{
  "abstract": [
    {
      "text": "The completion block for the Bluetooth picker.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.externalaccessory/documentation/ExternalAccessory"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.externalaccessory/documentation/ExternalAccessory/EABluetoothAccessoryPickerCompletion"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@T@EABluetoothAccessoryPickerCompletion",
    "fragments": [
      {
        "kind": "keyword",
        "text": "typealias"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "EABluetoothAccessoryPickerCompletion"
      }
    ],
    "modules": [
      {
        "name": "External Accessory"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "EABluetoothAccessoryPickerCompletion"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "3.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "3.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.0",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.13",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.0",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Type Alias",
    "symbolKind": "typealias",
    "title": "EABluetoothAccessoryPickerCompletion"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "typealias"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "EABluetoothAccessoryPickerCompletion"
            },
            {
              "kind": "text",
              "text": " = ((any "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:s5ErrorP",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:s5ErrorP",
              "text": "Error"
            },
            {
              "kind": "text",
              "text": ")?) -> "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:s4Voida",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:s4Voida",
              "text": "Void"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "You use this block to process results generated by the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.externalaccessory/documentation/ExternalAccessory/EAAccessoryManager/showBluetoothAccessoryPicker(withNameFilter:completion:)",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " method. The block receives an ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/foundation/nserror",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " object as its only parameter. If no error occurred, this parameter is set to ",
              "type": "text"
            },
            {
              "code": "nil",
              "type": "codeVoice"
            },
            {
              "text": ".",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/foundation/nserror": {
      "abstract": [
        {
          "text": "Information about an error condition including a domain, a domain-specific error code, and application-specific information.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "class "
        },
        {
          "kind": "identifier",
          "text": "NSError"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/foundation/nserror",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSError",
      "type": "topic",
      "url": "/documentation/foundation/nserror"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.externalaccessory/documentation/ExternalAccessory": {
      "abstract": [
        {
          "text": "Communicate with accessories that connect to a device with the Apple Lightning connector, or with Bluetooth wireless technology.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.externalaccessory/documentation/ExternalAccessory",
      "kind": "symbol",
      "role": "collection",
      "title": "External Accessory",
      "type": "topic",
      "url": "/documentation/externalaccessory"
    },
    "doc://com.apple.externalaccessory/documentation/ExternalAccessory/EAAccessoryManager/showBluetoothAccessoryPicker(withNameFilter:completion:)": {
      "abstract": [
        {
          "text": "Displays an alert that allows the user to pair the device with a Bluetooth accessory.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "showBluetoothAccessoryPicker"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "withNameFilter"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSPredicate",
          "text": "NSPredicate"
        },
        {
          "kind": "text",
          "text": "?, "
        },
        {
          "kind": "externalParam",
          "text": "completion"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@EABluetoothAccessoryPickerCompletion",
          "text": "EABluetoothAccessoryPickerCompletion"
        },
        {
          "kind": "text",
          "text": "?)"
        }
      ],
      "identifier": "doc://com.apple.externalaccessory/documentation/ExternalAccessory/EAAccessoryManager/showBluetoothAccessoryPicker(withNameFilter:completion:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "showBluetoothAccessoryPickerWithNameFilter:completion:"
        }
      ],
      "role": "symbol",
      "title": "showBluetoothAccessoryPicker(withNameFilter:completion:)",
      "type": "topic",
      "url": "/documentation/externalaccessory/eaaccessorymanager/showbluetoothaccessorypicker(withnamefilter:completion:)"
    },
    "doc://com.apple.externalaccessory/documentation/ExternalAccessory/EABluetoothAccessoryPickerCompletion": {
      "abstract": [
        {
          "text": "The completion block for the Bluetooth picker.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "EABluetoothAccessoryPickerCompletion"
        }
      ],
      "identifier": "doc://com.apple.externalaccessory/documentation/ExternalAccessory/EABluetoothAccessoryPickerCompletion",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "EABluetoothAccessoryPickerCompletion"
        }
      ],
      "role": "symbol",
      "title": "EABluetoothAccessoryPickerCompletion",
      "type": "topic",
      "url": "/documentation/externalaccessory/eabluetoothaccessorypickercompletion"
    },
    "doc://com.apple.externalaccessory/documentation/ExternalAccessory/EABluetoothAccessoryPickerError": {
      "abstract": [
        {
          "text": "Error codes returned by the Bluetooth accessory picker.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "EABluetoothAccessoryPickerError"
        }
      ],
      "identifier": "doc://com.apple.externalaccessory/documentation/ExternalAccessory/EABluetoothAccessoryPickerError",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "EABluetoothAccessoryPickerError"
        }
      ],
      "role": "symbol",
      "title": "EABluetoothAccessoryPickerError",
      "type": "topic",
      "url": "/documentation/externalaccessory/eabluetoothaccessorypickererror"
    },
    "doc://com.apple.externalaccessory/documentation/ExternalAccessory/EABluetoothAccessoryPickerError/Code": {
      "abstract": [
        {
          "text": "The error codes that may be passed in an error object for the Bluetooth picker completion block.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.externalaccessory/documentation/ExternalAccessory/EABluetoothAccessoryPickerError/Code",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "Code"
        }
      ],
      "role": "symbol",
      "title": "EABluetoothAccessoryPickerError.Code",
      "type": "topic",
      "url": "/documentation/externalaccessory/eabluetoothaccessorypickererror/code"
    },
    "doc://com.apple.externalaccessory/documentation/ExternalAccessory/EABluetoothAccessoryPickerErrorDomain": {
      "abstract": [
        {
          "text": "The domain for errors passed to a Bluetooth picker completion block.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "EABluetoothAccessoryPickerErrorDomain"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.externalaccessory/documentation/ExternalAccessory/EABluetoothAccessoryPickerErrorDomain",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "EABluetoothAccessoryPickerErrorDomain"
        }
      ],
      "role": "symbol",
      "title": "EABluetoothAccessoryPickerErrorDomain",
      "type": "topic",
      "url": "/documentation/externalaccessory/eabluetoothaccessorypickererrordomain"
    },
    "doc://com.externally.resolved.symbol/s:s4Voida": {
      "abstract": [
        {
          "text": "The return type of functions that don’t explicitly specify a return type, that is, an empty tuple `()`.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Void"
        },
        {
          "kind": "text",
          "text": " = ()"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s4Voida",
      "kind": "symbol",
      "role": "symbol",
      "title": "Void",
      "type": "topic",
      "url": "/documentation/Swift/Void"
    },
    "doc://com.externally.resolved.symbol/s:s5ErrorP": {
      "abstract": [
        {
          "text": "A type representing an error value that can be thrown.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Error"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s8SendableP",
          "text": "Sendable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s5ErrorP",
      "kind": "symbol",
      "role": "symbol",
      "title": "Error",
      "type": "topic",
      "url": "/documentation/Swift/Error"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Presenting-the-Bluetooth-Picker",
      "generated": true,
      "identifiers": [
        "doc://com.apple.externalaccessory/documentation/ExternalAccessory/EAAccessoryManager/showBluetoothAccessoryPicker(withNameFilter:completion:)",
        "doc://com.apple.externalaccessory/documentation/ExternalAccessory/EABluetoothAccessoryPickerError",
        "doc://com.apple.externalaccessory/documentation/ExternalAccessory/EABluetoothAccessoryPickerError/Code",
        "doc://com.apple.externalaccessory/documentation/ExternalAccessory/EABluetoothAccessoryPickerErrorDomain"
      ],
      "title": "Presenting the Bluetooth Picker"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "3.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "3.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.0",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.13",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.0",
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Type Alias"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "EABluetoothAccessoryPickerCompletion"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "typealias"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "EABluetoothAccessoryPickerCompletion"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "EABluetoothAccessoryPickerCompletion"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.externalaccessory/documentation/ExternalAccessory"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Presenting-the-Bluetooth-Picker",
              "generated": true,
              "identifiers": [
                "doc://com.apple.externalaccessory/documentation/ExternalAccessory/EAAccessoryManager/showBluetoothAccessoryPicker(withNameFilter:completion:)",
                "doc://com.apple.externalaccessory/documentation/ExternalAccessory/EABluetoothAccessoryPickerError/Code",
                "doc://com.apple.externalaccessory/documentation/ExternalAccessory/EABluetoothAccessoryPickerErrorDomain"
              ],
              "title": "Presenting the Bluetooth Picker"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "typedef"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:BFv(#*$objc(cs)NSError)",
                    "text": "void (^)(NSError *)"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "EABluetoothAccessoryPickerCompletion"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.externalaccessory~1documentation~1ExternalAccessory~1EAAccessoryManager~1showBluetoothAccessoryPicker(withNameFilter:completion:)/title",
          "value": "showBluetoothAccessoryPickerWithNameFilter:completion:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.externalaccessory~1documentation~1ExternalAccessory~1EAAccessoryManager~1showBluetoothAccessoryPicker(withNameFilter:completion:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "showBluetoothAccessoryPickerWithNameFilter:completion:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.externalaccessory~1documentation~1ExternalAccessory~1EABluetoothAccessoryPickerErrorDomain/title",
          "value": "EABluetoothAccessoryPickerErrorDomain"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.externalaccessory~1documentation~1ExternalAccessory~1EABluetoothAccessoryPickerErrorDomain/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "EABluetoothAccessoryPickerErrorDomain"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.externalaccessory~1documentation~1ExternalAccessory~1EABluetoothAccessoryPickerCompletion/title",
          "value": "EABluetoothAccessoryPickerCompletion"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.externalaccessory~1documentation~1ExternalAccessory~1EABluetoothAccessoryPickerCompletion/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "EABluetoothAccessoryPickerCompletion"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.externalaccessory~1documentation~1ExternalAccessory~1EABluetoothAccessoryPickerCompletion/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "EABluetoothAccessoryPickerCompletion"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.externalaccessory~1documentation~1ExternalAccessory~1EABluetoothAccessoryPickerError~1Code/title",
          "value": "EABluetoothAccessoryPickerErrorCode"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.externalaccessory~1documentation~1ExternalAccessory~1EABluetoothAccessoryPickerError~1Code/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "EABluetoothAccessoryPickerErrorCode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.externalaccessory~1documentation~1ExternalAccessory~1EABluetoothAccessoryPickerError~1Code/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "EABluetoothAccessoryPickerErrorCode"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/externalaccessory/eabluetoothaccessorypickercompletion"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/externalaccessory/eabluetoothaccessorypickercompletion"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
