{
  "abstract": [
    {
      "text": "Matches when a media item’s value for a given property is equal to the value in the media property predicate.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.mediaplayer/documentation/MediaPlayer",
        "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMediaPredicateComparison"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMediaPredicateComparison/equalTo"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@MPMediaPredicateComparison@MPMediaPredicateComparisonEqualTo",
    "fragments": [
      {
        "kind": "keyword",
        "text": "case"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "equalTo"
      }
    ],
    "modules": [
      {
        "name": "Media Player"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "MPMediaPredicateComparisonEqualTo"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "3.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "3.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.1",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Case",
    "symbolKind": "case",
    "title": "MPMediaPredicateComparison.equalTo"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "case"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "equalTo"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.mediaplayer/documentation/MediaPlayer": {
      "abstract": [
        {
          "text": "Find and play songs, audio podcasts, audio books, and more from within your app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.mediaplayer/documentation/MediaPlayer",
      "kind": "symbol",
      "role": "collection",
      "title": "Media Player",
      "type": "topic",
      "url": "/documentation/mediaplayer"
    },
    "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMediaPredicateComparison": {
      "abstract": [
        {
          "text": "Logical comparison types for media queries.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MPMediaPredicateComparison"
        }
      ],
      "identifier": "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMediaPredicateComparison",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MPMediaPredicateComparison"
        }
      ],
      "role": "symbol",
      "title": "MPMediaPredicateComparison",
      "type": "topic",
      "url": "/documentation/mediaplayer/mpmediapredicatecomparison"
    },
    "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMediaPredicateComparison/contains": {
      "abstract": [
        {
          "text": "Matches when a media item’s value for a given property is contained in the value of the media property predicate.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "contains"
        }
      ],
      "identifier": "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMediaPredicateComparison/contains",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MPMediaPredicateComparisonContains"
        }
      ],
      "role": "symbol",
      "title": "MPMediaPredicateComparison.contains",
      "type": "topic",
      "url": "/documentation/mediaplayer/mpmediapredicatecomparison/contains"
    },
    "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMediaPredicateComparison/equalTo": {
      "abstract": [
        {
          "text": "Matches when a media item’s value for a given property is equal to the value in the media property predicate.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "equalTo"
        }
      ],
      "identifier": "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMediaPredicateComparison/equalTo",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MPMediaPredicateComparisonEqualTo"
        }
      ],
      "role": "symbol",
      "title": "MPMediaPredicateComparison.equalTo",
      "type": "topic",
      "url": "/documentation/mediaplayer/mpmediapredicatecomparison/equalto"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Constants",
      "generated": true,
      "identifiers": [
        "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMediaPredicateComparison/contains"
      ],
      "title": "Constants"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "3.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "3.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.1",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration Case"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "MPMediaPredicateComparisonEqualTo"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "case"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MPMediaPredicateComparisonEqualTo"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.mediaplayer/documentation/MediaPlayer",
                "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMediaPredicateComparison"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Constants",
              "generated": true,
              "identifiers": [
                "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMediaPredicateComparison/contains"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "identifier",
                    "text": "MPMediaPredicateComparisonEqualTo"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaplayer~1documentation~1MediaPlayer~1MPMediaPredicateComparison~1equalTo/title",
          "value": "MPMediaPredicateComparisonEqualTo"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaplayer~1documentation~1MediaPlayer~1MPMediaPredicateComparison~1equalTo/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MPMediaPredicateComparisonEqualTo"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaplayer~1documentation~1MediaPlayer~1MPMediaPredicateComparison/title",
          "value": "MPMediaPredicateComparison"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaplayer~1documentation~1MediaPlayer~1MPMediaPredicateComparison/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MPMediaPredicateComparison"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaplayer~1documentation~1MediaPlayer~1MPMediaPredicateComparison/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MPMediaPredicateComparison"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaplayer~1documentation~1MediaPlayer~1MPMediaPredicateComparison~1contains/title",
          "value": "MPMediaPredicateComparisonContains"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaplayer~1documentation~1MediaPlayer~1MPMediaPredicateComparison~1contains/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MPMediaPredicateComparisonContains"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/mediaplayer/mpmediapredicatecomparison/equalto"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/mediaplayer/mpmediapredicatecomparison/equalto"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
