{
  "abstract": [
    {
      "text": "A possible diagnosis for limited position-tracking quality as of when the camera captured a frame.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.arkit/documentation/ARKit",
        "doc://com.apple.arkit/documentation/ARKit/ARCamera"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "occ",
    "url": "doc://com.apple.arkit/documentation/ARKit/ARCamera/trackingStateReason"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(cs)ARCamera(py)trackingStateReason",
    "fragments": [
      {
        "kind": "identifier",
        "text": "trackingStateReason"
      }
    ],
    "modules": [
      {
        "name": "ARKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "trackingStateReason"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "11.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "11.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.1",
        "name": "Mac Catalyst",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Instance Property",
    "symbolKind": "property",
    "title": "trackingStateReason"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "occ"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "@property"
            },
            {
              "kind": "text",
              "text": " ("
            },
            {
              "kind": "keyword",
              "text": "nonatomic"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "kind": "keyword",
              "text": "readonly"
            },
            {
              "kind": "text",
              "text": ") "
            },
            {
              "identifier": "doc://com.apple.arkit/documentation/ARKit/ARTrackingStateReason",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@E@ARTrackingStateReason",
              "text": "ARTrackingStateReason"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "trackingStateReason"
            },
            {
              "kind": "text",
              "text": ";"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.arkit/documentation/ARKit": {
      "abstract": [
        {
          "text": "Integrate hardware sensing features to produce augmented reality apps and games.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.arkit/documentation/ARKit",
      "kind": "symbol",
      "role": "collection",
      "title": "ARKit",
      "type": "topic",
      "url": "/documentation/arkit"
    },
    "doc://com.apple.arkit/documentation/ARKit/ARCamera": {
      "abstract": [
        {
          "text": "Information about the camera position and imaging characteristics for a given frame.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ARCamera"
        }
      ],
      "identifier": "doc://com.apple.arkit/documentation/ARKit/ARCamera",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ARCamera"
        }
      ],
      "role": "symbol",
      "title": "ARCamera",
      "type": "topic",
      "url": "/documentation/arkit/arcamera"
    },
    "doc://com.apple.arkit/documentation/ARKit/ARCamera/trackingState-9pgmq": {
      "abstract": [
        {
          "text": "The general quality of position tracking available when the camera captured a frame.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "trackingState"
        }
      ],
      "identifier": "doc://com.apple.arkit/documentation/ARKit/ARCamera/trackingState-9pgmq",
      "kind": "symbol",
      "role": "symbol",
      "title": "trackingState",
      "type": "topic",
      "url": "/documentation/arkit/arcamera/trackingstate-9pgmq"
    },
    "doc://com.apple.arkit/documentation/ARKit/ARCamera/trackingStateReason": {
      "abstract": [
        {
          "text": "A possible diagnosis for limited position-tracking quality as of when the camera captured a frame.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "trackingStateReason"
        }
      ],
      "identifier": "doc://com.apple.arkit/documentation/ARKit/ARCamera/trackingStateReason",
      "kind": "symbol",
      "role": "symbol",
      "title": "trackingStateReason",
      "type": "topic",
      "url": "/documentation/arkit/arcamera/trackingstatereason"
    },
    "doc://com.apple.arkit/documentation/ARKit/ARTrackingState": {
      "abstract": [
        {
          "text": "Possible values for position-tracking quality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "ARTrackingState"
        }
      ],
      "identifier": "doc://com.apple.arkit/documentation/ARKit/ARTrackingState",
      "kind": "symbol",
      "role": "symbol",
      "title": "ARTrackingState",
      "type": "topic",
      "url": "/documentation/arkit/artrackingstate"
    },
    "doc://com.apple.arkit/documentation/ARKit/ARTrackingStateReason": {
      "abstract": [
        {
          "text": "Possible causes for limited position-tracking quality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "ARTrackingStateReason"
        }
      ],
      "identifier": "doc://com.apple.arkit/documentation/ARKit/ARTrackingStateReason",
      "kind": "symbol",
      "role": "symbol",
      "title": "ARTrackingStateReason",
      "type": "topic",
      "url": "/documentation/arkit/artrackingstatereason"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Handling-Tracking-Status",
      "generated": true,
      "identifiers": [
        "doc://com.apple.arkit/documentation/ARKit/ARCamera/trackingState-9pgmq",
        "doc://com.apple.arkit/documentation/ARKit/ARTrackingState",
        "doc://com.apple.arkit/documentation/ARKit/ARTrackingStateReason"
      ],
      "title": "Handling Tracking Status"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.arkit~1documentation~1ARKit~1ARCamera/title",
          "value": "ARCamera"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.arkit~1documentation~1ARKit~1ARCamera/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ARCamera"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.arkit~1documentation~1ARKit~1ARCamera/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "ARCamera"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/arkit/arcamera/trackingstatereason"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
