{
  "abstract": [
    {
      "text": "Indicates that the session isn’t running and the output isn’t ready to receive requests.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.avfoundation/documentation/AVFoundation",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVCapturePhotoOutput",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVCapturePhotoOutput/CaptureReadiness-swift.enum"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.avfoundation/documentation/AVFoundation/AVCapturePhotoOutput/CaptureReadiness-swift.enum/sessionNotRunning"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@AVCapturePhotoOutputCaptureReadiness@AVCapturePhotoOutputCaptureReadinessSessionNotRunning",
    "fragments": [
      {
        "kind": "keyword",
        "text": "case"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "sessionNotRunning"
      }
    ],
    "modules": [
      {
        "name": "AVFoundation"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "AVCapturePhotoOutputCaptureReadinessSessionNotRunning"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "17.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "17.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "17.0",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "14.0",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "17.0",
        "name": "tvOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Case",
    "symbolKind": "case",
    "title": "AVCapturePhotoOutput.CaptureReadiness.sessionNotRunning"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "case"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "sessionNotRunning"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.avfoundation/documentation/AVFoundation": {
      "abstract": [
        {
          "text": "Work with audiovisual assets, control device cameras, process audio, and configure system audio interactions.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation",
      "kind": "symbol",
      "role": "collection",
      "title": "AVFoundation",
      "type": "topic",
      "url": "/documentation/avfoundation"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVCapturePhotoOutput": {
      "abstract": [
        {
          "text": "A capture output for still image, Live Photos, and other photography workflows.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AVCapturePhotoOutput"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVCapturePhotoOutput",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVCapturePhotoOutput"
        }
      ],
      "role": "symbol",
      "title": "AVCapturePhotoOutput",
      "type": "topic",
      "url": "/documentation/avfoundation/avcapturephotooutput"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVCapturePhotoOutput/CaptureReadiness-swift.enum": {
      "abstract": [
        {
          "text": "Constants that indicate whether the output is ready to receive capture requests.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CaptureReadiness"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVCapturePhotoOutput/CaptureReadiness-swift.enum",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CaptureReadiness"
        }
      ],
      "role": "symbol",
      "title": "AVCapturePhotoOutput.CaptureReadiness",
      "type": "topic",
      "url": "/documentation/avfoundation/avcapturephotooutput/capturereadiness-swift.enum"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVCapturePhotoOutput/CaptureReadiness-swift.enum/notReadyMomentarily": {
      "abstract": [
        {
          "text": "Indicates that the output isn’t ready to receive requests, but may be ready shortly.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "notReadyMomentarily"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVCapturePhotoOutput/CaptureReadiness-swift.enum/notReadyMomentarily",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVCapturePhotoOutputCaptureReadinessNotReadyMomentarily"
        }
      ],
      "role": "symbol",
      "title": "AVCapturePhotoOutput.CaptureReadiness.notReadyMomentarily",
      "type": "topic",
      "url": "/documentation/avfoundation/avcapturephotooutput/capturereadiness-swift.enum/notreadymomentarily"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVCapturePhotoOutput/CaptureReadiness-swift.enum/notReadyWaitingForCapture": {
      "abstract": [
        {
          "text": "Indicates that the output isn’t ready to receive requests for a longer duration because it’s busy capturing.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "notReadyWaitingForCapture"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVCapturePhotoOutput/CaptureReadiness-swift.enum/notReadyWaitingForCapture",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVCapturePhotoOutputCaptureReadinessNotReadyWaitingForCapture"
        }
      ],
      "role": "symbol",
      "title": "AVCapturePhotoOutput.CaptureReadiness.notReadyWaitingForCapture",
      "type": "topic",
      "url": "/documentation/avfoundation/avcapturephotooutput/capturereadiness-swift.enum/notreadywaitingforcapture"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVCapturePhotoOutput/CaptureReadiness-swift.enum/notReadyWaitingForProcessing": {
      "abstract": [
        {
          "text": "Indicates that the output isn’t ready to receive requests for a longer duration because it’s busy processing.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "notReadyWaitingForProcessing"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVCapturePhotoOutput/CaptureReadiness-swift.enum/notReadyWaitingForProcessing",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVCapturePhotoOutputCaptureReadinessNotReadyWaitingForProcessing"
        }
      ],
      "role": "symbol",
      "title": "AVCapturePhotoOutput.CaptureReadiness.notReadyWaitingForProcessing",
      "type": "topic",
      "url": "/documentation/avfoundation/avcapturephotooutput/capturereadiness-swift.enum/notreadywaitingforprocessing"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVCapturePhotoOutput/CaptureReadiness-swift.enum/ready": {
      "abstract": [
        {
          "text": "Indicates that the output is ready to receive new requests.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ready"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVCapturePhotoOutput/CaptureReadiness-swift.enum/ready",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVCapturePhotoOutputCaptureReadinessReady"
        }
      ],
      "role": "symbol",
      "title": "AVCapturePhotoOutput.CaptureReadiness.ready",
      "type": "topic",
      "url": "/documentation/avfoundation/avcapturephotooutput/capturereadiness-swift.enum/ready"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVCapturePhotoOutput/CaptureReadiness-swift.enum/sessionNotRunning": {
      "abstract": [
        {
          "text": "Indicates that the session isn’t running and the output isn’t ready to receive requests.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "sessionNotRunning"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVCapturePhotoOutput/CaptureReadiness-swift.enum/sessionNotRunning",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVCapturePhotoOutputCaptureReadinessSessionNotRunning"
        }
      ],
      "role": "symbol",
      "title": "AVCapturePhotoOutput.CaptureReadiness.sessionNotRunning",
      "type": "topic",
      "url": "/documentation/avfoundation/avcapturephotooutput/capturereadiness-swift.enum/sessionnotrunning"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Readiness-states",
      "generated": true,
      "identifiers": [
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVCapturePhotoOutput/CaptureReadiness-swift.enum/notReadyMomentarily",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVCapturePhotoOutput/CaptureReadiness-swift.enum/notReadyWaitingForCapture",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVCapturePhotoOutput/CaptureReadiness-swift.enum/notReadyWaitingForProcessing",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVCapturePhotoOutput/CaptureReadiness-swift.enum/ready"
      ],
      "title": "Readiness states"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "17.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "17.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "17.0",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "14.0",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "17.0",
              "name": "tvOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration Case"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "AVCapturePhotoOutputCaptureReadinessSessionNotRunning"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "case"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVCapturePhotoOutputCaptureReadinessSessionNotRunning"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.avfoundation/documentation/AVFoundation",
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVCapturePhotoOutput/CaptureReadiness-swift.enum"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Readiness-states",
              "generated": true,
              "identifiers": [
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVCapturePhotoOutput/CaptureReadiness-swift.enum/notReadyMomentarily",
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVCapturePhotoOutput/CaptureReadiness-swift.enum/notReadyWaitingForCapture",
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVCapturePhotoOutput/CaptureReadiness-swift.enum/notReadyWaitingForProcessing",
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVCapturePhotoOutput/CaptureReadiness-swift.enum/ready"
              ],
              "title": "Readiness states"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "identifier",
                    "text": "AVCapturePhotoOutputCaptureReadinessSessionNotRunning"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCapturePhotoOutput~1CaptureReadiness-swift.enum~1notReadyWaitingForCapture/title",
          "value": "AVCapturePhotoOutputCaptureReadinessNotReadyWaitingForCapture"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCapturePhotoOutput~1CaptureReadiness-swift.enum~1notReadyWaitingForCapture/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVCapturePhotoOutputCaptureReadinessNotReadyWaitingForCapture"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCapturePhotoOutput~1CaptureReadiness-swift.enum~1notReadyMomentarily/title",
          "value": "AVCapturePhotoOutputCaptureReadinessNotReadyMomentarily"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCapturePhotoOutput~1CaptureReadiness-swift.enum~1notReadyMomentarily/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVCapturePhotoOutputCaptureReadinessNotReadyMomentarily"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCapturePhotoOutput~1CaptureReadiness-swift.enum~1ready/title",
          "value": "AVCapturePhotoOutputCaptureReadinessReady"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCapturePhotoOutput~1CaptureReadiness-swift.enum~1ready/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVCapturePhotoOutputCaptureReadinessReady"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCapturePhotoOutput/title",
          "value": "AVCapturePhotoOutput"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCapturePhotoOutput/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVCapturePhotoOutput"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCapturePhotoOutput/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AVCapturePhotoOutput"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCapturePhotoOutput~1CaptureReadiness-swift.enum/title",
          "value": "AVCapturePhotoOutputCaptureReadiness"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCapturePhotoOutput~1CaptureReadiness-swift.enum/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVCapturePhotoOutputCaptureReadiness"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCapturePhotoOutput~1CaptureReadiness-swift.enum/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AVCapturePhotoOutputCaptureReadiness"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCapturePhotoOutput~1CaptureReadiness-swift.enum~1notReadyWaitingForProcessing/title",
          "value": "AVCapturePhotoOutputCaptureReadinessNotReadyWaitingForProcessing"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCapturePhotoOutput~1CaptureReadiness-swift.enum~1notReadyWaitingForProcessing/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVCapturePhotoOutputCaptureReadinessNotReadyWaitingForProcessing"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCapturePhotoOutput~1CaptureReadiness-swift.enum~1sessionNotRunning/title",
          "value": "AVCapturePhotoOutputCaptureReadinessSessionNotRunning"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCapturePhotoOutput~1CaptureReadiness-swift.enum~1sessionNotRunning/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVCapturePhotoOutputCaptureReadinessSessionNotRunning"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/avfoundation/avcapturephotooutput/capturereadiness-swift.enum/sessionnotrunning"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/avfoundation/avcapturephotooutput/capturereadiness-swift.enum/sessionnotrunning"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
