{
  "abstract": [
    {
      "text": "A constant that indicates the network was unavailable or a network error occurred.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.corelocation/documentation/CoreLocation",
        "doc://com.apple.corelocation/documentation/CoreLocation/CLError-swift.struct",
        "doc://com.apple.corelocation/documentation/CoreLocation/CLError-swift.struct/Code"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.corelocation/documentation/CoreLocation/CLError-swift.struct/Code/network"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@CLError@kCLErrorNetwork",
    "fragments": [
      {
        "kind": "keyword",
        "text": "case"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "network"
      }
    ],
    "modules": [
      {
        "name": "Core Location"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "kCLErrorNetwork"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "2.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "2.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.0",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.6",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "9.0",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "2.0",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Case",
    "symbolKind": "case",
    "title": "CLError.Code.network"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "case"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "network"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.corelocation/documentation/CoreLocation": {
      "abstract": [
        {
          "text": "Obtain the geographic location and orientation of a device.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.corelocation/documentation/CoreLocation",
      "kind": "symbol",
      "role": "collection",
      "title": "Core Location",
      "type": "topic",
      "url": "/documentation/corelocation"
    },
    "doc://com.apple.corelocation/documentation/CoreLocation/CLError-swift.struct": {
      "abstract": [
        {
          "text": "A Core Location error.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CLError"
        }
      ],
      "identifier": "doc://com.apple.corelocation/documentation/CoreLocation/CLError-swift.struct",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CLError"
        }
      ],
      "role": "symbol",
      "title": "CLError",
      "type": "topic",
      "url": "/documentation/corelocation/clerror-swift.struct"
    },
    "doc://com.apple.corelocation/documentation/CoreLocation/CLError-swift.struct/Code": {
      "abstract": [
        {
          "text": "Error codes returned by the location manager object.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.corelocation/documentation/CoreLocation/CLError-swift.struct/Code",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "Code"
        }
      ],
      "role": "symbol",
      "title": "CLError.Code",
      "type": "topic",
      "url": "/documentation/corelocation/clerror-swift.struct/code"
    },
    "doc://com.apple.corelocation/documentation/CoreLocation/CLError-swift.struct/Code/denied": {
      "abstract": [
        {
          "text": "A constant that indicates the user denied access to the location service.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "denied"
        }
      ],
      "identifier": "doc://com.apple.corelocation/documentation/CoreLocation/CLError-swift.struct/Code/denied",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCLErrorDenied"
        }
      ],
      "role": "symbol",
      "title": "CLError.Code.denied",
      "type": "topic",
      "url": "/documentation/corelocation/clerror-swift.struct/code/denied"
    },
    "doc://com.apple.corelocation/documentation/CoreLocation/CLError-swift.struct/Code/headingFailure": {
      "abstract": [
        {
          "text": "A constant that indicates the location manager can’t determine the heading.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "headingFailure"
        }
      ],
      "identifier": "doc://com.apple.corelocation/documentation/CoreLocation/CLError-swift.struct/Code/headingFailure",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCLErrorHeadingFailure"
        }
      ],
      "role": "symbol",
      "title": "CLError.Code.headingFailure",
      "type": "topic",
      "url": "/documentation/corelocation/clerror-swift.struct/code/headingfailure"
    },
    "doc://com.apple.corelocation/documentation/CoreLocation/CLError-swift.struct/Code/locationUnknown": {
      "abstract": [
        {
          "text": "A constant that indicates the location manager was unable to obtain a location value right now.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "locationUnknown"
        }
      ],
      "identifier": "doc://com.apple.corelocation/documentation/CoreLocation/CLError-swift.struct/Code/locationUnknown",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCLErrorLocationUnknown"
        }
      ],
      "role": "symbol",
      "title": "CLError.Code.locationUnknown",
      "type": "topic",
      "url": "/documentation/corelocation/clerror-swift.struct/code/locationunknown"
    },
    "doc://com.apple.corelocation/documentation/CoreLocation/CLError-swift.struct/Code/network": {
      "abstract": [
        {
          "text": "A constant that indicates the network was unavailable or a network error occurred.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "network"
        }
      ],
      "identifier": "doc://com.apple.corelocation/documentation/CoreLocation/CLError-swift.struct/Code/network",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCLErrorNetwork"
        }
      ],
      "role": "symbol",
      "title": "CLError.Code.network",
      "type": "topic",
      "url": "/documentation/corelocation/clerror-swift.struct/code/network"
    },
    "doc://com.apple.corelocation/documentation/CoreLocation/CLError-swift.struct/Code/promptDeclined": {
      "abstract": [
        {
          "text": "A constant that indicates the user didn’t grant the requested temporary authorization.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "promptDeclined"
        }
      ],
      "identifier": "doc://com.apple.corelocation/documentation/CoreLocation/CLError-swift.struct/Code/promptDeclined",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCLErrorPromptDeclined"
        }
      ],
      "role": "symbol",
      "title": "CLError.Code.promptDeclined",
      "type": "topic",
      "url": "/documentation/corelocation/clerror-swift.struct/code/promptdeclined"
    },
    "doc://com.apple.corelocation/documentation/CoreLocation/CLError-swift.struct/Code/rangingFailure": {
      "abstract": [
        {
          "text": "A constant that indicates a general ranging error occurred.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "rangingFailure"
        }
      ],
      "identifier": "doc://com.apple.corelocation/documentation/CoreLocation/CLError-swift.struct/Code/rangingFailure",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCLErrorRangingFailure"
        }
      ],
      "role": "symbol",
      "title": "CLError.Code.rangingFailure",
      "type": "topic",
      "url": "/documentation/corelocation/clerror-swift.struct/code/rangingfailure"
    },
    "doc://com.apple.corelocation/documentation/CoreLocation/CLError-swift.struct/Code/rangingUnavailable": {
      "abstract": [
        {
          "text": "A constant that indicates ranging is disabled.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "rangingUnavailable"
        }
      ],
      "identifier": "doc://com.apple.corelocation/documentation/CoreLocation/CLError-swift.struct/Code/rangingUnavailable",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCLErrorRangingUnavailable"
        }
      ],
      "role": "symbol",
      "title": "CLError.Code.rangingUnavailable",
      "type": "topic",
      "url": "/documentation/corelocation/clerror-swift.struct/code/rangingunavailable"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Getting-general-errors",
      "generated": true,
      "identifiers": [
        "doc://com.apple.corelocation/documentation/CoreLocation/CLError-swift.struct/Code/locationUnknown",
        "doc://com.apple.corelocation/documentation/CoreLocation/CLError-swift.struct/Code/denied",
        "doc://com.apple.corelocation/documentation/CoreLocation/CLError-swift.struct/Code/promptDeclined",
        "doc://com.apple.corelocation/documentation/CoreLocation/CLError-swift.struct/Code/headingFailure",
        "doc://com.apple.corelocation/documentation/CoreLocation/CLError-swift.struct/Code/rangingUnavailable",
        "doc://com.apple.corelocation/documentation/CoreLocation/CLError-swift.struct/Code/rangingFailure"
      ],
      "title": "Getting general errors"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "2.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "2.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.0",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.6",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "9.0",
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "2.0",
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration Case"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "kCLErrorNetwork"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "case"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCLErrorNetwork"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.corelocation/documentation/CoreLocation",
                "doc://com.apple.corelocation/documentation/CoreLocation/CLError-swift.struct/Code"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Getting-general-errors",
              "generated": true,
              "identifiers": [
                "doc://com.apple.corelocation/documentation/CoreLocation/CLError-swift.struct/Code/locationUnknown",
                "doc://com.apple.corelocation/documentation/CoreLocation/CLError-swift.struct/Code/denied",
                "doc://com.apple.corelocation/documentation/CoreLocation/CLError-swift.struct/Code/promptDeclined",
                "doc://com.apple.corelocation/documentation/CoreLocation/CLError-swift.struct/Code/headingFailure",
                "doc://com.apple.corelocation/documentation/CoreLocation/CLError-swift.struct/Code/rangingUnavailable",
                "doc://com.apple.corelocation/documentation/CoreLocation/CLError-swift.struct/Code/rangingFailure"
              ],
              "title": "Getting general errors"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "identifier",
                    "text": "kCLErrorNetwork"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corelocation~1documentation~1CoreLocation~1CLError-swift.struct~1Code~1rangingUnavailable/title",
          "value": "kCLErrorRangingUnavailable"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corelocation~1documentation~1CoreLocation~1CLError-swift.struct~1Code~1rangingUnavailable/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCLErrorRangingUnavailable"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corelocation~1documentation~1CoreLocation~1CLError-swift.struct~1Code~1rangingFailure/title",
          "value": "kCLErrorRangingFailure"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corelocation~1documentation~1CoreLocation~1CLError-swift.struct~1Code~1rangingFailure/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCLErrorRangingFailure"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corelocation~1documentation~1CoreLocation~1CLError-swift.struct~1Code~1headingFailure/title",
          "value": "kCLErrorHeadingFailure"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corelocation~1documentation~1CoreLocation~1CLError-swift.struct~1Code~1headingFailure/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCLErrorHeadingFailure"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corelocation~1documentation~1CoreLocation~1CLError-swift.struct~1Code/title",
          "value": "CLError"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corelocation~1documentation~1CoreLocation~1CLError-swift.struct~1Code/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CLError"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corelocation~1documentation~1CoreLocation~1CLError-swift.struct~1Code/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CLError"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corelocation~1documentation~1CoreLocation~1CLError-swift.struct~1Code~1network/title",
          "value": "kCLErrorNetwork"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corelocation~1documentation~1CoreLocation~1CLError-swift.struct~1Code~1network/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCLErrorNetwork"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corelocation~1documentation~1CoreLocation~1CLError-swift.struct~1Code~1locationUnknown/title",
          "value": "kCLErrorLocationUnknown"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corelocation~1documentation~1CoreLocation~1CLError-swift.struct~1Code~1locationUnknown/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCLErrorLocationUnknown"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corelocation~1documentation~1CoreLocation~1CLError-swift.struct~1Code~1promptDeclined/title",
          "value": "kCLErrorPromptDeclined"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corelocation~1documentation~1CoreLocation~1CLError-swift.struct~1Code~1promptDeclined/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCLErrorPromptDeclined"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corelocation~1documentation~1CoreLocation~1CLError-swift.struct~1Code~1denied/title",
          "value": "kCLErrorDenied"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corelocation~1documentation~1CoreLocation~1CLError-swift.struct~1Code~1denied/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCLErrorDenied"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/corelocation/clerror-swift.struct/code/network"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/corelocation/clerror-swift.struct/code/network"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
