{
  "abstract": [
    {
      "text": "The error codes that CloudKit returns.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.cloudkit/documentation/CloudKit",
        "doc://com.apple.cloudkit/documentation/CloudKit/CKError"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.cloudkit/documentation/CloudKit/CKError/Code"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@CKErrorCode",
    "fragments": [
      {
        "kind": "keyword",
        "text": "enum"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "Code"
      }
    ],
    "modules": [
      {
        "name": "CloudKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "Code"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "8.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "8.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.1",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.10",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "3.0",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Enumeration",
    "symbolKind": "enum",
    "title": "CKError.Code"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "enum"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "Code"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.cloudkit/documentation/CloudKit": {
      "abstract": [
        {
          "text": "Store structured app and user data in iCloud containers that all users of your app can share.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.cloudkit/documentation/CloudKit",
      "kind": "symbol",
      "role": "collection",
      "title": "CloudKit",
      "type": "topic",
      "url": "/documentation/cloudkit"
    },
    "doc://com.apple.cloudkit/documentation/CloudKit/CKError": {
      "abstract": [
        {
          "text": "A type that describes a CloudKit error.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CKError"
        }
      ],
      "identifier": "doc://com.apple.cloudkit/documentation/CloudKit/CKError",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CKError"
        }
      ],
      "role": "symbol",
      "title": "CKError",
      "type": "topic",
      "url": "/documentation/cloudkit/ckerror"
    },
    "doc://com.apple.cloudkit/documentation/CloudKit/CKError/Code": {
      "abstract": [
        {
          "text": "The error codes that CloudKit returns.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.cloudkit/documentation/CloudKit/CKError/Code",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "Code"
        }
      ],
      "role": "symbol",
      "title": "CKError.Code",
      "type": "topic",
      "url": "/documentation/cloudkit/ckerror/code"
    },
    "doc://com.apple.cloudkit/documentation/CloudKit/CKError/Code/accountTemporarilyUnavailable": {
      "abstract": [
        {
          "text": "An error that occurs when the user’s iCloud account is temporarily unavailable.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "accountTemporarilyUnavailable"
        }
      ],
      "identifier": "doc://com.apple.cloudkit/documentation/CloudKit/CKError/Code/accountTemporarilyUnavailable",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CKErrorAccountTemporarilyUnavailable"
        }
      ],
      "role": "symbol",
      "title": "CKError.Code.accountTemporarilyUnavailable",
      "type": "topic",
      "url": "/documentation/cloudkit/ckerror/code/accounttemporarilyunavailable"
    },
    "doc://com.apple.cloudkit/documentation/CloudKit/CKError/Code/alreadyShared": {
      "abstract": [
        {
          "text": "An error that occurs when CloudKit attempts to share a record with an existing share.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "alreadyShared"
        }
      ],
      "identifier": "doc://com.apple.cloudkit/documentation/CloudKit/CKError/Code/alreadyShared",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CKErrorAlreadyShared"
        }
      ],
      "role": "symbol",
      "title": "CKError.Code.alreadyShared",
      "type": "topic",
      "url": "/documentation/cloudkit/ckerror/code/alreadyshared"
    },
    "doc://com.apple.cloudkit/documentation/CloudKit/CKError/Code/assetFileModified": {
      "abstract": [
        {
          "text": "An error that occurs when the system modifies an asset while saving it.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "assetFileModified"
        }
      ],
      "identifier": "doc://com.apple.cloudkit/documentation/CloudKit/CKError/Code/assetFileModified",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CKErrorAssetFileModified"
        }
      ],
      "role": "symbol",
      "title": "CKError.Code.assetFileModified",
      "type": "topic",
      "url": "/documentation/cloudkit/ckerror/code/assetfilemodified"
    },
    "doc://com.apple.cloudkit/documentation/CloudKit/CKError/Code/assetFileNotFound": {
      "abstract": [
        {
          "text": "An error that occurs when the system can’t find the specified asset.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "assetFileNotFound"
        }
      ],
      "identifier": "doc://com.apple.cloudkit/documentation/CloudKit/CKError/Code/assetFileNotFound",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CKErrorAssetFileNotFound"
        }
      ],
      "role": "symbol",
      "title": "CKError.Code.assetFileNotFound",
      "type": "topic",
      "url": "/documentation/cloudkit/ckerror/code/assetfilenotfound"
    },
    "doc://com.apple.cloudkit/documentation/CloudKit/CKError/Code/assetNotAvailable": {
      "abstract": [
        {
          "text": "An error that occurs when the system can’t access the specified asset.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "assetNotAvailable"
        }
      ],
      "identifier": "doc://com.apple.cloudkit/documentation/CloudKit/CKError/Code/assetNotAvailable",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CKErrorAssetNotAvailable"
        }
      ],
      "role": "symbol",
      "title": "CKError.Code.assetNotAvailable",
      "type": "topic",
      "url": "/documentation/cloudkit/ckerror/code/assetnotavailable"
    },
    "doc://com.apple.cloudkit/documentation/CloudKit/CKError/Code/badContainer": {
      "abstract": [
        {
          "text": "An error that occurs when you use an unknown or unauthorized container.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "badContainer"
        }
      ],
      "identifier": "doc://com.apple.cloudkit/documentation/CloudKit/CKError/Code/badContainer",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CKErrorBadContainer"
        }
      ],
      "role": "symbol",
      "title": "CKError.Code.badContainer",
      "type": "topic",
      "url": "/documentation/cloudkit/ckerror/code/badcontainer"
    },
    "doc://com.apple.cloudkit/documentation/CloudKit/CKError/Code/badDatabase": {
      "abstract": [
        {
          "text": "An error that occurs when the operation can’t complete for the specified database.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "badDatabase"
        }
      ],
      "identifier": "doc://com.apple.cloudkit/documentation/CloudKit/CKError/Code/badDatabase",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CKErrorBadDatabase"
        }
      ],
      "role": "symbol",
      "title": "CKError.Code.badDatabase",
      "type": "topic",
      "url": "/documentation/cloudkit/ckerror/code/baddatabase"
    },
    "doc://com.apple.cloudkit/documentation/CloudKit/CKError/Code/batchRequestFailed": {
      "abstract": [
        {
          "text": "An error that occurs when the system rejects the entire batch of changes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "batchRequestFailed"
        }
      ],
      "identifier": "doc://com.apple.cloudkit/documentation/CloudKit/CKError/Code/batchRequestFailed",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CKErrorBatchRequestFailed"
        }
      ],
      "role": "symbol",
      "title": "CKError.Code.batchRequestFailed",
      "type": "topic",
      "url": "/documentation/cloudkit/ckerror/code/batchrequestfailed"
    },
    "doc://com.apple.cloudkit/documentation/CloudKit/CKError/Code/changeTokenExpired": {
      "abstract": [
        {
          "text": "An error that occurs when the change token expires.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "changeTokenExpired"
        }
      ],
      "identifier": "doc://com.apple.cloudkit/documentation/CloudKit/CKError/Code/changeTokenExpired",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CKErrorChangeTokenExpired"
        }
      ],
      "role": "symbol",
      "title": "CKError.Code.changeTokenExpired",
      "type": "topic",
      "url": "/documentation/cloudkit/ckerror/code/changetokenexpired"
    },
    "doc://com.apple.cloudkit/documentation/CloudKit/CKError/Code/constraintViolation": {
      "abstract": [
        {
          "text": "An error that occurs when the server rejects the request because of a unique constraint violation.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "constraintViolation"
        }
      ],
      "identifier": "doc://com.apple.cloudkit/documentation/CloudKit/CKError/Code/constraintViolation",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CKErrorConstraintViolation"
        }
      ],
      "role": "symbol",
      "title": "CKError.Code.constraintViolation",
      "type": "topic",
      "url": "/documentation/cloudkit/ckerror/code/constraintviolation"
    },
    "doc://com.apple.cloudkit/documentation/CloudKit/CKError/Code/incompatibleVersion": {
      "abstract": [
        {
          "text": "An error that occurs when the current app version is older than the oldest allowed version.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "incompatibleVersion"
        }
      ],
      "identifier": "doc://com.apple.cloudkit/documentation/CloudKit/CKError/Code/incompatibleVersion",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CKErrorIncompatibleVersion"
        }
      ],
      "role": "symbol",
      "title": "CKError.Code.incompatibleVersion",
      "type": "topic",
      "url": "/documentation/cloudkit/ckerror/code/incompatibleversion"
    },
    "doc://com.apple.cloudkit/documentation/CloudKit/CKError/Code/init(rawValue:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "?("
        },
        {
          "kind": "externalParam",
          "text": "rawValue"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.cloudkit/documentation/CloudKit/CKError/Code/init(rawValue:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "init(rawValue:)",
      "type": "topic",
      "url": "/documentation/cloudkit/ckerror/code/init(rawvalue:)"
    },
    "doc://com.apple.cloudkit/documentation/CloudKit/CKError/Code/internalError": {
      "abstract": [
        {
          "text": "A nonrecoverable error that CloudKit encounters.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "internalError"
        }
      ],
      "identifier": "doc://com.apple.cloudkit/documentation/CloudKit/CKError/Code/internalError",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CKErrorInternalError"
        }
      ],
      "role": "symbol",
      "title": "CKError.Code.internalError",
      "type": "topic",
      "url": "/documentation/cloudkit/ckerror/code/internalerror"
    },
    "doc://com.apple.cloudkit/documentation/CloudKit/CKError/Code/invalidArguments": {
      "abstract": [
        {
          "text": "An error that occurs when the request contains invalid information.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "invalidArguments"
        }
      ],
      "identifier": "doc://com.apple.cloudkit/documentation/CloudKit/CKError/Code/invalidArguments",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CKErrorInvalidArguments"
        }
      ],
      "role": "symbol",
      "title": "CKError.Code.invalidArguments",
      "type": "topic",
      "url": "/documentation/cloudkit/ckerror/code/invalidarguments"
    },
    "doc://com.apple.cloudkit/documentation/CloudKit/CKError/Code/limitExceeded": {
      "abstract": [
        {
          "text": "An error that occurs when a request’s size exceeds the limit.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "limitExceeded"
        }
      ],
      "identifier": "doc://com.apple.cloudkit/documentation/CloudKit/CKError/Code/limitExceeded",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CKErrorLimitExceeded"
        }
      ],
      "role": "symbol",
      "title": "CKError.Code.limitExceeded",
      "type": "topic",
      "url": "/documentation/cloudkit/ckerror/code/limitexceeded"
    },
    "doc://com.apple.cloudkit/documentation/CloudKit/CKError/Code/managedAccountRestricted": {
      "abstract": [
        {
          "text": "An error that occurs when CloudKit rejects a request due to a managed-account restriction.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "managedAccountRestricted"
        }
      ],
      "identifier": "doc://com.apple.cloudkit/documentation/CloudKit/CKError/Code/managedAccountRestricted",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CKErrorManagedAccountRestricted"
        }
      ],
      "role": "symbol",
      "title": "CKError.Code.managedAccountRestricted",
      "type": "topic",
      "url": "/documentation/cloudkit/ckerror/code/managedaccountrestricted"
    },
    "doc://com.apple.cloudkit/documentation/CloudKit/CKError/Code/missingEntitlement": {
      "abstract": [
        {
          "text": "An error that occurs when the app is missing a required entitlement.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "missingEntitlement"
        }
      ],
      "identifier": "doc://com.apple.cloudkit/documentation/CloudKit/CKError/Code/missingEntitlement",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CKErrorMissingEntitlement"
        }
      ],
      "role": "symbol",
      "title": "CKError.Code.missingEntitlement",
      "type": "topic",
      "url": "/documentation/cloudkit/ckerror/code/missingentitlement"
    },
    "doc://com.apple.cloudkit/documentation/CloudKit/CKError/Code/networkFailure": {
      "abstract": [
        {
          "text": "An error that occurs when a network is available, but CloudKit is inaccessible.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "networkFailure"
        }
      ],
      "identifier": "doc://com.apple.cloudkit/documentation/CloudKit/CKError/Code/networkFailure",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CKErrorNetworkFailure"
        }
      ],
      "role": "symbol",
      "title": "CKError.Code.networkFailure",
      "type": "topic",
      "url": "/documentation/cloudkit/ckerror/code/networkfailure"
    },
    "doc://com.apple.cloudkit/documentation/CloudKit/CKError/Code/networkUnavailable": {
      "abstract": [
        {
          "text": "An error that occurs when the network is unavailable.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "networkUnavailable"
        }
      ],
      "identifier": "doc://com.apple.cloudkit/documentation/CloudKit/CKError/Code/networkUnavailable",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CKErrorNetworkUnavailable"
        }
      ],
      "role": "symbol",
      "title": "CKError.Code.networkUnavailable",
      "type": "topic",
      "url": "/documentation/cloudkit/ckerror/code/networkunavailable"
    },
    "doc://com.apple.cloudkit/documentation/CloudKit/CKError/Code/notAuthenticated": {
      "abstract": [
        {
          "text": "An error that occurs when the user is unauthenticated.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "notAuthenticated"
        }
      ],
      "identifier": "doc://com.apple.cloudkit/documentation/CloudKit/CKError/Code/notAuthenticated",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CKErrorNotAuthenticated"
        }
      ],
      "role": "symbol",
      "title": "CKError.Code.notAuthenticated",
      "type": "topic",
      "url": "/documentation/cloudkit/ckerror/code/notauthenticated"
    },
    "doc://com.apple.cloudkit/documentation/CloudKit/CKError/Code/operationCancelled": {
      "abstract": [
        {
          "text": "An error that occurs when an operation cancels.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "operationCancelled"
        }
      ],
      "identifier": "doc://com.apple.cloudkit/documentation/CloudKit/CKError/Code/operationCancelled",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CKErrorOperationCancelled"
        }
      ],
      "role": "symbol",
      "title": "CKError.Code.operationCancelled",
      "type": "topic",
      "url": "/documentation/cloudkit/ckerror/code/operationcancelled"
    },
    "doc://com.apple.cloudkit/documentation/CloudKit/CKError/Code/partialFailure": {
      "abstract": [
        {
          "text": "An error that occurs when an operation completes with partial failures.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "partialFailure"
        }
      ],
      "identifier": "doc://com.apple.cloudkit/documentation/CloudKit/CKError/Code/partialFailure",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CKErrorPartialFailure"
        }
      ],
      "role": "symbol",
      "title": "CKError.Code.partialFailure",
      "type": "topic",
      "url": "/documentation/cloudkit/ckerror/code/partialfailure"
    },
    "doc://com.apple.cloudkit/documentation/CloudKit/CKError/Code/participantMayNeedVerification": {
      "abstract": [
        {
          "text": "An error that occurs when the user isn’t a participant of the share.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "participantMayNeedVerification"
        }
      ],
      "identifier": "doc://com.apple.cloudkit/documentation/CloudKit/CKError/Code/participantMayNeedVerification",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CKErrorParticipantMayNeedVerification"
        }
      ],
      "role": "symbol",
      "title": "CKError.Code.participantMayNeedVerification",
      "type": "topic",
      "url": "/documentation/cloudkit/ckerror/code/participantmayneedverification"
    },
    "doc://com.apple.cloudkit/documentation/CloudKit/CKError/Code/permissionFailure": {
      "abstract": [
        {
          "text": "An error that occurs when the user doesn’t have permission to save or fetch data.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "permissionFailure"
        }
      ],
      "identifier": "doc://com.apple.cloudkit/documentation/CloudKit/CKError/Code/permissionFailure",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CKErrorPermissionFailure"
        }
      ],
      "role": "symbol",
      "title": "CKError.Code.permissionFailure",
      "type": "topic",
      "url": "/documentation/cloudkit/ckerror/code/permissionfailure"
    },
    "doc://com.apple.cloudkit/documentation/CloudKit/CKError/Code/quotaExceeded": {
      "abstract": [
        {
          "text": "An error that occurs when saving a record exceeds the user’s storage quota.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "quotaExceeded"
        }
      ],
      "identifier": "doc://com.apple.cloudkit/documentation/CloudKit/CKError/Code/quotaExceeded",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CKErrorQuotaExceeded"
        }
      ],
      "role": "symbol",
      "title": "CKError.Code.quotaExceeded",
      "type": "topic",
      "url": "/documentation/cloudkit/ckerror/code/quotaexceeded"
    },
    "doc://com.apple.cloudkit/documentation/CloudKit/CKError/Code/referenceViolation": {
      "abstract": [
        {
          "text": "An error that occurs when CloudKit can’t find the target of a reference.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "referenceViolation"
        }
      ],
      "identifier": "doc://com.apple.cloudkit/documentation/CloudKit/CKError/Code/referenceViolation",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CKErrorReferenceViolation"
        }
      ],
      "role": "symbol",
      "title": "CKError.Code.referenceViolation",
      "type": "topic",
      "url": "/documentation/cloudkit/ckerror/code/referenceviolation"
    },
    "doc://com.apple.cloudkit/documentation/CloudKit/CKError/Code/requestRateLimited": {
      "abstract": [
        {
          "text": "An error that occurs when CloudKit rate-limits requests.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "requestRateLimited"
        }
      ],
      "identifier": "doc://com.apple.cloudkit/documentation/CloudKit/CKError/Code/requestRateLimited",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CKErrorRequestRateLimited"
        }
      ],
      "role": "symbol",
      "title": "CKError.Code.requestRateLimited",
      "type": "topic",
      "url": "/documentation/cloudkit/ckerror/code/requestratelimited"
    },
    "doc://com.apple.cloudkit/documentation/CloudKit/CKError/Code/resultsTruncated": {
      "abstract": [
        {
          "text": "An error that occurs when CloudKit truncates a query’s results.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "resultsTruncated"
        }
      ],
      "identifier": "doc://com.apple.cloudkit/documentation/CloudKit/CKError/Code/resultsTruncated",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CKErrorResultsTruncated"
        }
      ],
      "role": "symbol",
      "title": "CKError.Code.resultsTruncated",
      "type": "topic",
      "url": "/documentation/cloudkit/ckerror/code/resultstruncated"
    },
    "doc://com.apple.cloudkit/documentation/CloudKit/CKError/Code/serverRecordChanged": {
      "abstract": [
        {
          "text": "An error that occurs when CloudKit rejects a record because the server’s version is different.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "serverRecordChanged"
        }
      ],
      "identifier": "doc://com.apple.cloudkit/documentation/CloudKit/CKError/Code/serverRecordChanged",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CKErrorServerRecordChanged"
        }
      ],
      "role": "symbol",
      "title": "CKError.Code.serverRecordChanged",
      "type": "topic",
      "url": "/documentation/cloudkit/ckerror/code/serverrecordchanged"
    },
    "doc://com.apple.cloudkit/documentation/CloudKit/CKError/Code/serverRejectedRequest": {
      "abstract": [
        {
          "text": "An error that occurs when CloudKit rejects the request.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "serverRejectedRequest"
        }
      ],
      "identifier": "doc://com.apple.cloudkit/documentation/CloudKit/CKError/Code/serverRejectedRequest",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CKErrorServerRejectedRequest"
        }
      ],
      "role": "symbol",
      "title": "CKError.Code.serverRejectedRequest",
      "type": "topic",
      "url": "/documentation/cloudkit/ckerror/code/serverrejectedrequest"
    },
    "doc://com.apple.cloudkit/documentation/CloudKit/CKError/Code/serverResponseLost": {
      "abstract": [
        {
          "text": "An error that occurs when CloudKit is unable to maintain the network connection and provide a response.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "serverResponseLost"
        }
      ],
      "identifier": "doc://com.apple.cloudkit/documentation/CloudKit/CKError/Code/serverResponseLost",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CKErrorServerResponseLost"
        }
      ],
      "role": "symbol",
      "title": "CKError.Code.serverResponseLost",
      "type": "topic",
      "url": "/documentation/cloudkit/ckerror/code/serverresponselost"
    },
    "doc://com.apple.cloudkit/documentation/CloudKit/CKError/Code/serviceUnavailable": {
      "abstract": [
        {
          "text": "An error that occurs when CloudKit is unavailable.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "serviceUnavailable"
        }
      ],
      "identifier": "doc://com.apple.cloudkit/documentation/CloudKit/CKError/Code/serviceUnavailable",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CKErrorServiceUnavailable"
        }
      ],
      "role": "symbol",
      "title": "CKError.Code.serviceUnavailable",
      "type": "topic",
      "url": "/documentation/cloudkit/ckerror/code/serviceunavailable"
    },
    "doc://com.apple.cloudkit/documentation/CloudKit/CKError/Code/tooManyParticipants": {
      "abstract": [
        {
          "text": "An error that occurs when a share has too many participants.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "tooManyParticipants"
        }
      ],
      "identifier": "doc://com.apple.cloudkit/documentation/CloudKit/CKError/Code/tooManyParticipants",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CKErrorTooManyParticipants"
        }
      ],
      "role": "symbol",
      "title": "CKError.Code.tooManyParticipants",
      "type": "topic",
      "url": "/documentation/cloudkit/ckerror/code/toomanyparticipants"
    },
    "doc://com.apple.cloudkit/documentation/CloudKit/CKError/Code/unknownItem": {
      "abstract": [
        {
          "text": "An error that occurs when the specified record doesn’t exist.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "unknownItem"
        }
      ],
      "identifier": "doc://com.apple.cloudkit/documentation/CloudKit/CKError/Code/unknownItem",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CKErrorUnknownItem"
        }
      ],
      "role": "symbol",
      "title": "CKError.Code.unknownItem",
      "type": "topic",
      "url": "/documentation/cloudkit/ckerror/code/unknownitem"
    },
    "doc://com.apple.cloudkit/documentation/CloudKit/CKError/Code/userDeletedZone": {
      "abstract": [
        {
          "text": "An error that occurs when the user deletes a record zone using the Settings app.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "userDeletedZone"
        }
      ],
      "identifier": "doc://com.apple.cloudkit/documentation/CloudKit/CKError/Code/userDeletedZone",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CKErrorUserDeletedZone"
        }
      ],
      "role": "symbol",
      "title": "CKError.Code.userDeletedZone",
      "type": "topic",
      "url": "/documentation/cloudkit/ckerror/code/userdeletedzone"
    },
    "doc://com.apple.cloudkit/documentation/CloudKit/CKError/Code/zoneBusy": {
      "abstract": [
        {
          "text": "An error that occurs when the server is too busy to handle the record zone operation.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "zoneBusy"
        }
      ],
      "identifier": "doc://com.apple.cloudkit/documentation/CloudKit/CKError/Code/zoneBusy",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CKErrorZoneBusy"
        }
      ],
      "role": "symbol",
      "title": "CKError.Code.zoneBusy",
      "type": "topic",
      "url": "/documentation/cloudkit/ckerror/code/zonebusy"
    },
    "doc://com.apple.cloudkit/documentation/CloudKit/CKError/Code/zoneNotFound": {
      "abstract": [
        {
          "text": "An error that occurs when the specified record zone doesn’t exist.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "zoneNotFound"
        }
      ],
      "identifier": "doc://com.apple.cloudkit/documentation/CloudKit/CKError/Code/zoneNotFound",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CKErrorZoneNotFound"
        }
      ],
      "role": "symbol",
      "title": "CKError.Code.zoneNotFound",
      "type": "topic",
      "url": "/documentation/cloudkit/ckerror/code/zonenotfound"
    },
    "doc://com.apple.cloudkit/documentation/CloudKit/CKErrorDomain": {
      "abstract": [
        {
          "text": "The error domain for CloudKit errors.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CKErrorDomain"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.cloudkit/documentation/CloudKit/CKErrorDomain",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CKErrorDomain"
        }
      ],
      "role": "symbol",
      "title": "CKErrorDomain",
      "type": "topic",
      "url": "/documentation/cloudkit/ckerrordomain"
    },
    "doc://com.apple.cloudkit/documentation/CloudKit/CKErrorRetryAfterKey": {
      "abstract": [
        {
          "text": "The key to retrieve the number of seconds to wait before you retry a request.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CKErrorRetryAfterKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.cloudkit/documentation/CloudKit/CKErrorRetryAfterKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CKErrorRetryAfterKey"
        }
      ],
      "role": "symbol",
      "title": "CKErrorRetryAfterKey",
      "type": "topic",
      "url": "/documentation/cloudkit/ckerrorretryafterkey"
    },
    "doc://com.apple.cloudkit/documentation/CloudKit/CKErrorUserDidResetEncryptedDataKey": {
      "abstract": [
        {
          "text": "The key that determines whether CloudKit deletes a record zone because of a user action.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CKErrorUserDidResetEncryptedDataKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.cloudkit/documentation/CloudKit/CKErrorUserDidResetEncryptedDataKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CKErrorUserDidResetEncryptedDataKey"
        }
      ],
      "role": "symbol",
      "title": "CKErrorUserDidResetEncryptedDataKey",
      "type": "topic",
      "url": "/documentation/cloudkit/ckerroruserdidresetencrypteddatakey"
    },
    "doc://com.apple.cloudkit/documentation/CloudKit/CKPartialErrorsByItemIDKey": {
      "abstract": [
        {
          "text": "The key to retrieve partial errors.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CKPartialErrorsByItemIDKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.cloudkit/documentation/CloudKit/CKPartialErrorsByItemIDKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CKPartialErrorsByItemIDKey"
        }
      ],
      "role": "symbol",
      "title": "CKPartialErrorsByItemIDKey",
      "type": "topic",
      "url": "/documentation/cloudkit/ckpartialerrorsbyitemidkey"
    },
    "doc://com.apple.cloudkit/documentation/CloudKit/record-changed-error-keys": {
      "abstract": [
        {
          "text": "Constants that represent conflicting records in a save operation.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.cloudkit/documentation/CloudKit/record-changed-error-keys",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Record Changed Error Keys",
      "type": "topic",
      "url": "/documentation/cloudkit/record-changed-error-keys"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.externally.resolved.symbol/s:SH": {
      "abstract": [
        {
          "text": "A type that can be hashed into a `Hasher` to produce an integer hash value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Hashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SQ",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SH",
      "kind": "symbol",
      "role": "symbol",
      "title": "Hashable",
      "type": "topic",
      "url": "/documentation/Swift/Hashable"
    },
    "doc://com.externally.resolved.symbol/s:SQ": {
      "abstract": [
        {
          "text": "A type that can be compared for value equality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SQ",
      "kind": "symbol",
      "role": "symbol",
      "title": "Equatable",
      "type": "topic",
      "url": "/documentation/Swift/Equatable"
    },
    "doc://com.externally.resolved.symbol/s:SY": {
      "abstract": [
        {
          "text": "A type that can be converted to and from an associated raw value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "RawRepresentable"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SY8RawValueQa",
          "text": "RawValue"
        },
        {
          "kind": "text",
          "text": ">"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SY",
      "kind": "symbol",
      "role": "symbol",
      "title": "RawRepresentable",
      "type": "topic",
      "url": "/documentation/Swift/RawRepresentable"
    },
    "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BitwiseCopyable"
        },
        {
          "kind": "text",
          "text": " : ~Escapable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "BitwiseCopyable",
      "type": "topic",
      "url": "/documentation/Swift/BitwiseCopyable"
    },
    "doc://com.externally.resolved.symbol/s:s8SendableP": {
      "abstract": [
        {
          "text": "A thread-safe type whose values can be shared across arbitrary concurrent contexts without introducing a risk of data races.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Sendable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s8SendableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "Sendable",
      "type": "topic",
      "url": "/documentation/Swift/Sendable"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
        "doc://com.externally.resolved.symbol/s:SQ",
        "doc://com.externally.resolved.symbol/s:SH",
        "doc://com.externally.resolved.symbol/s:SY",
        "doc://com.externally.resolved.symbol/s:s8SendableP"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Errors",
      "generated": true,
      "identifiers": [
        "doc://com.apple.cloudkit/documentation/CloudKit/CKErrorDomain",
        "doc://com.apple.cloudkit/documentation/CloudKit/CKError",
        "doc://com.apple.cloudkit/documentation/CloudKit/CKErrorRetryAfterKey",
        "doc://com.apple.cloudkit/documentation/CloudKit/CKErrorUserDidResetEncryptedDataKey",
        "doc://com.apple.cloudkit/documentation/CloudKit/CKPartialErrorsByItemIDKey",
        "doc://com.apple.cloudkit/documentation/CloudKit/record-changed-error-keys"
      ],
      "title": "Errors"
    }
  ],
  "topicSections": [
    {
      "anchor": "Error-Codes",
      "identifiers": [
        "doc://com.apple.cloudkit/documentation/CloudKit/CKError/Code/accountTemporarilyUnavailable",
        "doc://com.apple.cloudkit/documentation/CloudKit/CKError/Code/alreadyShared",
        "doc://com.apple.cloudkit/documentation/CloudKit/CKError/Code/assetFileModified",
        "doc://com.apple.cloudkit/documentation/CloudKit/CKError/Code/assetFileNotFound",
        "doc://com.apple.cloudkit/documentation/CloudKit/CKError/Code/assetNotAvailable",
        "doc://com.apple.cloudkit/documentation/CloudKit/CKError/Code/badContainer",
        "doc://com.apple.cloudkit/documentation/CloudKit/CKError/Code/badDatabase",
        "doc://com.apple.cloudkit/documentation/CloudKit/CKError/Code/batchRequestFailed",
        "doc://com.apple.cloudkit/documentation/CloudKit/CKError/Code/changeTokenExpired",
        "doc://com.apple.cloudkit/documentation/CloudKit/CKError/Code/constraintViolation",
        "doc://com.apple.cloudkit/documentation/CloudKit/CKError/Code/incompatibleVersion",
        "doc://com.apple.cloudkit/documentation/CloudKit/CKError/Code/internalError",
        "doc://com.apple.cloudkit/documentation/CloudKit/CKError/Code/invalidArguments",
        "doc://com.apple.cloudkit/documentation/CloudKit/CKError/Code/limitExceeded",
        "doc://com.apple.cloudkit/documentation/CloudKit/CKError/Code/managedAccountRestricted",
        "doc://com.apple.cloudkit/documentation/CloudKit/CKError/Code/missingEntitlement",
        "doc://com.apple.cloudkit/documentation/CloudKit/CKError/Code/networkFailure",
        "doc://com.apple.cloudkit/documentation/CloudKit/CKError/Code/networkUnavailable",
        "doc://com.apple.cloudkit/documentation/CloudKit/CKError/Code/notAuthenticated",
        "doc://com.apple.cloudkit/documentation/CloudKit/CKError/Code/operationCancelled",
        "doc://com.apple.cloudkit/documentation/CloudKit/CKError/Code/partialFailure",
        "doc://com.apple.cloudkit/documentation/CloudKit/CKError/Code/participantMayNeedVerification",
        "doc://com.apple.cloudkit/documentation/CloudKit/CKError/Code/permissionFailure",
        "doc://com.apple.cloudkit/documentation/CloudKit/CKError/Code/quotaExceeded",
        "doc://com.apple.cloudkit/documentation/CloudKit/CKError/Code/referenceViolation",
        "doc://com.apple.cloudkit/documentation/CloudKit/CKError/Code/requestRateLimited",
        "doc://com.apple.cloudkit/documentation/CloudKit/CKError/Code/serverRecordChanged",
        "doc://com.apple.cloudkit/documentation/CloudKit/CKError/Code/serverRejectedRequest",
        "doc://com.apple.cloudkit/documentation/CloudKit/CKError/Code/serverResponseLost",
        "doc://com.apple.cloudkit/documentation/CloudKit/CKError/Code/serviceUnavailable",
        "doc://com.apple.cloudkit/documentation/CloudKit/CKError/Code/tooManyParticipants",
        "doc://com.apple.cloudkit/documentation/CloudKit/CKError/Code/unknownItem",
        "doc://com.apple.cloudkit/documentation/CloudKit/CKError/Code/userDeletedZone",
        "doc://com.apple.cloudkit/documentation/CloudKit/CKError/Code/zoneBusy",
        "doc://com.apple.cloudkit/documentation/CloudKit/CKError/Code/zoneNotFound",
        "doc://com.apple.cloudkit/documentation/CloudKit/CKError/Code/resultsTruncated"
      ],
      "title": "Error Codes"
    },
    {
      "anchor": "Initializers",
      "generated": true,
      "identifiers": [
        "doc://com.apple.cloudkit/documentation/CloudKit/CKError/Code/init(rawValue:)"
      ],
      "title": "Initializers"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "8.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "8.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.1",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.10",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "3.0",
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "CKErrorCode"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "enum"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CKErrorCode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CKErrorCode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.cloudkit/documentation/CloudKit"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Error-Codes",
              "identifiers": [
                "doc://com.apple.cloudkit/documentation/CloudKit/CKError/Code/accountTemporarilyUnavailable",
                "doc://com.apple.cloudkit/documentation/CloudKit/CKError/Code/alreadyShared",
                "doc://com.apple.cloudkit/documentation/CloudKit/CKError/Code/assetFileModified",
                "doc://com.apple.cloudkit/documentation/CloudKit/CKError/Code/assetFileNotFound",
                "doc://com.apple.cloudkit/documentation/CloudKit/CKError/Code/assetNotAvailable",
                "doc://com.apple.cloudkit/documentation/CloudKit/CKError/Code/badContainer",
                "doc://com.apple.cloudkit/documentation/CloudKit/CKError/Code/badDatabase",
                "doc://com.apple.cloudkit/documentation/CloudKit/CKError/Code/batchRequestFailed",
                "doc://com.apple.cloudkit/documentation/CloudKit/CKError/Code/changeTokenExpired",
                "doc://com.apple.cloudkit/documentation/CloudKit/CKError/Code/constraintViolation",
                "doc://com.apple.cloudkit/documentation/CloudKit/CKError/Code/incompatibleVersion",
                "doc://com.apple.cloudkit/documentation/CloudKit/CKError/Code/internalError",
                "doc://com.apple.cloudkit/documentation/CloudKit/CKError/Code/invalidArguments",
                "doc://com.apple.cloudkit/documentation/CloudKit/CKError/Code/limitExceeded",
                "doc://com.apple.cloudkit/documentation/CloudKit/CKError/Code/managedAccountRestricted",
                "doc://com.apple.cloudkit/documentation/CloudKit/CKError/Code/missingEntitlement",
                "doc://com.apple.cloudkit/documentation/CloudKit/CKError/Code/networkFailure",
                "doc://com.apple.cloudkit/documentation/CloudKit/CKError/Code/networkUnavailable",
                "doc://com.apple.cloudkit/documentation/CloudKit/CKError/Code/notAuthenticated",
                "doc://com.apple.cloudkit/documentation/CloudKit/CKError/Code/operationCancelled",
                "doc://com.apple.cloudkit/documentation/CloudKit/CKError/Code/partialFailure",
                "doc://com.apple.cloudkit/documentation/CloudKit/CKError/Code/participantMayNeedVerification",
                "doc://com.apple.cloudkit/documentation/CloudKit/CKError/Code/permissionFailure",
                "doc://com.apple.cloudkit/documentation/CloudKit/CKError/Code/quotaExceeded",
                "doc://com.apple.cloudkit/documentation/CloudKit/CKError/Code/referenceViolation",
                "doc://com.apple.cloudkit/documentation/CloudKit/CKError/Code/requestRateLimited",
                "doc://com.apple.cloudkit/documentation/CloudKit/CKError/Code/serverRecordChanged",
                "doc://com.apple.cloudkit/documentation/CloudKit/CKError/Code/serverRejectedRequest",
                "doc://com.apple.cloudkit/documentation/CloudKit/CKError/Code/serverResponseLost",
                "doc://com.apple.cloudkit/documentation/CloudKit/CKError/Code/serviceUnavailable",
                "doc://com.apple.cloudkit/documentation/CloudKit/CKError/Code/tooManyParticipants",
                "doc://com.apple.cloudkit/documentation/CloudKit/CKError/Code/unknownItem",
                "doc://com.apple.cloudkit/documentation/CloudKit/CKError/Code/userDeletedZone",
                "doc://com.apple.cloudkit/documentation/CloudKit/CKError/Code/zoneBusy",
                "doc://com.apple.cloudkit/documentation/CloudKit/CKError/Code/zoneNotFound",
                "doc://com.apple.cloudkit/documentation/CloudKit/CKError/Code/resultsTruncated"
              ],
              "title": "Error Codes"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Errors",
              "generated": true,
              "identifiers": [
                "doc://com.apple.cloudkit/documentation/CloudKit/CKErrorDomain",
                "doc://com.apple.cloudkit/documentation/CloudKit/CKErrorRetryAfterKey",
                "doc://com.apple.cloudkit/documentation/CloudKit/CKErrorUserDidResetEncryptedDataKey",
                "doc://com.apple.cloudkit/documentation/CloudKit/CKPartialErrorsByItemIDKey",
                "doc://com.apple.cloudkit/documentation/CloudKit/record-changed-error-keys"
              ],
              "title": "Errors"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "enum"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "CKErrorCode"
                  },
                  {
                    "kind": "text",
                    "text": " : "
                  },
                  {
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@NSInteger",
                    "text": "NSInteger"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cloudkit~1documentation~1CloudKit~1CKError~1Code~1assetFileNotFound/title",
          "value": "CKErrorAssetFileNotFound"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cloudkit~1documentation~1CloudKit~1CKError~1Code~1assetFileNotFound/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CKErrorAssetFileNotFound"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cloudkit~1documentation~1CloudKit~1CKError~1Code~1limitExceeded/title",
          "value": "CKErrorLimitExceeded"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cloudkit~1documentation~1CloudKit~1CKError~1Code~1limitExceeded/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CKErrorLimitExceeded"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cloudkit~1documentation~1CloudKit~1CKError~1Code~1badDatabase/title",
          "value": "CKErrorBadDatabase"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cloudkit~1documentation~1CloudKit~1CKError~1Code~1badDatabase/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CKErrorBadDatabase"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cloudkit~1documentation~1CloudKit~1CKError~1Code~1zoneNotFound/title",
          "value": "CKErrorZoneNotFound"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cloudkit~1documentation~1CloudKit~1CKError~1Code~1zoneNotFound/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CKErrorZoneNotFound"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cloudkit~1documentation~1CloudKit~1CKError~1Code~1serviceUnavailable/title",
          "value": "CKErrorServiceUnavailable"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cloudkit~1documentation~1CloudKit~1CKError~1Code~1serviceUnavailable/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CKErrorServiceUnavailable"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cloudkit~1documentation~1CloudKit~1CKError~1Code~1permissionFailure/title",
          "value": "CKErrorPermissionFailure"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cloudkit~1documentation~1CloudKit~1CKError~1Code~1permissionFailure/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CKErrorPermissionFailure"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cloudkit~1documentation~1CloudKit~1CKError~1Code~1managedAccountRestricted/title",
          "value": "CKErrorManagedAccountRestricted"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cloudkit~1documentation~1CloudKit~1CKError~1Code~1managedAccountRestricted/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CKErrorManagedAccountRestricted"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cloudkit~1documentation~1CloudKit~1CKError~1Code/title",
          "value": "CKErrorCode"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cloudkit~1documentation~1CloudKit~1CKError~1Code/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CKErrorCode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cloudkit~1documentation~1CloudKit~1CKError~1Code/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CKErrorCode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cloudkit~1documentation~1CloudKit~1CKError~1Code~1serverRecordChanged/title",
          "value": "CKErrorServerRecordChanged"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cloudkit~1documentation~1CloudKit~1CKError~1Code~1serverRecordChanged/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CKErrorServerRecordChanged"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cloudkit~1documentation~1CloudKit~1CKError~1Code~1networkUnavailable/title",
          "value": "CKErrorNetworkUnavailable"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cloudkit~1documentation~1CloudKit~1CKError~1Code~1networkUnavailable/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CKErrorNetworkUnavailable"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cloudkit~1documentation~1CloudKit~1CKError~1Code~1tooManyParticipants/title",
          "value": "CKErrorTooManyParticipants"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cloudkit~1documentation~1CloudKit~1CKError~1Code~1tooManyParticipants/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CKErrorTooManyParticipants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cloudkit~1documentation~1CloudKit~1CKError~1Code~1zoneBusy/title",
          "value": "CKErrorZoneBusy"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cloudkit~1documentation~1CloudKit~1CKError~1Code~1zoneBusy/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CKErrorZoneBusy"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cloudkit~1documentation~1CloudKit~1CKError~1Code~1unknownItem/title",
          "value": "CKErrorUnknownItem"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cloudkit~1documentation~1CloudKit~1CKError~1Code~1unknownItem/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CKErrorUnknownItem"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cloudkit~1documentation~1CloudKit~1CKErrorDomain/title",
          "value": "CKErrorDomain"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cloudkit~1documentation~1CloudKit~1CKErrorDomain/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CKErrorDomain"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cloudkit~1documentation~1CloudKit~1CKError~1Code~1requestRateLimited/title",
          "value": "CKErrorRequestRateLimited"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cloudkit~1documentation~1CloudKit~1CKError~1Code~1requestRateLimited/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CKErrorRequestRateLimited"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cloudkit~1documentation~1CloudKit~1CKError~1Code~1internalError/title",
          "value": "CKErrorInternalError"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cloudkit~1documentation~1CloudKit~1CKError~1Code~1internalError/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CKErrorInternalError"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cloudkit~1documentation~1CloudKit~1CKError~1Code~1incompatibleVersion/title",
          "value": "CKErrorIncompatibleVersion"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cloudkit~1documentation~1CloudKit~1CKError~1Code~1incompatibleVersion/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CKErrorIncompatibleVersion"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cloudkit~1documentation~1CloudKit~1CKError~1Code~1notAuthenticated/title",
          "value": "CKErrorNotAuthenticated"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cloudkit~1documentation~1CloudKit~1CKError~1Code~1notAuthenticated/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CKErrorNotAuthenticated"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cloudkit~1documentation~1CloudKit~1CKError~1Code~1batchRequestFailed/title",
          "value": "CKErrorBatchRequestFailed"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cloudkit~1documentation~1CloudKit~1CKError~1Code~1batchRequestFailed/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CKErrorBatchRequestFailed"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cloudkit~1documentation~1CloudKit~1CKError~1Code~1alreadyShared/title",
          "value": "CKErrorAlreadyShared"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cloudkit~1documentation~1CloudKit~1CKError~1Code~1alreadyShared/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CKErrorAlreadyShared"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cloudkit~1documentation~1CloudKit~1CKError~1Code~1partialFailure/title",
          "value": "CKErrorPartialFailure"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cloudkit~1documentation~1CloudKit~1CKError~1Code~1partialFailure/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CKErrorPartialFailure"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cloudkit~1documentation~1CloudKit~1CKError~1Code~1accountTemporarilyUnavailable/title",
          "value": "CKErrorAccountTemporarilyUnavailable"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cloudkit~1documentation~1CloudKit~1CKError~1Code~1accountTemporarilyUnavailable/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CKErrorAccountTemporarilyUnavailable"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cloudkit~1documentation~1CloudKit~1CKError~1Code~1operationCancelled/title",
          "value": "CKErrorOperationCancelled"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cloudkit~1documentation~1CloudKit~1CKError~1Code~1operationCancelled/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CKErrorOperationCancelled"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cloudkit~1documentation~1CloudKit~1CKError~1Code~1serverRejectedRequest/title",
          "value": "CKErrorServerRejectedRequest"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cloudkit~1documentation~1CloudKit~1CKError~1Code~1serverRejectedRequest/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CKErrorServerRejectedRequest"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cloudkit~1documentation~1CloudKit~1CKError~1Code~1constraintViolation/title",
          "value": "CKErrorConstraintViolation"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cloudkit~1documentation~1CloudKit~1CKError~1Code~1constraintViolation/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CKErrorConstraintViolation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cloudkit~1documentation~1CloudKit~1CKError~1Code~1referenceViolation/title",
          "value": "CKErrorReferenceViolation"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cloudkit~1documentation~1CloudKit~1CKError~1Code~1referenceViolation/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CKErrorReferenceViolation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cloudkit~1documentation~1CloudKit~1CKError~1Code~1serverResponseLost/title",
          "value": "CKErrorServerResponseLost"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cloudkit~1documentation~1CloudKit~1CKError~1Code~1serverResponseLost/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CKErrorServerResponseLost"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cloudkit~1documentation~1CloudKit~1CKError~1Code~1assetFileModified/title",
          "value": "CKErrorAssetFileModified"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cloudkit~1documentation~1CloudKit~1CKError~1Code~1assetFileModified/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CKErrorAssetFileModified"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cloudkit~1documentation~1CloudKit~1CKError~1Code~1badContainer/title",
          "value": "CKErrorBadContainer"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cloudkit~1documentation~1CloudKit~1CKError~1Code~1badContainer/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CKErrorBadContainer"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cloudkit~1documentation~1CloudKit~1CKError~1Code~1userDeletedZone/title",
          "value": "CKErrorUserDeletedZone"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cloudkit~1documentation~1CloudKit~1CKError~1Code~1userDeletedZone/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CKErrorUserDeletedZone"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cloudkit~1documentation~1CloudKit~1CKErrorUserDidResetEncryptedDataKey/title",
          "value": "CKErrorUserDidResetEncryptedDataKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cloudkit~1documentation~1CloudKit~1CKErrorUserDidResetEncryptedDataKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CKErrorUserDidResetEncryptedDataKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cloudkit~1documentation~1CloudKit~1CKError~1Code~1assetNotAvailable/title",
          "value": "CKErrorAssetNotAvailable"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cloudkit~1documentation~1CloudKit~1CKError~1Code~1assetNotAvailable/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CKErrorAssetNotAvailable"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cloudkit~1documentation~1CloudKit~1CKError~1Code~1resultsTruncated/title",
          "value": "CKErrorResultsTruncated"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cloudkit~1documentation~1CloudKit~1CKError~1Code~1resultsTruncated/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CKErrorResultsTruncated"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cloudkit~1documentation~1CloudKit~1CKError~1Code~1networkFailure/title",
          "value": "CKErrorNetworkFailure"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cloudkit~1documentation~1CloudKit~1CKError~1Code~1networkFailure/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CKErrorNetworkFailure"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cloudkit~1documentation~1CloudKit~1CKError~1Code~1quotaExceeded/title",
          "value": "CKErrorQuotaExceeded"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cloudkit~1documentation~1CloudKit~1CKError~1Code~1quotaExceeded/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CKErrorQuotaExceeded"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cloudkit~1documentation~1CloudKit~1CKPartialErrorsByItemIDKey/title",
          "value": "CKPartialErrorsByItemIDKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cloudkit~1documentation~1CloudKit~1CKPartialErrorsByItemIDKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CKPartialErrorsByItemIDKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cloudkit~1documentation~1CloudKit~1CKError~1Code~1missingEntitlement/title",
          "value": "CKErrorMissingEntitlement"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cloudkit~1documentation~1CloudKit~1CKError~1Code~1missingEntitlement/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CKErrorMissingEntitlement"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cloudkit~1documentation~1CloudKit~1CKError~1Code~1participantMayNeedVerification/title",
          "value": "CKErrorParticipantMayNeedVerification"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cloudkit~1documentation~1CloudKit~1CKError~1Code~1participantMayNeedVerification/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CKErrorParticipantMayNeedVerification"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cloudkit~1documentation~1CloudKit~1CKError~1Code~1invalidArguments/title",
          "value": "CKErrorInvalidArguments"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cloudkit~1documentation~1CloudKit~1CKError~1Code~1invalidArguments/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CKErrorInvalidArguments"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cloudkit~1documentation~1CloudKit~1CKError~1Code~1changeTokenExpired/title",
          "value": "CKErrorChangeTokenExpired"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cloudkit~1documentation~1CloudKit~1CKError~1Code~1changeTokenExpired/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CKErrorChangeTokenExpired"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cloudkit~1documentation~1CloudKit~1CKErrorRetryAfterKey/title",
          "value": "CKErrorRetryAfterKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cloudkit~1documentation~1CloudKit~1CKErrorRetryAfterKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CKErrorRetryAfterKey"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/cloudkit/ckerror/code"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/cloudkit/ckerror/code"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
