{
  "abstract": [
    {
      "text": "An error that occurs when the user is unauthenticated.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.cloudkit/documentation/CloudKit",
        "doc://com.apple.cloudkit/documentation/CloudKit/CKError"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.cloudkit/documentation/CloudKit/CKError/notAuthenticated"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "s:SC11CKErrorCodeLeV16notAuthenticatedSoAAVvpZ",
    "fragments": [
      {
        "kind": "keyword",
        "text": "static"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "keyword",
        "text": "var"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "notAuthenticated"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "s:SC11CKErrorCodeLeV",
        "text": "CKError"
      },
      {
        "kind": "text",
        "text": "."
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@E@CKErrorCode",
        "text": "Code"
      }
    ],
    "modules": [
      {
        "name": "CloudKit"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "8.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "8.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.1",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.10",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "3.0",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Type Property",
    "symbolKind": "property",
    "title": "notAuthenticated"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "static"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "keyword",
              "text": "var"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "notAuthenticated"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.cloudkit/documentation/CloudKit/CKError",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:SC11CKErrorCodeLeV",
              "text": "CKError"
            },
            {
              "kind": "text",
              "text": "."
            },
            {
              "identifier": "doc://com.apple.cloudkit/documentation/CloudKit/CKError/Code",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@E@CKErrorCode",
              "text": "Code"
            },
            {
              "kind": "text",
              "text": " { "
            },
            {
              "kind": "keyword",
              "text": "get"
            },
            {
              "kind": "text",
              "text": " }"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.cloudkit/documentation/CloudKit": {
      "abstract": [
        {
          "text": "Store structured app and user data in iCloud containers that all users of your app can share.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.cloudkit/documentation/CloudKit",
      "kind": "symbol",
      "role": "collection",
      "title": "CloudKit",
      "type": "topic",
      "url": "/documentation/cloudkit"
    },
    "doc://com.apple.cloudkit/documentation/CloudKit/CKError": {
      "abstract": [
        {
          "text": "A type that describes a CloudKit error.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CKError"
        }
      ],
      "identifier": "doc://com.apple.cloudkit/documentation/CloudKit/CKError",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CKError"
        }
      ],
      "role": "symbol",
      "title": "CKError",
      "type": "topic",
      "url": "/documentation/cloudkit/ckerror"
    },
    "doc://com.apple.cloudkit/documentation/CloudKit/CKError/Code": {
      "abstract": [
        {
          "text": "The error codes that CloudKit returns.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.cloudkit/documentation/CloudKit/CKError/Code",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "Code"
        }
      ],
      "role": "symbol",
      "title": "CKError.Code",
      "type": "topic",
      "url": "/documentation/cloudkit/ckerror/code"
    },
    "doc://com.apple.cloudkit/documentation/CloudKit/CKError/accountTemporarilyUnavailable": {
      "abstract": [
        {
          "text": "An error that occurs when the user’s iCloud account is temporarily unavailable.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "accountTemporarilyUnavailable"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC11CKErrorCodeLeV",
          "text": "CKError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@CKErrorCode",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.cloudkit/documentation/CloudKit/CKError/accountTemporarilyUnavailable",
      "kind": "symbol",
      "role": "symbol",
      "title": "accountTemporarilyUnavailable",
      "type": "topic",
      "url": "/documentation/cloudkit/ckerror/accounttemporarilyunavailable"
    },
    "doc://com.apple.cloudkit/documentation/CloudKit/CKError/alreadyShared": {
      "abstract": [
        {
          "text": "An error that occurs when CloudKit attempts to share a record with an existing share.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "alreadyShared"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC11CKErrorCodeLeV",
          "text": "CKError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@CKErrorCode",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.cloudkit/documentation/CloudKit/CKError/alreadyShared",
      "kind": "symbol",
      "role": "symbol",
      "title": "alreadyShared",
      "type": "topic",
      "url": "/documentation/cloudkit/ckerror/alreadyshared"
    },
    "doc://com.apple.cloudkit/documentation/CloudKit/CKError/assetFileModified": {
      "abstract": [
        {
          "text": "An error that occurs when the system modifies an asset while saving it.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "assetFileModified"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC11CKErrorCodeLeV",
          "text": "CKError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@CKErrorCode",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.cloudkit/documentation/CloudKit/CKError/assetFileModified",
      "kind": "symbol",
      "role": "symbol",
      "title": "assetFileModified",
      "type": "topic",
      "url": "/documentation/cloudkit/ckerror/assetfilemodified"
    },
    "doc://com.apple.cloudkit/documentation/CloudKit/CKError/assetFileNotFound": {
      "abstract": [
        {
          "text": "An error that occurs when the system can’t find the specified asset.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "assetFileNotFound"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC11CKErrorCodeLeV",
          "text": "CKError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@CKErrorCode",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.cloudkit/documentation/CloudKit/CKError/assetFileNotFound",
      "kind": "symbol",
      "role": "symbol",
      "title": "assetFileNotFound",
      "type": "topic",
      "url": "/documentation/cloudkit/ckerror/assetfilenotfound"
    },
    "doc://com.apple.cloudkit/documentation/CloudKit/CKError/assetNotAvailable": {
      "abstract": [
        {
          "text": "An error that occurs when the system can’t access the specified asset.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "assetNotAvailable"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC11CKErrorCodeLeV",
          "text": "CKError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@CKErrorCode",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.cloudkit/documentation/CloudKit/CKError/assetNotAvailable",
      "kind": "symbol",
      "role": "symbol",
      "title": "assetNotAvailable",
      "type": "topic",
      "url": "/documentation/cloudkit/ckerror/assetnotavailable"
    },
    "doc://com.apple.cloudkit/documentation/CloudKit/CKError/badContainer": {
      "abstract": [
        {
          "text": "An error that occurs when you use an unknown or unauthorized container.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "badContainer"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC11CKErrorCodeLeV",
          "text": "CKError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@CKErrorCode",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.cloudkit/documentation/CloudKit/CKError/badContainer",
      "kind": "symbol",
      "role": "symbol",
      "title": "badContainer",
      "type": "topic",
      "url": "/documentation/cloudkit/ckerror/badcontainer"
    },
    "doc://com.apple.cloudkit/documentation/CloudKit/CKError/badDatabase": {
      "abstract": [
        {
          "text": "An error that occurs when the operation can’t complete for the specified database.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "badDatabase"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC11CKErrorCodeLeV",
          "text": "CKError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@CKErrorCode",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.cloudkit/documentation/CloudKit/CKError/badDatabase",
      "kind": "symbol",
      "role": "symbol",
      "title": "badDatabase",
      "type": "topic",
      "url": "/documentation/cloudkit/ckerror/baddatabase"
    },
    "doc://com.apple.cloudkit/documentation/CloudKit/CKError/batchRequestFailed": {
      "abstract": [
        {
          "text": "An error that occurs when the system rejects the entire batch of changes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "batchRequestFailed"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC11CKErrorCodeLeV",
          "text": "CKError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@CKErrorCode",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.cloudkit/documentation/CloudKit/CKError/batchRequestFailed",
      "kind": "symbol",
      "role": "symbol",
      "title": "batchRequestFailed",
      "type": "topic",
      "url": "/documentation/cloudkit/ckerror/batchrequestfailed"
    },
    "doc://com.apple.cloudkit/documentation/CloudKit/CKError/changeTokenExpired": {
      "abstract": [
        {
          "text": "An error that occurs when the change token expires.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "changeTokenExpired"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC11CKErrorCodeLeV",
          "text": "CKError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@CKErrorCode",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.cloudkit/documentation/CloudKit/CKError/changeTokenExpired",
      "kind": "symbol",
      "role": "symbol",
      "title": "changeTokenExpired",
      "type": "topic",
      "url": "/documentation/cloudkit/ckerror/changetokenexpired"
    },
    "doc://com.apple.cloudkit/documentation/CloudKit/CKError/constraintViolation": {
      "abstract": [
        {
          "text": "An error that occurs when the server rejects the request because of a unique constraint violation.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "constraintViolation"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC11CKErrorCodeLeV",
          "text": "CKError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@CKErrorCode",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.cloudkit/documentation/CloudKit/CKError/constraintViolation",
      "kind": "symbol",
      "role": "symbol",
      "title": "constraintViolation",
      "type": "topic",
      "url": "/documentation/cloudkit/ckerror/constraintviolation"
    },
    "doc://com.apple.cloudkit/documentation/CloudKit/CKError/incompatibleVersion": {
      "abstract": [
        {
          "text": "An error that occurs when the current app version is older than the oldest allowed version.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "incompatibleVersion"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC11CKErrorCodeLeV",
          "text": "CKError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@CKErrorCode",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.cloudkit/documentation/CloudKit/CKError/incompatibleVersion",
      "kind": "symbol",
      "role": "symbol",
      "title": "incompatibleVersion",
      "type": "topic",
      "url": "/documentation/cloudkit/ckerror/incompatibleversion"
    },
    "doc://com.apple.cloudkit/documentation/CloudKit/CKError/internalError": {
      "abstract": [
        {
          "text": "A nonrecoverable error that CloudKit encounters.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "internalError"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC11CKErrorCodeLeV",
          "text": "CKError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@CKErrorCode",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.cloudkit/documentation/CloudKit/CKError/internalError",
      "kind": "symbol",
      "role": "symbol",
      "title": "internalError",
      "type": "topic",
      "url": "/documentation/cloudkit/ckerror/internalerror"
    },
    "doc://com.apple.cloudkit/documentation/CloudKit/CKError/invalidArguments": {
      "abstract": [
        {
          "text": "An error that occurs when the request contains invalid information.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "invalidArguments"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC11CKErrorCodeLeV",
          "text": "CKError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@CKErrorCode",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.cloudkit/documentation/CloudKit/CKError/invalidArguments",
      "kind": "symbol",
      "role": "symbol",
      "title": "invalidArguments",
      "type": "topic",
      "url": "/documentation/cloudkit/ckerror/invalidarguments"
    },
    "doc://com.apple.cloudkit/documentation/CloudKit/CKError/limitExceeded": {
      "abstract": [
        {
          "text": "An error that occurs when a request’s size exceeds the limit.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "limitExceeded"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC11CKErrorCodeLeV",
          "text": "CKError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@CKErrorCode",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.cloudkit/documentation/CloudKit/CKError/limitExceeded",
      "kind": "symbol",
      "role": "symbol",
      "title": "limitExceeded",
      "type": "topic",
      "url": "/documentation/cloudkit/ckerror/limitexceeded"
    },
    "doc://com.apple.cloudkit/documentation/CloudKit/CKError/managedAccountRestricted": {
      "abstract": [
        {
          "text": "An error that occurs when CloudKit rejects a request due to a managed-account restriction.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "managedAccountRestricted"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC11CKErrorCodeLeV",
          "text": "CKError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@CKErrorCode",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.cloudkit/documentation/CloudKit/CKError/managedAccountRestricted",
      "kind": "symbol",
      "role": "symbol",
      "title": "managedAccountRestricted",
      "type": "topic",
      "url": "/documentation/cloudkit/ckerror/managedaccountrestricted"
    },
    "doc://com.apple.cloudkit/documentation/CloudKit/CKError/notAuthenticated": {
      "abstract": [
        {
          "text": "An error that occurs when the user is unauthenticated.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "notAuthenticated"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC11CKErrorCodeLeV",
          "text": "CKError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@CKErrorCode",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.cloudkit/documentation/CloudKit/CKError/notAuthenticated",
      "kind": "symbol",
      "role": "symbol",
      "title": "notAuthenticated",
      "type": "topic",
      "url": "/documentation/cloudkit/ckerror/notauthenticated"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Getting-Error-Codes",
      "generated": true,
      "identifiers": [
        "doc://com.apple.cloudkit/documentation/CloudKit/CKError/accountTemporarilyUnavailable",
        "doc://com.apple.cloudkit/documentation/CloudKit/CKError/alreadyShared",
        "doc://com.apple.cloudkit/documentation/CloudKit/CKError/assetFileModified",
        "doc://com.apple.cloudkit/documentation/CloudKit/CKError/assetFileNotFound",
        "doc://com.apple.cloudkit/documentation/CloudKit/CKError/assetNotAvailable",
        "doc://com.apple.cloudkit/documentation/CloudKit/CKError/badContainer",
        "doc://com.apple.cloudkit/documentation/CloudKit/CKError/badDatabase",
        "doc://com.apple.cloudkit/documentation/CloudKit/CKError/batchRequestFailed",
        "doc://com.apple.cloudkit/documentation/CloudKit/CKError/changeTokenExpired",
        "doc://com.apple.cloudkit/documentation/CloudKit/CKError/constraintViolation",
        "doc://com.apple.cloudkit/documentation/CloudKit/CKError/incompatibleVersion",
        "doc://com.apple.cloudkit/documentation/CloudKit/CKError/internalError",
        "doc://com.apple.cloudkit/documentation/CloudKit/CKError/invalidArguments",
        "doc://com.apple.cloudkit/documentation/CloudKit/CKError/limitExceeded",
        "doc://com.apple.cloudkit/documentation/CloudKit/CKError/managedAccountRestricted"
      ],
      "title": "Getting Error Codes"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cloudkit~1documentation~1CloudKit~1CKError~1Code/title",
          "value": "CKErrorCode"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cloudkit~1documentation~1CloudKit~1CKError~1Code/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CKErrorCode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cloudkit~1documentation~1CloudKit~1CKError~1Code/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CKErrorCode"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/cloudkit/ckerror/notauthenticated"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    }
  ]
}
