{
  "abstract": [
    {
      "text": "The dictionary that contains errors that relate to individual record operations.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.cloudkit/documentation/CloudKit",
        "doc://com.apple.cloudkit/documentation/CloudKit/CKError"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.cloudkit/documentation/CloudKit/CKError/partialErrorsByItemID"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "extendedModule": "CloudKit",
    "externalID": "s:SC11CKErrorCodeLeV8CloudKitE21partialErrorsByItemIDSDys11AnyHashableVs5Error_pGSgvp",
    "fragments": [
      {
        "kind": "keyword",
        "text": "var"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "partialErrorsByItemID"
      },
      {
        "kind": "text",
        "text": ": ["
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "s:s11AnyHashableV",
        "text": "AnyHashable"
      },
      {
        "kind": "text",
        "text": " : any "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "s:s5ErrorP",
        "text": "Error"
      },
      {
        "kind": "text",
        "text": "]?"
      }
    ],
    "modules": [
      {
        "name": "CloudKit"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "8.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "8.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.1",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.10",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "9.0",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "3.0",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Instance Property",
    "symbolKind": "property",
    "title": "partialErrorsByItemID"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "var"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "partialErrorsByItemID"
            },
            {
              "kind": "text",
              "text": ": ["
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:s11AnyHashableV",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:s11AnyHashableV",
              "text": "AnyHashable"
            },
            {
              "kind": "text",
              "text": " : any "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:s5ErrorP",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:s5ErrorP",
              "text": "Error"
            },
            {
              "kind": "text",
              "text": "]? { "
            },
            {
              "kind": "keyword",
              "text": "get"
            },
            {
              "kind": "text",
              "text": " }"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "This property’s value is a dictionary that maps an item ID to an error. The type of each ID depends on where the error occurs. For example, if you receive a partial error when modifying a record, the ID is an instance of ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.cloudkit/documentation/CloudKit/CKRecord/ID",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " that corresponds to the record that CloudKit can’t modify.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "The error’s ",
              "type": "text"
            },
            {
              "code": "userInfo",
              "type": "codeVoice"
            },
            {
              "text": " dictionary contains the same value as this property. You can access it using the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.cloudkit/documentation/CloudKit/CKPartialErrorsByItemIDKey",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " key.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.cloudkit/documentation/CloudKit": {
      "abstract": [
        {
          "text": "Store structured app and user data in iCloud containers that all users of your app can share.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.cloudkit/documentation/CloudKit",
      "kind": "symbol",
      "role": "collection",
      "title": "CloudKit",
      "type": "topic",
      "url": "/documentation/cloudkit"
    },
    "doc://com.apple.cloudkit/documentation/CloudKit/CKError": {
      "abstract": [
        {
          "text": "A type that describes a CloudKit error.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CKError"
        }
      ],
      "identifier": "doc://com.apple.cloudkit/documentation/CloudKit/CKError",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CKError"
        }
      ],
      "role": "symbol",
      "title": "CKError",
      "type": "topic",
      "url": "/documentation/cloudkit/ckerror"
    },
    "doc://com.apple.cloudkit/documentation/CloudKit/CKError/partialErrorsByItemID": {
      "abstract": [
        {
          "text": "The dictionary that contains errors that relate to individual record operations.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "partialErrorsByItemID"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s11AnyHashableV",
          "text": "AnyHashable"
        },
        {
          "kind": "text",
          "text": " : any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5ErrorP",
          "text": "Error"
        },
        {
          "kind": "text",
          "text": "]?"
        }
      ],
      "identifier": "doc://com.apple.cloudkit/documentation/CloudKit/CKError/partialErrorsByItemID",
      "kind": "symbol",
      "role": "symbol",
      "title": "partialErrorsByItemID",
      "type": "topic",
      "url": "/documentation/cloudkit/ckerror/partialerrorsbyitemid"
    },
    "doc://com.apple.cloudkit/documentation/CloudKit/CKPartialErrorsByItemIDKey": {
      "abstract": [
        {
          "text": "The key to retrieve partial errors.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CKPartialErrorsByItemIDKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.cloudkit/documentation/CloudKit/CKPartialErrorsByItemIDKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CKPartialErrorsByItemIDKey"
        }
      ],
      "role": "symbol",
      "title": "CKPartialErrorsByItemIDKey",
      "type": "topic",
      "url": "/documentation/cloudkit/ckpartialerrorsbyitemidkey"
    },
    "doc://com.apple.cloudkit/documentation/CloudKit/CKRecord/ID": {
      "abstract": [
        {
          "text": "An object that uniquely identifies a record in a database.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ID"
        }
      ],
      "identifier": "doc://com.apple.cloudkit/documentation/CloudKit/CKRecord/ID",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ID"
        }
      ],
      "role": "symbol",
      "title": "CKRecord.ID",
      "type": "topic",
      "url": "/documentation/cloudkit/ckrecord/id"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.externally.resolved.symbol/s:s11AnyHashableV": {
      "abstract": [
        {
          "text": "A type-erased hashable value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@frozen"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AnyHashable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s11AnyHashableV",
      "kind": "symbol",
      "role": "symbol",
      "title": "AnyHashable",
      "type": "topic",
      "url": "/documentation/Swift/AnyHashable"
    },
    "doc://com.externally.resolved.symbol/s:s5ErrorP": {
      "abstract": [
        {
          "text": "A type representing an error value that can be thrown.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Error"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s8SendableP",
          "text": "Sendable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s5ErrorP",
      "kind": "symbol",
      "role": "symbol",
      "title": "Error",
      "type": "topic",
      "url": "/documentation/Swift/Error"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cloudkit~1documentation~1CloudKit~1CKRecord~1ID/title",
          "value": "CKRecordID"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cloudkit~1documentation~1CloudKit~1CKRecord~1ID/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CKRecordID"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cloudkit~1documentation~1CloudKit~1CKRecord~1ID/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CKRecordID"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cloudkit~1documentation~1CloudKit~1CKPartialErrorsByItemIDKey/title",
          "value": "CKPartialErrorsByItemIDKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cloudkit~1documentation~1CloudKit~1CKPartialErrorsByItemIDKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CKPartialErrorsByItemIDKey"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/cloudkit/ckerror/partialerrorsbyitemid"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    }
  ]
}
