{
  "abstract": [
    {
      "text": "Creates an object whose resolution indicates that your app doesn’t support the specified value.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.sirikit/documentation/Intents",
        "doc://com.apple.sirikit/documentation/Intents/INIntentResolutionResult"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "occ",
    "url": "doc://com.apple.sirikit/documentation/Intents/INIntentResolutionResult/unsupportedWithReason:"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(cs)INIntentResolutionResult(cm)unsupportedWithReason:",
    "fragments": [
      {
        "kind": "text",
        "text": "+ "
      },
      {
        "kind": "identifier",
        "text": "unsupportedWithReason:"
      }
    ],
    "modules": [
      {
        "name": "Intents"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "unsupportedWithReason:"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.1",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "11.0",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "14.0",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "6.0",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Type Method",
    "symbolKind": "method",
    "title": "unsupportedWithReason:"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "occ"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "text",
              "text": "+ ("
            },
            {
              "kind": "keyword",
              "text": "instancetype"
            },
            {
              "kind": "text",
              "text": ") "
            },
            {
              "kind": "identifier",
              "text": "unsupportedWithReason:"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/c:@T@NSInteger",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@NSInteger",
              "text": "NSInteger"
            },
            {
              "kind": "text",
              "text": ") "
            },
            {
              "kind": "internalParam",
              "text": "reason"
            },
            {
              "kind": "text",
              "text": ";"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "kind": "parameters",
      "parameters": [
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "The reason why your app is not using the specified value. For a list of possible values, see ",
                  "type": "text"
                },
                {
                  "code": "INIntentResolutionResultUnsupportedReason",
                  "type": "codeVoice"
                },
                {
                  "text": ".",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "reason"
        }
      ]
    },
    {
      "content": [
        {
          "anchor": "return-value",
          "level": 2,
          "text": "Return Value",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "A new ",
              "type": "text"
            },
            {
              "code": "INIntentResolutionResult",
              "type": "codeVoice"
            },
            {
              "text": " object.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    },
    {
      "content": [
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Use this method to create a resolution result object when your app doesn’t support an intent parameter. Siri may use the returned reason to let the user know that the value isn’t supported.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.sirikit/documentation/Intents": {
      "abstract": [
        {
          "text": "Empower people to customize interactions for your app on their device.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents",
      "kind": "symbol",
      "role": "collection",
      "title": "Intents",
      "type": "topic",
      "url": "/documentation/intents"
    },
    "doc://com.apple.sirikit/documentation/Intents/INIntentResolutionResult": {
      "abstract": [
        {
          "text": "A resolution result for a parameter of an intent object.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "INIntentResolutionResult"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INIntentResolutionResult",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INIntentResolutionResult"
        }
      ],
      "role": "symbol",
      "title": "INIntentResolutionResult",
      "type": "topic",
      "url": "/documentation/intents/inintentresolutionresult"
    },
    "doc://com.apple.sirikit/documentation/Intents/INIntentResolutionResult/confirmationRequiredWithItemToConfirm:forReason:": {
      "abstract": [
        {
          "text": "Creates an object whose resolution indicates that your app requires confirmation of the specified value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "+ "
        },
        {
          "kind": "identifier",
          "text": "confirmationRequiredWithItemToConfirm:forReason:"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INIntentResolutionResult/confirmationRequiredWithItemToConfirm:forReason:",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "confirmationRequiredWithItemToConfirm:forReason:"
        }
      ],
      "role": "symbol",
      "title": "confirmationRequiredWithItemToConfirm:forReason:",
      "type": "topic",
      "url": "/documentation/intents/inintentresolutionresult/confirmationrequiredwithitemtoconfirm:forreason:"
    },
    "doc://com.apple.sirikit/documentation/Intents/INIntentResolutionResult/needsValue()": {
      "abstract": [
        {
          "text": "Creates an object whose resolution indicates that a required parameter value is missing.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "needsValue"
        },
        {
          "kind": "text",
          "text": "() -> "
        },
        {
          "kind": "typeIdentifier",
          "text": "Self"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INIntentResolutionResult/needsValue()",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "needsValue"
        }
      ],
      "role": "symbol",
      "title": "needsValue()",
      "type": "topic",
      "url": "/documentation/intents/inintentresolutionresult/needsvalue()"
    },
    "doc://com.apple.sirikit/documentation/Intents/INIntentResolutionResult/notRequired()": {
      "abstract": [
        {
          "text": "Creates an object whose resolution indicates that you don’t need the value of the parameter.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "notRequired"
        },
        {
          "kind": "text",
          "text": "() -> "
        },
        {
          "kind": "typeIdentifier",
          "text": "Self"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INIntentResolutionResult/notRequired()",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "notRequired"
        }
      ],
      "role": "symbol",
      "title": "notRequired()",
      "type": "topic",
      "url": "/documentation/intents/inintentresolutionresult/notrequired()"
    },
    "doc://com.apple.sirikit/documentation/Intents/INIntentResolutionResult/unsupported()": {
      "abstract": [
        {
          "text": "Creates an object whose resolution indicates that your app doesn’t support the specified value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "unsupported"
        },
        {
          "kind": "text",
          "text": "() -> "
        },
        {
          "kind": "typeIdentifier",
          "text": "Self"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INIntentResolutionResult/unsupported()",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "unsupported"
        }
      ],
      "role": "symbol",
      "title": "unsupported()",
      "type": "topic",
      "url": "/documentation/intents/inintentresolutionresult/unsupported()"
    },
    "doc://com.apple.sirikit/documentation/Intents/INIntentResolutionResult/unsupportedWithReason:": {
      "abstract": [
        {
          "text": "Creates an object whose resolution indicates that your app doesn’t support the specified value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "+ "
        },
        {
          "kind": "identifier",
          "text": "unsupportedWithReason:"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INIntentResolutionResult/unsupportedWithReason:",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "unsupportedWithReason:"
        }
      ],
      "role": "symbol",
      "title": "unsupportedWithReason:",
      "type": "topic",
      "url": "/documentation/intents/inintentresolutionresult/unsupportedwithreason:"
    },
    "doc://com.externally.resolved.symbol/c:@T@NSInteger": {
      "abstract": [
        {
          "text": "Describes an integer.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "typealias "
        },
        {
          "kind": "identifier",
          "text": "NSInteger"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:@T@NSInteger",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSInteger",
      "type": "topic",
      "url": "/documentation/objectivec/nsinteger"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Common-Results",
      "generated": true,
      "identifiers": [
        "doc://com.apple.sirikit/documentation/Intents/INIntentResolutionResult/confirmationRequiredWithItemToConfirm:forReason:",
        "doc://com.apple.sirikit/documentation/Intents/INIntentResolutionResult/needsValue()",
        "doc://com.apple.sirikit/documentation/Intents/INIntentResolutionResult/notRequired()",
        "doc://com.apple.sirikit/documentation/Intents/INIntentResolutionResult/unsupported()"
      ],
      "title": "Common Results"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INIntentResolutionResult~1unsupported()/title",
          "value": "unsupported"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INIntentResolutionResult~1unsupported()/fragments",
          "value": [
            {
              "kind": "text",
              "text": "+ "
            },
            {
              "kind": "identifier",
              "text": "unsupported"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INIntentResolutionResult~1needsValue()/title",
          "value": "needsValue"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INIntentResolutionResult~1needsValue()/fragments",
          "value": [
            {
              "kind": "text",
              "text": "+ "
            },
            {
              "kind": "identifier",
              "text": "needsValue"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INIntentResolutionResult~1notRequired()/title",
          "value": "notRequired"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INIntentResolutionResult~1notRequired()/fragments",
          "value": [
            {
              "kind": "text",
              "text": "+ "
            },
            {
              "kind": "identifier",
              "text": "notRequired"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INIntentResolutionResult/title",
          "value": "INIntentResolutionResult"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INIntentResolutionResult/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INIntentResolutionResult"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INIntentResolutionResult/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "INIntentResolutionResult"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/intents/inintentresolutionresult/unsupportedwithreason:"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
