{
  "abstract": [
    {
      "text": "Convert between Metal and Model I/O vertex representations.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.metalkit/documentation/MetalKit"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.metalkit/documentation/MetalKit/conversion-functions"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "MetalKit"
      }
    ],
    "role": "collectionGroup",
    "roleHeading": "API Collection",
    "title": "Conversion Functions"
  },
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.metalkit/documentation/MetalKit": {
      "abstract": [
        {
          "text": "Build Metal apps quicker and easier using a common set of utility classes.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.metalkit/documentation/MetalKit",
      "kind": "symbol",
      "role": "collection",
      "title": "MetalKit",
      "type": "topic",
      "url": "/documentation/metalkit"
    },
    "doc://com.apple.metalkit/documentation/MetalKit/MTKMesh": {
      "abstract": [
        {
          "text": "A container for the vertex data of a Model I/O mesh, suitable for use in a Metal app.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MTKMesh"
        }
      ],
      "identifier": "doc://com.apple.metalkit/documentation/MetalKit/MTKMesh",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTKMesh"
        }
      ],
      "role": "symbol",
      "title": "MTKMesh",
      "type": "topic",
      "url": "/documentation/metalkit/mtkmesh"
    },
    "doc://com.apple.metalkit/documentation/MetalKit/MTKMeshBuffer": {
      "abstract": [
        {
          "text": "A buffer that backs the vertex data of a Model I/O mesh, suitable for use in a Metal app.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MTKMeshBuffer"
        }
      ],
      "identifier": "doc://com.apple.metalkit/documentation/MetalKit/MTKMeshBuffer",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTKMeshBuffer"
        }
      ],
      "role": "symbol",
      "title": "MTKMeshBuffer",
      "type": "topic",
      "url": "/documentation/metalkit/mtkmeshbuffer"
    },
    "doc://com.apple.metalkit/documentation/MetalKit/MTKMeshBufferAllocator": {
      "abstract": [
        {
          "text": "An interface for allocating a MetalKit buffer that backs the vertex data of a Model I/O mesh, suitable for use in a Metal app.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MTKMeshBufferAllocator"
        }
      ],
      "identifier": "doc://com.apple.metalkit/documentation/MetalKit/MTKMeshBufferAllocator",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTKMeshBufferAllocator"
        }
      ],
      "role": "symbol",
      "title": "MTKMeshBufferAllocator",
      "type": "topic",
      "url": "/documentation/metalkit/mtkmeshbufferallocator"
    },
    "doc://com.apple.metalkit/documentation/MetalKit/MTKMetalVertexDescriptorFromModelIO(_:)": {
      "abstract": [
        {
          "text": "Returns a partially converted Metal vertex descriptor.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MTKMetalVertexDescriptorFromModelIO"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)MDLVertexDescriptor",
          "text": "MDLVertexDescriptor"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)MTLVertexDescriptor",
          "text": "MTLVertexDescriptor"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.metalkit/documentation/MetalKit/MTKMetalVertexDescriptorFromModelIO(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTKMetalVertexDescriptorFromModelIO"
        }
      ],
      "role": "symbol",
      "title": "MTKMetalVertexDescriptorFromModelIO(_:)",
      "type": "topic",
      "url": "/documentation/metalkit/mtkmetalvertexdescriptorfrommodelio(_:)"
    },
    "doc://com.apple.metalkit/documentation/MetalKit/MTKMetalVertexDescriptorFromModelIOWithError": {
      "abstract": [
        {
          "text": "Returns a partially converted Metal vertex descriptor, reporting any error that occurs.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "MTKMetalVertexDescriptorFromModelIOWithError"
        }
      ],
      "identifier": "doc://com.apple.metalkit/documentation/MetalKit/MTKMetalVertexDescriptorFromModelIOWithError",
      "kind": "symbol",
      "role": "symbol",
      "title": "MTKMetalVertexDescriptorFromModelIOWithError",
      "type": "topic",
      "url": "/documentation/metalkit/mtkmetalvertexdescriptorfrommodeliowitherror"
    },
    "doc://com.apple.metalkit/documentation/MetalKit/MTKMetalVertexFormatFromModelIO(_:)": {
      "abstract": [
        {
          "text": "Returns a converted Metal vertex format.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MTKMetalVertexFormatFromModelIO"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@MDLVertexFormat",
          "text": "MDLVertexFormat"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@MTLVertexFormat",
          "text": "MTLVertexFormat"
        }
      ],
      "identifier": "doc://com.apple.metalkit/documentation/MetalKit/MTKMetalVertexFormatFromModelIO(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTKMetalVertexFormatFromModelIO"
        }
      ],
      "role": "symbol",
      "title": "MTKMetalVertexFormatFromModelIO(_:)",
      "type": "topic",
      "url": "/documentation/metalkit/mtkmetalvertexformatfrommodelio(_:)"
    },
    "doc://com.apple.metalkit/documentation/MetalKit/MTKModelIOVertexDescriptorFromMetal(_:)": {
      "abstract": [
        {
          "text": "Returns a partially converted Model I/O vertex descriptor.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MTKModelIOVertexDescriptorFromMetal"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)MTLVertexDescriptor",
          "text": "MTLVertexDescriptor"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)MDLVertexDescriptor",
          "text": "MDLVertexDescriptor"
        }
      ],
      "identifier": "doc://com.apple.metalkit/documentation/MetalKit/MTKModelIOVertexDescriptorFromMetal(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTKModelIOVertexDescriptorFromMetal"
        }
      ],
      "role": "symbol",
      "title": "MTKModelIOVertexDescriptorFromMetal(_:)",
      "type": "topic",
      "url": "/documentation/metalkit/mtkmodeliovertexdescriptorfrommetal(_:)"
    },
    "doc://com.apple.metalkit/documentation/MetalKit/MTKModelIOVertexDescriptorFromMetalWithError": {
      "abstract": [
        {
          "text": "Returns a partially converted Model I/O vertex descriptor, reporting any error that occurs.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "MTKModelIOVertexDescriptorFromMetalWithError"
        }
      ],
      "identifier": "doc://com.apple.metalkit/documentation/MetalKit/MTKModelIOVertexDescriptorFromMetalWithError",
      "kind": "symbol",
      "role": "symbol",
      "title": "MTKModelIOVertexDescriptorFromMetalWithError",
      "type": "topic",
      "url": "/documentation/metalkit/mtkmodeliovertexdescriptorfrommetalwitherror"
    },
    "doc://com.apple.metalkit/documentation/MetalKit/MTKModelIOVertexFormatFromMetal(_:)": {
      "abstract": [
        {
          "text": "Returns a converted Model I/O vertex format.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MTKModelIOVertexFormatFromMetal"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@MTLVertexFormat",
          "text": "MTLVertexFormat"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@MDLVertexFormat",
          "text": "MDLVertexFormat"
        }
      ],
      "identifier": "doc://com.apple.metalkit/documentation/MetalKit/MTKModelIOVertexFormatFromMetal(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTKModelIOVertexFormatFromMetal"
        }
      ],
      "role": "symbol",
      "title": "MTKModelIOVertexFormatFromMetal(_:)",
      "type": "topic",
      "url": "/documentation/metalkit/mtkmodeliovertexformatfrommetal(_:)"
    },
    "doc://com.apple.metalkit/documentation/MetalKit/MTKSubmesh": {
      "abstract": [
        {
          "text": "A container for the index data of a Model I/O submesh, suitable for use in a Metal app.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MTKSubmesh"
        }
      ],
      "identifier": "doc://com.apple.metalkit/documentation/MetalKit/MTKSubmesh",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTKSubmesh"
        }
      ],
      "role": "symbol",
      "title": "MTKSubmesh",
      "type": "topic",
      "url": "/documentation/metalkit/mtksubmesh"
    },
    "doc://com.apple.metalkit/documentation/MetalKit/model-errors": {
      "abstract": [
        {
          "text": "Learn about errors thrown by model handling methods.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.metalkit/documentation/MetalKit/model-errors",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Model Errors",
      "type": "topic",
      "url": "/documentation/metalkit/model-errors"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Model-Handling",
      "generated": true,
      "identifiers": [
        "doc://com.apple.metalkit/documentation/MetalKit/MTKMesh",
        "doc://com.apple.metalkit/documentation/MetalKit/MTKMeshBuffer",
        "doc://com.apple.metalkit/documentation/MetalKit/MTKMeshBufferAllocator",
        "doc://com.apple.metalkit/documentation/MetalKit/MTKSubmesh",
        "doc://com.apple.metalkit/documentation/MetalKit/model-errors"
      ],
      "title": "Model Handling"
    }
  ],
  "topicSections": [
    {
      "anchor": "Converting-Between-Model-IO-and-Metal-Vertex-Descriptors",
      "identifiers": [
        "doc://com.apple.metalkit/documentation/MetalKit/MTKMetalVertexDescriptorFromModelIO(_:)",
        "doc://com.apple.metalkit/documentation/MetalKit/MTKModelIOVertexDescriptorFromMetal(_:)"
      ],
      "title": "Converting Between Model I/O and Metal Vertex Descriptors"
    },
    {
      "anchor": "Converting-Between-Model-IO-and-Metal-Vertex-Formats",
      "identifiers": [
        "doc://com.apple.metalkit/documentation/MetalKit/MTKMetalVertexFormatFromModelIO(_:)",
        "doc://com.apple.metalkit/documentation/MetalKit/MTKModelIOVertexFormatFromMetal(_:)"
      ],
      "title": "Converting Between Model I/O and Metal Vertex Formats"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Converting-Between-Model-IO-and-Metal-Vertex-Descriptors",
              "identifiers": [
                "doc://com.apple.metalkit/documentation/MetalKit/MTKMetalVertexDescriptorFromModelIO(_:)",
                "doc://com.apple.metalkit/documentation/MetalKit/MTKMetalVertexDescriptorFromModelIOWithError",
                "doc://com.apple.metalkit/documentation/MetalKit/MTKModelIOVertexDescriptorFromMetal(_:)",
                "doc://com.apple.metalkit/documentation/MetalKit/MTKModelIOVertexDescriptorFromMetalWithError"
              ],
              "title": "Converting Between Model I/O and Metal Vertex Descriptors"
            },
            {
              "anchor": "Converting-Between-Model-IO-and-Metal-Vertex-Formats",
              "identifiers": [
                "doc://com.apple.metalkit/documentation/MetalKit/MTKMetalVertexFormatFromModelIO(_:)",
                "doc://com.apple.metalkit/documentation/MetalKit/MTKModelIOVertexFormatFromMetal(_:)"
              ],
              "title": "Converting Between Model I/O and Metal Vertex Formats"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Model-Handling",
              "generated": true,
              "identifiers": [
                "doc://com.apple.metalkit/documentation/MetalKit/MTKMesh",
                "doc://com.apple.metalkit/documentation/MetalKit/MTKMeshBuffer",
                "doc://com.apple.metalkit/documentation/MetalKit/MTKMeshBufferAllocator",
                "doc://com.apple.metalkit/documentation/MetalKit/MTKSubmesh",
                "doc://com.apple.metalkit/documentation/MetalKit/model-errors"
              ],
              "title": "Model Handling"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metalkit~1documentation~1MetalKit~1MTKMeshBufferAllocator/title",
          "value": "MTKMeshBufferAllocator"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metalkit~1documentation~1MetalKit~1MTKMeshBufferAllocator/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTKMeshBufferAllocator"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metalkit~1documentation~1MetalKit~1MTKMeshBufferAllocator/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MTKMeshBufferAllocator"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metalkit~1documentation~1MetalKit~1MTKModelIOVertexDescriptorFromMetal(_:)/title",
          "value": "MTKModelIOVertexDescriptorFromMetal"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metalkit~1documentation~1MetalKit~1MTKModelIOVertexDescriptorFromMetal(_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTKModelIOVertexDescriptorFromMetal"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metalkit~1documentation~1MetalKit~1MTKModelIOVertexFormatFromMetal(_:)/title",
          "value": "MTKModelIOVertexFormatFromMetal"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metalkit~1documentation~1MetalKit~1MTKModelIOVertexFormatFromMetal(_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTKModelIOVertexFormatFromMetal"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metalkit~1documentation~1MetalKit~1MTKMetalVertexDescriptorFromModelIO(_:)/title",
          "value": "MTKMetalVertexDescriptorFromModelIO"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metalkit~1documentation~1MetalKit~1MTKMetalVertexDescriptorFromModelIO(_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTKMetalVertexDescriptorFromModelIO"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metalkit~1documentation~1MetalKit~1MTKMesh/title",
          "value": "MTKMesh"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metalkit~1documentation~1MetalKit~1MTKMesh/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTKMesh"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metalkit~1documentation~1MetalKit~1MTKMesh/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MTKMesh"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metalkit~1documentation~1MetalKit~1MTKMetalVertexFormatFromModelIO(_:)/title",
          "value": "MTKMetalVertexFormatFromModelIO"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metalkit~1documentation~1MetalKit~1MTKMetalVertexFormatFromModelIO(_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTKMetalVertexFormatFromModelIO"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metalkit~1documentation~1MetalKit~1MTKSubmesh/title",
          "value": "MTKSubmesh"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metalkit~1documentation~1MetalKit~1MTKSubmesh/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTKSubmesh"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metalkit~1documentation~1MetalKit~1MTKSubmesh/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MTKSubmesh"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metalkit~1documentation~1MetalKit~1MTKMeshBuffer/title",
          "value": "MTKMeshBuffer"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metalkit~1documentation~1MetalKit~1MTKMeshBuffer/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTKMeshBuffer"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metalkit~1documentation~1MetalKit~1MTKMeshBuffer/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MTKMeshBuffer"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/metalkit/conversion-functions"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/metalkit/conversion-functions"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
