{
  "abstract": [
    {
      "text": "Returns a partially converted Metal vertex descriptor.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.metalkit/documentation/MetalKit"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.metalkit/documentation/MetalKit/MTKMetalVertexDescriptorFromModelIO(_:)"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@F@MTKMetalVertexDescriptorFromModelIO",
    "fragments": [
      {
        "kind": "keyword",
        "text": "func"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "MTKMetalVertexDescriptorFromModelIO"
      },
      {
        "kind": "text",
        "text": "("
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:objc(cs)MDLVertexDescriptor",
        "text": "MDLVertexDescriptor"
      },
      {
        "kind": "text",
        "text": ") -> "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:objc(cs)MTLVertexDescriptor",
        "text": "MTLVertexDescriptor"
      },
      {
        "kind": "text",
        "text": "?"
      }
    ],
    "modules": [
      {
        "name": "MetalKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "MTKMetalVertexDescriptorFromModelIO"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "9.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "9.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.1",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.11",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "9.0",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Function",
    "symbolKind": "func",
    "title": "MTKMetalVertexDescriptorFromModelIO(_:)"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "func"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "MTKMetalVertexDescriptorFromModelIO"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "kind": "externalParam",
              "text": "_"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "modelIODescriptor"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)MDLVertexDescriptor",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)MDLVertexDescriptor",
              "text": "MDLVertexDescriptor"
            },
            {
              "kind": "text",
              "text": ") -> "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)MTLVertexDescriptor",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)MTLVertexDescriptor",
              "text": "MTLVertexDescriptor"
            },
            {
              "kind": "text",
              "text": "?"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "return-value",
          "level": 2,
          "text": "Return Value",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "A Metal vertex descriptor object.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    },
    {
      "content": [
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "This function is equivalent to the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.metalkit/documentation/MetalKit/MTKMetalVertexDescriptorFromModelIOWithError",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " function, but does not report errors.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.metalkit/documentation/MetalKit": {
      "abstract": [
        {
          "text": "Build Metal apps quicker and easier using a common set of utility classes.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.metalkit/documentation/MetalKit",
      "kind": "symbol",
      "role": "collection",
      "title": "MetalKit",
      "type": "topic",
      "url": "/documentation/metalkit"
    },
    "doc://com.apple.metalkit/documentation/MetalKit/MTKMetalVertexDescriptorFromModelIO(_:)": {
      "abstract": [
        {
          "text": "Returns a partially converted Metal vertex descriptor.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MTKMetalVertexDescriptorFromModelIO"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)MDLVertexDescriptor",
          "text": "MDLVertexDescriptor"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)MTLVertexDescriptor",
          "text": "MTLVertexDescriptor"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.metalkit/documentation/MetalKit/MTKMetalVertexDescriptorFromModelIO(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTKMetalVertexDescriptorFromModelIO"
        }
      ],
      "role": "symbol",
      "title": "MTKMetalVertexDescriptorFromModelIO(_:)",
      "type": "topic",
      "url": "/documentation/metalkit/mtkmetalvertexdescriptorfrommodelio(_:)"
    },
    "doc://com.apple.metalkit/documentation/MetalKit/MTKMetalVertexDescriptorFromModelIOWithError": {
      "abstract": [
        {
          "text": "Returns a partially converted Metal vertex descriptor, reporting any error that occurs.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "MTKMetalVertexDescriptorFromModelIOWithError"
        }
      ],
      "identifier": "doc://com.apple.metalkit/documentation/MetalKit/MTKMetalVertexDescriptorFromModelIOWithError",
      "kind": "symbol",
      "role": "symbol",
      "title": "MTKMetalVertexDescriptorFromModelIOWithError",
      "type": "topic",
      "url": "/documentation/metalkit/mtkmetalvertexdescriptorfrommodeliowitherror"
    },
    "doc://com.apple.metalkit/documentation/MetalKit/MTKModelIOVertexDescriptorFromMetal(_:)": {
      "abstract": [
        {
          "text": "Returns a partially converted Model I/O vertex descriptor.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MTKModelIOVertexDescriptorFromMetal"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)MTLVertexDescriptor",
          "text": "MTLVertexDescriptor"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)MDLVertexDescriptor",
          "text": "MDLVertexDescriptor"
        }
      ],
      "identifier": "doc://com.apple.metalkit/documentation/MetalKit/MTKModelIOVertexDescriptorFromMetal(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTKModelIOVertexDescriptorFromMetal"
        }
      ],
      "role": "symbol",
      "title": "MTKModelIOVertexDescriptorFromMetal(_:)",
      "type": "topic",
      "url": "/documentation/metalkit/mtkmodeliovertexdescriptorfrommetal(_:)"
    },
    "doc://com.apple.metalkit/documentation/MetalKit/MTKModelIOVertexDescriptorFromMetalWithError": {
      "abstract": [
        {
          "text": "Returns a partially converted Model I/O vertex descriptor, reporting any error that occurs.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "MTKModelIOVertexDescriptorFromMetalWithError"
        }
      ],
      "identifier": "doc://com.apple.metalkit/documentation/MetalKit/MTKModelIOVertexDescriptorFromMetalWithError",
      "kind": "symbol",
      "role": "symbol",
      "title": "MTKModelIOVertexDescriptorFromMetalWithError",
      "type": "topic",
      "url": "/documentation/metalkit/mtkmodeliovertexdescriptorfrommetalwitherror"
    },
    "doc://com.externally.resolved.symbol/c:objc(cs)MDLVertexDescriptor": {
      "abstract": [
        {
          "text": "A description of the structure, format, and layout for vertex data buffers associated with a mesh.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MDLVertexDescriptor"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)MDLVertexDescriptor",
      "kind": "symbol",
      "role": "symbol",
      "title": "MDLVertexDescriptor",
      "type": "topic",
      "url": "/documentation/ModelIO/MDLVertexDescriptor"
    },
    "doc://com.externally.resolved.symbol/c:objc(cs)MTLVertexDescriptor": {
      "abstract": [
        {
          "text": "An object that describes how to organize and map data to a vertex function.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MTLVertexDescriptor"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)MTLVertexDescriptor",
      "kind": "symbol",
      "role": "symbol",
      "title": "MTLVertexDescriptor",
      "type": "topic",
      "url": "/documentation/Metal/MTLVertexDescriptor"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Converting-Between-Model-IO-and-Metal-Vertex-Descriptors",
      "generated": true,
      "identifiers": [
        "doc://com.apple.metalkit/documentation/MetalKit/MTKModelIOVertexDescriptorFromMetal(_:)"
      ],
      "title": "Converting Between Model I/O and Metal Vertex Descriptors"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "9.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "9.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.1",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.11",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "9.0",
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Function"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "MTKMetalVertexDescriptorFromModelIO"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "func"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTKMetalVertexDescriptorFromModelIO"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.metalkit/documentation/MetalKit"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Converting-Between-Model-IO-and-Metal-Vertex-Descriptors",
              "generated": true,
              "identifiers": [
                "doc://com.apple.metalkit/documentation/MetalKit/MTKMetalVertexDescriptorFromModelIOWithError",
                "doc://com.apple.metalkit/documentation/MetalKit/MTKModelIOVertexDescriptorFromMetal(_:)",
                "doc://com.apple.metalkit/documentation/MetalKit/MTKModelIOVertexDescriptorFromMetalWithError"
              ],
              "title": "Converting Between Model I/O and Metal Vertex Descriptors"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "extern"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)MTLVertexDescriptor",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(cs)MTLVertexDescriptor",
                    "text": "MTLVertexDescriptor"
                  },
                  {
                    "kind": "text",
                    "text": " * "
                  },
                  {
                    "kind": "identifier",
                    "text": "MTKMetalVertexDescriptorFromModelIO"
                  },
                  {
                    "kind": "text",
                    "text": "("
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)MDLVertexDescriptor",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(cs)MDLVertexDescriptor",
                    "text": "MDLVertexDescriptor"
                  },
                  {
                    "kind": "text",
                    "text": " * "
                  },
                  {
                    "kind": "internalParam",
                    "text": "modelIODescriptor"
                  },
                  {
                    "kind": "text",
                    "text": ");"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/1",
          "value": {
            "content": [
              {
                "anchor": "return-value",
                "level": 2,
                "text": "Return Value",
                "type": "heading"
              },
              {
                "inlineContent": [
                  {
                    "text": "A Metal vertex descriptor object.",
                    "type": "text"
                  }
                ],
                "type": "paragraph"
              }
            ],
            "kind": "content"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:objc(cs)MTLVertexDescriptor/fragments",
          "value": [
            {
              "kind": "keyword",
              "text": "@interface"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "MTLVertexDescriptor"
            },
            {
              "kind": "text",
              "text": " : "
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)NSObject",
              "text": "NSObject"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metalkit~1documentation~1MetalKit~1MTKMetalVertexDescriptorFromModelIO(_:)/title",
          "value": "MTKMetalVertexDescriptorFromModelIO"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metalkit~1documentation~1MetalKit~1MTKMetalVertexDescriptorFromModelIO(_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTKMetalVertexDescriptorFromModelIO"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:objc(cs)MDLVertexDescriptor/fragments",
          "value": [
            {
              "kind": "keyword",
              "text": "@interface"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "MDLVertexDescriptor"
            },
            {
              "kind": "text",
              "text": " : "
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)NSObject",
              "text": "NSObject"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metalkit~1documentation~1MetalKit~1MTKModelIOVertexDescriptorFromMetal(_:)/title",
          "value": "MTKModelIOVertexDescriptorFromMetal"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metalkit~1documentation~1MetalKit~1MTKModelIOVertexDescriptorFromMetal(_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTKModelIOVertexDescriptorFromMetal"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/metalkit/mtkmetalvertexdescriptorfrommodelio(_:)"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/metalkit/mtkmetalvertexdescriptorfrommodelio(_:)"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
