{
  "abstract": [
    {
      "text": "An interface for allocating a MetalKit buffer that backs the vertex data of a Model I/O mesh, suitable for use in a Metal app.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.metalkit/documentation/MetalKit"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.metalkit/documentation/MetalKit/MTKMeshBufferAllocator"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(cs)MTKMeshBufferAllocator",
    "fragments": [
      {
        "kind": "keyword",
        "text": "class"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "MTKMeshBufferAllocator"
      }
    ],
    "modules": [
      {
        "name": "MetalKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "MTKMeshBufferAllocator"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "9.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "9.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.1",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.11",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "9.0",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Class",
    "symbolKind": "class",
    "title": "MTKMeshBufferAllocator"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "class"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "MTKMeshBufferAllocator"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.metalkit/documentation/MetalKit": {
      "abstract": [
        {
          "text": "Build Metal apps quicker and easier using a common set of utility classes.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.metalkit/documentation/MetalKit",
      "kind": "symbol",
      "role": "collection",
      "title": "MetalKit",
      "type": "topic",
      "url": "/documentation/metalkit"
    },
    "doc://com.apple.metalkit/documentation/MetalKit/MTKMesh": {
      "abstract": [
        {
          "text": "A container for the vertex data of a Model I/O mesh, suitable for use in a Metal app.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MTKMesh"
        }
      ],
      "identifier": "doc://com.apple.metalkit/documentation/MetalKit/MTKMesh",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTKMesh"
        }
      ],
      "role": "symbol",
      "title": "MTKMesh",
      "type": "topic",
      "url": "/documentation/metalkit/mtkmesh"
    },
    "doc://com.apple.metalkit/documentation/MetalKit/MTKMeshBuffer": {
      "abstract": [
        {
          "text": "A buffer that backs the vertex data of a Model I/O mesh, suitable for use in a Metal app.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MTKMeshBuffer"
        }
      ],
      "identifier": "doc://com.apple.metalkit/documentation/MetalKit/MTKMeshBuffer",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTKMeshBuffer"
        }
      ],
      "role": "symbol",
      "title": "MTKMeshBuffer",
      "type": "topic",
      "url": "/documentation/metalkit/mtkmeshbuffer"
    },
    "doc://com.apple.metalkit/documentation/MetalKit/MTKMeshBufferAllocator": {
      "abstract": [
        {
          "text": "An interface for allocating a MetalKit buffer that backs the vertex data of a Model I/O mesh, suitable for use in a Metal app.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MTKMeshBufferAllocator"
        }
      ],
      "identifier": "doc://com.apple.metalkit/documentation/MetalKit/MTKMeshBufferAllocator",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTKMeshBufferAllocator"
        }
      ],
      "role": "symbol",
      "title": "MTKMeshBufferAllocator",
      "type": "topic",
      "url": "/documentation/metalkit/mtkmeshbufferallocator"
    },
    "doc://com.apple.metalkit/documentation/MetalKit/MTKMeshBufferAllocator/device": {
      "abstract": [
        {
          "text": "The device used to create Metal objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "device"
        },
        {
          "kind": "text",
          "text": ": any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(pl)MTLDevice",
          "text": "MTLDevice"
        }
      ],
      "identifier": "doc://com.apple.metalkit/documentation/MetalKit/MTKMeshBufferAllocator/device",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "device"
        }
      ],
      "role": "symbol",
      "title": "device",
      "type": "topic",
      "url": "/documentation/metalkit/mtkmeshbufferallocator/device"
    },
    "doc://com.apple.metalkit/documentation/MetalKit/MTKMeshBufferAllocator/init(device:)": {
      "abstract": [
        {
          "text": "Initializes a new allocator object.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "device"
        },
        {
          "kind": "text",
          "text": ": any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(pl)MTLDevice",
          "text": "MTLDevice"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.metalkit/documentation/MetalKit/MTKMeshBufferAllocator/init(device:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "initWithDevice:"
        }
      ],
      "role": "symbol",
      "title": "init(device:)",
      "type": "topic",
      "url": "/documentation/metalkit/mtkmeshbufferallocator/init(device:)"
    },
    "doc://com.apple.metalkit/documentation/MetalKit/MTKSubmesh": {
      "abstract": [
        {
          "text": "A container for the index data of a Model I/O submesh, suitable for use in a Metal app.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MTKSubmesh"
        }
      ],
      "identifier": "doc://com.apple.metalkit/documentation/MetalKit/MTKSubmesh",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTKSubmesh"
        }
      ],
      "role": "symbol",
      "title": "MTKSubmesh",
      "type": "topic",
      "url": "/documentation/metalkit/mtksubmesh"
    },
    "doc://com.apple.metalkit/documentation/MetalKit/conversion-functions": {
      "abstract": [
        {
          "text": "Convert between Metal and Model I/O vertex representations.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.metalkit/documentation/MetalKit/conversion-functions",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Conversion Functions",
      "type": "topic",
      "url": "/documentation/metalkit/conversion-functions"
    },
    "doc://com.apple.metalkit/documentation/MetalKit/model-errors": {
      "abstract": [
        {
          "text": "Learn about errors thrown by model handling methods.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.metalkit/documentation/MetalKit/model-errors",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Model Errors",
      "type": "topic",
      "url": "/documentation/metalkit/model-errors"
    },
    "doc://com.externally.resolved.symbol/c:objc(cs)NSObject": {
      "abstract": [
        {
          "text": "The root class of most Objective-C class hierarchies, from which subclasses inherit a basic interface to the runtime system and the ability to behave as Objective-C objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "class "
        },
        {
          "kind": "identifier",
          "text": "NSObject"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSObject",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSObject",
      "type": "topic",
      "url": "/documentation/objectivec/nsobject"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)MDLMeshBufferAllocator": {
      "abstract": [
        {
          "text": "The general interface for managing allocation of data buffers to be used in loading, processing, and rendering meshes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MDLMeshBufferAllocator"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(pl)NSObject",
          "text": "NSObjectProtocol"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)MDLMeshBufferAllocator",
      "kind": "symbol",
      "role": "symbol",
      "title": "MDLMeshBufferAllocator",
      "type": "topic",
      "url": "/documentation/ModelIO/MDLMeshBufferAllocator"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)NSObject": {
      "abstract": [
        {
          "text": "The group of methods that are fundamental to all Objective-C objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "protocol "
        },
        {
          "kind": "identifier",
          "text": "NSObjectProtocol"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSObject",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSObjectProtocol",
      "type": "topic",
      "url": "/documentation/objectivec/nsobjectprotocol"
    },
    "doc://com.externally.resolved.symbol/s:SH": {
      "abstract": [
        {
          "text": "A type that can be hashed into a `Hasher` to produce an integer hash value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Hashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SQ",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SH",
      "kind": "symbol",
      "role": "symbol",
      "title": "Hashable",
      "type": "topic",
      "url": "/documentation/Swift/Hashable"
    },
    "doc://com.externally.resolved.symbol/s:SQ": {
      "abstract": [
        {
          "text": "A type that can be compared for value equality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SQ",
      "kind": "symbol",
      "role": "symbol",
      "title": "Equatable",
      "type": "topic",
      "url": "/documentation/Swift/Equatable"
    },
    "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP": {
      "abstract": [
        {
          "text": "A type with a customized textual representation.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CustomStringConvertible"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CustomStringConvertible",
      "type": "topic",
      "url": "/documentation/Swift/CustomStringConvertible"
    },
    "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP": {
      "abstract": [
        {
          "text": "A type with a customized textual representation suitable for debugging purposes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CustomDebugStringConvertible"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CustomDebugStringConvertible",
      "type": "topic",
      "url": "/documentation/Swift/CustomDebugStringConvertible"
    },
    "doc://com.externally.resolved.symbol/s:s7CVarArgP": {
      "abstract": [
        {
          "text": "A type whose instances can be encoded, and appropriately passed, as elements of a C `va_list`.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CVarArg"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s7CVarArgP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CVarArg",
      "type": "topic",
      "url": "/documentation/Swift/CVarArg"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/c:objc(cs)NSObject"
      ],
      "kind": "relationships",
      "title": "Inherits From",
      "type": "inheritsFrom"
    },
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:s7CVarArgP",
        "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP",
        "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP",
        "doc://com.externally.resolved.symbol/s:SQ",
        "doc://com.externally.resolved.symbol/s:SH",
        "doc://com.externally.resolved.symbol/c:objc(pl)MDLMeshBufferAllocator",
        "doc://com.externally.resolved.symbol/c:objc(pl)NSObject"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Model-Handling",
      "generated": true,
      "identifiers": [
        "doc://com.apple.metalkit/documentation/MetalKit/MTKMesh",
        "doc://com.apple.metalkit/documentation/MetalKit/MTKMeshBuffer",
        "doc://com.apple.metalkit/documentation/MetalKit/MTKSubmesh",
        "doc://com.apple.metalkit/documentation/MetalKit/conversion-functions",
        "doc://com.apple.metalkit/documentation/MetalKit/model-errors"
      ],
      "title": "Model Handling"
    }
  ],
  "topicSections": [
    {
      "anchor": "Initialization",
      "identifiers": [
        "doc://com.apple.metalkit/documentation/MetalKit/MTKMeshBufferAllocator/init(device:)"
      ],
      "title": "Initialization"
    },
    {
      "anchor": "Device",
      "identifiers": [
        "doc://com.apple.metalkit/documentation/MetalKit/MTKMeshBufferAllocator/device"
      ],
      "title": "Device"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "9.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "9.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.1",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.11",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "9.0",
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Class"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "MTKMeshBufferAllocator"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "class"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTKMeshBufferAllocator"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MTKMeshBufferAllocator"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.metalkit/documentation/MetalKit"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Initialization",
              "identifiers": [
                "doc://com.apple.metalkit/documentation/MetalKit/MTKMeshBufferAllocator/init(device:)"
              ],
              "title": "Initialization"
            },
            {
              "anchor": "Device",
              "identifiers": [
                "doc://com.apple.metalkit/documentation/MetalKit/MTKMeshBufferAllocator/device"
              ],
              "title": "Device"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": [
            {
              "identifiers": [
                "doc://com.externally.resolved.symbol/c:objc(cs)NSObject"
              ],
              "kind": "relationships",
              "title": "Inherits From",
              "type": "inheritsFrom"
            },
            {
              "identifiers": [
                "doc://com.externally.resolved.symbol/c:objc(pl)MDLMeshBufferAllocator"
              ],
              "kind": "relationships",
              "title": "Conforms To",
              "type": "conformsTo"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Model-Handling",
              "generated": true,
              "identifiers": [
                "doc://com.apple.metalkit/documentation/MetalKit/MTKMesh",
                "doc://com.apple.metalkit/documentation/MetalKit/MTKMeshBuffer",
                "doc://com.apple.metalkit/documentation/MetalKit/MTKSubmesh",
                "doc://com.apple.metalkit/documentation/MetalKit/conversion-functions",
                "doc://com.apple.metalkit/documentation/MetalKit/model-errors"
              ],
              "title": "Model Handling"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "@interface"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "MTKMeshBufferAllocator"
                  },
                  {
                    "kind": "text",
                    "text": " : "
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSObject",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(cs)NSObject",
                    "text": "NSObject"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:objc(pl)NSObject/title",
          "value": "NSObject"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metalkit~1documentation~1MetalKit~1MTKMeshBuffer/title",
          "value": "MTKMeshBuffer"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metalkit~1documentation~1MetalKit~1MTKMeshBuffer/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTKMeshBuffer"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metalkit~1documentation~1MetalKit~1MTKMeshBuffer/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MTKMeshBuffer"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metalkit~1documentation~1MetalKit~1MTKMeshBufferAllocator/title",
          "value": "MTKMeshBufferAllocator"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metalkit~1documentation~1MetalKit~1MTKMeshBufferAllocator/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTKMeshBufferAllocator"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metalkit~1documentation~1MetalKit~1MTKMeshBufferAllocator/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MTKMeshBufferAllocator"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metalkit~1documentation~1MetalKit~1MTKMeshBufferAllocator~1device/title",
          "value": "device"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metalkit~1documentation~1MetalKit~1MTKMeshBufferAllocator~1device/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "device"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metalkit~1documentation~1MetalKit~1MTKMeshBufferAllocator~1init(device:)/title",
          "value": "initWithDevice:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metalkit~1documentation~1MetalKit~1MTKMeshBufferAllocator~1init(device:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "initWithDevice:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metalkit~1documentation~1MetalKit~1MTKSubmesh/title",
          "value": "MTKSubmesh"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metalkit~1documentation~1MetalKit~1MTKSubmesh/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTKSubmesh"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metalkit~1documentation~1MetalKit~1MTKSubmesh/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MTKSubmesh"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metalkit~1documentation~1MetalKit~1MTKMesh/title",
          "value": "MTKMesh"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metalkit~1documentation~1MetalKit~1MTKMesh/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTKMesh"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metalkit~1documentation~1MetalKit~1MTKMesh/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MTKMesh"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:objc(pl)MDLMeshBufferAllocator/fragments",
          "value": [
            {
              "kind": "keyword",
              "text": "@protocol"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "MDLMeshBufferAllocator"
            },
            {
              "kind": "text",
              "text": " <"
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(pl)NSObject",
              "text": "NSObject"
            },
            {
              "kind": "text",
              "text": ">"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/metalkit/mtkmeshbufferallocator"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/metalkit/mtkmeshbufferallocator"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
