{
  "abstract": [
    {
      "text": "Methods for responding to a MetalKit view’s drawing and resizing events.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.metalkit/documentation/MetalKit"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.metalkit/documentation/MetalKit/MTKViewDelegate"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(pl)MTKViewDelegate",
    "fragments": [
      {
        "kind": "keyword",
        "text": "protocol"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "MTKViewDelegate"
      }
    ],
    "modules": [
      {
        "name": "MetalKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "MTKViewDelegate"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "9.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "9.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.1",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.11",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "9.0",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Protocol",
    "symbolKind": "protocol",
    "title": "MTKViewDelegate"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "protocol"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "MTKViewDelegate"
            },
            {
              "kind": "text",
              "text": " : "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSObject",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(pl)NSObject",
              "text": "NSObjectProtocol"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "You can set an object that implements the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.metalkit/documentation/MetalKit/MTKViewDelegate",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " protocol as a ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.metalkit/documentation/MetalKit/MTKView",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " object’s delegate. Use a delegate to provide a drawing method to a ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.metalkit/documentation/MetalKit/MTKView",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " object and respond to rendering events without subclassing the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.metalkit/documentation/MetalKit/MTKView",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " class.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.metalkit/documentation/MetalKit": {
      "abstract": [
        {
          "text": "Build Metal apps quicker and easier using a common set of utility classes.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.metalkit/documentation/MetalKit",
      "kind": "symbol",
      "role": "collection",
      "title": "MetalKit",
      "type": "topic",
      "url": "/documentation/metalkit"
    },
    "doc://com.apple.metalkit/documentation/MetalKit/MTKView": {
      "abstract": [
        {
          "text": "A specialized view that creates, configures, and displays Metal objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MTKView"
        }
      ],
      "identifier": "doc://com.apple.metalkit/documentation/MetalKit/MTKView",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTKView"
        }
      ],
      "role": "symbol",
      "title": "MTKView",
      "type": "topic",
      "url": "/documentation/metalkit/mtkview"
    },
    "doc://com.apple.metalkit/documentation/MetalKit/MTKViewDelegate": {
      "abstract": [
        {
          "text": "Methods for responding to a MetalKit view’s drawing and resizing events.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MTKViewDelegate"
        }
      ],
      "identifier": "doc://com.apple.metalkit/documentation/MetalKit/MTKViewDelegate",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTKViewDelegate"
        }
      ],
      "role": "symbol",
      "title": "MTKViewDelegate",
      "type": "topic",
      "url": "/documentation/metalkit/mtkviewdelegate"
    },
    "doc://com.apple.metalkit/documentation/MetalKit/MTKViewDelegate/draw(in:)": {
      "abstract": [
        {
          "text": "Draws the view’s contents.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "draw"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "in"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)MTKView",
          "text": "MTKView"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.metalkit/documentation/MetalKit/MTKViewDelegate/draw(in:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "drawInMTKView:"
        }
      ],
      "required": true,
      "role": "symbol",
      "title": "draw(in:)",
      "type": "topic",
      "url": "/documentation/metalkit/mtkviewdelegate/draw(in:)"
    },
    "doc://com.apple.metalkit/documentation/MetalKit/MTKViewDelegate/mtkView(_:drawableSizeWillChange:)": {
      "abstract": [
        {
          "text": "Updates the view’s contents upon receiving a change in layout, resolution, or size.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "mtkView"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)MTKView",
          "text": "MTKView"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "drawableSizeWillChange"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@CGSize",
          "text": "CGSize"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.metalkit/documentation/MetalKit/MTKViewDelegate/mtkView(_:drawableSizeWillChange:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "mtkView:drawableSizeWillChange:"
        }
      ],
      "required": true,
      "role": "symbol",
      "title": "mtkView(_:drawableSizeWillChange:)",
      "type": "topic",
      "url": "/documentation/metalkit/mtkviewdelegate/mtkview(_:drawablesizewillchange:)"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)NSObject": {
      "abstract": [
        {
          "text": "The group of methods that are fundamental to all Objective-C objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "protocol "
        },
        {
          "kind": "identifier",
          "text": "NSObjectProtocol"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSObject",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSObjectProtocol",
      "type": "topic",
      "url": "/documentation/objectivec/nsobjectprotocol"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/c:objc(pl)NSObject"
      ],
      "kind": "relationships",
      "title": "Inherits From",
      "type": "inheritsFrom"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "View-Management",
      "generated": true,
      "identifiers": [
        "doc://com.apple.metalkit/documentation/MetalKit/MTKView"
      ],
      "title": "View Management"
    }
  ],
  "topicSections": [
    {
      "anchor": "Changing-the-Views-Layout",
      "identifiers": [
        "doc://com.apple.metalkit/documentation/MetalKit/MTKViewDelegate/mtkView(_:drawableSizeWillChange:)"
      ],
      "title": "Changing the View’s Layout"
    },
    {
      "anchor": "Drawing-the-Views-Contents",
      "identifiers": [
        "doc://com.apple.metalkit/documentation/MetalKit/MTKViewDelegate/draw(in:)"
      ],
      "title": "Drawing the View’s Contents"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "9.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "9.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.1",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.11",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "9.0",
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Protocol"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "MTKViewDelegate"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "protocol"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTKViewDelegate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MTKViewDelegate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.metalkit/documentation/MetalKit"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Changing-the-Views-Layout",
              "identifiers": [
                "doc://com.apple.metalkit/documentation/MetalKit/MTKViewDelegate/mtkView(_:drawableSizeWillChange:)"
              ],
              "title": "Changing the View’s Layout"
            },
            {
              "anchor": "Drawing-the-Views-Contents",
              "identifiers": [
                "doc://com.apple.metalkit/documentation/MetalKit/MTKViewDelegate/draw(in:)"
              ],
              "title": "Drawing the View’s Contents"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": [
            {
              "identifiers": [
                "doc://com.externally.resolved.symbol/c:objc(pl)NSObject"
              ],
              "kind": "relationships",
              "title": "Inherits From",
              "type": "inheritsFrom"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "View-Management",
              "generated": true,
              "identifiers": [
                "doc://com.apple.metalkit/documentation/MetalKit/MTKView"
              ],
              "title": "View Management"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "@protocol"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "MTKViewDelegate"
                  },
                  {
                    "kind": "text",
                    "text": " <"
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSObject",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(pl)NSObject",
                    "text": "NSObject"
                  },
                  {
                    "kind": "text",
                    "text": ">"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metalkit~1documentation~1MetalKit~1MTKViewDelegate/title",
          "value": "MTKViewDelegate"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metalkit~1documentation~1MetalKit~1MTKViewDelegate/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTKViewDelegate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metalkit~1documentation~1MetalKit~1MTKViewDelegate/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MTKViewDelegate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metalkit~1documentation~1MetalKit~1MTKViewDelegate~1mtkView(_:drawableSizeWillChange:)/title",
          "value": "mtkView:drawableSizeWillChange:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metalkit~1documentation~1MetalKit~1MTKViewDelegate~1mtkView(_:drawableSizeWillChange:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "mtkView:drawableSizeWillChange:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metalkit~1documentation~1MetalKit~1MTKViewDelegate~1draw(in:)/title",
          "value": "drawInMTKView:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metalkit~1documentation~1MetalKit~1MTKViewDelegate~1draw(in:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "drawInMTKView:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metalkit~1documentation~1MetalKit~1MTKView/title",
          "value": "MTKView"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metalkit~1documentation~1MetalKit~1MTKView/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTKView"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metalkit~1documentation~1MetalKit~1MTKView/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MTKView"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:objc(pl)NSObject/title",
          "value": "NSObject"
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/metalkit/mtkviewdelegate"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/metalkit/mtkviewdelegate"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
