{
  "abstract": [
    {
      "text": "Points of interest only. Specify this value when you want the search string to yield completions that correspond to a specific point-of-interest on the map.",
      "type": "text"
    }
  ],
  "deprecationSummary": [
    {
      "inlineContent": [
        {
          "text": "Use one of the options available in ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.mapkit/documentation/MapKit/MKLocalSearchCompleter/ResultType",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " instead.",
          "type": "text"
        }
      ],
      "type": "paragraph"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.mapkit/documentation/MapKit",
        "doc://com.apple.mapkit/documentation/MapKit/MKLocalSearchCompleter",
        "doc://com.apple.mapkit/documentation/MapKit/MKLocalSearchCompleter/FilterType-swift.enum"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.mapkit/documentation/MapKit/MKLocalSearchCompleter/FilterType-swift.enum/locationsOnly"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@MKSearchCompletionFilterType@MKSearchCompletionFilterTypeLocationsOnly",
    "fragments": [
      {
        "kind": "keyword",
        "text": "case"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "locationsOnly"
      }
    ],
    "modules": [
      {
        "name": "MapKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "MKSearchCompletionFilterTypeLocationsOnly"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "13.0",
        "introducedAt": "9.3",
        "message": "Use MKLocalSearchCompleterResultType",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "13.0",
        "introducedAt": "9.3",
        "message": "Use MKLocalSearchCompleterResultType",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "13.1",
        "introducedAt": "13.1",
        "message": "Use MKLocalSearchCompleterResultType",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "10.15",
        "introducedAt": "10.11.4",
        "message": "Use MKLocalSearchCompleterResultType",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "13.0",
        "introducedAt": "9.2",
        "message": "Use MKLocalSearchCompleterResultType",
        "name": "tvOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Case",
    "symbolKind": "case",
    "title": "MKLocalSearchCompleter.FilterType.locationsOnly"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "case"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "locationsOnly"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.mapkit/documentation/MapKit": {
      "abstract": [
        {
          "text": "Display map or satellite imagery within your app, call out points of interest, and determine placemark information for map coordinates.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.mapkit/documentation/MapKit",
      "kind": "symbol",
      "role": "collection",
      "title": "MapKit",
      "type": "topic",
      "url": "/documentation/mapkit"
    },
    "doc://com.apple.mapkit/documentation/MapKit/MKLocalSearchCompleter": {
      "abstract": [
        {
          "text": "A utility object for generating a list of completion strings based on a partial search string that you provide.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MKLocalSearchCompleter"
        }
      ],
      "identifier": "doc://com.apple.mapkit/documentation/MapKit/MKLocalSearchCompleter",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MKLocalSearchCompleter"
        }
      ],
      "role": "symbol",
      "title": "MKLocalSearchCompleter",
      "type": "topic",
      "url": "/documentation/mapkit/mklocalsearchcompleter"
    },
    "doc://com.apple.mapkit/documentation/MapKit/MKLocalSearchCompleter/FilterType-swift.enum": {
      "abstract": [
        {
          "text": "Constants indicating the types of search completions to return.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "FilterType"
        }
      ],
      "identifier": "doc://com.apple.mapkit/documentation/MapKit/MKLocalSearchCompleter/FilterType-swift.enum",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "FilterType"
        }
      ],
      "role": "symbol",
      "title": "MKLocalSearchCompleter.FilterType",
      "type": "topic",
      "url": "/documentation/mapkit/mklocalsearchcompleter/filtertype-swift.enum"
    },
    "doc://com.apple.mapkit/documentation/MapKit/MKLocalSearchCompleter/FilterType-swift.enum/locationsAndQueries": {
      "abstract": [
        {
          "text": "Points of interest and query suggestions. Specify this value when you want both map-based points of interest and common query terms used to find locations. For example, the search string ",
          "type": "text"
        },
        {
          "code": "cof",
          "type": "codeVoice"
        },
        {
          "text": " yields a completion for ",
          "type": "text"
        },
        {
          "inlineContent": [
            {
              "text": "coffee",
              "type": "text"
            }
          ],
          "type": "emphasis"
        },
        {
          "text": ".",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "locationsAndQueries"
        }
      ],
      "identifier": "doc://com.apple.mapkit/documentation/MapKit/MKLocalSearchCompleter/FilterType-swift.enum/locationsAndQueries",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MKSearchCompletionFilterTypeLocationsAndQueries"
        }
      ],
      "role": "symbol",
      "title": "MKLocalSearchCompleter.FilterType.locationsAndQueries",
      "type": "topic",
      "url": "/documentation/mapkit/mklocalsearchcompleter/filtertype-swift.enum/locationsandqueries"
    },
    "doc://com.apple.mapkit/documentation/MapKit/MKLocalSearchCompleter/FilterType-swift.enum/locationsOnly": {
      "abstract": [
        {
          "text": "Points of interest only. Specify this value when you want the search string to yield completions that correspond to a specific point-of-interest on the map.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "locationsOnly"
        }
      ],
      "identifier": "doc://com.apple.mapkit/documentation/MapKit/MKLocalSearchCompleter/FilterType-swift.enum/locationsOnly",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MKSearchCompletionFilterTypeLocationsOnly"
        }
      ],
      "role": "symbol",
      "title": "MKLocalSearchCompleter.FilterType.locationsOnly",
      "type": "topic",
      "url": "/documentation/mapkit/mklocalsearchcompleter/filtertype-swift.enum/locationsonly"
    },
    "doc://com.apple.mapkit/documentation/MapKit/MKLocalSearchCompleter/ResultType": {
      "abstract": [
        {
          "text": "Options that indicate types of search completions.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ResultType"
        }
      ],
      "identifier": "doc://com.apple.mapkit/documentation/MapKit/MKLocalSearchCompleter/ResultType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ResultType"
        }
      ],
      "role": "symbol",
      "title": "MKLocalSearchCompleter.ResultType",
      "type": "topic",
      "url": "/documentation/mapkit/mklocalsearchcompleter/resulttype"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Constants",
      "generated": true,
      "identifiers": [
        "doc://com.apple.mapkit/documentation/MapKit/MKLocalSearchCompleter/FilterType-swift.enum/locationsAndQueries",
        "doc://com.apple.mapkit/documentation/MapKit/MKLocalSearchCompleter/FilterType-swift.enum/locationsAndQueries"
      ],
      "title": "Constants"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "deprecatedAt": "13.0",
              "introducedAt": "9.3",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "deprecatedAt": "13.0",
              "introducedAt": "9.3",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "deprecatedAt": "13.1",
              "introducedAt": "13.1",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "deprecatedAt": "10.15",
              "introducedAt": "10.11.4",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "deprecatedAt": "13.0",
              "introducedAt": "9.2",
              "name": "tvOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration Case"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "MKSearchCompletionFilterTypeLocationsOnly"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "case"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MKSearchCompletionFilterTypeLocationsOnly"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.mapkit/documentation/MapKit",
                "doc://com.apple.mapkit/documentation/MapKit/MKLocalSearchCompleter/FilterType-swift.enum"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Constants",
              "generated": true,
              "identifiers": [
                "doc://com.apple.mapkit/documentation/MapKit/MKLocalSearchCompleter/FilterType-swift.enum/locationsAndQueries",
                "doc://com.apple.mapkit/documentation/MapKit/MKLocalSearchCompleter/FilterType-swift.enum/locationsAndQueries"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "identifier",
                    "text": "MKSearchCompletionFilterTypeLocationsOnly"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/deprecationSummary",
          "value": [
            {
              "inlineContent": [
                {
                  "text": "Use one of the options available in ",
                  "type": "text"
                },
                {
                  "identifier": "doc://com.apple.mapkit/documentation/MapKit/MKLocalSearchCompleter/ResultType",
                  "isActive": true,
                  "type": "reference"
                },
                {
                  "text": " instead.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKLocalSearchCompleter~1FilterType-swift.enum~1locationsOnly/title",
          "value": "MKSearchCompletionFilterTypeLocationsOnly"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKLocalSearchCompleter~1FilterType-swift.enum~1locationsOnly/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MKSearchCompletionFilterTypeLocationsOnly"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKLocalSearchCompleter/title",
          "value": "MKLocalSearchCompleter"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKLocalSearchCompleter/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MKLocalSearchCompleter"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKLocalSearchCompleter/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MKLocalSearchCompleter"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKLocalSearchCompleter~1FilterType-swift.enum~1locationsAndQueries/title",
          "value": "MKSearchCompletionFilterTypeLocationsAndQueries"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKLocalSearchCompleter~1FilterType-swift.enum~1locationsAndQueries/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MKSearchCompletionFilterTypeLocationsAndQueries"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKLocalSearchCompleter~1FilterType-swift.enum/title",
          "value": "MKSearchCompletionFilterType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKLocalSearchCompleter~1FilterType-swift.enum/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MKSearchCompletionFilterType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKLocalSearchCompleter~1FilterType-swift.enum/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MKSearchCompletionFilterType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKLocalSearchCompleter~1ResultType/title",
          "value": "MKLocalSearchCompleterResultType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKLocalSearchCompleter~1ResultType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MKLocalSearchCompleterResultType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKLocalSearchCompleter~1ResultType/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MKLocalSearchCompleterResultType"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/mapkit/mklocalsearchcompleter/filtertype-swift.enum/locationsonly"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/mapkit/mklocalsearchcompleter/filtertype-swift.enum/locationsonly"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
