{
  "abstract": [
    {
      "text": "The lens specification for the right eye.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.healthkit/documentation/HealthKit",
        "doc://com.apple.healthkit/documentation/HealthKit/HKGlassesPrescription"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.healthkit/documentation/HealthKit/HKGlassesPrescription/rightEye"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(cs)HKGlassesPrescription(py)rightEye",
    "fragments": [
      {
        "kind": "keyword",
        "text": "var"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "rightEye"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:objc(cs)HKGlassesLensSpecification",
        "text": "HKGlassesLensSpecification"
      },
      {
        "kind": "text",
        "text": "?"
      }
    ],
    "modules": [
      {
        "name": "HealthKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "rightEye"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "16.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "16.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "16.0",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.0",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "9.0",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Instance Property",
    "symbolKind": "property",
    "title": "rightEye"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "attribute",
              "text": "@NSCopying"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "keyword",
              "text": "var"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "rightEye"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKGlassesLensSpecification",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)HKGlassesLensSpecification",
              "text": "HKGlassesLensSpecification"
            },
            {
              "kind": "text",
              "text": "? { "
            },
            {
              "kind": "keyword",
              "text": "get"
            },
            {
              "kind": "text",
              "text": " }"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.healthkit/documentation/HealthKit": {
      "abstract": [
        {
          "text": "Access and share health and fitness data while maintaining the user’s privacy and control.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit",
      "kind": "symbol",
      "role": "collection",
      "title": "HealthKit",
      "type": "topic",
      "url": "/documentation/healthkit"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/HKGlassesLensSpecification": {
      "abstract": [
        {
          "text": "An object that contains the glasses prescription data for one eye.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "HKGlassesLensSpecification"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKGlassesLensSpecification",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HKGlassesLensSpecification"
        }
      ],
      "role": "symbol",
      "title": "HKGlassesLensSpecification",
      "type": "topic",
      "url": "/documentation/healthkit/hkglasseslensspecification"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/HKGlassesPrescription": {
      "abstract": [
        {
          "text": "A sample that stores a prescription for glasses.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "HKGlassesPrescription"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKGlassesPrescription",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HKGlassesPrescription"
        }
      ],
      "role": "symbol",
      "title": "HKGlassesPrescription",
      "type": "topic",
      "url": "/documentation/healthkit/hkglassesprescription"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/HKGlassesPrescription/leftEye": {
      "abstract": [
        {
          "text": "The lens specification for the left eye.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "leftEye"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)HKGlassesLensSpecification",
          "text": "HKGlassesLensSpecification"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKGlassesPrescription/leftEye",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "leftEye"
        }
      ],
      "role": "symbol",
      "title": "leftEye",
      "type": "topic",
      "url": "/documentation/healthkit/hkglassesprescription/lefteye"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/HKGlassesPrescription/rightEye": {
      "abstract": [
        {
          "text": "The lens specification for the right eye.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "rightEye"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)HKGlassesLensSpecification",
          "text": "HKGlassesLensSpecification"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKGlassesPrescription/rightEye",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "rightEye"
        }
      ],
      "role": "symbol",
      "title": "rightEye",
      "type": "topic",
      "url": "/documentation/healthkit/hkglassesprescription/righteye"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Accessing-the-glasses-prescription-data",
      "generated": true,
      "identifiers": [
        "doc://com.apple.healthkit/documentation/HealthKit/HKGlassesPrescription/leftEye"
      ],
      "title": "Accessing the glasses prescription data"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "16.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "16.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "16.0",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.0",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "9.0",
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Instance Property"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "rightEye"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "property"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "rightEye"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.healthkit/documentation/HealthKit",
                "doc://com.apple.healthkit/documentation/HealthKit/HKGlassesPrescription"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Accessing-the-glasses-prescription-data",
              "generated": true,
              "identifiers": [
                "doc://com.apple.healthkit/documentation/HealthKit/HKGlassesPrescription/leftEye"
              ],
              "title": "Accessing the glasses prescription data"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "@property"
                  },
                  {
                    "kind": "text",
                    "text": " ("
                  },
                  {
                    "kind": "keyword",
                    "text": "nonatomic"
                  },
                  {
                    "kind": "text",
                    "text": ", "
                  },
                  {
                    "kind": "keyword",
                    "text": "copy"
                  },
                  {
                    "kind": "text",
                    "text": ", "
                  },
                  {
                    "kind": "keyword",
                    "text": "readonly"
                  },
                  {
                    "kind": "text",
                    "text": ") "
                  },
                  {
                    "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKGlassesLensSpecification",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(cs)HKGlassesLensSpecification",
                    "text": "HKGlassesLensSpecification"
                  },
                  {
                    "kind": "text",
                    "text": " * "
                  },
                  {
                    "kind": "identifier",
                    "text": "rightEye"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKGlassesPrescription/title",
          "value": "HKGlassesPrescription"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKGlassesPrescription/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HKGlassesPrescription"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKGlassesPrescription/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "HKGlassesPrescription"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKGlassesLensSpecification/title",
          "value": "HKGlassesLensSpecification"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKGlassesLensSpecification/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HKGlassesLensSpecification"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKGlassesLensSpecification/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "HKGlassesLensSpecification"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKGlassesPrescription~1leftEye/title",
          "value": "leftEye"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKGlassesPrescription~1leftEye/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "leftEye"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKGlassesPrescription~1rightEye/title",
          "value": "rightEye"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKGlassesPrescription~1rightEye/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "rightEye"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/healthkit/hkglassesprescription/righteye"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/healthkit/hkglassesprescription/righteye"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
