{
  "abstract": [
    {
      "code": "NSNumber",
      "type": "codeVoice"
    },
    {
      "text": ", containing a Boolean value that is ",
      "type": "text"
    },
    {
      "identifier": "doc://com.apple.documentation/documentation/swift/true",
      "isActive": true,
      "type": "reference"
    },
    {
      "text": " if pages are centered vertically.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.appkit/documentation/AppKit",
        "doc://com.apple.appkit/documentation/AppKit/NSPrintInfo",
        "doc://com.apple.appkit/documentation/AppKit/NSPrintInfo/AttributeKey"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.appkit/documentation/AppKit/NSPrintInfo/AttributeKey/verticallyCentered"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "extendedModule": "AppKit",
    "externalID": "c:@NSPrintVerticallyCentered",
    "fragments": [
      {
        "kind": "keyword",
        "text": "static"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "keyword",
        "text": "let"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "verticallyCentered"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:objc(cs)NSPrintInfo",
        "text": "NSPrintInfo"
      },
      {
        "kind": "text",
        "text": "."
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@T@NSPrintInfoAttributeKey",
        "text": "AttributeKey"
      }
    ],
    "modules": [
      {
        "name": "AppKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "NSPrintVerticallyCentered"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Type Property",
    "symbolKind": "property",
    "title": "verticallyCentered"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "macOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "static"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "keyword",
              "text": "let"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "verticallyCentered"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.appkit/documentation/AppKit/NSPrintInfo",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)NSPrintInfo",
              "text": "NSPrintInfo"
            },
            {
              "kind": "text",
              "text": "."
            },
            {
              "identifier": "doc://com.apple.appkit/documentation/AppKit/NSPrintInfo/AttributeKey",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@NSPrintInfoAttributeKey",
              "text": "AttributeKey"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.appkit/documentation/AppKit": {
      "abstract": [
        {
          "text": "Construct and manage a graphical, event-driven user interface for your macOS app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit",
      "kind": "symbol",
      "role": "collection",
      "title": "AppKit",
      "type": "topic",
      "url": "/documentation/appkit"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSPrintInfo": {
      "abstract": [
        {
          "text": "An object that stores information that’s used to generate printed output.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSPrintInfo"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSPrintInfo",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSPrintInfo"
        }
      ],
      "role": "symbol",
      "title": "NSPrintInfo",
      "type": "topic",
      "url": "/documentation/appkit/nsprintinfo"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSPrintInfo/AttributeKey": {
      "abstract": [
        {
          "text": "Constants that specify print job attributes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AttributeKey"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSPrintInfo/AttributeKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AttributeKey"
        }
      ],
      "role": "symbol",
      "title": "NSPrintInfo.AttributeKey",
      "type": "topic",
      "url": "/documentation/appkit/nsprintinfo/attributekey"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSPrintInfo/AttributeKey/bottomMargin": {
      "abstract": [
        {
          "code": "NSNumber",
          "type": "codeVoice"
        },
        {
          "text": ", containing a floating-point value that specifies the bottom margin, in points.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "bottomMargin"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSPrintInfo",
          "text": "NSPrintInfo"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSPrintInfoAttributeKey",
          "text": "AttributeKey"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSPrintInfo/AttributeKey/bottomMargin",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSPrintBottomMargin"
        }
      ],
      "role": "symbol",
      "title": "bottomMargin",
      "type": "topic",
      "url": "/documentation/appkit/nsprintinfo/attributekey/bottommargin"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSPrintInfo/AttributeKey/horizontalPagination": {
      "abstract": [
        {
          "code": "NSNumber",
          "type": "codeVoice"
        },
        {
          "text": ", containing a ",
          "type": "text"
        },
        {
          "code": "NSPrintingPaginationMode",
          "type": "codeVoice"
        },
        {
          "text": " value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "horizontalPagination"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSPrintInfo",
          "text": "NSPrintInfo"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSPrintInfoAttributeKey",
          "text": "AttributeKey"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSPrintInfo/AttributeKey/horizontalPagination",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSPrintHorizontalPagination"
        }
      ],
      "role": "symbol",
      "title": "horizontalPagination",
      "type": "topic",
      "url": "/documentation/appkit/nsprintinfo/attributekey/horizontalpagination"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSPrintInfo/AttributeKey/horizontallyCentered": {
      "abstract": [
        {
          "code": "NSNumber",
          "type": "codeVoice"
        },
        {
          "text": ", containing a Boolean value that is ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.documentation/documentation/swift/true",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " if pages are centered horizontally.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "horizontallyCentered"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSPrintInfo",
          "text": "NSPrintInfo"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSPrintInfoAttributeKey",
          "text": "AttributeKey"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSPrintInfo/AttributeKey/horizontallyCentered",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSPrintHorizontallyCentered"
        }
      ],
      "role": "symbol",
      "title": "horizontallyCentered",
      "type": "topic",
      "url": "/documentation/appkit/nsprintinfo/attributekey/horizontallycentered"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSPrintInfo/AttributeKey/leftMargin": {
      "abstract": [
        {
          "code": "NSNumber",
          "type": "codeVoice"
        },
        {
          "text": ", containing a floating-point value that specifies the left margin, in points.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "leftMargin"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSPrintInfo",
          "text": "NSPrintInfo"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSPrintInfoAttributeKey",
          "text": "AttributeKey"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSPrintInfo/AttributeKey/leftMargin",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSPrintLeftMargin"
        }
      ],
      "role": "symbol",
      "title": "leftMargin",
      "type": "topic",
      "url": "/documentation/appkit/nsprintinfo/attributekey/leftmargin"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSPrintInfo/AttributeKey/rightMargin": {
      "abstract": [
        {
          "code": "NSNumber",
          "type": "codeVoice"
        },
        {
          "text": ", containing a floating-point value that specifies the right margin, in points.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "rightMargin"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSPrintInfo",
          "text": "NSPrintInfo"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSPrintInfoAttributeKey",
          "text": "AttributeKey"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSPrintInfo/AttributeKey/rightMargin",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSPrintRightMargin"
        }
      ],
      "role": "symbol",
      "title": "rightMargin",
      "type": "topic",
      "url": "/documentation/appkit/nsprintinfo/attributekey/rightmargin"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSPrintInfo/AttributeKey/topMargin": {
      "abstract": [
        {
          "code": "NSNumber",
          "type": "codeVoice"
        },
        {
          "text": ", containing a floating-point value that specifies the top margin, in points.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "topMargin"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSPrintInfo",
          "text": "NSPrintInfo"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSPrintInfoAttributeKey",
          "text": "AttributeKey"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSPrintInfo/AttributeKey/topMargin",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSPrintTopMargin"
        }
      ],
      "role": "symbol",
      "title": "topMargin",
      "type": "topic",
      "url": "/documentation/appkit/nsprintinfo/attributekey/topmargin"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSPrintInfo/AttributeKey/verticalPagination": {
      "abstract": [
        {
          "code": "NSNumber",
          "type": "codeVoice"
        },
        {
          "text": ", containing a ",
          "type": "text"
        },
        {
          "code": "NSPrintingPaginationMode",
          "type": "codeVoice"
        },
        {
          "text": " value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "verticalPagination"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSPrintInfo",
          "text": "NSPrintInfo"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSPrintInfoAttributeKey",
          "text": "AttributeKey"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSPrintInfo/AttributeKey/verticalPagination",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSPrintVerticalPagination"
        }
      ],
      "role": "symbol",
      "title": "verticalPagination",
      "type": "topic",
      "url": "/documentation/appkit/nsprintinfo/attributekey/verticalpagination"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSPrintInfo/AttributeKey/verticallyCentered": {
      "abstract": [
        {
          "code": "NSNumber",
          "type": "codeVoice"
        },
        {
          "text": ", containing a Boolean value that is ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.documentation/documentation/swift/true",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " if pages are centered vertically.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "verticallyCentered"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSPrintInfo",
          "text": "NSPrintInfo"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSPrintInfoAttributeKey",
          "text": "AttributeKey"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSPrintInfo/AttributeKey/verticallyCentered",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSPrintVerticallyCentered"
        }
      ],
      "role": "symbol",
      "title": "verticallyCentered",
      "type": "topic",
      "url": "/documentation/appkit/nsprintinfo/attributekey/verticallycentered"
    },
    "doc://com.apple.documentation/documentation/swift/true": {
      "abstract": [
        {
          "text": "A true value.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/swift/true",
      "kind": "symbol",
      "role": "symbol",
      "title": "true",
      "type": "topic",
      "url": "/documentation/swift/true"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Pagination-Attributes",
      "generated": true,
      "identifiers": [
        "doc://com.apple.appkit/documentation/AppKit/NSPrintInfo/AttributeKey/leftMargin",
        "doc://com.apple.appkit/documentation/AppKit/NSPrintInfo/AttributeKey/rightMargin",
        "doc://com.apple.appkit/documentation/AppKit/NSPrintInfo/AttributeKey/topMargin",
        "doc://com.apple.appkit/documentation/AppKit/NSPrintInfo/AttributeKey/bottomMargin",
        "doc://com.apple.appkit/documentation/AppKit/NSPrintInfo/AttributeKey/horizontallyCentered",
        "doc://com.apple.appkit/documentation/AppKit/NSPrintInfo/AttributeKey/horizontalPagination",
        "doc://com.apple.appkit/documentation/AppKit/NSPrintInfo/AttributeKey/verticalPagination"
      ],
      "title": "Pagination Attributes"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "name": "macOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Global Variable"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "NSPrintVerticallyCentered"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "var"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSPrintVerticallyCentered"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.appkit/documentation/AppKit"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Pagination-Attributes",
              "generated": true,
              "identifiers": [
                "doc://com.apple.appkit/documentation/AppKit/NSPrintInfo/AttributeKey/leftMargin",
                "doc://com.apple.appkit/documentation/AppKit/NSPrintInfo/AttributeKey/rightMargin",
                "doc://com.apple.appkit/documentation/AppKit/NSPrintInfo/AttributeKey/topMargin",
                "doc://com.apple.appkit/documentation/AppKit/NSPrintInfo/AttributeKey/bottomMargin",
                "doc://com.apple.appkit/documentation/AppKit/NSPrintInfo/AttributeKey/horizontallyCentered",
                "doc://com.apple.appkit/documentation/AppKit/NSPrintInfo/AttributeKey/horizontalPagination",
                "doc://com.apple.appkit/documentation/AppKit/NSPrintInfo/AttributeKey/verticalPagination"
              ],
              "title": "Pagination Attributes"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "Mac Catalyst",
                  "macOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "extern"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "identifier": "doc://com.apple.appkit/documentation/AppKit/NSPrintInfo/AttributeKey",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@NSPrintInfoAttributeKey",
                    "text": "NSPrintInfoAttributeKey"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "keyword",
                    "text": "const"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "NSPrintVerticallyCentered"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSPrintInfo~1AttributeKey~1leftMargin/title",
          "value": "NSPrintLeftMargin"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSPrintInfo~1AttributeKey~1leftMargin/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSPrintLeftMargin"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSPrintInfo~1AttributeKey~1verticallyCentered/title",
          "value": "NSPrintVerticallyCentered"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSPrintInfo~1AttributeKey~1verticallyCentered/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSPrintVerticallyCentered"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSPrintInfo~1AttributeKey~1bottomMargin/title",
          "value": "NSPrintBottomMargin"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSPrintInfo~1AttributeKey~1bottomMargin/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSPrintBottomMargin"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSPrintInfo~1AttributeKey~1horizontalPagination/title",
          "value": "NSPrintHorizontalPagination"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSPrintInfo~1AttributeKey~1horizontalPagination/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSPrintHorizontalPagination"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSPrintInfo~1AttributeKey~1topMargin/title",
          "value": "NSPrintTopMargin"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSPrintInfo~1AttributeKey~1topMargin/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSPrintTopMargin"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSPrintInfo~1AttributeKey/title",
          "value": "NSPrintInfoAttributeKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSPrintInfo~1AttributeKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSPrintInfoAttributeKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSPrintInfo~1AttributeKey/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSPrintInfoAttributeKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSPrintInfo~1AttributeKey~1horizontallyCentered/title",
          "value": "NSPrintHorizontallyCentered"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSPrintInfo~1AttributeKey~1horizontallyCentered/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSPrintHorizontallyCentered"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSPrintInfo~1AttributeKey~1rightMargin/title",
          "value": "NSPrintRightMargin"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSPrintInfo~1AttributeKey~1rightMargin/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSPrintRightMargin"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSPrintInfo/title",
          "value": "NSPrintInfo"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSPrintInfo/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSPrintInfo"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSPrintInfo/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSPrintInfo"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSPrintInfo~1AttributeKey~1verticalPagination/title",
          "value": "NSPrintVerticalPagination"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSPrintInfo~1AttributeKey~1verticalPagination/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSPrintVerticalPagination"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/appkit/nsprintinfo/attributekey/verticallycentered"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/appkit/nsprintinfo/attributekey/verticallycentered"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
