{
  "abstract": [
    {
      "text": "A scheme that classifies tokens according to class: part of speech, type of punctuation, or whitespace.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.naturallanguage/documentation/NaturalLanguage",
        "doc://com.apple.naturallanguage/documentation/NaturalLanguage/NLTagScheme"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.naturallanguage/documentation/NaturalLanguage/NLTagScheme/lexicalClass"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "extendedModule": "NaturalLanguage",
    "externalID": "c:@NLTagSchemeLexicalClass",
    "fragments": [
      {
        "kind": "keyword",
        "text": "static"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "keyword",
        "text": "let"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "lexicalClass"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@T@NLTagScheme",
        "text": "NLTagScheme"
      }
    ],
    "modules": [
      {
        "name": "Natural Language"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "NLTagSchemeLexicalClass"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "12.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "12.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.1",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.14",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "12.0",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "5.0",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Type Property",
    "symbolKind": "property",
    "title": "lexicalClass"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "static"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "keyword",
              "text": "let"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "lexicalClass"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.naturallanguage/documentation/NaturalLanguage/NLTagScheme",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@NLTagScheme",
              "text": "NLTagScheme"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "kind": "mentions",
      "mentions": [
        "doc://com.apple.naturallanguage/documentation/NaturalLanguage/identifying-parts-of-speech"
      ]
    },
    {
      "content": [
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "For possible values, see Lexical classes in ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.naturallanguage/documentation/NaturalLanguage/NLTag",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ".",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "The lexical class of a tag is a further distinction of its token type. Token types and lexical classes have the following correspondence:",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "header": "row",
          "rows": [
            [
              [
                {
                  "inlineContent": [
                    {
                      "text": "Token Type",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ],
              [
                {
                  "inlineContent": [
                    {
                      "text": "Lexical classes",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            ],
            [
              [
                {
                  "inlineContent": [
                    {
                      "identifier": "doc://com.apple.naturallanguage/documentation/NaturalLanguage/NLTag/word",
                      "isActive": true,
                      "type": "reference"
                    }
                  ],
                  "type": "paragraph"
                }
              ],
              [
                {
                  "inlineContent": [
                    {
                      "identifier": "doc://com.apple.naturallanguage/documentation/NaturalLanguage/NLTag/noun",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": " ",
                      "type": "text"
                    },
                    {
                      "identifier": "spacer",
                      "type": "image"
                    },
                    {
                      "text": " ",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.naturallanguage/documentation/NaturalLanguage/NLTag/verb",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": " ",
                      "type": "text"
                    },
                    {
                      "identifier": "spacer",
                      "type": "image"
                    },
                    {
                      "text": " ",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.naturallanguage/documentation/NaturalLanguage/NLTag/adjective",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": " ",
                      "type": "text"
                    },
                    {
                      "identifier": "spacer",
                      "type": "image"
                    },
                    {
                      "text": " ",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.naturallanguage/documentation/NaturalLanguage/NLTag/adverb",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": " ",
                      "type": "text"
                    },
                    {
                      "identifier": "spacer",
                      "type": "image"
                    },
                    {
                      "text": " ",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.naturallanguage/documentation/NaturalLanguage/NLTag/pronoun",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": " ",
                      "type": "text"
                    },
                    {
                      "identifier": "spacer",
                      "type": "image"
                    },
                    {
                      "text": " ",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.naturallanguage/documentation/NaturalLanguage/NLTag/determiner",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": " ",
                      "type": "text"
                    },
                    {
                      "identifier": "spacer",
                      "type": "image"
                    },
                    {
                      "text": " ",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.naturallanguage/documentation/NaturalLanguage/NLTag/particle",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": " ",
                      "type": "text"
                    },
                    {
                      "identifier": "spacer",
                      "type": "image"
                    },
                    {
                      "text": " ",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.naturallanguage/documentation/NaturalLanguage/NLTag/preposition",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": " ",
                      "type": "text"
                    },
                    {
                      "identifier": "spacer",
                      "type": "image"
                    },
                    {
                      "text": " ",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.naturallanguage/documentation/NaturalLanguage/NLTag/number",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": " ",
                      "type": "text"
                    },
                    {
                      "identifier": "spacer",
                      "type": "image"
                    },
                    {
                      "text": " ",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.naturallanguage/documentation/NaturalLanguage/NLTag/conjunction",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": " ",
                      "type": "text"
                    },
                    {
                      "identifier": "spacer",
                      "type": "image"
                    },
                    {
                      "text": " ",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.naturallanguage/documentation/NaturalLanguage/NLTag/interjection",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": " ",
                      "type": "text"
                    },
                    {
                      "identifier": "spacer",
                      "type": "image"
                    },
                    {
                      "text": " ",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.naturallanguage/documentation/NaturalLanguage/NLTag/classifier",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": " ",
                      "type": "text"
                    },
                    {
                      "identifier": "spacer",
                      "type": "image"
                    },
                    {
                      "text": " ",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.naturallanguage/documentation/NaturalLanguage/NLTag/idiom",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": " ",
                      "type": "text"
                    },
                    {
                      "identifier": "spacer",
                      "type": "image"
                    },
                    {
                      "text": " ",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.naturallanguage/documentation/NaturalLanguage/NLTag/otherWord",
                      "isActive": true,
                      "type": "reference"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            ],
            [
              [
                {
                  "inlineContent": [
                    {
                      "identifier": "doc://com.apple.naturallanguage/documentation/NaturalLanguage/NLTag/punctuation",
                      "isActive": true,
                      "type": "reference"
                    }
                  ],
                  "type": "paragraph"
                }
              ],
              [
                {
                  "inlineContent": [
                    {
                      "identifier": "doc://com.apple.naturallanguage/documentation/NaturalLanguage/NLTag/sentenceTerminator",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": " ",
                      "type": "text"
                    },
                    {
                      "identifier": "spacer",
                      "type": "image"
                    },
                    {
                      "text": " ",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.naturallanguage/documentation/NaturalLanguage/NLTag/openQuote",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": " ",
                      "type": "text"
                    },
                    {
                      "identifier": "spacer",
                      "type": "image"
                    },
                    {
                      "text": " ",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.naturallanguage/documentation/NaturalLanguage/NLTag/closeQuote",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": " ",
                      "type": "text"
                    },
                    {
                      "identifier": "spacer",
                      "type": "image"
                    },
                    {
                      "text": " ",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.naturallanguage/documentation/NaturalLanguage/NLTag/openParenthesis",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": " ",
                      "type": "text"
                    },
                    {
                      "identifier": "spacer",
                      "type": "image"
                    },
                    {
                      "text": " ",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.naturallanguage/documentation/NaturalLanguage/NLTag/closeParenthesis",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": " ",
                      "type": "text"
                    },
                    {
                      "identifier": "spacer",
                      "type": "image"
                    },
                    {
                      "text": " ",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.naturallanguage/documentation/NaturalLanguage/NLTag/wordJoiner",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": " ",
                      "type": "text"
                    },
                    {
                      "identifier": "spacer",
                      "type": "image"
                    },
                    {
                      "text": " ",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.naturallanguage/documentation/NaturalLanguage/NLTag/dash",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": " ",
                      "type": "text"
                    },
                    {
                      "identifier": "spacer",
                      "type": "image"
                    },
                    {
                      "text": " ",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.naturallanguage/documentation/NaturalLanguage/NLTag/otherPunctuation",
                      "isActive": true,
                      "type": "reference"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            ],
            [
              [
                {
                  "inlineContent": [
                    {
                      "identifier": "doc://com.apple.naturallanguage/documentation/NaturalLanguage/NLTag/whitespace",
                      "isActive": true,
                      "type": "reference"
                    }
                  ],
                  "type": "paragraph"
                }
              ],
              [
                {
                  "inlineContent": [
                    {
                      "identifier": "doc://com.apple.naturallanguage/documentation/NaturalLanguage/NLTag/paragraphBreak",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": " ",
                      "type": "text"
                    },
                    {
                      "identifier": "spacer",
                      "type": "image"
                    },
                    {
                      "text": " ",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.naturallanguage/documentation/NaturalLanguage/NLTag/otherWhitespace",
                      "isActive": true,
                      "type": "reference"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            ],
            [
              [
                {
                  "inlineContent": [
                    {
                      "identifier": "doc://com.apple.naturallanguage/documentation/NaturalLanguage/NLTag/other",
                      "isActive": true,
                      "type": "reference"
                    }
                  ],
                  "type": "paragraph"
                }
              ],
              [
                {
                  "inlineContent": [
                    {
                      "inlineContent": [
                        {
                          "text": "None",
                          "type": "text"
                        }
                      ],
                      "type": "emphasis"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            ]
          ],
          "type": "table"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.naturallanguage/documentation/NaturalLanguage": {
      "abstract": [
        {
          "text": "Analyze natural language text and deduce its language-specific metadata.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.naturallanguage/documentation/NaturalLanguage",
      "kind": "symbol",
      "role": "collection",
      "title": "Natural Language",
      "type": "topic",
      "url": "/documentation/naturallanguage"
    },
    "doc://com.apple.naturallanguage/documentation/NaturalLanguage/NLTag": {
      "abstract": [
        {
          "text": "A token type, lexical class, name, lemma, language, or script returned by a linguistic tagger for natural language text.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NLTag"
        }
      ],
      "identifier": "doc://com.apple.naturallanguage/documentation/NaturalLanguage/NLTag",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NLTag"
        }
      ],
      "role": "symbol",
      "title": "NLTag",
      "type": "topic",
      "url": "/documentation/naturallanguage/nltag"
    },
    "doc://com.apple.naturallanguage/documentation/NaturalLanguage/NLTag/adjective": {
      "abstract": [
        {
          "text": "A tag indicating that the token is an adjective",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "adjective"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NLTag",
          "text": "NLTag"
        }
      ],
      "identifier": "doc://com.apple.naturallanguage/documentation/NaturalLanguage/NLTag/adjective",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NLTagAdjective"
        }
      ],
      "role": "symbol",
      "title": "adjective",
      "type": "topic",
      "url": "/documentation/naturallanguage/nltag/adjective"
    },
    "doc://com.apple.naturallanguage/documentation/NaturalLanguage/NLTag/adverb": {
      "abstract": [
        {
          "text": "A tag indicating that the token is an adverb.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "adverb"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NLTag",
          "text": "NLTag"
        }
      ],
      "identifier": "doc://com.apple.naturallanguage/documentation/NaturalLanguage/NLTag/adverb",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NLTagAdverb"
        }
      ],
      "role": "symbol",
      "title": "adverb",
      "type": "topic",
      "url": "/documentation/naturallanguage/nltag/adverb"
    },
    "doc://com.apple.naturallanguage/documentation/NaturalLanguage/NLTag/classifier": {
      "abstract": [
        {
          "text": "A tag indicating that the token is a classifier.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "classifier"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NLTag",
          "text": "NLTag"
        }
      ],
      "identifier": "doc://com.apple.naturallanguage/documentation/NaturalLanguage/NLTag/classifier",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NLTagClassifier"
        }
      ],
      "role": "symbol",
      "title": "classifier",
      "type": "topic",
      "url": "/documentation/naturallanguage/nltag/classifier"
    },
    "doc://com.apple.naturallanguage/documentation/NaturalLanguage/NLTag/closeParenthesis": {
      "abstract": [
        {
          "text": "A tag indicating that the token is a close parenthesis.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "closeParenthesis"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NLTag",
          "text": "NLTag"
        }
      ],
      "identifier": "doc://com.apple.naturallanguage/documentation/NaturalLanguage/NLTag/closeParenthesis",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NLTagCloseParenthesis"
        }
      ],
      "role": "symbol",
      "title": "closeParenthesis",
      "type": "topic",
      "url": "/documentation/naturallanguage/nltag/closeparenthesis"
    },
    "doc://com.apple.naturallanguage/documentation/NaturalLanguage/NLTag/closeQuote": {
      "abstract": [
        {
          "text": "A tag indicating that the token is a close quote.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "closeQuote"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NLTag",
          "text": "NLTag"
        }
      ],
      "identifier": "doc://com.apple.naturallanguage/documentation/NaturalLanguage/NLTag/closeQuote",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NLTagCloseQuote"
        }
      ],
      "role": "symbol",
      "title": "closeQuote",
      "type": "topic",
      "url": "/documentation/naturallanguage/nltag/closequote"
    },
    "doc://com.apple.naturallanguage/documentation/NaturalLanguage/NLTag/conjunction": {
      "abstract": [
        {
          "text": "A tag indicating that the token is a conjunction.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "conjunction"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NLTag",
          "text": "NLTag"
        }
      ],
      "identifier": "doc://com.apple.naturallanguage/documentation/NaturalLanguage/NLTag/conjunction",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NLTagConjunction"
        }
      ],
      "role": "symbol",
      "title": "conjunction",
      "type": "topic",
      "url": "/documentation/naturallanguage/nltag/conjunction"
    },
    "doc://com.apple.naturallanguage/documentation/NaturalLanguage/NLTag/dash": {
      "abstract": [
        {
          "text": "A tag indicating that the token is a dash.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "dash"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NLTag",
          "text": "NLTag"
        }
      ],
      "identifier": "doc://com.apple.naturallanguage/documentation/NaturalLanguage/NLTag/dash",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NLTagDash"
        }
      ],
      "role": "symbol",
      "title": "dash",
      "type": "topic",
      "url": "/documentation/naturallanguage/nltag/dash"
    },
    "doc://com.apple.naturallanguage/documentation/NaturalLanguage/NLTag/determiner": {
      "abstract": [
        {
          "text": "A tag indicating that the token is a determiner.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "determiner"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NLTag",
          "text": "NLTag"
        }
      ],
      "identifier": "doc://com.apple.naturallanguage/documentation/NaturalLanguage/NLTag/determiner",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NLTagDeterminer"
        }
      ],
      "role": "symbol",
      "title": "determiner",
      "type": "topic",
      "url": "/documentation/naturallanguage/nltag/determiner"
    },
    "doc://com.apple.naturallanguage/documentation/NaturalLanguage/NLTag/idiom": {
      "abstract": [
        {
          "text": "A tag indicating that the token is an idiom.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "idiom"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NLTag",
          "text": "NLTag"
        }
      ],
      "identifier": "doc://com.apple.naturallanguage/documentation/NaturalLanguage/NLTag/idiom",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NLTagIdiom"
        }
      ],
      "role": "symbol",
      "title": "idiom",
      "type": "topic",
      "url": "/documentation/naturallanguage/nltag/idiom"
    },
    "doc://com.apple.naturallanguage/documentation/NaturalLanguage/NLTag/interjection": {
      "abstract": [
        {
          "text": "A tag indicating that the token is an interjection.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "interjection"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NLTag",
          "text": "NLTag"
        }
      ],
      "identifier": "doc://com.apple.naturallanguage/documentation/NaturalLanguage/NLTag/interjection",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NLTagInterjection"
        }
      ],
      "role": "symbol",
      "title": "interjection",
      "type": "topic",
      "url": "/documentation/naturallanguage/nltag/interjection"
    },
    "doc://com.apple.naturallanguage/documentation/NaturalLanguage/NLTag/noun": {
      "abstract": [
        {
          "text": "A tag indicating that the token is a noun.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "noun"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NLTag",
          "text": "NLTag"
        }
      ],
      "identifier": "doc://com.apple.naturallanguage/documentation/NaturalLanguage/NLTag/noun",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NLTagNoun"
        }
      ],
      "role": "symbol",
      "title": "noun",
      "type": "topic",
      "url": "/documentation/naturallanguage/nltag/noun"
    },
    "doc://com.apple.naturallanguage/documentation/NaturalLanguage/NLTag/number": {
      "abstract": [
        {
          "text": "A tag indicating that the token is a number.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "number"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NLTag",
          "text": "NLTag"
        }
      ],
      "identifier": "doc://com.apple.naturallanguage/documentation/NaturalLanguage/NLTag/number",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NLTagNumber"
        }
      ],
      "role": "symbol",
      "title": "number",
      "type": "topic",
      "url": "/documentation/naturallanguage/nltag/number"
    },
    "doc://com.apple.naturallanguage/documentation/NaturalLanguage/NLTag/openParenthesis": {
      "abstract": [
        {
          "text": "A tag indicating that the token is an open parenthesis.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "openParenthesis"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NLTag",
          "text": "NLTag"
        }
      ],
      "identifier": "doc://com.apple.naturallanguage/documentation/NaturalLanguage/NLTag/openParenthesis",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NLTagOpenParenthesis"
        }
      ],
      "role": "symbol",
      "title": "openParenthesis",
      "type": "topic",
      "url": "/documentation/naturallanguage/nltag/openparenthesis"
    },
    "doc://com.apple.naturallanguage/documentation/NaturalLanguage/NLTag/openQuote": {
      "abstract": [
        {
          "text": "A tag indicating that the token is an open quote.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "openQuote"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NLTag",
          "text": "NLTag"
        }
      ],
      "identifier": "doc://com.apple.naturallanguage/documentation/NaturalLanguage/NLTag/openQuote",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NLTagOpenQuote"
        }
      ],
      "role": "symbol",
      "title": "openQuote",
      "type": "topic",
      "url": "/documentation/naturallanguage/nltag/openquote"
    },
    "doc://com.apple.naturallanguage/documentation/NaturalLanguage/NLTag/other": {
      "abstract": [
        {
          "text": "A tag indicating that the token is a non-linguistic item, such as a symbol.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "other"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NLTag",
          "text": "NLTag"
        }
      ],
      "identifier": "doc://com.apple.naturallanguage/documentation/NaturalLanguage/NLTag/other",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NLTagOther"
        }
      ],
      "role": "symbol",
      "title": "other",
      "type": "topic",
      "url": "/documentation/naturallanguage/nltag/other"
    },
    "doc://com.apple.naturallanguage/documentation/NaturalLanguage/NLTag/otherPunctuation": {
      "abstract": [
        {
          "text": "A tag indicating that the token is punctuation other than a kind described by other lexical classes (sentence terminator, open or close quote, open or close parenthesis, word joiner, and dash).",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "otherPunctuation"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NLTag",
          "text": "NLTag"
        }
      ],
      "identifier": "doc://com.apple.naturallanguage/documentation/NaturalLanguage/NLTag/otherPunctuation",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NLTagOtherPunctuation"
        }
      ],
      "role": "symbol",
      "title": "otherPunctuation",
      "type": "topic",
      "url": "/documentation/naturallanguage/nltag/otherpunctuation"
    },
    "doc://com.apple.naturallanguage/documentation/NaturalLanguage/NLTag/otherWhitespace": {
      "abstract": [
        {
          "text": "A tag indicating that the token is whitespace other than a kind described by other lexical classes (paragraph break).",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "otherWhitespace"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NLTag",
          "text": "NLTag"
        }
      ],
      "identifier": "doc://com.apple.naturallanguage/documentation/NaturalLanguage/NLTag/otherWhitespace",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NLTagOtherWhitespace"
        }
      ],
      "role": "symbol",
      "title": "otherWhitespace",
      "type": "topic",
      "url": "/documentation/naturallanguage/nltag/otherwhitespace"
    },
    "doc://com.apple.naturallanguage/documentation/NaturalLanguage/NLTag/otherWord": {
      "abstract": [
        {
          "text": "A tag indicating that the token is a word other than a kind described by other lexical classes (noun, verb, adjective, adverb, pronoun, determiner, particle, preposition, number, conjunction, interjection, classifier, and idiom).",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "otherWord"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NLTag",
          "text": "NLTag"
        }
      ],
      "identifier": "doc://com.apple.naturallanguage/documentation/NaturalLanguage/NLTag/otherWord",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NLTagOtherWord"
        }
      ],
      "role": "symbol",
      "title": "otherWord",
      "type": "topic",
      "url": "/documentation/naturallanguage/nltag/otherword"
    },
    "doc://com.apple.naturallanguage/documentation/NaturalLanguage/NLTag/paragraphBreak": {
      "abstract": [
        {
          "text": "A tag indicating that the token is a paragraph break.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "paragraphBreak"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NLTag",
          "text": "NLTag"
        }
      ],
      "identifier": "doc://com.apple.naturallanguage/documentation/NaturalLanguage/NLTag/paragraphBreak",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NLTagParagraphBreak"
        }
      ],
      "role": "symbol",
      "title": "paragraphBreak",
      "type": "topic",
      "url": "/documentation/naturallanguage/nltag/paragraphbreak"
    },
    "doc://com.apple.naturallanguage/documentation/NaturalLanguage/NLTag/particle": {
      "abstract": [
        {
          "text": "A tag indicating that the token is a particle.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "particle"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NLTag",
          "text": "NLTag"
        }
      ],
      "identifier": "doc://com.apple.naturallanguage/documentation/NaturalLanguage/NLTag/particle",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NLTagParticle"
        }
      ],
      "role": "symbol",
      "title": "particle",
      "type": "topic",
      "url": "/documentation/naturallanguage/nltag/particle"
    },
    "doc://com.apple.naturallanguage/documentation/NaturalLanguage/NLTag/preposition": {
      "abstract": [
        {
          "text": "A tag indicating that the token is a preposition.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "preposition"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NLTag",
          "text": "NLTag"
        }
      ],
      "identifier": "doc://com.apple.naturallanguage/documentation/NaturalLanguage/NLTag/preposition",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NLTagPreposition"
        }
      ],
      "role": "symbol",
      "title": "preposition",
      "type": "topic",
      "url": "/documentation/naturallanguage/nltag/preposition"
    },
    "doc://com.apple.naturallanguage/documentation/NaturalLanguage/NLTag/pronoun": {
      "abstract": [
        {
          "text": "A tag indicating that the token is a pronoun.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "pronoun"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NLTag",
          "text": "NLTag"
        }
      ],
      "identifier": "doc://com.apple.naturallanguage/documentation/NaturalLanguage/NLTag/pronoun",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NLTagPronoun"
        }
      ],
      "role": "symbol",
      "title": "pronoun",
      "type": "topic",
      "url": "/documentation/naturallanguage/nltag/pronoun"
    },
    "doc://com.apple.naturallanguage/documentation/NaturalLanguage/NLTag/punctuation": {
      "abstract": [
        {
          "text": "A tag indicating that the token is punctuation.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "punctuation"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NLTag",
          "text": "NLTag"
        }
      ],
      "identifier": "doc://com.apple.naturallanguage/documentation/NaturalLanguage/NLTag/punctuation",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NLTagPunctuation"
        }
      ],
      "role": "symbol",
      "title": "punctuation",
      "type": "topic",
      "url": "/documentation/naturallanguage/nltag/punctuation"
    },
    "doc://com.apple.naturallanguage/documentation/NaturalLanguage/NLTag/sentenceTerminator": {
      "abstract": [
        {
          "text": "A tag indicating that the token is punctuation at the end of a sentence.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "sentenceTerminator"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NLTag",
          "text": "NLTag"
        }
      ],
      "identifier": "doc://com.apple.naturallanguage/documentation/NaturalLanguage/NLTag/sentenceTerminator",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NLTagSentenceTerminator"
        }
      ],
      "role": "symbol",
      "title": "sentenceTerminator",
      "type": "topic",
      "url": "/documentation/naturallanguage/nltag/sentenceterminator"
    },
    "doc://com.apple.naturallanguage/documentation/NaturalLanguage/NLTag/verb": {
      "abstract": [
        {
          "text": "A tag indicating that the token is a verb.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "verb"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NLTag",
          "text": "NLTag"
        }
      ],
      "identifier": "doc://com.apple.naturallanguage/documentation/NaturalLanguage/NLTag/verb",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NLTagVerb"
        }
      ],
      "role": "symbol",
      "title": "verb",
      "type": "topic",
      "url": "/documentation/naturallanguage/nltag/verb"
    },
    "doc://com.apple.naturallanguage/documentation/NaturalLanguage/NLTag/whitespace": {
      "abstract": [
        {
          "text": "A tag indicating that the token is white space of any sort.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "whitespace"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NLTag",
          "text": "NLTag"
        }
      ],
      "identifier": "doc://com.apple.naturallanguage/documentation/NaturalLanguage/NLTag/whitespace",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NLTagWhitespace"
        }
      ],
      "role": "symbol",
      "title": "whitespace",
      "type": "topic",
      "url": "/documentation/naturallanguage/nltag/whitespace"
    },
    "doc://com.apple.naturallanguage/documentation/NaturalLanguage/NLTag/word": {
      "abstract": [
        {
          "text": "A tag indicating that the token is a word.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "word"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NLTag",
          "text": "NLTag"
        }
      ],
      "identifier": "doc://com.apple.naturallanguage/documentation/NaturalLanguage/NLTag/word",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NLTagWord"
        }
      ],
      "role": "symbol",
      "title": "word",
      "type": "topic",
      "url": "/documentation/naturallanguage/nltag/word"
    },
    "doc://com.apple.naturallanguage/documentation/NaturalLanguage/NLTag/wordJoiner": {
      "abstract": [
        {
          "text": "A tag indicating that the token is a word joiner, signifying that two tokens on each side should not be broken up.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "wordJoiner"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NLTag",
          "text": "NLTag"
        }
      ],
      "identifier": "doc://com.apple.naturallanguage/documentation/NaturalLanguage/NLTag/wordJoiner",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NLTagWordJoiner"
        }
      ],
      "role": "symbol",
      "title": "wordJoiner",
      "type": "topic",
      "url": "/documentation/naturallanguage/nltag/wordjoiner"
    },
    "doc://com.apple.naturallanguage/documentation/NaturalLanguage/NLTagScheme": {
      "abstract": [
        {
          "text": "Constants for the tag schemes specified when initializing a linguistic tagger.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NLTagScheme"
        }
      ],
      "identifier": "doc://com.apple.naturallanguage/documentation/NaturalLanguage/NLTagScheme",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NLTagScheme"
        }
      ],
      "role": "symbol",
      "title": "NLTagScheme",
      "type": "topic",
      "url": "/documentation/naturallanguage/nltagscheme"
    },
    "doc://com.apple.naturallanguage/documentation/NaturalLanguage/NLTagScheme/language": {
      "abstract": [
        {
          "text": "A scheme that supplies the language for a token, if it can determine one.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "language"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NLTagScheme",
          "text": "NLTagScheme"
        }
      ],
      "identifier": "doc://com.apple.naturallanguage/documentation/NaturalLanguage/NLTagScheme/language",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NLTagSchemeLanguage"
        }
      ],
      "role": "symbol",
      "title": "language",
      "type": "topic",
      "url": "/documentation/naturallanguage/nltagscheme/language"
    },
    "doc://com.apple.naturallanguage/documentation/NaturalLanguage/NLTagScheme/lemma": {
      "abstract": [
        {
          "text": "A scheme that supplies a stem form of a word token, if known.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "lemma"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NLTagScheme",
          "text": "NLTagScheme"
        }
      ],
      "identifier": "doc://com.apple.naturallanguage/documentation/NaturalLanguage/NLTagScheme/lemma",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NLTagSchemeLemma"
        }
      ],
      "role": "symbol",
      "title": "lemma",
      "type": "topic",
      "url": "/documentation/naturallanguage/nltagscheme/lemma"
    },
    "doc://com.apple.naturallanguage/documentation/NaturalLanguage/NLTagScheme/lexicalClass": {
      "abstract": [
        {
          "text": "A scheme that classifies tokens according to class: part of speech, type of punctuation, or whitespace.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "lexicalClass"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NLTagScheme",
          "text": "NLTagScheme"
        }
      ],
      "identifier": "doc://com.apple.naturallanguage/documentation/NaturalLanguage/NLTagScheme/lexicalClass",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NLTagSchemeLexicalClass"
        }
      ],
      "role": "symbol",
      "title": "lexicalClass",
      "type": "topic",
      "url": "/documentation/naturallanguage/nltagscheme/lexicalclass"
    },
    "doc://com.apple.naturallanguage/documentation/NaturalLanguage/NLTagScheme/nameType": {
      "abstract": [
        {
          "text": "A scheme that classifies tokens according to whether they are part of a named entity.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "nameType"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NLTagScheme",
          "text": "NLTagScheme"
        }
      ],
      "identifier": "doc://com.apple.naturallanguage/documentation/NaturalLanguage/NLTagScheme/nameType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NLTagSchemeNameType"
        }
      ],
      "role": "symbol",
      "title": "nameType",
      "type": "topic",
      "url": "/documentation/naturallanguage/nltagscheme/nametype"
    },
    "doc://com.apple.naturallanguage/documentation/NaturalLanguage/NLTagScheme/nameTypeOrLexicalClass": {
      "abstract": [
        {
          "text": "A scheme that classifies tokens corresponding to names according to ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.naturallanguage/documentation/NaturalLanguage/NLTagScheme/nameType",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": ", and classifies all other tokens according to ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.naturallanguage/documentation/NaturalLanguage/NLTagScheme/lexicalClass",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": ".",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "nameTypeOrLexicalClass"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NLTagScheme",
          "text": "NLTagScheme"
        }
      ],
      "identifier": "doc://com.apple.naturallanguage/documentation/NaturalLanguage/NLTagScheme/nameTypeOrLexicalClass",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NLTagSchemeNameTypeOrLexicalClass"
        }
      ],
      "role": "symbol",
      "title": "nameTypeOrLexicalClass",
      "type": "topic",
      "url": "/documentation/naturallanguage/nltagscheme/nametypeorlexicalclass"
    },
    "doc://com.apple.naturallanguage/documentation/NaturalLanguage/NLTagScheme/script": {
      "abstract": [
        {
          "text": "A scheme that supplies the script for a token, if it can determine one.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "script"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NLTagScheme",
          "text": "NLTagScheme"
        }
      ],
      "identifier": "doc://com.apple.naturallanguage/documentation/NaturalLanguage/NLTagScheme/script",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NLTagSchemeScript"
        }
      ],
      "role": "symbol",
      "title": "script",
      "type": "topic",
      "url": "/documentation/naturallanguage/nltagscheme/script"
    },
    "doc://com.apple.naturallanguage/documentation/NaturalLanguage/NLTagScheme/sentimentScore": {
      "abstract": [
        {
          "text": "A scheme that scores text as positive, negative, or neutral based on its sentiment polarity.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "sentimentScore"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NLTagScheme",
          "text": "NLTagScheme"
        }
      ],
      "identifier": "doc://com.apple.naturallanguage/documentation/NaturalLanguage/NLTagScheme/sentimentScore",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NLTagSchemeSentimentScore"
        }
      ],
      "role": "symbol",
      "title": "sentimentScore",
      "type": "topic",
      "url": "/documentation/naturallanguage/nltagscheme/sentimentscore"
    },
    "doc://com.apple.naturallanguage/documentation/NaturalLanguage/NLTagScheme/tokenType": {
      "abstract": [
        {
          "text": "A scheme that classifies tokens according to their broad type: word, punctuation, or whitespace.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "tokenType"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NLTagScheme",
          "text": "NLTagScheme"
        }
      ],
      "identifier": "doc://com.apple.naturallanguage/documentation/NaturalLanguage/NLTagScheme/tokenType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NLTagSchemeTokenType"
        }
      ],
      "role": "symbol",
      "title": "tokenType",
      "type": "topic",
      "url": "/documentation/naturallanguage/nltagscheme/tokentype"
    },
    "doc://com.apple.naturallanguage/documentation/NaturalLanguage/identifying-parts-of-speech": {
      "abstract": [
        {
          "text": "Classify nouns, verbs, adjectives, and other parts of speech in a string.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.naturallanguage/documentation/NaturalLanguage/identifying-parts-of-speech",
      "kind": "article",
      "role": "article",
      "title": "Identifying parts of speech",
      "type": "topic",
      "url": "/documentation/naturallanguage/identifying-parts-of-speech"
    },
    "spacer": {
      "alt": null,
      "identifier": "spacer",
      "type": "image",
      "variants": [
        {
          "traits": [
            "1x",
            "light"
          ],
          "url": "https://docs-assets.developer.apple.com/published/67dc4b07a8d84366d4cc0e812eb40b4a/spacer.png"
        }
      ]
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Schemes",
      "generated": true,
      "identifiers": [
        "doc://com.apple.naturallanguage/documentation/NaturalLanguage/NLTagScheme/tokenType",
        "doc://com.apple.naturallanguage/documentation/NaturalLanguage/NLTagScheme/nameType",
        "doc://com.apple.naturallanguage/documentation/NaturalLanguage/NLTagScheme/nameTypeOrLexicalClass",
        "doc://com.apple.naturallanguage/documentation/NaturalLanguage/NLTagScheme/lemma",
        "doc://com.apple.naturallanguage/documentation/NaturalLanguage/NLTagScheme/language",
        "doc://com.apple.naturallanguage/documentation/NaturalLanguage/NLTagScheme/script",
        "doc://com.apple.naturallanguage/documentation/NaturalLanguage/NLTagScheme/sentimentScore"
      ],
      "title": "Schemes"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "12.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "12.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.1",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.14",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "12.0",
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "5.0",
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Global Variable"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "NLTagSchemeLexicalClass"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "var"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NLTagSchemeLexicalClass"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.naturallanguage/documentation/NaturalLanguage"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Schemes",
              "generated": true,
              "identifiers": [
                "doc://com.apple.naturallanguage/documentation/NaturalLanguage/NLTagScheme/tokenType",
                "doc://com.apple.naturallanguage/documentation/NaturalLanguage/NLTagScheme/nameType",
                "doc://com.apple.naturallanguage/documentation/NaturalLanguage/NLTagScheme/nameTypeOrLexicalClass",
                "doc://com.apple.naturallanguage/documentation/NaturalLanguage/NLTagScheme/lemma",
                "doc://com.apple.naturallanguage/documentation/NaturalLanguage/NLTagScheme/language",
                "doc://com.apple.naturallanguage/documentation/NaturalLanguage/NLTagScheme/script",
                "doc://com.apple.naturallanguage/documentation/NaturalLanguage/NLTagScheme/sentimentScore"
              ],
              "title": "Schemes"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "extern"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "identifier": "doc://com.apple.naturallanguage/documentation/NaturalLanguage/NLTagScheme",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@NLTagScheme",
                    "text": "NLTagScheme"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "keyword",
                    "text": "const"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "NLTagSchemeLexicalClass"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.naturallanguage~1documentation~1NaturalLanguage~1NLTagScheme~1nameType/title",
          "value": "NLTagSchemeNameType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.naturallanguage~1documentation~1NaturalLanguage~1NLTagScheme~1nameType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NLTagSchemeNameType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.naturallanguage~1documentation~1NaturalLanguage~1NLTag~1pronoun/title",
          "value": "NLTagPronoun"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.naturallanguage~1documentation~1NaturalLanguage~1NLTag~1pronoun/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NLTagPronoun"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.naturallanguage~1documentation~1NaturalLanguage~1NLTag~1number/title",
          "value": "NLTagNumber"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.naturallanguage~1documentation~1NaturalLanguage~1NLTag~1number/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NLTagNumber"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.naturallanguage~1documentation~1NaturalLanguage~1NLTag~1openQuote/title",
          "value": "NLTagOpenQuote"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.naturallanguage~1documentation~1NaturalLanguage~1NLTag~1openQuote/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NLTagOpenQuote"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.naturallanguage~1documentation~1NaturalLanguage~1NLTag~1wordJoiner/title",
          "value": "NLTagWordJoiner"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.naturallanguage~1documentation~1NaturalLanguage~1NLTag~1wordJoiner/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NLTagWordJoiner"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.naturallanguage~1documentation~1NaturalLanguage~1NLTagScheme/title",
          "value": "NLTagScheme"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.naturallanguage~1documentation~1NaturalLanguage~1NLTagScheme/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NLTagScheme"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.naturallanguage~1documentation~1NaturalLanguage~1NLTagScheme/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NLTagScheme"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.naturallanguage~1documentation~1NaturalLanguage~1NLTag~1closeQuote/title",
          "value": "NLTagCloseQuote"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.naturallanguage~1documentation~1NaturalLanguage~1NLTag~1closeQuote/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NLTagCloseQuote"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.naturallanguage~1documentation~1NaturalLanguage~1NLTagScheme~1nameTypeOrLexicalClass/title",
          "value": "NLTagSchemeNameTypeOrLexicalClass"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.naturallanguage~1documentation~1NaturalLanguage~1NLTagScheme~1nameTypeOrLexicalClass/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NLTagSchemeNameTypeOrLexicalClass"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.naturallanguage~1documentation~1NaturalLanguage~1NLTag~1interjection/title",
          "value": "NLTagInterjection"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.naturallanguage~1documentation~1NaturalLanguage~1NLTag~1interjection/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NLTagInterjection"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.naturallanguage~1documentation~1NaturalLanguage~1NLTag~1classifier/title",
          "value": "NLTagClassifier"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.naturallanguage~1documentation~1NaturalLanguage~1NLTag~1classifier/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NLTagClassifier"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.naturallanguage~1documentation~1NaturalLanguage~1NLTag~1otherWhitespace/title",
          "value": "NLTagOtherWhitespace"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.naturallanguage~1documentation~1NaturalLanguage~1NLTag~1otherWhitespace/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NLTagOtherWhitespace"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.naturallanguage~1documentation~1NaturalLanguage~1NLTag~1particle/title",
          "value": "NLTagParticle"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.naturallanguage~1documentation~1NaturalLanguage~1NLTag~1particle/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NLTagParticle"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.naturallanguage~1documentation~1NaturalLanguage~1NLTag~1determiner/title",
          "value": "NLTagDeterminer"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.naturallanguage~1documentation~1NaturalLanguage~1NLTag~1determiner/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NLTagDeterminer"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.naturallanguage~1documentation~1NaturalLanguage~1NLTag~1verb/title",
          "value": "NLTagVerb"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.naturallanguage~1documentation~1NaturalLanguage~1NLTag~1verb/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NLTagVerb"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.naturallanguage~1documentation~1NaturalLanguage~1NLTag~1conjunction/title",
          "value": "NLTagConjunction"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.naturallanguage~1documentation~1NaturalLanguage~1NLTag~1conjunction/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NLTagConjunction"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.naturallanguage~1documentation~1NaturalLanguage~1NLTag~1paragraphBreak/title",
          "value": "NLTagParagraphBreak"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.naturallanguage~1documentation~1NaturalLanguage~1NLTag~1paragraphBreak/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NLTagParagraphBreak"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.naturallanguage~1documentation~1NaturalLanguage~1NLTag~1openParenthesis/title",
          "value": "NLTagOpenParenthesis"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.naturallanguage~1documentation~1NaturalLanguage~1NLTag~1openParenthesis/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NLTagOpenParenthesis"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.naturallanguage~1documentation~1NaturalLanguage~1NLTag~1adverb/title",
          "value": "NLTagAdverb"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.naturallanguage~1documentation~1NaturalLanguage~1NLTag~1adverb/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NLTagAdverb"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.naturallanguage~1documentation~1NaturalLanguage~1NLTagScheme~1tokenType/title",
          "value": "NLTagSchemeTokenType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.naturallanguage~1documentation~1NaturalLanguage~1NLTagScheme~1tokenType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NLTagSchemeTokenType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.naturallanguage~1documentation~1NaturalLanguage~1NLTagScheme~1sentimentScore/title",
          "value": "NLTagSchemeSentimentScore"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.naturallanguage~1documentation~1NaturalLanguage~1NLTagScheme~1sentimentScore/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NLTagSchemeSentimentScore"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.naturallanguage~1documentation~1NaturalLanguage~1NLTag~1otherPunctuation/title",
          "value": "NLTagOtherPunctuation"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.naturallanguage~1documentation~1NaturalLanguage~1NLTag~1otherPunctuation/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NLTagOtherPunctuation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.naturallanguage~1documentation~1NaturalLanguage~1NLTag~1noun/title",
          "value": "NLTagNoun"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.naturallanguage~1documentation~1NaturalLanguage~1NLTag~1noun/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NLTagNoun"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.naturallanguage~1documentation~1NaturalLanguage~1NLTag~1preposition/title",
          "value": "NLTagPreposition"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.naturallanguage~1documentation~1NaturalLanguage~1NLTag~1preposition/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NLTagPreposition"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.naturallanguage~1documentation~1NaturalLanguage~1NLTag~1whitespace/title",
          "value": "NLTagWhitespace"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.naturallanguage~1documentation~1NaturalLanguage~1NLTag~1whitespace/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NLTagWhitespace"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.naturallanguage~1documentation~1NaturalLanguage~1NLTag/title",
          "value": "NLTag"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.naturallanguage~1documentation~1NaturalLanguage~1NLTag/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NLTag"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.naturallanguage~1documentation~1NaturalLanguage~1NLTag/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NLTag"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.naturallanguage~1documentation~1NaturalLanguage~1NLTagScheme~1lemma/title",
          "value": "NLTagSchemeLemma"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.naturallanguage~1documentation~1NaturalLanguage~1NLTagScheme~1lemma/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NLTagSchemeLemma"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.naturallanguage~1documentation~1NaturalLanguage~1NLTag~1word/title",
          "value": "NLTagWord"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.naturallanguage~1documentation~1NaturalLanguage~1NLTag~1word/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NLTagWord"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.naturallanguage~1documentation~1NaturalLanguage~1NLTagScheme~1script/title",
          "value": "NLTagSchemeScript"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.naturallanguage~1documentation~1NaturalLanguage~1NLTagScheme~1script/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NLTagSchemeScript"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.naturallanguage~1documentation~1NaturalLanguage~1NLTagScheme~1language/title",
          "value": "NLTagSchemeLanguage"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.naturallanguage~1documentation~1NaturalLanguage~1NLTagScheme~1language/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NLTagSchemeLanguage"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.naturallanguage~1documentation~1NaturalLanguage~1NLTagScheme~1lexicalClass/title",
          "value": "NLTagSchemeLexicalClass"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.naturallanguage~1documentation~1NaturalLanguage~1NLTagScheme~1lexicalClass/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NLTagSchemeLexicalClass"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.naturallanguage~1documentation~1NaturalLanguage~1NLTag~1otherWord/title",
          "value": "NLTagOtherWord"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.naturallanguage~1documentation~1NaturalLanguage~1NLTag~1otherWord/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NLTagOtherWord"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.naturallanguage~1documentation~1NaturalLanguage~1NLTag~1adjective/title",
          "value": "NLTagAdjective"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.naturallanguage~1documentation~1NaturalLanguage~1NLTag~1adjective/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NLTagAdjective"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.naturallanguage~1documentation~1NaturalLanguage~1NLTag~1idiom/title",
          "value": "NLTagIdiom"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.naturallanguage~1documentation~1NaturalLanguage~1NLTag~1idiom/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NLTagIdiom"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.naturallanguage~1documentation~1NaturalLanguage~1NLTag~1punctuation/title",
          "value": "NLTagPunctuation"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.naturallanguage~1documentation~1NaturalLanguage~1NLTag~1punctuation/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NLTagPunctuation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.naturallanguage~1documentation~1NaturalLanguage~1NLTag~1other/title",
          "value": "NLTagOther"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.naturallanguage~1documentation~1NaturalLanguage~1NLTag~1other/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NLTagOther"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.naturallanguage~1documentation~1NaturalLanguage~1NLTag~1dash/title",
          "value": "NLTagDash"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.naturallanguage~1documentation~1NaturalLanguage~1NLTag~1dash/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NLTagDash"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.naturallanguage~1documentation~1NaturalLanguage~1NLTag~1closeParenthesis/title",
          "value": "NLTagCloseParenthesis"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.naturallanguage~1documentation~1NaturalLanguage~1NLTag~1closeParenthesis/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NLTagCloseParenthesis"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.naturallanguage~1documentation~1NaturalLanguage~1NLTag~1sentenceTerminator/title",
          "value": "NLTagSentenceTerminator"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.naturallanguage~1documentation~1NaturalLanguage~1NLTag~1sentenceTerminator/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NLTagSentenceTerminator"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/naturallanguage/nltagscheme/lexicalclass"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/naturallanguage/nltagscheme/lexicalclass"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
