{
  "abstract": [
    {
      "text": "Medium quality, slower than the low interpolation option.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.appkit/documentation/AppKit",
        "doc://com.apple.appkit/documentation/AppKit/NSImageInterpolation"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.appkit/documentation/AppKit/NSImageInterpolation/medium"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@NSImageInterpolation@NSImageInterpolationMedium",
    "fragments": [
      {
        "kind": "keyword",
        "text": "case"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "medium"
      }
    ],
    "modules": [
      {
        "name": "AppKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "NSImageInterpolationMedium"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.6",
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Case",
    "symbolKind": "case",
    "title": "NSImageInterpolation.medium"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "macOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "case"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "medium"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.appkit/documentation/AppKit": {
      "abstract": [
        {
          "text": "Construct and manage a graphical, event-driven user interface for your macOS app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit",
      "kind": "symbol",
      "role": "collection",
      "title": "AppKit",
      "type": "topic",
      "url": "/documentation/appkit"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSImageInterpolation": {
      "abstract": [
        {
          "text": "Constants that specify the interpolation, or image smoothing, behavior used by the image interpolation property.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSImageInterpolation"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSImageInterpolation",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSImageInterpolation"
        }
      ],
      "role": "symbol",
      "title": "NSImageInterpolation",
      "type": "topic",
      "url": "/documentation/appkit/nsimageinterpolation"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSImageInterpolation/default": {
      "abstract": [
        {
          "text": "Use the context’s default interpolation.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "`default`"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSImageInterpolation/default",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSImageInterpolationDefault"
        }
      ],
      "role": "symbol",
      "title": "NSImageInterpolation.default",
      "type": "topic",
      "url": "/documentation/appkit/nsimageinterpolation/default"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSImageInterpolation/high": {
      "abstract": [
        {
          "text": "Highest quality, slower than the medium interpolation option.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "high"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSImageInterpolation/high",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSImageInterpolationHigh"
        }
      ],
      "role": "symbol",
      "title": "NSImageInterpolation.high",
      "type": "topic",
      "url": "/documentation/appkit/nsimageinterpolation/high"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSImageInterpolation/low": {
      "abstract": [
        {
          "text": "Fast, low-quality interpolation.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "low"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSImageInterpolation/low",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSImageInterpolationLow"
        }
      ],
      "role": "symbol",
      "title": "NSImageInterpolation.low",
      "type": "topic",
      "url": "/documentation/appkit/nsimageinterpolation/low"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSImageInterpolation/medium": {
      "abstract": [
        {
          "text": "Medium quality, slower than the low interpolation option.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "medium"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSImageInterpolation/medium",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSImageInterpolationMedium"
        }
      ],
      "role": "symbol",
      "title": "NSImageInterpolation.medium",
      "type": "topic",
      "url": "/documentation/appkit/nsimageinterpolation/medium"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSImageInterpolation/none": {
      "abstract": [
        {
          "text": "No interpolation.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "none"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSImageInterpolation/none",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSImageInterpolationNone"
        }
      ],
      "role": "symbol",
      "title": "NSImageInterpolation.none",
      "type": "topic",
      "url": "/documentation/appkit/nsimageinterpolation/none"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Constants",
      "generated": true,
      "identifiers": [
        "doc://com.apple.appkit/documentation/AppKit/NSImageInterpolation/default",
        "doc://com.apple.appkit/documentation/AppKit/NSImageInterpolation/none",
        "doc://com.apple.appkit/documentation/AppKit/NSImageInterpolation/low",
        "doc://com.apple.appkit/documentation/AppKit/NSImageInterpolation/high"
      ],
      "title": "Constants"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.6",
              "name": "macOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration Case"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "NSImageInterpolationMedium"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "case"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSImageInterpolationMedium"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.appkit/documentation/AppKit",
                "doc://com.apple.appkit/documentation/AppKit/NSImageInterpolation"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Constants",
              "generated": true,
              "identifiers": [
                "doc://com.apple.appkit/documentation/AppKit/NSImageInterpolation/default",
                "doc://com.apple.appkit/documentation/AppKit/NSImageInterpolation/none",
                "doc://com.apple.appkit/documentation/AppKit/NSImageInterpolation/low",
                "doc://com.apple.appkit/documentation/AppKit/NSImageInterpolation/high"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "Mac Catalyst",
                  "macOS"
                ],
                "tokens": [
                  {
                    "kind": "identifier",
                    "text": "NSImageInterpolationMedium"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSImageInterpolation~1none/title",
          "value": "NSImageInterpolationNone"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSImageInterpolation~1none/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSImageInterpolationNone"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSImageInterpolation/title",
          "value": "NSImageInterpolation"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSImageInterpolation/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSImageInterpolation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSImageInterpolation/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSImageInterpolation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSImageInterpolation~1high/title",
          "value": "NSImageInterpolationHigh"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSImageInterpolation~1high/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSImageInterpolationHigh"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSImageInterpolation~1default/title",
          "value": "NSImageInterpolationDefault"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSImageInterpolation~1default/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSImageInterpolationDefault"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSImageInterpolation~1medium/title",
          "value": "NSImageInterpolationMedium"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSImageInterpolation~1medium/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSImageInterpolationMedium"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSImageInterpolation~1low/title",
          "value": "NSImageInterpolationLow"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSImageInterpolation~1low/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSImageInterpolationLow"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/appkit/nsimageinterpolation/medium"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/appkit/nsimageinterpolation/medium"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
