{
  "abstract": [
    {
      "text": "The message contains an activity snippet.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.sirikit/documentation/Intents",
        "doc://com.apple.sirikit/documentation/Intents/INMessageType"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.sirikit/documentation/Intents/INMessageType/activitySnippet"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@INMessageType@INMessageTypeActivitySnippet",
    "fragments": [
      {
        "kind": "keyword",
        "text": "case"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "activitySnippet"
      }
    ],
    "modules": [
      {
        "name": "Intents"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "INMessageTypeActivitySnippet"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "12.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "12.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.1",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "5.0",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Case",
    "symbolKind": "case",
    "title": "INMessageType.activitySnippet"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "case"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "activitySnippet"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.sirikit/documentation/Intents": {
      "abstract": [
        {
          "text": "Empower people to customize interactions for your app on their device.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents",
      "kind": "symbol",
      "role": "collection",
      "title": "Intents",
      "type": "topic",
      "url": "/documentation/intents"
    },
    "doc://com.apple.sirikit/documentation/Intents/INMessageType": {
      "abstract": [
        {
          "text": "Constants that describe the kinds of content a message can contain.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "INMessageType"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INMessageType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INMessageType"
        }
      ],
      "role": "symbol",
      "title": "INMessageType",
      "type": "topic",
      "url": "/documentation/intents/inmessagetype"
    },
    "doc://com.apple.sirikit/documentation/Intents/INMessageType/activitySnippet": {
      "abstract": [
        {
          "text": "The message contains an activity snippet.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "activitySnippet"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INMessageType/activitySnippet",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INMessageTypeActivitySnippet"
        }
      ],
      "role": "symbol",
      "title": "INMessageType.activitySnippet",
      "type": "topic",
      "url": "/documentation/intents/inmessagetype/activitysnippet"
    },
    "doc://com.apple.sirikit/documentation/Intents/INMessageType/animoji": {
      "abstract": [
        {
          "text": "The message content is an animoji.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "animoji"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INMessageType/animoji",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INMessageTypeAnimoji"
        }
      ],
      "role": "symbol",
      "title": "INMessageType.animoji",
      "type": "topic",
      "url": "/documentation/intents/inmessagetype/animoji"
    },
    "doc://com.apple.sirikit/documentation/Intents/INMessageType/audio": {
      "abstract": [
        {
          "text": "The message contains audio content.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "audio"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INMessageType/audio",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INMessageTypeAudio"
        }
      ],
      "role": "symbol",
      "title": "INMessageType.audio",
      "type": "topic",
      "url": "/documentation/intents/inmessagetype/audio"
    },
    "doc://com.apple.sirikit/documentation/Intents/INMessageType/digitalTouch": {
      "abstract": [
        {
          "text": "The message contains digital touch content.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "digitalTouch"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INMessageType/digitalTouch",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INMessageTypeDigitalTouch"
        }
      ],
      "role": "symbol",
      "title": "INMessageType.digitalTouch",
      "type": "topic",
      "url": "/documentation/intents/inmessagetype/digitaltouch"
    },
    "doc://com.apple.sirikit/documentation/Intents/INMessageType/file": {
      "abstract": [
        {
          "text": "The message contains a file.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "file"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INMessageType/file",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INMessageTypeFile"
        }
      ],
      "role": "symbol",
      "title": "INMessageType.file",
      "type": "topic",
      "url": "/documentation/intents/inmessagetype/file"
    },
    "doc://com.apple.sirikit/documentation/Intents/INMessageType/handwriting": {
      "abstract": [
        {
          "text": "The message contains handwritten content.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "handwriting"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INMessageType/handwriting",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INMessageTypeHandwriting"
        }
      ],
      "role": "symbol",
      "title": "INMessageType.handwriting",
      "type": "topic",
      "url": "/documentation/intents/inmessagetype/handwriting"
    },
    "doc://com.apple.sirikit/documentation/Intents/INMessageType/link": {
      "abstract": [
        {
          "text": "The message contains link content.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "link"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INMessageType/link",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INMessageTypeLink"
        }
      ],
      "role": "symbol",
      "title": "INMessageType.link",
      "type": "topic",
      "url": "/documentation/intents/inmessagetype/link"
    },
    "doc://com.apple.sirikit/documentation/Intents/INMessageType/sticker": {
      "abstract": [
        {
          "text": "The message contains sticker content.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "sticker"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INMessageType/sticker",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INMessageTypeSticker"
        }
      ],
      "role": "symbol",
      "title": "INMessageType.sticker",
      "type": "topic",
      "url": "/documentation/intents/inmessagetype/sticker"
    },
    "doc://com.apple.sirikit/documentation/Intents/INMessageType/text": {
      "abstract": [
        {
          "text": "The message content is text-based.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "text"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INMessageType/text",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INMessageTypeText"
        }
      ],
      "role": "symbol",
      "title": "INMessageType.text",
      "type": "topic",
      "url": "/documentation/intents/inmessagetype/text"
    },
    "doc://com.apple.sirikit/documentation/Intents/INMessageType/unspecified": {
      "abstract": [
        {
          "text": "The message content isn’t specified.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "unspecified"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INMessageType/unspecified",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INMessageTypeUnspecified"
        }
      ],
      "role": "symbol",
      "title": "INMessageType.unspecified",
      "type": "topic",
      "url": "/documentation/intents/inmessagetype/unspecified"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "General-Types",
      "generated": true,
      "identifiers": [
        "doc://com.apple.sirikit/documentation/Intents/INMessageType/unspecified",
        "doc://com.apple.sirikit/documentation/Intents/INMessageType/text",
        "doc://com.apple.sirikit/documentation/Intents/INMessageType/animoji",
        "doc://com.apple.sirikit/documentation/Intents/INMessageType/audio",
        "doc://com.apple.sirikit/documentation/Intents/INMessageType/digitalTouch",
        "doc://com.apple.sirikit/documentation/Intents/INMessageType/handwriting",
        "doc://com.apple.sirikit/documentation/Intents/INMessageType/sticker",
        "doc://com.apple.sirikit/documentation/Intents/INMessageType/link",
        "doc://com.apple.sirikit/documentation/Intents/INMessageType/file"
      ],
      "title": "General Types"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "12.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "12.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.1",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "5.0",
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration Case"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "INMessageTypeActivitySnippet"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "case"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INMessageTypeActivitySnippet"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.sirikit/documentation/Intents",
                "doc://com.apple.sirikit/documentation/Intents/INMessageType"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "General-Types",
              "generated": true,
              "identifiers": [
                "doc://com.apple.sirikit/documentation/Intents/INMessageType/unspecified",
                "doc://com.apple.sirikit/documentation/Intents/INMessageType/text",
                "doc://com.apple.sirikit/documentation/Intents/INMessageType/animoji",
                "doc://com.apple.sirikit/documentation/Intents/INMessageType/audio",
                "doc://com.apple.sirikit/documentation/Intents/INMessageType/digitalTouch",
                "doc://com.apple.sirikit/documentation/Intents/INMessageType/handwriting",
                "doc://com.apple.sirikit/documentation/Intents/INMessageType/sticker",
                "doc://com.apple.sirikit/documentation/Intents/INMessageType/link",
                "doc://com.apple.sirikit/documentation/Intents/INMessageType/file"
              ],
              "title": "General Types"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "identifier",
                    "text": "INMessageTypeActivitySnippet"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INMessageType~1digitalTouch/title",
          "value": "INMessageTypeDigitalTouch"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INMessageType~1digitalTouch/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INMessageTypeDigitalTouch"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INMessageType~1activitySnippet/title",
          "value": "INMessageTypeActivitySnippet"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INMessageType~1activitySnippet/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INMessageTypeActivitySnippet"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INMessageType~1handwriting/title",
          "value": "INMessageTypeHandwriting"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INMessageType~1handwriting/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INMessageTypeHandwriting"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INMessageType~1link/title",
          "value": "INMessageTypeLink"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INMessageType~1link/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INMessageTypeLink"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INMessageType~1sticker/title",
          "value": "INMessageTypeSticker"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INMessageType~1sticker/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INMessageTypeSticker"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INMessageType~1text/title",
          "value": "INMessageTypeText"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INMessageType~1text/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INMessageTypeText"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INMessageType~1file/title",
          "value": "INMessageTypeFile"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INMessageType~1file/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INMessageTypeFile"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INMessageType~1unspecified/title",
          "value": "INMessageTypeUnspecified"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INMessageType~1unspecified/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INMessageTypeUnspecified"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INMessageType~1animoji/title",
          "value": "INMessageTypeAnimoji"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INMessageType~1animoji/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INMessageTypeAnimoji"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INMessageType/title",
          "value": "INMessageType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INMessageType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INMessageType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INMessageType/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "INMessageType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INMessageType~1audio/title",
          "value": "INMessageTypeAudio"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INMessageType~1audio/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INMessageTypeAudio"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/intents/inmessagetype/activitysnippet"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/intents/inmessagetype/activitysnippet"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
