{
  "abstract": [
    {
      "text": "Media content containing an image.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.sirikit/documentation/Intents",
        "doc://com.apple.sirikit/documentation/Intents/INMessageType"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.sirikit/documentation/Intents/INMessageType/mediaImage"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@INMessageType@INMessageTypeMediaImage",
    "fragments": [
      {
        "kind": "keyword",
        "text": "case"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "mediaImage"
      }
    ],
    "modules": [
      {
        "name": "Intents"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "INMessageTypeMediaImage"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "11.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "11.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.1",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "4.0",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Case",
    "symbolKind": "case",
    "title": "INMessageType.mediaImage"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "case"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "mediaImage"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.sirikit/documentation/Intents": {
      "abstract": [
        {
          "text": "Empower people to customize interactions for your app on their device.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents",
      "kind": "symbol",
      "role": "collection",
      "title": "Intents",
      "type": "topic",
      "url": "/documentation/intents"
    },
    "doc://com.apple.sirikit/documentation/Intents/INMessageType": {
      "abstract": [
        {
          "text": "Constants that describe the kinds of content a message can contain.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "INMessageType"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INMessageType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INMessageType"
        }
      ],
      "role": "symbol",
      "title": "INMessageType",
      "type": "topic",
      "url": "/documentation/intents/inmessagetype"
    },
    "doc://com.apple.sirikit/documentation/Intents/INMessageType/mediaAddressCard": {
      "abstract": [
        {
          "text": "Media content containing an address card.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "mediaAddressCard"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INMessageType/mediaAddressCard",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INMessageTypeMediaAddressCard"
        }
      ],
      "role": "symbol",
      "title": "INMessageType.mediaAddressCard",
      "type": "topic",
      "url": "/documentation/intents/inmessagetype/mediaaddresscard"
    },
    "doc://com.apple.sirikit/documentation/Intents/INMessageType/mediaAudio": {
      "abstract": [
        {
          "text": "Media content containing audio.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "mediaAudio"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INMessageType/mediaAudio",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INMessageTypeMediaAudio"
        }
      ],
      "role": "symbol",
      "title": "INMessageType.mediaAudio",
      "type": "topic",
      "url": "/documentation/intents/inmessagetype/mediaaudio"
    },
    "doc://com.apple.sirikit/documentation/Intents/INMessageType/mediaCalendar": {
      "abstract": [
        {
          "text": "Media content containing calendar data.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "mediaCalendar"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INMessageType/mediaCalendar",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INMessageTypeMediaCalendar"
        }
      ],
      "role": "symbol",
      "title": "INMessageType.mediaCalendar",
      "type": "topic",
      "url": "/documentation/intents/inmessagetype/mediacalendar"
    },
    "doc://com.apple.sirikit/documentation/Intents/INMessageType/mediaImage": {
      "abstract": [
        {
          "text": "Media content containing an image.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "mediaImage"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INMessageType/mediaImage",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INMessageTypeMediaImage"
        }
      ],
      "role": "symbol",
      "title": "INMessageType.mediaImage",
      "type": "topic",
      "url": "/documentation/intents/inmessagetype/mediaimage"
    },
    "doc://com.apple.sirikit/documentation/Intents/INMessageType/mediaLocation": {
      "abstract": [
        {
          "text": "Media content containing location data.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "mediaLocation"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INMessageType/mediaLocation",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INMessageTypeMediaLocation"
        }
      ],
      "role": "symbol",
      "title": "INMessageType.mediaLocation",
      "type": "topic",
      "url": "/documentation/intents/inmessagetype/medialocation"
    },
    "doc://com.apple.sirikit/documentation/Intents/INMessageType/mediaPass": {
      "abstract": [
        {
          "text": "Media content containing PassKit data.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "mediaPass"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INMessageType/mediaPass",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INMessageTypeMediaPass"
        }
      ],
      "role": "symbol",
      "title": "INMessageType.mediaPass",
      "type": "topic",
      "url": "/documentation/intents/inmessagetype/mediapass"
    },
    "doc://com.apple.sirikit/documentation/Intents/INMessageType/mediaVideo": {
      "abstract": [
        {
          "text": "Media content containing video.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "mediaVideo"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INMessageType/mediaVideo",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INMessageTypeMediaVideo"
        }
      ],
      "role": "symbol",
      "title": "INMessageType.mediaVideo",
      "type": "topic",
      "url": "/documentation/intents/inmessagetype/mediavideo"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Media-Types",
      "generated": true,
      "identifiers": [
        "doc://com.apple.sirikit/documentation/Intents/INMessageType/mediaCalendar",
        "doc://com.apple.sirikit/documentation/Intents/INMessageType/mediaLocation",
        "doc://com.apple.sirikit/documentation/Intents/INMessageType/mediaAddressCard",
        "doc://com.apple.sirikit/documentation/Intents/INMessageType/mediaVideo",
        "doc://com.apple.sirikit/documentation/Intents/INMessageType/mediaPass",
        "doc://com.apple.sirikit/documentation/Intents/INMessageType/mediaAudio"
      ],
      "title": "Media Types"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "11.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "11.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.1",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "4.0",
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration Case"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "INMessageTypeMediaImage"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "case"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INMessageTypeMediaImage"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.sirikit/documentation/Intents",
                "doc://com.apple.sirikit/documentation/Intents/INMessageType"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Media-Types",
              "generated": true,
              "identifiers": [
                "doc://com.apple.sirikit/documentation/Intents/INMessageType/mediaCalendar",
                "doc://com.apple.sirikit/documentation/Intents/INMessageType/mediaLocation",
                "doc://com.apple.sirikit/documentation/Intents/INMessageType/mediaAddressCard",
                "doc://com.apple.sirikit/documentation/Intents/INMessageType/mediaVideo",
                "doc://com.apple.sirikit/documentation/Intents/INMessageType/mediaPass",
                "doc://com.apple.sirikit/documentation/Intents/INMessageType/mediaAudio"
              ],
              "title": "Media Types"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "identifier",
                    "text": "INMessageTypeMediaImage"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INMessageType~1mediaAudio/title",
          "value": "INMessageTypeMediaAudio"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INMessageType~1mediaAudio/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INMessageTypeMediaAudio"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INMessageType~1mediaImage/title",
          "value": "INMessageTypeMediaImage"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INMessageType~1mediaImage/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INMessageTypeMediaImage"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INMessageType~1mediaAddressCard/title",
          "value": "INMessageTypeMediaAddressCard"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INMessageType~1mediaAddressCard/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INMessageTypeMediaAddressCard"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INMessageType~1mediaLocation/title",
          "value": "INMessageTypeMediaLocation"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INMessageType~1mediaLocation/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INMessageTypeMediaLocation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INMessageType~1mediaVideo/title",
          "value": "INMessageTypeMediaVideo"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INMessageType~1mediaVideo/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INMessageTypeMediaVideo"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INMessageType~1mediaPass/title",
          "value": "INMessageTypeMediaPass"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INMessageType~1mediaPass/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INMessageTypeMediaPass"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INMessageType/title",
          "value": "INMessageType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INMessageType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INMessageType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INMessageType/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "INMessageType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INMessageType~1mediaCalendar/title",
          "value": "INMessageTypeMediaCalendar"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INMessageType~1mediaCalendar/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INMessageTypeMediaCalendar"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/intents/inmessagetype/mediaimage"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/intents/inmessagetype/mediaimage"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
