{
  "abstract": [
    {
      "text": "Content indicating that the user emphasized something.",
      "type": "text"
    }
  ],
  "deprecationSummary": [
    {
      "inlineContent": [
        {
          "text": "Use INMessageReaction",
          "type": "text"
        }
      ],
      "type": "paragraph"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.sirikit/documentation/Intents",
        "doc://com.apple.sirikit/documentation/Intents/INMessageType"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.sirikit/documentation/Intents/INMessageType/tapbackEmphasized"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@INMessageType@INMessageTypeTapbackEmphasized",
    "fragments": [
      {
        "kind": "keyword",
        "text": "case"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "tapbackEmphasized"
      }
    ],
    "modules": [
      {
        "name": "Intents"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "INMessageTypeTapbackEmphasized"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "18.1",
        "introducedAt": "11.0",
        "message": "Use INMessageReaction",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "18.1",
        "introducedAt": "11.0",
        "message": "Use INMessageReaction",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "18.1",
        "introducedAt": "13.1",
        "message": "Use INMessageReaction",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "2.1",
        "introducedAt": "1.0",
        "message": "Use INMessageReaction",
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "11.1",
        "introducedAt": "4.0",
        "message": "Use INMessageReaction",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Case",
    "symbolKind": "case",
    "title": "INMessageType.tapbackEmphasized"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "case"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "tapbackEmphasized"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.sirikit/documentation/Intents": {
      "abstract": [
        {
          "text": "Empower people to customize interactions for your app on their device.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents",
      "kind": "symbol",
      "role": "collection",
      "title": "Intents",
      "type": "topic",
      "url": "/documentation/intents"
    },
    "doc://com.apple.sirikit/documentation/Intents/INMessageType": {
      "abstract": [
        {
          "text": "Constants that describe the kinds of content a message can contain.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "INMessageType"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INMessageType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INMessageType"
        }
      ],
      "role": "symbol",
      "title": "INMessageType",
      "type": "topic",
      "url": "/documentation/intents/inmessagetype"
    },
    "doc://com.apple.sirikit/documentation/Intents/INMessageType/tapbackDisliked": {
      "abstract": [
        {
          "text": "Content indicating that the user disliked something.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "tapbackDisliked"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INMessageType/tapbackDisliked",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INMessageTypeTapbackDisliked"
        }
      ],
      "role": "symbol",
      "title": "INMessageType.tapbackDisliked",
      "type": "topic",
      "url": "/documentation/intents/inmessagetype/tapbackdisliked"
    },
    "doc://com.apple.sirikit/documentation/Intents/INMessageType/tapbackEmphasized": {
      "abstract": [
        {
          "text": "Content indicating that the user emphasized something.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "tapbackEmphasized"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INMessageType/tapbackEmphasized",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INMessageTypeTapbackEmphasized"
        }
      ],
      "role": "symbol",
      "title": "INMessageType.tapbackEmphasized",
      "type": "topic",
      "url": "/documentation/intents/inmessagetype/tapbackemphasized"
    },
    "doc://com.apple.sirikit/documentation/Intents/INMessageType/tapbackLaughed": {
      "abstract": [
        {
          "text": "Content indicating that the user laughed at something.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "tapbackLaughed"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INMessageType/tapbackLaughed",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INMessageTypeTapbackLaughed"
        }
      ],
      "role": "symbol",
      "title": "INMessageType.tapbackLaughed",
      "type": "topic",
      "url": "/documentation/intents/inmessagetype/tapbacklaughed"
    },
    "doc://com.apple.sirikit/documentation/Intents/INMessageType/tapbackLiked": {
      "abstract": [
        {
          "text": "Content indicating that the user liked something.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "tapbackLiked"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INMessageType/tapbackLiked",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INMessageTypeTapbackLiked"
        }
      ],
      "role": "symbol",
      "title": "INMessageType.tapbackLiked",
      "type": "topic",
      "url": "/documentation/intents/inmessagetype/tapbackliked"
    },
    "doc://com.apple.sirikit/documentation/Intents/INMessageType/tapbackLoved": {
      "abstract": [
        {
          "text": "Content indicating that the user loved something.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "tapbackLoved"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INMessageType/tapbackLoved",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INMessageTypeTapbackLoved"
        }
      ],
      "role": "symbol",
      "title": "INMessageType.tapbackLoved",
      "type": "topic",
      "url": "/documentation/intents/inmessagetype/tapbackloved"
    },
    "doc://com.apple.sirikit/documentation/Intents/INMessageType/tapbackQuestioned": {
      "abstract": [
        {
          "text": "Content indicating that the user questioned something.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "tapbackQuestioned"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INMessageType/tapbackQuestioned",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INMessageTypeTapbackQuestioned"
        }
      ],
      "role": "symbol",
      "title": "INMessageType.tapbackQuestioned",
      "type": "topic",
      "url": "/documentation/intents/inmessagetype/tapbackquestioned"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Tapback-Types",
      "generated": true,
      "identifiers": [
        "doc://com.apple.sirikit/documentation/Intents/INMessageType/tapbackLiked",
        "doc://com.apple.sirikit/documentation/Intents/INMessageType/tapbackDisliked",
        "doc://com.apple.sirikit/documentation/Intents/INMessageType/tapbackLoved",
        "doc://com.apple.sirikit/documentation/Intents/INMessageType/tapbackQuestioned",
        "doc://com.apple.sirikit/documentation/Intents/INMessageType/tapbackLaughed"
      ],
      "title": "Tapback Types"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "deprecatedAt": "18.1",
              "introducedAt": "11.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "deprecatedAt": "18.1",
              "introducedAt": "11.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "deprecatedAt": "18.1",
              "introducedAt": "13.1",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "deprecatedAt": "2.1",
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "deprecatedAt": "11.1",
              "introducedAt": "4.0",
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration Case"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "INMessageTypeTapbackEmphasized"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "case"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INMessageTypeTapbackEmphasized"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.sirikit/documentation/Intents",
                "doc://com.apple.sirikit/documentation/Intents/INMessageType"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Tapback-Types",
              "generated": true,
              "identifiers": [
                "doc://com.apple.sirikit/documentation/Intents/INMessageType/tapbackLiked",
                "doc://com.apple.sirikit/documentation/Intents/INMessageType/tapbackDisliked",
                "doc://com.apple.sirikit/documentation/Intents/INMessageType/tapbackLoved",
                "doc://com.apple.sirikit/documentation/Intents/INMessageType/tapbackQuestioned",
                "doc://com.apple.sirikit/documentation/Intents/INMessageType/tapbackLaughed"
              ],
              "title": "Tapback Types"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "identifier",
                    "text": "INMessageTypeTapbackEmphasized"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/deprecationSummary",
          "value": [
            {
              "inlineContent": [
                {
                  "text": "Use INMessageReaction",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INMessageType~1tapbackEmphasized/title",
          "value": "INMessageTypeTapbackEmphasized"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INMessageType~1tapbackEmphasized/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INMessageTypeTapbackEmphasized"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INMessageType~1tapbackLiked/title",
          "value": "INMessageTypeTapbackLiked"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INMessageType~1tapbackLiked/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INMessageTypeTapbackLiked"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INMessageType~1tapbackDisliked/title",
          "value": "INMessageTypeTapbackDisliked"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INMessageType~1tapbackDisliked/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INMessageTypeTapbackDisliked"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INMessageType/title",
          "value": "INMessageType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INMessageType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INMessageType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INMessageType/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "INMessageType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INMessageType~1tapbackLoved/title",
          "value": "INMessageTypeTapbackLoved"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INMessageType~1tapbackLoved/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INMessageTypeTapbackLoved"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INMessageType~1tapbackLaughed/title",
          "value": "INMessageTypeTapbackLaughed"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INMessageType~1tapbackLaughed/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INMessageTypeTapbackLaughed"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INMessageType~1tapbackQuestioned/title",
          "value": "INMessageTypeTapbackQuestioned"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INMessageType~1tapbackQuestioned/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INMessageTypeTapbackQuestioned"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/intents/inmessagetype/tapbackemphasized"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/intents/inmessagetype/tapbackemphasized"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
