{
  "abstract": [
    {
      "text": "Use attachments to store a test’s output data for later analysis.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.xctest/documentation/XCTest",
        "doc://com.apple.xctest/documentation/XCTest/activities-and-attachments"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.xctest/documentation/XCTest/adding-attachments-to-tests-activities-and-issues"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "XCTest"
      }
    ],
    "role": "article",
    "roleHeading": "Article",
    "title": "Adding Attachments to Tests, Activities, and Issues"
  },
  "primaryContentSections": [
    {
      "content": [
        {
          "anchor": "overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Tests often produce output such as files, images, screenshots, and data during their execution. You can store this test output for later analysis by wrapping it in an ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.xctest/documentation/XCTest/XCTAttachment",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " instance and adding it to the current test, activity, or issue. You can then view these attachments within Xcode’s test results browser alongside the test, activity, or issue that created them.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "identifier": "media-2902802",
              "type": "image"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "identifier": "doc://com.apple.xctest/documentation/XCTest/XCTAttachment",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " provides several convenience initializers to create attachments for common data types, such as images, screenshots, files, folders, strings, and custom objects, that conform to ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/foundation/nssecurecoding",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " or that you can encode as a property list. Alternatively, you can attach custom test output by creating an attachment from raw data in memory.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "You associate an attachment with a test by calling the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.xctest/documentation/XCTest/XCTActivity/add(_:)",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " method on an instance of a type that conforms to the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.xctest/documentation/XCTest/XCTActivity",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " protocol. ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.xctest/documentation/XCTest/XCTestCase",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " automatically conforms to ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.xctest/documentation/XCTest/XCTActivity",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " so you can add an attachment to the current test by calling ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.xctest/documentation/XCTest/XCTActivity/add(_:)",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " from within any test method.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "Listing 1. Attaching a screenshot of an app’s first window to the current test.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "code": [
            "class MainWindowScreenshotTests: XCTestCase {",
            "    func testTakeScreenshotOfMainWindow() {",
            "        let app = XCUIApplication()",
            "        app.launch()",
            "        let screenshot = app.windows.firstMatch.screenshot()",
            "        let attachment = XCTAttachment(screenshot: screenshot)",
            "        attachment.lifetime = .keepAlways",
            "        add(attachment)",
            "    }",
            "}"
          ],
          "syntax": "swift",
          "type": "codeListing"
        },
        {
          "inlineContent": [
            {
              "text": "Alternatively, you can create and run a custom activity by calling the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.xctest/documentation/XCTest/XCTContext",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.xctest/documentation/XCTest/XCTContext/runActivityNamed:block:",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " class method from anywhere in your testing code. This method runs a user-provided block of test code, passing an ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.xctest/documentation/XCTest/XCTActivity",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " instance to the block. Call ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.xctest/documentation/XCTest/XCTActivity/add(_:)",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " on this ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.xctest/documentation/XCTest/XCTActivity",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " instance to add an attachment to the activity instead of the overall test.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "Every attachment you create has a ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.xctest/documentation/XCTest/XCTAttachment/uniformTypeIdentifier",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " property containing a Uniform Type Identifier (UTI) that identifies the type of content in the attachment. Many of ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.xctest/documentation/XCTest/XCTAttachment",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": "’s convenience initializers determine an appropriate UTI to use from their provided content. Alternatively, you can provide a manual UTI value to represent a custom data format to use in your app.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "Listing 2. Adding attachments in response to a background data download",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "code": [
            "func testDownloadAndAttachWebData() {",
            "    ",
            "    // Create an expectation for a background download task.",
            "    let expectation = XCTestExpectation(description: \"Download apple.com home page\")",
            "    ",
            "    // Create a URL for a web page to download.",
            "    let url = URL(string: \"https://apple.com\")!",
            "    ",
            "    // Create a background task to download the web page.",
            "    let dataTask = URLSession.shared.dataTask(with: url) { (data, urlResponse, error) in",
            "        ",
            "        // Process the download task's response, adding some of its output as attachments.",
            "        ",
            "        if let error = error {",
            "            ",
            "            XCTFail(\"Data failed to download with an error: \\(error.localizedDescription).\")",
            "            ",
            "        } else if let httpURLResponse = urlResponse as? HTTPURLResponse, httpURLResponse.statusCode != 200 {",
            "            ",
            "            // Attach the response's header fields as an XML property list.              ",
            "            let headers = XCTAttachment(plistObject: httpURLResponse.allHeaderFields)",
            "            headers.name = \"Headers\"",
            "                ",
            "            let description = \"Unexpected status code: \\(httpURLResponse.statusCode).\"",
            "            var issue = XCTIssue(type: .assertionFailure, compactDescription: description)",
            "            issue.add(headers)",
            "            self.record(issue)",
            "            ",
            "        } else if let data = data {",
            "            ",
            "            // Attach the retrieved HTML data with an appropriate UTI.",
            "            let html = XCTAttachment(data: data, uniformTypeIdentifier: \"public.html\")",
            "            html.name = \"HTML\"",
            "            // Keep the HTML attachment even when the test succeeds.",
            "            html.lifetime = .keepAlways",
            "            self.add(html)",
            "            ",
            "        }",
            "        ",
            "        // Fulfill the expectation to indicate that the background task has finished.",
            "        expectation.fulfill()",
            "        ",
            "    }",
            "    ",
            "    // Start the download task.",
            "    dataTask.resume()",
            "    ",
            "    // Wait until the expectation is fulfilled, with a timeout of 10 seconds.",
            "    wait(for: [expectation], timeout: 10.0)",
            "    ",
            "}"
          ],
          "syntax": "swift",
          "type": "codeListing"
        },
        {
          "inlineContent": [
            {
              "text": "Listing 2 performs an integration test of a web page download. The download occurs on a background thread.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "The code above produces one of three outcomes from the results of the download:",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "items": [
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "If the data task returns an error, the test fails and logs the error’s description as part of the failure.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "If the data task succeeds, but has an HTTP response status code of anything other than ",
                      "type": "text"
                    },
                    {
                      "code": "200 OK",
                      "type": "codeVoice"
                    },
                    {
                      "text": ", the sample code adds the response’s header fields to a new ",
                      "type": "text"
                    },
                    {
                      "code": "XCTIssue",
                      "type": "codeVoice"
                    },
                    {
                      "text": " as an XML property list attachment to assist with debugging the problem.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "If the data task succeeds and retrieves some data, the sample code adds the retrieved data to the test as an attachment with a UTI of ",
                      "type": "text"
                    },
                    {
                      "code": "public.html",
                      "type": "codeVoice"
                    },
                    {
                      "text": ", enabling Xcode to provide an appropriate Quick Look for the data within the Xcode test results browser. The sample code sets the attachment’s lifetime property to ",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.xctest/documentation/XCTest/XCTAttachment/Lifetime-swift.enum/keepAlways",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": " to store the HTML data even though the test succeeds.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            }
          ],
          "type": "unorderedList"
        },
        {
          "inlineContent": [
            {
              "text": "See ",
              "type": "text"
            },
            {
              "code": "Testing Asynchronous Operations with Expectations",
              "type": "codeVoice"
            },
            {
              "text": " for more information.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "anchor": "Attachment-Lifetime",
          "level": 3,
          "text": "Attachment Lifetime",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "By default, when the test passes successfully, it discards the test’s attachments to save storage. To persist an attachment even when its test passes, set the attachment’s ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.xctest/documentation/XCTest/XCTAttachment/lifetime-swift.property",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " property to ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.xctest/documentation/XCTest/XCTAttachment/Lifetime-swift.enum/keepAlways",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " rather than the default value of ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.xctest/documentation/XCTest/XCTAttachment/Lifetime-swift.enum/deleteOnSuccess",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ". Alternatively, change the default lifetime for an entire test scheme by deselecting the “Attachments: Delete when each test succeeds” option in the Options tab of the scheme’s Test scheme action.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "identifier": "media-2902800",
              "type": "image"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/foundation/nssecurecoding": {
      "abstract": [
        {
          "text": "A protocol that enables encoding and decoding in a manner that is robust against object substitution attacks.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "protocol "
        },
        {
          "kind": "identifier",
          "text": "NSSecureCoding"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/foundation/nssecurecoding",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSSecureCoding",
      "type": "topic",
      "url": "/documentation/foundation/nssecurecoding"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.xctest/documentation/XCTest": {
      "abstract": [
        {
          "text": "Create and run unit tests, performance tests, and UI tests for your Xcode project.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.xctest/documentation/XCTest",
      "kind": "symbol",
      "role": "collection",
      "title": "XCTest",
      "type": "topic",
      "url": "/documentation/xctest"
    },
    "doc://com.apple.xctest/documentation/XCTest/XCTActivity": {
      "abstract": [
        {
          "text": "A named substep of a test method.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "XCTActivity"
        }
      ],
      "identifier": "doc://com.apple.xctest/documentation/XCTest/XCTActivity",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "XCTActivity"
        }
      ],
      "role": "symbol",
      "title": "XCTActivity",
      "type": "topic",
      "url": "/documentation/xctest/xctactivity"
    },
    "doc://com.apple.xctest/documentation/XCTest/XCTActivity/add(_:)": {
      "abstract": [
        {
          "text": "Associates a file, image, or other attachment with the activity.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "add"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)XCTAttachment",
          "text": "XCTAttachment"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.xctest/documentation/XCTest/XCTActivity/add(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "addAttachment:"
        }
      ],
      "required": true,
      "role": "symbol",
      "title": "add(_:)",
      "type": "topic",
      "url": "/documentation/xctest/xctactivity/add(_:)"
    },
    "doc://com.apple.xctest/documentation/XCTest/XCTAttachment": {
      "abstract": [
        {
          "text": "Data from a test method’s execution, such as a file, image, screenshot, data blob, or ZIP file.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "XCTAttachment"
        }
      ],
      "identifier": "doc://com.apple.xctest/documentation/XCTest/XCTAttachment",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "XCTAttachment"
        }
      ],
      "role": "symbol",
      "title": "XCTAttachment",
      "type": "topic",
      "url": "/documentation/xctest/xctattachment"
    },
    "doc://com.apple.xctest/documentation/XCTest/XCTAttachment/Lifetime-swift.enum/deleteOnSuccess": {
      "abstract": [
        {
          "text": "Indicates that the attachment should be deleted if the test passes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "deleteOnSuccess"
        }
      ],
      "identifier": "doc://com.apple.xctest/documentation/XCTest/XCTAttachment/Lifetime-swift.enum/deleteOnSuccess",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "XCTAttachmentLifetimeDeleteOnSuccess"
        }
      ],
      "role": "symbol",
      "title": "XCTAttachment.Lifetime.deleteOnSuccess",
      "type": "topic",
      "url": "/documentation/xctest/xctattachment/lifetime-swift.enum/deleteonsuccess"
    },
    "doc://com.apple.xctest/documentation/XCTest/XCTAttachment/Lifetime-swift.enum/keepAlways": {
      "abstract": [
        {
          "text": "Indicates that the attachment should be persisted as part of the test’s results even if the test passes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "keepAlways"
        }
      ],
      "identifier": "doc://com.apple.xctest/documentation/XCTest/XCTAttachment/Lifetime-swift.enum/keepAlways",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "XCTAttachmentLifetimeKeepAlways"
        }
      ],
      "role": "symbol",
      "title": "XCTAttachment.Lifetime.keepAlways",
      "type": "topic",
      "url": "/documentation/xctest/xctattachment/lifetime-swift.enum/keepalways"
    },
    "doc://com.apple.xctest/documentation/XCTest/XCTAttachment/lifetime-swift.property": {
      "abstract": [
        {
          "text": "Indicates whether the attachment is kept or discarded when its associated test passes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "lifetime"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)XCTAttachment",
          "text": "XCTAttachment"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@XCTAttachmentLifetime",
          "text": "Lifetime"
        }
      ],
      "identifier": "doc://com.apple.xctest/documentation/XCTest/XCTAttachment/lifetime-swift.property",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "lifetime"
        }
      ],
      "role": "symbol",
      "title": "lifetime",
      "type": "topic",
      "url": "/documentation/xctest/xctattachment/lifetime-swift.property"
    },
    "doc://com.apple.xctest/documentation/XCTest/XCTAttachment/uniformTypeIdentifier": {
      "abstract": [
        {
          "text": "The Uniform Type Identifier (UTI) of the data represented by the attachment.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "uniformTypeIdentifier"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.xctest/documentation/XCTest/XCTAttachment/uniformTypeIdentifier",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "uniformTypeIdentifier"
        }
      ],
      "role": "symbol",
      "title": "uniformTypeIdentifier",
      "type": "topic",
      "url": "/documentation/xctest/xctattachment/uniformtypeidentifier"
    },
    "doc://com.apple.xctest/documentation/XCTest/XCTContext": {
      "abstract": [
        {
          "text": "A proxy for the current testing context.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "XCTContext"
        }
      ],
      "identifier": "doc://com.apple.xctest/documentation/XCTest/XCTContext",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "XCTContext"
        }
      ],
      "role": "symbol",
      "title": "XCTContext",
      "type": "topic",
      "url": "/documentation/xctest/xctcontext"
    },
    "doc://com.apple.xctest/documentation/XCTest/XCTContext/runActivityNamed:block:": {
      "abstract": [
        {
          "text": "Creates and runs an activity with the provided block of code.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "+ "
        },
        {
          "kind": "identifier",
          "text": "runActivityNamed:block:"
        }
      ],
      "identifier": "doc://com.apple.xctest/documentation/XCTest/XCTContext/runActivityNamed:block:",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "runActivityNamed:block:"
        }
      ],
      "role": "symbol",
      "title": "runActivityNamed:block:",
      "type": "topic",
      "url": "/documentation/xctest/xctcontext/runactivitynamed:block:"
    },
    "doc://com.apple.xctest/documentation/XCTest/XCTestCase": {
      "abstract": [
        {
          "text": "The primary class for defining test cases, test methods, and performance tests.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "XCTestCase"
        }
      ],
      "identifier": "doc://com.apple.xctest/documentation/XCTest/XCTestCase",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "XCTestCase"
        }
      ],
      "role": "symbol",
      "title": "XCTestCase",
      "type": "topic",
      "url": "/documentation/xctest/xctestcase"
    },
    "doc://com.apple.xctest/documentation/XCTest/activities-and-attachments": {
      "abstract": [
        {
          "text": "Split long tests into substeps with activities, and attach output data like files and screenshots.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.xctest/documentation/XCTest/activities-and-attachments",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Activities and Attachments",
      "type": "topic",
      "url": "/documentation/xctest/activities-and-attachments"
    },
    "media-2902800": {
      "alt": "A screenshot of Xcode’s Scheme Editor showing the “Delete when each test succeeds” attachments option in the Options tab of the scheme’s Test scheme action.",
      "identifier": "media-2902800",
      "type": "image",
      "variants": [
        {
          "traits": [
            "2x",
            "light"
          ],
          "url": "https://docs-assets.developer.apple.com/published/cf13056c108c4aabbb248e2377bbfdc1/media-2902800@2x.png"
        }
      ]
    },
    "media-2902802": {
      "alt": "A screenshot of the output of a UI test in Xcode’s test results browser. A contextual menu shows an option to view a Quick Look of a screenshot attachment.",
      "identifier": "media-2902802",
      "type": "image",
      "variants": [
        {
          "traits": [
            "2x",
            "light"
          ],
          "url": "https://docs-assets.developer.apple.com/published/8c704d4950733f86624db25ac36ac90f/media-2902802@2x.png"
        }
      ]
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Attachments",
      "generated": true,
      "identifiers": [
        "doc://com.apple.xctest/documentation/XCTest/XCTAttachment"
      ],
      "title": "Attachments"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Attachments",
              "generated": true,
              "identifiers": [
                "doc://com.apple.xctest/documentation/XCTest/XCTAttachment"
              ],
              "title": "Attachments"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCTAttachment~1uniformTypeIdentifier/title",
          "value": "uniformTypeIdentifier"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCTAttachment~1uniformTypeIdentifier/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "uniformTypeIdentifier"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCTActivity~1add(_:)/title",
          "value": "addAttachment:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCTActivity~1add(_:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "addAttachment:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCTestCase/title",
          "value": "XCTestCase"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCTestCase/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "XCTestCase"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCTestCase/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "XCTestCase"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCTContext/title",
          "value": "XCTContext"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCTContext/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "XCTContext"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCTContext/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "XCTContext"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCTActivity/title",
          "value": "XCTActivity"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCTActivity/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "XCTActivity"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCTActivity/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "XCTActivity"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCTAttachment~1Lifetime-swift.enum~1keepAlways/title",
          "value": "XCTAttachmentLifetimeKeepAlways"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCTAttachment~1Lifetime-swift.enum~1keepAlways/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "XCTAttachmentLifetimeKeepAlways"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCTAttachment~1Lifetime-swift.enum~1deleteOnSuccess/title",
          "value": "XCTAttachmentLifetimeDeleteOnSuccess"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCTAttachment~1Lifetime-swift.enum~1deleteOnSuccess/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "XCTAttachmentLifetimeDeleteOnSuccess"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCTAttachment/title",
          "value": "XCTAttachment"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCTAttachment/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "XCTAttachment"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCTAttachment/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "XCTAttachment"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCTAttachment~1lifetime-swift.property/title",
          "value": "lifetime"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCTAttachment~1lifetime-swift.property/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "lifetime"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/xctest/adding-attachments-to-tests-activities-and-issues"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/xctest/adding-attachments-to-tests-activities-and-issues"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
