{
  "abstract": [
    {
      "text": "Compare two values to determine whether one is larger or smaller than the other.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.xctest/documentation/XCTest"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.xctest/documentation/XCTest/comparable-value-assertions"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "XCTest"
      }
    ],
    "role": "collectionGroup",
    "roleHeading": "API Collection",
    "title": "Comparable Value Assertions"
  },
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.xctest/documentation/XCTest": {
      "abstract": [
        {
          "text": "Create and run unit tests, performance tests, and UI tests for your Xcode project.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.xctest/documentation/XCTest",
      "kind": "symbol",
      "role": "collection",
      "title": "XCTest",
      "type": "topic",
      "url": "/documentation/xctest"
    },
    "doc://com.apple.xctest/documentation/XCTest/XCTAssertGreaterThan": {
      "abstract": [
        {
          "text": "Asserts that the value of the first expression is greater than the value of the second expression.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "XCTAssertGreaterThan"
        }
      ],
      "identifier": "doc://com.apple.xctest/documentation/XCTest/XCTAssertGreaterThan",
      "kind": "symbol",
      "role": "symbol",
      "title": "XCTAssertGreaterThan",
      "type": "topic",
      "url": "/documentation/xctest/xctassertgreaterthan"
    },
    "doc://com.apple.xctest/documentation/XCTest/XCTAssertGreaterThan(_:_:_:file:line:)": {
      "abstract": [
        {
          "text": "Asserts that the value of the first expression is greater than the value of the second expression.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "XCTAssertGreaterThan"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "genericParameter",
          "text": "T"
        },
        {
          "kind": "text",
          "text": ">("
        },
        {
          "kind": "attribute",
          "text": "@autoclosure "
        },
        {
          "kind": "text",
          "text": "() "
        },
        {
          "kind": "keyword",
          "text": "throws"
        },
        {
          "kind": "text",
          "text": " -> "
        },
        {
          "kind": "typeIdentifier",
          "text": "T"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "attribute",
          "text": "@autoclosure "
        },
        {
          "kind": "text",
          "text": "() "
        },
        {
          "kind": "keyword",
          "text": "throws"
        },
        {
          "kind": "text",
          "text": " -> "
        },
        {
          "kind": "typeIdentifier",
          "text": "T"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "attribute",
          "text": "@autoclosure "
        },
        {
          "kind": "text",
          "text": "() -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "file"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s12StaticStringV",
          "text": "StaticString"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "line"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Su",
          "text": "UInt"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.xctest/documentation/XCTest/XCTAssertGreaterThan(_:_:_:file:line:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "XCTAssertGreaterThan(_:_:_:file:line:)",
      "type": "topic",
      "url": "/documentation/xctest/xctassertgreaterthan(_:_:_:file:line:)"
    },
    "doc://com.apple.xctest/documentation/XCTest/XCTAssertGreaterThanOrEqual": {
      "abstract": [
        {
          "text": "Asserts that the value of the first expression is greater than or equal to the value of the second expression.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "XCTAssertGreaterThanOrEqual"
        }
      ],
      "identifier": "doc://com.apple.xctest/documentation/XCTest/XCTAssertGreaterThanOrEqual",
      "kind": "symbol",
      "role": "symbol",
      "title": "XCTAssertGreaterThanOrEqual",
      "type": "topic",
      "url": "/documentation/xctest/xctassertgreaterthanorequal"
    },
    "doc://com.apple.xctest/documentation/XCTest/XCTAssertGreaterThanOrEqual(_:_:_:file:line:)": {
      "abstract": [
        {
          "text": "Asserts that the value of the first expression is greater than or equal to the value of the second expression.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "XCTAssertGreaterThanOrEqual"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "genericParameter",
          "text": "T"
        },
        {
          "kind": "text",
          "text": ">("
        },
        {
          "kind": "attribute",
          "text": "@autoclosure "
        },
        {
          "kind": "text",
          "text": "() "
        },
        {
          "kind": "keyword",
          "text": "throws"
        },
        {
          "kind": "text",
          "text": " -> "
        },
        {
          "kind": "typeIdentifier",
          "text": "T"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "attribute",
          "text": "@autoclosure "
        },
        {
          "kind": "text",
          "text": "() "
        },
        {
          "kind": "keyword",
          "text": "throws"
        },
        {
          "kind": "text",
          "text": " -> "
        },
        {
          "kind": "typeIdentifier",
          "text": "T"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "attribute",
          "text": "@autoclosure "
        },
        {
          "kind": "text",
          "text": "() -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "file"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s12StaticStringV",
          "text": "StaticString"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "line"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Su",
          "text": "UInt"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.xctest/documentation/XCTest/XCTAssertGreaterThanOrEqual(_:_:_:file:line:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "XCTAssertGreaterThanOrEqual(_:_:_:file:line:)",
      "type": "topic",
      "url": "/documentation/xctest/xctassertgreaterthanorequal(_:_:_:file:line:)"
    },
    "doc://com.apple.xctest/documentation/XCTest/XCTAssertLessThan": {
      "abstract": [
        {
          "text": "Asserts that the value of the first expression is less than the value of the second expression.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "XCTAssertLessThan"
        }
      ],
      "identifier": "doc://com.apple.xctest/documentation/XCTest/XCTAssertLessThan",
      "kind": "symbol",
      "role": "symbol",
      "title": "XCTAssertLessThan",
      "type": "topic",
      "url": "/documentation/xctest/xctassertlessthan"
    },
    "doc://com.apple.xctest/documentation/XCTest/XCTAssertLessThan(_:_:_:file:line:)": {
      "abstract": [
        {
          "text": "Asserts that the value of the first expression is less than the value of the second expression.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "XCTAssertLessThan"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "genericParameter",
          "text": "T"
        },
        {
          "kind": "text",
          "text": ">("
        },
        {
          "kind": "attribute",
          "text": "@autoclosure "
        },
        {
          "kind": "text",
          "text": "() "
        },
        {
          "kind": "keyword",
          "text": "throws"
        },
        {
          "kind": "text",
          "text": " -> "
        },
        {
          "kind": "typeIdentifier",
          "text": "T"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "attribute",
          "text": "@autoclosure "
        },
        {
          "kind": "text",
          "text": "() "
        },
        {
          "kind": "keyword",
          "text": "throws"
        },
        {
          "kind": "text",
          "text": " -> "
        },
        {
          "kind": "typeIdentifier",
          "text": "T"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "attribute",
          "text": "@autoclosure "
        },
        {
          "kind": "text",
          "text": "() -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "file"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s12StaticStringV",
          "text": "StaticString"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "line"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Su",
          "text": "UInt"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.xctest/documentation/XCTest/XCTAssertLessThan(_:_:_:file:line:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "XCTAssertLessThan(_:_:_:file:line:)",
      "type": "topic",
      "url": "/documentation/xctest/xctassertlessthan(_:_:_:file:line:)"
    },
    "doc://com.apple.xctest/documentation/XCTest/XCTAssertLessThanOrEqual": {
      "abstract": [
        {
          "text": "Asserts that the value of the first expression is less than or equal to the value of the second expression.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "XCTAssertLessThanOrEqual"
        }
      ],
      "identifier": "doc://com.apple.xctest/documentation/XCTest/XCTAssertLessThanOrEqual",
      "kind": "symbol",
      "role": "symbol",
      "title": "XCTAssertLessThanOrEqual",
      "type": "topic",
      "url": "/documentation/xctest/xctassertlessthanorequal"
    },
    "doc://com.apple.xctest/documentation/XCTest/XCTAssertLessThanOrEqual(_:_:_:file:line:)": {
      "abstract": [
        {
          "text": "Asserts that the value of the first expression is less than or equal to the value of the second expression.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "XCTAssertLessThanOrEqual"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "genericParameter",
          "text": "T"
        },
        {
          "kind": "text",
          "text": ">("
        },
        {
          "kind": "attribute",
          "text": "@autoclosure "
        },
        {
          "kind": "text",
          "text": "() "
        },
        {
          "kind": "keyword",
          "text": "throws"
        },
        {
          "kind": "text",
          "text": " -> "
        },
        {
          "kind": "typeIdentifier",
          "text": "T"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "attribute",
          "text": "@autoclosure "
        },
        {
          "kind": "text",
          "text": "() "
        },
        {
          "kind": "keyword",
          "text": "throws"
        },
        {
          "kind": "text",
          "text": " -> "
        },
        {
          "kind": "typeIdentifier",
          "text": "T"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "attribute",
          "text": "@autoclosure "
        },
        {
          "kind": "text",
          "text": "() -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "file"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s12StaticStringV",
          "text": "StaticString"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "line"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Su",
          "text": "UInt"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.xctest/documentation/XCTest/XCTAssertLessThanOrEqual(_:_:_:file:line:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "XCTAssertLessThanOrEqual(_:_:_:file:line:)",
      "type": "topic",
      "url": "/documentation/xctest/xctassertlessthanorequal(_:_:_:file:line:)"
    },
    "doc://com.apple.xctest/documentation/XCTest/boolean-assertions": {
      "abstract": [
        {
          "text": "Test a condition that generates a true or false result.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.xctest/documentation/XCTest/boolean-assertions",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Boolean Assertions",
      "type": "topic",
      "url": "/documentation/xctest/boolean-assertions"
    },
    "doc://com.apple.xctest/documentation/XCTest/equality-and-inequality-assertions": {
      "abstract": [
        {
          "text": "Check whether two values are equal or unequal.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.xctest/documentation/XCTest/equality-and-inequality-assertions",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Equality and Inequality Assertions",
      "type": "topic",
      "url": "/documentation/xctest/equality-and-inequality-assertions"
    },
    "doc://com.apple.xctest/documentation/XCTest/error-assertions": {
      "abstract": [
        {
          "text": "Check whether a function call throws, or doesn’t throw, an error.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.xctest/documentation/XCTest/error-assertions",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Error Assertions",
      "type": "topic",
      "url": "/documentation/xctest/error-assertions"
    },
    "doc://com.apple.xctest/documentation/XCTest/expected-failures": {
      "abstract": [
        {
          "text": "Anticipate known test failures to prevent failing tests from affecting your workflows.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.xctest/documentation/XCTest/expected-failures",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Expected Failures",
      "type": "topic",
      "url": "/documentation/xctest/expected-failures"
    },
    "doc://com.apple.xctest/documentation/XCTest/methods-for-skipping-tests": {
      "abstract": [
        {
          "text": "Skip tests when meeting specified conditions.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.xctest/documentation/XCTest/methods-for-skipping-tests",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Methods for Skipping Tests",
      "type": "topic",
      "url": "/documentation/xctest/methods-for-skipping-tests"
    },
    "doc://com.apple.xctest/documentation/XCTest/nil-and-non-nil-assertions": {
      "abstract": [
        {
          "text": "Check whether a test condition has, or doesn’t have, a value.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.xctest/documentation/XCTest/nil-and-non-nil-assertions",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Nil and Non-Nil Assertions",
      "type": "topic",
      "url": "/documentation/xctest/nil-and-non-nil-assertions"
    },
    "doc://com.apple.xctest/documentation/XCTest/nsexception-assertions": {
      "abstract": [
        {
          "text": "Check whether a function call throws, or doesn’t throw, an exception.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.xctest/documentation/XCTest/nsexception-assertions",
      "kind": "article",
      "role": "collectionGroup",
      "title": "NSException Assertions",
      "type": "topic",
      "url": "/documentation/xctest/nsexception-assertions"
    },
    "doc://com.apple.xctest/documentation/XCTest/unconditional-test-failures": {
      "abstract": [
        {
          "text": "Generate a failure immediately and unconditionally.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.xctest/documentation/XCTest/unconditional-test-failures",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Unconditional Test Failures",
      "type": "topic",
      "url": "/documentation/xctest/unconditional-test-failures"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Test-assertions",
      "generated": true,
      "identifiers": [
        "doc://com.apple.xctest/documentation/XCTest/boolean-assertions",
        "doc://com.apple.xctest/documentation/XCTest/nil-and-non-nil-assertions",
        "doc://com.apple.xctest/documentation/XCTest/equality-and-inequality-assertions",
        "doc://com.apple.xctest/documentation/XCTest/error-assertions",
        "doc://com.apple.xctest/documentation/XCTest/nsexception-assertions",
        "doc://com.apple.xctest/documentation/XCTest/unconditional-test-failures",
        "doc://com.apple.xctest/documentation/XCTest/expected-failures",
        "doc://com.apple.xctest/documentation/XCTest/methods-for-skipping-tests"
      ],
      "title": "Test assertions"
    }
  ],
  "topicSections": [
    {
      "anchor": "Tests-for-Comparable-Values",
      "identifiers": [
        "doc://com.apple.xctest/documentation/XCTest/XCTAssertGreaterThan(_:_:_:file:line:)",
        "doc://com.apple.xctest/documentation/XCTest/XCTAssertGreaterThanOrEqual(_:_:_:file:line:)",
        "doc://com.apple.xctest/documentation/XCTest/XCTAssertLessThanOrEqual(_:_:_:file:line:)",
        "doc://com.apple.xctest/documentation/XCTest/XCTAssertLessThan(_:_:_:file:line:)"
      ],
      "title": "Tests for Comparable Values"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Tests-for-Comparable-Values",
              "identifiers": [
                "doc://com.apple.xctest/documentation/XCTest/XCTAssertGreaterThan",
                "doc://com.apple.xctest/documentation/XCTest/XCTAssertGreaterThanOrEqual",
                "doc://com.apple.xctest/documentation/XCTest/XCTAssertLessThanOrEqual",
                "doc://com.apple.xctest/documentation/XCTest/XCTAssertLessThan"
              ],
              "title": "Tests for Comparable Values"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Test-assertions",
              "generated": true,
              "identifiers": [
                "doc://com.apple.xctest/documentation/XCTest/boolean-assertions",
                "doc://com.apple.xctest/documentation/XCTest/nil-and-non-nil-assertions",
                "doc://com.apple.xctest/documentation/XCTest/equality-and-inequality-assertions",
                "doc://com.apple.xctest/documentation/XCTest/error-assertions",
                "doc://com.apple.xctest/documentation/XCTest/nsexception-assertions",
                "doc://com.apple.xctest/documentation/XCTest/unconditional-test-failures",
                "doc://com.apple.xctest/documentation/XCTest/expected-failures",
                "doc://com.apple.xctest/documentation/XCTest/methods-for-skipping-tests"
              ],
              "title": "Test assertions"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/xctest/comparable-value-assertions"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/xctest/comparable-value-assertions"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
