{
  "abstract": [
    {
      "text": "Add test cases and test methods to a test target to confirm that your code performs as expected.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.xctest/documentation/XCTest"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.xctest/documentation/XCTest/defining-test-cases-and-test-methods"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "XCTest"
      }
    ],
    "role": "article",
    "roleHeading": "Article",
    "title": "Defining Test Cases and Test Methods"
  },
  "primaryContentSections": [
    {
      "content": [
        {
          "anchor": "overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Add tests to your Xcode project by writing one or more test methods, each of which verifies a specific aspect of your code. Group related test methods into test cases, each of which is a subclass of ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.xctest/documentation/XCTest/XCTestCase",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ".",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "To add tests to your project:",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "items": [
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Create a new subclass of ",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.xctest/documentation/XCTest/XCTestCase",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": " within a test target.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Add one or more test methods to the test case.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Add one or more test assertions to each test method.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            }
          ],
          "type": "unorderedList"
        },
        {
          "inlineContent": [
            {
              "text": "A test method is an instance method on an ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.xctest/documentation/XCTest/XCTestCase",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " subclass, with no parameters, no return value, and a name that begins with the lowercase word ",
              "type": "text"
            },
            {
              "inlineContent": [
                {
                  "text": "test",
                  "type": "text"
                }
              ],
              "type": "emphasis"
            },
            {
              "text": ". Test methods are automatically detected by the XCTest framework in Xcode.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "Listing 1. Example test case and test method",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "tabs": [
            {
              "content": [
                {
                  "code": [
                    "class TableValidationTests: XCTestCase {",
                    "    /// Tests that a new table instance has zero rows and columns.",
                    "    func testEmptyTableRowAndColumnCount() {",
                    "        let table = Table()",
                    "        XCTAssertEqual(table.rowCount, 0, \"Row count was not zero.\")",
                    "        XCTAssertEqual(table.columnCount, 0, \"Column count was not zero.\")",
                    "    }",
                    "}"
                  ],
                  "syntax": "swift",
                  "type": "codeListing"
                }
              ],
              "title": "Swift"
            },
            {
              "content": [
                {
                  "code": [
                    "@interface TableValidationTests: XCTestCase",
                    "@end",
                    "@implementation TableValidationTests",
                    "/// Tests that a new table instance has zero rows and columns.",
                    "- (void)testEmptyTableRowAndColumnCount {",
                    "    Table *table = [[Table alloc] init];",
                    "    XCTAssertEqual(table.rowCount, 0, \"Row count was not zero.\");",
                    "    XCTAssertEqual(table.columnCount, 0, \"Column count was not zero.\");",
                    "}",
                    "@end"
                  ],
                  "syntax": "objc",
                  "type": "codeListing"
                }
              ],
              "title": "Objective-C"
            }
          ],
          "type": "tabNavigator"
        },
        {
          "inlineContent": [
            {
              "text": "This example defines an ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.xctest/documentation/XCTest/XCTestCase",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " subclass, ",
              "type": "text"
            },
            {
              "code": "TableValidationTests",
              "type": "codeVoice"
            },
            {
              "text": ", with a single test method, ",
              "type": "text"
            },
            {
              "code": "testEmptyTableRowAndColumnCount()",
              "type": "codeVoice"
            },
            {
              "text": ". This test method creates a new instance of a class called ",
              "type": "text"
            },
            {
              "code": "Table",
              "type": "codeVoice"
            },
            {
              "text": ", and checks that its ",
              "type": "text"
            },
            {
              "code": "rowCount",
              "type": "codeVoice"
            },
            {
              "text": " and ",
              "type": "text"
            },
            {
              "code": "columnCount",
              "type": "codeVoice"
            },
            {
              "text": " properties are both equal to 0 after initialization.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "",
                  "type": "text"
                },
                {
                  "text": " ",
                  "type": "text"
                },
                {
                  "text": "Test case and test method names are used in Xcode’s test navigator and integration reports to group and identify tests.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            },
            {
              "inlineContent": [
                {
                  "text": "To help clarify the organization of your tests, give each test case a name that summarizes the tests within it, such as ",
                  "type": "text"
                },
                {
                  "code": "TableValidationTests",
                  "type": "codeVoice"
                },
                {
                  "text": ", ",
                  "type": "text"
                },
                {
                  "code": "NetworkReachabilityTests",
                  "type": "codeVoice"
                },
                {
                  "text": ", or ",
                  "type": "text"
                },
                {
                  "code": "JSONParsingTests",
                  "type": "codeVoice"
                },
                {
                  "text": ".",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            },
            {
              "inlineContent": [
                {
                  "text": "To help identify failing tests, give each test method a name that makes it clear what is tested by that method, such as ",
                  "type": "text"
                },
                {
                  "code": "testEmptyTableRowAndColumnCount()",
                  "type": "codeVoice"
                },
                {
                  "text": ", ",
                  "type": "text"
                },
                {
                  "code": "testUnreachableURLAccessThrowsAnError()",
                  "type": "codeVoice"
                },
                {
                  "text": ", or ",
                  "type": "text"
                },
                {
                  "code": "testUserJSONFeedParsing()",
                  "type": "codeVoice"
                },
                {
                  "text": ".",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "Tip",
          "style": "tip",
          "type": "aside"
        },
        {
          "anchor": "Asserting-Test-Conditions",
          "level": 3,
          "text": "Asserting Test Conditions",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "You can check (or ",
              "type": "text"
            },
            {
              "inlineContent": [
                {
                  "text": "assert",
                  "type": "text"
                }
              ],
              "type": "emphasis"
            },
            {
              "text": ") conditions inside test methods to make sure that your code is behaving as expected. Use the ",
              "type": "text"
            },
            {
              "code": "XCTAssert",
              "type": "codeVoice"
            },
            {
              "text": " family of functions to check for Boolean conditions, ",
              "type": "text"
            },
            {
              "code": "nil",
              "type": "codeVoice"
            },
            {
              "text": " or non-",
              "type": "text"
            },
            {
              "code": "nil",
              "type": "codeVoice"
            },
            {
              "text": " values, expected values, errors, or thrown exceptions.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "For example, Listing 1 above uses the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.xctest/documentation/XCTest/XCTAssertEqual",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " macro to assert that two integers have the same value.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.xctest/documentation/XCTest": {
      "abstract": [
        {
          "text": "Create and run unit tests, performance tests, and UI tests for your Xcode project.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.xctest/documentation/XCTest",
      "kind": "symbol",
      "role": "collection",
      "title": "XCTest",
      "type": "topic",
      "url": "/documentation/xctest"
    },
    "doc://com.apple.xctest/documentation/XCTest/XCTAssertEqual": {
      "abstract": [
        {
          "text": "Asserts that two expressions have the same value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "XCTAssertEqual"
        }
      ],
      "identifier": "doc://com.apple.xctest/documentation/XCTest/XCTAssertEqual",
      "kind": "symbol",
      "role": "symbol",
      "title": "XCTAssertEqual",
      "type": "topic",
      "url": "/documentation/xctest/xctassertequal"
    },
    "doc://com.apple.xctest/documentation/XCTest/XCTest": {
      "abstract": [
        {
          "text": "An abstract base class for creating, managing, and executing tests.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "XCTest"
        }
      ],
      "identifier": "doc://com.apple.xctest/documentation/XCTest/XCTest",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "XCTest"
        }
      ],
      "role": "symbol",
      "title": "XCTest",
      "type": "topic",
      "url": "/documentation/xctest/xctest"
    },
    "doc://com.apple.xctest/documentation/XCTest/XCTestCase": {
      "abstract": [
        {
          "text": "The primary class for defining test cases, test methods, and performance tests.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "XCTestCase"
        }
      ],
      "identifier": "doc://com.apple.xctest/documentation/XCTest/XCTestCase",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "XCTestCase"
        }
      ],
      "role": "symbol",
      "title": "XCTestCase",
      "type": "topic",
      "url": "/documentation/xctest/xctestcase"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Test-cases-and-test-methods",
      "generated": true,
      "identifiers": [
        "doc://com.apple.xctest/documentation/XCTest/XCTestCase",
        "doc://com.apple.xctest/documentation/XCTest/XCTest"
      ],
      "title": "Test cases and test methods"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Test-cases-and-test-methods",
              "generated": true,
              "identifiers": [
                "doc://com.apple.xctest/documentation/XCTest/XCTestCase",
                "doc://com.apple.xctest/documentation/XCTest/XCTest"
              ],
              "title": "Test cases and test methods"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCTestCase/title",
          "value": "XCTestCase"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCTestCase/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "XCTestCase"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCTestCase/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "XCTestCase"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCTest/title",
          "value": "XCTest"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCTest/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "XCTest"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCTest/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "XCTest"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/xctest/defining-test-cases-and-test-methods"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/xctest/defining-test-cases-and-test-methods"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
