{
  "abstract": [
    {
      "text": "These symbols are deprecated and are no longer recommended.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.xctest/documentation/XCTest"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.xctest/documentation/XCTest/deprecated-symbols"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "XCTest"
      }
    ],
    "role": "collectionGroup",
    "roleHeading": "API Collection",
    "title": "Deprecated Symbols"
  },
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.xctest/documentation/XCTest": {
      "abstract": [
        {
          "text": "Create and run unit tests, performance tests, and UI tests for your Xcode project.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.xctest/documentation/XCTest",
      "kind": "symbol",
      "role": "collection",
      "title": "XCTest",
      "type": "topic",
      "url": "/documentation/xctest"
    },
    "doc://com.apple.xctest/documentation/XCTest/XCTAssertEqualWithAccuracy(_:_:accuracy:_:file:line:)": {
      "abstract": [
        {
          "text": "Asserts that two values are equal within a certain accuracy.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "XCTAssertEqualWithAccuracy"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "genericParameter",
          "text": "T"
        },
        {
          "kind": "text",
          "text": ">("
        },
        {
          "kind": "attribute",
          "text": "@autoclosure "
        },
        {
          "kind": "text",
          "text": "() "
        },
        {
          "kind": "keyword",
          "text": "throws"
        },
        {
          "kind": "text",
          "text": " -> "
        },
        {
          "kind": "typeIdentifier",
          "text": "T"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "attribute",
          "text": "@autoclosure "
        },
        {
          "kind": "text",
          "text": "() "
        },
        {
          "kind": "keyword",
          "text": "throws"
        },
        {
          "kind": "text",
          "text": " -> "
        },
        {
          "kind": "typeIdentifier",
          "text": "T"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "accuracy"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "text": "T"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "attribute",
          "text": "@autoclosure "
        },
        {
          "kind": "text",
          "text": "() -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "file"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s12StaticStringV",
          "text": "StaticString"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "line"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Su",
          "text": "UInt"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.xctest/documentation/XCTest/XCTAssertEqualWithAccuracy(_:_:accuracy:_:file:line:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "XCTAssertEqualWithAccuracy(_:_:accuracy:_:file:line:)",
      "type": "topic",
      "url": "/documentation/xctest/xctassertequalwithaccuracy(_:_:accuracy:_:file:line:)"
    },
    "doc://com.apple.xctest/documentation/XCTest/XCTAssertNotEqualWithAccuracy(_:_:_:_:file:line:)": {
      "abstract": [
        {
          "text": "Asserts that two values are not equal within a certain accuracy.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "XCTAssertNotEqualWithAccuracy"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "genericParameter",
          "text": "T"
        },
        {
          "kind": "text",
          "text": ">("
        },
        {
          "kind": "attribute",
          "text": "@autoclosure "
        },
        {
          "kind": "text",
          "text": "() "
        },
        {
          "kind": "keyword",
          "text": "throws"
        },
        {
          "kind": "text",
          "text": " -> "
        },
        {
          "kind": "typeIdentifier",
          "text": "T"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "attribute",
          "text": "@autoclosure "
        },
        {
          "kind": "text",
          "text": "() "
        },
        {
          "kind": "keyword",
          "text": "throws"
        },
        {
          "kind": "text",
          "text": " -> "
        },
        {
          "kind": "typeIdentifier",
          "text": "T"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "text": "T"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "attribute",
          "text": "@autoclosure "
        },
        {
          "kind": "text",
          "text": "() -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "file"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s12StaticStringV",
          "text": "StaticString"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "line"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Su",
          "text": "UInt"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.xctest/documentation/XCTest/XCTAssertNotEqualWithAccuracy(_:_:_:_:file:line:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "XCTAssertNotEqualWithAccuracy(_:_:_:_:file:line:)",
      "type": "topic",
      "url": "/documentation/xctest/xctassertnotequalwithaccuracy(_:_:_:_:file:line:)"
    },
    "doc://com.apple.xctest/documentation/XCTest/XCTSelfTestMain()": {
      "abstract": [],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "XCTSelfTestMain"
        },
        {
          "kind": "text",
          "text": "() -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int32V",
          "text": "Int32"
        }
      ],
      "identifier": "doc://com.apple.xctest/documentation/XCTest/XCTSelfTestMain()",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "XCTSelfTestMain"
        }
      ],
      "role": "symbol",
      "title": "XCTSelfTestMain()",
      "type": "topic",
      "url": "/documentation/xctest/xctselftestmain()"
    },
    "doc://com.apple.xctest/documentation/XCTest/XCTestLog": {
      "abstract": [
        {
          "text": "An object that logs test failures and errors.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "XCTestLog"
        }
      ],
      "identifier": "doc://com.apple.xctest/documentation/XCTest/XCTestLog",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "XCTestLog"
        }
      ],
      "role": "symbol",
      "title": "XCTestLog",
      "type": "topic",
      "url": "/documentation/xctest/xctestlog"
    },
    "doc://com.apple.xctest/documentation/XCTest/XCTestObserver": {
      "abstract": [
        {
          "text": "An object that observes test activity and events.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "XCTestObserver"
        }
      ],
      "identifier": "doc://com.apple.xctest/documentation/XCTest/XCTestObserver",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "XCTestObserver"
        }
      ],
      "role": "symbol",
      "title": "XCTestObserver",
      "type": "topic",
      "url": "/documentation/xctest/xctestobserver"
    },
    "doc://com.apple.xctest/documentation/XCTest/XCTestObserverClassKey": {
      "abstract": [],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "XCTestObserverClassKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.xctest/documentation/XCTest/XCTestObserverClassKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "XCTestObserverClassKey"
        }
      ],
      "role": "symbol",
      "title": "XCTestObserverClassKey",
      "type": "topic",
      "url": "/documentation/xctest/xctestobserverclasskey"
    },
    "doc://com.apple.xctest/documentation/XCTest/XCTestProbe": {
      "abstract": [
        {
          "text": "An object that observes test activity status.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "XCTestProbe"
        }
      ],
      "identifier": "doc://com.apple.xctest/documentation/XCTest/XCTestProbe",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "XCTestProbe"
        }
      ],
      "role": "symbol",
      "title": "XCTestProbe",
      "type": "topic",
      "url": "/documentation/xctest/xctestprobe"
    },
    "doc://com.apple.xctest/documentation/XCTest/XCTestScopeAll": {
      "abstract": [],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "XCTestScopeAll"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.xctest/documentation/XCTest/XCTestScopeAll",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "XCTestScopeAll"
        }
      ],
      "role": "symbol",
      "title": "XCTestScopeAll",
      "type": "topic",
      "url": "/documentation/xctest/xctestscopeall"
    },
    "doc://com.apple.xctest/documentation/XCTest/XCTestScopeKey": {
      "abstract": [],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "XCTestScopeKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.xctest/documentation/XCTest/XCTestScopeKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "XCTestScopeKey"
        }
      ],
      "role": "symbol",
      "title": "XCTestScopeKey",
      "type": "topic",
      "url": "/documentation/xctest/xctestscopekey"
    },
    "doc://com.apple.xctest/documentation/XCTest/XCTestScopeNone": {
      "abstract": [],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "XCTestScopeNone"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.xctest/documentation/XCTest/XCTestScopeNone",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "XCTestScopeNone"
        }
      ],
      "role": "symbol",
      "title": "XCTestScopeNone",
      "type": "topic",
      "url": "/documentation/xctest/xctestscopenone"
    },
    "doc://com.apple.xctest/documentation/XCTest/XCTestScopeSelf": {
      "abstract": [],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "XCTestScopeSelf"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.xctest/documentation/XCTest/XCTestScopeSelf",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "XCTestScopeSelf"
        }
      ],
      "role": "symbol",
      "title": "XCTestScopeSelf",
      "type": "topic",
      "url": "/documentation/xctest/xctestscopeself"
    },
    "doc://com.apple.xctest/documentation/XCTest/XCTestToolKey": {
      "abstract": [],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "XCTestToolKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.xctest/documentation/XCTest/XCTestToolKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "XCTestToolKey"
        }
      ],
      "role": "symbol",
      "title": "XCTestToolKey",
      "type": "topic",
      "url": "/documentation/xctest/xctesttoolkey"
    },
    "doc://com.apple.xctest/documentation/XCTest/XCTestedUnitPath": {
      "abstract": [],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "XCTestedUnitPath"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.xctest/documentation/XCTest/XCTestedUnitPath",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "XCTestedUnitPath"
        }
      ],
      "role": "symbol",
      "title": "XCTestedUnitPath",
      "type": "topic",
      "url": "/documentation/xctest/xctestedunitpath"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "topicSections": [
    {
      "anchor": "Deprecated-Classes",
      "identifiers": [
        "doc://com.apple.xctest/documentation/XCTest/XCTestLog",
        "doc://com.apple.xctest/documentation/XCTest/XCTestObserver",
        "doc://com.apple.xctest/documentation/XCTest/XCTestProbe"
      ],
      "title": "Deprecated Classes"
    },
    {
      "anchor": "Deprecated-Functions",
      "identifiers": [
        "doc://com.apple.xctest/documentation/XCTest/XCTSelfTestMain()",
        "doc://com.apple.xctest/documentation/XCTest/XCTAssertEqualWithAccuracy(_:_:accuracy:_:file:line:)",
        "doc://com.apple.xctest/documentation/XCTest/XCTAssertNotEqualWithAccuracy(_:_:_:_:file:line:)"
      ],
      "title": "Deprecated Functions"
    },
    {
      "anchor": "Deprecated-Constants",
      "identifiers": [
        "doc://com.apple.xctest/documentation/XCTest/XCTestObserverClassKey",
        "doc://com.apple.xctest/documentation/XCTest/XCTestedUnitPath",
        "doc://com.apple.xctest/documentation/XCTest/XCTestScopeNone",
        "doc://com.apple.xctest/documentation/XCTest/XCTestScopeAll",
        "doc://com.apple.xctest/documentation/XCTest/XCTestScopeKey",
        "doc://com.apple.xctest/documentation/XCTest/XCTestScopeSelf",
        "doc://com.apple.xctest/documentation/XCTest/XCTestToolKey"
      ],
      "title": "Deprecated Constants"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Deprecated-Classes",
              "identifiers": [
                "doc://com.apple.xctest/documentation/XCTest/XCTestLog",
                "doc://com.apple.xctest/documentation/XCTest/XCTestObserver",
                "doc://com.apple.xctest/documentation/XCTest/XCTestProbe"
              ],
              "title": "Deprecated Classes"
            },
            {
              "anchor": "Deprecated-Functions",
              "identifiers": [
                "doc://com.apple.xctest/documentation/XCTest/XCTSelfTestMain()"
              ],
              "title": "Deprecated Functions"
            },
            {
              "anchor": "Deprecated-Constants",
              "identifiers": [
                "doc://com.apple.xctest/documentation/XCTest/XCTestObserverClassKey",
                "doc://com.apple.xctest/documentation/XCTest/XCTestedUnitPath",
                "doc://com.apple.xctest/documentation/XCTest/XCTestScopeNone",
                "doc://com.apple.xctest/documentation/XCTest/XCTestScopeAll",
                "doc://com.apple.xctest/documentation/XCTest/XCTestScopeKey",
                "doc://com.apple.xctest/documentation/XCTest/XCTestScopeSelf",
                "doc://com.apple.xctest/documentation/XCTest/XCTestToolKey"
              ],
              "title": "Deprecated Constants"
            }
          ]
        },
        {
          "op": "add",
          "path": "/seeAlsoSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCTestScopeAll/title",
          "value": "XCTestScopeAll"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCTestScopeAll/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "XCTestScopeAll"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCTestObserver/title",
          "value": "XCTestObserver"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCTestObserver/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "XCTestObserver"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCTestObserver/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "XCTestObserver"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCTestScopeNone/title",
          "value": "XCTestScopeNone"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCTestScopeNone/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "XCTestScopeNone"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCTestProbe/title",
          "value": "XCTestProbe"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCTestProbe/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "XCTestProbe"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCTestProbe/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "XCTestProbe"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCTestedUnitPath/title",
          "value": "XCTestedUnitPath"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCTestedUnitPath/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "XCTestedUnitPath"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCTestObserverClassKey/title",
          "value": "XCTestObserverClassKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCTestObserverClassKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "XCTestObserverClassKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCTestScopeSelf/title",
          "value": "XCTestScopeSelf"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCTestScopeSelf/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "XCTestScopeSelf"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCTestScopeKey/title",
          "value": "XCTestScopeKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCTestScopeKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "XCTestScopeKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCTSelfTestMain()/title",
          "value": "XCTSelfTestMain"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCTSelfTestMain()/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "XCTSelfTestMain"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCTestToolKey/title",
          "value": "XCTestToolKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCTestToolKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "XCTestToolKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCTestLog/title",
          "value": "XCTestLog"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCTestLog/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "XCTestLog"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCTestLog/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "XCTestLog"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/xctest/deprecated-symbols"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/xctest/deprecated-symbols"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
