{
  "abstract": [
    {
      "text": "Simplify test reports by creating activities that organize substeps within complex test methods.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.xctest/documentation/XCTest",
        "doc://com.apple.xctest/documentation/XCTest/activities-and-attachments"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.xctest/documentation/XCTest/grouping-tests-into-substeps-with-activities"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "XCTest"
      }
    ],
    "role": "article",
    "roleHeading": "Article",
    "title": "Grouping Tests into Substeps with Activities"
  },
  "primaryContentSections": [
    {
      "content": [
        {
          "anchor": "overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Use activities to break longer test methods, such as UI tests and integration tests, into smaller named substeps.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "Each activity wraps a block of code, giving the code a name. You can nest and call activities within other activities. Xcode test reports organize results by activity name, making test reports for complex, multistep tests easier to understand.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "For long test methods, especially in UI tests that contain lots of steps, simplify your test methods by refactoring them into utility methods or substeps with activities.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "anchor": "Organize-Long-Test-Methods-into-Substeps",
          "level": 3,
          "text": "Organize Long Test Methods into Substeps",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Identify the substeps that you want to group into named activities. For example, you might break down a login UI test into three substeps: opening the login window, entering a password, and closing the login window. Then, create named activities for each substep you identify.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "tabs": [
            {
              "content": [
                {
                  "code": [
                    "func testLogin() throws {",
                    "    openLoginWindow()",
                    "    enterPassword(for: .member)",
                    "    closeLoginWindow()",
                    "}",
                    "",
                    "func openLoginWindow() {",
                    "    XCTContext.runActivity(named: \"Open login window\") { activity in",
                    "        let loginButton = app.buttons[\"Login\"]",
                    "        ",
                    "        XCTAssertTrue(loginButton.exists, \"Login button is missing.\")",
                    "        XCTAssertTrue(loginButton.isHittable, \"Login button is not hittable.\")",
                    "        XCTAssertFalse(app.staticTexts[\"Logged In\"].exists, \"Logged In label is visible and should not be.\")",
                    "",
                    "        loginButton.tap()",
                    "        ",
                    "        let loginLabel = app.staticTexts[\"Login:\"]",
                    "        XCTAssertTrue(loginLabel.waitForExistence(timeout: 3.0), \"Login label is missing.\")",
                    "    }",
                    "}",
                    "",
                    "func enterPassword(for userType: TestUserType) {",
                    "    XCTContext.runActivity(named: \"Enter password\") { activity in",
                    "        let userNameTextField = app.textFields[\"user name\"]",
                    "        userNameTextField.tap()",
                    "        userNameTextField.typeText(userType.userName)",
                    "",
                    "        let passwordSecureTextField = app.secureTextFields[\"password\"]",
                    "        passwordSecureTextField.tap()",
                    "        passwordSecureTextField.typeText(userType.password)",
                    "        ",
                    "        // Dismiss keyboard.",
                    "        app.children(matching: .window).firstMatch.tap()",
                    "    }",
                    "}",
                    "",
                    "func closeLoginWindow() {",
                    "    XCTContext.runActivity(named: \"Close login window\") { activity in",
                    "        let submitLoginButton = app.buttons[\"Submit\"]",
                    "        XCTAssertTrue(submitLoginButton.exists, \"Submit button is missing.\")",
                    "        XCTAssertTrue(submitLoginButton.isHittable, \"Submit button is not hittable.\")",
                    "        submitLoginButton.tap()",
                    "        XCTAssertTrue(app.staticTexts[\"Logged In\"].waitForExistence(timeout: 3.0), \"Logged In label is missing.\")",
                    "    }",
                    "}",
                    ""
                  ],
                  "syntax": "swift",
                  "type": "codeListing"
                }
              ],
              "title": "Swift"
            },
            {
              "content": [
                {
                  "code": [
                    "- (void)testLogin {",
                    "    [self openLoginWindow];",
                    "    [self enterPasswordAndUserName:@\"member\"];",
                    "    [self closeLoginWindow];",
                    "}",
                    "",
                    "- (void)openLoginWindow {",
                    "    [XCTContext runActivityNamed:@\"Open login window\" block:^(id<XCTActivity> activity) {",
                    "        XCUIElement *loginButton = self.app.buttons[@\"Login\"];",
                    "        XCTAssertTrue(loginButton.exists, @\"Login button is missing.\");",
                    "        XCTAssertTrue(loginButton.isHittable, @\"Login button is not hittable.\");",
                    "        XCTAssertFalse(self.app.staticTexts[@\"Logged In\"].exists, @\"Logged In label is visible and should not be.\");",
                    "        [loginButton tap];",
                    "        ",
                    "        XCUIElement *loginLabel = self.app.staticTexts[@\"Login:\"];",
                    "        BOOL loginLabelAppeared = [loginLabel waitForExistenceWithTimeout:3.0];",
                    "        XCTAssertTrue(loginLabelAppeared, @\"Login label is missing.\");",
                    "    }];",
                    "}",
                    "",
                    "- (void)enterPasswordAndUserName:(NSString *)userName {",
                    "    [XCTContext runActivityNamed:@\"Enter password\" block:^(id<XCTActivity> activity) {",
                    "        XCUIElement *userNameTextField = self.app.textFields[@\"user name\"];",
                    "        [userNameTextField tap];",
                    "        [userNameTextField typeText:userName];",
                    "        ",
                    "        XCUIElement *passwordSecureTextField = self.app.secureTextFields[@\"password\"];",
                    "        [passwordSecureTextField tap];",
                    "        [passwordSecureTextField typeText:@\"password\"];",
                    "        ",
                    "        //Dismiss keyboard.",
                    "        [[[self.app childrenMatchingType:XCUIElementTypeWindow] firstMatch] tap];",
                    "    }];",
                    "}",
                    "",
                    "- (void)closeLoginWindow {",
                    "    [XCTContext runActivityNamed:@\"Close login window\" block:^(id<XCTActivity> activity) {",
                    "        XCUIElement *submitLoginButton = self.app.buttons[@\"Submit\"];",
                    "        XCTAssertTrue(submitLoginButton.exists, @\"Submit button is missing.\");",
                    "        XCTAssertTrue(submitLoginButton.isHittable, @\"Submit button is not hittable.\");",
                    "        [submitLoginButton tap];",
                    "",
                    "        BOOL loggedInLabelAppeared = [self.app.staticTexts[@\"Logged In\"] waitForExistenceWithTimeout:3.0];",
                    "        XCTAssertTrue(loggedInLabelAppeared, @\"Logged In label is missing.\");",
                    "    }];",
                    "}",
                    ""
                  ],
                  "syntax": "objc",
                  "type": "codeListing"
                }
              ],
              "title": "Objective-C"
            }
          ],
          "type": "tabNavigator"
        },
        {
          "inlineContent": [
            {
              "text": "Activities run against the current testing context, represented by ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.xctest/documentation/XCTest/XCTContext",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ". To run a block of code as an activity, call the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.xctest/documentation/XCTest/XCTContext/runActivityNamed:block:",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " class method on ",
              "type": "text"
            },
            {
              "code": "XCTContext",
              "type": "codeVoice"
            },
            {
              "text": ", passing your test code as the block to execute.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "anchor": "Build-Utility-Methods-from-Common-Test-Substeps",
          "level": 3,
          "text": "Build Utility Methods from Common Test Substeps",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Convert common test substeps into self-contained utility methods for reuse in multiple tests with activities. For example, if you have three UI tests that each require the user to be logged in, extract the login process into a utility method that wraps the process inside an activity called ",
              "type": "text"
            },
            {
              "code": "Login",
              "type": "codeVoice"
            },
            {
              "text": ", and call the utility method from within each test method. The login activity appears in the Xcode test report for each test method that calls it.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "tabs": [
            {
              "content": [
                {
                  "code": [
                    "func testAdminLoginFeatures() throws {",
                    "    let loginResult = login(for: .admin)",
                    "    try XCTAssertTrue(loginResult.get() == .admin)",
                    "    ",
                    "    XCTAssertTrue(app.buttons[\"Admin Features\"].exists, \"Missing Admin Features button.\")",
                    "    XCTAssertFalse(app.buttons[\"Member Features\"].exists, \"Member Features button is visible and should not be.\")",
                    "}",
                    "",
                    "func testMemberLoginFeatures() throws {",
                    "    let loginResult = login(for: .member)",
                    "    try XCTAssertTrue(loginResult.get() == .member)",
                    "    ",
                    "    XCTAssertFalse(app.buttons[\"Admin Features\"].exists, \"Admin Features button is visible and should not be.\")",
                    "    XCTAssertTrue(app.buttons[\"Member Features\"].exists, \"Missing Member Features button.\")",
                    "}",
                    "",
                    "func testGuestLoginFeatures() throws {",
                    "    let loginResult = login(for: .guest)",
                    "    ",
                    "    switch loginResult {",
                    "    case .success:",
                    "        XCTAssertFalse(app.buttons[\"Admin Features\"].exists, \"Admin Features button is visible and should not be.\")",
                    "        XCTAssertFalse(app.buttons[\"Member Features\"].exists, \"Member Features button is visible and should not be.\")",
                    "    case .failure(let error):",
                    "        throw XCTSkip(\"Guest logins are still not working, skip this test. Error was: \\(error)\")",
                    "    }",
                    "}",
                    "",
                    "func login(for userType: TestUserType) -> Result<TestUserType, Error> {",
                    "    return XCTContext.runActivity(named: \"Login\") { activity in",
                    "        performLoginUITests(for: userType)",
                    "        ",
                    "        guard app.staticTexts[\"Logged In\"].exists else {",
                    "            let screenshot = app.windows.firstMatch.screenshot()",
                    "            let attachment = XCTAttachment(screenshot: screenshot)",
                    "            attachment.lifetime = .keepAlways",
                    "            activity.add(attachment)",
                    "            return .failure(TestLoginError.invalidLogin)",
                    "        }",
                    "        return .success(userType)",
                    "    }",
                    "}",
                    ""
                  ],
                  "syntax": "swift",
                  "type": "codeListing"
                }
              ],
              "title": "Swift"
            },
            {
              "content": [
                {
                  "code": [
                    "- (void)testAdminLoginFeatures {",
                    "    BOOL loginResult = [self loginForUserName:@\"admin\"];",
                    "    XCTAssertTrue(loginResult);",
                    "    ",
                    "    XCTAssertTrue(self.app.buttons[@\"Admin Features\"].exists, @\"Missing Admin Features button.\");",
                    "    XCTAssertFalse(self.app.buttons[@\"Member Features\"].exists, @\"Member Features button is visible and should not be.\");",
                    "}",
                    "",
                    "- (void)testMemberLoginFeatures {",
                    "    BOOL loginResult = [self loginForUserName:@\"member\"];",
                    "    XCTAssertTrue(loginResult);",
                    "",
                    "    XCTAssertFalse(self.app.buttons[@\"Admin Features\"].exists, @\"Admin Features button is visible and should not be.\");",
                    "    XCTAssertTrue(self.app.buttons[@\"Member Features\"].exists, @\"Missing Member Features button.\");",
                    "}",
                    "",
                    "- (void)testGuestLoginFeatures {",
                    "    BOOL loginResult = [self loginForUserName:@\"guest\"];",
                    "    if (loginResult == YES) {",
                    "        XCTAssertFalse(self.app.buttons[@\"Admin Features\"].exists, @\"Admin Features button is visible and should not be.\");",
                    "        XCTAssertFalse(self.app.buttons[@\"Member Features\"].exists, @\"Member Features button is visible and should not be.\");",
                    "    } else {",
                    "        XCTSkip(@\"Guest logins are still not working, skip this test.\");",
                    "    }",
                    "}",
                    "",
                    "- (BOOL)loginForUserName:(NSString *) userName {",
                    "    __block BOOL loginSuccessful = NO;",
                    "    [XCTContext runActivityNamed:@\"Login\" block:^(id<XCTActivity> activity) {",
                    "        [self performLoginUITestsForUserName:userName];",
                    "        loginSuccessful = self.app.staticTexts[@\"Logged In\"].exists;",
                    "        if (!loginSuccessful) {",
                    "            XCUIScreenshot *screenshot = [self.app.windows.firstMatch screenshot];",
                    "            XCTAttachment *attachment = [XCTAttachment attachmentWithScreenshot:screenshot];",
                    "            attachment.lifetime = XCTAttachmentLifetimeKeepAlways;",
                    "            [activity addAttachment:attachment];",
                    "        }",
                    "    }];",
                    "    return loginSuccessful;",
                    "}",
                    ""
                  ],
                  "syntax": "objc",
                  "type": "codeListing"
                }
              ],
              "title": "Objective-C"
            }
          ],
          "type": "tabNavigator"
        },
        {
          "inlineContent": [
            {
              "text": "If the login fails, the login activity adds a screenshot as an attachment for later investigation. For more information, see ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.xctest/documentation/XCTest/adding-attachments-to-tests-activities-and-issues",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ".",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "You can use ",
              "type": "text"
            },
            {
              "code": "XCTContext",
              "type": "codeVoice"
            },
            {
              "text": " anywhere within your test target, not just within test methods on an ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.xctest/documentation/XCTest/XCTestCase",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " subclass. This enables you to define activities in your own utility code, such as in custom methods on subclasses of ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/XCUIAutomation/XCUIApplication",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " or ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/XCUIAutomation/XCUIElement",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ".",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/XCUIAutomation/XCUIApplication": {
      "abstract": [
        {
          "text": "A proxy that can launch, monitor, and terminate a test application.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@"
        },
        {
          "kind": "attribute",
          "preciseIdentifier": "s:ScM",
          "text": "MainActor"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "XCUIApplication"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/XCUIAutomation/XCUIApplication",
      "kind": "symbol",
      "role": "symbol",
      "title": "XCUIApplication",
      "type": "topic",
      "url": "/documentation/XCUIAutomation/XCUIApplication"
    },
    "doc://com.apple.documentation/documentation/XCUIAutomation/XCUIElement": {
      "abstract": [
        {
          "text": "A UI element in an application.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@"
        },
        {
          "kind": "attribute",
          "preciseIdentifier": "s:ScM",
          "text": "MainActor"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "XCUIElement"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/XCUIAutomation/XCUIElement",
      "kind": "symbol",
      "role": "symbol",
      "title": "XCUIElement",
      "type": "topic",
      "url": "/documentation/XCUIAutomation/XCUIElement"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.xctest/documentation/XCTest": {
      "abstract": [
        {
          "text": "Create and run unit tests, performance tests, and UI tests for your Xcode project.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.xctest/documentation/XCTest",
      "kind": "symbol",
      "role": "collection",
      "title": "XCTest",
      "type": "topic",
      "url": "/documentation/xctest"
    },
    "doc://com.apple.xctest/documentation/XCTest/XCTActivity": {
      "abstract": [
        {
          "text": "A named substep of a test method.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "XCTActivity"
        }
      ],
      "identifier": "doc://com.apple.xctest/documentation/XCTest/XCTActivity",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "XCTActivity"
        }
      ],
      "role": "symbol",
      "title": "XCTActivity",
      "type": "topic",
      "url": "/documentation/xctest/xctactivity"
    },
    "doc://com.apple.xctest/documentation/XCTest/XCTContext": {
      "abstract": [
        {
          "text": "A proxy for the current testing context.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "XCTContext"
        }
      ],
      "identifier": "doc://com.apple.xctest/documentation/XCTest/XCTContext",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "XCTContext"
        }
      ],
      "role": "symbol",
      "title": "XCTContext",
      "type": "topic",
      "url": "/documentation/xctest/xctcontext"
    },
    "doc://com.apple.xctest/documentation/XCTest/XCTContext/runActivityNamed:block:": {
      "abstract": [
        {
          "text": "Creates and runs an activity with the provided block of code.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "+ "
        },
        {
          "kind": "identifier",
          "text": "runActivityNamed:block:"
        }
      ],
      "identifier": "doc://com.apple.xctest/documentation/XCTest/XCTContext/runActivityNamed:block:",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "runActivityNamed:block:"
        }
      ],
      "role": "symbol",
      "title": "runActivityNamed:block:",
      "type": "topic",
      "url": "/documentation/xctest/xctcontext/runactivitynamed:block:"
    },
    "doc://com.apple.xctest/documentation/XCTest/XCTestCase": {
      "abstract": [
        {
          "text": "The primary class for defining test cases, test methods, and performance tests.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "XCTestCase"
        }
      ],
      "identifier": "doc://com.apple.xctest/documentation/XCTest/XCTestCase",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "XCTestCase"
        }
      ],
      "role": "symbol",
      "title": "XCTestCase",
      "type": "topic",
      "url": "/documentation/xctest/xctestcase"
    },
    "doc://com.apple.xctest/documentation/XCTest/activities-and-attachments": {
      "abstract": [
        {
          "text": "Split long tests into substeps with activities, and attach output data like files and screenshots.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.xctest/documentation/XCTest/activities-and-attachments",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Activities and Attachments",
      "type": "topic",
      "url": "/documentation/xctest/activities-and-attachments"
    },
    "doc://com.apple.xctest/documentation/XCTest/adding-attachments-to-tests-activities-and-issues": {
      "abstract": [
        {
          "text": "Use attachments to store a test’s output data for later analysis.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.xctest/documentation/XCTest/adding-attachments-to-tests-activities-and-issues",
      "kind": "article",
      "role": "article",
      "title": "Adding Attachments to Tests, Activities, and Issues",
      "type": "topic",
      "url": "/documentation/xctest/adding-attachments-to-tests-activities-and-issues"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Activities",
      "generated": true,
      "identifiers": [
        "doc://com.apple.xctest/documentation/XCTest/XCTContext",
        "doc://com.apple.xctest/documentation/XCTest/XCTActivity"
      ],
      "title": "Activities"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Activities",
              "generated": true,
              "identifiers": [
                "doc://com.apple.xctest/documentation/XCTest/XCTContext",
                "doc://com.apple.xctest/documentation/XCTest/XCTActivity"
              ],
              "title": "Activities"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCTestCase/title",
          "value": "XCTestCase"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCTestCase/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "XCTestCase"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCTestCase/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "XCTestCase"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCTActivity/title",
          "value": "XCTActivity"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCTActivity/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "XCTActivity"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCTActivity/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "XCTActivity"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1XCUIAutomation~1XCUIApplication/fragments",
          "value": [
            {
              "kind": "keyword",
              "text": "@interface"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "XCUIApplication"
            },
            {
              "kind": "text",
              "text": " : "
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)XCUIElement",
              "text": "XCUIElement"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCTContext/title",
          "value": "XCTContext"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCTContext/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "XCTContext"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCTContext/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "XCTContext"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1XCUIAutomation~1XCUIElement/fragments",
          "value": [
            {
              "kind": "keyword",
              "text": "@interface"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "XCUIElement"
            },
            {
              "kind": "text",
              "text": " : "
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)NSObject",
              "text": "NSObject"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/xctest/grouping-tests-into-substeps-with-activities"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/xctest/grouping-tests-into-substeps-with-activities"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
