{
  "abstract": [
    {
      "text": "Check whether a function call throws, or doesn’t throw, an exception.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.xctest/documentation/XCTest"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.xctest/documentation/XCTest/nsexception-assertions"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "XCTest"
      }
    ],
    "role": "collectionGroup",
    "roleHeading": "API Collection",
    "title": "NSException Assertions"
  },
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.xctest/documentation/XCTest": {
      "abstract": [
        {
          "text": "Create and run unit tests, performance tests, and UI tests for your Xcode project.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.xctest/documentation/XCTest",
      "kind": "symbol",
      "role": "collection",
      "title": "XCTest",
      "type": "topic",
      "url": "/documentation/xctest"
    },
    "doc://com.apple.xctest/documentation/XCTest/XCTAssertNoThrow": {
      "abstract": [
        {
          "text": "Asserts that an expression doesn’t throw an ",
          "type": "text"
        },
        {
          "code": "NSException",
          "type": "codeVoice"
        },
        {
          "text": ".",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "XCTAssertNoThrow"
        }
      ],
      "identifier": "doc://com.apple.xctest/documentation/XCTest/XCTAssertNoThrow",
      "kind": "symbol",
      "role": "symbol",
      "title": "XCTAssertNoThrow",
      "type": "topic",
      "url": "/documentation/xctest/xctassertnothrow"
    },
    "doc://com.apple.xctest/documentation/XCTest/XCTAssertNoThrowSpecific": {
      "abstract": [
        {
          "text": "Asserts that an expression doesn’t throw a specific ",
          "type": "text"
        },
        {
          "code": "NSException",
          "type": "codeVoice"
        },
        {
          "text": ".",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "XCTAssertNoThrowSpecific"
        }
      ],
      "identifier": "doc://com.apple.xctest/documentation/XCTest/XCTAssertNoThrowSpecific",
      "kind": "symbol",
      "role": "symbol",
      "title": "XCTAssertNoThrowSpecific",
      "type": "topic",
      "url": "/documentation/xctest/xctassertnothrowspecific"
    },
    "doc://com.apple.xctest/documentation/XCTest/XCTAssertNoThrowSpecificNamed": {
      "abstract": [
        {
          "text": "Asserts that an expression doesn’t throw a specific ",
          "type": "text"
        },
        {
          "code": "NSException",
          "type": "codeVoice"
        },
        {
          "text": " with a specific name.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "XCTAssertNoThrowSpecificNamed"
        }
      ],
      "identifier": "doc://com.apple.xctest/documentation/XCTest/XCTAssertNoThrowSpecificNamed",
      "kind": "symbol",
      "role": "symbol",
      "title": "XCTAssertNoThrowSpecificNamed",
      "type": "topic",
      "url": "/documentation/xctest/xctassertnothrowspecificnamed"
    },
    "doc://com.apple.xctest/documentation/XCTest/XCTAssertThrows": {
      "abstract": [
        {
          "text": "Asserts that an expression throws an ",
          "type": "text"
        },
        {
          "code": "NSException",
          "type": "codeVoice"
        },
        {
          "text": ".",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "XCTAssertThrows"
        }
      ],
      "identifier": "doc://com.apple.xctest/documentation/XCTest/XCTAssertThrows",
      "kind": "symbol",
      "role": "symbol",
      "title": "XCTAssertThrows",
      "type": "topic",
      "url": "/documentation/xctest/xctassertthrows"
    },
    "doc://com.apple.xctest/documentation/XCTest/XCTAssertThrowsSpecific": {
      "abstract": [
        {
          "text": "Asserts that an expression throws a specific ",
          "type": "text"
        },
        {
          "code": "NSException",
          "type": "codeVoice"
        },
        {
          "text": ".",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "XCTAssertThrowsSpecific"
        }
      ],
      "identifier": "doc://com.apple.xctest/documentation/XCTest/XCTAssertThrowsSpecific",
      "kind": "symbol",
      "role": "symbol",
      "title": "XCTAssertThrowsSpecific",
      "type": "topic",
      "url": "/documentation/xctest/xctassertthrowsspecific"
    },
    "doc://com.apple.xctest/documentation/XCTest/XCTAssertThrowsSpecificNamed": {
      "abstract": [
        {
          "text": "Asserts that an expression throws a specific NSException with a specific name.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "XCTAssertThrowsSpecificNamed"
        }
      ],
      "identifier": "doc://com.apple.xctest/documentation/XCTest/XCTAssertThrowsSpecificNamed",
      "kind": "symbol",
      "role": "symbol",
      "title": "XCTAssertThrowsSpecificNamed",
      "type": "topic",
      "url": "/documentation/xctest/xctassertthrowsspecificnamed"
    },
    "doc://com.apple.xctest/documentation/XCTest/boolean-assertions": {
      "abstract": [
        {
          "text": "Test a condition that generates a true or false result.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.xctest/documentation/XCTest/boolean-assertions",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Boolean Assertions",
      "type": "topic",
      "url": "/documentation/xctest/boolean-assertions"
    },
    "doc://com.apple.xctest/documentation/XCTest/comparable-value-assertions": {
      "abstract": [
        {
          "text": "Compare two values to determine whether one is larger or smaller than the other.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.xctest/documentation/XCTest/comparable-value-assertions",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Comparable Value Assertions",
      "type": "topic",
      "url": "/documentation/xctest/comparable-value-assertions"
    },
    "doc://com.apple.xctest/documentation/XCTest/equality-and-inequality-assertions": {
      "abstract": [
        {
          "text": "Check whether two values are equal or unequal.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.xctest/documentation/XCTest/equality-and-inequality-assertions",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Equality and Inequality Assertions",
      "type": "topic",
      "url": "/documentation/xctest/equality-and-inequality-assertions"
    },
    "doc://com.apple.xctest/documentation/XCTest/error-assertions": {
      "abstract": [
        {
          "text": "Check whether a function call throws, or doesn’t throw, an error.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.xctest/documentation/XCTest/error-assertions",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Error Assertions",
      "type": "topic",
      "url": "/documentation/xctest/error-assertions"
    },
    "doc://com.apple.xctest/documentation/XCTest/expected-failures": {
      "abstract": [
        {
          "text": "Anticipate known test failures to prevent failing tests from affecting your workflows.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.xctest/documentation/XCTest/expected-failures",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Expected Failures",
      "type": "topic",
      "url": "/documentation/xctest/expected-failures"
    },
    "doc://com.apple.xctest/documentation/XCTest/methods-for-skipping-tests": {
      "abstract": [
        {
          "text": "Skip tests when meeting specified conditions.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.xctest/documentation/XCTest/methods-for-skipping-tests",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Methods for Skipping Tests",
      "type": "topic",
      "url": "/documentation/xctest/methods-for-skipping-tests"
    },
    "doc://com.apple.xctest/documentation/XCTest/nil-and-non-nil-assertions": {
      "abstract": [
        {
          "text": "Check whether a test condition has, or doesn’t have, a value.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.xctest/documentation/XCTest/nil-and-non-nil-assertions",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Nil and Non-Nil Assertions",
      "type": "topic",
      "url": "/documentation/xctest/nil-and-non-nil-assertions"
    },
    "doc://com.apple.xctest/documentation/XCTest/unconditional-test-failures": {
      "abstract": [
        {
          "text": "Generate a failure immediately and unconditionally.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.xctest/documentation/XCTest/unconditional-test-failures",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Unconditional Test Failures",
      "type": "topic",
      "url": "/documentation/xctest/unconditional-test-failures"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Test-assertions",
      "generated": true,
      "identifiers": [
        "doc://com.apple.xctest/documentation/XCTest/boolean-assertions",
        "doc://com.apple.xctest/documentation/XCTest/nil-and-non-nil-assertions",
        "doc://com.apple.xctest/documentation/XCTest/equality-and-inequality-assertions",
        "doc://com.apple.xctest/documentation/XCTest/comparable-value-assertions",
        "doc://com.apple.xctest/documentation/XCTest/error-assertions",
        "doc://com.apple.xctest/documentation/XCTest/unconditional-test-failures",
        "doc://com.apple.xctest/documentation/XCTest/expected-failures",
        "doc://com.apple.xctest/documentation/XCTest/methods-for-skipping-tests"
      ],
      "title": "Test assertions"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Testing-for-Exceptions",
              "identifiers": [
                "doc://com.apple.xctest/documentation/XCTest/XCTAssertThrows",
                "doc://com.apple.xctest/documentation/XCTest/XCTAssertThrowsSpecific",
                "doc://com.apple.xctest/documentation/XCTest/XCTAssertThrowsSpecificNamed",
                "doc://com.apple.xctest/documentation/XCTest/XCTAssertNoThrow",
                "doc://com.apple.xctest/documentation/XCTest/XCTAssertNoThrowSpecific",
                "doc://com.apple.xctest/documentation/XCTest/XCTAssertNoThrowSpecificNamed"
              ],
              "title": "Testing for Exceptions"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Test-assertions",
              "generated": true,
              "identifiers": [
                "doc://com.apple.xctest/documentation/XCTest/boolean-assertions",
                "doc://com.apple.xctest/documentation/XCTest/nil-and-non-nil-assertions",
                "doc://com.apple.xctest/documentation/XCTest/equality-and-inequality-assertions",
                "doc://com.apple.xctest/documentation/XCTest/comparable-value-assertions",
                "doc://com.apple.xctest/documentation/XCTest/error-assertions",
                "doc://com.apple.xctest/documentation/XCTest/unconditional-test-failures",
                "doc://com.apple.xctest/documentation/XCTest/expected-failures",
                "doc://com.apple.xctest/documentation/XCTest/methods-for-skipping-tests"
              ],
              "title": "Test assertions"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/xctest/nsexception-assertions"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/xctest/nsexception-assertions"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
