{
  "abstract": [
    {
      "text": "Gather metrics while running your code, and report a failure if the metrics become significantly worse than a baseline value.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.xctest/documentation/XCTest"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.xctest/documentation/XCTest/performance-tests"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "XCTest"
      }
    ],
    "role": "collectionGroup",
    "roleHeading": "API Collection",
    "title": "Performance Tests"
  },
  "references": {
    "doc://com.apple.documentation/documentation/Xcode/writing-and-running-performance-tests": {
      "abstract": [
        {
          "text": "Repeatably gather metrics on the performance of your code.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/Xcode/writing-and-running-performance-tests",
      "kind": "article",
      "role": "article",
      "title": "Writing and running performance tests",
      "type": "topic",
      "url": "/documentation/Xcode/writing-and-running-performance-tests"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.xctest/documentation/XCTest": {
      "abstract": [
        {
          "text": "Create and run unit tests, performance tests, and UI tests for your Xcode project.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.xctest/documentation/XCTest",
      "kind": "symbol",
      "role": "collection",
      "title": "XCTest",
      "type": "topic",
      "url": "/documentation/xctest"
    },
    "doc://com.apple.xctest/documentation/XCTest/XCTApplicationLaunchMetric": {
      "abstract": [
        {
          "text": "A metric to record the application launch duration for a performance test.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "XCTApplicationLaunchMetric"
        }
      ],
      "identifier": "doc://com.apple.xctest/documentation/XCTest/XCTApplicationLaunchMetric",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "XCTApplicationLaunchMetric"
        }
      ],
      "role": "symbol",
      "title": "XCTApplicationLaunchMetric",
      "type": "topic",
      "url": "/documentation/xctest/xctapplicationlaunchmetric"
    },
    "doc://com.apple.xctest/documentation/XCTest/XCTCPUMetric": {
      "abstract": [
        {
          "text": "A metric to record information about CPU activity during a performance test.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "XCTCPUMetric"
        }
      ],
      "identifier": "doc://com.apple.xctest/documentation/XCTest/XCTCPUMetric",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "XCTCPUMetric"
        }
      ],
      "role": "symbol",
      "title": "XCTCPUMetric",
      "type": "topic",
      "url": "/documentation/xctest/xctcpumetric"
    },
    "doc://com.apple.xctest/documentation/XCTest/XCTClockMetric": {
      "abstract": [
        {
          "text": "A metric to record the time that elapses during a performance test.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "XCTClockMetric"
        }
      ],
      "identifier": "doc://com.apple.xctest/documentation/XCTest/XCTClockMetric",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "XCTClockMetric"
        }
      ],
      "role": "symbol",
      "title": "XCTClockMetric",
      "type": "topic",
      "url": "/documentation/xctest/xctclockmetric"
    },
    "doc://com.apple.xctest/documentation/XCTest/XCTMeasureOptions": {
      "abstract": [
        {
          "text": "Options to control the gathering of performance measurements during tests.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "XCTMeasureOptions"
        }
      ],
      "identifier": "doc://com.apple.xctest/documentation/XCTest/XCTMeasureOptions",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "XCTMeasureOptions"
        }
      ],
      "role": "symbol",
      "title": "XCTMeasureOptions",
      "type": "topic",
      "url": "/documentation/xctest/xctmeasureoptions"
    },
    "doc://com.apple.xctest/documentation/XCTest/XCTMemoryMetric": {
      "abstract": [
        {
          "text": "A metric to record the physical memory that a performance test uses.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "XCTMemoryMetric"
        }
      ],
      "identifier": "doc://com.apple.xctest/documentation/XCTest/XCTMemoryMetric",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "XCTMemoryMetric"
        }
      ],
      "role": "symbol",
      "title": "XCTMemoryMetric",
      "type": "topic",
      "url": "/documentation/xctest/xctmemorymetric"
    },
    "doc://com.apple.xctest/documentation/XCTest/XCTMetric": {
      "abstract": [
        {
          "text": "A protocol that defines the methods that objects must provide when gathering metrics during performance tests.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "XCTMetric"
        }
      ],
      "identifier": "doc://com.apple.xctest/documentation/XCTest/XCTMetric",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "XCTMetric"
        }
      ],
      "role": "symbol",
      "title": "XCTMetric",
      "type": "topic",
      "url": "/documentation/xctest/xctmetric"
    },
    "doc://com.apple.xctest/documentation/XCTest/XCTOSSignpostMetric": {
      "abstract": [
        {
          "text": "A metric to record the time that a performance test spends executing a signposted region of code.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "XCTOSSignpostMetric"
        }
      ],
      "identifier": "doc://com.apple.xctest/documentation/XCTest/XCTOSSignpostMetric",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "XCTOSSignpostMetric"
        }
      ],
      "role": "symbol",
      "title": "XCTOSSignpostMetric",
      "type": "topic",
      "url": "/documentation/xctest/xctossignpostmetric"
    },
    "doc://com.apple.xctest/documentation/XCTest/XCTPerformanceMeasurement": {
      "abstract": [
        {
          "text": "A measurement from a single iteration of a performance test.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "XCTPerformanceMeasurement"
        }
      ],
      "identifier": "doc://com.apple.xctest/documentation/XCTest/XCTPerformanceMeasurement",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "XCTPerformanceMeasurement"
        }
      ],
      "role": "symbol",
      "title": "XCTPerformanceMeasurement",
      "type": "topic",
      "url": "/documentation/xctest/xctperformancemeasurement"
    },
    "doc://com.apple.xctest/documentation/XCTest/XCTPerformanceMeasurementTimestamp": {
      "abstract": [
        {
          "text": "A point in time that captures the start or finish of a performance test iteration.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "XCTPerformanceMeasurementTimestamp"
        }
      ],
      "identifier": "doc://com.apple.xctest/documentation/XCTest/XCTPerformanceMeasurementTimestamp",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "XCTPerformanceMeasurementTimestamp"
        }
      ],
      "role": "symbol",
      "title": "XCTPerformanceMeasurementTimestamp",
      "type": "topic",
      "url": "/documentation/xctest/xctperformancemeasurementtimestamp"
    },
    "doc://com.apple.xctest/documentation/XCTest/XCTStorageMetric": {
      "abstract": [
        {
          "text": "A metric to record the amount of data that a performance test logically writes to storage.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "XCTStorageMetric"
        }
      ],
      "identifier": "doc://com.apple.xctest/documentation/XCTest/XCTStorageMetric",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "XCTStorageMetric"
        }
      ],
      "role": "symbol",
      "title": "XCTStorageMetric",
      "type": "topic",
      "url": "/documentation/xctest/xctstoragemetric"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "topicSections": [
    {
      "anchor": "Measuring-Performance",
      "identifiers": [
        "doc://com.apple.documentation/documentation/Xcode/writing-and-running-performance-tests"
      ],
      "title": "Measuring Performance"
    },
    {
      "anchor": "Measurement-Options",
      "identifiers": [
        "doc://com.apple.xctest/documentation/XCTest/XCTMeasureOptions"
      ],
      "title": "Measurement Options"
    },
    {
      "anchor": "Measurement-Metrics",
      "identifiers": [
        "doc://com.apple.xctest/documentation/XCTest/XCTMetric",
        "doc://com.apple.xctest/documentation/XCTest/XCTCPUMetric",
        "doc://com.apple.xctest/documentation/XCTest/XCTClockMetric",
        "doc://com.apple.xctest/documentation/XCTest/XCTMemoryMetric",
        "doc://com.apple.xctest/documentation/XCTest/XCTOSSignpostMetric",
        "doc://com.apple.xctest/documentation/XCTest/XCTStorageMetric",
        "doc://com.apple.xctest/documentation/XCTest/XCTApplicationLaunchMetric"
      ],
      "title": "Measurement Metrics"
    },
    {
      "anchor": "Measurements",
      "identifiers": [
        "doc://com.apple.xctest/documentation/XCTest/XCTPerformanceMeasurement",
        "doc://com.apple.xctest/documentation/XCTest/XCTPerformanceMeasurementTimestamp"
      ],
      "title": "Measurements"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Measuring-Performance",
              "identifiers": [
                "doc://com.apple.documentation/documentation/Xcode/writing-and-running-performance-tests"
              ],
              "title": "Measuring Performance"
            },
            {
              "anchor": "Measurement-Options",
              "identifiers": [
                "doc://com.apple.xctest/documentation/XCTest/XCTMeasureOptions"
              ],
              "title": "Measurement Options"
            },
            {
              "anchor": "Measurement-Metrics",
              "identifiers": [
                "doc://com.apple.xctest/documentation/XCTest/XCTMetric",
                "doc://com.apple.xctest/documentation/XCTest/XCTCPUMetric",
                "doc://com.apple.xctest/documentation/XCTest/XCTClockMetric",
                "doc://com.apple.xctest/documentation/XCTest/XCTMemoryMetric",
                "doc://com.apple.xctest/documentation/XCTest/XCTOSSignpostMetric",
                "doc://com.apple.xctest/documentation/XCTest/XCTStorageMetric",
                "doc://com.apple.xctest/documentation/XCTest/XCTApplicationLaunchMetric"
              ],
              "title": "Measurement Metrics"
            },
            {
              "anchor": "Measurements",
              "identifiers": [
                "doc://com.apple.xctest/documentation/XCTest/XCTPerformanceMeasurement",
                "doc://com.apple.xctest/documentation/XCTest/XCTPerformanceMeasurementTimestamp"
              ],
              "title": "Measurements"
            }
          ]
        },
        {
          "op": "add",
          "path": "/seeAlsoSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCTClockMetric/title",
          "value": "XCTClockMetric"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCTClockMetric/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "XCTClockMetric"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCTClockMetric/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "XCTClockMetric"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCTStorageMetric/title",
          "value": "XCTStorageMetric"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCTStorageMetric/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "XCTStorageMetric"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCTStorageMetric/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "XCTStorageMetric"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCTPerformanceMeasurement/title",
          "value": "XCTPerformanceMeasurement"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCTPerformanceMeasurement/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "XCTPerformanceMeasurement"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCTPerformanceMeasurement/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "XCTPerformanceMeasurement"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCTOSSignpostMetric/title",
          "value": "XCTOSSignpostMetric"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCTOSSignpostMetric/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "XCTOSSignpostMetric"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCTOSSignpostMetric/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "XCTOSSignpostMetric"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCTMetric/title",
          "value": "XCTMetric"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCTMetric/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "XCTMetric"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCTMetric/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "XCTMetric"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCTPerformanceMeasurementTimestamp/title",
          "value": "XCTPerformanceMeasurementTimestamp"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCTPerformanceMeasurementTimestamp/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "XCTPerformanceMeasurementTimestamp"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCTPerformanceMeasurementTimestamp/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "XCTPerformanceMeasurementTimestamp"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCTMeasureOptions/title",
          "value": "XCTMeasureOptions"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCTMeasureOptions/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "XCTMeasureOptions"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCTMeasureOptions/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "XCTMeasureOptions"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCTCPUMetric/title",
          "value": "XCTCPUMetric"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCTCPUMetric/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "XCTCPUMetric"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCTCPUMetric/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "XCTCPUMetric"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCTMemoryMetric/title",
          "value": "XCTMemoryMetric"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCTMemoryMetric/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "XCTMemoryMetric"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCTMemoryMetric/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "XCTMemoryMetric"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCTApplicationLaunchMetric/title",
          "value": "XCTApplicationLaunchMetric"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCTApplicationLaunchMetric/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "XCTApplicationLaunchMetric"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCTApplicationLaunchMetric/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "XCTApplicationLaunchMetric"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/xctest/performance-tests"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/xctest/performance-tests"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
