{
  "abstract": [
    {
      "text": "Observe, introspect, and customize the test execution flow.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.xctest/documentation/XCTest"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.xctest/documentation/XCTest/test-execution-and-observation"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "XCTest"
      }
    ],
    "role": "collectionGroup",
    "roleHeading": "API Collection",
    "title": "Test Execution and Observation"
  },
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.xctest/documentation/XCTest": {
      "abstract": [
        {
          "text": "Create and run unit tests, performance tests, and UI tests for your Xcode project.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.xctest/documentation/XCTest",
      "kind": "symbol",
      "role": "collection",
      "title": "XCTest",
      "type": "topic",
      "url": "/documentation/xctest"
    },
    "doc://com.apple.xctest/documentation/XCTest/XCTIssue-swift.struct": {
      "abstract": [
        {
          "text": "An object that represents a test failure, and includes source code call stacks for test reporting and investigation.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "XCTIssue"
        }
      ],
      "identifier": "doc://com.apple.xctest/documentation/XCTest/XCTIssue-swift.struct",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "XCTIssue"
        }
      ],
      "role": "symbol",
      "title": "XCTIssue",
      "type": "topic",
      "url": "/documentation/xctest/xctissue-swift.struct"
    },
    "doc://com.apple.xctest/documentation/XCTest/XCTIssueReference": {
      "abstract": [
        {
          "text": "An object that represents a test failure, and includes source code call stacks for test reporting and investigation.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "XCTIssueReference"
        }
      ],
      "identifier": "doc://com.apple.xctest/documentation/XCTest/XCTIssueReference",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "XCTIssueReference"
        }
      ],
      "role": "symbol",
      "title": "XCTIssueReference",
      "type": "topic",
      "url": "/documentation/xctest/xctissuereference"
    },
    "doc://com.apple.xctest/documentation/XCTest/XCTMutableIssue": {
      "abstract": [
        {
          "text": "A mutable object that represents a test failure, and includes source code call stacks for test reporting and investigation.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "XCTMutableIssue"
        }
      ],
      "identifier": "doc://com.apple.xctest/documentation/XCTest/XCTMutableIssue",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "XCTMutableIssue"
        }
      ],
      "role": "symbol",
      "title": "XCTMutableIssue",
      "type": "topic",
      "url": "/documentation/xctest/xctmutableissue"
    },
    "doc://com.apple.xctest/documentation/XCTest/XCTSourceCodeContext": {
      "abstract": [
        {
          "text": "An object that contains call stack and source code location details to provide context for a point of execution in a test.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "XCTSourceCodeContext"
        }
      ],
      "identifier": "doc://com.apple.xctest/documentation/XCTest/XCTSourceCodeContext",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "XCTSourceCodeContext"
        }
      ],
      "role": "symbol",
      "title": "XCTSourceCodeContext",
      "type": "topic",
      "url": "/documentation/xctest/xctsourcecodecontext"
    },
    "doc://com.apple.xctest/documentation/XCTest/XCTSourceCodeFrame": {
      "abstract": [
        {
          "text": "An object that represents a single frame in a call stack that supports retrieval of symbol information for the address.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "XCTSourceCodeFrame"
        }
      ],
      "identifier": "doc://com.apple.xctest/documentation/XCTest/XCTSourceCodeFrame",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "XCTSourceCodeFrame"
        }
      ],
      "role": "symbol",
      "title": "XCTSourceCodeFrame",
      "type": "topic",
      "url": "/documentation/xctest/xctsourcecodeframe"
    },
    "doc://com.apple.xctest/documentation/XCTest/XCTSourceCodeLocation": {
      "abstract": [
        {
          "text": "An object that contains a file URL and line number that represents a distinct location in source code.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "XCTSourceCodeLocation"
        }
      ],
      "identifier": "doc://com.apple.xctest/documentation/XCTest/XCTSourceCodeLocation",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "XCTSourceCodeLocation"
        }
      ],
      "role": "symbol",
      "title": "XCTSourceCodeLocation",
      "type": "topic",
      "url": "/documentation/xctest/xctsourcecodelocation"
    },
    "doc://com.apple.xctest/documentation/XCTest/XCTSourceCodeSymbolInfo": {
      "abstract": [
        {
          "text": "An object that contains symbolication information for a specified frame in a call stack.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "XCTSourceCodeSymbolInfo"
        }
      ],
      "identifier": "doc://com.apple.xctest/documentation/XCTest/XCTSourceCodeSymbolInfo",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "XCTSourceCodeSymbolInfo"
        }
      ],
      "role": "symbol",
      "title": "XCTSourceCodeSymbolInfo",
      "type": "topic",
      "url": "/documentation/xctest/xctsourcecodesymbolinfo"
    },
    "doc://com.apple.xctest/documentation/XCTest/XCTestCaseRun": {
      "abstract": [
        {
          "text": "An object that collects information about a specific execution of a test case.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "XCTestCaseRun"
        }
      ],
      "identifier": "doc://com.apple.xctest/documentation/XCTest/XCTestCaseRun",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "XCTestCaseRun"
        }
      ],
      "role": "symbol",
      "title": "XCTestCaseRun",
      "type": "topic",
      "url": "/documentation/xctest/xctestcaserun"
    },
    "doc://com.apple.xctest/documentation/XCTest/XCTestObservation": {
      "abstract": [
        {
          "text": "A protocol that defines methods the test runner calls in response to significant events during test runs.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "XCTestObservation"
        }
      ],
      "identifier": "doc://com.apple.xctest/documentation/XCTest/XCTestObservation",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "XCTestObservation"
        }
      ],
      "role": "symbol",
      "title": "XCTestObservation",
      "type": "topic",
      "url": "/documentation/xctest/xctestobservation"
    },
    "doc://com.apple.xctest/documentation/XCTest/XCTestObservationCenter": {
      "abstract": [
        {
          "text": "Provides information about the progress of test runs to registered observers.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "XCTestObservationCenter"
        }
      ],
      "identifier": "doc://com.apple.xctest/documentation/XCTest/XCTestObservationCenter",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "XCTestObservationCenter"
        }
      ],
      "role": "symbol",
      "title": "XCTestObservationCenter",
      "type": "topic",
      "url": "/documentation/xctest/xctestobservationcenter"
    },
    "doc://com.apple.xctest/documentation/XCTest/XCTestRun": {
      "abstract": [
        {
          "text": "A base class for collecting information about a specific execution of a test.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "XCTestRun"
        }
      ],
      "identifier": "doc://com.apple.xctest/documentation/XCTest/XCTestRun",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "XCTestRun"
        }
      ],
      "role": "symbol",
      "title": "XCTestRun",
      "type": "topic",
      "url": "/documentation/xctest/xctestrun"
    },
    "doc://com.apple.xctest/documentation/XCTest/XCTestSuite": {
      "abstract": [
        {
          "text": "A collection of test cases to manage as a test suite.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "XCTestSuite"
        }
      ],
      "identifier": "doc://com.apple.xctest/documentation/XCTest/XCTestSuite",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "XCTestSuite"
        }
      ],
      "role": "symbol",
      "title": "XCTestSuite",
      "type": "topic",
      "url": "/documentation/xctest/xctestsuite"
    },
    "doc://com.apple.xctest/documentation/XCTest/XCTestSuiteRun": {
      "abstract": [
        {
          "text": "An object that collects information about a specific execution of a test suite.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "XCTestSuiteRun"
        }
      ],
      "identifier": "doc://com.apple.xctest/documentation/XCTest/XCTestSuiteRun",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "XCTestSuiteRun"
        }
      ],
      "role": "symbol",
      "title": "XCTestSuiteRun",
      "type": "topic",
      "url": "/documentation/xctest/xctestsuiterun"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "topicSections": [
    {
      "abstract": [
        {
          "text": "Capture test failures with ",
          "type": "text"
        },
        {
          "code": "XCTIssue",
          "type": "codeVoice"
        },
        {
          "text": " and related classes that associate source code locations and call stacks with failures.",
          "type": "text"
        }
      ],
      "anchor": "Test-Failures",
      "identifiers": [
        "doc://com.apple.xctest/documentation/XCTest/XCTIssue-swift.struct",
        "doc://com.apple.xctest/documentation/XCTest/XCTIssueReference",
        "doc://com.apple.xctest/documentation/XCTest/XCTMutableIssue",
        "doc://com.apple.xctest/documentation/XCTest/XCTSourceCodeContext",
        "doc://com.apple.xctest/documentation/XCTest/XCTSourceCodeFrame",
        "doc://com.apple.xctest/documentation/XCTest/XCTSourceCodeLocation",
        "doc://com.apple.xctest/documentation/XCTest/XCTSourceCodeSymbolInfo"
      ],
      "title": "Test Failures"
    },
    {
      "anchor": "Test-Runs",
      "identifiers": [
        "doc://com.apple.xctest/documentation/XCTest/XCTestCaseRun",
        "doc://com.apple.xctest/documentation/XCTest/XCTestSuiteRun",
        "doc://com.apple.xctest/documentation/XCTest/XCTestRun"
      ],
      "title": "Test Runs"
    },
    {
      "anchor": "Test-Observation",
      "identifiers": [
        "doc://com.apple.xctest/documentation/XCTest/XCTestObservation",
        "doc://com.apple.xctest/documentation/XCTest/XCTestObservationCenter"
      ],
      "title": "Test Observation"
    },
    {
      "anchor": "Test-Suites",
      "identifiers": [
        "doc://com.apple.xctest/documentation/XCTest/XCTestSuite"
      ],
      "title": "Test Suites"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "abstract": [
                {
                  "text": "Capture test failures with ",
                  "type": "text"
                },
                {
                  "code": "XCTIssue",
                  "type": "codeVoice"
                },
                {
                  "text": " and related classes that associate source code locations and call stacks with failures.",
                  "type": "text"
                }
              ],
              "anchor": "Test-Failures",
              "identifiers": [
                "doc://com.apple.xctest/documentation/XCTest/XCTIssueReference",
                "doc://com.apple.xctest/documentation/XCTest/XCTMutableIssue",
                "doc://com.apple.xctest/documentation/XCTest/XCTSourceCodeContext",
                "doc://com.apple.xctest/documentation/XCTest/XCTSourceCodeFrame",
                "doc://com.apple.xctest/documentation/XCTest/XCTSourceCodeLocation",
                "doc://com.apple.xctest/documentation/XCTest/XCTSourceCodeSymbolInfo"
              ],
              "title": "Test Failures"
            },
            {
              "anchor": "Test-Runs",
              "identifiers": [
                "doc://com.apple.xctest/documentation/XCTest/XCTestCaseRun",
                "doc://com.apple.xctest/documentation/XCTest/XCTestSuiteRun",
                "doc://com.apple.xctest/documentation/XCTest/XCTestRun"
              ],
              "title": "Test Runs"
            },
            {
              "anchor": "Test-Observation",
              "identifiers": [
                "doc://com.apple.xctest/documentation/XCTest/XCTestObservation",
                "doc://com.apple.xctest/documentation/XCTest/XCTestObservationCenter"
              ],
              "title": "Test Observation"
            },
            {
              "anchor": "Test-Suites",
              "identifiers": [
                "doc://com.apple.xctest/documentation/XCTest/XCTestSuite"
              ],
              "title": "Test Suites"
            }
          ]
        },
        {
          "op": "add",
          "path": "/seeAlsoSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCTestSuiteRun/title",
          "value": "XCTestSuiteRun"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCTestSuiteRun/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "XCTestSuiteRun"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCTestSuiteRun/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "XCTestSuiteRun"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCTMutableIssue/title",
          "value": "XCTMutableIssue"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCTMutableIssue/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "XCTMutableIssue"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCTMutableIssue/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "XCTMutableIssue"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCTSourceCodeLocation/title",
          "value": "XCTSourceCodeLocation"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCTSourceCodeLocation/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "XCTSourceCodeLocation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCTSourceCodeLocation/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "XCTSourceCodeLocation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCTSourceCodeSymbolInfo/title",
          "value": "XCTSourceCodeSymbolInfo"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCTSourceCodeSymbolInfo/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "XCTSourceCodeSymbolInfo"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCTSourceCodeSymbolInfo/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "XCTSourceCodeSymbolInfo"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCTestSuite/title",
          "value": "XCTestSuite"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCTestSuite/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "XCTestSuite"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCTestSuite/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "XCTestSuite"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCTestObservationCenter/title",
          "value": "XCTestObservationCenter"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCTestObservationCenter/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "XCTestObservationCenter"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCTestObservationCenter/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "XCTestObservationCenter"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCTSourceCodeContext/title",
          "value": "XCTSourceCodeContext"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCTSourceCodeContext/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "XCTSourceCodeContext"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCTSourceCodeContext/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "XCTSourceCodeContext"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCTIssueReference/title",
          "value": "XCTIssue"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCTIssueReference/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "XCTIssue"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCTIssueReference/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "XCTIssue"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCTestCaseRun/title",
          "value": "XCTestCaseRun"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCTestCaseRun/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "XCTestCaseRun"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCTestCaseRun/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "XCTestCaseRun"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCTSourceCodeFrame/title",
          "value": "XCTSourceCodeFrame"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCTSourceCodeFrame/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "XCTSourceCodeFrame"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCTSourceCodeFrame/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "XCTSourceCodeFrame"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCTestObservation/title",
          "value": "XCTestObservation"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCTestObservation/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "XCTestObservation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCTestObservation/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "XCTestObservation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCTestRun/title",
          "value": "XCTestRun"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCTestRun/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "XCTestRun"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCTestRun/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "XCTestRun"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/xctest/test-execution-and-observation"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/xctest/test-execution-and-observation"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
