{
  "abstract": [
    {
      "text": "Generate a failure immediately and unconditionally.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.xctest/documentation/XCTest"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.xctest/documentation/XCTest/unconditional-test-failures"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "XCTest"
      }
    ],
    "role": "collectionGroup",
    "roleHeading": "API Collection",
    "title": "Unconditional Test Failures"
  },
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.xctest/documentation/XCTest": {
      "abstract": [
        {
          "text": "Create and run unit tests, performance tests, and UI tests for your Xcode project.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.xctest/documentation/XCTest",
      "kind": "symbol",
      "role": "collection",
      "title": "XCTest",
      "type": "topic",
      "url": "/documentation/xctest"
    },
    "doc://com.apple.xctest/documentation/XCTest/XCTFail": {
      "abstract": [
        {
          "text": "This function generates a failure immediately and unconditionally.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "XCTFail"
        }
      ],
      "identifier": "doc://com.apple.xctest/documentation/XCTest/XCTFail",
      "kind": "symbol",
      "role": "symbol",
      "title": "XCTFail",
      "type": "topic",
      "url": "/documentation/xctest/xctfail"
    },
    "doc://com.apple.xctest/documentation/XCTest/XCTFail(_:file:line:)": {
      "abstract": [
        {
          "text": "This function generates a failure immediately and unconditionally.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "XCTFail"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "file"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s12StaticStringV",
          "text": "StaticString"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "line"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Su",
          "text": "UInt"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.xctest/documentation/XCTest/XCTFail(_:file:line:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "XCTFail(_:file:line:)",
      "type": "topic",
      "url": "/documentation/xctest/xctfail(_:file:line:)"
    },
    "doc://com.apple.xctest/documentation/XCTest/boolean-assertions": {
      "abstract": [
        {
          "text": "Test a condition that generates a true or false result.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.xctest/documentation/XCTest/boolean-assertions",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Boolean Assertions",
      "type": "topic",
      "url": "/documentation/xctest/boolean-assertions"
    },
    "doc://com.apple.xctest/documentation/XCTest/comparable-value-assertions": {
      "abstract": [
        {
          "text": "Compare two values to determine whether one is larger or smaller than the other.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.xctest/documentation/XCTest/comparable-value-assertions",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Comparable Value Assertions",
      "type": "topic",
      "url": "/documentation/xctest/comparable-value-assertions"
    },
    "doc://com.apple.xctest/documentation/XCTest/equality-and-inequality-assertions": {
      "abstract": [
        {
          "text": "Check whether two values are equal or unequal.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.xctest/documentation/XCTest/equality-and-inequality-assertions",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Equality and Inequality Assertions",
      "type": "topic",
      "url": "/documentation/xctest/equality-and-inequality-assertions"
    },
    "doc://com.apple.xctest/documentation/XCTest/error-assertions": {
      "abstract": [
        {
          "text": "Check whether a function call throws, or doesn’t throw, an error.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.xctest/documentation/XCTest/error-assertions",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Error Assertions",
      "type": "topic",
      "url": "/documentation/xctest/error-assertions"
    },
    "doc://com.apple.xctest/documentation/XCTest/expected-failures": {
      "abstract": [
        {
          "text": "Anticipate known test failures to prevent failing tests from affecting your workflows.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.xctest/documentation/XCTest/expected-failures",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Expected Failures",
      "type": "topic",
      "url": "/documentation/xctest/expected-failures"
    },
    "doc://com.apple.xctest/documentation/XCTest/methods-for-skipping-tests": {
      "abstract": [
        {
          "text": "Skip tests when meeting specified conditions.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.xctest/documentation/XCTest/methods-for-skipping-tests",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Methods for Skipping Tests",
      "type": "topic",
      "url": "/documentation/xctest/methods-for-skipping-tests"
    },
    "doc://com.apple.xctest/documentation/XCTest/nil-and-non-nil-assertions": {
      "abstract": [
        {
          "text": "Check whether a test condition has, or doesn’t have, a value.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.xctest/documentation/XCTest/nil-and-non-nil-assertions",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Nil and Non-Nil Assertions",
      "type": "topic",
      "url": "/documentation/xctest/nil-and-non-nil-assertions"
    },
    "doc://com.apple.xctest/documentation/XCTest/nsexception-assertions": {
      "abstract": [
        {
          "text": "Check whether a function call throws, or doesn’t throw, an exception.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.xctest/documentation/XCTest/nsexception-assertions",
      "kind": "article",
      "role": "collectionGroup",
      "title": "NSException Assertions",
      "type": "topic",
      "url": "/documentation/xctest/nsexception-assertions"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Test-assertions",
      "generated": true,
      "identifiers": [
        "doc://com.apple.xctest/documentation/XCTest/boolean-assertions",
        "doc://com.apple.xctest/documentation/XCTest/nil-and-non-nil-assertions",
        "doc://com.apple.xctest/documentation/XCTest/equality-and-inequality-assertions",
        "doc://com.apple.xctest/documentation/XCTest/comparable-value-assertions",
        "doc://com.apple.xctest/documentation/XCTest/error-assertions",
        "doc://com.apple.xctest/documentation/XCTest/nsexception-assertions",
        "doc://com.apple.xctest/documentation/XCTest/expected-failures",
        "doc://com.apple.xctest/documentation/XCTest/methods-for-skipping-tests"
      ],
      "title": "Test assertions"
    }
  ],
  "topicSections": [
    {
      "anchor": "Unconditional-Test-Failures",
      "identifiers": [
        "doc://com.apple.xctest/documentation/XCTest/XCTFail(_:file:line:)"
      ],
      "title": "Unconditional Test Failures"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Unconditional-Test-Failures",
              "identifiers": [
                "doc://com.apple.xctest/documentation/XCTest/XCTFail"
              ],
              "title": "Unconditional Test Failures"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Test-assertions",
              "generated": true,
              "identifiers": [
                "doc://com.apple.xctest/documentation/XCTest/boolean-assertions",
                "doc://com.apple.xctest/documentation/XCTest/nil-and-non-nil-assertions",
                "doc://com.apple.xctest/documentation/XCTest/equality-and-inequality-assertions",
                "doc://com.apple.xctest/documentation/XCTest/comparable-value-assertions",
                "doc://com.apple.xctest/documentation/XCTest/error-assertions",
                "doc://com.apple.xctest/documentation/XCTest/nsexception-assertions",
                "doc://com.apple.xctest/documentation/XCTest/expected-failures",
                "doc://com.apple.xctest/documentation/XCTest/methods-for-skipping-tests"
              ],
              "title": "Test assertions"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/xctest/unconditional-test-failures"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/xctest/unconditional-test-failures"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
