{
  "abstract": [
    {
      "text": "Data from a test method’s execution, such as a file, image, screenshot, data blob, or ZIP file.",
      "type": "text"
    }
  ],
  "diffAvailability": {
    "major": {
      "change": "modified",
      "platform": "Xcode",
      "versions": [
        "16.0",
        "16.3 beta 2"
      ]
    },
    "minor": {
      "change": "modified",
      "platform": "Xcode",
      "versions": [
        "16.2",
        "16.3 beta 2"
      ]
    }
  },
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.xctest/documentation/XCTest"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.xctest/documentation/XCTest/XCTAttachment"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(cs)XCTAttachment",
    "fragments": [
      {
        "kind": "keyword",
        "text": "class"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "XCTAttachment"
      }
    ],
    "modules": [
      {
        "name": "XCTest"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "XCTAttachment"
      }
    ],
    "role": "symbol",
    "roleHeading": "Class",
    "symbolKind": "class",
    "title": "XCTAttachment"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "class"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "XCTAttachment"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "kind": "mentions",
      "mentions": [
        "doc://com.apple.xctest/documentation/XCTest/adding-attachments-to-tests-activities-and-issues"
      ]
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/XCUIAutomation/XCUIScreenshot": {
      "abstract": [
        {
          "text": "A captured image of a screen, app, or UI element state.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@"
        },
        {
          "kind": "attribute",
          "preciseIdentifier": "s:ScM",
          "text": "MainActor"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "XCUIScreenshot"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/XCUIAutomation/XCUIScreenshot",
      "kind": "symbol",
      "role": "symbol",
      "title": "XCUIScreenshot",
      "type": "topic",
      "url": "/documentation/XCUIAutomation/XCUIScreenshot"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.xctest/documentation/XCTest": {
      "abstract": [
        {
          "text": "Create and run unit tests, performance tests, and UI tests for your Xcode project.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.xctest/documentation/XCTest",
      "kind": "symbol",
      "role": "collection",
      "title": "XCTest",
      "type": "topic",
      "url": "/documentation/xctest"
    },
    "doc://com.apple.xctest/documentation/XCTest/XCTAttachment": {
      "abstract": [
        {
          "text": "Data from a test method’s execution, such as a file, image, screenshot, data blob, or ZIP file.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "XCTAttachment"
        }
      ],
      "identifier": "doc://com.apple.xctest/documentation/XCTest/XCTAttachment",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "XCTAttachment"
        }
      ],
      "role": "symbol",
      "title": "XCTAttachment",
      "type": "topic",
      "url": "/documentation/xctest/xctattachment"
    },
    "doc://com.apple.xctest/documentation/XCTest/XCTAttachment/ImageQuality": {
      "abstract": [
        {
          "text": "Compression quality options for image-based attachments.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ImageQuality"
        }
      ],
      "identifier": "doc://com.apple.xctest/documentation/XCTest/XCTAttachment/ImageQuality",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ImageQuality"
        }
      ],
      "role": "symbol",
      "title": "XCTAttachment.ImageQuality",
      "type": "topic",
      "url": "/documentation/xctest/xctattachment/imagequality"
    },
    "doc://com.apple.xctest/documentation/XCTest/XCTAttachment/Lifetime-swift.enum": {
      "abstract": [
        {
          "text": "The possible lifetime values for a test attachment.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Lifetime"
        }
      ],
      "identifier": "doc://com.apple.xctest/documentation/XCTest/XCTAttachment/Lifetime-swift.enum",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "Lifetime"
        }
      ],
      "role": "symbol",
      "title": "XCTAttachment.Lifetime",
      "type": "topic",
      "url": "/documentation/xctest/xctattachment/lifetime-swift.enum"
    },
    "doc://com.apple.xctest/documentation/XCTest/XCTAttachment/attachmentWithUniformTypeIdentifier:name:payload:userInfo:": {
      "abstract": [
        {
          "text": "Creates an attachment containing the provided data payload, optionally with a custom UTI, name, and user-provided metadata dictionary.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "+ "
        },
        {
          "kind": "identifier",
          "text": "attachmentWithUniformTypeIdentifier:name:payload:userInfo:"
        }
      ],
      "identifier": "doc://com.apple.xctest/documentation/XCTest/XCTAttachment/attachmentWithUniformTypeIdentifier:name:payload:userInfo:",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "attachmentWithUniformTypeIdentifier:name:payload:userInfo:"
        }
      ],
      "role": "symbol",
      "title": "attachmentWithUniformTypeIdentifier:name:payload:userInfo:",
      "type": "topic",
      "url": "/documentation/xctest/xctattachment/attachmentwithuniformtypeidentifier:name:payload:userinfo:"
    },
    "doc://com.apple.xctest/documentation/XCTest/XCTAttachment/init(archivableObject:)": {
      "abstract": [
        {
          "text": "Creates an attachment from an object that conforms to ",
          "type": "text"
        },
        {
          "code": "NSSecureCoding",
          "type": "codeVoice"
        },
        {
          "text": ".",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "convenience"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "archivableObject"
        },
        {
          "kind": "text",
          "text": ": any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(pl)NSSecureCoding",
          "text": "NSSecureCoding"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.xctest/documentation/XCTest/XCTAttachment/init(archivableObject:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "attachmentWithArchivableObject:"
        }
      ],
      "role": "symbol",
      "title": "init(archivableObject:)",
      "type": "topic",
      "url": "/documentation/xctest/xctattachment/init(archivableobject:)"
    },
    "doc://com.apple.xctest/documentation/XCTest/XCTAttachment/init(archivableObject:uniformTypeIdentifier:)": {
      "abstract": [
        {
          "text": "Creates an attachment from an object that conforms to ",
          "type": "text"
        },
        {
          "code": "NSSecureCoding",
          "type": "codeVoice"
        },
        {
          "text": ", with a custom UTI.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "convenience"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "archivableObject"
        },
        {
          "kind": "text",
          "text": ": any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(pl)NSSecureCoding",
          "text": "NSSecureCoding"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "uniformTypeIdentifier"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.xctest/documentation/XCTest/XCTAttachment/init(archivableObject:uniformTypeIdentifier:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "attachmentWithArchivableObject:uniformTypeIdentifier:"
        }
      ],
      "role": "symbol",
      "title": "init(archivableObject:uniformTypeIdentifier:)",
      "type": "topic",
      "url": "/documentation/xctest/xctattachment/init(archivableobject:uniformtypeidentifier:)"
    },
    "doc://com.apple.xctest/documentation/XCTest/XCTAttachment/init(compressedContentsOfDirectoryAtURL:)": {
      "abstract": [
        {
          "text": "Creates an attachment containing a zipped archive of an existing directory on disk.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "convenience"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "compressedContentsOfDirectoryAtURL"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10Foundation3URLV",
          "text": "URL"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.xctest/documentation/XCTest/XCTAttachment/init(compressedContentsOfDirectoryAtURL:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "attachmentWithCompressedContentsOfDirectoryAtURL:"
        }
      ],
      "role": "symbol",
      "title": "init(compressedContentsOfDirectoryAtURL:)",
      "type": "topic",
      "url": "/documentation/xctest/xctattachment/init(compressedcontentsofdirectoryaturl:)"
    },
    "doc://com.apple.xctest/documentation/XCTest/XCTAttachment/init(contentsOfFileAtURL:)": {
      "abstract": [
        {
          "text": "Creates an attachment from the contents of an existing file on disk.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "convenience"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "contentsOfFileAtURL"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10Foundation3URLV",
          "text": "URL"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.xctest/documentation/XCTest/XCTAttachment/init(contentsOfFileAtURL:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "attachmentWithContentsOfFileAtURL:"
        }
      ],
      "role": "symbol",
      "title": "init(contentsOfFileAtURL:)",
      "type": "topic",
      "url": "/documentation/xctest/xctattachment/init(contentsoffileaturl:)"
    },
    "doc://com.apple.xctest/documentation/XCTest/XCTAttachment/init(contentsOfFileAtURL:uniformTypeIdentifier:)": {
      "abstract": [
        {
          "text": "Creates an attachment from the contents of an existing file on disk, with a custom UTI.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "convenience"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "contentsOfFileAtURL"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10Foundation3URLV",
          "text": "URL"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "uniformTypeIdentifier"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.xctest/documentation/XCTest/XCTAttachment/init(contentsOfFileAtURL:uniformTypeIdentifier:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "attachmentWithContentsOfFileAtURL:uniformTypeIdentifier:"
        }
      ],
      "role": "symbol",
      "title": "init(contentsOfFileAtURL:uniformTypeIdentifier:)",
      "type": "topic",
      "url": "/documentation/xctest/xctattachment/init(contentsoffileaturl:uniformtypeidentifier:)"
    },
    "doc://com.apple.xctest/documentation/XCTest/XCTAttachment/init(data:)": {
      "abstract": [
        {
          "text": "Creates an attachment containing the provided data payload.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "convenience"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "data"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10Foundation4DataV",
          "text": "Data"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.xctest/documentation/XCTest/XCTAttachment/init(data:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "attachmentWithData:"
        }
      ],
      "role": "symbol",
      "title": "init(data:)",
      "type": "topic",
      "url": "/documentation/xctest/xctattachment/init(data:)"
    },
    "doc://com.apple.xctest/documentation/XCTest/XCTAttachment/init(data:uniformTypeIdentifier:)": {
      "abstract": [
        {
          "text": "Creates an attachment containing the provided data payload, with a custom UTI.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "convenience"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "data"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10Foundation4DataV",
          "text": "Data"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "uniformTypeIdentifier"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.xctest/documentation/XCTest/XCTAttachment/init(data:uniformTypeIdentifier:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "attachmentWithData:uniformTypeIdentifier:"
        }
      ],
      "role": "symbol",
      "title": "init(data:uniformTypeIdentifier:)",
      "type": "topic",
      "url": "/documentation/xctest/xctattachment/init(data:uniformtypeidentifier:)"
    },
    "doc://com.apple.xctest/documentation/XCTest/XCTAttachment/init(image:)": {
      "abstract": [
        {
          "text": "Creates an attachment containing a PNG representation of the provided image.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "convenience"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "image"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UIImage",
          "text": "UIImage"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.xctest/documentation/XCTest/XCTAttachment/init(image:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "attachmentWithImage:"
        }
      ],
      "role": "symbol",
      "title": "init(image:)",
      "type": "topic",
      "url": "/documentation/xctest/xctattachment/init(image:)"
    },
    "doc://com.apple.xctest/documentation/XCTest/XCTAttachment/init(image:quality:)": {
      "abstract": [
        {
          "text": "Creates an attachment containing a representation of the provided image at the requested image quality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "convenience"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "image"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UIImage",
          "text": "UIImage"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "quality"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)XCTAttachment",
          "text": "XCTAttachment"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@XCTImageQuality",
          "text": "ImageQuality"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.xctest/documentation/XCTest/XCTAttachment/init(image:quality:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "attachmentWithImage:quality:"
        }
      ],
      "role": "symbol",
      "title": "init(image:quality:)",
      "type": "topic",
      "url": "/documentation/xctest/xctattachment/init(image:quality:)"
    },
    "doc://com.apple.xctest/documentation/XCTest/XCTAttachment/init(plistObject:)": {
      "abstract": [
        {
          "text": "Creates an attachment from an object that can be represented in an XML property list.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "convenience"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "plistObject"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "keyword",
          "text": "Any"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.xctest/documentation/XCTest/XCTAttachment/init(plistObject:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "attachmentWithPlistObject:"
        }
      ],
      "role": "symbol",
      "title": "init(plistObject:)",
      "type": "topic",
      "url": "/documentation/xctest/xctattachment/init(plistobject:)"
    },
    "doc://com.apple.xctest/documentation/XCTest/XCTAttachment/init(screenshot:)": {
      "abstract": [
        {
          "text": "Creates an attachment containing a PNG representation of the provided screenshot.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "convenience"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "screenshot"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)XCUIScreenshot",
          "text": "XCUIScreenshot"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.xctest/documentation/XCTest/XCTAttachment/init(screenshot:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "attachmentWithScreenshot:"
        }
      ],
      "role": "symbol",
      "title": "init(screenshot:)",
      "type": "topic",
      "url": "/documentation/xctest/xctattachment/init(screenshot:)"
    },
    "doc://com.apple.xctest/documentation/XCTest/XCTAttachment/init(screenshot:quality:)": {
      "abstract": [
        {
          "text": "Creates an attachment containing a representation of the provided screenshot at the requested image quality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "convenience"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "screenshot"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)XCUIScreenshot",
          "text": "XCUIScreenshot"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "quality"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)XCTAttachment",
          "text": "XCTAttachment"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@XCTImageQuality",
          "text": "ImageQuality"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.xctest/documentation/XCTest/XCTAttachment/init(screenshot:quality:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "attachmentWithScreenshot:quality:"
        }
      ],
      "role": "symbol",
      "title": "init(screenshot:quality:)",
      "type": "topic",
      "url": "/documentation/xctest/xctattachment/init(screenshot:quality:)"
    },
    "doc://com.apple.xctest/documentation/XCTest/XCTAttachment/init(string:)": {
      "abstract": [
        {
          "text": "Creates an attachment containing the provided string.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "convenience"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "string"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.xctest/documentation/XCTest/XCTAttachment/init(string:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "attachmentWithString:"
        }
      ],
      "role": "symbol",
      "title": "init(string:)",
      "type": "topic",
      "url": "/documentation/xctest/xctattachment/init(string:)"
    },
    "doc://com.apple.xctest/documentation/XCTest/XCTAttachment/init(uniformTypeIdentifier:name:payload:userInfo:)": {
      "abstract": [
        {
          "text": "Creates an attachment containing the provided data payload, optionally with a custom UTI, name, and user-provided metadata dictionary.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "uniformTypeIdentifier"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": "?, "
        },
        {
          "kind": "externalParam",
          "text": "name"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": "?, "
        },
        {
          "kind": "externalParam",
          "text": "payload"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10Foundation4DataV",
          "text": "Data"
        },
        {
          "kind": "text",
          "text": "?, "
        },
        {
          "kind": "externalParam",
          "text": "userInfo"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s11AnyHashableV",
          "text": "AnyHashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "keyword",
          "text": "Any"
        },
        {
          "kind": "text",
          "text": "]?)"
        }
      ],
      "identifier": "doc://com.apple.xctest/documentation/XCTest/XCTAttachment/init(uniformTypeIdentifier:name:payload:userInfo:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "initWithUniformTypeIdentifier:name:payload:userInfo:"
        }
      ],
      "role": "symbol",
      "title": "init(uniformTypeIdentifier:name:payload:userInfo:)",
      "type": "topic",
      "url": "/documentation/xctest/xctattachment/init(uniformtypeidentifier:name:payload:userinfo:)"
    },
    "doc://com.apple.xctest/documentation/XCTest/XCTAttachment/lifetime-swift.property": {
      "abstract": [
        {
          "text": "Indicates whether the attachment is kept or discarded when its associated test passes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "lifetime"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)XCTAttachment",
          "text": "XCTAttachment"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@XCTAttachmentLifetime",
          "text": "Lifetime"
        }
      ],
      "identifier": "doc://com.apple.xctest/documentation/XCTest/XCTAttachment/lifetime-swift.property",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "lifetime"
        }
      ],
      "role": "symbol",
      "title": "lifetime",
      "type": "topic",
      "url": "/documentation/xctest/xctattachment/lifetime-swift.property"
    },
    "doc://com.apple.xctest/documentation/XCTest/XCTAttachment/name": {
      "abstract": [
        {
          "text": "The attachment’s name, or ",
          "type": "text"
        },
        {
          "code": "nil",
          "type": "codeVoice"
        },
        {
          "text": " if the attachment is unnamed.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "name"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.xctest/documentation/XCTest/XCTAttachment/name",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "name"
        }
      ],
      "role": "symbol",
      "title": "name",
      "type": "topic",
      "url": "/documentation/xctest/xctattachment/name"
    },
    "doc://com.apple.xctest/documentation/XCTest/XCTAttachment/uniformTypeIdentifier": {
      "abstract": [
        {
          "text": "The Uniform Type Identifier (UTI) of the data represented by the attachment.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "uniformTypeIdentifier"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.xctest/documentation/XCTest/XCTAttachment/uniformTypeIdentifier",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "uniformTypeIdentifier"
        }
      ],
      "role": "symbol",
      "title": "uniformTypeIdentifier",
      "type": "topic",
      "url": "/documentation/xctest/xctattachment/uniformtypeidentifier"
    },
    "doc://com.apple.xctest/documentation/XCTest/XCTAttachment/userInfo": {
      "abstract": [
        {
          "text": "User-provided metadata associated with the attachment.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "userInfo"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s11AnyHashableV",
          "text": "AnyHashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "keyword",
          "text": "Any"
        },
        {
          "kind": "text",
          "text": "]?"
        }
      ],
      "identifier": "doc://com.apple.xctest/documentation/XCTest/XCTAttachment/userInfo",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "userInfo"
        }
      ],
      "role": "symbol",
      "title": "userInfo",
      "type": "topic",
      "url": "/documentation/xctest/xctattachment/userinfo"
    },
    "doc://com.apple.xctest/documentation/XCTest/adding-attachments-to-tests-activities-and-issues": {
      "abstract": [
        {
          "text": "Use attachments to store a test’s output data for later analysis.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.xctest/documentation/XCTest/adding-attachments-to-tests-activities-and-issues",
      "kind": "article",
      "role": "article",
      "title": "Adding Attachments to Tests, Activities, and Issues",
      "type": "topic",
      "url": "/documentation/xctest/adding-attachments-to-tests-activities-and-issues"
    },
    "doc://com.externally.resolved.symbol/c:objc(cs)NSObject": {
      "abstract": [
        {
          "text": "The root class of most Objective-C class hierarchies, from which subclasses inherit a basic interface to the runtime system and the ability to behave as Objective-C objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "class "
        },
        {
          "kind": "identifier",
          "text": "NSObject"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSObject",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSObject",
      "type": "topic",
      "url": "/documentation/objectivec/nsobject"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)NSCoding": {
      "abstract": [
        {
          "text": "A protocol that enables an object to be encoded and decoded for archiving and distribution.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "protocol "
        },
        {
          "kind": "identifier",
          "text": "NSCoding"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSCoding",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSCoding",
      "type": "topic",
      "url": "/documentation/foundation/nscoding"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)NSObject": {
      "abstract": [
        {
          "text": "The group of methods that are fundamental to all Objective-C objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "protocol "
        },
        {
          "kind": "identifier",
          "text": "NSObjectProtocol"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSObject",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSObjectProtocol",
      "type": "topic",
      "url": "/documentation/objectivec/nsobjectprotocol"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)NSSecureCoding": {
      "abstract": [
        {
          "text": "A protocol that enables encoding and decoding in a manner that is robust against object substitution attacks.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "protocol "
        },
        {
          "kind": "identifier",
          "text": "NSSecureCoding"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSSecureCoding",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSSecureCoding",
      "type": "topic",
      "url": "/documentation/foundation/nssecurecoding"
    },
    "doc://com.externally.resolved.symbol/s:SH": {
      "abstract": [
        {
          "text": "A type that can be hashed into a `Hasher` to produce an integer hash value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Hashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SQ",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SH",
      "kind": "symbol",
      "role": "symbol",
      "title": "Hashable",
      "type": "topic",
      "url": "/documentation/Swift/Hashable"
    },
    "doc://com.externally.resolved.symbol/s:SQ": {
      "abstract": [
        {
          "text": "A type that can be compared for value equality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SQ",
      "kind": "symbol",
      "role": "symbol",
      "title": "Equatable",
      "type": "topic",
      "url": "/documentation/Swift/Equatable"
    },
    "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP": {
      "abstract": [
        {
          "text": "A type with a customized textual representation.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CustomStringConvertible"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CustomStringConvertible",
      "type": "topic",
      "url": "/documentation/Swift/CustomStringConvertible"
    },
    "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP": {
      "abstract": [
        {
          "text": "A type with a customized textual representation suitable for debugging purposes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CustomDebugStringConvertible"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CustomDebugStringConvertible",
      "type": "topic",
      "url": "/documentation/Swift/CustomDebugStringConvertible"
    },
    "doc://com.externally.resolved.symbol/s:s7CVarArgP": {
      "abstract": [
        {
          "text": "A type whose instances can be encoded, and appropriately passed, as elements of a C `va_list`.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CVarArg"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s7CVarArgP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CVarArg",
      "type": "topic",
      "url": "/documentation/Swift/CVarArg"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/c:objc(cs)NSObject"
      ],
      "kind": "relationships",
      "title": "Inherits From",
      "type": "inheritsFrom"
    },
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:s7CVarArgP",
        "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP",
        "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP",
        "doc://com.externally.resolved.symbol/s:SQ",
        "doc://com.externally.resolved.symbol/s:SH",
        "doc://com.externally.resolved.symbol/c:objc(pl)NSCoding",
        "doc://com.externally.resolved.symbol/c:objc(pl)NSObject",
        "doc://com.externally.resolved.symbol/c:objc(pl)NSSecureCoding"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Attachments",
      "generated": true,
      "identifiers": [
        "doc://com.apple.xctest/documentation/XCTest/adding-attachments-to-tests-activities-and-issues"
      ],
      "title": "Attachments"
    }
  ],
  "topicSections": [
    {
      "anchor": "Creating-Attachments-from-Data",
      "identifiers": [
        "doc://com.apple.xctest/documentation/XCTest/XCTAttachment/init(data:)",
        "doc://com.apple.xctest/documentation/XCTest/XCTAttachment/init(data:uniformTypeIdentifier:)",
        "doc://com.apple.xctest/documentation/XCTest/XCTAttachment/init(uniformTypeIdentifier:name:payload:userInfo:)"
      ],
      "title": "Creating Attachments from Data"
    },
    {
      "anchor": "Creating-Attachments-from-Files-and-Folders",
      "identifiers": [
        "doc://com.apple.xctest/documentation/XCTest/XCTAttachment/init(contentsOfFileAtURL:)",
        "doc://com.apple.xctest/documentation/XCTest/XCTAttachment/init(contentsOfFileAtURL:uniformTypeIdentifier:)",
        "doc://com.apple.xctest/documentation/XCTest/XCTAttachment/init(compressedContentsOfDirectoryAtURL:)"
      ],
      "title": "Creating Attachments from Files and Folders"
    },
    {
      "anchor": "Creating-Attachments-from-Images-and-Screenshots",
      "identifiers": [
        "doc://com.apple.xctest/documentation/XCTest/XCTAttachment/init(image:)",
        "doc://com.apple.xctest/documentation/XCTest/XCTAttachment/init(image:quality:)",
        "doc://com.apple.xctest/documentation/XCTest/XCTAttachment/init(screenshot:)",
        "doc://com.apple.xctest/documentation/XCTest/XCTAttachment/init(screenshot:quality:)",
        "doc://com.apple.documentation/documentation/XCUIAutomation/XCUIScreenshot",
        "doc://com.apple.xctest/documentation/XCTest/XCTAttachment/ImageQuality"
      ],
      "title": "Creating Attachments from Images and Screenshots"
    },
    {
      "anchor": "Creating-Attachments-from-Objects",
      "identifiers": [
        "doc://com.apple.xctest/documentation/XCTest/XCTAttachment/init(plistObject:)",
        "doc://com.apple.xctest/documentation/XCTest/XCTAttachment/init(archivableObject:)",
        "doc://com.apple.xctest/documentation/XCTest/XCTAttachment/init(archivableObject:uniformTypeIdentifier:)"
      ],
      "title": "Creating Attachments from Objects"
    },
    {
      "anchor": "Creating-Attachments-from-Strings",
      "identifiers": [
        "doc://com.apple.xctest/documentation/XCTest/XCTAttachment/init(string:)"
      ],
      "title": "Creating Attachments from Strings"
    },
    {
      "anchor": "Setting-an-Attachments-Lifetime",
      "identifiers": [
        "doc://com.apple.xctest/documentation/XCTest/XCTAttachment/lifetime-swift.property",
        "doc://com.apple.xctest/documentation/XCTest/XCTAttachment/Lifetime-swift.enum"
      ],
      "title": "Setting an Attachment’s Lifetime"
    },
    {
      "anchor": "Attachment-Metadata",
      "identifiers": [
        "doc://com.apple.xctest/documentation/XCTest/XCTAttachment/name",
        "doc://com.apple.xctest/documentation/XCTest/XCTAttachment/uniformTypeIdentifier",
        "doc://com.apple.xctest/documentation/XCTest/XCTAttachment/userInfo"
      ],
      "title": "Attachment Metadata"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "add",
          "path": "/metadata/platforms",
          "value": null
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Class"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "XCTAttachment"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "class"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "XCTAttachment"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "XCTAttachment"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.xctest/documentation/XCTest"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Creating-Attachments-from-Data",
              "identifiers": [
                "doc://com.apple.xctest/documentation/XCTest/XCTAttachment/init(data:)",
                "doc://com.apple.xctest/documentation/XCTest/XCTAttachment/init(data:uniformTypeIdentifier:)",
                "doc://com.apple.xctest/documentation/XCTest/XCTAttachment/init(uniformTypeIdentifier:name:payload:userInfo:)",
                "doc://com.apple.xctest/documentation/XCTest/XCTAttachment/attachmentWithUniformTypeIdentifier:name:payload:userInfo:"
              ],
              "title": "Creating Attachments from Data"
            },
            {
              "anchor": "Creating-Attachments-from-Files-and-Folders",
              "identifiers": [
                "doc://com.apple.xctest/documentation/XCTest/XCTAttachment/init(contentsOfFileAtURL:)",
                "doc://com.apple.xctest/documentation/XCTest/XCTAttachment/init(contentsOfFileAtURL:uniformTypeIdentifier:)",
                "doc://com.apple.xctest/documentation/XCTest/XCTAttachment/init(compressedContentsOfDirectoryAtURL:)"
              ],
              "title": "Creating Attachments from Files and Folders"
            },
            {
              "anchor": "Creating-Attachments-from-Images-and-Screenshots",
              "identifiers": [
                "doc://com.apple.xctest/documentation/XCTest/XCTAttachment/init(image:)",
                "doc://com.apple.xctest/documentation/XCTest/XCTAttachment/init(image:quality:)",
                "doc://com.apple.xctest/documentation/XCTest/XCTAttachment/init(screenshot:)",
                "doc://com.apple.xctest/documentation/XCTest/XCTAttachment/init(screenshot:quality:)",
                "doc://com.apple.documentation/documentation/XCUIAutomation/XCUIScreenshot",
                "doc://com.apple.xctest/documentation/XCTest/XCTAttachment/ImageQuality"
              ],
              "title": "Creating Attachments from Images and Screenshots"
            },
            {
              "anchor": "Creating-Attachments-from-Objects",
              "identifiers": [
                "doc://com.apple.xctest/documentation/XCTest/XCTAttachment/init(plistObject:)",
                "doc://com.apple.xctest/documentation/XCTest/XCTAttachment/init(archivableObject:)",
                "doc://com.apple.xctest/documentation/XCTest/XCTAttachment/init(archivableObject:uniformTypeIdentifier:)"
              ],
              "title": "Creating Attachments from Objects"
            },
            {
              "anchor": "Creating-Attachments-from-Strings",
              "identifiers": [
                "doc://com.apple.xctest/documentation/XCTest/XCTAttachment/init(string:)"
              ],
              "title": "Creating Attachments from Strings"
            },
            {
              "anchor": "Setting-an-Attachments-Lifetime",
              "identifiers": [
                "doc://com.apple.xctest/documentation/XCTest/XCTAttachment/lifetime-swift.property",
                "doc://com.apple.xctest/documentation/XCTest/XCTAttachment/Lifetime-swift.enum"
              ],
              "title": "Setting an Attachment’s Lifetime"
            },
            {
              "anchor": "Attachment-Metadata",
              "identifiers": [
                "doc://com.apple.xctest/documentation/XCTest/XCTAttachment/name",
                "doc://com.apple.xctest/documentation/XCTest/XCTAttachment/uniformTypeIdentifier",
                "doc://com.apple.xctest/documentation/XCTest/XCTAttachment/userInfo"
              ],
              "title": "Attachment Metadata"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": [
            {
              "identifiers": [
                "doc://com.externally.resolved.symbol/c:objc(cs)NSObject"
              ],
              "kind": "relationships",
              "title": "Inherits From",
              "type": "inheritsFrom"
            },
            {
              "identifiers": [
                "doc://com.externally.resolved.symbol/c:objc(pl)NSSecureCoding"
              ],
              "kind": "relationships",
              "title": "Conforms To",
              "type": "conformsTo"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Attachments",
              "generated": true,
              "identifiers": [
                "doc://com.apple.xctest/documentation/XCTest/adding-attachments-to-tests-activities-and-issues"
              ],
              "title": "Attachments"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "@interface"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "XCTAttachment"
                  },
                  {
                    "kind": "text",
                    "text": " : "
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSObject",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(cs)NSObject",
                    "text": "NSObject"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCTAttachment~1uniformTypeIdentifier/title",
          "value": "uniformTypeIdentifier"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCTAttachment~1uniformTypeIdentifier/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "uniformTypeIdentifier"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1XCUIAutomation~1XCUIScreenshot/fragments",
          "value": [
            {
              "kind": "keyword",
              "text": "@interface"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "XCUIScreenshot"
            },
            {
              "kind": "text",
              "text": " : "
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)NSObject",
              "text": "NSObject"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCTAttachment~1name/title",
          "value": "name"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCTAttachment~1name/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "name"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCTAttachment~1init(image:)/title",
          "value": "attachmentWithImage:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCTAttachment~1init(image:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "+ "
            },
            {
              "kind": "identifier",
              "text": "attachmentWithImage:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCTAttachment~1init(contentsOfFileAtURL:)/title",
          "value": "attachmentWithContentsOfFileAtURL:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCTAttachment~1init(contentsOfFileAtURL:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "+ "
            },
            {
              "kind": "identifier",
              "text": "attachmentWithContentsOfFileAtURL:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCTAttachment~1init(screenshot:quality:)/title",
          "value": "attachmentWithScreenshot:quality:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCTAttachment~1init(screenshot:quality:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "+ "
            },
            {
              "kind": "identifier",
              "text": "attachmentWithScreenshot:quality:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:objc(pl)NSObject/title",
          "value": "NSObject"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCTAttachment~1init(plistObject:)/title",
          "value": "attachmentWithPlistObject:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCTAttachment~1init(plistObject:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "+ "
            },
            {
              "kind": "identifier",
              "text": "attachmentWithPlistObject:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCTAttachment~1init(archivableObject:)/title",
          "value": "attachmentWithArchivableObject:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCTAttachment~1init(archivableObject:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "+ "
            },
            {
              "kind": "identifier",
              "text": "attachmentWithArchivableObject:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCTAttachment~1init(image:quality:)/title",
          "value": "attachmentWithImage:quality:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCTAttachment~1init(image:quality:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "+ "
            },
            {
              "kind": "identifier",
              "text": "attachmentWithImage:quality:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCTAttachment~1init(string:)/title",
          "value": "attachmentWithString:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCTAttachment~1init(string:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "+ "
            },
            {
              "kind": "identifier",
              "text": "attachmentWithString:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCTAttachment/title",
          "value": "XCTAttachment"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCTAttachment/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "XCTAttachment"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCTAttachment/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "XCTAttachment"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCTAttachment~1init(archivableObject:uniformTypeIdentifier:)/title",
          "value": "attachmentWithArchivableObject:uniformTypeIdentifier:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCTAttachment~1init(archivableObject:uniformTypeIdentifier:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "+ "
            },
            {
              "kind": "identifier",
              "text": "attachmentWithArchivableObject:uniformTypeIdentifier:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCTAttachment~1init(uniformTypeIdentifier:name:payload:userInfo:)/title",
          "value": "initWithUniformTypeIdentifier:name:payload:userInfo:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCTAttachment~1init(uniformTypeIdentifier:name:payload:userInfo:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "initWithUniformTypeIdentifier:name:payload:userInfo:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCTAttachment~1lifetime-swift.property/title",
          "value": "lifetime"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCTAttachment~1lifetime-swift.property/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "lifetime"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCTAttachment~1init(screenshot:)/title",
          "value": "attachmentWithScreenshot:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCTAttachment~1init(screenshot:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "+ "
            },
            {
              "kind": "identifier",
              "text": "attachmentWithScreenshot:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCTAttachment~1init(data:uniformTypeIdentifier:)/title",
          "value": "attachmentWithData:uniformTypeIdentifier:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCTAttachment~1init(data:uniformTypeIdentifier:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "+ "
            },
            {
              "kind": "identifier",
              "text": "attachmentWithData:uniformTypeIdentifier:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCTAttachment~1Lifetime-swift.enum/title",
          "value": "XCTAttachmentLifetime"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCTAttachment~1Lifetime-swift.enum/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "XCTAttachmentLifetime"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCTAttachment~1Lifetime-swift.enum/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "XCTAttachmentLifetime"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCTAttachment~1init(data:)/title",
          "value": "attachmentWithData:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCTAttachment~1init(data:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "+ "
            },
            {
              "kind": "identifier",
              "text": "attachmentWithData:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCTAttachment~1init(compressedContentsOfDirectoryAtURL:)/title",
          "value": "attachmentWithCompressedContentsOfDirectoryAtURL:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCTAttachment~1init(compressedContentsOfDirectoryAtURL:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "+ "
            },
            {
              "kind": "identifier",
              "text": "attachmentWithCompressedContentsOfDirectoryAtURL:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCTAttachment~1userInfo/title",
          "value": "userInfo"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCTAttachment~1userInfo/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "userInfo"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCTAttachment~1ImageQuality/title",
          "value": "XCTImageQuality"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCTAttachment~1ImageQuality/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "XCTImageQuality"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCTAttachment~1ImageQuality/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "XCTImageQuality"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCTAttachment~1init(contentsOfFileAtURL:uniformTypeIdentifier:)/title",
          "value": "attachmentWithContentsOfFileAtURL:uniformTypeIdentifier:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCTAttachment~1init(contentsOfFileAtURL:uniformTypeIdentifier:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "+ "
            },
            {
              "kind": "identifier",
              "text": "attachmentWithContentsOfFileAtURL:uniformTypeIdentifier:"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/xctest/xctattachment"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/xctest/xctattachment"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
