{
  "abstract": [
    {
      "text": "An expected outcome in an asynchronous test.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.xctest/documentation/XCTest"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.xctest/documentation/XCTest/XCTestExpectation"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(cs)XCTestExpectation",
    "fragments": [
      {
        "kind": "keyword",
        "text": "class"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "XCTestExpectation"
      }
    ],
    "modules": [
      {
        "name": "XCTest"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "XCTestExpectation"
      }
    ],
    "role": "symbol",
    "roleHeading": "Class",
    "symbolKind": "class",
    "title": "XCTestExpectation"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "class"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "XCTestExpectation"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.xctest/documentation/XCTest": {
      "abstract": [
        {
          "text": "Create and run unit tests, performance tests, and UI tests for your Xcode project.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.xctest/documentation/XCTest",
      "kind": "symbol",
      "role": "collection",
      "title": "XCTest",
      "type": "topic",
      "url": "/documentation/xctest"
    },
    "doc://com.apple.xctest/documentation/XCTest/XCTDarwinNotificationExpectation": {
      "abstract": [
        {
          "text": "An expectation that is fulfilled when an expected Darwin notification is received.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "XCTDarwinNotificationExpectation"
        }
      ],
      "identifier": "doc://com.apple.xctest/documentation/XCTest/XCTDarwinNotificationExpectation",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "XCTDarwinNotificationExpectation"
        }
      ],
      "role": "symbol",
      "title": "XCTDarwinNotificationExpectation",
      "type": "topic",
      "url": "/documentation/xctest/xctdarwinnotificationexpectation"
    },
    "doc://com.apple.xctest/documentation/XCTest/XCTKVOExpectation": {
      "abstract": [
        {
          "text": "An expectation that a specific key-value observing (KVO) condition fulfills.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "XCTKVOExpectation"
        }
      ],
      "identifier": "doc://com.apple.xctest/documentation/XCTest/XCTKVOExpectation",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "XCTKVOExpectation"
        }
      ],
      "role": "symbol",
      "title": "XCTKVOExpectation",
      "type": "topic",
      "url": "/documentation/xctest/xctkvoexpectation"
    },
    "doc://com.apple.xctest/documentation/XCTest/XCTKeyPathExpectation": {
      "abstract": [
        {
          "text": "An expectation that a specific key-value observing (KVO) condition fulfills.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "XCTKeyPathExpectation"
        }
      ],
      "identifier": "doc://com.apple.xctest/documentation/XCTest/XCTKeyPathExpectation",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "XCTKeyPathExpectation"
        }
      ],
      "role": "symbol",
      "title": "XCTKeyPathExpectation",
      "type": "topic",
      "url": "/documentation/xctest/xctkeypathexpectation"
    },
    "doc://com.apple.xctest/documentation/XCTest/XCTNSNotificationExpectation": {
      "abstract": [
        {
          "text": "An expectation that is fulfilled when an expected ",
          "type": "text"
        },
        {
          "code": "NSNotification",
          "type": "codeVoice"
        },
        {
          "text": " is received.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "XCTNSNotificationExpectation"
        }
      ],
      "identifier": "doc://com.apple.xctest/documentation/XCTest/XCTNSNotificationExpectation",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "XCTNSNotificationExpectation"
        }
      ],
      "role": "symbol",
      "title": "XCTNSNotificationExpectation",
      "type": "topic",
      "url": "/documentation/xctest/xctnsnotificationexpectation"
    },
    "doc://com.apple.xctest/documentation/XCTest/XCTNSPredicateExpectation": {
      "abstract": [
        {
          "text": "An expectation that’s fulfilled when an ",
          "type": "text"
        },
        {
          "code": "NSPredicate",
          "type": "codeVoice"
        },
        {
          "text": " is satisfied.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "XCTNSPredicateExpectation"
        }
      ],
      "identifier": "doc://com.apple.xctest/documentation/XCTest/XCTNSPredicateExpectation",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "XCTNSPredicateExpectation"
        }
      ],
      "role": "symbol",
      "title": "XCTNSPredicateExpectation",
      "type": "topic",
      "url": "/documentation/xctest/xctnspredicateexpectation"
    },
    "doc://com.apple.xctest/documentation/XCTest/XCTestExpectation": {
      "abstract": [
        {
          "text": "An expected outcome in an asynchronous test.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "XCTestExpectation"
        }
      ],
      "identifier": "doc://com.apple.xctest/documentation/XCTest/XCTestExpectation",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "XCTestExpectation"
        }
      ],
      "role": "symbol",
      "title": "XCTestExpectation",
      "type": "topic",
      "url": "/documentation/xctest/xctestexpectation"
    },
    "doc://com.apple.xctest/documentation/XCTest/XCTestExpectation/assertForOverFulfill": {
      "abstract": [
        {
          "text": "Indicates that an assertion should be triggered during testing if the expectation is over-fulfilled.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "assertForOverFulfill"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.xctest/documentation/XCTest/XCTestExpectation/assertForOverFulfill",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "assertForOverFulfill"
        }
      ],
      "role": "symbol",
      "title": "assertForOverFulfill",
      "type": "topic",
      "url": "/documentation/xctest/xctestexpectation/assertforoverfulfill"
    },
    "doc://com.apple.xctest/documentation/XCTest/XCTestExpectation/expectationDescription": {
      "abstract": [
        {
          "text": "A human readable string used to describe the expectation in log output and test reports.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "expectationDescription"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.xctest/documentation/XCTest/XCTestExpectation/expectationDescription",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "expectationDescription"
        }
      ],
      "role": "symbol",
      "title": "expectationDescription",
      "type": "topic",
      "url": "/documentation/xctest/xctestexpectation/expectationdescription"
    },
    "doc://com.apple.xctest/documentation/XCTest/XCTestExpectation/expectedFulfillmentCount": {
      "abstract": [
        {
          "text": "The number of times ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.xctest/documentation/XCTest/XCTestExpectation/fulfill()",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " must be called before the expectation is completely fulfilled.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "expectedFulfillmentCount"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.xctest/documentation/XCTest/XCTestExpectation/expectedFulfillmentCount",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "expectedFulfillmentCount"
        }
      ],
      "role": "symbol",
      "title": "expectedFulfillmentCount",
      "type": "topic",
      "url": "/documentation/xctest/xctestexpectation/expectedfulfillmentcount"
    },
    "doc://com.apple.xctest/documentation/XCTest/XCTestExpectation/fulfill()": {
      "abstract": [
        {
          "text": "Marks the expectation as having been met.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "fulfill"
        },
        {
          "kind": "text",
          "text": "()"
        }
      ],
      "identifier": "doc://com.apple.xctest/documentation/XCTest/XCTestExpectation/fulfill()",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "fulfill"
        }
      ],
      "role": "symbol",
      "title": "fulfill()",
      "type": "topic",
      "url": "/documentation/xctest/xctestexpectation/fulfill()"
    },
    "doc://com.apple.xctest/documentation/XCTest/XCTestExpectation/init(description:)": {
      "abstract": [
        {
          "text": "Creates a new ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.xctest/documentation/XCTest/XCTestExpectation",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " with the provided description.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "description"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.xctest/documentation/XCTest/XCTestExpectation/init(description:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "initWithDescription:"
        }
      ],
      "role": "symbol",
      "title": "init(description:)",
      "type": "topic",
      "url": "/documentation/xctest/xctestexpectation/init(description:)"
    },
    "doc://com.apple.xctest/documentation/XCTest/XCTestExpectation/isInverted": {
      "abstract": [
        {
          "text": "Indicates that the expectation is not intended to happen.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "isInverted"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.xctest/documentation/XCTest/XCTestExpectation/isInverted",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "inverted"
        }
      ],
      "role": "symbol",
      "title": "isInverted",
      "type": "topic",
      "url": "/documentation/xctest/xctestexpectation/isinverted"
    },
    "doc://com.externally.resolved.symbol/c:objc(cs)NSObject": {
      "abstract": [
        {
          "text": "The root class of most Objective-C class hierarchies, from which subclasses inherit a basic interface to the runtime system and the ability to behave as Objective-C objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "class "
        },
        {
          "kind": "identifier",
          "text": "NSObject"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSObject",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSObject",
      "type": "topic",
      "url": "/documentation/objectivec/nsobject"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)NSObject": {
      "abstract": [
        {
          "text": "The group of methods that are fundamental to all Objective-C objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "protocol "
        },
        {
          "kind": "identifier",
          "text": "NSObjectProtocol"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSObject",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSObjectProtocol",
      "type": "topic",
      "url": "/documentation/objectivec/nsobjectprotocol"
    },
    "doc://com.externally.resolved.symbol/s:SH": {
      "abstract": [
        {
          "text": "A type that can be hashed into a `Hasher` to produce an integer hash value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Hashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SQ",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SH",
      "kind": "symbol",
      "role": "symbol",
      "title": "Hashable",
      "type": "topic",
      "url": "/documentation/Swift/Hashable"
    },
    "doc://com.externally.resolved.symbol/s:SQ": {
      "abstract": [
        {
          "text": "A type that can be compared for value equality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SQ",
      "kind": "symbol",
      "role": "symbol",
      "title": "Equatable",
      "type": "topic",
      "url": "/documentation/Swift/Equatable"
    },
    "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP": {
      "abstract": [
        {
          "text": "A type with a customized textual representation.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CustomStringConvertible"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CustomStringConvertible",
      "type": "topic",
      "url": "/documentation/Swift/CustomStringConvertible"
    },
    "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP": {
      "abstract": [
        {
          "text": "A type with a customized textual representation suitable for debugging purposes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CustomDebugStringConvertible"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CustomDebugStringConvertible",
      "type": "topic",
      "url": "/documentation/Swift/CustomDebugStringConvertible"
    },
    "doc://com.externally.resolved.symbol/s:s7CVarArgP": {
      "abstract": [
        {
          "text": "A type whose instances can be encoded, and appropriately passed, as elements of a C `va_list`.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CVarArg"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s7CVarArgP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CVarArg",
      "type": "topic",
      "url": "/documentation/Swift/CVarArg"
    },
    "doc://com.externally.resolved.symbol/s:s8SendableP": {
      "abstract": [
        {
          "text": "A thread-safe type whose values can be shared across arbitrary concurrent contexts without introducing a risk of data races.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Sendable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s8SendableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "Sendable",
      "type": "topic",
      "url": "/documentation/Swift/Sendable"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/c:objc(cs)NSObject"
      ],
      "kind": "relationships",
      "title": "Inherits From",
      "type": "inheritsFrom"
    },
    {
      "identifiers": [
        "doc://com.apple.xctest/documentation/XCTest/XCTDarwinNotificationExpectation",
        "doc://com.apple.xctest/documentation/XCTest/XCTKVOExpectation",
        "doc://com.apple.xctest/documentation/XCTest/XCTKeyPathExpectation",
        "doc://com.apple.xctest/documentation/XCTest/XCTNSNotificationExpectation",
        "doc://com.apple.xctest/documentation/XCTest/XCTNSPredicateExpectation"
      ],
      "kind": "relationships",
      "title": "Inherited By",
      "type": "inheritedBy"
    },
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:s7CVarArgP",
        "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP",
        "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP",
        "doc://com.externally.resolved.symbol/s:SQ",
        "doc://com.externally.resolved.symbol/s:SH",
        "doc://com.externally.resolved.symbol/c:objc(pl)NSObject",
        "doc://com.externally.resolved.symbol/s:s8SendableP"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "topicSections": [
    {
      "anchor": "Creating-Expectations",
      "identifiers": [
        "doc://com.apple.xctest/documentation/XCTest/XCTestExpectation/init(description:)",
        "doc://com.apple.xctest/documentation/XCTest/XCTestExpectation/expectationDescription"
      ],
      "title": "Creating Expectations"
    },
    {
      "anchor": "Fulfilling-Expectations",
      "identifiers": [
        "doc://com.apple.xctest/documentation/XCTest/XCTestExpectation/fulfill()"
      ],
      "title": "Fulfilling Expectations"
    },
    {
      "anchor": "Fulfillment-Count",
      "identifiers": [
        "doc://com.apple.xctest/documentation/XCTest/XCTestExpectation/expectedFulfillmentCount",
        "doc://com.apple.xctest/documentation/XCTest/XCTestExpectation/assertForOverFulfill"
      ],
      "title": "Fulfillment Count"
    },
    {
      "anchor": "Unintended-Expectations",
      "identifiers": [
        "doc://com.apple.xctest/documentation/XCTest/XCTestExpectation/isInverted"
      ],
      "title": "Unintended Expectations"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "add",
          "path": "/metadata/platforms",
          "value": null
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Class"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "XCTestExpectation"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "class"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "XCTestExpectation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "XCTestExpectation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.xctest/documentation/XCTest"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Creating-Expectations",
              "identifiers": [
                "doc://com.apple.xctest/documentation/XCTest/XCTestExpectation/init(description:)",
                "doc://com.apple.xctest/documentation/XCTest/XCTestExpectation/expectationDescription"
              ],
              "title": "Creating Expectations"
            },
            {
              "anchor": "Fulfilling-Expectations",
              "identifiers": [
                "doc://com.apple.xctest/documentation/XCTest/XCTestExpectation/fulfill()"
              ],
              "title": "Fulfilling Expectations"
            },
            {
              "anchor": "Fulfillment-Count",
              "identifiers": [
                "doc://com.apple.xctest/documentation/XCTest/XCTestExpectation/expectedFulfillmentCount",
                "doc://com.apple.xctest/documentation/XCTest/XCTestExpectation/assertForOverFulfill"
              ],
              "title": "Fulfillment Count"
            },
            {
              "anchor": "Unintended-Expectations",
              "identifiers": [
                "doc://com.apple.xctest/documentation/XCTest/XCTestExpectation/isInverted"
              ],
              "title": "Unintended Expectations"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": [
            {
              "identifiers": [
                "doc://com.externally.resolved.symbol/c:objc(cs)NSObject"
              ],
              "kind": "relationships",
              "title": "Inherits From",
              "type": "inheritsFrom"
            },
            {
              "identifiers": [
                "doc://com.apple.xctest/documentation/XCTest/XCTDarwinNotificationExpectation",
                "doc://com.apple.xctest/documentation/XCTest/XCTKVOExpectation",
                "doc://com.apple.xctest/documentation/XCTest/XCTNSNotificationExpectation",
                "doc://com.apple.xctest/documentation/XCTest/XCTNSPredicateExpectation"
              ],
              "kind": "relationships",
              "title": "Inherited By",
              "type": "inheritedBy"
            }
          ]
        },
        {
          "op": "add",
          "path": "/seeAlsoSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "@interface"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "XCTestExpectation"
                  },
                  {
                    "kind": "text",
                    "text": " : "
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSObject",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(cs)NSObject",
                    "text": "NSObject"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCTNSPredicateExpectation/title",
          "value": "XCTNSPredicateExpectation"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCTNSPredicateExpectation/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "XCTNSPredicateExpectation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCTNSPredicateExpectation/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "XCTNSPredicateExpectation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCTestExpectation~1fulfill()/title",
          "value": "fulfill"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCTestExpectation~1fulfill()/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "fulfill"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCTestExpectation~1assertForOverFulfill/title",
          "value": "assertForOverFulfill"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCTestExpectation~1assertForOverFulfill/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "assertForOverFulfill"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:objc(pl)NSObject/title",
          "value": "NSObject"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCTestExpectation~1expectedFulfillmentCount/title",
          "value": "expectedFulfillmentCount"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCTestExpectation~1expectedFulfillmentCount/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "expectedFulfillmentCount"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCTestExpectation/title",
          "value": "XCTestExpectation"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCTestExpectation/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "XCTestExpectation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCTestExpectation/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "XCTestExpectation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCTestExpectation~1isInverted/title",
          "value": "inverted"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCTestExpectation~1isInverted/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "inverted"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCTNSNotificationExpectation/title",
          "value": "XCTNSNotificationExpectation"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCTNSNotificationExpectation/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "XCTNSNotificationExpectation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCTNSNotificationExpectation/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "XCTNSNotificationExpectation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCTDarwinNotificationExpectation/title",
          "value": "XCTDarwinNotificationExpectation"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCTDarwinNotificationExpectation/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "XCTDarwinNotificationExpectation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCTDarwinNotificationExpectation/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "XCTDarwinNotificationExpectation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCTKVOExpectation/title",
          "value": "XCTKVOExpectation"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCTKVOExpectation/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "XCTKVOExpectation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCTKVOExpectation/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "XCTKVOExpectation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCTestExpectation~1expectationDescription/title",
          "value": "expectationDescription"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCTestExpectation~1expectationDescription/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "expectationDescription"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCTestExpectation~1init(description:)/title",
          "value": "initWithDescription:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCTestExpectation~1init(description:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "initWithDescription:"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/xctest/xctestexpectation"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/xctest/xctestexpectation"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
