{
  "abstract": [
    {
      "text": "Instructs the test to expect a failure in an upcoming assertion, with options to customize expected failure checking and handling.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.xctest/documentation/XCTest"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "occ",
    "url": "doc://com.apple.xctest/documentation/XCTest/XCTExpectFailureWithOptions"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@F@XCTExpectFailureWithOptions",
    "fragments": [
      {
        "kind": "identifier",
        "text": "XCTExpectFailureWithOptions"
      }
    ],
    "modules": [
      {
        "name": "XCTest"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "XCTExpectFailureWithOptions"
      }
    ],
    "role": "symbol",
    "roleHeading": "Function",
    "symbolKind": "func",
    "title": "XCTExpectFailureWithOptions"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "occ"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "extern"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:v",
              "text": "void"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "XCTExpectFailureWithOptions"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSString",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)NSString",
              "text": "NSString"
            },
            {
              "kind": "text",
              "text": " * "
            },
            {
              "kind": "internalParam",
              "text": "failureReason"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "identifier": "doc://com.apple.xctest/documentation/XCTest/XCTExpectedFailure/Options",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)XCTExpectedFailureOptions",
              "text": "XCTExpectedFailureOptions"
            },
            {
              "kind": "text",
              "text": " * "
            },
            {
              "kind": "internalParam",
              "text": "options"
            },
            {
              "kind": "text",
              "text": ");"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.xctest/documentation/XCTest": {
      "abstract": [
        {
          "text": "Create and run unit tests, performance tests, and UI tests for your Xcode project.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.xctest/documentation/XCTest",
      "kind": "symbol",
      "role": "collection",
      "title": "XCTest",
      "type": "topic",
      "url": "/documentation/xctest"
    },
    "doc://com.apple.xctest/documentation/XCTest/XCTExpectFailure": {
      "abstract": [
        {
          "text": "Instructs the test to expect a failure in an upcoming assertion.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "XCTExpectFailure"
        }
      ],
      "identifier": "doc://com.apple.xctest/documentation/XCTest/XCTExpectFailure",
      "kind": "symbol",
      "role": "symbol",
      "title": "XCTExpectFailure",
      "type": "topic",
      "url": "/documentation/xctest/xctexpectfailure"
    },
    "doc://com.apple.xctest/documentation/XCTest/XCTExpectFailureInBlock": {
      "abstract": [
        {
          "text": "Instructs the test to expect a failure in an assertion in the provided block of code.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "XCTExpectFailureInBlock"
        }
      ],
      "identifier": "doc://com.apple.xctest/documentation/XCTest/XCTExpectFailureInBlock",
      "kind": "symbol",
      "role": "symbol",
      "title": "XCTExpectFailureInBlock",
      "type": "topic",
      "url": "/documentation/xctest/xctexpectfailureinblock"
    },
    "doc://com.apple.xctest/documentation/XCTest/XCTExpectFailureWithOptions": {
      "abstract": [
        {
          "text": "Instructs the test to expect a failure in an upcoming assertion, with options to customize expected failure checking and handling.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "XCTExpectFailureWithOptions"
        }
      ],
      "identifier": "doc://com.apple.xctest/documentation/XCTest/XCTExpectFailureWithOptions",
      "kind": "symbol",
      "role": "symbol",
      "title": "XCTExpectFailureWithOptions",
      "type": "topic",
      "url": "/documentation/xctest/xctexpectfailurewithoptions"
    },
    "doc://com.apple.xctest/documentation/XCTest/XCTExpectFailureWithOptionsInBlock": {
      "abstract": [
        {
          "text": "Instructs the test to expect a failure in an assertion in the provided block of code, with options to customize expected failure checking and handling.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "XCTExpectFailureWithOptionsInBlock"
        }
      ],
      "identifier": "doc://com.apple.xctest/documentation/XCTest/XCTExpectFailureWithOptionsInBlock",
      "kind": "symbol",
      "role": "symbol",
      "title": "XCTExpectFailureWithOptionsInBlock",
      "type": "topic",
      "url": "/documentation/xctest/xctexpectfailurewithoptionsinblock"
    },
    "doc://com.apple.xctest/documentation/XCTest/XCTExpectedFailure": {
      "abstract": [
        {
          "text": "An object that represents an expected test failure.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "XCTExpectedFailure"
        }
      ],
      "identifier": "doc://com.apple.xctest/documentation/XCTest/XCTExpectedFailure",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "XCTExpectedFailure"
        }
      ],
      "role": "symbol",
      "title": "XCTExpectedFailure",
      "type": "topic",
      "url": "/documentation/xctest/xctexpectedfailure"
    },
    "doc://com.apple.xctest/documentation/XCTest/XCTExpectedFailure/Options": {
      "abstract": [
        {
          "text": "Options that determine how the test matches the expected failure to an actual test failure, and whether an unfulfilled expected failure results in a test failure.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Options"
        }
      ],
      "identifier": "doc://com.apple.xctest/documentation/XCTest/XCTExpectedFailure/Options",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "Options"
        }
      ],
      "role": "symbol",
      "title": "XCTExpectedFailure.Options",
      "type": "topic",
      "url": "/documentation/xctest/xctexpectedfailure/options"
    },
    "doc://com.externally.resolved.symbol/c:objc(cs)NSString": {
      "abstract": [
        {
          "text": "A static, plain-text Unicode string object which you use when you need reference semantics or other Foundation-specific behavior. ",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "class "
        },
        {
          "kind": "identifier",
          "text": "NSString"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSString",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSString",
      "type": "topic",
      "url": "/documentation/foundation/nsstring"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Expected-Failures",
      "generated": true,
      "identifiers": [
        "doc://com.apple.xctest/documentation/XCTest/XCTExpectedFailure",
        "doc://com.apple.xctest/documentation/XCTest/XCTExpectedFailure/Options",
        "doc://com.apple.xctest/documentation/XCTest/XCTExpectFailure",
        "doc://com.apple.xctest/documentation/XCTest/XCTExpectFailureInBlock",
        "doc://com.apple.xctest/documentation/XCTest/XCTExpectFailureWithOptionsInBlock"
      ],
      "title": "Expected Failures"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:objc(cs)NSString/abstract",
          "value": [
            {
              "text": "A static, plain-text Unicode string object.",
              "type": "text"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCTExpectedFailure~1Options/title",
          "value": "XCTExpectedFailureOptions"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCTExpectedFailure~1Options/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "XCTExpectedFailureOptions"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCTExpectedFailure~1Options/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "XCTExpectedFailureOptions"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCTExpectedFailure/title",
          "value": "XCTExpectedFailure"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCTExpectedFailure/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "XCTExpectedFailure"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCTExpectedFailure/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "XCTExpectedFailure"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/xctest/xctexpectfailurewithoptions"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
