{
  "abstract": [
    {
      "text": "A base class for collecting information about a specific execution of a test.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.xctest/documentation/XCTest"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.xctest/documentation/XCTest/XCTestRun"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(cs)XCTestRun",
    "fragments": [
      {
        "kind": "keyword",
        "text": "class"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "XCTestRun"
      }
    ],
    "modules": [
      {
        "name": "XCTest"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "XCTestRun"
      }
    ],
    "role": "symbol",
    "roleHeading": "Class",
    "symbolKind": "class",
    "title": "XCTestRun"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "class"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "XCTestRun"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "code": "XCTestRun",
              "type": "codeVoice"
            },
            {
              "text": " classifies failures in explicit test assertions as ",
              "type": "text"
            },
            {
              "inlineContent": [
                {
                  "text": "expected",
                  "type": "text"
                }
              ],
              "type": "emphasis"
            },
            {
              "text": ", and failures from unrelated or uncaught exceptions as ",
              "type": "text"
            },
            {
              "inlineContent": [
                {
                  "text": "unexpected",
                  "type": "text"
                }
              ],
              "type": "emphasis"
            },
            {
              "text": ".",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.xctest/documentation/XCTest": {
      "abstract": [
        {
          "text": "Create and run unit tests, performance tests, and UI tests for your Xcode project.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.xctest/documentation/XCTest",
      "kind": "symbol",
      "role": "collection",
      "title": "XCTest",
      "type": "topic",
      "url": "/documentation/xctest"
    },
    "doc://com.apple.xctest/documentation/XCTest/XCTestCaseRun": {
      "abstract": [
        {
          "text": "An object that collects information about a specific execution of a test case.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "XCTestCaseRun"
        }
      ],
      "identifier": "doc://com.apple.xctest/documentation/XCTest/XCTestCaseRun",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "XCTestCaseRun"
        }
      ],
      "role": "symbol",
      "title": "XCTestCaseRun",
      "type": "topic",
      "url": "/documentation/xctest/xctestcaserun"
    },
    "doc://com.apple.xctest/documentation/XCTest/XCTestRun": {
      "abstract": [
        {
          "text": "A base class for collecting information about a specific execution of a test.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "XCTestRun"
        }
      ],
      "identifier": "doc://com.apple.xctest/documentation/XCTest/XCTestRun",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "XCTestRun"
        }
      ],
      "role": "symbol",
      "title": "XCTestRun",
      "type": "topic",
      "url": "/documentation/xctest/xctestrun"
    },
    "doc://com.apple.xctest/documentation/XCTest/XCTestRun/executionCount": {
      "abstract": [
        {
          "text": "The number of test executions during the run.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "executionCount"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.xctest/documentation/XCTest/XCTestRun/executionCount",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "executionCount"
        }
      ],
      "role": "symbol",
      "title": "executionCount",
      "type": "topic",
      "url": "/documentation/xctest/xctestrun/executioncount"
    },
    "doc://com.apple.xctest/documentation/XCTest/XCTestRun/failureCount": {
      "abstract": [
        {
          "text": "The number of test failures during the run.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "failureCount"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.xctest/documentation/XCTest/XCTestRun/failureCount",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "failureCount"
        }
      ],
      "role": "symbol",
      "title": "failureCount",
      "type": "topic",
      "url": "/documentation/xctest/xctestrun/failurecount"
    },
    "doc://com.apple.xctest/documentation/XCTest/XCTestRun/hasBeenSkipped": {
      "abstract": [
        {
          "text": "A Boolean value that indicates a skipped test.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "hasBeenSkipped"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.xctest/documentation/XCTest/XCTestRun/hasBeenSkipped",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "hasBeenSkipped"
        }
      ],
      "role": "symbol",
      "title": "hasBeenSkipped",
      "type": "topic",
      "url": "/documentation/xctest/xctestrun/hasbeenskipped"
    },
    "doc://com.apple.xctest/documentation/XCTest/XCTestRun/hasSucceeded": {
      "abstract": [
        {
          "text": "A Boolean value that returns true if all tests in the run completed without recording any failures; otherwise, false.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "hasSucceeded"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.xctest/documentation/XCTest/XCTestRun/hasSucceeded",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "hasSucceeded"
        }
      ],
      "role": "symbol",
      "title": "hasSucceeded",
      "type": "topic",
      "url": "/documentation/xctest/xctestrun/hassucceeded"
    },
    "doc://com.apple.xctest/documentation/XCTest/XCTestRun/init(test:)": {
      "abstract": [
        {
          "text": "Creates a new test run for the provided test.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "test"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)XCTest",
          "text": "XCTest"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.xctest/documentation/XCTest/XCTestRun/init(test:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "initWithTest:"
        }
      ],
      "role": "symbol",
      "title": "init(test:)",
      "type": "topic",
      "url": "/documentation/xctest/xctestrun/init(test:)"
    },
    "doc://com.apple.xctest/documentation/XCTest/XCTestRun/record(_:)": {
      "abstract": [
        {
          "text": "Records an issue during test execution for the test run.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "record"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:6XCTest8XCTIssueV",
          "text": "XCTIssue"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.xctest/documentation/XCTest/XCTestRun/record(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "recordIssue:"
        }
      ],
      "role": "symbol",
      "title": "record(_:)",
      "type": "topic",
      "url": "/documentation/xctest/xctestrun/record(_:)"
    },
    "doc://com.apple.xctest/documentation/XCTest/XCTestRun/recordFailure(withDescription:inFile:atLine:expected:)": {
      "abstract": [
        {
          "text": "Records a failure during test execution for the test run.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "recordFailure"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "withDescription"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "inFile"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": "?, "
        },
        {
          "kind": "externalParam",
          "text": "atLine"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "expected"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.xctest/documentation/XCTest/XCTestRun/recordFailure(withDescription:inFile:atLine:expected:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "recordFailureWithDescription:inFile:atLine:expected:"
        }
      ],
      "role": "symbol",
      "title": "recordFailure(withDescription:inFile:atLine:expected:)",
      "type": "topic",
      "url": "/documentation/xctest/xctestrun/recordfailure(withdescription:infile:atline:expected:)"
    },
    "doc://com.apple.xctest/documentation/XCTest/XCTestRun/skipCount": {
      "abstract": [
        {
          "text": "The number of skipped tests during the run.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "skipCount"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.xctest/documentation/XCTest/XCTestRun/skipCount",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "skipCount"
        }
      ],
      "role": "symbol",
      "title": "skipCount",
      "type": "topic",
      "url": "/documentation/xctest/xctestrun/skipcount"
    },
    "doc://com.apple.xctest/documentation/XCTest/XCTestRun/start()": {
      "abstract": [
        {
          "text": "Starts a test run.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "start"
        },
        {
          "kind": "text",
          "text": "()"
        }
      ],
      "identifier": "doc://com.apple.xctest/documentation/XCTest/XCTestRun/start()",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "start"
        }
      ],
      "role": "symbol",
      "title": "start()",
      "type": "topic",
      "url": "/documentation/xctest/xctestrun/start()"
    },
    "doc://com.apple.xctest/documentation/XCTest/XCTestRun/startDate": {
      "abstract": [
        {
          "text": "The date and time when the test run started, or no value if the test hasn’t run.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "startDate"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10Foundation4DateV",
          "text": "Date"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.xctest/documentation/XCTest/XCTestRun/startDate",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "startDate"
        }
      ],
      "role": "symbol",
      "title": "startDate",
      "type": "topic",
      "url": "/documentation/xctest/xctestrun/startdate"
    },
    "doc://com.apple.xctest/documentation/XCTest/XCTestRun/stop()": {
      "abstract": [
        {
          "text": "Stops a test run.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "stop"
        },
        {
          "kind": "text",
          "text": "()"
        }
      ],
      "identifier": "doc://com.apple.xctest/documentation/XCTest/XCTestRun/stop()",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "stop"
        }
      ],
      "role": "symbol",
      "title": "stop()",
      "type": "topic",
      "url": "/documentation/xctest/xctestrun/stop()"
    },
    "doc://com.apple.xctest/documentation/XCTest/XCTestRun/stopDate": {
      "abstract": [
        {
          "text": "The date and time when the test run stopped, or no value if the test hasn’t run.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "stopDate"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10Foundation4DateV",
          "text": "Date"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.xctest/documentation/XCTest/XCTestRun/stopDate",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "stopDate"
        }
      ],
      "role": "symbol",
      "title": "stopDate",
      "type": "topic",
      "url": "/documentation/xctest/xctestrun/stopdate"
    },
    "doc://com.apple.xctest/documentation/XCTest/XCTestRun/test": {
      "abstract": [
        {
          "text": "The test instance for the test run.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "test"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)XCTest",
          "text": "XCTest"
        }
      ],
      "identifier": "doc://com.apple.xctest/documentation/XCTest/XCTestRun/test",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "test"
        }
      ],
      "role": "symbol",
      "title": "test",
      "type": "topic",
      "url": "/documentation/xctest/xctestrun/test"
    },
    "doc://com.apple.xctest/documentation/XCTest/XCTestRun/testCaseCount": {
      "abstract": [
        {
          "text": "The number of tests in the run.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "testCaseCount"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.xctest/documentation/XCTest/XCTestRun/testCaseCount",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "testCaseCount"
        }
      ],
      "role": "symbol",
      "title": "testCaseCount",
      "type": "topic",
      "url": "/documentation/xctest/xctestrun/testcasecount"
    },
    "doc://com.apple.xctest/documentation/XCTest/XCTestRun/testDuration": {
      "abstract": [
        {
          "text": "The number of seconds that elapse between when the run starts and when it stops.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "testDuration"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSTimeInterval",
          "text": "TimeInterval"
        }
      ],
      "identifier": "doc://com.apple.xctest/documentation/XCTest/XCTestRun/testDuration",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "testDuration"
        }
      ],
      "role": "symbol",
      "title": "testDuration",
      "type": "topic",
      "url": "/documentation/xctest/xctestrun/testduration"
    },
    "doc://com.apple.xctest/documentation/XCTest/XCTestRun/testRunWithTest:": {
      "abstract": [
        {
          "text": "Creates a new ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.xctest/documentation/XCTest/XCTestRun",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " for the provided test.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "+ "
        },
        {
          "kind": "identifier",
          "text": "testRunWithTest:"
        }
      ],
      "identifier": "doc://com.apple.xctest/documentation/XCTest/XCTestRun/testRunWithTest:",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "testRunWithTest:"
        }
      ],
      "role": "symbol",
      "title": "testRunWithTest:",
      "type": "topic",
      "url": "/documentation/xctest/xctestrun/testrunwithtest:"
    },
    "doc://com.apple.xctest/documentation/XCTest/XCTestRun/totalDuration": {
      "abstract": [
        {
          "text": "The number of seconds that elapse between when the run starts and when it stops.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "totalDuration"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSTimeInterval",
          "text": "TimeInterval"
        }
      ],
      "identifier": "doc://com.apple.xctest/documentation/XCTest/XCTestRun/totalDuration",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "totalDuration"
        }
      ],
      "role": "symbol",
      "title": "totalDuration",
      "type": "topic",
      "url": "/documentation/xctest/xctestrun/totalduration"
    },
    "doc://com.apple.xctest/documentation/XCTest/XCTestRun/totalFailureCount": {
      "abstract": [
        {
          "text": "The number of test failures and uncaught exceptions during the run.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "totalFailureCount"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.xctest/documentation/XCTest/XCTestRun/totalFailureCount",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "totalFailureCount"
        }
      ],
      "role": "symbol",
      "title": "totalFailureCount",
      "type": "topic",
      "url": "/documentation/xctest/xctestrun/totalfailurecount"
    },
    "doc://com.apple.xctest/documentation/XCTest/XCTestRun/unexpectedExceptionCount": {
      "abstract": [
        {
          "text": "The number of uncaught exceptions during the run.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "unexpectedExceptionCount"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.xctest/documentation/XCTest/XCTestRun/unexpectedExceptionCount",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "unexpectedExceptionCount"
        }
      ],
      "role": "symbol",
      "title": "unexpectedExceptionCount",
      "type": "topic",
      "url": "/documentation/xctest/xctestrun/unexpectedexceptioncount"
    },
    "doc://com.apple.xctest/documentation/XCTest/XCTestSuiteRun": {
      "abstract": [
        {
          "text": "An object that collects information about a specific execution of a test suite.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "XCTestSuiteRun"
        }
      ],
      "identifier": "doc://com.apple.xctest/documentation/XCTest/XCTestSuiteRun",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "XCTestSuiteRun"
        }
      ],
      "role": "symbol",
      "title": "XCTestSuiteRun",
      "type": "topic",
      "url": "/documentation/xctest/xctestsuiterun"
    },
    "doc://com.externally.resolved.symbol/c:objc(cs)NSObject": {
      "abstract": [
        {
          "text": "The root class of most Objective-C class hierarchies, from which subclasses inherit a basic interface to the runtime system and the ability to behave as Objective-C objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "class "
        },
        {
          "kind": "identifier",
          "text": "NSObject"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSObject",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSObject",
      "type": "topic",
      "url": "/documentation/objectivec/nsobject"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)NSObject": {
      "abstract": [
        {
          "text": "The group of methods that are fundamental to all Objective-C objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "protocol "
        },
        {
          "kind": "identifier",
          "text": "NSObjectProtocol"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSObject",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSObjectProtocol",
      "type": "topic",
      "url": "/documentation/objectivec/nsobjectprotocol"
    },
    "doc://com.externally.resolved.symbol/s:SH": {
      "abstract": [
        {
          "text": "A type that can be hashed into a `Hasher` to produce an integer hash value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Hashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SQ",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SH",
      "kind": "symbol",
      "role": "symbol",
      "title": "Hashable",
      "type": "topic",
      "url": "/documentation/Swift/Hashable"
    },
    "doc://com.externally.resolved.symbol/s:SQ": {
      "abstract": [
        {
          "text": "A type that can be compared for value equality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SQ",
      "kind": "symbol",
      "role": "symbol",
      "title": "Equatable",
      "type": "topic",
      "url": "/documentation/Swift/Equatable"
    },
    "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP": {
      "abstract": [
        {
          "text": "A type with a customized textual representation.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CustomStringConvertible"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CustomStringConvertible",
      "type": "topic",
      "url": "/documentation/Swift/CustomStringConvertible"
    },
    "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP": {
      "abstract": [
        {
          "text": "A type with a customized textual representation suitable for debugging purposes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CustomDebugStringConvertible"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CustomDebugStringConvertible",
      "type": "topic",
      "url": "/documentation/Swift/CustomDebugStringConvertible"
    },
    "doc://com.externally.resolved.symbol/s:s7CVarArgP": {
      "abstract": [
        {
          "text": "A type whose instances can be encoded, and appropriately passed, as elements of a C `va_list`.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CVarArg"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s7CVarArgP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CVarArg",
      "type": "topic",
      "url": "/documentation/Swift/CVarArg"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/c:objc(cs)NSObject"
      ],
      "kind": "relationships",
      "title": "Inherits From",
      "type": "inheritsFrom"
    },
    {
      "identifiers": [
        "doc://com.apple.xctest/documentation/XCTest/XCTestCaseRun",
        "doc://com.apple.xctest/documentation/XCTest/XCTestSuiteRun"
      ],
      "kind": "relationships",
      "title": "Inherited By",
      "type": "inheritedBy"
    },
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:s7CVarArgP",
        "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP",
        "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP",
        "doc://com.externally.resolved.symbol/s:SQ",
        "doc://com.externally.resolved.symbol/s:SH",
        "doc://com.externally.resolved.symbol/c:objc(pl)NSObject"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Test-Runs",
      "generated": true,
      "identifiers": [
        "doc://com.apple.xctest/documentation/XCTest/XCTestCaseRun",
        "doc://com.apple.xctest/documentation/XCTest/XCTestSuiteRun"
      ],
      "title": "Test Runs"
    }
  ],
  "topicSections": [
    {
      "anchor": "Creating-Test-Runs",
      "identifiers": [
        "doc://com.apple.xctest/documentation/XCTest/XCTestRun/init(test:)"
      ],
      "title": "Creating Test Runs"
    },
    {
      "anchor": "Performing-Test-Runs",
      "identifiers": [
        "doc://com.apple.xctest/documentation/XCTest/XCTestRun/start()",
        "doc://com.apple.xctest/documentation/XCTest/XCTestRun/stop()",
        "doc://com.apple.xctest/documentation/XCTest/XCTestRun/record(_:)"
      ],
      "title": "Performing Test Runs"
    },
    {
      "anchor": "Tracking-Test-Durations",
      "identifiers": [
        "doc://com.apple.xctest/documentation/XCTest/XCTestRun/startDate",
        "doc://com.apple.xctest/documentation/XCTest/XCTestRun/stopDate",
        "doc://com.apple.xctest/documentation/XCTest/XCTestRun/testDuration",
        "doc://com.apple.xctest/documentation/XCTest/XCTestRun/totalDuration"
      ],
      "title": "Tracking Test Durations"
    },
    {
      "anchor": "Gathering-Test-Outcomes",
      "identifiers": [
        "doc://com.apple.xctest/documentation/XCTest/XCTestRun/hasSucceeded",
        "doc://com.apple.xctest/documentation/XCTest/XCTestRun/hasBeenSkipped",
        "doc://com.apple.xctest/documentation/XCTest/XCTestRun/executionCount",
        "doc://com.apple.xctest/documentation/XCTest/XCTestRun/failureCount",
        "doc://com.apple.xctest/documentation/XCTest/XCTestRun/skipCount",
        "doc://com.apple.xctest/documentation/XCTest/XCTestRun/test",
        "doc://com.apple.xctest/documentation/XCTest/XCTestRun/testCaseCount",
        "doc://com.apple.xctest/documentation/XCTest/XCTestRun/totalFailureCount",
        "doc://com.apple.xctest/documentation/XCTest/XCTestRun/unexpectedExceptionCount"
      ],
      "title": "Gathering Test Outcomes"
    },
    {
      "anchor": "Deprecated",
      "identifiers": [
        "doc://com.apple.xctest/documentation/XCTest/XCTestRun/recordFailure(withDescription:inFile:atLine:expected:)"
      ],
      "title": "Deprecated"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "add",
          "path": "/metadata/platforms",
          "value": null
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Class"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "XCTestRun"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "class"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "XCTestRun"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "XCTestRun"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.xctest/documentation/XCTest"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Creating-Test-Runs",
              "identifiers": [
                "doc://com.apple.xctest/documentation/XCTest/XCTestRun/init(test:)",
                "doc://com.apple.xctest/documentation/XCTest/XCTestRun/testRunWithTest:"
              ],
              "title": "Creating Test Runs"
            },
            {
              "anchor": "Performing-Test-Runs",
              "identifiers": [
                "doc://com.apple.xctest/documentation/XCTest/XCTestRun/start()",
                "doc://com.apple.xctest/documentation/XCTest/XCTestRun/stop()",
                "doc://com.apple.xctest/documentation/XCTest/XCTestRun/record(_:)"
              ],
              "title": "Performing Test Runs"
            },
            {
              "anchor": "Tracking-Test-Durations",
              "identifiers": [
                "doc://com.apple.xctest/documentation/XCTest/XCTestRun/startDate",
                "doc://com.apple.xctest/documentation/XCTest/XCTestRun/stopDate",
                "doc://com.apple.xctest/documentation/XCTest/XCTestRun/testDuration",
                "doc://com.apple.xctest/documentation/XCTest/XCTestRun/totalDuration"
              ],
              "title": "Tracking Test Durations"
            },
            {
              "anchor": "Gathering-Test-Outcomes",
              "identifiers": [
                "doc://com.apple.xctest/documentation/XCTest/XCTestRun/hasSucceeded",
                "doc://com.apple.xctest/documentation/XCTest/XCTestRun/hasBeenSkipped",
                "doc://com.apple.xctest/documentation/XCTest/XCTestRun/executionCount",
                "doc://com.apple.xctest/documentation/XCTest/XCTestRun/failureCount",
                "doc://com.apple.xctest/documentation/XCTest/XCTestRun/skipCount",
                "doc://com.apple.xctest/documentation/XCTest/XCTestRun/test",
                "doc://com.apple.xctest/documentation/XCTest/XCTestRun/testCaseCount",
                "doc://com.apple.xctest/documentation/XCTest/XCTestRun/totalFailureCount",
                "doc://com.apple.xctest/documentation/XCTest/XCTestRun/unexpectedExceptionCount"
              ],
              "title": "Gathering Test Outcomes"
            },
            {
              "anchor": "Deprecated",
              "identifiers": [
                "doc://com.apple.xctest/documentation/XCTest/XCTestRun/recordFailure(withDescription:inFile:atLine:expected:)"
              ],
              "title": "Deprecated"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": [
            {
              "identifiers": [
                "doc://com.externally.resolved.symbol/c:objc(cs)NSObject"
              ],
              "kind": "relationships",
              "title": "Inherits From",
              "type": "inheritsFrom"
            },
            {
              "identifiers": [
                "doc://com.apple.xctest/documentation/XCTest/XCTestCaseRun",
                "doc://com.apple.xctest/documentation/XCTest/XCTestSuiteRun"
              ],
              "kind": "relationships",
              "title": "Inherited By",
              "type": "inheritedBy"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Test-Runs",
              "generated": true,
              "identifiers": [
                "doc://com.apple.xctest/documentation/XCTest/XCTestCaseRun",
                "doc://com.apple.xctest/documentation/XCTest/XCTestSuiteRun"
              ],
              "title": "Test Runs"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "@interface"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "XCTestRun"
                  },
                  {
                    "kind": "text",
                    "text": " : "
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSObject",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(cs)NSObject",
                    "text": "NSObject"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCTestRun~1totalDuration/title",
          "value": "totalDuration"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCTestRun~1totalDuration/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "totalDuration"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCTestRun~1test/title",
          "value": "test"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCTestRun~1test/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "test"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCTestRun~1unexpectedExceptionCount/title",
          "value": "unexpectedExceptionCount"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCTestRun~1unexpectedExceptionCount/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "unexpectedExceptionCount"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCTestRun~1hasBeenSkipped/title",
          "value": "hasBeenSkipped"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCTestRun~1hasBeenSkipped/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "hasBeenSkipped"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCTestRun~1init(test:)/title",
          "value": "initWithTest:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCTestRun~1init(test:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "initWithTest:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCTestRun~1hasSucceeded/title",
          "value": "hasSucceeded"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCTestRun~1hasSucceeded/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "hasSucceeded"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCTestRun~1startDate/title",
          "value": "startDate"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCTestRun~1startDate/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "startDate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCTestRun~1totalFailureCount/title",
          "value": "totalFailureCount"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCTestRun~1totalFailureCount/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "totalFailureCount"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCTestRun~1skipCount/title",
          "value": "skipCount"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCTestRun~1skipCount/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "skipCount"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCTestRun~1failureCount/title",
          "value": "failureCount"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCTestRun~1failureCount/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "failureCount"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:objc(pl)NSObject/title",
          "value": "NSObject"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCTestRun/title",
          "value": "XCTestRun"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCTestRun/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "XCTestRun"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCTestRun/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "XCTestRun"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCTestRun~1record(_:)/title",
          "value": "recordIssue:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCTestRun~1record(_:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "recordIssue:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCTestRun~1executionCount/title",
          "value": "executionCount"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCTestRun~1executionCount/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "executionCount"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCTestRun~1stop()/title",
          "value": "stop"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCTestRun~1stop()/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "stop"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCTestRun~1stopDate/title",
          "value": "stopDate"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCTestRun~1stopDate/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "stopDate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCTestRun~1testDuration/title",
          "value": "testDuration"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCTestRun~1testDuration/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "testDuration"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCTestSuiteRun/title",
          "value": "XCTestSuiteRun"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCTestSuiteRun/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "XCTestSuiteRun"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCTestSuiteRun/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "XCTestSuiteRun"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCTestRun~1testCaseCount/title",
          "value": "testCaseCount"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCTestRun~1testCaseCount/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "testCaseCount"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCTestCaseRun/title",
          "value": "XCTestCaseRun"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCTestCaseRun/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "XCTestCaseRun"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCTestCaseRun/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "XCTestCaseRun"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCTestRun~1start()/title",
          "value": "start"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCTestRun~1start()/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "start"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCTestRun~1recordFailure(withDescription:inFile:atLine:expected:)/title",
          "value": "recordFailureWithDescription:inFile:atLine:expected:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCTestRun~1recordFailure(withDescription:inFile:atLine:expected:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "recordFailureWithDescription:inFile:atLine:expected:"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/xctest/xctestrun"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/xctest/xctestrun"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
