{
  "abstract": [
    {
      "text": "A protocol that defines methods the test runner calls in response to significant events during test runs.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.xctest/documentation/XCTest"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.xctest/documentation/XCTest/XCTestObservation"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(pl)XCTestObservation",
    "fragments": [
      {
        "kind": "keyword",
        "text": "protocol"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "XCTestObservation"
      }
    ],
    "modules": [
      {
        "name": "XCTest"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "XCTestObservation"
      }
    ],
    "role": "symbol",
    "roleHeading": "Protocol",
    "symbolKind": "protocol",
    "title": "XCTestObservation"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "protocol"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "XCTestObservation"
            },
            {
              "kind": "text",
              "text": " : "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSObject",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(pl)NSObject",
              "text": "NSObjectProtocol"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "The system calls the notification methods for ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.xctest/documentation/XCTest/XCTestObservation",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " in the following sequence for a test bundle:",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "items": [
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "identifier": "doc://com.apple.xctest/documentation/XCTest/XCTestObservation/testBundleWillStart(_:)",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": " — exactly once per test bundle",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "identifier": "doc://com.apple.xctest/documentation/XCTest/XCTestObservation/testSuiteWillStart(_:)",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": " — exactly once per test suite",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "identifier": "doc://com.apple.xctest/documentation/XCTest/XCTestObservation/testCaseWillStart(_:)",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": " — exactly once per test case",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "identifier": "doc://com.apple.xctest/documentation/XCTest/XCTestObservation/testCase(_:didRecord:)-4cou6",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": "  — for each test failure, zero or more times per test case at any point between test case start and finish",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "identifier": "doc://com.apple.xctest/documentation/XCTest/XCTestObservation/testCase(_:didRecord:)-8k955",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": "  — for each expected test failure, zero or more times per test case at any point between test case start and finish",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "identifier": "doc://com.apple.xctest/documentation/XCTest/XCTestObservation/testCaseDidFinish(_:)",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": " — exactly once per test case",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "identifier": "doc://com.apple.xctest/documentation/XCTest/XCTestObservation/testSuite(_:didRecord:)-3rk9k",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": " — for each test failure, zero or more times per test suite at any point between test suite start and finish",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "identifier": "doc://com.apple.xctest/documentation/XCTest/XCTestObservation/testSuite(_:didRecord:)-1xjkv",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": " — for each expected test failure, zero or more times per test suite at any point between test suite start and finish",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "identifier": "doc://com.apple.xctest/documentation/XCTest/XCTestObservation/testSuiteDidFinish(_:)",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": " — exactly once per test suite",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "identifier": "doc://com.apple.xctest/documentation/XCTest/XCTestObservation/testBundleDidFinish(_:)",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": " — exactly once per test bundle",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            }
          ],
          "type": "orderedList"
        },
        {
          "inlineContent": [
            {
              "text": "See ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.xctest/documentation/XCTest/XCTestObservationCenter",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " for details about registering and removing test observers.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.xctest/documentation/XCTest": {
      "abstract": [
        {
          "text": "Create and run unit tests, performance tests, and UI tests for your Xcode project.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.xctest/documentation/XCTest",
      "kind": "symbol",
      "role": "collection",
      "title": "XCTest",
      "type": "topic",
      "url": "/documentation/xctest"
    },
    "doc://com.apple.xctest/documentation/XCTest/XCTestObservation": {
      "abstract": [
        {
          "text": "A protocol that defines methods the test runner calls in response to significant events during test runs.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "XCTestObservation"
        }
      ],
      "identifier": "doc://com.apple.xctest/documentation/XCTest/XCTestObservation",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "XCTestObservation"
        }
      ],
      "role": "symbol",
      "title": "XCTestObservation",
      "type": "topic",
      "url": "/documentation/xctest/xctestobservation"
    },
    "doc://com.apple.xctest/documentation/XCTest/XCTestObservation/testBundleDidFinish(_:)": {
      "abstract": [
        {
          "text": "Notifies the observer immediately after all tests in a test bundle finish executing.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "testBundleDidFinish"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSBundle",
          "text": "Bundle"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.xctest/documentation/XCTest/XCTestObservation/testBundleDidFinish(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "testBundleDidFinish:"
        }
      ],
      "role": "symbol",
      "title": "testBundleDidFinish(_:)",
      "type": "topic",
      "url": "/documentation/xctest/xctestobservation/testbundledidfinish(_:)"
    },
    "doc://com.apple.xctest/documentation/XCTest/XCTestObservation/testBundleWillStart(_:)": {
      "abstract": [
        {
          "text": "Notifies the observer immediately before any tests in a test bundle begin.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "testBundleWillStart"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSBundle",
          "text": "Bundle"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.xctest/documentation/XCTest/XCTestObservation/testBundleWillStart(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "testBundleWillStart:"
        }
      ],
      "role": "symbol",
      "title": "testBundleWillStart(_:)",
      "type": "topic",
      "url": "/documentation/xctest/xctestobservation/testbundlewillstart(_:)"
    },
    "doc://com.apple.xctest/documentation/XCTest/XCTestObservation/testCase(_:didFailWithDescription:inFile:atLine:)": {
      "abstract": [
        {
          "text": "Notifies the observer when a test case reports a failure.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "testCase"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)XCTestCase",
          "text": "XCTestCase"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "didFailWithDescription"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "inFile"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": "?, "
        },
        {
          "kind": "externalParam",
          "text": "atLine"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.xctest/documentation/XCTest/XCTestObservation/testCase(_:didFailWithDescription:inFile:atLine:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "testCase:didFailWithDescription:inFile:atLine:"
        }
      ],
      "role": "symbol",
      "title": "testCase(_:didFailWithDescription:inFile:atLine:)",
      "type": "topic",
      "url": "/documentation/xctest/xctestobservation/testcase(_:didfailwithdescription:infile:atline:)"
    },
    "doc://com.apple.xctest/documentation/XCTest/XCTestObservation/testCase(_:didRecord:)-4cou6": {
      "abstract": [
        {
          "text": "Notifies the observer when a test case reports an issue.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "testCase"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)XCTestCase",
          "text": "XCTestCase"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "didRecord"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:6XCTest8XCTIssueV",
          "text": "XCTIssue"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.xctest/documentation/XCTest/XCTestObservation/testCase(_:didRecord:)-4cou6",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "testCase:didRecordIssue:"
        }
      ],
      "role": "symbol",
      "title": "testCase(_:didRecord:)",
      "type": "topic",
      "url": "/documentation/xctest/xctestobservation/testcase(_:didrecord:)-4cou6"
    },
    "doc://com.apple.xctest/documentation/XCTest/XCTestObservation/testCase(_:didRecord:)-8k955": {
      "abstract": [
        {
          "text": "Notifies the observer when a test case records an expected failure.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "testCase"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)XCTestCase",
          "text": "XCTestCase"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "didRecord"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)XCTExpectedFailure",
          "text": "XCTExpectedFailure"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.xctest/documentation/XCTest/XCTestObservation/testCase(_:didRecord:)-8k955",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "testCase:didRecordExpectedFailure:"
        }
      ],
      "role": "symbol",
      "title": "testCase(_:didRecord:)",
      "type": "topic",
      "url": "/documentation/xctest/xctestobservation/testcase(_:didrecord:)-8k955"
    },
    "doc://com.apple.xctest/documentation/XCTest/XCTestObservation/testCaseDidFinish(_:)": {
      "abstract": [
        {
          "text": "Notifies the observer immediately after a test case finishes executing.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "testCaseDidFinish"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)XCTestCase",
          "text": "XCTestCase"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.xctest/documentation/XCTest/XCTestObservation/testCaseDidFinish(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "testCaseDidFinish:"
        }
      ],
      "role": "symbol",
      "title": "testCaseDidFinish(_:)",
      "type": "topic",
      "url": "/documentation/xctest/xctestobservation/testcasedidfinish(_:)"
    },
    "doc://com.apple.xctest/documentation/XCTest/XCTestObservation/testCaseWillStart(_:)": {
      "abstract": [
        {
          "text": "Notifies the observer immediately before a test case begins executing.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "testCaseWillStart"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)XCTestCase",
          "text": "XCTestCase"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.xctest/documentation/XCTest/XCTestObservation/testCaseWillStart(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "testCaseWillStart:"
        }
      ],
      "role": "symbol",
      "title": "testCaseWillStart(_:)",
      "type": "topic",
      "url": "/documentation/xctest/xctestobservation/testcasewillstart(_:)"
    },
    "doc://com.apple.xctest/documentation/XCTest/XCTestObservation/testSuite(_:didFailWithDescription:inFile:atLine:)": {
      "abstract": [
        {
          "text": "Notifies the observer when a test suite reports a failure.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "testSuite"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)XCTestSuite",
          "text": "XCTestSuite"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "didFailWithDescription"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "inFile"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": "?, "
        },
        {
          "kind": "externalParam",
          "text": "atLine"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.xctest/documentation/XCTest/XCTestObservation/testSuite(_:didFailWithDescription:inFile:atLine:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "testSuite:didFailWithDescription:inFile:atLine:"
        }
      ],
      "role": "symbol",
      "title": "testSuite(_:didFailWithDescription:inFile:atLine:)",
      "type": "topic",
      "url": "/documentation/xctest/xctestobservation/testsuite(_:didfailwithdescription:infile:atline:)"
    },
    "doc://com.apple.xctest/documentation/XCTest/XCTestObservation/testSuite(_:didRecord:)-1xjkv": {
      "abstract": [
        {
          "text": "Notifies the observer when a test suite records an expected failure.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "testSuite"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)XCTestSuite",
          "text": "XCTestSuite"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "didRecord"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)XCTExpectedFailure",
          "text": "XCTExpectedFailure"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.xctest/documentation/XCTest/XCTestObservation/testSuite(_:didRecord:)-1xjkv",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "testSuite:didRecordExpectedFailure:"
        }
      ],
      "role": "symbol",
      "title": "testSuite(_:didRecord:)",
      "type": "topic",
      "url": "/documentation/xctest/xctestobservation/testsuite(_:didrecord:)-1xjkv"
    },
    "doc://com.apple.xctest/documentation/XCTest/XCTestObservation/testSuite(_:didRecord:)-3rk9k": {
      "abstract": [
        {
          "text": "Notifies the observer when a test suite reports an issue.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "testSuite"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)XCTestSuite",
          "text": "XCTestSuite"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "didRecord"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:6XCTest8XCTIssueV",
          "text": "XCTIssue"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.xctest/documentation/XCTest/XCTestObservation/testSuite(_:didRecord:)-3rk9k",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "testSuite:didRecordIssue:"
        }
      ],
      "role": "symbol",
      "title": "testSuite(_:didRecord:)",
      "type": "topic",
      "url": "/documentation/xctest/xctestobservation/testsuite(_:didrecord:)-3rk9k"
    },
    "doc://com.apple.xctest/documentation/XCTest/XCTestObservation/testSuiteDidFinish(_:)": {
      "abstract": [
        {
          "text": "Notifies the observer immediately after a test suite finishes executing.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "testSuiteDidFinish"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)XCTestSuite",
          "text": "XCTestSuite"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.xctest/documentation/XCTest/XCTestObservation/testSuiteDidFinish(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "testSuiteDidFinish:"
        }
      ],
      "role": "symbol",
      "title": "testSuiteDidFinish(_:)",
      "type": "topic",
      "url": "/documentation/xctest/xctestobservation/testsuitedidfinish(_:)"
    },
    "doc://com.apple.xctest/documentation/XCTest/XCTestObservation/testSuiteWillStart(_:)": {
      "abstract": [
        {
          "text": "Notifies the observer immediately before a test suite begins executing.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "testSuiteWillStart"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)XCTestSuite",
          "text": "XCTestSuite"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.xctest/documentation/XCTest/XCTestObservation/testSuiteWillStart(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "testSuiteWillStart:"
        }
      ],
      "role": "symbol",
      "title": "testSuiteWillStart(_:)",
      "type": "topic",
      "url": "/documentation/xctest/xctestobservation/testsuitewillstart(_:)"
    },
    "doc://com.apple.xctest/documentation/XCTest/XCTestObservationCenter": {
      "abstract": [
        {
          "text": "Provides information about the progress of test runs to registered observers.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "XCTestObservationCenter"
        }
      ],
      "identifier": "doc://com.apple.xctest/documentation/XCTest/XCTestObservationCenter",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "XCTestObservationCenter"
        }
      ],
      "role": "symbol",
      "title": "XCTestObservationCenter",
      "type": "topic",
      "url": "/documentation/xctest/xctestobservationcenter"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)NSObject": {
      "abstract": [
        {
          "text": "The group of methods that are fundamental to all Objective-C objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "protocol "
        },
        {
          "kind": "identifier",
          "text": "NSObjectProtocol"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSObject",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSObjectProtocol",
      "type": "topic",
      "url": "/documentation/objectivec/nsobjectprotocol"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/c:objc(pl)NSObject"
      ],
      "kind": "relationships",
      "title": "Inherits From",
      "type": "inheritsFrom"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Test-Observation",
      "generated": true,
      "identifiers": [
        "doc://com.apple.xctest/documentation/XCTest/XCTestObservationCenter"
      ],
      "title": "Test Observation"
    }
  ],
  "topicSections": [
    {
      "anchor": "Observation-Methods",
      "identifiers": [
        "doc://com.apple.xctest/documentation/XCTest/XCTestObservation/testBundleWillStart(_:)",
        "doc://com.apple.xctest/documentation/XCTest/XCTestObservation/testSuiteWillStart(_:)",
        "doc://com.apple.xctest/documentation/XCTest/XCTestObservation/testCaseWillStart(_:)",
        "doc://com.apple.xctest/documentation/XCTest/XCTestObservation/testCase(_:didRecord:)-4cou6",
        "doc://com.apple.xctest/documentation/XCTest/XCTestObservation/testCase(_:didRecord:)-8k955",
        "doc://com.apple.xctest/documentation/XCTest/XCTestObservation/testCase(_:didFailWithDescription:inFile:atLine:)",
        "doc://com.apple.xctest/documentation/XCTest/XCTestObservation/testCaseDidFinish(_:)",
        "doc://com.apple.xctest/documentation/XCTest/XCTestObservation/testSuite(_:didRecord:)-3rk9k",
        "doc://com.apple.xctest/documentation/XCTest/XCTestObservation/testSuite(_:didRecord:)-1xjkv",
        "doc://com.apple.xctest/documentation/XCTest/XCTestObservation/testSuite(_:didFailWithDescription:inFile:atLine:)",
        "doc://com.apple.xctest/documentation/XCTest/XCTestObservation/testSuiteDidFinish(_:)",
        "doc://com.apple.xctest/documentation/XCTest/XCTestObservation/testBundleDidFinish(_:)"
      ],
      "title": "Observation Methods"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "add",
          "path": "/metadata/platforms",
          "value": null
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Protocol"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "XCTestObservation"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "protocol"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "XCTestObservation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "XCTestObservation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.xctest/documentation/XCTest"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Observation-Methods",
              "identifiers": [
                "doc://com.apple.xctest/documentation/XCTest/XCTestObservation/testBundleWillStart(_:)",
                "doc://com.apple.xctest/documentation/XCTest/XCTestObservation/testSuiteWillStart(_:)",
                "doc://com.apple.xctest/documentation/XCTest/XCTestObservation/testCaseWillStart(_:)",
                "doc://com.apple.xctest/documentation/XCTest/XCTestObservation/testCase(_:didRecord:)-4cou6",
                "doc://com.apple.xctest/documentation/XCTest/XCTestObservation/testCase(_:didRecord:)-8k955",
                "doc://com.apple.xctest/documentation/XCTest/XCTestObservation/testCase(_:didFailWithDescription:inFile:atLine:)",
                "doc://com.apple.xctest/documentation/XCTest/XCTestObservation/testCaseDidFinish(_:)",
                "doc://com.apple.xctest/documentation/XCTest/XCTestObservation/testSuite(_:didRecord:)-3rk9k",
                "doc://com.apple.xctest/documentation/XCTest/XCTestObservation/testSuite(_:didRecord:)-1xjkv",
                "doc://com.apple.xctest/documentation/XCTest/XCTestObservation/testSuite(_:didFailWithDescription:inFile:atLine:)",
                "doc://com.apple.xctest/documentation/XCTest/XCTestObservation/testSuiteDidFinish(_:)",
                "doc://com.apple.xctest/documentation/XCTest/XCTestObservation/testBundleDidFinish(_:)"
              ],
              "title": "Observation Methods"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": [
            {
              "identifiers": [
                "doc://com.externally.resolved.symbol/c:objc(pl)NSObject"
              ],
              "kind": "relationships",
              "title": "Inherits From",
              "type": "inheritsFrom"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Test-Observation",
              "generated": true,
              "identifiers": [
                "doc://com.apple.xctest/documentation/XCTest/XCTestObservationCenter"
              ],
              "title": "Test Observation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "@protocol"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "XCTestObservation"
                  },
                  {
                    "kind": "text",
                    "text": " <"
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSObject",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(pl)NSObject",
                    "text": "NSObject"
                  },
                  {
                    "kind": "text",
                    "text": ">"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCTestObservation~1testCase(_:didFailWithDescription:inFile:atLine:)/title",
          "value": "testCase:didFailWithDescription:inFile:atLine:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCTestObservation~1testCase(_:didFailWithDescription:inFile:atLine:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "testCase:didFailWithDescription:inFile:atLine:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCTestObservation~1testSuite(_:didFailWithDescription:inFile:atLine:)/title",
          "value": "testSuite:didFailWithDescription:inFile:atLine:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCTestObservation~1testSuite(_:didFailWithDescription:inFile:atLine:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "testSuite:didFailWithDescription:inFile:atLine:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCTestObservation~1testBundleWillStart(_:)/title",
          "value": "testBundleWillStart:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCTestObservation~1testBundleWillStart(_:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "testBundleWillStart:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCTestObservation~1testBundleDidFinish(_:)/title",
          "value": "testBundleDidFinish:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCTestObservation~1testBundleDidFinish(_:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "testBundleDidFinish:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCTestObservation~1testSuite(_:didRecord:)-1xjkv/title",
          "value": "testSuite:didRecordExpectedFailure:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCTestObservation~1testSuite(_:didRecord:)-1xjkv/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "testSuite:didRecordExpectedFailure:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCTestObservation~1testSuiteWillStart(_:)/title",
          "value": "testSuiteWillStart:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCTestObservation~1testSuiteWillStart(_:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "testSuiteWillStart:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCTestObservation/title",
          "value": "XCTestObservation"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCTestObservation/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "XCTestObservation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCTestObservation/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "XCTestObservation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCTestObservation~1testCase(_:didRecord:)-4cou6/title",
          "value": "testCase:didRecordIssue:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCTestObservation~1testCase(_:didRecord:)-4cou6/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "testCase:didRecordIssue:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:objc(pl)NSObject/title",
          "value": "NSObject"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCTestObservationCenter/title",
          "value": "XCTestObservationCenter"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCTestObservationCenter/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "XCTestObservationCenter"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCTestObservationCenter/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "XCTestObservationCenter"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCTestObservation~1testCaseDidFinish(_:)/title",
          "value": "testCaseDidFinish:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCTestObservation~1testCaseDidFinish(_:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "testCaseDidFinish:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCTestObservation~1testSuiteDidFinish(_:)/title",
          "value": "testSuiteDidFinish:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCTestObservation~1testSuiteDidFinish(_:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "testSuiteDidFinish:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCTestObservation~1testCaseWillStart(_:)/title",
          "value": "testCaseWillStart:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCTestObservation~1testCaseWillStart(_:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "testCaseWillStart:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCTestObservation~1testSuite(_:didRecord:)-3rk9k/title",
          "value": "testSuite:didRecordIssue:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCTestObservation~1testSuite(_:didRecord:)-3rk9k/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "testSuite:didRecordIssue:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCTestObservation~1testCase(_:didRecord:)-8k955/title",
          "value": "testCase:didRecordExpectedFailure:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCTestObservation~1testCase(_:didRecord:)-8k955/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "testCase:didRecordExpectedFailure:"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/xctest/xctestobservation"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/xctest/xctestobservation"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
