{
  "abstract": [
    {
      "text": "An object that represents a test failure, and includes source code call stacks for test reporting and investigation.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.xctest/documentation/XCTest"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.xctest/documentation/XCTest/XCTIssue-swift.struct"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "s:6XCTest8XCTIssueV",
    "fragments": [
      {
        "kind": "keyword",
        "text": "struct"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "XCTIssue"
      }
    ],
    "modules": [
      {
        "name": "XCTest"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "XCTIssue"
      }
    ],
    "role": "symbol",
    "roleHeading": "Structure",
    "symbolKind": "struct",
    "title": "XCTIssue"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "struct"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "XCTIssue"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.xctest/documentation/XCTest": {
      "abstract": [
        {
          "text": "Create and run unit tests, performance tests, and UI tests for your Xcode project.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.xctest/documentation/XCTest",
      "kind": "symbol",
      "role": "collection",
      "title": "XCTest",
      "type": "topic",
      "url": "/documentation/xctest"
    },
    "doc://com.apple.xctest/documentation/XCTest/XCTIssue-swift.struct": {
      "abstract": [
        {
          "text": "An object that represents a test failure, and includes source code call stacks for test reporting and investigation.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "XCTIssue"
        }
      ],
      "identifier": "doc://com.apple.xctest/documentation/XCTest/XCTIssue-swift.struct",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "XCTIssue"
        }
      ],
      "role": "symbol",
      "title": "XCTIssue",
      "type": "topic",
      "url": "/documentation/xctest/xctissue-swift.struct"
    },
    "doc://com.apple.xctest/documentation/XCTest/XCTIssue-swift.struct/IssueType": {
      "abstract": [
        {
          "text": "Constants that indicate types of test failures, such as assertion failures, performance regressions, or thrown errors.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "IssueType"
        }
      ],
      "identifier": "doc://com.apple.xctest/documentation/XCTest/XCTIssue-swift.struct/IssueType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "IssueType"
        }
      ],
      "role": "symbol",
      "title": "XCTIssue.IssueType",
      "type": "topic",
      "url": "/documentation/xctest/xctissue-swift.struct/issuetype"
    },
    "doc://com.apple.xctest/documentation/XCTest/XCTIssue-swift.struct/add(_:)": {
      "abstract": [
        {
          "text": "Adds supporting data to an issue.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "add"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)XCTAttachment",
          "text": "XCTAttachment"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.xctest/documentation/XCTest/XCTIssue-swift.struct/add(_:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "add(_:)",
      "type": "topic",
      "url": "/documentation/xctest/xctissue-swift.struct/add(_:)"
    },
    "doc://com.apple.xctest/documentation/XCTest/XCTIssue-swift.struct/associatedError": {
      "abstract": [
        {
          "text": "An optional error to associate with a test issue.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "associatedError"
        },
        {
          "kind": "text",
          "text": ": (any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5ErrorP",
          "text": "Error"
        },
        {
          "kind": "text",
          "text": ")?"
        }
      ],
      "identifier": "doc://com.apple.xctest/documentation/XCTest/XCTIssue-swift.struct/associatedError",
      "kind": "symbol",
      "role": "symbol",
      "title": "associatedError",
      "type": "topic",
      "url": "/documentation/xctest/xctissue-swift.struct/associatederror"
    },
    "doc://com.apple.xctest/documentation/XCTest/XCTIssue-swift.struct/attachments": {
      "abstract": [
        {
          "text": "An array of data that augments an issue, such as files, images, screenshots, data blobs, or ZIP files.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "attachments"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)XCTAttachment",
          "text": "XCTAttachment"
        },
        {
          "kind": "text",
          "text": "]"
        }
      ],
      "identifier": "doc://com.apple.xctest/documentation/XCTest/XCTIssue-swift.struct/attachments",
      "kind": "symbol",
      "role": "symbol",
      "title": "attachments",
      "type": "topic",
      "url": "/documentation/xctest/xctissue-swift.struct/attachments"
    },
    "doc://com.apple.xctest/documentation/XCTest/XCTIssue-swift.struct/compactDescription": {
      "abstract": [
        {
          "text": "A concise description of the issue with no transient data, suitable for use in test run summaries and results aggregation across multiple test runs.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "compactDescription"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.xctest/documentation/XCTest/XCTIssue-swift.struct/compactDescription",
      "kind": "symbol",
      "role": "symbol",
      "title": "compactDescription",
      "type": "topic",
      "url": "/documentation/xctest/xctissue-swift.struct/compactdescription"
    },
    "doc://com.apple.xctest/documentation/XCTest/XCTIssue-swift.struct/detailedDescription": {
      "abstract": [
        {
          "text": "A detailed description of the issue that may include transient data, such as numbers, object identifiers, and timestamps, to help diagnose the issue.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "detailedDescription"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.xctest/documentation/XCTest/XCTIssue-swift.struct/detailedDescription",
      "kind": "symbol",
      "role": "symbol",
      "title": "detailedDescription",
      "type": "topic",
      "url": "/documentation/xctest/xctissue-swift.struct/detaileddescription"
    },
    "doc://com.apple.xctest/documentation/XCTest/XCTIssue-swift.struct/init(type:compactDescription:detailedDescription:sourceCodeContext:associatedError:attachments:)": {
      "abstract": [
        {
          "text": "Creates an issue for a test failure, with descriptions, source code location, error, and attachments.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "type"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:6XCTest8XCTIssueV",
          "text": "XCTIssue"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:6XCTest8XCTIssueV9IssueTypea",
          "text": "IssueType"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "compactDescription"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "detailedDescription"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": "?, "
        },
        {
          "kind": "externalParam",
          "text": "sourceCodeContext"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)XCTSourceCodeContext",
          "text": "XCTSourceCodeContext"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "associatedError"
        },
        {
          "kind": "text",
          "text": ": (any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5ErrorP",
          "text": "Error"
        },
        {
          "kind": "text",
          "text": ")?, "
        },
        {
          "kind": "externalParam",
          "text": "attachments"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)XCTAttachment",
          "text": "XCTAttachment"
        },
        {
          "kind": "text",
          "text": "])"
        }
      ],
      "identifier": "doc://com.apple.xctest/documentation/XCTest/XCTIssue-swift.struct/init(type:compactDescription:detailedDescription:sourceCodeContext:associatedError:attachments:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "init(type:compactDescription:detailedDescription:sourceCodeContext:associatedError:attachments:)",
      "type": "topic",
      "url": "/documentation/xctest/xctissue-swift.struct/init(type:compactdescription:detaileddescription:sourcecodecontext:associatederror:attachments:)"
    },
    "doc://com.apple.xctest/documentation/XCTest/XCTIssue-swift.struct/sourceCodeContext": {
      "abstract": [
        {
          "text": "The source code location for the issue, including the filename, line number, and call stack.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "sourceCodeContext"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)XCTSourceCodeContext",
          "text": "XCTSourceCodeContext"
        }
      ],
      "identifier": "doc://com.apple.xctest/documentation/XCTest/XCTIssue-swift.struct/sourceCodeContext",
      "kind": "symbol",
      "role": "symbol",
      "title": "sourceCodeContext",
      "type": "topic",
      "url": "/documentation/xctest/xctissue-swift.struct/sourcecodecontext"
    },
    "doc://com.apple.xctest/documentation/XCTest/XCTIssue-swift.struct/type": {
      "abstract": [
        {
          "text": "A value for classifying an issue that occurs during testing.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "type"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:6XCTest8XCTIssueV",
          "text": "XCTIssue"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:6XCTest8XCTIssueV9IssueTypea",
          "text": "IssueType"
        }
      ],
      "identifier": "doc://com.apple.xctest/documentation/XCTest/XCTIssue-swift.struct/type",
      "kind": "symbol",
      "role": "symbol",
      "title": "type",
      "type": "topic",
      "url": "/documentation/xctest/xctissue-swift.struct/type"
    },
    "doc://com.apple.xctest/documentation/XCTest/XCTIssueReference": {
      "abstract": [
        {
          "text": "An object that represents a test failure, and includes source code call stacks for test reporting and investigation.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "XCTIssueReference"
        }
      ],
      "identifier": "doc://com.apple.xctest/documentation/XCTest/XCTIssueReference",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "XCTIssueReference"
        }
      ],
      "role": "symbol",
      "title": "XCTIssueReference",
      "type": "topic",
      "url": "/documentation/xctest/xctissuereference"
    },
    "doc://com.apple.xctest/documentation/XCTest/XCTMutableIssue": {
      "abstract": [
        {
          "text": "A mutable object that represents a test failure, and includes source code call stacks for test reporting and investigation.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "XCTMutableIssue"
        }
      ],
      "identifier": "doc://com.apple.xctest/documentation/XCTest/XCTMutableIssue",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "XCTMutableIssue"
        }
      ],
      "role": "symbol",
      "title": "XCTMutableIssue",
      "type": "topic",
      "url": "/documentation/xctest/xctmutableissue"
    },
    "doc://com.apple.xctest/documentation/XCTest/XCTSourceCodeContext": {
      "abstract": [
        {
          "text": "An object that contains call stack and source code location details to provide context for a point of execution in a test.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "XCTSourceCodeContext"
        }
      ],
      "identifier": "doc://com.apple.xctest/documentation/XCTest/XCTSourceCodeContext",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "XCTSourceCodeContext"
        }
      ],
      "role": "symbol",
      "title": "XCTSourceCodeContext",
      "type": "topic",
      "url": "/documentation/xctest/xctsourcecodecontext"
    },
    "doc://com.apple.xctest/documentation/XCTest/XCTSourceCodeFrame": {
      "abstract": [
        {
          "text": "An object that represents a single frame in a call stack that supports retrieval of symbol information for the address.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "XCTSourceCodeFrame"
        }
      ],
      "identifier": "doc://com.apple.xctest/documentation/XCTest/XCTSourceCodeFrame",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "XCTSourceCodeFrame"
        }
      ],
      "role": "symbol",
      "title": "XCTSourceCodeFrame",
      "type": "topic",
      "url": "/documentation/xctest/xctsourcecodeframe"
    },
    "doc://com.apple.xctest/documentation/XCTest/XCTSourceCodeLocation": {
      "abstract": [
        {
          "text": "An object that contains a file URL and line number that represents a distinct location in source code.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "XCTSourceCodeLocation"
        }
      ],
      "identifier": "doc://com.apple.xctest/documentation/XCTest/XCTSourceCodeLocation",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "XCTSourceCodeLocation"
        }
      ],
      "role": "symbol",
      "title": "XCTSourceCodeLocation",
      "type": "topic",
      "url": "/documentation/xctest/xctsourcecodelocation"
    },
    "doc://com.apple.xctest/documentation/XCTest/XCTSourceCodeSymbolInfo": {
      "abstract": [
        {
          "text": "An object that contains symbolication information for a specified frame in a call stack.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "XCTSourceCodeSymbolInfo"
        }
      ],
      "identifier": "doc://com.apple.xctest/documentation/XCTest/XCTSourceCodeSymbolInfo",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "XCTSourceCodeSymbolInfo"
        }
      ],
      "role": "symbol",
      "title": "XCTSourceCodeSymbolInfo",
      "type": "topic",
      "url": "/documentation/xctest/xctsourcecodesymbolinfo"
    },
    "doc://com.externally.resolved.symbol/s:SH": {
      "abstract": [
        {
          "text": "A type that can be hashed into a `Hasher` to produce an integer hash value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Hashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SQ",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SH",
      "kind": "symbol",
      "role": "symbol",
      "title": "Hashable",
      "type": "topic",
      "url": "/documentation/Swift/Hashable"
    },
    "doc://com.externally.resolved.symbol/s:SQ": {
      "abstract": [
        {
          "text": "A type that can be compared for value equality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SQ",
      "kind": "symbol",
      "role": "symbol",
      "title": "Equatable",
      "type": "topic",
      "url": "/documentation/Swift/Equatable"
    },
    "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP": {
      "abstract": [
        {
          "text": "A type with a customized textual representation.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CustomStringConvertible"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CustomStringConvertible",
      "type": "topic",
      "url": "/documentation/Swift/CustomStringConvertible"
    },
    "doc://com.externally.resolved.symbol/s:s8CopyableP": {
      "abstract": [
        {
          "text": "A type whose values can be implicitly or explicitly copied.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Copyable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s8CopyableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "Copyable",
      "type": "topic",
      "url": "/documentation/Swift/Copyable"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:s8CopyableP",
        "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP",
        "doc://com.externally.resolved.symbol/s:SQ",
        "doc://com.externally.resolved.symbol/s:SH"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Test-Failures",
      "generated": true,
      "identifiers": [
        "doc://com.apple.xctest/documentation/XCTest/XCTIssueReference",
        "doc://com.apple.xctest/documentation/XCTest/XCTMutableIssue",
        "doc://com.apple.xctest/documentation/XCTest/XCTSourceCodeContext",
        "doc://com.apple.xctest/documentation/XCTest/XCTSourceCodeFrame",
        "doc://com.apple.xctest/documentation/XCTest/XCTSourceCodeLocation",
        "doc://com.apple.xctest/documentation/XCTest/XCTSourceCodeSymbolInfo"
      ],
      "title": "Test Failures"
    }
  ],
  "topicSections": [
    {
      "anchor": "Initializers",
      "identifiers": [
        "doc://com.apple.xctest/documentation/XCTest/XCTIssue-swift.struct/init(type:compactDescription:detailedDescription:sourceCodeContext:associatedError:attachments:)"
      ],
      "title": "Initializers"
    },
    {
      "anchor": "Issue-Types",
      "identifiers": [
        "doc://com.apple.xctest/documentation/XCTest/XCTIssue-swift.struct/IssueType"
      ],
      "title": "Issue Types"
    },
    {
      "anchor": "Issue-Details",
      "identifiers": [
        "doc://com.apple.xctest/documentation/XCTest/XCTIssue-swift.struct/type",
        "doc://com.apple.xctest/documentation/XCTest/XCTIssue-swift.struct/compactDescription",
        "doc://com.apple.xctest/documentation/XCTest/XCTIssue-swift.struct/detailedDescription",
        "doc://com.apple.xctest/documentation/XCTest/XCTIssue-swift.struct/sourceCodeContext",
        "doc://com.apple.xctest/documentation/XCTest/XCTIssue-swift.struct/associatedError",
        "doc://com.apple.xctest/documentation/XCTest/XCTIssue-swift.struct/attachments",
        "doc://com.apple.xctest/documentation/XCTest/XCTIssue-swift.struct/add(_:)"
      ],
      "title": "Issue Details"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCTMutableIssue/title",
          "value": "XCTMutableIssue"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCTMutableIssue/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "XCTMutableIssue"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCTMutableIssue/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "XCTMutableIssue"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCTSourceCodeLocation/title",
          "value": "XCTSourceCodeLocation"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCTSourceCodeLocation/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "XCTSourceCodeLocation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCTSourceCodeLocation/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "XCTSourceCodeLocation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCTSourceCodeFrame/title",
          "value": "XCTSourceCodeFrame"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCTSourceCodeFrame/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "XCTSourceCodeFrame"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCTSourceCodeFrame/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "XCTSourceCodeFrame"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCTSourceCodeContext/title",
          "value": "XCTSourceCodeContext"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCTSourceCodeContext/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "XCTSourceCodeContext"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCTSourceCodeContext/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "XCTSourceCodeContext"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCTIssueReference/title",
          "value": "XCTIssue"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCTIssueReference/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "XCTIssue"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCTIssueReference/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "XCTIssue"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCTSourceCodeSymbolInfo/title",
          "value": "XCTSourceCodeSymbolInfo"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCTSourceCodeSymbolInfo/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "XCTSourceCodeSymbolInfo"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCTSourceCodeSymbolInfo/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "XCTSourceCodeSymbolInfo"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/xctest/xctissue-swift.struct"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    }
  ]
}
