{
  "abstract": [
    {
      "text": "An expectation that a specific key-value observing (KVO) condition fulfills.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.xctest/documentation/XCTest"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.xctest/documentation/XCTest/XCTKVOExpectation"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(cs)XCTKVOExpectation",
    "fragments": [
      {
        "kind": "keyword",
        "text": "class"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "XCTKVOExpectation"
      }
    ],
    "modules": [
      {
        "name": "XCTest"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "XCTKVOExpectation"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "message": "Replaced by 'XCTKeyPathExpectation'",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "message": "Replaced by 'XCTKeyPathExpectation'",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "message": "Replaced by 'XCTKeyPathExpectation'",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "11.0",
        "message": "Replaced by 'XCTKeyPathExpectation'",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "message": "Replaced by 'XCTKeyPathExpectation'",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "1.0",
        "message": "Replaced by 'XCTKeyPathExpectation'",
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "9.0",
        "message": "Replaced by 'XCTKeyPathExpectation'",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Class",
    "symbolKind": "class",
    "title": "XCTKVOExpectation"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "class"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "XCTKVOExpectation"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Apple discourages the use of this symbol in Swift. Use ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.xctest/documentation/XCTest/XCTKeyPathExpectation",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " instead.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.xctest/documentation/XCTest": {
      "abstract": [
        {
          "text": "Create and run unit tests, performance tests, and UI tests for your Xcode project.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.xctest/documentation/XCTest",
      "kind": "symbol",
      "role": "collection",
      "title": "XCTest",
      "type": "topic",
      "url": "/documentation/xctest"
    },
    "doc://com.apple.xctest/documentation/XCTest/XCTKVOExpectation": {
      "abstract": [
        {
          "text": "An expectation that a specific key-value observing (KVO) condition fulfills.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "XCTKVOExpectation"
        }
      ],
      "identifier": "doc://com.apple.xctest/documentation/XCTest/XCTKVOExpectation",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "XCTKVOExpectation"
        }
      ],
      "role": "symbol",
      "title": "XCTKVOExpectation",
      "type": "topic",
      "url": "/documentation/xctest/xctkvoexpectation"
    },
    "doc://com.apple.xctest/documentation/XCTest/XCTKVOExpectation/Handler-swift.typealias": {
      "abstract": [
        {
          "text": "A custom handler to call when observing a KVO change for a specified key path.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Handler"
        }
      ],
      "identifier": "doc://com.apple.xctest/documentation/XCTest/XCTKVOExpectation/Handler-swift.typealias",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "Handler"
        }
      ],
      "role": "symbol",
      "title": "XCTKVOExpectation.Handler",
      "type": "topic",
      "url": "/documentation/xctest/xctkvoexpectation/handler-swift.typealias"
    },
    "doc://com.apple.xctest/documentation/XCTest/XCTKVOExpectation/expectedValue": {
      "abstract": [
        {
          "text": "The value that the key path’s specified property must equal to fulfill the expectation.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "expectedValue"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "keyword",
          "text": "Any"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.xctest/documentation/XCTest/XCTKVOExpectation/expectedValue",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "expectedValue"
        }
      ],
      "role": "symbol",
      "title": "expectedValue",
      "type": "topic",
      "url": "/documentation/xctest/xctkvoexpectation/expectedvalue"
    },
    "doc://com.apple.xctest/documentation/XCTest/XCTKVOExpectation/handler-swift.property": {
      "abstract": [
        {
          "text": "An optional handler that performs custom evaluation of changes to the observed key path.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "handler"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)XCTKVOExpectation",
          "text": "XCTKVOExpectation"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@XCKeyValueObservingExpectationHandler",
          "text": "Handler"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.xctest/documentation/XCTest/XCTKVOExpectation/handler-swift.property",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "handler"
        }
      ],
      "role": "symbol",
      "title": "handler",
      "type": "topic",
      "url": "/documentation/xctest/xctkvoexpectation/handler-swift.property"
    },
    "doc://com.apple.xctest/documentation/XCTest/XCTKVOExpectation/init(keyPath:object:)": {
      "abstract": [
        {
          "text": "Creates an expectation that any KVO change to the specified key path of the observed object fulfills.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "convenience"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "keyPath"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "object"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "keyword",
          "text": "Any"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.xctest/documentation/XCTest/XCTKVOExpectation/init(keyPath:object:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "initWithKeyPath:object:"
        }
      ],
      "role": "symbol",
      "title": "init(keyPath:object:)",
      "type": "topic",
      "url": "/documentation/xctest/xctkvoexpectation/init(keypath:object:)"
    },
    "doc://com.apple.xctest/documentation/XCTest/XCTKVOExpectation/init(keyPath:object:expectedValue:)": {
      "abstract": [
        {
          "text": "Creates an expectation a KVO change fulfills when it causes the specified key path of the observed object to have an expected value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "convenience"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "keyPath"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "object"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "keyword",
          "text": "Any"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "expectedValue"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "keyword",
          "text": "Any"
        },
        {
          "kind": "text",
          "text": "?)"
        }
      ],
      "identifier": "doc://com.apple.xctest/documentation/XCTest/XCTKVOExpectation/init(keyPath:object:expectedValue:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "initWithKeyPath:object:expectedValue:"
        }
      ],
      "role": "symbol",
      "title": "init(keyPath:object:expectedValue:)",
      "type": "topic",
      "url": "/documentation/xctest/xctkvoexpectation/init(keypath:object:expectedvalue:)"
    },
    "doc://com.apple.xctest/documentation/XCTest/XCTKVOExpectation/init(keyPath:object:expectedValue:options:)": {
      "abstract": [
        {
          "text": "Creates an expectation with custom observation options that a KVO change fulfills when it causes the specified key path of the observed object to have an expected value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "keyPath"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "object"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "keyword",
          "text": "Any"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "expectedValue"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "keyword",
          "text": "Any"
        },
        {
          "kind": "text",
          "text": "?, "
        },
        {
          "kind": "externalParam",
          "text": "options"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@NSKeyValueObservingOptions",
          "text": "NSKeyValueObservingOptions"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.xctest/documentation/XCTest/XCTKVOExpectation/init(keyPath:object:expectedValue:options:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "initWithKeyPath:object:expectedValue:options:"
        }
      ],
      "role": "symbol",
      "title": "init(keyPath:object:expectedValue:options:)",
      "type": "topic",
      "url": "/documentation/xctest/xctkvoexpectation/init(keypath:object:expectedvalue:options:)"
    },
    "doc://com.apple.xctest/documentation/XCTest/XCTKVOExpectation/keyPath": {
      "abstract": [
        {
          "text": "The key path the system observes for KVO changes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "keyPath"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.xctest/documentation/XCTest/XCTKVOExpectation/keyPath",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "keyPath"
        }
      ],
      "role": "symbol",
      "title": "keyPath",
      "type": "topic",
      "url": "/documentation/xctest/xctkvoexpectation/keypath"
    },
    "doc://com.apple.xctest/documentation/XCTest/XCTKVOExpectation/observedObject": {
      "abstract": [
        {
          "text": "The object that the system observes for KVO changes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "observedObject"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "keyword",
          "text": "Any"
        }
      ],
      "identifier": "doc://com.apple.xctest/documentation/XCTest/XCTKVOExpectation/observedObject",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "observedObject"
        }
      ],
      "role": "symbol",
      "title": "observedObject",
      "type": "topic",
      "url": "/documentation/xctest/xctkvoexpectation/observedobject"
    },
    "doc://com.apple.xctest/documentation/XCTest/XCTKVOExpectation/options": {
      "abstract": [
        {
          "text": "The key-value observing options the expectation uses when registering for observation.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "options"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@NSKeyValueObservingOptions",
          "text": "NSKeyValueObservingOptions"
        }
      ],
      "identifier": "doc://com.apple.xctest/documentation/XCTest/XCTKVOExpectation/options",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "options"
        }
      ],
      "role": "symbol",
      "title": "options",
      "type": "topic",
      "url": "/documentation/xctest/xctkvoexpectation/options"
    },
    "doc://com.apple.xctest/documentation/XCTest/XCTKeyPathExpectation": {
      "abstract": [
        {
          "text": "An expectation that a specific key-value observing (KVO) condition fulfills.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "XCTKeyPathExpectation"
        }
      ],
      "identifier": "doc://com.apple.xctest/documentation/XCTest/XCTKeyPathExpectation",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "XCTKeyPathExpectation"
        }
      ],
      "role": "symbol",
      "title": "XCTKeyPathExpectation",
      "type": "topic",
      "url": "/documentation/xctest/xctkeypathexpectation"
    },
    "doc://com.apple.xctest/documentation/XCTest/XCTestExpectation": {
      "abstract": [
        {
          "text": "An expected outcome in an asynchronous test.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "XCTestExpectation"
        }
      ],
      "identifier": "doc://com.apple.xctest/documentation/XCTest/XCTestExpectation",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "XCTestExpectation"
        }
      ],
      "role": "symbol",
      "title": "XCTestExpectation",
      "type": "topic",
      "url": "/documentation/xctest/xctestexpectation"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)NSObject": {
      "abstract": [
        {
          "text": "The group of methods that are fundamental to all Objective-C objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "protocol "
        },
        {
          "kind": "identifier",
          "text": "NSObjectProtocol"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSObject",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSObjectProtocol",
      "type": "topic",
      "url": "/documentation/objectivec/nsobjectprotocol"
    },
    "doc://com.externally.resolved.symbol/s:SH": {
      "abstract": [
        {
          "text": "A type that can be hashed into a `Hasher` to produce an integer hash value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Hashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SQ",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SH",
      "kind": "symbol",
      "role": "symbol",
      "title": "Hashable",
      "type": "topic",
      "url": "/documentation/Swift/Hashable"
    },
    "doc://com.externally.resolved.symbol/s:SQ": {
      "abstract": [
        {
          "text": "A type that can be compared for value equality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SQ",
      "kind": "symbol",
      "role": "symbol",
      "title": "Equatable",
      "type": "topic",
      "url": "/documentation/Swift/Equatable"
    },
    "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP": {
      "abstract": [
        {
          "text": "A type with a customized textual representation.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CustomStringConvertible"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CustomStringConvertible",
      "type": "topic",
      "url": "/documentation/Swift/CustomStringConvertible"
    },
    "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP": {
      "abstract": [
        {
          "text": "A type with a customized textual representation suitable for debugging purposes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CustomDebugStringConvertible"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CustomDebugStringConvertible",
      "type": "topic",
      "url": "/documentation/Swift/CustomDebugStringConvertible"
    },
    "doc://com.externally.resolved.symbol/s:s7CVarArgP": {
      "abstract": [
        {
          "text": "A type whose instances can be encoded, and appropriately passed, as elements of a C `va_list`.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CVarArg"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s7CVarArgP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CVarArg",
      "type": "topic",
      "url": "/documentation/Swift/CVarArg"
    },
    "doc://com.externally.resolved.symbol/s:s8SendableP": {
      "abstract": [
        {
          "text": "A thread-safe type whose values can be shared across arbitrary concurrent contexts without introducing a risk of data races.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Sendable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s8SendableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "Sendable",
      "type": "topic",
      "url": "/documentation/Swift/Sendable"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.apple.xctest/documentation/XCTest/XCTestExpectation"
      ],
      "kind": "relationships",
      "title": "Inherits From",
      "type": "inheritsFrom"
    },
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:s7CVarArgP",
        "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP",
        "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP",
        "doc://com.externally.resolved.symbol/s:SQ",
        "doc://com.externally.resolved.symbol/s:SH",
        "doc://com.externally.resolved.symbol/c:objc(pl)NSObject",
        "doc://com.externally.resolved.symbol/s:s8SendableP"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Key-Value-Observing-Expectations",
      "generated": true,
      "identifiers": [
        "doc://com.apple.xctest/documentation/XCTest/XCTKeyPathExpectation"
      ],
      "title": "Key Value Observing Expectations"
    }
  ],
  "topicSections": [
    {
      "anchor": "Creating-KVO-expectations",
      "identifiers": [
        "doc://com.apple.xctest/documentation/XCTest/XCTKVOExpectation/init(keyPath:object:)",
        "doc://com.apple.xctest/documentation/XCTest/XCTKVOExpectation/init(keyPath:object:expectedValue:)",
        "doc://com.apple.xctest/documentation/XCTest/XCTKVOExpectation/init(keyPath:object:expectedValue:options:)"
      ],
      "title": "Creating KVO expectations"
    },
    {
      "anchor": "Expectation-properties",
      "identifiers": [
        "doc://com.apple.xctest/documentation/XCTest/XCTKVOExpectation/keyPath",
        "doc://com.apple.xctest/documentation/XCTest/XCTKVOExpectation/observedObject",
        "doc://com.apple.xctest/documentation/XCTest/XCTKVOExpectation/expectedValue",
        "doc://com.apple.xctest/documentation/XCTest/XCTKVOExpectation/options"
      ],
      "title": "Expectation properties"
    },
    {
      "anchor": "Custom-KVO-evaluation",
      "identifiers": [
        "doc://com.apple.xctest/documentation/XCTest/XCTKVOExpectation/handler-swift.property",
        "doc://com.apple.xctest/documentation/XCTest/XCTKVOExpectation/Handler-swift.typealias"
      ],
      "title": "Custom KVO evaluation"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": null
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Class"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "XCTKVOExpectation"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "class"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "XCTKVOExpectation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "XCTKVOExpectation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.xctest/documentation/XCTest"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Creating-KVO-expectations",
              "identifiers": [
                "doc://com.apple.xctest/documentation/XCTest/XCTKVOExpectation/init(keyPath:object:)",
                "doc://com.apple.xctest/documentation/XCTest/XCTKVOExpectation/init(keyPath:object:expectedValue:)",
                "doc://com.apple.xctest/documentation/XCTest/XCTKVOExpectation/init(keyPath:object:expectedValue:options:)"
              ],
              "title": "Creating KVO expectations"
            },
            {
              "anchor": "Expectation-properties",
              "identifiers": [
                "doc://com.apple.xctest/documentation/XCTest/XCTKVOExpectation/keyPath",
                "doc://com.apple.xctest/documentation/XCTest/XCTKVOExpectation/observedObject",
                "doc://com.apple.xctest/documentation/XCTest/XCTKVOExpectation/expectedValue",
                "doc://com.apple.xctest/documentation/XCTest/XCTKVOExpectation/options"
              ],
              "title": "Expectation properties"
            },
            {
              "anchor": "Custom-KVO-evaluation",
              "identifiers": [
                "doc://com.apple.xctest/documentation/XCTest/XCTKVOExpectation/handler-swift.property",
                "doc://com.apple.xctest/documentation/XCTest/XCTKVOExpectation/Handler-swift.typealias"
              ],
              "title": "Custom KVO evaluation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": [
            {
              "identifiers": [
                "doc://com.apple.xctest/documentation/XCTest/XCTestExpectation"
              ],
              "kind": "relationships",
              "title": "Inherits From",
              "type": "inheritsFrom"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "@interface"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "XCTKVOExpectation"
                  },
                  {
                    "kind": "text",
                    "text": " : "
                  },
                  {
                    "identifier": "doc://com.apple.xctest/documentation/XCTest/XCTestExpectation",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(cs)XCTestExpectation",
                    "text": "XCTestExpectation"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "add",
          "path": "/deprecationSummary",
          "value": []
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCTKVOExpectation~1handler-swift.property/title",
          "value": "handler"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCTKVOExpectation~1handler-swift.property/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "handler"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCTKVOExpectation~1options/title",
          "value": "options"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCTKVOExpectation~1options/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "options"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCTKVOExpectation/title",
          "value": "XCTKVOExpectation"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCTKVOExpectation/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "XCTKVOExpectation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCTKVOExpectation/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "XCTKVOExpectation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCTKVOExpectation~1init(keyPath:object:expectedValue:)/title",
          "value": "initWithKeyPath:object:expectedValue:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCTKVOExpectation~1init(keyPath:object:expectedValue:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "initWithKeyPath:object:expectedValue:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCTKVOExpectation~1expectedValue/title",
          "value": "expectedValue"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCTKVOExpectation~1expectedValue/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "expectedValue"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:objc(pl)NSObject/title",
          "value": "NSObject"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCTKVOExpectation~1init(keyPath:object:)/title",
          "value": "initWithKeyPath:object:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCTKVOExpectation~1init(keyPath:object:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "initWithKeyPath:object:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCTKVOExpectation~1Handler-swift.typealias/title",
          "value": "XCKeyValueObservingExpectationHandler"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCTKVOExpectation~1Handler-swift.typealias/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "XCKeyValueObservingExpectationHandler"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCTKVOExpectation~1Handler-swift.typealias/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "XCKeyValueObservingExpectationHandler"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCTKVOExpectation~1init(keyPath:object:expectedValue:options:)/title",
          "value": "initWithKeyPath:object:expectedValue:options:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCTKVOExpectation~1init(keyPath:object:expectedValue:options:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "initWithKeyPath:object:expectedValue:options:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCTestExpectation/title",
          "value": "XCTestExpectation"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCTestExpectation/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "XCTestExpectation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCTestExpectation/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "XCTestExpectation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCTKVOExpectation~1observedObject/title",
          "value": "observedObject"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCTKVOExpectation~1observedObject/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "observedObject"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCTKVOExpectation~1keyPath/title",
          "value": "keyPath"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCTKVOExpectation~1keyPath/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "keyPath"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/xctest/xctkvoexpectation"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/xctest/xctkvoexpectation"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
