{
  "abstract": [
    {
      "text": "An expectation that is fulfilled when an expected ",
      "type": "text"
    },
    {
      "code": "NSNotification",
      "type": "codeVoice"
    },
    {
      "text": " is received.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.xctest/documentation/XCTest"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.xctest/documentation/XCTest/XCTNSNotificationExpectation"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(cs)XCTNSNotificationExpectation",
    "fragments": [
      {
        "kind": "keyword",
        "text": "class"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "XCTNSNotificationExpectation"
      }
    ],
    "modules": [
      {
        "name": "XCTest"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "XCTNSNotificationExpectation"
      }
    ],
    "role": "symbol",
    "roleHeading": "Class",
    "symbolKind": "class",
    "title": "XCTNSNotificationExpectation"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "class"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "XCTNSNotificationExpectation"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.xctest/documentation/XCTest": {
      "abstract": [
        {
          "text": "Create and run unit tests, performance tests, and UI tests for your Xcode project.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.xctest/documentation/XCTest",
      "kind": "symbol",
      "role": "collection",
      "title": "XCTest",
      "type": "topic",
      "url": "/documentation/xctest"
    },
    "doc://com.apple.xctest/documentation/XCTest/XCTDarwinNotificationExpectation": {
      "abstract": [
        {
          "text": "An expectation that is fulfilled when an expected Darwin notification is received.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "XCTDarwinNotificationExpectation"
        }
      ],
      "identifier": "doc://com.apple.xctest/documentation/XCTest/XCTDarwinNotificationExpectation",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "XCTDarwinNotificationExpectation"
        }
      ],
      "role": "symbol",
      "title": "XCTDarwinNotificationExpectation",
      "type": "topic",
      "url": "/documentation/xctest/xctdarwinnotificationexpectation"
    },
    "doc://com.apple.xctest/documentation/XCTest/XCTNSNotificationExpectation": {
      "abstract": [
        {
          "text": "An expectation that is fulfilled when an expected ",
          "type": "text"
        },
        {
          "code": "NSNotification",
          "type": "codeVoice"
        },
        {
          "text": " is received.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "XCTNSNotificationExpectation"
        }
      ],
      "identifier": "doc://com.apple.xctest/documentation/XCTest/XCTNSNotificationExpectation",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "XCTNSNotificationExpectation"
        }
      ],
      "role": "symbol",
      "title": "XCTNSNotificationExpectation",
      "type": "topic",
      "url": "/documentation/xctest/xctnsnotificationexpectation"
    },
    "doc://com.apple.xctest/documentation/XCTest/XCTNSNotificationExpectation/Handler-swift.typealias": {
      "abstract": [
        {
          "text": "A custom handler to be called when a matching notification is received.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Handler"
        }
      ],
      "identifier": "doc://com.apple.xctest/documentation/XCTest/XCTNSNotificationExpectation/Handler-swift.typealias",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "Handler"
        }
      ],
      "role": "symbol",
      "title": "XCTNSNotificationExpectation.Handler",
      "type": "topic",
      "url": "/documentation/xctest/xctnsnotificationexpectation/handler-swift.typealias"
    },
    "doc://com.apple.xctest/documentation/XCTest/XCTNSNotificationExpectation/handler-swift.property": {
      "abstract": [
        {
          "text": "An optional handler that performs custom evaluation of matching notifications.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "handler"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)XCTNSNotificationExpectation",
          "text": "XCTNSNotificationExpectation"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@XCNotificationExpectationHandler",
          "text": "Handler"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.xctest/documentation/XCTest/XCTNSNotificationExpectation/handler-swift.property",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "handler"
        }
      ],
      "role": "symbol",
      "title": "handler",
      "type": "topic",
      "url": "/documentation/xctest/xctnsnotificationexpectation/handler-swift.property"
    },
    "doc://com.apple.xctest/documentation/XCTest/XCTNSNotificationExpectation/init(name:)": {
      "abstract": [
        {
          "text": "Creates an expectation that is fulfilled when an ",
          "type": "text"
        },
        {
          "code": "NSNotification",
          "type": "codeVoice"
        },
        {
          "text": " is posted from the default notification center by any object.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "convenience"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "name"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSNotification",
          "text": "NSNotification"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSNotificationName",
          "text": "Name"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.xctest/documentation/XCTest/XCTNSNotificationExpectation/init(name:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "initWithName:"
        }
      ],
      "role": "symbol",
      "title": "init(name:)",
      "type": "topic",
      "url": "/documentation/xctest/xctnsnotificationexpectation/init(name:)"
    },
    "doc://com.apple.xctest/documentation/XCTest/XCTNSNotificationExpectation/init(name:object:)": {
      "abstract": [
        {
          "text": "Creates an expectation that is fulfilled when an ",
          "type": "text"
        },
        {
          "code": "NSNotification",
          "type": "codeVoice"
        },
        {
          "text": " is posted from the default notification center by a specific object.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "convenience"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "name"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSNotification",
          "text": "NSNotification"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSNotificationName",
          "text": "Name"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "object"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "keyword",
          "text": "Any"
        },
        {
          "kind": "text",
          "text": "?)"
        }
      ],
      "identifier": "doc://com.apple.xctest/documentation/XCTest/XCTNSNotificationExpectation/init(name:object:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "initWithName:object:"
        }
      ],
      "role": "symbol",
      "title": "init(name:object:)",
      "type": "topic",
      "url": "/documentation/xctest/xctnsnotificationexpectation/init(name:object:)"
    },
    "doc://com.apple.xctest/documentation/XCTest/XCTNSNotificationExpectation/init(name:object:notificationCenter:)": {
      "abstract": [
        {
          "text": "Creates an expectation that is fulfilled when an ",
          "type": "text"
        },
        {
          "code": "NSNotification",
          "type": "codeVoice"
        },
        {
          "text": " is posted from a specific notification center, optionally by a specific object.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "name"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSNotification",
          "text": "NSNotification"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSNotificationName",
          "text": "Name"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "object"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "keyword",
          "text": "Any"
        },
        {
          "kind": "text",
          "text": "?, "
        },
        {
          "kind": "externalParam",
          "text": "notificationCenter"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSNotificationCenter",
          "text": "NotificationCenter"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.xctest/documentation/XCTest/XCTNSNotificationExpectation/init(name:object:notificationCenter:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "initWithName:object:notificationCenter:"
        }
      ],
      "role": "symbol",
      "title": "init(name:object:notificationCenter:)",
      "type": "topic",
      "url": "/documentation/xctest/xctnsnotificationexpectation/init(name:object:notificationcenter:)"
    },
    "doc://com.apple.xctest/documentation/XCTest/XCTNSNotificationExpectation/notificationCenter": {
      "abstract": [
        {
          "text": "The notification center from which the notification must be posted.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "notificationCenter"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSNotificationCenter",
          "text": "NotificationCenter"
        }
      ],
      "identifier": "doc://com.apple.xctest/documentation/XCTest/XCTNSNotificationExpectation/notificationCenter",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "notificationCenter"
        }
      ],
      "role": "symbol",
      "title": "notificationCenter",
      "type": "topic",
      "url": "/documentation/xctest/xctnsnotificationexpectation/notificationcenter"
    },
    "doc://com.apple.xctest/documentation/XCTest/XCTNSNotificationExpectation/notificationName": {
      "abstract": [
        {
          "text": "The name of the notification that the expectation is waiting for.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "notificationName"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSNotification",
          "text": "NSNotification"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSNotificationName",
          "text": "Name"
        }
      ],
      "identifier": "doc://com.apple.xctest/documentation/XCTest/XCTNSNotificationExpectation/notificationName",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "notificationName"
        }
      ],
      "role": "symbol",
      "title": "notificationName",
      "type": "topic",
      "url": "/documentation/xctest/xctnsnotificationexpectation/notificationname"
    },
    "doc://com.apple.xctest/documentation/XCTest/XCTNSNotificationExpectation/observedObject": {
      "abstract": [
        {
          "text": "The object by which the notification must be posted, or nil if the notification can be posted by any object.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "observedObject"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "keyword",
          "text": "Any"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.xctest/documentation/XCTest/XCTNSNotificationExpectation/observedObject",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "observedObject"
        }
      ],
      "role": "symbol",
      "title": "observedObject",
      "type": "topic",
      "url": "/documentation/xctest/xctnsnotificationexpectation/observedobject"
    },
    "doc://com.apple.xctest/documentation/XCTest/XCTestExpectation": {
      "abstract": [
        {
          "text": "An expected outcome in an asynchronous test.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "XCTestExpectation"
        }
      ],
      "identifier": "doc://com.apple.xctest/documentation/XCTest/XCTestExpectation",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "XCTestExpectation"
        }
      ],
      "role": "symbol",
      "title": "XCTestExpectation",
      "type": "topic",
      "url": "/documentation/xctest/xctestexpectation"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)NSObject": {
      "abstract": [
        {
          "text": "The group of methods that are fundamental to all Objective-C objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "protocol "
        },
        {
          "kind": "identifier",
          "text": "NSObjectProtocol"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSObject",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSObjectProtocol",
      "type": "topic",
      "url": "/documentation/objectivec/nsobjectprotocol"
    },
    "doc://com.externally.resolved.symbol/s:SH": {
      "abstract": [
        {
          "text": "A type that can be hashed into a `Hasher` to produce an integer hash value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Hashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SQ",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SH",
      "kind": "symbol",
      "role": "symbol",
      "title": "Hashable",
      "type": "topic",
      "url": "/documentation/Swift/Hashable"
    },
    "doc://com.externally.resolved.symbol/s:SQ": {
      "abstract": [
        {
          "text": "A type that can be compared for value equality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SQ",
      "kind": "symbol",
      "role": "symbol",
      "title": "Equatable",
      "type": "topic",
      "url": "/documentation/Swift/Equatable"
    },
    "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP": {
      "abstract": [
        {
          "text": "A type with a customized textual representation.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CustomStringConvertible"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CustomStringConvertible",
      "type": "topic",
      "url": "/documentation/Swift/CustomStringConvertible"
    },
    "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP": {
      "abstract": [
        {
          "text": "A type with a customized textual representation suitable for debugging purposes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CustomDebugStringConvertible"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CustomDebugStringConvertible",
      "type": "topic",
      "url": "/documentation/Swift/CustomDebugStringConvertible"
    },
    "doc://com.externally.resolved.symbol/s:s7CVarArgP": {
      "abstract": [
        {
          "text": "A type whose instances can be encoded, and appropriately passed, as elements of a C `va_list`.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CVarArg"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s7CVarArgP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CVarArg",
      "type": "topic",
      "url": "/documentation/Swift/CVarArg"
    },
    "doc://com.externally.resolved.symbol/s:s8SendableP": {
      "abstract": [
        {
          "text": "A thread-safe type whose values can be shared across arbitrary concurrent contexts without introducing a risk of data races.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Sendable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s8SendableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "Sendable",
      "type": "topic",
      "url": "/documentation/Swift/Sendable"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.apple.xctest/documentation/XCTest/XCTestExpectation"
      ],
      "kind": "relationships",
      "title": "Inherits From",
      "type": "inheritsFrom"
    },
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:s7CVarArgP",
        "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP",
        "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP",
        "doc://com.externally.resolved.symbol/s:SQ",
        "doc://com.externally.resolved.symbol/s:SH",
        "doc://com.externally.resolved.symbol/c:objc(pl)NSObject",
        "doc://com.externally.resolved.symbol/s:s8SendableP"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Notification-Based-Expectations",
      "generated": true,
      "identifiers": [
        "doc://com.apple.xctest/documentation/XCTest/XCTDarwinNotificationExpectation"
      ],
      "title": "Notification-Based Expectations"
    }
  ],
  "topicSections": [
    {
      "anchor": "Creating-NSNotification-Expectations",
      "identifiers": [
        "doc://com.apple.xctest/documentation/XCTest/XCTNSNotificationExpectation/init(name:)",
        "doc://com.apple.xctest/documentation/XCTest/XCTNSNotificationExpectation/init(name:object:)",
        "doc://com.apple.xctest/documentation/XCTest/XCTNSNotificationExpectation/init(name:object:notificationCenter:)"
      ],
      "title": "Creating NSNotification Expectations"
    },
    {
      "anchor": "Expectation-Properties",
      "identifiers": [
        "doc://com.apple.xctest/documentation/XCTest/XCTNSNotificationExpectation/notificationName",
        "doc://com.apple.xctest/documentation/XCTest/XCTNSNotificationExpectation/observedObject",
        "doc://com.apple.xctest/documentation/XCTest/XCTNSNotificationExpectation/notificationCenter"
      ],
      "title": "Expectation Properties"
    },
    {
      "anchor": "Custom-Notification-Evaluation",
      "identifiers": [
        "doc://com.apple.xctest/documentation/XCTest/XCTNSNotificationExpectation/handler-swift.property",
        "doc://com.apple.xctest/documentation/XCTest/XCTNSNotificationExpectation/Handler-swift.typealias"
      ],
      "title": "Custom Notification Evaluation"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "add",
          "path": "/metadata/platforms",
          "value": null
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Class"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "XCTNSNotificationExpectation"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "class"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "XCTNSNotificationExpectation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "XCTNSNotificationExpectation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.xctest/documentation/XCTest"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Creating-NSNotification-Expectations",
              "identifiers": [
                "doc://com.apple.xctest/documentation/XCTest/XCTNSNotificationExpectation/init(name:)",
                "doc://com.apple.xctest/documentation/XCTest/XCTNSNotificationExpectation/init(name:object:)",
                "doc://com.apple.xctest/documentation/XCTest/XCTNSNotificationExpectation/init(name:object:notificationCenter:)"
              ],
              "title": "Creating NSNotification Expectations"
            },
            {
              "anchor": "Expectation-Properties",
              "identifiers": [
                "doc://com.apple.xctest/documentation/XCTest/XCTNSNotificationExpectation/notificationName",
                "doc://com.apple.xctest/documentation/XCTest/XCTNSNotificationExpectation/observedObject",
                "doc://com.apple.xctest/documentation/XCTest/XCTNSNotificationExpectation/notificationCenter"
              ],
              "title": "Expectation Properties"
            },
            {
              "anchor": "Custom-Notification-Evaluation",
              "identifiers": [
                "doc://com.apple.xctest/documentation/XCTest/XCTNSNotificationExpectation/handler-swift.property",
                "doc://com.apple.xctest/documentation/XCTest/XCTNSNotificationExpectation/Handler-swift.typealias"
              ],
              "title": "Custom Notification Evaluation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": [
            {
              "identifiers": [
                "doc://com.apple.xctest/documentation/XCTest/XCTestExpectation"
              ],
              "kind": "relationships",
              "title": "Inherits From",
              "type": "inheritsFrom"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Notification-Based-Expectations",
              "generated": true,
              "identifiers": [
                "doc://com.apple.xctest/documentation/XCTest/XCTDarwinNotificationExpectation"
              ],
              "title": "Notification-Based Expectations"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "@interface"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "XCTNSNotificationExpectation"
                  },
                  {
                    "kind": "text",
                    "text": " : "
                  },
                  {
                    "identifier": "doc://com.apple.xctest/documentation/XCTest/XCTestExpectation",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(cs)XCTestExpectation",
                    "text": "XCTestExpectation"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCTNSNotificationExpectation~1notificationName/title",
          "value": "notificationName"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCTNSNotificationExpectation~1notificationName/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "notificationName"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCTDarwinNotificationExpectation/title",
          "value": "XCTDarwinNotificationExpectation"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCTDarwinNotificationExpectation/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "XCTDarwinNotificationExpectation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCTDarwinNotificationExpectation/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "XCTDarwinNotificationExpectation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCTNSNotificationExpectation~1init(name:object:notificationCenter:)/title",
          "value": "initWithName:object:notificationCenter:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCTNSNotificationExpectation~1init(name:object:notificationCenter:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "initWithName:object:notificationCenter:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCTNSNotificationExpectation~1init(name:)/title",
          "value": "initWithName:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCTNSNotificationExpectation~1init(name:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "initWithName:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCTNSNotificationExpectation~1observedObject/title",
          "value": "observedObject"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCTNSNotificationExpectation~1observedObject/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "observedObject"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCTNSNotificationExpectation~1handler-swift.property/title",
          "value": "handler"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCTNSNotificationExpectation~1handler-swift.property/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "handler"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCTNSNotificationExpectation/title",
          "value": "XCTNSNotificationExpectation"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCTNSNotificationExpectation/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "XCTNSNotificationExpectation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCTNSNotificationExpectation/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "XCTNSNotificationExpectation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCTNSNotificationExpectation~1Handler-swift.typealias/title",
          "value": "XCNotificationExpectationHandler"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCTNSNotificationExpectation~1Handler-swift.typealias/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "XCNotificationExpectationHandler"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCTNSNotificationExpectation~1Handler-swift.typealias/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "XCNotificationExpectationHandler"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:objc(pl)NSObject/title",
          "value": "NSObject"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCTNSNotificationExpectation~1notificationCenter/title",
          "value": "notificationCenter"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCTNSNotificationExpectation~1notificationCenter/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "notificationCenter"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCTNSNotificationExpectation~1init(name:object:)/title",
          "value": "initWithName:object:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCTNSNotificationExpectation~1init(name:object:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "initWithName:object:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCTestExpectation/title",
          "value": "XCTestExpectation"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCTestExpectation/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "XCTestExpectation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCTestExpectation/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "XCTestExpectation"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/xctest/xctnsnotificationexpectation"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/xctest/xctnsnotificationexpectation"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
