{
  "abstract": [
    {
      "text": "A metric to record the time that a performance test spends executing a signposted region of code.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.xctest/documentation/XCTest"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.xctest/documentation/XCTest/XCTOSSignpostMetric"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(cs)XCTOSSignpostMetric",
    "fragments": [
      {
        "kind": "keyword",
        "text": "class"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "XCTOSSignpostMetric"
      }
    ],
    "modules": [
      {
        "name": "XCTest"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "XCTOSSignpostMetric"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.0",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.0",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "7.0",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Class",
    "symbolKind": "class",
    "title": "XCTOSSignpostMetric"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "class"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "XCTOSSignpostMetric"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "This metric captures the time that elapses between the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/os/OSSignpostType/begin",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " and ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/os/OSSignpostType/end",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " events for a specific named ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/os/os_signpost(_:dso:log:name:signpostID:)-2oz8u",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " region. It doesn’t record any results when there isn’t a matching pair of ",
              "type": "text"
            },
            {
              "code": "begin",
              "type": "codeVoice"
            },
            {
              "text": " and ",
              "type": "text"
            },
            {
              "code": "end",
              "type": "codeVoice"
            },
            {
              "text": " events.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/os/OSSignpostType/begin": {
      "abstract": [
        {
          "text": "A signpost that marks the start of a time interval of interest in your code.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "begin"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@EA@os_signpost_type_t",
          "text": "OSSignpostType"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/os/OSSignpostType/begin",
      "kind": "symbol",
      "role": "symbol",
      "title": "begin",
      "type": "topic",
      "url": "/documentation/os/OSSignpostType/begin"
    },
    "doc://com.apple.documentation/documentation/os/OSSignpostType/end": {
      "abstract": [
        {
          "text": "A signpost that marks the end of a time interval of interest in your code.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "end"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@EA@os_signpost_type_t",
          "text": "OSSignpostType"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/os/OSSignpostType/end",
      "kind": "symbol",
      "role": "symbol",
      "title": "end",
      "type": "topic",
      "url": "/documentation/os/OSSignpostType/end"
    },
    "doc://com.apple.documentation/documentation/os/os_signpost(_:dso:log:name:signpostID:)-2oz8u": {
      "abstract": [
        {
          "text": "Logs a point of interest in your code as a time interval or as an event for debugging performance in Instruments.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "os_signpost"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "_"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "internalParam",
          "text": "type"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@EA@os_signpost_type_t",
          "text": "OSSignpostType"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "dso"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SV",
          "text": "UnsafeRawPointer"
        },
        {
          "kind": "text",
          "text": " = "
        },
        {
          "kind": "keyword",
          "text": "#dsohandle"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "log"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)OS_os_log",
          "text": "OSLog"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "name"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s12StaticStringV",
          "text": "StaticString"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "signpostID"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:2os12OSSignpostIDV",
          "text": "OSSignpostID"
        },
        {
          "kind": "text",
          "text": " = .exclusive)"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/os/os_signpost(_:dso:log:name:signpostID:)-2oz8u",
      "kind": "symbol",
      "role": "symbol",
      "title": "os_signpost(_:dso:log:name:signpostID:)",
      "type": "topic",
      "url": "/documentation/os/os_signpost(_:dso:log:name:signpostID:)-2oz8u"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.xctest/documentation/XCTest": {
      "abstract": [
        {
          "text": "Create and run unit tests, performance tests, and UI tests for your Xcode project.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.xctest/documentation/XCTest",
      "kind": "symbol",
      "role": "collection",
      "title": "XCTest",
      "type": "topic",
      "url": "/documentation/xctest"
    },
    "doc://com.apple.xctest/documentation/XCTest/XCTApplicationLaunchMetric": {
      "abstract": [
        {
          "text": "A metric to record the application launch duration for a performance test.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "XCTApplicationLaunchMetric"
        }
      ],
      "identifier": "doc://com.apple.xctest/documentation/XCTest/XCTApplicationLaunchMetric",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "XCTApplicationLaunchMetric"
        }
      ],
      "role": "symbol",
      "title": "XCTApplicationLaunchMetric",
      "type": "topic",
      "url": "/documentation/xctest/xctapplicationlaunchmetric"
    },
    "doc://com.apple.xctest/documentation/XCTest/XCTCPUMetric": {
      "abstract": [
        {
          "text": "A metric to record information about CPU activity during a performance test.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "XCTCPUMetric"
        }
      ],
      "identifier": "doc://com.apple.xctest/documentation/XCTest/XCTCPUMetric",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "XCTCPUMetric"
        }
      ],
      "role": "symbol",
      "title": "XCTCPUMetric",
      "type": "topic",
      "url": "/documentation/xctest/xctcpumetric"
    },
    "doc://com.apple.xctest/documentation/XCTest/XCTClockMetric": {
      "abstract": [
        {
          "text": "A metric to record the time that elapses during a performance test.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "XCTClockMetric"
        }
      ],
      "identifier": "doc://com.apple.xctest/documentation/XCTest/XCTClockMetric",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "XCTClockMetric"
        }
      ],
      "role": "symbol",
      "title": "XCTClockMetric",
      "type": "topic",
      "url": "/documentation/xctest/xctclockmetric"
    },
    "doc://com.apple.xctest/documentation/XCTest/XCTMemoryMetric": {
      "abstract": [
        {
          "text": "A metric to record the physical memory that a performance test uses.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "XCTMemoryMetric"
        }
      ],
      "identifier": "doc://com.apple.xctest/documentation/XCTest/XCTMemoryMetric",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "XCTMemoryMetric"
        }
      ],
      "role": "symbol",
      "title": "XCTMemoryMetric",
      "type": "topic",
      "url": "/documentation/xctest/xctmemorymetric"
    },
    "doc://com.apple.xctest/documentation/XCTest/XCTMetric": {
      "abstract": [
        {
          "text": "A protocol that defines the methods that objects must provide when gathering metrics during performance tests.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "XCTMetric"
        }
      ],
      "identifier": "doc://com.apple.xctest/documentation/XCTest/XCTMetric",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "XCTMetric"
        }
      ],
      "role": "symbol",
      "title": "XCTMetric",
      "type": "topic",
      "url": "/documentation/xctest/xctmetric"
    },
    "doc://com.apple.xctest/documentation/XCTest/XCTOSSignpostMetric": {
      "abstract": [
        {
          "text": "A metric to record the time that a performance test spends executing a signposted region of code.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "XCTOSSignpostMetric"
        }
      ],
      "identifier": "doc://com.apple.xctest/documentation/XCTest/XCTOSSignpostMetric",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "XCTOSSignpostMetric"
        }
      ],
      "role": "symbol",
      "title": "XCTOSSignpostMetric",
      "type": "topic",
      "url": "/documentation/xctest/xctossignpostmetric"
    },
    "doc://com.apple.xctest/documentation/XCTest/XCTOSSignpostMetric/applicationLaunch": {
      "abstract": [
        {
          "text": "A metric that records the time that elapses during app launch.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "applicationLaunch"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)XCTOSSignpostMetric",
          "text": "XCTOSSignpostMetric"
        }
      ],
      "identifier": "doc://com.apple.xctest/documentation/XCTest/XCTOSSignpostMetric/applicationLaunch",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "applicationLaunchMetric"
        }
      ],
      "role": "symbol",
      "title": "applicationLaunch",
      "type": "topic",
      "url": "/documentation/xctest/xctossignpostmetric/applicationlaunch"
    },
    "doc://com.apple.xctest/documentation/XCTest/XCTOSSignpostMetric/customNavigationTransitionMetric": {
      "abstract": [
        {
          "text": "A metric that records the duration of custom navigation transitions between views.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "customNavigationTransitionMetric"
        },
        {
          "kind": "text",
          "text": ": any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(pl)XCTMetric",
          "text": "XCTMetric"
        }
      ],
      "identifier": "doc://com.apple.xctest/documentation/XCTest/XCTOSSignpostMetric/customNavigationTransitionMetric",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "customNavigationTransitionMetric"
        }
      ],
      "role": "symbol",
      "title": "customNavigationTransitionMetric",
      "type": "topic",
      "url": "/documentation/xctest/xctossignpostmetric/customnavigationtransitionmetric"
    },
    "doc://com.apple.xctest/documentation/XCTest/XCTOSSignpostMetric/init(subsystem:category:name:)": {
      "abstract": [
        {
          "text": "Creates a metric to record a specific signpost.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "subsystem"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "category"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "name"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.xctest/documentation/XCTest/XCTOSSignpostMetric/init(subsystem:category:name:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "initWithSubsystem:category:name:"
        }
      ],
      "role": "symbol",
      "title": "init(subsystem:category:name:)",
      "type": "topic",
      "url": "/documentation/xctest/xctossignpostmetric/init(subsystem:category:name:)"
    },
    "doc://com.apple.xctest/documentation/XCTest/XCTOSSignpostMetric/navigationTransitionMetric": {
      "abstract": [
        {
          "text": "A metric that records the duration of navigation transitions between views.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "navigationTransitionMetric"
        },
        {
          "kind": "text",
          "text": ": any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(pl)XCTMetric",
          "text": "XCTMetric"
        }
      ],
      "identifier": "doc://com.apple.xctest/documentation/XCTest/XCTOSSignpostMetric/navigationTransitionMetric",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "navigationTransitionMetric"
        }
      ],
      "role": "symbol",
      "title": "navigationTransitionMetric",
      "type": "topic",
      "url": "/documentation/xctest/xctossignpostmetric/navigationtransitionmetric"
    },
    "doc://com.apple.xctest/documentation/XCTest/XCTOSSignpostMetric/scrollDecelerationMetric": {
      "abstract": [
        {
          "text": "A metric that records scroll deceleration animations.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "scrollDecelerationMetric"
        },
        {
          "kind": "text",
          "text": ": any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(pl)XCTMetric",
          "text": "XCTMetric"
        }
      ],
      "identifier": "doc://com.apple.xctest/documentation/XCTest/XCTOSSignpostMetric/scrollDecelerationMetric",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "scrollDecelerationMetric"
        }
      ],
      "role": "symbol",
      "title": "scrollDecelerationMetric",
      "type": "topic",
      "url": "/documentation/xctest/xctossignpostmetric/scrolldecelerationmetric"
    },
    "doc://com.apple.xctest/documentation/XCTest/XCTOSSignpostMetric/scrollDraggingMetric": {
      "abstract": [
        {
          "text": "A metric that records scroll-dragging animations.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "scrollDraggingMetric"
        },
        {
          "kind": "text",
          "text": ": any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(pl)XCTMetric",
          "text": "XCTMetric"
        }
      ],
      "identifier": "doc://com.apple.xctest/documentation/XCTest/XCTOSSignpostMetric/scrollDraggingMetric",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "scrollDraggingMetric"
        }
      ],
      "role": "symbol",
      "title": "scrollDraggingMetric",
      "type": "topic",
      "url": "/documentation/xctest/xctossignpostmetric/scrolldraggingmetric"
    },
    "doc://com.apple.xctest/documentation/XCTest/XCTOSSignpostMetric/scrollingAndDecelerationMetric": {
      "abstract": [
        {
          "text": "A metric that records scroll-dragging and deceleration animations.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "scrollingAndDecelerationMetric"
        },
        {
          "kind": "text",
          "text": ": any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(pl)XCTMetric",
          "text": "XCTMetric"
        }
      ],
      "identifier": "doc://com.apple.xctest/documentation/XCTest/XCTOSSignpostMetric/scrollingAndDecelerationMetric",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "scrollingAndDecelerationMetric"
        }
      ],
      "role": "symbol",
      "title": "scrollingAndDecelerationMetric",
      "type": "topic",
      "url": "/documentation/xctest/xctossignpostmetric/scrollinganddecelerationmetric"
    },
    "doc://com.apple.xctest/documentation/XCTest/XCTStorageMetric": {
      "abstract": [
        {
          "text": "A metric to record the amount of data that a performance test logically writes to storage.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "XCTStorageMetric"
        }
      ],
      "identifier": "doc://com.apple.xctest/documentation/XCTest/XCTStorageMetric",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "XCTStorageMetric"
        }
      ],
      "role": "symbol",
      "title": "XCTStorageMetric",
      "type": "topic",
      "url": "/documentation/xctest/xctstoragemetric"
    },
    "doc://com.externally.resolved.symbol/c:objc(cs)NSObject": {
      "abstract": [
        {
          "text": "The root class of most Objective-C class hierarchies, from which subclasses inherit a basic interface to the runtime system and the ability to behave as Objective-C objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "class "
        },
        {
          "kind": "identifier",
          "text": "NSObject"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSObject",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSObject",
      "type": "topic",
      "url": "/documentation/objectivec/nsobject"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)NSCopying": {
      "abstract": [
        {
          "text": "A protocol that objects adopt to provide functional copies of themselves.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "protocol "
        },
        {
          "kind": "identifier",
          "text": "NSCopying"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSCopying",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSCopying",
      "type": "topic",
      "url": "/documentation/foundation/nscopying"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)NSObject": {
      "abstract": [
        {
          "text": "The group of methods that are fundamental to all Objective-C objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "protocol "
        },
        {
          "kind": "identifier",
          "text": "NSObjectProtocol"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSObject",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSObjectProtocol",
      "type": "topic",
      "url": "/documentation/objectivec/nsobjectprotocol"
    },
    "doc://com.externally.resolved.symbol/s:SH": {
      "abstract": [
        {
          "text": "A type that can be hashed into a `Hasher` to produce an integer hash value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Hashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SQ",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SH",
      "kind": "symbol",
      "role": "symbol",
      "title": "Hashable",
      "type": "topic",
      "url": "/documentation/Swift/Hashable"
    },
    "doc://com.externally.resolved.symbol/s:SQ": {
      "abstract": [
        {
          "text": "A type that can be compared for value equality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SQ",
      "kind": "symbol",
      "role": "symbol",
      "title": "Equatable",
      "type": "topic",
      "url": "/documentation/Swift/Equatable"
    },
    "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP": {
      "abstract": [
        {
          "text": "A type with a customized textual representation.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CustomStringConvertible"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CustomStringConvertible",
      "type": "topic",
      "url": "/documentation/Swift/CustomStringConvertible"
    },
    "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP": {
      "abstract": [
        {
          "text": "A type with a customized textual representation suitable for debugging purposes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CustomDebugStringConvertible"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CustomDebugStringConvertible",
      "type": "topic",
      "url": "/documentation/Swift/CustomDebugStringConvertible"
    },
    "doc://com.externally.resolved.symbol/s:s7CVarArgP": {
      "abstract": [
        {
          "text": "A type whose instances can be encoded, and appropriately passed, as elements of a C `va_list`.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CVarArg"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s7CVarArgP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CVarArg",
      "type": "topic",
      "url": "/documentation/Swift/CVarArg"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/c:objc(cs)NSObject"
      ],
      "kind": "relationships",
      "title": "Inherits From",
      "type": "inheritsFrom"
    },
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:s7CVarArgP",
        "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP",
        "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP",
        "doc://com.externally.resolved.symbol/s:SQ",
        "doc://com.externally.resolved.symbol/s:SH",
        "doc://com.externally.resolved.symbol/c:objc(pl)NSCopying",
        "doc://com.externally.resolved.symbol/c:objc(pl)NSObject",
        "doc://com.apple.xctest/documentation/XCTest/XCTMetric"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Measurement-Metrics",
      "generated": true,
      "identifiers": [
        "doc://com.apple.xctest/documentation/XCTest/XCTMetric",
        "doc://com.apple.xctest/documentation/XCTest/XCTCPUMetric",
        "doc://com.apple.xctest/documentation/XCTest/XCTClockMetric",
        "doc://com.apple.xctest/documentation/XCTest/XCTMemoryMetric",
        "doc://com.apple.xctest/documentation/XCTest/XCTStorageMetric",
        "doc://com.apple.xctest/documentation/XCTest/XCTApplicationLaunchMetric"
      ],
      "title": "Measurement Metrics"
    }
  ],
  "topicSections": [
    {
      "anchor": "Measuring-Specific-Signposts",
      "identifiers": [
        "doc://com.apple.xctest/documentation/XCTest/XCTOSSignpostMetric/init(subsystem:category:name:)"
      ],
      "title": "Measuring Specific Signposts"
    },
    {
      "anchor": "Measuring-Navigation-Transitions",
      "identifiers": [
        "doc://com.apple.xctest/documentation/XCTest/XCTOSSignpostMetric/customNavigationTransitionMetric",
        "doc://com.apple.xctest/documentation/XCTest/XCTOSSignpostMetric/navigationTransitionMetric"
      ],
      "title": "Measuring Navigation Transitions"
    },
    {
      "anchor": "Measuring-Scrolling-Properties",
      "identifiers": [
        "doc://com.apple.xctest/documentation/XCTest/XCTOSSignpostMetric/scrollingAndDecelerationMetric"
      ],
      "title": "Measuring Scrolling Properties"
    },
    {
      "anchor": "Deprecated",
      "identifiers": [
        "doc://com.apple.xctest/documentation/XCTest/XCTOSSignpostMetric/applicationLaunch",
        "doc://com.apple.xctest/documentation/XCTest/XCTOSSignpostMetric/scrollDecelerationMetric",
        "doc://com.apple.xctest/documentation/XCTest/XCTOSSignpostMetric/scrollDraggingMetric"
      ],
      "title": "Deprecated"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.0",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.0",
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "7.0",
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Class"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "XCTOSSignpostMetric"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "class"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "XCTOSSignpostMetric"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "XCTOSSignpostMetric"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.xctest/documentation/XCTest"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Measuring-Specific-Signposts",
              "identifiers": [
                "doc://com.apple.xctest/documentation/XCTest/XCTOSSignpostMetric/init(subsystem:category:name:)"
              ],
              "title": "Measuring Specific Signposts"
            },
            {
              "anchor": "Measuring-Navigation-Transitions",
              "identifiers": [
                "doc://com.apple.xctest/documentation/XCTest/XCTOSSignpostMetric/customNavigationTransitionMetric",
                "doc://com.apple.xctest/documentation/XCTest/XCTOSSignpostMetric/navigationTransitionMetric"
              ],
              "title": "Measuring Navigation Transitions"
            },
            {
              "anchor": "Measuring-Scrolling-Properties",
              "identifiers": [
                "doc://com.apple.xctest/documentation/XCTest/XCTOSSignpostMetric/scrollingAndDecelerationMetric"
              ],
              "title": "Measuring Scrolling Properties"
            },
            {
              "anchor": "Deprecated",
              "identifiers": [
                "doc://com.apple.xctest/documentation/XCTest/XCTOSSignpostMetric/applicationLaunch",
                "doc://com.apple.xctest/documentation/XCTest/XCTOSSignpostMetric/scrollDecelerationMetric",
                "doc://com.apple.xctest/documentation/XCTest/XCTOSSignpostMetric/scrollDraggingMetric"
              ],
              "title": "Deprecated"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": [
            {
              "identifiers": [
                "doc://com.externally.resolved.symbol/c:objc(cs)NSObject"
              ],
              "kind": "relationships",
              "title": "Inherits From",
              "type": "inheritsFrom"
            },
            {
              "identifiers": [
                "doc://com.apple.xctest/documentation/XCTest/XCTMetric"
              ],
              "kind": "relationships",
              "title": "Conforms To",
              "type": "conformsTo"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Measurement-Metrics",
              "generated": true,
              "identifiers": [
                "doc://com.apple.xctest/documentation/XCTest/XCTMetric",
                "doc://com.apple.xctest/documentation/XCTest/XCTCPUMetric",
                "doc://com.apple.xctest/documentation/XCTest/XCTClockMetric",
                "doc://com.apple.xctest/documentation/XCTest/XCTMemoryMetric",
                "doc://com.apple.xctest/documentation/XCTest/XCTStorageMetric",
                "doc://com.apple.xctest/documentation/XCTest/XCTApplicationLaunchMetric"
              ],
              "title": "Measurement Metrics"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "@interface"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "XCTOSSignpostMetric"
                  },
                  {
                    "kind": "text",
                    "text": " : "
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSObject",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(cs)NSObject",
                    "text": "NSObject"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCTStorageMetric/title",
          "value": "XCTStorageMetric"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCTStorageMetric/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "XCTStorageMetric"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCTStorageMetric/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "XCTStorageMetric"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCTOSSignpostMetric/title",
          "value": "XCTOSSignpostMetric"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCTOSSignpostMetric/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "XCTOSSignpostMetric"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCTOSSignpostMetric/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "XCTOSSignpostMetric"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCTOSSignpostMetric~1scrollDecelerationMetric/title",
          "value": "scrollDecelerationMetric"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCTOSSignpostMetric~1scrollDecelerationMetric/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "scrollDecelerationMetric"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCTOSSignpostMetric~1navigationTransitionMetric/title",
          "value": "navigationTransitionMetric"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCTOSSignpostMetric~1navigationTransitionMetric/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "navigationTransitionMetric"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCTOSSignpostMetric~1scrollDraggingMetric/title",
          "value": "scrollDraggingMetric"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCTOSSignpostMetric~1scrollDraggingMetric/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "scrollDraggingMetric"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:objc(pl)NSObject/title",
          "value": "NSObject"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCTOSSignpostMetric~1scrollingAndDecelerationMetric/title",
          "value": "scrollingAndDecelerationMetric"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCTOSSignpostMetric~1scrollingAndDecelerationMetric/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "scrollingAndDecelerationMetric"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCTClockMetric/title",
          "value": "XCTClockMetric"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCTClockMetric/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "XCTClockMetric"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCTClockMetric/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "XCTClockMetric"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCTMetric/title",
          "value": "XCTMetric"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCTMetric/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "XCTMetric"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCTMetric/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "XCTMetric"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCTApplicationLaunchMetric/title",
          "value": "XCTApplicationLaunchMetric"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCTApplicationLaunchMetric/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "XCTApplicationLaunchMetric"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCTApplicationLaunchMetric/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "XCTApplicationLaunchMetric"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCTCPUMetric/title",
          "value": "XCTCPUMetric"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCTCPUMetric/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "XCTCPUMetric"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCTCPUMetric/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "XCTCPUMetric"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCTOSSignpostMetric~1init(subsystem:category:name:)/title",
          "value": "initWithSubsystem:category:name:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCTOSSignpostMetric~1init(subsystem:category:name:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "initWithSubsystem:category:name:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCTOSSignpostMetric~1customNavigationTransitionMetric/title",
          "value": "customNavigationTransitionMetric"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCTOSSignpostMetric~1customNavigationTransitionMetric/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "customNavigationTransitionMetric"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCTMemoryMetric/title",
          "value": "XCTMemoryMetric"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCTMemoryMetric/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "XCTMemoryMetric"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCTMemoryMetric/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "XCTMemoryMetric"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCTOSSignpostMetric~1applicationLaunch/title",
          "value": "applicationLaunchMetric"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCTOSSignpostMetric~1applicationLaunch/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "applicationLaunchMetric"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/xctest/xctossignpostmetric"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/xctest/xctossignpostmetric"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
