{
  "abstract": [
    {
      "text": "A measurement from a single iteration of a performance test.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.xctest/documentation/XCTest"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.xctest/documentation/XCTest/XCTPerformanceMeasurement"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(cs)XCTPerformanceMeasurement",
    "fragments": [
      {
        "kind": "keyword",
        "text": "class"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "XCTPerformanceMeasurement"
      }
    ],
    "modules": [
      {
        "name": "XCTest"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "XCTPerformanceMeasurement"
      }
    ],
    "role": "symbol",
    "roleHeading": "Class",
    "symbolKind": "class",
    "title": "XCTPerformanceMeasurement"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "class"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "XCTPerformanceMeasurement"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.xctest/documentation/XCTest": {
      "abstract": [
        {
          "text": "Create and run unit tests, performance tests, and UI tests for your Xcode project.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.xctest/documentation/XCTest",
      "kind": "symbol",
      "role": "collection",
      "title": "XCTest",
      "type": "topic",
      "url": "/documentation/xctest"
    },
    "doc://com.apple.xctest/documentation/XCTest/XCTPerformanceMeasurement": {
      "abstract": [
        {
          "text": "A measurement from a single iteration of a performance test.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "XCTPerformanceMeasurement"
        }
      ],
      "identifier": "doc://com.apple.xctest/documentation/XCTest/XCTPerformanceMeasurement",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "XCTPerformanceMeasurement"
        }
      ],
      "role": "symbol",
      "title": "XCTPerformanceMeasurement",
      "type": "topic",
      "url": "/documentation/xctest/xctperformancemeasurement"
    },
    "doc://com.apple.xctest/documentation/XCTest/XCTPerformanceMeasurement/Polarity-swift.enum": {
      "abstract": [
        {
          "text": "Constants that state whether larger or smaller measurements, relative to a set baseline, indicate better performance.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Polarity"
        }
      ],
      "identifier": "doc://com.apple.xctest/documentation/XCTest/XCTPerformanceMeasurement/Polarity-swift.enum",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "Polarity"
        }
      ],
      "role": "symbol",
      "title": "XCTPerformanceMeasurement.Polarity",
      "type": "topic",
      "url": "/documentation/xctest/xctperformancemeasurement/polarity-swift.enum"
    },
    "doc://com.apple.xctest/documentation/XCTest/XCTPerformanceMeasurement/displayName": {
      "abstract": [
        {
          "text": "A human-readable name for a measurement.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "displayName"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.xctest/documentation/XCTest/XCTPerformanceMeasurement/displayName",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "displayName"
        }
      ],
      "role": "symbol",
      "title": "displayName",
      "type": "topic",
      "url": "/documentation/xctest/xctperformancemeasurement/displayname"
    },
    "doc://com.apple.xctest/documentation/XCTest/XCTPerformanceMeasurement/doubleValue": {
      "abstract": [
        {
          "text": "The measured value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "doubleValue"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sd",
          "text": "Double"
        }
      ],
      "identifier": "doc://com.apple.xctest/documentation/XCTest/XCTPerformanceMeasurement/doubleValue",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "doubleValue"
        }
      ],
      "role": "symbol",
      "title": "doubleValue",
      "type": "topic",
      "url": "/documentation/xctest/xctperformancemeasurement/doublevalue"
    },
    "doc://com.apple.xctest/documentation/XCTest/XCTPerformanceMeasurement/identifier": {
      "abstract": [
        {
          "text": "A unique identifier for a measurement.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "identifier"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.xctest/documentation/XCTest/XCTPerformanceMeasurement/identifier",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "identifier"
        }
      ],
      "role": "symbol",
      "title": "identifier",
      "type": "topic",
      "url": "/documentation/xctest/xctperformancemeasurement/identifier"
    },
    "doc://com.apple.xctest/documentation/XCTest/XCTPerformanceMeasurement/init(identifier:displayName:doubleValue:unitSymbol:)": {
      "abstract": [
        {
          "text": "Initializes a performance measurement for a single iteration with the value and unit of measurement.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "identifier"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "displayName"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "doubleValue"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sd",
          "text": "Double"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "unitSymbol"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.xctest/documentation/XCTest/XCTPerformanceMeasurement/init(identifier:displayName:doubleValue:unitSymbol:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "initWithIdentifier:displayName:doubleValue:unitSymbol:"
        }
      ],
      "role": "symbol",
      "title": "init(identifier:displayName:doubleValue:unitSymbol:)",
      "type": "topic",
      "url": "/documentation/xctest/xctperformancemeasurement/init(identifier:displayname:doublevalue:unitsymbol:)"
    },
    "doc://com.apple.xctest/documentation/XCTest/XCTPerformanceMeasurement/init(identifier:displayName:doubleValue:unitSymbol:polarity:)": {
      "abstract": [
        {
          "text": "Initializes a performance measurement for a single iteration with the value, unit of measurement, and polarity.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "convenience"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "identifier"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "displayName"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "doubleValue"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sd",
          "text": "Double"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "unitSymbol"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "polarity"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)XCTPerformanceMeasurement",
          "text": "XCTPerformanceMeasurement"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@XCTPerformanceMeasurementPolarity",
          "text": "Polarity"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.xctest/documentation/XCTest/XCTPerformanceMeasurement/init(identifier:displayName:doubleValue:unitSymbol:polarity:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "initWithIdentifier:displayName:doubleValue:unitSymbol:polarity:"
        }
      ],
      "role": "symbol",
      "title": "init(identifier:displayName:doubleValue:unitSymbol:polarity:)",
      "type": "topic",
      "url": "/documentation/xctest/xctperformancemeasurement/init(identifier:displayname:doublevalue:unitsymbol:polarity:)"
    },
    "doc://com.apple.xctest/documentation/XCTest/XCTPerformanceMeasurement/init(identifier:displayName:value:)": {
      "abstract": [
        {
          "text": "Initializes a performance measurement for a single iteration with the value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "convenience"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "identifier"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "displayName"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "value"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10Foundation11MeasurementV",
          "text": "Measurement"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSUnit",
          "text": "Unit"
        },
        {
          "kind": "text",
          "text": ">)"
        }
      ],
      "identifier": "doc://com.apple.xctest/documentation/XCTest/XCTPerformanceMeasurement/init(identifier:displayName:value:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "initWithIdentifier:displayName:value:"
        }
      ],
      "role": "symbol",
      "title": "init(identifier:displayName:value:)",
      "type": "topic",
      "url": "/documentation/xctest/xctperformancemeasurement/init(identifier:displayname:value:)"
    },
    "doc://com.apple.xctest/documentation/XCTest/XCTPerformanceMeasurement/init(identifier:displayName:value:polarity:)": {
      "abstract": [
        {
          "text": "Initializes a performance measurement for a single iteration with the value and polarity.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "convenience"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "identifier"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "displayName"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "value"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10Foundation11MeasurementV",
          "text": "Measurement"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSUnit",
          "text": "Unit"
        },
        {
          "kind": "text",
          "text": ">, "
        },
        {
          "kind": "externalParam",
          "text": "polarity"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)XCTPerformanceMeasurement",
          "text": "XCTPerformanceMeasurement"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@XCTPerformanceMeasurementPolarity",
          "text": "Polarity"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.xctest/documentation/XCTest/XCTPerformanceMeasurement/init(identifier:displayName:value:polarity:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "initWithIdentifier:displayName:value:polarity:"
        }
      ],
      "role": "symbol",
      "title": "init(identifier:displayName:value:polarity:)",
      "type": "topic",
      "url": "/documentation/xctest/xctperformancemeasurement/init(identifier:displayname:value:polarity:)"
    },
    "doc://com.apple.xctest/documentation/XCTest/XCTPerformanceMeasurement/polarity-swift.property": {
      "abstract": [
        {
          "text": "A constant that states whether larger or smaller measurements, relative to a set baseline, indicate better performance.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "polarity"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)XCTPerformanceMeasurement",
          "text": "XCTPerformanceMeasurement"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@XCTPerformanceMeasurementPolarity",
          "text": "Polarity"
        }
      ],
      "identifier": "doc://com.apple.xctest/documentation/XCTest/XCTPerformanceMeasurement/polarity-swift.property",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "polarity"
        }
      ],
      "role": "symbol",
      "title": "polarity",
      "type": "topic",
      "url": "/documentation/xctest/xctperformancemeasurement/polarity-swift.property"
    },
    "doc://com.apple.xctest/documentation/XCTest/XCTPerformanceMeasurement/unitSymbol": {
      "abstract": [
        {
          "text": "A string that represents the unit of measurement.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "unitSymbol"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.xctest/documentation/XCTest/XCTPerformanceMeasurement/unitSymbol",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "unitSymbol"
        }
      ],
      "role": "symbol",
      "title": "unitSymbol",
      "type": "topic",
      "url": "/documentation/xctest/xctperformancemeasurement/unitsymbol"
    },
    "doc://com.apple.xctest/documentation/XCTest/XCTPerformanceMeasurement/value": {
      "abstract": [
        {
          "text": "The measured value, including the unit of measure.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "value"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10Foundation11MeasurementV",
          "text": "Measurement"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSUnit",
          "text": "Unit"
        },
        {
          "kind": "text",
          "text": ">"
        }
      ],
      "identifier": "doc://com.apple.xctest/documentation/XCTest/XCTPerformanceMeasurement/value",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "value"
        }
      ],
      "role": "symbol",
      "title": "value",
      "type": "topic",
      "url": "/documentation/xctest/xctperformancemeasurement/value"
    },
    "doc://com.apple.xctest/documentation/XCTest/XCTPerformanceMeasurementTimestamp": {
      "abstract": [
        {
          "text": "A point in time that captures the start or finish of a performance test iteration.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "XCTPerformanceMeasurementTimestamp"
        }
      ],
      "identifier": "doc://com.apple.xctest/documentation/XCTest/XCTPerformanceMeasurementTimestamp",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "XCTPerformanceMeasurementTimestamp"
        }
      ],
      "role": "symbol",
      "title": "XCTPerformanceMeasurementTimestamp",
      "type": "topic",
      "url": "/documentation/xctest/xctperformancemeasurementtimestamp"
    },
    "doc://com.externally.resolved.symbol/c:objc(cs)NSObject": {
      "abstract": [
        {
          "text": "The root class of most Objective-C class hierarchies, from which subclasses inherit a basic interface to the runtime system and the ability to behave as Objective-C objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "class "
        },
        {
          "kind": "identifier",
          "text": "NSObject"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSObject",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSObject",
      "type": "topic",
      "url": "/documentation/objectivec/nsobject"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)NSObject": {
      "abstract": [
        {
          "text": "The group of methods that are fundamental to all Objective-C objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "protocol "
        },
        {
          "kind": "identifier",
          "text": "NSObjectProtocol"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSObject",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSObjectProtocol",
      "type": "topic",
      "url": "/documentation/objectivec/nsobjectprotocol"
    },
    "doc://com.externally.resolved.symbol/s:SH": {
      "abstract": [
        {
          "text": "A type that can be hashed into a `Hasher` to produce an integer hash value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Hashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SQ",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SH",
      "kind": "symbol",
      "role": "symbol",
      "title": "Hashable",
      "type": "topic",
      "url": "/documentation/Swift/Hashable"
    },
    "doc://com.externally.resolved.symbol/s:SQ": {
      "abstract": [
        {
          "text": "A type that can be compared for value equality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SQ",
      "kind": "symbol",
      "role": "symbol",
      "title": "Equatable",
      "type": "topic",
      "url": "/documentation/Swift/Equatable"
    },
    "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP": {
      "abstract": [
        {
          "text": "A type with a customized textual representation.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CustomStringConvertible"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CustomStringConvertible",
      "type": "topic",
      "url": "/documentation/Swift/CustomStringConvertible"
    },
    "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP": {
      "abstract": [
        {
          "text": "A type with a customized textual representation suitable for debugging purposes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CustomDebugStringConvertible"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CustomDebugStringConvertible",
      "type": "topic",
      "url": "/documentation/Swift/CustomDebugStringConvertible"
    },
    "doc://com.externally.resolved.symbol/s:s7CVarArgP": {
      "abstract": [
        {
          "text": "A type whose instances can be encoded, and appropriately passed, as elements of a C `va_list`.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CVarArg"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s7CVarArgP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CVarArg",
      "type": "topic",
      "url": "/documentation/Swift/CVarArg"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/c:objc(cs)NSObject"
      ],
      "kind": "relationships",
      "title": "Inherits From",
      "type": "inheritsFrom"
    },
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:s7CVarArgP",
        "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP",
        "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP",
        "doc://com.externally.resolved.symbol/s:SQ",
        "doc://com.externally.resolved.symbol/s:SH",
        "doc://com.externally.resolved.symbol/c:objc(pl)NSObject"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Measurements",
      "generated": true,
      "identifiers": [
        "doc://com.apple.xctest/documentation/XCTest/XCTPerformanceMeasurementTimestamp"
      ],
      "title": "Measurements"
    }
  ],
  "topicSections": [
    {
      "anchor": "Initializing-a-Measurement",
      "identifiers": [
        "doc://com.apple.xctest/documentation/XCTest/XCTPerformanceMeasurement/init(identifier:displayName:doubleValue:unitSymbol:)",
        "doc://com.apple.xctest/documentation/XCTest/XCTPerformanceMeasurement/init(identifier:displayName:doubleValue:unitSymbol:polarity:)",
        "doc://com.apple.xctest/documentation/XCTest/XCTPerformanceMeasurement/init(identifier:displayName:value:)",
        "doc://com.apple.xctest/documentation/XCTest/XCTPerformanceMeasurement/init(identifier:displayName:value:polarity:)"
      ],
      "title": "Initializing a Measurement"
    },
    {
      "anchor": "Identifying-Measurements",
      "identifiers": [
        "doc://com.apple.xctest/documentation/XCTest/XCTPerformanceMeasurement/displayName",
        "doc://com.apple.xctest/documentation/XCTest/XCTPerformanceMeasurement/identifier"
      ],
      "title": "Identifying Measurements"
    },
    {
      "anchor": "Accessing-Measured-Values",
      "identifiers": [
        "doc://com.apple.xctest/documentation/XCTest/XCTPerformanceMeasurement/doubleValue",
        "doc://com.apple.xctest/documentation/XCTest/XCTPerformanceMeasurement/unitSymbol",
        "doc://com.apple.xctest/documentation/XCTest/XCTPerformanceMeasurement/value",
        "doc://com.apple.xctest/documentation/XCTest/XCTPerformanceMeasurement/polarity-swift.property",
        "doc://com.apple.xctest/documentation/XCTest/XCTPerformanceMeasurement/Polarity-swift.enum"
      ],
      "title": "Accessing Measured Values"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "add",
          "path": "/metadata/platforms",
          "value": null
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Class"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "XCTPerformanceMeasurement"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "class"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "XCTPerformanceMeasurement"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "XCTPerformanceMeasurement"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.xctest/documentation/XCTest"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Initializing-a-Measurement",
              "identifiers": [
                "doc://com.apple.xctest/documentation/XCTest/XCTPerformanceMeasurement/init(identifier:displayName:doubleValue:unitSymbol:)",
                "doc://com.apple.xctest/documentation/XCTest/XCTPerformanceMeasurement/init(identifier:displayName:doubleValue:unitSymbol:polarity:)",
                "doc://com.apple.xctest/documentation/XCTest/XCTPerformanceMeasurement/init(identifier:displayName:value:)",
                "doc://com.apple.xctest/documentation/XCTest/XCTPerformanceMeasurement/init(identifier:displayName:value:polarity:)"
              ],
              "title": "Initializing a Measurement"
            },
            {
              "anchor": "Identifying-Measurements",
              "identifiers": [
                "doc://com.apple.xctest/documentation/XCTest/XCTPerformanceMeasurement/displayName",
                "doc://com.apple.xctest/documentation/XCTest/XCTPerformanceMeasurement/identifier"
              ],
              "title": "Identifying Measurements"
            },
            {
              "anchor": "Accessing-Measured-Values",
              "identifiers": [
                "doc://com.apple.xctest/documentation/XCTest/XCTPerformanceMeasurement/doubleValue",
                "doc://com.apple.xctest/documentation/XCTest/XCTPerformanceMeasurement/unitSymbol",
                "doc://com.apple.xctest/documentation/XCTest/XCTPerformanceMeasurement/value",
                "doc://com.apple.xctest/documentation/XCTest/XCTPerformanceMeasurement/polarity-swift.property",
                "doc://com.apple.xctest/documentation/XCTest/XCTPerformanceMeasurement/Polarity-swift.enum"
              ],
              "title": "Accessing Measured Values"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": [
            {
              "identifiers": [
                "doc://com.externally.resolved.symbol/c:objc(cs)NSObject"
              ],
              "kind": "relationships",
              "title": "Inherits From",
              "type": "inheritsFrom"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Measurements",
              "generated": true,
              "identifiers": [
                "doc://com.apple.xctest/documentation/XCTest/XCTPerformanceMeasurementTimestamp"
              ],
              "title": "Measurements"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "@interface"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "XCTPerformanceMeasurement"
                  },
                  {
                    "kind": "text",
                    "text": " : "
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSObject",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(cs)NSObject",
                    "text": "NSObject"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCTPerformanceMeasurement~1init(identifier:displayName:doubleValue:unitSymbol:polarity:)/title",
          "value": "initWithIdentifier:displayName:doubleValue:unitSymbol:polarity:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCTPerformanceMeasurement~1init(identifier:displayName:doubleValue:unitSymbol:polarity:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "initWithIdentifier:displayName:doubleValue:unitSymbol:polarity:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCTPerformanceMeasurement~1doubleValue/title",
          "value": "doubleValue"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCTPerformanceMeasurement~1doubleValue/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "doubleValue"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCTPerformanceMeasurement~1init(identifier:displayName:value:polarity:)/title",
          "value": "initWithIdentifier:displayName:value:polarity:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCTPerformanceMeasurement~1init(identifier:displayName:value:polarity:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "initWithIdentifier:displayName:value:polarity:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCTPerformanceMeasurement~1value/title",
          "value": "value"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCTPerformanceMeasurement~1value/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "value"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCTPerformanceMeasurement~1init(identifier:displayName:value:)/title",
          "value": "initWithIdentifier:displayName:value:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCTPerformanceMeasurement~1init(identifier:displayName:value:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "initWithIdentifier:displayName:value:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCTPerformanceMeasurement~1unitSymbol/title",
          "value": "unitSymbol"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCTPerformanceMeasurement~1unitSymbol/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "unitSymbol"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCTPerformanceMeasurement~1displayName/title",
          "value": "displayName"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCTPerformanceMeasurement~1displayName/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "displayName"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCTPerformanceMeasurement~1init(identifier:displayName:doubleValue:unitSymbol:)/title",
          "value": "initWithIdentifier:displayName:doubleValue:unitSymbol:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCTPerformanceMeasurement~1init(identifier:displayName:doubleValue:unitSymbol:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "initWithIdentifier:displayName:doubleValue:unitSymbol:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCTPerformanceMeasurement~1polarity-swift.property/title",
          "value": "polarity"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCTPerformanceMeasurement~1polarity-swift.property/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "polarity"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCTPerformanceMeasurement/title",
          "value": "XCTPerformanceMeasurement"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCTPerformanceMeasurement/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "XCTPerformanceMeasurement"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCTPerformanceMeasurement/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "XCTPerformanceMeasurement"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCTPerformanceMeasurementTimestamp/title",
          "value": "XCTPerformanceMeasurementTimestamp"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCTPerformanceMeasurementTimestamp/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "XCTPerformanceMeasurementTimestamp"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCTPerformanceMeasurementTimestamp/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "XCTPerformanceMeasurementTimestamp"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCTPerformanceMeasurement~1identifier/title",
          "value": "identifier"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCTPerformanceMeasurement~1identifier/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "identifier"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:objc(pl)NSObject/title",
          "value": "NSObject"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCTPerformanceMeasurement~1Polarity-swift.enum/title",
          "value": "XCTPerformanceMeasurementPolarity"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCTPerformanceMeasurement~1Polarity-swift.enum/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "XCTPerformanceMeasurementPolarity"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCTPerformanceMeasurement~1Polarity-swift.enum/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "XCTPerformanceMeasurementPolarity"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/xctest/xctperformancemeasurement"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/xctest/xctperformancemeasurement"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
