{
  "abstract": [
    {
      "text": "Performance metrics that the test records.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.xctest/documentation/XCTest"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.xctest/documentation/XCTest/XCTPerformanceMetric"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@T@XCTPerformanceMetric",
    "fragments": [
      {
        "kind": "keyword",
        "text": "struct"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "XCTPerformanceMetric"
      }
    ],
    "modules": [
      {
        "name": "XCTest"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "XCTPerformanceMetric"
      }
    ],
    "role": "symbol",
    "roleHeading": "Structure",
    "symbolKind": "struct",
    "title": "XCTPerformanceMetric"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "struct"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "XCTPerformanceMetric"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.xctest/documentation/XCTest": {
      "abstract": [
        {
          "text": "Create and run unit tests, performance tests, and UI tests for your Xcode project.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.xctest/documentation/XCTest",
      "kind": "symbol",
      "role": "collection",
      "title": "XCTest",
      "type": "topic",
      "url": "/documentation/xctest"
    },
    "doc://com.apple.xctest/documentation/XCTest/XCTPerformanceMetric": {
      "abstract": [
        {
          "text": "Performance metrics that the test records.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "XCTPerformanceMetric"
        }
      ],
      "identifier": "doc://com.apple.xctest/documentation/XCTest/XCTPerformanceMetric",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "XCTPerformanceMetric"
        }
      ],
      "role": "symbol",
      "title": "XCTPerformanceMetric",
      "type": "topic",
      "url": "/documentation/xctest/xctperformancemetric"
    },
    "doc://com.apple.xctest/documentation/XCTest/XCTPerformanceMetric/init(_:)": {
      "abstract": [
        {
          "text": "Creates a new instance with the specified raw value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.xctest/documentation/XCTest/XCTPerformanceMetric/init(_:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "init(_:)",
      "type": "topic",
      "url": "/documentation/xctest/xctperformancemetric/init(_:)"
    },
    "doc://com.apple.xctest/documentation/XCTest/XCTPerformanceMetric/init(rawValue:)": {
      "abstract": [
        {
          "text": "Creates a new instance with the specified raw value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "rawValue"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.xctest/documentation/XCTest/XCTPerformanceMetric/init(rawValue:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "init(rawValue:)",
      "type": "topic",
      "url": "/documentation/xctest/xctperformancemetric/init(rawvalue:)"
    },
    "doc://com.apple.xctest/documentation/XCTest/XCTPerformanceMetric/wallClockTime": {
      "abstract": [
        {
          "text": "A performance metric that records the time in seconds to execute a block of code.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "wallClockTime"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@XCTPerformanceMetric",
          "text": "XCTPerformanceMetric"
        }
      ],
      "identifier": "doc://com.apple.xctest/documentation/XCTest/XCTPerformanceMetric/wallClockTime",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "XCTPerformanceMetric_WallClockTime"
        }
      ],
      "role": "symbol",
      "title": "wallClockTime",
      "type": "topic",
      "url": "/documentation/xctest/xctperformancemetric/wallclocktime"
    },
    "doc://com.apple.xctest/documentation/XCTest/XCTestCase/defaultMeasureOptions": {
      "abstract": [
        {
          "text": "The default measurement options the test uses to record performance.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "defaultMeasureOptions"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)XCTMeasureOptions",
          "text": "XCTMeasureOptions"
        }
      ],
      "identifier": "doc://com.apple.xctest/documentation/XCTest/XCTestCase/defaultMeasureOptions",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "defaultMeasureOptions"
        }
      ],
      "role": "symbol",
      "title": "defaultMeasureOptions",
      "type": "topic",
      "url": "/documentation/xctest/xctestcase/defaultmeasureoptions"
    },
    "doc://com.apple.xctest/documentation/XCTest/XCTestCase/defaultMetrics": {
      "abstract": [
        {
          "text": "An array of default metrics the test uses to record performance.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "defaultMetrics"
        },
        {
          "kind": "text",
          "text": ": [any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(pl)XCTMetric",
          "text": "XCTMetric"
        },
        {
          "kind": "text",
          "text": "]"
        }
      ],
      "identifier": "doc://com.apple.xctest/documentation/XCTest/XCTestCase/defaultMetrics",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "defaultMetrics"
        }
      ],
      "role": "symbol",
      "title": "defaultMetrics",
      "type": "topic",
      "url": "/documentation/xctest/xctestcase/defaultmetrics"
    },
    "doc://com.apple.xctest/documentation/XCTest/XCTestCase/defaultPerformanceMetrics": {
      "abstract": [
        {
          "text": "An array of default performance metrics the test records.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "defaultPerformanceMetrics"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@XCTPerformanceMetric",
          "text": "XCTPerformanceMetric"
        },
        {
          "kind": "text",
          "text": "]"
        }
      ],
      "identifier": "doc://com.apple.xctest/documentation/XCTest/XCTestCase/defaultPerformanceMetrics",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "defaultPerformanceMetrics"
        }
      ],
      "role": "symbol",
      "title": "defaultPerformanceMetrics",
      "type": "topic",
      "url": "/documentation/xctest/xctestcase/defaultperformancemetrics"
    },
    "doc://com.apple.xctest/documentation/XCTest/XCTestCase/measure(_:)": {
      "abstract": [
        {
          "text": "Measures the performance of a block of code.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "measure"
        },
        {
          "kind": "text",
          "text": "(() -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s4Voida",
          "text": "Void"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.xctest/documentation/XCTest/XCTestCase/measure(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "measureBlock:"
        }
      ],
      "role": "symbol",
      "title": "measure(_:)",
      "type": "topic",
      "url": "/documentation/xctest/xctestcase/measure(_:)"
    },
    "doc://com.apple.xctest/documentation/XCTest/XCTestCase/measure(metrics:block:)": {
      "abstract": [
        {
          "text": "Records the selected metrics for a block of code.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "measure"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "metrics"
        },
        {
          "kind": "text",
          "text": ": [any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(pl)XCTMetric",
          "text": "XCTMetric"
        },
        {
          "kind": "text",
          "text": "], "
        },
        {
          "kind": "externalParam",
          "text": "block"
        },
        {
          "kind": "text",
          "text": ": () -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s4Voida",
          "text": "Void"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.xctest/documentation/XCTest/XCTestCase/measure(metrics:block:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "measureWithMetrics:block:"
        }
      ],
      "role": "symbol",
      "title": "measure(metrics:block:)",
      "type": "topic",
      "url": "/documentation/xctest/xctestcase/measure(metrics:block:)"
    },
    "doc://com.apple.xctest/documentation/XCTest/XCTestCase/measure(metrics:options:block:)": {
      "abstract": [
        {
          "text": "Records the selected metrics, using the specified measurement options, for a block of code.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "measure"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "metrics"
        },
        {
          "kind": "text",
          "text": ": [any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(pl)XCTMetric",
          "text": "XCTMetric"
        },
        {
          "kind": "text",
          "text": "], "
        },
        {
          "kind": "externalParam",
          "text": "options"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)XCTMeasureOptions",
          "text": "XCTMeasureOptions"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "block"
        },
        {
          "kind": "text",
          "text": ": () -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s4Voida",
          "text": "Void"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.xctest/documentation/XCTest/XCTestCase/measure(metrics:options:block:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "measureWithMetrics:options:block:"
        }
      ],
      "role": "symbol",
      "title": "measure(metrics:options:block:)",
      "type": "topic",
      "url": "/documentation/xctest/xctestcase/measure(metrics:options:block:)"
    },
    "doc://com.apple.xctest/documentation/XCTest/XCTestCase/measure(options:block:)": {
      "abstract": [
        {
          "text": "Records the performance, using the specified measurement options, for a block of code.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "measure"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "options"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)XCTMeasureOptions",
          "text": "XCTMeasureOptions"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "block"
        },
        {
          "kind": "text",
          "text": ": () -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s4Voida",
          "text": "Void"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.xctest/documentation/XCTest/XCTestCase/measure(options:block:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "measureWithOptions:block:"
        }
      ],
      "role": "symbol",
      "title": "measure(options:block:)",
      "type": "topic",
      "url": "/documentation/xctest/xctestcase/measure(options:block:)"
    },
    "doc://com.apple.xctest/documentation/XCTest/XCTestCase/measureMetrics(_:automaticallyStartMeasuring:for:)": {
      "abstract": [
        {
          "text": "Measures the performance of a block of code, optionally deferring the starting point for measurement.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "measureMetrics"
        },
        {
          "kind": "text",
          "text": "(["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@XCTPerformanceMetric",
          "text": "XCTPerformanceMetric"
        },
        {
          "kind": "text",
          "text": "], "
        },
        {
          "kind": "externalParam",
          "text": "automaticallyStartMeasuring"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "for"
        },
        {
          "kind": "text",
          "text": ": () -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s4Voida",
          "text": "Void"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.xctest/documentation/XCTest/XCTestCase/measureMetrics(_:automaticallyStartMeasuring:for:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "measureMetrics:automaticallyStartMeasuring:forBlock:"
        }
      ],
      "role": "symbol",
      "title": "measureMetrics(_:automaticallyStartMeasuring:for:)",
      "type": "topic",
      "url": "/documentation/xctest/xctestcase/measuremetrics(_:automaticallystartmeasuring:for:)"
    },
    "doc://com.apple.xctest/documentation/XCTest/XCTestCase/startMeasuring()": {
      "abstract": [
        {
          "text": "Starts recording performance metrics within a block of code.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "startMeasuring"
        },
        {
          "kind": "text",
          "text": "()"
        }
      ],
      "identifier": "doc://com.apple.xctest/documentation/XCTest/XCTestCase/startMeasuring()",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "startMeasuring"
        }
      ],
      "role": "symbol",
      "title": "startMeasuring()",
      "type": "topic",
      "url": "/documentation/xctest/xctestcase/startmeasuring()"
    },
    "doc://com.apple.xctest/documentation/XCTest/XCTestCase/stopMeasuring()": {
      "abstract": [
        {
          "text": "Ends recording performance metrics within a block of code.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "stopMeasuring"
        },
        {
          "kind": "text",
          "text": "()"
        }
      ],
      "identifier": "doc://com.apple.xctest/documentation/XCTest/XCTestCase/stopMeasuring()",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "stopMeasuring"
        }
      ],
      "role": "symbol",
      "title": "stopMeasuring()",
      "type": "topic",
      "url": "/documentation/xctest/xctestcase/stopmeasuring()"
    },
    "doc://com.externally.resolved.symbol/c:objc(cs)NSString": {
      "abstract": [
        {
          "text": "A static, plain-text Unicode string object which you use when you need reference semantics or other Foundation-specific behavior. ",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "class "
        },
        {
          "kind": "identifier",
          "text": "NSString"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSString",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSString",
      "type": "topic",
      "url": "/documentation/foundation/nsstring"
    },
    "doc://com.externally.resolved.symbol/s:SH": {
      "abstract": [
        {
          "text": "A type that can be hashed into a `Hasher` to produce an integer hash value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Hashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SQ",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SH",
      "kind": "symbol",
      "role": "symbol",
      "title": "Hashable",
      "type": "topic",
      "url": "/documentation/Swift/Hashable"
    },
    "doc://com.externally.resolved.symbol/s:SQ": {
      "abstract": [
        {
          "text": "A type that can be compared for value equality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SQ",
      "kind": "symbol",
      "role": "symbol",
      "title": "Equatable",
      "type": "topic",
      "url": "/documentation/Swift/Equatable"
    },
    "doc://com.externally.resolved.symbol/s:SY": {
      "abstract": [
        {
          "text": "A type that can be converted to and from an associated raw value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "RawRepresentable"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SY8RawValueQa",
          "text": "RawValue"
        },
        {
          "kind": "text",
          "text": ">"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SY",
      "kind": "symbol",
      "role": "symbol",
      "title": "RawRepresentable",
      "type": "topic",
      "url": "/documentation/Swift/RawRepresentable"
    },
    "doc://com.externally.resolved.symbol/s:s8SendableP": {
      "abstract": [
        {
          "text": "A thread-safe type whose values can be shared across arbitrary concurrent contexts without introducing a risk of data races.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Sendable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s8SendableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "Sendable",
      "type": "topic",
      "url": "/documentation/Swift/Sendable"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:SQ",
        "doc://com.externally.resolved.symbol/s:SH",
        "doc://com.externally.resolved.symbol/s:SY",
        "doc://com.externally.resolved.symbol/s:s8SendableP"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Measuring-Performance",
      "generated": true,
      "identifiers": [
        "doc://com.apple.xctest/documentation/XCTest/XCTestCase/measure(_:)",
        "doc://com.apple.xctest/documentation/XCTest/XCTestCase/measureMetrics(_:automaticallyStartMeasuring:for:)",
        "doc://com.apple.xctest/documentation/XCTest/XCTestCase/measure(metrics:block:)",
        "doc://com.apple.xctest/documentation/XCTest/XCTestCase/measure(metrics:options:block:)",
        "doc://com.apple.xctest/documentation/XCTest/XCTestCase/measure(options:block:)",
        "doc://com.apple.xctest/documentation/XCTest/XCTestCase/startMeasuring()",
        "doc://com.apple.xctest/documentation/XCTest/XCTestCase/stopMeasuring()",
        "doc://com.apple.xctest/documentation/XCTest/XCTestCase/defaultPerformanceMetrics",
        "doc://com.apple.xctest/documentation/XCTest/XCTestCase/defaultMetrics",
        "doc://com.apple.xctest/documentation/XCTest/XCTestCase/defaultMeasureOptions"
      ],
      "title": "Measuring Performance"
    }
  ],
  "topicSections": [
    {
      "anchor": "Measuring-Elapsed-Time",
      "identifiers": [
        "doc://com.apple.xctest/documentation/XCTest/XCTPerformanceMetric/wallClockTime"
      ],
      "title": "Measuring Elapsed Time"
    },
    {
      "anchor": "Initializing-an-Item",
      "identifiers": [
        "doc://com.apple.xctest/documentation/XCTest/XCTPerformanceMetric/init(_:)",
        "doc://com.apple.xctest/documentation/XCTest/XCTPerformanceMetric/init(rawValue:)"
      ],
      "title": "Initializing an Item"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "add",
          "path": "/metadata/platforms",
          "value": null
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Type Alias"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "XCTPerformanceMetric"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "typealias"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "XCTPerformanceMetric"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "XCTPerformanceMetric"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.xctest/documentation/XCTest"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Measuring-Elapsed-Time",
              "identifiers": [
                "doc://com.apple.xctest/documentation/XCTest/XCTPerformanceMetric/wallClockTime"
              ],
              "title": "Measuring Elapsed Time"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Measuring-Performance",
              "generated": true,
              "identifiers": [
                "doc://com.apple.xctest/documentation/XCTest/XCTestCase/measure(_:)",
                "doc://com.apple.xctest/documentation/XCTest/XCTestCase/measureMetrics(_:automaticallyStartMeasuring:for:)",
                "doc://com.apple.xctest/documentation/XCTest/XCTestCase/measure(metrics:block:)",
                "doc://com.apple.xctest/documentation/XCTest/XCTestCase/measure(metrics:options:block:)",
                "doc://com.apple.xctest/documentation/XCTest/XCTestCase/measure(options:block:)",
                "doc://com.apple.xctest/documentation/XCTest/XCTestCase/startMeasuring()",
                "doc://com.apple.xctest/documentation/XCTest/XCTestCase/stopMeasuring()",
                "doc://com.apple.xctest/documentation/XCTest/XCTestCase/defaultPerformanceMetrics",
                "doc://com.apple.xctest/documentation/XCTest/XCTestCase/defaultMetrics",
                "doc://com.apple.xctest/documentation/XCTest/XCTestCase/defaultMeasureOptions"
              ],
              "title": "Measuring Performance"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "typedef"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSString",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(cs)NSString",
                    "text": "NSString"
                  },
                  {
                    "kind": "text",
                    "text": " * "
                  },
                  {
                    "kind": "identifier",
                    "text": "XCTPerformanceMetric"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCTestCase~1measure(metrics:options:block:)/title",
          "value": "measureWithMetrics:options:block:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCTestCase~1measure(metrics:options:block:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "measureWithMetrics:options:block:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCTestCase~1defaultPerformanceMetrics/title",
          "value": "defaultPerformanceMetrics"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCTestCase~1defaultPerformanceMetrics/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "defaultPerformanceMetrics"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCTPerformanceMetric/title",
          "value": "XCTPerformanceMetric"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCTPerformanceMetric/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "XCTPerformanceMetric"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCTPerformanceMetric/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "XCTPerformanceMetric"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCTestCase~1measure(options:block:)/title",
          "value": "measureWithOptions:block:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCTestCase~1measure(options:block:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "measureWithOptions:block:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCTestCase~1startMeasuring()/title",
          "value": "startMeasuring"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCTestCase~1startMeasuring()/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "startMeasuring"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCTPerformanceMetric~1wallClockTime/title",
          "value": "XCTPerformanceMetric_WallClockTime"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCTPerformanceMetric~1wallClockTime/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "XCTPerformanceMetric_WallClockTime"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:objc(cs)NSString/abstract",
          "value": [
            {
              "text": "A static, plain-text Unicode string object.",
              "type": "text"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCTestCase~1measure(_:)/title",
          "value": "measureBlock:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCTestCase~1measure(_:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "measureBlock:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCTestCase~1measureMetrics(_:automaticallyStartMeasuring:for:)/title",
          "value": "measureMetrics:automaticallyStartMeasuring:forBlock:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCTestCase~1measureMetrics(_:automaticallyStartMeasuring:for:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "measureMetrics:automaticallyStartMeasuring:forBlock:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCTestCase~1measure(metrics:block:)/title",
          "value": "measureWithMetrics:block:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCTestCase~1measure(metrics:block:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "measureWithMetrics:block:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCTestCase~1defaultMetrics/title",
          "value": "defaultMetrics"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCTestCase~1defaultMetrics/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "defaultMetrics"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCTestCase~1stopMeasuring()/title",
          "value": "stopMeasuring"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCTestCase~1stopMeasuring()/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "stopMeasuring"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCTestCase~1defaultMeasureOptions/title",
          "value": "defaultMeasureOptions"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCTestCase~1defaultMeasureOptions/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "defaultMeasureOptions"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/xctest/xctperformancemetric"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/xctest/xctperformancemetric"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
