{
  "abstract": [
    {
      "text": "Defines methods that are called when ",
      "type": "text"
    },
    {
      "identifier": "doc://com.apple.xctest/documentation/XCTest/XCTWaiter",
      "isActive": true,
      "type": "reference"
    },
    {
      "text": " expectations are fulfilled correctly or incorrectly.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.xctest/documentation/XCTest"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.xctest/documentation/XCTest/XCTWaiterDelegate"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(pl)XCTWaiterDelegate",
    "fragments": [
      {
        "kind": "keyword",
        "text": "protocol"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "XCTWaiterDelegate"
      }
    ],
    "modules": [
      {
        "name": "XCTest"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "XCTWaiterDelegate"
      }
    ],
    "role": "symbol",
    "roleHeading": "Protocol",
    "symbolKind": "protocol",
    "title": "XCTWaiterDelegate"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "protocol"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "XCTWaiterDelegate"
            },
            {
              "kind": "text",
              "text": " : "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSObject",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(pl)NSObject",
              "text": "NSObjectProtocol"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "identifier": "doc://com.apple.xctest/documentation/XCTest/XCTestCase",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " instances automatically conform to the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.xctest/documentation/XCTest/XCTWaiterDelegate",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " protocol. If you pass a test case instance as the delegate property of ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.xctest/documentation/XCTest/XCTWaiter",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": "’s ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.xctest/documentation/XCTest/XCTWaiter/init(delegate:)",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " initializer, that test case will automatically report timeouts and other unexpected events as test failures.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.xctest/documentation/XCTest": {
      "abstract": [
        {
          "text": "Create and run unit tests, performance tests, and UI tests for your Xcode project.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.xctest/documentation/XCTest",
      "kind": "symbol",
      "role": "collection",
      "title": "XCTest",
      "type": "topic",
      "url": "/documentation/xctest"
    },
    "doc://com.apple.xctest/documentation/XCTest/XCTWaiter": {
      "abstract": [
        {
          "text": "Waits for the fulfillment of a group of expectations.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "XCTWaiter"
        }
      ],
      "identifier": "doc://com.apple.xctest/documentation/XCTest/XCTWaiter",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "XCTWaiter"
        }
      ],
      "role": "symbol",
      "title": "XCTWaiter",
      "type": "topic",
      "url": "/documentation/xctest/xctwaiter"
    },
    "doc://com.apple.xctest/documentation/XCTest/XCTWaiter/delegate": {
      "abstract": [
        {
          "text": "The delegate to which expectation fulfillment events will be reported.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "delegate"
        },
        {
          "kind": "text",
          "text": ": (any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(pl)XCTWaiterDelegate",
          "text": "XCTWaiterDelegate"
        },
        {
          "kind": "text",
          "text": ")?"
        }
      ],
      "identifier": "doc://com.apple.xctest/documentation/XCTest/XCTWaiter/delegate",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "delegate"
        }
      ],
      "role": "symbol",
      "title": "delegate",
      "type": "topic",
      "url": "/documentation/xctest/xctwaiter/delegate"
    },
    "doc://com.apple.xctest/documentation/XCTest/XCTWaiter/fulfilledExpectations": {
      "abstract": [
        {
          "text": "An array of expectations that were fulfilled, in order, up until the waiter stopped waiting.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "fulfilledExpectations"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)XCTestExpectation",
          "text": "XCTestExpectation"
        },
        {
          "kind": "text",
          "text": "]"
        }
      ],
      "identifier": "doc://com.apple.xctest/documentation/XCTest/XCTWaiter/fulfilledExpectations",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "fulfilledExpectations"
        }
      ],
      "role": "symbol",
      "title": "fulfilledExpectations",
      "type": "topic",
      "url": "/documentation/xctest/xctwaiter/fulfilledexpectations"
    },
    "doc://com.apple.xctest/documentation/XCTest/XCTWaiter/init(delegate:)": {
      "abstract": [
        {
          "text": "Creates a new waiter with the specified delegate.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "delegate"
        },
        {
          "kind": "text",
          "text": ": (any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(pl)XCTWaiterDelegate",
          "text": "XCTWaiterDelegate"
        },
        {
          "kind": "text",
          "text": ")?)"
        }
      ],
      "identifier": "doc://com.apple.xctest/documentation/XCTest/XCTWaiter/init(delegate:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "initWithDelegate:"
        }
      ],
      "role": "symbol",
      "title": "init(delegate:)",
      "type": "topic",
      "url": "/documentation/xctest/xctwaiter/init(delegate:)"
    },
    "doc://com.apple.xctest/documentation/XCTest/XCTWaiterDelegate": {
      "abstract": [
        {
          "text": "Defines methods that are called when ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.xctest/documentation/XCTest/XCTWaiter",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " expectations are fulfilled correctly or incorrectly.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "XCTWaiterDelegate"
        }
      ],
      "identifier": "doc://com.apple.xctest/documentation/XCTest/XCTWaiterDelegate",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "XCTWaiterDelegate"
        }
      ],
      "role": "symbol",
      "title": "XCTWaiterDelegate",
      "type": "topic",
      "url": "/documentation/xctest/xctwaiterdelegate"
    },
    "doc://com.apple.xctest/documentation/XCTest/XCTWaiterDelegate/nestedWaiter(_:wasInterruptedByTimedOutWaiter:)": {
      "abstract": [
        {
          "text": "Invoked when the waiter is interrupted prior to its expectations being fulfilled or timing out.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "nestedWaiter"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)XCTWaiter",
          "text": "XCTWaiter"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "wasInterruptedByTimedOutWaiter"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)XCTWaiter",
          "text": "XCTWaiter"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.xctest/documentation/XCTest/XCTWaiterDelegate/nestedWaiter(_:wasInterruptedByTimedOutWaiter:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "nestedWaiter:wasInterruptedByTimedOutWaiter:"
        }
      ],
      "role": "symbol",
      "title": "nestedWaiter(_:wasInterruptedByTimedOutWaiter:)",
      "type": "topic",
      "url": "/documentation/xctest/xctwaiterdelegate/nestedwaiter(_:wasinterruptedbytimedoutwaiter:)"
    },
    "doc://com.apple.xctest/documentation/XCTest/XCTWaiterDelegate/waiter(_:didFulfillInvertedExpectation:)": {
      "abstract": [
        {
          "text": "Invoked when an expectation whose ",
          "type": "text"
        },
        {
          "code": "isInverted",
          "type": "codeVoice"
        },
        {
          "text": " property is set to ",
          "type": "text"
        },
        {
          "code": "true",
          "type": "codeVoice"
        },
        {
          "text": " is fulfilled.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "waiter"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)XCTWaiter",
          "text": "XCTWaiter"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "didFulfillInvertedExpectation"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)XCTestExpectation",
          "text": "XCTestExpectation"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.xctest/documentation/XCTest/XCTWaiterDelegate/waiter(_:didFulfillInvertedExpectation:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "waiter:didFulfillInvertedExpectation:"
        }
      ],
      "role": "symbol",
      "title": "waiter(_:didFulfillInvertedExpectation:)",
      "type": "topic",
      "url": "/documentation/xctest/xctwaiterdelegate/waiter(_:didfulfillinvertedexpectation:)"
    },
    "doc://com.apple.xctest/documentation/XCTest/XCTWaiterDelegate/waiter(_:didTimeoutWithUnfulfilledExpectations:)": {
      "abstract": [
        {
          "text": "Invoked when not all waited on expectations are fulfilled during the timeout period.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "waiter"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)XCTWaiter",
          "text": "XCTWaiter"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "didTimeoutWithUnfulfilledExpectations"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)XCTestExpectation",
          "text": "XCTestExpectation"
        },
        {
          "kind": "text",
          "text": "])"
        }
      ],
      "identifier": "doc://com.apple.xctest/documentation/XCTest/XCTWaiterDelegate/waiter(_:didTimeoutWithUnfulfilledExpectations:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "waiter:didTimeoutWithUnfulfilledExpectations:"
        }
      ],
      "role": "symbol",
      "title": "waiter(_:didTimeoutWithUnfulfilledExpectations:)",
      "type": "topic",
      "url": "/documentation/xctest/xctwaiterdelegate/waiter(_:didtimeoutwithunfulfilledexpectations:)"
    },
    "doc://com.apple.xctest/documentation/XCTest/XCTWaiterDelegate/waiter(_:fulfillmentDidViolateOrderingConstraintsFor:requiredExpectation:)": {
      "abstract": [
        {
          "text": "Invoked when a waiter is enforcing fulfillment order and an expectation is fulfilled in the wrong order.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "waiter"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)XCTWaiter",
          "text": "XCTWaiter"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "fulfillmentDidViolateOrderingConstraintsFor"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)XCTestExpectation",
          "text": "XCTestExpectation"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "requiredExpectation"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)XCTestExpectation",
          "text": "XCTestExpectation"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.xctest/documentation/XCTest/XCTWaiterDelegate/waiter(_:fulfillmentDidViolateOrderingConstraintsFor:requiredExpectation:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "waiter:fulfillmentDidViolateOrderingConstraintsForExpectation:requiredExpectation:"
        }
      ],
      "role": "symbol",
      "title": "waiter(_:fulfillmentDidViolateOrderingConstraintsFor:requiredExpectation:)",
      "type": "topic",
      "url": "/documentation/xctest/xctwaiterdelegate/waiter(_:fulfillmentdidviolateorderingconstraintsfor:requiredexpectation:)"
    },
    "doc://com.apple.xctest/documentation/XCTest/XCTestCase": {
      "abstract": [
        {
          "text": "The primary class for defining test cases, test methods, and performance tests.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "XCTestCase"
        }
      ],
      "identifier": "doc://com.apple.xctest/documentation/XCTest/XCTestCase",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "XCTestCase"
        }
      ],
      "role": "symbol",
      "title": "XCTestCase",
      "type": "topic",
      "url": "/documentation/xctest/xctestcase"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)NSObject": {
      "abstract": [
        {
          "text": "The group of methods that are fundamental to all Objective-C objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "protocol "
        },
        {
          "kind": "identifier",
          "text": "NSObjectProtocol"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSObject",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSObjectProtocol",
      "type": "topic",
      "url": "/documentation/objectivec/nsobjectprotocol"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/c:objc(pl)NSObject"
      ],
      "kind": "relationships",
      "title": "Inherits From",
      "type": "inheritsFrom"
    },
    {
      "identifiers": [
        "doc://com.apple.xctest/documentation/XCTest/XCTestCase"
      ],
      "kind": "relationships",
      "title": "Conforming Types",
      "type": "conformingTypes"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Responding-to-Expectation-Fulfilment",
      "generated": true,
      "identifiers": [
        "doc://com.apple.xctest/documentation/XCTest/XCTWaiter/delegate",
        "doc://com.apple.xctest/documentation/XCTest/XCTWaiter/fulfilledExpectations"
      ],
      "title": "Responding to Expectation Fulfilment"
    }
  ],
  "topicSections": [
    {
      "anchor": "Timeout-Events",
      "identifiers": [
        "doc://com.apple.xctest/documentation/XCTest/XCTWaiterDelegate/waiter(_:didTimeoutWithUnfulfilledExpectations:)",
        "doc://com.apple.xctest/documentation/XCTest/XCTWaiterDelegate/nestedWaiter(_:wasInterruptedByTimedOutWaiter:)"
      ],
      "title": "Timeout Events"
    },
    {
      "anchor": "Order-of-Fulfillment-Events",
      "identifiers": [
        "doc://com.apple.xctest/documentation/XCTest/XCTWaiterDelegate/waiter(_:fulfillmentDidViolateOrderingConstraintsFor:requiredExpectation:)"
      ],
      "title": "Order of Fulfillment Events"
    },
    {
      "anchor": "Inverted-Expectation-Events",
      "identifiers": [
        "doc://com.apple.xctest/documentation/XCTest/XCTWaiterDelegate/waiter(_:didFulfillInvertedExpectation:)"
      ],
      "title": "Inverted Expectation Events"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "add",
          "path": "/metadata/platforms",
          "value": null
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Protocol"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "XCTWaiterDelegate"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "protocol"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "XCTWaiterDelegate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "XCTWaiterDelegate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.xctest/documentation/XCTest"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Timeout-Events",
              "identifiers": [
                "doc://com.apple.xctest/documentation/XCTest/XCTWaiterDelegate/waiter(_:didTimeoutWithUnfulfilledExpectations:)",
                "doc://com.apple.xctest/documentation/XCTest/XCTWaiterDelegate/nestedWaiter(_:wasInterruptedByTimedOutWaiter:)"
              ],
              "title": "Timeout Events"
            },
            {
              "anchor": "Order-of-Fulfillment-Events",
              "identifiers": [
                "doc://com.apple.xctest/documentation/XCTest/XCTWaiterDelegate/waiter(_:fulfillmentDidViolateOrderingConstraintsFor:requiredExpectation:)"
              ],
              "title": "Order of Fulfillment Events"
            },
            {
              "anchor": "Inverted-Expectation-Events",
              "identifiers": [
                "doc://com.apple.xctest/documentation/XCTest/XCTWaiterDelegate/waiter(_:didFulfillInvertedExpectation:)"
              ],
              "title": "Inverted Expectation Events"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": [
            {
              "identifiers": [
                "doc://com.externally.resolved.symbol/c:objc(pl)NSObject"
              ],
              "kind": "relationships",
              "title": "Inherits From",
              "type": "inheritsFrom"
            },
            {
              "identifiers": [
                "doc://com.apple.xctest/documentation/XCTest/XCTestCase"
              ],
              "kind": "relationships",
              "title": "Conforming Types",
              "type": "conformingTypes"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Responding-to-Expectation-Fulfilment",
              "generated": true,
              "identifiers": [
                "doc://com.apple.xctest/documentation/XCTest/XCTWaiter/delegate",
                "doc://com.apple.xctest/documentation/XCTest/XCTWaiter/fulfilledExpectations"
              ],
              "title": "Responding to Expectation Fulfilment"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "@protocol"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "XCTWaiterDelegate"
                  },
                  {
                    "kind": "text",
                    "text": " <"
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSObject",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(pl)NSObject",
                    "text": "NSObject"
                  },
                  {
                    "kind": "text",
                    "text": ">"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCTWaiter/title",
          "value": "XCTWaiter"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCTWaiter/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "XCTWaiter"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCTWaiter/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "XCTWaiter"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCTWaiter~1fulfilledExpectations/title",
          "value": "fulfilledExpectations"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCTWaiter~1fulfilledExpectations/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "fulfilledExpectations"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCTWaiterDelegate/title",
          "value": "XCTWaiterDelegate"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCTWaiterDelegate/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "XCTWaiterDelegate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCTWaiterDelegate/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "XCTWaiterDelegate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCTWaiter~1init(delegate:)/title",
          "value": "initWithDelegate:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCTWaiter~1init(delegate:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "initWithDelegate:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCTWaiter~1delegate/title",
          "value": "delegate"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCTWaiter~1delegate/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "delegate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:objc(pl)NSObject/title",
          "value": "NSObject"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCTWaiterDelegate~1nestedWaiter(_:wasInterruptedByTimedOutWaiter:)/title",
          "value": "nestedWaiter:wasInterruptedByTimedOutWaiter:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCTWaiterDelegate~1nestedWaiter(_:wasInterruptedByTimedOutWaiter:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "nestedWaiter:wasInterruptedByTimedOutWaiter:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCTWaiterDelegate~1waiter(_:didFulfillInvertedExpectation:)/title",
          "value": "waiter:didFulfillInvertedExpectation:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCTWaiterDelegate~1waiter(_:didFulfillInvertedExpectation:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "waiter:didFulfillInvertedExpectation:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCTestCase/title",
          "value": "XCTestCase"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCTestCase/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "XCTestCase"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCTestCase/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "XCTestCase"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCTWaiterDelegate~1waiter(_:fulfillmentDidViolateOrderingConstraintsFor:requiredExpectation:)/title",
          "value": "waiter:fulfillmentDidViolateOrderingConstraintsForExpectation:requiredExpectation:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCTWaiterDelegate~1waiter(_:fulfillmentDidViolateOrderingConstraintsFor:requiredExpectation:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "waiter:fulfillmentDidViolateOrderingConstraintsForExpectation:requiredExpectation:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCTWaiterDelegate~1waiter(_:didTimeoutWithUnfulfilledExpectations:)/title",
          "value": "waiter:didTimeoutWithUnfulfilledExpectations:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCTWaiterDelegate~1waiter(_:didTimeoutWithUnfulfilledExpectations:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "waiter:didTimeoutWithUnfulfilledExpectations:"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/xctest/xctwaiterdelegate"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/xctest/xctwaiterdelegate"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
