{
  "abstract": [
    {
      "text": "A location on screen relative to some UI element.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.xctest/documentation/XCTest"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.xctest/documentation/XCTest/XCUICoordinate"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(cs)XCUICoordinate",
    "fragments": [
      {
        "kind": "keyword",
        "text": "class"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "XCUICoordinate"
      }
    ],
    "modules": [
      {
        "name": "XCTest"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "XCUICoordinate"
      }
    ],
    "role": "symbol",
    "roleHeading": "Class",
    "symbolKind": "class",
    "title": "XCUICoordinate"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "macOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "attribute",
              "text": "@"
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:ScM",
              "kind": "attribute",
              "preciseIdentifier": "s:ScM",
              "text": "MainActor"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "keyword",
              "text": "class"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "XCUICoordinate"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Coordinates are dynamic, like the elements to which they refer, and may compute different screen locations at different times, or be invalid if the element they reference doesn’t exist.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.xctest/documentation/XCTest": {
      "abstract": [
        {
          "text": "Create and run unit tests, performance tests, and UI tests for your Xcode project.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.xctest/documentation/XCTest",
      "kind": "symbol",
      "role": "collection",
      "title": "XCTest",
      "type": "topic",
      "url": "/documentation/xctest"
    },
    "doc://com.apple.xctest/documentation/XCTest/XCUICoordinate": {
      "abstract": [
        {
          "text": "A location on screen relative to some UI element.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "XCUICoordinate"
        }
      ],
      "identifier": "doc://com.apple.xctest/documentation/XCTest/XCUICoordinate",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "XCUICoordinate"
        }
      ],
      "role": "symbol",
      "title": "XCUICoordinate",
      "type": "topic",
      "url": "/documentation/xctest/xcuicoordinate"
    },
    "doc://com.apple.xctest/documentation/XCTest/XCUICoordinate/click()": {
      "abstract": [
        {
          "text": "Sends a click event at the coordinate.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "click"
        },
        {
          "kind": "text",
          "text": "()"
        }
      ],
      "identifier": "doc://com.apple.xctest/documentation/XCTest/XCUICoordinate/click()",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "click"
        }
      ],
      "role": "symbol",
      "title": "click()",
      "type": "topic",
      "url": "/documentation/xctest/xcuicoordinate/click()"
    },
    "doc://com.apple.xctest/documentation/XCTest/XCUICoordinate/click(forDuration:thenDragTo:)": {
      "abstract": [
        {
          "text": "Clicks and holds for a duration you specify, then drags to the other coordinate.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "click"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "forDuration"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSTimeInterval",
          "text": "TimeInterval"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "thenDragTo"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)XCUICoordinate",
          "text": "XCUICoordinate"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.xctest/documentation/XCTest/XCUICoordinate/click(forDuration:thenDragTo:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "clickForDuration:thenDragToCoordinate:"
        }
      ],
      "role": "symbol",
      "title": "click(forDuration:thenDragTo:)",
      "type": "topic",
      "url": "/documentation/xctest/xcuicoordinate/click(forduration:thendragto:)"
    },
    "doc://com.apple.xctest/documentation/XCTest/XCUICoordinate/click(forDuration:thenDragTo:withVelocity:thenHoldForDuration:)": {
      "abstract": [
        {
          "text": "Clicks and holds for a duration you specify, drags at a velocity you specify, and holds over the other coordinate for a duration you specify.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "click"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "forDuration"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSTimeInterval",
          "text": "TimeInterval"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "thenDragTo"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)XCUICoordinate",
          "text": "XCUICoordinate"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "withVelocity"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@XCUIGestureVelocity",
          "text": "XCUIGestureVelocity"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "thenHoldForDuration"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSTimeInterval",
          "text": "TimeInterval"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.xctest/documentation/XCTest/XCUICoordinate/click(forDuration:thenDragTo:withVelocity:thenHoldForDuration:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "clickForDuration:thenDragToCoordinate:withVelocity:thenHoldForDuration:"
        }
      ],
      "role": "symbol",
      "title": "click(forDuration:thenDragTo:withVelocity:thenHoldForDuration:)",
      "type": "topic",
      "url": "/documentation/xctest/xcuicoordinate/click(forduration:thendragto:withvelocity:thenholdforduration:)"
    },
    "doc://com.apple.xctest/documentation/XCTest/XCUICoordinate/doubleClick()": {
      "abstract": [
        {
          "text": "Sends a double-click event at the coordinate.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "doubleClick"
        },
        {
          "kind": "text",
          "text": "()"
        }
      ],
      "identifier": "doc://com.apple.xctest/documentation/XCTest/XCUICoordinate/doubleClick()",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "doubleClick"
        }
      ],
      "role": "symbol",
      "title": "doubleClick()",
      "type": "topic",
      "url": "/documentation/xctest/xcuicoordinate/doubleclick()"
    },
    "doc://com.apple.xctest/documentation/XCTest/XCUICoordinate/doubleTap()": {
      "abstract": [
        {
          "text": "Sends a double tap event at the coordinate.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "doubleTap"
        },
        {
          "kind": "text",
          "text": "()"
        }
      ],
      "identifier": "doc://com.apple.xctest/documentation/XCTest/XCUICoordinate/doubleTap()",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "doubleTap"
        }
      ],
      "role": "symbol",
      "title": "doubleTap()",
      "type": "topic",
      "url": "/documentation/xctest/xcuicoordinate/doubletap()"
    },
    "doc://com.apple.xctest/documentation/XCTest/XCUICoordinate/hover()": {
      "abstract": [
        {
          "text": "Moves the pointer to the coordinate.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "hover"
        },
        {
          "kind": "text",
          "text": "()"
        }
      ],
      "identifier": "doc://com.apple.xctest/documentation/XCTest/XCUICoordinate/hover()",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "hover"
        }
      ],
      "role": "symbol",
      "title": "hover()",
      "type": "topic",
      "url": "/documentation/xctest/xcuicoordinate/hover()"
    },
    "doc://com.apple.xctest/documentation/XCTest/XCUICoordinate/press(forDuration:)": {
      "abstract": [
        {
          "text": "Initiates a press-and-hold gesture at the coordinate, holding for the duration you specify.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "press"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "forDuration"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSTimeInterval",
          "text": "TimeInterval"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.xctest/documentation/XCTest/XCUICoordinate/press(forDuration:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "pressForDuration:"
        }
      ],
      "role": "symbol",
      "title": "press(forDuration:)",
      "type": "topic",
      "url": "/documentation/xctest/xcuicoordinate/press(forduration:)"
    },
    "doc://com.apple.xctest/documentation/XCTest/XCUICoordinate/press(forDuration:thenDragTo:)": {
      "abstract": [
        {
          "text": "Initiates a press-and-hold gesture at the coordinate, then drags to another coordinate.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "press"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "forDuration"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSTimeInterval",
          "text": "TimeInterval"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "thenDragTo"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)XCUICoordinate",
          "text": "XCUICoordinate"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.xctest/documentation/XCTest/XCUICoordinate/press(forDuration:thenDragTo:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "pressForDuration:thenDragToCoordinate:"
        }
      ],
      "role": "symbol",
      "title": "press(forDuration:thenDragTo:)",
      "type": "topic",
      "url": "/documentation/xctest/xcuicoordinate/press(forduration:thendragto:)"
    },
    "doc://com.apple.xctest/documentation/XCTest/XCUICoordinate/press(forDuration:thenDragTo:withVelocity:thenHoldForDuration:)": {
      "abstract": [
        {
          "text": "Initiates a press-and-hold gesture, drags to another coordinate with a velocity you specify, and holds for a duration you specify.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "press"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "forDuration"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSTimeInterval",
          "text": "TimeInterval"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "thenDragTo"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)XCUICoordinate",
          "text": "XCUICoordinate"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "withVelocity"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@XCUIGestureVelocity",
          "text": "XCUIGestureVelocity"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "thenHoldForDuration"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSTimeInterval",
          "text": "TimeInterval"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.xctest/documentation/XCTest/XCUICoordinate/press(forDuration:thenDragTo:withVelocity:thenHoldForDuration:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "pressForDuration:thenDragToCoordinate:withVelocity:thenHoldForDuration:"
        }
      ],
      "role": "symbol",
      "title": "press(forDuration:thenDragTo:withVelocity:thenHoldForDuration:)",
      "type": "topic",
      "url": "/documentation/xctest/xcuicoordinate/press(forduration:thendragto:withvelocity:thenholdforduration:)"
    },
    "doc://com.apple.xctest/documentation/XCTest/XCUICoordinate/referencedElement": {
      "abstract": [
        {
          "text": "The element that the coordinate is based on, either directly or through the coordinate from which it was derived.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "referencedElement"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)XCUIElement",
          "text": "XCUIElement"
        }
      ],
      "identifier": "doc://com.apple.xctest/documentation/XCTest/XCUICoordinate/referencedElement",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "referencedElement"
        }
      ],
      "role": "symbol",
      "title": "referencedElement",
      "type": "topic",
      "url": "/documentation/xctest/xcuicoordinate/referencedelement"
    },
    "doc://com.apple.xctest/documentation/XCTest/XCUICoordinate/rightClick()": {
      "abstract": [
        {
          "text": "Sends a Control-click event at the coordinate.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "rightClick"
        },
        {
          "kind": "text",
          "text": "()"
        }
      ],
      "identifier": "doc://com.apple.xctest/documentation/XCTest/XCUICoordinate/rightClick()",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "rightClick"
        }
      ],
      "role": "symbol",
      "title": "rightClick()",
      "type": "topic",
      "url": "/documentation/xctest/xcuicoordinate/rightclick()"
    },
    "doc://com.apple.xctest/documentation/XCTest/XCUICoordinate/screenPoint": {
      "abstract": [
        {
          "text": "The dynamically computed value of the coordinate’s location on screen.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "screenPoint"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@CGPoint",
          "text": "CGPoint"
        }
      ],
      "identifier": "doc://com.apple.xctest/documentation/XCTest/XCUICoordinate/screenPoint",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "screenPoint"
        }
      ],
      "role": "symbol",
      "title": "screenPoint",
      "type": "topic",
      "url": "/documentation/xctest/xcuicoordinate/screenpoint"
    },
    "doc://com.apple.xctest/documentation/XCTest/XCUICoordinate/scroll(byDeltaX:deltaY:)": {
      "abstract": [
        {
          "text": "Scrolls the view by the number of x and y pixels you specify.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "scroll"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "byDeltaX"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:14CoreFoundation7CGFloatV",
          "text": "CGFloat"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "deltaY"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:14CoreFoundation7CGFloatV",
          "text": "CGFloat"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.xctest/documentation/XCTest/XCUICoordinate/scroll(byDeltaX:deltaY:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "scrollByDeltaX:deltaY:"
        }
      ],
      "role": "symbol",
      "title": "scroll(byDeltaX:deltaY:)",
      "type": "topic",
      "url": "/documentation/xctest/xcuicoordinate/scroll(bydeltax:deltay:)"
    },
    "doc://com.apple.xctest/documentation/XCTest/XCUICoordinate/swipeDown()": {
      "abstract": [
        {
          "text": "Sends a swipe-down gesture.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "swipeDown"
        },
        {
          "kind": "text",
          "text": "()"
        }
      ],
      "identifier": "doc://com.apple.xctest/documentation/XCTest/XCUICoordinate/swipeDown()",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "swipeDown"
        }
      ],
      "role": "symbol",
      "title": "swipeDown()",
      "type": "topic",
      "url": "/documentation/xctest/xcuicoordinate/swipedown()"
    },
    "doc://com.apple.xctest/documentation/XCTest/XCUICoordinate/swipeDown(velocity:)": {
      "abstract": [
        {
          "text": "Sends a swipe-down gesture with a velocity you specify.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "swipeDown"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "velocity"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@XCUIGestureVelocity",
          "text": "XCUIGestureVelocity"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.xctest/documentation/XCTest/XCUICoordinate/swipeDown(velocity:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "swipeDownWithVelocity:"
        }
      ],
      "role": "symbol",
      "title": "swipeDown(velocity:)",
      "type": "topic",
      "url": "/documentation/xctest/xcuicoordinate/swipedown(velocity:)"
    },
    "doc://com.apple.xctest/documentation/XCTest/XCUICoordinate/swipeLeft()": {
      "abstract": [
        {
          "text": "Sends a swipe-left gesture.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "swipeLeft"
        },
        {
          "kind": "text",
          "text": "()"
        }
      ],
      "identifier": "doc://com.apple.xctest/documentation/XCTest/XCUICoordinate/swipeLeft()",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "swipeLeft"
        }
      ],
      "role": "symbol",
      "title": "swipeLeft()",
      "type": "topic",
      "url": "/documentation/xctest/xcuicoordinate/swipeleft()"
    },
    "doc://com.apple.xctest/documentation/XCTest/XCUICoordinate/swipeLeft(velocity:)": {
      "abstract": [
        {
          "text": "Sends a swipe-left gesture with a velocity you specify.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "swipeLeft"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "velocity"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@XCUIGestureVelocity",
          "text": "XCUIGestureVelocity"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.xctest/documentation/XCTest/XCUICoordinate/swipeLeft(velocity:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "swipeLeftWithVelocity:"
        }
      ],
      "role": "symbol",
      "title": "swipeLeft(velocity:)",
      "type": "topic",
      "url": "/documentation/xctest/xcuicoordinate/swipeleft(velocity:)"
    },
    "doc://com.apple.xctest/documentation/XCTest/XCUICoordinate/swipeRight()": {
      "abstract": [
        {
          "text": "Sends a swipe-right gesture.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "swipeRight"
        },
        {
          "kind": "text",
          "text": "()"
        }
      ],
      "identifier": "doc://com.apple.xctest/documentation/XCTest/XCUICoordinate/swipeRight()",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "swipeRight"
        }
      ],
      "role": "symbol",
      "title": "swipeRight()",
      "type": "topic",
      "url": "/documentation/xctest/xcuicoordinate/swiperight()"
    },
    "doc://com.apple.xctest/documentation/XCTest/XCUICoordinate/swipeRight(velocity:)": {
      "abstract": [
        {
          "text": "Sends a swipe-right gesture with a velocity you specify.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "swipeRight"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "velocity"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@XCUIGestureVelocity",
          "text": "XCUIGestureVelocity"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.xctest/documentation/XCTest/XCUICoordinate/swipeRight(velocity:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "swipeRightWithVelocity:"
        }
      ],
      "role": "symbol",
      "title": "swipeRight(velocity:)",
      "type": "topic",
      "url": "/documentation/xctest/xcuicoordinate/swiperight(velocity:)"
    },
    "doc://com.apple.xctest/documentation/XCTest/XCUICoordinate/swipeUp()": {
      "abstract": [
        {
          "text": "Sends a swipe-up gesture.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "swipeUp"
        },
        {
          "kind": "text",
          "text": "()"
        }
      ],
      "identifier": "doc://com.apple.xctest/documentation/XCTest/XCUICoordinate/swipeUp()",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "swipeUp"
        }
      ],
      "role": "symbol",
      "title": "swipeUp()",
      "type": "topic",
      "url": "/documentation/xctest/xcuicoordinate/swipeup()"
    },
    "doc://com.apple.xctest/documentation/XCTest/XCUICoordinate/swipeUp(velocity:)": {
      "abstract": [
        {
          "text": "Sends a swipe-up gesture with a velocity you specify.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "swipeUp"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "velocity"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@XCUIGestureVelocity",
          "text": "XCUIGestureVelocity"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.xctest/documentation/XCTest/XCUICoordinate/swipeUp(velocity:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "swipeUpWithVelocity:"
        }
      ],
      "role": "symbol",
      "title": "swipeUp(velocity:)",
      "type": "topic",
      "url": "/documentation/xctest/xcuicoordinate/swipeup(velocity:)"
    },
    "doc://com.apple.xctest/documentation/XCTest/XCUICoordinate/tap()": {
      "abstract": [
        {
          "text": "Sends a tap event at the coordinate.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "tap"
        },
        {
          "kind": "text",
          "text": "()"
        }
      ],
      "identifier": "doc://com.apple.xctest/documentation/XCTest/XCUICoordinate/tap()",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "tap"
        }
      ],
      "role": "symbol",
      "title": "tap()",
      "type": "topic",
      "url": "/documentation/xctest/xcuicoordinate/tap()"
    },
    "doc://com.apple.xctest/documentation/XCTest/XCUICoordinate/withOffset(_:)": {
      "abstract": [
        {
          "text": "Creates a new coordinate with an absolute offset in points from the original coordinate.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "withOffset"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@CGVector",
          "text": "CGVector"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)XCUICoordinate",
          "text": "XCUICoordinate"
        }
      ],
      "identifier": "doc://com.apple.xctest/documentation/XCTest/XCUICoordinate/withOffset(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "coordinateWithOffset:"
        }
      ],
      "role": "symbol",
      "title": "withOffset(_:)",
      "type": "topic",
      "url": "/documentation/xctest/xcuicoordinate/withoffset(_:)"
    },
    "doc://com.apple.xctest/documentation/XCTest/XCUIElement": {
      "abstract": [
        {
          "text": "A UI element in an application.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "XCUIElement"
        }
      ],
      "identifier": "doc://com.apple.xctest/documentation/XCTest/XCUIElement",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "XCUIElement"
        }
      ],
      "role": "symbol",
      "title": "XCUIElement",
      "type": "topic",
      "url": "/documentation/xctest/xcuielement"
    },
    "doc://com.apple.xctest/documentation/XCTest/XCUIElementAttributes": {
      "abstract": [
        {
          "text": "Attributes exposed by UI elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "XCUIElementAttributes"
        }
      ],
      "identifier": "doc://com.apple.xctest/documentation/XCTest/XCUIElementAttributes",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "XCUIElementAttributes"
        }
      ],
      "role": "symbol",
      "title": "XCUIElementAttributes",
      "type": "topic",
      "url": "/documentation/xctest/xcuielementattributes"
    },
    "doc://com.apple.xctest/documentation/XCTest/XCUIElementSnapshot": {
      "abstract": [
        {
          "text": "A set of attributes to express a snapshot of an element’s attributes and descendant user interface hierarchy.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "XCUIElementSnapshot"
        }
      ],
      "identifier": "doc://com.apple.xctest/documentation/XCTest/XCUIElementSnapshot",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "XCUIElementSnapshot"
        }
      ],
      "role": "symbol",
      "title": "XCUIElementSnapshot",
      "type": "topic",
      "url": "/documentation/xctest/xcuielementsnapshot"
    },
    "doc://com.apple.xctest/documentation/XCTest/XCUIElementSnapshotProviding": {
      "abstract": [
        {
          "text": "A method to capture a snapshot of an element’s attributes and descendant user interface hierarchy.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "XCUIElementSnapshotProviding"
        }
      ],
      "identifier": "doc://com.apple.xctest/documentation/XCTest/XCUIElementSnapshotProviding",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "XCUIElementSnapshotProviding"
        }
      ],
      "role": "symbol",
      "title": "XCUIElementSnapshotProviding",
      "type": "topic",
      "url": "/documentation/xctest/xcuielementsnapshotproviding"
    },
    "doc://com.externally.resolved.symbol/c:objc(cs)NSObject": {
      "abstract": [
        {
          "text": "The root class of most Objective-C class hierarchies, from which subclasses inherit a basic interface to the runtime system and the ability to behave as Objective-C objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "class "
        },
        {
          "kind": "identifier",
          "text": "NSObject"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSObject",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSObject",
      "type": "topic",
      "url": "/documentation/objectivec/nsobject"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)NSCopying": {
      "abstract": [
        {
          "text": "A protocol that objects adopt to provide functional copies of themselves.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "protocol "
        },
        {
          "kind": "identifier",
          "text": "NSCopying"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSCopying",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSCopying",
      "type": "topic",
      "url": "/documentation/foundation/nscopying"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)NSObject": {
      "abstract": [
        {
          "text": "The group of methods that are fundamental to all Objective-C objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "protocol "
        },
        {
          "kind": "identifier",
          "text": "NSObjectProtocol"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSObject",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSObjectProtocol",
      "type": "topic",
      "url": "/documentation/objectivec/nsobjectprotocol"
    },
    "doc://com.externally.resolved.symbol/s:SH": {
      "abstract": [
        {
          "text": "A type that can be hashed into a `Hasher` to produce an integer hash value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Hashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SQ",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SH",
      "kind": "symbol",
      "role": "symbol",
      "title": "Hashable",
      "type": "topic",
      "url": "/documentation/Swift/Hashable"
    },
    "doc://com.externally.resolved.symbol/s:SQ": {
      "abstract": [
        {
          "text": "A type that can be compared for value equality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SQ",
      "kind": "symbol",
      "role": "symbol",
      "title": "Equatable",
      "type": "topic",
      "url": "/documentation/Swift/Equatable"
    },
    "doc://com.externally.resolved.symbol/s:ScM": {
      "abstract": [
        {
          "text": "A singleton actor whose executor is equivalent to the main dispatch queue.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@globalActor"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "final"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "actor"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MainActor"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:ScM",
      "kind": "symbol",
      "role": "symbol",
      "title": "MainActor",
      "type": "topic",
      "url": "/documentation/Swift/MainActor"
    },
    "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP": {
      "abstract": [
        {
          "text": "A type with a customized textual representation.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CustomStringConvertible"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CustomStringConvertible",
      "type": "topic",
      "url": "/documentation/Swift/CustomStringConvertible"
    },
    "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP": {
      "abstract": [
        {
          "text": "A type with a customized textual representation suitable for debugging purposes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CustomDebugStringConvertible"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CustomDebugStringConvertible",
      "type": "topic",
      "url": "/documentation/Swift/CustomDebugStringConvertible"
    },
    "doc://com.externally.resolved.symbol/s:s7CVarArgP": {
      "abstract": [
        {
          "text": "A type whose instances can be encoded, and appropriately passed, as elements of a C `va_list`.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CVarArg"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s7CVarArgP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CVarArg",
      "type": "topic",
      "url": "/documentation/Swift/CVarArg"
    },
    "doc://com.externally.resolved.symbol/s:s8SendableP": {
      "abstract": [
        {
          "text": "A thread-safe type whose values can be shared across arbitrary concurrent contexts without introducing a risk of data races.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Sendable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s8SendableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "Sendable",
      "type": "topic",
      "url": "/documentation/Swift/Sendable"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/c:objc(cs)NSObject"
      ],
      "kind": "relationships",
      "title": "Inherits From",
      "type": "inheritsFrom"
    },
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:s7CVarArgP",
        "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP",
        "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP",
        "doc://com.externally.resolved.symbol/s:SQ",
        "doc://com.externally.resolved.symbol/s:SH",
        "doc://com.externally.resolved.symbol/c:objc(pl)NSCopying",
        "doc://com.externally.resolved.symbol/c:objc(pl)NSObject",
        "doc://com.externally.resolved.symbol/s:s8SendableP"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "UI-Elements",
      "generated": true,
      "identifiers": [
        "doc://com.apple.xctest/documentation/XCTest/XCUIElement",
        "doc://com.apple.xctest/documentation/XCTest/XCUIElementAttributes",
        "doc://com.apple.xctest/documentation/XCTest/XCUIElementSnapshot",
        "doc://com.apple.xctest/documentation/XCTest/XCUIElementSnapshotProviding"
      ],
      "title": "UI Elements"
    }
  ],
  "topicSections": [
    {
      "anchor": "Getting-Coordinate-Properties",
      "identifiers": [
        "doc://com.apple.xctest/documentation/XCTest/XCUICoordinate/referencedElement",
        "doc://com.apple.xctest/documentation/XCTest/XCUICoordinate/screenPoint"
      ],
      "title": "Getting Coordinate Properties"
    },
    {
      "abstract": [
        {
          "text": "Available in macOS and in iPadOS 15 and later.",
          "type": "text"
        }
      ],
      "anchor": "Moving-the-Pointer",
      "identifiers": [
        "doc://com.apple.xctest/documentation/XCTest/XCUICoordinate/hover()"
      ],
      "title": "Moving the Pointer"
    },
    {
      "abstract": [
        {
          "text": "Available in macOS and in iPadOS 15 and later.",
          "type": "text"
        }
      ],
      "anchor": "Clicking",
      "identifiers": [
        "doc://com.apple.xctest/documentation/XCTest/XCUICoordinate/click()",
        "doc://com.apple.xctest/documentation/XCTest/XCUICoordinate/click(forDuration:thenDragTo:)",
        "doc://com.apple.xctest/documentation/XCTest/XCUICoordinate/click(forDuration:thenDragTo:withVelocity:thenHoldForDuration:)",
        "doc://com.apple.xctest/documentation/XCTest/XCUICoordinate/doubleClick()",
        "doc://com.apple.xctest/documentation/XCTest/XCUICoordinate/rightClick()"
      ],
      "title": "Clicking"
    },
    {
      "abstract": [
        {
          "text": "Available in macOS and in iPadOS 15 and later.",
          "type": "text"
        }
      ],
      "anchor": "Scrolling",
      "identifiers": [
        "doc://com.apple.xctest/documentation/XCTest/XCUICoordinate/scroll(byDeltaX:deltaY:)"
      ],
      "title": "Scrolling"
    },
    {
      "abstract": [
        {
          "text": "Available in iOS and for Touch Bar interactions in macOS.",
          "type": "text"
        }
      ],
      "anchor": "Tapping-and-Pressing",
      "identifiers": [
        "doc://com.apple.xctest/documentation/XCTest/XCUICoordinate/tap()",
        "doc://com.apple.xctest/documentation/XCTest/XCUICoordinate/doubleTap()",
        "doc://com.apple.xctest/documentation/XCTest/XCUICoordinate/press(forDuration:)",
        "doc://com.apple.xctest/documentation/XCTest/XCUICoordinate/press(forDuration:thenDragTo:)",
        "doc://com.apple.xctest/documentation/XCTest/XCUICoordinate/press(forDuration:thenDragTo:withVelocity:thenHoldForDuration:)"
      ],
      "title": "Tapping and Pressing"
    },
    {
      "anchor": "Performing-Gestures",
      "identifiers": [
        "doc://com.apple.xctest/documentation/XCTest/XCUICoordinate/swipeLeft()",
        "doc://com.apple.xctest/documentation/XCTest/XCUICoordinate/swipeLeft(velocity:)",
        "doc://com.apple.xctest/documentation/XCTest/XCUICoordinate/swipeRight()",
        "doc://com.apple.xctest/documentation/XCTest/XCUICoordinate/swipeRight(velocity:)",
        "doc://com.apple.xctest/documentation/XCTest/XCUICoordinate/swipeUp()",
        "doc://com.apple.xctest/documentation/XCTest/XCUICoordinate/swipeUp(velocity:)",
        "doc://com.apple.xctest/documentation/XCTest/XCUICoordinate/swipeDown()",
        "doc://com.apple.xctest/documentation/XCTest/XCUICoordinate/swipeDown(velocity:)"
      ],
      "title": "Performing Gestures"
    },
    {
      "anchor": "Creating-Relative-Coordinates",
      "identifiers": [
        "doc://com.apple.xctest/documentation/XCTest/XCUICoordinate/withOffset(_:)"
      ],
      "title": "Creating Relative Coordinates"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "add",
          "path": "/metadata/platforms",
          "value": null
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Class"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "XCUICoordinate"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "class"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "XCUICoordinate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "XCUICoordinate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.xctest/documentation/XCTest"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Getting-Coordinate-Properties",
              "identifiers": [
                "doc://com.apple.xctest/documentation/XCTest/XCUICoordinate/referencedElement",
                "doc://com.apple.xctest/documentation/XCTest/XCUICoordinate/screenPoint"
              ],
              "title": "Getting Coordinate Properties"
            },
            {
              "abstract": [
                {
                  "text": "Available in macOS and in iPadOS 15 and later.",
                  "type": "text"
                }
              ],
              "anchor": "Moving-the-Pointer",
              "identifiers": [
                "doc://com.apple.xctest/documentation/XCTest/XCUICoordinate/hover()"
              ],
              "title": "Moving the Pointer"
            },
            {
              "abstract": [
                {
                  "text": "Available in macOS and in iPadOS 15 and later.",
                  "type": "text"
                }
              ],
              "anchor": "Clicking",
              "identifiers": [
                "doc://com.apple.xctest/documentation/XCTest/XCUICoordinate/click()",
                "doc://com.apple.xctest/documentation/XCTest/XCUICoordinate/click(forDuration:thenDragTo:)",
                "doc://com.apple.xctest/documentation/XCTest/XCUICoordinate/click(forDuration:thenDragTo:withVelocity:thenHoldForDuration:)",
                "doc://com.apple.xctest/documentation/XCTest/XCUICoordinate/doubleClick()",
                "doc://com.apple.xctest/documentation/XCTest/XCUICoordinate/rightClick()"
              ],
              "title": "Clicking"
            },
            {
              "abstract": [
                {
                  "text": "Available in macOS and in iPadOS 15 and later.",
                  "type": "text"
                }
              ],
              "anchor": "Scrolling",
              "identifiers": [
                "doc://com.apple.xctest/documentation/XCTest/XCUICoordinate/scroll(byDeltaX:deltaY:)"
              ],
              "title": "Scrolling"
            },
            {
              "abstract": [
                {
                  "text": "Available in iOS and for Touch Bar interactions in macOS.",
                  "type": "text"
                }
              ],
              "anchor": "Tapping-and-Pressing",
              "identifiers": [
                "doc://com.apple.xctest/documentation/XCTest/XCUICoordinate/tap()",
                "doc://com.apple.xctest/documentation/XCTest/XCUICoordinate/doubleTap()",
                "doc://com.apple.xctest/documentation/XCTest/XCUICoordinate/press(forDuration:)",
                "doc://com.apple.xctest/documentation/XCTest/XCUICoordinate/press(forDuration:thenDragTo:)",
                "doc://com.apple.xctest/documentation/XCTest/XCUICoordinate/press(forDuration:thenDragTo:withVelocity:thenHoldForDuration:)"
              ],
              "title": "Tapping and Pressing"
            },
            {
              "anchor": "Performing-Gestures",
              "identifiers": [
                "doc://com.apple.xctest/documentation/XCTest/XCUICoordinate/swipeLeft()",
                "doc://com.apple.xctest/documentation/XCTest/XCUICoordinate/swipeLeft(velocity:)",
                "doc://com.apple.xctest/documentation/XCTest/XCUICoordinate/swipeRight()",
                "doc://com.apple.xctest/documentation/XCTest/XCUICoordinate/swipeRight(velocity:)",
                "doc://com.apple.xctest/documentation/XCTest/XCUICoordinate/swipeUp()",
                "doc://com.apple.xctest/documentation/XCTest/XCUICoordinate/swipeUp(velocity:)",
                "doc://com.apple.xctest/documentation/XCTest/XCUICoordinate/swipeDown()",
                "doc://com.apple.xctest/documentation/XCTest/XCUICoordinate/swipeDown(velocity:)"
              ],
              "title": "Performing Gestures"
            },
            {
              "anchor": "Creating-Relative-Coordinates",
              "identifiers": [
                "doc://com.apple.xctest/documentation/XCTest/XCUICoordinate/withOffset(_:)"
              ],
              "title": "Creating Relative Coordinates"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": [
            {
              "identifiers": [
                "doc://com.externally.resolved.symbol/c:objc(cs)NSObject"
              ],
              "kind": "relationships",
              "title": "Inherits From",
              "type": "inheritsFrom"
            },
            {
              "identifiers": [
                "doc://com.externally.resolved.symbol/c:objc(pl)NSCopying"
              ],
              "kind": "relationships",
              "title": "Conforms To",
              "type": "conformsTo"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "UI-Elements",
              "generated": true,
              "identifiers": [
                "doc://com.apple.xctest/documentation/XCTest/XCUIElement",
                "doc://com.apple.xctest/documentation/XCTest/XCUIElementAttributes",
                "doc://com.apple.xctest/documentation/XCTest/XCUIElementSnapshot",
                "doc://com.apple.xctest/documentation/XCTest/XCUIElementSnapshotProviding"
              ],
              "title": "UI Elements"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "macOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "@interface"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "XCUICoordinate"
                  },
                  {
                    "kind": "text",
                    "text": " : "
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSObject",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(cs)NSObject",
                    "text": "NSObject"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCUICoordinate~1scroll(byDeltaX:deltaY:)/title",
          "value": "scrollByDeltaX:deltaY:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCUICoordinate~1scroll(byDeltaX:deltaY:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "scrollByDeltaX:deltaY:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCUICoordinate~1hover()/title",
          "value": "hover"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCUICoordinate~1hover()/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "hover"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCUICoordinate~1click()/title",
          "value": "click"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCUICoordinate~1click()/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "click"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCUICoordinate~1swipeLeft(velocity:)/title",
          "value": "swipeLeftWithVelocity:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCUICoordinate~1swipeLeft(velocity:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "swipeLeftWithVelocity:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCUICoordinate~1press(forDuration:thenDragTo:withVelocity:thenHoldForDuration:)/title",
          "value": "pressForDuration:thenDragToCoordinate:withVelocity:thenHoldForDuration:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCUICoordinate~1press(forDuration:thenDragTo:withVelocity:thenHoldForDuration:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "pressForDuration:thenDragToCoordinate:withVelocity:thenHoldForDuration:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCUIElementSnapshot/title",
          "value": "XCUIElementSnapshot"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCUIElementSnapshot/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "XCUIElementSnapshot"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCUIElementSnapshot/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "XCUIElementSnapshot"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCUICoordinate~1doubleTap()/title",
          "value": "doubleTap"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCUICoordinate~1doubleTap()/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "doubleTap"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCUICoordinate~1click(forDuration:thenDragTo:withVelocity:thenHoldForDuration:)/title",
          "value": "clickForDuration:thenDragToCoordinate:withVelocity:thenHoldForDuration:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCUICoordinate~1click(forDuration:thenDragTo:withVelocity:thenHoldForDuration:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "clickForDuration:thenDragToCoordinate:withVelocity:thenHoldForDuration:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:objc(pl)NSObject/title",
          "value": "NSObject"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCUICoordinate~1rightClick()/title",
          "value": "rightClick"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCUICoordinate~1rightClick()/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "rightClick"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCUICoordinate~1swipeDown(velocity:)/title",
          "value": "swipeDownWithVelocity:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCUICoordinate~1swipeDown(velocity:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "swipeDownWithVelocity:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCUICoordinate~1swipeRight()/title",
          "value": "swipeRight"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCUICoordinate~1swipeRight()/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "swipeRight"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCUICoordinate~1press(forDuration:thenDragTo:)/title",
          "value": "pressForDuration:thenDragToCoordinate:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCUICoordinate~1press(forDuration:thenDragTo:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "pressForDuration:thenDragToCoordinate:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCUICoordinate~1referencedElement/title",
          "value": "referencedElement"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCUICoordinate~1referencedElement/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "referencedElement"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCUICoordinate~1swipeRight(velocity:)/title",
          "value": "swipeRightWithVelocity:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCUICoordinate~1swipeRight(velocity:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "swipeRightWithVelocity:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCUIElement/title",
          "value": "XCUIElement"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCUIElement/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "XCUIElement"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCUIElement/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "XCUIElement"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCUICoordinate~1swipeUp(velocity:)/title",
          "value": "swipeUpWithVelocity:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCUICoordinate~1swipeUp(velocity:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "swipeUpWithVelocity:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCUICoordinate~1click(forDuration:thenDragTo:)/title",
          "value": "clickForDuration:thenDragToCoordinate:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCUICoordinate~1click(forDuration:thenDragTo:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "clickForDuration:thenDragToCoordinate:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCUIElementAttributes/title",
          "value": "XCUIElementAttributes"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCUIElementAttributes/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "XCUIElementAttributes"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCUIElementAttributes/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "XCUIElementAttributes"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCUICoordinate/title",
          "value": "XCUICoordinate"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCUICoordinate/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "XCUICoordinate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCUICoordinate/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "XCUICoordinate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCUICoordinate~1withOffset(_:)/title",
          "value": "coordinateWithOffset:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCUICoordinate~1withOffset(_:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "coordinateWithOffset:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCUICoordinate~1screenPoint/title",
          "value": "screenPoint"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCUICoordinate~1screenPoint/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "screenPoint"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCUICoordinate~1tap()/title",
          "value": "tap"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCUICoordinate~1tap()/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "tap"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCUICoordinate~1doubleClick()/title",
          "value": "doubleClick"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCUICoordinate~1doubleClick()/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "doubleClick"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCUIElementSnapshotProviding/title",
          "value": "XCUIElementSnapshotProviding"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCUIElementSnapshotProviding/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "XCUIElementSnapshotProviding"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCUIElementSnapshotProviding/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "XCUIElementSnapshotProviding"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCUICoordinate~1swipeLeft()/title",
          "value": "swipeLeft"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCUICoordinate~1swipeLeft()/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "swipeLeft"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCUICoordinate~1swipeUp()/title",
          "value": "swipeUp"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCUICoordinate~1swipeUp()/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "swipeUp"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCUICoordinate~1swipeDown()/title",
          "value": "swipeDown"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCUICoordinate~1swipeDown()/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "swipeDown"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCUICoordinate~1press(forDuration:)/title",
          "value": "pressForDuration:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCUICoordinate~1press(forDuration:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "pressForDuration:"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/xctest/xcuicoordinate"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/xctest/xcuicoordinate"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
