{
  "abstract": [
    {
      "text": "A system resource that requires user authorization to access.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.xctest/documentation/XCTest"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.xctest/documentation/XCTest/XCUIProtectedResource"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@XCUIProtectedResource",
    "fragments": [
      {
        "kind": "keyword",
        "text": "enum"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "XCUIProtectedResource"
      }
    ],
    "modules": [
      {
        "name": "XCTest"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "XCUIProtectedResource"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.4",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.4",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.4",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.15.4",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.4",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "6.2",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Enumeration",
    "symbolKind": "enum",
    "title": "XCUIProtectedResource"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "enum"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "XCUIProtectedResource"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.xctest/documentation/XCTest": {
      "abstract": [
        {
          "text": "Create and run unit tests, performance tests, and UI tests for your Xcode project.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.xctest/documentation/XCTest",
      "kind": "symbol",
      "role": "collection",
      "title": "XCTest",
      "type": "topic",
      "url": "/documentation/xctest"
    },
    "doc://com.apple.xctest/documentation/XCTest/XCUIApplication/resetAuthorizationStatus(for:)": {
      "abstract": [
        {
          "text": "Resets the authorization status for a protected resource.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "resetAuthorizationStatus"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "for"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@XCUIProtectedResource",
          "text": "XCUIProtectedResource"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.xctest/documentation/XCTest/XCUIApplication/resetAuthorizationStatus(for:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "resetAuthorizationStatusForResource:"
        }
      ],
      "role": "symbol",
      "title": "resetAuthorizationStatus(for:)",
      "type": "topic",
      "url": "/documentation/xctest/xcuiapplication/resetauthorizationstatus(for:)"
    },
    "doc://com.apple.xctest/documentation/XCTest/XCUIProtectedResource": {
      "abstract": [
        {
          "text": "A system resource that requires user authorization to access.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "XCUIProtectedResource"
        }
      ],
      "identifier": "doc://com.apple.xctest/documentation/XCTest/XCUIProtectedResource",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "XCUIProtectedResource"
        }
      ],
      "role": "symbol",
      "title": "XCUIProtectedResource",
      "type": "topic",
      "url": "/documentation/xctest/xcuiprotectedresource"
    },
    "doc://com.apple.xctest/documentation/XCTest/XCUIProtectedResource/Equatable-Implementations": {
      "abstract": [],
      "identifier": "doc://com.apple.xctest/documentation/XCTest/XCUIProtectedResource/Equatable-Implementations",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Equatable Implementations",
      "type": "topic",
      "url": "/documentation/xctest/xcuiprotectedresource/equatable-implementations"
    },
    "doc://com.apple.xctest/documentation/XCTest/XCUIProtectedResource/RawRepresentable-Implementations": {
      "abstract": [],
      "identifier": "doc://com.apple.xctest/documentation/XCTest/XCUIProtectedResource/RawRepresentable-Implementations",
      "kind": "article",
      "role": "collectionGroup",
      "title": "RawRepresentable Implementations",
      "type": "topic",
      "url": "/documentation/xctest/xcuiprotectedresource/rawrepresentable-implementations"
    },
    "doc://com.apple.xctest/documentation/XCTest/XCUIProtectedResource/appleEvents": {
      "abstract": [
        {
          "text": "The protected resource case for the use of Apple Events.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "appleEvents"
        }
      ],
      "identifier": "doc://com.apple.xctest/documentation/XCTest/XCUIProtectedResource/appleEvents",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "XCUIProtectedResourceAppleEvents"
        }
      ],
      "role": "symbol",
      "title": "XCUIProtectedResource.appleEvents",
      "type": "topic",
      "url": "/documentation/xctest/xcuiprotectedresource/appleevents"
    },
    "doc://com.apple.xctest/documentation/XCTest/XCUIProtectedResource/bluetooth": {
      "abstract": [
        {
          "text": "The protected resource case for Bluetooth utilization.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "bluetooth"
        }
      ],
      "identifier": "doc://com.apple.xctest/documentation/XCTest/XCUIProtectedResource/bluetooth",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "XCUIProtectedResourceBluetooth"
        }
      ],
      "role": "symbol",
      "title": "XCUIProtectedResource.bluetooth",
      "type": "topic",
      "url": "/documentation/xctest/xcuiprotectedresource/bluetooth"
    },
    "doc://com.apple.xctest/documentation/XCTest/XCUIProtectedResource/calendar": {
      "abstract": [
        {
          "text": "The protected resource case for acces to Calendar data.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "calendar"
        }
      ],
      "identifier": "doc://com.apple.xctest/documentation/XCTest/XCUIProtectedResource/calendar",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "XCUIProtectedResourceCalendar"
        }
      ],
      "role": "symbol",
      "title": "XCUIProtectedResource.calendar",
      "type": "topic",
      "url": "/documentation/xctest/xcuiprotectedresource/calendar"
    },
    "doc://com.apple.xctest/documentation/XCTest/XCUIProtectedResource/camera": {
      "abstract": [
        {
          "text": "The protected resource case for access to the camera.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "camera"
        }
      ],
      "identifier": "doc://com.apple.xctest/documentation/XCTest/XCUIProtectedResource/camera",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "XCUIProtectedResourceCamera"
        }
      ],
      "role": "symbol",
      "title": "XCUIProtectedResource.camera",
      "type": "topic",
      "url": "/documentation/xctest/xcuiprotectedresource/camera"
    },
    "doc://com.apple.xctest/documentation/XCTest/XCUIProtectedResource/contacts": {
      "abstract": [
        {
          "text": "The protected resource case for access to Contacts.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "contacts"
        }
      ],
      "identifier": "doc://com.apple.xctest/documentation/XCTest/XCUIProtectedResource/contacts",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "XCUIProtectedResourceContacts"
        }
      ],
      "role": "symbol",
      "title": "XCUIProtectedResource.contacts",
      "type": "topic",
      "url": "/documentation/xctest/xcuiprotectedresource/contacts"
    },
    "doc://com.apple.xctest/documentation/XCTest/XCUIProtectedResource/focus": {
      "abstract": [
        {
          "text": "The protected resource case to see and share Focus status.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "focus"
        }
      ],
      "identifier": "doc://com.apple.xctest/documentation/XCTest/XCUIProtectedResource/focus",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "XCUIProtectedResourceFocus"
        }
      ],
      "role": "symbol",
      "title": "XCUIProtectedResource.focus",
      "type": "topic",
      "url": "/documentation/xctest/xcuiprotectedresource/focus"
    },
    "doc://com.apple.xctest/documentation/XCTest/XCUIProtectedResource/health": {
      "abstract": [
        {
          "text": "The protected resource case for access to Health data.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "health"
        }
      ],
      "identifier": "doc://com.apple.xctest/documentation/XCTest/XCUIProtectedResource/health",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "XCUIProtectedResourceHealth"
        }
      ],
      "role": "symbol",
      "title": "XCUIProtectedResource.health",
      "type": "topic",
      "url": "/documentation/xctest/xcuiprotectedresource/health"
    },
    "doc://com.apple.xctest/documentation/XCTest/XCUIProtectedResource/homeKit": {
      "abstract": [
        {
          "text": "The protected resource case for access to Home data.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "homeKit"
        }
      ],
      "identifier": "doc://com.apple.xctest/documentation/XCTest/XCUIProtectedResource/homeKit",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "XCUIProtectedResourceHomeKit"
        }
      ],
      "role": "symbol",
      "title": "XCUIProtectedResource.homeKit",
      "type": "topic",
      "url": "/documentation/xctest/xcuiprotectedresource/homekit"
    },
    "doc://com.apple.xctest/documentation/XCTest/XCUIProtectedResource/init(rawValue:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "?("
        },
        {
          "kind": "externalParam",
          "text": "rawValue"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.xctest/documentation/XCTest/XCUIProtectedResource/init(rawValue:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "init(rawValue:)",
      "type": "topic",
      "url": "/documentation/xctest/xcuiprotectedresource/init(rawvalue:)"
    },
    "doc://com.apple.xctest/documentation/XCTest/XCUIProtectedResource/keyboardNetwork": {
      "abstract": [
        {
          "text": "The protected resource case for access to the keyboard network.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "keyboardNetwork"
        }
      ],
      "identifier": "doc://com.apple.xctest/documentation/XCTest/XCUIProtectedResource/keyboardNetwork",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "XCUIProtectedResourceKeyboardNetwork"
        }
      ],
      "role": "symbol",
      "title": "XCUIProtectedResource.keyboardNetwork",
      "type": "topic",
      "url": "/documentation/xctest/xcuiprotectedresource/keyboardnetwork"
    },
    "doc://com.apple.xctest/documentation/XCTest/XCUIProtectedResource/localNetwork": {
      "abstract": [
        {
          "text": "The protected resource case for finding and communicating with devices on the local network.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "localNetwork"
        }
      ],
      "identifier": "doc://com.apple.xctest/documentation/XCTest/XCUIProtectedResource/localNetwork",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "XCUIProtectedResourceLocalNetwork"
        }
      ],
      "role": "symbol",
      "title": "XCUIProtectedResource.localNetwork",
      "type": "topic",
      "url": "/documentation/xctest/xcuiprotectedresource/localnetwork"
    },
    "doc://com.apple.xctest/documentation/XCTest/XCUIProtectedResource/location": {
      "abstract": [
        {
          "text": "The protected resource case for Location Services.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "location"
        }
      ],
      "identifier": "doc://com.apple.xctest/documentation/XCTest/XCUIProtectedResource/location",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "XCUIProtectedResourceLocation"
        }
      ],
      "role": "symbol",
      "title": "XCUIProtectedResource.location",
      "type": "topic",
      "url": "/documentation/xctest/xcuiprotectedresource/location"
    },
    "doc://com.apple.xctest/documentation/XCTest/XCUIProtectedResource/mediaLibrary": {
      "abstract": [
        {
          "text": "The protected resource case for access to the media library.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "mediaLibrary"
        }
      ],
      "identifier": "doc://com.apple.xctest/documentation/XCTest/XCUIProtectedResource/mediaLibrary",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "XCUIProtectedResourceMediaLibrary"
        }
      ],
      "role": "symbol",
      "title": "XCUIProtectedResource.mediaLibrary",
      "type": "topic",
      "url": "/documentation/xctest/xcuiprotectedresource/medialibrary"
    },
    "doc://com.apple.xctest/documentation/XCTest/XCUIProtectedResource/microphone": {
      "abstract": [
        {
          "text": "The protected resource case for access to the microphone.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "microphone"
        }
      ],
      "identifier": "doc://com.apple.xctest/documentation/XCTest/XCUIProtectedResource/microphone",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "XCUIProtectedResourceMicrophone"
        }
      ],
      "role": "symbol",
      "title": "XCUIProtectedResource.microphone",
      "type": "topic",
      "url": "/documentation/xctest/xcuiprotectedresource/microphone"
    },
    "doc://com.apple.xctest/documentation/XCTest/XCUIProtectedResource/networkVolumes": {
      "abstract": [
        {
          "text": "The protected resource case for access to network volumes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "networkVolumes"
        }
      ],
      "identifier": "doc://com.apple.xctest/documentation/XCTest/XCUIProtectedResource/networkVolumes",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "XCUIProtectedResourceNetworkVolumes"
        }
      ],
      "role": "symbol",
      "title": "XCUIProtectedResource.networkVolumes",
      "type": "topic",
      "url": "/documentation/xctest/xcuiprotectedresource/networkvolumes"
    },
    "doc://com.apple.xctest/documentation/XCTest/XCUIProtectedResource/photos": {
      "abstract": [
        {
          "text": "The protected resource case for access to Photos.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "photos"
        }
      ],
      "identifier": "doc://com.apple.xctest/documentation/XCTest/XCUIProtectedResource/photos",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "XCUIProtectedResourcePhotos"
        }
      ],
      "role": "symbol",
      "title": "XCUIProtectedResource.photos",
      "type": "topic",
      "url": "/documentation/xctest/xcuiprotectedresource/photos"
    },
    "doc://com.apple.xctest/documentation/XCTest/XCUIProtectedResource/reminders": {
      "abstract": [
        {
          "text": "The protected resource case for access to Reminders data.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "reminders"
        }
      ],
      "identifier": "doc://com.apple.xctest/documentation/XCTest/XCUIProtectedResource/reminders",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "XCUIProtectedResourceReminders"
        }
      ],
      "role": "symbol",
      "title": "XCUIProtectedResource.reminders",
      "type": "topic",
      "url": "/documentation/xctest/xcuiprotectedresource/reminders"
    },
    "doc://com.apple.xctest/documentation/XCTest/XCUIProtectedResource/removableVolumes": {
      "abstract": [
        {
          "text": "The protected resource case for access to removable volumes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "removableVolumes"
        }
      ],
      "identifier": "doc://com.apple.xctest/documentation/XCTest/XCUIProtectedResource/removableVolumes",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "XCUIProtectedResourceRemovableVolumes"
        }
      ],
      "role": "symbol",
      "title": "XCUIProtectedResource.removableVolumes",
      "type": "topic",
      "url": "/documentation/xctest/xcuiprotectedresource/removablevolumes"
    },
    "doc://com.apple.xctest/documentation/XCTest/XCUIProtectedResource/systemRootDirectory": {
      "abstract": [
        {
          "text": "The protected resource case for access to the system root directory.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "systemRootDirectory"
        }
      ],
      "identifier": "doc://com.apple.xctest/documentation/XCTest/XCUIProtectedResource/systemRootDirectory",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "XCUIProtectedResourceSystemRootDirectory"
        }
      ],
      "role": "symbol",
      "title": "XCUIProtectedResource.systemRootDirectory",
      "type": "topic",
      "url": "/documentation/xctest/xcuiprotectedresource/systemrootdirectory"
    },
    "doc://com.apple.xctest/documentation/XCTest/XCUIProtectedResource/userDesktopDirectory": {
      "abstract": [
        {
          "text": "The protected resource case for access to the Desktop directory.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "userDesktopDirectory"
        }
      ],
      "identifier": "doc://com.apple.xctest/documentation/XCTest/XCUIProtectedResource/userDesktopDirectory",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "XCUIProtectedResourceUserDesktopDirectory"
        }
      ],
      "role": "symbol",
      "title": "XCUIProtectedResource.userDesktopDirectory",
      "type": "topic",
      "url": "/documentation/xctest/xcuiprotectedresource/userdesktopdirectory"
    },
    "doc://com.apple.xctest/documentation/XCTest/XCUIProtectedResource/userDocumentsDirectory": {
      "abstract": [
        {
          "text": "The protected resource case for access to the Documents directory.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "userDocumentsDirectory"
        }
      ],
      "identifier": "doc://com.apple.xctest/documentation/XCTest/XCUIProtectedResource/userDocumentsDirectory",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "XCUIProtectedResourceUserDocumentsDirectory"
        }
      ],
      "role": "symbol",
      "title": "XCUIProtectedResource.userDocumentsDirectory",
      "type": "topic",
      "url": "/documentation/xctest/xcuiprotectedresource/userdocumentsdirectory"
    },
    "doc://com.apple.xctest/documentation/XCTest/XCUIProtectedResource/userDownloadsDirectory": {
      "abstract": [
        {
          "text": "The protected resource case for access to the Downloads directory.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "userDownloadsDirectory"
        }
      ],
      "identifier": "doc://com.apple.xctest/documentation/XCTest/XCUIProtectedResource/userDownloadsDirectory",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "XCUIProtectedResourceUserDownloadsDirectory"
        }
      ],
      "role": "symbol",
      "title": "XCUIProtectedResource.userDownloadsDirectory",
      "type": "topic",
      "url": "/documentation/xctest/xcuiprotectedresource/userdownloadsdirectory"
    },
    "doc://com.apple.xctest/documentation/XCTest/XCUIProtectedResource/userTracking": {
      "abstract": [
        {
          "text": "The protected resource case for access to tracking data.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "userTracking"
        }
      ],
      "identifier": "doc://com.apple.xctest/documentation/XCTest/XCUIProtectedResource/userTracking",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "XCUIProtectedResourceUserTracking"
        }
      ],
      "role": "symbol",
      "title": "XCUIProtectedResource.userTracking",
      "type": "topic",
      "url": "/documentation/xctest/xcuiprotectedresource/usertracking"
    },
    "doc://com.externally.resolved.symbol/s:SH": {
      "abstract": [
        {
          "text": "A type that can be hashed into a `Hasher` to produce an integer hash value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Hashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SQ",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SH",
      "kind": "symbol",
      "role": "symbol",
      "title": "Hashable",
      "type": "topic",
      "url": "/documentation/Swift/Hashable"
    },
    "doc://com.externally.resolved.symbol/s:SQ": {
      "abstract": [
        {
          "text": "A type that can be compared for value equality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SQ",
      "kind": "symbol",
      "role": "symbol",
      "title": "Equatable",
      "type": "topic",
      "url": "/documentation/Swift/Equatable"
    },
    "doc://com.externally.resolved.symbol/s:SY": {
      "abstract": [
        {
          "text": "A type that can be converted to and from an associated raw value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "RawRepresentable"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SY8RawValueQa",
          "text": "RawValue"
        },
        {
          "kind": "text",
          "text": ">"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SY",
      "kind": "symbol",
      "role": "symbol",
      "title": "RawRepresentable",
      "type": "topic",
      "url": "/documentation/Swift/RawRepresentable"
    },
    "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BitwiseCopyable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "BitwiseCopyable",
      "type": "topic",
      "url": "/documentation/Swift/BitwiseCopyable"
    },
    "doc://com.externally.resolved.symbol/s:s8SendableP": {
      "abstract": [
        {
          "text": "A thread-safe type whose values can be shared across arbitrary concurrent contexts without introducing a risk of data races.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Sendable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s8SendableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "Sendable",
      "type": "topic",
      "url": "/documentation/Swift/Sendable"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
        "doc://com.externally.resolved.symbol/s:SQ",
        "doc://com.externally.resolved.symbol/s:SH",
        "doc://com.externally.resolved.symbol/s:SY",
        "doc://com.externally.resolved.symbol/s:s8SendableP"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Resetting-Authorization-Status",
      "generated": true,
      "identifiers": [
        "doc://com.apple.xctest/documentation/XCTest/XCUIApplication/resetAuthorizationStatus(for:)"
      ],
      "title": "Resetting Authorization Status"
    }
  ],
  "topicSections": [
    {
      "anchor": "Protected-resources",
      "identifiers": [
        "doc://com.apple.xctest/documentation/XCTest/XCUIProtectedResource/location",
        "doc://com.apple.xctest/documentation/XCTest/XCUIProtectedResource/userTracking",
        "doc://com.apple.xctest/documentation/XCTest/XCUIProtectedResource/contacts",
        "doc://com.apple.xctest/documentation/XCTest/XCUIProtectedResource/calendar",
        "doc://com.apple.xctest/documentation/XCTest/XCUIProtectedResource/reminders",
        "doc://com.apple.xctest/documentation/XCTest/XCUIProtectedResource/photos",
        "doc://com.apple.xctest/documentation/XCTest/XCUIProtectedResource/bluetooth",
        "doc://com.apple.xctest/documentation/XCTest/XCUIProtectedResource/localNetwork",
        "doc://com.apple.xctest/documentation/XCTest/XCUIProtectedResource/microphone",
        "doc://com.apple.xctest/documentation/XCTest/XCUIProtectedResource/camera",
        "doc://com.apple.xctest/documentation/XCTest/XCUIProtectedResource/health",
        "doc://com.apple.xctest/documentation/XCTest/XCUIProtectedResource/homeKit",
        "doc://com.apple.xctest/documentation/XCTest/XCUIProtectedResource/mediaLibrary",
        "doc://com.apple.xctest/documentation/XCTest/XCUIProtectedResource/keyboardNetwork",
        "doc://com.apple.xctest/documentation/XCTest/XCUIProtectedResource/systemRootDirectory",
        "doc://com.apple.xctest/documentation/XCTest/XCUIProtectedResource/userDesktopDirectory",
        "doc://com.apple.xctest/documentation/XCTest/XCUIProtectedResource/userDocumentsDirectory",
        "doc://com.apple.xctest/documentation/XCTest/XCUIProtectedResource/userDownloadsDirectory",
        "doc://com.apple.xctest/documentation/XCTest/XCUIProtectedResource/focus",
        "doc://com.apple.xctest/documentation/XCTest/XCUIProtectedResource/removableVolumes",
        "doc://com.apple.xctest/documentation/XCTest/XCUIProtectedResource/networkVolumes",
        "doc://com.apple.xctest/documentation/XCTest/XCUIProtectedResource/appleEvents"
      ],
      "title": "Protected resources"
    },
    {
      "anchor": "Initializers",
      "generated": true,
      "identifiers": [
        "doc://com.apple.xctest/documentation/XCTest/XCUIProtectedResource/init(rawValue:)"
      ],
      "title": "Initializers"
    },
    {
      "anchor": "Default-Implementations",
      "generated": true,
      "identifiers": [
        "doc://com.apple.xctest/documentation/XCTest/XCUIProtectedResource/Equatable-Implementations",
        "doc://com.apple.xctest/documentation/XCTest/XCUIProtectedResource/RawRepresentable-Implementations"
      ],
      "title": "Default Implementations"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": null
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "XCUIProtectedResource"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "enum"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "XCUIProtectedResource"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "XCUIProtectedResource"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.xctest/documentation/XCTest"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Protected-resources",
              "identifiers": [
                "doc://com.apple.xctest/documentation/XCTest/XCUIProtectedResource/location",
                "doc://com.apple.xctest/documentation/XCTest/XCUIProtectedResource/userTracking",
                "doc://com.apple.xctest/documentation/XCTest/XCUIProtectedResource/contacts",
                "doc://com.apple.xctest/documentation/XCTest/XCUIProtectedResource/calendar",
                "doc://com.apple.xctest/documentation/XCTest/XCUIProtectedResource/reminders",
                "doc://com.apple.xctest/documentation/XCTest/XCUIProtectedResource/photos",
                "doc://com.apple.xctest/documentation/XCTest/XCUIProtectedResource/bluetooth",
                "doc://com.apple.xctest/documentation/XCTest/XCUIProtectedResource/localNetwork",
                "doc://com.apple.xctest/documentation/XCTest/XCUIProtectedResource/microphone",
                "doc://com.apple.xctest/documentation/XCTest/XCUIProtectedResource/camera",
                "doc://com.apple.xctest/documentation/XCTest/XCUIProtectedResource/health",
                "doc://com.apple.xctest/documentation/XCTest/XCUIProtectedResource/homeKit",
                "doc://com.apple.xctest/documentation/XCTest/XCUIProtectedResource/mediaLibrary",
                "doc://com.apple.xctest/documentation/XCTest/XCUIProtectedResource/keyboardNetwork",
                "doc://com.apple.xctest/documentation/XCTest/XCUIProtectedResource/systemRootDirectory",
                "doc://com.apple.xctest/documentation/XCTest/XCUIProtectedResource/userDesktopDirectory",
                "doc://com.apple.xctest/documentation/XCTest/XCUIProtectedResource/userDocumentsDirectory",
                "doc://com.apple.xctest/documentation/XCTest/XCUIProtectedResource/userDownloadsDirectory",
                "doc://com.apple.xctest/documentation/XCTest/XCUIProtectedResource/focus",
                "doc://com.apple.xctest/documentation/XCTest/XCUIProtectedResource/removableVolumes",
                "doc://com.apple.xctest/documentation/XCTest/XCUIProtectedResource/networkVolumes",
                "doc://com.apple.xctest/documentation/XCTest/XCUIProtectedResource/appleEvents"
              ],
              "title": "Protected resources"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Resetting-Authorization-Status",
              "generated": true,
              "identifiers": [
                "doc://com.apple.xctest/documentation/XCTest/XCUIApplication/resetAuthorizationStatus(for:)"
              ],
              "title": "Resetting Authorization Status"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "enum"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "XCUIProtectedResource"
                  },
                  {
                    "kind": "text",
                    "text": " : "
                  },
                  {
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@NSInteger",
                    "text": "NSInteger"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCUIProtectedResource~1networkVolumes/title",
          "value": "XCUIProtectedResourceNetworkVolumes"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCUIProtectedResource~1networkVolumes/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "XCUIProtectedResourceNetworkVolumes"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCUIProtectedResource~1focus/title",
          "value": "XCUIProtectedResourceFocus"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCUIProtectedResource~1focus/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "XCUIProtectedResourceFocus"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCUIProtectedResource~1mediaLibrary/title",
          "value": "XCUIProtectedResourceMediaLibrary"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCUIProtectedResource~1mediaLibrary/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "XCUIProtectedResourceMediaLibrary"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCUIProtectedResource~1location/title",
          "value": "XCUIProtectedResourceLocation"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCUIProtectedResource~1location/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "XCUIProtectedResourceLocation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCUIProtectedResource~1photos/title",
          "value": "XCUIProtectedResourcePhotos"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCUIProtectedResource~1photos/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "XCUIProtectedResourcePhotos"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCUIProtectedResource~1removableVolumes/title",
          "value": "XCUIProtectedResourceRemovableVolumes"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCUIProtectedResource~1removableVolumes/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "XCUIProtectedResourceRemovableVolumes"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCUIProtectedResource~1bluetooth/title",
          "value": "XCUIProtectedResourceBluetooth"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCUIProtectedResource~1bluetooth/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "XCUIProtectedResourceBluetooth"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCUIProtectedResource~1reminders/title",
          "value": "XCUIProtectedResourceReminders"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCUIProtectedResource~1reminders/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "XCUIProtectedResourceReminders"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCUIProtectedResource~1userTracking/title",
          "value": "XCUIProtectedResourceUserTracking"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCUIProtectedResource~1userTracking/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "XCUIProtectedResourceUserTracking"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCUIProtectedResource~1calendar/title",
          "value": "XCUIProtectedResourceCalendar"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCUIProtectedResource~1calendar/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "XCUIProtectedResourceCalendar"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCUIProtectedResource~1localNetwork/title",
          "value": "XCUIProtectedResourceLocalNetwork"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCUIProtectedResource~1localNetwork/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "XCUIProtectedResourceLocalNetwork"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCUIProtectedResource~1microphone/title",
          "value": "XCUIProtectedResourceMicrophone"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCUIProtectedResource~1microphone/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "XCUIProtectedResourceMicrophone"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCUIProtectedResource~1userDownloadsDirectory/title",
          "value": "XCUIProtectedResourceUserDownloadsDirectory"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCUIProtectedResource~1userDownloadsDirectory/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "XCUIProtectedResourceUserDownloadsDirectory"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCUIProtectedResource~1homeKit/title",
          "value": "XCUIProtectedResourceHomeKit"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCUIProtectedResource~1homeKit/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "XCUIProtectedResourceHomeKit"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCUIProtectedResource~1contacts/title",
          "value": "XCUIProtectedResourceContacts"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCUIProtectedResource~1contacts/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "XCUIProtectedResourceContacts"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCUIProtectedResource~1health/title",
          "value": "XCUIProtectedResourceHealth"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCUIProtectedResource~1health/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "XCUIProtectedResourceHealth"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCUIProtectedResource~1appleEvents/title",
          "value": "XCUIProtectedResourceAppleEvents"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCUIProtectedResource~1appleEvents/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "XCUIProtectedResourceAppleEvents"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCUIApplication~1resetAuthorizationStatus(for:)/title",
          "value": "resetAuthorizationStatusForResource:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCUIApplication~1resetAuthorizationStatus(for:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "resetAuthorizationStatusForResource:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCUIProtectedResource~1systemRootDirectory/title",
          "value": "XCUIProtectedResourceSystemRootDirectory"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCUIProtectedResource~1systemRootDirectory/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "XCUIProtectedResourceSystemRootDirectory"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCUIProtectedResource~1camera/title",
          "value": "XCUIProtectedResourceCamera"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCUIProtectedResource~1camera/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "XCUIProtectedResourceCamera"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCUIProtectedResource/title",
          "value": "XCUIProtectedResource"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCUIProtectedResource/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "XCUIProtectedResource"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCUIProtectedResource/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "XCUIProtectedResource"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCUIProtectedResource~1userDesktopDirectory/title",
          "value": "XCUIProtectedResourceUserDesktopDirectory"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCUIProtectedResource~1userDesktopDirectory/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "XCUIProtectedResourceUserDesktopDirectory"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCUIProtectedResource~1keyboardNetwork/title",
          "value": "XCUIProtectedResourceKeyboardNetwork"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCUIProtectedResource~1keyboardNetwork/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "XCUIProtectedResourceKeyboardNetwork"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCUIProtectedResource~1userDocumentsDirectory/title",
          "value": "XCUIProtectedResourceUserDocumentsDirectory"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCUIProtectedResource~1userDocumentsDirectory/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "XCUIProtectedResourceUserDocumentsDirectory"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/xctest/xcuiprotectedresource"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/xctest/xcuiprotectedresource"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
