{
  "abstract": [
    {
      "text": "A value that describes how fast a gesture moves across the screen, in pixels per second.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.xctest/documentation/XCTest"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.xctest/documentation/XCTest/XCUIGestureVelocity"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@T@XCUIGestureVelocity",
    "fragments": [
      {
        "kind": "keyword",
        "text": "struct"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "XCUIGestureVelocity"
      }
    ],
    "modules": [
      {
        "name": "XCTest"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "XCUIGestureVelocity"
      }
    ],
    "role": "symbol",
    "roleHeading": "Structure",
    "symbolKind": "struct",
    "title": "XCUIGestureVelocity"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "struct"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "XCUIGestureVelocity"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.xctest/documentation/XCTest": {
      "abstract": [
        {
          "text": "Create and run unit tests, performance tests, and UI tests for your Xcode project.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.xctest/documentation/XCTest",
      "kind": "symbol",
      "role": "collection",
      "title": "XCTest",
      "type": "topic",
      "url": "/documentation/xctest"
    },
    "doc://com.apple.xctest/documentation/XCTest/XCUIElement/pinch(withScale:velocity:)": {
      "abstract": [
        {
          "text": "Sends a pinching gesture with two touches.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "pinch"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "withScale"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:14CoreFoundation7CGFloatV",
          "text": "CGFloat"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "velocity"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:14CoreFoundation7CGFloatV",
          "text": "CGFloat"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.xctest/documentation/XCTest/XCUIElement/pinch(withScale:velocity:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "pinchWithScale:velocity:"
        }
      ],
      "role": "symbol",
      "title": "pinch(withScale:velocity:)",
      "type": "topic",
      "url": "/documentation/xctest/xcuielement/pinch(withscale:velocity:)"
    },
    "doc://com.apple.xctest/documentation/XCTest/XCUIElement/rotate(_:withVelocity:)": {
      "abstract": [
        {
          "text": "Sends a rotation gesture with two touches.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "rotate"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:14CoreFoundation7CGFloatV",
          "text": "CGFloat"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "withVelocity"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:14CoreFoundation7CGFloatV",
          "text": "CGFloat"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.xctest/documentation/XCTest/XCUIElement/rotate(_:withVelocity:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "rotate:withVelocity:"
        }
      ],
      "role": "symbol",
      "title": "rotate(_:withVelocity:)",
      "type": "topic",
      "url": "/documentation/xctest/xcuielement/rotate(_:withvelocity:)"
    },
    "doc://com.apple.xctest/documentation/XCTest/XCUIElement/swipeDown()": {
      "abstract": [
        {
          "text": "Sends a swipe-down gesture.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "swipeDown"
        },
        {
          "kind": "text",
          "text": "()"
        }
      ],
      "identifier": "doc://com.apple.xctest/documentation/XCTest/XCUIElement/swipeDown()",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "swipeDown"
        }
      ],
      "role": "symbol",
      "title": "swipeDown()",
      "type": "topic",
      "url": "/documentation/xctest/xcuielement/swipedown()"
    },
    "doc://com.apple.xctest/documentation/XCTest/XCUIElement/swipeDown(velocity:)": {
      "abstract": [
        {
          "text": "Sends a swipe-down gesture with a velocity you specify.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "swipeDown"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "velocity"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@XCUIGestureVelocity",
          "text": "XCUIGestureVelocity"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.xctest/documentation/XCTest/XCUIElement/swipeDown(velocity:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "swipeDownWithVelocity:"
        }
      ],
      "role": "symbol",
      "title": "swipeDown(velocity:)",
      "type": "topic",
      "url": "/documentation/xctest/xcuielement/swipedown(velocity:)"
    },
    "doc://com.apple.xctest/documentation/XCTest/XCUIElement/swipeLeft()": {
      "abstract": [
        {
          "text": "Sends a swipe-left gesture.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "swipeLeft"
        },
        {
          "kind": "text",
          "text": "()"
        }
      ],
      "identifier": "doc://com.apple.xctest/documentation/XCTest/XCUIElement/swipeLeft()",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "swipeLeft"
        }
      ],
      "role": "symbol",
      "title": "swipeLeft()",
      "type": "topic",
      "url": "/documentation/xctest/xcuielement/swipeleft()"
    },
    "doc://com.apple.xctest/documentation/XCTest/XCUIElement/swipeLeft(velocity:)": {
      "abstract": [
        {
          "text": "Sends a swipe-left gesture with a velocity you specify.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "swipeLeft"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "velocity"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@XCUIGestureVelocity",
          "text": "XCUIGestureVelocity"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.xctest/documentation/XCTest/XCUIElement/swipeLeft(velocity:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "swipeLeftWithVelocity:"
        }
      ],
      "role": "symbol",
      "title": "swipeLeft(velocity:)",
      "type": "topic",
      "url": "/documentation/xctest/xcuielement/swipeleft(velocity:)"
    },
    "doc://com.apple.xctest/documentation/XCTest/XCUIElement/swipeRight()": {
      "abstract": [
        {
          "text": "Sends a swipe-right gesture.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "swipeRight"
        },
        {
          "kind": "text",
          "text": "()"
        }
      ],
      "identifier": "doc://com.apple.xctest/documentation/XCTest/XCUIElement/swipeRight()",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "swipeRight"
        }
      ],
      "role": "symbol",
      "title": "swipeRight()",
      "type": "topic",
      "url": "/documentation/xctest/xcuielement/swiperight()"
    },
    "doc://com.apple.xctest/documentation/XCTest/XCUIElement/swipeRight(velocity:)": {
      "abstract": [
        {
          "text": "Sends a swipe-right gesture with a velocity you specify.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "swipeRight"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "velocity"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@XCUIGestureVelocity",
          "text": "XCUIGestureVelocity"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.xctest/documentation/XCTest/XCUIElement/swipeRight(velocity:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "swipeRightWithVelocity:"
        }
      ],
      "role": "symbol",
      "title": "swipeRight(velocity:)",
      "type": "topic",
      "url": "/documentation/xctest/xcuielement/swiperight(velocity:)"
    },
    "doc://com.apple.xctest/documentation/XCTest/XCUIElement/swipeUp()": {
      "abstract": [
        {
          "text": "Sends a swipe-up gesture.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "swipeUp"
        },
        {
          "kind": "text",
          "text": "()"
        }
      ],
      "identifier": "doc://com.apple.xctest/documentation/XCTest/XCUIElement/swipeUp()",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "swipeUp"
        }
      ],
      "role": "symbol",
      "title": "swipeUp()",
      "type": "topic",
      "url": "/documentation/xctest/xcuielement/swipeup()"
    },
    "doc://com.apple.xctest/documentation/XCTest/XCUIElement/swipeUp(velocity:)": {
      "abstract": [
        {
          "text": "Sends a swipe-up gesture with a velocity you specify.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "swipeUp"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "velocity"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@XCUIGestureVelocity",
          "text": "XCUIGestureVelocity"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.xctest/documentation/XCTest/XCUIElement/swipeUp(velocity:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "swipeUpWithVelocity:"
        }
      ],
      "role": "symbol",
      "title": "swipeUp(velocity:)",
      "type": "topic",
      "url": "/documentation/xctest/xcuielement/swipeup(velocity:)"
    },
    "doc://com.apple.xctest/documentation/XCTest/XCUIGestureVelocity": {
      "abstract": [
        {
          "text": "A value that describes how fast a gesture moves across the screen, in pixels per second.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "XCUIGestureVelocity"
        }
      ],
      "identifier": "doc://com.apple.xctest/documentation/XCTest/XCUIGestureVelocity",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "XCUIGestureVelocity"
        }
      ],
      "role": "symbol",
      "title": "XCUIGestureVelocity",
      "type": "topic",
      "url": "/documentation/xctest/xcuigesturevelocity"
    },
    "doc://com.apple.xctest/documentation/XCTest/XCUIGestureVelocity/Equatable-Implementations": {
      "abstract": [],
      "identifier": "doc://com.apple.xctest/documentation/XCTest/XCUIGestureVelocity/Equatable-Implementations",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Equatable Implementations",
      "type": "topic",
      "url": "/documentation/xctest/xcuigesturevelocity/equatable-implementations"
    },
    "doc://com.apple.xctest/documentation/XCTest/XCUIGestureVelocity/ExpressibleByFloatLiteral-Implementations": {
      "abstract": [],
      "identifier": "doc://com.apple.xctest/documentation/XCTest/XCUIGestureVelocity/ExpressibleByFloatLiteral-Implementations",
      "kind": "article",
      "role": "collectionGroup",
      "title": "ExpressibleByFloatLiteral Implementations",
      "type": "topic",
      "url": "/documentation/xctest/xcuigesturevelocity/expressiblebyfloatliteral-implementations"
    },
    "doc://com.apple.xctest/documentation/XCTest/XCUIGestureVelocity/ExpressibleByIntegerLiteral-Implementations": {
      "abstract": [],
      "identifier": "doc://com.apple.xctest/documentation/XCTest/XCUIGestureVelocity/ExpressibleByIntegerLiteral-Implementations",
      "kind": "article",
      "role": "collectionGroup",
      "title": "ExpressibleByIntegerLiteral Implementations",
      "type": "topic",
      "url": "/documentation/xctest/xcuigesturevelocity/expressiblebyintegerliteral-implementations"
    },
    "doc://com.apple.xctest/documentation/XCTest/XCUIGestureVelocity/FloatLiteralType": {
      "abstract": [
        {
          "text": "The native type that specifies the gesture velocity value, which differs on 32-bit and 64-bit architectures.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "FloatLiteralType"
        }
      ],
      "identifier": "doc://com.apple.xctest/documentation/XCTest/XCUIGestureVelocity/FloatLiteralType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "FloatLiteralType"
        }
      ],
      "role": "symbol",
      "title": "XCUIGestureVelocity.FloatLiteralType",
      "type": "topic",
      "url": "/documentation/xctest/xcuigesturevelocity/floatliteraltype"
    },
    "doc://com.apple.xctest/documentation/XCTest/XCUIGestureVelocity/IntegerLiteralType": {
      "abstract": [
        {
          "text": "A type that specifies a gesture velocity with an integer literal.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "IntegerLiteralType"
        }
      ],
      "identifier": "doc://com.apple.xctest/documentation/XCTest/XCUIGestureVelocity/IntegerLiteralType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "IntegerLiteralType"
        }
      ],
      "role": "symbol",
      "title": "XCUIGestureVelocity.IntegerLiteralType",
      "type": "topic",
      "url": "/documentation/xctest/xcuigesturevelocity/integerliteraltype"
    },
    "doc://com.apple.xctest/documentation/XCTest/XCUIGestureVelocity/_SwiftNewtypeWrapper-Implementations": {
      "abstract": [],
      "identifier": "doc://com.apple.xctest/documentation/XCTest/XCUIGestureVelocity/_SwiftNewtypeWrapper-Implementations",
      "kind": "article",
      "role": "collectionGroup",
      "title": "_SwiftNewtypeWrapper Implementations",
      "type": "topic",
      "url": "/documentation/xctest/xcuigesturevelocity/_swiftnewtypewrapper-implementations"
    },
    "doc://com.apple.xctest/documentation/XCTest/XCUIGestureVelocity/default": {
      "abstract": [
        {
          "text": "A value representing a default gesture velocity.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "`default`"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@XCUIGestureVelocity",
          "text": "XCUIGestureVelocity"
        }
      ],
      "identifier": "doc://com.apple.xctest/documentation/XCTest/XCUIGestureVelocity/default",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "XCUIGestureVelocityDefault"
        }
      ],
      "role": "symbol",
      "title": "default",
      "type": "topic",
      "url": "/documentation/xctest/xcuigesturevelocity/default"
    },
    "doc://com.apple.xctest/documentation/XCTest/XCUIGestureVelocity/fast": {
      "abstract": [
        {
          "text": "A value representing a fast gesture velocity.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "fast"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@XCUIGestureVelocity",
          "text": "XCUIGestureVelocity"
        }
      ],
      "identifier": "doc://com.apple.xctest/documentation/XCTest/XCUIGestureVelocity/fast",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "XCUIGestureVelocityFast"
        }
      ],
      "role": "symbol",
      "title": "fast",
      "type": "topic",
      "url": "/documentation/xctest/xcuigesturevelocity/fast"
    },
    "doc://com.apple.xctest/documentation/XCTest/XCUIGestureVelocity/init(_:)": {
      "abstract": [
        {
          "text": "Creates a gesture velocity, expressed as a float.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:14CoreFoundation7CGFloatV",
          "text": "CGFloat"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.xctest/documentation/XCTest/XCUIGestureVelocity/init(_:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "init(_:)",
      "type": "topic",
      "url": "/documentation/xctest/xcuigesturevelocity/init(_:)"
    },
    "doc://com.apple.xctest/documentation/XCTest/XCUIGestureVelocity/init(floatLiteral:)": {
      "abstract": [
        {
          "text": "Creates a gesture velocity with a float value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "floatLiteral"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@XCUIGestureVelocity",
          "text": "XCUIGestureVelocity"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:So19XCUIGestureVelocitya6XCTestE16FloatLiteralTypea",
          "text": "FloatLiteralType"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.xctest/documentation/XCTest/XCUIGestureVelocity/init(floatLiteral:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "init(floatLiteral:)",
      "type": "topic",
      "url": "/documentation/xctest/xcuigesturevelocity/init(floatliteral:)"
    },
    "doc://com.apple.xctest/documentation/XCTest/XCUIGestureVelocity/init(integerLiteral:)": {
      "abstract": [
        {
          "text": "Creates a gesture velocity with an integer value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "integerLiteral"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.xctest/documentation/XCTest/XCUIGestureVelocity/init(integerLiteral:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "init(integerLiteral:)",
      "type": "topic",
      "url": "/documentation/xctest/xcuigesturevelocity/init(integerliteral:)"
    },
    "doc://com.apple.xctest/documentation/XCTest/XCUIGestureVelocity/init(rawValue:)": {
      "abstract": [
        {
          "text": "Creates a gesture velocity with a raw value, expressed as a float.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "rawValue"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:14CoreFoundation7CGFloatV",
          "text": "CGFloat"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.xctest/documentation/XCTest/XCUIGestureVelocity/init(rawValue:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "init(rawValue:)",
      "type": "topic",
      "url": "/documentation/xctest/xcuigesturevelocity/init(rawvalue:)"
    },
    "doc://com.apple.xctest/documentation/XCTest/XCUIGestureVelocity/slow": {
      "abstract": [
        {
          "text": "A value representing a slow gesture velocity.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "slow"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@XCUIGestureVelocity",
          "text": "XCUIGestureVelocity"
        }
      ],
      "identifier": "doc://com.apple.xctest/documentation/XCTest/XCUIGestureVelocity/slow",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "XCUIGestureVelocitySlow"
        }
      ],
      "role": "symbol",
      "title": "slow",
      "type": "topic",
      "url": "/documentation/xctest/xcuigesturevelocity/slow"
    },
    "doc://com.externally.resolved.symbol/s:SH": {
      "abstract": [
        {
          "text": "A type that can be hashed into a `Hasher` to produce an integer hash value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Hashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SQ",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SH",
      "kind": "symbol",
      "role": "symbol",
      "title": "Hashable",
      "type": "topic",
      "url": "/documentation/Swift/Hashable"
    },
    "doc://com.externally.resolved.symbol/s:SQ": {
      "abstract": [
        {
          "text": "A type that can be compared for value equality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SQ",
      "kind": "symbol",
      "role": "symbol",
      "title": "Equatable",
      "type": "topic",
      "url": "/documentation/Swift/Equatable"
    },
    "doc://com.externally.resolved.symbol/s:SY": {
      "abstract": [
        {
          "text": "A type that can be converted to and from an associated raw value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "RawRepresentable"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SY8RawValueQa",
          "text": "RawValue"
        },
        {
          "kind": "text",
          "text": ">"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SY",
      "kind": "symbol",
      "role": "symbol",
      "title": "RawRepresentable",
      "type": "topic",
      "url": "/documentation/Swift/RawRepresentable"
    },
    "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BitwiseCopyable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "BitwiseCopyable",
      "type": "topic",
      "url": "/documentation/Swift/BitwiseCopyable"
    },
    "doc://com.externally.resolved.symbol/s:s25ExpressibleByFloatLiteralP": {
      "abstract": [
        {
          "text": "A type that can be initialized with a floating-point literal.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ExpressibleByFloatLiteral"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s25ExpressibleByFloatLiteralP",
      "kind": "symbol",
      "role": "symbol",
      "title": "ExpressibleByFloatLiteral",
      "type": "topic",
      "url": "/documentation/Swift/ExpressibleByFloatLiteral"
    },
    "doc://com.externally.resolved.symbol/s:s27ExpressibleByIntegerLiteralP": {
      "abstract": [
        {
          "text": "A type that can be initialized with an integer literal.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ExpressibleByIntegerLiteral"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s27ExpressibleByIntegerLiteralP",
      "kind": "symbol",
      "role": "symbol",
      "title": "ExpressibleByIntegerLiteral",
      "type": "topic",
      "url": "/documentation/Swift/ExpressibleByIntegerLiteral"
    },
    "doc://com.externally.resolved.symbol/s:s8CopyableP": {
      "abstract": [
        {
          "text": "A type whose values can be implicitly or explicitly copied.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Copyable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s8CopyableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "Copyable",
      "type": "topic",
      "url": "/documentation/Swift/Copyable"
    },
    "doc://com.externally.resolved.symbol/s:s8SendableP": {
      "abstract": [
        {
          "text": "A thread-safe type whose values can be shared across arbitrary concurrent contexts without introducing a risk of data races.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Sendable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s8SendableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "Sendable",
      "type": "topic",
      "url": "/documentation/Swift/Sendable"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
        "doc://com.externally.resolved.symbol/s:s8CopyableP",
        "doc://com.externally.resolved.symbol/s:SQ",
        "doc://com.externally.resolved.symbol/s:s25ExpressibleByFloatLiteralP",
        "doc://com.externally.resolved.symbol/s:s27ExpressibleByIntegerLiteralP",
        "doc://com.externally.resolved.symbol/s:SH",
        "doc://com.externally.resolved.symbol/s:SY",
        "doc://com.externally.resolved.symbol/s:s8SendableP"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Performing-Gestures",
      "generated": true,
      "identifiers": [
        "doc://com.apple.xctest/documentation/XCTest/XCUIElement/swipeLeft()",
        "doc://com.apple.xctest/documentation/XCTest/XCUIElement/swipeLeft(velocity:)",
        "doc://com.apple.xctest/documentation/XCTest/XCUIElement/swipeRight()",
        "doc://com.apple.xctest/documentation/XCTest/XCUIElement/swipeRight(velocity:)",
        "doc://com.apple.xctest/documentation/XCTest/XCUIElement/swipeUp()",
        "doc://com.apple.xctest/documentation/XCTest/XCUIElement/swipeUp(velocity:)",
        "doc://com.apple.xctest/documentation/XCTest/XCUIElement/swipeDown()",
        "doc://com.apple.xctest/documentation/XCTest/XCUIElement/swipeDown(velocity:)",
        "doc://com.apple.xctest/documentation/XCTest/XCUIElement/pinch(withScale:velocity:)",
        "doc://com.apple.xctest/documentation/XCTest/XCUIElement/rotate(_:withVelocity:)"
      ],
      "title": "Performing Gestures"
    }
  ],
  "topicSections": [
    {
      "anchor": "Creating-a-Gesture-Velocity",
      "identifiers": [
        "doc://com.apple.xctest/documentation/XCTest/XCUIGestureVelocity/init(_:)",
        "doc://com.apple.xctest/documentation/XCTest/XCUIGestureVelocity/init(floatLiteral:)",
        "doc://com.apple.xctest/documentation/XCTest/XCUIGestureVelocity/init(integerLiteral:)",
        "doc://com.apple.xctest/documentation/XCTest/XCUIGestureVelocity/init(rawValue:)",
        "doc://com.apple.xctest/documentation/XCTest/XCUIGestureVelocity/IntegerLiteralType",
        "doc://com.apple.xctest/documentation/XCTest/XCUIGestureVelocity/FloatLiteralType"
      ],
      "title": "Creating a Gesture Velocity"
    },
    {
      "anchor": "Using-Typical-Gesture-Velocities",
      "identifiers": [
        "doc://com.apple.xctest/documentation/XCTest/XCUIGestureVelocity/default",
        "doc://com.apple.xctest/documentation/XCTest/XCUIGestureVelocity/fast",
        "doc://com.apple.xctest/documentation/XCTest/XCUIGestureVelocity/slow"
      ],
      "title": "Using Typical Gesture Velocities"
    },
    {
      "anchor": "Default-Implementations",
      "generated": true,
      "identifiers": [
        "doc://com.apple.xctest/documentation/XCTest/XCUIGestureVelocity/Equatable-Implementations",
        "doc://com.apple.xctest/documentation/XCTest/XCUIGestureVelocity/ExpressibleByFloatLiteral-Implementations",
        "doc://com.apple.xctest/documentation/XCTest/XCUIGestureVelocity/ExpressibleByIntegerLiteral-Implementations",
        "doc://com.apple.xctest/documentation/XCTest/XCUIGestureVelocity/_SwiftNewtypeWrapper-Implementations"
      ],
      "title": "Default Implementations"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "add",
          "path": "/metadata/platforms",
          "value": null
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Type Alias"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "XCUIGestureVelocity"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "typealias"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "XCUIGestureVelocity"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "XCUIGestureVelocity"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.xctest/documentation/XCTest"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Using-Typical-Gesture-Velocities",
              "identifiers": [
                "doc://com.apple.xctest/documentation/XCTest/XCUIGestureVelocity/default",
                "doc://com.apple.xctest/documentation/XCTest/XCUIGestureVelocity/fast",
                "doc://com.apple.xctest/documentation/XCTest/XCUIGestureVelocity/slow"
              ],
              "title": "Using Typical Gesture Velocities"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Performing-Gestures",
              "generated": true,
              "identifiers": [
                "doc://com.apple.xctest/documentation/XCTest/XCUIElement/swipeLeft()",
                "doc://com.apple.xctest/documentation/XCTest/XCUIElement/swipeLeft(velocity:)",
                "doc://com.apple.xctest/documentation/XCTest/XCUIElement/swipeRight()",
                "doc://com.apple.xctest/documentation/XCTest/XCUIElement/swipeRight(velocity:)",
                "doc://com.apple.xctest/documentation/XCTest/XCUIElement/swipeUp()",
                "doc://com.apple.xctest/documentation/XCTest/XCUIElement/swipeUp(velocity:)",
                "doc://com.apple.xctest/documentation/XCTest/XCUIElement/swipeDown()",
                "doc://com.apple.xctest/documentation/XCTest/XCUIElement/swipeDown(velocity:)",
                "doc://com.apple.xctest/documentation/XCTest/XCUIElement/pinch(withScale:velocity:)",
                "doc://com.apple.xctest/documentation/XCTest/XCUIElement/rotate(_:withVelocity:)"
              ],
              "title": "Performing Gestures"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "typedef"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@CGFloat",
                    "text": "CGFloat"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "XCUIGestureVelocity"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCUIGestureVelocity~1fast/title",
          "value": "XCUIGestureVelocityFast"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCUIGestureVelocity~1fast/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "XCUIGestureVelocityFast"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCUIElement~1swipeLeft()/title",
          "value": "swipeLeft"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCUIElement~1swipeLeft()/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "swipeLeft"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCUIGestureVelocity~1default/title",
          "value": "XCUIGestureVelocityDefault"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCUIGestureVelocity~1default/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "XCUIGestureVelocityDefault"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCUIElement~1swipeRight(velocity:)/title",
          "value": "swipeRightWithVelocity:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCUIElement~1swipeRight(velocity:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "swipeRightWithVelocity:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCUIElement~1swipeDown()/title",
          "value": "swipeDown"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCUIElement~1swipeDown()/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "swipeDown"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCUIGestureVelocity/title",
          "value": "XCUIGestureVelocity"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCUIGestureVelocity/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "XCUIGestureVelocity"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCUIGestureVelocity/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "XCUIGestureVelocity"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCUIElement~1swipeUp()/title",
          "value": "swipeUp"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCUIElement~1swipeUp()/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "swipeUp"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCUIElement~1swipeLeft(velocity:)/title",
          "value": "swipeLeftWithVelocity:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCUIElement~1swipeLeft(velocity:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "swipeLeftWithVelocity:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCUIElement~1swipeUp(velocity:)/title",
          "value": "swipeUpWithVelocity:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCUIElement~1swipeUp(velocity:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "swipeUpWithVelocity:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCUIElement~1swipeDown(velocity:)/title",
          "value": "swipeDownWithVelocity:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCUIElement~1swipeDown(velocity:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "swipeDownWithVelocity:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCUIElement~1swipeRight()/title",
          "value": "swipeRight"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCUIElement~1swipeRight()/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "swipeRight"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCUIElement~1pinch(withScale:velocity:)/title",
          "value": "pinchWithScale:velocity:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCUIElement~1pinch(withScale:velocity:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "pinchWithScale:velocity:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCUIGestureVelocity~1slow/title",
          "value": "XCUIGestureVelocitySlow"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCUIGestureVelocity~1slow/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "XCUIGestureVelocitySlow"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCUIElement~1rotate(_:withVelocity:)/title",
          "value": "rotate:withVelocity:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCUIElement~1rotate(_:withVelocity:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "rotate:withVelocity:"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/xctest/xcuigesturevelocity"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/xctest/xcuigesturevelocity"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
