{
  "abstract": [
    {
      "text": "A proxy that can launch, monitor, and terminate a test application.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.xctest/documentation/XCTest"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.xctest/documentation/XCTest/XCUIApplication"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(cs)XCUIApplication",
    "fragments": [
      {
        "kind": "keyword",
        "text": "class"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "XCUIApplication"
      }
    ],
    "modules": [
      {
        "name": "XCTest"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "XCUIApplication"
      }
    ],
    "role": "symbol",
    "roleHeading": "Class",
    "symbolKind": "class",
    "title": "XCUIApplication"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "attribute",
              "text": "@"
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:ScM",
              "kind": "attribute",
              "preciseIdentifier": "s:ScM",
              "text": "MainActor"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "keyword",
              "text": "class"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "XCUIApplication"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "kind": "mentions",
      "mentions": [
        "doc://com.apple.xctest/documentation/XCTest/grouping-tests-into-substeps-with-activities"
      ]
    },
    {
      "content": [
        {
          "anchor": "overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Use this class to launch, monitor, and terminate your app in a UI test. Use ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.xctest/documentation/XCTest/XCUIApplication/wait(for:timeout:)",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " to launch your app and wait for it to reach an expected state before you check test conditions.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.xctest/documentation/XCTest": {
      "abstract": [
        {
          "text": "Create and run unit tests, performance tests, and UI tests for your Xcode project.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.xctest/documentation/XCTest",
      "kind": "symbol",
      "role": "collection",
      "title": "XCTest",
      "type": "topic",
      "url": "/documentation/xctest"
    },
    "doc://com.apple.xctest/documentation/XCTest/XCUIAccessibilityAuditIssue": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "XCUIAccessibilityAuditIssue"
        }
      ],
      "identifier": "doc://com.apple.xctest/documentation/XCTest/XCUIAccessibilityAuditIssue",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "XCUIAccessibilityAuditIssue"
        }
      ],
      "role": "symbol",
      "title": "XCUIAccessibilityAuditIssue",
      "type": "topic",
      "url": "/documentation/xctest/xcuiaccessibilityauditissue"
    },
    "doc://com.apple.xctest/documentation/XCTest/XCUIAccessibilityAuditType": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "XCUIAccessibilityAuditType"
        }
      ],
      "identifier": "doc://com.apple.xctest/documentation/XCTest/XCUIAccessibilityAuditType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "XCUIAccessibilityAuditType"
        }
      ],
      "role": "symbol",
      "title": "XCUIAccessibilityAuditType",
      "type": "topic",
      "url": "/documentation/xctest/xcuiaccessibilityaudittype"
    },
    "doc://com.apple.xctest/documentation/XCTest/XCUIApplication": {
      "abstract": [
        {
          "text": "A proxy that can launch, monitor, and terminate a test application.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "XCUIApplication"
        }
      ],
      "identifier": "doc://com.apple.xctest/documentation/XCTest/XCUIApplication",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "XCUIApplication"
        }
      ],
      "role": "symbol",
      "title": "XCUIApplication",
      "type": "topic",
      "url": "/documentation/xctest/xcuiapplication"
    },
    "doc://com.apple.xctest/documentation/XCTest/XCUIApplication/State-swift.enum": {
      "abstract": [
        {
          "text": "The possible states of an application during UI testing.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "State"
        }
      ],
      "identifier": "doc://com.apple.xctest/documentation/XCTest/XCUIApplication/State-swift.enum",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "State"
        }
      ],
      "role": "symbol",
      "title": "XCUIApplication.State",
      "type": "topic",
      "url": "/documentation/xctest/xcuiapplication/state-swift.enum"
    },
    "doc://com.apple.xctest/documentation/XCTest/XCUIApplication/activate()": {
      "abstract": [
        {
          "text": "Activates the application.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "activate"
        },
        {
          "kind": "text",
          "text": "()"
        }
      ],
      "identifier": "doc://com.apple.xctest/documentation/XCTest/XCUIApplication/activate()",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "activate"
        }
      ],
      "role": "symbol",
      "title": "activate()",
      "type": "topic",
      "url": "/documentation/xctest/xcuiapplication/activate()"
    },
    "doc://com.apple.xctest/documentation/XCTest/XCUIApplication/init()": {
      "abstract": [
        {
          "text": "Creates a proxy for the application as the ",
          "type": "text"
        },
        {
          "inlineContent": [
            {
              "text": "Target Application",
              "type": "text"
            }
          ],
          "type": "emphasis"
        },
        {
          "text": " in Xcode’s target settings.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "()"
        }
      ],
      "identifier": "doc://com.apple.xctest/documentation/XCTest/XCUIApplication/init()",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "init"
        }
      ],
      "role": "symbol",
      "title": "init()",
      "type": "topic",
      "url": "/documentation/xctest/xcuiapplication/init()"
    },
    "doc://com.apple.xctest/documentation/XCTest/XCUIApplication/init(bundleIdentifier:)": {
      "abstract": [
        {
          "text": "Creates a proxy for an application for the specified bundle identifier.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "bundleIdentifier"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.xctest/documentation/XCTest/XCUIApplication/init(bundleIdentifier:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "initWithBundleIdentifier:"
        }
      ],
      "role": "symbol",
      "title": "init(bundleIdentifier:)",
      "type": "topic",
      "url": "/documentation/xctest/xcuiapplication/init(bundleidentifier:)"
    },
    "doc://com.apple.xctest/documentation/XCTest/XCUIApplication/init(url:)": {
      "abstract": [
        {
          "text": "Creates a proxy for the application at the specified file system URL.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "url"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10Foundation3URLV",
          "text": "URL"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.xctest/documentation/XCTest/XCUIApplication/init(url:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "initWithURL:"
        }
      ],
      "role": "symbol",
      "title": "init(url:)",
      "type": "topic",
      "url": "/documentation/xctest/xcuiapplication/init(url:)"
    },
    "doc://com.apple.xctest/documentation/XCTest/XCUIApplication/launch()": {
      "abstract": [
        {
          "text": "Launches the application.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "launch"
        },
        {
          "kind": "text",
          "text": "()"
        }
      ],
      "identifier": "doc://com.apple.xctest/documentation/XCTest/XCUIApplication/launch()",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "launch"
        }
      ],
      "role": "symbol",
      "title": "launch()",
      "type": "topic",
      "url": "/documentation/xctest/xcuiapplication/launch()"
    },
    "doc://com.apple.xctest/documentation/XCTest/XCUIApplication/launchArguments": {
      "abstract": [
        {
          "text": "The arguments that pass to the application on launch.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "launchArguments"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": "]"
        }
      ],
      "identifier": "doc://com.apple.xctest/documentation/XCTest/XCUIApplication/launchArguments",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "launchArguments"
        }
      ],
      "role": "symbol",
      "title": "launchArguments",
      "type": "topic",
      "url": "/documentation/xctest/xcuiapplication/launcharguments"
    },
    "doc://com.apple.xctest/documentation/XCTest/XCUIApplication/launchEnvironment": {
      "abstract": [
        {
          "text": "The environment variables that pass to the application on launch.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "launchEnvironment"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": "]"
        }
      ],
      "identifier": "doc://com.apple.xctest/documentation/XCTest/XCUIApplication/launchEnvironment",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "launchEnvironment"
        }
      ],
      "role": "symbol",
      "title": "launchEnvironment",
      "type": "topic",
      "url": "/documentation/xctest/xcuiapplication/launchenvironment"
    },
    "doc://com.apple.xctest/documentation/XCTest/XCUIApplication/new": {
      "abstract": [
        {
          "text": "Creates a proxy for the application specified as the “Target Application” in Xcode’s target settings.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "+ "
        },
        {
          "kind": "identifier",
          "text": "new"
        }
      ],
      "identifier": "doc://com.apple.xctest/documentation/XCTest/XCUIApplication/new",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "new"
        }
      ],
      "role": "symbol",
      "title": "new",
      "type": "topic",
      "url": "/documentation/xctest/xcuiapplication/new"
    },
    "doc://com.apple.xctest/documentation/XCTest/XCUIApplication/open(_:)": {
      "abstract": [
        {
          "text": "Launch the application by URL.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "open"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10Foundation3URLV",
          "text": "URL"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.xctest/documentation/XCTest/XCUIApplication/open(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "openURL:"
        }
      ],
      "role": "symbol",
      "title": "open(_:)",
      "type": "topic",
      "url": "/documentation/xctest/xcuiapplication/open(_:)"
    },
    "doc://com.apple.xctest/documentation/XCTest/XCUIApplication/performAccessibilityAudit(for:_:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "performAccessibilityAudit"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "for"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@XCUIAccessibilityAuditType",
          "text": "XCUIAccessibilityAuditType"
        },
        {
          "kind": "text",
          "text": ", (("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)XCUIAccessibilityAuditIssue",
          "text": "XCUIAccessibilityAuditIssue"
        },
        {
          "kind": "text",
          "text": ") "
        },
        {
          "kind": "keyword",
          "text": "throws"
        },
        {
          "kind": "text",
          "text": " -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        },
        {
          "kind": "text",
          "text": ")?) "
        },
        {
          "kind": "keyword",
          "text": "throws"
        }
      ],
      "identifier": "doc://com.apple.xctest/documentation/XCTest/XCUIApplication/performAccessibilityAudit(for:_:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "performAccessibilityAudit(for:_:)",
      "type": "topic",
      "url": "/documentation/xctest/xcuiapplication/performaccessibilityaudit(for:_:)"
    },
    "doc://com.apple.xctest/documentation/XCTest/XCUIApplication/performAccessibilityAuditWithAuditTypes:issueHandler:error:": {
      "abstract": [],
      "fragments": [
        {
          "kind": "text",
          "text": "- "
        },
        {
          "kind": "identifier",
          "text": "performAccessibilityAuditWithAuditTypes:issueHandler:error:"
        }
      ],
      "identifier": "doc://com.apple.xctest/documentation/XCTest/XCUIApplication/performAccessibilityAuditWithAuditTypes:issueHandler:error:",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "performAccessibilityAuditWithAuditTypes:issueHandler:error:"
        }
      ],
      "role": "symbol",
      "title": "performAccessibilityAuditWithAuditTypes:issueHandler:error:",
      "type": "topic",
      "url": "/documentation/xctest/xcuiapplication/performaccessibilityauditwithaudittypes:issuehandler:error:"
    },
    "doc://com.apple.xctest/documentation/XCTest/XCUIApplication/resetAuthorizationStatus(for:)": {
      "abstract": [
        {
          "text": "Resets the authorization status for a protected resource.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "resetAuthorizationStatus"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "for"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@XCUIProtectedResource",
          "text": "XCUIProtectedResource"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.xctest/documentation/XCTest/XCUIApplication/resetAuthorizationStatus(for:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "resetAuthorizationStatusForResource:"
        }
      ],
      "role": "symbol",
      "title": "resetAuthorizationStatus(for:)",
      "type": "topic",
      "url": "/documentation/xctest/xcuiapplication/resetauthorizationstatus(for:)"
    },
    "doc://com.apple.xctest/documentation/XCTest/XCUIApplication/state-swift.property": {
      "abstract": [
        {
          "text": "The most recent state of the application.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "state"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)XCUIApplication",
          "text": "XCUIApplication"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@XCUIApplicationState",
          "text": "State"
        }
      ],
      "identifier": "doc://com.apple.xctest/documentation/XCTest/XCUIApplication/state-swift.property",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "state"
        }
      ],
      "role": "symbol",
      "title": "state",
      "type": "topic",
      "url": "/documentation/xctest/xcuiapplication/state-swift.property"
    },
    "doc://com.apple.xctest/documentation/XCTest/XCUIApplication/terminate()": {
      "abstract": [
        {
          "text": "Terminates any running instance of the application.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "terminate"
        },
        {
          "kind": "text",
          "text": "()"
        }
      ],
      "identifier": "doc://com.apple.xctest/documentation/XCTest/XCUIApplication/terminate()",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "terminate"
        }
      ],
      "role": "symbol",
      "title": "terminate()",
      "type": "topic",
      "url": "/documentation/xctest/xcuiapplication/terminate()"
    },
    "doc://com.apple.xctest/documentation/XCTest/XCUIApplication/wait(for:timeout:)": {
      "abstract": [
        {
          "text": "Waits for the application to reach the specified state or timeout.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "wait"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "for"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)XCUIApplication",
          "text": "XCUIApplication"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@XCUIApplicationState",
          "text": "State"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "timeout"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSTimeInterval",
          "text": "TimeInterval"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.xctest/documentation/XCTest/XCUIApplication/wait(for:timeout:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "waitForState:timeout:"
        }
      ],
      "role": "symbol",
      "title": "wait(for:timeout:)",
      "type": "topic",
      "url": "/documentation/xctest/xcuiapplication/wait(for:timeout:)"
    },
    "doc://com.apple.xctest/documentation/XCTest/XCUIElement": {
      "abstract": [
        {
          "text": "A UI element in an application.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "XCUIElement"
        }
      ],
      "identifier": "doc://com.apple.xctest/documentation/XCTest/XCUIElement",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "XCUIElement"
        }
      ],
      "role": "symbol",
      "title": "XCUIElement",
      "type": "topic",
      "url": "/documentation/xctest/xcuielement"
    },
    "doc://com.apple.xctest/documentation/XCTest/XCUIElementAttributes": {
      "abstract": [
        {
          "text": "Attributes exposed by UI elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "XCUIElementAttributes"
        }
      ],
      "identifier": "doc://com.apple.xctest/documentation/XCTest/XCUIElementAttributes",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "XCUIElementAttributes"
        }
      ],
      "role": "symbol",
      "title": "XCUIElementAttributes",
      "type": "topic",
      "url": "/documentation/xctest/xcuielementattributes"
    },
    "doc://com.apple.xctest/documentation/XCTest/XCUIElementSnapshotProviding": {
      "abstract": [
        {
          "text": "A method to capture a snapshot of an element’s attributes and descendant user interface hierarchy.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "XCUIElementSnapshotProviding"
        }
      ],
      "identifier": "doc://com.apple.xctest/documentation/XCTest/XCUIElementSnapshotProviding",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "XCUIElementSnapshotProviding"
        }
      ],
      "role": "symbol",
      "title": "XCUIElementSnapshotProviding",
      "type": "topic",
      "url": "/documentation/xctest/xcuielementsnapshotproviding"
    },
    "doc://com.apple.xctest/documentation/XCTest/XCUIElementTypeQueryProvider": {
      "abstract": [
        {
          "text": "A type that provides ready-made queries for locating descendant UI elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "XCUIElementTypeQueryProvider"
        }
      ],
      "identifier": "doc://com.apple.xctest/documentation/XCTest/XCUIElementTypeQueryProvider",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "XCUIElementTypeQueryProvider"
        }
      ],
      "role": "symbol",
      "title": "XCUIElementTypeQueryProvider",
      "type": "topic",
      "url": "/documentation/xctest/xcuielementtypequeryprovider"
    },
    "doc://com.apple.xctest/documentation/XCTest/XCUIProtectedResource": {
      "abstract": [
        {
          "text": "A system resource that requires user authorization to access.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "XCUIProtectedResource"
        }
      ],
      "identifier": "doc://com.apple.xctest/documentation/XCTest/XCUIProtectedResource",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "XCUIProtectedResource"
        }
      ],
      "role": "symbol",
      "title": "XCUIProtectedResource",
      "type": "topic",
      "url": "/documentation/xctest/xcuiprotectedresource"
    },
    "doc://com.apple.xctest/documentation/XCTest/XCUIScreenshotProviding": {
      "abstract": [
        {
          "text": "A type that can provide a screenshot of its current UI state.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "XCUIScreenshotProviding"
        }
      ],
      "identifier": "doc://com.apple.xctest/documentation/XCTest/XCUIScreenshotProviding",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "XCUIScreenshotProviding"
        }
      ],
      "role": "symbol",
      "title": "XCUIScreenshotProviding",
      "type": "topic",
      "url": "/documentation/xctest/xcuiscreenshotproviding"
    },
    "doc://com.apple.xctest/documentation/XCTest/grouping-tests-into-substeps-with-activities": {
      "abstract": [
        {
          "text": "Simplify test reports by creating activities that organize substeps within complex test methods.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.xctest/documentation/XCTest/grouping-tests-into-substeps-with-activities",
      "kind": "article",
      "role": "article",
      "title": "Grouping Tests into Substeps with Activities",
      "type": "topic",
      "url": "/documentation/xctest/grouping-tests-into-substeps-with-activities"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)NSObject": {
      "abstract": [
        {
          "text": "The group of methods that are fundamental to all Objective-C objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "protocol "
        },
        {
          "kind": "identifier",
          "text": "NSObjectProtocol"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSObject",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSObjectProtocol",
      "type": "topic",
      "url": "/documentation/objectivec/nsobjectprotocol"
    },
    "doc://com.externally.resolved.symbol/s:SH": {
      "abstract": [
        {
          "text": "A type that can be hashed into a `Hasher` to produce an integer hash value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Hashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SQ",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SH",
      "kind": "symbol",
      "role": "symbol",
      "title": "Hashable",
      "type": "topic",
      "url": "/documentation/Swift/Hashable"
    },
    "doc://com.externally.resolved.symbol/s:SQ": {
      "abstract": [
        {
          "text": "A type that can be compared for value equality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SQ",
      "kind": "symbol",
      "role": "symbol",
      "title": "Equatable",
      "type": "topic",
      "url": "/documentation/Swift/Equatable"
    },
    "doc://com.externally.resolved.symbol/s:ScM": {
      "abstract": [
        {
          "text": "A singleton actor whose executor is equivalent to the main dispatch queue.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@globalActor"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "final"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "actor"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MainActor"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:ScM",
      "kind": "symbol",
      "role": "symbol",
      "title": "MainActor",
      "type": "topic",
      "url": "/documentation/Swift/MainActor"
    },
    "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP": {
      "abstract": [
        {
          "text": "A type with a customized textual representation.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CustomStringConvertible"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CustomStringConvertible",
      "type": "topic",
      "url": "/documentation/Swift/CustomStringConvertible"
    },
    "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP": {
      "abstract": [
        {
          "text": "A type with a customized textual representation suitable for debugging purposes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CustomDebugStringConvertible"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CustomDebugStringConvertible",
      "type": "topic",
      "url": "/documentation/Swift/CustomDebugStringConvertible"
    },
    "doc://com.externally.resolved.symbol/s:s7CVarArgP": {
      "abstract": [
        {
          "text": "A type whose instances can be encoded, and appropriately passed, as elements of a C `va_list`.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CVarArg"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s7CVarArgP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CVarArg",
      "type": "topic",
      "url": "/documentation/Swift/CVarArg"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.apple.xctest/documentation/XCTest/XCUIElement"
      ],
      "kind": "relationships",
      "title": "Inherits From",
      "type": "inheritsFrom"
    },
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:s7CVarArgP",
        "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP",
        "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP",
        "doc://com.externally.resolved.symbol/s:SQ",
        "doc://com.externally.resolved.symbol/s:SH",
        "doc://com.externally.resolved.symbol/c:objc(pl)NSObject",
        "doc://com.apple.xctest/documentation/XCTest/XCUIElementAttributes",
        "doc://com.apple.xctest/documentation/XCTest/XCUIElementSnapshotProviding",
        "doc://com.apple.xctest/documentation/XCTest/XCUIElementTypeQueryProvider",
        "doc://com.apple.xctest/documentation/XCTest/XCUIScreenshotProviding"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "topicSections": [
    {
      "anchor": "Creating-an-Application-Proxy",
      "identifiers": [
        "doc://com.apple.xctest/documentation/XCTest/XCUIApplication/init()",
        "doc://com.apple.xctest/documentation/XCTest/XCUIApplication/init(bundleIdentifier:)",
        "doc://com.apple.xctest/documentation/XCTest/XCUIApplication/init(url:)"
      ],
      "title": "Creating an Application Proxy"
    },
    {
      "anchor": "Launching-the-Application",
      "identifiers": [
        "doc://com.apple.xctest/documentation/XCTest/XCUIApplication/launch()",
        "doc://com.apple.xctest/documentation/XCTest/XCUIApplication/launchArguments",
        "doc://com.apple.xctest/documentation/XCTest/XCUIApplication/launchEnvironment",
        "doc://com.apple.xctest/documentation/XCTest/XCUIApplication/open(_:)"
      ],
      "title": "Launching the Application"
    },
    {
      "anchor": "Activating-the-Application",
      "identifiers": [
        "doc://com.apple.xctest/documentation/XCTest/XCUIApplication/activate()"
      ],
      "title": "Activating the Application"
    },
    {
      "anchor": "Terminating-the-Application",
      "identifiers": [
        "doc://com.apple.xctest/documentation/XCTest/XCUIApplication/terminate()"
      ],
      "title": "Terminating the Application"
    },
    {
      "anchor": "Determining-Application-State",
      "identifiers": [
        "doc://com.apple.xctest/documentation/XCTest/XCUIApplication/state-swift.property",
        "doc://com.apple.xctest/documentation/XCTest/XCUIApplication/State-swift.enum"
      ],
      "title": "Determining Application State"
    },
    {
      "anchor": "Waiting-for-an-Application-State",
      "identifiers": [
        "doc://com.apple.xctest/documentation/XCTest/XCUIApplication/wait(for:timeout:)"
      ],
      "title": "Waiting for an Application State"
    },
    {
      "abstract": [
        {
          "text": "Reset authorization status for protected resources, like Contacts, Camera, and Photos.",
          "type": "text"
        }
      ],
      "anchor": "Resetting-Authorization-Status",
      "identifiers": [
        "doc://com.apple.xctest/documentation/XCTest/XCUIApplication/resetAuthorizationStatus(for:)",
        "doc://com.apple.xctest/documentation/XCTest/XCUIProtectedResource"
      ],
      "title": "Resetting Authorization Status"
    },
    {
      "anchor": "Performing-an-Accessibility-Audit",
      "identifiers": [
        "doc://com.apple.xctest/documentation/XCTest/XCUIApplication/performAccessibilityAudit(for:_:)",
        "doc://com.apple.xctest/documentation/XCTest/XCUIAccessibilityAuditType",
        "doc://com.apple.xctest/documentation/XCTest/XCUIAccessibilityAuditIssue"
      ],
      "title": "Performing an Accessibility Audit"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "add",
          "path": "/metadata/platforms",
          "value": null
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Class"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "XCUIApplication"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "class"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "XCUIApplication"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "XCUIApplication"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.xctest/documentation/XCTest"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Creating-an-Application-Proxy",
              "identifiers": [
                "doc://com.apple.xctest/documentation/XCTest/XCUIApplication/init()",
                "doc://com.apple.xctest/documentation/XCTest/XCUIApplication/new",
                "doc://com.apple.xctest/documentation/XCTest/XCUIApplication/init(bundleIdentifier:)",
                "doc://com.apple.xctest/documentation/XCTest/XCUIApplication/init(url:)"
              ],
              "title": "Creating an Application Proxy"
            },
            {
              "anchor": "Launching-the-Application",
              "identifiers": [
                "doc://com.apple.xctest/documentation/XCTest/XCUIApplication/launch()",
                "doc://com.apple.xctest/documentation/XCTest/XCUIApplication/launchArguments",
                "doc://com.apple.xctest/documentation/XCTest/XCUIApplication/launchEnvironment",
                "doc://com.apple.xctest/documentation/XCTest/XCUIApplication/open(_:)"
              ],
              "title": "Launching the Application"
            },
            {
              "anchor": "Activating-the-Application",
              "identifiers": [
                "doc://com.apple.xctest/documentation/XCTest/XCUIApplication/activate()"
              ],
              "title": "Activating the Application"
            },
            {
              "anchor": "Terminating-the-Application",
              "identifiers": [
                "doc://com.apple.xctest/documentation/XCTest/XCUIApplication/terminate()"
              ],
              "title": "Terminating the Application"
            },
            {
              "anchor": "Determining-Application-State",
              "identifiers": [
                "doc://com.apple.xctest/documentation/XCTest/XCUIApplication/state-swift.property",
                "doc://com.apple.xctest/documentation/XCTest/XCUIApplication/State-swift.enum"
              ],
              "title": "Determining Application State"
            },
            {
              "anchor": "Waiting-for-an-Application-State",
              "identifiers": [
                "doc://com.apple.xctest/documentation/XCTest/XCUIApplication/wait(for:timeout:)"
              ],
              "title": "Waiting for an Application State"
            },
            {
              "abstract": [
                {
                  "text": "Reset authorization status for protected resources, like Contacts, Camera, and Photos.",
                  "type": "text"
                }
              ],
              "anchor": "Resetting-Authorization-Status",
              "identifiers": [
                "doc://com.apple.xctest/documentation/XCTest/XCUIApplication/resetAuthorizationStatus(for:)",
                "doc://com.apple.xctest/documentation/XCTest/XCUIProtectedResource"
              ],
              "title": "Resetting Authorization Status"
            },
            {
              "anchor": "Performing-an-Accessibility-Audit",
              "identifiers": [
                "doc://com.apple.xctest/documentation/XCTest/XCUIApplication/performAccessibilityAuditWithAuditTypes:issueHandler:error:",
                "doc://com.apple.xctest/documentation/XCTest/XCUIAccessibilityAuditType",
                "doc://com.apple.xctest/documentation/XCTest/XCUIAccessibilityAuditIssue"
              ],
              "title": "Performing an Accessibility Audit"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": [
            {
              "identifiers": [
                "doc://com.apple.xctest/documentation/XCTest/XCUIElement"
              ],
              "kind": "relationships",
              "title": "Inherits From",
              "type": "inheritsFrom"
            }
          ]
        },
        {
          "op": "add",
          "path": "/seeAlsoSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "@interface"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "XCUIApplication"
                  },
                  {
                    "kind": "text",
                    "text": " : "
                  },
                  {
                    "identifier": "doc://com.apple.xctest/documentation/XCTest/XCUIElement",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(cs)XCUIElement",
                    "text": "XCUIElement"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCUIProtectedResource/title",
          "value": "XCUIProtectedResource"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCUIProtectedResource/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "XCUIProtectedResource"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCUIProtectedResource/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "XCUIProtectedResource"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCUIApplication~1init()/title",
          "value": "init"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCUIApplication~1init()/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "init"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCUIApplication~1init(url:)/title",
          "value": "initWithURL:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCUIApplication~1init(url:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "initWithURL:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCUIApplication~1init(bundleIdentifier:)/title",
          "value": "initWithBundleIdentifier:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCUIApplication~1init(bundleIdentifier:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "initWithBundleIdentifier:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCUIElement/title",
          "value": "XCUIElement"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCUIElement/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "XCUIElement"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCUIElement/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "XCUIElement"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCUIScreenshotProviding/title",
          "value": "XCUIScreenshotProviding"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCUIScreenshotProviding/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "XCUIScreenshotProviding"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCUIScreenshotProviding/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "XCUIScreenshotProviding"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCUIApplication/title",
          "value": "XCUIApplication"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCUIApplication/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "XCUIApplication"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCUIApplication/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "XCUIApplication"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:objc(pl)NSObject/title",
          "value": "NSObject"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCUIAccessibilityAuditType/title",
          "value": "XCUIAccessibilityAuditType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCUIAccessibilityAuditType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "XCUIAccessibilityAuditType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCUIAccessibilityAuditType/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "XCUIAccessibilityAuditType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCUIAccessibilityAuditIssue/title",
          "value": "XCUIAccessibilityAuditIssue"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCUIAccessibilityAuditIssue/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "XCUIAccessibilityAuditIssue"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCUIAccessibilityAuditIssue/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "XCUIAccessibilityAuditIssue"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCUIApplication~1launchArguments/title",
          "value": "launchArguments"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCUIApplication~1launchArguments/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "launchArguments"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCUIApplication~1resetAuthorizationStatus(for:)/title",
          "value": "resetAuthorizationStatusForResource:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCUIApplication~1resetAuthorizationStatus(for:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "resetAuthorizationStatusForResource:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCUIApplication~1terminate()/title",
          "value": "terminate"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCUIApplication~1terminate()/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "terminate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCUIApplication~1activate()/title",
          "value": "activate"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCUIApplication~1activate()/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "activate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCUIElementAttributes/title",
          "value": "XCUIElementAttributes"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCUIElementAttributes/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "XCUIElementAttributes"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCUIElementAttributes/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "XCUIElementAttributes"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCUIApplication~1launch()/title",
          "value": "launch"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCUIApplication~1launch()/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "launch"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCUIApplication~1State-swift.enum/title",
          "value": "XCUIApplicationState"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCUIApplication~1State-swift.enum/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "XCUIApplicationState"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCUIApplication~1State-swift.enum/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "XCUIApplicationState"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCUIElementTypeQueryProvider/title",
          "value": "XCUIElementTypeQueryProvider"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCUIElementTypeQueryProvider/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "XCUIElementTypeQueryProvider"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCUIElementTypeQueryProvider/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "XCUIElementTypeQueryProvider"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCUIApplication~1state-swift.property/title",
          "value": "state"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCUIApplication~1state-swift.property/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "state"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCUIElementSnapshotProviding/title",
          "value": "XCUIElementSnapshotProviding"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCUIElementSnapshotProviding/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "XCUIElementSnapshotProviding"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCUIElementSnapshotProviding/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "XCUIElementSnapshotProviding"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCUIApplication~1wait(for:timeout:)/title",
          "value": "waitForState:timeout:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCUIApplication~1wait(for:timeout:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "waitForState:timeout:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCUIApplication~1launchEnvironment/title",
          "value": "launchEnvironment"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCUIApplication~1launchEnvironment/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "launchEnvironment"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCUIApplication~1open(_:)/title",
          "value": "openURL:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCUIApplication~1open(_:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "openURL:"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/xctest/xcuiapplication"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/xctest/xcuiapplication"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
