{
  "abstract": [
    {
      "text": "Attributes exposed by UI elements.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.xctest/documentation/XCTest"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.xctest/documentation/XCTest/XCUIElementAttributes"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(pl)XCUIElementAttributes",
    "fragments": [
      {
        "kind": "keyword",
        "text": "protocol"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "XCUIElementAttributes"
      }
    ],
    "modules": [
      {
        "name": "XCTest"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "XCUIElementAttributes"
      }
    ],
    "role": "symbol",
    "roleHeading": "Protocol",
    "symbolKind": "protocol",
    "title": "XCUIElementAttributes"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "attribute",
              "text": "@"
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:ScM",
              "kind": "attribute",
              "preciseIdentifier": "s:ScM",
              "text": "MainActor"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "keyword",
              "text": "protocol"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "XCUIElementAttributes"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "The ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.xctest/documentation/XCTest/XCUIElementAttributes",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " protocol adds attribute-related functionality to the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.xctest/documentation/XCTest/XCUIElement",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " class. Access these properties on an instance of ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.xctest/documentation/XCTest/XCUIElement",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " to query the current state of the UI element’s attributes.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "",
                  "type": "text"
                },
                {
                  "text": " ",
                  "type": "text"
                },
                {
                  "text": "The attributes provided by this protocol represent data exposed to the Accessibility system, and are available during query matching.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "Note",
          "style": "note",
          "type": "aside"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.xctest/documentation/XCTest": {
      "abstract": [
        {
          "text": "Create and run unit tests, performance tests, and UI tests for your Xcode project.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.xctest/documentation/XCTest",
      "kind": "symbol",
      "role": "collection",
      "title": "XCTest",
      "type": "topic",
      "url": "/documentation/xctest"
    },
    "doc://com.apple.xctest/documentation/XCTest/XCUIApplication": {
      "abstract": [
        {
          "text": "A proxy that can launch, monitor, and terminate a test application.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "XCUIApplication"
        }
      ],
      "identifier": "doc://com.apple.xctest/documentation/XCTest/XCUIApplication",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "XCUIApplication"
        }
      ],
      "role": "symbol",
      "title": "XCUIApplication",
      "type": "topic",
      "url": "/documentation/xctest/xcuiapplication"
    },
    "doc://com.apple.xctest/documentation/XCTest/XCUICoordinate": {
      "abstract": [
        {
          "text": "A location on screen relative to some UI element.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "XCUICoordinate"
        }
      ],
      "identifier": "doc://com.apple.xctest/documentation/XCTest/XCUICoordinate",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "XCUICoordinate"
        }
      ],
      "role": "symbol",
      "title": "XCUICoordinate",
      "type": "topic",
      "url": "/documentation/xctest/xcuicoordinate"
    },
    "doc://com.apple.xctest/documentation/XCTest/XCUIElement": {
      "abstract": [
        {
          "text": "A UI element in an application.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "XCUIElement"
        }
      ],
      "identifier": "doc://com.apple.xctest/documentation/XCTest/XCUIElement",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "XCUIElement"
        }
      ],
      "role": "symbol",
      "title": "XCUIElement",
      "type": "topic",
      "url": "/documentation/xctest/xcuielement"
    },
    "doc://com.apple.xctest/documentation/XCTest/XCUIElement/ElementType": {
      "abstract": [
        {
          "text": "The types of UI element that you find, inspect, and interact with in a UI test.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ElementType"
        }
      ],
      "identifier": "doc://com.apple.xctest/documentation/XCTest/XCUIElement/ElementType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ElementType"
        }
      ],
      "role": "symbol",
      "title": "XCUIElement.ElementType",
      "type": "topic",
      "url": "/documentation/xctest/xcuielement/elementtype"
    },
    "doc://com.apple.xctest/documentation/XCTest/XCUIElement/SizeClass": {
      "abstract": [
        {
          "text": "The user interface size classes you can inspect in a UI test.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SizeClass"
        }
      ],
      "identifier": "doc://com.apple.xctest/documentation/XCTest/XCUIElement/SizeClass",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SizeClass"
        }
      ],
      "role": "symbol",
      "title": "XCUIElement.SizeClass",
      "type": "topic",
      "url": "/documentation/xctest/xcuielement/sizeclass"
    },
    "doc://com.apple.xctest/documentation/XCTest/XCUIElementAttributes": {
      "abstract": [
        {
          "text": "Attributes exposed by UI elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "XCUIElementAttributes"
        }
      ],
      "identifier": "doc://com.apple.xctest/documentation/XCTest/XCUIElementAttributes",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "XCUIElementAttributes"
        }
      ],
      "role": "symbol",
      "title": "XCUIElementAttributes",
      "type": "topic",
      "url": "/documentation/xctest/xcuielementattributes"
    },
    "doc://com.apple.xctest/documentation/XCTest/XCUIElementAttributes/elementType": {
      "abstract": [
        {
          "text": "The type of the element.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "elementType"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)XCUIElement",
          "text": "XCUIElement"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@XCUIElementType",
          "text": "ElementType"
        }
      ],
      "identifier": "doc://com.apple.xctest/documentation/XCTest/XCUIElementAttributes/elementType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "elementType"
        }
      ],
      "required": true,
      "role": "symbol",
      "title": "elementType",
      "type": "topic",
      "url": "/documentation/xctest/xcuielementattributes/elementtype"
    },
    "doc://com.apple.xctest/documentation/XCTest/XCUIElementAttributes/frame": {
      "abstract": [
        {
          "text": "The frame of the element in the screen coordinate space.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "frame"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@CGRect",
          "text": "CGRect"
        }
      ],
      "identifier": "doc://com.apple.xctest/documentation/XCTest/XCUIElementAttributes/frame",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "frame"
        }
      ],
      "required": true,
      "role": "symbol",
      "title": "frame",
      "type": "topic",
      "url": "/documentation/xctest/xcuielementattributes/frame"
    },
    "doc://com.apple.xctest/documentation/XCTest/XCUIElementAttributes/hasFocus": {
      "abstract": [
        {
          "text": "Whether or not the element has UI focus.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "hasFocus"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.xctest/documentation/XCTest/XCUIElementAttributes/hasFocus",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "hasFocus"
        }
      ],
      "required": true,
      "role": "symbol",
      "title": "hasFocus",
      "type": "topic",
      "url": "/documentation/xctest/xcuielementattributes/hasfocus"
    },
    "doc://com.apple.xctest/documentation/XCTest/XCUIElementAttributes/horizontalSizeClass": {
      "abstract": [
        {
          "text": "The horizontal size class of the element.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "horizontalSizeClass"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)XCUIElement",
          "text": "XCUIElement"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@XCUIUserInterfaceSizeClass",
          "text": "SizeClass"
        }
      ],
      "identifier": "doc://com.apple.xctest/documentation/XCTest/XCUIElementAttributes/horizontalSizeClass",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "horizontalSizeClass"
        }
      ],
      "required": true,
      "role": "symbol",
      "title": "horizontalSizeClass",
      "type": "topic",
      "url": "/documentation/xctest/xcuielementattributes/horizontalsizeclass"
    },
    "doc://com.apple.xctest/documentation/XCTest/XCUIElementAttributes/identifier": {
      "abstract": [
        {
          "text": "The element’s accessibility identifier.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "identifier"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.xctest/documentation/XCTest/XCUIElementAttributes/identifier",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "identifier"
        }
      ],
      "required": true,
      "role": "symbol",
      "title": "identifier",
      "type": "topic",
      "url": "/documentation/xctest/xcuielementattributes/identifier"
    },
    "doc://com.apple.xctest/documentation/XCTest/XCUIElementAttributes/isEnabled": {
      "abstract": [
        {
          "text": "Whether or not the element is enabled for user interaction.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "isEnabled"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.xctest/documentation/XCTest/XCUIElementAttributes/isEnabled",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "enabled"
        }
      ],
      "required": true,
      "role": "symbol",
      "title": "isEnabled",
      "type": "topic",
      "url": "/documentation/xctest/xcuielementattributes/isenabled"
    },
    "doc://com.apple.xctest/documentation/XCTest/XCUIElementAttributes/isSelected": {
      "abstract": [
        {
          "text": "Whether or not the element is selected.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "isSelected"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.xctest/documentation/XCTest/XCUIElementAttributes/isSelected",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "selected"
        }
      ],
      "required": true,
      "role": "symbol",
      "title": "isSelected",
      "type": "topic",
      "url": "/documentation/xctest/xcuielementattributes/isselected"
    },
    "doc://com.apple.xctest/documentation/XCTest/XCUIElementAttributes/label": {
      "abstract": [
        {
          "text": "The label attribute of the element.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "label"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.xctest/documentation/XCTest/XCUIElementAttributes/label",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "label"
        }
      ],
      "required": true,
      "role": "symbol",
      "title": "label",
      "type": "topic",
      "url": "/documentation/xctest/xcuielementattributes/label"
    },
    "doc://com.apple.xctest/documentation/XCTest/XCUIElementAttributes/placeholderValue": {
      "abstract": [
        {
          "text": "The value that is displayed when the element has no value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "placeholderValue"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.xctest/documentation/XCTest/XCUIElementAttributes/placeholderValue",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "placeholderValue"
        }
      ],
      "required": true,
      "role": "symbol",
      "title": "placeholderValue",
      "type": "topic",
      "url": "/documentation/xctest/xcuielementattributes/placeholdervalue"
    },
    "doc://com.apple.xctest/documentation/XCTest/XCUIElementAttributes/title": {
      "abstract": [
        {
          "text": "The title attribute of the element.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "title"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.xctest/documentation/XCTest/XCUIElementAttributes/title",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "title"
        }
      ],
      "required": true,
      "role": "symbol",
      "title": "title",
      "type": "topic",
      "url": "/documentation/xctest/xcuielementattributes/title"
    },
    "doc://com.apple.xctest/documentation/XCTest/XCUIElementAttributes/value": {
      "abstract": [
        {
          "text": "The raw value attribute of the element.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "value"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "keyword",
          "text": "Any"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.xctest/documentation/XCTest/XCUIElementAttributes/value",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "value"
        }
      ],
      "required": true,
      "role": "symbol",
      "title": "value",
      "type": "topic",
      "url": "/documentation/xctest/xcuielementattributes/value"
    },
    "doc://com.apple.xctest/documentation/XCTest/XCUIElementAttributes/verticalSizeClass": {
      "abstract": [
        {
          "text": "The vertical size class of the element.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "verticalSizeClass"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)XCUIElement",
          "text": "XCUIElement"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@XCUIUserInterfaceSizeClass",
          "text": "SizeClass"
        }
      ],
      "identifier": "doc://com.apple.xctest/documentation/XCTest/XCUIElementAttributes/verticalSizeClass",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "verticalSizeClass"
        }
      ],
      "required": true,
      "role": "symbol",
      "title": "verticalSizeClass",
      "type": "topic",
      "url": "/documentation/xctest/xcuielementattributes/verticalsizeclass"
    },
    "doc://com.apple.xctest/documentation/XCTest/XCUIElementSnapshot": {
      "abstract": [
        {
          "text": "A set of attributes to express a snapshot of an element’s attributes and descendant user interface hierarchy.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "XCUIElementSnapshot"
        }
      ],
      "identifier": "doc://com.apple.xctest/documentation/XCTest/XCUIElementSnapshot",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "XCUIElementSnapshot"
        }
      ],
      "role": "symbol",
      "title": "XCUIElementSnapshot",
      "type": "topic",
      "url": "/documentation/xctest/xcuielementsnapshot"
    },
    "doc://com.apple.xctest/documentation/XCTest/XCUIElementSnapshotProviding": {
      "abstract": [
        {
          "text": "A method to capture a snapshot of an element’s attributes and descendant user interface hierarchy.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "XCUIElementSnapshotProviding"
        }
      ],
      "identifier": "doc://com.apple.xctest/documentation/XCTest/XCUIElementSnapshotProviding",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "XCUIElementSnapshotProviding"
        }
      ],
      "role": "symbol",
      "title": "XCUIElementSnapshotProviding",
      "type": "topic",
      "url": "/documentation/xctest/xcuielementsnapshotproviding"
    },
    "doc://com.externally.resolved.symbol/s:ScM": {
      "abstract": [
        {
          "text": "A singleton actor whose executor is equivalent to the main dispatch queue.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@globalActor"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "final"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "actor"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MainActor"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:ScM",
      "kind": "symbol",
      "role": "symbol",
      "title": "MainActor",
      "type": "topic",
      "url": "/documentation/Swift/MainActor"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.apple.xctest/documentation/XCTest/XCUIElementSnapshot"
      ],
      "kind": "relationships",
      "title": "Inherited By",
      "type": "inheritedBy"
    },
    {
      "identifiers": [
        "doc://com.apple.xctest/documentation/XCTest/XCUIApplication",
        "doc://com.apple.xctest/documentation/XCTest/XCUIElement"
      ],
      "kind": "relationships",
      "title": "Conforming Types",
      "type": "conformingTypes"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "UI-Elements",
      "generated": true,
      "identifiers": [
        "doc://com.apple.xctest/documentation/XCTest/XCUIElement",
        "doc://com.apple.xctest/documentation/XCTest/XCUIElementSnapshot",
        "doc://com.apple.xctest/documentation/XCTest/XCUIElementSnapshotProviding",
        "doc://com.apple.xctest/documentation/XCTest/XCUICoordinate"
      ],
      "title": "UI Elements"
    }
  ],
  "topicSections": [
    {
      "anchor": "Identity",
      "identifiers": [
        "doc://com.apple.xctest/documentation/XCTest/XCUIElementAttributes/identifier",
        "doc://com.apple.xctest/documentation/XCTest/XCUIElementAttributes/elementType",
        "doc://com.apple.xctest/documentation/XCTest/XCUIElement/ElementType"
      ],
      "title": "Identity"
    },
    {
      "anchor": "Value",
      "identifiers": [
        "doc://com.apple.xctest/documentation/XCTest/XCUIElementAttributes/value",
        "doc://com.apple.xctest/documentation/XCTest/XCUIElementAttributes/placeholderValue",
        "doc://com.apple.xctest/documentation/XCTest/XCUIElementAttributes/title",
        "doc://com.apple.xctest/documentation/XCTest/XCUIElementAttributes/label"
      ],
      "title": "Value"
    },
    {
      "anchor": "Interaction-State",
      "identifiers": [
        "doc://com.apple.xctest/documentation/XCTest/XCUIElementAttributes/hasFocus",
        "doc://com.apple.xctest/documentation/XCTest/XCUIElementAttributes/isEnabled",
        "doc://com.apple.xctest/documentation/XCTest/XCUIElementAttributes/isSelected"
      ],
      "title": "Interaction State"
    },
    {
      "anchor": "Size",
      "identifiers": [
        "doc://com.apple.xctest/documentation/XCTest/XCUIElementAttributes/frame",
        "doc://com.apple.xctest/documentation/XCTest/XCUIElementAttributes/horizontalSizeClass",
        "doc://com.apple.xctest/documentation/XCTest/XCUIElementAttributes/verticalSizeClass",
        "doc://com.apple.xctest/documentation/XCTest/XCUIElement/SizeClass"
      ],
      "title": "Size"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "add",
          "path": "/metadata/platforms",
          "value": null
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Protocol"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "XCUIElementAttributes"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "protocol"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "XCUIElementAttributes"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "XCUIElementAttributes"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.xctest/documentation/XCTest"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Identity",
              "identifiers": [
                "doc://com.apple.xctest/documentation/XCTest/XCUIElementAttributes/identifier",
                "doc://com.apple.xctest/documentation/XCTest/XCUIElementAttributes/elementType",
                "doc://com.apple.xctest/documentation/XCTest/XCUIElement/ElementType"
              ],
              "title": "Identity"
            },
            {
              "anchor": "Value",
              "identifiers": [
                "doc://com.apple.xctest/documentation/XCTest/XCUIElementAttributes/value",
                "doc://com.apple.xctest/documentation/XCTest/XCUIElementAttributes/placeholderValue",
                "doc://com.apple.xctest/documentation/XCTest/XCUIElementAttributes/title",
                "doc://com.apple.xctest/documentation/XCTest/XCUIElementAttributes/label"
              ],
              "title": "Value"
            },
            {
              "anchor": "Interaction-State",
              "identifiers": [
                "doc://com.apple.xctest/documentation/XCTest/XCUIElementAttributes/hasFocus",
                "doc://com.apple.xctest/documentation/XCTest/XCUIElementAttributes/isEnabled",
                "doc://com.apple.xctest/documentation/XCTest/XCUIElementAttributes/isSelected"
              ],
              "title": "Interaction State"
            },
            {
              "anchor": "Size",
              "identifiers": [
                "doc://com.apple.xctest/documentation/XCTest/XCUIElementAttributes/frame",
                "doc://com.apple.xctest/documentation/XCTest/XCUIElementAttributes/horizontalSizeClass",
                "doc://com.apple.xctest/documentation/XCTest/XCUIElementAttributes/verticalSizeClass",
                "doc://com.apple.xctest/documentation/XCTest/XCUIElement/SizeClass"
              ],
              "title": "Size"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": [
            {
              "identifiers": [
                "doc://com.apple.xctest/documentation/XCTest/XCUIElementSnapshot"
              ],
              "kind": "relationships",
              "title": "Inherited By",
              "type": "inheritedBy"
            },
            {
              "identifiers": [
                "doc://com.apple.xctest/documentation/XCTest/XCUIElement"
              ],
              "kind": "relationships",
              "title": "Conforming Types",
              "type": "conformingTypes"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "UI-Elements",
              "generated": true,
              "identifiers": [
                "doc://com.apple.xctest/documentation/XCTest/XCUIElement",
                "doc://com.apple.xctest/documentation/XCTest/XCUIElementSnapshot",
                "doc://com.apple.xctest/documentation/XCTest/XCUIElementSnapshotProviding",
                "doc://com.apple.xctest/documentation/XCTest/XCUICoordinate"
              ],
              "title": "UI Elements"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "@protocol"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "XCUIElementAttributes"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCUIElementAttributes~1verticalSizeClass/title",
          "value": "verticalSizeClass"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCUIElementAttributes~1verticalSizeClass/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "verticalSizeClass"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCUIElementAttributes~1placeholderValue/title",
          "value": "placeholderValue"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCUIElementAttributes~1placeholderValue/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "placeholderValue"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCUIApplication/title",
          "value": "XCUIApplication"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCUIApplication/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "XCUIApplication"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCUIApplication/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "XCUIApplication"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCUIElementAttributes~1label/title",
          "value": "label"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCUIElementAttributes~1label/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "label"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCUIElement/title",
          "value": "XCUIElement"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCUIElement/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "XCUIElement"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCUIElement/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "XCUIElement"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCUICoordinate/title",
          "value": "XCUICoordinate"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCUICoordinate/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "XCUICoordinate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCUICoordinate/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "XCUICoordinate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCUIElementAttributes~1hasFocus/title",
          "value": "hasFocus"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCUIElementAttributes~1hasFocus/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "hasFocus"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCUIElementAttributes~1frame/title",
          "value": "frame"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCUIElementAttributes~1frame/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "frame"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCUIElementSnapshotProviding/title",
          "value": "XCUIElementSnapshotProviding"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCUIElementSnapshotProviding/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "XCUIElementSnapshotProviding"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCUIElementSnapshotProviding/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "XCUIElementSnapshotProviding"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCUIElementAttributes~1title/title",
          "value": "title"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCUIElementAttributes~1title/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "title"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCUIElementAttributes~1identifier/title",
          "value": "identifier"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCUIElementAttributes~1identifier/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "identifier"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCUIElementAttributes~1isSelected/title",
          "value": "selected"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCUIElementAttributes~1isSelected/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "selected"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCUIElementAttributes~1elementType/title",
          "value": "elementType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCUIElementAttributes~1elementType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "elementType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCUIElementAttributes~1horizontalSizeClass/title",
          "value": "horizontalSizeClass"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCUIElementAttributes~1horizontalSizeClass/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "horizontalSizeClass"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCUIElement~1ElementType/title",
          "value": "XCUIElementType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCUIElement~1ElementType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "XCUIElementType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCUIElement~1ElementType/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "XCUIElementType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCUIElementAttributes/title",
          "value": "XCUIElementAttributes"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCUIElementAttributes/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "XCUIElementAttributes"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCUIElementAttributes/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "XCUIElementAttributes"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCUIElementSnapshot/title",
          "value": "XCUIElementSnapshot"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCUIElementSnapshot/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "XCUIElementSnapshot"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCUIElementSnapshot/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "XCUIElementSnapshot"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCUIElementAttributes~1isEnabled/title",
          "value": "enabled"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCUIElementAttributes~1isEnabled/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "enabled"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCUIElementAttributes~1value/title",
          "value": "value"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCUIElementAttributes~1value/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "value"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCUIElement~1SizeClass/title",
          "value": "XCUIUserInterfaceSizeClass"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCUIElement~1SizeClass/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "XCUIUserInterfaceSizeClass"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCUIElement~1SizeClass/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "XCUIUserInterfaceSizeClass"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/xctest/xcuielementattributes"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/xctest/xcuielementattributes"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
