{
  "abstract": [
    {
      "text": "Automatically enables a marquee effect.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.sharedwithyou/documentation/SharedWithYou",
        "doc://com.apple.sharedwithyou/documentation/SharedWithYou/SWAttributionView"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "occ",
    "url": "doc://com.apple.sharedwithyou/documentation/SharedWithYou/SWAttributionView/enablesMarquee"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(cs)SWAttributionView(py)enablesMarquee",
    "fragments": [
      {
        "kind": "identifier",
        "text": "enablesMarquee"
      }
    ],
    "modules": [
      {
        "name": "Shared With You"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "enablesMarquee"
      }
    ],
    "platforms": [],
    "role": "symbol",
    "roleHeading": "Instance Property",
    "symbolKind": "property",
    "title": "enablesMarquee"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "occ"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "@property"
            },
            {
              "kind": "text",
              "text": " ("
            },
            {
              "kind": "keyword",
              "text": "nonatomic"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "kind": "keyword",
              "text": "assign"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "kind": "keyword",
              "text": "readwrite"
            },
            {
              "kind": "text",
              "text": ") "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/c:@T@BOOL",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@BOOL",
              "text": "BOOL"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "enablesMarquee"
            },
            {
              "kind": "text",
              "text": ";"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Automatically enables a marquee effect if the text contents extend past the bounds of the view.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.sharedwithyou/documentation/SharedWithYou": {
      "abstract": [
        {
          "text": "Surface shared content and collaborate in your app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.sharedwithyou/documentation/SharedWithYou",
      "kind": "symbol",
      "role": "collection",
      "title": "Shared With You",
      "type": "topic",
      "url": "/documentation/sharedwithyou"
    },
    "doc://com.apple.sharedwithyou/documentation/SharedWithYou/SWAttributionView": {
      "abstract": [
        {
          "text": "A view that displays the sender who shares a highlight and provides related actions.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SWAttributionView"
        }
      ],
      "identifier": "doc://com.apple.sharedwithyou/documentation/SharedWithYou/SWAttributionView",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SWAttributionView"
        }
      ],
      "role": "symbol",
      "title": "SWAttributionView",
      "type": "topic",
      "url": "/documentation/sharedwithyou/swattributionview"
    },
    "doc://com.apple.sharedwithyou/documentation/SharedWithYou/SWAttributionView/backgroundStyle-swift.property": {
      "abstract": [
        {
          "text": "The background style of the child view that contains names and avatars.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "backgroundStyle"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)SWAttributionView",
          "text": "SWAttributionView"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@SWAttributionViewBackgroundStyle",
          "text": "BackgroundStyle"
        }
      ],
      "identifier": "doc://com.apple.sharedwithyou/documentation/SharedWithYou/SWAttributionView/backgroundStyle-swift.property",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "backgroundStyle"
        }
      ],
      "role": "symbol",
      "title": "backgroundStyle",
      "type": "topic",
      "url": "/documentation/sharedwithyou/swattributionview/backgroundstyle-swift.property"
    },
    "doc://com.apple.sharedwithyou/documentation/SharedWithYou/SWAttributionView/displayContext-swift.property": {
      "abstract": [
        {
          "text": "The context for the content the system displays with this view.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "displayContext"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)SWAttributionView",
          "text": "SWAttributionView"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@SWAttributionViewDisplayContext",
          "text": "DisplayContext"
        }
      ],
      "identifier": "doc://com.apple.sharedwithyou/documentation/SharedWithYou/SWAttributionView/displayContext-swift.property",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "displayContext"
        }
      ],
      "role": "symbol",
      "title": "displayContext",
      "type": "topic",
      "url": "/documentation/sharedwithyou/swattributionview/displaycontext-swift.property"
    },
    "doc://com.apple.sharedwithyou/documentation/SharedWithYou/SWAttributionView/enablesMarquee": {
      "abstract": [
        {
          "text": "Automatically enables a marquee effect.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "enablesMarquee"
        }
      ],
      "identifier": "doc://com.apple.sharedwithyou/documentation/SharedWithYou/SWAttributionView/enablesMarquee",
      "kind": "symbol",
      "role": "symbol",
      "title": "enablesMarquee",
      "type": "topic",
      "url": "/documentation/sharedwithyou/swattributionview/enablesmarquee"
    },
    "doc://com.apple.sharedwithyou/documentation/SharedWithYou/SWAttributionView/highlight": {
      "abstract": [
        {
          "text": "The highlight you use to display this attribution.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "highlight"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)SWHighlight",
          "text": "SWHighlight"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.sharedwithyou/documentation/SharedWithYou/SWAttributionView/highlight",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "highlight"
        }
      ],
      "role": "symbol",
      "title": "highlight",
      "type": "topic",
      "url": "/documentation/sharedwithyou/swattributionview/highlight"
    },
    "doc://com.apple.sharedwithyou/documentation/SharedWithYou/SWAttributionView/highlightMenu": {
      "abstract": [
        {
          "text": "A menu with a list of system actions specific to this hightlight.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "highlightMenu"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UIMenu",
          "text": "UIMenu"
        }
      ],
      "identifier": "doc://com.apple.sharedwithyou/documentation/SharedWithYou/SWAttributionView/highlightMenu",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "highlightMenu"
        }
      ],
      "role": "symbol",
      "title": "highlightMenu",
      "type": "topic",
      "url": "/documentation/sharedwithyou/swattributionview/highlightmenu"
    },
    "doc://com.apple.sharedwithyou/documentation/SharedWithYou/SWAttributionView/horizontalAlignment-swift.property": {
      "abstract": [
        {
          "text": "The horizontal alignment of the view.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "horizontalAlignment"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)SWAttributionView",
          "text": "SWAttributionView"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@SWAttributionViewHorizontalAlignment",
          "text": "HorizontalAlignment"
        }
      ],
      "identifier": "doc://com.apple.sharedwithyou/documentation/SharedWithYou/SWAttributionView/horizontalAlignment-swift.property",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "horizontalAlignment"
        }
      ],
      "role": "symbol",
      "title": "horizontalAlignment",
      "type": "topic",
      "url": "/documentation/sharedwithyou/swattributionview/horizontalalignment-swift.property"
    },
    "doc://com.apple.sharedwithyou/documentation/SharedWithYou/SWAttributionView/menuTitleForHideAction": {
      "abstract": [
        {
          "text": "A localized string the system uses as a custom title for the hide menu item.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "menuTitleForHideAction"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.sharedwithyou/documentation/SharedWithYou/SWAttributionView/menuTitleForHideAction",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "menuTitleForHideAction"
        }
      ],
      "role": "symbol",
      "title": "menuTitleForHideAction",
      "type": "topic",
      "url": "/documentation/sharedwithyou/swattributionview/menutitleforhideaction"
    },
    "doc://com.apple.sharedwithyou/documentation/SharedWithYou/SWAttributionView/preferredMaxLayoutWidth": {
      "abstract": [
        {
          "text": "A width the system uses to constrain the view contents.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "preferredMaxLayoutWidth"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:14CoreFoundation7CGFloatV",
          "text": "CGFloat"
        }
      ],
      "identifier": "doc://com.apple.sharedwithyou/documentation/SharedWithYou/SWAttributionView/preferredMaxLayoutWidth",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "preferredMaxLayoutWidth"
        }
      ],
      "role": "symbol",
      "title": "preferredMaxLayoutWidth",
      "type": "topic",
      "url": "/documentation/sharedwithyou/swattributionview/preferredmaxlayoutwidth"
    },
    "doc://com.apple.sharedwithyou/documentation/SharedWithYou/SWAttributionView/supplementalMenu": {
      "abstract": [
        {
          "text": "A supplemental menu to augment the attribution view’s existing menu.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "supplementalMenu"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UIMenu",
          "text": "UIMenu"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.sharedwithyou/documentation/SharedWithYou/SWAttributionView/supplementalMenu",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "supplementalMenu"
        }
      ],
      "role": "symbol",
      "title": "supplementalMenu",
      "type": "topic",
      "url": "/documentation/sharedwithyou/swattributionview/supplementalmenu"
    },
    "doc://com.externally.resolved.symbol/c:@T@BOOL": {
      "abstract": [
        {
          "text": "Type to represent a Boolean value.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:@T@BOOL",
      "kind": "symbol",
      "role": "symbol",
      "title": "BOOL",
      "type": "topic",
      "url": "/documentation/objectivec/bool"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Customizing-highlights",
      "generated": true,
      "identifiers": [
        "doc://com.apple.sharedwithyou/documentation/SharedWithYou/SWAttributionView/backgroundStyle-swift.property",
        "doc://com.apple.sharedwithyou/documentation/SharedWithYou/SWAttributionView/displayContext-swift.property",
        "doc://com.apple.sharedwithyou/documentation/SharedWithYou/SWAttributionView/highlight",
        "doc://com.apple.sharedwithyou/documentation/SharedWithYou/SWAttributionView/highlightMenu",
        "doc://com.apple.sharedwithyou/documentation/SharedWithYou/SWAttributionView/horizontalAlignment-swift.property",
        "doc://com.apple.sharedwithyou/documentation/SharedWithYou/SWAttributionView/menuTitleForHideAction",
        "doc://com.apple.sharedwithyou/documentation/SharedWithYou/SWAttributionView/preferredMaxLayoutWidth",
        "doc://com.apple.sharedwithyou/documentation/SharedWithYou/SWAttributionView/supplementalMenu"
      ],
      "title": "Customizing highlights"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sharedwithyou~1documentation~1SharedWithYou~1SWAttributionView~1horizontalAlignment-swift.property/title",
          "value": "horizontalAlignment"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sharedwithyou~1documentation~1SharedWithYou~1SWAttributionView~1horizontalAlignment-swift.property/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "horizontalAlignment"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sharedwithyou~1documentation~1SharedWithYou~1SWAttributionView~1highlightMenu/title",
          "value": "highlightMenu"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sharedwithyou~1documentation~1SharedWithYou~1SWAttributionView~1highlightMenu/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "highlightMenu"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sharedwithyou~1documentation~1SharedWithYou~1SWAttributionView~1preferredMaxLayoutWidth/title",
          "value": "preferredMaxLayoutWidth"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sharedwithyou~1documentation~1SharedWithYou~1SWAttributionView~1preferredMaxLayoutWidth/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "preferredMaxLayoutWidth"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sharedwithyou~1documentation~1SharedWithYou~1SWAttributionView~1menuTitleForHideAction/title",
          "value": "menuTitleForHideAction"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sharedwithyou~1documentation~1SharedWithYou~1SWAttributionView~1menuTitleForHideAction/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "menuTitleForHideAction"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sharedwithyou~1documentation~1SharedWithYou~1SWAttributionView~1highlight/title",
          "value": "highlight"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sharedwithyou~1documentation~1SharedWithYou~1SWAttributionView~1highlight/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "highlight"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sharedwithyou~1documentation~1SharedWithYou~1SWAttributionView/title",
          "value": "SWAttributionView"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sharedwithyou~1documentation~1SharedWithYou~1SWAttributionView/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SWAttributionView"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sharedwithyou~1documentation~1SharedWithYou~1SWAttributionView/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SWAttributionView"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sharedwithyou~1documentation~1SharedWithYou~1SWAttributionView~1supplementalMenu/title",
          "value": "supplementalMenu"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sharedwithyou~1documentation~1SharedWithYou~1SWAttributionView~1supplementalMenu/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "supplementalMenu"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sharedwithyou~1documentation~1SharedWithYou~1SWAttributionView~1backgroundStyle-swift.property/title",
          "value": "backgroundStyle"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sharedwithyou~1documentation~1SharedWithYou~1SWAttributionView~1backgroundStyle-swift.property/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "backgroundStyle"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sharedwithyou~1documentation~1SharedWithYou~1SWAttributionView~1displayContext-swift.property/title",
          "value": "displayContext"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sharedwithyou~1documentation~1SharedWithYou~1SWAttributionView~1displayContext-swift.property/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "displayContext"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/sharedwithyou/swattributionview/enablesmarquee"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
