{
  "abstract": [
    {
      "text": "Create an account sign-up and sign-in strategy for your app.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.watchOS-Apps/documentation/watchOS-Apps"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.watchOS-Apps/documentation/watchOS-Apps/authenticating-users-on-apple-watch"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "role": "article",
    "roleHeading": "Article",
    "title": "Authenticating users on Apple Watch"
  },
  "primaryContentSections": [
    {
      "content": [
        {
          "anchor": "Overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Users can launch an independent watchOS app as soon as it downloads, even if they",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "don’t have their iPhone. As a result, users must be able to set up the application",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "directly on Apple Watch. If your app requires an account, users must be able to create",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "it and sign in on the watch.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "You have the following options for syncing or saving user data:",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "items": [
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Create an app that doesn’t require user accounts. Design your app so that it provides",
                      "type": "text"
                    },
                    {
                      "text": " ",
                      "type": "text"
                    },
                    {
                      "text": "a full set of features without user accounts, or use CloudKit to sync and store your",
                      "type": "text"
                    },
                    {
                      "text": " ",
                      "type": "text"
                    },
                    {
                      "text": "user’s data. Apps can access CloudKit data based on the user’s Apple ID without in-app",
                      "type": "text"
                    },
                    {
                      "text": " ",
                      "type": "text"
                    },
                    {
                      "text": "sign-in. watchOS 6 and later also supports CloudKit subscriptions and notifications",
                      "type": "text"
                    },
                    {
                      "text": " ",
                      "type": "text"
                    },
                    {
                      "text": "to let your app respond to changes from other devices.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Authenticate users with Sign In with Apple. This feature authenticates users based",
                      "type": "text"
                    },
                    {
                      "text": " ",
                      "type": "text"
                    },
                    {
                      "text": "on their Apple ID. For more information, see ",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.documentation/documentation/WatchKit/WKInterfaceAuthorizationAppleIDButton",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": " ",
                      "type": "text"
                    },
                    {
                      "text": "and ",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.documentation/documentation/AuthenticationServices",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": ".",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Create custom sign-in and sign-up forms.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            }
          ],
          "type": "unorderedList"
        },
        {
          "inlineContent": [
            {
              "text": "If you choose to create custom forms, watchOS 6 provides tools designed to fit the",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "small screen size and to streamline data entry on Apple Watch.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "anchor": "Simplify-account-creation-and-sign-in",
          "level": 3,
          "text": "Simplify account creation and sign-in",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Create your sign-in and sign-up forms using text fields. In SwiftUI, use the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/SwiftUI/TextField",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "and ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/SwiftUI/SecureField",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " structures.",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "In the storyboard, use the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/WatchKit/WKInterfaceTextField",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " class.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "To streamline data entry, perform the following steps:",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "items": [
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Set the text field’s content type. The text field’s content type modifies how",
                      "type": "text"
                    },
                    {
                      "text": " ",
                      "type": "text"
                    },
                    {
                      "text": "the text input controller and Apple Continuity Keyboard behave. For SwiftUI, set",
                      "type": "text"
                    },
                    {
                      "text": " ",
                      "type": "text"
                    },
                    {
                      "text": "the content type by calling the text field’s ",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.documentation/documentation/SwiftUI/View/textContentType(_:)-4dqqb",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": " ",
                      "type": "text"
                    },
                    {
                      "text": "method. For the storyboard, set the content type using the Attributes inspector.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Provide a placeholder that describes the text field’s expected content. Effective",
                      "type": "text"
                    },
                    {
                      "text": " ",
                      "type": "text"
                    },
                    {
                      "text": "placeholders help you get the most out of Apple Watch’s smaller screen. For SwiftUI,",
                      "type": "text"
                    },
                    {
                      "text": " ",
                      "type": "text"
                    },
                    {
                      "text": "when instantiating the text field, the ",
                      "type": "text"
                    },
                    {
                      "code": "title",
                      "type": "codeVoice"
                    },
                    {
                      "text": " property sets the placeholder. For",
                      "type": "text"
                    },
                    {
                      "text": " ",
                      "type": "text"
                    },
                    {
                      "text": "the storyboard, set the placeholder using the Attributes inspector. Note that the",
                      "type": "text"
                    },
                    {
                      "text": " ",
                      "type": "text"
                    },
                    {
                      "text": "system truncates placeholders if the text is too long, so keep your placeholders",
                      "type": "text"
                    },
                    {
                      "text": " ",
                      "type": "text"
                    },
                    {
                      "text": "short.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Set up your app’s associated domains. If you have a website where users can sign",
                      "type": "text"
                    },
                    {
                      "text": " ",
                      "type": "text"
                    },
                    {
                      "text": "in with the same username and password, associate the website’s domain with your",
                      "type": "text"
                    },
                    {
                      "text": " ",
                      "type": "text"
                    },
                    {
                      "text": "app. An associated domain tells the Apple Continuity Keyboard to provide autofill",
                      "type": "text"
                    },
                    {
                      "text": " ",
                      "type": "text"
                    },
                    {
                      "text": "suggestions for usernames and passwords from that domain. To learn how to set up",
                      "type": "text"
                    },
                    {
                      "text": " ",
                      "type": "text"
                    },
                    {
                      "text": "your app’s associated domains, see ",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.documentation/documentation/Xcode/supporting-associated-domains",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": ".",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            }
          ],
          "type": "orderedList"
        },
        {
          "anchor": "Support-password-autofill",
          "level": 3,
          "text": "Support password autofill",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "To support password autofill on Apple Watch, set the following ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/WatchKit/WKTextContentType",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "values.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "header": "row",
          "rows": [
            [
              [
                {
                  "inlineContent": [
                    {
                      "text": "Credential",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ],
              [
                {
                  "inlineContent": [
                    {
                      "text": "Content Type",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            ],
            [
              [
                {
                  "inlineContent": [
                    {
                      "text": "User Name",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ],
              [
                {
                  "inlineContent": [
                    {
                      "identifier": "doc://com.apple.documentation/documentation/WatchKit/WKTextContentType/username",
                      "isActive": true,
                      "type": "reference"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            ],
            [
              [
                {
                  "inlineContent": [
                    {
                      "text": "Password",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ],
              [
                {
                  "inlineContent": [
                    {
                      "identifier": "doc://com.apple.documentation/documentation/WatchKit/WKTextContentType/password",
                      "isActive": true,
                      "type": "reference"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            ],
            [
              [
                {
                  "inlineContent": [
                    {
                      "text": "New Password",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ],
              [
                {
                  "inlineContent": [
                    {
                      "identifier": "doc://com.apple.documentation/documentation/WatchKit/WKTextContentType/newPassword",
                      "isActive": true,
                      "type": "reference"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            ],
            [
              [
                {
                  "inlineContent": [
                    {
                      "text": "One-Time Code",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ],
              [
                {
                  "inlineContent": [
                    {
                      "identifier": "doc://com.apple.documentation/documentation/WatchKit/WKTextContentType/oneTimeCode",
                      "isActive": true,
                      "type": "reference"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            ]
          ],
          "type": "table"
        },
        {
          "inlineContent": [
            {
              "text": "For ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/SwiftUI/TextField",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " and ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/SwiftUI/SecureField",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ",",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "set the content type by calling the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/SwiftUI/View/textContentType(_:)-4dqqb",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "method.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "code": [
            "var body: some View {",
            "    VStack {",
            "        TextField(\"User Name\", text: $userName)",
            "            .textContentType(.username)",
            "            .multilineTextAlignment(.center)",
            "        SecureField(\"Password\", text: $password)",
            "            .textContentType(.password)",
            "            .multilineTextAlignment(.center)",
            "        Button(\"Done\") {",
            "        }.disabled(userName.isEmpty || password.isEmpty)",
            "    }",
            "}"
          ],
          "syntax": "swift",
          "type": "codeListing"
        },
        {
          "inlineContent": [
            {
              "text": "For ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/WatchKit/WKInterfaceTextField",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ", assign these values in Xcode by setting the",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "Content Type attribute in the Attributes inspector.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "identifier": "authenticating-users-on-apple-watch-1",
              "type": "image"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "watchOS provides an autofill suggestion for ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/WatchKit/WKTextContentType/oneTimeCode",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "fields after receiving an SMS message that contains a one-time code.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "If you place a ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/WatchKit/WKTextContentType/username",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " or ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/WatchKit/WKTextContentType/emailAddress",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "text field on the same screen as a ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/WatchKit/WKTextContentType/password",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " text field,",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "the Apple Continuity Keyboard attempts to fill both fields. Similarly, if you put",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "two ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/WatchKit/WKTextContentType/newPassword",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " fields on the same screen, the keyboard",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "automatically fills both when the user selects the suggested password.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "For more information, see ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/Security/password-autofill",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ".",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "authenticating-users-on-apple-watch-1": {
      "alt": "A screenshot showing the Content Type attribute in the Attributes inspector.",
      "identifier": "authenticating-users-on-apple-watch-1",
      "type": "image",
      "variants": [
        {
          "traits": [
            "2x",
            "light"
          ],
          "url": "https://docs-assets.developer.apple.com/published/504418c9024b811f847d0371089764b4/authenticating-users-on-apple-watch-1@2x.png"
        },
        {
          "traits": [
            "2x",
            "dark"
          ],
          "url": "https://docs-assets.developer.apple.com/published/7799e41366bb10157ef39022ce92a7f9/authenticating-users-on-apple-watch-1~dark@2x.png"
        }
      ]
    },
    "doc://com.apple.documentation/documentation/AppIntents/ActionButtonArticle": {
      "abstract": [
        {
          "text": "Use App Intents to register actions for your app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/AppIntents/ActionButtonArticle",
      "kind": "article",
      "role": "article",
      "title": "Responding to the Action button on Apple Watch Ultra",
      "type": "topic",
      "url": "/documentation/AppIntents/ActionButtonArticle"
    },
    "doc://com.apple.documentation/documentation/AuthenticationServices": {
      "abstract": [
        {
          "text": "Make it easy for users to log into apps and services.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/AuthenticationServices",
      "kind": "symbol",
      "role": "collection",
      "title": "Authentication Services",
      "type": "topic",
      "url": "/documentation/AuthenticationServices"
    },
    "doc://com.apple.documentation/documentation/Security/password-autofill": {
      "abstract": [
        {
          "text": "Streamline your app’s login and onboarding procedures.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/Security/password-autofill",
      "kind": "article",
      "role": "article",
      "title": "Password AutoFill",
      "type": "topic",
      "url": "/documentation/Security/password-autofill"
    },
    "doc://com.apple.documentation/documentation/SwiftUI/SecureField": {
      "abstract": [
        {
          "text": "A control into which people securely enter private text.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SecureField"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "genericParameter",
          "text": "Label"
        },
        {
          "kind": "text",
          "text": "> "
        },
        {
          "kind": "keyword",
          "text": "where"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "typeIdentifier",
          "text": "Label"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:7SwiftUI4ViewP",
          "text": "View"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/SwiftUI/SecureField",
      "kind": "symbol",
      "role": "symbol",
      "title": "SecureField",
      "type": "topic",
      "url": "/documentation/SwiftUI/SecureField"
    },
    "doc://com.apple.documentation/documentation/SwiftUI/TextField": {
      "abstract": [
        {
          "text": "A control that displays an editable text interface.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "TextField"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "genericParameter",
          "text": "Label"
        },
        {
          "kind": "text",
          "text": "> "
        },
        {
          "kind": "keyword",
          "text": "where"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "typeIdentifier",
          "text": "Label"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:7SwiftUI4ViewP",
          "text": "View"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/SwiftUI/TextField",
      "kind": "symbol",
      "role": "symbol",
      "title": "TextField",
      "type": "topic",
      "url": "/documentation/SwiftUI/TextField"
    },
    "doc://com.apple.documentation/documentation/SwiftUI/View/textContentType(_:)-4dqqb": {
      "abstract": [
        {
          "text": "Sets the text content type for this view, which the system uses to offer suggestions while the user enters text on a watchOS device.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "nonisolated"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "textContentType"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "_"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "internalParam",
          "text": "textContentType"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@WKTextContentType",
          "text": "WKTextContentType"
        },
        {
          "kind": "text",
          "text": "?) -> "
        },
        {
          "kind": "keyword",
          "text": "some"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:7SwiftUI4ViewP",
          "text": "View"
        },
        {
          "kind": "text",
          "text": "\n"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/SwiftUI/View/textContentType(_:)-4dqqb",
      "kind": "symbol",
      "role": "symbol",
      "title": "textContentType(_:)",
      "type": "topic",
      "url": "/documentation/SwiftUI/View/textContentType(_:)-4dqqb"
    },
    "doc://com.apple.documentation/documentation/WatchKit/WKInterfaceAuthorizationAppleIDButton": {
      "abstract": [
        {
          "text": "A button that you can use to trigger a Sign in with Apple request.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "WKInterfaceAuthorizationAppleIDButton"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/WatchKit/WKInterfaceAuthorizationAppleIDButton",
      "kind": "symbol",
      "role": "symbol",
      "title": "WKInterfaceAuthorizationAppleIDButton",
      "type": "topic",
      "url": "/documentation/WatchKit/WKInterfaceAuthorizationAppleIDButton"
    },
    "doc://com.apple.documentation/documentation/WatchKit/WKInterfaceTextField": {
      "abstract": [
        {
          "text": "An interface element that displays an editable text area.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "WKInterfaceTextField"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/WatchKit/WKInterfaceTextField",
      "kind": "symbol",
      "role": "symbol",
      "title": "WKInterfaceTextField",
      "type": "topic",
      "url": "/documentation/WatchKit/WKInterfaceTextField"
    },
    "doc://com.apple.documentation/documentation/WatchKit/WKTextContentType": {
      "abstract": [
        {
          "text": "Constants that specify a text field’s semantic meaning.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "WKTextContentType"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/WatchKit/WKTextContentType",
      "kind": "symbol",
      "role": "symbol",
      "title": "WKTextContentType",
      "type": "topic",
      "url": "/documentation/WatchKit/WKTextContentType"
    },
    "doc://com.apple.documentation/documentation/WatchKit/WKTextContentType/emailAddress": {
      "abstract": [
        {
          "text": "An email address.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "emailAddress"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@WKTextContentType",
          "text": "WKTextContentType"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/WatchKit/WKTextContentType/emailAddress",
      "kind": "symbol",
      "role": "symbol",
      "title": "emailAddress",
      "type": "topic",
      "url": "/documentation/WatchKit/WKTextContentType/emailAddress"
    },
    "doc://com.apple.documentation/documentation/WatchKit/WKTextContentType/newPassword": {
      "abstract": [
        {
          "text": "A new password.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "newPassword"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@WKTextContentType",
          "text": "WKTextContentType"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/WatchKit/WKTextContentType/newPassword",
      "kind": "symbol",
      "role": "symbol",
      "title": "newPassword",
      "type": "topic",
      "url": "/documentation/WatchKit/WKTextContentType/newPassword"
    },
    "doc://com.apple.documentation/documentation/WatchKit/WKTextContentType/oneTimeCode": {
      "abstract": [
        {
          "text": "A one-time code.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "oneTimeCode"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@WKTextContentType",
          "text": "WKTextContentType"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/WatchKit/WKTextContentType/oneTimeCode",
      "kind": "symbol",
      "role": "symbol",
      "title": "oneTimeCode",
      "type": "topic",
      "url": "/documentation/WatchKit/WKTextContentType/oneTimeCode"
    },
    "doc://com.apple.documentation/documentation/WatchKit/WKTextContentType/password": {
      "abstract": [
        {
          "text": "An existing password.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "password"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@WKTextContentType",
          "text": "WKTextContentType"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/WatchKit/WKTextContentType/password",
      "kind": "symbol",
      "role": "symbol",
      "title": "password",
      "type": "topic",
      "url": "/documentation/WatchKit/WKTextContentType/password"
    },
    "doc://com.apple.documentation/documentation/WatchKit/WKTextContentType/username": {
      "abstract": [
        {
          "text": "An account or login name.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "username"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@WKTextContentType",
          "text": "WKTextContentType"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/WatchKit/WKTextContentType/username",
      "kind": "symbol",
      "role": "symbol",
      "title": "username",
      "type": "topic",
      "url": "/documentation/WatchKit/WKTextContentType/username"
    },
    "doc://com.apple.documentation/documentation/Xcode/supporting-associated-domains": {
      "abstract": [
        {
          "text": "Connect your app and a website to provide both a native app and a browser experience.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/Xcode/supporting-associated-domains",
      "kind": "article",
      "role": "article",
      "title": "Supporting associated domains",
      "type": "topic",
      "url": "/documentation/Xcode/supporting-associated-domains"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.watchOS-Apps/documentation/watchOS-Apps": {
      "abstract": [
        {
          "text": "Build watchOS apps that combine complications, notifications, and Siri to create",
          "type": "text"
        },
        {
          "text": " ",
          "type": "text"
        },
        {
          "text": "a personal experience on Apple Watch.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.watchOS-Apps/documentation/watchOS-Apps",
      "images": [
        {
          "identifier": "watchOSApps-PageImage-card.png",
          "type": "card"
        }
      ],
      "kind": "article",
      "role": "collection",
      "title": "watchOS apps",
      "type": "topic",
      "url": "/documentation/watchos-apps"
    },
    "doc://com.apple.watchOS-Apps/documentation/watchOS-Apps/creating-independent-watchos-apps": {
      "abstract": [
        {
          "text": "Set up a watchOS app that installs and runs without a companion iOS app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.watchOS-Apps/documentation/watchOS-Apps/creating-independent-watchos-apps",
      "kind": "article",
      "role": "article",
      "title": "Creating independent watchOS apps",
      "type": "topic",
      "url": "/documentation/watchos-apps/creating-independent-watchos-apps"
    },
    "doc://com.apple.watchOS-Apps/documentation/watchOS-Apps/enabling-double-tap": {
      "abstract": [
        {
          "text": "Customize your app’s response to the double-tap gesture on Apple Watch.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.watchOS-Apps/documentation/watchOS-Apps/enabling-double-tap",
      "images": [
        {
          "identifier": "enabling-double-tap-on-watch-PageImage-card.png",
          "type": "card"
        }
      ],
      "kind": "article",
      "role": "article",
      "title": "Enabling the double-tap gesture on Apple Watch",
      "type": "topic",
      "url": "/documentation/watchos-apps/enabling-double-tap"
    },
    "doc://com.apple.watchOS-Apps/documentation/watchOS-Apps/keeping-your-watchos-app-s-content-up-to-date": {
      "abstract": [
        {
          "text": "Ensure that your app’s content is relevant and up to date.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.watchOS-Apps/documentation/watchOS-Apps/keeping-your-watchos-app-s-content-up-to-date",
      "kind": "article",
      "role": "article",
      "title": "Keeping your watchOS content up to date",
      "type": "topic",
      "url": "/documentation/watchos-apps/keeping-your-watchos-app-s-content-up-to-date"
    },
    "doc://com.apple.watchOS-Apps/documentation/watchOS-Apps/setting-up-a-watchos-project": {
      "abstract": [
        {
          "text": "Create a new watchOS project or add a watch target to an existing iOS project.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.watchOS-Apps/documentation/watchOS-Apps/setting-up-a-watchos-project",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Setting up a watchOS project",
      "type": "topic",
      "url": "/documentation/watchos-apps/setting-up-a-watchos-project"
    },
    "doc://com.apple.watchOS-Apps/documentation/watchOS-Apps/updating-watchos-apps-with-timelines": {
      "abstract": [
        {
          "text": "Seamlessly schedule updates to your user interface, even while it’s inactive.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.watchOS-Apps/documentation/watchOS-Apps/updating-watchos-apps-with-timelines",
      "kind": "article",
      "role": "article",
      "title": "Updating watchOS apps with timelines",
      "type": "topic",
      "url": "/documentation/watchos-apps/updating-watchos-apps-with-timelines"
    },
    "enabling-double-tap-on-watch-PageImage-card.png": {
      "alt": "A stylistic representation of the double tap gesture on Apple Watch.",
      "identifier": "enabling-double-tap-on-watch-PageImage-card.png",
      "type": "image",
      "variants": [
        {
          "traits": [
            "2x",
            "light"
          ],
          "url": "https://docs-assets.developer.apple.com/published/31d5e805205ce0e598c55fdb76989025/enabling-double-tap-on-watch-PageImage-card@2x.png"
        },
        {
          "traits": [
            "2x",
            "dark"
          ],
          "url": "https://docs-assets.developer.apple.com/published/235637bc0a7bc531746ce17b9ed199b3/enabling-double-tap-on-watch-PageImage-card~dark@2x.png"
        }
      ]
    },
    "watchOSApps-PageImage-card.png": {
      "alt": "A stylized representation of Apple Watch.",
      "identifier": "watchOSApps-PageImage-card.png",
      "type": "image",
      "variants": [
        {
          "traits": [
            "2x",
            "light"
          ],
          "url": "https://docs-assets.developer.apple.com/published/5e043ca96ec9c9e5579649124c448c35/watchOSApps-PageImage-card@2x.png"
        },
        {
          "traits": [
            "2x",
            "dark"
          ],
          "url": "https://docs-assets.developer.apple.com/published/2e82e5f258fb084d7b684889cabbe515/watchOSApps-PageImage-card~dark@2x.png"
        }
      ]
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "App-experience",
      "generated": true,
      "identifiers": [
        "doc://com.apple.watchOS-Apps/documentation/watchOS-Apps/setting-up-a-watchos-project",
        "doc://com.apple.watchOS-Apps/documentation/watchOS-Apps/creating-independent-watchos-apps",
        "doc://com.apple.watchOS-Apps/documentation/watchOS-Apps/keeping-your-watchos-app-s-content-up-to-date",
        "doc://com.apple.watchOS-Apps/documentation/watchOS-Apps/updating-watchos-apps-with-timelines",
        "doc://com.apple.documentation/documentation/AppIntents/ActionButtonArticle",
        "doc://com.apple.watchOS-Apps/documentation/watchOS-Apps/enabling-double-tap"
      ],
      "title": "App experience"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1WatchKit~1WKTextContentType~1username/title",
          "value": "WKTextContentTypeUsername"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1WatchKit~1WKTextContentType~1username/fragments",
          "value": [
            {
              "kind": "keyword",
              "text": "extern"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@WKTextContentType",
              "text": "WKTextContentType"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "keyword",
              "text": "const"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "WKTextContentTypeUsername"
            },
            {
              "kind": "text",
              "text": ";"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1WatchKit~1WKTextContentType~1password/title",
          "value": "WKTextContentTypePassword"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1WatchKit~1WKTextContentType~1password/fragments",
          "value": [
            {
              "kind": "keyword",
              "text": "extern"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@WKTextContentType",
              "text": "WKTextContentType"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "keyword",
              "text": "const"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "WKTextContentTypePassword"
            },
            {
              "kind": "text",
              "text": ";"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1WatchKit~1WKInterfaceTextField/fragments",
          "value": [
            {
              "kind": "keyword",
              "text": "@interface"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "WKInterfaceTextField"
            },
            {
              "kind": "text",
              "text": " : "
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)WKInterfaceObject",
              "text": "WKInterfaceObject"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1WatchKit~1WKInterfaceAuthorizationAppleIDButton/fragments",
          "value": [
            {
              "kind": "keyword",
              "text": "@interface"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "WKInterfaceAuthorizationAppleIDButton"
            },
            {
              "kind": "text",
              "text": " : "
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)WKInterfaceObject",
              "text": "WKInterfaceObject"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1WatchKit~1WKTextContentType~1newPassword/title",
          "value": "WKTextContentTypeNewPassword"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1WatchKit~1WKTextContentType~1newPassword/fragments",
          "value": [
            {
              "kind": "keyword",
              "text": "extern"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@WKTextContentType",
              "text": "WKTextContentType"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "keyword",
              "text": "const"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "WKTextContentTypeNewPassword"
            },
            {
              "kind": "text",
              "text": ";"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1WatchKit~1WKTextContentType~1oneTimeCode/title",
          "value": "WKTextContentTypeOneTimeCode"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1WatchKit~1WKTextContentType~1oneTimeCode/fragments",
          "value": [
            {
              "kind": "keyword",
              "text": "extern"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@WKTextContentType",
              "text": "WKTextContentType"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "keyword",
              "text": "const"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "WKTextContentTypeOneTimeCode"
            },
            {
              "kind": "text",
              "text": ";"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1WatchKit~1WKTextContentType/fragments",
          "value": [
            {
              "kind": "keyword",
              "text": "typedef"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)NSString",
              "text": "NSString"
            },
            {
              "kind": "text",
              "text": " * "
            },
            {
              "kind": "identifier",
              "text": "WKTextContentType"
            },
            {
              "kind": "text",
              "text": ";"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1WatchKit~1WKTextContentType~1emailAddress/title",
          "value": "WKTextContentTypeEmailAddress"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1WatchKit~1WKTextContentType~1emailAddress/fragments",
          "value": [
            {
              "kind": "keyword",
              "text": "extern"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@WKTextContentType",
              "text": "WKTextContentType"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "keyword",
              "text": "const"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "WKTextContentTypeEmailAddress"
            },
            {
              "kind": "text",
              "text": ";"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
