{
  "abstract": [
    {
      "text": "Set up your app’s life cycle and create its user interface with SwiftUI.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.watchOS-Apps/documentation/watchOS-Apps"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.watchOS-Apps/documentation/watchOS-Apps/building_a_watchos_app"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "role": "article",
    "roleHeading": "Article",
    "title": "Building a watchOS app"
  },
  "primaryContentSections": [
    {
      "content": [
        {
          "anchor": "Overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Develop powerful, personal apps for Apple Watch using SwiftUI, a declarative",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "framework for building user interfaces on all of Apple’s platforms. You can",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "create rich user interfaces by composing simple views — which perform a single,",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "focused task — into larger, more complex layouts. Your app describes the correct",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "layout for its views based on its current state. SwiftUI detects changes to the",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "state and updates the views accordingly.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "On watchOS, SwiftUI gives you considerably more freedom, power, and control than",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "user interfaces laid out and designed in a storyboard. For example,",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/SwiftUI/List",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " has a number of",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "features that aren’t supported by",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/WatchKit/WKInterfaceTable",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ", such as",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "the platter style, swipe actions (shown below), and row reordering.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "identifier": "building_a_watchos_app-1",
              "type": "image"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "Additionally, you can preview your SwiftUI code in Xcode’s canvas. You can",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "design, build, and test your interfaces without ever running your app.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "identifier": "building_a_watchos_app-2",
              "type": "image"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "SwiftUI also provides watch-specific representations of tab and navigation",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "views, with fully customizable navigation bars and customizable toolbar items",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "for confirmation, cancellation, and destructive actions. You can also use",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "SwiftUI to manage your app’s life cycle. To learn more about SwiftUI, see",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/tutorials/SwiftUI",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ".",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "anchor": "Set-up-the-root-view",
          "level": 3,
          "text": "Set up the root view",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "To manage your app’s life cycle with SwiftUI, create a structure that adopts the",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/SwiftUI/App",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " protocol in your",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "watchOS app target.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "code": [
            "import SwiftUI",
            "",
            "@main",
            "struct MyProject_Watch_App: App {",
            "}"
          ],
          "syntax": "swift",
          "type": "codeListing"
        },
        {
          "inlineContent": [
            {
              "text": "The",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "identifier": "https://docs.swift.org/swift-book/documentation/the-swift-programming-language/attributes",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": "",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "attribute indicates this is the entry point for your app. Each app can have only",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "one entry point.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "Inside the structure, define the app’s",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/SwiftUI/App/body-swift.property",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ".",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "The ",
              "type": "text"
            },
            {
              "code": "body",
              "type": "codeVoice"
            },
            {
              "text": " automatically composes a collection of",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/SwiftUI/Scene",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " instances into",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "a single, compound ",
              "type": "text"
            },
            {
              "code": "Scene",
              "type": "codeVoice"
            },
            {
              "text": ".",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "code": [
            "@main",
            "struct MyProject_Watch_App: App {",
            "    var body: some Scene {",
            "    }",
            "}"
          ],
          "syntax": "swift",
          "type": "codeListing"
        },
        {
          "inlineContent": [
            {
              "text": "Next, add a ",
              "type": "text"
            },
            {
              "code": "Scene",
              "type": "codeVoice"
            },
            {
              "text": " or your app’s root view. For a watchOS app, you typically",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "create a ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/SwiftUI/WindowGroup",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " scene",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "that wraps",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "a ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/SwiftUI/NavigationView",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " around",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "your app’s root view. The ",
              "type": "text"
            },
            {
              "code": "NavigationView",
              "type": "codeVoice"
            },
            {
              "text": " provides a navigation stack and title",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "area for your app.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "code": [
            "@main",
            "struct MyProject_Watch_App: App {",
            "    var body: some Scene {",
            "        WindowGroup {",
            "            NavigationView {",
            "                ContentView()",
            "            }",
            "        }",
            "    }",
            "}"
          ],
          "syntax": "swift",
          "type": "codeListing"
        },
        {
          "inlineContent": [
            {
              "text": "When your app launches, it displays the view hierarchy defined by the window",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "group.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "You can also add scenes for notification categories.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "code": [
            "var body: some Scene {",
            "    WindowGroup {",
            "        NavigationView {",
            "            ContentView()",
            "        }",
            "    }",
            "",
            "    WKNotificationScene(controller: NotificationController.self, category: \"myCategory\")",
            "}"
          ],
          "syntax": "swift",
          "type": "codeListing"
        },
        {
          "inlineContent": [
            {
              "text": "When the system receives a notification with a matching category, it displays",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "a dynamic view specified by the notification controller. You can create",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "a ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/SwiftUI/WKUserNotificationHostingController",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": "",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "subclass for each notification category supported by your app.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "code": [
            "import SwiftUI",
            "import UserNotifications",
            "",
            "class NotificationController: WKUserNotificationHostingController<NotificationLongLook> {",
            "",
            "    var content:UNNotificationContent!",
            "    var date:Date!",
            "",
            "    override var body: NotificationLongLook{",
            "        NotificationLongLook(content: content, date: date)",
            "    }",
            "",
            "    override class var isInteractive: Bool { true }",
            "",
            "    override func didReceive(_ notification: UNNotification) {",
            "        content = notification.request.content",
            "        date = notification.date",
            "    }",
            "}"
          ],
          "syntax": "swift",
          "type": "codeListing"
        },
        {
          "inlineContent": [
            {
              "text": "For more information, see ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.watchOS-Apps/documentation/watchOS-Apps/customizing-your-long-look-interface",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ".",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "anchor": "Respond-to-app-events-in-SwiftUI",
          "level": 3,
          "text": "Respond to app events in SwiftUI",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Your app can respond to many app events directly in SwiftUI.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "SwiftUI updates the",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/SwiftUI/EnvironmentValues/scenePhase",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": "",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "environment value as your app changes state. To update a view based on these",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "changes, you can use the",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/SwiftUI/View/onChange(of:perform:)",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": "",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "modifier. For more information, see",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/WatchKit/handling-common-state-transitions",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ".",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "SwiftUI also provides view modifiers for handling user activity and background",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "tasks:",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "items": [
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Use",
                      "type": "text"
                    },
                    {
                      "text": " ",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.documentation/documentation/SwiftUI/View/onContinueUserActivity(_:perform:)",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": "",
                      "type": "text"
                    },
                    {
                      "text": " ",
                      "type": "text"
                    },
                    {
                      "text": "to handle incoming",
                      "type": "text"
                    },
                    {
                      "text": " ",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.documentation/documentation/foundation/nsuseractivity",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": "",
                      "type": "text"
                    },
                    {
                      "text": " ",
                      "type": "text"
                    },
                    {
                      "text": "objects. For more information, see",
                      "type": "text"
                    },
                    {
                      "text": " ",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.documentation/documentation/WatchKit/handling-user-activity",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": ".",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Use",
                      "type": "text"
                    },
                    {
                      "text": " ",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.documentation/documentation/SwiftUI/Scene/backgroundTask(_:action:)",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": "",
                      "type": "text"
                    },
                    {
                      "text": " ",
                      "type": "text"
                    },
                    {
                      "text": "to handle incoming",
                      "type": "text"
                    },
                    {
                      "text": " ",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.documentation/documentation/SwiftUI/BackgroundTask",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": "",
                      "type": "text"
                    },
                    {
                      "text": " ",
                      "type": "text"
                    },
                    {
                      "text": "instances. For more information, see",
                      "type": "text"
                    },
                    {
                      "text": " ",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.documentation/documentation/WatchKit/using-background-tasks",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": ".",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            }
          ],
          "type": "unorderedList"
        },
        {
          "anchor": "Respond-to-app-events-using-an-app-delegate",
          "level": 3,
          "text": "Respond to app events using an app delegate",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "You need an app delegate to handle the following events:",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "items": [
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Life cycle events, like",
                      "type": "text"
                    },
                    {
                      "text": " ",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.documentation/documentation/WatchKit/WKApplicationDelegate/applicationDidFinishLaunching()",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": ",",
                      "type": "text"
                    },
                    {
                      "text": " ",
                      "type": "text"
                    },
                    {
                      "text": "that aren’t handled by the",
                      "type": "text"
                    },
                    {
                      "text": " ",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.documentation/documentation/SwiftUI/EnvironmentValues/scenePhase",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": "",
                      "type": "text"
                    },
                    {
                      "text": " ",
                      "type": "text"
                    },
                    {
                      "text": "environment variable",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "code": "userInfo",
                      "type": "codeVoice"
                    },
                    {
                      "text": " dictionaries from either handoff or complications",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Remote Now Playing activity",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Workout configurations and recovery",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Extended runtime sessions",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Registration of remote notifications",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            }
          ],
          "type": "unorderedList"
        },
        {
          "inlineContent": [
            {
              "text": "To add an app delegate to your app, create a class that adopts the",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/WatchKit/WKApplicationDelegate",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " protocol. In this",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "class, implement the methods needed to handle your app’s events. Then use the",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/SwiftUI/WKApplicationDelegateAdaptor",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": "",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "property wrapper to declare a variable for your delegate.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "code": [
            "import SwiftUI",
            "import WatchKit",
            "",
            "@main",
            "struct MyProject_Watch_App: App {",
            "",
            "    @WKApplicationDelegateAdaptor var appDelegate: MyAppDelegate",
            "",
            "    var body: some Scene {",
            "        WindowGroup {",
            "            NavigationView {",
            "                ContentView()",
            "            }",
            "        }",
            "",
            "        WKNotificationScene(controller: NotificationController.self, category: \"myCategory\")",
            "    }",
            "}"
          ],
          "syntax": "swift",
          "type": "codeListing"
        },
        {
          "inlineContent": [
            {
              "text": "When your app launches, the system instantiates your delegate class and calls",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/WatchKit/WKApplicationDelegate/applicationDidFinishLaunching()",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ".",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "Use this method to perform any additional configuration that your delegate",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "requires. After it returns, the system begins calling your delegate methods when",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "the corresponding events occur.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "building_a_watchos_app-1": {
      "alt": "A screenshot of a watch face displaying a list. The middle row shows the list’s delete swipe action. The row shifts to the left, revealing a large X.",
      "identifier": "building_a_watchos_app-1",
      "type": "image",
      "variants": [
        {
          "traits": [
            "2x",
            "light"
          ],
          "url": "https://docs-assets.developer.apple.com/published/2062deb1ae379223221556b390059420/building_a_watchos_app-1@2x.png"
        },
        {
          "traits": [
            "2x",
            "dark"
          ],
          "url": "https://docs-assets.developer.apple.com/published/ebcf45766b0513e9d230e8976df0f747/building_a_watchos_app-1~dark@2x.png"
        }
      ]
    },
    "building_a_watchos_app-2": {
      "alt": "A screenshot showing Xcode with the circle image selected in the preview.",
      "identifier": "building_a_watchos_app-2",
      "type": "image",
      "variants": [
        {
          "traits": [
            "2x",
            "light"
          ],
          "url": "https://docs-assets.developer.apple.com/published/39944a0d0fe662f30f19a7ae623bbd4d/building_a_watchos_app-2@2x.png"
        },
        {
          "traits": [
            "2x",
            "dark"
          ],
          "url": "https://docs-assets.developer.apple.com/published/b87287efd20a5fe9037782e589c8a47a/building_a_watchos_app-2~dark@2x.png"
        }
      ]
    },
    "doc://com.apple.documentation/documentation/SwiftUI/App": {
      "abstract": [
        {
          "text": "A type that represents the structure and behavior of an app.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@"
        },
        {
          "kind": "attribute",
          "preciseIdentifier": "s:ScM",
          "text": "MainActor"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "attribute",
          "text": "@preconcurrency"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "App"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/SwiftUI/App",
      "kind": "symbol",
      "role": "symbol",
      "title": "App",
      "type": "topic",
      "url": "/documentation/SwiftUI/App"
    },
    "doc://com.apple.documentation/documentation/SwiftUI/App/body-swift.property": {
      "abstract": [
        {
          "text": "The content and behavior of the app.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@"
        },
        {
          "kind": "attribute",
          "preciseIdentifier": "s:7SwiftUI12SceneBuilderV",
          "text": "SceneBuilder"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "attribute",
          "text": "@"
        },
        {
          "kind": "attribute",
          "preciseIdentifier": "s:ScM",
          "text": "MainActor"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "attribute",
          "text": "@preconcurrency"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "body"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "text": "Self"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:7SwiftUI3AppP4BodyQa",
          "text": "Body"
        },
        {
          "kind": "text",
          "text": " { "
        },
        {
          "kind": "keyword",
          "text": "get"
        },
        {
          "kind": "text",
          "text": " }"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/SwiftUI/App/body-swift.property",
      "kind": "symbol",
      "role": "symbol",
      "title": "body",
      "type": "topic",
      "url": "/documentation/SwiftUI/App/body-swift.property"
    },
    "doc://com.apple.documentation/documentation/SwiftUI/BackgroundTask": {
      "abstract": [
        {
          "text": "The kinds of background tasks that your app or extension can handle.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BackgroundTask"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "genericParameter",
          "text": "Request"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "genericParameter",
          "text": "Response"
        },
        {
          "kind": "text",
          "text": ">"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/SwiftUI/BackgroundTask",
      "kind": "symbol",
      "role": "symbol",
      "title": "BackgroundTask",
      "type": "topic",
      "url": "/documentation/SwiftUI/BackgroundTask"
    },
    "doc://com.apple.documentation/documentation/SwiftUI/EnvironmentValues/scenePhase": {
      "abstract": [
        {
          "text": "The current phase of the scene.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "scenePhase"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:7SwiftUI10ScenePhaseO",
          "text": "ScenePhase"
        },
        {
          "kind": "text",
          "text": " { "
        },
        {
          "kind": "keyword",
          "text": "get"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "set"
        },
        {
          "kind": "text",
          "text": " }"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/SwiftUI/EnvironmentValues/scenePhase",
      "kind": "symbol",
      "role": "symbol",
      "title": "scenePhase",
      "type": "topic",
      "url": "/documentation/SwiftUI/EnvironmentValues/scenePhase"
    },
    "doc://com.apple.documentation/documentation/SwiftUI/List": {
      "abstract": [
        {
          "text": "A container that presents rows of data arranged in a single column, optionally providing the ability to select one or more members.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@"
        },
        {
          "kind": "attribute",
          "preciseIdentifier": "s:ScM",
          "text": "MainActor"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "attribute",
          "text": "@preconcurrency"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "List"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "genericParameter",
          "text": "SelectionValue"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "genericParameter",
          "text": "Content"
        },
        {
          "kind": "text",
          "text": "> "
        },
        {
          "kind": "keyword",
          "text": "where"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "typeIdentifier",
          "text": "SelectionValue"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SH",
          "text": "Hashable"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "text": "Content"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:7SwiftUI4ViewP",
          "text": "View"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/SwiftUI/List",
      "kind": "symbol",
      "role": "symbol",
      "title": "List",
      "type": "topic",
      "url": "/documentation/SwiftUI/List"
    },
    "doc://com.apple.documentation/documentation/SwiftUI/NavigationView": {
      "abstract": [
        {
          "text": "A view for presenting a stack of views that represents a visible path in a navigation hierarchy.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NavigationView"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "genericParameter",
          "text": "Content"
        },
        {
          "kind": "text",
          "text": "> "
        },
        {
          "kind": "keyword",
          "text": "where"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "typeIdentifier",
          "text": "Content"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:7SwiftUI4ViewP",
          "text": "View"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/SwiftUI/NavigationView",
      "kind": "symbol",
      "role": "symbol",
      "title": "NavigationView",
      "type": "topic",
      "url": "/documentation/SwiftUI/NavigationView"
    },
    "doc://com.apple.documentation/documentation/SwiftUI/Scene": {
      "abstract": [
        {
          "text": "A part of an app’s user interface with a life cycle managed by the system.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@"
        },
        {
          "kind": "attribute",
          "preciseIdentifier": "s:ScM",
          "text": "MainActor"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "attribute",
          "text": "@preconcurrency"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Scene"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/SwiftUI/Scene",
      "kind": "symbol",
      "role": "symbol",
      "title": "Scene",
      "type": "topic",
      "url": "/documentation/SwiftUI/Scene"
    },
    "doc://com.apple.documentation/documentation/SwiftUI/Scene/backgroundTask(_:action:)": {
      "abstract": [
        {
          "text": "Runs the specified action when the system provides a background task.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "nonisolated"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "backgroundTask"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "genericParameter",
          "text": "D"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "genericParameter",
          "text": "R"
        },
        {
          "kind": "text",
          "text": ">("
        },
        {
          "kind": "externalParam",
          "text": "_"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "internalParam",
          "text": "task"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:7SwiftUI14BackgroundTaskV",
          "text": "BackgroundTask"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "text": "D"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "text": "R"
        },
        {
          "kind": "text",
          "text": ">, "
        },
        {
          "kind": "externalParam",
          "text": "action"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "keyword",
          "text": "@escaping"
        },
        {
          "kind": "text",
          "text": " ("
        },
        {
          "kind": "typeIdentifier",
          "text": "D"
        },
        {
          "kind": "text",
          "text": ") "
        },
        {
          "kind": "keyword",
          "text": "async"
        },
        {
          "kind": "text",
          "text": " -> "
        },
        {
          "kind": "typeIdentifier",
          "text": "R"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "keyword",
          "text": "some"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:7SwiftUI5SceneP",
          "text": "Scene"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "where"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "typeIdentifier",
          "text": "D"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s8SendableP",
          "text": "Sendable"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "text": "R"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s8SendableP",
          "text": "Sendable"
        },
        {
          "kind": "text",
          "text": "\n"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/SwiftUI/Scene/backgroundTask(_:action:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "backgroundTask(_:action:)",
      "type": "topic",
      "url": "/documentation/SwiftUI/Scene/backgroundTask(_:action:)"
    },
    "doc://com.apple.documentation/documentation/SwiftUI/View/onChange(of:perform:)": {
      "abstract": [
        {
          "text": "Adds an action to perform when the given value changes.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "attribute",
          "text": "nonisolated"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "onChange"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "genericParameter",
          "text": "V"
        },
        {
          "kind": "text",
          "text": ">("
        },
        {
          "kind": "externalParam",
          "text": "of"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "internalParam",
          "text": "value"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "text": "V"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "perform"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "internalParam",
          "text": "action"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "keyword",
          "text": "@escaping"
        },
        {
          "kind": "text",
          "text": " ("
        },
        {
          "kind": "typeIdentifier",
          "text": "V"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s4Voida",
          "text": "Void"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "keyword",
          "text": "some"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:7SwiftUI4ViewP",
          "text": "View"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "where"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "typeIdentifier",
          "text": "V"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SQ",
          "text": "Equatable"
        },
        {
          "kind": "text",
          "text": "\n"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/SwiftUI/View/onChange(of:perform:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "onChange(of:perform:)",
      "type": "topic",
      "url": "/documentation/SwiftUI/View/onChange(of:perform:)"
    },
    "doc://com.apple.documentation/documentation/SwiftUI/View/onContinueUserActivity(_:perform:)": {
      "abstract": [
        {
          "text": "Registers a handler to invoke in response to a user activity that your app receives.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "nonisolated"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "onContinueUserActivity"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "_"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "internalParam",
          "text": "activityType"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "perform"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "internalParam",
          "text": "action"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "keyword",
          "text": "@escaping"
        },
        {
          "kind": "text",
          "text": " ("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSUserActivity",
          "text": "NSUserActivity"
        },
        {
          "kind": "text",
          "text": ") -> ()) -> "
        },
        {
          "kind": "keyword",
          "text": "some"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:7SwiftUI4ViewP",
          "text": "View"
        },
        {
          "kind": "text",
          "text": "\n"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/SwiftUI/View/onContinueUserActivity(_:perform:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "onContinueUserActivity(_:perform:)",
      "type": "topic",
      "url": "/documentation/SwiftUI/View/onContinueUserActivity(_:perform:)"
    },
    "doc://com.apple.documentation/documentation/SwiftUI/WKApplicationDelegateAdaptor": {
      "abstract": [
        {
          "text": "A property wrapper that is used in `App` to provide a delegate from WatchKit.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@"
        },
        {
          "kind": "attribute",
          "preciseIdentifier": "s:ScM",
          "text": "MainActor"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "attribute",
          "text": "@preconcurrency"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "attribute",
          "text": "@propertyWrapper"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "WKApplicationDelegateAdaptor"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "genericParameter",
          "text": "DelegateType"
        },
        {
          "kind": "text",
          "text": "> "
        },
        {
          "kind": "keyword",
          "text": "where"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "typeIdentifier",
          "text": "DelegateType"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSObject",
          "text": "NSObject"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "text": "DelegateType"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(pl)WKApplicationDelegate",
          "text": "WKApplicationDelegate"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/SwiftUI/WKApplicationDelegateAdaptor",
      "kind": "symbol",
      "role": "symbol",
      "title": "WKApplicationDelegateAdaptor",
      "type": "topic",
      "url": "/documentation/SwiftUI/WKApplicationDelegateAdaptor"
    },
    "doc://com.apple.documentation/documentation/SwiftUI/WKUserNotificationHostingController": {
      "abstract": [
        {
          "text": "A WatchKit user notification interface controller that hosts a SwiftUI view hierarchy.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@"
        },
        {
          "kind": "attribute",
          "preciseIdentifier": "s:ScM",
          "text": "MainActor"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "attribute",
          "text": "@preconcurrency"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "WKUserNotificationHostingController"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "genericParameter",
          "text": "Body"
        },
        {
          "kind": "text",
          "text": "> "
        },
        {
          "kind": "keyword",
          "text": "where"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "typeIdentifier",
          "text": "Body"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:7SwiftUI4ViewP",
          "text": "View"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/SwiftUI/WKUserNotificationHostingController",
      "kind": "symbol",
      "role": "symbol",
      "title": "WKUserNotificationHostingController",
      "type": "topic",
      "url": "/documentation/SwiftUI/WKUserNotificationHostingController"
    },
    "doc://com.apple.documentation/documentation/SwiftUI/WindowGroup": {
      "abstract": [
        {
          "text": "A scene that presents a group of identically structured windows.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "WindowGroup"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "genericParameter",
          "text": "Content"
        },
        {
          "kind": "text",
          "text": "> "
        },
        {
          "kind": "keyword",
          "text": "where"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "typeIdentifier",
          "text": "Content"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:7SwiftUI4ViewP",
          "text": "View"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/SwiftUI/WindowGroup",
      "kind": "symbol",
      "role": "symbol",
      "title": "WindowGroup",
      "type": "topic",
      "url": "/documentation/SwiftUI/WindowGroup"
    },
    "doc://com.apple.documentation/documentation/Updates/watchos": {
      "abstract": [
        {
          "text": "Learn about important changes to watchOS.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/Updates/watchos",
      "kind": "article",
      "role": "article",
      "title": "watchOS updates",
      "type": "topic",
      "url": "/documentation/Updates/watchos"
    },
    "doc://com.apple.documentation/documentation/WatchKit/WKApplicationDelegate": {
      "abstract": [
        {
          "text": "A collection of methods that manages the app-level behavior for a single-target watchOS app.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@"
        },
        {
          "kind": "attribute",
          "preciseIdentifier": "s:ScM",
          "text": "MainActor"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "WKApplicationDelegate"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(pl)NSObject",
          "text": "NSObjectProtocol"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/WatchKit/WKApplicationDelegate",
      "kind": "symbol",
      "role": "symbol",
      "title": "WKApplicationDelegate",
      "type": "topic",
      "url": "/documentation/WatchKit/WKApplicationDelegate"
    },
    "doc://com.apple.documentation/documentation/WatchKit/WKApplicationDelegate/applicationDidFinishLaunching()": {
      "abstract": [
        {
          "text": "Tells the delegate that the launch process is almost done and the app is almost ready to run.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@"
        },
        {
          "kind": "attribute",
          "preciseIdentifier": "s:ScM",
          "text": "MainActor"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "optional"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "applicationDidFinishLaunching"
        },
        {
          "kind": "text",
          "text": "()"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/WatchKit/WKApplicationDelegate/applicationDidFinishLaunching()",
      "kind": "symbol",
      "role": "symbol",
      "title": "applicationDidFinishLaunching()",
      "type": "topic",
      "url": "/documentation/WatchKit/WKApplicationDelegate/applicationDidFinishLaunching()"
    },
    "doc://com.apple.documentation/documentation/WatchKit/WKInterfaceTable": {
      "abstract": [
        {
          "text": "An object that creates and manages the contents of a single-column table interface.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "WKInterfaceTable"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/WatchKit/WKInterfaceTable",
      "kind": "symbol",
      "role": "symbol",
      "title": "WKInterfaceTable",
      "type": "topic",
      "url": "/documentation/WatchKit/WKInterfaceTable"
    },
    "doc://com.apple.documentation/documentation/WatchKit/handling-common-state-transitions": {
      "abstract": [
        {
          "text": "Detect and respond to common state transitions.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/WatchKit/handling-common-state-transitions",
      "kind": "article",
      "role": "article",
      "title": "Handling Common State Transitions",
      "type": "topic",
      "url": "/documentation/WatchKit/handling-common-state-transitions"
    },
    "doc://com.apple.documentation/documentation/WatchKit/handling-user-activity": {
      "abstract": [
        {
          "text": "Detect and respond to user activity information from Handoff or a complication.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/WatchKit/handling-user-activity",
      "kind": "article",
      "role": "article",
      "title": "Handling User Activity",
      "type": "topic",
      "url": "/documentation/WatchKit/handling-user-activity"
    },
    "doc://com.apple.documentation/documentation/WatchKit/life-cycles": {
      "abstract": [
        {
          "text": "Receive and respond to life-cycle notifications.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/WatchKit/life-cycles",
      "kind": "article",
      "role": "article",
      "title": "Life cycles",
      "type": "topic",
      "url": "/documentation/WatchKit/life-cycles"
    },
    "doc://com.apple.documentation/documentation/WatchKit/using-background-tasks": {
      "abstract": [
        {
          "text": "Handle scheduled update tasks in the background, and respond to background system interactions including Siri intents and incoming Bluetooth messages.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/WatchKit/using-background-tasks",
      "kind": "article",
      "role": "article",
      "title": "Using background tasks",
      "type": "topic",
      "url": "/documentation/WatchKit/using-background-tasks"
    },
    "doc://com.apple.documentation/documentation/foundation/nsuseractivity": {
      "abstract": [
        {
          "text": "A representation of the state of your app at a moment in time.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "class "
        },
        {
          "kind": "identifier",
          "text": "NSUserActivity"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/foundation/nsuseractivity",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSUserActivity",
      "type": "topic",
      "url": "/documentation/foundation/nsuseractivity"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.documentation/tutorials/SwiftUI": {
      "abstract": [
        {
          "text": "SwiftUI is a modern way to declare user interfaces for any Apple platform. Create beautiful, dynamic apps faster than ever before.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/tutorials/SwiftUI",
      "kind": "overview",
      "role": "overview",
      "title": "Introducing SwiftUI",
      "type": "topic",
      "url": "/tutorials/SwiftUI"
    },
    "doc://com.apple.documentation/tutorials/SwiftUI/creating-a-watchOS-app": {
      "abstract": [
        {
          "text": "This tutorial gives you a chance to apply much of what you’ve already learned about SwiftUI, and — with little effort — migrate the Landmarks app to watchOS.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/tutorials/SwiftUI/creating-a-watchOS-app",
      "kind": "project",
      "role": "project",
      "title": "Creating a watchOS app",
      "type": "topic",
      "url": "/tutorials/SwiftUI/creating-a-watchOS-app"
    },
    "doc://com.apple.watchOS-Apps/documentation/watchOS-Apps": {
      "abstract": [
        {
          "text": "Build watchOS apps that combine complications, notifications, and Siri to create",
          "type": "text"
        },
        {
          "text": " ",
          "type": "text"
        },
        {
          "text": "a personal experience on Apple Watch.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.watchOS-Apps/documentation/watchOS-Apps",
      "images": [
        {
          "identifier": "watchOSApps-PageImage-card.png",
          "type": "card"
        }
      ],
      "kind": "article",
      "role": "collection",
      "title": "watchOS apps",
      "type": "topic",
      "url": "/documentation/watchos-apps"
    },
    "doc://com.apple.watchOS-Apps/documentation/watchOS-Apps/creating-an-intuitive-and-effective-ui-in-watchos-10": {
      "abstract": [
        {
          "text": "Provide an even more streamlined, consistent, and glanceable user experience with new design features.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.watchOS-Apps/documentation/watchOS-Apps/creating-an-intuitive-and-effective-ui-in-watchos-10",
      "kind": "article",
      "role": "article",
      "title": "Creating an intuitive and effective UI in watchOS 10",
      "type": "topic",
      "url": "/documentation/watchos-apps/creating-an-intuitive-and-effective-ui-in-watchos-10"
    },
    "doc://com.apple.watchOS-Apps/documentation/watchOS-Apps/customizing-your-long-look-interface": {
      "abstract": [
        {
          "text": "Create custom interfaces for your watchOS app’s notifications.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.watchOS-Apps/documentation/watchOS-Apps/customizing-your-long-look-interface",
      "kind": "article",
      "role": "article",
      "title": "Customizing your long-look interface",
      "type": "topic",
      "url": "/documentation/watchos-apps/customizing-your-long-look-interface"
    },
    "doc://com.apple.watchOS-Apps/documentation/watchOS-Apps/updating-your-app-and-widgets-for-watchos-10": {
      "abstract": [
        {
          "text": "Integrate SwiftUI elements and watch-specific features, and build widgets for the Smart Stack.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.watchOS-Apps/documentation/watchOS-Apps/updating-your-app-and-widgets-for-watchos-10",
      "kind": "article",
      "role": "sampleCode",
      "title": "Updating your app and widgets for watchOS 10",
      "type": "topic",
      "url": "/documentation/watchos-apps/updating-your-app-and-widgets-for-watchos-10"
    },
    "https://docs.swift.org/swift-book/documentation/the-swift-programming-language/attributes": {
      "identifier": "https://docs.swift.org/swift-book/documentation/the-swift-programming-language/attributes",
      "title": "@main",
      "titleInlineContent": [
        {
          "code": "@main",
          "type": "codeVoice"
        }
      ],
      "type": "link",
      "url": "https://docs.swift.org/swift-book/documentation/the-swift-programming-language/attributes"
    },
    "watchOSApps-PageImage-card.png": {
      "alt": "A stylized representation of Apple Watch.",
      "identifier": "watchOSApps-PageImage-card.png",
      "type": "image",
      "variants": [
        {
          "traits": [
            "2x",
            "light"
          ],
          "url": "https://docs-assets.developer.apple.com/published/5e043ca96ec9c9e5579649124c448c35/watchOSApps-PageImage-card@2x.png"
        },
        {
          "traits": [
            "2x",
            "dark"
          ],
          "url": "https://docs-assets.developer.apple.com/published/2e82e5f258fb084d7b684889cabbe515/watchOSApps-PageImage-card~dark@2x.png"
        }
      ]
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Related-Documentation",
      "identifiers": [
        "doc://com.apple.documentation/tutorials/SwiftUI/creating-a-watchOS-app",
        "doc://com.apple.documentation/documentation/WatchKit/life-cycles"
      ],
      "title": "Related Documentation"
    },
    {
      "anchor": "Essentials",
      "generated": true,
      "identifiers": [
        "doc://com.apple.watchOS-Apps/documentation/watchOS-Apps/creating-an-intuitive-and-effective-ui-in-watchos-10",
        "doc://com.apple.watchOS-Apps/documentation/watchOS-Apps/updating-your-app-and-widgets-for-watchos-10",
        "doc://com.apple.documentation/documentation/Updates/watchos"
      ],
      "title": "Essentials"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1WatchKit~1WKInterfaceTable/fragments",
          "value": [
            {
              "kind": "keyword",
              "text": "@interface"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "WKInterfaceTable"
            },
            {
              "kind": "text",
              "text": " : "
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)WKInterfaceObject",
              "text": "WKInterfaceObject"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1WatchKit~1WKApplicationDelegate/fragments",
          "value": [
            {
              "kind": "keyword",
              "text": "@protocol"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "WKApplicationDelegate"
            },
            {
              "kind": "text",
              "text": " <"
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(pl)NSObject",
              "text": "NSObject"
            },
            {
              "kind": "text",
              "text": ">"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1WatchKit~1WKApplicationDelegate~1applicationDidFinishLaunching()/title",
          "value": "applicationDidFinishLaunching"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1WatchKit~1WKApplicationDelegate~1applicationDidFinishLaunching()/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- ("
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:v",
              "text": "void"
            },
            {
              "kind": "text",
              "text": ") "
            },
            {
              "kind": "identifier",
              "text": "applicationDidFinishLaunching"
            },
            {
              "kind": "text",
              "text": ";"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
