{
  "abstract": [
    {
      "text": "Send requests from your app when it’s running in the background.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.watchOS-Apps/documentation/watchOS-Apps"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.watchOS-Apps/documentation/watchOS-Apps/making-background-requests"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "role": "article",
    "roleHeading": "Article",
    "title": "Making background requests"
  },
  "primaryContentSections": [
    {
      "content": [
        {
          "anchor": "Overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Use background requests when your app is running in the background or about to become",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "inactive.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "To create a background session:",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "items": [
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Create a background configuration by calling the ",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.documentation/documentation/foundation/urlsessionconfiguration/1411521-backgroundsessionconfiguration",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": " ",
                      "type": "text"
                    },
                    {
                      "text": "method on the ",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.documentation/documentation/foundation/urlsessionconfiguration",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": " ",
                      "type": "text"
                    },
                    {
                      "text": "class.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Create a background session by calling the ",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.documentation/documentation/foundation/urlsession",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": " ",
                      "type": "text"
                    },
                    {
                      "text": "class’s ",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.documentation/documentation/foundation/urlsession/1411597-init",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": " ",
                      "type": "text"
                    },
                    {
                      "text": "initializer, passing both the background configuration and a session delegate. Background",
                      "type": "text"
                    },
                    {
                      "text": " ",
                      "type": "text"
                    },
                    {
                      "text": "sessions must have a session delegate.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Create a task to download data by calling the session object’s ",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.documentation/documentation/foundation/urlsession/1411482-downloadtask",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": " ",
                      "type": "text"
                    },
                    {
                      "text": "method.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Start the task by calling its ",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.documentation/documentation/foundation/urlsessiontask/1411121-resume",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": " ",
                      "type": "text"
                    },
                    {
                      "text": "method.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Implement your WatchKit extension delegate’s ",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.documentation/documentation/WatchKit/WKExtensionDelegate/handle(_:)-92ulv",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": " ",
                      "type": "text"
                    },
                    {
                      "text": "method to respond to (and complete) the WatchKit background task. For more information,",
                      "type": "text"
                    },
                    {
                      "text": " ",
                      "type": "text"
                    },
                    {
                      "text": "see ",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.documentation/documentation/WatchKit/WKURLSessionRefreshBackgroundTask",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": ".",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Implement the session delegate’s methods to receive data and notifications from",
                      "type": "text"
                    },
                    {
                      "text": " ",
                      "type": "text"
                    },
                    {
                      "text": "the session. For more information, see ",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.documentation/documentation/foundation/urlsessiondelegate",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": ".",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            }
          ],
          "type": "orderedList"
        },
        {
          "inlineContent": [
            {
              "text": "Unlike default and ephemeral sessions, a background session persists even if your",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "watchOS app closes. If your app is still the frontmost app, the system wakes your",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "app as soon as it receives a response. Otherwise, the system may defer delivering",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "the response to your app, based on system resources. If the response hasn’t been",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "delivered yet, it’s delivered the next time your app becomes active.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "Background sessions may be deferred based on the system’s state, network connectivity,",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "and other issues. When making a background request, smaller transfers are better.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "For more information on working with WatchKit background tasks, see ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/WatchKit/background-execution",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ".",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/WatchKit/WKExtensionDelegate/handle(_:)-92ulv": {
      "abstract": [
        {
          "text": "Tells the delegate that the app has received one or more background tasks.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@"
        },
        {
          "kind": "attribute",
          "preciseIdentifier": "s:ScM",
          "text": "MainActor"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "optional"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "handle"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "_"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "internalParam",
          "text": "backgroundTasks"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sh",
          "text": "Set"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)WKRefreshBackgroundTask",
          "text": "WKRefreshBackgroundTask"
        },
        {
          "kind": "text",
          "text": ">)"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/WatchKit/WKExtensionDelegate/handle(_:)-92ulv",
      "kind": "symbol",
      "role": "symbol",
      "title": "handle(_:)",
      "type": "topic",
      "url": "/documentation/WatchKit/WKExtensionDelegate/handle(_:)-92ulv"
    },
    "doc://com.apple.documentation/documentation/WatchKit/WKURLSessionRefreshBackgroundTask": {
      "abstract": [
        {
          "text": "A task that responds to background URL sessions.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "WKURLSessionRefreshBackgroundTask"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/WatchKit/WKURLSessionRefreshBackgroundTask",
      "kind": "symbol",
      "role": "symbol",
      "title": "WKURLSessionRefreshBackgroundTask",
      "type": "topic",
      "url": "/documentation/WatchKit/WKURLSessionRefreshBackgroundTask"
    },
    "doc://com.apple.documentation/documentation/WatchKit/background-execution": {
      "abstract": [
        {
          "text": "Manage background sessions and tasks.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/WatchKit/background-execution",
      "kind": "article",
      "role": "article",
      "title": "Background execution",
      "type": "topic",
      "url": "/documentation/WatchKit/background-execution"
    },
    "doc://com.apple.documentation/documentation/foundation/urlsession": {
      "abstract": [
        {
          "text": "An object that coordinates a group of related, network data transfer tasks.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "class "
        },
        {
          "kind": "identifier",
          "text": "URLSession"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/foundation/urlsession",
      "kind": "symbol",
      "role": "symbol",
      "title": "URLSession",
      "type": "topic",
      "url": "/documentation/foundation/urlsession"
    },
    "doc://com.apple.documentation/documentation/foundation/urlsession/1411482-downloadtask": {
      "abstract": [
        {
          "text": "Creates a download task that retrieves the contents of the specified URL and saves the results to a file.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "func "
        },
        {
          "kind": "identifier",
          "text": "downloadTask"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "identifier",
          "text": "with"
        },
        {
          "kind": "text",
          "text": ": URL) -> URLSessionDownloadTask"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/foundation/urlsession/1411482-downloadtask",
      "kind": "symbol",
      "role": "symbol",
      "title": "downloadTask(with:)",
      "type": "topic",
      "url": "/documentation/foundation/urlsession/1411482-downloadtask"
    },
    "doc://com.apple.documentation/documentation/foundation/urlsession/1411597-init": {
      "abstract": [
        {
          "text": "Creates a session with the specified session configuration, delegate, and operation queue.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "identifier",
          "text": "configuration"
        },
        {
          "kind": "text",
          "text": ": URLSessionConfiguration, "
        },
        {
          "kind": "identifier",
          "text": "delegate"
        },
        {
          "kind": "text",
          "text": ": (any URLSessionDelegate)?, "
        },
        {
          "kind": "identifier",
          "text": "delegateQueue"
        },
        {
          "kind": "text",
          "text": ": OperationQueue?)"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/foundation/urlsession/1411597-init",
      "kind": "symbol",
      "role": "symbol",
      "title": "init(configuration:delegate:delegateQueue:)",
      "type": "topic",
      "url": "/documentation/foundation/urlsession/1411597-init"
    },
    "doc://com.apple.documentation/documentation/foundation/urlsessionconfiguration": {
      "abstract": [
        {
          "text": "A configuration object that defines behavior and policies for a URL session.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "class "
        },
        {
          "kind": "identifier",
          "text": "URLSessionConfiguration"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/foundation/urlsessionconfiguration",
      "kind": "symbol",
      "role": "symbol",
      "title": "URLSessionConfiguration",
      "type": "topic",
      "url": "/documentation/foundation/urlsessionconfiguration"
    },
    "doc://com.apple.documentation/documentation/foundation/urlsessionconfiguration/1411521-backgroundsessionconfiguration": {
      "abstract": [
        {
          "text": "Returns a session configuration object that allows HTTP and HTTPS uploads or downloads to be performed in the background.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "text",
          "text": "class func "
        },
        {
          "kind": "identifier",
          "text": "backgroundSessionConfiguration"
        },
        {
          "kind": "text",
          "text": "(String) -> URLSessionConfiguration"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/foundation/urlsessionconfiguration/1411521-backgroundsessionconfiguration",
      "kind": "symbol",
      "role": "symbol",
      "title": "backgroundSessionConfiguration(_:)",
      "type": "topic",
      "url": "/documentation/foundation/urlsessionconfiguration/1411521-backgroundsessionconfiguration"
    },
    "doc://com.apple.documentation/documentation/foundation/urlsessiondelegate": {
      "abstract": [
        {
          "text": "A protocol that defines methods that URL session instances call on their delegates to handle session-level events, like session life cycle changes. ",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "protocol "
        },
        {
          "kind": "identifier",
          "text": "URLSessionDelegate"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/foundation/urlsessiondelegate",
      "kind": "symbol",
      "role": "symbol",
      "title": "URLSessionDelegate",
      "type": "topic",
      "url": "/documentation/foundation/urlsessiondelegate"
    },
    "doc://com.apple.documentation/documentation/foundation/urlsessiontask/1411121-resume": {
      "abstract": [
        {
          "text": "Resumes the task, if it is suspended.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "func "
        },
        {
          "kind": "identifier",
          "text": "resume"
        },
        {
          "kind": "text",
          "text": "()"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/foundation/urlsessiontask/1411121-resume",
      "kind": "symbol",
      "role": "symbol",
      "title": "resume()",
      "type": "topic",
      "url": "/documentation/foundation/urlsessiontask/1411121-resume"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.watchOS-Apps/documentation/watchOS-Apps": {
      "abstract": [
        {
          "text": "Build watchOS apps that combine complications, notifications, and Siri to create",
          "type": "text"
        },
        {
          "text": " ",
          "type": "text"
        },
        {
          "text": "a personal experience on Apple Watch.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.watchOS-Apps/documentation/watchOS-Apps",
      "images": [
        {
          "identifier": "watchOSApps-PageImage-card.png",
          "type": "card"
        }
      ],
      "kind": "article",
      "role": "collection",
      "title": "watchOS apps",
      "type": "topic",
      "url": "/documentation/watchos-apps"
    },
    "doc://com.apple.watchOS-Apps/documentation/watchOS-Apps/making-default-and-ephemeral-requests": {
      "abstract": [
        {
          "text": "Send requests from your app when it’s running in the foreground.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.watchOS-Apps/documentation/watchOS-Apps/making-default-and-ephemeral-requests",
      "kind": "article",
      "role": "article",
      "title": "Making default and ephemeral requests",
      "type": "topic",
      "url": "/documentation/watchos-apps/making-default-and-ephemeral-requests"
    },
    "watchOSApps-PageImage-card.png": {
      "alt": "A stylized representation of Apple Watch.",
      "identifier": "watchOSApps-PageImage-card.png",
      "type": "image",
      "variants": [
        {
          "traits": [
            "2x",
            "light"
          ],
          "url": "https://docs-assets.developer.apple.com/published/5e043ca96ec9c9e5579649124c448c35/watchOSApps-PageImage-card@2x.png"
        },
        {
          "traits": [
            "2x",
            "dark"
          ],
          "url": "https://docs-assets.developer.apple.com/published/2e82e5f258fb084d7b684889cabbe515/watchOSApps-PageImage-card~dark@2x.png"
        }
      ]
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Network-requests",
      "generated": true,
      "identifiers": [
        "doc://com.apple.watchOS-Apps/documentation/watchOS-Apps/making-default-and-ephemeral-requests"
      ],
      "title": "Network requests"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1foundation~1urlsessionconfiguration/title",
          "value": "NSURLSessionConfiguration"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1WatchKit~1WKURLSessionRefreshBackgroundTask/fragments",
          "value": [
            {
              "kind": "keyword",
              "text": "@interface"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "WKURLSessionRefreshBackgroundTask"
            },
            {
              "kind": "text",
              "text": " : "
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)WKRefreshBackgroundTask",
              "text": "WKRefreshBackgroundTask"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1foundation~1urlsessionconfiguration~11411521-backgroundsessionconfiguration/title",
          "value": "backgroundSessionConfiguration:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1foundation~1urlsessiontask~11411121-resume/title",
          "value": "resume"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1foundation~1urlsession~11411597-init/title",
          "value": "sessionWithConfiguration:delegate:delegateQueue:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1foundation~1urlsession~11411482-downloadtask/title",
          "value": "downloadTaskWithURL:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1foundation~1urlsessiondelegate/title",
          "value": "NSURLSessionDelegate"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1foundation~1urlsession/title",
          "value": "NSURLSession"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1WatchKit~1WKExtensionDelegate~1handle(_:)-92ulv/title",
          "value": "handleBackgroundTasks:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1WatchKit~1WKExtensionDelegate~1handle(_:)-92ulv/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- ("
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:v",
              "text": "void"
            },
            {
              "kind": "text",
              "text": ") "
            },
            {
              "kind": "identifier",
              "text": "handleBackgroundTasks:"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:Q$objc(cs)NSSet",
              "text": "NSSet<WKRefreshBackgroundTask *>"
            },
            {
              "kind": "text",
              "text": " *) "
            },
            {
              "kind": "internalParam",
              "text": "backgroundTasks"
            },
            {
              "kind": "text",
              "text": ";"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
