{
  "abstract": [
    {
      "text": "Integrate SwiftUI elements and watch-specific features, and build widgets for the Smart Stack.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.watchOS-Apps/documentation/watchOS-Apps"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.watchOS-Apps/documentation/watchOS-Apps/updating-your-app-and-widgets-for-watchos-10"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "platforms": [
      {
        "beta": false,
        "introducedAt": "17.0",
        "name": "iOS"
      },
      {
        "beta": false,
        "introducedAt": "17.0",
        "name": "iPadOS"
      },
      {
        "beta": false,
        "introducedAt": "14.0",
        "name": "macOS"
      },
      {
        "beta": false,
        "introducedAt": "10.0",
        "name": "watchOS"
      },
      {
        "beta": false,
        "introducedAt": "15.0",
        "name": "Xcode"
      }
    ],
    "role": "sampleCode",
    "roleHeading": "Sample Code",
    "title": "Updating your app and widgets for watchOS 10"
  },
  "primaryContentSections": [
    {
      "content": [
        {
          "anchor": "Overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "watchOS 10 introduces a redesigned user interface to surface timely information, communicate",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "focused content at a glance, and make navigation consistent and predictable. This sample code project demonstrates",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "how to update your app and widgets for watchOS 10.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "This sample code project is associated with WWDC23 sessions 10031:",
                  "type": "text"
                },
                {
                  "text": " ",
                  "type": "text"
                },
                {
                  "identifier": "https://developer.apple.com/wwdc23/10031/",
                  "isActive": true,
                  "type": "reference"
                },
                {
                  "text": " and",
                  "type": "text"
                },
                {
                  "text": " ",
                  "type": "text"
                },
                {
                  "text": "10029: ",
                  "type": "text"
                },
                {
                  "identifier": "https://developer.apple.com/wwdc23/10029/",
                  "isActive": true,
                  "type": "reference"
                },
                {
                  "text": ". It’s based on the ",
                  "type": "text"
                },
                {
                  "identifier": "doc://com.apple.documentation/documentation/SwiftUI/Backyard-birds-sample",
                  "isActive": true,
                  "overridingTitle": "Backyard Birds",
                  "overridingTitleInlineContent": [
                    {
                      "text": "Backyard Birds",
                      "type": "text"
                    }
                  ],
                  "type": "reference"
                },
                {
                  "text": " sample.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "Note",
          "style": "note",
          "type": "aside"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "Backyard-Birds-intro.png": {
      "alt": null,
      "identifier": "Backyard-Birds-intro.png",
      "type": "image",
      "variants": [
        {
          "traits": [
            "2x",
            "light"
          ],
          "url": "https://docs-assets.developer.apple.com/published/308516255a4b167225a334a5a55a1ff3/Backyard-Birds-intro@2x.png"
        }
      ]
    },
    "bfbf1e340b52/UpdatingYourAppAndWidgetsForWatchOS10.zip": {
      "checksum": "bfbf1e340b52a4fced6a6f2f9b690301c0d9d1e0b7461e349c7de1c971fc20446c1eeb593084c6ecf9fabbad3ae0441c062c596f79a079e842a59cadcaa73602",
      "identifier": "bfbf1e340b52/UpdatingYourAppAndWidgetsForWatchOS10.zip",
      "type": "download",
      "url": "https://docs-assets.developer.apple.com/published/bfbf1e340b52/UpdatingYourAppAndWidgetsForWatchOS10.zip"
    },
    "doc://com.apple.documentation/documentation/SwiftUI/Backyard-birds-sample": {
      "abstract": [
        {
          "text": "Create an app with persistent data, interactive widgets, and an all new in-app purchase experience.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/SwiftUI/Backyard-birds-sample",
      "images": [
        {
          "identifier": "Backyard-Birds-intro.png",
          "type": "card"
        }
      ],
      "kind": "article",
      "role": "sampleCode",
      "title": "Backyard Birds: Building an app with SwiftData and widgets",
      "type": "topic",
      "url": "/documentation/SwiftUI/Backyard-birds-sample"
    },
    "doc://com.apple.documentation/documentation/Updates/watchos": {
      "abstract": [
        {
          "text": "Learn about important changes to watchOS.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/Updates/watchos",
      "kind": "article",
      "role": "article",
      "title": "watchOS updates",
      "type": "topic",
      "url": "/documentation/Updates/watchos"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.watchOS-Apps/documentation/watchOS-Apps": {
      "abstract": [
        {
          "text": "Build watchOS apps that combine complications, notifications, and Siri to create",
          "type": "text"
        },
        {
          "text": " ",
          "type": "text"
        },
        {
          "text": "a personal experience on Apple Watch.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.watchOS-Apps/documentation/watchOS-Apps",
      "images": [
        {
          "identifier": "watchOSApps-PageImage-card.png",
          "type": "card"
        }
      ],
      "kind": "article",
      "role": "collection",
      "title": "watchOS apps",
      "type": "topic",
      "url": "/documentation/watchos-apps"
    },
    "doc://com.apple.watchOS-Apps/documentation/watchOS-Apps/building_a_watchos_app": {
      "abstract": [
        {
          "text": "Set up your app’s life cycle and create its user interface with SwiftUI.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.watchOS-Apps/documentation/watchOS-Apps/building_a_watchos_app",
      "kind": "article",
      "role": "article",
      "title": "Building a watchOS app",
      "type": "topic",
      "url": "/documentation/watchos-apps/building_a_watchos_app"
    },
    "doc://com.apple.watchOS-Apps/documentation/watchOS-Apps/creating-an-intuitive-and-effective-ui-in-watchos-10": {
      "abstract": [
        {
          "text": "Provide an even more streamlined, consistent, and glanceable user experience with new design features.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.watchOS-Apps/documentation/watchOS-Apps/creating-an-intuitive-and-effective-ui-in-watchos-10",
      "kind": "article",
      "role": "article",
      "title": "Creating an intuitive and effective UI in watchOS 10",
      "type": "topic",
      "url": "/documentation/watchos-apps/creating-an-intuitive-and-effective-ui-in-watchos-10"
    },
    "https://developer.apple.com/wwdc23/10029/": {
      "identifier": "https://developer.apple.com/wwdc23/10029/",
      "title": "Build widgets for the Smart Stack on Apple Watch",
      "titleInlineContent": [
        {
          "text": "Build widgets for the Smart Stack on Apple Watch",
          "type": "text"
        }
      ],
      "type": "link",
      "url": "https://developer.apple.com/wwdc23/10029/"
    },
    "https://developer.apple.com/wwdc23/10031/": {
      "identifier": "https://developer.apple.com/wwdc23/10031/",
      "title": "Update your app for watchOS 10",
      "titleInlineContent": [
        {
          "text": "Update your app for watchOS 10",
          "type": "text"
        }
      ],
      "type": "link",
      "url": "https://developer.apple.com/wwdc23/10031/"
    },
    "watchOSApps-PageImage-card.png": {
      "alt": "A stylized representation of Apple Watch.",
      "identifier": "watchOSApps-PageImage-card.png",
      "type": "image",
      "variants": [
        {
          "traits": [
            "2x",
            "light"
          ],
          "url": "https://docs-assets.developer.apple.com/published/5e043ca96ec9c9e5579649124c448c35/watchOSApps-PageImage-card@2x.png"
        },
        {
          "traits": [
            "2x",
            "dark"
          ],
          "url": "https://docs-assets.developer.apple.com/published/2e82e5f258fb084d7b684889cabbe515/watchOSApps-PageImage-card~dark@2x.png"
        }
      ]
    }
  },
  "sampleCodeDownload": {
    "action": {
      "identifier": "bfbf1e340b52/UpdatingYourAppAndWidgetsForWatchOS10.zip",
      "isActive": true,
      "overridingTitle": "Download",
      "type": "reference"
    },
    "kind": "sampleDownload"
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Essentials",
      "generated": true,
      "identifiers": [
        "doc://com.apple.watchOS-Apps/documentation/watchOS-Apps/creating-an-intuitive-and-effective-ui-in-watchos-10",
        "doc://com.apple.watchOS-Apps/documentation/watchOS-Apps/building_a_watchos_app",
        "doc://com.apple.documentation/documentation/Updates/watchos"
      ],
      "title": "Essentials"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Essentials",
              "generated": true,
              "identifiers": [],
              "title": "Essentials"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
