{
  "abstract": [
    {
      "text": "Creates a property state with a value.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.coremediaio/documentation/CoreMediaIO",
        "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOExtensionPropertyState"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOExtensionPropertyState/init(value:)"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(cs)CMIOExtensionPropertyState(im)initWithValue:",
    "fragments": [
      {
        "kind": "keyword",
        "text": "convenience"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "init"
      },
      {
        "kind": "text",
        "text": "("
      },
      {
        "kind": "externalParam",
        "text": "value"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "text": "ObjectType"
      },
      {
        "kind": "text",
        "text": "?)"
      }
    ],
    "modules": [
      {
        "name": "Core Media I/O"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "initWithValue:"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "15.4",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "12.3",
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Initializer",
    "symbolKind": "init",
    "title": "init(value:)"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "Mac Catalyst",
            "macOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "convenience"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "keyword",
              "text": "init"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "kind": "externalParam",
              "text": "value"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "kind": "typeIdentifier",
              "text": "ObjectType"
            },
            {
              "kind": "text",
              "text": "?)"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "kind": "parameters",
      "parameters": [
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "The value to associate with the property state.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "value"
        }
      ]
    },
    {
      "content": [
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "The system supports the following value types: ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/foundation/nsdictionary",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ", ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/foundation/nsarray",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ", ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/foundation/nsstring",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ", ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/foundation/nsdata",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ", and ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/foundation/nsnumber",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ".",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.coremediaio/documentation/CoreMediaIO": {
      "abstract": [
        {
          "text": "Securely support custom camera devices in macOS.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.coremediaio/documentation/CoreMediaIO",
      "kind": "symbol",
      "role": "collection",
      "title": "Core Media I/O",
      "type": "topic",
      "url": "/documentation/coremediaio"
    },
    "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOExtensionPropertyState": {
      "abstract": [
        {
          "text": "An object that describes the state of a property.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CMIOExtensionPropertyState"
        }
      ],
      "identifier": "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOExtensionPropertyState",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CMIOExtensionPropertyState"
        }
      ],
      "role": "symbol",
      "title": "CMIOExtensionPropertyState",
      "type": "topic",
      "url": "/documentation/coremediaio/cmioextensionpropertystate"
    },
    "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOExtensionPropertyState/init(value:)": {
      "abstract": [
        {
          "text": "Creates a property state with a value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "convenience"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "value"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "text": "ObjectType"
        },
        {
          "kind": "text",
          "text": "?)"
        }
      ],
      "identifier": "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOExtensionPropertyState/init(value:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "initWithValue:"
        }
      ],
      "role": "symbol",
      "title": "init(value:)",
      "type": "topic",
      "url": "/documentation/coremediaio/cmioextensionpropertystate/init(value:)"
    },
    "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOExtensionPropertyState/init(value:attributes:)": {
      "abstract": [
        {
          "text": "Creates a property state with a value and attributes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "value"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "text": "ObjectType"
        },
        {
          "kind": "text",
          "text": "?, "
        },
        {
          "kind": "externalParam",
          "text": "attributes"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)CMIOExtensionPropertyAttributes",
          "text": "CMIOExtensionPropertyAttributes"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "text": "ObjectType"
        },
        {
          "kind": "text",
          "text": ">?)"
        }
      ],
      "identifier": "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOExtensionPropertyState/init(value:attributes:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "initWithValue:attributes:"
        }
      ],
      "role": "symbol",
      "title": "init(value:attributes:)",
      "type": "topic",
      "url": "/documentation/coremediaio/cmioextensionpropertystate/init(value:attributes:)"
    },
    "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOExtensionPropertyState/propertyStateWithValue:": {
      "abstract": [
        {
          "text": "Returns a new property state with a value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "+ "
        },
        {
          "kind": "identifier",
          "text": "propertyStateWithValue:"
        }
      ],
      "identifier": "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOExtensionPropertyState/propertyStateWithValue:",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "propertyStateWithValue:"
        }
      ],
      "role": "symbol",
      "title": "propertyStateWithValue:",
      "type": "topic",
      "url": "/documentation/coremediaio/cmioextensionpropertystate/propertystatewithvalue:"
    },
    "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOExtensionPropertyState/propertyStateWithValue:attributes:": {
      "abstract": [
        {
          "text": "Returns a new property state with a value and attributes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "+ "
        },
        {
          "kind": "identifier",
          "text": "propertyStateWithValue:attributes:"
        }
      ],
      "identifier": "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOExtensionPropertyState/propertyStateWithValue:attributes:",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "propertyStateWithValue:attributes:"
        }
      ],
      "role": "symbol",
      "title": "propertyStateWithValue:attributes:",
      "type": "topic",
      "url": "/documentation/coremediaio/cmioextensionpropertystate/propertystatewithvalue:attributes:"
    },
    "doc://com.apple.documentation/documentation/foundation/nsarray": {
      "abstract": [
        {
          "text": "An object representing a static ordered collection, for use instead of an  constant in cases that require reference semantics.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "class "
        },
        {
          "kind": "identifier",
          "text": "NSArray"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/foundation/nsarray",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSArray",
      "type": "topic",
      "url": "/documentation/foundation/nsarray"
    },
    "doc://com.apple.documentation/documentation/foundation/nsdata": {
      "abstract": [
        {
          "text": "A static byte buffer that bridges to ; use  when you need reference semantics or other Foundation-specific behavior.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "class "
        },
        {
          "kind": "identifier",
          "text": "NSData"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/foundation/nsdata",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSData",
      "type": "topic",
      "url": "/documentation/foundation/nsdata"
    },
    "doc://com.apple.documentation/documentation/foundation/nsdictionary": {
      "abstract": [
        {
          "text": "An object representing a static collection of key-value pairs, for use instead of a  constant in cases that require reference semantics.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "class "
        },
        {
          "kind": "identifier",
          "text": "NSDictionary"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/foundation/nsdictionary",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSDictionary",
      "type": "topic",
      "url": "/documentation/foundation/nsdictionary"
    },
    "doc://com.apple.documentation/documentation/foundation/nsnumber": {
      "abstract": [
        {
          "text": "An object wrapper for primitive scalar numeric values.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "class "
        },
        {
          "kind": "identifier",
          "text": "NSNumber"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/foundation/nsnumber",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSNumber",
      "type": "topic",
      "url": "/documentation/foundation/nsnumber"
    },
    "doc://com.apple.documentation/documentation/foundation/nsstring": {
      "abstract": [
        {
          "text": "A static, plain-text Unicode string object which you use when you need reference semantics or other Foundation-specific behavior. ",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "class "
        },
        {
          "kind": "identifier",
          "text": "NSString"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/foundation/nsstring",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSString",
      "type": "topic",
      "url": "/documentation/foundation/nsstring"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Creating-a-Property-State",
      "generated": true,
      "identifiers": [
        "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOExtensionPropertyState/init(value:attributes:)"
      ],
      "title": "Creating a Property State"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "15.4",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "12.3",
              "name": "macOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Instance Method"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "initWithValue:"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "method"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "initWithValue:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.coremediaio/documentation/CoreMediaIO",
                "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOExtensionPropertyState"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Creating-a-Property-State",
              "generated": true,
              "identifiers": [
                "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOExtensionPropertyState/propertyStateWithValue:",
                "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOExtensionPropertyState/propertyStateWithValue:attributes:",
                "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOExtensionPropertyState/init(value:attributes:)"
              ],
              "title": "Creating a Property State"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "Mac Catalyst",
                  "macOS"
                ],
                "tokens": [
                  {
                    "kind": "text",
                    "text": "- ("
                  },
                  {
                    "kind": "keyword",
                    "text": "instancetype"
                  },
                  {
                    "kind": "text",
                    "text": ") "
                  },
                  {
                    "kind": "identifier",
                    "text": "initWithValue:"
                  },
                  {
                    "kind": "text",
                    "text": "("
                  },
                  {
                    "kind": "keyword",
                    "text": "ObjectType"
                  },
                  {
                    "kind": "text",
                    "text": ") "
                  },
                  {
                    "kind": "internalParam",
                    "text": "value"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/1",
          "value": {
            "kind": "parameters",
            "parameters": [
              {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "The value to associate with the property state.",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ],
                "name": "value"
              }
            ]
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1foundation~1nsarray/abstract",
          "value": [
            {
              "text": "A static ordered collection of objects.",
              "type": "text"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1foundation~1nsdictionary/abstract",
          "value": [
            {
              "text": "A static collection of objects associated with unique keys.",
              "type": "text"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1CMIOExtensionPropertyState/title",
          "value": "CMIOExtensionPropertyState"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1CMIOExtensionPropertyState/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CMIOExtensionPropertyState"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1CMIOExtensionPropertyState/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CMIOExtensionPropertyState"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1CMIOExtensionPropertyState~1init(value:attributes:)/title",
          "value": "initWithValue:attributes:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1CMIOExtensionPropertyState~1init(value:attributes:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "initWithValue:attributes:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1foundation~1nsstring/abstract",
          "value": [
            {
              "text": "A static, plain-text Unicode string object.",
              "type": "text"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1CMIOExtensionPropertyState~1init(value:)/title",
          "value": "initWithValue:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1CMIOExtensionPropertyState~1init(value:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "initWithValue:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1foundation~1nsdata/abstract",
          "value": [
            {
              "text": "A static byte buffer in memory.",
              "type": "text"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/coremediaio/cmioextensionpropertystate/init(value:)"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/coremediaio/cmioextensionpropertystate/init(value:)"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
