{
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUParameterMIDIMapping"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUParameterMIDIMapping/init(mScope:mElement:mParameterID:mFlags:mSubRangeMin:mSubRangeMax:mStatus:mData1:reserved1:reserved2:reserved3:)"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "s:So22AUParameterMIDIMappingV6mScope8mElement12mParameterID6mFlags12mSubRangeMin01mhI3Max7mStatus6mData19reserved19reserved29reserved3ABs6UInt32V_A2OSo0abG0VS2fs5UInt8VA3sOtcfc",
    "fragments": [
      {
        "kind": "identifier",
        "text": "init"
      },
      {
        "kind": "text",
        "text": "("
      },
      {
        "kind": "externalParam",
        "text": "mScope"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@T@AudioUnitScope",
        "text": "AudioUnitScope"
      },
      {
        "kind": "text",
        "text": ", "
      },
      {
        "kind": "externalParam",
        "text": "mElement"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@T@AudioUnitElement",
        "text": "AudioUnitElement"
      },
      {
        "kind": "text",
        "text": ", "
      },
      {
        "kind": "externalParam",
        "text": "mParameterID"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@T@AudioUnitParameterID",
        "text": "AudioUnitParameterID"
      },
      {
        "kind": "text",
        "text": ", "
      },
      {
        "kind": "externalParam",
        "text": "mFlags"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@E@AUParameterMIDIMappingFlags",
        "text": "AUParameterMIDIMappingFlags"
      },
      {
        "kind": "text",
        "text": ", "
      },
      {
        "kind": "externalParam",
        "text": "mSubRangeMin"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@T@AudioUnitParameterValue",
        "text": "AudioUnitParameterValue"
      },
      {
        "kind": "text",
        "text": ", "
      },
      {
        "kind": "externalParam",
        "text": "mSubRangeMax"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@T@AudioUnitParameterValue",
        "text": "AudioUnitParameterValue"
      },
      {
        "kind": "text",
        "text": ", "
      },
      {
        "kind": "externalParam",
        "text": "mStatus"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "s:s5UInt8V",
        "text": "UInt8"
      },
      {
        "kind": "text",
        "text": ", "
      },
      {
        "kind": "externalParam",
        "text": "mData1"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "s:s5UInt8V",
        "text": "UInt8"
      },
      {
        "kind": "text",
        "text": ", "
      },
      {
        "kind": "externalParam",
        "text": "reserved1"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "s:s5UInt8V",
        "text": "UInt8"
      },
      {
        "kind": "text",
        "text": ", "
      },
      {
        "kind": "externalParam",
        "text": "reserved2"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "s:s5UInt8V",
        "text": "UInt8"
      },
      {
        "kind": "text",
        "text": ", "
      },
      {
        "kind": "externalParam",
        "text": "reserved3"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "s:s6UInt32V",
        "text": "UInt32"
      },
      {
        "kind": "text",
        "text": ")"
      }
    ],
    "modules": [
      {
        "name": "Audio Toolbox"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Initializer",
    "symbolKind": "init",
    "title": "init(mScope:mElement:mParameterID:mFlags:mSubRangeMin:mSubRangeMax:mStatus:mData1:reserved1:reserved2:reserved3:)"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "macOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "init"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "kind": "externalParam",
              "text": "mScope"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioUnitScope",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@AudioUnitScope",
              "text": "AudioUnitScope"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "kind": "externalParam",
              "text": "mElement"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioUnitElement",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@AudioUnitElement",
              "text": "AudioUnitElement"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "kind": "externalParam",
              "text": "mParameterID"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioUnitParameterID",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@AudioUnitParameterID",
              "text": "AudioUnitParameterID"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "kind": "externalParam",
              "text": "mFlags"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUParameterMIDIMappingFlags",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@E@AUParameterMIDIMappingFlags",
              "text": "AUParameterMIDIMappingFlags"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "kind": "externalParam",
              "text": "mSubRangeMin"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioUnitParameterValue",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@AudioUnitParameterValue",
              "text": "AudioUnitParameterValue"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "kind": "externalParam",
              "text": "mSubRangeMax"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioUnitParameterValue",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@AudioUnitParameterValue",
              "text": "AudioUnitParameterValue"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "kind": "externalParam",
              "text": "mStatus"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:s5UInt8V",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:s5UInt8V",
              "text": "UInt8"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "kind": "externalParam",
              "text": "mData1"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:s5UInt8V",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:s5UInt8V",
              "text": "UInt8"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "kind": "externalParam",
              "text": "reserved1"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:s5UInt8V",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:s5UInt8V",
              "text": "UInt8"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "kind": "externalParam",
              "text": "reserved2"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:s5UInt8V",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:s5UInt8V",
              "text": "UInt8"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "kind": "externalParam",
              "text": "reserved3"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:s6UInt32V",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:s6UInt32V",
              "text": "UInt32"
            },
            {
              "kind": "text",
              "text": ")"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox": {
      "abstract": [
        {
          "text": "Record or play audio, convert formats, parse audio streams, and configure your audio session.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox",
      "kind": "symbol",
      "role": "collection",
      "title": "Audio Toolbox",
      "type": "topic",
      "url": "/documentation/audiotoolbox"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUParameterMIDIMapping": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AUParameterMIDIMapping"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUParameterMIDIMapping",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AUParameterMIDIMapping"
        }
      ],
      "role": "symbol",
      "title": "AUParameterMIDIMapping",
      "type": "topic",
      "url": "/documentation/audiotoolbox/auparametermidimapping"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUParameterMIDIMapping/init(mScope:mElement:mParameterID:mFlags:mSubRangeMin:mSubRangeMax:mStatus:mData1:reserved1:reserved2:reserved3:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "mScope"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioUnitScope",
          "text": "AudioUnitScope"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "mElement"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioUnitElement",
          "text": "AudioUnitElement"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "mParameterID"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioUnitParameterID",
          "text": "AudioUnitParameterID"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "mFlags"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@AUParameterMIDIMappingFlags",
          "text": "AUParameterMIDIMappingFlags"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "mSubRangeMin"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioUnitParameterValue",
          "text": "AudioUnitParameterValue"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "mSubRangeMax"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioUnitParameterValue",
          "text": "AudioUnitParameterValue"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "mStatus"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5UInt8V",
          "text": "UInt8"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "mData1"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5UInt8V",
          "text": "UInt8"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "reserved1"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5UInt8V",
          "text": "UInt8"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "reserved2"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5UInt8V",
          "text": "UInt8"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "reserved3"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUParameterMIDIMapping/init(mScope:mElement:mParameterID:mFlags:mSubRangeMin:mSubRangeMax:mStatus:mData1:reserved1:reserved2:reserved3:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "init(mScope:mElement:mParameterID:mFlags:mSubRangeMin:mSubRangeMax:mStatus:mData1:reserved1:reserved2:reserved3:)",
      "type": "topic",
      "url": "/documentation/audiotoolbox/auparametermidimapping/init(mscope:melement:mparameterid:mflags:msubrangemin:msubrangemax:mstatus:mdata1:reserved1:reserved2:reserved3:)"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUParameterMIDIMappingFlags": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AUParameterMIDIMappingFlags"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUParameterMIDIMappingFlags",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AUParameterMIDIMappingFlags"
        }
      ],
      "role": "symbol",
      "title": "AUParameterMIDIMappingFlags",
      "type": "topic",
      "url": "/documentation/audiotoolbox/auparametermidimappingflags"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioUnitElement": {
      "abstract": [
        {
          "text": "The data type for an audio unit element identifier.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AudioUnitElement"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioUnitElement",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AudioUnitElement"
        }
      ],
      "role": "symbol",
      "title": "AudioUnitElement",
      "type": "topic",
      "url": "/documentation/audiotoolbox/audiounitelement"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioUnitParameterID": {
      "abstract": [
        {
          "text": "The data type for an audio unit parameter identifier.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AudioUnitParameterID"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioUnitParameterID",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AudioUnitParameterID"
        }
      ],
      "role": "symbol",
      "title": "AudioUnitParameterID",
      "type": "topic",
      "url": "/documentation/audiotoolbox/audiounitparameterid"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioUnitParameterValue": {
      "abstract": [
        {
          "text": "The data type for an audio unit parameter value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AudioUnitParameterValue"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioUnitParameterValue",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AudioUnitParameterValue"
        }
      ],
      "role": "symbol",
      "title": "AudioUnitParameterValue",
      "type": "topic",
      "url": "/documentation/audiotoolbox/audiounitparametervalue"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioUnitScope": {
      "abstract": [
        {
          "text": "The data type for audio unit scope identifiers.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AudioUnitScope"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioUnitScope",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AudioUnitScope"
        }
      ],
      "role": "symbol",
      "title": "AudioUnitScope",
      "type": "topic",
      "url": "/documentation/audiotoolbox/audiounitscope"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.externally.resolved.symbol/s:s5UInt8V": {
      "abstract": [
        {
          "text": "An 8-bit unsigned integer value type.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@frozen"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UInt8"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s5UInt8V",
      "kind": "symbol",
      "role": "symbol",
      "title": "UInt8",
      "type": "topic",
      "url": "/documentation/Swift/UInt8"
    },
    "doc://com.externally.resolved.symbol/s:s6UInt32V": {
      "abstract": [
        {
          "text": "A 32-bit unsigned integer value type.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@frozen"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UInt32"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s6UInt32V",
      "kind": "symbol",
      "role": "symbol",
      "title": "UInt32",
      "type": "topic",
      "url": "/documentation/Swift/UInt32"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AUParameterMIDIMapping/title",
          "value": "AUParameterMIDIMapping"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AUParameterMIDIMapping/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AUParameterMIDIMapping"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AUParameterMIDIMapping/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AUParameterMIDIMapping"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AUParameterMIDIMappingFlags/title",
          "value": "AUParameterMIDIMappingFlags"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AUParameterMIDIMappingFlags/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AUParameterMIDIMappingFlags"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AUParameterMIDIMappingFlags/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AUParameterMIDIMappingFlags"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioUnitParameterID/title",
          "value": "AudioUnitParameterID"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioUnitParameterID/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AudioUnitParameterID"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioUnitParameterID/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AudioUnitParameterID"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioUnitScope/title",
          "value": "AudioUnitScope"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioUnitScope/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AudioUnitScope"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioUnitScope/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AudioUnitScope"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioUnitElement/title",
          "value": "AudioUnitElement"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioUnitElement/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AudioUnitElement"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioUnitElement/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AudioUnitElement"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioUnitParameterValue/title",
          "value": "AudioUnitParameterValue"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioUnitParameterValue/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AudioUnitParameterValue"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioUnitParameterValue/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AudioUnitParameterValue"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/audiotoolbox/auparametermidimapping/init(mscope:melement:mparameterid:mflags:msubrangemin:msubrangemax:mstatus:mdata1:reserved1:reserved2:reserved3:)"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    }
  ]
}
