{
  "abstract": [
    {
      "text": "ASTC-compressed format with low-dynamic-range content, a block width of 8, and a block height of 8.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.metal/documentation/Metal",
        "doc://com.apple.metal/documentation/Metal/MTLPixelFormat"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.metal/documentation/Metal/MTLPixelFormat/astc_8x8_ldr"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@MTLPixelFormat@MTLPixelFormatASTC_8x8_LDR",
    "fragments": [
      {
        "kind": "keyword",
        "text": "case"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "astc_8x8_ldr"
      }
    ],
    "modules": [
      {
        "name": "Metal"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "MTLPixelFormatASTC_8x8_LDR"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "8.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "8.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "14.0",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "11.0",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Case",
    "symbolKind": "case",
    "title": "MTLPixelFormat.astc_8x8_ldr"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "case"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "astc_8x8_ldr"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.metal/documentation/Metal": {
      "abstract": [
        {
          "text": "Render advanced 3D graphics and compute data in parallel with graphics processors.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal",
      "kind": "symbol",
      "role": "collection",
      "title": "Metal",
      "type": "topic",
      "url": "/documentation/metal"
    },
    "doc://com.apple.metal/documentation/Metal/MTLPixelFormat": {
      "abstract": [
        {
          "text": "The data formats that describe the organization and characteristics of individual pixels in a texture.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MTLPixelFormat"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLPixelFormat",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTLPixelFormat"
        }
      ],
      "role": "symbol",
      "title": "MTLPixelFormat",
      "type": "topic",
      "url": "/documentation/metal/mtlpixelformat"
    },
    "doc://com.apple.metal/documentation/Metal/MTLPixelFormat/astc_10x10_srgb": {
      "abstract": [
        {
          "text": "ASTC-compressed format with low-dynamic-range content, conversion between sRGB and linear space, a block width of 10, and a block height of 10.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "astc_10x10_srgb"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLPixelFormat/astc_10x10_srgb",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTLPixelFormatASTC_10x10_sRGB"
        }
      ],
      "role": "symbol",
      "title": "MTLPixelFormat.astc_10x10_srgb",
      "type": "topic",
      "url": "/documentation/metal/mtlpixelformat/astc_10x10_srgb"
    },
    "doc://com.apple.metal/documentation/Metal/MTLPixelFormat/astc_10x5_srgb": {
      "abstract": [
        {
          "text": "ASTC-compressed format with low-dynamic-range content, conversion between sRGB and linear space, a block width of 10, and a block height of 5.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "astc_10x5_srgb"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLPixelFormat/astc_10x5_srgb",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTLPixelFormatASTC_10x5_sRGB"
        }
      ],
      "role": "symbol",
      "title": "MTLPixelFormat.astc_10x5_srgb",
      "type": "topic",
      "url": "/documentation/metal/mtlpixelformat/astc_10x5_srgb"
    },
    "doc://com.apple.metal/documentation/Metal/MTLPixelFormat/astc_10x6_srgb": {
      "abstract": [
        {
          "text": "ASTC-compressed format with low-dynamic-range content, conversion between sRGB and linear space, a block width of 10, and a block height of 6.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "astc_10x6_srgb"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLPixelFormat/astc_10x6_srgb",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTLPixelFormatASTC_10x6_sRGB"
        }
      ],
      "role": "symbol",
      "title": "MTLPixelFormat.astc_10x6_srgb",
      "type": "topic",
      "url": "/documentation/metal/mtlpixelformat/astc_10x6_srgb"
    },
    "doc://com.apple.metal/documentation/Metal/MTLPixelFormat/astc_10x8_srgb": {
      "abstract": [
        {
          "text": "ASTC-compressed format with low-dynamic-range content, conversion between sRGB and linear space, a block width of 10, and a block height of 8.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "astc_10x8_srgb"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLPixelFormat/astc_10x8_srgb",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTLPixelFormatASTC_10x8_sRGB"
        }
      ],
      "role": "symbol",
      "title": "MTLPixelFormat.astc_10x8_srgb",
      "type": "topic",
      "url": "/documentation/metal/mtlpixelformat/astc_10x8_srgb"
    },
    "doc://com.apple.metal/documentation/Metal/MTLPixelFormat/astc_12x10_srgb": {
      "abstract": [
        {
          "text": "ASTC-compressed format with low-dynamic-range content, conversion between sRGB and linear space, a block width of 12, and a block height of 10.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "astc_12x10_srgb"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLPixelFormat/astc_12x10_srgb",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTLPixelFormatASTC_12x10_sRGB"
        }
      ],
      "role": "symbol",
      "title": "MTLPixelFormat.astc_12x10_srgb",
      "type": "topic",
      "url": "/documentation/metal/mtlpixelformat/astc_12x10_srgb"
    },
    "doc://com.apple.metal/documentation/Metal/MTLPixelFormat/astc_12x12_srgb": {
      "abstract": [
        {
          "text": "ASTC-compressed format with low-dynamic-range content, conversion between sRGB and linear space, a block width of 12, and a block height of 12.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "astc_12x12_srgb"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLPixelFormat/astc_12x12_srgb",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTLPixelFormatASTC_12x12_sRGB"
        }
      ],
      "role": "symbol",
      "title": "MTLPixelFormat.astc_12x12_srgb",
      "type": "topic",
      "url": "/documentation/metal/mtlpixelformat/astc_12x12_srgb"
    },
    "doc://com.apple.metal/documentation/Metal/MTLPixelFormat/astc_4x4_ldr": {
      "abstract": [
        {
          "text": "ASTC-compressed format with low-dynamic-range content, a block width of 4, and a block height of 4.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "astc_4x4_ldr"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLPixelFormat/astc_4x4_ldr",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTLPixelFormatASTC_4x4_LDR"
        }
      ],
      "role": "symbol",
      "title": "MTLPixelFormat.astc_4x4_ldr",
      "type": "topic",
      "url": "/documentation/metal/mtlpixelformat/astc_4x4_ldr"
    },
    "doc://com.apple.metal/documentation/Metal/MTLPixelFormat/astc_4x4_srgb": {
      "abstract": [
        {
          "text": "ASTC-compressed format with low-dynamic-range content, conversion between sRGB and linear space, a block width of 4, and a block height of 4.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "astc_4x4_srgb"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLPixelFormat/astc_4x4_srgb",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTLPixelFormatASTC_4x4_sRGB"
        }
      ],
      "role": "symbol",
      "title": "MTLPixelFormat.astc_4x4_srgb",
      "type": "topic",
      "url": "/documentation/metal/mtlpixelformat/astc_4x4_srgb"
    },
    "doc://com.apple.metal/documentation/Metal/MTLPixelFormat/astc_5x4_srgb": {
      "abstract": [
        {
          "text": "ASTC-compressed format with low-dynamic-range content, conversion between sRGB and linear space, a block width of 5, and a block height of 4.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "astc_5x4_srgb"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLPixelFormat/astc_5x4_srgb",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTLPixelFormatASTC_5x4_sRGB"
        }
      ],
      "role": "symbol",
      "title": "MTLPixelFormat.astc_5x4_srgb",
      "type": "topic",
      "url": "/documentation/metal/mtlpixelformat/astc_5x4_srgb"
    },
    "doc://com.apple.metal/documentation/Metal/MTLPixelFormat/astc_5x5_srgb": {
      "abstract": [
        {
          "text": "ASTC-compressed format with low-dynamic-range content, conversion between sRGB and linear space, a block width of 5, and a block height of 5.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "astc_5x5_srgb"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLPixelFormat/astc_5x5_srgb",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTLPixelFormatASTC_5x5_sRGB"
        }
      ],
      "role": "symbol",
      "title": "MTLPixelFormat.astc_5x5_srgb",
      "type": "topic",
      "url": "/documentation/metal/mtlpixelformat/astc_5x5_srgb"
    },
    "doc://com.apple.metal/documentation/Metal/MTLPixelFormat/astc_6x5_srgb": {
      "abstract": [
        {
          "text": "ASTC-compressed format with low-dynamic-range content, conversion between sRGB and linear space, a block width of 6, and a block height of 5.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "astc_6x5_srgb"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLPixelFormat/astc_6x5_srgb",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTLPixelFormatASTC_6x5_sRGB"
        }
      ],
      "role": "symbol",
      "title": "MTLPixelFormat.astc_6x5_srgb",
      "type": "topic",
      "url": "/documentation/metal/mtlpixelformat/astc_6x5_srgb"
    },
    "doc://com.apple.metal/documentation/Metal/MTLPixelFormat/astc_6x6_srgb": {
      "abstract": [
        {
          "text": "ASTC-compressed format with low-dynamic-range content, conversion between sRGB and linear space, a block width of 6, and a block height of 6.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "astc_6x6_srgb"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLPixelFormat/astc_6x6_srgb",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTLPixelFormatASTC_6x6_sRGB"
        }
      ],
      "role": "symbol",
      "title": "MTLPixelFormat.astc_6x6_srgb",
      "type": "topic",
      "url": "/documentation/metal/mtlpixelformat/astc_6x6_srgb"
    },
    "doc://com.apple.metal/documentation/Metal/MTLPixelFormat/astc_8x5_srgb": {
      "abstract": [
        {
          "text": "ASTC-compressed format with low-dynamic-range content, conversion between sRGB and linear space, a block width of 8, and a block height of 5.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "astc_8x5_srgb"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLPixelFormat/astc_8x5_srgb",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTLPixelFormatASTC_8x5_sRGB"
        }
      ],
      "role": "symbol",
      "title": "MTLPixelFormat.astc_8x5_srgb",
      "type": "topic",
      "url": "/documentation/metal/mtlpixelformat/astc_8x5_srgb"
    },
    "doc://com.apple.metal/documentation/Metal/MTLPixelFormat/astc_8x6_srgb": {
      "abstract": [
        {
          "text": "ASTC-compressed format with low-dynamic-range content, conversion between sRGB and linear space, a block width of 8, and a block height of 6.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "astc_8x6_srgb"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLPixelFormat/astc_8x6_srgb",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTLPixelFormatASTC_8x6_sRGB"
        }
      ],
      "role": "symbol",
      "title": "MTLPixelFormat.astc_8x6_srgb",
      "type": "topic",
      "url": "/documentation/metal/mtlpixelformat/astc_8x6_srgb"
    },
    "doc://com.apple.metal/documentation/Metal/MTLPixelFormat/astc_8x8_ldr": {
      "abstract": [
        {
          "text": "ASTC-compressed format with low-dynamic-range content, a block width of 8, and a block height of 8.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "astc_8x8_ldr"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLPixelFormat/astc_8x8_ldr",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTLPixelFormatASTC_8x8_LDR"
        }
      ],
      "role": "symbol",
      "title": "MTLPixelFormat.astc_8x8_ldr",
      "type": "topic",
      "url": "/documentation/metal/mtlpixelformat/astc_8x8_ldr"
    },
    "doc://com.apple.metal/documentation/Metal/MTLPixelFormat/astc_8x8_srgb": {
      "abstract": [
        {
          "text": "ASTC-compressed format with low-dynamic-range content, conversion between sRGB and linear space, a block width of 8, and a block height of 8.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "astc_8x8_srgb"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLPixelFormat/astc_8x8_srgb",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTLPixelFormatASTC_8x8_sRGB"
        }
      ],
      "role": "symbol",
      "title": "MTLPixelFormat.astc_8x8_srgb",
      "type": "topic",
      "url": "/documentation/metal/mtlpixelformat/astc_8x8_srgb"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Compressed-ASTC-Pixel-Formats",
      "generated": true,
      "identifiers": [
        "doc://com.apple.metal/documentation/Metal/MTLPixelFormat/astc_4x4_srgb",
        "doc://com.apple.metal/documentation/Metal/MTLPixelFormat/astc_5x4_srgb",
        "doc://com.apple.metal/documentation/Metal/MTLPixelFormat/astc_5x5_srgb",
        "doc://com.apple.metal/documentation/Metal/MTLPixelFormat/astc_6x5_srgb",
        "doc://com.apple.metal/documentation/Metal/MTLPixelFormat/astc_6x6_srgb",
        "doc://com.apple.metal/documentation/Metal/MTLPixelFormat/astc_8x5_srgb",
        "doc://com.apple.metal/documentation/Metal/MTLPixelFormat/astc_8x6_srgb",
        "doc://com.apple.metal/documentation/Metal/MTLPixelFormat/astc_8x8_srgb",
        "doc://com.apple.metal/documentation/Metal/MTLPixelFormat/astc_10x5_srgb",
        "doc://com.apple.metal/documentation/Metal/MTLPixelFormat/astc_10x6_srgb",
        "doc://com.apple.metal/documentation/Metal/MTLPixelFormat/astc_10x8_srgb",
        "doc://com.apple.metal/documentation/Metal/MTLPixelFormat/astc_10x10_srgb",
        "doc://com.apple.metal/documentation/Metal/MTLPixelFormat/astc_12x10_srgb",
        "doc://com.apple.metal/documentation/Metal/MTLPixelFormat/astc_12x12_srgb",
        "doc://com.apple.metal/documentation/Metal/MTLPixelFormat/astc_4x4_ldr"
      ],
      "title": "Compressed ASTC Pixel Formats"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "8.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "8.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "14.0",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "11.0",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration Case"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "MTLPixelFormatASTC_8x8_LDR"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "case"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLPixelFormatASTC_8x8_LDR"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.metal/documentation/Metal",
                "doc://com.apple.metal/documentation/Metal/MTLPixelFormat"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Compressed-ASTC-Pixel-Formats",
              "generated": true,
              "identifiers": [
                "doc://com.apple.metal/documentation/Metal/MTLPixelFormat/astc_4x4_srgb",
                "doc://com.apple.metal/documentation/Metal/MTLPixelFormat/astc_5x4_srgb",
                "doc://com.apple.metal/documentation/Metal/MTLPixelFormat/astc_5x5_srgb",
                "doc://com.apple.metal/documentation/Metal/MTLPixelFormat/astc_6x5_srgb",
                "doc://com.apple.metal/documentation/Metal/MTLPixelFormat/astc_6x6_srgb",
                "doc://com.apple.metal/documentation/Metal/MTLPixelFormat/astc_8x5_srgb",
                "doc://com.apple.metal/documentation/Metal/MTLPixelFormat/astc_8x6_srgb",
                "doc://com.apple.metal/documentation/Metal/MTLPixelFormat/astc_8x8_srgb",
                "doc://com.apple.metal/documentation/Metal/MTLPixelFormat/astc_10x5_srgb",
                "doc://com.apple.metal/documentation/Metal/MTLPixelFormat/astc_10x6_srgb",
                "doc://com.apple.metal/documentation/Metal/MTLPixelFormat/astc_10x8_srgb",
                "doc://com.apple.metal/documentation/Metal/MTLPixelFormat/astc_10x10_srgb",
                "doc://com.apple.metal/documentation/Metal/MTLPixelFormat/astc_12x10_srgb",
                "doc://com.apple.metal/documentation/Metal/MTLPixelFormat/astc_12x12_srgb",
                "doc://com.apple.metal/documentation/Metal/MTLPixelFormat/astc_4x4_ldr"
              ],
              "title": "Compressed ASTC Pixel Formats"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS"
                ],
                "tokens": [
                  {
                    "kind": "identifier",
                    "text": "MTLPixelFormatASTC_8x8_LDR"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLPixelFormat~1astc_12x12_srgb/title",
          "value": "MTLPixelFormatASTC_12x12_sRGB"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLPixelFormat~1astc_12x12_srgb/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLPixelFormatASTC_12x12_sRGB"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLPixelFormat~1astc_5x4_srgb/title",
          "value": "MTLPixelFormatASTC_5x4_sRGB"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLPixelFormat~1astc_5x4_srgb/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLPixelFormatASTC_5x4_sRGB"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLPixelFormat~1astc_8x8_ldr/title",
          "value": "MTLPixelFormatASTC_8x8_LDR"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLPixelFormat~1astc_8x8_ldr/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLPixelFormatASTC_8x8_LDR"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLPixelFormat~1astc_4x4_ldr/title",
          "value": "MTLPixelFormatASTC_4x4_LDR"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLPixelFormat~1astc_4x4_ldr/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLPixelFormatASTC_4x4_LDR"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLPixelFormat~1astc_4x4_srgb/title",
          "value": "MTLPixelFormatASTC_4x4_sRGB"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLPixelFormat~1astc_4x4_srgb/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLPixelFormatASTC_4x4_sRGB"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLPixelFormat~1astc_5x5_srgb/title",
          "value": "MTLPixelFormatASTC_5x5_sRGB"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLPixelFormat~1astc_5x5_srgb/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLPixelFormatASTC_5x5_sRGB"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLPixelFormat~1astc_10x6_srgb/title",
          "value": "MTLPixelFormatASTC_10x6_sRGB"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLPixelFormat~1astc_10x6_srgb/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLPixelFormatASTC_10x6_sRGB"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLPixelFormat~1astc_6x6_srgb/title",
          "value": "MTLPixelFormatASTC_6x6_sRGB"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLPixelFormat~1astc_6x6_srgb/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLPixelFormatASTC_6x6_sRGB"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLPixelFormat~1astc_8x6_srgb/title",
          "value": "MTLPixelFormatASTC_8x6_sRGB"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLPixelFormat~1astc_8x6_srgb/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLPixelFormatASTC_8x6_sRGB"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLPixelFormat/title",
          "value": "MTLPixelFormat"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLPixelFormat/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLPixelFormat"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLPixelFormat/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLPixelFormat"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLPixelFormat~1astc_8x8_srgb/title",
          "value": "MTLPixelFormatASTC_8x8_sRGB"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLPixelFormat~1astc_8x8_srgb/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLPixelFormatASTC_8x8_sRGB"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLPixelFormat~1astc_12x10_srgb/title",
          "value": "MTLPixelFormatASTC_12x10_sRGB"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLPixelFormat~1astc_12x10_srgb/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLPixelFormatASTC_12x10_sRGB"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLPixelFormat~1astc_10x10_srgb/title",
          "value": "MTLPixelFormatASTC_10x10_sRGB"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLPixelFormat~1astc_10x10_srgb/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLPixelFormatASTC_10x10_sRGB"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLPixelFormat~1astc_8x5_srgb/title",
          "value": "MTLPixelFormatASTC_8x5_sRGB"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLPixelFormat~1astc_8x5_srgb/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLPixelFormatASTC_8x5_sRGB"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLPixelFormat~1astc_6x5_srgb/title",
          "value": "MTLPixelFormatASTC_6x5_sRGB"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLPixelFormat~1astc_6x5_srgb/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLPixelFormatASTC_6x5_sRGB"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLPixelFormat~1astc_10x5_srgb/title",
          "value": "MTLPixelFormatASTC_10x5_sRGB"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLPixelFormat~1astc_10x5_srgb/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLPixelFormatASTC_10x5_sRGB"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLPixelFormat~1astc_10x8_srgb/title",
          "value": "MTLPixelFormatASTC_10x8_sRGB"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLPixelFormat~1astc_10x8_srgb/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLPixelFormatASTC_10x8_sRGB"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/metal/mtlpixelformat/astc_8x8_ldr"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/metal/mtlpixelformat/astc_8x8_ldr"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
