{
  "abstract": [
    {
      "text": "Packed 16-bit format with normalized unsigned integer color components: 5 bits for blue, 6 bits for green, 5 bits for red, packed into 16 bits.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.metal/documentation/Metal",
        "doc://com.apple.metal/documentation/Metal/MTLPixelFormat"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.metal/documentation/Metal/MTLPixelFormat/b5g6r5Unorm"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@MTLPixelFormat@MTLPixelFormatB5G6R5Unorm",
    "fragments": [
      {
        "kind": "keyword",
        "text": "case"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "b5g6r5Unorm"
      }
    ],
    "modules": [
      {
        "name": "Metal"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "MTLPixelFormatB5G6R5Unorm"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "8.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "8.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "14.0",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "11.0",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Case",
    "symbolKind": "case",
    "title": "MTLPixelFormat.b5g6r5Unorm"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "case"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "b5g6r5Unorm"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "kind": "mentions",
      "mentions": [
        "doc://com.apple.metal/documentation/Metal/developing-metal-apps-that-run-in-simulator"
      ]
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.metal/documentation/Metal": {
      "abstract": [
        {
          "text": "Render advanced 3D graphics and compute data in parallel with graphics processors.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal",
      "kind": "symbol",
      "role": "collection",
      "title": "Metal",
      "type": "topic",
      "url": "/documentation/metal"
    },
    "doc://com.apple.metal/documentation/Metal/MTLPixelFormat": {
      "abstract": [
        {
          "text": "The data formats that describe the organization and characteristics of individual pixels in a texture.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MTLPixelFormat"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLPixelFormat",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTLPixelFormat"
        }
      ],
      "role": "symbol",
      "title": "MTLPixelFormat",
      "type": "topic",
      "url": "/documentation/metal/mtlpixelformat"
    },
    "doc://com.apple.metal/documentation/Metal/MTLPixelFormat/a1bgr5Unorm": {
      "abstract": [
        {
          "text": "Packed 16-bit format with normalized unsigned integer color components: 5 bits each for BGR and 1 for alpha, packed into 16 bits.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "a1bgr5Unorm"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLPixelFormat/a1bgr5Unorm",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTLPixelFormatA1BGR5Unorm"
        }
      ],
      "role": "symbol",
      "title": "MTLPixelFormat.a1bgr5Unorm",
      "type": "topic",
      "url": "/documentation/metal/mtlpixelformat/a1bgr5unorm"
    },
    "doc://com.apple.metal/documentation/Metal/MTLPixelFormat/abgr4Unorm": {
      "abstract": [
        {
          "text": "Packed 16-bit format with normalized unsigned integer color components: 4 bits each for ABGR, packed into 16 bits.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "abgr4Unorm"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLPixelFormat/abgr4Unorm",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTLPixelFormatABGR4Unorm"
        }
      ],
      "role": "symbol",
      "title": "MTLPixelFormat.abgr4Unorm",
      "type": "topic",
      "url": "/documentation/metal/mtlpixelformat/abgr4unorm"
    },
    "doc://com.apple.metal/documentation/Metal/MTLPixelFormat/b5g6r5Unorm": {
      "abstract": [
        {
          "text": "Packed 16-bit format with normalized unsigned integer color components: 5 bits for blue, 6 bits for green, 5 bits for red, packed into 16 bits.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "b5g6r5Unorm"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLPixelFormat/b5g6r5Unorm",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTLPixelFormatB5G6R5Unorm"
        }
      ],
      "role": "symbol",
      "title": "MTLPixelFormat.b5g6r5Unorm",
      "type": "topic",
      "url": "/documentation/metal/mtlpixelformat/b5g6r5unorm"
    },
    "doc://com.apple.metal/documentation/Metal/MTLPixelFormat/bgr5A1Unorm": {
      "abstract": [
        {
          "text": "Packed 16-bit format with normalized unsigned integer color components: 5 bits each for BGR and 1 for alpha, packed into 16 bits.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "bgr5A1Unorm"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLPixelFormat/bgr5A1Unorm",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTLPixelFormatBGR5A1Unorm"
        }
      ],
      "role": "symbol",
      "title": "MTLPixelFormat.bgr5A1Unorm",
      "type": "topic",
      "url": "/documentation/metal/mtlpixelformat/bgr5a1unorm"
    },
    "doc://com.apple.metal/documentation/Metal/developing-metal-apps-that-run-in-simulator": {
      "abstract": [
        {
          "text": "Prototype and test your Metal apps in Simulator.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/developing-metal-apps-that-run-in-simulator",
      "kind": "article",
      "role": "article",
      "title": "Developing Metal apps that run in Simulator",
      "type": "topic",
      "url": "/documentation/metal/developing-metal-apps-that-run-in-simulator"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Packed-16-Bit-Pixel-Formats",
      "generated": true,
      "identifiers": [
        "doc://com.apple.metal/documentation/Metal/MTLPixelFormat/a1bgr5Unorm",
        "doc://com.apple.metal/documentation/Metal/MTLPixelFormat/abgr4Unorm",
        "doc://com.apple.metal/documentation/Metal/MTLPixelFormat/bgr5A1Unorm"
      ],
      "title": "Packed 16-Bit Pixel Formats"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "8.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "8.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "14.0",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "11.0",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration Case"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "MTLPixelFormatB5G6R5Unorm"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "case"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLPixelFormatB5G6R5Unorm"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.metal/documentation/Metal",
                "doc://com.apple.metal/documentation/Metal/MTLPixelFormat"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Packed-16-Bit-Pixel-Formats",
              "generated": true,
              "identifiers": [
                "doc://com.apple.metal/documentation/Metal/MTLPixelFormat/a1bgr5Unorm",
                "doc://com.apple.metal/documentation/Metal/MTLPixelFormat/abgr4Unorm",
                "doc://com.apple.metal/documentation/Metal/MTLPixelFormat/bgr5A1Unorm"
              ],
              "title": "Packed 16-Bit Pixel Formats"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS"
                ],
                "tokens": [
                  {
                    "kind": "identifier",
                    "text": "MTLPixelFormatB5G6R5Unorm"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLPixelFormat~1abgr4Unorm/title",
          "value": "MTLPixelFormatABGR4Unorm"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLPixelFormat~1abgr4Unorm/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLPixelFormatABGR4Unorm"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLPixelFormat/title",
          "value": "MTLPixelFormat"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLPixelFormat/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLPixelFormat"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLPixelFormat/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLPixelFormat"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLPixelFormat~1bgr5A1Unorm/title",
          "value": "MTLPixelFormatBGR5A1Unorm"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLPixelFormat~1bgr5A1Unorm/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLPixelFormatBGR5A1Unorm"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLPixelFormat~1a1bgr5Unorm/title",
          "value": "MTLPixelFormatA1BGR5Unorm"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLPixelFormat~1a1bgr5Unorm/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLPixelFormatA1BGR5Unorm"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLPixelFormat~1b5g6r5Unorm/title",
          "value": "MTLPixelFormatB5G6R5Unorm"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLPixelFormat~1b5g6r5Unorm/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLPixelFormatB5G6R5Unorm"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/metal/mtlpixelformat/b5g6r5unorm"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/metal/mtlpixelformat/b5g6r5unorm"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
