{
  "abstract": [
    {
      "text": "Compressed format with two 64-bit chunks. The first chunk contains two 8-bit alpha components and one 48-bit descriptor component. The second chunk contains two 16-bit color components and one 32-bit descriptor component.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.metal/documentation/Metal",
        "doc://com.apple.metal/documentation/Metal/MTLPixelFormat"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.metal/documentation/Metal/MTLPixelFormat/bc3_rgba"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@MTLPixelFormat@MTLPixelFormatBC3_RGBA",
    "fragments": [
      {
        "kind": "keyword",
        "text": "case"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "bc3_rgba"
      }
    ],
    "modules": [
      {
        "name": "Metal"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "MTLPixelFormatBC3_RGBA"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "16.4",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "16.4",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.0",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.11",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "16.4",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Case",
    "symbolKind": "case",
    "title": "MTLPixelFormat.bc3_rgba"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "case"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "bc3_rgba"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.metal/documentation/Metal": {
      "abstract": [
        {
          "text": "Render advanced 3D graphics and compute data in parallel with graphics processors.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal",
      "kind": "symbol",
      "role": "collection",
      "title": "Metal",
      "type": "topic",
      "url": "/documentation/metal"
    },
    "doc://com.apple.metal/documentation/Metal/MTLPixelFormat": {
      "abstract": [
        {
          "text": "The data formats that describe the organization and characteristics of individual pixels in a texture.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MTLPixelFormat"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLPixelFormat",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTLPixelFormat"
        }
      ],
      "role": "symbol",
      "title": "MTLPixelFormat",
      "type": "topic",
      "url": "/documentation/metal/mtlpixelformat"
    },
    "doc://com.apple.metal/documentation/Metal/MTLPixelFormat/bc1_rgba": {
      "abstract": [
        {
          "text": "Compressed format with two 16-bit color components and one 32-bit descriptor component.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "bc1_rgba"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLPixelFormat/bc1_rgba",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTLPixelFormatBC1_RGBA"
        }
      ],
      "role": "symbol",
      "title": "MTLPixelFormat.bc1_rgba",
      "type": "topic",
      "url": "/documentation/metal/mtlpixelformat/bc1_rgba"
    },
    "doc://com.apple.metal/documentation/Metal/MTLPixelFormat/bc1_rgba_srgb": {
      "abstract": [
        {
          "text": "Compressed format with two 16-bit color components and one 32-bit descriptor component, with conversion between sRGB and linear space.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "bc1_rgba_srgb"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLPixelFormat/bc1_rgba_srgb",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTLPixelFormatBC1_RGBA_sRGB"
        }
      ],
      "role": "symbol",
      "title": "MTLPixelFormat.bc1_rgba_srgb",
      "type": "topic",
      "url": "/documentation/metal/mtlpixelformat/bc1_rgba_srgb"
    },
    "doc://com.apple.metal/documentation/Metal/MTLPixelFormat/bc2_rgba": {
      "abstract": [
        {
          "text": "Compressed format with two 64-bit chunks. The first chunk contains two 8-bit alpha components and one 48-bit descriptor component. The second chunk contains two 16-bit color components and one 32-bit descriptor component.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "bc2_rgba"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLPixelFormat/bc2_rgba",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTLPixelFormatBC2_RGBA"
        }
      ],
      "role": "symbol",
      "title": "MTLPixelFormat.bc2_rgba",
      "type": "topic",
      "url": "/documentation/metal/mtlpixelformat/bc2_rgba"
    },
    "doc://com.apple.metal/documentation/Metal/MTLPixelFormat/bc2_rgba_srgb": {
      "abstract": [
        {
          "text": "Compressed format with two 64-bit chunks, with conversion between sRGB and linear space. The first chunk contains two 8-bit alpha components and one 48-bit descriptor component. The second chunk contains two 16-bit color components and one 32-bit descriptor component.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "bc2_rgba_srgb"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLPixelFormat/bc2_rgba_srgb",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTLPixelFormatBC2_RGBA_sRGB"
        }
      ],
      "role": "symbol",
      "title": "MTLPixelFormat.bc2_rgba_srgb",
      "type": "topic",
      "url": "/documentation/metal/mtlpixelformat/bc2_rgba_srgb"
    },
    "doc://com.apple.metal/documentation/Metal/MTLPixelFormat/bc3_rgba": {
      "abstract": [
        {
          "text": "Compressed format with two 64-bit chunks. The first chunk contains two 8-bit alpha components and one 48-bit descriptor component. The second chunk contains two 16-bit color components and one 32-bit descriptor component.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "bc3_rgba"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLPixelFormat/bc3_rgba",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTLPixelFormatBC3_RGBA"
        }
      ],
      "role": "symbol",
      "title": "MTLPixelFormat.bc3_rgba",
      "type": "topic",
      "url": "/documentation/metal/mtlpixelformat/bc3_rgba"
    },
    "doc://com.apple.metal/documentation/Metal/MTLPixelFormat/bc3_rgba_srgb": {
      "abstract": [
        {
          "text": "Compressed format with two 64-bit chunks, with conversion between sRGB and linear space. The first chunk contains two 8-bit alpha components and one 48-bit descriptor component. The second chunk contains two 16-bit color components and one 32-bit descriptor component.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "bc3_rgba_srgb"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLPixelFormat/bc3_rgba_srgb",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTLPixelFormatBC3_RGBA_sRGB"
        }
      ],
      "role": "symbol",
      "title": "MTLPixelFormat.bc3_rgba_srgb",
      "type": "topic",
      "url": "/documentation/metal/mtlpixelformat/bc3_rgba_srgb"
    },
    "doc://com.apple.metal/documentation/Metal/MTLPixelFormat/bc4_rSnorm": {
      "abstract": [
        {
          "text": "Compressed format with one normalized signed integer component.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "bc4_rSnorm"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLPixelFormat/bc4_rSnorm",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTLPixelFormatBC4_RSnorm"
        }
      ],
      "role": "symbol",
      "title": "MTLPixelFormat.bc4_rSnorm",
      "type": "topic",
      "url": "/documentation/metal/mtlpixelformat/bc4_rsnorm"
    },
    "doc://com.apple.metal/documentation/Metal/MTLPixelFormat/bc4_rUnorm": {
      "abstract": [
        {
          "text": "Compressed format with one normalized unsigned integer component.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "bc4_rUnorm"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLPixelFormat/bc4_rUnorm",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTLPixelFormatBC4_RUnorm"
        }
      ],
      "role": "symbol",
      "title": "MTLPixelFormat.bc4_rUnorm",
      "type": "topic",
      "url": "/documentation/metal/mtlpixelformat/bc4_runorm"
    },
    "doc://com.apple.metal/documentation/Metal/MTLPixelFormat/bc5_rgSnorm": {
      "abstract": [
        {
          "text": "Compressed format with two normalized signed integer components.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "bc5_rgSnorm"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLPixelFormat/bc5_rgSnorm",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTLPixelFormatBC5_RGSnorm"
        }
      ],
      "role": "symbol",
      "title": "MTLPixelFormat.bc5_rgSnorm",
      "type": "topic",
      "url": "/documentation/metal/mtlpixelformat/bc5_rgsnorm"
    },
    "doc://com.apple.metal/documentation/Metal/MTLPixelFormat/bc5_rgUnorm": {
      "abstract": [
        {
          "text": "Compressed format with two normalized unsigned integer components.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "bc5_rgUnorm"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLPixelFormat/bc5_rgUnorm",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTLPixelFormatBC5_RGUnorm"
        }
      ],
      "role": "symbol",
      "title": "MTLPixelFormat.bc5_rgUnorm",
      "type": "topic",
      "url": "/documentation/metal/mtlpixelformat/bc5_rgunorm"
    },
    "doc://com.apple.metal/documentation/Metal/MTLPixelFormat/bc6H_rgbFloat": {
      "abstract": [
        {
          "text": "Compressed format with four floating-point components.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "bc6H_rgbFloat"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLPixelFormat/bc6H_rgbFloat",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTLPixelFormatBC6H_RGBFloat"
        }
      ],
      "role": "symbol",
      "title": "MTLPixelFormat.bc6H_rgbFloat",
      "type": "topic",
      "url": "/documentation/metal/mtlpixelformat/bc6h_rgbfloat"
    },
    "doc://com.apple.metal/documentation/Metal/MTLPixelFormat/bc6H_rgbuFloat": {
      "abstract": [
        {
          "text": "Compressed format with four unsigned floating-point components.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "bc6H_rgbuFloat"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLPixelFormat/bc6H_rgbuFloat",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTLPixelFormatBC6H_RGBUfloat"
        }
      ],
      "role": "symbol",
      "title": "MTLPixelFormat.bc6H_rgbuFloat",
      "type": "topic",
      "url": "/documentation/metal/mtlpixelformat/bc6h_rgbufloat"
    },
    "doc://com.apple.metal/documentation/Metal/MTLPixelFormat/bc7_rgbaUnorm": {
      "abstract": [
        {
          "text": "Compressed format with four normalized unsigned integer components.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "bc7_rgbaUnorm"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLPixelFormat/bc7_rgbaUnorm",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTLPixelFormatBC7_RGBAUnorm"
        }
      ],
      "role": "symbol",
      "title": "MTLPixelFormat.bc7_rgbaUnorm",
      "type": "topic",
      "url": "/documentation/metal/mtlpixelformat/bc7_rgbaunorm"
    },
    "doc://com.apple.metal/documentation/Metal/MTLPixelFormat/bc7_rgbaUnorm_srgb": {
      "abstract": [
        {
          "text": "Compressed format with four normalized unsigned integer components, with conversion between sRGB and linear space.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "bc7_rgbaUnorm_srgb"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLPixelFormat/bc7_rgbaUnorm_srgb",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTLPixelFormatBC7_RGBAUnorm_sRGB"
        }
      ],
      "role": "symbol",
      "title": "MTLPixelFormat.bc7_rgbaUnorm_srgb",
      "type": "topic",
      "url": "/documentation/metal/mtlpixelformat/bc7_rgbaunorm_srgb"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Compressed-BC-Pixel-Formats",
      "generated": true,
      "identifiers": [
        "doc://com.apple.metal/documentation/Metal/MTLPixelFormat/bc1_rgba",
        "doc://com.apple.metal/documentation/Metal/MTLPixelFormat/bc1_rgba_srgb",
        "doc://com.apple.metal/documentation/Metal/MTLPixelFormat/bc2_rgba",
        "doc://com.apple.metal/documentation/Metal/MTLPixelFormat/bc2_rgba_srgb",
        "doc://com.apple.metal/documentation/Metal/MTLPixelFormat/bc3_rgba_srgb",
        "doc://com.apple.metal/documentation/Metal/MTLPixelFormat/bc4_rUnorm",
        "doc://com.apple.metal/documentation/Metal/MTLPixelFormat/bc4_rSnorm",
        "doc://com.apple.metal/documentation/Metal/MTLPixelFormat/bc5_rgUnorm",
        "doc://com.apple.metal/documentation/Metal/MTLPixelFormat/bc5_rgSnorm",
        "doc://com.apple.metal/documentation/Metal/MTLPixelFormat/bc6H_rgbFloat",
        "doc://com.apple.metal/documentation/Metal/MTLPixelFormat/bc6H_rgbuFloat",
        "doc://com.apple.metal/documentation/Metal/MTLPixelFormat/bc7_rgbaUnorm",
        "doc://com.apple.metal/documentation/Metal/MTLPixelFormat/bc7_rgbaUnorm_srgb"
      ],
      "title": "Compressed BC Pixel Formats"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "16.4",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "16.4",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.1",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.11",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "16.4",
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration Case"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "MTLPixelFormatBC3_RGBA"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "case"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLPixelFormatBC3_RGBA"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.metal/documentation/Metal",
                "doc://com.apple.metal/documentation/Metal/MTLPixelFormat"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Compressed-BC-Pixel-Formats",
              "generated": true,
              "identifiers": [
                "doc://com.apple.metal/documentation/Metal/MTLPixelFormat/bc1_rgba",
                "doc://com.apple.metal/documentation/Metal/MTLPixelFormat/bc1_rgba_srgb",
                "doc://com.apple.metal/documentation/Metal/MTLPixelFormat/bc2_rgba",
                "doc://com.apple.metal/documentation/Metal/MTLPixelFormat/bc2_rgba_srgb",
                "doc://com.apple.metal/documentation/Metal/MTLPixelFormat/bc3_rgba_srgb",
                "doc://com.apple.metal/documentation/Metal/MTLPixelFormat/bc4_rUnorm",
                "doc://com.apple.metal/documentation/Metal/MTLPixelFormat/bc4_rSnorm",
                "doc://com.apple.metal/documentation/Metal/MTLPixelFormat/bc5_rgUnorm",
                "doc://com.apple.metal/documentation/Metal/MTLPixelFormat/bc5_rgSnorm",
                "doc://com.apple.metal/documentation/Metal/MTLPixelFormat/bc6H_rgbFloat",
                "doc://com.apple.metal/documentation/Metal/MTLPixelFormat/bc6H_rgbuFloat",
                "doc://com.apple.metal/documentation/Metal/MTLPixelFormat/bc7_rgbaUnorm",
                "doc://com.apple.metal/documentation/Metal/MTLPixelFormat/bc7_rgbaUnorm_srgb"
              ],
              "title": "Compressed BC Pixel Formats"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS"
                ],
                "tokens": [
                  {
                    "kind": "identifier",
                    "text": "MTLPixelFormatBC3_RGBA"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLPixelFormat~1bc1_rgba_srgb/title",
          "value": "MTLPixelFormatBC1_RGBA_sRGB"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLPixelFormat~1bc1_rgba_srgb/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLPixelFormatBC1_RGBA_sRGB"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLPixelFormat~1bc6H_rgbuFloat/title",
          "value": "MTLPixelFormatBC6H_RGBUfloat"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLPixelFormat~1bc6H_rgbuFloat/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLPixelFormatBC6H_RGBUfloat"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLPixelFormat~1bc2_rgba/title",
          "value": "MTLPixelFormatBC2_RGBA"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLPixelFormat~1bc2_rgba/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLPixelFormatBC2_RGBA"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLPixelFormat~1bc3_rgba_srgb/title",
          "value": "MTLPixelFormatBC3_RGBA_sRGB"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLPixelFormat~1bc3_rgba_srgb/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLPixelFormatBC3_RGBA_sRGB"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLPixelFormat~1bc4_rSnorm/title",
          "value": "MTLPixelFormatBC4_RSnorm"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLPixelFormat~1bc4_rSnorm/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLPixelFormatBC4_RSnorm"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLPixelFormat~1bc5_rgSnorm/title",
          "value": "MTLPixelFormatBC5_RGSnorm"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLPixelFormat~1bc5_rgSnorm/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLPixelFormatBC5_RGSnorm"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLPixelFormat~1bc1_rgba/title",
          "value": "MTLPixelFormatBC1_RGBA"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLPixelFormat~1bc1_rgba/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLPixelFormatBC1_RGBA"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLPixelFormat~1bc4_rUnorm/title",
          "value": "MTLPixelFormatBC4_RUnorm"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLPixelFormat~1bc4_rUnorm/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLPixelFormatBC4_RUnorm"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLPixelFormat~1bc6H_rgbFloat/title",
          "value": "MTLPixelFormatBC6H_RGBFloat"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLPixelFormat~1bc6H_rgbFloat/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLPixelFormatBC6H_RGBFloat"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLPixelFormat~1bc7_rgbaUnorm_srgb/title",
          "value": "MTLPixelFormatBC7_RGBAUnorm_sRGB"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLPixelFormat~1bc7_rgbaUnorm_srgb/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLPixelFormatBC7_RGBAUnorm_sRGB"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLPixelFormat~1bc7_rgbaUnorm/title",
          "value": "MTLPixelFormatBC7_RGBAUnorm"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLPixelFormat~1bc7_rgbaUnorm/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLPixelFormatBC7_RGBAUnorm"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLPixelFormat/title",
          "value": "MTLPixelFormat"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLPixelFormat/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLPixelFormat"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLPixelFormat/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLPixelFormat"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLPixelFormat~1bc3_rgba/title",
          "value": "MTLPixelFormatBC3_RGBA"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLPixelFormat~1bc3_rgba/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLPixelFormatBC3_RGBA"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLPixelFormat~1bc5_rgUnorm/title",
          "value": "MTLPixelFormatBC5_RGUnorm"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLPixelFormat~1bc5_rgUnorm/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLPixelFormatBC5_RGUnorm"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLPixelFormat~1bc2_rgba_srgb/title",
          "value": "MTLPixelFormatBC2_RGBA_sRGB"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLPixelFormat~1bc2_rgba_srgb/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLPixelFormatBC2_RGBA_sRGB"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/metal/mtlpixelformat/bc3_rgba"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/metal/mtlpixelformat/bc3_rgba"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
