{
  "abstract": [
    {
      "text": "Compressed format using PVRTC compression and 4bpp for RGBA components with conversion between sRGB and linear space.",
      "type": "text"
    }
  ],
  "deprecationSummary": [
    {
      "inlineContent": [
        {
          "text": "Use one of the other formats with ",
          "type": "text"
        },
        {
          "code": "astc",
          "type": "codeVoice"
        },
        {
          "text": "/",
          "type": "text"
        },
        {
          "code": "ASTC",
          "type": "codeVoice"
        },
        {
          "text": ", ",
          "type": "text"
        },
        {
          "code": "etc2",
          "type": "codeVoice"
        },
        {
          "text": "/",
          "type": "text"
        },
        {
          "code": "ETC2",
          "type": "codeVoice"
        },
        {
          "text": ", or ",
          "type": "text"
        },
        {
          "code": "bc",
          "type": "codeVoice"
        },
        {
          "text": "/",
          "type": "text"
        },
        {
          "code": "BC",
          "type": "codeVoice"
        },
        {
          "text": " instead.",
          "type": "text"
        }
      ],
      "type": "paragraph"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.metal/documentation/Metal",
        "doc://com.apple.metal/documentation/Metal/MTLPixelFormat"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.metal/documentation/Metal/MTLPixelFormat/pvrtc_rgba_4bpp_srgb"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@MTLPixelFormat@MTLPixelFormatPVRTC_RGBA_4BPP_sRGB",
    "fragments": [
      {
        "kind": "keyword",
        "text": "case"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "pvrtc_rgba_4bpp_srgb"
      }
    ],
    "modules": [
      {
        "name": "Metal"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "MTLPixelFormatPVRTC_RGBA_4BPP_sRGB"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "18.0",
        "introducedAt": "8.0",
        "message": "Usage of ASTC/ETC2/BC formats is recommended instead.",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "18.0",
        "introducedAt": "8.0",
        "message": "Usage of ASTC/ETC2/BC formats is recommended instead.",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "18.0",
        "introducedAt": "14.0",
        "message": "Usage of ASTC/ETC2/BC formats is recommended instead.",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "15.0",
        "introducedAt": "11.0",
        "message": "Usage of ASTC/ETC2/BC formats is recommended instead.",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "18.0",
        "message": "Usage of ASTC/ETC2/BC formats is recommended instead.",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "2.0",
        "introducedAt": "1.0",
        "message": "Usage of ASTC/ETC2/BC formats is recommended instead.",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Case",
    "symbolKind": "case",
    "title": "MTLPixelFormat.pvrtc_rgba_4bpp_srgb"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "case"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "pvrtc_rgba_4bpp_srgb"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Only ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.metal/documentation/Metal/MTLTextureType/type2D",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ", ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.metal/documentation/Metal/MTLTextureType/type2DArray",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ", and ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.metal/documentation/Metal/MTLTextureType/typeCube",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " textures are supported. Subimages are not supported.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.metal/documentation/Metal": {
      "abstract": [
        {
          "text": "Render advanced 3D graphics and compute data in parallel with graphics processors.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal",
      "kind": "symbol",
      "role": "collection",
      "title": "Metal",
      "type": "topic",
      "url": "/documentation/metal"
    },
    "doc://com.apple.metal/documentation/Metal/MTLPixelFormat": {
      "abstract": [
        {
          "text": "The data formats that describe the organization and characteristics of individual pixels in a texture.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MTLPixelFormat"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLPixelFormat",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTLPixelFormat"
        }
      ],
      "role": "symbol",
      "title": "MTLPixelFormat",
      "type": "topic",
      "url": "/documentation/metal/mtlpixelformat"
    },
    "doc://com.apple.metal/documentation/Metal/MTLPixelFormat/pvrtc_rgb_2bpp": {
      "abstract": [
        {
          "text": "Compressed format using PVRTC compression and 2bpp for RGB components.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "pvrtc_rgb_2bpp"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLPixelFormat/pvrtc_rgb_2bpp",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTLPixelFormatPVRTC_RGB_2BPP"
        }
      ],
      "role": "symbol",
      "title": "MTLPixelFormat.pvrtc_rgb_2bpp",
      "type": "topic",
      "url": "/documentation/metal/mtlpixelformat/pvrtc_rgb_2bpp"
    },
    "doc://com.apple.metal/documentation/Metal/MTLPixelFormat/pvrtc_rgb_2bpp_srgb": {
      "abstract": [
        {
          "text": "Compressed format using PVRTC compression and 2bpp for RGB components with conversion between sRGB and linear space.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "pvrtc_rgb_2bpp_srgb"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLPixelFormat/pvrtc_rgb_2bpp_srgb",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTLPixelFormatPVRTC_RGB_2BPP_sRGB"
        }
      ],
      "role": "symbol",
      "title": "MTLPixelFormat.pvrtc_rgb_2bpp_srgb",
      "type": "topic",
      "url": "/documentation/metal/mtlpixelformat/pvrtc_rgb_2bpp_srgb"
    },
    "doc://com.apple.metal/documentation/Metal/MTLPixelFormat/pvrtc_rgb_4bpp": {
      "abstract": [
        {
          "text": "Compressed format using PVRTC compression and 4bpp for RGB components.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "pvrtc_rgb_4bpp"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLPixelFormat/pvrtc_rgb_4bpp",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTLPixelFormatPVRTC_RGB_4BPP"
        }
      ],
      "role": "symbol",
      "title": "MTLPixelFormat.pvrtc_rgb_4bpp",
      "type": "topic",
      "url": "/documentation/metal/mtlpixelformat/pvrtc_rgb_4bpp"
    },
    "doc://com.apple.metal/documentation/Metal/MTLPixelFormat/pvrtc_rgb_4bpp_srgb": {
      "abstract": [
        {
          "text": "Compressed format using PVRTC compression and 4bpp for RGB components with conversion between sRGB and linear space.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "pvrtc_rgb_4bpp_srgb"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLPixelFormat/pvrtc_rgb_4bpp_srgb",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTLPixelFormatPVRTC_RGB_4BPP_sRGB"
        }
      ],
      "role": "symbol",
      "title": "MTLPixelFormat.pvrtc_rgb_4bpp_srgb",
      "type": "topic",
      "url": "/documentation/metal/mtlpixelformat/pvrtc_rgb_4bpp_srgb"
    },
    "doc://com.apple.metal/documentation/Metal/MTLPixelFormat/pvrtc_rgba_2bpp": {
      "abstract": [
        {
          "text": "Compressed format using PVRTC compression and 2bpp for RGBA components.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "pvrtc_rgba_2bpp"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLPixelFormat/pvrtc_rgba_2bpp",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTLPixelFormatPVRTC_RGBA_2BPP"
        }
      ],
      "role": "symbol",
      "title": "MTLPixelFormat.pvrtc_rgba_2bpp",
      "type": "topic",
      "url": "/documentation/metal/mtlpixelformat/pvrtc_rgba_2bpp"
    },
    "doc://com.apple.metal/documentation/Metal/MTLPixelFormat/pvrtc_rgba_2bpp_srgb": {
      "abstract": [
        {
          "text": "Compressed format using PVRTC compression and 2bpp for RGBA components with conversion between sRGB and linear space.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "pvrtc_rgba_2bpp_srgb"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLPixelFormat/pvrtc_rgba_2bpp_srgb",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTLPixelFormatPVRTC_RGBA_2BPP_sRGB"
        }
      ],
      "role": "symbol",
      "title": "MTLPixelFormat.pvrtc_rgba_2bpp_srgb",
      "type": "topic",
      "url": "/documentation/metal/mtlpixelformat/pvrtc_rgba_2bpp_srgb"
    },
    "doc://com.apple.metal/documentation/Metal/MTLPixelFormat/pvrtc_rgba_4bpp": {
      "abstract": [
        {
          "text": "Compressed format using PVRTC compression and 4bpp for RGBA components.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "pvrtc_rgba_4bpp"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLPixelFormat/pvrtc_rgba_4bpp",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTLPixelFormatPVRTC_RGBA_4BPP"
        }
      ],
      "role": "symbol",
      "title": "MTLPixelFormat.pvrtc_rgba_4bpp",
      "type": "topic",
      "url": "/documentation/metal/mtlpixelformat/pvrtc_rgba_4bpp"
    },
    "doc://com.apple.metal/documentation/Metal/MTLPixelFormat/pvrtc_rgba_4bpp_srgb": {
      "abstract": [
        {
          "text": "Compressed format using PVRTC compression and 4bpp for RGBA components with conversion between sRGB and linear space.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "pvrtc_rgba_4bpp_srgb"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLPixelFormat/pvrtc_rgba_4bpp_srgb",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTLPixelFormatPVRTC_RGBA_4BPP_sRGB"
        }
      ],
      "role": "symbol",
      "title": "MTLPixelFormat.pvrtc_rgba_4bpp_srgb",
      "type": "topic",
      "url": "/documentation/metal/mtlpixelformat/pvrtc_rgba_4bpp_srgb"
    },
    "doc://com.apple.metal/documentation/Metal/MTLTextureType/type2D": {
      "abstract": [
        {
          "text": "A two-dimensional texture image.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "type2D"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLTextureType/type2D",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTLTextureType2D"
        }
      ],
      "role": "symbol",
      "title": "MTLTextureType.type2D",
      "type": "topic",
      "url": "/documentation/metal/mtltexturetype/type2d"
    },
    "doc://com.apple.metal/documentation/Metal/MTLTextureType/type2DArray": {
      "abstract": [
        {
          "text": "An array of two-dimensional texture images.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "type2DArray"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLTextureType/type2DArray",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTLTextureType2DArray"
        }
      ],
      "role": "symbol",
      "title": "MTLTextureType.type2DArray",
      "type": "topic",
      "url": "/documentation/metal/mtltexturetype/type2darray"
    },
    "doc://com.apple.metal/documentation/Metal/MTLTextureType/typeCube": {
      "abstract": [
        {
          "text": "A cube texture with six two-dimensional images.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "typeCube"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLTextureType/typeCube",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTLTextureTypeCube"
        }
      ],
      "role": "symbol",
      "title": "MTLTextureType.typeCube",
      "type": "topic",
      "url": "/documentation/metal/mtltexturetype/typecube"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Compressed-PVRTC-Pixel-Formats",
      "generated": true,
      "identifiers": [
        "doc://com.apple.metal/documentation/Metal/MTLPixelFormat/pvrtc_rgb_2bpp",
        "doc://com.apple.metal/documentation/Metal/MTLPixelFormat/pvrtc_rgb_2bpp_srgb",
        "doc://com.apple.metal/documentation/Metal/MTLPixelFormat/pvrtc_rgb_4bpp",
        "doc://com.apple.metal/documentation/Metal/MTLPixelFormat/pvrtc_rgb_4bpp_srgb",
        "doc://com.apple.metal/documentation/Metal/MTLPixelFormat/pvrtc_rgba_2bpp",
        "doc://com.apple.metal/documentation/Metal/MTLPixelFormat/pvrtc_rgba_2bpp_srgb",
        "doc://com.apple.metal/documentation/Metal/MTLPixelFormat/pvrtc_rgba_4bpp"
      ],
      "title": "Compressed PVRTC Pixel Formats"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "deprecatedAt": "18.0",
              "introducedAt": "8.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "deprecatedAt": "18.0",
              "introducedAt": "8.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "deprecatedAt": "18.0",
              "introducedAt": "14.0",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "deprecatedAt": "15.0",
              "introducedAt": "11.0",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "deprecatedAt": "18.0",
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "deprecatedAt": "2.0",
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration Case"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "MTLPixelFormatPVRTC_RGBA_4BPP_sRGB"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "case"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLPixelFormatPVRTC_RGBA_4BPP_sRGB"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.metal/documentation/Metal",
                "doc://com.apple.metal/documentation/Metal/MTLPixelFormat"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Compressed-PVRTC-Pixel-Formats",
              "generated": true,
              "identifiers": [
                "doc://com.apple.metal/documentation/Metal/MTLPixelFormat/pvrtc_rgb_2bpp",
                "doc://com.apple.metal/documentation/Metal/MTLPixelFormat/pvrtc_rgb_2bpp_srgb",
                "doc://com.apple.metal/documentation/Metal/MTLPixelFormat/pvrtc_rgb_4bpp",
                "doc://com.apple.metal/documentation/Metal/MTLPixelFormat/pvrtc_rgb_4bpp_srgb",
                "doc://com.apple.metal/documentation/Metal/MTLPixelFormat/pvrtc_rgba_2bpp",
                "doc://com.apple.metal/documentation/Metal/MTLPixelFormat/pvrtc_rgba_2bpp_srgb",
                "doc://com.apple.metal/documentation/Metal/MTLPixelFormat/pvrtc_rgba_4bpp"
              ],
              "title": "Compressed PVRTC Pixel Formats"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS"
                ],
                "tokens": [
                  {
                    "kind": "identifier",
                    "text": "MTLPixelFormatPVRTC_RGBA_4BPP_sRGB"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/deprecationSummary",
          "value": [
            {
              "inlineContent": [
                {
                  "text": "Use one of the other formats with ",
                  "type": "text"
                },
                {
                  "code": "astc",
                  "type": "codeVoice"
                },
                {
                  "text": "/",
                  "type": "text"
                },
                {
                  "code": "ASTC",
                  "type": "codeVoice"
                },
                {
                  "text": ", ",
                  "type": "text"
                },
                {
                  "code": "etc2",
                  "type": "codeVoice"
                },
                {
                  "text": "/",
                  "type": "text"
                },
                {
                  "code": "ETC2",
                  "type": "codeVoice"
                },
                {
                  "text": ", or ",
                  "type": "text"
                },
                {
                  "code": "bc",
                  "type": "codeVoice"
                },
                {
                  "text": "/",
                  "type": "text"
                },
                {
                  "code": "BC",
                  "type": "codeVoice"
                },
                {
                  "text": " instead.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLTextureType~1type2DArray/title",
          "value": "MTLTextureType2DArray"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLTextureType~1type2DArray/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLTextureType2DArray"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLPixelFormat~1pvrtc_rgb_4bpp/title",
          "value": "MTLPixelFormatPVRTC_RGB_4BPP"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLPixelFormat~1pvrtc_rgb_4bpp/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLPixelFormatPVRTC_RGB_4BPP"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLTextureType~1type2D/title",
          "value": "MTLTextureType2D"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLTextureType~1type2D/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLTextureType2D"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLPixelFormat~1pvrtc_rgba_2bpp/title",
          "value": "MTLPixelFormatPVRTC_RGBA_2BPP"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLPixelFormat~1pvrtc_rgba_2bpp/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLPixelFormatPVRTC_RGBA_2BPP"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLPixelFormat~1pvrtc_rgba_2bpp_srgb/title",
          "value": "MTLPixelFormatPVRTC_RGBA_2BPP_sRGB"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLPixelFormat~1pvrtc_rgba_2bpp_srgb/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLPixelFormatPVRTC_RGBA_2BPP_sRGB"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLPixelFormat~1pvrtc_rgb_4bpp_srgb/title",
          "value": "MTLPixelFormatPVRTC_RGB_4BPP_sRGB"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLPixelFormat~1pvrtc_rgb_4bpp_srgb/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLPixelFormatPVRTC_RGB_4BPP_sRGB"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLPixelFormat/title",
          "value": "MTLPixelFormat"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLPixelFormat/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLPixelFormat"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLPixelFormat/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLPixelFormat"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLPixelFormat~1pvrtc_rgba_4bpp_srgb/title",
          "value": "MTLPixelFormatPVRTC_RGBA_4BPP_sRGB"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLPixelFormat~1pvrtc_rgba_4bpp_srgb/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLPixelFormatPVRTC_RGBA_4BPP_sRGB"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLPixelFormat~1pvrtc_rgb_2bpp/title",
          "value": "MTLPixelFormatPVRTC_RGB_2BPP"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLPixelFormat~1pvrtc_rgb_2bpp/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLPixelFormatPVRTC_RGB_2BPP"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLTextureType~1typeCube/title",
          "value": "MTLTextureTypeCube"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLTextureType~1typeCube/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLTextureTypeCube"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLPixelFormat~1pvrtc_rgba_4bpp/title",
          "value": "MTLPixelFormatPVRTC_RGBA_4BPP"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLPixelFormat~1pvrtc_rgba_4bpp/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLPixelFormatPVRTC_RGBA_4BPP"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLPixelFormat~1pvrtc_rgb_2bpp_srgb/title",
          "value": "MTLPixelFormatPVRTC_RGB_2BPP_sRGB"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLPixelFormat~1pvrtc_rgb_2bpp_srgb/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLPixelFormatPVRTC_RGB_2BPP_sRGB"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/metal/mtlpixelformat/pvrtc_rgba_4bpp_srgb"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/metal/mtlpixelformat/pvrtc_rgba_4bpp_srgb"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
