{
  "abstract": [
    {
      "text": "Ordinary format with two 8-bit normalized signed integer components.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.metal/documentation/Metal",
        "doc://com.apple.metal/documentation/Metal/MTLPixelFormat"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.metal/documentation/Metal/MTLPixelFormat/rg8Snorm"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@MTLPixelFormat@MTLPixelFormatRG8Snorm",
    "fragments": [
      {
        "kind": "keyword",
        "text": "case"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "rg8Snorm"
      }
    ],
    "modules": [
      {
        "name": "Metal"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "MTLPixelFormatRG8Snorm"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "8.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "8.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.1",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.11",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Case",
    "symbolKind": "case",
    "title": "MTLPixelFormat.rg8Snorm"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "case"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "rg8Snorm"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.metal/documentation/Metal": {
      "abstract": [
        {
          "text": "Render advanced 3D graphics and compute data in parallel with graphics processors.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal",
      "kind": "symbol",
      "role": "collection",
      "title": "Metal",
      "type": "topic",
      "url": "/documentation/metal"
    },
    "doc://com.apple.metal/documentation/Metal/MTLPixelFormat": {
      "abstract": [
        {
          "text": "The data formats that describe the organization and characteristics of individual pixels in a texture.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MTLPixelFormat"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLPixelFormat",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTLPixelFormat"
        }
      ],
      "role": "symbol",
      "title": "MTLPixelFormat",
      "type": "topic",
      "url": "/documentation/metal/mtlpixelformat"
    },
    "doc://com.apple.metal/documentation/Metal/MTLPixelFormat/r16Float": {
      "abstract": [
        {
          "text": "Ordinary format with one 16-bit floating-point component.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "r16Float"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLPixelFormat/r16Float",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTLPixelFormatR16Float"
        }
      ],
      "role": "symbol",
      "title": "MTLPixelFormat.r16Float",
      "type": "topic",
      "url": "/documentation/metal/mtlpixelformat/r16float"
    },
    "doc://com.apple.metal/documentation/Metal/MTLPixelFormat/r16Sint": {
      "abstract": [
        {
          "text": "Ordinary format with one 16-bit signed integer component.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "r16Sint"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLPixelFormat/r16Sint",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTLPixelFormatR16Sint"
        }
      ],
      "role": "symbol",
      "title": "MTLPixelFormat.r16Sint",
      "type": "topic",
      "url": "/documentation/metal/mtlpixelformat/r16sint"
    },
    "doc://com.apple.metal/documentation/Metal/MTLPixelFormat/r16Snorm": {
      "abstract": [
        {
          "text": "Ordinary format with one 16-bit normalized signed integer component.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "r16Snorm"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLPixelFormat/r16Snorm",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTLPixelFormatR16Snorm"
        }
      ],
      "role": "symbol",
      "title": "MTLPixelFormat.r16Snorm",
      "type": "topic",
      "url": "/documentation/metal/mtlpixelformat/r16snorm"
    },
    "doc://com.apple.metal/documentation/Metal/MTLPixelFormat/r16Uint": {
      "abstract": [
        {
          "text": "Ordinary format with one 16-bit unsigned integer component.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "r16Uint"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLPixelFormat/r16Uint",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTLPixelFormatR16Uint"
        }
      ],
      "role": "symbol",
      "title": "MTLPixelFormat.r16Uint",
      "type": "topic",
      "url": "/documentation/metal/mtlpixelformat/r16uint"
    },
    "doc://com.apple.metal/documentation/Metal/MTLPixelFormat/r16Unorm": {
      "abstract": [
        {
          "text": "Ordinary format with one 16-bit normalized unsigned integer component.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "r16Unorm"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLPixelFormat/r16Unorm",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTLPixelFormatR16Unorm"
        }
      ],
      "role": "symbol",
      "title": "MTLPixelFormat.r16Unorm",
      "type": "topic",
      "url": "/documentation/metal/mtlpixelformat/r16unorm"
    },
    "doc://com.apple.metal/documentation/Metal/MTLPixelFormat/rg8Sint": {
      "abstract": [
        {
          "text": "Ordinary format with two 8-bit signed integer components.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "rg8Sint"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLPixelFormat/rg8Sint",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTLPixelFormatRG8Sint"
        }
      ],
      "role": "symbol",
      "title": "MTLPixelFormat.rg8Sint",
      "type": "topic",
      "url": "/documentation/metal/mtlpixelformat/rg8sint"
    },
    "doc://com.apple.metal/documentation/Metal/MTLPixelFormat/rg8Snorm": {
      "abstract": [
        {
          "text": "Ordinary format with two 8-bit normalized signed integer components.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "rg8Snorm"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLPixelFormat/rg8Snorm",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTLPixelFormatRG8Snorm"
        }
      ],
      "role": "symbol",
      "title": "MTLPixelFormat.rg8Snorm",
      "type": "topic",
      "url": "/documentation/metal/mtlpixelformat/rg8snorm"
    },
    "doc://com.apple.metal/documentation/Metal/MTLPixelFormat/rg8Uint": {
      "abstract": [
        {
          "text": "Ordinary format with two 8-bit unsigned integer components.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "rg8Uint"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLPixelFormat/rg8Uint",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTLPixelFormatRG8Uint"
        }
      ],
      "role": "symbol",
      "title": "MTLPixelFormat.rg8Uint",
      "type": "topic",
      "url": "/documentation/metal/mtlpixelformat/rg8uint"
    },
    "doc://com.apple.metal/documentation/Metal/MTLPixelFormat/rg8Unorm": {
      "abstract": [
        {
          "text": "Ordinary format with two 8-bit normalized unsigned integer components.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "rg8Unorm"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLPixelFormat/rg8Unorm",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTLPixelFormatRG8Unorm"
        }
      ],
      "role": "symbol",
      "title": "MTLPixelFormat.rg8Unorm",
      "type": "topic",
      "url": "/documentation/metal/mtlpixelformat/rg8unorm"
    },
    "doc://com.apple.metal/documentation/Metal/MTLPixelFormat/rg8Unorm_srgb": {
      "abstract": [
        {
          "text": "Ordinary format with two 8-bit normalized unsigned integer components with conversion between sRGB and linear space.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "rg8Unorm_srgb"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLPixelFormat/rg8Unorm_srgb",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTLPixelFormatRG8Unorm_sRGB"
        }
      ],
      "role": "symbol",
      "title": "MTLPixelFormat.rg8Unorm_srgb",
      "type": "topic",
      "url": "/documentation/metal/mtlpixelformat/rg8unorm_srgb"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Ordinary-16-Bit-Pixel-Formats",
      "generated": true,
      "identifiers": [
        "doc://com.apple.metal/documentation/Metal/MTLPixelFormat/r16Unorm",
        "doc://com.apple.metal/documentation/Metal/MTLPixelFormat/r16Snorm",
        "doc://com.apple.metal/documentation/Metal/MTLPixelFormat/r16Uint",
        "doc://com.apple.metal/documentation/Metal/MTLPixelFormat/r16Sint",
        "doc://com.apple.metal/documentation/Metal/MTLPixelFormat/r16Float",
        "doc://com.apple.metal/documentation/Metal/MTLPixelFormat/rg8Unorm",
        "doc://com.apple.metal/documentation/Metal/MTLPixelFormat/rg8Unorm_srgb",
        "doc://com.apple.metal/documentation/Metal/MTLPixelFormat/rg8Uint",
        "doc://com.apple.metal/documentation/Metal/MTLPixelFormat/rg8Sint"
      ],
      "title": "Ordinary 16-Bit Pixel Formats"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "8.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "8.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.1",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.11",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration Case"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "MTLPixelFormatRG8Snorm"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "case"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLPixelFormatRG8Snorm"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.metal/documentation/Metal",
                "doc://com.apple.metal/documentation/Metal/MTLPixelFormat"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Ordinary-16-Bit-Pixel-Formats",
              "generated": true,
              "identifiers": [
                "doc://com.apple.metal/documentation/Metal/MTLPixelFormat/r16Unorm",
                "doc://com.apple.metal/documentation/Metal/MTLPixelFormat/r16Snorm",
                "doc://com.apple.metal/documentation/Metal/MTLPixelFormat/r16Uint",
                "doc://com.apple.metal/documentation/Metal/MTLPixelFormat/r16Sint",
                "doc://com.apple.metal/documentation/Metal/MTLPixelFormat/r16Float",
                "doc://com.apple.metal/documentation/Metal/MTLPixelFormat/rg8Unorm",
                "doc://com.apple.metal/documentation/Metal/MTLPixelFormat/rg8Unorm_srgb",
                "doc://com.apple.metal/documentation/Metal/MTLPixelFormat/rg8Uint",
                "doc://com.apple.metal/documentation/Metal/MTLPixelFormat/rg8Sint"
              ],
              "title": "Ordinary 16-Bit Pixel Formats"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS"
                ],
                "tokens": [
                  {
                    "kind": "identifier",
                    "text": "MTLPixelFormatRG8Snorm"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLPixelFormat~1rg8Sint/title",
          "value": "MTLPixelFormatRG8Sint"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLPixelFormat~1rg8Sint/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLPixelFormatRG8Sint"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLPixelFormat~1rg8Uint/title",
          "value": "MTLPixelFormatRG8Uint"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLPixelFormat~1rg8Uint/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLPixelFormatRG8Uint"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLPixelFormat~1r16Float/title",
          "value": "MTLPixelFormatR16Float"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLPixelFormat~1r16Float/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLPixelFormatR16Float"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLPixelFormat/title",
          "value": "MTLPixelFormat"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLPixelFormat/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLPixelFormat"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLPixelFormat/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLPixelFormat"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLPixelFormat~1r16Unorm/title",
          "value": "MTLPixelFormatR16Unorm"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLPixelFormat~1r16Unorm/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLPixelFormatR16Unorm"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLPixelFormat~1r16Sint/title",
          "value": "MTLPixelFormatR16Sint"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLPixelFormat~1r16Sint/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLPixelFormatR16Sint"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLPixelFormat~1rg8Snorm/title",
          "value": "MTLPixelFormatRG8Snorm"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLPixelFormat~1rg8Snorm/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLPixelFormatRG8Snorm"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLPixelFormat~1rg8Unorm_srgb/title",
          "value": "MTLPixelFormatRG8Unorm_sRGB"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLPixelFormat~1rg8Unorm_srgb/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLPixelFormatRG8Unorm_sRGB"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLPixelFormat~1r16Snorm/title",
          "value": "MTLPixelFormatR16Snorm"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLPixelFormat~1r16Snorm/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLPixelFormatR16Snorm"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLPixelFormat~1r16Uint/title",
          "value": "MTLPixelFormatR16Uint"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLPixelFormat~1r16Uint/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLPixelFormatR16Uint"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLPixelFormat~1rg8Unorm/title",
          "value": "MTLPixelFormatRG8Unorm"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLPixelFormat~1rg8Unorm/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLPixelFormatRG8Unorm"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/metal/mtlpixelformat/rg8snorm"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/metal/mtlpixelformat/rg8snorm"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
