{"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["/documentation/metal/mtlpixelformat/rg8uint"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["/documentation/metal/mtlpixelformat/rg8uint"]}],"abstract":[{"type":"text","text":"Ordinary format with two 8-bit unsigned integer components."}],"sections":[],"seeAlsoSections":[{"title":"Ordinary 16-Bit Pixel Formats","generated":true,"identifiers":["doc://com.apple.metal/documentation/Metal/MTLPixelFormat/r16Unorm","doc://com.apple.metal/documentation/Metal/MTLPixelFormat/r16Snorm","doc://com.apple.metal/documentation/Metal/MTLPixelFormat/r16Uint","doc://com.apple.metal/documentation/Metal/MTLPixelFormat/r16Sint","doc://com.apple.metal/documentation/Metal/MTLPixelFormat/r16Float","doc://com.apple.metal/documentation/Metal/MTLPixelFormat/rg8Unorm","doc://com.apple.metal/documentation/Metal/MTLPixelFormat/rg8Unorm_srgb","doc://com.apple.metal/documentation/Metal/MTLPixelFormat/rg8Snorm","doc://com.apple.metal/documentation/Metal/MTLPixelFormat/rg8Sint"],"anchor":"Ordinary-16-Bit-Pixel-Formats"}],"kind":"symbol","hierarchy":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.metal/documentation/Metal","doc://com.apple.metal/documentation/Metal/MTLPixelFormat"]]},"schemaVersion":{"major":0,"minor":3,"patch":0},"identifier":{"interfaceLanguage":"swift","url":"doc://com.apple.metal/documentation/Metal/MTLPixelFormat/rg8Uint"},"metadata":{"platforms":[{"introducedAt":"8.0","name":"iOS","beta":false,"unavailable":false,"deprecated":false},{"introducedAt":"8.0","name":"iPadOS","beta":false,"unavailable":false,"deprecated":false},{"introducedAt":"13.1","name":"Mac Catalyst","beta":false,"unavailable":false,"deprecated":false},{"introducedAt":"10.11","name":"macOS","beta":false,"unavailable":false,"deprecated":false},{"beta":false,"name":"tvOS","deprecated":false,"unavailable":false},{"beta":false,"name":"visionOS","deprecated":false,"unavailable":false,"introducedAt":"1.0"}],"symbolKind":"case","title":"MTLPixelFormat.rg8Uint","modules":[{"name":"Metal"}],"externalID":"c:@E@MTLPixelFormat@MTLPixelFormatRG8Uint","navigatorTitle":[{"text":"MTLPixelFormatRG8Uint","kind":"identifier"}],"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"rg8Uint","kind":"identifier"}],"role":"symbol","roleHeading":"Case"},"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"rg8Uint"}],"platforms":["iOS","iPadOS","Mac Catalyst","macOS","tvOS","visionOS"],"languages":["swift"]}],"kind":"declarations"}],"references":{"doc://com.apple.metal/documentation/Metal/MTLPixelFormat/rg8Snorm":{"kind":"symbol","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"rg8Snorm"}],"abstract":[{"text":"Ordinary format with two 8-bit normalized signed integer components.","type":"text"}],"role":"symbol","identifier":"doc://com.apple.metal/documentation/Metal/MTLPixelFormat/rg8Snorm","type":"topic","url":"/documentation/metal/mtlpixelformat/rg8snorm","navigatorTitle":[{"kind":"identifier","text":"MTLPixelFormatRG8Snorm"}],"title":"MTLPixelFormat.rg8Snorm"},"doc://com.apple.metal/documentation/Metal/MTLPixelFormat/r16Unorm":{"title":"MTLPixelFormat.r16Unorm","abstract":[{"text":"Ordinary format with one 16-bit normalized unsigned integer component.","type":"text"}],"fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"r16Unorm"}],"type":"topic","navigatorTitle":[{"kind":"identifier","text":"MTLPixelFormatR16Unorm"}],"url":"/documentation/metal/mtlpixelformat/r16unorm","role":"symbol","kind":"symbol","identifier":"doc://com.apple.metal/documentation/Metal/MTLPixelFormat/r16Unorm"},"doc://com.apple.metal/documentation/Metal/MTLPixelFormat/r16Sint":{"kind":"symbol","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"r16Sint","kind":"identifier"}],"abstract":[{"text":"Ordinary format with one 16-bit signed integer component.","type":"text"}],"role":"symbol","identifier":"doc://com.apple.metal/documentation/Metal/MTLPixelFormat/r16Sint","type":"topic","url":"/documentation/metal/mtlpixelformat/r16sint","navigatorTitle":[{"kind":"identifier","text":"MTLPixelFormatR16Sint"}],"title":"MTLPixelFormat.r16Sint"},"doc://com.apple.metal/documentation/Metal/MTLPixelFormat/r16Snorm":{"type":"topic","abstract":[{"text":"Ordinary format with one 16-bit normalized signed integer component.","type":"text"}],"role":"symbol","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"r16Snorm","kind":"identifier"}],"identifier":"doc://com.apple.metal/documentation/Metal/MTLPixelFormat/r16Snorm","title":"MTLPixelFormat.r16Snorm","navigatorTitle":[{"text":"MTLPixelFormatR16Snorm","kind":"identifier"}],"url":"/documentation/metal/mtlpixelformat/r16snorm","kind":"symbol"},"doc://com.apple.metal/documentation/Metal/MTLPixelFormat":{"role":"symbol","identifier":"doc://com.apple.metal/documentation/Metal/MTLPixelFormat","title":"MTLPixelFormat","kind":"symbol","type":"topic","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MTLPixelFormat","kind":"identifier"}],"url":"/documentation/metal/mtlpixelformat","abstract":[{"text":"The data formats that describe the organization and characteristics of individual pixels in a texture.","type":"text"}],"navigatorTitle":[{"text":"MTLPixelFormat","kind":"identifier"}]},"doc://com.apple.metal/documentation/Metal":{"role":"collection","kind":"symbol","type":"topic","identifier":"doc://com.apple.metal/documentation/Metal","title":"Metal","abstract":[{"text":"Render advanced 3D graphics and compute data in parallel with graphics processors.","type":"text"}],"url":"/documentation/metal"},"doc://com.apple.metal/documentation/Metal/MTLPixelFormat/rg8Unorm_srgb":{"title":"MTLPixelFormat.rg8Unorm_srgb","url":"/documentation/metal/mtlpixelformat/rg8unorm_srgb","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"rg8Unorm_srgb"}],"role":"symbol","abstract":[{"type":"text","text":"Ordinary format with two 8-bit normalized unsigned integer components with conversion between sRGB and linear space."}],"identifier":"doc://com.apple.metal/documentation/Metal/MTLPixelFormat/rg8Unorm_srgb","type":"topic","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"MTLPixelFormatRG8Unorm_sRGB"}]},"doc://com.apple.metal/documentation/Metal/MTLPixelFormat/rg8Unorm":{"title":"MTLPixelFormat.rg8Unorm","kind":"symbol","role":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"rg8Unorm"}],"navigatorTitle":[{"kind":"identifier","text":"MTLPixelFormatRG8Unorm"}],"identifier":"doc://com.apple.metal/documentation/Metal/MTLPixelFormat/rg8Unorm","url":"/documentation/metal/mtlpixelformat/rg8unorm","abstract":[{"text":"Ordinary format with two 8-bit normalized unsigned integer components.","type":"text"}]},"doc://com.apple.documentation/documentation/technologies":{"role":"overview","kind":"technologies","type":"topic","identifier":"doc://com.apple.documentation/documentation/technologies","title":"Technologies","abstract":[{"text":"","type":"text"}],"url":"/documentation/technologies"},"doc://com.apple.metal/documentation/Metal/MTLPixelFormat/r16Uint":{"navigatorTitle":[{"text":"MTLPixelFormatR16Uint","kind":"identifier"}],"identifier":"doc://com.apple.metal/documentation/Metal/MTLPixelFormat/r16Uint","role":"symbol","type":"topic","title":"MTLPixelFormat.r16Uint","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"r16Uint","kind":"identifier"}],"kind":"symbol","abstract":[{"text":"Ordinary format with one 16-bit unsigned integer component.","type":"text"}],"url":"/documentation/metal/mtlpixelformat/r16uint"},"doc://com.apple.metal/documentation/Metal/MTLPixelFormat/rg8Uint":{"navigatorTitle":[{"kind":"identifier","text":"MTLPixelFormatRG8Uint"}],"abstract":[{"type":"text","text":"Ordinary format with two 8-bit unsigned integer components."}],"identifier":"doc://com.apple.metal/documentation/Metal/MTLPixelFormat/rg8Uint","kind":"symbol","type":"topic","url":"/documentation/metal/mtlpixelformat/rg8uint","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"rg8Uint"}],"role":"symbol","title":"MTLPixelFormat.rg8Uint"},"doc://com.apple.metal/documentation/Metal/MTLPixelFormat/r16Float":{"identifier":"doc://com.apple.metal/documentation/Metal/MTLPixelFormat/r16Float","kind":"symbol","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"r16Float","kind":"identifier"}],"role":"symbol","navigatorTitle":[{"text":"MTLPixelFormatR16Float","kind":"identifier"}],"type":"topic","title":"MTLPixelFormat.r16Float","abstract":[{"text":"Ordinary format with one 16-bit floating-point component.","type":"text"}],"url":"/documentation/metal/mtlpixelformat/r16float"},"doc://com.apple.metal/documentation/Metal/MTLPixelFormat/rg8Sint":{"url":"/documentation/metal/mtlpixelformat/rg8sint","role":"symbol","navigatorTitle":[{"text":"MTLPixelFormatRG8Sint","kind":"identifier"}],"kind":"symbol","abstract":[{"type":"text","text":"Ordinary format with two 8-bit signed integer components."}],"title":"MTLPixelFormat.rg8Sint","type":"topic","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"rg8Sint","kind":"identifier"}],"identifier":"doc://com.apple.metal/documentation/Metal/MTLPixelFormat/rg8Sint"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"/identifier/interfaceLanguage"},{"value":[{"name":"iOS","introducedAt":"8.0","unavailable":false,"beta":false,"deprecated":false},{"name":"iPadOS","introducedAt":"8.0","unavailable":false,"beta":false,"deprecated":false},{"name":"Mac Catalyst","introducedAt":"13.1","unavailable":false,"beta":false,"deprecated":false},{"name":"macOS","introducedAt":"10.11","unavailable":false,"beta":false,"deprecated":false},{"name":"tvOS","unavailable":false,"beta":false,"deprecated":false},{"name":"visionOS","introducedAt":"1.0","unavailable":false,"beta":false,"deprecated":false}],"op":"replace","path":"/metadata/platforms"},{"value":"Enumeration Case","op":"replace","path":"/metadata/roleHeading"},{"value":"MTLPixelFormatRG8Uint","op":"replace","path":"/metadata/title"},{"value":"case","op":"replace","path":"/metadata/symbolKind"},{"path":"/metadata/fragments","op":"replace","value":[{"kind":"identifier","text":"MTLPixelFormatRG8Uint"}]},{"path":"/hierarchy","op":"replace","value":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.metal/documentation/Metal","doc://com.apple.metal/documentation/Metal/MTLPixelFormat"]]}},{"path":"/topicSections","op":"add","value":null},{"path":"/relationshipsSections","op":"add","value":null},{"path":"/seeAlsoSections","op":"replace","value":[{"title":"Ordinary 16-Bit Pixel Formats","identifiers":["doc://com.apple.metal/documentation/Metal/MTLPixelFormat/r16Unorm","doc://com.apple.metal/documentation/Metal/MTLPixelFormat/r16Snorm","doc://com.apple.metal/documentation/Metal/MTLPixelFormat/r16Uint","doc://com.apple.metal/documentation/Metal/MTLPixelFormat/r16Sint","doc://com.apple.metal/documentation/Metal/MTLPixelFormat/r16Float","doc://com.apple.metal/documentation/Metal/MTLPixelFormat/rg8Unorm","doc://com.apple.metal/documentation/Metal/MTLPixelFormat/rg8Unorm_srgb","doc://com.apple.metal/documentation/Metal/MTLPixelFormat/rg8Snorm","doc://com.apple.metal/documentation/Metal/MTLPixelFormat/rg8Sint"],"anchor":"Ordinary-16-Bit-Pixel-Formats","generated":true}]},{"path":"/primaryContentSections/0","op":"replace","value":{"declarations":[{"languages":["occ"],"tokens":[{"kind":"identifier","text":"MTLPixelFormatRG8Uint"}],"platforms":["iOS","iPadOS","Mac Catalyst","macOS","tvOS","visionOS"]}],"kind":"declarations"}},{"op":"replace","path":"/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLPixelFormat~1rg8Snorm/title","value":"MTLPixelFormatRG8Snorm"},{"op":"replace","path":"/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLPixelFormat~1rg8Snorm/fragments","value":[{"kind":"identifier","text":"MTLPixelFormatRG8Snorm"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLPixelFormat~1r16Unorm/title","value":"MTLPixelFormatR16Unorm"},{"value":[{"text":"MTLPixelFormatR16Unorm","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLPixelFormat~1r16Unorm/fragments","op":"replace"},{"value":"MTLPixelFormatR16Sint","path":"/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLPixelFormat~1r16Sint/title","op":"replace"},{"value":[{"text":"MTLPixelFormatR16Sint","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLPixelFormat~1r16Sint/fragments","op":"replace"},{"value":"MTLPixelFormatR16Snorm","path":"/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLPixelFormat~1r16Snorm/title","op":"replace"},{"value":[{"kind":"identifier","text":"MTLPixelFormatR16Snorm"}],"path":"/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLPixelFormat~1r16Snorm/fragments","op":"replace"},{"value":"MTLPixelFormat","path":"/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLPixelFormat/title","op":"replace"},{"value":[{"kind":"identifier","text":"MTLPixelFormat"}],"path":"/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLPixelFormat/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"MTLPixelFormat"}],"path":"/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLPixelFormat/navigatorTitle","op":"replace"},{"value":"MTLPixelFormatRG8Unorm_sRGB","path":"/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLPixelFormat~1rg8Unorm_srgb/title","op":"replace"},{"value":[{"kind":"identifier","text":"MTLPixelFormatRG8Unorm_sRGB"}],"path":"/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLPixelFormat~1rg8Unorm_srgb/fragments","op":"replace"},{"value":"MTLPixelFormatRG8Unorm","path":"/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLPixelFormat~1rg8Unorm/title","op":"replace"},{"value":[{"text":"MTLPixelFormatRG8Unorm","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLPixelFormat~1rg8Unorm/fragments","op":"replace"},{"op":"replace","path":"/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLPixelFormat~1r16Uint/title","value":"MTLPixelFormatR16Uint"},{"op":"replace","path":"/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLPixelFormat~1r16Uint/fragments","value":[{"text":"MTLPixelFormatR16Uint","kind":"identifier"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLPixelFormat~1rg8Uint/title","value":"MTLPixelFormatRG8Uint"},{"op":"replace","path":"/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLPixelFormat~1rg8Uint/fragments","value":[{"text":"MTLPixelFormatRG8Uint","kind":"identifier"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLPixelFormat~1r16Float/title","value":"MTLPixelFormatR16Float"},{"op":"replace","path":"/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLPixelFormat~1r16Float/fragments","value":[{"text":"MTLPixelFormatR16Float","kind":"identifier"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLPixelFormat~1rg8Sint/title","value":"MTLPixelFormatRG8Sint"},{"op":"replace","path":"/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLPixelFormat~1rg8Sint/fragments","value":[{"text":"MTLPixelFormatRG8Sint","kind":"identifier"}]}]}],"legalNotices":{"copyright":"Copyright &copy; 2025 Apple Inc. All rights reserved.","termsOfUse":"https://www.apple.com/legal/internet-services/terms/site.html","privacyPolicy":"https://www.apple.com/privacy/privacy-policy"}}