{"identifier":{"url":"doc://com.apple.metal/documentation/Metal/MTLPixelFormat/rg8Unorm_srgb","interfaceLanguage":"swift"},"schemaVersion":{"major":0,"minor":3,"patch":0},"variants":[{"paths":["/documentation/metal/mtlpixelformat/rg8unorm_srgb"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["/documentation/metal/mtlpixelformat/rg8unorm_srgb"],"traits":[{"interfaceLanguage":"occ"}]}],"metadata":{"fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"rg8Unorm_srgb"}],"modules":[{"name":"Metal"}],"platforms":[{"name":"iOS","beta":false,"introducedAt":"8.0","unavailable":false,"deprecated":false},{"name":"iPadOS","beta":false,"introducedAt":"8.0","unavailable":false,"deprecated":false},{"name":"Mac Catalyst","beta":false,"introducedAt":"14.0","unavailable":false,"deprecated":false},{"name":"macOS","introducedAt":"11.0","unavailable":false,"deprecated":false,"beta":false},{"name":"tvOS","unavailable":false,"deprecated":false,"beta":false},{"name":"visionOS","introducedAt":"1.0","unavailable":false,"deprecated":false,"beta":false}],"roleHeading":"Case","symbolKind":"case","externalID":"c:@E@MTLPixelFormat@MTLPixelFormatRG8Unorm_sRGB","navigatorTitle":[{"kind":"identifier","text":"MTLPixelFormatRG8Unorm_sRGB"}],"title":"MTLPixelFormat.rg8Unorm_srgb","role":"symbol"},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"rg8Unorm_srgb","kind":"identifier"}],"languages":["swift"],"platforms":["iOS","iPadOS","Mac Catalyst","macOS","tvOS","visionOS"]}]}],"kind":"symbol","seeAlsoSections":[{"anchor":"Ordinary-16-Bit-Pixel-Formats","title":"Ordinary 16-Bit Pixel Formats","generated":true,"identifiers":["doc://com.apple.metal/documentation/Metal/MTLPixelFormat/r16Unorm","doc://com.apple.metal/documentation/Metal/MTLPixelFormat/r16Snorm","doc://com.apple.metal/documentation/Metal/MTLPixelFormat/r16Uint","doc://com.apple.metal/documentation/Metal/MTLPixelFormat/r16Sint","doc://com.apple.metal/documentation/Metal/MTLPixelFormat/r16Float","doc://com.apple.metal/documentation/Metal/MTLPixelFormat/rg8Unorm","doc://com.apple.metal/documentation/Metal/MTLPixelFormat/rg8Snorm","doc://com.apple.metal/documentation/Metal/MTLPixelFormat/rg8Uint","doc://com.apple.metal/documentation/Metal/MTLPixelFormat/rg8Sint"]}],"abstract":[{"text":"Ordinary format with two 8-bit normalized unsigned integer components with conversion between sRGB and linear space.","type":"text"}],"hierarchy":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.metal/documentation/Metal","doc://com.apple.metal/documentation/Metal/MTLPixelFormat"]]},"sections":[],"references":{"doc://com.apple.metal/documentation/Metal":{"role":"collection","kind":"symbol","type":"topic","identifier":"doc://com.apple.metal/documentation/Metal","title":"Metal","abstract":[{"text":"Render advanced 3D graphics and compute data in parallel with graphics processors.","type":"text"}],"url":"/documentation/metal"},"doc://com.apple.metal/documentation/Metal/MTLPixelFormat/r16Uint":{"navigatorTitle":[{"text":"MTLPixelFormatR16Uint","kind":"identifier"}],"identifier":"doc://com.apple.metal/documentation/Metal/MTLPixelFormat/r16Uint","role":"symbol","type":"topic","title":"MTLPixelFormat.r16Uint","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"r16Uint","kind":"identifier"}],"kind":"symbol","abstract":[{"text":"Ordinary format with one 16-bit unsigned integer component.","type":"text"}],"url":"/documentation/metal/mtlpixelformat/r16uint"},"doc://com.apple.metal/documentation/Metal/MTLPixelFormat/rg8Unorm":{"title":"MTLPixelFormat.rg8Unorm","kind":"symbol","role":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"rg8Unorm"}],"navigatorTitle":[{"kind":"identifier","text":"MTLPixelFormatRG8Unorm"}],"identifier":"doc://com.apple.metal/documentation/Metal/MTLPixelFormat/rg8Unorm","url":"/documentation/metal/mtlpixelformat/rg8unorm","abstract":[{"text":"Ordinary format with two 8-bit normalized unsigned integer components.","type":"text"}]},"doc://com.apple.metal/documentation/Metal/MTLPixelFormat/rg8Snorm":{"kind":"symbol","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"rg8Snorm"}],"abstract":[{"text":"Ordinary format with two 8-bit normalized signed integer components.","type":"text"}],"role":"symbol","identifier":"doc://com.apple.metal/documentation/Metal/MTLPixelFormat/rg8Snorm","type":"topic","url":"/documentation/metal/mtlpixelformat/rg8snorm","navigatorTitle":[{"kind":"identifier","text":"MTLPixelFormatRG8Snorm"}],"title":"MTLPixelFormat.rg8Snorm"},"doc://com.apple.metal/documentation/Metal/MTLPixelFormat/r16Snorm":{"type":"topic","abstract":[{"text":"Ordinary format with one 16-bit normalized signed integer component.","type":"text"}],"role":"symbol","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"r16Snorm","kind":"identifier"}],"identifier":"doc://com.apple.metal/documentation/Metal/MTLPixelFormat/r16Snorm","title":"MTLPixelFormat.r16Snorm","navigatorTitle":[{"text":"MTLPixelFormatR16Snorm","kind":"identifier"}],"url":"/documentation/metal/mtlpixelformat/r16snorm","kind":"symbol"},"doc://com.apple.metal/documentation/Metal/MTLPixelFormat":{"role":"symbol","identifier":"doc://com.apple.metal/documentation/Metal/MTLPixelFormat","title":"MTLPixelFormat","kind":"symbol","type":"topic","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MTLPixelFormat","kind":"identifier"}],"url":"/documentation/metal/mtlpixelformat","abstract":[{"text":"The data formats that describe the organization and characteristics of individual pixels in a texture.","type":"text"}],"navigatorTitle":[{"text":"MTLPixelFormat","kind":"identifier"}]},"doc://com.apple.documentation/documentation/technologies":{"role":"overview","kind":"technologies","type":"topic","identifier":"doc://com.apple.documentation/documentation/technologies","title":"Technologies","abstract":[{"text":"","type":"text"}],"url":"/documentation/technologies"},"doc://com.apple.metal/documentation/Metal/MTLPixelFormat/r16Sint":{"kind":"symbol","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"r16Sint","kind":"identifier"}],"abstract":[{"text":"Ordinary format with one 16-bit signed integer component.","type":"text"}],"role":"symbol","identifier":"doc://com.apple.metal/documentation/Metal/MTLPixelFormat/r16Sint","type":"topic","url":"/documentation/metal/mtlpixelformat/r16sint","navigatorTitle":[{"kind":"identifier","text":"MTLPixelFormatR16Sint"}],"title":"MTLPixelFormat.r16Sint"},"doc://com.apple.metal/documentation/Metal/MTLPixelFormat/rg8Unorm_srgb":{"title":"MTLPixelFormat.rg8Unorm_srgb","url":"/documentation/metal/mtlpixelformat/rg8unorm_srgb","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"rg8Unorm_srgb"}],"role":"symbol","abstract":[{"type":"text","text":"Ordinary format with two 8-bit normalized unsigned integer components with conversion between sRGB and linear space."}],"identifier":"doc://com.apple.metal/documentation/Metal/MTLPixelFormat/rg8Unorm_srgb","type":"topic","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"MTLPixelFormatRG8Unorm_sRGB"}]},"doc://com.apple.metal/documentation/Metal/MTLPixelFormat/r16Float":{"identifier":"doc://com.apple.metal/documentation/Metal/MTLPixelFormat/r16Float","kind":"symbol","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"r16Float","kind":"identifier"}],"role":"symbol","navigatorTitle":[{"text":"MTLPixelFormatR16Float","kind":"identifier"}],"type":"topic","title":"MTLPixelFormat.r16Float","abstract":[{"text":"Ordinary format with one 16-bit floating-point component.","type":"text"}],"url":"/documentation/metal/mtlpixelformat/r16float"},"doc://com.apple.metal/documentation/Metal/MTLPixelFormat/rg8Sint":{"url":"/documentation/metal/mtlpixelformat/rg8sint","role":"symbol","navigatorTitle":[{"text":"MTLPixelFormatRG8Sint","kind":"identifier"}],"kind":"symbol","abstract":[{"type":"text","text":"Ordinary format with two 8-bit signed integer components."}],"title":"MTLPixelFormat.rg8Sint","type":"topic","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"rg8Sint","kind":"identifier"}],"identifier":"doc://com.apple.metal/documentation/Metal/MTLPixelFormat/rg8Sint"},"doc://com.apple.metal/documentation/Metal/MTLPixelFormat/r16Unorm":{"title":"MTLPixelFormat.r16Unorm","abstract":[{"text":"Ordinary format with one 16-bit normalized unsigned integer component.","type":"text"}],"fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"r16Unorm"}],"type":"topic","navigatorTitle":[{"kind":"identifier","text":"MTLPixelFormatR16Unorm"}],"url":"/documentation/metal/mtlpixelformat/r16unorm","role":"symbol","kind":"symbol","identifier":"doc://com.apple.metal/documentation/Metal/MTLPixelFormat/r16Unorm"},"doc://com.apple.metal/documentation/Metal/MTLPixelFormat/rg8Uint":{"navigatorTitle":[{"kind":"identifier","text":"MTLPixelFormatRG8Uint"}],"abstract":[{"type":"text","text":"Ordinary format with two 8-bit unsigned integer components."}],"identifier":"doc://com.apple.metal/documentation/Metal/MTLPixelFormat/rg8Uint","kind":"symbol","type":"topic","url":"/documentation/metal/mtlpixelformat/rg8uint","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"rg8Uint"}],"role":"symbol","title":"MTLPixelFormat.rg8Uint"}},"variantOverrides":[{"patch":[{"path":"/identifier/interfaceLanguage","value":"occ","op":"replace"},{"path":"/metadata/platforms","value":[{"name":"iOS","introducedAt":"8.0","unavailable":false,"deprecated":false,"beta":false},{"name":"iPadOS","introducedAt":"8.0","unavailable":false,"deprecated":false,"beta":false},{"name":"Mac Catalyst","introducedAt":"14.0","unavailable":false,"deprecated":false,"beta":false},{"name":"macOS","introducedAt":"11.0","unavailable":false,"deprecated":false,"beta":false},{"name":"tvOS","unavailable":false,"deprecated":false,"beta":false},{"name":"visionOS","introducedAt":"1.0","unavailable":false,"deprecated":false,"beta":false}],"op":"replace"},{"path":"/metadata/roleHeading","op":"replace","value":"Enumeration Case"},{"path":"/metadata/title","op":"replace","value":"MTLPixelFormatRG8Unorm_sRGB"},{"path":"/metadata/symbolKind","op":"replace","value":"case"},{"path":"/metadata/fragments","op":"replace","value":[{"text":"MTLPixelFormatRG8Unorm_sRGB","kind":"identifier"}]},{"path":"/hierarchy","op":"replace","value":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.metal/documentation/Metal","doc://com.apple.metal/documentation/Metal/MTLPixelFormat"]]}},{"path":"/topicSections","op":"add","value":null},{"path":"/relationshipsSections","op":"add","value":null},{"path":"/seeAlsoSections","op":"replace","value":[{"identifiers":["doc://com.apple.metal/documentation/Metal/MTLPixelFormat/r16Unorm","doc://com.apple.metal/documentation/Metal/MTLPixelFormat/r16Snorm","doc://com.apple.metal/documentation/Metal/MTLPixelFormat/r16Uint","doc://com.apple.metal/documentation/Metal/MTLPixelFormat/r16Sint","doc://com.apple.metal/documentation/Metal/MTLPixelFormat/r16Float","doc://com.apple.metal/documentation/Metal/MTLPixelFormat/rg8Unorm","doc://com.apple.metal/documentation/Metal/MTLPixelFormat/rg8Snorm","doc://com.apple.metal/documentation/Metal/MTLPixelFormat/rg8Uint","doc://com.apple.metal/documentation/Metal/MTLPixelFormat/rg8Sint"],"generated":true,"anchor":"Ordinary-16-Bit-Pixel-Formats","title":"Ordinary 16-Bit Pixel Formats"}]},{"path":"/primaryContentSections/0","op":"replace","value":{"declarations":[{"languages":["occ"],"tokens":[{"kind":"identifier","text":"MTLPixelFormatRG8Unorm_sRGB"}],"platforms":["iOS","iPadOS","Mac Catalyst","macOS","tvOS","visionOS"]}],"kind":"declarations"}},{"op":"replace","path":"/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLPixelFormat~1r16Uint/title","value":"MTLPixelFormatR16Uint"},{"op":"replace","path":"/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLPixelFormat~1r16Uint/fragments","value":[{"kind":"identifier","text":"MTLPixelFormatR16Uint"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLPixelFormat~1rg8Unorm/title","value":"MTLPixelFormatRG8Unorm"},{"op":"replace","path":"/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLPixelFormat~1rg8Unorm/fragments","value":[{"kind":"identifier","text":"MTLPixelFormatRG8Unorm"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLPixelFormat~1rg8Snorm/title","value":"MTLPixelFormatRG8Snorm"},{"op":"replace","path":"/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLPixelFormat~1rg8Snorm/fragments","value":[{"kind":"identifier","text":"MTLPixelFormatRG8Snorm"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLPixelFormat~1r16Snorm/title","value":"MTLPixelFormatR16Snorm"},{"op":"replace","path":"/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLPixelFormat~1r16Snorm/fragments","value":[{"text":"MTLPixelFormatR16Snorm","kind":"identifier"}]},{"value":"MTLPixelFormat","op":"replace","path":"/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLPixelFormat/title"},{"value":[{"text":"MTLPixelFormat","kind":"identifier"}],"op":"replace","path":"/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLPixelFormat/fragments"},{"value":[{"kind":"identifier","text":"MTLPixelFormat"}],"op":"replace","path":"/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLPixelFormat/navigatorTitle"},{"value":"MTLPixelFormatR16Sint","op":"replace","path":"/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLPixelFormat~1r16Sint/title"},{"value":[{"text":"MTLPixelFormatR16Sint","kind":"identifier"}],"op":"replace","path":"/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLPixelFormat~1r16Sint/fragments"},{"value":"MTLPixelFormatRG8Unorm_sRGB","op":"replace","path":"/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLPixelFormat~1rg8Unorm_srgb/title"},{"value":[{"kind":"identifier","text":"MTLPixelFormatRG8Unorm_sRGB"}],"op":"replace","path":"/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLPixelFormat~1rg8Unorm_srgb/fragments"},{"value":"MTLPixelFormatR16Float","op":"replace","path":"/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLPixelFormat~1r16Float/title"},{"value":[{"text":"MTLPixelFormatR16Float","kind":"identifier"}],"op":"replace","path":"/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLPixelFormat~1r16Float/fragments"},{"value":"MTLPixelFormatRG8Sint","op":"replace","path":"/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLPixelFormat~1rg8Sint/title"},{"value":[{"kind":"identifier","text":"MTLPixelFormatRG8Sint"}],"op":"replace","path":"/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLPixelFormat~1rg8Sint/fragments"},{"value":"MTLPixelFormatR16Unorm","op":"replace","path":"/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLPixelFormat~1r16Unorm/title"},{"value":[{"text":"MTLPixelFormatR16Unorm","kind":"identifier"}],"op":"replace","path":"/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLPixelFormat~1r16Unorm/fragments"},{"value":"MTLPixelFormatRG8Uint","op":"replace","path":"/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLPixelFormat~1rg8Uint/title"},{"value":[{"kind":"identifier","text":"MTLPixelFormatRG8Uint"}],"op":"replace","path":"/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLPixelFormat~1rg8Uint/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}],"legalNotices":{"copyright":"Copyright &copy; 2025 Apple Inc. All rights reserved.","termsOfUse":"https://www.apple.com/legal/internet-services/terms/site.html","privacyPolicy":"https://www.apple.com/privacy/privacy-policy"}}