{
  "abstract": [
    {
      "text": "Ordinary format with four 16-bit signed integer components in RGBA order.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.metal/documentation/Metal",
        "doc://com.apple.metal/documentation/Metal/MTLPixelFormat"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.metal/documentation/Metal/MTLPixelFormat/rgba16Sint"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@MTLPixelFormat@MTLPixelFormatRGBA16Sint",
    "fragments": [
      {
        "kind": "keyword",
        "text": "case"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "rgba16Sint"
      }
    ],
    "modules": [
      {
        "name": "Metal"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "MTLPixelFormatRGBA16Sint"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "8.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "8.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.1",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.11",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Case",
    "symbolKind": "case",
    "title": "MTLPixelFormat.rgba16Sint"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "case"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "rgba16Sint"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.metal/documentation/Metal": {
      "abstract": [
        {
          "text": "Render advanced 3D graphics and compute data in parallel with graphics processors.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal",
      "kind": "symbol",
      "role": "collection",
      "title": "Metal",
      "type": "topic",
      "url": "/documentation/metal"
    },
    "doc://com.apple.metal/documentation/Metal/MTLPixelFormat": {
      "abstract": [
        {
          "text": "The data formats that describe the organization and characteristics of individual pixels in a texture.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MTLPixelFormat"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLPixelFormat",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTLPixelFormat"
        }
      ],
      "role": "symbol",
      "title": "MTLPixelFormat",
      "type": "topic",
      "url": "/documentation/metal/mtlpixelformat"
    },
    "doc://com.apple.metal/documentation/Metal/MTLPixelFormat/rg32Float": {
      "abstract": [
        {
          "text": "Ordinary format with two 32-bit floating-point components.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "rg32Float"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLPixelFormat/rg32Float",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTLPixelFormatRG32Float"
        }
      ],
      "role": "symbol",
      "title": "MTLPixelFormat.rg32Float",
      "type": "topic",
      "url": "/documentation/metal/mtlpixelformat/rg32float"
    },
    "doc://com.apple.metal/documentation/Metal/MTLPixelFormat/rg32Sint": {
      "abstract": [
        {
          "text": "Ordinary format with two 32-bit signed integer components.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "rg32Sint"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLPixelFormat/rg32Sint",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTLPixelFormatRG32Sint"
        }
      ],
      "role": "symbol",
      "title": "MTLPixelFormat.rg32Sint",
      "type": "topic",
      "url": "/documentation/metal/mtlpixelformat/rg32sint"
    },
    "doc://com.apple.metal/documentation/Metal/MTLPixelFormat/rg32Uint": {
      "abstract": [
        {
          "text": "Ordinary format with two 32-bit unsigned integer components.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "rg32Uint"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLPixelFormat/rg32Uint",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTLPixelFormatRG32Uint"
        }
      ],
      "role": "symbol",
      "title": "MTLPixelFormat.rg32Uint",
      "type": "topic",
      "url": "/documentation/metal/mtlpixelformat/rg32uint"
    },
    "doc://com.apple.metal/documentation/Metal/MTLPixelFormat/rgba16Float": {
      "abstract": [
        {
          "text": "Ordinary format with four 16-bit floating-point components in RGBA order.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "rgba16Float"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLPixelFormat/rgba16Float",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTLPixelFormatRGBA16Float"
        }
      ],
      "role": "symbol",
      "title": "MTLPixelFormat.rgba16Float",
      "type": "topic",
      "url": "/documentation/metal/mtlpixelformat/rgba16float"
    },
    "doc://com.apple.metal/documentation/Metal/MTLPixelFormat/rgba16Sint": {
      "abstract": [
        {
          "text": "Ordinary format with four 16-bit signed integer components in RGBA order.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "rgba16Sint"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLPixelFormat/rgba16Sint",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTLPixelFormatRGBA16Sint"
        }
      ],
      "role": "symbol",
      "title": "MTLPixelFormat.rgba16Sint",
      "type": "topic",
      "url": "/documentation/metal/mtlpixelformat/rgba16sint"
    },
    "doc://com.apple.metal/documentation/Metal/MTLPixelFormat/rgba16Snorm": {
      "abstract": [
        {
          "text": "Ordinary format with four 16-bit normalized signed integer components in RGBA order.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "rgba16Snorm"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLPixelFormat/rgba16Snorm",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTLPixelFormatRGBA16Snorm"
        }
      ],
      "role": "symbol",
      "title": "MTLPixelFormat.rgba16Snorm",
      "type": "topic",
      "url": "/documentation/metal/mtlpixelformat/rgba16snorm"
    },
    "doc://com.apple.metal/documentation/Metal/MTLPixelFormat/rgba16Uint": {
      "abstract": [
        {
          "text": "Ordinary format with four 16-bit unsigned integer components in RGBA order.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "rgba16Uint"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLPixelFormat/rgba16Uint",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTLPixelFormatRGBA16Uint"
        }
      ],
      "role": "symbol",
      "title": "MTLPixelFormat.rgba16Uint",
      "type": "topic",
      "url": "/documentation/metal/mtlpixelformat/rgba16uint"
    },
    "doc://com.apple.metal/documentation/Metal/MTLPixelFormat/rgba16Unorm": {
      "abstract": [
        {
          "text": "Ordinary format with four 16-bit normalized unsigned integer components in RGBA order.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "rgba16Unorm"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLPixelFormat/rgba16Unorm",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTLPixelFormatRGBA16Unorm"
        }
      ],
      "role": "symbol",
      "title": "MTLPixelFormat.rgba16Unorm",
      "type": "topic",
      "url": "/documentation/metal/mtlpixelformat/rgba16unorm"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Ordinary-64-Bit-Pixel-Formats",
      "generated": true,
      "identifiers": [
        "doc://com.apple.metal/documentation/Metal/MTLPixelFormat/rg32Uint",
        "doc://com.apple.metal/documentation/Metal/MTLPixelFormat/rg32Sint",
        "doc://com.apple.metal/documentation/Metal/MTLPixelFormat/rg32Float",
        "doc://com.apple.metal/documentation/Metal/MTLPixelFormat/rgba16Unorm",
        "doc://com.apple.metal/documentation/Metal/MTLPixelFormat/rgba16Snorm",
        "doc://com.apple.metal/documentation/Metal/MTLPixelFormat/rgba16Uint",
        "doc://com.apple.metal/documentation/Metal/MTLPixelFormat/rgba16Float"
      ],
      "title": "Ordinary 64-Bit Pixel Formats"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "8.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "8.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.1",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.11",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration Case"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "MTLPixelFormatRGBA16Sint"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "case"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLPixelFormatRGBA16Sint"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.metal/documentation/Metal",
                "doc://com.apple.metal/documentation/Metal/MTLPixelFormat"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Ordinary-64-Bit-Pixel-Formats",
              "generated": true,
              "identifiers": [
                "doc://com.apple.metal/documentation/Metal/MTLPixelFormat/rg32Uint",
                "doc://com.apple.metal/documentation/Metal/MTLPixelFormat/rg32Sint",
                "doc://com.apple.metal/documentation/Metal/MTLPixelFormat/rg32Float",
                "doc://com.apple.metal/documentation/Metal/MTLPixelFormat/rgba16Unorm",
                "doc://com.apple.metal/documentation/Metal/MTLPixelFormat/rgba16Snorm",
                "doc://com.apple.metal/documentation/Metal/MTLPixelFormat/rgba16Uint",
                "doc://com.apple.metal/documentation/Metal/MTLPixelFormat/rgba16Float"
              ],
              "title": "Ordinary 64-Bit Pixel Formats"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS"
                ],
                "tokens": [
                  {
                    "kind": "identifier",
                    "text": "MTLPixelFormatRGBA16Sint"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLPixelFormat~1rgba16Float/title",
          "value": "MTLPixelFormatRGBA16Float"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLPixelFormat~1rgba16Float/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLPixelFormatRGBA16Float"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLPixelFormat~1rg32Uint/title",
          "value": "MTLPixelFormatRG32Uint"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLPixelFormat~1rg32Uint/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLPixelFormatRG32Uint"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLPixelFormat~1rgba16Sint/title",
          "value": "MTLPixelFormatRGBA16Sint"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLPixelFormat~1rgba16Sint/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLPixelFormatRGBA16Sint"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLPixelFormat/title",
          "value": "MTLPixelFormat"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLPixelFormat/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLPixelFormat"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLPixelFormat/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLPixelFormat"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLPixelFormat~1rgba16Uint/title",
          "value": "MTLPixelFormatRGBA16Uint"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLPixelFormat~1rgba16Uint/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLPixelFormatRGBA16Uint"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLPixelFormat~1rg32Float/title",
          "value": "MTLPixelFormatRG32Float"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLPixelFormat~1rg32Float/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLPixelFormatRG32Float"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLPixelFormat~1rg32Sint/title",
          "value": "MTLPixelFormatRG32Sint"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLPixelFormat~1rg32Sint/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLPixelFormatRG32Sint"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLPixelFormat~1rgba16Snorm/title",
          "value": "MTLPixelFormatRGBA16Snorm"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLPixelFormat~1rgba16Snorm/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLPixelFormatRGBA16Snorm"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLPixelFormat~1rgba16Unorm/title",
          "value": "MTLPixelFormatRGBA16Unorm"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLPixelFormat~1rgba16Unorm/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLPixelFormatRGBA16Unorm"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/metal/mtlpixelformat/rgba16sint"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/metal/mtlpixelformat/rgba16sint"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
