{
  "abstract": [
    {
      "text": "Ordinary format with four 8-bit normalized unsigned integer components in RGBA order with conversion between sRGB and linear space.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.metal/documentation/Metal",
        "doc://com.apple.metal/documentation/Metal/MTLPixelFormat"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.metal/documentation/Metal/MTLPixelFormat/rgba8Unorm_srgb"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@MTLPixelFormat@MTLPixelFormatRGBA8Unorm_sRGB",
    "fragments": [
      {
        "kind": "keyword",
        "text": "case"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "rgba8Unorm_srgb"
      }
    ],
    "modules": [
      {
        "name": "Metal"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "MTLPixelFormatRGBA8Unorm_sRGB"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "8.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "8.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.1",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.11",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Case",
    "symbolKind": "case",
    "title": "MTLPixelFormat.rgba8Unorm_srgb"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "case"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "rgba8Unorm_srgb"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.metal/documentation/Metal": {
      "abstract": [
        {
          "text": "Render advanced 3D graphics and compute data in parallel with graphics processors.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal",
      "kind": "symbol",
      "role": "collection",
      "title": "Metal",
      "type": "topic",
      "url": "/documentation/metal"
    },
    "doc://com.apple.metal/documentation/Metal/MTLPixelFormat": {
      "abstract": [
        {
          "text": "The data formats that describe the organization and characteristics of individual pixels in a texture.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MTLPixelFormat"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLPixelFormat",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTLPixelFormat"
        }
      ],
      "role": "symbol",
      "title": "MTLPixelFormat",
      "type": "topic",
      "url": "/documentation/metal/mtlpixelformat"
    },
    "doc://com.apple.metal/documentation/Metal/MTLPixelFormat/bgra8Unorm": {
      "abstract": [
        {
          "text": "Ordinary format with four 8-bit normalized unsigned integer components in BGRA order.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "bgra8Unorm"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLPixelFormat/bgra8Unorm",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTLPixelFormatBGRA8Unorm"
        }
      ],
      "role": "symbol",
      "title": "MTLPixelFormat.bgra8Unorm",
      "type": "topic",
      "url": "/documentation/metal/mtlpixelformat/bgra8unorm"
    },
    "doc://com.apple.metal/documentation/Metal/MTLPixelFormat/bgra8Unorm_srgb": {
      "abstract": [
        {
          "text": "Ordinary format with four 8-bit normalized unsigned integer components in BGRA order with conversion between sRGB and linear space.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "bgra8Unorm_srgb"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLPixelFormat/bgra8Unorm_srgb",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTLPixelFormatBGRA8Unorm_sRGB"
        }
      ],
      "role": "symbol",
      "title": "MTLPixelFormat.bgra8Unorm_srgb",
      "type": "topic",
      "url": "/documentation/metal/mtlpixelformat/bgra8unorm_srgb"
    },
    "doc://com.apple.metal/documentation/Metal/MTLPixelFormat/r32Float": {
      "abstract": [
        {
          "text": "Ordinary format with one 32-bit floating-point component.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "r32Float"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLPixelFormat/r32Float",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTLPixelFormatR32Float"
        }
      ],
      "role": "symbol",
      "title": "MTLPixelFormat.r32Float",
      "type": "topic",
      "url": "/documentation/metal/mtlpixelformat/r32float"
    },
    "doc://com.apple.metal/documentation/Metal/MTLPixelFormat/r32Sint": {
      "abstract": [
        {
          "text": "Ordinary format with one 32-bit signed integer component.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "r32Sint"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLPixelFormat/r32Sint",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTLPixelFormatR32Sint"
        }
      ],
      "role": "symbol",
      "title": "MTLPixelFormat.r32Sint",
      "type": "topic",
      "url": "/documentation/metal/mtlpixelformat/r32sint"
    },
    "doc://com.apple.metal/documentation/Metal/MTLPixelFormat/r32Uint": {
      "abstract": [
        {
          "text": "Ordinary format with one 32-bit unsigned integer component.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "r32Uint"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLPixelFormat/r32Uint",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTLPixelFormatR32Uint"
        }
      ],
      "role": "symbol",
      "title": "MTLPixelFormat.r32Uint",
      "type": "topic",
      "url": "/documentation/metal/mtlpixelformat/r32uint"
    },
    "doc://com.apple.metal/documentation/Metal/MTLPixelFormat/rg16Float": {
      "abstract": [
        {
          "text": "Ordinary format with two 16-bit floating-point components.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "rg16Float"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLPixelFormat/rg16Float",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTLPixelFormatRG16Float"
        }
      ],
      "role": "symbol",
      "title": "MTLPixelFormat.rg16Float",
      "type": "topic",
      "url": "/documentation/metal/mtlpixelformat/rg16float"
    },
    "doc://com.apple.metal/documentation/Metal/MTLPixelFormat/rg16Sint": {
      "abstract": [
        {
          "text": "Ordinary format with two 16-bit signed integer components.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "rg16Sint"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLPixelFormat/rg16Sint",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTLPixelFormatRG16Sint"
        }
      ],
      "role": "symbol",
      "title": "MTLPixelFormat.rg16Sint",
      "type": "topic",
      "url": "/documentation/metal/mtlpixelformat/rg16sint"
    },
    "doc://com.apple.metal/documentation/Metal/MTLPixelFormat/rg16Snorm": {
      "abstract": [
        {
          "text": "Ordinary format with two 16-bit normalized signed integer components.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "rg16Snorm"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLPixelFormat/rg16Snorm",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTLPixelFormatRG16Snorm"
        }
      ],
      "role": "symbol",
      "title": "MTLPixelFormat.rg16Snorm",
      "type": "topic",
      "url": "/documentation/metal/mtlpixelformat/rg16snorm"
    },
    "doc://com.apple.metal/documentation/Metal/MTLPixelFormat/rg16Uint": {
      "abstract": [
        {
          "text": "Ordinary format with two 16-bit unsigned integer components.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "rg16Uint"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLPixelFormat/rg16Uint",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTLPixelFormatRG16Uint"
        }
      ],
      "role": "symbol",
      "title": "MTLPixelFormat.rg16Uint",
      "type": "topic",
      "url": "/documentation/metal/mtlpixelformat/rg16uint"
    },
    "doc://com.apple.metal/documentation/Metal/MTLPixelFormat/rg16Unorm": {
      "abstract": [
        {
          "text": "Ordinary format with two 16-bit normalized unsigned integer components.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "rg16Unorm"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLPixelFormat/rg16Unorm",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTLPixelFormatRG16Unorm"
        }
      ],
      "role": "symbol",
      "title": "MTLPixelFormat.rg16Unorm",
      "type": "topic",
      "url": "/documentation/metal/mtlpixelformat/rg16unorm"
    },
    "doc://com.apple.metal/documentation/Metal/MTLPixelFormat/rgba8Sint": {
      "abstract": [
        {
          "text": "Ordinary format with four 8-bit signed integer components in RGBA order.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "rgba8Sint"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLPixelFormat/rgba8Sint",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTLPixelFormatRGBA8Sint"
        }
      ],
      "role": "symbol",
      "title": "MTLPixelFormat.rgba8Sint",
      "type": "topic",
      "url": "/documentation/metal/mtlpixelformat/rgba8sint"
    },
    "doc://com.apple.metal/documentation/Metal/MTLPixelFormat/rgba8Snorm": {
      "abstract": [
        {
          "text": "Ordinary format with four 8-bit normalized signed integer components in RGBA order.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "rgba8Snorm"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLPixelFormat/rgba8Snorm",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTLPixelFormatRGBA8Snorm"
        }
      ],
      "role": "symbol",
      "title": "MTLPixelFormat.rgba8Snorm",
      "type": "topic",
      "url": "/documentation/metal/mtlpixelformat/rgba8snorm"
    },
    "doc://com.apple.metal/documentation/Metal/MTLPixelFormat/rgba8Uint": {
      "abstract": [
        {
          "text": "Ordinary format with four 8-bit unsigned integer components in RGBA order.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "rgba8Uint"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLPixelFormat/rgba8Uint",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTLPixelFormatRGBA8Uint"
        }
      ],
      "role": "symbol",
      "title": "MTLPixelFormat.rgba8Uint",
      "type": "topic",
      "url": "/documentation/metal/mtlpixelformat/rgba8uint"
    },
    "doc://com.apple.metal/documentation/Metal/MTLPixelFormat/rgba8Unorm": {
      "abstract": [
        {
          "text": "Ordinary format with four 8-bit normalized unsigned integer components in RGBA order.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "rgba8Unorm"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLPixelFormat/rgba8Unorm",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTLPixelFormatRGBA8Unorm"
        }
      ],
      "role": "symbol",
      "title": "MTLPixelFormat.rgba8Unorm",
      "type": "topic",
      "url": "/documentation/metal/mtlpixelformat/rgba8unorm"
    },
    "doc://com.apple.metal/documentation/Metal/MTLPixelFormat/rgba8Unorm_srgb": {
      "abstract": [
        {
          "text": "Ordinary format with four 8-bit normalized unsigned integer components in RGBA order with conversion between sRGB and linear space.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "rgba8Unorm_srgb"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLPixelFormat/rgba8Unorm_srgb",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTLPixelFormatRGBA8Unorm_sRGB"
        }
      ],
      "role": "symbol",
      "title": "MTLPixelFormat.rgba8Unorm_srgb",
      "type": "topic",
      "url": "/documentation/metal/mtlpixelformat/rgba8unorm_srgb"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Ordinary-32-Bit-Pixel-Formats",
      "generated": true,
      "identifiers": [
        "doc://com.apple.metal/documentation/Metal/MTLPixelFormat/r32Uint",
        "doc://com.apple.metal/documentation/Metal/MTLPixelFormat/r32Sint",
        "doc://com.apple.metal/documentation/Metal/MTLPixelFormat/r32Float",
        "doc://com.apple.metal/documentation/Metal/MTLPixelFormat/rg16Unorm",
        "doc://com.apple.metal/documentation/Metal/MTLPixelFormat/rg16Snorm",
        "doc://com.apple.metal/documentation/Metal/MTLPixelFormat/rg16Uint",
        "doc://com.apple.metal/documentation/Metal/MTLPixelFormat/rg16Sint",
        "doc://com.apple.metal/documentation/Metal/MTLPixelFormat/rg16Float",
        "doc://com.apple.metal/documentation/Metal/MTLPixelFormat/rgba8Unorm",
        "doc://com.apple.metal/documentation/Metal/MTLPixelFormat/rgba8Snorm",
        "doc://com.apple.metal/documentation/Metal/MTLPixelFormat/rgba8Uint",
        "doc://com.apple.metal/documentation/Metal/MTLPixelFormat/rgba8Sint",
        "doc://com.apple.metal/documentation/Metal/MTLPixelFormat/bgra8Unorm",
        "doc://com.apple.metal/documentation/Metal/MTLPixelFormat/bgra8Unorm_srgb"
      ],
      "title": "Ordinary 32-Bit Pixel Formats"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "8.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "8.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.1",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.11",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration Case"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "MTLPixelFormatRGBA8Unorm_sRGB"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "case"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLPixelFormatRGBA8Unorm_sRGB"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.metal/documentation/Metal",
                "doc://com.apple.metal/documentation/Metal/MTLPixelFormat"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Ordinary-32-Bit-Pixel-Formats",
              "generated": true,
              "identifiers": [
                "doc://com.apple.metal/documentation/Metal/MTLPixelFormat/r32Uint",
                "doc://com.apple.metal/documentation/Metal/MTLPixelFormat/r32Sint",
                "doc://com.apple.metal/documentation/Metal/MTLPixelFormat/r32Float",
                "doc://com.apple.metal/documentation/Metal/MTLPixelFormat/rg16Unorm",
                "doc://com.apple.metal/documentation/Metal/MTLPixelFormat/rg16Snorm",
                "doc://com.apple.metal/documentation/Metal/MTLPixelFormat/rg16Uint",
                "doc://com.apple.metal/documentation/Metal/MTLPixelFormat/rg16Sint",
                "doc://com.apple.metal/documentation/Metal/MTLPixelFormat/rg16Float",
                "doc://com.apple.metal/documentation/Metal/MTLPixelFormat/rgba8Unorm",
                "doc://com.apple.metal/documentation/Metal/MTLPixelFormat/rgba8Snorm",
                "doc://com.apple.metal/documentation/Metal/MTLPixelFormat/rgba8Uint",
                "doc://com.apple.metal/documentation/Metal/MTLPixelFormat/rgba8Sint",
                "doc://com.apple.metal/documentation/Metal/MTLPixelFormat/bgra8Unorm",
                "doc://com.apple.metal/documentation/Metal/MTLPixelFormat/bgra8Unorm_srgb"
              ],
              "title": "Ordinary 32-Bit Pixel Formats"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS"
                ],
                "tokens": [
                  {
                    "kind": "identifier",
                    "text": "MTLPixelFormatRGBA8Unorm_sRGB"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLPixelFormat~1rg16Float/title",
          "value": "MTLPixelFormatRG16Float"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLPixelFormat~1rg16Float/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLPixelFormatRG16Float"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLPixelFormat~1rgba8Uint/title",
          "value": "MTLPixelFormatRGBA8Uint"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLPixelFormat~1rgba8Uint/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLPixelFormatRGBA8Uint"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLPixelFormat~1rgba8Unorm_srgb/title",
          "value": "MTLPixelFormatRGBA8Unorm_sRGB"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLPixelFormat~1rgba8Unorm_srgb/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLPixelFormatRGBA8Unorm_sRGB"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLPixelFormat~1bgra8Unorm/title",
          "value": "MTLPixelFormatBGRA8Unorm"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLPixelFormat~1bgra8Unorm/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLPixelFormatBGRA8Unorm"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLPixelFormat~1rg16Snorm/title",
          "value": "MTLPixelFormatRG16Snorm"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLPixelFormat~1rg16Snorm/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLPixelFormatRG16Snorm"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLPixelFormat~1rgba8Snorm/title",
          "value": "MTLPixelFormatRGBA8Snorm"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLPixelFormat~1rgba8Snorm/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLPixelFormatRGBA8Snorm"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLPixelFormat~1r32Uint/title",
          "value": "MTLPixelFormatR32Uint"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLPixelFormat~1r32Uint/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLPixelFormatR32Uint"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLPixelFormat~1rgba8Sint/title",
          "value": "MTLPixelFormatRGBA8Sint"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLPixelFormat~1rgba8Sint/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLPixelFormatRGBA8Sint"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLPixelFormat~1rg16Sint/title",
          "value": "MTLPixelFormatRG16Sint"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLPixelFormat~1rg16Sint/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLPixelFormatRG16Sint"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLPixelFormat/title",
          "value": "MTLPixelFormat"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLPixelFormat/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLPixelFormat"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLPixelFormat/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLPixelFormat"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLPixelFormat~1rgba8Unorm/title",
          "value": "MTLPixelFormatRGBA8Unorm"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLPixelFormat~1rgba8Unorm/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLPixelFormatRGBA8Unorm"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLPixelFormat~1bgra8Unorm_srgb/title",
          "value": "MTLPixelFormatBGRA8Unorm_sRGB"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLPixelFormat~1bgra8Unorm_srgb/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLPixelFormatBGRA8Unorm_sRGB"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLPixelFormat~1r32Sint/title",
          "value": "MTLPixelFormatR32Sint"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLPixelFormat~1r32Sint/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLPixelFormatR32Sint"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLPixelFormat~1rg16Uint/title",
          "value": "MTLPixelFormatRG16Uint"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLPixelFormat~1rg16Uint/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLPixelFormatRG16Uint"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLPixelFormat~1rg16Unorm/title",
          "value": "MTLPixelFormatRG16Unorm"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLPixelFormat~1rg16Unorm/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLPixelFormatRG16Unorm"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLPixelFormat~1r32Float/title",
          "value": "MTLPixelFormatR32Float"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLPixelFormat~1r32Float/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLPixelFormatR32Float"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/metal/mtlpixelformat/rgba8unorm_srgb"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/metal/mtlpixelformat/rgba8unorm_srgb"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
