{
  "abstract": [
    {
      "text": "A stencil pixel format used to read the stencil value from a texture with a combined 24-bit depth and 8-bit stencil value.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.metal/documentation/Metal",
        "doc://com.apple.metal/documentation/Metal/MTLPixelFormat"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.metal/documentation/Metal/MTLPixelFormat/x24_stencil8"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@MTLPixelFormat@MTLPixelFormatX24_Stencil8",
    "fragments": [
      {
        "kind": "keyword",
        "text": "case"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "x24_stencil8"
      }
    ],
    "modules": [
      {
        "name": "Metal"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "MTLPixelFormatX24_Stencil8"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.0",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.12",
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Case",
    "symbolKind": "case",
    "title": "MTLPixelFormat.x24_stencil8"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "Mac Catalyst",
            "macOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "case"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "x24_stencil8"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "You can’t directly read the stencil value of a texture with the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.metal/documentation/Metal/MTLPixelFormat/depth24Unorm_stencil8",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " format. To read stencil values from a texture with the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.metal/documentation/Metal/MTLPixelFormat/depth24Unorm_stencil8",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " format, create a texture view of that texture using the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.metal/documentation/Metal/MTLPixelFormat/x24_stencil8",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " format, and sample the texture view instead.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.metal/documentation/Metal": {
      "abstract": [
        {
          "text": "Render advanced 3D graphics and compute data in parallel with graphics processors.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal",
      "kind": "symbol",
      "role": "collection",
      "title": "Metal",
      "type": "topic",
      "url": "/documentation/metal"
    },
    "doc://com.apple.metal/documentation/Metal/MTLPixelFormat": {
      "abstract": [
        {
          "text": "The data formats that describe the organization and characteristics of individual pixels in a texture.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MTLPixelFormat"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLPixelFormat",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTLPixelFormat"
        }
      ],
      "role": "symbol",
      "title": "MTLPixelFormat",
      "type": "topic",
      "url": "/documentation/metal/mtlpixelformat"
    },
    "doc://com.apple.metal/documentation/Metal/MTLPixelFormat/depth16Unorm": {
      "abstract": [
        {
          "text": "A pixel format with a 16-bit normalized unsigned integer component, used for a depth render target.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "depth16Unorm"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLPixelFormat/depth16Unorm",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTLPixelFormatDepth16Unorm"
        }
      ],
      "role": "symbol",
      "title": "MTLPixelFormat.depth16Unorm",
      "type": "topic",
      "url": "/documentation/metal/mtlpixelformat/depth16unorm"
    },
    "doc://com.apple.metal/documentation/Metal/MTLPixelFormat/depth24Unorm_stencil8": {
      "abstract": [
        {
          "text": "A 32-bit combined depth and stencil pixel format with a 24-bit normalized unsigned integer for depth and an 8-bit unsigned integer for stencil.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "depth24Unorm_stencil8"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLPixelFormat/depth24Unorm_stencil8",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTLPixelFormatDepth24Unorm_Stencil8"
        }
      ],
      "role": "symbol",
      "title": "MTLPixelFormat.depth24Unorm_stencil8",
      "type": "topic",
      "url": "/documentation/metal/mtlpixelformat/depth24unorm_stencil8"
    },
    "doc://com.apple.metal/documentation/Metal/MTLPixelFormat/depth32Float": {
      "abstract": [
        {
          "text": "A pixel format with one 32-bit floating-point component, used for a depth render target.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "depth32Float"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLPixelFormat/depth32Float",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTLPixelFormatDepth32Float"
        }
      ],
      "role": "symbol",
      "title": "MTLPixelFormat.depth32Float",
      "type": "topic",
      "url": "/documentation/metal/mtlpixelformat/depth32float"
    },
    "doc://com.apple.metal/documentation/Metal/MTLPixelFormat/depth32Float_stencil8": {
      "abstract": [
        {
          "text": "A 40-bit combined depth and stencil pixel format with a 32-bit floating-point value for depth and an 8-bit unsigned integer for stencil.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "depth32Float_stencil8"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLPixelFormat/depth32Float_stencil8",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTLPixelFormatDepth32Float_Stencil8"
        }
      ],
      "role": "symbol",
      "title": "MTLPixelFormat.depth32Float_stencil8",
      "type": "topic",
      "url": "/documentation/metal/mtlpixelformat/depth32float_stencil8"
    },
    "doc://com.apple.metal/documentation/Metal/MTLPixelFormat/stencil8": {
      "abstract": [
        {
          "text": "A pixel format with an 8-bit unsigned integer component, used for a stencil render target.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "stencil8"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLPixelFormat/stencil8",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTLPixelFormatStencil8"
        }
      ],
      "role": "symbol",
      "title": "MTLPixelFormat.stencil8",
      "type": "topic",
      "url": "/documentation/metal/mtlpixelformat/stencil8"
    },
    "doc://com.apple.metal/documentation/Metal/MTLPixelFormat/x24_stencil8": {
      "abstract": [
        {
          "text": "A stencil pixel format used to read the stencil value from a texture with a combined 24-bit depth and 8-bit stencil value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "x24_stencil8"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLPixelFormat/x24_stencil8",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTLPixelFormatX24_Stencil8"
        }
      ],
      "role": "symbol",
      "title": "MTLPixelFormat.x24_stencil8",
      "type": "topic",
      "url": "/documentation/metal/mtlpixelformat/x24_stencil8"
    },
    "doc://com.apple.metal/documentation/Metal/MTLPixelFormat/x32_stencil8": {
      "abstract": [
        {
          "text": "A stencil pixel format used to read the stencil value from a texture with a combined 32-bit depth and 8-bit stencil value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "x32_stencil8"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLPixelFormat/x32_stencil8",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTLPixelFormatX32_Stencil8"
        }
      ],
      "role": "symbol",
      "title": "MTLPixelFormat.x32_stencil8",
      "type": "topic",
      "url": "/documentation/metal/mtlpixelformat/x32_stencil8"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Depth-and-Stencil-Pixel-Formats",
      "generated": true,
      "identifiers": [
        "doc://com.apple.metal/documentation/Metal/MTLPixelFormat/depth16Unorm",
        "doc://com.apple.metal/documentation/Metal/MTLPixelFormat/depth32Float",
        "doc://com.apple.metal/documentation/Metal/MTLPixelFormat/stencil8",
        "doc://com.apple.metal/documentation/Metal/MTLPixelFormat/depth24Unorm_stencil8",
        "doc://com.apple.metal/documentation/Metal/MTLPixelFormat/depth32Float_stencil8",
        "doc://com.apple.metal/documentation/Metal/MTLPixelFormat/x32_stencil8"
      ],
      "title": "Depth and Stencil Pixel Formats"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.1",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.12",
              "name": "macOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration Case"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "MTLPixelFormatX24_Stencil8"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "case"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLPixelFormatX24_Stencil8"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.metal/documentation/Metal",
                "doc://com.apple.metal/documentation/Metal/MTLPixelFormat"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Depth-and-Stencil-Pixel-Formats",
              "generated": true,
              "identifiers": [
                "doc://com.apple.metal/documentation/Metal/MTLPixelFormat/depth16Unorm",
                "doc://com.apple.metal/documentation/Metal/MTLPixelFormat/depth32Float",
                "doc://com.apple.metal/documentation/Metal/MTLPixelFormat/stencil8",
                "doc://com.apple.metal/documentation/Metal/MTLPixelFormat/depth24Unorm_stencil8",
                "doc://com.apple.metal/documentation/Metal/MTLPixelFormat/depth32Float_stencil8",
                "doc://com.apple.metal/documentation/Metal/MTLPixelFormat/x32_stencil8"
              ],
              "title": "Depth and Stencil Pixel Formats"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS"
                ],
                "tokens": [
                  {
                    "kind": "identifier",
                    "text": "MTLPixelFormatX24_Stencil8"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLPixelFormat~1depth24Unorm_stencil8/title",
          "value": "MTLPixelFormatDepth24Unorm_Stencil8"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLPixelFormat~1depth24Unorm_stencil8/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLPixelFormatDepth24Unorm_Stencil8"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLPixelFormat~1x24_stencil8/title",
          "value": "MTLPixelFormatX24_Stencil8"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLPixelFormat~1x24_stencil8/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLPixelFormatX24_Stencil8"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLPixelFormat/title",
          "value": "MTLPixelFormat"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLPixelFormat/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLPixelFormat"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLPixelFormat/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLPixelFormat"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLPixelFormat~1depth32Float_stencil8/title",
          "value": "MTLPixelFormatDepth32Float_Stencil8"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLPixelFormat~1depth32Float_stencil8/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLPixelFormatDepth32Float_Stencil8"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLPixelFormat~1x32_stencil8/title",
          "value": "MTLPixelFormatX32_Stencil8"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLPixelFormat~1x32_stencil8/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLPixelFormatX32_Stencil8"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLPixelFormat~1stencil8/title",
          "value": "MTLPixelFormatStencil8"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLPixelFormat~1stencil8/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLPixelFormatStencil8"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLPixelFormat~1depth32Float/title",
          "value": "MTLPixelFormatDepth32Float"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLPixelFormat~1depth32Float/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLPixelFormatDepth32Float"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLPixelFormat~1depth16Unorm/title",
          "value": "MTLPixelFormatDepth16Unorm"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLPixelFormat~1depth16Unorm/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLPixelFormatDepth16Unorm"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/metal/mtlpixelformat/x24_stencil8"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/metal/mtlpixelformat/x24_stencil8"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
