{
  "abstract": [
    {
      "text": "A media player error.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.watchkit/documentation/WatchKit",
        "doc://com.apple.watchkit/documentation/WatchKit/WatchKitError",
        "doc://com.apple.watchkit/documentation/WatchKit/WatchKitError/Code"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.watchkit/documentation/WatchKit/WatchKitError/Code/mediaPlayerFailed"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@WatchKitErrorCode@WatchKitMediaPlayerError",
    "fragments": [
      {
        "kind": "keyword",
        "text": "case"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "mediaPlayerFailed"
      }
    ],
    "modules": [
      {
        "name": "WatchKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "WatchKitMediaPlayerError"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Case",
    "symbolKind": "case",
    "title": "WatchKitError.Code.mediaPlayerFailed"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "case"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "mediaPlayerFailed"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "WatchKit reports this error when it’s unable to play a media file.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.watchkit/documentation/WatchKit": {
      "abstract": [
        {
          "text": "Build watchOS apps that use features the app delegate monitors or controls, such as background tasks and extended runtime sessions.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.watchkit/documentation/WatchKit",
      "kind": "symbol",
      "role": "collection",
      "title": "WatchKit",
      "type": "topic",
      "url": "/documentation/watchkit"
    },
    "doc://com.apple.watchkit/documentation/WatchKit/WatchKitError": {
      "abstract": [
        {
          "text": "An error reported by WatchKit.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "WatchKitError"
        }
      ],
      "identifier": "doc://com.apple.watchkit/documentation/WatchKit/WatchKitError",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "WatchKitError"
        }
      ],
      "role": "symbol",
      "title": "WatchKitError",
      "type": "topic",
      "url": "/documentation/watchkit/watchkiterror"
    },
    "doc://com.apple.watchkit/documentation/WatchKit/WatchKitError/Code": {
      "abstract": [
        {
          "text": "Error codes reported by WatchKit.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.watchkit/documentation/WatchKit/WatchKitError/Code",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "Code"
        }
      ],
      "role": "symbol",
      "title": "WatchKitError.Code",
      "type": "topic",
      "url": "/documentation/watchkit/watchkiterror/code"
    },
    "doc://com.apple.watchkit/documentation/WatchKit/WatchKitError/Code/applicationDelegateWatchKitRequestReplyNotCalled": {
      "abstract": [
        {
          "text": "An unresponsive delegate error.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "applicationDelegateWatchKitRequestReplyNotCalled"
        }
      ],
      "identifier": "doc://com.apple.watchkit/documentation/WatchKit/WatchKitError/Code/applicationDelegateWatchKitRequestReplyNotCalled",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "WatchKitApplicationDelegateWatchKitRequestReplyNotCalledError"
        }
      ],
      "role": "symbol",
      "title": "WatchKitError.Code.applicationDelegateWatchKitRequestReplyNotCalled",
      "type": "topic",
      "url": "/documentation/watchkit/watchkiterror/code/applicationdelegatewatchkitrequestreplynotcalled"
    },
    "doc://com.apple.watchkit/documentation/WatchKit/WatchKitError/Code/downloadFailed": {
      "abstract": [
        {
          "text": "A download error.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "downloadFailed"
        }
      ],
      "identifier": "doc://com.apple.watchkit/documentation/WatchKit/WatchKitError/Code/downloadFailed",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "WatchKitDownloadError"
        }
      ],
      "role": "symbol",
      "title": "WatchKitError.Code.downloadFailed",
      "type": "topic",
      "url": "/documentation/watchkit/watchkiterror/code/downloadfailed"
    },
    "doc://com.apple.watchkit/documentation/WatchKit/WatchKitError/Code/invalidArgument": {
      "abstract": [
        {
          "text": "An invalid argument error.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "invalidArgument"
        }
      ],
      "identifier": "doc://com.apple.watchkit/documentation/WatchKit/WatchKitError/Code/invalidArgument",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "WatchKitInvalidArgumentError"
        }
      ],
      "role": "symbol",
      "title": "WatchKitError.Code.invalidArgument",
      "type": "topic",
      "url": "/documentation/watchkit/watchkiterror/code/invalidargument"
    },
    "doc://com.apple.watchkit/documentation/WatchKit/WatchKitError/Code/mediaPlayerFailed": {
      "abstract": [
        {
          "text": "A media player error.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "mediaPlayerFailed"
        }
      ],
      "identifier": "doc://com.apple.watchkit/documentation/WatchKit/WatchKitError/Code/mediaPlayerFailed",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "WatchKitMediaPlayerError"
        }
      ],
      "role": "symbol",
      "title": "WatchKitError.Code.mediaPlayerFailed",
      "type": "topic",
      "url": "/documentation/watchkit/watchkiterror/code/mediaplayerfailed"
    },
    "doc://com.apple.watchkit/documentation/WatchKit/WatchKitError/Code/recordingFailed": {
      "abstract": [
        {
          "text": "An audio recording error.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "recordingFailed"
        }
      ],
      "identifier": "doc://com.apple.watchkit/documentation/WatchKit/WatchKitError/Code/recordingFailed",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "WatchKitRecordingFailedError"
        }
      ],
      "role": "symbol",
      "title": "WatchKitError.Code.recordingFailed",
      "type": "topic",
      "url": "/documentation/watchkit/watchkiterror/code/recordingfailed"
    },
    "doc://com.apple.watchkit/documentation/WatchKit/WatchKitError/Code/unknown": {
      "abstract": [
        {
          "text": "An unknown error.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "unknown"
        }
      ],
      "identifier": "doc://com.apple.watchkit/documentation/WatchKit/WatchKitError/Code/unknown",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "WatchKitUnknownError"
        }
      ],
      "role": "symbol",
      "title": "WatchKitError.Code.unknown",
      "type": "topic",
      "url": "/documentation/watchkit/watchkiterror/code/unknown"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Error-Codes",
      "generated": true,
      "identifiers": [
        "doc://com.apple.watchkit/documentation/WatchKit/WatchKitError/Code/downloadFailed",
        "doc://com.apple.watchkit/documentation/WatchKit/WatchKitError/Code/invalidArgument",
        "doc://com.apple.watchkit/documentation/WatchKit/WatchKitError/Code/recordingFailed",
        "doc://com.apple.watchkit/documentation/WatchKit/WatchKitError/Code/unknown",
        "doc://com.apple.watchkit/documentation/WatchKit/WatchKitError/Code/applicationDelegateWatchKitRequestReplyNotCalled",
        "doc://com.apple.watchkit/documentation/WatchKit/WatchKitError/Code/downloadFailed",
        "doc://com.apple.watchkit/documentation/WatchKit/WatchKitError/Code/invalidArgument",
        "doc://com.apple.watchkit/documentation/WatchKit/WatchKitError/Code/recordingFailed",
        "doc://com.apple.watchkit/documentation/WatchKit/WatchKitError/Code/unknown",
        "doc://com.apple.watchkit/documentation/WatchKit/WatchKitError/Code/applicationDelegateWatchKitRequestReplyNotCalled"
      ],
      "title": "Error Codes"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration Case"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "WatchKitMediaPlayerError"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "case"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "WatchKitMediaPlayerError"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.watchkit/documentation/WatchKit",
                "doc://com.apple.watchkit/documentation/WatchKit/WatchKitError/Code"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Error-Codes",
              "generated": true,
              "identifiers": [
                "doc://com.apple.watchkit/documentation/WatchKit/WatchKitError/Code/downloadFailed",
                "doc://com.apple.watchkit/documentation/WatchKit/WatchKitError/Code/invalidArgument",
                "doc://com.apple.watchkit/documentation/WatchKit/WatchKitError/Code/recordingFailed",
                "doc://com.apple.watchkit/documentation/WatchKit/WatchKitError/Code/unknown",
                "doc://com.apple.watchkit/documentation/WatchKit/WatchKitError/Code/applicationDelegateWatchKitRequestReplyNotCalled",
                "doc://com.apple.watchkit/documentation/WatchKit/WatchKitError/Code/downloadFailed",
                "doc://com.apple.watchkit/documentation/WatchKit/WatchKitError/Code/invalidArgument",
                "doc://com.apple.watchkit/documentation/WatchKit/WatchKitError/Code/recordingFailed",
                "doc://com.apple.watchkit/documentation/WatchKit/WatchKitError/Code/unknown",
                "doc://com.apple.watchkit/documentation/WatchKit/WatchKitError/Code/applicationDelegateWatchKitRequestReplyNotCalled"
              ],
              "title": "Error Codes"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "identifier",
                    "text": "WatchKitMediaPlayerError"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.watchkit~1documentation~1WatchKit~1WatchKitError~1Code/title",
          "value": "WatchKitErrorCode"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.watchkit~1documentation~1WatchKit~1WatchKitError~1Code/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "WatchKitErrorCode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.watchkit~1documentation~1WatchKit~1WatchKitError~1Code/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "WatchKitErrorCode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.watchkit~1documentation~1WatchKit~1WatchKitError~1Code~1applicationDelegateWatchKitRequestReplyNotCalled/title",
          "value": "WatchKitApplicationDelegateWatchKitRequestReplyNotCalledError"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.watchkit~1documentation~1WatchKit~1WatchKitError~1Code~1applicationDelegateWatchKitRequestReplyNotCalled/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "WatchKitApplicationDelegateWatchKitRequestReplyNotCalledError"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.watchkit~1documentation~1WatchKit~1WatchKitError~1Code~1downloadFailed/title",
          "value": "WatchKitDownloadError"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.watchkit~1documentation~1WatchKit~1WatchKitError~1Code~1downloadFailed/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "WatchKitDownloadError"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.watchkit~1documentation~1WatchKit~1WatchKitError~1Code~1recordingFailed/title",
          "value": "WatchKitRecordingFailedError"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.watchkit~1documentation~1WatchKit~1WatchKitError~1Code~1recordingFailed/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "WatchKitRecordingFailedError"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.watchkit~1documentation~1WatchKit~1WatchKitError~1Code~1unknown/title",
          "value": "WatchKitUnknownError"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.watchkit~1documentation~1WatchKit~1WatchKitError~1Code~1unknown/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "WatchKitUnknownError"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.watchkit~1documentation~1WatchKit~1WatchKitError~1Code~1invalidArgument/title",
          "value": "WatchKitInvalidArgumentError"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.watchkit~1documentation~1WatchKit~1WatchKitError~1Code~1invalidArgument/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "WatchKitInvalidArgumentError"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.watchkit~1documentation~1WatchKit~1WatchKitError~1Code~1mediaPlayerFailed/title",
          "value": "WatchKitMediaPlayerError"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.watchkit~1documentation~1WatchKit~1WatchKitError~1Code~1mediaPlayerFailed/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "WatchKitMediaPlayerError"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/watchkit/watchkiterror/code/mediaplayerfailed"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/watchkit/watchkiterror/code/mediaplayerfailed"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
