{
  "abstract": [
    {
      "text": "Returns a new reference object that combines spatial information from both this reference object and another.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.arkit/documentation/ARKit",
        "doc://com.apple.arkit/documentation/ARKit/ARReferenceObject"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.arkit/documentation/ARKit/ARReferenceObject/merging(_:)"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(cs)ARReferenceObject(im)referenceObjectByMergingObject:error:",
    "fragments": [
      {
        "kind": "keyword",
        "text": "func"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "merging"
      },
      {
        "kind": "text",
        "text": "("
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:objc(cs)ARReferenceObject",
        "text": "ARReferenceObject"
      },
      {
        "kind": "text",
        "text": ") "
      },
      {
        "kind": "keyword",
        "text": "throws"
      },
      {
        "kind": "text",
        "text": " -> "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:objc(cs)ARReferenceObject",
        "text": "ARReferenceObject"
      }
    ],
    "modules": [
      {
        "name": "ARKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "referenceObjectByMergingObject:error:"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "12.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "12.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.1",
        "name": "Mac Catalyst",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Instance Method",
    "symbolKind": "method",
    "title": "merging(_:)"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "func"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "merging"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "kind": "externalParam",
              "text": "_"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "object"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.arkit/documentation/ARKit/ARReferenceObject",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)ARReferenceObject",
              "text": "ARReferenceObject"
            },
            {
              "kind": "text",
              "text": ") "
            },
            {
              "kind": "keyword",
              "text": "throws"
            },
            {
              "kind": "text",
              "text": " -> "
            },
            {
              "identifier": "doc://com.apple.arkit/documentation/ARKit/ARReferenceObject",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)ARReferenceObject",
              "text": "ARReferenceObject"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "kind": "parameters",
      "parameters": [
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "The other reference object with which to combine this reference object.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "object"
        }
      ]
    },
    {
      "content": [
        {
          "anchor": "return-value",
          "level": 2,
          "text": "Return Value",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "A new ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.arkit/documentation/ARKit/ARReferenceObject",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " that includes the spatial information from both objects. From Swift, this method throws an ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.arkit/documentation/ARKit/ARError",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " if the two objects cannot be merged. From Objective-C, it returns ",
              "type": "text"
            },
            {
              "code": "nil",
              "type": "codeVoice"
            },
            {
              "text": " and populates the ",
              "type": "text"
            },
            {
              "code": "error",
              "type": "codeVoice"
            },
            {
              "text": " parameter with a description of the failure.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    },
    {
      "content": [
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "The accuracy of 3D object detection depends on similarity of lighting and environmental conditions between when you scan a real object (producing an ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.arkit/documentation/ARKit/ARReferenceObject",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ") and when a user of your app attempts to detect that object. If, for example, you scan an object in a bright environment, then a user attempts to detect it in a dark environment, ARKit may fail to recognize that the real object matches the reference object, or may not detect the object quickly.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "To make a reference object that is more robust in a wide variety of detection conditions, scan the same real-world object multiple times: For each scan, vary the lighting conditions or the background environment to capture the variety of situations in which your app might attempt to detect the same real object. Then, use this method to combine those scan results into a single ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.arkit/documentation/ARKit/ARReferenceObject",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " incorporating recognition information for all the conditions you scanned in.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.arkit/documentation/ARKit": {
      "abstract": [
        {
          "text": "Integrate hardware sensing features to produce augmented reality apps and games.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.arkit/documentation/ARKit",
      "kind": "symbol",
      "role": "collection",
      "title": "ARKit",
      "type": "topic",
      "url": "/documentation/arkit"
    },
    "doc://com.apple.arkit/documentation/ARKit/ARError": {
      "abstract": [
        {
          "text": "An error reported by ARKit.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ARError"
        }
      ],
      "identifier": "doc://com.apple.arkit/documentation/ARKit/ARError",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ARError"
        }
      ],
      "role": "symbol",
      "title": "ARError",
      "type": "topic",
      "url": "/documentation/arkit/arerror"
    },
    "doc://com.apple.arkit/documentation/ARKit/ARReferenceObject": {
      "abstract": [
        {
          "text": "The description of a 3D object that you want ARKit to detect in the physical environment.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ARReferenceObject"
        }
      ],
      "identifier": "doc://com.apple.arkit/documentation/ARKit/ARReferenceObject",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ARReferenceObject"
        }
      ],
      "role": "symbol",
      "title": "ARReferenceObject",
      "type": "topic",
      "url": "/documentation/arkit/arreferenceobject"
    },
    "doc://com.apple.arkit/documentation/ARKit/ARReferenceObject/applyingTransform(_:)": {
      "abstract": [
        {
          "text": "Returns a new reference object created by applying the specified transform to this reference object’s geometric data.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "applyingTransform"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@SA@simd_float4x4",
          "text": "simd_float4x4"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)ARReferenceObject",
          "text": "ARReferenceObject"
        }
      ],
      "identifier": "doc://com.apple.arkit/documentation/ARKit/ARReferenceObject/applyingTransform(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "referenceObjectByApplyingTransform:"
        }
      ],
      "role": "symbol",
      "title": "applyingTransform(_:)",
      "type": "topic",
      "url": "/documentation/arkit/arreferenceobject/applyingtransform(_:)"
    },
    "doc://com.apple.arkit/documentation/ARKit/ARReferenceObject/merging(_:)": {
      "abstract": [
        {
          "text": "Returns a new reference object that combines spatial information from both this reference object and another.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "merging"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)ARReferenceObject",
          "text": "ARReferenceObject"
        },
        {
          "kind": "text",
          "text": ") "
        },
        {
          "kind": "keyword",
          "text": "throws"
        },
        {
          "kind": "text",
          "text": " -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)ARReferenceObject",
          "text": "ARReferenceObject"
        }
      ],
      "identifier": "doc://com.apple.arkit/documentation/ARKit/ARReferenceObject/merging(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "referenceObjectByMergingObject:error:"
        }
      ],
      "role": "symbol",
      "title": "merging(_:)",
      "type": "topic",
      "url": "/documentation/arkit/arreferenceobject/merging(_:)"
    },
    "doc://com.apple.documentation/documentation/foundation/nserror": {
      "abstract": [
        {
          "text": "Information about an error condition including a domain, a domain-specific error code, and application-specific information.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "class "
        },
        {
          "kind": "identifier",
          "text": "NSError"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/foundation/nserror",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSError",
      "type": "topic",
      "url": "/documentation/foundation/nserror"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Creating-Derivative-Reference-Objects",
      "generated": true,
      "identifiers": [
        "doc://com.apple.arkit/documentation/ARKit/ARReferenceObject/applyingTransform(_:)"
      ],
      "title": "Creating Derivative Reference Objects"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "12.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "12.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.1",
              "name": "Mac Catalyst",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Instance Method"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "referenceObjectByMergingObject:error:"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "method"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "referenceObjectByMergingObject:error:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.arkit/documentation/ARKit",
                "doc://com.apple.arkit/documentation/ARKit/ARReferenceObject"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Creating-Derivative-Reference-Objects",
              "generated": true,
              "identifiers": [
                "doc://com.apple.arkit/documentation/ARKit/ARReferenceObject/applyingTransform(_:)"
              ],
              "title": "Creating Derivative Reference Objects"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst"
                ],
                "tokens": [
                  {
                    "kind": "text",
                    "text": "- ("
                  },
                  {
                    "identifier": "doc://com.apple.arkit/documentation/ARKit/ARReferenceObject",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(cs)ARReferenceObject",
                    "text": "ARReferenceObject"
                  },
                  {
                    "kind": "text",
                    "text": " *) "
                  },
                  {
                    "kind": "identifier",
                    "text": "referenceObjectByMergingObject:"
                  },
                  {
                    "kind": "text",
                    "text": "("
                  },
                  {
                    "identifier": "doc://com.apple.arkit/documentation/ARKit/ARReferenceObject",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(cs)ARReferenceObject",
                    "text": "ARReferenceObject"
                  },
                  {
                    "kind": "text",
                    "text": " *) "
                  },
                  {
                    "kind": "internalParam",
                    "text": "object"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "error:"
                  },
                  {
                    "kind": "text",
                    "text": "("
                  },
                  {
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(cs)NSError",
                    "text": "NSError"
                  },
                  {
                    "kind": "text",
                    "text": " * *) "
                  },
                  {
                    "kind": "internalParam",
                    "text": "error"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/1",
          "value": {
            "kind": "parameters",
            "parameters": [
              {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "The other reference object with which to combine this reference object.",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ],
                "name": "object"
              },
              {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "A pointer to an ",
                        "type": "text"
                      },
                      {
                        "identifier": "doc://com.apple.documentation/documentation/foundation/nserror",
                        "isActive": true,
                        "type": "reference"
                      },
                      {
                        "text": ". On completion, if the method returns ",
                        "type": "text"
                      },
                      {
                        "code": "nil",
                        "type": "codeVoice"
                      },
                      {
                        "text": ", this pointer references an object describing the failure.",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ],
                "name": "error"
              }
            ]
          }
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/2",
          "value": {
            "content": [
              {
                "anchor": "return-value",
                "level": 2,
                "text": "Return Value",
                "type": "heading"
              },
              {
                "inlineContent": [
                  {
                    "text": "A new ",
                    "type": "text"
                  },
                  {
                    "identifier": "doc://com.apple.arkit/documentation/ARKit/ARReferenceObject",
                    "isActive": true,
                    "type": "reference"
                  },
                  {
                    "text": " that includes the spatial information from both objects. From Swift, this method throws an ",
                    "type": "text"
                  },
                  {
                    "identifier": "doc://com.apple.arkit/documentation/ARKit/ARError",
                    "isActive": true,
                    "type": "reference"
                  },
                  {
                    "text": " if the two objects cannot be merged. From Objective-C, it returns ",
                    "type": "text"
                  },
                  {
                    "code": "nil",
                    "type": "codeVoice"
                  },
                  {
                    "text": " and populates the ",
                    "type": "text"
                  },
                  {
                    "code": "error",
                    "type": "codeVoice"
                  },
                  {
                    "text": " parameter with a description of the failure.",
                    "type": "text"
                  }
                ],
                "type": "paragraph"
              }
            ],
            "kind": "content"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.arkit~1documentation~1ARKit~1ARReferenceObject~1merging(_:)/title",
          "value": "referenceObjectByMergingObject:error:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.arkit~1documentation~1ARKit~1ARReferenceObject~1merging(_:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "referenceObjectByMergingObject:error:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.arkit~1documentation~1ARKit~1ARReferenceObject/title",
          "value": "ARReferenceObject"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.arkit~1documentation~1ARKit~1ARReferenceObject/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ARReferenceObject"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.arkit~1documentation~1ARKit~1ARReferenceObject/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "ARReferenceObject"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.arkit~1documentation~1ARKit~1ARReferenceObject~1applyingTransform(_:)/title",
          "value": "referenceObjectByApplyingTransform:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.arkit~1documentation~1ARKit~1ARReferenceObject~1applyingTransform(_:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "referenceObjectByApplyingTransform:"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/arkit/arreferenceobject/merging(_:)"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/arkit/arreferenceobject/merging(_:)"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
