{
  "abstract": [
    {
      "text": "Returns a filter that gets all assets in the assets group.",
      "type": "text"
    }
  ],
  "deprecationSummary": [
    {
      "inlineContent": [
        {
          "text": "Use fetchAssetsInAssetCollection:options: on PHAsset and set a mediaType predicate on the PHFetchOptions from the Photos framework instead",
          "type": "text"
        }
      ],
      "type": "paragraph"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.assetslibrary/documentation/AssetsLibrary",
        "doc://com.apple.assetslibrary/documentation/AssetsLibrary/ALAssetsFilter"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.assetslibrary/documentation/AssetsLibrary/ALAssetsFilter/allAssets()"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(cs)ALAssetsFilter(cm)allAssets",
    "fragments": [
      {
        "kind": "keyword",
        "text": "class"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "keyword",
        "text": "func"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "allAssets"
      },
      {
        "kind": "text",
        "text": "() -> "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:objc(cs)ALAssetsFilter",
        "text": "ALAssetsFilter"
      },
      {
        "kind": "text",
        "text": "!"
      }
    ],
    "modules": [
      {
        "name": "Assets Library"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "allAssets"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "9.0",
        "introducedAt": "4.0",
        "message": "Use fetchAssetsInAssetCollection:options: on PHAsset and set a mediaType predicate on the PHFetchOptions from the Photos framework instead",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "9.0",
        "introducedAt": "4.0",
        "message": "Use fetchAssetsInAssetCollection:options: on PHAsset and set a mediaType predicate on the PHFetchOptions from the Photos framework instead",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "13.1",
        "introducedAt": "13.1",
        "message": "Use fetchAssetsInAssetCollection:options: on PHAsset and set a mediaType predicate on the PHFetchOptions from the Photos framework instead",
        "name": "Mac Catalyst",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Type Method",
    "symbolKind": "method",
    "title": "allAssets()"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "class"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "keyword",
              "text": "func"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "allAssets"
            },
            {
              "kind": "text",
              "text": "() -> "
            },
            {
              "identifier": "doc://com.apple.assetslibrary/documentation/AssetsLibrary/ALAssetsFilter",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)ALAssetsFilter",
              "text": "ALAssetsFilter"
            },
            {
              "kind": "text",
              "text": "!"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "return-value",
          "level": 2,
          "text": "Return Value",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "A filter that gets all assets in the assets group.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.assetslibrary/documentation/AssetsLibrary": {
      "abstract": [
        {
          "text": "Access the assets in a user’s media library.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.assetslibrary/documentation/AssetsLibrary",
      "kind": "symbol",
      "role": "collection",
      "title": "Assets Library",
      "type": "topic",
      "url": "/documentation/assetslibrary"
    },
    "doc://com.apple.assetslibrary/documentation/AssetsLibrary/ALAssetsFilter": {
      "abstract": [
        {
          "code": "ALAssetsFilter",
          "type": "codeVoice"
        },
        {
          "text": " encapsulates filtering criteria to be used when retrieving assets from a group.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ALAssetsFilter"
        }
      ],
      "identifier": "doc://com.apple.assetslibrary/documentation/AssetsLibrary/ALAssetsFilter",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ALAssetsFilter"
        }
      ],
      "role": "symbol",
      "title": "ALAssetsFilter",
      "type": "topic",
      "url": "/documentation/assetslibrary/alassetsfilter"
    },
    "doc://com.apple.assetslibrary/documentation/AssetsLibrary/ALAssetsFilter/allAssets()": {
      "abstract": [
        {
          "text": "Returns a filter that gets all assets in the assets group.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "allAssets"
        },
        {
          "kind": "text",
          "text": "() -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)ALAssetsFilter",
          "text": "ALAssetsFilter"
        },
        {
          "kind": "text",
          "text": "!"
        }
      ],
      "identifier": "doc://com.apple.assetslibrary/documentation/AssetsLibrary/ALAssetsFilter/allAssets()",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "allAssets"
        }
      ],
      "role": "symbol",
      "title": "allAssets()",
      "type": "topic",
      "url": "/documentation/assetslibrary/alassetsfilter/allassets()"
    },
    "doc://com.apple.assetslibrary/documentation/AssetsLibrary/ALAssetsFilter/allPhotos()": {
      "abstract": [
        {
          "text": "Returns a filter that gets all photos in the assets group.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "allPhotos"
        },
        {
          "kind": "text",
          "text": "() -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)ALAssetsFilter",
          "text": "ALAssetsFilter"
        },
        {
          "kind": "text",
          "text": "!"
        }
      ],
      "identifier": "doc://com.apple.assetslibrary/documentation/AssetsLibrary/ALAssetsFilter/allPhotos()",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "allPhotos"
        }
      ],
      "role": "symbol",
      "title": "allPhotos()",
      "type": "topic",
      "url": "/documentation/assetslibrary/alassetsfilter/allphotos()"
    },
    "doc://com.apple.assetslibrary/documentation/AssetsLibrary/ALAssetsFilter/allVideos()": {
      "abstract": [
        {
          "text": "Returns a filter that gets all videos in the assets group.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "allVideos"
        },
        {
          "kind": "text",
          "text": "() -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)ALAssetsFilter",
          "text": "ALAssetsFilter"
        },
        {
          "kind": "text",
          "text": "!"
        }
      ],
      "identifier": "doc://com.apple.assetslibrary/documentation/AssetsLibrary/ALAssetsFilter/allVideos()",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "allVideos"
        }
      ],
      "role": "symbol",
      "title": "allVideos()",
      "type": "topic",
      "url": "/documentation/assetslibrary/alassetsfilter/allvideos()"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Creating-Filters",
      "generated": true,
      "identifiers": [
        "doc://com.apple.assetslibrary/documentation/AssetsLibrary/ALAssetsFilter/allPhotos()",
        "doc://com.apple.assetslibrary/documentation/AssetsLibrary/ALAssetsFilter/allVideos()"
      ],
      "title": "Creating Filters"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "deprecatedAt": "9.0",
              "introducedAt": "4.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "deprecatedAt": "9.0",
              "introducedAt": "4.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "deprecatedAt": "13.1",
              "introducedAt": "13.1",
              "name": "Mac Catalyst",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Type Method"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "allAssets"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "method"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "text",
              "text": "+ "
            },
            {
              "kind": "identifier",
              "text": "allAssets"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.assetslibrary/documentation/AssetsLibrary",
                "doc://com.apple.assetslibrary/documentation/AssetsLibrary/ALAssetsFilter"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Creating-Filters",
              "generated": true,
              "identifiers": [
                "doc://com.apple.assetslibrary/documentation/AssetsLibrary/ALAssetsFilter/allPhotos()",
                "doc://com.apple.assetslibrary/documentation/AssetsLibrary/ALAssetsFilter/allVideos()"
              ],
              "title": "Creating Filters"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst"
                ],
                "tokens": [
                  {
                    "kind": "text",
                    "text": "+ ("
                  },
                  {
                    "identifier": "doc://com.apple.assetslibrary/documentation/AssetsLibrary/ALAssetsFilter",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(cs)ALAssetsFilter",
                    "text": "ALAssetsFilter"
                  },
                  {
                    "kind": "text",
                    "text": " *) "
                  },
                  {
                    "kind": "identifier",
                    "text": "allAssets"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/1",
          "value": {
            "content": [
              {
                "anchor": "return-value",
                "level": 2,
                "text": "Return Value",
                "type": "heading"
              },
              {
                "inlineContent": [
                  {
                    "text": "A filter that gets all assets in the assets group.",
                    "type": "text"
                  }
                ],
                "type": "paragraph"
              }
            ],
            "kind": "content"
          }
        },
        {
          "op": "replace",
          "path": "/deprecationSummary",
          "value": [
            {
              "inlineContent": [
                {
                  "text": "Use fetchAssetsInAssetCollection:options: on PHAsset and set a mediaType predicate on the PHFetchOptions from the Photos framework instead",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.assetslibrary~1documentation~1AssetsLibrary~1ALAssetsFilter~1allAssets()/title",
          "value": "allAssets"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.assetslibrary~1documentation~1AssetsLibrary~1ALAssetsFilter~1allAssets()/fragments",
          "value": [
            {
              "kind": "text",
              "text": "+ "
            },
            {
              "kind": "identifier",
              "text": "allAssets"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.assetslibrary~1documentation~1AssetsLibrary~1ALAssetsFilter~1allPhotos()/title",
          "value": "allPhotos"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.assetslibrary~1documentation~1AssetsLibrary~1ALAssetsFilter~1allPhotos()/fragments",
          "value": [
            {
              "kind": "text",
              "text": "+ "
            },
            {
              "kind": "identifier",
              "text": "allPhotos"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.assetslibrary~1documentation~1AssetsLibrary~1ALAssetsFilter~1allVideos()/title",
          "value": "allVideos"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.assetslibrary~1documentation~1AssetsLibrary~1ALAssetsFilter~1allVideos()/fragments",
          "value": [
            {
              "kind": "text",
              "text": "+ "
            },
            {
              "kind": "identifier",
              "text": "allVideos"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.assetslibrary~1documentation~1AssetsLibrary~1ALAssetsFilter/title",
          "value": "ALAssetsFilter"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.assetslibrary~1documentation~1AssetsLibrary~1ALAssetsFilter/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ALAssetsFilter"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.assetslibrary~1documentation~1AssetsLibrary~1ALAssetsFilter/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "ALAssetsFilter"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/assetslibrary/alassetsfilter/allassets()"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/assetslibrary/alassetsfilter/allassets()"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
