{
  "diffAvailability": {
    "major": {
      "change": "modified",
      "platform": "Xcode",
      "versions": [
        "16.0",
        "16.3 beta 2"
      ]
    },
    "minor": {
      "change": "modified",
      "platform": "Xcode",
      "versions": [
        "16.2",
        "16.3 beta 2"
      ]
    }
  },
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.backgroundassets/documentation/BackgroundAssets"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.backgroundassets/documentation/BackgroundAssets/BADownloaderExtensionConfiguration"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "s:16BackgroundAssets34BADownloaderExtensionConfigurationP",
    "fragments": [
      {
        "kind": "keyword",
        "text": "protocol"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "BADownloaderExtensionConfiguration"
      }
    ],
    "modules": [
      {
        "name": "Background Assets"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "BADownloaderExtensionConfiguration"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "16.1",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "16.1",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "16.1",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.0",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": true,
        "deprecated": false,
        "introducedAt": "18.4",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": true,
        "deprecated": false,
        "introducedAt": "2.4",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Protocol",
    "symbolKind": "protocol",
    "title": "BADownloaderExtensionConfiguration"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "attribute",
              "text": "@"
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:ScM",
              "kind": "attribute",
              "preciseIdentifier": "s:ScM",
              "text": "MainActor"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "attribute",
              "text": "@preconcurrency"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "keyword",
              "text": "protocol"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "BADownloaderExtensionConfiguration"
            },
            {
              "kind": "text",
              "text": " : "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:19ExtensionFoundation03AppA13ConfigurationP",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:19ExtensionFoundation03AppA13ConfigurationP",
              "text": "AppExtensionConfiguration"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.backgroundassets/documentation/BackgroundAssets": {
      "abstract": [
        {
          "text": "Schedule background downloads of large assets after app installation, when the app updates, and periodically while the app remains on-device.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.backgroundassets/documentation/BackgroundAssets",
      "kind": "symbol",
      "role": "collection",
      "title": "Background Assets",
      "type": "topic",
      "url": "/documentation/backgroundassets"
    },
    "doc://com.apple.backgroundassets/documentation/BackgroundAssets/BADownloadManager": {
      "abstract": [
        {
          "text": "An object that manages the queue of scheduled asset downloads.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BADownloadManager"
        }
      ],
      "identifier": "doc://com.apple.backgroundassets/documentation/BackgroundAssets/BADownloadManager",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "BADownloadManager"
        }
      ],
      "role": "symbol",
      "title": "BADownloadManager",
      "type": "topic",
      "url": "/documentation/backgroundassets/badownloadmanager"
    },
    "doc://com.apple.backgroundassets/documentation/BackgroundAssets/BADownloaderExtension-qwaw": {
      "abstract": [
        {
          "text": "An interface for reacting to app life-cycle events and processing concluded asset downloads while your app isn’t running.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BADownloaderExtension"
        }
      ],
      "identifier": "doc://com.apple.backgroundassets/documentation/BackgroundAssets/BADownloaderExtension-qwaw",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "BADownloaderExtension"
        }
      ],
      "role": "symbol",
      "title": "BADownloaderExtension",
      "type": "topic",
      "url": "/documentation/backgroundassets/badownloaderextension-qwaw"
    },
    "doc://com.apple.backgroundassets/documentation/BackgroundAssets/BADownloaderExtensionConfiguration": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BADownloaderExtensionConfiguration"
        }
      ],
      "identifier": "doc://com.apple.backgroundassets/documentation/BackgroundAssets/BADownloaderExtensionConfiguration",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "BADownloaderExtensionConfiguration"
        }
      ],
      "role": "symbol",
      "title": "BADownloaderExtensionConfiguration",
      "type": "topic",
      "url": "/documentation/backgroundassets/badownloaderextensionconfiguration"
    },
    "doc://com.apple.backgroundassets/documentation/BackgroundAssets/downloading-essential-assets-in-the-background": {
      "abstract": [
        {
          "text": "Fetch the assets your app requires before its first launch using an app extension and the Background Assets framework.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.backgroundassets/documentation/BackgroundAssets/downloading-essential-assets-in-the-background",
      "kind": "article",
      "role": "sampleCode",
      "title": "Downloading essential assets in the background",
      "type": "topic",
      "url": "/documentation/backgroundassets/downloading-essential-assets-in-the-background"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.externally.resolved.symbol/s:19ExtensionFoundation03AppA13ConfigurationP": {
      "abstract": [
        {
          "text": "An object that holds configuration options for an app extension.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@"
        },
        {
          "kind": "attribute",
          "preciseIdentifier": "s:ScM",
          "text": "MainActor"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "attribute",
          "text": "@preconcurrency"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AppExtensionConfiguration"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s8SendableP",
          "text": "Sendable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:19ExtensionFoundation03AppA13ConfigurationP",
      "kind": "symbol",
      "role": "symbol",
      "title": "AppExtensionConfiguration",
      "type": "topic",
      "url": "/documentation/ExtensionFoundation/AppExtensionConfiguration"
    },
    "doc://com.externally.resolved.symbol/s:ScM": {
      "abstract": [
        {
          "text": "A singleton actor whose executor is equivalent to the main dispatch queue.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@globalActor"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "final"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "actor"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MainActor"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:ScM",
      "kind": "symbol",
      "role": "symbol",
      "title": "MainActor",
      "type": "topic",
      "url": "/documentation/Swift/MainActor"
    },
    "doc://com.externally.resolved.symbol/s:s8SendableP": {
      "abstract": [
        {
          "text": "A thread-safe type whose values can be shared across arbitrary concurrent contexts without introducing a risk of data races.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Sendable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s8SendableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "Sendable",
      "type": "topic",
      "url": "/documentation/Swift/Sendable"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:19ExtensionFoundation03AppA13ConfigurationP",
        "doc://com.externally.resolved.symbol/s:s8SendableP"
      ],
      "kind": "relationships",
      "title": "Inherits From",
      "type": "inheritsFrom"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Asset-download-management",
      "generated": true,
      "identifiers": [
        "doc://com.apple.backgroundassets/documentation/BackgroundAssets/BADownloadManager",
        "doc://com.apple.backgroundassets/documentation/BackgroundAssets/BADownloaderExtension-qwaw",
        "doc://com.apple.backgroundassets/documentation/BackgroundAssets/downloading-essential-assets-in-the-background"
      ],
      "title": "Asset download management"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.backgroundassets~1documentation~1BackgroundAssets~1BADownloadManager/title",
          "value": "BADownloadManager"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.backgroundassets~1documentation~1BackgroundAssets~1BADownloadManager/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "BADownloadManager"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.backgroundassets~1documentation~1BackgroundAssets~1BADownloadManager/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "BADownloadManager"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/backgroundassets/badownloaderextensionconfiguration"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    }
  ]
}
