{
  "diffAvailability": {
    "major": {
      "change": "modified",
      "platform": "Xcode",
      "versions": [
        "16.0",
        "16.3 beta 2"
      ]
    },
    "minor": {
      "change": "modified",
      "platform": "Xcode",
      "versions": [
        "16.2",
        "16.3 beta 2"
      ]
    }
  },
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.backgroundassets/documentation/BackgroundAssets"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.backgroundassets/documentation/BackgroundAssets/BAErrorCode"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@BAErrorCode",
    "fragments": [
      {
        "kind": "keyword",
        "text": "enum"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "BAErrorCode"
      }
    ],
    "modules": [
      {
        "name": "Background Assets"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "BAErrorCode"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "17.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "17.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "17.0",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "14.0",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": true,
        "deprecated": false,
        "introducedAt": "18.4",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": true,
        "deprecated": false,
        "introducedAt": "2.4",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Enumeration",
    "symbolKind": "enum",
    "title": "BAErrorCode"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "enum"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "BAErrorCode"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.backgroundassets/documentation/BackgroundAssets": {
      "abstract": [
        {
          "text": "Schedule background downloads of large assets after app installation, when the app updates, and periodically while the app remains on-device.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.backgroundassets/documentation/BackgroundAssets",
      "kind": "symbol",
      "role": "collection",
      "title": "Background Assets",
      "type": "topic",
      "url": "/documentation/backgroundassets"
    },
    "doc://com.apple.backgroundassets/documentation/BackgroundAssets/BAErrorCode": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BAErrorCode"
        }
      ],
      "identifier": "doc://com.apple.backgroundassets/documentation/BackgroundAssets/BAErrorCode",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "BAErrorCode"
        }
      ],
      "role": "symbol",
      "title": "BAErrorCode",
      "type": "topic",
      "url": "/documentation/backgroundassets/baerrorcode"
    },
    "doc://com.apple.backgroundassets/documentation/BackgroundAssets/BAErrorCode/callFromExtensionNotAllowed": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "callFromExtensionNotAllowed"
        }
      ],
      "identifier": "doc://com.apple.backgroundassets/documentation/BackgroundAssets/BAErrorCode/callFromExtensionNotAllowed",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "BAErrorCodeCallFromExtensionNotAllowed"
        }
      ],
      "role": "symbol",
      "title": "BAErrorCode.callFromExtensionNotAllowed",
      "type": "topic",
      "url": "/documentation/backgroundassets/baerrorcode/callfromextensionnotallowed"
    },
    "doc://com.apple.backgroundassets/documentation/BackgroundAssets/BAErrorCode/callFromInactiveProcessNotAllowed": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "callFromInactiveProcessNotAllowed"
        }
      ],
      "identifier": "doc://com.apple.backgroundassets/documentation/BackgroundAssets/BAErrorCode/callFromInactiveProcessNotAllowed",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "BAErrorCodeCallFromInactiveProcessNotAllowed"
        }
      ],
      "role": "symbol",
      "title": "BAErrorCode.callFromInactiveProcessNotAllowed",
      "type": "topic",
      "url": "/documentation/backgroundassets/baerrorcode/callfrominactiveprocessnotallowed"
    },
    "doc://com.apple.backgroundassets/documentation/BackgroundAssets/BAErrorCode/callerConnectionInvalid": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "callerConnectionInvalid"
        }
      ],
      "identifier": "doc://com.apple.backgroundassets/documentation/BackgroundAssets/BAErrorCode/callerConnectionInvalid",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "BAErrorCodeCallerConnectionInvalid"
        }
      ],
      "role": "symbol",
      "title": "BAErrorCode.callerConnectionInvalid",
      "type": "topic",
      "url": "/documentation/backgroundassets/baerrorcode/callerconnectioninvalid"
    },
    "doc://com.apple.backgroundassets/documentation/BackgroundAssets/BAErrorCode/callerConnectionNotAccepted": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "callerConnectionNotAccepted"
        }
      ],
      "identifier": "doc://com.apple.backgroundassets/documentation/BackgroundAssets/BAErrorCode/callerConnectionNotAccepted",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "BAErrorCodeCallerConnectionNotAccepted"
        }
      ],
      "role": "symbol",
      "title": "BAErrorCode.callerConnectionNotAccepted",
      "type": "topic",
      "url": "/documentation/backgroundassets/baerrorcode/callerconnectionnotaccepted"
    },
    "doc://com.apple.backgroundassets/documentation/BackgroundAssets/BAErrorCode/downloadAlreadyFailed": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "downloadAlreadyFailed"
        }
      ],
      "identifier": "doc://com.apple.backgroundassets/documentation/BackgroundAssets/BAErrorCode/downloadAlreadyFailed",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "BAErrorCodeDownloadAlreadyFailed"
        }
      ],
      "role": "symbol",
      "title": "BAErrorCode.downloadAlreadyFailed",
      "type": "topic",
      "url": "/documentation/backgroundassets/baerrorcode/downloadalreadyfailed"
    },
    "doc://com.apple.backgroundassets/documentation/BackgroundAssets/BAErrorCode/downloadAlreadyScheduled": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "downloadAlreadyScheduled"
        }
      ],
      "identifier": "doc://com.apple.backgroundassets/documentation/BackgroundAssets/BAErrorCode/downloadAlreadyScheduled",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "BAErrorCodeDownloadAlreadyScheduled"
        }
      ],
      "role": "symbol",
      "title": "BAErrorCode.downloadAlreadyScheduled",
      "type": "topic",
      "url": "/documentation/backgroundassets/baerrorcode/downloadalreadyscheduled"
    },
    "doc://com.apple.backgroundassets/documentation/BackgroundAssets/BAErrorCode/downloadBackgroundActivityProhibited": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "downloadBackgroundActivityProhibited"
        }
      ],
      "identifier": "doc://com.apple.backgroundassets/documentation/BackgroundAssets/BAErrorCode/downloadBackgroundActivityProhibited",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "BAErrorCodeDownloadBackgroundActivityProhibited"
        }
      ],
      "role": "symbol",
      "title": "BAErrorCode.downloadBackgroundActivityProhibited",
      "type": "topic",
      "url": "/documentation/backgroundassets/baerrorcode/downloadbackgroundactivityprohibited"
    },
    "doc://com.apple.backgroundassets/documentation/BackgroundAssets/BAErrorCode/downloadEssentialDownloadNotPermitted": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "downloadEssentialDownloadNotPermitted"
        }
      ],
      "identifier": "doc://com.apple.backgroundassets/documentation/BackgroundAssets/BAErrorCode/downloadEssentialDownloadNotPermitted",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "BAErrorCodeDownloadEssentialDownloadNotPermitted"
        }
      ],
      "role": "symbol",
      "title": "BAErrorCode.downloadEssentialDownloadNotPermitted",
      "type": "topic",
      "url": "/documentation/backgroundassets/baerrorcode/downloadessentialdownloadnotpermitted"
    },
    "doc://com.apple.backgroundassets/documentation/BackgroundAssets/BAErrorCode/downloadFailedToStart": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "downloadFailedToStart"
        }
      ],
      "identifier": "doc://com.apple.backgroundassets/documentation/BackgroundAssets/BAErrorCode/downloadFailedToStart",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "BAErrorCodeDownloadFailedToStart"
        }
      ],
      "role": "symbol",
      "title": "BAErrorCode.downloadFailedToStart",
      "type": "topic",
      "url": "/documentation/backgroundassets/baerrorcode/downloadfailedtostart"
    },
    "doc://com.apple.backgroundassets/documentation/BackgroundAssets/BAErrorCode/downloadInvalid": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "downloadInvalid"
        }
      ],
      "identifier": "doc://com.apple.backgroundassets/documentation/BackgroundAssets/BAErrorCode/downloadInvalid",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "BAErrorCodeDownloadInvalid"
        }
      ],
      "role": "symbol",
      "title": "BAErrorCode.downloadInvalid",
      "type": "topic",
      "url": "/documentation/backgroundassets/baerrorcode/downloadinvalid"
    },
    "doc://com.apple.backgroundassets/documentation/BackgroundAssets/BAErrorCode/downloadNotScheduled": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "downloadNotScheduled"
        }
      ],
      "identifier": "doc://com.apple.backgroundassets/documentation/BackgroundAssets/BAErrorCode/downloadNotScheduled",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "BAErrorCodeDownloadNotScheduled"
        }
      ],
      "role": "symbol",
      "title": "BAErrorCode.downloadNotScheduled",
      "type": "topic",
      "url": "/documentation/backgroundassets/baerrorcode/downloadnotscheduled"
    },
    "doc://com.apple.backgroundassets/documentation/BackgroundAssets/BAErrorCode/downloadWouldExceedAllowance": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "downloadWouldExceedAllowance"
        }
      ],
      "identifier": "doc://com.apple.backgroundassets/documentation/BackgroundAssets/BAErrorCode/downloadWouldExceedAllowance",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "BAErrorCodeDownloadWouldExceedAllowance"
        }
      ],
      "role": "symbol",
      "title": "BAErrorCode.downloadWouldExceedAllowance",
      "type": "topic",
      "url": "/documentation/backgroundassets/baerrorcode/downloadwouldexceedallowance"
    },
    "doc://com.apple.backgroundassets/documentation/BackgroundAssets/BAErrorCode/init(rawValue:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "?("
        },
        {
          "kind": "externalParam",
          "text": "rawValue"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.backgroundassets/documentation/BackgroundAssets/BAErrorCode/init(rawValue:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "init(rawValue:)",
      "type": "topic",
      "url": "/documentation/backgroundassets/baerrorcode/init(rawvalue:)"
    },
    "doc://com.apple.backgroundassets/documentation/BackgroundAssets/BAErrorCode/sessionDownloadAllowanceExceeded": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "sessionDownloadAllowanceExceeded"
        }
      ],
      "identifier": "doc://com.apple.backgroundassets/documentation/BackgroundAssets/BAErrorCode/sessionDownloadAllowanceExceeded",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "BAErrorCodeSessionDownloadAllowanceExceeded"
        }
      ],
      "role": "symbol",
      "title": "BAErrorCode.sessionDownloadAllowanceExceeded",
      "type": "topic",
      "url": "/documentation/backgroundassets/baerrorcode/sessiondownloadallowanceexceeded"
    },
    "doc://com.apple.backgroundassets/documentation/BackgroundAssets/BAErrorCode/sessionDownloadDisallowedByAllowance": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "sessionDownloadDisallowedByAllowance"
        }
      ],
      "identifier": "doc://com.apple.backgroundassets/documentation/BackgroundAssets/BAErrorCode/sessionDownloadDisallowedByAllowance",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "BAErrorCodeSessionDownloadDisallowedByAllowance"
        }
      ],
      "role": "symbol",
      "title": "BAErrorCode.sessionDownloadDisallowedByAllowance",
      "type": "topic",
      "url": "/documentation/backgroundassets/baerrorcode/sessiondownloaddisallowedbyallowance"
    },
    "doc://com.apple.backgroundassets/documentation/BackgroundAssets/BAErrorCode/sessionDownloadDisallowedByDomain": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "sessionDownloadDisallowedByDomain"
        }
      ],
      "identifier": "doc://com.apple.backgroundassets/documentation/BackgroundAssets/BAErrorCode/sessionDownloadDisallowedByDomain",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "BAErrorCodeSessionDownloadDisallowedByDomain"
        }
      ],
      "role": "symbol",
      "title": "BAErrorCode.sessionDownloadDisallowedByDomain",
      "type": "topic",
      "url": "/documentation/backgroundassets/baerrorcode/sessiondownloaddisallowedbydomain"
    },
    "doc://com.apple.backgroundassets/documentation/BackgroundAssets/BAErrorCode/sessionDownloadNotPermittedBeforeAppLaunch": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "sessionDownloadNotPermittedBeforeAppLaunch"
        }
      ],
      "identifier": "doc://com.apple.backgroundassets/documentation/BackgroundAssets/BAErrorCode/sessionDownloadNotPermittedBeforeAppLaunch",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "BAErrorCodeSessionDownloadNotPermittedBeforeAppLaunch"
        }
      ],
      "role": "symbol",
      "title": "BAErrorCode.sessionDownloadNotPermittedBeforeAppLaunch",
      "type": "topic",
      "url": "/documentation/backgroundassets/baerrorcode/sessiondownloadnotpermittedbeforeapplaunch"
    },
    "doc://com.apple.backgroundassets/documentation/BackgroundAssets/BAErrorDomain": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BAErrorDomain"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.backgroundassets/documentation/BackgroundAssets/BAErrorDomain",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "BAErrorDomain"
        }
      ],
      "role": "symbol",
      "title": "BAErrorDomain",
      "type": "topic",
      "url": "/documentation/backgroundassets/baerrordomain"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.externally.resolved.symbol/s:SH": {
      "abstract": [
        {
          "text": "A type that can be hashed into a `Hasher` to produce an integer hash value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Hashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SQ",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SH",
      "kind": "symbol",
      "role": "symbol",
      "title": "Hashable",
      "type": "topic",
      "url": "/documentation/Swift/Hashable"
    },
    "doc://com.externally.resolved.symbol/s:SQ": {
      "abstract": [
        {
          "text": "A type that can be compared for value equality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SQ",
      "kind": "symbol",
      "role": "symbol",
      "title": "Equatable",
      "type": "topic",
      "url": "/documentation/Swift/Equatable"
    },
    "doc://com.externally.resolved.symbol/s:SY": {
      "abstract": [
        {
          "text": "A type that can be converted to and from an associated raw value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "RawRepresentable"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SY8RawValueQa",
          "text": "RawValue"
        },
        {
          "kind": "text",
          "text": ">"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SY",
      "kind": "symbol",
      "role": "symbol",
      "title": "RawRepresentable",
      "type": "topic",
      "url": "/documentation/Swift/RawRepresentable"
    },
    "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BitwiseCopyable"
        },
        {
          "kind": "text",
          "text": " : ~Escapable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "BitwiseCopyable",
      "type": "topic",
      "url": "/documentation/Swift/BitwiseCopyable"
    },
    "doc://com.externally.resolved.symbol/s:s8SendableP": {
      "abstract": [
        {
          "text": "A thread-safe type whose values can be shared across arbitrary concurrent contexts without introducing a risk of data races.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Sendable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s8SendableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "Sendable",
      "type": "topic",
      "url": "/documentation/Swift/Sendable"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
        "doc://com.externally.resolved.symbol/s:SQ",
        "doc://com.externally.resolved.symbol/s:SH",
        "doc://com.externally.resolved.symbol/s:SY",
        "doc://com.externally.resolved.symbol/s:s8SendableP"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Errors",
      "generated": true,
      "identifiers": [
        "doc://com.apple.backgroundassets/documentation/BackgroundAssets/BAErrorDomain"
      ],
      "title": "Errors"
    }
  ],
  "topicSections": [
    {
      "anchor": "Error-codes",
      "identifiers": [
        "doc://com.apple.backgroundassets/documentation/BackgroundAssets/BAErrorCode/callFromExtensionNotAllowed",
        "doc://com.apple.backgroundassets/documentation/BackgroundAssets/BAErrorCode/callFromInactiveProcessNotAllowed",
        "doc://com.apple.backgroundassets/documentation/BackgroundAssets/BAErrorCode/callerConnectionInvalid",
        "doc://com.apple.backgroundassets/documentation/BackgroundAssets/BAErrorCode/callerConnectionNotAccepted",
        "doc://com.apple.backgroundassets/documentation/BackgroundAssets/BAErrorCode/downloadAlreadyFailed",
        "doc://com.apple.backgroundassets/documentation/BackgroundAssets/BAErrorCode/downloadAlreadyScheduled",
        "doc://com.apple.backgroundassets/documentation/BackgroundAssets/BAErrorCode/downloadBackgroundActivityProhibited",
        "doc://com.apple.backgroundassets/documentation/BackgroundAssets/BAErrorCode/downloadEssentialDownloadNotPermitted",
        "doc://com.apple.backgroundassets/documentation/BackgroundAssets/BAErrorCode/downloadFailedToStart",
        "doc://com.apple.backgroundassets/documentation/BackgroundAssets/BAErrorCode/downloadInvalid",
        "doc://com.apple.backgroundassets/documentation/BackgroundAssets/BAErrorCode/downloadNotScheduled",
        "doc://com.apple.backgroundassets/documentation/BackgroundAssets/BAErrorCode/downloadWouldExceedAllowance",
        "doc://com.apple.backgroundassets/documentation/BackgroundAssets/BAErrorCode/sessionDownloadAllowanceExceeded",
        "doc://com.apple.backgroundassets/documentation/BackgroundAssets/BAErrorCode/sessionDownloadDisallowedByAllowance",
        "doc://com.apple.backgroundassets/documentation/BackgroundAssets/BAErrorCode/sessionDownloadDisallowedByDomain",
        "doc://com.apple.backgroundassets/documentation/BackgroundAssets/BAErrorCode/sessionDownloadNotPermittedBeforeAppLaunch"
      ],
      "title": "Error codes"
    },
    {
      "anchor": "Initializers",
      "generated": true,
      "identifiers": [
        "doc://com.apple.backgroundassets/documentation/BackgroundAssets/BAErrorCode/init(rawValue:)"
      ],
      "title": "Initializers"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "17.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "17.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "17.0",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "14.0",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": true,
              "deprecated": false,
              "introducedAt": "18.4",
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": true,
              "deprecated": false,
              "introducedAt": "2.4",
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "BAErrorCode"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "enum"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "BAErrorCode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "BAErrorCode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.backgroundassets/documentation/BackgroundAssets"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Error-codes",
              "identifiers": [
                "doc://com.apple.backgroundassets/documentation/BackgroundAssets/BAErrorCode/callFromExtensionNotAllowed",
                "doc://com.apple.backgroundassets/documentation/BackgroundAssets/BAErrorCode/callFromInactiveProcessNotAllowed",
                "doc://com.apple.backgroundassets/documentation/BackgroundAssets/BAErrorCode/callerConnectionInvalid",
                "doc://com.apple.backgroundassets/documentation/BackgroundAssets/BAErrorCode/callerConnectionNotAccepted",
                "doc://com.apple.backgroundassets/documentation/BackgroundAssets/BAErrorCode/downloadAlreadyFailed",
                "doc://com.apple.backgroundassets/documentation/BackgroundAssets/BAErrorCode/downloadAlreadyScheduled",
                "doc://com.apple.backgroundassets/documentation/BackgroundAssets/BAErrorCode/downloadBackgroundActivityProhibited",
                "doc://com.apple.backgroundassets/documentation/BackgroundAssets/BAErrorCode/downloadEssentialDownloadNotPermitted",
                "doc://com.apple.backgroundassets/documentation/BackgroundAssets/BAErrorCode/downloadFailedToStart",
                "doc://com.apple.backgroundassets/documentation/BackgroundAssets/BAErrorCode/downloadInvalid",
                "doc://com.apple.backgroundassets/documentation/BackgroundAssets/BAErrorCode/downloadNotScheduled",
                "doc://com.apple.backgroundassets/documentation/BackgroundAssets/BAErrorCode/downloadWouldExceedAllowance",
                "doc://com.apple.backgroundassets/documentation/BackgroundAssets/BAErrorCode/sessionDownloadAllowanceExceeded",
                "doc://com.apple.backgroundassets/documentation/BackgroundAssets/BAErrorCode/sessionDownloadDisallowedByAllowance",
                "doc://com.apple.backgroundassets/documentation/BackgroundAssets/BAErrorCode/sessionDownloadDisallowedByDomain",
                "doc://com.apple.backgroundassets/documentation/BackgroundAssets/BAErrorCode/sessionDownloadNotPermittedBeforeAppLaunch"
              ],
              "title": "Error codes"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Errors",
              "generated": true,
              "identifiers": [
                "doc://com.apple.backgroundassets/documentation/BackgroundAssets/BAErrorDomain"
              ],
              "title": "Errors"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "enum"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "BAErrorCode"
                  },
                  {
                    "kind": "text",
                    "text": " : "
                  },
                  {
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@NSInteger",
                    "text": "NSInteger"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.backgroundassets~1documentation~1BackgroundAssets~1BAErrorCode~1downloadAlreadyScheduled/title",
          "value": "BAErrorCodeDownloadAlreadyScheduled"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.backgroundassets~1documentation~1BackgroundAssets~1BAErrorCode~1downloadAlreadyScheduled/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "BAErrorCodeDownloadAlreadyScheduled"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.backgroundassets~1documentation~1BackgroundAssets~1BAErrorCode~1sessionDownloadDisallowedByDomain/title",
          "value": "BAErrorCodeSessionDownloadDisallowedByDomain"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.backgroundassets~1documentation~1BackgroundAssets~1BAErrorCode~1sessionDownloadDisallowedByDomain/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "BAErrorCodeSessionDownloadDisallowedByDomain"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.backgroundassets~1documentation~1BackgroundAssets~1BAErrorCode~1downloadNotScheduled/title",
          "value": "BAErrorCodeDownloadNotScheduled"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.backgroundassets~1documentation~1BackgroundAssets~1BAErrorCode~1downloadNotScheduled/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "BAErrorCodeDownloadNotScheduled"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.backgroundassets~1documentation~1BackgroundAssets~1BAErrorCode~1callFromInactiveProcessNotAllowed/title",
          "value": "BAErrorCodeCallFromInactiveProcessNotAllowed"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.backgroundassets~1documentation~1BackgroundAssets~1BAErrorCode~1callFromInactiveProcessNotAllowed/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "BAErrorCodeCallFromInactiveProcessNotAllowed"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.backgroundassets~1documentation~1BackgroundAssets~1BAErrorCode~1downloadBackgroundActivityProhibited/title",
          "value": "BAErrorCodeDownloadBackgroundActivityProhibited"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.backgroundassets~1documentation~1BackgroundAssets~1BAErrorCode~1downloadBackgroundActivityProhibited/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "BAErrorCodeDownloadBackgroundActivityProhibited"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.backgroundassets~1documentation~1BackgroundAssets~1BAErrorCode~1sessionDownloadDisallowedByAllowance/title",
          "value": "BAErrorCodeSessionDownloadDisallowedByAllowance"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.backgroundassets~1documentation~1BackgroundAssets~1BAErrorCode~1sessionDownloadDisallowedByAllowance/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "BAErrorCodeSessionDownloadDisallowedByAllowance"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.backgroundassets~1documentation~1BackgroundAssets~1BAErrorCode~1callFromExtensionNotAllowed/title",
          "value": "BAErrorCodeCallFromExtensionNotAllowed"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.backgroundassets~1documentation~1BackgroundAssets~1BAErrorCode~1callFromExtensionNotAllowed/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "BAErrorCodeCallFromExtensionNotAllowed"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.backgroundassets~1documentation~1BackgroundAssets~1BAErrorCode/title",
          "value": "BAErrorCode"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.backgroundassets~1documentation~1BackgroundAssets~1BAErrorCode/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "BAErrorCode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.backgroundassets~1documentation~1BackgroundAssets~1BAErrorCode/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "BAErrorCode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.backgroundassets~1documentation~1BackgroundAssets~1BAErrorCode~1downloadAlreadyFailed/title",
          "value": "BAErrorCodeDownloadAlreadyFailed"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.backgroundassets~1documentation~1BackgroundAssets~1BAErrorCode~1downloadAlreadyFailed/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "BAErrorCodeDownloadAlreadyFailed"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.backgroundassets~1documentation~1BackgroundAssets~1BAErrorCode~1downloadFailedToStart/title",
          "value": "BAErrorCodeDownloadFailedToStart"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.backgroundassets~1documentation~1BackgroundAssets~1BAErrorCode~1downloadFailedToStart/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "BAErrorCodeDownloadFailedToStart"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.backgroundassets~1documentation~1BackgroundAssets~1BAErrorCode~1callerConnectionInvalid/title",
          "value": "BAErrorCodeCallerConnectionInvalid"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.backgroundassets~1documentation~1BackgroundAssets~1BAErrorCode~1callerConnectionInvalid/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "BAErrorCodeCallerConnectionInvalid"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.backgroundassets~1documentation~1BackgroundAssets~1BAErrorCode~1sessionDownloadAllowanceExceeded/title",
          "value": "BAErrorCodeSessionDownloadAllowanceExceeded"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.backgroundassets~1documentation~1BackgroundAssets~1BAErrorCode~1sessionDownloadAllowanceExceeded/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "BAErrorCodeSessionDownloadAllowanceExceeded"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.backgroundassets~1documentation~1BackgroundAssets~1BAErrorCode~1downloadWouldExceedAllowance/title",
          "value": "BAErrorCodeDownloadWouldExceedAllowance"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.backgroundassets~1documentation~1BackgroundAssets~1BAErrorCode~1downloadWouldExceedAllowance/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "BAErrorCodeDownloadWouldExceedAllowance"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.backgroundassets~1documentation~1BackgroundAssets~1BAErrorCode~1sessionDownloadNotPermittedBeforeAppLaunch/title",
          "value": "BAErrorCodeSessionDownloadNotPermittedBeforeAppLaunch"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.backgroundassets~1documentation~1BackgroundAssets~1BAErrorCode~1sessionDownloadNotPermittedBeforeAppLaunch/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "BAErrorCodeSessionDownloadNotPermittedBeforeAppLaunch"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.backgroundassets~1documentation~1BackgroundAssets~1BAErrorCode~1callerConnectionNotAccepted/title",
          "value": "BAErrorCodeCallerConnectionNotAccepted"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.backgroundassets~1documentation~1BackgroundAssets~1BAErrorCode~1callerConnectionNotAccepted/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "BAErrorCodeCallerConnectionNotAccepted"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.backgroundassets~1documentation~1BackgroundAssets~1BAErrorDomain/title",
          "value": "BAErrorDomain"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.backgroundassets~1documentation~1BackgroundAssets~1BAErrorDomain/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "BAErrorDomain"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.backgroundassets~1documentation~1BackgroundAssets~1BAErrorCode~1downloadEssentialDownloadNotPermitted/title",
          "value": "BAErrorCodeDownloadEssentialDownloadNotPermitted"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.backgroundassets~1documentation~1BackgroundAssets~1BAErrorCode~1downloadEssentialDownloadNotPermitted/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "BAErrorCodeDownloadEssentialDownloadNotPermitted"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.backgroundassets~1documentation~1BackgroundAssets~1BAErrorCode~1downloadInvalid/title",
          "value": "BAErrorCodeDownloadInvalid"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.backgroundassets~1documentation~1BackgroundAssets~1BAErrorCode~1downloadInvalid/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "BAErrorCodeDownloadInvalid"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/backgroundassets/baerrorcode"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/backgroundassets/baerrorcode"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
