{
  "abstract": [
    {
      "text": "The configuration being observed.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.Screen-Time/documentation/ScreenTime",
        "doc://com.apple.Screen-Time/documentation/ScreenTime/STScreenTimeConfigurationObserver"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.Screen-Time/documentation/ScreenTime/STScreenTimeConfigurationObserver/configuration"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(cs)STScreenTimeConfigurationObserver(py)configuration",
    "fragments": [
      {
        "kind": "keyword",
        "text": "var"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "configuration"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:objc(cs)STScreenTimeConfiguration",
        "text": "STScreenTimeConfiguration"
      },
      {
        "kind": "text",
        "text": "?"
      }
    ],
    "modules": [
      {
        "name": "Screen Time"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "configuration"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "14.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "14.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "14.0",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "11.0",
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Instance Property",
    "symbolKind": "property",
    "title": "configuration"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "var"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "configuration"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.Screen-Time/documentation/ScreenTime/STScreenTimeConfiguration",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)STScreenTimeConfiguration",
              "text": "STScreenTimeConfiguration"
            },
            {
              "kind": "text",
              "text": "? { "
            },
            {
              "kind": "keyword",
              "text": "get"
            },
            {
              "kind": "text",
              "text": " }"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.Screen-Time/documentation/ScreenTime": {
      "abstract": [
        {
          "text": "Share and manage web-usage data, and observe changes made by a parent or guardian.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.Screen-Time/documentation/ScreenTime",
      "kind": "symbol",
      "role": "collection",
      "title": "Screen Time",
      "type": "topic",
      "url": "/documentation/screentime"
    },
    "doc://com.apple.Screen-Time/documentation/ScreenTime/STScreenTimeConfiguration": {
      "abstract": [
        {
          "text": "The configuration for this device.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "STScreenTimeConfiguration"
        }
      ],
      "identifier": "doc://com.apple.Screen-Time/documentation/ScreenTime/STScreenTimeConfiguration",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "STScreenTimeConfiguration"
        }
      ],
      "role": "symbol",
      "title": "STScreenTimeConfiguration",
      "type": "topic",
      "url": "/documentation/screentime/stscreentimeconfiguration"
    },
    "doc://com.apple.Screen-Time/documentation/ScreenTime/STScreenTimeConfigurationObserver": {
      "abstract": [
        {
          "text": "The object you use to observe changes to the current configuration.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "STScreenTimeConfigurationObserver"
        }
      ],
      "identifier": "doc://com.apple.Screen-Time/documentation/ScreenTime/STScreenTimeConfigurationObserver",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "STScreenTimeConfigurationObserver"
        }
      ],
      "role": "symbol",
      "title": "STScreenTimeConfigurationObserver",
      "type": "topic",
      "url": "/documentation/screentime/stscreentimeconfigurationobserver"
    },
    "doc://com.apple.Screen-Time/documentation/ScreenTime/STScreenTimeConfigurationObserver/configuration": {
      "abstract": [
        {
          "text": "The configuration being observed.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "configuration"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)STScreenTimeConfiguration",
          "text": "STScreenTimeConfiguration"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.Screen-Time/documentation/ScreenTime/STScreenTimeConfigurationObserver/configuration",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "configuration"
        }
      ],
      "role": "symbol",
      "title": "configuration",
      "type": "topic",
      "url": "/documentation/screentime/stscreentimeconfigurationobserver/configuration"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "14.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "14.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "14.0",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "11.0",
              "name": "macOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Instance Property"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "configuration"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "property"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "configuration"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.Screen-Time/documentation/ScreenTime",
                "doc://com.apple.Screen-Time/documentation/ScreenTime/STScreenTimeConfigurationObserver"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/seeAlsoSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "@property"
                  },
                  {
                    "kind": "text",
                    "text": " ("
                  },
                  {
                    "kind": "keyword",
                    "text": "strong"
                  },
                  {
                    "kind": "text",
                    "text": ", "
                  },
                  {
                    "kind": "keyword",
                    "text": "readonly"
                  },
                  {
                    "kind": "text",
                    "text": ") "
                  },
                  {
                    "identifier": "doc://com.apple.Screen-Time/documentation/ScreenTime/STScreenTimeConfiguration",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(cs)STScreenTimeConfiguration",
                    "text": "STScreenTimeConfiguration"
                  },
                  {
                    "kind": "text",
                    "text": " * "
                  },
                  {
                    "kind": "identifier",
                    "text": "configuration"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.Screen-Time~1documentation~1ScreenTime~1STScreenTimeConfigurationObserver~1configuration/title",
          "value": "configuration"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.Screen-Time~1documentation~1ScreenTime~1STScreenTimeConfigurationObserver~1configuration/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "configuration"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.Screen-Time~1documentation~1ScreenTime~1STScreenTimeConfigurationObserver/title",
          "value": "STScreenTimeConfigurationObserver"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.Screen-Time~1documentation~1ScreenTime~1STScreenTimeConfigurationObserver/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "STScreenTimeConfigurationObserver"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.Screen-Time~1documentation~1ScreenTime~1STScreenTimeConfigurationObserver/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "STScreenTimeConfigurationObserver"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.Screen-Time~1documentation~1ScreenTime~1STScreenTimeConfiguration/title",
          "value": "STScreenTimeConfiguration"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.Screen-Time~1documentation~1ScreenTime~1STScreenTimeConfiguration/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "STScreenTimeConfiguration"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.Screen-Time~1documentation~1ScreenTime~1STScreenTimeConfiguration/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "STScreenTimeConfiguration"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/screentime/stscreentimeconfigurationobserver/configuration"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/screentime/stscreentimeconfigurationobserver/configuration"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
