{
  "abstract": [
    {
      "text": "An injectable contraceptive.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.healthkit/documentation/HealthKit",
        "doc://com.apple.healthkit/documentation/HealthKit/HKCategoryValueContraceptive"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.healthkit/documentation/HealthKit/HKCategoryValueContraceptive/injection"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@HKCategoryValueContraceptive@HKCategoryValueContraceptiveInjection",
    "fragments": [
      {
        "kind": "keyword",
        "text": "case"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "injection"
      }
    ],
    "modules": [
      {
        "name": "HealthKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "HKCategoryValueContraceptiveInjection"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "14.3",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "14.3",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "14.3",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.0",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "7.2",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Case",
    "symbolKind": "case",
    "title": "HKCategoryValueContraceptive.injection"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "case"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "injection"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.healthkit/documentation/HealthKit": {
      "abstract": [
        {
          "text": "Access and share health and fitness data while maintaining the user’s privacy and control.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit",
      "kind": "symbol",
      "role": "collection",
      "title": "HealthKit",
      "type": "topic",
      "url": "/documentation/healthkit"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/HKCategoryValueContraceptive": {
      "abstract": [
        {
          "text": "The type of contraceptive.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "HKCategoryValueContraceptive"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKCategoryValueContraceptive",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HKCategoryValueContraceptive"
        }
      ],
      "role": "symbol",
      "title": "HKCategoryValueContraceptive",
      "type": "topic",
      "url": "/documentation/healthkit/hkcategoryvaluecontraceptive"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/HKCategoryValueContraceptive/implant": {
      "abstract": [
        {
          "text": "A contraceptive implant.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "implant"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKCategoryValueContraceptive/implant",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HKCategoryValueContraceptiveImplant"
        }
      ],
      "role": "symbol",
      "title": "HKCategoryValueContraceptive.implant",
      "type": "topic",
      "url": "/documentation/healthkit/hkcategoryvaluecontraceptive/implant"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/HKCategoryValueContraceptive/injection": {
      "abstract": [
        {
          "text": "An injectable contraceptive.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "injection"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKCategoryValueContraceptive/injection",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HKCategoryValueContraceptiveInjection"
        }
      ],
      "role": "symbol",
      "title": "HKCategoryValueContraceptive.injection",
      "type": "topic",
      "url": "/documentation/healthkit/hkcategoryvaluecontraceptive/injection"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/HKCategoryValueContraceptive/intrauterineDevice": {
      "abstract": [
        {
          "text": "An intrauterine device (IUD).",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "intrauterineDevice"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKCategoryValueContraceptive/intrauterineDevice",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HKCategoryValueContraceptiveIntrauterineDevice"
        }
      ],
      "role": "symbol",
      "title": "HKCategoryValueContraceptive.intrauterineDevice",
      "type": "topic",
      "url": "/documentation/healthkit/hkcategoryvaluecontraceptive/intrauterinedevice"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/HKCategoryValueContraceptive/intravaginalRing": {
      "abstract": [
        {
          "text": "A contraceptive intravaginal ring.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "intravaginalRing"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKCategoryValueContraceptive/intravaginalRing",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HKCategoryValueContraceptiveIntravaginalRing"
        }
      ],
      "role": "symbol",
      "title": "HKCategoryValueContraceptive.intravaginalRing",
      "type": "topic",
      "url": "/documentation/healthkit/hkcategoryvaluecontraceptive/intravaginalring"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/HKCategoryValueContraceptive/oral": {
      "abstract": [
        {
          "text": "An oral contraceptive.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "oral"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKCategoryValueContraceptive/oral",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HKCategoryValueContraceptiveOral"
        }
      ],
      "role": "symbol",
      "title": "HKCategoryValueContraceptive.oral",
      "type": "topic",
      "url": "/documentation/healthkit/hkcategoryvaluecontraceptive/oral"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/HKCategoryValueContraceptive/patch": {
      "abstract": [
        {
          "text": "A contraceptive patch.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "patch"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKCategoryValueContraceptive/patch",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HKCategoryValueContraceptivePatch"
        }
      ],
      "role": "symbol",
      "title": "HKCategoryValueContraceptive.patch",
      "type": "topic",
      "url": "/documentation/healthkit/hkcategoryvaluecontraceptive/patch"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/HKCategoryValueContraceptive/unspecified": {
      "abstract": [
        {
          "text": "An unspecified type of contraceptive.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "unspecified"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKCategoryValueContraceptive/unspecified",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HKCategoryValueContraceptiveUnspecified"
        }
      ],
      "role": "symbol",
      "title": "HKCategoryValueContraceptive.unspecified",
      "type": "topic",
      "url": "/documentation/healthkit/hkcategoryvaluecontraceptive/unspecified"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Contraceptive-Types",
      "generated": true,
      "identifiers": [
        "doc://com.apple.healthkit/documentation/HealthKit/HKCategoryValueContraceptive/unspecified",
        "doc://com.apple.healthkit/documentation/HealthKit/HKCategoryValueContraceptive/implant",
        "doc://com.apple.healthkit/documentation/HealthKit/HKCategoryValueContraceptive/intrauterineDevice",
        "doc://com.apple.healthkit/documentation/HealthKit/HKCategoryValueContraceptive/intravaginalRing",
        "doc://com.apple.healthkit/documentation/HealthKit/HKCategoryValueContraceptive/oral",
        "doc://com.apple.healthkit/documentation/HealthKit/HKCategoryValueContraceptive/patch"
      ],
      "title": "Contraceptive Types"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "14.3",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "14.3",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "14.3",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.0",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "7.2",
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration Case"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "HKCategoryValueContraceptiveInjection"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "case"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HKCategoryValueContraceptiveInjection"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.healthkit/documentation/HealthKit",
                "doc://com.apple.healthkit/documentation/HealthKit/HKCategoryValueContraceptive"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Contraceptive-Types",
              "generated": true,
              "identifiers": [
                "doc://com.apple.healthkit/documentation/HealthKit/HKCategoryValueContraceptive/unspecified",
                "doc://com.apple.healthkit/documentation/HealthKit/HKCategoryValueContraceptive/implant",
                "doc://com.apple.healthkit/documentation/HealthKit/HKCategoryValueContraceptive/intrauterineDevice",
                "doc://com.apple.healthkit/documentation/HealthKit/HKCategoryValueContraceptive/intravaginalRing",
                "doc://com.apple.healthkit/documentation/HealthKit/HKCategoryValueContraceptive/oral",
                "doc://com.apple.healthkit/documentation/HealthKit/HKCategoryValueContraceptive/patch"
              ],
              "title": "Contraceptive Types"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "identifier",
                    "text": "HKCategoryValueContraceptiveInjection"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKCategoryValueContraceptive~1injection/title",
          "value": "HKCategoryValueContraceptiveInjection"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKCategoryValueContraceptive~1injection/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HKCategoryValueContraceptiveInjection"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKCategoryValueContraceptive/title",
          "value": "HKCategoryValueContraceptive"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKCategoryValueContraceptive/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HKCategoryValueContraceptive"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKCategoryValueContraceptive/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "HKCategoryValueContraceptive"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKCategoryValueContraceptive~1patch/title",
          "value": "HKCategoryValueContraceptivePatch"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKCategoryValueContraceptive~1patch/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HKCategoryValueContraceptivePatch"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKCategoryValueContraceptive~1unspecified/title",
          "value": "HKCategoryValueContraceptiveUnspecified"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKCategoryValueContraceptive~1unspecified/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HKCategoryValueContraceptiveUnspecified"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKCategoryValueContraceptive~1oral/title",
          "value": "HKCategoryValueContraceptiveOral"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKCategoryValueContraceptive~1oral/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HKCategoryValueContraceptiveOral"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKCategoryValueContraceptive~1intravaginalRing/title",
          "value": "HKCategoryValueContraceptiveIntravaginalRing"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKCategoryValueContraceptive~1intravaginalRing/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HKCategoryValueContraceptiveIntravaginalRing"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKCategoryValueContraceptive~1intrauterineDevice/title",
          "value": "HKCategoryValueContraceptiveIntrauterineDevice"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKCategoryValueContraceptive~1intrauterineDevice/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HKCategoryValueContraceptiveIntrauterineDevice"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKCategoryValueContraceptive~1implant/title",
          "value": "HKCategoryValueContraceptiveImplant"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKCategoryValueContraceptive~1implant/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HKCategoryValueContraceptiveImplant"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/healthkit/hkcategoryvaluecontraceptive/injection"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/healthkit/hkcategoryvaluecontraceptive/injection"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
