{
  "abstract": [
    {
      "text": "Returns a pattern object for the specified pattern string.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.webkit/documentation/WebKit",
        "doc://com.apple.webkit/documentation/WebKit/WKWebExtension/MatchPattern"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "occ",
    "url": "doc://com.apple.webkit/documentation/WebKit/WKWebExtensionMatchPattern/matchPatternWithString:"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(cs)WKWebExtensionMatchPattern(cm)matchPatternWithString:",
    "fragments": [
      {
        "kind": "text",
        "text": "+ "
      },
      {
        "kind": "identifier",
        "text": "matchPatternWithString:"
      }
    ],
    "modules": [
      {
        "name": "WebKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "matchPatternWithString:"
      }
    ],
    "platforms": [
      {
        "beta": true,
        "deprecated": false,
        "introducedAt": "18.4",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": true,
        "deprecated": false,
        "introducedAt": "18.4",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": true,
        "deprecated": false,
        "introducedAt": "18.4",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": true,
        "deprecated": false,
        "introducedAt": "15.4",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": true,
        "deprecated": false,
        "introducedAt": "2.4",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Type Method",
    "symbolKind": "method",
    "title": "matchPatternWithString:"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "occ"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "text",
              "text": "+ ("
            },
            {
              "kind": "keyword",
              "text": "instancetype"
            },
            {
              "kind": "text",
              "text": ") "
            },
            {
              "kind": "identifier",
              "text": "matchPatternWithString:"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSString",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)NSString",
              "text": "NSString"
            },
            {
              "kind": "text",
              "text": " *) "
            },
            {
              "kind": "internalParam",
              "text": "string"
            },
            {
              "kind": "text",
              "text": ";"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "return-value",
          "level": 2,
          "text": "Return Value",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Returns ",
              "type": "text"
            },
            {
              "code": "nil",
              "type": "codeVoice"
            },
            {
              "text": " if the pattern string is invalid.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.webkit/documentation/WebKit": {
      "abstract": [
        {
          "text": "Integrate web content seamlessly into your app, and customize content interactions to meet your app’s needs.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.webkit/documentation/WebKit",
      "kind": "symbol",
      "role": "collection",
      "title": "WebKit",
      "type": "topic",
      "url": "/documentation/webkit"
    },
    "doc://com.apple.webkit/documentation/WebKit/WKWebExtension/MatchPattern": {
      "abstract": [
        {
          "text": "An object that represents a way to specify groups of URLs.",
          "type": "text"
        }
      ],
      "beta": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MatchPattern"
        }
      ],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/WKWebExtension/MatchPattern",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MatchPattern"
        }
      ],
      "role": "symbol",
      "title": "WKWebExtension.MatchPattern",
      "type": "topic",
      "url": "/documentation/webkit/wkwebextension/matchpattern"
    },
    "doc://com.apple.webkit/documentation/WebKit/WKWebExtension/MatchPattern/init(string:)": {
      "abstract": [
        {
          "text": "Returns a pattern object for the specified pattern string.",
          "type": "text"
        }
      ],
      "beta": true,
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "string"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": ") "
        },
        {
          "kind": "keyword",
          "text": "throws"
        }
      ],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/WKWebExtension/MatchPattern/init(string:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "initWithString:error:"
        }
      ],
      "role": "symbol",
      "title": "init(string:)",
      "type": "topic",
      "url": "/documentation/webkit/wkwebextension/matchpattern/init(string:)"
    },
    "doc://com.apple.webkit/documentation/WebKit/WKWebExtensionMatchPattern/matchPatternWithString:": {
      "abstract": [
        {
          "text": "Returns a pattern object for the specified pattern string.",
          "type": "text"
        }
      ],
      "beta": true,
      "fragments": [
        {
          "kind": "text",
          "text": "+ "
        },
        {
          "kind": "identifier",
          "text": "matchPatternWithString:"
        }
      ],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/WKWebExtensionMatchPattern/matchPatternWithString:",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "matchPatternWithString:"
        }
      ],
      "role": "symbol",
      "title": "matchPatternWithString:",
      "type": "topic",
      "url": "/documentation/webkit/wkwebextensionmatchpattern/matchpatternwithstring:"
    },
    "doc://com.externally.resolved.symbol/c:objc(cs)NSString": {
      "abstract": [
        {
          "text": "A static, plain-text Unicode string object which you use when you need reference semantics or other Foundation-specific behavior. ",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "class "
        },
        {
          "kind": "identifier",
          "text": "NSString"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSString",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSString",
      "type": "topic",
      "url": "/documentation/foundation/nsstring"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Related-Documentation",
      "identifiers": [
        "doc://com.apple.webkit/documentation/WebKit/WKWebExtension/MatchPattern/init(string:)"
      ],
      "title": "Related Documentation"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WKWebExtension~1MatchPattern~1init(string:)/title",
          "value": "initWithString:error:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WKWebExtension~1MatchPattern~1init(string:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "initWithString:error:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:objc(cs)NSString/abstract",
          "value": [
            {
              "text": "A static, plain-text Unicode string object.",
              "type": "text"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WKWebExtension~1MatchPattern/title",
          "value": "WKWebExtensionMatchPattern"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WKWebExtension~1MatchPattern/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "WKWebExtensionMatchPattern"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WKWebExtension~1MatchPattern/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "WKWebExtensionMatchPattern"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/webkit/wkwebextensionmatchpattern/matchpatternwithstring:"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
