{
  "abstract": [
    {
      "text": "The user’s considerably below-normal score persists over a significant period of time.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.healthkit/documentation/HealthKit",
        "doc://com.apple.healthkit/documentation/HealthKit/HKCategoryValueAppleWalkingSteadinessEvent"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.healthkit/documentation/HealthKit/HKCategoryValueAppleWalkingSteadinessEvent/repeatVeryLow"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@HKCategoryValueAppleWalkingSteadinessEvent@HKCategoryValueAppleWalkingSteadinessEventRepeatVeryLow",
    "fragments": [
      {
        "kind": "keyword",
        "text": "case"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "repeatVeryLow"
      }
    ],
    "modules": [
      {
        "name": "HealthKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "HKCategoryValueAppleWalkingSteadinessEventRepeatVeryLow"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "15.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "15.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "15.0",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.0",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "8.0",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Case",
    "symbolKind": "case",
    "title": "HKCategoryValueAppleWalkingSteadinessEvent.repeatVeryLow"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "case"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "repeatVeryLow"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.healthkit/documentation/HealthKit": {
      "abstract": [
        {
          "text": "Access and share health and fitness data while maintaining the user’s privacy and control.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit",
      "kind": "symbol",
      "role": "collection",
      "title": "HealthKit",
      "type": "topic",
      "url": "/documentation/healthkit"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/HKCategoryValueAppleWalkingSteadinessEvent": {
      "abstract": [
        {
          "text": "The value of an event triggered by a reduced score for the steadiness of the user’s gait.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "HKCategoryValueAppleWalkingSteadinessEvent"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKCategoryValueAppleWalkingSteadinessEvent",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HKCategoryValueAppleWalkingSteadinessEvent"
        }
      ],
      "role": "symbol",
      "title": "HKCategoryValueAppleWalkingSteadinessEvent",
      "type": "topic",
      "url": "/documentation/healthkit/hkcategoryvalueapplewalkingsteadinessevent"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/HKCategoryValueAppleWalkingSteadinessEvent/initialLow": {
      "abstract": [
        {
          "text": "The user received a below-normal steadiness score for their gait while walking.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "initialLow"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKCategoryValueAppleWalkingSteadinessEvent/initialLow",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HKCategoryValueAppleWalkingSteadinessEventInitialLow"
        }
      ],
      "role": "symbol",
      "title": "HKCategoryValueAppleWalkingSteadinessEvent.initialLow",
      "type": "topic",
      "url": "/documentation/healthkit/hkcategoryvalueapplewalkingsteadinessevent/initiallow"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/HKCategoryValueAppleWalkingSteadinessEvent/initialVeryLow": {
      "abstract": [
        {
          "text": "The user received a steadiness score for their gait while walking that was considerably below normal.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "initialVeryLow"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKCategoryValueAppleWalkingSteadinessEvent/initialVeryLow",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HKCategoryValueAppleWalkingSteadinessEventInitialVeryLow"
        }
      ],
      "role": "symbol",
      "title": "HKCategoryValueAppleWalkingSteadinessEvent.initialVeryLow",
      "type": "topic",
      "url": "/documentation/healthkit/hkcategoryvalueapplewalkingsteadinessevent/initialverylow"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/HKCategoryValueAppleWalkingSteadinessEvent/repeatLow": {
      "abstract": [
        {
          "text": "The user’s below-normal score persists over a significant period of time.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "repeatLow"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKCategoryValueAppleWalkingSteadinessEvent/repeatLow",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HKCategoryValueAppleWalkingSteadinessEventRepeatLow"
        }
      ],
      "role": "symbol",
      "title": "HKCategoryValueAppleWalkingSteadinessEvent.repeatLow",
      "type": "topic",
      "url": "/documentation/healthkit/hkcategoryvalueapplewalkingsteadinessevent/repeatlow"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/HKCategoryValueAppleWalkingSteadinessEvent/repeatVeryLow": {
      "abstract": [
        {
          "text": "The user’s considerably below-normal score persists over a significant period of time.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "repeatVeryLow"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKCategoryValueAppleWalkingSteadinessEvent/repeatVeryLow",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HKCategoryValueAppleWalkingSteadinessEventRepeatVeryLow"
        }
      ],
      "role": "symbol",
      "title": "HKCategoryValueAppleWalkingSteadinessEvent.repeatVeryLow",
      "type": "topic",
      "url": "/documentation/healthkit/hkcategoryvalueapplewalkingsteadinessevent/repeatverylow"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Steadiness-Values",
      "generated": true,
      "identifiers": [
        "doc://com.apple.healthkit/documentation/HealthKit/HKCategoryValueAppleWalkingSteadinessEvent/initialLow",
        "doc://com.apple.healthkit/documentation/HealthKit/HKCategoryValueAppleWalkingSteadinessEvent/initialVeryLow",
        "doc://com.apple.healthkit/documentation/HealthKit/HKCategoryValueAppleWalkingSteadinessEvent/repeatLow"
      ],
      "title": "Steadiness Values"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "15.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "15.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "15.0",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.0",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "8.0",
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration Case"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "HKCategoryValueAppleWalkingSteadinessEventRepeatVeryLow"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "case"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HKCategoryValueAppleWalkingSteadinessEventRepeatVeryLow"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.healthkit/documentation/HealthKit",
                "doc://com.apple.healthkit/documentation/HealthKit/HKCategoryValueAppleWalkingSteadinessEvent"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Steadiness-Values",
              "generated": true,
              "identifiers": [
                "doc://com.apple.healthkit/documentation/HealthKit/HKCategoryValueAppleWalkingSteadinessEvent/initialLow",
                "doc://com.apple.healthkit/documentation/HealthKit/HKCategoryValueAppleWalkingSteadinessEvent/initialVeryLow",
                "doc://com.apple.healthkit/documentation/HealthKit/HKCategoryValueAppleWalkingSteadinessEvent/repeatLow"
              ],
              "title": "Steadiness Values"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "identifier",
                    "text": "HKCategoryValueAppleWalkingSteadinessEventRepeatVeryLow"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKCategoryValueAppleWalkingSteadinessEvent~1initialVeryLow/title",
          "value": "HKCategoryValueAppleWalkingSteadinessEventInitialVeryLow"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKCategoryValueAppleWalkingSteadinessEvent~1initialVeryLow/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HKCategoryValueAppleWalkingSteadinessEventInitialVeryLow"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKCategoryValueAppleWalkingSteadinessEvent~1repeatVeryLow/title",
          "value": "HKCategoryValueAppleWalkingSteadinessEventRepeatVeryLow"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKCategoryValueAppleWalkingSteadinessEvent~1repeatVeryLow/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HKCategoryValueAppleWalkingSteadinessEventRepeatVeryLow"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKCategoryValueAppleWalkingSteadinessEvent~1repeatLow/title",
          "value": "HKCategoryValueAppleWalkingSteadinessEventRepeatLow"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKCategoryValueAppleWalkingSteadinessEvent~1repeatLow/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HKCategoryValueAppleWalkingSteadinessEventRepeatLow"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKCategoryValueAppleWalkingSteadinessEvent/title",
          "value": "HKCategoryValueAppleWalkingSteadinessEvent"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKCategoryValueAppleWalkingSteadinessEvent/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HKCategoryValueAppleWalkingSteadinessEvent"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKCategoryValueAppleWalkingSteadinessEvent/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "HKCategoryValueAppleWalkingSteadinessEvent"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKCategoryValueAppleWalkingSteadinessEvent~1initialLow/title",
          "value": "HKCategoryValueAppleWalkingSteadinessEventInitialLow"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKCategoryValueAppleWalkingSteadinessEvent~1initialLow/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HKCategoryValueAppleWalkingSteadinessEventInitialLow"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/healthkit/hkcategoryvalueapplewalkingsteadinessevent/repeatverylow"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/healthkit/hkcategoryvalueapplewalkingsteadinessevent/repeatverylow"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
