{
  "abstract": [
    {
      "text": "Scale each dimension to exactly fit destination.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.appkit/documentation/AppKit",
        "doc://com.apple.appkit/documentation/AppKit/NSImageScaling"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.appkit/documentation/AppKit/NSImageScaling/scaleAxesIndependently"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@NSImageScaling@NSImageScaleAxesIndependently",
    "fragments": [
      {
        "kind": "keyword",
        "text": "case"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "scaleAxesIndependently"
      }
    ],
    "modules": [
      {
        "name": "AppKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "NSImageScaleAxesIndependently"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.5",
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Case",
    "symbolKind": "case",
    "title": "NSImageScaling.scaleAxesIndependently"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "macOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "case"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "scaleAxesIndependently"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "This setting does not preserve the aspect ratio of the image.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.appkit/documentation/AppKit": {
      "abstract": [
        {
          "text": "Construct and manage a graphical, event-driven user interface for your macOS app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit",
      "kind": "symbol",
      "role": "collection",
      "title": "AppKit",
      "type": "topic",
      "url": "/documentation/appkit"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSImageScaling": {
      "abstract": [
        {
          "text": "Constants that specify a cell’s image scaling behavior.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSImageScaling"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSImageScaling",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSImageScaling"
        }
      ],
      "role": "symbol",
      "title": "NSImageScaling",
      "type": "topic",
      "url": "/documentation/appkit/nsimagescaling"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSImageScaling/scaleAxesIndependently": {
      "abstract": [
        {
          "text": "Scale each dimension to exactly fit destination.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "scaleAxesIndependently"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSImageScaling/scaleAxesIndependently",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSImageScaleAxesIndependently"
        }
      ],
      "role": "symbol",
      "title": "NSImageScaling.scaleAxesIndependently",
      "type": "topic",
      "url": "/documentation/appkit/nsimagescaling/scaleaxesindependently"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSImageScaling/scaleNone": {
      "abstract": [
        {
          "text": "Do not scale the image.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "scaleNone"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSImageScaling/scaleNone",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSImageScaleNone"
        }
      ],
      "role": "symbol",
      "title": "NSImageScaling.scaleNone",
      "type": "topic",
      "url": "/documentation/appkit/nsimagescaling/scalenone"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSImageScaling/scaleProportionallyDown": {
      "abstract": [
        {
          "text": "If it is too large for the destination, scale the image down while preserving the aspect ratio.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "scaleProportionallyDown"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSImageScaling/scaleProportionallyDown",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSImageScaleProportionallyDown"
        }
      ],
      "role": "symbol",
      "title": "NSImageScaling.scaleProportionallyDown",
      "type": "topic",
      "url": "/documentation/appkit/nsimagescaling/scaleproportionallydown"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSImageScaling/scaleProportionallyUpOrDown": {
      "abstract": [
        {
          "text": "Scale the image to its maximum possible dimensions while both staying within the destination area and preserving its aspect ratio.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "scaleProportionallyUpOrDown"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSImageScaling/scaleProportionallyUpOrDown",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSImageScaleProportionallyUpOrDown"
        }
      ],
      "role": "symbol",
      "title": "NSImageScaling.scaleProportionallyUpOrDown",
      "type": "topic",
      "url": "/documentation/appkit/nsimagescaling/scaleproportionallyupordown"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Constants",
      "generated": true,
      "identifiers": [
        "doc://com.apple.appkit/documentation/AppKit/NSImageScaling/scaleProportionallyDown",
        "doc://com.apple.appkit/documentation/AppKit/NSImageScaling/scaleNone",
        "doc://com.apple.appkit/documentation/AppKit/NSImageScaling/scaleProportionallyUpOrDown"
      ],
      "title": "Constants"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.5",
              "name": "macOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration Case"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "NSImageScaleAxesIndependently"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "case"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSImageScaleAxesIndependently"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.appkit/documentation/AppKit",
                "doc://com.apple.appkit/documentation/AppKit/NSImageScaling"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Constants",
              "generated": true,
              "identifiers": [
                "doc://com.apple.appkit/documentation/AppKit/NSImageScaling/scaleProportionallyDown",
                "doc://com.apple.appkit/documentation/AppKit/NSImageScaling/scaleNone",
                "doc://com.apple.appkit/documentation/AppKit/NSImageScaling/scaleProportionallyUpOrDown"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "Mac Catalyst",
                  "macOS"
                ],
                "tokens": [
                  {
                    "kind": "identifier",
                    "text": "NSImageScaleAxesIndependently"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSImageScaling~1scaleNone/title",
          "value": "NSImageScaleNone"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSImageScaling~1scaleNone/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSImageScaleNone"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSImageScaling~1scaleProportionallyDown/title",
          "value": "NSImageScaleProportionallyDown"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSImageScaling~1scaleProportionallyDown/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSImageScaleProportionallyDown"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSImageScaling~1scaleAxesIndependently/title",
          "value": "NSImageScaleAxesIndependently"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSImageScaling~1scaleAxesIndependently/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSImageScaleAxesIndependently"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSImageScaling/title",
          "value": "NSImageScaling"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSImageScaling/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSImageScaling"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSImageScaling/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSImageScaling"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSImageScaling~1scaleProportionallyUpOrDown/title",
          "value": "NSImageScaleProportionallyUpOrDown"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSImageScaling~1scaleProportionallyUpOrDown/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSImageScaleProportionallyUpOrDown"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/appkit/nsimagescaling/scaleaxesindependently"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/appkit/nsimagescaling/scaleaxesindependently"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
