{
  "abstract": [
    {
      "text": "Released September 19, 2019 — Version 13 (15608.2.11)",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.Safari-Release-Notes/documentation/safari-release-notes"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.Safari-Release-Notes/documentation/Safari-Release-Notes/safari-13-release-notes"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "role": "article",
    "roleHeading": "Article",
    "title": "Safari 13 Release Notes"
  },
  "primaryContentSections": [
    {
      "content": [
        {
          "anchor": "Overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Safari 13 ships with iOS 13 and macOS 10.15. It’s also available for macOS 10.14.5 and 10.13.6.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "anchor": "General",
          "level": 3,
          "text": "General",
          "type": "heading"
        },
        {
          "anchor": "New-Features",
          "level": 4,
          "text": "New Features",
          "type": "heading"
        },
        {
          "items": [
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Added Desktop-class Browsing to Safari for iPad. Safari for iPad displays the same desktop websites as Safari for macOS, and provides the same capabilities. In addition it has more keyboard shortcuts, a download manager with background downloads, and support for top productivity websites.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Added opt-in dark mode support for websites in Safari for iOS.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Added support for aborting Fetch requests.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            }
          ],
          "type": "unorderedList"
        },
        {
          "anchor": "Authentication-and-Passwords",
          "level": 3,
          "text": "Authentication and Passwords",
          "type": "heading"
        },
        {
          "anchor": "New-Features",
          "level": 4,
          "text": "New Features",
          "type": "heading"
        },
        {
          "items": [
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Updated Safari to prompt the user to change weak passwords when signing into a website. Requesting a password change uses the well-known URL for changing passwords, enabling websites to specify the page to open for updating a password.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Added support for FIDO2-compliant USB security keys with the Web Authentication standard in Safari on macOS.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Added support for Sign in With Apple to Safari and to ",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.documentation/documentation/WebKit/WKWebView",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": ".",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            }
          ],
          "type": "unorderedList"
        },
        {
          "anchor": "Security-and-Privacy",
          "level": 3,
          "text": "Security and Privacy",
          "type": "heading"
        },
        {
          "anchor": "New-Features",
          "level": 4,
          "text": "New Features",
          "type": "heading"
        },
        {
          "items": [
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Added a permission API on iOS for ",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.documentation/documentation/webkitjs/devicemotionevent",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": " and ",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.documentation/documentation/webkitjs/deviceorientationevent",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": ".",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Changed the behavior for third party iframes to prevent them automatically navigating the page.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Updated Intelligent Tracking Prevention to prevent cross-site tracking through referrer and through link decoration.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Improved the privacy of local WebRTC data connections with mDNS ICE candidates.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Increased the security for WebKit sandboxes on iOS and macOS.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            }
          ],
          "type": "unorderedList"
        },
        {
          "anchor": "Layout-and-Rendering",
          "level": 3,
          "text": "Layout and Rendering",
          "type": "heading"
        },
        {
          "anchor": "New-Features",
          "level": 4,
          "text": "New Features",
          "type": "heading"
        },
        {
          "items": [
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Added support for one-finger accelerated scrolling to all frames and ",
                      "type": "text"
                    },
                    {
                      "code": "overflow:scroll",
                      "type": "codeVoice"
                    },
                    {
                      "text": " elements eliminating the need to ",
                      "type": "text"
                    },
                    {
                      "code": "set-webkit-overflow-scrolling: touch",
                      "type": "codeVoice"
                    },
                    {
                      "text": ".",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Changed the default behavior on iPad for wide web pages with responsive meta-tags that require horizontal scrolling. Pages are scaled to prevent horizontal scrolling and any text is resized to preserve legibility.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Added support for CSS conic gradients.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            }
          ],
          "type": "unorderedList"
        },
        {
          "anchor": "Performance",
          "level": 3,
          "text": "Performance",
          "type": "heading"
        },
        {
          "anchor": "New-Features",
          "level": 4,
          "text": "New Features",
          "type": "heading"
        },
        {
          "items": [
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Reduced the initial rendering time for webpages on iOS.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Added automatic support for Fast Tap to desktop websites on iPad.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Reduced load time up to 50% for webpages on watchOS.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Reduced the amount of memory used by JavaScript, including for non-web clients.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Improved the MotionMark graphics performance benchmark score by 10%.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            }
          ],
          "type": "unorderedList"
        },
        {
          "anchor": "Web-API",
          "level": 3,
          "text": "Web API",
          "type": "heading"
        },
        {
          "anchor": "New-Features",
          "level": 4,
          "text": "New Features",
          "type": "heading"
        },
        {
          "items": [
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Added support for the ",
                      "type": "text"
                    },
                    {
                      "code": "__Secure-",
                      "type": "codeVoice"
                    },
                    {
                      "text": " and ",
                      "type": "text"
                    },
                    {
                      "code": "__Host-",
                      "type": "codeVoice"
                    },
                    {
                      "text": " cookie prefixes in beta 3.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Improved iPad hardware keyboard support for websites including focus navigation and scrolling with the arrow keys.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Added support for the Pointer Events API enabling consistent access to mouse, trackpad, touch, and Apple Pencil events.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Added support for the Visual Viewport API for adjusting web content to avoid overlays, such as the onscreen keyboard.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Added support for programmatic paste with user consent to Safari for iOS.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Updated editing callouts to avoid in-page controls.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Added intelligent whitespace to editable WebViews and editable areas of webpages.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            }
          ],
          "type": "unorderedList"
        },
        {
          "anchor": "Payment-Request-API",
          "level": 3,
          "text": "Payment Request API",
          "type": "heading"
        },
        {
          "anchor": "New-Features",
          "level": 4,
          "text": "New Features",
          "type": "heading"
        },
        {
          "items": [
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Added support for Apple Pay on the Web to ",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.documentation/documentation/WebKit/WKWebView",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": ". Note that using script injection APIs, such as ",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.documentation/documentation/WebKit/WKUserScript",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": " or ",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.documentation/documentation/WebKit/WKWebView/evaluateJavaScript(_:completionHandler:)",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": " disables Apple Pay for that view.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            }
          ],
          "type": "unorderedList"
        },
        {
          "anchor": "Media",
          "level": 3,
          "text": "Media",
          "type": "heading"
        },
        {
          "anchor": "New-Features",
          "level": 4,
          "text": "New Features",
          "type": "heading"
        },
        {
          "items": [
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Added support for the ",
                      "type": "text"
                    },
                    {
                      "code": "decodingInfo()",
                      "type": "codeVoice"
                    },
                    {
                      "text": " method of the Media Capabilities API for checking supported codecs, efficiently supported codecs, and optional codec features including alpha.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Added the ability to Safari for macOS to share your screen with others using only web technologies. Plug-ins are no longer required.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Updated Safari for iPad to support Media Source Extensions.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Added support for the ",
                      "type": "text"
                    },
                    {
                      "code": "navigator.mediaDevices",
                      "type": "codeVoice"
                    },
                    {
                      "text": " property of the Media Capture and Streams API to ",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.documentation/documentation/SafariServices/SFSafariViewController",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": ".",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            }
          ],
          "type": "unorderedList"
        },
        {
          "anchor": "Resolved-Issues",
          "level": 4,
          "text": "Resolved Issues",
          "type": "heading"
        },
        {
          "items": [
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Transparency in video with an alpha channel now works correctly for all supported video formats.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            }
          ],
          "type": "unorderedList"
        },
        {
          "anchor": "Safari-App-Extension-API",
          "level": 3,
          "text": "Safari App Extension API",
          "type": "heading"
        },
        {
          "anchor": "New-Features",
          "level": 4,
          "text": "New Features",
          "type": "heading"
        },
        {
          "items": [
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Added an API for page navigation notifications.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Added support for associated Safari App Extensions receiving blocked content notifications from Content Blocker Safari Extensions.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            }
          ],
          "type": "unorderedList"
        },
        {
          "anchor": "Web-Inspector-and-Tools",
          "level": 3,
          "text": "Web Inspector and Tools",
          "type": "heading"
        },
        {
          "anchor": "New-Features",
          "level": 4,
          "text": "New Features",
          "type": "heading"
        },
        {
          "items": [
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Added Safari WebDriver to iOS.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Added importing and exporting of recorded timeline data.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Added the CPU Usage Timeline for analyzing and improving the power efficiency of websites.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Added the Audit tab for running tests against web content including a built-in accessibility audit, importing and exporting results, and creating custom audits.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Added the Changes sidebar in the Elements tab to track CSS changes in the Styles sidebar.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Added the Device Settings menu to override developer-related Safari settings when Web Inspector is connected to an iOS device.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Added a Security tab to the resources view of the Network tab to review certificates and TLS settings.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Increased the performance of Web Inspector for large sites.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            }
          ],
          "type": "unorderedList"
        },
        {
          "anchor": "Removed-Features",
          "level": 4,
          "text": "Removed Features",
          "type": "heading"
        },
        {
          "items": [
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Removed support for WebSQL.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Removed support for Legacy Safari Extensions.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Disabled ",
                      "type": "text"
                    },
                    {
                      "code": "-webkit-overflow-scrolling: touch ",
                      "type": "codeVoice"
                    },
                    {
                      "text": "on iPad. All frames and scrollable overflow areas now use accelerated one-finger scrolling without changing stacking.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Disabled frame flattening on iOS. Frames now render in the same way as a desktop browser.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            }
          ],
          "type": "unorderedList"
        },
        {
          "anchor": "AuthenticationServices-Framework",
          "level": 3,
          "text": "AuthenticationServices Framework",
          "type": "heading"
        },
        {
          "anchor": "New-Features",
          "level": 4,
          "text": "New Features",
          "type": "heading"
        },
        {
          "items": [
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Added ",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.documentation/documentation/AuthenticationServices/ASAuthorizationController",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": " to implement Sign In with Apple and to use a system-provided sign-in account picker for accounts stored in iCloud Keychain.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Added ",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.documentation/documentation/AuthenticationServices/ASWebAuthenticationSession",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": " to the SDK for macOS.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Added support for using web browsers other than Safari to ",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.documentation/documentation/AuthenticationServices/ASWebAuthenticationSession",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": " on macOS. For more information, see ",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.documentation/documentation/AuthenticationServices/ASWebAuthenticationSessionWebBrowserSessionManager",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": ".",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            }
          ],
          "type": "unorderedList"
        },
        {
          "anchor": "WebKit-Framework",
          "level": 3,
          "text": "WebKit Framework",
          "type": "heading"
        },
        {
          "anchor": "New-Features",
          "level": 4,
          "text": "New Features",
          "type": "heading"
        },
        {
          "items": [
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Added API to control desktop and mobile content modes.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            }
          ],
          "type": "unorderedList"
        },
        {
          "anchor": "JavaScriptCore-Framework",
          "level": 3,
          "text": "JavaScriptCore Framework",
          "type": "heading"
        },
        {
          "anchor": "New-Features",
          "level": 4,
          "text": "New Features",
          "type": "heading"
        },
        {
          "items": [
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Added an API for loading ES6 modules.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            }
          ],
          "type": "unorderedList"
        },
        {
          "anchor": "LinkPresentation-Framework",
          "level": 3,
          "text": "LinkPresentation Framework",
          "type": "heading"
        },
        {
          "anchor": "New-Features",
          "level": 4,
          "text": "New Features",
          "type": "heading"
        },
        {
          "items": [
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Added LinkPresentation to the SDKs, enabling presentation of web links and better share sheet integration.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            }
          ],
          "type": "unorderedList"
        },
        {
          "anchor": "Mac-Catalyst",
          "level": 3,
          "text": "Mac Catalyst",
          "type": "heading"
        },
        {
          "anchor": "Differences-From-iOS",
          "level": 4,
          "text": "Differences From iOS",
          "type": "heading"
        },
        {
          "items": [
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "identifier": "doc://com.apple.documentation/documentation/SafariServices/SFSafariViewController",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": " opens the URL in the user’s web browser and immediately calls ",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.documentation/documentation/SafariServices/SFSafariViewControllerDelegate/safariViewControllerDidFinish(_:)",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": ".",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            }
          ],
          "type": "unorderedList"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.Safari-Release-Notes/documentation/Safari-Release-Notes/safari-13_1-release_notes": {
      "abstract": [
        {
          "text": "Released March 24, 2020 — Version 13.1 (15609.1.20)",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.Safari-Release-Notes/documentation/Safari-Release-Notes/safari-13_1-release_notes",
      "kind": "article",
      "role": "article",
      "title": "Safari 13.1 Release Notes",
      "type": "topic",
      "url": "/documentation/safari-release-notes/safari-13_1-release_notes"
    },
    "doc://com.apple.Safari-Release-Notes/documentation/safari-release-notes": {
      "abstract": [
        {
          "text": "Learn about changes for Safari for iOS and macOS, Web Inspector, WebKit view for iOS and macOS, and Safari view for iOS.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.Safari-Release-Notes/documentation/safari-release-notes",
      "kind": "article",
      "role": "collection",
      "title": "Safari Release Notes",
      "type": "topic",
      "url": "/documentation/safari-release-notes"
    },
    "doc://com.apple.documentation/documentation/AuthenticationServices/ASAuthorizationController": {
      "abstract": [
        {
          "text": "A controller that manages authorization requests that a provider creates.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ASAuthorizationController"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/AuthenticationServices/ASAuthorizationController",
      "kind": "symbol",
      "role": "symbol",
      "title": "ASAuthorizationController",
      "type": "topic",
      "url": "/documentation/AuthenticationServices/ASAuthorizationController"
    },
    "doc://com.apple.documentation/documentation/AuthenticationServices/ASWebAuthenticationSession": {
      "abstract": [
        {
          "text": "A session that an app uses to authenticate a user through a web service.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ASWebAuthenticationSession"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/AuthenticationServices/ASWebAuthenticationSession",
      "kind": "symbol",
      "role": "symbol",
      "title": "ASWebAuthenticationSession",
      "type": "topic",
      "url": "/documentation/AuthenticationServices/ASWebAuthenticationSession"
    },
    "doc://com.apple.documentation/documentation/AuthenticationServices/ASWebAuthenticationSessionWebBrowserSessionManager": {
      "abstract": [
        {
          "text": "A session manager that mediates sharing data between an app and a web browser.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ASWebAuthenticationSessionWebBrowserSessionManager"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/AuthenticationServices/ASWebAuthenticationSessionWebBrowserSessionManager",
      "kind": "symbol",
      "role": "symbol",
      "title": "ASWebAuthenticationSessionWebBrowserSessionManager",
      "type": "topic",
      "url": "/documentation/AuthenticationServices/ASWebAuthenticationSessionWebBrowserSessionManager"
    },
    "doc://com.apple.documentation/documentation/SafariServices/SFSafariViewController": {
      "abstract": [
        {
          "text": "An object that provides a visible standard interface for browsing the web.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@"
        },
        {
          "kind": "attribute",
          "preciseIdentifier": "s:ScM",
          "text": "MainActor"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SFSafariViewController"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/SafariServices/SFSafariViewController",
      "kind": "symbol",
      "role": "symbol",
      "title": "SFSafariViewController",
      "type": "topic",
      "url": "/documentation/SafariServices/SFSafariViewController"
    },
    "doc://com.apple.documentation/documentation/SafariServices/SFSafariViewControllerDelegate/safariViewControllerDidFinish(_:)": {
      "abstract": [
        {
          "text": "Tells the delegate that the user dismissed the view.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "optional"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "safariViewControllerDidFinish"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "_"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "internalParam",
          "text": "controller"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)SFSafariViewController",
          "text": "SFSafariViewController"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/SafariServices/SFSafariViewControllerDelegate/safariViewControllerDidFinish(_:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "safariViewControllerDidFinish(_:)",
      "type": "topic",
      "url": "/documentation/SafariServices/SFSafariViewControllerDelegate/safariViewControllerDidFinish(_:)"
    },
    "doc://com.apple.documentation/documentation/WebKit/WKUserScript": {
      "abstract": [
        {
          "text": "A script that the web view injects into a webpage.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@"
        },
        {
          "kind": "attribute",
          "preciseIdentifier": "s:ScM",
          "text": "MainActor"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "WKUserScript"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/WebKit/WKUserScript",
      "kind": "symbol",
      "role": "symbol",
      "title": "WKUserScript",
      "type": "topic",
      "url": "/documentation/WebKit/WKUserScript"
    },
    "doc://com.apple.documentation/documentation/WebKit/WKWebView": {
      "abstract": [
        {
          "text": "An object that displays interactive web content, such as for an in-app browser.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@"
        },
        {
          "kind": "attribute",
          "preciseIdentifier": "s:ScM",
          "text": "MainActor"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "WKWebView"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/WebKit/WKWebView",
      "kind": "symbol",
      "role": "symbol",
      "title": "WKWebView",
      "type": "topic",
      "url": "/documentation/WebKit/WKWebView"
    },
    "doc://com.apple.documentation/documentation/WebKit/WKWebView/evaluateJavaScript(_:completionHandler:)": {
      "abstract": [
        {
          "text": "Evaluates the specified JavaScript string.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@"
        },
        {
          "kind": "attribute",
          "preciseIdentifier": "s:ScM",
          "text": "MainActor"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "evaluateJavaScript"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "_"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "internalParam",
          "text": "javaScriptString"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "completionHandler"
        },
        {
          "kind": "text",
          "text": ": (@"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:ScM",
          "text": "MainActor"
        },
        {
          "kind": "text",
          "text": " ("
        },
        {
          "kind": "keyword",
          "text": "Any"
        },
        {
          "kind": "text",
          "text": "?, (any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5ErrorP",
          "text": "Error"
        },
        {
          "kind": "text",
          "text": ")?) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s4Voida",
          "text": "Void"
        },
        {
          "kind": "text",
          "text": ")? = nil)"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/WebKit/WKWebView/evaluateJavaScript(_:completionHandler:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "evaluateJavaScript(_:completionHandler:)",
      "type": "topic",
      "url": "/documentation/WebKit/WKWebView/evaluateJavaScript(_:completionHandler:)"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.documentation/documentation/webkitjs/devicemotionevent": {
      "abstract": [
        {
          "text": "An instance of `DeviceMotionEvent` is created when significant change in motion occurs. The event object encapsulates the measurements of the interval, rotation rate, and acceleration of a device. ",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/webkitjs/devicemotionevent",
      "kind": "symbol",
      "role": "symbol",
      "title": "DeviceMotionEvent",
      "type": "topic",
      "url": "/documentation/webkitjs/devicemotionevent"
    },
    "doc://com.apple.documentation/documentation/webkitjs/deviceorientationevent": {
      "abstract": [
        {
          "text": "Instances of the `DeviceOrientationEvent` class are fired only when the device has a gyroscope and while the user is changing the orientation. The `DeviceOrientationEvent` class encapsulates the angles of rotation in degrees and heading. ",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/webkitjs/deviceorientationevent",
      "kind": "symbol",
      "role": "symbol",
      "title": "DeviceOrientationEvent",
      "type": "topic",
      "url": "/documentation/webkitjs/deviceorientationevent"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Version-13",
      "generated": true,
      "identifiers": [
        "doc://com.apple.Safari-Release-Notes/documentation/Safari-Release-Notes/safari-13_1-release_notes"
      ],
      "title": "Version 13"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1WebKit~1WKWebView/fragments",
          "value": [
            {
              "kind": "keyword",
              "text": "@interface"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "WKWebView"
            },
            {
              "kind": "text",
              "text": " : "
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)NSView",
              "text": "NSView"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1AuthenticationServices~1ASWebAuthenticationSessionWebBrowserSessionManager/fragments",
          "value": [
            {
              "kind": "keyword",
              "text": "@interface"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "ASWebAuthenticationSessionWebBrowserSessionManager"
            },
            {
              "kind": "text",
              "text": " : "
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)NSObject",
              "text": "NSObject"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1WebKit~1WKWebView~1evaluateJavaScript(_:completionHandler:)/title",
          "value": "evaluateJavaScript:completionHandler:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1WebKit~1WKWebView~1evaluateJavaScript(_:completionHandler:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- ("
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:v",
              "text": "void"
            },
            {
              "kind": "text",
              "text": ") "
            },
            {
              "kind": "identifier",
              "text": "evaluateJavaScript:"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)NSString",
              "text": "NSString"
            },
            {
              "kind": "text",
              "text": " *) "
            },
            {
              "kind": "internalParam",
              "text": "javaScriptString"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "completionHandler:"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:BFv(#*Qo#*$objc(cs)NSError)",
              "text": "void (^)(id, NSError *)"
            },
            {
              "kind": "text",
              "text": ") "
            },
            {
              "kind": "internalParam",
              "text": "completionHandler"
            },
            {
              "kind": "text",
              "text": ";"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1WebKit~1WKUserScript/fragments",
          "value": [
            {
              "kind": "keyword",
              "text": "@interface"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "WKUserScript"
            },
            {
              "kind": "text",
              "text": " : "
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)NSObject",
              "text": "NSObject"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1SafariServices~1SFSafariViewController/fragments",
          "value": [
            {
              "kind": "keyword",
              "text": "@interface"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "SFSafariViewController"
            },
            {
              "kind": "text",
              "text": " : "
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)UIViewController",
              "text": "UIViewController"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1AuthenticationServices~1ASAuthorizationController/fragments",
          "value": [
            {
              "kind": "keyword",
              "text": "@interface"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "ASAuthorizationController"
            },
            {
              "kind": "text",
              "text": " : "
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)NSObject",
              "text": "NSObject"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1AuthenticationServices~1ASWebAuthenticationSession/fragments",
          "value": [
            {
              "kind": "keyword",
              "text": "@interface"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "ASWebAuthenticationSession"
            },
            {
              "kind": "text",
              "text": " : "
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)NSObject",
              "text": "NSObject"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1SafariServices~1SFSafariViewControllerDelegate~1safariViewControllerDidFinish(_:)/title",
          "value": "safariViewControllerDidFinish:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1SafariServices~1SFSafariViewControllerDelegate~1safariViewControllerDidFinish(_:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- ("
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:v",
              "text": "void"
            },
            {
              "kind": "text",
              "text": ") "
            },
            {
              "kind": "identifier",
              "text": "safariViewControllerDidFinish:"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)SFSafariViewController",
              "text": "SFSafariViewController"
            },
            {
              "kind": "text",
              "text": " *) "
            },
            {
              "kind": "internalParam",
              "text": "controller"
            },
            {
              "kind": "text",
              "text": ";"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
