{
  "abstract": [
    {
      "text": "A Boolean value that determines whether the content view preserves the layout margins that it inherits from its superview on the horizontal or vertical axes.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.uikit/documentation/UIKit",
        "doc://com.apple.uikit/documentation/UIKit/UIListContentConfiguration-swift.struct"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.uikit/documentation/UIKit/UIListContentConfiguration-swift.struct/axesPreservingSuperviewLayoutMargins"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "s:5UIKit26UIListContentConfigurationV36axesPreservingSuperviewLayoutMarginsSo6UIAxisVvp",
    "fragments": [
      {
        "kind": "keyword",
        "text": "var"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "axesPreservingSuperviewLayoutMargins"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@E@UIAxis",
        "text": "UIAxis"
      }
    ],
    "modules": [
      {
        "name": "UIKit"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "14.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "14.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "14.0",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Instance Property",
    "symbolKind": "property",
    "title": "axesPreservingSuperviewLayoutMargins"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "tvOS",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "var"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "axesPreservingSuperviewLayoutMargins"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.uikit/documentation/UIKit/UIAxis",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@E@UIAxis",
              "text": "UIAxis"
            },
            {
              "kind": "text",
              "text": " { "
            },
            {
              "kind": "keyword",
              "text": "get"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "keyword",
              "text": "set"
            },
            {
              "kind": "text",
              "text": " }"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "By default, the content view preserves the layout margins of its superview on ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.uikit/documentation/UIKit/UIAxis/both",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " axes.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.uikit/documentation/UIKit": {
      "abstract": [
        {
          "text": "Construct and manage a graphical, event-driven user interface for your iOS, iPadOS, or tvOS app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit",
      "kind": "symbol",
      "role": "collection",
      "title": "UIKit",
      "type": "topic",
      "url": "/documentation/uikit"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIAxis": {
      "abstract": [
        {
          "text": "A structure that specifies the layout axes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UIAxis"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIAxis",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIAxis"
        }
      ],
      "role": "symbol",
      "title": "UIAxis",
      "type": "topic",
      "url": "/documentation/uikit/uiaxis"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIAxis/both": {
      "abstract": [
        {
          "text": "A value that represents both axes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "both"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@UIAxis",
          "text": "UIAxis"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIAxis/both",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIAxisBoth"
        }
      ],
      "role": "symbol",
      "title": "both",
      "type": "topic",
      "url": "/documentation/uikit/uiaxis/both"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIListContentConfiguration-swift.struct": {
      "abstract": [
        {
          "text": "A content configuration for a list-based content view.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UIListContentConfiguration"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIListContentConfiguration-swift.struct",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIListContentConfiguration"
        }
      ],
      "role": "symbol",
      "title": "UIListContentConfiguration",
      "type": "topic",
      "url": "/documentation/uikit/uilistcontentconfiguration-swift.struct"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIListContentConfiguration-swift.struct/axesPreservingSuperviewLayoutMargins": {
      "abstract": [
        {
          "text": "A Boolean value that determines whether the content view preserves the layout margins that it inherits from its superview on the horizontal or vertical axes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "axesPreservingSuperviewLayoutMargins"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@UIAxis",
          "text": "UIAxis"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIListContentConfiguration-swift.struct/axesPreservingSuperviewLayoutMargins",
      "kind": "symbol",
      "role": "symbol",
      "title": "axesPreservingSuperviewLayoutMargins",
      "type": "topic",
      "url": "/documentation/uikit/uilistcontentconfiguration-swift.struct/axespreservingsuperviewlayoutmargins"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIListContentConfiguration-swift.struct/directionalLayoutMargins": {
      "abstract": [
        {
          "text": "The margins between the content and the edges of the content view.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "directionalLayoutMargins"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@NSDirectionalEdgeInsets",
          "text": "NSDirectionalEdgeInsets"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIListContentConfiguration-swift.struct/directionalLayoutMargins",
      "kind": "symbol",
      "role": "symbol",
      "title": "directionalLayoutMargins",
      "type": "topic",
      "url": "/documentation/uikit/uilistcontentconfiguration-swift.struct/directionallayoutmargins"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIListContentConfiguration-swift.struct/imageToTextPadding": {
      "abstract": [
        {
          "text": "The padding between the image and text.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "imageToTextPadding"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:14CoreFoundation7CGFloatV",
          "text": "CGFloat"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIListContentConfiguration-swift.struct/imageToTextPadding",
      "kind": "symbol",
      "role": "symbol",
      "title": "imageToTextPadding",
      "type": "topic",
      "url": "/documentation/uikit/uilistcontentconfiguration-swift.struct/imagetotextpadding"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIListContentConfiguration-swift.struct/prefersSideBySideTextAndSecondaryText": {
      "abstract": [
        {
          "text": "A Boolean value that determines whether the configuration positions the text and secondary text side by side.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "prefersSideBySideTextAndSecondaryText"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIListContentConfiguration-swift.struct/prefersSideBySideTextAndSecondaryText",
      "kind": "symbol",
      "role": "symbol",
      "title": "prefersSideBySideTextAndSecondaryText",
      "type": "topic",
      "url": "/documentation/uikit/uilistcontentconfiguration-swift.struct/preferssidebysidetextandsecondarytext"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIListContentConfiguration-swift.struct/textToSecondaryTextHorizontalPadding": {
      "abstract": [
        {
          "text": "The minimum horizontal padding between the text and secondary text.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "textToSecondaryTextHorizontalPadding"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:14CoreFoundation7CGFloatV",
          "text": "CGFloat"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIListContentConfiguration-swift.struct/textToSecondaryTextHorizontalPadding",
      "kind": "symbol",
      "role": "symbol",
      "title": "textToSecondaryTextHorizontalPadding",
      "type": "topic",
      "url": "/documentation/uikit/uilistcontentconfiguration-swift.struct/texttosecondarytexthorizontalpadding"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIListContentConfiguration-swift.struct/textToSecondaryTextVerticalPadding": {
      "abstract": [
        {
          "text": "The vertical padding between the text and secondary text.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "textToSecondaryTextVerticalPadding"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:14CoreFoundation7CGFloatV",
          "text": "CGFloat"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIListContentConfiguration-swift.struct/textToSecondaryTextVerticalPadding",
      "kind": "symbol",
      "role": "symbol",
      "title": "textToSecondaryTextVerticalPadding",
      "type": "topic",
      "url": "/documentation/uikit/uilistcontentconfiguration-swift.struct/texttosecondarytextverticalpadding"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Customizing-layout",
      "generated": true,
      "identifiers": [
        "doc://com.apple.uikit/documentation/UIKit/UIListContentConfiguration-swift.struct/directionalLayoutMargins",
        "doc://com.apple.uikit/documentation/UIKit/UIListContentConfiguration-swift.struct/prefersSideBySideTextAndSecondaryText",
        "doc://com.apple.uikit/documentation/UIKit/UIListContentConfiguration-swift.struct/imageToTextPadding",
        "doc://com.apple.uikit/documentation/UIKit/UIListContentConfiguration-swift.struct/textToSecondaryTextHorizontalPadding",
        "doc://com.apple.uikit/documentation/UIKit/UIListContentConfiguration-swift.struct/textToSecondaryTextVerticalPadding"
      ],
      "title": "Customizing layout"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIAxis/title",
          "value": "UIAxis"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIAxis/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIAxis"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIAxis/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UIAxis"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIAxis~1both/title",
          "value": "UIAxisBoth"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIAxis~1both/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIAxisBoth"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/uikit/uilistcontentconfiguration-swift.struct/axespreservingsuperviewlayoutmargins"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    }
  ]
}
