{
  "abstract": [
    {
      "text": "Returns a fixed spatial experience configured for the specified sound stage size.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.avfoundation/documentation/AVFoundation",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVAudioSessionSpatialExperience"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.avfoundation/documentation/AVFoundation/AVAudioSessionSpatialExperience/fixed(soundStageSize:)"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "conformance": {
      "availabilityPrefix": [
        {
          "text": "Available when",
          "type": "text"
        }
      ],
      "conformancePrefix": [
        {
          "text": "Conforms when",
          "type": "text"
        }
      ],
      "constraints": [
        {
          "code": "Self",
          "type": "codeVoice"
        },
        {
          "text": " is ",
          "type": "text"
        },
        {
          "code": "AVAudioSession.FixedSpatialExperience",
          "type": "codeVoice"
        },
        {
          "text": ".",
          "type": "text"
        }
      ]
    },
    "extendedModule": "AVFoundation",
    "externalID": "s:12AVFoundation31AVAudioSessionSpatialExperiencePAASo0bC0CAAE05FixeddE0VRszrlE5fixed14soundStageSizeAGSo0bc5SoundiJ0V_tFZ",
    "fragments": [
      {
        "kind": "keyword",
        "text": "static"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "keyword",
        "text": "func"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "fixed"
      },
      {
        "kind": "text",
        "text": "("
      },
      {
        "kind": "externalParam",
        "text": "soundStageSize"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:objc(cs)AVAudioSession",
        "text": "AVAudioSession"
      },
      {
        "kind": "text",
        "text": "."
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@E@AVAudioSessionSoundStageSize",
        "text": "SoundStageSize"
      },
      {
        "kind": "text",
        "text": ") -> "
      },
      {
        "kind": "typeIdentifier",
        "text": "Self"
      }
    ],
    "modules": [
      {
        "name": "AVFoundation"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Type Method",
    "symbolKind": "method",
    "title": "fixed(soundStageSize:)"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "static"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "keyword",
              "text": "func"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "fixed"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "kind": "externalParam",
              "text": "soundStageSize"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)AVAudioSession",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)AVAudioSession",
              "text": "AVAudioSession"
            },
            {
              "kind": "text",
              "text": "."
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/c:@E@AVAudioSessionSoundStageSize",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@E@AVAudioSessionSoundStageSize",
              "text": "SoundStageSize"
            },
            {
              "kind": "text",
              "text": ") -> "
            },
            {
              "kind": "typeIdentifier",
              "text": "Self"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "kind": "parameters",
      "parameters": [
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "The size of the sound stage.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "soundStageSize"
        }
      ]
    },
    {
      "content": [
        {
          "anchor": "return-value",
          "level": 2,
          "text": "Return Value",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "A new spatial experience.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.avfoundation/documentation/AVFoundation": {
      "abstract": [
        {
          "text": "Work with audiovisual assets, control device cameras, process audio, and configure system audio interactions.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation",
      "kind": "symbol",
      "role": "collection",
      "title": "AVFoundation",
      "type": "topic",
      "url": "/documentation/avfoundation"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVAudioSessionSpatialExperience": {
      "abstract": [
        {
          "text": "A protocol that defines types of spatial audio experiences that the system supports.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AVAudioSessionSpatialExperience"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVAudioSessionSpatialExperience",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVAudioSessionSpatialExperience"
        }
      ],
      "role": "symbol",
      "title": "AVAudioSessionSpatialExperience",
      "type": "topic",
      "url": "/documentation/avfoundation/avaudiosessionspatialexperience"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVAudioSessionSpatialExperience/bypassed": {
      "abstract": [
        {
          "text": "A nonspatial experience.",
          "type": "text"
        }
      ],
      "conformance": {
        "availabilityPrefix": [
          {
            "text": "Available when",
            "type": "text"
          }
        ],
        "conformancePrefix": [
          {
            "text": "Conforms when",
            "type": "text"
          }
        ],
        "constraints": [
          {
            "code": "Self",
            "type": "codeVoice"
          },
          {
            "text": " is ",
            "type": "text"
          },
          {
            "code": "AVAudioSession.BypassedSpatialExperience",
            "type": "codeVoice"
          },
          {
            "text": ".",
            "type": "text"
          }
        ]
      },
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "bypassed"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)AVAudioSession",
          "text": "AVAudioSession"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:So14AVAudioSessionC12AVFoundationE25BypassedSpatialExperienceV",
          "text": "BypassedSpatialExperience"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVAudioSessionSpatialExperience/bypassed",
      "kind": "symbol",
      "role": "symbol",
      "title": "bypassed",
      "type": "topic",
      "url": "/documentation/avfoundation/avaudiosessionspatialexperience/bypassed"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVAudioSessionSpatialExperience/fixed(soundStageSize:)": {
      "abstract": [
        {
          "text": "Returns a fixed spatial experience configured for the specified sound stage size.",
          "type": "text"
        }
      ],
      "conformance": {
        "availabilityPrefix": [
          {
            "text": "Available when",
            "type": "text"
          }
        ],
        "conformancePrefix": [
          {
            "text": "Conforms when",
            "type": "text"
          }
        ],
        "constraints": [
          {
            "code": "Self",
            "type": "codeVoice"
          },
          {
            "text": " is ",
            "type": "text"
          },
          {
            "code": "AVAudioSession.FixedSpatialExperience",
            "type": "codeVoice"
          },
          {
            "text": ".",
            "type": "text"
          }
        ]
      },
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "fixed"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "soundStageSize"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)AVAudioSession",
          "text": "AVAudioSession"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@AVAudioSessionSoundStageSize",
          "text": "SoundStageSize"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "text": "Self"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVAudioSessionSpatialExperience/fixed(soundStageSize:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "fixed(soundStageSize:)",
      "type": "topic",
      "url": "/documentation/avfoundation/avaudiosessionspatialexperience/fixed(soundstagesize:)"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVAudioSessionSpatialExperience/headTracked(soundStageSize:anchoringStrategy:)": {
      "abstract": [
        {
          "text": "Returns a head-tracked spatial experience configured for the specified sound stage size and anchoring strategy.",
          "type": "text"
        }
      ],
      "conformance": {
        "availabilityPrefix": [
          {
            "text": "Available when",
            "type": "text"
          }
        ],
        "conformancePrefix": [
          {
            "text": "Conforms when",
            "type": "text"
          }
        ],
        "constraints": [
          {
            "code": "Self",
            "type": "codeVoice"
          },
          {
            "text": " is ",
            "type": "text"
          },
          {
            "code": "AVAudioSession.HeadTrackedSpatialExperience",
            "type": "codeVoice"
          },
          {
            "text": ".",
            "type": "text"
          }
        ]
      },
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "headTracked"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "soundStageSize"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)AVAudioSession",
          "text": "AVAudioSession"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@AVAudioSessionSoundStageSize",
          "text": "SoundStageSize"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "anchoringStrategy"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)AVAudioSession",
          "text": "AVAudioSession"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:So14AVAudioSessionC12AVFoundationE17AnchoringStrategyO",
          "text": "AnchoringStrategy"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "text": "Self"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVAudioSessionSpatialExperience/headTracked(soundStageSize:anchoringStrategy:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "headTracked(soundStageSize:anchoringStrategy:)",
      "type": "topic",
      "url": "/documentation/avfoundation/avaudiosessionspatialexperience/headtracked(soundstagesize:anchoringstrategy:)"
    },
    "doc://com.apple.documentation/documentation/AVFAudio/AVAudioSession/AnchoringStrategy": {
      "abstract": [
        {
          "text": "Constants that specify how to set the origin of audio in a head-tracked spatial experience.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AnchoringStrategy"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/AVFAudio/AVAudioSession/AnchoringStrategy",
      "kind": "symbol",
      "role": "symbol",
      "title": "AVAudioSession.AnchoringStrategy",
      "type": "topic",
      "url": "/documentation/AVFAudio/AVAudioSession/AnchoringStrategy"
    },
    "doc://com.apple.documentation/documentation/AVFAudio/AVAudioSession/SoundStageSize": {
      "abstract": [
        {
          "text": "Constants that specify the perceived size of sounds the audio session plays.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SoundStageSize"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/AVFAudio/AVAudioSession/SoundStageSize",
      "kind": "symbol",
      "role": "symbol",
      "title": "AVAudioSession.SoundStageSize",
      "type": "topic",
      "url": "/documentation/AVFAudio/AVAudioSession/SoundStageSize"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.externally.resolved.symbol/c:@E@AVAudioSessionSoundStageSize": {
      "abstract": [
        {
          "text": "Constants that specify the perceived size of sounds the audio session plays.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SoundStageSize"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:@E@AVAudioSessionSoundStageSize",
      "kind": "symbol",
      "role": "symbol",
      "title": "AVAudioSession.SoundStageSize",
      "type": "topic",
      "url": "/documentation/AVFAudio/AVAudioSession/SoundStageSize"
    },
    "doc://com.externally.resolved.symbol/c:objc(cs)AVAudioSession": {
      "abstract": [
        {
          "text": "An object that communicates to the system how you intend to use audio in your app.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AVAudioSession"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)AVAudioSession",
      "kind": "symbol",
      "role": "symbol",
      "title": "AVAudioSession",
      "type": "topic",
      "url": "/documentation/AVFAudio/AVAudioSession"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Specifying-the-experience",
      "generated": true,
      "identifiers": [
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVAudioSessionSpatialExperience/headTracked(soundStageSize:anchoringStrategy:)",
        "doc://com.apple.documentation/documentation/AVFAudio/AVAudioSession/SoundStageSize",
        "doc://com.apple.documentation/documentation/AVFAudio/AVAudioSession/AnchoringStrategy",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVAudioSessionSpatialExperience/bypassed"
      ],
      "title": "Specifying the experience"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:@E@AVAudioSessionSoundStageSize/title",
          "value": "AVAudioSessionSoundStageSize"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:@E@AVAudioSessionSoundStageSize/fragments",
          "value": [
            {
              "kind": "keyword",
              "text": "enum"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "AVAudioSessionSoundStageSize"
            },
            {
              "kind": "text",
              "text": " : "
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@NSInteger",
              "text": "NSInteger"
            },
            {
              "kind": "text",
              "text": ";"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1AVFAudio~1AVAudioSession~1SoundStageSize/title",
          "value": "AVAudioSessionSoundStageSize"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1AVFAudio~1AVAudioSession~1SoundStageSize/fragments",
          "value": [
            {
              "kind": "keyword",
              "text": "enum"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "AVAudioSessionSoundStageSize"
            },
            {
              "kind": "text",
              "text": " : "
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@NSInteger",
              "text": "NSInteger"
            },
            {
              "kind": "text",
              "text": ";"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:objc(cs)AVAudioSession/fragments",
          "value": [
            {
              "kind": "keyword",
              "text": "@interface"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "AVAudioSession"
            },
            {
              "kind": "text",
              "text": " : "
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)NSObject",
              "text": "NSObject"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/avfoundation/avaudiosessionspatialexperience/fixed(soundstagesize:)"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    }
  ]
}
