{
  "abstract": [
    {
      "text": "A Boolean value that indicates if the sample has an HEVC temporal sublayer access (TSA) picture.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.mediaextension/documentation/MediaExtension",
        "doc://com.apple.mediaextension/documentation/MediaExtension/MEHEVCDependencyInfo"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.mediaextension/documentation/MediaExtension/MEHEVCDependencyInfo/hasTemporalSubLayerAccess"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(cs)MEHEVCDependencyInfo(py)temporalSubLayerAccess",
    "fragments": [
      {
        "kind": "keyword",
        "text": "var"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "hasTemporalSubLayerAccess"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "s:Sb",
        "text": "Bool"
      }
    ],
    "modules": [
      {
        "name": "MediaExtension"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "temporalSubLayerAccess"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "14.0",
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Instance Property",
    "symbolKind": "property",
    "title": "hasTemporalSubLayerAccess"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "macOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "var"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "hasTemporalSubLayerAccess"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:Sb",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:Sb",
              "text": "Bool"
            },
            {
              "kind": "text",
              "text": " { "
            },
            {
              "kind": "keyword",
              "text": "get"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "keyword",
              "text": "set"
            },
            {
              "kind": "text",
              "text": " }"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "This value maps to the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/CoreMedia/kCMSampleAttachmentKey_HEVCTemporalSubLayerAccess",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " sample buffer attachment.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/CoreMedia/kCMSampleAttachmentKey_HEVCTemporalSubLayerAccess": {
      "abstract": [
        {
          "text": "An attachment that indicates a temporal sublayer access grouping.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMSampleAttachmentKey_HEVCTemporalSubLayerAccess"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/CoreMedia/kCMSampleAttachmentKey_HEVCTemporalSubLayerAccess",
      "kind": "symbol",
      "role": "symbol",
      "title": "kCMSampleAttachmentKey_HEVCTemporalSubLayerAccess",
      "type": "topic",
      "url": "/documentation/CoreMedia/kCMSampleAttachmentKey_HEVCTemporalSubLayerAccess"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.mediaextension/documentation/MediaExtension": {
      "abstract": [
        {
          "text": "This framework provides a means for developers to create format readers, video decoders, and RAW processors for media that the system doesn’t natively support.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.mediaextension/documentation/MediaExtension",
      "kind": "symbol",
      "role": "collection",
      "title": "MediaExtension",
      "type": "topic",
      "url": "/documentation/mediaextension"
    },
    "doc://com.apple.mediaextension/documentation/MediaExtension/MEHEVCDependencyInfo": {
      "abstract": [
        {
          "text": "An object that provides information about the HEVC dependency attributes of a sample.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MEHEVCDependencyInfo"
        }
      ],
      "identifier": "doc://com.apple.mediaextension/documentation/MediaExtension/MEHEVCDependencyInfo",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MEHEVCDependencyInfo"
        }
      ],
      "role": "symbol",
      "title": "MEHEVCDependencyInfo",
      "type": "topic",
      "url": "/documentation/mediaextension/mehevcdependencyinfo"
    },
    "doc://com.apple.mediaextension/documentation/MediaExtension/MEHEVCDependencyInfo/constraintIndicatorFlags": {
      "abstract": [
        {
          "text": "The HEVC constraint indicator flags (6 bytes), if available.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "constraintIndicatorFlags"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10Foundation4DataV",
          "text": "Data"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.mediaextension/documentation/MediaExtension/MEHEVCDependencyInfo/constraintIndicatorFlags",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "constraintIndicatorFlags"
        }
      ],
      "role": "symbol",
      "title": "constraintIndicatorFlags",
      "type": "topic",
      "url": "/documentation/mediaextension/mehevcdependencyinfo/constraintindicatorflags"
    },
    "doc://com.apple.mediaextension/documentation/MediaExtension/MEHEVCDependencyInfo/hasStepwiseTemporalSubLayerAccess": {
      "abstract": [
        {
          "text": "A Boolean value that indicates if the sample has an HEVC stepwise temporal sublayer access (STSA) picture.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "hasStepwiseTemporalSubLayerAccess"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.mediaextension/documentation/MediaExtension/MEHEVCDependencyInfo/hasStepwiseTemporalSubLayerAccess",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "stepwiseTemporalSubLayerAccess"
        }
      ],
      "role": "symbol",
      "title": "hasStepwiseTemporalSubLayerAccess",
      "type": "topic",
      "url": "/documentation/mediaextension/mehevcdependencyinfo/hasstepwisetemporalsublayeraccess"
    },
    "doc://com.apple.mediaextension/documentation/MediaExtension/MEHEVCDependencyInfo/hasTemporalSubLayerAccess": {
      "abstract": [
        {
          "text": "A Boolean value that indicates if the sample has an HEVC temporal sublayer access (TSA) picture.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "hasTemporalSubLayerAccess"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.mediaextension/documentation/MediaExtension/MEHEVCDependencyInfo/hasTemporalSubLayerAccess",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "temporalSubLayerAccess"
        }
      ],
      "role": "symbol",
      "title": "hasTemporalSubLayerAccess",
      "type": "topic",
      "url": "/documentation/mediaextension/mehevcdependencyinfo/hastemporalsublayeraccess"
    },
    "doc://com.apple.mediaextension/documentation/MediaExtension/MEHEVCDependencyInfo/levelIndex": {
      "abstract": [
        {
          "text": "The HEVC level index, if available.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "levelIndex"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int16V",
          "text": "Int16"
        }
      ],
      "identifier": "doc://com.apple.mediaextension/documentation/MediaExtension/MEHEVCDependencyInfo/levelIndex",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "levelIndex"
        }
      ],
      "role": "symbol",
      "title": "levelIndex",
      "type": "topic",
      "url": "/documentation/mediaextension/mehevcdependencyinfo/levelindex"
    },
    "doc://com.apple.mediaextension/documentation/MediaExtension/MEHEVCDependencyInfo/profileCompatibilityFlags": {
      "abstract": [
        {
          "text": "The HEVC profile compatibility flags (4 bytes), if available.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "profileCompatibilityFlags"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10Foundation4DataV",
          "text": "Data"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.mediaextension/documentation/MediaExtension/MEHEVCDependencyInfo/profileCompatibilityFlags",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "profileCompatibilityFlags"
        }
      ],
      "role": "symbol",
      "title": "profileCompatibilityFlags",
      "type": "topic",
      "url": "/documentation/mediaextension/mehevcdependencyinfo/profilecompatibilityflags"
    },
    "doc://com.apple.mediaextension/documentation/MediaExtension/MEHEVCDependencyInfo/profileIndex": {
      "abstract": [
        {
          "text": "The HEVC profile index, if available.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "profileIndex"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int16V",
          "text": "Int16"
        }
      ],
      "identifier": "doc://com.apple.mediaextension/documentation/MediaExtension/MEHEVCDependencyInfo/profileIndex",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "profileIndex"
        }
      ],
      "role": "symbol",
      "title": "profileIndex",
      "type": "topic",
      "url": "/documentation/mediaextension/mehevcdependencyinfo/profileindex"
    },
    "doc://com.apple.mediaextension/documentation/MediaExtension/MEHEVCDependencyInfo/profileSpace": {
      "abstract": [
        {
          "text": "The HEVC profile space, if available.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "profileSpace"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int16V",
          "text": "Int16"
        }
      ],
      "identifier": "doc://com.apple.mediaextension/documentation/MediaExtension/MEHEVCDependencyInfo/profileSpace",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "profileSpace"
        }
      ],
      "role": "symbol",
      "title": "profileSpace",
      "type": "topic",
      "url": "/documentation/mediaextension/mehevcdependencyinfo/profilespace"
    },
    "doc://com.apple.mediaextension/documentation/MediaExtension/MEHEVCDependencyInfo/syncSampleNALUnitType": {
      "abstract": [
        {
          "text": "The NAL unit type for HEVC sync sample groups.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "syncSampleNALUnitType"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int16V",
          "text": "Int16"
        }
      ],
      "identifier": "doc://com.apple.mediaextension/documentation/MediaExtension/MEHEVCDependencyInfo/syncSampleNALUnitType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "syncSampleNALUnitType"
        }
      ],
      "role": "symbol",
      "title": "syncSampleNALUnitType",
      "type": "topic",
      "url": "/documentation/mediaextension/mehevcdependencyinfo/syncsamplenalunittype"
    },
    "doc://com.apple.mediaextension/documentation/MediaExtension/MEHEVCDependencyInfo/temporalLevel": {
      "abstract": [
        {
          "text": "The HEVC temporal level, if available.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "temporalLevel"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int16V",
          "text": "Int16"
        }
      ],
      "identifier": "doc://com.apple.mediaextension/documentation/MediaExtension/MEHEVCDependencyInfo/temporalLevel",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "temporalLevel"
        }
      ],
      "role": "symbol",
      "title": "temporalLevel",
      "type": "topic",
      "url": "/documentation/mediaextension/mehevcdependencyinfo/temporallevel"
    },
    "doc://com.apple.mediaextension/documentation/MediaExtension/MEHEVCDependencyInfo/tierFlag": {
      "abstract": [
        {
          "text": "The HEVC tier level flag, if available.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "tierFlag"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int16V",
          "text": "Int16"
        }
      ],
      "identifier": "doc://com.apple.mediaextension/documentation/MediaExtension/MEHEVCDependencyInfo/tierFlag",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "tierFlag"
        }
      ],
      "role": "symbol",
      "title": "tierFlag",
      "type": "topic",
      "url": "/documentation/mediaextension/mehevcdependencyinfo/tierflag"
    },
    "doc://com.externally.resolved.symbol/c:@T@BOOL": {
      "abstract": [
        {
          "text": "Type to represent a Boolean value.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:@T@BOOL",
      "kind": "symbol",
      "role": "symbol",
      "title": "BOOL",
      "type": "topic",
      "url": "/documentation/objectivec/bool"
    },
    "doc://com.externally.resolved.symbol/s:Sb": {
      "abstract": [
        {
          "text": "A value type whose instances are either `true` or `false`.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@frozen"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:Sb",
      "kind": "symbol",
      "role": "symbol",
      "title": "Bool",
      "type": "topic",
      "url": "/documentation/Swift/Bool"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Inspecting-the-HEVC-dependency-attributes-of-a-sample",
      "generated": true,
      "identifiers": [
        "doc://com.apple.mediaextension/documentation/MediaExtension/MEHEVCDependencyInfo/hasStepwiseTemporalSubLayerAccess",
        "doc://com.apple.mediaextension/documentation/MediaExtension/MEHEVCDependencyInfo/syncSampleNALUnitType",
        "doc://com.apple.mediaextension/documentation/MediaExtension/MEHEVCDependencyInfo/temporalLevel",
        "doc://com.apple.mediaextension/documentation/MediaExtension/MEHEVCDependencyInfo/profileSpace",
        "doc://com.apple.mediaextension/documentation/MediaExtension/MEHEVCDependencyInfo/tierFlag",
        "doc://com.apple.mediaextension/documentation/MediaExtension/MEHEVCDependencyInfo/profileIndex",
        "doc://com.apple.mediaextension/documentation/MediaExtension/MEHEVCDependencyInfo/profileCompatibilityFlags",
        "doc://com.apple.mediaextension/documentation/MediaExtension/MEHEVCDependencyInfo/constraintIndicatorFlags",
        "doc://com.apple.mediaextension/documentation/MediaExtension/MEHEVCDependencyInfo/levelIndex"
      ],
      "title": "Inspecting the HEVC dependency attributes of a sample"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "14.0",
              "name": "macOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Instance Property"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "temporalSubLayerAccess"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "property"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "temporalSubLayerAccess"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.mediaextension/documentation/MediaExtension",
                "doc://com.apple.mediaextension/documentation/MediaExtension/MEHEVCDependencyInfo"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Inspecting-the-HEVC-dependency-attributes-of-a-sample",
              "generated": true,
              "identifiers": [
                "doc://com.apple.mediaextension/documentation/MediaExtension/MEHEVCDependencyInfo/hasStepwiseTemporalSubLayerAccess",
                "doc://com.apple.mediaextension/documentation/MediaExtension/MEHEVCDependencyInfo/syncSampleNALUnitType",
                "doc://com.apple.mediaextension/documentation/MediaExtension/MEHEVCDependencyInfo/temporalLevel",
                "doc://com.apple.mediaextension/documentation/MediaExtension/MEHEVCDependencyInfo/profileSpace",
                "doc://com.apple.mediaextension/documentation/MediaExtension/MEHEVCDependencyInfo/tierFlag",
                "doc://com.apple.mediaextension/documentation/MediaExtension/MEHEVCDependencyInfo/profileIndex",
                "doc://com.apple.mediaextension/documentation/MediaExtension/MEHEVCDependencyInfo/profileCompatibilityFlags",
                "doc://com.apple.mediaextension/documentation/MediaExtension/MEHEVCDependencyInfo/constraintIndicatorFlags",
                "doc://com.apple.mediaextension/documentation/MediaExtension/MEHEVCDependencyInfo/levelIndex"
              ],
              "title": "Inspecting the HEVC dependency attributes of a sample"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "Mac Catalyst",
                  "macOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "@property"
                  },
                  {
                    "kind": "text",
                    "text": " ("
                  },
                  {
                    "kind": "keyword",
                    "text": "nonatomic"
                  },
                  {
                    "kind": "text",
                    "text": ", "
                  },
                  {
                    "kind": "keyword",
                    "text": "getter"
                  },
                  {
                    "kind": "text",
                    "text": "="
                  },
                  {
                    "kind": "identifier",
                    "text": "hasTemporalSubLayerAccess"
                  },
                  {
                    "kind": "text",
                    "text": ") "
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:@T@BOOL",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@BOOL",
                    "text": "BOOL"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "temporalSubLayerAccess"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaextension~1documentation~1MediaExtension~1MEHEVCDependencyInfo/title",
          "value": "MEHEVCDependencyInfo"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaextension~1documentation~1MediaExtension~1MEHEVCDependencyInfo/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MEHEVCDependencyInfo"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaextension~1documentation~1MediaExtension~1MEHEVCDependencyInfo/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MEHEVCDependencyInfo"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaextension~1documentation~1MediaExtension~1MEHEVCDependencyInfo~1profileSpace/title",
          "value": "profileSpace"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaextension~1documentation~1MediaExtension~1MEHEVCDependencyInfo~1profileSpace/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "profileSpace"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1CoreMedia~1kCMSampleAttachmentKey_HEVCTemporalSubLayerAccess/fragments",
          "value": [
            {
              "kind": "keyword",
              "text": "extern"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@CFStringRef",
              "text": "CFStringRef"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "keyword",
              "text": "const"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "kCMSampleAttachmentKey_HEVCTemporalSubLayerAccess"
            },
            {
              "kind": "text",
              "text": ";"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaextension~1documentation~1MediaExtension~1MEHEVCDependencyInfo~1constraintIndicatorFlags/title",
          "value": "constraintIndicatorFlags"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaextension~1documentation~1MediaExtension~1MEHEVCDependencyInfo~1constraintIndicatorFlags/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "constraintIndicatorFlags"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaextension~1documentation~1MediaExtension~1MEHEVCDependencyInfo~1profileCompatibilityFlags/title",
          "value": "profileCompatibilityFlags"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaextension~1documentation~1MediaExtension~1MEHEVCDependencyInfo~1profileCompatibilityFlags/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "profileCompatibilityFlags"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaextension~1documentation~1MediaExtension~1MEHEVCDependencyInfo~1hasTemporalSubLayerAccess/title",
          "value": "temporalSubLayerAccess"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaextension~1documentation~1MediaExtension~1MEHEVCDependencyInfo~1hasTemporalSubLayerAccess/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "temporalSubLayerAccess"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaextension~1documentation~1MediaExtension~1MEHEVCDependencyInfo~1levelIndex/title",
          "value": "levelIndex"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaextension~1documentation~1MediaExtension~1MEHEVCDependencyInfo~1levelIndex/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "levelIndex"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaextension~1documentation~1MediaExtension~1MEHEVCDependencyInfo~1profileIndex/title",
          "value": "profileIndex"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaextension~1documentation~1MediaExtension~1MEHEVCDependencyInfo~1profileIndex/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "profileIndex"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaextension~1documentation~1MediaExtension~1MEHEVCDependencyInfo~1syncSampleNALUnitType/title",
          "value": "syncSampleNALUnitType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaextension~1documentation~1MediaExtension~1MEHEVCDependencyInfo~1syncSampleNALUnitType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "syncSampleNALUnitType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaextension~1documentation~1MediaExtension~1MEHEVCDependencyInfo~1temporalLevel/title",
          "value": "temporalLevel"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaextension~1documentation~1MediaExtension~1MEHEVCDependencyInfo~1temporalLevel/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "temporalLevel"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaextension~1documentation~1MediaExtension~1MEHEVCDependencyInfo~1hasStepwiseTemporalSubLayerAccess/title",
          "value": "stepwiseTemporalSubLayerAccess"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaextension~1documentation~1MediaExtension~1MEHEVCDependencyInfo~1hasStepwiseTemporalSubLayerAccess/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "stepwiseTemporalSubLayerAccess"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaextension~1documentation~1MediaExtension~1MEHEVCDependencyInfo~1tierFlag/title",
          "value": "tierFlag"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaextension~1documentation~1MediaExtension~1MEHEVCDependencyInfo~1tierFlag/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "tierFlag"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/mediaextension/mehevcdependencyinfo/hastemporalsublayeraccess"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/mediaextension/mehevcdependencyinfo/hastemporalsublayeraccess"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
