{
  "abstract": [
    {
      "text": "The requested eSIM provisioning succeeded.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.coretelephony/documentation/CoreTelephony",
        "doc://com.apple.coretelephony/documentation/CoreTelephony/CTCellularPlanProvisioningAddPlanResult"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.coretelephony/documentation/CoreTelephony/CTCellularPlanProvisioningAddPlanResult/success"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@CTCellularPlanProvisioningAddPlanResult@CTCellularPlanProvisioningAddPlanResultSuccess",
    "fragments": [
      {
        "kind": "keyword",
        "text": "case"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "success"
      }
    ],
    "modules": [
      {
        "name": "Core Telephony"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "CTCellularPlanProvisioningAddPlanResultSuccess"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "12.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "12.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.1",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.10",
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Case",
    "symbolKind": "case",
    "title": "CTCellularPlanProvisioningAddPlanResult.success"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "case"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "success"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.coretelephony/documentation/CoreTelephony": {
      "abstract": [
        {
          "text": "Access information about a user’s cellular service provider, such as its unique identifier and whether the carrier allows VoIP.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.coretelephony/documentation/CoreTelephony",
      "kind": "symbol",
      "role": "collection",
      "title": "Core Telephony",
      "type": "topic",
      "url": "/documentation/coretelephony"
    },
    "doc://com.apple.coretelephony/documentation/CoreTelephony/CTCellularPlanProvisioningAddPlanResult": {
      "abstract": [
        {
          "text": "The result from attempting to provision an eSIM.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CTCellularPlanProvisioningAddPlanResult"
        }
      ],
      "identifier": "doc://com.apple.coretelephony/documentation/CoreTelephony/CTCellularPlanProvisioningAddPlanResult",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CTCellularPlanProvisioningAddPlanResult"
        }
      ],
      "role": "symbol",
      "title": "CTCellularPlanProvisioningAddPlanResult",
      "type": "topic",
      "url": "/documentation/coretelephony/ctcellularplanprovisioningaddplanresult"
    },
    "doc://com.apple.coretelephony/documentation/CoreTelephony/CTCellularPlanProvisioningAddPlanResult/cancel": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "cancel"
        }
      ],
      "identifier": "doc://com.apple.coretelephony/documentation/CoreTelephony/CTCellularPlanProvisioningAddPlanResult/cancel",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CTCellularPlanProvisioningAddPlanResultCancel"
        }
      ],
      "role": "symbol",
      "title": "CTCellularPlanProvisioningAddPlanResult.cancel",
      "type": "topic",
      "url": "/documentation/coretelephony/ctcellularplanprovisioningaddplanresult/cancel"
    },
    "doc://com.apple.coretelephony/documentation/CoreTelephony/CTCellularPlanProvisioningAddPlanResult/fail": {
      "abstract": [
        {
          "text": "The requested eSIM provisioning failed.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "fail"
        }
      ],
      "identifier": "doc://com.apple.coretelephony/documentation/CoreTelephony/CTCellularPlanProvisioningAddPlanResult/fail",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CTCellularPlanProvisioningAddPlanResultFail"
        }
      ],
      "role": "symbol",
      "title": "CTCellularPlanProvisioningAddPlanResult.fail",
      "type": "topic",
      "url": "/documentation/coretelephony/ctcellularplanprovisioningaddplanresult/fail"
    },
    "doc://com.apple.coretelephony/documentation/CoreTelephony/CTCellularPlanProvisioningAddPlanResult/success": {
      "abstract": [
        {
          "text": "The requested eSIM provisioning succeeded.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "success"
        }
      ],
      "identifier": "doc://com.apple.coretelephony/documentation/CoreTelephony/CTCellularPlanProvisioningAddPlanResult/success",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CTCellularPlanProvisioningAddPlanResultSuccess"
        }
      ],
      "role": "symbol",
      "title": "CTCellularPlanProvisioningAddPlanResult.success",
      "type": "topic",
      "url": "/documentation/coretelephony/ctcellularplanprovisioningaddplanresult/success"
    },
    "doc://com.apple.coretelephony/documentation/CoreTelephony/CTCellularPlanProvisioningAddPlanResult/unknown": {
      "abstract": [
        {
          "text": "The result of the requested eSIM provisioning is unknown.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "unknown"
        }
      ],
      "identifier": "doc://com.apple.coretelephony/documentation/CoreTelephony/CTCellularPlanProvisioningAddPlanResult/unknown",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CTCellularPlanProvisioningAddPlanResultUnknown"
        }
      ],
      "role": "symbol",
      "title": "CTCellularPlanProvisioningAddPlanResult.unknown",
      "type": "topic",
      "url": "/documentation/coretelephony/ctcellularplanprovisioningaddplanresult/unknown"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Results",
      "generated": true,
      "identifiers": [
        "doc://com.apple.coretelephony/documentation/CoreTelephony/CTCellularPlanProvisioningAddPlanResult/fail",
        "doc://com.apple.coretelephony/documentation/CoreTelephony/CTCellularPlanProvisioningAddPlanResult/unknown",
        "doc://com.apple.coretelephony/documentation/CoreTelephony/CTCellularPlanProvisioningAddPlanResult/cancel"
      ],
      "title": "Results"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "12.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "12.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.1",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.10",
              "name": "macOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration Case"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "CTCellularPlanProvisioningAddPlanResultSuccess"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "case"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CTCellularPlanProvisioningAddPlanResultSuccess"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.coretelephony/documentation/CoreTelephony",
                "doc://com.apple.coretelephony/documentation/CoreTelephony/CTCellularPlanProvisioningAddPlanResult"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Results",
              "generated": true,
              "identifiers": [
                "doc://com.apple.coretelephony/documentation/CoreTelephony/CTCellularPlanProvisioningAddPlanResult/fail",
                "doc://com.apple.coretelephony/documentation/CoreTelephony/CTCellularPlanProvisioningAddPlanResult/unknown",
                "doc://com.apple.coretelephony/documentation/CoreTelephony/CTCellularPlanProvisioningAddPlanResult/cancel"
              ],
              "title": "Results"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS"
                ],
                "tokens": [
                  {
                    "kind": "identifier",
                    "text": "CTCellularPlanProvisioningAddPlanResultSuccess"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretelephony~1documentation~1CoreTelephony~1CTCellularPlanProvisioningAddPlanResult~1cancel/title",
          "value": "CTCellularPlanProvisioningAddPlanResultCancel"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretelephony~1documentation~1CoreTelephony~1CTCellularPlanProvisioningAddPlanResult~1cancel/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CTCellularPlanProvisioningAddPlanResultCancel"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretelephony~1documentation~1CoreTelephony~1CTCellularPlanProvisioningAddPlanResult~1unknown/title",
          "value": "CTCellularPlanProvisioningAddPlanResultUnknown"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretelephony~1documentation~1CoreTelephony~1CTCellularPlanProvisioningAddPlanResult~1unknown/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CTCellularPlanProvisioningAddPlanResultUnknown"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretelephony~1documentation~1CoreTelephony~1CTCellularPlanProvisioningAddPlanResult/title",
          "value": "CTCellularPlanProvisioningAddPlanResult"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretelephony~1documentation~1CoreTelephony~1CTCellularPlanProvisioningAddPlanResult/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CTCellularPlanProvisioningAddPlanResult"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretelephony~1documentation~1CoreTelephony~1CTCellularPlanProvisioningAddPlanResult/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CTCellularPlanProvisioningAddPlanResult"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretelephony~1documentation~1CoreTelephony~1CTCellularPlanProvisioningAddPlanResult~1fail/title",
          "value": "CTCellularPlanProvisioningAddPlanResultFail"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretelephony~1documentation~1CoreTelephony~1CTCellularPlanProvisioningAddPlanResult~1fail/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CTCellularPlanProvisioningAddPlanResultFail"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretelephony~1documentation~1CoreTelephony~1CTCellularPlanProvisioningAddPlanResult~1success/title",
          "value": "CTCellularPlanProvisioningAddPlanResultSuccess"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretelephony~1documentation~1CoreTelephony~1CTCellularPlanProvisioningAddPlanResult~1success/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CTCellularPlanProvisioningAddPlanResultSuccess"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/coretelephony/ctcellularplanprovisioningaddplanresult/success"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/coretelephony/ctcellularplanprovisioningaddplanresult/success"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
