{
  "abstract": [
    {
      "text": "Options for playing animations loaded from a scene file, used with the ",
      "type": "text"
    },
    {
      "identifier": "doc://com.apple.scenekit/documentation/SceneKit/SCNSceneSource/LoadingOption/animationImportPolicy",
      "isActive": true,
      "type": "reference"
    },
    {
      "text": " key in options dictionaries.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.scenekit/documentation/SceneKit",
        "doc://com.apple.scenekit/documentation/SceneKit/SCNSceneSource"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.scenekit/documentation/SceneKit/SCNSceneSource/AnimationImportPolicy"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "extendedModule": "SceneKit",
    "externalID": "c:@T@SCNSceneSourceAnimationImportPolicy",
    "fragments": [
      {
        "kind": "keyword",
        "text": "struct"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "AnimationImportPolicy"
      }
    ],
    "modules": [
      {
        "name": "SceneKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "AnimationImportPolicy"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Structure",
    "symbolKind": "struct",
    "title": "SCNSceneSource.AnimationImportPolicy"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "struct"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "AnimationImportPolicy"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.scenekit/documentation/SceneKit": {
      "abstract": [
        {
          "text": "Create 3D games and add 3D content to apps using high-level scene descriptions, and easily add animations, physics simulation, particle effects, and realistic physically based rendering.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.scenekit/documentation/SceneKit",
      "kind": "symbol",
      "role": "collection",
      "title": "SceneKit",
      "type": "topic",
      "url": "/documentation/scenekit"
    },
    "doc://com.apple.scenekit/documentation/SceneKit/SCNSceneRenderer/sceneTime": {
      "abstract": [
        {
          "text": "The current scene time.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "sceneTime"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSTimeInterval",
          "text": "TimeInterval"
        }
      ],
      "identifier": "doc://com.apple.scenekit/documentation/SceneKit/SCNSceneRenderer/sceneTime",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "sceneTime"
        }
      ],
      "required": true,
      "role": "symbol",
      "title": "sceneTime",
      "type": "topic",
      "url": "/documentation/scenekit/scnscenerenderer/scenetime"
    },
    "doc://com.apple.scenekit/documentation/SceneKit/SCNSceneSource": {
      "abstract": [
        {
          "text": "An object that manages the data-reading tasks associated with loading scene contents from a file or data.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SCNSceneSource"
        }
      ],
      "identifier": "doc://com.apple.scenekit/documentation/SceneKit/SCNSceneSource",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SCNSceneSource"
        }
      ],
      "role": "symbol",
      "title": "SCNSceneSource",
      "type": "topic",
      "url": "/documentation/scenekit/scnscenesource"
    },
    "doc://com.apple.scenekit/documentation/SceneKit/SCNSceneSource/AnimationImportPolicy": {
      "abstract": [
        {
          "text": "Options for playing animations loaded from a scene file, used with the ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.scenekit/documentation/SceneKit/SCNSceneSource/LoadingOption/animationImportPolicy",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " key in options dictionaries.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AnimationImportPolicy"
        }
      ],
      "identifier": "doc://com.apple.scenekit/documentation/SceneKit/SCNSceneSource/AnimationImportPolicy",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AnimationImportPolicy"
        }
      ],
      "role": "symbol",
      "title": "SCNSceneSource.AnimationImportPolicy",
      "type": "topic",
      "url": "/documentation/scenekit/scnscenesource/animationimportpolicy"
    },
    "doc://com.apple.scenekit/documentation/SceneKit/SCNSceneSource/AnimationImportPolicy/doNotPlay": {
      "abstract": [
        {
          "text": "Animations are not loaded from the scene file.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "doNotPlay"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)SCNSceneSource",
          "text": "SCNSceneSource"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@SCNSceneSourceAnimationImportPolicy",
          "text": "AnimationImportPolicy"
        }
      ],
      "identifier": "doc://com.apple.scenekit/documentation/SceneKit/SCNSceneSource/AnimationImportPolicy/doNotPlay",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SCNSceneSourceAnimationImportPolicyDoNotPlay"
        }
      ],
      "role": "symbol",
      "title": "doNotPlay",
      "type": "topic",
      "url": "/documentation/scenekit/scnscenesource/animationimportpolicy/donotplay"
    },
    "doc://com.apple.scenekit/documentation/SceneKit/SCNSceneSource/AnimationImportPolicy/init(rawValue:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "rawValue"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.scenekit/documentation/SceneKit/SCNSceneSource/AnimationImportPolicy/init(rawValue:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "init(rawValue:)",
      "type": "topic",
      "url": "/documentation/scenekit/scnscenesource/animationimportpolicy/init(rawvalue:)"
    },
    "doc://com.apple.scenekit/documentation/SceneKit/SCNSceneSource/AnimationImportPolicy/play": {
      "abstract": [
        {
          "text": "Animations loaded from the scene file are immediately added to the scene and played once.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "play"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)SCNSceneSource",
          "text": "SCNSceneSource"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@SCNSceneSourceAnimationImportPolicy",
          "text": "AnimationImportPolicy"
        }
      ],
      "identifier": "doc://com.apple.scenekit/documentation/SceneKit/SCNSceneSource/AnimationImportPolicy/play",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SCNSceneSourceAnimationImportPolicyPlay"
        }
      ],
      "role": "symbol",
      "title": "play",
      "type": "topic",
      "url": "/documentation/scenekit/scnscenesource/animationimportpolicy/play"
    },
    "doc://com.apple.scenekit/documentation/SceneKit/SCNSceneSource/AnimationImportPolicy/playRepeatedly": {
      "abstract": [
        {
          "text": "Animations loaded from the scene file are immediately added to the scene and played repeatedly.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "playRepeatedly"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)SCNSceneSource",
          "text": "SCNSceneSource"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@SCNSceneSourceAnimationImportPolicy",
          "text": "AnimationImportPolicy"
        }
      ],
      "identifier": "doc://com.apple.scenekit/documentation/SceneKit/SCNSceneSource/AnimationImportPolicy/playRepeatedly",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SCNSceneSourceAnimationImportPolicyPlayRepeatedly"
        }
      ],
      "role": "symbol",
      "title": "playRepeatedly",
      "type": "topic",
      "url": "/documentation/scenekit/scnscenesource/animationimportpolicy/playrepeatedly"
    },
    "doc://com.apple.scenekit/documentation/SceneKit/SCNSceneSource/AnimationImportPolicy/playUsingSceneTimeBase": {
      "abstract": [
        {
          "text": "Animations loaded from the scene file are immediately added to the scene and played according to the scene’s ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.scenekit/documentation/SceneKit/SCNSceneRenderer/sceneTime",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " property.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "playUsingSceneTimeBase"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)SCNSceneSource",
          "text": "SCNSceneSource"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@SCNSceneSourceAnimationImportPolicy",
          "text": "AnimationImportPolicy"
        }
      ],
      "identifier": "doc://com.apple.scenekit/documentation/SceneKit/SCNSceneSource/AnimationImportPolicy/playUsingSceneTimeBase",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SCNSceneSourceAnimationImportPolicyPlayUsingSceneTimeBase"
        }
      ],
      "role": "symbol",
      "title": "playUsingSceneTimeBase",
      "type": "topic",
      "url": "/documentation/scenekit/scnscenesource/animationimportpolicy/playusingscenetimebase"
    },
    "doc://com.apple.scenekit/documentation/SceneKit/SCNSceneSource/LoadingOption/animationImportPolicy": {
      "abstract": [
        {
          "text": "An option for controlling the playback of animations in a scene file.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "animationImportPolicy"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)SCNSceneSource",
          "text": "SCNSceneSource"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@SCNSceneSourceLoadingOption",
          "text": "LoadingOption"
        }
      ],
      "identifier": "doc://com.apple.scenekit/documentation/SceneKit/SCNSceneSource/LoadingOption/animationImportPolicy",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SCNSceneSourceAnimationImportPolicyKey"
        }
      ],
      "role": "symbol",
      "title": "animationImportPolicy",
      "type": "topic",
      "url": "/documentation/scenekit/scnscenesource/loadingoption/animationimportpolicy"
    },
    "doc://com.apple.scenekit/documentation/SceneKit/SCNSceneSource/LoadingOption/assetDirectoryURLs": {
      "abstract": [
        {
          "text": "Locations to use for resolving relative URLs to external resources.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "assetDirectoryURLs"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)SCNSceneSource",
          "text": "SCNSceneSource"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@SCNSceneSourceLoadingOption",
          "text": "LoadingOption"
        }
      ],
      "identifier": "doc://com.apple.scenekit/documentation/SceneKit/SCNSceneSource/LoadingOption/assetDirectoryURLs",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SCNSceneSourceAssetDirectoryURLsKey"
        }
      ],
      "role": "symbol",
      "title": "assetDirectoryURLs",
      "type": "topic",
      "url": "/documentation/scenekit/scnscenesource/loadingoption/assetdirectoryurls"
    },
    "doc://com.apple.scenekit/documentation/SceneKit/SCNSceneSource/LoadingOption/checkConsistency": {
      "abstract": [
        {
          "text": "An option to validate scene files while loading.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "checkConsistency"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)SCNSceneSource",
          "text": "SCNSceneSource"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@SCNSceneSourceLoadingOption",
          "text": "LoadingOption"
        }
      ],
      "identifier": "doc://com.apple.scenekit/documentation/SceneKit/SCNSceneSource/LoadingOption/checkConsistency",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SCNSceneSourceCheckConsistencyKey"
        }
      ],
      "role": "symbol",
      "title": "checkConsistency",
      "type": "topic",
      "url": "/documentation/scenekit/scnscenesource/loadingoption/checkconsistency"
    },
    "doc://com.apple.scenekit/documentation/SceneKit/SCNSceneSource/LoadingOption/convertToYUp": {
      "abstract": [
        {
          "text": "An option for whether to transform assets loaded from the scene file for use in a coordinate system where the y-axis points up.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "convertToYUp"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)SCNSceneSource",
          "text": "SCNSceneSource"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@SCNSceneSourceLoadingOption",
          "text": "LoadingOption"
        }
      ],
      "identifier": "doc://com.apple.scenekit/documentation/SceneKit/SCNSceneSource/LoadingOption/convertToYUp",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SCNSceneSourceConvertToYUpKey"
        }
      ],
      "role": "symbol",
      "title": "convertToYUp",
      "type": "topic",
      "url": "/documentation/scenekit/scnscenesource/loadingoption/converttoyup"
    },
    "doc://com.apple.scenekit/documentation/SceneKit/SCNSceneSource/LoadingOption/convertUnitsToMeters": {
      "abstract": [
        {
          "text": "An option for whether to automatically scale the scene’s contents.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "convertUnitsToMeters"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)SCNSceneSource",
          "text": "SCNSceneSource"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@SCNSceneSourceLoadingOption",
          "text": "LoadingOption"
        }
      ],
      "identifier": "doc://com.apple.scenekit/documentation/SceneKit/SCNSceneSource/LoadingOption/convertUnitsToMeters",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SCNSceneSourceConvertUnitsToMetersKey"
        }
      ],
      "role": "symbol",
      "title": "convertUnitsToMeters",
      "type": "topic",
      "url": "/documentation/scenekit/scnscenesource/loadingoption/convertunitstometers"
    },
    "doc://com.apple.scenekit/documentation/SceneKit/SCNSceneSource/LoadingOption/createNormalsIfAbsent": {
      "abstract": [
        {
          "text": "An option for automatically generating surface normals if they are absent when loading geometry.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "createNormalsIfAbsent"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)SCNSceneSource",
          "text": "SCNSceneSource"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@SCNSceneSourceLoadingOption",
          "text": "LoadingOption"
        }
      ],
      "identifier": "doc://com.apple.scenekit/documentation/SceneKit/SCNSceneSource/LoadingOption/createNormalsIfAbsent",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SCNSceneSourceCreateNormalsIfAbsentKey"
        }
      ],
      "role": "symbol",
      "title": "createNormalsIfAbsent",
      "type": "topic",
      "url": "/documentation/scenekit/scnscenesource/loadingoption/createnormalsifabsent"
    },
    "doc://com.apple.scenekit/documentation/SceneKit/SCNSceneSource/LoadingOption/flattenScene": {
      "abstract": [
        {
          "text": "An option for automatically merging portions of a scene graph during loading.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "flattenScene"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)SCNSceneSource",
          "text": "SCNSceneSource"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@SCNSceneSourceLoadingOption",
          "text": "LoadingOption"
        }
      ],
      "identifier": "doc://com.apple.scenekit/documentation/SceneKit/SCNSceneSource/LoadingOption/flattenScene",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SCNSceneSourceFlattenSceneKey"
        }
      ],
      "role": "symbol",
      "title": "flattenScene",
      "type": "topic",
      "url": "/documentation/scenekit/scnscenesource/loadingoption/flattenscene"
    },
    "doc://com.apple.scenekit/documentation/SceneKit/SCNSceneSource/LoadingOption/overrideAssetURLs": {
      "abstract": [
        {
          "text": "An option to attempt loading external resources using their URLs as specified in a scene file.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "overrideAssetURLs"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)SCNSceneSource",
          "text": "SCNSceneSource"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@SCNSceneSourceLoadingOption",
          "text": "LoadingOption"
        }
      ],
      "identifier": "doc://com.apple.scenekit/documentation/SceneKit/SCNSceneSource/LoadingOption/overrideAssetURLs",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SCNSceneSourceOverrideAssetURLsKey"
        }
      ],
      "role": "symbol",
      "title": "overrideAssetURLs",
      "type": "topic",
      "url": "/documentation/scenekit/scnscenesource/loadingoption/overrideasseturls"
    },
    "doc://com.apple.scenekit/documentation/SceneKit/SCNSceneSource/LoadingOption/preserveOriginalTopology": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "preserveOriginalTopology"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)SCNSceneSource",
          "text": "SCNSceneSource"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@SCNSceneSourceLoadingOption",
          "text": "LoadingOption"
        }
      ],
      "identifier": "doc://com.apple.scenekit/documentation/SceneKit/SCNSceneSource/LoadingOption/preserveOriginalTopology",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SCNSceneSourceLoadingOptionPreserveOriginalTopology"
        }
      ],
      "role": "symbol",
      "title": "preserveOriginalTopology",
      "type": "topic",
      "url": "/documentation/scenekit/scnscenesource/loadingoption/preserveoriginaltopology"
    },
    "doc://com.apple.scenekit/documentation/SceneKit/SCNSceneSource/LoadingOption/strictConformance": {
      "abstract": [
        {
          "text": "An option to interpret scene files exactly as specified by the scene file format.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "strictConformance"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)SCNSceneSource",
          "text": "SCNSceneSource"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@SCNSceneSourceLoadingOption",
          "text": "LoadingOption"
        }
      ],
      "identifier": "doc://com.apple.scenekit/documentation/SceneKit/SCNSceneSource/LoadingOption/strictConformance",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SCNSceneSourceStrictConformanceKey"
        }
      ],
      "role": "symbol",
      "title": "strictConformance",
      "type": "topic",
      "url": "/documentation/scenekit/scnscenesource/loadingoption/strictconformance"
    },
    "doc://com.apple.scenekit/documentation/SceneKit/SCNSceneSource/LoadingOption/useSafeMode": {
      "abstract": [
        {
          "text": "An option to limit filesystem and network access for external resources referenced by a scene file.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "useSafeMode"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)SCNSceneSource",
          "text": "SCNSceneSource"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@SCNSceneSourceLoadingOption",
          "text": "LoadingOption"
        }
      ],
      "identifier": "doc://com.apple.scenekit/documentation/SceneKit/SCNSceneSource/LoadingOption/useSafeMode",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SCNSceneSourceUseSafeModeKey"
        }
      ],
      "role": "symbol",
      "title": "useSafeMode",
      "type": "topic",
      "url": "/documentation/scenekit/scnscenesource/loadingoption/usesafemode"
    },
    "doc://com.externally.resolved.symbol/c:objc(cs)NSString": {
      "abstract": [
        {
          "text": "A static, plain-text Unicode string object which you use when you need reference semantics or other Foundation-specific behavior. ",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "class "
        },
        {
          "kind": "identifier",
          "text": "NSString"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSString",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSString",
      "type": "topic",
      "url": "/documentation/foundation/nsstring"
    },
    "doc://com.externally.resolved.symbol/s:SH": {
      "abstract": [
        {
          "text": "A type that can be hashed into a `Hasher` to produce an integer hash value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Hashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SQ",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SH",
      "kind": "symbol",
      "role": "symbol",
      "title": "Hashable",
      "type": "topic",
      "url": "/documentation/Swift/Hashable"
    },
    "doc://com.externally.resolved.symbol/s:SQ": {
      "abstract": [
        {
          "text": "A type that can be compared for value equality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SQ",
      "kind": "symbol",
      "role": "symbol",
      "title": "Equatable",
      "type": "topic",
      "url": "/documentation/Swift/Equatable"
    },
    "doc://com.externally.resolved.symbol/s:SY": {
      "abstract": [
        {
          "text": "A type that can be converted to and from an associated raw value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "RawRepresentable"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SY8RawValueQa",
          "text": "RawValue"
        },
        {
          "kind": "text",
          "text": ">"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SY",
      "kind": "symbol",
      "role": "symbol",
      "title": "RawRepresentable",
      "type": "topic",
      "url": "/documentation/Swift/RawRepresentable"
    },
    "doc://com.externally.resolved.symbol/s:s8SendableP": {
      "abstract": [
        {
          "text": "A thread-safe type whose values can be shared across arbitrary concurrent contexts without introducing a risk of data races.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Sendable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s8SendableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "Sendable",
      "type": "topic",
      "url": "/documentation/Swift/Sendable"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:SQ",
        "doc://com.externally.resolved.symbol/s:SH",
        "doc://com.externally.resolved.symbol/s:SY",
        "doc://com.externally.resolved.symbol/s:s8SendableP"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Type-Properties",
      "generated": true,
      "identifiers": [
        "doc://com.apple.scenekit/documentation/SceneKit/SCNSceneSource/LoadingOption/animationImportPolicy",
        "doc://com.apple.scenekit/documentation/SceneKit/SCNSceneSource/LoadingOption/assetDirectoryURLs",
        "doc://com.apple.scenekit/documentation/SceneKit/SCNSceneSource/LoadingOption/checkConsistency",
        "doc://com.apple.scenekit/documentation/SceneKit/SCNSceneSource/LoadingOption/convertToYUp",
        "doc://com.apple.scenekit/documentation/SceneKit/SCNSceneSource/LoadingOption/convertUnitsToMeters",
        "doc://com.apple.scenekit/documentation/SceneKit/SCNSceneSource/LoadingOption/createNormalsIfAbsent",
        "doc://com.apple.scenekit/documentation/SceneKit/SCNSceneSource/LoadingOption/flattenScene",
        "doc://com.apple.scenekit/documentation/SceneKit/SCNSceneSource/LoadingOption/overrideAssetURLs",
        "doc://com.apple.scenekit/documentation/SceneKit/SCNSceneSource/LoadingOption/preserveOriginalTopology",
        "doc://com.apple.scenekit/documentation/SceneKit/SCNSceneSource/LoadingOption/strictConformance",
        "doc://com.apple.scenekit/documentation/SceneKit/SCNSceneSource/LoadingOption/useSafeMode"
      ],
      "title": "Type Properties"
    }
  ],
  "topicSections": [
    {
      "anchor": "Type-Properties",
      "identifiers": [
        "doc://com.apple.scenekit/documentation/SceneKit/SCNSceneSource/AnimationImportPolicy/doNotPlay",
        "doc://com.apple.scenekit/documentation/SceneKit/SCNSceneSource/AnimationImportPolicy/play",
        "doc://com.apple.scenekit/documentation/SceneKit/SCNSceneSource/AnimationImportPolicy/playRepeatedly",
        "doc://com.apple.scenekit/documentation/SceneKit/SCNSceneSource/AnimationImportPolicy/playUsingSceneTimeBase"
      ],
      "title": "Type Properties"
    },
    {
      "anchor": "Initializers",
      "generated": true,
      "identifiers": [
        "doc://com.apple.scenekit/documentation/SceneKit/SCNSceneSource/AnimationImportPolicy/init(rawValue:)"
      ],
      "title": "Initializers"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "visionOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Type Alias"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "SCNSceneSourceAnimationImportPolicy"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "typealias"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SCNSceneSourceAnimationImportPolicy"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SCNSceneSourceAnimationImportPolicy"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.scenekit/documentation/SceneKit"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Type-Properties",
              "identifiers": [
                "doc://com.apple.scenekit/documentation/SceneKit/SCNSceneSource/AnimationImportPolicy/doNotPlay",
                "doc://com.apple.scenekit/documentation/SceneKit/SCNSceneSource/AnimationImportPolicy/play",
                "doc://com.apple.scenekit/documentation/SceneKit/SCNSceneSource/AnimationImportPolicy/playRepeatedly",
                "doc://com.apple.scenekit/documentation/SceneKit/SCNSceneSource/AnimationImportPolicy/playUsingSceneTimeBase"
              ],
              "title": "Type Properties"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Type-Properties",
              "generated": true,
              "identifiers": [
                "doc://com.apple.scenekit/documentation/SceneKit/SCNSceneSource/LoadingOption/animationImportPolicy",
                "doc://com.apple.scenekit/documentation/SceneKit/SCNSceneSource/LoadingOption/assetDirectoryURLs",
                "doc://com.apple.scenekit/documentation/SceneKit/SCNSceneSource/LoadingOption/checkConsistency",
                "doc://com.apple.scenekit/documentation/SceneKit/SCNSceneSource/LoadingOption/convertToYUp",
                "doc://com.apple.scenekit/documentation/SceneKit/SCNSceneSource/LoadingOption/convertUnitsToMeters",
                "doc://com.apple.scenekit/documentation/SceneKit/SCNSceneSource/LoadingOption/createNormalsIfAbsent",
                "doc://com.apple.scenekit/documentation/SceneKit/SCNSceneSource/LoadingOption/flattenScene",
                "doc://com.apple.scenekit/documentation/SceneKit/SCNSceneSource/LoadingOption/overrideAssetURLs",
                "doc://com.apple.scenekit/documentation/SceneKit/SCNSceneSource/LoadingOption/preserveOriginalTopology",
                "doc://com.apple.scenekit/documentation/SceneKit/SCNSceneSource/LoadingOption/strictConformance",
                "doc://com.apple.scenekit/documentation/SceneKit/SCNSceneSource/LoadingOption/useSafeMode"
              ],
              "title": "Type Properties"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "typedef"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSString",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(cs)NSString",
                    "text": "NSString"
                  },
                  {
                    "kind": "text",
                    "text": " * "
                  },
                  {
                    "kind": "identifier",
                    "text": "SCNSceneSourceAnimationImportPolicy"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:objc(cs)NSString/abstract",
          "value": [
            {
              "text": "A static, plain-text Unicode string object.",
              "type": "text"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNSceneSource~1LoadingOption~1createNormalsIfAbsent/title",
          "value": "SCNSceneSourceCreateNormalsIfAbsentKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNSceneSource~1LoadingOption~1createNormalsIfAbsent/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SCNSceneSourceCreateNormalsIfAbsentKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNSceneSource~1LoadingOption~1overrideAssetURLs/title",
          "value": "SCNSceneSourceOverrideAssetURLsKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNSceneSource~1LoadingOption~1overrideAssetURLs/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SCNSceneSourceOverrideAssetURLsKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNSceneSource~1LoadingOption~1assetDirectoryURLs/title",
          "value": "SCNSceneSourceAssetDirectoryURLsKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNSceneSource~1LoadingOption~1assetDirectoryURLs/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SCNSceneSourceAssetDirectoryURLsKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNSceneSource~1AnimationImportPolicy~1doNotPlay/title",
          "value": "SCNSceneSourceAnimationImportPolicyDoNotPlay"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNSceneSource~1AnimationImportPolicy~1doNotPlay/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SCNSceneSourceAnimationImportPolicyDoNotPlay"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNSceneSource~1LoadingOption~1checkConsistency/title",
          "value": "SCNSceneSourceCheckConsistencyKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNSceneSource~1LoadingOption~1checkConsistency/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SCNSceneSourceCheckConsistencyKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNSceneSource~1LoadingOption~1convertUnitsToMeters/title",
          "value": "SCNSceneSourceConvertUnitsToMetersKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNSceneSource~1LoadingOption~1convertUnitsToMeters/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SCNSceneSourceConvertUnitsToMetersKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNSceneSource~1AnimationImportPolicy~1playUsingSceneTimeBase/title",
          "value": "SCNSceneSourceAnimationImportPolicyPlayUsingSceneTimeBase"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNSceneSource~1AnimationImportPolicy~1playUsingSceneTimeBase/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SCNSceneSourceAnimationImportPolicyPlayUsingSceneTimeBase"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNSceneSource~1LoadingOption~1convertToYUp/title",
          "value": "SCNSceneSourceConvertToYUpKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNSceneSource~1LoadingOption~1convertToYUp/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SCNSceneSourceConvertToYUpKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNSceneSource~1LoadingOption~1strictConformance/title",
          "value": "SCNSceneSourceStrictConformanceKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNSceneSource~1LoadingOption~1strictConformance/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SCNSceneSourceStrictConformanceKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNSceneSource~1LoadingOption~1flattenScene/title",
          "value": "SCNSceneSourceFlattenSceneKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNSceneSource~1LoadingOption~1flattenScene/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SCNSceneSourceFlattenSceneKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNSceneSource~1LoadingOption~1preserveOriginalTopology/title",
          "value": "SCNSceneSourceLoadingOptionPreserveOriginalTopology"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNSceneSource~1LoadingOption~1preserveOriginalTopology/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SCNSceneSourceLoadingOptionPreserveOriginalTopology"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNSceneSource~1LoadingOption~1animationImportPolicy/title",
          "value": "SCNSceneSourceAnimationImportPolicyKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNSceneSource~1LoadingOption~1animationImportPolicy/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SCNSceneSourceAnimationImportPolicyKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNSceneRenderer~1sceneTime/title",
          "value": "sceneTime"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNSceneRenderer~1sceneTime/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "sceneTime"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNSceneSource~1LoadingOption~1useSafeMode/title",
          "value": "SCNSceneSourceUseSafeModeKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNSceneSource~1LoadingOption~1useSafeMode/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SCNSceneSourceUseSafeModeKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNSceneSource~1AnimationImportPolicy/title",
          "value": "SCNSceneSourceAnimationImportPolicy"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNSceneSource~1AnimationImportPolicy/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SCNSceneSourceAnimationImportPolicy"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNSceneSource~1AnimationImportPolicy/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SCNSceneSourceAnimationImportPolicy"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNSceneSource/title",
          "value": "SCNSceneSource"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNSceneSource/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SCNSceneSource"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNSceneSource/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SCNSceneSource"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNSceneSource~1AnimationImportPolicy~1play/title",
          "value": "SCNSceneSourceAnimationImportPolicyPlay"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNSceneSource~1AnimationImportPolicy~1play/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SCNSceneSourceAnimationImportPolicyPlay"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNSceneSource~1AnimationImportPolicy~1playRepeatedly/title",
          "value": "SCNSceneSourceAnimationImportPolicyPlayRepeatedly"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNSceneSource~1AnimationImportPolicy~1playRepeatedly/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SCNSceneSourceAnimationImportPolicyPlayRepeatedly"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/scenekit/scnscenesource/animationimportpolicy"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/scenekit/scnscenesource/animationimportpolicy"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
