{
  "abstract": [
    {
      "text": "A notification that posts when a person changes the flashing lights setting on the device.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.mediaaccessibility/documentation/MediaAccessibility"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.mediaaccessibility/documentation/MediaAccessibility/kMADimFlashingLightsChangedNotification"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@kMADimFlashingLightsChangedNotification",
    "fragments": [
      {
        "kind": "keyword",
        "text": "let"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "kMADimFlashingLightsChangedNotification"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@T@CFStringRef",
        "text": "CFString"
      }
    ],
    "modules": [
      {
        "name": "Media Accessibility"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "kMADimFlashingLightsChangedNotification"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "16.4",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "16.4",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "16.4",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.3",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "16.4",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Global Variable",
    "symbolKind": "var",
    "title": "kMADimFlashingLightsChangedNotification"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "let"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "kMADimFlashingLightsChangedNotification"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/c:@T@CFStringRef",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@CFStringRef",
              "text": "CFString"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.mediaaccessibility/documentation/MediaAccessibility": {
      "abstract": [
        {
          "text": "Make your app’s media more accessible by supporting people’s systemwide preferences for video and audio content.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.mediaaccessibility/documentation/MediaAccessibility",
      "kind": "symbol",
      "role": "collection",
      "title": "Media Accessibility",
      "type": "topic",
      "url": "/documentation/mediaaccessibility"
    },
    "doc://com.apple.mediaaccessibility/documentation/MediaAccessibility/MADimFlashingLightsEnabled()": {
      "abstract": [
        {
          "text": "Returns a Boolean value that indicates whether the flashing lights setting is enabled on the device.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MADimFlashingLightsEnabled"
        },
        {
          "kind": "text",
          "text": "() -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.mediaaccessibility/documentation/MediaAccessibility/MADimFlashingLightsEnabled()",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MADimFlashingLightsEnabled"
        }
      ],
      "role": "symbol",
      "title": "MADimFlashingLightsEnabled()",
      "type": "topic",
      "url": "/documentation/mediaaccessibility/madimflashinglightsenabled()"
    },
    "doc://com.apple.mediaaccessibility/documentation/MediaAccessibility/MAFlashingLightsProcessor": {
      "abstract": [
        {
          "text": "A class that processes a framebuffer object to detect and dim sequences of flashing lights.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MAFlashingLightsProcessor"
        }
      ],
      "identifier": "doc://com.apple.mediaaccessibility/documentation/MediaAccessibility/MAFlashingLightsProcessor",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MAFlashingLightsProcessor"
        }
      ],
      "role": "symbol",
      "title": "MAFlashingLightsProcessor",
      "type": "topic",
      "url": "/documentation/mediaaccessibility/maflashinglightsprocessor"
    },
    "doc://com.apple.mediaaccessibility/documentation/MediaAccessibility/kMADimFlashingLightsChangedNotification": {
      "abstract": [
        {
          "text": "A notification that posts when a person changes the flashing lights setting on the device.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kMADimFlashingLightsChangedNotification"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.mediaaccessibility/documentation/MediaAccessibility/kMADimFlashingLightsChangedNotification",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kMADimFlashingLightsChangedNotification"
        }
      ],
      "role": "symbol",
      "title": "kMADimFlashingLightsChangedNotification",
      "type": "topic",
      "url": "/documentation/mediaaccessibility/kmadimflashinglightschangednotification"
    },
    "doc://com.apple.mediaaccessibility/documentation/MediaAccessibility/responding-to-changes-in-the-flashing-lights-setting": {
      "abstract": [
        {
          "text": "Adjust your UI when a person chooses to dim flashing lights on their Apple device.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.mediaaccessibility/documentation/MediaAccessibility/responding-to-changes-in-the-flashing-lights-setting",
      "kind": "article",
      "role": "sampleCode",
      "title": "Responding to changes in the flashing lights setting",
      "type": "topic",
      "url": "/documentation/mediaaccessibility/responding-to-changes-in-the-flashing-lights-setting"
    },
    "doc://com.externally.resolved.symbol/c:@T@CFStringRef": {
      "abstract": [
        {
          "text": "A reference to a CFString object.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "class "
        },
        {
          "kind": "identifier",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:@T@CFStringRef",
      "kind": "symbol",
      "role": "symbol",
      "title": "CFString",
      "type": "topic",
      "url": "/documentation/corefoundation/cfstring"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Dim-flashing-lights",
      "generated": true,
      "identifiers": [
        "doc://com.apple.mediaaccessibility/documentation/MediaAccessibility/responding-to-changes-in-the-flashing-lights-setting",
        "doc://com.apple.mediaaccessibility/documentation/MediaAccessibility/MADimFlashingLightsEnabled()",
        "doc://com.apple.mediaaccessibility/documentation/MediaAccessibility/MAFlashingLightsProcessor"
      ],
      "title": "Dim flashing lights"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "16.4",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "16.4",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "16.4",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.3",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "16.4",
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Global Variable"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "kMADimFlashingLightsChangedNotification"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "var"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kMADimFlashingLightsChangedNotification"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.mediaaccessibility/documentation/MediaAccessibility"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Dim-flashing-lights",
              "generated": true,
              "identifiers": [
                "doc://com.apple.mediaaccessibility/documentation/MediaAccessibility/MADimFlashingLightsEnabled()",
                "doc://com.apple.mediaaccessibility/documentation/MediaAccessibility/MAFlashingLightsProcessor"
              ],
              "title": "Dim flashing lights"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "extern"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:@T@CFStringRef",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@CFStringRef",
                    "text": "CFStringRef"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "keyword",
                    "text": "const"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "kMADimFlashingLightsChangedNotification"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaaccessibility~1documentation~1MediaAccessibility~1kMADimFlashingLightsChangedNotification/title",
          "value": "kMADimFlashingLightsChangedNotification"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaaccessibility~1documentation~1MediaAccessibility~1kMADimFlashingLightsChangedNotification/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kMADimFlashingLightsChangedNotification"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:@T@CFStringRef/title",
          "value": "CFStringRef"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaaccessibility~1documentation~1MediaAccessibility~1MADimFlashingLightsEnabled()/title",
          "value": "MADimFlashingLightsEnabled"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaaccessibility~1documentation~1MediaAccessibility~1MADimFlashingLightsEnabled()/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MADimFlashingLightsEnabled"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaaccessibility~1documentation~1MediaAccessibility~1MAFlashingLightsProcessor/title",
          "value": "MAFlashingLightsProcessor"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaaccessibility~1documentation~1MediaAccessibility~1MAFlashingLightsProcessor/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MAFlashingLightsProcessor"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaaccessibility~1documentation~1MediaAccessibility~1MAFlashingLightsProcessor/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MAFlashingLightsProcessor"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/mediaaccessibility/kmadimflashinglightschangednotification"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/mediaaccessibility/kmadimflashinglightschangednotification"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
