{
  "abstract": [
    {
      "text": "A value that specifies a font style.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.mediaaccessibility/documentation/MediaAccessibility"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.mediaaccessibility/documentation/MediaAccessibility/MACaptionAppearanceFontStyle"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@MACaptionAppearanceFontStyle",
    "fragments": [
      {
        "kind": "keyword",
        "text": "enum"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "MACaptionAppearanceFontStyle"
      }
    ],
    "modules": [
      {
        "name": "Media Accessibility"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "MACaptionAppearanceFontStyle"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "7.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "7.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.1",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.9",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "17.0",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Enumeration",
    "symbolKind": "enum",
    "title": "MACaptionAppearanceFontStyle"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "enum"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "MACaptionAppearanceFontStyle"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.mediaaccessibility/documentation/MediaAccessibility": {
      "abstract": [
        {
          "text": "Make your app’s media more accessible by supporting people’s systemwide preferences for video and audio content.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.mediaaccessibility/documentation/MediaAccessibility",
      "kind": "symbol",
      "role": "collection",
      "title": "Media Accessibility",
      "type": "topic",
      "url": "/documentation/mediaaccessibility"
    },
    "doc://com.apple.mediaaccessibility/documentation/MediaAccessibility/MACaptionAppearanceBehavior": {
      "abstract": [
        {
          "text": "A value that indicates the preferred behavior for a preference setting.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MACaptionAppearanceBehavior"
        }
      ],
      "identifier": "doc://com.apple.mediaaccessibility/documentation/MediaAccessibility/MACaptionAppearanceBehavior",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MACaptionAppearanceBehavior"
        }
      ],
      "role": "symbol",
      "title": "MACaptionAppearanceBehavior",
      "type": "topic",
      "url": "/documentation/mediaaccessibility/macaptionappearancebehavior"
    },
    "doc://com.apple.mediaaccessibility/documentation/MediaAccessibility/MACaptionAppearanceDisplayType": {
      "abstract": [
        {
          "text": "A value that specifies the type of captions to display.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MACaptionAppearanceDisplayType"
        }
      ],
      "identifier": "doc://com.apple.mediaaccessibility/documentation/MediaAccessibility/MACaptionAppearanceDisplayType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MACaptionAppearanceDisplayType"
        }
      ],
      "role": "symbol",
      "title": "MACaptionAppearanceDisplayType",
      "type": "topic",
      "url": "/documentation/mediaaccessibility/macaptionappearancedisplaytype"
    },
    "doc://com.apple.mediaaccessibility/documentation/MediaAccessibility/MACaptionAppearanceDomain": {
      "abstract": [
        {
          "text": "A value that specifies which domain to retrieve a preference setting from.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MACaptionAppearanceDomain"
        }
      ],
      "identifier": "doc://com.apple.mediaaccessibility/documentation/MediaAccessibility/MACaptionAppearanceDomain",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MACaptionAppearanceDomain"
        }
      ],
      "role": "symbol",
      "title": "MACaptionAppearanceDomain",
      "type": "topic",
      "url": "/documentation/mediaaccessibility/macaptionappearancedomain"
    },
    "doc://com.apple.mediaaccessibility/documentation/MediaAccessibility/MACaptionAppearanceFontStyle": {
      "abstract": [
        {
          "text": "A value that specifies a font style.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MACaptionAppearanceFontStyle"
        }
      ],
      "identifier": "doc://com.apple.mediaaccessibility/documentation/MediaAccessibility/MACaptionAppearanceFontStyle",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MACaptionAppearanceFontStyle"
        }
      ],
      "role": "symbol",
      "title": "MACaptionAppearanceFontStyle",
      "type": "topic",
      "url": "/documentation/mediaaccessibility/macaptionappearancefontstyle"
    },
    "doc://com.apple.mediaaccessibility/documentation/MediaAccessibility/MACaptionAppearanceFontStyle/casual": {
      "abstract": [
        {
          "text": "The font style preferred for the casual font style.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "casual"
        }
      ],
      "identifier": "doc://com.apple.mediaaccessibility/documentation/MediaAccessibility/MACaptionAppearanceFontStyle/casual",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kMACaptionAppearanceFontStyleCasual"
        }
      ],
      "role": "symbol",
      "title": "MACaptionAppearanceFontStyle.casual",
      "type": "topic",
      "url": "/documentation/mediaaccessibility/macaptionappearancefontstyle/casual"
    },
    "doc://com.apple.mediaaccessibility/documentation/MediaAccessibility/MACaptionAppearanceFontStyle/cursive": {
      "abstract": [
        {
          "text": "The font style preferred for the cursive font style.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "cursive"
        }
      ],
      "identifier": "doc://com.apple.mediaaccessibility/documentation/MediaAccessibility/MACaptionAppearanceFontStyle/cursive",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kMACaptionAppearanceFontStyleCursive"
        }
      ],
      "role": "symbol",
      "title": "MACaptionAppearanceFontStyle.cursive",
      "type": "topic",
      "url": "/documentation/mediaaccessibility/macaptionappearancefontstyle/cursive"
    },
    "doc://com.apple.mediaaccessibility/documentation/MediaAccessibility/MACaptionAppearanceFontStyle/default": {
      "abstract": [
        {
          "text": "The default font style for all caption text.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "`default`"
        }
      ],
      "identifier": "doc://com.apple.mediaaccessibility/documentation/MediaAccessibility/MACaptionAppearanceFontStyle/default",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kMACaptionAppearanceFontStyleDefault"
        }
      ],
      "role": "symbol",
      "title": "MACaptionAppearanceFontStyle.default",
      "type": "topic",
      "url": "/documentation/mediaaccessibility/macaptionappearancefontstyle/default"
    },
    "doc://com.apple.mediaaccessibility/documentation/MediaAccessibility/MACaptionAppearanceFontStyle/init(rawValue:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "?("
        },
        {
          "kind": "externalParam",
          "text": "rawValue"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFIndex",
          "text": "CFIndex"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.mediaaccessibility/documentation/MediaAccessibility/MACaptionAppearanceFontStyle/init(rawValue:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "init(rawValue:)",
      "type": "topic",
      "url": "/documentation/mediaaccessibility/macaptionappearancefontstyle/init(rawvalue:)"
    },
    "doc://com.apple.mediaaccessibility/documentation/MediaAccessibility/MACaptionAppearanceFontStyle/monospacedWithSerif": {
      "abstract": [
        {
          "text": "The font style preferred for the monospaced serif font style.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "monospacedWithSerif"
        }
      ],
      "identifier": "doc://com.apple.mediaaccessibility/documentation/MediaAccessibility/MACaptionAppearanceFontStyle/monospacedWithSerif",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kMACaptionAppearanceFontStyleMonospacedWithSerif"
        }
      ],
      "role": "symbol",
      "title": "MACaptionAppearanceFontStyle.monospacedWithSerif",
      "type": "topic",
      "url": "/documentation/mediaaccessibility/macaptionappearancefontstyle/monospacedwithserif"
    },
    "doc://com.apple.mediaaccessibility/documentation/MediaAccessibility/MACaptionAppearanceFontStyle/monospacedWithoutSerif": {
      "abstract": [
        {
          "text": "The font style preferred for the monospaced sans serif font style.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "monospacedWithoutSerif"
        }
      ],
      "identifier": "doc://com.apple.mediaaccessibility/documentation/MediaAccessibility/MACaptionAppearanceFontStyle/monospacedWithoutSerif",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kMACaptionAppearanceFontStyleMonospacedWithoutSerif"
        }
      ],
      "role": "symbol",
      "title": "MACaptionAppearanceFontStyle.monospacedWithoutSerif",
      "type": "topic",
      "url": "/documentation/mediaaccessibility/macaptionappearancefontstyle/monospacedwithoutserif"
    },
    "doc://com.apple.mediaaccessibility/documentation/MediaAccessibility/MACaptionAppearanceFontStyle/proportionalWithSerif": {
      "abstract": [
        {
          "text": "The font style preferred for the proportional serif font style.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "proportionalWithSerif"
        }
      ],
      "identifier": "doc://com.apple.mediaaccessibility/documentation/MediaAccessibility/MACaptionAppearanceFontStyle/proportionalWithSerif",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kMACaptionAppearanceFontStyleProportionalWithSerif"
        }
      ],
      "role": "symbol",
      "title": "MACaptionAppearanceFontStyle.proportionalWithSerif",
      "type": "topic",
      "url": "/documentation/mediaaccessibility/macaptionappearancefontstyle/proportionalwithserif"
    },
    "doc://com.apple.mediaaccessibility/documentation/MediaAccessibility/MACaptionAppearanceFontStyle/proportionalWithoutSerif": {
      "abstract": [
        {
          "text": "The font style preferred for the proportional sans serif font style.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "proportionalWithoutSerif"
        }
      ],
      "identifier": "doc://com.apple.mediaaccessibility/documentation/MediaAccessibility/MACaptionAppearanceFontStyle/proportionalWithoutSerif",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kMACaptionAppearanceFontStyleProportionalWithoutSerif"
        }
      ],
      "role": "symbol",
      "title": "MACaptionAppearanceFontStyle.proportionalWithoutSerif",
      "type": "topic",
      "url": "/documentation/mediaaccessibility/macaptionappearancefontstyle/proportionalwithoutserif"
    },
    "doc://com.apple.mediaaccessibility/documentation/MediaAccessibility/MACaptionAppearanceFontStyle/smallCapital": {
      "abstract": [
        {
          "text": "The font style preferred for the small capital font style.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "smallCapital"
        }
      ],
      "identifier": "doc://com.apple.mediaaccessibility/documentation/MediaAccessibility/MACaptionAppearanceFontStyle/smallCapital",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kMACaptionAppearanceFontStyleSmallCapital"
        }
      ],
      "role": "symbol",
      "title": "MACaptionAppearanceFontStyle.smallCapital",
      "type": "topic",
      "url": "/documentation/mediaaccessibility/macaptionappearancefontstyle/smallcapital"
    },
    "doc://com.apple.mediaaccessibility/documentation/MediaAccessibility/MACaptionAppearanceTextEdgeStyle": {
      "abstract": [
        {
          "text": "A value that specifies a style for the outside of the text.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MACaptionAppearanceTextEdgeStyle"
        }
      ],
      "identifier": "doc://com.apple.mediaaccessibility/documentation/MediaAccessibility/MACaptionAppearanceTextEdgeStyle",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MACaptionAppearanceTextEdgeStyle"
        }
      ],
      "role": "symbol",
      "title": "MACaptionAppearanceTextEdgeStyle",
      "type": "topic",
      "url": "/documentation/mediaaccessibility/macaptionappearancetextedgestyle"
    },
    "doc://com.externally.resolved.symbol/c:@T@CFIndex": {
      "abstract": [
        {
          "text": "Priority values used for kAXPriorityKey",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "typealias "
        },
        {
          "kind": "identifier",
          "text": "CFIndex"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:@T@CFIndex",
      "kind": "symbol",
      "role": "symbol",
      "title": "CFIndex",
      "type": "topic",
      "url": "/documentation/corefoundation/cfindex"
    },
    "doc://com.externally.resolved.symbol/s:SH": {
      "abstract": [
        {
          "text": "A type that can be hashed into a `Hasher` to produce an integer hash value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Hashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SQ",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SH",
      "kind": "symbol",
      "role": "symbol",
      "title": "Hashable",
      "type": "topic",
      "url": "/documentation/Swift/Hashable"
    },
    "doc://com.externally.resolved.symbol/s:SQ": {
      "abstract": [
        {
          "text": "A type that can be compared for value equality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SQ",
      "kind": "symbol",
      "role": "symbol",
      "title": "Equatable",
      "type": "topic",
      "url": "/documentation/Swift/Equatable"
    },
    "doc://com.externally.resolved.symbol/s:SY": {
      "abstract": [
        {
          "text": "A type that can be converted to and from an associated raw value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "RawRepresentable"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SY8RawValueQa",
          "text": "RawValue"
        },
        {
          "kind": "text",
          "text": ">"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SY",
      "kind": "symbol",
      "role": "symbol",
      "title": "RawRepresentable",
      "type": "topic",
      "url": "/documentation/Swift/RawRepresentable"
    },
    "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BitwiseCopyable"
        },
        {
          "kind": "text",
          "text": " : ~Escapable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "BitwiseCopyable",
      "type": "topic",
      "url": "/documentation/Swift/BitwiseCopyable"
    },
    "doc://com.externally.resolved.symbol/s:s8SendableP": {
      "abstract": [
        {
          "text": "A thread-safe type whose values can be shared across arbitrary concurrent contexts without introducing a risk of data races.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Sendable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s8SendableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "Sendable",
      "type": "topic",
      "url": "/documentation/Swift/Sendable"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
        "doc://com.externally.resolved.symbol/s:SQ",
        "doc://com.externally.resolved.symbol/s:SH",
        "doc://com.externally.resolved.symbol/s:SY",
        "doc://com.externally.resolved.symbol/s:s8SendableP"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Constants",
      "generated": true,
      "identifiers": [
        "doc://com.apple.mediaaccessibility/documentation/MediaAccessibility/MACaptionAppearanceDomain",
        "doc://com.apple.mediaaccessibility/documentation/MediaAccessibility/MACaptionAppearanceDisplayType",
        "doc://com.apple.mediaaccessibility/documentation/MediaAccessibility/MACaptionAppearanceBehavior",
        "doc://com.apple.mediaaccessibility/documentation/MediaAccessibility/MACaptionAppearanceTextEdgeStyle"
      ],
      "title": "Constants"
    }
  ],
  "topicSections": [
    {
      "anchor": "Constants",
      "identifiers": [
        "doc://com.apple.mediaaccessibility/documentation/MediaAccessibility/MACaptionAppearanceFontStyle/default",
        "doc://com.apple.mediaaccessibility/documentation/MediaAccessibility/MACaptionAppearanceFontStyle/monospacedWithSerif",
        "doc://com.apple.mediaaccessibility/documentation/MediaAccessibility/MACaptionAppearanceFontStyle/proportionalWithSerif",
        "doc://com.apple.mediaaccessibility/documentation/MediaAccessibility/MACaptionAppearanceFontStyle/monospacedWithoutSerif",
        "doc://com.apple.mediaaccessibility/documentation/MediaAccessibility/MACaptionAppearanceFontStyle/proportionalWithoutSerif",
        "doc://com.apple.mediaaccessibility/documentation/MediaAccessibility/MACaptionAppearanceFontStyle/casual",
        "doc://com.apple.mediaaccessibility/documentation/MediaAccessibility/MACaptionAppearanceFontStyle/cursive",
        "doc://com.apple.mediaaccessibility/documentation/MediaAccessibility/MACaptionAppearanceFontStyle/smallCapital"
      ],
      "title": "Constants"
    },
    {
      "anchor": "Initializers",
      "generated": true,
      "identifiers": [
        "doc://com.apple.mediaaccessibility/documentation/MediaAccessibility/MACaptionAppearanceFontStyle/init(rawValue:)"
      ],
      "title": "Initializers"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "7.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "7.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.1",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.9",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "17.0",
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "MACaptionAppearanceFontStyle"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "enum"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MACaptionAppearanceFontStyle"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MACaptionAppearanceFontStyle"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.mediaaccessibility/documentation/MediaAccessibility"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Constants",
              "identifiers": [
                "doc://com.apple.mediaaccessibility/documentation/MediaAccessibility/MACaptionAppearanceFontStyle/default",
                "doc://com.apple.mediaaccessibility/documentation/MediaAccessibility/MACaptionAppearanceFontStyle/monospacedWithSerif",
                "doc://com.apple.mediaaccessibility/documentation/MediaAccessibility/MACaptionAppearanceFontStyle/proportionalWithSerif",
                "doc://com.apple.mediaaccessibility/documentation/MediaAccessibility/MACaptionAppearanceFontStyle/monospacedWithoutSerif",
                "doc://com.apple.mediaaccessibility/documentation/MediaAccessibility/MACaptionAppearanceFontStyle/proportionalWithoutSerif",
                "doc://com.apple.mediaaccessibility/documentation/MediaAccessibility/MACaptionAppearanceFontStyle/casual",
                "doc://com.apple.mediaaccessibility/documentation/MediaAccessibility/MACaptionAppearanceFontStyle/cursive",
                "doc://com.apple.mediaaccessibility/documentation/MediaAccessibility/MACaptionAppearanceFontStyle/smallCapital"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Constants",
              "generated": true,
              "identifiers": [
                "doc://com.apple.mediaaccessibility/documentation/MediaAccessibility/MACaptionAppearanceDomain",
                "doc://com.apple.mediaaccessibility/documentation/MediaAccessibility/MACaptionAppearanceDisplayType",
                "doc://com.apple.mediaaccessibility/documentation/MediaAccessibility/MACaptionAppearanceBehavior",
                "doc://com.apple.mediaaccessibility/documentation/MediaAccessibility/MACaptionAppearanceTextEdgeStyle"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "enum"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "MACaptionAppearanceFontStyle"
                  },
                  {
                    "kind": "text",
                    "text": " : "
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:@T@CFIndex",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@CFIndex",
                    "text": "CFIndex"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaaccessibility~1documentation~1MediaAccessibility~1MACaptionAppearanceFontStyle~1monospacedWithSerif/title",
          "value": "kMACaptionAppearanceFontStyleMonospacedWithSerif"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaaccessibility~1documentation~1MediaAccessibility~1MACaptionAppearanceFontStyle~1monospacedWithSerif/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kMACaptionAppearanceFontStyleMonospacedWithSerif"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaaccessibility~1documentation~1MediaAccessibility~1MACaptionAppearanceBehavior/title",
          "value": "MACaptionAppearanceBehavior"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaaccessibility~1documentation~1MediaAccessibility~1MACaptionAppearanceBehavior/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MACaptionAppearanceBehavior"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaaccessibility~1documentation~1MediaAccessibility~1MACaptionAppearanceBehavior/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MACaptionAppearanceBehavior"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaaccessibility~1documentation~1MediaAccessibility~1MACaptionAppearanceFontStyle~1proportionalWithoutSerif/title",
          "value": "kMACaptionAppearanceFontStyleProportionalWithoutSerif"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaaccessibility~1documentation~1MediaAccessibility~1MACaptionAppearanceFontStyle~1proportionalWithoutSerif/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kMACaptionAppearanceFontStyleProportionalWithoutSerif"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaaccessibility~1documentation~1MediaAccessibility~1MACaptionAppearanceFontStyle~1cursive/title",
          "value": "kMACaptionAppearanceFontStyleCursive"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaaccessibility~1documentation~1MediaAccessibility~1MACaptionAppearanceFontStyle~1cursive/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kMACaptionAppearanceFontStyleCursive"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaaccessibility~1documentation~1MediaAccessibility~1MACaptionAppearanceFontStyle~1monospacedWithoutSerif/title",
          "value": "kMACaptionAppearanceFontStyleMonospacedWithoutSerif"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaaccessibility~1documentation~1MediaAccessibility~1MACaptionAppearanceFontStyle~1monospacedWithoutSerif/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kMACaptionAppearanceFontStyleMonospacedWithoutSerif"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaaccessibility~1documentation~1MediaAccessibility~1MACaptionAppearanceDisplayType/title",
          "value": "MACaptionAppearanceDisplayType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaaccessibility~1documentation~1MediaAccessibility~1MACaptionAppearanceDisplayType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MACaptionAppearanceDisplayType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaaccessibility~1documentation~1MediaAccessibility~1MACaptionAppearanceDisplayType/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MACaptionAppearanceDisplayType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaaccessibility~1documentation~1MediaAccessibility~1MACaptionAppearanceFontStyle~1proportionalWithSerif/title",
          "value": "kMACaptionAppearanceFontStyleProportionalWithSerif"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaaccessibility~1documentation~1MediaAccessibility~1MACaptionAppearanceFontStyle~1proportionalWithSerif/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kMACaptionAppearanceFontStyleProportionalWithSerif"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaaccessibility~1documentation~1MediaAccessibility~1MACaptionAppearanceFontStyle/title",
          "value": "MACaptionAppearanceFontStyle"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaaccessibility~1documentation~1MediaAccessibility~1MACaptionAppearanceFontStyle/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MACaptionAppearanceFontStyle"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaaccessibility~1documentation~1MediaAccessibility~1MACaptionAppearanceFontStyle/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MACaptionAppearanceFontStyle"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaaccessibility~1documentation~1MediaAccessibility~1MACaptionAppearanceTextEdgeStyle/title",
          "value": "MACaptionAppearanceTextEdgeStyle"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaaccessibility~1documentation~1MediaAccessibility~1MACaptionAppearanceTextEdgeStyle/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MACaptionAppearanceTextEdgeStyle"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaaccessibility~1documentation~1MediaAccessibility~1MACaptionAppearanceTextEdgeStyle/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MACaptionAppearanceTextEdgeStyle"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaaccessibility~1documentation~1MediaAccessibility~1MACaptionAppearanceFontStyle~1casual/title",
          "value": "kMACaptionAppearanceFontStyleCasual"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaaccessibility~1documentation~1MediaAccessibility~1MACaptionAppearanceFontStyle~1casual/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kMACaptionAppearanceFontStyleCasual"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaaccessibility~1documentation~1MediaAccessibility~1MACaptionAppearanceDomain/title",
          "value": "MACaptionAppearanceDomain"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaaccessibility~1documentation~1MediaAccessibility~1MACaptionAppearanceDomain/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MACaptionAppearanceDomain"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaaccessibility~1documentation~1MediaAccessibility~1MACaptionAppearanceDomain/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MACaptionAppearanceDomain"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaaccessibility~1documentation~1MediaAccessibility~1MACaptionAppearanceFontStyle~1default/title",
          "value": "kMACaptionAppearanceFontStyleDefault"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaaccessibility~1documentation~1MediaAccessibility~1MACaptionAppearanceFontStyle~1default/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kMACaptionAppearanceFontStyleDefault"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaaccessibility~1documentation~1MediaAccessibility~1MACaptionAppearanceFontStyle~1smallCapital/title",
          "value": "kMACaptionAppearanceFontStyleSmallCapital"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaaccessibility~1documentation~1MediaAccessibility~1MACaptionAppearanceFontStyle~1smallCapital/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kMACaptionAppearanceFontStyleSmallCapital"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/mediaaccessibility/macaptionappearancefontstyle"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/mediaaccessibility/macaptionappearancefontstyle"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
