{
  "abstract": [
    {
      "text": "Returns the preference for the overlay’s opacity.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.mediaaccessibility/documentation/MediaAccessibility"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.mediaaccessibility/documentation/MediaAccessibility/MACaptionAppearanceGetWindowOpacity(_:_:)"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@F@MACaptionAppearanceGetWindowOpacity",
    "fragments": [
      {
        "kind": "keyword",
        "text": "func"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "MACaptionAppearanceGetWindowOpacity"
      },
      {
        "kind": "text",
        "text": "("
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@E@MACaptionAppearanceDomain",
        "text": "MACaptionAppearanceDomain"
      },
      {
        "kind": "text",
        "text": ", "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "s:Sp",
        "text": "UnsafeMutablePointer"
      },
      {
        "kind": "text",
        "text": "<"
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@E@MACaptionAppearanceBehavior",
        "text": "MACaptionAppearanceBehavior"
      },
      {
        "kind": "text",
        "text": ">?) -> "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "s:14CoreFoundation7CGFloatV",
        "text": "CGFloat"
      }
    ],
    "modules": [
      {
        "name": "Media Accessibility"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "MACaptionAppearanceGetWindowOpacity"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "7.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "7.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.1",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.9",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "17.0",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Function",
    "symbolKind": "func",
    "title": "MACaptionAppearanceGetWindowOpacity(_:_:)"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "func"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "MACaptionAppearanceGetWindowOpacity"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "kind": "externalParam",
              "text": "_"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "domain"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.mediaaccessibility/documentation/MediaAccessibility/MACaptionAppearanceDomain",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@E@MACaptionAppearanceDomain",
              "text": "MACaptionAppearanceDomain"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "kind": "externalParam",
              "text": "_"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "behavior"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:Sp",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:Sp",
              "text": "UnsafeMutablePointer"
            },
            {
              "kind": "text",
              "text": "<"
            },
            {
              "identifier": "doc://com.apple.mediaaccessibility/documentation/MediaAccessibility/MACaptionAppearanceBehavior",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@E@MACaptionAppearanceBehavior",
              "text": "MACaptionAppearanceBehavior"
            },
            {
              "kind": "text",
              "text": ">?) -> "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:14CoreFoundation7CGFloatV",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:14CoreFoundation7CGFloatV",
              "text": "CGFloat"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "kind": "parameters",
      "parameters": [
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "The domain to retrieve the preference value from. See ",
                  "type": "text"
                },
                {
                  "identifier": "doc://com.apple.mediaaccessibility/documentation/MediaAccessibility/MACaptionAppearanceDomain",
                  "isActive": true,
                  "type": "reference"
                },
                {
                  "text": ". Pass ",
                  "type": "text"
                },
                {
                  "identifier": "doc://com.apple.mediaaccessibility/documentation/MediaAccessibility/MACaptionAppearanceDomain/user",
                  "isActive": true,
                  "type": "reference"
                },
                {
                  "text": " unless the system defaults are needed for comparison.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "domain"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "A pointer to memory. On return, this memory holds the caption appearance behavior for this preference setting. For possible values see ",
                  "type": "text"
                },
                {
                  "identifier": "doc://com.apple.mediaaccessibility/documentation/MediaAccessibility/MACaptionAppearanceBehavior",
                  "isActive": true,
                  "type": "reference"
                },
                {
                  "text": ". Pass ",
                  "type": "text"
                },
                {
                  "code": "NULL",
                  "type": "codeVoice"
                },
                {
                  "text": " when you do not need the behavior setting.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "behavior"
        }
      ]
    },
    {
      "content": [
        {
          "anchor": "Return-Value",
          "level": 2,
          "text": "Return Value",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "The float value, ranging from ",
              "type": "text"
            },
            {
              "code": "0.0",
              "type": "codeVoice"
            },
            {
              "text": " to ",
              "type": "text"
            },
            {
              "code": "1.0",
              "type": "codeVoice"
            },
            {
              "text": ", representing the opacity of the color behind all other caption elements.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.mediaaccessibility/documentation/MediaAccessibility": {
      "abstract": [
        {
          "text": "Make your app’s media more accessible by supporting people’s systemwide preferences for video and audio content.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.mediaaccessibility/documentation/MediaAccessibility",
      "kind": "symbol",
      "role": "collection",
      "title": "Media Accessibility",
      "type": "topic",
      "url": "/documentation/mediaaccessibility"
    },
    "doc://com.apple.mediaaccessibility/documentation/MediaAccessibility/MACaptionAppearanceBehavior": {
      "abstract": [
        {
          "text": "A value that indicates the preferred behavior for a preference setting.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MACaptionAppearanceBehavior"
        }
      ],
      "identifier": "doc://com.apple.mediaaccessibility/documentation/MediaAccessibility/MACaptionAppearanceBehavior",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MACaptionAppearanceBehavior"
        }
      ],
      "role": "symbol",
      "title": "MACaptionAppearanceBehavior",
      "type": "topic",
      "url": "/documentation/mediaaccessibility/macaptionappearancebehavior"
    },
    "doc://com.apple.mediaaccessibility/documentation/MediaAccessibility/MACaptionAppearanceCopyWindowColor(_:_:)": {
      "abstract": [
        {
          "text": "Returns the preference for the caption window’s color.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MACaptionAppearanceCopyWindowColor"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@MACaptionAppearanceDomain",
          "text": "MACaptionAppearanceDomain"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sp",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@MACaptionAppearanceBehavior",
          "text": "MACaptionAppearanceBehavior"
        },
        {
          "kind": "text",
          "text": ">?) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s9UnmanagedV",
          "text": "Unmanaged"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CGColorRef",
          "text": "CGColor"
        },
        {
          "kind": "text",
          "text": ">"
        }
      ],
      "identifier": "doc://com.apple.mediaaccessibility/documentation/MediaAccessibility/MACaptionAppearanceCopyWindowColor(_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MACaptionAppearanceCopyWindowColor"
        }
      ],
      "role": "symbol",
      "title": "MACaptionAppearanceCopyWindowColor(_:_:)",
      "type": "topic",
      "url": "/documentation/mediaaccessibility/macaptionappearancecopywindowcolor(_:_:)"
    },
    "doc://com.apple.mediaaccessibility/documentation/MediaAccessibility/MACaptionAppearanceDomain": {
      "abstract": [
        {
          "text": "A value that specifies which domain to retrieve a preference setting from.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MACaptionAppearanceDomain"
        }
      ],
      "identifier": "doc://com.apple.mediaaccessibility/documentation/MediaAccessibility/MACaptionAppearanceDomain",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MACaptionAppearanceDomain"
        }
      ],
      "role": "symbol",
      "title": "MACaptionAppearanceDomain",
      "type": "topic",
      "url": "/documentation/mediaaccessibility/macaptionappearancedomain"
    },
    "doc://com.apple.mediaaccessibility/documentation/MediaAccessibility/MACaptionAppearanceDomain/user": {
      "abstract": [
        {
          "text": "The user’s preferred value for the setting should be returned.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "user"
        }
      ],
      "identifier": "doc://com.apple.mediaaccessibility/documentation/MediaAccessibility/MACaptionAppearanceDomain/user",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kMACaptionAppearanceDomainUser"
        }
      ],
      "role": "symbol",
      "title": "MACaptionAppearanceDomain.user",
      "type": "topic",
      "url": "/documentation/mediaaccessibility/macaptionappearancedomain/user"
    },
    "doc://com.apple.mediaaccessibility/documentation/MediaAccessibility/MACaptionAppearanceGetWindowOpacity(_:_:)": {
      "abstract": [
        {
          "text": "Returns the preference for the overlay’s opacity.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MACaptionAppearanceGetWindowOpacity"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@MACaptionAppearanceDomain",
          "text": "MACaptionAppearanceDomain"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sp",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@MACaptionAppearanceBehavior",
          "text": "MACaptionAppearanceBehavior"
        },
        {
          "kind": "text",
          "text": ">?) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:14CoreFoundation7CGFloatV",
          "text": "CGFloat"
        }
      ],
      "identifier": "doc://com.apple.mediaaccessibility/documentation/MediaAccessibility/MACaptionAppearanceGetWindowOpacity(_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MACaptionAppearanceGetWindowOpacity"
        }
      ],
      "role": "symbol",
      "title": "MACaptionAppearanceGetWindowOpacity(_:_:)",
      "type": "topic",
      "url": "/documentation/mediaaccessibility/macaptionappearancegetwindowopacity(_:_:)"
    },
    "doc://com.apple.mediaaccessibility/documentation/MediaAccessibility/MACaptionAppearanceGetWindowRoundedCornerRadius(_:_:)": {
      "abstract": [
        {
          "text": "Returns the radius of the caption window’s corners.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MACaptionAppearanceGetWindowRoundedCornerRadius"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@MACaptionAppearanceDomain",
          "text": "MACaptionAppearanceDomain"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sp",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@MACaptionAppearanceBehavior",
          "text": "MACaptionAppearanceBehavior"
        },
        {
          "kind": "text",
          "text": ">?) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:14CoreFoundation7CGFloatV",
          "text": "CGFloat"
        }
      ],
      "identifier": "doc://com.apple.mediaaccessibility/documentation/MediaAccessibility/MACaptionAppearanceGetWindowRoundedCornerRadius(_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MACaptionAppearanceGetWindowRoundedCornerRadius"
        }
      ],
      "role": "symbol",
      "title": "MACaptionAppearanceGetWindowRoundedCornerRadius(_:_:)",
      "type": "topic",
      "url": "/documentation/mediaaccessibility/macaptionappearancegetwindowroundedcornerradius(_:_:)"
    },
    "doc://com.externally.resolved.symbol/s:14CoreFoundation7CGFloatV": {
      "abstract": [
        {
          "text": "The basic type for floating-point scalar values in Core Graphics and related frameworks.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "struct "
        },
        {
          "kind": "identifier",
          "text": "CGFloat"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:14CoreFoundation7CGFloatV",
      "kind": "symbol",
      "role": "symbol",
      "title": "CGFloat",
      "type": "topic",
      "url": "/documentation/corefoundation/cgfloat"
    },
    "doc://com.externally.resolved.symbol/s:Sp": {
      "abstract": [
        {
          "text": "A pointer for accessing and manipulating data of a specific type.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@frozen"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "genericParameter",
          "text": "Pointee"
        },
        {
          "kind": "text",
          "text": "> "
        },
        {
          "kind": "keyword",
          "text": "where"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "typeIdentifier",
          "text": "Pointee"
        },
        {
          "kind": "text",
          "text": " : ~Copyable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:Sp",
      "kind": "symbol",
      "role": "symbol",
      "title": "UnsafeMutablePointer",
      "type": "topic",
      "url": "/documentation/Swift/UnsafeMutablePointer"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Caption-window-settings",
      "generated": true,
      "identifiers": [
        "doc://com.apple.mediaaccessibility/documentation/MediaAccessibility/MACaptionAppearanceCopyWindowColor(_:_:)",
        "doc://com.apple.mediaaccessibility/documentation/MediaAccessibility/MACaptionAppearanceGetWindowRoundedCornerRadius(_:_:)"
      ],
      "title": "Caption window settings"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "7.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "7.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.1",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.9",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "17.0",
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Function"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "MACaptionAppearanceGetWindowOpacity"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "func"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MACaptionAppearanceGetWindowOpacity"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.mediaaccessibility/documentation/MediaAccessibility"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Caption-window-settings",
              "generated": true,
              "identifiers": [
                "doc://com.apple.mediaaccessibility/documentation/MediaAccessibility/MACaptionAppearanceCopyWindowColor(_:_:)",
                "doc://com.apple.mediaaccessibility/documentation/MediaAccessibility/MACaptionAppearanceGetWindowRoundedCornerRadius(_:_:)"
              ],
              "title": "Caption window settings"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "extern"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@CGFloat",
                    "text": "CGFloat"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "MACaptionAppearanceGetWindowOpacity"
                  },
                  {
                    "kind": "text",
                    "text": "("
                  },
                  {
                    "identifier": "doc://com.apple.mediaaccessibility/documentation/MediaAccessibility/MACaptionAppearanceDomain",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@E@MACaptionAppearanceDomain",
                    "text": "MACaptionAppearanceDomain"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "internalParam",
                    "text": "domain"
                  },
                  {
                    "kind": "text",
                    "text": ", "
                  },
                  {
                    "identifier": "doc://com.apple.mediaaccessibility/documentation/MediaAccessibility/MACaptionAppearanceBehavior",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@E@MACaptionAppearanceBehavior",
                    "text": "MACaptionAppearanceBehavior"
                  },
                  {
                    "kind": "text",
                    "text": " * "
                  },
                  {
                    "kind": "internalParam",
                    "text": "behavior"
                  },
                  {
                    "kind": "text",
                    "text": ");"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/1",
          "value": {
            "kind": "parameters",
            "parameters": [
              {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "The domain to retrieve the preference value from. See ",
                        "type": "text"
                      },
                      {
                        "identifier": "doc://com.apple.mediaaccessibility/documentation/MediaAccessibility/MACaptionAppearanceDomain",
                        "isActive": true,
                        "type": "reference"
                      },
                      {
                        "text": ". Pass ",
                        "type": "text"
                      },
                      {
                        "identifier": "doc://com.apple.mediaaccessibility/documentation/MediaAccessibility/MACaptionAppearanceDomain/user",
                        "isActive": true,
                        "type": "reference"
                      },
                      {
                        "text": " unless the system defaults are needed for comparison.",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ],
                "name": "domain"
              },
              {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "A pointer to memory. On return, this memory holds the caption appearance behavior for this preference setting. For possible values see ",
                        "type": "text"
                      },
                      {
                        "identifier": "doc://com.apple.mediaaccessibility/documentation/MediaAccessibility/MACaptionAppearanceBehavior",
                        "isActive": true,
                        "type": "reference"
                      },
                      {
                        "text": ". Pass ",
                        "type": "text"
                      },
                      {
                        "code": "NULL",
                        "type": "codeVoice"
                      },
                      {
                        "text": " when you do not need the behavior setting.",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ],
                "name": "behavior"
              }
            ]
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaaccessibility~1documentation~1MediaAccessibility~1MACaptionAppearanceGetWindowOpacity(_:_:)/title",
          "value": "MACaptionAppearanceGetWindowOpacity"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaaccessibility~1documentation~1MediaAccessibility~1MACaptionAppearanceGetWindowOpacity(_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MACaptionAppearanceGetWindowOpacity"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaaccessibility~1documentation~1MediaAccessibility~1MACaptionAppearanceDomain/title",
          "value": "MACaptionAppearanceDomain"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaaccessibility~1documentation~1MediaAccessibility~1MACaptionAppearanceDomain/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MACaptionAppearanceDomain"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaaccessibility~1documentation~1MediaAccessibility~1MACaptionAppearanceDomain/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MACaptionAppearanceDomain"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaaccessibility~1documentation~1MediaAccessibility~1MACaptionAppearanceDomain~1user/title",
          "value": "kMACaptionAppearanceDomainUser"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaaccessibility~1documentation~1MediaAccessibility~1MACaptionAppearanceDomain~1user/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kMACaptionAppearanceDomainUser"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaaccessibility~1documentation~1MediaAccessibility~1MACaptionAppearanceCopyWindowColor(_:_:)/title",
          "value": "MACaptionAppearanceCopyWindowColor"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaaccessibility~1documentation~1MediaAccessibility~1MACaptionAppearanceCopyWindowColor(_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MACaptionAppearanceCopyWindowColor"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaaccessibility~1documentation~1MediaAccessibility~1MACaptionAppearanceGetWindowRoundedCornerRadius(_:_:)/title",
          "value": "MACaptionAppearanceGetWindowRoundedCornerRadius"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaaccessibility~1documentation~1MediaAccessibility~1MACaptionAppearanceGetWindowRoundedCornerRadius(_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MACaptionAppearanceGetWindowRoundedCornerRadius"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaaccessibility~1documentation~1MediaAccessibility~1MACaptionAppearanceBehavior/title",
          "value": "MACaptionAppearanceBehavior"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaaccessibility~1documentation~1MediaAccessibility~1MACaptionAppearanceBehavior/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MACaptionAppearanceBehavior"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaaccessibility~1documentation~1MediaAccessibility~1MACaptionAppearanceBehavior/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MACaptionAppearanceBehavior"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/mediaaccessibility/macaptionappearancegetwindowopacity(_:_:)"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/mediaaccessibility/macaptionappearancegetwindowopacity(_:_:)"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
