{
  "abstract": [
    {
      "text": "An object that reports the result of the flashing lights processor.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.mediaaccessibility/documentation/MediaAccessibility"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "occ",
    "url": "doc://com.apple.mediaaccessibility/documentation/MediaAccessibility/MAFlashingLightsProcessorResult"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(cs)MAFlashingLightsProcessorResult",
    "fragments": [
      {
        "kind": "identifier",
        "text": "MAFlashingLightsProcessorResult"
      }
    ],
    "modules": [
      {
        "name": "Media Accessibility"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "MAFlashingLightsProcessorResult"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "17.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "17.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "17.0",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "14.0",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "17.0",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Class",
    "symbolKind": "class",
    "title": "MAFlashingLightsProcessorResult"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "occ"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "@interface"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "MAFlashingLightsProcessorResult"
            },
            {
              "kind": "text",
              "text": " : "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSObject",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)NSObject",
              "text": "NSObject"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "An ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.mediaaccessibility/documentation/MediaAccessibility/MAFlashingLightsProcessorResult",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " object is the result of calling ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.mediaaccessibility/documentation/MediaAccessibility/MAFlashingLightsProcessor/processSurface:outSurface:timestamp:options:",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ". This object indicates whether the method successfully processed the input surface, the intensity of flashing lights in the input surface, and the amount of mitigation in the output surface.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.mediaaccessibility/documentation/MediaAccessibility": {
      "abstract": [
        {
          "text": "Make your app’s media more accessible by supporting people’s systemwide preferences for video and audio content.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.mediaaccessibility/documentation/MediaAccessibility",
      "kind": "symbol",
      "role": "collection",
      "title": "Media Accessibility",
      "type": "topic",
      "url": "/documentation/mediaaccessibility"
    },
    "doc://com.apple.mediaaccessibility/documentation/MediaAccessibility/MAFlashingLightsProcessor/OptionKey": {
      "abstract": [
        {
          "text": "Options for the flashing lights processor.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "OptionKey"
        }
      ],
      "identifier": "doc://com.apple.mediaaccessibility/documentation/MediaAccessibility/MAFlashingLightsProcessor/OptionKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "OptionKey"
        }
      ],
      "role": "symbol",
      "title": "MAFlashingLightsProcessor.OptionKey",
      "type": "topic",
      "url": "/documentation/mediaaccessibility/maflashinglightsprocessor/optionkey"
    },
    "doc://com.apple.mediaaccessibility/documentation/MediaAccessibility/MAFlashingLightsProcessor/processSurface:outSurface:timestamp:options:": {
      "abstract": [
        {
          "text": "Processes a surface by analyzing pixels for sequences of flashing lights and mitigates them by dimming the content.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "- "
        },
        {
          "kind": "identifier",
          "text": "processSurface:outSurface:timestamp:options:"
        }
      ],
      "identifier": "doc://com.apple.mediaaccessibility/documentation/MediaAccessibility/MAFlashingLightsProcessor/processSurface:outSurface:timestamp:options:",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "processSurface:outSurface:timestamp:options:"
        }
      ],
      "role": "symbol",
      "title": "processSurface:outSurface:timestamp:options:",
      "type": "topic",
      "url": "/documentation/mediaaccessibility/maflashinglightsprocessor/processsurface:outsurface:timestamp:options:"
    },
    "doc://com.apple.mediaaccessibility/documentation/MediaAccessibility/MAFlashingLightsProcessorResult": {
      "abstract": [
        {
          "text": "An object that reports the result of the flashing lights processor.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "MAFlashingLightsProcessorResult"
        }
      ],
      "identifier": "doc://com.apple.mediaaccessibility/documentation/MediaAccessibility/MAFlashingLightsProcessorResult",
      "kind": "symbol",
      "role": "symbol",
      "title": "MAFlashingLightsProcessorResult",
      "type": "topic",
      "url": "/documentation/mediaaccessibility/maflashinglightsprocessorresult"
    },
    "doc://com.apple.mediaaccessibility/documentation/MediaAccessibility/MAFlashingLightsProcessorResult/intensityLevel": {
      "abstract": [
        {
          "text": "The intensity of flashing lights in the input surface.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "intensityLevel"
        }
      ],
      "identifier": "doc://com.apple.mediaaccessibility/documentation/MediaAccessibility/MAFlashingLightsProcessorResult/intensityLevel",
      "kind": "symbol",
      "role": "symbol",
      "title": "intensityLevel",
      "type": "topic",
      "url": "/documentation/mediaaccessibility/maflashinglightsprocessorresult/intensitylevel"
    },
    "doc://com.apple.mediaaccessibility/documentation/MediaAccessibility/MAFlashingLightsProcessorResult/mitigationLevel": {
      "abstract": [
        {
          "text": "The amount of mitigation in the output surface.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "mitigationLevel"
        }
      ],
      "identifier": "doc://com.apple.mediaaccessibility/documentation/MediaAccessibility/MAFlashingLightsProcessorResult/mitigationLevel",
      "kind": "symbol",
      "role": "symbol",
      "title": "mitigationLevel",
      "type": "topic",
      "url": "/documentation/mediaaccessibility/maflashinglightsprocessorresult/mitigationlevel"
    },
    "doc://com.apple.mediaaccessibility/documentation/MediaAccessibility/MAFlashingLightsProcessorResult/surfaceProcessed": {
      "abstract": [
        {
          "text": "A Boolean value that indicates whether the flashing lights processor successfully processed the input surface.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "surfaceProcessed"
        }
      ],
      "identifier": "doc://com.apple.mediaaccessibility/documentation/MediaAccessibility/MAFlashingLightsProcessorResult/surfaceProcessed",
      "kind": "symbol",
      "role": "symbol",
      "title": "surfaceProcessed",
      "type": "topic",
      "url": "/documentation/mediaaccessibility/maflashinglightsprocessorresult/surfaceprocessed"
    },
    "doc://com.externally.resolved.symbol/c:objc(cs)NSObject": {
      "abstract": [
        {
          "text": "The root class of most Objective-C class hierarchies, from which subclasses inherit a basic interface to the runtime system and the ability to behave as Objective-C objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "class "
        },
        {
          "kind": "identifier",
          "text": "NSObject"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSObject",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSObject",
      "type": "topic",
      "url": "/documentation/objectivec/nsobject"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/c:objc(cs)NSObject"
      ],
      "kind": "relationships",
      "title": "Inherits From",
      "type": "inheritsFrom"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Processing-video-content",
      "generated": true,
      "identifiers": [
        "doc://com.apple.mediaaccessibility/documentation/MediaAccessibility/MAFlashingLightsProcessor/processSurface:outSurface:timestamp:options:",
        "doc://com.apple.mediaaccessibility/documentation/MediaAccessibility/MAFlashingLightsProcessor/OptionKey"
      ],
      "title": "Processing video content"
    }
  ],
  "topicSections": [
    {
      "anchor": "Interpreting-results-from-video-processing",
      "identifiers": [
        "doc://com.apple.mediaaccessibility/documentation/MediaAccessibility/MAFlashingLightsProcessorResult/surfaceProcessed",
        "doc://com.apple.mediaaccessibility/documentation/MediaAccessibility/MAFlashingLightsProcessorResult/intensityLevel",
        "doc://com.apple.mediaaccessibility/documentation/MediaAccessibility/MAFlashingLightsProcessorResult/mitigationLevel"
      ],
      "title": "Interpreting results from video processing"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaaccessibility~1documentation~1MediaAccessibility~1MAFlashingLightsProcessor~1OptionKey/title",
          "value": "MAFlashingLightsProcessorOptionKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaaccessibility~1documentation~1MediaAccessibility~1MAFlashingLightsProcessor~1OptionKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MAFlashingLightsProcessorOptionKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaaccessibility~1documentation~1MediaAccessibility~1MAFlashingLightsProcessor~1OptionKey/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MAFlashingLightsProcessorOptionKey"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/mediaaccessibility/maflashinglightsprocessorresult"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
