{
  "abstract": [
    {
      "text": "A media characteristic that indicates that a track includes legible content in the language of its specified locale that describes music and sound other than spoken dialog.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.mediaaccessibility/documentation/MediaAccessibility"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.mediaaccessibility/documentation/MediaAccessibility/MAMediaCharacteristicDescribesMusicAndSoundForAccessibility"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@MAMediaCharacteristicDescribesMusicAndSoundForAccessibility",
    "fragments": [
      {
        "kind": "keyword",
        "text": "let"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "MAMediaCharacteristicDescribesMusicAndSoundForAccessibility"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@T@CFStringRef",
        "text": "CFString"
      }
    ],
    "modules": [
      {
        "name": "Media Accessibility"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "MAMediaCharacteristicDescribesMusicAndSoundForAccessibility"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "7.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "7.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.1",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.9",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "17.0",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Global Variable",
    "symbolKind": "var",
    "title": "MAMediaCharacteristicDescribesMusicAndSoundForAccessibility"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "let"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "MAMediaCharacteristicDescribesMusicAndSoundForAccessibility"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/c:@T@CFStringRef",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@CFStringRef",
              "text": "CFString"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.mediaaccessibility/documentation/MediaAccessibility": {
      "abstract": [
        {
          "text": "Make your app’s media more accessible by supporting people’s systemwide preferences for video and audio content.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.mediaaccessibility/documentation/MediaAccessibility",
      "kind": "symbol",
      "role": "collection",
      "title": "Media Accessibility",
      "type": "topic",
      "url": "/documentation/mediaaccessibility"
    },
    "doc://com.apple.mediaaccessibility/documentation/MediaAccessibility/MAAudibleMediaCopyPreferredCharacteristics()": {
      "abstract": [
        {
          "text": "Returns the preference for audible media characteristics.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MAAudibleMediaCopyPreferredCharacteristics"
        },
        {
          "kind": "text",
          "text": "() -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s9UnmanagedV",
          "text": "Unmanaged"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFArrayRef",
          "text": "CFArray"
        },
        {
          "kind": "text",
          "text": ">"
        }
      ],
      "identifier": "doc://com.apple.mediaaccessibility/documentation/MediaAccessibility/MAAudibleMediaCopyPreferredCharacteristics()",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MAAudibleMediaCopyPreferredCharacteristics"
        }
      ],
      "role": "symbol",
      "title": "MAAudibleMediaCopyPreferredCharacteristics()",
      "type": "topic",
      "url": "/documentation/mediaaccessibility/maaudiblemediacopypreferredcharacteristics()"
    },
    "doc://com.apple.mediaaccessibility/documentation/MediaAccessibility/MAMediaCharacteristicDescribesMusicAndSoundForAccessibility": {
      "abstract": [
        {
          "text": "A media characteristic that indicates that a track includes legible content in the language of its specified locale that describes music and sound other than spoken dialog.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MAMediaCharacteristicDescribesMusicAndSoundForAccessibility"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.mediaaccessibility/documentation/MediaAccessibility/MAMediaCharacteristicDescribesMusicAndSoundForAccessibility",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MAMediaCharacteristicDescribesMusicAndSoundForAccessibility"
        }
      ],
      "role": "symbol",
      "title": "MAMediaCharacteristicDescribesMusicAndSoundForAccessibility",
      "type": "topic",
      "url": "/documentation/mediaaccessibility/mamediacharacteristicdescribesmusicandsoundforaccessibility"
    },
    "doc://com.apple.mediaaccessibility/documentation/MediaAccessibility/MAMediaCharacteristicDescribesVideoForAccessibility": {
      "abstract": [
        {
          "text": "A media characteristic that indicates that a track or media selection option includes audible content that describes a video for accessibility.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MAMediaCharacteristicDescribesVideoForAccessibility"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.mediaaccessibility/documentation/MediaAccessibility/MAMediaCharacteristicDescribesVideoForAccessibility",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MAMediaCharacteristicDescribesVideoForAccessibility"
        }
      ],
      "role": "symbol",
      "title": "MAMediaCharacteristicDescribesVideoForAccessibility",
      "type": "topic",
      "url": "/documentation/mediaaccessibility/mamediacharacteristicdescribesvideoforaccessibility"
    },
    "doc://com.apple.mediaaccessibility/documentation/MediaAccessibility/MAMediaCharacteristicTranscribesSpokenDialogForAccessibility": {
      "abstract": [
        {
          "text": "A media characteristic that indicates that a track includes legible content in the language of its specified locale that transcribes spoken dialog and identifies the speakers.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MAMediaCharacteristicTranscribesSpokenDialogForAccessibility"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.mediaaccessibility/documentation/MediaAccessibility/MAMediaCharacteristicTranscribesSpokenDialogForAccessibility",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MAMediaCharacteristicTranscribesSpokenDialogForAccessibility"
        }
      ],
      "role": "symbol",
      "title": "MAMediaCharacteristicTranscribesSpokenDialogForAccessibility",
      "type": "topic",
      "url": "/documentation/mediaaccessibility/mamediacharacteristictranscribesspokendialogforaccessibility"
    },
    "doc://com.apple.mediaaccessibility/documentation/MediaAccessibility/kMAAudibleMediaSettingsChangedNotification": {
      "abstract": [
        {
          "text": "A notification that occurs when any user-defined audible media settings change.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kMAAudibleMediaSettingsChangedNotification"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.mediaaccessibility/documentation/MediaAccessibility/kMAAudibleMediaSettingsChangedNotification",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kMAAudibleMediaSettingsChangedNotification"
        }
      ],
      "role": "symbol",
      "title": "kMAAudibleMediaSettingsChangedNotification",
      "type": "topic",
      "url": "/documentation/mediaaccessibility/kmaaudiblemediasettingschangednotification"
    },
    "doc://com.externally.resolved.symbol/c:@T@CFStringRef": {
      "abstract": [
        {
          "text": "A reference to a CFString object.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "class "
        },
        {
          "kind": "identifier",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:@T@CFStringRef",
      "kind": "symbol",
      "role": "symbol",
      "title": "CFString",
      "type": "topic",
      "url": "/documentation/corefoundation/cfstring"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Audible-media-selection-settings",
      "generated": true,
      "identifiers": [
        "doc://com.apple.mediaaccessibility/documentation/MediaAccessibility/kMAAudibleMediaSettingsChangedNotification",
        "doc://com.apple.mediaaccessibility/documentation/MediaAccessibility/MAAudibleMediaCopyPreferredCharacteristics()",
        "doc://com.apple.mediaaccessibility/documentation/MediaAccessibility/MAMediaCharacteristicDescribesVideoForAccessibility",
        "doc://com.apple.mediaaccessibility/documentation/MediaAccessibility/MAMediaCharacteristicTranscribesSpokenDialogForAccessibility"
      ],
      "title": "Audible media selection settings"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "7.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "7.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.1",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.9",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "17.0",
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Global Variable"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "MAMediaCharacteristicDescribesMusicAndSoundForAccessibility"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "var"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MAMediaCharacteristicDescribesMusicAndSoundForAccessibility"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.mediaaccessibility/documentation/MediaAccessibility"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Audible-media-selection-settings",
              "generated": true,
              "identifiers": [
                "doc://com.apple.mediaaccessibility/documentation/MediaAccessibility/kMAAudibleMediaSettingsChangedNotification",
                "doc://com.apple.mediaaccessibility/documentation/MediaAccessibility/MAAudibleMediaCopyPreferredCharacteristics()",
                "doc://com.apple.mediaaccessibility/documentation/MediaAccessibility/MAMediaCharacteristicDescribesVideoForAccessibility",
                "doc://com.apple.mediaaccessibility/documentation/MediaAccessibility/MAMediaCharacteristicTranscribesSpokenDialogForAccessibility"
              ],
              "title": "Audible media selection settings"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "extern"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:@T@CFStringRef",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@CFStringRef",
                    "text": "CFStringRef"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "keyword",
                    "text": "const"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "MAMediaCharacteristicDescribesMusicAndSoundForAccessibility"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaaccessibility~1documentation~1MediaAccessibility~1kMAAudibleMediaSettingsChangedNotification/title",
          "value": "kMAAudibleMediaSettingsChangedNotification"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaaccessibility~1documentation~1MediaAccessibility~1kMAAudibleMediaSettingsChangedNotification/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kMAAudibleMediaSettingsChangedNotification"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaaccessibility~1documentation~1MediaAccessibility~1MAMediaCharacteristicDescribesVideoForAccessibility/title",
          "value": "MAMediaCharacteristicDescribesVideoForAccessibility"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaaccessibility~1documentation~1MediaAccessibility~1MAMediaCharacteristicDescribesVideoForAccessibility/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MAMediaCharacteristicDescribesVideoForAccessibility"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaaccessibility~1documentation~1MediaAccessibility~1MAMediaCharacteristicTranscribesSpokenDialogForAccessibility/title",
          "value": "MAMediaCharacteristicTranscribesSpokenDialogForAccessibility"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaaccessibility~1documentation~1MediaAccessibility~1MAMediaCharacteristicTranscribesSpokenDialogForAccessibility/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MAMediaCharacteristicTranscribesSpokenDialogForAccessibility"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaaccessibility~1documentation~1MediaAccessibility~1MAMediaCharacteristicDescribesMusicAndSoundForAccessibility/title",
          "value": "MAMediaCharacteristicDescribesMusicAndSoundForAccessibility"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaaccessibility~1documentation~1MediaAccessibility~1MAMediaCharacteristicDescribesMusicAndSoundForAccessibility/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MAMediaCharacteristicDescribesMusicAndSoundForAccessibility"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:@T@CFStringRef/title",
          "value": "CFStringRef"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaaccessibility~1documentation~1MediaAccessibility~1MAAudibleMediaCopyPreferredCharacteristics()/title",
          "value": "MAAudibleMediaCopyPreferredCharacteristics"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaaccessibility~1documentation~1MediaAccessibility~1MAAudibleMediaCopyPreferredCharacteristics()/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MAAudibleMediaCopyPreferredCharacteristics"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/mediaaccessibility/mamediacharacteristicdescribesmusicandsoundforaccessibility"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/mediaaccessibility/mamediacharacteristicdescribesmusicandsoundforaccessibility"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
