{
  "abstract": [
    {
      "text": "Adjust your UI when a person chooses to dim flashing lights on their Apple device.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.mediaaccessibility/documentation/MediaAccessibility",
        "doc://com.apple.mediaaccessibility/documentation/MediaAccessibility/flashing-lights"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.mediaaccessibility/documentation/MediaAccessibility/responding-to-changes-in-the-flashing-lights-setting"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "Media Accessibility"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "introducedAt": "16.4",
        "name": "iOS"
      },
      {
        "beta": false,
        "introducedAt": "16.4",
        "name": "iPadOS"
      },
      {
        "beta": false,
        "introducedAt": "14.3",
        "name": "Xcode"
      }
    ],
    "role": "sampleCode",
    "roleHeading": "Sample Code",
    "title": "Responding to changes in the flashing lights setting"
  },
  "primaryContentSections": [
    {
      "content": [
        {
          "anchor": "Overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Dim Flashing Lights is a setting that allows a person to indicate that they want",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "to avoid bright, frequent flashes of light on their Apple device. When a person",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "turns on this setting, the device automatically dims video content",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "when the system detects flashing or strobing effects.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "In your app, you can check the current value of this setting and make any",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "necessary adjustments to your UI when the value changes. For example, this",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "sample code project demonstrates how to draw a custom media timeline that",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "indicates which portions of a video contain flashing lights.",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "For other examples of changes you might make in your UI in response to this",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "setting, read",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.mediaaccessibility/documentation/MediaAccessibility/flashing-lights",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ".",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "This sample code project includes a sample video that contains",
                  "type": "text"
                },
                {
                  "text": " ",
                  "type": "text"
                },
                {
                  "text": "sequences of flashing effects.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "Important",
          "style": "important",
          "type": "aside"
        },
        {
          "anchor": "Configure-the-sample-code-project",
          "level": 3,
          "text": "Configure the sample code project",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "This sample code project relies on changes to a system setting. To observe a",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "change in the sample app’s UI, change the value of the Dim Flashing Lights setting",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "at any time, and return to the app to observe how the UI responds.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "To change the setting, open Settings > Accessibility > Motion and turn on",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "Dim Flashing Lights.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "anchor": "Play-the-video-with-dimmed-flashing",
          "level": 3,
          "text": "Play the video with dimmed flashing",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "With Dim Flashing Lights on, play the sample video in the video player.",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "The sample app shows a custom media timeline below the video in the",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/AVFoundation/AVPlayer",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ".",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "This timeline annotates the segments of the sample video that present a high risk",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "of flashing lights.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "code": [
            "ForEach(videoFlashingTimes, id: \\.self) { timeRange in",
            "    // Draws red rectangles to indicate which segments of the video",
            "    // contain flashing light effects. The position relies on the",
            "    // start and end times of each segment in `videoFlashingTimes`.",
            "    RoundedRectangle(cornerRadius: 2)",
            "        .fill(.red)",
            "        .position(x: (timeRange[0] * width) + ((timeRange[1] * width) - (timeRange[0] * width)) / 2)",
            "        .frame(width: (timeRange[1] * width) - (timeRange[0] * width), height: 10)",
            "}"
          ],
          "syntax": "swift",
          "type": "codeListing"
        },
        {
          "inlineContent": [
            {
              "identifier": "x-source-tag://FlashingTimelineView",
              "isActive": true,
              "type": "reference"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "When the video playback reaches one of those segments,",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "the system automatically dims the video to reduce the flashing effects.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "anchor": "Register-for-changes-in-the-flashing-lights-setting",
          "level": 3,
          "text": "Register for changes in the flashing lights setting",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "This sample app draws the custom media timeline only when the Dim Flashing",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "Lights setting is on, which the app determines through a system notification.",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "First, the app imports the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.mediaaccessibility/documentation/MediaAccessibility",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "framework to interact with the API.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "code": [
            "import MediaAccessibility"
          ],
          "syntax": "swift",
          "type": "codeListing"
        },
        {
          "inlineContent": [
            {
              "text": "Then, it registers to receive the",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.mediaaccessibility/documentation/MediaAccessibility/kMADimFlashingLightsChangedNotification",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "notification, which the system sends when a person turns the setting on or off.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "code": [
            "// Registers for the system notification that posts when the value of",
            "// the Dim Flashing Lights setting changes.",
            "NotificationCenter.default.addObserver(self,",
            "    selector: #selector(dimFlashingLightsChanged),",
            "    name: kMADimFlashingLightsChangedNotification as NSNotification.Name,",
            "    object: nil)"
          ],
          "syntax": "swift",
          "type": "codeListing"
        },
        {
          "inlineContent": [
            {
              "identifier": "x-source-tag://RegisterForNotification",
              "isActive": true,
              "type": "reference"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "When the app receives the",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.mediaaccessibility/documentation/MediaAccessibility/kMADimFlashingLightsChangedNotification",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "notification, it sets the variable ",
              "type": "text"
            },
            {
              "code": "dimFlashingLightsStatus",
              "type": "codeVoice"
            },
            {
              "text": " to the current",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "value of the system setting, which the system reports through",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.mediaaccessibility/documentation/MediaAccessibility/MADimFlashingLightsEnabled()",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ".",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "code": [
            "@objc",
            "func dimFlashingLightsChanged(_ notification: Notification) {",
            "    // Updates `dimFlashingLightsStatus` to the new value of the",
            "    // Dim Flashing Light setting.",
            "    dimFlashingLightsStatus = MADimFlashingLightsEnabled()",
            "}"
          ],
          "syntax": "swift",
          "type": "codeListing"
        },
        {
          "inlineContent": [
            {
              "identifier": "x-source-tag://SettingChanged",
              "isActive": true,
              "type": "reference"
            }
          ],
          "type": "paragraph"
        },
        {
          "anchor": "Draw-the-custom-media-timeline-if-the-setting-is-on",
          "level": 3,
          "text": "Draw the custom media timeline if the setting is on",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "When the app draws its UI, it checks the value of the current setting status,",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "code": "dimFlashingLightsStatus",
              "type": "codeVoice"
            },
            {
              "text": ", to determine whether to draw the custom media timeline.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "code": [
            "// Checks the status of the Dim Flashing Lights setting to determine",
            "// whether to draw the custom media timeline.",
            "if playerManager.dimFlashingLightsStatus {",
            "    VStack {",
            "        Text(\"Custom Media Timeline\")",
            "            .font(.title2)",
            "            .padding(.bottom)",
            "        GeometryReader { proxy in",
            "            // Draws a timeline view that's the same width as the",
            "            // video player.",
            "            FlashingTimelineView(proxy.size.width)",
            "            ",
            "            // Draws a custom playback indicator on top of the",
            "            // timeline view.",
            "            RoundedRectangle(cornerRadius: 2)",
            "                .fill(.black)",
            "                .border(.white)",
            "                .position(x: playerManager.playbackPercentage * proxy.size.width)",
            "                .frame(width: 9, height: 9)",
            "        }",
            "    }",
            "    .padding(.top)",
            "}"
          ],
          "syntax": "swift",
          "type": "codeListing"
        },
        {
          "inlineContent": [
            {
              "identifier": "x-source-tag://CreateUI",
              "isActive": true,
              "type": "reference"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "If you turn the setting off, the sample app’s UI updates to remove the custom",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "media timeline.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "04a9293f1d3b/RespondingToChangesInTheFlashingLightsSetting.zip": {
      "checksum": "04a9293f1d3b81c2ec0b7d910ac6eb6100993be30b0d87fe60e4a351db92d5e167137e89e5aabb8e37421c087f146648ccecbda22c5dc1f8e9ea8dcc02b7f898",
      "identifier": "04a9293f1d3b/RespondingToChangesInTheFlashingLightsSetting.zip",
      "type": "download",
      "url": "https://docs-assets.developer.apple.com/published/04a9293f1d3b/RespondingToChangesInTheFlashingLightsSetting.zip"
    },
    "doc://com.apple.documentation/documentation/AVFoundation/AVPlayer": {
      "abstract": [
        {
          "text": "An object that provides the interface to control the player’s transport behavior.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@"
        },
        {
          "kind": "attribute",
          "preciseIdentifier": "s:ScM",
          "text": "MainActor"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AVPlayer"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/AVFoundation/AVPlayer",
      "kind": "symbol",
      "role": "symbol",
      "title": "AVPlayer",
      "type": "topic",
      "url": "/documentation/AVFoundation/AVPlayer"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.mediaaccessibility/documentation/MediaAccessibility": {
      "abstract": [
        {
          "text": "Make your app’s media more accessible by supporting people’s systemwide preferences for video and audio content.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.mediaaccessibility/documentation/MediaAccessibility",
      "kind": "symbol",
      "role": "collection",
      "title": "Media Accessibility",
      "type": "topic",
      "url": "/documentation/mediaaccessibility"
    },
    "doc://com.apple.mediaaccessibility/documentation/MediaAccessibility/MADimFlashingLightsEnabled()": {
      "abstract": [
        {
          "text": "Returns a Boolean value that indicates whether the flashing lights setting is enabled on the device.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MADimFlashingLightsEnabled"
        },
        {
          "kind": "text",
          "text": "() -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.mediaaccessibility/documentation/MediaAccessibility/MADimFlashingLightsEnabled()",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MADimFlashingLightsEnabled"
        }
      ],
      "role": "symbol",
      "title": "MADimFlashingLightsEnabled()",
      "type": "topic",
      "url": "/documentation/mediaaccessibility/madimflashinglightsenabled()"
    },
    "doc://com.apple.mediaaccessibility/documentation/MediaAccessibility/MAFlashingLightsProcessor": {
      "abstract": [
        {
          "text": "A class that processes a framebuffer object to detect and dim sequences of flashing lights.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MAFlashingLightsProcessor"
        }
      ],
      "identifier": "doc://com.apple.mediaaccessibility/documentation/MediaAccessibility/MAFlashingLightsProcessor",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MAFlashingLightsProcessor"
        }
      ],
      "role": "symbol",
      "title": "MAFlashingLightsProcessor",
      "type": "topic",
      "url": "/documentation/mediaaccessibility/maflashinglightsprocessor"
    },
    "doc://com.apple.mediaaccessibility/documentation/MediaAccessibility/flashing-lights": {
      "abstract": [
        {
          "text": "Detect, mitigate, and inform people about flashing lights in media content.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.mediaaccessibility/documentation/MediaAccessibility/flashing-lights",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Flashing lights",
      "type": "topic",
      "url": "/documentation/mediaaccessibility/flashing-lights"
    },
    "doc://com.apple.mediaaccessibility/documentation/MediaAccessibility/kMADimFlashingLightsChangedNotification": {
      "abstract": [
        {
          "text": "A notification that posts when a person changes the flashing lights setting on the device.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kMADimFlashingLightsChangedNotification"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.mediaaccessibility/documentation/MediaAccessibility/kMADimFlashingLightsChangedNotification",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kMADimFlashingLightsChangedNotification"
        }
      ],
      "role": "symbol",
      "title": "kMADimFlashingLightsChangedNotification",
      "type": "topic",
      "url": "/documentation/mediaaccessibility/kmadimflashinglightschangednotification"
    },
    "x-source-tag://CreateUI": {
      "identifier": "x-source-tag://CreateUI",
      "title": "View in Source",
      "titleInlineContent": [
        {
          "text": "View in Source",
          "type": "text"
        }
      ],
      "type": "link",
      "url": "x-source-tag://CreateUI"
    },
    "x-source-tag://FlashingTimelineView": {
      "identifier": "x-source-tag://FlashingTimelineView",
      "title": "View in Source",
      "titleInlineContent": [
        {
          "text": "View in Source",
          "type": "text"
        }
      ],
      "type": "link",
      "url": "x-source-tag://FlashingTimelineView"
    },
    "x-source-tag://RegisterForNotification": {
      "identifier": "x-source-tag://RegisterForNotification",
      "title": "View in Source",
      "titleInlineContent": [
        {
          "text": "View in Source",
          "type": "text"
        }
      ],
      "type": "link",
      "url": "x-source-tag://RegisterForNotification"
    },
    "x-source-tag://SettingChanged": {
      "identifier": "x-source-tag://SettingChanged",
      "title": "View in Source",
      "titleInlineContent": [
        {
          "text": "View in Source",
          "type": "text"
        }
      ],
      "type": "link",
      "url": "x-source-tag://SettingChanged"
    }
  },
  "sampleCodeDownload": {
    "action": {
      "identifier": "04a9293f1d3b/RespondingToChangesInTheFlashingLightsSetting.zip",
      "isActive": true,
      "overridingTitle": "Download",
      "type": "reference"
    },
    "kind": "sampleDownload"
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Dim-flashing-lights",
      "generated": true,
      "identifiers": [
        "doc://com.apple.mediaaccessibility/documentation/MediaAccessibility/MADimFlashingLightsEnabled()",
        "doc://com.apple.mediaaccessibility/documentation/MediaAccessibility/kMADimFlashingLightsChangedNotification",
        "doc://com.apple.mediaaccessibility/documentation/MediaAccessibility/MAFlashingLightsProcessor"
      ],
      "title": "Dim flashing lights"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaaccessibility~1documentation~1MediaAccessibility~1MAFlashingLightsProcessor/title",
          "value": "MAFlashingLightsProcessor"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaaccessibility~1documentation~1MediaAccessibility~1MAFlashingLightsProcessor/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MAFlashingLightsProcessor"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaaccessibility~1documentation~1MediaAccessibility~1MAFlashingLightsProcessor/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MAFlashingLightsProcessor"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1AVFoundation~1AVPlayer/fragments",
          "value": [
            {
              "kind": "keyword",
              "text": "@interface"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "AVPlayer"
            },
            {
              "kind": "text",
              "text": " : "
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)NSObject",
              "text": "NSObject"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaaccessibility~1documentation~1MediaAccessibility~1kMADimFlashingLightsChangedNotification/title",
          "value": "kMADimFlashingLightsChangedNotification"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaaccessibility~1documentation~1MediaAccessibility~1kMADimFlashingLightsChangedNotification/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kMADimFlashingLightsChangedNotification"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaaccessibility~1documentation~1MediaAccessibility~1MADimFlashingLightsEnabled()/title",
          "value": "MADimFlashingLightsEnabled"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaaccessibility~1documentation~1MediaAccessibility~1MADimFlashingLightsEnabled()/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MADimFlashingLightsEnabled"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/mediaaccessibility/responding-to-changes-in-the-flashing-lights-setting"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    }
  ]
}
