{"sections":[],"hierarchy":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.corebluetooth/documentation/CoreBluetooth","doc://com.apple.corebluetooth/documentation/CoreBluetooth/CBCentralManager"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"registerForConnectionEvents"},{"kind":"text","text":"("},{"kind":"externalParam","text":"options"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","identifier":"doc://com.apple.corebluetooth/documentation/CoreBluetooth/CBConnectionEventMatchingOption","text":"CBConnectionEventMatchingOption","preciseIdentifier":"c:@T@CBConnectionEventMatchingOption"},{"kind":"text","text":" : "},{"kind":"keyword","text":"Any"},{"kind":"text","text":"]? = nil)"}],"languages":["swift"],"platforms":["iOS","iPadOS","Mac Catalyst","tvOS","visionOS","watchOS"]}]},{"kind":"parameters","parameters":[{"name":"options","content":[{"inlineContent":[{"type":"text","text":"A dictionary that specifies options for connection events. See "},{"type":"reference","identifier":"doc://com.apple.corebluetooth/documentation/CoreBluetooth/peripheral-connection-options","isActive":true},{"type":"text","text":" for a list of possible options."}],"type":"paragraph"}]}]},{"kind":"content","content":[{"text":"Discussion","level":2,"type":"heading","anchor":"Discussion"},{"inlineContent":[{"type":"text","text":"When the central manager makes a connection that matches the options, it calls the delegate’s "},{"isActive":true,"type":"reference","identifier":"doc://com.apple.corebluetooth/documentation/CoreBluetooth/CBCentralManagerDelegate/centralManager(_:connectionEventDidOccur:for:)"},{"type":"text","text":" method."}],"type":"paragraph"}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"variants":[{"paths":["/documentation/corebluetooth/cbcentralmanager/registerforconnectionevents(options:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["/documentation/corebluetooth/cbcentralmanager/registerforconnectionevents(options:)"],"traits":[{"interfaceLanguage":"occ"}]}],"kind":"symbol","abstract":[{"type":"text","text":"Register for an event notification when the central manager makes a connection matching the given options."}],"seeAlsoSections":[{"generated":true,"anchor":"Receiving-Connection-Events","identifiers":["doc://com.apple.corebluetooth/documentation/CoreBluetooth/peripheral-connection-options","doc://com.apple.corebluetooth/documentation/CoreBluetooth/CBConnectionEvent","doc://com.apple.corebluetooth/documentation/CoreBluetooth/CBConnectionEventMatchingOption"],"title":"Receiving Connection Events"}],"metadata":{"modules":[{"name":"Core Bluetooth"}],"roleHeading":"Instance Method","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"registerForConnectionEvents","kind":"identifier"},{"text":"(","kind":"text"},{"text":"options","kind":"externalParam"},{"text":": [","kind":"text"},{"text":"CBConnectionEventMatchingOption","preciseIdentifier":"c:@T@CBConnectionEventMatchingOption","kind":"typeIdentifier"},{"text":" : ","kind":"text"},{"text":"Any","kind":"keyword"},{"text":"]?)","kind":"text"}],"title":"registerForConnectionEvents(options:)","symbolKind":"method","externalID":"c:objc(cs)CBCentralManager(im)registerForConnectionEventsWithOptions:","navigatorTitle":[{"text":"registerForConnectionEventsWithOptions:","kind":"identifier"}],"role":"symbol","platforms":[{"deprecated":false,"unavailable":false,"beta":false,"name":"iOS","introducedAt":"13.0"},{"deprecated":false,"unavailable":false,"introducedAt":"13.0","beta":false,"name":"iPadOS"},{"deprecated":false,"unavailable":false,"introducedAt":"13.1","beta":false,"name":"Mac Catalyst"},{"deprecated":false,"unavailable":false,"introducedAt":"13.0","beta":false,"name":"tvOS"},{"deprecated":false,"unavailable":false,"introducedAt":"1.0","beta":false,"name":"visionOS"},{"deprecated":false,"unavailable":false,"introducedAt":"6.0","beta":false,"name":"watchOS"}]},"identifier":{"interfaceLanguage":"swift","url":"doc://com.apple.corebluetooth/documentation/CoreBluetooth/CBCentralManager/registerForConnectionEvents(options:)"},"references":{"doc://com.apple.corebluetooth/documentation/CoreBluetooth/CBConnectionEvent":{"navigatorTitle":[{"kind":"identifier","text":"CBConnectionEvent"}],"role":"symbol","url":"/documentation/corebluetooth/cbconnectionevent","identifier":"doc://com.apple.corebluetooth/documentation/CoreBluetooth/CBConnectionEvent","abstract":[{"type":"text","text":"A change to the connection state of a peer."}],"kind":"symbol","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"CBConnectionEvent"}],"title":"CBConnectionEvent","type":"topic"},"doc://com.apple.corebluetooth/documentation/CoreBluetooth/CBConnectionEventMatchingOption":{"type":"topic","url":"/documentation/corebluetooth/cbconnectioneventmatchingoption","identifier":"doc://com.apple.corebluetooth/documentation/CoreBluetooth/CBConnectionEventMatchingOption","navigatorTitle":[{"kind":"identifier","text":"CBConnectionEventMatchingOption"}],"title":"CBConnectionEventMatchingOption","kind":"symbol","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"CBConnectionEventMatchingOption"}],"abstract":[{"type":"text","text":"A set of options to use when registering for connection events."}],"role":"symbol"},"doc://com.apple.documentation/documentation/technologies":{"abstract":[{"text":"","type":"text"}],"identifier":"doc://com.apple.documentation/documentation/technologies","kind":"technologies","type":"topic","title":"Technologies","role":"overview","url":"/documentation/technologies"},"doc://com.apple.corebluetooth/documentation/CoreBluetooth":{"title":"Core Bluetooth","abstract":[{"text":"Communicate with Bluetooth low energy and BR/EDR (“Classic”) Devices.","type":"text"}],"url":"/documentation/corebluetooth","kind":"symbol","type":"topic","role":"collection","identifier":"doc://com.apple.corebluetooth/documentation/CoreBluetooth"},"doc://com.apple.corebluetooth/documentation/CoreBluetooth/CBCentralManager/registerForConnectionEvents(options:)":{"type":"topic","url":"/documentation/corebluetooth/cbcentralmanager/registerforconnectionevents(options:)","identifier":"doc://com.apple.corebluetooth/documentation/CoreBluetooth/CBCentralManager/registerForConnectionEvents(options:)","navigatorTitle":[{"text":"registerForConnectionEventsWithOptions:","kind":"identifier"}],"title":"registerForConnectionEvents(options:)","kind":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"registerForConnectionEvents"},{"kind":"text","text":"("},{"kind":"externalParam","text":"options"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@CBConnectionEventMatchingOption","text":"CBConnectionEventMatchingOption"},{"kind":"text","text":" : "},{"kind":"keyword","text":"Any"},{"kind":"text","text":"]?)"}],"abstract":[{"type":"text","text":"Register for an event notification when the central manager makes a connection matching the given options."}],"role":"symbol"},"doc://com.apple.corebluetooth/documentation/CoreBluetooth/CBCentralManager":{"title":"CBCentralManager","type":"topic","kind":"symbol","navigatorTitle":[{"text":"CBCentralManager","kind":"identifier"}],"url":"/documentation/corebluetooth/cbcentralmanager","identifier":"doc://com.apple.corebluetooth/documentation/CoreBluetooth/CBCentralManager","abstract":[{"text":"An object that scans for, discovers, connects to, and manages peripherals.","type":"text"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"CBCentralManager","kind":"identifier"}],"role":"symbol"},"doc://com.apple.corebluetooth/documentation/CoreBluetooth/peripheral-connection-options":{"type":"topic","url":"/documentation/corebluetooth/peripheral-connection-options","identifier":"doc://com.apple.corebluetooth/documentation/CoreBluetooth/peripheral-connection-options","title":"Peripheral Connection Options","kind":"article","abstract":[{"type":"text","text":"Keys used to pass options when connecting to a peripheral."}],"role":"collectionGroup"},"doc://com.apple.corebluetooth/documentation/CoreBluetooth/CBCentralManagerDelegate/centralManager(_:connectionEventDidOccur:for:)":{"type":"topic","url":"/documentation/corebluetooth/cbcentralmanagerdelegate/centralmanager(_:connectioneventdidoccur:for:)","identifier":"doc://com.apple.corebluetooth/documentation/CoreBluetooth/CBCentralManagerDelegate/centralManager(_:connectionEventDidOccur:for:)","navigatorTitle":[{"text":"centralManager:connectionEventDidOccur:forPeripheral:","kind":"identifier"}],"title":"centralManager(_:connectionEventDidOccur:for:)","kind":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"centralManager"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)CBCentralManager","text":"CBCentralManager"},{"kind":"text","text":", "},{"kind":"externalParam","text":"connectionEventDidOccur"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@E@CBConnectionEvent","text":"CBConnectionEvent"},{"kind":"text","text":", "},{"text":"for","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"CBPeripheral","preciseIdentifier":"c:objc(cs)CBPeripheral","kind":"typeIdentifier"},{"text":")","kind":"text"}],"abstract":[{"type":"text","text":"Tells the delegate that a connection event occurred which matches the registered options."}],"role":"symbol"}},"variantOverrides":[{"patch":[{"path":"/identifier/interfaceLanguage","value":"occ","op":"replace"},{"path":"/metadata/platforms","value":[{"deprecated":false,"name":"iOS","beta":false,"unavailable":false,"introducedAt":"13.0"},{"deprecated":false,"name":"iPadOS","beta":false,"unavailable":false,"introducedAt":"13.0"},{"deprecated":false,"name":"Mac Catalyst","beta":false,"unavailable":false,"introducedAt":"13.1"},{"deprecated":false,"name":"tvOS","beta":false,"unavailable":false,"introducedAt":"13.0"},{"deprecated":false,"name":"visionOS","beta":false,"unavailable":false,"introducedAt":"1.0"},{"unavailable":false,"introducedAt":"6.0","deprecated":false,"name":"watchOS","beta":false}],"op":"replace"},{"path":"/metadata/roleHeading","value":"Instance Method","op":"replace"},{"path":"/metadata/title","value":"registerForConnectionEventsWithOptions:","op":"replace"},{"path":"/metadata/symbolKind","value":"method","op":"replace"},{"path":"/metadata/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"registerForConnectionEventsWithOptions:"}],"op":"replace"},{"path":"/hierarchy","value":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.corebluetooth/documentation/CoreBluetooth","doc://com.apple.corebluetooth/documentation/CoreBluetooth/CBCentralManager"]]},"op":"replace"},{"path":"/topicSections","value":null,"op":"add"},{"path":"/relationshipsSections","value":null,"op":"add"},{"path":"/seeAlsoSections","value":[{"generated":true,"anchor":"Receiving-Connection-Events","title":"Receiving Connection Events","identifiers":["doc://com.apple.corebluetooth/documentation/CoreBluetooth/peripheral-connection-options","doc://com.apple.corebluetooth/documentation/CoreBluetooth/CBConnectionEvent","doc://com.apple.corebluetooth/documentation/CoreBluetooth/CBConnectionEventMatchingOption"]}],"op":"replace"},{"path":"/primaryContentSections/0","value":{"declarations":[{"tokens":[{"text":"- (","kind":"text"},{"preciseIdentifier":"c:v","text":"void","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"registerForConnectionEventsWithOptions:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSDictionary<NSString *,id>","preciseIdentifier":"c:Q$objc(cs)NSDictionary","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"options","kind":"internalParam"},{"text":";","kind":"text"}],"languages":["occ"],"platforms":["iOS","iPadOS","Mac Catalyst","macOS","tvOS","visionOS","watchOS"]}],"kind":"declarations"},"op":"replace"},{"value":{"parameters":[{"content":[{"type":"paragraph","inlineContent":[{"text":"A dictionary that specifies options for connection events. See ","type":"text"},{"isActive":true,"type":"reference","identifier":"doc://com.apple.corebluetooth/documentation/CoreBluetooth/peripheral-connection-options"},{"text":" for a list of possible options.","type":"text"}]}],"name":"options"}],"kind":"parameters"},"path":"/primaryContentSections/1","op":"replace"},{"path":"/references/doc:~1~1com.apple.corebluetooth~1documentation~1CoreBluetooth~1CBConnectionEvent/title","value":"CBConnectionEvent","op":"replace"},{"path":"/references/doc:~1~1com.apple.corebluetooth~1documentation~1CoreBluetooth~1CBConnectionEvent/fragments","value":[{"kind":"identifier","text":"CBConnectionEvent"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.corebluetooth~1documentation~1CoreBluetooth~1CBConnectionEvent/navigatorTitle","value":[{"kind":"identifier","text":"CBConnectionEvent"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.corebluetooth~1documentation~1CoreBluetooth~1CBConnectionEventMatchingOption/title","value":"CBConnectionEventMatchingOption","op":"replace"},{"path":"/references/doc:~1~1com.apple.corebluetooth~1documentation~1CoreBluetooth~1CBConnectionEventMatchingOption/fragments","value":[{"text":"CBConnectionEventMatchingOption","kind":"identifier"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.corebluetooth~1documentation~1CoreBluetooth~1CBConnectionEventMatchingOption/navigatorTitle","value":[{"text":"CBConnectionEventMatchingOption","kind":"identifier"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.corebluetooth~1documentation~1CoreBluetooth~1CBCentralManager~1registerForConnectionEvents(options:)/title","value":"registerForConnectionEventsWithOptions:","op":"replace"},{"path":"/references/doc:~1~1com.apple.corebluetooth~1documentation~1CoreBluetooth~1CBCentralManager~1registerForConnectionEvents(options:)/fragments","value":[{"text":"- ","kind":"text"},{"text":"registerForConnectionEventsWithOptions:","kind":"identifier"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.corebluetooth~1documentation~1CoreBluetooth~1CBCentralManager/title","value":"CBCentralManager","op":"replace"},{"path":"/references/doc:~1~1com.apple.corebluetooth~1documentation~1CoreBluetooth~1CBCentralManager/fragments","value":[{"text":"CBCentralManager","kind":"identifier"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.corebluetooth~1documentation~1CoreBluetooth~1CBCentralManager/navigatorTitle","value":[{"kind":"identifier","text":"CBCentralManager"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.corebluetooth~1documentation~1CoreBluetooth~1CBCentralManagerDelegate~1centralManager(_:connectionEventDidOccur:for:)/title","value":"centralManager:connectionEventDidOccur:forPeripheral:","op":"replace"},{"path":"/references/doc:~1~1com.apple.corebluetooth~1documentation~1CoreBluetooth~1CBCentralManagerDelegate~1centralManager(_:connectionEventDidOccur:for:)/fragments","value":[{"text":"- ","kind":"text"},{"text":"centralManager:connectionEventDidOccur:forPeripheral:","kind":"identifier"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}],"legalNotices":{"copyright":"Copyright &copy; 2025 Apple Inc. All rights reserved.","termsOfUse":"https://www.apple.com/legal/internet-services/terms/site.html","privacyPolicy":"https://www.apple.com/privacy/privacy-policy"}}