{"metadata":{"modules":[{"name":"Core Bluetooth"}],"role":"symbol","platforms":[{"deprecated":false,"unavailable":false,"name":"iOS","beta":false,"introducedAt":"7.0"},{"deprecated":false,"unavailable":false,"name":"iPadOS","beta":false,"introducedAt":"7.0"},{"deprecated":false,"unavailable":false,"name":"Mac Catalyst","beta":false,"introducedAt":"13.1"},{"unavailable":false,"deprecated":false,"introducedAt":"10.9","beta":false,"name":"macOS"},{"unavailable":false,"deprecated":false,"introducedAt":"9.0","beta":false,"name":"tvOS"},{"unavailable":false,"deprecated":false,"introducedAt":"1.0","beta":false,"name":"visionOS"},{"unavailable":false,"deprecated":false,"introducedAt":"2.0","beta":false,"name":"watchOS"}],"symbolKind":"method","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"retrievePeripherals","kind":"identifier"},{"text":"(","kind":"text"},{"text":"withIdentifiers","kind":"externalParam"},{"text":": [","kind":"text"},{"preciseIdentifier":"s:10Foundation4UUIDV","text":"UUID","kind":"typeIdentifier"},{"text":"]) -> [","kind":"text"},{"text":"CBPeripheral","preciseIdentifier":"c:objc(cs)CBPeripheral","kind":"typeIdentifier"},{"text":"]","kind":"text"}],"navigatorTitle":[{"text":"retrievePeripheralsWithIdentifiers:","kind":"identifier"}],"roleHeading":"Instance Method","externalID":"c:objc(cs)CBCentralManager(im)retrievePeripheralsWithIdentifiers:","title":"retrievePeripherals(withIdentifiers:)"},"kind":"symbol","sections":[],"seeAlsoSections":[{"title":"Retrieving Lists of Peripherals","anchor":"Retrieving-Lists-of-Peripherals","identifiers":["doc://com.apple.corebluetooth/documentation/CoreBluetooth/CBCentralManager/retrieveConnectedPeripherals(withServices:)"],"generated":true}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["/documentation/corebluetooth/cbcentralmanager/retrieveperipherals(withidentifiers:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["/documentation/corebluetooth/cbcentralmanager/retrieveperipherals(withidentifiers:)"]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"retrievePeripherals","kind":"identifier"},{"text":"(","kind":"text"},{"text":"withIdentifiers","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"identifiers","kind":"internalParam"},{"text":": [","kind":"text"},{"identifier":"doc://com.externally.resolved.symbol/s:10Foundation4UUIDV","preciseIdentifier":"s:10Foundation4UUIDV","text":"UUID","kind":"typeIdentifier"},{"text":"]) -> [","kind":"text"},{"identifier":"doc://com.apple.corebluetooth/documentation/CoreBluetooth/CBPeripheral","preciseIdentifier":"c:objc(cs)CBPeripheral","text":"CBPeripheral","kind":"typeIdentifier"},{"text":"]","kind":"text"}],"platforms":["iOS","iPadOS","Mac Catalyst","macOS","tvOS","visionOS","watchOS"],"languages":["swift"]}]},{"kind":"parameters","parameters":[{"name":"identifiers","content":[{"inlineContent":[{"type":"text","text":"A list of peripheral identifiers (represented by "},{"identifier":"doc://com.apple.documentation/documentation/foundation/nsuuid","type":"reference","isActive":true},{"type":"text","text":" objects) from which "},{"identifier":"doc://com.apple.corebluetooth/documentation/CoreBluetooth/CBPeripheral","type":"reference","isActive":true},{"type":"text","text":" objects can be retrieved."}],"type":"paragraph"}]}]},{"kind":"content","content":[{"type":"heading","anchor":"return-value","text":"Return Value","level":2},{"inlineContent":[{"type":"text","text":"A list of peripherals that the central manager is able to match to the provided identifiers."}],"type":"paragraph"}]}],"hierarchy":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.corebluetooth/documentation/CoreBluetooth","doc://com.apple.corebluetooth/documentation/CoreBluetooth/CBCentralManager"]]},"schemaVersion":{"major":0,"minor":3,"patch":0},"identifier":{"url":"doc://com.apple.corebluetooth/documentation/CoreBluetooth/CBCentralManager/retrievePeripherals(withIdentifiers:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Returns a list of known peripherals by their identifiers."}],"references":{"doc://com.apple.corebluetooth/documentation/CoreBluetooth/CBCentralManager/retrievePeripherals(withIdentifiers:)":{"url":"/documentation/corebluetooth/cbcentralmanager/retrieveperipherals(withidentifiers:)","role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"retrievePeripherals","kind":"identifier"},{"text":"(","kind":"text"},{"text":"withIdentifiers","kind":"externalParam"},{"text":": [","kind":"text"},{"text":"UUID","preciseIdentifier":"s:10Foundation4UUIDV","kind":"typeIdentifier"},{"text":"]) -> [","kind":"text"},{"text":"CBPeripheral","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)CBPeripheral"},{"text":"]","kind":"text"}],"navigatorTitle":[{"text":"retrievePeripheralsWithIdentifiers:","kind":"identifier"}],"type":"topic","abstract":[{"text":"Returns a list of known peripherals by their identifiers.","type":"text"}],"identifier":"doc://com.apple.corebluetooth/documentation/CoreBluetooth/CBCentralManager/retrievePeripherals(withIdentifiers:)","title":"retrievePeripherals(withIdentifiers:)","kind":"symbol"},"doc://com.apple.corebluetooth/documentation/CoreBluetooth":{"title":"Core Bluetooth","abstract":[{"text":"Communicate with Bluetooth low energy and BR/EDR (“Classic”) Devices.","type":"text"}],"url":"/documentation/corebluetooth","kind":"symbol","type":"topic","role":"collection","identifier":"doc://com.apple.corebluetooth/documentation/CoreBluetooth"},"doc://com.apple.corebluetooth/documentation/CoreBluetooth/CBPeripheral":{"url":"/documentation/corebluetooth/cbperipheral","abstract":[{"text":"A remote peripheral device.","type":"text"}],"type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"CBPeripheral","kind":"identifier"}],"kind":"symbol","role":"symbol","title":"CBPeripheral","navigatorTitle":[{"text":"CBPeripheral","kind":"identifier"}],"identifier":"doc://com.apple.corebluetooth/documentation/CoreBluetooth/CBPeripheral"},"doc://com.apple.documentation/documentation/technologies":{"abstract":[{"text":"","type":"text"}],"identifier":"doc://com.apple.documentation/documentation/technologies","kind":"technologies","type":"topic","title":"Technologies","role":"overview","url":"/documentation/technologies"},"doc://com.externally.resolved.symbol/s:10Foundation4UUIDV":{"identifier":"doc://com.externally.resolved.symbol/s:10Foundation4UUIDV","url":"/documentation/foundation/uuid","fragments":[{"text":"struct ","kind":"text"},{"text":"UUID","kind":"identifier"}],"role":"symbol","title":"UUID","type":"topic","kind":"symbol","abstract":[{"type":"text","text":"A universally unique value to identify types, interfaces, and other items."}]},"doc://com.apple.documentation/documentation/foundation/nsuuid":{"title":"NSUUID","url":"/documentation/foundation/nsuuid","kind":"symbol","abstract":[{"type":"text","text":"An object representing a universally unique value that bridges to ; use  when you need reference semantics or other Foundation-specific behavior. "}],"identifier":"doc://com.apple.documentation/documentation/foundation/nsuuid","role":"symbol","type":"topic","fragments":[{"kind":"text","text":"class "},{"kind":"identifier","text":"NSUUID"}]},"doc://com.apple.corebluetooth/documentation/CoreBluetooth/CBCentralManager/retrieveConnectedPeripherals(withServices:)":{"role":"symbol","identifier":"doc://com.apple.corebluetooth/documentation/CoreBluetooth/CBCentralManager/retrieveConnectedPeripherals(withServices:)","abstract":[{"type":"text","text":"Returns a list of the peripherals connected to the system whose services match a given set of criteria."}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"retrieveConnectedPeripherals","kind":"identifier"},{"text":"(","kind":"text"},{"text":"withServices","kind":"externalParam"},{"text":": [","kind":"text"},{"preciseIdentifier":"c:objc(cs)CBUUID","text":"CBUUID","kind":"typeIdentifier"},{"text":"]) -> [","kind":"text"},{"text":"CBPeripheral","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)CBPeripheral"},{"text":"]","kind":"text"}],"title":"retrieveConnectedPeripherals(withServices:)","url":"/documentation/corebluetooth/cbcentralmanager/retrieveconnectedperipherals(withservices:)","type":"topic","kind":"symbol","navigatorTitle":[{"text":"retrieveConnectedPeripheralsWithServices:","kind":"identifier"}]},"doc://com.apple.corebluetooth/documentation/CoreBluetooth/CBCentralManager":{"title":"CBCentralManager","type":"topic","kind":"symbol","navigatorTitle":[{"text":"CBCentralManager","kind":"identifier"}],"url":"/documentation/corebluetooth/cbcentralmanager","identifier":"doc://com.apple.corebluetooth/documentation/CoreBluetooth/CBCentralManager","abstract":[{"text":"An object that scans for, discovers, connects to, and manages peripherals.","type":"text"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"CBCentralManager","kind":"identifier"}],"role":"symbol"}},"variantOverrides":[{"patch":[{"path":"/identifier/interfaceLanguage","value":"occ","op":"replace"},{"path":"/metadata/platforms","value":[{"unavailable":false,"deprecated":false,"name":"iOS","beta":false,"introducedAt":"7.0"},{"unavailable":false,"deprecated":false,"name":"iPadOS","beta":false,"introducedAt":"7.0"},{"unavailable":false,"deprecated":false,"name":"Mac Catalyst","beta":false,"introducedAt":"13.1"},{"unavailable":false,"deprecated":false,"introducedAt":"10.9","beta":false,"name":"macOS"},{"unavailable":false,"deprecated":false,"introducedAt":"9.0","beta":false,"name":"tvOS"},{"unavailable":false,"deprecated":false,"introducedAt":"1.0","beta":false,"name":"visionOS"},{"unavailable":false,"deprecated":false,"introducedAt":"2.0","beta":false,"name":"watchOS"}],"op":"replace"},{"path":"/metadata/roleHeading","value":"Instance Method","op":"replace"},{"path":"/metadata/title","value":"retrievePeripheralsWithIdentifiers:","op":"replace"},{"path":"/metadata/symbolKind","value":"method","op":"replace"},{"path":"/metadata/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"retrievePeripheralsWithIdentifiers:"}],"op":"replace"},{"path":"/hierarchy","value":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.corebluetooth/documentation/CoreBluetooth","doc://com.apple.corebluetooth/documentation/CoreBluetooth/CBCentralManager"]]},"op":"replace"},{"path":"/topicSections","value":null,"op":"add"},{"path":"/relationshipsSections","value":null,"op":"add"},{"path":"/seeAlsoSections","value":[{"generated":true,"anchor":"Retrieving-Lists-of-Peripherals","title":"Retrieving Lists of Peripherals","identifiers":["doc://com.apple.corebluetooth/documentation/CoreBluetooth/CBCentralManager/retrieveConnectedPeripherals(withServices:)"]}],"op":"replace"},{"path":"/primaryContentSections/0","value":{"declarations":[{"platforms":["iOS","iPadOS","Mac Catalyst","macOS","tvOS","visionOS","watchOS"],"tokens":[{"kind":"text","text":"- ("},{"preciseIdentifier":"c:Q$objc(cs)NSArray","kind":"typeIdentifier","text":"NSArray<CBPeripheral *>"},{"kind":"text","text":" *) "},{"kind":"identifier","text":"retrievePeripheralsWithIdentifiers:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSArray<NSUUID *>","preciseIdentifier":"c:Q$objc(cs)NSArray"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"identifiers"},{"kind":"text","text":";"}],"languages":["occ"]}],"kind":"declarations"},"op":"replace"},{"path":"/primaryContentSections/1","value":{"kind":"parameters","parameters":[{"content":[{"inlineContent":[{"text":"A list of peripheral identifiers (represented by ","type":"text"},{"isActive":true,"identifier":"doc://com.apple.documentation/documentation/foundation/nsuuid","type":"reference"},{"text":" objects) from which ","type":"text"},{"isActive":true,"identifier":"doc://com.apple.corebluetooth/documentation/CoreBluetooth/CBPeripheral","type":"reference"},{"text":" objects can be retrieved.","type":"text"}],"type":"paragraph"}],"name":"identifiers"}]},"op":"replace"},{"path":"/primaryContentSections/2","value":{"kind":"content","content":[{"anchor":"return-value","type":"heading","text":"Return Value","level":2},{"inlineContent":[{"type":"text","text":"A list of peripherals that the central manager is able to match to the provided identifiers."}],"type":"paragraph"}]},"op":"replace"},{"path":"/references/doc:~1~1com.apple.corebluetooth~1documentation~1CoreBluetooth~1CBCentralManager~1retrievePeripherals(withIdentifiers:)/title","op":"replace","value":"retrievePeripheralsWithIdentifiers:"},{"path":"/references/doc:~1~1com.apple.corebluetooth~1documentation~1CoreBluetooth~1CBCentralManager~1retrievePeripherals(withIdentifiers:)/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"retrievePeripheralsWithIdentifiers:"}]},{"path":"/references/doc:~1~1com.apple.corebluetooth~1documentation~1CoreBluetooth~1CBPeripheral/title","op":"replace","value":"CBPeripheral"},{"path":"/references/doc:~1~1com.apple.corebluetooth~1documentation~1CoreBluetooth~1CBPeripheral/fragments","op":"replace","value":[{"text":"CBPeripheral","kind":"identifier"}]},{"path":"/references/doc:~1~1com.apple.corebluetooth~1documentation~1CoreBluetooth~1CBPeripheral/navigatorTitle","op":"replace","value":[{"text":"CBPeripheral","kind":"identifier"}]},{"path":"/references/doc:~1~1com.apple.documentation~1documentation~1foundation~1nsuuid/abstract","op":"replace","value":[{"text":"A universally unique value that can be used to identify types, interfaces, and other items.  ","type":"text"}]},{"path":"/references/doc:~1~1com.apple.corebluetooth~1documentation~1CoreBluetooth~1CBCentralManager~1retrieveConnectedPeripherals(withServices:)/title","op":"replace","value":"retrieveConnectedPeripheralsWithServices:"},{"path":"/references/doc:~1~1com.apple.corebluetooth~1documentation~1CoreBluetooth~1CBCentralManager~1retrieveConnectedPeripherals(withServices:)/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"text":"retrieveConnectedPeripheralsWithServices:","kind":"identifier"}]},{"op":"replace","value":"CBCentralManager","path":"/references/doc:~1~1com.apple.corebluetooth~1documentation~1CoreBluetooth~1CBCentralManager/title"},{"op":"replace","value":[{"kind":"identifier","text":"CBCentralManager"}],"path":"/references/doc:~1~1com.apple.corebluetooth~1documentation~1CoreBluetooth~1CBCentralManager/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"CBCentralManager"}],"path":"/references/doc:~1~1com.apple.corebluetooth~1documentation~1CoreBluetooth~1CBCentralManager/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}],"legalNotices":{"copyright":"Copyright &copy; 2025 Apple Inc. All rights reserved.","termsOfUse":"https://www.apple.com/legal/internet-services/terms/site.html","privacyPolicy":"https://www.apple.com/privacy/privacy-policy"}}