{
  "abstract": [
    {
      "text": "Scans for peripherals that are advertising services.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.corebluetooth/documentation/CoreBluetooth",
        "doc://com.apple.corebluetooth/documentation/CoreBluetooth/CBCentralManager"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.corebluetooth/documentation/CoreBluetooth/CBCentralManager/scanForPeripherals(withServices:options:)"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(cs)CBCentralManager(im)scanForPeripheralsWithServices:options:",
    "fragments": [
      {
        "kind": "keyword",
        "text": "func"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "scanForPeripherals"
      },
      {
        "kind": "text",
        "text": "("
      },
      {
        "kind": "externalParam",
        "text": "withServices"
      },
      {
        "kind": "text",
        "text": ": ["
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:objc(cs)CBUUID",
        "text": "CBUUID"
      },
      {
        "kind": "text",
        "text": "]?, "
      },
      {
        "kind": "externalParam",
        "text": "options"
      },
      {
        "kind": "text",
        "text": ": ["
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "s:SS",
        "text": "String"
      },
      {
        "kind": "text",
        "text": " : "
      },
      {
        "kind": "keyword",
        "text": "Any"
      },
      {
        "kind": "text",
        "text": "]?)"
      }
    ],
    "modules": [
      {
        "name": "Core Bluetooth"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "scanForPeripheralsWithServices:options:"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "5.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "5.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.1",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.7",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "9.0",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "2.0",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Instance Method",
    "symbolKind": "method",
    "title": "scanForPeripherals(withServices:options:)"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "func"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "scanForPeripherals"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "kind": "externalParam",
              "text": "withServices"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "serviceUUIDs"
            },
            {
              "kind": "text",
              "text": ": ["
            },
            {
              "identifier": "doc://com.apple.corebluetooth/documentation/CoreBluetooth/CBUUID",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)CBUUID",
              "text": "CBUUID"
            },
            {
              "kind": "text",
              "text": "]?, "
            },
            {
              "kind": "externalParam",
              "text": "options"
            },
            {
              "kind": "text",
              "text": ": ["
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:SS",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:SS",
              "text": "String"
            },
            {
              "kind": "text",
              "text": " : "
            },
            {
              "kind": "keyword",
              "text": "Any"
            },
            {
              "kind": "text",
              "text": "]? = nil)"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "kind": "parameters",
      "parameters": [
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "An array of ",
                  "type": "text"
                },
                {
                  "identifier": "doc://com.apple.corebluetooth/documentation/CoreBluetooth/CBUUID",
                  "isActive": true,
                  "type": "reference"
                },
                {
                  "text": " objects that the app is interested in. Each ",
                  "type": "text"
                },
                {
                  "identifier": "doc://com.apple.corebluetooth/documentation/CoreBluetooth/CBUUID",
                  "isActive": true,
                  "type": "reference"
                },
                {
                  "text": " object represents the UUID of a service that a peripheral advertises.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "serviceUUIDs"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "A dictionary of options for customizing the scan. For available options, see ",
                  "type": "text"
                },
                {
                  "identifier": "doc://com.apple.corebluetooth/documentation/CoreBluetooth/peripheral-scanning-options",
                  "isActive": true,
                  "type": "reference"
                },
                {
                  "text": ".",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "options"
        }
      ]
    },
    {
      "content": [
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "You can provide an array of ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.corebluetooth/documentation/CoreBluetooth/CBUUID",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " objects — representing service UUIDs — in the ",
              "type": "text"
            },
            {
              "code": "serviceUUIDs",
              "type": "codeVoice"
            },
            {
              "text": " parameter. When you do, the central manager returns only peripherals that advertise the services you specify. If the ",
              "type": "text"
            },
            {
              "code": "serviceUUIDs",
              "type": "codeVoice"
            },
            {
              "text": " parameter is ",
              "type": "text"
            },
            {
              "code": "nil",
              "type": "codeVoice"
            },
            {
              "text": ", this method returns all discovered peripherals, regardless of their supported services.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "",
                  "type": "text"
                },
                {
                  "text": " ",
                  "type": "text"
                },
                {
                  "text": "The recommended practice is to populate the ",
                  "type": "text"
                },
                {
                  "code": "serviceUUIDs",
                  "type": "codeVoice"
                },
                {
                  "text": " parameter rather than leaving it ",
                  "type": "text"
                },
                {
                  "code": "nil",
                  "type": "codeVoice"
                },
                {
                  "text": ".",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "Note",
          "style": "note",
          "type": "aside"
        },
        {
          "inlineContent": [
            {
              "text": "If the central manager is actively scanning with one set of parameters and it receives another set to scan, the new parameters override the previous set. When the central manager discovers a peripheral, it calls the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.corebluetooth/documentation/CoreBluetooth/CBCentralManagerDelegate/centralManager(_:didDiscover:advertisementData:rssi:)",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " method of its delegate object.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "Your app can scan for Bluetooth devices in the background by specifying the ",
              "type": "text"
            },
            {
              "code": "bluetooth-central",
              "type": "codeVoice"
            },
            {
              "text": " background mode. To do this, your app must explicitly scan for one or more services by specifying them in the ",
              "type": "text"
            },
            {
              "code": "serviceUUIDs",
              "type": "codeVoice"
            },
            {
              "text": " parameter. The ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.corebluetooth/documentation/CoreBluetooth/CBCentralManager",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " scan option has no effect while scanning in the background.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.corebluetooth/documentation/CoreBluetooth": {
      "abstract": [
        {
          "text": "Communicate with Bluetooth low energy and BR/EDR (“Classic”) Devices.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.corebluetooth/documentation/CoreBluetooth",
      "kind": "symbol",
      "role": "collection",
      "title": "Core Bluetooth",
      "type": "topic",
      "url": "/documentation/corebluetooth"
    },
    "doc://com.apple.corebluetooth/documentation/CoreBluetooth/CBCentralManager": {
      "abstract": [
        {
          "text": "An object that scans for, discovers, connects to, and manages peripherals.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CBCentralManager"
        }
      ],
      "identifier": "doc://com.apple.corebluetooth/documentation/CoreBluetooth/CBCentralManager",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CBCentralManager"
        }
      ],
      "role": "symbol",
      "title": "CBCentralManager",
      "type": "topic",
      "url": "/documentation/corebluetooth/cbcentralmanager"
    },
    "doc://com.apple.corebluetooth/documentation/CoreBluetooth/CBCentralManager/isScanning": {
      "abstract": [
        {
          "text": "A Boolean value that indicates whether the central is currently scanning.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "isScanning"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.corebluetooth/documentation/CoreBluetooth/CBCentralManager/isScanning",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "isScanning"
        }
      ],
      "role": "symbol",
      "title": "isScanning",
      "type": "topic",
      "url": "/documentation/corebluetooth/cbcentralmanager/isscanning"
    },
    "doc://com.apple.corebluetooth/documentation/CoreBluetooth/CBCentralManager/scanForPeripherals(withServices:options:)": {
      "abstract": [
        {
          "text": "Scans for peripherals that are advertising services.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "scanForPeripherals"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "withServices"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)CBUUID",
          "text": "CBUUID"
        },
        {
          "kind": "text",
          "text": "]?, "
        },
        {
          "kind": "externalParam",
          "text": "options"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "keyword",
          "text": "Any"
        },
        {
          "kind": "text",
          "text": "]?)"
        }
      ],
      "identifier": "doc://com.apple.corebluetooth/documentation/CoreBluetooth/CBCentralManager/scanForPeripherals(withServices:options:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "scanForPeripheralsWithServices:options:"
        }
      ],
      "role": "symbol",
      "title": "scanForPeripherals(withServices:options:)",
      "type": "topic",
      "url": "/documentation/corebluetooth/cbcentralmanager/scanforperipherals(withservices:options:)"
    },
    "doc://com.apple.corebluetooth/documentation/CoreBluetooth/CBCentralManager/stopScan()": {
      "abstract": [
        {
          "text": "Asks the central manager to stop scanning for peripherals.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "stopScan"
        },
        {
          "kind": "text",
          "text": "()"
        }
      ],
      "identifier": "doc://com.apple.corebluetooth/documentation/CoreBluetooth/CBCentralManager/stopScan()",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "stopScan"
        }
      ],
      "role": "symbol",
      "title": "stopScan()",
      "type": "topic",
      "url": "/documentation/corebluetooth/cbcentralmanager/stopscan()"
    },
    "doc://com.apple.corebluetooth/documentation/CoreBluetooth/CBCentralManagerDelegate/centralManager(_:didDiscover:advertisementData:rssi:)": {
      "abstract": [
        {
          "text": "Tells the delegate the central manager discovered a peripheral while scanning for devices.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "centralManager"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)CBCentralManager",
          "text": "CBCentralManager"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "didDiscover"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)CBPeripheral",
          "text": "CBPeripheral"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "advertisementData"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "keyword",
          "text": "Any"
        },
        {
          "kind": "text",
          "text": "], "
        },
        {
          "kind": "externalParam",
          "text": "rssi"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSNumber",
          "text": "NSNumber"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.corebluetooth/documentation/CoreBluetooth/CBCentralManagerDelegate/centralManager(_:didDiscover:advertisementData:rssi:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "centralManager:didDiscoverPeripheral:advertisementData:RSSI:"
        }
      ],
      "role": "symbol",
      "title": "centralManager(_:didDiscover:advertisementData:rssi:)",
      "type": "topic",
      "url": "/documentation/corebluetooth/cbcentralmanagerdelegate/centralmanager(_:diddiscover:advertisementdata:rssi:)"
    },
    "doc://com.apple.corebluetooth/documentation/CoreBluetooth/CBUUID": {
      "abstract": [
        {
          "text": "A universally unique identifier, as defined by Bluetooth standards.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CBUUID"
        }
      ],
      "identifier": "doc://com.apple.corebluetooth/documentation/CoreBluetooth/CBUUID",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CBUUID"
        }
      ],
      "role": "symbol",
      "title": "CBUUID",
      "type": "topic",
      "url": "/documentation/corebluetooth/cbuuid"
    },
    "doc://com.apple.corebluetooth/documentation/CoreBluetooth/peripheral-scanning-options": {
      "abstract": [
        {
          "text": "Keys used to pass options when scanning for peripherals.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.corebluetooth/documentation/CoreBluetooth/peripheral-scanning-options",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Peripheral Scanning Options",
      "type": "topic",
      "url": "/documentation/corebluetooth/peripheral-scanning-options"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.externally.resolved.symbol/s:SS": {
      "abstract": [
        {
          "text": "A Unicode string value that is a collection of characters.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@frozen"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "String"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SS",
      "kind": "symbol",
      "role": "symbol",
      "title": "String",
      "type": "topic",
      "url": "/documentation/Swift/String"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Scanning-or-Stopping-Scans-of-Peripherals",
      "generated": true,
      "identifiers": [
        "doc://com.apple.corebluetooth/documentation/CoreBluetooth/peripheral-scanning-options",
        "doc://com.apple.corebluetooth/documentation/CoreBluetooth/CBCentralManager/stopScan()",
        "doc://com.apple.corebluetooth/documentation/CoreBluetooth/CBCentralManager/isScanning"
      ],
      "title": "Scanning or Stopping Scans of Peripherals"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "5.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "5.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.1",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.7",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "9.0",
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "2.0",
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Instance Method"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "scanForPeripheralsWithServices:options:"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "method"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "scanForPeripheralsWithServices:options:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.corebluetooth/documentation/CoreBluetooth",
                "doc://com.apple.corebluetooth/documentation/CoreBluetooth/CBCentralManager"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Scanning-or-Stopping-Scans-of-Peripherals",
              "generated": true,
              "identifiers": [
                "doc://com.apple.corebluetooth/documentation/CoreBluetooth/peripheral-scanning-options",
                "doc://com.apple.corebluetooth/documentation/CoreBluetooth/CBCentralManager/stopScan()",
                "doc://com.apple.corebluetooth/documentation/CoreBluetooth/CBCentralManager/isScanning"
              ],
              "title": "Scanning or Stopping Scans of Peripherals"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "text",
                    "text": "- ("
                  },
                  {
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:v",
                    "text": "void"
                  },
                  {
                    "kind": "text",
                    "text": ") "
                  },
                  {
                    "kind": "identifier",
                    "text": "scanForPeripheralsWithServices:"
                  },
                  {
                    "kind": "text",
                    "text": "("
                  },
                  {
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:Q$objc(cs)NSArray",
                    "text": "NSArray<CBUUID *>"
                  },
                  {
                    "kind": "text",
                    "text": " *) "
                  },
                  {
                    "kind": "internalParam",
                    "text": "serviceUUIDs"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "options:"
                  },
                  {
                    "kind": "text",
                    "text": "("
                  },
                  {
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:Q$objc(cs)NSDictionary",
                    "text": "NSDictionary<NSString *,id>"
                  },
                  {
                    "kind": "text",
                    "text": " *) "
                  },
                  {
                    "kind": "internalParam",
                    "text": "options"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/1",
          "value": {
            "kind": "parameters",
            "parameters": [
              {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "An array of ",
                        "type": "text"
                      },
                      {
                        "identifier": "doc://com.apple.corebluetooth/documentation/CoreBluetooth/CBUUID",
                        "isActive": true,
                        "type": "reference"
                      },
                      {
                        "text": " objects that the app is interested in. Each ",
                        "type": "text"
                      },
                      {
                        "identifier": "doc://com.apple.corebluetooth/documentation/CoreBluetooth/CBUUID",
                        "isActive": true,
                        "type": "reference"
                      },
                      {
                        "text": " object represents the UUID of a service that a peripheral advertises.",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ],
                "name": "serviceUUIDs"
              },
              {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "A dictionary of options for customizing the scan. For available options, see ",
                        "type": "text"
                      },
                      {
                        "identifier": "doc://com.apple.corebluetooth/documentation/CoreBluetooth/peripheral-scanning-options",
                        "isActive": true,
                        "type": "reference"
                      },
                      {
                        "text": ".",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ],
                "name": "options"
              }
            ]
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corebluetooth~1documentation~1CoreBluetooth~1CBCentralManager~1isScanning/title",
          "value": "isScanning"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corebluetooth~1documentation~1CoreBluetooth~1CBCentralManager~1isScanning/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "isScanning"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corebluetooth~1documentation~1CoreBluetooth~1CBCentralManagerDelegate~1centralManager(_:didDiscover:advertisementData:rssi:)/title",
          "value": "centralManager:didDiscoverPeripheral:advertisementData:RSSI:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corebluetooth~1documentation~1CoreBluetooth~1CBCentralManagerDelegate~1centralManager(_:didDiscover:advertisementData:rssi:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "centralManager:didDiscoverPeripheral:advertisementData:RSSI:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corebluetooth~1documentation~1CoreBluetooth~1CBCentralManager/title",
          "value": "CBCentralManager"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corebluetooth~1documentation~1CoreBluetooth~1CBCentralManager/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CBCentralManager"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corebluetooth~1documentation~1CoreBluetooth~1CBCentralManager/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CBCentralManager"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corebluetooth~1documentation~1CoreBluetooth~1CBCentralManager~1scanForPeripherals(withServices:options:)/title",
          "value": "scanForPeripheralsWithServices:options:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corebluetooth~1documentation~1CoreBluetooth~1CBCentralManager~1scanForPeripherals(withServices:options:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "scanForPeripheralsWithServices:options:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corebluetooth~1documentation~1CoreBluetooth~1CBCentralManager~1stopScan()/title",
          "value": "stopScan"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corebluetooth~1documentation~1CoreBluetooth~1CBCentralManager~1stopScan()/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "stopScan"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corebluetooth~1documentation~1CoreBluetooth~1CBUUID/title",
          "value": "CBUUID"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corebluetooth~1documentation~1CoreBluetooth~1CBUUID/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CBUUID"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corebluetooth~1documentation~1CoreBluetooth~1CBUUID/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CBUUID"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/corebluetooth/cbcentralmanager/scanforperipherals(withservices:options:)"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/corebluetooth/cbcentralmanager/scanforperipherals(withservices:options:)"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
