{
  "abstract": [
    {
      "text": "If this flag is set on the post-render call an error was returned by the audio unit’s render operation. In this case, the error can be retrieved through the lastRenderError property and the audio data in ",
      "type": "text"
    },
    {
      "code": "ioData",
      "type": "codeVoice"
    },
    {
      "text": " handed to the post-render notification will be invalid.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioUnitRenderActionFlags"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioUnitRenderActionFlags/unitRenderAction_PostRenderError"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@AudioUnitRenderActionFlags@kAudioUnitRenderAction_PostRenderError",
    "fragments": [
      {
        "kind": "keyword",
        "text": "static"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "keyword",
        "text": "var"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "unitRenderAction_PostRenderError"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@E@AudioUnitRenderActionFlags",
        "text": "AudioUnitRenderActionFlags"
      }
    ],
    "modules": [
      {
        "name": "Audio Toolbox"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "kAudioUnitRenderAction_PostRenderError"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Type Property",
    "symbolKind": "property",
    "title": "unitRenderAction_PostRenderError"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "static"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "keyword",
              "text": "var"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "unitRenderAction_PostRenderError"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioUnitRenderActionFlags",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@E@AudioUnitRenderActionFlags",
              "text": "AudioUnitRenderActionFlags"
            },
            {
              "kind": "text",
              "text": " { "
            },
            {
              "kind": "keyword",
              "text": "get"
            },
            {
              "kind": "text",
              "text": " }"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox": {
      "abstract": [
        {
          "text": "Record or play audio, convert formats, parse audio streams, and configure your audio session.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox",
      "kind": "symbol",
      "role": "collection",
      "title": "Audio Toolbox",
      "type": "topic",
      "url": "/documentation/audiotoolbox"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioUnitRenderActionFlags": {
      "abstract": [
        {
          "text": "Flags for configuring audio unit rendering.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AudioUnitRenderActionFlags"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioUnitRenderActionFlags",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AudioUnitRenderActionFlags"
        }
      ],
      "role": "symbol",
      "title": "AudioUnitRenderActionFlags",
      "type": "topic",
      "url": "/documentation/audiotoolbox/audiounitrenderactionflags"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioUnitRenderActionFlags/offlineUnitRenderAction_Complete": {
      "abstract": [
        {
          "text": "This flag is set when an offline unit has completed either its preflight or performed render operation.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "offlineUnitRenderAction_Complete"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@AudioUnitRenderActionFlags",
          "text": "AudioUnitRenderActionFlags"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioUnitRenderActionFlags/offlineUnitRenderAction_Complete",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioOfflineUnitRenderAction_Complete"
        }
      ],
      "role": "symbol",
      "title": "offlineUnitRenderAction_Complete",
      "type": "topic",
      "url": "/documentation/audiotoolbox/audiounitrenderactionflags/offlineunitrenderaction_complete"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioUnitRenderActionFlags/offlineUnitRenderAction_Preflight": {
      "abstract": [
        {
          "text": "This is used with offline audio units (of type ",
          "type": "text"
        },
        {
          "code": "'auol'",
          "type": "codeVoice"
        },
        {
          "text": "). It is used when an offline unit is being preflighted, which is performed prior to the actual offline rendering actions are performed. It is used for those cases where the offline process needs it (for example, with an offline unit that normalizes an audio file, it needs to see all of the audio data first before it can perform its normalization).",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "offlineUnitRenderAction_Preflight"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@AudioUnitRenderActionFlags",
          "text": "AudioUnitRenderActionFlags"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioUnitRenderActionFlags/offlineUnitRenderAction_Preflight",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioOfflineUnitRenderAction_Preflight"
        }
      ],
      "role": "symbol",
      "title": "offlineUnitRenderAction_Preflight",
      "type": "topic",
      "url": "/documentation/audiotoolbox/audiounitrenderactionflags/offlineunitrenderaction_preflight"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioUnitRenderActionFlags/offlineUnitRenderAction_Render": {
      "abstract": [
        {
          "text": "Once an offline unit has been successfully preflighted, it is then put into its render mode. So this flag is set to indicate to the audio unit that it is now in that state and that it should perform its processing on the input data.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "offlineUnitRenderAction_Render"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@AudioUnitRenderActionFlags",
          "text": "AudioUnitRenderActionFlags"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioUnitRenderActionFlags/offlineUnitRenderAction_Render",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioOfflineUnitRenderAction_Render"
        }
      ],
      "role": "symbol",
      "title": "offlineUnitRenderAction_Render",
      "type": "topic",
      "url": "/documentation/audiotoolbox/audiounitrenderactionflags/offlineunitrenderaction_render"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioUnitRenderActionFlags/unitRenderAction_DoNotCheckRenderArgs": {
      "abstract": [
        {
          "text": "If this flag is set, then checks that are done on the arguments provided to render are not performed. This can be useful to use to save computation time in situations where you are sure you are providing the correct arguments and structures to the various render calls.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "unitRenderAction_DoNotCheckRenderArgs"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@AudioUnitRenderActionFlags",
          "text": "AudioUnitRenderActionFlags"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioUnitRenderActionFlags/unitRenderAction_DoNotCheckRenderArgs",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioUnitRenderAction_DoNotCheckRenderArgs"
        }
      ],
      "role": "symbol",
      "title": "unitRenderAction_DoNotCheckRenderArgs",
      "type": "topic",
      "url": "/documentation/audiotoolbox/audiounitrenderactionflags/unitrenderaction_donotcheckrenderargs"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioUnitRenderActionFlags/unitRenderAction_OutputIsSilence": {
      "abstract": [
        {
          "text": "This flag can be set in a render input callback (or in the audio unit’s render operation itself) and is used to indicate that the render buffer contains only silence. It can then be used by the caller as a hint to whether the buffer needs to be processed or not.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "unitRenderAction_OutputIsSilence"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@AudioUnitRenderActionFlags",
          "text": "AudioUnitRenderActionFlags"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioUnitRenderActionFlags/unitRenderAction_OutputIsSilence",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioUnitRenderAction_OutputIsSilence"
        }
      ],
      "role": "symbol",
      "title": "unitRenderAction_OutputIsSilence",
      "type": "topic",
      "url": "/documentation/audiotoolbox/audiounitrenderactionflags/unitrenderaction_outputissilence"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioUnitRenderActionFlags/unitRenderAction_PostRender": {
      "abstract": [
        {
          "text": "Called on a render notification Proc - which is called either before or after the render operation of the audio unit. If this flag is set, the proc is being called after the render operation is completed.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "unitRenderAction_PostRender"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@AudioUnitRenderActionFlags",
          "text": "AudioUnitRenderActionFlags"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioUnitRenderActionFlags/unitRenderAction_PostRender",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioUnitRenderAction_PostRender"
        }
      ],
      "role": "symbol",
      "title": "unitRenderAction_PostRender",
      "type": "topic",
      "url": "/documentation/audiotoolbox/audiounitrenderactionflags/unitrenderaction_postrender"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioUnitRenderActionFlags/unitRenderAction_PostRenderError": {
      "abstract": [
        {
          "text": "If this flag is set on the post-render call an error was returned by the audio unit’s render operation. In this case, the error can be retrieved through the lastRenderError property and the audio data in ",
          "type": "text"
        },
        {
          "code": "ioData",
          "type": "codeVoice"
        },
        {
          "text": " handed to the post-render notification will be invalid.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "unitRenderAction_PostRenderError"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@AudioUnitRenderActionFlags",
          "text": "AudioUnitRenderActionFlags"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioUnitRenderActionFlags/unitRenderAction_PostRenderError",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioUnitRenderAction_PostRenderError"
        }
      ],
      "role": "symbol",
      "title": "unitRenderAction_PostRenderError",
      "type": "topic",
      "url": "/documentation/audiotoolbox/audiounitrenderactionflags/unitrenderaction_postrendererror"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioUnitRenderActionFlags/unitRenderAction_PreRender": {
      "abstract": [
        {
          "text": "Called on a render notification Proc - which is called either before or after the render operation of the audio unit. If this flag is set, the proc is being called before the render operation is performed.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "unitRenderAction_PreRender"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@AudioUnitRenderActionFlags",
          "text": "AudioUnitRenderActionFlags"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioUnitRenderActionFlags/unitRenderAction_PreRender",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioUnitRenderAction_PreRender"
        }
      ],
      "role": "symbol",
      "title": "unitRenderAction_PreRender",
      "type": "topic",
      "url": "/documentation/audiotoolbox/audiounitrenderactionflags/unitrenderaction_prerender"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Constants",
      "generated": true,
      "identifiers": [
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioUnitRenderActionFlags/unitRenderAction_PreRender",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioUnitRenderActionFlags/unitRenderAction_PostRender",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioUnitRenderActionFlags/unitRenderAction_OutputIsSilence",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioUnitRenderActionFlags/offlineUnitRenderAction_Preflight",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioUnitRenderActionFlags/offlineUnitRenderAction_Render",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioUnitRenderActionFlags/offlineUnitRenderAction_Complete",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioUnitRenderActionFlags/unitRenderAction_DoNotCheckRenderArgs"
      ],
      "title": "Constants"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration Case"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "kAudioUnitRenderAction_PostRenderError"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "case"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioUnitRenderAction_PostRenderError"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioUnitRenderActionFlags"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Constants",
              "generated": true,
              "identifiers": [
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioUnitRenderActionFlags/unitRenderAction_PreRender",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioUnitRenderActionFlags/unitRenderAction_PostRender",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioUnitRenderActionFlags/unitRenderAction_OutputIsSilence",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioUnitRenderActionFlags/offlineUnitRenderAction_Preflight",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioUnitRenderActionFlags/offlineUnitRenderAction_Render",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioUnitRenderActionFlags/offlineUnitRenderAction_Complete",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioUnitRenderActionFlags/unitRenderAction_DoNotCheckRenderArgs"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS"
                ],
                "tokens": [
                  {
                    "kind": "identifier",
                    "text": "kAudioUnitRenderAction_PostRenderError"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioUnitRenderActionFlags~1offlineUnitRenderAction_Complete/title",
          "value": "kAudioOfflineUnitRenderAction_Complete"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioUnitRenderActionFlags~1offlineUnitRenderAction_Complete/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioOfflineUnitRenderAction_Complete"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioUnitRenderActionFlags~1unitRenderAction_PostRenderError/title",
          "value": "kAudioUnitRenderAction_PostRenderError"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioUnitRenderActionFlags~1unitRenderAction_PostRenderError/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioUnitRenderAction_PostRenderError"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioUnitRenderActionFlags/title",
          "value": "AudioUnitRenderActionFlags"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioUnitRenderActionFlags/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AudioUnitRenderActionFlags"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioUnitRenderActionFlags/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AudioUnitRenderActionFlags"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioUnitRenderActionFlags~1offlineUnitRenderAction_Render/title",
          "value": "kAudioOfflineUnitRenderAction_Render"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioUnitRenderActionFlags~1offlineUnitRenderAction_Render/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioOfflineUnitRenderAction_Render"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioUnitRenderActionFlags~1unitRenderAction_OutputIsSilence/title",
          "value": "kAudioUnitRenderAction_OutputIsSilence"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioUnitRenderActionFlags~1unitRenderAction_OutputIsSilence/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioUnitRenderAction_OutputIsSilence"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioUnitRenderActionFlags~1unitRenderAction_DoNotCheckRenderArgs/title",
          "value": "kAudioUnitRenderAction_DoNotCheckRenderArgs"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioUnitRenderActionFlags~1unitRenderAction_DoNotCheckRenderArgs/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioUnitRenderAction_DoNotCheckRenderArgs"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioUnitRenderActionFlags~1unitRenderAction_PreRender/title",
          "value": "kAudioUnitRenderAction_PreRender"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioUnitRenderActionFlags~1unitRenderAction_PreRender/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioUnitRenderAction_PreRender"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioUnitRenderActionFlags~1offlineUnitRenderAction_Preflight/title",
          "value": "kAudioOfflineUnitRenderAction_Preflight"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioUnitRenderActionFlags~1offlineUnitRenderAction_Preflight/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioOfflineUnitRenderAction_Preflight"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioUnitRenderActionFlags~1unitRenderAction_PostRender/title",
          "value": "kAudioUnitRenderAction_PostRender"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioUnitRenderActionFlags~1unitRenderAction_PostRender/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioUnitRenderAction_PostRender"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/audiotoolbox/audiounitrenderactionflags/unitrenderaction_postrendererror"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/audiotoolbox/audiounitrenderactionflags/unitrenderaction_postrendererror"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
