{"kind":"symbol","identifier":{"interfaceLanguage":"swift","url":"doc://com.apple.iobluetooth/documentation/IOBluetooth/IOBluetoothHandsFreeAudioGateway/createIndicator(_:min:max:currentValue:)"},"abstract":[{"type":"text","text":"Sends a request to the Bluetooth device to show or update a status indicator."}],"variants":[{"paths":["/documentation/iobluetooth/iobluetoothhandsfreeaudiogateway/createindicator(_:min:max:currentvalue:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["/documentation/iobluetooth/iobluetoothhandsfreeaudiogateway/createindicator(_:min:max:currentvalue:)"],"traits":[{"interfaceLanguage":"occ"}]}],"seeAlsoSections":[{"title":"Showing Status Indicators","anchor":"Showing-Status-Indicators","identifiers":["doc://com.apple.iobluetooth/documentation/IOBluetooth/status-indicator-constants"],"generated":true}],"metadata":{"modules":[{"name":"IOBluetooth"}],"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"createIndicator"},{"kind":"text","text":"("},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":"!, "},{"kind":"externalParam","text":"min"},{"kind":"text","text":": "},{"preciseIdentifier":"s:s5Int32V","kind":"typeIdentifier","text":"Int32"},{"kind":"text","text":", "},{"kind":"externalParam","text":"max"},{"kind":"text","text":": "},{"preciseIdentifier":"s:s5Int32V","kind":"typeIdentifier","text":"Int32"},{"kind":"text","text":", "},{"kind":"externalParam","text":"currentValue"},{"kind":"text","text":": "},{"preciseIdentifier":"s:s5Int32V","kind":"typeIdentifier","text":"Int32"},{"kind":"text","text":")"}],"role":"symbol","externalID":"c:objc(cs)IOBluetoothHandsFreeAudioGateway(im)createIndicator:min:max:currentValue:","platforms":[{"name":"macOS","beta":false,"deprecated":false,"introducedAt":"10.7","unavailable":false}],"navigatorTitle":[{"kind":"identifier","text":"createIndicator:min:max:currentValue:"}],"title":"createIndicator(_:min:max:currentValue:)","symbolKind":"method","roleHeading":"Instance Method"},"primaryContentSections":[{"declarations":[{"platforms":["macOS"],"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"createIndicator"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"indicatorName"},{"kind":"text","text":": "},{"identifier":"doc://com.externally.resolved.symbol/s:SS","kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":"!, "},{"kind":"externalParam","text":"min"},{"kind":"text","text":" "},{"kind":"internalParam","text":"minValue"},{"kind":"text","text":": "},{"identifier":"doc://com.externally.resolved.symbol/s:s5Int32V","kind":"typeIdentifier","preciseIdentifier":"s:s5Int32V","text":"Int32"},{"kind":"text","text":", "},{"kind":"externalParam","text":"max"},{"kind":"text","text":" "},{"kind":"internalParam","text":"maxValue"},{"kind":"text","text":": "},{"identifier":"doc://com.externally.resolved.symbol/s:s5Int32V","kind":"typeIdentifier","preciseIdentifier":"s:s5Int32V","text":"Int32"},{"kind":"text","text":", "},{"kind":"externalParam","text":"currentValue"},{"kind":"text","text":": "},{"identifier":"doc://com.externally.resolved.symbol/s:s5Int32V","kind":"typeIdentifier","preciseIdentifier":"s:s5Int32V","text":"Int32"},{"kind":"text","text":")"}],"languages":["swift"]}],"kind":"declarations"},{"kind":"parameters","parameters":[{"name":"indicatorName","content":[{"inlineContent":[{"type":"text","text":"The name of the indicator. Use one of the following constants:"}],"type":"paragraph"},{"type":"unorderedList","items":[{"content":[{"inlineContent":[{"type":"reference","isActive":true,"identifier":"doc://com.apple.iobluetooth/documentation/IOBluetooth/IOBluetoothHandsFreeIndicatorService"}],"type":"paragraph"}]},{"content":[{"inlineContent":[{"identifier":"doc://com.apple.iobluetooth/documentation/IOBluetooth/IOBluetoothHandsFreeIndicatorCall","type":"reference","isActive":true}],"type":"paragraph"}]},{"content":[{"inlineContent":[{"isActive":true,"identifier":"doc://com.apple.iobluetooth/documentation/IOBluetooth/IOBluetoothHandsFreeIndicatorCallSetup","type":"reference"}],"type":"paragraph"}]},{"content":[{"type":"paragraph","inlineContent":[{"identifier":"doc://com.apple.iobluetooth/documentation/IOBluetooth/IOBluetoothHandsFreeIndicatorCallHeld","type":"reference","isActive":true}]}]},{"content":[{"type":"paragraph","inlineContent":[{"identifier":"doc://com.apple.iobluetooth/documentation/IOBluetooth/IOBluetoothHandsFreeIndicatorSignal","isActive":true,"type":"reference"}]}]},{"content":[{"type":"paragraph","inlineContent":[{"identifier":"doc://com.apple.iobluetooth/documentation/IOBluetooth/IOBluetoothHandsFreeIndicatorRoam","type":"reference","isActive":true}]}]},{"content":[{"inlineContent":[{"identifier":"doc://com.apple.iobluetooth/documentation/IOBluetooth/IOBluetoothHandsFreeIndicatorBattChg","type":"reference","isActive":true}],"type":"paragraph"}]}]}]},{"name":"minValue","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The minimum value for the indicator."}]}]},{"name":"maxValue","content":[{"inlineContent":[{"type":"text","text":"The maximum value for the indicator."}],"type":"paragraph"}]},{"name":"currentValue","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The current value of the indicator."}]}]}]}],"sections":[],"schemaVersion":{"major":0,"minor":3,"patch":0},"hierarchy":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.iobluetooth/documentation/IOBluetooth","doc://com.apple.iobluetooth/documentation/IOBluetooth/IOBluetoothHandsFreeAudioGateway"]]},"references":{"doc://com.apple.iobluetooth/documentation/IOBluetooth/status-indicator-constants":{"type":"topic","title":"Status Indicator Constants","role":"collectionGroup","abstract":[{"text":"Send commands to modify the status indicators of a hands-free Bluetooth device.","type":"text"}],"url":"/documentation/iobluetooth/status-indicator-constants","kind":"article","identifier":"doc://com.apple.iobluetooth/documentation/IOBluetooth/status-indicator-constants"},"doc://com.externally.resolved.symbol/s:SS":{"type":"topic","identifier":"doc://com.externally.resolved.symbol/s:SS","title":"String","role":"symbol","kind":"symbol","url":"/documentation/Swift/String","fragments":[{"kind":"attribute","text":"@frozen"},{"text":" ","kind":"text"},{"kind":"keyword","text":"struct"},{"text":" ","kind":"text"},{"kind":"identifier","text":"String"}],"abstract":[{"type":"text","text":"A Unicode string value that is a collection of characters."}]},"doc://com.apple.iobluetooth/documentation/IOBluetooth/IOBluetoothHandsFreeIndicatorCallHeld":{"type":"topic","title":"IOBluetoothHandsFreeIndicatorCallHeld","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"IOBluetoothHandsFreeIndicatorCallHeld","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"}],"role":"symbol","abstract":[{"text":"The command string you use to show a call hold status indicator on a phone.","type":"text"}],"navigatorTitle":[{"text":"IOBluetoothHandsFreeIndicatorCallHeld","kind":"identifier"}],"url":"/documentation/iobluetooth/iobluetoothhandsfreeindicatorcallheld","kind":"symbol","identifier":"doc://com.apple.iobluetooth/documentation/IOBluetooth/IOBluetoothHandsFreeIndicatorCallHeld"},"doc://com.apple.iobluetooth/documentation/IOBluetooth/IOBluetoothHandsFreeIndicatorSignal":{"kind":"symbol","navigatorTitle":[{"text":"IOBluetoothHandsFreeIndicatorSignal","kind":"identifier"}],"identifier":"doc://com.apple.iobluetooth/documentation/IOBluetooth/IOBluetoothHandsFreeIndicatorSignal","url":"/documentation/iobluetooth/iobluetoothhandsfreeindicatorsignal","abstract":[{"type":"text","text":"The command string you use to show a signal strength indicator on a phone."}],"type":"topic","title":"IOBluetoothHandsFreeIndicatorSignal","role":"symbol","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"IOBluetoothHandsFreeIndicatorSignal","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"}]},"doc://com.apple.iobluetooth/documentation/IOBluetooth/IOBluetoothHandsFreeIndicatorRoam":{"type":"topic","title":"IOBluetoothHandsFreeIndicatorRoam","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"IOBluetoothHandsFreeIndicatorRoam","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"}],"role":"symbol","abstract":[{"text":"The command string you use to show a roaming status indicator on a phone.","type":"text"}],"navigatorTitle":[{"text":"IOBluetoothHandsFreeIndicatorRoam","kind":"identifier"}],"url":"/documentation/iobluetooth/iobluetoothhandsfreeindicatorroam","kind":"symbol","identifier":"doc://com.apple.iobluetooth/documentation/IOBluetooth/IOBluetoothHandsFreeIndicatorRoam"},"doc://com.apple.iobluetooth/documentation/IOBluetooth/IOBluetoothHandsFreeIndicatorService":{"type":"topic","title":"IOBluetoothHandsFreeIndicatorService","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"IOBluetoothHandsFreeIndicatorService","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"}],"role":"symbol","abstract":[{"text":"The command string you use to show a carrier network connection indicator on a phone.","type":"text"}],"navigatorTitle":[{"text":"IOBluetoothHandsFreeIndicatorService","kind":"identifier"}],"url":"/documentation/iobluetooth/iobluetoothhandsfreeindicatorservice","kind":"symbol","identifier":"doc://com.apple.iobluetooth/documentation/IOBluetooth/IOBluetoothHandsFreeIndicatorService"},"doc://com.apple.iobluetooth/documentation/IOBluetooth/IOBluetoothHandsFreeIndicatorCall":{"type":"topic","title":"IOBluetoothHandsFreeIndicatorCall","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"IOBluetoothHandsFreeIndicatorCall","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"}],"role":"symbol","abstract":[{"text":"The command string you use to show an active call indicator on a phone.","type":"text"}],"navigatorTitle":[{"text":"IOBluetoothHandsFreeIndicatorCall","kind":"identifier"}],"url":"/documentation/iobluetooth/iobluetoothhandsfreeindicatorcall","kind":"symbol","identifier":"doc://com.apple.iobluetooth/documentation/IOBluetooth/IOBluetoothHandsFreeIndicatorCall"},"doc://com.externally.resolved.symbol/c:objc(cs)NSString":{"kind":"symbol","url":"/documentation/foundation/nsstring","title":"NSString","abstract":[{"text":"A static, plain-text Unicode string object which you use when you need reference semantics or other Foundation-specific behavior. ","type":"text"}],"type":"topic","role":"symbol","identifier":"doc://com.externally.resolved.symbol/c:objc(cs)NSString","fragments":[{"kind":"text","text":"class "},{"kind":"identifier","text":"NSString"}]},"doc://com.apple.iobluetooth/documentation/IOBluetooth/IOBluetoothHandsFreeAudioGateway/createIndicator(_:min:max:currentValue:)":{"kind":"symbol","navigatorTitle":[{"text":"createIndicator:min:max:currentValue:","kind":"identifier"}],"identifier":"doc://com.apple.iobluetooth/documentation/IOBluetooth/IOBluetoothHandsFreeAudioGateway/createIndicator(_:min:max:currentValue:)","url":"/documentation/iobluetooth/iobluetoothhandsfreeaudiogateway/createindicator(_:min:max:currentvalue:)","abstract":[{"type":"text","text":"Sends a request to the Bluetooth device to show or update a status indicator."}],"type":"topic","title":"createIndicator(_:min:max:currentValue:)","role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"createIndicator","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":"!, ","kind":"text"},{"text":"min","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:s5Int32V","text":"Int32","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"max","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:s5Int32V","text":"Int32","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"currentValue","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:s5Int32V","text":"Int32","kind":"typeIdentifier"},{"text":")","kind":"text"}]},"doc://com.apple.iobluetooth/documentation/IOBluetooth/IOBluetoothHandsFreeIndicatorCallSetup":{"type":"topic","title":"IOBluetoothHandsFreeIndicatorCallSetup","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"IOBluetoothHandsFreeIndicatorCallSetup","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"}],"role":"symbol","abstract":[{"type":"text","text":"The command string you use to show a call setup status indicator on a phone."}],"navigatorTitle":[{"text":"IOBluetoothHandsFreeIndicatorCallSetup","kind":"identifier"}],"url":"/documentation/iobluetooth/iobluetoothhandsfreeindicatorcallsetup","kind":"symbol","identifier":"doc://com.apple.iobluetooth/documentation/IOBluetooth/IOBluetoothHandsFreeIndicatorCallSetup"},"doc://com.apple.documentation/documentation/technologies":{"type":"topic","kind":"technologies","abstract":[{"type":"text","text":""}],"url":"/documentation/technologies","role":"overview","identifier":"doc://com.apple.documentation/documentation/technologies","title":"Technologies"},"doc://com.apple.iobluetooth/documentation/IOBluetooth":{"kind":"symbol","identifier":"doc://com.apple.iobluetooth/documentation/IOBluetooth","abstract":[{"type":"text","text":"Gain user-space access to Bluetooth devices."}],"url":"/documentation/iobluetooth","role":"collection","type":"topic","title":"IOBluetooth"},"doc://com.apple.iobluetooth/documentation/IOBluetooth/IOBluetoothHandsFreeAudioGateway":{"kind":"symbol","url":"/documentation/iobluetooth/iobluetoothhandsfreeaudiogateway","title":"IOBluetoothHandsFreeAudioGateway","abstract":[{"text":"An object that sends data to a connected Bluetooth hands-free phone or headset and processes commands from it.","type":"text"}],"type":"topic","role":"symbol","navigatorTitle":[{"text":"IOBluetoothHandsFreeAudioGateway","kind":"identifier"}],"identifier":"doc://com.apple.iobluetooth/documentation/IOBluetooth/IOBluetoothHandsFreeAudioGateway","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"IOBluetoothHandsFreeAudioGateway","kind":"identifier"}]},"doc://com.apple.iobluetooth/documentation/IOBluetooth/IOBluetoothHandsFreeIndicatorBattChg":{"type":"topic","title":"IOBluetoothHandsFreeIndicatorBattChg","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"text":"IOBluetoothHandsFreeIndicatorBattChg","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"}],"role":"symbol","abstract":[{"type":"text","text":"The command string you use to show a battery charge level indicator on a phone."}],"navigatorTitle":[{"text":"IOBluetoothHandsFreeIndicatorBattChg","kind":"identifier"}],"url":"/documentation/iobluetooth/iobluetoothhandsfreeindicatorbattchg","kind":"symbol","identifier":"doc://com.apple.iobluetooth/documentation/IOBluetooth/IOBluetoothHandsFreeIndicatorBattChg"},"doc://com.externally.resolved.symbol/s:s5Int32V":{"kind":"symbol","type":"topic","identifier":"doc://com.externally.resolved.symbol/s:s5Int32V","abstract":[{"text":"A 32-bit signed integer value type.","type":"text"}],"role":"symbol","title":"Int32","fragments":[{"text":"@frozen","kind":"attribute"},{"text":" ","kind":"text"},{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Int32","kind":"identifier"}],"url":"/documentation/Swift/Int32"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"/identifier/interfaceLanguage"},{"op":"replace","value":[{"unavailable":false,"introducedAt":"10.7","beta":false,"deprecated":false,"name":"macOS"}],"path":"/metadata/platforms"},{"op":"replace","value":"Instance Method","path":"/metadata/roleHeading"},{"op":"replace","value":"createIndicator:min:max:currentValue:","path":"/metadata/title"},{"op":"replace","value":"method","path":"/metadata/symbolKind"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"text":"createIndicator:min:max:currentValue:","kind":"identifier"}],"path":"/metadata/fragments"},{"op":"replace","value":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.iobluetooth/documentation/IOBluetooth","doc://com.apple.iobluetooth/documentation/IOBluetooth/IOBluetoothHandsFreeAudioGateway"]]},"path":"/hierarchy"},{"value":null,"op":"add","path":"/topicSections"},{"value":null,"op":"add","path":"/relationshipsSections"},{"value":[{"anchor":"Showing-Status-Indicators","generated":true,"identifiers":["doc://com.apple.iobluetooth/documentation/IOBluetooth/status-indicator-constants"],"title":"Showing Status Indicators"}],"op":"replace","path":"/seeAlsoSections"},{"value":{"declarations":[{"platforms":["macOS"],"languages":["occ"],"tokens":[{"kind":"text","text":"- ("},{"preciseIdentifier":"c:v","kind":"typeIdentifier","text":"void"},{"kind":"text","text":") "},{"kind":"identifier","text":"createIndicator:"},{"kind":"text","text":"("},{"preciseIdentifier":"c:objc(cs)NSString","kind":"typeIdentifier","text":"NSString","identifier":"doc://com.externally.resolved.symbol/c:objc(cs)NSString"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"indicatorName"},{"kind":"text","text":" "},{"kind":"identifier","text":"min:"},{"kind":"text","text":"("},{"preciseIdentifier":"c:I","kind":"typeIdentifier","text":"int"},{"kind":"text","text":") "},{"kind":"internalParam","text":"minValue"},{"text":" ","kind":"text"},{"text":"max:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"int","preciseIdentifier":"c:I","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"maxValue","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"currentValue:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"int","preciseIdentifier":"c:I","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"currentValue","kind":"internalParam"},{"text":";","kind":"text"}]}],"kind":"declarations"},"op":"replace","path":"/primaryContentSections/0"},{"path":"/primaryContentSections/1","value":{"parameters":[{"content":[{"type":"paragraph","inlineContent":[{"text":"The name of the indicator. Use one of the following constants:","type":"text"}]},{"type":"unorderedList","items":[{"content":[{"inlineContent":[{"identifier":"doc://com.apple.iobluetooth/documentation/IOBluetooth/IOBluetoothHandsFreeIndicatorService","type":"reference","isActive":true}],"type":"paragraph"}]},{"content":[{"inlineContent":[{"type":"reference","identifier":"doc://com.apple.iobluetooth/documentation/IOBluetooth/IOBluetoothHandsFreeIndicatorCall","isActive":true}],"type":"paragraph"}]},{"content":[{"type":"paragraph","inlineContent":[{"identifier":"doc://com.apple.iobluetooth/documentation/IOBluetooth/IOBluetoothHandsFreeIndicatorCallSetup","isActive":true,"type":"reference"}]}]},{"content":[{"type":"paragraph","inlineContent":[{"identifier":"doc://com.apple.iobluetooth/documentation/IOBluetooth/IOBluetoothHandsFreeIndicatorCallHeld","type":"reference","isActive":true}]}]},{"content":[{"inlineContent":[{"type":"reference","identifier":"doc://com.apple.iobluetooth/documentation/IOBluetooth/IOBluetoothHandsFreeIndicatorSignal","isActive":true}],"type":"paragraph"}]},{"content":[{"inlineContent":[{"identifier":"doc://com.apple.iobluetooth/documentation/IOBluetooth/IOBluetoothHandsFreeIndicatorRoam","type":"reference","isActive":true}],"type":"paragraph"}]},{"content":[{"inlineContent":[{"type":"reference","isActive":true,"identifier":"doc://com.apple.iobluetooth/documentation/IOBluetooth/IOBluetoothHandsFreeIndicatorBattChg"}],"type":"paragraph"}]}]}],"name":"indicatorName"},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The minimum value for the indicator."}]}],"name":"minValue"},{"content":[{"type":"paragraph","inlineContent":[{"text":"The maximum value for the indicator.","type":"text"}]}],"name":"maxValue"},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The current value of the indicator."}]}],"name":"currentValue"}],"kind":"parameters"},"op":"replace"},{"value":"IOBluetoothHandsFreeIndicatorCallHeld","op":"replace","path":"/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1IOBluetoothHandsFreeIndicatorCallHeld/title"},{"value":[{"kind":"identifier","text":"IOBluetoothHandsFreeIndicatorCallHeld"}],"op":"replace","path":"/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1IOBluetoothHandsFreeIndicatorCallHeld/fragments"},{"value":"IOBluetoothHandsFreeIndicatorSignal","op":"replace","path":"/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1IOBluetoothHandsFreeIndicatorSignal/title"},{"value":[{"text":"IOBluetoothHandsFreeIndicatorSignal","kind":"identifier"}],"op":"replace","path":"/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1IOBluetoothHandsFreeIndicatorSignal/fragments"},{"value":"IOBluetoothHandsFreeIndicatorRoam","op":"replace","path":"/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1IOBluetoothHandsFreeIndicatorRoam/title"},{"value":[{"kind":"identifier","text":"IOBluetoothHandsFreeIndicatorRoam"}],"op":"replace","path":"/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1IOBluetoothHandsFreeIndicatorRoam/fragments"},{"value":"IOBluetoothHandsFreeIndicatorService","op":"replace","path":"/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1IOBluetoothHandsFreeIndicatorService/title"},{"value":[{"kind":"identifier","text":"IOBluetoothHandsFreeIndicatorService"}],"op":"replace","path":"/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1IOBluetoothHandsFreeIndicatorService/fragments"},{"value":"IOBluetoothHandsFreeIndicatorCall","op":"replace","path":"/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1IOBluetoothHandsFreeIndicatorCall/title"},{"value":[{"kind":"identifier","text":"IOBluetoothHandsFreeIndicatorCall"}],"op":"replace","path":"/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1IOBluetoothHandsFreeIndicatorCall/fragments"},{"value":[{"text":"A static, plain-text Unicode string object.","type":"text"}],"op":"replace","path":"/references/doc:~1~1com.externally.resolved.symbol~1c:objc(cs)NSString/abstract"},{"value":"createIndicator:min:max:currentValue:","op":"replace","path":"/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1IOBluetoothHandsFreeAudioGateway~1createIndicator(_:min:max:currentValue:)/title"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"createIndicator:min:max:currentValue:"}],"op":"replace","path":"/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1IOBluetoothHandsFreeAudioGateway~1createIndicator(_:min:max:currentValue:)/fragments"},{"value":"IOBluetoothHandsFreeIndicatorCallSetup","op":"replace","path":"/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1IOBluetoothHandsFreeIndicatorCallSetup/title"},{"value":[{"kind":"identifier","text":"IOBluetoothHandsFreeIndicatorCallSetup"}],"op":"replace","path":"/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1IOBluetoothHandsFreeIndicatorCallSetup/fragments"},{"value":"IOBluetoothHandsFreeAudioGateway","op":"replace","path":"/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1IOBluetoothHandsFreeAudioGateway/title"},{"value":[{"kind":"identifier","text":"IOBluetoothHandsFreeAudioGateway"}],"op":"replace","path":"/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1IOBluetoothHandsFreeAudioGateway/fragments"},{"value":[{"text":"IOBluetoothHandsFreeAudioGateway","kind":"identifier"}],"op":"replace","path":"/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1IOBluetoothHandsFreeAudioGateway/navigatorTitle"},{"value":"IOBluetoothHandsFreeIndicatorBattChg","op":"replace","path":"/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1IOBluetoothHandsFreeIndicatorBattChg/title"},{"value":[{"text":"IOBluetoothHandsFreeIndicatorBattChg","kind":"identifier"}],"op":"replace","path":"/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1IOBluetoothHandsFreeIndicatorBattChg/fragments"}]}],"legalNotices":{"copyright":"Copyright &copy; 2025 Apple Inc. All rights reserved.","termsOfUse":"https://www.apple.com/legal/internet-services/terms/site.html","privacyPolicy":"https://www.apple.com/privacy/privacy-policy"}}