{
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.appkit/documentation/AppKit",
        "doc://com.apple.appkit/documentation/AppKit/NSGridRow",
        "doc://com.apple.appkit/documentation/AppKit/NSGridRow/Alignment"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.appkit/documentation/AppKit/NSGridRow/Alignment/inherited"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@NSGridRowAlignment@NSGridRowAlignmentInherited",
    "fragments": [
      {
        "kind": "keyword",
        "text": "case"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "inherited"
      }
    ],
    "modules": [
      {
        "name": "AppKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "NSGridRowAlignmentInherited"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.12",
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Case",
    "symbolKind": "case",
    "title": "NSGridRow.Alignment.inherited"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "macOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "case"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "inherited"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.appkit/documentation/AppKit": {
      "abstract": [
        {
          "text": "Construct and manage a graphical, event-driven user interface for your macOS app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit",
      "kind": "symbol",
      "role": "collection",
      "title": "AppKit",
      "type": "topic",
      "url": "/documentation/appkit"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSGridRow": {
      "abstract": [
        {
          "text": "A row within a grid view.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSGridRow"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSGridRow",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSGridRow"
        }
      ],
      "role": "symbol",
      "title": "NSGridRow",
      "type": "topic",
      "url": "/documentation/appkit/nsgridrow"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSGridRow/Alignment": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Alignment"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSGridRow/Alignment",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "Alignment"
        }
      ],
      "role": "symbol",
      "title": "NSGridRow.Alignment",
      "type": "topic",
      "url": "/documentation/appkit/nsgridrow/alignment"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSGridRow/Alignment/firstBaseline": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "firstBaseline"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSGridRow/Alignment/firstBaseline",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSGridRowAlignmentFirstBaseline"
        }
      ],
      "role": "symbol",
      "title": "NSGridRow.Alignment.firstBaseline",
      "type": "topic",
      "url": "/documentation/appkit/nsgridrow/alignment/firstbaseline"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSGridRow/Alignment/inherited": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "inherited"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSGridRow/Alignment/inherited",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSGridRowAlignmentInherited"
        }
      ],
      "role": "symbol",
      "title": "NSGridRow.Alignment.inherited",
      "type": "topic",
      "url": "/documentation/appkit/nsgridrow/alignment/inherited"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSGridRow/Alignment/lastBaseline": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "lastBaseline"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSGridRow/Alignment/lastBaseline",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSGridRowAlignmentLastBaseline"
        }
      ],
      "role": "symbol",
      "title": "NSGridRow.Alignment.lastBaseline",
      "type": "topic",
      "url": "/documentation/appkit/nsgridrow/alignment/lastbaseline"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSGridRow/Alignment/none": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "none"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSGridRow/Alignment/none",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSGridRowAlignmentNone"
        }
      ],
      "role": "symbol",
      "title": "NSGridRow.Alignment.none",
      "type": "topic",
      "url": "/documentation/appkit/nsgridrow/alignment/none"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Row-Alignment-Options",
      "generated": true,
      "identifiers": [
        "doc://com.apple.appkit/documentation/AppKit/NSGridRow/Alignment/firstBaseline",
        "doc://com.apple.appkit/documentation/AppKit/NSGridRow/Alignment/lastBaseline",
        "doc://com.apple.appkit/documentation/AppKit/NSGridRow/Alignment/none"
      ],
      "title": "Row Alignment Options"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.12",
              "name": "macOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration Case"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "NSGridRowAlignmentInherited"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "case"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSGridRowAlignmentInherited"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.appkit/documentation/AppKit",
                "doc://com.apple.appkit/documentation/AppKit/NSGridRow/Alignment"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Row-Alignment-Options",
              "generated": true,
              "identifiers": [
                "doc://com.apple.appkit/documentation/AppKit/NSGridRow/Alignment/firstBaseline",
                "doc://com.apple.appkit/documentation/AppKit/NSGridRow/Alignment/lastBaseline",
                "doc://com.apple.appkit/documentation/AppKit/NSGridRow/Alignment/none"
              ],
              "title": "Row Alignment Options"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "Mac Catalyst",
                  "macOS"
                ],
                "tokens": [
                  {
                    "kind": "identifier",
                    "text": "NSGridRowAlignmentInherited"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSGridRow~1Alignment/title",
          "value": "NSGridRowAlignment"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSGridRow~1Alignment/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSGridRowAlignment"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSGridRow~1Alignment/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSGridRowAlignment"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSGridRow~1Alignment~1inherited/title",
          "value": "NSGridRowAlignmentInherited"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSGridRow~1Alignment~1inherited/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSGridRowAlignmentInherited"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSGridRow~1Alignment~1none/title",
          "value": "NSGridRowAlignmentNone"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSGridRow~1Alignment~1none/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSGridRowAlignmentNone"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSGridRow/title",
          "value": "NSGridRow"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSGridRow/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSGridRow"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSGridRow/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSGridRow"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSGridRow~1Alignment~1firstBaseline/title",
          "value": "NSGridRowAlignmentFirstBaseline"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSGridRow~1Alignment~1firstBaseline/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSGridRowAlignmentFirstBaseline"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSGridRow~1Alignment~1lastBaseline/title",
          "value": "NSGridRowAlignmentLastBaseline"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSGridRow~1Alignment~1lastBaseline/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSGridRowAlignmentLastBaseline"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/appkit/nsgridrow/alignment/inherited"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/appkit/nsgridrow/alignment/inherited"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
