{
  "abstract": [
    {
      "text": "Dequeues a buffer from the queue, if it’s ready.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.coremedia/documentation/CoreMedia",
        "doc://com.apple.coremedia/documentation/CoreMedia/CMBufferQueue"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.coremedia/documentation/CoreMedia/CMBufferQueue/dequeueIfDataReady()"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "extendedModule": "CoreMedia",
    "externalID": "s:So16CMBufferQueueRefa9CoreMediaE18dequeueIfDataReadyyXlSgyF",
    "fragments": [
      {
        "kind": "keyword",
        "text": "func"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "dequeueIfDataReady"
      },
      {
        "kind": "text",
        "text": "() -> "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@T@CMBufferRef",
        "text": "CMBuffer"
      },
      {
        "kind": "text",
        "text": "?"
      }
    ],
    "modules": [
      {
        "name": "Core Media"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.15",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.0",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "6.0",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Instance Method",
    "symbolKind": "method",
    "title": "dequeueIfDataReady()"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "func"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "dequeueIfDataReady"
            },
            {
              "kind": "text",
              "text": "() -> "
            },
            {
              "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/CMBuffer",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@CMBufferRef",
              "text": "CMBuffer"
            },
            {
              "kind": "text",
              "text": "?"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "return-value",
          "level": 2,
          "text": "Return Value",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "A buffer or ",
              "type": "text"
            },
            {
              "code": "nil",
              "type": "codeVoice"
            },
            {
              "text": " if the buffer is empty or the data isn’t ready.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.coremedia/documentation/CoreMedia": {
      "abstract": [
        {
          "text": "Represent time-based audio-visual assets with essential data types.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia",
      "kind": "symbol",
      "role": "collection",
      "title": "Core Media",
      "type": "topic",
      "url": "/documentation/coremedia"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/CMBuffer": {
      "abstract": [
        {
          "text": "A reference to a buffer object.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CMBuffer"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/CMBuffer",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CMBuffer"
        }
      ],
      "role": "symbol",
      "title": "CMBuffer",
      "type": "topic",
      "url": "/documentation/coremedia/cmbuffer"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/CMBufferQueue": {
      "abstract": [
        {
          "text": "A reference to a buffer queue instance.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CMBufferQueue"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/CMBufferQueue",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CMBufferQueue"
        }
      ],
      "role": "symbol",
      "title": "CMBufferQueue",
      "type": "topic",
      "url": "/documentation/coremedia/cmbufferqueue"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/CMBufferQueue/dequeue()": {
      "abstract": [
        {
          "text": "Dequeues a buffer from the queue.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "dequeue"
        },
        {
          "kind": "text",
          "text": "() -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CMBufferRef",
          "text": "CMBuffer"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/CMBufferQueue/dequeue()",
      "kind": "symbol",
      "role": "symbol",
      "title": "dequeue()",
      "type": "topic",
      "url": "/documentation/coremedia/cmbufferqueue/dequeue()"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/CMBufferQueue/dequeueIfDataReady()": {
      "abstract": [
        {
          "text": "Dequeues a buffer from the queue, if it’s ready.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "dequeueIfDataReady"
        },
        {
          "kind": "text",
          "text": "() -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CMBufferRef",
          "text": "CMBuffer"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/CMBufferQueue/dequeueIfDataReady()",
      "kind": "symbol",
      "role": "symbol",
      "title": "dequeueIfDataReady()",
      "type": "topic",
      "url": "/documentation/coremedia/cmbufferqueue/dequeueifdataready()"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/CMBufferQueue/enqueue(_:)": {
      "abstract": [
        {
          "text": "Enqueues a buffer to the queue.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "enqueue"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CMBufferRef",
          "text": "CMBuffer"
        },
        {
          "kind": "text",
          "text": ") "
        },
        {
          "kind": "keyword",
          "text": "throws"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/CMBufferQueue/enqueue(_:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "enqueue(_:)",
      "type": "topic",
      "url": "/documentation/coremedia/cmbufferqueue/enqueue(_:)"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/CMBufferQueue/markEndOfData()": {
      "abstract": [
        {
          "text": "Marks a buffer as being at the end of its data.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "markEndOfData"
        },
        {
          "kind": "text",
          "text": "() "
        },
        {
          "kind": "keyword",
          "text": "throws"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/CMBufferQueue/markEndOfData()",
      "kind": "symbol",
      "role": "symbol",
      "title": "markEndOfData()",
      "type": "topic",
      "url": "/documentation/coremedia/cmbufferqueue/markendofdata()"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/CMBufferQueue/reset()": {
      "abstract": [
        {
          "text": "Empties the queue and resets its end-of-data state.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "reset"
        },
        {
          "kind": "text",
          "text": "() "
        },
        {
          "kind": "keyword",
          "text": "throws"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/CMBufferQueue/reset()",
      "kind": "symbol",
      "role": "symbol",
      "title": "reset()",
      "type": "topic",
      "url": "/documentation/coremedia/cmbufferqueue/reset()"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/CMBufferQueue/reset(_:)": {
      "abstract": [
        {
          "text": "Resets a buffer with a callback block.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "reset"
        },
        {
          "kind": "text",
          "text": "(("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CMBufferRef",
          "text": "CMBuffer"
        },
        {
          "kind": "text",
          "text": ") "
        },
        {
          "kind": "keyword",
          "text": "throws"
        },
        {
          "kind": "text",
          "text": " -> ()) "
        },
        {
          "kind": "keyword",
          "text": "throws"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/CMBufferQueue/reset(_:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "reset(_:)",
      "type": "topic",
      "url": "/documentation/coremedia/cmbufferqueue/reset(_:)"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Managing-a-Queue",
      "generated": true,
      "identifiers": [
        "doc://com.apple.coremedia/documentation/CoreMedia/CMBufferQueue/enqueue(_:)",
        "doc://com.apple.coremedia/documentation/CoreMedia/CMBufferQueue/dequeue()",
        "doc://com.apple.coremedia/documentation/CoreMedia/CMBufferQueue/markEndOfData()",
        "doc://com.apple.coremedia/documentation/CoreMedia/CMBufferQueue/reset()",
        "doc://com.apple.coremedia/documentation/CoreMedia/CMBufferQueue/reset(_:)"
      ],
      "title": "Managing a Queue"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1CMBufferQueue/title",
          "value": "CMBufferQueueRef"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1CMBufferQueue/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CMBufferQueueRef"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1CMBufferQueue/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CMBufferQueueRef"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1CMBuffer/title",
          "value": "CMBufferRef"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1CMBuffer/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CMBufferRef"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1CMBuffer/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CMBufferRef"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/coremedia/cmbufferqueue/dequeueifdataready()"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    }
  ]
}
