{
  "abstract": [
    {
      "text": "A keyboard shortcut that invokes the service menu command.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.bundleresources/documentation/BundleResources",
        "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List",
        "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSServices"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSServices/NSKeyEquivalent"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "plist:Information_Property_List.NSServices.NSKeyEquivalent",
    "modules": [
      {
        "name": "Bundle Resources"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "NSKeyEquivalent"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.0",
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Property List Key",
    "symbolKind": "dictionary",
    "title": "NSKeyEquivalent"
  },
  "primaryContentSections": [
    {
      "details": {
        "ideTitle": "Menu key equivalent",
        "name": "NSKeyEquivalent",
        "platforms": [],
        "titleStyle": "symbol",
        "value": [
          {
            "arrayMode": false,
            "baseType": "object"
          }
        ]
      },
      "kind": "details",
      "title": "Details"
    },
    {
      "items": [
        {
          "attributes": [],
          "content": [],
          "introducedVersion": "10.0.0",
          "name": "default",
          "required": true,
          "type": [
            {
              "kind": "text",
              "text": "string"
            }
          ]
        }
      ],
      "kind": "properties",
      "title": "Properties"
    },
    {
      "content": [
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "The dictionary key is ",
              "type": "text"
            },
            {
              "code": "default",
              "type": "codeVoice"
            },
            {
              "text": " with a string value.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.bundleresources/documentation/BundleResources": {
      "abstract": [
        {
          "text": "Resources located in an app, framework, or plugin bundle.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources",
      "kind": "symbol",
      "role": "collection",
      "title": "Bundle Resources",
      "type": "topic",
      "url": "/documentation/bundleresources"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List": {
      "abstract": [
        {
          "text": "A resource containing key-value pairs that identify and configure a bundle.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List",
      "kind": "symbol",
      "name": "Information Property List",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "Information Property List"
        }
      ],
      "role": "symbol",
      "title": "Information Property List",
      "titleStyle": "symbol",
      "type": "topic",
      "url": "/documentation/bundleresources/information-property-list"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSServices": {
      "abstract": [
        {
          "text": "The services provided by an app.",
          "type": "text"
        }
      ],
      "ideTitle": "Services",
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSServices",
      "kind": "symbol",
      "name": "NSServices",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSServices"
        }
      ],
      "role": "symbol",
      "title": "NSServices",
      "titleStyle": "symbol",
      "type": "topic",
      "url": "/documentation/bundleresources/information-property-list/nsservices"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSServices/NSKeyEquivalent": {
      "abstract": [
        {
          "text": "A keyboard shortcut that invokes the service menu command.",
          "type": "text"
        }
      ],
      "ideTitle": "Menu key equivalent",
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSServices/NSKeyEquivalent",
      "kind": "symbol",
      "name": "NSKeyEquivalent",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSKeyEquivalent"
        }
      ],
      "role": "symbol",
      "title": "NSKeyEquivalent",
      "titleStyle": "symbol",
      "type": "topic",
      "url": "/documentation/bundleresources/information-property-list/nsservices/nskeyequivalent"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSServices/NSMenuItem": {
      "abstract": [
        {
          "text": "Text for a Services menu item.",
          "type": "text"
        }
      ],
      "ideTitle": "Menu",
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSServices/NSMenuItem",
      "kind": "symbol",
      "name": "NSMenuItem",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSMenuItem"
        }
      ],
      "role": "symbol",
      "title": "NSMenuItem",
      "titleStyle": "symbol",
      "type": "topic",
      "url": "/documentation/bundleresources/information-property-list/nsservices/nsmenuitem"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSServices/NSMessage": {
      "abstract": [
        {
          "text": "An instance method that invokes the service.",
          "type": "text"
        }
      ],
      "ideTitle": "Instance method name",
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSServices/NSMessage",
      "kind": "symbol",
      "name": "NSMessage",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSMessage"
        }
      ],
      "role": "symbol",
      "title": "NSMessage",
      "titleStyle": "symbol",
      "type": "topic",
      "url": "/documentation/bundleresources/information-property-list/nsservices/nsmessage"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSServices/NSPortName": {
      "abstract": [
        {
          "text": "The port that the service monitors for incoming requests.",
          "type": "text"
        }
      ],
      "ideTitle": "Incoming service port name",
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSServices/NSPortName",
      "kind": "symbol",
      "name": "NSPortName",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSPortName"
        }
      ],
      "role": "symbol",
      "title": "NSPortName",
      "titleStyle": "symbol",
      "type": "topic",
      "url": "/documentation/bundleresources/information-property-list/nsservices/nsportname"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSServices/NSTimeout": {
      "abstract": [
        {
          "text": "The amount of time, in milliseconds, that the system waits for a response from the service.",
          "type": "text"
        }
      ],
      "ideTitle": "Timeout value (in milliseconds)",
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSServices/NSTimeout",
      "kind": "symbol",
      "name": "NSTimeout",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSTimeout"
        }
      ],
      "role": "symbol",
      "title": "NSTimeout",
      "titleStyle": "symbol",
      "type": "topic",
      "url": "/documentation/bundleresources/information-property-list/nsservices/nstimeout"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Invocation",
      "generated": true,
      "identifiers": [
        "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSServices/NSMenuItem",
        "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSServices/NSMessage",
        "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSServices/NSPortName",
        "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSServices/NSTimeout"
      ],
      "title": "Invocation"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.0",
              "name": "macOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Property List Key"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "NSKeyEquivalent"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "dictionary"
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSKeyEquivalent"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.bundleresources/documentation/BundleResources",
                "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List",
                "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSServices"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Invocation",
              "generated": true,
              "identifiers": [
                "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSServices/NSMenuItem",
                "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSServices/NSMessage",
                "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSServices/NSPortName",
                "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSServices/NSTimeout"
              ],
              "title": "Invocation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/3",
          "value": {
            "items": [
              {
                "attributes": [],
                "content": [],
                "introducedVersion": "10.0.0",
                "name": "default",
                "required": true,
                "type": [
                  {
                    "kind": "text",
                    "text": "string"
                  }
                ]
              }
            ],
            "kind": "properties",
            "title": "Properties"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1NSServices~1NSTimeout/title",
          "value": "NSTimeout"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1NSServices~1NSTimeout/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSTimeout"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1NSServices~1NSPortName/title",
          "value": "NSPortName"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1NSServices~1NSPortName/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSPortName"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1NSServices~1NSMenuItem/title",
          "value": "NSMenuItem"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1NSServices~1NSMenuItem/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSMenuItem"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List/title",
          "value": "Information Property List"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "Information Property List"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1NSServices~1NSMessage/title",
          "value": "NSMessage"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1NSServices~1NSMessage/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSMessage"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1NSServices~1NSKeyEquivalent/title",
          "value": "NSKeyEquivalent"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1NSServices~1NSKeyEquivalent/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSKeyEquivalent"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1NSServices/title",
          "value": "NSServices"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1NSServices/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSServices"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/bundleresources/information-property-list/nsservices/nskeyequivalent"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/bundleresources/information-property-list/nsservices/nskeyequivalent"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
