{
  "abstract": [
    {
      "text": "The data types that the service can read.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.bundleresources/documentation/BundleResources",
        "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List",
        "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSServices"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSServices/NSSendTypes"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "plist:Information_Property_List.NSServices.NSSendTypes",
    "modules": [
      {
        "name": "Bundle Resources"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "NSSendTypes"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.0",
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Property List Key",
    "symbolKind": "typealias",
    "title": "NSSendTypes"
  },
  "primaryContentSections": [
    {
      "details": {
        "ideTitle": "Send Types",
        "name": "NSSendTypes",
        "platforms": [],
        "titleStyle": "symbol",
        "value": [
          {
            "arrayMode": true,
            "baseType": "string "
          }
        ]
      },
      "kind": "details",
      "title": "Details"
    }
  ],
  "references": {
    "doc://com.apple.bundleresources/documentation/BundleResources": {
      "abstract": [
        {
          "text": "Resources located in an app, framework, or plugin bundle.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources",
      "kind": "symbol",
      "role": "collection",
      "title": "Bundle Resources",
      "type": "topic",
      "url": "/documentation/bundleresources"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List": {
      "abstract": [
        {
          "text": "A resource containing key-value pairs that identify and configure a bundle.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List",
      "kind": "symbol",
      "name": "Information Property List",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "Information Property List"
        }
      ],
      "role": "symbol",
      "title": "Information Property List",
      "titleStyle": "symbol",
      "type": "topic",
      "url": "/documentation/bundleresources/information-property-list"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSServices": {
      "abstract": [
        {
          "text": "The services provided by an app.",
          "type": "text"
        }
      ],
      "ideTitle": "Services",
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSServices",
      "kind": "symbol",
      "name": "NSServices",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSServices"
        }
      ],
      "role": "symbol",
      "title": "NSServices",
      "titleStyle": "symbol",
      "type": "topic",
      "url": "/documentation/bundleresources/information-property-list/nsservices"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSServices/NSReturnTypes": {
      "abstract": [
        {
          "text": "The data types that the service returns.",
          "type": "text"
        }
      ],
      "ideTitle": "Return Types",
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSServices/NSReturnTypes",
      "kind": "symbol",
      "name": "NSReturnTypes",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSReturnTypes"
        }
      ],
      "role": "symbol",
      "title": "NSReturnTypes",
      "titleStyle": "symbol",
      "type": "topic",
      "url": "/documentation/bundleresources/information-property-list/nsservices/nsreturntypes"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSServices/NSSendTypes": {
      "abstract": [
        {
          "text": "The data types that the service can read.",
          "type": "text"
        }
      ],
      "ideTitle": "Send Types",
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSServices/NSSendTypes",
      "kind": "symbol",
      "name": "NSSendTypes",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSSendTypes"
        }
      ],
      "role": "symbol",
      "title": "NSSendTypes",
      "titleStyle": "symbol",
      "type": "topic",
      "url": "/documentation/bundleresources/information-property-list/nsservices/nssendtypes"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSServices/NSUserData": {
      "abstract": [
        {
          "text": "A service-specific string value.",
          "type": "text"
        }
      ],
      "ideTitle": "User Data",
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSServices/NSUserData",
      "kind": "symbol",
      "name": "NSUserData",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSUserData"
        }
      ],
      "role": "symbol",
      "title": "NSUserData",
      "titleStyle": "symbol",
      "type": "topic",
      "url": "/documentation/bundleresources/information-property-list/nsservices/nsuserdata"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Data",
      "generated": true,
      "identifiers": [
        "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSServices/NSReturnTypes",
        "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSServices/NSUserData"
      ],
      "title": "Data"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.0",
              "name": "macOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Property List Key"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "NSSendTypes"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "typealias"
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSSendTypes"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.bundleresources/documentation/BundleResources",
                "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List",
                "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSServices"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Data",
              "generated": true,
              "identifiers": [
                "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSServices/NSReturnTypes",
                "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSServices/NSUserData"
              ],
              "title": "Data"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1NSServices~1NSUserData/title",
          "value": "NSUserData"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1NSServices~1NSUserData/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSUserData"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List/title",
          "value": "Information Property List"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "Information Property List"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1NSServices~1NSSendTypes/title",
          "value": "NSSendTypes"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1NSServices~1NSSendTypes/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSSendTypes"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1NSServices/title",
          "value": "NSServices"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1NSServices/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSServices"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1NSServices~1NSReturnTypes/title",
          "value": "NSReturnTypes"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1NSServices~1NSReturnTypes/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSReturnTypes"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/bundleresources/information-property-list/nsservices/nssendtypes"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/bundleresources/information-property-list/nsservices/nssendtypes"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
