{"sections":[],"schemaVersion":{"major":0,"minor":3,"patch":0},"abstract":[{"type":"text","text":"The current proposal for how to incorporate the dropped items."}],"primaryContentSections":[{"declarations":[{"platforms":["iOS","iPadOS","Mac Catalyst","visionOS"],"tokens":[{"kind":"attribute","text":"@"},{"identifier":"doc://com.externally.resolved.symbol/s:ScM","preciseIdentifier":"s:ScM","kind":"attribute","text":"MainActor"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"proposal"},{"kind":"text","text":": "},{"identifier":"doc://com.apple.uikit/documentation/UIKit/UICollectionViewDropProposal","preciseIdentifier":"c:objc(cs)UICollectionViewDropProposal","kind":"typeIdentifier","text":"UICollectionViewDropProposal"},{"kind":"text","text":" { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" }"}],"languages":["swift"]}],"kind":"declarations"},{"content":[{"type":"heading","anchor":"Discussion","level":2,"text":"Discussion"},{"inlineContent":[{"text":"If your drag delegate implements the ","type":"text"},{"isActive":true,"type":"reference","identifier":"doc://com.apple.uikit/documentation/UIKit/UICollectionViewDropDelegate/collectionView(_:dropSessionDidUpdate:withDestinationIndexPath:)"},{"text":" method, this object contains the information that you provided when making your drop proposal for the given location.","type":"text"}],"type":"paragraph"}],"kind":"content"}],"metadata":{"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"proposal"}],"modules":[{"name":"UIKit"}],"symbolKind":"property","title":"proposal","roleHeading":"Instance Property","required":true,"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"proposal"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)UICollectionViewDropProposal","kind":"typeIdentifier","text":"UICollectionViewDropProposal"}],"platforms":[{"introducedAt":"11.0","unavailable":false,"name":"iOS","deprecated":false,"beta":false},{"unavailable":false,"beta":false,"deprecated":false,"name":"iPadOS","introducedAt":"11.0"},{"unavailable":false,"beta":false,"deprecated":false,"name":"Mac Catalyst","introducedAt":"13.1"},{"unavailable":false,"beta":false,"deprecated":false,"name":"visionOS","introducedAt":"1.0"}],"externalID":"c:objc(pl)UICollectionViewDropCoordinator(py)proposal"},"variants":[{"paths":["/documentation/uikit/uicollectionviewdropcoordinator/proposal"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["/documentation/uikit/uicollectionviewdropcoordinator/proposal"],"traits":[{"interfaceLanguage":"occ"}]}],"seeAlsoSections":[{"anchor":"Getting-the-Session-Information","generated":true,"identifiers":["doc://com.apple.uikit/documentation/UIKit/UICollectionViewDropCoordinator/session"],"title":"Getting the Session Information"}],"hierarchy":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.uikit/documentation/UIKit","doc://com.apple.uikit/documentation/UIKit/UICollectionViewDropCoordinator"]]},"kind":"symbol","identifier":{"url":"doc://com.apple.uikit/documentation/UIKit/UICollectionViewDropCoordinator/proposal","interfaceLanguage":"swift"},"references":{"doc://com.apple.documentation/documentation/technologies":{"role":"overview","url":"/documentation/technologies","title":"Technologies","identifier":"doc://com.apple.documentation/documentation/technologies","abstract":[{"text":"","type":"text"}],"kind":"technologies","type":"topic"},"doc://com.apple.uikit/documentation/UIKit/UICollectionViewDropCoordinator/proposal":{"navigatorTitle":[{"text":"proposal","kind":"identifier"}],"url":"/documentation/uikit/uicollectionviewdropcoordinator/proposal","identifier":"doc://com.apple.uikit/documentation/UIKit/UICollectionViewDropCoordinator/proposal","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"proposal","kind":"identifier"},{"text":": ","kind":"text"},{"text":"UICollectionViewDropProposal","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UICollectionViewDropProposal"}],"role":"symbol","title":"proposal","kind":"symbol","required":true,"abstract":[{"type":"text","text":"The current proposal for how to incorporate the dropped items."}],"type":"topic"},"doc://com.apple.uikit/documentation/UIKit/UICollectionViewDropCoordinator":{"navigatorTitle":[{"text":"UICollectionViewDropCoordinator","kind":"identifier"}],"fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"UICollectionViewDropCoordinator","kind":"identifier"}],"kind":"symbol","url":"/documentation/uikit/uicollectionviewdropcoordinator","title":"UICollectionViewDropCoordinator","identifier":"doc://com.apple.uikit/documentation/UIKit/UICollectionViewDropCoordinator","type":"topic","role":"symbol","abstract":[{"type":"text","text":"An interface for coordinating your custom drop-related actions with the collection view."}]},"doc://com.apple.uikit/documentation/UIKit":{"kind":"symbol","role":"collection","title":"UIKit","identifier":"doc://com.apple.uikit/documentation/UIKit","url":"/documentation/uikit","abstract":[{"type":"text","text":"Construct and manage a graphical, event-driven user interface for your iOS, iPadOS, or tvOS app."}],"type":"topic"},"doc://com.apple.uikit/documentation/UIKit/UICollectionViewDropCoordinator/session":{"navigatorTitle":[{"text":"session","kind":"identifier"}],"url":"/documentation/uikit/uicollectionviewdropcoordinator/session","identifier":"doc://com.apple.uikit/documentation/UIKit/UICollectionViewDropCoordinator/session","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"session","kind":"identifier"},{"text":": any ","kind":"text"},{"text":"UIDropSession","kind":"typeIdentifier","preciseIdentifier":"c:objc(pl)UIDropSession"}],"role":"symbol","title":"session","kind":"symbol","required":true,"abstract":[{"type":"text","text":"The drop session containing information about the transaction."}],"type":"topic"},"doc://com.externally.resolved.symbol/s:ScM":{"abstract":[{"text":"A singleton actor whose executor is equivalent to the main dispatch queue.","type":"text"}],"url":"/documentation/Swift/MainActor","identifier":"doc://com.externally.resolved.symbol/s:ScM","title":"MainActor","fragments":[{"text":"@globalActor","kind":"attribute"},{"text":" ","kind":"text"},{"text":"final","kind":"keyword"},{"text":" ","kind":"text"},{"text":"actor","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MainActor","kind":"identifier"}],"type":"topic","kind":"symbol","role":"symbol"},"doc://com.apple.uikit/documentation/UIKit/UICollectionViewDropDelegate/collectionView(_:dropSessionDidUpdate:withDestinationIndexPath:)":{"type":"topic","url":"/documentation/uikit/uicollectionviewdropdelegate/collectionview(_:dropsessiondidupdate:withdestinationindexpath:)","kind":"symbol","role":"symbol","abstract":[{"text":"Tells your delegate that the position of the dragged data over the collection view changed.","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"collectionView:dropSessionDidUpdate:withDestinationIndexPath:"}],"title":"collectionView(_:dropSessionDidUpdate:withDestinationIndexPath:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"collectionView"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"UICollectionView","preciseIdentifier":"c:objc(cs)UICollectionView"},{"text":", ","kind":"text"},{"text":"dropSessionDidUpdate","kind":"externalParam"},{"text":": any ","kind":"text"},{"text":"UIDropSession","preciseIdentifier":"c:objc(pl)UIDropSession","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"withDestinationIndexPath","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"IndexPath","preciseIdentifier":"s:10Foundation9IndexPathV","kind":"typeIdentifier"},{"text":"?) -> ","kind":"text"},{"preciseIdentifier":"c:objc(cs)UICollectionViewDropProposal","kind":"typeIdentifier","text":"UICollectionViewDropProposal"}],"identifier":"doc://com.apple.uikit/documentation/UIKit/UICollectionViewDropDelegate/collectionView(_:dropSessionDidUpdate:withDestinationIndexPath:)"},"doc://com.apple.uikit/documentation/UIKit/UICollectionViewDropProposal":{"type":"topic","kind":"symbol","role":"symbol","navigatorTitle":[{"text":"UICollectionViewDropProposal","kind":"identifier"}],"title":"UICollectionViewDropProposal","url":"/documentation/uikit/uicollectionviewdropproposal","abstract":[{"text":"Your proposed solution for handling a drop in a collection view.","type":"text"}],"identifier":"doc://com.apple.uikit/documentation/UIKit/UICollectionViewDropProposal","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"UICollectionViewDropProposal","kind":"identifier"}]}},"variantOverrides":[{"patch":[{"op":"replace","path":"/identifier/interfaceLanguage","value":"occ"},{"op":"replace","path":"/metadata/platforms","value":[{"name":"iOS","unavailable":false,"introducedAt":"11.0","beta":false,"deprecated":false},{"unavailable":false,"beta":false,"deprecated":false,"name":"iPadOS","introducedAt":"11.0"},{"unavailable":false,"beta":false,"deprecated":false,"name":"Mac Catalyst","introducedAt":"13.1"},{"unavailable":false,"beta":false,"deprecated":false,"name":"visionOS","introducedAt":"1.0"}]},{"op":"replace","path":"/metadata/roleHeading","value":"Instance Property"},{"op":"replace","path":"/metadata/title","value":"proposal"},{"op":"replace","path":"/metadata/symbolKind","value":"property"},{"op":"replace","path":"/metadata/fragments","value":[{"text":"proposal","kind":"identifier"}]},{"op":"replace","path":"/hierarchy","value":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.uikit/documentation/UIKit","doc://com.apple.uikit/documentation/UIKit/UICollectionViewDropCoordinator"]]}},{"path":"/topicSections","op":"add","value":null},{"path":"/relationshipsSections","op":"add","value":null},{"path":"/seeAlsoSections","op":"replace","value":[{"identifiers":["doc://com.apple.uikit/documentation/UIKit/UICollectionViewDropCoordinator/session"],"generated":true,"title":"Getting the Session Information","anchor":"Getting-the-Session-Information"}]},{"path":"/primaryContentSections/0","op":"replace","value":{"kind":"declarations","declarations":[{"platforms":["iOS","iPadOS","Mac Catalyst","tvOS","visionOS"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"identifier":"doc://com.apple.uikit/documentation/UIKit/UICollectionViewDropProposal","kind":"typeIdentifier","text":"UICollectionViewDropProposal","preciseIdentifier":"c:objc(cs)UICollectionViewDropProposal"},{"kind":"text","text":" * "},{"kind":"identifier","text":"proposal"},{"kind":"text","text":";"}],"languages":["occ"]}]}},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UICollectionViewDropCoordinator~1proposal/title","op":"replace","value":"proposal"},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UICollectionViewDropCoordinator~1proposal/fragments","op":"replace","value":[{"text":"proposal","kind":"identifier"}]},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UICollectionViewDropCoordinator/title","op":"replace","value":"UICollectionViewDropCoordinator"},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UICollectionViewDropCoordinator/fragments","op":"replace","value":[{"kind":"identifier","text":"UICollectionViewDropCoordinator"}]},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UICollectionViewDropCoordinator/navigatorTitle","op":"replace","value":[{"text":"UICollectionViewDropCoordinator","kind":"identifier"}]},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UICollectionViewDropCoordinator~1session/title","op":"replace","value":"session"},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UICollectionViewDropCoordinator~1session/fragments","op":"replace","value":[{"text":"session","kind":"identifier"}]},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UICollectionViewDropDelegate~1collectionView(_:dropSessionDidUpdate:withDestinationIndexPath:)/title","op":"replace","value":"collectionView:dropSessionDidUpdate:withDestinationIndexPath:"},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UICollectionViewDropDelegate~1collectionView(_:dropSessionDidUpdate:withDestinationIndexPath:)/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"text":"collectionView:dropSessionDidUpdate:withDestinationIndexPath:","kind":"identifier"}]},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UICollectionViewDropProposal/title","op":"replace","value":"UICollectionViewDropProposal"},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UICollectionViewDropProposal/fragments","op":"replace","value":[{"kind":"identifier","text":"UICollectionViewDropProposal"}]},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UICollectionViewDropProposal/navigatorTitle","op":"replace","value":[{"text":"UICollectionViewDropProposal","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}],"legalNotices":{"copyright":"Copyright &copy; 2025 Apple Inc. All rights reserved.","termsOfUse":"https://www.apple.com/legal/internet-services/terms/site.html","privacyPolicy":"https://www.apple.com/privacy/privacy-policy"}}