{"metadata":{"navigatorTitle":[{"kind":"identifier","text":"session"}],"role":"symbol","symbolKind":"property","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"session"},{"kind":"text","text":": any "},{"kind":"typeIdentifier","text":"UIDropSession","preciseIdentifier":"c:objc(pl)UIDropSession"}],"externalID":"c:objc(pl)UICollectionViewDropCoordinator(py)session","modules":[{"name":"UIKit"}],"platforms":[{"introducedAt":"11.0","unavailable":false,"deprecated":false,"name":"iOS","beta":false},{"introducedAt":"11.0","unavailable":false,"deprecated":false,"name":"iPadOS","beta":false},{"introducedAt":"13.1","unavailable":false,"deprecated":false,"name":"Mac Catalyst","beta":false},{"introducedAt":"1.0","unavailable":false,"deprecated":false,"name":"visionOS","beta":false}],"title":"session","required":true,"roleHeading":"Instance Property"},"schemaVersion":{"major":0,"minor":3,"patch":0},"identifier":{"interfaceLanguage":"swift","url":"doc://com.apple.uikit/documentation/UIKit/UICollectionViewDropCoordinator/session"},"seeAlsoSections":[{"generated":true,"anchor":"Getting-the-Session-Information","title":"Getting the Session Information","identifiers":["doc://com.apple.uikit/documentation/UIKit/UICollectionViewDropCoordinator/proposal"]}],"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS","iPadOS","Mac Catalyst","visionOS"],"tokens":[{"kind":"attribute","text":"@"},{"identifier":"doc://com.externally.resolved.symbol/s:ScM","preciseIdentifier":"s:ScM","kind":"attribute","text":"MainActor"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"session"},{"kind":"text","text":": any "},{"identifier":"doc://com.apple.uikit/documentation/UIKit/UIDropSession","preciseIdentifier":"c:objc(pl)UIDropSession","kind":"typeIdentifier","text":"UIDropSession"},{"kind":"text","text":" { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" }"}]}]}],"hierarchy":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.uikit/documentation/UIKit","doc://com.apple.uikit/documentation/UIKit/UICollectionViewDropCoordinator"]]},"sections":[],"abstract":[{"type":"text","text":"The drop session containing information about the transaction."}],"variants":[{"paths":["/documentation/uikit/uicollectionviewdropcoordinator/session"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["/documentation/uikit/uicollectionviewdropcoordinator/session"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://com.apple.uikit/documentation/UIKit":{"kind":"symbol","role":"collection","title":"UIKit","identifier":"doc://com.apple.uikit/documentation/UIKit","url":"/documentation/uikit","abstract":[{"type":"text","text":"Construct and manage a graphical, event-driven user interface for your iOS, iPadOS, or tvOS app."}],"type":"topic"},"doc://com.apple.uikit/documentation/UIKit/UICollectionViewDropCoordinator/session":{"navigatorTitle":[{"text":"session","kind":"identifier"}],"url":"/documentation/uikit/uicollectionviewdropcoordinator/session","identifier":"doc://com.apple.uikit/documentation/UIKit/UICollectionViewDropCoordinator/session","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"session","kind":"identifier"},{"text":": any ","kind":"text"},{"text":"UIDropSession","kind":"typeIdentifier","preciseIdentifier":"c:objc(pl)UIDropSession"}],"role":"symbol","title":"session","kind":"symbol","required":true,"abstract":[{"type":"text","text":"The drop session containing information about the transaction."}],"type":"topic"},"doc://com.apple.documentation/documentation/technologies":{"role":"overview","url":"/documentation/technologies","title":"Technologies","identifier":"doc://com.apple.documentation/documentation/technologies","abstract":[{"text":"","type":"text"}],"kind":"technologies","type":"topic"},"doc://com.apple.uikit/documentation/UIKit/UICollectionViewDropCoordinator/proposal":{"navigatorTitle":[{"text":"proposal","kind":"identifier"}],"url":"/documentation/uikit/uicollectionviewdropcoordinator/proposal","identifier":"doc://com.apple.uikit/documentation/UIKit/UICollectionViewDropCoordinator/proposal","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"proposal","kind":"identifier"},{"text":": ","kind":"text"},{"text":"UICollectionViewDropProposal","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UICollectionViewDropProposal"}],"role":"symbol","title":"proposal","kind":"symbol","required":true,"abstract":[{"type":"text","text":"The current proposal for how to incorporate the dropped items."}],"type":"topic"},"doc://com.apple.uikit/documentation/UIKit/UIDropSession":{"abstract":[{"type":"text","text":"The interface for querying a drop session about its state and associated drag items."}],"url":"/documentation/uikit/uidropsession","identifier":"doc://com.apple.uikit/documentation/UIKit/UIDropSession","title":"UIDropSession","fragments":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"text":"UIDropSession","kind":"identifier"}],"navigatorTitle":[{"text":"UIDropSession","kind":"identifier"}],"type":"topic","kind":"symbol","role":"symbol"},"doc://com.externally.resolved.symbol/s:ScM":{"abstract":[{"text":"A singleton actor whose executor is equivalent to the main dispatch queue.","type":"text"}],"url":"/documentation/Swift/MainActor","identifier":"doc://com.externally.resolved.symbol/s:ScM","title":"MainActor","fragments":[{"text":"@globalActor","kind":"attribute"},{"text":" ","kind":"text"},{"text":"final","kind":"keyword"},{"text":" ","kind":"text"},{"text":"actor","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MainActor","kind":"identifier"}],"type":"topic","kind":"symbol","role":"symbol"},"doc://com.apple.uikit/documentation/UIKit/UICollectionViewDropCoordinator":{"navigatorTitle":[{"text":"UICollectionViewDropCoordinator","kind":"identifier"}],"fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"UICollectionViewDropCoordinator","kind":"identifier"}],"kind":"symbol","url":"/documentation/uikit/uicollectionviewdropcoordinator","title":"UICollectionViewDropCoordinator","identifier":"doc://com.apple.uikit/documentation/UIKit/UICollectionViewDropCoordinator","type":"topic","role":"symbol","abstract":[{"type":"text","text":"An interface for coordinating your custom drop-related actions with the collection view."}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"/identifier/interfaceLanguage","op":"replace","value":"occ"},{"path":"/metadata/platforms","op":"replace","value":[{"introducedAt":"11.0","deprecated":false,"unavailable":false,"beta":false,"name":"iOS"},{"introducedAt":"11.0","deprecated":false,"unavailable":false,"beta":false,"name":"iPadOS"},{"introducedAt":"13.1","deprecated":false,"unavailable":false,"beta":false,"name":"Mac Catalyst"},{"introducedAt":"1.0","deprecated":false,"unavailable":false,"beta":false,"name":"visionOS"}]},{"path":"/metadata/roleHeading","op":"replace","value":"Instance Property"},{"path":"/metadata/title","op":"replace","value":"session"},{"path":"/metadata/symbolKind","op":"replace","value":"property"},{"op":"replace","path":"/metadata/fragments","value":[{"kind":"identifier","text":"session"}]},{"op":"replace","path":"/hierarchy","value":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.uikit/documentation/UIKit","doc://com.apple.uikit/documentation/UIKit/UICollectionViewDropCoordinator"]]}},{"op":"add","path":"/topicSections","value":null},{"op":"add","path":"/relationshipsSections","value":null},{"op":"replace","path":"/seeAlsoSections","value":[{"title":"Getting the Session Information","generated":true,"identifiers":["doc://com.apple.uikit/documentation/UIKit/UICollectionViewDropCoordinator/proposal"],"anchor":"Getting-the-Session-Information"}]},{"path":"/primaryContentSections/0","op":"replace","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"preciseIdentifier":"c:Qoobjc(pl)UIDropSession","kind":"typeIdentifier","text":"id<UIDropSession>"},{"kind":"text","text":" "},{"kind":"identifier","text":"session"},{"kind":"text","text":";"}],"platforms":["iOS","iPadOS","Mac Catalyst","tvOS","visionOS"],"languages":["occ"]}]}},{"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UICollectionViewDropCoordinator~1session/title","value":"session"},{"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UICollectionViewDropCoordinator~1session/fragments","value":[{"kind":"identifier","text":"session"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UICollectionViewDropCoordinator~1proposal/title","value":"proposal"},{"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UICollectionViewDropCoordinator~1proposal/fragments","value":[{"kind":"identifier","text":"proposal"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIDropSession/title","value":"UIDropSession"},{"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIDropSession/fragments","value":[{"kind":"identifier","text":"UIDropSession"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIDropSession/navigatorTitle","value":[{"kind":"identifier","text":"UIDropSession"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UICollectionViewDropCoordinator/title","value":"UICollectionViewDropCoordinator"},{"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UICollectionViewDropCoordinator/fragments","value":[{"text":"UICollectionViewDropCoordinator","kind":"identifier"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UICollectionViewDropCoordinator/navigatorTitle","value":[{"text":"UICollectionViewDropCoordinator","kind":"identifier"}]}]}],"legalNotices":{"copyright":"Copyright &copy; 2025 Apple Inc. All rights reserved.","termsOfUse":"https://www.apple.com/legal/internet-services/terms/site.html","privacyPolicy":"https://www.apple.com/privacy/privacy-policy"}}