{
  "abstract": [
    {
      "text": "The ",
      "type": "text"
    },
    {
      "code": "c5",
      "type": "codeVoice"
    },
    {
      "text": " in the transfer function.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.accelerate/documentation/Accelerate",
        "doc://com.apple.accelerate/documentation/Accelerate/vImageTransferFunction"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.accelerate/documentation/Accelerate/vImageTransferFunction/c5"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@S@vImageTransferFunction@FI@c5",
    "fragments": [
      {
        "kind": "keyword",
        "text": "var"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "c5"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "s:14CoreFoundation7CGFloatV",
        "text": "CGFloat"
      }
    ],
    "modules": [
      {
        "name": "Accelerate"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "c5"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Instance Property",
    "symbolKind": "property",
    "title": "c5"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "var"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "c5"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:14CoreFoundation7CGFloatV",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:14CoreFoundation7CGFloatV",
              "text": "CGFloat"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.accelerate/documentation/Accelerate": {
      "abstract": [
        {
          "text": "Make large-scale mathematical computations and image calculations, optimized for high performance and low energy consumption.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate",
      "kind": "symbol",
      "role": "collection",
      "title": "Accelerate",
      "type": "topic",
      "url": "/documentation/accelerate"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/vImageTransferFunction": {
      "abstract": [
        {
          "text": "A transfer function to convert from linear to nonlinear RGB.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "vImageTransferFunction"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/vImageTransferFunction",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "vImageTransferFunction"
        }
      ],
      "role": "symbol",
      "title": "vImageTransferFunction",
      "type": "topic",
      "url": "/documentation/accelerate/vimagetransferfunction"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/vImageTransferFunction/c0": {
      "abstract": [
        {
          "text": "The ",
          "type": "text"
        },
        {
          "code": "c0",
          "type": "codeVoice"
        },
        {
          "text": " in the transfer function.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "c0"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:14CoreFoundation7CGFloatV",
          "text": "CGFloat"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/vImageTransferFunction/c0",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "c0"
        }
      ],
      "role": "symbol",
      "title": "c0",
      "type": "topic",
      "url": "/documentation/accelerate/vimagetransferfunction/c0"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/vImageTransferFunction/c1": {
      "abstract": [
        {
          "text": "The ",
          "type": "text"
        },
        {
          "code": "c1",
          "type": "codeVoice"
        },
        {
          "text": " in the transfer function.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "c1"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:14CoreFoundation7CGFloatV",
          "text": "CGFloat"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/vImageTransferFunction/c1",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "c1"
        }
      ],
      "role": "symbol",
      "title": "c1",
      "type": "topic",
      "url": "/documentation/accelerate/vimagetransferfunction/c1"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/vImageTransferFunction/c2": {
      "abstract": [
        {
          "text": "The ",
          "type": "text"
        },
        {
          "code": "c2",
          "type": "codeVoice"
        },
        {
          "text": " in the transfer function.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "c2"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:14CoreFoundation7CGFloatV",
          "text": "CGFloat"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/vImageTransferFunction/c2",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "c2"
        }
      ],
      "role": "symbol",
      "title": "c2",
      "type": "topic",
      "url": "/documentation/accelerate/vimagetransferfunction/c2"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/vImageTransferFunction/c3": {
      "abstract": [
        {
          "text": "The ",
          "type": "text"
        },
        {
          "code": "c3",
          "type": "codeVoice"
        },
        {
          "text": " in the transfer function.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "c3"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:14CoreFoundation7CGFloatV",
          "text": "CGFloat"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/vImageTransferFunction/c3",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "c3"
        }
      ],
      "role": "symbol",
      "title": "c3",
      "type": "topic",
      "url": "/documentation/accelerate/vimagetransferfunction/c3"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/vImageTransferFunction/c4": {
      "abstract": [
        {
          "text": "The ",
          "type": "text"
        },
        {
          "code": "c4",
          "type": "codeVoice"
        },
        {
          "text": " in the transfer function.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "c4"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:14CoreFoundation7CGFloatV",
          "text": "CGFloat"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/vImageTransferFunction/c4",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "c4"
        }
      ],
      "role": "symbol",
      "title": "c4",
      "type": "topic",
      "url": "/documentation/accelerate/vimagetransferfunction/c4"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/vImageTransferFunction/c5": {
      "abstract": [
        {
          "text": "The ",
          "type": "text"
        },
        {
          "code": "c5",
          "type": "codeVoice"
        },
        {
          "text": " in the transfer function.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "c5"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:14CoreFoundation7CGFloatV",
          "text": "CGFloat"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/vImageTransferFunction/c5",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "c5"
        }
      ],
      "role": "symbol",
      "title": "c5",
      "type": "topic",
      "url": "/documentation/accelerate/vimagetransferfunction/c5"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/vImageTransferFunction/cutoff": {
      "abstract": [
        {
          "text": "The ",
          "type": "text"
        },
        {
          "code": "cutoff",
          "type": "codeVoice"
        },
        {
          "text": " in the transfer function.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "cutoff"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:14CoreFoundation7CGFloatV",
          "text": "CGFloat"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/vImageTransferFunction/cutoff",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "cutoff"
        }
      ],
      "role": "symbol",
      "title": "cutoff",
      "type": "topic",
      "url": "/documentation/accelerate/vimagetransferfunction/cutoff"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/vImageTransferFunction/gamma": {
      "abstract": [
        {
          "text": "The ",
          "type": "text"
        },
        {
          "code": "gamma",
          "type": "codeVoice"
        },
        {
          "text": " in the transfer function.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "gamma"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:14CoreFoundation7CGFloatV",
          "text": "CGFloat"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/vImageTransferFunction/gamma",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "gamma"
        }
      ],
      "role": "symbol",
      "title": "gamma",
      "type": "topic",
      "url": "/documentation/accelerate/vimagetransferfunction/gamma"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.externally.resolved.symbol/s:14CoreFoundation7CGFloatV": {
      "abstract": [
        {
          "text": "The basic type for floating-point scalar values in Core Graphics and related frameworks.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "struct "
        },
        {
          "kind": "identifier",
          "text": "CGFloat"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:14CoreFoundation7CGFloatV",
      "kind": "symbol",
      "role": "symbol",
      "title": "CGFloat",
      "type": "topic",
      "url": "/documentation/corefoundation/cgfloat"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Transfer-function-properties",
      "generated": true,
      "identifiers": [
        "doc://com.apple.accelerate/documentation/Accelerate/vImageTransferFunction/c0",
        "doc://com.apple.accelerate/documentation/Accelerate/vImageTransferFunction/c1",
        "doc://com.apple.accelerate/documentation/Accelerate/vImageTransferFunction/c2",
        "doc://com.apple.accelerate/documentation/Accelerate/vImageTransferFunction/c3",
        "doc://com.apple.accelerate/documentation/Accelerate/vImageTransferFunction/cutoff",
        "doc://com.apple.accelerate/documentation/Accelerate/vImageTransferFunction/gamma",
        "doc://com.apple.accelerate/documentation/Accelerate/vImageTransferFunction/c4"
      ],
      "title": "Transfer function properties"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "visionOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Instance Property"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "c5"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "property"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "c5"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.accelerate/documentation/Accelerate",
                "doc://com.apple.accelerate/documentation/Accelerate/vImageTransferFunction"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Transfer-function-properties",
              "generated": true,
              "identifiers": [
                "doc://com.apple.accelerate/documentation/Accelerate/vImageTransferFunction/c0",
                "doc://com.apple.accelerate/documentation/Accelerate/vImageTransferFunction/c1",
                "doc://com.apple.accelerate/documentation/Accelerate/vImageTransferFunction/c2",
                "doc://com.apple.accelerate/documentation/Accelerate/vImageTransferFunction/c3",
                "doc://com.apple.accelerate/documentation/Accelerate/vImageTransferFunction/cutoff",
                "doc://com.apple.accelerate/documentation/Accelerate/vImageTransferFunction/gamma",
                "doc://com.apple.accelerate/documentation/Accelerate/vImageTransferFunction/c4"
              ],
              "title": "Transfer function properties"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@CGFloat",
                    "text": "CGFloat"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "c5"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1vImageTransferFunction~1c5/title",
          "value": "c5"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1vImageTransferFunction~1c5/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "c5"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1vImageTransferFunction~1c4/title",
          "value": "c4"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1vImageTransferFunction~1c4/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "c4"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1vImageTransferFunction~1cutoff/title",
          "value": "cutoff"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1vImageTransferFunction~1cutoff/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "cutoff"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1vImageTransferFunction~1gamma/title",
          "value": "gamma"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1vImageTransferFunction~1gamma/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "gamma"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1vImageTransferFunction~1c0/title",
          "value": "c0"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1vImageTransferFunction~1c0/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "c0"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1vImageTransferFunction~1c3/title",
          "value": "c3"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1vImageTransferFunction~1c3/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "c3"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1vImageTransferFunction~1c1/title",
          "value": "c1"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1vImageTransferFunction~1c1/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "c1"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1vImageTransferFunction/title",
          "value": "vImageTransferFunction"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1vImageTransferFunction/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "vImageTransferFunction"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1vImageTransferFunction/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "vImageTransferFunction"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1vImageTransferFunction~1c2/title",
          "value": "c2"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1vImageTransferFunction~1c2/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "c2"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/accelerate/vimagetransferfunction/c5"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/accelerate/vimagetransferfunction/c5"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
