{
  "abstract": [
    {
      "text": "The LZ4 compression algorithm for fast compression.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.compression/documentation/Compression"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.compression/documentation/Compression/COMPRESSION_LZ4"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@EA@compression_algorithm@COMPRESSION_LZ4",
    "fragments": [
      {
        "kind": "keyword",
        "text": "var"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "COMPRESSION_LZ4"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@EA@compression_algorithm",
        "text": "compression_algorithm"
      }
    ],
    "modules": [
      {
        "name": "Compression"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "COMPRESSION_LZ4"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Global Variable",
    "symbolKind": "var",
    "title": "COMPRESSION_LZ4"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "var"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "COMPRESSION_LZ4"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.compression/documentation/Compression/compression_algorithm",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@EA@compression_algorithm",
              "text": "compression_algorithm"
            },
            {
              "kind": "text",
              "text": " { "
            },
            {
              "kind": "keyword",
              "text": "get"
            },
            {
              "kind": "text",
              "text": " }"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "LZ4 is a high-performance compressor. The encoded format that the Compression library produces and consumes is compatible with the open source version, apart from the addition of a very simple frame to the raw stream to enable additional validation and functionality.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "An LZ4-encoded buffer is a sequence of blocks, each beginning with a header. Use the following header descriptions when wrapping another LZ4 encoder (or decoder) to enable it to produce or consume the same data stream:",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "items": [
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "A compressed block header consists of the octets ",
                      "type": "text"
                    },
                    {
                      "code": "0x62",
                      "type": "codeVoice"
                    },
                    {
                      "text": ", ",
                      "type": "text"
                    },
                    {
                      "code": "0x76",
                      "type": "codeVoice"
                    },
                    {
                      "text": ", ",
                      "type": "text"
                    },
                    {
                      "code": "0x34",
                      "type": "codeVoice"
                    },
                    {
                      "text": ", and ",
                      "type": "text"
                    },
                    {
                      "code": "0x31",
                      "type": "codeVoice"
                    },
                    {
                      "text": ". Following that is the size (in bytes) of the decoded (plaintext) data the block represents, and the size (in bytes) of the encoded data stored in the block. The header stores both sizes as (potentially unaligned) 32-bit little-endian values. The actual LZ4-encoded data stream immediately follows the compressed block header.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "An uncompressed block header consists of the octets ",
                      "type": "text"
                    },
                    {
                      "code": "0x62",
                      "type": "codeVoice"
                    },
                    {
                      "text": ", ",
                      "type": "text"
                    },
                    {
                      "code": "0x76",
                      "type": "codeVoice"
                    },
                    {
                      "text": ", ",
                      "type": "text"
                    },
                    {
                      "code": "0x34",
                      "type": "codeVoice"
                    },
                    {
                      "text": ", and ",
                      "type": "text"
                    },
                    {
                      "code": "0x2d",
                      "type": "codeVoice"
                    },
                    {
                      "text": ". Following that is a single 32-bit little-endian value representing the plaintext data’s size (in bytes), and then the plaintext data itself.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "An end of stream block header consists of the octets ",
                      "type": "text"
                    },
                    {
                      "code": "0x62",
                      "type": "codeVoice"
                    },
                    {
                      "text": ", ",
                      "type": "text"
                    },
                    {
                      "code": "0x76",
                      "type": "codeVoice"
                    },
                    {
                      "text": ", ",
                      "type": "text"
                    },
                    {
                      "code": "0x34",
                      "type": "codeVoice"
                    },
                    {
                      "text": ", and ",
                      "type": "text"
                    },
                    {
                      "code": "0x24",
                      "type": "codeVoice"
                    },
                    {
                      "text": " and identifies the end of the LZ4 frame.  Don’t attempt to read or write data beyond this header.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            }
          ],
          "type": "unorderedList"
        },
        {
          "inlineContent": [
            {
              "text": "If you’re implementing a wrapper for a raw LZ4 decoder, keep in mind that a compressed block may refer to data from the previous block, so the (decoded) previous block must be available to the decoder.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.compression/documentation/Compression": {
      "abstract": [
        {
          "text": "Leverage common compression algorithms for lossless data compression.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.compression/documentation/Compression",
      "kind": "symbol",
      "role": "collection",
      "title": "Compression",
      "type": "topic",
      "url": "/documentation/compression"
    },
    "doc://com.apple.compression/documentation/Compression/COMPRESSION_BROTLI": {
      "abstract": [
        {
          "text": "The Brotli compression algorithm, which is recommended for text compression.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "COMPRESSION_BROTLI"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@EA@compression_algorithm",
          "text": "compression_algorithm"
        }
      ],
      "identifier": "doc://com.apple.compression/documentation/Compression/COMPRESSION_BROTLI",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "COMPRESSION_BROTLI"
        }
      ],
      "role": "symbol",
      "title": "COMPRESSION_BROTLI",
      "type": "topic",
      "url": "/documentation/compression/compression_brotli"
    },
    "doc://com.apple.compression/documentation/Compression/COMPRESSION_LZ4": {
      "abstract": [
        {
          "text": "The LZ4 compression algorithm for fast compression.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "COMPRESSION_LZ4"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@EA@compression_algorithm",
          "text": "compression_algorithm"
        }
      ],
      "identifier": "doc://com.apple.compression/documentation/Compression/COMPRESSION_LZ4",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "COMPRESSION_LZ4"
        }
      ],
      "role": "symbol",
      "title": "COMPRESSION_LZ4",
      "type": "topic",
      "url": "/documentation/compression/compression_lz4"
    },
    "doc://com.apple.compression/documentation/Compression/COMPRESSION_LZ4_RAW": {
      "abstract": [
        {
          "text": "The LZ4 compression algorithm, without frame headers.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "COMPRESSION_LZ4_RAW"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@EA@compression_algorithm",
          "text": "compression_algorithm"
        }
      ],
      "identifier": "doc://com.apple.compression/documentation/Compression/COMPRESSION_LZ4_RAW",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "COMPRESSION_LZ4_RAW"
        }
      ],
      "role": "symbol",
      "title": "COMPRESSION_LZ4_RAW",
      "type": "topic",
      "url": "/documentation/compression/compression_lz4_raw"
    },
    "doc://com.apple.compression/documentation/Compression/COMPRESSION_LZBITMAP": {
      "abstract": [
        {
          "text": "The LZBITMAP compression algorithm, which is designed to exploit the vector instruction set of current CPUs.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "COMPRESSION_LZBITMAP"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@EA@compression_algorithm",
          "text": "compression_algorithm"
        }
      ],
      "identifier": "doc://com.apple.compression/documentation/Compression/COMPRESSION_LZBITMAP",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "COMPRESSION_LZBITMAP"
        }
      ],
      "role": "symbol",
      "title": "COMPRESSION_LZBITMAP",
      "type": "topic",
      "url": "/documentation/compression/compression_lzbitmap"
    },
    "doc://com.apple.compression/documentation/Compression/COMPRESSION_LZFSE": {
      "abstract": [
        {
          "text": "The LZFSE compression algorithm, which is recommended for use on Apple platforms.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "COMPRESSION_LZFSE"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@EA@compression_algorithm",
          "text": "compression_algorithm"
        }
      ],
      "identifier": "doc://com.apple.compression/documentation/Compression/COMPRESSION_LZFSE",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "COMPRESSION_LZFSE"
        }
      ],
      "role": "symbol",
      "title": "COMPRESSION_LZFSE",
      "type": "topic",
      "url": "/documentation/compression/compression_lzfse"
    },
    "doc://com.apple.compression/documentation/Compression/COMPRESSION_LZMA": {
      "abstract": [
        {
          "text": "The LZMA compression algorithm, which is recommended for high-compression ratio.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "COMPRESSION_LZMA"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@EA@compression_algorithm",
          "text": "compression_algorithm"
        }
      ],
      "identifier": "doc://com.apple.compression/documentation/Compression/COMPRESSION_LZMA",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "COMPRESSION_LZMA"
        }
      ],
      "role": "symbol",
      "title": "COMPRESSION_LZMA",
      "type": "topic",
      "url": "/documentation/compression/compression_lzma"
    },
    "doc://com.apple.compression/documentation/Compression/COMPRESSION_ZLIB": {
      "abstract": [
        {
          "text": "The zlib compression algorithm, which is recommended for cross-platform compression.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "COMPRESSION_ZLIB"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@EA@compression_algorithm",
          "text": "compression_algorithm"
        }
      ],
      "identifier": "doc://com.apple.compression/documentation/Compression/COMPRESSION_ZLIB",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "COMPRESSION_ZLIB"
        }
      ],
      "role": "symbol",
      "title": "COMPRESSION_ZLIB",
      "type": "topic",
      "url": "/documentation/compression/compression_zlib"
    },
    "doc://com.apple.compression/documentation/Compression/compression_algorithm": {
      "abstract": [
        {
          "text": "A structure for values that represent compression algorithms.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "compression_algorithm"
        }
      ],
      "identifier": "doc://com.apple.compression/documentation/Compression/compression_algorithm",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "compression_algorithm"
        }
      ],
      "role": "symbol",
      "title": "compression_algorithm",
      "type": "topic",
      "url": "/documentation/compression/compression_algorithm"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Algorithm-Constants",
      "generated": true,
      "identifiers": [
        "doc://com.apple.compression/documentation/Compression/COMPRESSION_LZFSE",
        "doc://com.apple.compression/documentation/Compression/COMPRESSION_LZ4_RAW",
        "doc://com.apple.compression/documentation/Compression/COMPRESSION_LZMA",
        "doc://com.apple.compression/documentation/Compression/COMPRESSION_ZLIB",
        "doc://com.apple.compression/documentation/Compression/COMPRESSION_BROTLI",
        "doc://com.apple.compression/documentation/Compression/COMPRESSION_LZBITMAP"
      ],
      "title": "Algorithm Constants"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "visionOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration Case"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "COMPRESSION_LZ4"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "case"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "COMPRESSION_LZ4"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.compression/documentation/Compression",
                "doc://com.apple.compression/documentation/Compression/compression_algorithm"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Algorithm-Constants",
              "generated": true,
              "identifiers": [
                "doc://com.apple.compression/documentation/Compression/COMPRESSION_LZFSE",
                "doc://com.apple.compression/documentation/Compression/COMPRESSION_LZ4_RAW",
                "doc://com.apple.compression/documentation/Compression/COMPRESSION_LZMA",
                "doc://com.apple.compression/documentation/Compression/COMPRESSION_ZLIB",
                "doc://com.apple.compression/documentation/Compression/COMPRESSION_BROTLI",
                "doc://com.apple.compression/documentation/Compression/COMPRESSION_LZBITMAP"
              ],
              "title": "Algorithm Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "identifier",
                    "text": "COMPRESSION_LZ4"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.compression~1documentation~1Compression~1COMPRESSION_LZBITMAP/title",
          "value": "COMPRESSION_LZBITMAP"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.compression~1documentation~1Compression~1COMPRESSION_LZBITMAP/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "COMPRESSION_LZBITMAP"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.compression~1documentation~1Compression~1COMPRESSION_LZ4/title",
          "value": "COMPRESSION_LZ4"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.compression~1documentation~1Compression~1COMPRESSION_LZ4/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "COMPRESSION_LZ4"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.compression~1documentation~1Compression~1compression_algorithm/title",
          "value": "compression_algorithm"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.compression~1documentation~1Compression~1compression_algorithm/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "compression_algorithm"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.compression~1documentation~1Compression~1compression_algorithm/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "compression_algorithm"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.compression~1documentation~1Compression~1COMPRESSION_LZ4_RAW/title",
          "value": "COMPRESSION_LZ4_RAW"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.compression~1documentation~1Compression~1COMPRESSION_LZ4_RAW/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "COMPRESSION_LZ4_RAW"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.compression~1documentation~1Compression~1COMPRESSION_ZLIB/title",
          "value": "COMPRESSION_ZLIB"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.compression~1documentation~1Compression~1COMPRESSION_ZLIB/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "COMPRESSION_ZLIB"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.compression~1documentation~1Compression~1COMPRESSION_LZFSE/title",
          "value": "COMPRESSION_LZFSE"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.compression~1documentation~1Compression~1COMPRESSION_LZFSE/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "COMPRESSION_LZFSE"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.compression~1documentation~1Compression~1COMPRESSION_LZMA/title",
          "value": "COMPRESSION_LZMA"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.compression~1documentation~1Compression~1COMPRESSION_LZMA/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "COMPRESSION_LZMA"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.compression~1documentation~1Compression~1COMPRESSION_BROTLI/title",
          "value": "COMPRESSION_BROTLI"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.compression~1documentation~1Compression~1COMPRESSION_BROTLI/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "COMPRESSION_BROTLI"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/compression/compression_lz4"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/compression/compression_lz4"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
