{"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["/documentation/compression/compression_status_ok"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["/documentation/compression/compression_status_ok"]}],"abstract":[{"text":"Indicates the stream has consumed all data in the source buffer, or used all space in the destination buffer.","type":"text"}],"seeAlsoSections":[{"generated":true,"title":"Status Constants","identifiers":["doc://com.apple.compression/documentation/Compression/COMPRESSION_STATUS_END","doc://com.apple.compression/documentation/Compression/COMPRESSION_STATUS_ERROR"],"anchor":"Status-Constants"}],"sections":[],"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"COMPRESSION_STATUS_OK"},{"kind":"text","text":": "},{"identifier":"doc://com.apple.compression/documentation/Compression/compression_status","preciseIdentifier":"c:@EA@compression_status","kind":"typeIdentifier","text":"compression_status"},{"kind":"text","text":" { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" }"}],"languages":["swift"],"platforms":["iOS","iPadOS","Mac Catalyst","macOS","tvOS","visionOS","watchOS"]}],"kind":"declarations"}],"kind":"symbol","hierarchy":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.compression/documentation/Compression"]]},"identifier":{"url":"doc://com.apple.compression/documentation/Compression/COMPRESSION_STATUS_OK","interfaceLanguage":"swift"},"schemaVersion":{"major":0,"minor":3,"patch":0},"metadata":{"role":"symbol","externalID":"c:@EA@compression_status@COMPRESSION_STATUS_OK","navigatorTitle":[{"kind":"identifier","text":"COMPRESSION_STATUS_OK"}],"modules":[{"name":"Compression"}],"title":"COMPRESSION_STATUS_OK","platforms":[{"beta":false,"deprecated":false,"unavailable":false,"name":"iOS"},{"beta":false,"deprecated":false,"unavailable":false,"name":"iPadOS"},{"beta":false,"deprecated":false,"unavailable":false,"name":"Mac Catalyst"},{"beta":false,"deprecated":false,"unavailable":false,"name":"macOS"},{"beta":false,"deprecated":false,"unavailable":false,"name":"tvOS"},{"beta":false,"deprecated":false,"unavailable":false,"name":"visionOS"},{"name":"watchOS","deprecated":false,"beta":false,"unavailable":false}],"roleHeading":"Global Variable","symbolKind":"var","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"COMPRESSION_STATUS_OK"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@EA@compression_status","text":"compression_status"}]},"references":{"doc://com.apple.documentation/documentation/technologies":{"identifier":"doc://com.apple.documentation/documentation/technologies","kind":"technologies","abstract":[{"type":"text","text":""}],"title":"Technologies","url":"/documentation/technologies","type":"topic","role":"overview"},"doc://com.apple.compression/documentation/Compression/compression_status":{"url":"/documentation/compression/compression_status","navigatorTitle":[{"text":"compression_status","kind":"identifier"}],"fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"compression_status","kind":"identifier"}],"kind":"symbol","title":"compression_status","role":"symbol","type":"topic","identifier":"doc://com.apple.compression/documentation/Compression/compression_status","abstract":[{"type":"text","text":"A set of values used to represent the status of stream compression."}]},"doc://com.apple.compression/documentation/Compression":{"identifier":"doc://com.apple.compression/documentation/Compression","kind":"symbol","abstract":[{"text":"Leverage common compression algorithms for lossless data compression.","type":"text"}],"title":"Compression","url":"/documentation/compression","type":"topic","role":"collection"},"doc://com.apple.compression/documentation/Compression/COMPRESSION_STATUS_END":{"url":"/documentation/compression/compression_status_end","type":"topic","identifier":"doc://com.apple.compression/documentation/Compression/COMPRESSION_STATUS_END","title":"COMPRESSION_STATUS_END","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"COMPRESSION_STATUS_END"}],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"COMPRESSION_STATUS_END"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@EA@compression_status","kind":"typeIdentifier","text":"compression_status"}],"abstract":[{"text":"Indicates the stream has read all input from the source, and written all output to the destination.","type":"text"}],"kind":"symbol"},"doc://com.apple.compression/documentation/Compression/COMPRESSION_STATUS_ERROR":{"identifier":"doc://com.apple.compression/documentation/Compression/COMPRESSION_STATUS_ERROR","kind":"symbol","abstract":[{"type":"text","text":"Indicates an error with stream compression."}],"title":"COMPRESSION_STATUS_ERROR","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"COMPRESSION_STATUS_ERROR","kind":"identifier"},{"text":": ","kind":"text"},{"text":"compression_status","preciseIdentifier":"c:@EA@compression_status","kind":"typeIdentifier"}],"url":"/documentation/compression/compression_status_error","type":"topic","navigatorTitle":[{"text":"COMPRESSION_STATUS_ERROR","kind":"identifier"}],"role":"symbol"},"doc://com.apple.compression/documentation/Compression/COMPRESSION_STATUS_OK":{"url":"/documentation/compression/compression_status_ok","navigatorTitle":[{"text":"COMPRESSION_STATUS_OK","kind":"identifier"}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"COMPRESSION_STATUS_OK","kind":"identifier"},{"text":": ","kind":"text"},{"text":"compression_status","preciseIdentifier":"c:@EA@compression_status","kind":"typeIdentifier"}],"kind":"symbol","title":"COMPRESSION_STATUS_OK","role":"symbol","type":"topic","identifier":"doc://com.apple.compression/documentation/Compression/COMPRESSION_STATUS_OK","abstract":[{"type":"text","text":"Indicates the stream has consumed all data in the source buffer, or used all space in the destination buffer."}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"/identifier/interfaceLanguage","value":"occ"},{"op":"replace","path":"/metadata/platforms","value":[{"name":"iOS","unavailable":false,"deprecated":false,"beta":false},{"name":"iPadOS","unavailable":false,"deprecated":false,"beta":false},{"name":"Mac Catalyst","unavailable":false,"deprecated":false,"beta":false},{"name":"macOS","unavailable":false,"deprecated":false,"beta":false},{"name":"tvOS","unavailable":false,"deprecated":false,"beta":false},{"name":"visionOS","deprecated":false,"beta":false,"unavailable":false},{"name":"watchOS","deprecated":false,"beta":false,"unavailable":false}]},{"op":"replace","path":"/metadata/roleHeading","value":"Enumeration Case"},{"op":"replace","path":"/metadata/title","value":"COMPRESSION_STATUS_OK"},{"op":"replace","path":"/metadata/symbolKind","value":"case"},{"op":"replace","path":"/metadata/fragments","value":[{"text":"COMPRESSION_STATUS_OK","kind":"identifier"}]},{"op":"replace","path":"/hierarchy","value":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.compression/documentation/Compression","doc://com.apple.compression/documentation/Compression/compression_status"]]}},{"op":"add","path":"/topicSections","value":null},{"op":"add","path":"/relationshipsSections","value":null},{"op":"replace","path":"/seeAlsoSections","value":[{"identifiers":["doc://com.apple.compression/documentation/Compression/COMPRESSION_STATUS_END","doc://com.apple.compression/documentation/Compression/COMPRESSION_STATUS_ERROR"],"anchor":"Status-Constants","generated":true,"title":"Status Constants"}]},{"op":"replace","path":"/primaryContentSections/0","value":{"declarations":[{"tokens":[{"kind":"identifier","text":"COMPRESSION_STATUS_OK"}],"languages":["occ"],"platforms":["iOS","iPadOS","Mac Catalyst","macOS","tvOS","visionOS","watchOS"]}],"kind":"declarations"}},{"op":"replace","path":"/references/doc:~1~1com.apple.compression~1documentation~1Compression~1compression_status/title","value":"compression_status"},{"op":"replace","path":"/references/doc:~1~1com.apple.compression~1documentation~1Compression~1compression_status/fragments","value":[{"text":"compression_status","kind":"identifier"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.compression~1documentation~1Compression~1compression_status/navigatorTitle","value":[{"text":"compression_status","kind":"identifier"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.compression~1documentation~1Compression~1COMPRESSION_STATUS_END/title","value":"COMPRESSION_STATUS_END"},{"op":"replace","path":"/references/doc:~1~1com.apple.compression~1documentation~1Compression~1COMPRESSION_STATUS_END/fragments","value":[{"kind":"identifier","text":"COMPRESSION_STATUS_END"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.compression~1documentation~1Compression~1COMPRESSION_STATUS_ERROR/title","value":"COMPRESSION_STATUS_ERROR"},{"op":"replace","path":"/references/doc:~1~1com.apple.compression~1documentation~1Compression~1COMPRESSION_STATUS_ERROR/fragments","value":[{"kind":"identifier","text":"COMPRESSION_STATUS_ERROR"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.compression~1documentation~1Compression~1COMPRESSION_STATUS_OK/title","value":"COMPRESSION_STATUS_OK"},{"op":"replace","path":"/references/doc:~1~1com.apple.compression~1documentation~1Compression~1COMPRESSION_STATUS_OK/fragments","value":[{"kind":"identifier","text":"COMPRESSION_STATUS_OK"}]}]}],"legalNotices":{"copyright":"Copyright &copy; 2025 Apple Inc. All rights reserved.","termsOfUse":"https://www.apple.com/legal/internet-services/terms/site.html","privacyPolicy":"https://www.apple.com/privacy/privacy-policy"}}