{
  "abstract": [
    {
      "text": "Frees any memory allocated by stream initialization function.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.compression/documentation/Compression"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.compression/documentation/Compression/compression_stream_destroy(_:)"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@F@compression_stream_destroy",
    "fragments": [
      {
        "kind": "keyword",
        "text": "func"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "compression_stream_destroy"
      },
      {
        "kind": "text",
        "text": "("
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "s:Sp",
        "text": "UnsafeMutablePointer"
      },
      {
        "kind": "text",
        "text": "<"
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@SA@compression_stream",
        "text": "compression_stream"
      },
      {
        "kind": "text",
        "text": ">) -> "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@EA@compression_status",
        "text": "compression_status"
      }
    ],
    "modules": [
      {
        "name": "Compression"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "compression_stream_destroy"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "9.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "9.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.1",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.11",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "9.0",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "2.0",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Function",
    "symbolKind": "func",
    "title": "compression_stream_destroy(_:)"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "func"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "compression_stream_destroy"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "kind": "externalParam",
              "text": "_"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "stream"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:Sp",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:Sp",
              "text": "UnsafeMutablePointer"
            },
            {
              "kind": "text",
              "text": "<"
            },
            {
              "identifier": "doc://com.apple.compression/documentation/Compression/compression_stream",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@SA@compression_stream",
              "text": "compression_stream"
            },
            {
              "kind": "text",
              "text": ">) -> "
            },
            {
              "identifier": "doc://com.apple.compression/documentation/Compression/compression_status",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@EA@compression_status",
              "text": "compression_status"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "kind": "parameters",
      "parameters": [
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "A pointer to an allocated and initialized ",
                  "type": "text"
                },
                {
                  "identifier": "doc://com.apple.compression/documentation/Compression/compression_stream",
                  "isActive": true,
                  "type": "reference"
                },
                {
                  "text": " structure.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "stream"
        }
      ]
    },
    {
      "content": [
        {
          "anchor": "Return-Value",
          "level": 3,
          "text": "Return Value",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "A value of type ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.compression/documentation/Compression/compression_status",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ", interpreted as follows:",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "items": [
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "identifier": "doc://com.apple.compression/documentation/Compression/COMPRESSION_STATUS_OK",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": " means that the function successfully destroyed the stream.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "identifier": "doc://com.apple.compression/documentation/Compression/COMPRESSION_STATUS_ERROR",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": " means an error occurred.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            }
          ],
          "type": "unorderedList"
        },
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Note that ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.compression/documentation/Compression/compression_stream_destroy(_:)",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " doesn’t free the stream object or the buffers allocated by the caller.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.compression/documentation/Compression": {
      "abstract": [
        {
          "text": "Leverage common compression algorithms for lossless data compression.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.compression/documentation/Compression",
      "kind": "symbol",
      "role": "collection",
      "title": "Compression",
      "type": "topic",
      "url": "/documentation/compression"
    },
    "doc://com.apple.compression/documentation/Compression/COMPRESSION_STATUS_ERROR": {
      "abstract": [
        {
          "text": "Indicates an error with stream compression.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "COMPRESSION_STATUS_ERROR"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@EA@compression_status",
          "text": "compression_status"
        }
      ],
      "identifier": "doc://com.apple.compression/documentation/Compression/COMPRESSION_STATUS_ERROR",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "COMPRESSION_STATUS_ERROR"
        }
      ],
      "role": "symbol",
      "title": "COMPRESSION_STATUS_ERROR",
      "type": "topic",
      "url": "/documentation/compression/compression_status_error"
    },
    "doc://com.apple.compression/documentation/Compression/COMPRESSION_STATUS_OK": {
      "abstract": [
        {
          "text": "Indicates the stream has consumed all data in the source buffer, or used all space in the destination buffer.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "COMPRESSION_STATUS_OK"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@EA@compression_status",
          "text": "compression_status"
        }
      ],
      "identifier": "doc://com.apple.compression/documentation/Compression/COMPRESSION_STATUS_OK",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "COMPRESSION_STATUS_OK"
        }
      ],
      "role": "symbol",
      "title": "COMPRESSION_STATUS_OK",
      "type": "topic",
      "url": "/documentation/compression/compression_status_ok"
    },
    "doc://com.apple.compression/documentation/Compression/compression_algorithm": {
      "abstract": [
        {
          "text": "A structure for values that represent compression algorithms.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "compression_algorithm"
        }
      ],
      "identifier": "doc://com.apple.compression/documentation/Compression/compression_algorithm",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "compression_algorithm"
        }
      ],
      "role": "symbol",
      "title": "compression_algorithm",
      "type": "topic",
      "url": "/documentation/compression/compression_algorithm"
    },
    "doc://com.apple.compression/documentation/Compression/compression_status": {
      "abstract": [
        {
          "text": "A set of values used to represent the status of stream compression.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "compression_status"
        }
      ],
      "identifier": "doc://com.apple.compression/documentation/Compression/compression_status",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "compression_status"
        }
      ],
      "role": "symbol",
      "title": "compression_status",
      "type": "topic",
      "url": "/documentation/compression/compression_status"
    },
    "doc://com.apple.compression/documentation/Compression/compression_stream": {
      "abstract": [
        {
          "text": "A structure representing a compression stream.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "compression_stream"
        }
      ],
      "identifier": "doc://com.apple.compression/documentation/Compression/compression_stream",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "compression_stream"
        }
      ],
      "role": "symbol",
      "title": "compression_stream",
      "type": "topic",
      "url": "/documentation/compression/compression_stream"
    },
    "doc://com.apple.compression/documentation/Compression/compression_stream_destroy(_:)": {
      "abstract": [
        {
          "text": "Frees any memory allocated by stream initialization function.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "compression_stream_destroy"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sp",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@SA@compression_stream",
          "text": "compression_stream"
        },
        {
          "kind": "text",
          "text": ">) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@EA@compression_status",
          "text": "compression_status"
        }
      ],
      "identifier": "doc://com.apple.compression/documentation/Compression/compression_stream_destroy(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "compression_stream_destroy"
        }
      ],
      "role": "symbol",
      "title": "compression_stream_destroy(_:)",
      "type": "topic",
      "url": "/documentation/compression/compression_stream_destroy(_:)"
    },
    "doc://com.apple.compression/documentation/Compression/compression_stream_flags": {
      "abstract": [
        {
          "text": "A set of values used to represent stream compression flags.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "compression_stream_flags"
        }
      ],
      "identifier": "doc://com.apple.compression/documentation/Compression/compression_stream_flags",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "compression_stream_flags"
        }
      ],
      "role": "symbol",
      "title": "compression_stream_flags",
      "type": "topic",
      "url": "/documentation/compression/compression_stream_flags"
    },
    "doc://com.apple.compression/documentation/Compression/compression_stream_init(_:_:_:)": {
      "abstract": [
        {
          "text": "Initializes a compression stream for either compression or decompression.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "compression_stream_init"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sp",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@SA@compression_stream",
          "text": "compression_stream"
        },
        {
          "kind": "text",
          "text": ">, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@EA@compression_stream_operation",
          "text": "compression_stream_operation"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@EA@compression_algorithm",
          "text": "compression_algorithm"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@EA@compression_status",
          "text": "compression_status"
        }
      ],
      "identifier": "doc://com.apple.compression/documentation/Compression/compression_stream_init(_:_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "compression_stream_init"
        }
      ],
      "role": "symbol",
      "title": "compression_stream_init(_:_:_:)",
      "type": "topic",
      "url": "/documentation/compression/compression_stream_init(_:_:_:)"
    },
    "doc://com.apple.compression/documentation/Compression/compression_stream_operation": {
      "abstract": [
        {
          "text": "A set of values used to represent a stream compression operation.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "compression_stream_operation"
        }
      ],
      "identifier": "doc://com.apple.compression/documentation/Compression/compression_stream_operation",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "compression_stream_operation"
        }
      ],
      "role": "symbol",
      "title": "compression_stream_operation",
      "type": "topic",
      "url": "/documentation/compression/compression_stream_operation"
    },
    "doc://com.apple.compression/documentation/Compression/compression_stream_process(_:_:)": {
      "abstract": [
        {
          "text": "Performs compression or decompression using an initialized compression stream structure.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "compression_stream_process"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sp",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@SA@compression_stream",
          "text": "compression_stream"
        },
        {
          "kind": "text",
          "text": ">, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int32V",
          "text": "Int32"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@EA@compression_status",
          "text": "compression_status"
        }
      ],
      "identifier": "doc://com.apple.compression/documentation/Compression/compression_stream_process(_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "compression_stream_process"
        }
      ],
      "role": "symbol",
      "title": "compression_stream_process(_:_:)",
      "type": "topic",
      "url": "/documentation/compression/compression_stream_process(_:_:)"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.externally.resolved.symbol/s:Sp": {
      "abstract": [
        {
          "text": "A pointer for accessing and manipulating data of a specific type.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@frozen"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "genericParameter",
          "text": "Pointee"
        },
        {
          "kind": "text",
          "text": "> "
        },
        {
          "kind": "keyword",
          "text": "where"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "typeIdentifier",
          "text": "Pointee"
        },
        {
          "kind": "text",
          "text": " : ~Copyable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:Sp",
      "kind": "symbol",
      "role": "symbol",
      "title": "UnsafeMutablePointer",
      "type": "topic",
      "url": "/documentation/Swift/UnsafeMutablePointer"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Multiple-step-compression",
      "generated": true,
      "identifiers": [
        "doc://com.apple.compression/documentation/Compression/compression_stream",
        "doc://com.apple.compression/documentation/Compression/compression_stream_init(_:_:_:)",
        "doc://com.apple.compression/documentation/Compression/compression_stream_process(_:_:)",
        "doc://com.apple.compression/documentation/Compression/compression_status",
        "doc://com.apple.compression/documentation/Compression/compression_stream_flags",
        "doc://com.apple.compression/documentation/Compression/compression_stream_operation",
        "doc://com.apple.compression/documentation/Compression/compression_algorithm"
      ],
      "title": "Multiple-step compression"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "9.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "9.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.1",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.11",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "9.0",
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "2.0",
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Function"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "compression_stream_destroy"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "func"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "compression_stream_destroy"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.compression/documentation/Compression"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Multiple-step-compression",
              "generated": true,
              "identifiers": [
                "doc://com.apple.compression/documentation/Compression/compression_stream",
                "doc://com.apple.compression/documentation/Compression/compression_stream_init(_:_:_:)",
                "doc://com.apple.compression/documentation/Compression/compression_stream_process(_:_:)",
                "doc://com.apple.compression/documentation/Compression/compression_status",
                "doc://com.apple.compression/documentation/Compression/compression_stream_flags",
                "doc://com.apple.compression/documentation/Compression/compression_stream_operation",
                "doc://com.apple.compression/documentation/Compression/compression_algorithm"
              ],
              "title": "Multiple-step compression"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "extern"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "identifier": "doc://com.apple.compression/documentation/Compression/compression_status",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@EA@compression_status",
                    "text": "compression_status"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "compression_stream_destroy"
                  },
                  {
                    "kind": "text",
                    "text": "("
                  },
                  {
                    "identifier": "doc://com.apple.compression/documentation/Compression/compression_stream",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@SA@compression_stream",
                    "text": "compression_stream"
                  },
                  {
                    "kind": "text",
                    "text": " * "
                  },
                  {
                    "kind": "internalParam",
                    "text": "stream"
                  },
                  {
                    "kind": "text",
                    "text": ");"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/1",
          "value": {
            "kind": "parameters",
            "parameters": [
              {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "A pointer to an allocated and initialized ",
                        "type": "text"
                      },
                      {
                        "identifier": "doc://com.apple.compression/documentation/Compression/compression_stream",
                        "isActive": true,
                        "type": "reference"
                      },
                      {
                        "text": " structure.",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ],
                "name": "stream"
              }
            ]
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.compression~1documentation~1Compression~1compression_stream/title",
          "value": "compression_stream"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.compression~1documentation~1Compression~1compression_stream/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "compression_stream"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.compression~1documentation~1Compression~1compression_stream/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "compression_stream"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.compression~1documentation~1Compression~1compression_status/title",
          "value": "compression_status"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.compression~1documentation~1Compression~1compression_status/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "compression_status"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.compression~1documentation~1Compression~1compression_status/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "compression_status"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.compression~1documentation~1Compression~1COMPRESSION_STATUS_OK/title",
          "value": "COMPRESSION_STATUS_OK"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.compression~1documentation~1Compression~1COMPRESSION_STATUS_OK/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "COMPRESSION_STATUS_OK"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.compression~1documentation~1Compression~1compression_stream_init(_:_:_:)/title",
          "value": "compression_stream_init"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.compression~1documentation~1Compression~1compression_stream_init(_:_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "compression_stream_init"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.compression~1documentation~1Compression~1compression_stream_operation/title",
          "value": "compression_stream_operation"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.compression~1documentation~1Compression~1compression_stream_operation/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "compression_stream_operation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.compression~1documentation~1Compression~1compression_stream_operation/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "compression_stream_operation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.compression~1documentation~1Compression~1compression_stream_process(_:_:)/title",
          "value": "compression_stream_process"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.compression~1documentation~1Compression~1compression_stream_process(_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "compression_stream_process"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.compression~1documentation~1Compression~1compression_stream_destroy(_:)/title",
          "value": "compression_stream_destroy"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.compression~1documentation~1Compression~1compression_stream_destroy(_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "compression_stream_destroy"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.compression~1documentation~1Compression~1COMPRESSION_STATUS_ERROR/title",
          "value": "COMPRESSION_STATUS_ERROR"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.compression~1documentation~1Compression~1COMPRESSION_STATUS_ERROR/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "COMPRESSION_STATUS_ERROR"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.compression~1documentation~1Compression~1compression_algorithm/title",
          "value": "compression_algorithm"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.compression~1documentation~1Compression~1compression_algorithm/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "compression_algorithm"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.compression~1documentation~1Compression~1compression_algorithm/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "compression_algorithm"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.compression~1documentation~1Compression~1compression_stream_flags/title",
          "value": "compression_stream_flags"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.compression~1documentation~1Compression~1compression_stream_flags/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "compression_stream_flags"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.compression~1documentation~1Compression~1compression_stream_flags/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "compression_stream_flags"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/compression/compression_stream_destroy(_:)"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/compression/compression_stream_destroy(_:)"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
