{
  "abstract": [
    {
      "text": "A constant indicating a compression operation.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.compression/documentation/Compression"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.compression/documentation/Compression/COMPRESSION_STREAM_ENCODE"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@EA@compression_stream_operation@COMPRESSION_STREAM_ENCODE",
    "fragments": [
      {
        "kind": "keyword",
        "text": "var"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "COMPRESSION_STREAM_ENCODE"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@EA@compression_stream_operation",
        "text": "compression_stream_operation"
      }
    ],
    "modules": [
      {
        "name": "Compression"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "COMPRESSION_STREAM_ENCODE"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Global Variable",
    "symbolKind": "var",
    "title": "COMPRESSION_STREAM_ENCODE"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "var"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "COMPRESSION_STREAM_ENCODE"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.compression/documentation/Compression/compression_stream_operation",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@EA@compression_stream_operation",
              "text": "compression_stream_operation"
            },
            {
              "kind": "text",
              "text": " { "
            },
            {
              "kind": "keyword",
              "text": "get"
            },
            {
              "kind": "text",
              "text": " }"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.compression/documentation/Compression": {
      "abstract": [
        {
          "text": "Leverage common compression algorithms for lossless data compression.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.compression/documentation/Compression",
      "kind": "symbol",
      "role": "collection",
      "title": "Compression",
      "type": "topic",
      "url": "/documentation/compression"
    },
    "doc://com.apple.compression/documentation/Compression/COMPRESSION_STREAM_DECODE": {
      "abstract": [
        {
          "text": "A constant indicating a decompression operation.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "COMPRESSION_STREAM_DECODE"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@EA@compression_stream_operation",
          "text": "compression_stream_operation"
        }
      ],
      "identifier": "doc://com.apple.compression/documentation/Compression/COMPRESSION_STREAM_DECODE",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "COMPRESSION_STREAM_DECODE"
        }
      ],
      "role": "symbol",
      "title": "COMPRESSION_STREAM_DECODE",
      "type": "topic",
      "url": "/documentation/compression/compression_stream_decode"
    },
    "doc://com.apple.compression/documentation/Compression/COMPRESSION_STREAM_ENCODE": {
      "abstract": [
        {
          "text": "A constant indicating a compression operation.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "COMPRESSION_STREAM_ENCODE"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@EA@compression_stream_operation",
          "text": "compression_stream_operation"
        }
      ],
      "identifier": "doc://com.apple.compression/documentation/Compression/COMPRESSION_STREAM_ENCODE",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "COMPRESSION_STREAM_ENCODE"
        }
      ],
      "role": "symbol",
      "title": "COMPRESSION_STREAM_ENCODE",
      "type": "topic",
      "url": "/documentation/compression/compression_stream_encode"
    },
    "doc://com.apple.compression/documentation/Compression/compression_stream_operation": {
      "abstract": [
        {
          "text": "A set of values used to represent a stream compression operation.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "compression_stream_operation"
        }
      ],
      "identifier": "doc://com.apple.compression/documentation/Compression/compression_stream_operation",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "compression_stream_operation"
        }
      ],
      "role": "symbol",
      "title": "compression_stream_operation",
      "type": "topic",
      "url": "/documentation/compression/compression_stream_operation"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Operation-Constants",
      "generated": true,
      "identifiers": [
        "doc://com.apple.compression/documentation/Compression/COMPRESSION_STREAM_DECODE"
      ],
      "title": "Operation Constants"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "visionOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration Case"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "COMPRESSION_STREAM_ENCODE"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "case"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "COMPRESSION_STREAM_ENCODE"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.compression/documentation/Compression",
                "doc://com.apple.compression/documentation/Compression/compression_stream_operation"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Operation-Constants",
              "generated": true,
              "identifiers": [
                "doc://com.apple.compression/documentation/Compression/COMPRESSION_STREAM_DECODE"
              ],
              "title": "Operation Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "identifier",
                    "text": "COMPRESSION_STREAM_ENCODE"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.compression~1documentation~1Compression~1COMPRESSION_STREAM_DECODE/title",
          "value": "COMPRESSION_STREAM_DECODE"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.compression~1documentation~1Compression~1COMPRESSION_STREAM_DECODE/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "COMPRESSION_STREAM_DECODE"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.compression~1documentation~1Compression~1COMPRESSION_STREAM_ENCODE/title",
          "value": "COMPRESSION_STREAM_ENCODE"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.compression~1documentation~1Compression~1COMPRESSION_STREAM_ENCODE/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "COMPRESSION_STREAM_ENCODE"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.compression~1documentation~1Compression~1compression_stream_operation/title",
          "value": "compression_stream_operation"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.compression~1documentation~1Compression~1compression_stream_operation/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "compression_stream_operation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.compression~1documentation~1Compression~1compression_stream_operation/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "compression_stream_operation"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/compression/compression_stream_encode"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/compression/compression_stream_encode"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
