{
  "abstract": [
    {
      "text": "Indicates an error with stream compression.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.compression/documentation/Compression"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.compression/documentation/Compression/COMPRESSION_STATUS_ERROR"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@EA@compression_status@COMPRESSION_STATUS_ERROR",
    "fragments": [
      {
        "kind": "keyword",
        "text": "var"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "COMPRESSION_STATUS_ERROR"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@EA@compression_status",
        "text": "compression_status"
      }
    ],
    "modules": [
      {
        "name": "Compression"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "COMPRESSION_STATUS_ERROR"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Global Variable",
    "symbolKind": "var",
    "title": "COMPRESSION_STATUS_ERROR"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "var"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "COMPRESSION_STATUS_ERROR"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.compression/documentation/Compression/compression_status",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@EA@compression_status",
              "text": "compression_status"
            },
            {
              "kind": "text",
              "text": " { "
            },
            {
              "kind": "keyword",
              "text": "get"
            },
            {
              "kind": "text",
              "text": " }"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "If there’s an error with stream compression or decompression, for example if the encoded data is corrupted, ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.compression/documentation/Compression/compression_stream_process(_:_:)",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " returns ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.compression/documentation/Compression/COMPRESSION_STATUS_ERROR",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ".",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.compression/documentation/Compression": {
      "abstract": [
        {
          "text": "Leverage common compression algorithms for lossless data compression.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.compression/documentation/Compression",
      "kind": "symbol",
      "role": "collection",
      "title": "Compression",
      "type": "topic",
      "url": "/documentation/compression"
    },
    "doc://com.apple.compression/documentation/Compression/COMPRESSION_STATUS_END": {
      "abstract": [
        {
          "text": "Indicates the stream has read all input from the source, and written all output to the destination.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "COMPRESSION_STATUS_END"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@EA@compression_status",
          "text": "compression_status"
        }
      ],
      "identifier": "doc://com.apple.compression/documentation/Compression/COMPRESSION_STATUS_END",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "COMPRESSION_STATUS_END"
        }
      ],
      "role": "symbol",
      "title": "COMPRESSION_STATUS_END",
      "type": "topic",
      "url": "/documentation/compression/compression_status_end"
    },
    "doc://com.apple.compression/documentation/Compression/COMPRESSION_STATUS_ERROR": {
      "abstract": [
        {
          "text": "Indicates an error with stream compression.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "COMPRESSION_STATUS_ERROR"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@EA@compression_status",
          "text": "compression_status"
        }
      ],
      "identifier": "doc://com.apple.compression/documentation/Compression/COMPRESSION_STATUS_ERROR",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "COMPRESSION_STATUS_ERROR"
        }
      ],
      "role": "symbol",
      "title": "COMPRESSION_STATUS_ERROR",
      "type": "topic",
      "url": "/documentation/compression/compression_status_error"
    },
    "doc://com.apple.compression/documentation/Compression/COMPRESSION_STATUS_OK": {
      "abstract": [
        {
          "text": "Indicates the stream has consumed all data in the source buffer, or used all space in the destination buffer.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "COMPRESSION_STATUS_OK"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@EA@compression_status",
          "text": "compression_status"
        }
      ],
      "identifier": "doc://com.apple.compression/documentation/Compression/COMPRESSION_STATUS_OK",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "COMPRESSION_STATUS_OK"
        }
      ],
      "role": "symbol",
      "title": "COMPRESSION_STATUS_OK",
      "type": "topic",
      "url": "/documentation/compression/compression_status_ok"
    },
    "doc://com.apple.compression/documentation/Compression/compression_status": {
      "abstract": [
        {
          "text": "A set of values used to represent the status of stream compression.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "compression_status"
        }
      ],
      "identifier": "doc://com.apple.compression/documentation/Compression/compression_status",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "compression_status"
        }
      ],
      "role": "symbol",
      "title": "compression_status",
      "type": "topic",
      "url": "/documentation/compression/compression_status"
    },
    "doc://com.apple.compression/documentation/Compression/compression_stream_process(_:_:)": {
      "abstract": [
        {
          "text": "Performs compression or decompression using an initialized compression stream structure.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "compression_stream_process"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sp",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@SA@compression_stream",
          "text": "compression_stream"
        },
        {
          "kind": "text",
          "text": ">, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int32V",
          "text": "Int32"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@EA@compression_status",
          "text": "compression_status"
        }
      ],
      "identifier": "doc://com.apple.compression/documentation/Compression/compression_stream_process(_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "compression_stream_process"
        }
      ],
      "role": "symbol",
      "title": "compression_stream_process(_:_:)",
      "type": "topic",
      "url": "/documentation/compression/compression_stream_process(_:_:)"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Status-Constants",
      "generated": true,
      "identifiers": [
        "doc://com.apple.compression/documentation/Compression/COMPRESSION_STATUS_OK",
        "doc://com.apple.compression/documentation/Compression/COMPRESSION_STATUS_END"
      ],
      "title": "Status Constants"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "visionOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration Case"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "COMPRESSION_STATUS_ERROR"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "case"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "COMPRESSION_STATUS_ERROR"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.compression/documentation/Compression",
                "doc://com.apple.compression/documentation/Compression/compression_status"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Status-Constants",
              "generated": true,
              "identifiers": [
                "doc://com.apple.compression/documentation/Compression/COMPRESSION_STATUS_OK",
                "doc://com.apple.compression/documentation/Compression/COMPRESSION_STATUS_END"
              ],
              "title": "Status Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "identifier",
                    "text": "COMPRESSION_STATUS_ERROR"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.compression~1documentation~1Compression~1compression_status/title",
          "value": "compression_status"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.compression~1documentation~1Compression~1compression_status/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "compression_status"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.compression~1documentation~1Compression~1compression_status/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "compression_status"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.compression~1documentation~1Compression~1COMPRESSION_STATUS_OK/title",
          "value": "COMPRESSION_STATUS_OK"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.compression~1documentation~1Compression~1COMPRESSION_STATUS_OK/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "COMPRESSION_STATUS_OK"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.compression~1documentation~1Compression~1COMPRESSION_STATUS_END/title",
          "value": "COMPRESSION_STATUS_END"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.compression~1documentation~1Compression~1COMPRESSION_STATUS_END/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "COMPRESSION_STATUS_END"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.compression~1documentation~1Compression~1COMPRESSION_STATUS_ERROR/title",
          "value": "COMPRESSION_STATUS_ERROR"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.compression~1documentation~1Compression~1COMPRESSION_STATUS_ERROR/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "COMPRESSION_STATUS_ERROR"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.compression~1documentation~1Compression~1compression_stream_process(_:_:)/title",
          "value": "compression_stream_process"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.compression~1documentation~1Compression~1compression_stream_process(_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "compression_stream_process"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/compression/compression_status_error"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/compression/compression_status_error"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
