{
  "abstract": [
    {
      "text": "Specifies the line cap style for the shape’s path.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.quartzcore/documentation/QuartzCore",
        "doc://com.apple.quartzcore/documentation/QuartzCore/CAShapeLayer"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.quartzcore/documentation/QuartzCore/CAShapeLayer/lineCap"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(cs)CAShapeLayer(py)lineCap",
    "fragments": [
      {
        "kind": "keyword",
        "text": "var"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "lineCap"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@T@CAShapeLayerLineCap",
        "text": "CAShapeLayerLineCap"
      }
    ],
    "modules": [
      {
        "name": "Core Animation"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "lineCap"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "3.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "3.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.1",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.6",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "9.0",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Instance Property",
    "symbolKind": "property",
    "title": "lineCap"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "var"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "lineCap"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.quartzcore/documentation/QuartzCore/CAShapeLayerLineCap",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@CAShapeLayerLineCap",
              "text": "CAShapeLayerLineCap"
            },
            {
              "kind": "text",
              "text": " { "
            },
            {
              "kind": "keyword",
              "text": "get"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "keyword",
              "text": "set"
            },
            {
              "kind": "text",
              "text": " }"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "The line cap style specifies the shape of the endpoints of an open path when stroked. The supported values are described in ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.quartzcore/documentation/QuartzCore/line-cap-values",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ". The following figure shows the appearance of the available line cap styles.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "identifier": "media-1965770",
              "type": "image"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "The default is ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.quartzcore/documentation/QuartzCore/CAShapeLayerLineCap/butt",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ".",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.quartzcore/documentation/QuartzCore": {
      "abstract": [
        {
          "text": "Render, compose, and animate visual elements.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.quartzcore/documentation/QuartzCore",
      "kind": "symbol",
      "role": "collection",
      "title": "Core Animation",
      "type": "topic",
      "url": "/documentation/quartzcore"
    },
    "doc://com.apple.quartzcore/documentation/QuartzCore/CAShapeLayer": {
      "abstract": [
        {
          "text": "A layer that draws a cubic Bezier spline in its coordinate space.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CAShapeLayer"
        }
      ],
      "identifier": "doc://com.apple.quartzcore/documentation/QuartzCore/CAShapeLayer",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CAShapeLayer"
        }
      ],
      "role": "symbol",
      "title": "CAShapeLayer",
      "type": "topic",
      "url": "/documentation/quartzcore/cashapelayer"
    },
    "doc://com.apple.quartzcore/documentation/QuartzCore/CAShapeLayer/fillColor": {
      "abstract": [
        {
          "text": "The color used to fill the shape’s path. Animatable.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "fillColor"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CGColorRef",
          "text": "CGColor"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.quartzcore/documentation/QuartzCore/CAShapeLayer/fillColor",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "fillColor"
        }
      ],
      "role": "symbol",
      "title": "fillColor",
      "type": "topic",
      "url": "/documentation/quartzcore/cashapelayer/fillcolor"
    },
    "doc://com.apple.quartzcore/documentation/QuartzCore/CAShapeLayer/fillRule": {
      "abstract": [
        {
          "text": "The fill rule used when filling the shape’s path.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "fillRule"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CAShapeLayerFillRule",
          "text": "CAShapeLayerFillRule"
        }
      ],
      "identifier": "doc://com.apple.quartzcore/documentation/QuartzCore/CAShapeLayer/fillRule",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "fillRule"
        }
      ],
      "role": "symbol",
      "title": "fillRule",
      "type": "topic",
      "url": "/documentation/quartzcore/cashapelayer/fillrule"
    },
    "doc://com.apple.quartzcore/documentation/QuartzCore/CAShapeLayer/lineCap": {
      "abstract": [
        {
          "text": "Specifies the line cap style for the shape’s path.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "lineCap"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CAShapeLayerLineCap",
          "text": "CAShapeLayerLineCap"
        }
      ],
      "identifier": "doc://com.apple.quartzcore/documentation/QuartzCore/CAShapeLayer/lineCap",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "lineCap"
        }
      ],
      "role": "symbol",
      "title": "lineCap",
      "type": "topic",
      "url": "/documentation/quartzcore/cashapelayer/linecap"
    },
    "doc://com.apple.quartzcore/documentation/QuartzCore/CAShapeLayer/lineDashPattern": {
      "abstract": [
        {
          "text": "The dash pattern applied to the shape’s path when stroked.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "lineDashPattern"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSNumber",
          "text": "NSNumber"
        },
        {
          "kind": "text",
          "text": "]?"
        }
      ],
      "identifier": "doc://com.apple.quartzcore/documentation/QuartzCore/CAShapeLayer/lineDashPattern",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "lineDashPattern"
        }
      ],
      "role": "symbol",
      "title": "lineDashPattern",
      "type": "topic",
      "url": "/documentation/quartzcore/cashapelayer/linedashpattern"
    },
    "doc://com.apple.quartzcore/documentation/QuartzCore/CAShapeLayer/lineDashPhase": {
      "abstract": [
        {
          "text": "The dash phase applied to the shape’s path when stroked. Animatable.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "lineDashPhase"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:14CoreFoundation7CGFloatV",
          "text": "CGFloat"
        }
      ],
      "identifier": "doc://com.apple.quartzcore/documentation/QuartzCore/CAShapeLayer/lineDashPhase",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "lineDashPhase"
        }
      ],
      "role": "symbol",
      "title": "lineDashPhase",
      "type": "topic",
      "url": "/documentation/quartzcore/cashapelayer/linedashphase"
    },
    "doc://com.apple.quartzcore/documentation/QuartzCore/CAShapeLayer/lineJoin": {
      "abstract": [
        {
          "text": "Specifies the line join style for the shape’s path.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "lineJoin"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CAShapeLayerLineJoin",
          "text": "CAShapeLayerLineJoin"
        }
      ],
      "identifier": "doc://com.apple.quartzcore/documentation/QuartzCore/CAShapeLayer/lineJoin",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "lineJoin"
        }
      ],
      "role": "symbol",
      "title": "lineJoin",
      "type": "topic",
      "url": "/documentation/quartzcore/cashapelayer/linejoin"
    },
    "doc://com.apple.quartzcore/documentation/QuartzCore/CAShapeLayer/lineWidth": {
      "abstract": [
        {
          "text": "Specifies the line width of the shape’s path. Animatable.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "lineWidth"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:14CoreFoundation7CGFloatV",
          "text": "CGFloat"
        }
      ],
      "identifier": "doc://com.apple.quartzcore/documentation/QuartzCore/CAShapeLayer/lineWidth",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "lineWidth"
        }
      ],
      "role": "symbol",
      "title": "lineWidth",
      "type": "topic",
      "url": "/documentation/quartzcore/cashapelayer/linewidth"
    },
    "doc://com.apple.quartzcore/documentation/QuartzCore/CAShapeLayer/miterLimit": {
      "abstract": [
        {
          "text": "The miter limit used when stroking the shape’s path. Animatable.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "miterLimit"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:14CoreFoundation7CGFloatV",
          "text": "CGFloat"
        }
      ],
      "identifier": "doc://com.apple.quartzcore/documentation/QuartzCore/CAShapeLayer/miterLimit",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "miterLimit"
        }
      ],
      "role": "symbol",
      "title": "miterLimit",
      "type": "topic",
      "url": "/documentation/quartzcore/cashapelayer/miterlimit"
    },
    "doc://com.apple.quartzcore/documentation/QuartzCore/CAShapeLayer/strokeColor": {
      "abstract": [
        {
          "text": "The color used to stroke the shape’s path. Animatable.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "strokeColor"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CGColorRef",
          "text": "CGColor"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.quartzcore/documentation/QuartzCore/CAShapeLayer/strokeColor",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "strokeColor"
        }
      ],
      "role": "symbol",
      "title": "strokeColor",
      "type": "topic",
      "url": "/documentation/quartzcore/cashapelayer/strokecolor"
    },
    "doc://com.apple.quartzcore/documentation/QuartzCore/CAShapeLayer/strokeEnd": {
      "abstract": [
        {
          "text": "The relative location at which to stop stroking the path. Animatable.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "strokeEnd"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:14CoreFoundation7CGFloatV",
          "text": "CGFloat"
        }
      ],
      "identifier": "doc://com.apple.quartzcore/documentation/QuartzCore/CAShapeLayer/strokeEnd",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "strokeEnd"
        }
      ],
      "role": "symbol",
      "title": "strokeEnd",
      "type": "topic",
      "url": "/documentation/quartzcore/cashapelayer/strokeend"
    },
    "doc://com.apple.quartzcore/documentation/QuartzCore/CAShapeLayer/strokeStart": {
      "abstract": [
        {
          "text": "The relative location at which to begin stroking the path. Animatable.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "strokeStart"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:14CoreFoundation7CGFloatV",
          "text": "CGFloat"
        }
      ],
      "identifier": "doc://com.apple.quartzcore/documentation/QuartzCore/CAShapeLayer/strokeStart",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "strokeStart"
        }
      ],
      "role": "symbol",
      "title": "strokeStart",
      "type": "topic",
      "url": "/documentation/quartzcore/cashapelayer/strokestart"
    },
    "doc://com.apple.quartzcore/documentation/QuartzCore/CAShapeLayerLineCap": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CAShapeLayerLineCap"
        }
      ],
      "identifier": "doc://com.apple.quartzcore/documentation/QuartzCore/CAShapeLayerLineCap",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CAShapeLayerLineCap"
        }
      ],
      "role": "symbol",
      "title": "CAShapeLayerLineCap",
      "type": "topic",
      "url": "/documentation/quartzcore/cashapelayerlinecap"
    },
    "doc://com.apple.quartzcore/documentation/QuartzCore/CAShapeLayerLineCap/butt": {
      "abstract": [
        {
          "text": "Specifies a butt line cap style for endpoints for an open path when stroked.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "butt"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CAShapeLayerLineCap",
          "text": "CAShapeLayerLineCap"
        }
      ],
      "identifier": "doc://com.apple.quartzcore/documentation/QuartzCore/CAShapeLayerLineCap/butt",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCALineCapButt"
        }
      ],
      "role": "symbol",
      "title": "butt",
      "type": "topic",
      "url": "/documentation/quartzcore/cashapelayerlinecap/butt"
    },
    "doc://com.apple.quartzcore/documentation/QuartzCore/line-cap-values": {
      "abstract": [
        {
          "text": "These constants specify the shape of endpoints for an open path when stroked.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.quartzcore/documentation/QuartzCore/line-cap-values",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Line Cap Values",
      "type": "topic",
      "url": "/documentation/quartzcore/line-cap-values"
    },
    "media-1965770": {
      "alt": null,
      "identifier": "media-1965770",
      "type": "image",
      "variants": [
        {
          "traits": [
            "1x",
            "light"
          ],
          "url": "https://docs-assets.developer.apple.com/published/5639a2a1fdd14a26edcf53a53ca3d86a/media-1965770.gif"
        }
      ]
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Accessing-Shape-Style-Properties",
      "generated": true,
      "identifiers": [
        "doc://com.apple.quartzcore/documentation/QuartzCore/CAShapeLayer/fillColor",
        "doc://com.apple.quartzcore/documentation/QuartzCore/CAShapeLayer/fillRule",
        "doc://com.apple.quartzcore/documentation/QuartzCore/CAShapeLayer/lineDashPattern",
        "doc://com.apple.quartzcore/documentation/QuartzCore/CAShapeLayer/lineDashPhase",
        "doc://com.apple.quartzcore/documentation/QuartzCore/CAShapeLayer/lineJoin",
        "doc://com.apple.quartzcore/documentation/QuartzCore/CAShapeLayer/lineWidth",
        "doc://com.apple.quartzcore/documentation/QuartzCore/CAShapeLayer/miterLimit",
        "doc://com.apple.quartzcore/documentation/QuartzCore/CAShapeLayer/strokeColor",
        "doc://com.apple.quartzcore/documentation/QuartzCore/CAShapeLayer/strokeStart",
        "doc://com.apple.quartzcore/documentation/QuartzCore/CAShapeLayer/strokeEnd"
      ],
      "title": "Accessing Shape Style Properties"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "3.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "3.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.1",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.6",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "9.0",
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Instance Property"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "lineCap"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "property"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "lineCap"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.quartzcore/documentation/QuartzCore",
                "doc://com.apple.quartzcore/documentation/QuartzCore/CAShapeLayer"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Accessing-Shape-Style-Properties",
              "generated": true,
              "identifiers": [
                "doc://com.apple.quartzcore/documentation/QuartzCore/CAShapeLayer/fillColor",
                "doc://com.apple.quartzcore/documentation/QuartzCore/CAShapeLayer/fillRule",
                "doc://com.apple.quartzcore/documentation/QuartzCore/CAShapeLayer/lineDashPattern",
                "doc://com.apple.quartzcore/documentation/QuartzCore/CAShapeLayer/lineDashPhase",
                "doc://com.apple.quartzcore/documentation/QuartzCore/CAShapeLayer/lineJoin",
                "doc://com.apple.quartzcore/documentation/QuartzCore/CAShapeLayer/lineWidth",
                "doc://com.apple.quartzcore/documentation/QuartzCore/CAShapeLayer/miterLimit",
                "doc://com.apple.quartzcore/documentation/QuartzCore/CAShapeLayer/strokeColor",
                "doc://com.apple.quartzcore/documentation/QuartzCore/CAShapeLayer/strokeStart",
                "doc://com.apple.quartzcore/documentation/QuartzCore/CAShapeLayer/strokeEnd"
              ],
              "title": "Accessing Shape Style Properties"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "@property"
                  },
                  {
                    "kind": "text",
                    "text": " ("
                  },
                  {
                    "kind": "keyword",
                    "text": "copy"
                  },
                  {
                    "kind": "text",
                    "text": ") "
                  },
                  {
                    "identifier": "doc://com.apple.quartzcore/documentation/QuartzCore/CAShapeLayerLineCap",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@CAShapeLayerLineCap",
                    "text": "CAShapeLayerLineCap"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "lineCap"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartzcore~1documentation~1QuartzCore~1CAShapeLayerLineCap~1butt/title",
          "value": "kCALineCapButt"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartzcore~1documentation~1QuartzCore~1CAShapeLayerLineCap~1butt/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCALineCapButt"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartzcore~1documentation~1QuartzCore~1CAShapeLayerLineCap/title",
          "value": "CAShapeLayerLineCap"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartzcore~1documentation~1QuartzCore~1CAShapeLayerLineCap/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CAShapeLayerLineCap"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartzcore~1documentation~1QuartzCore~1CAShapeLayerLineCap/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CAShapeLayerLineCap"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartzcore~1documentation~1QuartzCore~1CAShapeLayer~1lineCap/title",
          "value": "lineCap"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartzcore~1documentation~1QuartzCore~1CAShapeLayer~1lineCap/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "lineCap"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartzcore~1documentation~1QuartzCore~1CAShapeLayer~1fillColor/title",
          "value": "fillColor"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartzcore~1documentation~1QuartzCore~1CAShapeLayer~1fillColor/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "fillColor"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartzcore~1documentation~1QuartzCore~1CAShapeLayer~1strokeColor/title",
          "value": "strokeColor"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartzcore~1documentation~1QuartzCore~1CAShapeLayer~1strokeColor/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "strokeColor"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartzcore~1documentation~1QuartzCore~1CAShapeLayer~1lineDashPattern/title",
          "value": "lineDashPattern"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartzcore~1documentation~1QuartzCore~1CAShapeLayer~1lineDashPattern/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "lineDashPattern"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartzcore~1documentation~1QuartzCore~1CAShapeLayer~1strokeStart/title",
          "value": "strokeStart"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartzcore~1documentation~1QuartzCore~1CAShapeLayer~1strokeStart/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "strokeStart"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartzcore~1documentation~1QuartzCore~1CAShapeLayer/title",
          "value": "CAShapeLayer"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartzcore~1documentation~1QuartzCore~1CAShapeLayer/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CAShapeLayer"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartzcore~1documentation~1QuartzCore~1CAShapeLayer/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CAShapeLayer"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartzcore~1documentation~1QuartzCore~1CAShapeLayer~1miterLimit/title",
          "value": "miterLimit"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartzcore~1documentation~1QuartzCore~1CAShapeLayer~1miterLimit/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "miterLimit"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartzcore~1documentation~1QuartzCore~1CAShapeLayer~1lineWidth/title",
          "value": "lineWidth"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartzcore~1documentation~1QuartzCore~1CAShapeLayer~1lineWidth/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "lineWidth"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartzcore~1documentation~1QuartzCore~1CAShapeLayer~1strokeEnd/title",
          "value": "strokeEnd"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartzcore~1documentation~1QuartzCore~1CAShapeLayer~1strokeEnd/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "strokeEnd"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartzcore~1documentation~1QuartzCore~1CAShapeLayer~1lineDashPhase/title",
          "value": "lineDashPhase"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartzcore~1documentation~1QuartzCore~1CAShapeLayer~1lineDashPhase/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "lineDashPhase"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartzcore~1documentation~1QuartzCore~1CAShapeLayer~1lineJoin/title",
          "value": "lineJoin"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartzcore~1documentation~1QuartzCore~1CAShapeLayer~1lineJoin/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "lineJoin"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartzcore~1documentation~1QuartzCore~1CAShapeLayer~1fillRule/title",
          "value": "fillRule"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartzcore~1documentation~1QuartzCore~1CAShapeLayer~1fillRule/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "fillRule"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/quartzcore/cashapelayer/linecap"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/quartzcore/cashapelayer/linecap"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
