{
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/CAClockPropertyID"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/CAClockPropertyID/smpteFormat"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@CAClockPropertyID@kCAClockProperty_SMPTEFormat",
    "fragments": [
      {
        "kind": "keyword",
        "text": "case"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "smpteFormat"
      }
    ],
    "modules": [
      {
        "name": "Audio Toolbox"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "kCAClockProperty_SMPTEFormat"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Case",
    "symbolKind": "case",
    "title": "CAClockPropertyID.smpteFormat"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "macOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "case"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "smpteFormat"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox": {
      "abstract": [
        {
          "text": "Record or play audio, convert formats, parse audio streams, and configure your audio session.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox",
      "kind": "symbol",
      "role": "collection",
      "title": "Audio Toolbox",
      "type": "topic",
      "url": "/documentation/audiotoolbox"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/CAClockPropertyID": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CAClockPropertyID"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/CAClockPropertyID",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CAClockPropertyID"
        }
      ],
      "role": "symbol",
      "title": "CAClockPropertyID",
      "type": "topic",
      "url": "/documentation/audiotoolbox/caclockpropertyid"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/CAClockPropertyID/internalTimebase": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "internalTimebase"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/CAClockPropertyID/internalTimebase",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCAClockProperty_InternalTimebase"
        }
      ],
      "role": "symbol",
      "title": "CAClockPropertyID.internalTimebase",
      "type": "topic",
      "url": "/documentation/audiotoolbox/caclockpropertyid/internaltimebase"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/CAClockPropertyID/meterTrack": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "meterTrack"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/CAClockPropertyID/meterTrack",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCAClockProperty_MeterTrack"
        }
      ],
      "role": "symbol",
      "title": "CAClockPropertyID.meterTrack",
      "type": "topic",
      "url": "/documentation/audiotoolbox/caclockpropertyid/metertrack"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/CAClockPropertyID/midiClockDestinations": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "midiClockDestinations"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/CAClockPropertyID/midiClockDestinations",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCAClockProperty_MIDIClockDestinations"
        }
      ],
      "role": "symbol",
      "title": "CAClockPropertyID.midiClockDestinations",
      "type": "topic",
      "url": "/documentation/audiotoolbox/caclockpropertyid/midiclockdestinations"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/CAClockPropertyID/mtcDestinations": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "mtcDestinations"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/CAClockPropertyID/mtcDestinations",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCAClockProperty_MTCDestinations"
        }
      ],
      "role": "symbol",
      "title": "CAClockPropertyID.mtcDestinations",
      "type": "topic",
      "url": "/documentation/audiotoolbox/caclockpropertyid/mtcdestinations"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/CAClockPropertyID/mtcFreewheelTime": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "mtcFreewheelTime"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/CAClockPropertyID/mtcFreewheelTime",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCAClockProperty_MTCFreewheelTime"
        }
      ],
      "role": "symbol",
      "title": "CAClockPropertyID.mtcFreewheelTime",
      "type": "topic",
      "url": "/documentation/audiotoolbox/caclockpropertyid/mtcfreewheeltime"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/CAClockPropertyID/name": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "name"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/CAClockPropertyID/name",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCAClockProperty_Name"
        }
      ],
      "role": "symbol",
      "title": "CAClockPropertyID.name",
      "type": "topic",
      "url": "/documentation/audiotoolbox/caclockpropertyid/name"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/CAClockPropertyID/sendMIDISPP": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "sendMIDISPP"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/CAClockPropertyID/sendMIDISPP",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCAClockProperty_SendMIDISPP"
        }
      ],
      "role": "symbol",
      "title": "CAClockPropertyID.sendMIDISPP",
      "type": "topic",
      "url": "/documentation/audiotoolbox/caclockpropertyid/sendmidispp"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/CAClockPropertyID/smpteFormat": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "smpteFormat"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/CAClockPropertyID/smpteFormat",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCAClockProperty_SMPTEFormat"
        }
      ],
      "role": "symbol",
      "title": "CAClockPropertyID.smpteFormat",
      "type": "topic",
      "url": "/documentation/audiotoolbox/caclockpropertyid/smpteformat"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/CAClockPropertyID/smpteOffset": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "smpteOffset"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/CAClockPropertyID/smpteOffset",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCAClockProperty_SMPTEOffset"
        }
      ],
      "role": "symbol",
      "title": "CAClockPropertyID.smpteOffset",
      "type": "topic",
      "url": "/documentation/audiotoolbox/caclockpropertyid/smpteoffset"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/CAClockPropertyID/syncMode": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "syncMode"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/CAClockPropertyID/syncMode",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCAClockProperty_SyncMode"
        }
      ],
      "role": "symbol",
      "title": "CAClockPropertyID.syncMode",
      "type": "topic",
      "url": "/documentation/audiotoolbox/caclockpropertyid/syncmode"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/CAClockPropertyID/syncSource": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "syncSource"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/CAClockPropertyID/syncSource",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCAClockProperty_SyncSource"
        }
      ],
      "role": "symbol",
      "title": "CAClockPropertyID.syncSource",
      "type": "topic",
      "url": "/documentation/audiotoolbox/caclockpropertyid/syncsource"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/CAClockPropertyID/tempoMap": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "tempoMap"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/CAClockPropertyID/tempoMap",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCAClockProperty_TempoMap"
        }
      ],
      "role": "symbol",
      "title": "CAClockPropertyID.tempoMap",
      "type": "topic",
      "url": "/documentation/audiotoolbox/caclockpropertyid/tempomap"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/CAClockPropertyID/timebaseSource": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "timebaseSource"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/CAClockPropertyID/timebaseSource",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCAClockProperty_TimebaseSource"
        }
      ],
      "role": "symbol",
      "title": "CAClockPropertyID.timebaseSource",
      "type": "topic",
      "url": "/documentation/audiotoolbox/caclockpropertyid/timebasesource"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Constants",
      "generated": true,
      "identifiers": [
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/CAClockPropertyID/internalTimebase",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/CAClockPropertyID/midiClockDestinations",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/CAClockPropertyID/mtcDestinations",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/CAClockPropertyID/mtcFreewheelTime",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/CAClockPropertyID/meterTrack",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/CAClockPropertyID/name",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/CAClockPropertyID/smpteOffset",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/CAClockPropertyID/sendMIDISPP",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/CAClockPropertyID/syncMode",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/CAClockPropertyID/syncSource",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/CAClockPropertyID/tempoMap",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/CAClockPropertyID/timebaseSource"
      ],
      "title": "Constants"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "name": "macOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration Case"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "kCAClockProperty_SMPTEFormat"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "case"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCAClockProperty_SMPTEFormat"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/CAClockPropertyID"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Constants",
              "generated": true,
              "identifiers": [
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/CAClockPropertyID/internalTimebase",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/CAClockPropertyID/midiClockDestinations",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/CAClockPropertyID/mtcDestinations",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/CAClockPropertyID/mtcFreewheelTime",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/CAClockPropertyID/meterTrack",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/CAClockPropertyID/name",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/CAClockPropertyID/smpteOffset",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/CAClockPropertyID/sendMIDISPP",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/CAClockPropertyID/syncMode",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/CAClockPropertyID/syncSource",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/CAClockPropertyID/tempoMap",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/CAClockPropertyID/timebaseSource"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "macOS"
                ],
                "tokens": [
                  {
                    "kind": "identifier",
                    "text": "kCAClockProperty_SMPTEFormat"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1CAClockPropertyID~1timebaseSource/title",
          "value": "kCAClockProperty_TimebaseSource"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1CAClockPropertyID~1timebaseSource/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCAClockProperty_TimebaseSource"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1CAClockPropertyID~1midiClockDestinations/title",
          "value": "kCAClockProperty_MIDIClockDestinations"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1CAClockPropertyID~1midiClockDestinations/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCAClockProperty_MIDIClockDestinations"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1CAClockPropertyID~1name/title",
          "value": "kCAClockProperty_Name"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1CAClockPropertyID~1name/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCAClockProperty_Name"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1CAClockPropertyID~1smpteFormat/title",
          "value": "kCAClockProperty_SMPTEFormat"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1CAClockPropertyID~1smpteFormat/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCAClockProperty_SMPTEFormat"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1CAClockPropertyID~1mtcFreewheelTime/title",
          "value": "kCAClockProperty_MTCFreewheelTime"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1CAClockPropertyID~1mtcFreewheelTime/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCAClockProperty_MTCFreewheelTime"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1CAClockPropertyID~1mtcDestinations/title",
          "value": "kCAClockProperty_MTCDestinations"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1CAClockPropertyID~1mtcDestinations/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCAClockProperty_MTCDestinations"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1CAClockPropertyID/title",
          "value": "CAClockPropertyID"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1CAClockPropertyID/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CAClockPropertyID"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1CAClockPropertyID/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CAClockPropertyID"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1CAClockPropertyID~1smpteOffset/title",
          "value": "kCAClockProperty_SMPTEOffset"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1CAClockPropertyID~1smpteOffset/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCAClockProperty_SMPTEOffset"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1CAClockPropertyID~1syncMode/title",
          "value": "kCAClockProperty_SyncMode"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1CAClockPropertyID~1syncMode/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCAClockProperty_SyncMode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1CAClockPropertyID~1meterTrack/title",
          "value": "kCAClockProperty_MeterTrack"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1CAClockPropertyID~1meterTrack/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCAClockProperty_MeterTrack"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1CAClockPropertyID~1sendMIDISPP/title",
          "value": "kCAClockProperty_SendMIDISPP"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1CAClockPropertyID~1sendMIDISPP/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCAClockProperty_SendMIDISPP"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1CAClockPropertyID~1internalTimebase/title",
          "value": "kCAClockProperty_InternalTimebase"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1CAClockPropertyID~1internalTimebase/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCAClockProperty_InternalTimebase"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1CAClockPropertyID~1syncSource/title",
          "value": "kCAClockProperty_SyncSource"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1CAClockPropertyID~1syncSource/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCAClockProperty_SyncSource"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1CAClockPropertyID~1tempoMap/title",
          "value": "kCAClockProperty_TempoMap"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1CAClockPropertyID~1tempoMap/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCAClockProperty_TempoMap"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/audiotoolbox/caclockpropertyid/smpteformat"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/audiotoolbox/caclockpropertyid/smpteformat"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
