{
  "abstract": [
    {
      "text": "Request permission from the person to read and write their contact data.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.contacts/documentation/Contacts"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.contacts/documentation/Contacts/accessing-the-contact-store"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "Contacts"
      }
    ],
    "role": "article",
    "roleHeading": "Article",
    "title": "Accessing the contact store"
  },
  "primaryContentSections": [
    {
      "content": [
        {
          "anchor": "overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Your app canʼt access a personʼs Contacts entries until that person grants permission. When your app requests access to contact data, the person can",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "grant either limited or full access, or they can deny the request.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "Granting limited access to your app allows them to select specific contacts to share during the request authorization flow. They can expand or restrict",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "the list of contacts your app has access to later in the Settings app. Your app has automatic access to contacts it creates, but it can only fetch, edit,",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "or delete contacts that the person grants you access to. If the person approves full access for the app, you can create, fetch, edit, and delete contact",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "data, including contacts you didnʼt create. If the person denies the request, your app gets no access to the personʼs data.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "identifier": "doc://com.apple.documentation/documentation/ContactsUI",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " includes new APIs you can adopt for an enhanced privacy experience when someone gives full,",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "partial, or no access to your app. Use ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/ContactsUI/ContactAccessButton",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " and ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/SwiftUI/View/contactAccessPicker(isPresented:completionHandler:)",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " to let",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "the person control which contacts your app can access.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "anchor": "Provide-a-contacts-usage-description",
          "level": 3,
          "text": "Provide a contacts usage description",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "In Xcode, configure the required ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/BundleResources/Information-Property-List/NSContactsUsageDescription",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": "",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "setting in the Build Settings tab of your app target. The value for this setting is a string that explains why your app needs access to a person’s",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "contacts. The system displays the string when prompting the person to authorize your app for access. The following image shows an example contacts",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "usage description for an app that requires contacts access to edit your mailing address and profile image:",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "identifier": "media-4422032",
              "type": "image"
            }
          ],
          "type": "paragraph"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "",
                  "type": "text"
                },
                {
                  "text": " ",
                  "type": "text"
                },
                {
                  "text": "Your app crashes if you attempt to access contact data without a contacts usage description.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "Important",
          "style": "important",
          "type": "aside"
        },
        {
          "anchor": "Check-your-app-authorization-status",
          "level": 3,
          "text": "Check your app authorization status",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Verify the authorization status of your app before presenting features that require Contacts access in your UI. If your app hasn’t requested access yet,",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "any attempts to use these features automatically prompt the person for Contacts access. If the person previously denied access to your app, attempts to",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "use these features fail with a ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.contacts/documentation/Contacts/CNError/Code/authorizationDenied",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " error.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "The authorization status of your app is ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.contacts/documentation/Contacts/CNAuthorizationStatus/notDetermined",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " until the person authorizes or denies access. The person can approve or",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "deny your app’s request for authorization, then change the authorization status later in the Settings app.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "To determine your authorization status, call the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.contacts/documentation/Contacts/CNContactStore/authorizationStatus(for:)",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " class method of ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.contacts/documentation/Contacts/CNContactStore",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " with an entity type ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.contacts/documentation/Contacts/CNEntityType/contacts",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ":",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "code": [
            "let status = CNContactStore.authorizationStatus(for: .contacts)",
            "",
            "switch status {",
            "case .notDetermined:",
            "// The person hasn't yet decided whether the app may access contact data.",
            "case .restricted:",
            "// The app isn't authorized and the person can't authorize the app due to restrictions.",
            "case .denied:",
            "// The person explicitly denies access to contact data.",
            "case .authorized: ",
            "// The person authorizes access to all contact data.",
            "case .limited: ",
            "// The person authorizes access to some contact data. ",
            "}"
          ],
          "syntax": "swift",
          "type": "codeListing"
        },
        {
          "anchor": "Request-access-to-contact-data",
          "level": 3,
          "text": "Request access to contact data",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "If the authorization status of your app is ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.contacts/documentation/Contacts/CNAuthorizationStatus/notDetermined",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ", prompt the person for access by initializing the contact store, then",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "calling its ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.contacts/documentation/Contacts/CNContactStore/requestAccess(for:completionHandler:)",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " or ",
              "type": "text"
            },
            {
              "code": "requestAccess(for:)",
              "type": "codeVoice"
            },
            {
              "text": " method",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "with an entity type ",
              "type": "text"
            },
            {
              "code": "contacts",
              "type": "codeVoice"
            },
            {
              "text": ":",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "code": [
            "// Initialize the contact store. ",
            "var store = CNContactStore()",
            "",
            "// Request access to contacts.",
            "do {",
            "    let response = try await store.requestAccess(for: .contacts)",
            "} catch {",
            "    // Handle the error.",
            "}"
          ],
          "syntax": "swift",
          "type": "codeListing"
        },
        {
          "inlineContent": [
            {
              "text": "If the person grants limited access, your app receives a ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.contacts/documentation/Contacts/CNAuthorizationStatus/limited",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " authorization status. If the person grants full access, your",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "app receives a ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.contacts/documentation/Contacts/CNAuthorizationStatus/authorized",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " status. The system remembers your app’s authorization status so that subsequent calls to ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.contacts/documentation/Contacts/CNContactStore/requestAccess(for:completionHandler:)",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " or ",
              "type": "text"
            },
            {
              "code": "requestAccess(for:)",
              "type": "codeVoice"
            },
            {
              "text": " don’t prompt the person again.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "",
                  "type": "text"
                },
                {
                  "text": " ",
                  "type": "text"
                },
                {
                  "text": "If the person previously granted your app contacts access (",
                  "type": "text"
                },
                {
                  "identifier": "doc://com.apple.contacts/documentation/Contacts/CNAuthorizationStatus/authorized",
                  "isActive": true,
                  "type": "reference"
                },
                {
                  "text": ") in an earlier OS, your app still has full access in iOS 18 and later.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "Note",
          "style": "note",
          "type": "aside"
        },
        {
          "anchor": "Use-Contacts-with-limited-access",
          "level": 3,
          "text": "Use Contacts with limited access",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Your app can use the entire Contacts API when it has limited contact access. Use ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/ContactsUI/ContactAccessButton",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": "",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "to let people choose contacts to share with your app. When someone searches for a contact, the search results present contacts that your app doesn’t",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "have access to. If the person taps the button, the system immediately grants access to the contact without prompting them for authorization, and your",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "app receives a callback that includes the identifier of the newly added contact. To fetch information about this contact, create a fetch request that",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "uses ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.contacts/documentation/Contacts/CNContact/predicateForContacts(withIdentifiers:)",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ", pass the identifier to the predicate, and execute the request:",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "code": [
            "@State private var searchQuery = \"\"",
            "",
            "var body: some View {",
            "    ContactAccessButton(queryString: searchQuery) { identifiers in",
            "        // Fetch contacts whose identifiers match newly added contacts.",
            "        fetchContacts(withIdentifiers: identifiers)",
            "    }",
            "}"
          ],
          "syntax": "swift",
          "type": "codeListing"
        },
        {
          "inlineContent": [
            {
              "text": "For more information, see ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.contacts/documentation/Contacts/CNContactStore",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ".",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "If your app needs to read or modify contacts, consider presenting the contact access picker to let people update which contacts you can access. The",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "picker has full access to all contacts on the device regardless of your app’s authorization status. When the person dismisses the picker, your app",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "receives a callback that returns the identifiers of additional contacts the person chose. The callback doesn’t provide any information about contacts",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "you can no longer access or those you can already access. The following example creates a fetch request that searches for all approved contacts, executes",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "the request, and then uses the identifiers to highlight newly added contacts in the fetch result in your UI:",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "code": [
            "// Indicates whether to present the contact access picker.",
            "@State private var isPresented = false",
            "",
            "var body: some View {",
            "    // Tap the add button to present the picker.",
            "    addButton",
            "        .contactAccessPicker(isPresented: $isPresented) { identifiers in",
            "            // Fetch all contacts your app can access.",
            "            let contacts = fetchContacts()",
            "",
            "            // Highlight contacts whose identifiers match newly selected contacts.",
            "            highlightContacts(withIdentifiers: identifiers, in: contacts)",
            "        }",
            "}",
            "",
            "// An add button.",
            "private var addButton: some View {",
            "    Button {",
            "        isPresented.toggle()",
            "    } label: {",
            "        Label(\"Add contacts\", systemImage: \"person.fill.badge.plus\")",
            "    }",
            "}",
            ""
          ],
          "syntax": "swift",
          "type": "codeListing"
        },
        {
          "inlineContent": [
            {
              "text": "If you don’t adopt the contact access button or contact access picker, the person needs to use the Settings app to control which contacts you can access.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "anchor": "Add-entitlement-to-view-or-update-notes",
          "level": 3,
          "text": "Add entitlement to view or update notes",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "To read or write the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.contacts/documentation/Contacts/CNContact/note",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " field from a contact in iOS 13, macOS 13, or later, add the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/BundleResources/Entitlements/com.apple.developer.contacts.notes",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " entitlement to your app. The entitlement",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "requires permission from Apple to use, and you can’t publicly distribute your app until you have permission to use it. For more information about adding",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "the entitlement and requesting permission, see  ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/BundleResources/Entitlements/com.apple.developer.contacts.notes",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ".",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.contacts/documentation/Contacts": {
      "abstract": [
        {
          "text": "Access the user’s contacts, and format and localize contact information.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.contacts/documentation/Contacts",
      "kind": "symbol",
      "role": "collection",
      "title": "Contacts",
      "type": "topic",
      "url": "/documentation/contacts"
    },
    "doc://com.apple.contacts/documentation/Contacts/CNAuthorizationStatus/authorized": {
      "abstract": [
        {
          "text": "The application is authorized to access contact data.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "authorized"
        }
      ],
      "identifier": "doc://com.apple.contacts/documentation/Contacts/CNAuthorizationStatus/authorized",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CNAuthorizationStatusAuthorized"
        }
      ],
      "role": "symbol",
      "title": "CNAuthorizationStatus.authorized",
      "type": "topic",
      "url": "/documentation/contacts/cnauthorizationstatus/authorized"
    },
    "doc://com.apple.contacts/documentation/Contacts/CNAuthorizationStatus/limited": {
      "abstract": [
        {
          "text": "The app has access to a limited subset of contacts, chosen by the person using",
          "type": "text"
        },
        {
          "text": " ",
          "type": "text"
        },
        {
          "text": "the app.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "limited"
        }
      ],
      "identifier": "doc://com.apple.contacts/documentation/Contacts/CNAuthorizationStatus/limited",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CNAuthorizationStatusLimited"
        }
      ],
      "role": "symbol",
      "title": "CNAuthorizationStatus.limited",
      "type": "topic",
      "url": "/documentation/contacts/cnauthorizationstatus/limited"
    },
    "doc://com.apple.contacts/documentation/Contacts/CNAuthorizationStatus/notDetermined": {
      "abstract": [
        {
          "text": "The user has not yet made a choice regarding whether the application may access contact data.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "notDetermined"
        }
      ],
      "identifier": "doc://com.apple.contacts/documentation/Contacts/CNAuthorizationStatus/notDetermined",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CNAuthorizationStatusNotDetermined"
        }
      ],
      "role": "symbol",
      "title": "CNAuthorizationStatus.notDetermined",
      "type": "topic",
      "url": "/documentation/contacts/cnauthorizationstatus/notdetermined"
    },
    "doc://com.apple.contacts/documentation/Contacts/CNContact/note": {
      "abstract": [
        {
          "text": "A string containing notes for the contact.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "note"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.contacts/documentation/Contacts/CNContact/note",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "note"
        }
      ],
      "role": "symbol",
      "title": "note",
      "type": "topic",
      "url": "/documentation/contacts/cncontact/note"
    },
    "doc://com.apple.contacts/documentation/Contacts/CNContact/predicateForContacts(withIdentifiers:)": {
      "abstract": [
        {
          "text": "Returns a predicate to find the contacts matching the specified identifiers.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "predicateForContacts"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "withIdentifiers"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": "]) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSPredicate",
          "text": "NSPredicate"
        }
      ],
      "identifier": "doc://com.apple.contacts/documentation/Contacts/CNContact/predicateForContacts(withIdentifiers:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "predicateForContactsWithIdentifiers:"
        }
      ],
      "role": "symbol",
      "title": "predicateForContacts(withIdentifiers:)",
      "type": "topic",
      "url": "/documentation/contacts/cncontact/predicateforcontacts(withidentifiers:)"
    },
    "doc://com.apple.contacts/documentation/Contacts/CNContactStore": {
      "abstract": [
        {
          "text": "The object that fetches and saves contacts, groups, and containers from the user’s Contacts database.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CNContactStore"
        }
      ],
      "identifier": "doc://com.apple.contacts/documentation/Contacts/CNContactStore",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CNContactStore"
        }
      ],
      "role": "symbol",
      "title": "CNContactStore",
      "type": "topic",
      "url": "/documentation/contacts/cncontactstore"
    },
    "doc://com.apple.contacts/documentation/Contacts/CNContactStore/authorizationStatus(for:)": {
      "abstract": [
        {
          "text": "Returns the current authorization status to access the contact data.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "authorizationStatus"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "for"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@CNEntityType",
          "text": "CNEntityType"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@CNAuthorizationStatus",
          "text": "CNAuthorizationStatus"
        }
      ],
      "identifier": "doc://com.apple.contacts/documentation/Contacts/CNContactStore/authorizationStatus(for:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "authorizationStatusForEntityType:"
        }
      ],
      "role": "symbol",
      "title": "authorizationStatus(for:)",
      "type": "topic",
      "url": "/documentation/contacts/cncontactstore/authorizationstatus(for:)"
    },
    "doc://com.apple.contacts/documentation/Contacts/CNContactStore/requestAccess(for:completionHandler:)": {
      "abstract": [
        {
          "text": "Requests access to the user’s contacts.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "requestAccess"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "for"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@CNEntityType",
          "text": "CNEntityType"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "completionHandler"
        },
        {
          "kind": "text",
          "text": ": ("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        },
        {
          "kind": "text",
          "text": ", (any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5ErrorP",
          "text": "Error"
        },
        {
          "kind": "text",
          "text": ")?) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s4Voida",
          "text": "Void"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.contacts/documentation/Contacts/CNContactStore/requestAccess(for:completionHandler:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "requestAccessForEntityType:completionHandler:"
        }
      ],
      "role": "symbol",
      "title": "requestAccess(for:completionHandler:)",
      "type": "topic",
      "url": "/documentation/contacts/cncontactstore/requestaccess(for:completionhandler:)"
    },
    "doc://com.apple.contacts/documentation/Contacts/CNEntityType/contacts": {
      "abstract": [
        {
          "text": "The user’s contacts.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "contacts"
        }
      ],
      "identifier": "doc://com.apple.contacts/documentation/Contacts/CNEntityType/contacts",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CNEntityTypeContacts"
        }
      ],
      "role": "symbol",
      "title": "CNEntityType.contacts",
      "type": "topic",
      "url": "/documentation/contacts/cnentitytype/contacts"
    },
    "doc://com.apple.contacts/documentation/Contacts/CNError/Code/authorizationDenied": {
      "abstract": [
        {
          "text": "An error that indicates the system denied authorization.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "authorizationDenied"
        }
      ],
      "identifier": "doc://com.apple.contacts/documentation/Contacts/CNError/Code/authorizationDenied",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CNErrorCodeAuthorizationDenied"
        }
      ],
      "role": "symbol",
      "title": "CNError.Code.authorizationDenied",
      "type": "topic",
      "url": "/documentation/contacts/cnerror/code/authorizationdenied"
    },
    "doc://com.apple.contacts/documentation/Contacts/accessing-a-person-s-contact-data-using-contacts-and-contactsui": {
      "abstract": [
        {
          "text": "Allow people to grant your app access to contact data by adding the Contact access button and Contact access picker to your app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.contacts/documentation/Contacts/accessing-a-person-s-contact-data-using-contacts-and-contactsui",
      "kind": "article",
      "role": "sampleCode",
      "title": "Accessing a person’s contact data using Contacts and ContactsUI",
      "type": "topic",
      "url": "/documentation/contacts/accessing-a-person-s-contact-data-using-contacts-and-contactsui"
    },
    "doc://com.apple.documentation/documentation/BundleResources/Entitlements/com.apple.developer.contacts.notes": {
      "abstract": [
        {
          "text": "A Boolean value that indicates whether the app may access the notes in contact entries.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/BundleResources/Entitlements/com.apple.developer.contacts.notes",
      "kind": "symbol",
      "role": "symbol",
      "title": "com.apple.developer.contacts.notes",
      "type": "topic",
      "url": "/documentation/BundleResources/Entitlements/com.apple.developer.contacts.notes"
    },
    "doc://com.apple.documentation/documentation/BundleResources/Information-Property-List/NSContactsUsageDescription": {
      "abstract": [
        {
          "text": "A message that tells the user why the app is requesting access to the user’s contacts.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/BundleResources/Information-Property-List/NSContactsUsageDescription",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSContactsUsageDescription",
      "type": "topic",
      "url": "/documentation/BundleResources/Information-Property-List/NSContactsUsageDescription"
    },
    "doc://com.apple.documentation/documentation/ContactsUI": {
      "abstract": [
        {
          "text": "Provide an interface that allows people to display information about their contacts.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/ContactsUI",
      "kind": "symbol",
      "role": "collection",
      "title": "Contacts UI",
      "type": "topic",
      "url": "/documentation/ContactsUI"
    },
    "doc://com.apple.documentation/documentation/ContactsUI/ContactAccessButton": {
      "abstract": [
        {
          "text": "A SwiftUI button that you use to add to the set of contacts someone shares with your app.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@"
        },
        {
          "kind": "attribute",
          "preciseIdentifier": "s:ScM",
          "text": "MainActor"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "attribute",
          "text": "@preconcurrency"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ContactAccessButton"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/ContactsUI/ContactAccessButton",
      "kind": "symbol",
      "role": "symbol",
      "title": "ContactAccessButton",
      "type": "topic",
      "url": "/documentation/ContactsUI/ContactAccessButton"
    },
    "doc://com.apple.documentation/documentation/SwiftUI/View/contactAccessPicker(isPresented:completionHandler:)": {
      "abstract": [
        {
          "text": "Modally present UI which allows the user to select which contacts your app has access to.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@"
        },
        {
          "kind": "attribute",
          "preciseIdentifier": "s:ScM",
          "text": "MainActor"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "attribute",
          "text": "@preconcurrency"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "contactAccessPicker"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "isPresented"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:7SwiftUI7BindingV",
          "text": "Binding"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        },
        {
          "kind": "text",
          "text": ">, "
        },
        {
          "kind": "externalParam",
          "text": "completionHandler"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "keyword",
          "text": "@escaping"
        },
        {
          "kind": "text",
          "text": " (["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": "]) -> () = {_ in }) -> "
        },
        {
          "kind": "keyword",
          "text": "some"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:7SwiftUI4ViewP",
          "text": "View"
        },
        {
          "kind": "text",
          "text": "\n"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/SwiftUI/View/contactAccessPicker(isPresented:completionHandler:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "contactAccessPicker(isPresented:completionHandler:)",
      "type": "topic",
      "url": "/documentation/SwiftUI/View/contactAccessPicker(isPresented:completionHandler:)"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "media-4422032": {
      "alt": "A screenshot that shows a contacts usage description for an app that requires contacts access to edit your mailing address and profile image.",
      "identifier": "media-4422032",
      "type": "image",
      "variants": [
        {
          "traits": [
            "2x",
            "light"
          ],
          "url": "https://docs-assets.developer.apple.com/published/2aa45084813dbff396791d8af46ec34d/media-4422032@2x.png"
        },
        {
          "traits": [
            "2x",
            "dark"
          ],
          "url": "https://docs-assets.developer.apple.com/published/b39556790d4d8799ac0669f14d51a955/media-4422032~dark@2x.png"
        }
      ]
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Essentials",
      "generated": true,
      "identifiers": [
        "doc://com.apple.contacts/documentation/Contacts/accessing-a-person-s-contact-data-using-contacts-and-contactsui",
        "doc://com.apple.contacts/documentation/Contacts/CNContactStore",
        "doc://com.apple.documentation/documentation/BundleResources/Information-Property-List/NSContactsUsageDescription",
        "doc://com.apple.documentation/documentation/BundleResources/Entitlements/com.apple.developer.contacts.notes"
      ],
      "title": "Essentials"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Essentials",
              "generated": true,
              "identifiers": [
                "doc://com.apple.contacts/documentation/Contacts/accessing-a-person-s-contact-data-using-contacts-and-contactsui",
                "doc://com.apple.contacts/documentation/Contacts/CNContactStore",
                "doc://com.apple.documentation/documentation/BundleResources/Information-Property-List/NSContactsUsageDescription",
                "doc://com.apple.documentation/documentation/BundleResources/Entitlements/com.apple.developer.contacts.notes"
              ],
              "title": "Essentials"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.contacts~1documentation~1Contacts~1CNContactStore~1requestAccess(for:completionHandler:)/title",
          "value": "requestAccessForEntityType:completionHandler:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.contacts~1documentation~1Contacts~1CNContactStore~1requestAccess(for:completionHandler:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "requestAccessForEntityType:completionHandler:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.contacts~1documentation~1Contacts~1CNAuthorizationStatus~1notDetermined/title",
          "value": "CNAuthorizationStatusNotDetermined"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.contacts~1documentation~1Contacts~1CNAuthorizationStatus~1notDetermined/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CNAuthorizationStatusNotDetermined"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.contacts~1documentation~1Contacts~1CNAuthorizationStatus~1limited/title",
          "value": "CNAuthorizationStatusLimited"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.contacts~1documentation~1Contacts~1CNAuthorizationStatus~1limited/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CNAuthorizationStatusLimited"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.contacts~1documentation~1Contacts~1CNAuthorizationStatus~1authorized/title",
          "value": "CNAuthorizationStatusAuthorized"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.contacts~1documentation~1Contacts~1CNAuthorizationStatus~1authorized/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CNAuthorizationStatusAuthorized"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.contacts~1documentation~1Contacts~1CNContactStore/title",
          "value": "CNContactStore"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.contacts~1documentation~1Contacts~1CNContactStore/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CNContactStore"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.contacts~1documentation~1Contacts~1CNContactStore/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CNContactStore"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.contacts~1documentation~1Contacts~1CNContactStore~1authorizationStatus(for:)/title",
          "value": "authorizationStatusForEntityType:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.contacts~1documentation~1Contacts~1CNContactStore~1authorizationStatus(for:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "+ "
            },
            {
              "kind": "identifier",
              "text": "authorizationStatusForEntityType:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.contacts~1documentation~1Contacts~1CNContact~1predicateForContacts(withIdentifiers:)/title",
          "value": "predicateForContactsWithIdentifiers:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.contacts~1documentation~1Contacts~1CNContact~1predicateForContacts(withIdentifiers:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "+ "
            },
            {
              "kind": "identifier",
              "text": "predicateForContactsWithIdentifiers:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.contacts~1documentation~1Contacts~1CNEntityType~1contacts/title",
          "value": "CNEntityTypeContacts"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.contacts~1documentation~1Contacts~1CNEntityType~1contacts/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CNEntityTypeContacts"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.contacts~1documentation~1Contacts~1CNContact~1note/title",
          "value": "note"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.contacts~1documentation~1Contacts~1CNContact~1note/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "note"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.contacts~1documentation~1Contacts~1CNError~1Code~1authorizationDenied/title",
          "value": "CNErrorCodeAuthorizationDenied"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.contacts~1documentation~1Contacts~1CNError~1Code~1authorizationDenied/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CNErrorCodeAuthorizationDenied"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/contacts/accessing-the-contact-store"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/contacts/accessing-the-contact-store"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
