{
  "abstract": [
    {
      "text": "An object that represents a user removing a subgroup from a group.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.contacts/documentation/Contacts"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.contacts/documentation/Contacts/CNChangeHistoryRemoveSubgroupFromGroupEvent"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(cs)CNChangeHistoryRemoveSubgroupFromGroupEvent",
    "fragments": [
      {
        "kind": "keyword",
        "text": "class"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "CNChangeHistoryRemoveSubgroupFromGroupEvent"
      }
    ],
    "modules": [
      {
        "name": "Contacts"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "CNChangeHistoryRemoveSubgroupFromGroupEvent"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.1",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.15",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "6.0",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Class",
    "symbolKind": "class",
    "title": "CNChangeHistoryRemoveSubgroupFromGroupEvent"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "class"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "CNChangeHistoryRemoveSubgroupFromGroupEvent"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.contacts/documentation/Contacts": {
      "abstract": [
        {
          "text": "Access the user’s contacts, and format and localize contact information.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.contacts/documentation/Contacts",
      "kind": "symbol",
      "role": "collection",
      "title": "Contacts",
      "type": "topic",
      "url": "/documentation/contacts"
    },
    "doc://com.apple.contacts/documentation/Contacts/CNChangeHistoryAddContactEvent": {
      "abstract": [
        {
          "text": "An object that represents a user adding a contact.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CNChangeHistoryAddContactEvent"
        }
      ],
      "identifier": "doc://com.apple.contacts/documentation/Contacts/CNChangeHistoryAddContactEvent",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CNChangeHistoryAddContactEvent"
        }
      ],
      "role": "symbol",
      "title": "CNChangeHistoryAddContactEvent",
      "type": "topic",
      "url": "/documentation/contacts/cnchangehistoryaddcontactevent"
    },
    "doc://com.apple.contacts/documentation/Contacts/CNChangeHistoryAddGroupEvent": {
      "abstract": [
        {
          "text": "An object that represents a user adding a group.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CNChangeHistoryAddGroupEvent"
        }
      ],
      "identifier": "doc://com.apple.contacts/documentation/Contacts/CNChangeHistoryAddGroupEvent",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CNChangeHistoryAddGroupEvent"
        }
      ],
      "role": "symbol",
      "title": "CNChangeHistoryAddGroupEvent",
      "type": "topic",
      "url": "/documentation/contacts/cnchangehistoryaddgroupevent"
    },
    "doc://com.apple.contacts/documentation/Contacts/CNChangeHistoryAddMemberToGroupEvent": {
      "abstract": [
        {
          "text": "An object that represents a user adding a contact to a group.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CNChangeHistoryAddMemberToGroupEvent"
        }
      ],
      "identifier": "doc://com.apple.contacts/documentation/Contacts/CNChangeHistoryAddMemberToGroupEvent",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CNChangeHistoryAddMemberToGroupEvent"
        }
      ],
      "role": "symbol",
      "title": "CNChangeHistoryAddMemberToGroupEvent",
      "type": "topic",
      "url": "/documentation/contacts/cnchangehistoryaddmembertogroupevent"
    },
    "doc://com.apple.contacts/documentation/Contacts/CNChangeHistoryAddSubgroupToGroupEvent": {
      "abstract": [
        {
          "text": "An object that represents a user adding a subgroup to a group.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CNChangeHistoryAddSubgroupToGroupEvent"
        }
      ],
      "identifier": "doc://com.apple.contacts/documentation/Contacts/CNChangeHistoryAddSubgroupToGroupEvent",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CNChangeHistoryAddSubgroupToGroupEvent"
        }
      ],
      "role": "symbol",
      "title": "CNChangeHistoryAddSubgroupToGroupEvent",
      "type": "topic",
      "url": "/documentation/contacts/cnchangehistoryaddsubgrouptogroupevent"
    },
    "doc://com.apple.contacts/documentation/Contacts/CNChangeHistoryDeleteContactEvent": {
      "abstract": [
        {
          "text": "An object that represents a user deleting a contact.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CNChangeHistoryDeleteContactEvent"
        }
      ],
      "identifier": "doc://com.apple.contacts/documentation/Contacts/CNChangeHistoryDeleteContactEvent",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CNChangeHistoryDeleteContactEvent"
        }
      ],
      "role": "symbol",
      "title": "CNChangeHistoryDeleteContactEvent",
      "type": "topic",
      "url": "/documentation/contacts/cnchangehistorydeletecontactevent"
    },
    "doc://com.apple.contacts/documentation/Contacts/CNChangeHistoryDeleteGroupEvent": {
      "abstract": [
        {
          "text": "An object that represents a user deleting a group.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CNChangeHistoryDeleteGroupEvent"
        }
      ],
      "identifier": "doc://com.apple.contacts/documentation/Contacts/CNChangeHistoryDeleteGroupEvent",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CNChangeHistoryDeleteGroupEvent"
        }
      ],
      "role": "symbol",
      "title": "CNChangeHistoryDeleteGroupEvent",
      "type": "topic",
      "url": "/documentation/contacts/cnchangehistorydeletegroupevent"
    },
    "doc://com.apple.contacts/documentation/Contacts/CNChangeHistoryDropEverythingEvent": {
      "abstract": [
        {
          "text": "An object that indicates the delegate should drop all contacts and groups before handling change events.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CNChangeHistoryDropEverythingEvent"
        }
      ],
      "identifier": "doc://com.apple.contacts/documentation/Contacts/CNChangeHistoryDropEverythingEvent",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CNChangeHistoryDropEverythingEvent"
        }
      ],
      "role": "symbol",
      "title": "CNChangeHistoryDropEverythingEvent",
      "type": "topic",
      "url": "/documentation/contacts/cnchangehistorydropeverythingevent"
    },
    "doc://com.apple.contacts/documentation/Contacts/CNChangeHistoryEvent": {
      "abstract": [
        {
          "text": "An object that represents the user adding, updating, or deleting a contact or group.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CNChangeHistoryEvent"
        }
      ],
      "identifier": "doc://com.apple.contacts/documentation/Contacts/CNChangeHistoryEvent",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CNChangeHistoryEvent"
        }
      ],
      "role": "symbol",
      "title": "CNChangeHistoryEvent",
      "type": "topic",
      "url": "/documentation/contacts/cnchangehistoryevent"
    },
    "doc://com.apple.contacts/documentation/Contacts/CNChangeHistoryEventVisitor": {
      "abstract": [
        {
          "text": "An interface for receiving notice of changes to contacts and groups.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CNChangeHistoryEventVisitor"
        }
      ],
      "identifier": "doc://com.apple.contacts/documentation/Contacts/CNChangeHistoryEventVisitor",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CNChangeHistoryEventVisitor"
        }
      ],
      "role": "symbol",
      "title": "CNChangeHistoryEventVisitor",
      "type": "topic",
      "url": "/documentation/contacts/cnchangehistoryeventvisitor"
    },
    "doc://com.apple.contacts/documentation/Contacts/CNChangeHistoryFetchRequest": {
      "abstract": [
        {
          "text": "An object that specifies the criteria for fetching change history.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CNChangeHistoryFetchRequest"
        }
      ],
      "identifier": "doc://com.apple.contacts/documentation/Contacts/CNChangeHistoryFetchRequest",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CNChangeHistoryFetchRequest"
        }
      ],
      "role": "symbol",
      "title": "CNChangeHistoryFetchRequest",
      "type": "topic",
      "url": "/documentation/contacts/cnchangehistoryfetchrequest"
    },
    "doc://com.apple.contacts/documentation/Contacts/CNChangeHistoryRemoveMemberFromGroupEvent": {
      "abstract": [
        {
          "text": "An object that represents a user removing a contact from a group.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CNChangeHistoryRemoveMemberFromGroupEvent"
        }
      ],
      "identifier": "doc://com.apple.contacts/documentation/Contacts/CNChangeHistoryRemoveMemberFromGroupEvent",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CNChangeHistoryRemoveMemberFromGroupEvent"
        }
      ],
      "role": "symbol",
      "title": "CNChangeHistoryRemoveMemberFromGroupEvent",
      "type": "topic",
      "url": "/documentation/contacts/cnchangehistoryremovememberfromgroupevent"
    },
    "doc://com.apple.contacts/documentation/Contacts/CNChangeHistoryRemoveSubgroupFromGroupEvent": {
      "abstract": [
        {
          "text": "An object that represents a user removing a subgroup from a group.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CNChangeHistoryRemoveSubgroupFromGroupEvent"
        }
      ],
      "identifier": "doc://com.apple.contacts/documentation/Contacts/CNChangeHistoryRemoveSubgroupFromGroupEvent",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CNChangeHistoryRemoveSubgroupFromGroupEvent"
        }
      ],
      "role": "symbol",
      "title": "CNChangeHistoryRemoveSubgroupFromGroupEvent",
      "type": "topic",
      "url": "/documentation/contacts/cnchangehistoryremovesubgroupfromgroupevent"
    },
    "doc://com.apple.contacts/documentation/Contacts/CNChangeHistoryRemoveSubgroupFromGroupEvent/group": {
      "abstract": [
        {
          "text": "The group where the user removed a subgroup.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "group"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)CNGroup",
          "text": "CNGroup"
        }
      ],
      "identifier": "doc://com.apple.contacts/documentation/Contacts/CNChangeHistoryRemoveSubgroupFromGroupEvent/group",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "group"
        }
      ],
      "role": "symbol",
      "title": "group",
      "type": "topic",
      "url": "/documentation/contacts/cnchangehistoryremovesubgroupfromgroupevent/group"
    },
    "doc://com.apple.contacts/documentation/Contacts/CNChangeHistoryRemoveSubgroupFromGroupEvent/subgroup": {
      "abstract": [
        {
          "text": "The subgroup that the user removed from the group.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "subgroup"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)CNGroup",
          "text": "CNGroup"
        }
      ],
      "identifier": "doc://com.apple.contacts/documentation/Contacts/CNChangeHistoryRemoveSubgroupFromGroupEvent/subgroup",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "subgroup"
        }
      ],
      "role": "symbol",
      "title": "subgroup",
      "type": "topic",
      "url": "/documentation/contacts/cnchangehistoryremovesubgroupfromgroupevent/subgroup"
    },
    "doc://com.apple.contacts/documentation/Contacts/CNChangeHistoryUpdateContactEvent": {
      "abstract": [
        {
          "text": "An object that represents a user updating a contact.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CNChangeHistoryUpdateContactEvent"
        }
      ],
      "identifier": "doc://com.apple.contacts/documentation/Contacts/CNChangeHistoryUpdateContactEvent",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CNChangeHistoryUpdateContactEvent"
        }
      ],
      "role": "symbol",
      "title": "CNChangeHistoryUpdateContactEvent",
      "type": "topic",
      "url": "/documentation/contacts/cnchangehistoryupdatecontactevent"
    },
    "doc://com.apple.contacts/documentation/Contacts/CNChangeHistoryUpdateGroupEvent": {
      "abstract": [
        {
          "text": "An object that represents an updated group event.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CNChangeHistoryUpdateGroupEvent"
        }
      ],
      "identifier": "doc://com.apple.contacts/documentation/Contacts/CNChangeHistoryUpdateGroupEvent",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CNChangeHistoryUpdateGroupEvent"
        }
      ],
      "role": "symbol",
      "title": "CNChangeHistoryUpdateGroupEvent",
      "type": "topic",
      "url": "/documentation/contacts/cnchangehistoryupdategroupevent"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)NSCoding": {
      "abstract": [
        {
          "text": "A protocol that enables an object to be encoded and decoded for archiving and distribution.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "protocol "
        },
        {
          "kind": "identifier",
          "text": "NSCoding"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSCoding",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSCoding",
      "type": "topic",
      "url": "/documentation/foundation/nscoding"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)NSCopying": {
      "abstract": [
        {
          "text": "A protocol that objects adopt to provide functional copies of themselves.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "protocol "
        },
        {
          "kind": "identifier",
          "text": "NSCopying"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSCopying",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSCopying",
      "type": "topic",
      "url": "/documentation/foundation/nscopying"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)NSObject": {
      "abstract": [
        {
          "text": "The group of methods that are fundamental to all Objective-C objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "protocol "
        },
        {
          "kind": "identifier",
          "text": "NSObjectProtocol"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSObject",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSObjectProtocol",
      "type": "topic",
      "url": "/documentation/objectivec/nsobjectprotocol"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)NSSecureCoding": {
      "abstract": [
        {
          "text": "A protocol that enables encoding and decoding in a manner that is robust against object substitution attacks.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "protocol "
        },
        {
          "kind": "identifier",
          "text": "NSSecureCoding"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSSecureCoding",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSSecureCoding",
      "type": "topic",
      "url": "/documentation/foundation/nssecurecoding"
    },
    "doc://com.externally.resolved.symbol/s:SH": {
      "abstract": [
        {
          "text": "A type that can be hashed into a `Hasher` to produce an integer hash value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Hashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SQ",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SH",
      "kind": "symbol",
      "role": "symbol",
      "title": "Hashable",
      "type": "topic",
      "url": "/documentation/Swift/Hashable"
    },
    "doc://com.externally.resolved.symbol/s:SQ": {
      "abstract": [
        {
          "text": "A type that can be compared for value equality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SQ",
      "kind": "symbol",
      "role": "symbol",
      "title": "Equatable",
      "type": "topic",
      "url": "/documentation/Swift/Equatable"
    },
    "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP": {
      "abstract": [
        {
          "text": "A type with a customized textual representation.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CustomStringConvertible"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CustomStringConvertible",
      "type": "topic",
      "url": "/documentation/Swift/CustomStringConvertible"
    },
    "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP": {
      "abstract": [
        {
          "text": "A type with a customized textual representation suitable for debugging purposes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CustomDebugStringConvertible"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CustomDebugStringConvertible",
      "type": "topic",
      "url": "/documentation/Swift/CustomDebugStringConvertible"
    },
    "doc://com.externally.resolved.symbol/s:s7CVarArgP": {
      "abstract": [
        {
          "text": "A type whose instances can be encoded, and appropriately passed, as elements of a C `va_list`.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CVarArg"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s7CVarArgP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CVarArg",
      "type": "topic",
      "url": "/documentation/Swift/CVarArg"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.apple.contacts/documentation/Contacts/CNChangeHistoryEvent"
      ],
      "kind": "relationships",
      "title": "Inherits From",
      "type": "inheritsFrom"
    },
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:s7CVarArgP",
        "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP",
        "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP",
        "doc://com.externally.resolved.symbol/s:SQ",
        "doc://com.externally.resolved.symbol/s:SH",
        "doc://com.externally.resolved.symbol/c:objc(pl)NSCoding",
        "doc://com.externally.resolved.symbol/c:objc(pl)NSCopying",
        "doc://com.externally.resolved.symbol/c:objc(pl)NSObject",
        "doc://com.externally.resolved.symbol/c:objc(pl)NSSecureCoding"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Change-history-data",
      "generated": true,
      "identifiers": [
        "doc://com.apple.contacts/documentation/Contacts/CNChangeHistoryAddContactEvent",
        "doc://com.apple.contacts/documentation/Contacts/CNChangeHistoryAddGroupEvent",
        "doc://com.apple.contacts/documentation/Contacts/CNChangeHistoryAddMemberToGroupEvent",
        "doc://com.apple.contacts/documentation/Contacts/CNChangeHistoryAddSubgroupToGroupEvent",
        "doc://com.apple.contacts/documentation/Contacts/CNChangeHistoryDeleteContactEvent",
        "doc://com.apple.contacts/documentation/Contacts/CNChangeHistoryDeleteGroupEvent",
        "doc://com.apple.contacts/documentation/Contacts/CNChangeHistoryDropEverythingEvent",
        "doc://com.apple.contacts/documentation/Contacts/CNChangeHistoryEvent",
        "doc://com.apple.contacts/documentation/Contacts/CNChangeHistoryFetchRequest",
        "doc://com.apple.contacts/documentation/Contacts/CNChangeHistoryRemoveMemberFromGroupEvent",
        "doc://com.apple.contacts/documentation/Contacts/CNChangeHistoryUpdateContactEvent",
        "doc://com.apple.contacts/documentation/Contacts/CNChangeHistoryUpdateGroupEvent",
        "doc://com.apple.contacts/documentation/Contacts/CNChangeHistoryEventVisitor"
      ],
      "title": "Change history data"
    }
  ],
  "topicSections": [
    {
      "anchor": "Getting-event-details",
      "identifiers": [
        "doc://com.apple.contacts/documentation/Contacts/CNChangeHistoryRemoveSubgroupFromGroupEvent/group",
        "doc://com.apple.contacts/documentation/Contacts/CNChangeHistoryRemoveSubgroupFromGroupEvent/subgroup"
      ],
      "title": "Getting event details"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.1",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.15",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "6.0",
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Class"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "CNChangeHistoryRemoveSubgroupFromGroupEvent"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "class"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CNChangeHistoryRemoveSubgroupFromGroupEvent"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CNChangeHistoryRemoveSubgroupFromGroupEvent"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.contacts/documentation/Contacts"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Getting-event-details",
              "identifiers": [
                "doc://com.apple.contacts/documentation/Contacts/CNChangeHistoryRemoveSubgroupFromGroupEvent/group",
                "doc://com.apple.contacts/documentation/Contacts/CNChangeHistoryRemoveSubgroupFromGroupEvent/subgroup"
              ],
              "title": "Getting event details"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": [
            {
              "identifiers": [
                "doc://com.apple.contacts/documentation/Contacts/CNChangeHistoryEvent"
              ],
              "kind": "relationships",
              "title": "Inherits From",
              "type": "inheritsFrom"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Change-history-data",
              "generated": true,
              "identifiers": [
                "doc://com.apple.contacts/documentation/Contacts/CNChangeHistoryAddContactEvent",
                "doc://com.apple.contacts/documentation/Contacts/CNChangeHistoryAddGroupEvent",
                "doc://com.apple.contacts/documentation/Contacts/CNChangeHistoryAddMemberToGroupEvent",
                "doc://com.apple.contacts/documentation/Contacts/CNChangeHistoryAddSubgroupToGroupEvent",
                "doc://com.apple.contacts/documentation/Contacts/CNChangeHistoryDeleteContactEvent",
                "doc://com.apple.contacts/documentation/Contacts/CNChangeHistoryDeleteGroupEvent",
                "doc://com.apple.contacts/documentation/Contacts/CNChangeHistoryDropEverythingEvent",
                "doc://com.apple.contacts/documentation/Contacts/CNChangeHistoryEvent",
                "doc://com.apple.contacts/documentation/Contacts/CNChangeHistoryFetchRequest",
                "doc://com.apple.contacts/documentation/Contacts/CNChangeHistoryRemoveMemberFromGroupEvent",
                "doc://com.apple.contacts/documentation/Contacts/CNChangeHistoryUpdateContactEvent",
                "doc://com.apple.contacts/documentation/Contacts/CNChangeHistoryUpdateGroupEvent",
                "doc://com.apple.contacts/documentation/Contacts/CNChangeHistoryEventVisitor"
              ],
              "title": "Change history data"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "@interface"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "CNChangeHistoryRemoveSubgroupFromGroupEvent"
                  },
                  {
                    "kind": "text",
                    "text": " : "
                  },
                  {
                    "identifier": "doc://com.apple.contacts/documentation/Contacts/CNChangeHistoryEvent",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(cs)CNChangeHistoryEvent",
                    "text": "CNChangeHistoryEvent"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.contacts~1documentation~1Contacts~1CNChangeHistoryRemoveMemberFromGroupEvent/title",
          "value": "CNChangeHistoryRemoveMemberFromGroupEvent"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.contacts~1documentation~1Contacts~1CNChangeHistoryRemoveMemberFromGroupEvent/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CNChangeHistoryRemoveMemberFromGroupEvent"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.contacts~1documentation~1Contacts~1CNChangeHistoryRemoveMemberFromGroupEvent/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CNChangeHistoryRemoveMemberFromGroupEvent"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.contacts~1documentation~1Contacts~1CNChangeHistoryAddContactEvent/title",
          "value": "CNChangeHistoryAddContactEvent"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.contacts~1documentation~1Contacts~1CNChangeHistoryAddContactEvent/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CNChangeHistoryAddContactEvent"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.contacts~1documentation~1Contacts~1CNChangeHistoryAddContactEvent/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CNChangeHistoryAddContactEvent"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.contacts~1documentation~1Contacts~1CNChangeHistoryRemoveSubgroupFromGroupEvent/title",
          "value": "CNChangeHistoryRemoveSubgroupFromGroupEvent"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.contacts~1documentation~1Contacts~1CNChangeHistoryRemoveSubgroupFromGroupEvent/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CNChangeHistoryRemoveSubgroupFromGroupEvent"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.contacts~1documentation~1Contacts~1CNChangeHistoryRemoveSubgroupFromGroupEvent/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CNChangeHistoryRemoveSubgroupFromGroupEvent"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.contacts~1documentation~1Contacts~1CNChangeHistoryDeleteGroupEvent/title",
          "value": "CNChangeHistoryDeleteGroupEvent"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.contacts~1documentation~1Contacts~1CNChangeHistoryDeleteGroupEvent/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CNChangeHistoryDeleteGroupEvent"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.contacts~1documentation~1Contacts~1CNChangeHistoryDeleteGroupEvent/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CNChangeHistoryDeleteGroupEvent"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.contacts~1documentation~1Contacts~1CNChangeHistoryFetchRequest/title",
          "value": "CNChangeHistoryFetchRequest"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.contacts~1documentation~1Contacts~1CNChangeHistoryFetchRequest/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CNChangeHistoryFetchRequest"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.contacts~1documentation~1Contacts~1CNChangeHistoryFetchRequest/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CNChangeHistoryFetchRequest"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.contacts~1documentation~1Contacts~1CNChangeHistoryDropEverythingEvent/title",
          "value": "CNChangeHistoryDropEverythingEvent"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.contacts~1documentation~1Contacts~1CNChangeHistoryDropEverythingEvent/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CNChangeHistoryDropEverythingEvent"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.contacts~1documentation~1Contacts~1CNChangeHistoryDropEverythingEvent/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CNChangeHistoryDropEverythingEvent"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.contacts~1documentation~1Contacts~1CNChangeHistoryDeleteContactEvent/title",
          "value": "CNChangeHistoryDeleteContactEvent"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.contacts~1documentation~1Contacts~1CNChangeHistoryDeleteContactEvent/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CNChangeHistoryDeleteContactEvent"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.contacts~1documentation~1Contacts~1CNChangeHistoryDeleteContactEvent/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CNChangeHistoryDeleteContactEvent"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:objc(pl)NSObject/title",
          "value": "NSObject"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.contacts~1documentation~1Contacts~1CNChangeHistoryRemoveSubgroupFromGroupEvent~1group/title",
          "value": "group"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.contacts~1documentation~1Contacts~1CNChangeHistoryRemoveSubgroupFromGroupEvent~1group/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "group"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.contacts~1documentation~1Contacts~1CNChangeHistoryAddMemberToGroupEvent/title",
          "value": "CNChangeHistoryAddMemberToGroupEvent"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.contacts~1documentation~1Contacts~1CNChangeHistoryAddMemberToGroupEvent/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CNChangeHistoryAddMemberToGroupEvent"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.contacts~1documentation~1Contacts~1CNChangeHistoryAddMemberToGroupEvent/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CNChangeHistoryAddMemberToGroupEvent"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.contacts~1documentation~1Contacts~1CNChangeHistoryAddSubgroupToGroupEvent/title",
          "value": "CNChangeHistoryAddSubgroupToGroupEvent"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.contacts~1documentation~1Contacts~1CNChangeHistoryAddSubgroupToGroupEvent/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CNChangeHistoryAddSubgroupToGroupEvent"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.contacts~1documentation~1Contacts~1CNChangeHistoryAddSubgroupToGroupEvent/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CNChangeHistoryAddSubgroupToGroupEvent"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.contacts~1documentation~1Contacts~1CNChangeHistoryAddGroupEvent/title",
          "value": "CNChangeHistoryAddGroupEvent"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.contacts~1documentation~1Contacts~1CNChangeHistoryAddGroupEvent/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CNChangeHistoryAddGroupEvent"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.contacts~1documentation~1Contacts~1CNChangeHistoryAddGroupEvent/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CNChangeHistoryAddGroupEvent"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.contacts~1documentation~1Contacts~1CNChangeHistoryUpdateGroupEvent/title",
          "value": "CNChangeHistoryUpdateGroupEvent"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.contacts~1documentation~1Contacts~1CNChangeHistoryUpdateGroupEvent/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CNChangeHistoryUpdateGroupEvent"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.contacts~1documentation~1Contacts~1CNChangeHistoryUpdateGroupEvent/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CNChangeHistoryUpdateGroupEvent"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.contacts~1documentation~1Contacts~1CNChangeHistoryUpdateContactEvent/title",
          "value": "CNChangeHistoryUpdateContactEvent"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.contacts~1documentation~1Contacts~1CNChangeHistoryUpdateContactEvent/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CNChangeHistoryUpdateContactEvent"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.contacts~1documentation~1Contacts~1CNChangeHistoryUpdateContactEvent/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CNChangeHistoryUpdateContactEvent"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.contacts~1documentation~1Contacts~1CNChangeHistoryRemoveSubgroupFromGroupEvent~1subgroup/title",
          "value": "subgroup"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.contacts~1documentation~1Contacts~1CNChangeHistoryRemoveSubgroupFromGroupEvent~1subgroup/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "subgroup"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.contacts~1documentation~1Contacts~1CNChangeHistoryEvent/title",
          "value": "CNChangeHistoryEvent"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.contacts~1documentation~1Contacts~1CNChangeHistoryEvent/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CNChangeHistoryEvent"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.contacts~1documentation~1Contacts~1CNChangeHistoryEvent/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CNChangeHistoryEvent"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.contacts~1documentation~1Contacts~1CNChangeHistoryEventVisitor/title",
          "value": "CNChangeHistoryEventVisitor"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.contacts~1documentation~1Contacts~1CNChangeHistoryEventVisitor/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CNChangeHistoryEventVisitor"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.contacts~1documentation~1Contacts~1CNChangeHistoryEventVisitor/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CNChangeHistoryEventVisitor"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/contacts/cnchangehistoryremovesubgroupfromgroupevent"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/contacts/cnchangehistoryremovesubgroupfromgroupevent"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
