{
  "abstract": [
    {
      "text": "An interface for receiving notice of changes to contacts and groups.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.contacts/documentation/Contacts"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.contacts/documentation/Contacts/CNChangeHistoryEventVisitor"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(pl)CNChangeHistoryEventVisitor",
    "fragments": [
      {
        "kind": "keyword",
        "text": "protocol"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "CNChangeHistoryEventVisitor"
      }
    ],
    "modules": [
      {
        "name": "Contacts"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "CNChangeHistoryEventVisitor"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.1",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.15",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "6.0",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Protocol",
    "symbolKind": "protocol",
    "title": "CNChangeHistoryEventVisitor"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "protocol"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "CNChangeHistoryEventVisitor"
            },
            {
              "kind": "text",
              "text": " : "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSObject",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(pl)NSObject",
              "text": "NSObjectProtocol"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Implement this protocol to receive events that describe when a user adds, updates, or deletes contacts or groups outside your app.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.contacts/documentation/Contacts": {
      "abstract": [
        {
          "text": "Access the user’s contacts, and format and localize contact information.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.contacts/documentation/Contacts",
      "kind": "symbol",
      "role": "collection",
      "title": "Contacts",
      "type": "topic",
      "url": "/documentation/contacts"
    },
    "doc://com.apple.contacts/documentation/Contacts/CNChangeHistoryAddContactEvent": {
      "abstract": [
        {
          "text": "An object that represents a user adding a contact.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CNChangeHistoryAddContactEvent"
        }
      ],
      "identifier": "doc://com.apple.contacts/documentation/Contacts/CNChangeHistoryAddContactEvent",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CNChangeHistoryAddContactEvent"
        }
      ],
      "role": "symbol",
      "title": "CNChangeHistoryAddContactEvent",
      "type": "topic",
      "url": "/documentation/contacts/cnchangehistoryaddcontactevent"
    },
    "doc://com.apple.contacts/documentation/Contacts/CNChangeHistoryAddGroupEvent": {
      "abstract": [
        {
          "text": "An object that represents a user adding a group.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CNChangeHistoryAddGroupEvent"
        }
      ],
      "identifier": "doc://com.apple.contacts/documentation/Contacts/CNChangeHistoryAddGroupEvent",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CNChangeHistoryAddGroupEvent"
        }
      ],
      "role": "symbol",
      "title": "CNChangeHistoryAddGroupEvent",
      "type": "topic",
      "url": "/documentation/contacts/cnchangehistoryaddgroupevent"
    },
    "doc://com.apple.contacts/documentation/Contacts/CNChangeHistoryAddMemberToGroupEvent": {
      "abstract": [
        {
          "text": "An object that represents a user adding a contact to a group.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CNChangeHistoryAddMemberToGroupEvent"
        }
      ],
      "identifier": "doc://com.apple.contacts/documentation/Contacts/CNChangeHistoryAddMemberToGroupEvent",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CNChangeHistoryAddMemberToGroupEvent"
        }
      ],
      "role": "symbol",
      "title": "CNChangeHistoryAddMemberToGroupEvent",
      "type": "topic",
      "url": "/documentation/contacts/cnchangehistoryaddmembertogroupevent"
    },
    "doc://com.apple.contacts/documentation/Contacts/CNChangeHistoryAddSubgroupToGroupEvent": {
      "abstract": [
        {
          "text": "An object that represents a user adding a subgroup to a group.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CNChangeHistoryAddSubgroupToGroupEvent"
        }
      ],
      "identifier": "doc://com.apple.contacts/documentation/Contacts/CNChangeHistoryAddSubgroupToGroupEvent",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CNChangeHistoryAddSubgroupToGroupEvent"
        }
      ],
      "role": "symbol",
      "title": "CNChangeHistoryAddSubgroupToGroupEvent",
      "type": "topic",
      "url": "/documentation/contacts/cnchangehistoryaddsubgrouptogroupevent"
    },
    "doc://com.apple.contacts/documentation/Contacts/CNChangeHistoryDeleteContactEvent": {
      "abstract": [
        {
          "text": "An object that represents a user deleting a contact.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CNChangeHistoryDeleteContactEvent"
        }
      ],
      "identifier": "doc://com.apple.contacts/documentation/Contacts/CNChangeHistoryDeleteContactEvent",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CNChangeHistoryDeleteContactEvent"
        }
      ],
      "role": "symbol",
      "title": "CNChangeHistoryDeleteContactEvent",
      "type": "topic",
      "url": "/documentation/contacts/cnchangehistorydeletecontactevent"
    },
    "doc://com.apple.contacts/documentation/Contacts/CNChangeHistoryDeleteGroupEvent": {
      "abstract": [
        {
          "text": "An object that represents a user deleting a group.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CNChangeHistoryDeleteGroupEvent"
        }
      ],
      "identifier": "doc://com.apple.contacts/documentation/Contacts/CNChangeHistoryDeleteGroupEvent",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CNChangeHistoryDeleteGroupEvent"
        }
      ],
      "role": "symbol",
      "title": "CNChangeHistoryDeleteGroupEvent",
      "type": "topic",
      "url": "/documentation/contacts/cnchangehistorydeletegroupevent"
    },
    "doc://com.apple.contacts/documentation/Contacts/CNChangeHistoryDropEverythingEvent": {
      "abstract": [
        {
          "text": "An object that indicates the delegate should drop all contacts and groups before handling change events.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CNChangeHistoryDropEverythingEvent"
        }
      ],
      "identifier": "doc://com.apple.contacts/documentation/Contacts/CNChangeHistoryDropEverythingEvent",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CNChangeHistoryDropEverythingEvent"
        }
      ],
      "role": "symbol",
      "title": "CNChangeHistoryDropEverythingEvent",
      "type": "topic",
      "url": "/documentation/contacts/cnchangehistorydropeverythingevent"
    },
    "doc://com.apple.contacts/documentation/Contacts/CNChangeHistoryEvent": {
      "abstract": [
        {
          "text": "An object that represents the user adding, updating, or deleting a contact or group.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CNChangeHistoryEvent"
        }
      ],
      "identifier": "doc://com.apple.contacts/documentation/Contacts/CNChangeHistoryEvent",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CNChangeHistoryEvent"
        }
      ],
      "role": "symbol",
      "title": "CNChangeHistoryEvent",
      "type": "topic",
      "url": "/documentation/contacts/cnchangehistoryevent"
    },
    "doc://com.apple.contacts/documentation/Contacts/CNChangeHistoryEventVisitor": {
      "abstract": [
        {
          "text": "An interface for receiving notice of changes to contacts and groups.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CNChangeHistoryEventVisitor"
        }
      ],
      "identifier": "doc://com.apple.contacts/documentation/Contacts/CNChangeHistoryEventVisitor",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CNChangeHistoryEventVisitor"
        }
      ],
      "role": "symbol",
      "title": "CNChangeHistoryEventVisitor",
      "type": "topic",
      "url": "/documentation/contacts/cnchangehistoryeventvisitor"
    },
    "doc://com.apple.contacts/documentation/Contacts/CNChangeHistoryEventVisitor/visit(_:)-1pf2a": {
      "abstract": [
        {
          "text": "Tells the delegate that the user updated a contact.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "visit"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)CNChangeHistoryUpdateContactEvent",
          "text": "CNChangeHistoryUpdateContactEvent"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.contacts/documentation/Contacts/CNChangeHistoryEventVisitor/visit(_:)-1pf2a",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "visitUpdateContactEvent:"
        }
      ],
      "required": true,
      "role": "symbol",
      "title": "visit(_:)",
      "type": "topic",
      "url": "/documentation/contacts/cnchangehistoryeventvisitor/visit(_:)-1pf2a"
    },
    "doc://com.apple.contacts/documentation/Contacts/CNChangeHistoryEventVisitor/visit(_:)-23p9h": {
      "abstract": [
        {
          "text": "Tells the delegate that the user updated a group.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "visit"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)CNChangeHistoryUpdateGroupEvent",
          "text": "CNChangeHistoryUpdateGroupEvent"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.contacts/documentation/Contacts/CNChangeHistoryEventVisitor/visit(_:)-23p9h",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "visitUpdateGroupEvent:"
        }
      ],
      "role": "symbol",
      "title": "visit(_:)",
      "type": "topic",
      "url": "/documentation/contacts/cnchangehistoryeventvisitor/visit(_:)-23p9h"
    },
    "doc://com.apple.contacts/documentation/Contacts/CNChangeHistoryEventVisitor/visit(_:)-2yhz3": {
      "abstract": [
        {
          "text": "Tells the delegate to drop all contacts and groups before handling more events.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "visit"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)CNChangeHistoryDropEverythingEvent",
          "text": "CNChangeHistoryDropEverythingEvent"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.contacts/documentation/Contacts/CNChangeHistoryEventVisitor/visit(_:)-2yhz3",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "visitDropEverythingEvent:"
        }
      ],
      "required": true,
      "role": "symbol",
      "title": "visit(_:)",
      "type": "topic",
      "url": "/documentation/contacts/cnchangehistoryeventvisitor/visit(_:)-2yhz3"
    },
    "doc://com.apple.contacts/documentation/Contacts/CNChangeHistoryEventVisitor/visit(_:)-82duo": {
      "abstract": [
        {
          "text": "Tells the delegate that the user deleted a group.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "visit"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)CNChangeHistoryDeleteGroupEvent",
          "text": "CNChangeHistoryDeleteGroupEvent"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.contacts/documentation/Contacts/CNChangeHistoryEventVisitor/visit(_:)-82duo",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "visitDeleteGroupEvent:"
        }
      ],
      "role": "symbol",
      "title": "visit(_:)",
      "type": "topic",
      "url": "/documentation/contacts/cnchangehistoryeventvisitor/visit(_:)-82duo"
    },
    "doc://com.apple.contacts/documentation/Contacts/CNChangeHistoryEventVisitor/visit(_:)-9w73y": {
      "abstract": [
        {
          "text": "Tells the delegate that the user added a contact.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "visit"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)CNChangeHistoryAddContactEvent",
          "text": "CNChangeHistoryAddContactEvent"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.contacts/documentation/Contacts/CNChangeHistoryEventVisitor/visit(_:)-9w73y",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "visitAddContactEvent:"
        }
      ],
      "required": true,
      "role": "symbol",
      "title": "visit(_:)",
      "type": "topic",
      "url": "/documentation/contacts/cnchangehistoryeventvisitor/visit(_:)-9w73y"
    },
    "doc://com.apple.contacts/documentation/Contacts/CNChangeHistoryEventVisitor/visit(_:)-ci4z": {
      "abstract": [
        {
          "text": "Tells the delegate that the user deleted a contact.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "visit"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)CNChangeHistoryDeleteContactEvent",
          "text": "CNChangeHistoryDeleteContactEvent"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.contacts/documentation/Contacts/CNChangeHistoryEventVisitor/visit(_:)-ci4z",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "visitDeleteContactEvent:"
        }
      ],
      "required": true,
      "role": "symbol",
      "title": "visit(_:)",
      "type": "topic",
      "url": "/documentation/contacts/cnchangehistoryeventvisitor/visit(_:)-ci4z"
    },
    "doc://com.apple.contacts/documentation/Contacts/CNChangeHistoryEventVisitor/visit(_:)-ve62": {
      "abstract": [
        {
          "text": "Tells the delegate that the user added a group.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "visit"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)CNChangeHistoryAddGroupEvent",
          "text": "CNChangeHistoryAddGroupEvent"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.contacts/documentation/Contacts/CNChangeHistoryEventVisitor/visit(_:)-ve62",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "visitAddGroupEvent:"
        }
      ],
      "role": "symbol",
      "title": "visit(_:)",
      "type": "topic",
      "url": "/documentation/contacts/cnchangehistoryeventvisitor/visit(_:)-ve62"
    },
    "doc://com.apple.contacts/documentation/Contacts/CNChangeHistoryEventVisitor/visitAddMember(_:)": {
      "abstract": [
        {
          "text": "Tells the delegate that the user added a contact to a group.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "visitAddMember"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)CNChangeHistoryAddMemberToGroupEvent",
          "text": "CNChangeHistoryAddMemberToGroupEvent"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.contacts/documentation/Contacts/CNChangeHistoryEventVisitor/visitAddMember(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "visitAddMemberToGroupEvent:"
        }
      ],
      "role": "symbol",
      "title": "visitAddMember(_:)",
      "type": "topic",
      "url": "/documentation/contacts/cnchangehistoryeventvisitor/visitaddmember(_:)"
    },
    "doc://com.apple.contacts/documentation/Contacts/CNChangeHistoryEventVisitor/visitAddSubgroup(_:)": {
      "abstract": [
        {
          "text": "Tells the delegate that the user added a subgroup to a group.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "visitAddSubgroup"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)CNChangeHistoryAddSubgroupToGroupEvent",
          "text": "CNChangeHistoryAddSubgroupToGroupEvent"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.contacts/documentation/Contacts/CNChangeHistoryEventVisitor/visitAddSubgroup(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "visitAddSubgroupToGroupEvent:"
        }
      ],
      "role": "symbol",
      "title": "visitAddSubgroup(_:)",
      "type": "topic",
      "url": "/documentation/contacts/cnchangehistoryeventvisitor/visitaddsubgroup(_:)"
    },
    "doc://com.apple.contacts/documentation/Contacts/CNChangeHistoryEventVisitor/visitRemoveMember(_:)": {
      "abstract": [
        {
          "text": "Tells the delegate that the user removed a contact from a group.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "visitRemoveMember"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)CNChangeHistoryRemoveMemberFromGroupEvent",
          "text": "CNChangeHistoryRemoveMemberFromGroupEvent"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.contacts/documentation/Contacts/CNChangeHistoryEventVisitor/visitRemoveMember(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "visitRemoveMemberFromGroupEvent:"
        }
      ],
      "role": "symbol",
      "title": "visitRemoveMember(_:)",
      "type": "topic",
      "url": "/documentation/contacts/cnchangehistoryeventvisitor/visitremovemember(_:)"
    },
    "doc://com.apple.contacts/documentation/Contacts/CNChangeHistoryEventVisitor/visitRemoveSubgroup(_:)": {
      "abstract": [
        {
          "text": "Tells the delegate that the user removed a subgroup from a group.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "visitRemoveSubgroup"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)CNChangeHistoryRemoveSubgroupFromGroupEvent",
          "text": "CNChangeHistoryRemoveSubgroupFromGroupEvent"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.contacts/documentation/Contacts/CNChangeHistoryEventVisitor/visitRemoveSubgroup(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "visitRemoveSubgroupFromGroupEvent:"
        }
      ],
      "role": "symbol",
      "title": "visitRemoveSubgroup(_:)",
      "type": "topic",
      "url": "/documentation/contacts/cnchangehistoryeventvisitor/visitremovesubgroup(_:)"
    },
    "doc://com.apple.contacts/documentation/Contacts/CNChangeHistoryFetchRequest": {
      "abstract": [
        {
          "text": "An object that specifies the criteria for fetching change history.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CNChangeHistoryFetchRequest"
        }
      ],
      "identifier": "doc://com.apple.contacts/documentation/Contacts/CNChangeHistoryFetchRequest",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CNChangeHistoryFetchRequest"
        }
      ],
      "role": "symbol",
      "title": "CNChangeHistoryFetchRequest",
      "type": "topic",
      "url": "/documentation/contacts/cnchangehistoryfetchrequest"
    },
    "doc://com.apple.contacts/documentation/Contacts/CNChangeHistoryRemoveMemberFromGroupEvent": {
      "abstract": [
        {
          "text": "An object that represents a user removing a contact from a group.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CNChangeHistoryRemoveMemberFromGroupEvent"
        }
      ],
      "identifier": "doc://com.apple.contacts/documentation/Contacts/CNChangeHistoryRemoveMemberFromGroupEvent",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CNChangeHistoryRemoveMemberFromGroupEvent"
        }
      ],
      "role": "symbol",
      "title": "CNChangeHistoryRemoveMemberFromGroupEvent",
      "type": "topic",
      "url": "/documentation/contacts/cnchangehistoryremovememberfromgroupevent"
    },
    "doc://com.apple.contacts/documentation/Contacts/CNChangeHistoryRemoveSubgroupFromGroupEvent": {
      "abstract": [
        {
          "text": "An object that represents a user removing a subgroup from a group.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CNChangeHistoryRemoveSubgroupFromGroupEvent"
        }
      ],
      "identifier": "doc://com.apple.contacts/documentation/Contacts/CNChangeHistoryRemoveSubgroupFromGroupEvent",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CNChangeHistoryRemoveSubgroupFromGroupEvent"
        }
      ],
      "role": "symbol",
      "title": "CNChangeHistoryRemoveSubgroupFromGroupEvent",
      "type": "topic",
      "url": "/documentation/contacts/cnchangehistoryremovesubgroupfromgroupevent"
    },
    "doc://com.apple.contacts/documentation/Contacts/CNChangeHistoryUpdateContactEvent": {
      "abstract": [
        {
          "text": "An object that represents a user updating a contact.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CNChangeHistoryUpdateContactEvent"
        }
      ],
      "identifier": "doc://com.apple.contacts/documentation/Contacts/CNChangeHistoryUpdateContactEvent",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CNChangeHistoryUpdateContactEvent"
        }
      ],
      "role": "symbol",
      "title": "CNChangeHistoryUpdateContactEvent",
      "type": "topic",
      "url": "/documentation/contacts/cnchangehistoryupdatecontactevent"
    },
    "doc://com.apple.contacts/documentation/Contacts/CNChangeHistoryUpdateGroupEvent": {
      "abstract": [
        {
          "text": "An object that represents an updated group event.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CNChangeHistoryUpdateGroupEvent"
        }
      ],
      "identifier": "doc://com.apple.contacts/documentation/Contacts/CNChangeHistoryUpdateGroupEvent",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CNChangeHistoryUpdateGroupEvent"
        }
      ],
      "role": "symbol",
      "title": "CNChangeHistoryUpdateGroupEvent",
      "type": "topic",
      "url": "/documentation/contacts/cnchangehistoryupdategroupevent"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)NSObject": {
      "abstract": [
        {
          "text": "The group of methods that are fundamental to all Objective-C objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "protocol "
        },
        {
          "kind": "identifier",
          "text": "NSObjectProtocol"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSObject",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSObjectProtocol",
      "type": "topic",
      "url": "/documentation/objectivec/nsobjectprotocol"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/c:objc(pl)NSObject"
      ],
      "kind": "relationships",
      "title": "Inherits From",
      "type": "inheritsFrom"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Change-history-data",
      "generated": true,
      "identifiers": [
        "doc://com.apple.contacts/documentation/Contacts/CNChangeHistoryAddContactEvent",
        "doc://com.apple.contacts/documentation/Contacts/CNChangeHistoryAddGroupEvent",
        "doc://com.apple.contacts/documentation/Contacts/CNChangeHistoryAddMemberToGroupEvent",
        "doc://com.apple.contacts/documentation/Contacts/CNChangeHistoryAddSubgroupToGroupEvent",
        "doc://com.apple.contacts/documentation/Contacts/CNChangeHistoryDeleteContactEvent",
        "doc://com.apple.contacts/documentation/Contacts/CNChangeHistoryDeleteGroupEvent",
        "doc://com.apple.contacts/documentation/Contacts/CNChangeHistoryDropEverythingEvent",
        "doc://com.apple.contacts/documentation/Contacts/CNChangeHistoryEvent",
        "doc://com.apple.contacts/documentation/Contacts/CNChangeHistoryFetchRequest",
        "doc://com.apple.contacts/documentation/Contacts/CNChangeHistoryRemoveMemberFromGroupEvent",
        "doc://com.apple.contacts/documentation/Contacts/CNChangeHistoryRemoveSubgroupFromGroupEvent",
        "doc://com.apple.contacts/documentation/Contacts/CNChangeHistoryUpdateContactEvent",
        "doc://com.apple.contacts/documentation/Contacts/CNChangeHistoryUpdateGroupEvent"
      ],
      "title": "Change history data"
    }
  ],
  "topicSections": [
    {
      "anchor": "Updating-contacts",
      "identifiers": [
        "doc://com.apple.contacts/documentation/Contacts/CNChangeHistoryEventVisitor/visit(_:)-9w73y",
        "doc://com.apple.contacts/documentation/Contacts/CNChangeHistoryEventVisitor/visit(_:)-1pf2a",
        "doc://com.apple.contacts/documentation/Contacts/CNChangeHistoryEventVisitor/visit(_:)-ci4z"
      ],
      "title": "Updating contacts"
    },
    {
      "anchor": "Updating-groups",
      "identifiers": [
        "doc://com.apple.contacts/documentation/Contacts/CNChangeHistoryEventVisitor/visit(_:)-ve62",
        "doc://com.apple.contacts/documentation/Contacts/CNChangeHistoryEventVisitor/visit(_:)-23p9h",
        "doc://com.apple.contacts/documentation/Contacts/CNChangeHistoryEventVisitor/visit(_:)-82duo"
      ],
      "title": "Updating groups"
    },
    {
      "anchor": "Updating-subgroups",
      "identifiers": [
        "doc://com.apple.contacts/documentation/Contacts/CNChangeHistoryEventVisitor/visitAddSubgroup(_:)",
        "doc://com.apple.contacts/documentation/Contacts/CNChangeHistoryEventVisitor/visitRemoveSubgroup(_:)"
      ],
      "title": "Updating subgroups"
    },
    {
      "anchor": "Updating-contacts-in-groups",
      "identifiers": [
        "doc://com.apple.contacts/documentation/Contacts/CNChangeHistoryEventVisitor/visitAddMember(_:)",
        "doc://com.apple.contacts/documentation/Contacts/CNChangeHistoryEventVisitor/visitRemoveMember(_:)"
      ],
      "title": "Updating contacts in groups"
    },
    {
      "anchor": "Resetting-synced-data",
      "identifiers": [
        "doc://com.apple.contacts/documentation/Contacts/CNChangeHistoryEventVisitor/visit(_:)-2yhz3"
      ],
      "title": "Resetting synced data"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.1",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.15",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "6.0",
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Protocol"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "CNChangeHistoryEventVisitor"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "protocol"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CNChangeHistoryEventVisitor"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CNChangeHistoryEventVisitor"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.contacts/documentation/Contacts"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Updating-contacts",
              "identifiers": [
                "doc://com.apple.contacts/documentation/Contacts/CNChangeHistoryEventVisitor/visit(_:)-9w73y",
                "doc://com.apple.contacts/documentation/Contacts/CNChangeHistoryEventVisitor/visit(_:)-1pf2a",
                "doc://com.apple.contacts/documentation/Contacts/CNChangeHistoryEventVisitor/visit(_:)-ci4z"
              ],
              "title": "Updating contacts"
            },
            {
              "anchor": "Updating-groups",
              "identifiers": [
                "doc://com.apple.contacts/documentation/Contacts/CNChangeHistoryEventVisitor/visit(_:)-ve62",
                "doc://com.apple.contacts/documentation/Contacts/CNChangeHistoryEventVisitor/visit(_:)-23p9h",
                "doc://com.apple.contacts/documentation/Contacts/CNChangeHistoryEventVisitor/visit(_:)-82duo"
              ],
              "title": "Updating groups"
            },
            {
              "anchor": "Updating-subgroups",
              "identifiers": [
                "doc://com.apple.contacts/documentation/Contacts/CNChangeHistoryEventVisitor/visitAddSubgroup(_:)",
                "doc://com.apple.contacts/documentation/Contacts/CNChangeHistoryEventVisitor/visitRemoveSubgroup(_:)"
              ],
              "title": "Updating subgroups"
            },
            {
              "anchor": "Updating-contacts-in-groups",
              "identifiers": [
                "doc://com.apple.contacts/documentation/Contacts/CNChangeHistoryEventVisitor/visitAddMember(_:)",
                "doc://com.apple.contacts/documentation/Contacts/CNChangeHistoryEventVisitor/visitRemoveMember(_:)"
              ],
              "title": "Updating contacts in groups"
            },
            {
              "anchor": "Resetting-synced-data",
              "identifiers": [
                "doc://com.apple.contacts/documentation/Contacts/CNChangeHistoryEventVisitor/visit(_:)-2yhz3"
              ],
              "title": "Resetting synced data"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": [
            {
              "identifiers": [
                "doc://com.externally.resolved.symbol/c:objc(pl)NSObject"
              ],
              "kind": "relationships",
              "title": "Inherits From",
              "type": "inheritsFrom"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Change-history-data",
              "generated": true,
              "identifiers": [
                "doc://com.apple.contacts/documentation/Contacts/CNChangeHistoryAddContactEvent",
                "doc://com.apple.contacts/documentation/Contacts/CNChangeHistoryAddGroupEvent",
                "doc://com.apple.contacts/documentation/Contacts/CNChangeHistoryAddMemberToGroupEvent",
                "doc://com.apple.contacts/documentation/Contacts/CNChangeHistoryAddSubgroupToGroupEvent",
                "doc://com.apple.contacts/documentation/Contacts/CNChangeHistoryDeleteContactEvent",
                "doc://com.apple.contacts/documentation/Contacts/CNChangeHistoryDeleteGroupEvent",
                "doc://com.apple.contacts/documentation/Contacts/CNChangeHistoryDropEverythingEvent",
                "doc://com.apple.contacts/documentation/Contacts/CNChangeHistoryEvent",
                "doc://com.apple.contacts/documentation/Contacts/CNChangeHistoryFetchRequest",
                "doc://com.apple.contacts/documentation/Contacts/CNChangeHistoryRemoveMemberFromGroupEvent",
                "doc://com.apple.contacts/documentation/Contacts/CNChangeHistoryRemoveSubgroupFromGroupEvent",
                "doc://com.apple.contacts/documentation/Contacts/CNChangeHistoryUpdateContactEvent",
                "doc://com.apple.contacts/documentation/Contacts/CNChangeHistoryUpdateGroupEvent"
              ],
              "title": "Change history data"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "@protocol"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "CNChangeHistoryEventVisitor"
                  },
                  {
                    "kind": "text",
                    "text": " <"
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSObject",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(pl)NSObject",
                    "text": "NSObject"
                  },
                  {
                    "kind": "text",
                    "text": ">"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.contacts~1documentation~1Contacts~1CNChangeHistoryEventVisitor~1visit(_:)-82duo/title",
          "value": "visitDeleteGroupEvent:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.contacts~1documentation~1Contacts~1CNChangeHistoryEventVisitor~1visit(_:)-82duo/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "visitDeleteGroupEvent:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.contacts~1documentation~1Contacts~1CNChangeHistoryEventVisitor~1visit(_:)-1pf2a/title",
          "value": "visitUpdateContactEvent:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.contacts~1documentation~1Contacts~1CNChangeHistoryEventVisitor~1visit(_:)-1pf2a/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "visitUpdateContactEvent:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.contacts~1documentation~1Contacts~1CNChangeHistoryDeleteContactEvent/title",
          "value": "CNChangeHistoryDeleteContactEvent"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.contacts~1documentation~1Contacts~1CNChangeHistoryDeleteContactEvent/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CNChangeHistoryDeleteContactEvent"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.contacts~1documentation~1Contacts~1CNChangeHistoryDeleteContactEvent/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CNChangeHistoryDeleteContactEvent"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.contacts~1documentation~1Contacts~1CNChangeHistoryDropEverythingEvent/title",
          "value": "CNChangeHistoryDropEverythingEvent"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.contacts~1documentation~1Contacts~1CNChangeHistoryDropEverythingEvent/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CNChangeHistoryDropEverythingEvent"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.contacts~1documentation~1Contacts~1CNChangeHistoryDropEverythingEvent/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CNChangeHistoryDropEverythingEvent"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.contacts~1documentation~1Contacts~1CNChangeHistoryRemoveSubgroupFromGroupEvent/title",
          "value": "CNChangeHistoryRemoveSubgroupFromGroupEvent"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.contacts~1documentation~1Contacts~1CNChangeHistoryRemoveSubgroupFromGroupEvent/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CNChangeHistoryRemoveSubgroupFromGroupEvent"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.contacts~1documentation~1Contacts~1CNChangeHistoryRemoveSubgroupFromGroupEvent/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CNChangeHistoryRemoveSubgroupFromGroupEvent"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.contacts~1documentation~1Contacts~1CNChangeHistoryFetchRequest/title",
          "value": "CNChangeHistoryFetchRequest"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.contacts~1documentation~1Contacts~1CNChangeHistoryFetchRequest/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CNChangeHistoryFetchRequest"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.contacts~1documentation~1Contacts~1CNChangeHistoryFetchRequest/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CNChangeHistoryFetchRequest"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.contacts~1documentation~1Contacts~1CNChangeHistoryEventVisitor~1visit(_:)-2yhz3/title",
          "value": "visitDropEverythingEvent:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.contacts~1documentation~1Contacts~1CNChangeHistoryEventVisitor~1visit(_:)-2yhz3/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "visitDropEverythingEvent:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.contacts~1documentation~1Contacts~1CNChangeHistoryEventVisitor~1visitRemoveSubgroup(_:)/title",
          "value": "visitRemoveSubgroupFromGroupEvent:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.contacts~1documentation~1Contacts~1CNChangeHistoryEventVisitor~1visitRemoveSubgroup(_:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "visitRemoveSubgroupFromGroupEvent:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.contacts~1documentation~1Contacts~1CNChangeHistoryEventVisitor/title",
          "value": "CNChangeHistoryEventVisitor"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.contacts~1documentation~1Contacts~1CNChangeHistoryEventVisitor/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CNChangeHistoryEventVisitor"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.contacts~1documentation~1Contacts~1CNChangeHistoryEventVisitor/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CNChangeHistoryEventVisitor"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.contacts~1documentation~1Contacts~1CNChangeHistoryEventVisitor~1visit(_:)-23p9h/title",
          "value": "visitUpdateGroupEvent:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.contacts~1documentation~1Contacts~1CNChangeHistoryEventVisitor~1visit(_:)-23p9h/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "visitUpdateGroupEvent:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.contacts~1documentation~1Contacts~1CNChangeHistoryEvent/title",
          "value": "CNChangeHistoryEvent"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.contacts~1documentation~1Contacts~1CNChangeHistoryEvent/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CNChangeHistoryEvent"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.contacts~1documentation~1Contacts~1CNChangeHistoryEvent/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CNChangeHistoryEvent"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:objc(pl)NSObject/title",
          "value": "NSObject"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.contacts~1documentation~1Contacts~1CNChangeHistoryAddMemberToGroupEvent/title",
          "value": "CNChangeHistoryAddMemberToGroupEvent"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.contacts~1documentation~1Contacts~1CNChangeHistoryAddMemberToGroupEvent/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CNChangeHistoryAddMemberToGroupEvent"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.contacts~1documentation~1Contacts~1CNChangeHistoryAddMemberToGroupEvent/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CNChangeHistoryAddMemberToGroupEvent"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.contacts~1documentation~1Contacts~1CNChangeHistoryAddSubgroupToGroupEvent/title",
          "value": "CNChangeHistoryAddSubgroupToGroupEvent"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.contacts~1documentation~1Contacts~1CNChangeHistoryAddSubgroupToGroupEvent/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CNChangeHistoryAddSubgroupToGroupEvent"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.contacts~1documentation~1Contacts~1CNChangeHistoryAddSubgroupToGroupEvent/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CNChangeHistoryAddSubgroupToGroupEvent"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.contacts~1documentation~1Contacts~1CNChangeHistoryRemoveMemberFromGroupEvent/title",
          "value": "CNChangeHistoryRemoveMemberFromGroupEvent"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.contacts~1documentation~1Contacts~1CNChangeHistoryRemoveMemberFromGroupEvent/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CNChangeHistoryRemoveMemberFromGroupEvent"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.contacts~1documentation~1Contacts~1CNChangeHistoryRemoveMemberFromGroupEvent/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CNChangeHistoryRemoveMemberFromGroupEvent"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.contacts~1documentation~1Contacts~1CNChangeHistoryDeleteGroupEvent/title",
          "value": "CNChangeHistoryDeleteGroupEvent"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.contacts~1documentation~1Contacts~1CNChangeHistoryDeleteGroupEvent/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CNChangeHistoryDeleteGroupEvent"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.contacts~1documentation~1Contacts~1CNChangeHistoryDeleteGroupEvent/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CNChangeHistoryDeleteGroupEvent"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.contacts~1documentation~1Contacts~1CNChangeHistoryAddContactEvent/title",
          "value": "CNChangeHistoryAddContactEvent"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.contacts~1documentation~1Contacts~1CNChangeHistoryAddContactEvent/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CNChangeHistoryAddContactEvent"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.contacts~1documentation~1Contacts~1CNChangeHistoryAddContactEvent/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CNChangeHistoryAddContactEvent"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.contacts~1documentation~1Contacts~1CNChangeHistoryEventVisitor~1visit(_:)-9w73y/title",
          "value": "visitAddContactEvent:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.contacts~1documentation~1Contacts~1CNChangeHistoryEventVisitor~1visit(_:)-9w73y/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "visitAddContactEvent:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.contacts~1documentation~1Contacts~1CNChangeHistoryEventVisitor~1visitRemoveMember(_:)/title",
          "value": "visitRemoveMemberFromGroupEvent:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.contacts~1documentation~1Contacts~1CNChangeHistoryEventVisitor~1visitRemoveMember(_:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "visitRemoveMemberFromGroupEvent:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.contacts~1documentation~1Contacts~1CNChangeHistoryEventVisitor~1visit(_:)-ve62/title",
          "value": "visitAddGroupEvent:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.contacts~1documentation~1Contacts~1CNChangeHistoryEventVisitor~1visit(_:)-ve62/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "visitAddGroupEvent:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.contacts~1documentation~1Contacts~1CNChangeHistoryUpdateContactEvent/title",
          "value": "CNChangeHistoryUpdateContactEvent"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.contacts~1documentation~1Contacts~1CNChangeHistoryUpdateContactEvent/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CNChangeHistoryUpdateContactEvent"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.contacts~1documentation~1Contacts~1CNChangeHistoryUpdateContactEvent/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CNChangeHistoryUpdateContactEvent"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.contacts~1documentation~1Contacts~1CNChangeHistoryEventVisitor~1visitAddMember(_:)/title",
          "value": "visitAddMemberToGroupEvent:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.contacts~1documentation~1Contacts~1CNChangeHistoryEventVisitor~1visitAddMember(_:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "visitAddMemberToGroupEvent:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.contacts~1documentation~1Contacts~1CNChangeHistoryEventVisitor~1visit(_:)-ci4z/title",
          "value": "visitDeleteContactEvent:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.contacts~1documentation~1Contacts~1CNChangeHistoryEventVisitor~1visit(_:)-ci4z/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "visitDeleteContactEvent:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.contacts~1documentation~1Contacts~1CNChangeHistoryAddGroupEvent/title",
          "value": "CNChangeHistoryAddGroupEvent"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.contacts~1documentation~1Contacts~1CNChangeHistoryAddGroupEvent/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CNChangeHistoryAddGroupEvent"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.contacts~1documentation~1Contacts~1CNChangeHistoryAddGroupEvent/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CNChangeHistoryAddGroupEvent"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.contacts~1documentation~1Contacts~1CNChangeHistoryEventVisitor~1visitAddSubgroup(_:)/title",
          "value": "visitAddSubgroupToGroupEvent:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.contacts~1documentation~1Contacts~1CNChangeHistoryEventVisitor~1visitAddSubgroup(_:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "visitAddSubgroupToGroupEvent:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.contacts~1documentation~1Contacts~1CNChangeHistoryUpdateGroupEvent/title",
          "value": "CNChangeHistoryUpdateGroupEvent"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.contacts~1documentation~1Contacts~1CNChangeHistoryUpdateGroupEvent/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CNChangeHistoryUpdateGroupEvent"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.contacts~1documentation~1Contacts~1CNChangeHistoryUpdateGroupEvent/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CNChangeHistoryUpdateGroupEvent"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/contacts/cnchangehistoryeventvisitor"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/contacts/cnchangehistoryeventvisitor"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
