{
  "abstract": [
    {
      "text": "An object that you use to format contact information before displaying it to the user.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.contacts/documentation/Contacts"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.contacts/documentation/Contacts/CNContactFormatter"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(cs)CNContactFormatter",
    "fragments": [
      {
        "kind": "keyword",
        "text": "class"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "CNContactFormatter"
      }
    ],
    "modules": [
      {
        "name": "Contacts"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "CNContactFormatter"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "9.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "9.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.1",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.11",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "2.0",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Class",
    "symbolKind": "class",
    "title": "CNContactFormatter"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "class"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "CNContactFormatter"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "A ",
              "type": "text"
            },
            {
              "code": "CNContactFormatter",
              "type": "codeVoice"
            },
            {
              "text": " object handles international ordering and delimiting for the contact name components. When formatting many contacts, create an instance of this class and use the instance methods; otherwise use the class methods.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.contacts/documentation/Contacts": {
      "abstract": [
        {
          "text": "Access the user’s contacts, and format and localize contact information.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.contacts/documentation/Contacts",
      "kind": "symbol",
      "role": "collection",
      "title": "Contacts",
      "type": "topic",
      "url": "/documentation/contacts"
    },
    "doc://com.apple.contacts/documentation/Contacts/CNContactDisplayNameOrder": {
      "abstract": [
        {
          "text": "The formatting orders for contact names component.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CNContactDisplayNameOrder"
        }
      ],
      "identifier": "doc://com.apple.contacts/documentation/Contacts/CNContactDisplayNameOrder",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CNContactDisplayNameOrder"
        }
      ],
      "role": "symbol",
      "title": "CNContactDisplayNameOrder",
      "type": "topic",
      "url": "/documentation/contacts/cncontactdisplaynameorder"
    },
    "doc://com.apple.contacts/documentation/Contacts/CNContactFormatter": {
      "abstract": [
        {
          "text": "An object that you use to format contact information before displaying it to the user.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CNContactFormatter"
        }
      ],
      "identifier": "doc://com.apple.contacts/documentation/Contacts/CNContactFormatter",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CNContactFormatter"
        }
      ],
      "role": "symbol",
      "title": "CNContactFormatter",
      "type": "topic",
      "url": "/documentation/contacts/cncontactformatter"
    },
    "doc://com.apple.contacts/documentation/Contacts/CNContactFormatter/attributedString(from:defaultAttributes:)": {
      "abstract": [
        {
          "text": "Formats the contact name as an attributed string.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "attributedString"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "from"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)CNContact",
          "text": "CNContact"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "defaultAttributes"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s11AnyHashableV",
          "text": "AnyHashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "keyword",
          "text": "Any"
        },
        {
          "kind": "text",
          "text": "]?) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSAttributedString",
          "text": "NSAttributedString"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.contacts/documentation/Contacts/CNContactFormatter/attributedString(from:defaultAttributes:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "attributedStringFromContact:defaultAttributes:"
        }
      ],
      "role": "symbol",
      "title": "attributedString(from:defaultAttributes:)",
      "type": "topic",
      "url": "/documentation/contacts/cncontactformatter/attributedstring(from:defaultattributes:)"
    },
    "doc://com.apple.contacts/documentation/Contacts/CNContactFormatter/attributedString(from:style:defaultAttributes:)": {
      "abstract": [
        {
          "text": "Formats the contact name as an attributed string.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "attributedString"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "from"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)CNContact",
          "text": "CNContact"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "style"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@CNContactFormatterStyle",
          "text": "CNContactFormatterStyle"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "defaultAttributes"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s11AnyHashableV",
          "text": "AnyHashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "keyword",
          "text": "Any"
        },
        {
          "kind": "text",
          "text": "]?) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSAttributedString",
          "text": "NSAttributedString"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.contacts/documentation/Contacts/CNContactFormatter/attributedString(from:style:defaultAttributes:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "attributedStringFromContact:style:defaultAttributes:"
        }
      ],
      "role": "symbol",
      "title": "attributedString(from:style:defaultAttributes:)",
      "type": "topic",
      "url": "/documentation/contacts/cncontactformatter/attributedstring(from:style:defaultattributes:)"
    },
    "doc://com.apple.contacts/documentation/Contacts/CNContactFormatter/delimiter(for:)": {
      "abstract": [
        {
          "text": "Returns the delimiter to use between name components.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "delimiter"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "for"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)CNContact",
          "text": "CNContact"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.contacts/documentation/Contacts/CNContactFormatter/delimiter(for:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "delimiterForContact:"
        }
      ],
      "role": "symbol",
      "title": "delimiter(for:)",
      "type": "topic",
      "url": "/documentation/contacts/cncontactformatter/delimiter(for:)"
    },
    "doc://com.apple.contacts/documentation/Contacts/CNContactFormatter/descriptorForRequiredKeys(for:)": {
      "abstract": [
        {
          "text": "Returns the required key descriptor for the specified formatting style of the contact.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "descriptorForRequiredKeys"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "for"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@CNContactFormatterStyle",
          "text": "CNContactFormatterStyle"
        },
        {
          "kind": "text",
          "text": ") -> any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(pl)CNKeyDescriptor",
          "text": "CNKeyDescriptor"
        }
      ],
      "identifier": "doc://com.apple.contacts/documentation/Contacts/CNContactFormatter/descriptorForRequiredKeys(for:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "descriptorForRequiredKeysForStyle:"
        }
      ],
      "role": "symbol",
      "title": "descriptorForRequiredKeys(for:)",
      "type": "topic",
      "url": "/documentation/contacts/cncontactformatter/descriptorforrequiredkeys(for:)"
    },
    "doc://com.apple.contacts/documentation/Contacts/CNContactFormatter/descriptorForRequiredKeysForDelimiter": {
      "abstract": [
        {
          "text": "Returns the required key descriptor for the name delimiter.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "descriptorForRequiredKeysForDelimiter"
        },
        {
          "kind": "text",
          "text": ": any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(pl)CNKeyDescriptor",
          "text": "CNKeyDescriptor"
        }
      ],
      "identifier": "doc://com.apple.contacts/documentation/Contacts/CNContactFormatter/descriptorForRequiredKeysForDelimiter",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "descriptorForRequiredKeysForDelimiter"
        }
      ],
      "role": "symbol",
      "title": "descriptorForRequiredKeysForDelimiter",
      "type": "topic",
      "url": "/documentation/contacts/cncontactformatter/descriptorforrequiredkeysfordelimiter"
    },
    "doc://com.apple.contacts/documentation/Contacts/CNContactFormatter/descriptorForRequiredKeysForNameOrder": {
      "abstract": [
        {
          "text": "Returns the required key descriptor for the display name order.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "descriptorForRequiredKeysForNameOrder"
        },
        {
          "kind": "text",
          "text": ": any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(pl)CNKeyDescriptor",
          "text": "CNKeyDescriptor"
        }
      ],
      "identifier": "doc://com.apple.contacts/documentation/Contacts/CNContactFormatter/descriptorForRequiredKeysForNameOrder",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "descriptorForRequiredKeysForNameOrder"
        }
      ],
      "role": "symbol",
      "title": "descriptorForRequiredKeysForNameOrder",
      "type": "topic",
      "url": "/documentation/contacts/cncontactformatter/descriptorforrequiredkeysfornameorder"
    },
    "doc://com.apple.contacts/documentation/Contacts/CNContactFormatter/nameOrder(for:)": {
      "abstract": [
        {
          "text": "Returns the display name order.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "nameOrder"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "for"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)CNContact",
          "text": "CNContact"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@CNContactDisplayNameOrder",
          "text": "CNContactDisplayNameOrder"
        }
      ],
      "identifier": "doc://com.apple.contacts/documentation/Contacts/CNContactFormatter/nameOrder(for:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "nameOrderForContact:"
        }
      ],
      "role": "symbol",
      "title": "nameOrder(for:)",
      "type": "topic",
      "url": "/documentation/contacts/cncontactformatter/nameorder(for:)"
    },
    "doc://com.apple.contacts/documentation/Contacts/CNContactFormatter/string(from:)": {
      "abstract": [
        {
          "text": "Formats the contact name.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "string"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "from"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)CNContact",
          "text": "CNContact"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.contacts/documentation/Contacts/CNContactFormatter/string(from:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "stringFromContact:"
        }
      ],
      "role": "symbol",
      "title": "string(from:)",
      "type": "topic",
      "url": "/documentation/contacts/cncontactformatter/string(from:)"
    },
    "doc://com.apple.contacts/documentation/Contacts/CNContactFormatter/string(from:style:)": {
      "abstract": [
        {
          "text": "Returns the contact name, formatted with the specified formatter.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "string"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "from"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)CNContact",
          "text": "CNContact"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "style"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@CNContactFormatterStyle",
          "text": "CNContactFormatterStyle"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.contacts/documentation/Contacts/CNContactFormatter/string(from:style:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "stringFromContact:style:"
        }
      ],
      "role": "symbol",
      "title": "string(from:style:)",
      "type": "topic",
      "url": "/documentation/contacts/cncontactformatter/string(from:style:)"
    },
    "doc://com.apple.contacts/documentation/Contacts/CNContactFormatter/style": {
      "abstract": [
        {
          "text": "The formatting style for the contact name.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "style"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@CNContactFormatterStyle",
          "text": "CNContactFormatterStyle"
        }
      ],
      "identifier": "doc://com.apple.contacts/documentation/Contacts/CNContactFormatter/style",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "style"
        }
      ],
      "role": "symbol",
      "title": "style",
      "type": "topic",
      "url": "/documentation/contacts/cncontactformatter/style"
    },
    "doc://com.apple.contacts/documentation/Contacts/CNContactFormatterStyle": {
      "abstract": [
        {
          "text": "The formatting styles for contact names.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CNContactFormatterStyle"
        }
      ],
      "identifier": "doc://com.apple.contacts/documentation/Contacts/CNContactFormatterStyle",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CNContactFormatterStyle"
        }
      ],
      "role": "symbol",
      "title": "CNContactFormatterStyle",
      "type": "topic",
      "url": "/documentation/contacts/cncontactformatterstyle"
    },
    "doc://com.apple.contacts/documentation/Contacts/CNContactVCardSerialization": {
      "abstract": [
        {
          "text": "An object you use to convert to and from a vCard representation of the user’s contacts.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CNContactVCardSerialization"
        }
      ],
      "identifier": "doc://com.apple.contacts/documentation/Contacts/CNContactVCardSerialization",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CNContactVCardSerialization"
        }
      ],
      "role": "symbol",
      "title": "CNContactVCardSerialization",
      "type": "topic",
      "url": "/documentation/contacts/cncontactvcardserialization"
    },
    "doc://com.apple.contacts/documentation/Contacts/CNContactsUserDefaults": {
      "abstract": [
        {
          "text": "An object that defines the default options to use when displaying contacts.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CNContactsUserDefaults"
        }
      ],
      "identifier": "doc://com.apple.contacts/documentation/Contacts/CNContactsUserDefaults",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CNContactsUserDefaults"
        }
      ],
      "role": "symbol",
      "title": "CNContactsUserDefaults",
      "type": "topic",
      "url": "/documentation/contacts/cncontactsuserdefaults"
    },
    "doc://com.apple.contacts/documentation/Contacts/CNPostalAddressFormatter": {
      "abstract": [
        {
          "text": "An object that you use to format a contact’s postal addresses.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CNPostalAddressFormatter"
        }
      ],
      "identifier": "doc://com.apple.contacts/documentation/Contacts/CNPostalAddressFormatter",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CNPostalAddressFormatter"
        }
      ],
      "role": "symbol",
      "title": "CNPostalAddressFormatter",
      "type": "topic",
      "url": "/documentation/contacts/cnpostaladdressformatter"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.externally.resolved.symbol/c:objc(cs)NSFormatter": {
      "abstract": [
        {
          "text": "An abstract class that declares an interface for objects that create, interpret, and validate the textual representation of values.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "class "
        },
        {
          "kind": "identifier",
          "text": "Formatter"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSFormatter",
      "kind": "symbol",
      "role": "symbol",
      "title": "Formatter",
      "type": "topic",
      "url": "/documentation/foundation/formatter"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)NSCoding": {
      "abstract": [
        {
          "text": "A protocol that enables an object to be encoded and decoded for archiving and distribution.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "protocol "
        },
        {
          "kind": "identifier",
          "text": "NSCoding"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSCoding",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSCoding",
      "type": "topic",
      "url": "/documentation/foundation/nscoding"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)NSCopying": {
      "abstract": [
        {
          "text": "A protocol that objects adopt to provide functional copies of themselves.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "protocol "
        },
        {
          "kind": "identifier",
          "text": "NSCopying"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSCopying",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSCopying",
      "type": "topic",
      "url": "/documentation/foundation/nscopying"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)NSObject": {
      "abstract": [
        {
          "text": "The group of methods that are fundamental to all Objective-C objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "protocol "
        },
        {
          "kind": "identifier",
          "text": "NSObjectProtocol"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSObject",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSObjectProtocol",
      "type": "topic",
      "url": "/documentation/objectivec/nsobjectprotocol"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)NSSecureCoding": {
      "abstract": [
        {
          "text": "A protocol that enables encoding and decoding in a manner that is robust against object substitution attacks.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "protocol "
        },
        {
          "kind": "identifier",
          "text": "NSSecureCoding"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSSecureCoding",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSSecureCoding",
      "type": "topic",
      "url": "/documentation/foundation/nssecurecoding"
    },
    "doc://com.externally.resolved.symbol/s:SH": {
      "abstract": [
        {
          "text": "A type that can be hashed into a `Hasher` to produce an integer hash value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Hashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SQ",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SH",
      "kind": "symbol",
      "role": "symbol",
      "title": "Hashable",
      "type": "topic",
      "url": "/documentation/Swift/Hashable"
    },
    "doc://com.externally.resolved.symbol/s:SQ": {
      "abstract": [
        {
          "text": "A type that can be compared for value equality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SQ",
      "kind": "symbol",
      "role": "symbol",
      "title": "Equatable",
      "type": "topic",
      "url": "/documentation/Swift/Equatable"
    },
    "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP": {
      "abstract": [
        {
          "text": "A type with a customized textual representation.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CustomStringConvertible"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CustomStringConvertible",
      "type": "topic",
      "url": "/documentation/Swift/CustomStringConvertible"
    },
    "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP": {
      "abstract": [
        {
          "text": "A type with a customized textual representation suitable for debugging purposes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CustomDebugStringConvertible"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CustomDebugStringConvertible",
      "type": "topic",
      "url": "/documentation/Swift/CustomDebugStringConvertible"
    },
    "doc://com.externally.resolved.symbol/s:s7CVarArgP": {
      "abstract": [
        {
          "text": "A type whose instances can be encoded, and appropriately passed, as elements of a C `va_list`.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CVarArg"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s7CVarArgP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CVarArg",
      "type": "topic",
      "url": "/documentation/Swift/CVarArg"
    },
    "doc://com.externally.resolved.symbol/s:s8SendableP": {
      "abstract": [
        {
          "text": "A thread-safe type whose values can be shared across arbitrary concurrent contexts without introducing a risk of data races.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Sendable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s8SendableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "Sendable",
      "type": "topic",
      "url": "/documentation/Swift/Sendable"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/c:objc(cs)NSFormatter"
      ],
      "kind": "relationships",
      "title": "Inherits From",
      "type": "inheritsFrom"
    },
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:s7CVarArgP",
        "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP",
        "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP",
        "doc://com.externally.resolved.symbol/s:SQ",
        "doc://com.externally.resolved.symbol/s:SH",
        "doc://com.externally.resolved.symbol/c:objc(pl)NSCoding",
        "doc://com.externally.resolved.symbol/c:objc(pl)NSCopying",
        "doc://com.externally.resolved.symbol/c:objc(pl)NSObject",
        "doc://com.externally.resolved.symbol/c:objc(pl)NSSecureCoding",
        "doc://com.externally.resolved.symbol/s:s8SendableP"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Formatters",
      "generated": true,
      "identifiers": [
        "doc://com.apple.contacts/documentation/Contacts/CNPostalAddressFormatter",
        "doc://com.apple.contacts/documentation/Contacts/CNContactVCardSerialization",
        "doc://com.apple.contacts/documentation/Contacts/CNContactsUserDefaults"
      ],
      "title": "Formatters"
    }
  ],
  "topicSections": [
    {
      "anchor": "Creating-a-formatted-attributed-string",
      "identifiers": [
        "doc://com.apple.contacts/documentation/Contacts/CNContactFormatter/attributedString(from:defaultAttributes:)",
        "doc://com.apple.contacts/documentation/Contacts/CNContactFormatter/attributedString(from:style:defaultAttributes:)"
      ],
      "title": "Creating a formatted attributed string"
    },
    {
      "anchor": "Creating-a-formatted-string",
      "identifiers": [
        "doc://com.apple.contacts/documentation/Contacts/CNContactFormatter/string(from:)",
        "doc://com.apple.contacts/documentation/Contacts/CNContactFormatter/string(from:style:)"
      ],
      "title": "Creating a formatted string"
    },
    {
      "anchor": "Specifying-the-formatting-style",
      "identifiers": [
        "doc://com.apple.contacts/documentation/Contacts/CNContactFormatter/style",
        "doc://com.apple.contacts/documentation/Contacts/CNContactFormatterStyle"
      ],
      "title": "Specifying the formatting style"
    },
    {
      "anchor": "Getting-a-descriptor",
      "identifiers": [
        "doc://com.apple.contacts/documentation/Contacts/CNContactFormatter/descriptorForRequiredKeys(for:)",
        "doc://com.apple.contacts/documentation/Contacts/CNContactFormatter/descriptorForRequiredKeysForDelimiter",
        "doc://com.apple.contacts/documentation/Contacts/CNContactFormatter/descriptorForRequiredKeysForNameOrder"
      ],
      "title": "Getting a descriptor"
    },
    {
      "anchor": "Getting-format-information",
      "identifiers": [
        "doc://com.apple.contacts/documentation/Contacts/CNContactFormatter/delimiter(for:)",
        "doc://com.apple.contacts/documentation/Contacts/CNContactFormatter/nameOrder(for:)",
        "doc://com.apple.contacts/documentation/Contacts/CNContactDisplayNameOrder"
      ],
      "title": "Getting format information"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "9.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "9.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.1",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.11",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "2.0",
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Class"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "CNContactFormatter"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "class"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CNContactFormatter"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CNContactFormatter"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.contacts/documentation/Contacts"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Creating-a-formatted-attributed-string",
              "identifiers": [
                "doc://com.apple.contacts/documentation/Contacts/CNContactFormatter/attributedString(from:defaultAttributes:)",
                "doc://com.apple.contacts/documentation/Contacts/CNContactFormatter/attributedString(from:style:defaultAttributes:)"
              ],
              "title": "Creating a formatted attributed string"
            },
            {
              "anchor": "Creating-a-formatted-string",
              "identifiers": [
                "doc://com.apple.contacts/documentation/Contacts/CNContactFormatter/string(from:)",
                "doc://com.apple.contacts/documentation/Contacts/CNContactFormatter/string(from:style:)"
              ],
              "title": "Creating a formatted string"
            },
            {
              "anchor": "Specifying-the-formatting-style",
              "identifiers": [
                "doc://com.apple.contacts/documentation/Contacts/CNContactFormatter/style",
                "doc://com.apple.contacts/documentation/Contacts/CNContactFormatterStyle"
              ],
              "title": "Specifying the formatting style"
            },
            {
              "anchor": "Getting-a-descriptor",
              "identifiers": [
                "doc://com.apple.contacts/documentation/Contacts/CNContactFormatter/descriptorForRequiredKeys(for:)",
                "doc://com.apple.contacts/documentation/Contacts/CNContactFormatter/descriptorForRequiredKeysForDelimiter",
                "doc://com.apple.contacts/documentation/Contacts/CNContactFormatter/descriptorForRequiredKeysForNameOrder"
              ],
              "title": "Getting a descriptor"
            },
            {
              "anchor": "Getting-format-information",
              "identifiers": [
                "doc://com.apple.contacts/documentation/Contacts/CNContactFormatter/delimiter(for:)",
                "doc://com.apple.contacts/documentation/Contacts/CNContactFormatter/nameOrder(for:)",
                "doc://com.apple.contacts/documentation/Contacts/CNContactDisplayNameOrder"
              ],
              "title": "Getting format information"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": [
            {
              "identifiers": [
                "doc://com.externally.resolved.symbol/c:objc(cs)NSFormatter"
              ],
              "kind": "relationships",
              "title": "Inherits From",
              "type": "inheritsFrom"
            },
            {
              "identifiers": [
                "doc://com.externally.resolved.symbol/c:objc(pl)NSSecureCoding"
              ],
              "kind": "relationships",
              "title": "Conforms To",
              "type": "conformsTo"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Formatters",
              "generated": true,
              "identifiers": [
                "doc://com.apple.contacts/documentation/Contacts/CNPostalAddressFormatter",
                "doc://com.apple.contacts/documentation/Contacts/CNContactVCardSerialization",
                "doc://com.apple.contacts/documentation/Contacts/CNContactsUserDefaults"
              ],
              "title": "Formatters"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "@interface"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "CNContactFormatter"
                  },
                  {
                    "kind": "text",
                    "text": " : "
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSFormatter",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(cs)NSFormatter",
                    "text": "NSFormatter"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.contacts~1documentation~1Contacts~1CNContactFormatter~1string(from:style:)/title",
          "value": "stringFromContact:style:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.contacts~1documentation~1Contacts~1CNContactFormatter~1string(from:style:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "+ "
            },
            {
              "kind": "identifier",
              "text": "stringFromContact:style:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.contacts~1documentation~1Contacts~1CNContactVCardSerialization/title",
          "value": "CNContactVCardSerialization"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.contacts~1documentation~1Contacts~1CNContactVCardSerialization/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CNContactVCardSerialization"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.contacts~1documentation~1Contacts~1CNContactVCardSerialization/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CNContactVCardSerialization"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.contacts~1documentation~1Contacts~1CNPostalAddressFormatter/title",
          "value": "CNPostalAddressFormatter"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.contacts~1documentation~1Contacts~1CNPostalAddressFormatter/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CNPostalAddressFormatter"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.contacts~1documentation~1Contacts~1CNPostalAddressFormatter/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CNPostalAddressFormatter"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:objc(pl)NSObject/title",
          "value": "NSObject"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.contacts~1documentation~1Contacts~1CNContactDisplayNameOrder/title",
          "value": "CNContactDisplayNameOrder"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.contacts~1documentation~1Contacts~1CNContactDisplayNameOrder/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CNContactDisplayNameOrder"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.contacts~1documentation~1Contacts~1CNContactDisplayNameOrder/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CNContactDisplayNameOrder"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.contacts~1documentation~1Contacts~1CNContactFormatter~1nameOrder(for:)/title",
          "value": "nameOrderForContact:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.contacts~1documentation~1Contacts~1CNContactFormatter~1nameOrder(for:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "+ "
            },
            {
              "kind": "identifier",
              "text": "nameOrderForContact:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.contacts~1documentation~1Contacts~1CNContactFormatter~1string(from:)/title",
          "value": "stringFromContact:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.contacts~1documentation~1Contacts~1CNContactFormatter~1string(from:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "stringFromContact:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.contacts~1documentation~1Contacts~1CNContactFormatter~1descriptorForRequiredKeysForNameOrder/title",
          "value": "descriptorForRequiredKeysForNameOrder"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.contacts~1documentation~1Contacts~1CNContactFormatter~1descriptorForRequiredKeysForNameOrder/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "descriptorForRequiredKeysForNameOrder"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:objc(cs)NSFormatter/title",
          "value": "NSFormatter"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.contacts~1documentation~1Contacts~1CNContactFormatter~1style/title",
          "value": "style"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.contacts~1documentation~1Contacts~1CNContactFormatter~1style/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "style"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.contacts~1documentation~1Contacts~1CNContactFormatter~1attributedString(from:defaultAttributes:)/title",
          "value": "attributedStringFromContact:defaultAttributes:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.contacts~1documentation~1Contacts~1CNContactFormatter~1attributedString(from:defaultAttributes:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "attributedStringFromContact:defaultAttributes:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.contacts~1documentation~1Contacts~1CNContactFormatter~1descriptorForRequiredKeysForDelimiter/title",
          "value": "descriptorForRequiredKeysForDelimiter"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.contacts~1documentation~1Contacts~1CNContactFormatter~1descriptorForRequiredKeysForDelimiter/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "descriptorForRequiredKeysForDelimiter"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.contacts~1documentation~1Contacts~1CNContactFormatter~1attributedString(from:style:defaultAttributes:)/title",
          "value": "attributedStringFromContact:style:defaultAttributes:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.contacts~1documentation~1Contacts~1CNContactFormatter~1attributedString(from:style:defaultAttributes:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "+ "
            },
            {
              "kind": "identifier",
              "text": "attributedStringFromContact:style:defaultAttributes:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.contacts~1documentation~1Contacts~1CNContactFormatter/title",
          "value": "CNContactFormatter"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.contacts~1documentation~1Contacts~1CNContactFormatter/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CNContactFormatter"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.contacts~1documentation~1Contacts~1CNContactFormatter/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CNContactFormatter"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.contacts~1documentation~1Contacts~1CNContactFormatterStyle/title",
          "value": "CNContactFormatterStyle"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.contacts~1documentation~1Contacts~1CNContactFormatterStyle/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CNContactFormatterStyle"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.contacts~1documentation~1Contacts~1CNContactFormatterStyle/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CNContactFormatterStyle"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.contacts~1documentation~1Contacts~1CNContactsUserDefaults/title",
          "value": "CNContactsUserDefaults"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.contacts~1documentation~1Contacts~1CNContactsUserDefaults/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CNContactsUserDefaults"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.contacts~1documentation~1Contacts~1CNContactsUserDefaults/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CNContactsUserDefaults"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.contacts~1documentation~1Contacts~1CNContactFormatter~1delimiter(for:)/title",
          "value": "delimiterForContact:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.contacts~1documentation~1Contacts~1CNContactFormatter~1delimiter(for:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "+ "
            },
            {
              "kind": "identifier",
              "text": "delimiterForContact:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.contacts~1documentation~1Contacts~1CNContactFormatter~1descriptorForRequiredKeys(for:)/title",
          "value": "descriptorForRequiredKeysForStyle:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.contacts~1documentation~1Contacts~1CNContactFormatter~1descriptorForRequiredKeys(for:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "+ "
            },
            {
              "kind": "identifier",
              "text": "descriptorForRequiredKeysForStyle:"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/contacts/cncontactformatter"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/contacts/cncontactformatter"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
