{
  "abstract": [
    {
      "text": "Error information that may be returned when using the methods of the Contacts framework.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.contacts/documentation/Contacts"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.contacts/documentation/Contacts/CNError"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "s:SC11CNErrorCodeLeV",
    "fragments": [
      {
        "kind": "keyword",
        "text": "struct"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "CNError"
      }
    ],
    "modules": [
      {
        "name": "Contacts"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "CNError"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "9.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "9.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.1",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.11",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "2.0",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Structure",
    "symbolKind": "struct",
    "title": "CNError"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "struct"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "CNError"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.contacts/documentation/Contacts": {
      "abstract": [
        {
          "text": "Access the user’s contacts, and format and localize contact information.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.contacts/documentation/Contacts",
      "kind": "symbol",
      "role": "collection",
      "title": "Contacts",
      "type": "topic",
      "url": "/documentation/contacts"
    },
    "doc://com.apple.contacts/documentation/Contacts/CNError": {
      "abstract": [
        {
          "text": "Error information that may be returned when using the methods of the Contacts framework.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CNError"
        }
      ],
      "identifier": "doc://com.apple.contacts/documentation/Contacts/CNError",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CNError"
        }
      ],
      "role": "symbol",
      "title": "CNError",
      "type": "topic",
      "url": "/documentation/contacts/cnerror"
    },
    "doc://com.apple.contacts/documentation/Contacts/CNError/Code": {
      "abstract": [
        {
          "text": "Error codes that the system may return when you use Contacts framework methods.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.contacts/documentation/Contacts/CNError/Code",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "Code"
        }
      ],
      "role": "symbol",
      "title": "CNError.Code",
      "type": "topic",
      "url": "/documentation/contacts/cnerror/code"
    },
    "doc://com.apple.contacts/documentation/Contacts/CNError/affectedRecordIdentifiers": {
      "abstract": [
        {
          "text": "An array of strings that uniquely identify the records affected by the error.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "affectedRecordIdentifiers"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": "]?"
        }
      ],
      "identifier": "doc://com.apple.contacts/documentation/Contacts/CNError/affectedRecordIdentifiers",
      "kind": "symbol",
      "role": "symbol",
      "title": "affectedRecordIdentifiers",
      "type": "topic",
      "url": "/documentation/contacts/cnerror/affectedrecordidentifiers"
    },
    "doc://com.apple.contacts/documentation/Contacts/CNError/affectedRecords": {
      "abstract": [
        {
          "text": "An array of record objects for which the error applies.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "affectedRecords"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s9AnyObjecta",
          "text": "AnyObject"
        },
        {
          "kind": "text",
          "text": "]?"
        }
      ],
      "identifier": "doc://com.apple.contacts/documentation/Contacts/CNError/affectedRecords",
      "kind": "symbol",
      "role": "symbol",
      "title": "affectedRecords",
      "type": "topic",
      "url": "/documentation/contacts/cnerror/affectedrecords"
    },
    "doc://com.apple.contacts/documentation/Contacts/CNError/authorizationDenied": {
      "abstract": [
        {
          "text": "An error that indicates the system denied authorization.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "authorizationDenied"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC11CNErrorCodeLeV",
          "text": "CNError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@CNErrorCode",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.contacts/documentation/Contacts/CNError/authorizationDenied",
      "kind": "symbol",
      "role": "symbol",
      "title": "authorizationDenied",
      "type": "topic",
      "url": "/documentation/contacts/cnerror/authorizationdenied"
    },
    "doc://com.apple.contacts/documentation/Contacts/CNError/changeHistoryExpired": {
      "abstract": [
        {
          "text": "An error that indicates the change history expired.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "changeHistoryExpired"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC11CNErrorCodeLeV",
          "text": "CNError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@CNErrorCode",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.contacts/documentation/Contacts/CNError/changeHistoryExpired",
      "kind": "symbol",
      "role": "symbol",
      "title": "changeHistoryExpired",
      "type": "topic",
      "url": "/documentation/contacts/cnerror/changehistoryexpired"
    },
    "doc://com.apple.contacts/documentation/Contacts/CNError/changeHistoryInvalidAnchor": {
      "abstract": [
        {
          "text": "An error that indicates a change history anchor is invalid.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "changeHistoryInvalidAnchor"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC11CNErrorCodeLeV",
          "text": "CNError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@CNErrorCode",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.contacts/documentation/Contacts/CNError/changeHistoryInvalidAnchor",
      "kind": "symbol",
      "role": "symbol",
      "title": "changeHistoryInvalidAnchor",
      "type": "topic",
      "url": "/documentation/contacts/cnerror/changehistoryinvalidanchor"
    },
    "doc://com.apple.contacts/documentation/Contacts/CNError/changeHistoryInvalidFetchRequest": {
      "abstract": [
        {
          "text": "An error that indicates a change history fetch request is invalid.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "changeHistoryInvalidFetchRequest"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC11CNErrorCodeLeV",
          "text": "CNError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@CNErrorCode",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.contacts/documentation/Contacts/CNError/changeHistoryInvalidFetchRequest",
      "kind": "symbol",
      "role": "symbol",
      "title": "changeHistoryInvalidFetchRequest",
      "type": "topic",
      "url": "/documentation/contacts/cnerror/changehistoryinvalidfetchrequest"
    },
    "doc://com.apple.contacts/documentation/Contacts/CNError/clientIdentifierCollision": {
      "abstract": [
        {
          "text": "An error that indicates a client identifier collision.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "clientIdentifierCollision"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC11CNErrorCodeLeV",
          "text": "CNError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@CNErrorCode",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.contacts/documentation/Contacts/CNError/clientIdentifierCollision",
      "kind": "symbol",
      "role": "symbol",
      "title": "clientIdentifierCollision",
      "type": "topic",
      "url": "/documentation/contacts/cnerror/clientidentifiercollision"
    },
    "doc://com.apple.contacts/documentation/Contacts/CNError/clientIdentifierDoesNotExist": {
      "abstract": [
        {
          "text": "An error that indicates the client identifier doesn’t exist.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "clientIdentifierDoesNotExist"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC11CNErrorCodeLeV",
          "text": "CNError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@CNErrorCode",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.contacts/documentation/Contacts/CNError/clientIdentifierDoesNotExist",
      "kind": "symbol",
      "role": "symbol",
      "title": "clientIdentifierDoesNotExist",
      "type": "topic",
      "url": "/documentation/contacts/cnerror/clientidentifierdoesnotexist"
    },
    "doc://com.apple.contacts/documentation/Contacts/CNError/clientIdentifierInvalid": {
      "abstract": [
        {
          "text": "An error that indicates the client identifier is invalid.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "clientIdentifierInvalid"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC11CNErrorCodeLeV",
          "text": "CNError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@CNErrorCode",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.contacts/documentation/Contacts/CNError/clientIdentifierInvalid",
      "kind": "symbol",
      "role": "symbol",
      "title": "clientIdentifierInvalid",
      "type": "topic",
      "url": "/documentation/contacts/cnerror/clientidentifierinvalid"
    },
    "doc://com.apple.contacts/documentation/Contacts/CNError/communicationError": {
      "abstract": [
        {
          "text": "An error that indicates a communication error occurred.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "communicationError"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC11CNErrorCodeLeV",
          "text": "CNError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@CNErrorCode",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.contacts/documentation/Contacts/CNError/communicationError",
      "kind": "symbol",
      "role": "symbol",
      "title": "communicationError",
      "type": "topic",
      "url": "/documentation/contacts/cnerror/communicationerror"
    },
    "doc://com.apple.contacts/documentation/Contacts/CNError/containmentCycle": {
      "abstract": [
        {
          "text": "An error with the containment cycle.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "containmentCycle"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC11CNErrorCodeLeV",
          "text": "CNError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@CNErrorCode",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.contacts/documentation/Contacts/CNError/containmentCycle",
      "kind": "symbol",
      "role": "symbol",
      "title": "containmentCycle",
      "type": "topic",
      "url": "/documentation/contacts/cnerror/containmentcycle"
    },
    "doc://com.apple.contacts/documentation/Contacts/CNError/containmentScope": {
      "abstract": [
        {
          "text": "An error with containment scope.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "containmentScope"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC11CNErrorCodeLeV",
          "text": "CNError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@CNErrorCode",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.contacts/documentation/Contacts/CNError/containmentScope",
      "kind": "symbol",
      "role": "symbol",
      "title": "containmentScope",
      "type": "topic",
      "url": "/documentation/contacts/cnerror/containmentscope"
    },
    "doc://com.apple.contacts/documentation/Contacts/CNError/dataAccessError": {
      "abstract": [
        {
          "text": "An error with data access.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "dataAccessError"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC11CNErrorCodeLeV",
          "text": "CNError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@CNErrorCode",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.contacts/documentation/Contacts/CNError/dataAccessError",
      "kind": "symbol",
      "role": "symbol",
      "title": "dataAccessError",
      "type": "topic",
      "url": "/documentation/contacts/cnerror/dataaccesserror"
    },
    "doc://com.apple.contacts/documentation/Contacts/CNError/errorDomain": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "errorDomain"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.contacts/documentation/Contacts/CNError/errorDomain",
      "kind": "symbol",
      "role": "symbol",
      "title": "errorDomain",
      "type": "topic",
      "url": "/documentation/contacts/cnerror/errordomain"
    },
    "doc://com.apple.contacts/documentation/Contacts/CNError/featureDisabledByUser": {
      "abstract": [
        {
          "text": "An error that indicates the user disabled the feature.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "featureDisabledByUser"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC11CNErrorCodeLeV",
          "text": "CNError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@CNErrorCode",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.contacts/documentation/Contacts/CNError/featureDisabledByUser",
      "kind": "symbol",
      "role": "symbol",
      "title": "featureDisabledByUser",
      "type": "topic",
      "url": "/documentation/contacts/cnerror/featuredisabledbyuser"
    },
    "doc://com.apple.contacts/documentation/Contacts/CNError/featureNotAvailable": {
      "abstract": [
        {
          "text": "An error that indicates the feature isn’t available.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "featureNotAvailable"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC11CNErrorCodeLeV",
          "text": "CNError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@CNErrorCode",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.contacts/documentation/Contacts/CNError/featureNotAvailable",
      "kind": "symbol",
      "role": "symbol",
      "title": "featureNotAvailable",
      "type": "topic",
      "url": "/documentation/contacts/cnerror/featurenotavailable"
    },
    "doc://com.apple.contacts/documentation/Contacts/CNError/insertedRecordAlreadyExists": {
      "abstract": [
        {
          "text": "An error that indicates the inserted record already exists.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "insertedRecordAlreadyExists"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC11CNErrorCodeLeV",
          "text": "CNError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@CNErrorCode",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.contacts/documentation/Contacts/CNError/insertedRecordAlreadyExists",
      "kind": "symbol",
      "role": "symbol",
      "title": "insertedRecordAlreadyExists",
      "type": "topic",
      "url": "/documentation/contacts/cnerror/insertedrecordalreadyexists"
    },
    "doc://com.apple.contacts/documentation/Contacts/CNError/keyPaths": {
      "abstract": [
        {
          "text": "An array of key paths associated with the error.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "keyPaths"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": "]?"
        }
      ],
      "identifier": "doc://com.apple.contacts/documentation/Contacts/CNError/keyPaths",
      "kind": "symbol",
      "role": "symbol",
      "title": "keyPaths",
      "type": "topic",
      "url": "/documentation/contacts/cnerror/keypaths"
    },
    "doc://com.apple.contacts/documentation/Contacts/CNError/noAccessableWritableContainers": {
      "abstract": [
        {
          "text": "An error that indicates there are no accessible writable containers.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "noAccessableWritableContainers"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC11CNErrorCodeLeV",
          "text": "CNError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@CNErrorCode",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.contacts/documentation/Contacts/CNError/noAccessableWritableContainers",
      "kind": "symbol",
      "role": "symbol",
      "title": "noAccessableWritableContainers",
      "type": "topic",
      "url": "/documentation/contacts/cnerror/noaccessablewritablecontainers"
    },
    "doc://com.apple.contacts/documentation/Contacts/CNError/parentContainerNotWritable": {
      "abstract": [
        {
          "text": "An error that indicates the parent container isn’t writable.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "parentContainerNotWritable"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC11CNErrorCodeLeV",
          "text": "CNError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@CNErrorCode",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.contacts/documentation/Contacts/CNError/parentContainerNotWritable",
      "kind": "symbol",
      "role": "symbol",
      "title": "parentContainerNotWritable",
      "type": "topic",
      "url": "/documentation/contacts/cnerror/parentcontainernotwritable"
    },
    "doc://com.apple.contacts/documentation/Contacts/CNError/parentRecordDoesNotExist": {
      "abstract": [
        {
          "text": "An error that indicates the parent record doesn’t exist.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "parentRecordDoesNotExist"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC11CNErrorCodeLeV",
          "text": "CNError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@CNErrorCode",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.contacts/documentation/Contacts/CNError/parentRecordDoesNotExist",
      "kind": "symbol",
      "role": "symbol",
      "title": "parentRecordDoesNotExist",
      "type": "topic",
      "url": "/documentation/contacts/cnerror/parentrecorddoesnotexist"
    },
    "doc://com.apple.contacts/documentation/Contacts/CNError/policyViolation": {
      "abstract": [
        {
          "text": "An error that indicates a policy violation.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "policyViolation"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC11CNErrorCodeLeV",
          "text": "CNError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@CNErrorCode",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.contacts/documentation/Contacts/CNError/policyViolation",
      "kind": "symbol",
      "role": "symbol",
      "title": "policyViolation",
      "type": "topic",
      "url": "/documentation/contacts/cnerror/policyviolation"
    },
    "doc://com.apple.contacts/documentation/Contacts/CNError/predicateInvalid": {
      "abstract": [
        {
          "text": "An error that indicates an invalid predicate.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "predicateInvalid"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC11CNErrorCodeLeV",
          "text": "CNError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@CNErrorCode",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.contacts/documentation/Contacts/CNError/predicateInvalid",
      "kind": "symbol",
      "role": "symbol",
      "title": "predicateInvalid",
      "type": "topic",
      "url": "/documentation/contacts/cnerror/predicateinvalid"
    },
    "doc://com.apple.contacts/documentation/Contacts/CNError/recordDoesNotExist": {
      "abstract": [
        {
          "text": "An error that indicates a record doesn’t exist.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "recordDoesNotExist"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC11CNErrorCodeLeV",
          "text": "CNError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@CNErrorCode",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.contacts/documentation/Contacts/CNError/recordDoesNotExist",
      "kind": "symbol",
      "role": "symbol",
      "title": "recordDoesNotExist",
      "type": "topic",
      "url": "/documentation/contacts/cnerror/recorddoesnotexist"
    },
    "doc://com.apple.contacts/documentation/Contacts/CNError/recordIdentifierInvalid": {
      "abstract": [
        {
          "text": "An error that indicates a record identifier is invalid.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "recordIdentifierInvalid"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC11CNErrorCodeLeV",
          "text": "CNError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@CNErrorCode",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.contacts/documentation/Contacts/CNError/recordIdentifierInvalid",
      "kind": "symbol",
      "role": "symbol",
      "title": "recordIdentifierInvalid",
      "type": "topic",
      "url": "/documentation/contacts/cnerror/recordidentifierinvalid"
    },
    "doc://com.apple.contacts/documentation/Contacts/CNError/recordNotWritable": {
      "abstract": [
        {
          "text": "An error that indicates a record isn’t writable.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "recordNotWritable"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC11CNErrorCodeLeV",
          "text": "CNError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@CNErrorCode",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.contacts/documentation/Contacts/CNError/recordNotWritable",
      "kind": "symbol",
      "role": "symbol",
      "title": "recordNotWritable",
      "type": "topic",
      "url": "/documentation/contacts/cnerror/recordnotwritable"
    },
    "doc://com.apple.contacts/documentation/Contacts/CNError/unauthorizedKeys": {
      "abstract": [
        {
          "text": "An error that indicates unauthorized keys usage.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "unauthorizedKeys"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC11CNErrorCodeLeV",
          "text": "CNError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@CNErrorCode",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.contacts/documentation/Contacts/CNError/unauthorizedKeys",
      "kind": "symbol",
      "role": "symbol",
      "title": "unauthorizedKeys",
      "type": "topic",
      "url": "/documentation/contacts/cnerror/unauthorizedkeys"
    },
    "doc://com.apple.contacts/documentation/Contacts/CNError/vCardMalformed": {
      "abstract": [
        {
          "text": "An error that indicates a malformed vCard.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "vCardMalformed"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC11CNErrorCodeLeV",
          "text": "CNError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@CNErrorCode",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.contacts/documentation/Contacts/CNError/vCardMalformed",
      "kind": "symbol",
      "role": "symbol",
      "title": "vCardMalformed",
      "type": "topic",
      "url": "/documentation/contacts/cnerror/vcardmalformed"
    },
    "doc://com.apple.contacts/documentation/Contacts/CNError/vCardSummarizationError": {
      "abstract": [
        {
          "text": "An error that indicates a vCard summarization problem.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "vCardSummarizationError"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC11CNErrorCodeLeV",
          "text": "CNError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@CNErrorCode",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.contacts/documentation/Contacts/CNError/vCardSummarizationError",
      "kind": "symbol",
      "role": "symbol",
      "title": "vCardSummarizationError",
      "type": "topic",
      "url": "/documentation/contacts/cnerror/vcardsummarizationerror"
    },
    "doc://com.apple.contacts/documentation/Contacts/CNError/validationConfigurationError": {
      "abstract": [
        {
          "text": "An error with validation configuration.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "validationConfigurationError"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC11CNErrorCodeLeV",
          "text": "CNError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@CNErrorCode",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.contacts/documentation/Contacts/CNError/validationConfigurationError",
      "kind": "symbol",
      "role": "symbol",
      "title": "validationConfigurationError",
      "type": "topic",
      "url": "/documentation/contacts/cnerror/validationconfigurationerror"
    },
    "doc://com.apple.contacts/documentation/Contacts/CNError/validationMultipleErrors": {
      "abstract": [
        {
          "text": "An error that indicates the system encountered multiple validation errors.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "validationMultipleErrors"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC11CNErrorCodeLeV",
          "text": "CNError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@CNErrorCode",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.contacts/documentation/Contacts/CNError/validationMultipleErrors",
      "kind": "symbol",
      "role": "symbol",
      "title": "validationMultipleErrors",
      "type": "topic",
      "url": "/documentation/contacts/cnerror/validationmultipleerrors"
    },
    "doc://com.apple.contacts/documentation/Contacts/CNError/validationTypeMismatch": {
      "abstract": [
        {
          "text": "A validation error that indicates a type mismatch.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "validationTypeMismatch"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC11CNErrorCodeLeV",
          "text": "CNError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@CNErrorCode",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.contacts/documentation/Contacts/CNError/validationTypeMismatch",
      "kind": "symbol",
      "role": "symbol",
      "title": "validationTypeMismatch",
      "type": "topic",
      "url": "/documentation/contacts/cnerror/validationtypemismatch"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.externally.resolved.symbol/s:10Foundation13CustomNSErrorP": {
      "abstract": [
        {
          "text": "A specialized error that provides a domain, error code, and user-info dictionary.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "protocol "
        },
        {
          "kind": "identifier",
          "text": "CustomNSError"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:10Foundation13CustomNSErrorP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CustomNSError",
      "type": "topic",
      "url": "/documentation/foundation/customnserror"
    },
    "doc://com.externally.resolved.symbol/s:SH": {
      "abstract": [
        {
          "text": "A type that can be hashed into a `Hasher` to produce an integer hash value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Hashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SQ",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SH",
      "kind": "symbol",
      "role": "symbol",
      "title": "Hashable",
      "type": "topic",
      "url": "/documentation/Swift/Hashable"
    },
    "doc://com.externally.resolved.symbol/s:SQ": {
      "abstract": [
        {
          "text": "A type that can be compared for value equality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SQ",
      "kind": "symbol",
      "role": "symbol",
      "title": "Equatable",
      "type": "topic",
      "url": "/documentation/Swift/Equatable"
    },
    "doc://com.externally.resolved.symbol/s:s5ErrorP": {
      "abstract": [
        {
          "text": "A type representing an error value that can be thrown.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Error"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s8SendableP",
          "text": "Sendable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s5ErrorP",
      "kind": "symbol",
      "role": "symbol",
      "title": "Error",
      "type": "topic",
      "url": "/documentation/Swift/Error"
    },
    "doc://com.externally.resolved.symbol/s:s8SendableP": {
      "abstract": [
        {
          "text": "A thread-safe type whose values can be shared across arbitrary concurrent contexts without introducing a risk of data races.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Sendable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s8SendableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "Sendable",
      "type": "topic",
      "url": "/documentation/Swift/Sendable"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:10Foundation13CustomNSErrorP",
        "doc://com.externally.resolved.symbol/s:SQ",
        "doc://com.externally.resolved.symbol/s:s5ErrorP",
        "doc://com.externally.resolved.symbol/s:SH",
        "doc://com.externally.resolved.symbol/s:s8SendableP"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Error-codes",
      "generated": true,
      "identifiers": [
        "doc://com.apple.contacts/documentation/Contacts/CNError/Code"
      ],
      "title": "Error codes"
    }
  ],
  "topicSections": [
    {
      "anchor": "Error-codes",
      "identifiers": [
        "doc://com.apple.contacts/documentation/Contacts/CNError/authorizationDenied",
        "doc://com.apple.contacts/documentation/Contacts/CNError/changeHistoryExpired",
        "doc://com.apple.contacts/documentation/Contacts/CNError/changeHistoryInvalidAnchor",
        "doc://com.apple.contacts/documentation/Contacts/CNError/changeHistoryInvalidFetchRequest",
        "doc://com.apple.contacts/documentation/Contacts/CNError/clientIdentifierCollision",
        "doc://com.apple.contacts/documentation/Contacts/CNError/clientIdentifierDoesNotExist",
        "doc://com.apple.contacts/documentation/Contacts/CNError/clientIdentifierInvalid",
        "doc://com.apple.contacts/documentation/Contacts/CNError/communicationError",
        "doc://com.apple.contacts/documentation/Contacts/CNError/containmentCycle",
        "doc://com.apple.contacts/documentation/Contacts/CNError/containmentScope",
        "doc://com.apple.contacts/documentation/Contacts/CNError/dataAccessError",
        "doc://com.apple.contacts/documentation/Contacts/CNError/featureDisabledByUser",
        "doc://com.apple.contacts/documentation/Contacts/CNError/featureNotAvailable",
        "doc://com.apple.contacts/documentation/Contacts/CNError/insertedRecordAlreadyExists",
        "doc://com.apple.contacts/documentation/Contacts/CNError/noAccessableWritableContainers",
        "doc://com.apple.contacts/documentation/Contacts/CNError/parentContainerNotWritable",
        "doc://com.apple.contacts/documentation/Contacts/CNError/parentRecordDoesNotExist",
        "doc://com.apple.contacts/documentation/Contacts/CNError/policyViolation",
        "doc://com.apple.contacts/documentation/Contacts/CNError/predicateInvalid",
        "doc://com.apple.contacts/documentation/Contacts/CNError/recordDoesNotExist",
        "doc://com.apple.contacts/documentation/Contacts/CNError/recordIdentifierInvalid",
        "doc://com.apple.contacts/documentation/Contacts/CNError/recordNotWritable",
        "doc://com.apple.contacts/documentation/Contacts/CNError/unauthorizedKeys",
        "doc://com.apple.contacts/documentation/Contacts/CNError/vCardMalformed",
        "doc://com.apple.contacts/documentation/Contacts/CNError/vCardSummarizationError",
        "doc://com.apple.contacts/documentation/Contacts/CNError/validationConfigurationError",
        "doc://com.apple.contacts/documentation/Contacts/CNError/validationMultipleErrors",
        "doc://com.apple.contacts/documentation/Contacts/CNError/validationTypeMismatch"
      ],
      "title": "Error codes"
    },
    {
      "anchor": "Error-details",
      "identifiers": [
        "doc://com.apple.contacts/documentation/Contacts/CNError/affectedRecordIdentifiers",
        "doc://com.apple.contacts/documentation/Contacts/CNError/affectedRecords",
        "doc://com.apple.contacts/documentation/Contacts/CNError/Code",
        "doc://com.apple.contacts/documentation/Contacts/CNError/keyPaths"
      ],
      "title": "Error details"
    },
    {
      "anchor": "Type-Properties",
      "generated": true,
      "identifiers": [
        "doc://com.apple.contacts/documentation/Contacts/CNError/errorDomain"
      ],
      "title": "Type Properties"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.contacts~1documentation~1Contacts~1CNError~1Code/title",
          "value": "CNErrorCode"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.contacts~1documentation~1Contacts~1CNError~1Code/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CNErrorCode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.contacts~1documentation~1Contacts~1CNError~1Code/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CNErrorCode"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/contacts/cnerror"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    }
  ]
}
