{
  "abstract": [
    {
      "text": "Instant message service for AIM.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.contacts/documentation/Contacts"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.contacts/documentation/Contacts/CNInstantMessageServiceAIM"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@CNInstantMessageServiceAIM",
    "fragments": [
      {
        "kind": "keyword",
        "text": "let"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "CNInstantMessageServiceAIM"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "s:SS",
        "text": "String"
      }
    ],
    "modules": [
      {
        "name": "Contacts"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "CNInstantMessageServiceAIM"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "9.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "9.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.1",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.11",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "2.0",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Global Variable",
    "symbolKind": "var",
    "title": "CNInstantMessageServiceAIM"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "let"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "CNInstantMessageServiceAIM"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:SS",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:SS",
              "text": "String"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "This key takes a string value.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.contacts/documentation/Contacts": {
      "abstract": [
        {
          "text": "Access the user’s contacts, and format and localize contact information.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.contacts/documentation/Contacts",
      "kind": "symbol",
      "role": "collection",
      "title": "Contacts",
      "type": "topic",
      "url": "/documentation/contacts"
    },
    "doc://com.apple.contacts/documentation/Contacts/CNInstantMessageAddress/localizedString(forService:)": {
      "abstract": [
        {
          "text": "Returns a string containing the localized name of the specified service.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "localizedString"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "forService"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.contacts/documentation/Contacts/CNInstantMessageAddress/localizedString(forService:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "localizedStringForService:"
        }
      ],
      "role": "symbol",
      "title": "localizedString(forService:)",
      "type": "topic",
      "url": "/documentation/contacts/cninstantmessageaddress/localizedstring(forservice:)"
    },
    "doc://com.apple.contacts/documentation/Contacts/CNInstantMessageServiceAIM": {
      "abstract": [
        {
          "text": "Instant message service for AIM.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CNInstantMessageServiceAIM"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.contacts/documentation/Contacts/CNInstantMessageServiceAIM",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CNInstantMessageServiceAIM"
        }
      ],
      "role": "symbol",
      "title": "CNInstantMessageServiceAIM",
      "type": "topic",
      "url": "/documentation/contacts/cninstantmessageserviceaim"
    },
    "doc://com.apple.contacts/documentation/Contacts/CNInstantMessageServiceFacebook": {
      "abstract": [
        {
          "text": "Instant message service for Facebook.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CNInstantMessageServiceFacebook"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.contacts/documentation/Contacts/CNInstantMessageServiceFacebook",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CNInstantMessageServiceFacebook"
        }
      ],
      "role": "symbol",
      "title": "CNInstantMessageServiceFacebook",
      "type": "topic",
      "url": "/documentation/contacts/cninstantmessageservicefacebook"
    },
    "doc://com.apple.contacts/documentation/Contacts/CNInstantMessageServiceGaduGadu": {
      "abstract": [
        {
          "text": "Instant message service for Gadu Gadu.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CNInstantMessageServiceGaduGadu"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.contacts/documentation/Contacts/CNInstantMessageServiceGaduGadu",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CNInstantMessageServiceGaduGadu"
        }
      ],
      "role": "symbol",
      "title": "CNInstantMessageServiceGaduGadu",
      "type": "topic",
      "url": "/documentation/contacts/cninstantmessageservicegadugadu"
    },
    "doc://com.apple.contacts/documentation/Contacts/CNInstantMessageServiceGoogleTalk": {
      "abstract": [
        {
          "text": "Instant message service for Google Talk.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CNInstantMessageServiceGoogleTalk"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.contacts/documentation/Contacts/CNInstantMessageServiceGoogleTalk",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CNInstantMessageServiceGoogleTalk"
        }
      ],
      "role": "symbol",
      "title": "CNInstantMessageServiceGoogleTalk",
      "type": "topic",
      "url": "/documentation/contacts/cninstantmessageservicegoogletalk"
    },
    "doc://com.apple.contacts/documentation/Contacts/CNInstantMessageServiceICQ": {
      "abstract": [
        {
          "text": "Instant message service for ICQ.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CNInstantMessageServiceICQ"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.contacts/documentation/Contacts/CNInstantMessageServiceICQ",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CNInstantMessageServiceICQ"
        }
      ],
      "role": "symbol",
      "title": "CNInstantMessageServiceICQ",
      "type": "topic",
      "url": "/documentation/contacts/cninstantmessageserviceicq"
    },
    "doc://com.apple.contacts/documentation/Contacts/CNInstantMessageServiceJabber": {
      "abstract": [
        {
          "text": "Instant message service for Jabber.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CNInstantMessageServiceJabber"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.contacts/documentation/Contacts/CNInstantMessageServiceJabber",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CNInstantMessageServiceJabber"
        }
      ],
      "role": "symbol",
      "title": "CNInstantMessageServiceJabber",
      "type": "topic",
      "url": "/documentation/contacts/cninstantmessageservicejabber"
    },
    "doc://com.apple.contacts/documentation/Contacts/CNInstantMessageServiceMSN": {
      "abstract": [
        {
          "text": "Instant message service for MSN.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CNInstantMessageServiceMSN"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.contacts/documentation/Contacts/CNInstantMessageServiceMSN",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CNInstantMessageServiceMSN"
        }
      ],
      "role": "symbol",
      "title": "CNInstantMessageServiceMSN",
      "type": "topic",
      "url": "/documentation/contacts/cninstantmessageservicemsn"
    },
    "doc://com.apple.contacts/documentation/Contacts/CNInstantMessageServiceQQ": {
      "abstract": [
        {
          "text": "Instant message service for QQ.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CNInstantMessageServiceQQ"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.contacts/documentation/Contacts/CNInstantMessageServiceQQ",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CNInstantMessageServiceQQ"
        }
      ],
      "role": "symbol",
      "title": "CNInstantMessageServiceQQ",
      "type": "topic",
      "url": "/documentation/contacts/cninstantmessageserviceqq"
    },
    "doc://com.apple.contacts/documentation/Contacts/CNInstantMessageServiceSkype": {
      "abstract": [
        {
          "text": "Instant message service for Skype.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CNInstantMessageServiceSkype"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.contacts/documentation/Contacts/CNInstantMessageServiceSkype",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CNInstantMessageServiceSkype"
        }
      ],
      "role": "symbol",
      "title": "CNInstantMessageServiceSkype",
      "type": "topic",
      "url": "/documentation/contacts/cninstantmessageserviceskype"
    },
    "doc://com.apple.contacts/documentation/Contacts/CNInstantMessageServiceYahoo": {
      "abstract": [
        {
          "text": "Instant message service for Yahoo.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CNInstantMessageServiceYahoo"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.contacts/documentation/Contacts/CNInstantMessageServiceYahoo",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CNInstantMessageServiceYahoo"
        }
      ],
      "role": "symbol",
      "title": "CNInstantMessageServiceYahoo",
      "type": "topic",
      "url": "/documentation/contacts/cninstantmessageserviceyahoo"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.externally.resolved.symbol/c:objc(cs)NSString": {
      "abstract": [
        {
          "text": "A static, plain-text Unicode string object which you use when you need reference semantics or other Foundation-specific behavior. ",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "class "
        },
        {
          "kind": "identifier",
          "text": "NSString"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSString",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSString",
      "type": "topic",
      "url": "/documentation/foundation/nsstring"
    },
    "doc://com.externally.resolved.symbol/s:SS": {
      "abstract": [
        {
          "text": "A Unicode string value that is a collection of characters.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@frozen"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "String"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SS",
      "kind": "symbol",
      "role": "symbol",
      "title": "String",
      "type": "topic",
      "url": "/documentation/Swift/String"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Getting-Localized-Service-Names",
      "generated": true,
      "identifiers": [
        "doc://com.apple.contacts/documentation/Contacts/CNInstantMessageAddress/localizedString(forService:)",
        "doc://com.apple.contacts/documentation/Contacts/CNInstantMessageServiceFacebook",
        "doc://com.apple.contacts/documentation/Contacts/CNInstantMessageServiceGaduGadu",
        "doc://com.apple.contacts/documentation/Contacts/CNInstantMessageServiceGoogleTalk",
        "doc://com.apple.contacts/documentation/Contacts/CNInstantMessageServiceICQ",
        "doc://com.apple.contacts/documentation/Contacts/CNInstantMessageServiceJabber",
        "doc://com.apple.contacts/documentation/Contacts/CNInstantMessageServiceMSN",
        "doc://com.apple.contacts/documentation/Contacts/CNInstantMessageServiceQQ",
        "doc://com.apple.contacts/documentation/Contacts/CNInstantMessageServiceSkype",
        "doc://com.apple.contacts/documentation/Contacts/CNInstantMessageServiceYahoo"
      ],
      "title": "Getting Localized Service Names"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "9.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "9.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.1",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.11",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "2.0",
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Global Variable"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "CNInstantMessageServiceAIM"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "var"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CNInstantMessageServiceAIM"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.contacts/documentation/Contacts"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Getting-Localized-Service-Names",
              "generated": true,
              "identifiers": [
                "doc://com.apple.contacts/documentation/Contacts/CNInstantMessageAddress/localizedString(forService:)",
                "doc://com.apple.contacts/documentation/Contacts/CNInstantMessageServiceFacebook",
                "doc://com.apple.contacts/documentation/Contacts/CNInstantMessageServiceGaduGadu",
                "doc://com.apple.contacts/documentation/Contacts/CNInstantMessageServiceGoogleTalk",
                "doc://com.apple.contacts/documentation/Contacts/CNInstantMessageServiceICQ",
                "doc://com.apple.contacts/documentation/Contacts/CNInstantMessageServiceJabber",
                "doc://com.apple.contacts/documentation/Contacts/CNInstantMessageServiceMSN",
                "doc://com.apple.contacts/documentation/Contacts/CNInstantMessageServiceQQ",
                "doc://com.apple.contacts/documentation/Contacts/CNInstantMessageServiceSkype",
                "doc://com.apple.contacts/documentation/Contacts/CNInstantMessageServiceYahoo"
              ],
              "title": "Getting Localized Service Names"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "extern"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSString",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(cs)NSString",
                    "text": "NSString"
                  },
                  {
                    "kind": "text",
                    "text": " * "
                  },
                  {
                    "kind": "keyword",
                    "text": "const"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "CNInstantMessageServiceAIM"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.contacts~1documentation~1Contacts~1CNInstantMessageServiceGaduGadu/title",
          "value": "CNInstantMessageServiceGaduGadu"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.contacts~1documentation~1Contacts~1CNInstantMessageServiceGaduGadu/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CNInstantMessageServiceGaduGadu"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.contacts~1documentation~1Contacts~1CNInstantMessageServiceAIM/title",
          "value": "CNInstantMessageServiceAIM"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.contacts~1documentation~1Contacts~1CNInstantMessageServiceAIM/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CNInstantMessageServiceAIM"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.contacts~1documentation~1Contacts~1CNInstantMessageServiceSkype/title",
          "value": "CNInstantMessageServiceSkype"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.contacts~1documentation~1Contacts~1CNInstantMessageServiceSkype/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CNInstantMessageServiceSkype"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:objc(cs)NSString/abstract",
          "value": [
            {
              "text": "A static, plain-text Unicode string object.",
              "type": "text"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.contacts~1documentation~1Contacts~1CNInstantMessageServiceGoogleTalk/title",
          "value": "CNInstantMessageServiceGoogleTalk"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.contacts~1documentation~1Contacts~1CNInstantMessageServiceGoogleTalk/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CNInstantMessageServiceGoogleTalk"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.contacts~1documentation~1Contacts~1CNInstantMessageServiceMSN/title",
          "value": "CNInstantMessageServiceMSN"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.contacts~1documentation~1Contacts~1CNInstantMessageServiceMSN/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CNInstantMessageServiceMSN"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.contacts~1documentation~1Contacts~1CNInstantMessageServiceFacebook/title",
          "value": "CNInstantMessageServiceFacebook"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.contacts~1documentation~1Contacts~1CNInstantMessageServiceFacebook/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CNInstantMessageServiceFacebook"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.contacts~1documentation~1Contacts~1CNInstantMessageServiceYahoo/title",
          "value": "CNInstantMessageServiceYahoo"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.contacts~1documentation~1Contacts~1CNInstantMessageServiceYahoo/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CNInstantMessageServiceYahoo"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.contacts~1documentation~1Contacts~1CNInstantMessageServiceICQ/title",
          "value": "CNInstantMessageServiceICQ"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.contacts~1documentation~1Contacts~1CNInstantMessageServiceICQ/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CNInstantMessageServiceICQ"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.contacts~1documentation~1Contacts~1CNInstantMessageServiceJabber/title",
          "value": "CNInstantMessageServiceJabber"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.contacts~1documentation~1Contacts~1CNInstantMessageServiceJabber/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CNInstantMessageServiceJabber"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.contacts~1documentation~1Contacts~1CNInstantMessageAddress~1localizedString(forService:)/title",
          "value": "localizedStringForService:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.contacts~1documentation~1Contacts~1CNInstantMessageAddress~1localizedString(forService:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "+ "
            },
            {
              "kind": "identifier",
              "text": "localizedStringForService:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.contacts~1documentation~1Contacts~1CNInstantMessageServiceQQ/title",
          "value": "CNInstantMessageServiceQQ"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.contacts~1documentation~1Contacts~1CNInstantMessageServiceQQ/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CNInstantMessageServiceQQ"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/contacts/cninstantmessageserviceaim"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/contacts/cninstantmessageserviceaim"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
