{
  "abstract": [
    {
      "text": "The label for the contact’s eldest sister.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.contacts/documentation/Contacts"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.contacts/documentation/Contacts/CNLabelContactRelationEldestSister"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@CNLabelContactRelationEldestSister",
    "fragments": [
      {
        "kind": "keyword",
        "text": "let"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "CNLabelContactRelationEldestSister"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "s:SS",
        "text": "String"
      }
    ],
    "modules": [
      {
        "name": "Contacts"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "CNLabelContactRelationEldestSister"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.1",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.15",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "6.0",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Global Variable",
    "symbolKind": "var",
    "title": "CNLabelContactRelationEldestSister"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "let"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "CNLabelContactRelationEldestSister"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:SS",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:SS",
              "text": "String"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.contacts/documentation/Contacts": {
      "abstract": [
        {
          "text": "Access the user’s contacts, and format and localize contact information.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.contacts/documentation/Contacts",
      "kind": "symbol",
      "role": "collection",
      "title": "Contacts",
      "type": "topic",
      "url": "/documentation/contacts"
    },
    "doc://com.apple.contacts/documentation/Contacts/CNLabelContactRelationBrother": {
      "abstract": [
        {
          "text": "The label for the contact’s brother.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CNLabelContactRelationBrother"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.contacts/documentation/Contacts/CNLabelContactRelationBrother",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CNLabelContactRelationBrother"
        }
      ],
      "role": "symbol",
      "title": "CNLabelContactRelationBrother",
      "type": "topic",
      "url": "/documentation/contacts/cnlabelcontactrelationbrother"
    },
    "doc://com.apple.contacts/documentation/Contacts/CNLabelContactRelationChild": {
      "abstract": [
        {
          "text": "The label for the contact’s child.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CNLabelContactRelationChild"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.contacts/documentation/Contacts/CNLabelContactRelationChild",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CNLabelContactRelationChild"
        }
      ],
      "role": "symbol",
      "title": "CNLabelContactRelationChild",
      "type": "topic",
      "url": "/documentation/contacts/cnlabelcontactrelationchild"
    },
    "doc://com.apple.contacts/documentation/Contacts/CNLabelContactRelationDaughter": {
      "abstract": [
        {
          "text": "The label for the contact’s daughter.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CNLabelContactRelationDaughter"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.contacts/documentation/Contacts/CNLabelContactRelationDaughter",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CNLabelContactRelationDaughter"
        }
      ],
      "role": "symbol",
      "title": "CNLabelContactRelationDaughter",
      "type": "topic",
      "url": "/documentation/contacts/cnlabelcontactrelationdaughter"
    },
    "doc://com.apple.contacts/documentation/Contacts/CNLabelContactRelationElderBrother": {
      "abstract": [
        {
          "text": "The label for the contact’s elder brother.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CNLabelContactRelationElderBrother"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.contacts/documentation/Contacts/CNLabelContactRelationElderBrother",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CNLabelContactRelationElderBrother"
        }
      ],
      "role": "symbol",
      "title": "CNLabelContactRelationElderBrother",
      "type": "topic",
      "url": "/documentation/contacts/cnlabelcontactrelationelderbrother"
    },
    "doc://com.apple.contacts/documentation/Contacts/CNLabelContactRelationElderSibling": {
      "abstract": [
        {
          "text": "The label for the contact’s elder sibling.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CNLabelContactRelationElderSibling"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.contacts/documentation/Contacts/CNLabelContactRelationElderSibling",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CNLabelContactRelationElderSibling"
        }
      ],
      "role": "symbol",
      "title": "CNLabelContactRelationElderSibling",
      "type": "topic",
      "url": "/documentation/contacts/cnlabelcontactrelationeldersibling"
    },
    "doc://com.apple.contacts/documentation/Contacts/CNLabelContactRelationElderSister": {
      "abstract": [
        {
          "text": "The label for the contact’s elder sister.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CNLabelContactRelationElderSister"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.contacts/documentation/Contacts/CNLabelContactRelationElderSister",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CNLabelContactRelationElderSister"
        }
      ],
      "role": "symbol",
      "title": "CNLabelContactRelationElderSister",
      "type": "topic",
      "url": "/documentation/contacts/cnlabelcontactrelationeldersister"
    },
    "doc://com.apple.contacts/documentation/Contacts/CNLabelContactRelationEldestBrother": {
      "abstract": [
        {
          "text": "The label for the contact’s eldest brother.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CNLabelContactRelationEldestBrother"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.contacts/documentation/Contacts/CNLabelContactRelationEldestBrother",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CNLabelContactRelationEldestBrother"
        }
      ],
      "role": "symbol",
      "title": "CNLabelContactRelationEldestBrother",
      "type": "topic",
      "url": "/documentation/contacts/cnlabelcontactrelationeldestbrother"
    },
    "doc://com.apple.contacts/documentation/Contacts/CNLabelContactRelationEldestSister": {
      "abstract": [
        {
          "text": "The label for the contact’s eldest sister.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CNLabelContactRelationEldestSister"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.contacts/documentation/Contacts/CNLabelContactRelationEldestSister",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CNLabelContactRelationEldestSister"
        }
      ],
      "role": "symbol",
      "title": "CNLabelContactRelationEldestSister",
      "type": "topic",
      "url": "/documentation/contacts/cnlabelcontactrelationeldestsister"
    },
    "doc://com.apple.contacts/documentation/Contacts/CNLabelContactRelationFather": {
      "abstract": [
        {
          "text": "The label for the contact’s father.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CNLabelContactRelationFather"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.contacts/documentation/Contacts/CNLabelContactRelationFather",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CNLabelContactRelationFather"
        }
      ],
      "role": "symbol",
      "title": "CNLabelContactRelationFather",
      "type": "topic",
      "url": "/documentation/contacts/cnlabelcontactrelationfather"
    },
    "doc://com.apple.contacts/documentation/Contacts/CNLabelContactRelationFemalePartner": {
      "abstract": [
        {
          "text": "The label for the contact’s female partner.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CNLabelContactRelationFemalePartner"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.contacts/documentation/Contacts/CNLabelContactRelationFemalePartner",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CNLabelContactRelationFemalePartner"
        }
      ],
      "role": "symbol",
      "title": "CNLabelContactRelationFemalePartner",
      "type": "topic",
      "url": "/documentation/contacts/cnlabelcontactrelationfemalepartner"
    },
    "doc://com.apple.contacts/documentation/Contacts/CNLabelContactRelationHusband": {
      "abstract": [
        {
          "text": "The label for the contact’s husband.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CNLabelContactRelationHusband"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.contacts/documentation/Contacts/CNLabelContactRelationHusband",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CNLabelContactRelationHusband"
        }
      ],
      "role": "symbol",
      "title": "CNLabelContactRelationHusband",
      "type": "topic",
      "url": "/documentation/contacts/cnlabelcontactrelationhusband"
    },
    "doc://com.apple.contacts/documentation/Contacts/CNLabelContactRelationMalePartner": {
      "abstract": [
        {
          "text": "The label for the contact’s male partner.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CNLabelContactRelationMalePartner"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.contacts/documentation/Contacts/CNLabelContactRelationMalePartner",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CNLabelContactRelationMalePartner"
        }
      ],
      "role": "symbol",
      "title": "CNLabelContactRelationMalePartner",
      "type": "topic",
      "url": "/documentation/contacts/cnlabelcontactrelationmalepartner"
    },
    "doc://com.apple.contacts/documentation/Contacts/CNLabelContactRelationMother": {
      "abstract": [
        {
          "text": "The label for the contact’s mother.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CNLabelContactRelationMother"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.contacts/documentation/Contacts/CNLabelContactRelationMother",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CNLabelContactRelationMother"
        }
      ],
      "role": "symbol",
      "title": "CNLabelContactRelationMother",
      "type": "topic",
      "url": "/documentation/contacts/cnlabelcontactrelationmother"
    },
    "doc://com.apple.contacts/documentation/Contacts/CNLabelContactRelationParent": {
      "abstract": [
        {
          "text": "The label for the contact’s parent.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CNLabelContactRelationParent"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.contacts/documentation/Contacts/CNLabelContactRelationParent",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CNLabelContactRelationParent"
        }
      ],
      "role": "symbol",
      "title": "CNLabelContactRelationParent",
      "type": "topic",
      "url": "/documentation/contacts/cnlabelcontactrelationparent"
    },
    "doc://com.apple.contacts/documentation/Contacts/CNLabelContactRelationPartner": {
      "abstract": [
        {
          "text": "The label for the contact’s partner.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CNLabelContactRelationPartner"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.contacts/documentation/Contacts/CNLabelContactRelationPartner",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CNLabelContactRelationPartner"
        }
      ],
      "role": "symbol",
      "title": "CNLabelContactRelationPartner",
      "type": "topic",
      "url": "/documentation/contacts/cnlabelcontactrelationpartner"
    },
    "doc://com.apple.contacts/documentation/Contacts/CNLabelContactRelationSibling": {
      "abstract": [
        {
          "text": "The label for the contact’s sibling.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CNLabelContactRelationSibling"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.contacts/documentation/Contacts/CNLabelContactRelationSibling",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CNLabelContactRelationSibling"
        }
      ],
      "role": "symbol",
      "title": "CNLabelContactRelationSibling",
      "type": "topic",
      "url": "/documentation/contacts/cnlabelcontactrelationsibling"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.externally.resolved.symbol/c:objc(cs)NSString": {
      "abstract": [
        {
          "text": "A static, plain-text Unicode string object which you use when you need reference semantics or other Foundation-specific behavior. ",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "class "
        },
        {
          "kind": "identifier",
          "text": "NSString"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSString",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSString",
      "type": "topic",
      "url": "/documentation/foundation/nsstring"
    },
    "doc://com.externally.resolved.symbol/s:SS": {
      "abstract": [
        {
          "text": "A Unicode string value that is a collection of characters.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@frozen"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "String"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SS",
      "kind": "symbol",
      "role": "symbol",
      "title": "String",
      "type": "topic",
      "url": "/documentation/Swift/String"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Getting-immediate-family-relationship-labels",
      "generated": true,
      "identifiers": [
        "doc://com.apple.contacts/documentation/Contacts/CNLabelContactRelationBrother",
        "doc://com.apple.contacts/documentation/Contacts/CNLabelContactRelationChild",
        "doc://com.apple.contacts/documentation/Contacts/CNLabelContactRelationDaughter",
        "doc://com.apple.contacts/documentation/Contacts/CNLabelContactRelationElderBrother",
        "doc://com.apple.contacts/documentation/Contacts/CNLabelContactRelationElderSibling",
        "doc://com.apple.contacts/documentation/Contacts/CNLabelContactRelationElderSister",
        "doc://com.apple.contacts/documentation/Contacts/CNLabelContactRelationEldestBrother",
        "doc://com.apple.contacts/documentation/Contacts/CNLabelContactRelationFather",
        "doc://com.apple.contacts/documentation/Contacts/CNLabelContactRelationFemalePartner",
        "doc://com.apple.contacts/documentation/Contacts/CNLabelContactRelationHusband",
        "doc://com.apple.contacts/documentation/Contacts/CNLabelContactRelationMalePartner",
        "doc://com.apple.contacts/documentation/Contacts/CNLabelContactRelationMother",
        "doc://com.apple.contacts/documentation/Contacts/CNLabelContactRelationParent",
        "doc://com.apple.contacts/documentation/Contacts/CNLabelContactRelationPartner",
        "doc://com.apple.contacts/documentation/Contacts/CNLabelContactRelationSibling"
      ],
      "title": "Getting immediate family relationship labels"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.1",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.15",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "6.0",
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Global Variable"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "CNLabelContactRelationEldestSister"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "var"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CNLabelContactRelationEldestSister"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.contacts/documentation/Contacts"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Getting-immediate-family-relationship-labels",
              "generated": true,
              "identifiers": [
                "doc://com.apple.contacts/documentation/Contacts/CNLabelContactRelationBrother",
                "doc://com.apple.contacts/documentation/Contacts/CNLabelContactRelationChild",
                "doc://com.apple.contacts/documentation/Contacts/CNLabelContactRelationDaughter",
                "doc://com.apple.contacts/documentation/Contacts/CNLabelContactRelationElderBrother",
                "doc://com.apple.contacts/documentation/Contacts/CNLabelContactRelationElderSibling",
                "doc://com.apple.contacts/documentation/Contacts/CNLabelContactRelationElderSister",
                "doc://com.apple.contacts/documentation/Contacts/CNLabelContactRelationEldestBrother",
                "doc://com.apple.contacts/documentation/Contacts/CNLabelContactRelationFather",
                "doc://com.apple.contacts/documentation/Contacts/CNLabelContactRelationFemalePartner",
                "doc://com.apple.contacts/documentation/Contacts/CNLabelContactRelationHusband",
                "doc://com.apple.contacts/documentation/Contacts/CNLabelContactRelationMalePartner",
                "doc://com.apple.contacts/documentation/Contacts/CNLabelContactRelationMother",
                "doc://com.apple.contacts/documentation/Contacts/CNLabelContactRelationParent",
                "doc://com.apple.contacts/documentation/Contacts/CNLabelContactRelationPartner",
                "doc://com.apple.contacts/documentation/Contacts/CNLabelContactRelationSibling"
              ],
              "title": "Getting immediate family relationship labels"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "extern"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSString",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(cs)NSString",
                    "text": "NSString"
                  },
                  {
                    "kind": "text",
                    "text": " * "
                  },
                  {
                    "kind": "keyword",
                    "text": "const"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "CNLabelContactRelationEldestSister"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.contacts~1documentation~1Contacts~1CNLabelContactRelationEldestBrother/title",
          "value": "CNLabelContactRelationEldestBrother"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.contacts~1documentation~1Contacts~1CNLabelContactRelationEldestBrother/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CNLabelContactRelationEldestBrother"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.contacts~1documentation~1Contacts~1CNLabelContactRelationParent/title",
          "value": "CNLabelContactRelationParent"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.contacts~1documentation~1Contacts~1CNLabelContactRelationParent/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CNLabelContactRelationParent"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.contacts~1documentation~1Contacts~1CNLabelContactRelationBrother/title",
          "value": "CNLabelContactRelationBrother"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.contacts~1documentation~1Contacts~1CNLabelContactRelationBrother/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CNLabelContactRelationBrother"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.contacts~1documentation~1Contacts~1CNLabelContactRelationPartner/title",
          "value": "CNLabelContactRelationPartner"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.contacts~1documentation~1Contacts~1CNLabelContactRelationPartner/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CNLabelContactRelationPartner"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.contacts~1documentation~1Contacts~1CNLabelContactRelationElderBrother/title",
          "value": "CNLabelContactRelationElderBrother"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.contacts~1documentation~1Contacts~1CNLabelContactRelationElderBrother/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CNLabelContactRelationElderBrother"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.contacts~1documentation~1Contacts~1CNLabelContactRelationElderSibling/title",
          "value": "CNLabelContactRelationElderSibling"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.contacts~1documentation~1Contacts~1CNLabelContactRelationElderSibling/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CNLabelContactRelationElderSibling"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.contacts~1documentation~1Contacts~1CNLabelContactRelationDaughter/title",
          "value": "CNLabelContactRelationDaughter"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.contacts~1documentation~1Contacts~1CNLabelContactRelationDaughter/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CNLabelContactRelationDaughter"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:objc(cs)NSString/abstract",
          "value": [
            {
              "text": "A static, plain-text Unicode string object.",
              "type": "text"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.contacts~1documentation~1Contacts~1CNLabelContactRelationHusband/title",
          "value": "CNLabelContactRelationHusband"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.contacts~1documentation~1Contacts~1CNLabelContactRelationHusband/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CNLabelContactRelationHusband"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.contacts~1documentation~1Contacts~1CNLabelContactRelationFemalePartner/title",
          "value": "CNLabelContactRelationFemalePartner"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.contacts~1documentation~1Contacts~1CNLabelContactRelationFemalePartner/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CNLabelContactRelationFemalePartner"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.contacts~1documentation~1Contacts~1CNLabelContactRelationChild/title",
          "value": "CNLabelContactRelationChild"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.contacts~1documentation~1Contacts~1CNLabelContactRelationChild/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CNLabelContactRelationChild"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.contacts~1documentation~1Contacts~1CNLabelContactRelationMalePartner/title",
          "value": "CNLabelContactRelationMalePartner"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.contacts~1documentation~1Contacts~1CNLabelContactRelationMalePartner/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CNLabelContactRelationMalePartner"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.contacts~1documentation~1Contacts~1CNLabelContactRelationMother/title",
          "value": "CNLabelContactRelationMother"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.contacts~1documentation~1Contacts~1CNLabelContactRelationMother/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CNLabelContactRelationMother"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.contacts~1documentation~1Contacts~1CNLabelContactRelationFather/title",
          "value": "CNLabelContactRelationFather"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.contacts~1documentation~1Contacts~1CNLabelContactRelationFather/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CNLabelContactRelationFather"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.contacts~1documentation~1Contacts~1CNLabelContactRelationSibling/title",
          "value": "CNLabelContactRelationSibling"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.contacts~1documentation~1Contacts~1CNLabelContactRelationSibling/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CNLabelContactRelationSibling"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.contacts~1documentation~1Contacts~1CNLabelContactRelationEldestSister/title",
          "value": "CNLabelContactRelationEldestSister"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.contacts~1documentation~1Contacts~1CNLabelContactRelationEldestSister/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CNLabelContactRelationEldestSister"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.contacts~1documentation~1Contacts~1CNLabelContactRelationElderSister/title",
          "value": "CNLabelContactRelationElderSister"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.contacts~1documentation~1Contacts~1CNLabelContactRelationElderSister/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CNLabelContactRelationElderSister"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/contacts/cnlabelcontactrelationeldestsister"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/contacts/cnlabelcontactrelationeldestsister"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
