{
  "abstract": [
    {
      "text": "The label for the contact’s wife’s sister.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.contacts/documentation/Contacts"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.contacts/documentation/Contacts/CNLabelContactRelationSisterInLawWifesSister"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@CNLabelContactRelationSisterInLawWifesSister",
    "fragments": [
      {
        "kind": "keyword",
        "text": "let"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "CNLabelContactRelationSisterInLawWifesSister"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "s:SS",
        "text": "String"
      }
    ],
    "modules": [
      {
        "name": "Contacts"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "CNLabelContactRelationSisterInLawWifesSister"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.1",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.15",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "6.0",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Global Variable",
    "symbolKind": "var",
    "title": "CNLabelContactRelationSisterInLawWifesSister"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "let"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "CNLabelContactRelationSisterInLawWifesSister"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:SS",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:SS",
              "text": "String"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.contacts/documentation/Contacts": {
      "abstract": [
        {
          "text": "Access the user’s contacts, and format and localize contact information.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.contacts/documentation/Contacts",
      "kind": "symbol",
      "role": "collection",
      "title": "Contacts",
      "type": "topic",
      "url": "/documentation/contacts"
    },
    "doc://com.apple.contacts/documentation/Contacts/CNLabelContactRelationBrotherInLaw": {
      "abstract": [
        {
          "text": "The label for the contact’s brother-in-law.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CNLabelContactRelationBrotherInLaw"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.contacts/documentation/Contacts/CNLabelContactRelationBrotherInLaw",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CNLabelContactRelationBrotherInLaw"
        }
      ],
      "role": "symbol",
      "title": "CNLabelContactRelationBrotherInLaw",
      "type": "topic",
      "url": "/documentation/contacts/cnlabelcontactrelationbrotherinlaw"
    },
    "doc://com.apple.contacts/documentation/Contacts/CNLabelContactRelationBrotherInLawElderSistersHusband": {
      "abstract": [
        {
          "text": "The label for the contact’s elder sister’s husband.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CNLabelContactRelationBrotherInLawElderSistersHusband"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.contacts/documentation/Contacts/CNLabelContactRelationBrotherInLawElderSistersHusband",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CNLabelContactRelationBrotherInLawElderSistersHusband"
        }
      ],
      "role": "symbol",
      "title": "CNLabelContactRelationBrotherInLawElderSistersHusband",
      "type": "topic",
      "url": "/documentation/contacts/cnlabelcontactrelationbrotherinlaweldersistershusband"
    },
    "doc://com.apple.contacts/documentation/Contacts/CNLabelContactRelationBrotherInLawHusbandsBrother": {
      "abstract": [
        {
          "text": "The label for the contact’s husband’s brother.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CNLabelContactRelationBrotherInLawHusbandsBrother"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.contacts/documentation/Contacts/CNLabelContactRelationBrotherInLawHusbandsBrother",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CNLabelContactRelationBrotherInLawHusbandsBrother"
        }
      ],
      "role": "symbol",
      "title": "CNLabelContactRelationBrotherInLawHusbandsBrother",
      "type": "topic",
      "url": "/documentation/contacts/cnlabelcontactrelationbrotherinlawhusbandsbrother"
    },
    "doc://com.apple.contacts/documentation/Contacts/CNLabelContactRelationBrotherInLawHusbandsSistersHusband": {
      "abstract": [
        {
          "text": "The label for the contact’s husband’s sister’s husband.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CNLabelContactRelationBrotherInLawHusbandsSistersHusband"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.contacts/documentation/Contacts/CNLabelContactRelationBrotherInLawHusbandsSistersHusband",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CNLabelContactRelationBrotherInLawHusbandsSistersHusband"
        }
      ],
      "role": "symbol",
      "title": "CNLabelContactRelationBrotherInLawHusbandsSistersHusband",
      "type": "topic",
      "url": "/documentation/contacts/cnlabelcontactrelationbrotherinlawhusbandssistershusband"
    },
    "doc://com.apple.contacts/documentation/Contacts/CNLabelContactRelationBrotherInLawSistersHusband": {
      "abstract": [
        {
          "text": "The label for the contact’s sister’s husband.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CNLabelContactRelationBrotherInLawSistersHusband"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.contacts/documentation/Contacts/CNLabelContactRelationBrotherInLawSistersHusband",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CNLabelContactRelationBrotherInLawSistersHusband"
        }
      ],
      "role": "symbol",
      "title": "CNLabelContactRelationBrotherInLawSistersHusband",
      "type": "topic",
      "url": "/documentation/contacts/cnlabelcontactrelationbrotherinlawsistershusband"
    },
    "doc://com.apple.contacts/documentation/Contacts/CNLabelContactRelationBrotherInLawSpousesBrother": {
      "abstract": [
        {
          "text": "The label for the contact’s spouse’s brother.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CNLabelContactRelationBrotherInLawSpousesBrother"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.contacts/documentation/Contacts/CNLabelContactRelationBrotherInLawSpousesBrother",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CNLabelContactRelationBrotherInLawSpousesBrother"
        }
      ],
      "role": "symbol",
      "title": "CNLabelContactRelationBrotherInLawSpousesBrother",
      "type": "topic",
      "url": "/documentation/contacts/cnlabelcontactrelationbrotherinlawspousesbrother"
    },
    "doc://com.apple.contacts/documentation/Contacts/CNLabelContactRelationBrotherInLawWifesBrother": {
      "abstract": [
        {
          "text": "The label for the contact’s wife’s brother.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CNLabelContactRelationBrotherInLawWifesBrother"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.contacts/documentation/Contacts/CNLabelContactRelationBrotherInLawWifesBrother",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CNLabelContactRelationBrotherInLawWifesBrother"
        }
      ],
      "role": "symbol",
      "title": "CNLabelContactRelationBrotherInLawWifesBrother",
      "type": "topic",
      "url": "/documentation/contacts/cnlabelcontactrelationbrotherinlawwifesbrother"
    },
    "doc://com.apple.contacts/documentation/Contacts/CNLabelContactRelationBrotherInLawWifesSistersHusband": {
      "abstract": [
        {
          "text": "The label for the contact’s wife’s sister’s husband.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CNLabelContactRelationBrotherInLawWifesSistersHusband"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.contacts/documentation/Contacts/CNLabelContactRelationBrotherInLawWifesSistersHusband",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CNLabelContactRelationBrotherInLawWifesSistersHusband"
        }
      ],
      "role": "symbol",
      "title": "CNLabelContactRelationBrotherInLawWifesSistersHusband",
      "type": "topic",
      "url": "/documentation/contacts/cnlabelcontactrelationbrotherinlawwifessistershusband"
    },
    "doc://com.apple.contacts/documentation/Contacts/CNLabelContactRelationBrotherInLawYoungerSistersHusband": {
      "abstract": [
        {
          "text": "The label for the contact’s younger sister’s husband.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CNLabelContactRelationBrotherInLawYoungerSistersHusband"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.contacts/documentation/Contacts/CNLabelContactRelationBrotherInLawYoungerSistersHusband",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CNLabelContactRelationBrotherInLawYoungerSistersHusband"
        }
      ],
      "role": "symbol",
      "title": "CNLabelContactRelationBrotherInLawYoungerSistersHusband",
      "type": "topic",
      "url": "/documentation/contacts/cnlabelcontactrelationbrotherinlawyoungersistershusband"
    },
    "doc://com.apple.contacts/documentation/Contacts/CNLabelContactRelationChildInLaw": {
      "abstract": [
        {
          "text": "The label for the contact’s child-in-law.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CNLabelContactRelationChildInLaw"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.contacts/documentation/Contacts/CNLabelContactRelationChildInLaw",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CNLabelContactRelationChildInLaw"
        }
      ],
      "role": "symbol",
      "title": "CNLabelContactRelationChildInLaw",
      "type": "topic",
      "url": "/documentation/contacts/cnlabelcontactrelationchildinlaw"
    },
    "doc://com.apple.contacts/documentation/Contacts/CNLabelContactRelationCoBrotherInLaw": {
      "abstract": [
        {
          "text": "The label for the contact’s co-brother-in-law.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CNLabelContactRelationCoBrotherInLaw"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.contacts/documentation/Contacts/CNLabelContactRelationCoBrotherInLaw",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CNLabelContactRelationCoBrotherInLaw"
        }
      ],
      "role": "symbol",
      "title": "CNLabelContactRelationCoBrotherInLaw",
      "type": "topic",
      "url": "/documentation/contacts/cnlabelcontactrelationcobrotherinlaw"
    },
    "doc://com.apple.contacts/documentation/Contacts/CNLabelContactRelationCoFatherInLaw": {
      "abstract": [
        {
          "text": "The label for the contact’s co-father-in-law.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CNLabelContactRelationCoFatherInLaw"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.contacts/documentation/Contacts/CNLabelContactRelationCoFatherInLaw",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CNLabelContactRelationCoFatherInLaw"
        }
      ],
      "role": "symbol",
      "title": "CNLabelContactRelationCoFatherInLaw",
      "type": "topic",
      "url": "/documentation/contacts/cnlabelcontactrelationcofatherinlaw"
    },
    "doc://com.apple.contacts/documentation/Contacts/CNLabelContactRelationCoMotherInLaw": {
      "abstract": [
        {
          "text": "The label for the contact’s co-mother-in-law.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CNLabelContactRelationCoMotherInLaw"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.contacts/documentation/Contacts/CNLabelContactRelationCoMotherInLaw",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CNLabelContactRelationCoMotherInLaw"
        }
      ],
      "role": "symbol",
      "title": "CNLabelContactRelationCoMotherInLaw",
      "type": "topic",
      "url": "/documentation/contacts/cnlabelcontactrelationcomotherinlaw"
    },
    "doc://com.apple.contacts/documentation/Contacts/CNLabelContactRelationCoParentInLaw": {
      "abstract": [
        {
          "text": "The label for the contact’s co-parent-in-law.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CNLabelContactRelationCoParentInLaw"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.contacts/documentation/Contacts/CNLabelContactRelationCoParentInLaw",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CNLabelContactRelationCoParentInLaw"
        }
      ],
      "role": "symbol",
      "title": "CNLabelContactRelationCoParentInLaw",
      "type": "topic",
      "url": "/documentation/contacts/cnlabelcontactrelationcoparentinlaw"
    },
    "doc://com.apple.contacts/documentation/Contacts/CNLabelContactRelationCoSiblingInLaw": {
      "abstract": [
        {
          "text": "The label for the contact’s co-sibling-in-law.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CNLabelContactRelationCoSiblingInLaw"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.contacts/documentation/Contacts/CNLabelContactRelationCoSiblingInLaw",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CNLabelContactRelationCoSiblingInLaw"
        }
      ],
      "role": "symbol",
      "title": "CNLabelContactRelationCoSiblingInLaw",
      "type": "topic",
      "url": "/documentation/contacts/cnlabelcontactrelationcosiblinginlaw"
    },
    "doc://com.apple.contacts/documentation/Contacts/CNLabelContactRelationSisterInLawWifesSister": {
      "abstract": [
        {
          "text": "The label for the contact’s wife’s sister.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CNLabelContactRelationSisterInLawWifesSister"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.contacts/documentation/Contacts/CNLabelContactRelationSisterInLawWifesSister",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CNLabelContactRelationSisterInLawWifesSister"
        }
      ],
      "role": "symbol",
      "title": "CNLabelContactRelationSisterInLawWifesSister",
      "type": "topic",
      "url": "/documentation/contacts/cnlabelcontactrelationsisterinlawwifessister"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.externally.resolved.symbol/c:objc(cs)NSString": {
      "abstract": [
        {
          "text": "A static, plain-text Unicode string object which you use when you need reference semantics or other Foundation-specific behavior. ",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "class "
        },
        {
          "kind": "identifier",
          "text": "NSString"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSString",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSString",
      "type": "topic",
      "url": "/documentation/foundation/nsstring"
    },
    "doc://com.externally.resolved.symbol/s:SS": {
      "abstract": [
        {
          "text": "A Unicode string value that is a collection of characters.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@frozen"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "String"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SS",
      "kind": "symbol",
      "role": "symbol",
      "title": "String",
      "type": "topic",
      "url": "/documentation/Swift/String"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Getting-in-law-relationship-labels",
      "generated": true,
      "identifiers": [
        "doc://com.apple.contacts/documentation/Contacts/CNLabelContactRelationBrotherInLaw",
        "doc://com.apple.contacts/documentation/Contacts/CNLabelContactRelationBrotherInLawElderSistersHusband",
        "doc://com.apple.contacts/documentation/Contacts/CNLabelContactRelationBrotherInLawHusbandsBrother",
        "doc://com.apple.contacts/documentation/Contacts/CNLabelContactRelationBrotherInLawHusbandsSistersHusband",
        "doc://com.apple.contacts/documentation/Contacts/CNLabelContactRelationBrotherInLawSistersHusband",
        "doc://com.apple.contacts/documentation/Contacts/CNLabelContactRelationBrotherInLawSpousesBrother",
        "doc://com.apple.contacts/documentation/Contacts/CNLabelContactRelationBrotherInLawWifesBrother",
        "doc://com.apple.contacts/documentation/Contacts/CNLabelContactRelationBrotherInLawWifesSistersHusband",
        "doc://com.apple.contacts/documentation/Contacts/CNLabelContactRelationBrotherInLawYoungerSistersHusband",
        "doc://com.apple.contacts/documentation/Contacts/CNLabelContactRelationChildInLaw",
        "doc://com.apple.contacts/documentation/Contacts/CNLabelContactRelationCoBrotherInLaw",
        "doc://com.apple.contacts/documentation/Contacts/CNLabelContactRelationCoFatherInLaw",
        "doc://com.apple.contacts/documentation/Contacts/CNLabelContactRelationCoMotherInLaw",
        "doc://com.apple.contacts/documentation/Contacts/CNLabelContactRelationCoParentInLaw",
        "doc://com.apple.contacts/documentation/Contacts/CNLabelContactRelationCoSiblingInLaw"
      ],
      "title": "Getting in-law relationship labels"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.1",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.15",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "6.0",
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Global Variable"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "CNLabelContactRelationSisterInLawWifesSister"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "var"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CNLabelContactRelationSisterInLawWifesSister"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.contacts/documentation/Contacts"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Getting-in-law-relationship-labels",
              "generated": true,
              "identifiers": [
                "doc://com.apple.contacts/documentation/Contacts/CNLabelContactRelationBrotherInLaw",
                "doc://com.apple.contacts/documentation/Contacts/CNLabelContactRelationBrotherInLawElderSistersHusband",
                "doc://com.apple.contacts/documentation/Contacts/CNLabelContactRelationBrotherInLawHusbandsBrother",
                "doc://com.apple.contacts/documentation/Contacts/CNLabelContactRelationBrotherInLawHusbandsSistersHusband",
                "doc://com.apple.contacts/documentation/Contacts/CNLabelContactRelationBrotherInLawSistersHusband",
                "doc://com.apple.contacts/documentation/Contacts/CNLabelContactRelationBrotherInLawSpousesBrother",
                "doc://com.apple.contacts/documentation/Contacts/CNLabelContactRelationBrotherInLawWifesBrother",
                "doc://com.apple.contacts/documentation/Contacts/CNLabelContactRelationBrotherInLawWifesSistersHusband",
                "doc://com.apple.contacts/documentation/Contacts/CNLabelContactRelationBrotherInLawYoungerSistersHusband",
                "doc://com.apple.contacts/documentation/Contacts/CNLabelContactRelationChildInLaw",
                "doc://com.apple.contacts/documentation/Contacts/CNLabelContactRelationCoBrotherInLaw",
                "doc://com.apple.contacts/documentation/Contacts/CNLabelContactRelationCoFatherInLaw",
                "doc://com.apple.contacts/documentation/Contacts/CNLabelContactRelationCoMotherInLaw",
                "doc://com.apple.contacts/documentation/Contacts/CNLabelContactRelationCoParentInLaw",
                "doc://com.apple.contacts/documentation/Contacts/CNLabelContactRelationCoSiblingInLaw"
              ],
              "title": "Getting in-law relationship labels"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "extern"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSString",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(cs)NSString",
                    "text": "NSString"
                  },
                  {
                    "kind": "text",
                    "text": " * "
                  },
                  {
                    "kind": "keyword",
                    "text": "const"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "CNLabelContactRelationSisterInLawWifesSister"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.contacts~1documentation~1Contacts~1CNLabelContactRelationChildInLaw/title",
          "value": "CNLabelContactRelationChildInLaw"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.contacts~1documentation~1Contacts~1CNLabelContactRelationChildInLaw/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CNLabelContactRelationChildInLaw"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.contacts~1documentation~1Contacts~1CNLabelContactRelationBrotherInLawElderSistersHusband/title",
          "value": "CNLabelContactRelationBrotherInLawElderSistersHusband"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.contacts~1documentation~1Contacts~1CNLabelContactRelationBrotherInLawElderSistersHusband/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CNLabelContactRelationBrotherInLawElderSistersHusband"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.contacts~1documentation~1Contacts~1CNLabelContactRelationBrotherInLaw/title",
          "value": "CNLabelContactRelationBrotherInLaw"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.contacts~1documentation~1Contacts~1CNLabelContactRelationBrotherInLaw/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CNLabelContactRelationBrotherInLaw"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.contacts~1documentation~1Contacts~1CNLabelContactRelationCoMotherInLaw/title",
          "value": "CNLabelContactRelationCoMotherInLaw"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.contacts~1documentation~1Contacts~1CNLabelContactRelationCoMotherInLaw/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CNLabelContactRelationCoMotherInLaw"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.contacts~1documentation~1Contacts~1CNLabelContactRelationCoFatherInLaw/title",
          "value": "CNLabelContactRelationCoFatherInLaw"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.contacts~1documentation~1Contacts~1CNLabelContactRelationCoFatherInLaw/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CNLabelContactRelationCoFatherInLaw"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.contacts~1documentation~1Contacts~1CNLabelContactRelationBrotherInLawHusbandsSistersHusband/title",
          "value": "CNLabelContactRelationBrotherInLawHusbandsSistersHusband"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.contacts~1documentation~1Contacts~1CNLabelContactRelationBrotherInLawHusbandsSistersHusband/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CNLabelContactRelationBrotherInLawHusbandsSistersHusband"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:objc(cs)NSString/abstract",
          "value": [
            {
              "text": "A static, plain-text Unicode string object.",
              "type": "text"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.contacts~1documentation~1Contacts~1CNLabelContactRelationBrotherInLawWifesBrother/title",
          "value": "CNLabelContactRelationBrotherInLawWifesBrother"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.contacts~1documentation~1Contacts~1CNLabelContactRelationBrotherInLawWifesBrother/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CNLabelContactRelationBrotherInLawWifesBrother"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.contacts~1documentation~1Contacts~1CNLabelContactRelationBrotherInLawWifesSistersHusband/title",
          "value": "CNLabelContactRelationBrotherInLawWifesSistersHusband"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.contacts~1documentation~1Contacts~1CNLabelContactRelationBrotherInLawWifesSistersHusband/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CNLabelContactRelationBrotherInLawWifesSistersHusband"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.contacts~1documentation~1Contacts~1CNLabelContactRelationSisterInLawWifesSister/title",
          "value": "CNLabelContactRelationSisterInLawWifesSister"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.contacts~1documentation~1Contacts~1CNLabelContactRelationSisterInLawWifesSister/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CNLabelContactRelationSisterInLawWifesSister"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.contacts~1documentation~1Contacts~1CNLabelContactRelationBrotherInLawYoungerSistersHusband/title",
          "value": "CNLabelContactRelationBrotherInLawYoungerSistersHusband"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.contacts~1documentation~1Contacts~1CNLabelContactRelationBrotherInLawYoungerSistersHusband/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CNLabelContactRelationBrotherInLawYoungerSistersHusband"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.contacts~1documentation~1Contacts~1CNLabelContactRelationBrotherInLawSistersHusband/title",
          "value": "CNLabelContactRelationBrotherInLawSistersHusband"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.contacts~1documentation~1Contacts~1CNLabelContactRelationBrotherInLawSistersHusband/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CNLabelContactRelationBrotherInLawSistersHusband"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.contacts~1documentation~1Contacts~1CNLabelContactRelationCoBrotherInLaw/title",
          "value": "CNLabelContactRelationCoBrotherInLaw"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.contacts~1documentation~1Contacts~1CNLabelContactRelationCoBrotherInLaw/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CNLabelContactRelationCoBrotherInLaw"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.contacts~1documentation~1Contacts~1CNLabelContactRelationCoSiblingInLaw/title",
          "value": "CNLabelContactRelationCoSiblingInLaw"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.contacts~1documentation~1Contacts~1CNLabelContactRelationCoSiblingInLaw/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CNLabelContactRelationCoSiblingInLaw"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.contacts~1documentation~1Contacts~1CNLabelContactRelationBrotherInLawSpousesBrother/title",
          "value": "CNLabelContactRelationBrotherInLawSpousesBrother"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.contacts~1documentation~1Contacts~1CNLabelContactRelationBrotherInLawSpousesBrother/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CNLabelContactRelationBrotherInLawSpousesBrother"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.contacts~1documentation~1Contacts~1CNLabelContactRelationCoParentInLaw/title",
          "value": "CNLabelContactRelationCoParentInLaw"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.contacts~1documentation~1Contacts~1CNLabelContactRelationCoParentInLaw/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CNLabelContactRelationCoParentInLaw"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.contacts~1documentation~1Contacts~1CNLabelContactRelationBrotherInLawHusbandsBrother/title",
          "value": "CNLabelContactRelationBrotherInLawHusbandsBrother"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.contacts~1documentation~1Contacts~1CNLabelContactRelationBrotherInLawHusbandsBrother/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CNLabelContactRelationBrotherInLawHusbandsBrother"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/contacts/cnlabelcontactrelationsisterinlawwifessister"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/contacts/cnlabelcontactrelationsisterinlawwifessister"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
