{
  "abstract": [
    {
      "text": "The label for the contact’s son-in-law or stepson.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.contacts/documentation/Contacts"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.contacts/documentation/Contacts/CNLabelContactRelationSonInLawOrStepson"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@CNLabelContactRelationSonInLawOrStepson",
    "fragments": [
      {
        "kind": "keyword",
        "text": "let"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "CNLabelContactRelationSonInLawOrStepson"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "s:SS",
        "text": "String"
      }
    ],
    "modules": [
      {
        "name": "Contacts"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "CNLabelContactRelationSonInLawOrStepson"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.1",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.15",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "6.0",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Global Variable",
    "symbolKind": "var",
    "title": "CNLabelContactRelationSonInLawOrStepson"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "let"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "CNLabelContactRelationSonInLawOrStepson"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:SS",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:SS",
              "text": "String"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.contacts/documentation/Contacts": {
      "abstract": [
        {
          "text": "Access the user’s contacts, and format and localize contact information.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.contacts/documentation/Contacts",
      "kind": "symbol",
      "role": "collection",
      "title": "Contacts",
      "type": "topic",
      "url": "/documentation/contacts"
    },
    "doc://com.apple.contacts/documentation/Contacts/CNLabelContactRelationAunt": {
      "abstract": [
        {
          "text": "The label for the contact’s aunt.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CNLabelContactRelationAunt"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.contacts/documentation/Contacts/CNLabelContactRelationAunt",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CNLabelContactRelationAunt"
        }
      ],
      "role": "symbol",
      "title": "CNLabelContactRelationAunt",
      "type": "topic",
      "url": "/documentation/contacts/cnlabelcontactrelationaunt"
    },
    "doc://com.apple.contacts/documentation/Contacts/CNLabelContactRelationAuntFathersBrothersWife": {
      "abstract": [
        {
          "text": "The label for the contact’s father’s brother’s wife.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CNLabelContactRelationAuntFathersBrothersWife"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.contacts/documentation/Contacts/CNLabelContactRelationAuntFathersBrothersWife",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CNLabelContactRelationAuntFathersBrothersWife"
        }
      ],
      "role": "symbol",
      "title": "CNLabelContactRelationAuntFathersBrothersWife",
      "type": "topic",
      "url": "/documentation/contacts/cnlabelcontactrelationauntfathersbrotherswife"
    },
    "doc://com.apple.contacts/documentation/Contacts/CNLabelContactRelationAuntFathersElderBrothersWife": {
      "abstract": [
        {
          "text": "The label for the contact’s father’s elder brother’s wife.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CNLabelContactRelationAuntFathersElderBrothersWife"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.contacts/documentation/Contacts/CNLabelContactRelationAuntFathersElderBrothersWife",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CNLabelContactRelationAuntFathersElderBrothersWife"
        }
      ],
      "role": "symbol",
      "title": "CNLabelContactRelationAuntFathersElderBrothersWife",
      "type": "topic",
      "url": "/documentation/contacts/cnlabelcontactrelationauntfatherselderbrotherswife"
    },
    "doc://com.apple.contacts/documentation/Contacts/CNLabelContactRelationAuntFathersElderSister": {
      "abstract": [
        {
          "text": "The label for the contact’s father’s elder sister.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CNLabelContactRelationAuntFathersElderSister"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.contacts/documentation/Contacts/CNLabelContactRelationAuntFathersElderSister",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CNLabelContactRelationAuntFathersElderSister"
        }
      ],
      "role": "symbol",
      "title": "CNLabelContactRelationAuntFathersElderSister",
      "type": "topic",
      "url": "/documentation/contacts/cnlabelcontactrelationauntfatherseldersister"
    },
    "doc://com.apple.contacts/documentation/Contacts/CNLabelContactRelationAuntFathersSister": {
      "abstract": [
        {
          "text": "The label for the contact’s father’s sister.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CNLabelContactRelationAuntFathersSister"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.contacts/documentation/Contacts/CNLabelContactRelationAuntFathersSister",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CNLabelContactRelationAuntFathersSister"
        }
      ],
      "role": "symbol",
      "title": "CNLabelContactRelationAuntFathersSister",
      "type": "topic",
      "url": "/documentation/contacts/cnlabelcontactrelationauntfatherssister"
    },
    "doc://com.apple.contacts/documentation/Contacts/CNLabelContactRelationAuntFathersYoungerBrothersWife": {
      "abstract": [
        {
          "text": "The label for the contact’s father’s younger brother’s wife.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CNLabelContactRelationAuntFathersYoungerBrothersWife"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.contacts/documentation/Contacts/CNLabelContactRelationAuntFathersYoungerBrothersWife",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CNLabelContactRelationAuntFathersYoungerBrothersWife"
        }
      ],
      "role": "symbol",
      "title": "CNLabelContactRelationAuntFathersYoungerBrothersWife",
      "type": "topic",
      "url": "/documentation/contacts/cnlabelcontactrelationauntfathersyoungerbrotherswife"
    },
    "doc://com.apple.contacts/documentation/Contacts/CNLabelContactRelationAuntFathersYoungerSister": {
      "abstract": [
        {
          "text": "The label for the contact’s father’s younger sister.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CNLabelContactRelationAuntFathersYoungerSister"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.contacts/documentation/Contacts/CNLabelContactRelationAuntFathersYoungerSister",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CNLabelContactRelationAuntFathersYoungerSister"
        }
      ],
      "role": "symbol",
      "title": "CNLabelContactRelationAuntFathersYoungerSister",
      "type": "topic",
      "url": "/documentation/contacts/cnlabelcontactrelationauntfathersyoungersister"
    },
    "doc://com.apple.contacts/documentation/Contacts/CNLabelContactRelationAuntMothersBrothersWife": {
      "abstract": [
        {
          "text": "The label for the contact’s mother’s brother’s wife.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CNLabelContactRelationAuntMothersBrothersWife"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.contacts/documentation/Contacts/CNLabelContactRelationAuntMothersBrothersWife",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CNLabelContactRelationAuntMothersBrothersWife"
        }
      ],
      "role": "symbol",
      "title": "CNLabelContactRelationAuntMothersBrothersWife",
      "type": "topic",
      "url": "/documentation/contacts/cnlabelcontactrelationauntmothersbrotherswife"
    },
    "doc://com.apple.contacts/documentation/Contacts/CNLabelContactRelationAuntMothersElderSister": {
      "abstract": [
        {
          "text": "The label for the contact’s mother’s elder sister.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CNLabelContactRelationAuntMothersElderSister"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.contacts/documentation/Contacts/CNLabelContactRelationAuntMothersElderSister",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CNLabelContactRelationAuntMothersElderSister"
        }
      ],
      "role": "symbol",
      "title": "CNLabelContactRelationAuntMothersElderSister",
      "type": "topic",
      "url": "/documentation/contacts/cnlabelcontactrelationauntmotherseldersister"
    },
    "doc://com.apple.contacts/documentation/Contacts/CNLabelContactRelationAuntMothersSister": {
      "abstract": [
        {
          "text": "The label for the contact’s mother’s sister.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CNLabelContactRelationAuntMothersSister"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.contacts/documentation/Contacts/CNLabelContactRelationAuntMothersSister",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CNLabelContactRelationAuntMothersSister"
        }
      ],
      "role": "symbol",
      "title": "CNLabelContactRelationAuntMothersSister",
      "type": "topic",
      "url": "/documentation/contacts/cnlabelcontactrelationauntmotherssister"
    },
    "doc://com.apple.contacts/documentation/Contacts/CNLabelContactRelationAuntMothersYoungerSister": {
      "abstract": [
        {
          "text": "The label for the contact’s mother’s younger sister.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CNLabelContactRelationAuntMothersYoungerSister"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.contacts/documentation/Contacts/CNLabelContactRelationAuntMothersYoungerSister",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CNLabelContactRelationAuntMothersYoungerSister"
        }
      ],
      "role": "symbol",
      "title": "CNLabelContactRelationAuntMothersYoungerSister",
      "type": "topic",
      "url": "/documentation/contacts/cnlabelcontactrelationauntmothersyoungersister"
    },
    "doc://com.apple.contacts/documentation/Contacts/CNLabelContactRelationAuntParentsElderSister": {
      "abstract": [
        {
          "text": "The label for the contact’s parent’s elder sister.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CNLabelContactRelationAuntParentsElderSister"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.contacts/documentation/Contacts/CNLabelContactRelationAuntParentsElderSister",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CNLabelContactRelationAuntParentsElderSister"
        }
      ],
      "role": "symbol",
      "title": "CNLabelContactRelationAuntParentsElderSister",
      "type": "topic",
      "url": "/documentation/contacts/cnlabelcontactrelationauntparentseldersister"
    },
    "doc://com.apple.contacts/documentation/Contacts/CNLabelContactRelationAuntParentsSister": {
      "abstract": [
        {
          "text": "The label for the contact’s parent’s sister.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CNLabelContactRelationAuntParentsSister"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.contacts/documentation/Contacts/CNLabelContactRelationAuntParentsSister",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CNLabelContactRelationAuntParentsSister"
        }
      ],
      "role": "symbol",
      "title": "CNLabelContactRelationAuntParentsSister",
      "type": "topic",
      "url": "/documentation/contacts/cnlabelcontactrelationauntparentssister"
    },
    "doc://com.apple.contacts/documentation/Contacts/CNLabelContactRelationAuntParentsYoungerSister": {
      "abstract": [
        {
          "text": "The label for the contact’s parent’s younger sister.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CNLabelContactRelationAuntParentsYoungerSister"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.contacts/documentation/Contacts/CNLabelContactRelationAuntParentsYoungerSister",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CNLabelContactRelationAuntParentsYoungerSister"
        }
      ],
      "role": "symbol",
      "title": "CNLabelContactRelationAuntParentsYoungerSister",
      "type": "topic",
      "url": "/documentation/contacts/cnlabelcontactrelationauntparentsyoungersister"
    },
    "doc://com.apple.contacts/documentation/Contacts/CNLabelContactRelationCousin": {
      "abstract": [
        {
          "text": "The label for the contact’s cousin.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CNLabelContactRelationCousin"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.contacts/documentation/Contacts/CNLabelContactRelationCousin",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CNLabelContactRelationCousin"
        }
      ],
      "role": "symbol",
      "title": "CNLabelContactRelationCousin",
      "type": "topic",
      "url": "/documentation/contacts/cnlabelcontactrelationcousin"
    },
    "doc://com.apple.contacts/documentation/Contacts/CNLabelContactRelationSonInLawOrStepson": {
      "abstract": [
        {
          "text": "The label for the contact’s son-in-law or stepson.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CNLabelContactRelationSonInLawOrStepson"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.contacts/documentation/Contacts/CNLabelContactRelationSonInLawOrStepson",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CNLabelContactRelationSonInLawOrStepson"
        }
      ],
      "role": "symbol",
      "title": "CNLabelContactRelationSonInLawOrStepson",
      "type": "topic",
      "url": "/documentation/contacts/cnlabelcontactrelationsoninlaworstepson"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.externally.resolved.symbol/c:objc(cs)NSString": {
      "abstract": [
        {
          "text": "A static, plain-text Unicode string object which you use when you need reference semantics or other Foundation-specific behavior. ",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "class "
        },
        {
          "kind": "identifier",
          "text": "NSString"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSString",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSString",
      "type": "topic",
      "url": "/documentation/foundation/nsstring"
    },
    "doc://com.externally.resolved.symbol/s:SS": {
      "abstract": [
        {
          "text": "A Unicode string value that is a collection of characters.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@frozen"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "String"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SS",
      "kind": "symbol",
      "role": "symbol",
      "title": "String",
      "type": "topic",
      "url": "/documentation/Swift/String"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Getting-extended-family-relationship-labels",
      "generated": true,
      "identifiers": [
        "doc://com.apple.contacts/documentation/Contacts/CNLabelContactRelationAunt",
        "doc://com.apple.contacts/documentation/Contacts/CNLabelContactRelationAuntFathersBrothersWife",
        "doc://com.apple.contacts/documentation/Contacts/CNLabelContactRelationAuntFathersElderBrothersWife",
        "doc://com.apple.contacts/documentation/Contacts/CNLabelContactRelationAuntFathersElderSister",
        "doc://com.apple.contacts/documentation/Contacts/CNLabelContactRelationAuntFathersSister",
        "doc://com.apple.contacts/documentation/Contacts/CNLabelContactRelationAuntFathersYoungerBrothersWife",
        "doc://com.apple.contacts/documentation/Contacts/CNLabelContactRelationAuntFathersYoungerSister",
        "doc://com.apple.contacts/documentation/Contacts/CNLabelContactRelationAuntMothersBrothersWife",
        "doc://com.apple.contacts/documentation/Contacts/CNLabelContactRelationAuntMothersElderSister",
        "doc://com.apple.contacts/documentation/Contacts/CNLabelContactRelationAuntMothersSister",
        "doc://com.apple.contacts/documentation/Contacts/CNLabelContactRelationAuntMothersYoungerSister",
        "doc://com.apple.contacts/documentation/Contacts/CNLabelContactRelationAuntParentsElderSister",
        "doc://com.apple.contacts/documentation/Contacts/CNLabelContactRelationAuntParentsSister",
        "doc://com.apple.contacts/documentation/Contacts/CNLabelContactRelationAuntParentsYoungerSister",
        "doc://com.apple.contacts/documentation/Contacts/CNLabelContactRelationCousin"
      ],
      "title": "Getting extended family relationship labels"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.1",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.15",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "6.0",
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Global Variable"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "CNLabelContactRelationSonInLawOrStepson"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "var"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CNLabelContactRelationSonInLawOrStepson"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.contacts/documentation/Contacts"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Getting-extended-family-relationship-labels",
              "generated": true,
              "identifiers": [
                "doc://com.apple.contacts/documentation/Contacts/CNLabelContactRelationAunt",
                "doc://com.apple.contacts/documentation/Contacts/CNLabelContactRelationAuntFathersBrothersWife",
                "doc://com.apple.contacts/documentation/Contacts/CNLabelContactRelationAuntFathersElderBrothersWife",
                "doc://com.apple.contacts/documentation/Contacts/CNLabelContactRelationAuntFathersElderSister",
                "doc://com.apple.contacts/documentation/Contacts/CNLabelContactRelationAuntFathersSister",
                "doc://com.apple.contacts/documentation/Contacts/CNLabelContactRelationAuntFathersYoungerBrothersWife",
                "doc://com.apple.contacts/documentation/Contacts/CNLabelContactRelationAuntFathersYoungerSister",
                "doc://com.apple.contacts/documentation/Contacts/CNLabelContactRelationAuntMothersBrothersWife",
                "doc://com.apple.contacts/documentation/Contacts/CNLabelContactRelationAuntMothersElderSister",
                "doc://com.apple.contacts/documentation/Contacts/CNLabelContactRelationAuntMothersSister",
                "doc://com.apple.contacts/documentation/Contacts/CNLabelContactRelationAuntMothersYoungerSister",
                "doc://com.apple.contacts/documentation/Contacts/CNLabelContactRelationAuntParentsElderSister",
                "doc://com.apple.contacts/documentation/Contacts/CNLabelContactRelationAuntParentsSister",
                "doc://com.apple.contacts/documentation/Contacts/CNLabelContactRelationAuntParentsYoungerSister",
                "doc://com.apple.contacts/documentation/Contacts/CNLabelContactRelationCousin"
              ],
              "title": "Getting extended family relationship labels"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "extern"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSString",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(cs)NSString",
                    "text": "NSString"
                  },
                  {
                    "kind": "text",
                    "text": " * "
                  },
                  {
                    "kind": "keyword",
                    "text": "const"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "CNLabelContactRelationSonInLawOrStepson"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.contacts~1documentation~1Contacts~1CNLabelContactRelationAuntFathersBrothersWife/title",
          "value": "CNLabelContactRelationAuntFathersBrothersWife"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.contacts~1documentation~1Contacts~1CNLabelContactRelationAuntFathersBrothersWife/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CNLabelContactRelationAuntFathersBrothersWife"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:objc(cs)NSString/abstract",
          "value": [
            {
              "text": "A static, plain-text Unicode string object.",
              "type": "text"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.contacts~1documentation~1Contacts~1CNLabelContactRelationSonInLawOrStepson/title",
          "value": "CNLabelContactRelationSonInLawOrStepson"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.contacts~1documentation~1Contacts~1CNLabelContactRelationSonInLawOrStepson/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CNLabelContactRelationSonInLawOrStepson"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.contacts~1documentation~1Contacts~1CNLabelContactRelationAuntParentsElderSister/title",
          "value": "CNLabelContactRelationAuntParentsElderSister"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.contacts~1documentation~1Contacts~1CNLabelContactRelationAuntParentsElderSister/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CNLabelContactRelationAuntParentsElderSister"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.contacts~1documentation~1Contacts~1CNLabelContactRelationAuntFathersElderBrothersWife/title",
          "value": "CNLabelContactRelationAuntFathersElderBrothersWife"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.contacts~1documentation~1Contacts~1CNLabelContactRelationAuntFathersElderBrothersWife/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CNLabelContactRelationAuntFathersElderBrothersWife"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.contacts~1documentation~1Contacts~1CNLabelContactRelationAuntMothersYoungerSister/title",
          "value": "CNLabelContactRelationAuntMothersYoungerSister"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.contacts~1documentation~1Contacts~1CNLabelContactRelationAuntMothersYoungerSister/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CNLabelContactRelationAuntMothersYoungerSister"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.contacts~1documentation~1Contacts~1CNLabelContactRelationAuntMothersBrothersWife/title",
          "value": "CNLabelContactRelationAuntMothersBrothersWife"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.contacts~1documentation~1Contacts~1CNLabelContactRelationAuntMothersBrothersWife/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CNLabelContactRelationAuntMothersBrothersWife"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.contacts~1documentation~1Contacts~1CNLabelContactRelationAuntMothersSister/title",
          "value": "CNLabelContactRelationAuntMothersSister"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.contacts~1documentation~1Contacts~1CNLabelContactRelationAuntMothersSister/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CNLabelContactRelationAuntMothersSister"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.contacts~1documentation~1Contacts~1CNLabelContactRelationAuntFathersYoungerBrothersWife/title",
          "value": "CNLabelContactRelationAuntFathersYoungerBrothersWife"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.contacts~1documentation~1Contacts~1CNLabelContactRelationAuntFathersYoungerBrothersWife/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CNLabelContactRelationAuntFathersYoungerBrothersWife"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.contacts~1documentation~1Contacts~1CNLabelContactRelationAuntFathersYoungerSister/title",
          "value": "CNLabelContactRelationAuntFathersYoungerSister"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.contacts~1documentation~1Contacts~1CNLabelContactRelationAuntFathersYoungerSister/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CNLabelContactRelationAuntFathersYoungerSister"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.contacts~1documentation~1Contacts~1CNLabelContactRelationAuntFathersElderSister/title",
          "value": "CNLabelContactRelationAuntFathersElderSister"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.contacts~1documentation~1Contacts~1CNLabelContactRelationAuntFathersElderSister/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CNLabelContactRelationAuntFathersElderSister"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.contacts~1documentation~1Contacts~1CNLabelContactRelationAunt/title",
          "value": "CNLabelContactRelationAunt"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.contacts~1documentation~1Contacts~1CNLabelContactRelationAunt/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CNLabelContactRelationAunt"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.contacts~1documentation~1Contacts~1CNLabelContactRelationAuntParentsYoungerSister/title",
          "value": "CNLabelContactRelationAuntParentsYoungerSister"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.contacts~1documentation~1Contacts~1CNLabelContactRelationAuntParentsYoungerSister/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CNLabelContactRelationAuntParentsYoungerSister"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.contacts~1documentation~1Contacts~1CNLabelContactRelationCousin/title",
          "value": "CNLabelContactRelationCousin"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.contacts~1documentation~1Contacts~1CNLabelContactRelationCousin/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CNLabelContactRelationCousin"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.contacts~1documentation~1Contacts~1CNLabelContactRelationAuntFathersSister/title",
          "value": "CNLabelContactRelationAuntFathersSister"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.contacts~1documentation~1Contacts~1CNLabelContactRelationAuntFathersSister/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CNLabelContactRelationAuntFathersSister"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.contacts~1documentation~1Contacts~1CNLabelContactRelationAuntParentsSister/title",
          "value": "CNLabelContactRelationAuntParentsSister"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.contacts~1documentation~1Contacts~1CNLabelContactRelationAuntParentsSister/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CNLabelContactRelationAuntParentsSister"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.contacts~1documentation~1Contacts~1CNLabelContactRelationAuntMothersElderSister/title",
          "value": "CNLabelContactRelationAuntMothersElderSister"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.contacts~1documentation~1Contacts~1CNLabelContactRelationAuntMothersElderSister/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CNLabelContactRelationAuntMothersElderSister"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/contacts/cnlabelcontactrelationsoninlaworstepson"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/contacts/cnlabelcontactrelationsoninlaworstepson"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
