{
  "abstract": [
    {
      "text": "The label for the contact’s spouse.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.contacts/documentation/Contacts"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.contacts/documentation/Contacts/CNLabelContactRelationSpouse"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@CNLabelContactRelationSpouse",
    "fragments": [
      {
        "kind": "keyword",
        "text": "let"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "CNLabelContactRelationSpouse"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "s:SS",
        "text": "String"
      }
    ],
    "modules": [
      {
        "name": "Contacts"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "CNLabelContactRelationSpouse"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "9.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "9.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.1",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.11",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "2.0",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Global Variable",
    "symbolKind": "var",
    "title": "CNLabelContactRelationSpouse"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "let"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "CNLabelContactRelationSpouse"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:SS",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:SS",
              "text": "String"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "This label takes a string value.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.contacts/documentation/Contacts": {
      "abstract": [
        {
          "text": "Access the user’s contacts, and format and localize contact information.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.contacts/documentation/Contacts",
      "kind": "symbol",
      "role": "collection",
      "title": "Contacts",
      "type": "topic",
      "url": "/documentation/contacts"
    },
    "doc://com.apple.contacts/documentation/Contacts/CNLabelContactRelationAssistant": {
      "abstract": [
        {
          "text": "The label for the contact’s assistant.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CNLabelContactRelationAssistant"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.contacts/documentation/Contacts/CNLabelContactRelationAssistant",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CNLabelContactRelationAssistant"
        }
      ],
      "role": "symbol",
      "title": "CNLabelContactRelationAssistant",
      "type": "topic",
      "url": "/documentation/contacts/cnlabelcontactrelationassistant"
    },
    "doc://com.apple.contacts/documentation/Contacts/CNLabelContactRelationBrother": {
      "abstract": [
        {
          "text": "The label for the contact’s brother.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CNLabelContactRelationBrother"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.contacts/documentation/Contacts/CNLabelContactRelationBrother",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CNLabelContactRelationBrother"
        }
      ],
      "role": "symbol",
      "title": "CNLabelContactRelationBrother",
      "type": "topic",
      "url": "/documentation/contacts/cnlabelcontactrelationbrother"
    },
    "doc://com.apple.contacts/documentation/Contacts/CNLabelContactRelationChild": {
      "abstract": [
        {
          "text": "The label for the contact’s child.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CNLabelContactRelationChild"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.contacts/documentation/Contacts/CNLabelContactRelationChild",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CNLabelContactRelationChild"
        }
      ],
      "role": "symbol",
      "title": "CNLabelContactRelationChild",
      "type": "topic",
      "url": "/documentation/contacts/cnlabelcontactrelationchild"
    },
    "doc://com.apple.contacts/documentation/Contacts/CNLabelContactRelationDaughter": {
      "abstract": [
        {
          "text": "The label for the contact’s daughter.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CNLabelContactRelationDaughter"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.contacts/documentation/Contacts/CNLabelContactRelationDaughter",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CNLabelContactRelationDaughter"
        }
      ],
      "role": "symbol",
      "title": "CNLabelContactRelationDaughter",
      "type": "topic",
      "url": "/documentation/contacts/cnlabelcontactrelationdaughter"
    },
    "doc://com.apple.contacts/documentation/Contacts/CNLabelContactRelationFather": {
      "abstract": [
        {
          "text": "The label for the contact’s father.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CNLabelContactRelationFather"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.contacts/documentation/Contacts/CNLabelContactRelationFather",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CNLabelContactRelationFather"
        }
      ],
      "role": "symbol",
      "title": "CNLabelContactRelationFather",
      "type": "topic",
      "url": "/documentation/contacts/cnlabelcontactrelationfather"
    },
    "doc://com.apple.contacts/documentation/Contacts/CNLabelContactRelationFriend": {
      "abstract": [
        {
          "text": "The label for the contact’s friend.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CNLabelContactRelationFriend"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.contacts/documentation/Contacts/CNLabelContactRelationFriend",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CNLabelContactRelationFriend"
        }
      ],
      "role": "symbol",
      "title": "CNLabelContactRelationFriend",
      "type": "topic",
      "url": "/documentation/contacts/cnlabelcontactrelationfriend"
    },
    "doc://com.apple.contacts/documentation/Contacts/CNLabelContactRelationManager": {
      "abstract": [
        {
          "text": "The label for the contact’s manager.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CNLabelContactRelationManager"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.contacts/documentation/Contacts/CNLabelContactRelationManager",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CNLabelContactRelationManager"
        }
      ],
      "role": "symbol",
      "title": "CNLabelContactRelationManager",
      "type": "topic",
      "url": "/documentation/contacts/cnlabelcontactrelationmanager"
    },
    "doc://com.apple.contacts/documentation/Contacts/CNLabelContactRelationMother": {
      "abstract": [
        {
          "text": "The label for the contact’s mother.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CNLabelContactRelationMother"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.contacts/documentation/Contacts/CNLabelContactRelationMother",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CNLabelContactRelationMother"
        }
      ],
      "role": "symbol",
      "title": "CNLabelContactRelationMother",
      "type": "topic",
      "url": "/documentation/contacts/cnlabelcontactrelationmother"
    },
    "doc://com.apple.contacts/documentation/Contacts/CNLabelContactRelationParent": {
      "abstract": [
        {
          "text": "The label for the contact’s parent.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CNLabelContactRelationParent"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.contacts/documentation/Contacts/CNLabelContactRelationParent",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CNLabelContactRelationParent"
        }
      ],
      "role": "symbol",
      "title": "CNLabelContactRelationParent",
      "type": "topic",
      "url": "/documentation/contacts/cnlabelcontactrelationparent"
    },
    "doc://com.apple.contacts/documentation/Contacts/CNLabelContactRelationPartner": {
      "abstract": [
        {
          "text": "The label for the contact’s partner.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CNLabelContactRelationPartner"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.contacts/documentation/Contacts/CNLabelContactRelationPartner",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CNLabelContactRelationPartner"
        }
      ],
      "role": "symbol",
      "title": "CNLabelContactRelationPartner",
      "type": "topic",
      "url": "/documentation/contacts/cnlabelcontactrelationpartner"
    },
    "doc://com.apple.contacts/documentation/Contacts/CNLabelContactRelationSister": {
      "abstract": [
        {
          "text": "The label for the contact’s sister.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CNLabelContactRelationSister"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.contacts/documentation/Contacts/CNLabelContactRelationSister",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CNLabelContactRelationSister"
        }
      ],
      "role": "symbol",
      "title": "CNLabelContactRelationSister",
      "type": "topic",
      "url": "/documentation/contacts/cnlabelcontactrelationsister"
    },
    "doc://com.apple.contacts/documentation/Contacts/CNLabelContactRelationSon": {
      "abstract": [
        {
          "text": "The label for the contact’s son.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CNLabelContactRelationSon"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.contacts/documentation/Contacts/CNLabelContactRelationSon",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CNLabelContactRelationSon"
        }
      ],
      "role": "symbol",
      "title": "CNLabelContactRelationSon",
      "type": "topic",
      "url": "/documentation/contacts/cnlabelcontactrelationson"
    },
    "doc://com.apple.contacts/documentation/Contacts/CNLabelContactRelationSpouse": {
      "abstract": [
        {
          "text": "The label for the contact’s spouse.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CNLabelContactRelationSpouse"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.contacts/documentation/Contacts/CNLabelContactRelationSpouse",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CNLabelContactRelationSpouse"
        }
      ],
      "role": "symbol",
      "title": "CNLabelContactRelationSpouse",
      "type": "topic",
      "url": "/documentation/contacts/cnlabelcontactrelationspouse"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.externally.resolved.symbol/c:objc(cs)NSString": {
      "abstract": [
        {
          "text": "A static, plain-text Unicode string object which you use when you need reference semantics or other Foundation-specific behavior. ",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "class "
        },
        {
          "kind": "identifier",
          "text": "NSString"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSString",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSString",
      "type": "topic",
      "url": "/documentation/foundation/nsstring"
    },
    "doc://com.externally.resolved.symbol/s:SS": {
      "abstract": [
        {
          "text": "A Unicode string value that is a collection of characters.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@frozen"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "String"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SS",
      "kind": "symbol",
      "role": "symbol",
      "title": "String",
      "type": "topic",
      "url": "/documentation/Swift/String"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Getting-the-Common-Relationship-Labels",
      "generated": true,
      "identifiers": [
        "doc://com.apple.contacts/documentation/Contacts/CNLabelContactRelationPartner",
        "doc://com.apple.contacts/documentation/Contacts/CNLabelContactRelationDaughter",
        "doc://com.apple.contacts/documentation/Contacts/CNLabelContactRelationSon",
        "doc://com.apple.contacts/documentation/Contacts/CNLabelContactRelationChild",
        "doc://com.apple.contacts/documentation/Contacts/CNLabelContactRelationFather",
        "doc://com.apple.contacts/documentation/Contacts/CNLabelContactRelationMother",
        "doc://com.apple.contacts/documentation/Contacts/CNLabelContactRelationParent",
        "doc://com.apple.contacts/documentation/Contacts/CNLabelContactRelationBrother",
        "doc://com.apple.contacts/documentation/Contacts/CNLabelContactRelationSister",
        "doc://com.apple.contacts/documentation/Contacts/CNLabelContactRelationFriend",
        "doc://com.apple.contacts/documentation/Contacts/CNLabelContactRelationAssistant",
        "doc://com.apple.contacts/documentation/Contacts/CNLabelContactRelationManager"
      ],
      "title": "Getting the Common Relationship Labels"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "9.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "9.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.1",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.11",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "2.0",
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Global Variable"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "CNLabelContactRelationSpouse"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "var"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CNLabelContactRelationSpouse"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.contacts/documentation/Contacts"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Getting-the-Common-Relationship-Labels",
              "generated": true,
              "identifiers": [
                "doc://com.apple.contacts/documentation/Contacts/CNLabelContactRelationPartner",
                "doc://com.apple.contacts/documentation/Contacts/CNLabelContactRelationDaughter",
                "doc://com.apple.contacts/documentation/Contacts/CNLabelContactRelationSon",
                "doc://com.apple.contacts/documentation/Contacts/CNLabelContactRelationChild",
                "doc://com.apple.contacts/documentation/Contacts/CNLabelContactRelationFather",
                "doc://com.apple.contacts/documentation/Contacts/CNLabelContactRelationMother",
                "doc://com.apple.contacts/documentation/Contacts/CNLabelContactRelationParent",
                "doc://com.apple.contacts/documentation/Contacts/CNLabelContactRelationBrother",
                "doc://com.apple.contacts/documentation/Contacts/CNLabelContactRelationSister",
                "doc://com.apple.contacts/documentation/Contacts/CNLabelContactRelationFriend",
                "doc://com.apple.contacts/documentation/Contacts/CNLabelContactRelationAssistant",
                "doc://com.apple.contacts/documentation/Contacts/CNLabelContactRelationManager"
              ],
              "title": "Getting the Common Relationship Labels"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "extern"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSString",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(cs)NSString",
                    "text": "NSString"
                  },
                  {
                    "kind": "text",
                    "text": " * "
                  },
                  {
                    "kind": "keyword",
                    "text": "const"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "CNLabelContactRelationSpouse"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.contacts~1documentation~1Contacts~1CNLabelContactRelationSister/title",
          "value": "CNLabelContactRelationSister"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.contacts~1documentation~1Contacts~1CNLabelContactRelationSister/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CNLabelContactRelationSister"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:objc(cs)NSString/abstract",
          "value": [
            {
              "text": "A static, plain-text Unicode string object.",
              "type": "text"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.contacts~1documentation~1Contacts~1CNLabelContactRelationAssistant/title",
          "value": "CNLabelContactRelationAssistant"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.contacts~1documentation~1Contacts~1CNLabelContactRelationAssistant/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CNLabelContactRelationAssistant"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.contacts~1documentation~1Contacts~1CNLabelContactRelationSon/title",
          "value": "CNLabelContactRelationSon"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.contacts~1documentation~1Contacts~1CNLabelContactRelationSon/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CNLabelContactRelationSon"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.contacts~1documentation~1Contacts~1CNLabelContactRelationDaughter/title",
          "value": "CNLabelContactRelationDaughter"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.contacts~1documentation~1Contacts~1CNLabelContactRelationDaughter/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CNLabelContactRelationDaughter"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.contacts~1documentation~1Contacts~1CNLabelContactRelationFriend/title",
          "value": "CNLabelContactRelationFriend"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.contacts~1documentation~1Contacts~1CNLabelContactRelationFriend/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CNLabelContactRelationFriend"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.contacts~1documentation~1Contacts~1CNLabelContactRelationChild/title",
          "value": "CNLabelContactRelationChild"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.contacts~1documentation~1Contacts~1CNLabelContactRelationChild/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CNLabelContactRelationChild"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.contacts~1documentation~1Contacts~1CNLabelContactRelationSpouse/title",
          "value": "CNLabelContactRelationSpouse"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.contacts~1documentation~1Contacts~1CNLabelContactRelationSpouse/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CNLabelContactRelationSpouse"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.contacts~1documentation~1Contacts~1CNLabelContactRelationFather/title",
          "value": "CNLabelContactRelationFather"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.contacts~1documentation~1Contacts~1CNLabelContactRelationFather/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CNLabelContactRelationFather"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.contacts~1documentation~1Contacts~1CNLabelContactRelationManager/title",
          "value": "CNLabelContactRelationManager"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.contacts~1documentation~1Contacts~1CNLabelContactRelationManager/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CNLabelContactRelationManager"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.contacts~1documentation~1Contacts~1CNLabelContactRelationPartner/title",
          "value": "CNLabelContactRelationPartner"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.contacts~1documentation~1Contacts~1CNLabelContactRelationPartner/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CNLabelContactRelationPartner"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.contacts~1documentation~1Contacts~1CNLabelContactRelationMother/title",
          "value": "CNLabelContactRelationMother"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.contacts~1documentation~1Contacts~1CNLabelContactRelationMother/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CNLabelContactRelationMother"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.contacts~1documentation~1Contacts~1CNLabelContactRelationBrother/title",
          "value": "CNLabelContactRelationBrother"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.contacts~1documentation~1Contacts~1CNLabelContactRelationBrother/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CNLabelContactRelationBrother"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.contacts~1documentation~1Contacts~1CNLabelContactRelationParent/title",
          "value": "CNLabelContactRelationParent"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.contacts~1documentation~1Contacts~1CNLabelContactRelationParent/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CNLabelContactRelationParent"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/contacts/cnlabelcontactrelationspouse"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/contacts/cnlabelcontactrelationspouse"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
