{
  "abstract": [
    {
      "text": "An object that you use to format a contact’s postal addresses.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.contacts/documentation/Contacts"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.contacts/documentation/Contacts/CNPostalAddressFormatter"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(cs)CNPostalAddressFormatter",
    "fragments": [
      {
        "kind": "keyword",
        "text": "class"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "CNPostalAddressFormatter"
      }
    ],
    "modules": [
      {
        "name": "Contacts"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "CNPostalAddressFormatter"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "9.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "9.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.1",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.11",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "2.0",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Class",
    "symbolKind": "class",
    "title": "CNPostalAddressFormatter"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "class"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "CNPostalAddressFormatter"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "A ",
              "type": "text"
            },
            {
              "code": "CNPostalAddressFormatter",
              "type": "codeVoice"
            },
            {
              "text": " object handles international formatting of postal addresses. It is recommended that you create an instance of this class when formatting many postal addresses, and use the instance methods; otherwise use the class methods.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.contacts/documentation/Contacts": {
      "abstract": [
        {
          "text": "Access the user’s contacts, and format and localize contact information.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.contacts/documentation/Contacts",
      "kind": "symbol",
      "role": "collection",
      "title": "Contacts",
      "type": "topic",
      "url": "/documentation/contacts"
    },
    "doc://com.apple.contacts/documentation/Contacts/CNContactFormatter": {
      "abstract": [
        {
          "text": "An object that you use to format contact information before displaying it to the user.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CNContactFormatter"
        }
      ],
      "identifier": "doc://com.apple.contacts/documentation/Contacts/CNContactFormatter",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CNContactFormatter"
        }
      ],
      "role": "symbol",
      "title": "CNContactFormatter",
      "type": "topic",
      "url": "/documentation/contacts/cncontactformatter"
    },
    "doc://com.apple.contacts/documentation/Contacts/CNContactVCardSerialization": {
      "abstract": [
        {
          "text": "An object you use to convert to and from a vCard representation of the user’s contacts.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CNContactVCardSerialization"
        }
      ],
      "identifier": "doc://com.apple.contacts/documentation/Contacts/CNContactVCardSerialization",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CNContactVCardSerialization"
        }
      ],
      "role": "symbol",
      "title": "CNContactVCardSerialization",
      "type": "topic",
      "url": "/documentation/contacts/cncontactvcardserialization"
    },
    "doc://com.apple.contacts/documentation/Contacts/CNContactsUserDefaults": {
      "abstract": [
        {
          "text": "An object that defines the default options to use when displaying contacts.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CNContactsUserDefaults"
        }
      ],
      "identifier": "doc://com.apple.contacts/documentation/Contacts/CNContactsUserDefaults",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CNContactsUserDefaults"
        }
      ],
      "role": "symbol",
      "title": "CNContactsUserDefaults",
      "type": "topic",
      "url": "/documentation/contacts/cncontactsuserdefaults"
    },
    "doc://com.apple.contacts/documentation/Contacts/CNPostalAddressCityKey": {
      "abstract": [
        {
          "text": "The city of the address.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CNPostalAddressCityKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.contacts/documentation/Contacts/CNPostalAddressCityKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CNPostalAddressCityKey"
        }
      ],
      "role": "symbol",
      "title": "CNPostalAddressCityKey",
      "type": "topic",
      "url": "/documentation/contacts/cnpostaladdresscitykey"
    },
    "doc://com.apple.contacts/documentation/Contacts/CNPostalAddressCountryKey": {
      "abstract": [
        {
          "text": "The country or region name of the address.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CNPostalAddressCountryKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.contacts/documentation/Contacts/CNPostalAddressCountryKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CNPostalAddressCountryKey"
        }
      ],
      "role": "symbol",
      "title": "CNPostalAddressCountryKey",
      "type": "topic",
      "url": "/documentation/contacts/cnpostaladdresscountrykey"
    },
    "doc://com.apple.contacts/documentation/Contacts/CNPostalAddressFormatter": {
      "abstract": [
        {
          "text": "An object that you use to format a contact’s postal addresses.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CNPostalAddressFormatter"
        }
      ],
      "identifier": "doc://com.apple.contacts/documentation/Contacts/CNPostalAddressFormatter",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CNPostalAddressFormatter"
        }
      ],
      "role": "symbol",
      "title": "CNPostalAddressFormatter",
      "type": "topic",
      "url": "/documentation/contacts/cnpostaladdressformatter"
    },
    "doc://com.apple.contacts/documentation/Contacts/CNPostalAddressFormatter/attributedString(from:style:withDefaultAttributes:)": {
      "abstract": [
        {
          "text": "Returns a postal address as an attributed string and formatted for the specified style.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "attributedString"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "from"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)CNPostalAddress",
          "text": "CNPostalAddress"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "style"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@CNPostalAddressFormatterStyle",
          "text": "CNPostalAddressFormatterStyle"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "withDefaultAttributes"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s11AnyHashableV",
          "text": "AnyHashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "keyword",
          "text": "Any"
        },
        {
          "kind": "text",
          "text": "]) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSAttributedString",
          "text": "NSAttributedString"
        }
      ],
      "identifier": "doc://com.apple.contacts/documentation/Contacts/CNPostalAddressFormatter/attributedString(from:style:withDefaultAttributes:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "attributedStringFromPostalAddress:style:withDefaultAttributes:"
        }
      ],
      "role": "symbol",
      "title": "attributedString(from:style:withDefaultAttributes:)",
      "type": "topic",
      "url": "/documentation/contacts/cnpostaladdressformatter/attributedstring(from:style:withdefaultattributes:)"
    },
    "doc://com.apple.contacts/documentation/Contacts/CNPostalAddressFormatter/attributedString(from:withDefaultAttributes:)": {
      "abstract": [
        {
          "text": "Returns a formatted postal address as an attributed string.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "attributedString"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "from"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)CNPostalAddress",
          "text": "CNPostalAddress"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "withDefaultAttributes"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s11AnyHashableV",
          "text": "AnyHashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "keyword",
          "text": "Any"
        },
        {
          "kind": "text",
          "text": "]) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSAttributedString",
          "text": "NSAttributedString"
        }
      ],
      "identifier": "doc://com.apple.contacts/documentation/Contacts/CNPostalAddressFormatter/attributedString(from:withDefaultAttributes:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "attributedStringFromPostalAddress:withDefaultAttributes:"
        }
      ],
      "role": "symbol",
      "title": "attributedString(from:withDefaultAttributes:)",
      "type": "topic",
      "url": "/documentation/contacts/cnpostaladdressformatter/attributedstring(from:withdefaultattributes:)"
    },
    "doc://com.apple.contacts/documentation/Contacts/CNPostalAddressFormatter/string(from:)": {
      "abstract": [
        {
          "text": "Returns a formatted postal address.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "string"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "from"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)CNPostalAddress",
          "text": "CNPostalAddress"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.contacts/documentation/Contacts/CNPostalAddressFormatter/string(from:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "stringFromPostalAddress:"
        }
      ],
      "role": "symbol",
      "title": "string(from:)",
      "type": "topic",
      "url": "/documentation/contacts/cnpostaladdressformatter/string(from:)"
    },
    "doc://com.apple.contacts/documentation/Contacts/CNPostalAddressFormatter/string(from:style:)": {
      "abstract": [
        {
          "text": "Returns a postal address as a string and formatted for the specified style.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "string"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "from"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)CNPostalAddress",
          "text": "CNPostalAddress"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "style"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@CNPostalAddressFormatterStyle",
          "text": "CNPostalAddressFormatterStyle"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.contacts/documentation/Contacts/CNPostalAddressFormatter/string(from:style:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "stringFromPostalAddress:style:"
        }
      ],
      "role": "symbol",
      "title": "string(from:style:)",
      "type": "topic",
      "url": "/documentation/contacts/cnpostaladdressformatter/string(from:style:)"
    },
    "doc://com.apple.contacts/documentation/Contacts/CNPostalAddressFormatter/style": {
      "abstract": [
        {
          "text": "The style to apply when formatting strings.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "style"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@CNPostalAddressFormatterStyle",
          "text": "CNPostalAddressFormatterStyle"
        }
      ],
      "identifier": "doc://com.apple.contacts/documentation/Contacts/CNPostalAddressFormatter/style",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "style"
        }
      ],
      "role": "symbol",
      "title": "style",
      "type": "topic",
      "url": "/documentation/contacts/cnpostaladdressformatter/style"
    },
    "doc://com.apple.contacts/documentation/Contacts/CNPostalAddressFormatterStyle": {
      "abstract": [
        {
          "text": "Constants for postal formatting styles.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CNPostalAddressFormatterStyle"
        }
      ],
      "identifier": "doc://com.apple.contacts/documentation/Contacts/CNPostalAddressFormatterStyle",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CNPostalAddressFormatterStyle"
        }
      ],
      "role": "symbol",
      "title": "CNPostalAddressFormatterStyle",
      "type": "topic",
      "url": "/documentation/contacts/cnpostaladdressformatterstyle"
    },
    "doc://com.apple.contacts/documentation/Contacts/CNPostalAddressISOCountryCodeKey": {
      "abstract": [
        {
          "text": "The ISO country code of the address.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CNPostalAddressISOCountryCodeKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.contacts/documentation/Contacts/CNPostalAddressISOCountryCodeKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CNPostalAddressISOCountryCodeKey"
        }
      ],
      "role": "symbol",
      "title": "CNPostalAddressISOCountryCodeKey",
      "type": "topic",
      "url": "/documentation/contacts/cnpostaladdressisocountrycodekey"
    },
    "doc://com.apple.contacts/documentation/Contacts/CNPostalAddressLocalizedPropertyNameAttribute": {
      "abstract": [
        {
          "text": "An attribute that identifies the localized property of postal address.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CNPostalAddressLocalizedPropertyNameAttribute"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.contacts/documentation/Contacts/CNPostalAddressLocalizedPropertyNameAttribute",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CNPostalAddressLocalizedPropertyNameAttribute"
        }
      ],
      "role": "symbol",
      "title": "CNPostalAddressLocalizedPropertyNameAttribute",
      "type": "topic",
      "url": "/documentation/contacts/cnpostaladdresslocalizedpropertynameattribute"
    },
    "doc://com.apple.contacts/documentation/Contacts/CNPostalAddressPostalCodeKey": {
      "abstract": [
        {
          "text": "The postal code of the address.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CNPostalAddressPostalCodeKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.contacts/documentation/Contacts/CNPostalAddressPostalCodeKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CNPostalAddressPostalCodeKey"
        }
      ],
      "role": "symbol",
      "title": "CNPostalAddressPostalCodeKey",
      "type": "topic",
      "url": "/documentation/contacts/cnpostaladdresspostalcodekey"
    },
    "doc://com.apple.contacts/documentation/Contacts/CNPostalAddressPropertyAttribute": {
      "abstract": [
        {
          "text": "An attribute that identifies the purpose of a range of characters in an attributed string.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CNPostalAddressPropertyAttribute"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.contacts/documentation/Contacts/CNPostalAddressPropertyAttribute",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CNPostalAddressPropertyAttribute"
        }
      ],
      "role": "symbol",
      "title": "CNPostalAddressPropertyAttribute",
      "type": "topic",
      "url": "/documentation/contacts/cnpostaladdresspropertyattribute"
    },
    "doc://com.apple.contacts/documentation/Contacts/CNPostalAddressStateKey": {
      "abstract": [
        {
          "text": "The state name of the address.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CNPostalAddressStateKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.contacts/documentation/Contacts/CNPostalAddressStateKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CNPostalAddressStateKey"
        }
      ],
      "role": "symbol",
      "title": "CNPostalAddressStateKey",
      "type": "topic",
      "url": "/documentation/contacts/cnpostaladdressstatekey"
    },
    "doc://com.apple.contacts/documentation/Contacts/CNPostalAddressStreetKey": {
      "abstract": [
        {
          "text": "The street name of the address.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CNPostalAddressStreetKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.contacts/documentation/Contacts/CNPostalAddressStreetKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CNPostalAddressStreetKey"
        }
      ],
      "role": "symbol",
      "title": "CNPostalAddressStreetKey",
      "type": "topic",
      "url": "/documentation/contacts/cnpostaladdressstreetkey"
    },
    "doc://com.apple.contacts/documentation/Contacts/CNPostalAddressSubAdministrativeAreaKey": {
      "abstract": [
        {
          "text": "The subadministrative area of the address.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CNPostalAddressSubAdministrativeAreaKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.contacts/documentation/Contacts/CNPostalAddressSubAdministrativeAreaKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CNPostalAddressSubAdministrativeAreaKey"
        }
      ],
      "role": "symbol",
      "title": "CNPostalAddressSubAdministrativeAreaKey",
      "type": "topic",
      "url": "/documentation/contacts/cnpostaladdresssubadministrativeareakey"
    },
    "doc://com.apple.contacts/documentation/Contacts/CNPostalAddressSubLocalityKey": {
      "abstract": [
        {
          "text": "The sublocality of the address.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CNPostalAddressSubLocalityKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.contacts/documentation/Contacts/CNPostalAddressSubLocalityKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CNPostalAddressSubLocalityKey"
        }
      ],
      "role": "symbol",
      "title": "CNPostalAddressSubLocalityKey",
      "type": "topic",
      "url": "/documentation/contacts/cnpostaladdresssublocalitykey"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.externally.resolved.symbol/c:objc(cs)NSFormatter": {
      "abstract": [
        {
          "text": "An abstract class that declares an interface for objects that create, interpret, and validate the textual representation of values.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "class "
        },
        {
          "kind": "identifier",
          "text": "Formatter"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSFormatter",
      "kind": "symbol",
      "role": "symbol",
      "title": "Formatter",
      "type": "topic",
      "url": "/documentation/foundation/formatter"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)NSCoding": {
      "abstract": [
        {
          "text": "A protocol that enables an object to be encoded and decoded for archiving and distribution.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "protocol "
        },
        {
          "kind": "identifier",
          "text": "NSCoding"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSCoding",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSCoding",
      "type": "topic",
      "url": "/documentation/foundation/nscoding"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)NSCopying": {
      "abstract": [
        {
          "text": "A protocol that objects adopt to provide functional copies of themselves.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "protocol "
        },
        {
          "kind": "identifier",
          "text": "NSCopying"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSCopying",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSCopying",
      "type": "topic",
      "url": "/documentation/foundation/nscopying"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)NSObject": {
      "abstract": [
        {
          "text": "The group of methods that are fundamental to all Objective-C objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "protocol "
        },
        {
          "kind": "identifier",
          "text": "NSObjectProtocol"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSObject",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSObjectProtocol",
      "type": "topic",
      "url": "/documentation/objectivec/nsobjectprotocol"
    },
    "doc://com.externally.resolved.symbol/s:SH": {
      "abstract": [
        {
          "text": "A type that can be hashed into a `Hasher` to produce an integer hash value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Hashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SQ",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SH",
      "kind": "symbol",
      "role": "symbol",
      "title": "Hashable",
      "type": "topic",
      "url": "/documentation/Swift/Hashable"
    },
    "doc://com.externally.resolved.symbol/s:SQ": {
      "abstract": [
        {
          "text": "A type that can be compared for value equality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SQ",
      "kind": "symbol",
      "role": "symbol",
      "title": "Equatable",
      "type": "topic",
      "url": "/documentation/Swift/Equatable"
    },
    "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP": {
      "abstract": [
        {
          "text": "A type with a customized textual representation.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CustomStringConvertible"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CustomStringConvertible",
      "type": "topic",
      "url": "/documentation/Swift/CustomStringConvertible"
    },
    "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP": {
      "abstract": [
        {
          "text": "A type with a customized textual representation suitable for debugging purposes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CustomDebugStringConvertible"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CustomDebugStringConvertible",
      "type": "topic",
      "url": "/documentation/Swift/CustomDebugStringConvertible"
    },
    "doc://com.externally.resolved.symbol/s:s7CVarArgP": {
      "abstract": [
        {
          "text": "A type whose instances can be encoded, and appropriately passed, as elements of a C `va_list`.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CVarArg"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s7CVarArgP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CVarArg",
      "type": "topic",
      "url": "/documentation/Swift/CVarArg"
    },
    "doc://com.externally.resolved.symbol/s:s8SendableP": {
      "abstract": [
        {
          "text": "A thread-safe type whose values can be shared across arbitrary concurrent contexts without introducing a risk of data races.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Sendable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s8SendableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "Sendable",
      "type": "topic",
      "url": "/documentation/Swift/Sendable"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/c:objc(cs)NSFormatter"
      ],
      "kind": "relationships",
      "title": "Inherits From",
      "type": "inheritsFrom"
    },
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:s7CVarArgP",
        "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP",
        "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP",
        "doc://com.externally.resolved.symbol/s:SQ",
        "doc://com.externally.resolved.symbol/s:SH",
        "doc://com.externally.resolved.symbol/c:objc(pl)NSCoding",
        "doc://com.externally.resolved.symbol/c:objc(pl)NSCopying",
        "doc://com.externally.resolved.symbol/c:objc(pl)NSObject",
        "doc://com.externally.resolved.symbol/s:s8SendableP"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Formatters",
      "generated": true,
      "identifiers": [
        "doc://com.apple.contacts/documentation/Contacts/CNContactFormatter",
        "doc://com.apple.contacts/documentation/Contacts/CNContactVCardSerialization",
        "doc://com.apple.contacts/documentation/Contacts/CNContactsUserDefaults"
      ],
      "title": "Formatters"
    }
  ],
  "topicSections": [
    {
      "anchor": "Generating-a-formatted-attributed-string",
      "identifiers": [
        "doc://com.apple.contacts/documentation/Contacts/CNPostalAddressFormatter/attributedString(from:withDefaultAttributes:)",
        "doc://com.apple.contacts/documentation/Contacts/CNPostalAddressFormatter/attributedString(from:style:withDefaultAttributes:)",
        "doc://com.apple.contacts/documentation/Contacts/CNPostalAddressPropertyAttribute",
        "doc://com.apple.contacts/documentation/Contacts/CNPostalAddressLocalizedPropertyNameAttribute"
      ],
      "title": "Generating a formatted attributed string"
    },
    {
      "anchor": "Generating-a-formatted-string",
      "identifiers": [
        "doc://com.apple.contacts/documentation/Contacts/CNPostalAddressFormatter/string(from:)",
        "doc://com.apple.contacts/documentation/Contacts/CNPostalAddressFormatter/string(from:style:)"
      ],
      "title": "Generating a formatted string"
    },
    {
      "anchor": "Specifying-the-formatting-style",
      "identifiers": [
        "doc://com.apple.contacts/documentation/Contacts/CNPostalAddressFormatter/style",
        "doc://com.apple.contacts/documentation/Contacts/CNPostalAddressFormatterStyle"
      ],
      "title": "Specifying the formatting style"
    },
    {
      "anchor": "Getting-the-postal-attribute-keys",
      "identifiers": [
        "doc://com.apple.contacts/documentation/Contacts/CNPostalAddressCityKey",
        "doc://com.apple.contacts/documentation/Contacts/CNPostalAddressCountryKey",
        "doc://com.apple.contacts/documentation/Contacts/CNPostalAddressISOCountryCodeKey",
        "doc://com.apple.contacts/documentation/Contacts/CNPostalAddressPostalCodeKey",
        "doc://com.apple.contacts/documentation/Contacts/CNPostalAddressStateKey",
        "doc://com.apple.contacts/documentation/Contacts/CNPostalAddressStreetKey",
        "doc://com.apple.contacts/documentation/Contacts/CNPostalAddressSubAdministrativeAreaKey",
        "doc://com.apple.contacts/documentation/Contacts/CNPostalAddressSubLocalityKey"
      ],
      "title": "Getting the postal attribute keys"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "9.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "9.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.1",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.11",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "2.0",
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Class"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "CNPostalAddressFormatter"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "class"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CNPostalAddressFormatter"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CNPostalAddressFormatter"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.contacts/documentation/Contacts"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Generating-a-formatted-attributed-string",
              "identifiers": [
                "doc://com.apple.contacts/documentation/Contacts/CNPostalAddressFormatter/attributedString(from:withDefaultAttributes:)",
                "doc://com.apple.contacts/documentation/Contacts/CNPostalAddressFormatter/attributedString(from:style:withDefaultAttributes:)",
                "doc://com.apple.contacts/documentation/Contacts/CNPostalAddressPropertyAttribute",
                "doc://com.apple.contacts/documentation/Contacts/CNPostalAddressLocalizedPropertyNameAttribute"
              ],
              "title": "Generating a formatted attributed string"
            },
            {
              "anchor": "Generating-a-formatted-string",
              "identifiers": [
                "doc://com.apple.contacts/documentation/Contacts/CNPostalAddressFormatter/string(from:)",
                "doc://com.apple.contacts/documentation/Contacts/CNPostalAddressFormatter/string(from:style:)"
              ],
              "title": "Generating a formatted string"
            },
            {
              "anchor": "Specifying-the-formatting-style",
              "identifiers": [
                "doc://com.apple.contacts/documentation/Contacts/CNPostalAddressFormatter/style",
                "doc://com.apple.contacts/documentation/Contacts/CNPostalAddressFormatterStyle"
              ],
              "title": "Specifying the formatting style"
            },
            {
              "anchor": "Getting-the-postal-attribute-keys",
              "identifiers": [
                "doc://com.apple.contacts/documentation/Contacts/CNPostalAddressCityKey",
                "doc://com.apple.contacts/documentation/Contacts/CNPostalAddressCountryKey",
                "doc://com.apple.contacts/documentation/Contacts/CNPostalAddressISOCountryCodeKey",
                "doc://com.apple.contacts/documentation/Contacts/CNPostalAddressPostalCodeKey",
                "doc://com.apple.contacts/documentation/Contacts/CNPostalAddressStateKey",
                "doc://com.apple.contacts/documentation/Contacts/CNPostalAddressStreetKey",
                "doc://com.apple.contacts/documentation/Contacts/CNPostalAddressSubAdministrativeAreaKey",
                "doc://com.apple.contacts/documentation/Contacts/CNPostalAddressSubLocalityKey"
              ],
              "title": "Getting the postal attribute keys"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": [
            {
              "identifiers": [
                "doc://com.externally.resolved.symbol/c:objc(cs)NSFormatter"
              ],
              "kind": "relationships",
              "title": "Inherits From",
              "type": "inheritsFrom"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Formatters",
              "generated": true,
              "identifiers": [
                "doc://com.apple.contacts/documentation/Contacts/CNContactFormatter",
                "doc://com.apple.contacts/documentation/Contacts/CNContactVCardSerialization",
                "doc://com.apple.contacts/documentation/Contacts/CNContactsUserDefaults"
              ],
              "title": "Formatters"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "@interface"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "CNPostalAddressFormatter"
                  },
                  {
                    "kind": "text",
                    "text": " : "
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSFormatter",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(cs)NSFormatter",
                    "text": "NSFormatter"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.contacts~1documentation~1Contacts~1CNPostalAddressLocalizedPropertyNameAttribute/title",
          "value": "CNPostalAddressLocalizedPropertyNameAttribute"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.contacts~1documentation~1Contacts~1CNPostalAddressLocalizedPropertyNameAttribute/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CNPostalAddressLocalizedPropertyNameAttribute"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.contacts~1documentation~1Contacts~1CNPostalAddressSubAdministrativeAreaKey/title",
          "value": "CNPostalAddressSubAdministrativeAreaKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.contacts~1documentation~1Contacts~1CNPostalAddressSubAdministrativeAreaKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CNPostalAddressSubAdministrativeAreaKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.contacts~1documentation~1Contacts~1CNPostalAddressSubLocalityKey/title",
          "value": "CNPostalAddressSubLocalityKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.contacts~1documentation~1Contacts~1CNPostalAddressSubLocalityKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CNPostalAddressSubLocalityKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.contacts~1documentation~1Contacts~1CNPostalAddressFormatter~1style/title",
          "value": "style"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.contacts~1documentation~1Contacts~1CNPostalAddressFormatter~1style/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "style"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.contacts~1documentation~1Contacts~1CNPostalAddressStateKey/title",
          "value": "CNPostalAddressStateKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.contacts~1documentation~1Contacts~1CNPostalAddressStateKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CNPostalAddressStateKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.contacts~1documentation~1Contacts~1CNPostalAddressFormatterStyle/title",
          "value": "CNPostalAddressFormatterStyle"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.contacts~1documentation~1Contacts~1CNPostalAddressFormatterStyle/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CNPostalAddressFormatterStyle"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.contacts~1documentation~1Contacts~1CNPostalAddressFormatterStyle/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CNPostalAddressFormatterStyle"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.contacts~1documentation~1Contacts~1CNPostalAddressCityKey/title",
          "value": "CNPostalAddressCityKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.contacts~1documentation~1Contacts~1CNPostalAddressCityKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CNPostalAddressCityKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.contacts~1documentation~1Contacts~1CNPostalAddressPropertyAttribute/title",
          "value": "CNPostalAddressPropertyAttribute"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.contacts~1documentation~1Contacts~1CNPostalAddressPropertyAttribute/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CNPostalAddressPropertyAttribute"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:objc(cs)NSFormatter/title",
          "value": "NSFormatter"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.contacts~1documentation~1Contacts~1CNPostalAddressFormatter~1attributedString(from:style:withDefaultAttributes:)/title",
          "value": "attributedStringFromPostalAddress:style:withDefaultAttributes:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.contacts~1documentation~1Contacts~1CNPostalAddressFormatter~1attributedString(from:style:withDefaultAttributes:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "+ "
            },
            {
              "kind": "identifier",
              "text": "attributedStringFromPostalAddress:style:withDefaultAttributes:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.contacts~1documentation~1Contacts~1CNPostalAddressISOCountryCodeKey/title",
          "value": "CNPostalAddressISOCountryCodeKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.contacts~1documentation~1Contacts~1CNPostalAddressISOCountryCodeKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CNPostalAddressISOCountryCodeKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.contacts~1documentation~1Contacts~1CNContactVCardSerialization/title",
          "value": "CNContactVCardSerialization"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.contacts~1documentation~1Contacts~1CNContactVCardSerialization/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CNContactVCardSerialization"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.contacts~1documentation~1Contacts~1CNContactVCardSerialization/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CNContactVCardSerialization"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.contacts~1documentation~1Contacts~1CNContactsUserDefaults/title",
          "value": "CNContactsUserDefaults"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.contacts~1documentation~1Contacts~1CNContactsUserDefaults/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CNContactsUserDefaults"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.contacts~1documentation~1Contacts~1CNContactsUserDefaults/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CNContactsUserDefaults"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.contacts~1documentation~1Contacts~1CNPostalAddressFormatter/title",
          "value": "CNPostalAddressFormatter"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.contacts~1documentation~1Contacts~1CNPostalAddressFormatter/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CNPostalAddressFormatter"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.contacts~1documentation~1Contacts~1CNPostalAddressFormatter/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CNPostalAddressFormatter"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.contacts~1documentation~1Contacts~1CNPostalAddressStreetKey/title",
          "value": "CNPostalAddressStreetKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.contacts~1documentation~1Contacts~1CNPostalAddressStreetKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CNPostalAddressStreetKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.contacts~1documentation~1Contacts~1CNPostalAddressPostalCodeKey/title",
          "value": "CNPostalAddressPostalCodeKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.contacts~1documentation~1Contacts~1CNPostalAddressPostalCodeKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CNPostalAddressPostalCodeKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.contacts~1documentation~1Contacts~1CNContactFormatter/title",
          "value": "CNContactFormatter"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.contacts~1documentation~1Contacts~1CNContactFormatter/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CNContactFormatter"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.contacts~1documentation~1Contacts~1CNContactFormatter/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CNContactFormatter"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.contacts~1documentation~1Contacts~1CNPostalAddressFormatter~1string(from:)/title",
          "value": "stringFromPostalAddress:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.contacts~1documentation~1Contacts~1CNPostalAddressFormatter~1string(from:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "stringFromPostalAddress:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.contacts~1documentation~1Contacts~1CNPostalAddressFormatter~1string(from:style:)/title",
          "value": "stringFromPostalAddress:style:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.contacts~1documentation~1Contacts~1CNPostalAddressFormatter~1string(from:style:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "+ "
            },
            {
              "kind": "identifier",
              "text": "stringFromPostalAddress:style:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.contacts~1documentation~1Contacts~1CNPostalAddressCountryKey/title",
          "value": "CNPostalAddressCountryKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.contacts~1documentation~1Contacts~1CNPostalAddressCountryKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CNPostalAddressCountryKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:objc(pl)NSObject/title",
          "value": "NSObject"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.contacts~1documentation~1Contacts~1CNPostalAddressFormatter~1attributedString(from:withDefaultAttributes:)/title",
          "value": "attributedStringFromPostalAddress:withDefaultAttributes:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.contacts~1documentation~1Contacts~1CNPostalAddressFormatter~1attributedString(from:withDefaultAttributes:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "attributedStringFromPostalAddress:withDefaultAttributes:"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/contacts/cnpostaladdressformatter"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/contacts/cnpostaladdressformatter"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
