{
  "abstract": [
    {
      "text": "An immutable object that represents one of the user’s social profiles.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.contacts/documentation/Contacts"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.contacts/documentation/Contacts/CNSocialProfile"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(cs)CNSocialProfile",
    "fragments": [
      {
        "kind": "keyword",
        "text": "class"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "CNSocialProfile"
      }
    ],
    "modules": [
      {
        "name": "Contacts"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "CNSocialProfile"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "9.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "9.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.1",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.11",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "2.0",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Class",
    "symbolKind": "class",
    "title": "CNSocialProfile"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "class"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "CNSocialProfile"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Some social profile services, such as Facebook and Twitter, are predefined in this class. You can also specify your own social profile service with the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.contacts/documentation/Contacts/CNSocialProfile/init(urlString:username:userIdentifier:service:)",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " method.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "code": "CNSocialProfile",
              "type": "codeVoice"
            },
            {
              "text": " objects are thread-safe, and you may access their properties from any thread of your app.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.contacts/documentation/Contacts": {
      "abstract": [
        {
          "text": "Access the user’s contacts, and format and localize contact information.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.contacts/documentation/Contacts",
      "kind": "symbol",
      "role": "collection",
      "title": "Contacts",
      "type": "topic",
      "url": "/documentation/contacts"
    },
    "doc://com.apple.contacts/documentation/Contacts/CNSocialProfile": {
      "abstract": [
        {
          "text": "An immutable object that represents one of the user’s social profiles.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CNSocialProfile"
        }
      ],
      "identifier": "doc://com.apple.contacts/documentation/Contacts/CNSocialProfile",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CNSocialProfile"
        }
      ],
      "role": "symbol",
      "title": "CNSocialProfile",
      "type": "topic",
      "url": "/documentation/contacts/cnsocialprofile"
    },
    "doc://com.apple.contacts/documentation/Contacts/CNSocialProfile/init(urlString:username:userIdentifier:service:)": {
      "abstract": [
        {
          "text": "Initializes a new social profile object with the specified URL.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "urlString"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": "?, "
        },
        {
          "kind": "externalParam",
          "text": "username"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": "?, "
        },
        {
          "kind": "externalParam",
          "text": "userIdentifier"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": "?, "
        },
        {
          "kind": "externalParam",
          "text": "service"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": "?)"
        }
      ],
      "identifier": "doc://com.apple.contacts/documentation/Contacts/CNSocialProfile/init(urlString:username:userIdentifier:service:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "initWithUrlString:username:userIdentifier:service:"
        }
      ],
      "role": "symbol",
      "title": "init(urlString:username:userIdentifier:service:)",
      "type": "topic",
      "url": "/documentation/contacts/cnsocialprofile/init(urlstring:username:useridentifier:service:)"
    },
    "doc://com.apple.contacts/documentation/Contacts/CNSocialProfile/localizedString(forKey:)": {
      "abstract": [
        {
          "text": "Returns the localized name of the property for the specified key.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "localizedString"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "forKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.contacts/documentation/Contacts/CNSocialProfile/localizedString(forKey:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "localizedStringForKey:"
        }
      ],
      "role": "symbol",
      "title": "localizedString(forKey:)",
      "type": "topic",
      "url": "/documentation/contacts/cnsocialprofile/localizedstring(forkey:)"
    },
    "doc://com.apple.contacts/documentation/Contacts/CNSocialProfile/localizedString(forService:)": {
      "abstract": [
        {
          "text": "Returns the localized name of the specified service.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "localizedString"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "forService"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.contacts/documentation/Contacts/CNSocialProfile/localizedString(forService:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "localizedStringForService:"
        }
      ],
      "role": "symbol",
      "title": "localizedString(forService:)",
      "type": "topic",
      "url": "/documentation/contacts/cnsocialprofile/localizedstring(forservice:)"
    },
    "doc://com.apple.contacts/documentation/Contacts/CNSocialProfile/service": {
      "abstract": [
        {
          "text": "The social profile’s service name.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "service"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.contacts/documentation/Contacts/CNSocialProfile/service",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "service"
        }
      ],
      "role": "symbol",
      "title": "service",
      "type": "topic",
      "url": "/documentation/contacts/cnsocialprofile/service"
    },
    "doc://com.apple.contacts/documentation/Contacts/CNSocialProfile/urlString": {
      "abstract": [
        {
          "text": "The URL associated with the social profile.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "urlString"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.contacts/documentation/Contacts/CNSocialProfile/urlString",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "urlString"
        }
      ],
      "role": "symbol",
      "title": "urlString",
      "type": "topic",
      "url": "/documentation/contacts/cnsocialprofile/urlstring"
    },
    "doc://com.apple.contacts/documentation/Contacts/CNSocialProfile/userIdentifier": {
      "abstract": [
        {
          "text": "The service’s user identifier associated with the social profile.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "userIdentifier"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.contacts/documentation/Contacts/CNSocialProfile/userIdentifier",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "userIdentifier"
        }
      ],
      "role": "symbol",
      "title": "userIdentifier",
      "type": "topic",
      "url": "/documentation/contacts/cnsocialprofile/useridentifier"
    },
    "doc://com.apple.contacts/documentation/Contacts/CNSocialProfile/username": {
      "abstract": [
        {
          "text": "The user name for the social profile.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "username"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.contacts/documentation/Contacts/CNSocialProfile/username",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "username"
        }
      ],
      "role": "symbol",
      "title": "username",
      "type": "topic",
      "url": "/documentation/contacts/cnsocialprofile/username"
    },
    "doc://com.apple.contacts/documentation/Contacts/CNSocialProfileServiceFacebook": {
      "abstract": [
        {
          "text": "The Facebook social profile service.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CNSocialProfileServiceFacebook"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.contacts/documentation/Contacts/CNSocialProfileServiceFacebook",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CNSocialProfileServiceFacebook"
        }
      ],
      "role": "symbol",
      "title": "CNSocialProfileServiceFacebook",
      "type": "topic",
      "url": "/documentation/contacts/cnsocialprofileservicefacebook"
    },
    "doc://com.apple.contacts/documentation/Contacts/CNSocialProfileServiceFlickr": {
      "abstract": [
        {
          "text": "The Flickr social profile service.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CNSocialProfileServiceFlickr"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.contacts/documentation/Contacts/CNSocialProfileServiceFlickr",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CNSocialProfileServiceFlickr"
        }
      ],
      "role": "symbol",
      "title": "CNSocialProfileServiceFlickr",
      "type": "topic",
      "url": "/documentation/contacts/cnsocialprofileserviceflickr"
    },
    "doc://com.apple.contacts/documentation/Contacts/CNSocialProfileServiceGameCenter": {
      "abstract": [
        {
          "text": "The Game Center social profile service.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CNSocialProfileServiceGameCenter"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.contacts/documentation/Contacts/CNSocialProfileServiceGameCenter",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CNSocialProfileServiceGameCenter"
        }
      ],
      "role": "symbol",
      "title": "CNSocialProfileServiceGameCenter",
      "type": "topic",
      "url": "/documentation/contacts/cnsocialprofileservicegamecenter"
    },
    "doc://com.apple.contacts/documentation/Contacts/CNSocialProfileServiceKey": {
      "abstract": [
        {
          "text": "The social profile service.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CNSocialProfileServiceKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.contacts/documentation/Contacts/CNSocialProfileServiceKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CNSocialProfileServiceKey"
        }
      ],
      "role": "symbol",
      "title": "CNSocialProfileServiceKey",
      "type": "topic",
      "url": "/documentation/contacts/cnsocialprofileservicekey"
    },
    "doc://com.apple.contacts/documentation/Contacts/CNSocialProfileServiceLinkedIn": {
      "abstract": [
        {
          "text": "The LinkedIn social profile service.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CNSocialProfileServiceLinkedIn"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.contacts/documentation/Contacts/CNSocialProfileServiceLinkedIn",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CNSocialProfileServiceLinkedIn"
        }
      ],
      "role": "symbol",
      "title": "CNSocialProfileServiceLinkedIn",
      "type": "topic",
      "url": "/documentation/contacts/cnsocialprofileservicelinkedin"
    },
    "doc://com.apple.contacts/documentation/Contacts/CNSocialProfileServiceMySpace": {
      "abstract": [
        {
          "text": "The MySpace social profile service.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CNSocialProfileServiceMySpace"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.contacts/documentation/Contacts/CNSocialProfileServiceMySpace",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CNSocialProfileServiceMySpace"
        }
      ],
      "role": "symbol",
      "title": "CNSocialProfileServiceMySpace",
      "type": "topic",
      "url": "/documentation/contacts/cnsocialprofileservicemyspace"
    },
    "doc://com.apple.contacts/documentation/Contacts/CNSocialProfileServiceSinaWeibo": {
      "abstract": [
        {
          "text": "The Sina Weibo social profile service.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CNSocialProfileServiceSinaWeibo"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.contacts/documentation/Contacts/CNSocialProfileServiceSinaWeibo",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CNSocialProfileServiceSinaWeibo"
        }
      ],
      "role": "symbol",
      "title": "CNSocialProfileServiceSinaWeibo",
      "type": "topic",
      "url": "/documentation/contacts/cnsocialprofileservicesinaweibo"
    },
    "doc://com.apple.contacts/documentation/Contacts/CNSocialProfileServiceTencentWeibo": {
      "abstract": [
        {
          "text": "The Tencent Weibo social profile service.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CNSocialProfileServiceTencentWeibo"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.contacts/documentation/Contacts/CNSocialProfileServiceTencentWeibo",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CNSocialProfileServiceTencentWeibo"
        }
      ],
      "role": "symbol",
      "title": "CNSocialProfileServiceTencentWeibo",
      "type": "topic",
      "url": "/documentation/contacts/cnsocialprofileservicetencentweibo"
    },
    "doc://com.apple.contacts/documentation/Contacts/CNSocialProfileServiceTwitter": {
      "abstract": [
        {
          "text": "The Twitter social profile service.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CNSocialProfileServiceTwitter"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.contacts/documentation/Contacts/CNSocialProfileServiceTwitter",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CNSocialProfileServiceTwitter"
        }
      ],
      "role": "symbol",
      "title": "CNSocialProfileServiceTwitter",
      "type": "topic",
      "url": "/documentation/contacts/cnsocialprofileservicetwitter"
    },
    "doc://com.apple.contacts/documentation/Contacts/CNSocialProfileServiceYelp": {
      "abstract": [
        {
          "text": "The Yelp social profile service.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CNSocialProfileServiceYelp"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.contacts/documentation/Contacts/CNSocialProfileServiceYelp",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CNSocialProfileServiceYelp"
        }
      ],
      "role": "symbol",
      "title": "CNSocialProfileServiceYelp",
      "type": "topic",
      "url": "/documentation/contacts/cnsocialprofileserviceyelp"
    },
    "doc://com.apple.contacts/documentation/Contacts/CNSocialProfileURLStringKey": {
      "abstract": [
        {
          "text": "The social profile URL.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CNSocialProfileURLStringKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.contacts/documentation/Contacts/CNSocialProfileURLStringKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CNSocialProfileURLStringKey"
        }
      ],
      "role": "symbol",
      "title": "CNSocialProfileURLStringKey",
      "type": "topic",
      "url": "/documentation/contacts/cnsocialprofileurlstringkey"
    },
    "doc://com.apple.contacts/documentation/Contacts/CNSocialProfileUserIdentifierKey": {
      "abstract": [
        {
          "text": "The social profile user identifier.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CNSocialProfileUserIdentifierKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.contacts/documentation/Contacts/CNSocialProfileUserIdentifierKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CNSocialProfileUserIdentifierKey"
        }
      ],
      "role": "symbol",
      "title": "CNSocialProfileUserIdentifierKey",
      "type": "topic",
      "url": "/documentation/contacts/cnsocialprofileuseridentifierkey"
    },
    "doc://com.apple.contacts/documentation/Contacts/CNSocialProfileUsernameKey": {
      "abstract": [
        {
          "text": "The social profile user name.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CNSocialProfileUsernameKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.contacts/documentation/Contacts/CNSocialProfileUsernameKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CNSocialProfileUsernameKey"
        }
      ],
      "role": "symbol",
      "title": "CNSocialProfileUsernameKey",
      "type": "topic",
      "url": "/documentation/contacts/cnsocialprofileusernamekey"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.externally.resolved.symbol/c:objc(cs)NSObject": {
      "abstract": [
        {
          "text": "The root class of most Objective-C class hierarchies, from which subclasses inherit a basic interface to the runtime system and the ability to behave as Objective-C objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "class "
        },
        {
          "kind": "identifier",
          "text": "NSObject"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSObject",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSObject",
      "type": "topic",
      "url": "/documentation/objectivec/nsobject"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)NSCoding": {
      "abstract": [
        {
          "text": "A protocol that enables an object to be encoded and decoded for archiving and distribution.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "protocol "
        },
        {
          "kind": "identifier",
          "text": "NSCoding"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSCoding",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSCoding",
      "type": "topic",
      "url": "/documentation/foundation/nscoding"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)NSCopying": {
      "abstract": [
        {
          "text": "A protocol that objects adopt to provide functional copies of themselves.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "protocol "
        },
        {
          "kind": "identifier",
          "text": "NSCopying"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSCopying",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSCopying",
      "type": "topic",
      "url": "/documentation/foundation/nscopying"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)NSObject": {
      "abstract": [
        {
          "text": "The group of methods that are fundamental to all Objective-C objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "protocol "
        },
        {
          "kind": "identifier",
          "text": "NSObjectProtocol"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSObject",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSObjectProtocol",
      "type": "topic",
      "url": "/documentation/objectivec/nsobjectprotocol"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)NSSecureCoding": {
      "abstract": [
        {
          "text": "A protocol that enables encoding and decoding in a manner that is robust against object substitution attacks.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "protocol "
        },
        {
          "kind": "identifier",
          "text": "NSSecureCoding"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSSecureCoding",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSSecureCoding",
      "type": "topic",
      "url": "/documentation/foundation/nssecurecoding"
    },
    "doc://com.externally.resolved.symbol/s:SH": {
      "abstract": [
        {
          "text": "A type that can be hashed into a `Hasher` to produce an integer hash value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Hashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SQ",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SH",
      "kind": "symbol",
      "role": "symbol",
      "title": "Hashable",
      "type": "topic",
      "url": "/documentation/Swift/Hashable"
    },
    "doc://com.externally.resolved.symbol/s:SQ": {
      "abstract": [
        {
          "text": "A type that can be compared for value equality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SQ",
      "kind": "symbol",
      "role": "symbol",
      "title": "Equatable",
      "type": "topic",
      "url": "/documentation/Swift/Equatable"
    },
    "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP": {
      "abstract": [
        {
          "text": "A type with a customized textual representation.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CustomStringConvertible"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CustomStringConvertible",
      "type": "topic",
      "url": "/documentation/Swift/CustomStringConvertible"
    },
    "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP": {
      "abstract": [
        {
          "text": "A type with a customized textual representation suitable for debugging purposes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CustomDebugStringConvertible"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CustomDebugStringConvertible",
      "type": "topic",
      "url": "/documentation/Swift/CustomDebugStringConvertible"
    },
    "doc://com.externally.resolved.symbol/s:s7CVarArgP": {
      "abstract": [
        {
          "text": "A type whose instances can be encoded, and appropriately passed, as elements of a C `va_list`.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CVarArg"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s7CVarArgP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CVarArg",
      "type": "topic",
      "url": "/documentation/Swift/CVarArg"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/c:objc(cs)NSObject"
      ],
      "kind": "relationships",
      "title": "Inherits From",
      "type": "inheritsFrom"
    },
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:s7CVarArgP",
        "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP",
        "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP",
        "doc://com.externally.resolved.symbol/s:SQ",
        "doc://com.externally.resolved.symbol/s:SH",
        "doc://com.externally.resolved.symbol/c:objc(pl)NSCoding",
        "doc://com.externally.resolved.symbol/c:objc(pl)NSCopying",
        "doc://com.externally.resolved.symbol/c:objc(pl)NSObject",
        "doc://com.externally.resolved.symbol/c:objc(pl)NSSecureCoding"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "topicSections": [
    {
      "anchor": "Creating-a-Social-Profile-Object",
      "identifiers": [
        "doc://com.apple.contacts/documentation/Contacts/CNSocialProfile/init(urlString:username:userIdentifier:service:)"
      ],
      "title": "Creating a Social Profile Object"
    },
    {
      "anchor": "Getting-Social-Profile-Information",
      "identifiers": [
        "doc://com.apple.contacts/documentation/Contacts/CNSocialProfile/username",
        "doc://com.apple.contacts/documentation/Contacts/CNSocialProfile/service",
        "doc://com.apple.contacts/documentation/Contacts/CNSocialProfile/urlString",
        "doc://com.apple.contacts/documentation/Contacts/CNSocialProfile/userIdentifier"
      ],
      "title": "Getting Social Profile Information"
    },
    {
      "anchor": "Getting-Localized-User-Profile-Information",
      "identifiers": [
        "doc://com.apple.contacts/documentation/Contacts/CNSocialProfile/localizedString(forKey:)",
        "doc://com.apple.contacts/documentation/Contacts/CNSocialProfileUsernameKey",
        "doc://com.apple.contacts/documentation/Contacts/CNSocialProfileServiceKey",
        "doc://com.apple.contacts/documentation/Contacts/CNSocialProfileURLStringKey",
        "doc://com.apple.contacts/documentation/Contacts/CNSocialProfileUserIdentifierKey"
      ],
      "title": "Getting Localized User Profile Information"
    },
    {
      "anchor": "Getting-Localized-Service-Names",
      "identifiers": [
        "doc://com.apple.contacts/documentation/Contacts/CNSocialProfile/localizedString(forService:)",
        "doc://com.apple.contacts/documentation/Contacts/CNSocialProfileServiceFacebook",
        "doc://com.apple.contacts/documentation/Contacts/CNSocialProfileServiceFlickr",
        "doc://com.apple.contacts/documentation/Contacts/CNSocialProfileServiceGameCenter",
        "doc://com.apple.contacts/documentation/Contacts/CNSocialProfileServiceLinkedIn",
        "doc://com.apple.contacts/documentation/Contacts/CNSocialProfileServiceMySpace",
        "doc://com.apple.contacts/documentation/Contacts/CNSocialProfileServiceSinaWeibo",
        "doc://com.apple.contacts/documentation/Contacts/CNSocialProfileServiceTencentWeibo",
        "doc://com.apple.contacts/documentation/Contacts/CNSocialProfileServiceTwitter",
        "doc://com.apple.contacts/documentation/Contacts/CNSocialProfileServiceYelp"
      ],
      "title": "Getting Localized Service Names"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "9.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "9.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.1",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.11",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "2.0",
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Class"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "CNSocialProfile"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "class"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CNSocialProfile"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CNSocialProfile"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.contacts/documentation/Contacts"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Creating-a-Social-Profile-Object",
              "identifiers": [
                "doc://com.apple.contacts/documentation/Contacts/CNSocialProfile/init(urlString:username:userIdentifier:service:)"
              ],
              "title": "Creating a Social Profile Object"
            },
            {
              "anchor": "Getting-Social-Profile-Information",
              "identifiers": [
                "doc://com.apple.contacts/documentation/Contacts/CNSocialProfile/username",
                "doc://com.apple.contacts/documentation/Contacts/CNSocialProfile/service",
                "doc://com.apple.contacts/documentation/Contacts/CNSocialProfile/urlString",
                "doc://com.apple.contacts/documentation/Contacts/CNSocialProfile/userIdentifier"
              ],
              "title": "Getting Social Profile Information"
            },
            {
              "anchor": "Getting-Localized-User-Profile-Information",
              "identifiers": [
                "doc://com.apple.contacts/documentation/Contacts/CNSocialProfile/localizedString(forKey:)",
                "doc://com.apple.contacts/documentation/Contacts/CNSocialProfileUsernameKey",
                "doc://com.apple.contacts/documentation/Contacts/CNSocialProfileServiceKey",
                "doc://com.apple.contacts/documentation/Contacts/CNSocialProfileURLStringKey",
                "doc://com.apple.contacts/documentation/Contacts/CNSocialProfileUserIdentifierKey"
              ],
              "title": "Getting Localized User Profile Information"
            },
            {
              "anchor": "Getting-Localized-Service-Names",
              "identifiers": [
                "doc://com.apple.contacts/documentation/Contacts/CNSocialProfile/localizedString(forService:)",
                "doc://com.apple.contacts/documentation/Contacts/CNSocialProfileServiceFacebook",
                "doc://com.apple.contacts/documentation/Contacts/CNSocialProfileServiceFlickr",
                "doc://com.apple.contacts/documentation/Contacts/CNSocialProfileServiceGameCenter",
                "doc://com.apple.contacts/documentation/Contacts/CNSocialProfileServiceLinkedIn",
                "doc://com.apple.contacts/documentation/Contacts/CNSocialProfileServiceMySpace",
                "doc://com.apple.contacts/documentation/Contacts/CNSocialProfileServiceSinaWeibo",
                "doc://com.apple.contacts/documentation/Contacts/CNSocialProfileServiceTencentWeibo",
                "doc://com.apple.contacts/documentation/Contacts/CNSocialProfileServiceTwitter",
                "doc://com.apple.contacts/documentation/Contacts/CNSocialProfileServiceYelp"
              ],
              "title": "Getting Localized Service Names"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": [
            {
              "identifiers": [
                "doc://com.externally.resolved.symbol/c:objc(cs)NSObject"
              ],
              "kind": "relationships",
              "title": "Inherits From",
              "type": "inheritsFrom"
            },
            {
              "identifiers": [
                "doc://com.externally.resolved.symbol/c:objc(pl)NSCopying",
                "doc://com.externally.resolved.symbol/c:objc(pl)NSSecureCoding"
              ],
              "kind": "relationships",
              "title": "Conforms To",
              "type": "conformsTo"
            }
          ]
        },
        {
          "op": "add",
          "path": "/seeAlsoSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "@interface"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "CNSocialProfile"
                  },
                  {
                    "kind": "text",
                    "text": " : "
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSObject",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(cs)NSObject",
                    "text": "NSObject"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.contacts~1documentation~1Contacts~1CNSocialProfile~1service/title",
          "value": "service"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.contacts~1documentation~1Contacts~1CNSocialProfile~1service/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "service"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.contacts~1documentation~1Contacts~1CNSocialProfileServiceFacebook/title",
          "value": "CNSocialProfileServiceFacebook"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.contacts~1documentation~1Contacts~1CNSocialProfileServiceFacebook/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CNSocialProfileServiceFacebook"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.contacts~1documentation~1Contacts~1CNSocialProfileServiceKey/title",
          "value": "CNSocialProfileServiceKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.contacts~1documentation~1Contacts~1CNSocialProfileServiceKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CNSocialProfileServiceKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.contacts~1documentation~1Contacts~1CNSocialProfileServiceSinaWeibo/title",
          "value": "CNSocialProfileServiceSinaWeibo"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.contacts~1documentation~1Contacts~1CNSocialProfileServiceSinaWeibo/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CNSocialProfileServiceSinaWeibo"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:objc(pl)NSObject/title",
          "value": "NSObject"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.contacts~1documentation~1Contacts~1CNSocialProfileServiceYelp/title",
          "value": "CNSocialProfileServiceYelp"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.contacts~1documentation~1Contacts~1CNSocialProfileServiceYelp/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CNSocialProfileServiceYelp"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.contacts~1documentation~1Contacts~1CNSocialProfileServiceMySpace/title",
          "value": "CNSocialProfileServiceMySpace"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.contacts~1documentation~1Contacts~1CNSocialProfileServiceMySpace/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CNSocialProfileServiceMySpace"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.contacts~1documentation~1Contacts~1CNSocialProfileServiceFlickr/title",
          "value": "CNSocialProfileServiceFlickr"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.contacts~1documentation~1Contacts~1CNSocialProfileServiceFlickr/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CNSocialProfileServiceFlickr"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.contacts~1documentation~1Contacts~1CNSocialProfile~1localizedString(forService:)/title",
          "value": "localizedStringForService:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.contacts~1documentation~1Contacts~1CNSocialProfile~1localizedString(forService:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "+ "
            },
            {
              "kind": "identifier",
              "text": "localizedStringForService:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.contacts~1documentation~1Contacts~1CNSocialProfile~1urlString/title",
          "value": "urlString"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.contacts~1documentation~1Contacts~1CNSocialProfile~1urlString/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "urlString"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.contacts~1documentation~1Contacts~1CNSocialProfileUserIdentifierKey/title",
          "value": "CNSocialProfileUserIdentifierKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.contacts~1documentation~1Contacts~1CNSocialProfileUserIdentifierKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CNSocialProfileUserIdentifierKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.contacts~1documentation~1Contacts~1CNSocialProfile/title",
          "value": "CNSocialProfile"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.contacts~1documentation~1Contacts~1CNSocialProfile/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CNSocialProfile"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.contacts~1documentation~1Contacts~1CNSocialProfile/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CNSocialProfile"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.contacts~1documentation~1Contacts~1CNSocialProfile~1userIdentifier/title",
          "value": "userIdentifier"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.contacts~1documentation~1Contacts~1CNSocialProfile~1userIdentifier/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "userIdentifier"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.contacts~1documentation~1Contacts~1CNSocialProfileServiceLinkedIn/title",
          "value": "CNSocialProfileServiceLinkedIn"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.contacts~1documentation~1Contacts~1CNSocialProfileServiceLinkedIn/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CNSocialProfileServiceLinkedIn"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.contacts~1documentation~1Contacts~1CNSocialProfileUsernameKey/title",
          "value": "CNSocialProfileUsernameKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.contacts~1documentation~1Contacts~1CNSocialProfileUsernameKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CNSocialProfileUsernameKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.contacts~1documentation~1Contacts~1CNSocialProfile~1init(urlString:username:userIdentifier:service:)/title",
          "value": "initWithUrlString:username:userIdentifier:service:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.contacts~1documentation~1Contacts~1CNSocialProfile~1init(urlString:username:userIdentifier:service:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "initWithUrlString:username:userIdentifier:service:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.contacts~1documentation~1Contacts~1CNSocialProfileURLStringKey/title",
          "value": "CNSocialProfileURLStringKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.contacts~1documentation~1Contacts~1CNSocialProfileURLStringKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CNSocialProfileURLStringKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.contacts~1documentation~1Contacts~1CNSocialProfileServiceTencentWeibo/title",
          "value": "CNSocialProfileServiceTencentWeibo"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.contacts~1documentation~1Contacts~1CNSocialProfileServiceTencentWeibo/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CNSocialProfileServiceTencentWeibo"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.contacts~1documentation~1Contacts~1CNSocialProfileServiceGameCenter/title",
          "value": "CNSocialProfileServiceGameCenter"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.contacts~1documentation~1Contacts~1CNSocialProfileServiceGameCenter/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CNSocialProfileServiceGameCenter"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.contacts~1documentation~1Contacts~1CNSocialProfileServiceTwitter/title",
          "value": "CNSocialProfileServiceTwitter"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.contacts~1documentation~1Contacts~1CNSocialProfileServiceTwitter/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CNSocialProfileServiceTwitter"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.contacts~1documentation~1Contacts~1CNSocialProfile~1username/title",
          "value": "username"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.contacts~1documentation~1Contacts~1CNSocialProfile~1username/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "username"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.contacts~1documentation~1Contacts~1CNSocialProfile~1localizedString(forKey:)/title",
          "value": "localizedStringForKey:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.contacts~1documentation~1Contacts~1CNSocialProfile~1localizedString(forKey:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "+ "
            },
            {
              "kind": "identifier",
              "text": "localizedStringForKey:"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/contacts/cnsocialprofile"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/contacts/cnsocialprofile"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
