{
  "abstract": [
    {
      "text": "Specify contact-related properties during fetch operations.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.contacts/documentation/Contacts"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.contacts/documentation/Contacts/contact-keys"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "Contacts"
      }
    ],
    "role": "collectionGroup",
    "roleHeading": "API Collection",
    "title": "Contact Keys"
  },
  "references": {
    "doc://com.apple.contacts/documentation/Contacts": {
      "abstract": [
        {
          "text": "Access the user’s contacts, and format and localize contact information.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.contacts/documentation/Contacts",
      "kind": "symbol",
      "role": "collection",
      "title": "Contacts",
      "type": "topic",
      "url": "/documentation/contacts"
    },
    "doc://com.apple.contacts/documentation/Contacts/CNContact": {
      "abstract": [
        {
          "text": "An immutable object that stores information about a single contact, such as the contact’s first name, phone numbers, and addresses.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CNContact"
        }
      ],
      "identifier": "doc://com.apple.contacts/documentation/Contacts/CNContact",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CNContact"
        }
      ],
      "role": "symbol",
      "title": "CNContact",
      "type": "topic",
      "url": "/documentation/contacts/cncontact"
    },
    "doc://com.apple.contacts/documentation/Contacts/CNContactBirthdayKey": {
      "abstract": [
        {
          "text": "The birthday of a contact.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CNContactBirthdayKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.contacts/documentation/Contacts/CNContactBirthdayKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CNContactBirthdayKey"
        }
      ],
      "role": "symbol",
      "title": "CNContactBirthdayKey",
      "type": "topic",
      "url": "/documentation/contacts/cncontactbirthdaykey"
    },
    "doc://com.apple.contacts/documentation/Contacts/CNContactDatesKey": {
      "abstract": [
        {
          "text": "Dates associated with a contact.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CNContactDatesKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.contacts/documentation/Contacts/CNContactDatesKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CNContactDatesKey"
        }
      ],
      "role": "symbol",
      "title": "CNContactDatesKey",
      "type": "topic",
      "url": "/documentation/contacts/cncontactdateskey"
    },
    "doc://com.apple.contacts/documentation/Contacts/CNContactDepartmentNameKey": {
      "abstract": [
        {
          "text": "The contact’s department name.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CNContactDepartmentNameKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.contacts/documentation/Contacts/CNContactDepartmentNameKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CNContactDepartmentNameKey"
        }
      ],
      "role": "symbol",
      "title": "CNContactDepartmentNameKey",
      "type": "topic",
      "url": "/documentation/contacts/cncontactdepartmentnamekey"
    },
    "doc://com.apple.contacts/documentation/Contacts/CNContactEmailAddressesKey": {
      "abstract": [
        {
          "text": "The email addresses of the contact.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CNContactEmailAddressesKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.contacts/documentation/Contacts/CNContactEmailAddressesKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CNContactEmailAddressesKey"
        }
      ],
      "role": "symbol",
      "title": "CNContactEmailAddressesKey",
      "type": "topic",
      "url": "/documentation/contacts/cncontactemailaddresseskey"
    },
    "doc://com.apple.contacts/documentation/Contacts/CNContactFamilyNameKey": {
      "abstract": [
        {
          "text": "The contact’s family name.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CNContactFamilyNameKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.contacts/documentation/Contacts/CNContactFamilyNameKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CNContactFamilyNameKey"
        }
      ],
      "role": "symbol",
      "title": "CNContactFamilyNameKey",
      "type": "topic",
      "url": "/documentation/contacts/cncontactfamilynamekey"
    },
    "doc://com.apple.contacts/documentation/Contacts/CNContactGivenNameKey": {
      "abstract": [
        {
          "text": "The contact’s given name.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CNContactGivenNameKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.contacts/documentation/Contacts/CNContactGivenNameKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CNContactGivenNameKey"
        }
      ],
      "role": "symbol",
      "title": "CNContactGivenNameKey",
      "type": "topic",
      "url": "/documentation/contacts/cncontactgivennamekey"
    },
    "doc://com.apple.contacts/documentation/Contacts/CNContactIdentifierKey": {
      "abstract": [
        {
          "text": "The contact’s unique identifier.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CNContactIdentifierKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.contacts/documentation/Contacts/CNContactIdentifierKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CNContactIdentifierKey"
        }
      ],
      "role": "symbol",
      "title": "CNContactIdentifierKey",
      "type": "topic",
      "url": "/documentation/contacts/cncontactidentifierkey"
    },
    "doc://com.apple.contacts/documentation/Contacts/CNContactImageDataAvailableKey": {
      "abstract": [
        {
          "text": "Image data availability for a contact.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CNContactImageDataAvailableKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.contacts/documentation/Contacts/CNContactImageDataAvailableKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CNContactImageDataAvailableKey"
        }
      ],
      "role": "symbol",
      "title": "CNContactImageDataAvailableKey",
      "type": "topic",
      "url": "/documentation/contacts/cncontactimagedataavailablekey"
    },
    "doc://com.apple.contacts/documentation/Contacts/CNContactImageDataKey": {
      "abstract": [
        {
          "text": "Image data for a contact.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CNContactImageDataKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.contacts/documentation/Contacts/CNContactImageDataKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CNContactImageDataKey"
        }
      ],
      "role": "symbol",
      "title": "CNContactImageDataKey",
      "type": "topic",
      "url": "/documentation/contacts/cncontactimagedatakey"
    },
    "doc://com.apple.contacts/documentation/Contacts/CNContactInstantMessageAddressesKey": {
      "abstract": [
        {
          "text": "The instant message addresses of the contact.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CNContactInstantMessageAddressesKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.contacts/documentation/Contacts/CNContactInstantMessageAddressesKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CNContactInstantMessageAddressesKey"
        }
      ],
      "role": "symbol",
      "title": "CNContactInstantMessageAddressesKey",
      "type": "topic",
      "url": "/documentation/contacts/cncontactinstantmessageaddresseskey"
    },
    "doc://com.apple.contacts/documentation/Contacts/CNContactJobTitleKey": {
      "abstract": [
        {
          "text": "The contact’s job title.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CNContactJobTitleKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.contacts/documentation/Contacts/CNContactJobTitleKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CNContactJobTitleKey"
        }
      ],
      "role": "symbol",
      "title": "CNContactJobTitleKey",
      "type": "topic",
      "url": "/documentation/contacts/cncontactjobtitlekey"
    },
    "doc://com.apple.contacts/documentation/Contacts/CNContactMiddleNameKey": {
      "abstract": [
        {
          "text": "The contact’s middle name.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CNContactMiddleNameKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.contacts/documentation/Contacts/CNContactMiddleNameKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CNContactMiddleNameKey"
        }
      ],
      "role": "symbol",
      "title": "CNContactMiddleNameKey",
      "type": "topic",
      "url": "/documentation/contacts/cncontactmiddlenamekey"
    },
    "doc://com.apple.contacts/documentation/Contacts/CNContactNamePrefixKey": {
      "abstract": [
        {
          "text": "The prefix for the contact’s name.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CNContactNamePrefixKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.contacts/documentation/Contacts/CNContactNamePrefixKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CNContactNamePrefixKey"
        }
      ],
      "role": "symbol",
      "title": "CNContactNamePrefixKey",
      "type": "topic",
      "url": "/documentation/contacts/cncontactnameprefixkey"
    },
    "doc://com.apple.contacts/documentation/Contacts/CNContactNameSuffixKey": {
      "abstract": [
        {
          "text": "The contact’s name suffix.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CNContactNameSuffixKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.contacts/documentation/Contacts/CNContactNameSuffixKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CNContactNameSuffixKey"
        }
      ],
      "role": "symbol",
      "title": "CNContactNameSuffixKey",
      "type": "topic",
      "url": "/documentation/contacts/cncontactnamesuffixkey"
    },
    "doc://com.apple.contacts/documentation/Contacts/CNContactNicknameKey": {
      "abstract": [
        {
          "text": "The contact’s nickname.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CNContactNicknameKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.contacts/documentation/Contacts/CNContactNicknameKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CNContactNicknameKey"
        }
      ],
      "role": "symbol",
      "title": "CNContactNicknameKey",
      "type": "topic",
      "url": "/documentation/contacts/cncontactnicknamekey"
    },
    "doc://com.apple.contacts/documentation/Contacts/CNContactNonGregorianBirthdayKey": {
      "abstract": [
        {
          "text": "The non-Gregorian birthday of the contact.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CNContactNonGregorianBirthdayKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.contacts/documentation/Contacts/CNContactNonGregorianBirthdayKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CNContactNonGregorianBirthdayKey"
        }
      ],
      "role": "symbol",
      "title": "CNContactNonGregorianBirthdayKey",
      "type": "topic",
      "url": "/documentation/contacts/cncontactnongregorianbirthdaykey"
    },
    "doc://com.apple.contacts/documentation/Contacts/CNContactNoteKey": {
      "abstract": [
        {
          "text": "A note associated with a contact.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CNContactNoteKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.contacts/documentation/Contacts/CNContactNoteKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CNContactNoteKey"
        }
      ],
      "role": "symbol",
      "title": "CNContactNoteKey",
      "type": "topic",
      "url": "/documentation/contacts/cncontactnotekey"
    },
    "doc://com.apple.contacts/documentation/Contacts/CNContactOrganizationNameKey": {
      "abstract": [
        {
          "text": "The contact’s organization name.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CNContactOrganizationNameKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.contacts/documentation/Contacts/CNContactOrganizationNameKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CNContactOrganizationNameKey"
        }
      ],
      "role": "symbol",
      "title": "CNContactOrganizationNameKey",
      "type": "topic",
      "url": "/documentation/contacts/cncontactorganizationnamekey"
    },
    "doc://com.apple.contacts/documentation/Contacts/CNContactPhoneNumbersKey": {
      "abstract": [
        {
          "text": "A phone numbers of a contact.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CNContactPhoneNumbersKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.contacts/documentation/Contacts/CNContactPhoneNumbersKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CNContactPhoneNumbersKey"
        }
      ],
      "role": "symbol",
      "title": "CNContactPhoneNumbersKey",
      "type": "topic",
      "url": "/documentation/contacts/cncontactphonenumberskey"
    },
    "doc://com.apple.contacts/documentation/Contacts/CNContactPhoneticFamilyNameKey": {
      "abstract": [
        {
          "text": "The phonetic spelling of the contact’s family name.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CNContactPhoneticFamilyNameKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.contacts/documentation/Contacts/CNContactPhoneticFamilyNameKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CNContactPhoneticFamilyNameKey"
        }
      ],
      "role": "symbol",
      "title": "CNContactPhoneticFamilyNameKey",
      "type": "topic",
      "url": "/documentation/contacts/cncontactphoneticfamilynamekey"
    },
    "doc://com.apple.contacts/documentation/Contacts/CNContactPhoneticGivenNameKey": {
      "abstract": [
        {
          "text": "The phonetic spelling of the contact’s  given name.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CNContactPhoneticGivenNameKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.contacts/documentation/Contacts/CNContactPhoneticGivenNameKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CNContactPhoneticGivenNameKey"
        }
      ],
      "role": "symbol",
      "title": "CNContactPhoneticGivenNameKey",
      "type": "topic",
      "url": "/documentation/contacts/cncontactphoneticgivennamekey"
    },
    "doc://com.apple.contacts/documentation/Contacts/CNContactPhoneticMiddleNameKey": {
      "abstract": [
        {
          "text": "The phonetic spelling of the contact’s middle name.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CNContactPhoneticMiddleNameKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.contacts/documentation/Contacts/CNContactPhoneticMiddleNameKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CNContactPhoneticMiddleNameKey"
        }
      ],
      "role": "symbol",
      "title": "CNContactPhoneticMiddleNameKey",
      "type": "topic",
      "url": "/documentation/contacts/cncontactphoneticmiddlenamekey"
    },
    "doc://com.apple.contacts/documentation/Contacts/CNContactPhoneticOrganizationNameKey": {
      "abstract": [
        {
          "text": "The phonetic spelling of the contact’s organization name.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CNContactPhoneticOrganizationNameKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.contacts/documentation/Contacts/CNContactPhoneticOrganizationNameKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CNContactPhoneticOrganizationNameKey"
        }
      ],
      "role": "symbol",
      "title": "CNContactPhoneticOrganizationNameKey",
      "type": "topic",
      "url": "/documentation/contacts/cncontactphoneticorganizationnamekey"
    },
    "doc://com.apple.contacts/documentation/Contacts/CNContactPostalAddressesKey": {
      "abstract": [
        {
          "text": "The postal addresses of the contact.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CNContactPostalAddressesKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.contacts/documentation/Contacts/CNContactPostalAddressesKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CNContactPostalAddressesKey"
        }
      ],
      "role": "symbol",
      "title": "CNContactPostalAddressesKey",
      "type": "topic",
      "url": "/documentation/contacts/cncontactpostaladdresseskey"
    },
    "doc://com.apple.contacts/documentation/Contacts/CNContactPreviousFamilyNameKey": {
      "abstract": [
        {
          "text": "The contact’s previous family name.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CNContactPreviousFamilyNameKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.contacts/documentation/Contacts/CNContactPreviousFamilyNameKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CNContactPreviousFamilyNameKey"
        }
      ],
      "role": "symbol",
      "title": "CNContactPreviousFamilyNameKey",
      "type": "topic",
      "url": "/documentation/contacts/cncontactpreviousfamilynamekey"
    },
    "doc://com.apple.contacts/documentation/Contacts/CNContactPropertyAttribute": {
      "abstract": [
        {
          "text": "The contact’s name component property key.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CNContactPropertyAttribute"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.contacts/documentation/Contacts/CNContactPropertyAttribute",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CNContactPropertyAttribute"
        }
      ],
      "role": "symbol",
      "title": "CNContactPropertyAttribute",
      "type": "topic",
      "url": "/documentation/contacts/cncontactpropertyattribute"
    },
    "doc://com.apple.contacts/documentation/Contacts/CNContactRelationsKey": {
      "abstract": [
        {
          "text": "The relationships of the contact.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CNContactRelationsKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.contacts/documentation/Contacts/CNContactRelationsKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CNContactRelationsKey"
        }
      ],
      "role": "symbol",
      "title": "CNContactRelationsKey",
      "type": "topic",
      "url": "/documentation/contacts/cncontactrelationskey"
    },
    "doc://com.apple.contacts/documentation/Contacts/CNContactSocialProfilesKey": {
      "abstract": [
        {
          "text": "A social profiles of a contact.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CNContactSocialProfilesKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.contacts/documentation/Contacts/CNContactSocialProfilesKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CNContactSocialProfilesKey"
        }
      ],
      "role": "symbol",
      "title": "CNContactSocialProfilesKey",
      "type": "topic",
      "url": "/documentation/contacts/cncontactsocialprofileskey"
    },
    "doc://com.apple.contacts/documentation/Contacts/CNContactThumbnailImageDataKey": {
      "abstract": [
        {
          "text": "Thumbnail data for a contact.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CNContactThumbnailImageDataKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.contacts/documentation/Contacts/CNContactThumbnailImageDataKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CNContactThumbnailImageDataKey"
        }
      ],
      "role": "symbol",
      "title": "CNContactThumbnailImageDataKey",
      "type": "topic",
      "url": "/documentation/contacts/cncontactthumbnailimagedatakey"
    },
    "doc://com.apple.contacts/documentation/Contacts/CNContactTypeKey": {
      "abstract": [
        {
          "text": "The type of contact.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CNContactTypeKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.contacts/documentation/Contacts/CNContactTypeKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CNContactTypeKey"
        }
      ],
      "role": "symbol",
      "title": "CNContactTypeKey",
      "type": "topic",
      "url": "/documentation/contacts/cncontacttypekey"
    },
    "doc://com.apple.contacts/documentation/Contacts/CNContactUrlAddressesKey": {
      "abstract": [
        {
          "text": "The URL addresses of the contact.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CNContactUrlAddressesKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.contacts/documentation/Contacts/CNContactUrlAddressesKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CNContactUrlAddressesKey"
        }
      ],
      "role": "symbol",
      "title": "CNContactUrlAddressesKey",
      "type": "topic",
      "url": "/documentation/contacts/cncontacturladdresseskey"
    },
    "doc://com.apple.contacts/documentation/Contacts/CNContainerNameKey": {
      "abstract": [
        {
          "text": "The name of the container.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CNContainerNameKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.contacts/documentation/Contacts/CNContainerNameKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CNContainerNameKey"
        }
      ],
      "role": "symbol",
      "title": "CNContainerNameKey",
      "type": "topic",
      "url": "/documentation/contacts/cncontainernamekey"
    },
    "doc://com.apple.contacts/documentation/Contacts/CNContainerTypeKey": {
      "abstract": [
        {
          "text": "The type of the container.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CNContainerTypeKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.contacts/documentation/Contacts/CNContainerTypeKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CNContainerTypeKey"
        }
      ],
      "role": "symbol",
      "title": "CNContainerTypeKey",
      "type": "topic",
      "url": "/documentation/contacts/cncontainertypekey"
    },
    "doc://com.apple.contacts/documentation/Contacts/CNGroupIdentifierKey": {
      "abstract": [
        {
          "text": "The identifier of the group.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CNGroupIdentifierKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.contacts/documentation/Contacts/CNGroupIdentifierKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CNGroupIdentifierKey"
        }
      ],
      "role": "symbol",
      "title": "CNGroupIdentifierKey",
      "type": "topic",
      "url": "/documentation/contacts/cngroupidentifierkey"
    },
    "doc://com.apple.contacts/documentation/Contacts/CNGroupNameKey": {
      "abstract": [
        {
          "text": "The name of the group.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CNGroupNameKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.contacts/documentation/Contacts/CNGroupNameKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CNGroupNameKey"
        }
      ],
      "role": "symbol",
      "title": "CNGroupNameKey",
      "type": "topic",
      "url": "/documentation/contacts/cngroupnamekey"
    },
    "doc://com.apple.contacts/documentation/Contacts/CNInstantMessageAddressServiceKey": {
      "abstract": [
        {
          "text": "Instant message address service key.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CNInstantMessageAddressServiceKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.contacts/documentation/Contacts/CNInstantMessageAddressServiceKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CNInstantMessageAddressServiceKey"
        }
      ],
      "role": "symbol",
      "title": "CNInstantMessageAddressServiceKey",
      "type": "topic",
      "url": "/documentation/contacts/cninstantmessageaddressservicekey"
    },
    "doc://com.apple.contacts/documentation/Contacts/CNInstantMessageAddressUsernameKey": {
      "abstract": [
        {
          "text": "Instant message address username key.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CNInstantMessageAddressUsernameKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.contacts/documentation/Contacts/CNInstantMessageAddressUsernameKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CNInstantMessageAddressUsernameKey"
        }
      ],
      "role": "symbol",
      "title": "CNInstantMessageAddressUsernameKey",
      "type": "topic",
      "url": "/documentation/contacts/cninstantmessageaddressusernamekey"
    },
    "doc://com.apple.contacts/documentation/Contacts/CNKeyDescriptor": {
      "abstract": [
        {
          "text": "This protocol is reserved for Contacts framework usage.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CNKeyDescriptor"
        }
      ],
      "identifier": "doc://com.apple.contacts/documentation/Contacts/CNKeyDescriptor",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CNKeyDescriptor"
        }
      ],
      "role": "symbol",
      "title": "CNKeyDescriptor",
      "type": "topic",
      "url": "/documentation/contacts/cnkeydescriptor"
    },
    "doc://com.apple.contacts/documentation/Contacts/CNMutableContact": {
      "abstract": [
        {
          "text": "A mutable object that stores information about a single contact, such as the contact’s first name, phone numbers, and addresses.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CNMutableContact"
        }
      ],
      "identifier": "doc://com.apple.contacts/documentation/Contacts/CNMutableContact",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CNMutableContact"
        }
      ],
      "role": "symbol",
      "title": "CNMutableContact",
      "type": "topic",
      "url": "/documentation/contacts/cnmutablecontact"
    },
    "doc://com.apple.contacts/documentation/Contacts/CNSocialProfileServiceKey": {
      "abstract": [
        {
          "text": "The social profile service.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CNSocialProfileServiceKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.contacts/documentation/Contacts/CNSocialProfileServiceKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CNSocialProfileServiceKey"
        }
      ],
      "role": "symbol",
      "title": "CNSocialProfileServiceKey",
      "type": "topic",
      "url": "/documentation/contacts/cnsocialprofileservicekey"
    },
    "doc://com.apple.contacts/documentation/Contacts/CNSocialProfileURLStringKey": {
      "abstract": [
        {
          "text": "The social profile URL.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CNSocialProfileURLStringKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.contacts/documentation/Contacts/CNSocialProfileURLStringKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CNSocialProfileURLStringKey"
        }
      ],
      "role": "symbol",
      "title": "CNSocialProfileURLStringKey",
      "type": "topic",
      "url": "/documentation/contacts/cnsocialprofileurlstringkey"
    },
    "doc://com.apple.contacts/documentation/Contacts/CNSocialProfileUserIdentifierKey": {
      "abstract": [
        {
          "text": "The social profile user identifier.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CNSocialProfileUserIdentifierKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.contacts/documentation/Contacts/CNSocialProfileUserIdentifierKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CNSocialProfileUserIdentifierKey"
        }
      ],
      "role": "symbol",
      "title": "CNSocialProfileUserIdentifierKey",
      "type": "topic",
      "url": "/documentation/contacts/cnsocialprofileuseridentifierkey"
    },
    "doc://com.apple.contacts/documentation/Contacts/CNSocialProfileUsernameKey": {
      "abstract": [
        {
          "text": "The social profile user name.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CNSocialProfileUsernameKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.contacts/documentation/Contacts/CNSocialProfileUsernameKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CNSocialProfileUsernameKey"
        }
      ],
      "role": "symbol",
      "title": "CNSocialProfileUsernameKey",
      "type": "topic",
      "url": "/documentation/contacts/cnsocialprofileusernamekey"
    },
    "doc://com.apple.contacts/documentation/Contacts/data-objects": {
      "abstract": [
        {
          "text": "Access contact-related data, such as the user’s postal address and phone number.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.contacts/documentation/Contacts/data-objects",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Data Objects",
      "type": "topic",
      "url": "/documentation/contacts/data-objects"
    },
    "doc://com.apple.documentation/documentation/BundleResources/Entitlements/com.apple.developer.contacts.notes": {
      "abstract": [
        {
          "text": "A Boolean value that indicates whether the app may access the notes in contact entries.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/BundleResources/Entitlements/com.apple.developer.contacts.notes",
      "kind": "symbol",
      "role": "symbol",
      "title": "com.apple.developer.contacts.notes",
      "type": "topic",
      "url": "/documentation/BundleResources/Entitlements/com.apple.developer.contacts.notes"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Contact-data",
      "generated": true,
      "identifiers": [
        "doc://com.apple.contacts/documentation/Contacts/CNContact",
        "doc://com.apple.contacts/documentation/Contacts/CNMutableContact",
        "doc://com.apple.contacts/documentation/Contacts/data-objects"
      ],
      "title": "Contact data"
    }
  ],
  "topicSections": [
    {
      "anchor": "Contact-Identification",
      "identifiers": [
        "doc://com.apple.contacts/documentation/Contacts/CNContactIdentifierKey",
        "doc://com.apple.contacts/documentation/Contacts/CNContactTypeKey",
        "doc://com.apple.contacts/documentation/Contacts/CNContactPropertyAttribute"
      ],
      "title": "Contact Identification"
    },
    {
      "anchor": "Name",
      "identifiers": [
        "doc://com.apple.contacts/documentation/Contacts/CNContactNamePrefixKey",
        "doc://com.apple.contacts/documentation/Contacts/CNContactGivenNameKey",
        "doc://com.apple.contacts/documentation/Contacts/CNContactMiddleNameKey",
        "doc://com.apple.contacts/documentation/Contacts/CNContactFamilyNameKey",
        "doc://com.apple.contacts/documentation/Contacts/CNContactPreviousFamilyNameKey",
        "doc://com.apple.contacts/documentation/Contacts/CNContactNameSuffixKey",
        "doc://com.apple.contacts/documentation/Contacts/CNContactNicknameKey",
        "doc://com.apple.contacts/documentation/Contacts/CNContactPhoneticGivenNameKey",
        "doc://com.apple.contacts/documentation/Contacts/CNContactPhoneticMiddleNameKey",
        "doc://com.apple.contacts/documentation/Contacts/CNContactPhoneticFamilyNameKey"
      ],
      "title": "Name"
    },
    {
      "anchor": "Work",
      "identifiers": [
        "doc://com.apple.contacts/documentation/Contacts/CNContactJobTitleKey",
        "doc://com.apple.contacts/documentation/Contacts/CNContactDepartmentNameKey",
        "doc://com.apple.contacts/documentation/Contacts/CNContactOrganizationNameKey",
        "doc://com.apple.contacts/documentation/Contacts/CNContactPhoneticOrganizationNameKey"
      ],
      "title": "Work"
    },
    {
      "anchor": "Addresses",
      "identifiers": [
        "doc://com.apple.contacts/documentation/Contacts/CNContactPostalAddressesKey",
        "doc://com.apple.contacts/documentation/Contacts/CNContactEmailAddressesKey",
        "doc://com.apple.contacts/documentation/Contacts/CNContactUrlAddressesKey",
        "doc://com.apple.contacts/documentation/Contacts/CNContactInstantMessageAddressesKey"
      ],
      "title": "Addresses"
    },
    {
      "anchor": "Phone",
      "identifiers": [
        "doc://com.apple.contacts/documentation/Contacts/CNContactPhoneNumbersKey"
      ],
      "title": "Phone"
    },
    {
      "anchor": "Social-Profiles",
      "identifiers": [
        "doc://com.apple.contacts/documentation/Contacts/CNContactSocialProfilesKey"
      ],
      "title": "Social Profiles"
    },
    {
      "anchor": "Birthday",
      "identifiers": [
        "doc://com.apple.contacts/documentation/Contacts/CNContactBirthdayKey",
        "doc://com.apple.contacts/documentation/Contacts/CNContactNonGregorianBirthdayKey",
        "doc://com.apple.contacts/documentation/Contacts/CNContactDatesKey"
      ],
      "title": "Birthday"
    },
    {
      "anchor": "Notes",
      "identifiers": [
        "doc://com.apple.contacts/documentation/Contacts/CNContactNoteKey",
        "doc://com.apple.documentation/documentation/BundleResources/Entitlements/com.apple.developer.contacts.notes"
      ],
      "title": "Notes"
    },
    {
      "anchor": "Images",
      "identifiers": [
        "doc://com.apple.contacts/documentation/Contacts/CNContactImageDataKey",
        "doc://com.apple.contacts/documentation/Contacts/CNContactThumbnailImageDataKey",
        "doc://com.apple.contacts/documentation/Contacts/CNContactImageDataAvailableKey"
      ],
      "title": "Images"
    },
    {
      "anchor": "Relationships",
      "identifiers": [
        "doc://com.apple.contacts/documentation/Contacts/CNContactRelationsKey"
      ],
      "title": "Relationships"
    },
    {
      "anchor": "Groups-and-Containers",
      "identifiers": [
        "doc://com.apple.contacts/documentation/Contacts/CNGroupNameKey",
        "doc://com.apple.contacts/documentation/Contacts/CNGroupIdentifierKey",
        "doc://com.apple.contacts/documentation/Contacts/CNContainerNameKey",
        "doc://com.apple.contacts/documentation/Contacts/CNContainerTypeKey"
      ],
      "title": "Groups and Containers"
    },
    {
      "anchor": "Instant-Messaging-Keys",
      "identifiers": [
        "doc://com.apple.contacts/documentation/Contacts/CNInstantMessageAddressServiceKey",
        "doc://com.apple.contacts/documentation/Contacts/CNInstantMessageAddressUsernameKey"
      ],
      "title": "Instant Messaging Keys"
    },
    {
      "anchor": "Social-Profile-Keys",
      "identifiers": [
        "doc://com.apple.contacts/documentation/Contacts/CNSocialProfileServiceKey",
        "doc://com.apple.contacts/documentation/Contacts/CNSocialProfileURLStringKey",
        "doc://com.apple.contacts/documentation/Contacts/CNSocialProfileUsernameKey",
        "doc://com.apple.contacts/documentation/Contacts/CNSocialProfileUserIdentifierKey"
      ],
      "title": "Social Profile Keys"
    },
    {
      "anchor": "Key-Descriptors",
      "identifiers": [
        "doc://com.apple.contacts/documentation/Contacts/CNKeyDescriptor"
      ],
      "title": "Key Descriptors"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Contact-Identification",
              "identifiers": [
                "doc://com.apple.contacts/documentation/Contacts/CNContactIdentifierKey",
                "doc://com.apple.contacts/documentation/Contacts/CNContactTypeKey",
                "doc://com.apple.contacts/documentation/Contacts/CNContactPropertyAttribute"
              ],
              "title": "Contact Identification"
            },
            {
              "anchor": "Name",
              "identifiers": [
                "doc://com.apple.contacts/documentation/Contacts/CNContactNamePrefixKey",
                "doc://com.apple.contacts/documentation/Contacts/CNContactGivenNameKey",
                "doc://com.apple.contacts/documentation/Contacts/CNContactMiddleNameKey",
                "doc://com.apple.contacts/documentation/Contacts/CNContactFamilyNameKey",
                "doc://com.apple.contacts/documentation/Contacts/CNContactPreviousFamilyNameKey",
                "doc://com.apple.contacts/documentation/Contacts/CNContactNameSuffixKey",
                "doc://com.apple.contacts/documentation/Contacts/CNContactNicknameKey",
                "doc://com.apple.contacts/documentation/Contacts/CNContactPhoneticGivenNameKey",
                "doc://com.apple.contacts/documentation/Contacts/CNContactPhoneticMiddleNameKey",
                "doc://com.apple.contacts/documentation/Contacts/CNContactPhoneticFamilyNameKey"
              ],
              "title": "Name"
            },
            {
              "anchor": "Work",
              "identifiers": [
                "doc://com.apple.contacts/documentation/Contacts/CNContactJobTitleKey",
                "doc://com.apple.contacts/documentation/Contacts/CNContactDepartmentNameKey",
                "doc://com.apple.contacts/documentation/Contacts/CNContactOrganizationNameKey",
                "doc://com.apple.contacts/documentation/Contacts/CNContactPhoneticOrganizationNameKey"
              ],
              "title": "Work"
            },
            {
              "anchor": "Addresses",
              "identifiers": [
                "doc://com.apple.contacts/documentation/Contacts/CNContactPostalAddressesKey",
                "doc://com.apple.contacts/documentation/Contacts/CNContactEmailAddressesKey",
                "doc://com.apple.contacts/documentation/Contacts/CNContactUrlAddressesKey",
                "doc://com.apple.contacts/documentation/Contacts/CNContactInstantMessageAddressesKey"
              ],
              "title": "Addresses"
            },
            {
              "anchor": "Phone",
              "identifiers": [
                "doc://com.apple.contacts/documentation/Contacts/CNContactPhoneNumbersKey"
              ],
              "title": "Phone"
            },
            {
              "anchor": "Social-Profiles",
              "identifiers": [
                "doc://com.apple.contacts/documentation/Contacts/CNContactSocialProfilesKey"
              ],
              "title": "Social Profiles"
            },
            {
              "anchor": "Birthday",
              "identifiers": [
                "doc://com.apple.contacts/documentation/Contacts/CNContactBirthdayKey",
                "doc://com.apple.contacts/documentation/Contacts/CNContactNonGregorianBirthdayKey",
                "doc://com.apple.contacts/documentation/Contacts/CNContactDatesKey"
              ],
              "title": "Birthday"
            },
            {
              "anchor": "Notes",
              "identifiers": [
                "doc://com.apple.contacts/documentation/Contacts/CNContactNoteKey",
                "doc://com.apple.documentation/documentation/BundleResources/Entitlements/com.apple.developer.contacts.notes"
              ],
              "title": "Notes"
            },
            {
              "anchor": "Images",
              "identifiers": [
                "doc://com.apple.contacts/documentation/Contacts/CNContactImageDataKey",
                "doc://com.apple.contacts/documentation/Contacts/CNContactThumbnailImageDataKey",
                "doc://com.apple.contacts/documentation/Contacts/CNContactImageDataAvailableKey"
              ],
              "title": "Images"
            },
            {
              "anchor": "Relationships",
              "identifiers": [
                "doc://com.apple.contacts/documentation/Contacts/CNContactRelationsKey"
              ],
              "title": "Relationships"
            },
            {
              "anchor": "Groups-and-Containers",
              "identifiers": [
                "doc://com.apple.contacts/documentation/Contacts/CNGroupNameKey",
                "doc://com.apple.contacts/documentation/Contacts/CNGroupIdentifierKey",
                "doc://com.apple.contacts/documentation/Contacts/CNContainerNameKey",
                "doc://com.apple.contacts/documentation/Contacts/CNContainerTypeKey"
              ],
              "title": "Groups and Containers"
            },
            {
              "anchor": "Instant-Messaging-Keys",
              "identifiers": [
                "doc://com.apple.contacts/documentation/Contacts/CNInstantMessageAddressServiceKey",
                "doc://com.apple.contacts/documentation/Contacts/CNInstantMessageAddressUsernameKey"
              ],
              "title": "Instant Messaging Keys"
            },
            {
              "anchor": "Social-Profile-Keys",
              "identifiers": [
                "doc://com.apple.contacts/documentation/Contacts/CNSocialProfileServiceKey",
                "doc://com.apple.contacts/documentation/Contacts/CNSocialProfileURLStringKey",
                "doc://com.apple.contacts/documentation/Contacts/CNSocialProfileUsernameKey",
                "doc://com.apple.contacts/documentation/Contacts/CNSocialProfileUserIdentifierKey"
              ],
              "title": "Social Profile Keys"
            },
            {
              "anchor": "Key-Descriptors",
              "identifiers": [
                "doc://com.apple.contacts/documentation/Contacts/CNKeyDescriptor"
              ],
              "title": "Key Descriptors"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Contact-data",
              "generated": true,
              "identifiers": [
                "doc://com.apple.contacts/documentation/Contacts/CNContact",
                "doc://com.apple.contacts/documentation/Contacts/CNMutableContact",
                "doc://com.apple.contacts/documentation/Contacts/data-objects"
              ],
              "title": "Contact data"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.contacts~1documentation~1Contacts~1CNContactNonGregorianBirthdayKey/title",
          "value": "CNContactNonGregorianBirthdayKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.contacts~1documentation~1Contacts~1CNContactNonGregorianBirthdayKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CNContactNonGregorianBirthdayKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.contacts~1documentation~1Contacts~1CNContactMiddleNameKey/title",
          "value": "CNContactMiddleNameKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.contacts~1documentation~1Contacts~1CNContactMiddleNameKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CNContactMiddleNameKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.contacts~1documentation~1Contacts~1CNContactInstantMessageAddressesKey/title",
          "value": "CNContactInstantMessageAddressesKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.contacts~1documentation~1Contacts~1CNContactInstantMessageAddressesKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CNContactInstantMessageAddressesKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.contacts~1documentation~1Contacts~1CNGroupNameKey/title",
          "value": "CNGroupNameKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.contacts~1documentation~1Contacts~1CNGroupNameKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CNGroupNameKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.contacts~1documentation~1Contacts~1CNContactPropertyAttribute/title",
          "value": "CNContactPropertyAttribute"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.contacts~1documentation~1Contacts~1CNContactPropertyAttribute/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CNContactPropertyAttribute"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.contacts~1documentation~1Contacts~1CNContactUrlAddressesKey/title",
          "value": "CNContactUrlAddressesKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.contacts~1documentation~1Contacts~1CNContactUrlAddressesKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CNContactUrlAddressesKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.contacts~1documentation~1Contacts~1CNSocialProfileUsernameKey/title",
          "value": "CNSocialProfileUsernameKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.contacts~1documentation~1Contacts~1CNSocialProfileUsernameKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CNSocialProfileUsernameKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.contacts~1documentation~1Contacts~1CNContactPostalAddressesKey/title",
          "value": "CNContactPostalAddressesKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.contacts~1documentation~1Contacts~1CNContactPostalAddressesKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CNContactPostalAddressesKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.contacts~1documentation~1Contacts~1CNSocialProfileServiceKey/title",
          "value": "CNSocialProfileServiceKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.contacts~1documentation~1Contacts~1CNSocialProfileServiceKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CNSocialProfileServiceKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.contacts~1documentation~1Contacts~1CNContactPhoneticFamilyNameKey/title",
          "value": "CNContactPhoneticFamilyNameKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.contacts~1documentation~1Contacts~1CNContactPhoneticFamilyNameKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CNContactPhoneticFamilyNameKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.contacts~1documentation~1Contacts~1CNContactNoteKey/title",
          "value": "CNContactNoteKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.contacts~1documentation~1Contacts~1CNContactNoteKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CNContactNoteKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.contacts~1documentation~1Contacts~1CNContactTypeKey/title",
          "value": "CNContactTypeKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.contacts~1documentation~1Contacts~1CNContactTypeKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CNContactTypeKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.contacts~1documentation~1Contacts~1CNInstantMessageAddressUsernameKey/title",
          "value": "CNInstantMessageAddressUsernameKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.contacts~1documentation~1Contacts~1CNInstantMessageAddressUsernameKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CNInstantMessageAddressUsernameKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.contacts~1documentation~1Contacts~1CNContactSocialProfilesKey/title",
          "value": "CNContactSocialProfilesKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.contacts~1documentation~1Contacts~1CNContactSocialProfilesKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CNContactSocialProfilesKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.contacts~1documentation~1Contacts~1CNContactImageDataAvailableKey/title",
          "value": "CNContactImageDataAvailableKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.contacts~1documentation~1Contacts~1CNContactImageDataAvailableKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CNContactImageDataAvailableKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.contacts~1documentation~1Contacts~1CNContactBirthdayKey/title",
          "value": "CNContactBirthdayKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.contacts~1documentation~1Contacts~1CNContactBirthdayKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CNContactBirthdayKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.contacts~1documentation~1Contacts~1CNContactPhoneticGivenNameKey/title",
          "value": "CNContactPhoneticGivenNameKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.contacts~1documentation~1Contacts~1CNContactPhoneticGivenNameKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CNContactPhoneticGivenNameKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.contacts~1documentation~1Contacts~1CNContactThumbnailImageDataKey/title",
          "value": "CNContactThumbnailImageDataKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.contacts~1documentation~1Contacts~1CNContactThumbnailImageDataKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CNContactThumbnailImageDataKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.contacts~1documentation~1Contacts~1CNContactRelationsKey/title",
          "value": "CNContactRelationsKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.contacts~1documentation~1Contacts~1CNContactRelationsKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CNContactRelationsKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.contacts~1documentation~1Contacts~1CNContainerNameKey/title",
          "value": "CNContainerNameKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.contacts~1documentation~1Contacts~1CNContainerNameKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CNContainerNameKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.contacts~1documentation~1Contacts~1CNInstantMessageAddressServiceKey/title",
          "value": "CNInstantMessageAddressServiceKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.contacts~1documentation~1Contacts~1CNInstantMessageAddressServiceKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CNInstantMessageAddressServiceKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.contacts~1documentation~1Contacts~1CNContactNicknameKey/title",
          "value": "CNContactNicknameKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.contacts~1documentation~1Contacts~1CNContactNicknameKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CNContactNicknameKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.contacts~1documentation~1Contacts~1CNContactPhoneticMiddleNameKey/title",
          "value": "CNContactPhoneticMiddleNameKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.contacts~1documentation~1Contacts~1CNContactPhoneticMiddleNameKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CNContactPhoneticMiddleNameKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.contacts~1documentation~1Contacts~1CNContactGivenNameKey/title",
          "value": "CNContactGivenNameKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.contacts~1documentation~1Contacts~1CNContactGivenNameKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CNContactGivenNameKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.contacts~1documentation~1Contacts~1CNKeyDescriptor/title",
          "value": "CNKeyDescriptor"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.contacts~1documentation~1Contacts~1CNKeyDescriptor/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CNKeyDescriptor"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.contacts~1documentation~1Contacts~1CNKeyDescriptor/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CNKeyDescriptor"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.contacts~1documentation~1Contacts~1CNMutableContact/title",
          "value": "CNMutableContact"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.contacts~1documentation~1Contacts~1CNMutableContact/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CNMutableContact"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.contacts~1documentation~1Contacts~1CNMutableContact/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CNMutableContact"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.contacts~1documentation~1Contacts~1CNContact/title",
          "value": "CNContact"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.contacts~1documentation~1Contacts~1CNContact/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CNContact"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.contacts~1documentation~1Contacts~1CNContact/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CNContact"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.contacts~1documentation~1Contacts~1CNContactDepartmentNameKey/title",
          "value": "CNContactDepartmentNameKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.contacts~1documentation~1Contacts~1CNContactDepartmentNameKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CNContactDepartmentNameKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.contacts~1documentation~1Contacts~1CNContactNameSuffixKey/title",
          "value": "CNContactNameSuffixKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.contacts~1documentation~1Contacts~1CNContactNameSuffixKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CNContactNameSuffixKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.contacts~1documentation~1Contacts~1CNContactEmailAddressesKey/title",
          "value": "CNContactEmailAddressesKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.contacts~1documentation~1Contacts~1CNContactEmailAddressesKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CNContactEmailAddressesKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.contacts~1documentation~1Contacts~1CNContactPhoneticOrganizationNameKey/title",
          "value": "CNContactPhoneticOrganizationNameKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.contacts~1documentation~1Contacts~1CNContactPhoneticOrganizationNameKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CNContactPhoneticOrganizationNameKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.contacts~1documentation~1Contacts~1CNContactIdentifierKey/title",
          "value": "CNContactIdentifierKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.contacts~1documentation~1Contacts~1CNContactIdentifierKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CNContactIdentifierKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.contacts~1documentation~1Contacts~1CNContainerTypeKey/title",
          "value": "CNContainerTypeKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.contacts~1documentation~1Contacts~1CNContainerTypeKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CNContainerTypeKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.contacts~1documentation~1Contacts~1CNContactDatesKey/title",
          "value": "CNContactDatesKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.contacts~1documentation~1Contacts~1CNContactDatesKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CNContactDatesKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.contacts~1documentation~1Contacts~1CNContactPhoneNumbersKey/title",
          "value": "CNContactPhoneNumbersKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.contacts~1documentation~1Contacts~1CNContactPhoneNumbersKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CNContactPhoneNumbersKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.contacts~1documentation~1Contacts~1CNContactOrganizationNameKey/title",
          "value": "CNContactOrganizationNameKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.contacts~1documentation~1Contacts~1CNContactOrganizationNameKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CNContactOrganizationNameKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.contacts~1documentation~1Contacts~1CNSocialProfileURLStringKey/title",
          "value": "CNSocialProfileURLStringKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.contacts~1documentation~1Contacts~1CNSocialProfileURLStringKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CNSocialProfileURLStringKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.contacts~1documentation~1Contacts~1CNGroupIdentifierKey/title",
          "value": "CNGroupIdentifierKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.contacts~1documentation~1Contacts~1CNGroupIdentifierKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CNGroupIdentifierKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.contacts~1documentation~1Contacts~1CNContactJobTitleKey/title",
          "value": "CNContactJobTitleKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.contacts~1documentation~1Contacts~1CNContactJobTitleKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CNContactJobTitleKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.contacts~1documentation~1Contacts~1CNContactFamilyNameKey/title",
          "value": "CNContactFamilyNameKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.contacts~1documentation~1Contacts~1CNContactFamilyNameKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CNContactFamilyNameKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.contacts~1documentation~1Contacts~1CNContactNamePrefixKey/title",
          "value": "CNContactNamePrefixKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.contacts~1documentation~1Contacts~1CNContactNamePrefixKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CNContactNamePrefixKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.contacts~1documentation~1Contacts~1CNSocialProfileUserIdentifierKey/title",
          "value": "CNSocialProfileUserIdentifierKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.contacts~1documentation~1Contacts~1CNSocialProfileUserIdentifierKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CNSocialProfileUserIdentifierKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.contacts~1documentation~1Contacts~1CNContactPreviousFamilyNameKey/title",
          "value": "CNContactPreviousFamilyNameKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.contacts~1documentation~1Contacts~1CNContactPreviousFamilyNameKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CNContactPreviousFamilyNameKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.contacts~1documentation~1Contacts~1CNContactImageDataKey/title",
          "value": "CNContactImageDataKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.contacts~1documentation~1Contacts~1CNContactImageDataKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CNContactImageDataKey"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/contacts/contact-keys"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/contacts/contact-keys"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
