{
  "abstract": [
    {
      "text": "Access contact-related data, such as the user’s postal address and phone number.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.contacts/documentation/Contacts"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.contacts/documentation/Contacts/data-objects"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "Contacts"
      }
    ],
    "role": "collectionGroup",
    "roleHeading": "API Collection",
    "title": "Data Objects"
  },
  "references": {
    "doc://com.apple.contacts/documentation/Contacts": {
      "abstract": [
        {
          "text": "Access the user’s contacts, and format and localize contact information.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.contacts/documentation/Contacts",
      "kind": "symbol",
      "role": "collection",
      "title": "Contacts",
      "type": "topic",
      "url": "/documentation/contacts"
    },
    "doc://com.apple.contacts/documentation/Contacts/CNContact": {
      "abstract": [
        {
          "text": "An immutable object that stores information about a single contact, such as the contact’s first name, phone numbers, and addresses.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CNContact"
        }
      ],
      "identifier": "doc://com.apple.contacts/documentation/Contacts/CNContact",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CNContact"
        }
      ],
      "role": "symbol",
      "title": "CNContact",
      "type": "topic",
      "url": "/documentation/contacts/cncontact"
    },
    "doc://com.apple.contacts/documentation/Contacts/CNContactProperty": {
      "abstract": [
        {
          "text": "An object that represents a property of a contact.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CNContactProperty"
        }
      ],
      "identifier": "doc://com.apple.contacts/documentation/Contacts/CNContactProperty",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CNContactProperty"
        }
      ],
      "role": "symbol",
      "title": "CNContactProperty",
      "type": "topic",
      "url": "/documentation/contacts/cncontactproperty"
    },
    "doc://com.apple.contacts/documentation/Contacts/CNContactRelation": {
      "abstract": [
        {
          "text": "An immutable object that represents the relationship between one contact to another.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CNContactRelation"
        }
      ],
      "identifier": "doc://com.apple.contacts/documentation/Contacts/CNContactRelation",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CNContactRelation"
        }
      ],
      "role": "symbol",
      "title": "CNContactRelation",
      "type": "topic",
      "url": "/documentation/contacts/cncontactrelation"
    },
    "doc://com.apple.contacts/documentation/Contacts/CNContainer": {
      "abstract": [
        {
          "text": "An immutable object that represents a collection of contacts.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CNContainer"
        }
      ],
      "identifier": "doc://com.apple.contacts/documentation/Contacts/CNContainer",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CNContainer"
        }
      ],
      "role": "symbol",
      "title": "CNContainer",
      "type": "topic",
      "url": "/documentation/contacts/cncontainer"
    },
    "doc://com.apple.contacts/documentation/Contacts/CNGroup": {
      "abstract": [
        {
          "text": "An immutable object that represents a group of contacts.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CNGroup"
        }
      ],
      "identifier": "doc://com.apple.contacts/documentation/Contacts/CNGroup",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CNGroup"
        }
      ],
      "role": "symbol",
      "title": "CNGroup",
      "type": "topic",
      "url": "/documentation/contacts/cngroup"
    },
    "doc://com.apple.contacts/documentation/Contacts/CNInstantMessageAddress": {
      "abstract": [
        {
          "text": "An immutable object representing an instant message address for the contact.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CNInstantMessageAddress"
        }
      ],
      "identifier": "doc://com.apple.contacts/documentation/Contacts/CNInstantMessageAddress",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CNInstantMessageAddress"
        }
      ],
      "role": "symbol",
      "title": "CNInstantMessageAddress",
      "type": "topic",
      "url": "/documentation/contacts/cninstantmessageaddress"
    },
    "doc://com.apple.contacts/documentation/Contacts/CNLabeledValue": {
      "abstract": [
        {
          "text": "An immutable object that combines a contact property value with a label that describes that property.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CNLabeledValue"
        }
      ],
      "identifier": "doc://com.apple.contacts/documentation/Contacts/CNLabeledValue",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CNLabeledValue"
        }
      ],
      "role": "symbol",
      "title": "CNLabeledValue",
      "type": "topic",
      "url": "/documentation/contacts/cnlabeledvalue"
    },
    "doc://com.apple.contacts/documentation/Contacts/CNMutableContact": {
      "abstract": [
        {
          "text": "A mutable object that stores information about a single contact, such as the contact’s first name, phone numbers, and addresses.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CNMutableContact"
        }
      ],
      "identifier": "doc://com.apple.contacts/documentation/Contacts/CNMutableContact",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CNMutableContact"
        }
      ],
      "role": "symbol",
      "title": "CNMutableContact",
      "type": "topic",
      "url": "/documentation/contacts/cnmutablecontact"
    },
    "doc://com.apple.contacts/documentation/Contacts/CNMutableGroup": {
      "abstract": [
        {
          "text": "A mutable object that represents a group of contacts.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CNMutableGroup"
        }
      ],
      "identifier": "doc://com.apple.contacts/documentation/Contacts/CNMutableGroup",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CNMutableGroup"
        }
      ],
      "role": "symbol",
      "title": "CNMutableGroup",
      "type": "topic",
      "url": "/documentation/contacts/cnmutablegroup"
    },
    "doc://com.apple.contacts/documentation/Contacts/CNMutablePostalAddress": {
      "abstract": [
        {
          "text": "A mutable representation of the postal address for a contact.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CNMutablePostalAddress"
        }
      ],
      "identifier": "doc://com.apple.contacts/documentation/Contacts/CNMutablePostalAddress",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CNMutablePostalAddress"
        }
      ],
      "role": "symbol",
      "title": "CNMutablePostalAddress",
      "type": "topic",
      "url": "/documentation/contacts/cnmutablepostaladdress"
    },
    "doc://com.apple.contacts/documentation/Contacts/CNPhoneNumber": {
      "abstract": [
        {
          "text": "An immutable object representing a phone number for a contact.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CNPhoneNumber"
        }
      ],
      "identifier": "doc://com.apple.contacts/documentation/Contacts/CNPhoneNumber",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CNPhoneNumber"
        }
      ],
      "role": "symbol",
      "title": "CNPhoneNumber",
      "type": "topic",
      "url": "/documentation/contacts/cnphonenumber"
    },
    "doc://com.apple.contacts/documentation/Contacts/CNPostalAddress": {
      "abstract": [
        {
          "text": "An immutable representation of the postal address for a contact.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CNPostalAddress"
        }
      ],
      "identifier": "doc://com.apple.contacts/documentation/Contacts/CNPostalAddress",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CNPostalAddress"
        }
      ],
      "role": "symbol",
      "title": "CNPostalAddress",
      "type": "topic",
      "url": "/documentation/contacts/cnpostaladdress"
    },
    "doc://com.apple.contacts/documentation/Contacts/CNSocialProfile": {
      "abstract": [
        {
          "text": "An immutable object that represents one of the user’s social profiles.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CNSocialProfile"
        }
      ],
      "identifier": "doc://com.apple.contacts/documentation/Contacts/CNSocialProfile",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CNSocialProfile"
        }
      ],
      "role": "symbol",
      "title": "CNSocialProfile",
      "type": "topic",
      "url": "/documentation/contacts/cnsocialprofile"
    },
    "doc://com.apple.contacts/documentation/Contacts/contact-keys": {
      "abstract": [
        {
          "text": "Specify contact-related properties during fetch operations.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.contacts/documentation/Contacts/contact-keys",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Contact Keys",
      "type": "topic",
      "url": "/documentation/contacts/contact-keys"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Contact-data",
      "generated": true,
      "identifiers": [
        "doc://com.apple.contacts/documentation/Contacts/CNContact",
        "doc://com.apple.contacts/documentation/Contacts/CNMutableContact",
        "doc://com.apple.contacts/documentation/Contacts/contact-keys"
      ],
      "title": "Contact data"
    }
  ],
  "topicSections": [
    {
      "anchor": "Addresses",
      "identifiers": [
        "doc://com.apple.contacts/documentation/Contacts/CNPostalAddress",
        "doc://com.apple.contacts/documentation/Contacts/CNMutablePostalAddress",
        "doc://com.apple.contacts/documentation/Contacts/CNInstantMessageAddress"
      ],
      "title": "Addresses"
    },
    {
      "anchor": "Phone-Numbers",
      "identifiers": [
        "doc://com.apple.contacts/documentation/Contacts/CNPhoneNumber"
      ],
      "title": "Phone Numbers"
    },
    {
      "anchor": "Groups-and-Containers",
      "identifiers": [
        "doc://com.apple.contacts/documentation/Contacts/CNGroup",
        "doc://com.apple.contacts/documentation/Contacts/CNMutableGroup",
        "doc://com.apple.contacts/documentation/Contacts/CNContainer"
      ],
      "title": "Groups and Containers"
    },
    {
      "anchor": "Social-Profiles",
      "identifiers": [
        "doc://com.apple.contacts/documentation/Contacts/CNSocialProfile"
      ],
      "title": "Social Profiles"
    },
    {
      "anchor": "Related-Data",
      "identifiers": [
        "doc://com.apple.contacts/documentation/Contacts/CNContactRelation"
      ],
      "title": "Related Data"
    },
    {
      "anchor": "Generic-Types",
      "identifiers": [
        "doc://com.apple.contacts/documentation/Contacts/CNLabeledValue",
        "doc://com.apple.contacts/documentation/Contacts/CNContactProperty"
      ],
      "title": "Generic Types"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Addresses",
              "identifiers": [
                "doc://com.apple.contacts/documentation/Contacts/CNPostalAddress",
                "doc://com.apple.contacts/documentation/Contacts/CNMutablePostalAddress",
                "doc://com.apple.contacts/documentation/Contacts/CNInstantMessageAddress"
              ],
              "title": "Addresses"
            },
            {
              "anchor": "Phone-Numbers",
              "identifiers": [
                "doc://com.apple.contacts/documentation/Contacts/CNPhoneNumber"
              ],
              "title": "Phone Numbers"
            },
            {
              "anchor": "Groups-and-Containers",
              "identifiers": [
                "doc://com.apple.contacts/documentation/Contacts/CNGroup",
                "doc://com.apple.contacts/documentation/Contacts/CNMutableGroup",
                "doc://com.apple.contacts/documentation/Contacts/CNContainer"
              ],
              "title": "Groups and Containers"
            },
            {
              "anchor": "Social-Profiles",
              "identifiers": [
                "doc://com.apple.contacts/documentation/Contacts/CNSocialProfile"
              ],
              "title": "Social Profiles"
            },
            {
              "anchor": "Related-Data",
              "identifiers": [
                "doc://com.apple.contacts/documentation/Contacts/CNContactRelation"
              ],
              "title": "Related Data"
            },
            {
              "anchor": "Generic-Types",
              "identifiers": [
                "doc://com.apple.contacts/documentation/Contacts/CNLabeledValue",
                "doc://com.apple.contacts/documentation/Contacts/CNContactProperty"
              ],
              "title": "Generic Types"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Contact-data",
              "generated": true,
              "identifiers": [
                "doc://com.apple.contacts/documentation/Contacts/CNContact",
                "doc://com.apple.contacts/documentation/Contacts/CNMutableContact",
                "doc://com.apple.contacts/documentation/Contacts/contact-keys"
              ],
              "title": "Contact data"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.contacts~1documentation~1Contacts~1CNContact/title",
          "value": "CNContact"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.contacts~1documentation~1Contacts~1CNContact/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CNContact"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.contacts~1documentation~1Contacts~1CNContact/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CNContact"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.contacts~1documentation~1Contacts~1CNInstantMessageAddress/title",
          "value": "CNInstantMessageAddress"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.contacts~1documentation~1Contacts~1CNInstantMessageAddress/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CNInstantMessageAddress"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.contacts~1documentation~1Contacts~1CNInstantMessageAddress/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CNInstantMessageAddress"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.contacts~1documentation~1Contacts~1CNContactProperty/title",
          "value": "CNContactProperty"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.contacts~1documentation~1Contacts~1CNContactProperty/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CNContactProperty"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.contacts~1documentation~1Contacts~1CNContactProperty/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CNContactProperty"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.contacts~1documentation~1Contacts~1CNPhoneNumber/title",
          "value": "CNPhoneNumber"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.contacts~1documentation~1Contacts~1CNPhoneNumber/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CNPhoneNumber"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.contacts~1documentation~1Contacts~1CNPhoneNumber/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CNPhoneNumber"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.contacts~1documentation~1Contacts~1CNSocialProfile/title",
          "value": "CNSocialProfile"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.contacts~1documentation~1Contacts~1CNSocialProfile/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CNSocialProfile"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.contacts~1documentation~1Contacts~1CNSocialProfile/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CNSocialProfile"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.contacts~1documentation~1Contacts~1CNGroup/title",
          "value": "CNGroup"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.contacts~1documentation~1Contacts~1CNGroup/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CNGroup"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.contacts~1documentation~1Contacts~1CNGroup/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CNGroup"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.contacts~1documentation~1Contacts~1CNMutablePostalAddress/title",
          "value": "CNMutablePostalAddress"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.contacts~1documentation~1Contacts~1CNMutablePostalAddress/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CNMutablePostalAddress"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.contacts~1documentation~1Contacts~1CNMutablePostalAddress/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CNMutablePostalAddress"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.contacts~1documentation~1Contacts~1CNContainer/title",
          "value": "CNContainer"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.contacts~1documentation~1Contacts~1CNContainer/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CNContainer"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.contacts~1documentation~1Contacts~1CNContainer/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CNContainer"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.contacts~1documentation~1Contacts~1CNLabeledValue/title",
          "value": "CNLabeledValue"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.contacts~1documentation~1Contacts~1CNLabeledValue/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CNLabeledValue"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.contacts~1documentation~1Contacts~1CNLabeledValue/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CNLabeledValue"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.contacts~1documentation~1Contacts~1CNContactRelation/title",
          "value": "CNContactRelation"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.contacts~1documentation~1Contacts~1CNContactRelation/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CNContactRelation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.contacts~1documentation~1Contacts~1CNContactRelation/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CNContactRelation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.contacts~1documentation~1Contacts~1CNPostalAddress/title",
          "value": "CNPostalAddress"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.contacts~1documentation~1Contacts~1CNPostalAddress/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CNPostalAddress"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.contacts~1documentation~1Contacts~1CNPostalAddress/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CNPostalAddress"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.contacts~1documentation~1Contacts~1CNMutableGroup/title",
          "value": "CNMutableGroup"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.contacts~1documentation~1Contacts~1CNMutableGroup/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CNMutableGroup"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.contacts~1documentation~1Contacts~1CNMutableGroup/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CNMutableGroup"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.contacts~1documentation~1Contacts~1CNMutableContact/title",
          "value": "CNMutableContact"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.contacts~1documentation~1Contacts~1CNMutableContact/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CNMutableContact"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.contacts~1documentation~1Contacts~1CNMutableContact/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CNMutableContact"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/contacts/data-objects"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/contacts/data-objects"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
