{
  "abstract": [
    {
      "text": "Diagnose errors generated by the Contacts framework.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.contacts/documentation/Contacts"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.contacts/documentation/Contacts/error-information"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "Contacts"
      }
    ],
    "role": "collectionGroup",
    "roleHeading": "API Collection",
    "title": "Error Information"
  },
  "references": {
    "doc://com.apple.contacts/documentation/Contacts": {
      "abstract": [
        {
          "text": "Access the user’s contacts, and format and localize contact information.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.contacts/documentation/Contacts",
      "kind": "symbol",
      "role": "collection",
      "title": "Contacts",
      "type": "topic",
      "url": "/documentation/contacts"
    },
    "doc://com.apple.contacts/documentation/Contacts/CNContactPropertyNotFetchedExceptionName": {
      "abstract": [
        {
          "text": "Exception thrown when an accessed property was not fetched.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CNContactPropertyNotFetchedExceptionName"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.contacts/documentation/Contacts/CNContactPropertyNotFetchedExceptionName",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CNContactPropertyNotFetchedExceptionName"
        }
      ],
      "role": "symbol",
      "title": "CNContactPropertyNotFetchedExceptionName",
      "type": "topic",
      "url": "/documentation/contacts/cncontactpropertynotfetchedexceptionname"
    },
    "doc://com.apple.contacts/documentation/Contacts/CNError": {
      "abstract": [
        {
          "text": "Error information that may be returned when using the methods of the Contacts framework.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CNError"
        }
      ],
      "identifier": "doc://com.apple.contacts/documentation/Contacts/CNError",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CNError"
        }
      ],
      "role": "symbol",
      "title": "CNError",
      "type": "topic",
      "url": "/documentation/contacts/cnerror"
    },
    "doc://com.apple.contacts/documentation/Contacts/CNError/Code": {
      "abstract": [
        {
          "text": "Error codes that the system may return when you use Contacts framework methods.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.contacts/documentation/Contacts/CNError/Code",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "Code"
        }
      ],
      "role": "symbol",
      "title": "CNError.Code",
      "type": "topic",
      "url": "/documentation/contacts/cnerror/code"
    },
    "doc://com.apple.contacts/documentation/Contacts/CNErrorDomain": {
      "abstract": [
        {
          "text": "The error domain for the Contacts framework.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CNErrorDomain"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.contacts/documentation/Contacts/CNErrorDomain",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CNErrorDomain"
        }
      ],
      "role": "symbol",
      "title": "CNErrorDomain",
      "type": "topic",
      "url": "/documentation/contacts/cnerrordomain"
    },
    "doc://com.apple.contacts/documentation/Contacts/CNErrorUserInfoAffectedRecordIdentifiersKey": {
      "abstract": [
        {
          "text": "String objects for which the error code applies.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CNErrorUserInfoAffectedRecordIdentifiersKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.contacts/documentation/Contacts/CNErrorUserInfoAffectedRecordIdentifiersKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CNErrorUserInfoAffectedRecordIdentifiersKey"
        }
      ],
      "role": "symbol",
      "title": "CNErrorUserInfoAffectedRecordIdentifiersKey",
      "type": "topic",
      "url": "/documentation/contacts/cnerroruserinfoaffectedrecordidentifierskey"
    },
    "doc://com.apple.contacts/documentation/Contacts/CNErrorUserInfoAffectedRecordsKey": {
      "abstract": [
        {
          "text": "The contact, group, and container objects for which the error code applies.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CNErrorUserInfoAffectedRecordsKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.contacts/documentation/Contacts/CNErrorUserInfoAffectedRecordsKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CNErrorUserInfoAffectedRecordsKey"
        }
      ],
      "role": "symbol",
      "title": "CNErrorUserInfoAffectedRecordsKey",
      "type": "topic",
      "url": "/documentation/contacts/cnerroruserinfoaffectedrecordskey"
    },
    "doc://com.apple.contacts/documentation/Contacts/CNErrorUserInfoKeyPathsKey": {
      "abstract": [
        {
          "text": "An array of key paths associated with a given error.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CNErrorUserInfoKeyPathsKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.contacts/documentation/Contacts/CNErrorUserInfoKeyPathsKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CNErrorUserInfoKeyPathsKey"
        }
      ],
      "role": "symbol",
      "title": "CNErrorUserInfoKeyPathsKey",
      "type": "topic",
      "url": "/documentation/contacts/cnerroruserinfokeypathskey"
    },
    "doc://com.apple.contacts/documentation/Contacts/CNErrorUserInfoValidationErrorsKey": {
      "abstract": [
        {
          "text": "An array of validation-related error objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CNErrorUserInfoValidationErrorsKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.contacts/documentation/Contacts/CNErrorUserInfoValidationErrorsKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CNErrorUserInfoValidationErrorsKey"
        }
      ],
      "role": "symbol",
      "title": "CNErrorUserInfoValidationErrorsKey",
      "type": "topic",
      "url": "/documentation/contacts/cnerroruserinfovalidationerrorskey"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "topicSections": [
    {
      "anchor": "Error-domain",
      "identifiers": [
        "doc://com.apple.contacts/documentation/Contacts/CNErrorDomain"
      ],
      "title": "Error domain"
    },
    {
      "anchor": "Error-codes",
      "identifiers": [
        "doc://com.apple.contacts/documentation/Contacts/CNError",
        "doc://com.apple.contacts/documentation/Contacts/CNError/Code"
      ],
      "title": "Error codes"
    },
    {
      "anchor": "Error-data-keys",
      "identifiers": [
        "doc://com.apple.contacts/documentation/Contacts/CNErrorUserInfoAffectedRecordsKey",
        "doc://com.apple.contacts/documentation/Contacts/CNErrorUserInfoAffectedRecordIdentifiersKey",
        "doc://com.apple.contacts/documentation/Contacts/CNErrorUserInfoValidationErrorsKey",
        "doc://com.apple.contacts/documentation/Contacts/CNErrorUserInfoKeyPathsKey"
      ],
      "title": "Error data keys"
    },
    {
      "anchor": "Exceptions",
      "identifiers": [
        "doc://com.apple.contacts/documentation/Contacts/CNContactPropertyNotFetchedExceptionName"
      ],
      "title": "Exceptions"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Error-domain",
              "identifiers": [
                "doc://com.apple.contacts/documentation/Contacts/CNErrorDomain"
              ],
              "title": "Error domain"
            },
            {
              "anchor": "Error-codes",
              "identifiers": [
                "doc://com.apple.contacts/documentation/Contacts/CNError/Code"
              ],
              "title": "Error codes"
            },
            {
              "anchor": "Error-data-keys",
              "identifiers": [
                "doc://com.apple.contacts/documentation/Contacts/CNErrorUserInfoAffectedRecordsKey",
                "doc://com.apple.contacts/documentation/Contacts/CNErrorUserInfoAffectedRecordIdentifiersKey",
                "doc://com.apple.contacts/documentation/Contacts/CNErrorUserInfoValidationErrorsKey",
                "doc://com.apple.contacts/documentation/Contacts/CNErrorUserInfoKeyPathsKey"
              ],
              "title": "Error data keys"
            },
            {
              "anchor": "Exceptions",
              "identifiers": [
                "doc://com.apple.contacts/documentation/Contacts/CNContactPropertyNotFetchedExceptionName"
              ],
              "title": "Exceptions"
            }
          ]
        },
        {
          "op": "add",
          "path": "/seeAlsoSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.contacts~1documentation~1Contacts~1CNErrorUserInfoAffectedRecordIdentifiersKey/title",
          "value": "CNErrorUserInfoAffectedRecordIdentifiersKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.contacts~1documentation~1Contacts~1CNErrorUserInfoAffectedRecordIdentifiersKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CNErrorUserInfoAffectedRecordIdentifiersKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.contacts~1documentation~1Contacts~1CNError~1Code/title",
          "value": "CNErrorCode"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.contacts~1documentation~1Contacts~1CNError~1Code/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CNErrorCode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.contacts~1documentation~1Contacts~1CNError~1Code/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CNErrorCode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.contacts~1documentation~1Contacts~1CNErrorDomain/title",
          "value": "CNErrorDomain"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.contacts~1documentation~1Contacts~1CNErrorDomain/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CNErrorDomain"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.contacts~1documentation~1Contacts~1CNContactPropertyNotFetchedExceptionName/title",
          "value": "CNContactPropertyNotFetchedExceptionName"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.contacts~1documentation~1Contacts~1CNContactPropertyNotFetchedExceptionName/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CNContactPropertyNotFetchedExceptionName"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.contacts~1documentation~1Contacts~1CNErrorUserInfoAffectedRecordsKey/title",
          "value": "CNErrorUserInfoAffectedRecordsKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.contacts~1documentation~1Contacts~1CNErrorUserInfoAffectedRecordsKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CNErrorUserInfoAffectedRecordsKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.contacts~1documentation~1Contacts~1CNErrorUserInfoKeyPathsKey/title",
          "value": "CNErrorUserInfoKeyPathsKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.contacts~1documentation~1Contacts~1CNErrorUserInfoKeyPathsKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CNErrorUserInfoKeyPathsKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.contacts~1documentation~1Contacts~1CNErrorUserInfoValidationErrorsKey/title",
          "value": "CNErrorUserInfoValidationErrorsKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.contacts~1documentation~1Contacts~1CNErrorUserInfoValidationErrorsKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CNErrorUserInfoValidationErrorsKey"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/contacts/error-information"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/contacts/error-information"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
