{
  "abstract": [
    {
      "text": "Creates a promise object using the specified executor callback.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.javascriptcore/documentation/JavaScriptCore",
        "doc://com.apple.javascriptcore/documentation/JavaScriptCore/JSValue"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.javascriptcore/documentation/JavaScriptCore/JSValue/init(newPromiseIn:fromExecutor:)"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(cs)JSValue(cm)valueWithNewPromiseInContext:fromExecutor:",
    "fragments": [
      {
        "kind": "identifier",
        "text": "init"
      },
      {
        "kind": "text",
        "text": "!("
      },
      {
        "kind": "externalParam",
        "text": "newPromiseIn"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:objc(cs)JSContext",
        "text": "JSContext"
      },
      {
        "kind": "text",
        "text": "!, "
      },
      {
        "kind": "externalParam",
        "text": "fromExecutor"
      },
      {
        "kind": "text",
        "text": ": (("
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:objc(cs)JSValue",
        "text": "JSValue"
      },
      {
        "kind": "text",
        "text": "?, "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:objc(cs)JSValue",
        "text": "JSValue"
      },
      {
        "kind": "text",
        "text": "?) -> "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "s:s4Voida",
        "text": "Void"
      },
      {
        "kind": "text",
        "text": ")!)"
      }
    ],
    "modules": [
      {
        "name": "JavaScriptCore"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "valueWithNewPromiseInContext:fromExecutor:"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.1",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.15",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "9.0",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Initializer",
    "symbolKind": "init",
    "title": "init(newPromiseIn:fromExecutor:)"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "init"
            },
            {
              "kind": "text",
              "text": "!("
            },
            {
              "kind": "externalParam",
              "text": "newPromiseIn"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "context"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.javascriptcore/documentation/JavaScriptCore/JSContext",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)JSContext",
              "text": "JSContext"
            },
            {
              "kind": "text",
              "text": "!, "
            },
            {
              "kind": "externalParam",
              "text": "fromExecutor"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "callback"
            },
            {
              "kind": "text",
              "text": ": (("
            },
            {
              "identifier": "doc://com.apple.javascriptcore/documentation/JavaScriptCore/JSValue",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)JSValue",
              "text": "JSValue"
            },
            {
              "kind": "text",
              "text": "?, "
            },
            {
              "identifier": "doc://com.apple.javascriptcore/documentation/JavaScriptCore/JSValue",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)JSValue",
              "text": "JSValue"
            },
            {
              "kind": "text",
              "text": "?) -> "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:s4Voida",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:s4Voida",
              "text": "Void"
            },
            {
              "kind": "text",
              "text": ")!)"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "kind": "parameters",
      "parameters": [
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "The ",
                  "type": "text"
                },
                {
                  "identifier": "doc://com.apple.javascriptcore/documentation/JavaScriptCore/JSContext",
                  "isActive": true,
                  "type": "reference"
                },
                {
                  "text": " the resulting ",
                  "type": "text"
                },
                {
                  "identifier": "doc://com.apple.javascriptcore/documentation/JavaScriptCore/JSValue",
                  "isActive": true,
                  "type": "reference"
                },
                {
                  "text": " belongs to.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "context"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "A callback block to invoke during initialization of the promise object. The ",
                  "type": "text"
                },
                {
                  "code": "resolve",
                  "type": "codeVoice"
                },
                {
                  "text": " and ",
                  "type": "text"
                },
                {
                  "code": "reject",
                  "type": "codeVoice"
                },
                {
                  "text": " parameters are functions that you can call to notify any pending reactions about the state of the new promise object.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "callback"
        }
      ]
    },
    {
      "content": [
        {
          "anchor": "return-value",
          "level": 2,
          "text": "Return Value",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "A ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.javascriptcore/documentation/JavaScriptCore/JSValue",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " that represents a new promise JavaScript object.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    },
    {
      "content": [
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "This method is equivalent to calling the ",
              "type": "text"
            },
            {
              "code": "Promise()",
              "type": "codeVoice"
            },
            {
              "text": " constructor in JavaScript.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "The ",
              "type": "text"
            },
            {
              "code": "resolve",
              "type": "codeVoice"
            },
            {
              "text": " and ",
              "type": "text"
            },
            {
              "code": "reject",
              "type": "codeVoice"
            },
            {
              "text": " callbacks each typically take a single value, which they forward to all relevant pending reactions. While inside the executor callback, ",
              "type": "text"
            },
            {
              "code": "context",
              "type": "codeVoice"
            },
            {
              "text": " acts as if it is in any other callback, except ",
              "type": "text"
            },
            {
              "code": "calleeFunction",
              "type": "codeVoice"
            },
            {
              "text": " is ",
              "type": "text"
            },
            {
              "code": "nil",
              "type": "codeVoice"
            },
            {
              "text": ". This also means you can access the new promise object using ",
              "type": "text"
            },
            {
              "code": "[context thisValue]",
              "type": "codeVoice"
            },
            {
              "text": ".",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.javascriptcore/documentation/JavaScriptCore": {
      "abstract": [
        {
          "text": "Evaluate JavaScript programs from within an app, and support JavaScript scripting of your app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.javascriptcore/documentation/JavaScriptCore",
      "kind": "symbol",
      "role": "collection",
      "title": "JavaScriptCore",
      "type": "topic",
      "url": "/documentation/javascriptcore"
    },
    "doc://com.apple.javascriptcore/documentation/JavaScriptCore/JSContext": {
      "abstract": [
        {
          "text": "A JavaScript execution environment.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "JSContext"
        }
      ],
      "identifier": "doc://com.apple.javascriptcore/documentation/JavaScriptCore/JSContext",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "JSContext"
        }
      ],
      "role": "symbol",
      "title": "JSContext",
      "type": "topic",
      "url": "/documentation/javascriptcore/jscontext"
    },
    "doc://com.apple.javascriptcore/documentation/JavaScriptCore/JSValue": {
      "abstract": [
        {
          "text": "A JavaScript value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "JSValue"
        }
      ],
      "identifier": "doc://com.apple.javascriptcore/documentation/JavaScriptCore/JSValue",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "JSValue"
        }
      ],
      "role": "symbol",
      "title": "JSValue",
      "type": "topic",
      "url": "/documentation/javascriptcore/jsvalue"
    },
    "doc://com.apple.javascriptcore/documentation/JavaScriptCore/JSValue/init(bool:in:)": {
      "abstract": [
        {
          "text": "Creates a JavaScript representation of the specified Boolean value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "!("
        },
        {
          "kind": "externalParam",
          "text": "bool"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "in"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)JSContext",
          "text": "JSContext"
        },
        {
          "kind": "text",
          "text": "!)"
        }
      ],
      "identifier": "doc://com.apple.javascriptcore/documentation/JavaScriptCore/JSValue/init(bool:in:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "valueWithBool:inContext:"
        }
      ],
      "role": "symbol",
      "title": "init(bool:in:)",
      "type": "topic",
      "url": "/documentation/javascriptcore/jsvalue/init(bool:in:)"
    },
    "doc://com.apple.javascriptcore/documentation/JavaScriptCore/JSValue/init(double:in:)": {
      "abstract": [
        {
          "text": "Creates a JavaScript representation of the specified floating-point value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "!("
        },
        {
          "kind": "externalParam",
          "text": "double"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sd",
          "text": "Double"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "in"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)JSContext",
          "text": "JSContext"
        },
        {
          "kind": "text",
          "text": "!)"
        }
      ],
      "identifier": "doc://com.apple.javascriptcore/documentation/JavaScriptCore/JSValue/init(double:in:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "valueWithDouble:inContext:"
        }
      ],
      "role": "symbol",
      "title": "init(double:in:)",
      "type": "topic",
      "url": "/documentation/javascriptcore/jsvalue/init(double:in:)"
    },
    "doc://com.apple.javascriptcore/documentation/JavaScriptCore/JSValue/init(int32:in:)": {
      "abstract": [
        {
          "text": "Creates a JavaScript representation of the specified signed integer value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "!("
        },
        {
          "kind": "externalParam",
          "text": "int32"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int32V",
          "text": "Int32"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "in"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)JSContext",
          "text": "JSContext"
        },
        {
          "kind": "text",
          "text": "!)"
        }
      ],
      "identifier": "doc://com.apple.javascriptcore/documentation/JavaScriptCore/JSValue/init(int32:in:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "valueWithInt32:inContext:"
        }
      ],
      "role": "symbol",
      "title": "init(int32:in:)",
      "type": "topic",
      "url": "/documentation/javascriptcore/jsvalue/init(int32:in:)"
    },
    "doc://com.apple.javascriptcore/documentation/JavaScriptCore/JSValue/init(newArrayIn:)": {
      "abstract": [
        {
          "text": "Creates a new, empty JavaScript array value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "!("
        },
        {
          "kind": "externalParam",
          "text": "newArrayIn"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)JSContext",
          "text": "JSContext"
        },
        {
          "kind": "text",
          "text": "!)"
        }
      ],
      "identifier": "doc://com.apple.javascriptcore/documentation/JavaScriptCore/JSValue/init(newArrayIn:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "valueWithNewArrayInContext:"
        }
      ],
      "role": "symbol",
      "title": "init(newArrayIn:)",
      "type": "topic",
      "url": "/documentation/javascriptcore/jsvalue/init(newarrayin:)"
    },
    "doc://com.apple.javascriptcore/documentation/JavaScriptCore/JSValue/init(newErrorFromMessage:in:)": {
      "abstract": [
        {
          "text": "Creates a JavaScript error value with the specified error message.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "!("
        },
        {
          "kind": "externalParam",
          "text": "newErrorFromMessage"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": "!, "
        },
        {
          "kind": "externalParam",
          "text": "in"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)JSContext",
          "text": "JSContext"
        },
        {
          "kind": "text",
          "text": "!)"
        }
      ],
      "identifier": "doc://com.apple.javascriptcore/documentation/JavaScriptCore/JSValue/init(newErrorFromMessage:in:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "valueWithNewErrorFromMessage:inContext:"
        }
      ],
      "role": "symbol",
      "title": "init(newErrorFromMessage:in:)",
      "type": "topic",
      "url": "/documentation/javascriptcore/jsvalue/init(newerrorfrommessage:in:)"
    },
    "doc://com.apple.javascriptcore/documentation/JavaScriptCore/JSValue/init(newObjectIn:)": {
      "abstract": [
        {
          "text": "Creates a new, empty JavaScript object value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "!("
        },
        {
          "kind": "externalParam",
          "text": "newObjectIn"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)JSContext",
          "text": "JSContext"
        },
        {
          "kind": "text",
          "text": "!)"
        }
      ],
      "identifier": "doc://com.apple.javascriptcore/documentation/JavaScriptCore/JSValue/init(newObjectIn:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "valueWithNewObjectInContext:"
        }
      ],
      "role": "symbol",
      "title": "init(newObjectIn:)",
      "type": "topic",
      "url": "/documentation/javascriptcore/jsvalue/init(newobjectin:)"
    },
    "doc://com.apple.javascriptcore/documentation/JavaScriptCore/JSValue/init(newPromiseIn:fromExecutor:)": {
      "abstract": [
        {
          "text": "Creates a promise object using the specified executor callback.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "!("
        },
        {
          "kind": "externalParam",
          "text": "newPromiseIn"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)JSContext",
          "text": "JSContext"
        },
        {
          "kind": "text",
          "text": "!, "
        },
        {
          "kind": "externalParam",
          "text": "fromExecutor"
        },
        {
          "kind": "text",
          "text": ": (("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)JSValue",
          "text": "JSValue"
        },
        {
          "kind": "text",
          "text": "?, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)JSValue",
          "text": "JSValue"
        },
        {
          "kind": "text",
          "text": "?) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s4Voida",
          "text": "Void"
        },
        {
          "kind": "text",
          "text": ")!)"
        }
      ],
      "identifier": "doc://com.apple.javascriptcore/documentation/JavaScriptCore/JSValue/init(newPromiseIn:fromExecutor:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "valueWithNewPromiseInContext:fromExecutor:"
        }
      ],
      "role": "symbol",
      "title": "init(newPromiseIn:fromExecutor:)",
      "type": "topic",
      "url": "/documentation/javascriptcore/jsvalue/init(newpromisein:fromexecutor:)"
    },
    "doc://com.apple.javascriptcore/documentation/JavaScriptCore/JSValue/init(newRegularExpressionFromPattern:flags:in:)": {
      "abstract": [
        {
          "text": "Creates a JavaScript regular expression value from the specified pattern.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "!("
        },
        {
          "kind": "externalParam",
          "text": "newRegularExpressionFromPattern"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": "!, "
        },
        {
          "kind": "externalParam",
          "text": "flags"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": "!, "
        },
        {
          "kind": "externalParam",
          "text": "in"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)JSContext",
          "text": "JSContext"
        },
        {
          "kind": "text",
          "text": "!)"
        }
      ],
      "identifier": "doc://com.apple.javascriptcore/documentation/JavaScriptCore/JSValue/init(newRegularExpressionFromPattern:flags:in:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "valueWithNewRegularExpressionFromPattern:flags:inContext:"
        }
      ],
      "role": "symbol",
      "title": "init(newRegularExpressionFromPattern:flags:in:)",
      "type": "topic",
      "url": "/documentation/javascriptcore/jsvalue/init(newregularexpressionfrompattern:flags:in:)"
    },
    "doc://com.apple.javascriptcore/documentation/JavaScriptCore/JSValue/init(nullIn:)": {
      "abstract": [
        {
          "text": "Creates a JavaScript ",
          "type": "text"
        },
        {
          "code": "null",
          "type": "codeVoice"
        },
        {
          "text": " value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "!("
        },
        {
          "kind": "externalParam",
          "text": "nullIn"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)JSContext",
          "text": "JSContext"
        },
        {
          "kind": "text",
          "text": "!)"
        }
      ],
      "identifier": "doc://com.apple.javascriptcore/documentation/JavaScriptCore/JSValue/init(nullIn:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "valueWithNullInContext:"
        }
      ],
      "role": "symbol",
      "title": "init(nullIn:)",
      "type": "topic",
      "url": "/documentation/javascriptcore/jsvalue/init(nullin:)"
    },
    "doc://com.apple.javascriptcore/documentation/JavaScriptCore/JSValue/init(object:in:)": {
      "abstract": [
        {
          "text": "Creates a JavaScript value by converting the specified native object.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "!("
        },
        {
          "kind": "externalParam",
          "text": "object"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "keyword",
          "text": "Any"
        },
        {
          "kind": "text",
          "text": "!, "
        },
        {
          "kind": "externalParam",
          "text": "in"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)JSContext",
          "text": "JSContext"
        },
        {
          "kind": "text",
          "text": "!)"
        }
      ],
      "identifier": "doc://com.apple.javascriptcore/documentation/JavaScriptCore/JSValue/init(object:in:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "valueWithObject:inContext:"
        }
      ],
      "role": "symbol",
      "title": "init(object:in:)",
      "type": "topic",
      "url": "/documentation/javascriptcore/jsvalue/init(object:in:)"
    },
    "doc://com.apple.javascriptcore/documentation/JavaScriptCore/JSValue/init(point:inContext:)": {
      "abstract": [
        {
          "text": "Creates a JavaScript representation of the specified point.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "!("
        },
        {
          "kind": "externalParam",
          "text": "point"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@CGPoint",
          "text": "CGPoint"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "inContext"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)JSContext",
          "text": "JSContext"
        },
        {
          "kind": "text",
          "text": "!)"
        }
      ],
      "identifier": "doc://com.apple.javascriptcore/documentation/JavaScriptCore/JSValue/init(point:inContext:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "valueWithPoint:inContext:"
        }
      ],
      "role": "symbol",
      "title": "init(point:inContext:)",
      "type": "topic",
      "url": "/documentation/javascriptcore/jsvalue/init(point:incontext:)"
    },
    "doc://com.apple.javascriptcore/documentation/JavaScriptCore/JSValue/init(range:inContext:)": {
      "abstract": [
        {
          "text": "Creates a JavaScript representation of the specified range.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "!("
        },
        {
          "kind": "externalParam",
          "text": "range"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "text": "NSRange"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "inContext"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)JSContext",
          "text": "JSContext"
        },
        {
          "kind": "text",
          "text": "!)"
        }
      ],
      "identifier": "doc://com.apple.javascriptcore/documentation/JavaScriptCore/JSValue/init(range:inContext:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "valueWithRange:inContext:"
        }
      ],
      "role": "symbol",
      "title": "init(range:inContext:)",
      "type": "topic",
      "url": "/documentation/javascriptcore/jsvalue/init(range:incontext:)"
    },
    "doc://com.apple.javascriptcore/documentation/JavaScriptCore/JSValue/init(rect:inContext:)": {
      "abstract": [
        {
          "text": "Creates a JavaScript representation of the specified rectangle.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "!("
        },
        {
          "kind": "externalParam",
          "text": "rect"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@CGRect",
          "text": "CGRect"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "inContext"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)JSContext",
          "text": "JSContext"
        },
        {
          "kind": "text",
          "text": "!)"
        }
      ],
      "identifier": "doc://com.apple.javascriptcore/documentation/JavaScriptCore/JSValue/init(rect:inContext:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "valueWithRect:inContext:"
        }
      ],
      "role": "symbol",
      "title": "init(rect:inContext:)",
      "type": "topic",
      "url": "/documentation/javascriptcore/jsvalue/init(rect:incontext:)"
    },
    "doc://com.apple.javascriptcore/documentation/JavaScriptCore/JSValue/init(size:inContext:)": {
      "abstract": [
        {
          "text": "Creates a JavaScript representation of the specified width and height.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "!("
        },
        {
          "kind": "externalParam",
          "text": "size"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@CGSize",
          "text": "CGSize"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "inContext"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)JSContext",
          "text": "JSContext"
        },
        {
          "kind": "text",
          "text": "!)"
        }
      ],
      "identifier": "doc://com.apple.javascriptcore/documentation/JavaScriptCore/JSValue/init(size:inContext:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "valueWithSize:inContext:"
        }
      ],
      "role": "symbol",
      "title": "init(size:inContext:)",
      "type": "topic",
      "url": "/documentation/javascriptcore/jsvalue/init(size:incontext:)"
    },
    "doc://com.apple.javascriptcore/documentation/JavaScriptCore/JSValue/init(uInt32:in:)": {
      "abstract": [
        {
          "text": "Creates a JavaScript representation of the specified unsigned integer value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "!("
        },
        {
          "kind": "externalParam",
          "text": "uInt32"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "in"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)JSContext",
          "text": "JSContext"
        },
        {
          "kind": "text",
          "text": "!)"
        }
      ],
      "identifier": "doc://com.apple.javascriptcore/documentation/JavaScriptCore/JSValue/init(uInt32:in:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "valueWithUInt32:inContext:"
        }
      ],
      "role": "symbol",
      "title": "init(uInt32:in:)",
      "type": "topic",
      "url": "/documentation/javascriptcore/jsvalue/init(uint32:in:)"
    },
    "doc://com.apple.javascriptcore/documentation/JavaScriptCore/JSValue/init(undefinedIn:)": {
      "abstract": [
        {
          "text": "Creates a JavaScript ",
          "type": "text"
        },
        {
          "code": "undefined",
          "type": "codeVoice"
        },
        {
          "text": " value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "!("
        },
        {
          "kind": "externalParam",
          "text": "undefinedIn"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)JSContext",
          "text": "JSContext"
        },
        {
          "kind": "text",
          "text": "!)"
        }
      ],
      "identifier": "doc://com.apple.javascriptcore/documentation/JavaScriptCore/JSValue/init(undefinedIn:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "valueWithUndefinedInContext:"
        }
      ],
      "role": "symbol",
      "title": "init(undefinedIn:)",
      "type": "topic",
      "url": "/documentation/javascriptcore/jsvalue/init(undefinedin:)"
    },
    "doc://com.externally.resolved.symbol/s:s4Voida": {
      "abstract": [
        {
          "text": "The return type of functions that don’t explicitly specify a return type, that is, an empty tuple `()`.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Void"
        },
        {
          "kind": "text",
          "text": " = ()"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s4Voida",
      "kind": "symbol",
      "role": "symbol",
      "title": "Void",
      "type": "topic",
      "url": "/documentation/Swift/Void"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Creating-JavaScript-Values",
      "generated": true,
      "identifiers": [
        "doc://com.apple.javascriptcore/documentation/JavaScriptCore/JSValue/init(object:in:)",
        "doc://com.apple.javascriptcore/documentation/JavaScriptCore/JSValue/init(bool:in:)",
        "doc://com.apple.javascriptcore/documentation/JavaScriptCore/JSValue/init(double:in:)",
        "doc://com.apple.javascriptcore/documentation/JavaScriptCore/JSValue/init(int32:in:)",
        "doc://com.apple.javascriptcore/documentation/JavaScriptCore/JSValue/init(uInt32:in:)",
        "doc://com.apple.javascriptcore/documentation/JavaScriptCore/JSValue/init(newObjectIn:)",
        "doc://com.apple.javascriptcore/documentation/JavaScriptCore/JSValue/init(newArrayIn:)",
        "doc://com.apple.javascriptcore/documentation/JavaScriptCore/JSValue/init(newRegularExpressionFromPattern:flags:in:)",
        "doc://com.apple.javascriptcore/documentation/JavaScriptCore/JSValue/init(newErrorFromMessage:in:)",
        "doc://com.apple.javascriptcore/documentation/JavaScriptCore/JSValue/init(undefinedIn:)",
        "doc://com.apple.javascriptcore/documentation/JavaScriptCore/JSValue/init(nullIn:)",
        "doc://com.apple.javascriptcore/documentation/JavaScriptCore/JSValue/init(point:inContext:)",
        "doc://com.apple.javascriptcore/documentation/JavaScriptCore/JSValue/init(range:inContext:)",
        "doc://com.apple.javascriptcore/documentation/JavaScriptCore/JSValue/init(rect:inContext:)",
        "doc://com.apple.javascriptcore/documentation/JavaScriptCore/JSValue/init(size:inContext:)"
      ],
      "title": "Creating JavaScript Values"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.1",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.15",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "9.0",
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Type Method"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "valueWithNewPromiseInContext:fromExecutor:"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "method"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "text",
              "text": "+ "
            },
            {
              "kind": "identifier",
              "text": "valueWithNewPromiseInContext:fromExecutor:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.javascriptcore/documentation/JavaScriptCore",
                "doc://com.apple.javascriptcore/documentation/JavaScriptCore/JSValue"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Creating-JavaScript-Values",
              "generated": true,
              "identifiers": [
                "doc://com.apple.javascriptcore/documentation/JavaScriptCore/JSValue/init(object:in:)",
                "doc://com.apple.javascriptcore/documentation/JavaScriptCore/JSValue/init(bool:in:)",
                "doc://com.apple.javascriptcore/documentation/JavaScriptCore/JSValue/init(double:in:)",
                "doc://com.apple.javascriptcore/documentation/JavaScriptCore/JSValue/init(int32:in:)",
                "doc://com.apple.javascriptcore/documentation/JavaScriptCore/JSValue/init(uInt32:in:)",
                "doc://com.apple.javascriptcore/documentation/JavaScriptCore/JSValue/init(newObjectIn:)",
                "doc://com.apple.javascriptcore/documentation/JavaScriptCore/JSValue/init(newArrayIn:)",
                "doc://com.apple.javascriptcore/documentation/JavaScriptCore/JSValue/init(newRegularExpressionFromPattern:flags:in:)",
                "doc://com.apple.javascriptcore/documentation/JavaScriptCore/JSValue/init(newErrorFromMessage:in:)",
                "doc://com.apple.javascriptcore/documentation/JavaScriptCore/JSValue/init(undefinedIn:)",
                "doc://com.apple.javascriptcore/documentation/JavaScriptCore/JSValue/init(nullIn:)",
                "doc://com.apple.javascriptcore/documentation/JavaScriptCore/JSValue/init(point:inContext:)",
                "doc://com.apple.javascriptcore/documentation/JavaScriptCore/JSValue/init(range:inContext:)",
                "doc://com.apple.javascriptcore/documentation/JavaScriptCore/JSValue/init(rect:inContext:)",
                "doc://com.apple.javascriptcore/documentation/JavaScriptCore/JSValue/init(size:inContext:)"
              ],
              "title": "Creating JavaScript Values"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS"
                ],
                "tokens": [
                  {
                    "kind": "text",
                    "text": "+ ("
                  },
                  {
                    "identifier": "doc://com.apple.javascriptcore/documentation/JavaScriptCore/JSValue",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(cs)JSValue",
                    "text": "JSValue"
                  },
                  {
                    "kind": "text",
                    "text": " *) "
                  },
                  {
                    "kind": "identifier",
                    "text": "valueWithNewPromiseInContext:"
                  },
                  {
                    "kind": "text",
                    "text": "("
                  },
                  {
                    "identifier": "doc://com.apple.javascriptcore/documentation/JavaScriptCore/JSContext",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(cs)JSContext",
                    "text": "JSContext"
                  },
                  {
                    "kind": "text",
                    "text": " *) "
                  },
                  {
                    "kind": "internalParam",
                    "text": "context"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "fromExecutor:"
                  },
                  {
                    "kind": "text",
                    "text": "("
                  },
                  {
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:v",
                    "text": "void"
                  },
                  {
                    "kind": "text",
                    "text": " (^)("
                  },
                  {
                    "identifier": "doc://com.apple.javascriptcore/documentation/JavaScriptCore/JSValue",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(cs)JSValue",
                    "text": "JSValue"
                  },
                  {
                    "kind": "text",
                    "text": " * "
                  },
                  {
                    "kind": "internalParam",
                    "text": "resolve"
                  },
                  {
                    "kind": "text",
                    "text": ", "
                  },
                  {
                    "identifier": "doc://com.apple.javascriptcore/documentation/JavaScriptCore/JSValue",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(cs)JSValue",
                    "text": "JSValue"
                  },
                  {
                    "kind": "text",
                    "text": " * "
                  },
                  {
                    "kind": "internalParam",
                    "text": "reject"
                  },
                  {
                    "kind": "text",
                    "text": ")) "
                  },
                  {
                    "kind": "internalParam",
                    "text": "callback"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/1",
          "value": {
            "kind": "parameters",
            "parameters": [
              {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "The ",
                        "type": "text"
                      },
                      {
                        "identifier": "doc://com.apple.javascriptcore/documentation/JavaScriptCore/JSContext",
                        "isActive": true,
                        "type": "reference"
                      },
                      {
                        "text": " the resulting ",
                        "type": "text"
                      },
                      {
                        "identifier": "doc://com.apple.javascriptcore/documentation/JavaScriptCore/JSValue",
                        "isActive": true,
                        "type": "reference"
                      },
                      {
                        "text": " belongs to.",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ],
                "name": "context"
              },
              {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "A callback block to invoke during initialization of the promise object. The ",
                        "type": "text"
                      },
                      {
                        "code": "resolve",
                        "type": "codeVoice"
                      },
                      {
                        "text": " and ",
                        "type": "text"
                      },
                      {
                        "code": "reject",
                        "type": "codeVoice"
                      },
                      {
                        "text": " parameters are functions that you can call to notify any pending reactions about the state of the new promise object.",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ],
                "name": "callback"
              }
            ]
          }
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/2",
          "value": {
            "content": [
              {
                "anchor": "return-value",
                "level": 2,
                "text": "Return Value",
                "type": "heading"
              },
              {
                "inlineContent": [
                  {
                    "text": "A ",
                    "type": "text"
                  },
                  {
                    "identifier": "doc://com.apple.javascriptcore/documentation/JavaScriptCore/JSValue",
                    "isActive": true,
                    "type": "reference"
                  },
                  {
                    "text": " that represents a new promise JavaScript object.",
                    "type": "text"
                  }
                ],
                "type": "paragraph"
              }
            ],
            "kind": "content"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.javascriptcore~1documentation~1JavaScriptCore~1JSValue~1init(newObjectIn:)/title",
          "value": "valueWithNewObjectInContext:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.javascriptcore~1documentation~1JavaScriptCore~1JSValue~1init(newObjectIn:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "+ "
            },
            {
              "kind": "identifier",
              "text": "valueWithNewObjectInContext:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.javascriptcore~1documentation~1JavaScriptCore~1JSValue/title",
          "value": "JSValue"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.javascriptcore~1documentation~1JavaScriptCore~1JSValue/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "JSValue"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.javascriptcore~1documentation~1JavaScriptCore~1JSValue/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "JSValue"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.javascriptcore~1documentation~1JavaScriptCore~1JSValue~1init(uInt32:in:)/title",
          "value": "valueWithUInt32:inContext:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.javascriptcore~1documentation~1JavaScriptCore~1JSValue~1init(uInt32:in:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "+ "
            },
            {
              "kind": "identifier",
              "text": "valueWithUInt32:inContext:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.javascriptcore~1documentation~1JavaScriptCore~1JSValue~1init(nullIn:)/title",
          "value": "valueWithNullInContext:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.javascriptcore~1documentation~1JavaScriptCore~1JSValue~1init(nullIn:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "+ "
            },
            {
              "kind": "identifier",
              "text": "valueWithNullInContext:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.javascriptcore~1documentation~1JavaScriptCore~1JSValue~1init(bool:in:)/title",
          "value": "valueWithBool:inContext:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.javascriptcore~1documentation~1JavaScriptCore~1JSValue~1init(bool:in:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "+ "
            },
            {
              "kind": "identifier",
              "text": "valueWithBool:inContext:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.javascriptcore~1documentation~1JavaScriptCore~1JSValue~1init(newErrorFromMessage:in:)/title",
          "value": "valueWithNewErrorFromMessage:inContext:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.javascriptcore~1documentation~1JavaScriptCore~1JSValue~1init(newErrorFromMessage:in:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "+ "
            },
            {
              "kind": "identifier",
              "text": "valueWithNewErrorFromMessage:inContext:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.javascriptcore~1documentation~1JavaScriptCore~1JSValue~1init(newArrayIn:)/title",
          "value": "valueWithNewArrayInContext:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.javascriptcore~1documentation~1JavaScriptCore~1JSValue~1init(newArrayIn:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "+ "
            },
            {
              "kind": "identifier",
              "text": "valueWithNewArrayInContext:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.javascriptcore~1documentation~1JavaScriptCore~1JSValue~1init(double:in:)/title",
          "value": "valueWithDouble:inContext:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.javascriptcore~1documentation~1JavaScriptCore~1JSValue~1init(double:in:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "+ "
            },
            {
              "kind": "identifier",
              "text": "valueWithDouble:inContext:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.javascriptcore~1documentation~1JavaScriptCore~1JSValue~1init(newRegularExpressionFromPattern:flags:in:)/title",
          "value": "valueWithNewRegularExpressionFromPattern:flags:inContext:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.javascriptcore~1documentation~1JavaScriptCore~1JSValue~1init(newRegularExpressionFromPattern:flags:in:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "+ "
            },
            {
              "kind": "identifier",
              "text": "valueWithNewRegularExpressionFromPattern:flags:inContext:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.javascriptcore~1documentation~1JavaScriptCore~1JSValue~1init(undefinedIn:)/title",
          "value": "valueWithUndefinedInContext:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.javascriptcore~1documentation~1JavaScriptCore~1JSValue~1init(undefinedIn:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "+ "
            },
            {
              "kind": "identifier",
              "text": "valueWithUndefinedInContext:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.javascriptcore~1documentation~1JavaScriptCore~1JSContext/title",
          "value": "JSContext"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.javascriptcore~1documentation~1JavaScriptCore~1JSContext/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "JSContext"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.javascriptcore~1documentation~1JavaScriptCore~1JSContext/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "JSContext"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.javascriptcore~1documentation~1JavaScriptCore~1JSValue~1init(newPromiseIn:fromExecutor:)/title",
          "value": "valueWithNewPromiseInContext:fromExecutor:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.javascriptcore~1documentation~1JavaScriptCore~1JSValue~1init(newPromiseIn:fromExecutor:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "+ "
            },
            {
              "kind": "identifier",
              "text": "valueWithNewPromiseInContext:fromExecutor:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.javascriptcore~1documentation~1JavaScriptCore~1JSValue~1init(point:inContext:)/title",
          "value": "valueWithPoint:inContext:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.javascriptcore~1documentation~1JavaScriptCore~1JSValue~1init(point:inContext:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "+ "
            },
            {
              "kind": "identifier",
              "text": "valueWithPoint:inContext:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.javascriptcore~1documentation~1JavaScriptCore~1JSValue~1init(size:inContext:)/title",
          "value": "valueWithSize:inContext:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.javascriptcore~1documentation~1JavaScriptCore~1JSValue~1init(size:inContext:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "+ "
            },
            {
              "kind": "identifier",
              "text": "valueWithSize:inContext:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.javascriptcore~1documentation~1JavaScriptCore~1JSValue~1init(object:in:)/title",
          "value": "valueWithObject:inContext:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.javascriptcore~1documentation~1JavaScriptCore~1JSValue~1init(object:in:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "+ "
            },
            {
              "kind": "identifier",
              "text": "valueWithObject:inContext:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.javascriptcore~1documentation~1JavaScriptCore~1JSValue~1init(int32:in:)/title",
          "value": "valueWithInt32:inContext:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.javascriptcore~1documentation~1JavaScriptCore~1JSValue~1init(int32:in:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "+ "
            },
            {
              "kind": "identifier",
              "text": "valueWithInt32:inContext:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.javascriptcore~1documentation~1JavaScriptCore~1JSValue~1init(rect:inContext:)/title",
          "value": "valueWithRect:inContext:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.javascriptcore~1documentation~1JavaScriptCore~1JSValue~1init(rect:inContext:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "+ "
            },
            {
              "kind": "identifier",
              "text": "valueWithRect:inContext:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.javascriptcore~1documentation~1JavaScriptCore~1JSValue~1init(range:inContext:)/title",
          "value": "valueWithRange:inContext:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.javascriptcore~1documentation~1JavaScriptCore~1JSValue~1init(range:inContext:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "+ "
            },
            {
              "kind": "identifier",
              "text": "valueWithRange:inContext:"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/javascriptcore/jsvalue/init(newpromisein:fromexecutor:)"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/javascriptcore/jsvalue/init(newpromisein:fromexecutor:)"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
