{
  "abstract": [
    {
      "text": "The audio channel flags that indicate how to interpret the channel coordinates.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes",
        "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/AudioChannelDescription"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/AudioChannelDescription/mChannelFlags"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@S@AudioChannelDescription@FI@mChannelFlags",
    "fragments": [
      {
        "kind": "keyword",
        "text": "var"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "mChannelFlags"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@E@AudioChannelFlags",
        "text": "AudioChannelFlags"
      }
    ],
    "modules": [
      {
        "name": "Core Audio Types"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "mChannelFlags"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "introducedAt": "2.0",
        "name": "iOS"
      },
      {
        "beta": false,
        "introducedAt": "2.0",
        "name": "iPadOS"
      },
      {
        "beta": false,
        "introducedAt": "10.2",
        "name": "macOS"
      },
      {
        "beta": false,
        "introducedAt": "9.0",
        "name": "tvOS"
      },
      {
        "beta": false,
        "introducedAt": "1.0",
        "name": "visionOS"
      },
      {
        "beta": false,
        "introducedAt": "3.0",
        "name": "watchOS"
      }
    ],
    "role": "symbol",
    "roleHeading": "Instance Property",
    "symbolKind": "property",
    "title": "mChannelFlags"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "var"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "mChannelFlags"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/AudioChannelFlags",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@E@AudioChannelFlags",
              "text": "AudioChannelFlags"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "See ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/audio-channel-coordinates",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " for possible values.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes": {
      "abstract": [
        {
          "text": "Use specialized data types to interact with audio streams, complex buffers, and audiovisual timestamps.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes",
      "kind": "symbol",
      "role": "collection",
      "title": "Core Audio Types",
      "type": "topic",
      "url": "/documentation/coreaudiotypes"
    },
    "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/AudioChannelDescription": {
      "abstract": [
        {
          "text": "A structure that describes a channel of audio data.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AudioChannelDescription"
        }
      ],
      "identifier": "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/AudioChannelDescription",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AudioChannelDescription"
        }
      ],
      "role": "symbol",
      "title": "AudioChannelDescription",
      "type": "topic",
      "url": "/documentation/coreaudiotypes/audiochanneldescription"
    },
    "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/AudioChannelDescription/mChannelFlags": {
      "abstract": [
        {
          "text": "The audio channel flags that indicate how to interpret the channel coordinates.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "mChannelFlags"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@AudioChannelFlags",
          "text": "AudioChannelFlags"
        }
      ],
      "identifier": "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/AudioChannelDescription/mChannelFlags",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "mChannelFlags"
        }
      ],
      "role": "symbol",
      "title": "mChannelFlags",
      "type": "topic",
      "url": "/documentation/coreaudiotypes/audiochanneldescription/mchannelflags"
    },
    "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/AudioChannelDescription/mChannelLabel": {
      "abstract": [
        {
          "text": "A label that describes the audio channel.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "mChannelLabel"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioChannelLabel",
          "text": "AudioChannelLabel"
        }
      ],
      "identifier": "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/AudioChannelDescription/mChannelLabel",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "mChannelLabel"
        }
      ],
      "role": "symbol",
      "title": "mChannelLabel",
      "type": "topic",
      "url": "/documentation/coreaudiotypes/audiochanneldescription/mchannellabel"
    },
    "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/AudioChannelDescription/mCoordinates": {
      "abstract": [
        {
          "text": "The coordinates that specify a precise speaker location.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "mCoordinates"
        },
        {
          "kind": "text",
          "text": ": ("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s7Float32a",
          "text": "Float32"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s7Float32a",
          "text": "Float32"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s7Float32a",
          "text": "Float32"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/AudioChannelDescription/mCoordinates",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "mCoordinates"
        }
      ],
      "role": "symbol",
      "title": "mCoordinates",
      "type": "topic",
      "url": "/documentation/coreaudiotypes/audiochanneldescription/mcoordinates"
    },
    "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/AudioChannelFlags": {
      "abstract": [
        {
          "text": "Constants that define the audio channel flags of an audio channel description.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AudioChannelFlags"
        }
      ],
      "identifier": "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/AudioChannelFlags",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AudioChannelFlags"
        }
      ],
      "role": "symbol",
      "title": "AudioChannelFlags",
      "type": "topic",
      "url": "/documentation/coreaudiotypes/audiochannelflags"
    },
    "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/AudioChannelLabel": {
      "abstract": [
        {
          "text": "Identifies how an audio data channel is to be used.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AudioChannelLabel"
        }
      ],
      "identifier": "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/AudioChannelLabel",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AudioChannelLabel"
        }
      ],
      "role": "symbol",
      "title": "AudioChannelLabel",
      "type": "topic",
      "url": "/documentation/coreaudiotypes/audiochannellabel"
    },
    "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/audio-channel-coordinates": {
      "abstract": [
        {
          "text": "Used in the ",
          "type": "text"
        },
        {
          "code": "mChannelFlags",
          "type": "codeVoice"
        },
        {
          "text": " field of an ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/AudioChannelDescription",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " structure.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/audio-channel-coordinates",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Audio Channel Coordinates",
      "type": "topic",
      "url": "/documentation/coreaudiotypes/audio-channel-coordinates"
    },
    "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/audio-channel-labels": {
      "abstract": [
        {
          "text": "Channel labels for use in the ",
          "type": "text"
        },
        {
          "code": "mChannelLabel",
          "type": "codeVoice"
        },
        {
          "text": " field of an ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/AudioChannelDescription",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " structure.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/audio-channel-labels",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Audio Channel Labels",
      "type": "topic",
      "url": "/documentation/coreaudiotypes/audio-channel-labels"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Accessing-the-Data",
      "generated": true,
      "identifiers": [
        "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/AudioChannelDescription/mChannelLabel",
        "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/AudioChannelDescription/mCoordinates",
        "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/AudioChannelLabel",
        "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/audio-channel-coordinates",
        "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/AudioChannelFlags",
        "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/audio-channel-labels"
      ],
      "title": "Accessing the Data"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.0",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.15",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.0",
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "6.0",
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Instance Property"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "mChannelFlags"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "property"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "mChannelFlags"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes",
                "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/AudioChannelDescription"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Accessing-the-Data",
              "generated": true,
              "identifiers": [
                "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/AudioChannelDescription/mChannelLabel",
                "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/AudioChannelDescription/mCoordinates",
                "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/AudioChannelLabel",
                "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/audio-channel-coordinates",
                "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/AudioChannelFlags"
              ],
              "title": "Accessing the Data"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "identifier": "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/AudioChannelFlags",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@E@AudioChannelFlags",
                    "text": "AudioChannelFlags"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "mChannelFlags"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudiotypes~1documentation~1CoreAudioTypes~1AudioChannelFlags/title",
          "value": "AudioChannelFlags"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudiotypes~1documentation~1CoreAudioTypes~1AudioChannelFlags/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AudioChannelFlags"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudiotypes~1documentation~1CoreAudioTypes~1AudioChannelFlags/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AudioChannelFlags"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudiotypes~1documentation~1CoreAudioTypes~1AudioChannelLabel/title",
          "value": "AudioChannelLabel"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudiotypes~1documentation~1CoreAudioTypes~1AudioChannelLabel/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AudioChannelLabel"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudiotypes~1documentation~1CoreAudioTypes~1AudioChannelLabel/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AudioChannelLabel"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudiotypes~1documentation~1CoreAudioTypes~1AudioChannelDescription/title",
          "value": "AudioChannelDescription"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudiotypes~1documentation~1CoreAudioTypes~1AudioChannelDescription/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AudioChannelDescription"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudiotypes~1documentation~1CoreAudioTypes~1AudioChannelDescription/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AudioChannelDescription"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudiotypes~1documentation~1CoreAudioTypes~1AudioChannelDescription~1mChannelLabel/title",
          "value": "mChannelLabel"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudiotypes~1documentation~1CoreAudioTypes~1AudioChannelDescription~1mChannelLabel/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "mChannelLabel"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudiotypes~1documentation~1CoreAudioTypes~1AudioChannelDescription~1mCoordinates/title",
          "value": "mCoordinates"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudiotypes~1documentation~1CoreAudioTypes~1AudioChannelDescription~1mCoordinates/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "mCoordinates"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudiotypes~1documentation~1CoreAudioTypes~1AudioChannelDescription~1mChannelFlags/title",
          "value": "mChannelFlags"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudiotypes~1documentation~1CoreAudioTypes~1AudioChannelDescription~1mChannelFlags/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "mChannelFlags"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/coreaudiotypes/audiochanneldescription/mchannelflags"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/coreaudiotypes/audiochanneldescription/mchannelflags"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
