{
  "abstract": [
    {
      "text": "The policy to use when saving changes to records.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.cloudkit/documentation/CloudKit",
        "doc://com.apple.cloudkit/documentation/CloudKit/CKModifyRecordsOperation"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.cloudkit/documentation/CloudKit/CKModifyRecordsOperation/savePolicy"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(cs)CKModifyRecordsOperation(py)savePolicy",
    "fragments": [
      {
        "kind": "keyword",
        "text": "var"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "savePolicy"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:objc(cs)CKModifyRecordsOperation",
        "text": "CKModifyRecordsOperation"
      },
      {
        "kind": "text",
        "text": "."
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@E@CKRecordSavePolicy",
        "text": "RecordSavePolicy"
      }
    ],
    "modules": [
      {
        "name": "CloudKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "savePolicy"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "8.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "8.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.1",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.10",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "3.0",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Instance Property",
    "symbolKind": "property",
    "title": "savePolicy"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "var"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "savePolicy"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.cloudkit/documentation/CloudKit/CKModifyRecordsOperation",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)CKModifyRecordsOperation",
              "text": "CKModifyRecordsOperation"
            },
            {
              "kind": "text",
              "text": "."
            },
            {
              "identifier": "doc://com.apple.cloudkit/documentation/CloudKit/CKModifyRecordsOperation/RecordSavePolicy",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@E@CKRecordSavePolicy",
              "text": "RecordSavePolicy"
            },
            {
              "kind": "text",
              "text": " { "
            },
            {
              "kind": "keyword",
              "text": "get"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "keyword",
              "text": "set"
            },
            {
              "kind": "text",
              "text": " }"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "The server uses this property to determine how to proceed when saving record changes. The exact behavior depends on the policy you choose:",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "items": [
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Use ",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.cloudkit/documentation/CloudKit/CKModifyRecordsOperation/RecordSavePolicy/ifServerRecordUnchanged",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": " to only save a record when the change tag of the local copy matches that of the server’s copy. If the server record’s change tag is more recent, CloudKit discards the save and returns a ",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.cloudkit/documentation/CloudKit/CKError/Code/serverRecordChanged",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": " error.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Use ",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.cloudkit/documentation/CloudKit/CKModifyRecordsOperation/RecordSavePolicy/changedKeys",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": " to save only the fields of the record that contain changes. The server doesn’t compare record change tags when using this policy.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Use ",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.cloudkit/documentation/CloudKit/CKModifyRecordsOperation/RecordSavePolicy/allKeys",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": " to save every field of the record, even those without changes. The server doesn’t compare record change tags when using this policy.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            }
          ],
          "type": "unorderedList"
        },
        {
          "inlineContent": [
            {
              "text": "If you change the property’s value, do so before you execute the operation or submit the operation to a queue. The default value is ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.cloudkit/documentation/CloudKit/CKModifyRecordsOperation/RecordSavePolicy/ifServerRecordUnchanged",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ".",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.cloudkit/documentation/CloudKit": {
      "abstract": [
        {
          "text": "Store structured app and user data in iCloud containers that all users of your app can share.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.cloudkit/documentation/CloudKit",
      "kind": "symbol",
      "role": "collection",
      "title": "CloudKit",
      "type": "topic",
      "url": "/documentation/cloudkit"
    },
    "doc://com.apple.cloudkit/documentation/CloudKit/CKError/Code/serverRecordChanged": {
      "abstract": [
        {
          "text": "An error that occurs when CloudKit rejects a record because the server’s version is different.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "serverRecordChanged"
        }
      ],
      "identifier": "doc://com.apple.cloudkit/documentation/CloudKit/CKError/Code/serverRecordChanged",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CKErrorServerRecordChanged"
        }
      ],
      "role": "symbol",
      "title": "CKError.Code.serverRecordChanged",
      "type": "topic",
      "url": "/documentation/cloudkit/ckerror/code/serverrecordchanged"
    },
    "doc://com.apple.cloudkit/documentation/CloudKit/CKModifyRecordsOperation": {
      "abstract": [
        {
          "text": "An operation that modifies one or more records.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CKModifyRecordsOperation"
        }
      ],
      "identifier": "doc://com.apple.cloudkit/documentation/CloudKit/CKModifyRecordsOperation",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CKModifyRecordsOperation"
        }
      ],
      "role": "symbol",
      "title": "CKModifyRecordsOperation",
      "type": "topic",
      "url": "/documentation/cloudkit/ckmodifyrecordsoperation"
    },
    "doc://com.apple.cloudkit/documentation/CloudKit/CKModifyRecordsOperation/RecordSavePolicy": {
      "abstract": [
        {
          "text": "Constants that indicate which policy to apply when saving records.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "RecordSavePolicy"
        }
      ],
      "identifier": "doc://com.apple.cloudkit/documentation/CloudKit/CKModifyRecordsOperation/RecordSavePolicy",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "RecordSavePolicy"
        }
      ],
      "role": "symbol",
      "title": "CKModifyRecordsOperation.RecordSavePolicy",
      "type": "topic",
      "url": "/documentation/cloudkit/ckmodifyrecordsoperation/recordsavepolicy"
    },
    "doc://com.apple.cloudkit/documentation/CloudKit/CKModifyRecordsOperation/RecordSavePolicy/allKeys": {
      "abstract": [
        {
          "text": "A policy that instructs CloudKit to save all keys of a record, even those without changes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "allKeys"
        }
      ],
      "identifier": "doc://com.apple.cloudkit/documentation/CloudKit/CKModifyRecordsOperation/RecordSavePolicy/allKeys",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CKRecordSaveAllKeys"
        }
      ],
      "role": "symbol",
      "title": "CKModifyRecordsOperation.RecordSavePolicy.allKeys",
      "type": "topic",
      "url": "/documentation/cloudkit/ckmodifyrecordsoperation/recordsavepolicy/allkeys"
    },
    "doc://com.apple.cloudkit/documentation/CloudKit/CKModifyRecordsOperation/RecordSavePolicy/changedKeys": {
      "abstract": [
        {
          "text": "A policy that instructs CloudKit to save only the fields of a record that contain changes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "changedKeys"
        }
      ],
      "identifier": "doc://com.apple.cloudkit/documentation/CloudKit/CKModifyRecordsOperation/RecordSavePolicy/changedKeys",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CKRecordSaveChangedKeys"
        }
      ],
      "role": "symbol",
      "title": "CKModifyRecordsOperation.RecordSavePolicy.changedKeys",
      "type": "topic",
      "url": "/documentation/cloudkit/ckmodifyrecordsoperation/recordsavepolicy/changedkeys"
    },
    "doc://com.apple.cloudkit/documentation/CloudKit/CKModifyRecordsOperation/RecordSavePolicy/ifServerRecordUnchanged": {
      "abstract": [
        {
          "text": "A policy that instructs CloudKit to only proceed if the record’s change tag matches that of the server’s copy.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ifServerRecordUnchanged"
        }
      ],
      "identifier": "doc://com.apple.cloudkit/documentation/CloudKit/CKModifyRecordsOperation/RecordSavePolicy/ifServerRecordUnchanged",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CKRecordSaveIfServerRecordUnchanged"
        }
      ],
      "role": "symbol",
      "title": "CKModifyRecordsOperation.RecordSavePolicy.ifServerRecordUnchanged",
      "type": "topic",
      "url": "/documentation/cloudkit/ckmodifyrecordsoperation/recordsavepolicy/ifserverrecordunchanged"
    },
    "doc://com.apple.cloudkit/documentation/CloudKit/CKModifyRecordsOperation/clientChangeTokenData": {
      "abstract": [
        {
          "text": "A token that tracks local changes to records.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "clientChangeTokenData"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10Foundation4DataV",
          "text": "Data"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.cloudkit/documentation/CloudKit/CKModifyRecordsOperation/clientChangeTokenData",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "clientChangeTokenData"
        }
      ],
      "role": "symbol",
      "title": "clientChangeTokenData",
      "type": "topic",
      "url": "/documentation/cloudkit/ckmodifyrecordsoperation/clientchangetokendata"
    },
    "doc://com.apple.cloudkit/documentation/CloudKit/CKModifyRecordsOperation/isAtomic": {
      "abstract": [
        {
          "text": "A Boolean value that indicates whether the entire operation fails when CloudKit can’t update one or more records in a record zone.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "isAtomic"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.cloudkit/documentation/CloudKit/CKModifyRecordsOperation/isAtomic",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "atomic"
        }
      ],
      "role": "symbol",
      "title": "isAtomic",
      "type": "topic",
      "url": "/documentation/cloudkit/ckmodifyrecordsoperation/isatomic"
    },
    "doc://com.apple.cloudkit/documentation/CloudKit/CKModifyRecordsOperation/recordIDsToDelete": {
      "abstract": [
        {
          "text": "The IDs of the records to delete permanently from the database.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "recordIDsToDelete"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)CKRecord",
          "text": "CKRecord"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)CKRecordID",
          "text": "ID"
        },
        {
          "kind": "text",
          "text": "]?"
        }
      ],
      "identifier": "doc://com.apple.cloudkit/documentation/CloudKit/CKModifyRecordsOperation/recordIDsToDelete",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "recordIDsToDelete"
        }
      ],
      "role": "symbol",
      "title": "recordIDsToDelete",
      "type": "topic",
      "url": "/documentation/cloudkit/ckmodifyrecordsoperation/recordidstodelete"
    },
    "doc://com.apple.cloudkit/documentation/CloudKit/CKModifyRecordsOperation/recordsToSave": {
      "abstract": [
        {
          "text": "The records to save to the database.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "recordsToSave"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)CKRecord",
          "text": "CKRecord"
        },
        {
          "kind": "text",
          "text": "]?"
        }
      ],
      "identifier": "doc://com.apple.cloudkit/documentation/CloudKit/CKModifyRecordsOperation/recordsToSave",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "recordsToSave"
        }
      ],
      "role": "symbol",
      "title": "recordsToSave",
      "type": "topic",
      "url": "/documentation/cloudkit/ckmodifyrecordsoperation/recordstosave"
    },
    "doc://com.apple.cloudkit/documentation/CloudKit/CKModifyRecordsOperation/savePolicy": {
      "abstract": [
        {
          "text": "The policy to use when saving changes to records.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "savePolicy"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)CKModifyRecordsOperation",
          "text": "CKModifyRecordsOperation"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@CKRecordSavePolicy",
          "text": "RecordSavePolicy"
        }
      ],
      "identifier": "doc://com.apple.cloudkit/documentation/CloudKit/CKModifyRecordsOperation/savePolicy",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "savePolicy"
        }
      ],
      "role": "symbol",
      "title": "savePolicy",
      "type": "topic",
      "url": "/documentation/cloudkit/ckmodifyrecordsoperation/savepolicy"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Configuring-the-Modify-Record-Operation",
      "generated": true,
      "identifiers": [
        "doc://com.apple.cloudkit/documentation/CloudKit/CKModifyRecordsOperation/recordsToSave",
        "doc://com.apple.cloudkit/documentation/CloudKit/CKModifyRecordsOperation/recordIDsToDelete",
        "doc://com.apple.cloudkit/documentation/CloudKit/CKModifyRecordsOperation/clientChangeTokenData",
        "doc://com.apple.cloudkit/documentation/CloudKit/CKModifyRecordsOperation/isAtomic",
        "doc://com.apple.cloudkit/documentation/CloudKit/CKModifyRecordsOperation/RecordSavePolicy"
      ],
      "title": "Configuring the Modify Record Operation"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "8.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "8.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.1",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.10",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "3.0",
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Instance Property"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "savePolicy"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "property"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "savePolicy"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.cloudkit/documentation/CloudKit",
                "doc://com.apple.cloudkit/documentation/CloudKit/CKModifyRecordsOperation"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Configuring-the-Modify-Record-Operation",
              "generated": true,
              "identifiers": [
                "doc://com.apple.cloudkit/documentation/CloudKit/CKModifyRecordsOperation/recordsToSave",
                "doc://com.apple.cloudkit/documentation/CloudKit/CKModifyRecordsOperation/recordIDsToDelete",
                "doc://com.apple.cloudkit/documentation/CloudKit/CKModifyRecordsOperation/clientChangeTokenData",
                "doc://com.apple.cloudkit/documentation/CloudKit/CKModifyRecordsOperation/isAtomic",
                "doc://com.apple.cloudkit/documentation/CloudKit/CKModifyRecordsOperation/RecordSavePolicy"
              ],
              "title": "Configuring the Modify Record Operation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "@property"
                  },
                  {
                    "kind": "text",
                    "text": " ("
                  },
                  {
                    "kind": "keyword",
                    "text": "nonatomic"
                  },
                  {
                    "kind": "text",
                    "text": ", "
                  },
                  {
                    "kind": "keyword",
                    "text": "assign"
                  },
                  {
                    "kind": "text",
                    "text": ") "
                  },
                  {
                    "identifier": "doc://com.apple.cloudkit/documentation/CloudKit/CKModifyRecordsOperation/RecordSavePolicy",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@E@CKRecordSavePolicy",
                    "text": "CKRecordSavePolicy"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "savePolicy"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cloudkit~1documentation~1CloudKit~1CKModifyRecordsOperation/title",
          "value": "CKModifyRecordsOperation"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cloudkit~1documentation~1CloudKit~1CKModifyRecordsOperation/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CKModifyRecordsOperation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cloudkit~1documentation~1CloudKit~1CKModifyRecordsOperation/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CKModifyRecordsOperation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cloudkit~1documentation~1CloudKit~1CKModifyRecordsOperation~1RecordSavePolicy~1allKeys/title",
          "value": "CKRecordSaveAllKeys"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cloudkit~1documentation~1CloudKit~1CKModifyRecordsOperation~1RecordSavePolicy~1allKeys/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CKRecordSaveAllKeys"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cloudkit~1documentation~1CloudKit~1CKModifyRecordsOperation~1savePolicy/title",
          "value": "savePolicy"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cloudkit~1documentation~1CloudKit~1CKModifyRecordsOperation~1savePolicy/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "savePolicy"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cloudkit~1documentation~1CloudKit~1CKModifyRecordsOperation~1clientChangeTokenData/title",
          "value": "clientChangeTokenData"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cloudkit~1documentation~1CloudKit~1CKModifyRecordsOperation~1clientChangeTokenData/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "clientChangeTokenData"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cloudkit~1documentation~1CloudKit~1CKError~1Code~1serverRecordChanged/title",
          "value": "CKErrorServerRecordChanged"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cloudkit~1documentation~1CloudKit~1CKError~1Code~1serverRecordChanged/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CKErrorServerRecordChanged"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cloudkit~1documentation~1CloudKit~1CKModifyRecordsOperation~1recordIDsToDelete/title",
          "value": "recordIDsToDelete"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cloudkit~1documentation~1CloudKit~1CKModifyRecordsOperation~1recordIDsToDelete/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "recordIDsToDelete"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cloudkit~1documentation~1CloudKit~1CKModifyRecordsOperation~1isAtomic/title",
          "value": "atomic"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cloudkit~1documentation~1CloudKit~1CKModifyRecordsOperation~1isAtomic/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "atomic"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cloudkit~1documentation~1CloudKit~1CKModifyRecordsOperation~1RecordSavePolicy/title",
          "value": "CKRecordSavePolicy"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cloudkit~1documentation~1CloudKit~1CKModifyRecordsOperation~1RecordSavePolicy/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CKRecordSavePolicy"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cloudkit~1documentation~1CloudKit~1CKModifyRecordsOperation~1RecordSavePolicy/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CKRecordSavePolicy"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cloudkit~1documentation~1CloudKit~1CKModifyRecordsOperation~1RecordSavePolicy~1changedKeys/title",
          "value": "CKRecordSaveChangedKeys"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cloudkit~1documentation~1CloudKit~1CKModifyRecordsOperation~1RecordSavePolicy~1changedKeys/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CKRecordSaveChangedKeys"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cloudkit~1documentation~1CloudKit~1CKModifyRecordsOperation~1recordsToSave/title",
          "value": "recordsToSave"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cloudkit~1documentation~1CloudKit~1CKModifyRecordsOperation~1recordsToSave/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "recordsToSave"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cloudkit~1documentation~1CloudKit~1CKModifyRecordsOperation~1RecordSavePolicy~1ifServerRecordUnchanged/title",
          "value": "CKRecordSaveIfServerRecordUnchanged"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cloudkit~1documentation~1CloudKit~1CKModifyRecordsOperation~1RecordSavePolicy~1ifServerRecordUnchanged/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CKRecordSaveIfServerRecordUnchanged"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/cloudkit/ckmodifyrecordsoperation/savepolicy"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/cloudkit/ckmodifyrecordsoperation/savepolicy"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
