{
  "abstract": [
    {
      "text": "Constants that define the levels of quality for a person segmentation request.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.vision/documentation/Vision",
        "doc://com.apple.vision/documentation/Vision/VNGeneratePersonSegmentationRequest"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.vision/documentation/Vision/VNGeneratePersonSegmentationRequest/QualityLevel-swift.enum"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "extendedModule": "Vision",
    "externalID": "c:@E@VNGeneratePersonSegmentationRequestQualityLevel",
    "fragments": [
      {
        "kind": "keyword",
        "text": "enum"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "QualityLevel"
      }
    ],
    "modules": [
      {
        "name": "Vision"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "QualityLevel"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "11.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "11.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.0",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.13",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "11.0",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Enumeration",
    "symbolKind": "enum",
    "title": "VNGeneratePersonSegmentationRequest.QualityLevel"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "enum"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "QualityLevel"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.vision/documentation/Vision": {
      "abstract": [
        {
          "text": "Apply computer vision algorithms to perform a variety of tasks on input images and videos.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.vision/documentation/Vision",
      "kind": "symbol",
      "role": "collection",
      "title": "Vision",
      "type": "topic",
      "url": "/documentation/vision"
    },
    "doc://com.apple.vision/documentation/Vision/VNGeneratePersonSegmentationRequest": {
      "abstract": [
        {
          "text": "An object that produces a matte image for a person it finds in the input image.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "VNGeneratePersonSegmentationRequest"
        }
      ],
      "identifier": "doc://com.apple.vision/documentation/Vision/VNGeneratePersonSegmentationRequest",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "VNGeneratePersonSegmentationRequest"
        }
      ],
      "role": "symbol",
      "title": "VNGeneratePersonSegmentationRequest",
      "type": "topic",
      "url": "/documentation/vision/vngeneratepersonsegmentationrequest"
    },
    "doc://com.apple.vision/documentation/Vision/VNGeneratePersonSegmentationRequest/QualityLevel-swift.enum": {
      "abstract": [
        {
          "text": "Constants that define the levels of quality for a person segmentation request.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "QualityLevel"
        }
      ],
      "identifier": "doc://com.apple.vision/documentation/Vision/VNGeneratePersonSegmentationRequest/QualityLevel-swift.enum",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "QualityLevel"
        }
      ],
      "role": "symbol",
      "title": "VNGeneratePersonSegmentationRequest.QualityLevel",
      "type": "topic",
      "url": "/documentation/vision/vngeneratepersonsegmentationrequest/qualitylevel-swift.enum"
    },
    "doc://com.apple.vision/documentation/Vision/VNGeneratePersonSegmentationRequest/QualityLevel-swift.enum/accurate": {
      "abstract": [
        {
          "text": "Prefers image quality over performance.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "accurate"
        }
      ],
      "identifier": "doc://com.apple.vision/documentation/Vision/VNGeneratePersonSegmentationRequest/QualityLevel-swift.enum/accurate",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "VNGeneratePersonSegmentationRequestQualityLevelAccurate"
        }
      ],
      "role": "symbol",
      "title": "VNGeneratePersonSegmentationRequest.QualityLevel.accurate",
      "type": "topic",
      "url": "/documentation/vision/vngeneratepersonsegmentationrequest/qualitylevel-swift.enum/accurate"
    },
    "doc://com.apple.vision/documentation/Vision/VNGeneratePersonSegmentationRequest/QualityLevel-swift.enum/balanced": {
      "abstract": [
        {
          "text": "Prefers processing that balances image quality and performance.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "balanced"
        }
      ],
      "identifier": "doc://com.apple.vision/documentation/Vision/VNGeneratePersonSegmentationRequest/QualityLevel-swift.enum/balanced",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "VNGeneratePersonSegmentationRequestQualityLevelBalanced"
        }
      ],
      "role": "symbol",
      "title": "VNGeneratePersonSegmentationRequest.QualityLevel.balanced",
      "type": "topic",
      "url": "/documentation/vision/vngeneratepersonsegmentationrequest/qualitylevel-swift.enum/balanced"
    },
    "doc://com.apple.vision/documentation/Vision/VNGeneratePersonSegmentationRequest/QualityLevel-swift.enum/fast": {
      "abstract": [
        {
          "text": "Prefers performance over image quality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "fast"
        }
      ],
      "identifier": "doc://com.apple.vision/documentation/Vision/VNGeneratePersonSegmentationRequest/QualityLevel-swift.enum/fast",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "VNGeneratePersonSegmentationRequestQualityLevelFast"
        }
      ],
      "role": "symbol",
      "title": "VNGeneratePersonSegmentationRequest.QualityLevel.fast",
      "type": "topic",
      "url": "/documentation/vision/vngeneratepersonsegmentationrequest/qualitylevel-swift.enum/fast"
    },
    "doc://com.apple.vision/documentation/Vision/VNGeneratePersonSegmentationRequest/QualityLevel-swift.enum/init(rawValue:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "?("
        },
        {
          "kind": "externalParam",
          "text": "rawValue"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Su",
          "text": "UInt"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.vision/documentation/Vision/VNGeneratePersonSegmentationRequest/QualityLevel-swift.enum/init(rawValue:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "init(rawValue:)",
      "type": "topic",
      "url": "/documentation/vision/vngeneratepersonsegmentationrequest/qualitylevel-swift.enum/init(rawvalue:)"
    },
    "doc://com.apple.vision/documentation/Vision/VNGeneratePersonSegmentationRequest/outputPixelFormat": {
      "abstract": [
        {
          "text": "The pixel format of the output image.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "outputPixelFormat"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OSType",
          "text": "OSType"
        }
      ],
      "identifier": "doc://com.apple.vision/documentation/Vision/VNGeneratePersonSegmentationRequest/outputPixelFormat",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "outputPixelFormat"
        }
      ],
      "role": "symbol",
      "title": "outputPixelFormat",
      "type": "topic",
      "url": "/documentation/vision/vngeneratepersonsegmentationrequest/outputpixelformat"
    },
    "doc://com.apple.vision/documentation/Vision/VNGeneratePersonSegmentationRequest/qualityLevel-swift.property": {
      "abstract": [
        {
          "text": "A value that indicates how the request balances accuracy and performance.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "qualityLevel"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)VNGeneratePersonSegmentationRequest",
          "text": "VNGeneratePersonSegmentationRequest"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@VNGeneratePersonSegmentationRequestQualityLevel",
          "text": "QualityLevel"
        }
      ],
      "identifier": "doc://com.apple.vision/documentation/Vision/VNGeneratePersonSegmentationRequest/qualityLevel-swift.property",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "qualityLevel"
        }
      ],
      "role": "symbol",
      "title": "qualityLevel",
      "type": "topic",
      "url": "/documentation/vision/vngeneratepersonsegmentationrequest/qualitylevel-swift.property"
    },
    "doc://com.externally.resolved.symbol/s:SH": {
      "abstract": [
        {
          "text": "A type that can be hashed into a `Hasher` to produce an integer hash value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Hashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SQ",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SH",
      "kind": "symbol",
      "role": "symbol",
      "title": "Hashable",
      "type": "topic",
      "url": "/documentation/Swift/Hashable"
    },
    "doc://com.externally.resolved.symbol/s:SQ": {
      "abstract": [
        {
          "text": "A type that can be compared for value equality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SQ",
      "kind": "symbol",
      "role": "symbol",
      "title": "Equatable",
      "type": "topic",
      "url": "/documentation/Swift/Equatable"
    },
    "doc://com.externally.resolved.symbol/s:SY": {
      "abstract": [
        {
          "text": "A type that can be converted to and from an associated raw value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "RawRepresentable"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SY8RawValueQa",
          "text": "RawValue"
        },
        {
          "kind": "text",
          "text": ">"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SY",
      "kind": "symbol",
      "role": "symbol",
      "title": "RawRepresentable",
      "type": "topic",
      "url": "/documentation/Swift/RawRepresentable"
    },
    "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BitwiseCopyable"
        },
        {
          "kind": "text",
          "text": " : ~Escapable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "BitwiseCopyable",
      "type": "topic",
      "url": "/documentation/Swift/BitwiseCopyable"
    },
    "doc://com.externally.resolved.symbol/s:s8SendableP": {
      "abstract": [
        {
          "text": "A thread-safe type whose values can be shared across arbitrary concurrent contexts without introducing a risk of data races.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Sendable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s8SendableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "Sendable",
      "type": "topic",
      "url": "/documentation/Swift/Sendable"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
        "doc://com.externally.resolved.symbol/s:SQ",
        "doc://com.externally.resolved.symbol/s:SH",
        "doc://com.externally.resolved.symbol/s:SY",
        "doc://com.externally.resolved.symbol/s:s8SendableP"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Configuring-the-Request",
      "generated": true,
      "identifiers": [
        "doc://com.apple.vision/documentation/Vision/VNGeneratePersonSegmentationRequest/outputPixelFormat",
        "doc://com.apple.vision/documentation/Vision/VNGeneratePersonSegmentationRequest/qualityLevel-swift.property"
      ],
      "title": "Configuring the Request"
    }
  ],
  "topicSections": [
    {
      "anchor": "Quality-Levels",
      "identifiers": [
        "doc://com.apple.vision/documentation/Vision/VNGeneratePersonSegmentationRequest/QualityLevel-swift.enum/accurate",
        "doc://com.apple.vision/documentation/Vision/VNGeneratePersonSegmentationRequest/QualityLevel-swift.enum/balanced",
        "doc://com.apple.vision/documentation/Vision/VNGeneratePersonSegmentationRequest/QualityLevel-swift.enum/fast"
      ],
      "title": "Quality Levels"
    },
    {
      "anchor": "Creating-a-Quality-Level",
      "identifiers": [
        "doc://com.apple.vision/documentation/Vision/VNGeneratePersonSegmentationRequest/QualityLevel-swift.enum/init(rawValue:)"
      ],
      "title": "Creating a Quality Level"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "11.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "11.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.0",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.13",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "11.0",
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "VNGeneratePersonSegmentationRequestQualityLevel"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "enum"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "VNGeneratePersonSegmentationRequestQualityLevel"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "VNGeneratePersonSegmentationRequestQualityLevel"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.vision/documentation/Vision"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Quality-Levels",
              "identifiers": [
                "doc://com.apple.vision/documentation/Vision/VNGeneratePersonSegmentationRequest/QualityLevel-swift.enum/accurate",
                "doc://com.apple.vision/documentation/Vision/VNGeneratePersonSegmentationRequest/QualityLevel-swift.enum/balanced",
                "doc://com.apple.vision/documentation/Vision/VNGeneratePersonSegmentationRequest/QualityLevel-swift.enum/fast"
              ],
              "title": "Quality Levels"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Configuring-the-Request",
              "generated": true,
              "identifiers": [
                "doc://com.apple.vision/documentation/Vision/VNGeneratePersonSegmentationRequest/outputPixelFormat",
                "doc://com.apple.vision/documentation/Vision/VNGeneratePersonSegmentationRequest/qualityLevel-swift.property"
              ],
              "title": "Configuring the Request"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "enum"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "VNGeneratePersonSegmentationRequestQualityLevel"
                  },
                  {
                    "kind": "text",
                    "text": " : "
                  },
                  {
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@NSUInteger",
                    "text": "NSUInteger"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNGeneratePersonSegmentationRequest~1outputPixelFormat/title",
          "value": "outputPixelFormat"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNGeneratePersonSegmentationRequest~1outputPixelFormat/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "outputPixelFormat"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNGeneratePersonSegmentationRequest~1QualityLevel-swift.enum/title",
          "value": "VNGeneratePersonSegmentationRequestQualityLevel"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNGeneratePersonSegmentationRequest~1QualityLevel-swift.enum/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "VNGeneratePersonSegmentationRequestQualityLevel"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNGeneratePersonSegmentationRequest~1QualityLevel-swift.enum/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "VNGeneratePersonSegmentationRequestQualityLevel"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNGeneratePersonSegmentationRequest/title",
          "value": "VNGeneratePersonSegmentationRequest"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNGeneratePersonSegmentationRequest/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "VNGeneratePersonSegmentationRequest"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNGeneratePersonSegmentationRequest/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "VNGeneratePersonSegmentationRequest"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNGeneratePersonSegmentationRequest~1qualityLevel-swift.property/title",
          "value": "qualityLevel"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNGeneratePersonSegmentationRequest~1qualityLevel-swift.property/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "qualityLevel"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNGeneratePersonSegmentationRequest~1QualityLevel-swift.enum~1fast/title",
          "value": "VNGeneratePersonSegmentationRequestQualityLevelFast"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNGeneratePersonSegmentationRequest~1QualityLevel-swift.enum~1fast/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "VNGeneratePersonSegmentationRequestQualityLevelFast"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNGeneratePersonSegmentationRequest~1QualityLevel-swift.enum~1balanced/title",
          "value": "VNGeneratePersonSegmentationRequestQualityLevelBalanced"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNGeneratePersonSegmentationRequest~1QualityLevel-swift.enum~1balanced/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "VNGeneratePersonSegmentationRequestQualityLevelBalanced"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNGeneratePersonSegmentationRequest~1QualityLevel-swift.enum~1accurate/title",
          "value": "VNGeneratePersonSegmentationRequestQualityLevelAccurate"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNGeneratePersonSegmentationRequest~1QualityLevel-swift.enum~1accurate/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "VNGeneratePersonSegmentationRequestQualityLevelAccurate"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/vision/vngeneratepersonsegmentationrequest/qualitylevel-swift.enum"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/vision/vngeneratepersonsegmentationrequest/qualitylevel-swift.enum"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
