{
  "abstract": [
    {
      "text": "The default type for new tags.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.imageio/documentation/ImageIO",
        "doc://com.apple.imageio/documentation/ImageIO/CGImageMetadataType"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.imageio/documentation/ImageIO/CGImageMetadataType/default"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@CGImageMetadataType@kCGImageMetadataTypeDefault",
    "fragments": [
      {
        "kind": "keyword",
        "text": "case"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "`default`"
      }
    ],
    "modules": [
      {
        "name": "Image I/O"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "kCGImageMetadataTypeDefault"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "4.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "4.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.0",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.8",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "9.0",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "2.0",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Case",
    "symbolKind": "case",
    "title": "CGImageMetadataType.default"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "case"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "`default`"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "When you create new tags, the system assigns this value initially. The system uses the Core Foundation type of the metadata tag’s value to determine an appropriate type. During the serialization process, the system converts the type automatically to a nondefault value.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.imageio/documentation/ImageIO": {
      "abstract": [
        {
          "text": "Read and write most image file formats, and access an image’s metadata.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.imageio/documentation/ImageIO",
      "kind": "symbol",
      "role": "collection",
      "title": "Image I/O",
      "type": "topic",
      "url": "/documentation/imageio"
    },
    "doc://com.apple.imageio/documentation/ImageIO/CGImageMetadataType": {
      "abstract": [
        {
          "text": "Constants that indicate the XMP type for a metadata tag.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CGImageMetadataType"
        }
      ],
      "identifier": "doc://com.apple.imageio/documentation/ImageIO/CGImageMetadataType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CGImageMetadataType"
        }
      ],
      "role": "symbol",
      "title": "CGImageMetadataType",
      "type": "topic",
      "url": "/documentation/imageio/cgimagemetadatatype"
    },
    "doc://com.apple.imageio/documentation/ImageIO/CGImageMetadataType/alternateArray": {
      "abstract": [
        {
          "text": "An ordered array, in which all elements are alternates for the same value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "alternateArray"
        }
      ],
      "identifier": "doc://com.apple.imageio/documentation/ImageIO/CGImageMetadataType/alternateArray",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCGImageMetadataTypeAlternateArray"
        }
      ],
      "role": "symbol",
      "title": "CGImageMetadataType.alternateArray",
      "type": "topic",
      "url": "/documentation/imageio/cgimagemetadatatype/alternatearray"
    },
    "doc://com.apple.imageio/documentation/ImageIO/CGImageMetadataType/alternateText": {
      "abstract": [
        {
          "text": "An alternate array, in which all elements are localized strings for the same value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "alternateText"
        }
      ],
      "identifier": "doc://com.apple.imageio/documentation/ImageIO/CGImageMetadataType/alternateText",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCGImageMetadataTypeAlternateText"
        }
      ],
      "role": "symbol",
      "title": "CGImageMetadataType.alternateText",
      "type": "topic",
      "url": "/documentation/imageio/cgimagemetadatatype/alternatetext"
    },
    "doc://com.apple.imageio/documentation/ImageIO/CGImageMetadataType/arrayOrdered": {
      "abstract": [
        {
          "text": "An array that preserves the order of items.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "arrayOrdered"
        }
      ],
      "identifier": "doc://com.apple.imageio/documentation/ImageIO/CGImageMetadataType/arrayOrdered",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCGImageMetadataTypeArrayOrdered"
        }
      ],
      "role": "symbol",
      "title": "CGImageMetadataType.arrayOrdered",
      "type": "topic",
      "url": "/documentation/imageio/cgimagemetadatatype/arrayordered"
    },
    "doc://com.apple.imageio/documentation/ImageIO/CGImageMetadataType/arrayUnordered": {
      "abstract": [
        {
          "text": "An array that doesn’t preserve the order of items.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "arrayUnordered"
        }
      ],
      "identifier": "doc://com.apple.imageio/documentation/ImageIO/CGImageMetadataType/arrayUnordered",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCGImageMetadataTypeArrayUnordered"
        }
      ],
      "role": "symbol",
      "title": "CGImageMetadataType.arrayUnordered",
      "type": "topic",
      "url": "/documentation/imageio/cgimagemetadatatype/arrayunordered"
    },
    "doc://com.apple.imageio/documentation/ImageIO/CGImageMetadataType/default": {
      "abstract": [
        {
          "text": "The default type for new tags.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "`default`"
        }
      ],
      "identifier": "doc://com.apple.imageio/documentation/ImageIO/CGImageMetadataType/default",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCGImageMetadataTypeDefault"
        }
      ],
      "role": "symbol",
      "title": "CGImageMetadataType.default",
      "type": "topic",
      "url": "/documentation/imageio/cgimagemetadatatype/default"
    },
    "doc://com.apple.imageio/documentation/ImageIO/CGImageMetadataType/invalid": {
      "abstract": [
        {
          "text": "An invalid metadata type.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "invalid"
        }
      ],
      "identifier": "doc://com.apple.imageio/documentation/ImageIO/CGImageMetadataType/invalid",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCGImageMetadataTypeInvalid"
        }
      ],
      "role": "symbol",
      "title": "CGImageMetadataType.invalid",
      "type": "topic",
      "url": "/documentation/imageio/cgimagemetadatatype/invalid"
    },
    "doc://com.apple.imageio/documentation/ImageIO/CGImageMetadataType/string": {
      "abstract": [
        {
          "text": "A string value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "string"
        }
      ],
      "identifier": "doc://com.apple.imageio/documentation/ImageIO/CGImageMetadataType/string",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCGImageMetadataTypeString"
        }
      ],
      "role": "symbol",
      "title": "CGImageMetadataType.string",
      "type": "topic",
      "url": "/documentation/imageio/cgimagemetadatatype/string"
    },
    "doc://com.apple.imageio/documentation/ImageIO/CGImageMetadataType/structure": {
      "abstract": [
        {
          "text": "A collection of keys and values.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "structure"
        }
      ],
      "identifier": "doc://com.apple.imageio/documentation/ImageIO/CGImageMetadataType/structure",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCGImageMetadataTypeStructure"
        }
      ],
      "role": "symbol",
      "title": "CGImageMetadataType.structure",
      "type": "topic",
      "url": "/documentation/imageio/cgimagemetadatatype/structure"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Metadata-Types",
      "generated": true,
      "identifiers": [
        "doc://com.apple.imageio/documentation/ImageIO/CGImageMetadataType/invalid",
        "doc://com.apple.imageio/documentation/ImageIO/CGImageMetadataType/string",
        "doc://com.apple.imageio/documentation/ImageIO/CGImageMetadataType/arrayUnordered",
        "doc://com.apple.imageio/documentation/ImageIO/CGImageMetadataType/arrayOrdered",
        "doc://com.apple.imageio/documentation/ImageIO/CGImageMetadataType/alternateArray",
        "doc://com.apple.imageio/documentation/ImageIO/CGImageMetadataType/alternateText",
        "doc://com.apple.imageio/documentation/ImageIO/CGImageMetadataType/structure"
      ],
      "title": "Metadata Types"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "4.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "4.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.0",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.8",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "9.0",
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "2.0",
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration Case"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "kCGImageMetadataTypeDefault"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "case"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCGImageMetadataTypeDefault"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.imageio/documentation/ImageIO",
                "doc://com.apple.imageio/documentation/ImageIO/CGImageMetadataType"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Metadata-Types",
              "generated": true,
              "identifiers": [
                "doc://com.apple.imageio/documentation/ImageIO/CGImageMetadataType/invalid",
                "doc://com.apple.imageio/documentation/ImageIO/CGImageMetadataType/string",
                "doc://com.apple.imageio/documentation/ImageIO/CGImageMetadataType/arrayUnordered",
                "doc://com.apple.imageio/documentation/ImageIO/CGImageMetadataType/arrayOrdered",
                "doc://com.apple.imageio/documentation/ImageIO/CGImageMetadataType/alternateArray",
                "doc://com.apple.imageio/documentation/ImageIO/CGImageMetadataType/alternateText",
                "doc://com.apple.imageio/documentation/ImageIO/CGImageMetadataType/structure"
              ],
              "title": "Metadata Types"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "identifier",
                    "text": "kCGImageMetadataTypeDefault"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1CGImageMetadataType~1alternateArray/title",
          "value": "kCGImageMetadataTypeAlternateArray"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1CGImageMetadataType~1alternateArray/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCGImageMetadataTypeAlternateArray"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1CGImageMetadataType~1default/title",
          "value": "kCGImageMetadataTypeDefault"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1CGImageMetadataType~1default/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCGImageMetadataTypeDefault"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1CGImageMetadataType~1alternateText/title",
          "value": "kCGImageMetadataTypeAlternateText"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1CGImageMetadataType~1alternateText/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCGImageMetadataTypeAlternateText"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1CGImageMetadataType~1invalid/title",
          "value": "kCGImageMetadataTypeInvalid"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1CGImageMetadataType~1invalid/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCGImageMetadataTypeInvalid"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1CGImageMetadataType~1structure/title",
          "value": "kCGImageMetadataTypeStructure"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1CGImageMetadataType~1structure/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCGImageMetadataTypeStructure"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1CGImageMetadataType~1arrayOrdered/title",
          "value": "kCGImageMetadataTypeArrayOrdered"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1CGImageMetadataType~1arrayOrdered/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCGImageMetadataTypeArrayOrdered"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1CGImageMetadataType/title",
          "value": "CGImageMetadataType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1CGImageMetadataType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CGImageMetadataType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1CGImageMetadataType/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CGImageMetadataType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1CGImageMetadataType~1string/title",
          "value": "kCGImageMetadataTypeString"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1CGImageMetadataType~1string/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCGImageMetadataTypeString"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1CGImageMetadataType~1arrayUnordered/title",
          "value": "kCGImageMetadataTypeArrayUnordered"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1CGImageMetadataType~1arrayUnordered/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCGImageMetadataTypeArrayUnordered"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/imageio/cgimagemetadatatype/default"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/imageio/cgimagemetadatatype/default"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
