{
  "abstract": [
    {
      "text": "A constant that represents the Home key.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.xctest/documentation/XCTest",
        "doc://com.apple.xctest/documentation/XCTest/XCUIKeyboardKey"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.xctest/documentation/XCTest/XCUIKeyboardKey/home"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "extendedModule": "XCTest",
    "externalID": "c:@XCUIKeyboardKeyHome",
    "fragments": [
      {
        "kind": "keyword",
        "text": "static"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "keyword",
        "text": "let"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "home"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@T@XCUIKeyboardKey",
        "text": "XCUIKeyboardKey"
      }
    ],
    "modules": [
      {
        "name": "XCTest"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "XCUIKeyboardKeyHome"
      }
    ],
    "role": "symbol",
    "roleHeading": "Type Property",
    "symbolKind": "property",
    "title": "home"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "static"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "keyword",
              "text": "let"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "home"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.xctest/documentation/XCTest/XCUIKeyboardKey",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@XCUIKeyboardKey",
              "text": "XCUIKeyboardKey"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.xctest/documentation/XCTest": {
      "abstract": [
        {
          "text": "Create and run unit tests, performance tests, and UI tests for your Xcode project.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.xctest/documentation/XCTest",
      "kind": "symbol",
      "role": "collection",
      "title": "XCTest",
      "type": "topic",
      "url": "/documentation/xctest"
    },
    "doc://com.apple.xctest/documentation/XCTest/XCUIKeyboardKey": {
      "abstract": [
        {
          "text": "Constants to represent keys that have no typewritten equivalent.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "XCUIKeyboardKey"
        }
      ],
      "identifier": "doc://com.apple.xctest/documentation/XCTest/XCUIKeyboardKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "XCUIKeyboardKey"
        }
      ],
      "role": "symbol",
      "title": "XCUIKeyboardKey",
      "type": "topic",
      "url": "/documentation/xctest/xcuikeyboardkey"
    },
    "doc://com.apple.xctest/documentation/XCTest/XCUIKeyboardKey/downArrow": {
      "abstract": [
        {
          "text": "A constant that represents the Down Arrow key.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "downArrow"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@XCUIKeyboardKey",
          "text": "XCUIKeyboardKey"
        }
      ],
      "identifier": "doc://com.apple.xctest/documentation/XCTest/XCUIKeyboardKey/downArrow",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "XCUIKeyboardKeyDownArrow"
        }
      ],
      "role": "symbol",
      "title": "downArrow",
      "type": "topic",
      "url": "/documentation/xctest/xcuikeyboardkey/downarrow"
    },
    "doc://com.apple.xctest/documentation/XCTest/XCUIKeyboardKey/end": {
      "abstract": [
        {
          "text": "A constant that represents the End key.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "end"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@XCUIKeyboardKey",
          "text": "XCUIKeyboardKey"
        }
      ],
      "identifier": "doc://com.apple.xctest/documentation/XCTest/XCUIKeyboardKey/end",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "XCUIKeyboardKeyEnd"
        }
      ],
      "role": "symbol",
      "title": "end",
      "type": "topic",
      "url": "/documentation/xctest/xcuikeyboardkey/end"
    },
    "doc://com.apple.xctest/documentation/XCTest/XCUIKeyboardKey/help": {
      "abstract": [
        {
          "text": "A constant that represents the Help key.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "help"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@XCUIKeyboardKey",
          "text": "XCUIKeyboardKey"
        }
      ],
      "identifier": "doc://com.apple.xctest/documentation/XCTest/XCUIKeyboardKey/help",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "XCUIKeyboardKeyHelp"
        }
      ],
      "role": "symbol",
      "title": "help",
      "type": "topic",
      "url": "/documentation/xctest/xcuikeyboardkey/help"
    },
    "doc://com.apple.xctest/documentation/XCTest/XCUIKeyboardKey/home": {
      "abstract": [
        {
          "text": "A constant that represents the Home key.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "home"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@XCUIKeyboardKey",
          "text": "XCUIKeyboardKey"
        }
      ],
      "identifier": "doc://com.apple.xctest/documentation/XCTest/XCUIKeyboardKey/home",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "XCUIKeyboardKeyHome"
        }
      ],
      "role": "symbol",
      "title": "home",
      "type": "topic",
      "url": "/documentation/xctest/xcuikeyboardkey/home"
    },
    "doc://com.apple.xctest/documentation/XCTest/XCUIKeyboardKey/leftArrow": {
      "abstract": [
        {
          "text": "A constant that represents the Left Arrow key.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "leftArrow"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@XCUIKeyboardKey",
          "text": "XCUIKeyboardKey"
        }
      ],
      "identifier": "doc://com.apple.xctest/documentation/XCTest/XCUIKeyboardKey/leftArrow",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "XCUIKeyboardKeyLeftArrow"
        }
      ],
      "role": "symbol",
      "title": "leftArrow",
      "type": "topic",
      "url": "/documentation/xctest/xcuikeyboardkey/leftarrow"
    },
    "doc://com.apple.xctest/documentation/XCTest/XCUIKeyboardKey/pageDown": {
      "abstract": [
        {
          "text": "A constant that represents the Page Down key.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "pageDown"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@XCUIKeyboardKey",
          "text": "XCUIKeyboardKey"
        }
      ],
      "identifier": "doc://com.apple.xctest/documentation/XCTest/XCUIKeyboardKey/pageDown",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "XCUIKeyboardKeyPageDown"
        }
      ],
      "role": "symbol",
      "title": "pageDown",
      "type": "topic",
      "url": "/documentation/xctest/xcuikeyboardkey/pagedown"
    },
    "doc://com.apple.xctest/documentation/XCTest/XCUIKeyboardKey/pageUp": {
      "abstract": [
        {
          "text": "A constant that represents the Page Up key.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "pageUp"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@XCUIKeyboardKey",
          "text": "XCUIKeyboardKey"
        }
      ],
      "identifier": "doc://com.apple.xctest/documentation/XCTest/XCUIKeyboardKey/pageUp",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "XCUIKeyboardKeyPageUp"
        }
      ],
      "role": "symbol",
      "title": "pageUp",
      "type": "topic",
      "url": "/documentation/xctest/xcuikeyboardkey/pageup"
    },
    "doc://com.apple.xctest/documentation/XCTest/XCUIKeyboardKey/rightArrow": {
      "abstract": [
        {
          "text": "A constant that represents the Right Arrow key.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "rightArrow"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@XCUIKeyboardKey",
          "text": "XCUIKeyboardKey"
        }
      ],
      "identifier": "doc://com.apple.xctest/documentation/XCTest/XCUIKeyboardKey/rightArrow",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "XCUIKeyboardKeyRightArrow"
        }
      ],
      "role": "symbol",
      "title": "rightArrow",
      "type": "topic",
      "url": "/documentation/xctest/xcuikeyboardkey/rightarrow"
    },
    "doc://com.apple.xctest/documentation/XCTest/XCUIKeyboardKey/upArrow": {
      "abstract": [
        {
          "text": "A constant that represents the Up Arrow key.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "upArrow"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@XCUIKeyboardKey",
          "text": "XCUIKeyboardKey"
        }
      ],
      "identifier": "doc://com.apple.xctest/documentation/XCTest/XCUIKeyboardKey/upArrow",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "XCUIKeyboardKeyUpArrow"
        }
      ],
      "role": "symbol",
      "title": "upArrow",
      "type": "topic",
      "url": "/documentation/xctest/xcuikeyboardkey/uparrow"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Navigation-Keys",
      "generated": true,
      "identifiers": [
        "doc://com.apple.xctest/documentation/XCTest/XCUIKeyboardKey/upArrow",
        "doc://com.apple.xctest/documentation/XCTest/XCUIKeyboardKey/downArrow",
        "doc://com.apple.xctest/documentation/XCTest/XCUIKeyboardKey/leftArrow",
        "doc://com.apple.xctest/documentation/XCTest/XCUIKeyboardKey/rightArrow",
        "doc://com.apple.xctest/documentation/XCTest/XCUIKeyboardKey/end",
        "doc://com.apple.xctest/documentation/XCTest/XCUIKeyboardKey/pageUp",
        "doc://com.apple.xctest/documentation/XCTest/XCUIKeyboardKey/pageDown",
        "doc://com.apple.xctest/documentation/XCTest/XCUIKeyboardKey/help"
      ],
      "title": "Navigation Keys"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "add",
          "path": "/metadata/platforms",
          "value": null
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Global Variable"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "XCUIKeyboardKeyHome"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "var"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "XCUIKeyboardKeyHome"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.xctest/documentation/XCTest"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Navigation-Keys",
              "generated": true,
              "identifiers": [
                "doc://com.apple.xctest/documentation/XCTest/XCUIKeyboardKey/upArrow",
                "doc://com.apple.xctest/documentation/XCTest/XCUIKeyboardKey/downArrow",
                "doc://com.apple.xctest/documentation/XCTest/XCUIKeyboardKey/leftArrow",
                "doc://com.apple.xctest/documentation/XCTest/XCUIKeyboardKey/rightArrow",
                "doc://com.apple.xctest/documentation/XCTest/XCUIKeyboardKey/end",
                "doc://com.apple.xctest/documentation/XCTest/XCUIKeyboardKey/pageUp",
                "doc://com.apple.xctest/documentation/XCTest/XCUIKeyboardKey/pageDown",
                "doc://com.apple.xctest/documentation/XCTest/XCUIKeyboardKey/help"
              ],
              "title": "Navigation Keys"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "extern"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "identifier": "doc://com.apple.xctest/documentation/XCTest/XCUIKeyboardKey",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@XCUIKeyboardKey",
                    "text": "XCUIKeyboardKey"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "keyword",
                    "text": "const"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "XCUIKeyboardKeyHome"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCUIKeyboardKey~1downArrow/title",
          "value": "XCUIKeyboardKeyDownArrow"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCUIKeyboardKey~1downArrow/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "XCUIKeyboardKeyDownArrow"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCUIKeyboardKey~1help/title",
          "value": "XCUIKeyboardKeyHelp"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCUIKeyboardKey~1help/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "XCUIKeyboardKeyHelp"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCUIKeyboardKey~1pageUp/title",
          "value": "XCUIKeyboardKeyPageUp"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCUIKeyboardKey~1pageUp/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "XCUIKeyboardKeyPageUp"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCUIKeyboardKey~1end/title",
          "value": "XCUIKeyboardKeyEnd"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCUIKeyboardKey~1end/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "XCUIKeyboardKeyEnd"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCUIKeyboardKey~1pageDown/title",
          "value": "XCUIKeyboardKeyPageDown"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCUIKeyboardKey~1pageDown/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "XCUIKeyboardKeyPageDown"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCUIKeyboardKey/title",
          "value": "XCUIKeyboardKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCUIKeyboardKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "XCUIKeyboardKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCUIKeyboardKey/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "XCUIKeyboardKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCUIKeyboardKey~1leftArrow/title",
          "value": "XCUIKeyboardKeyLeftArrow"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCUIKeyboardKey~1leftArrow/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "XCUIKeyboardKeyLeftArrow"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCUIKeyboardKey~1rightArrow/title",
          "value": "XCUIKeyboardKeyRightArrow"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCUIKeyboardKey~1rightArrow/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "XCUIKeyboardKeyRightArrow"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCUIKeyboardKey~1home/title",
          "value": "XCUIKeyboardKeyHome"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCUIKeyboardKey~1home/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "XCUIKeyboardKeyHome"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCUIKeyboardKey~1upArrow/title",
          "value": "XCUIKeyboardKeyUpArrow"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCUIKeyboardKey~1upArrow/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "XCUIKeyboardKeyUpArrow"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/xctest/xcuikeyboardkey/home"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/xctest/xcuikeyboardkey/home"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
