{
  "abstract": [
    {
      "text": "A constant that represents the Tab key.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.xctest/documentation/XCTest",
        "doc://com.apple.xctest/documentation/XCTest/XCUIKeyboardKey"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.xctest/documentation/XCTest/XCUIKeyboardKey/tab"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "extendedModule": "XCTest",
    "externalID": "c:@XCUIKeyboardKeyTab",
    "fragments": [
      {
        "kind": "keyword",
        "text": "static"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "keyword",
        "text": "let"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "tab"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@T@XCUIKeyboardKey",
        "text": "XCUIKeyboardKey"
      }
    ],
    "modules": [
      {
        "name": "XCTest"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "XCUIKeyboardKeyTab"
      }
    ],
    "role": "symbol",
    "roleHeading": "Type Property",
    "symbolKind": "property",
    "title": "tab"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "static"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "keyword",
              "text": "let"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "tab"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.xctest/documentation/XCTest/XCUIKeyboardKey",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@XCUIKeyboardKey",
              "text": "XCUIKeyboardKey"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.xctest/documentation/XCTest": {
      "abstract": [
        {
          "text": "Create and run unit tests, performance tests, and UI tests for your Xcode project.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.xctest/documentation/XCTest",
      "kind": "symbol",
      "role": "collection",
      "title": "XCTest",
      "type": "topic",
      "url": "/documentation/xctest"
    },
    "doc://com.apple.xctest/documentation/XCTest/XCUIKeyboardKey": {
      "abstract": [
        {
          "text": "Constants to represent keys that have no typewritten equivalent.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "XCUIKeyboardKey"
        }
      ],
      "identifier": "doc://com.apple.xctest/documentation/XCTest/XCUIKeyboardKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "XCUIKeyboardKey"
        }
      ],
      "role": "symbol",
      "title": "XCUIKeyboardKey",
      "type": "topic",
      "url": "/documentation/xctest/xcuikeyboardkey"
    },
    "doc://com.apple.xctest/documentation/XCTest/XCUIKeyboardKey/capsLock": {
      "abstract": [
        {
          "text": "A constant that represents the Caps Lock key.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "capsLock"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@XCUIKeyboardKey",
          "text": "XCUIKeyboardKey"
        }
      ],
      "identifier": "doc://com.apple.xctest/documentation/XCTest/XCUIKeyboardKey/capsLock",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "XCUIKeyboardKeyCapsLock"
        }
      ],
      "role": "symbol",
      "title": "capsLock",
      "type": "topic",
      "url": "/documentation/xctest/xcuikeyboardkey/capslock"
    },
    "doc://com.apple.xctest/documentation/XCTest/XCUIKeyboardKey/delete": {
      "abstract": [
        {
          "text": "A constant that represents the Delete key.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "delete"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@XCUIKeyboardKey",
          "text": "XCUIKeyboardKey"
        }
      ],
      "identifier": "doc://com.apple.xctest/documentation/XCTest/XCUIKeyboardKey/delete",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "XCUIKeyboardKeyDelete"
        }
      ],
      "role": "symbol",
      "title": "delete",
      "type": "topic",
      "url": "/documentation/xctest/xcuikeyboardkey/delete"
    },
    "doc://com.apple.xctest/documentation/XCTest/XCUIKeyboardKey/forwardDelete": {
      "abstract": [
        {
          "text": "A constant that represents the Forward Delete key.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "forwardDelete"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@XCUIKeyboardKey",
          "text": "XCUIKeyboardKey"
        }
      ],
      "identifier": "doc://com.apple.xctest/documentation/XCTest/XCUIKeyboardKey/forwardDelete",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "XCUIKeyboardKeyForwardDelete"
        }
      ],
      "role": "symbol",
      "title": "forwardDelete",
      "type": "topic",
      "url": "/documentation/xctest/xcuikeyboardkey/forwarddelete"
    },
    "doc://com.apple.xctest/documentation/XCTest/XCUIKeyboardKey/space": {
      "abstract": [
        {
          "text": "A constant that represents the Space bar.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "space"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@XCUIKeyboardKey",
          "text": "XCUIKeyboardKey"
        }
      ],
      "identifier": "doc://com.apple.xctest/documentation/XCTest/XCUIKeyboardKey/space",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "XCUIKeyboardKeySpace"
        }
      ],
      "role": "symbol",
      "title": "space",
      "type": "topic",
      "url": "/documentation/xctest/xcuikeyboardkey/space"
    },
    "doc://com.apple.xctest/documentation/XCTest/XCUIKeyboardKey/tab": {
      "abstract": [
        {
          "text": "A constant that represents the Tab key.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "tab"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@XCUIKeyboardKey",
          "text": "XCUIKeyboardKey"
        }
      ],
      "identifier": "doc://com.apple.xctest/documentation/XCTest/XCUIKeyboardKey/tab",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "XCUIKeyboardKeyTab"
        }
      ],
      "role": "symbol",
      "title": "tab",
      "type": "topic",
      "url": "/documentation/xctest/xcuikeyboardkey/tab"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Text-Editing-Keys",
      "generated": true,
      "identifiers": [
        "doc://com.apple.xctest/documentation/XCTest/XCUIKeyboardKey/capsLock",
        "doc://com.apple.xctest/documentation/XCTest/XCUIKeyboardKey/delete",
        "doc://com.apple.xctest/documentation/XCTest/XCUIKeyboardKey/forwardDelete",
        "doc://com.apple.xctest/documentation/XCTest/XCUIKeyboardKey/space"
      ],
      "title": "Text-Editing Keys"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "add",
          "path": "/metadata/platforms",
          "value": null
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Global Variable"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "XCUIKeyboardKeyTab"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "var"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "XCUIKeyboardKeyTab"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.xctest/documentation/XCTest"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Text-Editing-Keys",
              "generated": true,
              "identifiers": [
                "doc://com.apple.xctest/documentation/XCTest/XCUIKeyboardKey/capsLock",
                "doc://com.apple.xctest/documentation/XCTest/XCUIKeyboardKey/delete",
                "doc://com.apple.xctest/documentation/XCTest/XCUIKeyboardKey/forwardDelete",
                "doc://com.apple.xctest/documentation/XCTest/XCUIKeyboardKey/space"
              ],
              "title": "Text-Editing Keys"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "extern"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "identifier": "doc://com.apple.xctest/documentation/XCTest/XCUIKeyboardKey",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@XCUIKeyboardKey",
                    "text": "XCUIKeyboardKey"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "keyword",
                    "text": "const"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "XCUIKeyboardKeyTab"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCUIKeyboardKey~1space/title",
          "value": "XCUIKeyboardKeySpace"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCUIKeyboardKey~1space/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "XCUIKeyboardKeySpace"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCUIKeyboardKey~1delete/title",
          "value": "XCUIKeyboardKeyDelete"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCUIKeyboardKey~1delete/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "XCUIKeyboardKeyDelete"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCUIKeyboardKey~1capsLock/title",
          "value": "XCUIKeyboardKeyCapsLock"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCUIKeyboardKey~1capsLock/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "XCUIKeyboardKeyCapsLock"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCUIKeyboardKey~1tab/title",
          "value": "XCUIKeyboardKeyTab"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCUIKeyboardKey~1tab/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "XCUIKeyboardKeyTab"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCUIKeyboardKey/title",
          "value": "XCUIKeyboardKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCUIKeyboardKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "XCUIKeyboardKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCUIKeyboardKey/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "XCUIKeyboardKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCUIKeyboardKey~1forwardDelete/title",
          "value": "XCUIKeyboardKeyForwardDelete"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCUIKeyboardKey~1forwardDelete/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "XCUIKeyboardKeyForwardDelete"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/xctest/xcuikeyboardkey/tab"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/xctest/xcuikeyboardkey/tab"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
