{
  "abstract": [
    {
      "text": "If recording, specifies that you want to use low-quality video recording.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.uikit/documentation/UIKit",
        "doc://com.apple.uikit/documentation/UIKit/UIImagePickerController",
        "doc://com.apple.uikit/documentation/UIKit/UIImagePickerController/QualityType"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.uikit/documentation/UIKit/UIImagePickerController/QualityType/typeLow"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@UIImagePickerControllerQualityType@UIImagePickerControllerQualityTypeLow",
    "fragments": [
      {
        "kind": "keyword",
        "text": "case"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "typeLow"
      }
    ],
    "modules": [
      {
        "name": "UIKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "UIImagePickerControllerQualityTypeLow"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "Mac Catalyst",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Case",
    "symbolKind": "case",
    "title": "UIImagePickerController.QualityType.typeLow"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "case"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "typeLow"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Recorded files can usually be transferred over the cellular network.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "If displaying a recorded movie in the image picker, specifies that you want to transcode higher-quality movies to low video quality.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.uikit/documentation/UIKit": {
      "abstract": [
        {
          "text": "Construct and manage a graphical, event-driven user interface for your iOS, iPadOS, or tvOS app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit",
      "kind": "symbol",
      "role": "collection",
      "title": "UIKit",
      "type": "topic",
      "url": "/documentation/uikit"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIImagePickerController": {
      "abstract": [
        {
          "text": "A view controller that manages the system interfaces for taking pictures, recording movies, and choosing items from the user’s media library.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UIImagePickerController"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIImagePickerController",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIImagePickerController"
        }
      ],
      "role": "symbol",
      "title": "UIImagePickerController",
      "type": "topic",
      "url": "/documentation/uikit/uiimagepickercontroller"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIImagePickerController/QualityType": {
      "abstract": [
        {
          "text": "Constants that describe video quality settings for movies that are recorded with the built-in camera, or that are transcoded when they’re displayed in the image picker.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "QualityType"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIImagePickerController/QualityType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "QualityType"
        }
      ],
      "role": "symbol",
      "title": "UIImagePickerController.QualityType",
      "type": "topic",
      "url": "/documentation/uikit/uiimagepickercontroller/qualitytype"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIImagePickerController/QualityType/type640x480": {
      "abstract": [
        {
          "text": "If recording, specifies that you want to use VGA-quality video recording (pixel dimensions of 640x480).",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "type640x480"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIImagePickerController/QualityType/type640x480",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIImagePickerControllerQualityType640x480"
        }
      ],
      "role": "symbol",
      "title": "UIImagePickerController.QualityType.type640x480",
      "type": "topic",
      "url": "/documentation/uikit/uiimagepickercontroller/qualitytype/type640x480"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIImagePickerController/QualityType/typeHigh": {
      "abstract": [
        {
          "text": "If recording, specifies that you want to use the highest-quality video recording supported for the active camera on the device.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "typeHigh"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIImagePickerController/QualityType/typeHigh",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIImagePickerControllerQualityTypeHigh"
        }
      ],
      "role": "symbol",
      "title": "UIImagePickerController.QualityType.typeHigh",
      "type": "topic",
      "url": "/documentation/uikit/uiimagepickercontroller/qualitytype/typehigh"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIImagePickerController/QualityType/typeIFrame1280x720": {
      "abstract": [
        {
          "text": "If recording, specifies that you want to use 1280x720 iFrame format.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "typeIFrame1280x720"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIImagePickerController/QualityType/typeIFrame1280x720",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIImagePickerControllerQualityTypeIFrame1280x720"
        }
      ],
      "role": "symbol",
      "title": "UIImagePickerController.QualityType.typeIFrame1280x720",
      "type": "topic",
      "url": "/documentation/uikit/uiimagepickercontroller/qualitytype/typeiframe1280x720"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIImagePickerController/QualityType/typeIFrame960x540": {
      "abstract": [
        {
          "text": "If recording, specifies that you want to use 960x540 iFrame format.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "typeIFrame960x540"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIImagePickerController/QualityType/typeIFrame960x540",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIImagePickerControllerQualityTypeIFrame960x540"
        }
      ],
      "role": "symbol",
      "title": "UIImagePickerController.QualityType.typeIFrame960x540",
      "type": "topic",
      "url": "/documentation/uikit/uiimagepickercontroller/qualitytype/typeiframe960x540"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIImagePickerController/QualityType/typeLow": {
      "abstract": [
        {
          "text": "If recording, specifies that you want to use low-quality video recording.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "typeLow"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIImagePickerController/QualityType/typeLow",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIImagePickerControllerQualityTypeLow"
        }
      ],
      "role": "symbol",
      "title": "UIImagePickerController.QualityType.typeLow",
      "type": "topic",
      "url": "/documentation/uikit/uiimagepickercontroller/qualitytype/typelow"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIImagePickerController/QualityType/typeMedium": {
      "abstract": [
        {
          "text": "If recording, specifies that you want to use medium-quality video recording.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "typeMedium"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIImagePickerController/QualityType/typeMedium",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIImagePickerControllerQualityTypeMedium"
        }
      ],
      "role": "symbol",
      "title": "UIImagePickerController.QualityType.typeMedium",
      "type": "topic",
      "url": "/documentation/uikit/uiimagepickercontroller/qualitytype/typemedium"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Constants",
      "generated": true,
      "identifiers": [
        "doc://com.apple.uikit/documentation/UIKit/UIImagePickerController/QualityType/typeHigh",
        "doc://com.apple.uikit/documentation/UIKit/UIImagePickerController/QualityType/type640x480",
        "doc://com.apple.uikit/documentation/UIKit/UIImagePickerController/QualityType/typeMedium",
        "doc://com.apple.uikit/documentation/UIKit/UIImagePickerController/QualityType/typeIFrame1280x720",
        "doc://com.apple.uikit/documentation/UIKit/UIImagePickerController/QualityType/typeIFrame960x540"
      ],
      "title": "Constants"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "Mac Catalyst",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration Case"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "UIImagePickerControllerQualityTypeLow"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "case"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIImagePickerControllerQualityTypeLow"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.uikit/documentation/UIKit",
                "doc://com.apple.uikit/documentation/UIKit/UIImagePickerController/QualityType"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Constants",
              "generated": true,
              "identifiers": [
                "doc://com.apple.uikit/documentation/UIKit/UIImagePickerController/QualityType/typeHigh",
                "doc://com.apple.uikit/documentation/UIKit/UIImagePickerController/QualityType/type640x480",
                "doc://com.apple.uikit/documentation/UIKit/UIImagePickerController/QualityType/typeMedium",
                "doc://com.apple.uikit/documentation/UIKit/UIImagePickerController/QualityType/typeIFrame1280x720",
                "doc://com.apple.uikit/documentation/UIKit/UIImagePickerController/QualityType/typeIFrame960x540"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "tvOS",
                  "visionOS"
                ],
                "tokens": [
                  {
                    "kind": "identifier",
                    "text": "UIImagePickerControllerQualityTypeLow"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIImagePickerController/title",
          "value": "UIImagePickerController"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIImagePickerController/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIImagePickerController"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIImagePickerController/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UIImagePickerController"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIImagePickerController~1QualityType~1typeLow/title",
          "value": "UIImagePickerControllerQualityTypeLow"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIImagePickerController~1QualityType~1typeLow/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIImagePickerControllerQualityTypeLow"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIImagePickerController~1QualityType~1typeMedium/title",
          "value": "UIImagePickerControllerQualityTypeMedium"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIImagePickerController~1QualityType~1typeMedium/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIImagePickerControllerQualityTypeMedium"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIImagePickerController~1QualityType~1typeHigh/title",
          "value": "UIImagePickerControllerQualityTypeHigh"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIImagePickerController~1QualityType~1typeHigh/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIImagePickerControllerQualityTypeHigh"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIImagePickerController~1QualityType~1typeIFrame1280x720/title",
          "value": "UIImagePickerControllerQualityTypeIFrame1280x720"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIImagePickerController~1QualityType~1typeIFrame1280x720/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIImagePickerControllerQualityTypeIFrame1280x720"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIImagePickerController~1QualityType/title",
          "value": "UIImagePickerControllerQualityType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIImagePickerController~1QualityType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIImagePickerControllerQualityType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIImagePickerController~1QualityType/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UIImagePickerControllerQualityType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIImagePickerController~1QualityType~1type640x480/title",
          "value": "UIImagePickerControllerQualityType640x480"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIImagePickerController~1QualityType~1type640x480/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIImagePickerControllerQualityType640x480"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIImagePickerController~1QualityType~1typeIFrame960x540/title",
          "value": "UIImagePickerControllerQualityTypeIFrame960x540"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIImagePickerController~1QualityType~1typeIFrame960x540/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIImagePickerControllerQualityTypeIFrame960x540"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/uikit/uiimagepickercontroller/qualitytype/typelow"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/uikit/uiimagepickercontroller/qualitytype/typelow"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
