{"kind":"symbol","identifier":{"interfaceLanguage":"swift","url":"doc://com.apple.authenticationservices/documentation/AuthenticationServices/ASAuthorizationWebBrowserPlatformPublicKeyCredentialRegistrationRequest/clientData-5dk66"},"sections":[],"abstract":[{"text":"The client data to supply to the relying party.","type":"text"}],"variants":[{"paths":["/documentation/authenticationservices/asauthorizationwebbrowserplatformpublickeycredentialregistrationrequest/clientdata-5dk66"],"traits":[{"interfaceLanguage":"swift"}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"clientData"},{"kind":"text","text":": "},{"preciseIdentifier":"s:22AuthenticationServices31ASPublicKeyCredentialClientDataV","kind":"typeIdentifier","text":"ASPublicKeyCredentialClientData","identifier":"doc://com.apple.authenticationservices/documentation/AuthenticationServices/ASPublicKeyCredentialClientData-swift.struct"},{"kind":"text","text":"? { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" }"}],"platforms":["Mac Catalyst","macOS"],"languages":["swift"]}]}],"seeAlsoSections":[{"identifiers":["doc://com.apple.authenticationservices/documentation/AuthenticationServices/ASAuthorizationWebBrowserPlatformPublicKeyCredentialRegistrationRequest/excludedCredentials","doc://com.apple.authenticationservices/documentation/AuthenticationServices/ASAuthorizationWebBrowserPlatformPublicKeyCredentialRegistrationRequest/shouldShowHybridTransport"],"generated":true,"anchor":"Information-about-the-assertion","title":"Information about the assertion"}],"metadata":{"externalID":"s:So71ASAuthorizationWebBrowserPlatformPublicKeyCredentialRegistrationRequestP22AuthenticationServicesE10clientDataAC08ASPublicfg6ClientM0VSgvp","modules":[{"name":"Authentication Services"}],"platforms":[{"beta":false,"name":"Mac Catalyst","introducedAt":"16.6","deprecated":false,"unavailable":false},{"beta":false,"deprecated":false,"name":"macOS","introducedAt":"13.5","unavailable":false}],"role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"clientData"},{"kind":"text","text":": "},{"preciseIdentifier":"s:22AuthenticationServices31ASPublicKeyCredentialClientDataV","kind":"typeIdentifier","text":"ASPublicKeyCredentialClientData"},{"kind":"text","text":"?"}],"roleHeading":"Instance Property","extendedModule":"AuthenticationServices","symbolKind":"property","title":"clientData"},"hierarchy":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.authenticationservices/documentation/AuthenticationServices","doc://com.apple.authenticationservices/documentation/AuthenticationServices/ASAuthorizationWebBrowserPlatformPublicKeyCredentialRegistrationRequest"]]},"references":{"doc://com.apple.documentation/documentation/technologies":{"url":"/documentation/technologies","role":"overview","kind":"technologies","type":"topic","title":"Technologies","abstract":[{"text":"","type":"text"}],"identifier":"doc://com.apple.documentation/documentation/technologies"},"doc://com.apple.authenticationservices/documentation/AuthenticationServices/ASAuthorizationWebBrowserPlatformPublicKeyCredentialRegistrationRequest/clientData-5dk66":{"kind":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"clientData"},{"kind":"text","text":": "},{"preciseIdentifier":"s:22AuthenticationServices31ASPublicKeyCredentialClientDataV","kind":"typeIdentifier","text":"ASPublicKeyCredentialClientData"},{"kind":"text","text":"?"}],"abstract":[{"text":"The client data to supply to the relying party.","type":"text"}],"type":"topic","role":"symbol","title":"clientData","url":"/documentation/authenticationservices/asauthorizationwebbrowserplatformpublickeycredentialregistrationrequest/clientdata-5dk66","identifier":"doc://com.apple.authenticationservices/documentation/AuthenticationServices/ASAuthorizationWebBrowserPlatformPublicKeyCredentialRegistrationRequest/clientData-5dk66"},"doc://com.apple.authenticationservices/documentation/AuthenticationServices/ASAuthorizationWebBrowserPlatformPublicKeyCredentialRegistrationRequest":{"navigatorTitle":[{"kind":"identifier","text":"ASAuthorizationWebBrowserPlatformPublicKeyCredentialRegistrationRequest"}],"title":"ASAuthorizationWebBrowserPlatformPublicKeyCredentialRegistrationRequest","type":"topic","identifier":"doc://com.apple.authenticationservices/documentation/AuthenticationServices/ASAuthorizationWebBrowserPlatformPublicKeyCredentialRegistrationRequest","kind":"symbol","abstract":[{"type":"text","text":"An interface you use to respond to passkey-creation challenges in a web browser."}],"url":"/documentation/authenticationservices/asauthorizationwebbrowserplatformpublickeycredentialregistrationrequest","role":"symbol","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"ASAuthorizationWebBrowserPlatformPublicKeyCredentialRegistrationRequest"}]},"doc://com.apple.authenticationservices/documentation/AuthenticationServices/ASAuthorizationWebBrowserPlatformPublicKeyCredentialRegistrationRequest/excludedCredentials":{"url":"/documentation/authenticationservices/asauthorizationwebbrowserplatformpublickeycredentialregistrationrequest/excludedcredentials","navigatorTitle":[{"kind":"identifier","text":"excludedCredentials"}],"title":"excludedCredentials","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"excludedCredentials"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"ASAuthorizationPlatformPublicKeyCredentialDescriptor","preciseIdentifier":"c:objc(cs)ASAuthorizationPlatformPublicKeyCredentialDescriptor"},{"kind":"text","text":"]?"}],"required":true,"role":"symbol","kind":"symbol","identifier":"doc://com.apple.authenticationservices/documentation/AuthenticationServices/ASAuthorizationWebBrowserPlatformPublicKeyCredentialRegistrationRequest/excludedCredentials","type":"topic","abstract":[{"type":"text","text":"A list of passkeys that the relying party doesn’t accept for resolving the challenge."}]},"doc://com.apple.authenticationservices/documentation/AuthenticationServices":{"identifier":"doc://com.apple.authenticationservices/documentation/AuthenticationServices","abstract":[{"text":"Make it easy for users to log into apps and services.","type":"text"}],"role":"collection","type":"topic","title":"Authentication Services","url":"/documentation/authenticationservices","kind":"symbol"},"doc://com.apple.authenticationservices/documentation/AuthenticationServices/ASPublicKeyCredentialClientData-swift.struct":{"kind":"symbol","abstract":[],"fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ASPublicKeyCredentialClientData","kind":"identifier"}],"title":"ASPublicKeyCredentialClientData","role":"symbol","navigatorTitle":[{"text":"ASPublicKeyCredentialClientData","kind":"identifier"}],"type":"topic","identifier":"doc://com.apple.authenticationservices/documentation/AuthenticationServices/ASPublicKeyCredentialClientData-swift.struct","url":"/documentation/authenticationservices/aspublickeycredentialclientdata-swift.struct"},"doc://com.apple.authenticationservices/documentation/AuthenticationServices/ASAuthorizationWebBrowserPlatformPublicKeyCredentialRegistrationRequest/shouldShowHybridTransport":{"url":"/documentation/authenticationservices/asauthorizationwebbrowserplatformpublickeycredentialregistrationrequest/shouldshowhybridtransport","navigatorTitle":[{"kind":"identifier","text":"shouldShowHybridTransport"}],"title":"shouldShowHybridTransport","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"shouldShowHybridTransport"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sb","kind":"typeIdentifier","text":"Bool"}],"required":true,"role":"symbol","kind":"symbol","identifier":"doc://com.apple.authenticationservices/documentation/AuthenticationServices/ASAuthorizationWebBrowserPlatformPublicKeyCredentialRegistrationRequest/shouldShowHybridTransport","type":"topic","abstract":[{"type":"text","text":"Whether a remote authenticator that communicates with the operating system using Bluetooth can resolve the challenge."}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"/references/doc:~1~1com.apple.authenticationservices~1documentation~1AuthenticationServices~1ASAuthorizationWebBrowserPlatformPublicKeyCredentialRegistrationRequest/title","value":"ASAuthorizationWebBrowserPlatformPublicKeyCredentialRegistrationRequest","op":"replace"},{"value":[{"text":"ASAuthorizationWebBrowserPlatformPublicKeyCredentialRegistrationRequest","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.authenticationservices~1documentation~1AuthenticationServices~1ASAuthorizationWebBrowserPlatformPublicKeyCredentialRegistrationRequest/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"ASAuthorizationWebBrowserPlatformPublicKeyCredentialRegistrationRequest"}],"path":"/references/doc:~1~1com.apple.authenticationservices~1documentation~1AuthenticationServices~1ASAuthorizationWebBrowserPlatformPublicKeyCredentialRegistrationRequest/navigatorTitle","op":"replace"},{"value":"excludedCredentials","path":"/references/doc:~1~1com.apple.authenticationservices~1documentation~1AuthenticationServices~1ASAuthorizationWebBrowserPlatformPublicKeyCredentialRegistrationRequest~1excludedCredentials/title","op":"replace"},{"value":[{"text":"excludedCredentials","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.authenticationservices~1documentation~1AuthenticationServices~1ASAuthorizationWebBrowserPlatformPublicKeyCredentialRegistrationRequest~1excludedCredentials/fragments","op":"replace"},{"path":"/references/doc:~1~1com.apple.authenticationservices~1documentation~1AuthenticationServices~1ASAuthorizationWebBrowserPlatformPublicKeyCredentialRegistrationRequest~1shouldShowHybridTransport/title","value":"shouldShowHybridTransport","op":"replace"},{"path":"/references/doc:~1~1com.apple.authenticationservices~1documentation~1AuthenticationServices~1ASAuthorizationWebBrowserPlatformPublicKeyCredentialRegistrationRequest~1shouldShowHybridTransport/fragments","value":[{"text":"shouldShowHybridTransport","kind":"identifier"}],"op":"replace"}]}],"legalNotices":{"copyright":"Copyright &copy; 2025 Apple Inc. All rights reserved.","termsOfUse":"https://www.apple.com/legal/internet-services/terms/site.html","privacyPolicy":"https://www.apple.com/privacy/privacy-policy"}}