{
  "abstract": [
    {
      "text": "An error indicating that the File Provider manager can’t find the specified provider.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.fileprovider/documentation/FileProvider",
        "doc://com.apple.fileprovider/documentation/FileProvider/NSFileProviderError",
        "doc://com.apple.fileprovider/documentation/FileProvider/NSFileProviderError/Code"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.fileprovider/documentation/FileProvider/NSFileProviderError/Code/providerNotFound"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@NSFileProviderErrorCode@NSFileProviderErrorProviderNotFound",
    "fragments": [
      {
        "kind": "keyword",
        "text": "case"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "providerNotFound"
      }
    ],
    "modules": [
      {
        "name": "File Provider"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "NSFileProviderErrorProviderNotFound"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "16.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "16.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "11.0",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Case",
    "symbolKind": "case",
    "title": "NSFileProviderError.Code.providerNotFound"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "macOS",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "case"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "providerNotFound"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "If this error occurs during development, make sure the app includes a file provider extension. In a deployed app this error indicates that the system hasn’t registered the specified provider yet. Wait for a ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.fileprovider/documentation/FileProvider/NSFileProviderDomainDidChange",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " notification and try again.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.fileprovider/documentation/FileProvider": {
      "abstract": [
        {
          "text": "An extension other apps use to access files and folders managed by your app and synced with a remote storage.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.fileprovider/documentation/FileProvider",
      "kind": "symbol",
      "role": "collection",
      "title": "File Provider",
      "type": "topic",
      "url": "/documentation/fileprovider"
    },
    "doc://com.apple.fileprovider/documentation/FileProvider/NSFileProviderDomainDidChange": {
      "abstract": [
        {
          "text": "A notification that posts when a file provider’s domain changes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "NSFileProviderDomainDidChange"
        }
      ],
      "identifier": "doc://com.apple.fileprovider/documentation/FileProvider/NSFileProviderDomainDidChange",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSFileProviderDomainDidChange",
      "type": "topic",
      "url": "/documentation/fileprovider/nsfileproviderdomaindidchange"
    },
    "doc://com.apple.fileprovider/documentation/FileProvider/NSFileProviderError": {
      "abstract": [
        {
          "text": "A structure that contains information about File Provider extension errors.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSFileProviderError"
        }
      ],
      "identifier": "doc://com.apple.fileprovider/documentation/FileProvider/NSFileProviderError",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSFileProviderError"
        }
      ],
      "role": "symbol",
      "title": "NSFileProviderError",
      "type": "topic",
      "url": "/documentation/fileprovider/nsfileprovidererror"
    },
    "doc://com.apple.fileprovider/documentation/FileProvider/NSFileProviderError/Code": {
      "abstract": [
        {
          "text": "The error codes for the File Provider extension.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.fileprovider/documentation/FileProvider/NSFileProviderError/Code",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "Code"
        }
      ],
      "role": "symbol",
      "title": "NSFileProviderError.Code",
      "type": "topic",
      "url": "/documentation/fileprovider/nsfileprovidererror/code"
    },
    "doc://com.apple.fileprovider/documentation/FileProvider/NSFileProviderError/Code/cannotSynchronize": {
      "abstract": [
        {
          "text": "An error indicating a failed sync attempt.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "cannotSynchronize"
        }
      ],
      "identifier": "doc://com.apple.fileprovider/documentation/FileProvider/NSFileProviderError/Code/cannotSynchronize",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSFileProviderErrorCannotSynchronize"
        }
      ],
      "role": "symbol",
      "title": "NSFileProviderError.Code.cannotSynchronize",
      "type": "topic",
      "url": "/documentation/fileprovider/nsfileprovidererror/code/cannotsynchronize"
    },
    "doc://com.apple.fileprovider/documentation/FileProvider/NSFileProviderError/Code/deletionRejected": {
      "abstract": [
        {
          "text": "An error indicating a failed deletion action.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "deletionRejected"
        }
      ],
      "identifier": "doc://com.apple.fileprovider/documentation/FileProvider/NSFileProviderError/Code/deletionRejected",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSFileProviderErrorDeletionRejected"
        }
      ],
      "role": "symbol",
      "title": "NSFileProviderError.Code.deletionRejected",
      "type": "topic",
      "url": "/documentation/fileprovider/nsfileprovidererror/code/deletionrejected"
    },
    "doc://com.apple.fileprovider/documentation/FileProvider/NSFileProviderError/Code/directoryNotEmpty": {
      "abstract": [
        {
          "text": "An error indicating an attempt to nonrecursively delete a directory that isn’t empty.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "directoryNotEmpty"
        }
      ],
      "identifier": "doc://com.apple.fileprovider/documentation/FileProvider/NSFileProviderError/Code/directoryNotEmpty",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSFileProviderErrorDirectoryNotEmpty"
        }
      ],
      "role": "symbol",
      "title": "NSFileProviderError.Code.directoryNotEmpty",
      "type": "topic",
      "url": "/documentation/fileprovider/nsfileprovidererror/code/directorynotempty"
    },
    "doc://com.apple.fileprovider/documentation/FileProvider/NSFileProviderError/Code/filenameCollision": {
      "abstract": [
        {
          "text": "An error indicating that an item with the same name already exists in the same directory.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "filenameCollision"
        }
      ],
      "identifier": "doc://com.apple.fileprovider/documentation/FileProvider/NSFileProviderError/Code/filenameCollision",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSFileProviderErrorFilenameCollision"
        }
      ],
      "role": "symbol",
      "title": "NSFileProviderError.Code.filenameCollision",
      "type": "topic",
      "url": "/documentation/fileprovider/nsfileprovidererror/code/filenamecollision"
    },
    "doc://com.apple.fileprovider/documentation/FileProvider/NSFileProviderError/Code/insufficientQuota": {
      "abstract": [
        {
          "text": "An error indicating that the File Provider extension can’t upload the item because it would push the account over its quota.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "insufficientQuota"
        }
      ],
      "identifier": "doc://com.apple.fileprovider/documentation/FileProvider/NSFileProviderError/Code/insufficientQuota",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSFileProviderErrorInsufficientQuota"
        }
      ],
      "role": "symbol",
      "title": "NSFileProviderError.Code.insufficientQuota",
      "type": "topic",
      "url": "/documentation/fileprovider/nsfileprovidererror/code/insufficientquota"
    },
    "doc://com.apple.fileprovider/documentation/FileProvider/NSFileProviderError/Code/newerExtensionVersionFound": {
      "abstract": [
        {
          "text": "An error indicating that the registered provider in the system is a newer version than the one the app uses.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "newerExtensionVersionFound"
        }
      ],
      "identifier": "doc://com.apple.fileprovider/documentation/FileProvider/NSFileProviderError/Code/newerExtensionVersionFound",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSFileProviderErrorNewerExtensionVersionFound"
        }
      ],
      "role": "symbol",
      "title": "NSFileProviderError.Code.newerExtensionVersionFound",
      "type": "topic",
      "url": "/documentation/fileprovider/nsfileprovidererror/code/newerextensionversionfound"
    },
    "doc://com.apple.fileprovider/documentation/FileProvider/NSFileProviderError/Code/noSuchItem": {
      "abstract": [
        {
          "text": "An error indicating that the specified item doesn’t exist.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "noSuchItem"
        }
      ],
      "identifier": "doc://com.apple.fileprovider/documentation/FileProvider/NSFileProviderError/Code/noSuchItem",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSFileProviderErrorNoSuchItem"
        }
      ],
      "role": "symbol",
      "title": "NSFileProviderError.Code.noSuchItem",
      "type": "topic",
      "url": "/documentation/fileprovider/nsfileprovidererror/code/nosuchitem"
    },
    "doc://com.apple.fileprovider/documentation/FileProvider/NSFileProviderError/Code/nonEvictable": {
      "abstract": [
        {
          "text": "An error indicating that the File Provider extension can’t evict an item.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "nonEvictable"
        }
      ],
      "identifier": "doc://com.apple.fileprovider/documentation/FileProvider/NSFileProviderError/Code/nonEvictable",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSFileProviderErrorNonEvictable"
        }
      ],
      "role": "symbol",
      "title": "NSFileProviderError.Code.nonEvictable",
      "type": "topic",
      "url": "/documentation/fileprovider/nsfileprovidererror/code/nonevictable"
    },
    "doc://com.apple.fileprovider/documentation/FileProvider/NSFileProviderError/Code/nonEvictableChildren": {
      "abstract": [
        {
          "text": "An error indicating that the File Provider extension can’t evict a directory because it contains nonevictable items.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "nonEvictableChildren"
        }
      ],
      "identifier": "doc://com.apple.fileprovider/documentation/FileProvider/NSFileProviderError/Code/nonEvictableChildren",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSFileProviderErrorNonEvictableChildren"
        }
      ],
      "role": "symbol",
      "title": "NSFileProviderError.Code.nonEvictableChildren",
      "type": "topic",
      "url": "/documentation/fileprovider/nsfileprovidererror/code/nonevictablechildren"
    },
    "doc://com.apple.fileprovider/documentation/FileProvider/NSFileProviderError/Code/notAuthenticated": {
      "abstract": [
        {
          "text": "An error indicating that you can’t verify the user’s credentials.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "notAuthenticated"
        }
      ],
      "identifier": "doc://com.apple.fileprovider/documentation/FileProvider/NSFileProviderError/Code/notAuthenticated",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSFileProviderErrorNotAuthenticated"
        }
      ],
      "role": "symbol",
      "title": "NSFileProviderError.Code.notAuthenticated",
      "type": "topic",
      "url": "/documentation/fileprovider/nsfileprovidererror/code/notauthenticated"
    },
    "doc://com.apple.fileprovider/documentation/FileProvider/NSFileProviderError/Code/olderExtensionVersionRunning": {
      "abstract": [
        {
          "text": "An error indicating that the registered provider in the system is an older version than the one the app uses.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "olderExtensionVersionRunning"
        }
      ],
      "identifier": "doc://com.apple.fileprovider/documentation/FileProvider/NSFileProviderError/Code/olderExtensionVersionRunning",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSFileProviderErrorOlderExtensionVersionRunning"
        }
      ],
      "role": "symbol",
      "title": "NSFileProviderError.Code.olderExtensionVersionRunning",
      "type": "topic",
      "url": "/documentation/fileprovider/nsfileprovidererror/code/olderextensionversionrunning"
    },
    "doc://com.apple.fileprovider/documentation/FileProvider/NSFileProviderError/Code/pageExpired": {
      "abstract": [
        {
          "text": "An error indicating that the page is too old, and that the system must restart the enumeration operation from the beginning.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "pageExpired"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC23NSFileProviderErrorCodeLeV",
          "text": "NSFileProviderError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@NSFileProviderErrorCode",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.fileprovider/documentation/FileProvider/NSFileProviderError/Code/pageExpired",
      "kind": "symbol",
      "role": "symbol",
      "title": "pageExpired",
      "type": "topic",
      "url": "/documentation/fileprovider/nsfileprovidererror/code/pageexpired"
    },
    "doc://com.apple.fileprovider/documentation/FileProvider/NSFileProviderError/Code/providerNotFound": {
      "abstract": [
        {
          "text": "An error indicating that the File Provider manager can’t find the specified provider.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "providerNotFound"
        }
      ],
      "identifier": "doc://com.apple.fileprovider/documentation/FileProvider/NSFileProviderError/Code/providerNotFound",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSFileProviderErrorProviderNotFound"
        }
      ],
      "role": "symbol",
      "title": "NSFileProviderError.Code.providerNotFound",
      "type": "topic",
      "url": "/documentation/fileprovider/nsfileprovidererror/code/providernotfound"
    },
    "doc://com.apple.fileprovider/documentation/FileProvider/NSFileProviderError/Code/providerTranslocated": {
      "abstract": [
        {
          "text": "An error indicating the File Provider extension is in a disabled state due to Gatekeeper’s restrictions for apps from outside the App Store.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "providerTranslocated"
        }
      ],
      "identifier": "doc://com.apple.fileprovider/documentation/FileProvider/NSFileProviderError/Code/providerTranslocated",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSFileProviderErrorProviderTranslocated"
        }
      ],
      "role": "symbol",
      "title": "NSFileProviderError.Code.providerTranslocated",
      "type": "topic",
      "url": "/documentation/fileprovider/nsfileprovidererror/code/providertranslocated"
    },
    "doc://com.apple.fileprovider/documentation/FileProvider/NSFileProviderError/Code/serverUnreachable": {
      "abstract": [
        {
          "text": "An error indicating that the File Provider extension can’t reach the remote server.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "serverUnreachable"
        }
      ],
      "identifier": "doc://com.apple.fileprovider/documentation/FileProvider/NSFileProviderError/Code/serverUnreachable",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSFileProviderErrorServerUnreachable"
        }
      ],
      "role": "symbol",
      "title": "NSFileProviderError.Code.serverUnreachable",
      "type": "topic",
      "url": "/documentation/fileprovider/nsfileprovidererror/code/serverunreachable"
    },
    "doc://com.apple.fileprovider/documentation/FileProvider/NSFileProviderError/Code/syncAnchorExpired": {
      "abstract": [
        {
          "text": "An error indicating that the sync anchor is too old, and that the system must restart the sync operation from the beginning.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "syncAnchorExpired"
        }
      ],
      "identifier": "doc://com.apple.fileprovider/documentation/FileProvider/NSFileProviderError/Code/syncAnchorExpired",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSFileProviderErrorSyncAnchorExpired"
        }
      ],
      "role": "symbol",
      "title": "NSFileProviderError.Code.syncAnchorExpired",
      "type": "topic",
      "url": "/documentation/fileprovider/nsfileprovidererror/code/syncanchorexpired"
    },
    "doc://com.apple.fileprovider/documentation/FileProvider/NSFileProviderError/Code/unsyncedEdits": {
      "abstract": [
        {
          "text": "An error indicating that the item contains unsynced changes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "unsyncedEdits"
        }
      ],
      "identifier": "doc://com.apple.fileprovider/documentation/FileProvider/NSFileProviderError/Code/unsyncedEdits",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSFileProviderErrorUnsyncedEdits"
        }
      ],
      "role": "symbol",
      "title": "NSFileProviderError.Code.unsyncedEdits",
      "type": "topic",
      "url": "/documentation/fileprovider/nsfileprovidererror/code/unsyncededits"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Error-codes",
      "generated": true,
      "identifiers": [
        "doc://com.apple.fileprovider/documentation/FileProvider/NSFileProviderError/Code/filenameCollision",
        "doc://com.apple.fileprovider/documentation/FileProvider/NSFileProviderError/Code/insufficientQuota",
        "doc://com.apple.fileprovider/documentation/FileProvider/NSFileProviderError/Code/noSuchItem",
        "doc://com.apple.fileprovider/documentation/FileProvider/NSFileProviderError/Code/notAuthenticated",
        "doc://com.apple.fileprovider/documentation/FileProvider/NSFileProviderError/Code/serverUnreachable",
        "doc://com.apple.fileprovider/documentation/FileProvider/NSFileProviderError/Code/syncAnchorExpired",
        "doc://com.apple.fileprovider/documentation/FileProvider/NSFileProviderError/Code/pageExpired",
        "doc://com.apple.fileprovider/documentation/FileProvider/NSFileProviderError/Code/directoryNotEmpty",
        "doc://com.apple.fileprovider/documentation/FileProvider/NSFileProviderError/Code/providerTranslocated",
        "doc://com.apple.fileprovider/documentation/FileProvider/NSFileProviderError/Code/olderExtensionVersionRunning",
        "doc://com.apple.fileprovider/documentation/FileProvider/NSFileProviderError/Code/newerExtensionVersionFound",
        "doc://com.apple.fileprovider/documentation/FileProvider/NSFileProviderError/Code/nonEvictable",
        "doc://com.apple.fileprovider/documentation/FileProvider/NSFileProviderError/Code/nonEvictableChildren",
        "doc://com.apple.fileprovider/documentation/FileProvider/NSFileProviderError/Code/unsyncedEdits",
        "doc://com.apple.fileprovider/documentation/FileProvider/NSFileProviderError/Code/cannotSynchronize"
      ],
      "title": "Error codes"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "16.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "16.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "11.0",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration Case"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "NSFileProviderErrorProviderNotFound"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "case"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSFileProviderErrorProviderNotFound"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.fileprovider/documentation/FileProvider",
                "doc://com.apple.fileprovider/documentation/FileProvider/NSFileProviderError/Code"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Error-codes",
              "generated": true,
              "identifiers": [
                "doc://com.apple.fileprovider/documentation/FileProvider/NSFileProviderError/Code/filenameCollision",
                "doc://com.apple.fileprovider/documentation/FileProvider/NSFileProviderError/Code/insufficientQuota",
                "doc://com.apple.fileprovider/documentation/FileProvider/NSFileProviderError/Code/noSuchItem",
                "doc://com.apple.fileprovider/documentation/FileProvider/NSFileProviderError/Code/notAuthenticated",
                "doc://com.apple.fileprovider/documentation/FileProvider/NSFileProviderError/Code/serverUnreachable",
                "doc://com.apple.fileprovider/documentation/FileProvider/NSFileProviderError/Code/syncAnchorExpired",
                "doc://com.apple.fileprovider/documentation/FileProvider/NSFileProviderError/Code/directoryNotEmpty",
                "doc://com.apple.fileprovider/documentation/FileProvider/NSFileProviderError/Code/providerTranslocated",
                "doc://com.apple.fileprovider/documentation/FileProvider/NSFileProviderError/Code/olderExtensionVersionRunning",
                "doc://com.apple.fileprovider/documentation/FileProvider/NSFileProviderError/Code/newerExtensionVersionFound",
                "doc://com.apple.fileprovider/documentation/FileProvider/NSFileProviderError/Code/nonEvictable",
                "doc://com.apple.fileprovider/documentation/FileProvider/NSFileProviderError/Code/nonEvictableChildren",
                "doc://com.apple.fileprovider/documentation/FileProvider/NSFileProviderError/Code/unsyncedEdits",
                "doc://com.apple.fileprovider/documentation/FileProvider/NSFileProviderError/Code/cannotSynchronize",
                "doc://com.apple.fileprovider/documentation/FileProvider/NSFileProviderError/Code/deletionRejected"
              ],
              "title": "Error codes"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "visionOS"
                ],
                "tokens": [
                  {
                    "kind": "identifier",
                    "text": "NSFileProviderErrorProviderNotFound"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.fileprovider~1documentation~1FileProvider~1NSFileProviderError~1Code~1newerExtensionVersionFound/title",
          "value": "NSFileProviderErrorNewerExtensionVersionFound"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.fileprovider~1documentation~1FileProvider~1NSFileProviderError~1Code~1newerExtensionVersionFound/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSFileProviderErrorNewerExtensionVersionFound"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.fileprovider~1documentation~1FileProvider~1NSFileProviderError~1Code~1insufficientQuota/title",
          "value": "NSFileProviderErrorInsufficientQuota"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.fileprovider~1documentation~1FileProvider~1NSFileProviderError~1Code~1insufficientQuota/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSFileProviderErrorInsufficientQuota"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.fileprovider~1documentation~1FileProvider~1NSFileProviderError~1Code~1cannotSynchronize/title",
          "value": "NSFileProviderErrorCannotSynchronize"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.fileprovider~1documentation~1FileProvider~1NSFileProviderError~1Code~1cannotSynchronize/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSFileProviderErrorCannotSynchronize"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.fileprovider~1documentation~1FileProvider~1NSFileProviderError~1Code~1serverUnreachable/title",
          "value": "NSFileProviderErrorServerUnreachable"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.fileprovider~1documentation~1FileProvider~1NSFileProviderError~1Code~1serverUnreachable/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSFileProviderErrorServerUnreachable"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.fileprovider~1documentation~1FileProvider~1NSFileProviderError~1Code~1deletionRejected/title",
          "value": "NSFileProviderErrorDeletionRejected"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.fileprovider~1documentation~1FileProvider~1NSFileProviderError~1Code~1deletionRejected/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSFileProviderErrorDeletionRejected"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.fileprovider~1documentation~1FileProvider~1NSFileProviderError~1Code~1providerTranslocated/title",
          "value": "NSFileProviderErrorProviderTranslocated"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.fileprovider~1documentation~1FileProvider~1NSFileProviderError~1Code~1providerTranslocated/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSFileProviderErrorProviderTranslocated"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.fileprovider~1documentation~1FileProvider~1NSFileProviderError~1Code~1olderExtensionVersionRunning/title",
          "value": "NSFileProviderErrorOlderExtensionVersionRunning"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.fileprovider~1documentation~1FileProvider~1NSFileProviderError~1Code~1olderExtensionVersionRunning/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSFileProviderErrorOlderExtensionVersionRunning"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.fileprovider~1documentation~1FileProvider~1NSFileProviderError~1Code~1nonEvictable/title",
          "value": "NSFileProviderErrorNonEvictable"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.fileprovider~1documentation~1FileProvider~1NSFileProviderError~1Code~1nonEvictable/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSFileProviderErrorNonEvictable"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.fileprovider~1documentation~1FileProvider~1NSFileProviderError~1Code~1providerNotFound/title",
          "value": "NSFileProviderErrorProviderNotFound"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.fileprovider~1documentation~1FileProvider~1NSFileProviderError~1Code~1providerNotFound/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSFileProviderErrorProviderNotFound"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.fileprovider~1documentation~1FileProvider~1NSFileProviderError~1Code~1filenameCollision/title",
          "value": "NSFileProviderErrorFilenameCollision"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.fileprovider~1documentation~1FileProvider~1NSFileProviderError~1Code~1filenameCollision/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSFileProviderErrorFilenameCollision"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.fileprovider~1documentation~1FileProvider~1NSFileProviderError~1Code~1nonEvictableChildren/title",
          "value": "NSFileProviderErrorNonEvictableChildren"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.fileprovider~1documentation~1FileProvider~1NSFileProviderError~1Code~1nonEvictableChildren/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSFileProviderErrorNonEvictableChildren"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.fileprovider~1documentation~1FileProvider~1NSFileProviderError~1Code/title",
          "value": "NSFileProviderErrorCode"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.fileprovider~1documentation~1FileProvider~1NSFileProviderError~1Code/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSFileProviderErrorCode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.fileprovider~1documentation~1FileProvider~1NSFileProviderError~1Code/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSFileProviderErrorCode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.fileprovider~1documentation~1FileProvider~1NSFileProviderError~1Code~1noSuchItem/title",
          "value": "NSFileProviderErrorNoSuchItem"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.fileprovider~1documentation~1FileProvider~1NSFileProviderError~1Code~1noSuchItem/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSFileProviderErrorNoSuchItem"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.fileprovider~1documentation~1FileProvider~1NSFileProviderError~1Code~1notAuthenticated/title",
          "value": "NSFileProviderErrorNotAuthenticated"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.fileprovider~1documentation~1FileProvider~1NSFileProviderError~1Code~1notAuthenticated/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSFileProviderErrorNotAuthenticated"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.fileprovider~1documentation~1FileProvider~1NSFileProviderError~1Code~1unsyncedEdits/title",
          "value": "NSFileProviderErrorUnsyncedEdits"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.fileprovider~1documentation~1FileProvider~1NSFileProviderError~1Code~1unsyncedEdits/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSFileProviderErrorUnsyncedEdits"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.fileprovider~1documentation~1FileProvider~1NSFileProviderError~1Code~1directoryNotEmpty/title",
          "value": "NSFileProviderErrorDirectoryNotEmpty"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.fileprovider~1documentation~1FileProvider~1NSFileProviderError~1Code~1directoryNotEmpty/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSFileProviderErrorDirectoryNotEmpty"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.fileprovider~1documentation~1FileProvider~1NSFileProviderError~1Code~1syncAnchorExpired/title",
          "value": "NSFileProviderErrorSyncAnchorExpired"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.fileprovider~1documentation~1FileProvider~1NSFileProviderError~1Code~1syncAnchorExpired/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSFileProviderErrorSyncAnchorExpired"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/fileprovider/nsfileprovidererror/code/providernotfound"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/fileprovider/nsfileprovidererror/code/providernotfound"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
