{
  "abstract": [
    {
      "text": "A rule protocol to match UDP traffic.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.networkextension/documentation/NetworkExtension",
        "doc://com.apple.networkextension/documentation/NetworkExtension/NENetworkRule",
        "doc://com.apple.networkextension/documentation/NetworkExtension/NENetworkRule/Protocol"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.networkextension/documentation/NetworkExtension/NENetworkRule/Protocol/UDP"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@NENetworkRuleProtocol@NENetworkRuleProtocolUDP",
    "fragments": [
      {
        "kind": "keyword",
        "text": "case"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "UDP"
      }
    ],
    "modules": [
      {
        "name": "Network Extension"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "NENetworkRuleProtocolUDP"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.15",
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Case",
    "symbolKind": "case",
    "title": "NENetworkRule.Protocol.UDP"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "macOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "case"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "UDP"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.networkextension/documentation/NetworkExtension": {
      "abstract": [
        {
          "text": "Customize and extend core networking features.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.networkextension/documentation/NetworkExtension",
      "kind": "symbol",
      "role": "collection",
      "title": "Network Extension",
      "type": "topic",
      "url": "/documentation/networkextension"
    },
    "doc://com.apple.networkextension/documentation/NetworkExtension/NENetworkRule": {
      "abstract": [
        {
          "text": "A rule to match attributes of network traffic.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NENetworkRule"
        }
      ],
      "identifier": "doc://com.apple.networkextension/documentation/NetworkExtension/NENetworkRule",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NENetworkRule"
        }
      ],
      "role": "symbol",
      "title": "NENetworkRule",
      "type": "topic",
      "url": "/documentation/networkextension/nenetworkrule"
    },
    "doc://com.apple.networkextension/documentation/NetworkExtension/NENetworkRule/Protocol": {
      "abstract": [
        {
          "text": "A type to represent network protocols used by routing rules.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Protocol"
        }
      ],
      "identifier": "doc://com.apple.networkextension/documentation/NetworkExtension/NENetworkRule/Protocol",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "Protocol"
        }
      ],
      "role": "symbol",
      "title": "NENetworkRule.Protocol",
      "type": "topic",
      "url": "/documentation/networkextension/nenetworkrule/protocol"
    },
    "doc://com.apple.networkextension/documentation/NetworkExtension/NENetworkRule/Protocol/TCP": {
      "abstract": [
        {
          "text": "A rule protocol to match TCP traffic.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "TCP"
        }
      ],
      "identifier": "doc://com.apple.networkextension/documentation/NetworkExtension/NENetworkRule/Protocol/TCP",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NENetworkRuleProtocolTCP"
        }
      ],
      "role": "symbol",
      "title": "NENetworkRule.Protocol.TCP",
      "type": "topic",
      "url": "/documentation/networkextension/nenetworkrule/protocol/tcp"
    },
    "doc://com.apple.networkextension/documentation/NetworkExtension/NENetworkRule/Protocol/UDP": {
      "abstract": [
        {
          "text": "A rule protocol to match UDP traffic.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UDP"
        }
      ],
      "identifier": "doc://com.apple.networkextension/documentation/NetworkExtension/NENetworkRule/Protocol/UDP",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NENetworkRuleProtocolUDP"
        }
      ],
      "role": "symbol",
      "title": "NENetworkRule.Protocol.UDP",
      "type": "topic",
      "url": "/documentation/networkextension/nenetworkrule/protocol/udp"
    },
    "doc://com.apple.networkextension/documentation/NetworkExtension/NENetworkRule/Protocol/any": {
      "abstract": [
        {
          "text": "A rule protocol to match TCP and UDP traffic.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "any"
        }
      ],
      "identifier": "doc://com.apple.networkextension/documentation/NetworkExtension/NENetworkRule/Protocol/any",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NENetworkRuleProtocolAny"
        }
      ],
      "role": "symbol",
      "title": "NENetworkRule.Protocol.any",
      "type": "topic",
      "url": "/documentation/networkextension/nenetworkrule/protocol/any"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Protocols",
      "generated": true,
      "identifiers": [
        "doc://com.apple.networkextension/documentation/NetworkExtension/NENetworkRule/Protocol/TCP",
        "doc://com.apple.networkextension/documentation/NetworkExtension/NENetworkRule/Protocol/any"
      ],
      "title": "Protocols"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.15",
              "name": "macOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration Case"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "NENetworkRuleProtocolUDP"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "case"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NENetworkRuleProtocolUDP"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.networkextension/documentation/NetworkExtension",
                "doc://com.apple.networkextension/documentation/NetworkExtension/NENetworkRule/Protocol"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Protocols",
              "generated": true,
              "identifiers": [
                "doc://com.apple.networkextension/documentation/NetworkExtension/NENetworkRule/Protocol/TCP",
                "doc://com.apple.networkextension/documentation/NetworkExtension/NENetworkRule/Protocol/any"
              ],
              "title": "Protocols"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "identifier",
                    "text": "NENetworkRuleProtocolUDP"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.networkextension~1documentation~1NetworkExtension~1NENetworkRule~1Protocol~1any/title",
          "value": "NENetworkRuleProtocolAny"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.networkextension~1documentation~1NetworkExtension~1NENetworkRule~1Protocol~1any/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NENetworkRuleProtocolAny"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.networkextension~1documentation~1NetworkExtension~1NENetworkRule~1Protocol/title",
          "value": "NENetworkRuleProtocol"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.networkextension~1documentation~1NetworkExtension~1NENetworkRule~1Protocol/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NENetworkRuleProtocol"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.networkextension~1documentation~1NetworkExtension~1NENetworkRule~1Protocol/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NENetworkRuleProtocol"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.networkextension~1documentation~1NetworkExtension~1NENetworkRule/title",
          "value": "NENetworkRule"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.networkextension~1documentation~1NetworkExtension~1NENetworkRule/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NENetworkRule"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.networkextension~1documentation~1NetworkExtension~1NENetworkRule/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NENetworkRule"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.networkextension~1documentation~1NetworkExtension~1NENetworkRule~1Protocol~1UDP/title",
          "value": "NENetworkRuleProtocolUDP"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.networkextension~1documentation~1NetworkExtension~1NENetworkRule~1Protocol~1UDP/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NENetworkRuleProtocolUDP"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.networkextension~1documentation~1NetworkExtension~1NENetworkRule~1Protocol~1TCP/title",
          "value": "NENetworkRuleProtocolTCP"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.networkextension~1documentation~1NetworkExtension~1NENetworkRule~1Protocol~1TCP/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NENetworkRuleProtocolTCP"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/networkextension/nenetworkrule/protocol/udp"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/networkextension/nenetworkrule/protocol/udp"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
