{
  "abstract": [
    {
      "text": "The contacts system item.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.uikit/documentation/UIKit",
        "doc://com.apple.uikit/documentation/UIKit/UITabBarItem",
        "doc://com.apple.uikit/documentation/UIKit/UITabBarItem/SystemItem"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.uikit/documentation/UIKit/UITabBarItem/SystemItem/contacts"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@UITabBarSystemItem@UITabBarSystemItemContacts",
    "fragments": [
      {
        "kind": "keyword",
        "text": "case"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "contacts"
      }
    ],
    "modules": [
      {
        "name": "UIKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "UITabBarSystemItemContacts"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Case",
    "symbolKind": "case",
    "title": "UITabBarItem.SystemItem.contacts"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "tvOS",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "case"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "contacts"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.uikit/documentation/UIKit": {
      "abstract": [
        {
          "text": "Construct and manage a graphical, event-driven user interface for your iOS, iPadOS, or tvOS app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit",
      "kind": "symbol",
      "role": "collection",
      "title": "UIKit",
      "type": "topic",
      "url": "/documentation/uikit"
    },
    "doc://com.apple.uikit/documentation/UIKit/UITabBarItem": {
      "abstract": [
        {
          "text": "An object that describes an item in a tab bar.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UITabBarItem"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UITabBarItem",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UITabBarItem"
        }
      ],
      "role": "symbol",
      "title": "UITabBarItem",
      "type": "topic",
      "url": "/documentation/uikit/uitabbaritem"
    },
    "doc://com.apple.uikit/documentation/UIKit/UITabBarItem/SystemItem": {
      "abstract": [
        {
          "text": "Constants that represent the system tab bar items.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SystemItem"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UITabBarItem/SystemItem",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SystemItem"
        }
      ],
      "role": "symbol",
      "title": "UITabBarItem.SystemItem",
      "type": "topic",
      "url": "/documentation/uikit/uitabbaritem/systemitem"
    },
    "doc://com.apple.uikit/documentation/UIKit/UITabBarItem/SystemItem/bookmarks": {
      "abstract": [
        {
          "text": "The bookmarks system item.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "bookmarks"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UITabBarItem/SystemItem/bookmarks",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UITabBarSystemItemBookmarks"
        }
      ],
      "role": "symbol",
      "title": "UITabBarItem.SystemItem.bookmarks",
      "type": "topic",
      "url": "/documentation/uikit/uitabbaritem/systemitem/bookmarks"
    },
    "doc://com.apple.uikit/documentation/UIKit/UITabBarItem/SystemItem/contacts": {
      "abstract": [
        {
          "text": "The contacts system item.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "contacts"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UITabBarItem/SystemItem/contacts",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UITabBarSystemItemContacts"
        }
      ],
      "role": "symbol",
      "title": "UITabBarItem.SystemItem.contacts",
      "type": "topic",
      "url": "/documentation/uikit/uitabbaritem/systemitem/contacts"
    },
    "doc://com.apple.uikit/documentation/UIKit/UITabBarItem/SystemItem/downloads": {
      "abstract": [
        {
          "text": "The downloads system item.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "downloads"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UITabBarItem/SystemItem/downloads",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UITabBarSystemItemDownloads"
        }
      ],
      "role": "symbol",
      "title": "UITabBarItem.SystemItem.downloads",
      "type": "topic",
      "url": "/documentation/uikit/uitabbaritem/systemitem/downloads"
    },
    "doc://com.apple.uikit/documentation/UIKit/UITabBarItem/SystemItem/favorites": {
      "abstract": [
        {
          "text": "The favorites system item.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "favorites"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UITabBarItem/SystemItem/favorites",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UITabBarSystemItemFavorites"
        }
      ],
      "role": "symbol",
      "title": "UITabBarItem.SystemItem.favorites",
      "type": "topic",
      "url": "/documentation/uikit/uitabbaritem/systemitem/favorites"
    },
    "doc://com.apple.uikit/documentation/UIKit/UITabBarItem/SystemItem/featured": {
      "abstract": [
        {
          "text": "The featured system item.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "featured"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UITabBarItem/SystemItem/featured",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UITabBarSystemItemFeatured"
        }
      ],
      "role": "symbol",
      "title": "UITabBarItem.SystemItem.featured",
      "type": "topic",
      "url": "/documentation/uikit/uitabbaritem/systemitem/featured"
    },
    "doc://com.apple.uikit/documentation/UIKit/UITabBarItem/SystemItem/history": {
      "abstract": [
        {
          "text": "The history system item.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "history"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UITabBarItem/SystemItem/history",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UITabBarSystemItemHistory"
        }
      ],
      "role": "symbol",
      "title": "UITabBarItem.SystemItem.history",
      "type": "topic",
      "url": "/documentation/uikit/uitabbaritem/systemitem/history"
    },
    "doc://com.apple.uikit/documentation/UIKit/UITabBarItem/SystemItem/more": {
      "abstract": [
        {
          "text": "The more system item.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "more"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UITabBarItem/SystemItem/more",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UITabBarSystemItemMore"
        }
      ],
      "role": "symbol",
      "title": "UITabBarItem.SystemItem.more",
      "type": "topic",
      "url": "/documentation/uikit/uitabbaritem/systemitem/more"
    },
    "doc://com.apple.uikit/documentation/UIKit/UITabBarItem/SystemItem/mostRecent": {
      "abstract": [
        {
          "text": "The most recent system item.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "mostRecent"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UITabBarItem/SystemItem/mostRecent",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UITabBarSystemItemMostRecent"
        }
      ],
      "role": "symbol",
      "title": "UITabBarItem.SystemItem.mostRecent",
      "type": "topic",
      "url": "/documentation/uikit/uitabbaritem/systemitem/mostrecent"
    },
    "doc://com.apple.uikit/documentation/UIKit/UITabBarItem/SystemItem/mostViewed": {
      "abstract": [
        {
          "text": "The most viewed system item.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "mostViewed"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UITabBarItem/SystemItem/mostViewed",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UITabBarSystemItemMostViewed"
        }
      ],
      "role": "symbol",
      "title": "UITabBarItem.SystemItem.mostViewed",
      "type": "topic",
      "url": "/documentation/uikit/uitabbaritem/systemitem/mostviewed"
    },
    "doc://com.apple.uikit/documentation/UIKit/UITabBarItem/SystemItem/recents": {
      "abstract": [
        {
          "text": "The recents system item.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "recents"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UITabBarItem/SystemItem/recents",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UITabBarSystemItemRecents"
        }
      ],
      "role": "symbol",
      "title": "UITabBarItem.SystemItem.recents",
      "type": "topic",
      "url": "/documentation/uikit/uitabbaritem/systemitem/recents"
    },
    "doc://com.apple.uikit/documentation/UIKit/UITabBarItem/SystemItem/search": {
      "abstract": [
        {
          "text": "The search system item.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "search"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UITabBarItem/SystemItem/search",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UITabBarSystemItemSearch"
        }
      ],
      "role": "symbol",
      "title": "UITabBarItem.SystemItem.search",
      "type": "topic",
      "url": "/documentation/uikit/uitabbaritem/systemitem/search"
    },
    "doc://com.apple.uikit/documentation/UIKit/UITabBarItem/SystemItem/topRated": {
      "abstract": [
        {
          "text": "The top rated system item.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "topRated"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UITabBarItem/SystemItem/topRated",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UITabBarSystemItemTopRated"
        }
      ],
      "role": "symbol",
      "title": "UITabBarItem.SystemItem.topRated",
      "type": "topic",
      "url": "/documentation/uikit/uitabbaritem/systemitem/toprated"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "System-items",
      "generated": true,
      "identifiers": [
        "doc://com.apple.uikit/documentation/UIKit/UITabBarItem/SystemItem/bookmarks",
        "doc://com.apple.uikit/documentation/UIKit/UITabBarItem/SystemItem/downloads",
        "doc://com.apple.uikit/documentation/UIKit/UITabBarItem/SystemItem/favorites",
        "doc://com.apple.uikit/documentation/UIKit/UITabBarItem/SystemItem/featured",
        "doc://com.apple.uikit/documentation/UIKit/UITabBarItem/SystemItem/history",
        "doc://com.apple.uikit/documentation/UIKit/UITabBarItem/SystemItem/more",
        "doc://com.apple.uikit/documentation/UIKit/UITabBarItem/SystemItem/mostRecent",
        "doc://com.apple.uikit/documentation/UIKit/UITabBarItem/SystemItem/mostViewed",
        "doc://com.apple.uikit/documentation/UIKit/UITabBarItem/SystemItem/recents",
        "doc://com.apple.uikit/documentation/UIKit/UITabBarItem/SystemItem/search",
        "doc://com.apple.uikit/documentation/UIKit/UITabBarItem/SystemItem/topRated"
      ],
      "title": "System items"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration Case"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "UITabBarSystemItemContacts"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "case"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UITabBarSystemItemContacts"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.uikit/documentation/UIKit",
                "doc://com.apple.uikit/documentation/UIKit/UITabBarItem/SystemItem"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "System-items",
              "generated": true,
              "identifiers": [
                "doc://com.apple.uikit/documentation/UIKit/UITabBarItem/SystemItem/bookmarks",
                "doc://com.apple.uikit/documentation/UIKit/UITabBarItem/SystemItem/downloads",
                "doc://com.apple.uikit/documentation/UIKit/UITabBarItem/SystemItem/favorites",
                "doc://com.apple.uikit/documentation/UIKit/UITabBarItem/SystemItem/featured",
                "doc://com.apple.uikit/documentation/UIKit/UITabBarItem/SystemItem/history",
                "doc://com.apple.uikit/documentation/UIKit/UITabBarItem/SystemItem/more",
                "doc://com.apple.uikit/documentation/UIKit/UITabBarItem/SystemItem/mostRecent",
                "doc://com.apple.uikit/documentation/UIKit/UITabBarItem/SystemItem/mostViewed",
                "doc://com.apple.uikit/documentation/UIKit/UITabBarItem/SystemItem/recents",
                "doc://com.apple.uikit/documentation/UIKit/UITabBarItem/SystemItem/search",
                "doc://com.apple.uikit/documentation/UIKit/UITabBarItem/SystemItem/topRated"
              ],
              "title": "System items"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "tvOS",
                  "visionOS"
                ],
                "tokens": [
                  {
                    "kind": "identifier",
                    "text": "UITabBarSystemItemContacts"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITabBarItem~1SystemItem/title",
          "value": "UITabBarSystemItem"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITabBarItem~1SystemItem/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UITabBarSystemItem"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITabBarItem~1SystemItem/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UITabBarSystemItem"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITabBarItem~1SystemItem~1history/title",
          "value": "UITabBarSystemItemHistory"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITabBarItem~1SystemItem~1history/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UITabBarSystemItemHistory"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITabBarItem~1SystemItem~1more/title",
          "value": "UITabBarSystemItemMore"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITabBarItem~1SystemItem~1more/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UITabBarSystemItemMore"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITabBarItem~1SystemItem~1search/title",
          "value": "UITabBarSystemItemSearch"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITabBarItem~1SystemItem~1search/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UITabBarSystemItemSearch"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITabBarItem~1SystemItem~1bookmarks/title",
          "value": "UITabBarSystemItemBookmarks"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITabBarItem~1SystemItem~1bookmarks/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UITabBarSystemItemBookmarks"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITabBarItem~1SystemItem~1downloads/title",
          "value": "UITabBarSystemItemDownloads"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITabBarItem~1SystemItem~1downloads/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UITabBarSystemItemDownloads"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITabBarItem~1SystemItem~1mostRecent/title",
          "value": "UITabBarSystemItemMostRecent"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITabBarItem~1SystemItem~1mostRecent/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UITabBarSystemItemMostRecent"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITabBarItem~1SystemItem~1favorites/title",
          "value": "UITabBarSystemItemFavorites"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITabBarItem~1SystemItem~1favorites/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UITabBarSystemItemFavorites"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITabBarItem~1SystemItem~1recents/title",
          "value": "UITabBarSystemItemRecents"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITabBarItem~1SystemItem~1recents/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UITabBarSystemItemRecents"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITabBarItem~1SystemItem~1topRated/title",
          "value": "UITabBarSystemItemTopRated"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITabBarItem~1SystemItem~1topRated/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UITabBarSystemItemTopRated"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITabBarItem~1SystemItem~1mostViewed/title",
          "value": "UITabBarSystemItemMostViewed"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITabBarItem~1SystemItem~1mostViewed/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UITabBarSystemItemMostViewed"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITabBarItem~1SystemItem~1contacts/title",
          "value": "UITabBarSystemItemContacts"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITabBarItem~1SystemItem~1contacts/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UITabBarSystemItemContacts"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITabBarItem~1SystemItem~1featured/title",
          "value": "UITabBarSystemItemFeatured"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITabBarItem~1SystemItem~1featured/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UITabBarSystemItemFeatured"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITabBarItem/title",
          "value": "UITabBarItem"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITabBarItem/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UITabBarItem"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITabBarItem/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UITabBarItem"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/uikit/uitabbaritem/systemitem/contacts"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/uikit/uitabbaritem/systemitem/contacts"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
