{
  "abstract": [
    {
      "text": "The constant for playing baseball.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.healthkit/documentation/HealthKit",
        "doc://com.apple.healthkit/documentation/HealthKit/HKWorkoutActivityType"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.healthkit/documentation/HealthKit/HKWorkoutActivityType/baseball"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@HKWorkoutActivityType@HKWorkoutActivityTypeBaseball",
    "fragments": [
      {
        "kind": "keyword",
        "text": "case"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "baseball"
      }
    ],
    "modules": [
      {
        "name": "HealthKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "HKWorkoutActivityTypeBaseball"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "8.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "8.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.0",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.0",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "2.0",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Case",
    "symbolKind": "case",
    "title": "HKWorkoutActivityType.baseball"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "case"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "baseball"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.healthkit/documentation/HealthKit": {
      "abstract": [
        {
          "text": "Access and share health and fitness data while maintaining the user’s privacy and control.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit",
      "kind": "symbol",
      "role": "collection",
      "title": "HealthKit",
      "type": "topic",
      "url": "/documentation/healthkit"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/HKWorkoutActivityType": {
      "abstract": [
        {
          "text": "The type of activity performed during a workout.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "HKWorkoutActivityType"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKWorkoutActivityType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HKWorkoutActivityType"
        }
      ],
      "role": "symbol",
      "title": "HKWorkoutActivityType",
      "type": "topic",
      "url": "/documentation/healthkit/hkworkoutactivitytype"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/HKWorkoutActivityType/americanFootball": {
      "abstract": [
        {
          "text": "The constant for playing American football.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "americanFootball"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKWorkoutActivityType/americanFootball",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HKWorkoutActivityTypeAmericanFootball"
        }
      ],
      "role": "symbol",
      "title": "HKWorkoutActivityType.americanFootball",
      "type": "topic",
      "url": "/documentation/healthkit/hkworkoutactivitytype/americanfootball"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/HKWorkoutActivityType/australianFootball": {
      "abstract": [
        {
          "text": "The constant for playing Australian football.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "australianFootball"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKWorkoutActivityType/australianFootball",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HKWorkoutActivityTypeAustralianFootball"
        }
      ],
      "role": "symbol",
      "title": "HKWorkoutActivityType.australianFootball",
      "type": "topic",
      "url": "/documentation/healthkit/hkworkoutactivitytype/australianfootball"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/HKWorkoutActivityType/baseball": {
      "abstract": [
        {
          "text": "The constant for playing baseball.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "baseball"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKWorkoutActivityType/baseball",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HKWorkoutActivityTypeBaseball"
        }
      ],
      "role": "symbol",
      "title": "HKWorkoutActivityType.baseball",
      "type": "topic",
      "url": "/documentation/healthkit/hkworkoutactivitytype/baseball"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/HKWorkoutActivityType/basketball": {
      "abstract": [
        {
          "text": "The constant for playing basketball.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "basketball"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKWorkoutActivityType/basketball",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HKWorkoutActivityTypeBasketball"
        }
      ],
      "role": "symbol",
      "title": "HKWorkoutActivityType.basketball",
      "type": "topic",
      "url": "/documentation/healthkit/hkworkoutactivitytype/basketball"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/HKWorkoutActivityType/cricket": {
      "abstract": [
        {
          "text": "The constant for playing cricket.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "cricket"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKWorkoutActivityType/cricket",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HKWorkoutActivityTypeCricket"
        }
      ],
      "role": "symbol",
      "title": "HKWorkoutActivityType.cricket",
      "type": "topic",
      "url": "/documentation/healthkit/hkworkoutactivitytype/cricket"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/HKWorkoutActivityType/discSports": {
      "abstract": [
        {
          "text": "The constant for playing disc sports such as Ultimate and Disc Golf.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "discSports"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKWorkoutActivityType/discSports",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HKWorkoutActivityTypeDiscSports"
        }
      ],
      "role": "symbol",
      "title": "HKWorkoutActivityType.discSports",
      "type": "topic",
      "url": "/documentation/healthkit/hkworkoutactivitytype/discsports"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/HKWorkoutActivityType/handball": {
      "abstract": [
        {
          "text": "The constant for playing handball.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "handball"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKWorkoutActivityType/handball",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HKWorkoutActivityTypeHandball"
        }
      ],
      "role": "symbol",
      "title": "HKWorkoutActivityType.handball",
      "type": "topic",
      "url": "/documentation/healthkit/hkworkoutactivitytype/handball"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/HKWorkoutActivityType/hockey": {
      "abstract": [
        {
          "text": "The constant for playing hockey, including ice hockey, field hockey, and related sports.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "hockey"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKWorkoutActivityType/hockey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HKWorkoutActivityTypeHockey"
        }
      ],
      "role": "symbol",
      "title": "HKWorkoutActivityType.hockey",
      "type": "topic",
      "url": "/documentation/healthkit/hkworkoutactivitytype/hockey"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/HKWorkoutActivityType/lacrosse": {
      "abstract": [
        {
          "text": "The constant for playing lacrosse.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "lacrosse"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKWorkoutActivityType/lacrosse",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HKWorkoutActivityTypeLacrosse"
        }
      ],
      "role": "symbol",
      "title": "HKWorkoutActivityType.lacrosse",
      "type": "topic",
      "url": "/documentation/healthkit/hkworkoutactivitytype/lacrosse"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/HKWorkoutActivityType/rugby": {
      "abstract": [
        {
          "text": "The constant for playing rugby.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "rugby"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKWorkoutActivityType/rugby",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HKWorkoutActivityTypeRugby"
        }
      ],
      "role": "symbol",
      "title": "HKWorkoutActivityType.rugby",
      "type": "topic",
      "url": "/documentation/healthkit/hkworkoutactivitytype/rugby"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/HKWorkoutActivityType/soccer": {
      "abstract": [
        {
          "text": "The constant for playing soccer.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "soccer"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKWorkoutActivityType/soccer",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HKWorkoutActivityTypeSoccer"
        }
      ],
      "role": "symbol",
      "title": "HKWorkoutActivityType.soccer",
      "type": "topic",
      "url": "/documentation/healthkit/hkworkoutactivitytype/soccer"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/HKWorkoutActivityType/softball": {
      "abstract": [
        {
          "text": "The constant for playing softball.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "softball"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKWorkoutActivityType/softball",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HKWorkoutActivityTypeSoftball"
        }
      ],
      "role": "symbol",
      "title": "HKWorkoutActivityType.softball",
      "type": "topic",
      "url": "/documentation/healthkit/hkworkoutactivitytype/softball"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/HKWorkoutActivityType/volleyball": {
      "abstract": [
        {
          "text": "The constant for playing volleyball.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "volleyball"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKWorkoutActivityType/volleyball",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HKWorkoutActivityTypeVolleyball"
        }
      ],
      "role": "symbol",
      "title": "HKWorkoutActivityType.volleyball",
      "type": "topic",
      "url": "/documentation/healthkit/hkworkoutactivitytype/volleyball"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Team-sports",
      "generated": true,
      "identifiers": [
        "doc://com.apple.healthkit/documentation/HealthKit/HKWorkoutActivityType/americanFootball",
        "doc://com.apple.healthkit/documentation/HealthKit/HKWorkoutActivityType/australianFootball",
        "doc://com.apple.healthkit/documentation/HealthKit/HKWorkoutActivityType/basketball",
        "doc://com.apple.healthkit/documentation/HealthKit/HKWorkoutActivityType/cricket",
        "doc://com.apple.healthkit/documentation/HealthKit/HKWorkoutActivityType/discSports",
        "doc://com.apple.healthkit/documentation/HealthKit/HKWorkoutActivityType/handball",
        "doc://com.apple.healthkit/documentation/HealthKit/HKWorkoutActivityType/hockey",
        "doc://com.apple.healthkit/documentation/HealthKit/HKWorkoutActivityType/lacrosse",
        "doc://com.apple.healthkit/documentation/HealthKit/HKWorkoutActivityType/rugby",
        "doc://com.apple.healthkit/documentation/HealthKit/HKWorkoutActivityType/soccer",
        "doc://com.apple.healthkit/documentation/HealthKit/HKWorkoutActivityType/softball",
        "doc://com.apple.healthkit/documentation/HealthKit/HKWorkoutActivityType/volleyball"
      ],
      "title": "Team sports"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "8.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "8.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.0",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.0",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "2.0",
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration Case"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "HKWorkoutActivityTypeBaseball"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "case"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HKWorkoutActivityTypeBaseball"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.healthkit/documentation/HealthKit",
                "doc://com.apple.healthkit/documentation/HealthKit/HKWorkoutActivityType"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Team-sports",
              "generated": true,
              "identifiers": [
                "doc://com.apple.healthkit/documentation/HealthKit/HKWorkoutActivityType/americanFootball",
                "doc://com.apple.healthkit/documentation/HealthKit/HKWorkoutActivityType/australianFootball",
                "doc://com.apple.healthkit/documentation/HealthKit/HKWorkoutActivityType/basketball",
                "doc://com.apple.healthkit/documentation/HealthKit/HKWorkoutActivityType/cricket",
                "doc://com.apple.healthkit/documentation/HealthKit/HKWorkoutActivityType/discSports",
                "doc://com.apple.healthkit/documentation/HealthKit/HKWorkoutActivityType/handball",
                "doc://com.apple.healthkit/documentation/HealthKit/HKWorkoutActivityType/hockey",
                "doc://com.apple.healthkit/documentation/HealthKit/HKWorkoutActivityType/lacrosse",
                "doc://com.apple.healthkit/documentation/HealthKit/HKWorkoutActivityType/rugby",
                "doc://com.apple.healthkit/documentation/HealthKit/HKWorkoutActivityType/soccer",
                "doc://com.apple.healthkit/documentation/HealthKit/HKWorkoutActivityType/softball",
                "doc://com.apple.healthkit/documentation/HealthKit/HKWorkoutActivityType/volleyball"
              ],
              "title": "Team sports"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "identifier",
                    "text": "HKWorkoutActivityTypeBaseball"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKWorkoutActivityType~1basketball/title",
          "value": "HKWorkoutActivityTypeBasketball"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKWorkoutActivityType~1basketball/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HKWorkoutActivityTypeBasketball"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKWorkoutActivityType~1baseball/title",
          "value": "HKWorkoutActivityTypeBaseball"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKWorkoutActivityType~1baseball/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HKWorkoutActivityTypeBaseball"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKWorkoutActivityType~1americanFootball/title",
          "value": "HKWorkoutActivityTypeAmericanFootball"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKWorkoutActivityType~1americanFootball/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HKWorkoutActivityTypeAmericanFootball"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKWorkoutActivityType~1soccer/title",
          "value": "HKWorkoutActivityTypeSoccer"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKWorkoutActivityType~1soccer/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HKWorkoutActivityTypeSoccer"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKWorkoutActivityType~1volleyball/title",
          "value": "HKWorkoutActivityTypeVolleyball"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKWorkoutActivityType~1volleyball/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HKWorkoutActivityTypeVolleyball"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKWorkoutActivityType~1cricket/title",
          "value": "HKWorkoutActivityTypeCricket"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKWorkoutActivityType~1cricket/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HKWorkoutActivityTypeCricket"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKWorkoutActivityType~1lacrosse/title",
          "value": "HKWorkoutActivityTypeLacrosse"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKWorkoutActivityType~1lacrosse/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HKWorkoutActivityTypeLacrosse"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKWorkoutActivityType~1hockey/title",
          "value": "HKWorkoutActivityTypeHockey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKWorkoutActivityType~1hockey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HKWorkoutActivityTypeHockey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKWorkoutActivityType/title",
          "value": "HKWorkoutActivityType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKWorkoutActivityType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HKWorkoutActivityType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKWorkoutActivityType/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "HKWorkoutActivityType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKWorkoutActivityType~1discSports/title",
          "value": "HKWorkoutActivityTypeDiscSports"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKWorkoutActivityType~1discSports/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HKWorkoutActivityTypeDiscSports"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKWorkoutActivityType~1handball/title",
          "value": "HKWorkoutActivityTypeHandball"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKWorkoutActivityType~1handball/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HKWorkoutActivityTypeHandball"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKWorkoutActivityType~1australianFootball/title",
          "value": "HKWorkoutActivityTypeAustralianFootball"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKWorkoutActivityType~1australianFootball/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HKWorkoutActivityTypeAustralianFootball"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKWorkoutActivityType~1softball/title",
          "value": "HKWorkoutActivityTypeSoftball"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKWorkoutActivityType~1softball/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HKWorkoutActivityTypeSoftball"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKWorkoutActivityType~1rugby/title",
          "value": "HKWorkoutActivityTypeRugby"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKWorkoutActivityType~1rugby/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HKWorkoutActivityTypeRugby"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/healthkit/hkworkoutactivitytype/baseball"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/healthkit/hkworkoutactivitytype/baseball"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
