{
  "abstract": [
    {
      "text": "The constant for running and jogging.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.healthkit/documentation/HealthKit",
        "doc://com.apple.healthkit/documentation/HealthKit/HKWorkoutActivityType"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.healthkit/documentation/HealthKit/HKWorkoutActivityType/running"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@HKWorkoutActivityType@HKWorkoutActivityTypeRunning",
    "fragments": [
      {
        "kind": "keyword",
        "text": "case"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "running"
      }
    ],
    "modules": [
      {
        "name": "HealthKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "HKWorkoutActivityTypeRunning"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "8.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "8.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.0",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.0",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "2.0",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Case",
    "symbolKind": "case",
    "title": "HKWorkoutActivityType.running"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "case"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "running"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "kind": "mentions",
      "mentions": [
        "doc://com.apple.healthkit/documentation/HealthKit/dividing-a-healthkit-workout-into-activities",
        "doc://com.apple.healthkit/documentation/HealthKit/receiving-downhill-skiing-and-snowboarding-data"
      ]
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.healthkit/documentation/HealthKit": {
      "abstract": [
        {
          "text": "Access and share health and fitness data while maintaining the user’s privacy and control.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit",
      "kind": "symbol",
      "role": "collection",
      "title": "HealthKit",
      "type": "topic",
      "url": "/documentation/healthkit"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/HKWorkoutActivityType": {
      "abstract": [
        {
          "text": "The type of activity performed during a workout.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "HKWorkoutActivityType"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKWorkoutActivityType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HKWorkoutActivityType"
        }
      ],
      "role": "symbol",
      "title": "HKWorkoutActivityType",
      "type": "topic",
      "url": "/documentation/healthkit/hkworkoutactivitytype"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/HKWorkoutActivityType/cooldown": {
      "abstract": [
        {
          "text": "The constant for low intensity stretching and mobility exercises following a more vigorous workout.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "cooldown"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKWorkoutActivityType/cooldown",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HKWorkoutActivityTypeCooldown"
        }
      ],
      "role": "symbol",
      "title": "HKWorkoutActivityType.cooldown",
      "type": "topic",
      "url": "/documentation/healthkit/hkworkoutactivitytype/cooldown"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/HKWorkoutActivityType/coreTraining": {
      "abstract": [
        {
          "text": "The constant for core training.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "coreTraining"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKWorkoutActivityType/coreTraining",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HKWorkoutActivityTypeCoreTraining"
        }
      ],
      "role": "symbol",
      "title": "HKWorkoutActivityType.coreTraining",
      "type": "topic",
      "url": "/documentation/healthkit/hkworkoutactivitytype/coretraining"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/HKWorkoutActivityType/crossTraining": {
      "abstract": [
        {
          "text": "The constant for exercise that includes any mixture of cardio, strength, and/or flexibility training.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "crossTraining"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKWorkoutActivityType/crossTraining",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HKWorkoutActivityTypeCrossTraining"
        }
      ],
      "role": "symbol",
      "title": "HKWorkoutActivityType.crossTraining",
      "type": "topic",
      "url": "/documentation/healthkit/hkworkoutactivitytype/crosstraining"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/HKWorkoutActivityType/cycling": {
      "abstract": [
        {
          "text": "The constant for cycling.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "cycling"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKWorkoutActivityType/cycling",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HKWorkoutActivityTypeCycling"
        }
      ],
      "role": "symbol",
      "title": "HKWorkoutActivityType.cycling",
      "type": "topic",
      "url": "/documentation/healthkit/hkworkoutactivitytype/cycling"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/HKWorkoutActivityType/elliptical": {
      "abstract": [
        {
          "text": "The constant for workouts on an elliptical machine.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "elliptical"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKWorkoutActivityType/elliptical",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HKWorkoutActivityTypeElliptical"
        }
      ],
      "role": "symbol",
      "title": "HKWorkoutActivityType.elliptical",
      "type": "topic",
      "url": "/documentation/healthkit/hkworkoutactivitytype/elliptical"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/HKWorkoutActivityType/flexibility": {
      "abstract": [
        {
          "text": "The constant for a flexibility workout.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "flexibility"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKWorkoutActivityType/flexibility",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HKWorkoutActivityTypeFlexibility"
        }
      ],
      "role": "symbol",
      "title": "HKWorkoutActivityType.flexibility",
      "type": "topic",
      "url": "/documentation/healthkit/hkworkoutactivitytype/flexibility"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/HKWorkoutActivityType/functionalStrengthTraining": {
      "abstract": [
        {
          "text": "The constant for strength training, primarily with free weights and body weight.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "functionalStrengthTraining"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKWorkoutActivityType/functionalStrengthTraining",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HKWorkoutActivityTypeFunctionalStrengthTraining"
        }
      ],
      "role": "symbol",
      "title": "HKWorkoutActivityType.functionalStrengthTraining",
      "type": "topic",
      "url": "/documentation/healthkit/hkworkoutactivitytype/functionalstrengthtraining"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/HKWorkoutActivityType/handCycling": {
      "abstract": [
        {
          "text": "The constant for hand cycling.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "handCycling"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKWorkoutActivityType/handCycling",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HKWorkoutActivityTypeHandCycling"
        }
      ],
      "role": "symbol",
      "title": "HKWorkoutActivityType.handCycling",
      "type": "topic",
      "url": "/documentation/healthkit/hkworkoutactivitytype/handcycling"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/HKWorkoutActivityType/highIntensityIntervalTraining": {
      "abstract": [
        {
          "text": "The constant for high intensity interval training.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "highIntensityIntervalTraining"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKWorkoutActivityType/highIntensityIntervalTraining",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HKWorkoutActivityTypeHighIntensityIntervalTraining"
        }
      ],
      "role": "symbol",
      "title": "HKWorkoutActivityType.highIntensityIntervalTraining",
      "type": "topic",
      "url": "/documentation/healthkit/hkworkoutactivitytype/highintensityintervaltraining"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/HKWorkoutActivityType/mixedCardio": {
      "abstract": [
        {
          "text": "The constant for workouts that mix a variety of cardio exercise machines or modalities.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "mixedCardio"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKWorkoutActivityType/mixedCardio",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HKWorkoutActivityTypeMixedCardio"
        }
      ],
      "role": "symbol",
      "title": "HKWorkoutActivityType.mixedCardio",
      "type": "topic",
      "url": "/documentation/healthkit/hkworkoutactivitytype/mixedcardio"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/HKWorkoutActivityType/preparationAndRecovery": {
      "abstract": [
        {
          "text": "The constant for warm-up and therapeutic activities like foam rolling and stretching.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "preparationAndRecovery"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKWorkoutActivityType/preparationAndRecovery",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HKWorkoutActivityTypePreparationAndRecovery"
        }
      ],
      "role": "symbol",
      "title": "HKWorkoutActivityType.preparationAndRecovery",
      "type": "topic",
      "url": "/documentation/healthkit/hkworkoutactivitytype/preparationandrecovery"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/HKWorkoutActivityType/running": {
      "abstract": [
        {
          "text": "The constant for running and jogging.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "running"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKWorkoutActivityType/running",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HKWorkoutActivityTypeRunning"
        }
      ],
      "role": "symbol",
      "title": "HKWorkoutActivityType.running",
      "type": "topic",
      "url": "/documentation/healthkit/hkworkoutactivitytype/running"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/HKWorkoutActivityType/traditionalStrengthTraining": {
      "abstract": [
        {
          "text": "The constant for strength training exercises primarily using machines or free weights.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "traditionalStrengthTraining"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKWorkoutActivityType/traditionalStrengthTraining",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HKWorkoutActivityTypeTraditionalStrengthTraining"
        }
      ],
      "role": "symbol",
      "title": "HKWorkoutActivityType.traditionalStrengthTraining",
      "type": "topic",
      "url": "/documentation/healthkit/hkworkoutactivitytype/traditionalstrengthtraining"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/HKWorkoutActivityType/walking": {
      "abstract": [
        {
          "text": "The constant for walking.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "walking"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKWorkoutActivityType/walking",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HKWorkoutActivityTypeWalking"
        }
      ],
      "role": "symbol",
      "title": "HKWorkoutActivityType.walking",
      "type": "topic",
      "url": "/documentation/healthkit/hkworkoutactivitytype/walking"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/HKWorkoutActivityType/wheelchairRunPace": {
      "abstract": [
        {
          "text": "The constant for wheelchair workout at running pace.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "wheelchairRunPace"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKWorkoutActivityType/wheelchairRunPace",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HKWorkoutActivityTypeWheelchairRunPace"
        }
      ],
      "role": "symbol",
      "title": "HKWorkoutActivityType.wheelchairRunPace",
      "type": "topic",
      "url": "/documentation/healthkit/hkworkoutactivitytype/wheelchairrunpace"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/HKWorkoutActivityType/wheelchairWalkPace": {
      "abstract": [
        {
          "text": "The constant for a wheelchair workout at walking pace.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "wheelchairWalkPace"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKWorkoutActivityType/wheelchairWalkPace",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HKWorkoutActivityTypeWheelchairWalkPace"
        }
      ],
      "role": "symbol",
      "title": "HKWorkoutActivityType.wheelchairWalkPace",
      "type": "topic",
      "url": "/documentation/healthkit/hkworkoutactivitytype/wheelchairwalkpace"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/dividing-a-healthkit-workout-into-activities": {
      "abstract": [
        {
          "text": "Partition multisport and interval workouts into activities that represent the different parts of the workout.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/dividing-a-healthkit-workout-into-activities",
      "kind": "article",
      "role": "article",
      "title": "Dividing a HealthKit workout into activities",
      "type": "topic",
      "url": "/documentation/healthkit/dividing-a-healthkit-workout-into-activities"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/receiving-downhill-skiing-and-snowboarding-data": {
      "abstract": [
        {
          "text": "Receive segments and distance samples during downhill skiing and snowboarding workout sessions.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/receiving-downhill-skiing-and-snowboarding-data",
      "kind": "article",
      "role": "article",
      "title": "Receiving Downhill Skiing and Snowboarding Data",
      "type": "topic",
      "url": "/documentation/healthkit/receiving-downhill-skiing-and-snowboarding-data"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Exercise-and-fitness",
      "generated": true,
      "identifiers": [
        "doc://com.apple.healthkit/documentation/HealthKit/HKWorkoutActivityType/preparationAndRecovery",
        "doc://com.apple.healthkit/documentation/HealthKit/HKWorkoutActivityType/flexibility",
        "doc://com.apple.healthkit/documentation/HealthKit/HKWorkoutActivityType/cooldown",
        "doc://com.apple.healthkit/documentation/HealthKit/HKWorkoutActivityType/walking",
        "doc://com.apple.healthkit/documentation/HealthKit/HKWorkoutActivityType/wheelchairWalkPace",
        "doc://com.apple.healthkit/documentation/HealthKit/HKWorkoutActivityType/wheelchairRunPace",
        "doc://com.apple.healthkit/documentation/HealthKit/HKWorkoutActivityType/cycling",
        "doc://com.apple.healthkit/documentation/HealthKit/HKWorkoutActivityType/handCycling",
        "doc://com.apple.healthkit/documentation/HealthKit/HKWorkoutActivityType/coreTraining",
        "doc://com.apple.healthkit/documentation/HealthKit/HKWorkoutActivityType/elliptical",
        "doc://com.apple.healthkit/documentation/HealthKit/HKWorkoutActivityType/functionalStrengthTraining",
        "doc://com.apple.healthkit/documentation/HealthKit/HKWorkoutActivityType/traditionalStrengthTraining",
        "doc://com.apple.healthkit/documentation/HealthKit/HKWorkoutActivityType/crossTraining",
        "doc://com.apple.healthkit/documentation/HealthKit/HKWorkoutActivityType/mixedCardio",
        "doc://com.apple.healthkit/documentation/HealthKit/HKWorkoutActivityType/highIntensityIntervalTraining"
      ],
      "title": "Exercise and fitness"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "8.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "8.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.0",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.0",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "2.0",
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration Case"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "HKWorkoutActivityTypeRunning"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "case"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HKWorkoutActivityTypeRunning"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.healthkit/documentation/HealthKit",
                "doc://com.apple.healthkit/documentation/HealthKit/HKWorkoutActivityType"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Exercise-and-fitness",
              "generated": true,
              "identifiers": [
                "doc://com.apple.healthkit/documentation/HealthKit/HKWorkoutActivityType/preparationAndRecovery",
                "doc://com.apple.healthkit/documentation/HealthKit/HKWorkoutActivityType/flexibility",
                "doc://com.apple.healthkit/documentation/HealthKit/HKWorkoutActivityType/cooldown",
                "doc://com.apple.healthkit/documentation/HealthKit/HKWorkoutActivityType/walking",
                "doc://com.apple.healthkit/documentation/HealthKit/HKWorkoutActivityType/wheelchairWalkPace",
                "doc://com.apple.healthkit/documentation/HealthKit/HKWorkoutActivityType/wheelchairRunPace",
                "doc://com.apple.healthkit/documentation/HealthKit/HKWorkoutActivityType/cycling",
                "doc://com.apple.healthkit/documentation/HealthKit/HKWorkoutActivityType/handCycling",
                "doc://com.apple.healthkit/documentation/HealthKit/HKWorkoutActivityType/coreTraining",
                "doc://com.apple.healthkit/documentation/HealthKit/HKWorkoutActivityType/elliptical",
                "doc://com.apple.healthkit/documentation/HealthKit/HKWorkoutActivityType/functionalStrengthTraining",
                "doc://com.apple.healthkit/documentation/HealthKit/HKWorkoutActivityType/traditionalStrengthTraining",
                "doc://com.apple.healthkit/documentation/HealthKit/HKWorkoutActivityType/crossTraining",
                "doc://com.apple.healthkit/documentation/HealthKit/HKWorkoutActivityType/mixedCardio",
                "doc://com.apple.healthkit/documentation/HealthKit/HKWorkoutActivityType/highIntensityIntervalTraining"
              ],
              "title": "Exercise and fitness"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "identifier",
                    "text": "HKWorkoutActivityTypeRunning"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKWorkoutActivityType~1mixedCardio/title",
          "value": "HKWorkoutActivityTypeMixedCardio"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKWorkoutActivityType~1mixedCardio/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HKWorkoutActivityTypeMixedCardio"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKWorkoutActivityType~1highIntensityIntervalTraining/title",
          "value": "HKWorkoutActivityTypeHighIntensityIntervalTraining"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKWorkoutActivityType~1highIntensityIntervalTraining/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HKWorkoutActivityTypeHighIntensityIntervalTraining"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKWorkoutActivityType~1traditionalStrengthTraining/title",
          "value": "HKWorkoutActivityTypeTraditionalStrengthTraining"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKWorkoutActivityType~1traditionalStrengthTraining/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HKWorkoutActivityTypeTraditionalStrengthTraining"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKWorkoutActivityType~1cooldown/title",
          "value": "HKWorkoutActivityTypeCooldown"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKWorkoutActivityType~1cooldown/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HKWorkoutActivityTypeCooldown"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKWorkoutActivityType~1running/title",
          "value": "HKWorkoutActivityTypeRunning"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKWorkoutActivityType~1running/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HKWorkoutActivityTypeRunning"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKWorkoutActivityType~1flexibility/title",
          "value": "HKWorkoutActivityTypeFlexibility"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKWorkoutActivityType~1flexibility/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HKWorkoutActivityTypeFlexibility"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKWorkoutActivityType~1wheelchairRunPace/title",
          "value": "HKWorkoutActivityTypeWheelchairRunPace"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKWorkoutActivityType~1wheelchairRunPace/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HKWorkoutActivityTypeWheelchairRunPace"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKWorkoutActivityType~1functionalStrengthTraining/title",
          "value": "HKWorkoutActivityTypeFunctionalStrengthTraining"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKWorkoutActivityType~1functionalStrengthTraining/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HKWorkoutActivityTypeFunctionalStrengthTraining"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKWorkoutActivityType~1walking/title",
          "value": "HKWorkoutActivityTypeWalking"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKWorkoutActivityType~1walking/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HKWorkoutActivityTypeWalking"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKWorkoutActivityType~1coreTraining/title",
          "value": "HKWorkoutActivityTypeCoreTraining"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKWorkoutActivityType~1coreTraining/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HKWorkoutActivityTypeCoreTraining"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKWorkoutActivityType~1elliptical/title",
          "value": "HKWorkoutActivityTypeElliptical"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKWorkoutActivityType~1elliptical/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HKWorkoutActivityTypeElliptical"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKWorkoutActivityType/title",
          "value": "HKWorkoutActivityType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKWorkoutActivityType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HKWorkoutActivityType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKWorkoutActivityType/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "HKWorkoutActivityType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKWorkoutActivityType~1handCycling/title",
          "value": "HKWorkoutActivityTypeHandCycling"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKWorkoutActivityType~1handCycling/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HKWorkoutActivityTypeHandCycling"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKWorkoutActivityType~1wheelchairWalkPace/title",
          "value": "HKWorkoutActivityTypeWheelchairWalkPace"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKWorkoutActivityType~1wheelchairWalkPace/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HKWorkoutActivityTypeWheelchairWalkPace"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKWorkoutActivityType~1cycling/title",
          "value": "HKWorkoutActivityTypeCycling"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKWorkoutActivityType~1cycling/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HKWorkoutActivityTypeCycling"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKWorkoutActivityType~1preparationAndRecovery/title",
          "value": "HKWorkoutActivityTypePreparationAndRecovery"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKWorkoutActivityType~1preparationAndRecovery/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HKWorkoutActivityTypePreparationAndRecovery"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKWorkoutActivityType~1crossTraining/title",
          "value": "HKWorkoutActivityTypeCrossTraining"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKWorkoutActivityType~1crossTraining/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HKWorkoutActivityTypeCrossTraining"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/healthkit/hkworkoutactivitytype/running"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/healthkit/hkworkoutactivitytype/running"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
