{
  "abstract": [
    {
      "text": "The constant for snowboarding.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.healthkit/documentation/HealthKit",
        "doc://com.apple.healthkit/documentation/HealthKit/HKWorkoutActivityType"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.healthkit/documentation/HealthKit/HKWorkoutActivityType/snowboarding"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@HKWorkoutActivityType@HKWorkoutActivityTypeSnowboarding",
    "fragments": [
      {
        "kind": "keyword",
        "text": "case"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "snowboarding"
      }
    ],
    "modules": [
      {
        "name": "HealthKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "HKWorkoutActivityTypeSnowboarding"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.0",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.0",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "3.0",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Case",
    "symbolKind": "case",
    "title": "HKWorkoutActivityType.snowboarding"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "case"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "snowboarding"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "kind": "mentions",
      "mentions": [
        "doc://com.apple.healthkit/documentation/HealthKit/receiving-downhill-skiing-and-snowboarding-data"
      ]
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.healthkit/documentation/HealthKit": {
      "abstract": [
        {
          "text": "Access and share health and fitness data while maintaining the user’s privacy and control.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit",
      "kind": "symbol",
      "role": "collection",
      "title": "HealthKit",
      "type": "topic",
      "url": "/documentation/healthkit"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/HKWorkoutActivityType": {
      "abstract": [
        {
          "text": "The type of activity performed during a workout.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "HKWorkoutActivityType"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKWorkoutActivityType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HKWorkoutActivityType"
        }
      ],
      "role": "symbol",
      "title": "HKWorkoutActivityType",
      "type": "topic",
      "url": "/documentation/healthkit/hkworkoutactivitytype"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/HKWorkoutActivityType/crossCountrySkiing": {
      "abstract": [
        {
          "text": "The constant for cross country skiing.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "crossCountrySkiing"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKWorkoutActivityType/crossCountrySkiing",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HKWorkoutActivityTypeCrossCountrySkiing"
        }
      ],
      "role": "symbol",
      "title": "HKWorkoutActivityType.crossCountrySkiing",
      "type": "topic",
      "url": "/documentation/healthkit/hkworkoutactivitytype/crosscountryskiing"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/HKWorkoutActivityType/curling": {
      "abstract": [
        {
          "text": "The constant for curling.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "curling"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKWorkoutActivityType/curling",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HKWorkoutActivityTypeCurling"
        }
      ],
      "role": "symbol",
      "title": "HKWorkoutActivityType.curling",
      "type": "topic",
      "url": "/documentation/healthkit/hkworkoutactivitytype/curling"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/HKWorkoutActivityType/downhillSkiing": {
      "abstract": [
        {
          "text": "The constant for downhill skiing.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "downhillSkiing"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKWorkoutActivityType/downhillSkiing",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HKWorkoutActivityTypeDownhillSkiing"
        }
      ],
      "role": "symbol",
      "title": "HKWorkoutActivityType.downhillSkiing",
      "type": "topic",
      "url": "/documentation/healthkit/hkworkoutactivitytype/downhillskiing"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/HKWorkoutActivityType/skatingSports": {
      "abstract": [
        {
          "text": "The constant for skating activities, including ice skating, speed skating, inline skating, and skateboarding.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "skatingSports"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKWorkoutActivityType/skatingSports",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HKWorkoutActivityTypeSkatingSports"
        }
      ],
      "role": "symbol",
      "title": "HKWorkoutActivityType.skatingSports",
      "type": "topic",
      "url": "/documentation/healthkit/hkworkoutactivitytype/skatingsports"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/HKWorkoutActivityType/snowSports": {
      "abstract": [
        {
          "text": "The constant for a variety of snow sports, including sledding, snowmobiling, or building a snowman.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "snowSports"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKWorkoutActivityType/snowSports",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HKWorkoutActivityTypeSnowSports"
        }
      ],
      "role": "symbol",
      "title": "HKWorkoutActivityType.snowSports",
      "type": "topic",
      "url": "/documentation/healthkit/hkworkoutactivitytype/snowsports"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/HKWorkoutActivityType/snowboarding": {
      "abstract": [
        {
          "text": "The constant for snowboarding.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "snowboarding"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKWorkoutActivityType/snowboarding",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HKWorkoutActivityTypeSnowboarding"
        }
      ],
      "role": "symbol",
      "title": "HKWorkoutActivityType.snowboarding",
      "type": "topic",
      "url": "/documentation/healthkit/hkworkoutactivitytype/snowboarding"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/receiving-downhill-skiing-and-snowboarding-data": {
      "abstract": [
        {
          "text": "Receive segments and distance samples during downhill skiing and snowboarding workout sessions.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/receiving-downhill-skiing-and-snowboarding-data",
      "kind": "article",
      "role": "article",
      "title": "Receiving Downhill Skiing and Snowboarding Data",
      "type": "topic",
      "url": "/documentation/healthkit/receiving-downhill-skiing-and-snowboarding-data"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Snow-and-ice-sports",
      "generated": true,
      "identifiers": [
        "doc://com.apple.healthkit/documentation/HealthKit/HKWorkoutActivityType/crossCountrySkiing",
        "doc://com.apple.healthkit/documentation/HealthKit/HKWorkoutActivityType/curling",
        "doc://com.apple.healthkit/documentation/HealthKit/HKWorkoutActivityType/downhillSkiing",
        "doc://com.apple.healthkit/documentation/HealthKit/HKWorkoutActivityType/snowSports",
        "doc://com.apple.healthkit/documentation/HealthKit/HKWorkoutActivityType/skatingSports"
      ],
      "title": "Snow and ice sports"
    }
  ],
  "topicSections": [
    {
      "anchor": "Monitoring-Downhill-Skiing-Workout-Sessions",
      "identifiers": [
        "doc://com.apple.healthkit/documentation/HealthKit/receiving-downhill-skiing-and-snowboarding-data"
      ],
      "title": "Monitoring Downhill Skiing Workout Sessions"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.0",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.0",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "3.0",
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration Case"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "HKWorkoutActivityTypeSnowboarding"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "case"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HKWorkoutActivityTypeSnowboarding"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.healthkit/documentation/HealthKit",
                "doc://com.apple.healthkit/documentation/HealthKit/HKWorkoutActivityType"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Monitoring-Downhill-Skiing-Workout-Sessions",
              "identifiers": [
                "doc://com.apple.healthkit/documentation/HealthKit/receiving-downhill-skiing-and-snowboarding-data"
              ],
              "title": "Monitoring Downhill Skiing Workout Sessions"
            }
          ]
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Snow-and-ice-sports",
              "generated": true,
              "identifiers": [
                "doc://com.apple.healthkit/documentation/HealthKit/HKWorkoutActivityType/crossCountrySkiing",
                "doc://com.apple.healthkit/documentation/HealthKit/HKWorkoutActivityType/curling",
                "doc://com.apple.healthkit/documentation/HealthKit/HKWorkoutActivityType/downhillSkiing",
                "doc://com.apple.healthkit/documentation/HealthKit/HKWorkoutActivityType/snowSports",
                "doc://com.apple.healthkit/documentation/HealthKit/HKWorkoutActivityType/skatingSports"
              ],
              "title": "Snow and ice sports"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "identifier",
                    "text": "HKWorkoutActivityTypeSnowboarding"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKWorkoutActivityType~1snowSports/title",
          "value": "HKWorkoutActivityTypeSnowSports"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKWorkoutActivityType~1snowSports/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HKWorkoutActivityTypeSnowSports"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKWorkoutActivityType/title",
          "value": "HKWorkoutActivityType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKWorkoutActivityType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HKWorkoutActivityType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKWorkoutActivityType/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "HKWorkoutActivityType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKWorkoutActivityType~1downhillSkiing/title",
          "value": "HKWorkoutActivityTypeDownhillSkiing"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKWorkoutActivityType~1downhillSkiing/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HKWorkoutActivityTypeDownhillSkiing"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKWorkoutActivityType~1skatingSports/title",
          "value": "HKWorkoutActivityTypeSkatingSports"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKWorkoutActivityType~1skatingSports/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HKWorkoutActivityTypeSkatingSports"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKWorkoutActivityType~1crossCountrySkiing/title",
          "value": "HKWorkoutActivityTypeCrossCountrySkiing"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKWorkoutActivityType~1crossCountrySkiing/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HKWorkoutActivityTypeCrossCountrySkiing"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKWorkoutActivityType~1snowboarding/title",
          "value": "HKWorkoutActivityTypeSnowboarding"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKWorkoutActivityType~1snowboarding/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HKWorkoutActivityTypeSnowboarding"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKWorkoutActivityType~1curling/title",
          "value": "HKWorkoutActivityTypeCurling"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKWorkoutActivityType~1curling/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HKWorkoutActivityTypeCurling"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/healthkit/hkworkoutactivitytype/snowboarding"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/healthkit/hkworkoutactivitytype/snowboarding"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
