{"abstract":[{"type":"text","text":"The connection timed out."}],"identifier":{"interfaceLanguage":"swift","url":"doc://com.apple.corebluetooth/documentation/CoreBluetooth/CBError-swift.struct/Code/connectionTimeout"},"metadata":{"roleHeading":"Case","title":"CBError.Code.connectionTimeout","navigatorTitle":[{"kind":"identifier","text":"CBErrorConnectionTimeout"}],"modules":[{"name":"Core Bluetooth"}],"platforms":[{"introducedAt":"6.0","deprecated":false,"beta":false,"name":"iOS","unavailable":false},{"introducedAt":"6.0","deprecated":false,"beta":false,"name":"iPadOS","unavailable":false},{"introducedAt":"13.1","deprecated":false,"beta":false,"name":"Mac Catalyst","unavailable":false},{"name":"macOS","unavailable":false,"introducedAt":"10.9","deprecated":false,"beta":false},{"name":"tvOS","unavailable":false,"introducedAt":"9.0","deprecated":false,"beta":false},{"name":"visionOS","unavailable":false,"introducedAt":"1.0","deprecated":false,"beta":false},{"name":"watchOS","unavailable":false,"introducedAt":"2.0","deprecated":false,"beta":false}],"symbolKind":"case","role":"symbol","externalID":"c:@E@CBError@CBErrorConnectionTimeout","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"connectionTimeout"}]},"sections":[],"schemaVersion":{"major":0,"minor":3,"patch":0},"primaryContentSections":[{"declarations":[{"platforms":["iOS","iPadOS","Mac Catalyst","macOS","tvOS","visionOS","watchOS"],"languages":["swift"],"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"connectionTimeout","kind":"identifier"}]}],"kind":"declarations"}],"variants":[{"paths":["/documentation/corebluetooth/cberror-swift.struct/code/connectiontimeout"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["/documentation/corebluetooth/cberror-swift.struct/code/connectiontimeout"],"traits":[{"interfaceLanguage":"occ"}]}],"kind":"symbol","seeAlsoSections":[{"generated":true,"anchor":"Error-Codes","title":"Error Codes","identifiers":["doc://com.apple.corebluetooth/documentation/CoreBluetooth/CBError-swift.struct/Code/unknown","doc://com.apple.corebluetooth/documentation/CoreBluetooth/CBError-swift.struct/Code/invalidParameters","doc://com.apple.corebluetooth/documentation/CoreBluetooth/CBError-swift.struct/Code/invalidHandle","doc://com.apple.corebluetooth/documentation/CoreBluetooth/CBError-swift.struct/Code/notConnected","doc://com.apple.corebluetooth/documentation/CoreBluetooth/CBError-swift.struct/Code/outOfSpace","doc://com.apple.corebluetooth/documentation/CoreBluetooth/CBError-swift.struct/Code/operationCancelled","doc://com.apple.corebluetooth/documentation/CoreBluetooth/CBError-swift.struct/Code/peripheralDisconnected","doc://com.apple.corebluetooth/documentation/CoreBluetooth/CBError-swift.struct/Code/uuidNotAllowed","doc://com.apple.corebluetooth/documentation/CoreBluetooth/CBError-swift.struct/Code/alreadyAdvertising","doc://com.apple.corebluetooth/documentation/CoreBluetooth/CBError-swift.struct/Code/connectionFailed","doc://com.apple.corebluetooth/documentation/CoreBluetooth/CBError-swift.struct/Code/connectionLimitReached","doc://com.apple.corebluetooth/documentation/CoreBluetooth/CBError-swift.struct/Code/operationNotSupported","doc://com.apple.corebluetooth/documentation/CoreBluetooth/CBError-swift.struct/Code/unknownDevice","doc://com.apple.corebluetooth/documentation/CoreBluetooth/CBError-swift.struct/Code/unkownDevice"]}],"hierarchy":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.corebluetooth/documentation/CoreBluetooth","doc://com.apple.corebluetooth/documentation/CoreBluetooth/CBError-swift.struct","doc://com.apple.corebluetooth/documentation/CoreBluetooth/CBError-swift.struct/Code"]]},"references":{"doc://com.apple.corebluetooth/documentation/CoreBluetooth/CBError-swift.struct/Code/connectionTimeout":{"type":"topic","navigatorTitle":[{"kind":"identifier","text":"CBErrorConnectionTimeout"}],"role":"symbol","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"connectionTimeout"}],"abstract":[{"type":"text","text":"The connection timed out."}],"kind":"symbol","identifier":"doc://com.apple.corebluetooth/documentation/CoreBluetooth/CBError-swift.struct/Code/connectionTimeout","title":"CBError.Code.connectionTimeout","url":"/documentation/corebluetooth/cberror-swift.struct/code/connectiontimeout"},"doc://com.apple.corebluetooth/documentation/CoreBluetooth/CBError-swift.struct/Code/connectionLimitReached":{"type":"topic","url":"/documentation/corebluetooth/cberror-swift.struct/code/connectionlimitreached","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"connectionLimitReached","kind":"identifier"}],"abstract":[{"text":"The device already has the maximum number of connections.","type":"text"}],"identifier":"doc://com.apple.corebluetooth/documentation/CoreBluetooth/CBError-swift.struct/Code/connectionLimitReached","title":"CBError.Code.connectionLimitReached","kind":"symbol","role":"symbol","navigatorTitle":[{"text":"CBErrorConnectionLimitReached","kind":"identifier"}]},"doc://com.apple.corebluetooth/documentation/CoreBluetooth/CBError-swift.struct/Code/alreadyAdvertising":{"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"text":"alreadyAdvertising","kind":"identifier"}],"role":"symbol","kind":"symbol","title":"CBError.Code.alreadyAdvertising","abstract":[{"text":"The peripheral is already advertising.","type":"text"}],"type":"topic","identifier":"doc://com.apple.corebluetooth/documentation/CoreBluetooth/CBError-swift.struct/Code/alreadyAdvertising","navigatorTitle":[{"text":"CBErrorAlreadyAdvertising","kind":"identifier"}],"url":"/documentation/corebluetooth/cberror-swift.struct/code/alreadyadvertising"},"doc://com.apple.corebluetooth/documentation/CoreBluetooth/CBError-swift.struct/Code":{"navigatorTitle":[{"kind":"identifier","text":"Code"}],"role":"symbol","type":"topic","url":"/documentation/corebluetooth/cberror-swift.struct/code","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"Code"}],"abstract":[{"text":"The codes for errors that Core Bluetooth returns during Bluetooth transactions.","type":"text"}],"identifier":"doc://com.apple.corebluetooth/documentation/CoreBluetooth/CBError-swift.struct/Code","title":"CBError.Code","kind":"symbol"},"doc://com.apple.corebluetooth/documentation/CoreBluetooth/CBError-swift.struct/Code/notConnected":{"identifier":"doc://com.apple.corebluetooth/documentation/CoreBluetooth/CBError-swift.struct/Code/notConnected","navigatorTitle":[{"text":"CBErrorNotConnected","kind":"identifier"}],"title":"CBError.Code.notConnected","abstract":[{"type":"text","text":"The device isn’t currently connected."}],"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"notConnected","kind":"identifier"}],"url":"/documentation/corebluetooth/cberror-swift.struct/code/notconnected","type":"topic","role":"symbol","kind":"symbol"},"doc://com.apple.corebluetooth/documentation/CoreBluetooth/CBError-swift.struct/Code/operationNotSupported":{"type":"topic","navigatorTitle":[{"kind":"identifier","text":"CBErrorOperationNotSupported"}],"role":"symbol","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"operationNotSupported"}],"abstract":[{"type":"text","text":"The operation isn’t supported."}],"kind":"symbol","identifier":"doc://com.apple.corebluetooth/documentation/CoreBluetooth/CBError-swift.struct/Code/operationNotSupported","title":"CBError.Code.operationNotSupported","url":"/documentation/corebluetooth/cberror-swift.struct/code/operationnotsupported"},"doc://com.apple.corebluetooth/documentation/CoreBluetooth/CBError-swift.struct/Code/invalidParameters":{"type":"topic","navigatorTitle":[{"kind":"identifier","text":"CBErrorInvalidParameters"}],"role":"symbol","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"invalidParameters"}],"abstract":[{"text":"The specified parameters are invalid.","type":"text"}],"kind":"symbol","identifier":"doc://com.apple.corebluetooth/documentation/CoreBluetooth/CBError-swift.struct/Code/invalidParameters","title":"CBError.Code.invalidParameters","url":"/documentation/corebluetooth/cberror-swift.struct/code/invalidparameters"},"doc://com.apple.corebluetooth/documentation/CoreBluetooth/CBError-swift.struct/Code/unkownDevice":{"identifier":"doc://com.apple.corebluetooth/documentation/CoreBluetooth/CBError-swift.struct/Code/unkownDevice","navigatorTitle":[{"text":"CBErrorUnkownDevice","kind":"identifier"}],"title":"CBError.Code.unkownDevice","abstract":[{"text":"A misspelled version of the unknown device error code.","type":"text"}],"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"unkownDevice","kind":"identifier"}],"url":"/documentation/corebluetooth/cberror-swift.struct/code/unkowndevice","type":"topic","role":"symbol","kind":"symbol","deprecated":true},"doc://com.apple.corebluetooth/documentation/CoreBluetooth/CBError-swift.struct/Code/peripheralDisconnected":{"identifier":"doc://com.apple.corebluetooth/documentation/CoreBluetooth/CBError-swift.struct/Code/peripheralDisconnected","navigatorTitle":[{"text":"CBErrorPeripheralDisconnected","kind":"identifier"}],"title":"CBError.Code.peripheralDisconnected","abstract":[{"text":"The peripheral disconnected.","type":"text"}],"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"peripheralDisconnected","kind":"identifier"}],"url":"/documentation/corebluetooth/cberror-swift.struct/code/peripheraldisconnected","type":"topic","role":"symbol","kind":"symbol"},"doc://com.apple.corebluetooth/documentation/CoreBluetooth/CBError-swift.struct/Code/unknown":{"type":"topic","navigatorTitle":[{"kind":"identifier","text":"CBErrorUnknown"}],"role":"symbol","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"unknown"}],"abstract":[{"text":"An unknown error occurred.","type":"text"}],"kind":"symbol","identifier":"doc://com.apple.corebluetooth/documentation/CoreBluetooth/CBError-swift.struct/Code/unknown","title":"CBError.Code.unknown","url":"/documentation/corebluetooth/cberror-swift.struct/code/unknown"},"doc://com.apple.corebluetooth/documentation/CoreBluetooth/CBError-swift.struct/Code/operationCancelled":{"role":"symbol","identifier":"doc://com.apple.corebluetooth/documentation/CoreBluetooth/CBError-swift.struct/Code/operationCancelled","url":"/documentation/corebluetooth/cberror-swift.struct/code/operationcancelled","title":"CBError.Code.operationCancelled","navigatorTitle":[{"text":"CBErrorOperationCancelled","kind":"identifier"}],"abstract":[{"type":"text","text":"The error represents a canceled operation."}],"type":"topic","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"operationCancelled","kind":"identifier"}],"kind":"symbol"},"doc://com.apple.documentation/documentation/technologies":{"abstract":[{"text":"","type":"text"}],"identifier":"doc://com.apple.documentation/documentation/technologies","kind":"technologies","type":"topic","title":"Technologies","role":"overview","url":"/documentation/technologies"},"doc://com.apple.corebluetooth/documentation/CoreBluetooth/CBError-swift.struct/Code/uuidNotAllowed":{"identifier":"doc://com.apple.corebluetooth/documentation/CoreBluetooth/CBError-swift.struct/Code/uuidNotAllowed","title":"CBError.Code.uuidNotAllowed","url":"/documentation/corebluetooth/cberror-swift.struct/code/uuidnotallowed","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"uuidNotAllowed","kind":"identifier"}],"navigatorTitle":[{"text":"CBErrorUUIDNotAllowed","kind":"identifier"}],"kind":"symbol","abstract":[{"type":"text","text":"The specified UUID isn’t permitted."}],"type":"topic","role":"symbol"},"doc://com.apple.corebluetooth/documentation/CoreBluetooth":{"title":"Core Bluetooth","abstract":[{"text":"Communicate with Bluetooth low energy and BR/EDR (“Classic”) Devices.","type":"text"}],"url":"/documentation/corebluetooth","kind":"symbol","type":"topic","role":"collection","identifier":"doc://com.apple.corebluetooth/documentation/CoreBluetooth"},"doc://com.apple.corebluetooth/documentation/CoreBluetooth/CBError-c.enum/CBErrorUnknownDevice":{"type":"topic","url":"/documentation/corebluetooth/cberror-c.enum/cberrorunknowndevice","fragments":[{"text":"CBErrorUnknownDevice","kind":"identifier"}],"abstract":[{"text":"The device is unknown.","type":"text"}],"identifier":"doc://com.apple.corebluetooth/documentation/CoreBluetooth/CBError-c.enum/CBErrorUnknownDevice","title":"CBErrorUnknownDevice","kind":"symbol","role":"symbol"},"doc://com.apple.corebluetooth/documentation/CoreBluetooth/CBError-swift.struct/Code/unknownDevice":{"type":"topic","role":"symbol","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"unknownDevice"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SC7CBErrorLeV","text":"CBError"},{"kind":"text","text":"."},{"kind":"typeIdentifier","preciseIdentifier":"c:@E@CBError","text":"Code"}],"abstract":[{"text":"The device is unknown.","type":"text"}],"kind":"symbol","identifier":"doc://com.apple.corebluetooth/documentation/CoreBluetooth/CBError-swift.struct/Code/unknownDevice","title":"unknownDevice","url":"/documentation/corebluetooth/cberror-swift.struct/code/unknowndevice"},"doc://com.apple.corebluetooth/documentation/CoreBluetooth/CBError-swift.struct":{"fragments":[{"text":"struct","kind":"keyword"},{"kind":"text","text":" "},{"text":"CBError","kind":"identifier"}],"title":"CBError","type":"topic","identifier":"doc://com.apple.corebluetooth/documentation/CoreBluetooth/CBError-swift.struct","role":"symbol","abstract":[{"text":"An error that Core Bluetooth returns during Bluetooth transactions.","type":"text"}],"kind":"symbol","navigatorTitle":[{"text":"CBError","kind":"identifier"}],"url":"/documentation/corebluetooth/cberror-swift.struct"},"doc://com.apple.corebluetooth/documentation/CoreBluetooth/CBError-swift.struct/Code/outOfSpace":{"identifier":"doc://com.apple.corebluetooth/documentation/CoreBluetooth/CBError-swift.struct/Code/outOfSpace","navigatorTitle":[{"kind":"identifier","text":"CBErrorOutOfSpace"}],"title":"CBError.Code.outOfSpace","abstract":[{"type":"text","text":"The device has run out of space to complete the intended operation."}],"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"outOfSpace","kind":"identifier"}],"url":"/documentation/corebluetooth/cberror-swift.struct/code/outofspace","type":"topic","role":"symbol","kind":"symbol"},"doc://com.apple.corebluetooth/documentation/CoreBluetooth/CBError-swift.struct/Code/invalidHandle":{"identifier":"doc://com.apple.corebluetooth/documentation/CoreBluetooth/CBError-swift.struct/Code/invalidHandle","navigatorTitle":[{"text":"CBErrorInvalidHandle","kind":"identifier"}],"title":"CBError.Code.invalidHandle","abstract":[{"text":"The specified attribute handle is invalid.","type":"text"}],"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"invalidHandle","kind":"identifier"}],"url":"/documentation/corebluetooth/cberror-swift.struct/code/invalidhandle","type":"topic","role":"symbol","kind":"symbol"},"doc://com.apple.corebluetooth/documentation/CoreBluetooth/CBError-swift.struct/Code/connectionFailed":{"identifier":"doc://com.apple.corebluetooth/documentation/CoreBluetooth/CBError-swift.struct/Code/connectionFailed","title":"CBError.Code.connectionFailed","url":"/documentation/corebluetooth/cberror-swift.struct/code/connectionfailed","fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"connectionFailed"}],"navigatorTitle":[{"kind":"identifier","text":"CBErrorConnectionFailed"}],"kind":"symbol","abstract":[{"type":"text","text":"The connection failed."}],"type":"topic","role":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"/identifier/interfaceLanguage","value":"occ"},{"value":[{"name":"iOS","deprecated":false,"unavailable":false,"beta":false,"introducedAt":"6.0"},{"name":"iPadOS","deprecated":false,"unavailable":false,"beta":false,"introducedAt":"6.0"},{"name":"Mac Catalyst","deprecated":false,"unavailable":false,"beta":false,"introducedAt":"13.1"},{"name":"macOS","unavailable":false,"introducedAt":"10.9","deprecated":false,"beta":false},{"name":"tvOS","unavailable":false,"introducedAt":"9.0","deprecated":false,"beta":false},{"name":"visionOS","unavailable":false,"introducedAt":"1.0","deprecated":false,"beta":false},{"name":"watchOS","unavailable":false,"introducedAt":"2.0","deprecated":false,"beta":false}],"op":"replace","path":"/metadata/platforms"},{"value":"Enumeration Case","op":"replace","path":"/metadata/roleHeading"},{"value":"CBErrorConnectionTimeout","path":"/metadata/title","op":"replace"},{"value":"case","path":"/metadata/symbolKind","op":"replace"},{"value":[{"text":"CBErrorConnectionTimeout","kind":"identifier"}],"path":"/metadata/fragments","op":"replace"},{"value":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.corebluetooth/documentation/CoreBluetooth","doc://com.apple.corebluetooth/documentation/CoreBluetooth/CBError-swift.struct/Code"]]},"path":"/hierarchy","op":"replace"},{"value":null,"path":"/topicSections","op":"add"},{"op":"add","value":null,"path":"/relationshipsSections"},{"op":"replace","value":[{"anchor":"Error-Codes","identifiers":["doc://com.apple.corebluetooth/documentation/CoreBluetooth/CBError-swift.struct/Code/unknown","doc://com.apple.corebluetooth/documentation/CoreBluetooth/CBError-swift.struct/Code/invalidParameters","doc://com.apple.corebluetooth/documentation/CoreBluetooth/CBError-swift.struct/Code/invalidHandle","doc://com.apple.corebluetooth/documentation/CoreBluetooth/CBError-swift.struct/Code/notConnected","doc://com.apple.corebluetooth/documentation/CoreBluetooth/CBError-swift.struct/Code/outOfSpace","doc://com.apple.corebluetooth/documentation/CoreBluetooth/CBError-swift.struct/Code/operationCancelled","doc://com.apple.corebluetooth/documentation/CoreBluetooth/CBError-swift.struct/Code/peripheralDisconnected","doc://com.apple.corebluetooth/documentation/CoreBluetooth/CBError-swift.struct/Code/uuidNotAllowed","doc://com.apple.corebluetooth/documentation/CoreBluetooth/CBError-swift.struct/Code/alreadyAdvertising","doc://com.apple.corebluetooth/documentation/CoreBluetooth/CBError-swift.struct/Code/connectionFailed","doc://com.apple.corebluetooth/documentation/CoreBluetooth/CBError-swift.struct/Code/connectionLimitReached","doc://com.apple.corebluetooth/documentation/CoreBluetooth/CBError-swift.struct/Code/operationNotSupported","doc://com.apple.corebluetooth/documentation/CoreBluetooth/CBError-c.enum/CBErrorUnknownDevice","doc://com.apple.corebluetooth/documentation/CoreBluetooth/CBError-swift.struct/Code/unkownDevice"],"title":"Error Codes","generated":true}],"path":"/seeAlsoSections"},{"op":"replace","value":{"declarations":[{"tokens":[{"text":"CBErrorConnectionTimeout","kind":"identifier"}],"languages":["occ"],"platforms":["iOS","iPadOS","Mac Catalyst","macOS","tvOS","visionOS","watchOS"]}],"kind":"declarations"},"path":"/primaryContentSections/0"},{"value":"CBErrorConnectionTimeout","path":"/references/doc:~1~1com.apple.corebluetooth~1documentation~1CoreBluetooth~1CBError-swift.struct~1Code~1connectionTimeout/title","op":"replace"},{"value":[{"text":"CBErrorConnectionTimeout","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.corebluetooth~1documentation~1CoreBluetooth~1CBError-swift.struct~1Code~1connectionTimeout/fragments","op":"replace"},{"value":"CBErrorConnectionLimitReached","path":"/references/doc:~1~1com.apple.corebluetooth~1documentation~1CoreBluetooth~1CBError-swift.struct~1Code~1connectionLimitReached/title","op":"replace"},{"value":[{"text":"CBErrorConnectionLimitReached","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.corebluetooth~1documentation~1CoreBluetooth~1CBError-swift.struct~1Code~1connectionLimitReached/fragments","op":"replace"},{"value":"CBErrorAlreadyAdvertising","path":"/references/doc:~1~1com.apple.corebluetooth~1documentation~1CoreBluetooth~1CBError-swift.struct~1Code~1alreadyAdvertising/title","op":"replace"},{"value":[{"text":"CBErrorAlreadyAdvertising","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.corebluetooth~1documentation~1CoreBluetooth~1CBError-swift.struct~1Code~1alreadyAdvertising/fragments","op":"replace"},{"value":"CBError","path":"/references/doc:~1~1com.apple.corebluetooth~1documentation~1CoreBluetooth~1CBError-swift.struct~1Code/title","op":"replace"},{"value":[{"kind":"identifier","text":"CBError"}],"path":"/references/doc:~1~1com.apple.corebluetooth~1documentation~1CoreBluetooth~1CBError-swift.struct~1Code/fragments","op":"replace"},{"value":[{"text":"CBError","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.corebluetooth~1documentation~1CoreBluetooth~1CBError-swift.struct~1Code/navigatorTitle","op":"replace"},{"value":"CBErrorNotConnected","path":"/references/doc:~1~1com.apple.corebluetooth~1documentation~1CoreBluetooth~1CBError-swift.struct~1Code~1notConnected/title","op":"replace"},{"value":[{"kind":"identifier","text":"CBErrorNotConnected"}],"path":"/references/doc:~1~1com.apple.corebluetooth~1documentation~1CoreBluetooth~1CBError-swift.struct~1Code~1notConnected/fragments","op":"replace"},{"value":"CBErrorOperationNotSupported","path":"/references/doc:~1~1com.apple.corebluetooth~1documentation~1CoreBluetooth~1CBError-swift.struct~1Code~1operationNotSupported/title","op":"replace"},{"value":[{"kind":"identifier","text":"CBErrorOperationNotSupported"}],"path":"/references/doc:~1~1com.apple.corebluetooth~1documentation~1CoreBluetooth~1CBError-swift.struct~1Code~1operationNotSupported/fragments","op":"replace"},{"value":"CBErrorInvalidParameters","path":"/references/doc:~1~1com.apple.corebluetooth~1documentation~1CoreBluetooth~1CBError-swift.struct~1Code~1invalidParameters/title","op":"replace"},{"value":[{"text":"CBErrorInvalidParameters","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.corebluetooth~1documentation~1CoreBluetooth~1CBError-swift.struct~1Code~1invalidParameters/fragments","op":"replace"},{"value":"CBErrorUnkownDevice","path":"/references/doc:~1~1com.apple.corebluetooth~1documentation~1CoreBluetooth~1CBError-swift.struct~1Code~1unkownDevice/title","op":"replace"},{"value":[{"text":"CBErrorUnkownDevice","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.corebluetooth~1documentation~1CoreBluetooth~1CBError-swift.struct~1Code~1unkownDevice/fragments","op":"replace"},{"value":"CBErrorPeripheralDisconnected","path":"/references/doc:~1~1com.apple.corebluetooth~1documentation~1CoreBluetooth~1CBError-swift.struct~1Code~1peripheralDisconnected/title","op":"replace"},{"value":[{"kind":"identifier","text":"CBErrorPeripheralDisconnected"}],"path":"/references/doc:~1~1com.apple.corebluetooth~1documentation~1CoreBluetooth~1CBError-swift.struct~1Code~1peripheralDisconnected/fragments","op":"replace"},{"value":"CBErrorUnknown","path":"/references/doc:~1~1com.apple.corebluetooth~1documentation~1CoreBluetooth~1CBError-swift.struct~1Code~1unknown/title","op":"replace"},{"value":[{"kind":"identifier","text":"CBErrorUnknown"}],"path":"/references/doc:~1~1com.apple.corebluetooth~1documentation~1CoreBluetooth~1CBError-swift.struct~1Code~1unknown/fragments","op":"replace"},{"value":"CBErrorOperationCancelled","path":"/references/doc:~1~1com.apple.corebluetooth~1documentation~1CoreBluetooth~1CBError-swift.struct~1Code~1operationCancelled/title","op":"replace"},{"value":[{"kind":"identifier","text":"CBErrorOperationCancelled"}],"path":"/references/doc:~1~1com.apple.corebluetooth~1documentation~1CoreBluetooth~1CBError-swift.struct~1Code~1operationCancelled/fragments","op":"replace"},{"value":"CBErrorUUIDNotAllowed","path":"/references/doc:~1~1com.apple.corebluetooth~1documentation~1CoreBluetooth~1CBError-swift.struct~1Code~1uuidNotAllowed/title","op":"replace"},{"value":[{"text":"CBErrorUUIDNotAllowed","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.corebluetooth~1documentation~1CoreBluetooth~1CBError-swift.struct~1Code~1uuidNotAllowed/fragments","op":"replace"},{"value":"CBErrorOutOfSpace","path":"/references/doc:~1~1com.apple.corebluetooth~1documentation~1CoreBluetooth~1CBError-swift.struct~1Code~1outOfSpace/title","op":"replace"},{"value":[{"kind":"identifier","text":"CBErrorOutOfSpace"}],"path":"/references/doc:~1~1com.apple.corebluetooth~1documentation~1CoreBluetooth~1CBError-swift.struct~1Code~1outOfSpace/fragments","op":"replace"},{"value":"CBErrorInvalidHandle","path":"/references/doc:~1~1com.apple.corebluetooth~1documentation~1CoreBluetooth~1CBError-swift.struct~1Code~1invalidHandle/title","op":"replace"},{"value":[{"text":"CBErrorInvalidHandle","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.corebluetooth~1documentation~1CoreBluetooth~1CBError-swift.struct~1Code~1invalidHandle/fragments","op":"replace"},{"value":"CBErrorConnectionFailed","path":"/references/doc:~1~1com.apple.corebluetooth~1documentation~1CoreBluetooth~1CBError-swift.struct~1Code~1connectionFailed/title","op":"replace"},{"value":[{"text":"CBErrorConnectionFailed","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.corebluetooth~1documentation~1CoreBluetooth~1CBError-swift.struct~1Code~1connectionFailed/fragments","op":"replace"}]}],"legalNotices":{"copyright":"Copyright &copy; 2025 Apple Inc. All rights reserved.","termsOfUse":"https://www.apple.com/legal/internet-services/terms/site.html","privacyPolicy":"https://www.apple.com/privacy/privacy-policy"}}