{"sections":[],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["/documentation/corebluetooth/cberror-swift.struct/code/encryptiontimedout"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["/documentation/corebluetooth/cberror-swift.struct/code/encryptiontimedout"]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"kind":"symbol","primaryContentSections":[{"declarations":[{"platforms":["iOS","iPadOS","Mac Catalyst","macOS","tvOS","visionOS","watchOS"],"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"encryptionTimedOut","kind":"identifier"}],"languages":["swift"]}],"kind":"declarations"}],"metadata":{"role":"symbol","platforms":[{"unavailable":false,"name":"iOS","beta":false,"deprecated":false,"introducedAt":"13.4"},{"unavailable":false,"name":"iPadOS","beta":false,"deprecated":false,"introducedAt":"13.4"},{"unavailable":false,"name":"Mac Catalyst","beta":false,"deprecated":false,"introducedAt":"13.4"},{"unavailable":false,"name":"macOS","beta":false,"deprecated":false,"introducedAt":"10.15"},{"unavailable":false,"name":"tvOS","beta":false,"deprecated":false,"introducedAt":"13.4"},{"unavailable":false,"name":"visionOS","beta":false,"deprecated":false,"introducedAt":"1.0"},{"unavailable":false,"name":"watchOS","beta":false,"deprecated":false,"introducedAt":"6.2"}],"title":"CBError.Code.encryptionTimedOut","roleHeading":"Case","symbolKind":"case","modules":[{"name":"Core Bluetooth"}],"navigatorTitle":[{"text":"CBErrorEncryptionTimedOut","kind":"identifier"}],"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"encryptionTimedOut","kind":"identifier"}],"externalID":"c:@E@CBError@CBErrorEncryptionTimedOut"},"identifier":{"interfaceLanguage":"swift","url":"doc://com.apple.corebluetooth/documentation/CoreBluetooth/CBError-swift.struct/Code/encryptionTimedOut"},"hierarchy":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.corebluetooth/documentation/CoreBluetooth","doc://com.apple.corebluetooth/documentation/CoreBluetooth/CBError-swift.struct","doc://com.apple.corebluetooth/documentation/CoreBluetooth/CBError-swift.struct/Code"]]},"references":{"doc://com.apple.documentation/documentation/technologies":{"abstract":[{"text":"","type":"text"}],"identifier":"doc://com.apple.documentation/documentation/technologies","kind":"technologies","type":"topic","title":"Technologies","role":"overview","url":"/documentation/technologies"},"doc://com.apple.corebluetooth/documentation/CoreBluetooth/CBError-swift.struct/Code":{"navigatorTitle":[{"kind":"identifier","text":"Code"}],"role":"symbol","type":"topic","url":"/documentation/corebluetooth/cberror-swift.struct/code","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"Code"}],"abstract":[{"text":"The codes for errors that Core Bluetooth returns during Bluetooth transactions.","type":"text"}],"identifier":"doc://com.apple.corebluetooth/documentation/CoreBluetooth/CBError-swift.struct/Code","title":"CBError.Code","kind":"symbol"},"doc://com.apple.corebluetooth/documentation/CoreBluetooth":{"title":"Core Bluetooth","abstract":[{"text":"Communicate with Bluetooth low energy and BR/EDR (“Classic”) Devices.","type":"text"}],"url":"/documentation/corebluetooth","kind":"symbol","type":"topic","role":"collection","identifier":"doc://com.apple.corebluetooth/documentation/CoreBluetooth"},"doc://com.apple.corebluetooth/documentation/CoreBluetooth/CBError-swift.struct":{"fragments":[{"text":"struct","kind":"keyword"},{"kind":"text","text":" "},{"text":"CBError","kind":"identifier"}],"title":"CBError","type":"topic","identifier":"doc://com.apple.corebluetooth/documentation/CoreBluetooth/CBError-swift.struct","role":"symbol","abstract":[{"text":"An error that Core Bluetooth returns during Bluetooth transactions.","type":"text"}],"kind":"symbol","navigatorTitle":[{"text":"CBError","kind":"identifier"}],"url":"/documentation/corebluetooth/cberror-swift.struct"},"doc://com.apple.corebluetooth/documentation/CoreBluetooth/CBError-swift.struct/Code/encryptionTimedOut":{"kind":"symbol","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"CBErrorEncryptionTimedOut"}],"type":"topic","title":"CBError.Code.encryptionTimedOut","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"encryptionTimedOut"}],"url":"/documentation/corebluetooth/cberror-swift.struct/code/encryptiontimedout","identifier":"doc://com.apple.corebluetooth/documentation/CoreBluetooth/CBError-swift.struct/Code/encryptionTimedOut","abstract":[]}},"variantOverrides":[{"patch":[{"value":"occ","path":"/identifier/interfaceLanguage","op":"replace"},{"value":[{"deprecated":false,"name":"iOS","unavailable":false,"beta":false,"introducedAt":"13.4"},{"unavailable":false,"name":"iPadOS","beta":false,"deprecated":false,"introducedAt":"13.4"},{"unavailable":false,"name":"Mac Catalyst","beta":false,"deprecated":false,"introducedAt":"13.4"},{"unavailable":false,"name":"macOS","beta":false,"deprecated":false,"introducedAt":"10.15"},{"unavailable":false,"name":"tvOS","beta":false,"deprecated":false,"introducedAt":"13.4"},{"unavailable":false,"name":"visionOS","beta":false,"deprecated":false,"introducedAt":"1.0"},{"unavailable":false,"name":"watchOS","beta":false,"deprecated":false,"introducedAt":"6.2"}],"path":"/metadata/platforms","op":"replace"},{"value":"Enumeration Case","path":"/metadata/roleHeading","op":"replace"},{"op":"replace","value":"CBErrorEncryptionTimedOut","path":"/metadata/title"},{"op":"replace","value":"case","path":"/metadata/symbolKind"},{"op":"replace","value":[{"kind":"identifier","text":"CBErrorEncryptionTimedOut"}],"path":"/metadata/fragments"},{"path":"/hierarchy","op":"replace","value":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.corebluetooth/documentation/CoreBluetooth","doc://com.apple.corebluetooth/documentation/CoreBluetooth/CBError-swift.struct/Code"]]}},{"path":"/topicSections","op":"add","value":null},{"path":"/relationshipsSections","op":"add","value":null},{"path":"/seeAlsoSections","op":"add","value":null},{"path":"/primaryContentSections/0","op":"replace","value":{"declarations":[{"tokens":[{"kind":"identifier","text":"CBErrorEncryptionTimedOut"}],"platforms":["iOS","iPadOS","Mac Catalyst","macOS","tvOS","visionOS","watchOS"],"languages":["occ"]}],"kind":"declarations"}},{"path":"/references/doc:~1~1com.apple.corebluetooth~1documentation~1CoreBluetooth~1CBError-swift.struct~1Code/title","op":"replace","value":"CBError"},{"path":"/references/doc:~1~1com.apple.corebluetooth~1documentation~1CoreBluetooth~1CBError-swift.struct~1Code/fragments","op":"replace","value":[{"text":"CBError","kind":"identifier"}]},{"path":"/references/doc:~1~1com.apple.corebluetooth~1documentation~1CoreBluetooth~1CBError-swift.struct~1Code/navigatorTitle","op":"replace","value":[{"text":"CBError","kind":"identifier"}]},{"path":"/references/doc:~1~1com.apple.corebluetooth~1documentation~1CoreBluetooth~1CBError-swift.struct~1Code~1encryptionTimedOut/title","op":"replace","value":"CBErrorEncryptionTimedOut"},{"path":"/references/doc:~1~1com.apple.corebluetooth~1documentation~1CoreBluetooth~1CBError-swift.struct~1Code~1encryptionTimedOut/fragments","op":"replace","value":[{"kind":"identifier","text":"CBErrorEncryptionTimedOut"}]}],"traits":[{"interfaceLanguage":"occ"}]}],"legalNotices":{"copyright":"Copyright &copy; 2025 Apple Inc. All rights reserved.","termsOfUse":"https://www.apple.com/legal/internet-services/terms/site.html","privacyPolicy":"https://www.apple.com/privacy/privacy-policy"}}