{
  "abstract": [
    {
      "text": "The specified attribute handle is invalid.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.corebluetooth/documentation/CoreBluetooth",
        "doc://com.apple.corebluetooth/documentation/CoreBluetooth/CBError-swift.struct",
        "doc://com.apple.corebluetooth/documentation/CoreBluetooth/CBError-swift.struct/Code"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.corebluetooth/documentation/CoreBluetooth/CBError-swift.struct/Code/invalidHandle"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@CBError@CBErrorInvalidHandle",
    "fragments": [
      {
        "kind": "keyword",
        "text": "case"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "invalidHandle"
      }
    ],
    "modules": [
      {
        "name": "Core Bluetooth"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "CBErrorInvalidHandle"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "6.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "6.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.1",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.9",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "9.0",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "2.0",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Case",
    "symbolKind": "case",
    "title": "CBError.Code.invalidHandle"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "case"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "invalidHandle"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.corebluetooth/documentation/CoreBluetooth": {
      "abstract": [
        {
          "text": "Communicate with Bluetooth low energy and BR/EDR (“Classic”) Devices.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.corebluetooth/documentation/CoreBluetooth",
      "kind": "symbol",
      "role": "collection",
      "title": "Core Bluetooth",
      "type": "topic",
      "url": "/documentation/corebluetooth"
    },
    "doc://com.apple.corebluetooth/documentation/CoreBluetooth/CBError-c.enum/CBErrorUnknownDevice": {
      "abstract": [
        {
          "text": "The device is unknown.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "CBErrorUnknownDevice"
        }
      ],
      "identifier": "doc://com.apple.corebluetooth/documentation/CoreBluetooth/CBError-c.enum/CBErrorUnknownDevice",
      "kind": "symbol",
      "role": "symbol",
      "title": "CBErrorUnknownDevice",
      "type": "topic",
      "url": "/documentation/corebluetooth/cberror-c.enum/cberrorunknowndevice"
    },
    "doc://com.apple.corebluetooth/documentation/CoreBluetooth/CBError-swift.struct": {
      "abstract": [
        {
          "text": "An error that Core Bluetooth returns during Bluetooth transactions.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CBError"
        }
      ],
      "identifier": "doc://com.apple.corebluetooth/documentation/CoreBluetooth/CBError-swift.struct",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CBError"
        }
      ],
      "role": "symbol",
      "title": "CBError",
      "type": "topic",
      "url": "/documentation/corebluetooth/cberror-swift.struct"
    },
    "doc://com.apple.corebluetooth/documentation/CoreBluetooth/CBError-swift.struct/Code": {
      "abstract": [
        {
          "text": "The codes for errors that Core Bluetooth returns during Bluetooth transactions.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.corebluetooth/documentation/CoreBluetooth/CBError-swift.struct/Code",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "Code"
        }
      ],
      "role": "symbol",
      "title": "CBError.Code",
      "type": "topic",
      "url": "/documentation/corebluetooth/cberror-swift.struct/code"
    },
    "doc://com.apple.corebluetooth/documentation/CoreBluetooth/CBError-swift.struct/Code/alreadyAdvertising": {
      "abstract": [
        {
          "text": "The peripheral is already advertising.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "alreadyAdvertising"
        }
      ],
      "identifier": "doc://com.apple.corebluetooth/documentation/CoreBluetooth/CBError-swift.struct/Code/alreadyAdvertising",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CBErrorAlreadyAdvertising"
        }
      ],
      "role": "symbol",
      "title": "CBError.Code.alreadyAdvertising",
      "type": "topic",
      "url": "/documentation/corebluetooth/cberror-swift.struct/code/alreadyadvertising"
    },
    "doc://com.apple.corebluetooth/documentation/CoreBluetooth/CBError-swift.struct/Code/connectionFailed": {
      "abstract": [
        {
          "text": "The connection failed.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "connectionFailed"
        }
      ],
      "identifier": "doc://com.apple.corebluetooth/documentation/CoreBluetooth/CBError-swift.struct/Code/connectionFailed",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CBErrorConnectionFailed"
        }
      ],
      "role": "symbol",
      "title": "CBError.Code.connectionFailed",
      "type": "topic",
      "url": "/documentation/corebluetooth/cberror-swift.struct/code/connectionfailed"
    },
    "doc://com.apple.corebluetooth/documentation/CoreBluetooth/CBError-swift.struct/Code/connectionLimitReached": {
      "abstract": [
        {
          "text": "The device already has the maximum number of connections.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "connectionLimitReached"
        }
      ],
      "identifier": "doc://com.apple.corebluetooth/documentation/CoreBluetooth/CBError-swift.struct/Code/connectionLimitReached",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CBErrorConnectionLimitReached"
        }
      ],
      "role": "symbol",
      "title": "CBError.Code.connectionLimitReached",
      "type": "topic",
      "url": "/documentation/corebluetooth/cberror-swift.struct/code/connectionlimitreached"
    },
    "doc://com.apple.corebluetooth/documentation/CoreBluetooth/CBError-swift.struct/Code/connectionTimeout": {
      "abstract": [
        {
          "text": "The connection timed out.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "connectionTimeout"
        }
      ],
      "identifier": "doc://com.apple.corebluetooth/documentation/CoreBluetooth/CBError-swift.struct/Code/connectionTimeout",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CBErrorConnectionTimeout"
        }
      ],
      "role": "symbol",
      "title": "CBError.Code.connectionTimeout",
      "type": "topic",
      "url": "/documentation/corebluetooth/cberror-swift.struct/code/connectiontimeout"
    },
    "doc://com.apple.corebluetooth/documentation/CoreBluetooth/CBError-swift.struct/Code/invalidHandle": {
      "abstract": [
        {
          "text": "The specified attribute handle is invalid.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "invalidHandle"
        }
      ],
      "identifier": "doc://com.apple.corebluetooth/documentation/CoreBluetooth/CBError-swift.struct/Code/invalidHandle",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CBErrorInvalidHandle"
        }
      ],
      "role": "symbol",
      "title": "CBError.Code.invalidHandle",
      "type": "topic",
      "url": "/documentation/corebluetooth/cberror-swift.struct/code/invalidhandle"
    },
    "doc://com.apple.corebluetooth/documentation/CoreBluetooth/CBError-swift.struct/Code/invalidParameters": {
      "abstract": [
        {
          "text": "The specified parameters are invalid.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "invalidParameters"
        }
      ],
      "identifier": "doc://com.apple.corebluetooth/documentation/CoreBluetooth/CBError-swift.struct/Code/invalidParameters",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CBErrorInvalidParameters"
        }
      ],
      "role": "symbol",
      "title": "CBError.Code.invalidParameters",
      "type": "topic",
      "url": "/documentation/corebluetooth/cberror-swift.struct/code/invalidparameters"
    },
    "doc://com.apple.corebluetooth/documentation/CoreBluetooth/CBError-swift.struct/Code/notConnected": {
      "abstract": [
        {
          "text": "The device isn’t currently connected.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "notConnected"
        }
      ],
      "identifier": "doc://com.apple.corebluetooth/documentation/CoreBluetooth/CBError-swift.struct/Code/notConnected",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CBErrorNotConnected"
        }
      ],
      "role": "symbol",
      "title": "CBError.Code.notConnected",
      "type": "topic",
      "url": "/documentation/corebluetooth/cberror-swift.struct/code/notconnected"
    },
    "doc://com.apple.corebluetooth/documentation/CoreBluetooth/CBError-swift.struct/Code/operationCancelled": {
      "abstract": [
        {
          "text": "The error represents a canceled operation.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "operationCancelled"
        }
      ],
      "identifier": "doc://com.apple.corebluetooth/documentation/CoreBluetooth/CBError-swift.struct/Code/operationCancelled",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CBErrorOperationCancelled"
        }
      ],
      "role": "symbol",
      "title": "CBError.Code.operationCancelled",
      "type": "topic",
      "url": "/documentation/corebluetooth/cberror-swift.struct/code/operationcancelled"
    },
    "doc://com.apple.corebluetooth/documentation/CoreBluetooth/CBError-swift.struct/Code/operationNotSupported": {
      "abstract": [
        {
          "text": "The operation isn’t supported.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "operationNotSupported"
        }
      ],
      "identifier": "doc://com.apple.corebluetooth/documentation/CoreBluetooth/CBError-swift.struct/Code/operationNotSupported",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CBErrorOperationNotSupported"
        }
      ],
      "role": "symbol",
      "title": "CBError.Code.operationNotSupported",
      "type": "topic",
      "url": "/documentation/corebluetooth/cberror-swift.struct/code/operationnotsupported"
    },
    "doc://com.apple.corebluetooth/documentation/CoreBluetooth/CBError-swift.struct/Code/outOfSpace": {
      "abstract": [
        {
          "text": "The device has run out of space to complete the intended operation.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "outOfSpace"
        }
      ],
      "identifier": "doc://com.apple.corebluetooth/documentation/CoreBluetooth/CBError-swift.struct/Code/outOfSpace",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CBErrorOutOfSpace"
        }
      ],
      "role": "symbol",
      "title": "CBError.Code.outOfSpace",
      "type": "topic",
      "url": "/documentation/corebluetooth/cberror-swift.struct/code/outofspace"
    },
    "doc://com.apple.corebluetooth/documentation/CoreBluetooth/CBError-swift.struct/Code/peripheralDisconnected": {
      "abstract": [
        {
          "text": "The peripheral disconnected.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "peripheralDisconnected"
        }
      ],
      "identifier": "doc://com.apple.corebluetooth/documentation/CoreBluetooth/CBError-swift.struct/Code/peripheralDisconnected",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CBErrorPeripheralDisconnected"
        }
      ],
      "role": "symbol",
      "title": "CBError.Code.peripheralDisconnected",
      "type": "topic",
      "url": "/documentation/corebluetooth/cberror-swift.struct/code/peripheraldisconnected"
    },
    "doc://com.apple.corebluetooth/documentation/CoreBluetooth/CBError-swift.struct/Code/unknown": {
      "abstract": [
        {
          "text": "An unknown error occurred.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "unknown"
        }
      ],
      "identifier": "doc://com.apple.corebluetooth/documentation/CoreBluetooth/CBError-swift.struct/Code/unknown",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CBErrorUnknown"
        }
      ],
      "role": "symbol",
      "title": "CBError.Code.unknown",
      "type": "topic",
      "url": "/documentation/corebluetooth/cberror-swift.struct/code/unknown"
    },
    "doc://com.apple.corebluetooth/documentation/CoreBluetooth/CBError-swift.struct/Code/unknownDevice": {
      "abstract": [
        {
          "text": "The device is unknown.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "unknownDevice"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC7CBErrorLeV",
          "text": "CBError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@CBError",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.corebluetooth/documentation/CoreBluetooth/CBError-swift.struct/Code/unknownDevice",
      "kind": "symbol",
      "role": "symbol",
      "title": "unknownDevice",
      "type": "topic",
      "url": "/documentation/corebluetooth/cberror-swift.struct/code/unknowndevice"
    },
    "doc://com.apple.corebluetooth/documentation/CoreBluetooth/CBError-swift.struct/Code/unkownDevice": {
      "abstract": [
        {
          "text": "A misspelled version of the unknown device error code.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "unkownDevice"
        }
      ],
      "identifier": "doc://com.apple.corebluetooth/documentation/CoreBluetooth/CBError-swift.struct/Code/unkownDevice",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CBErrorUnkownDevice"
        }
      ],
      "role": "symbol",
      "title": "CBError.Code.unkownDevice",
      "type": "topic",
      "url": "/documentation/corebluetooth/cberror-swift.struct/code/unkowndevice"
    },
    "doc://com.apple.corebluetooth/documentation/CoreBluetooth/CBError-swift.struct/Code/uuidNotAllowed": {
      "abstract": [
        {
          "text": "The specified UUID isn’t permitted.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "uuidNotAllowed"
        }
      ],
      "identifier": "doc://com.apple.corebluetooth/documentation/CoreBluetooth/CBError-swift.struct/Code/uuidNotAllowed",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CBErrorUUIDNotAllowed"
        }
      ],
      "role": "symbol",
      "title": "CBError.Code.uuidNotAllowed",
      "type": "topic",
      "url": "/documentation/corebluetooth/cberror-swift.struct/code/uuidnotallowed"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Error-Codes",
      "generated": true,
      "identifiers": [
        "doc://com.apple.corebluetooth/documentation/CoreBluetooth/CBError-swift.struct/Code/unknown",
        "doc://com.apple.corebluetooth/documentation/CoreBluetooth/CBError-swift.struct/Code/invalidParameters",
        "doc://com.apple.corebluetooth/documentation/CoreBluetooth/CBError-swift.struct/Code/notConnected",
        "doc://com.apple.corebluetooth/documentation/CoreBluetooth/CBError-swift.struct/Code/outOfSpace",
        "doc://com.apple.corebluetooth/documentation/CoreBluetooth/CBError-swift.struct/Code/operationCancelled",
        "doc://com.apple.corebluetooth/documentation/CoreBluetooth/CBError-swift.struct/Code/connectionTimeout",
        "doc://com.apple.corebluetooth/documentation/CoreBluetooth/CBError-swift.struct/Code/peripheralDisconnected",
        "doc://com.apple.corebluetooth/documentation/CoreBluetooth/CBError-swift.struct/Code/uuidNotAllowed",
        "doc://com.apple.corebluetooth/documentation/CoreBluetooth/CBError-swift.struct/Code/alreadyAdvertising",
        "doc://com.apple.corebluetooth/documentation/CoreBluetooth/CBError-swift.struct/Code/connectionFailed",
        "doc://com.apple.corebluetooth/documentation/CoreBluetooth/CBError-swift.struct/Code/connectionLimitReached",
        "doc://com.apple.corebluetooth/documentation/CoreBluetooth/CBError-swift.struct/Code/operationNotSupported",
        "doc://com.apple.corebluetooth/documentation/CoreBluetooth/CBError-swift.struct/Code/unknownDevice",
        "doc://com.apple.corebluetooth/documentation/CoreBluetooth/CBError-swift.struct/Code/unkownDevice"
      ],
      "title": "Error Codes"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "6.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "6.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.1",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.9",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "9.0",
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "2.0",
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration Case"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "CBErrorInvalidHandle"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "case"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CBErrorInvalidHandle"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.corebluetooth/documentation/CoreBluetooth",
                "doc://com.apple.corebluetooth/documentation/CoreBluetooth/CBError-swift.struct/Code"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Error-Codes",
              "generated": true,
              "identifiers": [
                "doc://com.apple.corebluetooth/documentation/CoreBluetooth/CBError-swift.struct/Code/unknown",
                "doc://com.apple.corebluetooth/documentation/CoreBluetooth/CBError-swift.struct/Code/invalidParameters",
                "doc://com.apple.corebluetooth/documentation/CoreBluetooth/CBError-swift.struct/Code/notConnected",
                "doc://com.apple.corebluetooth/documentation/CoreBluetooth/CBError-swift.struct/Code/outOfSpace",
                "doc://com.apple.corebluetooth/documentation/CoreBluetooth/CBError-swift.struct/Code/operationCancelled",
                "doc://com.apple.corebluetooth/documentation/CoreBluetooth/CBError-swift.struct/Code/connectionTimeout",
                "doc://com.apple.corebluetooth/documentation/CoreBluetooth/CBError-swift.struct/Code/peripheralDisconnected",
                "doc://com.apple.corebluetooth/documentation/CoreBluetooth/CBError-swift.struct/Code/uuidNotAllowed",
                "doc://com.apple.corebluetooth/documentation/CoreBluetooth/CBError-swift.struct/Code/alreadyAdvertising",
                "doc://com.apple.corebluetooth/documentation/CoreBluetooth/CBError-swift.struct/Code/connectionFailed",
                "doc://com.apple.corebluetooth/documentation/CoreBluetooth/CBError-swift.struct/Code/connectionLimitReached",
                "doc://com.apple.corebluetooth/documentation/CoreBluetooth/CBError-swift.struct/Code/operationNotSupported",
                "doc://com.apple.corebluetooth/documentation/CoreBluetooth/CBError-c.enum/CBErrorUnknownDevice",
                "doc://com.apple.corebluetooth/documentation/CoreBluetooth/CBError-swift.struct/Code/unkownDevice"
              ],
              "title": "Error Codes"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "identifier",
                    "text": "CBErrorInvalidHandle"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corebluetooth~1documentation~1CoreBluetooth~1CBError-swift.struct~1Code~1notConnected/title",
          "value": "CBErrorNotConnected"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corebluetooth~1documentation~1CoreBluetooth~1CBError-swift.struct~1Code~1notConnected/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CBErrorNotConnected"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corebluetooth~1documentation~1CoreBluetooth~1CBError-swift.struct~1Code~1operationCancelled/title",
          "value": "CBErrorOperationCancelled"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corebluetooth~1documentation~1CoreBluetooth~1CBError-swift.struct~1Code~1operationCancelled/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CBErrorOperationCancelled"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corebluetooth~1documentation~1CoreBluetooth~1CBError-swift.struct~1Code~1operationNotSupported/title",
          "value": "CBErrorOperationNotSupported"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corebluetooth~1documentation~1CoreBluetooth~1CBError-swift.struct~1Code~1operationNotSupported/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CBErrorOperationNotSupported"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corebluetooth~1documentation~1CoreBluetooth~1CBError-swift.struct~1Code~1peripheralDisconnected/title",
          "value": "CBErrorPeripheralDisconnected"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corebluetooth~1documentation~1CoreBluetooth~1CBError-swift.struct~1Code~1peripheralDisconnected/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CBErrorPeripheralDisconnected"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corebluetooth~1documentation~1CoreBluetooth~1CBError-swift.struct~1Code~1invalidHandle/title",
          "value": "CBErrorInvalidHandle"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corebluetooth~1documentation~1CoreBluetooth~1CBError-swift.struct~1Code~1invalidHandle/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CBErrorInvalidHandle"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corebluetooth~1documentation~1CoreBluetooth~1CBError-swift.struct~1Code~1alreadyAdvertising/title",
          "value": "CBErrorAlreadyAdvertising"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corebluetooth~1documentation~1CoreBluetooth~1CBError-swift.struct~1Code~1alreadyAdvertising/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CBErrorAlreadyAdvertising"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corebluetooth~1documentation~1CoreBluetooth~1CBError-swift.struct~1Code/title",
          "value": "CBError"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corebluetooth~1documentation~1CoreBluetooth~1CBError-swift.struct~1Code/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CBError"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corebluetooth~1documentation~1CoreBluetooth~1CBError-swift.struct~1Code/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CBError"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corebluetooth~1documentation~1CoreBluetooth~1CBError-swift.struct~1Code~1invalidParameters/title",
          "value": "CBErrorInvalidParameters"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corebluetooth~1documentation~1CoreBluetooth~1CBError-swift.struct~1Code~1invalidParameters/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CBErrorInvalidParameters"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corebluetooth~1documentation~1CoreBluetooth~1CBError-swift.struct~1Code~1unknown/title",
          "value": "CBErrorUnknown"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corebluetooth~1documentation~1CoreBluetooth~1CBError-swift.struct~1Code~1unknown/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CBErrorUnknown"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corebluetooth~1documentation~1CoreBluetooth~1CBError-swift.struct~1Code~1unkownDevice/title",
          "value": "CBErrorUnkownDevice"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corebluetooth~1documentation~1CoreBluetooth~1CBError-swift.struct~1Code~1unkownDevice/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CBErrorUnkownDevice"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corebluetooth~1documentation~1CoreBluetooth~1CBError-swift.struct~1Code~1connectionFailed/title",
          "value": "CBErrorConnectionFailed"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corebluetooth~1documentation~1CoreBluetooth~1CBError-swift.struct~1Code~1connectionFailed/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CBErrorConnectionFailed"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corebluetooth~1documentation~1CoreBluetooth~1CBError-swift.struct~1Code~1connectionLimitReached/title",
          "value": "CBErrorConnectionLimitReached"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corebluetooth~1documentation~1CoreBluetooth~1CBError-swift.struct~1Code~1connectionLimitReached/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CBErrorConnectionLimitReached"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corebluetooth~1documentation~1CoreBluetooth~1CBError-swift.struct~1Code~1uuidNotAllowed/title",
          "value": "CBErrorUUIDNotAllowed"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corebluetooth~1documentation~1CoreBluetooth~1CBError-swift.struct~1Code~1uuidNotAllowed/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CBErrorUUIDNotAllowed"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corebluetooth~1documentation~1CoreBluetooth~1CBError-swift.struct~1Code~1connectionTimeout/title",
          "value": "CBErrorConnectionTimeout"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corebluetooth~1documentation~1CoreBluetooth~1CBError-swift.struct~1Code~1connectionTimeout/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CBErrorConnectionTimeout"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corebluetooth~1documentation~1CoreBluetooth~1CBError-swift.struct~1Code~1outOfSpace/title",
          "value": "CBErrorOutOfSpace"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corebluetooth~1documentation~1CoreBluetooth~1CBError-swift.struct~1Code~1outOfSpace/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CBErrorOutOfSpace"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/corebluetooth/cberror-swift.struct/code/invalidhandle"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/corebluetooth/cberror-swift.struct/code/invalidhandle"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
