{"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["watchOS"],"languages":["swift"],"tokens":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"leGattExceededBackgroundNotificationLimit"}]}]}],"metadata":{"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"leGattExceededBackgroundNotificationLimit","kind":"identifier"}],"title":"CBError.Code.leGattExceededBackgroundNotificationLimit","platforms":[{"deprecated":false,"unavailable":false,"introducedAt":"9.0","name":"watchOS","beta":false}],"modules":[{"name":"Core Bluetooth"}],"role":"symbol","roleHeading":"Case","externalID":"c:@E@CBError@CBErrorLeGattExceededBackgroundNotificationLimit","navigatorTitle":[{"text":"CBErrorLeGattExceededBackgroundNotificationLimit","kind":"identifier"}],"symbolKind":"case"},"hierarchy":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.corebluetooth/documentation/CoreBluetooth","doc://com.apple.corebluetooth/documentation/CoreBluetooth/CBError-swift.struct","doc://com.apple.corebluetooth/documentation/CoreBluetooth/CBError-swift.struct/Code"]]},"sections":[],"identifier":{"interfaceLanguage":"swift","url":"doc://com.apple.corebluetooth/documentation/CoreBluetooth/CBError-swift.struct/Code/leGattExceededBackgroundNotificationLimit"},"kind":"symbol","schemaVersion":{"major":0,"minor":3,"patch":0},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["/documentation/corebluetooth/cberror-swift.struct/code/legattexceededbackgroundnotificationlimit"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["/documentation/corebluetooth/cberror-swift.struct/code/legattexceededbackgroundnotificationlimit"]}],"references":{"doc://com.apple.corebluetooth/documentation/CoreBluetooth/CBError-swift.struct/Code/leGattExceededBackgroundNotificationLimit":{"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"leGattExceededBackgroundNotificationLimit"}],"title":"CBError.Code.leGattExceededBackgroundNotificationLimit","type":"topic","identifier":"doc://com.apple.corebluetooth/documentation/CoreBluetooth/CBError-swift.struct/Code/leGattExceededBackgroundNotificationLimit","role":"symbol","abstract":[],"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"CBErrorLeGattExceededBackgroundNotificationLimit"}],"url":"/documentation/corebluetooth/cberror-swift.struct/code/legattexceededbackgroundnotificationlimit"},"doc://com.apple.corebluetooth/documentation/CoreBluetooth":{"title":"Core Bluetooth","abstract":[{"text":"Communicate with Bluetooth low energy and BR/EDR (“Classic”) Devices.","type":"text"}],"url":"/documentation/corebluetooth","kind":"symbol","type":"topic","role":"collection","identifier":"doc://com.apple.corebluetooth/documentation/CoreBluetooth"},"doc://com.apple.documentation/documentation/technologies":{"abstract":[{"text":"","type":"text"}],"identifier":"doc://com.apple.documentation/documentation/technologies","kind":"technologies","type":"topic","title":"Technologies","role":"overview","url":"/documentation/technologies"},"doc://com.apple.corebluetooth/documentation/CoreBluetooth/CBError-swift.struct/Code":{"navigatorTitle":[{"kind":"identifier","text":"Code"}],"role":"symbol","type":"topic","url":"/documentation/corebluetooth/cberror-swift.struct/code","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"Code"}],"abstract":[{"text":"The codes for errors that Core Bluetooth returns during Bluetooth transactions.","type":"text"}],"identifier":"doc://com.apple.corebluetooth/documentation/CoreBluetooth/CBError-swift.struct/Code","title":"CBError.Code","kind":"symbol"},"doc://com.apple.corebluetooth/documentation/CoreBluetooth/CBError-swift.struct":{"fragments":[{"text":"struct","kind":"keyword"},{"kind":"text","text":" "},{"text":"CBError","kind":"identifier"}],"title":"CBError","type":"topic","identifier":"doc://com.apple.corebluetooth/documentation/CoreBluetooth/CBError-swift.struct","role":"symbol","abstract":[{"text":"An error that Core Bluetooth returns during Bluetooth transactions.","type":"text"}],"kind":"symbol","navigatorTitle":[{"text":"CBError","kind":"identifier"}],"url":"/documentation/corebluetooth/cberror-swift.struct"}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"/identifier/interfaceLanguage"},{"value":[{"deprecated":false,"unavailable":false,"introducedAt":"9.0","name":"watchOS","beta":false}],"op":"replace","path":"/metadata/platforms"},{"value":"Enumeration Case","op":"replace","path":"/metadata/roleHeading"},{"value":"CBErrorLeGattExceededBackgroundNotificationLimit","op":"replace","path":"/metadata/title"},{"value":"case","op":"replace","path":"/metadata/symbolKind"},{"value":[{"text":"CBErrorLeGattExceededBackgroundNotificationLimit","kind":"identifier"}],"op":"replace","path":"/metadata/fragments"},{"value":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.corebluetooth/documentation/CoreBluetooth","doc://com.apple.corebluetooth/documentation/CoreBluetooth/CBError-swift.struct/Code"]]},"op":"replace","path":"/hierarchy"},{"value":null,"op":"add","path":"/topicSections"},{"value":null,"op":"add","path":"/relationshipsSections"},{"value":null,"op":"add","path":"/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"platforms":["iOS","iPadOS","Mac Catalyst","macOS","tvOS","visionOS","watchOS"],"languages":["occ"],"tokens":[{"kind":"identifier","text":"CBErrorLeGattExceededBackgroundNotificationLimit"}]}]},"op":"replace","path":"/primaryContentSections/0"},{"path":"/references/doc:~1~1com.apple.corebluetooth~1documentation~1CoreBluetooth~1CBError-swift.struct~1Code~1leGattExceededBackgroundNotificationLimit/title","op":"replace","value":"CBErrorLeGattExceededBackgroundNotificationLimit"},{"path":"/references/doc:~1~1com.apple.corebluetooth~1documentation~1CoreBluetooth~1CBError-swift.struct~1Code~1leGattExceededBackgroundNotificationLimit/fragments","op":"replace","value":[{"kind":"identifier","text":"CBErrorLeGattExceededBackgroundNotificationLimit"}]},{"path":"/references/doc:~1~1com.apple.corebluetooth~1documentation~1CoreBluetooth~1CBError-swift.struct~1Code/title","op":"replace","value":"CBError"},{"path":"/references/doc:~1~1com.apple.corebluetooth~1documentation~1CoreBluetooth~1CBError-swift.struct~1Code/fragments","op":"replace","value":[{"kind":"identifier","text":"CBError"}]},{"path":"/references/doc:~1~1com.apple.corebluetooth~1documentation~1CoreBluetooth~1CBError-swift.struct~1Code/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"CBError"}]}],"traits":[{"interfaceLanguage":"occ"}]}],"legalNotices":{"copyright":"Copyright &copy; 2025 Apple Inc. All rights reserved.","termsOfUse":"https://www.apple.com/legal/internet-services/terms/site.html","privacyPolicy":"https://www.apple.com/privacy/privacy-policy"}}