{
  "abstract": [
    {
      "text": "An interface with methods you use to retrieve decoded video, audio, and image data from a source media file.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/CompressorMediaDecoder"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(pl)CompressorMediaDecoder",
    "fragments": [
      {
        "kind": "keyword",
        "text": "protocol"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "CompressorMediaDecoder"
      }
    ],
    "modules": [
      {
        "name": "Professional Video Applications"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "CompressorMediaDecoder"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "introducedAt": "1.0",
        "name": "ProVideo Encoder Extensions"
      }
    ],
    "role": "symbol",
    "roleHeading": "Protocol",
    "symbolKind": "protocol",
    "title": "CompressorMediaDecoder"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "Unsupported OS: ProExtension"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "protocol"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "CompressorMediaDecoder"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "The Compressor app configures a decoder object to produce decoded video frames and audio samples based on the encoder attributes and source media properties.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "During the encoding process, the Compressor app provides this decoder object to the extension. Call the methods in the decoder object to get:",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "items": [
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Source video frames at the width, height, and frame rate specified in the decoding attributes.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Audio samples at the sample rate and channel layout specified in the encoder settings.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Uncompressed images from the decoder object with an image format that the extension, the source media, and the Compressor app filters support.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Closed-caption data and details of the source media timecode.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            }
          ],
          "type": "unorderedList"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications": {
      "abstract": [
        {
          "text": "Exchange data with Final Cut Pro, and create effects plug-ins for Final Cut Pro and Motion.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications",
      "kind": "symbol",
      "role": "collection",
      "title": "Professional Video Applications",
      "type": "topic",
      "url": "/documentation/professional_video_applications"
    },
    "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/CompressorMediaDecoder": {
      "abstract": [
        {
          "text": "An interface with methods you use to retrieve decoded video, audio, and image data from a source media file.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CompressorMediaDecoder"
        }
      ],
      "identifier": "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/CompressorMediaDecoder",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CompressorMediaDecoder"
        }
      ],
      "role": "symbol",
      "title": "CompressorMediaDecoder",
      "type": "topic",
      "url": "/documentation/professional_video_applications/compressormediadecoder"
    },
    "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/CompressorMediaDecoder/copyAudio(atStart:count:)": {
      "abstract": [
        {
          "text": "Returns decoded audio samples starting from the specified temporal position.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "copyAudio"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "atStart"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int64V",
          "text": "Int64"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "count"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sp",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int64V",
          "text": "Int64"
        },
        {
          "kind": "text",
          "text": ">!) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10Foundation4DataV",
          "text": "Data"
        },
        {
          "kind": "text",
          "text": "!"
        }
      ],
      "identifier": "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/CompressorMediaDecoder/copyAudio(atStart:count:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "copyAudioAtStart:count:"
        }
      ],
      "required": true,
      "role": "symbol",
      "title": "copyAudio(atStart:count:)",
      "type": "topic",
      "url": "/documentation/professional_video_applications/compressormediadecoder/copyaudio(atstart:count:)"
    },
    "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/CompressorMediaDecoder/copyCloseCaptionData(_:frameCount:)": {
      "abstract": [
        {
          "text": "Returns a list of closed-caption tracks associated with the specified video frames.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "copyCloseCaptionData"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int64V",
          "text": "Int64"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "frameCount"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int64V",
          "text": "Int64"
        },
        {
          "kind": "text",
          "text": ") -> ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s11AnyHashableV",
          "text": "AnyHashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "keyword",
          "text": "Any"
        },
        {
          "kind": "text",
          "text": "]!"
        }
      ],
      "identifier": "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/CompressorMediaDecoder/copyCloseCaptionData(_:frameCount:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "copyCloseCaptionData:frameCount:"
        }
      ],
      "required": true,
      "role": "symbol",
      "title": "copyCloseCaptionData(_:frameCount:)",
      "type": "topic",
      "url": "/documentation/professional_video_applications/compressormediadecoder/copyclosecaptiondata(_:framecount:)"
    },
    "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/CompressorMediaDecoder/copyFrame(_:)": {
      "abstract": [
        {
          "text": "Returns the decoded video frame indicated by the frame number.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "copyFrame"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int64V",
          "text": "Int64"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)IOSurface",
          "text": "IOSurface"
        },
        {
          "kind": "text",
          "text": "!"
        }
      ],
      "identifier": "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/CompressorMediaDecoder/copyFrame(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "copyFrame:"
        }
      ],
      "required": true,
      "role": "symbol",
      "title": "copyFrame(_:)",
      "type": "topic",
      "url": "/documentation/professional_video_applications/compressormediadecoder/copyframe(_:)"
    },
    "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/CompressorMediaDecoder/decodingAttributes()": {
      "abstract": [
        {
          "text": "Returns a set of video attributes of the decoded source media file.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "decodingAttributes"
        },
        {
          "kind": "text",
          "text": "() -> ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s11AnyHashableV",
          "text": "AnyHashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "keyword",
          "text": "Any"
        },
        {
          "kind": "text",
          "text": "]!"
        }
      ],
      "identifier": "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/CompressorMediaDecoder/decodingAttributes()",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "decodingAttributes"
        }
      ],
      "required": true,
      "role": "symbol",
      "title": "decodingAttributes()",
      "type": "topic",
      "url": "/documentation/professional_video_applications/compressormediadecoder/decodingattributes()"
    },
    "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/CompressorMediaDecoder/releaseFrame(_:)": {
      "abstract": [
        {
          "text": "Release a decoded frame when the encoder extension no longer needs the frame.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "releaseFrame"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)IOSurface",
          "text": "IOSurface"
        },
        {
          "kind": "text",
          "text": "!)"
        }
      ],
      "identifier": "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/CompressorMediaDecoder/releaseFrame(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "releaseFrame:"
        }
      ],
      "required": true,
      "role": "symbol",
      "title": "releaseFrame(_:)",
      "type": "topic",
      "url": "/documentation/professional_video_applications/compressormediadecoder/releaseframe(_:)"
    },
    "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/CompressorMediaDecoder/startTimeCodeForMedia()": {
      "abstract": [
        {
          "text": "Returns the source media timecode details.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "startTimeCodeForMedia"
        },
        {
          "kind": "text",
          "text": "() -> ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s11AnyHashableV",
          "text": "AnyHashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "keyword",
          "text": "Any"
        },
        {
          "kind": "text",
          "text": "]!"
        }
      ],
      "identifier": "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/CompressorMediaDecoder/startTimeCodeForMedia()",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "startTimeCodeForMedia"
        }
      ],
      "required": true,
      "role": "symbol",
      "title": "startTimeCodeForMedia()",
      "type": "topic",
      "url": "/documentation/professional_video_applications/compressormediadecoder/starttimecodeformedia()"
    },
    "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/CompressorMediaDecoderPtr": {
      "abstract": [
        {
          "text": "The type alias for referencing the decoder object.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CompressorMediaDecoderPtr"
        }
      ],
      "identifier": "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/CompressorMediaDecoderPtr",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CompressorMediaDecoderPtr"
        }
      ],
      "role": "symbol",
      "title": "CompressorMediaDecoderPtr",
      "type": "topic",
      "url": "/documentation/professional_video_applications/compressormediadecoderptr"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "topicSections": [
    {
      "anchor": "Getting-Decoded-Frames-and-Samples",
      "identifiers": [
        "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/CompressorMediaDecoder/copyAudio(atStart:count:)",
        "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/CompressorMediaDecoder/copyCloseCaptionData(_:frameCount:)",
        "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/CompressorMediaDecoder/copyFrame(_:)",
        "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/CompressorMediaDecoder/releaseFrame(_:)",
        "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/CompressorMediaDecoderPtr"
      ],
      "title": "Getting Decoded Frames and Samples"
    },
    {
      "anchor": "Getting-Decoding-Attributes",
      "identifiers": [
        "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/CompressorMediaDecoder/decodingAttributes()",
        "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/CompressorMediaDecoder/startTimeCodeForMedia()"
      ],
      "title": "Getting Decoding Attributes"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": null
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Protocol"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "CompressorMediaDecoder"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "protocol"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CompressorMediaDecoder"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CompressorMediaDecoder"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Getting-Decoded-Frames-and-Samples",
              "identifiers": [
                "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/CompressorMediaDecoder/copyAudio(atStart:count:)",
                "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/CompressorMediaDecoder/copyCloseCaptionData(_:frameCount:)",
                "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/CompressorMediaDecoder/copyFrame(_:)",
                "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/CompressorMediaDecoder/releaseFrame(_:)",
                "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/CompressorMediaDecoderPtr"
              ],
              "title": "Getting Decoded Frames and Samples"
            },
            {
              "anchor": "Getting-Decoding-Attributes",
              "identifiers": [
                "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/CompressorMediaDecoder/decodingAttributes()",
                "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/CompressorMediaDecoder/startTimeCodeForMedia()"
              ],
              "title": "Getting Decoding Attributes"
            }
          ]
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/seeAlsoSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "Unsupported OS: ProExtension"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "@protocol"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "CompressorMediaDecoder"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.professionalvideoapplications~1documentation~1professional_video_applications~1CompressorMediaDecoder~1decodingAttributes()/title",
          "value": "decodingAttributes"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.professionalvideoapplications~1documentation~1professional_video_applications~1CompressorMediaDecoder~1decodingAttributes()/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "decodingAttributes"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.professionalvideoapplications~1documentation~1professional_video_applications~1CompressorMediaDecoder~1copyAudio(atStart:count:)/title",
          "value": "copyAudioAtStart:count:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.professionalvideoapplications~1documentation~1professional_video_applications~1CompressorMediaDecoder~1copyAudio(atStart:count:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "copyAudioAtStart:count:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.professionalvideoapplications~1documentation~1professional_video_applications~1CompressorMediaDecoder~1copyCloseCaptionData(_:frameCount:)/title",
          "value": "copyCloseCaptionData:frameCount:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.professionalvideoapplications~1documentation~1professional_video_applications~1CompressorMediaDecoder~1copyCloseCaptionData(_:frameCount:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "copyCloseCaptionData:frameCount:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.professionalvideoapplications~1documentation~1professional_video_applications~1CompressorMediaDecoder/title",
          "value": "CompressorMediaDecoder"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.professionalvideoapplications~1documentation~1professional_video_applications~1CompressorMediaDecoder/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CompressorMediaDecoder"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.professionalvideoapplications~1documentation~1professional_video_applications~1CompressorMediaDecoder/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CompressorMediaDecoder"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.professionalvideoapplications~1documentation~1professional_video_applications~1CompressorMediaDecoder~1copyFrame(_:)/title",
          "value": "copyFrame:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.professionalvideoapplications~1documentation~1professional_video_applications~1CompressorMediaDecoder~1copyFrame(_:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "copyFrame:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.professionalvideoapplications~1documentation~1professional_video_applications~1CompressorMediaDecoderPtr/title",
          "value": "CompressorMediaDecoderPtr"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.professionalvideoapplications~1documentation~1professional_video_applications~1CompressorMediaDecoderPtr/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CompressorMediaDecoderPtr"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.professionalvideoapplications~1documentation~1professional_video_applications~1CompressorMediaDecoderPtr/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CompressorMediaDecoderPtr"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.professionalvideoapplications~1documentation~1professional_video_applications~1CompressorMediaDecoder~1releaseFrame(_:)/title",
          "value": "releaseFrame:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.professionalvideoapplications~1documentation~1professional_video_applications~1CompressorMediaDecoder~1releaseFrame(_:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "releaseFrame:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.professionalvideoapplications~1documentation~1professional_video_applications~1CompressorMediaDecoder~1startTimeCodeForMedia()/title",
          "value": "startTimeCodeForMedia"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.professionalvideoapplications~1documentation~1professional_video_applications~1CompressorMediaDecoder~1startTimeCodeForMedia()/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "startTimeCodeForMedia"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/professional_video_applications/compressormediadecoder"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/professional_video_applications/compressormediadecoder"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
