{
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/eCEColorSpecP3D65PQ"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@EA@eCEColorSpace@eCEColorSpecP3D65PQ",
    "fragments": [
      {
        "kind": "keyword",
        "text": "var"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "eCEColorSpecP3D65PQ"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@EA@eCEColorSpace",
        "text": "eCEColorSpace"
      }
    ],
    "modules": [
      {
        "name": "Professional Video Applications"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "eCEColorSpecP3D65PQ"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "introducedAt": "1.0",
        "name": "ProVideo Encoder Extensions"
      }
    ],
    "role": "symbol",
    "roleHeading": "Global Variable",
    "symbolKind": "var",
    "title": "eCEColorSpecP3D65PQ"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "Unsupported OS: ProExtension"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "var"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "eCEColorSpecP3D65PQ"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/eCEColorSpace",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@EA@eCEColorSpace",
              "text": "eCEColorSpace"
            },
            {
              "kind": "text",
              "text": " { "
            },
            {
              "kind": "keyword",
              "text": "get"
            },
            {
              "kind": "text",
              "text": " }"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications": {
      "abstract": [
        {
          "text": "Exchange data with Final Cut Pro, and create effects plug-ins for Final Cut Pro and Motion.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications",
      "kind": "symbol",
      "role": "collection",
      "title": "Professional Video Applications",
      "type": "topic",
      "url": "/documentation/professional_video_applications"
    },
    "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/eCEColorSpace": {
      "abstract": [
        {
          "text": "The list of color spaces an encoder extension can support.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "eCEColorSpace"
        }
      ],
      "identifier": "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/eCEColorSpace",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "eCEColorSpace"
        }
      ],
      "role": "symbol",
      "title": "eCEColorSpace",
      "type": "topic",
      "url": "/documentation/professional_video_applications/ececolorspace"
    },
    "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/eCEColorSpace601NTSC": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "eCEColorSpace601NTSC"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@EA@eCEColorSpace",
          "text": "eCEColorSpace"
        }
      ],
      "identifier": "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/eCEColorSpace601NTSC",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "eCEColorSpace601NTSC"
        }
      ],
      "role": "symbol",
      "title": "eCEColorSpace601NTSC",
      "type": "topic",
      "url": "/documentation/professional_video_applications/ececolorspace601ntsc"
    },
    "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/eCEColorSpace601PAL": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "eCEColorSpace601PAL"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@EA@eCEColorSpace",
          "text": "eCEColorSpace"
        }
      ],
      "identifier": "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/eCEColorSpace601PAL",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "eCEColorSpace601PAL"
        }
      ],
      "role": "symbol",
      "title": "eCEColorSpace601PAL",
      "type": "topic",
      "url": "/documentation/professional_video_applications/ececolorspace601pal"
    },
    "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/eCEColorSpace709": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "eCEColorSpace709"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@EA@eCEColorSpace",
          "text": "eCEColorSpace"
        }
      ],
      "identifier": "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/eCEColorSpace709",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "eCEColorSpace709"
        }
      ],
      "role": "symbol",
      "title": "eCEColorSpace709",
      "type": "topic",
      "url": "/documentation/professional_video_applications/ececolorspace709"
    },
    "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/eCEColorSpaceDeviceRGB": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "eCEColorSpaceDeviceRGB"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@EA@eCEColorSpace",
          "text": "eCEColorSpace"
        }
      ],
      "identifier": "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/eCEColorSpaceDeviceRGB",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "eCEColorSpaceDeviceRGB"
        }
      ],
      "role": "symbol",
      "title": "eCEColorSpaceDeviceRGB",
      "type": "topic",
      "url": "/documentation/professional_video_applications/ececolorspacedevicergb"
    },
    "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/eCEColorSpaceUnknown": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "eCEColorSpaceUnknown"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@EA@eCEColorSpace",
          "text": "eCEColorSpace"
        }
      ],
      "identifier": "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/eCEColorSpaceUnknown",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "eCEColorSpaceUnknown"
        }
      ],
      "role": "symbol",
      "title": "eCEColorSpaceUnknown",
      "type": "topic",
      "url": "/documentation/professional_video_applications/ececolorspaceunknown"
    },
    "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/eCEColorSpecDCIP3": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "eCEColorSpecDCIP3"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@EA@eCEColorSpace",
          "text": "eCEColorSpace"
        }
      ],
      "identifier": "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/eCEColorSpecDCIP3",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "eCEColorSpecDCIP3"
        }
      ],
      "role": "symbol",
      "title": "eCEColorSpecDCIP3",
      "type": "topic",
      "url": "/documentation/professional_video_applications/ececolorspecdcip3"
    },
    "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/eCEColorSpecITUR2020": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "eCEColorSpecITUR2020"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@EA@eCEColorSpace",
          "text": "eCEColorSpace"
        }
      ],
      "identifier": "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/eCEColorSpecITUR2020",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "eCEColorSpecITUR2020"
        }
      ],
      "role": "symbol",
      "title": "eCEColorSpecITUR2020",
      "type": "topic",
      "url": "/documentation/professional_video_applications/ececolorspecitur2020"
    },
    "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/eCEColorSpecP3D65": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "eCEColorSpecP3D65"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@EA@eCEColorSpace",
          "text": "eCEColorSpace"
        }
      ],
      "identifier": "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/eCEColorSpecP3D65",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "eCEColorSpecP3D65"
        }
      ],
      "role": "symbol",
      "title": "eCEColorSpecP3D65",
      "type": "topic",
      "url": "/documentation/professional_video_applications/ececolorspecp3d65"
    },
    "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/eCEColorSpecP3D65HLG": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "eCEColorSpecP3D65HLG"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@EA@eCEColorSpace",
          "text": "eCEColorSpace"
        }
      ],
      "identifier": "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/eCEColorSpecP3D65HLG",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "eCEColorSpecP3D65HLG"
        }
      ],
      "role": "symbol",
      "title": "eCEColorSpecP3D65HLG",
      "type": "topic",
      "url": "/documentation/professional_video_applications/ececolorspecp3d65hlg"
    },
    "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/eCEColorSpecP3D65PQ": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "eCEColorSpecP3D65PQ"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@EA@eCEColorSpace",
          "text": "eCEColorSpace"
        }
      ],
      "identifier": "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/eCEColorSpecP3D65PQ",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "eCEColorSpecP3D65PQ"
        }
      ],
      "role": "symbol",
      "title": "eCEColorSpecP3D65PQ",
      "type": "topic",
      "url": "/documentation/professional_video_applications/ececolorspecp3d65pq"
    },
    "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/eCEColorSpecP3DCIPQ": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "eCEColorSpecP3DCIPQ"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@EA@eCEColorSpace",
          "text": "eCEColorSpace"
        }
      ],
      "identifier": "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/eCEColorSpecP3DCIPQ",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "eCEColorSpecP3DCIPQ"
        }
      ],
      "role": "symbol",
      "title": "eCEColorSpecP3DCIPQ",
      "type": "topic",
      "url": "/documentation/professional_video_applications/ececolorspecp3dcipq"
    },
    "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/eCEColorSpecRGBHDRLinear": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "eCEColorSpecRGBHDRLinear"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@EA@eCEColorSpace",
          "text": "eCEColorSpace"
        }
      ],
      "identifier": "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/eCEColorSpecRGBHDRLinear",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "eCEColorSpecRGBHDRLinear"
        }
      ],
      "role": "symbol",
      "title": "eCEColorSpecRGBHDRLinear",
      "type": "topic",
      "url": "/documentation/professional_video_applications/ececolorspecrgbhdrlinear"
    },
    "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/eCEColorSpecRGBSDRLinear": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "eCEColorSpecRGBSDRLinear"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@EA@eCEColorSpace",
          "text": "eCEColorSpace"
        }
      ],
      "identifier": "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/eCEColorSpecRGBSDRLinear",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "eCEColorSpecRGBSDRLinear"
        }
      ],
      "role": "symbol",
      "title": "eCEColorSpecRGBSDRLinear",
      "type": "topic",
      "url": "/documentation/professional_video_applications/ececolorspecrgbsdrlinear"
    },
    "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/eCEColorSpecSRGB": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "eCEColorSpecSRGB"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@EA@eCEColorSpace",
          "text": "eCEColorSpace"
        }
      ],
      "identifier": "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/eCEColorSpecSRGB",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "eCEColorSpecSRGB"
        }
      ],
      "role": "symbol",
      "title": "eCEColorSpecSRGB",
      "type": "topic",
      "url": "/documentation/professional_video_applications/ececolorspecsrgb"
    },
    "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/eCEColorSpectITUR2020HLG": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "eCEColorSpectITUR2020HLG"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@EA@eCEColorSpace",
          "text": "eCEColorSpace"
        }
      ],
      "identifier": "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/eCEColorSpectITUR2020HLG",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "eCEColorSpectITUR2020HLG"
        }
      ],
      "role": "symbol",
      "title": "eCEColorSpectITUR2020HLG",
      "type": "topic",
      "url": "/documentation/professional_video_applications/ececolorspectitur2020hlg"
    },
    "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/eCEColorSpectITUR2020PQ": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "eCEColorSpectITUR2020PQ"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@EA@eCEColorSpace",
          "text": "eCEColorSpace"
        }
      ],
      "identifier": "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/eCEColorSpectITUR2020PQ",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "eCEColorSpectITUR2020PQ"
        }
      ],
      "role": "symbol",
      "title": "eCEColorSpectITUR2020PQ",
      "type": "topic",
      "url": "/documentation/professional_video_applications/ececolorspectitur2020pq"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Constants",
      "generated": true,
      "identifiers": [
        "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/eCEColorSpace601NTSC",
        "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/eCEColorSpace601PAL",
        "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/eCEColorSpace709",
        "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/eCEColorSpaceDeviceRGB",
        "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/eCEColorSpaceUnknown",
        "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/eCEColorSpecDCIP3",
        "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/eCEColorSpecITUR2020",
        "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/eCEColorSpecP3D65",
        "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/eCEColorSpecP3D65HLG",
        "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/eCEColorSpecP3DCIPQ",
        "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/eCEColorSpecRGBHDRLinear",
        "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/eCEColorSpecRGBSDRLinear",
        "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/eCEColorSpecSRGB",
        "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/eCEColorSpectITUR2020HLG",
        "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/eCEColorSpectITUR2020PQ"
      ],
      "title": "Constants"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": null
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration Case"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "eCEColorSpecP3D65PQ"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "case"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "eCEColorSpecP3D65PQ"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications",
                "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/eCEColorSpace"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Constants",
              "generated": true,
              "identifiers": [
                "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/eCEColorSpace601NTSC",
                "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/eCEColorSpace601PAL",
                "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/eCEColorSpace709",
                "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/eCEColorSpaceDeviceRGB",
                "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/eCEColorSpaceUnknown",
                "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/eCEColorSpecDCIP3",
                "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/eCEColorSpecITUR2020",
                "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/eCEColorSpecP3D65",
                "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/eCEColorSpecP3D65HLG",
                "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/eCEColorSpecP3DCIPQ",
                "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/eCEColorSpecRGBHDRLinear",
                "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/eCEColorSpecRGBSDRLinear",
                "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/eCEColorSpecSRGB",
                "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/eCEColorSpectITUR2020HLG",
                "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/eCEColorSpectITUR2020PQ"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "Unsupported OS: ProExtension"
                ],
                "tokens": [
                  {
                    "kind": "identifier",
                    "text": "eCEColorSpecP3D65PQ"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.professionalvideoapplications~1documentation~1professional_video_applications~1eCEColorSpecP3D65HLG/title",
          "value": "eCEColorSpecP3D65HLG"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.professionalvideoapplications~1documentation~1professional_video_applications~1eCEColorSpecP3D65HLG/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "eCEColorSpecP3D65HLG"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.professionalvideoapplications~1documentation~1professional_video_applications~1eCEColorSpecP3D65/title",
          "value": "eCEColorSpecP3D65"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.professionalvideoapplications~1documentation~1professional_video_applications~1eCEColorSpecP3D65/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "eCEColorSpecP3D65"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.professionalvideoapplications~1documentation~1professional_video_applications~1eCEColorSpace709/title",
          "value": "eCEColorSpace709"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.professionalvideoapplications~1documentation~1professional_video_applications~1eCEColorSpace709/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "eCEColorSpace709"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.professionalvideoapplications~1documentation~1professional_video_applications~1eCEColorSpaceDeviceRGB/title",
          "value": "eCEColorSpaceDeviceRGB"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.professionalvideoapplications~1documentation~1professional_video_applications~1eCEColorSpaceDeviceRGB/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "eCEColorSpaceDeviceRGB"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.professionalvideoapplications~1documentation~1professional_video_applications~1eCEColorSpecDCIP3/title",
          "value": "eCEColorSpecDCIP3"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.professionalvideoapplications~1documentation~1professional_video_applications~1eCEColorSpecDCIP3/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "eCEColorSpecDCIP3"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.professionalvideoapplications~1documentation~1professional_video_applications~1eCEColorSpecP3DCIPQ/title",
          "value": "eCEColorSpecP3DCIPQ"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.professionalvideoapplications~1documentation~1professional_video_applications~1eCEColorSpecP3DCIPQ/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "eCEColorSpecP3DCIPQ"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.professionalvideoapplications~1documentation~1professional_video_applications~1eCEColorSpecP3D65PQ/title",
          "value": "eCEColorSpecP3D65PQ"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.professionalvideoapplications~1documentation~1professional_video_applications~1eCEColorSpecP3D65PQ/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "eCEColorSpecP3D65PQ"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.professionalvideoapplications~1documentation~1professional_video_applications~1eCEColorSpectITUR2020HLG/title",
          "value": "eCEColorSpectITUR2020HLG"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.professionalvideoapplications~1documentation~1professional_video_applications~1eCEColorSpectITUR2020HLG/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "eCEColorSpectITUR2020HLG"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.professionalvideoapplications~1documentation~1professional_video_applications~1eCEColorSpace601NTSC/title",
          "value": "eCEColorSpace601NTSC"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.professionalvideoapplications~1documentation~1professional_video_applications~1eCEColorSpace601NTSC/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "eCEColorSpace601NTSC"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.professionalvideoapplications~1documentation~1professional_video_applications~1eCEColorSpecRGBSDRLinear/title",
          "value": "eCEColorSpecRGBSDRLinear"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.professionalvideoapplications~1documentation~1professional_video_applications~1eCEColorSpecRGBSDRLinear/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "eCEColorSpecRGBSDRLinear"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.professionalvideoapplications~1documentation~1professional_video_applications~1eCEColorSpecRGBHDRLinear/title",
          "value": "eCEColorSpecRGBHDRLinear"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.professionalvideoapplications~1documentation~1professional_video_applications~1eCEColorSpecRGBHDRLinear/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "eCEColorSpecRGBHDRLinear"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.professionalvideoapplications~1documentation~1professional_video_applications~1eCEColorSpecSRGB/title",
          "value": "eCEColorSpecSRGB"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.professionalvideoapplications~1documentation~1professional_video_applications~1eCEColorSpecSRGB/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "eCEColorSpecSRGB"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.professionalvideoapplications~1documentation~1professional_video_applications~1eCEColorSpaceUnknown/title",
          "value": "eCEColorSpaceUnknown"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.professionalvideoapplications~1documentation~1professional_video_applications~1eCEColorSpaceUnknown/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "eCEColorSpaceUnknown"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.professionalvideoapplications~1documentation~1professional_video_applications~1eCEColorSpectITUR2020PQ/title",
          "value": "eCEColorSpectITUR2020PQ"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.professionalvideoapplications~1documentation~1professional_video_applications~1eCEColorSpectITUR2020PQ/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "eCEColorSpectITUR2020PQ"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.professionalvideoapplications~1documentation~1professional_video_applications~1eCEColorSpace/title",
          "value": "eCEColorSpace"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.professionalvideoapplications~1documentation~1professional_video_applications~1eCEColorSpace/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "eCEColorSpace"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.professionalvideoapplications~1documentation~1professional_video_applications~1eCEColorSpace601PAL/title",
          "value": "eCEColorSpace601PAL"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.professionalvideoapplications~1documentation~1professional_video_applications~1eCEColorSpace601PAL/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "eCEColorSpace601PAL"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.professionalvideoapplications~1documentation~1professional_video_applications~1eCEColorSpecITUR2020/title",
          "value": "eCEColorSpecITUR2020"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.professionalvideoapplications~1documentation~1professional_video_applications~1eCEColorSpecITUR2020/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "eCEColorSpecITUR2020"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/professional_video_applications/ececolorspecp3d65pq"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/professional_video_applications/ececolorspecp3d65pq"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
