{
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "occ",
    "url": "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/enum_(unnamed)-7jahq"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@Ea@kFxParameterFlag_DEFAULT",
    "modules": [
      {
        "name": "Professional Video Applications"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "enum (unnamed)"
      }
    ],
    "role": "symbol",
    "roleHeading": "Enumeration",
    "symbolKind": "enum",
    "title": "enum (unnamed)"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "occ"
          ],
          "platforms": [
            "Unsupported OS: FxPlug"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "enum"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:i",
              "text": "unsigned int"
            },
            {
              "kind": "text",
              "text": ";"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications": {
      "abstract": [
        {
          "text": "Exchange data with Final Cut Pro, and create effects plug-ins for Final Cut Pro and Motion.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications",
      "kind": "symbol",
      "role": "collection",
      "title": "Professional Video Applications",
      "type": "topic",
      "url": "/documentation/professional_video_applications"
    },
    "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/FxAnalysisAPI/analysisStateForEffect()": {
      "abstract": [
        {
          "text": "Fetches the state of frame analysis for your plug-in.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "analysisStateForEffect"
        },
        {
          "kind": "text",
          "text": "() -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@FxAnalysisState",
          "text": "FxAnalysisState"
        }
      ],
      "identifier": "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/FxAnalysisAPI/analysisStateForEffect()",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "analysisStateForEffect"
        }
      ],
      "required": true,
      "role": "symbol",
      "title": "analysisStateForEffect()",
      "type": "topic",
      "url": "/documentation/professional_video_applications/fxanalysisapi/analysisstateforeffect()"
    },
    "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/enum_(unnamed)-14vbr": {
      "abstract": [
        {
          "text": "The field order.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/enum_(unnamed)-14vbr",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "enum (unnamed)"
        }
      ],
      "role": "symbol",
      "title": "enum (unnamed)",
      "type": "topic",
      "url": "/documentation/professional_video_applications/enum_(unnamed)-14vbr"
    },
    "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/enum_(unnamed)-187sa": {
      "abstract": [],
      "identifier": "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/enum_(unnamed)-187sa",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "enum (unnamed)"
        }
      ],
      "role": "symbol",
      "title": "enum (unnamed)",
      "type": "topic",
      "url": "/documentation/professional_video_applications/enum_(unnamed)-187sa"
    },
    "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/enum_(unnamed)-1tjh8": {
      "abstract": [
        {
          "text": "The possible states of analysis, as reported by the host application when queried with ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/FxAnalysisAPI/analysisStateForEffect()",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": ".",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/enum_(unnamed)-1tjh8",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "enum (unnamed)"
        }
      ],
      "role": "symbol",
      "title": "enum (unnamed)",
      "type": "topic",
      "url": "/documentation/professional_video_applications/enum_(unnamed)-1tjh8"
    },
    "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/enum_(unnamed)-2epbe": {
      "abstract": [],
      "identifier": "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/enum_(unnamed)-2epbe",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "enum (unnamed)"
        }
      ],
      "role": "symbol",
      "title": "enum (unnamed)",
      "type": "topic",
      "url": "/documentation/professional_video_applications/enum_(unnamed)-2epbe"
    },
    "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/enum_(unnamed)-35krj": {
      "abstract": [
        {
          "text": "The path blend mode.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/enum_(unnamed)-35krj",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "enum (unnamed)"
        }
      ],
      "role": "symbol",
      "title": "enum (unnamed)",
      "type": "topic",
      "url": "/documentation/professional_video_applications/enum_(unnamed)-35krj"
    },
    "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/enum_(unnamed)-3fxly": {
      "abstract": [
        {
          "text": "The bit-depth",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/enum_(unnamed)-3fxly",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "enum (unnamed)"
        }
      ],
      "role": "symbol",
      "title": "enum (unnamed)",
      "type": "topic",
      "url": "/documentation/professional_video_applications/enum_(unnamed)-3fxly"
    },
    "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/enum_(unnamed)-3hmov": {
      "abstract": [
        {
          "text": "The render quality.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/enum_(unnamed)-3hmov",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "enum (unnamed)"
        }
      ],
      "role": "symbol",
      "title": "enum (unnamed)",
      "type": "topic",
      "url": "/documentation/professional_video_applications/enum_(unnamed)-3hmov"
    },
    "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/enum_(unnamed)-424rv": {
      "abstract": [],
      "identifier": "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/enum_(unnamed)-424rv",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "enum (unnamed)"
        }
      ],
      "role": "symbol",
      "title": "enum (unnamed)",
      "type": "topic",
      "url": "/documentation/professional_video_applications/enum_(unnamed)-424rv"
    },
    "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/enum_(unnamed)-5fh3s": {
      "abstract": [
        {
          "text": "Errors returned by plug-in hosts applications.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/enum_(unnamed)-5fh3s",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "enum (unnamed)"
        }
      ],
      "role": "symbol",
      "title": "enum (unnamed)",
      "type": "topic",
      "url": "/documentation/professional_video_applications/enum_(unnamed)-5fh3s"
    },
    "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/enum_(unnamed)-5key8": {
      "abstract": [],
      "identifier": "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/enum_(unnamed)-5key8",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "enum (unnamed)"
        }
      ],
      "role": "symbol",
      "title": "enum (unnamed)",
      "type": "topic",
      "url": "/documentation/professional_video_applications/enum_(unnamed)-5key8"
    },
    "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/enum_(unnamed)-5ml7h": {
      "abstract": [],
      "identifier": "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/enum_(unnamed)-5ml7h",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "enum (unnamed)"
        }
      ],
      "role": "symbol",
      "title": "enum (unnamed)",
      "type": "topic",
      "url": "/documentation/professional_video_applications/enum_(unnamed)-5ml7h"
    },
    "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/enum_(unnamed)-5r2wt": {
      "abstract": [
        {
          "text": "Constants used to describe a set of color primaries.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/enum_(unnamed)-5r2wt",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "enum (unnamed)"
        }
      ],
      "role": "symbol",
      "title": "enum (unnamed)",
      "type": "topic",
      "url": "/documentation/professional_video_applications/enum_(unnamed)-5r2wt"
    },
    "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/enum_(unnamed)-5zg4z": {
      "abstract": [],
      "identifier": "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/enum_(unnamed)-5zg4z",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "enum (unnamed)"
        }
      ],
      "role": "symbol",
      "title": "enum (unnamed)",
      "type": "topic",
      "url": "/documentation/professional_video_applications/enum_(unnamed)-5zg4z"
    },
    "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/enum_(unnamed)-74key": {
      "abstract": [],
      "identifier": "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/enum_(unnamed)-74key",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "enum (unnamed)"
        }
      ],
      "role": "symbol",
      "title": "enum (unnamed)",
      "type": "topic",
      "url": "/documentation/professional_video_applications/enum_(unnamed)-74key"
    },
    "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/enum_(unnamed)-7b48r": {
      "abstract": [],
      "identifier": "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/enum_(unnamed)-7b48r",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "enum (unnamed)"
        }
      ],
      "role": "symbol",
      "title": "enum (unnamed)",
      "type": "topic",
      "url": "/documentation/professional_video_applications/enum_(unnamed)-7b48r"
    },
    "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/enum_(unnamed)-7jahq": {
      "abstract": [],
      "identifier": "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/enum_(unnamed)-7jahq",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "enum (unnamed)"
        }
      ],
      "role": "symbol",
      "title": "enum (unnamed)",
      "type": "topic",
      "url": "/documentation/professional_video_applications/enum_(unnamed)-7jahq"
    },
    "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/kFxParameterFlag_COLLAPSED": {
      "abstract": [
        {
          "text": "This group parameter’s subgroup is closed and its sub-parameters are not visible in the Inspector.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kFxParameterFlag_COLLAPSED"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/kFxParameterFlag_COLLAPSED",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kFxParameterFlag_COLLAPSED"
        }
      ],
      "role": "symbol",
      "title": "kFxParameterFlag_COLLAPSED",
      "type": "topic",
      "url": "/documentation/professional_video_applications/kfxparameterflag_collapsed"
    },
    "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/kFxParameterFlag_CURVE_EDITOR_HIDDEN": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kFxParameterFlag_CURVE_EDITOR_HIDDEN"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/kFxParameterFlag_CURVE_EDITOR_HIDDEN",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kFxParameterFlag_CURVE_EDITOR_HIDDEN"
        }
      ],
      "role": "symbol",
      "title": "kFxParameterFlag_CURVE_EDITOR_HIDDEN",
      "type": "topic",
      "url": "/documentation/professional_video_applications/kfxparameterflag_curve_editor_hidden"
    },
    "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/kFxParameterFlag_CUSTOM_UI": {
      "abstract": [
        {
          "text": "This parameter uses a custom user interface that replaces the standard parameter UI.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kFxParameterFlag_CUSTOM_UI"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/kFxParameterFlag_CUSTOM_UI",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kFxParameterFlag_CUSTOM_UI"
        }
      ],
      "role": "symbol",
      "title": "kFxParameterFlag_CUSTOM_UI",
      "type": "topic",
      "url": "/documentation/professional_video_applications/kfxparameterflag_custom_ui"
    },
    "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/kFxParameterFlag_DEFAULT": {
      "abstract": [
        {
          "text": "Convenience constant. No flags set.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kFxParameterFlag_DEFAULT"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/kFxParameterFlag_DEFAULT",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kFxParameterFlag_DEFAULT"
        }
      ],
      "role": "symbol",
      "title": "kFxParameterFlag_DEFAULT",
      "type": "topic",
      "url": "/documentation/professional_video_applications/kfxparameterflag_default"
    },
    "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/kFxParameterFlag_DISABLED": {
      "abstract": [
        {
          "text": "This parameter is dimmed and disabled.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kFxParameterFlag_DISABLED"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/kFxParameterFlag_DISABLED",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kFxParameterFlag_DISABLED"
        }
      ],
      "role": "symbol",
      "title": "kFxParameterFlag_DISABLED",
      "type": "topic",
      "url": "/documentation/professional_video_applications/kfxparameterflag_disabled"
    },
    "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/kFxParameterFlag_DONT_DISPLAY_IN_DASHBOARD": {
      "abstract": [
        {
          "text": "This parameter is not visible in the dashboard controls.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kFxParameterFlag_DONT_DISPLAY_IN_DASHBOARD"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/kFxParameterFlag_DONT_DISPLAY_IN_DASHBOARD",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kFxParameterFlag_DONT_DISPLAY_IN_DASHBOARD"
        }
      ],
      "role": "symbol",
      "title": "kFxParameterFlag_DONT_DISPLAY_IN_DASHBOARD",
      "type": "topic",
      "url": "/documentation/professional_video_applications/kfxparameterflag_dont_display_in_dashboard"
    },
    "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/kFxParameterFlag_DONT_REMAP_COLORS": {
      "abstract": [
        {
          "text": "Indicates that the host must not remap colors to sRGB.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kFxParameterFlag_DONT_REMAP_COLORS"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/kFxParameterFlag_DONT_REMAP_COLORS",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kFxParameterFlag_DONT_REMAP_COLORS"
        }
      ],
      "role": "symbol",
      "title": "kFxParameterFlag_DONT_REMAP_COLORS",
      "type": "topic",
      "url": "/documentation/professional_video_applications/kfxparameterflag_dont_remap_colors"
    },
    "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/kFxParameterFlag_DONT_SAVE": {
      "abstract": [
        {
          "text": "This parameter’s values are not saved or loaded.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kFxParameterFlag_DONT_SAVE"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/kFxParameterFlag_DONT_SAVE",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kFxParameterFlag_DONT_SAVE"
        }
      ],
      "role": "symbol",
      "title": "kFxParameterFlag_DONT_SAVE",
      "type": "topic",
      "url": "/documentation/professional_video_applications/kfxparameterflag_dont_save"
    },
    "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/kFxParameterFlag_HIDDEN": {
      "abstract": [
        {
          "text": "This parameter displays no UI to the user, but its value is saved/loaded.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kFxParameterFlag_HIDDEN"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/kFxParameterFlag_HIDDEN",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kFxParameterFlag_HIDDEN"
        }
      ],
      "role": "symbol",
      "title": "kFxParameterFlag_HIDDEN",
      "type": "topic",
      "url": "/documentation/professional_video_applications/kfxparameterflag_hidden"
    },
    "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/kFxParameterFlag_IGNORE_MINMAX": {
      "abstract": [
        {
          "text": "This parameter’s range is unbounded.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kFxParameterFlag_IGNORE_MINMAX"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/kFxParameterFlag_IGNORE_MINMAX",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kFxParameterFlag_IGNORE_MINMAX"
        }
      ],
      "role": "symbol",
      "title": "kFxParameterFlag_IGNORE_MINMAX",
      "type": "topic",
      "url": "/documentation/professional_video_applications/kfxparameterflag_ignore_minmax"
    },
    "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/kFxParameterFlag_NOT_ANIMATABLE": {
      "abstract": [
        {
          "text": "This parameter’s value is constant across time and cannot be animated.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kFxParameterFlag_NOT_ANIMATABLE"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/kFxParameterFlag_NOT_ANIMATABLE",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kFxParameterFlag_NOT_ANIMATABLE"
        }
      ],
      "role": "symbol",
      "title": "kFxParameterFlag_NOT_ANIMATABLE",
      "type": "topic",
      "url": "/documentation/professional_video_applications/kfxparameterflag_not_animatable"
    },
    "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/kFxParameterFlag_USE_FULL_VIEW_WIDTH": {
      "abstract": [
        {
          "text": "This parameter uses the full width of the view.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kFxParameterFlag_USE_FULL_VIEW_WIDTH"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/kFxParameterFlag_USE_FULL_VIEW_WIDTH",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kFxParameterFlag_USE_FULL_VIEW_WIDTH"
        }
      ],
      "role": "symbol",
      "title": "kFxParameterFlag_USE_FULL_VIEW_WIDTH",
      "type": "topic",
      "url": "/documentation/professional_video_applications/kfxparameterflag_use_full_view_width"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Anonymous-enumerations",
      "generated": true,
      "identifiers": [
        "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/enum_(unnamed)-14vbr",
        "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/enum_(unnamed)-187sa",
        "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/enum_(unnamed)-1tjh8",
        "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/enum_(unnamed)-2epbe",
        "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/enum_(unnamed)-35krj",
        "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/enum_(unnamed)-3fxly",
        "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/enum_(unnamed)-3hmov",
        "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/enum_(unnamed)-424rv",
        "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/enum_(unnamed)-5fh3s",
        "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/enum_(unnamed)-5key8",
        "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/enum_(unnamed)-5ml7h",
        "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/enum_(unnamed)-5r2wt",
        "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/enum_(unnamed)-5zg4z",
        "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/enum_(unnamed)-74key",
        "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/enum_(unnamed)-7b48r"
      ],
      "title": "Anonymous enumerations"
    }
  ],
  "topicSections": [
    {
      "anchor": "Constants",
      "identifiers": [
        "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/kFxParameterFlag_COLLAPSED",
        "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/kFxParameterFlag_CURVE_EDITOR_HIDDEN",
        "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/kFxParameterFlag_CUSTOM_UI",
        "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/kFxParameterFlag_DEFAULT",
        "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/kFxParameterFlag_DISABLED",
        "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/kFxParameterFlag_DONT_DISPLAY_IN_DASHBOARD",
        "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/kFxParameterFlag_DONT_SAVE",
        "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/kFxParameterFlag_HIDDEN",
        "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/kFxParameterFlag_IGNORE_MINMAX",
        "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/kFxParameterFlag_NOT_ANIMATABLE",
        "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/kFxParameterFlag_DONT_REMAP_COLORS",
        "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/kFxParameterFlag_USE_FULL_VIEW_WIDTH"
      ],
      "title": "Constants"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.professionalvideoapplications~1documentation~1professional_video_applications~1kFxParameterFlag_IGNORE_MINMAX/title",
          "value": "kFxParameterFlag_IGNORE_MINMAX"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.professionalvideoapplications~1documentation~1professional_video_applications~1kFxParameterFlag_IGNORE_MINMAX/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kFxParameterFlag_IGNORE_MINMAX"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.professionalvideoapplications~1documentation~1professional_video_applications~1kFxParameterFlag_DISABLED/title",
          "value": "kFxParameterFlag_DISABLED"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.professionalvideoapplications~1documentation~1professional_video_applications~1kFxParameterFlag_DISABLED/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kFxParameterFlag_DISABLED"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.professionalvideoapplications~1documentation~1professional_video_applications~1kFxParameterFlag_NOT_ANIMATABLE/title",
          "value": "kFxParameterFlag_NOT_ANIMATABLE"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.professionalvideoapplications~1documentation~1professional_video_applications~1kFxParameterFlag_NOT_ANIMATABLE/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kFxParameterFlag_NOT_ANIMATABLE"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.professionalvideoapplications~1documentation~1professional_video_applications~1kFxParameterFlag_CUSTOM_UI/title",
          "value": "kFxParameterFlag_CUSTOM_UI"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.professionalvideoapplications~1documentation~1professional_video_applications~1kFxParameterFlag_CUSTOM_UI/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kFxParameterFlag_CUSTOM_UI"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.professionalvideoapplications~1documentation~1professional_video_applications~1kFxParameterFlag_DEFAULT/title",
          "value": "kFxParameterFlag_DEFAULT"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.professionalvideoapplications~1documentation~1professional_video_applications~1kFxParameterFlag_DEFAULT/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kFxParameterFlag_DEFAULT"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.professionalvideoapplications~1documentation~1professional_video_applications~1kFxParameterFlag_HIDDEN/title",
          "value": "kFxParameterFlag_HIDDEN"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.professionalvideoapplications~1documentation~1professional_video_applications~1kFxParameterFlag_HIDDEN/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kFxParameterFlag_HIDDEN"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.professionalvideoapplications~1documentation~1professional_video_applications~1kFxParameterFlag_DONT_DISPLAY_IN_DASHBOARD/title",
          "value": "kFxParameterFlag_DONT_DISPLAY_IN_DASHBOARD"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.professionalvideoapplications~1documentation~1professional_video_applications~1kFxParameterFlag_DONT_DISPLAY_IN_DASHBOARD/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kFxParameterFlag_DONT_DISPLAY_IN_DASHBOARD"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.professionalvideoapplications~1documentation~1professional_video_applications~1kFxParameterFlag_DONT_SAVE/title",
          "value": "kFxParameterFlag_DONT_SAVE"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.professionalvideoapplications~1documentation~1professional_video_applications~1kFxParameterFlag_DONT_SAVE/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kFxParameterFlag_DONT_SAVE"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.professionalvideoapplications~1documentation~1professional_video_applications~1kFxParameterFlag_COLLAPSED/title",
          "value": "kFxParameterFlag_COLLAPSED"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.professionalvideoapplications~1documentation~1professional_video_applications~1kFxParameterFlag_COLLAPSED/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kFxParameterFlag_COLLAPSED"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.professionalvideoapplications~1documentation~1professional_video_applications~1kFxParameterFlag_DONT_REMAP_COLORS/title",
          "value": "kFxParameterFlag_DONT_REMAP_COLORS"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.professionalvideoapplications~1documentation~1professional_video_applications~1kFxParameterFlag_DONT_REMAP_COLORS/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kFxParameterFlag_DONT_REMAP_COLORS"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.professionalvideoapplications~1documentation~1professional_video_applications~1FxAnalysisAPI~1analysisStateForEffect()/title",
          "value": "analysisStateForEffect"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.professionalvideoapplications~1documentation~1professional_video_applications~1FxAnalysisAPI~1analysisStateForEffect()/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "analysisStateForEffect"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.professionalvideoapplications~1documentation~1professional_video_applications~1kFxParameterFlag_USE_FULL_VIEW_WIDTH/title",
          "value": "kFxParameterFlag_USE_FULL_VIEW_WIDTH"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.professionalvideoapplications~1documentation~1professional_video_applications~1kFxParameterFlag_USE_FULL_VIEW_WIDTH/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kFxParameterFlag_USE_FULL_VIEW_WIDTH"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.professionalvideoapplications~1documentation~1professional_video_applications~1kFxParameterFlag_CURVE_EDITOR_HIDDEN/title",
          "value": "kFxParameterFlag_CURVE_EDITOR_HIDDEN"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.professionalvideoapplications~1documentation~1professional_video_applications~1kFxParameterFlag_CURVE_EDITOR_HIDDEN/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kFxParameterFlag_CURVE_EDITOR_HIDDEN"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/professional_video_applications/enum_(unnamed)-7jahq"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
