{
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "occ",
    "url": "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/enum_(unnamed)-74key"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@Ea@kFxKeyframeStyle_Constant",
    "modules": [
      {
        "name": "Professional Video Applications"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "enum (unnamed)"
      }
    ],
    "role": "symbol",
    "roleHeading": "Enumeration",
    "symbolKind": "enum",
    "title": "enum (unnamed)"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "occ"
          ],
          "platforms": [
            "Unsupported OS: FxPlug"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "enum"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:i",
              "text": "unsigned int"
            },
            {
              "kind": "text",
              "text": ";"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications": {
      "abstract": [
        {
          "text": "Exchange data with Final Cut Pro, and create effects plug-ins for Final Cut Pro and Motion.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications",
      "kind": "symbol",
      "role": "collection",
      "title": "Professional Video Applications",
      "type": "topic",
      "url": "/documentation/professional_video_applications"
    },
    "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/FxAnalysisAPI/analysisStateForEffect()": {
      "abstract": [
        {
          "text": "Fetches the state of frame analysis for your plug-in.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "analysisStateForEffect"
        },
        {
          "kind": "text",
          "text": "() -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@FxAnalysisState",
          "text": "FxAnalysisState"
        }
      ],
      "identifier": "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/FxAnalysisAPI/analysisStateForEffect()",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "analysisStateForEffect"
        }
      ],
      "required": true,
      "role": "symbol",
      "title": "analysisStateForEffect()",
      "type": "topic",
      "url": "/documentation/professional_video_applications/fxanalysisapi/analysisstateforeffect()"
    },
    "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/enum_(unnamed)-14vbr": {
      "abstract": [
        {
          "text": "The field order.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/enum_(unnamed)-14vbr",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "enum (unnamed)"
        }
      ],
      "role": "symbol",
      "title": "enum (unnamed)",
      "type": "topic",
      "url": "/documentation/professional_video_applications/enum_(unnamed)-14vbr"
    },
    "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/enum_(unnamed)-187sa": {
      "abstract": [],
      "identifier": "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/enum_(unnamed)-187sa",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "enum (unnamed)"
        }
      ],
      "role": "symbol",
      "title": "enum (unnamed)",
      "type": "topic",
      "url": "/documentation/professional_video_applications/enum_(unnamed)-187sa"
    },
    "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/enum_(unnamed)-1tjh8": {
      "abstract": [
        {
          "text": "The possible states of analysis, as reported by the host application when queried with ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/FxAnalysisAPI/analysisStateForEffect()",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": ".",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/enum_(unnamed)-1tjh8",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "enum (unnamed)"
        }
      ],
      "role": "symbol",
      "title": "enum (unnamed)",
      "type": "topic",
      "url": "/documentation/professional_video_applications/enum_(unnamed)-1tjh8"
    },
    "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/enum_(unnamed)-2epbe": {
      "abstract": [],
      "identifier": "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/enum_(unnamed)-2epbe",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "enum (unnamed)"
        }
      ],
      "role": "symbol",
      "title": "enum (unnamed)",
      "type": "topic",
      "url": "/documentation/professional_video_applications/enum_(unnamed)-2epbe"
    },
    "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/enum_(unnamed)-35krj": {
      "abstract": [
        {
          "text": "The path blend mode.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/enum_(unnamed)-35krj",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "enum (unnamed)"
        }
      ],
      "role": "symbol",
      "title": "enum (unnamed)",
      "type": "topic",
      "url": "/documentation/professional_video_applications/enum_(unnamed)-35krj"
    },
    "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/enum_(unnamed)-3fxly": {
      "abstract": [
        {
          "text": "The bit-depth",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/enum_(unnamed)-3fxly",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "enum (unnamed)"
        }
      ],
      "role": "symbol",
      "title": "enum (unnamed)",
      "type": "topic",
      "url": "/documentation/professional_video_applications/enum_(unnamed)-3fxly"
    },
    "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/enum_(unnamed)-3hmov": {
      "abstract": [
        {
          "text": "The render quality.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/enum_(unnamed)-3hmov",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "enum (unnamed)"
        }
      ],
      "role": "symbol",
      "title": "enum (unnamed)",
      "type": "topic",
      "url": "/documentation/professional_video_applications/enum_(unnamed)-3hmov"
    },
    "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/enum_(unnamed)-424rv": {
      "abstract": [],
      "identifier": "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/enum_(unnamed)-424rv",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "enum (unnamed)"
        }
      ],
      "role": "symbol",
      "title": "enum (unnamed)",
      "type": "topic",
      "url": "/documentation/professional_video_applications/enum_(unnamed)-424rv"
    },
    "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/enum_(unnamed)-5fh3s": {
      "abstract": [
        {
          "text": "Errors returned by plug-in hosts applications.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/enum_(unnamed)-5fh3s",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "enum (unnamed)"
        }
      ],
      "role": "symbol",
      "title": "enum (unnamed)",
      "type": "topic",
      "url": "/documentation/professional_video_applications/enum_(unnamed)-5fh3s"
    },
    "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/enum_(unnamed)-5key8": {
      "abstract": [],
      "identifier": "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/enum_(unnamed)-5key8",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "enum (unnamed)"
        }
      ],
      "role": "symbol",
      "title": "enum (unnamed)",
      "type": "topic",
      "url": "/documentation/professional_video_applications/enum_(unnamed)-5key8"
    },
    "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/enum_(unnamed)-5ml7h": {
      "abstract": [],
      "identifier": "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/enum_(unnamed)-5ml7h",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "enum (unnamed)"
        }
      ],
      "role": "symbol",
      "title": "enum (unnamed)",
      "type": "topic",
      "url": "/documentation/professional_video_applications/enum_(unnamed)-5ml7h"
    },
    "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/enum_(unnamed)-5r2wt": {
      "abstract": [
        {
          "text": "Constants used to describe a set of color primaries.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/enum_(unnamed)-5r2wt",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "enum (unnamed)"
        }
      ],
      "role": "symbol",
      "title": "enum (unnamed)",
      "type": "topic",
      "url": "/documentation/professional_video_applications/enum_(unnamed)-5r2wt"
    },
    "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/enum_(unnamed)-5zg4z": {
      "abstract": [],
      "identifier": "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/enum_(unnamed)-5zg4z",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "enum (unnamed)"
        }
      ],
      "role": "symbol",
      "title": "enum (unnamed)",
      "type": "topic",
      "url": "/documentation/professional_video_applications/enum_(unnamed)-5zg4z"
    },
    "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/enum_(unnamed)-74key": {
      "abstract": [],
      "identifier": "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/enum_(unnamed)-74key",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "enum (unnamed)"
        }
      ],
      "role": "symbol",
      "title": "enum (unnamed)",
      "type": "topic",
      "url": "/documentation/professional_video_applications/enum_(unnamed)-74key"
    },
    "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/enum_(unnamed)-7b48r": {
      "abstract": [],
      "identifier": "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/enum_(unnamed)-7b48r",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "enum (unnamed)"
        }
      ],
      "role": "symbol",
      "title": "enum (unnamed)",
      "type": "topic",
      "url": "/documentation/professional_video_applications/enum_(unnamed)-7b48r"
    },
    "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/enum_(unnamed)-7jahq": {
      "abstract": [],
      "identifier": "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/enum_(unnamed)-7jahq",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "enum (unnamed)"
        }
      ],
      "role": "symbol",
      "title": "enum (unnamed)",
      "type": "topic",
      "url": "/documentation/professional_video_applications/enum_(unnamed)-7jahq"
    },
    "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/kFxKeyframeStyle_All": {
      "abstract": [
        {
          "text": "A mask for all types.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kFxKeyframeStyle_All"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        }
      ],
      "identifier": "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/kFxKeyframeStyle_All",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kFxKeyframeStyle_All"
        }
      ],
      "role": "symbol",
      "title": "kFxKeyframeStyle_All",
      "type": "topic",
      "url": "/documentation/professional_video_applications/kfxkeyframestyle_all"
    },
    "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/kFxKeyframeStyle_BSpline": {
      "abstract": [
        {
          "text": "The values are interpolated along a B-Spline.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kFxKeyframeStyle_BSpline"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        }
      ],
      "identifier": "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/kFxKeyframeStyle_BSpline",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kFxKeyframeStyle_BSpline"
        }
      ],
      "role": "symbol",
      "title": "kFxKeyframeStyle_BSpline",
      "type": "topic",
      "url": "/documentation/professional_video_applications/kfxkeyframestyle_bspline"
    },
    "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/kFxKeyframeStyle_Bezier": {
      "abstract": [
        {
          "text": "The values are interpolated along a cubic curve the user can control by varying the tangent handles.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kFxKeyframeStyle_Bezier"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        }
      ],
      "identifier": "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/kFxKeyframeStyle_Bezier",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kFxKeyframeStyle_Bezier"
        }
      ],
      "role": "symbol",
      "title": "kFxKeyframeStyle_Bezier",
      "type": "topic",
      "url": "/documentation/professional_video_applications/kfxkeyframestyle_bezier"
    },
    "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/kFxKeyframeStyle_Constant": {
      "abstract": [
        {
          "text": "Also known as “Hold,” constant keyframes have a constant value between keyframes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kFxKeyframeStyle_Constant"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        }
      ],
      "identifier": "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/kFxKeyframeStyle_Constant",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kFxKeyframeStyle_Constant"
        }
      ],
      "role": "symbol",
      "title": "kFxKeyframeStyle_Constant",
      "type": "topic",
      "url": "/documentation/professional_video_applications/kfxkeyframestyle_constant"
    },
    "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/kFxKeyframeStyle_Cubic": {
      "abstract": [
        {
          "text": "The values are interpolated along a cubic curve.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kFxKeyframeStyle_Cubic"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        }
      ],
      "identifier": "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/kFxKeyframeStyle_Cubic",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kFxKeyframeStyle_Cubic"
        }
      ],
      "role": "symbol",
      "title": "kFxKeyframeStyle_Cubic",
      "type": "topic",
      "url": "/documentation/professional_video_applications/kfxkeyframestyle_cubic"
    },
    "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/kFxKeyframeStyle_EaseIn": {
      "abstract": [
        {
          "text": "The values are interpolated along a pre-calculated cubic curve that smoothly transitions into the next value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kFxKeyframeStyle_EaseIn"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        }
      ],
      "identifier": "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/kFxKeyframeStyle_EaseIn",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kFxKeyframeStyle_EaseIn"
        }
      ],
      "role": "symbol",
      "title": "kFxKeyframeStyle_EaseIn",
      "type": "topic",
      "url": "/documentation/professional_video_applications/kfxkeyframestyle_easein"
    },
    "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/kFxKeyframeStyle_EaseOut": {
      "abstract": [
        {
          "text": "The values are interpolated along a pre-calculated cubic curve that smoothly transitions out of the previous value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kFxKeyframeStyle_EaseOut"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        }
      ],
      "identifier": "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/kFxKeyframeStyle_EaseOut",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kFxKeyframeStyle_EaseOut"
        }
      ],
      "role": "symbol",
      "title": "kFxKeyframeStyle_EaseOut",
      "type": "topic",
      "url": "/documentation/professional_video_applications/kfxkeyframestyle_easeout"
    },
    "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/kFxKeyframeStyle_Exponential": {
      "abstract": [
        {
          "text": "The values are interpolated along an exponential curve.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kFxKeyframeStyle_Exponential"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        }
      ],
      "identifier": "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/kFxKeyframeStyle_Exponential",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kFxKeyframeStyle_Exponential"
        }
      ],
      "role": "symbol",
      "title": "kFxKeyframeStyle_Exponential",
      "type": "topic",
      "url": "/documentation/professional_video_applications/kfxkeyframestyle_exponential"
    },
    "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/kFxKeyframeStyle_Linear": {
      "abstract": [
        {
          "text": "The values are interpolated along a straight line between keyframes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kFxKeyframeStyle_Linear"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        }
      ],
      "identifier": "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/kFxKeyframeStyle_Linear",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kFxKeyframeStyle_Linear"
        }
      ],
      "role": "symbol",
      "title": "kFxKeyframeStyle_Linear",
      "type": "topic",
      "url": "/documentation/professional_video_applications/kfxkeyframestyle_linear"
    },
    "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/kFxKeyframeStyle_Logarithmic": {
      "abstract": [
        {
          "text": "The values are interpolated along a logarithmic curve.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kFxKeyframeStyle_Logarithmic"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        }
      ],
      "identifier": "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/kFxKeyframeStyle_Logarithmic",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kFxKeyframeStyle_Logarithmic"
        }
      ],
      "role": "symbol",
      "title": "kFxKeyframeStyle_Logarithmic",
      "type": "topic",
      "url": "/documentation/professional_video_applications/kfxkeyframestyle_logarithmic"
    },
    "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/kFxKeyframeStyle_Mixed": {
      "abstract": [
        {
          "text": "The keyframe is a mixture of two of the other style types.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kFxKeyframeStyle_Mixed"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        }
      ],
      "identifier": "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/kFxKeyframeStyle_Mixed",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kFxKeyframeStyle_Mixed"
        }
      ],
      "role": "symbol",
      "title": "kFxKeyframeStyle_Mixed",
      "type": "topic",
      "url": "/documentation/professional_video_applications/kfxkeyframestyle_mixed"
    },
    "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/kFxKeyframeStyle_Quadratic": {
      "abstract": [
        {
          "text": "The values are interpolated along a quadratic curve.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kFxKeyframeStyle_Quadratic"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        }
      ],
      "identifier": "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/kFxKeyframeStyle_Quadratic",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kFxKeyframeStyle_Quadratic"
        }
      ],
      "role": "symbol",
      "title": "kFxKeyframeStyle_Quadratic",
      "type": "topic",
      "url": "/documentation/professional_video_applications/kfxkeyframestyle_quadratic"
    },
    "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/kFxKeyframeStyle_XSpline": {
      "abstract": [
        {
          "text": "The values are interpolated along a weighted X-Spline.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kFxKeyframeStyle_XSpline"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        }
      ],
      "identifier": "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/kFxKeyframeStyle_XSpline",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kFxKeyframeStyle_XSpline"
        }
      ],
      "role": "symbol",
      "title": "kFxKeyframeStyle_XSpline",
      "type": "topic",
      "url": "/documentation/professional_video_applications/kfxkeyframestyle_xspline"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Anonymous-enumerations",
      "generated": true,
      "identifiers": [
        "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/enum_(unnamed)-14vbr",
        "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/enum_(unnamed)-187sa",
        "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/enum_(unnamed)-1tjh8",
        "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/enum_(unnamed)-2epbe",
        "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/enum_(unnamed)-35krj",
        "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/enum_(unnamed)-3fxly",
        "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/enum_(unnamed)-3hmov",
        "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/enum_(unnamed)-424rv",
        "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/enum_(unnamed)-5fh3s",
        "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/enum_(unnamed)-5key8",
        "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/enum_(unnamed)-5ml7h",
        "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/enum_(unnamed)-5r2wt",
        "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/enum_(unnamed)-5zg4z",
        "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/enum_(unnamed)-7b48r",
        "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/enum_(unnamed)-7jahq"
      ],
      "title": "Anonymous enumerations"
    }
  ],
  "topicSections": [
    {
      "anchor": "Constants",
      "identifiers": [
        "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/kFxKeyframeStyle_All",
        "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/kFxKeyframeStyle_BSpline",
        "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/kFxKeyframeStyle_Bezier",
        "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/kFxKeyframeStyle_Constant",
        "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/kFxKeyframeStyle_Cubic",
        "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/kFxKeyframeStyle_EaseIn",
        "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/kFxKeyframeStyle_EaseOut",
        "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/kFxKeyframeStyle_Exponential",
        "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/kFxKeyframeStyle_Linear",
        "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/kFxKeyframeStyle_Logarithmic",
        "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/kFxKeyframeStyle_Mixed",
        "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/kFxKeyframeStyle_Quadratic",
        "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/kFxKeyframeStyle_XSpline"
      ],
      "title": "Constants"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.professionalvideoapplications~1documentation~1professional_video_applications~1kFxKeyframeStyle_EaseIn/title",
          "value": "kFxKeyframeStyle_EaseIn"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.professionalvideoapplications~1documentation~1professional_video_applications~1kFxKeyframeStyle_EaseIn/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kFxKeyframeStyle_EaseIn"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.professionalvideoapplications~1documentation~1professional_video_applications~1kFxKeyframeStyle_Exponential/title",
          "value": "kFxKeyframeStyle_Exponential"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.professionalvideoapplications~1documentation~1professional_video_applications~1kFxKeyframeStyle_Exponential/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kFxKeyframeStyle_Exponential"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.professionalvideoapplications~1documentation~1professional_video_applications~1kFxKeyframeStyle_XSpline/title",
          "value": "kFxKeyframeStyle_XSpline"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.professionalvideoapplications~1documentation~1professional_video_applications~1kFxKeyframeStyle_XSpline/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kFxKeyframeStyle_XSpline"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.professionalvideoapplications~1documentation~1professional_video_applications~1kFxKeyframeStyle_EaseOut/title",
          "value": "kFxKeyframeStyle_EaseOut"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.professionalvideoapplications~1documentation~1professional_video_applications~1kFxKeyframeStyle_EaseOut/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kFxKeyframeStyle_EaseOut"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.professionalvideoapplications~1documentation~1professional_video_applications~1kFxKeyframeStyle_Quadratic/title",
          "value": "kFxKeyframeStyle_Quadratic"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.professionalvideoapplications~1documentation~1professional_video_applications~1kFxKeyframeStyle_Quadratic/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kFxKeyframeStyle_Quadratic"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.professionalvideoapplications~1documentation~1professional_video_applications~1kFxKeyframeStyle_All/title",
          "value": "kFxKeyframeStyle_All"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.professionalvideoapplications~1documentation~1professional_video_applications~1kFxKeyframeStyle_All/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kFxKeyframeStyle_All"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.professionalvideoapplications~1documentation~1professional_video_applications~1kFxKeyframeStyle_Cubic/title",
          "value": "kFxKeyframeStyle_Cubic"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.professionalvideoapplications~1documentation~1professional_video_applications~1kFxKeyframeStyle_Cubic/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kFxKeyframeStyle_Cubic"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.professionalvideoapplications~1documentation~1professional_video_applications~1kFxKeyframeStyle_Mixed/title",
          "value": "kFxKeyframeStyle_Mixed"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.professionalvideoapplications~1documentation~1professional_video_applications~1kFxKeyframeStyle_Mixed/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kFxKeyframeStyle_Mixed"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.professionalvideoapplications~1documentation~1professional_video_applications~1kFxKeyframeStyle_Constant/title",
          "value": "kFxKeyframeStyle_Constant"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.professionalvideoapplications~1documentation~1professional_video_applications~1kFxKeyframeStyle_Constant/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kFxKeyframeStyle_Constant"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.professionalvideoapplications~1documentation~1professional_video_applications~1kFxKeyframeStyle_Bezier/title",
          "value": "kFxKeyframeStyle_Bezier"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.professionalvideoapplications~1documentation~1professional_video_applications~1kFxKeyframeStyle_Bezier/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kFxKeyframeStyle_Bezier"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.professionalvideoapplications~1documentation~1professional_video_applications~1kFxKeyframeStyle_BSpline/title",
          "value": "kFxKeyframeStyle_BSpline"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.professionalvideoapplications~1documentation~1professional_video_applications~1kFxKeyframeStyle_BSpline/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kFxKeyframeStyle_BSpline"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.professionalvideoapplications~1documentation~1professional_video_applications~1kFxKeyframeStyle_Logarithmic/title",
          "value": "kFxKeyframeStyle_Logarithmic"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.professionalvideoapplications~1documentation~1professional_video_applications~1kFxKeyframeStyle_Logarithmic/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kFxKeyframeStyle_Logarithmic"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.professionalvideoapplications~1documentation~1professional_video_applications~1FxAnalysisAPI~1analysisStateForEffect()/title",
          "value": "analysisStateForEffect"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.professionalvideoapplications~1documentation~1professional_video_applications~1FxAnalysisAPI~1analysisStateForEffect()/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "analysisStateForEffect"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.professionalvideoapplications~1documentation~1professional_video_applications~1kFxKeyframeStyle_Linear/title",
          "value": "kFxKeyframeStyle_Linear"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.professionalvideoapplications~1documentation~1professional_video_applications~1kFxKeyframeStyle_Linear/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kFxKeyframeStyle_Linear"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/professional_video_applications/enum_(unnamed)-74key"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
