{
  "abstract": [
    {
      "text": "Errors returned by plug-in hosts applications.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "occ",
    "url": "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/enum_(unnamed)-5fh3s"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@Ea@kFxError_Success",
    "modules": [
      {
        "name": "Professional Video Applications"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "enum (unnamed)"
      }
    ],
    "role": "symbol",
    "roleHeading": "Enumeration",
    "symbolKind": "enum",
    "title": "enum (unnamed)"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "occ"
          ],
          "platforms": [
            "Unsupported OS: FxPlug"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "enum"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:i",
              "text": "unsigned int"
            },
            {
              "kind": "text",
              "text": ";"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications": {
      "abstract": [
        {
          "text": "Exchange data with Final Cut Pro, and create effects plug-ins for Final Cut Pro and Motion.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications",
      "kind": "symbol",
      "role": "collection",
      "title": "Professional Video Applications",
      "type": "topic",
      "url": "/documentation/professional_video_applications"
    },
    "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/FxAnalysisAPI/analysisStateForEffect()": {
      "abstract": [
        {
          "text": "Fetches the state of frame analysis for your plug-in.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "analysisStateForEffect"
        },
        {
          "kind": "text",
          "text": "() -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@FxAnalysisState",
          "text": "FxAnalysisState"
        }
      ],
      "identifier": "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/FxAnalysisAPI/analysisStateForEffect()",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "analysisStateForEffect"
        }
      ],
      "required": true,
      "role": "symbol",
      "title": "analysisStateForEffect()",
      "type": "topic",
      "url": "/documentation/professional_video_applications/fxanalysisapi/analysisstateforeffect()"
    },
    "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/enum_(unnamed)-14vbr": {
      "abstract": [
        {
          "text": "The field order.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/enum_(unnamed)-14vbr",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "enum (unnamed)"
        }
      ],
      "role": "symbol",
      "title": "enum (unnamed)",
      "type": "topic",
      "url": "/documentation/professional_video_applications/enum_(unnamed)-14vbr"
    },
    "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/enum_(unnamed)-187sa": {
      "abstract": [],
      "identifier": "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/enum_(unnamed)-187sa",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "enum (unnamed)"
        }
      ],
      "role": "symbol",
      "title": "enum (unnamed)",
      "type": "topic",
      "url": "/documentation/professional_video_applications/enum_(unnamed)-187sa"
    },
    "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/enum_(unnamed)-1tjh8": {
      "abstract": [
        {
          "text": "The possible states of analysis, as reported by the host application when queried with ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/FxAnalysisAPI/analysisStateForEffect()",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": ".",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/enum_(unnamed)-1tjh8",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "enum (unnamed)"
        }
      ],
      "role": "symbol",
      "title": "enum (unnamed)",
      "type": "topic",
      "url": "/documentation/professional_video_applications/enum_(unnamed)-1tjh8"
    },
    "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/enum_(unnamed)-2epbe": {
      "abstract": [],
      "identifier": "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/enum_(unnamed)-2epbe",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "enum (unnamed)"
        }
      ],
      "role": "symbol",
      "title": "enum (unnamed)",
      "type": "topic",
      "url": "/documentation/professional_video_applications/enum_(unnamed)-2epbe"
    },
    "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/enum_(unnamed)-35krj": {
      "abstract": [
        {
          "text": "The path blend mode.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/enum_(unnamed)-35krj",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "enum (unnamed)"
        }
      ],
      "role": "symbol",
      "title": "enum (unnamed)",
      "type": "topic",
      "url": "/documentation/professional_video_applications/enum_(unnamed)-35krj"
    },
    "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/enum_(unnamed)-3fxly": {
      "abstract": [
        {
          "text": "The bit-depth",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/enum_(unnamed)-3fxly",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "enum (unnamed)"
        }
      ],
      "role": "symbol",
      "title": "enum (unnamed)",
      "type": "topic",
      "url": "/documentation/professional_video_applications/enum_(unnamed)-3fxly"
    },
    "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/enum_(unnamed)-3hmov": {
      "abstract": [
        {
          "text": "The render quality.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/enum_(unnamed)-3hmov",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "enum (unnamed)"
        }
      ],
      "role": "symbol",
      "title": "enum (unnamed)",
      "type": "topic",
      "url": "/documentation/professional_video_applications/enum_(unnamed)-3hmov"
    },
    "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/enum_(unnamed)-424rv": {
      "abstract": [],
      "identifier": "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/enum_(unnamed)-424rv",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "enum (unnamed)"
        }
      ],
      "role": "symbol",
      "title": "enum (unnamed)",
      "type": "topic",
      "url": "/documentation/professional_video_applications/enum_(unnamed)-424rv"
    },
    "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/enum_(unnamed)-5fh3s": {
      "abstract": [
        {
          "text": "Errors returned by plug-in hosts applications.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/enum_(unnamed)-5fh3s",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "enum (unnamed)"
        }
      ],
      "role": "symbol",
      "title": "enum (unnamed)",
      "type": "topic",
      "url": "/documentation/professional_video_applications/enum_(unnamed)-5fh3s"
    },
    "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/enum_(unnamed)-5key8": {
      "abstract": [],
      "identifier": "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/enum_(unnamed)-5key8",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "enum (unnamed)"
        }
      ],
      "role": "symbol",
      "title": "enum (unnamed)",
      "type": "topic",
      "url": "/documentation/professional_video_applications/enum_(unnamed)-5key8"
    },
    "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/enum_(unnamed)-5ml7h": {
      "abstract": [],
      "identifier": "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/enum_(unnamed)-5ml7h",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "enum (unnamed)"
        }
      ],
      "role": "symbol",
      "title": "enum (unnamed)",
      "type": "topic",
      "url": "/documentation/professional_video_applications/enum_(unnamed)-5ml7h"
    },
    "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/enum_(unnamed)-5r2wt": {
      "abstract": [
        {
          "text": "Constants used to describe a set of color primaries.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/enum_(unnamed)-5r2wt",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "enum (unnamed)"
        }
      ],
      "role": "symbol",
      "title": "enum (unnamed)",
      "type": "topic",
      "url": "/documentation/professional_video_applications/enum_(unnamed)-5r2wt"
    },
    "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/enum_(unnamed)-5zg4z": {
      "abstract": [],
      "identifier": "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/enum_(unnamed)-5zg4z",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "enum (unnamed)"
        }
      ],
      "role": "symbol",
      "title": "enum (unnamed)",
      "type": "topic",
      "url": "/documentation/professional_video_applications/enum_(unnamed)-5zg4z"
    },
    "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/enum_(unnamed)-74key": {
      "abstract": [],
      "identifier": "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/enum_(unnamed)-74key",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "enum (unnamed)"
        }
      ],
      "role": "symbol",
      "title": "enum (unnamed)",
      "type": "topic",
      "url": "/documentation/professional_video_applications/enum_(unnamed)-74key"
    },
    "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/enum_(unnamed)-7b48r": {
      "abstract": [],
      "identifier": "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/enum_(unnamed)-7b48r",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "enum (unnamed)"
        }
      ],
      "role": "symbol",
      "title": "enum (unnamed)",
      "type": "topic",
      "url": "/documentation/professional_video_applications/enum_(unnamed)-7b48r"
    },
    "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/enum_(unnamed)-7jahq": {
      "abstract": [],
      "identifier": "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/enum_(unnamed)-7jahq",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "enum (unnamed)"
        }
      ],
      "role": "symbol",
      "title": "enum (unnamed)",
      "type": "topic",
      "url": "/documentation/professional_video_applications/enum_(unnamed)-7jahq"
    },
    "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/kFxError_APIUnavailable": {
      "abstract": [
        {
          "text": "The requested API cannot be used by the plug-in at this time.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kFxError_APIUnavailable"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/kFxError_APIUnavailable",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kFxError_APIUnavailable"
        }
      ],
      "role": "symbol",
      "title": "kFxError_APIUnavailable",
      "type": "topic",
      "url": "/documentation/professional_video_applications/kfxerror_apiunavailable"
    },
    "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/kFxError_AnalysisError": {
      "abstract": [
        {
          "text": "An error with analysis occurred.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kFxError_AnalysisError"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/kFxError_AnalysisError",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kFxError_AnalysisError"
        }
      ],
      "role": "symbol",
      "title": "kFxError_AnalysisError",
      "type": "topic",
      "url": "/documentation/professional_video_applications/kfxerror_analysiserror"
    },
    "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/kFxError_AnalysisExtensionNotFound": {
      "abstract": [
        {
          "text": "Analysis extension not found.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kFxError_AnalysisExtensionNotFound"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/kFxError_AnalysisExtensionNotFound",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kFxError_AnalysisExtensionNotFound"
        }
      ],
      "role": "symbol",
      "title": "kFxError_AnalysisExtensionNotFound",
      "type": "topic",
      "url": "/documentation/professional_video_applications/kfxerror_analysisextensionnotfound"
    },
    "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/kFxError_CommandNotProcessed": {
      "abstract": [
        {
          "text": "Unable to complete the command sent to the ",
          "type": "text"
        },
        {
          "code": "FxCommandAPI",
          "type": "codeVoice"
        },
        {
          "text": ".",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kFxError_CommandNotProcessed"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/kFxError_CommandNotProcessed",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kFxError_CommandNotProcessed"
        }
      ],
      "role": "symbol",
      "title": "kFxError_CommandNotProcessed",
      "type": "topic",
      "url": "/documentation/professional_video_applications/kfxerror_commandnotprocessed"
    },
    "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/kFxError_HostUnreachable": {
      "abstract": [
        {
          "text": "The host application cannot be reached to complete an operation.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kFxError_HostUnreachable"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/kFxError_HostUnreachable",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kFxError_HostUnreachable"
        }
      ],
      "role": "symbol",
      "title": "kFxError_HostUnreachable",
      "type": "topic",
      "url": "/documentation/professional_video_applications/kfxerror_hostunreachable"
    },
    "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/kFxError_InvalidColorGamut": {
      "abstract": [
        {
          "text": "A constant that indicates that an attempt to get color gamut info from the host failed.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kFxError_InvalidColorGamut"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/kFxError_InvalidColorGamut",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kFxError_InvalidColorGamut"
        }
      ],
      "role": "symbol",
      "title": "kFxError_InvalidColorGamut",
      "type": "topic",
      "url": "/documentation/professional_video_applications/kfxerror_invalidcolorgamut"
    },
    "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/kFxError_InvalidDataLength": {
      "abstract": [
        {
          "text": "An invalid data length was found by the plug-in while the host or framework was decoding data.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kFxError_InvalidDataLength"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/kFxError_InvalidDataLength",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kFxError_InvalidDataLength"
        }
      ],
      "role": "symbol",
      "title": "kFxError_InvalidDataLength",
      "type": "topic",
      "url": "/documentation/professional_video_applications/kfxerror_invaliddatalength"
    },
    "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/kFxError_InvalidKeyframeIndex": {
      "abstract": [
        {
          "text": "The plug-in passed an invalid keyframe index to the host.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kFxError_InvalidKeyframeIndex"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/kFxError_InvalidKeyframeIndex",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kFxError_InvalidKeyframeIndex"
        }
      ],
      "role": "symbol",
      "title": "kFxError_InvalidKeyframeIndex",
      "type": "topic",
      "url": "/documentation/professional_video_applications/kfxerror_invalidkeyframeindex"
    },
    "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/kFxError_InvalidLightAccess": {
      "abstract": [
        {
          "text": "An attempt was made by the plug-in to access lights without first requesting light access.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kFxError_InvalidLightAccess"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/kFxError_InvalidLightAccess",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kFxError_InvalidLightAccess"
        }
      ],
      "role": "symbol",
      "title": "kFxError_InvalidLightAccess",
      "type": "topic",
      "url": "/documentation/professional_video_applications/kfxerror_invalidlightaccess"
    },
    "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/kFxError_InvalidParameter": {
      "abstract": [
        {
          "text": "A parameter sent by the caller to an API method was invalid.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kFxError_InvalidParameter"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/kFxError_InvalidParameter",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kFxError_InvalidParameter"
        }
      ],
      "role": "symbol",
      "title": "kFxError_InvalidParameter",
      "type": "topic",
      "url": "/documentation/professional_video_applications/kfxerror_invalidparameter"
    },
    "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/kFxError_InvalidParameterChannelIndex": {
      "abstract": [
        {
          "text": "The plug-in passed an invalid channel number for a parameter to the host.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kFxError_InvalidParameterChannelIndex"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/kFxError_InvalidParameterChannelIndex",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kFxError_InvalidParameterChannelIndex"
        }
      ],
      "role": "symbol",
      "title": "kFxError_InvalidParameterChannelIndex",
      "type": "topic",
      "url": "/documentation/professional_video_applications/kfxerror_invalidparameterchannelindex"
    },
    "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/kFxError_InvalidParameterID": {
      "abstract": [
        {
          "text": "The plug-in passed an invalid parameter to the host.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kFxError_InvalidParameterID"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/kFxError_InvalidParameterID",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kFxError_InvalidParameterID"
        }
      ],
      "role": "symbol",
      "title": "kFxError_InvalidParameterID",
      "type": "topic",
      "url": "/documentation/professional_video_applications/kfxerror_invalidparameterid"
    },
    "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/kFxError_InvalidPathID": {
      "abstract": [
        {
          "text": "No path with that ID exists.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kFxError_InvalidPathID"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/kFxError_InvalidPathID",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kFxError_InvalidPathID"
        }
      ],
      "role": "symbol",
      "title": "kFxError_InvalidPathID",
      "type": "topic",
      "url": "/documentation/professional_video_applications/kfxerror_invalidpathid"
    },
    "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/kFxError_InvalidPathIndex": {
      "abstract": [
        {
          "text": "The index is greater than the number of paths.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kFxError_InvalidPathIndex"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/kFxError_InvalidPathIndex",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kFxError_InvalidPathIndex"
        }
      ],
      "role": "symbol",
      "title": "kFxError_InvalidPathIndex",
      "type": "topic",
      "url": "/documentation/professional_video_applications/kfxerror_invalidpathindex"
    },
    "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/kFxError_InvalidPathStyle": {
      "abstract": [
        {
          "text": "An invalid path style was used by the plug-in.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kFxError_InvalidPathStyle"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/kFxError_InvalidPathStyle",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kFxError_InvalidPathStyle"
        }
      ],
      "role": "symbol",
      "title": "kFxError_InvalidPathStyle",
      "type": "topic",
      "url": "/documentation/professional_video_applications/kfxerror_invalidpathstyle"
    },
    "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/kFxError_InvalidPaths": {
      "abstract": [
        {
          "text": "A constant that indicates that an attempt to get path info from the host failed.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kFxError_InvalidPaths"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/kFxError_InvalidPaths",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kFxError_InvalidPaths"
        }
      ],
      "role": "symbol",
      "title": "kFxError_InvalidPaths",
      "type": "topic",
      "url": "/documentation/professional_video_applications/kfxerror_invalidpaths"
    },
    "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/kFxError_InvalidSegmentIndex": {
      "abstract": [
        {
          "text": "The index of the segment of the path is greater than the number of segments in the path.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kFxError_InvalidSegmentIndex"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/kFxError_InvalidSegmentIndex",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kFxError_InvalidSegmentIndex"
        }
      ],
      "role": "symbol",
      "title": "kFxError_InvalidSegmentIndex",
      "type": "topic",
      "url": "/documentation/professional_video_applications/kfxerror_invalidsegmentindex"
    },
    "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/kFxError_InvalidTime": {
      "abstract": [
        {
          "text": "The plug-in passed an invalid time to the host.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kFxError_InvalidTime"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/kFxError_InvalidTime",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kFxError_InvalidTime"
        }
      ],
      "role": "symbol",
      "title": "kFxError_InvalidTime",
      "type": "topic",
      "url": "/documentation/professional_video_applications/kfxerror_invalidtime"
    },
    "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/kFxError_InvalidTiming": {
      "abstract": [
        {
          "text": "A constant that indicates that an attempt to get timing info from the host failed.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kFxError_InvalidTiming"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/kFxError_InvalidTiming",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kFxError_InvalidTiming"
        }
      ],
      "role": "symbol",
      "title": "kFxError_InvalidTiming",
      "type": "topic",
      "url": "/documentation/professional_video_applications/kfxerror_invalidtiming"
    },
    "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/kFxError_LostConnectionToPlugin": {
      "abstract": [
        {
          "text": "The connection between the host and the plug-in was lost.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kFxError_LostConnectionToPlugin"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/kFxError_LostConnectionToPlugin",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kFxError_LostConnectionToPlugin"
        }
      ],
      "role": "symbol",
      "title": "kFxError_LostConnectionToPlugin",
      "type": "topic",
      "url": "/documentation/professional_video_applications/kfxerror_lostconnectiontoplugin"
    },
    "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/kFxError_MemoryNotAllocated": {
      "abstract": [
        {
          "text": "Unable to free a memory resource because it is not allocated.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kFxError_MemoryNotAllocated"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/kFxError_MemoryNotAllocated",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kFxError_MemoryNotAllocated"
        }
      ],
      "role": "symbol",
      "title": "kFxError_MemoryNotAllocated",
      "type": "topic",
      "url": "/documentation/professional_video_applications/kfxerror_memorynotallocated"
    },
    "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/kFxError_NoDocumentFound": {
      "abstract": [
        {
          "text": "The FxPlug is not in a project.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kFxError_NoDocumentFound"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/kFxError_NoDocumentFound",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kFxError_NoDocumentFound"
        }
      ],
      "role": "symbol",
      "title": "kFxError_NoDocumentFound",
      "type": "topic",
      "url": "/documentation/professional_video_applications/kfxerror_nodocumentfound"
    },
    "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/kFxError_NoMediaFolder": {
      "abstract": [
        {
          "text": "The project has no media folder.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kFxError_NoMediaFolder"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/kFxError_NoMediaFolder",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kFxError_NoMediaFolder"
        }
      ],
      "role": "symbol",
      "title": "kFxError_NoMediaFolder",
      "type": "topic",
      "url": "/documentation/professional_video_applications/kfxerror_nomediafolder"
    },
    "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/kFxError_NoViewFound": {
      "abstract": [
        {
          "text": "A constant that indicates the remote window view wasn’t retrieved by the host.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kFxError_NoViewFound"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/kFxError_NoViewFound",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kFxError_NoViewFound"
        }
      ],
      "role": "symbol",
      "title": "kFxError_NoViewFound",
      "type": "topic",
      "url": "/documentation/professional_video_applications/kfxerror_noviewfound"
    },
    "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/kFxError_NotYetImplemented": {
      "abstract": [
        {
          "text": "The host application has not yet implemented the API.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kFxError_NotYetImplemented"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/kFxError_NotYetImplemented",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kFxError_NotYetImplemented"
        }
      ],
      "role": "symbol",
      "title": "kFxError_NotYetImplemented",
      "type": "topic",
      "url": "/documentation/professional_video_applications/kfxerror_notyetimplemented"
    },
    "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/kFxError_OpenGLError": {
      "abstract": [
        {
          "text": "OpenGL returned an error.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kFxError_OpenGLError"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/kFxError_OpenGLError",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kFxError_OpenGLError"
        }
      ],
      "role": "symbol",
      "title": "kFxError_OpenGLError",
      "type": "topic",
      "url": "/documentation/professional_video_applications/kfxerror_openglerror"
    },
    "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/kFxError_OutOfMemory": {
      "abstract": [
        {
          "text": "Unable to allocate memory.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kFxError_OutOfMemory"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/kFxError_OutOfMemory",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kFxError_OutOfMemory"
        }
      ],
      "role": "symbol",
      "title": "kFxError_OutOfMemory",
      "type": "topic",
      "url": "/documentation/professional_video_applications/kfxerror_outofmemory"
    },
    "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/kFxError_PluginNotFound": {
      "abstract": [
        {
          "text": "The host couldn’t find the plug-in.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kFxError_PluginNotFound"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/kFxError_PluginNotFound",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kFxError_PluginNotFound"
        }
      ],
      "role": "symbol",
      "title": "kFxError_PluginNotFound",
      "type": "topic",
      "url": "/documentation/professional_video_applications/kfxerror_pluginnotfound"
    },
    "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/kFxError_Success": {
      "abstract": [
        {
          "text": "No error occurred.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kFxError_Success"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/kFxError_Success",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kFxError_Success"
        }
      ],
      "role": "symbol",
      "title": "kFxError_Success",
      "type": "topic",
      "url": "/documentation/professional_video_applications/kfxerror_success"
    },
    "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/kFxError_ThirdPartyDeveloperStart": {
      "abstract": [
        {
          "text": "All third-party error values must be greater than or equal to this value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kFxError_ThirdPartyDeveloperStart"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/kFxError_ThirdPartyDeveloperStart",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kFxError_ThirdPartyDeveloperStart"
        }
      ],
      "role": "symbol",
      "title": "kFxError_ThirdPartyDeveloperStart",
      "type": "topic",
      "url": "/documentation/professional_video_applications/kfxerror_thirdpartydeveloperstart"
    },
    "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/kFxError_UnableToCreateDynamicRegistrationEndpoint": {
      "abstract": [
        {
          "text": "The XPC service was unable to create a new XPC Listener Endpoint for communication with the host application.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kFxError_UnableToCreateDynamicRegistrationEndpoint"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/kFxError_UnableToCreateDynamicRegistrationEndpoint",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kFxError_UnableToCreateDynamicRegistrationEndpoint"
        }
      ],
      "role": "symbol",
      "title": "kFxError_UnableToCreateDynamicRegistrationEndpoint",
      "type": "topic",
      "url": "/documentation/professional_video_applications/kfxerror_unabletocreatedynamicregistrationendpoint"
    },
    "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/kFxError_UnableToInstantiateDynamicRegistrar": {
      "abstract": [
        {
          "text": "The XPC service was unable to instantiate a dynamic registrar object.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kFxError_UnableToInstantiateDynamicRegistrar"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/kFxError_UnableToInstantiateDynamicRegistrar",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kFxError_UnableToInstantiateDynamicRegistrar"
        }
      ],
      "role": "symbol",
      "title": "kFxError_UnableToInstantiateDynamicRegistrar",
      "type": "topic",
      "url": "/documentation/professional_video_applications/kfxerror_unabletoinstantiatedynamicregistrar"
    },
    "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/kFxError_UnableToMovePlayhead": {
      "abstract": [
        {
          "text": "An attempt by the host to move the playhead failed.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kFxError_UnableToMovePlayhead"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/kFxError_UnableToMovePlayhead",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kFxError_UnableToMovePlayhead"
        }
      ],
      "role": "symbol",
      "title": "kFxError_UnableToMovePlayhead",
      "type": "topic",
      "url": "/documentation/professional_video_applications/kfxerror_unabletomoveplayhead"
    },
    "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/kFxError_UnableToObtainProjectAspectRatio": {
      "abstract": [
        {
          "text": "The host couldn’t obtain the project’s aspect ratio.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kFxError_UnableToObtainProjectAspectRatio"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/kFxError_UnableToObtainProjectAspectRatio",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kFxError_UnableToObtainProjectAspectRatio"
        }
      ],
      "role": "symbol",
      "title": "kFxError_UnableToObtainProjectAspectRatio",
      "type": "topic",
      "url": "/documentation/professional_video_applications/kfxerror_unabletoobtainprojectaspectratio"
    },
    "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/kFxError_UserCancelled": {
      "abstract": [
        {
          "text": "An analysis operation was canceled by the user.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kFxError_UserCancelled"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/kFxError_UserCancelled",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kFxError_UserCancelled"
        }
      ],
      "role": "symbol",
      "title": "kFxError_UserCancelled",
      "type": "topic",
      "url": "/documentation/professional_video_applications/kfxerror_usercancelled"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Anonymous-enumerations",
      "generated": true,
      "identifiers": [
        "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/enum_(unnamed)-14vbr",
        "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/enum_(unnamed)-187sa",
        "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/enum_(unnamed)-1tjh8",
        "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/enum_(unnamed)-2epbe",
        "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/enum_(unnamed)-35krj",
        "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/enum_(unnamed)-3fxly",
        "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/enum_(unnamed)-3hmov",
        "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/enum_(unnamed)-424rv",
        "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/enum_(unnamed)-5key8",
        "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/enum_(unnamed)-5ml7h",
        "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/enum_(unnamed)-5r2wt",
        "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/enum_(unnamed)-5zg4z",
        "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/enum_(unnamed)-74key",
        "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/enum_(unnamed)-7b48r",
        "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/enum_(unnamed)-7jahq"
      ],
      "title": "Anonymous enumerations"
    }
  ],
  "topicSections": [
    {
      "anchor": "Constants",
      "identifiers": [
        "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/kFxError_AnalysisError",
        "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/kFxError_AnalysisExtensionNotFound",
        "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/kFxError_APIUnavailable",
        "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/kFxError_CommandNotProcessed",
        "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/kFxError_HostUnreachable",
        "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/kFxError_InvalidColorGamut",
        "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/kFxError_InvalidDataLength",
        "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/kFxError_InvalidKeyframeIndex",
        "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/kFxError_InvalidLightAccess",
        "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/kFxError_InvalidParameter",
        "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/kFxError_InvalidParameterChannelIndex",
        "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/kFxError_InvalidParameterID",
        "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/kFxError_InvalidPathID",
        "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/kFxError_InvalidPathIndex",
        "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/kFxError_InvalidPaths",
        "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/kFxError_InvalidPathStyle",
        "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/kFxError_InvalidSegmentIndex",
        "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/kFxError_InvalidTime",
        "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/kFxError_InvalidTiming",
        "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/kFxError_LostConnectionToPlugin",
        "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/kFxError_MemoryNotAllocated",
        "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/kFxError_NoDocumentFound",
        "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/kFxError_NoMediaFolder",
        "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/kFxError_NotYetImplemented",
        "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/kFxError_NoViewFound",
        "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/kFxError_OpenGLError",
        "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/kFxError_OutOfMemory",
        "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/kFxError_PluginNotFound",
        "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/kFxError_Success",
        "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/kFxError_ThirdPartyDeveloperStart",
        "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/kFxError_UnableToCreateDynamicRegistrationEndpoint",
        "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/kFxError_UnableToInstantiateDynamicRegistrar",
        "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/kFxError_UnableToMovePlayhead",
        "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/kFxError_UserCancelled",
        "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/kFxError_UnableToObtainProjectAspectRatio"
      ],
      "title": "Constants"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.professionalvideoapplications~1documentation~1professional_video_applications~1kFxError_UnableToInstantiateDynamicRegistrar/title",
          "value": "kFxError_UnableToInstantiateDynamicRegistrar"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.professionalvideoapplications~1documentation~1professional_video_applications~1kFxError_UnableToInstantiateDynamicRegistrar/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kFxError_UnableToInstantiateDynamicRegistrar"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.professionalvideoapplications~1documentation~1professional_video_applications~1kFxError_InvalidLightAccess/title",
          "value": "kFxError_InvalidLightAccess"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.professionalvideoapplications~1documentation~1professional_video_applications~1kFxError_InvalidLightAccess/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kFxError_InvalidLightAccess"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.professionalvideoapplications~1documentation~1professional_video_applications~1kFxError_Success/title",
          "value": "kFxError_Success"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.professionalvideoapplications~1documentation~1professional_video_applications~1kFxError_Success/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kFxError_Success"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.professionalvideoapplications~1documentation~1professional_video_applications~1FxAnalysisAPI~1analysisStateForEffect()/title",
          "value": "analysisStateForEffect"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.professionalvideoapplications~1documentation~1professional_video_applications~1FxAnalysisAPI~1analysisStateForEffect()/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "analysisStateForEffect"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.professionalvideoapplications~1documentation~1professional_video_applications~1kFxError_UnableToMovePlayhead/title",
          "value": "kFxError_UnableToMovePlayhead"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.professionalvideoapplications~1documentation~1professional_video_applications~1kFxError_UnableToMovePlayhead/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kFxError_UnableToMovePlayhead"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.professionalvideoapplications~1documentation~1professional_video_applications~1kFxError_CommandNotProcessed/title",
          "value": "kFxError_CommandNotProcessed"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.professionalvideoapplications~1documentation~1professional_video_applications~1kFxError_CommandNotProcessed/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kFxError_CommandNotProcessed"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.professionalvideoapplications~1documentation~1professional_video_applications~1kFxError_InvalidSegmentIndex/title",
          "value": "kFxError_InvalidSegmentIndex"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.professionalvideoapplications~1documentation~1professional_video_applications~1kFxError_InvalidSegmentIndex/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kFxError_InvalidSegmentIndex"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.professionalvideoapplications~1documentation~1professional_video_applications~1kFxError_UnableToObtainProjectAspectRatio/title",
          "value": "kFxError_UnableToObtainProjectAspectRatio"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.professionalvideoapplications~1documentation~1professional_video_applications~1kFxError_UnableToObtainProjectAspectRatio/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kFxError_UnableToObtainProjectAspectRatio"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.professionalvideoapplications~1documentation~1professional_video_applications~1kFxError_InvalidPathID/title",
          "value": "kFxError_InvalidPathID"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.professionalvideoapplications~1documentation~1professional_video_applications~1kFxError_InvalidPathID/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kFxError_InvalidPathID"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.professionalvideoapplications~1documentation~1professional_video_applications~1kFxError_InvalidDataLength/title",
          "value": "kFxError_InvalidDataLength"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.professionalvideoapplications~1documentation~1professional_video_applications~1kFxError_InvalidDataLength/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kFxError_InvalidDataLength"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.professionalvideoapplications~1documentation~1professional_video_applications~1kFxError_InvalidKeyframeIndex/title",
          "value": "kFxError_InvalidKeyframeIndex"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.professionalvideoapplications~1documentation~1professional_video_applications~1kFxError_InvalidKeyframeIndex/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kFxError_InvalidKeyframeIndex"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.professionalvideoapplications~1documentation~1professional_video_applications~1kFxError_PluginNotFound/title",
          "value": "kFxError_PluginNotFound"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.professionalvideoapplications~1documentation~1professional_video_applications~1kFxError_PluginNotFound/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kFxError_PluginNotFound"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.professionalvideoapplications~1documentation~1professional_video_applications~1kFxError_InvalidTime/title",
          "value": "kFxError_InvalidTime"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.professionalvideoapplications~1documentation~1professional_video_applications~1kFxError_InvalidTime/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kFxError_InvalidTime"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.professionalvideoapplications~1documentation~1professional_video_applications~1kFxError_NotYetImplemented/title",
          "value": "kFxError_NotYetImplemented"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.professionalvideoapplications~1documentation~1professional_video_applications~1kFxError_NotYetImplemented/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kFxError_NotYetImplemented"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.professionalvideoapplications~1documentation~1professional_video_applications~1kFxError_InvalidTiming/title",
          "value": "kFxError_InvalidTiming"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.professionalvideoapplications~1documentation~1professional_video_applications~1kFxError_InvalidTiming/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kFxError_InvalidTiming"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.professionalvideoapplications~1documentation~1professional_video_applications~1kFxError_InvalidParameterChannelIndex/title",
          "value": "kFxError_InvalidParameterChannelIndex"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.professionalvideoapplications~1documentation~1professional_video_applications~1kFxError_InvalidParameterChannelIndex/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kFxError_InvalidParameterChannelIndex"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.professionalvideoapplications~1documentation~1professional_video_applications~1kFxError_InvalidParameterID/title",
          "value": "kFxError_InvalidParameterID"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.professionalvideoapplications~1documentation~1professional_video_applications~1kFxError_InvalidParameterID/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kFxError_InvalidParameterID"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.professionalvideoapplications~1documentation~1professional_video_applications~1kFxError_InvalidPathIndex/title",
          "value": "kFxError_InvalidPathIndex"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.professionalvideoapplications~1documentation~1professional_video_applications~1kFxError_InvalidPathIndex/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kFxError_InvalidPathIndex"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.professionalvideoapplications~1documentation~1professional_video_applications~1kFxError_AnalysisError/title",
          "value": "kFxError_AnalysisError"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.professionalvideoapplications~1documentation~1professional_video_applications~1kFxError_AnalysisError/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kFxError_AnalysisError"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.professionalvideoapplications~1documentation~1professional_video_applications~1kFxError_HostUnreachable/title",
          "value": "kFxError_HostUnreachable"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.professionalvideoapplications~1documentation~1professional_video_applications~1kFxError_HostUnreachable/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kFxError_HostUnreachable"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.professionalvideoapplications~1documentation~1professional_video_applications~1kFxError_NoDocumentFound/title",
          "value": "kFxError_NoDocumentFound"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.professionalvideoapplications~1documentation~1professional_video_applications~1kFxError_NoDocumentFound/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kFxError_NoDocumentFound"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.professionalvideoapplications~1documentation~1professional_video_applications~1kFxError_InvalidParameter/title",
          "value": "kFxError_InvalidParameter"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.professionalvideoapplications~1documentation~1professional_video_applications~1kFxError_InvalidParameter/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kFxError_InvalidParameter"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.professionalvideoapplications~1documentation~1professional_video_applications~1kFxError_OutOfMemory/title",
          "value": "kFxError_OutOfMemory"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.professionalvideoapplications~1documentation~1professional_video_applications~1kFxError_OutOfMemory/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kFxError_OutOfMemory"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.professionalvideoapplications~1documentation~1professional_video_applications~1kFxError_NoViewFound/title",
          "value": "kFxError_NoViewFound"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.professionalvideoapplications~1documentation~1professional_video_applications~1kFxError_NoViewFound/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kFxError_NoViewFound"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.professionalvideoapplications~1documentation~1professional_video_applications~1kFxError_UnableToCreateDynamicRegistrationEndpoint/title",
          "value": "kFxError_UnableToCreateDynamicRegistrationEndpoint"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.professionalvideoapplications~1documentation~1professional_video_applications~1kFxError_UnableToCreateDynamicRegistrationEndpoint/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kFxError_UnableToCreateDynamicRegistrationEndpoint"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.professionalvideoapplications~1documentation~1professional_video_applications~1kFxError_InvalidPathStyle/title",
          "value": "kFxError_InvalidPathStyle"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.professionalvideoapplications~1documentation~1professional_video_applications~1kFxError_InvalidPathStyle/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kFxError_InvalidPathStyle"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.professionalvideoapplications~1documentation~1professional_video_applications~1kFxError_LostConnectionToPlugin/title",
          "value": "kFxError_LostConnectionToPlugin"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.professionalvideoapplications~1documentation~1professional_video_applications~1kFxError_LostConnectionToPlugin/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kFxError_LostConnectionToPlugin"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.professionalvideoapplications~1documentation~1professional_video_applications~1kFxError_UserCancelled/title",
          "value": "kFxError_UserCancelled"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.professionalvideoapplications~1documentation~1professional_video_applications~1kFxError_UserCancelled/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kFxError_UserCancelled"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.professionalvideoapplications~1documentation~1professional_video_applications~1kFxError_NoMediaFolder/title",
          "value": "kFxError_NoMediaFolder"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.professionalvideoapplications~1documentation~1professional_video_applications~1kFxError_NoMediaFolder/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kFxError_NoMediaFolder"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.professionalvideoapplications~1documentation~1professional_video_applications~1kFxError_InvalidPaths/title",
          "value": "kFxError_InvalidPaths"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.professionalvideoapplications~1documentation~1professional_video_applications~1kFxError_InvalidPaths/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kFxError_InvalidPaths"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.professionalvideoapplications~1documentation~1professional_video_applications~1kFxError_APIUnavailable/title",
          "value": "kFxError_APIUnavailable"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.professionalvideoapplications~1documentation~1professional_video_applications~1kFxError_APIUnavailable/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kFxError_APIUnavailable"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.professionalvideoapplications~1documentation~1professional_video_applications~1kFxError_MemoryNotAllocated/title",
          "value": "kFxError_MemoryNotAllocated"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.professionalvideoapplications~1documentation~1professional_video_applications~1kFxError_MemoryNotAllocated/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kFxError_MemoryNotAllocated"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.professionalvideoapplications~1documentation~1professional_video_applications~1kFxError_OpenGLError/title",
          "value": "kFxError_OpenGLError"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.professionalvideoapplications~1documentation~1professional_video_applications~1kFxError_OpenGLError/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kFxError_OpenGLError"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.professionalvideoapplications~1documentation~1professional_video_applications~1kFxError_AnalysisExtensionNotFound/title",
          "value": "kFxError_AnalysisExtensionNotFound"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.professionalvideoapplications~1documentation~1professional_video_applications~1kFxError_AnalysisExtensionNotFound/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kFxError_AnalysisExtensionNotFound"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.professionalvideoapplications~1documentation~1professional_video_applications~1kFxError_InvalidColorGamut/title",
          "value": "kFxError_InvalidColorGamut"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.professionalvideoapplications~1documentation~1professional_video_applications~1kFxError_InvalidColorGamut/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kFxError_InvalidColorGamut"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.professionalvideoapplications~1documentation~1professional_video_applications~1kFxError_ThirdPartyDeveloperStart/title",
          "value": "kFxError_ThirdPartyDeveloperStart"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.professionalvideoapplications~1documentation~1professional_video_applications~1kFxError_ThirdPartyDeveloperStart/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kFxError_ThirdPartyDeveloperStart"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/professional_video_applications/enum_(unnamed)-5fh3s"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
