{
  "abstract": [
    {
      "text": "The path color.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "occ",
    "url": "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/enum_(unnamed)-rvg5"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@Ea@kFxPathColor_Red",
    "modules": [
      {
        "name": "Professional Video Applications"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "enum (unnamed)"
      }
    ],
    "role": "symbol",
    "roleHeading": "Enumeration",
    "symbolKind": "enum",
    "title": "enum (unnamed)"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "occ"
          ],
          "platforms": [
            "Unsupported OS: FxPlug"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "enum"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:i",
              "text": "unsigned int"
            },
            {
              "kind": "text",
              "text": ";"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications": {
      "abstract": [
        {
          "text": "Exchange data with Final Cut Pro, and create effects plug-ins for Final Cut Pro and Motion.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications",
      "kind": "symbol",
      "role": "collection",
      "title": "Professional Video Applications",
      "type": "topic",
      "url": "/documentation/professional_video_applications"
    },
    "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/FxAnalysisAPI/analysisStateForEffect()": {
      "abstract": [
        {
          "text": "Fetches the state of frame analysis for your plug-in.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "analysisStateForEffect"
        },
        {
          "kind": "text",
          "text": "() -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@FxAnalysisState",
          "text": "FxAnalysisState"
        }
      ],
      "identifier": "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/FxAnalysisAPI/analysisStateForEffect()",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "analysisStateForEffect"
        }
      ],
      "required": true,
      "role": "symbol",
      "title": "analysisStateForEffect()",
      "type": "topic",
      "url": "/documentation/professional_video_applications/fxanalysisapi/analysisstateforeffect()"
    },
    "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/enum_(unnamed)-14vbr": {
      "abstract": [
        {
          "text": "The field order.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/enum_(unnamed)-14vbr",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "enum (unnamed)"
        }
      ],
      "role": "symbol",
      "title": "enum (unnamed)",
      "type": "topic",
      "url": "/documentation/professional_video_applications/enum_(unnamed)-14vbr"
    },
    "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/enum_(unnamed)-187sa": {
      "abstract": [],
      "identifier": "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/enum_(unnamed)-187sa",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "enum (unnamed)"
        }
      ],
      "role": "symbol",
      "title": "enum (unnamed)",
      "type": "topic",
      "url": "/documentation/professional_video_applications/enum_(unnamed)-187sa"
    },
    "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/enum_(unnamed)-1tjh8": {
      "abstract": [
        {
          "text": "The possible states of analysis, as reported by the host application when queried with ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/FxAnalysisAPI/analysisStateForEffect()",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": ".",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/enum_(unnamed)-1tjh8",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "enum (unnamed)"
        }
      ],
      "role": "symbol",
      "title": "enum (unnamed)",
      "type": "topic",
      "url": "/documentation/professional_video_applications/enum_(unnamed)-1tjh8"
    },
    "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/enum_(unnamed)-2epbe": {
      "abstract": [],
      "identifier": "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/enum_(unnamed)-2epbe",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "enum (unnamed)"
        }
      ],
      "role": "symbol",
      "title": "enum (unnamed)",
      "type": "topic",
      "url": "/documentation/professional_video_applications/enum_(unnamed)-2epbe"
    },
    "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/enum_(unnamed)-35krj": {
      "abstract": [
        {
          "text": "The path blend mode.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/enum_(unnamed)-35krj",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "enum (unnamed)"
        }
      ],
      "role": "symbol",
      "title": "enum (unnamed)",
      "type": "topic",
      "url": "/documentation/professional_video_applications/enum_(unnamed)-35krj"
    },
    "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/enum_(unnamed)-3fxly": {
      "abstract": [
        {
          "text": "The bit-depth",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/enum_(unnamed)-3fxly",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "enum (unnamed)"
        }
      ],
      "role": "symbol",
      "title": "enum (unnamed)",
      "type": "topic",
      "url": "/documentation/professional_video_applications/enum_(unnamed)-3fxly"
    },
    "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/enum_(unnamed)-3hmov": {
      "abstract": [
        {
          "text": "The render quality.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/enum_(unnamed)-3hmov",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "enum (unnamed)"
        }
      ],
      "role": "symbol",
      "title": "enum (unnamed)",
      "type": "topic",
      "url": "/documentation/professional_video_applications/enum_(unnamed)-3hmov"
    },
    "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/enum_(unnamed)-424rv": {
      "abstract": [],
      "identifier": "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/enum_(unnamed)-424rv",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "enum (unnamed)"
        }
      ],
      "role": "symbol",
      "title": "enum (unnamed)",
      "type": "topic",
      "url": "/documentation/professional_video_applications/enum_(unnamed)-424rv"
    },
    "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/enum_(unnamed)-5fh3s": {
      "abstract": [
        {
          "text": "Errors returned by plug-in hosts applications.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/enum_(unnamed)-5fh3s",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "enum (unnamed)"
        }
      ],
      "role": "symbol",
      "title": "enum (unnamed)",
      "type": "topic",
      "url": "/documentation/professional_video_applications/enum_(unnamed)-5fh3s"
    },
    "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/enum_(unnamed)-5key8": {
      "abstract": [],
      "identifier": "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/enum_(unnamed)-5key8",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "enum (unnamed)"
        }
      ],
      "role": "symbol",
      "title": "enum (unnamed)",
      "type": "topic",
      "url": "/documentation/professional_video_applications/enum_(unnamed)-5key8"
    },
    "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/enum_(unnamed)-5ml7h": {
      "abstract": [],
      "identifier": "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/enum_(unnamed)-5ml7h",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "enum (unnamed)"
        }
      ],
      "role": "symbol",
      "title": "enum (unnamed)",
      "type": "topic",
      "url": "/documentation/professional_video_applications/enum_(unnamed)-5ml7h"
    },
    "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/enum_(unnamed)-5r2wt": {
      "abstract": [
        {
          "text": "Constants used to describe a set of color primaries.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/enum_(unnamed)-5r2wt",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "enum (unnamed)"
        }
      ],
      "role": "symbol",
      "title": "enum (unnamed)",
      "type": "topic",
      "url": "/documentation/professional_video_applications/enum_(unnamed)-5r2wt"
    },
    "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/enum_(unnamed)-5zg4z": {
      "abstract": [],
      "identifier": "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/enum_(unnamed)-5zg4z",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "enum (unnamed)"
        }
      ],
      "role": "symbol",
      "title": "enum (unnamed)",
      "type": "topic",
      "url": "/documentation/professional_video_applications/enum_(unnamed)-5zg4z"
    },
    "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/enum_(unnamed)-74key": {
      "abstract": [],
      "identifier": "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/enum_(unnamed)-74key",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "enum (unnamed)"
        }
      ],
      "role": "symbol",
      "title": "enum (unnamed)",
      "type": "topic",
      "url": "/documentation/professional_video_applications/enum_(unnamed)-74key"
    },
    "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/enum_(unnamed)-7b48r": {
      "abstract": [],
      "identifier": "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/enum_(unnamed)-7b48r",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "enum (unnamed)"
        }
      ],
      "role": "symbol",
      "title": "enum (unnamed)",
      "type": "topic",
      "url": "/documentation/professional_video_applications/enum_(unnamed)-7b48r"
    },
    "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/enum_(unnamed)-rvg5": {
      "abstract": [
        {
          "text": "The path color.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/enum_(unnamed)-rvg5",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "enum (unnamed)"
        }
      ],
      "role": "symbol",
      "title": "enum (unnamed)",
      "type": "topic",
      "url": "/documentation/professional_video_applications/enum_(unnamed)-rvg5"
    },
    "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/kFxPathColor_Blue": {
      "abstract": [
        {
          "text": "The path is displayed in blue.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kFxPathColor_Blue"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/kFxPathColor_Blue",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kFxPathColor_Blue"
        }
      ],
      "role": "symbol",
      "title": "kFxPathColor_Blue",
      "type": "topic",
      "url": "/documentation/professional_video_applications/kfxpathcolor_blue"
    },
    "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/kFxPathColor_Cyan": {
      "abstract": [
        {
          "text": "The path is displayed in cyan.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kFxPathColor_Cyan"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/kFxPathColor_Cyan",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kFxPathColor_Cyan"
        }
      ],
      "role": "symbol",
      "title": "kFxPathColor_Cyan",
      "type": "topic",
      "url": "/documentation/professional_video_applications/kfxpathcolor_cyan"
    },
    "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/kFxPathColor_Green": {
      "abstract": [
        {
          "text": "The path is displayed in green.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kFxPathColor_Green"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/kFxPathColor_Green",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kFxPathColor_Green"
        }
      ],
      "role": "symbol",
      "title": "kFxPathColor_Green",
      "type": "topic",
      "url": "/documentation/professional_video_applications/kfxpathcolor_green"
    },
    "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/kFxPathColor_Magenta": {
      "abstract": [
        {
          "text": "The path is displayed in magenta.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kFxPathColor_Magenta"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/kFxPathColor_Magenta",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kFxPathColor_Magenta"
        }
      ],
      "role": "symbol",
      "title": "kFxPathColor_Magenta",
      "type": "topic",
      "url": "/documentation/professional_video_applications/kfxpathcolor_magenta"
    },
    "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/kFxPathColor_Orange": {
      "abstract": [
        {
          "text": "The path is displayed in orange.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kFxPathColor_Orange"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/kFxPathColor_Orange",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kFxPathColor_Orange"
        }
      ],
      "role": "symbol",
      "title": "kFxPathColor_Orange",
      "type": "topic",
      "url": "/documentation/professional_video_applications/kfxpathcolor_orange"
    },
    "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/kFxPathColor_Purple": {
      "abstract": [
        {
          "text": "The path is displayed in purple.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kFxPathColor_Purple"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/kFxPathColor_Purple",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kFxPathColor_Purple"
        }
      ],
      "role": "symbol",
      "title": "kFxPathColor_Purple",
      "type": "topic",
      "url": "/documentation/professional_video_applications/kfxpathcolor_purple"
    },
    "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/kFxPathColor_Red": {
      "abstract": [
        {
          "text": "The path is displayed in red.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kFxPathColor_Red"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/kFxPathColor_Red",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kFxPathColor_Red"
        }
      ],
      "role": "symbol",
      "title": "kFxPathColor_Red",
      "type": "topic",
      "url": "/documentation/professional_video_applications/kfxpathcolor_red"
    },
    "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/kFxPathColor_Yellow": {
      "abstract": [
        {
          "text": "The path is displayed in yellow.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kFxPathColor_Yellow"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/kFxPathColor_Yellow",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kFxPathColor_Yellow"
        }
      ],
      "role": "symbol",
      "title": "kFxPathColor_Yellow",
      "type": "topic",
      "url": "/documentation/professional_video_applications/kfxpathcolor_yellow"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Anonymous-enumerations",
      "generated": true,
      "identifiers": [
        "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/enum_(unnamed)-14vbr",
        "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/enum_(unnamed)-187sa",
        "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/enum_(unnamed)-1tjh8",
        "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/enum_(unnamed)-2epbe",
        "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/enum_(unnamed)-35krj",
        "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/enum_(unnamed)-3fxly",
        "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/enum_(unnamed)-3hmov",
        "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/enum_(unnamed)-424rv",
        "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/enum_(unnamed)-5fh3s",
        "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/enum_(unnamed)-5key8",
        "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/enum_(unnamed)-5ml7h",
        "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/enum_(unnamed)-5r2wt",
        "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/enum_(unnamed)-5zg4z",
        "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/enum_(unnamed)-74key",
        "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/enum_(unnamed)-7b48r"
      ],
      "title": "Anonymous enumerations"
    }
  ],
  "topicSections": [
    {
      "anchor": "Constants",
      "identifiers": [
        "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/kFxPathColor_Blue",
        "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/kFxPathColor_Cyan",
        "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/kFxPathColor_Green",
        "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/kFxPathColor_Magenta",
        "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/kFxPathColor_Orange",
        "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/kFxPathColor_Purple",
        "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/kFxPathColor_Red",
        "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/kFxPathColor_Yellow"
      ],
      "title": "Constants"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.professionalvideoapplications~1documentation~1professional_video_applications~1kFxPathColor_Magenta/title",
          "value": "kFxPathColor_Magenta"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.professionalvideoapplications~1documentation~1professional_video_applications~1kFxPathColor_Magenta/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kFxPathColor_Magenta"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.professionalvideoapplications~1documentation~1professional_video_applications~1kFxPathColor_Orange/title",
          "value": "kFxPathColor_Orange"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.professionalvideoapplications~1documentation~1professional_video_applications~1kFxPathColor_Orange/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kFxPathColor_Orange"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.professionalvideoapplications~1documentation~1professional_video_applications~1kFxPathColor_Purple/title",
          "value": "kFxPathColor_Purple"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.professionalvideoapplications~1documentation~1professional_video_applications~1kFxPathColor_Purple/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kFxPathColor_Purple"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.professionalvideoapplications~1documentation~1professional_video_applications~1kFxPathColor_Blue/title",
          "value": "kFxPathColor_Blue"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.professionalvideoapplications~1documentation~1professional_video_applications~1kFxPathColor_Blue/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kFxPathColor_Blue"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.professionalvideoapplications~1documentation~1professional_video_applications~1kFxPathColor_Red/title",
          "value": "kFxPathColor_Red"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.professionalvideoapplications~1documentation~1professional_video_applications~1kFxPathColor_Red/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kFxPathColor_Red"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.professionalvideoapplications~1documentation~1professional_video_applications~1FxAnalysisAPI~1analysisStateForEffect()/title",
          "value": "analysisStateForEffect"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.professionalvideoapplications~1documentation~1professional_video_applications~1FxAnalysisAPI~1analysisStateForEffect()/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "analysisStateForEffect"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.professionalvideoapplications~1documentation~1professional_video_applications~1kFxPathColor_Green/title",
          "value": "kFxPathColor_Green"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.professionalvideoapplications~1documentation~1professional_video_applications~1kFxPathColor_Green/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kFxPathColor_Green"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.professionalvideoapplications~1documentation~1professional_video_applications~1kFxPathColor_Cyan/title",
          "value": "kFxPathColor_Cyan"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.professionalvideoapplications~1documentation~1professional_video_applications~1kFxPathColor_Cyan/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kFxPathColor_Cyan"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.professionalvideoapplications~1documentation~1professional_video_applications~1kFxPathColor_Yellow/title",
          "value": "kFxPathColor_Yellow"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.professionalvideoapplications~1documentation~1professional_video_applications~1kFxPathColor_Yellow/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kFxPathColor_Yellow"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/professional_video_applications/enum_(unnamed)-rvg5"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
