{
  "abstract": [
    {
      "text": "The possible states of analysis, as reported by the host application when queried with ",
      "type": "text"
    },
    {
      "identifier": "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/FxAnalysisAPI/analysisStateForEffect()",
      "isActive": true,
      "type": "reference"
    },
    {
      "text": ".",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "occ",
    "url": "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/enum_(unnamed)-1tjh8"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@Ea@kFxAnalysisState_NotAnalyzing",
    "modules": [
      {
        "name": "Professional Video Applications"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "enum (unnamed)"
      }
    ],
    "role": "symbol",
    "roleHeading": "Enumeration",
    "symbolKind": "enum",
    "title": "enum (unnamed)"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "occ"
          ],
          "platforms": [
            "Unsupported OS: FxPlug"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "enum"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/FxAnalysisState",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@FxAnalysisState",
              "text": "FxAnalysisState"
            },
            {
              "kind": "text",
              "text": ";"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications": {
      "abstract": [
        {
          "text": "Exchange data with Final Cut Pro, and create effects plug-ins for Final Cut Pro and Motion.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications",
      "kind": "symbol",
      "role": "collection",
      "title": "Professional Video Applications",
      "type": "topic",
      "url": "/documentation/professional_video_applications"
    },
    "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/FxAnalysisAPI/analysisStateForEffect()": {
      "abstract": [
        {
          "text": "Fetches the state of frame analysis for your plug-in.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "analysisStateForEffect"
        },
        {
          "kind": "text",
          "text": "() -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@FxAnalysisState",
          "text": "FxAnalysisState"
        }
      ],
      "identifier": "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/FxAnalysisAPI/analysisStateForEffect()",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "analysisStateForEffect"
        }
      ],
      "required": true,
      "role": "symbol",
      "title": "analysisStateForEffect()",
      "type": "topic",
      "url": "/documentation/professional_video_applications/fxanalysisapi/analysisstateforeffect()"
    },
    "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/FxAnalysisState": {
      "abstract": [
        {
          "text": "The possible states of frame analysis, as reported by the host application.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "FxAnalysisState"
        }
      ],
      "identifier": "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/FxAnalysisState",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "FxAnalysisState"
        }
      ],
      "role": "symbol",
      "title": "FxAnalysisState",
      "type": "topic",
      "url": "/documentation/professional_video_applications/fxanalysisstate"
    },
    "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/enum_(unnamed)-14vbr": {
      "abstract": [
        {
          "text": "The field order.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/enum_(unnamed)-14vbr",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "enum (unnamed)"
        }
      ],
      "role": "symbol",
      "title": "enum (unnamed)",
      "type": "topic",
      "url": "/documentation/professional_video_applications/enum_(unnamed)-14vbr"
    },
    "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/enum_(unnamed)-187sa": {
      "abstract": [],
      "identifier": "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/enum_(unnamed)-187sa",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "enum (unnamed)"
        }
      ],
      "role": "symbol",
      "title": "enum (unnamed)",
      "type": "topic",
      "url": "/documentation/professional_video_applications/enum_(unnamed)-187sa"
    },
    "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/enum_(unnamed)-1tjh8": {
      "abstract": [
        {
          "text": "The possible states of analysis, as reported by the host application when queried with ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/FxAnalysisAPI/analysisStateForEffect()",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": ".",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/enum_(unnamed)-1tjh8",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "enum (unnamed)"
        }
      ],
      "role": "symbol",
      "title": "enum (unnamed)",
      "type": "topic",
      "url": "/documentation/professional_video_applications/enum_(unnamed)-1tjh8"
    },
    "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/enum_(unnamed)-2epbe": {
      "abstract": [],
      "identifier": "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/enum_(unnamed)-2epbe",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "enum (unnamed)"
        }
      ],
      "role": "symbol",
      "title": "enum (unnamed)",
      "type": "topic",
      "url": "/documentation/professional_video_applications/enum_(unnamed)-2epbe"
    },
    "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/enum_(unnamed)-35krj": {
      "abstract": [
        {
          "text": "The path blend mode.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/enum_(unnamed)-35krj",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "enum (unnamed)"
        }
      ],
      "role": "symbol",
      "title": "enum (unnamed)",
      "type": "topic",
      "url": "/documentation/professional_video_applications/enum_(unnamed)-35krj"
    },
    "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/enum_(unnamed)-3fxly": {
      "abstract": [
        {
          "text": "The bit-depth",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/enum_(unnamed)-3fxly",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "enum (unnamed)"
        }
      ],
      "role": "symbol",
      "title": "enum (unnamed)",
      "type": "topic",
      "url": "/documentation/professional_video_applications/enum_(unnamed)-3fxly"
    },
    "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/enum_(unnamed)-3hmov": {
      "abstract": [
        {
          "text": "The render quality.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/enum_(unnamed)-3hmov",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "enum (unnamed)"
        }
      ],
      "role": "symbol",
      "title": "enum (unnamed)",
      "type": "topic",
      "url": "/documentation/professional_video_applications/enum_(unnamed)-3hmov"
    },
    "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/enum_(unnamed)-424rv": {
      "abstract": [],
      "identifier": "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/enum_(unnamed)-424rv",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "enum (unnamed)"
        }
      ],
      "role": "symbol",
      "title": "enum (unnamed)",
      "type": "topic",
      "url": "/documentation/professional_video_applications/enum_(unnamed)-424rv"
    },
    "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/enum_(unnamed)-5fh3s": {
      "abstract": [
        {
          "text": "Errors returned by plug-in hosts applications.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/enum_(unnamed)-5fh3s",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "enum (unnamed)"
        }
      ],
      "role": "symbol",
      "title": "enum (unnamed)",
      "type": "topic",
      "url": "/documentation/professional_video_applications/enum_(unnamed)-5fh3s"
    },
    "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/enum_(unnamed)-5key8": {
      "abstract": [],
      "identifier": "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/enum_(unnamed)-5key8",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "enum (unnamed)"
        }
      ],
      "role": "symbol",
      "title": "enum (unnamed)",
      "type": "topic",
      "url": "/documentation/professional_video_applications/enum_(unnamed)-5key8"
    },
    "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/enum_(unnamed)-5ml7h": {
      "abstract": [],
      "identifier": "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/enum_(unnamed)-5ml7h",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "enum (unnamed)"
        }
      ],
      "role": "symbol",
      "title": "enum (unnamed)",
      "type": "topic",
      "url": "/documentation/professional_video_applications/enum_(unnamed)-5ml7h"
    },
    "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/enum_(unnamed)-5r2wt": {
      "abstract": [
        {
          "text": "Constants used to describe a set of color primaries.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/enum_(unnamed)-5r2wt",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "enum (unnamed)"
        }
      ],
      "role": "symbol",
      "title": "enum (unnamed)",
      "type": "topic",
      "url": "/documentation/professional_video_applications/enum_(unnamed)-5r2wt"
    },
    "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/enum_(unnamed)-5zg4z": {
      "abstract": [],
      "identifier": "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/enum_(unnamed)-5zg4z",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "enum (unnamed)"
        }
      ],
      "role": "symbol",
      "title": "enum (unnamed)",
      "type": "topic",
      "url": "/documentation/professional_video_applications/enum_(unnamed)-5zg4z"
    },
    "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/enum_(unnamed)-74key": {
      "abstract": [],
      "identifier": "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/enum_(unnamed)-74key",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "enum (unnamed)"
        }
      ],
      "role": "symbol",
      "title": "enum (unnamed)",
      "type": "topic",
      "url": "/documentation/professional_video_applications/enum_(unnamed)-74key"
    },
    "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/enum_(unnamed)-7b48r": {
      "abstract": [],
      "identifier": "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/enum_(unnamed)-7b48r",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "enum (unnamed)"
        }
      ],
      "role": "symbol",
      "title": "enum (unnamed)",
      "type": "topic",
      "url": "/documentation/professional_video_applications/enum_(unnamed)-7b48r"
    },
    "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/enum_(unnamed)-7jahq": {
      "abstract": [],
      "identifier": "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/enum_(unnamed)-7jahq",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "enum (unnamed)"
        }
      ],
      "role": "symbol",
      "title": "enum (unnamed)",
      "type": "topic",
      "url": "/documentation/professional_video_applications/enum_(unnamed)-7jahq"
    },
    "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/kFxAnalysisState_AnalysisCompleted": {
      "abstract": [
        {
          "text": "Analysis completed.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kFxAnalysisState_AnalysisCompleted"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@FxAnalysisState",
          "text": "FxAnalysisState"
        }
      ],
      "identifier": "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/kFxAnalysisState_AnalysisCompleted",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kFxAnalysisState_AnalysisCompleted"
        }
      ],
      "role": "symbol",
      "title": "kFxAnalysisState_AnalysisCompleted",
      "type": "topic",
      "url": "/documentation/professional_video_applications/kfxanalysisstate_analysiscompleted"
    },
    "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/kFxAnalysisState_AnalysisInterrupted": {
      "abstract": [
        {
          "text": "Analysis interrupted.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kFxAnalysisState_AnalysisInterrupted"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@FxAnalysisState",
          "text": "FxAnalysisState"
        }
      ],
      "identifier": "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/kFxAnalysisState_AnalysisInterrupted",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kFxAnalysisState_AnalysisInterrupted"
        }
      ],
      "role": "symbol",
      "title": "kFxAnalysisState_AnalysisInterrupted",
      "type": "topic",
      "url": "/documentation/professional_video_applications/kfxanalysisstate_analysisinterrupted"
    },
    "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/kFxAnalysisState_AnalysisRequested": {
      "abstract": [
        {
          "text": "Analysis requested.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kFxAnalysisState_AnalysisRequested"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@FxAnalysisState",
          "text": "FxAnalysisState"
        }
      ],
      "identifier": "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/kFxAnalysisState_AnalysisRequested",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kFxAnalysisState_AnalysisRequested"
        }
      ],
      "role": "symbol",
      "title": "kFxAnalysisState_AnalysisRequested",
      "type": "topic",
      "url": "/documentation/professional_video_applications/kfxanalysisstate_analysisrequested"
    },
    "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/kFxAnalysisState_AnalysisStarted": {
      "abstract": [
        {
          "text": "Analysis started.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kFxAnalysisState_AnalysisStarted"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@FxAnalysisState",
          "text": "FxAnalysisState"
        }
      ],
      "identifier": "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/kFxAnalysisState_AnalysisStarted",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kFxAnalysisState_AnalysisStarted"
        }
      ],
      "role": "symbol",
      "title": "kFxAnalysisState_AnalysisStarted",
      "type": "topic",
      "url": "/documentation/professional_video_applications/kfxanalysisstate_analysisstarted"
    },
    "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/kFxAnalysisState_NotAnalyzing": {
      "abstract": [
        {
          "text": "Not currently analyzing.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kFxAnalysisState_NotAnalyzing"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@FxAnalysisState",
          "text": "FxAnalysisState"
        }
      ],
      "identifier": "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/kFxAnalysisState_NotAnalyzing",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kFxAnalysisState_NotAnalyzing"
        }
      ],
      "role": "symbol",
      "title": "kFxAnalysisState_NotAnalyzing",
      "type": "topic",
      "url": "/documentation/professional_video_applications/kfxanalysisstate_notanalyzing"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Anonymous-enumerations",
      "generated": true,
      "identifiers": [
        "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/enum_(unnamed)-14vbr",
        "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/enum_(unnamed)-187sa",
        "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/enum_(unnamed)-2epbe",
        "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/enum_(unnamed)-35krj",
        "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/enum_(unnamed)-3fxly",
        "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/enum_(unnamed)-3hmov",
        "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/enum_(unnamed)-424rv",
        "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/enum_(unnamed)-5fh3s",
        "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/enum_(unnamed)-5key8",
        "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/enum_(unnamed)-5ml7h",
        "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/enum_(unnamed)-5r2wt",
        "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/enum_(unnamed)-5zg4z",
        "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/enum_(unnamed)-74key",
        "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/enum_(unnamed)-7b48r",
        "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/enum_(unnamed)-7jahq"
      ],
      "title": "Anonymous enumerations"
    }
  ],
  "topicSections": [
    {
      "anchor": "Constants",
      "identifiers": [
        "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/kFxAnalysisState_NotAnalyzing",
        "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/kFxAnalysisState_AnalysisRequested",
        "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/kFxAnalysisState_AnalysisStarted",
        "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/kFxAnalysisState_AnalysisCompleted",
        "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/kFxAnalysisState_AnalysisInterrupted"
      ],
      "title": "Constants"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.professionalvideoapplications~1documentation~1professional_video_applications~1kFxAnalysisState_AnalysisRequested/title",
          "value": "kFxAnalysisState_AnalysisRequested"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.professionalvideoapplications~1documentation~1professional_video_applications~1kFxAnalysisState_AnalysisRequested/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kFxAnalysisState_AnalysisRequested"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.professionalvideoapplications~1documentation~1professional_video_applications~1kFxAnalysisState_AnalysisCompleted/title",
          "value": "kFxAnalysisState_AnalysisCompleted"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.professionalvideoapplications~1documentation~1professional_video_applications~1kFxAnalysisState_AnalysisCompleted/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kFxAnalysisState_AnalysisCompleted"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.professionalvideoapplications~1documentation~1professional_video_applications~1FxAnalysisAPI~1analysisStateForEffect()/title",
          "value": "analysisStateForEffect"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.professionalvideoapplications~1documentation~1professional_video_applications~1FxAnalysisAPI~1analysisStateForEffect()/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "analysisStateForEffect"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.professionalvideoapplications~1documentation~1professional_video_applications~1kFxAnalysisState_NotAnalyzing/title",
          "value": "kFxAnalysisState_NotAnalyzing"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.professionalvideoapplications~1documentation~1professional_video_applications~1kFxAnalysisState_NotAnalyzing/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kFxAnalysisState_NotAnalyzing"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.professionalvideoapplications~1documentation~1professional_video_applications~1FxAnalysisState/title",
          "value": "FxAnalysisState"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.professionalvideoapplications~1documentation~1professional_video_applications~1FxAnalysisState/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "FxAnalysisState"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.professionalvideoapplications~1documentation~1professional_video_applications~1FxAnalysisState/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "FxAnalysisState"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.professionalvideoapplications~1documentation~1professional_video_applications~1kFxAnalysisState_AnalysisStarted/title",
          "value": "kFxAnalysisState_AnalysisStarted"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.professionalvideoapplications~1documentation~1professional_video_applications~1kFxAnalysisState_AnalysisStarted/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kFxAnalysisState_AnalysisStarted"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.professionalvideoapplications~1documentation~1professional_video_applications~1kFxAnalysisState_AnalysisInterrupted/title",
          "value": "kFxAnalysisState_AnalysisInterrupted"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.professionalvideoapplications~1documentation~1professional_video_applications~1kFxAnalysisState_AnalysisInterrupted/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kFxAnalysisState_AnalysisInterrupted"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/professional_video_applications/enum_(unnamed)-1tjh8"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
