{
  "abstract": [
    {
      "text": "The Final Cut Pro timeline object types.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/FCPXObjectType"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@FCPXObjectType",
    "fragments": [
      {
        "kind": "keyword",
        "text": "enum"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "FCPXObjectType"
      }
    ],
    "modules": [
      {
        "name": "Professional Video Applications"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "FCPXObjectType"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "introducedAt": "1.0",
        "name": "ProVideo Workflow Extensions"
      }
    ],
    "role": "symbol",
    "roleHeading": "Enumeration",
    "symbolKind": "enum",
    "title": "FCPXObjectType"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "Unsupported OS: ProExtensionHost"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "enum"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "FCPXObjectType"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications": {
      "abstract": [
        {
          "text": "Exchange data with Final Cut Pro, and create effects plug-ins for Final Cut Pro and Motion.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications",
      "kind": "symbol",
      "role": "collection",
      "title": "Professional Video Applications",
      "type": "topic",
      "url": "/documentation/professional_video_applications"
    },
    "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/FCPXEvent": {
      "abstract": [
        {
          "text": "An object that contains details of an event in the Final Cut Pro library.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "FCPXEvent"
        }
      ],
      "identifier": "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/FCPXEvent",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "FCPXEvent"
        }
      ],
      "role": "symbol",
      "title": "FCPXEvent",
      "type": "topic",
      "url": "/documentation/professional_video_applications/fcpxevent"
    },
    "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/FCPXLibrary": {
      "abstract": [
        {
          "text": "An object that contains details of a Final Cut Pro library.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "FCPXLibrary"
        }
      ],
      "identifier": "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/FCPXLibrary",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "FCPXLibrary"
        }
      ],
      "role": "symbol",
      "title": "FCPXLibrary",
      "type": "topic",
      "url": "/documentation/professional_video_applications/fcpxlibrary"
    },
    "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/FCPXObject": {
      "abstract": [
        {
          "text": "An abstract superclass for Final Cut Pro timeline proxy objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "FCPXObject"
        }
      ],
      "identifier": "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/FCPXObject",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "FCPXObject"
        }
      ],
      "role": "symbol",
      "title": "FCPXObject",
      "type": "topic",
      "url": "/documentation/professional_video_applications/fcpxobject"
    },
    "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/FCPXObjectType": {
      "abstract": [
        {
          "text": "The Final Cut Pro timeline object types.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "FCPXObjectType"
        }
      ],
      "identifier": "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/FCPXObjectType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "FCPXObjectType"
        }
      ],
      "role": "symbol",
      "title": "FCPXObjectType",
      "type": "topic",
      "url": "/documentation/professional_video_applications/fcpxobjecttype"
    },
    "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/FCPXObjectType/Equatable-Implementations": {
      "abstract": [],
      "identifier": "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/FCPXObjectType/Equatable-Implementations",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Equatable Implementations",
      "type": "topic",
      "url": "/documentation/professional_video_applications/fcpxobjecttype/equatable-implementations"
    },
    "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/FCPXObjectType/RawRepresentable-Implementations": {
      "abstract": [],
      "identifier": "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/FCPXObjectType/RawRepresentable-Implementations",
      "kind": "article",
      "role": "collectionGroup",
      "title": "RawRepresentable Implementations",
      "type": "topic",
      "url": "/documentation/professional_video_applications/fcpxobjecttype/rawrepresentable-implementations"
    },
    "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/FCPXObjectType/event": {
      "abstract": [
        {
          "text": "A Final Cut Pro timeline event.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "event"
        }
      ],
      "identifier": "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/FCPXObjectType/event",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kFCPXObjectType_Event"
        }
      ],
      "role": "symbol",
      "title": "FCPXObjectType.event",
      "type": "topic",
      "url": "/documentation/professional_video_applications/fcpxobjecttype/event"
    },
    "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/FCPXObjectType/init(rawValue:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "?("
        },
        {
          "kind": "externalParam",
          "text": "rawValue"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/FCPXObjectType/init(rawValue:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "init(rawValue:)",
      "type": "topic",
      "url": "/documentation/professional_video_applications/fcpxobjecttype/init(rawvalue:)"
    },
    "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/FCPXObjectType/library": {
      "abstract": [
        {
          "text": "A Final Cut Pro timeline library.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "library"
        }
      ],
      "identifier": "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/FCPXObjectType/library",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kFCPXObjectType_Library"
        }
      ],
      "role": "symbol",
      "title": "FCPXObjectType.library",
      "type": "topic",
      "url": "/documentation/professional_video_applications/fcpxobjecttype/library"
    },
    "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/FCPXObjectType/project": {
      "abstract": [
        {
          "text": "A Final Cut Pro timeline project.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "project"
        }
      ],
      "identifier": "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/FCPXObjectType/project",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kFCPXObjectType_Project"
        }
      ],
      "role": "symbol",
      "title": "FCPXObjectType.project",
      "type": "topic",
      "url": "/documentation/professional_video_applications/fcpxobjecttype/project"
    },
    "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/FCPXObjectType/sequence": {
      "abstract": [
        {
          "text": "A Final Cut Pro timeline sequence.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "sequence"
        }
      ],
      "identifier": "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/FCPXObjectType/sequence",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kFCPXObjectType_Sequence"
        }
      ],
      "role": "symbol",
      "title": "FCPXObjectType.sequence",
      "type": "topic",
      "url": "/documentation/professional_video_applications/fcpxobjecttype/sequence"
    },
    "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/FCPXProject": {
      "abstract": [
        {
          "text": "An object that contains details of a project with the sequence open in the Final Cut Pro timeline.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "FCPXProject"
        }
      ],
      "identifier": "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/FCPXProject",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "FCPXProject"
        }
      ],
      "role": "symbol",
      "title": "FCPXProject",
      "type": "topic",
      "url": "/documentation/professional_video_applications/fcpxproject"
    },
    "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/FCPXSequence": {
      "abstract": [
        {
          "text": "An object that contains details of a sequence that’s open in the Final Cut Pro timeline.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "FCPXSequence"
        }
      ],
      "identifier": "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/FCPXSequence",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "FCPXSequence"
        }
      ],
      "role": "symbol",
      "title": "FCPXSequence",
      "type": "topic",
      "url": "/documentation/professional_video_applications/fcpxsequence"
    },
    "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/FCPXSequenceTimecodeFormat": {
      "abstract": [
        {
          "text": "The display format of the sequence timecode.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "FCPXSequenceTimecodeFormat"
        }
      ],
      "identifier": "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/FCPXSequenceTimecodeFormat",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "FCPXSequenceTimecodeFormat"
        }
      ],
      "role": "symbol",
      "title": "FCPXSequenceTimecodeFormat",
      "type": "topic",
      "url": "/documentation/professional_video_applications/fcpxsequencetimecodeformat"
    },
    "doc://com.externally.resolved.symbol/s:SH": {
      "abstract": [
        {
          "text": "A type that can be hashed into a `Hasher` to produce an integer hash value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Hashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SQ",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SH",
      "kind": "symbol",
      "role": "symbol",
      "title": "Hashable",
      "type": "topic",
      "url": "/documentation/Swift/Hashable"
    },
    "doc://com.externally.resolved.symbol/s:SQ": {
      "abstract": [
        {
          "text": "A type that can be compared for value equality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SQ",
      "kind": "symbol",
      "role": "symbol",
      "title": "Equatable",
      "type": "topic",
      "url": "/documentation/Swift/Equatable"
    },
    "doc://com.externally.resolved.symbol/s:SY": {
      "abstract": [
        {
          "text": "A type that can be converted to and from an associated raw value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "RawRepresentable"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SY8RawValueQa",
          "text": "RawValue"
        },
        {
          "kind": "text",
          "text": ">"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SY",
      "kind": "symbol",
      "role": "symbol",
      "title": "RawRepresentable",
      "type": "topic",
      "url": "/documentation/Swift/RawRepresentable"
    },
    "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BitwiseCopyable"
        },
        {
          "kind": "text",
          "text": " : ~Escapable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "BitwiseCopyable",
      "type": "topic",
      "url": "/documentation/Swift/BitwiseCopyable"
    },
    "doc://com.externally.resolved.symbol/s:s8SendableP": {
      "abstract": [
        {
          "text": "A thread-safe type whose values can be shared across arbitrary concurrent contexts without introducing a risk of data races.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Sendable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s8SendableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "Sendable",
      "type": "topic",
      "url": "/documentation/Swift/Sendable"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
        "doc://com.externally.resolved.symbol/s:SQ",
        "doc://com.externally.resolved.symbol/s:SH",
        "doc://com.externally.resolved.symbol/s:SY",
        "doc://com.externally.resolved.symbol/s:s8SendableP"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "FCPX-Timeline-Proxy-Objects",
      "generated": true,
      "identifiers": [
        "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/FCPXObject",
        "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/FCPXLibrary",
        "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/FCPXEvent",
        "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/FCPXProject",
        "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/FCPXSequence",
        "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/FCPXSequenceTimecodeFormat"
      ],
      "title": "FCPX Timeline Proxy Objects"
    }
  ],
  "topicSections": [
    {
      "anchor": "Final-Cut-Pro-Timeline-Object-Types",
      "identifiers": [
        "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/FCPXObjectType/event",
        "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/FCPXObjectType/library",
        "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/FCPXObjectType/project",
        "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/FCPXObjectType/sequence"
      ],
      "title": "Final Cut Pro Timeline Object Types"
    },
    {
      "anchor": "Initializers",
      "generated": true,
      "identifiers": [
        "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/FCPXObjectType/init(rawValue:)"
      ],
      "title": "Initializers"
    },
    {
      "anchor": "Default-Implementations",
      "generated": true,
      "identifiers": [
        "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/FCPXObjectType/Equatable-Implementations",
        "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/FCPXObjectType/RawRepresentable-Implementations"
      ],
      "title": "Default Implementations"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": null
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "FCPXObjectType"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "enum"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "FCPXObjectType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "FCPXObjectType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Final-Cut-Pro-Timeline-Object-Types",
              "identifiers": [
                "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/FCPXObjectType/event",
                "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/FCPXObjectType/library",
                "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/FCPXObjectType/project",
                "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/FCPXObjectType/sequence"
              ],
              "title": "Final Cut Pro Timeline Object Types"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "FCPX-Timeline-Proxy-Objects",
              "generated": true,
              "identifiers": [
                "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/FCPXObject",
                "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/FCPXLibrary",
                "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/FCPXEvent",
                "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/FCPXProject",
                "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/FCPXSequence",
                "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/FCPXSequenceTimecodeFormat"
              ],
              "title": "FCPX Timeline Proxy Objects"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "Unsupported OS: ProExtensionHost"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "enum"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "FCPXObjectType"
                  },
                  {
                    "kind": "text",
                    "text": ": "
                  },
                  {
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@NSInteger",
                    "text": "NSInteger"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.professionalvideoapplications~1documentation~1professional_video_applications~1FCPXLibrary/title",
          "value": "FCPXLibrary"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.professionalvideoapplications~1documentation~1professional_video_applications~1FCPXLibrary/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "FCPXLibrary"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.professionalvideoapplications~1documentation~1professional_video_applications~1FCPXLibrary/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "FCPXLibrary"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.professionalvideoapplications~1documentation~1professional_video_applications~1FCPXObjectType~1project/title",
          "value": "kFCPXObjectType_Project"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.professionalvideoapplications~1documentation~1professional_video_applications~1FCPXObjectType~1project/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kFCPXObjectType_Project"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.professionalvideoapplications~1documentation~1professional_video_applications~1FCPXObjectType~1event/title",
          "value": "kFCPXObjectType_Event"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.professionalvideoapplications~1documentation~1professional_video_applications~1FCPXObjectType~1event/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kFCPXObjectType_Event"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.professionalvideoapplications~1documentation~1professional_video_applications~1FCPXSequence/title",
          "value": "FCPXSequence"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.professionalvideoapplications~1documentation~1professional_video_applications~1FCPXSequence/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "FCPXSequence"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.professionalvideoapplications~1documentation~1professional_video_applications~1FCPXSequence/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "FCPXSequence"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.professionalvideoapplications~1documentation~1professional_video_applications~1FCPXObjectType/title",
          "value": "FCPXObjectType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.professionalvideoapplications~1documentation~1professional_video_applications~1FCPXObjectType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "FCPXObjectType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.professionalvideoapplications~1documentation~1professional_video_applications~1FCPXObjectType/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "FCPXObjectType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.professionalvideoapplications~1documentation~1professional_video_applications~1FCPXObjectType~1sequence/title",
          "value": "kFCPXObjectType_Sequence"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.professionalvideoapplications~1documentation~1professional_video_applications~1FCPXObjectType~1sequence/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kFCPXObjectType_Sequence"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.professionalvideoapplications~1documentation~1professional_video_applications~1FCPXProject/title",
          "value": "FCPXProject"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.professionalvideoapplications~1documentation~1professional_video_applications~1FCPXProject/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "FCPXProject"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.professionalvideoapplications~1documentation~1professional_video_applications~1FCPXProject/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "FCPXProject"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.professionalvideoapplications~1documentation~1professional_video_applications~1FCPXEvent/title",
          "value": "FCPXEvent"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.professionalvideoapplications~1documentation~1professional_video_applications~1FCPXEvent/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "FCPXEvent"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.professionalvideoapplications~1documentation~1professional_video_applications~1FCPXEvent/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "FCPXEvent"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.professionalvideoapplications~1documentation~1professional_video_applications~1FCPXSequenceTimecodeFormat/title",
          "value": "FCPXSequenceTimecodeFormat"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.professionalvideoapplications~1documentation~1professional_video_applications~1FCPXSequenceTimecodeFormat/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "FCPXSequenceTimecodeFormat"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.professionalvideoapplications~1documentation~1professional_video_applications~1FCPXSequenceTimecodeFormat/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "FCPXSequenceTimecodeFormat"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.professionalvideoapplications~1documentation~1professional_video_applications~1FCPXObject/title",
          "value": "FCPXObject"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.professionalvideoapplications~1documentation~1professional_video_applications~1FCPXObject/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "FCPXObject"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.professionalvideoapplications~1documentation~1professional_video_applications~1FCPXObject/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "FCPXObject"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.professionalvideoapplications~1documentation~1professional_video_applications~1FCPXObjectType~1library/title",
          "value": "kFCPXObjectType_Library"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.professionalvideoapplications~1documentation~1professional_video_applications~1FCPXObjectType~1library/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kFCPXObjectType_Library"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/professional_video_applications/fcpxobjecttype"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/professional_video_applications/fcpxobjecttype"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
