{
  "abstract": [
    {
      "text": "A protocol that provides an interface to retrieve the Final Cut Pro timeline proxy objects and details of the host app.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/FCPXHost"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(pl)FCPXHost",
    "fragments": [
      {
        "kind": "keyword",
        "text": "protocol"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "FCPXHost"
      }
    ],
    "modules": [
      {
        "name": "Professional Video Applications"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "FCPXHost"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "introducedAt": "1.0",
        "name": "ProVideo Workflow Extensions"
      }
    ],
    "role": "symbol",
    "roleHeading": "Protocol",
    "symbolKind": "protocol",
    "title": "FCPXHost"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "Unsupported OS: ProExtensionHost"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "protocol"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "FCPXHost"
            },
            {
              "kind": "text",
              "text": " : "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSObject",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(pl)NSObject",
              "text": "NSObjectProtocol"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "kind": "mentions",
      "mentions": [
        "doc://com.apple.professionalvideoapplications/documentation/Professional-Video-Applications/interacting-with-the-final-cut-pro-timeline"
      ]
    },
    {
      "content": [
        {
          "anchor": "overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Workflow extensions can use the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/FCPXHost/timeline",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " property of this protocol as a starting point for communicating with the Final Cut Pro timeline.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.professionalvideoapplications/documentation/Professional-Video-Applications/interacting-with-the-final-cut-pro-timeline": {
      "abstract": [
        {
          "text": "Extend your workflows beyond media exchange by enabling a workflow extension to interact with the Final Cut Pro timeline.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.professionalvideoapplications/documentation/Professional-Video-Applications/interacting-with-the-final-cut-pro-timeline",
      "kind": "article",
      "role": "article",
      "title": "Interacting with the Final Cut Pro Timeline",
      "type": "topic",
      "url": "/documentation/professional-video-applications/interacting-with-the-final-cut-pro-timeline"
    },
    "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications": {
      "abstract": [
        {
          "text": "Exchange data with Final Cut Pro, and create effects plug-ins for Final Cut Pro and Motion.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications",
      "kind": "symbol",
      "role": "collection",
      "title": "Professional Video Applications",
      "type": "topic",
      "url": "/documentation/professional_video_applications"
    },
    "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/FCPXHost": {
      "abstract": [
        {
          "text": "A protocol that provides an interface to retrieve the Final Cut Pro timeline proxy objects and details of the host app.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "FCPXHost"
        }
      ],
      "identifier": "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/FCPXHost",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "FCPXHost"
        }
      ],
      "role": "symbol",
      "title": "FCPXHost",
      "type": "topic",
      "url": "/documentation/professional_video_applications/fcpxhost"
    },
    "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/FCPXHost/bundleIdentifier": {
      "abstract": [
        {
          "text": "A unique string that identifies a host app to the system.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "bundleIdentifier"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/FCPXHost/bundleIdentifier",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "bundleIdentifier"
        }
      ],
      "required": true,
      "role": "symbol",
      "title": "bundleIdentifier",
      "type": "topic",
      "url": "/documentation/professional_video_applications/fcpxhost/bundleidentifier"
    },
    "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/FCPXHost/name": {
      "abstract": [
        {
          "text": "The name of the host app.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "name"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/FCPXHost/name",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "name"
        }
      ],
      "required": true,
      "role": "symbol",
      "title": "name",
      "type": "topic",
      "url": "/documentation/professional_video_applications/fcpxhost/name"
    },
    "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/FCPXHost/timeline": {
      "abstract": [
        {
          "text": "A pointer to the Final Cut Pro timeline proxy object.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "timeline"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)FCPXTimeline",
          "text": "FCPXTimeline"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/FCPXHost/timeline",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "timeline"
        }
      ],
      "required": true,
      "role": "symbol",
      "title": "timeline",
      "type": "topic",
      "url": "/documentation/professional_video_applications/fcpxhost/timeline"
    },
    "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/FCPXHost/versionString": {
      "abstract": [
        {
          "text": "The version number of the host app.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "versionString"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/FCPXHost/versionString",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "versionString"
        }
      ],
      "required": true,
      "role": "symbol",
      "title": "versionString",
      "type": "topic",
      "url": "/documentation/professional_video_applications/fcpxhost/versionstring"
    },
    "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/FCPXTimeline": {
      "abstract": [
        {
          "text": "An interface that has methods and properties to communicate and interact with the Final Cut Pro timeline.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "FCPXTimeline"
        }
      ],
      "identifier": "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/FCPXTimeline",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "FCPXTimeline"
        }
      ],
      "role": "symbol",
      "title": "FCPXTimeline",
      "type": "topic",
      "url": "/documentation/professional_video_applications/fcpxtimeline"
    },
    "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/FCPXTimelineObserver": {
      "abstract": [
        {
          "text": "An interface with optional methods implemented by observers of ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/FCPXTimeline",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "FCPXTimelineObserver"
        }
      ],
      "identifier": "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/FCPXTimelineObserver",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "FCPXTimelineObserver"
        }
      ],
      "role": "symbol",
      "title": "FCPXTimelineObserver",
      "type": "topic",
      "url": "/documentation/professional_video_applications/fcpxtimelineobserver"
    },
    "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/ProExtensionHostSingleton()": {
      "abstract": [
        {
          "text": "Returns the singleton proxy instance of the host object.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ProExtensionHostSingleton"
        },
        {
          "kind": "text",
          "text": "() -> (any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(pl)NSObject",
          "text": "NSObjectProtocol"
        },
        {
          "kind": "text",
          "text": ")?"
        }
      ],
      "identifier": "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/ProExtensionHostSingleton()",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ProExtensionHostSingleton"
        }
      ],
      "role": "symbol",
      "title": "ProExtensionHostSingleton()",
      "type": "topic",
      "url": "/documentation/professional_video_applications/proextensionhostsingleton()"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)NSObject": {
      "abstract": [
        {
          "text": "The group of methods that are fundamental to all Objective-C objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "protocol "
        },
        {
          "kind": "identifier",
          "text": "NSObjectProtocol"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSObject",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSObjectProtocol",
      "type": "topic",
      "url": "/documentation/objectivec/nsobjectprotocol"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/c:objc(pl)NSObject"
      ],
      "kind": "relationships",
      "title": "Inherits From",
      "type": "inheritsFrom"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "FCPX-Interactions",
      "generated": true,
      "identifiers": [
        "doc://com.apple.professionalvideoapplications/documentation/Professional-Video-Applications/interacting-with-the-final-cut-pro-timeline",
        "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/ProExtensionHostSingleton()",
        "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/FCPXTimeline",
        "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/FCPXTimelineObserver"
      ],
      "title": "FCPX Interactions"
    }
  ],
  "topicSections": [
    {
      "anchor": "Getting-the-Host-Object-Details",
      "identifiers": [
        "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/FCPXHost/bundleIdentifier",
        "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/FCPXHost/name",
        "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/FCPXHost/timeline",
        "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/FCPXHost/versionString"
      ],
      "title": "Getting the Host Object Details"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": null
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Protocol"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "FCPXHost"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "protocol"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "FCPXHost"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "FCPXHost"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Getting-the-Host-Object-Details",
              "identifiers": [
                "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/FCPXHost/bundleIdentifier",
                "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/FCPXHost/name",
                "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/FCPXHost/timeline",
                "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/FCPXHost/versionString"
              ],
              "title": "Getting the Host Object Details"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": [
            {
              "identifiers": [
                "doc://com.externally.resolved.symbol/c:objc(pl)NSObject"
              ],
              "kind": "relationships",
              "title": "Inherits From",
              "type": "inheritsFrom"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "FCPX-Interactions",
              "generated": true,
              "identifiers": [
                "doc://com.apple.professionalvideoapplications/documentation/Professional-Video-Applications/interacting-with-the-final-cut-pro-timeline",
                "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/ProExtensionHostSingleton()",
                "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/FCPXTimeline",
                "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/FCPXTimelineObserver"
              ],
              "title": "FCPX Interactions"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "Unsupported OS: ProExtensionHost"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "@protocol"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "FCPXHost"
                  },
                  {
                    "kind": "text",
                    "text": " <"
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSObject",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(pl)NSObject",
                    "text": "NSObject"
                  },
                  {
                    "kind": "text",
                    "text": ">"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:objc(pl)NSObject/title",
          "value": "NSObject"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.professionalvideoapplications~1documentation~1professional_video_applications~1FCPXHost~1versionString/title",
          "value": "versionString"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.professionalvideoapplications~1documentation~1professional_video_applications~1FCPXHost~1versionString/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "versionString"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.professionalvideoapplications~1documentation~1professional_video_applications~1FCPXHost~1name/title",
          "value": "name"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.professionalvideoapplications~1documentation~1professional_video_applications~1FCPXHost~1name/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "name"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.professionalvideoapplications~1documentation~1professional_video_applications~1FCPXHost/title",
          "value": "FCPXHost"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.professionalvideoapplications~1documentation~1professional_video_applications~1FCPXHost/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "FCPXHost"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.professionalvideoapplications~1documentation~1professional_video_applications~1FCPXHost/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "FCPXHost"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.professionalvideoapplications~1documentation~1professional_video_applications~1FCPXTimeline/title",
          "value": "FCPXTimeline"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.professionalvideoapplications~1documentation~1professional_video_applications~1FCPXTimeline/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "FCPXTimeline"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.professionalvideoapplications~1documentation~1professional_video_applications~1FCPXTimeline/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "FCPXTimeline"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.professionalvideoapplications~1documentation~1professional_video_applications~1FCPXHost~1timeline/title",
          "value": "timeline"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.professionalvideoapplications~1documentation~1professional_video_applications~1FCPXHost~1timeline/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "timeline"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.professionalvideoapplications~1documentation~1professional_video_applications~1FCPXTimelineObserver/title",
          "value": "FCPXTimelineObserver"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.professionalvideoapplications~1documentation~1professional_video_applications~1FCPXTimelineObserver/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "FCPXTimelineObserver"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.professionalvideoapplications~1documentation~1professional_video_applications~1FCPXTimelineObserver/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "FCPXTimelineObserver"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.professionalvideoapplications~1documentation~1professional_video_applications~1FCPXHost~1bundleIdentifier/title",
          "value": "bundleIdentifier"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.professionalvideoapplications~1documentation~1professional_video_applications~1FCPXHost~1bundleIdentifier/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "bundleIdentifier"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.professionalvideoapplications~1documentation~1professional_video_applications~1ProExtensionHostSingleton()/title",
          "value": "ProExtensionHostSingleton"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.professionalvideoapplications~1documentation~1professional_video_applications~1ProExtensionHostSingleton()/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ProExtensionHostSingleton"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/professional_video_applications/fcpxhost"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/professional_video_applications/fcpxhost"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
