{
  "abstract": [
    {
      "text": "The possible states of frame analysis, as reported by the host application.",
      "type": "text"
    }
  ],
  "diffAvailability": {
    "major": {
      "change": "added",
      "platform": "FxPlug",
      "versions": [
        "4.0",
        "4.2.9"
      ]
    }
  },
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/FxAnalysisState"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@T@FxAnalysisState",
    "fragments": [
      {
        "kind": "keyword",
        "text": "typealias"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "FxAnalysisState"
      }
    ],
    "modules": [
      {
        "name": "Professional Video Applications"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "FxAnalysisState"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "introducedAt": "4.1",
        "name": "FxPlug"
      }
    ],
    "role": "symbol",
    "roleHeading": "Type Alias",
    "symbolKind": "typealias",
    "title": "FxAnalysisState"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "Unsupported OS: FxPlug"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "typealias"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "FxAnalysisState"
            },
            {
              "kind": "text",
              "text": " = "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:Si",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:Si",
              "text": "Int"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "kind": "parameters",
      "parameters": [
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "Not currently analyzing.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "kFxAnalysisState_NotAnalyzing"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "Analysis requested.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "kFxAnalysisState_AnalysisRequested"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "Analysis started.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "kFxAnalysisState_AnalysisStarted"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "Analysis completed.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "kFxAnalysisState_AnalysisCompleted"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "Analysis interrupted.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "kFxAnalysisState_AnalysisInterrupted"
        }
      ]
    },
    {
      "content": [
        {
          "anchor": "discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Query the analysis state with ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/FxAnalysisAPI/analysisStateForEffect()",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ".",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications": {
      "abstract": [
        {
          "text": "Exchange data with Final Cut Pro, and create effects plug-ins for Final Cut Pro and Motion.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications",
      "kind": "symbol",
      "role": "collection",
      "title": "Professional Video Applications",
      "type": "topic",
      "url": "/documentation/professional_video_applications"
    },
    "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/FxAnalysisAPI/analysisStateForEffect()": {
      "abstract": [
        {
          "text": "Fetches the state of frame analysis for your plug-in.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "analysisStateForEffect"
        },
        {
          "kind": "text",
          "text": "() -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@FxAnalysisState",
          "text": "FxAnalysisState"
        }
      ],
      "identifier": "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/FxAnalysisAPI/analysisStateForEffect()",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "analysisStateForEffect"
        }
      ],
      "required": true,
      "role": "symbol",
      "title": "analysisStateForEffect()",
      "type": "topic",
      "url": "/documentation/professional_video_applications/fxanalysisapi/analysisstateforeffect()"
    },
    "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/FxAnalysisState": {
      "abstract": [
        {
          "text": "The possible states of frame analysis, as reported by the host application.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "FxAnalysisState"
        }
      ],
      "identifier": "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/FxAnalysisState",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "FxAnalysisState"
        }
      ],
      "role": "symbol",
      "title": "FxAnalysisState",
      "type": "topic",
      "url": "/documentation/professional_video_applications/fxanalysisstate"
    },
    "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/kFxAnalysisState_AnalysisCompleted": {
      "abstract": [
        {
          "text": "Analysis completed.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kFxAnalysisState_AnalysisCompleted"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@FxAnalysisState",
          "text": "FxAnalysisState"
        }
      ],
      "identifier": "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/kFxAnalysisState_AnalysisCompleted",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kFxAnalysisState_AnalysisCompleted"
        }
      ],
      "role": "symbol",
      "title": "kFxAnalysisState_AnalysisCompleted",
      "type": "topic",
      "url": "/documentation/professional_video_applications/kfxanalysisstate_analysiscompleted"
    },
    "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/kFxAnalysisState_AnalysisInterrupted": {
      "abstract": [
        {
          "text": "Analysis interrupted.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kFxAnalysisState_AnalysisInterrupted"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@FxAnalysisState",
          "text": "FxAnalysisState"
        }
      ],
      "identifier": "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/kFxAnalysisState_AnalysisInterrupted",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kFxAnalysisState_AnalysisInterrupted"
        }
      ],
      "role": "symbol",
      "title": "kFxAnalysisState_AnalysisInterrupted",
      "type": "topic",
      "url": "/documentation/professional_video_applications/kfxanalysisstate_analysisinterrupted"
    },
    "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/kFxAnalysisState_AnalysisRequested": {
      "abstract": [
        {
          "text": "Analysis requested.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kFxAnalysisState_AnalysisRequested"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@FxAnalysisState",
          "text": "FxAnalysisState"
        }
      ],
      "identifier": "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/kFxAnalysisState_AnalysisRequested",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kFxAnalysisState_AnalysisRequested"
        }
      ],
      "role": "symbol",
      "title": "kFxAnalysisState_AnalysisRequested",
      "type": "topic",
      "url": "/documentation/professional_video_applications/kfxanalysisstate_analysisrequested"
    },
    "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/kFxAnalysisState_AnalysisStarted": {
      "abstract": [
        {
          "text": "Analysis started.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kFxAnalysisState_AnalysisStarted"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@FxAnalysisState",
          "text": "FxAnalysisState"
        }
      ],
      "identifier": "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/kFxAnalysisState_AnalysisStarted",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kFxAnalysisState_AnalysisStarted"
        }
      ],
      "role": "symbol",
      "title": "kFxAnalysisState_AnalysisStarted",
      "type": "topic",
      "url": "/documentation/professional_video_applications/kfxanalysisstate_analysisstarted"
    },
    "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/kFxAnalysisState_NotAnalyzing": {
      "abstract": [
        {
          "text": "Not currently analyzing.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kFxAnalysisState_NotAnalyzing"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@FxAnalysisState",
          "text": "FxAnalysisState"
        }
      ],
      "identifier": "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/kFxAnalysisState_NotAnalyzing",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kFxAnalysisState_NotAnalyzing"
        }
      ],
      "role": "symbol",
      "title": "kFxAnalysisState_NotAnalyzing",
      "type": "topic",
      "url": "/documentation/professional_video_applications/kfxanalysisstate_notanalyzing"
    },
    "doc://com.externally.resolved.symbol/s:Si": {
      "abstract": [
        {
          "text": "A signed integer value type.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@frozen"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:Si",
      "kind": "symbol",
      "role": "symbol",
      "title": "Int",
      "type": "topic",
      "url": "/documentation/Swift/Int"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "topicSections": [
    {
      "anchor": "States-of-Analysis",
      "identifiers": [
        "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/kFxAnalysisState_NotAnalyzing",
        "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/kFxAnalysisState_AnalysisRequested",
        "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/kFxAnalysisState_AnalysisStarted",
        "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/kFxAnalysisState_AnalysisCompleted",
        "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/kFxAnalysisState_AnalysisInterrupted"
      ],
      "title": "States of Analysis"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": null
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Type Alias"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "FxAnalysisState"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "typealias"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "FxAnalysisState"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "FxAnalysisState"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "States-of-Analysis",
              "identifiers": [
                "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/kFxAnalysisState_NotAnalyzing",
                "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/kFxAnalysisState_AnalysisRequested",
                "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/kFxAnalysisState_AnalysisStarted",
                "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/kFxAnalysisState_AnalysisCompleted",
                "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/kFxAnalysisState_AnalysisInterrupted"
              ],
              "title": "States of Analysis"
            }
          ]
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/seeAlsoSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "Unsupported OS: FxPlug"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "typedef"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@NSUInteger",
                    "text": "NSUInteger"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "FxAnalysisState"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.professionalvideoapplications~1documentation~1professional_video_applications~1FxAnalysisAPI~1analysisStateForEffect()/title",
          "value": "analysisStateForEffect"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.professionalvideoapplications~1documentation~1professional_video_applications~1FxAnalysisAPI~1analysisStateForEffect()/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "analysisStateForEffect"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.professionalvideoapplications~1documentation~1professional_video_applications~1kFxAnalysisState_AnalysisInterrupted/title",
          "value": "kFxAnalysisState_AnalysisInterrupted"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.professionalvideoapplications~1documentation~1professional_video_applications~1kFxAnalysisState_AnalysisInterrupted/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kFxAnalysisState_AnalysisInterrupted"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.professionalvideoapplications~1documentation~1professional_video_applications~1kFxAnalysisState_AnalysisRequested/title",
          "value": "kFxAnalysisState_AnalysisRequested"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.professionalvideoapplications~1documentation~1professional_video_applications~1kFxAnalysisState_AnalysisRequested/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kFxAnalysisState_AnalysisRequested"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.professionalvideoapplications~1documentation~1professional_video_applications~1kFxAnalysisState_AnalysisStarted/title",
          "value": "kFxAnalysisState_AnalysisStarted"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.professionalvideoapplications~1documentation~1professional_video_applications~1kFxAnalysisState_AnalysisStarted/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kFxAnalysisState_AnalysisStarted"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.professionalvideoapplications~1documentation~1professional_video_applications~1kFxAnalysisState_AnalysisCompleted/title",
          "value": "kFxAnalysisState_AnalysisCompleted"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.professionalvideoapplications~1documentation~1professional_video_applications~1kFxAnalysisState_AnalysisCompleted/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kFxAnalysisState_AnalysisCompleted"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.professionalvideoapplications~1documentation~1professional_video_applications~1FxAnalysisState/title",
          "value": "FxAnalysisState"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.professionalvideoapplications~1documentation~1professional_video_applications~1FxAnalysisState/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "FxAnalysisState"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.professionalvideoapplications~1documentation~1professional_video_applications~1FxAnalysisState/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "FxAnalysisState"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.professionalvideoapplications~1documentation~1professional_video_applications~1kFxAnalysisState_NotAnalyzing/title",
          "value": "kFxAnalysisState_NotAnalyzing"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.professionalvideoapplications~1documentation~1professional_video_applications~1kFxAnalysisState_NotAnalyzing/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kFxAnalysisState_NotAnalyzing"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/professional_video_applications/fxanalysisstate"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/professional_video_applications/fxanalysisstate"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
