{
  "abstract": [
    {
      "text": "A protocol you implement in your plug-in to analyze frames that the plug-in is applied to.",
      "type": "text"
    }
  ],
  "diffAvailability": {
    "major": {
      "change": "added",
      "platform": "FxPlug",
      "versions": [
        "4.0",
        "4.2.9"
      ]
    }
  },
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/FxAnalyzer"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(pl)FxAnalyzer",
    "fragments": [
      {
        "kind": "keyword",
        "text": "protocol"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "FxAnalyzer"
      }
    ],
    "modules": [
      {
        "name": "Professional Video Applications"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "FxAnalyzer"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "introducedAt": "4.1",
        "name": "FxPlug"
      }
    ],
    "role": "symbol",
    "roleHeading": "Protocol",
    "symbolKind": "protocol",
    "title": "FxAnalyzer"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "Unsupported OS: FxPlug"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "protocol"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "FxAnalyzer"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "kind": "mentions",
      "mentions": [
        "doc://com.apple.professionalvideoapplications/documentation/Professional-Video-Applications/analyzing-media"
      ]
    },
    {
      "content": [
        {
          "anchor": "overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Implement this protocol if your plug-in needs to analyze some or all of the frames your plug-in is applied to before being able to render.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.professionalvideoapplications/documentation/Professional-Video-Applications/analyzing-media": {
      "abstract": [
        {
          "text": "Use the FxPlug analysis API to analyze frames of source media before rendering them.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.professionalvideoapplications/documentation/Professional-Video-Applications/analyzing-media",
      "kind": "article",
      "role": "article",
      "title": "Analyzing media",
      "type": "topic",
      "url": "/documentation/professional-video-applications/analyzing-media"
    },
    "doc://com.apple.professionalvideoapplications/documentation/Professional-Video-Applications/scheduling-media-in-plug-ins": {
      "abstract": [
        {
          "text": "Use the scheduling APIs in FxPlug to retrieve frames from different times.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.professionalvideoapplications/documentation/Professional-Video-Applications/scheduling-media-in-plug-ins",
      "kind": "article",
      "role": "article",
      "title": "Scheduling media in plug-ins",
      "type": "topic",
      "url": "/documentation/professional-video-applications/scheduling-media-in-plug-ins"
    },
    "doc://com.apple.professionalvideoapplications/documentation/Professional-Video-Applications/understanding-time-in-fxplug": {
      "abstract": [
        {
          "text": "Learn about time handling in host apps and plug-ins.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.professionalvideoapplications/documentation/Professional-Video-Applications/understanding-time-in-fxplug",
      "kind": "article",
      "role": "article",
      "title": "Understanding time in FxPlug",
      "type": "topic",
      "url": "/documentation/professional-video-applications/understanding-time-in-fxplug"
    },
    "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications": {
      "abstract": [
        {
          "text": "Exchange data with Final Cut Pro, and create effects plug-ins for Final Cut Pro and Motion.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications",
      "kind": "symbol",
      "role": "collection",
      "title": "Professional Video Applications",
      "type": "topic",
      "url": "/documentation/professional_video_applications"
    },
    "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/FxAnalysisAPI": {
      "abstract": [
        {
          "text": "A protocol that host applications implement to provide information to plug-ins that support the FxAnalyzer protocol.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "FxAnalysisAPI"
        }
      ],
      "identifier": "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/FxAnalysisAPI",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "FxAnalysisAPI"
        }
      ],
      "role": "symbol",
      "title": "FxAnalysisAPI",
      "type": "topic",
      "url": "/documentation/professional_video_applications/fxanalysisapi"
    },
    "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/FxAnalysisAPI_v2": {
      "abstract": [
        {
          "text": "A protocol that host applications implement to provide information to plug-ins that support the FxAnalyzer protocol.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "FxAnalysisAPI_v2"
        }
      ],
      "identifier": "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/FxAnalysisAPI_v2",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "FxAnalysisAPI_v2"
        }
      ],
      "role": "symbol",
      "title": "FxAnalysisAPI_v2",
      "type": "topic",
      "url": "/documentation/professional_video_applications/fxanalysisapi_v2"
    },
    "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/FxAnalysisState": {
      "abstract": [
        {
          "text": "The possible states of frame analysis, as reported by the host application.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "FxAnalysisState"
        }
      ],
      "identifier": "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/FxAnalysisState",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "FxAnalysisState"
        }
      ],
      "role": "symbol",
      "title": "FxAnalysisState",
      "type": "topic",
      "url": "/documentation/professional_video_applications/fxanalysisstate"
    },
    "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/FxAnalyzer": {
      "abstract": [
        {
          "text": "A protocol you implement in your plug-in to analyze frames that the plug-in is applied to.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "FxAnalyzer"
        }
      ],
      "identifier": "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/FxAnalyzer",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "FxAnalyzer"
        }
      ],
      "role": "symbol",
      "title": "FxAnalyzer",
      "type": "topic",
      "url": "/documentation/professional_video_applications/fxanalyzer"
    },
    "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/FxAnalyzer/analyzeFrame(_:at:)": {
      "abstract": [
        {
          "text": "Analyzes the next frame.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "analyzeFrame"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)FxImageTile",
          "text": "FxImageTile"
        },
        {
          "kind": "text",
          "text": "!, "
        },
        {
          "kind": "externalParam",
          "text": "at"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@SA@CMTime",
          "text": "CMTime"
        },
        {
          "kind": "text",
          "text": ") "
        },
        {
          "kind": "keyword",
          "text": "throws"
        }
      ],
      "identifier": "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/FxAnalyzer/analyzeFrame(_:at:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "analyzeFrame:atTime:error:"
        }
      ],
      "required": true,
      "role": "symbol",
      "title": "analyzeFrame(_:at:)",
      "type": "topic",
      "url": "/documentation/professional_video_applications/fxanalyzer/analyzeframe(_:at:)"
    },
    "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/FxAnalyzer/cleanupAnalysis()": {
      "abstract": [
        {
          "text": "Completes any necessary cleanup work after your plug-in’s frame analysis.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "cleanupAnalysis"
        },
        {
          "kind": "text",
          "text": "() "
        },
        {
          "kind": "keyword",
          "text": "throws"
        }
      ],
      "identifier": "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/FxAnalyzer/cleanupAnalysis()",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "cleanupAnalysis:"
        }
      ],
      "required": true,
      "role": "symbol",
      "title": "cleanupAnalysis()",
      "type": "topic",
      "url": "/documentation/professional_video_applications/fxanalyzer/cleanupanalysis()"
    },
    "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/FxAnalyzer/desiredAnalysisTimeRange(_:forInputWith:)": {
      "abstract": [
        {
          "text": "Requests the specified time range of frames you want to analyze.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "desiredAnalysisTimeRange"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sp",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@SA@CMTimeRange",
          "text": "CMTimeRange"
        },
        {
          "kind": "text",
          "text": ">!, "
        },
        {
          "kind": "externalParam",
          "text": "forInputWith"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@SA@CMTimeRange",
          "text": "CMTimeRange"
        },
        {
          "kind": "text",
          "text": ") "
        },
        {
          "kind": "keyword",
          "text": "throws"
        }
      ],
      "identifier": "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/FxAnalyzer/desiredAnalysisTimeRange(_:forInputWith:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "desiredAnalysisTimeRange:forInputWithTimeRange:error:"
        }
      ],
      "required": true,
      "role": "symbol",
      "title": "desiredAnalysisTimeRange(_:forInputWith:)",
      "type": "topic",
      "url": "/documentation/professional_video_applications/fxanalyzer/desiredanalysistimerange(_:forinputwith:)"
    },
    "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/FxAnalyzer/setupAnalysis(for:frameDuration:)": {
      "abstract": [
        {
          "text": "Completes any setup work before starting the frame analysis.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "setupAnalysis"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "for"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@SA@CMTimeRange",
          "text": "CMTimeRange"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "frameDuration"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@SA@CMTime",
          "text": "CMTime"
        },
        {
          "kind": "text",
          "text": ") "
        },
        {
          "kind": "keyword",
          "text": "throws"
        }
      ],
      "identifier": "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/FxAnalyzer/setupAnalysis(for:frameDuration:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "setupAnalysisForTimeRange:frameDuration:error:"
        }
      ],
      "required": true,
      "role": "symbol",
      "title": "setupAnalysis(for:frameDuration:)",
      "type": "topic",
      "url": "/documentation/professional_video_applications/fxanalyzer/setupanalysis(for:frameduration:)"
    },
    "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/FxKeyframeAPI_v3": {
      "abstract": [
        {
          "text": "A collection of methods for manipulating the keyframes of your FxPlug 4 plug-in.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "FxKeyframeAPI_v3"
        }
      ],
      "identifier": "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/FxKeyframeAPI_v3",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "FxKeyframeAPI_v3"
        }
      ],
      "role": "symbol",
      "title": "FxKeyframeAPI_v3",
      "type": "topic",
      "url": "/documentation/professional_video_applications/fxkeyframeapi_v3"
    },
    "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/FxTimingAPI_v4": {
      "abstract": [
        {
          "text": "A protocol that defines the methods provided by the host, so that a plug-in can query the timing properties of its input.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "FxTimingAPI_v4"
        }
      ],
      "identifier": "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/FxTimingAPI_v4",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "FxTimingAPI_v4"
        }
      ],
      "role": "symbol",
      "title": "FxTimingAPI_v4",
      "type": "topic",
      "url": "/documentation/professional_video_applications/fxtimingapi_v4"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Time-and-analysis",
      "generated": true,
      "identifiers": [
        "doc://com.apple.professionalvideoapplications/documentation/Professional-Video-Applications/understanding-time-in-fxplug",
        "doc://com.apple.professionalvideoapplications/documentation/Professional-Video-Applications/scheduling-media-in-plug-ins",
        "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/FxTimingAPI_v4",
        "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/FxKeyframeAPI_v3",
        "doc://com.apple.professionalvideoapplications/documentation/Professional-Video-Applications/analyzing-media",
        "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/FxAnalysisAPI",
        "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/FxAnalysisAPI_v2"
      ],
      "title": "Time and analysis"
    }
  ],
  "topicSections": [
    {
      "anchor": "Analyzing-Frames-in-Your-Plug-in",
      "identifiers": [
        "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/FxAnalyzer/desiredAnalysisTimeRange(_:forInputWith:)",
        "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/FxAnalyzer/setupAnalysis(for:frameDuration:)",
        "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/FxAnalyzer/analyzeFrame(_:at:)",
        "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/FxAnalyzer/cleanupAnalysis()"
      ],
      "title": "Analyzing Frames in Your Plug-in"
    },
    {
      "anchor": "Determining-the-Analysis-State",
      "identifiers": [
        "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/FxAnalysisState"
      ],
      "title": "Determining the Analysis State"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": null
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Protocol"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "FxAnalyzer"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "protocol"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "FxAnalyzer"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "FxAnalyzer"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Analyzing-Frames-in-Your-Plug-in",
              "identifiers": [
                "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/FxAnalyzer/desiredAnalysisTimeRange(_:forInputWith:)",
                "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/FxAnalyzer/setupAnalysis(for:frameDuration:)",
                "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/FxAnalyzer/analyzeFrame(_:at:)",
                "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/FxAnalyzer/cleanupAnalysis()"
              ],
              "title": "Analyzing Frames in Your Plug-in"
            },
            {
              "anchor": "Determining-the-Analysis-State",
              "identifiers": [
                "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/FxAnalysisState"
              ],
              "title": "Determining the Analysis State"
            }
          ]
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Time-and-analysis",
              "generated": true,
              "identifiers": [
                "doc://com.apple.professionalvideoapplications/documentation/Professional-Video-Applications/understanding-time-in-fxplug",
                "doc://com.apple.professionalvideoapplications/documentation/Professional-Video-Applications/scheduling-media-in-plug-ins",
                "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/FxTimingAPI_v4",
                "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/FxKeyframeAPI_v3",
                "doc://com.apple.professionalvideoapplications/documentation/Professional-Video-Applications/analyzing-media",
                "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/FxAnalysisAPI",
                "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/FxAnalysisAPI_v2"
              ],
              "title": "Time and analysis"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "Unsupported OS: FxPlug"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "@protocol"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "FxAnalyzer"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.professionalvideoapplications~1documentation~1professional_video_applications~1FxTimingAPI_v4/title",
          "value": "FxTimingAPI_v4"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.professionalvideoapplications~1documentation~1professional_video_applications~1FxTimingAPI_v4/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "FxTimingAPI_v4"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.professionalvideoapplications~1documentation~1professional_video_applications~1FxTimingAPI_v4/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "FxTimingAPI_v4"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.professionalvideoapplications~1documentation~1professional_video_applications~1FxAnalyzer~1analyzeFrame(_:at:)/title",
          "value": "analyzeFrame:atTime:error:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.professionalvideoapplications~1documentation~1professional_video_applications~1FxAnalyzer~1analyzeFrame(_:at:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "analyzeFrame:atTime:error:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.professionalvideoapplications~1documentation~1professional_video_applications~1FxAnalysisAPI/title",
          "value": "FxAnalysisAPI"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.professionalvideoapplications~1documentation~1professional_video_applications~1FxAnalysisAPI/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "FxAnalysisAPI"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.professionalvideoapplications~1documentation~1professional_video_applications~1FxAnalysisAPI/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "FxAnalysisAPI"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.professionalvideoapplications~1documentation~1professional_video_applications~1FxAnalyzer/title",
          "value": "FxAnalyzer"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.professionalvideoapplications~1documentation~1professional_video_applications~1FxAnalyzer/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "FxAnalyzer"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.professionalvideoapplications~1documentation~1professional_video_applications~1FxAnalyzer/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "FxAnalyzer"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.professionalvideoapplications~1documentation~1professional_video_applications~1FxAnalyzer~1setupAnalysis(for:frameDuration:)/title",
          "value": "setupAnalysisForTimeRange:frameDuration:error:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.professionalvideoapplications~1documentation~1professional_video_applications~1FxAnalyzer~1setupAnalysis(for:frameDuration:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "setupAnalysisForTimeRange:frameDuration:error:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.professionalvideoapplications~1documentation~1professional_video_applications~1FxAnalyzer~1desiredAnalysisTimeRange(_:forInputWith:)/title",
          "value": "desiredAnalysisTimeRange:forInputWithTimeRange:error:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.professionalvideoapplications~1documentation~1professional_video_applications~1FxAnalyzer~1desiredAnalysisTimeRange(_:forInputWith:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "desiredAnalysisTimeRange:forInputWithTimeRange:error:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.professionalvideoapplications~1documentation~1professional_video_applications~1FxAnalysisAPI_v2/title",
          "value": "FxAnalysisAPI_v2"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.professionalvideoapplications~1documentation~1professional_video_applications~1FxAnalysisAPI_v2/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "FxAnalysisAPI_v2"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.professionalvideoapplications~1documentation~1professional_video_applications~1FxAnalysisAPI_v2/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "FxAnalysisAPI_v2"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.professionalvideoapplications~1documentation~1professional_video_applications~1FxAnalyzer~1cleanupAnalysis()/title",
          "value": "cleanupAnalysis:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.professionalvideoapplications~1documentation~1professional_video_applications~1FxAnalyzer~1cleanupAnalysis()/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "cleanupAnalysis:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.professionalvideoapplications~1documentation~1professional_video_applications~1FxAnalysisState/title",
          "value": "FxAnalysisState"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.professionalvideoapplications~1documentation~1professional_video_applications~1FxAnalysisState/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "FxAnalysisState"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.professionalvideoapplications~1documentation~1professional_video_applications~1FxAnalysisState/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "FxAnalysisState"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.professionalvideoapplications~1documentation~1professional_video_applications~1FxKeyframeAPI_v3/title",
          "value": "FxKeyframeAPI_v3"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.professionalvideoapplications~1documentation~1professional_video_applications~1FxKeyframeAPI_v3/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "FxKeyframeAPI_v3"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.professionalvideoapplications~1documentation~1professional_video_applications~1FxKeyframeAPI_v3/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "FxKeyframeAPI_v3"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/professional_video_applications/fxanalyzer"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/professional_video_applications/fxanalyzer"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
