{
  "abstract": [
    {
      "text": "Commands that you can tell the host to perform.",
      "type": "text"
    }
  ],
  "diffAvailability": {
    "major": {
      "change": "added",
      "platform": "FxPlug",
      "versions": [
        "4.0",
        "4.2.9"
      ]
    }
  },
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/FxCommandAPI"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(pl)FxCommandAPI",
    "fragments": [
      {
        "kind": "keyword",
        "text": "protocol"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "FxCommandAPI"
      }
    ],
    "modules": [
      {
        "name": "Professional Video Applications"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "FxCommandAPI"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "introducedAt": "4.1",
        "name": "FxPlug"
      }
    ],
    "role": "symbol",
    "roleHeading": "Protocol",
    "symbolKind": "protocol",
    "title": "FxCommandAPI"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "Unsupported OS: FxPlug"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "protocol"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "FxCommandAPI"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.professionalvideoapplications/documentation/Professional-Video-Applications/adding-onscreen-controls-to-plug-ins": {
      "abstract": [
        {
          "text": "Simplify user interaction by using onscreen controls for your FxPlug plug-in.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.professionalvideoapplications/documentation/Professional-Video-Applications/adding-onscreen-controls-to-plug-ins",
      "kind": "article",
      "role": "article",
      "title": "Adding onscreen controls to plug-ins",
      "type": "topic",
      "url": "/documentation/professional-video-applications/adding-onscreen-controls-to-plug-ins"
    },
    "doc://com.apple.professionalvideoapplications/documentation/Professional-Video-Applications/adding-parameters-to-plug-ins": {
      "abstract": [
        {
          "text": "Create standard and custom user-facing parameters for your plug-in that will appear in the inspector.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.professionalvideoapplications/documentation/Professional-Video-Applications/adding-parameters-to-plug-ins",
      "kind": "article",
      "role": "article",
      "title": "Adding parameters to plug-ins",
      "type": "topic",
      "url": "/documentation/professional-video-applications/adding-parameters-to-plug-ins"
    },
    "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications": {
      "abstract": [
        {
          "text": "Exchange data with Final Cut Pro, and create effects plug-ins for Final Cut Pro and Motion.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications",
      "kind": "symbol",
      "role": "collection",
      "title": "Professional Video Applications",
      "type": "topic",
      "url": "/documentation/professional_video_applications"
    },
    "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/FxCommand": {
      "abstract": [
        {
          "text": "Defines the commands that can be performed by the host.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "FxCommand"
        }
      ],
      "identifier": "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/FxCommand",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "FxCommand"
        }
      ],
      "role": "symbol",
      "title": "FxCommand",
      "type": "topic",
      "url": "/documentation/professional_video_applications/fxcommand"
    },
    "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/FxCommandAPI": {
      "abstract": [
        {
          "text": "Commands that you can tell the host to perform.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "FxCommandAPI"
        }
      ],
      "identifier": "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/FxCommandAPI",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "FxCommandAPI"
        }
      ],
      "role": "symbol",
      "title": "FxCommandAPI",
      "type": "topic",
      "url": "/documentation/professional_video_applications/fxcommandapi"
    },
    "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/FxCommandAPI/perform(_:)": {
      "abstract": [
        {
          "text": "Instructs the host application to perform a command.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "perform"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@FxCommand",
          "text": "FxCommand"
        },
        {
          "kind": "text",
          "text": ") "
        },
        {
          "kind": "keyword",
          "text": "throws"
        }
      ],
      "identifier": "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/FxCommandAPI/perform(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "performCommand:error:"
        }
      ],
      "required": true,
      "role": "symbol",
      "title": "perform(_:)",
      "type": "topic",
      "url": "/documentation/professional_video_applications/fxcommandapi/perform(_:)"
    },
    "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/FxCommandAPI_v2": {
      "abstract": [
        {
          "text": "Adds functionality to move the playhead to a specific timeline time.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "FxCommandAPI_v2"
        }
      ],
      "identifier": "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/FxCommandAPI_v2",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "FxCommandAPI_v2"
        }
      ],
      "role": "symbol",
      "title": "FxCommandAPI_v2",
      "type": "topic",
      "url": "/documentation/professional_video_applications/fxcommandapi_v2"
    },
    "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/FxCommandHandler": {
      "abstract": [
        {
          "text": "Defines the methods a plug-in must implement to be notified of the application’s key binding for common commands.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "FxCommandHandler"
        }
      ],
      "identifier": "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/FxCommandHandler",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "FxCommandHandler"
        }
      ],
      "role": "symbol",
      "title": "FxCommandHandler",
      "type": "topic",
      "url": "/documentation/professional_video_applications/fxcommandhandler"
    },
    "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/FxPathAPI_v3": {
      "abstract": [
        {
          "text": "An API that defines the methods to retrieve information about paths, shapes, and masks the user has drawn on an object.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "FxPathAPI_v3"
        }
      ],
      "identifier": "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/FxPathAPI_v3",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "FxPathAPI_v3"
        }
      ],
      "role": "symbol",
      "title": "FxPathAPI_v3",
      "type": "topic",
      "url": "/documentation/professional_video_applications/fxpathapi_v3"
    },
    "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/FxRemoteWindowAPI": {
      "abstract": [
        {
          "text": "A protocol that allows the plug-in to request that the host create a window.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "FxRemoteWindowAPI"
        }
      ],
      "identifier": "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/FxRemoteWindowAPI",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "FxRemoteWindowAPI"
        }
      ],
      "role": "symbol",
      "title": "FxRemoteWindowAPI",
      "type": "topic",
      "url": "/documentation/professional_video_applications/fxremotewindowapi"
    },
    "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/FxRemoteWindowAPI_v2": {
      "abstract": [
        {
          "text": "A protocol that allows the plug-in to request that the host create a window with a defined minimum and maximum size.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "FxRemoteWindowAPI_v2"
        }
      ],
      "identifier": "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/FxRemoteWindowAPI_v2",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "FxRemoteWindowAPI_v2"
        }
      ],
      "role": "symbol",
      "title": "FxRemoteWindowAPI_v2",
      "type": "topic",
      "url": "/documentation/professional_video_applications/fxremotewindowapi_v2"
    },
    "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/FxUndoAPI": {
      "abstract": [
        {
          "text": "An API that defines the methods that the host app implements to handle plug-in management of the host app’s undo queue.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "FxUndoAPI"
        }
      ],
      "identifier": "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/FxUndoAPI",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "FxUndoAPI"
        }
      ],
      "role": "symbol",
      "title": "FxUndoAPI",
      "type": "topic",
      "url": "/documentation/professional_video_applications/fxundoapi"
    },
    "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/kKeyChar_DownArrow": {
      "abstract": [
        {
          "text": "The key character for Unicode 0x21df.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kKeyChar_DownArrow"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@unichar",
          "text": "unichar"
        }
      ],
      "identifier": "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/kKeyChar_DownArrow",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kKeyChar_DownArrow"
        }
      ],
      "role": "symbol",
      "title": "kKeyChar_DownArrow",
      "type": "topic",
      "url": "/documentation/professional_video_applications/kkeychar_downarrow"
    },
    "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/kKeyChar_LeftArrow": {
      "abstract": [
        {
          "text": "The key character for Unicode 0x21e0.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kKeyChar_LeftArrow"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@unichar",
          "text": "unichar"
        }
      ],
      "identifier": "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/kKeyChar_LeftArrow",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kKeyChar_LeftArrow"
        }
      ],
      "role": "symbol",
      "title": "kKeyChar_LeftArrow",
      "type": "topic",
      "url": "/documentation/professional_video_applications/kkeychar_leftarrow"
    },
    "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/kKeyChar_RightArrow": {
      "abstract": [
        {
          "text": "The key character for Unicode 0x21e2.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kKeyChar_RightArrow"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@unichar",
          "text": "unichar"
        }
      ],
      "identifier": "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/kKeyChar_RightArrow",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kKeyChar_RightArrow"
        }
      ],
      "role": "symbol",
      "title": "kKeyChar_RightArrow",
      "type": "topic",
      "url": "/documentation/professional_video_applications/kkeychar_rightarrow"
    },
    "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/kKeyChar_UpArrow": {
      "abstract": [
        {
          "text": "The key character for Unicode 0x21de.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kKeyChar_UpArrow"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@unichar",
          "text": "unichar"
        }
      ],
      "identifier": "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/kKeyChar_UpArrow",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kKeyChar_UpArrow"
        }
      ],
      "role": "symbol",
      "title": "kKeyChar_UpArrow",
      "type": "topic",
      "url": "/documentation/professional_video_applications/kkeychar_uparrow"
    },
    "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/kKey_Character": {
      "abstract": [
        {
          "text": "The character the user must press to invoke the command.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kKey_Character"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/kKey_Character",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kKey_Character"
        }
      ],
      "role": "symbol",
      "title": "kKey_Character",
      "type": "topic",
      "url": "/documentation/professional_video_applications/kkey_character"
    },
    "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/kKey_Command": {
      "abstract": [
        {
          "text": "The FxCommand that will be invoked by this keypress.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kKey_Command"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/kKey_Command",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kKey_Command"
        }
      ],
      "role": "symbol",
      "title": "kKey_Command",
      "type": "topic",
      "url": "/documentation/professional_video_applications/kkey_command"
    },
    "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/kKey_Modifiers": {
      "abstract": [
        {
          "text": "The modifiers the user must include in the keypress to invoke the command.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kKey_Modifiers"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/kKey_Modifiers",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kKey_Modifiers"
        }
      ],
      "role": "symbol",
      "title": "kKey_Modifiers",
      "type": "topic",
      "url": "/documentation/professional_video_applications/kkey_modifiers"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/FxCommandAPI_v2"
      ],
      "kind": "relationships",
      "title": "Inherited By",
      "type": "inheritedBy"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "User-interface",
      "generated": true,
      "identifiers": [
        "doc://com.apple.professionalvideoapplications/documentation/Professional-Video-Applications/adding-parameters-to-plug-ins",
        "doc://com.apple.professionalvideoapplications/documentation/Professional-Video-Applications/adding-onscreen-controls-to-plug-ins",
        "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/FxPathAPI_v3",
        "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/FxUndoAPI",
        "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/FxCommandAPI_v2",
        "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/FxRemoteWindowAPI",
        "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/FxRemoteWindowAPI_v2"
      ],
      "title": "User interface"
    }
  ],
  "topicSections": [
    {
      "anchor": "Instructing-the-Host-to-Perform-a-Command",
      "identifiers": [
        "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/FxCommandAPI/perform(_:)"
      ],
      "title": "Instructing the Host to Perform a Command"
    },
    {
      "anchor": "Handling-and-Defining-Commands",
      "identifiers": [
        "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/FxCommandHandler",
        "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/FxCommand"
      ],
      "title": "Handling and Defining Commands"
    },
    {
      "anchor": "Constants",
      "identifiers": [
        "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/kKeyChar_UpArrow",
        "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/kKeyChar_LeftArrow",
        "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/kKeyChar_DownArrow",
        "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/kKeyChar_RightArrow",
        "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/kKey_Command",
        "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/kKey_Character",
        "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/kKey_Modifiers"
      ],
      "title": "Constants"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": null
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Protocol"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "FxCommandAPI"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "protocol"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "FxCommandAPI"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "FxCommandAPI"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Instructing-the-Host-to-Perform-a-Command",
              "identifiers": [
                "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/FxCommandAPI/perform(_:)"
              ],
              "title": "Instructing the Host to Perform a Command"
            },
            {
              "anchor": "Handling-and-Defining-Commands",
              "identifiers": [
                "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/FxCommandHandler",
                "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/FxCommand"
              ],
              "title": "Handling and Defining Commands"
            },
            {
              "anchor": "Constants",
              "identifiers": [
                "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/kKeyChar_UpArrow",
                "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/kKeyChar_LeftArrow",
                "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/kKeyChar_DownArrow",
                "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/kKeyChar_RightArrow",
                "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/kKey_Command",
                "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/kKey_Character",
                "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/kKey_Modifiers"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": [
            {
              "identifiers": [
                "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/FxCommandAPI_v2"
              ],
              "kind": "relationships",
              "title": "Inherited By",
              "type": "inheritedBy"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "User-interface",
              "generated": true,
              "identifiers": [
                "doc://com.apple.professionalvideoapplications/documentation/Professional-Video-Applications/adding-parameters-to-plug-ins",
                "doc://com.apple.professionalvideoapplications/documentation/Professional-Video-Applications/adding-onscreen-controls-to-plug-ins",
                "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/FxPathAPI_v3",
                "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/FxUndoAPI",
                "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/FxCommandAPI_v2",
                "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/FxRemoteWindowAPI",
                "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/FxRemoteWindowAPI_v2"
              ],
              "title": "User interface"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "Unsupported OS: FxPlug"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "@protocol"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "FxCommandAPI"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.professionalvideoapplications~1documentation~1professional_video_applications~1FxCommandAPI_v2/title",
          "value": "FxCommandAPI_v2"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.professionalvideoapplications~1documentation~1professional_video_applications~1FxCommandAPI_v2/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "FxCommandAPI_v2"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.professionalvideoapplications~1documentation~1professional_video_applications~1FxCommandAPI_v2/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "FxCommandAPI_v2"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.professionalvideoapplications~1documentation~1professional_video_applications~1FxPathAPI_v3/title",
          "value": "FxPathAPI_v3"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.professionalvideoapplications~1documentation~1professional_video_applications~1FxPathAPI_v3/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "FxPathAPI_v3"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.professionalvideoapplications~1documentation~1professional_video_applications~1FxPathAPI_v3/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "FxPathAPI_v3"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.professionalvideoapplications~1documentation~1professional_video_applications~1kKeyChar_LeftArrow/title",
          "value": "kKeyChar_LeftArrow"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.professionalvideoapplications~1documentation~1professional_video_applications~1kKeyChar_LeftArrow/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kKeyChar_LeftArrow"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.professionalvideoapplications~1documentation~1professional_video_applications~1FxRemoteWindowAPI_v2/title",
          "value": "FxRemoteWindowAPI_v2"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.professionalvideoapplications~1documentation~1professional_video_applications~1FxRemoteWindowAPI_v2/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "FxRemoteWindowAPI_v2"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.professionalvideoapplications~1documentation~1professional_video_applications~1FxRemoteWindowAPI_v2/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "FxRemoteWindowAPI_v2"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.professionalvideoapplications~1documentation~1professional_video_applications~1kKey_Command/title",
          "value": "kKey_Command"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.professionalvideoapplications~1documentation~1professional_video_applications~1kKey_Command/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kKey_Command"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.professionalvideoapplications~1documentation~1professional_video_applications~1kKey_Modifiers/title",
          "value": "kKey_Modifiers"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.professionalvideoapplications~1documentation~1professional_video_applications~1kKey_Modifiers/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kKey_Modifiers"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.professionalvideoapplications~1documentation~1professional_video_applications~1FxCommand/title",
          "value": "FxCommand"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.professionalvideoapplications~1documentation~1professional_video_applications~1FxCommand/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "FxCommand"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.professionalvideoapplications~1documentation~1professional_video_applications~1FxCommand/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "FxCommand"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.professionalvideoapplications~1documentation~1professional_video_applications~1FxCommandHandler/title",
          "value": "FxCommandHandler"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.professionalvideoapplications~1documentation~1professional_video_applications~1FxCommandHandler/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "FxCommandHandler"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.professionalvideoapplications~1documentation~1professional_video_applications~1FxCommandHandler/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "FxCommandHandler"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.professionalvideoapplications~1documentation~1professional_video_applications~1kKeyChar_RightArrow/title",
          "value": "kKeyChar_RightArrow"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.professionalvideoapplications~1documentation~1professional_video_applications~1kKeyChar_RightArrow/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kKeyChar_RightArrow"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.professionalvideoapplications~1documentation~1professional_video_applications~1FxCommandAPI/title",
          "value": "FxCommandAPI"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.professionalvideoapplications~1documentation~1professional_video_applications~1FxCommandAPI/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "FxCommandAPI"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.professionalvideoapplications~1documentation~1professional_video_applications~1FxCommandAPI/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "FxCommandAPI"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.professionalvideoapplications~1documentation~1professional_video_applications~1FxRemoteWindowAPI/title",
          "value": "FxRemoteWindowAPI"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.professionalvideoapplications~1documentation~1professional_video_applications~1FxRemoteWindowAPI/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "FxRemoteWindowAPI"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.professionalvideoapplications~1documentation~1professional_video_applications~1FxRemoteWindowAPI/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "FxRemoteWindowAPI"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.professionalvideoapplications~1documentation~1professional_video_applications~1kKey_Character/title",
          "value": "kKey_Character"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.professionalvideoapplications~1documentation~1professional_video_applications~1kKey_Character/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kKey_Character"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.professionalvideoapplications~1documentation~1professional_video_applications~1FxUndoAPI/title",
          "value": "FxUndoAPI"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.professionalvideoapplications~1documentation~1professional_video_applications~1FxUndoAPI/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "FxUndoAPI"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.professionalvideoapplications~1documentation~1professional_video_applications~1FxUndoAPI/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "FxUndoAPI"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.professionalvideoapplications~1documentation~1professional_video_applications~1kKeyChar_UpArrow/title",
          "value": "kKeyChar_UpArrow"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.professionalvideoapplications~1documentation~1professional_video_applications~1kKeyChar_UpArrow/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kKeyChar_UpArrow"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.professionalvideoapplications~1documentation~1professional_video_applications~1kKeyChar_DownArrow/title",
          "value": "kKeyChar_DownArrow"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.professionalvideoapplications~1documentation~1professional_video_applications~1kKeyChar_DownArrow/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kKeyChar_DownArrow"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.professionalvideoapplications~1documentation~1professional_video_applications~1FxCommandAPI~1perform(_:)/title",
          "value": "performCommand:error:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.professionalvideoapplications~1documentation~1professional_video_applications~1FxCommandAPI~1perform(_:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "performCommand:error:"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/professional_video_applications/fxcommandapi"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/professional_video_applications/fxcommandapi"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
