{
  "abstract": [
    {
      "text": "Adds functionality to move the playhead to a specific timeline time.",
      "type": "text"
    }
  ],
  "diffAvailability": {
    "major": {
      "change": "added",
      "platform": "FxPlug",
      "versions": [
        "4.0",
        "4.2.9"
      ]
    }
  },
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/FxCommandAPI_v2"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(pl)FxCommandAPI_v2",
    "fragments": [
      {
        "kind": "keyword",
        "text": "protocol"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "FxCommandAPI_v2"
      }
    ],
    "modules": [
      {
        "name": "Professional Video Applications"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "FxCommandAPI_v2"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "introducedAt": "4.2",
        "name": "FxPlug"
      }
    ],
    "role": "symbol",
    "roleHeading": "Protocol",
    "symbolKind": "protocol",
    "title": "FxCommandAPI_v2"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "Unsupported OS: FxPlug"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "protocol"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "FxCommandAPI_v2"
            },
            {
              "kind": "text",
              "text": " : "
            },
            {
              "identifier": "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/FxCommandAPI",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(pl)FxCommandAPI",
              "text": "FxCommandAPI"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.professionalvideoapplications/documentation/Professional-Video-Applications/adding-onscreen-controls-to-plug-ins": {
      "abstract": [
        {
          "text": "Simplify user interaction by using onscreen controls for your FxPlug plug-in.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.professionalvideoapplications/documentation/Professional-Video-Applications/adding-onscreen-controls-to-plug-ins",
      "kind": "article",
      "role": "article",
      "title": "Adding onscreen controls to plug-ins",
      "type": "topic",
      "url": "/documentation/professional-video-applications/adding-onscreen-controls-to-plug-ins"
    },
    "doc://com.apple.professionalvideoapplications/documentation/Professional-Video-Applications/adding-parameters-to-plug-ins": {
      "abstract": [
        {
          "text": "Create standard and custom user-facing parameters for your plug-in that will appear in the inspector.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.professionalvideoapplications/documentation/Professional-Video-Applications/adding-parameters-to-plug-ins",
      "kind": "article",
      "role": "article",
      "title": "Adding parameters to plug-ins",
      "type": "topic",
      "url": "/documentation/professional-video-applications/adding-parameters-to-plug-ins"
    },
    "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications": {
      "abstract": [
        {
          "text": "Exchange data with Final Cut Pro, and create effects plug-ins for Final Cut Pro and Motion.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications",
      "kind": "symbol",
      "role": "collection",
      "title": "Professional Video Applications",
      "type": "topic",
      "url": "/documentation/professional_video_applications"
    },
    "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/FxCommandAPI": {
      "abstract": [
        {
          "text": "Commands that you can tell the host to perform.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "FxCommandAPI"
        }
      ],
      "identifier": "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/FxCommandAPI",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "FxCommandAPI"
        }
      ],
      "role": "symbol",
      "title": "FxCommandAPI",
      "type": "topic",
      "url": "/documentation/professional_video_applications/fxcommandapi"
    },
    "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/FxCommandAPI_v2": {
      "abstract": [
        {
          "text": "Adds functionality to move the playhead to a specific timeline time.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "FxCommandAPI_v2"
        }
      ],
      "identifier": "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/FxCommandAPI_v2",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "FxCommandAPI_v2"
        }
      ],
      "role": "symbol",
      "title": "FxCommandAPI_v2",
      "type": "topic",
      "url": "/documentation/professional_video_applications/fxcommandapi_v2"
    },
    "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/FxCommandAPI_v2/movePlayhead(to:)": {
      "abstract": [
        {
          "text": "Moves the playhead to the desired time.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "movePlayhead"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "to"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@SA@CMTime",
          "text": "CMTime"
        },
        {
          "kind": "text",
          "text": ") "
        },
        {
          "kind": "keyword",
          "text": "throws"
        }
      ],
      "identifier": "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/FxCommandAPI_v2/movePlayhead(to:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "movePlayheadToTime:error:"
        }
      ],
      "required": true,
      "role": "symbol",
      "title": "movePlayhead(to:)",
      "type": "topic",
      "url": "/documentation/professional_video_applications/fxcommandapi_v2/moveplayhead(to:)"
    },
    "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/FxPathAPI_v3": {
      "abstract": [
        {
          "text": "An API that defines the methods to retrieve information about paths, shapes, and masks the user has drawn on an object.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "FxPathAPI_v3"
        }
      ],
      "identifier": "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/FxPathAPI_v3",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "FxPathAPI_v3"
        }
      ],
      "role": "symbol",
      "title": "FxPathAPI_v3",
      "type": "topic",
      "url": "/documentation/professional_video_applications/fxpathapi_v3"
    },
    "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/FxRemoteWindowAPI": {
      "abstract": [
        {
          "text": "A protocol that allows the plug-in to request that the host create a window.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "FxRemoteWindowAPI"
        }
      ],
      "identifier": "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/FxRemoteWindowAPI",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "FxRemoteWindowAPI"
        }
      ],
      "role": "symbol",
      "title": "FxRemoteWindowAPI",
      "type": "topic",
      "url": "/documentation/professional_video_applications/fxremotewindowapi"
    },
    "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/FxRemoteWindowAPI_v2": {
      "abstract": [
        {
          "text": "A protocol that allows the plug-in to request that the host create a window with a defined minimum and maximum size.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "FxRemoteWindowAPI_v2"
        }
      ],
      "identifier": "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/FxRemoteWindowAPI_v2",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "FxRemoteWindowAPI_v2"
        }
      ],
      "role": "symbol",
      "title": "FxRemoteWindowAPI_v2",
      "type": "topic",
      "url": "/documentation/professional_video_applications/fxremotewindowapi_v2"
    },
    "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/FxUndoAPI": {
      "abstract": [
        {
          "text": "An API that defines the methods that the host app implements to handle plug-in management of the host app’s undo queue.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "FxUndoAPI"
        }
      ],
      "identifier": "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/FxUndoAPI",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "FxUndoAPI"
        }
      ],
      "role": "symbol",
      "title": "FxUndoAPI",
      "type": "topic",
      "url": "/documentation/professional_video_applications/fxundoapi"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/FxCommandAPI"
      ],
      "kind": "relationships",
      "title": "Inherits From",
      "type": "inheritsFrom"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "User-interface",
      "generated": true,
      "identifiers": [
        "doc://com.apple.professionalvideoapplications/documentation/Professional-Video-Applications/adding-parameters-to-plug-ins",
        "doc://com.apple.professionalvideoapplications/documentation/Professional-Video-Applications/adding-onscreen-controls-to-plug-ins",
        "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/FxPathAPI_v3",
        "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/FxUndoAPI",
        "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/FxCommandAPI",
        "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/FxRemoteWindowAPI",
        "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/FxRemoteWindowAPI_v2"
      ],
      "title": "User interface"
    }
  ],
  "topicSections": [
    {
      "anchor": "Moving-the-Playhead",
      "identifiers": [
        "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/FxCommandAPI_v2/movePlayhead(to:)"
      ],
      "title": "Moving the Playhead"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": null
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Protocol"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "FxCommandAPI_v2"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "protocol"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "FxCommandAPI_v2"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "FxCommandAPI_v2"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Moving-the-Playhead",
              "identifiers": [
                "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/FxCommandAPI_v2/movePlayhead(to:)"
              ],
              "title": "Moving the Playhead"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": [
            {
              "identifiers": [
                "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/FxCommandAPI"
              ],
              "kind": "relationships",
              "title": "Inherits From",
              "type": "inheritsFrom"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "User-interface",
              "generated": true,
              "identifiers": [
                "doc://com.apple.professionalvideoapplications/documentation/Professional-Video-Applications/adding-parameters-to-plug-ins",
                "doc://com.apple.professionalvideoapplications/documentation/Professional-Video-Applications/adding-onscreen-controls-to-plug-ins",
                "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/FxPathAPI_v3",
                "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/FxUndoAPI",
                "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/FxCommandAPI",
                "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/FxRemoteWindowAPI",
                "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/FxRemoteWindowAPI_v2"
              ],
              "title": "User interface"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "Unsupported OS: FxPlug"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "@protocol"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "FxCommandAPI_v2"
                  },
                  {
                    "kind": "text",
                    "text": " <"
                  },
                  {
                    "identifier": "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/FxCommandAPI",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(pl)FxCommandAPI",
                    "text": "FxCommandAPI"
                  },
                  {
                    "kind": "text",
                    "text": ">"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.professionalvideoapplications~1documentation~1professional_video_applications~1FxPathAPI_v3/title",
          "value": "FxPathAPI_v3"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.professionalvideoapplications~1documentation~1professional_video_applications~1FxPathAPI_v3/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "FxPathAPI_v3"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.professionalvideoapplications~1documentation~1professional_video_applications~1FxPathAPI_v3/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "FxPathAPI_v3"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.professionalvideoapplications~1documentation~1professional_video_applications~1FxRemoteWindowAPI/title",
          "value": "FxRemoteWindowAPI"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.professionalvideoapplications~1documentation~1professional_video_applications~1FxRemoteWindowAPI/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "FxRemoteWindowAPI"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.professionalvideoapplications~1documentation~1professional_video_applications~1FxRemoteWindowAPI/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "FxRemoteWindowAPI"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.professionalvideoapplications~1documentation~1professional_video_applications~1FxCommandAPI_v2~1movePlayhead(to:)/title",
          "value": "movePlayheadToTime:error:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.professionalvideoapplications~1documentation~1professional_video_applications~1FxCommandAPI_v2~1movePlayhead(to:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "movePlayheadToTime:error:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.professionalvideoapplications~1documentation~1professional_video_applications~1FxCommandAPI/title",
          "value": "FxCommandAPI"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.professionalvideoapplications~1documentation~1professional_video_applications~1FxCommandAPI/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "FxCommandAPI"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.professionalvideoapplications~1documentation~1professional_video_applications~1FxCommandAPI/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "FxCommandAPI"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.professionalvideoapplications~1documentation~1professional_video_applications~1FxCommandAPI_v2/title",
          "value": "FxCommandAPI_v2"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.professionalvideoapplications~1documentation~1professional_video_applications~1FxCommandAPI_v2/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "FxCommandAPI_v2"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.professionalvideoapplications~1documentation~1professional_video_applications~1FxCommandAPI_v2/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "FxCommandAPI_v2"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.professionalvideoapplications~1documentation~1professional_video_applications~1FxUndoAPI/title",
          "value": "FxUndoAPI"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.professionalvideoapplications~1documentation~1professional_video_applications~1FxUndoAPI/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "FxUndoAPI"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.professionalvideoapplications~1documentation~1professional_video_applications~1FxUndoAPI/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "FxUndoAPI"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.professionalvideoapplications~1documentation~1professional_video_applications~1FxRemoteWindowAPI_v2/title",
          "value": "FxRemoteWindowAPI_v2"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.professionalvideoapplications~1documentation~1professional_video_applications~1FxRemoteWindowAPI_v2/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "FxRemoteWindowAPI_v2"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.professionalvideoapplications~1documentation~1professional_video_applications~1FxRemoteWindowAPI_v2/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "FxRemoteWindowAPI_v2"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/professional_video_applications/fxcommandapi_v2"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/professional_video_applications/fxcommandapi_v2"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
