{
  "abstract": [
    {
      "text": "An API you use to get information about lights in a scene in a Motion project.",
      "type": "text"
    }
  ],
  "diffAvailability": {
    "major": {
      "change": "added",
      "platform": "FxPlug",
      "versions": [
        "4.0",
        "4.2.9"
      ]
    }
  },
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/FxLightingAPI_v3"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(pl)FxLightingAPI_v3",
    "fragments": [
      {
        "kind": "keyword",
        "text": "protocol"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "FxLightingAPI_v3"
      }
    ],
    "modules": [
      {
        "name": "Professional Video Applications"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "FxLightingAPI_v3"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "introducedAt": "4.0",
        "name": "FxPlug"
      }
    ],
    "role": "symbol",
    "roleHeading": "Protocol",
    "symbolKind": "protocol",
    "title": "FxLightingAPI_v3"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "Unsupported OS: FxPlug"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "protocol"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "FxLightingAPI_v3"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "This API provides a plug-in with the number of lights in a scene, as well as information about each light at a given time.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications": {
      "abstract": [
        {
          "text": "Exchange data with Final Cut Pro, and create effects plug-ins for Final Cut Pro and Motion.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications",
      "kind": "symbol",
      "role": "collection",
      "title": "Professional Video Applications",
      "type": "topic",
      "url": "/documentation/professional_video_applications"
    },
    "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/Fx3DAPI_v5": {
      "abstract": [
        {
          "text": "An API that defines the methods the host application provides to get information about the 3D environment, including camera and object transforms.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Fx3DAPI_v5"
        }
      ],
      "identifier": "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/Fx3DAPI_v5",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "Fx3DAPI_v5"
        }
      ],
      "role": "symbol",
      "title": "Fx3DAPI_v5",
      "type": "topic",
      "url": "/documentation/professional_video_applications/fx3dapi_v5"
    },
    "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/FxLight": {
      "abstract": [
        {
          "text": "A structure that contains lighting information.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "FxLight"
        }
      ],
      "identifier": "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/FxLight",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "FxLight"
        }
      ],
      "role": "symbol",
      "title": "FxLight",
      "type": "topic",
      "url": "/documentation/professional_video_applications/fxlight"
    },
    "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/FxLightType": {
      "abstract": [
        {
          "text": "The type of lighting.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "FxLightType"
        }
      ],
      "identifier": "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/FxLightType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "FxLightType"
        }
      ],
      "role": "symbol",
      "title": "FxLightType",
      "type": "topic",
      "url": "/documentation/professional_video_applications/fxlighttype"
    },
    "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/FxLight_CurrentVersion": {
      "abstract": [
        {
          "text": "A property used to define a lighting information structure as being the most current version.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "FxLight_CurrentVersion"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int32V",
          "text": "Int32"
        }
      ],
      "identifier": "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/FxLight_CurrentVersion",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "FxLight_CurrentVersion"
        }
      ],
      "role": "symbol",
      "title": "FxLight_CurrentVersion",
      "type": "topic",
      "url": "/documentation/professional_video_applications/fxlight_currentversion"
    },
    "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/FxLightingAPI_v3": {
      "abstract": [
        {
          "text": "An API you use to get information about lights in a scene in a Motion project.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "FxLightingAPI_v3"
        }
      ],
      "identifier": "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/FxLightingAPI_v3",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "FxLightingAPI_v3"
        }
      ],
      "role": "symbol",
      "title": "FxLightingAPI_v3",
      "type": "topic",
      "url": "/documentation/professional_video_applications/fxlightingapi_v3"
    },
    "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/FxLightingAPI_v3/lightInfo(_:forLight:at:)": {
      "abstract": [
        {
          "text": "Provides information about a light at a particular time.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "lightInfo"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sp",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@FxLight",
          "text": "FxLight"
        },
        {
          "kind": "text",
          "text": ">!, "
        },
        {
          "kind": "externalParam",
          "text": "forLight"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "at"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@SA@CMTime",
          "text": "CMTime"
        },
        {
          "kind": "text",
          "text": ") "
        },
        {
          "kind": "keyword",
          "text": "throws"
        }
      ],
      "identifier": "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/FxLightingAPI_v3/lightInfo(_:forLight:at:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "lightInfo:forLight:atTime:error:"
        }
      ],
      "required": true,
      "role": "symbol",
      "title": "lightInfo(_:forLight:at:)",
      "type": "topic",
      "url": "/documentation/professional_video_applications/fxlightingapi_v3/lightinfo(_:forlight:at:)"
    },
    "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/FxLightingAPI_v3/numberOfLights(at:)": {
      "abstract": [
        {
          "text": "Retrieves the number of lights at the passed-in time.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "numberOfLights"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "at"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@SA@CMTime",
          "text": "CMTime"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/FxLightingAPI_v3/numberOfLights(at:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "numberOfLightsAtTime:"
        }
      ],
      "required": true,
      "role": "symbol",
      "title": "numberOfLights(at:)",
      "type": "topic",
      "url": "/documentation/professional_video_applications/fxlightingapi_v3/numberoflights(at:)"
    },
    "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/FxMatrix44": {
      "abstract": [
        {
          "text": "The ",
          "type": "text"
        },
        {
          "code": "FxMatrix",
          "type": "codeVoice"
        },
        {
          "text": " class encapsulates a 4x4 matrix object and provides matrix inversion and transforming of 2D and 3D points.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "FxMatrix44"
        }
      ],
      "identifier": "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/FxMatrix44",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "FxMatrix44"
        }
      ],
      "role": "symbol",
      "title": "FxMatrix44",
      "type": "topic",
      "url": "/documentation/professional_video_applications/fxmatrix44"
    },
    "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/kFxLight_V3": {
      "abstract": [
        {
          "text": "The version number of the lighting information.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kFxLight_V3"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int32V",
          "text": "Int32"
        }
      ],
      "identifier": "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/kFxLight_V3",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kFxLight_V3"
        }
      ],
      "role": "symbol",
      "title": "kFxLight_V3",
      "type": "topic",
      "url": "/documentation/professional_video_applications/kfxlight_v3"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "3D-and-lighting",
      "generated": true,
      "identifiers": [
        "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/Fx3DAPI_v5",
        "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/FxMatrix44"
      ],
      "title": "3D and lighting"
    }
  ],
  "topicSections": [
    {
      "anchor": "Getting-Lighting-Information",
      "identifiers": [
        "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/FxLightingAPI_v3/lightInfo(_:forLight:at:)",
        "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/FxLightingAPI_v3/numberOfLights(at:)",
        "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/FxLight"
      ],
      "title": "Getting Lighting Information"
    },
    {
      "anchor": "Constants",
      "identifiers": [
        "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/kFxLight_V3",
        "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/FxLight_CurrentVersion",
        "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/FxLight",
        "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/FxLightType"
      ],
      "title": "Constants"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": null
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Protocol"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "FxLightingAPI_v3"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "protocol"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "FxLightingAPI_v3"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "FxLightingAPI_v3"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Getting-Lighting-Information",
              "identifiers": [
                "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/FxLightingAPI_v3/lightInfo(_:forLight:at:)",
                "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/FxLightingAPI_v3/numberOfLights(at:)",
                "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/FxLight"
              ],
              "title": "Getting Lighting Information"
            },
            {
              "anchor": "Constants",
              "identifiers": [
                "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/kFxLight_V3",
                "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/FxLight_CurrentVersion",
                "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/FxLight",
                "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/FxLightType"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "3D-and-lighting",
              "generated": true,
              "identifiers": [
                "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/Fx3DAPI_v5",
                "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/FxMatrix44"
              ],
              "title": "3D and lighting"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "Unsupported OS: FxPlug"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "@protocol"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "FxLightingAPI_v3"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.professionalvideoapplications~1documentation~1professional_video_applications~1FxLight_CurrentVersion/title",
          "value": "FxLight_CurrentVersion"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.professionalvideoapplications~1documentation~1professional_video_applications~1FxLight_CurrentVersion/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "FxLight_CurrentVersion"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.professionalvideoapplications~1documentation~1professional_video_applications~1FxLightingAPI_v3~1numberOfLights(at:)/title",
          "value": "numberOfLightsAtTime:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.professionalvideoapplications~1documentation~1professional_video_applications~1FxLightingAPI_v3~1numberOfLights(at:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "numberOfLightsAtTime:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.professionalvideoapplications~1documentation~1professional_video_applications~1kFxLight_V3/title",
          "value": "kFxLight_V3"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.professionalvideoapplications~1documentation~1professional_video_applications~1kFxLight_V3/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kFxLight_V3"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.professionalvideoapplications~1documentation~1professional_video_applications~1Fx3DAPI_v5/title",
          "value": "Fx3DAPI_v5"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.professionalvideoapplications~1documentation~1professional_video_applications~1Fx3DAPI_v5/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "Fx3DAPI_v5"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.professionalvideoapplications~1documentation~1professional_video_applications~1Fx3DAPI_v5/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "Fx3DAPI_v5"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.professionalvideoapplications~1documentation~1professional_video_applications~1FxLightingAPI_v3~1lightInfo(_:forLight:at:)/title",
          "value": "lightInfo:forLight:atTime:error:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.professionalvideoapplications~1documentation~1professional_video_applications~1FxLightingAPI_v3~1lightInfo(_:forLight:at:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "lightInfo:forLight:atTime:error:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.professionalvideoapplications~1documentation~1professional_video_applications~1FxLightingAPI_v3/title",
          "value": "FxLightingAPI_v3"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.professionalvideoapplications~1documentation~1professional_video_applications~1FxLightingAPI_v3/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "FxLightingAPI_v3"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.professionalvideoapplications~1documentation~1professional_video_applications~1FxLightingAPI_v3/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "FxLightingAPI_v3"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.professionalvideoapplications~1documentation~1professional_video_applications~1FxMatrix44/title",
          "value": "FxMatrix44"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.professionalvideoapplications~1documentation~1professional_video_applications~1FxMatrix44/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "FxMatrix44"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.professionalvideoapplications~1documentation~1professional_video_applications~1FxMatrix44/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "FxMatrix44"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.professionalvideoapplications~1documentation~1professional_video_applications~1FxLight/title",
          "value": "FxLight"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.professionalvideoapplications~1documentation~1professional_video_applications~1FxLight/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "FxLight"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.professionalvideoapplications~1documentation~1professional_video_applications~1FxLight/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "FxLight"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.professionalvideoapplications~1documentation~1professional_video_applications~1FxLightType/title",
          "value": "FxLightType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.professionalvideoapplications~1documentation~1professional_video_applications~1FxLightType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "FxLightType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.professionalvideoapplications~1documentation~1professional_video_applications~1FxLightType/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "FxLightType"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/professional_video_applications/fxlightingapi_v3"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/professional_video_applications/fxlightingapi_v3"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
