{
  "abstract": [
    {
      "text": "Specifies flags that identify modifier keys held down while an event is generated.",
      "type": "text"
    }
  ],
  "diffAvailability": {
    "major": {
      "change": "added",
      "platform": "FxPlug",
      "versions": [
        "4.0",
        "4.2.9"
      ]
    }
  },
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/FxModifierKeys"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@T@FxModifierKeys",
    "fragments": [
      {
        "kind": "keyword",
        "text": "typealias"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "FxModifierKeys"
      }
    ],
    "modules": [
      {
        "name": "Professional Video Applications"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "FxModifierKeys"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "introducedAt": "3.1",
        "name": "FxPlug"
      }
    ],
    "role": "symbol",
    "roleHeading": "Type Alias",
    "symbolKind": "typealias",
    "title": "FxModifierKeys"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "Unsupported OS: FxPlug"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "typealias"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "FxModifierKeys"
            },
            {
              "kind": "text",
              "text": " = "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:Si",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:Si",
              "text": "Int"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications": {
      "abstract": [
        {
          "text": "Exchange data with Final Cut Pro, and create effects plug-ins for Final Cut Pro and Motion.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications",
      "kind": "symbol",
      "role": "collection",
      "title": "Professional Video Applications",
      "type": "topic",
      "url": "/documentation/professional_video_applications"
    },
    "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/FxAnalysisLocation": {
      "abstract": [
        {
          "text": "Indicates the type of hardware to use for analysis, either CPU or GPU.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "FxAnalysisLocation"
        }
      ],
      "identifier": "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/FxAnalysisLocation",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "FxAnalysisLocation"
        }
      ],
      "role": "symbol",
      "title": "FxAnalysisLocation",
      "type": "topic",
      "url": "/documentation/professional_video_applications/fxanalysislocation"
    },
    "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/FxImageColorInfo": {
      "abstract": [
        {
          "text": "Identifies some color properties of an FxImage instance. These include the color space, gamma level, and, in the case of ",
          "type": "text"
        },
        {
          "code": "YCbCr",
          "type": "codeVoice"
        },
        {
          "text": " images, the color matrix for conversion to RGB.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "FxImageColorInfo"
        }
      ],
      "identifier": "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/FxImageColorInfo",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "FxImageColorInfo"
        }
      ],
      "role": "symbol",
      "title": "FxImageColorInfo",
      "type": "topic",
      "url": "/documentation/professional_video_applications/fximagecolorinfo"
    },
    "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/FxImageOrigin": {
      "abstract": [
        {
          "text": "These constants define the orientation of an image’s coordinate system. Images in Motion have a bottom-left origin. Images in Final Cut have a top-left origin.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "FxImageOrigin"
        }
      ],
      "identifier": "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/FxImageOrigin",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "FxImageOrigin"
        }
      ],
      "role": "symbol",
      "title": "FxImageOrigin",
      "type": "topic",
      "url": "/documentation/professional_video_applications/fximageorigin"
    },
    "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/FxLightType": {
      "abstract": [
        {
          "text": "The type of lighting.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "FxLightType"
        }
      ],
      "identifier": "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/FxLightType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "FxLightType"
        }
      ],
      "role": "symbol",
      "title": "FxLightType",
      "type": "topic",
      "url": "/documentation/professional_video_applications/fxlighttype"
    },
    "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/FxModifierKeys": {
      "abstract": [
        {
          "text": "Specifies flags that identify modifier keys held down while an event is generated.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "FxModifierKeys"
        }
      ],
      "identifier": "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/FxModifierKeys",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "FxModifierKeys"
        }
      ],
      "role": "symbol",
      "title": "FxModifierKeys",
      "type": "topic",
      "url": "/documentation/professional_video_applications/fxmodifierkeys"
    },
    "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/FxPixelTransformSupport": {
      "abstract": [
        {
          "text": "Constants that define the support for pixel transforms.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "FxPixelTransformSupport"
        }
      ],
      "identifier": "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/FxPixelTransformSupport",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "FxPixelTransformSupport"
        }
      ],
      "role": "symbol",
      "title": "FxPixelTransformSupport",
      "type": "topic",
      "url": "/documentation/professional_video_applications/fxpixeltransformsupport"
    },
    "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/kFxModifierKey_CAPS_LOCK": {
      "abstract": [
        {
          "text": "Specifies the Caps-Lock.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kFxModifierKey_CAPS_LOCK"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/kFxModifierKey_CAPS_LOCK",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kFxModifierKey_CAPS_LOCK"
        }
      ],
      "role": "symbol",
      "title": "kFxModifierKey_CAPS_LOCK",
      "type": "topic",
      "url": "/documentation/professional_video_applications/kfxmodifierkey_caps_lock"
    },
    "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/kFxModifierKey_COMMAND": {
      "abstract": [
        {
          "text": "Specifies the Command key.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kFxModifierKey_COMMAND"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/kFxModifierKey_COMMAND",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kFxModifierKey_COMMAND"
        }
      ],
      "role": "symbol",
      "title": "kFxModifierKey_COMMAND",
      "type": "topic",
      "url": "/documentation/professional_video_applications/kfxmodifierkey_command"
    },
    "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/kFxModifierKey_CONTROL": {
      "abstract": [
        {
          "text": "Specifies the left or right Control key.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kFxModifierKey_CONTROL"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/kFxModifierKey_CONTROL",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kFxModifierKey_CONTROL"
        }
      ],
      "role": "symbol",
      "title": "kFxModifierKey_CONTROL",
      "type": "topic",
      "url": "/documentation/professional_video_applications/kfxmodifierkey_control"
    },
    "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/kFxModifierKey_OPTION": {
      "abstract": [
        {
          "text": "Specifies the left or right Option key.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kFxModifierKey_OPTION"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/kFxModifierKey_OPTION",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kFxModifierKey_OPTION"
        }
      ],
      "role": "symbol",
      "title": "kFxModifierKey_OPTION",
      "type": "topic",
      "url": "/documentation/professional_video_applications/kfxmodifierkey_option"
    },
    "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/kFxModifierKey_SHIFT": {
      "abstract": [
        {
          "text": "Specifies the left or right Shift key.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kFxModifierKey_SHIFT"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/kFxModifierKey_SHIFT",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kFxModifierKey_SHIFT"
        }
      ],
      "role": "symbol",
      "title": "kFxModifierKey_SHIFT",
      "type": "topic",
      "url": "/documentation/professional_video_applications/kfxmodifierkey_shift"
    },
    "doc://com.externally.resolved.symbol/s:Si": {
      "abstract": [
        {
          "text": "A signed integer value type.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@frozen"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:Si",
      "kind": "symbol",
      "role": "symbol",
      "title": "Int",
      "type": "topic",
      "url": "/documentation/Swift/Int"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Enumerations",
      "generated": true,
      "identifiers": [
        "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/FxImageColorInfo",
        "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/FxPixelTransformSupport",
        "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/FxImageOrigin",
        "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/FxLightType",
        "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/FxAnalysisLocation"
      ],
      "title": "Enumerations"
    }
  ],
  "topicSections": [
    {
      "anchor": "Constants",
      "identifiers": [
        "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/kFxModifierKey_SHIFT",
        "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/kFxModifierKey_CONTROL",
        "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/kFxModifierKey_OPTION",
        "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/kFxModifierKey_COMMAND",
        "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/kFxModifierKey_CAPS_LOCK"
      ],
      "title": "Constants"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": null
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Type Alias"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "FxModifierKeys"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "typealias"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "FxModifierKeys"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "FxModifierKeys"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Constants",
              "identifiers": [
                "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/kFxModifierKey_SHIFT",
                "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/kFxModifierKey_CONTROL",
                "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/kFxModifierKey_OPTION",
                "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/kFxModifierKey_COMMAND",
                "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/kFxModifierKey_CAPS_LOCK"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Enumerations",
              "generated": true,
              "identifiers": [
                "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/FxImageColorInfo",
                "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/FxPixelTransformSupport",
                "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/FxImageOrigin",
                "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/FxLightType",
                "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/FxAnalysisLocation"
              ],
              "title": "Enumerations"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "Unsupported OS: FxPlug"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "typedef"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@NSUInteger",
                    "text": "NSUInteger"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "FxModifierKeys"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.professionalvideoapplications~1documentation~1professional_video_applications~1kFxModifierKey_COMMAND/title",
          "value": "kFxModifierKey_COMMAND"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.professionalvideoapplications~1documentation~1professional_video_applications~1kFxModifierKey_COMMAND/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kFxModifierKey_COMMAND"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.professionalvideoapplications~1documentation~1professional_video_applications~1kFxModifierKey_CAPS_LOCK/title",
          "value": "kFxModifierKey_CAPS_LOCK"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.professionalvideoapplications~1documentation~1professional_video_applications~1kFxModifierKey_CAPS_LOCK/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kFxModifierKey_CAPS_LOCK"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.professionalvideoapplications~1documentation~1professional_video_applications~1kFxModifierKey_SHIFT/title",
          "value": "kFxModifierKey_SHIFT"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.professionalvideoapplications~1documentation~1professional_video_applications~1kFxModifierKey_SHIFT/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kFxModifierKey_SHIFT"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.professionalvideoapplications~1documentation~1professional_video_applications~1FxImageOrigin/title",
          "value": "FxImageOrigin"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.professionalvideoapplications~1documentation~1professional_video_applications~1FxImageOrigin/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "FxImageOrigin"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.professionalvideoapplications~1documentation~1professional_video_applications~1FxImageOrigin/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "FxImageOrigin"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.professionalvideoapplications~1documentation~1professional_video_applications~1FxPixelTransformSupport/title",
          "value": "FxPixelTransformSupport"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.professionalvideoapplications~1documentation~1professional_video_applications~1FxPixelTransformSupport/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "FxPixelTransformSupport"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.professionalvideoapplications~1documentation~1professional_video_applications~1FxPixelTransformSupport/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "FxPixelTransformSupport"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.professionalvideoapplications~1documentation~1professional_video_applications~1kFxModifierKey_OPTION/title",
          "value": "kFxModifierKey_OPTION"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.professionalvideoapplications~1documentation~1professional_video_applications~1kFxModifierKey_OPTION/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kFxModifierKey_OPTION"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.professionalvideoapplications~1documentation~1professional_video_applications~1FxModifierKeys/title",
          "value": "FxModifierKeys"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.professionalvideoapplications~1documentation~1professional_video_applications~1FxModifierKeys/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "FxModifierKeys"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.professionalvideoapplications~1documentation~1professional_video_applications~1FxModifierKeys/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "FxModifierKeys"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.professionalvideoapplications~1documentation~1professional_video_applications~1FxAnalysisLocation/title",
          "value": "FxAnalysisLocation"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.professionalvideoapplications~1documentation~1professional_video_applications~1FxAnalysisLocation/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "FxAnalysisLocation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.professionalvideoapplications~1documentation~1professional_video_applications~1FxAnalysisLocation/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "FxAnalysisLocation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.professionalvideoapplications~1documentation~1professional_video_applications~1FxLightType/title",
          "value": "FxLightType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.professionalvideoapplications~1documentation~1professional_video_applications~1FxLightType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "FxLightType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.professionalvideoapplications~1documentation~1professional_video_applications~1FxLightType/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "FxLightType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.professionalvideoapplications~1documentation~1professional_video_applications~1FxImageColorInfo/title",
          "value": "FxImageColorInfo"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.professionalvideoapplications~1documentation~1professional_video_applications~1FxImageColorInfo/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "FxImageColorInfo"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.professionalvideoapplications~1documentation~1professional_video_applications~1FxImageColorInfo/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "FxImageColorInfo"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.professionalvideoapplications~1documentation~1professional_video_applications~1kFxModifierKey_CONTROL/title",
          "value": "kFxModifierKey_CONTROL"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.professionalvideoapplications~1documentation~1professional_video_applications~1kFxModifierKey_CONTROL/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kFxModifierKey_CONTROL"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/professional_video_applications/fxmodifierkeys"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/professional_video_applications/fxmodifierkeys"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
