{
  "abstract": [
    {
      "text": "The ",
      "type": "text"
    },
    {
      "code": "FxOnScreenControlAPI",
      "type": "codeVoice"
    },
    {
      "text": " protocol defines the methods the host application uses to draw controls and other user interface elements directly on the canvas where the user has applied the plug-in.",
      "type": "text"
    }
  ],
  "diffAvailability": {
    "major": {
      "change": "added",
      "platform": "FxPlug",
      "versions": [
        "4.0",
        "4.2.9"
      ]
    }
  },
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/FxOnScreenControlAPI"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(pl)FxOnScreenControlAPI",
    "fragments": [
      {
        "kind": "keyword",
        "text": "protocol"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "FxOnScreenControlAPI"
      }
    ],
    "modules": [
      {
        "name": "Professional Video Applications"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "FxOnScreenControlAPI"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "introducedAt": "3.1",
        "name": "FxPlug"
      }
    ],
    "role": "symbol",
    "roleHeading": "Protocol",
    "symbolKind": "protocol",
    "title": "FxOnScreenControlAPI"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "Unsupported OS: FxPlug"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "protocol"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "FxOnScreenControlAPI"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "kind": "mentions",
      "mentions": [
        "doc://com.apple.professionalvideoapplications/documentation/Professional-Video-Applications/adding-onscreen-controls-to-plug-ins"
      ]
    },
    {
      "content": [
        {
          "anchor": "overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Plug-ins use protocol to direct manipulation of the object and is an intuitive means for users to interact with a plug-in.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "Use this API to transform points from the drawing space of the canvas or document to the pixel space of the object the user wants to manipulate, and vice-versa.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.professionalvideoapplications/documentation/Professional-Video-Applications/adding-onscreen-controls-to-plug-ins": {
      "abstract": [
        {
          "text": "Simplify user interaction by using onscreen controls for your FxPlug plug-in.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.professionalvideoapplications/documentation/Professional-Video-Applications/adding-onscreen-controls-to-plug-ins",
      "kind": "article",
      "role": "article",
      "title": "Adding onscreen controls to plug-ins",
      "type": "topic",
      "url": "/documentation/professional-video-applications/adding-onscreen-controls-to-plug-ins"
    },
    "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications": {
      "abstract": [
        {
          "text": "Exchange data with Final Cut Pro, and create effects plug-ins for Final Cut Pro and Motion.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications",
      "kind": "symbol",
      "role": "collection",
      "title": "Professional Video Applications",
      "type": "topic",
      "url": "/documentation/professional_video_applications"
    },
    "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/FxOnScreenControlAPI": {
      "abstract": [
        {
          "text": "The ",
          "type": "text"
        },
        {
          "code": "FxOnScreenControlAPI",
          "type": "codeVoice"
        },
        {
          "text": " protocol defines the methods the host application uses to draw controls and other user interface elements directly on the canvas where the user has applied the plug-in.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "FxOnScreenControlAPI"
        }
      ],
      "identifier": "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/FxOnScreenControlAPI",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "FxOnScreenControlAPI"
        }
      ],
      "role": "symbol",
      "title": "FxOnScreenControlAPI",
      "type": "topic",
      "url": "/documentation/professional_video_applications/fxonscreencontrolapi"
    },
    "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/FxOnScreenControlAPI/convertPoint(fromSpace:fromX:fromY:toSpace:toX:toY:)": {
      "abstract": [
        {
          "text": "Converts a position from object space to canvas space.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "convertPoint"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "fromSpace"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@FxDrawingCoordinates",
          "text": "FxDrawingCoordinates"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "fromX"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sd",
          "text": "Double"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "fromY"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sd",
          "text": "Double"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "toSpace"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@FxDrawingCoordinates",
          "text": "FxDrawingCoordinates"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "toX"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sp",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sd",
          "text": "Double"
        },
        {
          "kind": "text",
          "text": ">!, "
        },
        {
          "kind": "externalParam",
          "text": "toY"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sp",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sd",
          "text": "Double"
        },
        {
          "kind": "text",
          "text": ">!)"
        }
      ],
      "identifier": "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/FxOnScreenControlAPI/convertPoint(fromSpace:fromX:fromY:toSpace:toX:toY:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "convertPointFromSpace:fromX:fromY:toSpace:toX:toY:"
        }
      ],
      "required": true,
      "role": "symbol",
      "title": "convertPoint(fromSpace:fromX:fromY:toSpace:toX:toY:)",
      "type": "topic",
      "url": "/documentation/professional_video_applications/fxonscreencontrolapi/convertpoint(fromspace:fromx:fromy:tospace:tox:toy:)"
    },
    "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/FxOnScreenControlAPI_v2": {
      "abstract": [
        {
          "text": "The ",
          "type": "text"
        },
        {
          "code": "FxOnScreenControlAPI_v2",
          "type": "codeVoice"
        },
        {
          "text": " protocol specifies additions to the ",
          "type": "text"
        },
        {
          "code": "FxOnScreenControlAPI",
          "type": "codeVoice"
        },
        {
          "text": " protocol which defines the methods the host application provides to manage conversions between various on-screen coordinate spaces.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "FxOnScreenControlAPI_v2"
        }
      ],
      "identifier": "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/FxOnScreenControlAPI_v2",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "FxOnScreenControlAPI_v2"
        }
      ],
      "role": "symbol",
      "title": "FxOnScreenControlAPI_v2",
      "type": "topic",
      "url": "/documentation/professional_video_applications/fxonscreencontrolapi_v2"
    },
    "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/FxOnScreenControlAPI_v3": {
      "abstract": [
        {
          "text": "The ",
          "type": "text"
        },
        {
          "code": "FxOnScreenControlAPI_v3",
          "type": "codeVoice"
        },
        {
          "text": " protocol specifies additions to the ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/FxOnScreenControlAPI",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " protocol which defines the methods the host application provides to manage conversions between various on-screen coordinate spaces.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "FxOnScreenControlAPI_v3"
        }
      ],
      "identifier": "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/FxOnScreenControlAPI_v3",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "FxOnScreenControlAPI_v3"
        }
      ],
      "role": "symbol",
      "title": "FxOnScreenControlAPI_v3",
      "type": "topic",
      "url": "/documentation/professional_video_applications/fxonscreencontrolapi_v3"
    },
    "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/FxOnScreenControlAPI_v4": {
      "abstract": [
        {
          "text": "The ",
          "type": "text"
        },
        {
          "code": "FxOnScreenControlAPI_v4",
          "type": "codeVoice"
        },
        {
          "text": " protocol specifies additions to the ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/FxOnScreenControlAPI",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " protocol which defines the methods the host application provides to manage conversions between various on-screen coordinate spaces.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "FxOnScreenControlAPI_v4"
        }
      ],
      "identifier": "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/FxOnScreenControlAPI_v4",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "FxOnScreenControlAPI_v4"
        }
      ],
      "role": "symbol",
      "title": "FxOnScreenControlAPI_v4",
      "type": "topic",
      "url": "/documentation/professional_video_applications/fxonscreencontrolapi_v4"
    },
    "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/FxOnScreenControl_v4": {
      "abstract": [
        {
          "text": "Defines the methods a plug-in must implement to create parameter controls.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "FxOnScreenControl_v4"
        }
      ],
      "identifier": "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/FxOnScreenControl_v4",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "FxOnScreenControl_v4"
        }
      ],
      "role": "symbol",
      "title": "FxOnScreenControl_v4",
      "type": "topic",
      "url": "/documentation/professional_video_applications/fxonscreencontrol_v4"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/FxOnScreenControlAPI_v2",
        "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/FxOnScreenControlAPI_v3",
        "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/FxOnScreenControlAPI_v4"
      ],
      "kind": "relationships",
      "title": "Inherited By",
      "type": "inheritedBy"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Onscreen-Control-APIs",
      "generated": true,
      "identifiers": [
        "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/FxOnScreenControl_v4",
        "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/FxOnScreenControlAPI_v2",
        "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/FxOnScreenControlAPI_v3",
        "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/FxOnScreenControlAPI_v4"
      ],
      "title": "Onscreen Control APIs"
    }
  ],
  "topicSections": [
    {
      "anchor": "Converting-Points-Between-Coordinate-Spaces",
      "identifiers": [
        "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/FxOnScreenControlAPI/convertPoint(fromSpace:fromX:fromY:toSpace:toX:toY:)"
      ],
      "title": "Converting Points Between Coordinate Spaces"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": null
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Protocol"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "FxOnScreenControlAPI"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "protocol"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "FxOnScreenControlAPI"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "FxOnScreenControlAPI"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Converting-Points-Between-Coordinate-Spaces",
              "identifiers": [
                "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/FxOnScreenControlAPI/convertPoint(fromSpace:fromX:fromY:toSpace:toX:toY:)"
              ],
              "title": "Converting Points Between Coordinate Spaces"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": [
            {
              "identifiers": [
                "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/FxOnScreenControlAPI_v2"
              ],
              "kind": "relationships",
              "title": "Inherited By",
              "type": "inheritedBy"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Onscreen-Control-APIs",
              "generated": true,
              "identifiers": [
                "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/FxOnScreenControl_v4",
                "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/FxOnScreenControlAPI_v2",
                "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/FxOnScreenControlAPI_v3",
                "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/FxOnScreenControlAPI_v4"
              ],
              "title": "Onscreen Control APIs"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "Unsupported OS: FxPlug"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "@protocol"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "FxOnScreenControlAPI"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.professionalvideoapplications~1documentation~1professional_video_applications~1FxOnScreenControlAPI_v4/title",
          "value": "FxOnScreenControlAPI_v4"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.professionalvideoapplications~1documentation~1professional_video_applications~1FxOnScreenControlAPI_v4/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "FxOnScreenControlAPI_v4"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.professionalvideoapplications~1documentation~1professional_video_applications~1FxOnScreenControlAPI_v4/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "FxOnScreenControlAPI_v4"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.professionalvideoapplications~1documentation~1professional_video_applications~1FxOnScreenControlAPI~1convertPoint(fromSpace:fromX:fromY:toSpace:toX:toY:)/title",
          "value": "convertPointFromSpace:fromX:fromY:toSpace:toX:toY:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.professionalvideoapplications~1documentation~1professional_video_applications~1FxOnScreenControlAPI~1convertPoint(fromSpace:fromX:fromY:toSpace:toX:toY:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "convertPointFromSpace:fromX:fromY:toSpace:toX:toY:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.professionalvideoapplications~1documentation~1professional_video_applications~1FxOnScreenControlAPI_v3/title",
          "value": "FxOnScreenControlAPI_v3"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.professionalvideoapplications~1documentation~1professional_video_applications~1FxOnScreenControlAPI_v3/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "FxOnScreenControlAPI_v3"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.professionalvideoapplications~1documentation~1professional_video_applications~1FxOnScreenControlAPI_v3/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "FxOnScreenControlAPI_v3"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.professionalvideoapplications~1documentation~1professional_video_applications~1FxOnScreenControlAPI_v2/title",
          "value": "FxOnScreenControlAPI_v2"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.professionalvideoapplications~1documentation~1professional_video_applications~1FxOnScreenControlAPI_v2/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "FxOnScreenControlAPI_v2"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.professionalvideoapplications~1documentation~1professional_video_applications~1FxOnScreenControlAPI_v2/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "FxOnScreenControlAPI_v2"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.professionalvideoapplications~1documentation~1professional_video_applications~1FxOnScreenControl_v4/title",
          "value": "FxOnScreenControl_v4"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.professionalvideoapplications~1documentation~1professional_video_applications~1FxOnScreenControl_v4/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "FxOnScreenControl_v4"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.professionalvideoapplications~1documentation~1professional_video_applications~1FxOnScreenControl_v4/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "FxOnScreenControl_v4"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.professionalvideoapplications~1documentation~1professional_video_applications~1FxOnScreenControlAPI/title",
          "value": "FxOnScreenControlAPI"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.professionalvideoapplications~1documentation~1professional_video_applications~1FxOnScreenControlAPI/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "FxOnScreenControlAPI"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.professionalvideoapplications~1documentation~1professional_video_applications~1FxOnScreenControlAPI/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "FxOnScreenControlAPI"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/professional_video_applications/fxonscreencontrolapi"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/professional_video_applications/fxonscreencontrolapi"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
