{
  "abstract": [
    {
      "text": "Defines the functions the application provides to set parameter values.",
      "type": "text"
    }
  ],
  "diffAvailability": {
    "major": {
      "change": "added",
      "platform": "FxPlug",
      "versions": [
        "4.0",
        "4.2.9"
      ]
    }
  },
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/FxParameterSettingAPI_v5"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(pl)FxParameterSettingAPI_v5",
    "fragments": [
      {
        "kind": "keyword",
        "text": "protocol"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "FxParameterSettingAPI_v5"
      }
    ],
    "modules": [
      {
        "name": "Professional Video Applications"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "FxParameterSettingAPI_v5"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "introducedAt": "4.0",
        "name": "FxPlug"
      }
    ],
    "role": "symbol",
    "roleHeading": "Protocol",
    "symbolKind": "protocol",
    "title": "FxParameterSettingAPI_v5"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "Unsupported OS: FxPlug"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "protocol"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "FxParameterSettingAPI_v5"
            },
            {
              "kind": "text",
              "text": " : "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSObject",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(pl)NSObject",
              "text": "NSObjectProtocol"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "kind": "mentions",
      "mentions": [
        "doc://com.apple.professionalvideoapplications/documentation/Professional-Video-Applications/analyzing-media"
      ]
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.professionalvideoapplications/documentation/Professional-Video-Applications/analyzing-media": {
      "abstract": [
        {
          "text": "Use the FxPlug analysis API to analyze frames of source media before rendering them.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.professionalvideoapplications/documentation/Professional-Video-Applications/analyzing-media",
      "kind": "article",
      "role": "article",
      "title": "Analyzing media",
      "type": "topic",
      "url": "/documentation/professional-video-applications/analyzing-media"
    },
    "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications": {
      "abstract": [
        {
          "text": "Exchange data with Final Cut Pro, and create effects plug-ins for Final Cut Pro and Motion.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications",
      "kind": "symbol",
      "role": "collection",
      "title": "Professional Video Applications",
      "type": "topic",
      "url": "/documentation/professional_video_applications"
    },
    "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/FxDynamicParameterAPI_v3": {
      "abstract": [
        {
          "text": "Allows your plugin to create parameters on-the-fly.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "FxDynamicParameterAPI_v3"
        }
      ],
      "identifier": "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/FxDynamicParameterAPI_v3",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "FxDynamicParameterAPI_v3"
        }
      ],
      "role": "symbol",
      "title": "FxDynamicParameterAPI_v3",
      "type": "topic",
      "url": "/documentation/professional_video_applications/fxdynamicparameterapi_v3"
    },
    "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/FxParameterCreationAPI_v5": {
      "abstract": [
        {
          "text": "Defines the methods provided by the host application to create parameters.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "FxParameterCreationAPI_v5"
        }
      ],
      "identifier": "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/FxParameterCreationAPI_v5",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "FxParameterCreationAPI_v5"
        }
      ],
      "role": "symbol",
      "title": "FxParameterCreationAPI_v5",
      "type": "topic",
      "url": "/documentation/professional_video_applications/fxparametercreationapi_v5"
    },
    "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/FxParameterRetrievalAPI_v6": {
      "abstract": [
        {
          "text": "Defines the functions the application provides to retrieve parameter values.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "FxParameterRetrievalAPI_v6"
        }
      ],
      "identifier": "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/FxParameterRetrievalAPI_v6",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "FxParameterRetrievalAPI_v6"
        }
      ],
      "role": "symbol",
      "title": "FxParameterRetrievalAPI_v6",
      "type": "topic",
      "url": "/documentation/professional_video_applications/fxparameterretrievalapi_v6"
    },
    "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/FxParameterRetrievalAPI_v7": {
      "abstract": [
        {
          "text": "Adds a method to retrieve the image information about an image parameter.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "FxParameterRetrievalAPI_v7"
        }
      ],
      "identifier": "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/FxParameterRetrievalAPI_v7",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "FxParameterRetrievalAPI_v7"
        }
      ],
      "role": "symbol",
      "title": "FxParameterRetrievalAPI_v7",
      "type": "topic",
      "url": "/documentation/professional_video_applications/fxparameterretrievalapi_v7"
    },
    "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/FxParameterSettingAPI_v5": {
      "abstract": [
        {
          "text": "Defines the functions the application provides to set parameter values.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "FxParameterSettingAPI_v5"
        }
      ],
      "identifier": "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/FxParameterSettingAPI_v5",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "FxParameterSettingAPI_v5"
        }
      ],
      "role": "symbol",
      "title": "FxParameterSettingAPI_v5",
      "type": "topic",
      "url": "/documentation/professional_video_applications/fxparametersettingapi_v5"
    },
    "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/FxParameterSettingAPI_v5/setBoolValue(_:toParameter:at:)": {
      "abstract": [
        {
          "text": "Sets the value of a Boolean parameter.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "setBoolValue"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "toParameter"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "at"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@SA@CMTime",
          "text": "CMTime"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/FxParameterSettingAPI_v5/setBoolValue(_:toParameter:at:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "setBoolValue:toParameter:atTime:"
        }
      ],
      "required": true,
      "role": "symbol",
      "title": "setBoolValue(_:toParameter:at:)",
      "type": "topic",
      "url": "/documentation/professional_video_applications/fxparametersettingapi_v5/setboolvalue(_:toparameter:at:)"
    },
    "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/FxParameterSettingAPI_v5/setCustomParameterValue(_:toParameter:at:)": {
      "abstract": [
        {
          "text": "Sets a custom value for a custom parameter.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "setCustomParameterValue"
        },
        {
          "kind": "text",
          "text": "(any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(pl)NSCopying",
          "text": "NSCopying"
        },
        {
          "kind": "text",
          "text": " & "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(pl)NSSecureCoding",
          "text": "NSSecureCoding"
        },
        {
          "kind": "text",
          "text": " & "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(pl)NSObject",
          "text": "NSObjectProtocol"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "toParameter"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "at"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@SA@CMTime",
          "text": "CMTime"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/FxParameterSettingAPI_v5/setCustomParameterValue(_:toParameter:at:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "setCustomParameterValue:toParameter:atTime:"
        }
      ],
      "required": true,
      "role": "symbol",
      "title": "setCustomParameterValue(_:toParameter:at:)",
      "type": "topic",
      "url": "/documentation/professional_video_applications/fxparametersettingapi_v5/setcustomparametervalue(_:toparameter:at:)"
    },
    "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/FxParameterSettingAPI_v5/setFloatValue(_:toParameter:at:)": {
      "abstract": [
        {
          "text": "Sets the value of a floating point parameter.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "setFloatValue"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sd",
          "text": "Double"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "toParameter"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "at"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@SA@CMTime",
          "text": "CMTime"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/FxParameterSettingAPI_v5/setFloatValue(_:toParameter:at:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "setFloatValue:toParameter:atTime:"
        }
      ],
      "required": true,
      "role": "symbol",
      "title": "setFloatValue(_:toParameter:at:)",
      "type": "topic",
      "url": "/documentation/professional_video_applications/fxparametersettingapi_v5/setfloatvalue(_:toparameter:at:)"
    },
    "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/FxParameterSettingAPI_v5/setHistogramBlackIn(_:blackOut:whiteIn:whiteOut:gamma:forChannel:fromParameter:at:)": {
      "abstract": [
        {
          "text": "Sets the values in a histogram parameter group.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "setHistogramBlackIn"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sd",
          "text": "Double"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "blackOut"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sd",
          "text": "Double"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "whiteIn"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sd",
          "text": "Double"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "whiteOut"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sd",
          "text": "Double"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "gamma"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sd",
          "text": "Double"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "forChannel"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@FxHistogramChannel",
          "text": "FxHistogramChannel"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "fromParameter"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "at"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@SA@CMTime",
          "text": "CMTime"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/FxParameterSettingAPI_v5/setHistogramBlackIn(_:blackOut:whiteIn:whiteOut:gamma:forChannel:fromParameter:at:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "setHistogramBlackIn:blackOut:whiteIn:whiteOut:gamma:forChannel:fromParameter:atTime:"
        }
      ],
      "required": true,
      "role": "symbol",
      "title": "setHistogramBlackIn(_:blackOut:whiteIn:whiteOut:gamma:forChannel:fromParameter:at:)",
      "type": "topic",
      "url": "/documentation/professional_video_applications/fxparametersettingapi_v5/sethistogramblackin(_:blackout:whitein:whiteout:gamma:forchannel:fromparameter:at:)"
    },
    "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/FxParameterSettingAPI_v5/setIntValue(_:toParameter:at:)": {
      "abstract": [
        {
          "text": "Sets the value of an integer parameter.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "setIntValue"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int32V",
          "text": "Int32"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "toParameter"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "at"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@SA@CMTime",
          "text": "CMTime"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/FxParameterSettingAPI_v5/setIntValue(_:toParameter:at:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "setIntValue:toParameter:atTime:"
        }
      ],
      "required": true,
      "role": "symbol",
      "title": "setIntValue(_:toParameter:at:)",
      "type": "topic",
      "url": "/documentation/professional_video_applications/fxparametersettingapi_v5/setintvalue(_:toparameter:at:)"
    },
    "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/FxParameterSettingAPI_v5/setParameterFlags(_:toParameter:)": {
      "abstract": [
        {
          "text": "Sets the flags for the state of a parameter.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "setParameterFlags"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@FxParameterFlags",
          "text": "FxParameterFlags"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "toParameter"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/FxParameterSettingAPI_v5/setParameterFlags(_:toParameter:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "setParameterFlags:toParameter:"
        }
      ],
      "required": true,
      "role": "symbol",
      "title": "setParameterFlags(_:toParameter:)",
      "type": "topic",
      "url": "/documentation/professional_video_applications/fxparametersettingapi_v5/setparameterflags(_:toparameter:)"
    },
    "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/FxParameterSettingAPI_v5/setPathID(_:toParameter:at:)": {
      "abstract": [
        {
          "text": "Sets a custom value for a custom parameter.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "setPathID"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@FxPathID",
          "text": "FxPathID"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "toParameter"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "at"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@SA@CMTime",
          "text": "CMTime"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/FxParameterSettingAPI_v5/setPathID(_:toParameter:at:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "setPathID:toParameter:atTime:"
        }
      ],
      "required": true,
      "role": "symbol",
      "title": "setPathID(_:toParameter:at:)",
      "type": "topic",
      "url": "/documentation/professional_video_applications/fxparametersettingapi_v5/setpathid(_:toparameter:at:)"
    },
    "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/FxParameterSettingAPI_v5/setRedValue(_:greenValue:blueValue:alphaValue:toParameter:at:)": {
      "abstract": [
        {
          "text": "Sets the value of an RGBA color parameter.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "setRedValue"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sd",
          "text": "Double"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "greenValue"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sd",
          "text": "Double"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "blueValue"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sd",
          "text": "Double"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "alphaValue"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sd",
          "text": "Double"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "toParameter"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "at"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@SA@CMTime",
          "text": "CMTime"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/FxParameterSettingAPI_v5/setRedValue(_:greenValue:blueValue:alphaValue:toParameter:at:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "setRedValue:greenValue:blueValue:alphaValue:toParameter:atTime:"
        }
      ],
      "required": true,
      "role": "symbol",
      "title": "setRedValue(_:greenValue:blueValue:alphaValue:toParameter:at:)",
      "type": "topic",
      "url": "/documentation/professional_video_applications/fxparametersettingapi_v5/setredvalue(_:greenvalue:bluevalue:alphavalue:toparameter:at:)"
    },
    "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/FxParameterSettingAPI_v5/setRedValue(_:greenValue:blueValue:toParameter:at:)": {
      "abstract": [
        {
          "text": "Set the values of an RGB color parameter.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "setRedValue"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sd",
          "text": "Double"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "greenValue"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sd",
          "text": "Double"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "blueValue"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sd",
          "text": "Double"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "toParameter"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "at"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@SA@CMTime",
          "text": "CMTime"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/FxParameterSettingAPI_v5/setRedValue(_:greenValue:blueValue:toParameter:at:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "setRedValue:greenValue:blueValue:toParameter:atTime:"
        }
      ],
      "required": true,
      "role": "symbol",
      "title": "setRedValue(_:greenValue:blueValue:toParameter:at:)",
      "type": "topic",
      "url": "/documentation/professional_video_applications/fxparametersettingapi_v5/setredvalue(_:greenvalue:bluevalue:toparameter:at:)"
    },
    "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/FxParameterSettingAPI_v5/setStringParameterValue(_:toParameter:)": {
      "abstract": [
        {
          "text": "Sets a string value for a string parameter.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "setStringParameterValue"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "toParameter"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/FxParameterSettingAPI_v5/setStringParameterValue(_:toParameter:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "setStringParameterValue:toParameter:"
        }
      ],
      "required": true,
      "role": "symbol",
      "title": "setStringParameterValue(_:toParameter:)",
      "type": "topic",
      "url": "/documentation/professional_video_applications/fxparametersettingapi_v5/setstringparametervalue(_:toparameter:)"
    },
    "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/FxParameterSettingAPI_v5/setXValue(_:yValue:toParameter:at:)": {
      "abstract": [
        {
          "text": "Sets the xy values for a position parameter.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "setXValue"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sd",
          "text": "Double"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "yValue"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sd",
          "text": "Double"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "toParameter"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "at"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@SA@CMTime",
          "text": "CMTime"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/FxParameterSettingAPI_v5/setXValue(_:yValue:toParameter:at:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "setXValue:YValue:toParameter:atTime:"
        }
      ],
      "required": true,
      "role": "symbol",
      "title": "setXValue(_:yValue:toParameter:at:)",
      "type": "topic",
      "url": "/documentation/professional_video_applications/fxparametersettingapi_v5/setxvalue(_:yvalue:toparameter:at:)"
    },
    "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/FxParameterSettingAPI_v6": {
      "abstract": [
        {
          "text": "Defines the functions the application provides to set parameter flags.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "FxParameterSettingAPI_v6"
        }
      ],
      "identifier": "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/FxParameterSettingAPI_v6",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "FxParameterSettingAPI_v6"
        }
      ],
      "role": "symbol",
      "title": "FxParameterSettingAPI_v6",
      "type": "topic",
      "url": "/documentation/professional_video_applications/fxparametersettingapi_v6"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)NSObject": {
      "abstract": [
        {
          "text": "The group of methods that are fundamental to all Objective-C objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "protocol "
        },
        {
          "kind": "identifier",
          "text": "NSObjectProtocol"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSObject",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSObjectProtocol",
      "type": "topic",
      "url": "/documentation/objectivec/nsobjectprotocol"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/c:objc(pl)NSObject"
      ],
      "kind": "relationships",
      "title": "Inherits From",
      "type": "inheritsFrom"
    },
    {
      "identifiers": [
        "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/FxParameterSettingAPI_v6"
      ],
      "kind": "relationships",
      "title": "Inherited By",
      "type": "inheritedBy"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Parameter-APIs",
      "generated": true,
      "identifiers": [
        "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/FxParameterCreationAPI_v5",
        "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/FxParameterRetrievalAPI_v6",
        "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/FxParameterRetrievalAPI_v7",
        "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/FxParameterSettingAPI_v6",
        "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/FxDynamicParameterAPI_v3"
      ],
      "title": "Parameter APIs"
    }
  ],
  "topicSections": [
    {
      "anchor": "Instance-Methods",
      "identifiers": [
        "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/FxParameterSettingAPI_v5/setBoolValue(_:toParameter:at:)",
        "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/FxParameterSettingAPI_v5/setCustomParameterValue(_:toParameter:at:)",
        "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/FxParameterSettingAPI_v5/setFloatValue(_:toParameter:at:)",
        "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/FxParameterSettingAPI_v5/setHistogramBlackIn(_:blackOut:whiteIn:whiteOut:gamma:forChannel:fromParameter:at:)",
        "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/FxParameterSettingAPI_v5/setIntValue(_:toParameter:at:)",
        "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/FxParameterSettingAPI_v5/setParameterFlags(_:toParameter:)",
        "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/FxParameterSettingAPI_v5/setPathID(_:toParameter:at:)",
        "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/FxParameterSettingAPI_v5/setRedValue(_:greenValue:blueValue:alphaValue:toParameter:at:)",
        "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/FxParameterSettingAPI_v5/setRedValue(_:greenValue:blueValue:toParameter:at:)",
        "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/FxParameterSettingAPI_v5/setStringParameterValue(_:toParameter:)",
        "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/FxParameterSettingAPI_v5/setXValue(_:yValue:toParameter:at:)"
      ],
      "title": "Instance Methods"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": null
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Protocol"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "FxParameterSettingAPI_v5"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "protocol"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "FxParameterSettingAPI_v5"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "FxParameterSettingAPI_v5"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Instance-Methods",
              "identifiers": [
                "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/FxParameterSettingAPI_v5/setBoolValue(_:toParameter:at:)",
                "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/FxParameterSettingAPI_v5/setCustomParameterValue(_:toParameter:at:)",
                "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/FxParameterSettingAPI_v5/setFloatValue(_:toParameter:at:)",
                "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/FxParameterSettingAPI_v5/setHistogramBlackIn(_:blackOut:whiteIn:whiteOut:gamma:forChannel:fromParameter:at:)",
                "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/FxParameterSettingAPI_v5/setIntValue(_:toParameter:at:)",
                "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/FxParameterSettingAPI_v5/setParameterFlags(_:toParameter:)",
                "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/FxParameterSettingAPI_v5/setPathID(_:toParameter:at:)",
                "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/FxParameterSettingAPI_v5/setRedValue(_:greenValue:blueValue:alphaValue:toParameter:at:)",
                "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/FxParameterSettingAPI_v5/setRedValue(_:greenValue:blueValue:toParameter:at:)",
                "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/FxParameterSettingAPI_v5/setStringParameterValue(_:toParameter:)",
                "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/FxParameterSettingAPI_v5/setXValue(_:yValue:toParameter:at:)"
              ],
              "title": "Instance Methods"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": [
            {
              "identifiers": [
                "doc://com.externally.resolved.symbol/c:objc(pl)NSObject"
              ],
              "kind": "relationships",
              "title": "Inherits From",
              "type": "inheritsFrom"
            },
            {
              "identifiers": [
                "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/FxParameterSettingAPI_v6"
              ],
              "kind": "relationships",
              "title": "Inherited By",
              "type": "inheritedBy"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Parameter-APIs",
              "generated": true,
              "identifiers": [
                "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/FxParameterCreationAPI_v5",
                "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/FxParameterRetrievalAPI_v6",
                "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/FxParameterRetrievalAPI_v7",
                "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/FxParameterSettingAPI_v6",
                "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/FxDynamicParameterAPI_v3"
              ],
              "title": "Parameter APIs"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "Unsupported OS: FxPlug"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "@protocol"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "FxParameterSettingAPI_v5"
                  },
                  {
                    "kind": "text",
                    "text": " <"
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSObject",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(pl)NSObject",
                    "text": "NSObject"
                  },
                  {
                    "kind": "text",
                    "text": ">"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.professionalvideoapplications~1documentation~1professional_video_applications~1FxParameterSettingAPI_v5~1setParameterFlags(_:toParameter:)/title",
          "value": "setParameterFlags:toParameter:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.professionalvideoapplications~1documentation~1professional_video_applications~1FxParameterSettingAPI_v5~1setParameterFlags(_:toParameter:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "setParameterFlags:toParameter:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.professionalvideoapplications~1documentation~1professional_video_applications~1FxParameterSettingAPI_v5/title",
          "value": "FxParameterSettingAPI_v5"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.professionalvideoapplications~1documentation~1professional_video_applications~1FxParameterSettingAPI_v5/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "FxParameterSettingAPI_v5"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.professionalvideoapplications~1documentation~1professional_video_applications~1FxParameterSettingAPI_v5/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "FxParameterSettingAPI_v5"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.professionalvideoapplications~1documentation~1professional_video_applications~1FxParameterSettingAPI_v5~1setFloatValue(_:toParameter:at:)/title",
          "value": "setFloatValue:toParameter:atTime:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.professionalvideoapplications~1documentation~1professional_video_applications~1FxParameterSettingAPI_v5~1setFloatValue(_:toParameter:at:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "setFloatValue:toParameter:atTime:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.professionalvideoapplications~1documentation~1professional_video_applications~1FxParameterSettingAPI_v5~1setStringParameterValue(_:toParameter:)/title",
          "value": "setStringParameterValue:toParameter:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.professionalvideoapplications~1documentation~1professional_video_applications~1FxParameterSettingAPI_v5~1setStringParameterValue(_:toParameter:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "setStringParameterValue:toParameter:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.professionalvideoapplications~1documentation~1professional_video_applications~1FxDynamicParameterAPI_v3/title",
          "value": "FxDynamicParameterAPI_v3"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.professionalvideoapplications~1documentation~1professional_video_applications~1FxDynamicParameterAPI_v3/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "FxDynamicParameterAPI_v3"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.professionalvideoapplications~1documentation~1professional_video_applications~1FxDynamicParameterAPI_v3/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "FxDynamicParameterAPI_v3"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.professionalvideoapplications~1documentation~1professional_video_applications~1FxParameterSettingAPI_v5~1setIntValue(_:toParameter:at:)/title",
          "value": "setIntValue:toParameter:atTime:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.professionalvideoapplications~1documentation~1professional_video_applications~1FxParameterSettingAPI_v5~1setIntValue(_:toParameter:at:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "setIntValue:toParameter:atTime:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.professionalvideoapplications~1documentation~1professional_video_applications~1FxParameterSettingAPI_v5~1setCustomParameterValue(_:toParameter:at:)/title",
          "value": "setCustomParameterValue:toParameter:atTime:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.professionalvideoapplications~1documentation~1professional_video_applications~1FxParameterSettingAPI_v5~1setCustomParameterValue(_:toParameter:at:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "setCustomParameterValue:toParameter:atTime:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.professionalvideoapplications~1documentation~1professional_video_applications~1FxParameterRetrievalAPI_v6/title",
          "value": "FxParameterRetrievalAPI_v6"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.professionalvideoapplications~1documentation~1professional_video_applications~1FxParameterRetrievalAPI_v6/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "FxParameterRetrievalAPI_v6"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.professionalvideoapplications~1documentation~1professional_video_applications~1FxParameterRetrievalAPI_v6/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "FxParameterRetrievalAPI_v6"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.professionalvideoapplications~1documentation~1professional_video_applications~1FxParameterSettingAPI_v5~1setRedValue(_:greenValue:blueValue:toParameter:at:)/title",
          "value": "setRedValue:greenValue:blueValue:toParameter:atTime:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.professionalvideoapplications~1documentation~1professional_video_applications~1FxParameterSettingAPI_v5~1setRedValue(_:greenValue:blueValue:toParameter:at:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "setRedValue:greenValue:blueValue:toParameter:atTime:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.professionalvideoapplications~1documentation~1professional_video_applications~1FxParameterSettingAPI_v6/title",
          "value": "FxParameterSettingAPI_v6"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.professionalvideoapplications~1documentation~1professional_video_applications~1FxParameterSettingAPI_v6/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "FxParameterSettingAPI_v6"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.professionalvideoapplications~1documentation~1professional_video_applications~1FxParameterSettingAPI_v6/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "FxParameterSettingAPI_v6"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:objc(pl)NSObject/title",
          "value": "NSObject"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.professionalvideoapplications~1documentation~1professional_video_applications~1FxParameterSettingAPI_v5~1setHistogramBlackIn(_:blackOut:whiteIn:whiteOut:gamma:forChannel:fromParameter:at:)/title",
          "value": "setHistogramBlackIn:blackOut:whiteIn:whiteOut:gamma:forChannel:fromParameter:atTime:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.professionalvideoapplications~1documentation~1professional_video_applications~1FxParameterSettingAPI_v5~1setHistogramBlackIn(_:blackOut:whiteIn:whiteOut:gamma:forChannel:fromParameter:at:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "setHistogramBlackIn:blackOut:whiteIn:whiteOut:gamma:forChannel:fromParameter:atTime:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.professionalvideoapplications~1documentation~1professional_video_applications~1FxParameterSettingAPI_v5~1setRedValue(_:greenValue:blueValue:alphaValue:toParameter:at:)/title",
          "value": "setRedValue:greenValue:blueValue:alphaValue:toParameter:atTime:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.professionalvideoapplications~1documentation~1professional_video_applications~1FxParameterSettingAPI_v5~1setRedValue(_:greenValue:blueValue:alphaValue:toParameter:at:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "setRedValue:greenValue:blueValue:alphaValue:toParameter:atTime:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.professionalvideoapplications~1documentation~1professional_video_applications~1FxParameterSettingAPI_v5~1setBoolValue(_:toParameter:at:)/title",
          "value": "setBoolValue:toParameter:atTime:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.professionalvideoapplications~1documentation~1professional_video_applications~1FxParameterSettingAPI_v5~1setBoolValue(_:toParameter:at:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "setBoolValue:toParameter:atTime:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.professionalvideoapplications~1documentation~1professional_video_applications~1FxParameterRetrievalAPI_v7/title",
          "value": "FxParameterRetrievalAPI_v7"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.professionalvideoapplications~1documentation~1professional_video_applications~1FxParameterRetrievalAPI_v7/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "FxParameterRetrievalAPI_v7"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.professionalvideoapplications~1documentation~1professional_video_applications~1FxParameterRetrievalAPI_v7/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "FxParameterRetrievalAPI_v7"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.professionalvideoapplications~1documentation~1professional_video_applications~1FxParameterCreationAPI_v5/title",
          "value": "FxParameterCreationAPI_v5"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.professionalvideoapplications~1documentation~1professional_video_applications~1FxParameterCreationAPI_v5/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "FxParameterCreationAPI_v5"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.professionalvideoapplications~1documentation~1professional_video_applications~1FxParameterCreationAPI_v5/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "FxParameterCreationAPI_v5"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.professionalvideoapplications~1documentation~1professional_video_applications~1FxParameterSettingAPI_v5~1setXValue(_:yValue:toParameter:at:)/title",
          "value": "setXValue:YValue:toParameter:atTime:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.professionalvideoapplications~1documentation~1professional_video_applications~1FxParameterSettingAPI_v5~1setXValue(_:yValue:toParameter:at:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "setXValue:YValue:toParameter:atTime:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.professionalvideoapplications~1documentation~1professional_video_applications~1FxParameterSettingAPI_v5~1setPathID(_:toParameter:at:)/title",
          "value": "setPathID:toParameter:atTime:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.professionalvideoapplications~1documentation~1professional_video_applications~1FxParameterSettingAPI_v5~1setPathID(_:toParameter:at:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "setPathID:toParameter:atTime:"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/professional_video_applications/fxparametersettingapi_v5"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/professional_video_applications/fxparametersettingapi_v5"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
