{
  "abstract": [
    {
      "text": "Adds a method to retrieve the image information about an image parameter.",
      "type": "text"
    }
  ],
  "diffAvailability": {
    "major": {
      "change": "added",
      "platform": "FxPlug",
      "versions": [
        "4.0",
        "4.2.9"
      ]
    }
  },
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/FxParameterRetrievalAPI_v7"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(pl)FxParameterRetrievalAPI_v7",
    "fragments": [
      {
        "kind": "keyword",
        "text": "protocol"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "FxParameterRetrievalAPI_v7"
      }
    ],
    "modules": [
      {
        "name": "Professional Video Applications"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "FxParameterRetrievalAPI_v7"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "introducedAt": "4.2",
        "name": "FxPlug"
      }
    ],
    "role": "symbol",
    "roleHeading": "Protocol",
    "symbolKind": "protocol",
    "title": "FxParameterRetrievalAPI_v7"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "Unsupported OS: FxPlug"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "protocol"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "FxParameterRetrievalAPI_v7"
            },
            {
              "kind": "text",
              "text": " : "
            },
            {
              "identifier": "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/FxParameterRetrievalAPI_v6",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(pl)FxParameterRetrievalAPI_v6",
              "text": "FxParameterRetrievalAPI_v6"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "kind": "mentions",
      "mentions": [
        "doc://com.apple.professionalvideoapplications/documentation/Professional-Video-Applications/managing-color-space-and-gamut-in-plug-ins"
      ]
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.professionalvideoapplications/documentation/Professional-Video-Applications/managing-color-space-and-gamut-in-plug-ins": {
      "abstract": [
        {
          "text": "Control the appearance of your rendering by using the color gamut API.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.professionalvideoapplications/documentation/Professional-Video-Applications/managing-color-space-and-gamut-in-plug-ins",
      "kind": "article",
      "role": "article",
      "title": "Managing color space and gamut in plug-ins",
      "type": "topic",
      "url": "/documentation/professional-video-applications/managing-color-space-and-gamut-in-plug-ins"
    },
    "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications": {
      "abstract": [
        {
          "text": "Exchange data with Final Cut Pro, and create effects plug-ins for Final Cut Pro and Motion.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications",
      "kind": "symbol",
      "role": "collection",
      "title": "Professional Video Applications",
      "type": "topic",
      "url": "/documentation/professional_video_applications"
    },
    "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/FxDynamicParameterAPI_v3": {
      "abstract": [
        {
          "text": "Allows your plugin to create parameters on-the-fly.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "FxDynamicParameterAPI_v3"
        }
      ],
      "identifier": "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/FxDynamicParameterAPI_v3",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "FxDynamicParameterAPI_v3"
        }
      ],
      "role": "symbol",
      "title": "FxDynamicParameterAPI_v3",
      "type": "topic",
      "url": "/documentation/professional_video_applications/fxdynamicparameterapi_v3"
    },
    "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/FxParameterCreationAPI_v5": {
      "abstract": [
        {
          "text": "Defines the methods provided by the host application to create parameters.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "FxParameterCreationAPI_v5"
        }
      ],
      "identifier": "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/FxParameterCreationAPI_v5",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "FxParameterCreationAPI_v5"
        }
      ],
      "role": "symbol",
      "title": "FxParameterCreationAPI_v5",
      "type": "topic",
      "url": "/documentation/professional_video_applications/fxparametercreationapi_v5"
    },
    "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/FxParameterRetrievalAPI_v6": {
      "abstract": [
        {
          "text": "Defines the functions the application provides to retrieve parameter values.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "FxParameterRetrievalAPI_v6"
        }
      ],
      "identifier": "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/FxParameterRetrievalAPI_v6",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "FxParameterRetrievalAPI_v6"
        }
      ],
      "role": "symbol",
      "title": "FxParameterRetrievalAPI_v6",
      "type": "topic",
      "url": "/documentation/professional_video_applications/fxparameterretrievalapi_v6"
    },
    "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/FxParameterRetrievalAPI_v7": {
      "abstract": [
        {
          "text": "Adds a method to retrieve the image information about an image parameter.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "FxParameterRetrievalAPI_v7"
        }
      ],
      "identifier": "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/FxParameterRetrievalAPI_v7",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "FxParameterRetrievalAPI_v7"
        }
      ],
      "role": "symbol",
      "title": "FxParameterRetrievalAPI_v7",
      "type": "topic",
      "url": "/documentation/professional_video_applications/fxparameterretrievalapi_v7"
    },
    "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/FxParameterRetrievalAPI_v7/imageSize(_:fromParameter:at:)": {
      "abstract": [
        {
          "text": "Provides the dimensions of the image well image when it is at 100-percent scale and has square pixels.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "imageSize"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sp",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@CGSize",
          "text": "CGSize"
        },
        {
          "kind": "text",
          "text": ">, "
        },
        {
          "kind": "externalParam",
          "text": "fromParameter"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "at"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@SA@CMTime",
          "text": "CMTime"
        },
        {
          "kind": "text",
          "text": ") "
        },
        {
          "kind": "keyword",
          "text": "throws"
        }
      ],
      "identifier": "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/FxParameterRetrievalAPI_v7/imageSize(_:fromParameter:at:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "imageSize:fromParameter:atTime:error:"
        }
      ],
      "required": true,
      "role": "symbol",
      "title": "imageSize(_:fromParameter:at:)",
      "type": "topic",
      "url": "/documentation/professional_video_applications/fxparameterretrievalapi_v7/imagesize(_:fromparameter:at:)"
    },
    "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/FxParameterSettingAPI_v5": {
      "abstract": [
        {
          "text": "Defines the functions the application provides to set parameter values.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "FxParameterSettingAPI_v5"
        }
      ],
      "identifier": "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/FxParameterSettingAPI_v5",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "FxParameterSettingAPI_v5"
        }
      ],
      "role": "symbol",
      "title": "FxParameterSettingAPI_v5",
      "type": "topic",
      "url": "/documentation/professional_video_applications/fxparametersettingapi_v5"
    },
    "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/FxParameterSettingAPI_v6": {
      "abstract": [
        {
          "text": "Defines the functions the application provides to set parameter flags.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "FxParameterSettingAPI_v6"
        }
      ],
      "identifier": "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/FxParameterSettingAPI_v6",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "FxParameterSettingAPI_v6"
        }
      ],
      "role": "symbol",
      "title": "FxParameterSettingAPI_v6",
      "type": "topic",
      "url": "/documentation/professional_video_applications/fxparametersettingapi_v6"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)NSObject": {
      "abstract": [
        {
          "text": "The group of methods that are fundamental to all Objective-C objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "protocol "
        },
        {
          "kind": "identifier",
          "text": "NSObjectProtocol"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSObject",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSObjectProtocol",
      "type": "topic",
      "url": "/documentation/objectivec/nsobjectprotocol"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/FxParameterRetrievalAPI_v6",
        "doc://com.externally.resolved.symbol/c:objc(pl)NSObject"
      ],
      "kind": "relationships",
      "title": "Inherits From",
      "type": "inheritsFrom"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Parameter-APIs",
      "generated": true,
      "identifiers": [
        "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/FxParameterCreationAPI_v5",
        "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/FxParameterRetrievalAPI_v6",
        "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/FxParameterSettingAPI_v5",
        "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/FxParameterSettingAPI_v6",
        "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/FxDynamicParameterAPI_v3"
      ],
      "title": "Parameter APIs"
    }
  ],
  "topicSections": [
    {
      "anchor": "Instance-Methods",
      "identifiers": [
        "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/FxParameterRetrievalAPI_v7/imageSize(_:fromParameter:at:)"
      ],
      "title": "Instance Methods"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": null
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Protocol"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "FxParameterRetrievalAPI_v7"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "protocol"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "FxParameterRetrievalAPI_v7"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "FxParameterRetrievalAPI_v7"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Instance-Methods",
              "identifiers": [
                "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/FxParameterRetrievalAPI_v7/imageSize(_:fromParameter:at:)"
              ],
              "title": "Instance Methods"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": [
            {
              "identifiers": [
                "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/FxParameterRetrievalAPI_v6"
              ],
              "kind": "relationships",
              "title": "Inherits From",
              "type": "inheritsFrom"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Parameter-APIs",
              "generated": true,
              "identifiers": [
                "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/FxParameterCreationAPI_v5",
                "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/FxParameterRetrievalAPI_v6",
                "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/FxParameterSettingAPI_v5",
                "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/FxParameterSettingAPI_v6",
                "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/FxDynamicParameterAPI_v3"
              ],
              "title": "Parameter APIs"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "Unsupported OS: FxPlug"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "@protocol"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "FxParameterRetrievalAPI_v7"
                  },
                  {
                    "kind": "text",
                    "text": " <"
                  },
                  {
                    "identifier": "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/FxParameterRetrievalAPI_v6",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(pl)FxParameterRetrievalAPI_v6",
                    "text": "FxParameterRetrievalAPI_v6"
                  },
                  {
                    "kind": "text",
                    "text": ">"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.professionalvideoapplications~1documentation~1professional_video_applications~1FxParameterRetrievalAPI_v7~1imageSize(_:fromParameter:at:)/title",
          "value": "imageSize:fromParameter:atTime:error:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.professionalvideoapplications~1documentation~1professional_video_applications~1FxParameterRetrievalAPI_v7~1imageSize(_:fromParameter:at:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "imageSize:fromParameter:atTime:error:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.professionalvideoapplications~1documentation~1professional_video_applications~1FxParameterRetrievalAPI_v6/title",
          "value": "FxParameterRetrievalAPI_v6"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.professionalvideoapplications~1documentation~1professional_video_applications~1FxParameterRetrievalAPI_v6/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "FxParameterRetrievalAPI_v6"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.professionalvideoapplications~1documentation~1professional_video_applications~1FxParameterRetrievalAPI_v6/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "FxParameterRetrievalAPI_v6"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.professionalvideoapplications~1documentation~1professional_video_applications~1FxParameterSettingAPI_v5/title",
          "value": "FxParameterSettingAPI_v5"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.professionalvideoapplications~1documentation~1professional_video_applications~1FxParameterSettingAPI_v5/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "FxParameterSettingAPI_v5"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.professionalvideoapplications~1documentation~1professional_video_applications~1FxParameterSettingAPI_v5/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "FxParameterSettingAPI_v5"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.professionalvideoapplications~1documentation~1professional_video_applications~1FxDynamicParameterAPI_v3/title",
          "value": "FxDynamicParameterAPI_v3"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.professionalvideoapplications~1documentation~1professional_video_applications~1FxDynamicParameterAPI_v3/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "FxDynamicParameterAPI_v3"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.professionalvideoapplications~1documentation~1professional_video_applications~1FxDynamicParameterAPI_v3/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "FxDynamicParameterAPI_v3"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.professionalvideoapplications~1documentation~1professional_video_applications~1FxParameterRetrievalAPI_v7/title",
          "value": "FxParameterRetrievalAPI_v7"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.professionalvideoapplications~1documentation~1professional_video_applications~1FxParameterRetrievalAPI_v7/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "FxParameterRetrievalAPI_v7"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.professionalvideoapplications~1documentation~1professional_video_applications~1FxParameterRetrievalAPI_v7/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "FxParameterRetrievalAPI_v7"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.professionalvideoapplications~1documentation~1professional_video_applications~1FxParameterSettingAPI_v6/title",
          "value": "FxParameterSettingAPI_v6"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.professionalvideoapplications~1documentation~1professional_video_applications~1FxParameterSettingAPI_v6/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "FxParameterSettingAPI_v6"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.professionalvideoapplications~1documentation~1professional_video_applications~1FxParameterSettingAPI_v6/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "FxParameterSettingAPI_v6"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:objc(pl)NSObject/title",
          "value": "NSObject"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.professionalvideoapplications~1documentation~1professional_video_applications~1FxParameterCreationAPI_v5/title",
          "value": "FxParameterCreationAPI_v5"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.professionalvideoapplications~1documentation~1professional_video_applications~1FxParameterCreationAPI_v5/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "FxParameterCreationAPI_v5"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.professionalvideoapplications~1documentation~1professional_video_applications~1FxParameterCreationAPI_v5/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "FxParameterCreationAPI_v5"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/professional_video_applications/fxparameterretrievalapi_v7"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/professional_video_applications/fxparameterretrievalapi_v7"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
