{
  "abstract": [
    {
      "text": "Specifies the aspect ratio of the output frame pixels.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/kCEPixelAspectKey"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:ProCompressorExtensionProtocols.h@3864@macro@kCEPixelAspectKey",
    "fragments": [
      {
        "kind": "keyword",
        "text": "var"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "kCEPixelAspectKey"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "s:SS",
        "text": "String"
      }
    ],
    "modules": [
      {
        "name": "Professional Video Applications"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "kCEPixelAspectKey"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "introducedAt": "1.0",
        "name": "ProVideo Encoder Extensions"
      }
    ],
    "role": "symbol",
    "roleHeading": "Global Variable",
    "symbolKind": "var",
    "title": "kCEPixelAspectKey"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "Unsupported OS: ProExtension"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "var"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "kCEPixelAspectKey"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:SS",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:SS",
              "text": "String"
            },
            {
              "kind": "text",
              "text": " { "
            },
            {
              "kind": "keyword",
              "text": "get"
            },
            {
              "kind": "text",
              "text": " }"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "If the value is set to zero, the pixel ratio of the source file is used.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications": {
      "abstract": [
        {
          "text": "Exchange data with Final Cut Pro, and create effects plug-ins for Final Cut Pro and Motion.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications",
      "kind": "symbol",
      "role": "collection",
      "title": "Professional Video Applications",
      "type": "topic",
      "url": "/documentation/professional_video_applications"
    },
    "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/kCEAllowsSegmentationKey": {
      "abstract": [
        {
          "text": "Specifies whether the extension supports segmentation of the source media.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCEAllowsSegmentationKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/kCEAllowsSegmentationKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCEAllowsSegmentationKey"
        }
      ],
      "role": "symbol",
      "title": "kCEAllowsSegmentationKey",
      "type": "topic",
      "url": "/documentation/professional_video_applications/kceallowssegmentationkey"
    },
    "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/kCEAudioChannelLayoutKey": {
      "abstract": [
        {
          "text": "Specifies the audio channel layout for the output file.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCEAudioChannelLayoutKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/kCEAudioChannelLayoutKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCEAudioChannelLayoutKey"
        }
      ],
      "role": "symbol",
      "title": "kCEAudioChannelLayoutKey",
      "type": "topic",
      "url": "/documentation/professional_video_applications/kceaudiochannellayoutkey"
    },
    "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/kCEAudioEnabledKey": {
      "abstract": [
        {
          "text": "Specifies whether audio is enabled in the output file.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCEAudioEnabledKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/kCEAudioEnabledKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCEAudioEnabledKey"
        }
      ],
      "role": "symbol",
      "title": "kCEAudioEnabledKey",
      "type": "topic",
      "url": "/documentation/professional_video_applications/kceaudioenabledkey"
    },
    "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/kCEAudioSampleFloatKey": {
      "abstract": [
        {
          "text": "Specifies whether audio samples are in floating-point value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCEAudioSampleFloatKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/kCEAudioSampleFloatKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCEAudioSampleFloatKey"
        }
      ],
      "role": "symbol",
      "title": "kCEAudioSampleFloatKey",
      "type": "topic",
      "url": "/documentation/professional_video_applications/kceaudiosamplefloatkey"
    },
    "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/kCEAudioSampleRateKey": {
      "abstract": [
        {
          "text": "Specifies the sample rate of audio in the output file.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCEAudioSampleRateKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/kCEAudioSampleRateKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCEAudioSampleRateKey"
        }
      ],
      "role": "symbol",
      "title": "kCEAudioSampleRateKey",
      "type": "topic",
      "url": "/documentation/professional_video_applications/kceaudiosampleratekey"
    },
    "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/kCEAudioSampleSizeKey": {
      "abstract": [
        {
          "text": "Specifies the number of bits per audio sample in the output file.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCEAudioSampleSizeKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/kCEAudioSampleSizeKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCEAudioSampleSizeKey"
        }
      ],
      "role": "symbol",
      "title": "kCEAudioSampleSizeKey",
      "type": "topic",
      "url": "/documentation/professional_video_applications/kceaudiosamplesizekey"
    },
    "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/kCEAutoHeightKey": {
      "abstract": [
        {
          "text": "Specifies whether the output file height is set to automatic in the encoder settings.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCEAutoHeightKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/kCEAutoHeightKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCEAutoHeightKey"
        }
      ],
      "role": "symbol",
      "title": "kCEAutoHeightKey",
      "type": "topic",
      "url": "/documentation/professional_video_applications/kceautoheightkey"
    },
    "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/kCEAutoRateKey": {
      "abstract": [
        {
          "text": "Specifies whether the frame rate is set to automatic in the encoder settings.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCEAutoRateKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/kCEAutoRateKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCEAutoRateKey"
        }
      ],
      "role": "symbol",
      "title": "kCEAutoRateKey",
      "type": "topic",
      "url": "/documentation/professional_video_applications/kceautoratekey"
    },
    "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/kCEAutoWidthKey": {
      "abstract": [
        {
          "text": "Specifies whether the output file width is set to automatic in the encoder settings.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCEAutoWidthKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/kCEAutoWidthKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCEAutoWidthKey"
        }
      ],
      "role": "symbol",
      "title": "kCEAutoWidthKey",
      "type": "topic",
      "url": "/documentation/professional_video_applications/kceautowidthkey"
    },
    "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/kCEColorSpaceKey": {
      "abstract": [
        {
          "text": "Specifies the color space supported in the output file.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCEColorSpaceKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/kCEColorSpaceKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCEColorSpaceKey"
        }
      ],
      "role": "symbol",
      "title": "kCEColorSpaceKey",
      "type": "topic",
      "url": "/documentation/professional_video_applications/kcecolorspacekey"
    },
    "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/kCEFieldOrderKey": {
      "abstract": [
        {
          "text": "Specifies the output scanning method.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCEFieldOrderKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/kCEFieldOrderKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCEFieldOrderKey"
        }
      ],
      "role": "symbol",
      "title": "kCEFieldOrderKey",
      "type": "topic",
      "url": "/documentation/professional_video_applications/kcefieldorderkey"
    },
    "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/kCEFileExtensionKey": {
      "abstract": [
        {
          "text": "Specifies the extension of the output file.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCEFileExtensionKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/kCEFileExtensionKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCEFileExtensionKey"
        }
      ],
      "role": "symbol",
      "title": "kCEFileExtensionKey",
      "type": "topic",
      "url": "/documentation/professional_video_applications/kcefileextensionkey"
    },
    "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/kCEHeightKey": {
      "abstract": [
        {
          "text": "Specifies the height of the encoded video.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCEHeightKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/kCEHeightKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCEHeightKey"
        }
      ],
      "role": "symbol",
      "title": "kCEHeightKey",
      "type": "topic",
      "url": "/documentation/professional_video_applications/kceheightkey"
    },
    "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/kCEPixelAspectKey": {
      "abstract": [
        {
          "text": "Specifies the aspect ratio of the output frame pixels.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCEPixelAspectKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/kCEPixelAspectKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCEPixelAspectKey"
        }
      ],
      "role": "symbol",
      "title": "kCEPixelAspectKey",
      "type": "topic",
      "url": "/documentation/professional_video_applications/kcepixelaspectkey"
    },
    "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/kCEVideoEnabledKey": {
      "abstract": [
        {
          "text": "Specifies whether video is enabled in the output file.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCEVideoEnabledKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/kCEVideoEnabledKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCEVideoEnabledKey"
        }
      ],
      "role": "symbol",
      "title": "kCEVideoEnabledKey",
      "type": "topic",
      "url": "/documentation/professional_video_applications/kcevideoenabledkey"
    },
    "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/kCEWidthKey": {
      "abstract": [
        {
          "text": "Specifies the width of the encoded video.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCEWidthKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/kCEWidthKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCEWidthKey"
        }
      ],
      "role": "symbol",
      "title": "kCEWidthKey",
      "type": "topic",
      "url": "/documentation/professional_video_applications/kcewidthkey"
    },
    "doc://com.externally.resolved.symbol/s:SS": {
      "abstract": [
        {
          "text": "A Unicode string value that is a collection of characters.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@frozen"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "String"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SS",
      "kind": "symbol",
      "role": "symbol",
      "title": "String",
      "type": "topic",
      "url": "/documentation/Swift/String"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Encoder-Attribute-Keys",
      "generated": true,
      "identifiers": [
        "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/kCEAllowsSegmentationKey",
        "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/kCEFileExtensionKey",
        "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/kCEFieldOrderKey",
        "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/kCEColorSpaceKey",
        "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/kCEAudioChannelLayoutKey",
        "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/kCEVideoEnabledKey",
        "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/kCEAudioEnabledKey",
        "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/kCEAudioSampleFloatKey",
        "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/kCEAudioSampleRateKey",
        "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/kCEAudioSampleSizeKey",
        "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/kCEWidthKey",
        "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/kCEHeightKey",
        "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/kCEAutoRateKey",
        "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/kCEAutoWidthKey",
        "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/kCEAutoHeightKey"
      ],
      "title": "Encoder Attribute Keys"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": null
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Macro"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "kCEPixelAspectKey"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "macro"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCEPixelAspectKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Encoder-Attribute-Keys",
              "generated": true,
              "identifiers": [
                "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/kCEAllowsSegmentationKey",
                "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/kCEFileExtensionKey",
                "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/kCEFieldOrderKey",
                "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/kCEColorSpaceKey",
                "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/kCEAudioChannelLayoutKey",
                "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/kCEVideoEnabledKey",
                "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/kCEAudioEnabledKey",
                "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/kCEAudioSampleFloatKey",
                "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/kCEAudioSampleRateKey",
                "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/kCEAudioSampleSizeKey",
                "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/kCEWidthKey",
                "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/kCEHeightKey",
                "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/kCEAutoRateKey",
                "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/kCEAutoWidthKey",
                "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/kCEAutoHeightKey"
              ],
              "title": "Encoder Attribute Keys"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "Unsupported OS: ProExtension"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "#define"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "kCEPixelAspectKey"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.professionalvideoapplications~1documentation~1professional_video_applications~1kCEAutoHeightKey/title",
          "value": "kCEAutoHeightKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.professionalvideoapplications~1documentation~1professional_video_applications~1kCEAutoHeightKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCEAutoHeightKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.professionalvideoapplications~1documentation~1professional_video_applications~1kCEAutoWidthKey/title",
          "value": "kCEAutoWidthKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.professionalvideoapplications~1documentation~1professional_video_applications~1kCEAutoWidthKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCEAutoWidthKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.professionalvideoapplications~1documentation~1professional_video_applications~1kCEFileExtensionKey/title",
          "value": "kCEFileExtensionKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.professionalvideoapplications~1documentation~1professional_video_applications~1kCEFileExtensionKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCEFileExtensionKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.professionalvideoapplications~1documentation~1professional_video_applications~1kCEAllowsSegmentationKey/title",
          "value": "kCEAllowsSegmentationKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.professionalvideoapplications~1documentation~1professional_video_applications~1kCEAllowsSegmentationKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCEAllowsSegmentationKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.professionalvideoapplications~1documentation~1professional_video_applications~1kCEVideoEnabledKey/title",
          "value": "kCEVideoEnabledKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.professionalvideoapplications~1documentation~1professional_video_applications~1kCEVideoEnabledKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCEVideoEnabledKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.professionalvideoapplications~1documentation~1professional_video_applications~1kCEColorSpaceKey/title",
          "value": "kCEColorSpaceKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.professionalvideoapplications~1documentation~1professional_video_applications~1kCEColorSpaceKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCEColorSpaceKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.professionalvideoapplications~1documentation~1professional_video_applications~1kCEWidthKey/title",
          "value": "kCEWidthKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.professionalvideoapplications~1documentation~1professional_video_applications~1kCEWidthKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCEWidthKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.professionalvideoapplications~1documentation~1professional_video_applications~1kCEHeightKey/title",
          "value": "kCEHeightKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.professionalvideoapplications~1documentation~1professional_video_applications~1kCEHeightKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCEHeightKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.professionalvideoapplications~1documentation~1professional_video_applications~1kCEAudioChannelLayoutKey/title",
          "value": "kCEAudioChannelLayoutKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.professionalvideoapplications~1documentation~1professional_video_applications~1kCEAudioChannelLayoutKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCEAudioChannelLayoutKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.professionalvideoapplications~1documentation~1professional_video_applications~1kCEFieldOrderKey/title",
          "value": "kCEFieldOrderKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.professionalvideoapplications~1documentation~1professional_video_applications~1kCEFieldOrderKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCEFieldOrderKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.professionalvideoapplications~1documentation~1professional_video_applications~1kCEAudioEnabledKey/title",
          "value": "kCEAudioEnabledKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.professionalvideoapplications~1documentation~1professional_video_applications~1kCEAudioEnabledKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCEAudioEnabledKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.professionalvideoapplications~1documentation~1professional_video_applications~1kCEAudioSampleFloatKey/title",
          "value": "kCEAudioSampleFloatKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.professionalvideoapplications~1documentation~1professional_video_applications~1kCEAudioSampleFloatKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCEAudioSampleFloatKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.professionalvideoapplications~1documentation~1professional_video_applications~1kCEPixelAspectKey/title",
          "value": "kCEPixelAspectKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.professionalvideoapplications~1documentation~1professional_video_applications~1kCEPixelAspectKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCEPixelAspectKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.professionalvideoapplications~1documentation~1professional_video_applications~1kCEAutoRateKey/title",
          "value": "kCEAutoRateKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.professionalvideoapplications~1documentation~1professional_video_applications~1kCEAutoRateKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCEAutoRateKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.professionalvideoapplications~1documentation~1professional_video_applications~1kCEAudioSampleRateKey/title",
          "value": "kCEAudioSampleRateKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.professionalvideoapplications~1documentation~1professional_video_applications~1kCEAudioSampleRateKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCEAudioSampleRateKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.professionalvideoapplications~1documentation~1professional_video_applications~1kCEAudioSampleSizeKey/title",
          "value": "kCEAudioSampleSizeKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.professionalvideoapplications~1documentation~1professional_video_applications~1kCEAudioSampleSizeKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCEAudioSampleSizeKey"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/professional_video_applications/kcepixelaspectkey"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/professional_video_applications/kcepixelaspectkey"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
