{
  "abstract": [
    {
      "text": "A constant that indicates the remote window view wasn’t retrieved by the host.",
      "type": "text"
    }
  ],
  "diffAvailability": {
    "major": {
      "change": "added",
      "platform": "FxPlug",
      "versions": [
        "4.0",
        "4.2.9"
      ]
    }
  },
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/kFxError_NoViewFound"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@Ea@kFxError_Success@kFxError_NoViewFound",
    "fragments": [
      {
        "kind": "keyword",
        "text": "var"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "kFxError_NoViewFound"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "s:Si",
        "text": "Int"
      }
    ],
    "modules": [
      {
        "name": "Professional Video Applications"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "kFxError_NoViewFound"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "introducedAt": "4.2.1",
        "name": "FxPlug"
      }
    ],
    "role": "symbol",
    "roleHeading": "Global Variable",
    "symbolKind": "var",
    "title": "kFxError_NoViewFound"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "Unsupported OS: FxPlug"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "var"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "kFxError_NoViewFound"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:Si",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:Si",
              "text": "Int"
            },
            {
              "kind": "text",
              "text": " { "
            },
            {
              "kind": "keyword",
              "text": "get"
            },
            {
              "kind": "text",
              "text": " }"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications": {
      "abstract": [
        {
          "text": "Exchange data with Final Cut Pro, and create effects plug-ins for Final Cut Pro and Motion.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications",
      "kind": "symbol",
      "role": "collection",
      "title": "Professional Video Applications",
      "type": "topic",
      "url": "/documentation/professional_video_applications"
    },
    "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/enum_(unnamed)-5fh3s": {
      "abstract": [
        {
          "text": "Errors returned by plug-in hosts applications.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/enum_(unnamed)-5fh3s",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "enum (unnamed)"
        }
      ],
      "role": "symbol",
      "title": "enum (unnamed)",
      "type": "topic",
      "url": "/documentation/professional_video_applications/enum_(unnamed)-5fh3s"
    },
    "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/kFxError_APIUnavailable": {
      "abstract": [
        {
          "text": "The requested API cannot be used by the plug-in at this time.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kFxError_APIUnavailable"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/kFxError_APIUnavailable",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kFxError_APIUnavailable"
        }
      ],
      "role": "symbol",
      "title": "kFxError_APIUnavailable",
      "type": "topic",
      "url": "/documentation/professional_video_applications/kfxerror_apiunavailable"
    },
    "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/kFxError_AnalysisError": {
      "abstract": [
        {
          "text": "An error with analysis occurred.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kFxError_AnalysisError"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/kFxError_AnalysisError",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kFxError_AnalysisError"
        }
      ],
      "role": "symbol",
      "title": "kFxError_AnalysisError",
      "type": "topic",
      "url": "/documentation/professional_video_applications/kfxerror_analysiserror"
    },
    "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/kFxError_AnalysisExtensionNotFound": {
      "abstract": [
        {
          "text": "Analysis extension not found.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kFxError_AnalysisExtensionNotFound"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/kFxError_AnalysisExtensionNotFound",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kFxError_AnalysisExtensionNotFound"
        }
      ],
      "role": "symbol",
      "title": "kFxError_AnalysisExtensionNotFound",
      "type": "topic",
      "url": "/documentation/professional_video_applications/kfxerror_analysisextensionnotfound"
    },
    "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/kFxError_CommandNotProcessed": {
      "abstract": [
        {
          "text": "Unable to complete the command sent to the ",
          "type": "text"
        },
        {
          "code": "FxCommandAPI",
          "type": "codeVoice"
        },
        {
          "text": ".",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kFxError_CommandNotProcessed"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/kFxError_CommandNotProcessed",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kFxError_CommandNotProcessed"
        }
      ],
      "role": "symbol",
      "title": "kFxError_CommandNotProcessed",
      "type": "topic",
      "url": "/documentation/professional_video_applications/kfxerror_commandnotprocessed"
    },
    "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/kFxError_HostUnreachable": {
      "abstract": [
        {
          "text": "The host application cannot be reached to complete an operation.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kFxError_HostUnreachable"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/kFxError_HostUnreachable",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kFxError_HostUnreachable"
        }
      ],
      "role": "symbol",
      "title": "kFxError_HostUnreachable",
      "type": "topic",
      "url": "/documentation/professional_video_applications/kfxerror_hostunreachable"
    },
    "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/kFxError_InvalidColorGamut": {
      "abstract": [
        {
          "text": "A constant that indicates that an attempt to get color gamut info from the host failed.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kFxError_InvalidColorGamut"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/kFxError_InvalidColorGamut",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kFxError_InvalidColorGamut"
        }
      ],
      "role": "symbol",
      "title": "kFxError_InvalidColorGamut",
      "type": "topic",
      "url": "/documentation/professional_video_applications/kfxerror_invalidcolorgamut"
    },
    "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/kFxError_InvalidDataLength": {
      "abstract": [
        {
          "text": "An invalid data length was found by the plug-in while the host or framework was decoding data.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kFxError_InvalidDataLength"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/kFxError_InvalidDataLength",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kFxError_InvalidDataLength"
        }
      ],
      "role": "symbol",
      "title": "kFxError_InvalidDataLength",
      "type": "topic",
      "url": "/documentation/professional_video_applications/kfxerror_invaliddatalength"
    },
    "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/kFxError_InvalidKeyframeIndex": {
      "abstract": [
        {
          "text": "The plug-in passed an invalid keyframe index to the host.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kFxError_InvalidKeyframeIndex"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/kFxError_InvalidKeyframeIndex",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kFxError_InvalidKeyframeIndex"
        }
      ],
      "role": "symbol",
      "title": "kFxError_InvalidKeyframeIndex",
      "type": "topic",
      "url": "/documentation/professional_video_applications/kfxerror_invalidkeyframeindex"
    },
    "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/kFxError_InvalidLightAccess": {
      "abstract": [
        {
          "text": "An attempt was made by the plug-in to access lights without first requesting light access.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kFxError_InvalidLightAccess"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/kFxError_InvalidLightAccess",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kFxError_InvalidLightAccess"
        }
      ],
      "role": "symbol",
      "title": "kFxError_InvalidLightAccess",
      "type": "topic",
      "url": "/documentation/professional_video_applications/kfxerror_invalidlightaccess"
    },
    "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/kFxError_InvalidParameter": {
      "abstract": [
        {
          "text": "A parameter sent by the caller to an API method was invalid.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kFxError_InvalidParameter"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/kFxError_InvalidParameter",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kFxError_InvalidParameter"
        }
      ],
      "role": "symbol",
      "title": "kFxError_InvalidParameter",
      "type": "topic",
      "url": "/documentation/professional_video_applications/kfxerror_invalidparameter"
    },
    "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/kFxError_InvalidParameterChannelIndex": {
      "abstract": [
        {
          "text": "The plug-in passed an invalid channel number for a parameter to the host.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kFxError_InvalidParameterChannelIndex"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/kFxError_InvalidParameterChannelIndex",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kFxError_InvalidParameterChannelIndex"
        }
      ],
      "role": "symbol",
      "title": "kFxError_InvalidParameterChannelIndex",
      "type": "topic",
      "url": "/documentation/professional_video_applications/kfxerror_invalidparameterchannelindex"
    },
    "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/kFxError_InvalidParameterID": {
      "abstract": [
        {
          "text": "The plug-in passed an invalid parameter to the host.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kFxError_InvalidParameterID"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/kFxError_InvalidParameterID",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kFxError_InvalidParameterID"
        }
      ],
      "role": "symbol",
      "title": "kFxError_InvalidParameterID",
      "type": "topic",
      "url": "/documentation/professional_video_applications/kfxerror_invalidparameterid"
    },
    "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/kFxError_InvalidPathID": {
      "abstract": [
        {
          "text": "No path with that ID exists.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kFxError_InvalidPathID"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/kFxError_InvalidPathID",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kFxError_InvalidPathID"
        }
      ],
      "role": "symbol",
      "title": "kFxError_InvalidPathID",
      "type": "topic",
      "url": "/documentation/professional_video_applications/kfxerror_invalidpathid"
    },
    "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/kFxError_InvalidPathIndex": {
      "abstract": [
        {
          "text": "The index is greater than the number of paths.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kFxError_InvalidPathIndex"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/kFxError_InvalidPathIndex",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kFxError_InvalidPathIndex"
        }
      ],
      "role": "symbol",
      "title": "kFxError_InvalidPathIndex",
      "type": "topic",
      "url": "/documentation/professional_video_applications/kfxerror_invalidpathindex"
    },
    "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/kFxError_InvalidPaths": {
      "abstract": [
        {
          "text": "A constant that indicates that an attempt to get path info from the host failed.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kFxError_InvalidPaths"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/kFxError_InvalidPaths",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kFxError_InvalidPaths"
        }
      ],
      "role": "symbol",
      "title": "kFxError_InvalidPaths",
      "type": "topic",
      "url": "/documentation/professional_video_applications/kfxerror_invalidpaths"
    },
    "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/kFxError_NoViewFound": {
      "abstract": [
        {
          "text": "A constant that indicates the remote window view wasn’t retrieved by the host.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kFxError_NoViewFound"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/kFxError_NoViewFound",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kFxError_NoViewFound"
        }
      ],
      "role": "symbol",
      "title": "kFxError_NoViewFound",
      "type": "topic",
      "url": "/documentation/professional_video_applications/kfxerror_noviewfound"
    },
    "doc://com.externally.resolved.symbol/s:Si": {
      "abstract": [
        {
          "text": "A signed integer value type.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@frozen"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:Si",
      "kind": "symbol",
      "role": "symbol",
      "title": "Int",
      "type": "topic",
      "url": "/documentation/Swift/Int"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Constants",
      "generated": true,
      "identifiers": [
        "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/kFxError_AnalysisError",
        "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/kFxError_AnalysisExtensionNotFound",
        "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/kFxError_APIUnavailable",
        "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/kFxError_CommandNotProcessed",
        "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/kFxError_HostUnreachable",
        "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/kFxError_InvalidColorGamut",
        "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/kFxError_InvalidDataLength",
        "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/kFxError_InvalidKeyframeIndex",
        "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/kFxError_InvalidLightAccess",
        "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/kFxError_InvalidParameter",
        "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/kFxError_InvalidParameterChannelIndex",
        "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/kFxError_InvalidParameterID",
        "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/kFxError_InvalidPathID",
        "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/kFxError_InvalidPathIndex",
        "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/kFxError_InvalidPaths"
      ],
      "title": "Constants"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": null
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration Case"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "kFxError_NoViewFound"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "case"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kFxError_NoViewFound"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications",
                "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/enum_(unnamed)-5fh3s"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Constants",
              "generated": true,
              "identifiers": [
                "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/kFxError_AnalysisError",
                "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/kFxError_AnalysisExtensionNotFound",
                "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/kFxError_APIUnavailable",
                "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/kFxError_CommandNotProcessed",
                "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/kFxError_HostUnreachable",
                "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/kFxError_InvalidColorGamut",
                "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/kFxError_InvalidDataLength",
                "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/kFxError_InvalidKeyframeIndex",
                "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/kFxError_InvalidLightAccess",
                "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/kFxError_InvalidParameter",
                "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/kFxError_InvalidParameterChannelIndex",
                "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/kFxError_InvalidParameterID",
                "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/kFxError_InvalidPathID",
                "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/kFxError_InvalidPathIndex",
                "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/kFxError_InvalidPaths"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "Unsupported OS: FxPlug"
                ],
                "tokens": [
                  {
                    "kind": "identifier",
                    "text": "kFxError_NoViewFound"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.professionalvideoapplications~1documentation~1professional_video_applications~1kFxError_InvalidParameterChannelIndex/title",
          "value": "kFxError_InvalidParameterChannelIndex"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.professionalvideoapplications~1documentation~1professional_video_applications~1kFxError_InvalidParameterChannelIndex/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kFxError_InvalidParameterChannelIndex"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.professionalvideoapplications~1documentation~1professional_video_applications~1kFxError_InvalidColorGamut/title",
          "value": "kFxError_InvalidColorGamut"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.professionalvideoapplications~1documentation~1professional_video_applications~1kFxError_InvalidColorGamut/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kFxError_InvalidColorGamut"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.professionalvideoapplications~1documentation~1professional_video_applications~1kFxError_InvalidParameterID/title",
          "value": "kFxError_InvalidParameterID"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.professionalvideoapplications~1documentation~1professional_video_applications~1kFxError_InvalidParameterID/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kFxError_InvalidParameterID"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.professionalvideoapplications~1documentation~1professional_video_applications~1kFxError_NoViewFound/title",
          "value": "kFxError_NoViewFound"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.professionalvideoapplications~1documentation~1professional_video_applications~1kFxError_NoViewFound/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kFxError_NoViewFound"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.professionalvideoapplications~1documentation~1professional_video_applications~1kFxError_InvalidLightAccess/title",
          "value": "kFxError_InvalidLightAccess"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.professionalvideoapplications~1documentation~1professional_video_applications~1kFxError_InvalidLightAccess/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kFxError_InvalidLightAccess"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.professionalvideoapplications~1documentation~1professional_video_applications~1kFxError_InvalidPathID/title",
          "value": "kFxError_InvalidPathID"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.professionalvideoapplications~1documentation~1professional_video_applications~1kFxError_InvalidPathID/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kFxError_InvalidPathID"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.professionalvideoapplications~1documentation~1professional_video_applications~1kFxError_InvalidPathIndex/title",
          "value": "kFxError_InvalidPathIndex"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.professionalvideoapplications~1documentation~1professional_video_applications~1kFxError_InvalidPathIndex/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kFxError_InvalidPathIndex"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.professionalvideoapplications~1documentation~1professional_video_applications~1kFxError_InvalidPaths/title",
          "value": "kFxError_InvalidPaths"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.professionalvideoapplications~1documentation~1professional_video_applications~1kFxError_InvalidPaths/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kFxError_InvalidPaths"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.professionalvideoapplications~1documentation~1professional_video_applications~1kFxError_AnalysisError/title",
          "value": "kFxError_AnalysisError"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.professionalvideoapplications~1documentation~1professional_video_applications~1kFxError_AnalysisError/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kFxError_AnalysisError"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.professionalvideoapplications~1documentation~1professional_video_applications~1kFxError_InvalidKeyframeIndex/title",
          "value": "kFxError_InvalidKeyframeIndex"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.professionalvideoapplications~1documentation~1professional_video_applications~1kFxError_InvalidKeyframeIndex/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kFxError_InvalidKeyframeIndex"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.professionalvideoapplications~1documentation~1professional_video_applications~1kFxError_CommandNotProcessed/title",
          "value": "kFxError_CommandNotProcessed"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.professionalvideoapplications~1documentation~1professional_video_applications~1kFxError_CommandNotProcessed/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kFxError_CommandNotProcessed"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.professionalvideoapplications~1documentation~1professional_video_applications~1kFxError_APIUnavailable/title",
          "value": "kFxError_APIUnavailable"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.professionalvideoapplications~1documentation~1professional_video_applications~1kFxError_APIUnavailable/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kFxError_APIUnavailable"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.professionalvideoapplications~1documentation~1professional_video_applications~1kFxError_InvalidDataLength/title",
          "value": "kFxError_InvalidDataLength"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.professionalvideoapplications~1documentation~1professional_video_applications~1kFxError_InvalidDataLength/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kFxError_InvalidDataLength"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.professionalvideoapplications~1documentation~1professional_video_applications~1kFxError_InvalidParameter/title",
          "value": "kFxError_InvalidParameter"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.professionalvideoapplications~1documentation~1professional_video_applications~1kFxError_InvalidParameter/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kFxError_InvalidParameter"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.professionalvideoapplications~1documentation~1professional_video_applications~1kFxError_HostUnreachable/title",
          "value": "kFxError_HostUnreachable"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.professionalvideoapplications~1documentation~1professional_video_applications~1kFxError_HostUnreachable/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kFxError_HostUnreachable"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.professionalvideoapplications~1documentation~1professional_video_applications~1kFxError_AnalysisExtensionNotFound/title",
          "value": "kFxError_AnalysisExtensionNotFound"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.professionalvideoapplications~1documentation~1professional_video_applications~1kFxError_AnalysisExtensionNotFound/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kFxError_AnalysisExtensionNotFound"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/professional_video_applications/kfxerror_noviewfound"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/professional_video_applications/kfxerror_noviewfound"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
