{
  "abstract": [
    {
      "text": "A constant that indicates that the requested frame is associated with the source clip.",
      "type": "text"
    }
  ],
  "diffAvailability": {
    "major": {
      "change": "added",
      "platform": "FxPlug",
      "versions": [
        "4.0",
        "4.2.9"
      ]
    }
  },
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/kFxImageTileRequestSourceEffectClip"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@EA@FxImageTileRequestSource@kFxImageTileRequestSourceEffectClip",
    "fragments": [
      {
        "kind": "keyword",
        "text": "var"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "kFxImageTileRequestSourceEffectClip"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@EA@FxImageTileRequestSource",
        "text": "FxImageTileRequestSource"
      }
    ],
    "modules": [
      {
        "name": "Professional Video Applications"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "kFxImageTileRequestSourceEffectClip"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "introducedAt": "4.0",
        "name": "FxPlug"
      }
    ],
    "role": "symbol",
    "roleHeading": "Global Variable",
    "symbolKind": "var",
    "title": "kFxImageTileRequestSourceEffectClip"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "Unsupported OS: FxPlug"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "var"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "kFxImageTileRequestSourceEffectClip"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/FxImageTileRequestSource",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@EA@FxImageTileRequestSource",
              "text": "FxImageTileRequestSource"
            },
            {
              "kind": "text",
              "text": " { "
            },
            {
              "kind": "keyword",
              "text": "get"
            },
            {
              "kind": "text",
              "text": " }"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications": {
      "abstract": [
        {
          "text": "Exchange data with Final Cut Pro, and create effects plug-ins for Final Cut Pro and Motion.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications",
      "kind": "symbol",
      "role": "collection",
      "title": "Professional Video Applications",
      "type": "topic",
      "url": "/documentation/professional_video_applications"
    },
    "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/FxImageTileRequestSource": {
      "abstract": [
        {
          "text": "An enumeration that identifies the requested frame.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "FxImageTileRequestSource"
        }
      ],
      "identifier": "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/FxImageTileRequestSource",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "FxImageTileRequestSource"
        }
      ],
      "role": "symbol",
      "title": "FxImageTileRequestSource",
      "type": "topic",
      "url": "/documentation/professional_video_applications/fximagetilerequestsource"
    },
    "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/kFxImageTileRequestSourceEffectClip": {
      "abstract": [
        {
          "text": "A constant that indicates that the requested frame is associated with the source clip.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kFxImageTileRequestSourceEffectClip"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@EA@FxImageTileRequestSource",
          "text": "FxImageTileRequestSource"
        }
      ],
      "identifier": "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/kFxImageTileRequestSourceEffectClip",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kFxImageTileRequestSourceEffectClip"
        }
      ],
      "role": "symbol",
      "title": "kFxImageTileRequestSourceEffectClip",
      "type": "topic",
      "url": "/documentation/professional_video_applications/kfximagetilerequestsourceeffectclip"
    },
    "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/kFxImageTileRequestSourceNone": {
      "abstract": [
        {
          "text": "A constant that indicates that the requested frame is not associated with an effect or parameter.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kFxImageTileRequestSourceNone"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@EA@FxImageTileRequestSource",
          "text": "FxImageTileRequestSource"
        }
      ],
      "identifier": "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/kFxImageTileRequestSourceNone",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kFxImageTileRequestSourceNone"
        }
      ],
      "role": "symbol",
      "title": "kFxImageTileRequestSourceNone",
      "type": "topic",
      "url": "/documentation/professional_video_applications/kfximagetilerequestsourcenone"
    },
    "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/kFxImageTileRequestSourceOutput": {
      "abstract": [
        {
          "text": "A constant that indicates that the requested frame is the output of a plug-in.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kFxImageTileRequestSourceOutput"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@EA@FxImageTileRequestSource",
          "text": "FxImageTileRequestSource"
        }
      ],
      "identifier": "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/kFxImageTileRequestSourceOutput",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kFxImageTileRequestSourceOutput"
        }
      ],
      "role": "symbol",
      "title": "kFxImageTileRequestSourceOutput",
      "type": "topic",
      "url": "/documentation/professional_video_applications/kfximagetilerequestsourceoutput"
    },
    "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/kFxImageTileRequestSourceParameter": {
      "abstract": [
        {
          "text": "A constant that indicates that the requested frame is associated with an image well parameter.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kFxImageTileRequestSourceParameter"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@EA@FxImageTileRequestSource",
          "text": "FxImageTileRequestSource"
        }
      ],
      "identifier": "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/kFxImageTileRequestSourceParameter",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kFxImageTileRequestSourceParameter"
        }
      ],
      "role": "symbol",
      "title": "kFxImageTileRequestSourceParameter",
      "type": "topic",
      "url": "/documentation/professional_video_applications/kfximagetilerequestsourceparameter"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Constants",
      "generated": true,
      "identifiers": [
        "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/kFxImageTileRequestSourceNone",
        "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/kFxImageTileRequestSourceOutput",
        "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/kFxImageTileRequestSourceParameter"
      ],
      "title": "Constants"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": null
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration Case"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "kFxImageTileRequestSourceEffectClip"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "case"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kFxImageTileRequestSourceEffectClip"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications",
                "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/FxImageTileRequestSource"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Constants",
              "generated": true,
              "identifiers": [
                "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/kFxImageTileRequestSourceNone",
                "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/kFxImageTileRequestSourceOutput",
                "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/kFxImageTileRequestSourceParameter"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "Unsupported OS: FxPlug"
                ],
                "tokens": [
                  {
                    "kind": "identifier",
                    "text": "kFxImageTileRequestSourceEffectClip"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.professionalvideoapplications~1documentation~1professional_video_applications~1kFxImageTileRequestSourceOutput/title",
          "value": "kFxImageTileRequestSourceOutput"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.professionalvideoapplications~1documentation~1professional_video_applications~1kFxImageTileRequestSourceOutput/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kFxImageTileRequestSourceOutput"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.professionalvideoapplications~1documentation~1professional_video_applications~1kFxImageTileRequestSourceParameter/title",
          "value": "kFxImageTileRequestSourceParameter"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.professionalvideoapplications~1documentation~1professional_video_applications~1kFxImageTileRequestSourceParameter/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kFxImageTileRequestSourceParameter"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.professionalvideoapplications~1documentation~1professional_video_applications~1kFxImageTileRequestSourceNone/title",
          "value": "kFxImageTileRequestSourceNone"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.professionalvideoapplications~1documentation~1professional_video_applications~1kFxImageTileRequestSourceNone/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kFxImageTileRequestSourceNone"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.professionalvideoapplications~1documentation~1professional_video_applications~1FxImageTileRequestSource/title",
          "value": "FxImageTileRequestSource"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.professionalvideoapplications~1documentation~1professional_video_applications~1FxImageTileRequestSource/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "FxImageTileRequestSource"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.professionalvideoapplications~1documentation~1professional_video_applications~1kFxImageTileRequestSourceEffectClip/title",
          "value": "kFxImageTileRequestSourceEffectClip"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.professionalvideoapplications~1documentation~1professional_video_applications~1kFxImageTileRequestSourceEffectClip/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kFxImageTileRequestSourceEffectClip"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/professional_video_applications/kfximagetilerequestsourceeffectclip"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/professional_video_applications/kfximagetilerequestsourceeffectclip"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
