{
  "diffAvailability": {
    "major": {
      "change": "added",
      "platform": "FxPlug",
      "versions": [
        "4.0",
        "4.2.9"
      ]
    }
  },
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/kFxParameterFlag_CURVE_EDITOR_HIDDEN"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@Ea@kFxParameterFlag_DEFAULT@kFxParameterFlag_CURVE_EDITOR_HIDDEN",
    "fragments": [
      {
        "kind": "keyword",
        "text": "var"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "kFxParameterFlag_CURVE_EDITOR_HIDDEN"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "s:Si",
        "text": "Int"
      }
    ],
    "modules": [
      {
        "name": "Professional Video Applications"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "kFxParameterFlag_CURVE_EDITOR_HIDDEN"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "introducedAt": "3.1",
        "name": "FxPlug"
      }
    ],
    "role": "symbol",
    "roleHeading": "Global Variable",
    "symbolKind": "var",
    "title": "kFxParameterFlag_CURVE_EDITOR_HIDDEN"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "Unsupported OS: FxPlug"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "var"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "kFxParameterFlag_CURVE_EDITOR_HIDDEN"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:Si",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:Si",
              "text": "Int"
            },
            {
              "kind": "text",
              "text": " { "
            },
            {
              "kind": "keyword",
              "text": "get"
            },
            {
              "kind": "text",
              "text": " }"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications": {
      "abstract": [
        {
          "text": "Exchange data with Final Cut Pro, and create effects plug-ins for Final Cut Pro and Motion.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications",
      "kind": "symbol",
      "role": "collection",
      "title": "Professional Video Applications",
      "type": "topic",
      "url": "/documentation/professional_video_applications"
    },
    "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/enum_(unnamed)-7jahq": {
      "abstract": [],
      "identifier": "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/enum_(unnamed)-7jahq",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "enum (unnamed)"
        }
      ],
      "role": "symbol",
      "title": "enum (unnamed)",
      "type": "topic",
      "url": "/documentation/professional_video_applications/enum_(unnamed)-7jahq"
    },
    "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/kFxParameterFlag_COLLAPSED": {
      "abstract": [
        {
          "text": "This group parameter’s subgroup is closed and its sub-parameters are not visible in the Inspector.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kFxParameterFlag_COLLAPSED"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/kFxParameterFlag_COLLAPSED",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kFxParameterFlag_COLLAPSED"
        }
      ],
      "role": "symbol",
      "title": "kFxParameterFlag_COLLAPSED",
      "type": "topic",
      "url": "/documentation/professional_video_applications/kfxparameterflag_collapsed"
    },
    "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/kFxParameterFlag_CURVE_EDITOR_HIDDEN": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kFxParameterFlag_CURVE_EDITOR_HIDDEN"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/kFxParameterFlag_CURVE_EDITOR_HIDDEN",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kFxParameterFlag_CURVE_EDITOR_HIDDEN"
        }
      ],
      "role": "symbol",
      "title": "kFxParameterFlag_CURVE_EDITOR_HIDDEN",
      "type": "topic",
      "url": "/documentation/professional_video_applications/kfxparameterflag_curve_editor_hidden"
    },
    "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/kFxParameterFlag_CUSTOM_UI": {
      "abstract": [
        {
          "text": "This parameter uses a custom user interface that replaces the standard parameter UI.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kFxParameterFlag_CUSTOM_UI"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/kFxParameterFlag_CUSTOM_UI",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kFxParameterFlag_CUSTOM_UI"
        }
      ],
      "role": "symbol",
      "title": "kFxParameterFlag_CUSTOM_UI",
      "type": "topic",
      "url": "/documentation/professional_video_applications/kfxparameterflag_custom_ui"
    },
    "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/kFxParameterFlag_DEFAULT": {
      "abstract": [
        {
          "text": "Convenience constant. No flags set.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kFxParameterFlag_DEFAULT"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/kFxParameterFlag_DEFAULT",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kFxParameterFlag_DEFAULT"
        }
      ],
      "role": "symbol",
      "title": "kFxParameterFlag_DEFAULT",
      "type": "topic",
      "url": "/documentation/professional_video_applications/kfxparameterflag_default"
    },
    "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/kFxParameterFlag_DISABLED": {
      "abstract": [
        {
          "text": "This parameter is dimmed and disabled.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kFxParameterFlag_DISABLED"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/kFxParameterFlag_DISABLED",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kFxParameterFlag_DISABLED"
        }
      ],
      "role": "symbol",
      "title": "kFxParameterFlag_DISABLED",
      "type": "topic",
      "url": "/documentation/professional_video_applications/kfxparameterflag_disabled"
    },
    "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/kFxParameterFlag_DONT_DISPLAY_IN_DASHBOARD": {
      "abstract": [
        {
          "text": "This parameter is not visible in the dashboard controls.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kFxParameterFlag_DONT_DISPLAY_IN_DASHBOARD"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/kFxParameterFlag_DONT_DISPLAY_IN_DASHBOARD",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kFxParameterFlag_DONT_DISPLAY_IN_DASHBOARD"
        }
      ],
      "role": "symbol",
      "title": "kFxParameterFlag_DONT_DISPLAY_IN_DASHBOARD",
      "type": "topic",
      "url": "/documentation/professional_video_applications/kfxparameterflag_dont_display_in_dashboard"
    },
    "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/kFxParameterFlag_DONT_REMAP_COLORS": {
      "abstract": [
        {
          "text": "Indicates that the host must not remap colors to sRGB.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kFxParameterFlag_DONT_REMAP_COLORS"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/kFxParameterFlag_DONT_REMAP_COLORS",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kFxParameterFlag_DONT_REMAP_COLORS"
        }
      ],
      "role": "symbol",
      "title": "kFxParameterFlag_DONT_REMAP_COLORS",
      "type": "topic",
      "url": "/documentation/professional_video_applications/kfxparameterflag_dont_remap_colors"
    },
    "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/kFxParameterFlag_DONT_SAVE": {
      "abstract": [
        {
          "text": "This parameter’s values are not saved or loaded.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kFxParameterFlag_DONT_SAVE"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/kFxParameterFlag_DONT_SAVE",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kFxParameterFlag_DONT_SAVE"
        }
      ],
      "role": "symbol",
      "title": "kFxParameterFlag_DONT_SAVE",
      "type": "topic",
      "url": "/documentation/professional_video_applications/kfxparameterflag_dont_save"
    },
    "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/kFxParameterFlag_HIDDEN": {
      "abstract": [
        {
          "text": "This parameter displays no UI to the user, but its value is saved/loaded.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kFxParameterFlag_HIDDEN"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/kFxParameterFlag_HIDDEN",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kFxParameterFlag_HIDDEN"
        }
      ],
      "role": "symbol",
      "title": "kFxParameterFlag_HIDDEN",
      "type": "topic",
      "url": "/documentation/professional_video_applications/kfxparameterflag_hidden"
    },
    "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/kFxParameterFlag_IGNORE_MINMAX": {
      "abstract": [
        {
          "text": "This parameter’s range is unbounded.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kFxParameterFlag_IGNORE_MINMAX"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/kFxParameterFlag_IGNORE_MINMAX",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kFxParameterFlag_IGNORE_MINMAX"
        }
      ],
      "role": "symbol",
      "title": "kFxParameterFlag_IGNORE_MINMAX",
      "type": "topic",
      "url": "/documentation/professional_video_applications/kfxparameterflag_ignore_minmax"
    },
    "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/kFxParameterFlag_NOT_ANIMATABLE": {
      "abstract": [
        {
          "text": "This parameter’s value is constant across time and cannot be animated.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kFxParameterFlag_NOT_ANIMATABLE"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/kFxParameterFlag_NOT_ANIMATABLE",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kFxParameterFlag_NOT_ANIMATABLE"
        }
      ],
      "role": "symbol",
      "title": "kFxParameterFlag_NOT_ANIMATABLE",
      "type": "topic",
      "url": "/documentation/professional_video_applications/kfxparameterflag_not_animatable"
    },
    "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/kFxParameterFlag_USE_FULL_VIEW_WIDTH": {
      "abstract": [
        {
          "text": "This parameter uses the full width of the view.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kFxParameterFlag_USE_FULL_VIEW_WIDTH"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/kFxParameterFlag_USE_FULL_VIEW_WIDTH",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kFxParameterFlag_USE_FULL_VIEW_WIDTH"
        }
      ],
      "role": "symbol",
      "title": "kFxParameterFlag_USE_FULL_VIEW_WIDTH",
      "type": "topic",
      "url": "/documentation/professional_video_applications/kfxparameterflag_use_full_view_width"
    },
    "doc://com.externally.resolved.symbol/s:Si": {
      "abstract": [
        {
          "text": "A signed integer value type.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@frozen"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:Si",
      "kind": "symbol",
      "role": "symbol",
      "title": "Int",
      "type": "topic",
      "url": "/documentation/Swift/Int"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Constants",
      "generated": true,
      "identifiers": [
        "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/kFxParameterFlag_COLLAPSED",
        "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/kFxParameterFlag_CUSTOM_UI",
        "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/kFxParameterFlag_DEFAULT",
        "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/kFxParameterFlag_DISABLED",
        "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/kFxParameterFlag_DONT_DISPLAY_IN_DASHBOARD",
        "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/kFxParameterFlag_DONT_SAVE",
        "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/kFxParameterFlag_HIDDEN",
        "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/kFxParameterFlag_IGNORE_MINMAX",
        "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/kFxParameterFlag_NOT_ANIMATABLE",
        "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/kFxParameterFlag_DONT_REMAP_COLORS",
        "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/kFxParameterFlag_USE_FULL_VIEW_WIDTH"
      ],
      "title": "Constants"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": null
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration Case"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "kFxParameterFlag_CURVE_EDITOR_HIDDEN"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "case"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kFxParameterFlag_CURVE_EDITOR_HIDDEN"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications",
                "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/enum_(unnamed)-7jahq"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Constants",
              "generated": true,
              "identifiers": [
                "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/kFxParameterFlag_COLLAPSED",
                "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/kFxParameterFlag_CUSTOM_UI",
                "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/kFxParameterFlag_DEFAULT",
                "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/kFxParameterFlag_DISABLED",
                "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/kFxParameterFlag_DONT_DISPLAY_IN_DASHBOARD",
                "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/kFxParameterFlag_DONT_SAVE",
                "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/kFxParameterFlag_HIDDEN",
                "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/kFxParameterFlag_IGNORE_MINMAX",
                "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/kFxParameterFlag_NOT_ANIMATABLE",
                "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/kFxParameterFlag_DONT_REMAP_COLORS",
                "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/kFxParameterFlag_USE_FULL_VIEW_WIDTH"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "Unsupported OS: FxPlug"
                ],
                "tokens": [
                  {
                    "kind": "identifier",
                    "text": "kFxParameterFlag_CURVE_EDITOR_HIDDEN"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.professionalvideoapplications~1documentation~1professional_video_applications~1kFxParameterFlag_COLLAPSED/title",
          "value": "kFxParameterFlag_COLLAPSED"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.professionalvideoapplications~1documentation~1professional_video_applications~1kFxParameterFlag_COLLAPSED/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kFxParameterFlag_COLLAPSED"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.professionalvideoapplications~1documentation~1professional_video_applications~1kFxParameterFlag_NOT_ANIMATABLE/title",
          "value": "kFxParameterFlag_NOT_ANIMATABLE"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.professionalvideoapplications~1documentation~1professional_video_applications~1kFxParameterFlag_NOT_ANIMATABLE/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kFxParameterFlag_NOT_ANIMATABLE"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.professionalvideoapplications~1documentation~1professional_video_applications~1kFxParameterFlag_HIDDEN/title",
          "value": "kFxParameterFlag_HIDDEN"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.professionalvideoapplications~1documentation~1professional_video_applications~1kFxParameterFlag_HIDDEN/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kFxParameterFlag_HIDDEN"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.professionalvideoapplications~1documentation~1professional_video_applications~1kFxParameterFlag_USE_FULL_VIEW_WIDTH/title",
          "value": "kFxParameterFlag_USE_FULL_VIEW_WIDTH"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.professionalvideoapplications~1documentation~1professional_video_applications~1kFxParameterFlag_USE_FULL_VIEW_WIDTH/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kFxParameterFlag_USE_FULL_VIEW_WIDTH"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.professionalvideoapplications~1documentation~1professional_video_applications~1kFxParameterFlag_DONT_SAVE/title",
          "value": "kFxParameterFlag_DONT_SAVE"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.professionalvideoapplications~1documentation~1professional_video_applications~1kFxParameterFlag_DONT_SAVE/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kFxParameterFlag_DONT_SAVE"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.professionalvideoapplications~1documentation~1professional_video_applications~1kFxParameterFlag_CUSTOM_UI/title",
          "value": "kFxParameterFlag_CUSTOM_UI"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.professionalvideoapplications~1documentation~1professional_video_applications~1kFxParameterFlag_CUSTOM_UI/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kFxParameterFlag_CUSTOM_UI"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.professionalvideoapplications~1documentation~1professional_video_applications~1kFxParameterFlag_DISABLED/title",
          "value": "kFxParameterFlag_DISABLED"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.professionalvideoapplications~1documentation~1professional_video_applications~1kFxParameterFlag_DISABLED/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kFxParameterFlag_DISABLED"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.professionalvideoapplications~1documentation~1professional_video_applications~1kFxParameterFlag_DEFAULT/title",
          "value": "kFxParameterFlag_DEFAULT"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.professionalvideoapplications~1documentation~1professional_video_applications~1kFxParameterFlag_DEFAULT/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kFxParameterFlag_DEFAULT"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.professionalvideoapplications~1documentation~1professional_video_applications~1kFxParameterFlag_DONT_DISPLAY_IN_DASHBOARD/title",
          "value": "kFxParameterFlag_DONT_DISPLAY_IN_DASHBOARD"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.professionalvideoapplications~1documentation~1professional_video_applications~1kFxParameterFlag_DONT_DISPLAY_IN_DASHBOARD/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kFxParameterFlag_DONT_DISPLAY_IN_DASHBOARD"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.professionalvideoapplications~1documentation~1professional_video_applications~1kFxParameterFlag_DONT_REMAP_COLORS/title",
          "value": "kFxParameterFlag_DONT_REMAP_COLORS"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.professionalvideoapplications~1documentation~1professional_video_applications~1kFxParameterFlag_DONT_REMAP_COLORS/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kFxParameterFlag_DONT_REMAP_COLORS"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.professionalvideoapplications~1documentation~1professional_video_applications~1kFxParameterFlag_CURVE_EDITOR_HIDDEN/title",
          "value": "kFxParameterFlag_CURVE_EDITOR_HIDDEN"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.professionalvideoapplications~1documentation~1professional_video_applications~1kFxParameterFlag_CURVE_EDITOR_HIDDEN/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kFxParameterFlag_CURVE_EDITOR_HIDDEN"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.professionalvideoapplications~1documentation~1professional_video_applications~1kFxParameterFlag_IGNORE_MINMAX/title",
          "value": "kFxParameterFlag_IGNORE_MINMAX"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.professionalvideoapplications~1documentation~1professional_video_applications~1kFxParameterFlag_IGNORE_MINMAX/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kFxParameterFlag_IGNORE_MINMAX"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/professional_video_applications/kfxparameterflag_curve_editor_hidden"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/professional_video_applications/kfxparameterflag_curve_editor_hidden"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
