{
  "abstract": [
    {
      "text": "A key that determines whether your plug-in renders in linear or gamma-corrected color space.",
      "type": "text"
    }
  ],
  "diffAvailability": {
    "major": {
      "change": "added",
      "platform": "FxPlug",
      "versions": [
        "4.0",
        "4.2.9"
      ]
    }
  },
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/kFxPropertyKey_DesiredProcessingColorInfo"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@macro@kFxPropertyKey_DesiredProcessingColorInfo",
    "fragments": [
      {
        "kind": "keyword",
        "text": "var"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "kFxPropertyKey_DesiredProcessingColorInfo"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "s:SS",
        "text": "String"
      }
    ],
    "modules": [
      {
        "name": "Professional Video Applications"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "kFxPropertyKey_DesiredProcessingColorInfo"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "introducedAt": "3.1",
        "name": "FxPlug"
      }
    ],
    "role": "symbol",
    "roleHeading": "Global Variable",
    "symbolKind": "var",
    "title": "kFxPropertyKey_DesiredProcessingColorInfo"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "Unsupported OS: FxPlug"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "var"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "kFxPropertyKey_DesiredProcessingColorInfo"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:SS",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:SS",
              "text": "String"
            },
            {
              "kind": "text",
              "text": " { "
            },
            {
              "kind": "keyword",
              "text": "get"
            },
            {
              "kind": "text",
              "text": " }"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "kind": "mentions",
      "mentions": [
        "doc://com.apple.professionalvideoapplications/documentation/Professional-Video-Applications/managing-color-space-and-gamut-in-plug-ins"
      ]
    },
    {
      "content": [
        {
          "anchor": "discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "The value for this key is an ",
              "type": "text"
            },
            {
              "code": "NSUInteger",
              "type": "codeVoice"
            },
            {
              "text": " indicating the color space that the plug-in will process in. This color space is expressed as an ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/FxImageColorInfo",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " constant. If a plug-in includes this property, all inputs are in the specified color space, and the output must also be in this color space.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.professionalvideoapplications/documentation/Professional-Video-Applications/managing-color-space-and-gamut-in-plug-ins": {
      "abstract": [
        {
          "text": "Control the appearance of your rendering by using the color gamut API.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.professionalvideoapplications/documentation/Professional-Video-Applications/managing-color-space-and-gamut-in-plug-ins",
      "kind": "article",
      "role": "article",
      "title": "Managing color space and gamut in plug-ins",
      "type": "topic",
      "url": "/documentation/professional-video-applications/managing-color-space-and-gamut-in-plug-ins"
    },
    "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications": {
      "abstract": [
        {
          "text": "Exchange data with Final Cut Pro, and create effects plug-ins for Final Cut Pro and Motion.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications",
      "kind": "symbol",
      "role": "collection",
      "title": "Professional Video Applications",
      "type": "topic",
      "url": "/documentation/professional_video_applications"
    },
    "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/FxImageColorInfo": {
      "abstract": [
        {
          "text": "Identifies some color properties of an FxImage instance. These include the color space, gamma level, and, in the case of ",
          "type": "text"
        },
        {
          "code": "YCbCr",
          "type": "codeVoice"
        },
        {
          "text": " images, the color matrix for conversion to RGB.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "FxImageColorInfo"
        }
      ],
      "identifier": "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/FxImageColorInfo",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "FxImageColorInfo"
        }
      ],
      "role": "symbol",
      "title": "FxImageColorInfo",
      "type": "topic",
      "url": "/documentation/professional_video_applications/fximagecolorinfo"
    },
    "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/kFxPropertyKey_ChangesOutputSize": {
      "abstract": [
        {
          "text": "A key that determines whether your filter has the ability to change the size of its output to be different than the size of its input.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kFxPropertyKey_ChangesOutputSize"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/kFxPropertyKey_ChangesOutputSize",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kFxPropertyKey_ChangesOutputSize"
        }
      ],
      "role": "symbol",
      "title": "kFxPropertyKey_ChangesOutputSize",
      "type": "topic",
      "url": "/documentation/professional_video_applications/kfxpropertykey_changesoutputsize"
    },
    "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/kFxPropertyKey_DesiredProcessingColorInfo": {
      "abstract": [
        {
          "text": "A key that determines whether your plug-in renders in linear or gamma-corrected color space.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kFxPropertyKey_DesiredProcessingColorInfo"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/kFxPropertyKey_DesiredProcessingColorInfo",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kFxPropertyKey_DesiredProcessingColorInfo"
        }
      ],
      "role": "symbol",
      "title": "kFxPropertyKey_DesiredProcessingColorInfo",
      "type": "topic",
      "url": "/documentation/professional_video_applications/kfxpropertykey_desiredprocessingcolorinfo"
    },
    "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/kFxPropertyKey_NeedsFullBuffer": {
      "abstract": [
        {
          "text": "A key that determines whether the plug-in needs the entire image to do its processing, and can’t tile its rendering.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kFxPropertyKey_NeedsFullBuffer"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/kFxPropertyKey_NeedsFullBuffer",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kFxPropertyKey_NeedsFullBuffer"
        }
      ],
      "role": "symbol",
      "title": "kFxPropertyKey_NeedsFullBuffer",
      "type": "topic",
      "url": "/documentation/professional_video_applications/kfxpropertykey_needsfullbuffer"
    },
    "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/kFxPropertyKey_VariesWhenParamsAreStatic": {
      "abstract": [
        {
          "text": "A key that determines whether your rendering varies even when the parameters remain the same.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kFxPropertyKey_VariesWhenParamsAreStatic"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/kFxPropertyKey_VariesWhenParamsAreStatic",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kFxPropertyKey_VariesWhenParamsAreStatic"
        }
      ],
      "role": "symbol",
      "title": "kFxPropertyKey_VariesWhenParamsAreStatic",
      "type": "topic",
      "url": "/documentation/professional_video_applications/kfxpropertykey_varieswhenparamsarestatic"
    },
    "doc://com.externally.resolved.symbol/s:SS": {
      "abstract": [
        {
          "text": "A Unicode string value that is a collection of characters.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@frozen"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "String"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SS",
      "kind": "symbol",
      "role": "symbol",
      "title": "String",
      "type": "topic",
      "url": "/documentation/Swift/String"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Property-Keys",
      "generated": true,
      "identifiers": [
        "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/kFxPropertyKey_NeedsFullBuffer",
        "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/kFxPropertyKey_VariesWhenParamsAreStatic",
        "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/kFxPropertyKey_ChangesOutputSize"
      ],
      "title": "Property Keys"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": null
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Macro"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "kFxPropertyKey_DesiredProcessingColorInfo"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "macro"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kFxPropertyKey_DesiredProcessingColorInfo"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Property-Keys",
              "generated": true,
              "identifiers": [
                "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/kFxPropertyKey_NeedsFullBuffer",
                "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/kFxPropertyKey_VariesWhenParamsAreStatic",
                "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/kFxPropertyKey_ChangesOutputSize"
              ],
              "title": "Property Keys"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "Unsupported OS: FxPlug"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "#define"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "kFxPropertyKey_DesiredProcessingColorInfo"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.professionalvideoapplications~1documentation~1professional_video_applications~1kFxPropertyKey_DesiredProcessingColorInfo/title",
          "value": "kFxPropertyKey_DesiredProcessingColorInfo"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.professionalvideoapplications~1documentation~1professional_video_applications~1kFxPropertyKey_DesiredProcessingColorInfo/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kFxPropertyKey_DesiredProcessingColorInfo"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.professionalvideoapplications~1documentation~1professional_video_applications~1FxImageColorInfo/title",
          "value": "FxImageColorInfo"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.professionalvideoapplications~1documentation~1professional_video_applications~1FxImageColorInfo/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "FxImageColorInfo"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.professionalvideoapplications~1documentation~1professional_video_applications~1FxImageColorInfo/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "FxImageColorInfo"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.professionalvideoapplications~1documentation~1professional_video_applications~1kFxPropertyKey_NeedsFullBuffer/title",
          "value": "kFxPropertyKey_NeedsFullBuffer"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.professionalvideoapplications~1documentation~1professional_video_applications~1kFxPropertyKey_NeedsFullBuffer/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kFxPropertyKey_NeedsFullBuffer"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.professionalvideoapplications~1documentation~1professional_video_applications~1kFxPropertyKey_VariesWhenParamsAreStatic/title",
          "value": "kFxPropertyKey_VariesWhenParamsAreStatic"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.professionalvideoapplications~1documentation~1professional_video_applications~1kFxPropertyKey_VariesWhenParamsAreStatic/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kFxPropertyKey_VariesWhenParamsAreStatic"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.professionalvideoapplications~1documentation~1professional_video_applications~1kFxPropertyKey_ChangesOutputSize/title",
          "value": "kFxPropertyKey_ChangesOutputSize"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.professionalvideoapplications~1documentation~1professional_video_applications~1kFxPropertyKey_ChangesOutputSize/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kFxPropertyKey_ChangesOutputSize"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/professional_video_applications/kfxpropertykey_desiredprocessingcolorinfo"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/professional_video_applications/kfxpropertykey_desiredprocessingcolorinfo"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
