{
  "abstract": [
    {
      "text": "A key in the ",
      "type": "text"
    },
    {
      "code": "properties",
      "type": "codeVoice"
    },
    {
      "text": " dictionary in the ",
      "type": "text"
    },
    {
      "code": "FXBaseEffect",
      "type": "codeVoice"
    },
    {
      "text": " Class that corresponds to an ",
      "type": "text"
    },
    {
      "code": "NSNumber",
      "type": "codeVoice"
    },
    {
      "text": " containing one of the ",
      "type": "text"
    },
    {
      "code": "FxImage",
      "type": "codeVoice"
    },
    {
      "text": " values.",
      "type": "text"
    }
  ],
  "diffAvailability": {
    "major": {
      "change": "added",
      "platform": "FxPlug",
      "versions": [
        "4.0",
        "4.2.9"
      ]
    }
  },
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/kFxPropertyKey_PixelTransformSupport"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@macro@kFxPropertyKey_PixelTransformSupport",
    "fragments": [
      {
        "kind": "keyword",
        "text": "var"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "kFxPropertyKey_PixelTransformSupport"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "s:SS",
        "text": "String"
      }
    ],
    "modules": [
      {
        "name": "Professional Video Applications"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "kFxPropertyKey_PixelTransformSupport"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "introducedAt": "3.1",
        "name": "FxPlug"
      }
    ],
    "role": "symbol",
    "roleHeading": "Global Variable",
    "symbolKind": "var",
    "title": "kFxPropertyKey_PixelTransformSupport"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "Unsupported OS: FxPlug"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "var"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "kFxPropertyKey_PixelTransformSupport"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:SS",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:SS",
              "text": "String"
            },
            {
              "kind": "text",
              "text": " { "
            },
            {
              "kind": "keyword",
              "text": "get"
            },
            {
              "kind": "text",
              "text": " }"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "kind": "mentions",
      "mentions": [
        "doc://com.apple.professionalvideoapplications/documentation/Professional-Video-Applications/optimizing-fxplug-plug-ins"
      ]
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.professionalvideoapplications/documentation/Professional-Video-Applications/optimizing-fxplug-plug-ins": {
      "abstract": [
        {
          "text": "Maintain consistent rendering at all resolutions and aspect ratios by using pixel transforms.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.professionalvideoapplications/documentation/Professional-Video-Applications/optimizing-fxplug-plug-ins",
      "kind": "article",
      "role": "article",
      "title": "Optimizing FxPlug plug-ins",
      "type": "topic",
      "url": "/documentation/professional-video-applications/optimizing-fxplug-plug-ins"
    },
    "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications": {
      "abstract": [
        {
          "text": "Exchange data with Final Cut Pro, and create effects plug-ins for Final Cut Pro and Motion.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications",
      "kind": "symbol",
      "role": "collection",
      "title": "Professional Video Applications",
      "type": "topic",
      "url": "/documentation/professional_video_applications"
    },
    "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/PluginManagerVersionNumber": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "PluginManagerVersionNumber"
        }
      ],
      "identifier": "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/PluginManagerVersionNumber",
      "kind": "symbol",
      "role": "symbol",
      "title": "PluginManagerVersionNumber",
      "type": "topic",
      "url": "/documentation/professional_video_applications/pluginmanagerversionnumber"
    },
    "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/PluginManagerVersionString": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "PluginManagerVersionString"
        }
      ],
      "identifier": "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/PluginManagerVersionString",
      "kind": "symbol",
      "role": "symbol",
      "title": "PluginManagerVersionString",
      "type": "topic",
      "url": "/documentation/professional_video_applications/pluginmanagerversionstring"
    },
    "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/kFxPropertyKey_DrawsInScreenSpace": {
      "abstract": [
        {
          "text": "Indicates that the filter or generator requires that its output to always be aligned with the camera’s film-back.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kFxPropertyKey_DrawsInScreenSpace"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/kFxPropertyKey_DrawsInScreenSpace",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kFxPropertyKey_DrawsInScreenSpace"
        }
      ],
      "role": "symbol",
      "title": "kFxPropertyKey_DrawsInScreenSpace",
      "type": "topic",
      "url": "/documentation/professional_video_applications/kfxpropertykey_drawsinscreenspace"
    },
    "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/kFxPropertyKey_MayRemapTime": {
      "abstract": [
        {
          "text": "A Boolean value, encoded as an ",
          "type": "text"
        },
        {
          "code": "NSNumber",
          "type": "codeVoice"
        },
        {
          "text": " object, indicating whether or not this plug-in may try to sample its input image(s) at any time other than the output time.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kFxPropertyKey_MayRemapTime"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/kFxPropertyKey_MayRemapTime",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kFxPropertyKey_MayRemapTime"
        }
      ],
      "role": "symbol",
      "title": "kFxPropertyKey_MayRemapTime",
      "type": "topic",
      "url": "/documentation/professional_video_applications/kfxpropertykey_mayremaptime"
    },
    "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/kFxPropertyKey_PixelTransformSupport": {
      "abstract": [
        {
          "text": "A key in the ",
          "type": "text"
        },
        {
          "code": "properties",
          "type": "codeVoice"
        },
        {
          "text": " dictionary in the ",
          "type": "text"
        },
        {
          "code": "FXBaseEffect",
          "type": "codeVoice"
        },
        {
          "text": " Class that corresponds to an ",
          "type": "text"
        },
        {
          "code": "NSNumber",
          "type": "codeVoice"
        },
        {
          "text": " containing one of the ",
          "type": "text"
        },
        {
          "code": "FxImage",
          "type": "codeVoice"
        },
        {
          "text": " values.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kFxPropertyKey_PixelTransformSupport"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/kFxPropertyKey_PixelTransformSupport",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kFxPropertyKey_PixelTransformSupport"
        }
      ],
      "role": "symbol",
      "title": "kFxPropertyKey_PixelTransformSupport",
      "type": "topic",
      "url": "/documentation/professional_video_applications/kfxpropertykey_pixeltransformsupport"
    },
    "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/kFxPropertyKey_UsesNonmatchingTextureLayout": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kFxPropertyKey_UsesNonmatchingTextureLayout"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/kFxPropertyKey_UsesNonmatchingTextureLayout",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kFxPropertyKey_UsesNonmatchingTextureLayout"
        }
      ],
      "role": "symbol",
      "title": "kFxPropertyKey_UsesNonmatchingTextureLayout",
      "type": "topic",
      "url": "/documentation/professional_video_applications/kfxpropertykey_usesnonmatchingtexturelayout"
    },
    "doc://com.externally.resolved.symbol/s:SS": {
      "abstract": [
        {
          "text": "A Unicode string value that is a collection of characters.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@frozen"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "String"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SS",
      "kind": "symbol",
      "role": "symbol",
      "title": "String",
      "type": "topic",
      "url": "/documentation/Swift/String"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Constants",
      "generated": true,
      "identifiers": [
        "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/kFxPropertyKey_DrawsInScreenSpace",
        "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/kFxPropertyKey_MayRemapTime",
        "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/kFxPropertyKey_UsesNonmatchingTextureLayout"
      ],
      "title": "Constants"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": null
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Macro"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "kFxPropertyKey_PixelTransformSupport"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "macro"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kFxPropertyKey_PixelTransformSupport"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Constants",
              "generated": true,
              "identifiers": [
                "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/kFxPropertyKey_DrawsInScreenSpace",
                "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/kFxPropertyKey_MayRemapTime",
                "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/kFxPropertyKey_UsesNonmatchingTextureLayout",
                "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/PluginManagerVersionNumber",
                "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/PluginManagerVersionString"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "Unsupported OS: FxPlug"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "#define"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "kFxPropertyKey_PixelTransformSupport"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.professionalvideoapplications~1documentation~1professional_video_applications~1kFxPropertyKey_MayRemapTime/title",
          "value": "kFxPropertyKey_MayRemapTime"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.professionalvideoapplications~1documentation~1professional_video_applications~1kFxPropertyKey_MayRemapTime/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kFxPropertyKey_MayRemapTime"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.professionalvideoapplications~1documentation~1professional_video_applications~1kFxPropertyKey_PixelTransformSupport/title",
          "value": "kFxPropertyKey_PixelTransformSupport"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.professionalvideoapplications~1documentation~1professional_video_applications~1kFxPropertyKey_PixelTransformSupport/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kFxPropertyKey_PixelTransformSupport"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.professionalvideoapplications~1documentation~1professional_video_applications~1kFxPropertyKey_UsesNonmatchingTextureLayout/title",
          "value": "kFxPropertyKey_UsesNonmatchingTextureLayout"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.professionalvideoapplications~1documentation~1professional_video_applications~1kFxPropertyKey_UsesNonmatchingTextureLayout/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kFxPropertyKey_UsesNonmatchingTextureLayout"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.professionalvideoapplications~1documentation~1professional_video_applications~1kFxPropertyKey_DrawsInScreenSpace/title",
          "value": "kFxPropertyKey_DrawsInScreenSpace"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.professionalvideoapplications~1documentation~1professional_video_applications~1kFxPropertyKey_DrawsInScreenSpace/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kFxPropertyKey_DrawsInScreenSpace"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/professional_video_applications/kfxpropertykey_pixeltransformsupport"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/professional_video_applications/kfxpropertykey_pixeltransformsupport"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
