{
  "abstract": [
    {
      "text": "The key character for Unicode 0x21df.",
      "type": "text"
    }
  ],
  "diffAvailability": {
    "major": {
      "change": "added",
      "platform": "FxPlug",
      "versions": [
        "4.0",
        "4.2.9"
      ]
    }
  },
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/kKeyChar_DownArrow"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@kKeyChar_DownArrow",
    "fragments": [
      {
        "kind": "keyword",
        "text": "var"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "kKeyChar_DownArrow"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@T@unichar",
        "text": "unichar"
      }
    ],
    "modules": [
      {
        "name": "Professional Video Applications"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "kKeyChar_DownArrow"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "introducedAt": "4.1",
        "name": "FxPlug"
      }
    ],
    "role": "symbol",
    "roleHeading": "Global Variable",
    "symbolKind": "var",
    "title": "kKeyChar_DownArrow"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "Unsupported OS: FxPlug"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "var"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "kKeyChar_DownArrow"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/c:@T@unichar",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@unichar",
              "text": "unichar"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications": {
      "abstract": [
        {
          "text": "Exchange data with Final Cut Pro, and create effects plug-ins for Final Cut Pro and Motion.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications",
      "kind": "symbol",
      "role": "collection",
      "title": "Professional Video Applications",
      "type": "topic",
      "url": "/documentation/professional_video_applications"
    },
    "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/kKeyChar_DownArrow": {
      "abstract": [
        {
          "text": "The key character for Unicode 0x21df.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kKeyChar_DownArrow"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@unichar",
          "text": "unichar"
        }
      ],
      "identifier": "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/kKeyChar_DownArrow",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kKeyChar_DownArrow"
        }
      ],
      "role": "symbol",
      "title": "kKeyChar_DownArrow",
      "type": "topic",
      "url": "/documentation/professional_video_applications/kkeychar_downarrow"
    },
    "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/kKeyChar_LeftArrow": {
      "abstract": [
        {
          "text": "The key character for Unicode 0x21e0.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kKeyChar_LeftArrow"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@unichar",
          "text": "unichar"
        }
      ],
      "identifier": "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/kKeyChar_LeftArrow",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kKeyChar_LeftArrow"
        }
      ],
      "role": "symbol",
      "title": "kKeyChar_LeftArrow",
      "type": "topic",
      "url": "/documentation/professional_video_applications/kkeychar_leftarrow"
    },
    "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/kKeyChar_RightArrow": {
      "abstract": [
        {
          "text": "The key character for Unicode 0x21e2.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kKeyChar_RightArrow"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@unichar",
          "text": "unichar"
        }
      ],
      "identifier": "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/kKeyChar_RightArrow",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kKeyChar_RightArrow"
        }
      ],
      "role": "symbol",
      "title": "kKeyChar_RightArrow",
      "type": "topic",
      "url": "/documentation/professional_video_applications/kkeychar_rightarrow"
    },
    "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/kKeyChar_UpArrow": {
      "abstract": [
        {
          "text": "The key character for Unicode 0x21de.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kKeyChar_UpArrow"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@unichar",
          "text": "unichar"
        }
      ],
      "identifier": "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/kKeyChar_UpArrow",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kKeyChar_UpArrow"
        }
      ],
      "role": "symbol",
      "title": "kKeyChar_UpArrow",
      "type": "topic",
      "url": "/documentation/professional_video_applications/kkeychar_uparrow"
    },
    "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/kKey_Character": {
      "abstract": [
        {
          "text": "The character the user must press to invoke the command.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kKey_Character"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/kKey_Character",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kKey_Character"
        }
      ],
      "role": "symbol",
      "title": "kKey_Character",
      "type": "topic",
      "url": "/documentation/professional_video_applications/kkey_character"
    },
    "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/kKey_Command": {
      "abstract": [
        {
          "text": "The FxCommand that will be invoked by this keypress.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kKey_Command"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/kKey_Command",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kKey_Command"
        }
      ],
      "role": "symbol",
      "title": "kKey_Command",
      "type": "topic",
      "url": "/documentation/professional_video_applications/kkey_command"
    },
    "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/kKey_Modifiers": {
      "abstract": [
        {
          "text": "The modifiers the user must include in the keypress to invoke the command.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kKey_Modifiers"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/kKey_Modifiers",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kKey_Modifiers"
        }
      ],
      "role": "symbol",
      "title": "kKey_Modifiers",
      "type": "topic",
      "url": "/documentation/professional_video_applications/kkey_modifiers"
    },
    "doc://com.externally.resolved.symbol/c:@T@unichar": {
      "abstract": [
        {
          "text": "Type for UTF-16 code units.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "typealias "
        },
        {
          "kind": "identifier",
          "text": "unichar"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:@T@unichar",
      "kind": "symbol",
      "role": "symbol",
      "title": "unichar",
      "type": "topic",
      "url": "/documentation/foundation/unichar"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Constants",
      "generated": true,
      "identifiers": [
        "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/kKeyChar_UpArrow",
        "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/kKeyChar_LeftArrow",
        "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/kKeyChar_RightArrow",
        "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/kKey_Command",
        "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/kKey_Character",
        "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/kKey_Modifiers"
      ],
      "title": "Constants"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": null
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Global Variable"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "kKeyChar_DownArrow"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "var"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kKeyChar_DownArrow"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Constants",
              "generated": true,
              "identifiers": [
                "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/kKeyChar_UpArrow",
                "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/kKeyChar_LeftArrow",
                "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/kKeyChar_RightArrow",
                "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/kKey_Command",
                "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/kKey_Character",
                "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/kKey_Modifiers"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "Unsupported OS: FxPlug"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "extern"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:@T@unichar",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@unichar",
                    "text": "unichar"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "kKeyChar_DownArrow"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.professionalvideoapplications~1documentation~1professional_video_applications~1kKey_Command/title",
          "value": "kKey_Command"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.professionalvideoapplications~1documentation~1professional_video_applications~1kKey_Command/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kKey_Command"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.professionalvideoapplications~1documentation~1professional_video_applications~1kKey_Modifiers/title",
          "value": "kKey_Modifiers"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.professionalvideoapplications~1documentation~1professional_video_applications~1kKey_Modifiers/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kKey_Modifiers"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.professionalvideoapplications~1documentation~1professional_video_applications~1kKey_Character/title",
          "value": "kKey_Character"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.professionalvideoapplications~1documentation~1professional_video_applications~1kKey_Character/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kKey_Character"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.professionalvideoapplications~1documentation~1professional_video_applications~1kKeyChar_LeftArrow/title",
          "value": "kKeyChar_LeftArrow"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.professionalvideoapplications~1documentation~1professional_video_applications~1kKeyChar_LeftArrow/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kKeyChar_LeftArrow"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.professionalvideoapplications~1documentation~1professional_video_applications~1kKeyChar_RightArrow/title",
          "value": "kKeyChar_RightArrow"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.professionalvideoapplications~1documentation~1professional_video_applications~1kKeyChar_RightArrow/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kKeyChar_RightArrow"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.professionalvideoapplications~1documentation~1professional_video_applications~1kKeyChar_DownArrow/title",
          "value": "kKeyChar_DownArrow"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.professionalvideoapplications~1documentation~1professional_video_applications~1kKeyChar_DownArrow/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kKeyChar_DownArrow"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.professionalvideoapplications~1documentation~1professional_video_applications~1kKeyChar_UpArrow/title",
          "value": "kKeyChar_UpArrow"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.professionalvideoapplications~1documentation~1professional_video_applications~1kKeyChar_UpArrow/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kKeyChar_UpArrow"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/professional_video_applications/kkeychar_downarrow"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/professional_video_applications/kkeychar_downarrow"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
