{
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "occ",
    "url": "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/PluginManagerVersionString"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@PluginManagerVersionString",
    "fragments": [
      {
        "kind": "identifier",
        "text": "PluginManagerVersionString"
      }
    ],
    "modules": [
      {
        "name": "Professional Video Applications"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "PluginManagerVersionString"
      }
    ],
    "role": "symbol",
    "roleHeading": "Global Variable",
    "symbolKind": "var",
    "title": "PluginManagerVersionString"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "occ"
          ],
          "platforms": [
            "Unsupported OS: PluginManager"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "extern"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "keyword",
              "text": "const"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:c",
              "text": "unsigned char"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "PluginManagerVersionString"
            },
            {
              "kind": "text",
              "text": "[];"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications": {
      "abstract": [
        {
          "text": "Exchange data with Final Cut Pro, and create effects plug-ins for Final Cut Pro and Motion.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications",
      "kind": "symbol",
      "role": "collection",
      "title": "Professional Video Applications",
      "type": "topic",
      "url": "/documentation/professional_video_applications"
    },
    "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/PluginManagerVersionNumber": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "PluginManagerVersionNumber"
        }
      ],
      "identifier": "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/PluginManagerVersionNumber",
      "kind": "symbol",
      "role": "symbol",
      "title": "PluginManagerVersionNumber",
      "type": "topic",
      "url": "/documentation/professional_video_applications/pluginmanagerversionnumber"
    },
    "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/PluginManagerVersionString": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "PluginManagerVersionString"
        }
      ],
      "identifier": "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/PluginManagerVersionString",
      "kind": "symbol",
      "role": "symbol",
      "title": "PluginManagerVersionString",
      "type": "topic",
      "url": "/documentation/professional_video_applications/pluginmanagerversionstring"
    },
    "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/kFxPropertyKey_DrawsInScreenSpace": {
      "abstract": [
        {
          "text": "Indicates that the filter or generator requires that its output to always be aligned with the camera’s film-back.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kFxPropertyKey_DrawsInScreenSpace"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/kFxPropertyKey_DrawsInScreenSpace",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kFxPropertyKey_DrawsInScreenSpace"
        }
      ],
      "role": "symbol",
      "title": "kFxPropertyKey_DrawsInScreenSpace",
      "type": "topic",
      "url": "/documentation/professional_video_applications/kfxpropertykey_drawsinscreenspace"
    },
    "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/kFxPropertyKey_MayRemapTime": {
      "abstract": [
        {
          "text": "A Boolean value, encoded as an ",
          "type": "text"
        },
        {
          "code": "NSNumber",
          "type": "codeVoice"
        },
        {
          "text": " object, indicating whether or not this plug-in may try to sample its input image(s) at any time other than the output time.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kFxPropertyKey_MayRemapTime"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/kFxPropertyKey_MayRemapTime",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kFxPropertyKey_MayRemapTime"
        }
      ],
      "role": "symbol",
      "title": "kFxPropertyKey_MayRemapTime",
      "type": "topic",
      "url": "/documentation/professional_video_applications/kfxpropertykey_mayremaptime"
    },
    "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/kFxPropertyKey_PixelTransformSupport": {
      "abstract": [
        {
          "text": "A key in the ",
          "type": "text"
        },
        {
          "code": "properties",
          "type": "codeVoice"
        },
        {
          "text": " dictionary in the ",
          "type": "text"
        },
        {
          "code": "FXBaseEffect",
          "type": "codeVoice"
        },
        {
          "text": " Class that corresponds to an ",
          "type": "text"
        },
        {
          "code": "NSNumber",
          "type": "codeVoice"
        },
        {
          "text": " containing one of the ",
          "type": "text"
        },
        {
          "code": "FxImage",
          "type": "codeVoice"
        },
        {
          "text": " values.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kFxPropertyKey_PixelTransformSupport"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/kFxPropertyKey_PixelTransformSupport",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kFxPropertyKey_PixelTransformSupport"
        }
      ],
      "role": "symbol",
      "title": "kFxPropertyKey_PixelTransformSupport",
      "type": "topic",
      "url": "/documentation/professional_video_applications/kfxpropertykey_pixeltransformsupport"
    },
    "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/kFxPropertyKey_UsesNonmatchingTextureLayout": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kFxPropertyKey_UsesNonmatchingTextureLayout"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/kFxPropertyKey_UsesNonmatchingTextureLayout",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kFxPropertyKey_UsesNonmatchingTextureLayout"
        }
      ],
      "role": "symbol",
      "title": "kFxPropertyKey_UsesNonmatchingTextureLayout",
      "type": "topic",
      "url": "/documentation/professional_video_applications/kfxpropertykey_usesnonmatchingtexturelayout"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Constants",
      "generated": true,
      "identifiers": [
        "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/kFxPropertyKey_DrawsInScreenSpace",
        "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/kFxPropertyKey_MayRemapTime",
        "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/kFxPropertyKey_PixelTransformSupport",
        "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/kFxPropertyKey_UsesNonmatchingTextureLayout",
        "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/PluginManagerVersionNumber"
      ],
      "title": "Constants"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.professionalvideoapplications~1documentation~1professional_video_applications~1kFxPropertyKey_MayRemapTime/title",
          "value": "kFxPropertyKey_MayRemapTime"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.professionalvideoapplications~1documentation~1professional_video_applications~1kFxPropertyKey_MayRemapTime/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kFxPropertyKey_MayRemapTime"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.professionalvideoapplications~1documentation~1professional_video_applications~1kFxPropertyKey_DrawsInScreenSpace/title",
          "value": "kFxPropertyKey_DrawsInScreenSpace"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.professionalvideoapplications~1documentation~1professional_video_applications~1kFxPropertyKey_DrawsInScreenSpace/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kFxPropertyKey_DrawsInScreenSpace"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.professionalvideoapplications~1documentation~1professional_video_applications~1kFxPropertyKey_UsesNonmatchingTextureLayout/title",
          "value": "kFxPropertyKey_UsesNonmatchingTextureLayout"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.professionalvideoapplications~1documentation~1professional_video_applications~1kFxPropertyKey_UsesNonmatchingTextureLayout/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kFxPropertyKey_UsesNonmatchingTextureLayout"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.professionalvideoapplications~1documentation~1professional_video_applications~1kFxPropertyKey_PixelTransformSupport/title",
          "value": "kFxPropertyKey_PixelTransformSupport"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.professionalvideoapplications~1documentation~1professional_video_applications~1kFxPropertyKey_PixelTransformSupport/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kFxPropertyKey_PixelTransformSupport"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/professional_video_applications/pluginmanagerversionstring"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
