{
  "abstract": [
    {
      "text": "Describes the relationship of an asset resource to its owning asset.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.photokit/documentation/Photos"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.photokit/documentation/Photos/PHAssetResourceType"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@PHAssetResourceType",
    "fragments": [
      {
        "kind": "keyword",
        "text": "enum"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "PHAssetResourceType"
      }
    ],
    "modules": [
      {
        "name": "Photos"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "PHAssetResourceType"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "9.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "9.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.1",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.11",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.0",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Enumeration",
    "symbolKind": "enum",
    "title": "PHAssetResourceType"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "enum"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "PHAssetResourceType"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.photokit/documentation/Photos": {
      "abstract": [
        {
          "text": "Work with image and video assets that the Photos app manages, including those from iCloud Photos and Live Photos.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.photokit/documentation/Photos",
      "kind": "symbol",
      "role": "collection",
      "title": "Photos",
      "type": "topic",
      "url": "/documentation/photos"
    },
    "doc://com.apple.photokit/documentation/Photos/PHAssetResource/assetLocalIdentifier": {
      "abstract": [
        {
          "text": "The unique identifier the system associates for a local asset object.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "assetLocalIdentifier"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.photokit/documentation/Photos/PHAssetResource/assetLocalIdentifier",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "assetLocalIdentifier"
        }
      ],
      "role": "symbol",
      "title": "assetLocalIdentifier",
      "type": "topic",
      "url": "/documentation/photos/phassetresource/assetlocalidentifier"
    },
    "doc://com.apple.photokit/documentation/Photos/PHAssetResource/originalFilename": {
      "abstract": [
        {
          "text": "The original filename of the asset resource from when it was created or imported.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "originalFilename"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.photokit/documentation/Photos/PHAssetResource/originalFilename",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "originalFilename"
        }
      ],
      "role": "symbol",
      "title": "originalFilename",
      "type": "topic",
      "url": "/documentation/photos/phassetresource/originalfilename"
    },
    "doc://com.apple.photokit/documentation/Photos/PHAssetResource/pixelHeight": {
      "abstract": [
        {
          "text": "The height of the resource, in pixels.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "pixelHeight"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.photokit/documentation/Photos/PHAssetResource/pixelHeight",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "pixelHeight"
        }
      ],
      "role": "symbol",
      "title": "pixelHeight",
      "type": "topic",
      "url": "/documentation/photos/phassetresource/pixelheight"
    },
    "doc://com.apple.photokit/documentation/Photos/PHAssetResource/pixelWidth": {
      "abstract": [
        {
          "text": "The width of the resource, in pixels.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "pixelWidth"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.photokit/documentation/Photos/PHAssetResource/pixelWidth",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "pixelWidth"
        }
      ],
      "role": "symbol",
      "title": "pixelWidth",
      "type": "topic",
      "url": "/documentation/photos/phassetresource/pixelwidth"
    },
    "doc://com.apple.photokit/documentation/Photos/PHAssetResource/type": {
      "abstract": [
        {
          "text": "The relationship of an asset resource to its owning asset.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "type"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@PHAssetResourceType",
          "text": "PHAssetResourceType"
        }
      ],
      "identifier": "doc://com.apple.photokit/documentation/Photos/PHAssetResource/type",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "type"
        }
      ],
      "role": "symbol",
      "title": "type",
      "type": "topic",
      "url": "/documentation/photos/phassetresource/type"
    },
    "doc://com.apple.photokit/documentation/Photos/PHAssetResource/uniformTypeIdentifier": {
      "abstract": [
        {
          "text": "The uniform type identifier for the asset resource’s image or video data.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "uniformTypeIdentifier"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.photokit/documentation/Photos/PHAssetResource/uniformTypeIdentifier",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "uniformTypeIdentifier"
        }
      ],
      "role": "symbol",
      "title": "uniformTypeIdentifier",
      "type": "topic",
      "url": "/documentation/photos/phassetresource/uniformtypeidentifier"
    },
    "doc://com.apple.photokit/documentation/Photos/PHAssetResourceType": {
      "abstract": [
        {
          "text": "Describes the relationship of an asset resource to its owning asset.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "PHAssetResourceType"
        }
      ],
      "identifier": "doc://com.apple.photokit/documentation/Photos/PHAssetResourceType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PHAssetResourceType"
        }
      ],
      "role": "symbol",
      "title": "PHAssetResourceType",
      "type": "topic",
      "url": "/documentation/photos/phassetresourcetype"
    },
    "doc://com.apple.photokit/documentation/Photos/PHAssetResourceType/adjustmentBasePairedVideo": {
      "abstract": [
        {
          "text": "Provides an unaltered version of the video data for a Live Photo asset for use in reconstructing recent edits.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "adjustmentBasePairedVideo"
        }
      ],
      "identifier": "doc://com.apple.photokit/documentation/Photos/PHAssetResourceType/adjustmentBasePairedVideo",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PHAssetResourceTypeAdjustmentBasePairedVideo"
        }
      ],
      "role": "symbol",
      "title": "PHAssetResourceType.adjustmentBasePairedVideo",
      "type": "topic",
      "url": "/documentation/photos/phassetresourcetype/adjustmentbasepairedvideo"
    },
    "doc://com.apple.photokit/documentation/Photos/PHAssetResourceType/adjustmentBasePhoto": {
      "abstract": [
        {
          "text": "Provides an unaltered version of its photo asset for use in for use in reconstructing recent edits.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "adjustmentBasePhoto"
        }
      ],
      "identifier": "doc://com.apple.photokit/documentation/Photos/PHAssetResourceType/adjustmentBasePhoto",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PHAssetResourceTypeAdjustmentBasePhoto"
        }
      ],
      "role": "symbol",
      "title": "PHAssetResourceType.adjustmentBasePhoto",
      "type": "topic",
      "url": "/documentation/photos/phassetresourcetype/adjustmentbasephoto"
    },
    "doc://com.apple.photokit/documentation/Photos/PHAssetResourceType/adjustmentBaseVideo": {
      "abstract": [
        {
          "text": "Provides an unaltered version of its video asset.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "adjustmentBaseVideo"
        }
      ],
      "identifier": "doc://com.apple.photokit/documentation/Photos/PHAssetResourceType/adjustmentBaseVideo",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PHAssetResourceTypeAdjustmentBaseVideo"
        }
      ],
      "role": "symbol",
      "title": "PHAssetResourceType.adjustmentBaseVideo",
      "type": "topic",
      "url": "/documentation/photos/phassetresourcetype/adjustmentbasevideo"
    },
    "doc://com.apple.photokit/documentation/Photos/PHAssetResourceType/adjustmentData": {
      "abstract": [
        {
          "text": "Provides data for use in reconstructing recent edits to its asset.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "adjustmentData"
        }
      ],
      "identifier": "doc://com.apple.photokit/documentation/Photos/PHAssetResourceType/adjustmentData",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PHAssetResourceTypeAdjustmentData"
        }
      ],
      "role": "symbol",
      "title": "PHAssetResourceType.adjustmentData",
      "type": "topic",
      "url": "/documentation/photos/phassetresourcetype/adjustmentdata"
    },
    "doc://com.apple.photokit/documentation/Photos/PHAssetResourceType/alternatePhoto": {
      "abstract": [
        {
          "text": "Provides photo data that isn’t the primary form of its asset.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "alternatePhoto"
        }
      ],
      "identifier": "doc://com.apple.photokit/documentation/Photos/PHAssetResourceType/alternatePhoto",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PHAssetResourceTypeAlternatePhoto"
        }
      ],
      "role": "symbol",
      "title": "PHAssetResourceType.alternatePhoto",
      "type": "topic",
      "url": "/documentation/photos/phassetresourcetype/alternatephoto"
    },
    "doc://com.apple.photokit/documentation/Photos/PHAssetResourceType/audio": {
      "abstract": [
        {
          "text": "Provides the original audio data for its asset.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "audio"
        }
      ],
      "identifier": "doc://com.apple.photokit/documentation/Photos/PHAssetResourceType/audio",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PHAssetResourceTypeAudio"
        }
      ],
      "role": "symbol",
      "title": "PHAssetResourceType.audio",
      "type": "topic",
      "url": "/documentation/photos/phassetresourcetype/audio"
    },
    "doc://com.apple.photokit/documentation/Photos/PHAssetResourceType/fullSizePairedVideo": {
      "abstract": [
        {
          "text": "Provides the current video data component of a Live Photo asset.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "fullSizePairedVideo"
        }
      ],
      "identifier": "doc://com.apple.photokit/documentation/Photos/PHAssetResourceType/fullSizePairedVideo",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PHAssetResourceTypeFullSizePairedVideo"
        }
      ],
      "role": "symbol",
      "title": "PHAssetResourceType.fullSizePairedVideo",
      "type": "topic",
      "url": "/documentation/photos/phassetresourcetype/fullsizepairedvideo"
    },
    "doc://com.apple.photokit/documentation/Photos/PHAssetResourceType/fullSizePhoto": {
      "abstract": [
        {
          "text": "Provides a modified version of the original photo asset.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "fullSizePhoto"
        }
      ],
      "identifier": "doc://com.apple.photokit/documentation/Photos/PHAssetResourceType/fullSizePhoto",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PHAssetResourceTypeFullSizePhoto"
        }
      ],
      "role": "symbol",
      "title": "PHAssetResourceType.fullSizePhoto",
      "type": "topic",
      "url": "/documentation/photos/phassetresourcetype/fullsizephoto"
    },
    "doc://com.apple.photokit/documentation/Photos/PHAssetResourceType/fullSizeVideo": {
      "abstract": [
        {
          "text": "Provides a modified version of the original video asset.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "fullSizeVideo"
        }
      ],
      "identifier": "doc://com.apple.photokit/documentation/Photos/PHAssetResourceType/fullSizeVideo",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PHAssetResourceTypeFullSizeVideo"
        }
      ],
      "role": "symbol",
      "title": "PHAssetResourceType.fullSizeVideo",
      "type": "topic",
      "url": "/documentation/photos/phassetresourcetype/fullsizevideo"
    },
    "doc://com.apple.photokit/documentation/Photos/PHAssetResourceType/init(rawValue:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "?("
        },
        {
          "kind": "externalParam",
          "text": "rawValue"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.photokit/documentation/Photos/PHAssetResourceType/init(rawValue:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "init(rawValue:)",
      "type": "topic",
      "url": "/documentation/photos/phassetresourcetype/init(rawvalue:)"
    },
    "doc://com.apple.photokit/documentation/Photos/PHAssetResourceType/pairedVideo": {
      "abstract": [
        {
          "text": "Provides the original video data component of a Live Photo asset.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "pairedVideo"
        }
      ],
      "identifier": "doc://com.apple.photokit/documentation/Photos/PHAssetResourceType/pairedVideo",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PHAssetResourceTypePairedVideo"
        }
      ],
      "role": "symbol",
      "title": "PHAssetResourceType.pairedVideo",
      "type": "topic",
      "url": "/documentation/photos/phassetresourcetype/pairedvideo"
    },
    "doc://com.apple.photokit/documentation/Photos/PHAssetResourceType/photo": {
      "abstract": [
        {
          "text": "Provides the original photo data for its asset.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "photo"
        }
      ],
      "identifier": "doc://com.apple.photokit/documentation/Photos/PHAssetResourceType/photo",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PHAssetResourceTypePhoto"
        }
      ],
      "role": "symbol",
      "title": "PHAssetResourceType.photo",
      "type": "topic",
      "url": "/documentation/photos/phassetresourcetype/photo"
    },
    "doc://com.apple.photokit/documentation/Photos/PHAssetResourceType/photoProxy": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "photoProxy"
        }
      ],
      "identifier": "doc://com.apple.photokit/documentation/Photos/PHAssetResourceType/photoProxy",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PHAssetResourceTypePhotoProxy"
        }
      ],
      "role": "symbol",
      "title": "PHAssetResourceType.photoProxy",
      "type": "topic",
      "url": "/documentation/photos/phassetresourcetype/photoproxy"
    },
    "doc://com.apple.photokit/documentation/Photos/PHAssetResourceType/video": {
      "abstract": [
        {
          "text": "Provides the original video data for its asset.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "video"
        }
      ],
      "identifier": "doc://com.apple.photokit/documentation/Photos/PHAssetResourceType/video",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PHAssetResourceTypeVideo"
        }
      ],
      "role": "symbol",
      "title": "PHAssetResourceType.video",
      "type": "topic",
      "url": "/documentation/photos/phassetresourcetype/video"
    },
    "doc://com.externally.resolved.symbol/c:@T@NSInteger": {
      "abstract": [
        {
          "text": "Describes an integer.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "typealias "
        },
        {
          "kind": "identifier",
          "text": "NSInteger"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:@T@NSInteger",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSInteger",
      "type": "topic",
      "url": "/documentation/objectivec/nsinteger"
    },
    "doc://com.externally.resolved.symbol/s:SH": {
      "abstract": [
        {
          "text": "A type that can be hashed into a `Hasher` to produce an integer hash value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Hashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SQ",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SH",
      "kind": "symbol",
      "role": "symbol",
      "title": "Hashable",
      "type": "topic",
      "url": "/documentation/Swift/Hashable"
    },
    "doc://com.externally.resolved.symbol/s:SQ": {
      "abstract": [
        {
          "text": "A type that can be compared for value equality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SQ",
      "kind": "symbol",
      "role": "symbol",
      "title": "Equatable",
      "type": "topic",
      "url": "/documentation/Swift/Equatable"
    },
    "doc://com.externally.resolved.symbol/s:SY": {
      "abstract": [
        {
          "text": "A type that can be converted to and from an associated raw value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "RawRepresentable"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SY8RawValueQa",
          "text": "RawValue"
        },
        {
          "kind": "text",
          "text": ">"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SY",
      "kind": "symbol",
      "role": "symbol",
      "title": "RawRepresentable",
      "type": "topic",
      "url": "/documentation/Swift/RawRepresentable"
    },
    "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BitwiseCopyable"
        },
        {
          "kind": "text",
          "text": " : ~Escapable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "BitwiseCopyable",
      "type": "topic",
      "url": "/documentation/Swift/BitwiseCopyable"
    },
    "doc://com.externally.resolved.symbol/s:s8SendableP": {
      "abstract": [
        {
          "text": "A thread-safe type whose values can be shared across arbitrary concurrent contexts without introducing a risk of data races.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Sendable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s8SendableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "Sendable",
      "type": "topic",
      "url": "/documentation/Swift/Sendable"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
        "doc://com.externally.resolved.symbol/s:SQ",
        "doc://com.externally.resolved.symbol/s:SH",
        "doc://com.externally.resolved.symbol/s:SY",
        "doc://com.externally.resolved.symbol/s:s8SendableP"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Inspecting-an-Asset-Resource",
      "generated": true,
      "identifiers": [
        "doc://com.apple.photokit/documentation/Photos/PHAssetResource/type",
        "doc://com.apple.photokit/documentation/Photos/PHAssetResource/assetLocalIdentifier",
        "doc://com.apple.photokit/documentation/Photos/PHAssetResource/uniformTypeIdentifier",
        "doc://com.apple.photokit/documentation/Photos/PHAssetResource/originalFilename",
        "doc://com.apple.photokit/documentation/Photos/PHAssetResource/pixelHeight",
        "doc://com.apple.photokit/documentation/Photos/PHAssetResource/pixelWidth"
      ],
      "title": "Inspecting an Asset Resource"
    }
  ],
  "topicSections": [
    {
      "anchor": "Resource-Types",
      "identifiers": [
        "doc://com.apple.photokit/documentation/Photos/PHAssetResourceType/photo",
        "doc://com.apple.photokit/documentation/Photos/PHAssetResourceType/video",
        "doc://com.apple.photokit/documentation/Photos/PHAssetResourceType/audio",
        "doc://com.apple.photokit/documentation/Photos/PHAssetResourceType/alternatePhoto",
        "doc://com.apple.photokit/documentation/Photos/PHAssetResourceType/fullSizePhoto",
        "doc://com.apple.photokit/documentation/Photos/PHAssetResourceType/fullSizeVideo",
        "doc://com.apple.photokit/documentation/Photos/PHAssetResourceType/adjustmentData",
        "doc://com.apple.photokit/documentation/Photos/PHAssetResourceType/adjustmentBasePhoto",
        "doc://com.apple.photokit/documentation/Photos/PHAssetResourceType/pairedVideo",
        "doc://com.apple.photokit/documentation/Photos/PHAssetResourceType/fullSizePairedVideo",
        "doc://com.apple.photokit/documentation/Photos/PHAssetResourceType/adjustmentBaseVideo",
        "doc://com.apple.photokit/documentation/Photos/PHAssetResourceType/adjustmentBasePairedVideo"
      ],
      "title": "Resource Types"
    },
    {
      "anchor": "Enumeration-Cases",
      "generated": true,
      "identifiers": [
        "doc://com.apple.photokit/documentation/Photos/PHAssetResourceType/photoProxy"
      ],
      "title": "Enumeration Cases"
    },
    {
      "anchor": "Initializers",
      "generated": true,
      "identifiers": [
        "doc://com.apple.photokit/documentation/Photos/PHAssetResourceType/init(rawValue:)"
      ],
      "title": "Initializers"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "9.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "9.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.1",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.11",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.0",
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "PHAssetResourceType"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "enum"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PHAssetResourceType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "PHAssetResourceType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.photokit/documentation/Photos"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Resource-Types",
              "identifiers": [
                "doc://com.apple.photokit/documentation/Photos/PHAssetResourceType/photo",
                "doc://com.apple.photokit/documentation/Photos/PHAssetResourceType/video",
                "doc://com.apple.photokit/documentation/Photos/PHAssetResourceType/audio",
                "doc://com.apple.photokit/documentation/Photos/PHAssetResourceType/alternatePhoto",
                "doc://com.apple.photokit/documentation/Photos/PHAssetResourceType/fullSizePhoto",
                "doc://com.apple.photokit/documentation/Photos/PHAssetResourceType/fullSizeVideo",
                "doc://com.apple.photokit/documentation/Photos/PHAssetResourceType/adjustmentData",
                "doc://com.apple.photokit/documentation/Photos/PHAssetResourceType/adjustmentBasePhoto",
                "doc://com.apple.photokit/documentation/Photos/PHAssetResourceType/pairedVideo",
                "doc://com.apple.photokit/documentation/Photos/PHAssetResourceType/fullSizePairedVideo",
                "doc://com.apple.photokit/documentation/Photos/PHAssetResourceType/adjustmentBaseVideo",
                "doc://com.apple.photokit/documentation/Photos/PHAssetResourceType/adjustmentBasePairedVideo"
              ],
              "title": "Resource Types"
            },
            {
              "anchor": "Enumeration-Cases",
              "generated": true,
              "identifiers": [
                "doc://com.apple.photokit/documentation/Photos/PHAssetResourceType/photoProxy"
              ],
              "title": "Enumeration Cases"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Inspecting-an-Asset-Resource",
              "generated": true,
              "identifiers": [
                "doc://com.apple.photokit/documentation/Photos/PHAssetResource/type",
                "doc://com.apple.photokit/documentation/Photos/PHAssetResource/assetLocalIdentifier",
                "doc://com.apple.photokit/documentation/Photos/PHAssetResource/uniformTypeIdentifier",
                "doc://com.apple.photokit/documentation/Photos/PHAssetResource/originalFilename",
                "doc://com.apple.photokit/documentation/Photos/PHAssetResource/pixelHeight",
                "doc://com.apple.photokit/documentation/Photos/PHAssetResource/pixelWidth"
              ],
              "title": "Inspecting an Asset Resource"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "enum"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "PHAssetResourceType"
                  },
                  {
                    "kind": "text",
                    "text": " : "
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:@T@NSInteger",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@NSInteger",
                    "text": "NSInteger"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHAssetResourceType~1adjustmentBasePhoto/title",
          "value": "PHAssetResourceTypeAdjustmentBasePhoto"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHAssetResourceType~1adjustmentBasePhoto/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PHAssetResourceTypeAdjustmentBasePhoto"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHAssetResource~1pixelHeight/title",
          "value": "pixelHeight"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHAssetResource~1pixelHeight/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "pixelHeight"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHAssetResource~1uniformTypeIdentifier/title",
          "value": "uniformTypeIdentifier"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHAssetResource~1uniformTypeIdentifier/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "uniformTypeIdentifier"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHAssetResourceType~1adjustmentBaseVideo/title",
          "value": "PHAssetResourceTypeAdjustmentBaseVideo"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHAssetResourceType~1adjustmentBaseVideo/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PHAssetResourceTypeAdjustmentBaseVideo"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHAssetResourceType~1fullSizePairedVideo/title",
          "value": "PHAssetResourceTypeFullSizePairedVideo"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHAssetResourceType~1fullSizePairedVideo/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PHAssetResourceTypeFullSizePairedVideo"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHAssetResource~1type/title",
          "value": "type"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHAssetResource~1type/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "type"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHAssetResourceType/title",
          "value": "PHAssetResourceType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHAssetResourceType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PHAssetResourceType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHAssetResourceType/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "PHAssetResourceType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHAssetResource~1assetLocalIdentifier/title",
          "value": "assetLocalIdentifier"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHAssetResource~1assetLocalIdentifier/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "assetLocalIdentifier"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHAssetResourceType~1photoProxy/title",
          "value": "PHAssetResourceTypePhotoProxy"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHAssetResourceType~1photoProxy/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PHAssetResourceTypePhotoProxy"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHAssetResource~1pixelWidth/title",
          "value": "pixelWidth"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHAssetResource~1pixelWidth/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "pixelWidth"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHAssetResourceType~1adjustmentData/title",
          "value": "PHAssetResourceTypeAdjustmentData"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHAssetResourceType~1adjustmentData/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PHAssetResourceTypeAdjustmentData"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHAssetResourceType~1photo/title",
          "value": "PHAssetResourceTypePhoto"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHAssetResourceType~1photo/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PHAssetResourceTypePhoto"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHAssetResourceType~1fullSizeVideo/title",
          "value": "PHAssetResourceTypeFullSizeVideo"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHAssetResourceType~1fullSizeVideo/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PHAssetResourceTypeFullSizeVideo"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHAssetResourceType~1adjustmentBasePairedVideo/title",
          "value": "PHAssetResourceTypeAdjustmentBasePairedVideo"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHAssetResourceType~1adjustmentBasePairedVideo/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PHAssetResourceTypeAdjustmentBasePairedVideo"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHAssetResourceType~1fullSizePhoto/title",
          "value": "PHAssetResourceTypeFullSizePhoto"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHAssetResourceType~1fullSizePhoto/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PHAssetResourceTypeFullSizePhoto"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHAssetResource~1originalFilename/title",
          "value": "originalFilename"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHAssetResource~1originalFilename/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "originalFilename"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHAssetResourceType~1pairedVideo/title",
          "value": "PHAssetResourceTypePairedVideo"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHAssetResourceType~1pairedVideo/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PHAssetResourceTypePairedVideo"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHAssetResourceType~1audio/title",
          "value": "PHAssetResourceTypeAudio"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHAssetResourceType~1audio/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PHAssetResourceTypeAudio"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHAssetResourceType~1video/title",
          "value": "PHAssetResourceTypeVideo"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHAssetResourceType~1video/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PHAssetResourceTypeVideo"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHAssetResourceType~1alternatePhoto/title",
          "value": "PHAssetResourceTypeAlternatePhoto"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHAssetResourceType~1alternatePhoto/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PHAssetResourceTypeAlternatePhoto"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/photos/phassetresourcetype"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/photos/phassetresourcetype"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
