{
  "abstract": [
    {
      "text": "Minor distinctions between kinds of asset collections, used by the ",
      "type": "text"
    },
    {
      "identifier": "doc://com.apple.photokit/documentation/Photos/PHAssetCollection/assetCollectionSubtype",
      "isActive": true,
      "type": "reference"
    },
    {
      "text": " property and the ",
      "type": "text"
    },
    {
      "identifier": "doc://com.apple.photokit/documentation/Photos/PHAssetCollection/fetchAssetCollections(with:subtype:options:)",
      "isActive": true,
      "type": "reference"
    },
    {
      "text": " method.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.photokit/documentation/Photos"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.photokit/documentation/Photos/PHAssetCollectionSubtype"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@PHAssetCollectionSubtype",
    "fragments": [
      {
        "kind": "keyword",
        "text": "enum"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "PHAssetCollectionSubtype"
      }
    ],
    "modules": [
      {
        "name": "Photos"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "PHAssetCollectionSubtype"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "8.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "8.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.1",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.11",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.0",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Enumeration",
    "symbolKind": "enum",
    "title": "PHAssetCollectionSubtype"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "enum"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "PHAssetCollectionSubtype"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.photokit/documentation/Photos": {
      "abstract": [
        {
          "text": "Work with image and video assets that the Photos app manages, including those from iCloud Photos and Live Photos.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.photokit/documentation/Photos",
      "kind": "symbol",
      "role": "collection",
      "title": "Photos",
      "type": "topic",
      "url": "/documentation/photos"
    },
    "doc://com.apple.photokit/documentation/Photos/PHAssetCollection/approximateLocation": {
      "abstract": [
        {
          "text": "A location representing those of all assets in the collection.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "approximateLocation"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)CLLocation",
          "text": "CLLocation"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.photokit/documentation/Photos/PHAssetCollection/approximateLocation",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "approximateLocation"
        }
      ],
      "role": "symbol",
      "title": "approximateLocation",
      "type": "topic",
      "url": "/documentation/photos/phassetcollection/approximatelocation"
    },
    "doc://com.apple.photokit/documentation/Photos/PHAssetCollection/assetCollectionSubtype": {
      "abstract": [
        {
          "text": "The subtype of the asset collection.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "assetCollectionSubtype"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@PHAssetCollectionSubtype",
          "text": "PHAssetCollectionSubtype"
        }
      ],
      "identifier": "doc://com.apple.photokit/documentation/Photos/PHAssetCollection/assetCollectionSubtype",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "assetCollectionSubtype"
        }
      ],
      "role": "symbol",
      "title": "assetCollectionSubtype",
      "type": "topic",
      "url": "/documentation/photos/phassetcollection/assetcollectionsubtype"
    },
    "doc://com.apple.photokit/documentation/Photos/PHAssetCollection/assetCollectionType": {
      "abstract": [
        {
          "text": "The type of the asset collection, such as an album or a moment.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "assetCollectionType"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@PHAssetCollectionType",
          "text": "PHAssetCollectionType"
        }
      ],
      "identifier": "doc://com.apple.photokit/documentation/Photos/PHAssetCollection/assetCollectionType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "assetCollectionType"
        }
      ],
      "role": "symbol",
      "title": "assetCollectionType",
      "type": "topic",
      "url": "/documentation/photos/phassetcollection/assetcollectiontype"
    },
    "doc://com.apple.photokit/documentation/Photos/PHAssetCollection/endDate": {
      "abstract": [
        {
          "text": "The latest creation date among all assets in the asset collection.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "endDate"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10Foundation4DateV",
          "text": "Date"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.photokit/documentation/Photos/PHAssetCollection/endDate",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "endDate"
        }
      ],
      "role": "symbol",
      "title": "endDate",
      "type": "topic",
      "url": "/documentation/photos/phassetcollection/enddate"
    },
    "doc://com.apple.photokit/documentation/Photos/PHAssetCollection/estimatedAssetCount": {
      "abstract": [
        {
          "text": "The estimated number of assets in the asset collection.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "estimatedAssetCount"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.photokit/documentation/Photos/PHAssetCollection/estimatedAssetCount",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "estimatedAssetCount"
        }
      ],
      "role": "symbol",
      "title": "estimatedAssetCount",
      "type": "topic",
      "url": "/documentation/photos/phassetcollection/estimatedassetcount"
    },
    "doc://com.apple.photokit/documentation/Photos/PHAssetCollection/fetchAssetCollections(with:subtype:options:)": {
      "abstract": [
        {
          "text": "Retrieves asset collections of the specified type and subtype.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "fetchAssetCollections"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "with"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@PHAssetCollectionType",
          "text": "PHAssetCollectionType"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "subtype"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@PHAssetCollectionSubtype",
          "text": "PHAssetCollectionSubtype"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "options"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)PHFetchOptions",
          "text": "PHFetchOptions"
        },
        {
          "kind": "text",
          "text": "?) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)PHFetchResult",
          "text": "PHFetchResult"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)PHAssetCollection",
          "text": "PHAssetCollection"
        },
        {
          "kind": "text",
          "text": ">"
        }
      ],
      "identifier": "doc://com.apple.photokit/documentation/Photos/PHAssetCollection/fetchAssetCollections(with:subtype:options:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "fetchAssetCollectionsWithType:subtype:options:"
        }
      ],
      "role": "symbol",
      "title": "fetchAssetCollections(with:subtype:options:)",
      "type": "topic",
      "url": "/documentation/photos/phassetcollection/fetchassetcollections(with:subtype:options:)"
    },
    "doc://com.apple.photokit/documentation/Photos/PHAssetCollection/fetchAssetCollectionsContaining(_:with:options:)": {
      "abstract": [
        {
          "text": "Retrieves asset collections of the specified type containing the specified asset.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "fetchAssetCollectionsContaining"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)PHAsset",
          "text": "PHAsset"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "with"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@PHAssetCollectionType",
          "text": "PHAssetCollectionType"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "options"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)PHFetchOptions",
          "text": "PHFetchOptions"
        },
        {
          "kind": "text",
          "text": "?) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)PHFetchResult",
          "text": "PHFetchResult"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)PHAssetCollection",
          "text": "PHAssetCollection"
        },
        {
          "kind": "text",
          "text": ">"
        }
      ],
      "identifier": "doc://com.apple.photokit/documentation/Photos/PHAssetCollection/fetchAssetCollectionsContaining(_:with:options:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "fetchAssetCollectionsContainingAsset:withType:options:"
        }
      ],
      "role": "symbol",
      "title": "fetchAssetCollectionsContaining(_:with:options:)",
      "type": "topic",
      "url": "/documentation/photos/phassetcollection/fetchassetcollectionscontaining(_:with:options:)"
    },
    "doc://com.apple.photokit/documentation/Photos/PHAssetCollection/localizedLocationNames": {
      "abstract": [
        {
          "text": "The names of locations grouped by the collection (an array of ",
          "type": "text"
        },
        {
          "code": "NSString",
          "type": "codeVoice"
        },
        {
          "text": " objects).",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "localizedLocationNames"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": "]"
        }
      ],
      "identifier": "doc://com.apple.photokit/documentation/Photos/PHAssetCollection/localizedLocationNames",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "localizedLocationNames"
        }
      ],
      "role": "symbol",
      "title": "localizedLocationNames",
      "type": "topic",
      "url": "/documentation/photos/phassetcollection/localizedlocationnames"
    },
    "doc://com.apple.photokit/documentation/Photos/PHAssetCollection/startDate": {
      "abstract": [
        {
          "text": "The earliest creation date among all assets in the asset collection.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "startDate"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10Foundation4DateV",
          "text": "Date"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.photokit/documentation/Photos/PHAssetCollection/startDate",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "startDate"
        }
      ],
      "role": "symbol",
      "title": "startDate",
      "type": "topic",
      "url": "/documentation/photos/phassetcollection/startdate"
    },
    "doc://com.apple.photokit/documentation/Photos/PHAssetCollectionSubtype": {
      "abstract": [
        {
          "text": "Minor distinctions between kinds of asset collections, used by the ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.photokit/documentation/Photos/PHAssetCollection/assetCollectionSubtype",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " property and the ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.photokit/documentation/Photos/PHAssetCollection/fetchAssetCollections(with:subtype:options:)",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " method.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "PHAssetCollectionSubtype"
        }
      ],
      "identifier": "doc://com.apple.photokit/documentation/Photos/PHAssetCollectionSubtype",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PHAssetCollectionSubtype"
        }
      ],
      "role": "symbol",
      "title": "PHAssetCollectionSubtype",
      "type": "topic",
      "url": "/documentation/photos/phassetcollectionsubtype"
    },
    "doc://com.apple.photokit/documentation/Photos/PHAssetCollectionSubtype/albumCloudShared": {
      "abstract": [
        {
          "text": "An iCloud Shared Photo Stream.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "albumCloudShared"
        }
      ],
      "identifier": "doc://com.apple.photokit/documentation/Photos/PHAssetCollectionSubtype/albumCloudShared",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PHAssetCollectionSubtypeAlbumCloudShared"
        }
      ],
      "role": "symbol",
      "title": "PHAssetCollectionSubtype.albumCloudShared",
      "type": "topic",
      "url": "/documentation/photos/phassetcollectionsubtype/albumcloudshared"
    },
    "doc://com.apple.photokit/documentation/Photos/PHAssetCollectionSubtype/albumImported": {
      "abstract": [
        {
          "text": "An album imported from a camera or external storage.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "albumImported"
        }
      ],
      "identifier": "doc://com.apple.photokit/documentation/Photos/PHAssetCollectionSubtype/albumImported",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PHAssetCollectionSubtypeAlbumImported"
        }
      ],
      "role": "symbol",
      "title": "PHAssetCollectionSubtype.albumImported",
      "type": "topic",
      "url": "/documentation/photos/phassetcollectionsubtype/albumimported"
    },
    "doc://com.apple.photokit/documentation/Photos/PHAssetCollectionSubtype/albumMyPhotoStream": {
      "abstract": [
        {
          "text": "The user’s personal iCloud Photo Stream.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "albumMyPhotoStream"
        }
      ],
      "identifier": "doc://com.apple.photokit/documentation/Photos/PHAssetCollectionSubtype/albumMyPhotoStream",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PHAssetCollectionSubtypeAlbumMyPhotoStream"
        }
      ],
      "role": "symbol",
      "title": "PHAssetCollectionSubtype.albumMyPhotoStream",
      "type": "topic",
      "url": "/documentation/photos/phassetcollectionsubtype/albummyphotostream"
    },
    "doc://com.apple.photokit/documentation/Photos/PHAssetCollectionSubtype/albumRegular": {
      "abstract": [
        {
          "text": "An album created in the Photos app.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "albumRegular"
        }
      ],
      "identifier": "doc://com.apple.photokit/documentation/Photos/PHAssetCollectionSubtype/albumRegular",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PHAssetCollectionSubtypeAlbumRegular"
        }
      ],
      "role": "symbol",
      "title": "PHAssetCollectionSubtype.albumRegular",
      "type": "topic",
      "url": "/documentation/photos/phassetcollectionsubtype/albumregular"
    },
    "doc://com.apple.photokit/documentation/Photos/PHAssetCollectionSubtype/albumSyncedAlbum": {
      "abstract": [
        {
          "text": "An album synced to the device from iPhoto.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "albumSyncedAlbum"
        }
      ],
      "identifier": "doc://com.apple.photokit/documentation/Photos/PHAssetCollectionSubtype/albumSyncedAlbum",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PHAssetCollectionSubtypeAlbumSyncedAlbum"
        }
      ],
      "role": "symbol",
      "title": "PHAssetCollectionSubtype.albumSyncedAlbum",
      "type": "topic",
      "url": "/documentation/photos/phassetcollectionsubtype/albumsyncedalbum"
    },
    "doc://com.apple.photokit/documentation/Photos/PHAssetCollectionSubtype/albumSyncedEvent": {
      "abstract": [
        {
          "text": "An Event synced to the device from iPhoto.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "albumSyncedEvent"
        }
      ],
      "identifier": "doc://com.apple.photokit/documentation/Photos/PHAssetCollectionSubtype/albumSyncedEvent",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PHAssetCollectionSubtypeAlbumSyncedEvent"
        }
      ],
      "role": "symbol",
      "title": "PHAssetCollectionSubtype.albumSyncedEvent",
      "type": "topic",
      "url": "/documentation/photos/phassetcollectionsubtype/albumsyncedevent"
    },
    "doc://com.apple.photokit/documentation/Photos/PHAssetCollectionSubtype/albumSyncedFaces": {
      "abstract": [
        {
          "text": "A Faces group synced to the device from iPhoto.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "albumSyncedFaces"
        }
      ],
      "identifier": "doc://com.apple.photokit/documentation/Photos/PHAssetCollectionSubtype/albumSyncedFaces",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PHAssetCollectionSubtypeAlbumSyncedFaces"
        }
      ],
      "role": "symbol",
      "title": "PHAssetCollectionSubtype.albumSyncedFaces",
      "type": "topic",
      "url": "/documentation/photos/phassetcollectionsubtype/albumsyncedfaces"
    },
    "doc://com.apple.photokit/documentation/Photos/PHAssetCollectionSubtype/any": {
      "abstract": [
        {
          "text": "A bit mask representing all possible subtypes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "any"
        }
      ],
      "identifier": "doc://com.apple.photokit/documentation/Photos/PHAssetCollectionSubtype/any",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PHAssetCollectionSubtypeAny"
        }
      ],
      "role": "symbol",
      "title": "PHAssetCollectionSubtype.any",
      "type": "topic",
      "url": "/documentation/photos/phassetcollectionsubtype/any"
    },
    "doc://com.apple.photokit/documentation/Photos/PHAssetCollectionSubtype/init(rawValue:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "?("
        },
        {
          "kind": "externalParam",
          "text": "rawValue"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.photokit/documentation/Photos/PHAssetCollectionSubtype/init(rawValue:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "init(rawValue:)",
      "type": "topic",
      "url": "/documentation/photos/phassetcollectionsubtype/init(rawvalue:)"
    },
    "doc://com.apple.photokit/documentation/Photos/PHAssetCollectionSubtype/smartAlbumAllHidden": {
      "abstract": [
        {
          "text": "A Smart Album that groups all assets hidden from the Moments view in the Photos app.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "smartAlbumAllHidden"
        }
      ],
      "identifier": "doc://com.apple.photokit/documentation/Photos/PHAssetCollectionSubtype/smartAlbumAllHidden",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PHAssetCollectionSubtypeSmartAlbumAllHidden"
        }
      ],
      "role": "symbol",
      "title": "PHAssetCollectionSubtype.smartAlbumAllHidden",
      "type": "topic",
      "url": "/documentation/photos/phassetcollectionsubtype/smartalbumallhidden"
    },
    "doc://com.apple.photokit/documentation/Photos/PHAssetCollectionSubtype/smartAlbumAnimated": {
      "abstract": [
        {
          "text": "A Smart Album that groups all image animation assets.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "smartAlbumAnimated"
        }
      ],
      "identifier": "doc://com.apple.photokit/documentation/Photos/PHAssetCollectionSubtype/smartAlbumAnimated",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PHAssetCollectionSubtypeSmartAlbumAnimated"
        }
      ],
      "role": "symbol",
      "title": "PHAssetCollectionSubtype.smartAlbumAnimated",
      "type": "topic",
      "url": "/documentation/photos/phassetcollectionsubtype/smartalbumanimated"
    },
    "doc://com.apple.photokit/documentation/Photos/PHAssetCollectionSubtype/smartAlbumBursts": {
      "abstract": [
        {
          "text": "A Smart Album that groups all burst photo sequences in the photo library.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "smartAlbumBursts"
        }
      ],
      "identifier": "doc://com.apple.photokit/documentation/Photos/PHAssetCollectionSubtype/smartAlbumBursts",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PHAssetCollectionSubtypeSmartAlbumBursts"
        }
      ],
      "role": "symbol",
      "title": "PHAssetCollectionSubtype.smartAlbumBursts",
      "type": "topic",
      "url": "/documentation/photos/phassetcollectionsubtype/smartalbumbursts"
    },
    "doc://com.apple.photokit/documentation/Photos/PHAssetCollectionSubtype/smartAlbumCinematic": {
      "abstract": [
        {
          "text": "A Smart Album that groups all cinematic photo assets.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "smartAlbumCinematic"
        }
      ],
      "identifier": "doc://com.apple.photokit/documentation/Photos/PHAssetCollectionSubtype/smartAlbumCinematic",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PHAssetCollectionSubtypeSmartAlbumCinematic"
        }
      ],
      "role": "symbol",
      "title": "PHAssetCollectionSubtype.smartAlbumCinematic",
      "type": "topic",
      "url": "/documentation/photos/phassetcollectionsubtype/smartalbumcinematic"
    },
    "doc://com.apple.photokit/documentation/Photos/PHAssetCollectionSubtype/smartAlbumDepthEffect": {
      "abstract": [
        {
          "text": "A Smart Album that groups all images captured using the Depth Effect camera mode on compatible devices.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "smartAlbumDepthEffect"
        }
      ],
      "identifier": "doc://com.apple.photokit/documentation/Photos/PHAssetCollectionSubtype/smartAlbumDepthEffect",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PHAssetCollectionSubtypeSmartAlbumDepthEffect"
        }
      ],
      "role": "symbol",
      "title": "PHAssetCollectionSubtype.smartAlbumDepthEffect",
      "type": "topic",
      "url": "/documentation/photos/phassetcollectionsubtype/smartalbumdeptheffect"
    },
    "doc://com.apple.photokit/documentation/Photos/PHAssetCollectionSubtype/smartAlbumFavorites": {
      "abstract": [
        {
          "text": "A Smart Album that groups all assets that the user marks as favorites.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "smartAlbumFavorites"
        }
      ],
      "identifier": "doc://com.apple.photokit/documentation/Photos/PHAssetCollectionSubtype/smartAlbumFavorites",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PHAssetCollectionSubtypeSmartAlbumFavorites"
        }
      ],
      "role": "symbol",
      "title": "PHAssetCollectionSubtype.smartAlbumFavorites",
      "type": "topic",
      "url": "/documentation/photos/phassetcollectionsubtype/smartalbumfavorites"
    },
    "doc://com.apple.photokit/documentation/Photos/PHAssetCollectionSubtype/smartAlbumGeneric": {
      "abstract": [
        {
          "text": "A Smart Album without a more-specific subtype.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "smartAlbumGeneric"
        }
      ],
      "identifier": "doc://com.apple.photokit/documentation/Photos/PHAssetCollectionSubtype/smartAlbumGeneric",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PHAssetCollectionSubtypeSmartAlbumGeneric"
        }
      ],
      "role": "symbol",
      "title": "PHAssetCollectionSubtype.smartAlbumGeneric",
      "type": "topic",
      "url": "/documentation/photos/phassetcollectionsubtype/smartalbumgeneric"
    },
    "doc://com.apple.photokit/documentation/Photos/PHAssetCollectionSubtype/smartAlbumLivePhotos": {
      "abstract": [
        {
          "text": "A Smart Album that groups all Live Photos assets.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "smartAlbumLivePhotos"
        }
      ],
      "identifier": "doc://com.apple.photokit/documentation/Photos/PHAssetCollectionSubtype/smartAlbumLivePhotos",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PHAssetCollectionSubtypeSmartAlbumLivePhotos"
        }
      ],
      "role": "symbol",
      "title": "PHAssetCollectionSubtype.smartAlbumLivePhotos",
      "type": "topic",
      "url": "/documentation/photos/phassetcollectionsubtype/smartalbumlivephotos"
    },
    "doc://com.apple.photokit/documentation/Photos/PHAssetCollectionSubtype/smartAlbumLongExposures": {
      "abstract": [
        {
          "text": "A Smart Album that groups all Live Photos assets where the Long Exposure variation is in an enabled state.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "smartAlbumLongExposures"
        }
      ],
      "identifier": "doc://com.apple.photokit/documentation/Photos/PHAssetCollectionSubtype/smartAlbumLongExposures",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PHAssetCollectionSubtypeSmartAlbumLongExposures"
        }
      ],
      "role": "symbol",
      "title": "PHAssetCollectionSubtype.smartAlbumLongExposures",
      "type": "topic",
      "url": "/documentation/photos/phassetcollectionsubtype/smartalbumlongexposures"
    },
    "doc://com.apple.photokit/documentation/Photos/PHAssetCollectionSubtype/smartAlbumPanoramas": {
      "abstract": [
        {
          "text": "A Smart Album that groups all panorama photos in the photo library.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "smartAlbumPanoramas"
        }
      ],
      "identifier": "doc://com.apple.photokit/documentation/Photos/PHAssetCollectionSubtype/smartAlbumPanoramas",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PHAssetCollectionSubtypeSmartAlbumPanoramas"
        }
      ],
      "role": "symbol",
      "title": "PHAssetCollectionSubtype.smartAlbumPanoramas",
      "type": "topic",
      "url": "/documentation/photos/phassetcollectionsubtype/smartalbumpanoramas"
    },
    "doc://com.apple.photokit/documentation/Photos/PHAssetCollectionSubtype/smartAlbumRAW": {
      "abstract": [
        {
          "text": "A Smart Album that groups all RAW assets in the photo library.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "smartAlbumRAW"
        }
      ],
      "identifier": "doc://com.apple.photokit/documentation/Photos/PHAssetCollectionSubtype/smartAlbumRAW",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PHAssetCollectionSubtypeSmartAlbumRAW"
        }
      ],
      "role": "symbol",
      "title": "PHAssetCollectionSubtype.smartAlbumRAW",
      "type": "topic",
      "url": "/documentation/photos/phassetcollectionsubtype/smartalbumraw"
    },
    "doc://com.apple.photokit/documentation/Photos/PHAssetCollectionSubtype/smartAlbumRecentlyAdded": {
      "abstract": [
        {
          "text": "A Smart Album that groups all recently added assets in the photo library.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "smartAlbumRecentlyAdded"
        }
      ],
      "identifier": "doc://com.apple.photokit/documentation/Photos/PHAssetCollectionSubtype/smartAlbumRecentlyAdded",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PHAssetCollectionSubtypeSmartAlbumRecentlyAdded"
        }
      ],
      "role": "symbol",
      "title": "PHAssetCollectionSubtype.smartAlbumRecentlyAdded",
      "type": "topic",
      "url": "/documentation/photos/phassetcollectionsubtype/smartalbumrecentlyadded"
    },
    "doc://com.apple.photokit/documentation/Photos/PHAssetCollectionSubtype/smartAlbumScreenshots": {
      "abstract": [
        {
          "text": "A Smart Album that groups all images captured using the device’s screenshot function.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "smartAlbumScreenshots"
        }
      ],
      "identifier": "doc://com.apple.photokit/documentation/Photos/PHAssetCollectionSubtype/smartAlbumScreenshots",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PHAssetCollectionSubtypeSmartAlbumScreenshots"
        }
      ],
      "role": "symbol",
      "title": "PHAssetCollectionSubtype.smartAlbumScreenshots",
      "type": "topic",
      "url": "/documentation/photos/phassetcollectionsubtype/smartalbumscreenshots"
    },
    "doc://com.apple.photokit/documentation/Photos/PHAssetCollectionSubtype/smartAlbumSelfPortraits": {
      "abstract": [
        {
          "text": "A Smart Album that groups all photos and videos captured using the device’s front-facing camera.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "smartAlbumSelfPortraits"
        }
      ],
      "identifier": "doc://com.apple.photokit/documentation/Photos/PHAssetCollectionSubtype/smartAlbumSelfPortraits",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PHAssetCollectionSubtypeSmartAlbumSelfPortraits"
        }
      ],
      "role": "symbol",
      "title": "PHAssetCollectionSubtype.smartAlbumSelfPortraits",
      "type": "topic",
      "url": "/documentation/photos/phassetcollectionsubtype/smartalbumselfportraits"
    },
    "doc://com.apple.photokit/documentation/Photos/PHAssetCollectionSubtype/smartAlbumSlomoVideos": {
      "abstract": [
        {
          "text": "A Smart Album that groups all Slow-Mo videos in the photo library.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "smartAlbumSlomoVideos"
        }
      ],
      "identifier": "doc://com.apple.photokit/documentation/Photos/PHAssetCollectionSubtype/smartAlbumSlomoVideos",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PHAssetCollectionSubtypeSmartAlbumSlomoVideos"
        }
      ],
      "role": "symbol",
      "title": "PHAssetCollectionSubtype.smartAlbumSlomoVideos",
      "type": "topic",
      "url": "/documentation/photos/phassetcollectionsubtype/smartalbumslomovideos"
    },
    "doc://com.apple.photokit/documentation/Photos/PHAssetCollectionSubtype/smartAlbumSpatial": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "smartAlbumSpatial"
        }
      ],
      "identifier": "doc://com.apple.photokit/documentation/Photos/PHAssetCollectionSubtype/smartAlbumSpatial",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PHAssetCollectionSubtypeSmartAlbumSpatial"
        }
      ],
      "role": "symbol",
      "title": "PHAssetCollectionSubtype.smartAlbumSpatial",
      "type": "topic",
      "url": "/documentation/photos/phassetcollectionsubtype/smartalbumspatial"
    },
    "doc://com.apple.photokit/documentation/Photos/PHAssetCollectionSubtype/smartAlbumTimelapses": {
      "abstract": [
        {
          "text": "A Smart Album that groups all time-lapse videos in the photo library.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "smartAlbumTimelapses"
        }
      ],
      "identifier": "doc://com.apple.photokit/documentation/Photos/PHAssetCollectionSubtype/smartAlbumTimelapses",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PHAssetCollectionSubtypeSmartAlbumTimelapses"
        }
      ],
      "role": "symbol",
      "title": "PHAssetCollectionSubtype.smartAlbumTimelapses",
      "type": "topic",
      "url": "/documentation/photos/phassetcollectionsubtype/smartalbumtimelapses"
    },
    "doc://com.apple.photokit/documentation/Photos/PHAssetCollectionSubtype/smartAlbumUnableToUpload": {
      "abstract": [
        {
          "text": "A Smart Album that groups all assets that the system can’t upload to iCloud.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "smartAlbumUnableToUpload"
        }
      ],
      "identifier": "doc://com.apple.photokit/documentation/Photos/PHAssetCollectionSubtype/smartAlbumUnableToUpload",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PHAssetCollectionSubtypeSmartAlbumUnableToUpload"
        }
      ],
      "role": "symbol",
      "title": "PHAssetCollectionSubtype.smartAlbumUnableToUpload",
      "type": "topic",
      "url": "/documentation/photos/phassetcollectionsubtype/smartalbumunabletoupload"
    },
    "doc://com.apple.photokit/documentation/Photos/PHAssetCollectionSubtype/smartAlbumUserLibrary": {
      "abstract": [
        {
          "text": "A Smart Album that groups all assets that originate in the user’s own library (as opposed to assets from iCloud Shared Albums).",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "smartAlbumUserLibrary"
        }
      ],
      "identifier": "doc://com.apple.photokit/documentation/Photos/PHAssetCollectionSubtype/smartAlbumUserLibrary",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PHAssetCollectionSubtypeSmartAlbumUserLibrary"
        }
      ],
      "role": "symbol",
      "title": "PHAssetCollectionSubtype.smartAlbumUserLibrary",
      "type": "topic",
      "url": "/documentation/photos/phassetcollectionsubtype/smartalbumuserlibrary"
    },
    "doc://com.apple.photokit/documentation/Photos/PHAssetCollectionSubtype/smartAlbumVideos": {
      "abstract": [
        {
          "text": "A Smart Album that groups all video assets in the photo library.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "smartAlbumVideos"
        }
      ],
      "identifier": "doc://com.apple.photokit/documentation/Photos/PHAssetCollectionSubtype/smartAlbumVideos",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PHAssetCollectionSubtypeSmartAlbumVideos"
        }
      ],
      "role": "symbol",
      "title": "PHAssetCollectionSubtype.smartAlbumVideos",
      "type": "topic",
      "url": "/documentation/photos/phassetcollectionsubtype/smartalbumvideos"
    },
    "doc://com.apple.photokit/documentation/Photos/PHAssetCollectionType": {
      "abstract": [
        {
          "text": "Major distinctions between kinds of asset collections, used by the ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.photokit/documentation/Photos/PHAssetCollection/assetCollectionType",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " property and the ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.photokit/documentation/Photos/PHAssetCollection/fetchAssetCollectionsContaining(_:with:options:)",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " and ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.photokit/documentation/Photos/PHAssetCollection/fetchAssetCollections(with:subtype:options:)",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " methods.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "PHAssetCollectionType"
        }
      ],
      "identifier": "doc://com.apple.photokit/documentation/Photos/PHAssetCollectionType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PHAssetCollectionType"
        }
      ],
      "role": "symbol",
      "title": "PHAssetCollectionType",
      "type": "topic",
      "url": "/documentation/photos/phassetcollectiontype"
    },
    "doc://com.externally.resolved.symbol/c:@T@NSInteger": {
      "abstract": [
        {
          "text": "Describes an integer.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "typealias "
        },
        {
          "kind": "identifier",
          "text": "NSInteger"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:@T@NSInteger",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSInteger",
      "type": "topic",
      "url": "/documentation/objectivec/nsinteger"
    },
    "doc://com.externally.resolved.symbol/s:SH": {
      "abstract": [
        {
          "text": "A type that can be hashed into a `Hasher` to produce an integer hash value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Hashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SQ",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SH",
      "kind": "symbol",
      "role": "symbol",
      "title": "Hashable",
      "type": "topic",
      "url": "/documentation/Swift/Hashable"
    },
    "doc://com.externally.resolved.symbol/s:SQ": {
      "abstract": [
        {
          "text": "A type that can be compared for value equality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SQ",
      "kind": "symbol",
      "role": "symbol",
      "title": "Equatable",
      "type": "topic",
      "url": "/documentation/Swift/Equatable"
    },
    "doc://com.externally.resolved.symbol/s:SY": {
      "abstract": [
        {
          "text": "A type that can be converted to and from an associated raw value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "RawRepresentable"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SY8RawValueQa",
          "text": "RawValue"
        },
        {
          "kind": "text",
          "text": ">"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SY",
      "kind": "symbol",
      "role": "symbol",
      "title": "RawRepresentable",
      "type": "topic",
      "url": "/documentation/Swift/RawRepresentable"
    },
    "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BitwiseCopyable"
        },
        {
          "kind": "text",
          "text": " : ~Escapable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "BitwiseCopyable",
      "type": "topic",
      "url": "/documentation/Swift/BitwiseCopyable"
    },
    "doc://com.externally.resolved.symbol/s:s8SendableP": {
      "abstract": [
        {
          "text": "A thread-safe type whose values can be shared across arbitrary concurrent contexts without introducing a risk of data races.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Sendable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s8SendableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "Sendable",
      "type": "topic",
      "url": "/documentation/Swift/Sendable"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
        "doc://com.externally.resolved.symbol/s:SQ",
        "doc://com.externally.resolved.symbol/s:SH",
        "doc://com.externally.resolved.symbol/s:SY",
        "doc://com.externally.resolved.symbol/s:s8SendableP"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Reading-Asset-Collection-Metadata",
      "generated": true,
      "identifiers": [
        "doc://com.apple.photokit/documentation/Photos/PHAssetCollection/assetCollectionType",
        "doc://com.apple.photokit/documentation/Photos/PHAssetCollectionType",
        "doc://com.apple.photokit/documentation/Photos/PHAssetCollection/assetCollectionSubtype",
        "doc://com.apple.photokit/documentation/Photos/PHAssetCollection/estimatedAssetCount",
        "doc://com.apple.photokit/documentation/Photos/PHAssetCollection/startDate",
        "doc://com.apple.photokit/documentation/Photos/PHAssetCollection/endDate",
        "doc://com.apple.photokit/documentation/Photos/PHAssetCollection/approximateLocation",
        "doc://com.apple.photokit/documentation/Photos/PHAssetCollection/localizedLocationNames"
      ],
      "title": "Reading Asset Collection Metadata"
    }
  ],
  "topicSections": [
    {
      "anchor": "User-Album-Types",
      "identifiers": [
        "doc://com.apple.photokit/documentation/Photos/PHAssetCollectionSubtype/albumRegular",
        "doc://com.apple.photokit/documentation/Photos/PHAssetCollectionSubtype/albumSyncedEvent",
        "doc://com.apple.photokit/documentation/Photos/PHAssetCollectionSubtype/albumSyncedFaces",
        "doc://com.apple.photokit/documentation/Photos/PHAssetCollectionSubtype/albumSyncedAlbum",
        "doc://com.apple.photokit/documentation/Photos/PHAssetCollectionSubtype/albumImported"
      ],
      "title": "User Album Types"
    },
    {
      "anchor": "Cloud-Album-Types",
      "identifiers": [
        "doc://com.apple.photokit/documentation/Photos/PHAssetCollectionSubtype/albumMyPhotoStream",
        "doc://com.apple.photokit/documentation/Photos/PHAssetCollectionSubtype/albumCloudShared"
      ],
      "title": "Cloud Album Types"
    },
    {
      "anchor": "Smart-Album-Types",
      "identifiers": [
        "doc://com.apple.photokit/documentation/Photos/PHAssetCollectionSubtype/smartAlbumAllHidden",
        "doc://com.apple.photokit/documentation/Photos/PHAssetCollectionSubtype/smartAlbumAnimated",
        "doc://com.apple.photokit/documentation/Photos/PHAssetCollectionSubtype/smartAlbumBursts",
        "doc://com.apple.photokit/documentation/Photos/PHAssetCollectionSubtype/smartAlbumCinematic",
        "doc://com.apple.photokit/documentation/Photos/PHAssetCollectionSubtype/smartAlbumDepthEffect",
        "doc://com.apple.photokit/documentation/Photos/PHAssetCollectionSubtype/smartAlbumFavorites",
        "doc://com.apple.photokit/documentation/Photos/PHAssetCollectionSubtype/smartAlbumGeneric",
        "doc://com.apple.photokit/documentation/Photos/PHAssetCollectionSubtype/smartAlbumLivePhotos",
        "doc://com.apple.photokit/documentation/Photos/PHAssetCollectionSubtype/smartAlbumLongExposures",
        "doc://com.apple.photokit/documentation/Photos/PHAssetCollectionSubtype/smartAlbumPanoramas",
        "doc://com.apple.photokit/documentation/Photos/PHAssetCollectionSubtype/smartAlbumRAW",
        "doc://com.apple.photokit/documentation/Photos/PHAssetCollectionSubtype/smartAlbumRecentlyAdded",
        "doc://com.apple.photokit/documentation/Photos/PHAssetCollectionSubtype/smartAlbumScreenshots",
        "doc://com.apple.photokit/documentation/Photos/PHAssetCollectionSubtype/smartAlbumSelfPortraits",
        "doc://com.apple.photokit/documentation/Photos/PHAssetCollectionSubtype/smartAlbumSlomoVideos",
        "doc://com.apple.photokit/documentation/Photos/PHAssetCollectionSubtype/smartAlbumTimelapses",
        "doc://com.apple.photokit/documentation/Photos/PHAssetCollectionSubtype/smartAlbumUnableToUpload",
        "doc://com.apple.photokit/documentation/Photos/PHAssetCollectionSubtype/smartAlbumUserLibrary",
        "doc://com.apple.photokit/documentation/Photos/PHAssetCollectionSubtype/smartAlbumVideos"
      ],
      "title": "Smart Album Types"
    },
    {
      "anchor": "Wildcard-Search",
      "identifiers": [
        "doc://com.apple.photokit/documentation/Photos/PHAssetCollectionSubtype/any"
      ],
      "title": "Wildcard Search"
    },
    {
      "anchor": "Enumeration-Cases",
      "generated": true,
      "identifiers": [
        "doc://com.apple.photokit/documentation/Photos/PHAssetCollectionSubtype/smartAlbumSpatial"
      ],
      "title": "Enumeration Cases"
    },
    {
      "anchor": "Initializers",
      "generated": true,
      "identifiers": [
        "doc://com.apple.photokit/documentation/Photos/PHAssetCollectionSubtype/init(rawValue:)"
      ],
      "title": "Initializers"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "8.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "8.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.1",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.11",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.0",
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "PHAssetCollectionSubtype"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "enum"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PHAssetCollectionSubtype"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "PHAssetCollectionSubtype"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.photokit/documentation/Photos"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "User-Album-Types",
              "identifiers": [
                "doc://com.apple.photokit/documentation/Photos/PHAssetCollectionSubtype/albumRegular",
                "doc://com.apple.photokit/documentation/Photos/PHAssetCollectionSubtype/albumSyncedEvent",
                "doc://com.apple.photokit/documentation/Photos/PHAssetCollectionSubtype/albumSyncedFaces",
                "doc://com.apple.photokit/documentation/Photos/PHAssetCollectionSubtype/albumSyncedAlbum",
                "doc://com.apple.photokit/documentation/Photos/PHAssetCollectionSubtype/albumImported"
              ],
              "title": "User Album Types"
            },
            {
              "anchor": "Cloud-Album-Types",
              "identifiers": [
                "doc://com.apple.photokit/documentation/Photos/PHAssetCollectionSubtype/albumMyPhotoStream",
                "doc://com.apple.photokit/documentation/Photos/PHAssetCollectionSubtype/albumCloudShared"
              ],
              "title": "Cloud Album Types"
            },
            {
              "anchor": "Smart-Album-Types",
              "identifiers": [
                "doc://com.apple.photokit/documentation/Photos/PHAssetCollectionSubtype/smartAlbumAllHidden",
                "doc://com.apple.photokit/documentation/Photos/PHAssetCollectionSubtype/smartAlbumAnimated",
                "doc://com.apple.photokit/documentation/Photos/PHAssetCollectionSubtype/smartAlbumBursts",
                "doc://com.apple.photokit/documentation/Photos/PHAssetCollectionSubtype/smartAlbumCinematic",
                "doc://com.apple.photokit/documentation/Photos/PHAssetCollectionSubtype/smartAlbumDepthEffect",
                "doc://com.apple.photokit/documentation/Photos/PHAssetCollectionSubtype/smartAlbumFavorites",
                "doc://com.apple.photokit/documentation/Photos/PHAssetCollectionSubtype/smartAlbumGeneric",
                "doc://com.apple.photokit/documentation/Photos/PHAssetCollectionSubtype/smartAlbumLivePhotos",
                "doc://com.apple.photokit/documentation/Photos/PHAssetCollectionSubtype/smartAlbumLongExposures",
                "doc://com.apple.photokit/documentation/Photos/PHAssetCollectionSubtype/smartAlbumPanoramas",
                "doc://com.apple.photokit/documentation/Photos/PHAssetCollectionSubtype/smartAlbumRAW",
                "doc://com.apple.photokit/documentation/Photos/PHAssetCollectionSubtype/smartAlbumRecentlyAdded",
                "doc://com.apple.photokit/documentation/Photos/PHAssetCollectionSubtype/smartAlbumScreenshots",
                "doc://com.apple.photokit/documentation/Photos/PHAssetCollectionSubtype/smartAlbumSelfPortraits",
                "doc://com.apple.photokit/documentation/Photos/PHAssetCollectionSubtype/smartAlbumSlomoVideos",
                "doc://com.apple.photokit/documentation/Photos/PHAssetCollectionSubtype/smartAlbumTimelapses",
                "doc://com.apple.photokit/documentation/Photos/PHAssetCollectionSubtype/smartAlbumUnableToUpload",
                "doc://com.apple.photokit/documentation/Photos/PHAssetCollectionSubtype/smartAlbumUserLibrary",
                "doc://com.apple.photokit/documentation/Photos/PHAssetCollectionSubtype/smartAlbumVideos"
              ],
              "title": "Smart Album Types"
            },
            {
              "anchor": "Wildcard-Search",
              "identifiers": [
                "doc://com.apple.photokit/documentation/Photos/PHAssetCollectionSubtype/any"
              ],
              "title": "Wildcard Search"
            },
            {
              "anchor": "Enumeration-Cases",
              "generated": true,
              "identifiers": [
                "doc://com.apple.photokit/documentation/Photos/PHAssetCollectionSubtype/smartAlbumSpatial"
              ],
              "title": "Enumeration Cases"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Reading-Asset-Collection-Metadata",
              "generated": true,
              "identifiers": [
                "doc://com.apple.photokit/documentation/Photos/PHAssetCollection/assetCollectionType",
                "doc://com.apple.photokit/documentation/Photos/PHAssetCollectionType",
                "doc://com.apple.photokit/documentation/Photos/PHAssetCollection/assetCollectionSubtype",
                "doc://com.apple.photokit/documentation/Photos/PHAssetCollection/estimatedAssetCount",
                "doc://com.apple.photokit/documentation/Photos/PHAssetCollection/startDate",
                "doc://com.apple.photokit/documentation/Photos/PHAssetCollection/endDate",
                "doc://com.apple.photokit/documentation/Photos/PHAssetCollection/approximateLocation",
                "doc://com.apple.photokit/documentation/Photos/PHAssetCollection/localizedLocationNames"
              ],
              "title": "Reading Asset Collection Metadata"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "enum"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "PHAssetCollectionSubtype"
                  },
                  {
                    "kind": "text",
                    "text": " : "
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:@T@NSInteger",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@NSInteger",
                    "text": "NSInteger"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHAssetCollectionSubtype~1smartAlbumUnableToUpload/title",
          "value": "PHAssetCollectionSubtypeSmartAlbumUnableToUpload"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHAssetCollectionSubtype~1smartAlbumUnableToUpload/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PHAssetCollectionSubtypeSmartAlbumUnableToUpload"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHAssetCollectionSubtype~1smartAlbumAnimated/title",
          "value": "PHAssetCollectionSubtypeSmartAlbumAnimated"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHAssetCollectionSubtype~1smartAlbumAnimated/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PHAssetCollectionSubtypeSmartAlbumAnimated"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHAssetCollection~1endDate/title",
          "value": "endDate"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHAssetCollection~1endDate/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "endDate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHAssetCollectionSubtype~1albumCloudShared/title",
          "value": "PHAssetCollectionSubtypeAlbumCloudShared"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHAssetCollectionSubtype~1albumCloudShared/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PHAssetCollectionSubtypeAlbumCloudShared"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHAssetCollectionSubtype~1albumSyncedFaces/title",
          "value": "PHAssetCollectionSubtypeAlbumSyncedFaces"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHAssetCollectionSubtype~1albumSyncedFaces/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PHAssetCollectionSubtypeAlbumSyncedFaces"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHAssetCollection~1startDate/title",
          "value": "startDate"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHAssetCollection~1startDate/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "startDate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHAssetCollectionSubtype~1smartAlbumFavorites/title",
          "value": "PHAssetCollectionSubtypeSmartAlbumFavorites"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHAssetCollectionSubtype~1smartAlbumFavorites/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PHAssetCollectionSubtypeSmartAlbumFavorites"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHAssetCollectionSubtype~1albumImported/title",
          "value": "PHAssetCollectionSubtypeAlbumImported"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHAssetCollectionSubtype~1albumImported/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PHAssetCollectionSubtypeAlbumImported"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHAssetCollection~1fetchAssetCollectionsContaining(_:with:options:)/title",
          "value": "fetchAssetCollectionsContainingAsset:withType:options:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHAssetCollection~1fetchAssetCollectionsContaining(_:with:options:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "+ "
            },
            {
              "kind": "identifier",
              "text": "fetchAssetCollectionsContainingAsset:withType:options:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHAssetCollectionType/title",
          "value": "PHAssetCollectionType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHAssetCollectionType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PHAssetCollectionType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHAssetCollectionType/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "PHAssetCollectionType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHAssetCollectionSubtype~1smartAlbumRecentlyAdded/title",
          "value": "PHAssetCollectionSubtypeSmartAlbumRecentlyAdded"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHAssetCollectionSubtype~1smartAlbumRecentlyAdded/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PHAssetCollectionSubtypeSmartAlbumRecentlyAdded"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHAssetCollectionSubtype~1smartAlbumSpatial/title",
          "value": "PHAssetCollectionSubtypeSmartAlbumSpatial"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHAssetCollectionSubtype~1smartAlbumSpatial/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PHAssetCollectionSubtypeSmartAlbumSpatial"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHAssetCollectionSubtype~1smartAlbumPanoramas/title",
          "value": "PHAssetCollectionSubtypeSmartAlbumPanoramas"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHAssetCollectionSubtype~1smartAlbumPanoramas/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PHAssetCollectionSubtypeSmartAlbumPanoramas"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHAssetCollectionSubtype~1smartAlbumBursts/title",
          "value": "PHAssetCollectionSubtypeSmartAlbumBursts"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHAssetCollectionSubtype~1smartAlbumBursts/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PHAssetCollectionSubtypeSmartAlbumBursts"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHAssetCollectionSubtype~1smartAlbumVideos/title",
          "value": "PHAssetCollectionSubtypeSmartAlbumVideos"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHAssetCollectionSubtype~1smartAlbumVideos/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PHAssetCollectionSubtypeSmartAlbumVideos"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHAssetCollectionSubtype~1albumMyPhotoStream/title",
          "value": "PHAssetCollectionSubtypeAlbumMyPhotoStream"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHAssetCollectionSubtype~1albumMyPhotoStream/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PHAssetCollectionSubtypeAlbumMyPhotoStream"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHAssetCollectionSubtype~1albumSyncedAlbum/title",
          "value": "PHAssetCollectionSubtypeAlbumSyncedAlbum"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHAssetCollectionSubtype~1albumSyncedAlbum/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PHAssetCollectionSubtypeAlbumSyncedAlbum"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHAssetCollectionSubtype~1smartAlbumAllHidden/title",
          "value": "PHAssetCollectionSubtypeSmartAlbumAllHidden"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHAssetCollectionSubtype~1smartAlbumAllHidden/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PHAssetCollectionSubtypeSmartAlbumAllHidden"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHAssetCollectionSubtype~1albumSyncedEvent/title",
          "value": "PHAssetCollectionSubtypeAlbumSyncedEvent"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHAssetCollectionSubtype~1albumSyncedEvent/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PHAssetCollectionSubtypeAlbumSyncedEvent"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHAssetCollectionSubtype~1smartAlbumSlomoVideos/title",
          "value": "PHAssetCollectionSubtypeSmartAlbumSlomoVideos"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHAssetCollectionSubtype~1smartAlbumSlomoVideos/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PHAssetCollectionSubtypeSmartAlbumSlomoVideos"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHAssetCollectionSubtype~1smartAlbumRAW/title",
          "value": "PHAssetCollectionSubtypeSmartAlbumRAW"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHAssetCollectionSubtype~1smartAlbumRAW/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PHAssetCollectionSubtypeSmartAlbumRAW"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHAssetCollectionSubtype~1smartAlbumLivePhotos/title",
          "value": "PHAssetCollectionSubtypeSmartAlbumLivePhotos"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHAssetCollectionSubtype~1smartAlbumLivePhotos/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PHAssetCollectionSubtypeSmartAlbumLivePhotos"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHAssetCollectionSubtype~1smartAlbumLongExposures/title",
          "value": "PHAssetCollectionSubtypeSmartAlbumLongExposures"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHAssetCollectionSubtype~1smartAlbumLongExposures/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PHAssetCollectionSubtypeSmartAlbumLongExposures"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHAssetCollection~1estimatedAssetCount/title",
          "value": "estimatedAssetCount"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHAssetCollection~1estimatedAssetCount/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "estimatedAssetCount"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHAssetCollectionSubtype~1smartAlbumDepthEffect/title",
          "value": "PHAssetCollectionSubtypeSmartAlbumDepthEffect"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHAssetCollectionSubtype~1smartAlbumDepthEffect/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PHAssetCollectionSubtypeSmartAlbumDepthEffect"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHAssetCollection~1assetCollectionSubtype/title",
          "value": "assetCollectionSubtype"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHAssetCollection~1assetCollectionSubtype/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "assetCollectionSubtype"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHAssetCollection~1fetchAssetCollections(with:subtype:options:)/title",
          "value": "fetchAssetCollectionsWithType:subtype:options:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHAssetCollection~1fetchAssetCollections(with:subtype:options:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "+ "
            },
            {
              "kind": "identifier",
              "text": "fetchAssetCollectionsWithType:subtype:options:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHAssetCollectionSubtype~1smartAlbumSelfPortraits/title",
          "value": "PHAssetCollectionSubtypeSmartAlbumSelfPortraits"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHAssetCollectionSubtype~1smartAlbumSelfPortraits/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PHAssetCollectionSubtypeSmartAlbumSelfPortraits"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHAssetCollectionSubtype~1smartAlbumScreenshots/title",
          "value": "PHAssetCollectionSubtypeSmartAlbumScreenshots"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHAssetCollectionSubtype~1smartAlbumScreenshots/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PHAssetCollectionSubtypeSmartAlbumScreenshots"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHAssetCollectionSubtype~1smartAlbumCinematic/title",
          "value": "PHAssetCollectionSubtypeSmartAlbumCinematic"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHAssetCollectionSubtype~1smartAlbumCinematic/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PHAssetCollectionSubtypeSmartAlbumCinematic"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHAssetCollectionSubtype~1smartAlbumUserLibrary/title",
          "value": "PHAssetCollectionSubtypeSmartAlbumUserLibrary"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHAssetCollectionSubtype~1smartAlbumUserLibrary/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PHAssetCollectionSubtypeSmartAlbumUserLibrary"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHAssetCollection~1localizedLocationNames/title",
          "value": "localizedLocationNames"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHAssetCollection~1localizedLocationNames/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "localizedLocationNames"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHAssetCollection~1assetCollectionType/title",
          "value": "assetCollectionType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHAssetCollection~1assetCollectionType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "assetCollectionType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHAssetCollection~1approximateLocation/title",
          "value": "approximateLocation"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHAssetCollection~1approximateLocation/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "approximateLocation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHAssetCollectionSubtype~1smartAlbumGeneric/title",
          "value": "PHAssetCollectionSubtypeSmartAlbumGeneric"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHAssetCollectionSubtype~1smartAlbumGeneric/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PHAssetCollectionSubtypeSmartAlbumGeneric"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHAssetCollectionSubtype~1smartAlbumTimelapses/title",
          "value": "PHAssetCollectionSubtypeSmartAlbumTimelapses"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHAssetCollectionSubtype~1smartAlbumTimelapses/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PHAssetCollectionSubtypeSmartAlbumTimelapses"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHAssetCollectionSubtype/title",
          "value": "PHAssetCollectionSubtype"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHAssetCollectionSubtype/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PHAssetCollectionSubtype"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHAssetCollectionSubtype/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "PHAssetCollectionSubtype"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHAssetCollectionSubtype~1albumRegular/title",
          "value": "PHAssetCollectionSubtypeAlbumRegular"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHAssetCollectionSubtype~1albumRegular/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PHAssetCollectionSubtypeAlbumRegular"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHAssetCollectionSubtype~1any/title",
          "value": "PHAssetCollectionSubtypeAny"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHAssetCollectionSubtype~1any/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PHAssetCollectionSubtypeAny"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/photos/phassetcollectionsubtype"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/photos/phassetcollectionsubtype"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
