{
  "abstract": [
    {
      "text": "A request to create, delete, change metadata for, or edit the content of a Photos asset, for use in a photo library change block.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.photokit/documentation/Photos"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.photokit/documentation/Photos/PHAssetChangeRequest"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(cs)PHAssetChangeRequest",
    "fragments": [
      {
        "kind": "keyword",
        "text": "class"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "PHAssetChangeRequest"
      }
    ],
    "modules": [
      {
        "name": "Photos"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "PHAssetChangeRequest"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "8.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "8.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.1",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.15",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.0",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Class",
    "symbolKind": "class",
    "title": "PHAssetChangeRequest"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "class"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "PHAssetChangeRequest"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "kind": "mentions",
      "mentions": [
        "doc://com.apple.photokit/documentation/PhotoKit/requesting-changes-to-the-photo-library",
        "doc://com.apple.photokit/documentation/PhotoKit/editing-asset-content"
      ]
    },
    {
      "content": [
        {
          "anchor": "overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "You use the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.photokit/documentation/Photos/PHAssetChangeRequest",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " class to request changes for ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.photokit/documentation/Photos/PHAsset",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " objects. To make changes to assets in the Photos library, create a change request by using the appropriate class method for the change you want to perform.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "items": [
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Call one of the methods listed in Adding New Assets to create a new asset from an image or video file.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Call the ",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.photokit/documentation/Photos/PHAssetChangeRequest/deleteAssets(_:)",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": " method to delete existing assets.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Call the ",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.photokit/documentation/Photos/PHAssetChangeRequest/init(for:)",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": " method to modify an asset’s content or metadata.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            }
          ],
          "type": "unorderedList"
        },
        {
          "inlineContent": [
            {
              "text": "A change request for creating or modifying an asset works like a mutable version of the asset object. Use the change request’s properties to request changes to the corresponding properties of the asset itself. For example, the following code uses the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.photokit/documentation/Photos/PHAssetChangeRequest/isFavorite",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " property of a change request to mark an asset as a favorite:",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "tabs": [
            {
              "content": [
                {
                  "code": [
                    "func toggleFavorite(for asset: PHAsset) {        ",
                    "    PHPhotoLibrary.shared().performChanges {",
                    "        // Create a change request from the asset to be modified.",
                    "        let request = PHAssetChangeRequest(for: asset)",
                    "        // Set a property of the request to change the asset itself.",
                    "        request.isFavorite = !asset.isFavorite",
                    "    } completionHandler: { success, error in",
                    "        print(\"Finished updating asset. \" + (success ? \"Success.\" : error!.localizedDescription))",
                    "    }  ",
                    "}"
                  ],
                  "syntax": "swift",
                  "type": "codeListing"
                }
              ],
              "title": "Swift"
            },
            {
              "content": [
                {
                  "code": [
                    "- (void)toggleFavoriteForAsset:(PHAsset *)asset {",
                    "    [[PHPhotoLibrary sharedPhotoLibrary] performChanges:^{",
                    "        // Create a change request from the asset to be modified.",
                    "        PHAssetChangeRequest *request = [PHAssetChangeRequest changeRequestForAsset:asset];",
                    "        // Set a property of the request to change the asset itself.",
                    "        request.favorite = !asset.favorite;",
                    "    } completionHandler:^(BOOL success, NSError *error) {",
                    "        NSLog(@\"Finished updating asset. %@\", (success ? @\"Success.\" : error));",
                    "    }];",
                    "}"
                  ],
                  "syntax": "objc",
                  "type": "codeListing"
                }
              ],
              "title": "Objective-C"
            }
          ],
          "type": "tabNavigator"
        },
        {
          "inlineContent": [
            {
              "text": "After Photos runs the change block and calls your completion handler, the asset’s state reflects the changes that you requested in the block.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "If you create or use a change request object outside a photo library change block, Photos raises an Objective-C exception. For details on change blocks, see ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.photokit/documentation/Photos/PHPhotoLibrary",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ".",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.photokit/documentation/PhotoKit/editing-asset-content": {
      "abstract": [
        {
          "text": "Make a request to modify and save a photo or video asset.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.photokit/documentation/PhotoKit/editing-asset-content",
      "kind": "article",
      "role": "article",
      "title": "Editing Asset Content",
      "type": "topic",
      "url": "/documentation/photokit/editing-asset-content"
    },
    "doc://com.apple.photokit/documentation/PhotoKit/requesting-changes-to-the-photo-library": {
      "abstract": [
        {
          "text": "Create, delete, or modify assets and collections in a photo library by making change requests.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.photokit/documentation/PhotoKit/requesting-changes-to-the-photo-library",
      "kind": "article",
      "role": "article",
      "title": "Requesting Changes to the Photo Library",
      "type": "topic",
      "url": "/documentation/photokit/requesting-changes-to-the-photo-library"
    },
    "doc://com.apple.photokit/documentation/Photos": {
      "abstract": [
        {
          "text": "Work with image and video assets that the Photos app manages, including those from iCloud Photos and Live Photos.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.photokit/documentation/Photos",
      "kind": "symbol",
      "role": "collection",
      "title": "Photos",
      "type": "topic",
      "url": "/documentation/photos"
    },
    "doc://com.apple.photokit/documentation/Photos/PHAsset": {
      "abstract": [
        {
          "text": "A representation of an image, video, or Live Photo in the Photos library.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "PHAsset"
        }
      ],
      "identifier": "doc://com.apple.photokit/documentation/Photos/PHAsset",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PHAsset"
        }
      ],
      "role": "symbol",
      "title": "PHAsset",
      "type": "topic",
      "url": "/documentation/photos/phasset"
    },
    "doc://com.apple.photokit/documentation/Photos/PHAssetChangeRequest": {
      "abstract": [
        {
          "text": "A request to create, delete, change metadata for, or edit the content of a Photos asset, for use in a photo library change block.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "PHAssetChangeRequest"
        }
      ],
      "identifier": "doc://com.apple.photokit/documentation/Photos/PHAssetChangeRequest",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PHAssetChangeRequest"
        }
      ],
      "role": "symbol",
      "title": "PHAssetChangeRequest",
      "type": "topic",
      "url": "/documentation/photos/phassetchangerequest"
    },
    "doc://com.apple.photokit/documentation/Photos/PHAssetChangeRequest/contentEditingOutput": {
      "abstract": [
        {
          "text": "The output of an asset content editing session.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "contentEditingOutput"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)PHContentEditingOutput",
          "text": "PHContentEditingOutput"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.photokit/documentation/Photos/PHAssetChangeRequest/contentEditingOutput",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "contentEditingOutput"
        }
      ],
      "role": "symbol",
      "title": "contentEditingOutput",
      "type": "topic",
      "url": "/documentation/photos/phassetchangerequest/contenteditingoutput"
    },
    "doc://com.apple.photokit/documentation/Photos/PHAssetChangeRequest/creationDate": {
      "abstract": [
        {
          "text": "The date and time at which the asset claims to have been originally created.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "creationDate"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10Foundation4DateV",
          "text": "Date"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.photokit/documentation/Photos/PHAssetChangeRequest/creationDate",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "creationDate"
        }
      ],
      "role": "symbol",
      "title": "creationDate",
      "type": "topic",
      "url": "/documentation/photos/phassetchangerequest/creationdate"
    },
    "doc://com.apple.photokit/documentation/Photos/PHAssetChangeRequest/creationRequestForAsset(from:)": {
      "abstract": [
        {
          "text": "Creates a request for adding a new image asset to the Photos library.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "creationRequestForAsset"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "from"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UIImage",
          "text": "UIImage"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "text": "Self"
        }
      ],
      "identifier": "doc://com.apple.photokit/documentation/Photos/PHAssetChangeRequest/creationRequestForAsset(from:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "creationRequestForAssetFromImage:"
        }
      ],
      "role": "symbol",
      "title": "creationRequestForAsset(from:)",
      "type": "topic",
      "url": "/documentation/photos/phassetchangerequest/creationrequestforasset(from:)"
    },
    "doc://com.apple.photokit/documentation/Photos/PHAssetChangeRequest/creationRequestForAssetFromImage(atFileURL:)": {
      "abstract": [
        {
          "text": "Creates a request for adding a new image asset to the Photos library, using the image file at the specified URL.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "creationRequestForAssetFromImage"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "atFileURL"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10Foundation3URLV",
          "text": "URL"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "text": "Self"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.photokit/documentation/Photos/PHAssetChangeRequest/creationRequestForAssetFromImage(atFileURL:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "creationRequestForAssetFromImageAtFileURL:"
        }
      ],
      "role": "symbol",
      "title": "creationRequestForAssetFromImage(atFileURL:)",
      "type": "topic",
      "url": "/documentation/photos/phassetchangerequest/creationrequestforassetfromimage(atfileurl:)"
    },
    "doc://com.apple.photokit/documentation/Photos/PHAssetChangeRequest/creationRequestForAssetFromVideo(atFileURL:)": {
      "abstract": [
        {
          "text": "Creates a request for adding a new video asset to the Photos library, using the video file at the specified URL.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "creationRequestForAssetFromVideo"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "atFileURL"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10Foundation3URLV",
          "text": "URL"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "text": "Self"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.photokit/documentation/Photos/PHAssetChangeRequest/creationRequestForAssetFromVideo(atFileURL:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "creationRequestForAssetFromVideoAtFileURL:"
        }
      ],
      "role": "symbol",
      "title": "creationRequestForAssetFromVideo(atFileURL:)",
      "type": "topic",
      "url": "/documentation/photos/phassetchangerequest/creationrequestforassetfromvideo(atfileurl:)"
    },
    "doc://com.apple.photokit/documentation/Photos/PHAssetChangeRequest/deleteAssets(_:)": {
      "abstract": [
        {
          "text": "Requests that the specified assets be deleted.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "deleteAssets"
        },
        {
          "kind": "text",
          "text": "(any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(pl)NSFastEnumeration",
          "text": "NSFastEnumeration"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.photokit/documentation/Photos/PHAssetChangeRequest/deleteAssets(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "deleteAssets:"
        }
      ],
      "role": "symbol",
      "title": "deleteAssets(_:)",
      "type": "topic",
      "url": "/documentation/photos/phassetchangerequest/deleteassets(_:)"
    },
    "doc://com.apple.photokit/documentation/Photos/PHAssetChangeRequest/init(for:)": {
      "abstract": [
        {
          "text": "Creates a request for modifying the specified asset.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "convenience"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "for"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)PHAsset",
          "text": "PHAsset"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.photokit/documentation/Photos/PHAssetChangeRequest/init(for:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "changeRequestForAsset:"
        }
      ],
      "role": "symbol",
      "title": "init(for:)",
      "type": "topic",
      "url": "/documentation/photos/phassetchangerequest/init(for:)"
    },
    "doc://com.apple.photokit/documentation/Photos/PHAssetChangeRequest/isFavorite": {
      "abstract": [
        {
          "text": "A Boolean value that indicates whether the asset is marked as one of the user’s favorites.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "isFavorite"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.photokit/documentation/Photos/PHAssetChangeRequest/isFavorite",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "favorite"
        }
      ],
      "role": "symbol",
      "title": "isFavorite",
      "type": "topic",
      "url": "/documentation/photos/phassetchangerequest/isfavorite"
    },
    "doc://com.apple.photokit/documentation/Photos/PHAssetChangeRequest/isHidden": {
      "abstract": [
        {
          "text": "A Boolean value that indicates whether the asset is hidden in collections.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "isHidden"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.photokit/documentation/Photos/PHAssetChangeRequest/isHidden",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "hidden"
        }
      ],
      "role": "symbol",
      "title": "isHidden",
      "type": "topic",
      "url": "/documentation/photos/phassetchangerequest/ishidden"
    },
    "doc://com.apple.photokit/documentation/Photos/PHAssetChangeRequest/location": {
      "abstract": [
        {
          "text": "The location information saved with the asset.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "location"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)CLLocation",
          "text": "CLLocation"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.photokit/documentation/Photos/PHAssetChangeRequest/location",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "location"
        }
      ],
      "role": "symbol",
      "title": "location",
      "type": "topic",
      "url": "/documentation/photos/phassetchangerequest/location"
    },
    "doc://com.apple.photokit/documentation/Photos/PHAssetChangeRequest/placeholderForCreatedAsset": {
      "abstract": [
        {
          "text": "A placeholder object for the asset that the change request creates.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "placeholderForCreatedAsset"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)PHObjectPlaceholder",
          "text": "PHObjectPlaceholder"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.photokit/documentation/Photos/PHAssetChangeRequest/placeholderForCreatedAsset",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "placeholderForCreatedAsset"
        }
      ],
      "role": "symbol",
      "title": "placeholderForCreatedAsset",
      "type": "topic",
      "url": "/documentation/photos/phassetchangerequest/placeholderforcreatedasset"
    },
    "doc://com.apple.photokit/documentation/Photos/PHAssetChangeRequest/revertAssetContentToOriginal()": {
      "abstract": [
        {
          "text": "Request to revert any edits made to the asset’s content.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "revertAssetContentToOriginal"
        },
        {
          "kind": "text",
          "text": "()"
        }
      ],
      "identifier": "doc://com.apple.photokit/documentation/Photos/PHAssetChangeRequest/revertAssetContentToOriginal()",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "revertAssetContentToOriginal"
        }
      ],
      "role": "symbol",
      "title": "revertAssetContentToOriginal()",
      "type": "topic",
      "url": "/documentation/photos/phassetchangerequest/revertassetcontenttooriginal()"
    },
    "doc://com.apple.photokit/documentation/Photos/PHAssetCollectionChangeRequest": {
      "abstract": [
        {
          "text": "A request to create, delete, or modify a Photos asset collection, for use in a photo library change block.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "PHAssetCollectionChangeRequest"
        }
      ],
      "identifier": "doc://com.apple.photokit/documentation/Photos/PHAssetCollectionChangeRequest",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PHAssetCollectionChangeRequest"
        }
      ],
      "role": "symbol",
      "title": "PHAssetCollectionChangeRequest",
      "type": "topic",
      "url": "/documentation/photos/phassetcollectionchangerequest"
    },
    "doc://com.apple.photokit/documentation/Photos/PHAssetCreationRequest": {
      "abstract": [
        {
          "text": "A request to create a new Photos asset from underlying data resources, for use in a photo library change block.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "PHAssetCreationRequest"
        }
      ],
      "identifier": "doc://com.apple.photokit/documentation/Photos/PHAssetCreationRequest",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PHAssetCreationRequest"
        }
      ],
      "role": "symbol",
      "title": "PHAssetCreationRequest",
      "type": "topic",
      "url": "/documentation/photos/phassetcreationrequest"
    },
    "doc://com.apple.photokit/documentation/Photos/PHChangeRequest": {
      "abstract": [
        {
          "text": "The abstract base class of the framework’s photo library change requests.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "PHChangeRequest"
        }
      ],
      "identifier": "doc://com.apple.photokit/documentation/Photos/PHChangeRequest",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PHChangeRequest"
        }
      ],
      "role": "symbol",
      "title": "PHChangeRequest",
      "type": "topic",
      "url": "/documentation/photos/phchangerequest"
    },
    "doc://com.apple.photokit/documentation/Photos/PHCollectionListChangeRequest": {
      "abstract": [
        {
          "text": "A request to create, delete, or modify a Photos collection list, for use in a photo library change block.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "PHCollectionListChangeRequest"
        }
      ],
      "identifier": "doc://com.apple.photokit/documentation/Photos/PHCollectionListChangeRequest",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PHCollectionListChangeRequest"
        }
      ],
      "role": "symbol",
      "title": "PHCollectionListChangeRequest",
      "type": "topic",
      "url": "/documentation/photos/phcollectionlistchangerequest"
    },
    "doc://com.apple.photokit/documentation/Photos/PHObjectPlaceholder": {
      "abstract": [
        {
          "text": "A read-only proxy object that represents a Photos asset or collection to create.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "PHObjectPlaceholder"
        }
      ],
      "identifier": "doc://com.apple.photokit/documentation/Photos/PHObjectPlaceholder",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PHObjectPlaceholder"
        }
      ],
      "role": "symbol",
      "title": "PHObjectPlaceholder",
      "type": "topic",
      "url": "/documentation/photos/phobjectplaceholder"
    },
    "doc://com.apple.photokit/documentation/Photos/PHPhotoLibrary": {
      "abstract": [
        {
          "text": "An object that manages access and changes to the user’s photo library.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "PHPhotoLibrary"
        }
      ],
      "identifier": "doc://com.apple.photokit/documentation/Photos/PHPhotoLibrary",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PHPhotoLibrary"
        }
      ],
      "role": "symbol",
      "title": "PHPhotoLibrary",
      "type": "topic",
      "url": "/documentation/photos/phphotolibrary"
    },
    "doc://com.apple.photokit/documentation/Photos/PHPhotoLibrary/performChanges(_:completionHandler:)": {
      "abstract": [
        {
          "text": "Asynchronously runs a block that requests changes to the photo library.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "performChanges"
        },
        {
          "kind": "text",
          "text": "(() -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s4Voida",
          "text": "Void"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "completionHandler"
        },
        {
          "kind": "text",
          "text": ": (("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        },
        {
          "kind": "text",
          "text": ", (any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5ErrorP",
          "text": "Error"
        },
        {
          "kind": "text",
          "text": ")?) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s4Voida",
          "text": "Void"
        },
        {
          "kind": "text",
          "text": ")?)"
        }
      ],
      "identifier": "doc://com.apple.photokit/documentation/Photos/PHPhotoLibrary/performChanges(_:completionHandler:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "performChanges:completionHandler:"
        }
      ],
      "role": "symbol",
      "title": "performChanges(_:completionHandler:)",
      "type": "topic",
      "url": "/documentation/photos/phphotolibrary/performchanges(_:completionhandler:)"
    },
    "doc://com.apple.photokit/documentation/Photos/PHPhotoLibrary/performChangesAndWait(_:)": {
      "abstract": [
        {
          "text": "Synchronously runs a block that requests changes to be performed in the photo library.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "performChangesAndWait"
        },
        {
          "kind": "text",
          "text": "(() -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s4Voida",
          "text": "Void"
        },
        {
          "kind": "text",
          "text": ") "
        },
        {
          "kind": "keyword",
          "text": "throws"
        }
      ],
      "identifier": "doc://com.apple.photokit/documentation/Photos/PHPhotoLibrary/performChangesAndWait(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "performChangesAndWait:error:"
        }
      ],
      "role": "symbol",
      "title": "performChangesAndWait(_:)",
      "type": "topic",
      "url": "/documentation/photos/phphotolibrary/performchangesandwait(_:)"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)NSObject": {
      "abstract": [
        {
          "text": "The group of methods that are fundamental to all Objective-C objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "protocol "
        },
        {
          "kind": "identifier",
          "text": "NSObjectProtocol"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSObject",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSObjectProtocol",
      "type": "topic",
      "url": "/documentation/objectivec/nsobjectprotocol"
    },
    "doc://com.externally.resolved.symbol/s:SH": {
      "abstract": [
        {
          "text": "A type that can be hashed into a `Hasher` to produce an integer hash value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Hashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SQ",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SH",
      "kind": "symbol",
      "role": "symbol",
      "title": "Hashable",
      "type": "topic",
      "url": "/documentation/Swift/Hashable"
    },
    "doc://com.externally.resolved.symbol/s:SQ": {
      "abstract": [
        {
          "text": "A type that can be compared for value equality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SQ",
      "kind": "symbol",
      "role": "symbol",
      "title": "Equatable",
      "type": "topic",
      "url": "/documentation/Swift/Equatable"
    },
    "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP": {
      "abstract": [
        {
          "text": "A type with a customized textual representation.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CustomStringConvertible"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CustomStringConvertible",
      "type": "topic",
      "url": "/documentation/Swift/CustomStringConvertible"
    },
    "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP": {
      "abstract": [
        {
          "text": "A type with a customized textual representation suitable for debugging purposes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CustomDebugStringConvertible"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CustomDebugStringConvertible",
      "type": "topic",
      "url": "/documentation/Swift/CustomDebugStringConvertible"
    },
    "doc://com.externally.resolved.symbol/s:s7CVarArgP": {
      "abstract": [
        {
          "text": "A type whose instances can be encoded, and appropriately passed, as elements of a C `va_list`.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CVarArg"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s7CVarArgP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CVarArg",
      "type": "topic",
      "url": "/documentation/Swift/CVarArg"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.apple.photokit/documentation/Photos/PHChangeRequest"
      ],
      "kind": "relationships",
      "title": "Inherits From",
      "type": "inheritsFrom"
    },
    {
      "identifiers": [
        "doc://com.apple.photokit/documentation/Photos/PHAssetCreationRequest"
      ],
      "kind": "relationships",
      "title": "Inherited By",
      "type": "inheritedBy"
    },
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:s7CVarArgP",
        "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP",
        "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP",
        "doc://com.externally.resolved.symbol/s:SQ",
        "doc://com.externally.resolved.symbol/s:SH",
        "doc://com.externally.resolved.symbol/c:objc(pl)NSObject"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Updating-the-Library",
      "generated": true,
      "identifiers": [
        "doc://com.apple.photokit/documentation/PhotoKit/requesting-changes-to-the-photo-library",
        "doc://com.apple.photokit/documentation/Photos/PHPhotoLibrary/performChanges(_:completionHandler:)",
        "doc://com.apple.photokit/documentation/Photos/PHPhotoLibrary/performChangesAndWait(_:)",
        "doc://com.apple.photokit/documentation/Photos/PHChangeRequest",
        "doc://com.apple.photokit/documentation/Photos/PHAssetCollectionChangeRequest",
        "doc://com.apple.photokit/documentation/Photos/PHCollectionListChangeRequest",
        "doc://com.apple.photokit/documentation/Photos/PHObjectPlaceholder"
      ],
      "title": "Updating the Library"
    }
  ],
  "topicSections": [
    {
      "anchor": "Adding-New-Assets",
      "identifiers": [
        "doc://com.apple.photokit/documentation/Photos/PHAssetChangeRequest/creationRequestForAsset(from:)",
        "doc://com.apple.photokit/documentation/Photos/PHAssetChangeRequest/creationRequestForAssetFromImage(atFileURL:)",
        "doc://com.apple.photokit/documentation/Photos/PHAssetChangeRequest/creationRequestForAssetFromVideo(atFileURL:)",
        "doc://com.apple.photokit/documentation/Photos/PHAssetChangeRequest/placeholderForCreatedAsset"
      ],
      "title": "Adding New Assets"
    },
    {
      "anchor": "Deleting-Assets",
      "identifiers": [
        "doc://com.apple.photokit/documentation/Photos/PHAssetChangeRequest/deleteAssets(_:)"
      ],
      "title": "Deleting Assets"
    },
    {
      "anchor": "Modifying-Assets",
      "identifiers": [
        "doc://com.apple.photokit/documentation/Photos/PHAssetChangeRequest/init(for:)",
        "doc://com.apple.photokit/documentation/Photos/PHAssetChangeRequest/creationDate",
        "doc://com.apple.photokit/documentation/Photos/PHAssetChangeRequest/location",
        "doc://com.apple.photokit/documentation/Photos/PHAssetChangeRequest/isFavorite",
        "doc://com.apple.photokit/documentation/Photos/PHAssetChangeRequest/isHidden"
      ],
      "title": "Modifying Assets"
    },
    {
      "anchor": "Editing-Asset-Content",
      "identifiers": [
        "doc://com.apple.photokit/documentation/Photos/PHAssetChangeRequest/contentEditingOutput",
        "doc://com.apple.photokit/documentation/Photos/PHAssetChangeRequest/revertAssetContentToOriginal()"
      ],
      "title": "Editing Asset Content"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "8.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "8.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.1",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.15",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.0",
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Class"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "PHAssetChangeRequest"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "class"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PHAssetChangeRequest"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "PHAssetChangeRequest"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.photokit/documentation/Photos"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Adding-New-Assets",
              "identifiers": [
                "doc://com.apple.photokit/documentation/Photos/PHAssetChangeRequest/creationRequestForAsset(from:)",
                "doc://com.apple.photokit/documentation/Photos/PHAssetChangeRequest/creationRequestForAssetFromImage(atFileURL:)",
                "doc://com.apple.photokit/documentation/Photos/PHAssetChangeRequest/creationRequestForAssetFromVideo(atFileURL:)",
                "doc://com.apple.photokit/documentation/Photos/PHAssetChangeRequest/placeholderForCreatedAsset"
              ],
              "title": "Adding New Assets"
            },
            {
              "anchor": "Deleting-Assets",
              "identifiers": [
                "doc://com.apple.photokit/documentation/Photos/PHAssetChangeRequest/deleteAssets(_:)"
              ],
              "title": "Deleting Assets"
            },
            {
              "anchor": "Modifying-Assets",
              "identifiers": [
                "doc://com.apple.photokit/documentation/Photos/PHAssetChangeRequest/init(for:)",
                "doc://com.apple.photokit/documentation/Photos/PHAssetChangeRequest/creationDate",
                "doc://com.apple.photokit/documentation/Photos/PHAssetChangeRequest/location",
                "doc://com.apple.photokit/documentation/Photos/PHAssetChangeRequest/isFavorite",
                "doc://com.apple.photokit/documentation/Photos/PHAssetChangeRequest/isHidden"
              ],
              "title": "Modifying Assets"
            },
            {
              "anchor": "Editing-Asset-Content",
              "identifiers": [
                "doc://com.apple.photokit/documentation/Photos/PHAssetChangeRequest/contentEditingOutput",
                "doc://com.apple.photokit/documentation/Photos/PHAssetChangeRequest/revertAssetContentToOriginal()"
              ],
              "title": "Editing Asset Content"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": [
            {
              "identifiers": [
                "doc://com.apple.photokit/documentation/Photos/PHChangeRequest"
              ],
              "kind": "relationships",
              "title": "Inherits From",
              "type": "inheritsFrom"
            },
            {
              "identifiers": [
                "doc://com.apple.photokit/documentation/Photos/PHAssetCreationRequest"
              ],
              "kind": "relationships",
              "title": "Inherited By",
              "type": "inheritedBy"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Updating-the-Library",
              "generated": true,
              "identifiers": [
                "doc://com.apple.photokit/documentation/Photos/PHPhotoLibrary/performChanges(_:completionHandler:)",
                "doc://com.apple.photokit/documentation/Photos/PHPhotoLibrary/performChangesAndWait(_:)",
                "doc://com.apple.photokit/documentation/Photos/PHChangeRequest",
                "doc://com.apple.photokit/documentation/Photos/PHAssetCollectionChangeRequest",
                "doc://com.apple.photokit/documentation/Photos/PHCollectionListChangeRequest",
                "doc://com.apple.photokit/documentation/Photos/PHObjectPlaceholder"
              ],
              "title": "Updating the Library"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "@interface"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "PHAssetChangeRequest"
                  },
                  {
                    "kind": "text",
                    "text": " : "
                  },
                  {
                    "identifier": "doc://com.apple.photokit/documentation/Photos/PHChangeRequest",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(cs)PHChangeRequest",
                    "text": "PHChangeRequest"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHAssetChangeRequest~1isFavorite/title",
          "value": "favorite"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHAssetChangeRequest~1isFavorite/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "favorite"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHPhotoLibrary/title",
          "value": "PHPhotoLibrary"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHPhotoLibrary/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PHPhotoLibrary"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHPhotoLibrary/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "PHPhotoLibrary"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHAssetChangeRequest~1creationRequestForAssetFromVideo(atFileURL:)/title",
          "value": "creationRequestForAssetFromVideoAtFileURL:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHAssetChangeRequest~1creationRequestForAssetFromVideo(atFileURL:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "+ "
            },
            {
              "kind": "identifier",
              "text": "creationRequestForAssetFromVideoAtFileURL:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHAssetChangeRequest~1contentEditingOutput/title",
          "value": "contentEditingOutput"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHAssetChangeRequest~1contentEditingOutput/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "contentEditingOutput"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHAssetChangeRequest~1creationRequestForAsset(from:)/title",
          "value": "creationRequestForAssetFromImage:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHAssetChangeRequest~1creationRequestForAsset(from:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "+ "
            },
            {
              "kind": "identifier",
              "text": "creationRequestForAssetFromImage:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHAssetChangeRequest~1isHidden/title",
          "value": "hidden"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHAssetChangeRequest~1isHidden/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "hidden"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHPhotoLibrary~1performChangesAndWait(_:)/title",
          "value": "performChangesAndWait:error:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHPhotoLibrary~1performChangesAndWait(_:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "performChangesAndWait:error:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHPhotoLibrary~1performChanges(_:completionHandler:)/title",
          "value": "performChanges:completionHandler:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHPhotoLibrary~1performChanges(_:completionHandler:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "performChanges:completionHandler:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:objc(pl)NSObject/title",
          "value": "NSObject"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHAssetChangeRequest~1init(for:)/title",
          "value": "changeRequestForAsset:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHAssetChangeRequest~1init(for:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "+ "
            },
            {
              "kind": "identifier",
              "text": "changeRequestForAsset:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHAssetChangeRequest~1creationRequestForAssetFromImage(atFileURL:)/title",
          "value": "creationRequestForAssetFromImageAtFileURL:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHAssetChangeRequest~1creationRequestForAssetFromImage(atFileURL:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "+ "
            },
            {
              "kind": "identifier",
              "text": "creationRequestForAssetFromImageAtFileURL:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHAssetCreationRequest/title",
          "value": "PHAssetCreationRequest"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHAssetCreationRequest/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PHAssetCreationRequest"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHAssetCreationRequest/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "PHAssetCreationRequest"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHCollectionListChangeRequest/title",
          "value": "PHCollectionListChangeRequest"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHCollectionListChangeRequest/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PHCollectionListChangeRequest"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHCollectionListChangeRequest/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "PHCollectionListChangeRequest"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHAssetChangeRequest~1creationDate/title",
          "value": "creationDate"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHAssetChangeRequest~1creationDate/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "creationDate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHAssetCollectionChangeRequest/title",
          "value": "PHAssetCollectionChangeRequest"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHAssetCollectionChangeRequest/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PHAssetCollectionChangeRequest"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHAssetCollectionChangeRequest/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "PHAssetCollectionChangeRequest"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHAssetChangeRequest~1location/title",
          "value": "location"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHAssetChangeRequest~1location/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "location"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHChangeRequest/title",
          "value": "PHChangeRequest"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHChangeRequest/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PHChangeRequest"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHChangeRequest/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "PHChangeRequest"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHAsset/title",
          "value": "PHAsset"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHAsset/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PHAsset"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHAsset/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "PHAsset"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHObjectPlaceholder/title",
          "value": "PHObjectPlaceholder"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHObjectPlaceholder/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PHObjectPlaceholder"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHObjectPlaceholder/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "PHObjectPlaceholder"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHAssetChangeRequest~1deleteAssets(_:)/title",
          "value": "deleteAssets:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHAssetChangeRequest~1deleteAssets(_:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "+ "
            },
            {
              "kind": "identifier",
              "text": "deleteAssets:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHAssetChangeRequest~1placeholderForCreatedAsset/title",
          "value": "placeholderForCreatedAsset"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHAssetChangeRequest~1placeholderForCreatedAsset/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "placeholderForCreatedAsset"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHAssetChangeRequest~1revertAssetContentToOriginal()/title",
          "value": "revertAssetContentToOriginal"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHAssetChangeRequest~1revertAssetContentToOriginal()/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "revertAssetContentToOriginal"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHAssetChangeRequest/title",
          "value": "PHAssetChangeRequest"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHAssetChangeRequest/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PHAssetChangeRequest"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHAssetChangeRequest/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "PHAssetChangeRequest"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/photos/phassetchangerequest"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/photos/phassetchangerequest"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
