{
  "abstract": [
    {
      "text": "A request to create, delete, or modify a Photos asset collection, for use in a photo library change block.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.photokit/documentation/Photos"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.photokit/documentation/Photos/PHAssetCollectionChangeRequest"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(cs)PHAssetCollectionChangeRequest",
    "fragments": [
      {
        "kind": "keyword",
        "text": "class"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "PHAssetCollectionChangeRequest"
      }
    ],
    "modules": [
      {
        "name": "Photos"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "PHAssetCollectionChangeRequest"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "8.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "8.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.1",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.15",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.0",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Class",
    "symbolKind": "class",
    "title": "PHAssetCollectionChangeRequest"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "class"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "PHAssetCollectionChangeRequest"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "kind": "mentions",
      "mentions": [
        "doc://com.apple.photokit/documentation/PhotoKit/requesting-changes-to-the-photo-library"
      ]
    },
    {
      "content": [
        {
          "anchor": "overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "You use the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.photokit/documentation/Photos/PHAssetCollectionChangeRequest",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " class to request changes for ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.photokit/documentation/Photos/PHAssetCollection",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " objects. To make changes to asset collections (such as user-created albums) in the Photos library, create a change request using the appropriate class method for the change you want to perform.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "items": [
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Call the ",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.photokit/documentation/Photos/PHAssetCollectionChangeRequest/creationRequestForAssetCollection(withTitle:)",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": " method to create a new asset collection.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Call the ",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.photokit/documentation/Photos/PHAssetCollectionChangeRequest/deleteAssetCollections(_:)",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": " method to delete existing asset collections.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Call the ",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.photokit/documentation/Photos/PHAssetCollectionChangeRequest/init(for:)",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": " or ",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.photokit/documentation/Photos/PHAssetCollectionChangeRequest/init(for:assets:)",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": " method to modify a collection’s metadata or list of member assets.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            }
          ],
          "type": "unorderedList"
        },
        {
          "inlineContent": [
            {
              "text": "Before creating a change request, use the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.photokit/documentation/Photos/PHCollection/canPerform(_:)",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " method to verify that the collection allows the edit operation you’re requesting. If you attempt to perform an unsupported edit operation, Photos throws an exception.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "A change request for creating or modifying an asset collection works like a mutable version of the asset collection object. Use the change request’s properties and instance methods to request changes to the asset collection itself. For example, the following code removes an asset from an album.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "tabs": [
            {
              "content": [
                {
                  "code": [
                    "PHPhotoLibrary.shared().performChanges {",
                    "",
                    "    let request = PHAssetCollectionChangeRequest(for: myAlbum,",
                    "                                                 assets: albumAssetsFetchResult)",
                    "    ",
                    "    request!.removeAssets([asset] as NSFastEnumeration)",
                    "",
                    "} completionHandler: { success, error in",
                    "    print(\"Finished removing the asset from the album. \\(success ? \"Success\" : String(describing: error))\")",
                    "}"
                  ],
                  "syntax": "swift",
                  "type": "codeListing"
                }
              ],
              "title": "Swift"
            },
            {
              "content": [
                {
                  "code": [
                    "[[PHPhotoLibrary sharedPhotoLibrary] performChanges:^{",
                    "        ",
                    "    PHAssetCollectionChangeRequest *request =",
                    "        [PHAssetCollectionChangeRequest changeRequestForAssetCollection:myAlbum",
                    "                                                                 assets:albumAssetsFetchResult];",
                    "        ",
                    "    [request removeAssets:@[asset]];",
                    "     ",
                    "} completionHandler:^(BOOL success, NSError *error) {",
                    "    NSLog(@\"Finished removing the asset from the album. %@\", (success ? @\"Success\" : error));",
                    "}];"
                  ],
                  "syntax": "objc",
                  "type": "codeListing"
                }
              ],
              "title": "Objective-C"
            }
          ],
          "type": "tabNavigator"
        },
        {
          "inlineContent": [
            {
              "text": "After Photos runs the change block and calls your completion handler, the asset collection’s state reflects the changes you requested in the block.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "If you create or use a change request object outside a photo library change block, Photos raises an Objective-C exception. For details on change blocks, see ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.photokit/documentation/Photos/PHPhotoLibrary",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ".",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.photokit/documentation/PhotoKit/requesting-changes-to-the-photo-library": {
      "abstract": [
        {
          "text": "Create, delete, or modify assets and collections in a photo library by making change requests.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.photokit/documentation/PhotoKit/requesting-changes-to-the-photo-library",
      "kind": "article",
      "role": "article",
      "title": "Requesting Changes to the Photo Library",
      "type": "topic",
      "url": "/documentation/photokit/requesting-changes-to-the-photo-library"
    },
    "doc://com.apple.photokit/documentation/Photos": {
      "abstract": [
        {
          "text": "Work with image and video assets that the Photos app manages, including those from iCloud Photos and Live Photos.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.photokit/documentation/Photos",
      "kind": "symbol",
      "role": "collection",
      "title": "Photos",
      "type": "topic",
      "url": "/documentation/photos"
    },
    "doc://com.apple.photokit/documentation/Photos/PHAssetChangeRequest": {
      "abstract": [
        {
          "text": "A request to create, delete, change metadata for, or edit the content of a Photos asset, for use in a photo library change block.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "PHAssetChangeRequest"
        }
      ],
      "identifier": "doc://com.apple.photokit/documentation/Photos/PHAssetChangeRequest",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PHAssetChangeRequest"
        }
      ],
      "role": "symbol",
      "title": "PHAssetChangeRequest",
      "type": "topic",
      "url": "/documentation/photos/phassetchangerequest"
    },
    "doc://com.apple.photokit/documentation/Photos/PHAssetCollection": {
      "abstract": [
        {
          "text": "A representation of a Photos asset grouping, such as a moment, user-created album, or smart album.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "PHAssetCollection"
        }
      ],
      "identifier": "doc://com.apple.photokit/documentation/Photos/PHAssetCollection",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PHAssetCollection"
        }
      ],
      "role": "symbol",
      "title": "PHAssetCollection",
      "type": "topic",
      "url": "/documentation/photos/phassetcollection"
    },
    "doc://com.apple.photokit/documentation/Photos/PHAssetCollectionChangeRequest": {
      "abstract": [
        {
          "text": "A request to create, delete, or modify a Photos asset collection, for use in a photo library change block.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "PHAssetCollectionChangeRequest"
        }
      ],
      "identifier": "doc://com.apple.photokit/documentation/Photos/PHAssetCollectionChangeRequest",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PHAssetCollectionChangeRequest"
        }
      ],
      "role": "symbol",
      "title": "PHAssetCollectionChangeRequest",
      "type": "topic",
      "url": "/documentation/photos/phassetcollectionchangerequest"
    },
    "doc://com.apple.photokit/documentation/Photos/PHAssetCollectionChangeRequest/addAssets(_:)": {
      "abstract": [
        {
          "text": "Adds the specified assets to the asset collection.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "addAssets"
        },
        {
          "kind": "text",
          "text": "(any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(pl)NSFastEnumeration",
          "text": "NSFastEnumeration"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.photokit/documentation/Photos/PHAssetCollectionChangeRequest/addAssets(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "addAssets:"
        }
      ],
      "role": "symbol",
      "title": "addAssets(_:)",
      "type": "topic",
      "url": "/documentation/photos/phassetcollectionchangerequest/addassets(_:)"
    },
    "doc://com.apple.photokit/documentation/Photos/PHAssetCollectionChangeRequest/creationRequestForAssetCollection(withTitle:)": {
      "abstract": [
        {
          "text": "Creates a request for adding a new asset collection to the Photos library.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "creationRequestForAssetCollection"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "withTitle"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "text": "Self"
        }
      ],
      "identifier": "doc://com.apple.photokit/documentation/Photos/PHAssetCollectionChangeRequest/creationRequestForAssetCollection(withTitle:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "creationRequestForAssetCollectionWithTitle:"
        }
      ],
      "role": "symbol",
      "title": "creationRequestForAssetCollection(withTitle:)",
      "type": "topic",
      "url": "/documentation/photos/phassetcollectionchangerequest/creationrequestforassetcollection(withtitle:)"
    },
    "doc://com.apple.photokit/documentation/Photos/PHAssetCollectionChangeRequest/deleteAssetCollections(_:)": {
      "abstract": [
        {
          "text": "Requests that the specified asset collections be deleted.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "deleteAssetCollections"
        },
        {
          "kind": "text",
          "text": "(any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(pl)NSFastEnumeration",
          "text": "NSFastEnumeration"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.photokit/documentation/Photos/PHAssetCollectionChangeRequest/deleteAssetCollections(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "deleteAssetCollections:"
        }
      ],
      "role": "symbol",
      "title": "deleteAssetCollections(_:)",
      "type": "topic",
      "url": "/documentation/photos/phassetcollectionchangerequest/deleteassetcollections(_:)"
    },
    "doc://com.apple.photokit/documentation/Photos/PHAssetCollectionChangeRequest/init(for:)": {
      "abstract": [
        {
          "text": "Creates a request for modifying the specified asset collection.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "convenience"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "?("
        },
        {
          "kind": "externalParam",
          "text": "for"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)PHAssetCollection",
          "text": "PHAssetCollection"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.photokit/documentation/Photos/PHAssetCollectionChangeRequest/init(for:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "changeRequestForAssetCollection:"
        }
      ],
      "role": "symbol",
      "title": "init(for:)",
      "type": "topic",
      "url": "/documentation/photos/phassetcollectionchangerequest/init(for:)"
    },
    "doc://com.apple.photokit/documentation/Photos/PHAssetCollectionChangeRequest/init(for:assets:)": {
      "abstract": [
        {
          "text": "Creates a request for modifying the specified asset collection, with a fetch result for tracking changes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "convenience"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "?("
        },
        {
          "kind": "externalParam",
          "text": "for"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)PHAssetCollection",
          "text": "PHAssetCollection"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "assets"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)PHFetchResult",
          "text": "PHFetchResult"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)PHAsset",
          "text": "PHAsset"
        },
        {
          "kind": "text",
          "text": ">?)"
        }
      ],
      "identifier": "doc://com.apple.photokit/documentation/Photos/PHAssetCollectionChangeRequest/init(for:assets:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "changeRequestForAssetCollection:assets:"
        }
      ],
      "role": "symbol",
      "title": "init(for:assets:)",
      "type": "topic",
      "url": "/documentation/photos/phassetcollectionchangerequest/init(for:assets:)"
    },
    "doc://com.apple.photokit/documentation/Photos/PHAssetCollectionChangeRequest/insertAssets(_:at:)": {
      "abstract": [
        {
          "text": "Inserts the specified assets into the collection at the specified indexes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "insertAssets"
        },
        {
          "kind": "text",
          "text": "(any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(pl)NSFastEnumeration",
          "text": "NSFastEnumeration"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "at"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10Foundation8IndexSetV",
          "text": "IndexSet"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.photokit/documentation/Photos/PHAssetCollectionChangeRequest/insertAssets(_:at:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "insertAssets:atIndexes:"
        }
      ],
      "role": "symbol",
      "title": "insertAssets(_:at:)",
      "type": "topic",
      "url": "/documentation/photos/phassetcollectionchangerequest/insertassets(_:at:)"
    },
    "doc://com.apple.photokit/documentation/Photos/PHAssetCollectionChangeRequest/moveAssets(at:to:)": {
      "abstract": [
        {
          "text": "Moves the assets at the specified indexes in the asset collection to a new index.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "moveAssets"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "at"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10Foundation8IndexSetV",
          "text": "IndexSet"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "to"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.photokit/documentation/Photos/PHAssetCollectionChangeRequest/moveAssets(at:to:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "moveAssetsAtIndexes:toIndex:"
        }
      ],
      "role": "symbol",
      "title": "moveAssets(at:to:)",
      "type": "topic",
      "url": "/documentation/photos/phassetcollectionchangerequest/moveassets(at:to:)"
    },
    "doc://com.apple.photokit/documentation/Photos/PHAssetCollectionChangeRequest/placeholderForCreatedAssetCollection": {
      "abstract": [
        {
          "text": "A placeholder object for the asset collection that the change request creates.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "placeholderForCreatedAssetCollection"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)PHObjectPlaceholder",
          "text": "PHObjectPlaceholder"
        }
      ],
      "identifier": "doc://com.apple.photokit/documentation/Photos/PHAssetCollectionChangeRequest/placeholderForCreatedAssetCollection",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "placeholderForCreatedAssetCollection"
        }
      ],
      "role": "symbol",
      "title": "placeholderForCreatedAssetCollection",
      "type": "topic",
      "url": "/documentation/photos/phassetcollectionchangerequest/placeholderforcreatedassetcollection"
    },
    "doc://com.apple.photokit/documentation/Photos/PHAssetCollectionChangeRequest/removeAssets(_:)": {
      "abstract": [
        {
          "text": "Removes the specified assets from the asset collection.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "removeAssets"
        },
        {
          "kind": "text",
          "text": "(any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(pl)NSFastEnumeration",
          "text": "NSFastEnumeration"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.photokit/documentation/Photos/PHAssetCollectionChangeRequest/removeAssets(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "removeAssets:"
        }
      ],
      "role": "symbol",
      "title": "removeAssets(_:)",
      "type": "topic",
      "url": "/documentation/photos/phassetcollectionchangerequest/removeassets(_:)"
    },
    "doc://com.apple.photokit/documentation/Photos/PHAssetCollectionChangeRequest/removeAssets(at:)": {
      "abstract": [
        {
          "text": "Removes the assets at the specified indexes from the asset collection.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "removeAssets"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "at"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10Foundation8IndexSetV",
          "text": "IndexSet"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.photokit/documentation/Photos/PHAssetCollectionChangeRequest/removeAssets(at:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "removeAssetsAtIndexes:"
        }
      ],
      "role": "symbol",
      "title": "removeAssets(at:)",
      "type": "topic",
      "url": "/documentation/photos/phassetcollectionchangerequest/removeassets(at:)"
    },
    "doc://com.apple.photokit/documentation/Photos/PHAssetCollectionChangeRequest/replaceAssets(at:withAssets:)": {
      "abstract": [
        {
          "text": "Replaces the assets at the specified indexes in the asset collection with the specified assets.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "replaceAssets"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "at"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10Foundation8IndexSetV",
          "text": "IndexSet"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "withAssets"
        },
        {
          "kind": "text",
          "text": ": any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(pl)NSFastEnumeration",
          "text": "NSFastEnumeration"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.photokit/documentation/Photos/PHAssetCollectionChangeRequest/replaceAssets(at:withAssets:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "replaceAssetsAtIndexes:withAssets:"
        }
      ],
      "role": "symbol",
      "title": "replaceAssets(at:withAssets:)",
      "type": "topic",
      "url": "/documentation/photos/phassetcollectionchangerequest/replaceassets(at:withassets:)"
    },
    "doc://com.apple.photokit/documentation/Photos/PHAssetCollectionChangeRequest/title": {
      "abstract": [
        {
          "text": "The displayed name of the asset collection.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "title"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.photokit/documentation/Photos/PHAssetCollectionChangeRequest/title",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "title"
        }
      ],
      "role": "symbol",
      "title": "title",
      "type": "topic",
      "url": "/documentation/photos/phassetcollectionchangerequest/title"
    },
    "doc://com.apple.photokit/documentation/Photos/PHChangeRequest": {
      "abstract": [
        {
          "text": "The abstract base class of the framework’s photo library change requests.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "PHChangeRequest"
        }
      ],
      "identifier": "doc://com.apple.photokit/documentation/Photos/PHChangeRequest",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PHChangeRequest"
        }
      ],
      "role": "symbol",
      "title": "PHChangeRequest",
      "type": "topic",
      "url": "/documentation/photos/phchangerequest"
    },
    "doc://com.apple.photokit/documentation/Photos/PHCollection/canPerform(_:)": {
      "abstract": [
        {
          "text": "Returns whether the collection supports the specified editing operation.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "canPerform"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@PHCollectionEditOperation",
          "text": "PHCollectionEditOperation"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.photokit/documentation/Photos/PHCollection/canPerform(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "canPerformEditOperation:"
        }
      ],
      "role": "symbol",
      "title": "canPerform(_:)",
      "type": "topic",
      "url": "/documentation/photos/phcollection/canperform(_:)"
    },
    "doc://com.apple.photokit/documentation/Photos/PHCollectionListChangeRequest": {
      "abstract": [
        {
          "text": "A request to create, delete, or modify a Photos collection list, for use in a photo library change block.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "PHCollectionListChangeRequest"
        }
      ],
      "identifier": "doc://com.apple.photokit/documentation/Photos/PHCollectionListChangeRequest",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PHCollectionListChangeRequest"
        }
      ],
      "role": "symbol",
      "title": "PHCollectionListChangeRequest",
      "type": "topic",
      "url": "/documentation/photos/phcollectionlistchangerequest"
    },
    "doc://com.apple.photokit/documentation/Photos/PHObjectPlaceholder": {
      "abstract": [
        {
          "text": "A read-only proxy object that represents a Photos asset or collection to create.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "PHObjectPlaceholder"
        }
      ],
      "identifier": "doc://com.apple.photokit/documentation/Photos/PHObjectPlaceholder",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PHObjectPlaceholder"
        }
      ],
      "role": "symbol",
      "title": "PHObjectPlaceholder",
      "type": "topic",
      "url": "/documentation/photos/phobjectplaceholder"
    },
    "doc://com.apple.photokit/documentation/Photos/PHPhotoLibrary": {
      "abstract": [
        {
          "text": "An object that manages access and changes to the user’s photo library.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "PHPhotoLibrary"
        }
      ],
      "identifier": "doc://com.apple.photokit/documentation/Photos/PHPhotoLibrary",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PHPhotoLibrary"
        }
      ],
      "role": "symbol",
      "title": "PHPhotoLibrary",
      "type": "topic",
      "url": "/documentation/photos/phphotolibrary"
    },
    "doc://com.apple.photokit/documentation/Photos/PHPhotoLibrary/performChanges(_:completionHandler:)": {
      "abstract": [
        {
          "text": "Asynchronously runs a block that requests changes to the photo library.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "performChanges"
        },
        {
          "kind": "text",
          "text": "(() -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s4Voida",
          "text": "Void"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "completionHandler"
        },
        {
          "kind": "text",
          "text": ": (("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        },
        {
          "kind": "text",
          "text": ", (any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5ErrorP",
          "text": "Error"
        },
        {
          "kind": "text",
          "text": ")?) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s4Voida",
          "text": "Void"
        },
        {
          "kind": "text",
          "text": ")?)"
        }
      ],
      "identifier": "doc://com.apple.photokit/documentation/Photos/PHPhotoLibrary/performChanges(_:completionHandler:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "performChanges:completionHandler:"
        }
      ],
      "role": "symbol",
      "title": "performChanges(_:completionHandler:)",
      "type": "topic",
      "url": "/documentation/photos/phphotolibrary/performchanges(_:completionhandler:)"
    },
    "doc://com.apple.photokit/documentation/Photos/PHPhotoLibrary/performChangesAndWait(_:)": {
      "abstract": [
        {
          "text": "Synchronously runs a block that requests changes to be performed in the photo library.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "performChangesAndWait"
        },
        {
          "kind": "text",
          "text": "(() -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s4Voida",
          "text": "Void"
        },
        {
          "kind": "text",
          "text": ") "
        },
        {
          "kind": "keyword",
          "text": "throws"
        }
      ],
      "identifier": "doc://com.apple.photokit/documentation/Photos/PHPhotoLibrary/performChangesAndWait(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "performChangesAndWait:error:"
        }
      ],
      "role": "symbol",
      "title": "performChangesAndWait(_:)",
      "type": "topic",
      "url": "/documentation/photos/phphotolibrary/performchangesandwait(_:)"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)NSObject": {
      "abstract": [
        {
          "text": "The group of methods that are fundamental to all Objective-C objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "protocol "
        },
        {
          "kind": "identifier",
          "text": "NSObjectProtocol"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSObject",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSObjectProtocol",
      "type": "topic",
      "url": "/documentation/objectivec/nsobjectprotocol"
    },
    "doc://com.externally.resolved.symbol/s:SH": {
      "abstract": [
        {
          "text": "A type that can be hashed into a `Hasher` to produce an integer hash value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Hashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SQ",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SH",
      "kind": "symbol",
      "role": "symbol",
      "title": "Hashable",
      "type": "topic",
      "url": "/documentation/Swift/Hashable"
    },
    "doc://com.externally.resolved.symbol/s:SQ": {
      "abstract": [
        {
          "text": "A type that can be compared for value equality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SQ",
      "kind": "symbol",
      "role": "symbol",
      "title": "Equatable",
      "type": "topic",
      "url": "/documentation/Swift/Equatable"
    },
    "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP": {
      "abstract": [
        {
          "text": "A type with a customized textual representation.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CustomStringConvertible"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CustomStringConvertible",
      "type": "topic",
      "url": "/documentation/Swift/CustomStringConvertible"
    },
    "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP": {
      "abstract": [
        {
          "text": "A type with a customized textual representation suitable for debugging purposes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CustomDebugStringConvertible"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CustomDebugStringConvertible",
      "type": "topic",
      "url": "/documentation/Swift/CustomDebugStringConvertible"
    },
    "doc://com.externally.resolved.symbol/s:s7CVarArgP": {
      "abstract": [
        {
          "text": "A type whose instances can be encoded, and appropriately passed, as elements of a C `va_list`.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CVarArg"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s7CVarArgP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CVarArg",
      "type": "topic",
      "url": "/documentation/Swift/CVarArg"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.apple.photokit/documentation/Photos/PHChangeRequest"
      ],
      "kind": "relationships",
      "title": "Inherits From",
      "type": "inheritsFrom"
    },
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:s7CVarArgP",
        "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP",
        "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP",
        "doc://com.externally.resolved.symbol/s:SQ",
        "doc://com.externally.resolved.symbol/s:SH",
        "doc://com.externally.resolved.symbol/c:objc(pl)NSObject"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Updating-the-Library",
      "generated": true,
      "identifiers": [
        "doc://com.apple.photokit/documentation/PhotoKit/requesting-changes-to-the-photo-library",
        "doc://com.apple.photokit/documentation/Photos/PHPhotoLibrary/performChanges(_:completionHandler:)",
        "doc://com.apple.photokit/documentation/Photos/PHPhotoLibrary/performChangesAndWait(_:)",
        "doc://com.apple.photokit/documentation/Photos/PHChangeRequest",
        "doc://com.apple.photokit/documentation/Photos/PHAssetChangeRequest",
        "doc://com.apple.photokit/documentation/Photos/PHCollectionListChangeRequest",
        "doc://com.apple.photokit/documentation/Photos/PHObjectPlaceholder"
      ],
      "title": "Updating the Library"
    }
  ],
  "topicSections": [
    {
      "anchor": "Adding-New-Asset-Collections",
      "identifiers": [
        "doc://com.apple.photokit/documentation/Photos/PHAssetCollectionChangeRequest/creationRequestForAssetCollection(withTitle:)",
        "doc://com.apple.photokit/documentation/Photos/PHAssetCollectionChangeRequest/placeholderForCreatedAssetCollection"
      ],
      "title": "Adding New Asset Collections"
    },
    {
      "anchor": "Deleting-Asset-Collections",
      "identifiers": [
        "doc://com.apple.photokit/documentation/Photos/PHAssetCollectionChangeRequest/deleteAssetCollections(_:)"
      ],
      "title": "Deleting Asset Collections"
    },
    {
      "anchor": "Modifying-Asset-Collections",
      "identifiers": [
        "doc://com.apple.photokit/documentation/Photos/PHAssetCollectionChangeRequest/init(for:)",
        "doc://com.apple.photokit/documentation/Photos/PHAssetCollectionChangeRequest/init(for:assets:)",
        "doc://com.apple.photokit/documentation/Photos/PHAssetCollectionChangeRequest/title",
        "doc://com.apple.photokit/documentation/Photos/PHAssetCollectionChangeRequest/addAssets(_:)",
        "doc://com.apple.photokit/documentation/Photos/PHAssetCollectionChangeRequest/insertAssets(_:at:)",
        "doc://com.apple.photokit/documentation/Photos/PHAssetCollectionChangeRequest/removeAssets(_:)",
        "doc://com.apple.photokit/documentation/Photos/PHAssetCollectionChangeRequest/removeAssets(at:)",
        "doc://com.apple.photokit/documentation/Photos/PHAssetCollectionChangeRequest/replaceAssets(at:withAssets:)",
        "doc://com.apple.photokit/documentation/Photos/PHAssetCollectionChangeRequest/moveAssets(at:to:)"
      ],
      "title": "Modifying Asset Collections"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "8.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "8.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.1",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.15",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.0",
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Class"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "PHAssetCollectionChangeRequest"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "class"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PHAssetCollectionChangeRequest"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "PHAssetCollectionChangeRequest"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.photokit/documentation/Photos"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Adding-New-Asset-Collections",
              "identifiers": [
                "doc://com.apple.photokit/documentation/Photos/PHAssetCollectionChangeRequest/creationRequestForAssetCollection(withTitle:)",
                "doc://com.apple.photokit/documentation/Photos/PHAssetCollectionChangeRequest/placeholderForCreatedAssetCollection"
              ],
              "title": "Adding New Asset Collections"
            },
            {
              "anchor": "Deleting-Asset-Collections",
              "identifiers": [
                "doc://com.apple.photokit/documentation/Photos/PHAssetCollectionChangeRequest/deleteAssetCollections(_:)"
              ],
              "title": "Deleting Asset Collections"
            },
            {
              "anchor": "Modifying-Asset-Collections",
              "identifiers": [
                "doc://com.apple.photokit/documentation/Photos/PHAssetCollectionChangeRequest/init(for:)",
                "doc://com.apple.photokit/documentation/Photos/PHAssetCollectionChangeRequest/init(for:assets:)",
                "doc://com.apple.photokit/documentation/Photos/PHAssetCollectionChangeRequest/title",
                "doc://com.apple.photokit/documentation/Photos/PHAssetCollectionChangeRequest/addAssets(_:)",
                "doc://com.apple.photokit/documentation/Photos/PHAssetCollectionChangeRequest/insertAssets(_:at:)",
                "doc://com.apple.photokit/documentation/Photos/PHAssetCollectionChangeRequest/removeAssets(_:)",
                "doc://com.apple.photokit/documentation/Photos/PHAssetCollectionChangeRequest/removeAssets(at:)",
                "doc://com.apple.photokit/documentation/Photos/PHAssetCollectionChangeRequest/replaceAssets(at:withAssets:)",
                "doc://com.apple.photokit/documentation/Photos/PHAssetCollectionChangeRequest/moveAssets(at:to:)"
              ],
              "title": "Modifying Asset Collections"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": [
            {
              "identifiers": [
                "doc://com.apple.photokit/documentation/Photos/PHChangeRequest"
              ],
              "kind": "relationships",
              "title": "Inherits From",
              "type": "inheritsFrom"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Updating-the-Library",
              "generated": true,
              "identifiers": [
                "doc://com.apple.photokit/documentation/Photos/PHPhotoLibrary/performChanges(_:completionHandler:)",
                "doc://com.apple.photokit/documentation/Photos/PHPhotoLibrary/performChangesAndWait(_:)",
                "doc://com.apple.photokit/documentation/Photos/PHChangeRequest",
                "doc://com.apple.photokit/documentation/Photos/PHAssetChangeRequest",
                "doc://com.apple.photokit/documentation/Photos/PHCollectionListChangeRequest",
                "doc://com.apple.photokit/documentation/Photos/PHObjectPlaceholder"
              ],
              "title": "Updating the Library"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "@interface"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "PHAssetCollectionChangeRequest"
                  },
                  {
                    "kind": "text",
                    "text": " : "
                  },
                  {
                    "identifier": "doc://com.apple.photokit/documentation/Photos/PHChangeRequest",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(cs)PHChangeRequest",
                    "text": "PHChangeRequest"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHAssetCollectionChangeRequest~1removeAssets(at:)/title",
          "value": "removeAssetsAtIndexes:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHAssetCollectionChangeRequest~1removeAssets(at:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "removeAssetsAtIndexes:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHAssetCollectionChangeRequest~1moveAssets(at:to:)/title",
          "value": "moveAssetsAtIndexes:toIndex:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHAssetCollectionChangeRequest~1moveAssets(at:to:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "moveAssetsAtIndexes:toIndex:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHAssetCollectionChangeRequest~1deleteAssetCollections(_:)/title",
          "value": "deleteAssetCollections:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHAssetCollectionChangeRequest~1deleteAssetCollections(_:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "+ "
            },
            {
              "kind": "identifier",
              "text": "deleteAssetCollections:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHAssetCollectionChangeRequest/title",
          "value": "PHAssetCollectionChangeRequest"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHAssetCollectionChangeRequest/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PHAssetCollectionChangeRequest"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHAssetCollectionChangeRequest/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "PHAssetCollectionChangeRequest"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHAssetCollection/title",
          "value": "PHAssetCollection"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHAssetCollection/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PHAssetCollection"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHAssetCollection/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "PHAssetCollection"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHPhotoLibrary~1performChanges(_:completionHandler:)/title",
          "value": "performChanges:completionHandler:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHPhotoLibrary~1performChanges(_:completionHandler:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "performChanges:completionHandler:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHObjectPlaceholder/title",
          "value": "PHObjectPlaceholder"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHObjectPlaceholder/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PHObjectPlaceholder"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHObjectPlaceholder/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "PHObjectPlaceholder"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:objc(pl)NSObject/title",
          "value": "NSObject"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHAssetCollectionChangeRequest~1init(for:assets:)/title",
          "value": "changeRequestForAssetCollection:assets:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHAssetCollectionChangeRequest~1init(for:assets:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "+ "
            },
            {
              "kind": "identifier",
              "text": "changeRequestForAssetCollection:assets:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHCollection~1canPerform(_:)/title",
          "value": "canPerformEditOperation:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHCollection~1canPerform(_:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "canPerformEditOperation:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHChangeRequest/title",
          "value": "PHChangeRequest"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHChangeRequest/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PHChangeRequest"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHChangeRequest/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "PHChangeRequest"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHAssetCollectionChangeRequest~1creationRequestForAssetCollection(withTitle:)/title",
          "value": "creationRequestForAssetCollectionWithTitle:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHAssetCollectionChangeRequest~1creationRequestForAssetCollection(withTitle:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "+ "
            },
            {
              "kind": "identifier",
              "text": "creationRequestForAssetCollectionWithTitle:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHPhotoLibrary~1performChangesAndWait(_:)/title",
          "value": "performChangesAndWait:error:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHPhotoLibrary~1performChangesAndWait(_:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "performChangesAndWait:error:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHCollectionListChangeRequest/title",
          "value": "PHCollectionListChangeRequest"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHCollectionListChangeRequest/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PHCollectionListChangeRequest"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHCollectionListChangeRequest/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "PHCollectionListChangeRequest"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHAssetCollectionChangeRequest~1insertAssets(_:at:)/title",
          "value": "insertAssets:atIndexes:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHAssetCollectionChangeRequest~1insertAssets(_:at:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "insertAssets:atIndexes:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHAssetCollectionChangeRequest~1replaceAssets(at:withAssets:)/title",
          "value": "replaceAssetsAtIndexes:withAssets:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHAssetCollectionChangeRequest~1replaceAssets(at:withAssets:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "replaceAssetsAtIndexes:withAssets:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHPhotoLibrary/title",
          "value": "PHPhotoLibrary"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHPhotoLibrary/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PHPhotoLibrary"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHPhotoLibrary/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "PHPhotoLibrary"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHAssetCollectionChangeRequest~1placeholderForCreatedAssetCollection/title",
          "value": "placeholderForCreatedAssetCollection"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHAssetCollectionChangeRequest~1placeholderForCreatedAssetCollection/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "placeholderForCreatedAssetCollection"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHAssetChangeRequest/title",
          "value": "PHAssetChangeRequest"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHAssetChangeRequest/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PHAssetChangeRequest"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHAssetChangeRequest/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "PHAssetChangeRequest"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHAssetCollectionChangeRequest~1init(for:)/title",
          "value": "changeRequestForAssetCollection:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHAssetCollectionChangeRequest~1init(for:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "+ "
            },
            {
              "kind": "identifier",
              "text": "changeRequestForAssetCollection:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHAssetCollectionChangeRequest~1removeAssets(_:)/title",
          "value": "removeAssets:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHAssetCollectionChangeRequest~1removeAssets(_:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "removeAssets:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHAssetCollectionChangeRequest~1title/title",
          "value": "title"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHAssetCollectionChangeRequest~1title/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "title"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHAssetCollectionChangeRequest~1addAssets(_:)/title",
          "value": "addAssets:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHAssetCollectionChangeRequest~1addAssets(_:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "addAssets:"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/photos/phassetcollectionchangerequest"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/photos/phassetcollectionchangerequest"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
