{
  "abstract": [
    {
      "text": "Constants identifying specific variations of asset media, such as panorama or screenshot photos, and time-lapse or high-frame-rate video.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.photokit/documentation/Photos"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.photokit/documentation/Photos/PHAssetMediaSubtype"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@PHAssetMediaSubtype",
    "fragments": [
      {
        "kind": "keyword",
        "text": "struct"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "PHAssetMediaSubtype"
      }
    ],
    "modules": [
      {
        "name": "Photos"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "PHAssetMediaSubtype"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "8.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "8.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.1",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.11",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.0",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Structure",
    "symbolKind": "struct",
    "title": "PHAssetMediaSubtype"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "struct"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "PHAssetMediaSubtype"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "You use these constants with the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.photokit/documentation/Photos/PHAsset",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " and ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.photokit/documentation/Photos/PHContentEditingInput",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " classes to fetch specific types of assets or to identify an asset being edited.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "Media subtypes are ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/Swift/OptionSet",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " values, so you can combine them using set literal syntax to test for multiple subtypes.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/Swift/OptionSet": {
      "abstract": [
        {
          "text": "A type that presents a mathematical set interface to a bit set.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "OptionSet"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SY",
          "text": "RawRepresentable"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s10SetAlgebraP",
          "text": "SetAlgebra"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/Swift/OptionSet",
      "kind": "symbol",
      "role": "symbol",
      "title": "OptionSet",
      "type": "topic",
      "url": "/documentation/Swift/OptionSet"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.photokit/documentation/Photos": {
      "abstract": [
        {
          "text": "Work with image and video assets that the Photos app manages, including those from iCloud Photos and Live Photos.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.photokit/documentation/Photos",
      "kind": "symbol",
      "role": "collection",
      "title": "Photos",
      "type": "topic",
      "url": "/documentation/photos"
    },
    "doc://com.apple.photokit/documentation/Photos/PHAsset": {
      "abstract": [
        {
          "text": "A representation of an image, video, or Live Photo in the Photos library.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "PHAsset"
        }
      ],
      "identifier": "doc://com.apple.photokit/documentation/Photos/PHAsset",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PHAsset"
        }
      ],
      "role": "symbol",
      "title": "PHAsset",
      "type": "topic",
      "url": "/documentation/photos/phasset"
    },
    "doc://com.apple.photokit/documentation/Photos/PHAsset/adjustmentFormatIdentifier": {
      "abstract": [
        {
          "text": "The identifier that describes the adjustment format.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "adjustmentFormatIdentifier"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.photokit/documentation/Photos/PHAsset/adjustmentFormatIdentifier",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "adjustmentFormatIdentifier"
        }
      ],
      "role": "symbol",
      "title": "adjustmentFormatIdentifier",
      "type": "topic",
      "url": "/documentation/photos/phasset/adjustmentformatidentifier"
    },
    "doc://com.apple.photokit/documentation/Photos/PHAsset/creationDate": {
      "abstract": [
        {
          "text": "The date and time of the asset’s creation.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "creationDate"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10Foundation4DateV",
          "text": "Date"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.photokit/documentation/Photos/PHAsset/creationDate",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "creationDate"
        }
      ],
      "role": "symbol",
      "title": "creationDate",
      "type": "topic",
      "url": "/documentation/photos/phasset/creationdate"
    },
    "doc://com.apple.photokit/documentation/Photos/PHAsset/duration": {
      "abstract": [
        {
          "text": "The duration, in seconds, of the video asset.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "duration"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSTimeInterval",
          "text": "TimeInterval"
        }
      ],
      "identifier": "doc://com.apple.photokit/documentation/Photos/PHAsset/duration",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "duration"
        }
      ],
      "role": "symbol",
      "title": "duration",
      "type": "topic",
      "url": "/documentation/photos/phasset/duration"
    },
    "doc://com.apple.photokit/documentation/Photos/PHAsset/hasAdjustments": {
      "abstract": [
        {
          "text": "A Boolean value that indicates whether the asset contains adjustment data.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "hasAdjustments"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.photokit/documentation/Photos/PHAsset/hasAdjustments",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "hasAdjustments"
        }
      ],
      "role": "symbol",
      "title": "hasAdjustments",
      "type": "topic",
      "url": "/documentation/photos/phasset/hasadjustments"
    },
    "doc://com.apple.photokit/documentation/Photos/PHAsset/isFavorite": {
      "abstract": [
        {
          "text": "A Boolean value that indicates whether the user marks the asset as a favorite.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "isFavorite"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.photokit/documentation/Photos/PHAsset/isFavorite",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "favorite"
        }
      ],
      "role": "symbol",
      "title": "isFavorite",
      "type": "topic",
      "url": "/documentation/photos/phasset/isfavorite"
    },
    "doc://com.apple.photokit/documentation/Photos/PHAsset/isHidden": {
      "abstract": [
        {
          "text": "A Boolean value that indicates whether the user hides the asset.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "isHidden"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.photokit/documentation/Photos/PHAsset/isHidden",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "hidden"
        }
      ],
      "role": "symbol",
      "title": "isHidden",
      "type": "topic",
      "url": "/documentation/photos/phasset/ishidden"
    },
    "doc://com.apple.photokit/documentation/Photos/PHAsset/location": {
      "abstract": [
        {
          "text": "The location information for the asset.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "location"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)CLLocation",
          "text": "CLLocation"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.photokit/documentation/Photos/PHAsset/location",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "location"
        }
      ],
      "role": "symbol",
      "title": "location",
      "type": "topic",
      "url": "/documentation/photos/phasset/location"
    },
    "doc://com.apple.photokit/documentation/Photos/PHAsset/mediaSubtypes": {
      "abstract": [
        {
          "text": "The subtypes of the asset, identifying special kinds of assets, such as panoramic photo or high-frame-rate video.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "mediaSubtypes"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@PHAssetMediaSubtype",
          "text": "PHAssetMediaSubtype"
        }
      ],
      "identifier": "doc://com.apple.photokit/documentation/Photos/PHAsset/mediaSubtypes",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "mediaSubtypes"
        }
      ],
      "role": "symbol",
      "title": "mediaSubtypes",
      "type": "topic",
      "url": "/documentation/photos/phasset/mediasubtypes"
    },
    "doc://com.apple.photokit/documentation/Photos/PHAsset/mediaType": {
      "abstract": [
        {
          "text": "The type of the asset, such as video or audio.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "mediaType"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@PHAssetMediaType",
          "text": "PHAssetMediaType"
        }
      ],
      "identifier": "doc://com.apple.photokit/documentation/Photos/PHAsset/mediaType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "mediaType"
        }
      ],
      "role": "symbol",
      "title": "mediaType",
      "type": "topic",
      "url": "/documentation/photos/phasset/mediatype"
    },
    "doc://com.apple.photokit/documentation/Photos/PHAsset/modificationDate": {
      "abstract": [
        {
          "text": "The date and time of the asset’s last modification.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "modificationDate"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10Foundation4DateV",
          "text": "Date"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.photokit/documentation/Photos/PHAsset/modificationDate",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "modificationDate"
        }
      ],
      "role": "symbol",
      "title": "modificationDate",
      "type": "topic",
      "url": "/documentation/photos/phasset/modificationdate"
    },
    "doc://com.apple.photokit/documentation/Photos/PHAsset/pixelHeight": {
      "abstract": [
        {
          "text": "The height, in pixels, of the asset’s image or video data.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "pixelHeight"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.photokit/documentation/Photos/PHAsset/pixelHeight",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "pixelHeight"
        }
      ],
      "role": "symbol",
      "title": "pixelHeight",
      "type": "topic",
      "url": "/documentation/photos/phasset/pixelheight"
    },
    "doc://com.apple.photokit/documentation/Photos/PHAsset/pixelWidth": {
      "abstract": [
        {
          "text": "The width, in pixels, of the asset’s image or video data.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "pixelWidth"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.photokit/documentation/Photos/PHAsset/pixelWidth",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "pixelWidth"
        }
      ],
      "role": "symbol",
      "title": "pixelWidth",
      "type": "topic",
      "url": "/documentation/photos/phasset/pixelwidth"
    },
    "doc://com.apple.photokit/documentation/Photos/PHAsset/sourceType": {
      "abstract": [
        {
          "text": "The means by which the asset enters the user’s Photos library.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "sourceType"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@PHAssetSourceType",
          "text": "PHAssetSourceType"
        }
      ],
      "identifier": "doc://com.apple.photokit/documentation/Photos/PHAsset/sourceType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "sourceType"
        }
      ],
      "role": "symbol",
      "title": "sourceType",
      "type": "topic",
      "url": "/documentation/photos/phasset/sourcetype"
    },
    "doc://com.apple.photokit/documentation/Photos/PHAssetMediaSubtype": {
      "abstract": [
        {
          "text": "Constants identifying specific variations of asset media, such as panorama or screenshot photos, and time-lapse or high-frame-rate video.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "PHAssetMediaSubtype"
        }
      ],
      "identifier": "doc://com.apple.photokit/documentation/Photos/PHAssetMediaSubtype",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PHAssetMediaSubtype"
        }
      ],
      "role": "symbol",
      "title": "PHAssetMediaSubtype",
      "type": "topic",
      "url": "/documentation/photos/phassetmediasubtype"
    },
    "doc://com.apple.photokit/documentation/Photos/PHAssetMediaSubtype/PHAssetMediaSubtypeNone": {
      "abstract": [
        {
          "text": "The asset has no subtype.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "PHAssetMediaSubtypeNone"
        }
      ],
      "identifier": "doc://com.apple.photokit/documentation/Photos/PHAssetMediaSubtype/PHAssetMediaSubtypeNone",
      "kind": "symbol",
      "role": "symbol",
      "title": "PHAssetMediaSubtypeNone",
      "type": "topic",
      "url": "/documentation/photos/phassetmediasubtype/phassetmediasubtypenone"
    },
    "doc://com.apple.photokit/documentation/Photos/PHAssetMediaSubtype/init(rawValue:)": {
      "abstract": [
        {
          "text": "Initializes a media subtype from a raw value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "rawValue"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Su",
          "text": "UInt"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.photokit/documentation/Photos/PHAssetMediaSubtype/init(rawValue:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "init(rawValue:)",
      "type": "topic",
      "url": "/documentation/photos/phassetmediasubtype/init(rawvalue:)"
    },
    "doc://com.apple.photokit/documentation/Photos/PHAssetMediaSubtype/photoDepthEffect": {
      "abstract": [
        {
          "text": "The asset is a photo captured with the Camera app’s Portrait mode depth effect.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "photoDepthEffect"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@PHAssetMediaSubtype",
          "text": "PHAssetMediaSubtype"
        }
      ],
      "identifier": "doc://com.apple.photokit/documentation/Photos/PHAssetMediaSubtype/photoDepthEffect",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PHAssetMediaSubtypePhotoDepthEffect"
        }
      ],
      "role": "symbol",
      "title": "photoDepthEffect",
      "type": "topic",
      "url": "/documentation/photos/phassetmediasubtype/photodeptheffect"
    },
    "doc://com.apple.photokit/documentation/Photos/PHAssetMediaSubtype/photoHDR": {
      "abstract": [
        {
          "text": "The asset is a high-dynamic range photo.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "photoHDR"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@PHAssetMediaSubtype",
          "text": "PHAssetMediaSubtype"
        }
      ],
      "identifier": "doc://com.apple.photokit/documentation/Photos/PHAssetMediaSubtype/photoHDR",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PHAssetMediaSubtypePhotoHDR"
        }
      ],
      "role": "symbol",
      "title": "photoHDR",
      "type": "topic",
      "url": "/documentation/photos/phassetmediasubtype/photohdr"
    },
    "doc://com.apple.photokit/documentation/Photos/PHAssetMediaSubtype/photoLive": {
      "abstract": [
        {
          "text": "The asset is a Live Photo that includes movement and sounds from the moments just before and after its capture.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "photoLive"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@PHAssetMediaSubtype",
          "text": "PHAssetMediaSubtype"
        }
      ],
      "identifier": "doc://com.apple.photokit/documentation/Photos/PHAssetMediaSubtype/photoLive",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PHAssetMediaSubtypePhotoLive"
        }
      ],
      "role": "symbol",
      "title": "photoLive",
      "type": "topic",
      "url": "/documentation/photos/phassetmediasubtype/photolive"
    },
    "doc://com.apple.photokit/documentation/Photos/PHAssetMediaSubtype/photoPanorama": {
      "abstract": [
        {
          "text": "The asset is a large-format panorama photo.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "photoPanorama"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@PHAssetMediaSubtype",
          "text": "PHAssetMediaSubtype"
        }
      ],
      "identifier": "doc://com.apple.photokit/documentation/Photos/PHAssetMediaSubtype/photoPanorama",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PHAssetMediaSubtypePhotoPanorama"
        }
      ],
      "role": "symbol",
      "title": "photoPanorama",
      "type": "topic",
      "url": "/documentation/photos/phassetmediasubtype/photopanorama"
    },
    "doc://com.apple.photokit/documentation/Photos/PHAssetMediaSubtype/photoScreenshot": {
      "abstract": [
        {
          "text": "The asset is an image captured with the device’s screenshot feature.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "photoScreenshot"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@PHAssetMediaSubtype",
          "text": "PHAssetMediaSubtype"
        }
      ],
      "identifier": "doc://com.apple.photokit/documentation/Photos/PHAssetMediaSubtype/photoScreenshot",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PHAssetMediaSubtypePhotoScreenshot"
        }
      ],
      "role": "symbol",
      "title": "photoScreenshot",
      "type": "topic",
      "url": "/documentation/photos/phassetmediasubtype/photoscreenshot"
    },
    "doc://com.apple.photokit/documentation/Photos/PHAssetMediaSubtype/spatialMedia": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "spatialMedia"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@PHAssetMediaSubtype",
          "text": "PHAssetMediaSubtype"
        }
      ],
      "identifier": "doc://com.apple.photokit/documentation/Photos/PHAssetMediaSubtype/spatialMedia",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PHAssetMediaSubtypeSpatialMedia"
        }
      ],
      "role": "symbol",
      "title": "spatialMedia",
      "type": "topic",
      "url": "/documentation/photos/phassetmediasubtype/spatialmedia"
    },
    "doc://com.apple.photokit/documentation/Photos/PHAssetMediaSubtype/videoCinematic": {
      "abstract": [
        {
          "text": "The asset is a cinematic video.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "videoCinematic"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@PHAssetMediaSubtype",
          "text": "PHAssetMediaSubtype"
        }
      ],
      "identifier": "doc://com.apple.photokit/documentation/Photos/PHAssetMediaSubtype/videoCinematic",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PHAssetMediaSubtypeVideoCinematic"
        }
      ],
      "role": "symbol",
      "title": "videoCinematic",
      "type": "topic",
      "url": "/documentation/photos/phassetmediasubtype/videocinematic"
    },
    "doc://com.apple.photokit/documentation/Photos/PHAssetMediaSubtype/videoHighFrameRate": {
      "abstract": [
        {
          "text": "The asset is a high-frame-rate video.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "videoHighFrameRate"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@PHAssetMediaSubtype",
          "text": "PHAssetMediaSubtype"
        }
      ],
      "identifier": "doc://com.apple.photokit/documentation/Photos/PHAssetMediaSubtype/videoHighFrameRate",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PHAssetMediaSubtypeVideoHighFrameRate"
        }
      ],
      "role": "symbol",
      "title": "videoHighFrameRate",
      "type": "topic",
      "url": "/documentation/photos/phassetmediasubtype/videohighframerate"
    },
    "doc://com.apple.photokit/documentation/Photos/PHAssetMediaSubtype/videoStreamed": {
      "abstract": [
        {
          "text": "The asset is a video with contents that always stream over a network connection.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "videoStreamed"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@PHAssetMediaSubtype",
          "text": "PHAssetMediaSubtype"
        }
      ],
      "identifier": "doc://com.apple.photokit/documentation/Photos/PHAssetMediaSubtype/videoStreamed",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PHAssetMediaSubtypeVideoStreamed"
        }
      ],
      "role": "symbol",
      "title": "videoStreamed",
      "type": "topic",
      "url": "/documentation/photos/phassetmediasubtype/videostreamed"
    },
    "doc://com.apple.photokit/documentation/Photos/PHAssetMediaSubtype/videoTimelapse": {
      "abstract": [
        {
          "text": "The asset is a time-lapse video.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "videoTimelapse"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@PHAssetMediaSubtype",
          "text": "PHAssetMediaSubtype"
        }
      ],
      "identifier": "doc://com.apple.photokit/documentation/Photos/PHAssetMediaSubtype/videoTimelapse",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PHAssetMediaSubtypeVideoTimelapse"
        }
      ],
      "role": "symbol",
      "title": "videoTimelapse",
      "type": "topic",
      "url": "/documentation/photos/phassetmediasubtype/videotimelapse"
    },
    "doc://com.apple.photokit/documentation/Photos/PHAssetMediaType": {
      "abstract": [
        {
          "text": "Identifies the general type of an asset, such as image or video.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "PHAssetMediaType"
        }
      ],
      "identifier": "doc://com.apple.photokit/documentation/Photos/PHAssetMediaType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PHAssetMediaType"
        }
      ],
      "role": "symbol",
      "title": "PHAssetMediaType",
      "type": "topic",
      "url": "/documentation/photos/phassetmediatype"
    },
    "doc://com.apple.photokit/documentation/Photos/PHAssetSourceType": {
      "abstract": [
        {
          "text": "The means by which an asset enters the Photos library.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "PHAssetSourceType"
        }
      ],
      "identifier": "doc://com.apple.photokit/documentation/Photos/PHAssetSourceType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PHAssetSourceType"
        }
      ],
      "role": "symbol",
      "title": "PHAssetSourceType",
      "type": "topic",
      "url": "/documentation/photos/phassetsourcetype"
    },
    "doc://com.apple.photokit/documentation/Photos/PHContentEditingInput": {
      "abstract": [
        {
          "text": "A container that provides information about and access to the image, video, or Live Photo content of an asset to be edited.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "PHContentEditingInput"
        }
      ],
      "identifier": "doc://com.apple.photokit/documentation/Photos/PHContentEditingInput",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PHContentEditingInput"
        }
      ],
      "role": "symbol",
      "title": "PHContentEditingInput",
      "type": "topic",
      "url": "/documentation/photos/phcontenteditinginput"
    },
    "doc://com.externally.resolved.symbol/s:SQ": {
      "abstract": [
        {
          "text": "A type that can be compared for value equality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SQ",
      "kind": "symbol",
      "role": "symbol",
      "title": "Equatable",
      "type": "topic",
      "url": "/documentation/Swift/Equatable"
    },
    "doc://com.externally.resolved.symbol/s:SY": {
      "abstract": [
        {
          "text": "A type that can be converted to and from an associated raw value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "RawRepresentable"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SY8RawValueQa",
          "text": "RawValue"
        },
        {
          "kind": "text",
          "text": ">"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SY",
      "kind": "symbol",
      "role": "symbol",
      "title": "RawRepresentable",
      "type": "topic",
      "url": "/documentation/Swift/RawRepresentable"
    },
    "doc://com.externally.resolved.symbol/s:s10SetAlgebraP": {
      "abstract": [
        {
          "text": "A type that provides mathematical set operations.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SetAlgebra"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s10SetAlgebraP7ElementQa",
          "text": "Element"
        },
        {
          "kind": "text",
          "text": "> : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SQ",
          "text": "Equatable"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s25ExpressibleByArrayLiteralP",
          "text": "ExpressibleByArrayLiteral"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s10SetAlgebraP",
      "kind": "symbol",
      "role": "symbol",
      "title": "SetAlgebra",
      "type": "topic",
      "url": "/documentation/Swift/SetAlgebra"
    },
    "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BitwiseCopyable"
        },
        {
          "kind": "text",
          "text": " : ~Escapable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "BitwiseCopyable",
      "type": "topic",
      "url": "/documentation/Swift/BitwiseCopyable"
    },
    "doc://com.externally.resolved.symbol/s:s25ExpressibleByArrayLiteralP": {
      "abstract": [
        {
          "text": "A type that can be initialized using an array literal.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ExpressibleByArrayLiteral"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s25ExpressibleByArrayLiteralP",
      "kind": "symbol",
      "role": "symbol",
      "title": "ExpressibleByArrayLiteral",
      "type": "topic",
      "url": "/documentation/Swift/ExpressibleByArrayLiteral"
    },
    "doc://com.externally.resolved.symbol/s:s8SendableP": {
      "abstract": [
        {
          "text": "A thread-safe type whose values can be shared across arbitrary concurrent contexts without introducing a risk of data races.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Sendable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s8SendableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "Sendable",
      "type": "topic",
      "url": "/documentation/Swift/Sendable"
    },
    "doc://com.externally.resolved.symbol/s:s9OptionSetP": {
      "abstract": [
        {
          "text": "A type that presents a mathematical set interface to a bit set.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "OptionSet"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SY",
          "text": "RawRepresentable"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s10SetAlgebraP",
          "text": "SetAlgebra"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s9OptionSetP",
      "kind": "symbol",
      "role": "symbol",
      "title": "OptionSet",
      "type": "topic",
      "url": "/documentation/Swift/OptionSet"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
        "doc://com.externally.resolved.symbol/s:SQ",
        "doc://com.externally.resolved.symbol/s:s25ExpressibleByArrayLiteralP",
        "doc://com.externally.resolved.symbol/s:s9OptionSetP",
        "doc://com.externally.resolved.symbol/s:SY",
        "doc://com.externally.resolved.symbol/s:s8SendableP",
        "doc://com.externally.resolved.symbol/s:s10SetAlgebraP"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Reading-Asset-Metadata",
      "generated": true,
      "identifiers": [
        "doc://com.apple.photokit/documentation/Photos/PHAsset/mediaType",
        "doc://com.apple.photokit/documentation/Photos/PHAssetMediaType",
        "doc://com.apple.photokit/documentation/Photos/PHAsset/mediaSubtypes",
        "doc://com.apple.photokit/documentation/Photos/PHAsset/sourceType",
        "doc://com.apple.photokit/documentation/Photos/PHAssetSourceType",
        "doc://com.apple.photokit/documentation/Photos/PHAsset/pixelWidth",
        "doc://com.apple.photokit/documentation/Photos/PHAsset/pixelHeight",
        "doc://com.apple.photokit/documentation/Photos/PHAsset/creationDate",
        "doc://com.apple.photokit/documentation/Photos/PHAsset/modificationDate",
        "doc://com.apple.photokit/documentation/Photos/PHAsset/location",
        "doc://com.apple.photokit/documentation/Photos/PHAsset/duration",
        "doc://com.apple.photokit/documentation/Photos/PHAsset/isFavorite",
        "doc://com.apple.photokit/documentation/Photos/PHAsset/isHidden",
        "doc://com.apple.photokit/documentation/Photos/PHAsset/hasAdjustments",
        "doc://com.apple.photokit/documentation/Photos/PHAsset/adjustmentFormatIdentifier"
      ],
      "title": "Reading Asset Metadata"
    }
  ],
  "topicSections": [
    {
      "anchor": "Initializers",
      "identifiers": [
        "doc://com.apple.photokit/documentation/Photos/PHAssetMediaSubtype/init(rawValue:)"
      ],
      "title": "Initializers"
    },
    {
      "anchor": "Media-Subtypes",
      "identifiers": [
        "doc://com.apple.photokit/documentation/Photos/PHAssetMediaSubtype/photoPanorama",
        "doc://com.apple.photokit/documentation/Photos/PHAssetMediaSubtype/photoHDR",
        "doc://com.apple.photokit/documentation/Photos/PHAssetMediaSubtype/photoScreenshot",
        "doc://com.apple.photokit/documentation/Photos/PHAssetMediaSubtype/photoLive",
        "doc://com.apple.photokit/documentation/Photos/PHAssetMediaSubtype/videoCinematic",
        "doc://com.apple.photokit/documentation/Photos/PHAssetMediaSubtype/videoStreamed",
        "doc://com.apple.photokit/documentation/Photos/PHAssetMediaSubtype/videoHighFrameRate",
        "doc://com.apple.photokit/documentation/Photos/PHAssetMediaSubtype/videoTimelapse",
        "doc://com.apple.photokit/documentation/Photos/PHAssetMediaSubtype/photoDepthEffect"
      ],
      "title": "Media Subtypes"
    },
    {
      "anchor": "Type-Properties",
      "generated": true,
      "identifiers": [
        "doc://com.apple.photokit/documentation/Photos/PHAssetMediaSubtype/spatialMedia"
      ],
      "title": "Type Properties"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "8.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "8.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.1",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.11",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.0",
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "PHAssetMediaSubtype"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "enum"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PHAssetMediaSubtype"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "PHAssetMediaSubtype"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.photokit/documentation/Photos"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Media-Subtypes",
              "identifiers": [
                "doc://com.apple.photokit/documentation/Photos/PHAssetMediaSubtype/PHAssetMediaSubtypeNone",
                "doc://com.apple.photokit/documentation/Photos/PHAssetMediaSubtype/photoPanorama",
                "doc://com.apple.photokit/documentation/Photos/PHAssetMediaSubtype/photoHDR",
                "doc://com.apple.photokit/documentation/Photos/PHAssetMediaSubtype/photoScreenshot",
                "doc://com.apple.photokit/documentation/Photos/PHAssetMediaSubtype/photoLive",
                "doc://com.apple.photokit/documentation/Photos/PHAssetMediaSubtype/videoCinematic",
                "doc://com.apple.photokit/documentation/Photos/PHAssetMediaSubtype/videoStreamed",
                "doc://com.apple.photokit/documentation/Photos/PHAssetMediaSubtype/videoHighFrameRate",
                "doc://com.apple.photokit/documentation/Photos/PHAssetMediaSubtype/videoTimelapse",
                "doc://com.apple.photokit/documentation/Photos/PHAssetMediaSubtype/photoDepthEffect"
              ],
              "title": "Media Subtypes"
            },
            {
              "anchor": "Enumeration-Cases",
              "generated": true,
              "identifiers": [
                "doc://com.apple.photokit/documentation/Photos/PHAssetMediaSubtype/spatialMedia"
              ],
              "title": "Enumeration Cases"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Reading-Asset-Metadata",
              "generated": true,
              "identifiers": [
                "doc://com.apple.photokit/documentation/Photos/PHAsset/mediaType",
                "doc://com.apple.photokit/documentation/Photos/PHAssetMediaType",
                "doc://com.apple.photokit/documentation/Photos/PHAsset/mediaSubtypes",
                "doc://com.apple.photokit/documentation/Photos/PHAsset/sourceType",
                "doc://com.apple.photokit/documentation/Photos/PHAssetSourceType",
                "doc://com.apple.photokit/documentation/Photos/PHAsset/pixelWidth",
                "doc://com.apple.photokit/documentation/Photos/PHAsset/pixelHeight",
                "doc://com.apple.photokit/documentation/Photos/PHAsset/creationDate",
                "doc://com.apple.photokit/documentation/Photos/PHAsset/modificationDate",
                "doc://com.apple.photokit/documentation/Photos/PHAsset/location",
                "doc://com.apple.photokit/documentation/Photos/PHAsset/duration",
                "doc://com.apple.photokit/documentation/Photos/PHAsset/isFavorite",
                "doc://com.apple.photokit/documentation/Photos/PHAsset/isHidden",
                "doc://com.apple.photokit/documentation/Photos/PHAsset/hasAdjustments",
                "doc://com.apple.photokit/documentation/Photos/PHAsset/adjustmentFormatIdentifier"
              ],
              "title": "Reading Asset Metadata"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "enum"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "PHAssetMediaSubtype"
                  },
                  {
                    "kind": "text",
                    "text": " : "
                  },
                  {
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@NSUInteger",
                    "text": "NSUInteger"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHAsset~1isFavorite/title",
          "value": "favorite"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHAsset~1isFavorite/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "favorite"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHAsset~1adjustmentFormatIdentifier/title",
          "value": "adjustmentFormatIdentifier"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHAsset~1adjustmentFormatIdentifier/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "adjustmentFormatIdentifier"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHAsset~1creationDate/title",
          "value": "creationDate"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHAsset~1creationDate/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "creationDate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHContentEditingInput/title",
          "value": "PHContentEditingInput"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHContentEditingInput/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PHContentEditingInput"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHContentEditingInput/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "PHContentEditingInput"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHAssetMediaSubtype~1videoTimelapse/title",
          "value": "PHAssetMediaSubtypeVideoTimelapse"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHAssetMediaSubtype~1videoTimelapse/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PHAssetMediaSubtypeVideoTimelapse"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHAssetMediaSubtype~1spatialMedia/title",
          "value": "PHAssetMediaSubtypeSpatialMedia"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHAssetMediaSubtype~1spatialMedia/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PHAssetMediaSubtypeSpatialMedia"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHAsset~1pixelWidth/title",
          "value": "pixelWidth"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHAsset~1pixelWidth/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "pixelWidth"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHAsset~1mediaSubtypes/title",
          "value": "mediaSubtypes"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHAsset~1mediaSubtypes/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "mediaSubtypes"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHAsset~1isHidden/title",
          "value": "hidden"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHAsset~1isHidden/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "hidden"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHAsset~1mediaType/title",
          "value": "mediaType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHAsset~1mediaType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "mediaType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHAssetMediaSubtype~1photoScreenshot/title",
          "value": "PHAssetMediaSubtypePhotoScreenshot"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHAssetMediaSubtype~1photoScreenshot/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PHAssetMediaSubtypePhotoScreenshot"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHAsset/title",
          "value": "PHAsset"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHAsset/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PHAsset"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHAsset/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "PHAsset"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHAssetMediaSubtype~1videoHighFrameRate/title",
          "value": "PHAssetMediaSubtypeVideoHighFrameRate"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHAssetMediaSubtype~1videoHighFrameRate/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PHAssetMediaSubtypeVideoHighFrameRate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHAssetMediaType/title",
          "value": "PHAssetMediaType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHAssetMediaType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PHAssetMediaType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHAssetMediaType/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "PHAssetMediaType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHAsset~1location/title",
          "value": "location"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHAsset~1location/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "location"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHAssetMediaSubtype~1photoPanorama/title",
          "value": "PHAssetMediaSubtypePhotoPanorama"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHAssetMediaSubtype~1photoPanorama/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PHAssetMediaSubtypePhotoPanorama"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHAssetMediaSubtype~1videoCinematic/title",
          "value": "PHAssetMediaSubtypeVideoCinematic"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHAssetMediaSubtype~1videoCinematic/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PHAssetMediaSubtypeVideoCinematic"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHAsset~1duration/title",
          "value": "duration"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHAsset~1duration/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "duration"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHAssetMediaSubtype~1photoDepthEffect/title",
          "value": "PHAssetMediaSubtypePhotoDepthEffect"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHAssetMediaSubtype~1photoDepthEffect/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PHAssetMediaSubtypePhotoDepthEffect"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHAsset~1hasAdjustments/title",
          "value": "hasAdjustments"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHAsset~1hasAdjustments/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "hasAdjustments"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHAssetMediaSubtype/title",
          "value": "PHAssetMediaSubtype"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHAssetMediaSubtype/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PHAssetMediaSubtype"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHAssetMediaSubtype/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "PHAssetMediaSubtype"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHAssetMediaSubtype~1photoLive/title",
          "value": "PHAssetMediaSubtypePhotoLive"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHAssetMediaSubtype~1photoLive/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PHAssetMediaSubtypePhotoLive"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHAssetMediaSubtype~1photoHDR/title",
          "value": "PHAssetMediaSubtypePhotoHDR"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHAssetMediaSubtype~1photoHDR/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PHAssetMediaSubtypePhotoHDR"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHAssetMediaSubtype~1videoStreamed/title",
          "value": "PHAssetMediaSubtypeVideoStreamed"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHAssetMediaSubtype~1videoStreamed/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PHAssetMediaSubtypeVideoStreamed"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHAsset~1pixelHeight/title",
          "value": "pixelHeight"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHAsset~1pixelHeight/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "pixelHeight"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHAsset~1sourceType/title",
          "value": "sourceType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHAsset~1sourceType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "sourceType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHAsset~1modificationDate/title",
          "value": "modificationDate"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHAsset~1modificationDate/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "modificationDate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHAssetSourceType/title",
          "value": "PHAssetSourceType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHAssetSourceType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PHAssetSourceType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHAssetSourceType/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "PHAssetSourceType"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/photos/phassetmediasubtype"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/photos/phassetmediasubtype"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
