{
  "abstract": [
    {
      "text": "A resource manager for the data storage underlying a Photos asset.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.photokit/documentation/Photos"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.photokit/documentation/Photos/PHAssetResourceManager"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(cs)PHAssetResourceManager",
    "fragments": [
      {
        "kind": "keyword",
        "text": "class"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "PHAssetResourceManager"
      }
    ],
    "modules": [
      {
        "name": "Photos"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "PHAssetResourceManager"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "9.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "9.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.1",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.15",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.0",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Class",
    "symbolKind": "class",
    "title": "PHAssetResourceManager"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "class"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "PHAssetResourceManager"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "An asset can have multiple underlying data resources—for example, both original and edited versions—each of which is represented by a ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.photokit/documentation/Photos/PHAssetResource",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " object. Unlike the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.photokit/documentation/Photos/PHImageManager",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " class, which provides and caches the primary representations of assets as thumbnails, image objects, or video objects, the asset resource manager provides direct access to these underlying data resources.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.photokit/documentation/PhotoKit/resource-loading-request-identifiers": {
      "abstract": [
        {
          "text": "Special values for the ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.photokit/documentation/Photos/PHAssetResourceDataRequestID",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " identifier that are returned by asynchronous requests.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.photokit/documentation/PhotoKit/resource-loading-request-identifiers",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Resource Loading Request Identifiers",
      "type": "topic",
      "url": "/documentation/photokit/resource-loading-request-identifiers"
    },
    "doc://com.apple.photokit/documentation/Photos": {
      "abstract": [
        {
          "text": "Work with image and video assets that the Photos app manages, including those from iCloud Photos and Live Photos.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.photokit/documentation/Photos",
      "kind": "symbol",
      "role": "collection",
      "title": "Photos",
      "type": "topic",
      "url": "/documentation/photos"
    },
    "doc://com.apple.photokit/documentation/Photos/PHAssetCreationRequest": {
      "abstract": [
        {
          "text": "A request to create a new Photos asset from underlying data resources, for use in a photo library change block.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "PHAssetCreationRequest"
        }
      ],
      "identifier": "doc://com.apple.photokit/documentation/Photos/PHAssetCreationRequest",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PHAssetCreationRequest"
        }
      ],
      "role": "symbol",
      "title": "PHAssetCreationRequest",
      "type": "topic",
      "url": "/documentation/photos/phassetcreationrequest"
    },
    "doc://com.apple.photokit/documentation/Photos/PHAssetResource": {
      "abstract": [
        {
          "text": "An underlying data resource associated with a photo, video, or Live Photo asset in the Photos library.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "PHAssetResource"
        }
      ],
      "identifier": "doc://com.apple.photokit/documentation/Photos/PHAssetResource",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PHAssetResource"
        }
      ],
      "role": "symbol",
      "title": "PHAssetResource",
      "type": "topic",
      "url": "/documentation/photos/phassetresource"
    },
    "doc://com.apple.photokit/documentation/Photos/PHAssetResourceCreationOptions": {
      "abstract": [
        {
          "text": "A set of options affecting the creation of a new Photos asset from underlying resources.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "PHAssetResourceCreationOptions"
        }
      ],
      "identifier": "doc://com.apple.photokit/documentation/Photos/PHAssetResourceCreationOptions",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PHAssetResourceCreationOptions"
        }
      ],
      "role": "symbol",
      "title": "PHAssetResourceCreationOptions",
      "type": "topic",
      "url": "/documentation/photos/phassetresourcecreationoptions"
    },
    "doc://com.apple.photokit/documentation/Photos/PHAssetResourceDataRequestID": {
      "abstract": [
        {
          "text": "A numeric identifier for an asynchronous asset resource loading request.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "PHAssetResourceDataRequestID"
        }
      ],
      "identifier": "doc://com.apple.photokit/documentation/Photos/PHAssetResourceDataRequestID",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PHAssetResourceDataRequestID"
        }
      ],
      "role": "symbol",
      "title": "PHAssetResourceDataRequestID",
      "type": "topic",
      "url": "/documentation/photos/phassetresourcedatarequestid"
    },
    "doc://com.apple.photokit/documentation/Photos/PHAssetResourceManager": {
      "abstract": [
        {
          "text": "A resource manager for the data storage underlying a Photos asset.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "PHAssetResourceManager"
        }
      ],
      "identifier": "doc://com.apple.photokit/documentation/Photos/PHAssetResourceManager",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PHAssetResourceManager"
        }
      ],
      "role": "symbol",
      "title": "PHAssetResourceManager",
      "type": "topic",
      "url": "/documentation/photos/phassetresourcemanager"
    },
    "doc://com.apple.photokit/documentation/Photos/PHAssetResourceManager/cancelDataRequest(_:)": {
      "abstract": [
        {
          "text": "Cancels an asynchronous request.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "cancelDataRequest"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@PHAssetResourceDataRequestID",
          "text": "PHAssetResourceDataRequestID"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.photokit/documentation/Photos/PHAssetResourceManager/cancelDataRequest(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "cancelDataRequest:"
        }
      ],
      "role": "symbol",
      "title": "cancelDataRequest(_:)",
      "type": "topic",
      "url": "/documentation/photos/phassetresourcemanager/canceldatarequest(_:)"
    },
    "doc://com.apple.photokit/documentation/Photos/PHAssetResourceManager/default()": {
      "abstract": [
        {
          "text": "Returns the shared asset resource manager object.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "`default`"
        },
        {
          "kind": "text",
          "text": "() -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)PHAssetResourceManager",
          "text": "PHAssetResourceManager"
        }
      ],
      "identifier": "doc://com.apple.photokit/documentation/Photos/PHAssetResourceManager/default()",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "defaultManager"
        }
      ],
      "role": "symbol",
      "title": "default()",
      "type": "topic",
      "url": "/documentation/photos/phassetresourcemanager/default()"
    },
    "doc://com.apple.photokit/documentation/Photos/PHAssetResourceManager/requestData(for:options:dataReceivedHandler:completionHandler:)": {
      "abstract": [
        {
          "text": "Requests the underlying data for the specified asset resource, to be delivered asynchronously.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "requestData"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "for"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)PHAssetResource",
          "text": "PHAssetResource"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "options"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)PHAssetResourceRequestOptions",
          "text": "PHAssetResourceRequestOptions"
        },
        {
          "kind": "text",
          "text": "?, "
        },
        {
          "kind": "externalParam",
          "text": "dataReceivedHandler"
        },
        {
          "kind": "text",
          "text": ": ("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10Foundation4DataV",
          "text": "Data"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s4Voida",
          "text": "Void"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "completionHandler"
        },
        {
          "kind": "text",
          "text": ": ((any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5ErrorP",
          "text": "Error"
        },
        {
          "kind": "text",
          "text": ")?) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s4Voida",
          "text": "Void"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@PHAssetResourceDataRequestID",
          "text": "PHAssetResourceDataRequestID"
        }
      ],
      "identifier": "doc://com.apple.photokit/documentation/Photos/PHAssetResourceManager/requestData(for:options:dataReceivedHandler:completionHandler:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "requestDataForAssetResource:options:dataReceivedHandler:completionHandler:"
        }
      ],
      "role": "symbol",
      "title": "requestData(for:options:dataReceivedHandler:completionHandler:)",
      "type": "topic",
      "url": "/documentation/photos/phassetresourcemanager/requestdata(for:options:datareceivedhandler:completionhandler:)"
    },
    "doc://com.apple.photokit/documentation/Photos/PHAssetResourceManager/writeData(for:toFile:options:completionHandler:)": {
      "abstract": [
        {
          "text": "Requests the underlying data for the specified asset resource, to be asynchronously written to a local file.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "writeData"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "for"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)PHAssetResource",
          "text": "PHAssetResource"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "toFile"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10Foundation3URLV",
          "text": "URL"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "options"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)PHAssetResourceRequestOptions",
          "text": "PHAssetResourceRequestOptions"
        },
        {
          "kind": "text",
          "text": "?, "
        },
        {
          "kind": "externalParam",
          "text": "completionHandler"
        },
        {
          "kind": "text",
          "text": ": ((any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5ErrorP",
          "text": "Error"
        },
        {
          "kind": "text",
          "text": ")?) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s4Voida",
          "text": "Void"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.photokit/documentation/Photos/PHAssetResourceManager/writeData(for:toFile:options:completionHandler:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "writeDataForAssetResource:toFile:options:completionHandler:"
        }
      ],
      "role": "symbol",
      "title": "writeData(for:toFile:options:completionHandler:)",
      "type": "topic",
      "url": "/documentation/photos/phassetresourcemanager/writedata(for:tofile:options:completionhandler:)"
    },
    "doc://com.apple.photokit/documentation/Photos/PHAssetResourceRequestOptions": {
      "abstract": [
        {
          "text": "A set of options affecting the delivery of underlying asset data that you request from the asset resource manager.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "PHAssetResourceRequestOptions"
        }
      ],
      "identifier": "doc://com.apple.photokit/documentation/Photos/PHAssetResourceRequestOptions",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PHAssetResourceRequestOptions"
        }
      ],
      "role": "symbol",
      "title": "PHAssetResourceRequestOptions",
      "type": "topic",
      "url": "/documentation/photos/phassetresourcerequestoptions"
    },
    "doc://com.apple.photokit/documentation/Photos/PHImageManager": {
      "abstract": [
        {
          "text": "An object that facilitates retrieving or generating preview thumbnails and asset data.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "PHImageManager"
        }
      ],
      "identifier": "doc://com.apple.photokit/documentation/Photos/PHImageManager",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PHImageManager"
        }
      ],
      "role": "symbol",
      "title": "PHImageManager",
      "type": "topic",
      "url": "/documentation/photos/phimagemanager"
    },
    "doc://com.externally.resolved.symbol/c:objc(cs)NSObject": {
      "abstract": [
        {
          "text": "The root class of most Objective-C class hierarchies, from which subclasses inherit a basic interface to the runtime system and the ability to behave as Objective-C objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "class "
        },
        {
          "kind": "identifier",
          "text": "NSObject"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSObject",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSObject",
      "type": "topic",
      "url": "/documentation/objectivec/nsobject"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)NSObject": {
      "abstract": [
        {
          "text": "The group of methods that are fundamental to all Objective-C objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "protocol "
        },
        {
          "kind": "identifier",
          "text": "NSObjectProtocol"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSObject",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSObjectProtocol",
      "type": "topic",
      "url": "/documentation/objectivec/nsobjectprotocol"
    },
    "doc://com.externally.resolved.symbol/s:SH": {
      "abstract": [
        {
          "text": "A type that can be hashed into a `Hasher` to produce an integer hash value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Hashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SQ",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SH",
      "kind": "symbol",
      "role": "symbol",
      "title": "Hashable",
      "type": "topic",
      "url": "/documentation/Swift/Hashable"
    },
    "doc://com.externally.resolved.symbol/s:SQ": {
      "abstract": [
        {
          "text": "A type that can be compared for value equality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SQ",
      "kind": "symbol",
      "role": "symbol",
      "title": "Equatable",
      "type": "topic",
      "url": "/documentation/Swift/Equatable"
    },
    "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP": {
      "abstract": [
        {
          "text": "A type with a customized textual representation.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CustomStringConvertible"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CustomStringConvertible",
      "type": "topic",
      "url": "/documentation/Swift/CustomStringConvertible"
    },
    "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP": {
      "abstract": [
        {
          "text": "A type with a customized textual representation suitable for debugging purposes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CustomDebugStringConvertible"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CustomDebugStringConvertible",
      "type": "topic",
      "url": "/documentation/Swift/CustomDebugStringConvertible"
    },
    "doc://com.externally.resolved.symbol/s:s7CVarArgP": {
      "abstract": [
        {
          "text": "A type whose instances can be encoded, and appropriately passed, as elements of a C `va_list`.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CVarArg"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s7CVarArgP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CVarArg",
      "type": "topic",
      "url": "/documentation/Swift/CVarArg"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/c:objc(cs)NSObject"
      ],
      "kind": "relationships",
      "title": "Inherits From",
      "type": "inheritsFrom"
    },
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:s7CVarArgP",
        "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP",
        "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP",
        "doc://com.externally.resolved.symbol/s:SQ",
        "doc://com.externally.resolved.symbol/s:SH",
        "doc://com.externally.resolved.symbol/c:objc(pl)NSObject"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Asset-resource-management",
      "generated": true,
      "identifiers": [
        "doc://com.apple.photokit/documentation/Photos/PHAssetResource",
        "doc://com.apple.photokit/documentation/Photos/PHAssetCreationRequest",
        "doc://com.apple.photokit/documentation/Photos/PHAssetResourceCreationOptions",
        "doc://com.apple.photokit/documentation/Photos/PHAssetResourceRequestOptions"
      ],
      "title": "Asset resource management"
    }
  ],
  "topicSections": [
    {
      "anchor": "Getting-the-Asset-Resource-Manager",
      "identifiers": [
        "doc://com.apple.photokit/documentation/Photos/PHAssetResourceManager/default()"
      ],
      "title": "Getting the Asset Resource Manager"
    },
    {
      "anchor": "Requesting-Resources",
      "identifiers": [
        "doc://com.apple.photokit/documentation/Photos/PHAssetResourceManager/requestData(for:options:dataReceivedHandler:completionHandler:)",
        "doc://com.apple.photokit/documentation/Photos/PHAssetResourceManager/cancelDataRequest(_:)",
        "doc://com.apple.photokit/documentation/Photos/PHAssetResourceManager/writeData(for:toFile:options:completionHandler:)"
      ],
      "title": "Requesting Resources"
    },
    {
      "anchor": "Constants",
      "identifiers": [
        "doc://com.apple.photokit/documentation/Photos/PHAssetResourceDataRequestID",
        "doc://com.apple.photokit/documentation/PhotoKit/resource-loading-request-identifiers"
      ],
      "title": "Constants"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "9.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "9.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.1",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.15",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.0",
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Class"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "PHAssetResourceManager"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "class"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PHAssetResourceManager"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "PHAssetResourceManager"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.photokit/documentation/Photos"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Getting-the-Asset-Resource-Manager",
              "identifiers": [
                "doc://com.apple.photokit/documentation/Photos/PHAssetResourceManager/default()"
              ],
              "title": "Getting the Asset Resource Manager"
            },
            {
              "anchor": "Requesting-Resources",
              "identifiers": [
                "doc://com.apple.photokit/documentation/Photos/PHAssetResourceManager/requestData(for:options:dataReceivedHandler:completionHandler:)",
                "doc://com.apple.photokit/documentation/Photos/PHAssetResourceManager/cancelDataRequest(_:)",
                "doc://com.apple.photokit/documentation/Photos/PHAssetResourceManager/writeData(for:toFile:options:completionHandler:)"
              ],
              "title": "Requesting Resources"
            },
            {
              "anchor": "Constants",
              "identifiers": [
                "doc://com.apple.photokit/documentation/Photos/PHAssetResourceDataRequestID",
                "doc://com.apple.photokit/documentation/PhotoKit/resource-loading-request-identifiers"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": [
            {
              "identifiers": [
                "doc://com.externally.resolved.symbol/c:objc(cs)NSObject"
              ],
              "kind": "relationships",
              "title": "Inherits From",
              "type": "inheritsFrom"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Asset-resource-management",
              "generated": true,
              "identifiers": [
                "doc://com.apple.photokit/documentation/Photos/PHAssetResource",
                "doc://com.apple.photokit/documentation/Photos/PHAssetCreationRequest",
                "doc://com.apple.photokit/documentation/Photos/PHAssetResourceCreationOptions",
                "doc://com.apple.photokit/documentation/Photos/PHAssetResourceRequestOptions"
              ],
              "title": "Asset resource management"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "@interface"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "PHAssetResourceManager"
                  },
                  {
                    "kind": "text",
                    "text": " : "
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSObject",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(cs)NSObject",
                    "text": "NSObject"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHAssetResource/title",
          "value": "PHAssetResource"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHAssetResource/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PHAssetResource"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHAssetResource/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "PHAssetResource"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHAssetResourceManager~1default()/title",
          "value": "defaultManager"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHAssetResourceManager~1default()/fragments",
          "value": [
            {
              "kind": "text",
              "text": "+ "
            },
            {
              "kind": "identifier",
              "text": "defaultManager"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:objc(pl)NSObject/title",
          "value": "NSObject"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHImageManager/title",
          "value": "PHImageManager"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHImageManager/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PHImageManager"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHImageManager/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "PHImageManager"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHAssetResourceManager~1writeData(for:toFile:options:completionHandler:)/title",
          "value": "writeDataForAssetResource:toFile:options:completionHandler:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHAssetResourceManager~1writeData(for:toFile:options:completionHandler:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "writeDataForAssetResource:toFile:options:completionHandler:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHAssetCreationRequest/title",
          "value": "PHAssetCreationRequest"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHAssetCreationRequest/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PHAssetCreationRequest"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHAssetCreationRequest/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "PHAssetCreationRequest"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHAssetResourceManager~1cancelDataRequest(_:)/title",
          "value": "cancelDataRequest:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHAssetResourceManager~1cancelDataRequest(_:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "cancelDataRequest:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHAssetResourceDataRequestID/title",
          "value": "PHAssetResourceDataRequestID"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHAssetResourceDataRequestID/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PHAssetResourceDataRequestID"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHAssetResourceDataRequestID/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "PHAssetResourceDataRequestID"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHAssetResourceCreationOptions/title",
          "value": "PHAssetResourceCreationOptions"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHAssetResourceCreationOptions/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PHAssetResourceCreationOptions"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHAssetResourceCreationOptions/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "PHAssetResourceCreationOptions"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHAssetResourceRequestOptions/title",
          "value": "PHAssetResourceRequestOptions"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHAssetResourceRequestOptions/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PHAssetResourceRequestOptions"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHAssetResourceRequestOptions/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "PHAssetResourceRequestOptions"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHAssetResourceManager/title",
          "value": "PHAssetResourceManager"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHAssetResourceManager/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PHAssetResourceManager"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHAssetResourceManager/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "PHAssetResourceManager"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHAssetResourceManager~1requestData(for:options:dataReceivedHandler:completionHandler:)/title",
          "value": "requestDataForAssetResource:options:dataReceivedHandler:completionHandler:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHAssetResourceManager~1requestData(for:options:dataReceivedHandler:completionHandler:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "requestDataForAssetResource:options:dataReceivedHandler:completionHandler:"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/photos/phassetresourcemanager"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/photos/phassetresourcemanager"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
