{
  "abstract": [
    {
      "text": "Values identifying possible actions that a collection can support, used by the ",
      "type": "text"
    },
    {
      "identifier": "doc://com.apple.photokit/documentation/Photos/PHCollection/canPerform(_:)",
      "isActive": true,
      "type": "reference"
    },
    {
      "text": " method.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.photokit/documentation/Photos"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.photokit/documentation/Photos/PHCollectionEditOperation"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@PHCollectionEditOperation",
    "fragments": [
      {
        "kind": "keyword",
        "text": "enum"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "PHCollectionEditOperation"
      }
    ],
    "modules": [
      {
        "name": "Photos"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "PHCollectionEditOperation"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "8.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "8.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.1",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.11",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.0",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Enumeration",
    "symbolKind": "enum",
    "title": "PHCollectionEditOperation"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "enum"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "PHCollectionEditOperation"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.photokit/documentation/Photos": {
      "abstract": [
        {
          "text": "Work with image and video assets that the Photos app manages, including those from iCloud Photos and Live Photos.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.photokit/documentation/Photos",
      "kind": "symbol",
      "role": "collection",
      "title": "Photos",
      "type": "topic",
      "url": "/documentation/photos"
    },
    "doc://com.apple.photokit/documentation/Photos/PHCollection/canContainAssets": {
      "abstract": [
        {
          "text": "A Boolean value indicating whether the collection can contain assets.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "canContainAssets"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.photokit/documentation/Photos/PHCollection/canContainAssets",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "canContainAssets"
        }
      ],
      "role": "symbol",
      "title": "canContainAssets",
      "type": "topic",
      "url": "/documentation/photos/phcollection/cancontainassets"
    },
    "doc://com.apple.photokit/documentation/Photos/PHCollection/canContainCollections": {
      "abstract": [
        {
          "text": "A Boolean value indicating whether the collection can contain other collections.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "canContainCollections"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.photokit/documentation/Photos/PHCollection/canContainCollections",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "canContainCollections"
        }
      ],
      "role": "symbol",
      "title": "canContainCollections",
      "type": "topic",
      "url": "/documentation/photos/phcollection/cancontaincollections"
    },
    "doc://com.apple.photokit/documentation/Photos/PHCollection/canPerform(_:)": {
      "abstract": [
        {
          "text": "Returns whether the collection supports the specified editing operation.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "canPerform"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@PHCollectionEditOperation",
          "text": "PHCollectionEditOperation"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.photokit/documentation/Photos/PHCollection/canPerform(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "canPerformEditOperation:"
        }
      ],
      "role": "symbol",
      "title": "canPerform(_:)",
      "type": "topic",
      "url": "/documentation/photos/phcollection/canperform(_:)"
    },
    "doc://com.apple.photokit/documentation/Photos/PHCollectionEditOperation": {
      "abstract": [
        {
          "text": "Values identifying possible actions that a collection can support, used by the ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.photokit/documentation/Photos/PHCollection/canPerform(_:)",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " method.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "PHCollectionEditOperation"
        }
      ],
      "identifier": "doc://com.apple.photokit/documentation/Photos/PHCollectionEditOperation",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PHCollectionEditOperation"
        }
      ],
      "role": "symbol",
      "title": "PHCollectionEditOperation",
      "type": "topic",
      "url": "/documentation/photos/phcollectioneditoperation"
    },
    "doc://com.apple.photokit/documentation/Photos/PHCollectionEditOperation/addContent": {
      "abstract": [
        {
          "text": "The collection supports adding items that already exist elsewhere in the photo library.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "addContent"
        }
      ],
      "identifier": "doc://com.apple.photokit/documentation/Photos/PHCollectionEditOperation/addContent",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PHCollectionEditOperationAddContent"
        }
      ],
      "role": "symbol",
      "title": "PHCollectionEditOperation.addContent",
      "type": "topic",
      "url": "/documentation/photos/phcollectioneditoperation/addcontent"
    },
    "doc://com.apple.photokit/documentation/Photos/PHCollectionEditOperation/createContent": {
      "abstract": [
        {
          "text": "The collection supports creating new items.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "createContent"
        }
      ],
      "identifier": "doc://com.apple.photokit/documentation/Photos/PHCollectionEditOperation/createContent",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PHCollectionEditOperationCreateContent"
        }
      ],
      "role": "symbol",
      "title": "PHCollectionEditOperation.createContent",
      "type": "topic",
      "url": "/documentation/photos/phcollectioneditoperation/createcontent"
    },
    "doc://com.apple.photokit/documentation/Photos/PHCollectionEditOperation/delete": {
      "abstract": [
        {
          "text": "The collection itself can be deleted.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "delete"
        }
      ],
      "identifier": "doc://com.apple.photokit/documentation/Photos/PHCollectionEditOperation/delete",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PHCollectionEditOperationDelete"
        }
      ],
      "role": "symbol",
      "title": "PHCollectionEditOperation.delete",
      "type": "topic",
      "url": "/documentation/photos/phcollectioneditoperation/delete"
    },
    "doc://com.apple.photokit/documentation/Photos/PHCollectionEditOperation/deleteContent": {
      "abstract": [
        {
          "text": "The collection supports deleting the items it contains.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "deleteContent"
        }
      ],
      "identifier": "doc://com.apple.photokit/documentation/Photos/PHCollectionEditOperation/deleteContent",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PHCollectionEditOperationDeleteContent"
        }
      ],
      "role": "symbol",
      "title": "PHCollectionEditOperation.deleteContent",
      "type": "topic",
      "url": "/documentation/photos/phcollectioneditoperation/deletecontent"
    },
    "doc://com.apple.photokit/documentation/Photos/PHCollectionEditOperation/init(rawValue:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "?("
        },
        {
          "kind": "externalParam",
          "text": "rawValue"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.photokit/documentation/Photos/PHCollectionEditOperation/init(rawValue:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "init(rawValue:)",
      "type": "topic",
      "url": "/documentation/photos/phcollectioneditoperation/init(rawvalue:)"
    },
    "doc://com.apple.photokit/documentation/Photos/PHCollectionEditOperation/rearrangeContent": {
      "abstract": [
        {
          "text": "The collection supports reordering the arrangement of items it contains.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "rearrangeContent"
        }
      ],
      "identifier": "doc://com.apple.photokit/documentation/Photos/PHCollectionEditOperation/rearrangeContent",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PHCollectionEditOperationRearrangeContent"
        }
      ],
      "role": "symbol",
      "title": "PHCollectionEditOperation.rearrangeContent",
      "type": "topic",
      "url": "/documentation/photos/phcollectioneditoperation/rearrangecontent"
    },
    "doc://com.apple.photokit/documentation/Photos/PHCollectionEditOperation/removeContent": {
      "abstract": [
        {
          "text": "The collection supports removing the items it contains.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "removeContent"
        }
      ],
      "identifier": "doc://com.apple.photokit/documentation/Photos/PHCollectionEditOperation/removeContent",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PHCollectionEditOperationRemoveContent"
        }
      ],
      "role": "symbol",
      "title": "PHCollectionEditOperation.removeContent",
      "type": "topic",
      "url": "/documentation/photos/phcollectioneditoperation/removecontent"
    },
    "doc://com.apple.photokit/documentation/Photos/PHCollectionEditOperation/rename": {
      "abstract": [
        {
          "text": "The collection itself can be renamed.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "rename"
        }
      ],
      "identifier": "doc://com.apple.photokit/documentation/Photos/PHCollectionEditOperation/rename",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PHCollectionEditOperationRename"
        }
      ],
      "role": "symbol",
      "title": "PHCollectionEditOperation.rename",
      "type": "topic",
      "url": "/documentation/photos/phcollectioneditoperation/rename"
    },
    "doc://com.externally.resolved.symbol/c:@T@NSInteger": {
      "abstract": [
        {
          "text": "Describes an integer.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "typealias "
        },
        {
          "kind": "identifier",
          "text": "NSInteger"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:@T@NSInteger",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSInteger",
      "type": "topic",
      "url": "/documentation/objectivec/nsinteger"
    },
    "doc://com.externally.resolved.symbol/s:SH": {
      "abstract": [
        {
          "text": "A type that can be hashed into a `Hasher` to produce an integer hash value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Hashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SQ",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SH",
      "kind": "symbol",
      "role": "symbol",
      "title": "Hashable",
      "type": "topic",
      "url": "/documentation/Swift/Hashable"
    },
    "doc://com.externally.resolved.symbol/s:SQ": {
      "abstract": [
        {
          "text": "A type that can be compared for value equality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SQ",
      "kind": "symbol",
      "role": "symbol",
      "title": "Equatable",
      "type": "topic",
      "url": "/documentation/Swift/Equatable"
    },
    "doc://com.externally.resolved.symbol/s:SY": {
      "abstract": [
        {
          "text": "A type that can be converted to and from an associated raw value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "RawRepresentable"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SY8RawValueQa",
          "text": "RawValue"
        },
        {
          "kind": "text",
          "text": ">"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SY",
      "kind": "symbol",
      "role": "symbol",
      "title": "RawRepresentable",
      "type": "topic",
      "url": "/documentation/Swift/RawRepresentable"
    },
    "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BitwiseCopyable"
        },
        {
          "kind": "text",
          "text": " : ~Escapable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "BitwiseCopyable",
      "type": "topic",
      "url": "/documentation/Swift/BitwiseCopyable"
    },
    "doc://com.externally.resolved.symbol/s:s8SendableP": {
      "abstract": [
        {
          "text": "A thread-safe type whose values can be shared across arbitrary concurrent contexts without introducing a risk of data races.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Sendable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s8SendableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "Sendable",
      "type": "topic",
      "url": "/documentation/Swift/Sendable"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
        "doc://com.externally.resolved.symbol/s:SQ",
        "doc://com.externally.resolved.symbol/s:SH",
        "doc://com.externally.resolved.symbol/s:SY",
        "doc://com.externally.resolved.symbol/s:s8SendableP"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Determining-Collection-Capabilities",
      "generated": true,
      "identifiers": [
        "doc://com.apple.photokit/documentation/Photos/PHCollection/canContainAssets",
        "doc://com.apple.photokit/documentation/Photos/PHCollection/canContainCollections",
        "doc://com.apple.photokit/documentation/Photos/PHCollection/canPerform(_:)"
      ],
      "title": "Determining Collection Capabilities"
    }
  ],
  "topicSections": [
    {
      "anchor": "Constants",
      "identifiers": [
        "doc://com.apple.photokit/documentation/Photos/PHCollectionEditOperation/deleteContent",
        "doc://com.apple.photokit/documentation/Photos/PHCollectionEditOperation/removeContent",
        "doc://com.apple.photokit/documentation/Photos/PHCollectionEditOperation/addContent",
        "doc://com.apple.photokit/documentation/Photos/PHCollectionEditOperation/createContent",
        "doc://com.apple.photokit/documentation/Photos/PHCollectionEditOperation/rearrangeContent",
        "doc://com.apple.photokit/documentation/Photos/PHCollectionEditOperation/delete",
        "doc://com.apple.photokit/documentation/Photos/PHCollectionEditOperation/rename"
      ],
      "title": "Constants"
    },
    {
      "anchor": "Initializers",
      "generated": true,
      "identifiers": [
        "doc://com.apple.photokit/documentation/Photos/PHCollectionEditOperation/init(rawValue:)"
      ],
      "title": "Initializers"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "8.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "8.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.1",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.11",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.0",
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "PHCollectionEditOperation"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "enum"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PHCollectionEditOperation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "PHCollectionEditOperation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.photokit/documentation/Photos"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Constants",
              "identifiers": [
                "doc://com.apple.photokit/documentation/Photos/PHCollectionEditOperation/deleteContent",
                "doc://com.apple.photokit/documentation/Photos/PHCollectionEditOperation/removeContent",
                "doc://com.apple.photokit/documentation/Photos/PHCollectionEditOperation/addContent",
                "doc://com.apple.photokit/documentation/Photos/PHCollectionEditOperation/createContent",
                "doc://com.apple.photokit/documentation/Photos/PHCollectionEditOperation/rearrangeContent",
                "doc://com.apple.photokit/documentation/Photos/PHCollectionEditOperation/delete",
                "doc://com.apple.photokit/documentation/Photos/PHCollectionEditOperation/rename"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Determining-Collection-Capabilities",
              "generated": true,
              "identifiers": [
                "doc://com.apple.photokit/documentation/Photos/PHCollection/canContainAssets",
                "doc://com.apple.photokit/documentation/Photos/PHCollection/canContainCollections",
                "doc://com.apple.photokit/documentation/Photos/PHCollection/canPerform(_:)"
              ],
              "title": "Determining Collection Capabilities"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "enum"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "PHCollectionEditOperation"
                  },
                  {
                    "kind": "text",
                    "text": " : "
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:@T@NSInteger",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@NSInteger",
                    "text": "NSInteger"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHCollection~1canContainCollections/title",
          "value": "canContainCollections"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHCollection~1canContainCollections/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "canContainCollections"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHCollectionEditOperation~1delete/title",
          "value": "PHCollectionEditOperationDelete"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHCollectionEditOperation~1delete/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PHCollectionEditOperationDelete"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHCollectionEditOperation~1deleteContent/title",
          "value": "PHCollectionEditOperationDeleteContent"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHCollectionEditOperation~1deleteContent/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PHCollectionEditOperationDeleteContent"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHCollection~1canContainAssets/title",
          "value": "canContainAssets"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHCollection~1canContainAssets/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "canContainAssets"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHCollectionEditOperation/title",
          "value": "PHCollectionEditOperation"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHCollectionEditOperation/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PHCollectionEditOperation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHCollectionEditOperation/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "PHCollectionEditOperation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHCollectionEditOperation~1removeContent/title",
          "value": "PHCollectionEditOperationRemoveContent"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHCollectionEditOperation~1removeContent/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PHCollectionEditOperationRemoveContent"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHCollectionEditOperation~1rearrangeContent/title",
          "value": "PHCollectionEditOperationRearrangeContent"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHCollectionEditOperation~1rearrangeContent/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PHCollectionEditOperationRearrangeContent"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHCollectionEditOperation~1addContent/title",
          "value": "PHCollectionEditOperationAddContent"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHCollectionEditOperation~1addContent/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PHCollectionEditOperationAddContent"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHCollection~1canPerform(_:)/title",
          "value": "canPerformEditOperation:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHCollection~1canPerform(_:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "canPerformEditOperation:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHCollectionEditOperation~1rename/title",
          "value": "PHCollectionEditOperationRename"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHCollectionEditOperation~1rename/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PHCollectionEditOperationRename"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHCollectionEditOperation~1createContent/title",
          "value": "PHCollectionEditOperationCreateContent"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHCollectionEditOperation~1createContent/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PHCollectionEditOperationCreateContent"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/photos/phcollectioneditoperation"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/photos/phcollectioneditoperation"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
