{"kind":"symbol","abstract":[{"text":"A description of changes that occurred in the set of asset or collection objects listed in a fetch result.","type":"text"}],"sections":[],"seeAlsoSections":[{"title":"Observing Library Changes","anchor":"Observing-Library-Changes","generated":true,"identifiers":["doc://com.apple.photokit/documentation/PhotoKit/observing-changes-in-the-photo-library","doc://com.apple.photokit/documentation/Photos/PHPhotoLibrary/register(_:)-6y3b9","doc://com.apple.photokit/documentation/Photos/PHPhotoLibrary/unregisterChangeObserver(_:)","doc://com.apple.photokit/documentation/Photos/PHPhotoLibraryChangeObserver","doc://com.apple.photokit/documentation/Photos/PHChange","doc://com.apple.photokit/documentation/Photos/PHObjectChangeDetails"]}],"identifier":{"interfaceLanguage":"swift","url":"doc://com.apple.photokit/documentation/Photos/PHFetchResultChangeDetails"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["/documentation/photos/phfetchresultchangedetails"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["/documentation/photos/phfetchresultchangedetails"]}],"metadata":{"title":"PHFetchResultChangeDetails","role":"symbol","roleHeading":"Class","externalID":"c:objc(cs)PHFetchResultChangeDetails","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"PHFetchResultChangeDetails","kind":"identifier"}],"modules":[{"name":"Photos"}],"platforms":[{"beta":false,"name":"iOS","deprecated":false,"unavailable":false,"introducedAt":"8.0"},{"beta":false,"name":"iPadOS","deprecated":false,"unavailable":false,"introducedAt":"8.0"},{"beta":false,"name":"Mac Catalyst","deprecated":false,"unavailable":false,"introducedAt":"13.1"},{"beta":false,"name":"macOS","deprecated":false,"unavailable":false,"introducedAt":"10.13"},{"beta":false,"name":"tvOS","deprecated":false,"unavailable":false,"introducedAt":"10.0"},{"beta":false,"name":"visionOS","deprecated":false,"unavailable":false,"introducedAt":"1.0"}],"navigatorTitle":[{"text":"PHFetchResultChangeDetails","kind":"identifier"}],"symbolKind":"class"},"topicSections":[{"title":"Getting the Changed Fetch Result","anchor":"Getting-the-Changed-Fetch-Result","identifiers":["doc://com.apple.photokit/documentation/Photos/PHFetchResultChangeDetails/fetchResultBeforeChanges","doc://com.apple.photokit/documentation/Photos/PHFetchResultChangeDetails/fetchResultAfterChanges"]},{"title":"Getting Change Information","anchor":"Getting-Change-Information","identifiers":["doc://com.apple.photokit/documentation/Photos/PHFetchResultChangeDetails/hasIncrementalChanges","doc://com.apple.photokit/documentation/Photos/PHFetchResultChangeDetails/removedIndexes","doc://com.apple.photokit/documentation/Photos/PHFetchResultChangeDetails/removedObjects","doc://com.apple.photokit/documentation/Photos/PHFetchResultChangeDetails/insertedIndexes","doc://com.apple.photokit/documentation/Photos/PHFetchResultChangeDetails/insertedObjects","doc://com.apple.photokit/documentation/Photos/PHFetchResultChangeDetails/changedIndexes","doc://com.apple.photokit/documentation/Photos/PHFetchResultChangeDetails/changedObjects","doc://com.apple.photokit/documentation/Photos/PHFetchResultChangeDetails/hasMoves","doc://com.apple.photokit/documentation/Photos/PHFetchResultChangeDetails/enumerateMoves(_:)"]},{"title":"Comparing Fetch Results","anchor":"Comparing-Fetch-Results","identifiers":["doc://com.apple.photokit/documentation/Photos/PHFetchResultChangeDetails/init(from:to:changedObjects:)"]}],"hierarchy":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.photokit/documentation/Photos"]]},"relationshipsSections":[{"title":"Inherits From","kind":"relationships","identifiers":["doc://com.externally.resolved.symbol/c:objc(cs)NSObject"],"type":"inheritsFrom"},{"title":"Conforms To","kind":"relationships","identifiers":["doc://com.externally.resolved.symbol/s:s7CVarArgP","doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP","doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP","doc://com.externally.resolved.symbol/s:SQ","doc://com.externally.resolved.symbol/s:SH","doc://com.externally.resolved.symbol/c:objc(pl)NSObject","doc://com.externally.resolved.symbol/s:s8SendableP"],"type":"conformsTo"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS","iPadOS","Mac Catalyst","macOS","tvOS","visionOS"],"tokens":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"PHFetchResultChangeDetails"},{"kind":"text","text":"<"},{"kind":"genericParameter","text":"ObjectType"},{"kind":"text","text":"> "},{"kind":"keyword","text":"where"},{"kind":"text","text":" "},{"kind":"typeIdentifier","text":"ObjectType"},{"kind":"text","text":" : "},{"preciseIdentifier":"c:objc(cs)PHObject","identifier":"doc://com.apple.photokit/documentation/Photos/PHObject","kind":"typeIdentifier","text":"PHObject"}],"languages":["swift"]}]},{"content":[{"anchor":"overview","type":"heading","level":2,"text":"Overview"},{"inlineContent":[{"text":"A ","type":"text"},{"identifier":"doc://com.apple.photokit/documentation/Photos/PHFetchResultChangeDetails","type":"reference","isActive":true},{"text":" object provides detailed information about the differences between two fetch results—one that you previously obtained and an updated one that would result if you performed the same fetch again. The change details object provides information useful for updating a UI that lists the contents of a fetch result, such as the indexes of added, removed, and rearranged objects.","type":"text"}],"type":"paragraph"},{"anchor":"Processing-Changes-in-Order","type":"heading","level":3,"text":"Processing Changes in Order"},{"inlineContent":[{"text":"PhotoKit describes ","type":"text"},{"identifier":"doc://com.apple.photokit/documentation/Photos/PHFetchResultChangeDetails/changedIndexes","isActive":true,"type":"reference"},{"text":" in the ","type":"text"},{"inlineContent":[{"type":"text","text":"after"}],"type":"emphasis"},{"text":" state, while ","type":"text"},{"identifier":"doc://com.apple.documentation/documentation/UIKit/UICollectionView","isActive":true,"type":"reference"},{"text":"w’s ","type":"text"},{"identifier":"doc://com.apple.documentation/documentation/UIKit/UICollectionView/performBatchUpdates(_:completion:)","isActive":true,"type":"reference"},{"text":" expects them in the ","type":"text"},{"inlineContent":[{"type":"text","text":"before"}],"type":"emphasis"},{"text":" state. As a result, ","type":"text"},{"identifier":"doc://com.apple.photokit/documentation/Photos/PHFetchResultChangeDetails/changedIndexes","isActive":true,"type":"reference"},{"text":" can’t be used safely inside ","type":"text"},{"identifier":"doc://com.apple.documentation/documentation/UIKit/UICollectionView/performBatchUpdates(_:completion:)","isActive":true,"type":"reference"},{"text":".","type":"text"}],"type":"paragraph"},{"inlineContent":[{"type":"text","text":"Instead, use "},{"type":"reference","identifier":"doc://com.apple.photokit/documentation/Photos/PHFetchResultChangeDetails/changedIndexes","isActive":true},{"type":"text","text":" "},{"type":"emphasis","inlineContent":[{"type":"text","text":"after"}]},{"type":"text","text":" and outside the "},{"type":"reference","identifier":"doc://com.apple.documentation/documentation/UIKit/UICollectionView/performBatchUpdates(_:completion:)","isActive":true},{"type":"text","text":" call, reapplying the code used to configure cells in "},{"type":"reference","identifier":"doc://com.apple.documentation/documentation/UIKit/UICollectionView/cellForItem(at:)","isActive":true},{"type":"text","text":" rather than telling "},{"type":"reference","identifier":"doc://com.apple.documentation/documentation/UIKit/UICollectionView","isActive":true},{"type":"text","text":" to reload."}],"type":"paragraph"},{"tabs":[{"title":"Swift","content":[{"type":"codeListing","syntax":"swift","code":["let collectionView = UICollectionView()","let fetchResultChangeDetails = PHFetchResultChangeDetails()","let deletedCollectionIndicesBeforeChanges = IndexSet()","let insertedCollectionIndicesAfterDeletions = IndexSet()","let deletedPhotoPathsBeforeChanges: [IndexPath] = []","let insertedPhotoPathsAfterDeletions: [IndexPath] = []","","collectionView.performBatchUpdates({ () -> Void in","    if (!deletedCollectionIndicesBeforeChanges.isEmpty) {","        collectionView.deleteSections(deletedCollectionIndicesBeforeChanges)","    }","    if (!insertedCollectionIndicesAfterDeletions.isEmpty) {","        collectionView.insertSections(insertedCollectionIndicesAfterDeletions)","    }","    if (!deletedPhotoPathsBeforeChanges.isEmpty) {","        collectionView.deleteItems(at: deletedPhotoPathsBeforeChanges)","    }","    if (!insertedPhotoPathsAfterDeletions.isEmpty) {","        collectionView.insertItems(at: insertedPhotoPathsAfterDeletions)","    }","}, completion:nil)","","guard let changeIndices = fetchResultChangeDetails.changedIndexes else {","    return","}","for indexSetElem in changeIndices {","    let indexPath = IndexPath(item: indexSetElem, section: 0)","    guard let changedCell = collectionView.cellForItem(at: indexPath) else {","        break","    }","    // ... Configure changedCell here ...","}"]}]},{"title":"Objective-C","content":[{"code":["@property (nonatomic, strong) UICollectionView* collectionView;","// ...","PHFetchResultChangeDetails* fetchResultChangeDetails;","NSIndexSet* deletedCollectionIndicesBeforeChanges;","NSIndexSet* insertedCollectionIndicesAfterDeletions;","NSArray* deletedPhotoPathsBeforeChanges;","NSArray* insertedPhotoPathsAfterDeletions;","","[self.collectionView performBatchUpdates:^{","    if (deletedCollectionIndicesBeforeChanges.count > 0) {","        [self.collectionView deleteSections:deletedCollectionIndicesBeforeChanges];","    }","    if (insertedCollectionIndicesAfterDeletions.count > 0) {","        [self.collectionView insertSections:insertedCollectionIndicesAfterDeletions];","    }","    if (deletedPhotoPathsBeforeChanges.count > 0) {","        [self.collectionView deleteItemsAtIndexPaths:deletedPhotoPathsBeforeChanges];","    }","    if (insertedPhotoPathsAfterDeletions) {","        [self.collectionView insertItemsAtIndexPaths:insertedPhotoPathsAfterDeletions];","    }","} completion:nil];","","[fetchResultChangeDetails.changedIndexes enumerateIndexesUsingBlock:^(NSUInteger index, BOOL* stop) {","    NSIndexPath* indexPath = [NSIndexPath indexPathWithItem:index inSection:0];","    UICollectionViewCell* changedCell = [self.collectionView cellForItemAtIndexPath:indexPath];","    if (changedCell) {","        // ... Configure changedCell here ...","    }","    // Set *stop = YES to stop iteration early.","}];"],"syntax":"objc","type":"codeListing"}]}],"type":"tabNavigator"}],"kind":"content"}],"schemaVersion":{"major":0,"minor":3,"patch":0},"references":{"doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP":{"role":"symbol","url":"/documentation/Swift/CustomStringConvertible","type":"topic","abstract":[{"text":"A type with a customized textual representation.","type":"text"}],"identifier":"doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"CustomStringConvertible","kind":"identifier"}],"title":"CustomStringConvertible","kind":"symbol"},"doc://com.apple.documentation/documentation/technologies":{"identifier":"doc://com.apple.documentation/documentation/technologies","role":"overview","type":"topic","kind":"technologies","abstract":[{"type":"text","text":""}],"title":"Technologies","url":"/documentation/technologies"},"doc://com.externally.resolved.symbol/s:SQ":{"type":"topic","identifier":"doc://com.externally.resolved.symbol/s:SQ","abstract":[{"text":"A type that can be compared for value equality.","type":"text"}],"kind":"symbol","title":"Equatable","url":"/documentation/Swift/Equatable","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"Equatable"}],"role":"symbol"},"doc://com.apple.photokit/documentation/Photos/PHFetchResultChangeDetails/fetchResultBeforeChanges":{"abstract":[{"type":"text","text":"The original fetch result, without recent changes."}],"navigatorTitle":[{"text":"fetchResultBeforeChanges","kind":"identifier"}],"kind":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"fetchResultBeforeChanges"},{"text":": ","kind":"text"},{"text":"PHFetchResult","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)PHFetchResult"},{"text":"<","kind":"text"},{"text":"ObjectType","kind":"typeIdentifier"},{"text":">","kind":"text"}],"url":"/documentation/photos/phfetchresultchangedetails/fetchresultbeforechanges","title":"fetchResultBeforeChanges","type":"topic","identifier":"doc://com.apple.photokit/documentation/Photos/PHFetchResultChangeDetails/fetchResultBeforeChanges","role":"symbol"},"doc://com.apple.photokit/documentation/Photos/PHPhotoLibrary/register(_:)-6y3b9":{"identifier":"doc://com.apple.photokit/documentation/Photos/PHPhotoLibrary/register(_:)-6y3b9","url":"/documentation/photos/phphotolibrary/register(_:)-6y3b9","title":"register(_:)","type":"topic","role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"register"},{"kind":"text","text":"(any "},{"preciseIdentifier":"c:objc(pl)PHPhotoLibraryChangeObserver","kind":"typeIdentifier","text":"PHPhotoLibraryChangeObserver"},{"kind":"text","text":")"}],"abstract":[{"text":"Registers an object to receive messages when objects in the photo library change.","type":"text"}],"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"registerChangeObserver:"}]},"doc://com.apple.photokit/documentation/Photos/PHFetchResultChangeDetails/enumerateMoves(_:)":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"enumerateMoves","kind":"identifier"},{"text":"((","kind":"text"},{"text":"Int","preciseIdentifier":"s:Si","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"Int","preciseIdentifier":"s:Si","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"text":"Void","preciseIdentifier":"s:s4Voida","kind":"typeIdentifier"},{"kind":"text","text":")"}],"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"enumerateMovesWithBlock:"}],"identifier":"doc://com.apple.photokit/documentation/Photos/PHFetchResultChangeDetails/enumerateMoves(_:)","title":"enumerateMoves(_:)","abstract":[{"type":"text","text":"Runs the specified block for each case where an object has moved from one index to another in the fetch result."}],"url":"/documentation/photos/phfetchresultchangedetails/enumeratemoves(_:)","role":"symbol","type":"topic"},"doc://com.apple.photokit/documentation/Photos/PHPhotoLibrary/unregisterChangeObserver(_:)":{"identifier":"doc://com.apple.photokit/documentation/Photos/PHPhotoLibrary/unregisterChangeObserver(_:)","url":"/documentation/photos/phphotolibrary/unregisterchangeobserver(_:)","title":"unregisterChangeObserver(_:)","type":"topic","role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"unregisterChangeObserver"},{"kind":"text","text":"(any "},{"preciseIdentifier":"c:objc(pl)PHPhotoLibraryChangeObserver","kind":"typeIdentifier","text":"PHPhotoLibraryChangeObserver"},{"kind":"text","text":")"}],"abstract":[{"text":"Unregisters an object so that it no longer receives change messages.","type":"text"}],"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"unregisterChangeObserver:"}]},"doc://com.apple.photokit/documentation/Photos/PHPhotoLibraryChangeObserver":{"fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"PHPhotoLibraryChangeObserver"}],"url":"/documentation/photos/phphotolibrarychangeobserver","abstract":[{"type":"text","text":"A protocol to adopt to have the system notify your app of changes to the photo library."}],"identifier":"doc://com.apple.photokit/documentation/Photos/PHPhotoLibraryChangeObserver","role":"symbol","type":"topic","title":"PHPhotoLibraryChangeObserver","navigatorTitle":[{"kind":"identifier","text":"PHPhotoLibraryChangeObserver"}],"kind":"symbol"},"doc://com.apple.photokit/documentation/Photos":{"title":"Photos","role":"collection","kind":"symbol","identifier":"doc://com.apple.photokit/documentation/Photos","abstract":[{"type":"text","text":"Work with image and video assets that the Photos app manages, including those from iCloud Photos and Live Photos."}],"type":"topic","url":"/documentation/photos"},"doc://com.externally.resolved.symbol/s:SH":{"type":"topic","role":"symbol","url":"/documentation/Swift/Hashable","abstract":[{"type":"text","text":"A type that can be hashed into a `Hasher` to produce an integer hash value."}],"title":"Hashable","kind":"symbol","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"Hashable"},{"kind":"text","text":" : "},{"preciseIdentifier":"s:SQ","kind":"typeIdentifier","text":"Equatable"}],"identifier":"doc://com.externally.resolved.symbol/s:SH"},"doc://com.apple.photokit/documentation/Photos/PHFetchResultChangeDetails/hasIncrementalChanges":{"url":"/documentation/photos/phfetchresultchangedetails/hasincrementalchanges","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"hasIncrementalChanges"}],"abstract":[{"text":"A Boolean value that indicates whether changes to the fetch result can be described incrementally.","type":"text"}],"identifier":"doc://com.apple.photokit/documentation/Photos/PHFetchResultChangeDetails/hasIncrementalChanges","title":"hasIncrementalChanges","kind":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"hasIncrementalChanges"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"}]},"doc://com.externally.resolved.symbol/s:s7CVarArgP":{"type":"topic","title":"CVarArg","abstract":[{"type":"text","text":"A type whose instances can be encoded, and appropriately passed, as elements of a C `va_list`."}],"kind":"symbol","url":"/documentation/Swift/CVarArg","identifier":"doc://com.externally.resolved.symbol/s:s7CVarArgP","role":"symbol","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"CVarArg","kind":"identifier"}]},"doc://com.externally.resolved.symbol/c:objc(pl)NSObject":{"role":"symbol","fragments":[{"text":"protocol ","kind":"text"},{"text":"NSObjectProtocol","kind":"identifier"}],"identifier":"doc://com.externally.resolved.symbol/c:objc(pl)NSObject","title":"NSObjectProtocol","url":"/documentation/objectivec/nsobjectprotocol","kind":"symbol","type":"topic","abstract":[{"text":"The group of methods that are fundamental to all Objective-C objects.","type":"text"}]},"doc://com.apple.photokit/documentation/Photos/PHObject":{"role":"symbol","title":"PHObject","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"PHObject"}],"kind":"symbol","identifier":"doc://com.apple.photokit/documentation/Photos/PHObject","navigatorTitle":[{"kind":"identifier","text":"PHObject"}],"url":"/documentation/photos/phobject","type":"topic","abstract":[{"type":"text","text":"The abstract superclass for Photos model objects (assets and collections)."}]},"doc://com.apple.photokit/documentation/Photos/PHFetchResultChangeDetails/removedObjects":{"role":"symbol","title":"removedObjects","url":"/documentation/photos/phfetchresultchangedetails/removedobjects","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"removedObjects","kind":"identifier"},{"text":": [","kind":"text"},{"text":"ObjectType","kind":"typeIdentifier"},{"text":"]","kind":"text"}],"identifier":"doc://com.apple.photokit/documentation/Photos/PHFetchResultChangeDetails/removedObjects","navigatorTitle":[{"text":"removedObjects","kind":"identifier"}],"type":"topic","abstract":[{"type":"text","text":"The items that have been removed from the fetch result."}],"kind":"symbol"},"doc://com.apple.photokit/documentation/Photos/PHChange":{"type":"topic","identifier":"doc://com.apple.photokit/documentation/Photos/PHChange","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"PHChange"}],"role":"symbol","title":"PHChange","abstract":[{"type":"text","text":"A description of a change that occurred in the photo library."}],"url":"/documentation/photos/phchange","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"PHChange"}]},"doc://com.apple.photokit/documentation/Photos/PHFetchResultChangeDetails/init(from:to:changedObjects:)":{"navigatorTitle":[{"text":"changeDetailsFromFetchResult:toFetchResult:changedObjects:","kind":"identifier"}],"identifier":"doc://com.apple.photokit/documentation/Photos/PHFetchResultChangeDetails/init(from:to:changedObjects:)","type":"topic","role":"symbol","kind":"symbol","title":"init(from:to:changedObjects:)","abstract":[{"text":"Creates a change details object that summarizes the differences between two fetch results.","type":"text"}],"fragments":[{"kind":"keyword","text":"convenience"},{"kind":"text","text":" "},{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"from"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)PHFetchResult","text":"PHFetchResult"},{"kind":"text","text":"<"},{"kind":"typeIdentifier","text":"ObjectType"},{"kind":"text","text":">, "},{"kind":"externalParam","text":"to"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)PHFetchResult","text":"PHFetchResult"},{"kind":"text","text":"<"},{"text":"ObjectType","kind":"typeIdentifier"},{"text":">, ","kind":"text"},{"text":"changedObjects","kind":"externalParam"},{"text":": [","kind":"text"},{"text":"ObjectType","kind":"typeIdentifier"},{"text":"])","kind":"text"}],"url":"/documentation/photos/phfetchresultchangedetails/init(from:to:changedobjects:)"},"doc://com.externally.resolved.symbol/c:objc(cs)NSObject":{"fragments":[{"text":"class ","kind":"text"},{"text":"NSObject","kind":"identifier"}],"identifier":"doc://com.externally.resolved.symbol/c:objc(cs)NSObject","title":"NSObject","role":"symbol","type":"topic","abstract":[{"text":"The root class of most Objective-C class hierarchies, from which subclasses inherit a basic interface to the runtime system and the ability to behave as Objective-C objects.","type":"text"}],"url":"/documentation/objectivec/nsobject","kind":"symbol"},"doc://com.apple.photokit/documentation/Photos/PHFetchResultChangeDetails":{"title":"PHFetchResultChangeDetails","identifier":"doc://com.apple.photokit/documentation/Photos/PHFetchResultChangeDetails","abstract":[{"text":"A description of changes that occurred in the set of asset or collection objects listed in a fetch result.","type":"text"}],"kind":"symbol","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"PHFetchResultChangeDetails","kind":"identifier"}],"navigatorTitle":[{"text":"PHFetchResultChangeDetails","kind":"identifier"}],"url":"/documentation/photos/phfetchresultchangedetails","type":"topic"},"doc://com.apple.photokit/documentation/Photos/PHFetchResultChangeDetails/removedIndexes":{"role":"symbol","title":"removedIndexes","url":"/documentation/photos/phfetchresultchangedetails/removedindexes","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"removedIndexes"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:10Foundation8IndexSetV","text":"IndexSet"},{"text":"?","kind":"text"}],"identifier":"doc://com.apple.photokit/documentation/Photos/PHFetchResultChangeDetails/removedIndexes","navigatorTitle":[{"text":"removedIndexes","kind":"identifier"}],"type":"topic","abstract":[{"type":"text","text":"The indexes from which objects have been removed from the fetch result."}],"kind":"symbol"},"doc://com.apple.documentation/documentation/UIKit/UICollectionView/cellForItem(at:)":{"identifier":"doc://com.apple.documentation/documentation/UIKit/UICollectionView/cellForItem(at:)","type":"topic","title":"cellForItem(at:)","kind":"symbol","url":"/documentation/UIKit/UICollectionView/cellForItem(at:)","abstract":[{"type":"text","text":"Gets the cell object at the index path you specify."}],"role":"symbol","fragments":[{"kind":"attribute","text":"@"},{"preciseIdentifier":"s:ScM","kind":"attribute","text":"MainActor"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"cellForItem"},{"kind":"text","text":"("},{"kind":"externalParam","text":"at"},{"kind":"text","text":" "},{"kind":"internalParam","text":"indexPath"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:10Foundation9IndexPathV","text":"IndexPath"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UICollectionViewCell","text":"UICollectionViewCell"},{"kind":"text","text":"?"}]},"doc://com.apple.photokit/documentation/Photos/PHFetchResultChangeDetails/changedIndexes":{"url":"/documentation/photos/phfetchresultchangedetails/changedindexes","role":"symbol","navigatorTitle":[{"text":"changedIndexes","kind":"identifier"}],"abstract":[{"type":"text","text":"The indexes of objects in the fetch result whose content or metadata have been updated."}],"identifier":"doc://com.apple.photokit/documentation/Photos/PHFetchResultChangeDetails/changedIndexes","title":"changedIndexes","kind":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"changedIndexes","kind":"identifier"},{"text":": ","kind":"text"},{"text":"IndexSet","kind":"typeIdentifier","preciseIdentifier":"s:10Foundation8IndexSetV"},{"text":"?","kind":"text"}]},"doc://com.apple.photokit/documentation/PhotoKit/observing-changes-in-the-photo-library":{"abstract":[{"text":"Register an observer to be notified of changes to the photo library.","type":"text"}],"url":"/documentation/photokit/observing-changes-in-the-photo-library","role":"article","kind":"article","title":"Observing Changes in the Photo Library","identifier":"doc://com.apple.photokit/documentation/PhotoKit/observing-changes-in-the-photo-library","type":"topic"},"doc://com.apple.photokit/documentation/Photos/PHFetchResultChangeDetails/hasMoves":{"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"hasMoves","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"}],"kind":"symbol","navigatorTitle":[{"text":"hasMoves","kind":"identifier"}],"identifier":"doc://com.apple.photokit/documentation/Photos/PHFetchResultChangeDetails/hasMoves","title":"hasMoves","abstract":[{"text":"A Boolean value that indicates whether objects have been rearranged in the fetch result.","type":"text"}],"url":"/documentation/photos/phfetchresultchangedetails/hasmoves","role":"symbol","type":"topic"},"doc://com.apple.photokit/documentation/Photos/PHFetchResultChangeDetails/insertedIndexes":{"abstract":[{"type":"text","text":"The indexes where new objects have been inserted in the fetch result."}],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"insertedIndexes"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:10Foundation8IndexSetV","text":"IndexSet","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"title":"insertedIndexes","url":"/documentation/photos/phfetchresultchangedetails/insertedindexes","kind":"symbol","role":"symbol","type":"topic","identifier":"doc://com.apple.photokit/documentation/Photos/PHFetchResultChangeDetails/insertedIndexes","navigatorTitle":[{"text":"insertedIndexes","kind":"identifier"}]},"doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP":{"url":"/documentation/Swift/CustomDebugStringConvertible","type":"topic","title":"CustomDebugStringConvertible","kind":"symbol","identifier":"doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"CustomDebugStringConvertible"}],"role":"symbol","abstract":[{"type":"text","text":"A type with a customized textual representation suitable for debugging purposes."}]},"doc://com.apple.documentation/documentation/UIKit/UICollectionView/performBatchUpdates(_:completion:)":{"abstract":[{"text":"Animates multiple insert, delete, reload, and move operations as a group.","type":"text"}],"url":"/documentation/UIKit/UICollectionView/performBatchUpdates(_:completion:)","role":"symbol","kind":"symbol","title":"performBatchUpdates(_:completion:)","identifier":"doc://com.apple.documentation/documentation/UIKit/UICollectionView/performBatchUpdates(_:completion:)","type":"topic","fragments":[{"kind":"attribute","text":"@"},{"kind":"attribute","preciseIdentifier":"s:ScM","text":"MainActor"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"performBatchUpdates"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"updates"},{"kind":"text","text":": (() -> "},{"preciseIdentifier":"s:s4Voida","kind":"typeIdentifier","text":"Void"},{"kind":"text","text":")?, "},{"kind":"externalParam","text":"completion"},{"kind":"text","text":": (("},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":")? = nil)"}]},"doc://com.apple.documentation/documentation/UIKit/UICollectionView":{"identifier":"doc://com.apple.documentation/documentation/UIKit/UICollectionView","url":"/documentation/UIKit/UICollectionView","title":"UICollectionView","type":"topic","role":"symbol","fragments":[{"kind":"attribute","text":"@"},{"preciseIdentifier":"s:ScM","kind":"attribute","text":"MainActor"},{"kind":"text","text":" "},{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"UICollectionView"}],"abstract":[{"text":"An object that manages an ordered collection of data items and presents them using customizable layouts.","type":"text"}],"kind":"symbol"},"doc://com.apple.photokit/documentation/Photos/PHObjectChangeDetails":{"url":"/documentation/photos/phobjectchangedetails","identifier":"doc://com.apple.photokit/documentation/Photos/PHObjectChangeDetails","abstract":[{"type":"text","text":"A description of changes that occurred in an asset or collection object."}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"PHObjectChangeDetails"}],"type":"topic","navigatorTitle":[{"kind":"identifier","text":"PHObjectChangeDetails"}],"kind":"symbol","role":"symbol","title":"PHObjectChangeDetails"},"doc://com.apple.photokit/documentation/Photos/PHFetchResultChangeDetails/fetchResultAfterChanges":{"identifier":"doc://com.apple.photokit/documentation/Photos/PHFetchResultChangeDetails/fetchResultAfterChanges","abstract":[{"type":"text","text":"The current fetch result, incorporating recent changes."}],"kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"fetchResultAfterChanges"}],"title":"fetchResultAfterChanges","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"fetchResultAfterChanges","kind":"identifier"},{"text":": ","kind":"text"},{"text":"PHFetchResult","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)PHFetchResult"},{"text":"<","kind":"text"},{"kind":"typeIdentifier","text":"ObjectType"},{"kind":"text","text":">"}],"role":"symbol","url":"/documentation/photos/phfetchresultchangedetails/fetchresultafterchanges"},"doc://com.apple.photokit/documentation/Photos/PHFetchResultChangeDetails/insertedObjects":{"role":"symbol","title":"insertedObjects","url":"/documentation/photos/phfetchresultchangedetails/insertedobjects","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"insertedObjects","kind":"identifier"},{"text":": [","kind":"text"},{"text":"ObjectType","kind":"typeIdentifier"},{"text":"]","kind":"text"}],"identifier":"doc://com.apple.photokit/documentation/Photos/PHFetchResultChangeDetails/insertedObjects","navigatorTitle":[{"text":"insertedObjects","kind":"identifier"}],"type":"topic","abstract":[{"type":"text","text":"The new items that have been inserted in the fetch result."}],"kind":"symbol"},"doc://com.externally.resolved.symbol/s:s8SendableP":{"role":"symbol","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Sendable","kind":"identifier"}],"identifier":"doc://com.externally.resolved.symbol/s:s8SendableP","title":"Sendable","url":"/documentation/Swift/Sendable","kind":"symbol","type":"topic","abstract":[{"type":"text","text":"A thread-safe type whose values can be shared across arbitrary concurrent contexts without introducing a risk of data races."}]},"doc://com.apple.photokit/documentation/Photos/PHFetchResultChangeDetails/changedObjects":{"role":"symbol","kind":"symbol","identifier":"doc://com.apple.photokit/documentation/Photos/PHFetchResultChangeDetails/changedObjects","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"changedObjects","kind":"identifier"},{"text":": [","kind":"text"},{"text":"ObjectType","kind":"typeIdentifier"},{"text":"]","kind":"text"}],"navigatorTitle":[{"text":"changedObjects","kind":"identifier"}],"url":"/documentation/photos/phfetchresultchangedetails/changedobjects","abstract":[{"text":"The objects in the fetch result whose content or metadata have been updated.","type":"text"}],"title":"changedObjects","type":"topic"}},"variantOverrides":[{"patch":[{"op":"replace","path":"/identifier/interfaceLanguage","value":"occ"},{"op":"replace","path":"/metadata/platforms","value":[{"deprecated":false,"introducedAt":"8.0","beta":false,"name":"iOS","unavailable":false},{"deprecated":false,"introducedAt":"8.0","beta":false,"name":"iPadOS","unavailable":false},{"introducedAt":"13.1","beta":false,"name":"Mac Catalyst","unavailable":false,"deprecated":false},{"introducedAt":"10.13","beta":false,"name":"macOS","unavailable":false,"deprecated":false},{"introducedAt":"10.0","beta":false,"name":"tvOS","unavailable":false,"deprecated":false},{"introducedAt":"1.0","beta":false,"name":"visionOS","unavailable":false,"deprecated":false}]},{"op":"replace","path":"/metadata/roleHeading","value":"Class"},{"op":"replace","path":"/metadata/title","value":"PHFetchResultChangeDetails"},{"op":"replace","path":"/metadata/symbolKind","value":"class"},{"op":"replace","path":"/metadata/fragments","value":[{"text":"PHFetchResultChangeDetails","kind":"identifier"}]},{"op":"replace","path":"/metadata/navigatorTitle","value":[{"kind":"identifier","text":"PHFetchResultChangeDetails"}]},{"op":"replace","path":"/hierarchy","value":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.photokit/documentation/Photos"]]}},{"op":"replace","path":"/topicSections","value":[{"title":"Getting the Changed Fetch Result","anchor":"Getting-the-Changed-Fetch-Result","identifiers":["doc://com.apple.photokit/documentation/Photos/PHFetchResultChangeDetails/fetchResultBeforeChanges","doc://com.apple.photokit/documentation/Photos/PHFetchResultChangeDetails/fetchResultAfterChanges"]},{"title":"Getting Change Information","anchor":"Getting-Change-Information","identifiers":["doc://com.apple.photokit/documentation/Photos/PHFetchResultChangeDetails/hasIncrementalChanges","doc://com.apple.photokit/documentation/Photos/PHFetchResultChangeDetails/removedIndexes","doc://com.apple.photokit/documentation/Photos/PHFetchResultChangeDetails/removedObjects","doc://com.apple.photokit/documentation/Photos/PHFetchResultChangeDetails/insertedIndexes","doc://com.apple.photokit/documentation/Photos/PHFetchResultChangeDetails/insertedObjects","doc://com.apple.photokit/documentation/Photos/PHFetchResultChangeDetails/changedIndexes","doc://com.apple.photokit/documentation/Photos/PHFetchResultChangeDetails/changedObjects","doc://com.apple.photokit/documentation/Photos/PHFetchResultChangeDetails/hasMoves","doc://com.apple.photokit/documentation/Photos/PHFetchResultChangeDetails/enumerateMoves(_:)"]},{"title":"Comparing Fetch Results","anchor":"Comparing-Fetch-Results","identifiers":["doc://com.apple.photokit/documentation/Photos/PHFetchResultChangeDetails/init(from:to:changedObjects:)"]}]},{"op":"replace","path":"/relationshipsSections","value":[{"identifiers":["doc://com.externally.resolved.symbol/c:objc(cs)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"}]},{"op":"replace","path":"/seeAlsoSections","value":[{"title":"Observing Library Changes","identifiers":["doc://com.apple.photokit/documentation/Photos/PHPhotoLibrary/register(_:)-6y3b9","doc://com.apple.photokit/documentation/Photos/PHPhotoLibrary/unregisterChangeObserver(_:)","doc://com.apple.photokit/documentation/Photos/PHPhotoLibraryChangeObserver","doc://com.apple.photokit/documentation/Photos/PHChange","doc://com.apple.photokit/documentation/Photos/PHObjectChangeDetails"],"generated":true,"anchor":"Observing-Library-Changes"}]},{"op":"replace","path":"/primaryContentSections/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"PHFetchResultChangeDetails"},{"kind":"text","text":" : "},{"preciseIdentifier":"c:objc(cs)NSObject","identifier":"doc://com.externally.resolved.symbol/c:objc(cs)NSObject","kind":"typeIdentifier","text":"NSObject"}],"platforms":["iOS","iPadOS","Mac Catalyst","macOS","tvOS","visionOS"],"languages":["occ"]}]}},{"path":"/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHFetchResultChangeDetails~1fetchResultBeforeChanges/title","op":"replace","value":"fetchResultBeforeChanges"},{"path":"/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHFetchResultChangeDetails~1fetchResultBeforeChanges/fragments","op":"replace","value":[{"text":"fetchResultBeforeChanges","kind":"identifier"}]},{"path":"/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHPhotoLibrary~1register(_:)-6y3b9/title","op":"replace","value":"registerChangeObserver:"},{"path":"/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHPhotoLibrary~1register(_:)-6y3b9/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"registerChangeObserver:"}]},{"path":"/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHFetchResultChangeDetails~1enumerateMoves(_:)/title","op":"replace","value":"enumerateMovesWithBlock:"},{"path":"/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHFetchResultChangeDetails~1enumerateMoves(_:)/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"text":"enumerateMovesWithBlock:","kind":"identifier"}]},{"path":"/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHPhotoLibrary~1unregisterChangeObserver(_:)/title","op":"replace","value":"unregisterChangeObserver:"},{"path":"/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHPhotoLibrary~1unregisterChangeObserver(_:)/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"text":"unregisterChangeObserver:","kind":"identifier"}]},{"path":"/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHPhotoLibraryChangeObserver/title","op":"replace","value":"PHPhotoLibraryChangeObserver"},{"path":"/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHPhotoLibraryChangeObserver/fragments","op":"replace","value":[{"kind":"identifier","text":"PHPhotoLibraryChangeObserver"}]},{"path":"/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHPhotoLibraryChangeObserver/navigatorTitle","op":"replace","value":[{"text":"PHPhotoLibraryChangeObserver","kind":"identifier"}]},{"path":"/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHFetchResultChangeDetails~1hasIncrementalChanges/title","op":"replace","value":"hasIncrementalChanges"},{"path":"/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHFetchResultChangeDetails~1hasIncrementalChanges/fragments","op":"replace","value":[{"text":"hasIncrementalChanges","kind":"identifier"}]},{"path":"/references/doc:~1~1com.externally.resolved.symbol~1c:objc(pl)NSObject/title","op":"replace","value":"NSObject"},{"path":"/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHObject/title","op":"replace","value":"PHObject"},{"path":"/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHObject/fragments","op":"replace","value":[{"kind":"identifier","text":"PHObject"}]},{"path":"/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHObject/navigatorTitle","op":"replace","value":[{"text":"PHObject","kind":"identifier"}]},{"path":"/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHFetchResultChangeDetails~1removedObjects/title","op":"replace","value":"removedObjects"},{"path":"/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHFetchResultChangeDetails~1removedObjects/fragments","op":"replace","value":[{"kind":"identifier","text":"removedObjects"}]},{"path":"/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHChange/title","op":"replace","value":"PHChange"},{"path":"/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHChange/fragments","op":"replace","value":[{"kind":"identifier","text":"PHChange"}]},{"path":"/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHChange/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"PHChange"}]},{"path":"/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHFetchResultChangeDetails~1init(from:to:changedObjects:)/title","op":"replace","value":"changeDetailsFromFetchResult:toFetchResult:changedObjects:"},{"path":"/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHFetchResultChangeDetails~1init(from:to:changedObjects:)/fragments","op":"replace","value":[{"text":"+ ","kind":"text"},{"text":"changeDetailsFromFetchResult:toFetchResult:changedObjects:","kind":"identifier"}]},{"path":"/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHFetchResultChangeDetails/title","op":"replace","value":"PHFetchResultChangeDetails"},{"path":"/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHFetchResultChangeDetails/fragments","op":"replace","value":[{"text":"PHFetchResultChangeDetails","kind":"identifier"}]},{"path":"/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHFetchResultChangeDetails/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"PHFetchResultChangeDetails"}]},{"path":"/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHFetchResultChangeDetails~1removedIndexes/title","op":"replace","value":"removedIndexes"},{"path":"/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHFetchResultChangeDetails~1removedIndexes/fragments","op":"replace","value":[{"kind":"identifier","text":"removedIndexes"}]},{"path":"/references/doc:~1~1com.apple.documentation~1documentation~1UIKit~1UICollectionView~1cellForItem(at:)/title","op":"replace","value":"cellForItemAtIndexPath:"},{"path":"/references/doc:~1~1com.apple.documentation~1documentation~1UIKit~1UICollectionView~1cellForItem(at:)/fragments","op":"replace","value":[{"text":"- (","kind":"text"},{"text":"UICollectionViewCell","preciseIdentifier":"c:objc(cs)UICollectionViewCell","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"cellForItemAtIndexPath:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSIndexPath","preciseIdentifier":"c:objc(cs)NSIndexPath","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"indexPath","kind":"internalParam"},{"text":";","kind":"text"}]},{"path":"/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHFetchResultChangeDetails~1changedIndexes/title","op":"replace","value":"changedIndexes"},{"path":"/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHFetchResultChangeDetails~1changedIndexes/fragments","op":"replace","value":[{"kind":"identifier","text":"changedIndexes"}]},{"path":"/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHFetchResultChangeDetails~1hasMoves/title","op":"replace","value":"hasMoves"},{"path":"/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHFetchResultChangeDetails~1hasMoves/fragments","op":"replace","value":[{"text":"hasMoves","kind":"identifier"}]},{"path":"/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHFetchResultChangeDetails~1insertedIndexes/title","op":"replace","value":"insertedIndexes"},{"path":"/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHFetchResultChangeDetails~1insertedIndexes/fragments","op":"replace","value":[{"kind":"identifier","text":"insertedIndexes"}]},{"path":"/references/doc:~1~1com.apple.documentation~1documentation~1UIKit~1UICollectionView~1performBatchUpdates(_:completion:)/title","op":"replace","value":"performBatchUpdates:completion:"},{"path":"/references/doc:~1~1com.apple.documentation~1documentation~1UIKit~1UICollectionView~1performBatchUpdates(_:completion:)/fragments","op":"replace","value":[{"text":"- (","kind":"text"},{"text":"void","preciseIdentifier":"c:v","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"performBatchUpdates:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"void","preciseIdentifier":"c:v","kind":"typeIdentifier"},{"text":" (^)()) ","kind":"text"},{"text":"updates","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"completion:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"void","preciseIdentifier":"c:v","kind":"typeIdentifier"},{"text":" (^)(","kind":"text"},{"text":"BOOL","preciseIdentifier":"c:@T@BOOL","kind":"typeIdentifier"},{"text":" ","kind":"text"},{"text":"finished","kind":"internalParam"},{"text":")) ","kind":"text"},{"text":"completion","kind":"internalParam"},{"text":";","kind":"text"}]},{"path":"/references/doc:~1~1com.apple.documentation~1documentation~1UIKit~1UICollectionView/fragments","op":"replace","value":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"UICollectionView"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIScrollView","text":"UIScrollView"}]},{"path":"/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHObjectChangeDetails/title","op":"replace","value":"PHObjectChangeDetails"},{"path":"/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHObjectChangeDetails/fragments","op":"replace","value":[{"kind":"identifier","text":"PHObjectChangeDetails"}]},{"path":"/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHObjectChangeDetails/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"PHObjectChangeDetails"}]},{"path":"/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHFetchResultChangeDetails~1fetchResultAfterChanges/title","op":"replace","value":"fetchResultAfterChanges"},{"path":"/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHFetchResultChangeDetails~1fetchResultAfterChanges/fragments","op":"replace","value":[{"text":"fetchResultAfterChanges","kind":"identifier"}]},{"path":"/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHFetchResultChangeDetails~1insertedObjects/title","op":"replace","value":"insertedObjects"},{"path":"/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHFetchResultChangeDetails~1insertedObjects/fragments","op":"replace","value":[{"kind":"identifier","text":"insertedObjects"}]},{"path":"/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHFetchResultChangeDetails~1changedObjects/title","op":"replace","value":"changedObjects"},{"path":"/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHFetchResultChangeDetails~1changedObjects/fragments","op":"replace","value":[{"text":"changedObjects","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}],"legalNotices":{"copyright":"Copyright &copy; 2025 Apple Inc. All rights reserved.","termsOfUse":"https://www.apple.com/legal/internet-services/terms/site.html","privacyPolicy":"https://www.apple.com/privacy/privacy-policy"}}