{
  "abstract": [
    {
      "text": "Options for delivering requested image data, used by the ",
      "type": "text"
    },
    {
      "identifier": "doc://com.apple.photokit/documentation/Photos/PHImageRequestOptions/deliveryMode",
      "isActive": true,
      "type": "reference"
    },
    {
      "text": " property.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.photokit/documentation/Photos"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.photokit/documentation/Photos/PHImageRequestOptionsDeliveryMode"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@PHImageRequestOptionsDeliveryMode",
    "fragments": [
      {
        "kind": "keyword",
        "text": "enum"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "PHImageRequestOptionsDeliveryMode"
      }
    ],
    "modules": [
      {
        "name": "Photos"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "PHImageRequestOptionsDeliveryMode"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "8.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "8.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.1",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.13",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.0",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Enumeration",
    "symbolKind": "enum",
    "title": "PHImageRequestOptionsDeliveryMode"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "enum"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "PHImageRequestOptionsDeliveryMode"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.photokit/documentation/Photos": {
      "abstract": [
        {
          "text": "Work with image and video assets that the Photos app manages, including those from iCloud Photos and Live Photos.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.photokit/documentation/Photos",
      "kind": "symbol",
      "role": "collection",
      "title": "Photos",
      "type": "topic",
      "url": "/documentation/photos"
    },
    "doc://com.apple.photokit/documentation/Photos/PHImageRequestOptions/deliveryMode": {
      "abstract": [
        {
          "text": "The requested image quality and delivery priority.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "deliveryMode"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@PHImageRequestOptionsDeliveryMode",
          "text": "PHImageRequestOptionsDeliveryMode"
        }
      ],
      "identifier": "doc://com.apple.photokit/documentation/Photos/PHImageRequestOptions/deliveryMode",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "deliveryMode"
        }
      ],
      "role": "symbol",
      "title": "deliveryMode",
      "type": "topic",
      "url": "/documentation/photos/phimagerequestoptions/deliverymode"
    },
    "doc://com.apple.photokit/documentation/Photos/PHImageRequestOptions/normalizedCropRect": {
      "abstract": [
        {
          "text": "A rectangle for requesting a cropped version of the original image.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "normalizedCropRect"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@CGRect",
          "text": "CGRect"
        }
      ],
      "identifier": "doc://com.apple.photokit/documentation/Photos/PHImageRequestOptions/normalizedCropRect",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "normalizedCropRect"
        }
      ],
      "role": "symbol",
      "title": "normalizedCropRect",
      "type": "topic",
      "url": "/documentation/photos/phimagerequestoptions/normalizedcroprect"
    },
    "doc://com.apple.photokit/documentation/Photos/PHImageRequestOptions/resizeMode": {
      "abstract": [
        {
          "text": "A mode that specifies how to resize the requested image.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "resizeMode"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@PHImageRequestOptionsResizeMode",
          "text": "PHImageRequestOptionsResizeMode"
        }
      ],
      "identifier": "doc://com.apple.photokit/documentation/Photos/PHImageRequestOptions/resizeMode",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "resizeMode"
        }
      ],
      "role": "symbol",
      "title": "resizeMode",
      "type": "topic",
      "url": "/documentation/photos/phimagerequestoptions/resizemode"
    },
    "doc://com.apple.photokit/documentation/Photos/PHImageRequestOptions/version": {
      "abstract": [
        {
          "text": "The version of the image to be requested.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "version"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@PHImageRequestOptionsVersion",
          "text": "PHImageRequestOptionsVersion"
        }
      ],
      "identifier": "doc://com.apple.photokit/documentation/Photos/PHImageRequestOptions/version",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "version"
        }
      ],
      "role": "symbol",
      "title": "version",
      "type": "topic",
      "url": "/documentation/photos/phimagerequestoptions/version"
    },
    "doc://com.apple.photokit/documentation/Photos/PHImageRequestOptionsDeliveryMode": {
      "abstract": [
        {
          "text": "Options for delivering requested image data, used by the ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.photokit/documentation/Photos/PHImageRequestOptions/deliveryMode",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " property.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "PHImageRequestOptionsDeliveryMode"
        }
      ],
      "identifier": "doc://com.apple.photokit/documentation/Photos/PHImageRequestOptionsDeliveryMode",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PHImageRequestOptionsDeliveryMode"
        }
      ],
      "role": "symbol",
      "title": "PHImageRequestOptionsDeliveryMode",
      "type": "topic",
      "url": "/documentation/photos/phimagerequestoptionsdeliverymode"
    },
    "doc://com.apple.photokit/documentation/Photos/PHImageRequestOptionsDeliveryMode/fastFormat": {
      "abstract": [
        {
          "text": "Photos provides only a fast-loading image, possibly sacrificing image quality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "fastFormat"
        }
      ],
      "identifier": "doc://com.apple.photokit/documentation/Photos/PHImageRequestOptionsDeliveryMode/fastFormat",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PHImageRequestOptionsDeliveryModeFastFormat"
        }
      ],
      "role": "symbol",
      "title": "PHImageRequestOptionsDeliveryMode.fastFormat",
      "type": "topic",
      "url": "/documentation/photos/phimagerequestoptionsdeliverymode/fastformat"
    },
    "doc://com.apple.photokit/documentation/Photos/PHImageRequestOptionsDeliveryMode/highQualityFormat": {
      "abstract": [
        {
          "text": "Photos provides only the highest-quality image available, regardless of how much time it takes to load.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "highQualityFormat"
        }
      ],
      "identifier": "doc://com.apple.photokit/documentation/Photos/PHImageRequestOptionsDeliveryMode/highQualityFormat",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PHImageRequestOptionsDeliveryModeHighQualityFormat"
        }
      ],
      "role": "symbol",
      "title": "PHImageRequestOptionsDeliveryMode.highQualityFormat",
      "type": "topic",
      "url": "/documentation/photos/phimagerequestoptionsdeliverymode/highqualityformat"
    },
    "doc://com.apple.photokit/documentation/Photos/PHImageRequestOptionsDeliveryMode/init(rawValue:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "?("
        },
        {
          "kind": "externalParam",
          "text": "rawValue"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.photokit/documentation/Photos/PHImageRequestOptionsDeliveryMode/init(rawValue:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "init(rawValue:)",
      "type": "topic",
      "url": "/documentation/photos/phimagerequestoptionsdeliverymode/init(rawvalue:)"
    },
    "doc://com.apple.photokit/documentation/Photos/PHImageRequestOptionsDeliveryMode/opportunistic": {
      "abstract": [
        {
          "text": "Photos automatically provides one or more results in order to balance image quality and responsiveness.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "opportunistic"
        }
      ],
      "identifier": "doc://com.apple.photokit/documentation/Photos/PHImageRequestOptionsDeliveryMode/opportunistic",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PHImageRequestOptionsDeliveryModeOpportunistic"
        }
      ],
      "role": "symbol",
      "title": "PHImageRequestOptionsDeliveryMode.opportunistic",
      "type": "topic",
      "url": "/documentation/photos/phimagerequestoptionsdeliverymode/opportunistic"
    },
    "doc://com.apple.photokit/documentation/Photos/PHImageRequestOptionsResizeMode": {
      "abstract": [
        {
          "text": "Options for how to resize the requested image to fit a target size, used by the ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.photokit/documentation/Photos/PHImageRequestOptions/resizeMode",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " property.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "PHImageRequestOptionsResizeMode"
        }
      ],
      "identifier": "doc://com.apple.photokit/documentation/Photos/PHImageRequestOptionsResizeMode",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PHImageRequestOptionsResizeMode"
        }
      ],
      "role": "symbol",
      "title": "PHImageRequestOptionsResizeMode",
      "type": "topic",
      "url": "/documentation/photos/phimagerequestoptionsresizemode"
    },
    "doc://com.apple.photokit/documentation/Photos/PHImageRequestOptionsVersion": {
      "abstract": [
        {
          "text": "Options for requesting an image asset with or without adjustments, used by the ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.photokit/documentation/Photos/PHImageRequestOptions/version",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " property.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "PHImageRequestOptionsVersion"
        }
      ],
      "identifier": "doc://com.apple.photokit/documentation/Photos/PHImageRequestOptionsVersion",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PHImageRequestOptionsVersion"
        }
      ],
      "role": "symbol",
      "title": "PHImageRequestOptionsVersion",
      "type": "topic",
      "url": "/documentation/photos/phimagerequestoptionsversion"
    },
    "doc://com.externally.resolved.symbol/c:@T@NSInteger": {
      "abstract": [
        {
          "text": "Describes an integer.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "typealias "
        },
        {
          "kind": "identifier",
          "text": "NSInteger"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:@T@NSInteger",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSInteger",
      "type": "topic",
      "url": "/documentation/objectivec/nsinteger"
    },
    "doc://com.externally.resolved.symbol/s:SH": {
      "abstract": [
        {
          "text": "A type that can be hashed into a `Hasher` to produce an integer hash value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Hashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SQ",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SH",
      "kind": "symbol",
      "role": "symbol",
      "title": "Hashable",
      "type": "topic",
      "url": "/documentation/Swift/Hashable"
    },
    "doc://com.externally.resolved.symbol/s:SQ": {
      "abstract": [
        {
          "text": "A type that can be compared for value equality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SQ",
      "kind": "symbol",
      "role": "symbol",
      "title": "Equatable",
      "type": "topic",
      "url": "/documentation/Swift/Equatable"
    },
    "doc://com.externally.resolved.symbol/s:SY": {
      "abstract": [
        {
          "text": "A type that can be converted to and from an associated raw value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "RawRepresentable"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SY8RawValueQa",
          "text": "RawValue"
        },
        {
          "kind": "text",
          "text": ">"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SY",
      "kind": "symbol",
      "role": "symbol",
      "title": "RawRepresentable",
      "type": "topic",
      "url": "/documentation/Swift/RawRepresentable"
    },
    "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BitwiseCopyable"
        },
        {
          "kind": "text",
          "text": " : ~Escapable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "BitwiseCopyable",
      "type": "topic",
      "url": "/documentation/Swift/BitwiseCopyable"
    },
    "doc://com.externally.resolved.symbol/s:s8SendableP": {
      "abstract": [
        {
          "text": "A thread-safe type whose values can be shared across arbitrary concurrent contexts without introducing a risk of data races.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Sendable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s8SendableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "Sendable",
      "type": "topic",
      "url": "/documentation/Swift/Sendable"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
        "doc://com.externally.resolved.symbol/s:SQ",
        "doc://com.externally.resolved.symbol/s:SH",
        "doc://com.externally.resolved.symbol/s:SY",
        "doc://com.externally.resolved.symbol/s:s8SendableP"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Specifying-Image-Request-Options",
      "generated": true,
      "identifiers": [
        "doc://com.apple.photokit/documentation/Photos/PHImageRequestOptions/version",
        "doc://com.apple.photokit/documentation/Photos/PHImageRequestOptionsVersion",
        "doc://com.apple.photokit/documentation/Photos/PHImageRequestOptions/deliveryMode",
        "doc://com.apple.photokit/documentation/Photos/PHImageRequestOptions/resizeMode",
        "doc://com.apple.photokit/documentation/Photos/PHImageRequestOptionsResizeMode",
        "doc://com.apple.photokit/documentation/Photos/PHImageRequestOptions/normalizedCropRect"
      ],
      "title": "Specifying Image Request Options"
    }
  ],
  "topicSections": [
    {
      "anchor": "Constants",
      "identifiers": [
        "doc://com.apple.photokit/documentation/Photos/PHImageRequestOptionsDeliveryMode/opportunistic",
        "doc://com.apple.photokit/documentation/Photos/PHImageRequestOptionsDeliveryMode/highQualityFormat",
        "doc://com.apple.photokit/documentation/Photos/PHImageRequestOptionsDeliveryMode/fastFormat"
      ],
      "title": "Constants"
    },
    {
      "anchor": "Initializers",
      "generated": true,
      "identifiers": [
        "doc://com.apple.photokit/documentation/Photos/PHImageRequestOptionsDeliveryMode/init(rawValue:)"
      ],
      "title": "Initializers"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "8.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "8.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.1",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.13",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.0",
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "PHImageRequestOptionsDeliveryMode"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "enum"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PHImageRequestOptionsDeliveryMode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "PHImageRequestOptionsDeliveryMode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.photokit/documentation/Photos"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Constants",
              "identifiers": [
                "doc://com.apple.photokit/documentation/Photos/PHImageRequestOptionsDeliveryMode/opportunistic",
                "doc://com.apple.photokit/documentation/Photos/PHImageRequestOptionsDeliveryMode/highQualityFormat",
                "doc://com.apple.photokit/documentation/Photos/PHImageRequestOptionsDeliveryMode/fastFormat"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Specifying-Image-Request-Options",
              "generated": true,
              "identifiers": [
                "doc://com.apple.photokit/documentation/Photos/PHImageRequestOptions/version",
                "doc://com.apple.photokit/documentation/Photos/PHImageRequestOptionsVersion",
                "doc://com.apple.photokit/documentation/Photos/PHImageRequestOptions/deliveryMode",
                "doc://com.apple.photokit/documentation/Photos/PHImageRequestOptions/resizeMode",
                "doc://com.apple.photokit/documentation/Photos/PHImageRequestOptionsResizeMode",
                "doc://com.apple.photokit/documentation/Photos/PHImageRequestOptions/normalizedCropRect"
              ],
              "title": "Specifying Image Request Options"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "enum"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "PHImageRequestOptionsDeliveryMode"
                  },
                  {
                    "kind": "text",
                    "text": " : "
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:@T@NSInteger",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@NSInteger",
                    "text": "NSInteger"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHImageRequestOptionsDeliveryMode~1highQualityFormat/title",
          "value": "PHImageRequestOptionsDeliveryModeHighQualityFormat"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHImageRequestOptionsDeliveryMode~1highQualityFormat/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PHImageRequestOptionsDeliveryModeHighQualityFormat"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHImageRequestOptionsResizeMode/title",
          "value": "PHImageRequestOptionsResizeMode"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHImageRequestOptionsResizeMode/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PHImageRequestOptionsResizeMode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHImageRequestOptionsResizeMode/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "PHImageRequestOptionsResizeMode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHImageRequestOptionsDeliveryMode/title",
          "value": "PHImageRequestOptionsDeliveryMode"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHImageRequestOptionsDeliveryMode/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PHImageRequestOptionsDeliveryMode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHImageRequestOptionsDeliveryMode/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "PHImageRequestOptionsDeliveryMode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHImageRequestOptionsVersion/title",
          "value": "PHImageRequestOptionsVersion"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHImageRequestOptionsVersion/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PHImageRequestOptionsVersion"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHImageRequestOptionsVersion/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "PHImageRequestOptionsVersion"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHImageRequestOptions~1deliveryMode/title",
          "value": "deliveryMode"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHImageRequestOptions~1deliveryMode/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "deliveryMode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHImageRequestOptions~1resizeMode/title",
          "value": "resizeMode"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHImageRequestOptions~1resizeMode/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "resizeMode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHImageRequestOptions~1normalizedCropRect/title",
          "value": "normalizedCropRect"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHImageRequestOptions~1normalizedCropRect/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "normalizedCropRect"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHImageRequestOptions~1version/title",
          "value": "version"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHImageRequestOptions~1version/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "version"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHImageRequestOptionsDeliveryMode~1fastFormat/title",
          "value": "PHImageRequestOptionsDeliveryModeFastFormat"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHImageRequestOptionsDeliveryMode~1fastFormat/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PHImageRequestOptionsDeliveryModeFastFormat"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHImageRequestOptionsDeliveryMode~1opportunistic/title",
          "value": "PHImageRequestOptionsDeliveryModeOpportunistic"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHImageRequestOptionsDeliveryMode~1opportunistic/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PHImageRequestOptionsDeliveryModeOpportunistic"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/photos/phimagerequestoptionsdeliverymode"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/photos/phimagerequestoptionsdeliverymode"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
