{
  "abstract": [
    {
      "text": "A container that provides image content for a single frame of a Live Photo in an editing context.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.photokit/documentation/Photos"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.photokit/documentation/Photos/PHLivePhotoFrame"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(pl)PHLivePhotoFrame",
    "fragments": [
      {
        "kind": "keyword",
        "text": "protocol"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "PHLivePhotoFrame"
      }
    ],
    "modules": [
      {
        "name": "Photos"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "PHLivePhotoFrame"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.1",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.12",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.0",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Protocol",
    "symbolKind": "protocol",
    "title": "PHLivePhotoFrame"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "protocol"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "PHLivePhotoFrame"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "You don’t create classes that implement this protocol. Instead, you provide a ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.photokit/documentation/Photos/PHLivePhotoEditingContext/frameProcessor",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " block when editing a Live Photo with the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.photokit/documentation/Photos/PHLivePhotoEditingContext",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " class. When you process your edits for output or display, Photos calls your block repeatedly to process each frame of the Live Photo’s video and still photo content. On each call, Photos provides the frame’s image content and associated information in an object that adopts this protocol. In that block, you use that object’s ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.photokit/documentation/Photos/PHLivePhotoFrame/image",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " property to access the image to be edited, then perform your edits and return another ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/coreimage/ciimage",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " object representing the result of processing the input image.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/coreimage/ciimage": {
      "abstract": [
        {
          "text": "A representation of an image to be processed or produced by Core Image filters.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "class "
        },
        {
          "kind": "identifier",
          "text": "CIImage"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/coreimage/ciimage",
      "kind": "symbol",
      "role": "symbol",
      "title": "CIImage",
      "type": "topic",
      "url": "/documentation/coreimage/ciimage"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.photokit/documentation/PhotoKit/editing-asset-content": {
      "abstract": [
        {
          "text": "Make a request to modify and save a photo or video asset.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.photokit/documentation/PhotoKit/editing-asset-content",
      "kind": "article",
      "role": "article",
      "title": "Editing Asset Content",
      "type": "topic",
      "url": "/documentation/photokit/editing-asset-content"
    },
    "doc://com.apple.photokit/documentation/PhotoKit/editing-request-info-keys": {
      "abstract": [
        {
          "text": "Keys indicating the status of an asset content editing request, used in the completion handler of the ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.photokit/documentation/Photos/PHAsset/requestContentEditingInput(with:completionHandler:)",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " method.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.photokit/documentation/PhotoKit/editing-request-info-keys",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Editing Request Info Keys",
      "type": "topic",
      "url": "/documentation/photokit/editing-request-info-keys"
    },
    "doc://com.apple.photokit/documentation/Photos": {
      "abstract": [
        {
          "text": "Work with image and video assets that the Photos app manages, including those from iCloud Photos and Live Photos.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.photokit/documentation/Photos",
      "kind": "symbol",
      "role": "collection",
      "title": "Photos",
      "type": "topic",
      "url": "/documentation/photos"
    },
    "doc://com.apple.photokit/documentation/Photos/PHAdjustmentData": {
      "abstract": [
        {
          "text": "A description of the edits made to an asset’s photo, video, or Live Photo content, which allows your app to reconstruct or revert the effects of prior editing sessions.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "PHAdjustmentData"
        }
      ],
      "identifier": "doc://com.apple.photokit/documentation/Photos/PHAdjustmentData",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PHAdjustmentData"
        }
      ],
      "role": "symbol",
      "title": "PHAdjustmentData",
      "type": "topic",
      "url": "/documentation/photos/phadjustmentdata"
    },
    "doc://com.apple.photokit/documentation/Photos/PHAsset/canPerform(_:)": {
      "abstract": [
        {
          "text": "Returns whether the asset supports the specified editing operation.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "canPerform"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@PHAssetEditOperation",
          "text": "PHAssetEditOperation"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.photokit/documentation/Photos/PHAsset/canPerform(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "canPerformEditOperation:"
        }
      ],
      "role": "symbol",
      "title": "canPerform(_:)",
      "type": "topic",
      "url": "/documentation/photos/phasset/canperform(_:)"
    },
    "doc://com.apple.photokit/documentation/Photos/PHAsset/cancelContentEditingInputRequest(_:)": {
      "abstract": [
        {
          "text": "Cancels a request for editing the asset’s content.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "cancelContentEditingInputRequest"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@PHContentEditingInputRequestID",
          "text": "PHContentEditingInputRequestID"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.photokit/documentation/Photos/PHAsset/cancelContentEditingInputRequest(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "cancelContentEditingInputRequest:"
        }
      ],
      "role": "symbol",
      "title": "cancelContentEditingInputRequest(_:)",
      "type": "topic",
      "url": "/documentation/photos/phasset/cancelcontenteditinginputrequest(_:)"
    },
    "doc://com.apple.photokit/documentation/Photos/PHAsset/requestContentEditingInput(with:completionHandler:)": {
      "abstract": [
        {
          "text": "Requests asset information for beginning a content editing session.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "requestContentEditingInput"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "with"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)PHContentEditingInputRequestOptions",
          "text": "PHContentEditingInputRequestOptions"
        },
        {
          "kind": "text",
          "text": "?, "
        },
        {
          "kind": "externalParam",
          "text": "completionHandler"
        },
        {
          "kind": "text",
          "text": ": ("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)PHContentEditingInput",
          "text": "PHContentEditingInput"
        },
        {
          "kind": "text",
          "text": "?, ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s11AnyHashableV",
          "text": "AnyHashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "keyword",
          "text": "Any"
        },
        {
          "kind": "text",
          "text": "]) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s4Voida",
          "text": "Void"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@PHContentEditingInputRequestID",
          "text": "PHContentEditingInputRequestID"
        }
      ],
      "identifier": "doc://com.apple.photokit/documentation/Photos/PHAsset/requestContentEditingInput(with:completionHandler:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "requestContentEditingInputWithOptions:completionHandler:"
        }
      ],
      "role": "symbol",
      "title": "requestContentEditingInput(with:completionHandler:)",
      "type": "topic",
      "url": "/documentation/photos/phasset/requestcontenteditinginput(with:completionhandler:)"
    },
    "doc://com.apple.photokit/documentation/Photos/PHAssetEditOperation": {
      "abstract": [
        {
          "text": "Values identifying possible actions an asset can support, used by the ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.photokit/documentation/Photos/PHAsset/canPerform(_:)",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " method.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "PHAssetEditOperation"
        }
      ],
      "identifier": "doc://com.apple.photokit/documentation/Photos/PHAssetEditOperation",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PHAssetEditOperation"
        }
      ],
      "role": "symbol",
      "title": "PHAssetEditOperation",
      "type": "topic",
      "url": "/documentation/photos/phasseteditoperation"
    },
    "doc://com.apple.photokit/documentation/Photos/PHContentEditingInput": {
      "abstract": [
        {
          "text": "A container that provides information about and access to the image, video, or Live Photo content of an asset to be edited.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "PHContentEditingInput"
        }
      ],
      "identifier": "doc://com.apple.photokit/documentation/Photos/PHContentEditingInput",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PHContentEditingInput"
        }
      ],
      "role": "symbol",
      "title": "PHContentEditingInput",
      "type": "topic",
      "url": "/documentation/photos/phcontenteditinginput"
    },
    "doc://com.apple.photokit/documentation/Photos/PHContentEditingInputRequestID": {
      "abstract": [
        {
          "text": "An identifier for an asset content editing session.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "PHContentEditingInputRequestID"
        }
      ],
      "identifier": "doc://com.apple.photokit/documentation/Photos/PHContentEditingInputRequestID",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PHContentEditingInputRequestID"
        }
      ],
      "role": "symbol",
      "title": "PHContentEditingInputRequestID",
      "type": "topic",
      "url": "/documentation/photos/phcontenteditinginputrequestid"
    },
    "doc://com.apple.photokit/documentation/Photos/PHContentEditingInputRequestOptions": {
      "abstract": [
        {
          "text": "A set of options affecting the delivery of image or video data when you request to edit the content of a Photos asset.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "PHContentEditingInputRequestOptions"
        }
      ],
      "identifier": "doc://com.apple.photokit/documentation/Photos/PHContentEditingInputRequestOptions",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PHContentEditingInputRequestOptions"
        }
      ],
      "role": "symbol",
      "title": "PHContentEditingInputRequestOptions",
      "type": "topic",
      "url": "/documentation/photos/phcontenteditinginputrequestoptions"
    },
    "doc://com.apple.photokit/documentation/Photos/PHContentEditingOutput": {
      "abstract": [
        {
          "text": "A container to which you provide the results of editing the photo, video, or Live Photo content of a Photos asset.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "PHContentEditingOutput"
        }
      ],
      "identifier": "doc://com.apple.photokit/documentation/Photos/PHContentEditingOutput",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PHContentEditingOutput"
        }
      ],
      "role": "symbol",
      "title": "PHContentEditingOutput",
      "type": "topic",
      "url": "/documentation/photos/phcontenteditingoutput"
    },
    "doc://com.apple.photokit/documentation/Photos/PHLivePhotoEditingContext": {
      "abstract": [
        {
          "text": "An editing session for modifying the photo, video, and audio content of a Live Photo.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "PHLivePhotoEditingContext"
        }
      ],
      "identifier": "doc://com.apple.photokit/documentation/Photos/PHLivePhotoEditingContext",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PHLivePhotoEditingContext"
        }
      ],
      "role": "symbol",
      "title": "PHLivePhotoEditingContext",
      "type": "topic",
      "url": "/documentation/photos/phlivephotoeditingcontext"
    },
    "doc://com.apple.photokit/documentation/Photos/PHLivePhotoEditingContext/frameProcessor": {
      "abstract": [
        {
          "text": "A block to be called by Photos for processing each frame of the Live Photo’s visual content.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "frameProcessor"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@PHLivePhotoFrameProcessingBlock",
          "text": "PHLivePhotoFrameProcessingBlock"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.photokit/documentation/Photos/PHLivePhotoEditingContext/frameProcessor",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "frameProcessor"
        }
      ],
      "role": "symbol",
      "title": "frameProcessor",
      "type": "topic",
      "url": "/documentation/photos/phlivephotoeditingcontext/frameprocessor"
    },
    "doc://com.apple.photokit/documentation/Photos/PHLivePhotoFrame": {
      "abstract": [
        {
          "text": "A container that provides image content for a single frame of a Live Photo in an editing context.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "PHLivePhotoFrame"
        }
      ],
      "identifier": "doc://com.apple.photokit/documentation/Photos/PHLivePhotoFrame",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PHLivePhotoFrame"
        }
      ],
      "role": "symbol",
      "title": "PHLivePhotoFrame",
      "type": "topic",
      "url": "/documentation/photos/phlivephotoframe"
    },
    "doc://com.apple.photokit/documentation/Photos/PHLivePhotoFrame/image": {
      "abstract": [
        {
          "text": "The image content of the frame to be processed.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "image"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)CIImage",
          "text": "CIImage"
        }
      ],
      "identifier": "doc://com.apple.photokit/documentation/Photos/PHLivePhotoFrame/image",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "image"
        }
      ],
      "required": true,
      "role": "symbol",
      "title": "image",
      "type": "topic",
      "url": "/documentation/photos/phlivephotoframe/image"
    },
    "doc://com.apple.photokit/documentation/Photos/PHLivePhotoFrame/renderScale": {
      "abstract": [
        {
          "text": "The scale factor of the frame image relative to the Live Photo’s photo content.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "renderScale"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:14CoreFoundation7CGFloatV",
          "text": "CGFloat"
        }
      ],
      "identifier": "doc://com.apple.photokit/documentation/Photos/PHLivePhotoFrame/renderScale",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "renderScale"
        }
      ],
      "required": true,
      "role": "symbol",
      "title": "renderScale",
      "type": "topic",
      "url": "/documentation/photos/phlivephotoframe/renderscale"
    },
    "doc://com.apple.photokit/documentation/Photos/PHLivePhotoFrame/time": {
      "abstract": [
        {
          "text": "The time offset, in seconds, of this frame relative to the start of the Live Photo.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "time"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@SA@CMTime",
          "text": "CMTime"
        }
      ],
      "identifier": "doc://com.apple.photokit/documentation/Photos/PHLivePhotoFrame/time",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "time"
        }
      ],
      "required": true,
      "role": "symbol",
      "title": "time",
      "type": "topic",
      "url": "/documentation/photos/phlivephotoframe/time"
    },
    "doc://com.apple.photokit/documentation/Photos/PHLivePhotoFrame/type": {
      "abstract": [
        {
          "text": "The type of image content in this frame.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "type"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@PHLivePhotoFrameType",
          "text": "PHLivePhotoFrameType"
        }
      ],
      "identifier": "doc://com.apple.photokit/documentation/Photos/PHLivePhotoFrame/type",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "type"
        }
      ],
      "required": true,
      "role": "symbol",
      "title": "type",
      "type": "topic",
      "url": "/documentation/photos/phlivephotoframe/type"
    },
    "doc://com.apple.photokit/documentation/Photos/PHLivePhotoFrameType": {
      "abstract": [
        {
          "text": "Identifiers for the type of frame image to be processed. Used with the ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.photokit/documentation/Photos/PHLivePhotoFrame/type",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " property.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "PHLivePhotoFrameType"
        }
      ],
      "identifier": "doc://com.apple.photokit/documentation/Photos/PHLivePhotoFrameType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PHLivePhotoFrameType"
        }
      ],
      "role": "symbol",
      "title": "PHLivePhotoFrameType",
      "type": "topic",
      "url": "/documentation/photos/phlivephotoframetype"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Editing-an-Asset",
      "generated": true,
      "identifiers": [
        "doc://com.apple.photokit/documentation/PhotoKit/editing-asset-content",
        "doc://com.apple.photokit/documentation/Photos/PHContentEditingInput",
        "doc://com.apple.photokit/documentation/Photos/PHContentEditingOutput",
        "doc://com.apple.photokit/documentation/Photos/PHAdjustmentData",
        "doc://com.apple.photokit/documentation/Photos/PHContentEditingInputRequestOptions",
        "doc://com.apple.photokit/documentation/Photos/PHLivePhotoEditingContext",
        "doc://com.apple.photokit/documentation/Photos/PHAsset/canPerform(_:)",
        "doc://com.apple.photokit/documentation/Photos/PHAssetEditOperation",
        "doc://com.apple.photokit/documentation/Photos/PHAsset/requestContentEditingInput(with:completionHandler:)",
        "doc://com.apple.photokit/documentation/Photos/PHAsset/cancelContentEditingInputRequest(_:)",
        "doc://com.apple.photokit/documentation/Photos/PHContentEditingInputRequestID",
        "doc://com.apple.photokit/documentation/PhotoKit/editing-request-info-keys"
      ],
      "title": "Editing an Asset"
    }
  ],
  "topicSections": [
    {
      "anchor": "Editing-the-Frame-Image",
      "identifiers": [
        "doc://com.apple.photokit/documentation/Photos/PHLivePhotoFrame/image"
      ],
      "title": "Editing the Frame Image"
    },
    {
      "anchor": "Getting-Information-About-the-Frame",
      "identifiers": [
        "doc://com.apple.photokit/documentation/Photos/PHLivePhotoFrame/renderScale",
        "doc://com.apple.photokit/documentation/Photos/PHLivePhotoFrame/time",
        "doc://com.apple.photokit/documentation/Photos/PHLivePhotoFrame/type",
        "doc://com.apple.photokit/documentation/Photos/PHLivePhotoFrameType"
      ],
      "title": "Getting Information About the Frame"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.1",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.12",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.0",
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Protocol"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "PHLivePhotoFrame"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "protocol"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PHLivePhotoFrame"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "PHLivePhotoFrame"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.photokit/documentation/Photos"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Editing-the-Frame-Image",
              "identifiers": [
                "doc://com.apple.photokit/documentation/Photos/PHLivePhotoFrame/image"
              ],
              "title": "Editing the Frame Image"
            },
            {
              "anchor": "Getting-Information-About-the-Frame",
              "identifiers": [
                "doc://com.apple.photokit/documentation/Photos/PHLivePhotoFrame/renderScale",
                "doc://com.apple.photokit/documentation/Photos/PHLivePhotoFrame/time",
                "doc://com.apple.photokit/documentation/Photos/PHLivePhotoFrame/type",
                "doc://com.apple.photokit/documentation/Photos/PHLivePhotoFrameType"
              ],
              "title": "Getting Information About the Frame"
            }
          ]
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Editing-an-Asset",
              "generated": true,
              "identifiers": [
                "doc://com.apple.photokit/documentation/Photos/PHContentEditingInput",
                "doc://com.apple.photokit/documentation/Photos/PHContentEditingOutput",
                "doc://com.apple.photokit/documentation/Photos/PHAdjustmentData",
                "doc://com.apple.photokit/documentation/Photos/PHContentEditingInputRequestOptions",
                "doc://com.apple.photokit/documentation/Photos/PHLivePhotoEditingContext",
                "doc://com.apple.photokit/documentation/Photos/PHAsset/canPerform(_:)",
                "doc://com.apple.photokit/documentation/Photos/PHAssetEditOperation",
                "doc://com.apple.photokit/documentation/Photos/PHAsset/requestContentEditingInput(with:completionHandler:)",
                "doc://com.apple.photokit/documentation/Photos/PHAsset/cancelContentEditingInputRequest(_:)",
                "doc://com.apple.photokit/documentation/Photos/PHContentEditingInputRequestID"
              ],
              "title": "Editing an Asset"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "@protocol"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "PHLivePhotoFrame"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHAsset~1requestContentEditingInput(with:completionHandler:)/title",
          "value": "requestContentEditingInputWithOptions:completionHandler:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHAsset~1requestContentEditingInput(with:completionHandler:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "requestContentEditingInputWithOptions:completionHandler:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHAsset~1cancelContentEditingInputRequest(_:)/title",
          "value": "cancelContentEditingInputRequest:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHAsset~1cancelContentEditingInputRequest(_:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "cancelContentEditingInputRequest:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHAsset~1canPerform(_:)/title",
          "value": "canPerformEditOperation:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHAsset~1canPerform(_:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "canPerformEditOperation:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHLivePhotoEditingContext~1frameProcessor/title",
          "value": "frameProcessor"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHLivePhotoEditingContext~1frameProcessor/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "frameProcessor"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHAssetEditOperation/title",
          "value": "PHAssetEditOperation"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHAssetEditOperation/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PHAssetEditOperation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHAssetEditOperation/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "PHAssetEditOperation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHContentEditingInputRequestOptions/title",
          "value": "PHContentEditingInputRequestOptions"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHContentEditingInputRequestOptions/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PHContentEditingInputRequestOptions"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHContentEditingInputRequestOptions/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "PHContentEditingInputRequestOptions"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHLivePhotoEditingContext/title",
          "value": "PHLivePhotoEditingContext"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHLivePhotoEditingContext/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PHLivePhotoEditingContext"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHLivePhotoEditingContext/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "PHLivePhotoEditingContext"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHLivePhotoFrame~1image/title",
          "value": "image"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHLivePhotoFrame~1image/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "image"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHLivePhotoFrame/title",
          "value": "PHLivePhotoFrame"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHLivePhotoFrame/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PHLivePhotoFrame"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHLivePhotoFrame/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "PHLivePhotoFrame"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHLivePhotoFrame~1type/title",
          "value": "type"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHLivePhotoFrame~1type/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "type"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHLivePhotoFrame~1renderScale/title",
          "value": "renderScale"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHLivePhotoFrame~1renderScale/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "renderScale"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHLivePhotoFrame~1time/title",
          "value": "time"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHLivePhotoFrame~1time/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "time"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHContentEditingInputRequestID/title",
          "value": "PHContentEditingInputRequestID"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHContentEditingInputRequestID/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PHContentEditingInputRequestID"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHContentEditingInputRequestID/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "PHContentEditingInputRequestID"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHLivePhotoFrameType/title",
          "value": "PHLivePhotoFrameType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHLivePhotoFrameType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PHLivePhotoFrameType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHLivePhotoFrameType/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "PHLivePhotoFrameType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHAdjustmentData/title",
          "value": "PHAdjustmentData"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHAdjustmentData/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PHAdjustmentData"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHAdjustmentData/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "PHAdjustmentData"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHContentEditingOutput/title",
          "value": "PHContentEditingOutput"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHContentEditingOutput/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PHContentEditingOutput"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHContentEditingOutput/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "PHContentEditingOutput"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHContentEditingInput/title",
          "value": "PHContentEditingInput"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHContentEditingInput/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PHContentEditingInput"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHContentEditingInput/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "PHContentEditingInput"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/photos/phlivephotoframe"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/photos/phlivephotoframe"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
