{
  "abstract": [
    {
      "text": "A constant value that indicates that the system can’t resolve a local object from a global identifier.",
      "type": "text"
    }
  ],
  "deprecationSummary": [
    {
      "inlineContent": [
        {
          "text": "Use ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.photokit/documentation/Photos/PHLocalIdentifierMapping",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " instead.",
          "type": "text"
        }
      ],
      "type": "paragraph"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.photokit/documentation/Photos"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.photokit/documentation/Photos/PHLocalIdentifierNotFound"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@PHLocalIdentifierNotFound",
    "fragments": [
      {
        "kind": "keyword",
        "text": "let"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "PHLocalIdentifierNotFound"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "s:SS",
        "text": "String"
      }
    ],
    "modules": [
      {
        "name": "Photos"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "PHLocalIdentifierNotFound"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "12.0",
        "introducedAt": "10.13",
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Global Variable",
    "symbolKind": "var",
    "title": "PHLocalIdentifierNotFound"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "macOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "let"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "PHLocalIdentifierNotFound"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:SS",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:SS",
              "text": "String"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.photokit/documentation/Photos": {
      "abstract": [
        {
          "text": "Work with image and video assets that the Photos app manages, including those from iCloud Photos and Live Photos.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.photokit/documentation/Photos",
      "kind": "symbol",
      "role": "collection",
      "title": "Photos",
      "type": "topic",
      "url": "/documentation/photos"
    },
    "doc://com.apple.photokit/documentation/Photos/PHCloudIdentifier": {
      "abstract": [
        {
          "text": "An object that identifies an asset or collection that syncs through iCloud Photos.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "PHCloudIdentifier"
        }
      ],
      "identifier": "doc://com.apple.photokit/documentation/Photos/PHCloudIdentifier",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PHCloudIdentifier"
        }
      ],
      "role": "symbol",
      "title": "PHCloudIdentifier",
      "type": "topic",
      "url": "/documentation/photos/phcloudidentifier"
    },
    "doc://com.apple.photokit/documentation/Photos/PHCloudIdentifierMapping": {
      "abstract": [
        {
          "text": "An object that contains the cloud identifier result from looking up a local identifier, or an error indicating why the lookup failed.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "PHCloudIdentifierMapping"
        }
      ],
      "identifier": "doc://com.apple.photokit/documentation/Photos/PHCloudIdentifierMapping",
      "kind": "symbol",
      "role": "symbol",
      "title": "PHCloudIdentifierMapping",
      "type": "topic",
      "url": "/documentation/photos/phcloudidentifiermapping"
    },
    "doc://com.apple.photokit/documentation/Photos/PHLocalIdentifierMapping": {
      "abstract": [
        {
          "text": "An object that contains the local identifier result from looking up a cloud identifier, or an error indicating why the lookup failed.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "PHLocalIdentifierMapping"
        }
      ],
      "identifier": "doc://com.apple.photokit/documentation/Photos/PHLocalIdentifierMapping",
      "kind": "symbol",
      "role": "symbol",
      "title": "PHLocalIdentifierMapping",
      "type": "topic",
      "url": "/documentation/photos/phlocalidentifiermapping"
    },
    "doc://com.apple.photokit/documentation/Photos/PHLocalIdentifierNotFound": {
      "abstract": [
        {
          "text": "A constant value that indicates that the system can’t resolve a local object from a global identifier.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "PHLocalIdentifierNotFound"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.photokit/documentation/Photos/PHLocalIdentifierNotFound",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PHLocalIdentifierNotFound"
        }
      ],
      "role": "symbol",
      "title": "PHLocalIdentifierNotFound",
      "type": "topic",
      "url": "/documentation/photos/phlocalidentifiernotfound"
    },
    "doc://com.apple.photokit/documentation/Photos/PHPhotoLibrary/cloudIdentifierMappings(forLocalIdentifiers:)": {
      "abstract": [
        {
          "text": "Retrieves the cloud identifier mappings for the list of local identifiers.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "cloudIdentifierMappings"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "forLocalIdentifiers"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": "]) -> ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6ResultO",
          "text": "Result"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)PHCloudIdentifier",
          "text": "PHCloudIdentifier"
        },
        {
          "kind": "text",
          "text": ", any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5ErrorP",
          "text": "Error"
        },
        {
          "kind": "text",
          "text": ">]"
        }
      ],
      "identifier": "doc://com.apple.photokit/documentation/Photos/PHPhotoLibrary/cloudIdentifierMappings(forLocalIdentifiers:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "cloudIdentifierMappings(forLocalIdentifiers:)",
      "type": "topic",
      "url": "/documentation/photos/phphotolibrary/cloudidentifiermappings(forlocalidentifiers:)"
    },
    "doc://com.apple.photokit/documentation/Photos/PHPhotoLibrary/cloudIdentifierMappingsForLocalIdentifiers:": {
      "abstract": [
        {
          "text": "Retrieves the cloud identifier mappings for the list of local identifiers.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "- "
        },
        {
          "kind": "identifier",
          "text": "cloudIdentifierMappingsForLocalIdentifiers:"
        }
      ],
      "identifier": "doc://com.apple.photokit/documentation/Photos/PHPhotoLibrary/cloudIdentifierMappingsForLocalIdentifiers:",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "cloudIdentifierMappingsForLocalIdentifiers:"
        }
      ],
      "role": "symbol",
      "title": "cloudIdentifierMappingsForLocalIdentifiers:",
      "type": "topic",
      "url": "/documentation/photos/phphotolibrary/cloudidentifiermappingsforlocalidentifiers:"
    },
    "doc://com.apple.photokit/documentation/Photos/PHPhotoLibrary/cloudIdentifiers(forLocalIdentifiers:)": {
      "abstract": [
        {
          "text": "Retrieves the equivalent iCloud identifiers for the list of local identifiers.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "cloudIdentifiers"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "forLocalIdentifiers"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": "]) -> ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)PHCloudIdentifier",
          "text": "PHCloudIdentifier"
        },
        {
          "kind": "text",
          "text": "]"
        }
      ],
      "identifier": "doc://com.apple.photokit/documentation/Photos/PHPhotoLibrary/cloudIdentifiers(forLocalIdentifiers:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "cloudIdentifiersForLocalIdentifiers:"
        }
      ],
      "role": "symbol",
      "title": "cloudIdentifiers(forLocalIdentifiers:)",
      "type": "topic",
      "url": "/documentation/photos/phphotolibrary/cloudidentifiers(forlocalidentifiers:)"
    },
    "doc://com.apple.photokit/documentation/Photos/PHPhotoLibrary/localIdentifierMappings(for:)": {
      "abstract": [
        {
          "text": "Retrieves the local identifier mappings for the list of cloud identifiers.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "localIdentifierMappings"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "for"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)PHCloudIdentifier",
          "text": "PHCloudIdentifier"
        },
        {
          "kind": "text",
          "text": "]) -> ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)PHCloudIdentifier",
          "text": "PHCloudIdentifier"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6ResultO",
          "text": "Result"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": ", any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5ErrorP",
          "text": "Error"
        },
        {
          "kind": "text",
          "text": ">]"
        }
      ],
      "identifier": "doc://com.apple.photokit/documentation/Photos/PHPhotoLibrary/localIdentifierMappings(for:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "localIdentifierMappings(for:)",
      "type": "topic",
      "url": "/documentation/photos/phphotolibrary/localidentifiermappings(for:)"
    },
    "doc://com.apple.photokit/documentation/Photos/PHPhotoLibrary/localIdentifierMappingsForCloudIdentifiers:": {
      "abstract": [
        {
          "text": "Retrieves the local identifier mappings for the list of cloud identifiers.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "- "
        },
        {
          "kind": "identifier",
          "text": "localIdentifierMappingsForCloudIdentifiers:"
        }
      ],
      "identifier": "doc://com.apple.photokit/documentation/Photos/PHPhotoLibrary/localIdentifierMappingsForCloudIdentifiers:",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "localIdentifierMappingsForCloudIdentifiers:"
        }
      ],
      "role": "symbol",
      "title": "localIdentifierMappingsForCloudIdentifiers:",
      "type": "topic",
      "url": "/documentation/photos/phphotolibrary/localidentifiermappingsforcloudidentifiers:"
    },
    "doc://com.apple.photokit/documentation/Photos/PHPhotoLibrary/localIdentifiers(for:)": {
      "abstract": [
        {
          "text": "Retrieves the equivalent local identifiers for the list of iCloud identifiers.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "localIdentifiers"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "for"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)PHCloudIdentifier",
          "text": "PHCloudIdentifier"
        },
        {
          "kind": "text",
          "text": "]) -> ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": "]"
        }
      ],
      "identifier": "doc://com.apple.photokit/documentation/Photos/PHPhotoLibrary/localIdentifiers(for:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "localIdentifiersForCloudIdentifiers:"
        }
      ],
      "role": "symbol",
      "title": "localIdentifiers(for:)",
      "type": "topic",
      "url": "/documentation/photos/phphotolibrary/localidentifiers(for:)"
    },
    "doc://com.externally.resolved.symbol/c:objc(cs)NSString": {
      "abstract": [
        {
          "text": "A static, plain-text Unicode string object which you use when you need reference semantics or other Foundation-specific behavior. ",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "class "
        },
        {
          "kind": "identifier",
          "text": "NSString"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSString",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSString",
      "type": "topic",
      "url": "/documentation/foundation/nsstring"
    },
    "doc://com.externally.resolved.symbol/s:SS": {
      "abstract": [
        {
          "text": "A Unicode string value that is a collection of characters.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@frozen"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "String"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SS",
      "kind": "symbol",
      "role": "symbol",
      "title": "String",
      "type": "topic",
      "url": "/documentation/Swift/String"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Converting-Between-Local-and-iCloud-Identifiers",
      "generated": true,
      "identifiers": [
        "doc://com.apple.photokit/documentation/Photos/PHPhotoLibrary/cloudIdentifierMappings(forLocalIdentifiers:)",
        "doc://com.apple.photokit/documentation/Photos/PHPhotoLibrary/localIdentifierMappings(for:)",
        "doc://com.apple.photokit/documentation/Photos/PHCloudIdentifier",
        "doc://com.apple.photokit/documentation/Photos/PHPhotoLibrary/cloudIdentifiers(forLocalIdentifiers:)",
        "doc://com.apple.photokit/documentation/Photos/PHPhotoLibrary/localIdentifiers(for:)"
      ],
      "title": "Converting Between Local and iCloud Identifiers"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "deprecatedAt": "12.0",
              "introducedAt": "10.13",
              "name": "macOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Global Variable"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "PHLocalIdentifierNotFound"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "var"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PHLocalIdentifierNotFound"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.photokit/documentation/Photos"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Converting-Between-Local-and-iCloud-Identifiers",
              "generated": true,
              "identifiers": [
                "doc://com.apple.photokit/documentation/Photos/PHPhotoLibrary/cloudIdentifierMappingsForLocalIdentifiers:",
                "doc://com.apple.photokit/documentation/Photos/PHPhotoLibrary/localIdentifierMappingsForCloudIdentifiers:",
                "doc://com.apple.photokit/documentation/Photos/PHCloudIdentifier",
                "doc://com.apple.photokit/documentation/Photos/PHCloudIdentifierMapping",
                "doc://com.apple.photokit/documentation/Photos/PHLocalIdentifierMapping",
                "doc://com.apple.photokit/documentation/Photos/PHPhotoLibrary/cloudIdentifiers(forLocalIdentifiers:)",
                "doc://com.apple.photokit/documentation/Photos/PHPhotoLibrary/localIdentifiers(for:)"
              ],
              "title": "Converting Between Local and iCloud Identifiers"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "extern"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSString",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(cs)NSString",
                    "text": "NSString"
                  },
                  {
                    "kind": "text",
                    "text": " * "
                  },
                  {
                    "kind": "keyword",
                    "text": "const"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "PHLocalIdentifierNotFound"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/deprecationSummary",
          "value": [
            {
              "inlineContent": [
                {
                  "text": "Use ",
                  "type": "text"
                },
                {
                  "identifier": "doc://com.apple.photokit/documentation/Photos/PHLocalIdentifierMapping",
                  "isActive": true,
                  "type": "reference"
                },
                {
                  "text": " instead.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:objc(cs)NSString/abstract",
          "value": [
            {
              "text": "A static, plain-text Unicode string object.",
              "type": "text"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHLocalIdentifierNotFound/title",
          "value": "PHLocalIdentifierNotFound"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHLocalIdentifierNotFound/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PHLocalIdentifierNotFound"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHPhotoLibrary~1localIdentifiers(for:)/title",
          "value": "localIdentifiersForCloudIdentifiers:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHPhotoLibrary~1localIdentifiers(for:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "localIdentifiersForCloudIdentifiers:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHPhotoLibrary~1cloudIdentifiers(forLocalIdentifiers:)/title",
          "value": "cloudIdentifiersForLocalIdentifiers:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHPhotoLibrary~1cloudIdentifiers(forLocalIdentifiers:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "cloudIdentifiersForLocalIdentifiers:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHCloudIdentifier/title",
          "value": "PHCloudIdentifier"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHCloudIdentifier/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PHCloudIdentifier"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHCloudIdentifier/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "PHCloudIdentifier"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/photos/phlocalidentifiernotfound"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/photos/phlocalidentifiernotfound"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
