{
  "abstract": [
    {
      "text": "An object that contains the local identifier result from looking up a cloud identifier, or an error indicating why the lookup failed.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.photokit/documentation/Photos"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "occ",
    "url": "doc://com.apple.photokit/documentation/Photos/PHLocalIdentifierMapping"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(cs)PHLocalIdentifierMapping",
    "fragments": [
      {
        "kind": "identifier",
        "text": "PHLocalIdentifierMapping"
      }
    ],
    "modules": [
      {
        "name": "Photos"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "PHLocalIdentifierMapping"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "15.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "15.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "15.0",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "12.0",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "15.0",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Class",
    "symbolKind": "class",
    "title": "PHLocalIdentifierMapping"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "occ"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "@interface"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "PHLocalIdentifierMapping"
            },
            {
              "kind": "text",
              "text": " : "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSObject",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)NSObject",
              "text": "NSObject"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.photokit/documentation/Photos": {
      "abstract": [
        {
          "text": "Work with image and video assets that the Photos app manages, including those from iCloud Photos and Live Photos.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.photokit/documentation/Photos",
      "kind": "symbol",
      "role": "collection",
      "title": "Photos",
      "type": "topic",
      "url": "/documentation/photos"
    },
    "doc://com.apple.photokit/documentation/Photos/PHCloudIdentifier": {
      "abstract": [
        {
          "text": "An object that identifies an asset or collection that syncs through iCloud Photos.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "PHCloudIdentifier"
        }
      ],
      "identifier": "doc://com.apple.photokit/documentation/Photos/PHCloudIdentifier",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PHCloudIdentifier"
        }
      ],
      "role": "symbol",
      "title": "PHCloudIdentifier",
      "type": "topic",
      "url": "/documentation/photos/phcloudidentifier"
    },
    "doc://com.apple.photokit/documentation/Photos/PHCloudIdentifierMapping": {
      "abstract": [
        {
          "text": "An object that contains the cloud identifier result from looking up a local identifier, or an error indicating why the lookup failed.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "PHCloudIdentifierMapping"
        }
      ],
      "identifier": "doc://com.apple.photokit/documentation/Photos/PHCloudIdentifierMapping",
      "kind": "symbol",
      "role": "symbol",
      "title": "PHCloudIdentifierMapping",
      "type": "topic",
      "url": "/documentation/photos/phcloudidentifiermapping"
    },
    "doc://com.apple.photokit/documentation/Photos/PHLocalIdentifierMapping": {
      "abstract": [
        {
          "text": "An object that contains the local identifier result from looking up a cloud identifier, or an error indicating why the lookup failed.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "PHLocalIdentifierMapping"
        }
      ],
      "identifier": "doc://com.apple.photokit/documentation/Photos/PHLocalIdentifierMapping",
      "kind": "symbol",
      "role": "symbol",
      "title": "PHLocalIdentifierMapping",
      "type": "topic",
      "url": "/documentation/photos/phlocalidentifiermapping"
    },
    "doc://com.apple.photokit/documentation/Photos/PHLocalIdentifierMapping/error": {
      "abstract": [
        {
          "text": "An error indicating why the local identifier lookup failed.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "error"
        }
      ],
      "identifier": "doc://com.apple.photokit/documentation/Photos/PHLocalIdentifierMapping/error",
      "kind": "symbol",
      "role": "symbol",
      "title": "error",
      "type": "topic",
      "url": "/documentation/photos/phlocalidentifiermapping/error"
    },
    "doc://com.apple.photokit/documentation/Photos/PHLocalIdentifierMapping/localIdentifier": {
      "abstract": [
        {
          "text": "The local identifier associated with a iCloud identifier.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "localIdentifier"
        }
      ],
      "identifier": "doc://com.apple.photokit/documentation/Photos/PHLocalIdentifierMapping/localIdentifier",
      "kind": "symbol",
      "role": "symbol",
      "title": "localIdentifier",
      "type": "topic",
      "url": "/documentation/photos/phlocalidentifiermapping/localidentifier"
    },
    "doc://com.apple.photokit/documentation/Photos/PHLocalIdentifierNotFound": {
      "abstract": [
        {
          "text": "A constant value that indicates that the system can’t resolve a local object from a global identifier.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "PHLocalIdentifierNotFound"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.photokit/documentation/Photos/PHLocalIdentifierNotFound",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PHLocalIdentifierNotFound"
        }
      ],
      "role": "symbol",
      "title": "PHLocalIdentifierNotFound",
      "type": "topic",
      "url": "/documentation/photos/phlocalidentifiernotfound"
    },
    "doc://com.apple.photokit/documentation/Photos/PHPhotoLibrary/cloudIdentifierMappingsForLocalIdentifiers:": {
      "abstract": [
        {
          "text": "Retrieves the cloud identifier mappings for the list of local identifiers.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "- "
        },
        {
          "kind": "identifier",
          "text": "cloudIdentifierMappingsForLocalIdentifiers:"
        }
      ],
      "identifier": "doc://com.apple.photokit/documentation/Photos/PHPhotoLibrary/cloudIdentifierMappingsForLocalIdentifiers:",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "cloudIdentifierMappingsForLocalIdentifiers:"
        }
      ],
      "role": "symbol",
      "title": "cloudIdentifierMappingsForLocalIdentifiers:",
      "type": "topic",
      "url": "/documentation/photos/phphotolibrary/cloudidentifiermappingsforlocalidentifiers:"
    },
    "doc://com.apple.photokit/documentation/Photos/PHPhotoLibrary/cloudIdentifiers(forLocalIdentifiers:)": {
      "abstract": [
        {
          "text": "Retrieves the equivalent iCloud identifiers for the list of local identifiers.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "cloudIdentifiers"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "forLocalIdentifiers"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": "]) -> ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)PHCloudIdentifier",
          "text": "PHCloudIdentifier"
        },
        {
          "kind": "text",
          "text": "]"
        }
      ],
      "identifier": "doc://com.apple.photokit/documentation/Photos/PHPhotoLibrary/cloudIdentifiers(forLocalIdentifiers:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "cloudIdentifiersForLocalIdentifiers:"
        }
      ],
      "role": "symbol",
      "title": "cloudIdentifiers(forLocalIdentifiers:)",
      "type": "topic",
      "url": "/documentation/photos/phphotolibrary/cloudidentifiers(forlocalidentifiers:)"
    },
    "doc://com.apple.photokit/documentation/Photos/PHPhotoLibrary/localIdentifierMappingsForCloudIdentifiers:": {
      "abstract": [
        {
          "text": "Retrieves the local identifier mappings for the list of cloud identifiers.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "- "
        },
        {
          "kind": "identifier",
          "text": "localIdentifierMappingsForCloudIdentifiers:"
        }
      ],
      "identifier": "doc://com.apple.photokit/documentation/Photos/PHPhotoLibrary/localIdentifierMappingsForCloudIdentifiers:",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "localIdentifierMappingsForCloudIdentifiers:"
        }
      ],
      "role": "symbol",
      "title": "localIdentifierMappingsForCloudIdentifiers:",
      "type": "topic",
      "url": "/documentation/photos/phphotolibrary/localidentifiermappingsforcloudidentifiers:"
    },
    "doc://com.apple.photokit/documentation/Photos/PHPhotoLibrary/localIdentifiers(for:)": {
      "abstract": [
        {
          "text": "Retrieves the equivalent local identifiers for the list of iCloud identifiers.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "localIdentifiers"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "for"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)PHCloudIdentifier",
          "text": "PHCloudIdentifier"
        },
        {
          "kind": "text",
          "text": "]) -> ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": "]"
        }
      ],
      "identifier": "doc://com.apple.photokit/documentation/Photos/PHPhotoLibrary/localIdentifiers(for:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "localIdentifiersForCloudIdentifiers:"
        }
      ],
      "role": "symbol",
      "title": "localIdentifiers(for:)",
      "type": "topic",
      "url": "/documentation/photos/phphotolibrary/localidentifiers(for:)"
    },
    "doc://com.externally.resolved.symbol/c:objc(cs)NSObject": {
      "abstract": [
        {
          "text": "The root class of most Objective-C class hierarchies, from which subclasses inherit a basic interface to the runtime system and the ability to behave as Objective-C objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "class "
        },
        {
          "kind": "identifier",
          "text": "NSObject"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSObject",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSObject",
      "type": "topic",
      "url": "/documentation/objectivec/nsobject"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/c:objc(cs)NSObject"
      ],
      "kind": "relationships",
      "title": "Inherits From",
      "type": "inheritsFrom"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Converting-Between-Local-and-iCloud-Identifiers",
      "generated": true,
      "identifiers": [
        "doc://com.apple.photokit/documentation/Photos/PHPhotoLibrary/cloudIdentifierMappingsForLocalIdentifiers:",
        "doc://com.apple.photokit/documentation/Photos/PHPhotoLibrary/localIdentifierMappingsForCloudIdentifiers:",
        "doc://com.apple.photokit/documentation/Photos/PHCloudIdentifier",
        "doc://com.apple.photokit/documentation/Photos/PHCloudIdentifierMapping",
        "doc://com.apple.photokit/documentation/Photos/PHPhotoLibrary/cloudIdentifiers(forLocalIdentifiers:)",
        "doc://com.apple.photokit/documentation/Photos/PHPhotoLibrary/localIdentifiers(for:)",
        "doc://com.apple.photokit/documentation/Photos/PHLocalIdentifierNotFound"
      ],
      "title": "Converting Between Local and iCloud Identifiers"
    }
  ],
  "topicSections": [
    {
      "anchor": "Getting-the-Local-Identifier",
      "identifiers": [
        "doc://com.apple.photokit/documentation/Photos/PHLocalIdentifierMapping/localIdentifier"
      ],
      "title": "Getting the Local Identifier"
    },
    {
      "anchor": "Getting-the-Lookup-Error-Reason",
      "identifiers": [
        "doc://com.apple.photokit/documentation/Photos/PHLocalIdentifierMapping/error"
      ],
      "title": "Getting the Lookup Error Reason"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHPhotoLibrary~1cloudIdentifiers(forLocalIdentifiers:)/title",
          "value": "cloudIdentifiersForLocalIdentifiers:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHPhotoLibrary~1cloudIdentifiers(forLocalIdentifiers:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "cloudIdentifiersForLocalIdentifiers:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHLocalIdentifierNotFound/title",
          "value": "PHLocalIdentifierNotFound"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHLocalIdentifierNotFound/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PHLocalIdentifierNotFound"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHCloudIdentifier/title",
          "value": "PHCloudIdentifier"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHCloudIdentifier/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PHCloudIdentifier"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHCloudIdentifier/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "PHCloudIdentifier"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHPhotoLibrary~1localIdentifiers(for:)/title",
          "value": "localIdentifiersForCloudIdentifiers:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHPhotoLibrary~1localIdentifiers(for:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "localIdentifiersForCloudIdentifiers:"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/photos/phlocalidentifiermapping"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
