{"metadata":{"platforms":[{"unavailable":false,"name":"iOS","deprecated":false,"introducedAt":"16.0","beta":false},{"unavailable":false,"name":"iPadOS","deprecated":false,"introducedAt":"16.0","beta":false},{"unavailable":false,"name":"Mac Catalyst","deprecated":false,"introducedAt":"16.0","beta":false},{"unavailable":false,"name":"visionOS","deprecated":false,"introducedAt":"1.0","beta":false}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"addElements","kind":"identifier"},{"kind":"text","text":"(["},{"kind":"typeIdentifier","text":"PKIdentityElement","preciseIdentifier":"c:objc(cs)PKIdentityElement"},{"kind":"text","text":"], "},{"kind":"externalParam","text":"intentToStore"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"PKIdentityIntentToStore","preciseIdentifier":"c:objc(cs)PKIdentityIntentToStore"},{"kind":"text","text":")"}],"navigatorTitle":[{"kind":"identifier","text":"addElements:withIntentToStore:"}],"role":"symbol","required":true,"roleHeading":"Instance Method","modules":[{"name":"PassKit (Apple Pay and Wallet)"}],"symbolKind":"method","title":"addElements(_:intentToStore:)","externalID":"c:objc(pl)PKIdentityDocumentDescriptor(im)addElements:withIntentToStore:"},"kind":"symbol","seeAlsoSections":[{"anchor":"Adding-an-identity-element","identifiers":["doc://com.apple.passkit/documentation/PassKit/PKIdentityIntentToStore"],"title":"Adding an identity element","generated":true}],"identifier":{"url":"doc://com.apple.passkit/documentation/PassKit/PKIdentityDocumentDescriptor/addElements(_:intentToStore:)","interfaceLanguage":"swift"},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS","iPadOS","Mac Catalyst","visionOS"],"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"addElements"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"elements"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","identifier":"doc://com.apple.passkit/documentation/PassKit/PKIdentityElement","preciseIdentifier":"c:objc(cs)PKIdentityElement","text":"PKIdentityElement"},{"kind":"text","text":"], "},{"kind":"externalParam","text":"intentToStore"},{"text":": ","kind":"text"},{"text":"PKIdentityIntentToStore","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)PKIdentityIntentToStore","identifier":"doc://com.apple.passkit/documentation/PassKit/PKIdentityIntentToStore"},{"text":")","kind":"text"}]}]},{"kind":"parameters","parameters":[{"content":[{"inlineContent":[{"text":"A list of identity elements.","type":"text"}],"type":"paragraph"}],"name":"elements"},{"content":[{"type":"paragraph","inlineContent":[{"text":"An object that defines how long an app or it’s server stores the elements.","type":"text"}]}],"name":"intentToStore"}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"abstract":[{"text":"Adds a list of identity element and defines the way an app, or it’s server, stores the elements.","type":"text"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["/documentation/passkit/pkidentitydocumentdescriptor/addelements(_:intenttostore:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["/documentation/passkit/pkidentitydocumentdescriptor/addelements(_:intenttostore:)"]}],"sections":[],"hierarchy":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.passkit/documentation/PassKit","doc://com.apple.passkit/documentation/PassKit/PKIdentityDocumentDescriptor"]]},"references":{"doc://com.apple.passkit/documentation/PassKit/PKIdentityDocumentDescriptor":{"type":"topic","title":"PKIdentityDocumentDescriptor","navigatorTitle":[{"kind":"identifier","text":"PKIdentityDocumentDescriptor"}],"role":"symbol","kind":"symbol","abstract":[{"type":"text","text":"A type that describes the structure and behavior of an identity document."}],"identifier":"doc://com.apple.passkit/documentation/PassKit/PKIdentityDocumentDescriptor","url":"/documentation/passkit/pkidentitydocumentdescriptor","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"PKIdentityDocumentDescriptor"}]},"doc://com.apple.passkit/documentation/PassKit/PKIdentityDocumentDescriptor/addElements(_:intentToStore:)":{"url":"/documentation/passkit/pkidentitydocumentdescriptor/addelements(_:intenttostore:)","identifier":"doc://com.apple.passkit/documentation/PassKit/PKIdentityDocumentDescriptor/addElements(_:intentToStore:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"addElements","kind":"identifier"},{"text":"([","kind":"text"},{"text":"PKIdentityElement","preciseIdentifier":"c:objc(cs)PKIdentityElement","kind":"typeIdentifier"},{"text":"], ","kind":"text"},{"text":"intentToStore","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)PKIdentityIntentToStore","text":"PKIdentityIntentToStore","kind":"typeIdentifier"},{"text":")","kind":"text"}],"navigatorTitle":[{"text":"addElements:withIntentToStore:","kind":"identifier"}],"role":"symbol","required":true,"abstract":[{"text":"Adds a list of identity element and defines the way an app, or it’s server, stores the elements.","type":"text"}],"type":"topic","kind":"symbol","title":"addElements(_:intentToStore:)"},"doc://com.apple.passkit/documentation/PassKit":{"type":"topic","title":"PassKit (Apple Pay and Wallet)","abstract":[{"text":"Process Apple Pay payments in your app, and create and distribute passes for the Wallet app.","type":"text"}],"identifier":"doc://com.apple.passkit/documentation/PassKit","url":"/documentation/passkit","kind":"symbol","role":"collection"},"doc://com.apple.documentation/documentation/technologies":{"type":"topic","title":"Technologies","abstract":[{"type":"text","text":""}],"identifier":"doc://com.apple.documentation/documentation/technologies","url":"/documentation/technologies","kind":"technologies","role":"overview"},"doc://com.apple.passkit/documentation/PassKit/PKIdentityElement":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"PKIdentityElement","kind":"identifier"}],"abstract":[{"type":"text","text":"An object that represents the elements an app requests from identity documents."}],"role":"symbol","kind":"symbol","identifier":"doc://com.apple.passkit/documentation/PassKit/PKIdentityElement","navigatorTitle":[{"text":"PKIdentityElement","kind":"identifier"}],"type":"topic","url":"/documentation/passkit/pkidentityelement","title":"PKIdentityElement"},"doc://com.apple.passkit/documentation/PassKit/PKIdentityIntentToStore":{"type":"topic","title":"PKIdentityIntentToStore","navigatorTitle":[{"kind":"identifier","text":"PKIdentityIntentToStore"}],"role":"symbol","kind":"symbol","abstract":[{"type":"text","text":"An object that represents your intention to store an identity element or values derived from an identity element."}],"identifier":"doc://com.apple.passkit/documentation/PassKit/PKIdentityIntentToStore","url":"/documentation/passkit/pkidentityintenttostore","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"PKIdentityIntentToStore"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"/identifier/interfaceLanguage","op":"replace"},{"value":[{"introducedAt":"16.0","deprecated":false,"name":"iOS","unavailable":false,"beta":false},{"unavailable":false,"name":"iPadOS","deprecated":false,"introducedAt":"16.0","beta":false},{"unavailable":false,"name":"Mac Catalyst","deprecated":false,"introducedAt":"16.0","beta":false},{"unavailable":false,"name":"visionOS","deprecated":false,"introducedAt":"1.0","beta":false}],"path":"/metadata/platforms","op":"replace"},{"value":"Instance Method","path":"/metadata/roleHeading","op":"replace"},{"value":"addElements:withIntentToStore:","path":"/metadata/title","op":"replace"},{"value":"method","path":"/metadata/symbolKind","op":"replace"},{"value":[{"text":"- ","kind":"text"},{"text":"addElements:withIntentToStore:","kind":"identifier"}],"path":"/metadata/fragments","op":"replace"},{"value":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.passkit/documentation/PassKit","doc://com.apple.passkit/documentation/PassKit/PKIdentityDocumentDescriptor"]]},"path":"/hierarchy","op":"replace"},{"value":null,"path":"/topicSections","op":"add"},{"value":null,"path":"/relationshipsSections","op":"add"},{"value":[{"title":"Adding an identity element","generated":true,"identifiers":["doc://com.apple.passkit/documentation/PassKit/PKIdentityIntentToStore"],"anchor":"Adding-an-identity-element"}],"path":"/seeAlsoSections","op":"replace"},{"value":{"kind":"declarations","declarations":[{"platforms":["iOS","iPadOS","Mac Catalyst","macOS","visionOS","watchOS"],"languages":["occ"],"tokens":[{"text":"- (","kind":"text"},{"text":"void","preciseIdentifier":"c:v","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"addElements:","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","text":"NSArray<PKIdentityElement *>","preciseIdentifier":"c:Q$objc(cs)NSArray"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"elements"},{"kind":"text","text":" "},{"kind":"identifier","text":"withIntentToStore:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"PKIdentityIntentToStore","preciseIdentifier":"c:objc(cs)PKIdentityIntentToStore","identifier":"doc://com.apple.passkit/documentation/PassKit/PKIdentityIntentToStore"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"intentToStore"},{"kind":"text","text":";"}]}]},"path":"/primaryContentSections/0","op":"replace"},{"value":{"kind":"parameters","parameters":[{"content":[{"inlineContent":[{"type":"text","text":"A list of identity elements."}],"type":"paragraph"}],"name":"elements"},{"content":[{"type":"paragraph","inlineContent":[{"text":"An object that defines how long an app or it’s server stores the elements.","type":"text"}]}],"name":"intentToStore"}]},"path":"/primaryContentSections/1","op":"replace"},{"path":"/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKIdentityDocumentDescriptor/title","op":"replace","value":"PKIdentityDocumentDescriptor"},{"path":"/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKIdentityDocumentDescriptor/fragments","op":"replace","value":[{"text":"PKIdentityDocumentDescriptor","kind":"identifier"}]},{"path":"/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKIdentityDocumentDescriptor/navigatorTitle","op":"replace","value":[{"text":"PKIdentityDocumentDescriptor","kind":"identifier"}]},{"path":"/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKIdentityDocumentDescriptor~1addElements(_:intentToStore:)/title","op":"replace","value":"addElements:withIntentToStore:"},{"path":"/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKIdentityDocumentDescriptor~1addElements(_:intentToStore:)/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"text":"addElements:withIntentToStore:","kind":"identifier"}]},{"path":"/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKIdentityElement/title","op":"replace","value":"PKIdentityElement"},{"path":"/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKIdentityElement/fragments","op":"replace","value":[{"kind":"identifier","text":"PKIdentityElement"}]},{"path":"/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKIdentityElement/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"PKIdentityElement"}]},{"path":"/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKIdentityIntentToStore/title","op":"replace","value":"PKIdentityIntentToStore"},{"op":"replace","value":[{"text":"PKIdentityIntentToStore","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKIdentityIntentToStore/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"PKIdentityIntentToStore"}],"path":"/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKIdentityIntentToStore/navigatorTitle"}]}],"legalNotices":{"copyright":"Copyright &copy; 2025 Apple Inc. All rights reserved.","termsOfUse":"https://www.apple.com/legal/internet-services/terms/site.html","privacyPolicy":"https://www.apple.com/privacy/privacy-policy"}}