{"schemaVersion":{"major":0,"minor":3,"patch":0},"variants":[{"paths":["/documentation/opendirectory/odmappings/setrecordmap(_:forstandardrecordtype:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["/documentation/opendirectory/odmappings/setrecordmap(_:forstandardrecordtype:)"],"traits":[{"interfaceLanguage":"occ"}]}],"kind":"symbol","identifier":{"url":"doc://com.apple.opendirectory/documentation/OpenDirectory/ODMappings/setRecordMap(_:forStandardRecordType:)","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.opendirectory/documentation/OpenDirectory","doc://com.apple.opendirectory/documentation/OpenDirectory/ODMappings"]]},"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"setRecordMap"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"map"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)ODRecordMap","identifier":"doc://com.apple.opendirectory/documentation/OpenDirectory/ODRecordMap","kind":"typeIdentifier","text":"ODRecordMap"},{"kind":"text","text":"!, "},{"text":"forStandardRecordType","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"stdType","kind":"internalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier","identifier":"doc://com.externally.resolved.symbol/s:SS"},{"text":"!)","kind":"text"}],"languages":["swift"],"platforms":["macOS"]}],"kind":"declarations"}],"sections":[],"metadata":{"roleHeading":"Instance Method","externalID":"c:objc(cs)ODMappings(im)setRecordMap:forStandardRecordType:","navigatorTitle":[{"text":"setRecordMap:forStandardRecordType:","kind":"identifier"}],"title":"setRecordMap(_:forStandardRecordType:)","modules":[{"name":"Open Directory"}],"symbolKind":"method","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"setRecordMap","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)ODRecordMap","text":"ODRecordMap","kind":"typeIdentifier"},{"text":"!, ","kind":"text"},{"text":"forStandardRecordType","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":"!)","kind":"text"}],"role":"symbol","platforms":[{"deprecated":false,"name":"Mac Catalyst","unavailable":false,"beta":false},{"introducedAt":"10.9","deprecated":false,"name":"macOS","unavailable":false,"beta":false}]},"references":{"doc://com.externally.resolved.symbol/s:SS":{"kind":"symbol","fragments":[{"kind":"attribute","text":"@frozen"},{"kind":"text","text":" "},{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"String"}],"title":"String","url":"/documentation/Swift/String","role":"symbol","type":"topic","abstract":[{"type":"text","text":"A Unicode string value that is a collection of characters."}],"identifier":"doc://com.externally.resolved.symbol/s:SS"},"doc://com.apple.documentation/documentation/technologies":{"identifier":"doc://com.apple.documentation/documentation/technologies","kind":"technologies","title":"Technologies","type":"topic","url":"/documentation/technologies","abstract":[{"type":"text","text":""}],"role":"overview"},"doc://com.externally.resolved.symbol/c:objc(cs)NSString":{"kind":"symbol","fragments":[{"kind":"text","text":"class "},{"kind":"identifier","text":"NSString"}],"title":"NSString","url":"/documentation/foundation/nsstring","role":"symbol","type":"topic","abstract":[{"type":"text","text":"A static, plain-text Unicode string object which you use when you need reference semantics or other Foundation-specific behavior. "}],"identifier":"doc://com.externally.resolved.symbol/c:objc(cs)NSString"},"doc://com.apple.opendirectory/documentation/OpenDirectory/ODMappings/setRecordMap(_:forStandardRecordType:)":{"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"setRecordMap","kind":"identifier"},{"text":"(","kind":"text"},{"text":"ODRecordMap","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)ODRecordMap"},{"text":"!, ","kind":"text"},{"text":"forStandardRecordType","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":"!)","kind":"text"}],"url":"/documentation/opendirectory/odmappings/setrecordmap(_:forstandardrecordtype:)","type":"topic","abstract":[],"kind":"symbol","identifier":"doc://com.apple.opendirectory/documentation/OpenDirectory/ODMappings/setRecordMap(_:forStandardRecordType:)","navigatorTitle":[{"text":"setRecordMap:forStandardRecordType:","kind":"identifier"}],"role":"symbol","title":"setRecordMap(_:forStandardRecordType:)"},"doc://com.apple.opendirectory/documentation/OpenDirectory/ODMappings":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"ODMappings"}],"navigatorTitle":[{"kind":"identifier","text":"ODMappings"}],"identifier":"doc://com.apple.opendirectory/documentation/OpenDirectory/ODMappings","role":"symbol","title":"ODMappings","url":"/documentation/opendirectory/odmappings","kind":"symbol","abstract":[],"type":"topic"},"doc://com.apple.opendirectory/documentation/OpenDirectory/ODRecordMap":{"navigatorTitle":[{"kind":"identifier","text":"ODRecordMap"}],"identifier":"doc://com.apple.opendirectory/documentation/OpenDirectory/ODRecordMap","kind":"symbol","title":"ODRecordMap","role":"symbol","abstract":[],"url":"/documentation/opendirectory/odrecordmap","type":"topic","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ODRecordMap"}]},"doc://com.apple.opendirectory/documentation/OpenDirectory":{"title":"Open Directory","role":"collection","abstract":[{"type":"text","text":"Authenticate users, and search for contact information in Open Directory and LDAP directories."}],"kind":"symbol","type":"topic","identifier":"doc://com.apple.opendirectory/documentation/OpenDirectory","url":"/documentation/opendirectory"}},"variantOverrides":[{"patch":[{"op":"replace","value":"occ","path":"/identifier/interfaceLanguage"},{"op":"replace","value":[{"deprecated":false,"name":"Mac Catalyst","unavailable":false,"beta":false},{"introducedAt":"10.9","deprecated":false,"name":"macOS","unavailable":false,"beta":false}],"path":"/metadata/platforms"},{"op":"replace","value":"Instance Method","path":"/metadata/roleHeading"},{"op":"replace","value":"setRecordMap:forStandardRecordType:","path":"/metadata/title"},{"value":"method","path":"/metadata/symbolKind","op":"replace"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"setRecordMap:forStandardRecordType:"}],"path":"/metadata/fragments","op":"replace"},{"value":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.opendirectory/documentation/OpenDirectory","doc://com.apple.opendirectory/documentation/OpenDirectory/ODMappings"]]},"path":"/hierarchy","op":"replace"},{"value":null,"path":"/topicSections","op":"add"},{"value":null,"path":"/relationshipsSections","op":"add"},{"value":null,"path":"/seeAlsoSections","op":"add"},{"value":{"declarations":[{"platforms":["macOS"],"tokens":[{"kind":"text","text":"- ("},{"preciseIdentifier":"c:v","kind":"typeIdentifier","text":"void"},{"kind":"text","text":") "},{"kind":"identifier","text":"setRecordMap:"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)ODRecordMap","text":"ODRecordMap","kind":"typeIdentifier","identifier":"doc://com.apple.opendirectory/documentation/OpenDirectory/ODRecordMap"},{"text":" *) ","kind":"text"},{"text":"map","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"forStandardRecordType:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSString","text":"NSString","kind":"typeIdentifier","identifier":"doc://com.externally.resolved.symbol/c:objc(cs)NSString"},{"text":" *) ","kind":"text"},{"text":"stdType","kind":"internalParam"},{"text":";","kind":"text"}],"languages":["occ"]}],"kind":"declarations"},"path":"/primaryContentSections/0","op":"replace"},{"value":[{"text":"A static, plain-text Unicode string object.","type":"text"}],"op":"replace","path":"/references/doc:~1~1com.externally.resolved.symbol~1c:objc(cs)NSString/abstract"},{"value":"setRecordMap:forStandardRecordType:","op":"replace","path":"/references/doc:~1~1com.apple.opendirectory~1documentation~1OpenDirectory~1ODMappings~1setRecordMap(_:forStandardRecordType:)/title"},{"value":[{"text":"- ","kind":"text"},{"text":"setRecordMap:forStandardRecordType:","kind":"identifier"}],"op":"replace","path":"/references/doc:~1~1com.apple.opendirectory~1documentation~1OpenDirectory~1ODMappings~1setRecordMap(_:forStandardRecordType:)/fragments"},{"value":"ODMappings","op":"replace","path":"/references/doc:~1~1com.apple.opendirectory~1documentation~1OpenDirectory~1ODMappings/title"},{"value":[{"kind":"identifier","text":"ODMappings"}],"op":"replace","path":"/references/doc:~1~1com.apple.opendirectory~1documentation~1OpenDirectory~1ODMappings/fragments"},{"value":[{"text":"ODMappings","kind":"identifier"}],"op":"replace","path":"/references/doc:~1~1com.apple.opendirectory~1documentation~1OpenDirectory~1ODMappings/navigatorTitle"},{"value":"ODRecordMap","op":"replace","path":"/references/doc:~1~1com.apple.opendirectory~1documentation~1OpenDirectory~1ODRecordMap/title"},{"value":[{"text":"ODRecordMap","kind":"identifier"}],"op":"replace","path":"/references/doc:~1~1com.apple.opendirectory~1documentation~1OpenDirectory~1ODRecordMap/fragments"},{"value":[{"text":"ODRecordMap","kind":"identifier"}],"op":"replace","path":"/references/doc:~1~1com.apple.opendirectory~1documentation~1OpenDirectory~1ODRecordMap/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}],"legalNotices":{"copyright":"Copyright &copy; 2025 Apple Inc. All rights reserved.","termsOfUse":"https://www.apple.com/legal/internet-services/terms/site.html","privacyPolicy":"https://www.apple.com/privacy/privacy-policy"}}