{
  "abstract": [
    {
      "text": "An object that represents the attributes of an overlay you use to recommend an App Clip’s corresponding full app.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.storekit/documentation/StoreKit",
        "doc://com.apple.storekit/documentation/StoreKit/SKOverlay"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.storekit/documentation/StoreKit/SKOverlay/AppClipConfiguration"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "extendedModule": "StoreKit",
    "externalID": "c:objc(cs)SKOverlayAppClipConfiguration",
    "fragments": [
      {
        "kind": "keyword",
        "text": "class"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "AppClipConfiguration"
      }
    ],
    "modules": [
      {
        "name": "StoreKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "AppClipConfiguration"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "14.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "14.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "14.0",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Class",
    "symbolKind": "class",
    "title": "SKOverlay.AppClipConfiguration"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "class"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "AppClipConfiguration"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.storekit/documentation/StoreKit": {
      "abstract": [
        {
          "text": "Support In-App Purchases and interactions with the App Store.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.storekit/documentation/StoreKit",
      "kind": "symbol",
      "role": "collection",
      "title": "StoreKit",
      "type": "topic",
      "url": "/documentation/storekit"
    },
    "doc://com.apple.storekit/documentation/StoreKit/SKOverlay": {
      "abstract": [
        {
          "text": "A class that displays an overlay you can use to recommend another app or an App Clip’s corresponding full app.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SKOverlay"
        }
      ],
      "identifier": "doc://com.apple.storekit/documentation/StoreKit/SKOverlay",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SKOverlay"
        }
      ],
      "role": "symbol",
      "title": "SKOverlay",
      "type": "topic",
      "url": "/documentation/storekit/skoverlay"
    },
    "doc://com.apple.storekit/documentation/StoreKit/SKOverlay/AppClipConfiguration": {
      "abstract": [
        {
          "text": "An object that represents the attributes of an overlay you use to recommend an App Clip’s corresponding full app.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AppClipConfiguration"
        }
      ],
      "identifier": "doc://com.apple.storekit/documentation/StoreKit/SKOverlay/AppClipConfiguration",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AppClipConfiguration"
        }
      ],
      "role": "symbol",
      "title": "SKOverlay.AppClipConfiguration",
      "type": "topic",
      "url": "/documentation/storekit/skoverlay/appclipconfiguration"
    },
    "doc://com.apple.storekit/documentation/StoreKit/SKOverlay/AppClipConfiguration/additionalValue(forKey:)": {
      "abstract": [
        {
          "text": "Returns the object associated with the key.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "additionalValue"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "forKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "keyword",
          "text": "Any"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.storekit/documentation/StoreKit/SKOverlay/AppClipConfiguration/additionalValue(forKey:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "additionalValueForKey:"
        }
      ],
      "role": "symbol",
      "title": "additionalValue(forKey:)",
      "type": "topic",
      "url": "/documentation/storekit/skoverlay/appclipconfiguration/additionalvalue(forkey:)"
    },
    "doc://com.apple.storekit/documentation/StoreKit/SKOverlay/AppClipConfiguration/campaignToken": {
      "abstract": [
        {
          "text": "A token you use to represent an ad campaign and measure its effectiveness.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "campaignToken"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.storekit/documentation/StoreKit/SKOverlay/AppClipConfiguration/campaignToken",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "campaignToken"
        }
      ],
      "role": "symbol",
      "title": "campaignToken",
      "type": "topic",
      "url": "/documentation/storekit/skoverlay/appclipconfiguration/campaigntoken"
    },
    "doc://com.apple.storekit/documentation/StoreKit/SKOverlay/AppClipConfiguration/customProductPageIdentifier": {
      "abstract": [
        {
          "text": "An identifier for a parent app’s custom product page.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "customProductPageIdentifier"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.storekit/documentation/StoreKit/SKOverlay/AppClipConfiguration/customProductPageIdentifier",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "customProductPageIdentifier"
        }
      ],
      "role": "symbol",
      "title": "customProductPageIdentifier",
      "type": "topic",
      "url": "/documentation/storekit/skoverlay/appclipconfiguration/customproductpageidentifier"
    },
    "doc://com.apple.storekit/documentation/StoreKit/SKOverlay/AppClipConfiguration/init(position:)": {
      "abstract": [
        {
          "text": "Creates an object that represents the attributes of an overlay you use to recommend an App Clip’s corresponding app.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "position"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)SKOverlay",
          "text": "SKOverlay"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@SKOverlayPosition",
          "text": "Position"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.storekit/documentation/StoreKit/SKOverlay/AppClipConfiguration/init(position:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "initWithPosition:"
        }
      ],
      "role": "symbol",
      "title": "init(position:)",
      "type": "topic",
      "url": "/documentation/storekit/skoverlay/appclipconfiguration/init(position:)"
    },
    "doc://com.apple.storekit/documentation/StoreKit/SKOverlay/AppClipConfiguration/latestReleaseID": {
      "abstract": [
        {
          "text": "The release ID of the latest version of your parent app as displayed in App Store Connect.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "latestReleaseID"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.storekit/documentation/StoreKit/SKOverlay/AppClipConfiguration/latestReleaseID",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "latestReleaseID"
        }
      ],
      "role": "symbol",
      "title": "latestReleaseID",
      "type": "topic",
      "url": "/documentation/storekit/skoverlay/appclipconfiguration/latestreleaseid"
    },
    "doc://com.apple.storekit/documentation/StoreKit/SKOverlay/AppClipConfiguration/position": {
      "abstract": [
        {
          "text": "The position of the overlay on the screen.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "position"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)SKOverlay",
          "text": "SKOverlay"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@SKOverlayPosition",
          "text": "Position"
        }
      ],
      "identifier": "doc://com.apple.storekit/documentation/StoreKit/SKOverlay/AppClipConfiguration/position",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "position"
        }
      ],
      "role": "symbol",
      "title": "position",
      "type": "topic",
      "url": "/documentation/storekit/skoverlay/appclipconfiguration/position"
    },
    "doc://com.apple.storekit/documentation/StoreKit/SKOverlay/AppClipConfiguration/providerToken": {
      "abstract": [
        {
          "text": "A token that represents the provider of an app promotion campaign, and that you use to measure the campaign’s effectiveness.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "providerToken"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.storekit/documentation/StoreKit/SKOverlay/AppClipConfiguration/providerToken",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "providerToken"
        }
      ],
      "role": "symbol",
      "title": "providerToken",
      "type": "topic",
      "url": "/documentation/storekit/skoverlay/appclipconfiguration/providertoken"
    },
    "doc://com.apple.storekit/documentation/StoreKit/SKOverlay/AppClipConfiguration/setAdditionalValue(_:forKey:)": {
      "abstract": [
        {
          "text": "Sets an additional value for a key, such as a value for measuring the effectiveness of an ad campaign.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "setAdditionalValue"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "keyword",
          "text": "Any"
        },
        {
          "kind": "text",
          "text": "?, "
        },
        {
          "kind": "externalParam",
          "text": "forKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.storekit/documentation/StoreKit/SKOverlay/AppClipConfiguration/setAdditionalValue(_:forKey:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "setAdditionalValue:forKey:"
        }
      ],
      "role": "symbol",
      "title": "setAdditionalValue(_:forKey:)",
      "type": "topic",
      "url": "/documentation/storekit/skoverlay/appclipconfiguration/setadditionalvalue(_:forkey:)"
    },
    "doc://com.apple.storekit/documentation/StoreKit/SKOverlay/AppConfiguration": {
      "abstract": [
        {
          "text": "An object that represents the attributes of an overlay you use to recommend another app on the App Store.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AppConfiguration"
        }
      ],
      "identifier": "doc://com.apple.storekit/documentation/StoreKit/SKOverlay/AppConfiguration",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AppConfiguration"
        }
      ],
      "role": "symbol",
      "title": "SKOverlay.AppConfiguration",
      "type": "topic",
      "url": "/documentation/storekit/skoverlay/appconfiguration"
    },
    "doc://com.apple.storekit/documentation/StoreKit/SKOverlay/Configuration-swift.class": {
      "abstract": [
        {
          "text": "The abstract superclass for all classes that represent an overlay’s attributes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Configuration"
        }
      ],
      "identifier": "doc://com.apple.storekit/documentation/StoreKit/SKOverlay/Configuration-swift.class",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "Configuration"
        }
      ],
      "role": "symbol",
      "title": "SKOverlay.Configuration",
      "type": "topic",
      "url": "/documentation/storekit/skoverlay/configuration-swift.class"
    },
    "doc://com.apple.storekit/documentation/StoreKit/SKOverlay/Position": {
      "abstract": [
        {
          "text": "Constants that identify the position of an overlay on the screen.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Position"
        }
      ],
      "identifier": "doc://com.apple.storekit/documentation/StoreKit/SKOverlay/Position",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "Position"
        }
      ],
      "role": "symbol",
      "title": "SKOverlay.Position",
      "type": "topic",
      "url": "/documentation/storekit/skoverlay/position"
    },
    "doc://com.apple.storekit/documentation/StoreKit/SKOverlay/configuration-swift.property": {
      "abstract": [
        {
          "text": "An overlay’s attributes; for example, its position on the screen.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "configuration"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)SKOverlay",
          "text": "SKOverlay"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)SKOverlayConfiguration",
          "text": "Configuration"
        }
      ],
      "identifier": "doc://com.apple.storekit/documentation/StoreKit/SKOverlay/configuration-swift.property",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "configuration"
        }
      ],
      "role": "symbol",
      "title": "configuration",
      "type": "topic",
      "url": "/documentation/storekit/skoverlay/configuration-swift.property"
    },
    "doc://com.apple.storekit/documentation/StoreKit/SKOverlay/init(configuration:)": {
      "abstract": [
        {
          "text": "Creates an overlay you use to recommend another app on the App Store.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "configuration"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)SKOverlay",
          "text": "SKOverlay"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)SKOverlayConfiguration",
          "text": "Configuration"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.storekit/documentation/StoreKit/SKOverlay/init(configuration:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "initWithConfiguration:"
        }
      ],
      "role": "symbol",
      "title": "init(configuration:)",
      "type": "topic",
      "url": "/documentation/storekit/skoverlay/init(configuration:)"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)NSObject": {
      "abstract": [
        {
          "text": "The group of methods that are fundamental to all Objective-C objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "protocol "
        },
        {
          "kind": "identifier",
          "text": "NSObjectProtocol"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSObject",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSObjectProtocol",
      "type": "topic",
      "url": "/documentation/objectivec/nsobjectprotocol"
    },
    "doc://com.externally.resolved.symbol/s:SH": {
      "abstract": [
        {
          "text": "A type that can be hashed into a `Hasher` to produce an integer hash value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Hashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SQ",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SH",
      "kind": "symbol",
      "role": "symbol",
      "title": "Hashable",
      "type": "topic",
      "url": "/documentation/Swift/Hashable"
    },
    "doc://com.externally.resolved.symbol/s:SQ": {
      "abstract": [
        {
          "text": "A type that can be compared for value equality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SQ",
      "kind": "symbol",
      "role": "symbol",
      "title": "Equatable",
      "type": "topic",
      "url": "/documentation/Swift/Equatable"
    },
    "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP": {
      "abstract": [
        {
          "text": "A type with a customized textual representation.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CustomStringConvertible"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CustomStringConvertible",
      "type": "topic",
      "url": "/documentation/Swift/CustomStringConvertible"
    },
    "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP": {
      "abstract": [
        {
          "text": "A type with a customized textual representation suitable for debugging purposes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CustomDebugStringConvertible"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CustomDebugStringConvertible",
      "type": "topic",
      "url": "/documentation/Swift/CustomDebugStringConvertible"
    },
    "doc://com.externally.resolved.symbol/s:s7CVarArgP": {
      "abstract": [
        {
          "text": "A type whose instances can be encoded, and appropriately passed, as elements of a C `va_list`.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CVarArg"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s7CVarArgP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CVarArg",
      "type": "topic",
      "url": "/documentation/Swift/CVarArg"
    },
    "doc://com.externally.resolved.symbol/s:s8SendableP": {
      "abstract": [
        {
          "text": "A thread-safe type whose values can be shared across arbitrary concurrent contexts without introducing a risk of data races.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Sendable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s8SendableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "Sendable",
      "type": "topic",
      "url": "/documentation/Swift/Sendable"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.apple.storekit/documentation/StoreKit/SKOverlay/Configuration-swift.class"
      ],
      "kind": "relationships",
      "title": "Inherits From",
      "type": "inheritsFrom"
    },
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:s7CVarArgP",
        "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP",
        "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP",
        "doc://com.externally.resolved.symbol/s:SQ",
        "doc://com.externally.resolved.symbol/s:SH",
        "doc://com.externally.resolved.symbol/c:objc(pl)NSObject",
        "doc://com.externally.resolved.symbol/s:s8SendableP"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Creating-an-overlay",
      "generated": true,
      "identifiers": [
        "doc://com.apple.storekit/documentation/StoreKit/SKOverlay/init(configuration:)",
        "doc://com.apple.storekit/documentation/StoreKit/SKOverlay/configuration-swift.property",
        "doc://com.apple.storekit/documentation/StoreKit/SKOverlay/AppConfiguration",
        "doc://com.apple.storekit/documentation/StoreKit/SKOverlay/Configuration-swift.class"
      ],
      "title": "Creating an overlay"
    }
  ],
  "topicSections": [
    {
      "anchor": "Creating-an-App-Clip-Configuration",
      "identifiers": [
        "doc://com.apple.storekit/documentation/StoreKit/SKOverlay/AppClipConfiguration/init(position:)",
        "doc://com.apple.storekit/documentation/StoreKit/SKOverlay/AppClipConfiguration/position",
        "doc://com.apple.storekit/documentation/StoreKit/SKOverlay/Position"
      ],
      "title": "Creating an App Clip Configuration"
    },
    {
      "anchor": "Verifying-Advertising-Campaigns",
      "identifiers": [
        "doc://com.apple.storekit/documentation/StoreKit/SKOverlay/AppClipConfiguration/campaignToken",
        "doc://com.apple.storekit/documentation/StoreKit/SKOverlay/AppClipConfiguration/providerToken",
        "doc://com.apple.storekit/documentation/StoreKit/SKOverlay/AppClipConfiguration/setAdditionalValue(_:forKey:)",
        "doc://com.apple.storekit/documentation/StoreKit/SKOverlay/AppClipConfiguration/additionalValue(forKey:)"
      ],
      "title": "Verifying Advertising Campaigns"
    },
    {
      "anchor": "Promoting-the-Latest-App-Version",
      "identifiers": [
        "doc://com.apple.storekit/documentation/StoreKit/SKOverlay/AppClipConfiguration/latestReleaseID"
      ],
      "title": "Promoting the Latest App Version"
    },
    {
      "anchor": "Advertising-Another-App",
      "identifiers": [
        "doc://com.apple.storekit/documentation/StoreKit/SKOverlay/AppClipConfiguration/customProductPageIdentifier"
      ],
      "title": "Advertising Another App"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "14.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "14.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "14.0",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Class"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "SKOverlayAppClipConfiguration"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "class"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SKOverlayAppClipConfiguration"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SKOverlayAppClipConfiguration"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.storekit/documentation/StoreKit"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Creating-an-App-Clip-Configuration",
              "identifiers": [
                "doc://com.apple.storekit/documentation/StoreKit/SKOverlay/AppClipConfiguration/init(position:)",
                "doc://com.apple.storekit/documentation/StoreKit/SKOverlay/AppClipConfiguration/position",
                "doc://com.apple.storekit/documentation/StoreKit/SKOverlay/Position"
              ],
              "title": "Creating an App Clip Configuration"
            },
            {
              "anchor": "Verifying-Advertising-Campaigns",
              "identifiers": [
                "doc://com.apple.storekit/documentation/StoreKit/SKOverlay/AppClipConfiguration/campaignToken",
                "doc://com.apple.storekit/documentation/StoreKit/SKOverlay/AppClipConfiguration/providerToken",
                "doc://com.apple.storekit/documentation/StoreKit/SKOverlay/AppClipConfiguration/setAdditionalValue(_:forKey:)",
                "doc://com.apple.storekit/documentation/StoreKit/SKOverlay/AppClipConfiguration/additionalValue(forKey:)"
              ],
              "title": "Verifying Advertising Campaigns"
            },
            {
              "anchor": "Promoting-the-Latest-App-Version",
              "identifiers": [
                "doc://com.apple.storekit/documentation/StoreKit/SKOverlay/AppClipConfiguration/latestReleaseID"
              ],
              "title": "Promoting the Latest App Version"
            },
            {
              "anchor": "Advertising-Another-App",
              "identifiers": [
                "doc://com.apple.storekit/documentation/StoreKit/SKOverlay/AppClipConfiguration/customProductPageIdentifier"
              ],
              "title": "Advertising Another App"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": [
            {
              "identifiers": [
                "doc://com.apple.storekit/documentation/StoreKit/SKOverlay/Configuration-swift.class"
              ],
              "kind": "relationships",
              "title": "Inherits From",
              "type": "inheritsFrom"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Creating-an-overlay",
              "generated": true,
              "identifiers": [
                "doc://com.apple.storekit/documentation/StoreKit/SKOverlay/init(configuration:)",
                "doc://com.apple.storekit/documentation/StoreKit/SKOverlay/configuration-swift.property",
                "doc://com.apple.storekit/documentation/StoreKit/SKOverlay/AppConfiguration",
                "doc://com.apple.storekit/documentation/StoreKit/SKOverlay/Configuration-swift.class"
              ],
              "title": "Creating an overlay"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "@interface"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "SKOverlayAppClipConfiguration"
                  },
                  {
                    "kind": "text",
                    "text": " : "
                  },
                  {
                    "identifier": "doc://com.apple.storekit/documentation/StoreKit/SKOverlay/Configuration-swift.class",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(cs)SKOverlayConfiguration",
                    "text": "SKOverlayConfiguration"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.storekit~1documentation~1StoreKit~1SKOverlay/title",
          "value": "SKOverlay"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.storekit~1documentation~1StoreKit~1SKOverlay/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SKOverlay"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.storekit~1documentation~1StoreKit~1SKOverlay/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SKOverlay"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.storekit~1documentation~1StoreKit~1SKOverlay~1AppClipConfiguration~1providerToken/title",
          "value": "providerToken"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.storekit~1documentation~1StoreKit~1SKOverlay~1AppClipConfiguration~1providerToken/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "providerToken"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.storekit~1documentation~1StoreKit~1SKOverlay~1Configuration-swift.class/title",
          "value": "SKOverlayConfiguration"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.storekit~1documentation~1StoreKit~1SKOverlay~1Configuration-swift.class/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SKOverlayConfiguration"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.storekit~1documentation~1StoreKit~1SKOverlay~1Configuration-swift.class/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SKOverlayConfiguration"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.storekit~1documentation~1StoreKit~1SKOverlay~1AppClipConfiguration~1customProductPageIdentifier/title",
          "value": "customProductPageIdentifier"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.storekit~1documentation~1StoreKit~1SKOverlay~1AppClipConfiguration~1customProductPageIdentifier/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "customProductPageIdentifier"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.storekit~1documentation~1StoreKit~1SKOverlay~1AppClipConfiguration~1campaignToken/title",
          "value": "campaignToken"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.storekit~1documentation~1StoreKit~1SKOverlay~1AppClipConfiguration~1campaignToken/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "campaignToken"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.storekit~1documentation~1StoreKit~1SKOverlay~1AppClipConfiguration~1additionalValue(forKey:)/title",
          "value": "additionalValueForKey:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.storekit~1documentation~1StoreKit~1SKOverlay~1AppClipConfiguration~1additionalValue(forKey:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "additionalValueForKey:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.storekit~1documentation~1StoreKit~1SKOverlay~1AppClipConfiguration~1latestReleaseID/title",
          "value": "latestReleaseID"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.storekit~1documentation~1StoreKit~1SKOverlay~1AppClipConfiguration~1latestReleaseID/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "latestReleaseID"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.storekit~1documentation~1StoreKit~1SKOverlay~1Position/title",
          "value": "SKOverlayPosition"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.storekit~1documentation~1StoreKit~1SKOverlay~1Position/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SKOverlayPosition"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.storekit~1documentation~1StoreKit~1SKOverlay~1Position/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SKOverlayPosition"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.storekit~1documentation~1StoreKit~1SKOverlay~1AppClipConfiguration~1position/title",
          "value": "position"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.storekit~1documentation~1StoreKit~1SKOverlay~1AppClipConfiguration~1position/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "position"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.storekit~1documentation~1StoreKit~1SKOverlay~1AppClipConfiguration/title",
          "value": "SKOverlayAppClipConfiguration"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.storekit~1documentation~1StoreKit~1SKOverlay~1AppClipConfiguration/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SKOverlayAppClipConfiguration"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.storekit~1documentation~1StoreKit~1SKOverlay~1AppClipConfiguration/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SKOverlayAppClipConfiguration"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:objc(pl)NSObject/title",
          "value": "NSObject"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.storekit~1documentation~1StoreKit~1SKOverlay~1AppClipConfiguration~1setAdditionalValue(_:forKey:)/title",
          "value": "setAdditionalValue:forKey:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.storekit~1documentation~1StoreKit~1SKOverlay~1AppClipConfiguration~1setAdditionalValue(_:forKey:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "setAdditionalValue:forKey:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.storekit~1documentation~1StoreKit~1SKOverlay~1configuration-swift.property/title",
          "value": "configuration"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.storekit~1documentation~1StoreKit~1SKOverlay~1configuration-swift.property/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "configuration"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.storekit~1documentation~1StoreKit~1SKOverlay~1AppClipConfiguration~1init(position:)/title",
          "value": "initWithPosition:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.storekit~1documentation~1StoreKit~1SKOverlay~1AppClipConfiguration~1init(position:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "initWithPosition:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.storekit~1documentation~1StoreKit~1SKOverlay~1init(configuration:)/title",
          "value": "initWithConfiguration:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.storekit~1documentation~1StoreKit~1SKOverlay~1init(configuration:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "initWithConfiguration:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.storekit~1documentation~1StoreKit~1SKOverlay~1AppConfiguration/title",
          "value": "SKOverlayAppConfiguration"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.storekit~1documentation~1StoreKit~1SKOverlay~1AppConfiguration/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SKOverlayAppConfiguration"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.storekit~1documentation~1StoreKit~1SKOverlay~1AppConfiguration/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SKOverlayAppConfiguration"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/storekit/skoverlay/appclipconfiguration"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/storekit/skoverlay/appclipconfiguration"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
