{"hierarchy":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.uikit/documentation/UIKit","doc://com.apple.uikit/documentation/UIKit/UISearchBarDelegate"]]},"seeAlsoSections":[{"generated":true,"title":"Managing the search text","anchor":"Managing-the-search-text","identifiers":["doc://com.apple.uikit/documentation/UIKit/UISearchBarDelegate/searchBar(_:textDidChange:)","doc://com.apple.uikit/documentation/UIKit/UISearchBarDelegate/searchBar(_:shouldChangeTextIn:replacementText:)","doc://com.apple.uikit/documentation/UIKit/UISearchBarDelegate/searchBarShouldBeginEditing(_:)","doc://com.apple.uikit/documentation/UIKit/UISearchBarDelegate/searchBarShouldEndEditing(_:)","doc://com.apple.uikit/documentation/UIKit/UISearchBarDelegate/searchBarTextDidEndEditing(_:)"]}],"metadata":{"platforms":[{"unavailable":false,"name":"iOS","introducedAt":"2.0","deprecated":false,"beta":false},{"unavailable":false,"name":"iPadOS","introducedAt":"2.0","deprecated":false,"beta":false},{"unavailable":false,"name":"Mac Catalyst","introducedAt":"13.1","deprecated":false,"beta":false},{"unavailable":false,"name":"tvOS","deprecated":false,"beta":false},{"unavailable":false,"name":"visionOS","introducedAt":"1.0","deprecated":false,"beta":false}],"modules":[{"name":"UIKit"}],"role":"symbol","title":"searchBarTextDidBeginEditing(_:)","navigatorTitle":[{"kind":"identifier","text":"searchBarTextDidBeginEditing:"}],"externalID":"c:objc(pl)UISearchBarDelegate(im)searchBarTextDidBeginEditing:","roleHeading":"Instance Method","symbolKind":"method","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"searchBarTextDidBeginEditing"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UISearchBar","text":"UISearchBar"},{"kind":"text","text":")"}]},"abstract":[{"type":"text","text":"Tells the delegate when the user begins editing the search text."}],"kind":"symbol","schemaVersion":{"major":0,"minor":3,"patch":0},"primaryContentSections":[{"declarations":[{"platforms":["iOS","iPadOS","Mac Catalyst","tvOS","visionOS"],"tokens":[{"text":"@","kind":"attribute"},{"preciseIdentifier":"s:ScM","text":"MainActor","kind":"attribute","identifier":"doc://com.externally.resolved.symbol/s:ScM"},{"text":" ","kind":"text"},{"text":"optional","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"searchBarTextDidBeginEditing","kind":"identifier"},{"text":"(","kind":"text"},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"searchBar","kind":"internalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)UISearchBar","text":"UISearchBar","kind":"typeIdentifier","identifier":"doc://com.apple.uikit/documentation/UIKit/UISearchBar"},{"text":")","kind":"text"}],"languages":["swift"]}],"kind":"declarations"},{"parameters":[{"name":"searchBar","content":[{"inlineContent":[{"text":"The search bar that is being edited.","type":"text"}],"type":"paragraph"}]}],"kind":"parameters"}],"sections":[],"variants":[{"paths":["/documentation/uikit/uisearchbardelegate/searchbartextdidbeginediting(_:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["/documentation/uikit/uisearchbardelegate/searchbartextdidbeginediting(_:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc://com.apple.uikit/documentation/UIKit/UISearchBarDelegate/searchBarTextDidBeginEditing(_:)","interfaceLanguage":"swift"},"references":{"doc://com.apple.uikit/documentation/UIKit/UISearchBar":{"abstract":[{"text":"A specialized view for receiving search-related information from the user.","type":"text"}],"title":"UISearchBar","url":"/documentation/uikit/uisearchbar","navigatorTitle":[{"text":"UISearchBar","kind":"identifier"}],"kind":"symbol","type":"topic","role":"symbol","identifier":"doc://com.apple.uikit/documentation/UIKit/UISearchBar","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"UISearchBar","kind":"identifier"}]},"doc://com.apple.documentation/documentation/technologies":{"role":"overview","url":"/documentation/technologies","title":"Technologies","identifier":"doc://com.apple.documentation/documentation/technologies","abstract":[{"text":"","type":"text"}],"kind":"technologies","type":"topic"},"doc://com.apple.uikit/documentation/UIKit/UISearchBarDelegate/searchBarTextDidBeginEditing(_:)":{"abstract":[{"text":"Tells the delegate when the user begins editing the search text.","type":"text"}],"kind":"symbol","identifier":"doc://com.apple.uikit/documentation/UIKit/UISearchBarDelegate/searchBarTextDidBeginEditing(_:)","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"searchBarTextDidBeginEditing","kind":"identifier"},{"text":"(","kind":"text"},{"text":"UISearchBar","preciseIdentifier":"c:objc(cs)UISearchBar","kind":"typeIdentifier"},{"text":")","kind":"text"}],"title":"searchBarTextDidBeginEditing(_:)","role":"symbol","navigatorTitle":[{"text":"searchBarTextDidBeginEditing:","kind":"identifier"}],"type":"topic","url":"/documentation/uikit/uisearchbardelegate/searchbartextdidbeginediting(_:)"},"doc://com.apple.uikit/documentation/UIKit/UISearchBarDelegate/searchBarShouldBeginEditing(_:)":{"title":"searchBarShouldBeginEditing(_:)","kind":"symbol","role":"symbol","identifier":"doc://com.apple.uikit/documentation/UIKit/UISearchBarDelegate/searchBarShouldBeginEditing(_:)","abstract":[{"text":"Asks the delegate if editing should begin in the specified search bar.","type":"text"}],"type":"topic","navigatorTitle":[{"text":"searchBarShouldBeginEditing:","kind":"identifier"}],"url":"/documentation/uikit/uisearchbardelegate/searchbarshouldbeginediting(_:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"searchBarShouldBeginEditing","kind":"identifier"},{"text":"(","kind":"text"},{"text":"UISearchBar","preciseIdentifier":"c:objc(cs)UISearchBar","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"}]},"doc://com.externally.resolved.symbol/s:ScM":{"abstract":[{"text":"A singleton actor whose executor is equivalent to the main dispatch queue.","type":"text"}],"url":"/documentation/Swift/MainActor","identifier":"doc://com.externally.resolved.symbol/s:ScM","title":"MainActor","fragments":[{"text":"@globalActor","kind":"attribute"},{"text":" ","kind":"text"},{"text":"final","kind":"keyword"},{"text":" ","kind":"text"},{"text":"actor","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MainActor","kind":"identifier"}],"type":"topic","kind":"symbol","role":"symbol"},"doc://com.apple.uikit/documentation/UIKit/UISearchBarDelegate/searchBarShouldEndEditing(_:)":{"abstract":[{"type":"text","text":"Asks the delegate if editing should stop in the specified search bar."}],"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"searchBarShouldEndEditing"},{"kind":"text","text":"("},{"preciseIdentifier":"c:objc(cs)UISearchBar","kind":"typeIdentifier","text":"UISearchBar"},{"kind":"text","text":") -> "},{"preciseIdentifier":"s:Sb","kind":"typeIdentifier","text":"Bool"}],"identifier":"doc://com.apple.uikit/documentation/UIKit/UISearchBarDelegate/searchBarShouldEndEditing(_:)","type":"topic","title":"searchBarShouldEndEditing(_:)","kind":"symbol","role":"symbol","url":"/documentation/uikit/uisearchbardelegate/searchbarshouldendediting(_:)","navigatorTitle":[{"kind":"identifier","text":"searchBarShouldEndEditing:"}]},"doc://com.apple.uikit/documentation/UIKit/UISearchBarDelegate/searchBar(_:textDidChange:)":{"abstract":[{"text":"Tells the delegate that the user changed the search text.","type":"text"}],"kind":"symbol","identifier":"doc://com.apple.uikit/documentation/UIKit/UISearchBarDelegate/searchBar(_:textDidChange:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"searchBar","kind":"identifier"},{"text":"(","kind":"text"},{"text":"UISearchBar","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UISearchBar"},{"text":", ","kind":"text"},{"text":"textDidChange","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":")","kind":"text"}],"title":"searchBar(_:textDidChange:)","role":"symbol","navigatorTitle":[{"text":"searchBar:textDidChange:","kind":"identifier"}],"type":"topic","url":"/documentation/uikit/uisearchbardelegate/searchbar(_:textdidchange:)"},"doc://com.apple.uikit/documentation/UIKit/UISearchBarDelegate/searchBar(_:shouldChangeTextIn:replacementText:)":{"title":"searchBar(_:shouldChangeTextIn:replacementText:)","kind":"symbol","role":"symbol","identifier":"doc://com.apple.uikit/documentation/UIKit/UISearchBarDelegate/searchBar(_:shouldChangeTextIn:replacementText:)","abstract":[{"text":"Ask the delegate if text in a specified range should be replaced with given text.","type":"text"}],"type":"topic","navigatorTitle":[{"kind":"identifier","text":"searchBar:shouldChangeTextInRange:replacementText:"}],"url":"/documentation/uikit/uisearchbardelegate/searchbar(_:shouldchangetextin:replacementtext:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"searchBar"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UISearchBar","text":"UISearchBar"},{"kind":"text","text":", "},{"kind":"externalParam","text":"shouldChangeTextIn"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NSRange"},{"kind":"text","text":", "},{"kind":"externalParam","text":"replacementText"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"}]},"doc://com.apple.uikit/documentation/UIKit":{"kind":"symbol","role":"collection","title":"UIKit","identifier":"doc://com.apple.uikit/documentation/UIKit","url":"/documentation/uikit","abstract":[{"type":"text","text":"Construct and manage a graphical, event-driven user interface for your iOS, iPadOS, or tvOS app."}],"type":"topic"},"doc://com.apple.uikit/documentation/UIKit/UISearchBarDelegate":{"role":"symbol","abstract":[{"type":"text","text":"A collection of optional methods that you implement to make a search bar control functional."}],"navigatorTitle":[{"kind":"identifier","text":"UISearchBarDelegate"}],"type":"topic","url":"/documentation/uikit/uisearchbardelegate","kind":"symbol","identifier":"doc://com.apple.uikit/documentation/UIKit/UISearchBarDelegate","fragments":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"UISearchBarDelegate"}],"title":"UISearchBarDelegate"},"doc://com.apple.uikit/documentation/UIKit/UISearchBarDelegate/searchBarTextDidEndEditing(_:)":{"title":"searchBarTextDidEndEditing(_:)","type":"topic","navigatorTitle":[{"kind":"identifier","text":"searchBarTextDidEndEditing:"}],"abstract":[{"type":"text","text":"Tells the delegate that the user finished editing the search text."}],"identifier":"doc://com.apple.uikit/documentation/UIKit/UISearchBarDelegate/searchBarTextDidEndEditing(_:)","role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"searchBarTextDidEndEditing"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UISearchBar","text":"UISearchBar"},{"kind":"text","text":")"}],"kind":"symbol","url":"/documentation/uikit/uisearchbardelegate/searchbartextdidendediting(_:)"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"/identifier/interfaceLanguage","op":"replace","value":"occ"},{"path":"/metadata/platforms","op":"replace","value":[{"deprecated":false,"name":"iOS","unavailable":false,"beta":false},{"deprecated":false,"name":"iPadOS","unavailable":false,"beta":false},{"deprecated":false,"name":"Mac Catalyst","unavailable":false,"beta":false},{"deprecated":false,"name":"tvOS","unavailable":false,"beta":false},{"deprecated":false,"name":"visionOS","unavailable":false,"beta":false}]},{"path":"/metadata/roleHeading","op":"replace","value":"Instance Method"},{"path":"/metadata/title","op":"replace","value":"searchBarTextDidBeginEditing:"},{"path":"/metadata/symbolKind","op":"replace","value":"method"},{"path":"/metadata/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"text":"searchBarTextDidBeginEditing:","kind":"identifier"}]},{"path":"/hierarchy","op":"replace","value":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.uikit/documentation/UIKit","doc://com.apple.uikit/documentation/UIKit/UISearchBarDelegate"]]}},{"value":null,"op":"add","path":"/topicSections"},{"value":null,"op":"add","path":"/relationshipsSections"},{"value":[{"generated":true,"anchor":"Managing-the-search-text","title":"Managing the search text","identifiers":["doc://com.apple.uikit/documentation/UIKit/UISearchBarDelegate/searchBar(_:textDidChange:)","doc://com.apple.uikit/documentation/UIKit/UISearchBarDelegate/searchBar(_:shouldChangeTextIn:replacementText:)","doc://com.apple.uikit/documentation/UIKit/UISearchBarDelegate/searchBarShouldBeginEditing(_:)","doc://com.apple.uikit/documentation/UIKit/UISearchBarDelegate/searchBarShouldEndEditing(_:)","doc://com.apple.uikit/documentation/UIKit/UISearchBarDelegate/searchBarTextDidEndEditing(_:)"]}],"op":"replace","path":"/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS","iPadOS","Mac Catalyst","tvOS","visionOS"],"tokens":[{"text":"- (","kind":"text"},{"text":"void","kind":"typeIdentifier","preciseIdentifier":"c:v"},{"text":") ","kind":"text"},{"text":"searchBarTextDidBeginEditing:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"UISearchBar","kind":"typeIdentifier","identifier":"doc://com.apple.uikit/documentation/UIKit/UISearchBar","preciseIdentifier":"c:objc(cs)UISearchBar"},{"text":" *) ","kind":"text"},{"text":"searchBar","kind":"internalParam"},{"text":";","kind":"text"}]}]},"op":"replace","path":"/primaryContentSections/0"},{"path":"/primaryContentSections/1","value":{"kind":"parameters","parameters":[{"name":"searchBar","content":[{"type":"paragraph","inlineContent":[{"text":"The search bar that is being edited.","type":"text"}]}]}]},"op":"replace"},{"value":"UISearchBar","op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UISearchBar/title"},{"value":[{"text":"UISearchBar","kind":"identifier"}],"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UISearchBar/fragments"},{"value":[{"text":"UISearchBar","kind":"identifier"}],"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UISearchBar/navigatorTitle"},{"value":"searchBarTextDidBeginEditing:","op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UISearchBarDelegate~1searchBarTextDidBeginEditing(_:)/title"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"searchBarTextDidBeginEditing:"}],"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UISearchBarDelegate~1searchBarTextDidBeginEditing(_:)/fragments"},{"value":"searchBarShouldBeginEditing:","op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UISearchBarDelegate~1searchBarShouldBeginEditing(_:)/title"},{"value":[{"text":"- ","kind":"text"},{"text":"searchBarShouldBeginEditing:","kind":"identifier"}],"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UISearchBarDelegate~1searchBarShouldBeginEditing(_:)/fragments"},{"value":"searchBarShouldEndEditing:","op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UISearchBarDelegate~1searchBarShouldEndEditing(_:)/title"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"searchBarShouldEndEditing:"}],"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UISearchBarDelegate~1searchBarShouldEndEditing(_:)/fragments"},{"value":"searchBar:textDidChange:","op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UISearchBarDelegate~1searchBar(_:textDidChange:)/title"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"searchBar:textDidChange:"}],"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UISearchBarDelegate~1searchBar(_:textDidChange:)/fragments"},{"value":"searchBar:shouldChangeTextInRange:replacementText:","op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UISearchBarDelegate~1searchBar(_:shouldChangeTextIn:replacementText:)/title"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"searchBar:shouldChangeTextInRange:replacementText:"}],"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UISearchBarDelegate~1searchBar(_:shouldChangeTextIn:replacementText:)/fragments"},{"value":"UISearchBarDelegate","op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UISearchBarDelegate/title"},{"value":[{"text":"UISearchBarDelegate","kind":"identifier"}],"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UISearchBarDelegate/fragments"},{"value":[{"kind":"identifier","text":"UISearchBarDelegate"}],"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UISearchBarDelegate/navigatorTitle"},{"value":"searchBarTextDidEndEditing:","op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UISearchBarDelegate~1searchBarTextDidEndEditing(_:)/title"},{"value":[{"kind":"text","text":"- "},{"text":"searchBarTextDidEndEditing:","kind":"identifier"}],"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UISearchBarDelegate~1searchBarTextDidEndEditing(_:)/fragments"}]}],"legalNotices":{"copyright":"Copyright &copy; 2025 Apple Inc. All rights reserved.","termsOfUse":"https://www.apple.com/legal/internet-services/terms/site.html","privacyPolicy":"https://www.apple.com/privacy/privacy-policy"}}