{"metadata":{"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"searchBarShouldBeginEditing:"}],"modules":[{"name":"UIKit"}],"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"searchBarShouldBeginEditing"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"UISearchBar","preciseIdentifier":"c:objc(cs)UISearchBar"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"symbolKind":"method","roleHeading":"Instance Method","platforms":[{"name":"iOS","deprecated":false,"introducedAt":"2.0","unavailable":false,"beta":false},{"name":"iPadOS","deprecated":false,"introducedAt":"2.0","unavailable":false,"beta":false},{"name":"Mac Catalyst","deprecated":false,"introducedAt":"13.1","unavailable":false,"beta":false},{"name":"tvOS","deprecated":false,"unavailable":false,"beta":false},{"name":"visionOS","deprecated":false,"introducedAt":"1.0","unavailable":false,"beta":false}],"title":"searchBarShouldBeginEditing(_:)","externalID":"c:objc(pl)UISearchBarDelegate(im)searchBarShouldBeginEditing:"},"identifier":{"url":"doc://com.apple.uikit/documentation/UIKit/UISearchBarDelegate/searchBarShouldBeginEditing(_:)","interfaceLanguage":"swift"},"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"attribute","text":"@"},{"kind":"attribute","text":"MainActor","preciseIdentifier":"s:ScM","identifier":"doc://com.externally.resolved.symbol/s:ScM"},{"kind":"text","text":" "},{"kind":"keyword","text":"optional"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"searchBarShouldBeginEditing"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"searchBar"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UISearchBar","preciseIdentifier":"c:objc(cs)UISearchBar","identifier":"doc://com.apple.uikit/documentation/UIKit/UISearchBar"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb","identifier":"doc://com.externally.resolved.symbol/s:Sb"}],"languages":["swift"],"platforms":["iOS","iPadOS","Mac Catalyst","tvOS","visionOS"]}],"kind":"declarations"},{"parameters":[{"name":"searchBar","content":[{"inlineContent":[{"text":"The search bar that is being edited.","type":"text"}],"type":"paragraph"}]}],"kind":"parameters"},{"content":[{"anchor":"return-value","level":2,"text":"Return Value","type":"heading"},{"inlineContent":[{"type":"text","text":""},{"isActive":true,"identifier":"doc://com.apple.documentation/documentation/swift/true","type":"reference"},{"type":"text","text":" if an editing session should be initiated, otherwise, "},{"isActive":true,"identifier":"doc://com.apple.documentation/documentation/swift/false","type":"reference"},{"type":"text","text":"."}],"type":"paragraph"}],"kind":"content"}],"sections":[],"hierarchy":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.uikit/documentation/UIKit","doc://com.apple.uikit/documentation/UIKit/UISearchBarDelegate"]]},"seeAlsoSections":[{"anchor":"Managing-the-search-text","title":"Managing the search text","identifiers":["doc://com.apple.uikit/documentation/UIKit/UISearchBarDelegate/searchBar(_:textDidChange:)","doc://com.apple.uikit/documentation/UIKit/UISearchBarDelegate/searchBar(_:shouldChangeTextIn:replacementText:)","doc://com.apple.uikit/documentation/UIKit/UISearchBarDelegate/searchBarTextDidBeginEditing(_:)","doc://com.apple.uikit/documentation/UIKit/UISearchBarDelegate/searchBarShouldEndEditing(_:)","doc://com.apple.uikit/documentation/UIKit/UISearchBarDelegate/searchBarTextDidEndEditing(_:)"],"generated":true}],"schemaVersion":{"major":0,"minor":3,"patch":0},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["/documentation/uikit/uisearchbardelegate/searchbarshouldbeginediting(_:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["/documentation/uikit/uisearchbardelegate/searchbarshouldbeginediting(_:)"]}],"kind":"symbol","abstract":[{"text":"Asks the delegate if editing should begin in the specified search bar.","type":"text"}],"references":{"doc://com.externally.resolved.symbol/s:ScM":{"abstract":[{"text":"A singleton actor whose executor is equivalent to the main dispatch queue.","type":"text"}],"url":"/documentation/Swift/MainActor","identifier":"doc://com.externally.resolved.symbol/s:ScM","title":"MainActor","fragments":[{"text":"@globalActor","kind":"attribute"},{"text":" ","kind":"text"},{"text":"final","kind":"keyword"},{"text":" ","kind":"text"},{"text":"actor","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MainActor","kind":"identifier"}],"type":"topic","kind":"symbol","role":"symbol"},"doc://com.externally.resolved.symbol/s:Sb":{"role":"symbol","abstract":[{"type":"text","text":"A value type whose instances are either `true` or `false`."}],"type":"topic","url":"/documentation/Swift/Bool","kind":"symbol","identifier":"doc://com.externally.resolved.symbol/s:Sb","fragments":[{"kind":"attribute","text":"@frozen"},{"kind":"text","text":" "},{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"Bool"}],"title":"Bool"},"doc://com.apple.uikit/documentation/UIKit":{"kind":"symbol","role":"collection","title":"UIKit","identifier":"doc://com.apple.uikit/documentation/UIKit","url":"/documentation/uikit","abstract":[{"type":"text","text":"Construct and manage a graphical, event-driven user interface for your iOS, iPadOS, or tvOS app."}],"type":"topic"},"doc://com.apple.documentation/documentation/swift/false":{"role":"symbol","url":"/documentation/swift/false","title":"false","identifier":"doc://com.apple.documentation/documentation/swift/false","abstract":[{"text":"A false value.","type":"text"}],"kind":"symbol","type":"topic"},"doc://com.externally.resolved.symbol/c:@T@BOOL":{"abstract":[{"text":"Type to represent a Boolean value.","type":"text"}],"identifier":"doc://com.externally.resolved.symbol/c:@T@BOOL","role":"symbol","url":"/documentation/objectivec/bool","kind":"symbol","type":"topic","title":"BOOL"},"doc://com.apple.uikit/documentation/UIKit/UISearchBarDelegate/searchBar(_:shouldChangeTextIn:replacementText:)":{"title":"searchBar(_:shouldChangeTextIn:replacementText:)","kind":"symbol","role":"symbol","identifier":"doc://com.apple.uikit/documentation/UIKit/UISearchBarDelegate/searchBar(_:shouldChangeTextIn:replacementText:)","abstract":[{"text":"Ask the delegate if text in a specified range should be replaced with given text.","type":"text"}],"type":"topic","navigatorTitle":[{"kind":"identifier","text":"searchBar:shouldChangeTextInRange:replacementText:"}],"url":"/documentation/uikit/uisearchbardelegate/searchbar(_:shouldchangetextin:replacementtext:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"searchBar"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UISearchBar","text":"UISearchBar"},{"kind":"text","text":", "},{"kind":"externalParam","text":"shouldChangeTextIn"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NSRange"},{"kind":"text","text":", "},{"kind":"externalParam","text":"replacementText"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"}]},"doc://com.apple.uikit/documentation/UIKit/UISearchBarDelegate/searchBarShouldBeginEditing(_:)":{"title":"searchBarShouldBeginEditing(_:)","kind":"symbol","role":"symbol","identifier":"doc://com.apple.uikit/documentation/UIKit/UISearchBarDelegate/searchBarShouldBeginEditing(_:)","abstract":[{"text":"Asks the delegate if editing should begin in the specified search bar.","type":"text"}],"type":"topic","navigatorTitle":[{"text":"searchBarShouldBeginEditing:","kind":"identifier"}],"url":"/documentation/uikit/uisearchbardelegate/searchbarshouldbeginediting(_:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"searchBarShouldBeginEditing","kind":"identifier"},{"text":"(","kind":"text"},{"text":"UISearchBar","preciseIdentifier":"c:objc(cs)UISearchBar","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"}]},"doc://com.apple.uikit/documentation/UIKit/UISearchBarDelegate/searchBarTextDidEndEditing(_:)":{"title":"searchBarTextDidEndEditing(_:)","type":"topic","navigatorTitle":[{"kind":"identifier","text":"searchBarTextDidEndEditing:"}],"abstract":[{"type":"text","text":"Tells the delegate that the user finished editing the search text."}],"identifier":"doc://com.apple.uikit/documentation/UIKit/UISearchBarDelegate/searchBarTextDidEndEditing(_:)","role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"searchBarTextDidEndEditing"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UISearchBar","text":"UISearchBar"},{"kind":"text","text":")"}],"kind":"symbol","url":"/documentation/uikit/uisearchbardelegate/searchbartextdidendediting(_:)"},"doc://com.apple.documentation/documentation/swift/true":{"abstract":[{"text":"A true value.","type":"text"}],"role":"symbol","url":"/documentation/swift/true","identifier":"doc://com.apple.documentation/documentation/swift/true","type":"topic","title":"true","kind":"symbol"},"doc://com.apple.uikit/documentation/UIKit/UISearchBarDelegate":{"role":"symbol","abstract":[{"type":"text","text":"A collection of optional methods that you implement to make a search bar control functional."}],"navigatorTitle":[{"kind":"identifier","text":"UISearchBarDelegate"}],"type":"topic","url":"/documentation/uikit/uisearchbardelegate","kind":"symbol","identifier":"doc://com.apple.uikit/documentation/UIKit/UISearchBarDelegate","fragments":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"UISearchBarDelegate"}],"title":"UISearchBarDelegate"},"doc://com.apple.uikit/documentation/UIKit/UISearchBar":{"abstract":[{"text":"A specialized view for receiving search-related information from the user.","type":"text"}],"title":"UISearchBar","url":"/documentation/uikit/uisearchbar","navigatorTitle":[{"text":"UISearchBar","kind":"identifier"}],"kind":"symbol","type":"topic","role":"symbol","identifier":"doc://com.apple.uikit/documentation/UIKit/UISearchBar","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"UISearchBar","kind":"identifier"}]},"doc://com.apple.uikit/documentation/UIKit/UISearchBarDelegate/searchBar(_:textDidChange:)":{"abstract":[{"text":"Tells the delegate that the user changed the search text.","type":"text"}],"kind":"symbol","identifier":"doc://com.apple.uikit/documentation/UIKit/UISearchBarDelegate/searchBar(_:textDidChange:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"searchBar","kind":"identifier"},{"text":"(","kind":"text"},{"text":"UISearchBar","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UISearchBar"},{"text":", ","kind":"text"},{"text":"textDidChange","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":")","kind":"text"}],"title":"searchBar(_:textDidChange:)","role":"symbol","navigatorTitle":[{"text":"searchBar:textDidChange:","kind":"identifier"}],"type":"topic","url":"/documentation/uikit/uisearchbardelegate/searchbar(_:textdidchange:)"},"doc://com.apple.uikit/documentation/UIKit/UISearchBarDelegate/searchBarShouldEndEditing(_:)":{"abstract":[{"type":"text","text":"Asks the delegate if editing should stop in the specified search bar."}],"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"searchBarShouldEndEditing"},{"kind":"text","text":"("},{"preciseIdentifier":"c:objc(cs)UISearchBar","kind":"typeIdentifier","text":"UISearchBar"},{"kind":"text","text":") -> "},{"preciseIdentifier":"s:Sb","kind":"typeIdentifier","text":"Bool"}],"identifier":"doc://com.apple.uikit/documentation/UIKit/UISearchBarDelegate/searchBarShouldEndEditing(_:)","type":"topic","title":"searchBarShouldEndEditing(_:)","kind":"symbol","role":"symbol","url":"/documentation/uikit/uisearchbardelegate/searchbarshouldendediting(_:)","navigatorTitle":[{"kind":"identifier","text":"searchBarShouldEndEditing:"}]},"doc://com.apple.uikit/documentation/UIKit/UISearchBarDelegate/searchBarTextDidBeginEditing(_:)":{"abstract":[{"text":"Tells the delegate when the user begins editing the search text.","type":"text"}],"kind":"symbol","identifier":"doc://com.apple.uikit/documentation/UIKit/UISearchBarDelegate/searchBarTextDidBeginEditing(_:)","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"searchBarTextDidBeginEditing","kind":"identifier"},{"text":"(","kind":"text"},{"text":"UISearchBar","preciseIdentifier":"c:objc(cs)UISearchBar","kind":"typeIdentifier"},{"text":")","kind":"text"}],"title":"searchBarTextDidBeginEditing(_:)","role":"symbol","navigatorTitle":[{"text":"searchBarTextDidBeginEditing:","kind":"identifier"}],"type":"topic","url":"/documentation/uikit/uisearchbardelegate/searchbartextdidbeginediting(_:)"},"doc://com.apple.documentation/documentation/technologies":{"role":"overview","url":"/documentation/technologies","title":"Technologies","identifier":"doc://com.apple.documentation/documentation/technologies","abstract":[{"text":"","type":"text"}],"kind":"technologies","type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"/identifier/interfaceLanguage","value":"occ"},{"op":"replace","value":[{"name":"iOS","deprecated":false,"unavailable":false,"beta":false},{"name":"iPadOS","deprecated":false,"unavailable":false,"beta":false},{"name":"Mac Catalyst","deprecated":false,"unavailable":false,"beta":false},{"name":"tvOS","deprecated":false,"unavailable":false,"beta":false},{"name":"visionOS","deprecated":false,"unavailable":false,"beta":false}],"path":"/metadata/platforms"},{"op":"replace","value":"Instance Method","path":"/metadata/roleHeading"},{"op":"replace","value":"searchBarShouldBeginEditing:","path":"/metadata/title"},{"op":"replace","value":"method","path":"/metadata/symbolKind"},{"op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"searchBarShouldBeginEditing:"}],"path":"/metadata/fragments"},{"op":"replace","value":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.uikit/documentation/UIKit","doc://com.apple.uikit/documentation/UIKit/UISearchBarDelegate"]]},"path":"/hierarchy"},{"op":"add","value":null,"path":"/topicSections"},{"op":"add","value":null,"path":"/relationshipsSections"},{"op":"replace","value":[{"anchor":"Managing-the-search-text","title":"Managing the search text","identifiers":["doc://com.apple.uikit/documentation/UIKit/UISearchBarDelegate/searchBar(_:textDidChange:)","doc://com.apple.uikit/documentation/UIKit/UISearchBarDelegate/searchBar(_:shouldChangeTextIn:replacementText:)","doc://com.apple.uikit/documentation/UIKit/UISearchBarDelegate/searchBarTextDidBeginEditing(_:)","doc://com.apple.uikit/documentation/UIKit/UISearchBarDelegate/searchBarShouldEndEditing(_:)","doc://com.apple.uikit/documentation/UIKit/UISearchBarDelegate/searchBarTextDidEndEditing(_:)"],"generated":true}],"path":"/seeAlsoSections"},{"op":"replace","value":{"declarations":[{"platforms":["iOS","iPadOS","Mac Catalyst","tvOS","visionOS"],"languages":["occ"],"tokens":[{"kind":"text","text":"- ("},{"identifier":"doc://com.externally.resolved.symbol/c:@T@BOOL","kind":"typeIdentifier","text":"BOOL","preciseIdentifier":"c:@T@BOOL"},{"kind":"text","text":") "},{"kind":"identifier","text":"searchBarShouldBeginEditing:"},{"kind":"text","text":"("},{"identifier":"doc://com.apple.uikit/documentation/UIKit/UISearchBar","kind":"typeIdentifier","text":"UISearchBar","preciseIdentifier":"c:objc(cs)UISearchBar"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"searchBar"},{"kind":"text","text":";"}]}],"kind":"declarations"},"path":"/primaryContentSections/0"},{"path":"/primaryContentSections/1","op":"replace","value":{"kind":"parameters","parameters":[{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The search bar that is being edited."}]}],"name":"searchBar"}]}},{"op":"replace","value":{"kind":"content","content":[{"anchor":"return-value","level":2,"type":"heading","text":"Return Value"},{"type":"paragraph","inlineContent":[{"text":"","type":"text"},{"identifier":"doc://com.apple.documentation/documentation/swift/true","type":"reference","isActive":true},{"text":" if an editing session should be initiated, otherwise, ","type":"text"},{"identifier":"doc://com.apple.documentation/documentation/swift/false","type":"reference","isActive":true},{"text":".","type":"text"}]}]},"path":"/primaryContentSections/2"},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UISearchBarDelegate~1searchBar(_:shouldChangeTextIn:replacementText:)/title","op":"replace","value":"searchBar:shouldChangeTextInRange:replacementText:"},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UISearchBarDelegate~1searchBar(_:shouldChangeTextIn:replacementText:)/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"text":"searchBar:shouldChangeTextInRange:replacementText:","kind":"identifier"}]},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UISearchBarDelegate~1searchBarShouldBeginEditing(_:)/title","op":"replace","value":"searchBarShouldBeginEditing:"},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UISearchBarDelegate~1searchBarShouldBeginEditing(_:)/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"searchBarShouldBeginEditing:"}]},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UISearchBarDelegate~1searchBarTextDidEndEditing(_:)/title","op":"replace","value":"searchBarTextDidEndEditing:"},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UISearchBarDelegate~1searchBarTextDidEndEditing(_:)/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"searchBarTextDidEndEditing:"}]},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UISearchBarDelegate/title","op":"replace","value":"UISearchBarDelegate"},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UISearchBarDelegate/fragments","op":"replace","value":[{"kind":"identifier","text":"UISearchBarDelegate"}]},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UISearchBarDelegate/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"UISearchBarDelegate"}]},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UISearchBar/title","op":"replace","value":"UISearchBar"},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UISearchBar/fragments","op":"replace","value":[{"text":"UISearchBar","kind":"identifier"}]},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UISearchBar/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"UISearchBar"}]},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UISearchBarDelegate~1searchBar(_:textDidChange:)/title","op":"replace","value":"searchBar:textDidChange:"},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UISearchBarDelegate~1searchBar(_:textDidChange:)/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"text":"searchBar:textDidChange:","kind":"identifier"}]},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UISearchBarDelegate~1searchBarShouldEndEditing(_:)/title","op":"replace","value":"searchBarShouldEndEditing:"},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UISearchBarDelegate~1searchBarShouldEndEditing(_:)/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"searchBarShouldEndEditing:"}]},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UISearchBarDelegate~1searchBarTextDidBeginEditing(_:)/title","op":"replace","value":"searchBarTextDidBeginEditing:"},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UISearchBarDelegate~1searchBarTextDidBeginEditing(_:)/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"text":"searchBarTextDidBeginEditing:","kind":"identifier"}]}]}],"legalNotices":{"copyright":"Copyright &copy; 2025 Apple Inc. All rights reserved.","termsOfUse":"https://www.apple.com/legal/internet-services/terms/site.html","privacyPolicy":"https://www.apple.com/privacy/privacy-policy"}}