{"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["/documentation/uikit/uisearchbardelegate/searchbarsearchbuttonclicked(_:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["/documentation/uikit/uisearchbardelegate/searchbarsearchbuttonclicked(_:)"]}],"sections":[],"abstract":[{"type":"text","text":"Tells the delegate that the search button was tapped."}],"metadata":{"platforms":[{"beta":false,"name":"iOS","introducedAt":"2.0","deprecated":false,"unavailable":false},{"introducedAt":"2.0","beta":false,"name":"iPadOS","unavailable":false,"deprecated":false},{"introducedAt":"13.1","beta":false,"name":"Mac Catalyst","unavailable":false,"deprecated":false},{"beta":false,"name":"tvOS","unavailable":false,"deprecated":false},{"introducedAt":"1.0","beta":false,"name":"visionOS","unavailable":false,"deprecated":false}],"roleHeading":"Instance Method","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"searchBarSearchButtonClicked"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UISearchBar","text":"UISearchBar"},{"kind":"text","text":")"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"searchBarSearchButtonClicked:"}],"modules":[{"name":"UIKit"}],"externalID":"c:objc(pl)UISearchBarDelegate(im)searchBarSearchButtonClicked:","title":"searchBarSearchButtonClicked(_:)","symbolKind":"method"},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"@","kind":"attribute"},{"text":"MainActor","identifier":"doc://com.externally.resolved.symbol/s:ScM","preciseIdentifier":"s:ScM","kind":"attribute"},{"text":" ","kind":"text"},{"kind":"keyword","text":"optional"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"searchBarSearchButtonClicked"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"text":" ","kind":"text"},{"text":"searchBar","kind":"internalParam"},{"text":": ","kind":"text"},{"text":"UISearchBar","identifier":"doc://com.apple.uikit/documentation/UIKit/UISearchBar","preciseIdentifier":"c:objc(cs)UISearchBar","kind":"typeIdentifier"},{"text":")","kind":"text"}],"platforms":["iOS","iPadOS","Mac Catalyst","tvOS","visionOS"],"languages":["swift"]}]},{"kind":"parameters","parameters":[{"name":"searchBar","content":[{"inlineContent":[{"text":"The search bar that was tapped.","type":"text"}],"type":"paragraph"}]}]},{"kind":"content","content":[{"text":"Discussion","type":"heading","anchor":"Discussion","level":2},{"inlineContent":[{"type":"text","text":"You should implement this method to begin the search. Use the "},{"identifier":"doc://com.apple.uikit/documentation/UIKit/UISearchBar/text","type":"reference","isActive":true},{"type":"text","text":" property of the search bar to get the text. You can also send "},{"identifier":"doc://com.apple.uikit/documentation/UIKit/UIResponder/becomeFirstResponder()","type":"reference","isActive":true},{"type":"text","text":" to the search bar to begin editing programmatically."}],"type":"paragraph"}]}],"identifier":{"interfaceLanguage":"swift","url":"doc://com.apple.uikit/documentation/UIKit/UISearchBarDelegate/searchBarSearchButtonClicked(_:)"},"schemaVersion":{"major":0,"minor":3,"patch":0},"hierarchy":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.uikit/documentation/UIKit","doc://com.apple.uikit/documentation/UIKit/UISearchBarDelegate"]]},"seeAlsoSections":[{"anchor":"Responding-to-clicks-in-search-controls","identifiers":["doc://com.apple.uikit/documentation/UIKit/UISearchBarDelegate/searchBarBookmarkButtonClicked(_:)","doc://com.apple.uikit/documentation/UIKit/UISearchBarDelegate/searchBarCancelButtonClicked(_:)","doc://com.apple.uikit/documentation/UIKit/UISearchBarDelegate/searchBarResultsListButtonClicked(_:)"],"title":"Responding to clicks in search controls","generated":true}],"kind":"symbol","references":{"doc://com.apple.uikit/documentation/UIKit/UIResponder/becomeFirstResponder()":{"navigatorTitle":[{"kind":"identifier","text":"becomeFirstResponder"}],"kind":"symbol","identifier":"doc://com.apple.uikit/documentation/UIKit/UIResponder/becomeFirstResponder()","title":"becomeFirstResponder()","url":"/documentation/uikit/uiresponder/becomefirstresponder()","role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"becomeFirstResponder"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"}],"abstract":[{"type":"text","text":"Asks UIKit to make this object the first responder in its window."}],"type":"topic"},"doc://com.apple.uikit/documentation/UIKit/UISearchBarDelegate/searchBarResultsListButtonClicked(_:)":{"abstract":[{"type":"text","text":"Tells the delegate that the search results list button was tapped."}],"role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"searchBarResultsListButtonClicked","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)UISearchBar","text":"UISearchBar","kind":"typeIdentifier"},{"text":")","kind":"text"}],"type":"topic","kind":"symbol","identifier":"doc://com.apple.uikit/documentation/UIKit/UISearchBarDelegate/searchBarResultsListButtonClicked(_:)","title":"searchBarResultsListButtonClicked(_:)","url":"/documentation/uikit/uisearchbardelegate/searchbarresultslistbuttonclicked(_:)","navigatorTitle":[{"text":"searchBarResultsListButtonClicked:","kind":"identifier"}]},"doc://com.externally.resolved.symbol/s:ScM":{"abstract":[{"text":"A singleton actor whose executor is equivalent to the main dispatch queue.","type":"text"}],"url":"/documentation/Swift/MainActor","identifier":"doc://com.externally.resolved.symbol/s:ScM","title":"MainActor","fragments":[{"text":"@globalActor","kind":"attribute"},{"text":" ","kind":"text"},{"text":"final","kind":"keyword"},{"text":" ","kind":"text"},{"text":"actor","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MainActor","kind":"identifier"}],"type":"topic","kind":"symbol","role":"symbol"},"doc://com.apple.uikit/documentation/UIKit/UISearchBar":{"abstract":[{"text":"A specialized view for receiving search-related information from the user.","type":"text"}],"title":"UISearchBar","url":"/documentation/uikit/uisearchbar","navigatorTitle":[{"text":"UISearchBar","kind":"identifier"}],"kind":"symbol","type":"topic","role":"symbol","identifier":"doc://com.apple.uikit/documentation/UIKit/UISearchBar","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"UISearchBar","kind":"identifier"}]},"doc://com.apple.documentation/documentation/technologies":{"role":"overview","url":"/documentation/technologies","title":"Technologies","identifier":"doc://com.apple.documentation/documentation/technologies","abstract":[{"text":"","type":"text"}],"kind":"technologies","type":"topic"},"doc://com.apple.uikit/documentation/UIKit/UISearchBarDelegate/searchBarSearchButtonClicked(_:)":{"abstract":[{"type":"text","text":"Tells the delegate that the search button was tapped."}],"role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"searchBarSearchButtonClicked","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)UISearchBar","text":"UISearchBar","kind":"typeIdentifier"},{"text":")","kind":"text"}],"type":"topic","kind":"symbol","identifier":"doc://com.apple.uikit/documentation/UIKit/UISearchBarDelegate/searchBarSearchButtonClicked(_:)","title":"searchBarSearchButtonClicked(_:)","url":"/documentation/uikit/uisearchbardelegate/searchbarsearchbuttonclicked(_:)","navigatorTitle":[{"text":"searchBarSearchButtonClicked:","kind":"identifier"}]},"doc://com.apple.uikit/documentation/UIKit/UISearchBarDelegate/searchBarCancelButtonClicked(_:)":{"abstract":[{"type":"text","text":"Tells the delegate that the cancel button was tapped."}],"role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"searchBarCancelButtonClicked","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)UISearchBar","text":"UISearchBar","kind":"typeIdentifier"},{"text":")","kind":"text"}],"type":"topic","kind":"symbol","identifier":"doc://com.apple.uikit/documentation/UIKit/UISearchBarDelegate/searchBarCancelButtonClicked(_:)","title":"searchBarCancelButtonClicked(_:)","url":"/documentation/uikit/uisearchbardelegate/searchbarcancelbuttonclicked(_:)","navigatorTitle":[{"text":"searchBarCancelButtonClicked:","kind":"identifier"}]},"doc://com.apple.uikit/documentation/UIKit/UISearchBarDelegate":{"role":"symbol","abstract":[{"type":"text","text":"A collection of optional methods that you implement to make a search bar control functional."}],"navigatorTitle":[{"kind":"identifier","text":"UISearchBarDelegate"}],"type":"topic","url":"/documentation/uikit/uisearchbardelegate","kind":"symbol","identifier":"doc://com.apple.uikit/documentation/UIKit/UISearchBarDelegate","fragments":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"UISearchBarDelegate"}],"title":"UISearchBarDelegate"},"doc://com.apple.uikit/documentation/UIKit/UISearchBarDelegate/searchBarBookmarkButtonClicked(_:)":{"abstract":[{"type":"text","text":"Tells the delegate that the bookmark button was tapped."}],"role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"searchBarBookmarkButtonClicked"},{"kind":"text","text":"("},{"preciseIdentifier":"c:objc(cs)UISearchBar","kind":"typeIdentifier","text":"UISearchBar"},{"kind":"text","text":")"}],"type":"topic","kind":"symbol","identifier":"doc://com.apple.uikit/documentation/UIKit/UISearchBarDelegate/searchBarBookmarkButtonClicked(_:)","title":"searchBarBookmarkButtonClicked(_:)","url":"/documentation/uikit/uisearchbardelegate/searchbarbookmarkbuttonclicked(_:)","navigatorTitle":[{"kind":"identifier","text":"searchBarBookmarkButtonClicked:"}]},"doc://com.apple.uikit/documentation/UIKit":{"kind":"symbol","role":"collection","title":"UIKit","identifier":"doc://com.apple.uikit/documentation/UIKit","url":"/documentation/uikit","abstract":[{"type":"text","text":"Construct and manage a graphical, event-driven user interface for your iOS, iPadOS, or tvOS app."}],"type":"topic"},"doc://com.apple.uikit/documentation/UIKit/UISearchBar/text":{"title":"text","url":"/documentation/uikit/uisearchbar/text","kind":"symbol","identifier":"doc://com.apple.uikit/documentation/UIKit/UISearchBar/text","type":"topic","navigatorTitle":[{"kind":"identifier","text":"text"}],"abstract":[{"type":"text","text":"The current or starting search text."}],"role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"text","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"?","kind":"text"}]}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"/identifier/interfaceLanguage"},{"value":[{"beta":false,"name":"iOS","unavailable":false,"deprecated":false},{"beta":false,"name":"iPadOS","unavailable":false,"deprecated":false},{"beta":false,"name":"Mac Catalyst","unavailable":false,"deprecated":false},{"beta":false,"name":"tvOS","unavailable":false,"deprecated":false},{"beta":false,"name":"visionOS","unavailable":false,"deprecated":false}],"op":"replace","path":"/metadata/platforms"},{"value":"Instance Method","op":"replace","path":"/metadata/roleHeading"},{"value":"searchBarSearchButtonClicked:","op":"replace","path":"/metadata/title"},{"value":"method","op":"replace","path":"/metadata/symbolKind"},{"value":[{"text":"- ","kind":"text"},{"text":"searchBarSearchButtonClicked:","kind":"identifier"}],"op":"replace","path":"/metadata/fragments"},{"value":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.uikit/documentation/UIKit","doc://com.apple.uikit/documentation/UIKit/UISearchBarDelegate"]]},"op":"replace","path":"/hierarchy"},{"op":"add","path":"/topicSections","value":null},{"op":"add","path":"/relationshipsSections","value":null},{"op":"replace","path":"/seeAlsoSections","value":[{"title":"Responding to clicks in search controls","generated":true,"identifiers":["doc://com.apple.uikit/documentation/UIKit/UISearchBarDelegate/searchBarBookmarkButtonClicked(_:)","doc://com.apple.uikit/documentation/UIKit/UISearchBarDelegate/searchBarCancelButtonClicked(_:)","doc://com.apple.uikit/documentation/UIKit/UISearchBarDelegate/searchBarResultsListButtonClicked(_:)"],"anchor":"Responding-to-clicks-in-search-controls"}]},{"op":"replace","path":"/primaryContentSections/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","preciseIdentifier":"c:v","text":"void"},{"kind":"text","text":") "},{"kind":"identifier","text":"searchBarSearchButtonClicked:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","identifier":"doc://com.apple.uikit/documentation/UIKit/UISearchBar","preciseIdentifier":"c:objc(cs)UISearchBar","text":"UISearchBar"},{"kind":"text","text":" *) "},{"text":"searchBar","kind":"internalParam"},{"text":";","kind":"text"}],"languages":["occ"],"platforms":["iOS","iPadOS","Mac Catalyst","tvOS","visionOS"]}]}},{"op":"replace","path":"/primaryContentSections/1","value":{"kind":"parameters","parameters":[{"content":[{"type":"paragraph","inlineContent":[{"text":"The search bar that was tapped.","type":"text"}]}],"name":"searchBar"}]}},{"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIResponder~1becomeFirstResponder()/title","value":"becomeFirstResponder"},{"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIResponder~1becomeFirstResponder()/fragments","value":[{"text":"- ","kind":"text"},{"text":"becomeFirstResponder","kind":"identifier"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UISearchBarDelegate~1searchBarResultsListButtonClicked(_:)/title","value":"searchBarResultsListButtonClicked:"},{"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UISearchBarDelegate~1searchBarResultsListButtonClicked(_:)/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"searchBarResultsListButtonClicked:"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UISearchBar/title","value":"UISearchBar"},{"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UISearchBar/fragments","value":[{"text":"UISearchBar","kind":"identifier"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UISearchBar/navigatorTitle","value":[{"text":"UISearchBar","kind":"identifier"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UISearchBarDelegate~1searchBarSearchButtonClicked(_:)/title","value":"searchBarSearchButtonClicked:"},{"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UISearchBarDelegate~1searchBarSearchButtonClicked(_:)/fragments","value":[{"text":"- ","kind":"text"},{"text":"searchBarSearchButtonClicked:","kind":"identifier"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UISearchBarDelegate~1searchBarCancelButtonClicked(_:)/title","value":"searchBarCancelButtonClicked:"},{"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UISearchBarDelegate~1searchBarCancelButtonClicked(_:)/fragments","value":[{"text":"- ","kind":"text"},{"text":"searchBarCancelButtonClicked:","kind":"identifier"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UISearchBarDelegate/title","value":"UISearchBarDelegate"},{"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UISearchBarDelegate/fragments","value":[{"kind":"identifier","text":"UISearchBarDelegate"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UISearchBarDelegate/navigatorTitle","value":[{"text":"UISearchBarDelegate","kind":"identifier"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UISearchBarDelegate~1searchBarBookmarkButtonClicked(_:)/title","value":"searchBarBookmarkButtonClicked:"},{"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UISearchBarDelegate~1searchBarBookmarkButtonClicked(_:)/fragments","value":[{"text":"- ","kind":"text"},{"text":"searchBarBookmarkButtonClicked:","kind":"identifier"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UISearchBar~1text/title","value":"text"},{"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UISearchBar~1text/fragments","value":[{"text":"text","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}],"legalNotices":{"copyright":"Copyright &copy; 2025 Apple Inc. All rights reserved.","termsOfUse":"https://www.apple.com/legal/internet-services/terms/site.html","privacyPolicy":"https://www.apple.com/privacy/privacy-policy"}}