{"metadata":{"externalID":"c:objc(pl)UISearchBarDelegate(im)searchBarCancelButtonClicked:","symbolKind":"method","platforms":[{"unavailable":false,"deprecated":false,"name":"iOS","introducedAt":"2.0","beta":false},{"unavailable":false,"deprecated":false,"name":"iPadOS","introducedAt":"2.0","beta":false},{"unavailable":false,"deprecated":false,"name":"Mac Catalyst","introducedAt":"13.1","beta":false},{"unavailable":false,"deprecated":false,"name":"visionOS","introducedAt":"1.0","beta":false}],"modules":[{"name":"UIKit"}],"title":"searchBarCancelButtonClicked(_:)","navigatorTitle":[{"text":"searchBarCancelButtonClicked:","kind":"identifier"}],"role":"symbol","roleHeading":"Instance Method","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"searchBarCancelButtonClicked","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)UISearchBar","text":"UISearchBar","kind":"typeIdentifier"},{"text":")","kind":"text"}]},"abstract":[{"type":"text","text":"Tells the delegate that the cancel button was tapped."}],"hierarchy":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.uikit/documentation/UIKit","doc://com.apple.uikit/documentation/UIKit/UISearchBarDelegate"]]},"kind":"symbol","seeAlsoSections":[{"identifiers":["doc://com.apple.uikit/documentation/UIKit/UISearchBar/showsCancelButton"],"anchor":"Related-Documentation","title":"Related Documentation"},{"identifiers":["doc://com.apple.uikit/documentation/UIKit/UISearchBarDelegate/searchBarBookmarkButtonClicked(_:)","doc://com.apple.uikit/documentation/UIKit/UISearchBarDelegate/searchBarSearchButtonClicked(_:)","doc://com.apple.uikit/documentation/UIKit/UISearchBarDelegate/searchBarResultsListButtonClicked(_:)"],"anchor":"Responding-to-clicks-in-search-controls","generated":true,"title":"Responding to clicks in search controls"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"@","kind":"attribute"},{"text":"MainActor","kind":"attribute","preciseIdentifier":"s:ScM","identifier":"doc://com.externally.resolved.symbol/s:ScM"},{"text":" ","kind":"text"},{"text":"optional","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"searchBarCancelButtonClicked","kind":"identifier"},{"text":"(","kind":"text"},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"searchBar","kind":"internalParam"},{"text":": ","kind":"text"},{"text":"UISearchBar","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UISearchBar","identifier":"doc://com.apple.uikit/documentation/UIKit/UISearchBar"},{"text":")","kind":"text"}],"platforms":["iOS","iPadOS","Mac Catalyst","visionOS"],"languages":["swift"]}]},{"kind":"parameters","parameters":[{"name":"searchBar","content":[{"inlineContent":[{"text":"The search bar that was tapped.","type":"text"}],"type":"paragraph"}]}]},{"content":[{"anchor":"Discussion","level":2,"text":"Discussion","type":"heading"},{"inlineContent":[{"text":"Typically, you implement this method to dismiss the search bar.","type":"text"}],"type":"paragraph"}],"kind":"content"}],"identifier":{"interfaceLanguage":"swift","url":"doc://com.apple.uikit/documentation/UIKit/UISearchBarDelegate/searchBarCancelButtonClicked(_:)"},"sections":[],"schemaVersion":{"major":0,"minor":3,"patch":0},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["/documentation/uikit/uisearchbardelegate/searchbarcancelbuttonclicked(_:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["/documentation/uikit/uisearchbardelegate/searchbarcancelbuttonclicked(_:)"]}],"references":{"doc://com.apple.uikit/documentation/UIKit/UISearchBarDelegate/searchBarResultsListButtonClicked(_:)":{"abstract":[{"type":"text","text":"Tells the delegate that the search results list button was tapped."}],"role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"searchBarResultsListButtonClicked","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)UISearchBar","text":"UISearchBar","kind":"typeIdentifier"},{"text":")","kind":"text"}],"type":"topic","kind":"symbol","identifier":"doc://com.apple.uikit/documentation/UIKit/UISearchBarDelegate/searchBarResultsListButtonClicked(_:)","title":"searchBarResultsListButtonClicked(_:)","url":"/documentation/uikit/uisearchbardelegate/searchbarresultslistbuttonclicked(_:)","navigatorTitle":[{"text":"searchBarResultsListButtonClicked:","kind":"identifier"}]},"doc://com.apple.uikit/documentation/UIKit/UISearchBarDelegate/searchBarSearchButtonClicked(_:)":{"abstract":[{"type":"text","text":"Tells the delegate that the search button was tapped."}],"role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"searchBarSearchButtonClicked","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)UISearchBar","text":"UISearchBar","kind":"typeIdentifier"},{"text":")","kind":"text"}],"type":"topic","kind":"symbol","identifier":"doc://com.apple.uikit/documentation/UIKit/UISearchBarDelegate/searchBarSearchButtonClicked(_:)","title":"searchBarSearchButtonClicked(_:)","url":"/documentation/uikit/uisearchbardelegate/searchbarsearchbuttonclicked(_:)","navigatorTitle":[{"text":"searchBarSearchButtonClicked:","kind":"identifier"}]},"doc://com.apple.uikit/documentation/UIKit":{"kind":"symbol","role":"collection","title":"UIKit","identifier":"doc://com.apple.uikit/documentation/UIKit","url":"/documentation/uikit","abstract":[{"type":"text","text":"Construct and manage a graphical, event-driven user interface for your iOS, iPadOS, or tvOS app."}],"type":"topic"},"doc://com.apple.documentation/documentation/technologies":{"role":"overview","url":"/documentation/technologies","title":"Technologies","identifier":"doc://com.apple.documentation/documentation/technologies","abstract":[{"text":"","type":"text"}],"kind":"technologies","type":"topic"},"doc://com.apple.uikit/documentation/UIKit/UISearchBar/showsCancelButton":{"url":"/documentation/uikit/uisearchbar/showscancelbutton","kind":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"showsCancelButton","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"}],"identifier":"doc://com.apple.uikit/documentation/UIKit/UISearchBar/showsCancelButton","role":"symbol","navigatorTitle":[{"text":"showsCancelButton","kind":"identifier"}],"abstract":[{"type":"text","text":"A Boolean value indicating whether the cancel button is displayed."}],"title":"showsCancelButton","type":"topic"},"doc://com.apple.uikit/documentation/UIKit/UISearchBarDelegate/searchBarBookmarkButtonClicked(_:)":{"abstract":[{"type":"text","text":"Tells the delegate that the bookmark button was tapped."}],"role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"searchBarBookmarkButtonClicked"},{"kind":"text","text":"("},{"preciseIdentifier":"c:objc(cs)UISearchBar","kind":"typeIdentifier","text":"UISearchBar"},{"kind":"text","text":")"}],"type":"topic","kind":"symbol","identifier":"doc://com.apple.uikit/documentation/UIKit/UISearchBarDelegate/searchBarBookmarkButtonClicked(_:)","title":"searchBarBookmarkButtonClicked(_:)","url":"/documentation/uikit/uisearchbardelegate/searchbarbookmarkbuttonclicked(_:)","navigatorTitle":[{"kind":"identifier","text":"searchBarBookmarkButtonClicked:"}]},"doc://com.apple.uikit/documentation/UIKit/UISearchBarDelegate":{"role":"symbol","abstract":[{"type":"text","text":"A collection of optional methods that you implement to make a search bar control functional."}],"navigatorTitle":[{"kind":"identifier","text":"UISearchBarDelegate"}],"type":"topic","url":"/documentation/uikit/uisearchbardelegate","kind":"symbol","identifier":"doc://com.apple.uikit/documentation/UIKit/UISearchBarDelegate","fragments":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"UISearchBarDelegate"}],"title":"UISearchBarDelegate"},"doc://com.apple.uikit/documentation/UIKit/UISearchBar":{"abstract":[{"text":"A specialized view for receiving search-related information from the user.","type":"text"}],"title":"UISearchBar","url":"/documentation/uikit/uisearchbar","navigatorTitle":[{"text":"UISearchBar","kind":"identifier"}],"kind":"symbol","type":"topic","role":"symbol","identifier":"doc://com.apple.uikit/documentation/UIKit/UISearchBar","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"UISearchBar","kind":"identifier"}]},"doc://com.externally.resolved.symbol/s:ScM":{"abstract":[{"text":"A singleton actor whose executor is equivalent to the main dispatch queue.","type":"text"}],"url":"/documentation/Swift/MainActor","identifier":"doc://com.externally.resolved.symbol/s:ScM","title":"MainActor","fragments":[{"text":"@globalActor","kind":"attribute"},{"text":" ","kind":"text"},{"text":"final","kind":"keyword"},{"text":" ","kind":"text"},{"text":"actor","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MainActor","kind":"identifier"}],"type":"topic","kind":"symbol","role":"symbol"},"doc://com.apple.uikit/documentation/UIKit/UISearchBarDelegate/searchBarCancelButtonClicked(_:)":{"abstract":[{"type":"text","text":"Tells the delegate that the cancel button was tapped."}],"role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"searchBarCancelButtonClicked","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)UISearchBar","text":"UISearchBar","kind":"typeIdentifier"},{"text":")","kind":"text"}],"type":"topic","kind":"symbol","identifier":"doc://com.apple.uikit/documentation/UIKit/UISearchBarDelegate/searchBarCancelButtonClicked(_:)","title":"searchBarCancelButtonClicked(_:)","url":"/documentation/uikit/uisearchbardelegate/searchbarcancelbuttonclicked(_:)","navigatorTitle":[{"text":"searchBarCancelButtonClicked:","kind":"identifier"}]}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"/identifier/interfaceLanguage"},{"value":[{"unavailable":false,"deprecated":false,"beta":false,"name":"iOS"},{"unavailable":false,"deprecated":false,"beta":false,"name":"iPadOS"},{"unavailable":false,"deprecated":false,"beta":false,"name":"Mac Catalyst"},{"unavailable":false,"deprecated":false,"beta":false,"name":"visionOS"}],"op":"replace","path":"/metadata/platforms"},{"value":"Instance Method","op":"replace","path":"/metadata/roleHeading"},{"value":"searchBarCancelButtonClicked:","op":"replace","path":"/metadata/title"},{"value":"method","op":"replace","path":"/metadata/symbolKind"},{"value":[{"text":"- ","kind":"text"},{"text":"searchBarCancelButtonClicked:","kind":"identifier"}],"op":"replace","path":"/metadata/fragments"},{"value":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.uikit/documentation/UIKit","doc://com.apple.uikit/documentation/UIKit/UISearchBarDelegate"]]},"op":"replace","path":"/hierarchy"},{"value":null,"op":"add","path":"/topicSections"},{"value":null,"op":"add","path":"/relationshipsSections"},{"value":[{"identifiers":["doc://com.apple.uikit/documentation/UIKit/UISearchBar/showsCancelButton"],"anchor":"Related-Documentation","title":"Related Documentation"},{"anchor":"Responding-to-clicks-in-search-controls","generated":true,"identifiers":["doc://com.apple.uikit/documentation/UIKit/UISearchBarDelegate/searchBarBookmarkButtonClicked(_:)","doc://com.apple.uikit/documentation/UIKit/UISearchBarDelegate/searchBarSearchButtonClicked(_:)","doc://com.apple.uikit/documentation/UIKit/UISearchBarDelegate/searchBarResultsListButtonClicked(_:)"],"title":"Responding to clicks in search controls"}],"op":"replace","path":"/seeAlsoSections"},{"value":{"declarations":[{"languages":["occ"],"platforms":["iOS","iPadOS","Mac Catalyst","tvOS","visionOS"],"tokens":[{"text":"- (","kind":"text"},{"text":"void","preciseIdentifier":"c:v","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"searchBarCancelButtonClicked:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"UISearchBar","preciseIdentifier":"c:objc(cs)UISearchBar","identifier":"doc://com.apple.uikit/documentation/UIKit/UISearchBar","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"searchBar","kind":"internalParam"},{"text":";","kind":"text"}]}],"kind":"declarations"},"op":"replace","path":"/primaryContentSections/0"},{"path":"/primaryContentSections/1","value":{"kind":"parameters","parameters":[{"name":"searchBar","content":[{"inlineContent":[{"type":"text","text":"The search bar that was tapped."}],"type":"paragraph"}]}]},"op":"replace"},{"value":"searchBarResultsListButtonClicked:","op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UISearchBarDelegate~1searchBarResultsListButtonClicked(_:)/title"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"searchBarResultsListButtonClicked:"}],"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UISearchBarDelegate~1searchBarResultsListButtonClicked(_:)/fragments"},{"value":"searchBarSearchButtonClicked:","op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UISearchBarDelegate~1searchBarSearchButtonClicked(_:)/title"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"searchBarSearchButtonClicked:"}],"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UISearchBarDelegate~1searchBarSearchButtonClicked(_:)/fragments"},{"value":"showsCancelButton","op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UISearchBar~1showsCancelButton/title"},{"value":[{"text":"showsCancelButton","kind":"identifier"}],"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UISearchBar~1showsCancelButton/fragments"},{"value":"searchBarBookmarkButtonClicked:","op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UISearchBarDelegate~1searchBarBookmarkButtonClicked(_:)/title"},{"value":[{"text":"- ","kind":"text"},{"text":"searchBarBookmarkButtonClicked:","kind":"identifier"}],"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UISearchBarDelegate~1searchBarBookmarkButtonClicked(_:)/fragments"},{"value":"UISearchBarDelegate","op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UISearchBarDelegate/title"},{"value":[{"kind":"identifier","text":"UISearchBarDelegate"}],"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UISearchBarDelegate/fragments"},{"value":[{"kind":"identifier","text":"UISearchBarDelegate"}],"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UISearchBarDelegate/navigatorTitle"},{"value":"UISearchBar","op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UISearchBar/title"},{"value":[{"kind":"identifier","text":"UISearchBar"}],"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UISearchBar/fragments"},{"value":[{"text":"UISearchBar","kind":"identifier"}],"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UISearchBar/navigatorTitle"},{"value":"searchBarCancelButtonClicked:","op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UISearchBarDelegate~1searchBarCancelButtonClicked(_:)/title"},{"value":[{"text":"- ","kind":"text"},{"text":"searchBarCancelButtonClicked:","kind":"identifier"}],"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UISearchBarDelegate~1searchBarCancelButtonClicked(_:)/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}],"legalNotices":{"copyright":"Copyright &copy; 2025 Apple Inc. All rights reserved.","termsOfUse":"https://www.apple.com/legal/internet-services/terms/site.html","privacyPolicy":"https://www.apple.com/privacy/privacy-policy"}}