{
  "abstract": [
    {
      "text": "A property key for a Boolean value that indicates whether the stream has more data.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.coremediaio/documentation/CoreMediaIO",
        "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOExtensionProperty"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOExtensionProperty/streamSinkEndOfData"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "extendedModule": "CoreMediaIO",
    "externalID": "c:@CMIOExtensionPropertyStreamSinkEndOfData",
    "fragments": [
      {
        "kind": "keyword",
        "text": "static"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "keyword",
        "text": "let"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "streamSinkEndOfData"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@T@CMIOExtensionProperty",
        "text": "CMIOExtensionProperty"
      }
    ],
    "modules": [
      {
        "name": "Core Media I/O"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "CMIOExtensionPropertyStreamSinkEndOfData"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "15.4",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "12.3",
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Type Property",
    "symbolKind": "property",
    "title": "streamSinkEndOfData"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "Mac Catalyst",
            "macOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "static"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "keyword",
              "text": "let"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "streamSinkEndOfData"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOExtensionProperty",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@CMIOExtensionProperty",
              "text": "CMIOExtensionProperty"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "The property state for this property is a number that represents a Boolean value: ",
              "type": "text"
            },
            {
              "code": "1",
              "type": "codeVoice"
            },
            {
              "text": " indicates the stream is at its end, and ",
              "type": "text"
            },
            {
              "code": "0",
              "type": "codeVoice"
            },
            {
              "text": " indicates that more data exists.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "The value of this property matches the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIOStreamPropertyEndOfData",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " property.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.coremediaio/documentation/CoreMediaIO": {
      "abstract": [
        {
          "text": "Securely support custom camera devices in macOS.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.coremediaio/documentation/CoreMediaIO",
      "kind": "symbol",
      "role": "collection",
      "title": "Core Media I/O",
      "type": "topic",
      "url": "/documentation/coremediaio"
    },
    "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOExtensionProperty": {
      "abstract": [
        {
          "text": "A structure that defines the properties that providers, devices, and streams support.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CMIOExtensionProperty"
        }
      ],
      "identifier": "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOExtensionProperty",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CMIOExtensionProperty"
        }
      ],
      "role": "symbol",
      "title": "CMIOExtensionProperty",
      "type": "topic",
      "url": "/documentation/coremediaio/cmioextensionproperty"
    },
    "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOExtensionProperty/streamActiveFormatIndex": {
      "abstract": [
        {
          "text": "A property key for the index of the active stream format.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "streamActiveFormatIndex"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CMIOExtensionProperty",
          "text": "CMIOExtensionProperty"
        }
      ],
      "identifier": "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOExtensionProperty/streamActiveFormatIndex",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CMIOExtensionPropertyStreamActiveFormatIndex"
        }
      ],
      "role": "symbol",
      "title": "streamActiveFormatIndex",
      "type": "topic",
      "url": "/documentation/coremediaio/cmioextensionproperty/streamactiveformatindex"
    },
    "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOExtensionProperty/streamFrameDuration": {
      "abstract": [
        {
          "text": "A property key for the frame duration.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "streamFrameDuration"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CMIOExtensionProperty",
          "text": "CMIOExtensionProperty"
        }
      ],
      "identifier": "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOExtensionProperty/streamFrameDuration",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CMIOExtensionPropertyStreamFrameDuration"
        }
      ],
      "role": "symbol",
      "title": "streamFrameDuration",
      "type": "topic",
      "url": "/documentation/coremediaio/cmioextensionproperty/streamframeduration"
    },
    "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOExtensionProperty/streamMaxFrameDuration": {
      "abstract": [
        {
          "text": "A property key for the maximum frame duration.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "streamMaxFrameDuration"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CMIOExtensionProperty",
          "text": "CMIOExtensionProperty"
        }
      ],
      "identifier": "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOExtensionProperty/streamMaxFrameDuration",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CMIOExtensionPropertyStreamMaxFrameDuration"
        }
      ],
      "role": "symbol",
      "title": "streamMaxFrameDuration",
      "type": "topic",
      "url": "/documentation/coremediaio/cmioextensionproperty/streammaxframeduration"
    },
    "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOExtensionProperty/streamSinkBufferQueueSize": {
      "abstract": [
        {
          "text": "A property key for the sink buffer queue size.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "streamSinkBufferQueueSize"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CMIOExtensionProperty",
          "text": "CMIOExtensionProperty"
        }
      ],
      "identifier": "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOExtensionProperty/streamSinkBufferQueueSize",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CMIOExtensionPropertyStreamSinkBufferQueueSize"
        }
      ],
      "role": "symbol",
      "title": "streamSinkBufferQueueSize",
      "type": "topic",
      "url": "/documentation/coremediaio/cmioextensionproperty/streamsinkbufferqueuesize"
    },
    "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOExtensionProperty/streamSinkBufferUnderrunCount": {
      "abstract": [
        {
          "text": "A property key for the buffer underrun count.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "streamSinkBufferUnderrunCount"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CMIOExtensionProperty",
          "text": "CMIOExtensionProperty"
        }
      ],
      "identifier": "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOExtensionProperty/streamSinkBufferUnderrunCount",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CMIOExtensionPropertyStreamSinkBufferUnderrunCount"
        }
      ],
      "role": "symbol",
      "title": "streamSinkBufferUnderrunCount",
      "type": "topic",
      "url": "/documentation/coremediaio/cmioextensionproperty/streamsinkbufferunderruncount"
    },
    "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOExtensionProperty/streamSinkBuffersRequiredForStartup": {
      "abstract": [
        {
          "text": "A property key for the number of buffers required for startup.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "streamSinkBuffersRequiredForStartup"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CMIOExtensionProperty",
          "text": "CMIOExtensionProperty"
        }
      ],
      "identifier": "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOExtensionProperty/streamSinkBuffersRequiredForStartup",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CMIOExtensionPropertyStreamSinkBuffersRequiredForStartup"
        }
      ],
      "role": "symbol",
      "title": "streamSinkBuffersRequiredForStartup",
      "type": "topic",
      "url": "/documentation/coremediaio/cmioextensionproperty/streamsinkbuffersrequiredforstartup"
    },
    "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOExtensionProperty/streamSinkEndOfData": {
      "abstract": [
        {
          "text": "A property key for a Boolean value that indicates whether the stream has more data.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "streamSinkEndOfData"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CMIOExtensionProperty",
          "text": "CMIOExtensionProperty"
        }
      ],
      "identifier": "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOExtensionProperty/streamSinkEndOfData",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CMIOExtensionPropertyStreamSinkEndOfData"
        }
      ],
      "role": "symbol",
      "title": "streamSinkEndOfData",
      "type": "topic",
      "url": "/documentation/coremediaio/cmioextensionproperty/streamsinkendofdata"
    },
    "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIOStreamPropertyEndOfData": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMIOStreamPropertyEndOfData"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.coremediaio/documentation/CoreMediaIO/kCMIOStreamPropertyEndOfData",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMIOStreamPropertyEndOfData"
        }
      ],
      "role": "symbol",
      "title": "kCMIOStreamPropertyEndOfData",
      "type": "topic",
      "url": "/documentation/coremediaio/kcmiostreampropertyendofdata"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Stream-Properties",
      "generated": true,
      "identifiers": [
        "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOExtensionProperty/streamActiveFormatIndex",
        "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOExtensionProperty/streamFrameDuration",
        "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOExtensionProperty/streamMaxFrameDuration",
        "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOExtensionProperty/streamSinkBufferQueueSize",
        "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOExtensionProperty/streamSinkBuffersRequiredForStartup",
        "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOExtensionProperty/streamSinkBufferUnderrunCount"
      ],
      "title": "Stream Properties"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "15.4",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "12.3",
              "name": "macOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Global Variable"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "CMIOExtensionPropertyStreamSinkEndOfData"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "var"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CMIOExtensionPropertyStreamSinkEndOfData"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.coremediaio/documentation/CoreMediaIO"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Stream-Properties",
              "generated": true,
              "identifiers": [
                "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOExtensionProperty/streamActiveFormatIndex",
                "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOExtensionProperty/streamFrameDuration",
                "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOExtensionProperty/streamMaxFrameDuration",
                "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOExtensionProperty/streamSinkBufferQueueSize",
                "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOExtensionProperty/streamSinkBuffersRequiredForStartup",
                "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOExtensionProperty/streamSinkBufferUnderrunCount"
              ],
              "title": "Stream Properties"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "Mac Catalyst",
                  "macOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "extern"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "identifier": "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOExtensionProperty",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@CMIOExtensionProperty",
                    "text": "CMIOExtensionProperty"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "keyword",
                    "text": "const"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "CMIOExtensionPropertyStreamSinkEndOfData"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1CMIOExtensionProperty~1streamSinkBufferQueueSize/title",
          "value": "CMIOExtensionPropertyStreamSinkBufferQueueSize"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1CMIOExtensionProperty~1streamSinkBufferQueueSize/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CMIOExtensionPropertyStreamSinkBufferQueueSize"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1kCMIOStreamPropertyEndOfData/title",
          "value": "kCMIOStreamPropertyEndOfData"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1kCMIOStreamPropertyEndOfData/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMIOStreamPropertyEndOfData"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1CMIOExtensionProperty~1streamSinkBuffersRequiredForStartup/title",
          "value": "CMIOExtensionPropertyStreamSinkBuffersRequiredForStartup"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1CMIOExtensionProperty~1streamSinkBuffersRequiredForStartup/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CMIOExtensionPropertyStreamSinkBuffersRequiredForStartup"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1CMIOExtensionProperty~1streamMaxFrameDuration/title",
          "value": "CMIOExtensionPropertyStreamMaxFrameDuration"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1CMIOExtensionProperty~1streamMaxFrameDuration/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CMIOExtensionPropertyStreamMaxFrameDuration"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1CMIOExtensionProperty~1streamSinkBufferUnderrunCount/title",
          "value": "CMIOExtensionPropertyStreamSinkBufferUnderrunCount"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1CMIOExtensionProperty~1streamSinkBufferUnderrunCount/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CMIOExtensionPropertyStreamSinkBufferUnderrunCount"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1CMIOExtensionProperty~1streamActiveFormatIndex/title",
          "value": "CMIOExtensionPropertyStreamActiveFormatIndex"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1CMIOExtensionProperty~1streamActiveFormatIndex/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CMIOExtensionPropertyStreamActiveFormatIndex"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1CMIOExtensionProperty~1streamSinkEndOfData/title",
          "value": "CMIOExtensionPropertyStreamSinkEndOfData"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1CMIOExtensionProperty~1streamSinkEndOfData/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CMIOExtensionPropertyStreamSinkEndOfData"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1CMIOExtensionProperty/title",
          "value": "CMIOExtensionProperty"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1CMIOExtensionProperty/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CMIOExtensionProperty"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1CMIOExtensionProperty/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CMIOExtensionProperty"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1CMIOExtensionProperty~1streamFrameDuration/title",
          "value": "CMIOExtensionPropertyStreamFrameDuration"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1CMIOExtensionProperty~1streamFrameDuration/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CMIOExtensionPropertyStreamFrameDuration"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/coremediaio/cmioextensionproperty/streamsinkendofdata"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/coremediaio/cmioextensionproperty/streamsinkendofdata"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
