{
  "abstract": [
    {
      "text": "A Boolean indicating if the version of the app changed at least once during the reporting period.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.metrickit/documentation/MetricKit",
        "doc://com.apple.metrickit/documentation/MetricKit/MXMetricPayload"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.metrickit/documentation/MetricKit/MXMetricPayload/includesMultipleApplicationVersions"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(cs)MXMetricPayload(py)includesMultipleApplicationVersions",
    "fragments": [
      {
        "kind": "keyword",
        "text": "var"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "includesMultipleApplicationVersions"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "s:Sb",
        "text": "Bool"
      }
    ],
    "modules": [
      {
        "name": "MetricKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "includesMultipleApplicationVersions"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.1",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Instance Property",
    "symbolKind": "property",
    "title": "includesMultipleApplicationVersions"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "var"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "includesMultipleApplicationVersions"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:Sb",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:Sb",
              "text": "Bool"
            },
            {
              "kind": "text",
              "text": " { "
            },
            {
              "kind": "keyword",
              "text": "get"
            },
            {
              "kind": "text",
              "text": " }"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.metrickit/documentation/MetricKit": {
      "abstract": [
        {
          "text": "Aggregate and analyze per-device reports on exception and crash diagnostics and on power and performance metrics.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.metrickit/documentation/MetricKit",
      "kind": "symbol",
      "role": "collection",
      "title": "MetricKit",
      "type": "topic",
      "url": "/documentation/metrickit"
    },
    "doc://com.apple.metrickit/documentation/MetricKit/MXMetricPayload": {
      "abstract": [
        {
          "text": "An object that encapsulates a daily metrics report.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MXMetricPayload"
        }
      ],
      "identifier": "doc://com.apple.metrickit/documentation/MetricKit/MXMetricPayload",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MXMetricPayload"
        }
      ],
      "role": "symbol",
      "title": "MXMetricPayload",
      "type": "topic",
      "url": "/documentation/metrickit/mxmetricpayload"
    },
    "doc://com.apple.metrickit/documentation/MetricKit/MXMetricPayload/includesMultipleApplicationVersions": {
      "abstract": [
        {
          "text": "A Boolean indicating if the version of the app changed at least once during the reporting period.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "includesMultipleApplicationVersions"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.metrickit/documentation/MetricKit/MXMetricPayload/includesMultipleApplicationVersions",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "includesMultipleApplicationVersions"
        }
      ],
      "role": "symbol",
      "title": "includesMultipleApplicationVersions",
      "type": "topic",
      "url": "/documentation/metrickit/mxmetricpayload/includesmultipleapplicationversions"
    },
    "doc://com.apple.metrickit/documentation/MetricKit/MXMetricPayload/latestApplicationVersion": {
      "abstract": [
        {
          "text": "The version of the app on the device at the end of the reporting period.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "latestApplicationVersion"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.metrickit/documentation/MetricKit/MXMetricPayload/latestApplicationVersion",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "latestApplicationVersion"
        }
      ],
      "role": "symbol",
      "title": "latestApplicationVersion",
      "type": "topic",
      "url": "/documentation/metrickit/mxmetricpayload/latestapplicationversion"
    },
    "doc://com.apple.metrickit/documentation/MetricKit/MXMetricPayload/metaData": {
      "abstract": [
        {
          "text": "A set of system-level information for the device.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "metaData"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)MXMetaData",
          "text": "MXMetaData"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.metrickit/documentation/MetricKit/MXMetricPayload/metaData",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "metaData"
        }
      ],
      "role": "symbol",
      "title": "metaData",
      "type": "topic",
      "url": "/documentation/metrickit/mxmetricpayload/metadata"
    },
    "doc://com.apple.metrickit/documentation/MetricKit/MXMetricPayload/timeStampBegin": {
      "abstract": [
        {
          "text": "The starting time of the reporting period.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "timeStampBegin"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10Foundation4DateV",
          "text": "Date"
        }
      ],
      "identifier": "doc://com.apple.metrickit/documentation/MetricKit/MXMetricPayload/timeStampBegin",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "timeStampBegin"
        }
      ],
      "role": "symbol",
      "title": "timeStampBegin",
      "type": "topic",
      "url": "/documentation/metrickit/mxmetricpayload/timestampbegin"
    },
    "doc://com.apple.metrickit/documentation/MetricKit/MXMetricPayload/timeStampEnd": {
      "abstract": [
        {
          "text": "The ending time of the reporting period.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "timeStampEnd"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10Foundation4DateV",
          "text": "Date"
        }
      ],
      "identifier": "doc://com.apple.metrickit/documentation/MetricKit/MXMetricPayload/timeStampEnd",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "timeStampEnd"
        }
      ],
      "role": "symbol",
      "title": "timeStampEnd",
      "type": "topic",
      "url": "/documentation/metrickit/mxmetricpayload/timestampend"
    },
    "doc://com.externally.resolved.symbol/s:Sb": {
      "abstract": [
        {
          "text": "A value type whose instances are either `true` or `false`.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@frozen"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:Sb",
      "kind": "symbol",
      "role": "symbol",
      "title": "Bool",
      "type": "topic",
      "url": "/documentation/Swift/Bool"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Reading-information-about-the-payload",
      "generated": true,
      "identifiers": [
        "doc://com.apple.metrickit/documentation/MetricKit/MXMetricPayload/timeStampBegin",
        "doc://com.apple.metrickit/documentation/MetricKit/MXMetricPayload/timeStampEnd",
        "doc://com.apple.metrickit/documentation/MetricKit/MXMetricPayload/latestApplicationVersion",
        "doc://com.apple.metrickit/documentation/MetricKit/MXMetricPayload/metaData"
      ],
      "title": "Reading information about the payload"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.1",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Instance Property"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "includesMultipleApplicationVersions"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "property"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "includesMultipleApplicationVersions"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.metrickit/documentation/MetricKit",
                "doc://com.apple.metrickit/documentation/MetricKit/MXMetricPayload"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Reading-information-about-the-payload",
              "generated": true,
              "identifiers": [
                "doc://com.apple.metrickit/documentation/MetricKit/MXMetricPayload/timeStampBegin",
                "doc://com.apple.metrickit/documentation/MetricKit/MXMetricPayload/timeStampEnd",
                "doc://com.apple.metrickit/documentation/MetricKit/MXMetricPayload/latestApplicationVersion",
                "doc://com.apple.metrickit/documentation/MetricKit/MXMetricPayload/metaData"
              ],
              "title": "Reading information about the payload"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "@property"
                  },
                  {
                    "kind": "text",
                    "text": " ("
                  },
                  {
                    "kind": "keyword",
                    "text": "readonly"
                  },
                  {
                    "kind": "text",
                    "text": ") "
                  },
                  {
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@BOOL",
                    "text": "BOOL"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "includesMultipleApplicationVersions"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metrickit~1documentation~1MetricKit~1MXMetricPayload~1timeStampEnd/title",
          "value": "timeStampEnd"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metrickit~1documentation~1MetricKit~1MXMetricPayload~1timeStampEnd/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "timeStampEnd"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metrickit~1documentation~1MetricKit~1MXMetricPayload~1latestApplicationVersion/title",
          "value": "latestApplicationVersion"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metrickit~1documentation~1MetricKit~1MXMetricPayload~1latestApplicationVersion/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "latestApplicationVersion"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metrickit~1documentation~1MetricKit~1MXMetricPayload/title",
          "value": "MXMetricPayload"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metrickit~1documentation~1MetricKit~1MXMetricPayload/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MXMetricPayload"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metrickit~1documentation~1MetricKit~1MXMetricPayload/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MXMetricPayload"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metrickit~1documentation~1MetricKit~1MXMetricPayload~1metaData/title",
          "value": "metaData"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metrickit~1documentation~1MetricKit~1MXMetricPayload~1metaData/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "metaData"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metrickit~1documentation~1MetricKit~1MXMetricPayload~1includesMultipleApplicationVersions/title",
          "value": "includesMultipleApplicationVersions"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metrickit~1documentation~1MetricKit~1MXMetricPayload~1includesMultipleApplicationVersions/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "includesMultipleApplicationVersions"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metrickit~1documentation~1MetricKit~1MXMetricPayload~1timeStampBegin/title",
          "value": "timeStampBegin"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metrickit~1documentation~1MetricKit~1MXMetricPayload~1timeStampBegin/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "timeStampBegin"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/metrickit/mxmetricpayload/includesmultipleapplicationversions"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/metrickit/mxmetricpayload/includesmultipleapplicationversions"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
