{
  "abstract": [
    {
      "text": "The left wrist.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.vision/documentation/Vision",
        "doc://com.apple.vision/documentation/Vision/VNRecognizedPointKey"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.vision/documentation/Vision/VNRecognizedPointKey/bodyLandmarkKeyLeftWrist"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "extendedModule": "Vision",
    "externalID": "c:@VNBodyLandmarkKeyLeftWrist",
    "fragments": [
      {
        "kind": "keyword",
        "text": "static"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "keyword",
        "text": "let"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "bodyLandmarkKeyLeftWrist"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@T@VNRecognizedPointKey",
        "text": "VNRecognizedPointKey"
      }
    ],
    "modules": [
      {
        "name": "Vision"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "VNBodyLandmarkKeyLeftWrist"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "14.0",
        "introducedAt": "14.0",
        "name": "iOS",
        "renamed": "VNHumanBodyPoseObservation.JointName.leftWrist",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "14.0",
        "introducedAt": "14.0",
        "name": "iPadOS",
        "renamed": "VNHumanBodyPoseObservation.JointName.leftWrist",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "14.0",
        "introducedAt": "14.0",
        "name": "Mac Catalyst",
        "renamed": "VNHumanBodyPoseObservation.JointName.leftWrist",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "11.0",
        "introducedAt": "11.0",
        "name": "macOS",
        "renamed": "VNHumanBodyPoseObservation.JointName.leftWrist",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "14.0",
        "introducedAt": "14.0",
        "name": "tvOS",
        "renamed": "VNHumanBodyPoseObservation.JointName.leftWrist",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "1.0",
        "introducedAt": "1.0",
        "name": "visionOS",
        "renamed": "VNHumanBodyPoseObservation.JointName.leftWrist",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Type Property",
    "symbolKind": "property",
    "title": "bodyLandmarkKeyLeftWrist"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "static"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "keyword",
              "text": "let"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "bodyLandmarkKeyLeftWrist"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.vision/documentation/Vision/VNRecognizedPointKey",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@VNRecognizedPointKey",
              "text": "VNRecognizedPointKey"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.vision/documentation/Vision": {
      "abstract": [
        {
          "text": "Apply computer vision algorithms to perform a variety of tasks on input images and videos.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.vision/documentation/Vision",
      "kind": "symbol",
      "role": "collection",
      "title": "Vision",
      "type": "topic",
      "url": "/documentation/vision"
    },
    "doc://com.apple.vision/documentation/Vision/VNRecognizedPointGroupKey/bodyLandmarkRegionKeyLeftArm": {
      "abstract": [
        {
          "text": "A group key identifying the landmarks of the left arm.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "bodyLandmarkRegionKeyLeftArm"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@VNRecognizedPointGroupKey",
          "text": "VNRecognizedPointGroupKey"
        }
      ],
      "identifier": "doc://com.apple.vision/documentation/Vision/VNRecognizedPointGroupKey/bodyLandmarkRegionKeyLeftArm",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "VNBodyLandmarkRegionKeyLeftArm"
        }
      ],
      "role": "symbol",
      "title": "bodyLandmarkRegionKeyLeftArm",
      "type": "topic",
      "url": "/documentation/vision/vnrecognizedpointgroupkey/bodylandmarkregionkeyleftarm"
    },
    "doc://com.apple.vision/documentation/Vision/VNRecognizedPointGroupKey/bodyLandmarkRegionKeyRightArm": {
      "abstract": [
        {
          "text": "A group key identifying the landmarks of the right arm.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "bodyLandmarkRegionKeyRightArm"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@VNRecognizedPointGroupKey",
          "text": "VNRecognizedPointGroupKey"
        }
      ],
      "identifier": "doc://com.apple.vision/documentation/Vision/VNRecognizedPointGroupKey/bodyLandmarkRegionKeyRightArm",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "VNBodyLandmarkRegionKeyRightArm"
        }
      ],
      "role": "symbol",
      "title": "bodyLandmarkRegionKeyRightArm",
      "type": "topic",
      "url": "/documentation/vision/vnrecognizedpointgroupkey/bodylandmarkregionkeyrightarm"
    },
    "doc://com.apple.vision/documentation/Vision/VNRecognizedPointKey": {
      "abstract": [
        {
          "text": "The data type for all recognized point keys.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "VNRecognizedPointKey"
        }
      ],
      "identifier": "doc://com.apple.vision/documentation/Vision/VNRecognizedPointKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "VNRecognizedPointKey"
        }
      ],
      "role": "symbol",
      "title": "VNRecognizedPointKey",
      "type": "topic",
      "url": "/documentation/vision/vnrecognizedpointkey"
    },
    "doc://com.apple.vision/documentation/Vision/VNRecognizedPointKey/bodyLandmarkKeyLeftElbow": {
      "abstract": [
        {
          "text": "The left elbow.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "bodyLandmarkKeyLeftElbow"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@VNRecognizedPointKey",
          "text": "VNRecognizedPointKey"
        }
      ],
      "identifier": "doc://com.apple.vision/documentation/Vision/VNRecognizedPointKey/bodyLandmarkKeyLeftElbow",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "VNBodyLandmarkKeyLeftElbow"
        }
      ],
      "role": "symbol",
      "title": "bodyLandmarkKeyLeftElbow",
      "type": "topic",
      "url": "/documentation/vision/vnrecognizedpointkey/bodylandmarkkeyleftelbow"
    },
    "doc://com.apple.vision/documentation/Vision/VNRecognizedPointKey/bodyLandmarkKeyLeftWrist": {
      "abstract": [
        {
          "text": "The left wrist.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "bodyLandmarkKeyLeftWrist"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@VNRecognizedPointKey",
          "text": "VNRecognizedPointKey"
        }
      ],
      "identifier": "doc://com.apple.vision/documentation/Vision/VNRecognizedPointKey/bodyLandmarkKeyLeftWrist",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "VNBodyLandmarkKeyLeftWrist"
        }
      ],
      "role": "symbol",
      "title": "bodyLandmarkKeyLeftWrist",
      "type": "topic",
      "url": "/documentation/vision/vnrecognizedpointkey/bodylandmarkkeyleftwrist"
    },
    "doc://com.apple.vision/documentation/Vision/VNRecognizedPointKey/bodyLandmarkKeyRightElbow": {
      "abstract": [
        {
          "text": "The right elbow.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "bodyLandmarkKeyRightElbow"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@VNRecognizedPointKey",
          "text": "VNRecognizedPointKey"
        }
      ],
      "identifier": "doc://com.apple.vision/documentation/Vision/VNRecognizedPointKey/bodyLandmarkKeyRightElbow",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "VNBodyLandmarkKeyRightElbow"
        }
      ],
      "role": "symbol",
      "title": "bodyLandmarkKeyRightElbow",
      "type": "topic",
      "url": "/documentation/vision/vnrecognizedpointkey/bodylandmarkkeyrightelbow"
    },
    "doc://com.apple.vision/documentation/Vision/VNRecognizedPointKey/bodyLandmarkKeyRightWrist": {
      "abstract": [
        {
          "text": "The right wrist.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "bodyLandmarkKeyRightWrist"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@VNRecognizedPointKey",
          "text": "VNRecognizedPointKey"
        }
      ],
      "identifier": "doc://com.apple.vision/documentation/Vision/VNRecognizedPointKey/bodyLandmarkKeyRightWrist",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "VNBodyLandmarkKeyRightWrist"
        }
      ],
      "role": "symbol",
      "title": "bodyLandmarkKeyRightWrist",
      "type": "topic",
      "url": "/documentation/vision/vnrecognizedpointkey/bodylandmarkkeyrightwrist"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Arms",
      "generated": true,
      "identifiers": [
        "doc://com.apple.vision/documentation/Vision/VNRecognizedPointKey/bodyLandmarkKeyRightWrist",
        "doc://com.apple.vision/documentation/Vision/VNRecognizedPointKey/bodyLandmarkKeyRightElbow",
        "doc://com.apple.vision/documentation/Vision/VNRecognizedPointGroupKey/bodyLandmarkRegionKeyRightArm",
        "doc://com.apple.vision/documentation/Vision/VNRecognizedPointKey/bodyLandmarkKeyLeftElbow",
        "doc://com.apple.vision/documentation/Vision/VNRecognizedPointGroupKey/bodyLandmarkRegionKeyLeftArm"
      ],
      "title": "Arms"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "deprecatedAt": "14.0",
              "introducedAt": "14.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "deprecatedAt": "14.0",
              "introducedAt": "14.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "deprecatedAt": "14.0",
              "introducedAt": "14.0",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "deprecatedAt": "11.0",
              "introducedAt": "11.0",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "deprecatedAt": "14.0",
              "introducedAt": "14.0",
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "deprecatedAt": "1.0",
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Global Variable"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "VNBodyLandmarkKeyLeftWrist"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "var"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "VNBodyLandmarkKeyLeftWrist"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.vision/documentation/Vision"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Arms",
              "generated": true,
              "identifiers": [
                "doc://com.apple.vision/documentation/Vision/VNRecognizedPointKey/bodyLandmarkKeyRightWrist",
                "doc://com.apple.vision/documentation/Vision/VNRecognizedPointKey/bodyLandmarkKeyRightElbow",
                "doc://com.apple.vision/documentation/Vision/VNRecognizedPointGroupKey/bodyLandmarkRegionKeyRightArm",
                "doc://com.apple.vision/documentation/Vision/VNRecognizedPointKey/bodyLandmarkKeyLeftElbow",
                "doc://com.apple.vision/documentation/Vision/VNRecognizedPointGroupKey/bodyLandmarkRegionKeyLeftArm"
              ],
              "title": "Arms"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "extern"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "identifier": "doc://com.apple.vision/documentation/Vision/VNRecognizedPointKey",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@VNRecognizedPointKey",
                    "text": "VNRecognizedPointKey"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "keyword",
                    "text": "const"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "VNBodyLandmarkKeyLeftWrist"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNRecognizedPointKey/title",
          "value": "VNRecognizedPointKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNRecognizedPointKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "VNRecognizedPointKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNRecognizedPointKey/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "VNRecognizedPointKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNRecognizedPointKey~1bodyLandmarkKeyRightElbow/title",
          "value": "VNBodyLandmarkKeyRightElbow"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNRecognizedPointKey~1bodyLandmarkKeyRightElbow/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "VNBodyLandmarkKeyRightElbow"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNRecognizedPointKey~1bodyLandmarkKeyRightWrist/title",
          "value": "VNBodyLandmarkKeyRightWrist"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNRecognizedPointKey~1bodyLandmarkKeyRightWrist/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "VNBodyLandmarkKeyRightWrist"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNRecognizedPointKey~1bodyLandmarkKeyLeftWrist/title",
          "value": "VNBodyLandmarkKeyLeftWrist"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNRecognizedPointKey~1bodyLandmarkKeyLeftWrist/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "VNBodyLandmarkKeyLeftWrist"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNRecognizedPointGroupKey~1bodyLandmarkRegionKeyLeftArm/title",
          "value": "VNBodyLandmarkRegionKeyLeftArm"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNRecognizedPointGroupKey~1bodyLandmarkRegionKeyLeftArm/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "VNBodyLandmarkRegionKeyLeftArm"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNRecognizedPointKey~1bodyLandmarkKeyLeftElbow/title",
          "value": "VNBodyLandmarkKeyLeftElbow"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNRecognizedPointKey~1bodyLandmarkKeyLeftElbow/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "VNBodyLandmarkKeyLeftElbow"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNRecognizedPointGroupKey~1bodyLandmarkRegionKeyRightArm/title",
          "value": "VNBodyLandmarkRegionKeyRightArm"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNRecognizedPointGroupKey~1bodyLandmarkRegionKeyRightArm/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "VNBodyLandmarkRegionKeyRightArm"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/vision/vnrecognizedpointkey/bodylandmarkkeyleftwrist"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/vision/vnrecognizedpointkey/bodylandmarkkeyleftwrist"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
