{
  "abstract": [
    {
      "text": "A key for the context’s set of invalidated objects.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.coredata/documentation/CoreData",
        "doc://com.apple.coredata/documentation/CoreData/NSManagedObjectContext",
        "doc://com.apple.coredata/documentation/CoreData/NSManagedObjectContext/NotificationKey"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.coredata/documentation/CoreData/NSManagedObjectContext/NotificationKey/invalidatedObjects"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "s:So22NSManagedObjectContextC8CoreDataE15NotificationKeyO18invalidatedObjectsyA2EmF",
    "fragments": [
      {
        "kind": "keyword",
        "text": "case"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "invalidatedObjects"
      }
    ],
    "modules": [
      {
        "name": "Core Data"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "3.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "3.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.5",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "3.0",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Case",
    "symbolKind": "case",
    "title": "NSManagedObjectContext.NotificationKey.invalidatedObjects"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "case"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "invalidatedObjects"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.coredata/documentation/CoreData": {
      "abstract": [
        {
          "text": "Persist or cache data on a single device, or sync data to multiple devices with CloudKit.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.coredata/documentation/CoreData",
      "kind": "symbol",
      "role": "collection",
      "title": "Core Data",
      "type": "topic",
      "url": "/documentation/coredata"
    },
    "doc://com.apple.coredata/documentation/CoreData/NSManagedObjectContext": {
      "abstract": [
        {
          "text": "An object space to manipulate and track changes to managed objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSManagedObjectContext"
        }
      ],
      "identifier": "doc://com.apple.coredata/documentation/CoreData/NSManagedObjectContext",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSManagedObjectContext"
        }
      ],
      "role": "symbol",
      "title": "NSManagedObjectContext",
      "type": "topic",
      "url": "/documentation/coredata/nsmanagedobjectcontext"
    },
    "doc://com.apple.coredata/documentation/CoreData/NSManagedObjectContext/NotificationKey": {
      "abstract": [
        {
          "text": "Keys to access details in user info dictionaries of managed object context notifications.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NotificationKey"
        }
      ],
      "identifier": "doc://com.apple.coredata/documentation/CoreData/NSManagedObjectContext/NotificationKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NotificationKey"
        }
      ],
      "role": "symbol",
      "title": "NSManagedObjectContext.NotificationKey",
      "type": "topic",
      "url": "/documentation/coredata/nsmanagedobjectcontext/notificationkey"
    },
    "doc://com.apple.coredata/documentation/CoreData/NSManagedObjectContext/NotificationKey/deletedObjectIDs": {
      "abstract": [
        {
          "text": "A key for the set of deleted object identifiers.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "deletedObjectIDs"
        }
      ],
      "identifier": "doc://com.apple.coredata/documentation/CoreData/NSManagedObjectContext/NotificationKey/deletedObjectIDs",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSManagedObjectContext.NotificationKey.deletedObjectIDs",
      "type": "topic",
      "url": "/documentation/coredata/nsmanagedobjectcontext/notificationkey/deletedobjectids"
    },
    "doc://com.apple.coredata/documentation/CoreData/NSManagedObjectContext/NotificationKey/deletedObjects": {
      "abstract": [
        {
          "text": "A key for the context’s set of deleted objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "deletedObjects"
        }
      ],
      "identifier": "doc://com.apple.coredata/documentation/CoreData/NSManagedObjectContext/NotificationKey/deletedObjects",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSManagedObjectContext.NotificationKey.deletedObjects",
      "type": "topic",
      "url": "/documentation/coredata/nsmanagedobjectcontext/notificationkey/deletedobjects"
    },
    "doc://com.apple.coredata/documentation/CoreData/NSManagedObjectContext/NotificationKey/insertedObjectIDs": {
      "abstract": [
        {
          "text": "A key for the set of inserted object identifiers.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "insertedObjectIDs"
        }
      ],
      "identifier": "doc://com.apple.coredata/documentation/CoreData/NSManagedObjectContext/NotificationKey/insertedObjectIDs",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSManagedObjectContext.NotificationKey.insertedObjectIDs",
      "type": "topic",
      "url": "/documentation/coredata/nsmanagedobjectcontext/notificationkey/insertedobjectids"
    },
    "doc://com.apple.coredata/documentation/CoreData/NSManagedObjectContext/NotificationKey/insertedObjects": {
      "abstract": [
        {
          "text": "A key for the context’s set of inserted objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "insertedObjects"
        }
      ],
      "identifier": "doc://com.apple.coredata/documentation/CoreData/NSManagedObjectContext/NotificationKey/insertedObjects",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSManagedObjectContext.NotificationKey.insertedObjects",
      "type": "topic",
      "url": "/documentation/coredata/nsmanagedobjectcontext/notificationkey/insertedobjects"
    },
    "doc://com.apple.coredata/documentation/CoreData/NSManagedObjectContext/NotificationKey/invalidatedAllObjects": {
      "abstract": [
        {
          "text": "A key for the context’s set of all invalidated objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "invalidatedAllObjects"
        }
      ],
      "identifier": "doc://com.apple.coredata/documentation/CoreData/NSManagedObjectContext/NotificationKey/invalidatedAllObjects",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSManagedObjectContext.NotificationKey.invalidatedAllObjects",
      "type": "topic",
      "url": "/documentation/coredata/nsmanagedobjectcontext/notificationkey/invalidatedallobjects"
    },
    "doc://com.apple.coredata/documentation/CoreData/NSManagedObjectContext/NotificationKey/invalidatedObjectIDs": {
      "abstract": [
        {
          "text": "A key for the set of invalidated object identifiers.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "invalidatedObjectIDs"
        }
      ],
      "identifier": "doc://com.apple.coredata/documentation/CoreData/NSManagedObjectContext/NotificationKey/invalidatedObjectIDs",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSManagedObjectContext.NotificationKey.invalidatedObjectIDs",
      "type": "topic",
      "url": "/documentation/coredata/nsmanagedobjectcontext/notificationkey/invalidatedobjectids"
    },
    "doc://com.apple.coredata/documentation/CoreData/NSManagedObjectContext/NotificationKey/invalidatedObjects": {
      "abstract": [
        {
          "text": "A key for the context’s set of invalidated objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "invalidatedObjects"
        }
      ],
      "identifier": "doc://com.apple.coredata/documentation/CoreData/NSManagedObjectContext/NotificationKey/invalidatedObjects",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSManagedObjectContext.NotificationKey.invalidatedObjects",
      "type": "topic",
      "url": "/documentation/coredata/nsmanagedobjectcontext/notificationkey/invalidatedobjects"
    },
    "doc://com.apple.coredata/documentation/CoreData/NSManagedObjectContext/NotificationKey/queryGeneration": {
      "abstract": [
        {
          "text": "A key for the token that indicates which generation of the persistent store Core Data is accessing",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "queryGeneration"
        }
      ],
      "identifier": "doc://com.apple.coredata/documentation/CoreData/NSManagedObjectContext/NotificationKey/queryGeneration",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSManagedObjectContext.NotificationKey.queryGeneration",
      "type": "topic",
      "url": "/documentation/coredata/nsmanagedobjectcontext/notificationkey/querygeneration"
    },
    "doc://com.apple.coredata/documentation/CoreData/NSManagedObjectContext/NotificationKey/refreshedObjectIDs": {
      "abstract": [
        {
          "text": "A key for the set of refreshed object identifiers.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "refreshedObjectIDs"
        }
      ],
      "identifier": "doc://com.apple.coredata/documentation/CoreData/NSManagedObjectContext/NotificationKey/refreshedObjectIDs",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSManagedObjectContext.NotificationKey.refreshedObjectIDs",
      "type": "topic",
      "url": "/documentation/coredata/nsmanagedobjectcontext/notificationkey/refreshedobjectids"
    },
    "doc://com.apple.coredata/documentation/CoreData/NSManagedObjectContext/NotificationKey/refreshedObjects": {
      "abstract": [
        {
          "text": "A key for the context’s set of refreshed objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "refreshedObjects"
        }
      ],
      "identifier": "doc://com.apple.coredata/documentation/CoreData/NSManagedObjectContext/NotificationKey/refreshedObjects",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSManagedObjectContext.NotificationKey.refreshedObjects",
      "type": "topic",
      "url": "/documentation/coredata/nsmanagedobjectcontext/notificationkey/refreshedobjects"
    },
    "doc://com.apple.coredata/documentation/CoreData/NSManagedObjectContext/NotificationKey/updatedObjectIDs": {
      "abstract": [
        {
          "text": "A key for the set of updated object identifiers.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "updatedObjectIDs"
        }
      ],
      "identifier": "doc://com.apple.coredata/documentation/CoreData/NSManagedObjectContext/NotificationKey/updatedObjectIDs",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSManagedObjectContext.NotificationKey.updatedObjectIDs",
      "type": "topic",
      "url": "/documentation/coredata/nsmanagedobjectcontext/notificationkey/updatedobjectids"
    },
    "doc://com.apple.coredata/documentation/CoreData/NSManagedObjectContext/NotificationKey/updatedObjects": {
      "abstract": [
        {
          "text": "A key for the context’s set of updated objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "updatedObjects"
        }
      ],
      "identifier": "doc://com.apple.coredata/documentation/CoreData/NSManagedObjectContext/NotificationKey/updatedObjects",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSManagedObjectContext.NotificationKey.updatedObjects",
      "type": "topic",
      "url": "/documentation/coredata/nsmanagedobjectcontext/notificationkey/updatedobjects"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Constants",
      "generated": true,
      "identifiers": [
        "doc://com.apple.coredata/documentation/CoreData/NSManagedObjectContext/NotificationKey/deletedObjectIDs",
        "doc://com.apple.coredata/documentation/CoreData/NSManagedObjectContext/NotificationKey/deletedObjects",
        "doc://com.apple.coredata/documentation/CoreData/NSManagedObjectContext/NotificationKey/insertedObjectIDs",
        "doc://com.apple.coredata/documentation/CoreData/NSManagedObjectContext/NotificationKey/insertedObjects",
        "doc://com.apple.coredata/documentation/CoreData/NSManagedObjectContext/NotificationKey/invalidatedAllObjects",
        "doc://com.apple.coredata/documentation/CoreData/NSManagedObjectContext/NotificationKey/invalidatedObjectIDs",
        "doc://com.apple.coredata/documentation/CoreData/NSManagedObjectContext/NotificationKey/queryGeneration",
        "doc://com.apple.coredata/documentation/CoreData/NSManagedObjectContext/NotificationKey/refreshedObjectIDs",
        "doc://com.apple.coredata/documentation/CoreData/NSManagedObjectContext/NotificationKey/refreshedObjects",
        "doc://com.apple.coredata/documentation/CoreData/NSManagedObjectContext/NotificationKey/updatedObjectIDs",
        "doc://com.apple.coredata/documentation/CoreData/NSManagedObjectContext/NotificationKey/updatedObjects"
      ],
      "title": "Constants"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coredata~1documentation~1CoreData~1NSManagedObjectContext/title",
          "value": "NSManagedObjectContext"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coredata~1documentation~1CoreData~1NSManagedObjectContext/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSManagedObjectContext"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coredata~1documentation~1CoreData~1NSManagedObjectContext/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSManagedObjectContext"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/coredata/nsmanagedobjectcontext/notificationkey/invalidatedobjects"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    }
  ]
}
