{
  "abstract": [
    {
      "text": "Detect and respond to squeezes a person makes on Apple Pencil Pro.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.ApplePencil/documentation/ApplePencil"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.ApplePencil/documentation/ApplePencil/handling-squeezes-from-apple-pencil"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "role": "article",
    "roleHeading": "Article",
    "title": "Handling squeezes from Apple Pencil"
  },
  "primaryContentSections": [
    {
      "content": [
        {
          "anchor": "Overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "You can use Apple Pencil interactions to allow people to access functionality in your app quickly.",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "Squeezing Apple Pencil Pro lets a person perform actions such as showing a contextual palette without moving the pencil to another location on the screen.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "identifier": "apple-pencil-squeeze",
              "type": "image"
            }
          ],
          "type": "paragraph"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "Only Apple Pencil Pro supports squeeze interactions.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "Note",
          "style": "note",
          "type": "aside"
        },
        {
          "anchor": "Register-for-a-squeeze",
          "level": 3,
          "text": "Register for a squeeze",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "To respond to squeezes from Apple Pencil Pro in your app, you need to register your view to receive squeeze interactions.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "tabs": [
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Add an ",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.documentation/documentation/SwiftUI/View/onPencilSqueeze(perform:)",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": " view modifier to your view.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                },
                {
                  "code": [
                    "MyView()",
                    "    .onPencilSqueeze { phase in",
                    "        // ...",
                    "    }"
                  ],
                  "syntax": "swift",
                  "type": "codeListing"
                }
              ],
              "title": "SwiftUI"
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Create a ",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.documentation/documentation/UIKit/UIPencilInteraction",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": " object, passing an object that implements the ",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.documentation/documentation/UIKit/UIPencilInteractionDelegate",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": " protocol to the ",
                      "type": "text"
                    },
                    {
                      "code": "delegate",
                      "type": "codeVoice"
                    },
                    {
                      "text": " parameter.",
                      "type": "text"
                    },
                    {
                      "text": " ",
                      "type": "text"
                    },
                    {
                      "text": "Then, add the interaction to your view.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                },
                {
                  "code": [
                    "class ViewController: UIViewController, UIPencilInteractionDelegate {",
                    "   ",
                    "   override func viewDidLoad() {",
                    "       super.viewDidLoad()",
                    "       ",
                    "       // Register for a squeeze.",
                    "       let pencilInteraction = UIPencilInteraction(delegate: self)",
                    "       view.addInteraction(pencilInteraction)",
                    "   }",
                    "   // ...",
                    "}"
                  ],
                  "syntax": "swift",
                  "type": "codeListing"
                }
              ],
              "title": "UIKit"
            }
          ],
          "type": "tabNavigator"
        },
        {
          "anchor": "Check-the-preferred-squeeze-action",
          "level": 3,
          "text": "Check the preferred squeeze action",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "A person can choose which action they prefer to perform when they squeeze Apple Pencil Pro.",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "They choose this preference in Settings > Apple Pencil > Actions > Squeeze.",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "In addition to drawing-specific actions like switching drawing tools, people can configure the preferred action for squeeze to perform any App Shortcut, including pre-configured shortcuts you provide for your app.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "In your app, you can check the value of this preferred action for squeeze.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "tabs": [
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "To check the preferred action, use the ",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.documentation/documentation/SwiftUI/EnvironmentValues/preferredPencilSqueezeAction",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": " environment value. For possible values, see ",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.documentation/documentation/SwiftUI/PencilPreferredAction",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": ".",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                },
                {
                  "code": [
                    "@Environment(\\.preferredPencilSqueezeAction) private var preferredAction"
                  ],
                  "syntax": "swift",
                  "type": "codeListing"
                }
              ],
              "title": "SwiftUI"
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "To check the preferred action, use the ",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.documentation/documentation/UIKit/UIPencilInteraction/preferredSqueezeAction",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": " class property on ",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.documentation/documentation/UIKit/UIPencilInteraction",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": ". For possible values, see ",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.documentation/documentation/UIKit/UIPencilPreferredAction",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": ".",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                },
                {
                  "code": [
                    "UIPencilInteraction.preferredSqueezeAction"
                  ],
                  "syntax": "swift",
                  "type": "codeListing"
                }
              ],
              "title": "UIKit"
            }
          ],
          "type": "tabNavigator"
        },
        {
          "anchor": "Choose-the-action-to-perform",
          "level": 3,
          "text": "Choose the action to perform",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "When possible, perform the preferred action to provide a consistent user experience across apps that support squeezes.",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "If the preferred action doesn’t make sense in your app, consider giving people a way to specify a custom action that’s suitable for your app.",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "For design guidance, read Human Interface Guidelines > Apple Pencil and Scribble > ",
              "type": "text"
            },
            {
              "identifier": "https://developer.apple.com/design/human-interface-guidelines/apple-pencil-and-scribble#Squeeze",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ".",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "The following code shows a snippet from a drawing app that provides custom drawing tools.",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "This app allows a person to configure a custom action to quickly swap to their favorite custom drawing tool instead of using the systemwide preferred action for squeezes.",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "This app also supports the preferred actions to ignore squeezes, switch to the previous tool, and show a custom contextual palette near the Apple Pencil Pro tip.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "tabs": [
            {
              "content": [
                {
                  "code": [
                    "enum Tool {",
                    "    case brush",
                    "    case lasso",
                    "    case eraser",
                    "    case magnifier",
                    "}",
                    "",
                    "enum CustomAction: String {",
                    "    case switchLasso",
                    "    case switchMagnifier",
                    "}",
                    "",
                    "@State private var currentTool: Tool? = .brush",
                    "@State private var previousTool: Tool?",
                    "@State private var contextualPalettePresented = false",
                    "@State private var contextualPaletteAnchor: PopoverAttachmentAnchor?",
                    "",
                    "@Environment(\\.preferredPencilSqueezeAction) private var preferredAction",
                    "@AppStorage(\"customPencilSqueezeAction\") private var customAction: CustomAction?",
                    "",
                    "var body: some View {",
                    "    MyView()",
                    "        .onPencilSqueeze { phase in",
                    "            // Respect the systemwide preferred action to ignore squeezes.",
                    "            guard preferredAction != .ignore else { return }",
                    "            ",
                    "            // If the person chooses to override the systemwide",
                    "            // squeeze action to perform a custom action in this app,",
                    "            // check which custom action they prefer and perform that action.",
                    "            if let customAction, case let .ended(value) = phase {",
                    "                if customAction == .switchLasso, currentTool != .lasso {",
                    "                    (currentTool, previousTool) = (.lasso, currentTool)",
                    "                }",
                    "                else if customAction == .switchMagnifier, currentTool != .magnifier {",
                    "                    (currentTool, previousTool) = (.magnifier, currentTool)",
                    "                }",
                    "            }",
                    "            ",
                    "            // If the person prefers to use the systemwide squeeze action,",
                    "            // perform the actions that are appropriate in the context of this app:",
                    "            // show a custom palette near the Apple Pencil Pro tip, or switch to the previous tool.",
                    "            if preferredAction == .showContextualPalette, case let .ended(value) = phase {",
                    "                if let anchorPoint = value.hoverPose?.anchor {",
                    "                    contextualPaletteAnchor = .point(anchorPoint)",
                    "                }",
                    "                contextualPalettePresented = true",
                    "            }",
                    "            else if preferredAction == .switchPrevious, case let .ended(value) = phase {",
                    "                (currentTool, previousTool) = (previousTool, currentTool)",
                    "            }",
                    "        }",
                    "        .popover(",
                    "            isPresented: $contextualPalettePresented,",
                    "            attachmentAnchor: contextualPaletteAnchor ?? .point(.center)",
                    "        ) {",
                    "            MyContextualPalette()",
                    "        }",
                    "}"
                  ],
                  "syntax": "swift",
                  "type": "codeListing"
                }
              ],
              "title": "SwiftUI"
            },
            {
              "content": [
                {
                  "code": [
                    "enum Tool {",
                    "    case brush",
                    "    case lasso",
                    "    case eraser",
                    "    case magnifier",
                    "}",
                    "",
                    "enum CustomAction {",
                    "    case switchLasso",
                    "    case switchMagnifier",
                    "}",
                    "",
                    "private var currentTool: Tool? = .brush",
                    "private var previousTool: Tool?",
                    "private var customAction: CustomAction?",
                    "",
                    "override func viewDidLoad() {",
                    "    super.viewDidLoad()",
                    "    ",
                    "    // Register for a squeeze.",
                    "    let pencilInteraction = UIPencilInteraction(delegate: self)",
                    "    view.addInteraction(pencilInteraction)",
                    "}",
                    "",
                    "func pencilInteraction(_ interaction: UIPencilInteraction,",
                    "                   didReceiveSqueeze squeeze: UIPencilInteraction.Squeeze) {",
                    "    let preferredAction = UIPencilInteraction.preferredSqueezeAction",
                    "    ",
                    "    // Respect the systemwide preferred action to ignore squeezes.",
                    "    guard preferredAction != .ignore else { return }",
                    "    ",
                    "    // If the person chooses to override the systemwide",
                    "    // squeeze action to perform a custom action in this app,",
                    "    // check which custom action they prefer and perform that action.",
                    "    if let customAction, squeeze.phase == .ended {",
                    "        if customAction == .switchLasso, currentTool != .lasso {",
                    "            (currentTool, previousTool) = (.lasso, currentTool)",
                    "        }",
                    "        else if customAction == .switchMagnifier, currentTool != .magnifier {",
                    "            (currentTool, previousTool) = (.magnifier, currentTool)",
                    "        }",
                    "    }",
                    "    ",
                    "    // If the person prefers to use the systemwide squeeze action,",
                    "    // perform the actions that are appropriate in the context of this app:",
                    "    // show a custom palette near the Apple Pencil Pro tip, or switch to the previous tool.",
                    "    if preferredAction == .showContextualPalette, squeeze.phase == .ended {",
                    "        if let anchorPoint = squeeze.hoverPose?.location {",
                    "            presentContextualPalette(atLocation: anchorPoint)",
                    "        }",
                    "    }",
                    "    else if preferredAction == .switchPrevious, squeeze.phase == .ended {",
                    "        (currentTool, previousTool) = (previousTool, currentTool)",
                    "    }",
                    "}"
                  ],
                  "syntax": "swift",
                  "type": "codeListing"
                }
              ],
              "title": "UIKit"
            }
          ],
          "type": "tabNavigator"
        },
        {
          "columns": [
            {
              "content": [
                {
                  "anchor": "See-Also",
                  "level": 2,
                  "text": "See Also",
                  "type": "heading"
                }
              ],
              "size": 1
            }
          ],
          "numberOfColumns": 1,
          "type": "row"
        },
        {
          "anchor": "Related-articles",
          "level": 4,
          "text": "Related articles",
          "type": "heading"
        },
        {
          "items": [
            "doc://com.apple.ApplePencil/documentation/ApplePencil/handling-double-taps-from-apple-pencil"
          ],
          "style": "list",
          "type": "links"
        },
        {
          "anchor": "Related-reference-in-SwiftUI",
          "level": 4,
          "text": "Related reference in SwiftUI",
          "type": "heading"
        },
        {
          "items": [
            "doc://com.apple.documentation/documentation/SwiftUI/View/onPencilSqueeze(perform:)",
            "doc://com.apple.documentation/documentation/SwiftUI/PencilSqueezeGesturePhase",
            "doc://com.apple.documentation/documentation/SwiftUI/PencilSqueezeGestureValue",
            "doc://com.apple.documentation/documentation/SwiftUI/PencilPreferredAction",
            "doc://com.apple.documentation/documentation/SwiftUI/PencilHoverPose"
          ],
          "style": "list",
          "type": "links"
        },
        {
          "anchor": "Related-reference-in-UIKit",
          "level": 4,
          "text": "Related reference in UIKit",
          "type": "heading"
        },
        {
          "items": [
            "doc://com.apple.documentation/documentation/UIKit/UIPencilInteraction",
            "doc://com.apple.documentation/documentation/UIKit/UIPencilInteractionDelegate",
            "doc://com.apple.documentation/documentation/UIKit/UIPencilInteraction/Squeeze",
            "doc://com.apple.documentation/documentation/UIKit/UIPencilInteraction/Phase",
            "doc://com.apple.documentation/documentation/UIKit/UIPencilHoverPose"
          ],
          "style": "list",
          "type": "links"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "apple-pencil-squeeze": {
      "alt": "An illustration showing a hand squeezing Apple Pencil near the tip.",
      "identifier": "apple-pencil-squeeze",
      "type": "image",
      "variants": [
        {
          "traits": [
            "2x",
            "light"
          ],
          "url": "https://docs-assets.developer.apple.com/published/7d3dbec5d663bd982e3a4b95467f91c7/apple-pencil-squeeze@2x.png"
        },
        {
          "traits": [
            "2x",
            "dark"
          ],
          "url": "https://docs-assets.developer.apple.com/published/cda0a883d951a438b74fbc6a25b440ed/apple-pencil-squeeze~dark@2x.png"
        }
      ]
    },
    "doc://com.apple.ApplePencil/documentation/ApplePencil": {
      "abstract": [
        {
          "text": "Enhance your iPad app’s user experience by supporting drawing, handwriting, and other features of Apple Pencil.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.ApplePencil/documentation/ApplePencil",
      "kind": "article",
      "role": "collection",
      "title": "Apple Pencil",
      "type": "topic",
      "url": "/documentation/applepencil"
    },
    "doc://com.apple.ApplePencil/documentation/ApplePencil/handling-double-taps-from-apple-pencil": {
      "abstract": [
        {
          "text": "Detect and respond to double taps a person makes on Apple Pencil.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.ApplePencil/documentation/ApplePencil/handling-double-taps-from-apple-pencil",
      "kind": "article",
      "role": "article",
      "title": "Handling double taps from Apple Pencil",
      "type": "topic",
      "url": "/documentation/applepencil/handling-double-taps-from-apple-pencil"
    },
    "doc://com.apple.documentation/documentation/SwiftUI/EnvironmentValues/preferredPencilSqueezeAction": {
      "abstract": [
        {
          "text": "The action that the user prefers to perform when squeezing their Apple Pencil, as selected in the Settings app.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "preferredPencilSqueezeAction"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:7SwiftUI21PencilPreferredActionV",
          "text": "PencilPreferredAction"
        },
        {
          "kind": "text",
          "text": " { "
        },
        {
          "kind": "keyword",
          "text": "get"
        },
        {
          "kind": "text",
          "text": " }"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/SwiftUI/EnvironmentValues/preferredPencilSqueezeAction",
      "kind": "symbol",
      "role": "symbol",
      "title": "preferredPencilSqueezeAction",
      "type": "topic",
      "url": "/documentation/SwiftUI/EnvironmentValues/preferredPencilSqueezeAction"
    },
    "doc://com.apple.documentation/documentation/SwiftUI/PencilHoverPose": {
      "abstract": [
        {
          "text": "A value describing the location and distance of an Apple Pencil hovering in the area above a view’s bounds.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "PencilHoverPose"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/SwiftUI/PencilHoverPose",
      "kind": "symbol",
      "role": "symbol",
      "title": "PencilHoverPose",
      "type": "topic",
      "url": "/documentation/SwiftUI/PencilHoverPose"
    },
    "doc://com.apple.documentation/documentation/SwiftUI/PencilPreferredAction": {
      "abstract": [
        {
          "text": "An action that the user prefers to perform after double-tapping their Apple Pencil.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "PencilPreferredAction"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/SwiftUI/PencilPreferredAction",
      "kind": "symbol",
      "role": "symbol",
      "title": "PencilPreferredAction",
      "type": "topic",
      "url": "/documentation/SwiftUI/PencilPreferredAction"
    },
    "doc://com.apple.documentation/documentation/SwiftUI/PencilSqueezeGesturePhase": {
      "abstract": [
        {
          "text": "Describes the phase and value of an Apple Pencil squeeze gesture.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@frozen"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "PencilSqueezeGesturePhase"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/SwiftUI/PencilSqueezeGesturePhase",
      "kind": "symbol",
      "role": "symbol",
      "title": "PencilSqueezeGesturePhase",
      "type": "topic",
      "url": "/documentation/SwiftUI/PencilSqueezeGesturePhase"
    },
    "doc://com.apple.documentation/documentation/SwiftUI/PencilSqueezeGestureValue": {
      "abstract": [
        {
          "text": "Describes the value of an Apple Pencil squeeze gesture.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "PencilSqueezeGestureValue"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/SwiftUI/PencilSqueezeGestureValue",
      "kind": "symbol",
      "role": "symbol",
      "title": "PencilSqueezeGestureValue",
      "type": "topic",
      "url": "/documentation/SwiftUI/PencilSqueezeGestureValue"
    },
    "doc://com.apple.documentation/documentation/SwiftUI/View/onPencilSqueeze(perform:)": {
      "abstract": [
        {
          "text": "Adds an action to perform when the user squeezes their Apple Pencil.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "nonisolated"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "onPencilSqueeze"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "perform"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "internalParam",
          "text": "action"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "keyword",
          "text": "@escaping"
        },
        {
          "kind": "text",
          "text": " ("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:7SwiftUI25PencilSqueezeGesturePhaseO",
          "text": "PencilSqueezeGesturePhase"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s4Voida",
          "text": "Void"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "keyword",
          "text": "some"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:7SwiftUI4ViewP",
          "text": "View"
        },
        {
          "kind": "text",
          "text": "\n"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/SwiftUI/View/onPencilSqueeze(perform:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "onPencilSqueeze(perform:)",
      "type": "topic",
      "url": "/documentation/SwiftUI/View/onPencilSqueeze(perform:)"
    },
    "doc://com.apple.documentation/documentation/UIKit/UIPencilHoverPose": {
      "abstract": [
        {
          "text": "An object that describes the hover pose of Apple Pencil during an interaction like double tap or squeeze.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@"
        },
        {
          "kind": "attribute",
          "preciseIdentifier": "s:ScM",
          "text": "MainActor"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UIPencilHoverPose"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/UIKit/UIPencilHoverPose",
      "kind": "symbol",
      "role": "symbol",
      "title": "UIPencilHoverPose",
      "type": "topic",
      "url": "/documentation/UIKit/UIPencilHoverPose"
    },
    "doc://com.apple.documentation/documentation/UIKit/UIPencilInteraction": {
      "abstract": [
        {
          "text": "An interaction that tells your app when a person double-taps or squeezes Apple Pencil.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@"
        },
        {
          "kind": "attribute",
          "preciseIdentifier": "s:ScM",
          "text": "MainActor"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UIPencilInteraction"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/UIKit/UIPencilInteraction",
      "kind": "symbol",
      "role": "symbol",
      "title": "UIPencilInteraction",
      "type": "topic",
      "url": "/documentation/UIKit/UIPencilInteraction"
    },
    "doc://com.apple.documentation/documentation/UIKit/UIPencilInteraction/Phase": {
      "abstract": [
        {
          "text": "Constants that describe the phases of an interaction on Apple Pencil.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Phase"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/UIKit/UIPencilInteraction/Phase",
      "kind": "symbol",
      "role": "symbol",
      "title": "UIPencilInteraction.Phase",
      "type": "topic",
      "url": "/documentation/UIKit/UIPencilInteraction/Phase"
    },
    "doc://com.apple.documentation/documentation/UIKit/UIPencilInteraction/Squeeze": {
      "abstract": [
        {
          "text": "An interaction that represents a squeeze on Apple Pencil.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@"
        },
        {
          "kind": "attribute",
          "preciseIdentifier": "s:ScM",
          "text": "MainActor"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Squeeze"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/UIKit/UIPencilInteraction/Squeeze",
      "kind": "symbol",
      "role": "symbol",
      "title": "UIPencilInteraction.Squeeze",
      "type": "topic",
      "url": "/documentation/UIKit/UIPencilInteraction/Squeeze"
    },
    "doc://com.apple.documentation/documentation/UIKit/UIPencilInteraction/preferredSqueezeAction": {
      "abstract": [
        {
          "text": "A person’s preferred squeeze action for Apple Pencil, as specified in the Settings app.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@"
        },
        {
          "kind": "attribute",
          "preciseIdentifier": "s:ScM",
          "text": "MainActor"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "preferredSqueezeAction"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@UIPencilPreferredAction",
          "text": "UIPencilPreferredAction"
        },
        {
          "kind": "text",
          "text": " { "
        },
        {
          "kind": "keyword",
          "text": "get"
        },
        {
          "kind": "text",
          "text": " }"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/UIKit/UIPencilInteraction/preferredSqueezeAction",
      "kind": "symbol",
      "role": "symbol",
      "title": "preferredSqueezeAction",
      "type": "topic",
      "url": "/documentation/UIKit/UIPencilInteraction/preferredSqueezeAction"
    },
    "doc://com.apple.documentation/documentation/UIKit/UIPencilInteractionDelegate": {
      "abstract": [
        {
          "text": "The interface an object implements to handle double taps or squeezes a person makes on Apple Pencil.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@"
        },
        {
          "kind": "attribute",
          "preciseIdentifier": "s:ScM",
          "text": "MainActor"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UIPencilInteractionDelegate"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(pl)NSObject",
          "text": "NSObjectProtocol"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/UIKit/UIPencilInteractionDelegate",
      "kind": "symbol",
      "role": "symbol",
      "title": "UIPencilInteractionDelegate",
      "type": "topic",
      "url": "/documentation/UIKit/UIPencilInteractionDelegate"
    },
    "doc://com.apple.documentation/documentation/UIKit/UIPencilPreferredAction": {
      "abstract": [
        {
          "text": "The actions Apple Pencil can perform after a person performs a double tap or squeeze.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UIPencilPreferredAction"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/UIKit/UIPencilPreferredAction",
      "kind": "symbol",
      "role": "symbol",
      "title": "UIPencilPreferredAction",
      "type": "topic",
      "url": "/documentation/UIKit/UIPencilPreferredAction"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "https://developer.apple.com/design/human-interface-guidelines/apple-pencil-and-scribble#Squeeze": {
      "identifier": "https://developer.apple.com/design/human-interface-guidelines/apple-pencil-and-scribble#Squeeze",
      "title": "Squeeze",
      "titleInlineContent": [
        {
          "text": "Squeeze",
          "type": "text"
        }
      ],
      "type": "link",
      "url": "https://developer.apple.com/design/human-interface-guidelines/apple-pencil-and-scribble#Squeeze"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1UIKit~1UIPencilInteraction~1preferredSqueezeAction/fragments",
          "value": [
            {
              "kind": "keyword",
              "text": "@property"
            },
            {
              "kind": "text",
              "text": " ("
            },
            {
              "kind": "keyword",
              "text": "class"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "kind": "keyword",
              "text": "nonatomic"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "kind": "keyword",
              "text": "readonly"
            },
            {
              "kind": "text",
              "text": ") "
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@E@UIPencilPreferredAction",
              "text": "UIPencilPreferredAction"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "preferredSqueezeAction"
            },
            {
              "kind": "text",
              "text": ";"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1UIKit~1UIPencilInteraction~1Phase/title",
          "value": "UIPencilInteractionPhase"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1UIKit~1UIPencilInteraction~1Phase/fragments",
          "value": [
            {
              "kind": "keyword",
              "text": "enum"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "UIPencilInteractionPhase"
            },
            {
              "kind": "text",
              "text": " : "
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@NSUInteger",
              "text": "NSUInteger"
            },
            {
              "kind": "text",
              "text": ";"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1UIKit~1UIPencilHoverPose/fragments",
          "value": [
            {
              "kind": "keyword",
              "text": "@interface"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "UIPencilHoverPose"
            },
            {
              "kind": "text",
              "text": " : "
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)NSObject",
              "text": "NSObject"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1UIKit~1UIPencilInteraction~1Squeeze/title",
          "value": "UIPencilInteractionSqueeze"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1UIKit~1UIPencilInteraction~1Squeeze/fragments",
          "value": [
            {
              "kind": "keyword",
              "text": "@interface"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "UIPencilInteractionSqueeze"
            },
            {
              "kind": "text",
              "text": " : "
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)NSObject",
              "text": "NSObject"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1UIKit~1UIPencilPreferredAction/fragments",
          "value": [
            {
              "kind": "keyword",
              "text": "enum"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "UIPencilPreferredAction"
            },
            {
              "kind": "text",
              "text": " : "
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@NSInteger",
              "text": "NSInteger"
            },
            {
              "kind": "text",
              "text": ";"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1UIKit~1UIPencilInteractionDelegate/fragments",
          "value": [
            {
              "kind": "keyword",
              "text": "@protocol"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "UIPencilInteractionDelegate"
            },
            {
              "kind": "text",
              "text": " <"
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(pl)NSObject",
              "text": "NSObject"
            },
            {
              "kind": "text",
              "text": ">"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1UIKit~1UIPencilInteraction/fragments",
          "value": [
            {
              "kind": "keyword",
              "text": "@interface"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "UIPencilInteraction"
            },
            {
              "kind": "text",
              "text": " : "
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)NSObject",
              "text": "NSObject"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
