{
  "abstract": [
    {
      "text": "An optical drive source such as a CD or DVD.",
      "type": "text"
    }
  ],
  "deprecationSummary": [
    {
      "inlineContent": [
        {
          "text": "This intent is no longer available. You may define a custom intent instead. For more information, see ",
          "type": "text"
        },
        {
          "identifier": "https://developer.apple.com/support/deprecated-sirikit-intent-domains",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": ".",
          "type": "text"
        }
      ],
      "type": "paragraph"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.sirikit/documentation/Intents",
        "doc://com.apple.sirikit/documentation/Intents/INCarAudioSource"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.sirikit/documentation/Intents/INCarAudioSource/sourceOpticalDrive"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@INCarAudioSource@INCarAudioSourceOpticalDrive",
    "fragments": [
      {
        "kind": "keyword",
        "text": "case"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "sourceOpticalDrive"
      }
    ],
    "modules": [
      {
        "name": "Intents"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "INCarAudioSourceOpticalDrive"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "15.0",
        "introducedAt": "10.0",
        "message": "INCarAudioSource is deprecated. There is no replacement.",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "15.0",
        "introducedAt": "10.0",
        "message": "INCarAudioSource is deprecated. There is no replacement.",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "15.0",
        "introducedAt": "13.1",
        "message": "INCarAudioSource is deprecated. There is no replacement.",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "1.0",
        "introducedAt": "1.0",
        "message": "INCarAudioSource is deprecated. There is no replacement.",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Case",
    "symbolKind": "case",
    "title": "INCarAudioSource.sourceOpticalDrive"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "case"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "sourceOpticalDrive"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.sirikit/documentation/Intents": {
      "abstract": [
        {
          "text": "Empower people to customize interactions for your app on their device.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents",
      "kind": "symbol",
      "role": "collection",
      "title": "Intents",
      "type": "topic",
      "url": "/documentation/intents"
    },
    "doc://com.apple.sirikit/documentation/Intents/INCarAudioSource": {
      "abstract": [
        {
          "text": "Constants indicating the source of audio.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "INCarAudioSource"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INCarAudioSource",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INCarAudioSource"
        }
      ],
      "role": "symbol",
      "title": "INCarAudioSource",
      "type": "topic",
      "url": "/documentation/intents/incaraudiosource"
    },
    "doc://com.apple.sirikit/documentation/Intents/INCarAudioSource/sourceAUX": {
      "abstract": [
        {
          "text": "A source connected through an auxiliary jack.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "sourceAUX"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INCarAudioSource/sourceAUX",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INCarAudioSourceAUX"
        }
      ],
      "role": "symbol",
      "title": "INCarAudioSource.sourceAUX",
      "type": "topic",
      "url": "/documentation/intents/incaraudiosource/sourceaux"
    },
    "doc://com.apple.sirikit/documentation/Intents/INCarAudioSource/sourceBluetooth": {
      "abstract": [
        {
          "text": "A source connected over Bluetooth.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "sourceBluetooth"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INCarAudioSource/sourceBluetooth",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INCarAudioSourceBluetooth"
        }
      ],
      "role": "symbol",
      "title": "INCarAudioSource.sourceBluetooth",
      "type": "topic",
      "url": "/documentation/intents/incaraudiosource/sourcebluetooth"
    },
    "doc://com.apple.sirikit/documentation/Intents/INCarAudioSource/sourceCarPlay": {
      "abstract": [
        {
          "text": "A CarPlay source.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "sourceCarPlay"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INCarAudioSource/sourceCarPlay",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INCarAudioSourceCarPlay"
        }
      ],
      "role": "symbol",
      "title": "INCarAudioSource.sourceCarPlay",
      "type": "topic",
      "url": "/documentation/intents/incaraudiosource/sourcecarplay"
    },
    "doc://com.apple.sirikit/documentation/Intents/INCarAudioSource/sourceHardDrive": {
      "abstract": [
        {
          "text": "A hard drive source.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "sourceHardDrive"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INCarAudioSource/sourceHardDrive",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INCarAudioSourceHardDrive"
        }
      ],
      "role": "symbol",
      "title": "INCarAudioSource.sourceHardDrive",
      "type": "topic",
      "url": "/documentation/intents/incaraudiosource/sourceharddrive"
    },
    "doc://com.apple.sirikit/documentation/Intents/INCarAudioSource/sourceMemoryCard": {
      "abstract": [
        {
          "text": "A memory card source.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "sourceMemoryCard"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INCarAudioSource/sourceMemoryCard",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INCarAudioSourceMemoryCard"
        }
      ],
      "role": "symbol",
      "title": "INCarAudioSource.sourceMemoryCard",
      "type": "topic",
      "url": "/documentation/intents/incaraudiosource/sourcememorycard"
    },
    "doc://com.apple.sirikit/documentation/Intents/INCarAudioSource/sourceOpticalDrive": {
      "abstract": [
        {
          "text": "An optical drive source such as a CD or DVD.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "sourceOpticalDrive"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INCarAudioSource/sourceOpticalDrive",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INCarAudioSourceOpticalDrive"
        }
      ],
      "role": "symbol",
      "title": "INCarAudioSource.sourceOpticalDrive",
      "type": "topic",
      "url": "/documentation/intents/incaraudiosource/sourceopticaldrive"
    },
    "doc://com.apple.sirikit/documentation/Intents/INCarAudioSource/sourceRadio": {
      "abstract": [
        {
          "text": "A radio source.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "sourceRadio"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INCarAudioSource/sourceRadio",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INCarAudioSourceRadio"
        }
      ],
      "role": "symbol",
      "title": "INCarAudioSource.sourceRadio",
      "type": "topic",
      "url": "/documentation/intents/incaraudiosource/sourceradio"
    },
    "doc://com.apple.sirikit/documentation/Intents/INCarAudioSource/sourceUSB": {
      "abstract": [
        {
          "text": "A source connected through a USB plug.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "sourceUSB"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INCarAudioSource/sourceUSB",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INCarAudioSourceUSB"
        }
      ],
      "role": "symbol",
      "title": "INCarAudioSource.sourceUSB",
      "type": "topic",
      "url": "/documentation/intents/incaraudiosource/sourceusb"
    },
    "doc://com.apple.sirikit/documentation/Intents/INCarAudioSource/sourceUnknown": {
      "abstract": [
        {
          "text": "An unknown source.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "sourceUnknown"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INCarAudioSource/sourceUnknown",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INCarAudioSourceUnknown"
        }
      ],
      "role": "symbol",
      "title": "INCarAudioSource.sourceUnknown",
      "type": "topic",
      "url": "/documentation/intents/incaraudiosource/sourceunknown"
    },
    "doc://com.apple.sirikit/documentation/Intents/INCarAudioSource/sourceiPod": {
      "abstract": [
        {
          "text": "An iPod source.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "sourceiPod"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INCarAudioSource/sourceiPod",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INCarAudioSourceiPod"
        }
      ],
      "role": "symbol",
      "title": "INCarAudioSource.sourceiPod",
      "type": "topic",
      "url": "/documentation/intents/incaraudiosource/sourceipod"
    },
    "https://developer.apple.com/support/deprecated-sirikit-intent-domains": {
      "identifier": "https://developer.apple.com/support/deprecated-sirikit-intent-domains",
      "title": "Deprecated SiriKit Intent Domains",
      "titleInlineContent": [
        {
          "text": "Deprecated SiriKit Intent Domains",
          "type": "text"
        }
      ],
      "type": "link",
      "url": "https://developer.apple.com/support/deprecated-sirikit-intent-domains"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Constants",
      "generated": true,
      "identifiers": [
        "doc://com.apple.sirikit/documentation/Intents/INCarAudioSource/sourceUnknown",
        "doc://com.apple.sirikit/documentation/Intents/INCarAudioSource/sourceCarPlay",
        "doc://com.apple.sirikit/documentation/Intents/INCarAudioSource/sourceiPod",
        "doc://com.apple.sirikit/documentation/Intents/INCarAudioSource/sourceRadio",
        "doc://com.apple.sirikit/documentation/Intents/INCarAudioSource/sourceBluetooth",
        "doc://com.apple.sirikit/documentation/Intents/INCarAudioSource/sourceAUX",
        "doc://com.apple.sirikit/documentation/Intents/INCarAudioSource/sourceUSB",
        "doc://com.apple.sirikit/documentation/Intents/INCarAudioSource/sourceMemoryCard",
        "doc://com.apple.sirikit/documentation/Intents/INCarAudioSource/sourceHardDrive"
      ],
      "title": "Constants"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "deprecatedAt": "15.0",
              "introducedAt": "10.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "deprecatedAt": "15.0",
              "introducedAt": "10.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "deprecatedAt": "15.0",
              "introducedAt": "13.1",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "deprecatedAt": "1.0",
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration Case"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "INCarAudioSourceOpticalDrive"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "case"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INCarAudioSourceOpticalDrive"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.sirikit/documentation/Intents",
                "doc://com.apple.sirikit/documentation/Intents/INCarAudioSource"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Constants",
              "generated": true,
              "identifiers": [
                "doc://com.apple.sirikit/documentation/Intents/INCarAudioSource/sourceUnknown",
                "doc://com.apple.sirikit/documentation/Intents/INCarAudioSource/sourceCarPlay",
                "doc://com.apple.sirikit/documentation/Intents/INCarAudioSource/sourceiPod",
                "doc://com.apple.sirikit/documentation/Intents/INCarAudioSource/sourceRadio",
                "doc://com.apple.sirikit/documentation/Intents/INCarAudioSource/sourceBluetooth",
                "doc://com.apple.sirikit/documentation/Intents/INCarAudioSource/sourceAUX",
                "doc://com.apple.sirikit/documentation/Intents/INCarAudioSource/sourceUSB",
                "doc://com.apple.sirikit/documentation/Intents/INCarAudioSource/sourceMemoryCard",
                "doc://com.apple.sirikit/documentation/Intents/INCarAudioSource/sourceHardDrive"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "identifier",
                    "text": "INCarAudioSourceOpticalDrive"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/deprecationSummary",
          "value": [
            {
              "inlineContent": [
                {
                  "text": "This intent is no longer available. You may define a custom intent instead. For more information, see ",
                  "type": "text"
                },
                {
                  "identifier": "https://developer.apple.com/support/deprecated-sirikit-intent-domains",
                  "isActive": true,
                  "type": "reference"
                },
                {
                  "text": ".",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INCarAudioSource~1sourceBluetooth/title",
          "value": "INCarAudioSourceBluetooth"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INCarAudioSource~1sourceBluetooth/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INCarAudioSourceBluetooth"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INCarAudioSource~1sourceMemoryCard/title",
          "value": "INCarAudioSourceMemoryCard"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INCarAudioSource~1sourceMemoryCard/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INCarAudioSourceMemoryCard"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INCarAudioSource~1sourceCarPlay/title",
          "value": "INCarAudioSourceCarPlay"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INCarAudioSource~1sourceCarPlay/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INCarAudioSourceCarPlay"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INCarAudioSource~1sourceUSB/title",
          "value": "INCarAudioSourceUSB"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INCarAudioSource~1sourceUSB/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INCarAudioSourceUSB"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INCarAudioSource~1sourceHardDrive/title",
          "value": "INCarAudioSourceHardDrive"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INCarAudioSource~1sourceHardDrive/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INCarAudioSourceHardDrive"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INCarAudioSource~1sourceUnknown/title",
          "value": "INCarAudioSourceUnknown"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INCarAudioSource~1sourceUnknown/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INCarAudioSourceUnknown"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INCarAudioSource/title",
          "value": "INCarAudioSource"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INCarAudioSource/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INCarAudioSource"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INCarAudioSource/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "INCarAudioSource"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INCarAudioSource~1sourceiPod/title",
          "value": "INCarAudioSourceiPod"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INCarAudioSource~1sourceiPod/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INCarAudioSourceiPod"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INCarAudioSource~1sourceOpticalDrive/title",
          "value": "INCarAudioSourceOpticalDrive"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INCarAudioSource~1sourceOpticalDrive/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INCarAudioSourceOpticalDrive"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INCarAudioSource~1sourceAUX/title",
          "value": "INCarAudioSourceAUX"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INCarAudioSource~1sourceAUX/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INCarAudioSourceAUX"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INCarAudioSource~1sourceRadio/title",
          "value": "INCarAudioSourceRadio"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INCarAudioSource~1sourceRadio/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INCarAudioSourceRadio"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/intents/incaraudiosource/sourceopticaldrive"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/intents/incaraudiosource/sourceopticaldrive"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
