{"metadata":{"title":"keyboardType","symbolKind":"property","modules":[{"name":"UIKit"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"keyboardType"}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"keyboardType"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@E@UIKeyboardType","text":"UIKeyboardType"}],"platforms":[{"beta":false,"deprecated":false,"unavailable":false,"name":"iOS"},{"beta":false,"deprecated":false,"unavailable":false,"name":"iPadOS"},{"beta":false,"deprecated":false,"unavailable":false,"name":"Mac Catalyst"},{"beta":false,"deprecated":false,"unavailable":false,"name":"tvOS"},{"beta":false,"deprecated":false,"unavailable":false,"name":"visionOS"}],"roleHeading":"Instance Property","externalID":"c:objc(pl)UITextInputTraits(py)keyboardType"},"abstract":[{"text":"The keyboard type for the text object.","type":"text"}],"schemaVersion":{"major":0,"minor":3,"patch":0},"hierarchy":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.uikit/documentation/UIKit","doc://com.apple.uikit/documentation/UIKit/UITextInputTraits"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"@","kind":"attribute"},{"text":"MainActor","kind":"attribute","identifier":"doc://com.externally.resolved.symbol/s:ScM","preciseIdentifier":"s:ScM"},{"text":" ","kind":"text"},{"text":"optional","kind":"keyword"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"keyboardType","kind":"identifier"},{"text":": ","kind":"text"},{"text":"UIKeyboardType","kind":"typeIdentifier","identifier":"doc://com.apple.uikit/documentation/UIKit/UIKeyboardType","preciseIdentifier":"c:@E@UIKeyboardType"},{"text":" { ","kind":"text"},{"text":"get","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"set"},{"kind":"text","text":" }"}],"languages":["swift"],"platforms":["iOS","iPadOS","Mac Catalyst","tvOS","visionOS"]}]},{"mentions":["doc://com.apple.uikit/documentation/UIKit/configuring-a-custom-keyboard-interface"],"kind":"mentions"},{"content":[{"text":"Discussion","type":"heading","anchor":"Discussion","level":2},{"type":"paragraph","inlineContent":[{"type":"text","text":"Text objects can be targeted for specific types of input, such as plain text, email, numeric entry, and so on. The keyboard style identifies what keys are available on the keyboard and which ones appear by default. The default value for this property is "},{"type":"reference","isActive":true,"identifier":"doc://com.apple.uikit/documentation/UIKit/UIKeyboardType/default"},{"type":"text","text":"."}]}],"kind":"content"}],"kind":"symbol","sections":[],"identifier":{"url":"doc://com.apple.uikit/documentation/UIKit/UITextInputTraits/keyboardType","interfaceLanguage":"swift"},"seeAlsoSections":[{"anchor":"Configuring-the-keyboard-appearance","identifiers":["doc://com.apple.uikit/documentation/UIKit/UIKeyboardType","doc://com.apple.uikit/documentation/UIKit/UITextInputTraits/keyboardAppearance","doc://com.apple.uikit/documentation/UIKit/UIKeyboardAppearance","doc://com.apple.uikit/documentation/UIKit/UITextInputTraits/returnKeyType","doc://com.apple.uikit/documentation/UIKit/UIReturnKeyType","doc://com.apple.uikit/documentation/UIKit/UITextInputTraits/textContentType","doc://com.apple.uikit/documentation/UIKit/UITextContentType"],"generated":true,"title":"Configuring the keyboard appearance"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["/documentation/uikit/uitextinputtraits/keyboardtype"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["/documentation/uikit/uitextinputtraits/keyboardtype"]}],"references":{"doc://com.externally.resolved.symbol/s:ScM":{"abstract":[{"text":"A singleton actor whose executor is equivalent to the main dispatch queue.","type":"text"}],"url":"/documentation/Swift/MainActor","identifier":"doc://com.externally.resolved.symbol/s:ScM","title":"MainActor","fragments":[{"text":"@globalActor","kind":"attribute"},{"text":" ","kind":"text"},{"text":"final","kind":"keyword"},{"text":" ","kind":"text"},{"text":"actor","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MainActor","kind":"identifier"}],"type":"topic","kind":"symbol","role":"symbol"},"doc://com.apple.uikit/documentation/UIKit/UIReturnKeyType":{"url":"/documentation/uikit/uireturnkeytype","abstract":[{"type":"text","text":"Constants that specify the text string that displays in the Return key of a keyboard."}],"type":"topic","kind":"symbol","role":"symbol","identifier":"doc://com.apple.uikit/documentation/UIKit/UIReturnKeyType","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"UIReturnKeyType"}],"navigatorTitle":[{"kind":"identifier","text":"UIReturnKeyType"}],"title":"UIReturnKeyType"},"doc://com.apple.uikit/documentation/UIKit/UITextInputTraits/returnKeyType":{"abstract":[{"type":"text","text":"The visible title of the Return key."}],"navigatorTitle":[{"text":"returnKeyType","kind":"identifier"}],"type":"topic","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"returnKeyType","kind":"identifier"},{"text":": ","kind":"text"},{"text":"UIReturnKeyType","preciseIdentifier":"c:@E@UIReturnKeyType","kind":"typeIdentifier"}],"role":"symbol","identifier":"doc://com.apple.uikit/documentation/UIKit/UITextInputTraits/returnKeyType","url":"/documentation/uikit/uitextinputtraits/returnkeytype","kind":"symbol","title":"returnKeyType"},"doc://com.apple.documentation/documentation/technologies":{"role":"overview","url":"/documentation/technologies","title":"Technologies","identifier":"doc://com.apple.documentation/documentation/technologies","abstract":[{"text":"","type":"text"}],"kind":"technologies","type":"topic"},"doc://com.apple.uikit/documentation/UIKit/UIKeyboardType":{"role":"symbol","abstract":[{"text":"Constants that specify the type of keyboard to display for a text-based view.","type":"text"}],"url":"/documentation/uikit/uikeyboardtype","type":"topic","fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"kind":"identifier","text":"UIKeyboardType"}],"title":"UIKeyboardType","navigatorTitle":[{"kind":"identifier","text":"UIKeyboardType"}],"identifier":"doc://com.apple.uikit/documentation/UIKit/UIKeyboardType","kind":"symbol"},"doc://com.apple.uikit/documentation/UIKit/UITextInputTraits/keyboardType":{"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"keyboardType","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@E@UIKeyboardType","text":"UIKeyboardType","kind":"typeIdentifier"}],"title":"keyboardType","url":"/documentation/uikit/uitextinputtraits/keyboardtype","type":"topic","navigatorTitle":[{"text":"keyboardType","kind":"identifier"}],"kind":"symbol","identifier":"doc://com.apple.uikit/documentation/UIKit/UITextInputTraits/keyboardType","role":"symbol","abstract":[{"type":"text","text":"The keyboard type for the text object."}]},"doc://com.apple.uikit/documentation/UIKit/UIKeyboardAppearance":{"url":"/documentation/uikit/uikeyboardappearance","navigatorTitle":[{"kind":"identifier","text":"UIKeyboardAppearance"}],"title":"UIKeyboardAppearance","type":"topic","identifier":"doc://com.apple.uikit/documentation/UIKit/UIKeyboardAppearance","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"UIKeyboardAppearance"}],"kind":"symbol","abstract":[{"type":"text","text":"Constants that specify the appearance of the keyboard for a text-based view."}],"role":"symbol"},"doc://com.apple.uikit/documentation/UIKit":{"kind":"symbol","role":"collection","title":"UIKit","identifier":"doc://com.apple.uikit/documentation/UIKit","url":"/documentation/uikit","abstract":[{"type":"text","text":"Construct and manage a graphical, event-driven user interface for your iOS, iPadOS, or tvOS app."}],"type":"topic"},"doc://com.apple.uikit/documentation/UIKit/UITextContentType":{"title":"UITextContentType","kind":"symbol","role":"symbol","identifier":"doc://com.apple.uikit/documentation/UIKit/UITextContentType","abstract":[{"text":"Constants that identify the semantic meaning for a text-entry area.","type":"text"}],"type":"topic","navigatorTitle":[{"text":"UITextContentType","kind":"identifier"}],"url":"/documentation/uikit/uitextcontenttype","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"UITextContentType","kind":"identifier"}]},"doc://com.apple.uikit/documentation/UIKit/UITextInputTraits/keyboardAppearance":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"keyboardAppearance"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIKeyboardAppearance","preciseIdentifier":"c:@E@UIKeyboardAppearance"}],"title":"keyboardAppearance","url":"/documentation/uikit/uitextinputtraits/keyboardappearance","type":"topic","navigatorTitle":[{"kind":"identifier","text":"keyboardAppearance"}],"kind":"symbol","identifier":"doc://com.apple.uikit/documentation/UIKit/UITextInputTraits/keyboardAppearance","role":"symbol","abstract":[{"text":"The appearance style of the keyboard for the text object.","type":"text"}]},"doc://com.apple.uikit/documentation/UIKit/UITextInputTraits/textContentType":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"textContentType"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UITextContentType","preciseIdentifier":"c:@T@UITextContentType"},{"kind":"text","text":"!"}],"title":"textContentType","url":"/documentation/uikit/uitextinputtraits/textcontenttype","type":"topic","navigatorTitle":[{"kind":"identifier","text":"textContentType"}],"kind":"symbol","identifier":"doc://com.apple.uikit/documentation/UIKit/UITextInputTraits/textContentType","role":"symbol","abstract":[{"text":"The semantic meaning for a text input area.","type":"text"}]},"doc://com.apple.uikit/documentation/UIKit/UIKeyboardType/default":{"role":"symbol","title":"UIKeyboardType.default","navigatorTitle":[{"kind":"identifier","text":"UIKeyboardTypeDefault"}],"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"`default`"}],"kind":"symbol","abstract":[{"type":"text","text":"Specifies the default keyboard for the current input method."}],"url":"/documentation/uikit/uikeyboardtype/default","type":"topic","identifier":"doc://com.apple.uikit/documentation/UIKit/UIKeyboardType/default"},"doc://com.apple.uikit/documentation/UIKit/UITextInputTraits":{"abstract":[{"type":"text","text":"A set of methods that defines features for keyboard input to a text object."}],"kind":"symbol","identifier":"doc://com.apple.uikit/documentation/UIKit/UITextInputTraits","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"UITextInputTraits"}],"title":"UITextInputTraits","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"UITextInputTraits"}],"type":"topic","url":"/documentation/uikit/uitextinputtraits"},"doc://com.apple.uikit/documentation/UIKit/configuring-a-custom-keyboard-interface":{"identifier":"doc://com.apple.uikit/documentation/UIKit/configuring-a-custom-keyboard-interface","abstract":[{"text":"Design a flexible, functional, and responsive interface for editing text.","type":"text"}],"title":"Configuring a custom keyboard interface","role":"article","url":"/documentation/uikit/configuring-a-custom-keyboard-interface","kind":"article","type":"topic"}},"variantOverrides":[{"patch":[{"op":"replace","path":"/identifier/interfaceLanguage","value":"occ"},{"op":"replace","path":"/metadata/platforms","value":[{"name":"iOS","unavailable":false,"deprecated":false,"beta":false},{"name":"iPadOS","unavailable":false,"deprecated":false,"beta":false},{"name":"Mac Catalyst","unavailable":false,"deprecated":false,"beta":false},{"name":"tvOS","unavailable":false,"deprecated":false,"beta":false},{"name":"visionOS","unavailable":false,"deprecated":false,"beta":false}]},{"op":"replace","path":"/metadata/roleHeading","value":"Instance Property"},{"op":"replace","path":"/metadata/title","value":"keyboardType"},{"op":"replace","path":"/metadata/symbolKind","value":"property"},{"op":"replace","path":"/metadata/fragments","value":[{"text":"keyboardType","kind":"identifier"}]},{"op":"replace","path":"/hierarchy","value":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.uikit/documentation/UIKit","doc://com.apple.uikit/documentation/UIKit/UITextInputTraits"]]}},{"op":"add","path":"/topicSections","value":null},{"op":"add","path":"/relationshipsSections","value":null},{"op":"replace","path":"/seeAlsoSections","value":[{"generated":true,"identifiers":["doc://com.apple.uikit/documentation/UIKit/UIKeyboardType","doc://com.apple.uikit/documentation/UIKit/UITextInputTraits/keyboardAppearance","doc://com.apple.uikit/documentation/UIKit/UIKeyboardAppearance","doc://com.apple.uikit/documentation/UIKit/UITextInputTraits/returnKeyType","doc://com.apple.uikit/documentation/UIKit/UIReturnKeyType","doc://com.apple.uikit/documentation/UIKit/UITextInputTraits/textContentType","doc://com.apple.uikit/documentation/UIKit/UITextContentType"],"title":"Configuring the keyboard appearance","anchor":"Configuring-the-keyboard-appearance"}]},{"op":"replace","path":"/primaryContentSections/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS","iPadOS","Mac Catalyst","tvOS","visionOS"],"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":") "},{"kind":"typeIdentifier","text":"UIKeyboardType","preciseIdentifier":"c:@E@UIKeyboardType","identifier":"doc://com.apple.uikit/documentation/UIKit/UIKeyboardType"},{"kind":"text","text":" "},{"kind":"identifier","text":"keyboardType"},{"kind":"text","text":";"}]}]}},{"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIReturnKeyType/title","value":"UIReturnKeyType"},{"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIReturnKeyType/fragments","value":[{"text":"UIReturnKeyType","kind":"identifier"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIReturnKeyType/navigatorTitle","value":[{"text":"UIReturnKeyType","kind":"identifier"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITextInputTraits~1returnKeyType/title","value":"returnKeyType"},{"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITextInputTraits~1returnKeyType/fragments","value":[{"text":"returnKeyType","kind":"identifier"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIKeyboardType/title","value":"UIKeyboardType"},{"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIKeyboardType/fragments","value":[{"kind":"identifier","text":"UIKeyboardType"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIKeyboardType/navigatorTitle","value":[{"kind":"identifier","text":"UIKeyboardType"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITextInputTraits~1keyboardType/title","value":"keyboardType"},{"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITextInputTraits~1keyboardType/fragments","value":[{"kind":"identifier","text":"keyboardType"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIKeyboardAppearance/title","value":"UIKeyboardAppearance"},{"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIKeyboardAppearance/fragments","value":[{"text":"UIKeyboardAppearance","kind":"identifier"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIKeyboardAppearance/navigatorTitle","value":[{"text":"UIKeyboardAppearance","kind":"identifier"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITextContentType/title","value":"UITextContentType"},{"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITextContentType/fragments","value":[{"kind":"identifier","text":"UITextContentType"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITextContentType/navigatorTitle","value":[{"kind":"identifier","text":"UITextContentType"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITextInputTraits~1keyboardAppearance/title","value":"keyboardAppearance"},{"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITextInputTraits~1keyboardAppearance/fragments","value":[{"text":"keyboardAppearance","kind":"identifier"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITextInputTraits~1textContentType/title","value":"textContentType"},{"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITextInputTraits~1textContentType/fragments","value":[{"text":"textContentType","kind":"identifier"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIKeyboardType~1default/title","value":"UIKeyboardTypeDefault"},{"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIKeyboardType~1default/fragments","value":[{"text":"UIKeyboardTypeDefault","kind":"identifier"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITextInputTraits/title","value":"UITextInputTraits"},{"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITextInputTraits/fragments","value":[{"text":"UITextInputTraits","kind":"identifier"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITextInputTraits/navigatorTitle","value":[{"kind":"identifier","text":"UITextInputTraits"}]}],"traits":[{"interfaceLanguage":"occ"}]}],"legalNotices":{"copyright":"Copyright &copy; 2025 Apple Inc. All rights reserved.","termsOfUse":"https://www.apple.com/legal/internet-services/terms/site.html","privacyPolicy":"https://www.apple.com/privacy/privacy-policy"}}