{
  "abstract": [
    {
      "text": "The visible title of the Return key.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.uikit/documentation/UIKit",
        "doc://com.apple.uikit/documentation/UIKit/UITextInputTraits"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.uikit/documentation/UIKit/UITextInputTraits/returnKeyType"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(pl)UITextInputTraits(py)returnKeyType",
    "fragments": [
      {
        "kind": "keyword",
        "text": "var"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "returnKeyType"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@E@UIReturnKeyType",
        "text": "UIReturnKeyType"
      }
    ],
    "modules": [
      {
        "name": "UIKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "returnKeyType"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Instance Property",
    "symbolKind": "property",
    "title": "returnKeyType"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "tvOS",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "attribute",
              "text": "@"
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:ScM",
              "kind": "attribute",
              "preciseIdentifier": "s:ScM",
              "text": "MainActor"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "keyword",
              "text": "optional"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "keyword",
              "text": "var"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "returnKeyType"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.uikit/documentation/UIKit/UIReturnKeyType",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@E@UIReturnKeyType",
              "text": "UIReturnKeyType"
            },
            {
              "kind": "text",
              "text": " { "
            },
            {
              "kind": "keyword",
              "text": "get"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "keyword",
              "text": "set"
            },
            {
              "kind": "text",
              "text": " }"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Setting this property to a different key type changes the visible title of the Return key and typically results in the keyboard being dismissed when it is pressed. The default value for this property is ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.uikit/documentation/UIKit/UIReturnKeyType/default",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ".",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.uikit/documentation/UIKit": {
      "abstract": [
        {
          "text": "Construct and manage a graphical, event-driven user interface for your iOS, iPadOS, or tvOS app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit",
      "kind": "symbol",
      "role": "collection",
      "title": "UIKit",
      "type": "topic",
      "url": "/documentation/uikit"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIKeyboardAppearance": {
      "abstract": [
        {
          "text": "Constants that specify the appearance of the keyboard for a text-based view.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UIKeyboardAppearance"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIKeyboardAppearance",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIKeyboardAppearance"
        }
      ],
      "role": "symbol",
      "title": "UIKeyboardAppearance",
      "type": "topic",
      "url": "/documentation/uikit/uikeyboardappearance"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIKeyboardType": {
      "abstract": [
        {
          "text": "Constants that specify the type of keyboard to display for a text-based view.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UIKeyboardType"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIKeyboardType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIKeyboardType"
        }
      ],
      "role": "symbol",
      "title": "UIKeyboardType",
      "type": "topic",
      "url": "/documentation/uikit/uikeyboardtype"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIReturnKeyType": {
      "abstract": [
        {
          "text": "Constants that specify the text string that displays in the Return key of a keyboard.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UIReturnKeyType"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIReturnKeyType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIReturnKeyType"
        }
      ],
      "role": "symbol",
      "title": "UIReturnKeyType",
      "type": "topic",
      "url": "/documentation/uikit/uireturnkeytype"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIReturnKeyType/default": {
      "abstract": [
        {
          "text": "Specifies that the visible title of the Return key is ",
          "type": "text"
        },
        {
          "inlineContent": [
            {
              "text": "return",
              "type": "text"
            }
          ],
          "type": "emphasis"
        },
        {
          "text": ".",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "`default`"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIReturnKeyType/default",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIReturnKeyDefault"
        }
      ],
      "role": "symbol",
      "title": "UIReturnKeyType.default",
      "type": "topic",
      "url": "/documentation/uikit/uireturnkeytype/default"
    },
    "doc://com.apple.uikit/documentation/UIKit/UITextContentType": {
      "abstract": [
        {
          "text": "Constants that identify the semantic meaning for a text-entry area.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UITextContentType"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UITextContentType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UITextContentType"
        }
      ],
      "role": "symbol",
      "title": "UITextContentType",
      "type": "topic",
      "url": "/documentation/uikit/uitextcontenttype"
    },
    "doc://com.apple.uikit/documentation/UIKit/UITextInputTraits": {
      "abstract": [
        {
          "text": "A set of methods that defines features for keyboard input to a text object.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UITextInputTraits"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UITextInputTraits",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UITextInputTraits"
        }
      ],
      "role": "symbol",
      "title": "UITextInputTraits",
      "type": "topic",
      "url": "/documentation/uikit/uitextinputtraits"
    },
    "doc://com.apple.uikit/documentation/UIKit/UITextInputTraits/keyboardAppearance": {
      "abstract": [
        {
          "text": "The appearance style of the keyboard for the text object.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "keyboardAppearance"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@UIKeyboardAppearance",
          "text": "UIKeyboardAppearance"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UITextInputTraits/keyboardAppearance",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "keyboardAppearance"
        }
      ],
      "role": "symbol",
      "title": "keyboardAppearance",
      "type": "topic",
      "url": "/documentation/uikit/uitextinputtraits/keyboardappearance"
    },
    "doc://com.apple.uikit/documentation/UIKit/UITextInputTraits/keyboardType": {
      "abstract": [
        {
          "text": "The keyboard type for the text object.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "keyboardType"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@UIKeyboardType",
          "text": "UIKeyboardType"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UITextInputTraits/keyboardType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "keyboardType"
        }
      ],
      "role": "symbol",
      "title": "keyboardType",
      "type": "topic",
      "url": "/documentation/uikit/uitextinputtraits/keyboardtype"
    },
    "doc://com.apple.uikit/documentation/UIKit/UITextInputTraits/returnKeyType": {
      "abstract": [
        {
          "text": "The visible title of the Return key.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "returnKeyType"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@UIReturnKeyType",
          "text": "UIReturnKeyType"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UITextInputTraits/returnKeyType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "returnKeyType"
        }
      ],
      "role": "symbol",
      "title": "returnKeyType",
      "type": "topic",
      "url": "/documentation/uikit/uitextinputtraits/returnkeytype"
    },
    "doc://com.apple.uikit/documentation/UIKit/UITextInputTraits/textContentType": {
      "abstract": [
        {
          "text": "The semantic meaning for a text input area.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "textContentType"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@UITextContentType",
          "text": "UITextContentType"
        },
        {
          "kind": "text",
          "text": "!"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UITextInputTraits/textContentType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "textContentType"
        }
      ],
      "role": "symbol",
      "title": "textContentType",
      "type": "topic",
      "url": "/documentation/uikit/uitextinputtraits/textcontenttype"
    },
    "doc://com.externally.resolved.symbol/s:ScM": {
      "abstract": [
        {
          "text": "A singleton actor whose executor is equivalent to the main dispatch queue.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@globalActor"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "final"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "actor"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MainActor"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:ScM",
      "kind": "symbol",
      "role": "symbol",
      "title": "MainActor",
      "type": "topic",
      "url": "/documentation/Swift/MainActor"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Configuring-the-keyboard-appearance",
      "generated": true,
      "identifiers": [
        "doc://com.apple.uikit/documentation/UIKit/UITextInputTraits/keyboardType",
        "doc://com.apple.uikit/documentation/UIKit/UIKeyboardType",
        "doc://com.apple.uikit/documentation/UIKit/UITextInputTraits/keyboardAppearance",
        "doc://com.apple.uikit/documentation/UIKit/UIKeyboardAppearance",
        "doc://com.apple.uikit/documentation/UIKit/UIReturnKeyType",
        "doc://com.apple.uikit/documentation/UIKit/UITextInputTraits/textContentType",
        "doc://com.apple.uikit/documentation/UIKit/UITextContentType"
      ],
      "title": "Configuring the keyboard appearance"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Instance Property"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "returnKeyType"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "property"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "returnKeyType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.uikit/documentation/UIKit",
                "doc://com.apple.uikit/documentation/UIKit/UITextInputTraits"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Configuring-the-keyboard-appearance",
              "generated": true,
              "identifiers": [
                "doc://com.apple.uikit/documentation/UIKit/UITextInputTraits/keyboardType",
                "doc://com.apple.uikit/documentation/UIKit/UIKeyboardType",
                "doc://com.apple.uikit/documentation/UIKit/UITextInputTraits/keyboardAppearance",
                "doc://com.apple.uikit/documentation/UIKit/UIKeyboardAppearance",
                "doc://com.apple.uikit/documentation/UIKit/UIReturnKeyType",
                "doc://com.apple.uikit/documentation/UIKit/UITextInputTraits/textContentType",
                "doc://com.apple.uikit/documentation/UIKit/UITextContentType"
              ],
              "title": "Configuring the keyboard appearance"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "tvOS",
                  "visionOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "@property"
                  },
                  {
                    "kind": "text",
                    "text": " ("
                  },
                  {
                    "kind": "keyword",
                    "text": "nonatomic"
                  },
                  {
                    "kind": "text",
                    "text": ") "
                  },
                  {
                    "identifier": "doc://com.apple.uikit/documentation/UIKit/UIReturnKeyType",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@E@UIReturnKeyType",
                    "text": "UIReturnKeyType"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "returnKeyType"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIReturnKeyType~1default/title",
          "value": "UIReturnKeyDefault"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIReturnKeyType~1default/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIReturnKeyDefault"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITextInputTraits~1keyboardAppearance/title",
          "value": "keyboardAppearance"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITextInputTraits~1keyboardAppearance/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "keyboardAppearance"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITextInputTraits~1textContentType/title",
          "value": "textContentType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITextInputTraits~1textContentType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "textContentType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIKeyboardAppearance/title",
          "value": "UIKeyboardAppearance"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIKeyboardAppearance/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIKeyboardAppearance"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIKeyboardAppearance/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UIKeyboardAppearance"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITextInputTraits~1returnKeyType/title",
          "value": "returnKeyType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITextInputTraits~1returnKeyType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "returnKeyType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITextInputTraits/title",
          "value": "UITextInputTraits"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITextInputTraits/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UITextInputTraits"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITextInputTraits/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UITextInputTraits"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITextContentType/title",
          "value": "UITextContentType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITextContentType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UITextContentType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITextContentType/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UITextContentType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIKeyboardType/title",
          "value": "UIKeyboardType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIKeyboardType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIKeyboardType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIKeyboardType/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UIKeyboardType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITextInputTraits~1keyboardType/title",
          "value": "keyboardType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITextInputTraits~1keyboardType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "keyboardType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIReturnKeyType/title",
          "value": "UIReturnKeyType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIReturnKeyType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIReturnKeyType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIReturnKeyType/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UIReturnKeyType"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/uikit/uitextinputtraits/returnkeytype"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/uikit/uitextinputtraits/returnkeytype"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
