{
  "abstract": [
    {
      "text": "Constants that specify print job attributes.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.appkit/documentation/AppKit",
        "doc://com.apple.appkit/documentation/AppKit/NSPrintInfo"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.appkit/documentation/AppKit/NSPrintInfo/AttributeKey"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "extendedModule": "AppKit",
    "externalID": "c:@T@NSPrintInfoAttributeKey",
    "fragments": [
      {
        "kind": "keyword",
        "text": "struct"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "AttributeKey"
      }
    ],
    "modules": [
      {
        "name": "AppKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "AttributeKey"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Structure",
    "symbolKind": "struct",
    "title": "NSPrintInfo.AttributeKey"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "macOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "struct"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "AttributeKey"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.appkit/documentation/AppKit": {
      "abstract": [
        {
          "text": "Construct and manage a graphical, event-driven user interface for your macOS app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit",
      "kind": "symbol",
      "role": "collection",
      "title": "AppKit",
      "type": "topic",
      "url": "/documentation/appkit"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSPrintInfo": {
      "abstract": [
        {
          "text": "An object that stores information that’s used to generate printed output.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSPrintInfo"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSPrintInfo",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSPrintInfo"
        }
      ],
      "role": "symbol",
      "title": "NSPrintInfo",
      "type": "topic",
      "url": "/documentation/appkit/nsprintinfo"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSPrintInfo/AttributeKey": {
      "abstract": [
        {
          "text": "Constants that specify print job attributes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AttributeKey"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSPrintInfo/AttributeKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AttributeKey"
        }
      ],
      "role": "symbol",
      "title": "NSPrintInfo.AttributeKey",
      "type": "topic",
      "url": "/documentation/appkit/nsprintinfo/attributekey"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSPrintInfo/AttributeKey/allPages": {
      "abstract": [
        {
          "text": "An ",
          "type": "text"
        },
        {
          "code": "NSNumber",
          "type": "codeVoice"
        },
        {
          "text": " object containing a Boolean value—if ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.documentation/documentation/swift/true",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": ", includes all pages in output.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "allPages"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSPrintInfo",
          "text": "NSPrintInfo"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSPrintInfoAttributeKey",
          "text": "AttributeKey"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSPrintInfo/AttributeKey/allPages",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSPrintAllPages"
        }
      ],
      "role": "symbol",
      "title": "allPages",
      "type": "topic",
      "url": "/documentation/appkit/nsprintinfo/attributekey/allpages"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSPrintInfo/AttributeKey/bottomMargin": {
      "abstract": [
        {
          "code": "NSNumber",
          "type": "codeVoice"
        },
        {
          "text": ", containing a floating-point value that specifies the bottom margin, in points.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "bottomMargin"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSPrintInfo",
          "text": "NSPrintInfo"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSPrintInfoAttributeKey",
          "text": "AttributeKey"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSPrintInfo/AttributeKey/bottomMargin",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSPrintBottomMargin"
        }
      ],
      "role": "symbol",
      "title": "bottomMargin",
      "type": "topic",
      "url": "/documentation/appkit/nsprintinfo/attributekey/bottommargin"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSPrintInfo/AttributeKey/copies": {
      "abstract": [
        {
          "text": "An ",
          "type": "text"
        },
        {
          "code": "NSNumber",
          "type": "codeVoice"
        },
        {
          "text": " object containing an integer—the number of copies to spool.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "copies"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSPrintInfo",
          "text": "NSPrintInfo"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSPrintInfoAttributeKey",
          "text": "AttributeKey"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSPrintInfo/AttributeKey/copies",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSPrintCopies"
        }
      ],
      "role": "symbol",
      "title": "copies",
      "type": "topic",
      "url": "/documentation/appkit/nsprintinfo/attributekey/copies"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSPrintInfo/AttributeKey/detailedErrorReporting": {
      "abstract": [
        {
          "text": "An ",
          "type": "text"
        },
        {
          "code": "NSNumber",
          "type": "codeVoice"
        },
        {
          "text": " object containing a Boolean value—if ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.documentation/documentation/swift/true",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": ", produce detailed reports when an error occurs.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "detailedErrorReporting"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSPrintInfo",
          "text": "NSPrintInfo"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSPrintInfoAttributeKey",
          "text": "AttributeKey"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSPrintInfo/AttributeKey/detailedErrorReporting",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSPrintDetailedErrorReporting"
        }
      ],
      "role": "symbol",
      "title": "detailedErrorReporting",
      "type": "topic",
      "url": "/documentation/appkit/nsprintinfo/attributekey/detailederrorreporting"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSPrintInfo/AttributeKey/faxNumber": {
      "abstract": [
        {
          "text": "An ",
          "type": "text"
        },
        {
          "code": "NSString",
          "type": "codeVoice"
        },
        {
          "text": " object that specifies a fax number.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "faxNumber"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSPrintInfo",
          "text": "NSPrintInfo"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSPrintInfoAttributeKey",
          "text": "AttributeKey"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSPrintInfo/AttributeKey/faxNumber",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSPrintFaxNumber"
        }
      ],
      "role": "symbol",
      "title": "faxNumber",
      "type": "topic",
      "url": "/documentation/appkit/nsprintinfo/attributekey/faxnumber"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSPrintInfo/AttributeKey/firstPage": {
      "abstract": [
        {
          "text": "An ",
          "type": "text"
        },
        {
          "code": "NSNumber",
          "type": "codeVoice"
        },
        {
          "text": " object containing an integer value that specifies the first page in the print job.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "firstPage"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSPrintInfo",
          "text": "NSPrintInfo"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSPrintInfoAttributeKey",
          "text": "AttributeKey"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSPrintInfo/AttributeKey/firstPage",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSPrintFirstPage"
        }
      ],
      "role": "symbol",
      "title": "firstPage",
      "type": "topic",
      "url": "/documentation/appkit/nsprintinfo/attributekey/firstpage"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSPrintInfo/AttributeKey/headerAndFooter": {
      "abstract": [
        {
          "text": "An ",
          "type": "text"
        },
        {
          "code": "NSNumber",
          "type": "codeVoice"
        },
        {
          "text": " object containing a Boolean value—if ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.documentation/documentation/swift/true",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": ", a standard header and footer are added outside the margins of each page.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "headerAndFooter"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSPrintInfo",
          "text": "NSPrintInfo"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSPrintInfoAttributeKey",
          "text": "AttributeKey"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSPrintInfo/AttributeKey/headerAndFooter",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSPrintHeaderAndFooter"
        }
      ],
      "role": "symbol",
      "title": "headerAndFooter",
      "type": "topic",
      "url": "/documentation/appkit/nsprintinfo/attributekey/headerandfooter"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSPrintInfo/AttributeKey/horizontalPagination": {
      "abstract": [
        {
          "code": "NSNumber",
          "type": "codeVoice"
        },
        {
          "text": ", containing a ",
          "type": "text"
        },
        {
          "code": "NSPrintingPaginationMode",
          "type": "codeVoice"
        },
        {
          "text": " value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "horizontalPagination"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSPrintInfo",
          "text": "NSPrintInfo"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSPrintInfoAttributeKey",
          "text": "AttributeKey"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSPrintInfo/AttributeKey/horizontalPagination",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSPrintHorizontalPagination"
        }
      ],
      "role": "symbol",
      "title": "horizontalPagination",
      "type": "topic",
      "url": "/documentation/appkit/nsprintinfo/attributekey/horizontalpagination"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSPrintInfo/AttributeKey/horizontallyCentered": {
      "abstract": [
        {
          "code": "NSNumber",
          "type": "codeVoice"
        },
        {
          "text": ", containing a Boolean value that is ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.documentation/documentation/swift/true",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " if pages are centered horizontally.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "horizontallyCentered"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSPrintInfo",
          "text": "NSPrintInfo"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSPrintInfoAttributeKey",
          "text": "AttributeKey"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSPrintInfo/AttributeKey/horizontallyCentered",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSPrintHorizontallyCentered"
        }
      ],
      "role": "symbol",
      "title": "horizontallyCentered",
      "type": "topic",
      "url": "/documentation/appkit/nsprintinfo/attributekey/horizontallycentered"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSPrintInfo/AttributeKey/init(_:)": {
      "abstract": [
        {
          "text": "Creates a print job attribute key.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSPrintInfo/AttributeKey/init(_:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "init(_:)",
      "type": "topic",
      "url": "/documentation/appkit/nsprintinfo/attributekey/init(_:)"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSPrintInfo/AttributeKey/init(rawValue:)": {
      "abstract": [
        {
          "text": "Creates a new instance with the specified raw value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "rawValue"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSPrintInfo/AttributeKey/init(rawValue:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "init(rawValue:)",
      "type": "topic",
      "url": "/documentation/appkit/nsprintinfo/attributekey/init(rawvalue:)"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSPrintInfo/AttributeKey/jobDisposition": {
      "abstract": [
        {
          "text": "An ",
          "type": "text"
        },
        {
          "code": "NSString",
          "type": "codeVoice"
        },
        {
          "text": " object that specifies the job disposition.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "jobDisposition"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSPrintInfo",
          "text": "NSPrintInfo"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSPrintInfoAttributeKey",
          "text": "AttributeKey"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSPrintInfo/AttributeKey/jobDisposition",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSPrintJobDisposition"
        }
      ],
      "role": "symbol",
      "title": "jobDisposition",
      "type": "topic",
      "url": "/documentation/appkit/nsprintinfo/attributekey/jobdisposition"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSPrintInfo/AttributeKey/jobSavingFileNameExtensionHidden": {
      "abstract": [
        {
          "text": "A Boolean ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.documentation/documentation/foundation/nsnumber",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " indicating whether the job’s file name extension should be hidden when the ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.appkit/documentation/AppKit/NSPrintInfo/jobDisposition-swift.property",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " is ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.appkit/documentation/AppKit/NSPrintInfo/JobDisposition-swift.struct/save",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": ". The default is ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.documentation/documentation/swift/false",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": ".",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "jobSavingFileNameExtensionHidden"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSPrintInfo",
          "text": "NSPrintInfo"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSPrintInfoAttributeKey",
          "text": "AttributeKey"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSPrintInfo/AttributeKey/jobSavingFileNameExtensionHidden",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSPrintJobSavingFileNameExtensionHidden"
        }
      ],
      "role": "symbol",
      "title": "jobSavingFileNameExtensionHidden",
      "type": "topic",
      "url": "/documentation/appkit/nsprintinfo/attributekey/jobsavingfilenameextensionhidden"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSPrintInfo/AttributeKey/jobSavingURL": {
      "abstract": [
        {
          "text": "An ",
          "type": "text"
        },
        {
          "code": "NSURL",
          "type": "codeVoice"
        },
        {
          "text": " containing the location to which the job file will be saved when the ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.appkit/documentation/AppKit/NSPrintInfo/jobDisposition-swift.property",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " is ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.appkit/documentation/AppKit/NSPrintInfo/JobDisposition-swift.struct/save",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": ".",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "jobSavingURL"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSPrintInfo",
          "text": "NSPrintInfo"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSPrintInfoAttributeKey",
          "text": "AttributeKey"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSPrintInfo/AttributeKey/jobSavingURL",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSPrintJobSavingURL"
        }
      ],
      "role": "symbol",
      "title": "jobSavingURL",
      "type": "topic",
      "url": "/documentation/appkit/nsprintinfo/attributekey/jobsavingurl"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSPrintInfo/AttributeKey/lastPage": {
      "abstract": [
        {
          "text": "An ",
          "type": "text"
        },
        {
          "code": "NSNumber",
          "type": "codeVoice"
        },
        {
          "text": " object containing an integer value that specifies the last page in the print job.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "lastPage"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSPrintInfo",
          "text": "NSPrintInfo"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSPrintInfoAttributeKey",
          "text": "AttributeKey"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSPrintInfo/AttributeKey/lastPage",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSPrintLastPage"
        }
      ],
      "role": "symbol",
      "title": "lastPage",
      "type": "topic",
      "url": "/documentation/appkit/nsprintinfo/attributekey/lastpage"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSPrintInfo/AttributeKey/leftMargin": {
      "abstract": [
        {
          "code": "NSNumber",
          "type": "codeVoice"
        },
        {
          "text": ", containing a floating-point value that specifies the left margin, in points.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "leftMargin"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSPrintInfo",
          "text": "NSPrintInfo"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSPrintInfoAttributeKey",
          "text": "AttributeKey"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSPrintInfo/AttributeKey/leftMargin",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSPrintLeftMargin"
        }
      ],
      "role": "symbol",
      "title": "leftMargin",
      "type": "topic",
      "url": "/documentation/appkit/nsprintinfo/attributekey/leftmargin"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSPrintInfo/AttributeKey/mustCollate": {
      "abstract": [
        {
          "text": "An ",
          "type": "text"
        },
        {
          "code": "NSNumber",
          "type": "codeVoice"
        },
        {
          "text": " object containing a Boolean value—if ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.documentation/documentation/swift/true",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": ", collates output.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "mustCollate"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSPrintInfo",
          "text": "NSPrintInfo"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSPrintInfoAttributeKey",
          "text": "AttributeKey"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSPrintInfo/AttributeKey/mustCollate",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSPrintMustCollate"
        }
      ],
      "role": "symbol",
      "title": "mustCollate",
      "type": "topic",
      "url": "/documentation/appkit/nsprintinfo/attributekey/mustcollate"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSPrintInfo/AttributeKey/orientation": {
      "abstract": [
        {
          "text": "An ",
          "type": "text"
        },
        {
          "code": "NSNumber",
          "type": "codeVoice"
        },
        {
          "text": " object containing an ",
          "type": "text"
        },
        {
          "code": "NSPrintingOrientation",
          "type": "codeVoice"
        },
        {
          "text": ".",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "orientation"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSPrintInfo",
          "text": "NSPrintInfo"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSPrintInfoAttributeKey",
          "text": "AttributeKey"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSPrintInfo/AttributeKey/orientation",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSPrintOrientation"
        }
      ],
      "role": "symbol",
      "title": "orientation",
      "type": "topic",
      "url": "/documentation/appkit/nsprintinfo/attributekey/orientation"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSPrintInfo/AttributeKey/pagesAcross": {
      "abstract": [
        {
          "text": "An ",
          "type": "text"
        },
        {
          "code": "NSNumber",
          "type": "codeVoice"
        },
        {
          "text": " object that specifies the number of logical pages to be tiled horizontally on a physical sheet of paper.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "pagesAcross"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSPrintInfo",
          "text": "NSPrintInfo"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSPrintInfoAttributeKey",
          "text": "AttributeKey"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSPrintInfo/AttributeKey/pagesAcross",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSPrintPagesAcross"
        }
      ],
      "role": "symbol",
      "title": "pagesAcross",
      "type": "topic",
      "url": "/documentation/appkit/nsprintinfo/attributekey/pagesacross"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSPrintInfo/AttributeKey/pagesDown": {
      "abstract": [
        {
          "text": "An ",
          "type": "text"
        },
        {
          "code": "NSNumber",
          "type": "codeVoice"
        },
        {
          "text": " object that specifies the number of logical pages to be tiled vertically on a physical sheet of paper.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "pagesDown"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSPrintInfo",
          "text": "NSPrintInfo"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSPrintInfoAttributeKey",
          "text": "AttributeKey"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSPrintInfo/AttributeKey/pagesDown",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSPrintPagesDown"
        }
      ],
      "role": "symbol",
      "title": "pagesDown",
      "type": "topic",
      "url": "/documentation/appkit/nsprintinfo/attributekey/pagesdown"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSPrintInfo/AttributeKey/paperName": {
      "abstract": [
        {
          "text": "An ",
          "type": "text"
        },
        {
          "code": "NSString",
          "type": "codeVoice"
        },
        {
          "text": " object containing the paper name.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "paperName"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSPrintInfo",
          "text": "NSPrintInfo"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSPrintInfoAttributeKey",
          "text": "AttributeKey"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSPrintInfo/AttributeKey/paperName",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSPrintPaperName"
        }
      ],
      "role": "symbol",
      "title": "paperName",
      "type": "topic",
      "url": "/documentation/appkit/nsprintinfo/attributekey/papername"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSPrintInfo/AttributeKey/paperSize": {
      "abstract": [
        {
          "text": "An ",
          "type": "text"
        },
        {
          "code": "NSSize",
          "type": "codeVoice"
        },
        {
          "text": " value specifying the height and width of paper in points.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "paperSize"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSPrintInfo",
          "text": "NSPrintInfo"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSPrintInfoAttributeKey",
          "text": "AttributeKey"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSPrintInfo/AttributeKey/paperSize",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSPrintPaperSize"
        }
      ],
      "role": "symbol",
      "title": "paperSize",
      "type": "topic",
      "url": "/documentation/appkit/nsprintinfo/attributekey/papersize"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSPrintInfo/AttributeKey/printer": {
      "abstract": [
        {
          "text": "An ",
          "type": "text"
        },
        {
          "code": "NSPrinter",
          "type": "codeVoice"
        },
        {
          "text": " object—the printer to use.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "printer"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSPrintInfo",
          "text": "NSPrintInfo"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSPrintInfoAttributeKey",
          "text": "AttributeKey"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSPrintInfo/AttributeKey/printer",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSPrintPrinter"
        }
      ],
      "role": "symbol",
      "title": "printer",
      "type": "topic",
      "url": "/documentation/appkit/nsprintinfo/attributekey/printer"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSPrintInfo/AttributeKey/printerName": {
      "abstract": [
        {
          "text": "An ",
          "type": "text"
        },
        {
          "code": "NSString",
          "type": "codeVoice"
        },
        {
          "text": " object that specifies the name of a printer.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "printerName"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSPrintInfo",
          "text": "NSPrintInfo"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSPrintInfoAttributeKey",
          "text": "AttributeKey"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSPrintInfo/AttributeKey/printerName",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSPrintPrinterName"
        }
      ],
      "role": "symbol",
      "title": "printerName",
      "type": "topic",
      "url": "/documentation/appkit/nsprintinfo/attributekey/printername"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSPrintInfo/AttributeKey/reversePageOrder": {
      "abstract": [
        {
          "text": "An ",
          "type": "text"
        },
        {
          "code": "NSNumber",
          "type": "codeVoice"
        },
        {
          "text": " object containing a Boolean value—if ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.documentation/documentation/swift/true",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": ", prints first page last.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "reversePageOrder"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSPrintInfo",
          "text": "NSPrintInfo"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSPrintInfoAttributeKey",
          "text": "AttributeKey"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSPrintInfo/AttributeKey/reversePageOrder",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSPrintReversePageOrder"
        }
      ],
      "role": "symbol",
      "title": "reversePageOrder",
      "type": "topic",
      "url": "/documentation/appkit/nsprintinfo/attributekey/reversepageorder"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSPrintInfo/AttributeKey/rightMargin": {
      "abstract": [
        {
          "code": "NSNumber",
          "type": "codeVoice"
        },
        {
          "text": ", containing a floating-point value that specifies the right margin, in points.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "rightMargin"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSPrintInfo",
          "text": "NSPrintInfo"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSPrintInfoAttributeKey",
          "text": "AttributeKey"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSPrintInfo/AttributeKey/rightMargin",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSPrintRightMargin"
        }
      ],
      "role": "symbol",
      "title": "rightMargin",
      "type": "topic",
      "url": "/documentation/appkit/nsprintinfo/attributekey/rightmargin"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSPrintInfo/AttributeKey/scalingFactor": {
      "abstract": [
        {
          "text": "Scale factor percentage before pagination.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "scalingFactor"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSPrintInfo",
          "text": "NSPrintInfo"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSPrintInfoAttributeKey",
          "text": "AttributeKey"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSPrintInfo/AttributeKey/scalingFactor",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSPrintScalingFactor"
        }
      ],
      "role": "symbol",
      "title": "scalingFactor",
      "type": "topic",
      "url": "/documentation/appkit/nsprintinfo/attributekey/scalingfactor"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSPrintInfo/AttributeKey/selectionOnly": {
      "abstract": [
        {
          "text": "An ",
          "type": "text"
        },
        {
          "code": "NSNumber",
          "type": "codeVoice"
        },
        {
          "text": " object containing a Boolean value—if ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.documentation/documentation/swift/true",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " only the current selection is printed.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "selectionOnly"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSPrintInfo",
          "text": "NSPrintInfo"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSPrintInfoAttributeKey",
          "text": "AttributeKey"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSPrintInfo/AttributeKey/selectionOnly",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSPrintSelectionOnly"
        }
      ],
      "role": "symbol",
      "title": "selectionOnly",
      "type": "topic",
      "url": "/documentation/appkit/nsprintinfo/attributekey/selectiononly"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSPrintInfo/AttributeKey/time": {
      "abstract": [
        {
          "text": "An ",
          "type": "text"
        },
        {
          "code": "NSDate",
          "type": "codeVoice"
        },
        {
          "text": " object that specifies the time at which printing should begin.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "time"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSPrintInfo",
          "text": "NSPrintInfo"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSPrintInfoAttributeKey",
          "text": "AttributeKey"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSPrintInfo/AttributeKey/time",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSPrintTime"
        }
      ],
      "role": "symbol",
      "title": "time",
      "type": "topic",
      "url": "/documentation/appkit/nsprintinfo/attributekey/time"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSPrintInfo/AttributeKey/topMargin": {
      "abstract": [
        {
          "code": "NSNumber",
          "type": "codeVoice"
        },
        {
          "text": ", containing a floating-point value that specifies the top margin, in points.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "topMargin"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSPrintInfo",
          "text": "NSPrintInfo"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSPrintInfoAttributeKey",
          "text": "AttributeKey"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSPrintInfo/AttributeKey/topMargin",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSPrintTopMargin"
        }
      ],
      "role": "symbol",
      "title": "topMargin",
      "type": "topic",
      "url": "/documentation/appkit/nsprintinfo/attributekey/topmargin"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSPrintInfo/AttributeKey/verticalPagination": {
      "abstract": [
        {
          "code": "NSNumber",
          "type": "codeVoice"
        },
        {
          "text": ", containing a ",
          "type": "text"
        },
        {
          "code": "NSPrintingPaginationMode",
          "type": "codeVoice"
        },
        {
          "text": " value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "verticalPagination"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSPrintInfo",
          "text": "NSPrintInfo"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSPrintInfoAttributeKey",
          "text": "AttributeKey"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSPrintInfo/AttributeKey/verticalPagination",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSPrintVerticalPagination"
        }
      ],
      "role": "symbol",
      "title": "verticalPagination",
      "type": "topic",
      "url": "/documentation/appkit/nsprintinfo/attributekey/verticalpagination"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSPrintInfo/AttributeKey/verticallyCentered": {
      "abstract": [
        {
          "code": "NSNumber",
          "type": "codeVoice"
        },
        {
          "text": ", containing a Boolean value that is ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.documentation/documentation/swift/true",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " if pages are centered vertically.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "verticallyCentered"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSPrintInfo",
          "text": "NSPrintInfo"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSPrintInfoAttributeKey",
          "text": "AttributeKey"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSPrintInfo/AttributeKey/verticallyCentered",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSPrintVerticallyCentered"
        }
      ],
      "role": "symbol",
      "title": "verticallyCentered",
      "type": "topic",
      "url": "/documentation/appkit/nsprintinfo/attributekey/verticallycentered"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSPrintInfo/JobDisposition-swift.struct/save": {
      "abstract": [
        {
          "text": "Save to a file.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "save"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSPrintInfo",
          "text": "NSPrintInfo"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSPrintJobDispositionValue",
          "text": "JobDisposition"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSPrintInfo/JobDisposition-swift.struct/save",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSPrintSaveJob"
        }
      ],
      "role": "symbol",
      "title": "save",
      "type": "topic",
      "url": "/documentation/appkit/nsprintinfo/jobdisposition-swift.struct/save"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSPrintInfo/jobDisposition-swift.property": {
      "abstract": [
        {
          "text": "The action specified for the job.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "jobDisposition"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSPrintInfo",
          "text": "NSPrintInfo"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSPrintJobDispositionValue",
          "text": "JobDisposition"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSPrintInfo/jobDisposition-swift.property",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "jobDisposition"
        }
      ],
      "role": "symbol",
      "title": "jobDisposition",
      "type": "topic",
      "url": "/documentation/appkit/nsprintinfo/jobdisposition-swift.property"
    },
    "doc://com.apple.documentation/documentation/foundation/nsnumber": {
      "abstract": [
        {
          "text": "An object wrapper for primitive scalar numeric values.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "class "
        },
        {
          "kind": "identifier",
          "text": "NSNumber"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/foundation/nsnumber",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSNumber",
      "type": "topic",
      "url": "/documentation/foundation/nsnumber"
    },
    "doc://com.apple.documentation/documentation/swift/false": {
      "abstract": [
        {
          "text": "A false value.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/swift/false",
      "kind": "symbol",
      "role": "symbol",
      "title": "false",
      "type": "topic",
      "url": "/documentation/swift/false"
    },
    "doc://com.apple.documentation/documentation/swift/true": {
      "abstract": [
        {
          "text": "A true value.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/swift/true",
      "kind": "symbol",
      "role": "symbol",
      "title": "true",
      "type": "topic",
      "url": "/documentation/swift/true"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.externally.resolved.symbol/c:objc(cs)NSString": {
      "abstract": [
        {
          "text": "A static, plain-text Unicode string object which you use when you need reference semantics or other Foundation-specific behavior. ",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "class "
        },
        {
          "kind": "identifier",
          "text": "NSString"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSString",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSString",
      "type": "topic",
      "url": "/documentation/foundation/nsstring"
    },
    "doc://com.externally.resolved.symbol/s:SH": {
      "abstract": [
        {
          "text": "A type that can be hashed into a `Hasher` to produce an integer hash value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Hashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SQ",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SH",
      "kind": "symbol",
      "role": "symbol",
      "title": "Hashable",
      "type": "topic",
      "url": "/documentation/Swift/Hashable"
    },
    "doc://com.externally.resolved.symbol/s:SQ": {
      "abstract": [
        {
          "text": "A type that can be compared for value equality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SQ",
      "kind": "symbol",
      "role": "symbol",
      "title": "Equatable",
      "type": "topic",
      "url": "/documentation/Swift/Equatable"
    },
    "doc://com.externally.resolved.symbol/s:SY": {
      "abstract": [
        {
          "text": "A type that can be converted to and from an associated raw value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "RawRepresentable"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SY8RawValueQa",
          "text": "RawValue"
        },
        {
          "kind": "text",
          "text": ">"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SY",
      "kind": "symbol",
      "role": "symbol",
      "title": "RawRepresentable",
      "type": "topic",
      "url": "/documentation/Swift/RawRepresentable"
    },
    "doc://com.externally.resolved.symbol/s:s8SendableP": {
      "abstract": [
        {
          "text": "A thread-safe type whose values can be shared across arbitrary concurrent contexts without introducing a risk of data races.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Sendable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s8SendableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "Sendable",
      "type": "topic",
      "url": "/documentation/Swift/Sendable"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:SQ",
        "doc://com.externally.resolved.symbol/s:SH",
        "doc://com.externally.resolved.symbol/s:SY",
        "doc://com.externally.resolved.symbol/s:s8SendableP"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "topicSections": [
    {
      "anchor": "Page-Setup-Attributes",
      "identifiers": [
        "doc://com.apple.appkit/documentation/AppKit/NSPrintInfo/AttributeKey/paperName",
        "doc://com.apple.appkit/documentation/AppKit/NSPrintInfo/AttributeKey/paperSize",
        "doc://com.apple.appkit/documentation/AppKit/NSPrintInfo/AttributeKey/orientation",
        "doc://com.apple.appkit/documentation/AppKit/NSPrintInfo/AttributeKey/scalingFactor"
      ],
      "title": "Page Setup Attributes"
    },
    {
      "anchor": "Pagination-Attributes",
      "identifiers": [
        "doc://com.apple.appkit/documentation/AppKit/NSPrintInfo/AttributeKey/leftMargin",
        "doc://com.apple.appkit/documentation/AppKit/NSPrintInfo/AttributeKey/rightMargin",
        "doc://com.apple.appkit/documentation/AppKit/NSPrintInfo/AttributeKey/topMargin",
        "doc://com.apple.appkit/documentation/AppKit/NSPrintInfo/AttributeKey/bottomMargin",
        "doc://com.apple.appkit/documentation/AppKit/NSPrintInfo/AttributeKey/horizontallyCentered",
        "doc://com.apple.appkit/documentation/AppKit/NSPrintInfo/AttributeKey/verticallyCentered",
        "doc://com.apple.appkit/documentation/AppKit/NSPrintInfo/AttributeKey/horizontalPagination",
        "doc://com.apple.appkit/documentation/AppKit/NSPrintInfo/AttributeKey/verticalPagination"
      ],
      "title": "Pagination Attributes"
    },
    {
      "anchor": "Other-Attributes",
      "identifiers": [
        "doc://com.apple.appkit/documentation/AppKit/NSPrintInfo/AttributeKey/allPages",
        "doc://com.apple.appkit/documentation/AppKit/NSPrintInfo/AttributeKey/copies",
        "doc://com.apple.appkit/documentation/AppKit/NSPrintInfo/AttributeKey/detailedErrorReporting",
        "doc://com.apple.appkit/documentation/AppKit/NSPrintInfo/AttributeKey/faxNumber",
        "doc://com.apple.appkit/documentation/AppKit/NSPrintInfo/AttributeKey/firstPage",
        "doc://com.apple.appkit/documentation/AppKit/NSPrintInfo/AttributeKey/headerAndFooter",
        "doc://com.apple.appkit/documentation/AppKit/NSPrintInfo/AttributeKey/jobDisposition",
        "doc://com.apple.appkit/documentation/AppKit/NSPrintInfo/AttributeKey/jobSavingFileNameExtensionHidden",
        "doc://com.apple.appkit/documentation/AppKit/NSPrintInfo/AttributeKey/jobSavingURL",
        "doc://com.apple.appkit/documentation/AppKit/NSPrintInfo/AttributeKey/lastPage",
        "doc://com.apple.appkit/documentation/AppKit/NSPrintInfo/AttributeKey/mustCollate",
        "doc://com.apple.appkit/documentation/AppKit/NSPrintInfo/AttributeKey/pagesAcross",
        "doc://com.apple.appkit/documentation/AppKit/NSPrintInfo/AttributeKey/pagesDown",
        "doc://com.apple.appkit/documentation/AppKit/NSPrintInfo/AttributeKey/printer",
        "doc://com.apple.appkit/documentation/AppKit/NSPrintInfo/AttributeKey/printerName",
        "doc://com.apple.appkit/documentation/AppKit/NSPrintInfo/AttributeKey/reversePageOrder",
        "doc://com.apple.appkit/documentation/AppKit/NSPrintInfo/AttributeKey/selectionOnly",
        "doc://com.apple.appkit/documentation/AppKit/NSPrintInfo/AttributeKey/time"
      ],
      "title": "Other Attributes"
    },
    {
      "anchor": "Initializers",
      "generated": true,
      "identifiers": [
        "doc://com.apple.appkit/documentation/AppKit/NSPrintInfo/AttributeKey/init(_:)",
        "doc://com.apple.appkit/documentation/AppKit/NSPrintInfo/AttributeKey/init(rawValue:)"
      ],
      "title": "Initializers"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "name": "macOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Type Alias"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "NSPrintInfoAttributeKey"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "typealias"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSPrintInfoAttributeKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSPrintInfoAttributeKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.appkit/documentation/AppKit"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Page-Setup-Attributes",
              "identifiers": [
                "doc://com.apple.appkit/documentation/AppKit/NSPrintInfo/AttributeKey/paperName",
                "doc://com.apple.appkit/documentation/AppKit/NSPrintInfo/AttributeKey/paperSize",
                "doc://com.apple.appkit/documentation/AppKit/NSPrintInfo/AttributeKey/orientation",
                "doc://com.apple.appkit/documentation/AppKit/NSPrintInfo/AttributeKey/scalingFactor"
              ],
              "title": "Page Setup Attributes"
            },
            {
              "anchor": "Pagination-Attributes",
              "identifiers": [
                "doc://com.apple.appkit/documentation/AppKit/NSPrintInfo/AttributeKey/leftMargin",
                "doc://com.apple.appkit/documentation/AppKit/NSPrintInfo/AttributeKey/rightMargin",
                "doc://com.apple.appkit/documentation/AppKit/NSPrintInfo/AttributeKey/topMargin",
                "doc://com.apple.appkit/documentation/AppKit/NSPrintInfo/AttributeKey/bottomMargin",
                "doc://com.apple.appkit/documentation/AppKit/NSPrintInfo/AttributeKey/horizontallyCentered",
                "doc://com.apple.appkit/documentation/AppKit/NSPrintInfo/AttributeKey/verticallyCentered",
                "doc://com.apple.appkit/documentation/AppKit/NSPrintInfo/AttributeKey/horizontalPagination",
                "doc://com.apple.appkit/documentation/AppKit/NSPrintInfo/AttributeKey/verticalPagination"
              ],
              "title": "Pagination Attributes"
            },
            {
              "anchor": "Other-Attributes",
              "identifiers": [
                "doc://com.apple.appkit/documentation/AppKit/NSPrintInfo/AttributeKey/allPages",
                "doc://com.apple.appkit/documentation/AppKit/NSPrintInfo/AttributeKey/copies",
                "doc://com.apple.appkit/documentation/AppKit/NSPrintInfo/AttributeKey/detailedErrorReporting",
                "doc://com.apple.appkit/documentation/AppKit/NSPrintInfo/AttributeKey/faxNumber",
                "doc://com.apple.appkit/documentation/AppKit/NSPrintInfo/AttributeKey/firstPage",
                "doc://com.apple.appkit/documentation/AppKit/NSPrintInfo/AttributeKey/headerAndFooter",
                "doc://com.apple.appkit/documentation/AppKit/NSPrintInfo/AttributeKey/jobDisposition",
                "doc://com.apple.appkit/documentation/AppKit/NSPrintInfo/AttributeKey/jobSavingFileNameExtensionHidden",
                "doc://com.apple.appkit/documentation/AppKit/NSPrintInfo/AttributeKey/jobSavingURL",
                "doc://com.apple.appkit/documentation/AppKit/NSPrintInfo/AttributeKey/lastPage",
                "doc://com.apple.appkit/documentation/AppKit/NSPrintInfo/AttributeKey/mustCollate",
                "doc://com.apple.appkit/documentation/AppKit/NSPrintInfo/AttributeKey/pagesAcross",
                "doc://com.apple.appkit/documentation/AppKit/NSPrintInfo/AttributeKey/pagesDown",
                "doc://com.apple.appkit/documentation/AppKit/NSPrintInfo/AttributeKey/printer",
                "doc://com.apple.appkit/documentation/AppKit/NSPrintInfo/AttributeKey/printerName",
                "doc://com.apple.appkit/documentation/AppKit/NSPrintInfo/AttributeKey/reversePageOrder",
                "doc://com.apple.appkit/documentation/AppKit/NSPrintInfo/AttributeKey/selectionOnly",
                "doc://com.apple.appkit/documentation/AppKit/NSPrintInfo/AttributeKey/time"
              ],
              "title": "Other Attributes"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/seeAlsoSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "Mac Catalyst",
                  "macOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "typedef"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSString",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(cs)NSString",
                    "text": "NSString"
                  },
                  {
                    "kind": "text",
                    "text": " * "
                  },
                  {
                    "kind": "identifier",
                    "text": "NSPrintInfoAttributeKey"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSPrintInfo~1AttributeKey~1lastPage/title",
          "value": "NSPrintLastPage"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSPrintInfo~1AttributeKey~1lastPage/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSPrintLastPage"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSPrintInfo~1AttributeKey~1time/title",
          "value": "NSPrintTime"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSPrintInfo~1AttributeKey~1time/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSPrintTime"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSPrintInfo~1AttributeKey~1pagesAcross/title",
          "value": "NSPrintPagesAcross"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSPrintInfo~1AttributeKey~1pagesAcross/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSPrintPagesAcross"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSPrintInfo/title",
          "value": "NSPrintInfo"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSPrintInfo/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSPrintInfo"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSPrintInfo/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSPrintInfo"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSPrintInfo~1AttributeKey~1allPages/title",
          "value": "NSPrintAllPages"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSPrintInfo~1AttributeKey~1allPages/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSPrintAllPages"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSPrintInfo~1JobDisposition-swift.struct~1save/title",
          "value": "NSPrintSaveJob"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSPrintInfo~1JobDisposition-swift.struct~1save/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSPrintSaveJob"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSPrintInfo~1AttributeKey~1printer/title",
          "value": "NSPrintPrinter"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSPrintInfo~1AttributeKey~1printer/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSPrintPrinter"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSPrintInfo~1AttributeKey~1faxNumber/title",
          "value": "NSPrintFaxNumber"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSPrintInfo~1AttributeKey~1faxNumber/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSPrintFaxNumber"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:objc(cs)NSString/abstract",
          "value": [
            {
              "text": "A static, plain-text Unicode string object.",
              "type": "text"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSPrintInfo~1jobDisposition-swift.property/title",
          "value": "jobDisposition"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSPrintInfo~1jobDisposition-swift.property/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "jobDisposition"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSPrintInfo~1AttributeKey~1jobSavingURL/title",
          "value": "NSPrintJobSavingURL"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSPrintInfo~1AttributeKey~1jobSavingURL/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSPrintJobSavingURL"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSPrintInfo~1AttributeKey~1horizontalPagination/title",
          "value": "NSPrintHorizontalPagination"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSPrintInfo~1AttributeKey~1horizontalPagination/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSPrintHorizontalPagination"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSPrintInfo~1AttributeKey~1bottomMargin/title",
          "value": "NSPrintBottomMargin"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSPrintInfo~1AttributeKey~1bottomMargin/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSPrintBottomMargin"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSPrintInfo~1AttributeKey~1verticallyCentered/title",
          "value": "NSPrintVerticallyCentered"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSPrintInfo~1AttributeKey~1verticallyCentered/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSPrintVerticallyCentered"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSPrintInfo~1AttributeKey~1copies/title",
          "value": "NSPrintCopies"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSPrintInfo~1AttributeKey~1copies/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSPrintCopies"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSPrintInfo~1AttributeKey~1firstPage/title",
          "value": "NSPrintFirstPage"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSPrintInfo~1AttributeKey~1firstPage/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSPrintFirstPage"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSPrintInfo~1AttributeKey~1horizontallyCentered/title",
          "value": "NSPrintHorizontallyCentered"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSPrintInfo~1AttributeKey~1horizontallyCentered/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSPrintHorizontallyCentered"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSPrintInfo~1AttributeKey~1pagesDown/title",
          "value": "NSPrintPagesDown"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSPrintInfo~1AttributeKey~1pagesDown/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSPrintPagesDown"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSPrintInfo~1AttributeKey~1topMargin/title",
          "value": "NSPrintTopMargin"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSPrintInfo~1AttributeKey~1topMargin/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSPrintTopMargin"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSPrintInfo~1AttributeKey~1scalingFactor/title",
          "value": "NSPrintScalingFactor"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSPrintInfo~1AttributeKey~1scalingFactor/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSPrintScalingFactor"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSPrintInfo~1AttributeKey~1jobSavingFileNameExtensionHidden/title",
          "value": "NSPrintJobSavingFileNameExtensionHidden"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSPrintInfo~1AttributeKey~1jobSavingFileNameExtensionHidden/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSPrintJobSavingFileNameExtensionHidden"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSPrintInfo~1AttributeKey~1jobDisposition/title",
          "value": "NSPrintJobDisposition"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSPrintInfo~1AttributeKey~1jobDisposition/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSPrintJobDisposition"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSPrintInfo~1AttributeKey~1rightMargin/title",
          "value": "NSPrintRightMargin"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSPrintInfo~1AttributeKey~1rightMargin/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSPrintRightMargin"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSPrintInfo~1AttributeKey~1detailedErrorReporting/title",
          "value": "NSPrintDetailedErrorReporting"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSPrintInfo~1AttributeKey~1detailedErrorReporting/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSPrintDetailedErrorReporting"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSPrintInfo~1AttributeKey~1printerName/title",
          "value": "NSPrintPrinterName"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSPrintInfo~1AttributeKey~1printerName/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSPrintPrinterName"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSPrintInfo~1AttributeKey~1reversePageOrder/title",
          "value": "NSPrintReversePageOrder"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSPrintInfo~1AttributeKey~1reversePageOrder/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSPrintReversePageOrder"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSPrintInfo~1AttributeKey~1mustCollate/title",
          "value": "NSPrintMustCollate"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSPrintInfo~1AttributeKey~1mustCollate/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSPrintMustCollate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSPrintInfo~1AttributeKey~1selectionOnly/title",
          "value": "NSPrintSelectionOnly"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSPrintInfo~1AttributeKey~1selectionOnly/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSPrintSelectionOnly"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSPrintInfo~1AttributeKey~1leftMargin/title",
          "value": "NSPrintLeftMargin"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSPrintInfo~1AttributeKey~1leftMargin/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSPrintLeftMargin"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSPrintInfo~1AttributeKey/title",
          "value": "NSPrintInfoAttributeKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSPrintInfo~1AttributeKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSPrintInfoAttributeKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSPrintInfo~1AttributeKey/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSPrintInfoAttributeKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSPrintInfo~1AttributeKey~1orientation/title",
          "value": "NSPrintOrientation"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSPrintInfo~1AttributeKey~1orientation/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSPrintOrientation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSPrintInfo~1AttributeKey~1paperSize/title",
          "value": "NSPrintPaperSize"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSPrintInfo~1AttributeKey~1paperSize/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSPrintPaperSize"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSPrintInfo~1AttributeKey~1paperName/title",
          "value": "NSPrintPaperName"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSPrintInfo~1AttributeKey~1paperName/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSPrintPaperName"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSPrintInfo~1AttributeKey~1verticalPagination/title",
          "value": "NSPrintVerticalPagination"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSPrintInfo~1AttributeKey~1verticalPagination/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSPrintVerticalPagination"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSPrintInfo~1AttributeKey~1headerAndFooter/title",
          "value": "NSPrintHeaderAndFooter"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSPrintInfo~1AttributeKey~1headerAndFooter/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSPrintHeaderAndFooter"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/appkit/nsprintinfo/attributekey"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/appkit/nsprintinfo/attributekey"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
