{
  "abstract": [
    {
      "text": "An error that indicates the requested operation can’t complete due to an unknown error.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.mediaplayer/documentation/MediaPlayer",
        "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPError",
        "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPError/Code"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPError/Code/unknown"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@MPErrorCode@MPErrorUnknown",
    "fragments": [
      {
        "kind": "keyword",
        "text": "case"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "unknown"
      }
    ],
    "modules": [
      {
        "name": "Media Player"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "MPErrorUnknown"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "9.3",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "9.3",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.1",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.14.2",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "9.0",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "5.0",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Case",
    "symbolKind": "case",
    "title": "MPError.Code.unknown"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "case"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "unknown"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.mediaplayer/documentation/MediaPlayer": {
      "abstract": [
        {
          "text": "Find and play songs, audio podcasts, audio books, and more from within your app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.mediaplayer/documentation/MediaPlayer",
      "kind": "symbol",
      "role": "collection",
      "title": "Media Player",
      "type": "topic",
      "url": "/documentation/mediaplayer"
    },
    "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPError": {
      "abstract": [
        {
          "text": "A structure that represents a framework error.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MPError"
        }
      ],
      "identifier": "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPError",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MPError"
        }
      ],
      "role": "symbol",
      "title": "MPError",
      "type": "topic",
      "url": "/documentation/mediaplayer/mperror"
    },
    "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPError/Code": {
      "abstract": [
        {
          "text": "An enumeration that represents error codes for framework operations.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPError/Code",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "Code"
        }
      ],
      "role": "symbol",
      "title": "MPError.Code",
      "type": "topic",
      "url": "/documentation/mediaplayer/mperror/code"
    },
    "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPError/Code/cancelled": {
      "abstract": [
        {
          "text": "An error that indicates the system canceled the requested operation before it completed.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "cancelled"
        }
      ],
      "identifier": "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPError/Code/cancelled",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MPErrorCancelled"
        }
      ],
      "role": "symbol",
      "title": "MPError.Code.cancelled",
      "type": "topic",
      "url": "/documentation/mediaplayer/mperror/code/cancelled"
    },
    "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPError/Code/cloudServiceCapabilityMissing": {
      "abstract": [
        {
          "text": "An error that indicates the operation can’t complete because iCloud services aren’t enabled.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "cloudServiceCapabilityMissing"
        }
      ],
      "identifier": "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPError/Code/cloudServiceCapabilityMissing",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MPErrorCloudServiceCapabilityMissing"
        }
      ],
      "role": "symbol",
      "title": "MPError.Code.cloudServiceCapabilityMissing",
      "type": "topic",
      "url": "/documentation/mediaplayer/mperror/code/cloudservicecapabilitymissing"
    },
    "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPError/Code/networkConnectionFailed": {
      "abstract": [
        {
          "text": "An error that indicates the operation failed because the device can’t connect to the network.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "networkConnectionFailed"
        }
      ],
      "identifier": "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPError/Code/networkConnectionFailed",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MPErrorNetworkConnectionFailed"
        }
      ],
      "role": "symbol",
      "title": "MPError.Code.networkConnectionFailed",
      "type": "topic",
      "url": "/documentation/mediaplayer/mperror/code/networkconnectionfailed"
    },
    "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPError/Code/notFound": {
      "abstract": [
        {
          "text": "An error that indicates the operation failed because the system can’t find the requested identifier in the current storefront.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "notFound"
        }
      ],
      "identifier": "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPError/Code/notFound",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MPErrorNotFound"
        }
      ],
      "role": "symbol",
      "title": "MPError.Code.notFound",
      "type": "topic",
      "url": "/documentation/mediaplayer/mperror/code/notfound"
    },
    "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPError/Code/notSupported": {
      "abstract": [
        {
          "text": "An error that indicates the requested operation failed because the system doesn’t support it.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "notSupported"
        }
      ],
      "identifier": "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPError/Code/notSupported",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MPErrorNotSupported"
        }
      ],
      "role": "symbol",
      "title": "MPError.Code.notSupported",
      "type": "topic",
      "url": "/documentation/mediaplayer/mperror/code/notsupported"
    },
    "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPError/Code/permissionDenied": {
      "abstract": [
        {
          "text": "An error that indicates the operation can’t complete because the user doesn’t have permission to execute the operation.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "permissionDenied"
        }
      ],
      "identifier": "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPError/Code/permissionDenied",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MPErrorPermissionDenied"
        }
      ],
      "role": "symbol",
      "title": "MPError.Code.permissionDenied",
      "type": "topic",
      "url": "/documentation/mediaplayer/mperror/code/permissiondenied"
    },
    "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPError/Code/requestTimedOut": {
      "abstract": [
        {
          "text": "An error that indicates the requested operation timed out.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "requestTimedOut"
        }
      ],
      "identifier": "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPError/Code/requestTimedOut",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MPErrorRequestTimedOut"
        }
      ],
      "role": "symbol",
      "title": "MPError.Code.requestTimedOut",
      "type": "topic",
      "url": "/documentation/mediaplayer/mperror/code/requesttimedout"
    },
    "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPError/Code/unknown": {
      "abstract": [
        {
          "text": "An error that indicates the requested operation can’t complete due to an unknown error.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "unknown"
        }
      ],
      "identifier": "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPError/Code/unknown",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MPErrorUnknown"
        }
      ],
      "role": "symbol",
      "title": "MPError.Code.unknown",
      "type": "topic",
      "url": "/documentation/mediaplayer/mperror/code/unknown"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Error-codes",
      "generated": true,
      "identifiers": [
        "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPError/Code/cancelled",
        "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPError/Code/cloudServiceCapabilityMissing",
        "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPError/Code/networkConnectionFailed",
        "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPError/Code/notFound",
        "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPError/Code/notSupported",
        "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPError/Code/permissionDenied",
        "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPError/Code/requestTimedOut"
      ],
      "title": "Error codes"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "9.3",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "9.3",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.1",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.14.2",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "9.0",
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "5.0",
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration Case"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "MPErrorUnknown"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "case"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MPErrorUnknown"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.mediaplayer/documentation/MediaPlayer",
                "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPError/Code"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Error-codes",
              "generated": true,
              "identifiers": [
                "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPError/Code/cancelled",
                "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPError/Code/cloudServiceCapabilityMissing",
                "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPError/Code/networkConnectionFailed",
                "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPError/Code/notFound",
                "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPError/Code/notSupported",
                "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPError/Code/permissionDenied",
                "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPError/Code/requestTimedOut"
              ],
              "title": "Error codes"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "identifier",
                    "text": "MPErrorUnknown"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaplayer~1documentation~1MediaPlayer~1MPError~1Code~1permissionDenied/title",
          "value": "MPErrorPermissionDenied"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaplayer~1documentation~1MediaPlayer~1MPError~1Code~1permissionDenied/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MPErrorPermissionDenied"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaplayer~1documentation~1MediaPlayer~1MPError~1Code~1notFound/title",
          "value": "MPErrorNotFound"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaplayer~1documentation~1MediaPlayer~1MPError~1Code~1notFound/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MPErrorNotFound"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaplayer~1documentation~1MediaPlayer~1MPError~1Code~1requestTimedOut/title",
          "value": "MPErrorRequestTimedOut"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaplayer~1documentation~1MediaPlayer~1MPError~1Code~1requestTimedOut/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MPErrorRequestTimedOut"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaplayer~1documentation~1MediaPlayer~1MPError~1Code/title",
          "value": "MPErrorCode"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaplayer~1documentation~1MediaPlayer~1MPError~1Code/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MPErrorCode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaplayer~1documentation~1MediaPlayer~1MPError~1Code/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MPErrorCode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaplayer~1documentation~1MediaPlayer~1MPError~1Code~1unknown/title",
          "value": "MPErrorUnknown"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaplayer~1documentation~1MediaPlayer~1MPError~1Code~1unknown/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MPErrorUnknown"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaplayer~1documentation~1MediaPlayer~1MPError~1Code~1cancelled/title",
          "value": "MPErrorCancelled"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaplayer~1documentation~1MediaPlayer~1MPError~1Code~1cancelled/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MPErrorCancelled"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaplayer~1documentation~1MediaPlayer~1MPError~1Code~1networkConnectionFailed/title",
          "value": "MPErrorNetworkConnectionFailed"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaplayer~1documentation~1MediaPlayer~1MPError~1Code~1networkConnectionFailed/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MPErrorNetworkConnectionFailed"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaplayer~1documentation~1MediaPlayer~1MPError~1Code~1cloudServiceCapabilityMissing/title",
          "value": "MPErrorCloudServiceCapabilityMissing"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaplayer~1documentation~1MediaPlayer~1MPError~1Code~1cloudServiceCapabilityMissing/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MPErrorCloudServiceCapabilityMissing"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaplayer~1documentation~1MediaPlayer~1MPError~1Code~1notSupported/title",
          "value": "MPErrorNotSupported"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaplayer~1documentation~1MediaPlayer~1MPError~1Code~1notSupported/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MPErrorNotSupported"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/mediaplayer/mperror/code/unknown"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/mediaplayer/mperror/code/unknown"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
