{
  "abstract": [
    {
      "text": "Operations for setting up page breaks, a display box, and display direction.",
      "type": "text"
    }
  ],
  "diffAvailability": {
    "major": {
      "change": "modified",
      "platform": "Xcode",
      "versions": [
        "16.0",
        "16.3 beta 2"
      ]
    }
  },
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.pdfkit/documentation/PDFKit",
        "doc://com.apple.pdfkit/documentation/PDFKit/PDFView",
        "doc://com.apple.pdfkit/documentation/PDFKit/configurations"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.pdfkit/documentation/PDFKit/additional-display-configurations"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "PDFKit"
      }
    ],
    "role": "collectionGroup",
    "roleHeading": "API Collection",
    "title": "Additional Display Configurations"
  },
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.pdfkit/documentation/PDFKit": {
      "abstract": [
        {
          "text": "Display and manipulate PDF documents in your apps.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.pdfkit/documentation/PDFKit",
      "kind": "symbol",
      "role": "collection",
      "title": "PDFKit",
      "type": "topic",
      "url": "/documentation/pdfkit"
    },
    "doc://com.apple.pdfkit/documentation/PDFKit/PDFDisplayMode": {
      "abstract": [
        {
          "text": "A wrapper for the chosen display mode constant.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "PDFDisplayMode"
        }
      ],
      "identifier": "doc://com.apple.pdfkit/documentation/PDFKit/PDFDisplayMode",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PDFDisplayMode"
        }
      ],
      "role": "symbol",
      "title": "PDFDisplayMode",
      "type": "topic",
      "url": "/documentation/pdfkit/pdfdisplaymode"
    },
    "doc://com.apple.pdfkit/documentation/PDFKit/PDFView": {
      "abstract": [
        {
          "text": "An object that encapsulates the functionality of PDF Kit into a single widget that you can add to your application using Interface Builder.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "PDFView"
        }
      ],
      "identifier": "doc://com.apple.pdfkit/documentation/PDFKit/PDFView",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PDFView"
        }
      ],
      "role": "symbol",
      "title": "PDFView",
      "type": "topic",
      "url": "/documentation/pdfkit/pdfview"
    },
    "doc://com.apple.pdfkit/documentation/PDFKit/PDFView/displayBox": {
      "abstract": [
        {
          "text": "The current style of display box.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "displayBox"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@PDFDisplayBox",
          "text": "PDFDisplayBox"
        }
      ],
      "identifier": "doc://com.apple.pdfkit/documentation/PDFKit/PDFView/displayBox",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "displayBox"
        }
      ],
      "role": "symbol",
      "title": "displayBox",
      "type": "topic",
      "url": "/documentation/pdfkit/pdfview/displaybox"
    },
    "doc://com.apple.pdfkit/documentation/PDFKit/PDFView/displayDirection": {
      "abstract": [
        {
          "text": "The layout direction, either vertical or horizontal, for the given display mode.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "displayDirection"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@PDFDisplayDirection",
          "text": "PDFDisplayDirection"
        }
      ],
      "identifier": "doc://com.apple.pdfkit/documentation/PDFKit/PDFView/displayDirection",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "displayDirection"
        }
      ],
      "role": "symbol",
      "title": "displayDirection",
      "type": "topic",
      "url": "/documentation/pdfkit/pdfview/displaydirection"
    },
    "doc://com.apple.pdfkit/documentation/PDFKit/PDFView/displayMode": {
      "abstract": [
        {
          "text": "The current display mode.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "displayMode"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@PDFDisplayMode",
          "text": "PDFDisplayMode"
        }
      ],
      "identifier": "doc://com.apple.pdfkit/documentation/PDFKit/PDFView/displayMode",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "displayMode"
        }
      ],
      "role": "symbol",
      "title": "displayMode",
      "type": "topic",
      "url": "/documentation/pdfkit/pdfview/displaymode"
    },
    "doc://com.apple.pdfkit/documentation/PDFKit/PDFView/displaysPageBreaks": {
      "abstract": [
        {
          "text": "A Boolean value indicating whether the view is displaying page breaks.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "displaysPageBreaks"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.pdfkit/documentation/PDFKit/PDFView/displaysPageBreaks",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "displaysPageBreaks"
        }
      ],
      "role": "symbol",
      "title": "displaysPageBreaks",
      "type": "topic",
      "url": "/documentation/pdfkit/pdfview/displayspagebreaks"
    },
    "doc://com.apple.pdfkit/documentation/PDFKit/PDFView/displaysRTL": {
      "abstract": [
        {
          "text": "The presentation of pages from right-to-left.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "displaysRTL"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.pdfkit/documentation/PDFKit/PDFView/displaysRTL",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "displaysRTL"
        }
      ],
      "role": "symbol",
      "title": "displaysRTL",
      "type": "topic",
      "url": "/documentation/pdfkit/pdfview/displaysrtl"
    },
    "doc://com.apple.pdfkit/documentation/PDFKit/PDFView/pageBreakMargins": {
      "abstract": [
        {
          "text": "The spacing between pages as defined by the top, bottom, left, and right margins.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "pageBreakMargins"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@UIEdgeInsets",
          "text": "UIEdgeInsets"
        }
      ],
      "identifier": "doc://com.apple.pdfkit/documentation/PDFKit/PDFView/pageBreakMargins",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "pageBreakMargins"
        }
      ],
      "role": "symbol",
      "title": "pageBreakMargins",
      "type": "topic",
      "url": "/documentation/pdfkit/pdfview/pagebreakmargins"
    },
    "doc://com.apple.pdfkit/documentation/PDFKit/book-display": {
      "abstract": [
        {
          "text": "Operations to setup a book display for a PDF view.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.pdfkit/documentation/PDFKit/book-display",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Book Display",
      "type": "topic",
      "url": "/documentation/pdfkit/book-display"
    },
    "doc://com.apple.pdfkit/documentation/PDFKit/configurations": {
      "abstract": [
        {
          "text": "Define display modes, scaling, rendering, printing and graphics properties.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.pdfkit/documentation/PDFKit/configurations",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Configurations",
      "type": "topic",
      "url": "/documentation/pdfkit/configurations"
    },
    "doc://com.apple.pdfkit/documentation/PDFKit/graphics-properties": {
      "abstract": [
        {
          "text": "Operations to define the background color, antialiasing, and greeking for a PDF view.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.pdfkit/documentation/PDFKit/graphics-properties",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Graphics Properties",
      "type": "topic",
      "url": "/documentation/pdfkit/graphics-properties"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Working-with-Display-Modes-and-Characteristics",
      "generated": true,
      "identifiers": [
        "doc://com.apple.pdfkit/documentation/PDFKit/PDFView/displayMode",
        "doc://com.apple.pdfkit/documentation/PDFKit/PDFDisplayMode",
        "doc://com.apple.pdfkit/documentation/PDFKit/book-display",
        "doc://com.apple.pdfkit/documentation/PDFKit/graphics-properties"
      ],
      "title": "Working with Display Modes and Characteristics"
    }
  ],
  "topicSections": [
    {
      "anchor": "Defining-Display-Box",
      "identifiers": [
        "doc://com.apple.pdfkit/documentation/PDFKit/PDFView/displayBox"
      ],
      "title": "Defining Display Box"
    },
    {
      "anchor": "Defining-Page-Breaks",
      "identifiers": [
        "doc://com.apple.pdfkit/documentation/PDFKit/PDFView/displaysPageBreaks",
        "doc://com.apple.pdfkit/documentation/PDFKit/PDFView/pageBreakMargins"
      ],
      "title": "Defining Page Breaks"
    },
    {
      "anchor": "Defining-Display-Direction",
      "identifiers": [
        "doc://com.apple.pdfkit/documentation/PDFKit/PDFView/displayDirection",
        "doc://com.apple.pdfkit/documentation/PDFKit/PDFView/displaysRTL"
      ],
      "title": "Defining Display Direction"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Defining-Display-Box",
              "identifiers": [
                "doc://com.apple.pdfkit/documentation/PDFKit/PDFView/displayBox"
              ],
              "title": "Defining Display Box"
            },
            {
              "anchor": "Defining-Page-Breaks",
              "identifiers": [
                "doc://com.apple.pdfkit/documentation/PDFKit/PDFView/displaysPageBreaks",
                "doc://com.apple.pdfkit/documentation/PDFKit/PDFView/pageBreakMargins"
              ],
              "title": "Defining Page Breaks"
            },
            {
              "anchor": "Defining-Display-Direction",
              "identifiers": [
                "doc://com.apple.pdfkit/documentation/PDFKit/PDFView/displayDirection",
                "doc://com.apple.pdfkit/documentation/PDFKit/PDFView/displaysRTL"
              ],
              "title": "Defining Display Direction"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Working-with-Display-Modes-and-Characteristics",
              "generated": true,
              "identifiers": [
                "doc://com.apple.pdfkit/documentation/PDFKit/PDFView/displayMode",
                "doc://com.apple.pdfkit/documentation/PDFKit/PDFDisplayMode",
                "doc://com.apple.pdfkit/documentation/PDFKit/book-display",
                "doc://com.apple.pdfkit/documentation/PDFKit/graphics-properties"
              ],
              "title": "Working with Display Modes and Characteristics"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFDisplayMode/title",
          "value": "PDFDisplayMode"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFDisplayMode/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PDFDisplayMode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFDisplayMode/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "PDFDisplayMode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFView~1displayMode/title",
          "value": "displayMode"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFView~1displayMode/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "displayMode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFView~1displayBox/title",
          "value": "displayBox"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFView~1displayBox/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "displayBox"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFView~1displaysRTL/title",
          "value": "displaysRTL"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFView~1displaysRTL/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "displaysRTL"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFView~1displaysPageBreaks/title",
          "value": "displaysPageBreaks"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFView~1displaysPageBreaks/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "displaysPageBreaks"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFView/title",
          "value": "PDFView"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFView/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PDFView"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFView/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "PDFView"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFView~1pageBreakMargins/title",
          "value": "pageBreakMargins"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFView~1pageBreakMargins/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "pageBreakMargins"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFView~1displayDirection/title",
          "value": "displayDirection"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFView~1displayDirection/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "displayDirection"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/pdfkit/additional-display-configurations"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/pdfkit/additional-display-configurations"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
