{
  "abstract": [
    {
      "text": "Operations to setup a book display for a PDF view.",
      "type": "text"
    }
  ],
  "diffAvailability": {
    "major": {
      "change": "modified",
      "platform": "Xcode",
      "versions": [
        "16.0",
        "16.3 beta 2"
      ]
    }
  },
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.pdfkit/documentation/PDFKit",
        "doc://com.apple.pdfkit/documentation/PDFKit/PDFView",
        "doc://com.apple.pdfkit/documentation/PDFKit/configurations"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.pdfkit/documentation/PDFKit/book-display"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "PDFKit"
      }
    ],
    "role": "collectionGroup",
    "roleHeading": "API Collection",
    "title": "Book Display"
  },
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.pdfkit/documentation/PDFKit": {
      "abstract": [
        {
          "text": "Display and manipulate PDF documents in your apps.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.pdfkit/documentation/PDFKit",
      "kind": "symbol",
      "role": "collection",
      "title": "PDFKit",
      "type": "topic",
      "url": "/documentation/pdfkit"
    },
    "doc://com.apple.pdfkit/documentation/PDFKit/PDFDisplayMode": {
      "abstract": [
        {
          "text": "A wrapper for the chosen display mode constant.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "PDFDisplayMode"
        }
      ],
      "identifier": "doc://com.apple.pdfkit/documentation/PDFKit/PDFDisplayMode",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PDFDisplayMode"
        }
      ],
      "role": "symbol",
      "title": "PDFDisplayMode",
      "type": "topic",
      "url": "/documentation/pdfkit/pdfdisplaymode"
    },
    "doc://com.apple.pdfkit/documentation/PDFKit/PDFView": {
      "abstract": [
        {
          "text": "An object that encapsulates the functionality of PDF Kit into a single widget that you can add to your application using Interface Builder.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "PDFView"
        }
      ],
      "identifier": "doc://com.apple.pdfkit/documentation/PDFKit/PDFView",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PDFView"
        }
      ],
      "role": "symbol",
      "title": "PDFView",
      "type": "topic",
      "url": "/documentation/pdfkit/pdfview"
    },
    "doc://com.apple.pdfkit/documentation/PDFKit/PDFView/displayMode": {
      "abstract": [
        {
          "text": "The current display mode.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "displayMode"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@PDFDisplayMode",
          "text": "PDFDisplayMode"
        }
      ],
      "identifier": "doc://com.apple.pdfkit/documentation/PDFKit/PDFView/displayMode",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "displayMode"
        }
      ],
      "role": "symbol",
      "title": "displayMode",
      "type": "topic",
      "url": "/documentation/pdfkit/pdfview/displaymode"
    },
    "doc://com.apple.pdfkit/documentation/PDFKit/PDFView/displaysAsBook": {
      "abstract": [
        {
          "text": "A Boolean value indicating whether the view will display the first page as a book cover (meaningful only when the document is in two-up or two-up continuous display mode).",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "displaysAsBook"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.pdfkit/documentation/PDFKit/PDFView/displaysAsBook",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "displaysAsBook"
        }
      ],
      "role": "symbol",
      "title": "displaysAsBook",
      "type": "topic",
      "url": "/documentation/pdfkit/pdfview/displaysasbook"
    },
    "doc://com.apple.pdfkit/documentation/PDFKit/PDFView/isUsingPageViewController": {
      "abstract": [
        {
          "text": "A Boolean value indicating whether the scroll view is using a ",
          "type": "text"
        },
        {
          "code": "UIPageViewController",
          "type": "codeVoice"
        },
        {
          "text": ".",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "isUsingPageViewController"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.pdfkit/documentation/PDFKit/PDFView/isUsingPageViewController",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "isUsingPageViewController"
        }
      ],
      "role": "symbol",
      "title": "isUsingPageViewController",
      "type": "topic",
      "url": "/documentation/pdfkit/pdfview/isusingpageviewcontroller"
    },
    "doc://com.apple.pdfkit/documentation/PDFKit/PDFView/usePageViewController(_:withViewOptions:)": {
      "abstract": [
        {
          "text": "Changes the scroll view to use a ",
          "type": "text"
        },
        {
          "code": "UIPageViewController",
          "type": "codeVoice"
        },
        {
          "text": " to layout and navigate pages.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "usePageViewController"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "withViewOptions"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s11AnyHashableV",
          "text": "AnyHashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "keyword",
          "text": "Any"
        },
        {
          "kind": "text",
          "text": "]?)"
        }
      ],
      "identifier": "doc://com.apple.pdfkit/documentation/PDFKit/PDFView/usePageViewController(_:withViewOptions:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "usePageViewController:withViewOptions:"
        }
      ],
      "role": "symbol",
      "title": "usePageViewController(_:withViewOptions:)",
      "type": "topic",
      "url": "/documentation/pdfkit/pdfview/usepageviewcontroller(_:withviewoptions:)"
    },
    "doc://com.apple.pdfkit/documentation/PDFKit/additional-display-configurations": {
      "abstract": [
        {
          "text": "Operations for setting up page breaks, a display box, and display direction.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.pdfkit/documentation/PDFKit/additional-display-configurations",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Additional Display Configurations",
      "type": "topic",
      "url": "/documentation/pdfkit/additional-display-configurations"
    },
    "doc://com.apple.pdfkit/documentation/PDFKit/configurations": {
      "abstract": [
        {
          "text": "Define display modes, scaling, rendering, printing and graphics properties.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.pdfkit/documentation/PDFKit/configurations",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Configurations",
      "type": "topic",
      "url": "/documentation/pdfkit/configurations"
    },
    "doc://com.apple.pdfkit/documentation/PDFKit/graphics-properties": {
      "abstract": [
        {
          "text": "Operations to define the background color, antialiasing, and greeking for a PDF view.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.pdfkit/documentation/PDFKit/graphics-properties",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Graphics Properties",
      "type": "topic",
      "url": "/documentation/pdfkit/graphics-properties"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Working-with-Display-Modes-and-Characteristics",
      "generated": true,
      "identifiers": [
        "doc://com.apple.pdfkit/documentation/PDFKit/PDFView/displayMode",
        "doc://com.apple.pdfkit/documentation/PDFKit/PDFDisplayMode",
        "doc://com.apple.pdfkit/documentation/PDFKit/additional-display-configurations",
        "doc://com.apple.pdfkit/documentation/PDFKit/graphics-properties"
      ],
      "title": "Working with Display Modes and Characteristics"
    }
  ],
  "topicSections": [
    {
      "anchor": "Displaying-as-Book",
      "identifiers": [
        "doc://com.apple.pdfkit/documentation/PDFKit/PDFView/displaysAsBook",
        "doc://com.apple.pdfkit/documentation/PDFKit/PDFView/isUsingPageViewController",
        "doc://com.apple.pdfkit/documentation/PDFKit/PDFView/usePageViewController(_:withViewOptions:)"
      ],
      "title": "Displaying as Book"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Displaying-as-Book",
              "identifiers": [
                "doc://com.apple.pdfkit/documentation/PDFKit/PDFView/displaysAsBook",
                "doc://com.apple.pdfkit/documentation/PDFKit/PDFView/isUsingPageViewController",
                "doc://com.apple.pdfkit/documentation/PDFKit/PDFView/usePageViewController(_:withViewOptions:)"
              ],
              "title": "Displaying as Book"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Working-with-Display-Modes-and-Characteristics",
              "generated": true,
              "identifiers": [
                "doc://com.apple.pdfkit/documentation/PDFKit/PDFView/displayMode",
                "doc://com.apple.pdfkit/documentation/PDFKit/PDFDisplayMode",
                "doc://com.apple.pdfkit/documentation/PDFKit/additional-display-configurations",
                "doc://com.apple.pdfkit/documentation/PDFKit/graphics-properties"
              ],
              "title": "Working with Display Modes and Characteristics"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFDisplayMode/title",
          "value": "PDFDisplayMode"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFDisplayMode/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PDFDisplayMode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFDisplayMode/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "PDFDisplayMode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFView~1isUsingPageViewController/title",
          "value": "isUsingPageViewController"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFView~1isUsingPageViewController/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "isUsingPageViewController"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFView~1displaysAsBook/title",
          "value": "displaysAsBook"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFView~1displaysAsBook/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "displaysAsBook"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFView~1displayMode/title",
          "value": "displayMode"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFView~1displayMode/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "displayMode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFView~1usePageViewController(_:withViewOptions:)/title",
          "value": "usePageViewController:withViewOptions:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFView~1usePageViewController(_:withViewOptions:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "usePageViewController:withViewOptions:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFView/title",
          "value": "PDFView"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFView/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PDFView"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFView/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "PDFView"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/pdfkit/book-display"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/pdfkit/book-display"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
