{
  "abstract": [
    {
      "text": "Define display modes, scaling, rendering, printing and graphics properties.",
      "type": "text"
    }
  ],
  "diffAvailability": {
    "major": {
      "change": "modified",
      "platform": "Xcode",
      "versions": [
        "16.0",
        "16.3 beta 2"
      ]
    }
  },
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.pdfkit/documentation/PDFKit",
        "doc://com.apple.pdfkit/documentation/PDFKit/PDFView"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.pdfkit/documentation/PDFKit/configurations"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "PDFKit"
      }
    ],
    "role": "collectionGroup",
    "roleHeading": "API Collection",
    "title": "Configurations"
  },
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.pdfkit/documentation/PDFKit": {
      "abstract": [
        {
          "text": "Display and manipulate PDF documents in your apps.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.pdfkit/documentation/PDFKit",
      "kind": "symbol",
      "role": "collection",
      "title": "PDFKit",
      "type": "topic",
      "url": "/documentation/pdfkit"
    },
    "doc://com.apple.pdfkit/documentation/PDFKit/PDFDisplayMode": {
      "abstract": [
        {
          "text": "A wrapper for the chosen display mode constant.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "PDFDisplayMode"
        }
      ],
      "identifier": "doc://com.apple.pdfkit/documentation/PDFKit/PDFDisplayMode",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PDFDisplayMode"
        }
      ],
      "role": "symbol",
      "title": "PDFDisplayMode",
      "type": "topic",
      "url": "/documentation/pdfkit/pdfdisplaymode"
    },
    "doc://com.apple.pdfkit/documentation/PDFKit/PDFView": {
      "abstract": [
        {
          "text": "An object that encapsulates the functionality of PDF Kit into a single widget that you can add to your application using Interface Builder.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "PDFView"
        }
      ],
      "identifier": "doc://com.apple.pdfkit/documentation/PDFKit/PDFView",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PDFView"
        }
      ],
      "role": "symbol",
      "title": "PDFView",
      "type": "topic",
      "url": "/documentation/pdfkit/pdfview"
    },
    "doc://com.apple.pdfkit/documentation/PDFKit/PDFView/autoScales": {
      "abstract": [
        {
          "text": "A Boolean value indicating whether autoscaling is set.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "autoScales"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.pdfkit/documentation/PDFKit/PDFView/autoScales",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "autoScales"
        }
      ],
      "role": "symbol",
      "title": "autoScales",
      "type": "topic",
      "url": "/documentation/pdfkit/pdfview/autoscales"
    },
    "doc://com.apple.pdfkit/documentation/PDFKit/PDFView/displayMode": {
      "abstract": [
        {
          "text": "The current display mode.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "displayMode"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@PDFDisplayMode",
          "text": "PDFDisplayMode"
        }
      ],
      "identifier": "doc://com.apple.pdfkit/documentation/PDFKit/PDFView/displayMode",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "displayMode"
        }
      ],
      "role": "symbol",
      "title": "displayMode",
      "type": "topic",
      "url": "/documentation/pdfkit/pdfview/displaymode"
    },
    "doc://com.apple.pdfkit/documentation/PDFKit/PDFView/documentView": {
      "abstract": [
        {
          "text": "The innermost view used by ",
          "type": "text"
        },
        {
          "code": "PDFView",
          "type": "codeVoice"
        },
        {
          "text": " or by your ",
          "type": "text"
        },
        {
          "code": "PDFView",
          "type": "codeVoice"
        },
        {
          "text": " subclass.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "documentView"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UIView",
          "text": "UIView"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.pdfkit/documentation/PDFKit/PDFView/documentView",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "documentView"
        }
      ],
      "role": "symbol",
      "title": "documentView",
      "type": "topic",
      "url": "/documentation/pdfkit/pdfview/documentview"
    },
    "doc://com.apple.pdfkit/documentation/PDFKit/PDFView/draw(_:)": {
      "abstract": [
        {
          "text": "Draw and render a visible page.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "draw"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)PDFPage",
          "text": "PDFPage"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.pdfkit/documentation/PDFKit/PDFView/draw(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "drawPage:"
        }
      ],
      "role": "symbol",
      "title": "draw(_:)",
      "type": "topic",
      "url": "/documentation/pdfkit/pdfview/draw(_:)"
    },
    "doc://com.apple.pdfkit/documentation/PDFKit/PDFView/drawPagePost(_:)": {
      "abstract": [
        {
          "text": "Perform post-page rendering.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "drawPagePost"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)PDFPage",
          "text": "PDFPage"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.pdfkit/documentation/PDFKit/PDFView/drawPagePost(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "drawPagePost:"
        }
      ],
      "role": "symbol",
      "title": "drawPagePost(_:)",
      "type": "topic",
      "url": "/documentation/pdfkit/pdfview/drawpagepost(_:)"
    },
    "doc://com.apple.pdfkit/documentation/PDFKit/PDFView/layoutDocumentView()": {
      "abstract": [
        {
          "text": "Performs layout of the inner views.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "layoutDocumentView"
        },
        {
          "kind": "text",
          "text": "()"
        }
      ],
      "identifier": "doc://com.apple.pdfkit/documentation/PDFKit/PDFView/layoutDocumentView()",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "layoutDocumentView"
        }
      ],
      "role": "symbol",
      "title": "layoutDocumentView()",
      "type": "topic",
      "url": "/documentation/pdfkit/pdfview/layoutdocumentview()"
    },
    "doc://com.apple.pdfkit/documentation/PDFKit/PDFView/maxScaleFactor": {
      "abstract": [
        {
          "text": "The maximum scaling factor for the PDF document.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "maxScaleFactor"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:14CoreFoundation7CGFloatV",
          "text": "CGFloat"
        }
      ],
      "identifier": "doc://com.apple.pdfkit/documentation/PDFKit/PDFView/maxScaleFactor",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "maxScaleFactor"
        }
      ],
      "role": "symbol",
      "title": "maxScaleFactor",
      "type": "topic",
      "url": "/documentation/pdfkit/pdfview/maxscalefactor"
    },
    "doc://com.apple.pdfkit/documentation/PDFKit/PDFView/minScaleFactor": {
      "abstract": [
        {
          "text": "The minimum scaling factor for the PDF document.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "minScaleFactor"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:14CoreFoundation7CGFloatV",
          "text": "CGFloat"
        }
      ],
      "identifier": "doc://com.apple.pdfkit/documentation/PDFKit/PDFView/minScaleFactor",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "minScaleFactor"
        }
      ],
      "role": "symbol",
      "title": "minScaleFactor",
      "type": "topic",
      "url": "/documentation/pdfkit/pdfview/minscalefactor"
    },
    "doc://com.apple.pdfkit/documentation/PDFKit/PDFView/print(with:autoRotate:)": {
      "abstract": [
        {
          "text": "Prints the document with the specified printer information.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "print"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "with"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSPrintInfo",
          "text": "NSPrintInfo"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "autoRotate"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.pdfkit/documentation/PDFKit/PDFView/print(with:autoRotate:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "printWithInfo:autoRotate:"
        }
      ],
      "role": "symbol",
      "title": "print(with:autoRotate:)",
      "type": "topic",
      "url": "/documentation/pdfkit/pdfview/print(with:autorotate:)"
    },
    "doc://com.apple.pdfkit/documentation/PDFKit/PDFView/print(with:autoRotate:pageScaling:)": {
      "abstract": [
        {
          "text": "Prints the document with the specified printer and page-scaling information.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "print"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "with"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSPrintInfo",
          "text": "NSPrintInfo"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "autoRotate"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "pageScaling"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@PDFPrintScalingMode",
          "text": "PDFPrintScalingMode"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.pdfkit/documentation/PDFKit/PDFView/print(with:autoRotate:pageScaling:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "printWithInfo:autoRotate:pageScaling:"
        }
      ],
      "role": "symbol",
      "title": "print(with:autoRotate:pageScaling:)",
      "type": "topic",
      "url": "/documentation/pdfkit/pdfview/print(with:autorotate:pagescaling:)"
    },
    "doc://com.apple.pdfkit/documentation/PDFKit/PDFView/rowSize(for:)": {
      "abstract": [
        {
          "text": "Returns the size needed to display a row of the current document page.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "rowSize"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "for"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)PDFPage",
          "text": "PDFPage"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@CGSize",
          "text": "CGSize"
        }
      ],
      "identifier": "doc://com.apple.pdfkit/documentation/PDFKit/PDFView/rowSize(for:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "rowSizeForPage:"
        }
      ],
      "role": "symbol",
      "title": "rowSize(for:)",
      "type": "topic",
      "url": "/documentation/pdfkit/pdfview/rowsize(for:)"
    },
    "doc://com.apple.pdfkit/documentation/PDFKit/PDFView/scaleFactor": {
      "abstract": [
        {
          "text": "The current scale factor for the view.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "scaleFactor"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:14CoreFoundation7CGFloatV",
          "text": "CGFloat"
        }
      ],
      "identifier": "doc://com.apple.pdfkit/documentation/PDFKit/PDFView/scaleFactor",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "scaleFactor"
        }
      ],
      "role": "symbol",
      "title": "scaleFactor",
      "type": "topic",
      "url": "/documentation/pdfkit/pdfview/scalefactor"
    },
    "doc://com.apple.pdfkit/documentation/PDFKit/PDFView/scaleFactorForSizeToFit": {
      "abstract": [
        {
          "text": "The “size to fit” scale factor that ",
          "type": "text"
        },
        {
          "code": "autoScales",
          "type": "codeVoice"
        },
        {
          "text": " would use for scaling the current document and layout.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "scaleFactorForSizeToFit"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:14CoreFoundation7CGFloatV",
          "text": "CGFloat"
        }
      ],
      "identifier": "doc://com.apple.pdfkit/documentation/PDFKit/PDFView/scaleFactorForSizeToFit",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "scaleFactorForSizeToFit"
        }
      ],
      "role": "symbol",
      "title": "scaleFactorForSizeToFit",
      "type": "topic",
      "url": "/documentation/pdfkit/pdfview/scalefactorforsizetofit"
    },
    "doc://com.apple.pdfkit/documentation/PDFKit/additional-display-configurations": {
      "abstract": [
        {
          "text": "Operations for setting up page breaks, a display box, and display direction.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.pdfkit/documentation/PDFKit/additional-display-configurations",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Additional Display Configurations",
      "type": "topic",
      "url": "/documentation/pdfkit/additional-display-configurations"
    },
    "doc://com.apple.pdfkit/documentation/PDFKit/book-display": {
      "abstract": [
        {
          "text": "Operations to setup a book display for a PDF view.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.pdfkit/documentation/PDFKit/book-display",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Book Display",
      "type": "topic",
      "url": "/documentation/pdfkit/book-display"
    },
    "doc://com.apple.pdfkit/documentation/PDFKit/draw-operations": {
      "abstract": [
        {
          "text": "Draw in a PDF page.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.pdfkit/documentation/PDFKit/draw-operations",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Draw Operations",
      "type": "topic",
      "url": "/documentation/pdfkit/draw-operations"
    },
    "doc://com.apple.pdfkit/documentation/PDFKit/graphics-properties": {
      "abstract": [
        {
          "text": "Operations to define the background color, antialiasing, and greeking for a PDF view.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.pdfkit/documentation/PDFKit/graphics-properties",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Graphics Properties",
      "type": "topic",
      "url": "/documentation/pdfkit/graphics-properties"
    },
    "doc://com.apple.pdfkit/documentation/PDFKit/zoom-operations": {
      "abstract": [
        {
          "text": "Zoom operations for a PDF View.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.pdfkit/documentation/PDFKit/zoom-operations",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Zoom Operations",
      "type": "topic",
      "url": "/documentation/pdfkit/zoom-operations"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "topicSections": [
    {
      "anchor": "Working-with-Display-Modes-and-Characteristics",
      "identifiers": [
        "doc://com.apple.pdfkit/documentation/PDFKit/PDFView/displayMode",
        "doc://com.apple.pdfkit/documentation/PDFKit/PDFDisplayMode",
        "doc://com.apple.pdfkit/documentation/PDFKit/additional-display-configurations",
        "doc://com.apple.pdfkit/documentation/PDFKit/book-display",
        "doc://com.apple.pdfkit/documentation/PDFKit/graphics-properties"
      ],
      "title": "Working with Display Modes and Characteristics"
    },
    {
      "anchor": "Scaling-the-View",
      "identifiers": [
        "doc://com.apple.pdfkit/documentation/PDFKit/PDFView/scaleFactor",
        "doc://com.apple.pdfkit/documentation/PDFKit/PDFView/scaleFactorForSizeToFit",
        "doc://com.apple.pdfkit/documentation/PDFKit/PDFView/maxScaleFactor",
        "doc://com.apple.pdfkit/documentation/PDFKit/PDFView/minScaleFactor",
        "doc://com.apple.pdfkit/documentation/PDFKit/PDFView/autoScales",
        "doc://com.apple.pdfkit/documentation/PDFKit/PDFView/rowSize(for:)",
        "doc://com.apple.pdfkit/documentation/PDFKit/zoom-operations"
      ],
      "title": "Scaling the View"
    },
    {
      "anchor": "Rendering-the-View-and-Printing",
      "identifiers": [
        "doc://com.apple.pdfkit/documentation/PDFKit/PDFView/draw(_:)",
        "doc://com.apple.pdfkit/documentation/PDFKit/PDFView/drawPagePost(_:)",
        "doc://com.apple.pdfkit/documentation/PDFKit/PDFView/print(with:autoRotate:)",
        "doc://com.apple.pdfkit/documentation/PDFKit/PDFView/print(with:autoRotate:pageScaling:)"
      ],
      "title": "Rendering the View and Printing"
    },
    {
      "anchor": "Specializing-the-View",
      "identifiers": [
        "doc://com.apple.pdfkit/documentation/PDFKit/PDFView/documentView",
        "doc://com.apple.pdfkit/documentation/PDFKit/PDFView/layoutDocumentView()",
        "doc://com.apple.pdfkit/documentation/PDFKit/draw-operations"
      ],
      "title": "Specializing the View"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Working-with-Display-Modes-and-Characteristics",
              "identifiers": [
                "doc://com.apple.pdfkit/documentation/PDFKit/PDFView/displayMode",
                "doc://com.apple.pdfkit/documentation/PDFKit/PDFDisplayMode",
                "doc://com.apple.pdfkit/documentation/PDFKit/additional-display-configurations",
                "doc://com.apple.pdfkit/documentation/PDFKit/book-display",
                "doc://com.apple.pdfkit/documentation/PDFKit/graphics-properties"
              ],
              "title": "Working with Display Modes and Characteristics"
            },
            {
              "anchor": "Scaling-the-View",
              "identifiers": [
                "doc://com.apple.pdfkit/documentation/PDFKit/PDFView/scaleFactor",
                "doc://com.apple.pdfkit/documentation/PDFKit/PDFView/scaleFactorForSizeToFit",
                "doc://com.apple.pdfkit/documentation/PDFKit/PDFView/maxScaleFactor",
                "doc://com.apple.pdfkit/documentation/PDFKit/PDFView/minScaleFactor",
                "doc://com.apple.pdfkit/documentation/PDFKit/PDFView/autoScales",
                "doc://com.apple.pdfkit/documentation/PDFKit/PDFView/rowSize(for:)",
                "doc://com.apple.pdfkit/documentation/PDFKit/zoom-operations"
              ],
              "title": "Scaling the View"
            },
            {
              "anchor": "Rendering-the-View-and-Printing",
              "identifiers": [
                "doc://com.apple.pdfkit/documentation/PDFKit/PDFView/draw(_:)",
                "doc://com.apple.pdfkit/documentation/PDFKit/PDFView/drawPagePost(_:)",
                "doc://com.apple.pdfkit/documentation/PDFKit/PDFView/print(with:autoRotate:)",
                "doc://com.apple.pdfkit/documentation/PDFKit/PDFView/print(with:autoRotate:pageScaling:)"
              ],
              "title": "Rendering the View and Printing"
            },
            {
              "anchor": "Specializing-the-View",
              "identifiers": [
                "doc://com.apple.pdfkit/documentation/PDFKit/PDFView/documentView",
                "doc://com.apple.pdfkit/documentation/PDFKit/PDFView/layoutDocumentView()",
                "doc://com.apple.pdfkit/documentation/PDFKit/draw-operations"
              ],
              "title": "Specializing the View"
            }
          ]
        },
        {
          "op": "add",
          "path": "/seeAlsoSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFView~1draw(_:)/title",
          "value": "drawPage:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFView~1draw(_:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "drawPage:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFView~1scaleFactorForSizeToFit/title",
          "value": "scaleFactorForSizeToFit"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFView~1scaleFactorForSizeToFit/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "scaleFactorForSizeToFit"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFView/title",
          "value": "PDFView"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFView/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PDFView"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFView/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "PDFView"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFView~1documentView/title",
          "value": "documentView"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFView~1documentView/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "documentView"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFDisplayMode/title",
          "value": "PDFDisplayMode"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFDisplayMode/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PDFDisplayMode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFDisplayMode/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "PDFDisplayMode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFView~1maxScaleFactor/title",
          "value": "maxScaleFactor"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFView~1maxScaleFactor/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "maxScaleFactor"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFView~1rowSize(for:)/title",
          "value": "rowSizeForPage:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFView~1rowSize(for:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "rowSizeForPage:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFView~1autoScales/title",
          "value": "autoScales"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFView~1autoScales/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "autoScales"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFView~1drawPagePost(_:)/title",
          "value": "drawPagePost:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFView~1drawPagePost(_:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "drawPagePost:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFView~1print(with:autoRotate:pageScaling:)/title",
          "value": "printWithInfo:autoRotate:pageScaling:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFView~1print(with:autoRotate:pageScaling:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "printWithInfo:autoRotate:pageScaling:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFView~1print(with:autoRotate:)/title",
          "value": "printWithInfo:autoRotate:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFView~1print(with:autoRotate:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "printWithInfo:autoRotate:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFView~1scaleFactor/title",
          "value": "scaleFactor"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFView~1scaleFactor/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "scaleFactor"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFView~1layoutDocumentView()/title",
          "value": "layoutDocumentView"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFView~1layoutDocumentView()/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "layoutDocumentView"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFView~1minScaleFactor/title",
          "value": "minScaleFactor"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFView~1minScaleFactor/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "minScaleFactor"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFView~1displayMode/title",
          "value": "displayMode"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFView~1displayMode/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "displayMode"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/pdfkit/configurations"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/pdfkit/configurations"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
