{
  "diffAvailability": {
    "major": {
      "change": "modified",
      "platform": "Xcode",
      "versions": [
        "16.0",
        "16.3 beta 2"
      ]
    }
  },
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.pdfkit/documentation/PDFKit"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.pdfkit/documentation/PDFKit/constants"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "PDFKit"
      }
    ],
    "role": "collectionGroup",
    "roleHeading": "API Collection",
    "title": "PDFKit Constants"
  },
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.pdfkit/documentation/PDFKit": {
      "abstract": [
        {
          "text": "Display and manipulate PDF documents in your apps.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.pdfkit/documentation/PDFKit",
      "kind": "symbol",
      "role": "collection",
      "title": "PDFKit",
      "type": "topic",
      "url": "/documentation/pdfkit"
    },
    "doc://com.apple.pdfkit/documentation/PDFKit/PDFDocumentFoundSelectionKey": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "PDFDocumentFoundSelectionKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.pdfkit/documentation/PDFKit/PDFDocumentFoundSelectionKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PDFDocumentFoundSelectionKey"
        }
      ],
      "role": "symbol",
      "title": "PDFDocumentFoundSelectionKey",
      "type": "topic",
      "url": "/documentation/pdfkit/pdfdocumentfoundselectionkey"
    },
    "doc://com.apple.pdfkit/documentation/PDFKit/PDFDocumentPageIndexKey": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "PDFDocumentPageIndexKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.pdfkit/documentation/PDFKit/PDFDocumentPageIndexKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PDFDocumentPageIndexKey"
        }
      ],
      "role": "symbol",
      "title": "PDFDocumentPageIndexKey",
      "type": "topic",
      "url": "/documentation/pdfkit/pdfdocumentpageindexkey"
    },
    "doc://com.apple.pdfkit/documentation/PDFKit/PDFEdgeInsets": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "PDFEdgeInsets"
        }
      ],
      "identifier": "doc://com.apple.pdfkit/documentation/PDFKit/PDFEdgeInsets",
      "kind": "symbol",
      "role": "symbol",
      "title": "PDFEdgeInsets",
      "type": "topic",
      "url": "/documentation/pdfkit/pdfedgeinsets"
    },
    "doc://com.apple.pdfkit/documentation/PDFKit/PDFEdgeInsetsZero": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "PDFEdgeInsetsZero"
        }
      ],
      "identifier": "doc://com.apple.pdfkit/documentation/PDFKit/PDFEdgeInsetsZero",
      "kind": "symbol",
      "role": "symbol",
      "title": "PDFEdgeInsetsZero",
      "type": "topic",
      "url": "/documentation/pdfkit/pdfedgeinsetszero"
    },
    "doc://com.apple.pdfkit/documentation/PDFKit/PDFKIT_AVAILABLE": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "PDFKIT_AVAILABLE"
        }
      ],
      "identifier": "doc://com.apple.pdfkit/documentation/PDFKit/PDFKIT_AVAILABLE",
      "kind": "symbol",
      "role": "symbol",
      "title": "PDFKIT_AVAILABLE",
      "type": "topic",
      "url": "/documentation/pdfkit/pdfkit_available"
    },
    "doc://com.apple.pdfkit/documentation/PDFKit/PDFKIT_CLASS_AVAILABLE": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "PDFKIT_CLASS_AVAILABLE"
        }
      ],
      "identifier": "doc://com.apple.pdfkit/documentation/PDFKit/PDFKIT_CLASS_AVAILABLE",
      "kind": "symbol",
      "role": "symbol",
      "title": "PDFKIT_CLASS_AVAILABLE",
      "type": "topic",
      "url": "/documentation/pdfkit/pdfkit_class_available"
    },
    "doc://com.apple.pdfkit/documentation/PDFKit/PDFKIT_CLASS_DEPRECATED": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "PDFKIT_CLASS_DEPRECATED"
        }
      ],
      "identifier": "doc://com.apple.pdfkit/documentation/PDFKit/PDFKIT_CLASS_DEPRECATED",
      "kind": "symbol",
      "role": "symbol",
      "title": "PDFKIT_CLASS_DEPRECATED",
      "type": "topic",
      "url": "/documentation/pdfkit/pdfkit_class_deprecated"
    },
    "doc://com.apple.pdfkit/documentation/PDFKit/PDFKIT_DEPRECATED": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "PDFKIT_DEPRECATED"
        }
      ],
      "identifier": "doc://com.apple.pdfkit/documentation/PDFKit/PDFKIT_DEPRECATED",
      "kind": "symbol",
      "role": "symbol",
      "title": "PDFKIT_DEPRECATED",
      "type": "topic",
      "url": "/documentation/pdfkit/pdfkit_deprecated"
    },
    "doc://com.apple.pdfkit/documentation/PDFKit/PDFKIT_ENUM_AVAILABLE": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "PDFKIT_ENUM_AVAILABLE"
        }
      ],
      "identifier": "doc://com.apple.pdfkit/documentation/PDFKit/PDFKIT_ENUM_AVAILABLE",
      "kind": "symbol",
      "role": "symbol",
      "title": "PDFKIT_ENUM_AVAILABLE",
      "type": "topic",
      "url": "/documentation/pdfkit/pdfkit_enum_available"
    },
    "doc://com.apple.pdfkit/documentation/PDFKit/PDFKIT_ENUM_DEPRECATED": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "PDFKIT_ENUM_DEPRECATED"
        }
      ],
      "identifier": "doc://com.apple.pdfkit/documentation/PDFKit/PDFKIT_ENUM_DEPRECATED",
      "kind": "symbol",
      "role": "symbol",
      "title": "PDFKIT_ENUM_DEPRECATED",
      "type": "topic",
      "url": "/documentation/pdfkit/pdfkit_enum_deprecated"
    },
    "doc://com.apple.pdfkit/documentation/PDFKit/PDFKIT_EXTERN": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "PDFKIT_EXTERN"
        }
      ],
      "identifier": "doc://com.apple.pdfkit/documentation/PDFKit/PDFKIT_EXTERN",
      "kind": "symbol",
      "role": "symbol",
      "title": "PDFKIT_EXTERN",
      "type": "topic",
      "url": "/documentation/pdfkit/pdfkit_extern"
    },
    "doc://com.apple.pdfkit/documentation/PDFKit/PDFKIT_PLATFORM_IOS": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "PDFKIT_PLATFORM_IOS"
        }
      ],
      "identifier": "doc://com.apple.pdfkit/documentation/PDFKit/PDFKIT_PLATFORM_IOS",
      "kind": "symbol",
      "role": "symbol",
      "title": "PDFKIT_PLATFORM_IOS",
      "type": "topic",
      "url": "/documentation/pdfkit/pdfkit_platform_ios"
    },
    "doc://com.apple.pdfkit/documentation/PDFKit/PDFKIT_PLATFORM_MACCATALYST": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "PDFKIT_PLATFORM_MACCATALYST"
        }
      ],
      "identifier": "doc://com.apple.pdfkit/documentation/PDFKit/PDFKIT_PLATFORM_MACCATALYST",
      "kind": "symbol",
      "role": "symbol",
      "title": "PDFKIT_PLATFORM_MACCATALYST",
      "type": "topic",
      "url": "/documentation/pdfkit/pdfkit_platform_maccatalyst"
    },
    "doc://com.apple.pdfkit/documentation/PDFKit/PDFKIT_PLATFORM_OSX": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "PDFKIT_PLATFORM_OSX"
        }
      ],
      "identifier": "doc://com.apple.pdfkit/documentation/PDFKit/PDFKIT_PLATFORM_OSX",
      "kind": "symbol",
      "role": "symbol",
      "title": "PDFKIT_PLATFORM_OSX",
      "type": "topic",
      "url": "/documentation/pdfkit/pdfkit_platform_osx"
    },
    "doc://com.apple.pdfkit/documentation/PDFKit/PDFKitPlatformAccessibilityElement": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "PDFKitPlatformAccessibilityElement"
        }
      ],
      "identifier": "doc://com.apple.pdfkit/documentation/PDFKit/PDFKitPlatformAccessibilityElement",
      "kind": "symbol",
      "role": "symbol",
      "title": "PDFKitPlatformAccessibilityElement",
      "type": "topic",
      "url": "/documentation/pdfkit/pdfkitplatformaccessibilityelement"
    },
    "doc://com.apple.pdfkit/documentation/PDFKit/PDFKitPlatformBezierPath": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "PDFKitPlatformBezierPath"
        }
      ],
      "identifier": "doc://com.apple.pdfkit/documentation/PDFKit/PDFKitPlatformBezierPath",
      "kind": "symbol",
      "role": "symbol",
      "title": "PDFKitPlatformBezierPath",
      "type": "topic",
      "url": "/documentation/pdfkit/pdfkitplatformbezierpath"
    },
    "doc://com.apple.pdfkit/documentation/PDFKit/PDFKitPlatformBezierPathElement": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "PDFKitPlatformBezierPathElement"
        }
      ],
      "identifier": "doc://com.apple.pdfkit/documentation/PDFKit/PDFKitPlatformBezierPathElement",
      "kind": "symbol",
      "role": "symbol",
      "title": "PDFKitPlatformBezierPathElement",
      "type": "topic",
      "url": "/documentation/pdfkit/pdfkitplatformbezierpathelement"
    },
    "doc://com.apple.pdfkit/documentation/PDFKit/PDFKitPlatformButton": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "PDFKitPlatformButton"
        }
      ],
      "identifier": "doc://com.apple.pdfkit/documentation/PDFKit/PDFKitPlatformButton",
      "kind": "symbol",
      "role": "symbol",
      "title": "PDFKitPlatformButton",
      "type": "topic",
      "url": "/documentation/pdfkit/pdfkitplatformbutton"
    },
    "doc://com.apple.pdfkit/documentation/PDFKit/PDFKitPlatformButtonCell": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "PDFKitPlatformButtonCell"
        }
      ],
      "identifier": "doc://com.apple.pdfkit/documentation/PDFKit/PDFKitPlatformButtonCell",
      "kind": "symbol",
      "role": "symbol",
      "title": "PDFKitPlatformButtonCell",
      "type": "topic",
      "url": "/documentation/pdfkit/pdfkitplatformbuttoncell"
    },
    "doc://com.apple.pdfkit/documentation/PDFKit/PDFKitPlatformChoiceWidgetComboBoxView": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "PDFKitPlatformChoiceWidgetComboBoxView"
        }
      ],
      "identifier": "doc://com.apple.pdfkit/documentation/PDFKit/PDFKitPlatformChoiceWidgetComboBoxView",
      "kind": "symbol",
      "role": "symbol",
      "title": "PDFKitPlatformChoiceWidgetComboBoxView",
      "type": "topic",
      "url": "/documentation/pdfkit/pdfkitplatformchoicewidgetcomboboxview"
    },
    "doc://com.apple.pdfkit/documentation/PDFKit/PDFKitPlatformChoiceWidgetListView": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "PDFKitPlatformChoiceWidgetListView"
        }
      ],
      "identifier": "doc://com.apple.pdfkit/documentation/PDFKit/PDFKitPlatformChoiceWidgetListView",
      "kind": "symbol",
      "role": "symbol",
      "title": "PDFKitPlatformChoiceWidgetListView",
      "type": "topic",
      "url": "/documentation/pdfkit/pdfkitplatformchoicewidgetlistview"
    },
    "doc://com.apple.pdfkit/documentation/PDFKit/PDFKitPlatformColor": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "PDFKitPlatformColor"
        }
      ],
      "identifier": "doc://com.apple.pdfkit/documentation/PDFKit/PDFKitPlatformColor",
      "kind": "symbol",
      "role": "symbol",
      "title": "PDFKitPlatformColor",
      "type": "topic",
      "url": "/documentation/pdfkit/pdfkitplatformcolor"
    },
    "doc://com.apple.pdfkit/documentation/PDFKit/PDFKitPlatformControl": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "PDFKitPlatformControl"
        }
      ],
      "identifier": "doc://com.apple.pdfkit/documentation/PDFKit/PDFKitPlatformControl",
      "kind": "symbol",
      "role": "symbol",
      "title": "PDFKitPlatformControl",
      "type": "topic",
      "url": "/documentation/pdfkit/pdfkitplatformcontrol"
    },
    "doc://com.apple.pdfkit/documentation/PDFKit/PDFKitPlatformEvent": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "PDFKitPlatformEvent"
        }
      ],
      "identifier": "doc://com.apple.pdfkit/documentation/PDFKit/PDFKitPlatformEvent",
      "kind": "symbol",
      "role": "symbol",
      "title": "PDFKitPlatformEvent",
      "type": "topic",
      "url": "/documentation/pdfkit/pdfkitplatformevent"
    },
    "doc://com.apple.pdfkit/documentation/PDFKit/PDFKitPlatformFont": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "PDFKitPlatformFont"
        }
      ],
      "identifier": "doc://com.apple.pdfkit/documentation/PDFKit/PDFKitPlatformFont",
      "kind": "symbol",
      "role": "symbol",
      "title": "PDFKitPlatformFont",
      "type": "topic",
      "url": "/documentation/pdfkit/pdfkitplatformfont"
    },
    "doc://com.apple.pdfkit/documentation/PDFKit/PDFKitPlatformFontWeightRegular": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "PDFKitPlatformFontWeightRegular"
        }
      ],
      "identifier": "doc://com.apple.pdfkit/documentation/PDFKit/PDFKitPlatformFontWeightRegular",
      "kind": "symbol",
      "role": "symbol",
      "title": "PDFKitPlatformFontWeightRegular",
      "type": "topic",
      "url": "/documentation/pdfkit/pdfkitplatformfontweightregular"
    },
    "doc://com.apple.pdfkit/documentation/PDFKit/PDFKitPlatformImage": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "PDFKitPlatformImage"
        }
      ],
      "identifier": "doc://com.apple.pdfkit/documentation/PDFKit/PDFKitPlatformImage",
      "kind": "symbol",
      "role": "symbol",
      "title": "PDFKitPlatformImage",
      "type": "topic",
      "url": "/documentation/pdfkit/pdfkitplatformimage"
    },
    "doc://com.apple.pdfkit/documentation/PDFKit/PDFKitPlatformImageView": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "PDFKitPlatformImageView"
        }
      ],
      "identifier": "doc://com.apple.pdfkit/documentation/PDFKit/PDFKitPlatformImageView",
      "kind": "symbol",
      "role": "symbol",
      "title": "PDFKitPlatformImageView",
      "type": "topic",
      "url": "/documentation/pdfkit/pdfkitplatformimageview"
    },
    "doc://com.apple.pdfkit/documentation/PDFKit/PDFKitPlatformScrollView": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "PDFKitPlatformScrollView"
        }
      ],
      "identifier": "doc://com.apple.pdfkit/documentation/PDFKit/PDFKitPlatformScrollView",
      "kind": "symbol",
      "role": "symbol",
      "title": "PDFKitPlatformScrollView",
      "type": "topic",
      "url": "/documentation/pdfkit/pdfkitplatformscrollview"
    },
    "doc://com.apple.pdfkit/documentation/PDFKit/PDFKitPlatformTextContentType": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "PDFKitPlatformTextContentType"
        }
      ],
      "identifier": "doc://com.apple.pdfkit/documentation/PDFKit/PDFKitPlatformTextContentType",
      "kind": "symbol",
      "role": "symbol",
      "title": "PDFKitPlatformTextContentType",
      "type": "topic",
      "url": "/documentation/pdfkit/pdfkitplatformtextcontenttype"
    },
    "doc://com.apple.pdfkit/documentation/PDFKit/PDFKitPlatformTextField": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "PDFKitPlatformTextField"
        }
      ],
      "identifier": "doc://com.apple.pdfkit/documentation/PDFKit/PDFKitPlatformTextField",
      "kind": "symbol",
      "role": "symbol",
      "title": "PDFKitPlatformTextField",
      "type": "topic",
      "url": "/documentation/pdfkit/pdfkitplatformtextfield"
    },
    "doc://com.apple.pdfkit/documentation/PDFKit/PDFKitPlatformTextView": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "PDFKitPlatformTextView"
        }
      ],
      "identifier": "doc://com.apple.pdfkit/documentation/PDFKit/PDFKitPlatformTextView",
      "kind": "symbol",
      "role": "symbol",
      "title": "PDFKitPlatformTextView",
      "type": "topic",
      "url": "/documentation/pdfkit/pdfkitplatformtextview"
    },
    "doc://com.apple.pdfkit/documentation/PDFKit/PDFKitPlatformTextViewDelegate": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "PDFKitPlatformTextViewDelegate"
        }
      ],
      "identifier": "doc://com.apple.pdfkit/documentation/PDFKit/PDFKitPlatformTextViewDelegate",
      "kind": "symbol",
      "role": "symbol",
      "title": "PDFKitPlatformTextViewDelegate",
      "type": "topic",
      "url": "/documentation/pdfkit/pdfkitplatformtextviewdelegate"
    },
    "doc://com.apple.pdfkit/documentation/PDFKit/PDFKitPlatformView": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "PDFKitPlatformView"
        }
      ],
      "identifier": "doc://com.apple.pdfkit/documentation/PDFKit/PDFKitPlatformView",
      "kind": "symbol",
      "role": "symbol",
      "title": "PDFKitPlatformView",
      "type": "topic",
      "url": "/documentation/pdfkit/pdfkitplatformview"
    },
    "doc://com.apple.pdfkit/documentation/PDFKit/PDFKitPlatformViewController": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "PDFKitPlatformViewController"
        }
      ],
      "identifier": "doc://com.apple.pdfkit/documentation/PDFKit/PDFKitPlatformViewController",
      "kind": "symbol",
      "role": "symbol",
      "title": "PDFKitPlatformViewController",
      "type": "topic",
      "url": "/documentation/pdfkit/pdfkitplatformviewcontroller"
    },
    "doc://com.apple.pdfkit/documentation/PDFKit/PDFKitResponder": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "PDFKitResponder"
        }
      ],
      "identifier": "doc://com.apple.pdfkit/documentation/PDFKit/PDFKitResponder",
      "kind": "symbol",
      "role": "symbol",
      "title": "PDFKitResponder",
      "type": "topic",
      "url": "/documentation/pdfkit/pdfkitresponder"
    },
    "doc://com.apple.pdfkit/documentation/PDFKit/PDFPoint": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "PDFPoint"
        }
      ],
      "identifier": "doc://com.apple.pdfkit/documentation/PDFKit/PDFPoint",
      "kind": "symbol",
      "role": "symbol",
      "title": "PDFPoint",
      "type": "topic",
      "url": "/documentation/pdfkit/pdfpoint"
    },
    "doc://com.apple.pdfkit/documentation/PDFKit/PDFPointZero": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "PDFPointZero"
        }
      ],
      "identifier": "doc://com.apple.pdfkit/documentation/PDFKit/PDFPointZero",
      "kind": "symbol",
      "role": "symbol",
      "title": "PDFPointZero",
      "type": "topic",
      "url": "/documentation/pdfkit/pdfpointzero"
    },
    "doc://com.apple.pdfkit/documentation/PDFKit/PDFRect": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "PDFRect"
        }
      ],
      "identifier": "doc://com.apple.pdfkit/documentation/PDFKit/PDFRect",
      "kind": "symbol",
      "role": "symbol",
      "title": "PDFRect",
      "type": "topic",
      "url": "/documentation/pdfkit/pdfrect"
    },
    "doc://com.apple.pdfkit/documentation/PDFKit/PDFRectZero": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "PDFRectZero"
        }
      ],
      "identifier": "doc://com.apple.pdfkit/documentation/PDFKit/PDFRectZero",
      "kind": "symbol",
      "role": "symbol",
      "title": "PDFRectZero",
      "type": "topic",
      "url": "/documentation/pdfkit/pdfrectzero"
    },
    "doc://com.apple.pdfkit/documentation/PDFKit/PDFSize": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "PDFSize"
        }
      ],
      "identifier": "doc://com.apple.pdfkit/documentation/PDFKit/PDFSize",
      "kind": "symbol",
      "role": "symbol",
      "title": "PDFSize",
      "type": "topic",
      "url": "/documentation/pdfkit/pdfsize"
    },
    "doc://com.apple.pdfkit/documentation/PDFKit/PDFSizeZero": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "PDFSizeZero"
        }
      ],
      "identifier": "doc://com.apple.pdfkit/documentation/PDFKit/PDFSizeZero",
      "kind": "symbol",
      "role": "symbol",
      "title": "PDFSizeZero",
      "type": "topic",
      "url": "/documentation/pdfkit/pdfsizezero"
    },
    "doc://com.apple.pdfkit/documentation/PDFKit/PDFTrackingRunLoopMode": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "PDFTrackingRunLoopMode"
        }
      ],
      "identifier": "doc://com.apple.pdfkit/documentation/PDFKit/PDFTrackingRunLoopMode",
      "kind": "symbol",
      "role": "symbol",
      "title": "PDFTrackingRunLoopMode",
      "type": "topic",
      "url": "/documentation/pdfkit/pdftrackingrunloopmode"
    },
    "doc://com.apple.pdfkit/documentation/PDFKit/data-types": {
      "abstract": [],
      "identifier": "doc://com.apple.pdfkit/documentation/PDFKit/data-types",
      "kind": "article",
      "role": "collectionGroup",
      "title": "PDFKit Data Types",
      "type": "topic",
      "url": "/documentation/pdfkit/data-types"
    },
    "doc://com.apple.pdfkit/documentation/PDFKit/enumerations": {
      "abstract": [],
      "identifier": "doc://com.apple.pdfkit/documentation/PDFKit/enumerations",
      "kind": "article",
      "role": "collectionGroup",
      "title": "PDFKit Enumerations",
      "type": "topic",
      "url": "/documentation/pdfkit/enumerations"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Reference",
      "generated": true,
      "identifiers": [
        "doc://com.apple.pdfkit/documentation/PDFKit/enumerations",
        "doc://com.apple.pdfkit/documentation/PDFKit/data-types"
      ],
      "title": "Reference"
    }
  ],
  "topicSections": [
    {
      "anchor": "Constants",
      "identifiers": [
        "doc://com.apple.pdfkit/documentation/PDFKit/PDFDocumentFoundSelectionKey",
        "doc://com.apple.pdfkit/documentation/PDFKit/PDFDocumentPageIndexKey"
      ],
      "title": "Constants"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Constants",
              "identifiers": [
                "doc://com.apple.pdfkit/documentation/PDFKit/PDFDocumentFoundSelectionKey",
                "doc://com.apple.pdfkit/documentation/PDFKit/PDFDocumentPageIndexKey"
              ],
              "title": "Constants"
            },
            {
              "anchor": "Macros",
              "identifiers": [
                "doc://com.apple.pdfkit/documentation/PDFKit/PDFEdgeInsets",
                "doc://com.apple.pdfkit/documentation/PDFKit/PDFEdgeInsetsZero",
                "doc://com.apple.pdfkit/documentation/PDFKit/PDFKIT_AVAILABLE",
                "doc://com.apple.pdfkit/documentation/PDFKit/PDFKIT_CLASS_AVAILABLE",
                "doc://com.apple.pdfkit/documentation/PDFKit/PDFKIT_CLASS_DEPRECATED",
                "doc://com.apple.pdfkit/documentation/PDFKit/PDFKIT_DEPRECATED",
                "doc://com.apple.pdfkit/documentation/PDFKit/PDFKIT_ENUM_AVAILABLE",
                "doc://com.apple.pdfkit/documentation/PDFKit/PDFKIT_ENUM_DEPRECATED",
                "doc://com.apple.pdfkit/documentation/PDFKit/PDFKIT_EXTERN",
                "doc://com.apple.pdfkit/documentation/PDFKit/PDFKIT_PLATFORM_IOS",
                "doc://com.apple.pdfkit/documentation/PDFKit/PDFKIT_PLATFORM_MACCATALYST",
                "doc://com.apple.pdfkit/documentation/PDFKit/PDFKIT_PLATFORM_OSX",
                "doc://com.apple.pdfkit/documentation/PDFKit/PDFKitPlatformAccessibilityElement",
                "doc://com.apple.pdfkit/documentation/PDFKit/PDFKitPlatformBezierPath",
                "doc://com.apple.pdfkit/documentation/PDFKit/PDFKitPlatformBezierPathElement",
                "doc://com.apple.pdfkit/documentation/PDFKit/PDFKitPlatformButton",
                "doc://com.apple.pdfkit/documentation/PDFKit/PDFKitPlatformButtonCell",
                "doc://com.apple.pdfkit/documentation/PDFKit/PDFKitPlatformChoiceWidgetComboBoxView",
                "doc://com.apple.pdfkit/documentation/PDFKit/PDFKitPlatformChoiceWidgetListView",
                "doc://com.apple.pdfkit/documentation/PDFKit/PDFKitPlatformColor",
                "doc://com.apple.pdfkit/documentation/PDFKit/PDFKitPlatformControl",
                "doc://com.apple.pdfkit/documentation/PDFKit/PDFKitPlatformEvent",
                "doc://com.apple.pdfkit/documentation/PDFKit/PDFKitPlatformFont",
                "doc://com.apple.pdfkit/documentation/PDFKit/PDFKitPlatformFontWeightRegular",
                "doc://com.apple.pdfkit/documentation/PDFKit/PDFKitPlatformImage",
                "doc://com.apple.pdfkit/documentation/PDFKit/PDFKitPlatformImageView",
                "doc://com.apple.pdfkit/documentation/PDFKit/PDFKitPlatformScrollView",
                "doc://com.apple.pdfkit/documentation/PDFKit/PDFKitPlatformTextContentType",
                "doc://com.apple.pdfkit/documentation/PDFKit/PDFKitPlatformTextField",
                "doc://com.apple.pdfkit/documentation/PDFKit/PDFKitPlatformTextView",
                "doc://com.apple.pdfkit/documentation/PDFKit/PDFKitPlatformTextViewDelegate",
                "doc://com.apple.pdfkit/documentation/PDFKit/PDFKitPlatformView",
                "doc://com.apple.pdfkit/documentation/PDFKit/PDFKitPlatformViewController",
                "doc://com.apple.pdfkit/documentation/PDFKit/PDFKitResponder",
                "doc://com.apple.pdfkit/documentation/PDFKit/PDFPoint",
                "doc://com.apple.pdfkit/documentation/PDFKit/PDFPointZero",
                "doc://com.apple.pdfkit/documentation/PDFKit/PDFRect",
                "doc://com.apple.pdfkit/documentation/PDFKit/PDFRectZero",
                "doc://com.apple.pdfkit/documentation/PDFKit/PDFSize",
                "doc://com.apple.pdfkit/documentation/PDFKit/PDFSizeZero",
                "doc://com.apple.pdfkit/documentation/PDFKit/PDFTrackingRunLoopMode"
              ],
              "title": "Macros"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Reference",
              "generated": true,
              "identifiers": [
                "doc://com.apple.pdfkit/documentation/PDFKit/enumerations",
                "doc://com.apple.pdfkit/documentation/PDFKit/data-types"
              ],
              "title": "Reference"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFDocumentPageIndexKey/title",
          "value": "PDFDocumentPageIndexKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFDocumentPageIndexKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PDFDocumentPageIndexKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFDocumentFoundSelectionKey/title",
          "value": "PDFDocumentFoundSelectionKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFDocumentFoundSelectionKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PDFDocumentFoundSelectionKey"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/pdfkit/constants"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/pdfkit/constants"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
