{
  "abstract": [
    {
      "text": "Review unsupported symbols and their replacements.",
      "type": "text"
    }
  ],
  "diffAvailability": {
    "major": {
      "change": "modified",
      "platform": "Xcode",
      "versions": [
        "16.0",
        "16.3 beta 2"
      ]
    }
  },
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.pdfkit/documentation/PDFKit",
        "doc://com.apple.pdfkit/documentation/PDFKit/PDFAnnotation"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.pdfkit/documentation/PDFKit/deprecated-symbols"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "PDFKit"
      }
    ],
    "role": "collectionGroup",
    "roleHeading": "API Collection",
    "title": "Deprecated Symbols"
  },
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.pdfkit/documentation/PDFKit": {
      "abstract": [
        {
          "text": "Display and manipulate PDF documents in your apps.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.pdfkit/documentation/PDFKit",
      "kind": "symbol",
      "role": "collection",
      "title": "PDFKit",
      "type": "topic",
      "url": "/documentation/pdfkit"
    },
    "doc://com.apple.pdfkit/documentation/PDFKit/PDFAnnotation": {
      "abstract": [
        {
          "text": "An annotation in a PDF document.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "PDFAnnotation"
        }
      ],
      "identifier": "doc://com.apple.pdfkit/documentation/PDFKit/PDFAnnotation",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PDFAnnotation"
        }
      ],
      "role": "symbol",
      "title": "PDFAnnotation",
      "type": "topic",
      "url": "/documentation/pdfkit/pdfannotation"
    },
    "doc://com.apple.pdfkit/documentation/PDFKit/PDFAnnotation/draw(with:)": {
      "abstract": [
        {
          "text": "Draws the annotation on its associated page.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "draw"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "with"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@PDFDisplayBox",
          "text": "PDFDisplayBox"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.pdfkit/documentation/PDFKit/PDFAnnotation/draw(with:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "drawWithBox:"
        }
      ],
      "role": "symbol",
      "title": "draw(with:)",
      "type": "topic",
      "url": "/documentation/pdfkit/pdfannotation/draw(with:)"
    },
    "doc://com.apple.pdfkit/documentation/PDFKit/PDFAnnotation/init(bounds:)": {
      "abstract": [
        {
          "text": "Creates a PDF annotation object.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "convenience"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "bounds"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSRect",
          "text": "NSRect"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.pdfkit/documentation/PDFKit/PDFAnnotation/init(bounds:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "initWithBounds:"
        }
      ],
      "role": "symbol",
      "title": "init(bounds:)",
      "type": "topic",
      "url": "/documentation/pdfkit/pdfannotation/init(bounds:)"
    },
    "doc://com.apple.pdfkit/documentation/PDFKit/PDFAnnotation/init(dictionary:forPage:)": {
      "abstract": [],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "convenience"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "dictionary"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s11AnyHashableV",
          "text": "AnyHashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "keyword",
          "text": "Any"
        },
        {
          "kind": "text",
          "text": "], "
        },
        {
          "kind": "externalParam",
          "text": "forPage"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)PDFPage",
          "text": "PDFPage"
        },
        {
          "kind": "text",
          "text": "?)"
        }
      ],
      "identifier": "doc://com.apple.pdfkit/documentation/PDFKit/PDFAnnotation/init(dictionary:forPage:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "initWithDictionary:forPage:"
        }
      ],
      "role": "symbol",
      "title": "init(dictionary:forPage:)",
      "type": "topic",
      "url": "/documentation/pdfkit/pdfannotation/init(dictionary:forpage:)"
    },
    "doc://com.apple.pdfkit/documentation/PDFKit/PDFAnnotation/mouseUpAction": {
      "abstract": [
        {
          "text": "The action to perform when a user releases the mouse button within an annotation.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "mouseUpAction"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)PDFAction",
          "text": "PDFAction"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.pdfkit/documentation/PDFKit/PDFAnnotation/mouseUpAction",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "mouseUpAction"
        }
      ],
      "role": "symbol",
      "title": "mouseUpAction",
      "type": "topic",
      "url": "/documentation/pdfkit/pdfannotation/mouseupaction"
    },
    "doc://com.apple.pdfkit/documentation/PDFKit/PDFAnnotation/removeAllAppearanceStreams()": {
      "abstract": [],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "removeAllAppearanceStreams"
        },
        {
          "kind": "text",
          "text": "()"
        }
      ],
      "identifier": "doc://com.apple.pdfkit/documentation/PDFKit/PDFAnnotation/removeAllAppearanceStreams()",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "removeAllAppearanceStreams"
        }
      ],
      "role": "symbol",
      "title": "removeAllAppearanceStreams()",
      "type": "topic",
      "url": "/documentation/pdfkit/pdfannotation/removeallappearancestreams()"
    },
    "doc://com.apple.pdfkit/documentation/PDFKit/PDFAnnotation/toolTip": {
      "abstract": [
        {
          "text": "Returns text for display as a help tag.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "toolTip"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.pdfkit/documentation/PDFKit/PDFAnnotation/toolTip",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "toolTip"
        }
      ],
      "role": "symbol",
      "title": "toolTip",
      "type": "topic",
      "url": "/documentation/pdfkit/pdfannotation/tooltip"
    },
    "doc://com.apple.pdfkit/documentation/PDFKit/PDFAnnotationButtonWidget": {
      "abstract": [
        {
          "text": "A ",
          "type": "text"
        },
        {
          "code": "PDFAnnotationButtonWidget",
          "type": "codeVoice"
        },
        {
          "text": " object provides user interactivity on a page of a PDF document. There are three types of buttons available: push button, radio button, and checkbox.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "PDFAnnotationButtonWidget"
        }
      ],
      "identifier": "doc://com.apple.pdfkit/documentation/PDFKit/PDFAnnotationButtonWidget",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PDFAnnotationButtonWidget"
        }
      ],
      "role": "symbol",
      "title": "PDFAnnotationButtonWidget",
      "type": "topic",
      "url": "/documentation/pdfkit/pdfannotationbuttonwidget"
    },
    "doc://com.apple.pdfkit/documentation/PDFKit/PDFAnnotationChoiceWidget": {
      "abstract": [
        {
          "text": "A ",
          "type": "text"
        },
        {
          "code": "PDFAnnotationChoiceWidget",
          "type": "codeVoice"
        },
        {
          "text": " object provides user interactivity on a page of a PDF document, in the form of pop-up menus and lists.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "PDFAnnotationChoiceWidget"
        }
      ],
      "identifier": "doc://com.apple.pdfkit/documentation/PDFKit/PDFAnnotationChoiceWidget",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PDFAnnotationChoiceWidget"
        }
      ],
      "role": "symbol",
      "title": "PDFAnnotationChoiceWidget",
      "type": "topic",
      "url": "/documentation/pdfkit/pdfannotationchoicewidget"
    },
    "doc://com.apple.pdfkit/documentation/PDFKit/PDFAnnotationCircle": {
      "abstract": [],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "PDFAnnotationCircle"
        }
      ],
      "identifier": "doc://com.apple.pdfkit/documentation/PDFKit/PDFAnnotationCircle",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PDFAnnotationCircle"
        }
      ],
      "role": "symbol",
      "title": "PDFAnnotationCircle",
      "type": "topic",
      "url": "/documentation/pdfkit/pdfannotationcircle"
    },
    "doc://com.apple.pdfkit/documentation/PDFKit/PDFAnnotationFreeText": {
      "abstract": [
        {
          "text": "A ",
          "type": "text"
        },
        {
          "code": "PDFAnnotationFreeText",
          "type": "codeVoice"
        },
        {
          "text": " object displays text on a page.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "PDFAnnotationFreeText"
        }
      ],
      "identifier": "doc://com.apple.pdfkit/documentation/PDFKit/PDFAnnotationFreeText",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PDFAnnotationFreeText"
        }
      ],
      "role": "symbol",
      "title": "PDFAnnotationFreeText",
      "type": "topic",
      "url": "/documentation/pdfkit/pdfannotationfreetext"
    },
    "doc://com.apple.pdfkit/documentation/PDFKit/PDFAnnotationInk": {
      "abstract": [],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "PDFAnnotationInk"
        }
      ],
      "identifier": "doc://com.apple.pdfkit/documentation/PDFKit/PDFAnnotationInk",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PDFAnnotationInk"
        }
      ],
      "role": "symbol",
      "title": "PDFAnnotationInk",
      "type": "topic",
      "url": "/documentation/pdfkit/pdfannotationink"
    },
    "doc://com.apple.pdfkit/documentation/PDFKit/PDFAnnotationLine": {
      "abstract": [
        {
          "text": "A ",
          "type": "text"
        },
        {
          "code": "PDFAnnotationLine",
          "type": "codeVoice"
        },
        {
          "text": " object displays a single line on a page.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "PDFAnnotationLine"
        }
      ],
      "identifier": "doc://com.apple.pdfkit/documentation/PDFKit/PDFAnnotationLine",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PDFAnnotationLine"
        }
      ],
      "role": "symbol",
      "title": "PDFAnnotationLine",
      "type": "topic",
      "url": "/documentation/pdfkit/pdfannotationline"
    },
    "doc://com.apple.pdfkit/documentation/PDFKit/PDFAnnotationLink": {
      "abstract": [],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "PDFAnnotationLink"
        }
      ],
      "identifier": "doc://com.apple.pdfkit/documentation/PDFKit/PDFAnnotationLink",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PDFAnnotationLink"
        }
      ],
      "role": "symbol",
      "title": "PDFAnnotationLink",
      "type": "topic",
      "url": "/documentation/pdfkit/pdfannotationlink"
    },
    "doc://com.apple.pdfkit/documentation/PDFKit/PDFAnnotationMarkup": {
      "abstract": [
        {
          "text": "A ",
          "type": "text"
        },
        {
          "code": "PDFAnnotationMarkup",
          "type": "codeVoice"
        },
        {
          "text": " object appears as highlighting, underlining, or a strikethrough style applied to the text of a document.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "PDFAnnotationMarkup"
        }
      ],
      "identifier": "doc://com.apple.pdfkit/documentation/PDFKit/PDFAnnotationMarkup",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PDFAnnotationMarkup"
        }
      ],
      "role": "symbol",
      "title": "PDFAnnotationMarkup",
      "type": "topic",
      "url": "/documentation/pdfkit/pdfannotationmarkup"
    },
    "doc://com.apple.pdfkit/documentation/PDFKit/PDFAnnotationPopup": {
      "abstract": [
        {
          "text": "A ",
          "type": "text"
        },
        {
          "code": "PDFAnnotationPopup",
          "type": "codeVoice"
        },
        {
          "text": " object provides user interactivity on a PDF page in the form of a pop-up menu.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "PDFAnnotationPopup"
        }
      ],
      "identifier": "doc://com.apple.pdfkit/documentation/PDFKit/PDFAnnotationPopup",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PDFAnnotationPopup"
        }
      ],
      "role": "symbol",
      "title": "PDFAnnotationPopup",
      "type": "topic",
      "url": "/documentation/pdfkit/pdfannotationpopup"
    },
    "doc://com.apple.pdfkit/documentation/PDFKit/PDFAnnotationSquare": {
      "abstract": [
        {
          "text": "A rectangle annotation on a page.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "PDFAnnotationSquare"
        }
      ],
      "identifier": "doc://com.apple.pdfkit/documentation/PDFKit/PDFAnnotationSquare",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PDFAnnotationSquare"
        }
      ],
      "role": "symbol",
      "title": "PDFAnnotationSquare",
      "type": "topic",
      "url": "/documentation/pdfkit/pdfannotationsquare"
    },
    "doc://com.apple.pdfkit/documentation/PDFKit/PDFAnnotationStamp": {
      "abstract": [
        {
          "text": "A ",
          "type": "text"
        },
        {
          "code": "PDFAnnotationStamp",
          "type": "codeVoice"
        },
        {
          "text": " object allows you to display a word or phrase, such as “Confidential,” in a PDF page.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "PDFAnnotationStamp"
        }
      ],
      "identifier": "doc://com.apple.pdfkit/documentation/PDFKit/PDFAnnotationStamp",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PDFAnnotationStamp"
        }
      ],
      "role": "symbol",
      "title": "PDFAnnotationStamp",
      "type": "topic",
      "url": "/documentation/pdfkit/pdfannotationstamp"
    },
    "doc://com.apple.pdfkit/documentation/PDFKit/PDFAnnotationText": {
      "abstract": [
        {
          "text": "A ",
          "type": "text"
        },
        {
          "code": "PDFAnnotationText",
          "type": "codeVoice"
        },
        {
          "text": " object displays as an icon (such as a “sticky note”) attached to a specified point in the PDF document.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "PDFAnnotationText"
        }
      ],
      "identifier": "doc://com.apple.pdfkit/documentation/PDFKit/PDFAnnotationText",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PDFAnnotationText"
        }
      ],
      "role": "symbol",
      "title": "PDFAnnotationText",
      "type": "topic",
      "url": "/documentation/pdfkit/pdfannotationtext"
    },
    "doc://com.apple.pdfkit/documentation/PDFKit/PDFAnnotationTextWidget": {
      "abstract": [
        {
          "text": "A ",
          "type": "text"
        },
        {
          "code": "PDFAnnotationTextWidget",
          "type": "codeVoice"
        },
        {
          "text": " object allows you to manage the appearance and content of text fields.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "PDFAnnotationTextWidget"
        }
      ],
      "identifier": "doc://com.apple.pdfkit/documentation/PDFKit/PDFAnnotationTextWidget",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PDFAnnotationTextWidget"
        }
      ],
      "role": "symbol",
      "title": "PDFAnnotationTextWidget",
      "type": "topic",
      "url": "/documentation/pdfkit/pdfannotationtextwidget"
    },
    "doc://com.apple.pdfkit/documentation/PDFKit/kPDFAnnotationKey_Action": {
      "abstract": [],
      "deprecated": true,
      "fragments": [
        {
          "kind": "identifier",
          "text": "kPDFAnnotationKey_Action"
        }
      ],
      "identifier": "doc://com.apple.pdfkit/documentation/PDFKit/kPDFAnnotationKey_Action",
      "kind": "symbol",
      "role": "symbol",
      "title": "kPDFAnnotationKey_Action",
      "type": "topic",
      "url": "/documentation/pdfkit/kpdfannotationkey_action"
    },
    "doc://com.apple.pdfkit/documentation/PDFKit/kPDFAnnotationKey_AdditionalActions": {
      "abstract": [],
      "deprecated": true,
      "fragments": [
        {
          "kind": "identifier",
          "text": "kPDFAnnotationKey_AdditionalActions"
        }
      ],
      "identifier": "doc://com.apple.pdfkit/documentation/PDFKit/kPDFAnnotationKey_AdditionalActions",
      "kind": "symbol",
      "role": "symbol",
      "title": "kPDFAnnotationKey_AdditionalActions",
      "type": "topic",
      "url": "/documentation/pdfkit/kpdfannotationkey_additionalactions"
    },
    "doc://com.apple.pdfkit/documentation/PDFKit/kPDFAnnotationKey_AppearanceDictionary": {
      "abstract": [],
      "deprecated": true,
      "fragments": [
        {
          "kind": "identifier",
          "text": "kPDFAnnotationKey_AppearanceDictionary"
        }
      ],
      "identifier": "doc://com.apple.pdfkit/documentation/PDFKit/kPDFAnnotationKey_AppearanceDictionary",
      "kind": "symbol",
      "role": "symbol",
      "title": "kPDFAnnotationKey_AppearanceDictionary",
      "type": "topic",
      "url": "/documentation/pdfkit/kpdfannotationkey_appearancedictionary"
    },
    "doc://com.apple.pdfkit/documentation/PDFKit/kPDFAnnotationKey_AppearanceState": {
      "abstract": [],
      "deprecated": true,
      "fragments": [
        {
          "kind": "identifier",
          "text": "kPDFAnnotationKey_AppearanceState"
        }
      ],
      "identifier": "doc://com.apple.pdfkit/documentation/PDFKit/kPDFAnnotationKey_AppearanceState",
      "kind": "symbol",
      "role": "symbol",
      "title": "kPDFAnnotationKey_AppearanceState",
      "type": "topic",
      "url": "/documentation/pdfkit/kpdfannotationkey_appearancestate"
    },
    "doc://com.apple.pdfkit/documentation/PDFKit/kPDFAnnotationKey_Border": {
      "abstract": [],
      "deprecated": true,
      "fragments": [
        {
          "kind": "identifier",
          "text": "kPDFAnnotationKey_Border"
        }
      ],
      "identifier": "doc://com.apple.pdfkit/documentation/PDFKit/kPDFAnnotationKey_Border",
      "kind": "symbol",
      "role": "symbol",
      "title": "kPDFAnnotationKey_Border",
      "type": "topic",
      "url": "/documentation/pdfkit/kpdfannotationkey_border"
    },
    "doc://com.apple.pdfkit/documentation/PDFKit/kPDFAnnotationKey_BorderStyle": {
      "abstract": [],
      "deprecated": true,
      "fragments": [
        {
          "kind": "identifier",
          "text": "kPDFAnnotationKey_BorderStyle"
        }
      ],
      "identifier": "doc://com.apple.pdfkit/documentation/PDFKit/kPDFAnnotationKey_BorderStyle",
      "kind": "symbol",
      "role": "symbol",
      "title": "kPDFAnnotationKey_BorderStyle",
      "type": "topic",
      "url": "/documentation/pdfkit/kpdfannotationkey_borderstyle"
    },
    "doc://com.apple.pdfkit/documentation/PDFKit/kPDFAnnotationKey_Color": {
      "abstract": [],
      "deprecated": true,
      "fragments": [
        {
          "kind": "identifier",
          "text": "kPDFAnnotationKey_Color"
        }
      ],
      "identifier": "doc://com.apple.pdfkit/documentation/PDFKit/kPDFAnnotationKey_Color",
      "kind": "symbol",
      "role": "symbol",
      "title": "kPDFAnnotationKey_Color",
      "type": "topic",
      "url": "/documentation/pdfkit/kpdfannotationkey_color"
    },
    "doc://com.apple.pdfkit/documentation/PDFKit/kPDFAnnotationKey_Contents": {
      "abstract": [],
      "deprecated": true,
      "fragments": [
        {
          "kind": "identifier",
          "text": "kPDFAnnotationKey_Contents"
        }
      ],
      "identifier": "doc://com.apple.pdfkit/documentation/PDFKit/kPDFAnnotationKey_Contents",
      "kind": "symbol",
      "role": "symbol",
      "title": "kPDFAnnotationKey_Contents",
      "type": "topic",
      "url": "/documentation/pdfkit/kpdfannotationkey_contents"
    },
    "doc://com.apple.pdfkit/documentation/PDFKit/kPDFAnnotationKey_Date": {
      "abstract": [],
      "deprecated": true,
      "fragments": [
        {
          "kind": "identifier",
          "text": "kPDFAnnotationKey_Date"
        }
      ],
      "identifier": "doc://com.apple.pdfkit/documentation/PDFKit/kPDFAnnotationKey_Date",
      "kind": "symbol",
      "role": "symbol",
      "title": "kPDFAnnotationKey_Date",
      "type": "topic",
      "url": "/documentation/pdfkit/kpdfannotationkey_date"
    },
    "doc://com.apple.pdfkit/documentation/PDFKit/kPDFAnnotationKey_DefaultAppearance": {
      "abstract": [],
      "deprecated": true,
      "fragments": [
        {
          "kind": "identifier",
          "text": "kPDFAnnotationKey_DefaultAppearance"
        }
      ],
      "identifier": "doc://com.apple.pdfkit/documentation/PDFKit/kPDFAnnotationKey_DefaultAppearance",
      "kind": "symbol",
      "role": "symbol",
      "title": "kPDFAnnotationKey_DefaultAppearance",
      "type": "topic",
      "url": "/documentation/pdfkit/kpdfannotationkey_defaultappearance"
    },
    "doc://com.apple.pdfkit/documentation/PDFKit/kPDFAnnotationKey_Destination": {
      "abstract": [],
      "deprecated": true,
      "fragments": [
        {
          "kind": "identifier",
          "text": "kPDFAnnotationKey_Destination"
        }
      ],
      "identifier": "doc://com.apple.pdfkit/documentation/PDFKit/kPDFAnnotationKey_Destination",
      "kind": "symbol",
      "role": "symbol",
      "title": "kPDFAnnotationKey_Destination",
      "type": "topic",
      "url": "/documentation/pdfkit/kpdfannotationkey_destination"
    },
    "doc://com.apple.pdfkit/documentation/PDFKit/kPDFAnnotationKey_Flags": {
      "abstract": [],
      "deprecated": true,
      "fragments": [
        {
          "kind": "identifier",
          "text": "kPDFAnnotationKey_Flags"
        }
      ],
      "identifier": "doc://com.apple.pdfkit/documentation/PDFKit/kPDFAnnotationKey_Flags",
      "kind": "symbol",
      "role": "symbol",
      "title": "kPDFAnnotationKey_Flags",
      "type": "topic",
      "url": "/documentation/pdfkit/kpdfannotationkey_flags"
    },
    "doc://com.apple.pdfkit/documentation/PDFKit/kPDFAnnotationKey_HighlightingMode": {
      "abstract": [],
      "deprecated": true,
      "fragments": [
        {
          "kind": "identifier",
          "text": "kPDFAnnotationKey_HighlightingMode"
        }
      ],
      "identifier": "doc://com.apple.pdfkit/documentation/PDFKit/kPDFAnnotationKey_HighlightingMode",
      "kind": "symbol",
      "role": "symbol",
      "title": "kPDFAnnotationKey_HighlightingMode",
      "type": "topic",
      "url": "/documentation/pdfkit/kpdfannotationkey_highlightingmode"
    },
    "doc://com.apple.pdfkit/documentation/PDFKit/kPDFAnnotationKey_IconName": {
      "abstract": [],
      "deprecated": true,
      "fragments": [
        {
          "kind": "identifier",
          "text": "kPDFAnnotationKey_IconName"
        }
      ],
      "identifier": "doc://com.apple.pdfkit/documentation/PDFKit/kPDFAnnotationKey_IconName",
      "kind": "symbol",
      "role": "symbol",
      "title": "kPDFAnnotationKey_IconName",
      "type": "topic",
      "url": "/documentation/pdfkit/kpdfannotationkey_iconname"
    },
    "doc://com.apple.pdfkit/documentation/PDFKit/kPDFAnnotationKey_Inklist": {
      "abstract": [],
      "deprecated": true,
      "fragments": [
        {
          "kind": "identifier",
          "text": "kPDFAnnotationKey_Inklist"
        }
      ],
      "identifier": "doc://com.apple.pdfkit/documentation/PDFKit/kPDFAnnotationKey_Inklist",
      "kind": "symbol",
      "role": "symbol",
      "title": "kPDFAnnotationKey_Inklist",
      "type": "topic",
      "url": "/documentation/pdfkit/kpdfannotationkey_inklist"
    },
    "doc://com.apple.pdfkit/documentation/PDFKit/kPDFAnnotationKey_InteriorColor": {
      "abstract": [],
      "deprecated": true,
      "fragments": [
        {
          "kind": "identifier",
          "text": "kPDFAnnotationKey_InteriorColor"
        }
      ],
      "identifier": "doc://com.apple.pdfkit/documentation/PDFKit/kPDFAnnotationKey_InteriorColor",
      "kind": "symbol",
      "role": "symbol",
      "title": "kPDFAnnotationKey_InteriorColor",
      "type": "topic",
      "url": "/documentation/pdfkit/kpdfannotationkey_interiorcolor"
    },
    "doc://com.apple.pdfkit/documentation/PDFKit/kPDFAnnotationKey_LineEndingStyles": {
      "abstract": [],
      "deprecated": true,
      "fragments": [
        {
          "kind": "identifier",
          "text": "kPDFAnnotationKey_LineEndingStyles"
        }
      ],
      "identifier": "doc://com.apple.pdfkit/documentation/PDFKit/kPDFAnnotationKey_LineEndingStyles",
      "kind": "symbol",
      "role": "symbol",
      "title": "kPDFAnnotationKey_LineEndingStyles",
      "type": "topic",
      "url": "/documentation/pdfkit/kpdfannotationkey_lineendingstyles"
    },
    "doc://com.apple.pdfkit/documentation/PDFKit/kPDFAnnotationKey_LinePoints": {
      "abstract": [],
      "deprecated": true,
      "fragments": [
        {
          "kind": "identifier",
          "text": "kPDFAnnotationKey_LinePoints"
        }
      ],
      "identifier": "doc://com.apple.pdfkit/documentation/PDFKit/kPDFAnnotationKey_LinePoints",
      "kind": "symbol",
      "role": "symbol",
      "title": "kPDFAnnotationKey_LinePoints",
      "type": "topic",
      "url": "/documentation/pdfkit/kpdfannotationkey_linepoints"
    },
    "doc://com.apple.pdfkit/documentation/PDFKit/kPDFAnnotationKey_Name": {
      "abstract": [],
      "deprecated": true,
      "fragments": [
        {
          "kind": "identifier",
          "text": "kPDFAnnotationKey_Name"
        }
      ],
      "identifier": "doc://com.apple.pdfkit/documentation/PDFKit/kPDFAnnotationKey_Name",
      "kind": "symbol",
      "role": "symbol",
      "title": "kPDFAnnotationKey_Name",
      "type": "topic",
      "url": "/documentation/pdfkit/kpdfannotationkey_name"
    },
    "doc://com.apple.pdfkit/documentation/PDFKit/kPDFAnnotationKey_Open": {
      "abstract": [],
      "deprecated": true,
      "fragments": [
        {
          "kind": "identifier",
          "text": "kPDFAnnotationKey_Open"
        }
      ],
      "identifier": "doc://com.apple.pdfkit/documentation/PDFKit/kPDFAnnotationKey_Open",
      "kind": "symbol",
      "role": "symbol",
      "title": "kPDFAnnotationKey_Open",
      "type": "topic",
      "url": "/documentation/pdfkit/kpdfannotationkey_open"
    },
    "doc://com.apple.pdfkit/documentation/PDFKit/kPDFAnnotationKey_Page": {
      "abstract": [],
      "deprecated": true,
      "fragments": [
        {
          "kind": "identifier",
          "text": "kPDFAnnotationKey_Page"
        }
      ],
      "identifier": "doc://com.apple.pdfkit/documentation/PDFKit/kPDFAnnotationKey_Page",
      "kind": "symbol",
      "role": "symbol",
      "title": "kPDFAnnotationKey_Page",
      "type": "topic",
      "url": "/documentation/pdfkit/kpdfannotationkey_page"
    },
    "doc://com.apple.pdfkit/documentation/PDFKit/kPDFAnnotationKey_Parent": {
      "abstract": [],
      "deprecated": true,
      "fragments": [
        {
          "kind": "identifier",
          "text": "kPDFAnnotationKey_Parent"
        }
      ],
      "identifier": "doc://com.apple.pdfkit/documentation/PDFKit/kPDFAnnotationKey_Parent",
      "kind": "symbol",
      "role": "symbol",
      "title": "kPDFAnnotationKey_Parent",
      "type": "topic",
      "url": "/documentation/pdfkit/kpdfannotationkey_parent"
    },
    "doc://com.apple.pdfkit/documentation/PDFKit/kPDFAnnotationKey_Popup": {
      "abstract": [],
      "deprecated": true,
      "fragments": [
        {
          "kind": "identifier",
          "text": "kPDFAnnotationKey_Popup"
        }
      ],
      "identifier": "doc://com.apple.pdfkit/documentation/PDFKit/kPDFAnnotationKey_Popup",
      "kind": "symbol",
      "role": "symbol",
      "title": "kPDFAnnotationKey_Popup",
      "type": "topic",
      "url": "/documentation/pdfkit/kpdfannotationkey_popup"
    },
    "doc://com.apple.pdfkit/documentation/PDFKit/kPDFAnnotationKey_QuadPoints": {
      "abstract": [],
      "deprecated": true,
      "fragments": [
        {
          "kind": "identifier",
          "text": "kPDFAnnotationKey_QuadPoints"
        }
      ],
      "identifier": "doc://com.apple.pdfkit/documentation/PDFKit/kPDFAnnotationKey_QuadPoints",
      "kind": "symbol",
      "role": "symbol",
      "title": "kPDFAnnotationKey_QuadPoints",
      "type": "topic",
      "url": "/documentation/pdfkit/kpdfannotationkey_quadpoints"
    },
    "doc://com.apple.pdfkit/documentation/PDFKit/kPDFAnnotationKey_Quadding": {
      "abstract": [],
      "deprecated": true,
      "fragments": [
        {
          "kind": "identifier",
          "text": "kPDFAnnotationKey_Quadding"
        }
      ],
      "identifier": "doc://com.apple.pdfkit/documentation/PDFKit/kPDFAnnotationKey_Quadding",
      "kind": "symbol",
      "role": "symbol",
      "title": "kPDFAnnotationKey_Quadding",
      "type": "topic",
      "url": "/documentation/pdfkit/kpdfannotationkey_quadding"
    },
    "doc://com.apple.pdfkit/documentation/PDFKit/kPDFAnnotationKey_Rect": {
      "abstract": [],
      "deprecated": true,
      "fragments": [
        {
          "kind": "identifier",
          "text": "kPDFAnnotationKey_Rect"
        }
      ],
      "identifier": "doc://com.apple.pdfkit/documentation/PDFKit/kPDFAnnotationKey_Rect",
      "kind": "symbol",
      "role": "symbol",
      "title": "kPDFAnnotationKey_Rect",
      "type": "topic",
      "url": "/documentation/pdfkit/kpdfannotationkey_rect"
    },
    "doc://com.apple.pdfkit/documentation/PDFKit/kPDFAnnotationKey_Subtype": {
      "abstract": [],
      "deprecated": true,
      "fragments": [
        {
          "kind": "identifier",
          "text": "kPDFAnnotationKey_Subtype"
        }
      ],
      "identifier": "doc://com.apple.pdfkit/documentation/PDFKit/kPDFAnnotationKey_Subtype",
      "kind": "symbol",
      "role": "symbol",
      "title": "kPDFAnnotationKey_Subtype",
      "type": "topic",
      "url": "/documentation/pdfkit/kpdfannotationkey_subtype"
    },
    "doc://com.apple.pdfkit/documentation/PDFKit/kPDFAnnotationKey_TextLabel": {
      "abstract": [],
      "deprecated": true,
      "fragments": [
        {
          "kind": "identifier",
          "text": "kPDFAnnotationKey_TextLabel"
        }
      ],
      "identifier": "doc://com.apple.pdfkit/documentation/PDFKit/kPDFAnnotationKey_TextLabel",
      "kind": "symbol",
      "role": "symbol",
      "title": "kPDFAnnotationKey_TextLabel",
      "type": "topic",
      "url": "/documentation/pdfkit/kpdfannotationkey_textlabel"
    },
    "doc://com.apple.pdfkit/documentation/PDFKit/kPDFAnnotationKey_WidgetAppearanceDictionary": {
      "abstract": [],
      "deprecated": true,
      "fragments": [
        {
          "kind": "identifier",
          "text": "kPDFAnnotationKey_WidgetAppearanceDictionary"
        }
      ],
      "identifier": "doc://com.apple.pdfkit/documentation/PDFKit/kPDFAnnotationKey_WidgetAppearanceDictionary",
      "kind": "symbol",
      "role": "symbol",
      "title": "kPDFAnnotationKey_WidgetAppearanceDictionary",
      "type": "topic",
      "url": "/documentation/pdfkit/kpdfannotationkey_widgetappearancedictionary"
    },
    "doc://com.apple.pdfkit/documentation/PDFKit/kPDFAnnotationKey_WidgetDefaultValue": {
      "abstract": [],
      "deprecated": true,
      "fragments": [
        {
          "kind": "identifier",
          "text": "kPDFAnnotationKey_WidgetDefaultValue"
        }
      ],
      "identifier": "doc://com.apple.pdfkit/documentation/PDFKit/kPDFAnnotationKey_WidgetDefaultValue",
      "kind": "symbol",
      "role": "symbol",
      "title": "kPDFAnnotationKey_WidgetDefaultValue",
      "type": "topic",
      "url": "/documentation/pdfkit/kpdfannotationkey_widgetdefaultvalue"
    },
    "doc://com.apple.pdfkit/documentation/PDFKit/kPDFAnnotationKey_WidgetFieldFlags": {
      "abstract": [],
      "deprecated": true,
      "fragments": [
        {
          "kind": "identifier",
          "text": "kPDFAnnotationKey_WidgetFieldFlags"
        }
      ],
      "identifier": "doc://com.apple.pdfkit/documentation/PDFKit/kPDFAnnotationKey_WidgetFieldFlags",
      "kind": "symbol",
      "role": "symbol",
      "title": "kPDFAnnotationKey_WidgetFieldFlags",
      "type": "topic",
      "url": "/documentation/pdfkit/kpdfannotationkey_widgetfieldflags"
    },
    "doc://com.apple.pdfkit/documentation/PDFKit/kPDFAnnotationKey_WidgetFieldType": {
      "abstract": [],
      "deprecated": true,
      "fragments": [
        {
          "kind": "identifier",
          "text": "kPDFAnnotationKey_WidgetFieldType"
        }
      ],
      "identifier": "doc://com.apple.pdfkit/documentation/PDFKit/kPDFAnnotationKey_WidgetFieldType",
      "kind": "symbol",
      "role": "symbol",
      "title": "kPDFAnnotationKey_WidgetFieldType",
      "type": "topic",
      "url": "/documentation/pdfkit/kpdfannotationkey_widgetfieldtype"
    },
    "doc://com.apple.pdfkit/documentation/PDFKit/kPDFAnnotationKey_WidgetMaxLen": {
      "abstract": [],
      "deprecated": true,
      "fragments": [
        {
          "kind": "identifier",
          "text": "kPDFAnnotationKey_WidgetMaxLen"
        }
      ],
      "identifier": "doc://com.apple.pdfkit/documentation/PDFKit/kPDFAnnotationKey_WidgetMaxLen",
      "kind": "symbol",
      "role": "symbol",
      "title": "kPDFAnnotationKey_WidgetMaxLen",
      "type": "topic",
      "url": "/documentation/pdfkit/kpdfannotationkey_widgetmaxlen"
    },
    "doc://com.apple.pdfkit/documentation/PDFKit/kPDFAnnotationKey_WidgetOptions": {
      "abstract": [],
      "deprecated": true,
      "fragments": [
        {
          "kind": "identifier",
          "text": "kPDFAnnotationKey_WidgetOptions"
        }
      ],
      "identifier": "doc://com.apple.pdfkit/documentation/PDFKit/kPDFAnnotationKey_WidgetOptions",
      "kind": "symbol",
      "role": "symbol",
      "title": "kPDFAnnotationKey_WidgetOptions",
      "type": "topic",
      "url": "/documentation/pdfkit/kpdfannotationkey_widgetoptions"
    },
    "doc://com.apple.pdfkit/documentation/PDFKit/kPDFAnnotationKey_WidgetTextLabelUI": {
      "abstract": [],
      "deprecated": true,
      "fragments": [
        {
          "kind": "identifier",
          "text": "kPDFAnnotationKey_WidgetTextLabelUI"
        }
      ],
      "identifier": "doc://com.apple.pdfkit/documentation/PDFKit/kPDFAnnotationKey_WidgetTextLabelUI",
      "kind": "symbol",
      "role": "symbol",
      "title": "kPDFAnnotationKey_WidgetTextLabelUI",
      "type": "topic",
      "url": "/documentation/pdfkit/kpdfannotationkey_widgettextlabelui"
    },
    "doc://com.apple.pdfkit/documentation/PDFKit/kPDFAnnotationKey_WidgetValue": {
      "abstract": [],
      "deprecated": true,
      "fragments": [
        {
          "kind": "identifier",
          "text": "kPDFAnnotationKey_WidgetValue"
        }
      ],
      "identifier": "doc://com.apple.pdfkit/documentation/PDFKit/kPDFAnnotationKey_WidgetValue",
      "kind": "symbol",
      "role": "symbol",
      "title": "kPDFAnnotationKey_WidgetValue",
      "type": "topic",
      "url": "/documentation/pdfkit/kpdfannotationkey_widgetvalue"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "topicSections": [
    {
      "anchor": "Deprecated-Annotation-Types",
      "identifiers": [
        "doc://com.apple.pdfkit/documentation/PDFKit/PDFAnnotationButtonWidget",
        "doc://com.apple.pdfkit/documentation/PDFKit/PDFAnnotationChoiceWidget",
        "doc://com.apple.pdfkit/documentation/PDFKit/PDFAnnotationCircle",
        "doc://com.apple.pdfkit/documentation/PDFKit/PDFAnnotationFreeText",
        "doc://com.apple.pdfkit/documentation/PDFKit/PDFAnnotationInk",
        "doc://com.apple.pdfkit/documentation/PDFKit/PDFAnnotationLine",
        "doc://com.apple.pdfkit/documentation/PDFKit/PDFAnnotationLink",
        "doc://com.apple.pdfkit/documentation/PDFKit/PDFAnnotationMarkup",
        "doc://com.apple.pdfkit/documentation/PDFKit/PDFAnnotationPopup",
        "doc://com.apple.pdfkit/documentation/PDFKit/PDFAnnotationSquare",
        "doc://com.apple.pdfkit/documentation/PDFKit/PDFAnnotationStamp",
        "doc://com.apple.pdfkit/documentation/PDFKit/PDFAnnotationText",
        "doc://com.apple.pdfkit/documentation/PDFKit/PDFAnnotationTextWidget"
      ],
      "title": "Deprecated Annotation Types"
    },
    {
      "anchor": "Deprecated-Methods",
      "identifiers": [
        "doc://com.apple.pdfkit/documentation/PDFKit/PDFAnnotation/init(bounds:)",
        "doc://com.apple.pdfkit/documentation/PDFKit/PDFAnnotation/init(dictionary:forPage:)",
        "doc://com.apple.pdfkit/documentation/PDFKit/PDFAnnotation/removeAllAppearanceStreams()",
        "doc://com.apple.pdfkit/documentation/PDFKit/PDFAnnotation/draw(with:)"
      ],
      "title": "Deprecated Methods"
    },
    {
      "anchor": "Deprecated-Properties",
      "identifiers": [
        "doc://com.apple.pdfkit/documentation/PDFKit/PDFAnnotation/mouseUpAction",
        "doc://com.apple.pdfkit/documentation/PDFKit/PDFAnnotation/toolTip"
      ],
      "title": "Deprecated Properties"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Deprecated-Annotation-Types",
              "identifiers": [
                "doc://com.apple.pdfkit/documentation/PDFKit/PDFAnnotationButtonWidget",
                "doc://com.apple.pdfkit/documentation/PDFKit/PDFAnnotationChoiceWidget",
                "doc://com.apple.pdfkit/documentation/PDFKit/PDFAnnotationCircle",
                "doc://com.apple.pdfkit/documentation/PDFKit/PDFAnnotationFreeText",
                "doc://com.apple.pdfkit/documentation/PDFKit/PDFAnnotationInk",
                "doc://com.apple.pdfkit/documentation/PDFKit/PDFAnnotationLine",
                "doc://com.apple.pdfkit/documentation/PDFKit/PDFAnnotationLink",
                "doc://com.apple.pdfkit/documentation/PDFKit/PDFAnnotationMarkup",
                "doc://com.apple.pdfkit/documentation/PDFKit/PDFAnnotationPopup",
                "doc://com.apple.pdfkit/documentation/PDFKit/PDFAnnotationSquare",
                "doc://com.apple.pdfkit/documentation/PDFKit/PDFAnnotationStamp",
                "doc://com.apple.pdfkit/documentation/PDFKit/PDFAnnotationText",
                "doc://com.apple.pdfkit/documentation/PDFKit/PDFAnnotationTextWidget"
              ],
              "title": "Deprecated Annotation Types"
            },
            {
              "anchor": "Deprecated-Methods",
              "identifiers": [
                "doc://com.apple.pdfkit/documentation/PDFKit/PDFAnnotation/init(bounds:)",
                "doc://com.apple.pdfkit/documentation/PDFKit/PDFAnnotation/init(dictionary:forPage:)",
                "doc://com.apple.pdfkit/documentation/PDFKit/PDFAnnotation/removeAllAppearanceStreams()",
                "doc://com.apple.pdfkit/documentation/PDFKit/PDFAnnotation/draw(with:)"
              ],
              "title": "Deprecated Methods"
            },
            {
              "anchor": "Deprecated-Properties",
              "identifiers": [
                "doc://com.apple.pdfkit/documentation/PDFKit/PDFAnnotation/mouseUpAction",
                "doc://com.apple.pdfkit/documentation/PDFKit/PDFAnnotation/toolTip"
              ],
              "title": "Deprecated Properties"
            },
            {
              "anchor": "Deprecated-Annotation-Keys",
              "identifiers": [
                "doc://com.apple.pdfkit/documentation/PDFKit/kPDFAnnotationKey_Action",
                "doc://com.apple.pdfkit/documentation/PDFKit/kPDFAnnotationKey_AdditionalActions",
                "doc://com.apple.pdfkit/documentation/PDFKit/kPDFAnnotationKey_AppearanceDictionary",
                "doc://com.apple.pdfkit/documentation/PDFKit/kPDFAnnotationKey_AppearanceState",
                "doc://com.apple.pdfkit/documentation/PDFKit/kPDFAnnotationKey_Border",
                "doc://com.apple.pdfkit/documentation/PDFKit/kPDFAnnotationKey_BorderStyle",
                "doc://com.apple.pdfkit/documentation/PDFKit/kPDFAnnotationKey_Color",
                "doc://com.apple.pdfkit/documentation/PDFKit/kPDFAnnotationKey_Contents",
                "doc://com.apple.pdfkit/documentation/PDFKit/kPDFAnnotationKey_Date",
                "doc://com.apple.pdfkit/documentation/PDFKit/kPDFAnnotationKey_DefaultAppearance",
                "doc://com.apple.pdfkit/documentation/PDFKit/kPDFAnnotationKey_Destination",
                "doc://com.apple.pdfkit/documentation/PDFKit/kPDFAnnotationKey_Flags",
                "doc://com.apple.pdfkit/documentation/PDFKit/kPDFAnnotationKey_HighlightingMode",
                "doc://com.apple.pdfkit/documentation/PDFKit/kPDFAnnotationKey_IconName",
                "doc://com.apple.pdfkit/documentation/PDFKit/kPDFAnnotationKey_Inklist",
                "doc://com.apple.pdfkit/documentation/PDFKit/kPDFAnnotationKey_InteriorColor",
                "doc://com.apple.pdfkit/documentation/PDFKit/kPDFAnnotationKey_LineEndingStyles",
                "doc://com.apple.pdfkit/documentation/PDFKit/kPDFAnnotationKey_LinePoints",
                "doc://com.apple.pdfkit/documentation/PDFKit/kPDFAnnotationKey_Name",
                "doc://com.apple.pdfkit/documentation/PDFKit/kPDFAnnotationKey_Open",
                "doc://com.apple.pdfkit/documentation/PDFKit/kPDFAnnotationKey_Page",
                "doc://com.apple.pdfkit/documentation/PDFKit/kPDFAnnotationKey_Parent",
                "doc://com.apple.pdfkit/documentation/PDFKit/kPDFAnnotationKey_Popup",
                "doc://com.apple.pdfkit/documentation/PDFKit/kPDFAnnotationKey_QuadPoints",
                "doc://com.apple.pdfkit/documentation/PDFKit/kPDFAnnotationKey_Quadding",
                "doc://com.apple.pdfkit/documentation/PDFKit/kPDFAnnotationKey_Rect",
                "doc://com.apple.pdfkit/documentation/PDFKit/kPDFAnnotationKey_Subtype",
                "doc://com.apple.pdfkit/documentation/PDFKit/kPDFAnnotationKey_TextLabel",
                "doc://com.apple.pdfkit/documentation/PDFKit/kPDFAnnotationKey_WidgetAppearanceDictionary",
                "doc://com.apple.pdfkit/documentation/PDFKit/kPDFAnnotationKey_WidgetDefaultValue",
                "doc://com.apple.pdfkit/documentation/PDFKit/kPDFAnnotationKey_WidgetFieldFlags",
                "doc://com.apple.pdfkit/documentation/PDFKit/kPDFAnnotationKey_WidgetFieldType",
                "doc://com.apple.pdfkit/documentation/PDFKit/kPDFAnnotationKey_WidgetMaxLen",
                "doc://com.apple.pdfkit/documentation/PDFKit/kPDFAnnotationKey_WidgetOptions",
                "doc://com.apple.pdfkit/documentation/PDFKit/kPDFAnnotationKey_WidgetTextLabelUI",
                "doc://com.apple.pdfkit/documentation/PDFKit/kPDFAnnotationKey_WidgetValue"
              ],
              "title": "Deprecated Annotation Keys"
            }
          ]
        },
        {
          "op": "add",
          "path": "/seeAlsoSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFAnnotationLine/title",
          "value": "PDFAnnotationLine"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFAnnotationLine/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PDFAnnotationLine"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFAnnotationLine/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "PDFAnnotationLine"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFAnnotationFreeText/title",
          "value": "PDFAnnotationFreeText"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFAnnotationFreeText/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PDFAnnotationFreeText"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFAnnotationFreeText/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "PDFAnnotationFreeText"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFAnnotation~1mouseUpAction/title",
          "value": "mouseUpAction"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFAnnotation~1mouseUpAction/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "mouseUpAction"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFAnnotationText/title",
          "value": "PDFAnnotationText"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFAnnotationText/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PDFAnnotationText"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFAnnotationText/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "PDFAnnotationText"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFAnnotationStamp/title",
          "value": "PDFAnnotationStamp"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFAnnotationStamp/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PDFAnnotationStamp"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFAnnotationStamp/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "PDFAnnotationStamp"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFAnnotation~1init(bounds:)/title",
          "value": "initWithBounds:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFAnnotation~1init(bounds:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "initWithBounds:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFAnnotation/title",
          "value": "PDFAnnotation"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFAnnotation/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PDFAnnotation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFAnnotation/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "PDFAnnotation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFAnnotationTextWidget/title",
          "value": "PDFAnnotationTextWidget"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFAnnotationTextWidget/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PDFAnnotationTextWidget"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFAnnotationTextWidget/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "PDFAnnotationTextWidget"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFAnnotationSquare/title",
          "value": "PDFAnnotationSquare"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFAnnotationSquare/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PDFAnnotationSquare"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFAnnotationSquare/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "PDFAnnotationSquare"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFAnnotationInk/title",
          "value": "PDFAnnotationInk"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFAnnotationInk/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PDFAnnotationInk"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFAnnotationInk/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "PDFAnnotationInk"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFAnnotation~1toolTip/title",
          "value": "toolTip"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFAnnotation~1toolTip/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "toolTip"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFAnnotationButtonWidget/title",
          "value": "PDFAnnotationButtonWidget"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFAnnotationButtonWidget/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PDFAnnotationButtonWidget"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFAnnotationButtonWidget/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "PDFAnnotationButtonWidget"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFAnnotationChoiceWidget/title",
          "value": "PDFAnnotationChoiceWidget"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFAnnotationChoiceWidget/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PDFAnnotationChoiceWidget"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFAnnotationChoiceWidget/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "PDFAnnotationChoiceWidget"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFAnnotation~1removeAllAppearanceStreams()/title",
          "value": "removeAllAppearanceStreams"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFAnnotation~1removeAllAppearanceStreams()/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "removeAllAppearanceStreams"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFAnnotationLink/title",
          "value": "PDFAnnotationLink"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFAnnotationLink/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PDFAnnotationLink"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFAnnotationLink/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "PDFAnnotationLink"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFAnnotationMarkup/title",
          "value": "PDFAnnotationMarkup"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFAnnotationMarkup/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PDFAnnotationMarkup"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFAnnotationMarkup/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "PDFAnnotationMarkup"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFAnnotation~1draw(with:)/title",
          "value": "drawWithBox:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFAnnotation~1draw(with:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "drawWithBox:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFAnnotationPopup/title",
          "value": "PDFAnnotationPopup"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFAnnotationPopup/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PDFAnnotationPopup"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFAnnotationPopup/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "PDFAnnotationPopup"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFAnnotation~1init(dictionary:forPage:)/title",
          "value": "initWithDictionary:forPage:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFAnnotation~1init(dictionary:forPage:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "initWithDictionary:forPage:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFAnnotationCircle/title",
          "value": "PDFAnnotationCircle"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFAnnotationCircle/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PDFAnnotationCircle"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFAnnotationCircle/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "PDFAnnotationCircle"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/pdfkit/deprecated-symbols"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/pdfkit/deprecated-symbols"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
