{
  "abstract": [
    {
      "text": "Handle selections, work with annotation actions, convert page and view points, and work with mouse events in a document.",
      "type": "text"
    }
  ],
  "diffAvailability": {
    "major": {
      "change": "modified",
      "platform": "Xcode",
      "versions": [
        "16.0",
        "16.3 beta 2"
      ]
    }
  },
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.pdfkit/documentation/PDFKit",
        "doc://com.apple.pdfkit/documentation/PDFKit/PDFView"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.pdfkit/documentation/PDFKit/document-interactions"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "PDFKit"
      }
    ],
    "role": "collectionGroup",
    "roleHeading": "API Collection",
    "title": "Document Interactions"
  },
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.pdfkit/documentation/PDFKit": {
      "abstract": [
        {
          "text": "Display and manipulate PDF documents in your apps.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.pdfkit/documentation/PDFKit",
      "kind": "symbol",
      "role": "collection",
      "title": "PDFKit",
      "type": "topic",
      "url": "/documentation/pdfkit"
    },
    "doc://com.apple.pdfkit/documentation/PDFKit/PDFAreaOfInterest": {
      "abstract": [
        {
          "text": "The mouse position over PDF view areas.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "PDFAreaOfInterest"
        }
      ],
      "identifier": "doc://com.apple.pdfkit/documentation/PDFKit/PDFAreaOfInterest",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PDFAreaOfInterest"
        }
      ],
      "role": "symbol",
      "title": "PDFAreaOfInterest",
      "type": "topic",
      "url": "/documentation/pdfkit/pdfareaofinterest"
    },
    "doc://com.apple.pdfkit/documentation/PDFKit/PDFView": {
      "abstract": [
        {
          "text": "An object that encapsulates the functionality of PDF Kit into a single widget that you can add to your application using Interface Builder.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "PDFView"
        }
      ],
      "identifier": "doc://com.apple.pdfkit/documentation/PDFKit/PDFView",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PDFView"
        }
      ],
      "role": "symbol",
      "title": "PDFView",
      "type": "topic",
      "url": "/documentation/pdfkit/pdfview"
    },
    "doc://com.apple.pdfkit/documentation/PDFKit/PDFView/annotationsChanged(on:)": {
      "abstract": [
        {
          "text": "Tells the PDF view that an annotation on the specified page has changed.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "annotationsChanged"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "on"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)PDFPage",
          "text": "PDFPage"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.pdfkit/documentation/PDFKit/PDFView/annotationsChanged(on:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "annotationsChangedOnPage:"
        }
      ],
      "role": "symbol",
      "title": "annotationsChanged(on:)",
      "type": "topic",
      "url": "/documentation/pdfkit/pdfview/annotationschanged(on:)"
    },
    "doc://com.apple.pdfkit/documentation/PDFKit/PDFView/areaOfInterest(for:)": {
      "abstract": [
        {
          "text": "Returns the type of area for a specific cursor location point.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "areaOfInterest"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "for"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@CGPoint",
          "text": "CGPoint"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@PDFAreaOfInterest",
          "text": "PDFAreaOfInterest"
        }
      ],
      "identifier": "doc://com.apple.pdfkit/documentation/PDFKit/PDFView/areaOfInterest(for:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "areaOfInterestForPoint:"
        }
      ],
      "role": "symbol",
      "title": "areaOfInterest(for:)",
      "type": "topic",
      "url": "/documentation/pdfkit/pdfview/areaofinterest(for:)"
    },
    "doc://com.apple.pdfkit/documentation/PDFKit/PDFView/areaOfInterest(forMouse:)": {
      "abstract": [
        {
          "text": "Returns the type of area the mouse cursor is over.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "areaOfInterest"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "forMouse"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UIEvent",
          "text": "UIEvent"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@PDFAreaOfInterest",
          "text": "PDFAreaOfInterest"
        }
      ],
      "identifier": "doc://com.apple.pdfkit/documentation/PDFKit/PDFView/areaOfInterest(forMouse:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "areaOfInterestForMouse:"
        }
      ],
      "role": "symbol",
      "title": "areaOfInterest(forMouse:)",
      "type": "topic",
      "url": "/documentation/pdfkit/pdfview/areaofinterest(formouse:)"
    },
    "doc://com.apple.pdfkit/documentation/PDFKit/PDFView/clearSelection()": {
      "abstract": [
        {
          "text": "Clears the selection.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "clearSelection"
        },
        {
          "kind": "text",
          "text": "()"
        }
      ],
      "identifier": "doc://com.apple.pdfkit/documentation/PDFKit/PDFView/clearSelection()",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "clearSelection"
        }
      ],
      "role": "symbol",
      "title": "clearSelection()",
      "type": "topic",
      "url": "/documentation/pdfkit/pdfview/clearselection()"
    },
    "doc://com.apple.pdfkit/documentation/PDFKit/PDFView/convert(_:from:)-4evlx": {
      "abstract": [
        {
          "text": "Converts a point from page space to view space.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "convert"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@CGPoint",
          "text": "CGPoint"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "from"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)PDFPage",
          "text": "PDFPage"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@CGPoint",
          "text": "CGPoint"
        }
      ],
      "identifier": "doc://com.apple.pdfkit/documentation/PDFKit/PDFView/convert(_:from:)-4evlx",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "convertPoint:fromPage:"
        }
      ],
      "role": "symbol",
      "title": "convert(_:from:)",
      "type": "topic",
      "url": "/documentation/pdfkit/pdfview/convert(_:from:)-4evlx"
    },
    "doc://com.apple.pdfkit/documentation/PDFKit/PDFView/convert(_:from:)-9xv1z": {
      "abstract": [
        {
          "text": "Converts a rectangle from page space to view space.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "convert"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@CGRect",
          "text": "CGRect"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "from"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)PDFPage",
          "text": "PDFPage"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@CGRect",
          "text": "CGRect"
        }
      ],
      "identifier": "doc://com.apple.pdfkit/documentation/PDFKit/PDFView/convert(_:from:)-9xv1z",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "convertRect:fromPage:"
        }
      ],
      "role": "symbol",
      "title": "convert(_:from:)",
      "type": "topic",
      "url": "/documentation/pdfkit/pdfview/convert(_:from:)-9xv1z"
    },
    "doc://com.apple.pdfkit/documentation/PDFKit/PDFView/convert(_:to:)-8cp0c": {
      "abstract": [
        {
          "text": "Converts a rectangle from view space to page space.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "convert"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@CGRect",
          "text": "CGRect"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "to"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)PDFPage",
          "text": "PDFPage"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@CGRect",
          "text": "CGRect"
        }
      ],
      "identifier": "doc://com.apple.pdfkit/documentation/PDFKit/PDFView/convert(_:to:)-8cp0c",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "convertRect:toPage:"
        }
      ],
      "role": "symbol",
      "title": "convert(_:to:)",
      "type": "topic",
      "url": "/documentation/pdfkit/pdfview/convert(_:to:)-8cp0c"
    },
    "doc://com.apple.pdfkit/documentation/PDFKit/PDFView/convert(_:to:)-9twqk": {
      "abstract": [
        {
          "text": "Converts a point from view space to page space.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "convert"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@CGPoint",
          "text": "CGPoint"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "to"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)PDFPage",
          "text": "PDFPage"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@CGPoint",
          "text": "CGPoint"
        }
      ],
      "identifier": "doc://com.apple.pdfkit/documentation/PDFKit/PDFView/convert(_:to:)-9twqk",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "convertPoint:toPage:"
        }
      ],
      "role": "symbol",
      "title": "convert(_:to:)",
      "type": "topic",
      "url": "/documentation/pdfkit/pdfview/convert(_:to:)-9twqk"
    },
    "doc://com.apple.pdfkit/documentation/PDFKit/PDFView/copy(_:)": {
      "abstract": [
        {
          "text": "Copies the text in the selection, if any, to the Pasteboard.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "copy"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "keyword",
          "text": "Any"
        },
        {
          "kind": "text",
          "text": "?)"
        }
      ],
      "identifier": "doc://com.apple.pdfkit/documentation/PDFKit/PDFView/copy(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "copy:"
        }
      ],
      "role": "symbol",
      "title": "copy(_:)",
      "type": "topic",
      "url": "/documentation/pdfkit/pdfview/copy(_:)"
    },
    "doc://com.apple.pdfkit/documentation/PDFKit/PDFView/currentSelection": {
      "abstract": [
        {
          "text": "The current selection.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "currentSelection"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)PDFSelection",
          "text": "PDFSelection"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.pdfkit/documentation/PDFKit/PDFView/currentSelection",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "currentSelection"
        }
      ],
      "role": "symbol",
      "title": "currentSelection",
      "type": "topic",
      "url": "/documentation/pdfkit/pdfview/currentselection"
    },
    "doc://com.apple.pdfkit/documentation/PDFKit/PDFView/highlightedSelections": {
      "abstract": [
        {
          "text": "Returns the array of selections that are highlighted using ",
          "type": "text"
        },
        {
          "code": "setHighlightedSelections",
          "type": "codeVoice"
        },
        {
          "text": ".",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "highlightedSelections"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)PDFSelection",
          "text": "PDFSelection"
        },
        {
          "kind": "text",
          "text": "]?"
        }
      ],
      "identifier": "doc://com.apple.pdfkit/documentation/PDFKit/PDFView/highlightedSelections",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "highlightedSelections"
        }
      ],
      "role": "symbol",
      "title": "highlightedSelections",
      "type": "topic",
      "url": "/documentation/pdfkit/pdfview/highlightedselections"
    },
    "doc://com.apple.pdfkit/documentation/PDFKit/PDFView/page(for:nearest:)": {
      "abstract": [
        {
          "text": "Returns the page containing a point specified in view coordinates.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "page"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "for"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@CGPoint",
          "text": "CGPoint"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "nearest"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)PDFPage",
          "text": "PDFPage"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.pdfkit/documentation/PDFKit/PDFView/page(for:nearest:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "pageForPoint:nearest:"
        }
      ],
      "role": "symbol",
      "title": "page(for:nearest:)",
      "type": "topic",
      "url": "/documentation/pdfkit/pdfview/page(for:nearest:)"
    },
    "doc://com.apple.pdfkit/documentation/PDFKit/PDFView/perform(_:)": {
      "abstract": [
        {
          "text": "Performs the specified action.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "perform"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)PDFAction",
          "text": "PDFAction"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.pdfkit/documentation/PDFKit/PDFView/perform(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "performAction:"
        }
      ],
      "role": "symbol",
      "title": "perform(_:)",
      "type": "topic",
      "url": "/documentation/pdfkit/pdfview/perform(_:)"
    },
    "doc://com.apple.pdfkit/documentation/PDFKit/PDFView/scrollSelectionToVisible(_:)": {
      "abstract": [
        {
          "text": "Scrolls the view until the selection is visible.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "scrollSelectionToVisible"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "keyword",
          "text": "Any"
        },
        {
          "kind": "text",
          "text": "?)"
        }
      ],
      "identifier": "doc://com.apple.pdfkit/documentation/PDFKit/PDFView/scrollSelectionToVisible(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "scrollSelectionToVisible:"
        }
      ],
      "role": "symbol",
      "title": "scrollSelectionToVisible(_:)",
      "type": "topic",
      "url": "/documentation/pdfkit/pdfview/scrollselectiontovisible(_:)"
    },
    "doc://com.apple.pdfkit/documentation/PDFKit/PDFView/selectAll(_:)": {
      "abstract": [
        {
          "text": "Selects all text in the document.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "selectAll"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "keyword",
          "text": "Any"
        },
        {
          "kind": "text",
          "text": "?)"
        }
      ],
      "identifier": "doc://com.apple.pdfkit/documentation/PDFKit/PDFView/selectAll(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "selectAll:"
        }
      ],
      "role": "symbol",
      "title": "selectAll(_:)",
      "type": "topic",
      "url": "/documentation/pdfkit/pdfview/selectall(_:)"
    },
    "doc://com.apple.pdfkit/documentation/PDFKit/PDFView/setCurrentSelection(_:animate:)": {
      "abstract": [
        {
          "text": "Sets the current selection, in an animated way, if desired.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "setCurrentSelection"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)PDFSelection",
          "text": "PDFSelection"
        },
        {
          "kind": "text",
          "text": "?, "
        },
        {
          "kind": "externalParam",
          "text": "animate"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.pdfkit/documentation/PDFKit/PDFView/setCurrentSelection(_:animate:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "setCurrentSelection:animate:"
        }
      ],
      "role": "symbol",
      "title": "setCurrentSelection(_:animate:)",
      "type": "topic",
      "url": "/documentation/pdfkit/pdfview/setcurrentselection(_:animate:)"
    },
    "doc://com.apple.pdfkit/documentation/PDFKit/PDFView/setCursorFor(_:)": {
      "abstract": [
        {
          "text": "Sets the type of mouse cursor according to the type of area the mouse cursor is over.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "setCursorFor"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@PDFAreaOfInterest",
          "text": "PDFAreaOfInterest"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.pdfkit/documentation/PDFKit/PDFView/setCursorFor(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "setCursorForAreaOfInterest:"
        }
      ],
      "role": "symbol",
      "title": "setCursorFor(_:)",
      "type": "topic",
      "url": "/documentation/pdfkit/pdfview/setcursorfor(_:)"
    },
    "doc://com.apple.pdfkit/documentation/PDFKit/drag-operations": {
      "abstract": [
        {
          "text": "Define drag operations allowed for a view.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.pdfkit/documentation/PDFKit/drag-operations",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Drag Operations",
      "type": "topic",
      "url": "/documentation/pdfkit/drag-operations"
    },
    "doc://com.apple.pdfkit/documentation/PDFKit/link-annotations": {
      "abstract": [
        {
          "text": "Validate and handle links in a PDF view.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.pdfkit/documentation/PDFKit/link-annotations",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Link Annotations",
      "type": "topic",
      "url": "/documentation/pdfkit/link-annotations"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "topicSections": [
    {
      "anchor": "Handling-Selections",
      "identifiers": [
        "doc://com.apple.pdfkit/documentation/PDFKit/PDFView/currentSelection",
        "doc://com.apple.pdfkit/documentation/PDFKit/PDFView/setCurrentSelection(_:animate:)",
        "doc://com.apple.pdfkit/documentation/PDFKit/PDFView/selectAll(_:)",
        "doc://com.apple.pdfkit/documentation/PDFKit/PDFView/clearSelection()",
        "doc://com.apple.pdfkit/documentation/PDFKit/PDFView/copy(_:)",
        "doc://com.apple.pdfkit/documentation/PDFKit/PDFView/scrollSelectionToVisible(_:)",
        "doc://com.apple.pdfkit/documentation/PDFKit/PDFView/highlightedSelections"
      ],
      "title": "Handling Selections"
    },
    {
      "anchor": "Working-with-Annotation-Actions",
      "identifiers": [
        "doc://com.apple.pdfkit/documentation/PDFKit/PDFView/annotationsChanged(on:)",
        "doc://com.apple.pdfkit/documentation/PDFKit/link-annotations"
      ],
      "title": "Working with Annotation Actions"
    },
    {
      "anchor": "Converting-Page-and-View-Points",
      "identifiers": [
        "doc://com.apple.pdfkit/documentation/PDFKit/PDFView/page(for:nearest:)",
        "doc://com.apple.pdfkit/documentation/PDFKit/PDFView/convert(_:to:)-9twqk",
        "doc://com.apple.pdfkit/documentation/PDFKit/PDFView/convert(_:to:)-8cp0c",
        "doc://com.apple.pdfkit/documentation/PDFKit/PDFView/convert(_:from:)-4evlx",
        "doc://com.apple.pdfkit/documentation/PDFKit/PDFView/convert(_:from:)-9xv1z"
      ],
      "title": "Converting Page and View Points"
    },
    {
      "anchor": "Working-with-Mouse-Position-and-Events",
      "identifiers": [
        "doc://com.apple.pdfkit/documentation/PDFKit/PDFView/areaOfInterest(forMouse:)",
        "doc://com.apple.pdfkit/documentation/PDFKit/PDFView/areaOfInterest(for:)",
        "doc://com.apple.pdfkit/documentation/PDFKit/PDFAreaOfInterest",
        "doc://com.apple.pdfkit/documentation/PDFKit/PDFView/setCursorFor(_:)",
        "doc://com.apple.pdfkit/documentation/PDFKit/PDFView/perform(_:)",
        "doc://com.apple.pdfkit/documentation/PDFKit/drag-operations"
      ],
      "title": "Working with Mouse Position and Events"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Handling-Selections",
              "identifiers": [
                "doc://com.apple.pdfkit/documentation/PDFKit/PDFView/currentSelection",
                "doc://com.apple.pdfkit/documentation/PDFKit/PDFView/setCurrentSelection(_:animate:)",
                "doc://com.apple.pdfkit/documentation/PDFKit/PDFView/selectAll(_:)",
                "doc://com.apple.pdfkit/documentation/PDFKit/PDFView/clearSelection()",
                "doc://com.apple.pdfkit/documentation/PDFKit/PDFView/copy(_:)",
                "doc://com.apple.pdfkit/documentation/PDFKit/PDFView/scrollSelectionToVisible(_:)",
                "doc://com.apple.pdfkit/documentation/PDFKit/PDFView/highlightedSelections"
              ],
              "title": "Handling Selections"
            },
            {
              "anchor": "Working-with-Annotation-Actions",
              "identifiers": [
                "doc://com.apple.pdfkit/documentation/PDFKit/PDFView/annotationsChanged(on:)",
                "doc://com.apple.pdfkit/documentation/PDFKit/link-annotations"
              ],
              "title": "Working with Annotation Actions"
            },
            {
              "anchor": "Converting-Page-and-View-Points",
              "identifiers": [
                "doc://com.apple.pdfkit/documentation/PDFKit/PDFView/page(for:nearest:)",
                "doc://com.apple.pdfkit/documentation/PDFKit/PDFView/convert(_:to:)-9twqk",
                "doc://com.apple.pdfkit/documentation/PDFKit/PDFView/convert(_:to:)-8cp0c",
                "doc://com.apple.pdfkit/documentation/PDFKit/PDFView/convert(_:from:)-4evlx",
                "doc://com.apple.pdfkit/documentation/PDFKit/PDFView/convert(_:from:)-9xv1z"
              ],
              "title": "Converting Page and View Points"
            },
            {
              "anchor": "Working-with-Mouse-Position-and-Events",
              "identifiers": [
                "doc://com.apple.pdfkit/documentation/PDFKit/PDFView/areaOfInterest(forMouse:)",
                "doc://com.apple.pdfkit/documentation/PDFKit/PDFView/areaOfInterest(for:)",
                "doc://com.apple.pdfkit/documentation/PDFKit/PDFAreaOfInterest",
                "doc://com.apple.pdfkit/documentation/PDFKit/PDFView/setCursorFor(_:)",
                "doc://com.apple.pdfkit/documentation/PDFKit/PDFView/perform(_:)",
                "doc://com.apple.pdfkit/documentation/PDFKit/drag-operations"
              ],
              "title": "Working with Mouse Position and Events"
            }
          ]
        },
        {
          "op": "add",
          "path": "/seeAlsoSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFView/title",
          "value": "PDFView"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFView/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PDFView"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFView/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "PDFView"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFAreaOfInterest/title",
          "value": "PDFAreaOfInterest"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFAreaOfInterest/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PDFAreaOfInterest"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFAreaOfInterest/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "PDFAreaOfInterest"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFView~1scrollSelectionToVisible(_:)/title",
          "value": "scrollSelectionToVisible:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFView~1scrollSelectionToVisible(_:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "scrollSelectionToVisible:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFView~1currentSelection/title",
          "value": "currentSelection"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFView~1currentSelection/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "currentSelection"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFView~1clearSelection()/title",
          "value": "clearSelection"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFView~1clearSelection()/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "clearSelection"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFView~1highlightedSelections/title",
          "value": "highlightedSelections"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFView~1highlightedSelections/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "highlightedSelections"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFView~1setCurrentSelection(_:animate:)/title",
          "value": "setCurrentSelection:animate:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFView~1setCurrentSelection(_:animate:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "setCurrentSelection:animate:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFView~1areaOfInterest(forMouse:)/title",
          "value": "areaOfInterestForMouse:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFView~1areaOfInterest(forMouse:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "areaOfInterestForMouse:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFView~1page(for:nearest:)/title",
          "value": "pageForPoint:nearest:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFView~1page(for:nearest:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "pageForPoint:nearest:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFView~1perform(_:)/title",
          "value": "performAction:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFView~1perform(_:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "performAction:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFView~1areaOfInterest(for:)/title",
          "value": "areaOfInterestForPoint:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFView~1areaOfInterest(for:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "areaOfInterestForPoint:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFView~1annotationsChanged(on:)/title",
          "value": "annotationsChangedOnPage:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFView~1annotationsChanged(on:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "annotationsChangedOnPage:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFView~1convert(_:to:)-8cp0c/title",
          "value": "convertRect:toPage:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFView~1convert(_:to:)-8cp0c/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "convertRect:toPage:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFView~1convert(_:to:)-9twqk/title",
          "value": "convertPoint:toPage:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFView~1convert(_:to:)-9twqk/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "convertPoint:toPage:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFView~1selectAll(_:)/title",
          "value": "selectAll:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFView~1selectAll(_:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "selectAll:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFView~1convert(_:from:)-4evlx/title",
          "value": "convertPoint:fromPage:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFView~1convert(_:from:)-4evlx/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "convertPoint:fromPage:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFView~1setCursorFor(_:)/title",
          "value": "setCursorForAreaOfInterest:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFView~1setCursorFor(_:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "setCursorForAreaOfInterest:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFView~1convert(_:from:)-9xv1z/title",
          "value": "convertRect:fromPage:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFView~1convert(_:from:)-9xv1z/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "convertRect:fromPage:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFView~1copy(_:)/title",
          "value": "copy:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFView~1copy(_:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "copy:"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/pdfkit/document-interactions"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/pdfkit/document-interactions"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
