{
  "abstract": [
    {
      "text": "Define drag operations allowed for a view.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.pdfkit/documentation/PDFKit",
        "doc://com.apple.pdfkit/documentation/PDFKit/PDFView",
        "doc://com.apple.pdfkit/documentation/PDFKit/document-interactions"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.pdfkit/documentation/PDFKit/drag-operations"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "PDFKit"
      }
    ],
    "role": "collectionGroup",
    "roleHeading": "API Collection",
    "title": "Drag Operations"
  },
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.pdfkit/documentation/PDFKit": {
      "abstract": [
        {
          "text": "Display and manipulate PDF documents in your apps.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.pdfkit/documentation/PDFKit",
      "kind": "symbol",
      "role": "collection",
      "title": "PDFKit",
      "type": "topic",
      "url": "/documentation/pdfkit"
    },
    "doc://com.apple.pdfkit/documentation/PDFKit/PDFAreaOfInterest": {
      "abstract": [
        {
          "text": "The mouse position over PDF view areas.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "PDFAreaOfInterest"
        }
      ],
      "identifier": "doc://com.apple.pdfkit/documentation/PDFKit/PDFAreaOfInterest",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PDFAreaOfInterest"
        }
      ],
      "role": "symbol",
      "title": "PDFAreaOfInterest",
      "type": "topic",
      "url": "/documentation/pdfkit/pdfareaofinterest"
    },
    "doc://com.apple.pdfkit/documentation/PDFKit/PDFView": {
      "abstract": [
        {
          "text": "An object that encapsulates the functionality of PDF Kit into a single widget that you can add to your application using Interface Builder.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "PDFView"
        }
      ],
      "identifier": "doc://com.apple.pdfkit/documentation/PDFKit/PDFView",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PDFView"
        }
      ],
      "role": "symbol",
      "title": "PDFView",
      "type": "topic",
      "url": "/documentation/pdfkit/pdfview"
    },
    "doc://com.apple.pdfkit/documentation/PDFKit/PDFView/acceptsDraggedFiles": {
      "abstract": [
        {
          "text": "A Boolean value indicating whether you can drag a file into the view.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "acceptsDraggedFiles"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.pdfkit/documentation/PDFKit/PDFView/acceptsDraggedFiles",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "acceptsDraggedFiles"
        }
      ],
      "role": "symbol",
      "title": "acceptsDraggedFiles",
      "type": "topic",
      "url": "/documentation/pdfkit/pdfview/acceptsdraggedfiles"
    },
    "doc://com.apple.pdfkit/documentation/PDFKit/PDFView/allowsDragging": {
      "abstract": [
        {
          "text": "A Boolean value indicating whether the view can accept new PDF documents dragged into it by the user.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "allowsDragging"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.pdfkit/documentation/PDFKit/PDFView/allowsDragging",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "allowsDragging"
        }
      ],
      "role": "symbol",
      "title": "allowsDragging",
      "type": "topic",
      "url": "/documentation/pdfkit/pdfview/allowsdragging"
    },
    "doc://com.apple.pdfkit/documentation/PDFKit/PDFView/areaOfInterest(for:)": {
      "abstract": [
        {
          "text": "Returns the type of area for a specific cursor location point.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "areaOfInterest"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "for"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@CGPoint",
          "text": "CGPoint"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@PDFAreaOfInterest",
          "text": "PDFAreaOfInterest"
        }
      ],
      "identifier": "doc://com.apple.pdfkit/documentation/PDFKit/PDFView/areaOfInterest(for:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "areaOfInterestForPoint:"
        }
      ],
      "role": "symbol",
      "title": "areaOfInterest(for:)",
      "type": "topic",
      "url": "/documentation/pdfkit/pdfview/areaofinterest(for:)"
    },
    "doc://com.apple.pdfkit/documentation/PDFKit/PDFView/areaOfInterest(forMouse:)": {
      "abstract": [
        {
          "text": "Returns the type of area the mouse cursor is over.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "areaOfInterest"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "forMouse"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UIEvent",
          "text": "UIEvent"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@PDFAreaOfInterest",
          "text": "PDFAreaOfInterest"
        }
      ],
      "identifier": "doc://com.apple.pdfkit/documentation/PDFKit/PDFView/areaOfInterest(forMouse:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "areaOfInterestForMouse:"
        }
      ],
      "role": "symbol",
      "title": "areaOfInterest(forMouse:)",
      "type": "topic",
      "url": "/documentation/pdfkit/pdfview/areaofinterest(formouse:)"
    },
    "doc://com.apple.pdfkit/documentation/PDFKit/PDFView/perform(_:)": {
      "abstract": [
        {
          "text": "Performs the specified action.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "perform"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)PDFAction",
          "text": "PDFAction"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.pdfkit/documentation/PDFKit/PDFView/perform(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "performAction:"
        }
      ],
      "role": "symbol",
      "title": "perform(_:)",
      "type": "topic",
      "url": "/documentation/pdfkit/pdfview/perform(_:)"
    },
    "doc://com.apple.pdfkit/documentation/PDFKit/PDFView/setCursorFor(_:)": {
      "abstract": [
        {
          "text": "Sets the type of mouse cursor according to the type of area the mouse cursor is over.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "setCursorFor"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@PDFAreaOfInterest",
          "text": "PDFAreaOfInterest"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.pdfkit/documentation/PDFKit/PDFView/setCursorFor(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "setCursorForAreaOfInterest:"
        }
      ],
      "role": "symbol",
      "title": "setCursorFor(_:)",
      "type": "topic",
      "url": "/documentation/pdfkit/pdfview/setcursorfor(_:)"
    },
    "doc://com.apple.pdfkit/documentation/PDFKit/document-interactions": {
      "abstract": [
        {
          "text": "Handle selections, work with annotation actions, convert page and view points, and work with mouse events in a document.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.pdfkit/documentation/PDFKit/document-interactions",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Document Interactions",
      "type": "topic",
      "url": "/documentation/pdfkit/document-interactions"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Working-with-Mouse-Position-and-Events",
      "generated": true,
      "identifiers": [
        "doc://com.apple.pdfkit/documentation/PDFKit/PDFView/areaOfInterest(forMouse:)",
        "doc://com.apple.pdfkit/documentation/PDFKit/PDFView/areaOfInterest(for:)",
        "doc://com.apple.pdfkit/documentation/PDFKit/PDFAreaOfInterest",
        "doc://com.apple.pdfkit/documentation/PDFKit/PDFView/setCursorFor(_:)",
        "doc://com.apple.pdfkit/documentation/PDFKit/PDFView/perform(_:)"
      ],
      "title": "Working with Mouse Position and Events"
    }
  ],
  "topicSections": [
    {
      "anchor": "Dragging-in-a-View",
      "identifiers": [
        "doc://com.apple.pdfkit/documentation/PDFKit/PDFView/allowsDragging",
        "doc://com.apple.pdfkit/documentation/PDFKit/PDFView/acceptsDraggedFiles"
      ],
      "title": "Dragging in a View"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Dragging-in-a-View",
              "identifiers": [
                "doc://com.apple.pdfkit/documentation/PDFKit/PDFView/allowsDragging",
                "doc://com.apple.pdfkit/documentation/PDFKit/PDFView/acceptsDraggedFiles"
              ],
              "title": "Dragging in a View"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Working-with-Mouse-Position-and-Events",
              "generated": true,
              "identifiers": [
                "doc://com.apple.pdfkit/documentation/PDFKit/PDFView/areaOfInterest(forMouse:)",
                "doc://com.apple.pdfkit/documentation/PDFKit/PDFView/areaOfInterest(for:)",
                "doc://com.apple.pdfkit/documentation/PDFKit/PDFAreaOfInterest",
                "doc://com.apple.pdfkit/documentation/PDFKit/PDFView/setCursorFor(_:)",
                "doc://com.apple.pdfkit/documentation/PDFKit/PDFView/perform(_:)"
              ],
              "title": "Working with Mouse Position and Events"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFView~1acceptsDraggedFiles/title",
          "value": "acceptsDraggedFiles"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFView~1acceptsDraggedFiles/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "acceptsDraggedFiles"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFView~1allowsDragging/title",
          "value": "allowsDragging"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFView~1allowsDragging/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "allowsDragging"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFView/title",
          "value": "PDFView"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFView/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PDFView"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFView/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "PDFView"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFView~1areaOfInterest(forMouse:)/title",
          "value": "areaOfInterestForMouse:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFView~1areaOfInterest(forMouse:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "areaOfInterestForMouse:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFView~1areaOfInterest(for:)/title",
          "value": "areaOfInterestForPoint:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFView~1areaOfInterest(for:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "areaOfInterestForPoint:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFView~1setCursorFor(_:)/title",
          "value": "setCursorForAreaOfInterest:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFView~1setCursorFor(_:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "setCursorForAreaOfInterest:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFAreaOfInterest/title",
          "value": "PDFAreaOfInterest"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFAreaOfInterest/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PDFAreaOfInterest"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFAreaOfInterest/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "PDFAreaOfInterest"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFView~1perform(_:)/title",
          "value": "performAction:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFView~1perform(_:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "performAction:"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/pdfkit/drag-operations"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/pdfkit/drag-operations"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
