{
  "diffAvailability": {
    "major": {
      "change": "modified",
      "platform": "Xcode",
      "versions": [
        "16.0",
        "16.3 beta 2"
      ]
    }
  },
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.pdfkit/documentation/PDFKit"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.pdfkit/documentation/PDFKit/enumerations"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "PDFKit"
      }
    ],
    "role": "collectionGroup",
    "roleHeading": "API Collection",
    "title": "PDFKit Enumerations"
  },
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.pdfkit/documentation/PDFKit": {
      "abstract": [
        {
          "text": "Display and manipulate PDF documents in your apps.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.pdfkit/documentation/PDFKit",
      "kind": "symbol",
      "role": "collection",
      "title": "PDFKit",
      "type": "topic",
      "url": "/documentation/pdfkit"
    },
    "doc://com.apple.pdfkit/documentation/PDFKit/PDFAccessPermissions": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "PDFAccessPermissions"
        }
      ],
      "identifier": "doc://com.apple.pdfkit/documentation/PDFKit/PDFAccessPermissions",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PDFAccessPermissions"
        }
      ],
      "role": "symbol",
      "title": "PDFAccessPermissions",
      "type": "topic",
      "url": "/documentation/pdfkit/pdfaccesspermissions"
    },
    "doc://com.apple.pdfkit/documentation/PDFKit/PDFSelectionGranularity": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "PDFSelectionGranularity"
        }
      ],
      "identifier": "doc://com.apple.pdfkit/documentation/PDFKit/PDFSelectionGranularity",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PDFSelectionGranularity"
        }
      ],
      "role": "symbol",
      "title": "PDFSelectionGranularity",
      "type": "topic",
      "url": "/documentation/pdfkit/pdfselectiongranularity"
    },
    "doc://com.apple.pdfkit/documentation/PDFKit/PDFThumbnailLayoutMode": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "PDFThumbnailLayoutMode"
        }
      ],
      "identifier": "doc://com.apple.pdfkit/documentation/PDFKit/PDFThumbnailLayoutMode",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PDFThumbnailLayoutMode"
        }
      ],
      "role": "symbol",
      "title": "PDFThumbnailLayoutMode",
      "type": "topic",
      "url": "/documentation/pdfkit/pdfthumbnaillayoutmode"
    },
    "doc://com.apple.pdfkit/documentation/PDFKit/constants": {
      "abstract": [],
      "identifier": "doc://com.apple.pdfkit/documentation/PDFKit/constants",
      "kind": "article",
      "role": "collectionGroup",
      "title": "PDFKit Constants",
      "type": "topic",
      "url": "/documentation/pdfkit/constants"
    },
    "doc://com.apple.pdfkit/documentation/PDFKit/data-types": {
      "abstract": [],
      "identifier": "doc://com.apple.pdfkit/documentation/PDFKit/data-types",
      "kind": "article",
      "role": "collectionGroup",
      "title": "PDFKit Data Types",
      "type": "topic",
      "url": "/documentation/pdfkit/data-types"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Reference",
      "generated": true,
      "identifiers": [
        "doc://com.apple.pdfkit/documentation/PDFKit/constants",
        "doc://com.apple.pdfkit/documentation/PDFKit/data-types"
      ],
      "title": "Reference"
    }
  ],
  "topicSections": [
    {
      "anchor": "Enumerations",
      "identifiers": [
        "doc://com.apple.pdfkit/documentation/PDFKit/PDFAccessPermissions",
        "doc://com.apple.pdfkit/documentation/PDFKit/PDFSelectionGranularity",
        "doc://com.apple.pdfkit/documentation/PDFKit/PDFThumbnailLayoutMode"
      ],
      "title": "Enumerations"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Enumerations",
              "identifiers": [
                "doc://com.apple.pdfkit/documentation/PDFKit/PDFAccessPermissions",
                "doc://com.apple.pdfkit/documentation/PDFKit/PDFSelectionGranularity",
                "doc://com.apple.pdfkit/documentation/PDFKit/PDFThumbnailLayoutMode"
              ],
              "title": "Enumerations"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Reference",
              "generated": true,
              "identifiers": [
                "doc://com.apple.pdfkit/documentation/PDFKit/constants",
                "doc://com.apple.pdfkit/documentation/PDFKit/data-types"
              ],
              "title": "Reference"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFAccessPermissions/title",
          "value": "PDFAccessPermissions"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFAccessPermissions/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PDFAccessPermissions"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFAccessPermissions/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "PDFAccessPermissions"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFSelectionGranularity/title",
          "value": "PDFSelectionGranularity"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFSelectionGranularity/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PDFSelectionGranularity"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFSelectionGranularity/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "PDFSelectionGranularity"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFThumbnailLayoutMode/title",
          "value": "PDFThumbnailLayoutMode"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFThumbnailLayoutMode/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PDFThumbnailLayoutMode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFThumbnailLayoutMode/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "PDFThumbnailLayoutMode"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/pdfkit/enumerations"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/pdfkit/enumerations"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
