{
  "abstract": [
    {
      "text": "Operations to define the background color, antialiasing, and greeking for a PDF view.",
      "type": "text"
    }
  ],
  "diffAvailability": {
    "major": {
      "change": "modified",
      "platform": "Xcode",
      "versions": [
        "16.0",
        "16.3 beta 2"
      ]
    }
  },
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.pdfkit/documentation/PDFKit",
        "doc://com.apple.pdfkit/documentation/PDFKit/PDFView",
        "doc://com.apple.pdfkit/documentation/PDFKit/configurations"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.pdfkit/documentation/PDFKit/graphics-properties"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "PDFKit"
      }
    ],
    "role": "collectionGroup",
    "roleHeading": "API Collection",
    "title": "Graphics Properties"
  },
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.pdfkit/documentation/PDFKit": {
      "abstract": [
        {
          "text": "Display and manipulate PDF documents in your apps.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.pdfkit/documentation/PDFKit",
      "kind": "symbol",
      "role": "collection",
      "title": "PDFKit",
      "type": "topic",
      "url": "/documentation/pdfkit"
    },
    "doc://com.apple.pdfkit/documentation/PDFKit/PDFDisplayMode": {
      "abstract": [
        {
          "text": "A wrapper for the chosen display mode constant.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "PDFDisplayMode"
        }
      ],
      "identifier": "doc://com.apple.pdfkit/documentation/PDFKit/PDFDisplayMode",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PDFDisplayMode"
        }
      ],
      "role": "symbol",
      "title": "PDFDisplayMode",
      "type": "topic",
      "url": "/documentation/pdfkit/pdfdisplaymode"
    },
    "doc://com.apple.pdfkit/documentation/PDFKit/PDFInterpolationQuality": {
      "abstract": [
        {
          "text": "A wrapper for the specified interpolation quality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "PDFInterpolationQuality"
        }
      ],
      "identifier": "doc://com.apple.pdfkit/documentation/PDFKit/PDFInterpolationQuality",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PDFInterpolationQuality"
        }
      ],
      "role": "symbol",
      "title": "PDFInterpolationQuality",
      "type": "topic",
      "url": "/documentation/pdfkit/pdfinterpolationquality"
    },
    "doc://com.apple.pdfkit/documentation/PDFKit/PDFView": {
      "abstract": [
        {
          "text": "An object that encapsulates the functionality of PDF Kit into a single widget that you can add to your application using Interface Builder.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "PDFView"
        }
      ],
      "identifier": "doc://com.apple.pdfkit/documentation/PDFKit/PDFView",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PDFView"
        }
      ],
      "role": "symbol",
      "title": "PDFView",
      "type": "topic",
      "url": "/documentation/pdfkit/pdfview"
    },
    "doc://com.apple.pdfkit/documentation/PDFKit/PDFView/backgroundColor": {
      "abstract": [
        {
          "text": "The view’s background color.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "backgroundColor"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UIColor",
          "text": "UIColor"
        }
      ],
      "identifier": "doc://com.apple.pdfkit/documentation/PDFKit/PDFView/backgroundColor",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "backgroundColor"
        }
      ],
      "role": "symbol",
      "title": "backgroundColor",
      "type": "topic",
      "url": "/documentation/pdfkit/pdfview/backgroundcolor"
    },
    "doc://com.apple.pdfkit/documentation/PDFKit/PDFView/displayMode": {
      "abstract": [
        {
          "text": "The current display mode.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "displayMode"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@PDFDisplayMode",
          "text": "PDFDisplayMode"
        }
      ],
      "identifier": "doc://com.apple.pdfkit/documentation/PDFKit/PDFView/displayMode",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "displayMode"
        }
      ],
      "role": "symbol",
      "title": "displayMode",
      "type": "topic",
      "url": "/documentation/pdfkit/pdfview/displaymode"
    },
    "doc://com.apple.pdfkit/documentation/PDFKit/PDFView/greekingThreshold": {
      "abstract": [
        {
          "text": "Returns the current greeking threshold for the view.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "greekingThreshold"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:14CoreFoundation7CGFloatV",
          "text": "CGFloat"
        }
      ],
      "identifier": "doc://com.apple.pdfkit/documentation/PDFKit/PDFView/greekingThreshold",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "greekingThreshold"
        }
      ],
      "role": "symbol",
      "title": "greekingThreshold",
      "type": "topic",
      "url": "/documentation/pdfkit/pdfview/greekingthreshold"
    },
    "doc://com.apple.pdfkit/documentation/PDFKit/PDFView/interpolationQuality": {
      "abstract": [
        {
          "text": "The interpolation quality for images drawn into the ",
          "type": "text"
        },
        {
          "code": "PDFView",
          "type": "codeVoice"
        },
        {
          "text": " context.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "interpolationQuality"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@PDFInterpolationQuality",
          "text": "PDFInterpolationQuality"
        }
      ],
      "identifier": "doc://com.apple.pdfkit/documentation/PDFKit/PDFView/interpolationQuality",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "interpolationQuality"
        }
      ],
      "role": "symbol",
      "title": "interpolationQuality",
      "type": "topic",
      "url": "/documentation/pdfkit/pdfview/interpolationquality"
    },
    "doc://com.apple.pdfkit/documentation/PDFKit/PDFView/shouldAntiAlias": {
      "abstract": [
        {
          "text": "A Boolean value indicating whether the view is antialiased.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "shouldAntiAlias"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.pdfkit/documentation/PDFKit/PDFView/shouldAntiAlias",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "shouldAntiAlias"
        }
      ],
      "role": "symbol",
      "title": "shouldAntiAlias",
      "type": "topic",
      "url": "/documentation/pdfkit/pdfview/shouldantialias"
    },
    "doc://com.apple.pdfkit/documentation/PDFKit/PDFView/takeBackgroundColorFrom(_:)": {
      "abstract": [
        {
          "text": "Sets the view’s background color to the specified color.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "takeBackgroundColorFrom"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "keyword",
          "text": "Any"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.pdfkit/documentation/PDFKit/PDFView/takeBackgroundColorFrom(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "takeBackgroundColorFrom:"
        }
      ],
      "role": "symbol",
      "title": "takeBackgroundColorFrom(_:)",
      "type": "topic",
      "url": "/documentation/pdfkit/pdfview/takebackgroundcolorfrom(_:)"
    },
    "doc://com.apple.pdfkit/documentation/PDFKit/additional-display-configurations": {
      "abstract": [
        {
          "text": "Operations for setting up page breaks, a display box, and display direction.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.pdfkit/documentation/PDFKit/additional-display-configurations",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Additional Display Configurations",
      "type": "topic",
      "url": "/documentation/pdfkit/additional-display-configurations"
    },
    "doc://com.apple.pdfkit/documentation/PDFKit/book-display": {
      "abstract": [
        {
          "text": "Operations to setup a book display for a PDF view.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.pdfkit/documentation/PDFKit/book-display",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Book Display",
      "type": "topic",
      "url": "/documentation/pdfkit/book-display"
    },
    "doc://com.apple.pdfkit/documentation/PDFKit/configurations": {
      "abstract": [
        {
          "text": "Define display modes, scaling, rendering, printing and graphics properties.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.pdfkit/documentation/PDFKit/configurations",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Configurations",
      "type": "topic",
      "url": "/documentation/pdfkit/configurations"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Working-with-Display-Modes-and-Characteristics",
      "generated": true,
      "identifiers": [
        "doc://com.apple.pdfkit/documentation/PDFKit/PDFView/displayMode",
        "doc://com.apple.pdfkit/documentation/PDFKit/PDFDisplayMode",
        "doc://com.apple.pdfkit/documentation/PDFKit/additional-display-configurations",
        "doc://com.apple.pdfkit/documentation/PDFKit/book-display"
      ],
      "title": "Working with Display Modes and Characteristics"
    }
  ],
  "topicSections": [
    {
      "anchor": "Setting-Background-Color",
      "identifiers": [
        "doc://com.apple.pdfkit/documentation/PDFKit/PDFView/takeBackgroundColorFrom(_:)",
        "doc://com.apple.pdfkit/documentation/PDFKit/PDFView/backgroundColor"
      ],
      "title": "Setting Background Color"
    },
    {
      "anchor": "Antialiasing",
      "identifiers": [
        "doc://com.apple.pdfkit/documentation/PDFKit/PDFView/shouldAntiAlias",
        "doc://com.apple.pdfkit/documentation/PDFKit/PDFView/interpolationQuality",
        "doc://com.apple.pdfkit/documentation/PDFKit/PDFInterpolationQuality"
      ],
      "title": "Antialiasing"
    },
    {
      "anchor": "Greeking",
      "identifiers": [
        "doc://com.apple.pdfkit/documentation/PDFKit/PDFView/greekingThreshold"
      ],
      "title": "Greeking"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Setting-Background-Color",
              "identifiers": [
                "doc://com.apple.pdfkit/documentation/PDFKit/PDFView/takeBackgroundColorFrom(_:)",
                "doc://com.apple.pdfkit/documentation/PDFKit/PDFView/backgroundColor"
              ],
              "title": "Setting Background Color"
            },
            {
              "anchor": "Antialiasing",
              "identifiers": [
                "doc://com.apple.pdfkit/documentation/PDFKit/PDFView/shouldAntiAlias",
                "doc://com.apple.pdfkit/documentation/PDFKit/PDFView/interpolationQuality",
                "doc://com.apple.pdfkit/documentation/PDFKit/PDFInterpolationQuality"
              ],
              "title": "Antialiasing"
            },
            {
              "anchor": "Greeking",
              "identifiers": [
                "doc://com.apple.pdfkit/documentation/PDFKit/PDFView/greekingThreshold"
              ],
              "title": "Greeking"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Working-with-Display-Modes-and-Characteristics",
              "generated": true,
              "identifiers": [
                "doc://com.apple.pdfkit/documentation/PDFKit/PDFView/displayMode",
                "doc://com.apple.pdfkit/documentation/PDFKit/PDFDisplayMode",
                "doc://com.apple.pdfkit/documentation/PDFKit/additional-display-configurations",
                "doc://com.apple.pdfkit/documentation/PDFKit/book-display"
              ],
              "title": "Working with Display Modes and Characteristics"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFView~1takeBackgroundColorFrom(_:)/title",
          "value": "takeBackgroundColorFrom:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFView~1takeBackgroundColorFrom(_:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "takeBackgroundColorFrom:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFView~1interpolationQuality/title",
          "value": "interpolationQuality"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFView~1interpolationQuality/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "interpolationQuality"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFView~1shouldAntiAlias/title",
          "value": "shouldAntiAlias"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFView~1shouldAntiAlias/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "shouldAntiAlias"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFDisplayMode/title",
          "value": "PDFDisplayMode"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFDisplayMode/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PDFDisplayMode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFDisplayMode/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "PDFDisplayMode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFView~1greekingThreshold/title",
          "value": "greekingThreshold"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFView~1greekingThreshold/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "greekingThreshold"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFView~1displayMode/title",
          "value": "displayMode"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFView~1displayMode/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "displayMode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFView/title",
          "value": "PDFView"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFView/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PDFView"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFView/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "PDFView"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFInterpolationQuality/title",
          "value": "PDFInterpolationQuality"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFInterpolationQuality/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PDFInterpolationQuality"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFInterpolationQuality/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "PDFInterpolationQuality"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFView~1backgroundColor/title",
          "value": "backgroundColor"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFView~1backgroundColor/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "backgroundColor"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/pdfkit/graphics-properties"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/pdfkit/graphics-properties"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
