{
  "deprecationSummary": [
    {
      "inlineContent": [
        {
          "text": "Use ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.pdfkit/documentation/PDFKit/PDFAnnotationKey",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " constant instead.",
          "type": "text"
        }
      ],
      "type": "paragraph"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.pdfkit/documentation/PDFKit"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "occ",
    "url": "doc://com.apple.pdfkit/documentation/PDFKit/kPDFAnnotationKey_LinePoints"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@kPDFAnnotationKey_LinePoints",
    "fragments": [
      {
        "kind": "identifier",
        "text": "kPDFAnnotationKey_LinePoints"
      }
    ],
    "modules": [
      {
        "name": "PDFKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "kPDFAnnotationKey_LinePoints"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "10.13",
        "introducedAt": "10.12",
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Global Variable",
    "symbolKind": "var",
    "title": "kPDFAnnotationKey_LinePoints"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "occ"
          ],
          "platforms": [
            "macOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "extern"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "identifier": "doc://com.apple.pdfkit/documentation/PDFKit/PDFAnnotationKey",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@PDFAnnotationKey",
              "text": "PDFAnnotationKey"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "kPDFAnnotationKey_LinePoints"
            },
            {
              "kind": "text",
              "text": ";"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.pdfkit/documentation/PDFKit": {
      "abstract": [
        {
          "text": "Display and manipulate PDF documents in your apps.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.pdfkit/documentation/PDFKit",
      "kind": "symbol",
      "role": "collection",
      "title": "PDFKit",
      "type": "topic",
      "url": "/documentation/pdfkit"
    },
    "doc://com.apple.pdfkit/documentation/PDFKit/PDFAnnotationKey": {
      "abstract": [
        {
          "text": "Keys for setting properties of annotations.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "PDFAnnotationKey"
        }
      ],
      "identifier": "doc://com.apple.pdfkit/documentation/PDFKit/PDFAnnotationKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PDFAnnotationKey"
        }
      ],
      "role": "symbol",
      "title": "PDFAnnotationKey",
      "type": "topic",
      "url": "/documentation/pdfkit/pdfannotationkey"
    },
    "doc://com.apple.pdfkit/documentation/PDFKit/kPDFAnnotationKey_Action": {
      "abstract": [],
      "deprecated": true,
      "fragments": [
        {
          "kind": "identifier",
          "text": "kPDFAnnotationKey_Action"
        }
      ],
      "identifier": "doc://com.apple.pdfkit/documentation/PDFKit/kPDFAnnotationKey_Action",
      "kind": "symbol",
      "role": "symbol",
      "title": "kPDFAnnotationKey_Action",
      "type": "topic",
      "url": "/documentation/pdfkit/kpdfannotationkey_action"
    },
    "doc://com.apple.pdfkit/documentation/PDFKit/kPDFAnnotationKey_AdditionalActions": {
      "abstract": [],
      "deprecated": true,
      "fragments": [
        {
          "kind": "identifier",
          "text": "kPDFAnnotationKey_AdditionalActions"
        }
      ],
      "identifier": "doc://com.apple.pdfkit/documentation/PDFKit/kPDFAnnotationKey_AdditionalActions",
      "kind": "symbol",
      "role": "symbol",
      "title": "kPDFAnnotationKey_AdditionalActions",
      "type": "topic",
      "url": "/documentation/pdfkit/kpdfannotationkey_additionalactions"
    },
    "doc://com.apple.pdfkit/documentation/PDFKit/kPDFAnnotationKey_AppearanceDictionary": {
      "abstract": [],
      "deprecated": true,
      "fragments": [
        {
          "kind": "identifier",
          "text": "kPDFAnnotationKey_AppearanceDictionary"
        }
      ],
      "identifier": "doc://com.apple.pdfkit/documentation/PDFKit/kPDFAnnotationKey_AppearanceDictionary",
      "kind": "symbol",
      "role": "symbol",
      "title": "kPDFAnnotationKey_AppearanceDictionary",
      "type": "topic",
      "url": "/documentation/pdfkit/kpdfannotationkey_appearancedictionary"
    },
    "doc://com.apple.pdfkit/documentation/PDFKit/kPDFAnnotationKey_AppearanceState": {
      "abstract": [],
      "deprecated": true,
      "fragments": [
        {
          "kind": "identifier",
          "text": "kPDFAnnotationKey_AppearanceState"
        }
      ],
      "identifier": "doc://com.apple.pdfkit/documentation/PDFKit/kPDFAnnotationKey_AppearanceState",
      "kind": "symbol",
      "role": "symbol",
      "title": "kPDFAnnotationKey_AppearanceState",
      "type": "topic",
      "url": "/documentation/pdfkit/kpdfannotationkey_appearancestate"
    },
    "doc://com.apple.pdfkit/documentation/PDFKit/kPDFAnnotationKey_Border": {
      "abstract": [],
      "deprecated": true,
      "fragments": [
        {
          "kind": "identifier",
          "text": "kPDFAnnotationKey_Border"
        }
      ],
      "identifier": "doc://com.apple.pdfkit/documentation/PDFKit/kPDFAnnotationKey_Border",
      "kind": "symbol",
      "role": "symbol",
      "title": "kPDFAnnotationKey_Border",
      "type": "topic",
      "url": "/documentation/pdfkit/kpdfannotationkey_border"
    },
    "doc://com.apple.pdfkit/documentation/PDFKit/kPDFAnnotationKey_BorderStyle": {
      "abstract": [],
      "deprecated": true,
      "fragments": [
        {
          "kind": "identifier",
          "text": "kPDFAnnotationKey_BorderStyle"
        }
      ],
      "identifier": "doc://com.apple.pdfkit/documentation/PDFKit/kPDFAnnotationKey_BorderStyle",
      "kind": "symbol",
      "role": "symbol",
      "title": "kPDFAnnotationKey_BorderStyle",
      "type": "topic",
      "url": "/documentation/pdfkit/kpdfannotationkey_borderstyle"
    },
    "doc://com.apple.pdfkit/documentation/PDFKit/kPDFAnnotationKey_Color": {
      "abstract": [],
      "deprecated": true,
      "fragments": [
        {
          "kind": "identifier",
          "text": "kPDFAnnotationKey_Color"
        }
      ],
      "identifier": "doc://com.apple.pdfkit/documentation/PDFKit/kPDFAnnotationKey_Color",
      "kind": "symbol",
      "role": "symbol",
      "title": "kPDFAnnotationKey_Color",
      "type": "topic",
      "url": "/documentation/pdfkit/kpdfannotationkey_color"
    },
    "doc://com.apple.pdfkit/documentation/PDFKit/kPDFAnnotationKey_Contents": {
      "abstract": [],
      "deprecated": true,
      "fragments": [
        {
          "kind": "identifier",
          "text": "kPDFAnnotationKey_Contents"
        }
      ],
      "identifier": "doc://com.apple.pdfkit/documentation/PDFKit/kPDFAnnotationKey_Contents",
      "kind": "symbol",
      "role": "symbol",
      "title": "kPDFAnnotationKey_Contents",
      "type": "topic",
      "url": "/documentation/pdfkit/kpdfannotationkey_contents"
    },
    "doc://com.apple.pdfkit/documentation/PDFKit/kPDFAnnotationKey_Date": {
      "abstract": [],
      "deprecated": true,
      "fragments": [
        {
          "kind": "identifier",
          "text": "kPDFAnnotationKey_Date"
        }
      ],
      "identifier": "doc://com.apple.pdfkit/documentation/PDFKit/kPDFAnnotationKey_Date",
      "kind": "symbol",
      "role": "symbol",
      "title": "kPDFAnnotationKey_Date",
      "type": "topic",
      "url": "/documentation/pdfkit/kpdfannotationkey_date"
    },
    "doc://com.apple.pdfkit/documentation/PDFKit/kPDFAnnotationKey_DefaultAppearance": {
      "abstract": [],
      "deprecated": true,
      "fragments": [
        {
          "kind": "identifier",
          "text": "kPDFAnnotationKey_DefaultAppearance"
        }
      ],
      "identifier": "doc://com.apple.pdfkit/documentation/PDFKit/kPDFAnnotationKey_DefaultAppearance",
      "kind": "symbol",
      "role": "symbol",
      "title": "kPDFAnnotationKey_DefaultAppearance",
      "type": "topic",
      "url": "/documentation/pdfkit/kpdfannotationkey_defaultappearance"
    },
    "doc://com.apple.pdfkit/documentation/PDFKit/kPDFAnnotationKey_Destination": {
      "abstract": [],
      "deprecated": true,
      "fragments": [
        {
          "kind": "identifier",
          "text": "kPDFAnnotationKey_Destination"
        }
      ],
      "identifier": "doc://com.apple.pdfkit/documentation/PDFKit/kPDFAnnotationKey_Destination",
      "kind": "symbol",
      "role": "symbol",
      "title": "kPDFAnnotationKey_Destination",
      "type": "topic",
      "url": "/documentation/pdfkit/kpdfannotationkey_destination"
    },
    "doc://com.apple.pdfkit/documentation/PDFKit/kPDFAnnotationKey_Flags": {
      "abstract": [],
      "deprecated": true,
      "fragments": [
        {
          "kind": "identifier",
          "text": "kPDFAnnotationKey_Flags"
        }
      ],
      "identifier": "doc://com.apple.pdfkit/documentation/PDFKit/kPDFAnnotationKey_Flags",
      "kind": "symbol",
      "role": "symbol",
      "title": "kPDFAnnotationKey_Flags",
      "type": "topic",
      "url": "/documentation/pdfkit/kpdfannotationkey_flags"
    },
    "doc://com.apple.pdfkit/documentation/PDFKit/kPDFAnnotationKey_HighlightingMode": {
      "abstract": [],
      "deprecated": true,
      "fragments": [
        {
          "kind": "identifier",
          "text": "kPDFAnnotationKey_HighlightingMode"
        }
      ],
      "identifier": "doc://com.apple.pdfkit/documentation/PDFKit/kPDFAnnotationKey_HighlightingMode",
      "kind": "symbol",
      "role": "symbol",
      "title": "kPDFAnnotationKey_HighlightingMode",
      "type": "topic",
      "url": "/documentation/pdfkit/kpdfannotationkey_highlightingmode"
    },
    "doc://com.apple.pdfkit/documentation/PDFKit/kPDFAnnotationKey_IconName": {
      "abstract": [],
      "deprecated": true,
      "fragments": [
        {
          "kind": "identifier",
          "text": "kPDFAnnotationKey_IconName"
        }
      ],
      "identifier": "doc://com.apple.pdfkit/documentation/PDFKit/kPDFAnnotationKey_IconName",
      "kind": "symbol",
      "role": "symbol",
      "title": "kPDFAnnotationKey_IconName",
      "type": "topic",
      "url": "/documentation/pdfkit/kpdfannotationkey_iconname"
    },
    "doc://com.apple.pdfkit/documentation/PDFKit/kPDFAnnotationKey_Inklist": {
      "abstract": [],
      "deprecated": true,
      "fragments": [
        {
          "kind": "identifier",
          "text": "kPDFAnnotationKey_Inklist"
        }
      ],
      "identifier": "doc://com.apple.pdfkit/documentation/PDFKit/kPDFAnnotationKey_Inklist",
      "kind": "symbol",
      "role": "symbol",
      "title": "kPDFAnnotationKey_Inklist",
      "type": "topic",
      "url": "/documentation/pdfkit/kpdfannotationkey_inklist"
    },
    "doc://com.apple.pdfkit/documentation/PDFKit/kPDFAnnotationKey_LinePoints": {
      "abstract": [],
      "deprecated": true,
      "fragments": [
        {
          "kind": "identifier",
          "text": "kPDFAnnotationKey_LinePoints"
        }
      ],
      "identifier": "doc://com.apple.pdfkit/documentation/PDFKit/kPDFAnnotationKey_LinePoints",
      "kind": "symbol",
      "role": "symbol",
      "title": "kPDFAnnotationKey_LinePoints",
      "type": "topic",
      "url": "/documentation/pdfkit/kpdfannotationkey_linepoints"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Deprecated-Annotation-Keys",
      "generated": true,
      "identifiers": [
        "doc://com.apple.pdfkit/documentation/PDFKit/kPDFAnnotationKey_Action",
        "doc://com.apple.pdfkit/documentation/PDFKit/kPDFAnnotationKey_AdditionalActions",
        "doc://com.apple.pdfkit/documentation/PDFKit/kPDFAnnotationKey_AppearanceDictionary",
        "doc://com.apple.pdfkit/documentation/PDFKit/kPDFAnnotationKey_AppearanceState",
        "doc://com.apple.pdfkit/documentation/PDFKit/kPDFAnnotationKey_Border",
        "doc://com.apple.pdfkit/documentation/PDFKit/kPDFAnnotationKey_BorderStyle",
        "doc://com.apple.pdfkit/documentation/PDFKit/kPDFAnnotationKey_Color",
        "doc://com.apple.pdfkit/documentation/PDFKit/kPDFAnnotationKey_Contents",
        "doc://com.apple.pdfkit/documentation/PDFKit/kPDFAnnotationKey_Date",
        "doc://com.apple.pdfkit/documentation/PDFKit/kPDFAnnotationKey_DefaultAppearance",
        "doc://com.apple.pdfkit/documentation/PDFKit/kPDFAnnotationKey_Destination",
        "doc://com.apple.pdfkit/documentation/PDFKit/kPDFAnnotationKey_Flags",
        "doc://com.apple.pdfkit/documentation/PDFKit/kPDFAnnotationKey_HighlightingMode",
        "doc://com.apple.pdfkit/documentation/PDFKit/kPDFAnnotationKey_IconName",
        "doc://com.apple.pdfkit/documentation/PDFKit/kPDFAnnotationKey_Inklist"
      ],
      "title": "Deprecated Annotation Keys"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFAnnotationKey/title",
          "value": "PDFAnnotationKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFAnnotationKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PDFAnnotationKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFAnnotationKey/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "PDFAnnotationKey"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/pdfkit/kpdfannotationkey_linepoints"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
