{
  "abstract": [
    {
      "text": "Operations for moving through page history and seeking to a page in a document.",
      "type": "text"
    }
  ],
  "diffAvailability": {
    "major": {
      "change": "modified",
      "platform": "Xcode",
      "versions": [
        "16.0",
        "16.3 beta 2"
      ]
    }
  },
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.pdfkit/documentation/PDFKit",
        "doc://com.apple.pdfkit/documentation/PDFKit/PDFView"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.pdfkit/documentation/PDFKit/navigation"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "PDFKit"
      }
    ],
    "role": "collectionGroup",
    "roleHeading": "API Collection",
    "title": "Navigation"
  },
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.pdfkit/documentation/PDFKit": {
      "abstract": [
        {
          "text": "Display and manipulate PDF documents in your apps.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.pdfkit/documentation/PDFKit",
      "kind": "symbol",
      "role": "collection",
      "title": "PDFKit",
      "type": "topic",
      "url": "/documentation/pdfkit"
    },
    "doc://com.apple.pdfkit/documentation/PDFKit/PDFView": {
      "abstract": [
        {
          "text": "An object that encapsulates the functionality of PDF Kit into a single widget that you can add to your application using Interface Builder.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "PDFView"
        }
      ],
      "identifier": "doc://com.apple.pdfkit/documentation/PDFKit/PDFView",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PDFView"
        }
      ],
      "role": "symbol",
      "title": "PDFView",
      "type": "topic",
      "url": "/documentation/pdfkit/pdfview"
    },
    "doc://com.apple.pdfkit/documentation/PDFKit/PDFView/canGoBack": {
      "abstract": [
        {
          "text": "Returns a Boolean value indicating whether the user can navigate to the previous page in the page history.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "canGoBack"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.pdfkit/documentation/PDFKit/PDFView/canGoBack",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "canGoBack"
        }
      ],
      "role": "symbol",
      "title": "canGoBack",
      "type": "topic",
      "url": "/documentation/pdfkit/pdfview/cangoback"
    },
    "doc://com.apple.pdfkit/documentation/PDFKit/PDFView/canGoForward": {
      "abstract": [
        {
          "text": "Returns a Boolean value indicating whether the user can navigate to the next page in the page history.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "canGoForward"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.pdfkit/documentation/PDFKit/PDFView/canGoForward",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "canGoForward"
        }
      ],
      "role": "symbol",
      "title": "canGoForward",
      "type": "topic",
      "url": "/documentation/pdfkit/pdfview/cangoforward"
    },
    "doc://com.apple.pdfkit/documentation/PDFKit/PDFView/canGoToFirstPage": {
      "abstract": [
        {
          "text": "Returns a Boolean value indicating whether the user can navigate to the first page of the document.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "canGoToFirstPage"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.pdfkit/documentation/PDFKit/PDFView/canGoToFirstPage",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "canGoToFirstPage"
        }
      ],
      "role": "symbol",
      "title": "canGoToFirstPage",
      "type": "topic",
      "url": "/documentation/pdfkit/pdfview/cangotofirstpage"
    },
    "doc://com.apple.pdfkit/documentation/PDFKit/PDFView/canGoToLastPage": {
      "abstract": [
        {
          "text": "Returns a Boolean value indicating whether the user can navigate to the last page of the document.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "canGoToLastPage"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.pdfkit/documentation/PDFKit/PDFView/canGoToLastPage",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "canGoToLastPage"
        }
      ],
      "role": "symbol",
      "title": "canGoToLastPage",
      "type": "topic",
      "url": "/documentation/pdfkit/pdfview/cangotolastpage"
    },
    "doc://com.apple.pdfkit/documentation/PDFKit/PDFView/canGoToNextPage": {
      "abstract": [
        {
          "text": "Returns a Boolean value indicating whether the user can navigate to the next page of the document.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "canGoToNextPage"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.pdfkit/documentation/PDFKit/PDFView/canGoToNextPage",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "canGoToNextPage"
        }
      ],
      "role": "symbol",
      "title": "canGoToNextPage",
      "type": "topic",
      "url": "/documentation/pdfkit/pdfview/cangotonextpage"
    },
    "doc://com.apple.pdfkit/documentation/PDFKit/PDFView/canGoToPreviousPage": {
      "abstract": [
        {
          "text": "Returns a Boolean value indicating whether the user can navigate to the previous page of the document.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "canGoToPreviousPage"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.pdfkit/documentation/PDFKit/PDFView/canGoToPreviousPage",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "canGoToPreviousPage"
        }
      ],
      "role": "symbol",
      "title": "canGoToPreviousPage",
      "type": "topic",
      "url": "/documentation/pdfkit/pdfview/cangotopreviouspage"
    },
    "doc://com.apple.pdfkit/documentation/PDFKit/PDFView/currentDestination": {
      "abstract": [
        {
          "text": "Returns a ",
          "type": "text"
        },
        {
          "code": "PDFDestination",
          "type": "codeVoice"
        },
        {
          "text": " object representing the current page and the current point in the view specified in page space.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "currentDestination"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)PDFDestination",
          "text": "PDFDestination"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.pdfkit/documentation/PDFKit/PDFView/currentDestination",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "currentDestination"
        }
      ],
      "role": "symbol",
      "title": "currentDestination",
      "type": "topic",
      "url": "/documentation/pdfkit/pdfview/currentdestination"
    },
    "doc://com.apple.pdfkit/documentation/PDFKit/PDFView/currentPage": {
      "abstract": [
        {
          "text": "Returns the current page.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "currentPage"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)PDFPage",
          "text": "PDFPage"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.pdfkit/documentation/PDFKit/PDFView/currentPage",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "currentPage"
        }
      ],
      "role": "symbol",
      "title": "currentPage",
      "type": "topic",
      "url": "/documentation/pdfkit/pdfview/currentpage"
    },
    "doc://com.apple.pdfkit/documentation/PDFKit/PDFView/go(to:)-3t5go": {
      "abstract": [
        {
          "text": "Scrolls to the first character of the specified selection.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "go"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "to"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)PDFSelection",
          "text": "PDFSelection"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.pdfkit/documentation/PDFKit/PDFView/go(to:)-3t5go",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "goToSelection:"
        }
      ],
      "role": "symbol",
      "title": "go(to:)",
      "type": "topic",
      "url": "/documentation/pdfkit/pdfview/go(to:)-3t5go"
    },
    "doc://com.apple.pdfkit/documentation/PDFKit/PDFView/go(to:)-5lh5d": {
      "abstract": [
        {
          "text": "Navigates to the specified destination.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "go"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "to"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)PDFDestination",
          "text": "PDFDestination"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.pdfkit/documentation/PDFKit/PDFView/go(to:)-5lh5d",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "goToDestination:"
        }
      ],
      "role": "symbol",
      "title": "go(to:)",
      "type": "topic",
      "url": "/documentation/pdfkit/pdfview/go(to:)-5lh5d"
    },
    "doc://com.apple.pdfkit/documentation/PDFKit/PDFView/go(to:)-6x8y2": {
      "abstract": [
        {
          "text": "Scrolls to the specified page.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "go"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "to"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)PDFPage",
          "text": "PDFPage"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.pdfkit/documentation/PDFKit/PDFView/go(to:)-6x8y2",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "goToPage:"
        }
      ],
      "role": "symbol",
      "title": "go(to:)",
      "type": "topic",
      "url": "/documentation/pdfkit/pdfview/go(to:)-6x8y2"
    },
    "doc://com.apple.pdfkit/documentation/PDFKit/PDFView/go(to:on:)": {
      "abstract": [
        {
          "text": "Navigates to the specified rectangle on the specified page.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "go"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "to"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@CGRect",
          "text": "CGRect"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "on"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)PDFPage",
          "text": "PDFPage"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.pdfkit/documentation/PDFKit/PDFView/go(to:on:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "goToRect:onPage:"
        }
      ],
      "role": "symbol",
      "title": "go(to:on:)",
      "type": "topic",
      "url": "/documentation/pdfkit/pdfview/go(to:on:)"
    },
    "doc://com.apple.pdfkit/documentation/PDFKit/PDFView/goBack(_:)": {
      "abstract": [
        {
          "text": "Navigates back one step in the page history.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "goBack"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "keyword",
          "text": "Any"
        },
        {
          "kind": "text",
          "text": "?)"
        }
      ],
      "identifier": "doc://com.apple.pdfkit/documentation/PDFKit/PDFView/goBack(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "goBack:"
        }
      ],
      "role": "symbol",
      "title": "goBack(_:)",
      "type": "topic",
      "url": "/documentation/pdfkit/pdfview/goback(_:)"
    },
    "doc://com.apple.pdfkit/documentation/PDFKit/PDFView/goForward(_:)": {
      "abstract": [
        {
          "text": "Navigates forward one step in the page history.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "goForward"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "keyword",
          "text": "Any"
        },
        {
          "kind": "text",
          "text": "?)"
        }
      ],
      "identifier": "doc://com.apple.pdfkit/documentation/PDFKit/PDFView/goForward(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "goForward:"
        }
      ],
      "role": "symbol",
      "title": "goForward(_:)",
      "type": "topic",
      "url": "/documentation/pdfkit/pdfview/goforward(_:)"
    },
    "doc://com.apple.pdfkit/documentation/PDFKit/PDFView/goToFirstPage(_:)": {
      "abstract": [
        {
          "text": "Navigates to the first page of the document.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "goToFirstPage"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "keyword",
          "text": "Any"
        },
        {
          "kind": "text",
          "text": "?)"
        }
      ],
      "identifier": "doc://com.apple.pdfkit/documentation/PDFKit/PDFView/goToFirstPage(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "goToFirstPage:"
        }
      ],
      "role": "symbol",
      "title": "goToFirstPage(_:)",
      "type": "topic",
      "url": "/documentation/pdfkit/pdfview/gotofirstpage(_:)"
    },
    "doc://com.apple.pdfkit/documentation/PDFKit/PDFView/goToLastPage(_:)": {
      "abstract": [
        {
          "text": "Navigates to the last page of the document.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "goToLastPage"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "keyword",
          "text": "Any"
        },
        {
          "kind": "text",
          "text": "?)"
        }
      ],
      "identifier": "doc://com.apple.pdfkit/documentation/PDFKit/PDFView/goToLastPage(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "goToLastPage:"
        }
      ],
      "role": "symbol",
      "title": "goToLastPage(_:)",
      "type": "topic",
      "url": "/documentation/pdfkit/pdfview/gotolastpage(_:)"
    },
    "doc://com.apple.pdfkit/documentation/PDFKit/PDFView/goToNextPage(_:)": {
      "abstract": [
        {
          "text": "Navigates to the next page of the document.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "goToNextPage"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "keyword",
          "text": "Any"
        },
        {
          "kind": "text",
          "text": "?)"
        }
      ],
      "identifier": "doc://com.apple.pdfkit/documentation/PDFKit/PDFView/goToNextPage(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "goToNextPage:"
        }
      ],
      "role": "symbol",
      "title": "goToNextPage(_:)",
      "type": "topic",
      "url": "/documentation/pdfkit/pdfview/gotonextpage(_:)"
    },
    "doc://com.apple.pdfkit/documentation/PDFKit/PDFView/goToPreviousPage(_:)": {
      "abstract": [
        {
          "text": "Navigates to the previous page of the document.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "goToPreviousPage"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "keyword",
          "text": "Any"
        },
        {
          "kind": "text",
          "text": "?)"
        }
      ],
      "identifier": "doc://com.apple.pdfkit/documentation/PDFKit/PDFView/goToPreviousPage(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "goToPreviousPage:"
        }
      ],
      "role": "symbol",
      "title": "goToPreviousPage(_:)",
      "type": "topic",
      "url": "/documentation/pdfkit/pdfview/gotopreviouspage(_:)"
    },
    "doc://com.apple.pdfkit/documentation/PDFKit/PDFView/visiblePages": {
      "abstract": [
        {
          "text": "Returns an array of ",
          "type": "text"
        },
        {
          "code": "PDFPage",
          "type": "codeVoice"
        },
        {
          "text": " objects that represent the currently visible pages.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "visiblePages"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)PDFPage",
          "text": "PDFPage"
        },
        {
          "kind": "text",
          "text": "]"
        }
      ],
      "identifier": "doc://com.apple.pdfkit/documentation/PDFKit/PDFView/visiblePages",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "visiblePages"
        }
      ],
      "role": "symbol",
      "title": "visiblePages",
      "type": "topic",
      "url": "/documentation/pdfkit/pdfview/visiblepages"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Navigating-Within-a-Document",
      "generated": true,
      "identifiers": [
        "doc://com.apple.pdfkit/documentation/PDFKit/PDFView/currentPage",
        "doc://com.apple.pdfkit/documentation/PDFKit/PDFView/currentDestination",
        "doc://com.apple.pdfkit/documentation/PDFKit/PDFView/visiblePages"
      ],
      "title": "Navigating Within a Document"
    }
  ],
  "topicSections": [
    {
      "anchor": "Determining-Valid-History-Operations",
      "identifiers": [
        "doc://com.apple.pdfkit/documentation/PDFKit/PDFView/canGoBack",
        "doc://com.apple.pdfkit/documentation/PDFKit/PDFView/canGoForward",
        "doc://com.apple.pdfkit/documentation/PDFKit/PDFView/canGoToFirstPage",
        "doc://com.apple.pdfkit/documentation/PDFKit/PDFView/canGoToLastPage",
        "doc://com.apple.pdfkit/documentation/PDFKit/PDFView/canGoToNextPage",
        "doc://com.apple.pdfkit/documentation/PDFKit/PDFView/canGoToPreviousPage"
      ],
      "title": "Determining Valid History Operations"
    },
    {
      "anchor": "Navigating-History-for-a-Document",
      "identifiers": [
        "doc://com.apple.pdfkit/documentation/PDFKit/PDFView/goBack(_:)",
        "doc://com.apple.pdfkit/documentation/PDFKit/PDFView/goForward(_:)",
        "doc://com.apple.pdfkit/documentation/PDFKit/PDFView/goToFirstPage(_:)",
        "doc://com.apple.pdfkit/documentation/PDFKit/PDFView/goToLastPage(_:)",
        "doc://com.apple.pdfkit/documentation/PDFKit/PDFView/goToNextPage(_:)",
        "doc://com.apple.pdfkit/documentation/PDFKit/PDFView/goToPreviousPage(_:)"
      ],
      "title": "Navigating History for a Document"
    },
    {
      "anchor": "Using-Seek-in-a-Document",
      "identifiers": [
        "doc://com.apple.pdfkit/documentation/PDFKit/PDFView/go(to:)-6x8y2",
        "doc://com.apple.pdfkit/documentation/PDFKit/PDFView/go(to:)-5lh5d",
        "doc://com.apple.pdfkit/documentation/PDFKit/PDFView/go(to:)-3t5go",
        "doc://com.apple.pdfkit/documentation/PDFKit/PDFView/go(to:on:)"
      ],
      "title": "Using Seek in a Document"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Determining-Valid-History-Operations",
              "identifiers": [
                "doc://com.apple.pdfkit/documentation/PDFKit/PDFView/canGoBack",
                "doc://com.apple.pdfkit/documentation/PDFKit/PDFView/canGoForward",
                "doc://com.apple.pdfkit/documentation/PDFKit/PDFView/canGoToFirstPage",
                "doc://com.apple.pdfkit/documentation/PDFKit/PDFView/canGoToLastPage",
                "doc://com.apple.pdfkit/documentation/PDFKit/PDFView/canGoToNextPage",
                "doc://com.apple.pdfkit/documentation/PDFKit/PDFView/canGoToPreviousPage"
              ],
              "title": "Determining Valid History Operations"
            },
            {
              "anchor": "Navigating-History-for-a-Document",
              "identifiers": [
                "doc://com.apple.pdfkit/documentation/PDFKit/PDFView/goBack(_:)",
                "doc://com.apple.pdfkit/documentation/PDFKit/PDFView/goForward(_:)",
                "doc://com.apple.pdfkit/documentation/PDFKit/PDFView/goToFirstPage(_:)",
                "doc://com.apple.pdfkit/documentation/PDFKit/PDFView/goToLastPage(_:)",
                "doc://com.apple.pdfkit/documentation/PDFKit/PDFView/goToNextPage(_:)",
                "doc://com.apple.pdfkit/documentation/PDFKit/PDFView/goToPreviousPage(_:)"
              ],
              "title": "Navigating History for a Document"
            },
            {
              "anchor": "Using-Seek-in-a-Document",
              "identifiers": [
                "doc://com.apple.pdfkit/documentation/PDFKit/PDFView/go(to:)-6x8y2",
                "doc://com.apple.pdfkit/documentation/PDFKit/PDFView/go(to:)-5lh5d",
                "doc://com.apple.pdfkit/documentation/PDFKit/PDFView/go(to:)-3t5go",
                "doc://com.apple.pdfkit/documentation/PDFKit/PDFView/go(to:on:)"
              ],
              "title": "Using Seek in a Document"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Navigating-Within-a-Document",
              "generated": true,
              "identifiers": [
                "doc://com.apple.pdfkit/documentation/PDFKit/PDFView/currentPage",
                "doc://com.apple.pdfkit/documentation/PDFKit/PDFView/currentDestination",
                "doc://com.apple.pdfkit/documentation/PDFKit/PDFView/visiblePages"
              ],
              "title": "Navigating Within a Document"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFView~1goToFirstPage(_:)/title",
          "value": "goToFirstPage:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFView~1goToFirstPage(_:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "goToFirstPage:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFView~1go(to:)-5lh5d/title",
          "value": "goToDestination:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFView~1go(to:)-5lh5d/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "goToDestination:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFView~1go(to:)-3t5go/title",
          "value": "goToSelection:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFView~1go(to:)-3t5go/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "goToSelection:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFView~1canGoForward/title",
          "value": "canGoForward"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFView~1canGoForward/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "canGoForward"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFView~1canGoToFirstPage/title",
          "value": "canGoToFirstPage"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFView~1canGoToFirstPage/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "canGoToFirstPage"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFView~1canGoBack/title",
          "value": "canGoBack"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFView~1canGoBack/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "canGoBack"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFView~1goToLastPage(_:)/title",
          "value": "goToLastPage:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFView~1goToLastPage(_:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "goToLastPage:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFView~1currentDestination/title",
          "value": "currentDestination"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFView~1currentDestination/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "currentDestination"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFView~1visiblePages/title",
          "value": "visiblePages"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFView~1visiblePages/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "visiblePages"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFView~1currentPage/title",
          "value": "currentPage"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFView~1currentPage/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "currentPage"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFView~1canGoToPreviousPage/title",
          "value": "canGoToPreviousPage"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFView~1canGoToPreviousPage/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "canGoToPreviousPage"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFView~1go(to:on:)/title",
          "value": "goToRect:onPage:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFView~1go(to:on:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "goToRect:onPage:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFView~1go(to:)-6x8y2/title",
          "value": "goToPage:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFView~1go(to:)-6x8y2/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "goToPage:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFView~1canGoToNextPage/title",
          "value": "canGoToNextPage"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFView~1canGoToNextPage/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "canGoToNextPage"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFView~1canGoToLastPage/title",
          "value": "canGoToLastPage"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFView~1canGoToLastPage/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "canGoToLastPage"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFView~1goToNextPage(_:)/title",
          "value": "goToNextPage:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFView~1goToNextPage(_:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "goToNextPage:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFView~1goToPreviousPage(_:)/title",
          "value": "goToPreviousPage:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFView~1goToPreviousPage(_:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "goToPreviousPage:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFView~1goBack(_:)/title",
          "value": "goBack:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFView~1goBack(_:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "goBack:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFView/title",
          "value": "PDFView"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFView/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PDFView"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFView/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "PDFView"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFView~1goForward(_:)/title",
          "value": "goForward:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFView~1goForward(_:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "goForward:"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/pdfkit/navigation"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/pdfkit/navigation"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
