{
  "abstract": [
    {
      "text": "A ",
      "type": "text"
    },
    {
      "code": "PDFAnnotationLine",
      "type": "codeVoice"
    },
    {
      "text": " object displays a single line on a page.",
      "type": "text"
    }
  ],
  "deprecationSummary": [
    {
      "inlineContent": [
        {
          "text": "Use ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.pdfkit/documentation/PDFKit/PDFAnnotationSubtype",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " instead.",
          "type": "text"
        }
      ],
      "type": "paragraph"
    }
  ],
  "diffAvailability": {
    "major": {
      "change": "modified",
      "platform": "Xcode",
      "versions": [
        "16.0",
        "16.3 beta 2"
      ]
    }
  },
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.pdfkit/documentation/PDFKit"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.pdfkit/documentation/PDFKit/PDFAnnotationLine"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(cs)PDFAnnotationLine",
    "fragments": [
      {
        "kind": "keyword",
        "text": "class"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "PDFAnnotationLine"
      }
    ],
    "modules": [
      {
        "name": "PDFKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "PDFAnnotationLine"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "10.12",
        "introducedAt": "10.4",
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Class",
    "symbolKind": "class",
    "title": "PDFAnnotationLine"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "macOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "class"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "PDFAnnotationLine"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "The ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.pdfkit/documentation/PDFKit/PDFBorder/lineWidth",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " and ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.pdfkit/documentation/PDFKit/PDFBorder/style",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " properties of the annotation’s associated ",
              "type": "text"
            },
            {
              "code": "PDFBorder",
              "type": "codeVoice"
            },
            {
              "text": " object determines the stroke thickness and style. The ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.pdfkit/documentation/PDFKit/PDFAnnotation/color",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " property of the ",
              "type": "text"
            },
            {
              "code": "PDFAnnotation",
              "type": "codeVoice"
            },
            {
              "text": " class determines the stroke color.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.pdfkit/documentation/PDFKit": {
      "abstract": [
        {
          "text": "Display and manipulate PDF documents in your apps.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.pdfkit/documentation/PDFKit",
      "kind": "symbol",
      "role": "collection",
      "title": "PDFKit",
      "type": "topic",
      "url": "/documentation/pdfkit"
    },
    "doc://com.apple.pdfkit/documentation/PDFKit/PDFAnnotation": {
      "abstract": [
        {
          "text": "An annotation in a PDF document.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "PDFAnnotation"
        }
      ],
      "identifier": "doc://com.apple.pdfkit/documentation/PDFKit/PDFAnnotation",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PDFAnnotation"
        }
      ],
      "role": "symbol",
      "title": "PDFAnnotation",
      "type": "topic",
      "url": "/documentation/pdfkit/pdfannotation"
    },
    "doc://com.apple.pdfkit/documentation/PDFKit/PDFAnnotation/color": {
      "abstract": [
        {
          "text": "Sets the stroke color for the annotation.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "color"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UIColor",
          "text": "UIColor"
        }
      ],
      "identifier": "doc://com.apple.pdfkit/documentation/PDFKit/PDFAnnotation/color",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "color"
        }
      ],
      "role": "symbol",
      "title": "color",
      "type": "topic",
      "url": "/documentation/pdfkit/pdfannotation/color"
    },
    "doc://com.apple.pdfkit/documentation/PDFKit/PDFAnnotationButtonWidget": {
      "abstract": [
        {
          "text": "A ",
          "type": "text"
        },
        {
          "code": "PDFAnnotationButtonWidget",
          "type": "codeVoice"
        },
        {
          "text": " object provides user interactivity on a page of a PDF document. There are three types of buttons available: push button, radio button, and checkbox.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "PDFAnnotationButtonWidget"
        }
      ],
      "identifier": "doc://com.apple.pdfkit/documentation/PDFKit/PDFAnnotationButtonWidget",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PDFAnnotationButtonWidget"
        }
      ],
      "role": "symbol",
      "title": "PDFAnnotationButtonWidget",
      "type": "topic",
      "url": "/documentation/pdfkit/pdfannotationbuttonwidget"
    },
    "doc://com.apple.pdfkit/documentation/PDFKit/PDFAnnotationChoiceWidget": {
      "abstract": [
        {
          "text": "A ",
          "type": "text"
        },
        {
          "code": "PDFAnnotationChoiceWidget",
          "type": "codeVoice"
        },
        {
          "text": " object provides user interactivity on a page of a PDF document, in the form of pop-up menus and lists.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "PDFAnnotationChoiceWidget"
        }
      ],
      "identifier": "doc://com.apple.pdfkit/documentation/PDFKit/PDFAnnotationChoiceWidget",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PDFAnnotationChoiceWidget"
        }
      ],
      "role": "symbol",
      "title": "PDFAnnotationChoiceWidget",
      "type": "topic",
      "url": "/documentation/pdfkit/pdfannotationchoicewidget"
    },
    "doc://com.apple.pdfkit/documentation/PDFKit/PDFAnnotationCircle": {
      "abstract": [],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "PDFAnnotationCircle"
        }
      ],
      "identifier": "doc://com.apple.pdfkit/documentation/PDFKit/PDFAnnotationCircle",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PDFAnnotationCircle"
        }
      ],
      "role": "symbol",
      "title": "PDFAnnotationCircle",
      "type": "topic",
      "url": "/documentation/pdfkit/pdfannotationcircle"
    },
    "doc://com.apple.pdfkit/documentation/PDFKit/PDFAnnotationFreeText": {
      "abstract": [
        {
          "text": "A ",
          "type": "text"
        },
        {
          "code": "PDFAnnotationFreeText",
          "type": "codeVoice"
        },
        {
          "text": " object displays text on a page.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "PDFAnnotationFreeText"
        }
      ],
      "identifier": "doc://com.apple.pdfkit/documentation/PDFKit/PDFAnnotationFreeText",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PDFAnnotationFreeText"
        }
      ],
      "role": "symbol",
      "title": "PDFAnnotationFreeText",
      "type": "topic",
      "url": "/documentation/pdfkit/pdfannotationfreetext"
    },
    "doc://com.apple.pdfkit/documentation/PDFKit/PDFAnnotationInk": {
      "abstract": [],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "PDFAnnotationInk"
        }
      ],
      "identifier": "doc://com.apple.pdfkit/documentation/PDFKit/PDFAnnotationInk",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PDFAnnotationInk"
        }
      ],
      "role": "symbol",
      "title": "PDFAnnotationInk",
      "type": "topic",
      "url": "/documentation/pdfkit/pdfannotationink"
    },
    "doc://com.apple.pdfkit/documentation/PDFKit/PDFAnnotationLine": {
      "abstract": [
        {
          "text": "A ",
          "type": "text"
        },
        {
          "code": "PDFAnnotationLine",
          "type": "codeVoice"
        },
        {
          "text": " object displays a single line on a page.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "PDFAnnotationLine"
        }
      ],
      "identifier": "doc://com.apple.pdfkit/documentation/PDFKit/PDFAnnotationLine",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PDFAnnotationLine"
        }
      ],
      "role": "symbol",
      "title": "PDFAnnotationLine",
      "type": "topic",
      "url": "/documentation/pdfkit/pdfannotationline"
    },
    "doc://com.apple.pdfkit/documentation/PDFKit/PDFAnnotationLine/endLineStyle()": {
      "abstract": [
        {
          "text": "Returns the line ending style for the ending point of the line.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "endLineStyle"
        },
        {
          "kind": "text",
          "text": "() -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@PDFLineStyle",
          "text": "PDFLineStyle"
        }
      ],
      "identifier": "doc://com.apple.pdfkit/documentation/PDFKit/PDFAnnotationLine/endLineStyle()",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "endLineStyle"
        }
      ],
      "role": "symbol",
      "title": "endLineStyle()",
      "type": "topic",
      "url": "/documentation/pdfkit/pdfannotationline/endlinestyle()"
    },
    "doc://com.apple.pdfkit/documentation/PDFKit/PDFAnnotationLine/endPoint()": {
      "abstract": [
        {
          "text": "Returns the ending point for the line in page space.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "endPoint"
        },
        {
          "kind": "text",
          "text": "() -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSPoint",
          "text": "NSPoint"
        }
      ],
      "identifier": "doc://com.apple.pdfkit/documentation/PDFKit/PDFAnnotationLine/endPoint()",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "endPoint"
        }
      ],
      "role": "symbol",
      "title": "endPoint()",
      "type": "topic",
      "url": "/documentation/pdfkit/pdfannotationline/endpoint()"
    },
    "doc://com.apple.pdfkit/documentation/PDFKit/PDFAnnotationLine/interiorColor()": {
      "abstract": [
        {
          "text": "Returns the color used to fill the ornament at the ends of the line.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "interiorColor"
        },
        {
          "kind": "text",
          "text": "() -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSColor",
          "text": "NSColor"
        },
        {
          "kind": "text",
          "text": "!"
        }
      ],
      "identifier": "doc://com.apple.pdfkit/documentation/PDFKit/PDFAnnotationLine/interiorColor()",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "interiorColor"
        }
      ],
      "role": "symbol",
      "title": "interiorColor()",
      "type": "topic",
      "url": "/documentation/pdfkit/pdfannotationline/interiorcolor()"
    },
    "doc://com.apple.pdfkit/documentation/PDFKit/PDFAnnotationLine/setEnd(_:)-2qn58": {
      "abstract": [
        {
          "text": "Sets the ending point for the line.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "setEnd"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSPoint",
          "text": "NSPoint"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.pdfkit/documentation/PDFKit/PDFAnnotationLine/setEnd(_:)-2qn58",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "setEndPoint:"
        }
      ],
      "role": "symbol",
      "title": "setEnd(_:)",
      "type": "topic",
      "url": "/documentation/pdfkit/pdfannotationline/setend(_:)-2qn58"
    },
    "doc://com.apple.pdfkit/documentation/PDFKit/PDFAnnotationLine/setEnd(_:)-9cp0t": {
      "abstract": [
        {
          "text": "Sets the line ending style for the ending point of the line.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "setEnd"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@PDFLineStyle",
          "text": "PDFLineStyle"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.pdfkit/documentation/PDFKit/PDFAnnotationLine/setEnd(_:)-9cp0t",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "setEndLineStyle:"
        }
      ],
      "role": "symbol",
      "title": "setEnd(_:)",
      "type": "topic",
      "url": "/documentation/pdfkit/pdfannotationline/setend(_:)-9cp0t"
    },
    "doc://com.apple.pdfkit/documentation/PDFKit/PDFAnnotationLine/setInteriorColor(_:)": {
      "abstract": [
        {
          "text": "Sets the color used to fill the ornament at the ends of the line.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "setInteriorColor"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSColor",
          "text": "NSColor"
        },
        {
          "kind": "text",
          "text": "!)"
        }
      ],
      "identifier": "doc://com.apple.pdfkit/documentation/PDFKit/PDFAnnotationLine/setInteriorColor(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "setInteriorColor:"
        }
      ],
      "role": "symbol",
      "title": "setInteriorColor(_:)",
      "type": "topic",
      "url": "/documentation/pdfkit/pdfannotationline/setinteriorcolor(_:)"
    },
    "doc://com.apple.pdfkit/documentation/PDFKit/PDFAnnotationLine/setStart(_:)-57pe0": {
      "abstract": [
        {
          "text": "Sets the line ending style for the starting point of the line.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "setStart"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@PDFLineStyle",
          "text": "PDFLineStyle"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.pdfkit/documentation/PDFKit/PDFAnnotationLine/setStart(_:)-57pe0",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "setStartLineStyle:"
        }
      ],
      "role": "symbol",
      "title": "setStart(_:)",
      "type": "topic",
      "url": "/documentation/pdfkit/pdfannotationline/setstart(_:)-57pe0"
    },
    "doc://com.apple.pdfkit/documentation/PDFKit/PDFAnnotationLine/setStart(_:)-86is0": {
      "abstract": [
        {
          "text": "Sets the starting point for the line.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "setStart"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSPoint",
          "text": "NSPoint"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.pdfkit/documentation/PDFKit/PDFAnnotationLine/setStart(_:)-86is0",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "setStartPoint:"
        }
      ],
      "role": "symbol",
      "title": "setStart(_:)",
      "type": "topic",
      "url": "/documentation/pdfkit/pdfannotationline/setstart(_:)-86is0"
    },
    "doc://com.apple.pdfkit/documentation/PDFKit/PDFAnnotationLine/startLineStyle()": {
      "abstract": [
        {
          "text": "Returns the line ending style for the starting point of the line.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "startLineStyle"
        },
        {
          "kind": "text",
          "text": "() -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@PDFLineStyle",
          "text": "PDFLineStyle"
        }
      ],
      "identifier": "doc://com.apple.pdfkit/documentation/PDFKit/PDFAnnotationLine/startLineStyle()",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "startLineStyle"
        }
      ],
      "role": "symbol",
      "title": "startLineStyle()",
      "type": "topic",
      "url": "/documentation/pdfkit/pdfannotationline/startlinestyle()"
    },
    "doc://com.apple.pdfkit/documentation/PDFKit/PDFAnnotationLine/startPoint()": {
      "abstract": [
        {
          "text": "Returns the starting point for the line.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "startPoint"
        },
        {
          "kind": "text",
          "text": "() -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSPoint",
          "text": "NSPoint"
        }
      ],
      "identifier": "doc://com.apple.pdfkit/documentation/PDFKit/PDFAnnotationLine/startPoint()",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "startPoint"
        }
      ],
      "role": "symbol",
      "title": "startPoint()",
      "type": "topic",
      "url": "/documentation/pdfkit/pdfannotationline/startpoint()"
    },
    "doc://com.apple.pdfkit/documentation/PDFKit/PDFAnnotationLink": {
      "abstract": [],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "PDFAnnotationLink"
        }
      ],
      "identifier": "doc://com.apple.pdfkit/documentation/PDFKit/PDFAnnotationLink",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PDFAnnotationLink"
        }
      ],
      "role": "symbol",
      "title": "PDFAnnotationLink",
      "type": "topic",
      "url": "/documentation/pdfkit/pdfannotationlink"
    },
    "doc://com.apple.pdfkit/documentation/PDFKit/PDFAnnotationMarkup": {
      "abstract": [
        {
          "text": "A ",
          "type": "text"
        },
        {
          "code": "PDFAnnotationMarkup",
          "type": "codeVoice"
        },
        {
          "text": " object appears as highlighting, underlining, or a strikethrough style applied to the text of a document.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "PDFAnnotationMarkup"
        }
      ],
      "identifier": "doc://com.apple.pdfkit/documentation/PDFKit/PDFAnnotationMarkup",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PDFAnnotationMarkup"
        }
      ],
      "role": "symbol",
      "title": "PDFAnnotationMarkup",
      "type": "topic",
      "url": "/documentation/pdfkit/pdfannotationmarkup"
    },
    "doc://com.apple.pdfkit/documentation/PDFKit/PDFAnnotationPopup": {
      "abstract": [
        {
          "text": "A ",
          "type": "text"
        },
        {
          "code": "PDFAnnotationPopup",
          "type": "codeVoice"
        },
        {
          "text": " object provides user interactivity on a PDF page in the form of a pop-up menu.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "PDFAnnotationPopup"
        }
      ],
      "identifier": "doc://com.apple.pdfkit/documentation/PDFKit/PDFAnnotationPopup",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PDFAnnotationPopup"
        }
      ],
      "role": "symbol",
      "title": "PDFAnnotationPopup",
      "type": "topic",
      "url": "/documentation/pdfkit/pdfannotationpopup"
    },
    "doc://com.apple.pdfkit/documentation/PDFKit/PDFAnnotationSquare": {
      "abstract": [
        {
          "text": "A rectangle annotation on a page.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "PDFAnnotationSquare"
        }
      ],
      "identifier": "doc://com.apple.pdfkit/documentation/PDFKit/PDFAnnotationSquare",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PDFAnnotationSquare"
        }
      ],
      "role": "symbol",
      "title": "PDFAnnotationSquare",
      "type": "topic",
      "url": "/documentation/pdfkit/pdfannotationsquare"
    },
    "doc://com.apple.pdfkit/documentation/PDFKit/PDFAnnotationStamp": {
      "abstract": [
        {
          "text": "A ",
          "type": "text"
        },
        {
          "code": "PDFAnnotationStamp",
          "type": "codeVoice"
        },
        {
          "text": " object allows you to display a word or phrase, such as “Confidential,” in a PDF page.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "PDFAnnotationStamp"
        }
      ],
      "identifier": "doc://com.apple.pdfkit/documentation/PDFKit/PDFAnnotationStamp",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PDFAnnotationStamp"
        }
      ],
      "role": "symbol",
      "title": "PDFAnnotationStamp",
      "type": "topic",
      "url": "/documentation/pdfkit/pdfannotationstamp"
    },
    "doc://com.apple.pdfkit/documentation/PDFKit/PDFAnnotationSubtype": {
      "abstract": [
        {
          "text": "The type of annotation, such as circle, text, or ink.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "PDFAnnotationSubtype"
        }
      ],
      "identifier": "doc://com.apple.pdfkit/documentation/PDFKit/PDFAnnotationSubtype",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PDFAnnotationSubtype"
        }
      ],
      "role": "symbol",
      "title": "PDFAnnotationSubtype",
      "type": "topic",
      "url": "/documentation/pdfkit/pdfannotationsubtype"
    },
    "doc://com.apple.pdfkit/documentation/PDFKit/PDFAnnotationText": {
      "abstract": [
        {
          "text": "A ",
          "type": "text"
        },
        {
          "code": "PDFAnnotationText",
          "type": "codeVoice"
        },
        {
          "text": " object displays as an icon (such as a “sticky note”) attached to a specified point in the PDF document.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "PDFAnnotationText"
        }
      ],
      "identifier": "doc://com.apple.pdfkit/documentation/PDFKit/PDFAnnotationText",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PDFAnnotationText"
        }
      ],
      "role": "symbol",
      "title": "PDFAnnotationText",
      "type": "topic",
      "url": "/documentation/pdfkit/pdfannotationtext"
    },
    "doc://com.apple.pdfkit/documentation/PDFKit/PDFAnnotationTextWidget": {
      "abstract": [
        {
          "text": "A ",
          "type": "text"
        },
        {
          "code": "PDFAnnotationTextWidget",
          "type": "codeVoice"
        },
        {
          "text": " object allows you to manage the appearance and content of text fields.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "PDFAnnotationTextWidget"
        }
      ],
      "identifier": "doc://com.apple.pdfkit/documentation/PDFKit/PDFAnnotationTextWidget",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PDFAnnotationTextWidget"
        }
      ],
      "role": "symbol",
      "title": "PDFAnnotationTextWidget",
      "type": "topic",
      "url": "/documentation/pdfkit/pdfannotationtextwidget"
    },
    "doc://com.apple.pdfkit/documentation/PDFKit/PDFBorder/lineWidth": {
      "abstract": [
        {
          "text": "Sets the line width (in points) for the border.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "lineWidth"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:14CoreFoundation7CGFloatV",
          "text": "CGFloat"
        }
      ],
      "identifier": "doc://com.apple.pdfkit/documentation/PDFKit/PDFBorder/lineWidth",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "lineWidth"
        }
      ],
      "role": "symbol",
      "title": "lineWidth",
      "type": "topic",
      "url": "/documentation/pdfkit/pdfborder/linewidth"
    },
    "doc://com.apple.pdfkit/documentation/PDFKit/PDFBorder/style": {
      "abstract": [
        {
          "text": "Sets the border style.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "style"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@PDFBorderStyle",
          "text": "PDFBorderStyle"
        }
      ],
      "identifier": "doc://com.apple.pdfkit/documentation/PDFKit/PDFBorder/style",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "style"
        }
      ],
      "role": "symbol",
      "title": "style",
      "type": "topic",
      "url": "/documentation/pdfkit/pdfborder/style"
    },
    "doc://com.apple.pdfkit/documentation/PDFKit/PDFLineStyle": {
      "abstract": [
        {
          "text": "The following constants specify the available line ending styles.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "PDFLineStyle"
        }
      ],
      "identifier": "doc://com.apple.pdfkit/documentation/PDFKit/PDFLineStyle",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PDFLineStyle"
        }
      ],
      "role": "symbol",
      "title": "PDFLineStyle",
      "type": "topic",
      "url": "/documentation/pdfkit/pdflinestyle"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)NSCoding": {
      "abstract": [
        {
          "text": "A protocol that enables an object to be encoded and decoded for archiving and distribution.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "protocol "
        },
        {
          "kind": "identifier",
          "text": "NSCoding"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSCoding",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSCoding",
      "type": "topic",
      "url": "/documentation/foundation/nscoding"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)NSCopying": {
      "abstract": [
        {
          "text": "A protocol that objects adopt to provide functional copies of themselves.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "protocol "
        },
        {
          "kind": "identifier",
          "text": "NSCopying"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSCopying",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSCopying",
      "type": "topic",
      "url": "/documentation/foundation/nscopying"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)NSObject": {
      "abstract": [
        {
          "text": "The group of methods that are fundamental to all Objective-C objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "protocol "
        },
        {
          "kind": "identifier",
          "text": "NSObjectProtocol"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSObject",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSObjectProtocol",
      "type": "topic",
      "url": "/documentation/objectivec/nsobjectprotocol"
    },
    "doc://com.externally.resolved.symbol/s:SH": {
      "abstract": [
        {
          "text": "A type that can be hashed into a `Hasher` to produce an integer hash value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Hashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SQ",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SH",
      "kind": "symbol",
      "role": "symbol",
      "title": "Hashable",
      "type": "topic",
      "url": "/documentation/Swift/Hashable"
    },
    "doc://com.externally.resolved.symbol/s:SQ": {
      "abstract": [
        {
          "text": "A type that can be compared for value equality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SQ",
      "kind": "symbol",
      "role": "symbol",
      "title": "Equatable",
      "type": "topic",
      "url": "/documentation/Swift/Equatable"
    },
    "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP": {
      "abstract": [
        {
          "text": "A type with a customized textual representation.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CustomStringConvertible"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CustomStringConvertible",
      "type": "topic",
      "url": "/documentation/Swift/CustomStringConvertible"
    },
    "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP": {
      "abstract": [
        {
          "text": "A type with a customized textual representation suitable for debugging purposes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CustomDebugStringConvertible"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CustomDebugStringConvertible",
      "type": "topic",
      "url": "/documentation/Swift/CustomDebugStringConvertible"
    },
    "doc://com.externally.resolved.symbol/s:s7CVarArgP": {
      "abstract": [
        {
          "text": "A type whose instances can be encoded, and appropriately passed, as elements of a C `va_list`.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CVarArg"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s7CVarArgP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CVarArg",
      "type": "topic",
      "url": "/documentation/Swift/CVarArg"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.apple.pdfkit/documentation/PDFKit/PDFAnnotation"
      ],
      "kind": "relationships",
      "title": "Inherits From",
      "type": "inheritsFrom"
    },
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:s7CVarArgP",
        "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP",
        "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP",
        "doc://com.externally.resolved.symbol/s:SQ",
        "doc://com.externally.resolved.symbol/s:SH",
        "doc://com.externally.resolved.symbol/c:objc(pl)NSCoding",
        "doc://com.externally.resolved.symbol/c:objc(pl)NSCopying",
        "doc://com.externally.resolved.symbol/c:objc(pl)NSObject"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Deprecated-Annotation-Types",
      "generated": true,
      "identifiers": [
        "doc://com.apple.pdfkit/documentation/PDFKit/PDFAnnotationButtonWidget",
        "doc://com.apple.pdfkit/documentation/PDFKit/PDFAnnotationChoiceWidget",
        "doc://com.apple.pdfkit/documentation/PDFKit/PDFAnnotationCircle",
        "doc://com.apple.pdfkit/documentation/PDFKit/PDFAnnotationFreeText",
        "doc://com.apple.pdfkit/documentation/PDFKit/PDFAnnotationInk",
        "doc://com.apple.pdfkit/documentation/PDFKit/PDFAnnotationLink",
        "doc://com.apple.pdfkit/documentation/PDFKit/PDFAnnotationMarkup",
        "doc://com.apple.pdfkit/documentation/PDFKit/PDFAnnotationPopup",
        "doc://com.apple.pdfkit/documentation/PDFKit/PDFAnnotationSquare",
        "doc://com.apple.pdfkit/documentation/PDFKit/PDFAnnotationStamp",
        "doc://com.apple.pdfkit/documentation/PDFKit/PDFAnnotationText",
        "doc://com.apple.pdfkit/documentation/PDFKit/PDFAnnotationTextWidget"
      ],
      "title": "Deprecated Annotation Types"
    }
  ],
  "topicSections": [
    {
      "anchor": "Specifying-the-Starting-and-Ending-Points",
      "identifiers": [
        "doc://com.apple.pdfkit/documentation/PDFKit/PDFAnnotationLine/startPoint()",
        "doc://com.apple.pdfkit/documentation/PDFKit/PDFAnnotationLine/setStart(_:)-86is0",
        "doc://com.apple.pdfkit/documentation/PDFKit/PDFAnnotationLine/endPoint()",
        "doc://com.apple.pdfkit/documentation/PDFKit/PDFAnnotationLine/setEnd(_:)-2qn58"
      ],
      "title": "Specifying the Starting and Ending Points"
    },
    {
      "anchor": "Specifying-the-Line-Ending-Styles",
      "identifiers": [
        "doc://com.apple.pdfkit/documentation/PDFKit/PDFAnnotationLine/startLineStyle()",
        "doc://com.apple.pdfkit/documentation/PDFKit/PDFAnnotationLine/setStart(_:)-57pe0",
        "doc://com.apple.pdfkit/documentation/PDFKit/PDFAnnotationLine/endLineStyle()",
        "doc://com.apple.pdfkit/documentation/PDFKit/PDFAnnotationLine/setEnd(_:)-9cp0t"
      ],
      "title": "Specifying the Line Ending Styles"
    },
    {
      "anchor": "Specifying-the-Color-of-Line-end-Ornaments",
      "identifiers": [
        "doc://com.apple.pdfkit/documentation/PDFKit/PDFAnnotationLine/interiorColor()",
        "doc://com.apple.pdfkit/documentation/PDFKit/PDFAnnotationLine/setInteriorColor(_:)"
      ],
      "title": "Specifying the Color of Line-end Ornaments"
    },
    {
      "anchor": "Constants",
      "identifiers": [
        "doc://com.apple.pdfkit/documentation/PDFKit/PDFLineStyle"
      ],
      "title": "Constants"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "deprecatedAt": "10.12",
              "introducedAt": "10.4",
              "name": "macOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Class"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "PDFAnnotationLine"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "class"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PDFAnnotationLine"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "PDFAnnotationLine"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.pdfkit/documentation/PDFKit"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Specifying-the-Starting-and-Ending-Points",
              "identifiers": [
                "doc://com.apple.pdfkit/documentation/PDFKit/PDFAnnotationLine/startPoint()",
                "doc://com.apple.pdfkit/documentation/PDFKit/PDFAnnotationLine/setStart(_:)-86is0",
                "doc://com.apple.pdfkit/documentation/PDFKit/PDFAnnotationLine/endPoint()",
                "doc://com.apple.pdfkit/documentation/PDFKit/PDFAnnotationLine/setEnd(_:)-2qn58"
              ],
              "title": "Specifying the Starting and Ending Points"
            },
            {
              "anchor": "Specifying-the-Line-Ending-Styles",
              "identifiers": [
                "doc://com.apple.pdfkit/documentation/PDFKit/PDFAnnotationLine/startLineStyle()",
                "doc://com.apple.pdfkit/documentation/PDFKit/PDFAnnotationLine/setStart(_:)-57pe0",
                "doc://com.apple.pdfkit/documentation/PDFKit/PDFAnnotationLine/endLineStyle()",
                "doc://com.apple.pdfkit/documentation/PDFKit/PDFAnnotationLine/setEnd(_:)-9cp0t"
              ],
              "title": "Specifying the Line Ending Styles"
            },
            {
              "anchor": "Specifying-the-Color-of-Line-end-Ornaments",
              "identifiers": [
                "doc://com.apple.pdfkit/documentation/PDFKit/PDFAnnotationLine/interiorColor()",
                "doc://com.apple.pdfkit/documentation/PDFKit/PDFAnnotationLine/setInteriorColor(_:)"
              ],
              "title": "Specifying the Color of Line-end Ornaments"
            },
            {
              "anchor": "Constants",
              "identifiers": [
                "doc://com.apple.pdfkit/documentation/PDFKit/PDFLineStyle"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": [
            {
              "identifiers": [
                "doc://com.apple.pdfkit/documentation/PDFKit/PDFAnnotation"
              ],
              "kind": "relationships",
              "title": "Inherits From",
              "type": "inheritsFrom"
            },
            {
              "identifiers": [
                "doc://com.externally.resolved.symbol/c:objc(pl)NSCoding",
                "doc://com.externally.resolved.symbol/c:objc(pl)NSCopying"
              ],
              "kind": "relationships",
              "title": "Conforms To",
              "type": "conformsTo"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Deprecated-Annotation-Types",
              "generated": true,
              "identifiers": [
                "doc://com.apple.pdfkit/documentation/PDFKit/PDFAnnotationButtonWidget",
                "doc://com.apple.pdfkit/documentation/PDFKit/PDFAnnotationChoiceWidget",
                "doc://com.apple.pdfkit/documentation/PDFKit/PDFAnnotationCircle",
                "doc://com.apple.pdfkit/documentation/PDFKit/PDFAnnotationFreeText",
                "doc://com.apple.pdfkit/documentation/PDFKit/PDFAnnotationInk",
                "doc://com.apple.pdfkit/documentation/PDFKit/PDFAnnotationLink",
                "doc://com.apple.pdfkit/documentation/PDFKit/PDFAnnotationMarkup",
                "doc://com.apple.pdfkit/documentation/PDFKit/PDFAnnotationPopup",
                "doc://com.apple.pdfkit/documentation/PDFKit/PDFAnnotationSquare",
                "doc://com.apple.pdfkit/documentation/PDFKit/PDFAnnotationStamp",
                "doc://com.apple.pdfkit/documentation/PDFKit/PDFAnnotationText",
                "doc://com.apple.pdfkit/documentation/PDFKit/PDFAnnotationTextWidget"
              ],
              "title": "Deprecated Annotation Types"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "macOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "@interface"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "PDFAnnotationLine"
                  },
                  {
                    "kind": "text",
                    "text": " : "
                  },
                  {
                    "identifier": "doc://com.apple.pdfkit/documentation/PDFKit/PDFAnnotation",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(cs)PDFAnnotation",
                    "text": "PDFAnnotation"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/deprecationSummary",
          "value": [
            {
              "inlineContent": [
                {
                  "text": "Use ",
                  "type": "text"
                },
                {
                  "identifier": "doc://com.apple.pdfkit/documentation/PDFKit/PDFAnnotationSubtype",
                  "isActive": true,
                  "type": "reference"
                },
                {
                  "text": " instead.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFAnnotationInk/title",
          "value": "PDFAnnotationInk"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFAnnotationInk/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PDFAnnotationInk"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFAnnotationInk/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "PDFAnnotationInk"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFAnnotationLine~1interiorColor()/title",
          "value": "interiorColor"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFAnnotationLine~1interiorColor()/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "interiorColor"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFAnnotationStamp/title",
          "value": "PDFAnnotationStamp"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFAnnotationStamp/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PDFAnnotationStamp"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFAnnotationStamp/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "PDFAnnotationStamp"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFAnnotationLine~1startPoint()/title",
          "value": "startPoint"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFAnnotationLine~1startPoint()/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "startPoint"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFAnnotationLine~1endLineStyle()/title",
          "value": "endLineStyle"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFAnnotationLine~1endLineStyle()/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "endLineStyle"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFAnnotationLine~1setStart(_:)-86is0/title",
          "value": "setStartPoint:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFAnnotationLine~1setStart(_:)-86is0/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "setStartPoint:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFAnnotationTextWidget/title",
          "value": "PDFAnnotationTextWidget"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFAnnotationTextWidget/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PDFAnnotationTextWidget"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFAnnotationTextWidget/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "PDFAnnotationTextWidget"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFAnnotationChoiceWidget/title",
          "value": "PDFAnnotationChoiceWidget"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFAnnotationChoiceWidget/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PDFAnnotationChoiceWidget"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFAnnotationChoiceWidget/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "PDFAnnotationChoiceWidget"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFAnnotation~1color/title",
          "value": "color"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFAnnotation~1color/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "color"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFAnnotationText/title",
          "value": "PDFAnnotationText"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFAnnotationText/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PDFAnnotationText"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFAnnotationText/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "PDFAnnotationText"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:objc(pl)NSObject/title",
          "value": "NSObject"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFAnnotationLine~1setEnd(_:)-9cp0t/title",
          "value": "setEndLineStyle:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFAnnotationLine~1setEnd(_:)-9cp0t/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "setEndLineStyle:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFLineStyle/title",
          "value": "PDFLineStyle"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFLineStyle/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PDFLineStyle"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFLineStyle/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "PDFLineStyle"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFAnnotationButtonWidget/title",
          "value": "PDFAnnotationButtonWidget"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFAnnotationButtonWidget/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PDFAnnotationButtonWidget"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFAnnotationButtonWidget/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "PDFAnnotationButtonWidget"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFAnnotationSubtype/title",
          "value": "PDFAnnotationSubtype"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFAnnotationSubtype/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PDFAnnotationSubtype"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFAnnotationSubtype/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "PDFAnnotationSubtype"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFAnnotationLine~1endPoint()/title",
          "value": "endPoint"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFAnnotationLine~1endPoint()/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "endPoint"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFAnnotationLine~1startLineStyle()/title",
          "value": "startLineStyle"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFAnnotationLine~1startLineStyle()/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "startLineStyle"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFAnnotationMarkup/title",
          "value": "PDFAnnotationMarkup"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFAnnotationMarkup/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PDFAnnotationMarkup"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFAnnotationMarkup/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "PDFAnnotationMarkup"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFAnnotationLink/title",
          "value": "PDFAnnotationLink"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFAnnotationLink/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PDFAnnotationLink"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFAnnotationLink/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "PDFAnnotationLink"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFAnnotationCircle/title",
          "value": "PDFAnnotationCircle"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFAnnotationCircle/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PDFAnnotationCircle"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFAnnotationCircle/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "PDFAnnotationCircle"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFAnnotationLine~1setInteriorColor(_:)/title",
          "value": "setInteriorColor:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFAnnotationLine~1setInteriorColor(_:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "setInteriorColor:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFAnnotationSquare/title",
          "value": "PDFAnnotationSquare"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFAnnotationSquare/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PDFAnnotationSquare"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFAnnotationSquare/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "PDFAnnotationSquare"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFAnnotationLine/title",
          "value": "PDFAnnotationLine"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFAnnotationLine/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PDFAnnotationLine"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFAnnotationLine/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "PDFAnnotationLine"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFBorder~1lineWidth/title",
          "value": "lineWidth"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFBorder~1lineWidth/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "lineWidth"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFBorder~1style/title",
          "value": "style"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFBorder~1style/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "style"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFAnnotationLine~1setEnd(_:)-2qn58/title",
          "value": "setEndPoint:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFAnnotationLine~1setEnd(_:)-2qn58/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "setEndPoint:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFAnnotationLine~1setStart(_:)-57pe0/title",
          "value": "setStartLineStyle:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFAnnotationLine~1setStart(_:)-57pe0/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "setStartLineStyle:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFAnnotation/title",
          "value": "PDFAnnotation"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFAnnotation/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PDFAnnotation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFAnnotation/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "PDFAnnotation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFAnnotationPopup/title",
          "value": "PDFAnnotationPopup"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFAnnotationPopup/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PDFAnnotationPopup"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFAnnotationPopup/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "PDFAnnotationPopup"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFAnnotationFreeText/title",
          "value": "PDFAnnotationFreeText"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFAnnotationFreeText/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PDFAnnotationFreeText"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFAnnotationFreeText/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "PDFAnnotationFreeText"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/pdfkit/pdfannotationline"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/pdfkit/pdfannotationline"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
