{
  "abstract": [
    {
      "text": "Keys to control a widget’s appearance.",
      "type": "text"
    }
  ],
  "diffAvailability": {
    "major": {
      "change": "modified",
      "platform": "Xcode",
      "versions": [
        "16.0",
        "16.3 beta 2"
      ]
    }
  },
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.pdfkit/documentation/PDFKit"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.pdfkit/documentation/PDFKit/PDFAppearanceCharacteristicsKey"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@T@PDFAppearanceCharacteristicsKey",
    "fragments": [
      {
        "kind": "keyword",
        "text": "struct"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "PDFAppearanceCharacteristicsKey"
      }
    ],
    "modules": [
      {
        "name": "PDFKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "PDFAppearanceCharacteristicsKey"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "11.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "11.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "11.0",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.4",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Structure",
    "symbolKind": "struct",
    "title": "PDFAppearanceCharacteristicsKey"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "struct"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "PDFAppearanceCharacteristicsKey"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.pdfkit/documentation/PDFKit": {
      "abstract": [
        {
          "text": "Display and manipulate PDF documents in your apps.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.pdfkit/documentation/PDFKit",
      "kind": "symbol",
      "role": "collection",
      "title": "PDFKit",
      "type": "topic",
      "url": "/documentation/pdfkit"
    },
    "doc://com.apple.pdfkit/documentation/PDFKit/PDFAppearanceCharacteristics/appearanceCharacteristicsKeyValues": {
      "abstract": [
        {
          "text": "A dictionary that contains a deep copy of the appearance characteristic key-value pairs.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "appearanceCharacteristicsKeyValues"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s11AnyHashableV",
          "text": "AnyHashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "keyword",
          "text": "Any"
        },
        {
          "kind": "text",
          "text": "]"
        }
      ],
      "identifier": "doc://com.apple.pdfkit/documentation/PDFKit/PDFAppearanceCharacteristics/appearanceCharacteristicsKeyValues",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "appearanceCharacteristicsKeyValues"
        }
      ],
      "role": "symbol",
      "title": "appearanceCharacteristicsKeyValues",
      "type": "topic",
      "url": "/documentation/pdfkit/pdfappearancecharacteristics/appearancecharacteristicskeyvalues"
    },
    "doc://com.apple.pdfkit/documentation/PDFKit/PDFAppearanceCharacteristics/backgroundColor": {
      "abstract": [
        {
          "text": "The background color of the widget annotation.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "backgroundColor"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UIColor",
          "text": "UIColor"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.pdfkit/documentation/PDFKit/PDFAppearanceCharacteristics/backgroundColor",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "backgroundColor"
        }
      ],
      "role": "symbol",
      "title": "backgroundColor",
      "type": "topic",
      "url": "/documentation/pdfkit/pdfappearancecharacteristics/backgroundcolor"
    },
    "doc://com.apple.pdfkit/documentation/PDFKit/PDFAppearanceCharacteristics/borderColor": {
      "abstract": [
        {
          "text": "The border color of the widget annotation.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "borderColor"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UIColor",
          "text": "UIColor"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.pdfkit/documentation/PDFKit/PDFAppearanceCharacteristics/borderColor",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "borderColor"
        }
      ],
      "role": "symbol",
      "title": "borderColor",
      "type": "topic",
      "url": "/documentation/pdfkit/pdfappearancecharacteristics/bordercolor"
    },
    "doc://com.apple.pdfkit/documentation/PDFKit/PDFAppearanceCharacteristics/caption": {
      "abstract": [
        {
          "text": "The text that the button widget annotation displays when the user isn’t interacting with it.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "caption"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.pdfkit/documentation/PDFKit/PDFAppearanceCharacteristics/caption",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "caption"
        }
      ],
      "role": "symbol",
      "title": "caption",
      "type": "topic",
      "url": "/documentation/pdfkit/pdfappearancecharacteristics/caption"
    },
    "doc://com.apple.pdfkit/documentation/PDFKit/PDFAppearanceCharacteristics/controlType": {
      "abstract": [
        {
          "text": "The type of button widget annotation.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "controlType"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@PDFWidgetControlType",
          "text": "PDFWidgetControlType"
        }
      ],
      "identifier": "doc://com.apple.pdfkit/documentation/PDFKit/PDFAppearanceCharacteristics/controlType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "controlType"
        }
      ],
      "role": "symbol",
      "title": "controlType",
      "type": "topic",
      "url": "/documentation/pdfkit/pdfappearancecharacteristics/controltype"
    },
    "doc://com.apple.pdfkit/documentation/PDFKit/PDFAppearanceCharacteristics/downCaption": {
      "abstract": [
        {
          "text": "The text that the button widget annotation displays when the user holds down on it.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "downCaption"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.pdfkit/documentation/PDFKit/PDFAppearanceCharacteristics/downCaption",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "downCaption"
        }
      ],
      "role": "symbol",
      "title": "downCaption",
      "type": "topic",
      "url": "/documentation/pdfkit/pdfappearancecharacteristics/downcaption"
    },
    "doc://com.apple.pdfkit/documentation/PDFKit/PDFAppearanceCharacteristics/rolloverCaption": {
      "abstract": [
        {
          "text": "The text that the widget annotation displays when the user hovers the pointer over it.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "rolloverCaption"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.pdfkit/documentation/PDFKit/PDFAppearanceCharacteristics/rolloverCaption",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "rolloverCaption"
        }
      ],
      "role": "symbol",
      "title": "rolloverCaption",
      "type": "topic",
      "url": "/documentation/pdfkit/pdfappearancecharacteristics/rollovercaption"
    },
    "doc://com.apple.pdfkit/documentation/PDFKit/PDFAppearanceCharacteristics/rotation": {
      "abstract": [
        {
          "text": "The number of degrees, in multiples of 90, that the widget annotation rotates counterclockwise relative to the page.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "rotation"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.pdfkit/documentation/PDFKit/PDFAppearanceCharacteristics/rotation",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "rotation"
        }
      ],
      "role": "symbol",
      "title": "rotation",
      "type": "topic",
      "url": "/documentation/pdfkit/pdfappearancecharacteristics/rotation"
    },
    "doc://com.apple.pdfkit/documentation/PDFKit/PDFAppearanceCharacteristicsKey": {
      "abstract": [
        {
          "text": "Keys to control a widget’s appearance.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "PDFAppearanceCharacteristicsKey"
        }
      ],
      "identifier": "doc://com.apple.pdfkit/documentation/PDFKit/PDFAppearanceCharacteristicsKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PDFAppearanceCharacteristicsKey"
        }
      ],
      "role": "symbol",
      "title": "PDFAppearanceCharacteristicsKey",
      "type": "topic",
      "url": "/documentation/pdfkit/pdfappearancecharacteristicskey"
    },
    "doc://com.apple.pdfkit/documentation/PDFKit/PDFAppearanceCharacteristicsKey/backgroundColor": {
      "abstract": [
        {
          "text": "The background color of the widget annotation.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "backgroundColor"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@PDFAppearanceCharacteristicsKey",
          "text": "PDFAppearanceCharacteristicsKey"
        }
      ],
      "identifier": "doc://com.apple.pdfkit/documentation/PDFKit/PDFAppearanceCharacteristicsKey/backgroundColor",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PDFAppearanceCharacteristicsKeyBackgroundColor"
        }
      ],
      "role": "symbol",
      "title": "backgroundColor",
      "type": "topic",
      "url": "/documentation/pdfkit/pdfappearancecharacteristicskey/backgroundcolor"
    },
    "doc://com.apple.pdfkit/documentation/PDFKit/PDFAppearanceCharacteristicsKey/borderColor": {
      "abstract": [
        {
          "text": "The border color of the widget annotation.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "borderColor"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@PDFAppearanceCharacteristicsKey",
          "text": "PDFAppearanceCharacteristicsKey"
        }
      ],
      "identifier": "doc://com.apple.pdfkit/documentation/PDFKit/PDFAppearanceCharacteristicsKey/borderColor",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PDFAppearanceCharacteristicsKeyBorderColor"
        }
      ],
      "role": "symbol",
      "title": "borderColor",
      "type": "topic",
      "url": "/documentation/pdfkit/pdfappearancecharacteristicskey/bordercolor"
    },
    "doc://com.apple.pdfkit/documentation/PDFKit/PDFAppearanceCharacteristicsKey/caption": {
      "abstract": [
        {
          "text": "The text that the button widget annotation displays when the user isn’t interacting with it.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "caption"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@PDFAppearanceCharacteristicsKey",
          "text": "PDFAppearanceCharacteristicsKey"
        }
      ],
      "identifier": "doc://com.apple.pdfkit/documentation/PDFKit/PDFAppearanceCharacteristicsKey/caption",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PDFAppearanceCharacteristicsKeyCaption"
        }
      ],
      "role": "symbol",
      "title": "caption",
      "type": "topic",
      "url": "/documentation/pdfkit/pdfappearancecharacteristicskey/caption"
    },
    "doc://com.apple.pdfkit/documentation/PDFKit/PDFAppearanceCharacteristicsKey/downCaption": {
      "abstract": [
        {
          "text": "The text that the button widget annotation displays when the user holds down on it.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "downCaption"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@PDFAppearanceCharacteristicsKey",
          "text": "PDFAppearanceCharacteristicsKey"
        }
      ],
      "identifier": "doc://com.apple.pdfkit/documentation/PDFKit/PDFAppearanceCharacteristicsKey/downCaption",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PDFAppearanceCharacteristicsKeyDownCaption"
        }
      ],
      "role": "symbol",
      "title": "downCaption",
      "type": "topic",
      "url": "/documentation/pdfkit/pdfappearancecharacteristicskey/downcaption"
    },
    "doc://com.apple.pdfkit/documentation/PDFKit/PDFAppearanceCharacteristicsKey/init(rawValue:)": {
      "abstract": [
        {
          "text": "Creates an appearance characteristic key using the specified raw string.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "rawValue"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.pdfkit/documentation/PDFKit/PDFAppearanceCharacteristicsKey/init(rawValue:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "init(rawValue:)",
      "type": "topic",
      "url": "/documentation/pdfkit/pdfappearancecharacteristicskey/init(rawvalue:)"
    },
    "doc://com.apple.pdfkit/documentation/PDFKit/PDFAppearanceCharacteristicsKey/rolloverCaption": {
      "abstract": [
        {
          "text": "The text that the button widget annotation displays when the user hovers the pointer over it.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "rolloverCaption"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@PDFAppearanceCharacteristicsKey",
          "text": "PDFAppearanceCharacteristicsKey"
        }
      ],
      "identifier": "doc://com.apple.pdfkit/documentation/PDFKit/PDFAppearanceCharacteristicsKey/rolloverCaption",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PDFAppearanceCharacteristicsKeyRolloverCaption"
        }
      ],
      "role": "symbol",
      "title": "rolloverCaption",
      "type": "topic",
      "url": "/documentation/pdfkit/pdfappearancecharacteristicskey/rollovercaption"
    },
    "doc://com.apple.pdfkit/documentation/PDFKit/PDFAppearanceCharacteristicsKey/rotation": {
      "abstract": [
        {
          "text": "The number of degrees, in multiples of 90, that the widget annotation rotates counterclockwise relative to the page.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "rotation"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@PDFAppearanceCharacteristicsKey",
          "text": "PDFAppearanceCharacteristicsKey"
        }
      ],
      "identifier": "doc://com.apple.pdfkit/documentation/PDFKit/PDFAppearanceCharacteristicsKey/rotation",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PDFAppearanceCharacteristicsKeyRotation"
        }
      ],
      "role": "symbol",
      "title": "rotation",
      "type": "topic",
      "url": "/documentation/pdfkit/pdfappearancecharacteristicskey/rotation"
    },
    "doc://com.externally.resolved.symbol/c:objc(cs)NSString": {
      "abstract": [
        {
          "text": "A static, plain-text Unicode string object which you use when you need reference semantics or other Foundation-specific behavior. ",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "class "
        },
        {
          "kind": "identifier",
          "text": "NSString"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSString",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSString",
      "type": "topic",
      "url": "/documentation/foundation/nsstring"
    },
    "doc://com.externally.resolved.symbol/s:SH": {
      "abstract": [
        {
          "text": "A type that can be hashed into a `Hasher` to produce an integer hash value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Hashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SQ",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SH",
      "kind": "symbol",
      "role": "symbol",
      "title": "Hashable",
      "type": "topic",
      "url": "/documentation/Swift/Hashable"
    },
    "doc://com.externally.resolved.symbol/s:SQ": {
      "abstract": [
        {
          "text": "A type that can be compared for value equality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SQ",
      "kind": "symbol",
      "role": "symbol",
      "title": "Equatable",
      "type": "topic",
      "url": "/documentation/Swift/Equatable"
    },
    "doc://com.externally.resolved.symbol/s:SY": {
      "abstract": [
        {
          "text": "A type that can be converted to and from an associated raw value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "RawRepresentable"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SY8RawValueQa",
          "text": "RawValue"
        },
        {
          "kind": "text",
          "text": ">"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SY",
      "kind": "symbol",
      "role": "symbol",
      "title": "RawRepresentable",
      "type": "topic",
      "url": "/documentation/Swift/RawRepresentable"
    },
    "doc://com.externally.resolved.symbol/s:s8SendableP": {
      "abstract": [
        {
          "text": "A thread-safe type whose values can be shared across arbitrary concurrent contexts without introducing a risk of data races.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Sendable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s8SendableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "Sendable",
      "type": "topic",
      "url": "/documentation/Swift/Sendable"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:SQ",
        "doc://com.externally.resolved.symbol/s:SH",
        "doc://com.externally.resolved.symbol/s:SY",
        "doc://com.externally.resolved.symbol/s:s8SendableP"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Configuring-a-Widgets-Appearance",
      "generated": true,
      "identifiers": [
        "doc://com.apple.pdfkit/documentation/PDFKit/PDFAppearanceCharacteristics/backgroundColor",
        "doc://com.apple.pdfkit/documentation/PDFKit/PDFAppearanceCharacteristics/borderColor",
        "doc://com.apple.pdfkit/documentation/PDFKit/PDFAppearanceCharacteristics/caption",
        "doc://com.apple.pdfkit/documentation/PDFKit/PDFAppearanceCharacteristics/controlType",
        "doc://com.apple.pdfkit/documentation/PDFKit/PDFAppearanceCharacteristics/downCaption",
        "doc://com.apple.pdfkit/documentation/PDFKit/PDFAppearanceCharacteristics/rolloverCaption",
        "doc://com.apple.pdfkit/documentation/PDFKit/PDFAppearanceCharacteristics/rotation",
        "doc://com.apple.pdfkit/documentation/PDFKit/PDFAppearanceCharacteristics/appearanceCharacteristicsKeyValues"
      ],
      "title": "Configuring a Widget’s Appearance"
    }
  ],
  "topicSections": [
    {
      "anchor": "Modifying-Widget-Appearance",
      "identifiers": [
        "doc://com.apple.pdfkit/documentation/PDFKit/PDFAppearanceCharacteristicsKey/backgroundColor",
        "doc://com.apple.pdfkit/documentation/PDFKit/PDFAppearanceCharacteristicsKey/borderColor",
        "doc://com.apple.pdfkit/documentation/PDFKit/PDFAppearanceCharacteristicsKey/caption",
        "doc://com.apple.pdfkit/documentation/PDFKit/PDFAppearanceCharacteristicsKey/downCaption",
        "doc://com.apple.pdfkit/documentation/PDFKit/PDFAppearanceCharacteristicsKey/rolloverCaption",
        "doc://com.apple.pdfkit/documentation/PDFKit/PDFAppearanceCharacteristicsKey/rotation"
      ],
      "title": "Modifying Widget Appearance"
    },
    {
      "anchor": "Creating-an-Appearance-Characteristic-Key",
      "identifiers": [
        "doc://com.apple.pdfkit/documentation/PDFKit/PDFAppearanceCharacteristicsKey/init(rawValue:)"
      ],
      "title": "Creating an Appearance Characteristic Key"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "11.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "11.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "11.0",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.4",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Type Alias"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "PDFAppearanceCharacteristicsKey"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "typealias"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PDFAppearanceCharacteristicsKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "PDFAppearanceCharacteristicsKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.pdfkit/documentation/PDFKit"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Modifying-Widget-Appearance",
              "identifiers": [
                "doc://com.apple.pdfkit/documentation/PDFKit/PDFAppearanceCharacteristicsKey/backgroundColor",
                "doc://com.apple.pdfkit/documentation/PDFKit/PDFAppearanceCharacteristicsKey/borderColor",
                "doc://com.apple.pdfkit/documentation/PDFKit/PDFAppearanceCharacteristicsKey/caption",
                "doc://com.apple.pdfkit/documentation/PDFKit/PDFAppearanceCharacteristicsKey/downCaption",
                "doc://com.apple.pdfkit/documentation/PDFKit/PDFAppearanceCharacteristicsKey/rolloverCaption",
                "doc://com.apple.pdfkit/documentation/PDFKit/PDFAppearanceCharacteristicsKey/rotation"
              ],
              "title": "Modifying Widget Appearance"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Configuring-a-Widgets-Appearance",
              "generated": true,
              "identifiers": [
                "doc://com.apple.pdfkit/documentation/PDFKit/PDFAppearanceCharacteristics/backgroundColor",
                "doc://com.apple.pdfkit/documentation/PDFKit/PDFAppearanceCharacteristics/borderColor",
                "doc://com.apple.pdfkit/documentation/PDFKit/PDFAppearanceCharacteristics/caption",
                "doc://com.apple.pdfkit/documentation/PDFKit/PDFAppearanceCharacteristics/controlType",
                "doc://com.apple.pdfkit/documentation/PDFKit/PDFAppearanceCharacteristics/downCaption",
                "doc://com.apple.pdfkit/documentation/PDFKit/PDFAppearanceCharacteristics/rolloverCaption",
                "doc://com.apple.pdfkit/documentation/PDFKit/PDFAppearanceCharacteristics/rotation",
                "doc://com.apple.pdfkit/documentation/PDFKit/PDFAppearanceCharacteristics/appearanceCharacteristicsKeyValues"
              ],
              "title": "Configuring a Widget’s Appearance"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "typedef"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSString",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(cs)NSString",
                    "text": "NSString"
                  },
                  {
                    "kind": "text",
                    "text": " * "
                  },
                  {
                    "kind": "keyword",
                    "text": "const"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "PDFAppearanceCharacteristicsKey"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFAppearanceCharacteristics~1rotation/title",
          "value": "rotation"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFAppearanceCharacteristics~1rotation/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "rotation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFAppearanceCharacteristicsKey~1downCaption/title",
          "value": "PDFAppearanceCharacteristicsKeyDownCaption"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFAppearanceCharacteristicsKey~1downCaption/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PDFAppearanceCharacteristicsKeyDownCaption"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFAppearanceCharacteristicsKey~1rotation/title",
          "value": "PDFAppearanceCharacteristicsKeyRotation"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFAppearanceCharacteristicsKey~1rotation/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PDFAppearanceCharacteristicsKeyRotation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFAppearanceCharacteristics~1controlType/title",
          "value": "controlType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFAppearanceCharacteristics~1controlType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "controlType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFAppearanceCharacteristics~1borderColor/title",
          "value": "borderColor"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFAppearanceCharacteristics~1borderColor/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "borderColor"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFAppearanceCharacteristicsKey~1rolloverCaption/title",
          "value": "PDFAppearanceCharacteristicsKeyRolloverCaption"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFAppearanceCharacteristicsKey~1rolloverCaption/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PDFAppearanceCharacteristicsKeyRolloverCaption"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFAppearanceCharacteristicsKey/title",
          "value": "PDFAppearanceCharacteristicsKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFAppearanceCharacteristicsKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PDFAppearanceCharacteristicsKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFAppearanceCharacteristicsKey/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "PDFAppearanceCharacteristicsKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFAppearanceCharacteristicsKey~1backgroundColor/title",
          "value": "PDFAppearanceCharacteristicsKeyBackgroundColor"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFAppearanceCharacteristicsKey~1backgroundColor/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PDFAppearanceCharacteristicsKeyBackgroundColor"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFAppearanceCharacteristics~1downCaption/title",
          "value": "downCaption"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFAppearanceCharacteristics~1downCaption/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "downCaption"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFAppearanceCharacteristicsKey~1caption/title",
          "value": "PDFAppearanceCharacteristicsKeyCaption"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFAppearanceCharacteristicsKey~1caption/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PDFAppearanceCharacteristicsKeyCaption"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFAppearanceCharacteristicsKey~1borderColor/title",
          "value": "PDFAppearanceCharacteristicsKeyBorderColor"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFAppearanceCharacteristicsKey~1borderColor/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PDFAppearanceCharacteristicsKeyBorderColor"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFAppearanceCharacteristics~1appearanceCharacteristicsKeyValues/title",
          "value": "appearanceCharacteristicsKeyValues"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFAppearanceCharacteristics~1appearanceCharacteristicsKeyValues/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "appearanceCharacteristicsKeyValues"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:objc(cs)NSString/abstract",
          "value": [
            {
              "text": "A static, plain-text Unicode string object.",
              "type": "text"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFAppearanceCharacteristics~1rolloverCaption/title",
          "value": "rolloverCaption"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFAppearanceCharacteristics~1rolloverCaption/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "rolloverCaption"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFAppearanceCharacteristics~1caption/title",
          "value": "caption"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFAppearanceCharacteristics~1caption/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "caption"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFAppearanceCharacteristics~1backgroundColor/title",
          "value": "backgroundColor"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFAppearanceCharacteristics~1backgroundColor/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "backgroundColor"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/pdfkit/pdfappearancecharacteristicskey"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/pdfkit/pdfappearancecharacteristicskey"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
