{"hierarchy":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.pdfkit/documentation/PDFKit"]]},"seeAlsoSections":[{"generated":true,"anchor":"Action-Types","title":"Action Types","identifiers":["doc://com.apple.pdfkit/documentation/PDFKit/PDFActionNamed","doc://com.apple.pdfkit/documentation/PDFKit/PDFActionRemoteGoTo","doc://com.apple.pdfkit/documentation/PDFKit/PDFActionResetForm","doc://com.apple.pdfkit/documentation/PDFKit/PDFActionURL","doc://com.apple.pdfkit/documentation/PDFKit/PDFActionNamedName"]}],"relationshipsSections":[{"kind":"relationships","title":"Inherits From","type":"inheritsFrom","identifiers":["doc://com.apple.pdfkit/documentation/PDFKit/PDFAction"]},{"kind":"relationships","title":"Conforms To","type":"conformsTo","identifiers":["doc://com.externally.resolved.symbol/s:s7CVarArgP","doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP","doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP","doc://com.externally.resolved.symbol/s:SQ","doc://com.externally.resolved.symbol/s:SH","doc://com.externally.resolved.symbol/c:objc(pl)NSCopying","doc://com.externally.resolved.symbol/c:objc(pl)NSObject"]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"PDFActionGoTo","kind":"identifier"}],"platforms":["iOS","iPadOS","Mac Catalyst","macOS","tvOS","visionOS"]}]},{"kind":"content","content":[{"text":"Overview","type":"heading","anchor":"overview","level":2},{"type":"paragraph","inlineContent":[{"text":"A ","type":"text"},{"code":"PDFActionGoTo","type":"codeVoice"},{"text":" object represents the action of going to a specific location within the PDF document.","type":"text"}]}]}],"kind":"symbol","variants":[{"paths":["/documentation/pdfkit/pdfactiongoto"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["/documentation/pdfkit/pdfactiongoto"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"identifier":{"url":"doc://com.apple.pdfkit/documentation/PDFKit/PDFActionGoTo","interfaceLanguage":"swift"},"metadata":{"navigatorTitle":[{"text":"PDFActionGoTo","kind":"identifier"}],"title":"PDFActionGoTo","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"PDFActionGoTo","kind":"identifier"}],"role":"symbol","externalID":"c:objc(cs)PDFActionGoTo","modules":[{"name":"PDFKit"}],"roleHeading":"Class","symbolKind":"class","platforms":[{"introducedAt":"11.0","deprecated":false,"unavailable":false,"beta":false,"name":"iOS"},{"introducedAt":"11.0","deprecated":false,"unavailable":false,"beta":false,"name":"iPadOS"},{"introducedAt":"13.1","deprecated":false,"unavailable":false,"beta":false,"name":"Mac Catalyst"},{"introducedAt":"10.5","deprecated":false,"unavailable":false,"beta":false,"name":"macOS"},{"introducedAt":"11.0","deprecated":false,"unavailable":false,"beta":false,"name":"tvOS"},{"introducedAt":"1.0","deprecated":false,"unavailable":false,"beta":false,"name":"visionOS"}]},"topicSections":[{"anchor":"Accessing-the-Destination","title":"Accessing the Destination","identifiers":["doc://com.apple.pdfkit/documentation/PDFKit/PDFActionGoTo/destination"]},{"anchor":"Initializing-the-Action","title":"Initializing the Action","identifiers":["doc://com.apple.pdfkit/documentation/PDFKit/PDFActionGoTo/init(destination:)"]}],"abstract":[{"code":"PDFActionGoTo","type":"codeVoice"},{"text":", a subclass of ","type":"text"},{"code":"PDFAction","type":"codeVoice"},{"text":", defines methods for getting and setting the destination of a go-to action.","type":"text"}],"sections":[],"references":{"doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP":{"type":"topic","abstract":[{"text":"A type with a customized textual representation.","type":"text"}],"title":"CustomStringConvertible","role":"symbol","url":"/documentation/Swift/CustomStringConvertible","identifier":"doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"CustomStringConvertible","kind":"identifier"}],"kind":"symbol"},"doc://com.apple.pdfkit/documentation/PDFKit/PDFActionResetForm":{"navigatorTitle":[{"text":"PDFActionResetForm","kind":"identifier"}],"role":"symbol","kind":"symbol","title":"PDFActionResetForm","identifier":"doc://com.apple.pdfkit/documentation/PDFKit/PDFActionResetForm","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"PDFActionResetForm","kind":"identifier"}],"url":"/documentation/pdfkit/pdfactionresetform","abstract":[{"code":"PDFActionResetForm","type":"codeVoice"},{"type":"text","text":", a subclass of "},{"type":"codeVoice","code":"PDFAction"},{"text":", defines methods for getting and clearing fields in a PDF form.","type":"text"}],"type":"topic"},"doc://com.externally.resolved.symbol/s:SQ":{"role":"symbol","abstract":[{"text":"A type that can be compared for value equality.","type":"text"}],"kind":"symbol","type":"topic","identifier":"doc://com.externally.resolved.symbol/s:SQ","title":"Equatable","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Equatable","kind":"identifier"}],"url":"/documentation/Swift/Equatable"},"doc://com.apple.pdfkit/documentation/PDFKit/PDFActionNamed":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"PDFActionNamed","kind":"identifier"}],"type":"topic","url":"/documentation/pdfkit/pdfactionnamed","title":"PDFActionNamed","abstract":[{"code":"PDFActionNamed","type":"codeVoice"},{"text":" defines methods used to work with actions in PDF documents, some of which are named in the Adobe PDF Specification.","type":"text"}],"role":"symbol","navigatorTitle":[{"text":"PDFActionNamed","kind":"identifier"}],"identifier":"doc://com.apple.pdfkit/documentation/PDFKit/PDFActionNamed","kind":"symbol"},"doc://com.apple.pdfkit/documentation/PDFKit":{"role":"collection","identifier":"doc://com.apple.pdfkit/documentation/PDFKit","type":"topic","abstract":[{"type":"text","text":"Display and manipulate PDF documents in your apps."}],"kind":"symbol","title":"PDFKit","url":"/documentation/pdfkit"},"doc://com.apple.pdfkit/documentation/PDFKit/PDFActionNamedName":{"type":"topic","role":"symbol","url":"/documentation/pdfkit/pdfactionnamedname","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"PDFActionNamedName"}],"abstract":[],"navigatorTitle":[{"kind":"identifier","text":"PDFActionNamedName"}],"title":"PDFActionNamedName","kind":"symbol","identifier":"doc://com.apple.pdfkit/documentation/PDFKit/PDFActionNamedName"},"doc://com.externally.resolved.symbol/c:objc(pl)NSCopying":{"title":"NSCopying","identifier":"doc://com.externally.resolved.symbol/c:objc(pl)NSCopying","url":"/documentation/foundation/nscopying","role":"symbol","abstract":[{"text":"A protocol that objects adopt to provide functional copies of themselves.","type":"text"}],"kind":"symbol","type":"topic","fragments":[{"text":"protocol ","kind":"text"},{"text":"NSCopying","kind":"identifier"}]},"doc://com.apple.pdfkit/documentation/PDFKit/PDFActionGoTo":{"navigatorTitle":[{"text":"PDFActionGoTo","kind":"identifier"}],"role":"symbol","kind":"symbol","title":"PDFActionGoTo","identifier":"doc://com.apple.pdfkit/documentation/PDFKit/PDFActionGoTo","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"PDFActionGoTo","kind":"identifier"}],"url":"/documentation/pdfkit/pdfactiongoto","abstract":[{"type":"codeVoice","code":"PDFActionGoTo"},{"type":"text","text":", a subclass of "},{"type":"codeVoice","code":"PDFAction"},{"text":", defines methods for getting and setting the destination of a go-to action.","type":"text"}],"type":"topic"},"doc://com.apple.pdfkit/documentation/PDFKit/PDFActionRemoteGoTo":{"abstract":[{"code":"PDFActionRemoteGoTo","type":"codeVoice"},{"text":", a subclass of ","type":"text"},{"type":"codeVoice","code":"PDFAction"},{"type":"text","text":", defines methods for getting and setting the destination of a go-to action that targets another document."}],"title":"PDFActionRemoteGoTo","role":"symbol","identifier":"doc://com.apple.pdfkit/documentation/PDFKit/PDFActionRemoteGoTo","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"PDFActionRemoteGoTo"}],"url":"/documentation/pdfkit/pdfactionremotegoto","type":"topic","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"PDFActionRemoteGoTo"}]},"doc://com.externally.resolved.symbol/s:SH":{"fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Hashable","kind":"identifier"},{"text":" : ","kind":"text"},{"text":"Equatable","preciseIdentifier":"s:SQ","kind":"typeIdentifier"}],"abstract":[{"text":"A type that can be hashed into a `Hasher` to produce an integer hash value.","type":"text"}],"url":"/documentation/Swift/Hashable","identifier":"doc://com.externally.resolved.symbol/s:SH","title":"Hashable","kind":"symbol","role":"symbol","type":"topic"},"doc://com.apple.pdfkit/documentation/PDFKit/PDFAction":{"url":"/documentation/pdfkit/pdfaction","role":"symbol","identifier":"doc://com.apple.pdfkit/documentation/PDFKit/PDFAction","title":"PDFAction","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"PDFAction"}],"abstract":[{"text":"An action that is performed when, for example, a PDF annotation is activated or an outline item is clicked.","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"PDFAction"}],"kind":"symbol","type":"topic"},"doc://com.apple.pdfkit/documentation/PDFKit/PDFActionGoTo/destination":{"navigatorTitle":[{"text":"destination","kind":"identifier"}],"role":"symbol","kind":"symbol","title":"destination","identifier":"doc://com.apple.pdfkit/documentation/PDFKit/PDFActionGoTo/destination","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"destination","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)PDFDestination","text":"PDFDestination","kind":"typeIdentifier"}],"url":"/documentation/pdfkit/pdfactiongoto/destination","abstract":[{"type":"text","text":"Returns the destination associated with the action."}],"type":"topic"},"doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP":{"fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"text":"CustomDebugStringConvertible","kind":"identifier"}],"kind":"symbol","type":"topic","title":"CustomDebugStringConvertible","identifier":"doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP","abstract":[{"type":"text","text":"A type with a customized textual representation suitable for debugging purposes."}],"role":"symbol","url":"/documentation/Swift/CustomDebugStringConvertible"},"doc://com.apple.pdfkit/documentation/PDFKit/PDFActionURL":{"navigatorTitle":[{"text":"PDFActionURL","kind":"identifier"}],"role":"symbol","kind":"symbol","title":"PDFActionURL","identifier":"doc://com.apple.pdfkit/documentation/PDFKit/PDFActionURL","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"PDFActionURL","kind":"identifier"}],"url":"/documentation/pdfkit/pdfactionurl","abstract":[{"type":"codeVoice","code":"PDFActionURL"},{"type":"text","text":", a subclass of "},{"code":"PDFAction","type":"codeVoice"},{"type":"text","text":", defines methods for getting and setting the URL associated with a URL action."}],"type":"topic"},"doc://com.apple.documentation/documentation/technologies":{"kind":"technologies","url":"/documentation/technologies","role":"overview","identifier":"doc://com.apple.documentation/documentation/technologies","abstract":[{"text":"","type":"text"}],"title":"Technologies","type":"topic"},"doc://com.apple.pdfkit/documentation/PDFKit/PDFActionGoTo/init(destination:)":{"navigatorTitle":[{"text":"initWithDestination:","kind":"identifier"}],"role":"symbol","kind":"symbol","title":"init(destination:)","identifier":"doc://com.apple.pdfkit/documentation/PDFKit/PDFActionGoTo/init(destination:)","fragments":[{"kind":"identifier","text":"init"},{"text":"(","kind":"text"},{"text":"destination","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)PDFDestination","text":"PDFDestination","kind":"typeIdentifier"},{"text":")","kind":"text"}],"url":"/documentation/pdfkit/pdfactiongoto/init(destination:)","abstract":[{"type":"text","text":"Initializes the go-to action."}],"type":"topic"},"doc://com.externally.resolved.symbol/s:s7CVarArgP":{"fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"CVarArg","kind":"identifier"}],"abstract":[{"type":"text","text":"A type whose instances can be encoded, and appropriately passed, as elements of a C `va_list`."}],"url":"/documentation/Swift/CVarArg","identifier":"doc://com.externally.resolved.symbol/s:s7CVarArgP","title":"CVarArg","kind":"symbol","role":"symbol","type":"topic"},"doc://com.externally.resolved.symbol/c:objc(pl)NSObject":{"role":"symbol","abstract":[{"text":"The group of methods that are fundamental to all Objective-C objects.","type":"text"}],"kind":"symbol","type":"topic","identifier":"doc://com.externally.resolved.symbol/c:objc(pl)NSObject","title":"NSObjectProtocol","fragments":[{"text":"protocol ","kind":"text"},{"text":"NSObjectProtocol","kind":"identifier"}],"url":"/documentation/objectivec/nsobjectprotocol"}},"variantOverrides":[{"patch":[{"value":"occ","path":"/identifier/interfaceLanguage","op":"replace"},{"value":[{"deprecated":false,"introducedAt":"11.0","beta":false,"name":"iOS","unavailable":false},{"deprecated":false,"introducedAt":"11.0","beta":false,"name":"iPadOS","unavailable":false},{"deprecated":false,"introducedAt":"13.1","beta":false,"name":"Mac Catalyst","unavailable":false},{"deprecated":false,"introducedAt":"10.5","beta":false,"name":"macOS","unavailable":false},{"deprecated":false,"introducedAt":"11.0","beta":false,"name":"tvOS","unavailable":false},{"deprecated":false,"introducedAt":"1.0","beta":false,"name":"visionOS","unavailable":false}],"path":"/metadata/platforms","op":"replace"},{"value":"Class","path":"/metadata/roleHeading","op":"replace"},{"value":"PDFActionGoTo","path":"/metadata/title","op":"replace"},{"value":"class","path":"/metadata/symbolKind","op":"replace"},{"value":[{"kind":"identifier","text":"PDFActionGoTo"}],"path":"/metadata/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"PDFActionGoTo"}],"path":"/metadata/navigatorTitle","op":"replace"},{"value":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.pdfkit/documentation/PDFKit"]]},"path":"/hierarchy","op":"replace"},{"value":[{"anchor":"Accessing-the-Destination","title":"Accessing the Destination","identifiers":["doc://com.apple.pdfkit/documentation/PDFKit/PDFActionGoTo/destination"]},{"anchor":"Initializing-the-Action","title":"Initializing the Action","identifiers":["doc://com.apple.pdfkit/documentation/PDFKit/PDFActionGoTo/init(destination:)"]}],"path":"/topicSections","op":"replace"},{"value":[{"title":"Inherits From","kind":"relationships","type":"inheritsFrom","identifiers":["doc://com.apple.pdfkit/documentation/PDFKit/PDFAction"]},{"title":"Conforms To","kind":"relationships","type":"conformsTo","identifiers":["doc://com.externally.resolved.symbol/c:objc(pl)NSCopying"]}],"path":"/relationshipsSections","op":"replace"},{"value":[{"anchor":"Action-Types","generated":true,"title":"Action Types","identifiers":["doc://com.apple.pdfkit/documentation/PDFKit/PDFActionNamed","doc://com.apple.pdfkit/documentation/PDFKit/PDFActionRemoteGoTo","doc://com.apple.pdfkit/documentation/PDFKit/PDFActionResetForm","doc://com.apple.pdfkit/documentation/PDFKit/PDFActionURL","doc://com.apple.pdfkit/documentation/PDFKit/PDFActionNamedName"]}],"path":"/seeAlsoSections","op":"replace"},{"value":{"declarations":[{"platforms":["iOS","iPadOS","Mac Catalyst","macOS","tvOS","visionOS"],"tokens":[{"text":"@interface","kind":"keyword"},{"text":" ","kind":"text"},{"text":"PDFActionGoTo","kind":"identifier"},{"text":" : ","kind":"text"},{"preciseIdentifier":"c:objc(cs)PDFAction","identifier":"doc://com.apple.pdfkit/documentation/PDFKit/PDFAction","text":"PDFAction","kind":"typeIdentifier"}],"languages":["occ"]}],"kind":"declarations"},"path":"/primaryContentSections/0","op":"replace"},{"op":"replace","value":"PDFActionResetForm","path":"/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFActionResetForm/title"},{"op":"replace","value":[{"kind":"identifier","text":"PDFActionResetForm"}],"path":"/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFActionResetForm/fragments"},{"op":"replace","value":[{"text":"PDFActionResetForm","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFActionResetForm/navigatorTitle"},{"op":"replace","value":"PDFActionNamed","path":"/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFActionNamed/title"},{"op":"replace","value":[{"text":"PDFActionNamed","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFActionNamed/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"PDFActionNamed"}],"path":"/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFActionNamed/navigatorTitle"},{"op":"replace","value":"PDFActionNamedName","path":"/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFActionNamedName/title"},{"op":"replace","value":[{"text":"PDFActionNamedName","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFActionNamedName/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"PDFActionNamedName"}],"path":"/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFActionNamedName/navigatorTitle"},{"op":"replace","value":"PDFActionGoTo","path":"/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFActionGoTo/title"},{"op":"replace","value":[{"kind":"identifier","text":"PDFActionGoTo"}],"path":"/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFActionGoTo/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"PDFActionGoTo"}],"path":"/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFActionGoTo/navigatorTitle"},{"path":"/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFActionRemoteGoTo/title","value":"PDFActionRemoteGoTo","op":"replace"},{"path":"/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFActionRemoteGoTo/fragments","value":[{"kind":"identifier","text":"PDFActionRemoteGoTo"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFActionRemoteGoTo/navigatorTitle","value":[{"kind":"identifier","text":"PDFActionRemoteGoTo"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFAction/title","value":"PDFAction","op":"replace"},{"path":"/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFAction/fragments","value":[{"kind":"identifier","text":"PDFAction"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFAction/navigatorTitle","value":[{"text":"PDFAction","kind":"identifier"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFActionGoTo~1destination/title","value":"destination","op":"replace"},{"path":"/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFActionGoTo~1destination/fragments","value":[{"kind":"identifier","text":"destination"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFActionURL/title","value":"PDFActionURL","op":"replace"},{"path":"/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFActionURL/fragments","value":[{"kind":"identifier","text":"PDFActionURL"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFActionURL/navigatorTitle","value":[{"text":"PDFActionURL","kind":"identifier"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFActionGoTo~1init(destination:)/title","value":"initWithDestination:","op":"replace"},{"path":"/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFActionGoTo~1init(destination:)/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithDestination:"}],"op":"replace"},{"path":"/references/doc:~1~1com.externally.resolved.symbol~1c:objc(pl)NSObject/title","value":"NSObject","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}],"diffAvailability":{"major":{"change":"modified","platform":"Xcode","versions":["16.0","16.3 beta 2"]}},"legalNotices":{"copyright":"Copyright &copy; 2025 Apple Inc. All rights reserved.","termsOfUse":"https://www.apple.com/legal/internet-services/terms/site.html","privacyPolicy":"https://www.apple.com/privacy/privacy-policy"}}