{
  "abstract": [
    {
      "code": "PDFActionNamed",
      "type": "codeVoice"
    },
    {
      "text": " defines methods used to work with actions in PDF documents, some of which are named in the Adobe PDF Specification.",
      "type": "text"
    }
  ],
  "diffAvailability": {
    "major": {
      "change": "modified",
      "platform": "Xcode",
      "versions": [
        "16.0",
        "16.3 beta 2"
      ]
    }
  },
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.pdfkit/documentation/PDFKit"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.pdfkit/documentation/PDFKit/PDFActionNamed"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(cs)PDFActionNamed",
    "fragments": [
      {
        "kind": "keyword",
        "text": "class"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "PDFActionNamed"
      }
    ],
    "modules": [
      {
        "name": "PDFKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "PDFActionNamed"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "11.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "11.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.1",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.5",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "11.0",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Class",
    "symbolKind": "class",
    "title": "PDFActionNamed"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "class"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "PDFActionNamed"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "A ",
              "type": "text"
            },
            {
              "code": "PDFActionNamed",
              "type": "codeVoice"
            },
            {
              "text": " object represents an action with a defined name, such as “Go back” or “Zoom in.”",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.pdfkit/documentation/PDFKit": {
      "abstract": [
        {
          "text": "Display and manipulate PDF documents in your apps.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.pdfkit/documentation/PDFKit",
      "kind": "symbol",
      "role": "collection",
      "title": "PDFKit",
      "type": "topic",
      "url": "/documentation/pdfkit"
    },
    "doc://com.apple.pdfkit/documentation/PDFKit/PDFAction": {
      "abstract": [
        {
          "text": "An action that is performed when, for example, a PDF annotation is activated or an outline item is clicked.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "PDFAction"
        }
      ],
      "identifier": "doc://com.apple.pdfkit/documentation/PDFKit/PDFAction",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PDFAction"
        }
      ],
      "role": "symbol",
      "title": "PDFAction",
      "type": "topic",
      "url": "/documentation/pdfkit/pdfaction"
    },
    "doc://com.apple.pdfkit/documentation/PDFKit/PDFActionGoTo": {
      "abstract": [
        {
          "code": "PDFActionGoTo",
          "type": "codeVoice"
        },
        {
          "text": ", a subclass of ",
          "type": "text"
        },
        {
          "code": "PDFAction",
          "type": "codeVoice"
        },
        {
          "text": ", defines methods for getting and setting the destination of a go-to action.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "PDFActionGoTo"
        }
      ],
      "identifier": "doc://com.apple.pdfkit/documentation/PDFKit/PDFActionGoTo",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PDFActionGoTo"
        }
      ],
      "role": "symbol",
      "title": "PDFActionGoTo",
      "type": "topic",
      "url": "/documentation/pdfkit/pdfactiongoto"
    },
    "doc://com.apple.pdfkit/documentation/PDFKit/PDFActionNamed": {
      "abstract": [
        {
          "code": "PDFActionNamed",
          "type": "codeVoice"
        },
        {
          "text": " defines methods used to work with actions in PDF documents, some of which are named in the Adobe PDF Specification.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "PDFActionNamed"
        }
      ],
      "identifier": "doc://com.apple.pdfkit/documentation/PDFKit/PDFActionNamed",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PDFActionNamed"
        }
      ],
      "role": "symbol",
      "title": "PDFActionNamed",
      "type": "topic",
      "url": "/documentation/pdfkit/pdfactionnamed"
    },
    "doc://com.apple.pdfkit/documentation/PDFKit/PDFActionNamed/init(name:)": {
      "abstract": [
        {
          "text": "Initializes the ",
          "type": "text"
        },
        {
          "code": "PDFActionName",
          "type": "codeVoice"
        },
        {
          "text": " object with the specified named action.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "name"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@PDFActionNamedName",
          "text": "PDFActionNamedName"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.pdfkit/documentation/PDFKit/PDFActionNamed/init(name:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "initWithName:"
        }
      ],
      "role": "symbol",
      "title": "init(name:)",
      "type": "topic",
      "url": "/documentation/pdfkit/pdfactionnamed/init(name:)"
    },
    "doc://com.apple.pdfkit/documentation/PDFKit/PDFActionNamed/name": {
      "abstract": [
        {
          "text": "Returns the name of the named action.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "name"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@PDFActionNamedName",
          "text": "PDFActionNamedName"
        }
      ],
      "identifier": "doc://com.apple.pdfkit/documentation/PDFKit/PDFActionNamed/name",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "name"
        }
      ],
      "role": "symbol",
      "title": "name",
      "type": "topic",
      "url": "/documentation/pdfkit/pdfactionnamed/name"
    },
    "doc://com.apple.pdfkit/documentation/PDFKit/PDFActionNamedName": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "PDFActionNamedName"
        }
      ],
      "identifier": "doc://com.apple.pdfkit/documentation/PDFKit/PDFActionNamedName",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PDFActionNamedName"
        }
      ],
      "role": "symbol",
      "title": "PDFActionNamedName",
      "type": "topic",
      "url": "/documentation/pdfkit/pdfactionnamedname"
    },
    "doc://com.apple.pdfkit/documentation/PDFKit/PDFActionRemoteGoTo": {
      "abstract": [
        {
          "code": "PDFActionRemoteGoTo",
          "type": "codeVoice"
        },
        {
          "text": ", a subclass of ",
          "type": "text"
        },
        {
          "code": "PDFAction",
          "type": "codeVoice"
        },
        {
          "text": ", defines methods for getting and setting the destination of a go-to action that targets another document.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "PDFActionRemoteGoTo"
        }
      ],
      "identifier": "doc://com.apple.pdfkit/documentation/PDFKit/PDFActionRemoteGoTo",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PDFActionRemoteGoTo"
        }
      ],
      "role": "symbol",
      "title": "PDFActionRemoteGoTo",
      "type": "topic",
      "url": "/documentation/pdfkit/pdfactionremotegoto"
    },
    "doc://com.apple.pdfkit/documentation/PDFKit/PDFActionResetForm": {
      "abstract": [
        {
          "code": "PDFActionResetForm",
          "type": "codeVoice"
        },
        {
          "text": ", a subclass of ",
          "type": "text"
        },
        {
          "code": "PDFAction",
          "type": "codeVoice"
        },
        {
          "text": ", defines methods for getting and clearing fields in a PDF form.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "PDFActionResetForm"
        }
      ],
      "identifier": "doc://com.apple.pdfkit/documentation/PDFKit/PDFActionResetForm",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PDFActionResetForm"
        }
      ],
      "role": "symbol",
      "title": "PDFActionResetForm",
      "type": "topic",
      "url": "/documentation/pdfkit/pdfactionresetform"
    },
    "doc://com.apple.pdfkit/documentation/PDFKit/PDFActionURL": {
      "abstract": [
        {
          "code": "PDFActionURL",
          "type": "codeVoice"
        },
        {
          "text": ", a subclass of ",
          "type": "text"
        },
        {
          "code": "PDFAction",
          "type": "codeVoice"
        },
        {
          "text": ", defines methods for getting and setting the URL associated with a URL action.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "PDFActionURL"
        }
      ],
      "identifier": "doc://com.apple.pdfkit/documentation/PDFKit/PDFActionURL",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PDFActionURL"
        }
      ],
      "role": "symbol",
      "title": "PDFActionURL",
      "type": "topic",
      "url": "/documentation/pdfkit/pdfactionurl"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)NSCopying": {
      "abstract": [
        {
          "text": "A protocol that objects adopt to provide functional copies of themselves.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "protocol "
        },
        {
          "kind": "identifier",
          "text": "NSCopying"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSCopying",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSCopying",
      "type": "topic",
      "url": "/documentation/foundation/nscopying"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)NSObject": {
      "abstract": [
        {
          "text": "The group of methods that are fundamental to all Objective-C objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "protocol "
        },
        {
          "kind": "identifier",
          "text": "NSObjectProtocol"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSObject",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSObjectProtocol",
      "type": "topic",
      "url": "/documentation/objectivec/nsobjectprotocol"
    },
    "doc://com.externally.resolved.symbol/s:SH": {
      "abstract": [
        {
          "text": "A type that can be hashed into a `Hasher` to produce an integer hash value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Hashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SQ",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SH",
      "kind": "symbol",
      "role": "symbol",
      "title": "Hashable",
      "type": "topic",
      "url": "/documentation/Swift/Hashable"
    },
    "doc://com.externally.resolved.symbol/s:SQ": {
      "abstract": [
        {
          "text": "A type that can be compared for value equality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SQ",
      "kind": "symbol",
      "role": "symbol",
      "title": "Equatable",
      "type": "topic",
      "url": "/documentation/Swift/Equatable"
    },
    "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP": {
      "abstract": [
        {
          "text": "A type with a customized textual representation.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CustomStringConvertible"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CustomStringConvertible",
      "type": "topic",
      "url": "/documentation/Swift/CustomStringConvertible"
    },
    "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP": {
      "abstract": [
        {
          "text": "A type with a customized textual representation suitable for debugging purposes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CustomDebugStringConvertible"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CustomDebugStringConvertible",
      "type": "topic",
      "url": "/documentation/Swift/CustomDebugStringConvertible"
    },
    "doc://com.externally.resolved.symbol/s:s7CVarArgP": {
      "abstract": [
        {
          "text": "A type whose instances can be encoded, and appropriately passed, as elements of a C `va_list`.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CVarArg"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s7CVarArgP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CVarArg",
      "type": "topic",
      "url": "/documentation/Swift/CVarArg"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.apple.pdfkit/documentation/PDFKit/PDFAction"
      ],
      "kind": "relationships",
      "title": "Inherits From",
      "type": "inheritsFrom"
    },
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:s7CVarArgP",
        "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP",
        "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP",
        "doc://com.externally.resolved.symbol/s:SQ",
        "doc://com.externally.resolved.symbol/s:SH",
        "doc://com.externally.resolved.symbol/c:objc(pl)NSCopying",
        "doc://com.externally.resolved.symbol/c:objc(pl)NSObject"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Action-Types",
      "generated": true,
      "identifiers": [
        "doc://com.apple.pdfkit/documentation/PDFKit/PDFActionGoTo",
        "doc://com.apple.pdfkit/documentation/PDFKit/PDFActionRemoteGoTo",
        "doc://com.apple.pdfkit/documentation/PDFKit/PDFActionResetForm",
        "doc://com.apple.pdfkit/documentation/PDFKit/PDFActionURL",
        "doc://com.apple.pdfkit/documentation/PDFKit/PDFActionNamedName"
      ],
      "title": "Action Types"
    }
  ],
  "topicSections": [
    {
      "anchor": "Accessing-the-Name-of-the-Action",
      "identifiers": [
        "doc://com.apple.pdfkit/documentation/PDFKit/PDFActionNamed/name"
      ],
      "title": "Accessing the Name of the Action"
    },
    {
      "anchor": "Initializing-the-Action",
      "identifiers": [
        "doc://com.apple.pdfkit/documentation/PDFKit/PDFActionNamed/init(name:)"
      ],
      "title": "Initializing the Action"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "11.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "11.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.1",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.5",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "11.0",
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Class"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "PDFActionNamed"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "class"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PDFActionNamed"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "PDFActionNamed"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.pdfkit/documentation/PDFKit"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Accessing-the-Name-of-the-Action",
              "identifiers": [
                "doc://com.apple.pdfkit/documentation/PDFKit/PDFActionNamed/name"
              ],
              "title": "Accessing the Name of the Action"
            },
            {
              "anchor": "Initializing-the-Action",
              "identifiers": [
                "doc://com.apple.pdfkit/documentation/PDFKit/PDFActionNamed/init(name:)"
              ],
              "title": "Initializing the Action"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": [
            {
              "identifiers": [
                "doc://com.apple.pdfkit/documentation/PDFKit/PDFAction"
              ],
              "kind": "relationships",
              "title": "Inherits From",
              "type": "inheritsFrom"
            },
            {
              "identifiers": [
                "doc://com.externally.resolved.symbol/c:objc(pl)NSCopying"
              ],
              "kind": "relationships",
              "title": "Conforms To",
              "type": "conformsTo"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Action-Types",
              "generated": true,
              "identifiers": [
                "doc://com.apple.pdfkit/documentation/PDFKit/PDFActionGoTo",
                "doc://com.apple.pdfkit/documentation/PDFKit/PDFActionRemoteGoTo",
                "doc://com.apple.pdfkit/documentation/PDFKit/PDFActionResetForm",
                "doc://com.apple.pdfkit/documentation/PDFKit/PDFActionURL",
                "doc://com.apple.pdfkit/documentation/PDFKit/PDFActionNamedName"
              ],
              "title": "Action Types"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "@interface"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "PDFActionNamed"
                  },
                  {
                    "kind": "text",
                    "text": " : "
                  },
                  {
                    "identifier": "doc://com.apple.pdfkit/documentation/PDFKit/PDFAction",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(cs)PDFAction",
                    "text": "PDFAction"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFAction/title",
          "value": "PDFAction"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFAction/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PDFAction"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFAction/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "PDFAction"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:objc(pl)NSObject/title",
          "value": "NSObject"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFActionRemoteGoTo/title",
          "value": "PDFActionRemoteGoTo"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFActionRemoteGoTo/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PDFActionRemoteGoTo"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFActionRemoteGoTo/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "PDFActionRemoteGoTo"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFActionNamed~1init(name:)/title",
          "value": "initWithName:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFActionNamed~1init(name:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "initWithName:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFActionNamedName/title",
          "value": "PDFActionNamedName"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFActionNamedName/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PDFActionNamedName"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFActionNamedName/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "PDFActionNamedName"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFActionURL/title",
          "value": "PDFActionURL"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFActionURL/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PDFActionURL"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFActionURL/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "PDFActionURL"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFActionGoTo/title",
          "value": "PDFActionGoTo"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFActionGoTo/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PDFActionGoTo"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFActionGoTo/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "PDFActionGoTo"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFActionNamed~1name/title",
          "value": "name"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFActionNamed~1name/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "name"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFActionNamed/title",
          "value": "PDFActionNamed"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFActionNamed/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PDFActionNamed"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFActionNamed/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "PDFActionNamed"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFActionResetForm/title",
          "value": "PDFActionResetForm"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFActionResetForm/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PDFActionResetForm"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFActionResetForm/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "PDFActionResetForm"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/pdfkit/pdfactionnamed"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/pdfkit/pdfactionnamed"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
