{
  "diffAvailability": {
    "major": {
      "change": "modified",
      "platform": "Xcode",
      "versions": [
        "16.0",
        "16.3 beta 2"
      ]
    }
  },
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.pdfkit/documentation/PDFKit"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.pdfkit/documentation/PDFKit/PDFActionNamedName"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@PDFActionNamedName",
    "fragments": [
      {
        "kind": "keyword",
        "text": "enum"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "PDFActionNamedName"
      }
    ],
    "modules": [
      {
        "name": "PDFKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "PDFActionNamedName"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "11.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "11.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.1",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.5",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "11.0",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Enumeration",
    "symbolKind": "enum",
    "title": "PDFActionNamedName"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "enum"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "PDFActionNamedName"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.pdfkit/documentation/PDFKit": {
      "abstract": [
        {
          "text": "Display and manipulate PDF documents in your apps.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.pdfkit/documentation/PDFKit",
      "kind": "symbol",
      "role": "collection",
      "title": "PDFKit",
      "type": "topic",
      "url": "/documentation/pdfkit"
    },
    "doc://com.apple.pdfkit/documentation/PDFKit/PDFActionGoTo": {
      "abstract": [
        {
          "code": "PDFActionGoTo",
          "type": "codeVoice"
        },
        {
          "text": ", a subclass of ",
          "type": "text"
        },
        {
          "code": "PDFAction",
          "type": "codeVoice"
        },
        {
          "text": ", defines methods for getting and setting the destination of a go-to action.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "PDFActionGoTo"
        }
      ],
      "identifier": "doc://com.apple.pdfkit/documentation/PDFKit/PDFActionGoTo",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PDFActionGoTo"
        }
      ],
      "role": "symbol",
      "title": "PDFActionGoTo",
      "type": "topic",
      "url": "/documentation/pdfkit/pdfactiongoto"
    },
    "doc://com.apple.pdfkit/documentation/PDFKit/PDFActionNamed": {
      "abstract": [
        {
          "code": "PDFActionNamed",
          "type": "codeVoice"
        },
        {
          "text": " defines methods used to work with actions in PDF documents, some of which are named in the Adobe PDF Specification.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "PDFActionNamed"
        }
      ],
      "identifier": "doc://com.apple.pdfkit/documentation/PDFKit/PDFActionNamed",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PDFActionNamed"
        }
      ],
      "role": "symbol",
      "title": "PDFActionNamed",
      "type": "topic",
      "url": "/documentation/pdfkit/pdfactionnamed"
    },
    "doc://com.apple.pdfkit/documentation/PDFKit/PDFActionNamedName": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "PDFActionNamedName"
        }
      ],
      "identifier": "doc://com.apple.pdfkit/documentation/PDFKit/PDFActionNamedName",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PDFActionNamedName"
        }
      ],
      "role": "symbol",
      "title": "PDFActionNamedName",
      "type": "topic",
      "url": "/documentation/pdfkit/pdfactionnamedname"
    },
    "doc://com.apple.pdfkit/documentation/PDFKit/PDFActionNamedName/find": {
      "abstract": [
        {
          "text": "The Find action.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "find"
        }
      ],
      "identifier": "doc://com.apple.pdfkit/documentation/PDFKit/PDFActionNamedName/find",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kPDFActionNamedFind"
        }
      ],
      "role": "symbol",
      "title": "PDFActionNamedName.find",
      "type": "topic",
      "url": "/documentation/pdfkit/pdfactionnamedname/find"
    },
    "doc://com.apple.pdfkit/documentation/PDFKit/PDFActionNamedName/firstPage": {
      "abstract": [
        {
          "text": "The First Page action.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "firstPage"
        }
      ],
      "identifier": "doc://com.apple.pdfkit/documentation/PDFKit/PDFActionNamedName/firstPage",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kPDFActionNamedFirstPage"
        }
      ],
      "role": "symbol",
      "title": "PDFActionNamedName.firstPage",
      "type": "topic",
      "url": "/documentation/pdfkit/pdfactionnamedname/firstpage"
    },
    "doc://com.apple.pdfkit/documentation/PDFKit/PDFActionNamedName/goBack": {
      "abstract": [
        {
          "text": "The Go Back action.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "goBack"
        }
      ],
      "identifier": "doc://com.apple.pdfkit/documentation/PDFKit/PDFActionNamedName/goBack",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kPDFActionNamedGoBack"
        }
      ],
      "role": "symbol",
      "title": "PDFActionNamedName.goBack",
      "type": "topic",
      "url": "/documentation/pdfkit/pdfactionnamedname/goback"
    },
    "doc://com.apple.pdfkit/documentation/PDFKit/PDFActionNamedName/goForward": {
      "abstract": [
        {
          "text": "The Go Forward action.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "goForward"
        }
      ],
      "identifier": "doc://com.apple.pdfkit/documentation/PDFKit/PDFActionNamedName/goForward",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kPDFActionNamedGoForward"
        }
      ],
      "role": "symbol",
      "title": "PDFActionNamedName.goForward",
      "type": "topic",
      "url": "/documentation/pdfkit/pdfactionnamedname/goforward"
    },
    "doc://com.apple.pdfkit/documentation/PDFKit/PDFActionNamedName/goToPage": {
      "abstract": [
        {
          "text": "The Go to Page action.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "goToPage"
        }
      ],
      "identifier": "doc://com.apple.pdfkit/documentation/PDFKit/PDFActionNamedName/goToPage",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kPDFActionNamedGoToPage"
        }
      ],
      "role": "symbol",
      "title": "PDFActionNamedName.goToPage",
      "type": "topic",
      "url": "/documentation/pdfkit/pdfactionnamedname/gotopage"
    },
    "doc://com.apple.pdfkit/documentation/PDFKit/PDFActionNamedName/init(rawValue:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "?("
        },
        {
          "kind": "externalParam",
          "text": "rawValue"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.pdfkit/documentation/PDFKit/PDFActionNamedName/init(rawValue:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "init(rawValue:)",
      "type": "topic",
      "url": "/documentation/pdfkit/pdfactionnamedname/init(rawvalue:)"
    },
    "doc://com.apple.pdfkit/documentation/PDFKit/PDFActionNamedName/lastPage": {
      "abstract": [
        {
          "text": "The Last Page action.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "lastPage"
        }
      ],
      "identifier": "doc://com.apple.pdfkit/documentation/PDFKit/PDFActionNamedName/lastPage",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kPDFActionNamedLastPage"
        }
      ],
      "role": "symbol",
      "title": "PDFActionNamedName.lastPage",
      "type": "topic",
      "url": "/documentation/pdfkit/pdfactionnamedname/lastpage"
    },
    "doc://com.apple.pdfkit/documentation/PDFKit/PDFActionNamedName/nextPage": {
      "abstract": [
        {
          "text": "The Next Page action.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "nextPage"
        }
      ],
      "identifier": "doc://com.apple.pdfkit/documentation/PDFKit/PDFActionNamedName/nextPage",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kPDFActionNamedNextPage"
        }
      ],
      "role": "symbol",
      "title": "PDFActionNamedName.nextPage",
      "type": "topic",
      "url": "/documentation/pdfkit/pdfactionnamedname/nextpage"
    },
    "doc://com.apple.pdfkit/documentation/PDFKit/PDFActionNamedName/none": {
      "abstract": [
        {
          "text": "The action has no name.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "none"
        }
      ],
      "identifier": "doc://com.apple.pdfkit/documentation/PDFKit/PDFActionNamedName/none",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kPDFActionNamedNone"
        }
      ],
      "role": "symbol",
      "title": "PDFActionNamedName.none",
      "type": "topic",
      "url": "/documentation/pdfkit/pdfactionnamedname/none"
    },
    "doc://com.apple.pdfkit/documentation/PDFKit/PDFActionNamedName/previousPage": {
      "abstract": [
        {
          "text": "The Previous Page action.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "previousPage"
        }
      ],
      "identifier": "doc://com.apple.pdfkit/documentation/PDFKit/PDFActionNamedName/previousPage",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kPDFActionNamedPreviousPage"
        }
      ],
      "role": "symbol",
      "title": "PDFActionNamedName.previousPage",
      "type": "topic",
      "url": "/documentation/pdfkit/pdfactionnamedname/previouspage"
    },
    "doc://com.apple.pdfkit/documentation/PDFKit/PDFActionNamedName/print": {
      "abstract": [
        {
          "text": "The Print action.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "print"
        }
      ],
      "identifier": "doc://com.apple.pdfkit/documentation/PDFKit/PDFActionNamedName/print",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kPDFActionNamedPrint"
        }
      ],
      "role": "symbol",
      "title": "PDFActionNamedName.print",
      "type": "topic",
      "url": "/documentation/pdfkit/pdfactionnamedname/print"
    },
    "doc://com.apple.pdfkit/documentation/PDFKit/PDFActionNamedName/zoomIn": {
      "abstract": [
        {
          "text": "The Zoom In action.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "zoomIn"
        }
      ],
      "identifier": "doc://com.apple.pdfkit/documentation/PDFKit/PDFActionNamedName/zoomIn",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kPDFActionNamedZoomIn"
        }
      ],
      "role": "symbol",
      "title": "PDFActionNamedName.zoomIn",
      "type": "topic",
      "url": "/documentation/pdfkit/pdfactionnamedname/zoomin"
    },
    "doc://com.apple.pdfkit/documentation/PDFKit/PDFActionNamedName/zoomOut": {
      "abstract": [
        {
          "text": "The Zoom Out action.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "zoomOut"
        }
      ],
      "identifier": "doc://com.apple.pdfkit/documentation/PDFKit/PDFActionNamedName/zoomOut",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kPDFActionNamedZoomOut"
        }
      ],
      "role": "symbol",
      "title": "PDFActionNamedName.zoomOut",
      "type": "topic",
      "url": "/documentation/pdfkit/pdfactionnamedname/zoomout"
    },
    "doc://com.apple.pdfkit/documentation/PDFKit/PDFActionRemoteGoTo": {
      "abstract": [
        {
          "code": "PDFActionRemoteGoTo",
          "type": "codeVoice"
        },
        {
          "text": ", a subclass of ",
          "type": "text"
        },
        {
          "code": "PDFAction",
          "type": "codeVoice"
        },
        {
          "text": ", defines methods for getting and setting the destination of a go-to action that targets another document.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "PDFActionRemoteGoTo"
        }
      ],
      "identifier": "doc://com.apple.pdfkit/documentation/PDFKit/PDFActionRemoteGoTo",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PDFActionRemoteGoTo"
        }
      ],
      "role": "symbol",
      "title": "PDFActionRemoteGoTo",
      "type": "topic",
      "url": "/documentation/pdfkit/pdfactionremotegoto"
    },
    "doc://com.apple.pdfkit/documentation/PDFKit/PDFActionResetForm": {
      "abstract": [
        {
          "code": "PDFActionResetForm",
          "type": "codeVoice"
        },
        {
          "text": ", a subclass of ",
          "type": "text"
        },
        {
          "code": "PDFAction",
          "type": "codeVoice"
        },
        {
          "text": ", defines methods for getting and clearing fields in a PDF form.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "PDFActionResetForm"
        }
      ],
      "identifier": "doc://com.apple.pdfkit/documentation/PDFKit/PDFActionResetForm",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PDFActionResetForm"
        }
      ],
      "role": "symbol",
      "title": "PDFActionResetForm",
      "type": "topic",
      "url": "/documentation/pdfkit/pdfactionresetform"
    },
    "doc://com.apple.pdfkit/documentation/PDFKit/PDFActionURL": {
      "abstract": [
        {
          "code": "PDFActionURL",
          "type": "codeVoice"
        },
        {
          "text": ", a subclass of ",
          "type": "text"
        },
        {
          "code": "PDFAction",
          "type": "codeVoice"
        },
        {
          "text": ", defines methods for getting and setting the URL associated with a URL action.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "PDFActionURL"
        }
      ],
      "identifier": "doc://com.apple.pdfkit/documentation/PDFKit/PDFActionURL",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PDFActionURL"
        }
      ],
      "role": "symbol",
      "title": "PDFActionURL",
      "type": "topic",
      "url": "/documentation/pdfkit/pdfactionurl"
    },
    "doc://com.externally.resolved.symbol/s:SH": {
      "abstract": [
        {
          "text": "A type that can be hashed into a `Hasher` to produce an integer hash value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Hashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SQ",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SH",
      "kind": "symbol",
      "role": "symbol",
      "title": "Hashable",
      "type": "topic",
      "url": "/documentation/Swift/Hashable"
    },
    "doc://com.externally.resolved.symbol/s:SQ": {
      "abstract": [
        {
          "text": "A type that can be compared for value equality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SQ",
      "kind": "symbol",
      "role": "symbol",
      "title": "Equatable",
      "type": "topic",
      "url": "/documentation/Swift/Equatable"
    },
    "doc://com.externally.resolved.symbol/s:SY": {
      "abstract": [
        {
          "text": "A type that can be converted to and from an associated raw value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "RawRepresentable"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SY8RawValueQa",
          "text": "RawValue"
        },
        {
          "kind": "text",
          "text": ">"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SY",
      "kind": "symbol",
      "role": "symbol",
      "title": "RawRepresentable",
      "type": "topic",
      "url": "/documentation/Swift/RawRepresentable"
    },
    "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BitwiseCopyable"
        },
        {
          "kind": "text",
          "text": " : ~Escapable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "BitwiseCopyable",
      "type": "topic",
      "url": "/documentation/Swift/BitwiseCopyable"
    },
    "doc://com.externally.resolved.symbol/s:s8SendableP": {
      "abstract": [
        {
          "text": "A thread-safe type whose values can be shared across arbitrary concurrent contexts without introducing a risk of data races.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Sendable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s8SendableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "Sendable",
      "type": "topic",
      "url": "/documentation/Swift/Sendable"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
        "doc://com.externally.resolved.symbol/s:SQ",
        "doc://com.externally.resolved.symbol/s:SH",
        "doc://com.externally.resolved.symbol/s:SY",
        "doc://com.externally.resolved.symbol/s:s8SendableP"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Action-Types",
      "generated": true,
      "identifiers": [
        "doc://com.apple.pdfkit/documentation/PDFKit/PDFActionGoTo",
        "doc://com.apple.pdfkit/documentation/PDFKit/PDFActionNamed",
        "doc://com.apple.pdfkit/documentation/PDFKit/PDFActionRemoteGoTo",
        "doc://com.apple.pdfkit/documentation/PDFKit/PDFActionResetForm",
        "doc://com.apple.pdfkit/documentation/PDFKit/PDFActionURL"
      ],
      "title": "Action Types"
    }
  ],
  "topicSections": [
    {
      "anchor": "Constants",
      "identifiers": [
        "doc://com.apple.pdfkit/documentation/PDFKit/PDFActionNamedName/find",
        "doc://com.apple.pdfkit/documentation/PDFKit/PDFActionNamedName/firstPage",
        "doc://com.apple.pdfkit/documentation/PDFKit/PDFActionNamedName/goBack",
        "doc://com.apple.pdfkit/documentation/PDFKit/PDFActionNamedName/goForward",
        "doc://com.apple.pdfkit/documentation/PDFKit/PDFActionNamedName/goToPage",
        "doc://com.apple.pdfkit/documentation/PDFKit/PDFActionNamedName/lastPage",
        "doc://com.apple.pdfkit/documentation/PDFKit/PDFActionNamedName/nextPage",
        "doc://com.apple.pdfkit/documentation/PDFKit/PDFActionNamedName/none",
        "doc://com.apple.pdfkit/documentation/PDFKit/PDFActionNamedName/previousPage",
        "doc://com.apple.pdfkit/documentation/PDFKit/PDFActionNamedName/print",
        "doc://com.apple.pdfkit/documentation/PDFKit/PDFActionNamedName/zoomIn",
        "doc://com.apple.pdfkit/documentation/PDFKit/PDFActionNamedName/zoomOut"
      ],
      "title": "Constants"
    },
    {
      "anchor": "Initializers",
      "generated": true,
      "identifiers": [
        "doc://com.apple.pdfkit/documentation/PDFKit/PDFActionNamedName/init(rawValue:)"
      ],
      "title": "Initializers"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "11.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "11.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "11.0",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.4",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "PDFActionNamedName"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "enum"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PDFActionNamedName"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "PDFActionNamedName"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.pdfkit/documentation/PDFKit"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Constants",
              "identifiers": [
                "doc://com.apple.pdfkit/documentation/PDFKit/PDFActionNamedName/find",
                "doc://com.apple.pdfkit/documentation/PDFKit/PDFActionNamedName/firstPage",
                "doc://com.apple.pdfkit/documentation/PDFKit/PDFActionNamedName/goBack",
                "doc://com.apple.pdfkit/documentation/PDFKit/PDFActionNamedName/goForward",
                "doc://com.apple.pdfkit/documentation/PDFKit/PDFActionNamedName/goToPage",
                "doc://com.apple.pdfkit/documentation/PDFKit/PDFActionNamedName/lastPage",
                "doc://com.apple.pdfkit/documentation/PDFKit/PDFActionNamedName/nextPage",
                "doc://com.apple.pdfkit/documentation/PDFKit/PDFActionNamedName/none",
                "doc://com.apple.pdfkit/documentation/PDFKit/PDFActionNamedName/previousPage",
                "doc://com.apple.pdfkit/documentation/PDFKit/PDFActionNamedName/print",
                "doc://com.apple.pdfkit/documentation/PDFKit/PDFActionNamedName/zoomIn",
                "doc://com.apple.pdfkit/documentation/PDFKit/PDFActionNamedName/zoomOut"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Action-Types",
              "generated": true,
              "identifiers": [
                "doc://com.apple.pdfkit/documentation/PDFKit/PDFActionGoTo",
                "doc://com.apple.pdfkit/documentation/PDFKit/PDFActionNamed",
                "doc://com.apple.pdfkit/documentation/PDFKit/PDFActionRemoteGoTo",
                "doc://com.apple.pdfkit/documentation/PDFKit/PDFActionResetForm",
                "doc://com.apple.pdfkit/documentation/PDFKit/PDFActionURL"
              ],
              "title": "Action Types"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "enum"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "PDFActionNamedName"
                  },
                  {
                    "kind": "text",
                    "text": " : "
                  },
                  {
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@NSInteger",
                    "text": "NSInteger"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFActionResetForm/title",
          "value": "PDFActionResetForm"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFActionResetForm/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PDFActionResetForm"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFActionResetForm/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "PDFActionResetForm"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFActionRemoteGoTo/title",
          "value": "PDFActionRemoteGoTo"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFActionRemoteGoTo/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PDFActionRemoteGoTo"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFActionRemoteGoTo/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "PDFActionRemoteGoTo"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFActionGoTo/title",
          "value": "PDFActionGoTo"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFActionGoTo/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PDFActionGoTo"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFActionGoTo/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "PDFActionGoTo"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFActionURL/title",
          "value": "PDFActionURL"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFActionURL/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PDFActionURL"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFActionURL/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "PDFActionURL"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFActionNamedName~1zoomIn/title",
          "value": "kPDFActionNamedZoomIn"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFActionNamedName~1zoomIn/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kPDFActionNamedZoomIn"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFActionNamed/title",
          "value": "PDFActionNamed"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFActionNamed/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PDFActionNamed"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFActionNamed/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "PDFActionNamed"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFActionNamedName~1nextPage/title",
          "value": "kPDFActionNamedNextPage"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFActionNamedName~1nextPage/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kPDFActionNamedNextPage"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFActionNamedName~1none/title",
          "value": "kPDFActionNamedNone"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFActionNamedName~1none/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kPDFActionNamedNone"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFActionNamedName~1goBack/title",
          "value": "kPDFActionNamedGoBack"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFActionNamedName~1goBack/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kPDFActionNamedGoBack"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFActionNamedName~1zoomOut/title",
          "value": "kPDFActionNamedZoomOut"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFActionNamedName~1zoomOut/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kPDFActionNamedZoomOut"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFActionNamedName~1print/title",
          "value": "kPDFActionNamedPrint"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFActionNamedName~1print/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kPDFActionNamedPrint"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFActionNamedName~1find/title",
          "value": "kPDFActionNamedFind"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFActionNamedName~1find/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kPDFActionNamedFind"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFActionNamedName~1firstPage/title",
          "value": "kPDFActionNamedFirstPage"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFActionNamedName~1firstPage/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kPDFActionNamedFirstPage"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFActionNamedName~1previousPage/title",
          "value": "kPDFActionNamedPreviousPage"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFActionNamedName~1previousPage/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kPDFActionNamedPreviousPage"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFActionNamedName~1lastPage/title",
          "value": "kPDFActionNamedLastPage"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFActionNamedName~1lastPage/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kPDFActionNamedLastPage"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFActionNamedName~1goToPage/title",
          "value": "kPDFActionNamedGoToPage"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFActionNamedName~1goToPage/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kPDFActionNamedGoToPage"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFActionNamedName~1goForward/title",
          "value": "kPDFActionNamedGoForward"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFActionNamedName~1goForward/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kPDFActionNamedGoForward"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFActionNamedName/title",
          "value": "PDFActionNamedName"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFActionNamedName/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PDFActionNamedName"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFActionNamedName/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "PDFActionNamedName"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/pdfkit/pdfactionnamedname"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/pdfkit/pdfactionnamedname"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
