{
  "diffAvailability": {
    "major": {
      "change": "modified",
      "platform": "Xcode",
      "versions": [
        "16.0",
        "16.3 beta 2"
      ]
    }
  },
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.pdfkit/documentation/PDFKit"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.pdfkit/documentation/PDFKit/PDFAnnotationHighlightingMode"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@T@PDFAnnotationHighlightingMode",
    "fragments": [
      {
        "kind": "keyword",
        "text": "struct"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "PDFAnnotationHighlightingMode"
      }
    ],
    "modules": [
      {
        "name": "PDFKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "PDFAnnotationHighlightingMode"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "11.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "11.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "11.0",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.4",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Structure",
    "symbolKind": "struct",
    "title": "PDFAnnotationHighlightingMode"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "struct"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "PDFAnnotationHighlightingMode"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.pdfkit/documentation/PDFKit": {
      "abstract": [
        {
          "text": "Display and manipulate PDF documents in your apps.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.pdfkit/documentation/PDFKit",
      "kind": "symbol",
      "role": "collection",
      "title": "PDFKit",
      "type": "topic",
      "url": "/documentation/pdfkit"
    },
    "doc://com.apple.pdfkit/documentation/PDFKit/PDFAnnotationHighlightingMode": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "PDFAnnotationHighlightingMode"
        }
      ],
      "identifier": "doc://com.apple.pdfkit/documentation/PDFKit/PDFAnnotationHighlightingMode",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PDFAnnotationHighlightingMode"
        }
      ],
      "role": "symbol",
      "title": "PDFAnnotationHighlightingMode",
      "type": "topic",
      "url": "/documentation/pdfkit/pdfannotationhighlightingmode"
    },
    "doc://com.apple.pdfkit/documentation/PDFKit/PDFAnnotationHighlightingMode/init(rawValue:)": {
      "abstract": [
        {
          "text": "Creates a highlight mode using the specified raw string value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "rawValue"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.pdfkit/documentation/PDFKit/PDFAnnotationHighlightingMode/init(rawValue:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "init(rawValue:)",
      "type": "topic",
      "url": "/documentation/pdfkit/pdfannotationhighlightingmode/init(rawvalue:)"
    },
    "doc://com.apple.pdfkit/documentation/PDFKit/PDFAnnotationHighlightingMode/invert": {
      "abstract": [
        {
          "text": "A highlight mode that inverts the content of the annotation.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "invert"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@PDFAnnotationHighlightingMode",
          "text": "PDFAnnotationHighlightingMode"
        }
      ],
      "identifier": "doc://com.apple.pdfkit/documentation/PDFKit/PDFAnnotationHighlightingMode/invert",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PDFAnnotationHighlightingModeInvert"
        }
      ],
      "role": "symbol",
      "title": "invert",
      "type": "topic",
      "url": "/documentation/pdfkit/pdfannotationhighlightingmode/invert"
    },
    "doc://com.apple.pdfkit/documentation/PDFKit/PDFAnnotationHighlightingMode/none": {
      "abstract": [
        {
          "text": "A highlight mode that doesn’t change the appearance of the annotation.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "none"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@PDFAnnotationHighlightingMode",
          "text": "PDFAnnotationHighlightingMode"
        }
      ],
      "identifier": "doc://com.apple.pdfkit/documentation/PDFKit/PDFAnnotationHighlightingMode/none",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PDFAnnotationHighlightingModeNone"
        }
      ],
      "role": "symbol",
      "title": "none",
      "type": "topic",
      "url": "/documentation/pdfkit/pdfannotationhighlightingmode/none"
    },
    "doc://com.apple.pdfkit/documentation/PDFKit/PDFAnnotationHighlightingMode/outline": {
      "abstract": [
        {
          "text": "A highlight mode that inverts the annotation’s border.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "outline"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@PDFAnnotationHighlightingMode",
          "text": "PDFAnnotationHighlightingMode"
        }
      ],
      "identifier": "doc://com.apple.pdfkit/documentation/PDFKit/PDFAnnotationHighlightingMode/outline",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PDFAnnotationHighlightingModeOutline"
        }
      ],
      "role": "symbol",
      "title": "outline",
      "type": "topic",
      "url": "/documentation/pdfkit/pdfannotationhighlightingmode/outline"
    },
    "doc://com.apple.pdfkit/documentation/PDFKit/PDFAnnotationHighlightingMode/push": {
      "abstract": [
        {
          "text": "A highlight mode that renders a pressed appearance for the annotation.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "push"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@PDFAnnotationHighlightingMode",
          "text": "PDFAnnotationHighlightingMode"
        }
      ],
      "identifier": "doc://com.apple.pdfkit/documentation/PDFKit/PDFAnnotationHighlightingMode/push",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PDFAnnotationHighlightingModePush"
        }
      ],
      "role": "symbol",
      "title": "push",
      "type": "topic",
      "url": "/documentation/pdfkit/pdfannotationhighlightingmode/push"
    },
    "doc://com.apple.pdfkit/documentation/PDFKit/PDFAnnotationKey/appearanceDictionary": {
      "abstract": [
        {
          "text": "A dictionary that contains properties for controlling the annotation’s visual appearance.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "appearanceDictionary"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@PDFAnnotationKey",
          "text": "PDFAnnotationKey"
        }
      ],
      "identifier": "doc://com.apple.pdfkit/documentation/PDFKit/PDFAnnotationKey/appearanceDictionary",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PDFAnnotationKeyAppearanceDictionary"
        }
      ],
      "role": "symbol",
      "title": "appearanceDictionary",
      "type": "topic",
      "url": "/documentation/pdfkit/pdfannotationkey/appearancedictionary"
    },
    "doc://com.apple.pdfkit/documentation/PDFKit/PDFAnnotationKey/appearanceState": {
      "abstract": [
        {
          "text": "A string that specifies the appearance stream for the annotation.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "appearanceState"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@PDFAnnotationKey",
          "text": "PDFAnnotationKey"
        }
      ],
      "identifier": "doc://com.apple.pdfkit/documentation/PDFKit/PDFAnnotationKey/appearanceState",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PDFAnnotationKeyAppearanceState"
        }
      ],
      "role": "symbol",
      "title": "appearanceState",
      "type": "topic",
      "url": "/documentation/pdfkit/pdfannotationkey/appearancestate"
    },
    "doc://com.apple.pdfkit/documentation/PDFKit/PDFAnnotationKey/border": {
      "abstract": [
        {
          "text": "An array of integers or border objects that describes the border of the annotation.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "border"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@PDFAnnotationKey",
          "text": "PDFAnnotationKey"
        }
      ],
      "identifier": "doc://com.apple.pdfkit/documentation/PDFKit/PDFAnnotationKey/border",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PDFAnnotationKeyBorder"
        }
      ],
      "role": "symbol",
      "title": "border",
      "type": "topic",
      "url": "/documentation/pdfkit/pdfannotationkey/border"
    },
    "doc://com.apple.pdfkit/documentation/PDFKit/PDFAnnotationKey/borderStyle": {
      "abstract": [
        {
          "text": "A dictionary that contains the properties of the annotation’s border.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "borderStyle"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@PDFAnnotationKey",
          "text": "PDFAnnotationKey"
        }
      ],
      "identifier": "doc://com.apple.pdfkit/documentation/PDFKit/PDFAnnotationKey/borderStyle",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PDFAnnotationKeyBorderStyle"
        }
      ],
      "role": "symbol",
      "title": "borderStyle",
      "type": "topic",
      "url": "/documentation/pdfkit/pdfannotationkey/borderstyle"
    },
    "doc://com.apple.pdfkit/documentation/PDFKit/PDFAnnotationKey/color": {
      "abstract": [
        {
          "text": "An array of floats or a color object that specifies the annotation’s color.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "color"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@PDFAnnotationKey",
          "text": "PDFAnnotationKey"
        }
      ],
      "identifier": "doc://com.apple.pdfkit/documentation/PDFKit/PDFAnnotationKey/color",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PDFAnnotationKeyColor"
        }
      ],
      "role": "symbol",
      "title": "color",
      "type": "topic",
      "url": "/documentation/pdfkit/pdfannotationkey/color"
    },
    "doc://com.apple.pdfkit/documentation/PDFKit/PDFAnnotationKey/defaultAppearance": {
      "abstract": [
        {
          "text": "A string value a free text annotation uses to format the text.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "defaultAppearance"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@PDFAnnotationKey",
          "text": "PDFAnnotationKey"
        }
      ],
      "identifier": "doc://com.apple.pdfkit/documentation/PDFKit/PDFAnnotationKey/defaultAppearance",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PDFAnnotationKeyDefaultAppearance"
        }
      ],
      "role": "symbol",
      "title": "defaultAppearance",
      "type": "topic",
      "url": "/documentation/pdfkit/pdfannotationkey/defaultappearance"
    },
    "doc://com.apple.pdfkit/documentation/PDFKit/PDFAnnotationKey/highlightingMode": {
      "abstract": [
        {
          "text": "A string value that defines the way an annotation highlights when the user activates it, such as when clicking or tapping a link.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "highlightingMode"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@PDFAnnotationKey",
          "text": "PDFAnnotationKey"
        }
      ],
      "identifier": "doc://com.apple.pdfkit/documentation/PDFKit/PDFAnnotationKey/highlightingMode",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PDFAnnotationKeyHighlightingMode"
        }
      ],
      "role": "symbol",
      "title": "highlightingMode",
      "type": "topic",
      "url": "/documentation/pdfkit/pdfannotationkey/highlightingmode"
    },
    "doc://com.apple.pdfkit/documentation/PDFKit/PDFAnnotationKey/iconName": {
      "abstract": [
        {
          "text": "A string value that specifies the name of an icon for a text or stamp annotation.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "iconName"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@PDFAnnotationKey",
          "text": "PDFAnnotationKey"
        }
      ],
      "identifier": "doc://com.apple.pdfkit/documentation/PDFKit/PDFAnnotationKey/iconName",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PDFAnnotationKeyIconName"
        }
      ],
      "role": "symbol",
      "title": "iconName",
      "type": "topic",
      "url": "/documentation/pdfkit/pdfannotationkey/iconname"
    },
    "doc://com.apple.pdfkit/documentation/PDFKit/PDFAnnotationKey/interiorColor": {
      "abstract": [
        {
          "text": "An array of floating point values or a PDF color object that annotations use to fill interior space, such as line endings, squares, or circles.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "interiorColor"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@PDFAnnotationKey",
          "text": "PDFAnnotationKey"
        }
      ],
      "identifier": "doc://com.apple.pdfkit/documentation/PDFKit/PDFAnnotationKey/interiorColor",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PDFAnnotationKeyInteriorColor"
        }
      ],
      "role": "symbol",
      "title": "interiorColor",
      "type": "topic",
      "url": "/documentation/pdfkit/pdfannotationkey/interiorcolor"
    },
    "doc://com.apple.pdfkit/documentation/PDFKit/PDFAnnotationKey/quadding": {
      "abstract": [
        {
          "text": "An integer value that specifies left, right, or center justification.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "quadding"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@PDFAnnotationKey",
          "text": "PDFAnnotationKey"
        }
      ],
      "identifier": "doc://com.apple.pdfkit/documentation/PDFKit/PDFAnnotationKey/quadding",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PDFAnnotationKeyQuadding"
        }
      ],
      "role": "symbol",
      "title": "quadding",
      "type": "topic",
      "url": "/documentation/pdfkit/pdfannotationkey/quadding"
    },
    "doc://com.externally.resolved.symbol/c:objc(cs)NSString": {
      "abstract": [
        {
          "text": "A static, plain-text Unicode string object which you use when you need reference semantics or other Foundation-specific behavior. ",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "class "
        },
        {
          "kind": "identifier",
          "text": "NSString"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSString",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSString",
      "type": "topic",
      "url": "/documentation/foundation/nsstring"
    },
    "doc://com.externally.resolved.symbol/s:SH": {
      "abstract": [
        {
          "text": "A type that can be hashed into a `Hasher` to produce an integer hash value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Hashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SQ",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SH",
      "kind": "symbol",
      "role": "symbol",
      "title": "Hashable",
      "type": "topic",
      "url": "/documentation/Swift/Hashable"
    },
    "doc://com.externally.resolved.symbol/s:SQ": {
      "abstract": [
        {
          "text": "A type that can be compared for value equality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SQ",
      "kind": "symbol",
      "role": "symbol",
      "title": "Equatable",
      "type": "topic",
      "url": "/documentation/Swift/Equatable"
    },
    "doc://com.externally.resolved.symbol/s:SY": {
      "abstract": [
        {
          "text": "A type that can be converted to and from an associated raw value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "RawRepresentable"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SY8RawValueQa",
          "text": "RawValue"
        },
        {
          "kind": "text",
          "text": ">"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SY",
      "kind": "symbol",
      "role": "symbol",
      "title": "RawRepresentable",
      "type": "topic",
      "url": "/documentation/Swift/RawRepresentable"
    },
    "doc://com.externally.resolved.symbol/s:s8SendableP": {
      "abstract": [
        {
          "text": "A thread-safe type whose values can be shared across arbitrary concurrent contexts without introducing a risk of data races.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Sendable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s8SendableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "Sendable",
      "type": "topic",
      "url": "/documentation/Swift/Sendable"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:SQ",
        "doc://com.externally.resolved.symbol/s:SH",
        "doc://com.externally.resolved.symbol/s:SY",
        "doc://com.externally.resolved.symbol/s:s8SendableP"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Configuring-Annotation-Appearance",
      "generated": true,
      "identifiers": [
        "doc://com.apple.pdfkit/documentation/PDFKit/PDFAnnotationKey/appearanceDictionary",
        "doc://com.apple.pdfkit/documentation/PDFKit/PDFAnnotationKey/appearanceState",
        "doc://com.apple.pdfkit/documentation/PDFKit/PDFAnnotationKey/border",
        "doc://com.apple.pdfkit/documentation/PDFKit/PDFAnnotationKey/borderStyle",
        "doc://com.apple.pdfkit/documentation/PDFKit/PDFAnnotationKey/color",
        "doc://com.apple.pdfkit/documentation/PDFKit/PDFAnnotationKey/defaultAppearance",
        "doc://com.apple.pdfkit/documentation/PDFKit/PDFAnnotationKey/highlightingMode",
        "doc://com.apple.pdfkit/documentation/PDFKit/PDFAnnotationKey/iconName",
        "doc://com.apple.pdfkit/documentation/PDFKit/PDFAnnotationKey/interiorColor",
        "doc://com.apple.pdfkit/documentation/PDFKit/PDFAnnotationKey/quadding"
      ],
      "title": "Configuring Annotation Appearance"
    }
  ],
  "topicSections": [
    {
      "anchor": "Choosing-a-Highlight-Mode",
      "identifiers": [
        "doc://com.apple.pdfkit/documentation/PDFKit/PDFAnnotationHighlightingMode/invert",
        "doc://com.apple.pdfkit/documentation/PDFKit/PDFAnnotationHighlightingMode/none",
        "doc://com.apple.pdfkit/documentation/PDFKit/PDFAnnotationHighlightingMode/outline",
        "doc://com.apple.pdfkit/documentation/PDFKit/PDFAnnotationHighlightingMode/push"
      ],
      "title": "Choosing a Highlight Mode"
    },
    {
      "anchor": "Creating-an-Annotation-Highlight-Mode",
      "identifiers": [
        "doc://com.apple.pdfkit/documentation/PDFKit/PDFAnnotationHighlightingMode/init(rawValue:)"
      ],
      "title": "Creating an Annotation Highlight Mode"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "11.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "11.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "11.0",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.4",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Type Alias"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "PDFAnnotationHighlightingMode"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "typealias"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PDFAnnotationHighlightingMode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "PDFAnnotationHighlightingMode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.pdfkit/documentation/PDFKit"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Choosing-a-Highlight-Mode",
              "identifiers": [
                "doc://com.apple.pdfkit/documentation/PDFKit/PDFAnnotationHighlightingMode/invert",
                "doc://com.apple.pdfkit/documentation/PDFKit/PDFAnnotationHighlightingMode/none",
                "doc://com.apple.pdfkit/documentation/PDFKit/PDFAnnotationHighlightingMode/outline",
                "doc://com.apple.pdfkit/documentation/PDFKit/PDFAnnotationHighlightingMode/push"
              ],
              "title": "Choosing a Highlight Mode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Configuring-Annotation-Appearance",
              "generated": true,
              "identifiers": [
                "doc://com.apple.pdfkit/documentation/PDFKit/PDFAnnotationKey/appearanceDictionary",
                "doc://com.apple.pdfkit/documentation/PDFKit/PDFAnnotationKey/appearanceState",
                "doc://com.apple.pdfkit/documentation/PDFKit/PDFAnnotationKey/border",
                "doc://com.apple.pdfkit/documentation/PDFKit/PDFAnnotationKey/borderStyle",
                "doc://com.apple.pdfkit/documentation/PDFKit/PDFAnnotationKey/color",
                "doc://com.apple.pdfkit/documentation/PDFKit/PDFAnnotationKey/defaultAppearance",
                "doc://com.apple.pdfkit/documentation/PDFKit/PDFAnnotationKey/highlightingMode",
                "doc://com.apple.pdfkit/documentation/PDFKit/PDFAnnotationKey/iconName",
                "doc://com.apple.pdfkit/documentation/PDFKit/PDFAnnotationKey/interiorColor",
                "doc://com.apple.pdfkit/documentation/PDFKit/PDFAnnotationKey/quadding"
              ],
              "title": "Configuring Annotation Appearance"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "typedef"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSString",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(cs)NSString",
                    "text": "NSString"
                  },
                  {
                    "kind": "text",
                    "text": " * "
                  },
                  {
                    "kind": "keyword",
                    "text": "const"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "PDFAnnotationHighlightingMode"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFAnnotationKey~1color/title",
          "value": "PDFAnnotationKeyColor"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFAnnotationKey~1color/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PDFAnnotationKeyColor"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFAnnotationHighlightingMode/title",
          "value": "PDFAnnotationHighlightingMode"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFAnnotationHighlightingMode/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PDFAnnotationHighlightingMode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFAnnotationHighlightingMode/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "PDFAnnotationHighlightingMode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFAnnotationKey~1defaultAppearance/title",
          "value": "PDFAnnotationKeyDefaultAppearance"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFAnnotationKey~1defaultAppearance/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PDFAnnotationKeyDefaultAppearance"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFAnnotationKey~1quadding/title",
          "value": "PDFAnnotationKeyQuadding"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFAnnotationKey~1quadding/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PDFAnnotationKeyQuadding"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFAnnotationKey~1appearanceDictionary/title",
          "value": "PDFAnnotationKeyAppearanceDictionary"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFAnnotationKey~1appearanceDictionary/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PDFAnnotationKeyAppearanceDictionary"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFAnnotationKey~1borderStyle/title",
          "value": "PDFAnnotationKeyBorderStyle"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFAnnotationKey~1borderStyle/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PDFAnnotationKeyBorderStyle"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFAnnotationKey~1border/title",
          "value": "PDFAnnotationKeyBorder"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFAnnotationKey~1border/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PDFAnnotationKeyBorder"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFAnnotationHighlightingMode~1none/title",
          "value": "PDFAnnotationHighlightingModeNone"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFAnnotationHighlightingMode~1none/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PDFAnnotationHighlightingModeNone"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFAnnotationKey~1appearanceState/title",
          "value": "PDFAnnotationKeyAppearanceState"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFAnnotationKey~1appearanceState/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PDFAnnotationKeyAppearanceState"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFAnnotationKey~1iconName/title",
          "value": "PDFAnnotationKeyIconName"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFAnnotationKey~1iconName/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PDFAnnotationKeyIconName"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFAnnotationHighlightingMode~1push/title",
          "value": "PDFAnnotationHighlightingModePush"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFAnnotationHighlightingMode~1push/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PDFAnnotationHighlightingModePush"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:objc(cs)NSString/abstract",
          "value": [
            {
              "text": "A static, plain-text Unicode string object.",
              "type": "text"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFAnnotationHighlightingMode~1invert/title",
          "value": "PDFAnnotationHighlightingModeInvert"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFAnnotationHighlightingMode~1invert/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PDFAnnotationHighlightingModeInvert"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFAnnotationHighlightingMode~1outline/title",
          "value": "PDFAnnotationHighlightingModeOutline"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFAnnotationHighlightingMode~1outline/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PDFAnnotationHighlightingModeOutline"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFAnnotationKey~1highlightingMode/title",
          "value": "PDFAnnotationKeyHighlightingMode"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFAnnotationKey~1highlightingMode/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PDFAnnotationKeyHighlightingMode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFAnnotationKey~1interiorColor/title",
          "value": "PDFAnnotationKeyInteriorColor"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFAnnotationKey~1interiorColor/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PDFAnnotationKeyInteriorColor"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/pdfkit/pdfannotationhighlightingmode"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/pdfkit/pdfannotationhighlightingmode"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
