{
  "abstract": [
    {
      "text": "The mouse position over PDF view areas.",
      "type": "text"
    }
  ],
  "diffAvailability": {
    "major": {
      "change": "modified",
      "platform": "Xcode",
      "versions": [
        "16.0",
        "16.3 beta 2"
      ]
    }
  },
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.pdfkit/documentation/PDFKit"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.pdfkit/documentation/PDFKit/PDFAreaOfInterest"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@PDFAreaOfInterest",
    "fragments": [
      {
        "kind": "keyword",
        "text": "struct"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "PDFAreaOfInterest"
      }
    ],
    "modules": [
      {
        "name": "PDFKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "PDFAreaOfInterest"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "11.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "11.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.1",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.4",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "11.0",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Structure",
    "symbolKind": "struct",
    "title": "PDFAreaOfInterest"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "struct"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "PDFAreaOfInterest"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "These constants are components of a bit field and may be combined arbitrarily.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.pdfkit/documentation/PDFKit": {
      "abstract": [
        {
          "text": "Display and manipulate PDF documents in your apps.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.pdfkit/documentation/PDFKit",
      "kind": "symbol",
      "role": "collection",
      "title": "PDFKit",
      "type": "topic",
      "url": "/documentation/pdfkit"
    },
    "doc://com.apple.pdfkit/documentation/PDFKit/PDFAreaOfInterest": {
      "abstract": [
        {
          "text": "The mouse position over PDF view areas.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "PDFAreaOfInterest"
        }
      ],
      "identifier": "doc://com.apple.pdfkit/documentation/PDFKit/PDFAreaOfInterest",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PDFAreaOfInterest"
        }
      ],
      "role": "symbol",
      "title": "PDFAreaOfInterest",
      "type": "topic",
      "url": "/documentation/pdfkit/pdfareaofinterest"
    },
    "doc://com.apple.pdfkit/documentation/PDFKit/PDFAreaOfInterest/annotationArea": {
      "abstract": [
        {
          "text": "The mouse is over an annotation.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "annotationArea"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@PDFAreaOfInterest",
          "text": "PDFAreaOfInterest"
        }
      ],
      "identifier": "doc://com.apple.pdfkit/documentation/PDFKit/PDFAreaOfInterest/annotationArea",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kPDFAnnotationArea"
        }
      ],
      "role": "symbol",
      "title": "annotationArea",
      "type": "topic",
      "url": "/documentation/pdfkit/pdfareaofinterest/annotationarea"
    },
    "doc://com.apple.pdfkit/documentation/PDFKit/PDFAreaOfInterest/anyArea": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "anyArea"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@PDFAreaOfInterest",
          "text": "PDFAreaOfInterest"
        }
      ],
      "identifier": "doc://com.apple.pdfkit/documentation/PDFKit/PDFAreaOfInterest/anyArea",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kPDFAnyArea"
        }
      ],
      "role": "symbol",
      "title": "anyArea",
      "type": "topic",
      "url": "/documentation/pdfkit/pdfareaofinterest/anyarea"
    },
    "doc://com.apple.pdfkit/documentation/PDFKit/PDFAreaOfInterest/controlArea": {
      "abstract": [
        {
          "text": "The mouse is over a control.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "controlArea"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@PDFAreaOfInterest",
          "text": "PDFAreaOfInterest"
        }
      ],
      "identifier": "doc://com.apple.pdfkit/documentation/PDFKit/PDFAreaOfInterest/controlArea",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kPDFControlArea"
        }
      ],
      "role": "symbol",
      "title": "controlArea",
      "type": "topic",
      "url": "/documentation/pdfkit/pdfareaofinterest/controlarea"
    },
    "doc://com.apple.pdfkit/documentation/PDFKit/PDFAreaOfInterest/iconArea": {
      "abstract": [
        {
          "text": "The mouse is over an icon.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "iconArea"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@PDFAreaOfInterest",
          "text": "PDFAreaOfInterest"
        }
      ],
      "identifier": "doc://com.apple.pdfkit/documentation/PDFKit/PDFAreaOfInterest/iconArea",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kPDFIconArea"
        }
      ],
      "role": "symbol",
      "title": "iconArea",
      "type": "topic",
      "url": "/documentation/pdfkit/pdfareaofinterest/iconarea"
    },
    "doc://com.apple.pdfkit/documentation/PDFKit/PDFAreaOfInterest/imageArea": {
      "abstract": [
        {
          "text": "The mouse is over an image.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "imageArea"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@PDFAreaOfInterest",
          "text": "PDFAreaOfInterest"
        }
      ],
      "identifier": "doc://com.apple.pdfkit/documentation/PDFKit/PDFAreaOfInterest/imageArea",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kPDFImageArea"
        }
      ],
      "role": "symbol",
      "title": "imageArea",
      "type": "topic",
      "url": "/documentation/pdfkit/pdfareaofinterest/imagearea"
    },
    "doc://com.apple.pdfkit/documentation/PDFKit/PDFAreaOfInterest/init(rawValue:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "rawValue"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.pdfkit/documentation/PDFKit/PDFAreaOfInterest/init(rawValue:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "init(rawValue:)",
      "type": "topic",
      "url": "/documentation/pdfkit/pdfareaofinterest/init(rawvalue:)"
    },
    "doc://com.apple.pdfkit/documentation/PDFKit/PDFAreaOfInterest/kPDFNoArea": {
      "abstract": [
        {
          "text": "The mouse is over an undefined area.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "kPDFNoArea"
        }
      ],
      "identifier": "doc://com.apple.pdfkit/documentation/PDFKit/PDFAreaOfInterest/kPDFNoArea",
      "kind": "symbol",
      "role": "symbol",
      "title": "kPDFNoArea",
      "type": "topic",
      "url": "/documentation/pdfkit/pdfareaofinterest/kpdfnoarea"
    },
    "doc://com.apple.pdfkit/documentation/PDFKit/PDFAreaOfInterest/linkArea": {
      "abstract": [
        {
          "text": "The mouse is over a link.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "linkArea"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@PDFAreaOfInterest",
          "text": "PDFAreaOfInterest"
        }
      ],
      "identifier": "doc://com.apple.pdfkit/documentation/PDFKit/PDFAreaOfInterest/linkArea",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kPDFLinkArea"
        }
      ],
      "role": "symbol",
      "title": "linkArea",
      "type": "topic",
      "url": "/documentation/pdfkit/pdfareaofinterest/linkarea"
    },
    "doc://com.apple.pdfkit/documentation/PDFKit/PDFAreaOfInterest/pageArea": {
      "abstract": [
        {
          "text": "The mouse is over a page.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "pageArea"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@PDFAreaOfInterest",
          "text": "PDFAreaOfInterest"
        }
      ],
      "identifier": "doc://com.apple.pdfkit/documentation/PDFKit/PDFAreaOfInterest/pageArea",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kPDFPageArea"
        }
      ],
      "role": "symbol",
      "title": "pageArea",
      "type": "topic",
      "url": "/documentation/pdfkit/pdfareaofinterest/pagearea"
    },
    "doc://com.apple.pdfkit/documentation/PDFKit/PDFAreaOfInterest/popupArea": {
      "abstract": [
        {
          "text": "The mouse is over a popup menu.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "popupArea"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@PDFAreaOfInterest",
          "text": "PDFAreaOfInterest"
        }
      ],
      "identifier": "doc://com.apple.pdfkit/documentation/PDFKit/PDFAreaOfInterest/popupArea",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kPDFPopupArea"
        }
      ],
      "role": "symbol",
      "title": "popupArea",
      "type": "topic",
      "url": "/documentation/pdfkit/pdfareaofinterest/popuparea"
    },
    "doc://com.apple.pdfkit/documentation/PDFKit/PDFAreaOfInterest/textArea": {
      "abstract": [
        {
          "text": "The mouse is over text.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "textArea"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@PDFAreaOfInterest",
          "text": "PDFAreaOfInterest"
        }
      ],
      "identifier": "doc://com.apple.pdfkit/documentation/PDFKit/PDFAreaOfInterest/textArea",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kPDFTextArea"
        }
      ],
      "role": "symbol",
      "title": "textArea",
      "type": "topic",
      "url": "/documentation/pdfkit/pdfareaofinterest/textarea"
    },
    "doc://com.apple.pdfkit/documentation/PDFKit/PDFAreaOfInterest/textFieldArea": {
      "abstract": [
        {
          "text": "The mouse is over a text field.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "textFieldArea"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@PDFAreaOfInterest",
          "text": "PDFAreaOfInterest"
        }
      ],
      "identifier": "doc://com.apple.pdfkit/documentation/PDFKit/PDFAreaOfInterest/textFieldArea",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kPDFTextFieldArea"
        }
      ],
      "role": "symbol",
      "title": "textFieldArea",
      "type": "topic",
      "url": "/documentation/pdfkit/pdfareaofinterest/textfieldarea"
    },
    "doc://com.apple.pdfkit/documentation/PDFKit/PDFView/areaOfInterest(for:)": {
      "abstract": [
        {
          "text": "Returns the type of area for a specific cursor location point.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "areaOfInterest"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "for"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@CGPoint",
          "text": "CGPoint"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@PDFAreaOfInterest",
          "text": "PDFAreaOfInterest"
        }
      ],
      "identifier": "doc://com.apple.pdfkit/documentation/PDFKit/PDFView/areaOfInterest(for:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "areaOfInterestForPoint:"
        }
      ],
      "role": "symbol",
      "title": "areaOfInterest(for:)",
      "type": "topic",
      "url": "/documentation/pdfkit/pdfview/areaofinterest(for:)"
    },
    "doc://com.apple.pdfkit/documentation/PDFKit/PDFView/areaOfInterest(forMouse:)": {
      "abstract": [
        {
          "text": "Returns the type of area the mouse cursor is over.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "areaOfInterest"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "forMouse"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UIEvent",
          "text": "UIEvent"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@PDFAreaOfInterest",
          "text": "PDFAreaOfInterest"
        }
      ],
      "identifier": "doc://com.apple.pdfkit/documentation/PDFKit/PDFView/areaOfInterest(forMouse:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "areaOfInterestForMouse:"
        }
      ],
      "role": "symbol",
      "title": "areaOfInterest(forMouse:)",
      "type": "topic",
      "url": "/documentation/pdfkit/pdfview/areaofinterest(formouse:)"
    },
    "doc://com.apple.pdfkit/documentation/PDFKit/PDFView/perform(_:)": {
      "abstract": [
        {
          "text": "Performs the specified action.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "perform"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)PDFAction",
          "text": "PDFAction"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.pdfkit/documentation/PDFKit/PDFView/perform(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "performAction:"
        }
      ],
      "role": "symbol",
      "title": "perform(_:)",
      "type": "topic",
      "url": "/documentation/pdfkit/pdfview/perform(_:)"
    },
    "doc://com.apple.pdfkit/documentation/PDFKit/PDFView/setCursorFor(_:)": {
      "abstract": [
        {
          "text": "Sets the type of mouse cursor according to the type of area the mouse cursor is over.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "setCursorFor"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@PDFAreaOfInterest",
          "text": "PDFAreaOfInterest"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.pdfkit/documentation/PDFKit/PDFView/setCursorFor(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "setCursorForAreaOfInterest:"
        }
      ],
      "role": "symbol",
      "title": "setCursorFor(_:)",
      "type": "topic",
      "url": "/documentation/pdfkit/pdfview/setcursorfor(_:)"
    },
    "doc://com.apple.pdfkit/documentation/PDFKit/drag-operations": {
      "abstract": [
        {
          "text": "Define drag operations allowed for a view.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.pdfkit/documentation/PDFKit/drag-operations",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Drag Operations",
      "type": "topic",
      "url": "/documentation/pdfkit/drag-operations"
    },
    "doc://com.externally.resolved.symbol/s:SQ": {
      "abstract": [
        {
          "text": "A type that can be compared for value equality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SQ",
      "kind": "symbol",
      "role": "symbol",
      "title": "Equatable",
      "type": "topic",
      "url": "/documentation/Swift/Equatable"
    },
    "doc://com.externally.resolved.symbol/s:SY": {
      "abstract": [
        {
          "text": "A type that can be converted to and from an associated raw value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "RawRepresentable"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SY8RawValueQa",
          "text": "RawValue"
        },
        {
          "kind": "text",
          "text": ">"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SY",
      "kind": "symbol",
      "role": "symbol",
      "title": "RawRepresentable",
      "type": "topic",
      "url": "/documentation/Swift/RawRepresentable"
    },
    "doc://com.externally.resolved.symbol/s:s10SetAlgebraP": {
      "abstract": [
        {
          "text": "A type that provides mathematical set operations.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SetAlgebra"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s10SetAlgebraP7ElementQa",
          "text": "Element"
        },
        {
          "kind": "text",
          "text": "> : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SQ",
          "text": "Equatable"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s25ExpressibleByArrayLiteralP",
          "text": "ExpressibleByArrayLiteral"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s10SetAlgebraP",
      "kind": "symbol",
      "role": "symbol",
      "title": "SetAlgebra",
      "type": "topic",
      "url": "/documentation/Swift/SetAlgebra"
    },
    "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BitwiseCopyable"
        },
        {
          "kind": "text",
          "text": " : ~Escapable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "BitwiseCopyable",
      "type": "topic",
      "url": "/documentation/Swift/BitwiseCopyable"
    },
    "doc://com.externally.resolved.symbol/s:s25ExpressibleByArrayLiteralP": {
      "abstract": [
        {
          "text": "A type that can be initialized using an array literal.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ExpressibleByArrayLiteral"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s25ExpressibleByArrayLiteralP",
      "kind": "symbol",
      "role": "symbol",
      "title": "ExpressibleByArrayLiteral",
      "type": "topic",
      "url": "/documentation/Swift/ExpressibleByArrayLiteral"
    },
    "doc://com.externally.resolved.symbol/s:s8SendableP": {
      "abstract": [
        {
          "text": "A thread-safe type whose values can be shared across arbitrary concurrent contexts without introducing a risk of data races.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Sendable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s8SendableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "Sendable",
      "type": "topic",
      "url": "/documentation/Swift/Sendable"
    },
    "doc://com.externally.resolved.symbol/s:s9OptionSetP": {
      "abstract": [
        {
          "text": "A type that presents a mathematical set interface to a bit set.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "OptionSet"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SY",
          "text": "RawRepresentable"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s10SetAlgebraP",
          "text": "SetAlgebra"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s9OptionSetP",
      "kind": "symbol",
      "role": "symbol",
      "title": "OptionSet",
      "type": "topic",
      "url": "/documentation/Swift/OptionSet"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
        "doc://com.externally.resolved.symbol/s:SQ",
        "doc://com.externally.resolved.symbol/s:s25ExpressibleByArrayLiteralP",
        "doc://com.externally.resolved.symbol/s:s9OptionSetP",
        "doc://com.externally.resolved.symbol/s:SY",
        "doc://com.externally.resolved.symbol/s:s8SendableP",
        "doc://com.externally.resolved.symbol/s:s10SetAlgebraP"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Working-with-Mouse-Position-and-Events",
      "generated": true,
      "identifiers": [
        "doc://com.apple.pdfkit/documentation/PDFKit/PDFView/areaOfInterest(forMouse:)",
        "doc://com.apple.pdfkit/documentation/PDFKit/PDFView/areaOfInterest(for:)",
        "doc://com.apple.pdfkit/documentation/PDFKit/PDFView/setCursorFor(_:)",
        "doc://com.apple.pdfkit/documentation/PDFKit/PDFView/perform(_:)",
        "doc://com.apple.pdfkit/documentation/PDFKit/drag-operations"
      ],
      "title": "Working with Mouse Position and Events"
    }
  ],
  "topicSections": [
    {
      "anchor": "Constants",
      "identifiers": [
        "doc://com.apple.pdfkit/documentation/PDFKit/PDFAreaOfInterest/pageArea",
        "doc://com.apple.pdfkit/documentation/PDFKit/PDFAreaOfInterest/textArea",
        "doc://com.apple.pdfkit/documentation/PDFKit/PDFAreaOfInterest/annotationArea",
        "doc://com.apple.pdfkit/documentation/PDFKit/PDFAreaOfInterest/linkArea",
        "doc://com.apple.pdfkit/documentation/PDFKit/PDFAreaOfInterest/controlArea",
        "doc://com.apple.pdfkit/documentation/PDFKit/PDFAreaOfInterest/textFieldArea",
        "doc://com.apple.pdfkit/documentation/PDFKit/PDFAreaOfInterest/iconArea",
        "doc://com.apple.pdfkit/documentation/PDFKit/PDFAreaOfInterest/popupArea",
        "doc://com.apple.pdfkit/documentation/PDFKit/PDFAreaOfInterest/imageArea"
      ],
      "title": "Constants"
    },
    {
      "anchor": "Initializers",
      "identifiers": [
        "doc://com.apple.pdfkit/documentation/PDFKit/PDFAreaOfInterest/init(rawValue:)"
      ],
      "title": "Initializers"
    },
    {
      "anchor": "Type-Properties",
      "identifiers": [
        "doc://com.apple.pdfkit/documentation/PDFKit/PDFAreaOfInterest/anyArea"
      ],
      "title": "Type Properties"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "11.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "11.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "11.0",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.4",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "PDFAreaOfInterest"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "enum"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PDFAreaOfInterest"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "PDFAreaOfInterest"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.pdfkit/documentation/PDFKit"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Constants",
              "identifiers": [
                "doc://com.apple.pdfkit/documentation/PDFKit/PDFAreaOfInterest/kPDFNoArea",
                "doc://com.apple.pdfkit/documentation/PDFKit/PDFAreaOfInterest/pageArea",
                "doc://com.apple.pdfkit/documentation/PDFKit/PDFAreaOfInterest/textArea",
                "doc://com.apple.pdfkit/documentation/PDFKit/PDFAreaOfInterest/annotationArea",
                "doc://com.apple.pdfkit/documentation/PDFKit/PDFAreaOfInterest/linkArea",
                "doc://com.apple.pdfkit/documentation/PDFKit/PDFAreaOfInterest/controlArea",
                "doc://com.apple.pdfkit/documentation/PDFKit/PDFAreaOfInterest/textFieldArea",
                "doc://com.apple.pdfkit/documentation/PDFKit/PDFAreaOfInterest/iconArea",
                "doc://com.apple.pdfkit/documentation/PDFKit/PDFAreaOfInterest/popupArea",
                "doc://com.apple.pdfkit/documentation/PDFKit/PDFAreaOfInterest/imageArea"
              ],
              "title": "Constants"
            },
            {
              "anchor": "Type-Properties",
              "identifiers": [
                "doc://com.apple.pdfkit/documentation/PDFKit/PDFAreaOfInterest/anyArea"
              ],
              "title": "Type Properties"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Working-with-Mouse-Position-and-Events",
              "generated": true,
              "identifiers": [
                "doc://com.apple.pdfkit/documentation/PDFKit/PDFView/areaOfInterest(forMouse:)",
                "doc://com.apple.pdfkit/documentation/PDFKit/PDFView/areaOfInterest(for:)",
                "doc://com.apple.pdfkit/documentation/PDFKit/PDFView/setCursorFor(_:)",
                "doc://com.apple.pdfkit/documentation/PDFKit/PDFView/perform(_:)",
                "doc://com.apple.pdfkit/documentation/PDFKit/drag-operations"
              ],
              "title": "Working with Mouse Position and Events"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "enum"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "PDFAreaOfInterest"
                  },
                  {
                    "kind": "text",
                    "text": " : "
                  },
                  {
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@NSInteger",
                    "text": "NSInteger"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFView~1setCursorFor(_:)/title",
          "value": "setCursorForAreaOfInterest:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFView~1setCursorFor(_:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "setCursorForAreaOfInterest:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFAreaOfInterest~1textArea/title",
          "value": "kPDFTextArea"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFAreaOfInterest~1textArea/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kPDFTextArea"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFView~1areaOfInterest(forMouse:)/title",
          "value": "areaOfInterestForMouse:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFView~1areaOfInterest(forMouse:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "areaOfInterestForMouse:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFAreaOfInterest/title",
          "value": "PDFAreaOfInterest"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFAreaOfInterest/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PDFAreaOfInterest"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFAreaOfInterest/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "PDFAreaOfInterest"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFAreaOfInterest~1linkArea/title",
          "value": "kPDFLinkArea"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFAreaOfInterest~1linkArea/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kPDFLinkArea"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFView~1perform(_:)/title",
          "value": "performAction:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFView~1perform(_:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "performAction:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFAreaOfInterest~1textFieldArea/title",
          "value": "kPDFTextFieldArea"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFAreaOfInterest~1textFieldArea/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kPDFTextFieldArea"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFAreaOfInterest~1imageArea/title",
          "value": "kPDFImageArea"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFAreaOfInterest~1imageArea/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kPDFImageArea"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFAreaOfInterest~1iconArea/title",
          "value": "kPDFIconArea"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFAreaOfInterest~1iconArea/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kPDFIconArea"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFAreaOfInterest~1pageArea/title",
          "value": "kPDFPageArea"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFAreaOfInterest~1pageArea/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kPDFPageArea"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFAreaOfInterest~1annotationArea/title",
          "value": "kPDFAnnotationArea"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFAreaOfInterest~1annotationArea/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kPDFAnnotationArea"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFView~1areaOfInterest(for:)/title",
          "value": "areaOfInterestForPoint:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFView~1areaOfInterest(for:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "areaOfInterestForPoint:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFAreaOfInterest~1anyArea/title",
          "value": "kPDFAnyArea"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFAreaOfInterest~1anyArea/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kPDFAnyArea"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFAreaOfInterest~1controlArea/title",
          "value": "kPDFControlArea"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFAreaOfInterest~1controlArea/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kPDFControlArea"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFAreaOfInterest~1popupArea/title",
          "value": "kPDFPopupArea"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFAreaOfInterest~1popupArea/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kPDFPopupArea"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/pdfkit/pdfareaofinterest"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/pdfkit/pdfareaofinterest"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
