{
  "diffAvailability": {
    "major": {
      "change": "modified",
      "platform": "Xcode",
      "versions": [
        "16.0",
        "16.3 beta 2"
      ]
    }
  },
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.pdfkit/documentation/PDFKit"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.pdfkit/documentation/PDFKit/PDFAnnotationWidgetSubtype"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@T@PDFAnnotationWidgetSubtype",
    "fragments": [
      {
        "kind": "keyword",
        "text": "struct"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "PDFAnnotationWidgetSubtype"
      }
    ],
    "modules": [
      {
        "name": "PDFKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "PDFAnnotationWidgetSubtype"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "11.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "11.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "11.0",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.4",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Structure",
    "symbolKind": "struct",
    "title": "PDFAnnotationWidgetSubtype"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "struct"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "PDFAnnotationWidgetSubtype"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "kind": "mentions",
      "mentions": [
        "doc://com.apple.pdfkit/documentation/PDFKit/adding-widgets-to-a-pdf-document"
      ]
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.pdfkit/documentation/PDFKit": {
      "abstract": [
        {
          "text": "Display and manipulate PDF documents in your apps.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.pdfkit/documentation/PDFKit",
      "kind": "symbol",
      "role": "collection",
      "title": "PDFKit",
      "type": "topic",
      "url": "/documentation/pdfkit"
    },
    "doc://com.apple.pdfkit/documentation/PDFKit/PDFAnnotationKey/widgetAppearanceDictionary": {
      "abstract": [
        {
          "text": "A dictionary or appearance characteristic object that contains properties for controlling the widget’s visual appearance.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "widgetAppearanceDictionary"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@PDFAnnotationKey",
          "text": "PDFAnnotationKey"
        }
      ],
      "identifier": "doc://com.apple.pdfkit/documentation/PDFKit/PDFAnnotationKey/widgetAppearanceDictionary",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PDFAnnotationKeyWidgetAppearanceDictionary"
        }
      ],
      "role": "symbol",
      "title": "widgetAppearanceDictionary",
      "type": "topic",
      "url": "/documentation/pdfkit/pdfannotationkey/widgetappearancedictionary"
    },
    "doc://com.apple.pdfkit/documentation/PDFKit/PDFAnnotationKey/widgetBackgroundColor": {
      "abstract": [
        {
          "text": "An array of floating point values or a PDF color object that specifies the widget’s background color.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "widgetBackgroundColor"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@PDFAnnotationKey",
          "text": "PDFAnnotationKey"
        }
      ],
      "identifier": "doc://com.apple.pdfkit/documentation/PDFKit/PDFAnnotationKey/widgetBackgroundColor",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PDFAnnotationKeyWidgetBackgroundColor"
        }
      ],
      "role": "symbol",
      "title": "widgetBackgroundColor",
      "type": "topic",
      "url": "/documentation/pdfkit/pdfannotationkey/widgetbackgroundcolor"
    },
    "doc://com.apple.pdfkit/documentation/PDFKit/PDFAnnotationKey/widgetBorderColor": {
      "abstract": [
        {
          "text": "An array of floating point values or a PDF color object that specifies the widget’s border color.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "widgetBorderColor"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@PDFAnnotationKey",
          "text": "PDFAnnotationKey"
        }
      ],
      "identifier": "doc://com.apple.pdfkit/documentation/PDFKit/PDFAnnotationKey/widgetBorderColor",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PDFAnnotationKeyWidgetBorderColor"
        }
      ],
      "role": "symbol",
      "title": "widgetBorderColor",
      "type": "topic",
      "url": "/documentation/pdfkit/pdfannotationkey/widgetbordercolor"
    },
    "doc://com.apple.pdfkit/documentation/PDFKit/PDFAnnotationKey/widgetCaption": {
      "abstract": [
        {
          "text": "A string that a push button widget displays when it isn’t in a pressed state.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "widgetCaption"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@PDFAnnotationKey",
          "text": "PDFAnnotationKey"
        }
      ],
      "identifier": "doc://com.apple.pdfkit/documentation/PDFKit/PDFAnnotationKey/widgetCaption",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PDFAnnotationKeyWidgetCaption"
        }
      ],
      "role": "symbol",
      "title": "widgetCaption",
      "type": "topic",
      "url": "/documentation/pdfkit/pdfannotationkey/widgetcaption"
    },
    "doc://com.apple.pdfkit/documentation/PDFKit/PDFAnnotationKey/widgetDefaultValue": {
      "abstract": [
        {
          "text": "A default value for the widget.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "widgetDefaultValue"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@PDFAnnotationKey",
          "text": "PDFAnnotationKey"
        }
      ],
      "identifier": "doc://com.apple.pdfkit/documentation/PDFKit/PDFAnnotationKey/widgetDefaultValue",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PDFAnnotationKeyWidgetDefaultValue"
        }
      ],
      "role": "symbol",
      "title": "widgetDefaultValue",
      "type": "topic",
      "url": "/documentation/pdfkit/pdfannotationkey/widgetdefaultvalue"
    },
    "doc://com.apple.pdfkit/documentation/PDFKit/PDFAnnotationKey/widgetDownCaption": {
      "abstract": [
        {
          "text": "A string that a push button widgets displays when it’s in a pressed state.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "widgetDownCaption"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@PDFAnnotationKey",
          "text": "PDFAnnotationKey"
        }
      ],
      "identifier": "doc://com.apple.pdfkit/documentation/PDFKit/PDFAnnotationKey/widgetDownCaption",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PDFAnnotationKeyWidgetDownCaption"
        }
      ],
      "role": "symbol",
      "title": "widgetDownCaption",
      "type": "topic",
      "url": "/documentation/pdfkit/pdfannotationkey/widgetdowncaption"
    },
    "doc://com.apple.pdfkit/documentation/PDFKit/PDFAnnotationKey/widgetFieldFlags": {
      "abstract": [
        {
          "text": "An integer value that specifies flags for a widget.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "widgetFieldFlags"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@PDFAnnotationKey",
          "text": "PDFAnnotationKey"
        }
      ],
      "identifier": "doc://com.apple.pdfkit/documentation/PDFKit/PDFAnnotationKey/widgetFieldFlags",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PDFAnnotationKeyWidgetFieldFlags"
        }
      ],
      "role": "symbol",
      "title": "widgetFieldFlags",
      "type": "topic",
      "url": "/documentation/pdfkit/pdfannotationkey/widgetfieldflags"
    },
    "doc://com.apple.pdfkit/documentation/PDFKit/PDFAnnotationKey/widgetFieldType": {
      "abstract": [
        {
          "text": "A string that specifies the type of widget, such as button, checkbox, or signature field.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "widgetFieldType"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@PDFAnnotationKey",
          "text": "PDFAnnotationKey"
        }
      ],
      "identifier": "doc://com.apple.pdfkit/documentation/PDFKit/PDFAnnotationKey/widgetFieldType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PDFAnnotationKeyWidgetFieldType"
        }
      ],
      "role": "symbol",
      "title": "widgetFieldType",
      "type": "topic",
      "url": "/documentation/pdfkit/pdfannotationkey/widgetfieldtype"
    },
    "doc://com.apple.pdfkit/documentation/PDFKit/PDFAnnotationKey/widgetMaxLen": {
      "abstract": [
        {
          "text": "An integer value that specifies the maximum length of a text field, in characters.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "widgetMaxLen"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@PDFAnnotationKey",
          "text": "PDFAnnotationKey"
        }
      ],
      "identifier": "doc://com.apple.pdfkit/documentation/PDFKit/PDFAnnotationKey/widgetMaxLen",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PDFAnnotationKeyWidgetMaxLen"
        }
      ],
      "role": "symbol",
      "title": "widgetMaxLen",
      "type": "topic",
      "url": "/documentation/pdfkit/pdfannotationkey/widgetmaxlen"
    },
    "doc://com.apple.pdfkit/documentation/PDFKit/PDFAnnotationKey/widgetOptions": {
      "abstract": [
        {
          "text": "An array that specifies the options to present in radio buttons or choice lists.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "widgetOptions"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@PDFAnnotationKey",
          "text": "PDFAnnotationKey"
        }
      ],
      "identifier": "doc://com.apple.pdfkit/documentation/PDFKit/PDFAnnotationKey/widgetOptions",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PDFAnnotationKeyWidgetOptions"
        }
      ],
      "role": "symbol",
      "title": "widgetOptions",
      "type": "topic",
      "url": "/documentation/pdfkit/pdfannotationkey/widgetoptions"
    },
    "doc://com.apple.pdfkit/documentation/PDFKit/PDFAnnotationKey/widgetRolloverCaption": {
      "abstract": [
        {
          "text": "A string that push button widgets display when the pointer is over the button, but not clicking it.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "widgetRolloverCaption"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@PDFAnnotationKey",
          "text": "PDFAnnotationKey"
        }
      ],
      "identifier": "doc://com.apple.pdfkit/documentation/PDFKit/PDFAnnotationKey/widgetRolloverCaption",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PDFAnnotationKeyWidgetRolloverCaption"
        }
      ],
      "role": "symbol",
      "title": "widgetRolloverCaption",
      "type": "topic",
      "url": "/documentation/pdfkit/pdfannotationkey/widgetrollovercaption"
    },
    "doc://com.apple.pdfkit/documentation/PDFKit/PDFAnnotationKey/widgetRotation": {
      "abstract": [
        {
          "text": "An integer value that specifies the rotation of the widget.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "widgetRotation"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@PDFAnnotationKey",
          "text": "PDFAnnotationKey"
        }
      ],
      "identifier": "doc://com.apple.pdfkit/documentation/PDFKit/PDFAnnotationKey/widgetRotation",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PDFAnnotationKeyWidgetRotation"
        }
      ],
      "role": "symbol",
      "title": "widgetRotation",
      "type": "topic",
      "url": "/documentation/pdfkit/pdfannotationkey/widgetrotation"
    },
    "doc://com.apple.pdfkit/documentation/PDFKit/PDFAnnotationKey/widgetTextLabelUI": {
      "abstract": [
        {
          "text": "A user-visible alternative field name that identifies the widget, typically for accessibility purposes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "widgetTextLabelUI"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@PDFAnnotationKey",
          "text": "PDFAnnotationKey"
        }
      ],
      "identifier": "doc://com.apple.pdfkit/documentation/PDFKit/PDFAnnotationKey/widgetTextLabelUI",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PDFAnnotationKeyWidgetTextLabelUI"
        }
      ],
      "role": "symbol",
      "title": "widgetTextLabelUI",
      "type": "topic",
      "url": "/documentation/pdfkit/pdfannotationkey/widgettextlabelui"
    },
    "doc://com.apple.pdfkit/documentation/PDFKit/PDFAnnotationKey/widgetValue": {
      "abstract": [
        {
          "text": "The widget’s value, typically for text and choice widgets.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "widgetValue"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@PDFAnnotationKey",
          "text": "PDFAnnotationKey"
        }
      ],
      "identifier": "doc://com.apple.pdfkit/documentation/PDFKit/PDFAnnotationKey/widgetValue",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PDFAnnotationKeyWidgetValue"
        }
      ],
      "role": "symbol",
      "title": "widgetValue",
      "type": "topic",
      "url": "/documentation/pdfkit/pdfannotationkey/widgetvalue"
    },
    "doc://com.apple.pdfkit/documentation/PDFKit/PDFAnnotationWidgetSubtype": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "PDFAnnotationWidgetSubtype"
        }
      ],
      "identifier": "doc://com.apple.pdfkit/documentation/PDFKit/PDFAnnotationWidgetSubtype",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PDFAnnotationWidgetSubtype"
        }
      ],
      "role": "symbol",
      "title": "PDFAnnotationWidgetSubtype",
      "type": "topic",
      "url": "/documentation/pdfkit/pdfannotationwidgetsubtype"
    },
    "doc://com.apple.pdfkit/documentation/PDFKit/PDFAnnotationWidgetSubtype/button": {
      "abstract": [
        {
          "text": "A button widget type, including push buttons, checkboxes, and radio buttons.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "button"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@PDFAnnotationWidgetSubtype",
          "text": "PDFAnnotationWidgetSubtype"
        }
      ],
      "identifier": "doc://com.apple.pdfkit/documentation/PDFKit/PDFAnnotationWidgetSubtype/button",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PDFAnnotationWidgetSubtypeButton"
        }
      ],
      "role": "symbol",
      "title": "button",
      "type": "topic",
      "url": "/documentation/pdfkit/pdfannotationwidgetsubtype/button"
    },
    "doc://com.apple.pdfkit/documentation/PDFKit/PDFAnnotationWidgetSubtype/choice": {
      "abstract": [
        {
          "text": "A type that presents a list of choices the user can choose from.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "choice"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@PDFAnnotationWidgetSubtype",
          "text": "PDFAnnotationWidgetSubtype"
        }
      ],
      "identifier": "doc://com.apple.pdfkit/documentation/PDFKit/PDFAnnotationWidgetSubtype/choice",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PDFAnnotationWidgetSubtypeChoice"
        }
      ],
      "role": "symbol",
      "title": "choice",
      "type": "topic",
      "url": "/documentation/pdfkit/pdfannotationwidgetsubtype/choice"
    },
    "doc://com.apple.pdfkit/documentation/PDFKit/PDFAnnotationWidgetSubtype/init(rawValue:)": {
      "abstract": [
        {
          "text": "Creates a widget subtype using the specified raw string value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "rawValue"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.pdfkit/documentation/PDFKit/PDFAnnotationWidgetSubtype/init(rawValue:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "init(rawValue:)",
      "type": "topic",
      "url": "/documentation/pdfkit/pdfannotationwidgetsubtype/init(rawvalue:)"
    },
    "doc://com.apple.pdfkit/documentation/PDFKit/PDFAnnotationWidgetSubtype/signature": {
      "abstract": [
        {
          "text": "A digital signature widget type.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "signature"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@PDFAnnotationWidgetSubtype",
          "text": "PDFAnnotationWidgetSubtype"
        }
      ],
      "identifier": "doc://com.apple.pdfkit/documentation/PDFKit/PDFAnnotationWidgetSubtype/signature",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PDFAnnotationWidgetSubtypeSignature"
        }
      ],
      "role": "symbol",
      "title": "signature",
      "type": "topic",
      "url": "/documentation/pdfkit/pdfannotationwidgetsubtype/signature"
    },
    "doc://com.apple.pdfkit/documentation/PDFKit/PDFAnnotationWidgetSubtype/text": {
      "abstract": [
        {
          "text": "A text field the user can type text in.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "text"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@PDFAnnotationWidgetSubtype",
          "text": "PDFAnnotationWidgetSubtype"
        }
      ],
      "identifier": "doc://com.apple.pdfkit/documentation/PDFKit/PDFAnnotationWidgetSubtype/text",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PDFAnnotationWidgetSubtypeText"
        }
      ],
      "role": "symbol",
      "title": "text",
      "type": "topic",
      "url": "/documentation/pdfkit/pdfannotationwidgetsubtype/text"
    },
    "doc://com.apple.pdfkit/documentation/PDFKit/adding-widgets-to-a-pdf-document": {
      "abstract": [
        {
          "text": "Add text, button, and choice widgets to a PDF document.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.pdfkit/documentation/PDFKit/adding-widgets-to-a-pdf-document",
      "kind": "article",
      "role": "article",
      "title": "Adding Widgets to a PDF Document",
      "type": "topic",
      "url": "/documentation/pdfkit/adding-widgets-to-a-pdf-document"
    },
    "doc://com.externally.resolved.symbol/c:objc(cs)NSString": {
      "abstract": [
        {
          "text": "A static, plain-text Unicode string object which you use when you need reference semantics or other Foundation-specific behavior. ",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "class "
        },
        {
          "kind": "identifier",
          "text": "NSString"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSString",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSString",
      "type": "topic",
      "url": "/documentation/foundation/nsstring"
    },
    "doc://com.externally.resolved.symbol/s:SH": {
      "abstract": [
        {
          "text": "A type that can be hashed into a `Hasher` to produce an integer hash value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Hashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SQ",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SH",
      "kind": "symbol",
      "role": "symbol",
      "title": "Hashable",
      "type": "topic",
      "url": "/documentation/Swift/Hashable"
    },
    "doc://com.externally.resolved.symbol/s:SQ": {
      "abstract": [
        {
          "text": "A type that can be compared for value equality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SQ",
      "kind": "symbol",
      "role": "symbol",
      "title": "Equatable",
      "type": "topic",
      "url": "/documentation/Swift/Equatable"
    },
    "doc://com.externally.resolved.symbol/s:SY": {
      "abstract": [
        {
          "text": "A type that can be converted to and from an associated raw value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "RawRepresentable"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SY8RawValueQa",
          "text": "RawValue"
        },
        {
          "kind": "text",
          "text": ">"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SY",
      "kind": "symbol",
      "role": "symbol",
      "title": "RawRepresentable",
      "type": "topic",
      "url": "/documentation/Swift/RawRepresentable"
    },
    "doc://com.externally.resolved.symbol/s:s8SendableP": {
      "abstract": [
        {
          "text": "A thread-safe type whose values can be shared across arbitrary concurrent contexts without introducing a risk of data races.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Sendable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s8SendableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "Sendable",
      "type": "topic",
      "url": "/documentation/Swift/Sendable"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:SQ",
        "doc://com.externally.resolved.symbol/s:SH",
        "doc://com.externally.resolved.symbol/s:SY",
        "doc://com.externally.resolved.symbol/s:s8SendableP"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Configuring-Widget-Annotations",
      "generated": true,
      "identifiers": [
        "doc://com.apple.pdfkit/documentation/PDFKit/PDFAnnotationKey/widgetAppearanceDictionary",
        "doc://com.apple.pdfkit/documentation/PDFKit/PDFAnnotationKey/widgetBackgroundColor",
        "doc://com.apple.pdfkit/documentation/PDFKit/PDFAnnotationKey/widgetBorderColor",
        "doc://com.apple.pdfkit/documentation/PDFKit/PDFAnnotationKey/widgetCaption",
        "doc://com.apple.pdfkit/documentation/PDFKit/PDFAnnotationKey/widgetDefaultValue",
        "doc://com.apple.pdfkit/documentation/PDFKit/PDFAnnotationKey/widgetDownCaption",
        "doc://com.apple.pdfkit/documentation/PDFKit/PDFAnnotationKey/widgetFieldFlags",
        "doc://com.apple.pdfkit/documentation/PDFKit/PDFAnnotationKey/widgetFieldType",
        "doc://com.apple.pdfkit/documentation/PDFKit/PDFAnnotationKey/widgetMaxLen",
        "doc://com.apple.pdfkit/documentation/PDFKit/PDFAnnotationKey/widgetOptions",
        "doc://com.apple.pdfkit/documentation/PDFKit/PDFAnnotationKey/widgetRolloverCaption",
        "doc://com.apple.pdfkit/documentation/PDFKit/PDFAnnotationKey/widgetRotation",
        "doc://com.apple.pdfkit/documentation/PDFKit/PDFAnnotationKey/widgetTextLabelUI",
        "doc://com.apple.pdfkit/documentation/PDFKit/PDFAnnotationKey/widgetValue"
      ],
      "title": "Configuring Widget Annotations"
    }
  ],
  "topicSections": [
    {
      "anchor": "Configuring-a-Widget-Subtype",
      "identifiers": [
        "doc://com.apple.pdfkit/documentation/PDFKit/PDFAnnotationWidgetSubtype/button",
        "doc://com.apple.pdfkit/documentation/PDFKit/PDFAnnotationWidgetSubtype/choice",
        "doc://com.apple.pdfkit/documentation/PDFKit/PDFAnnotationWidgetSubtype/signature",
        "doc://com.apple.pdfkit/documentation/PDFKit/PDFAnnotationWidgetSubtype/text"
      ],
      "title": "Configuring a Widget Subtype"
    },
    {
      "anchor": "Creating-a-Widget-Subtype",
      "identifiers": [
        "doc://com.apple.pdfkit/documentation/PDFKit/PDFAnnotationWidgetSubtype/init(rawValue:)"
      ],
      "title": "Creating a Widget Subtype"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "11.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "11.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "11.0",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.4",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Type Alias"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "PDFAnnotationWidgetSubtype"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "typealias"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PDFAnnotationWidgetSubtype"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "PDFAnnotationWidgetSubtype"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.pdfkit/documentation/PDFKit"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Configuring-a-Widget-Subtype",
              "identifiers": [
                "doc://com.apple.pdfkit/documentation/PDFKit/PDFAnnotationWidgetSubtype/button",
                "doc://com.apple.pdfkit/documentation/PDFKit/PDFAnnotationWidgetSubtype/choice",
                "doc://com.apple.pdfkit/documentation/PDFKit/PDFAnnotationWidgetSubtype/signature",
                "doc://com.apple.pdfkit/documentation/PDFKit/PDFAnnotationWidgetSubtype/text"
              ],
              "title": "Configuring a Widget Subtype"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Configuring-Widget-Annotations",
              "generated": true,
              "identifiers": [
                "doc://com.apple.pdfkit/documentation/PDFKit/PDFAnnotationKey/widgetAppearanceDictionary",
                "doc://com.apple.pdfkit/documentation/PDFKit/PDFAnnotationKey/widgetBackgroundColor",
                "doc://com.apple.pdfkit/documentation/PDFKit/PDFAnnotationKey/widgetBorderColor",
                "doc://com.apple.pdfkit/documentation/PDFKit/PDFAnnotationKey/widgetCaption",
                "doc://com.apple.pdfkit/documentation/PDFKit/PDFAnnotationKey/widgetDefaultValue",
                "doc://com.apple.pdfkit/documentation/PDFKit/PDFAnnotationKey/widgetDownCaption",
                "doc://com.apple.pdfkit/documentation/PDFKit/PDFAnnotationKey/widgetFieldFlags",
                "doc://com.apple.pdfkit/documentation/PDFKit/PDFAnnotationKey/widgetFieldType",
                "doc://com.apple.pdfkit/documentation/PDFKit/PDFAnnotationKey/widgetMaxLen",
                "doc://com.apple.pdfkit/documentation/PDFKit/PDFAnnotationKey/widgetOptions",
                "doc://com.apple.pdfkit/documentation/PDFKit/PDFAnnotationKey/widgetRolloverCaption",
                "doc://com.apple.pdfkit/documentation/PDFKit/PDFAnnotationKey/widgetRotation",
                "doc://com.apple.pdfkit/documentation/PDFKit/PDFAnnotationKey/widgetTextLabelUI",
                "doc://com.apple.pdfkit/documentation/PDFKit/PDFAnnotationKey/widgetValue"
              ],
              "title": "Configuring Widget Annotations"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "typedef"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSString",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(cs)NSString",
                    "text": "NSString"
                  },
                  {
                    "kind": "text",
                    "text": " * "
                  },
                  {
                    "kind": "keyword",
                    "text": "const"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "PDFAnnotationWidgetSubtype"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFAnnotationWidgetSubtype~1text/title",
          "value": "PDFAnnotationWidgetSubtypeText"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFAnnotationWidgetSubtype~1text/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PDFAnnotationWidgetSubtypeText"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFAnnotationKey~1widgetFieldType/title",
          "value": "PDFAnnotationKeyWidgetFieldType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFAnnotationKey~1widgetFieldType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PDFAnnotationKeyWidgetFieldType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFAnnotationKey~1widgetBackgroundColor/title",
          "value": "PDFAnnotationKeyWidgetBackgroundColor"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFAnnotationKey~1widgetBackgroundColor/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PDFAnnotationKeyWidgetBackgroundColor"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFAnnotationKey~1widgetTextLabelUI/title",
          "value": "PDFAnnotationKeyWidgetTextLabelUI"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFAnnotationKey~1widgetTextLabelUI/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PDFAnnotationKeyWidgetTextLabelUI"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFAnnotationKey~1widgetDownCaption/title",
          "value": "PDFAnnotationKeyWidgetDownCaption"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFAnnotationKey~1widgetDownCaption/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PDFAnnotationKeyWidgetDownCaption"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFAnnotationKey~1widgetFieldFlags/title",
          "value": "PDFAnnotationKeyWidgetFieldFlags"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFAnnotationKey~1widgetFieldFlags/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PDFAnnotationKeyWidgetFieldFlags"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFAnnotationKey~1widgetDefaultValue/title",
          "value": "PDFAnnotationKeyWidgetDefaultValue"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFAnnotationKey~1widgetDefaultValue/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PDFAnnotationKeyWidgetDefaultValue"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFAnnotationWidgetSubtype~1choice/title",
          "value": "PDFAnnotationWidgetSubtypeChoice"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFAnnotationWidgetSubtype~1choice/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PDFAnnotationWidgetSubtypeChoice"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFAnnotationWidgetSubtype~1button/title",
          "value": "PDFAnnotationWidgetSubtypeButton"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFAnnotationWidgetSubtype~1button/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PDFAnnotationWidgetSubtypeButton"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFAnnotationKey~1widgetOptions/title",
          "value": "PDFAnnotationKeyWidgetOptions"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFAnnotationKey~1widgetOptions/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PDFAnnotationKeyWidgetOptions"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFAnnotationKey~1widgetBorderColor/title",
          "value": "PDFAnnotationKeyWidgetBorderColor"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFAnnotationKey~1widgetBorderColor/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PDFAnnotationKeyWidgetBorderColor"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFAnnotationKey~1widgetAppearanceDictionary/title",
          "value": "PDFAnnotationKeyWidgetAppearanceDictionary"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFAnnotationKey~1widgetAppearanceDictionary/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PDFAnnotationKeyWidgetAppearanceDictionary"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFAnnotationKey~1widgetRotation/title",
          "value": "PDFAnnotationKeyWidgetRotation"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFAnnotationKey~1widgetRotation/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PDFAnnotationKeyWidgetRotation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFAnnotationWidgetSubtype~1signature/title",
          "value": "PDFAnnotationWidgetSubtypeSignature"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFAnnotationWidgetSubtype~1signature/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PDFAnnotationWidgetSubtypeSignature"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFAnnotationWidgetSubtype/title",
          "value": "PDFAnnotationWidgetSubtype"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFAnnotationWidgetSubtype/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PDFAnnotationWidgetSubtype"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFAnnotationWidgetSubtype/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "PDFAnnotationWidgetSubtype"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFAnnotationKey~1widgetValue/title",
          "value": "PDFAnnotationKeyWidgetValue"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFAnnotationKey~1widgetValue/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PDFAnnotationKeyWidgetValue"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:objc(cs)NSString/abstract",
          "value": [
            {
              "text": "A static, plain-text Unicode string object.",
              "type": "text"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFAnnotationKey~1widgetMaxLen/title",
          "value": "PDFAnnotationKeyWidgetMaxLen"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFAnnotationKey~1widgetMaxLen/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PDFAnnotationKeyWidgetMaxLen"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFAnnotationKey~1widgetCaption/title",
          "value": "PDFAnnotationKeyWidgetCaption"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFAnnotationKey~1widgetCaption/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PDFAnnotationKeyWidgetCaption"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFAnnotationKey~1widgetRolloverCaption/title",
          "value": "PDFAnnotationKeyWidgetRolloverCaption"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFAnnotationKey~1widgetRolloverCaption/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PDFAnnotationKeyWidgetRolloverCaption"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/pdfkit/pdfannotationwidgetsubtype"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/pdfkit/pdfannotationwidgetsubtype"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
