{
  "abstract": [
    {
      "text": "A ",
      "type": "text"
    },
    {
      "code": "PDFAnnotationButtonWidget",
      "type": "codeVoice"
    },
    {
      "text": " object provides user interactivity on a page of a PDF document. There are three types of buttons available: push button, radio button, and checkbox.",
      "type": "text"
    }
  ],
  "deprecationSummary": [
    {
      "inlineContent": [
        {
          "text": "Use ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.pdfkit/documentation/PDFKit/PDFAnnotationSubtype",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " instead.",
          "type": "text"
        }
      ],
      "type": "paragraph"
    }
  ],
  "diffAvailability": {
    "major": {
      "change": "modified",
      "platform": "Xcode",
      "versions": [
        "16.0",
        "16.3 beta 2"
      ]
    }
  },
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.pdfkit/documentation/PDFKit"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.pdfkit/documentation/PDFKit/PDFAnnotationButtonWidget"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(cs)PDFAnnotationButtonWidget",
    "fragments": [
      {
        "kind": "keyword",
        "text": "class"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "PDFAnnotationButtonWidget"
      }
    ],
    "modules": [
      {
        "name": "PDFKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "PDFAnnotationButtonWidget"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "10.12",
        "introducedAt": "10.4",
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Class",
    "symbolKind": "class",
    "title": "PDFAnnotationButtonWidget"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "macOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "class"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "PDFAnnotationButtonWidget"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "code": "PDFAnnotationButtonWidget",
              "type": "codeVoice"
            },
            {
              "text": " inherits general annotation behavior from the ",
              "type": "text"
            },
            {
              "code": "PDFAnnotation",
              "type": "codeVoice"
            },
            {
              "text": " class. If you use a ",
              "type": "text"
            },
            {
              "code": "PDFAnnotationButtonWidget",
              "type": "codeVoice"
            },
            {
              "text": " object, your application must handle hit testing, unless you are simply using ",
              "type": "text"
            },
            {
              "code": "PDFView",
              "type": "codeVoice"
            },
            {
              "text": " to display content. This is because ",
              "type": "text"
            },
            {
              "code": "PDFView",
              "type": "codeVoice"
            },
            {
              "text": " automatically handles hit testing for you.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.pdfkit/documentation/PDFKit": {
      "abstract": [
        {
          "text": "Display and manipulate PDF documents in your apps.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.pdfkit/documentation/PDFKit",
      "kind": "symbol",
      "role": "collection",
      "title": "PDFKit",
      "type": "topic",
      "url": "/documentation/pdfkit"
    },
    "doc://com.apple.pdfkit/documentation/PDFKit/PDFAnnotation": {
      "abstract": [
        {
          "text": "An annotation in a PDF document.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "PDFAnnotation"
        }
      ],
      "identifier": "doc://com.apple.pdfkit/documentation/PDFKit/PDFAnnotation",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PDFAnnotation"
        }
      ],
      "role": "symbol",
      "title": "PDFAnnotation",
      "type": "topic",
      "url": "/documentation/pdfkit/pdfannotation"
    },
    "doc://com.apple.pdfkit/documentation/PDFKit/PDFAnnotationButtonWidget": {
      "abstract": [
        {
          "text": "A ",
          "type": "text"
        },
        {
          "code": "PDFAnnotationButtonWidget",
          "type": "codeVoice"
        },
        {
          "text": " object provides user interactivity on a page of a PDF document. There are three types of buttons available: push button, radio button, and checkbox.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "PDFAnnotationButtonWidget"
        }
      ],
      "identifier": "doc://com.apple.pdfkit/documentation/PDFKit/PDFAnnotationButtonWidget",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PDFAnnotationButtonWidget"
        }
      ],
      "role": "symbol",
      "title": "PDFAnnotationButtonWidget",
      "type": "topic",
      "url": "/documentation/pdfkit/pdfannotationbuttonwidget"
    },
    "doc://com.apple.pdfkit/documentation/PDFKit/PDFAnnotationButtonWidget/allowsToggleToOff()": {
      "abstract": [
        {
          "text": "Returns a Boolean value indicating whether a radio button behaves in a toggling manner.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "allowsToggleToOff"
        },
        {
          "kind": "text",
          "text": "() -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.pdfkit/documentation/PDFKit/PDFAnnotationButtonWidget/allowsToggleToOff()",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "allowsToggleToOff"
        }
      ],
      "role": "symbol",
      "title": "allowsToggleToOff()",
      "type": "topic",
      "url": "/documentation/pdfkit/pdfannotationbuttonwidget/allowstoggletooff()"
    },
    "doc://com.apple.pdfkit/documentation/PDFKit/PDFAnnotationButtonWidget/backgroundColor()": {
      "abstract": [
        {
          "text": "Returns the background color of the control.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "backgroundColor"
        },
        {
          "kind": "text",
          "text": "() -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSColor",
          "text": "NSColor"
        },
        {
          "kind": "text",
          "text": "!"
        }
      ],
      "identifier": "doc://com.apple.pdfkit/documentation/PDFKit/PDFAnnotationButtonWidget/backgroundColor()",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "backgroundColor"
        }
      ],
      "role": "symbol",
      "title": "backgroundColor()",
      "type": "topic",
      "url": "/documentation/pdfkit/pdfannotationbuttonwidget/backgroundcolor()"
    },
    "doc://com.apple.pdfkit/documentation/PDFKit/PDFAnnotationButtonWidget/caption()": {
      "abstract": [
        {
          "text": "Returns the text of the label on a push button control.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "caption"
        },
        {
          "kind": "text",
          "text": "() -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": "!"
        }
      ],
      "identifier": "doc://com.apple.pdfkit/documentation/PDFKit/PDFAnnotationButtonWidget/caption()",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "caption"
        }
      ],
      "role": "symbol",
      "title": "caption()",
      "type": "topic",
      "url": "/documentation/pdfkit/pdfannotationbuttonwidget/caption()"
    },
    "doc://com.apple.pdfkit/documentation/PDFKit/PDFAnnotationButtonWidget/controlType()": {
      "abstract": [
        {
          "text": "Returns the type of the control.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "controlType"
        },
        {
          "kind": "text",
          "text": "() -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@PDFWidgetControlType",
          "text": "PDFWidgetControlType"
        }
      ],
      "identifier": "doc://com.apple.pdfkit/documentation/PDFKit/PDFAnnotationButtonWidget/controlType()",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "controlType"
        }
      ],
      "role": "symbol",
      "title": "controlType()",
      "type": "topic",
      "url": "/documentation/pdfkit/pdfannotationbuttonwidget/controltype()"
    },
    "doc://com.apple.pdfkit/documentation/PDFKit/PDFAnnotationButtonWidget/fieldName()": {
      "abstract": [
        {
          "text": "Returns the internal name of a field (used for reset-form actions).",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "fieldName"
        },
        {
          "kind": "text",
          "text": "() -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": "!"
        }
      ],
      "identifier": "doc://com.apple.pdfkit/documentation/PDFKit/PDFAnnotationButtonWidget/fieldName()",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "fieldName"
        }
      ],
      "role": "symbol",
      "title": "fieldName()",
      "type": "topic",
      "url": "/documentation/pdfkit/pdfannotationbuttonwidget/fieldname()"
    },
    "doc://com.apple.pdfkit/documentation/PDFKit/PDFAnnotationButtonWidget/font()": {
      "abstract": [
        {
          "text": "Returns the font used in the control’s label.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "font"
        },
        {
          "kind": "text",
          "text": "() -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSFont",
          "text": "NSFont"
        },
        {
          "kind": "text",
          "text": "!"
        }
      ],
      "identifier": "doc://com.apple.pdfkit/documentation/PDFKit/PDFAnnotationButtonWidget/font()",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "font"
        }
      ],
      "role": "symbol",
      "title": "font()",
      "type": "topic",
      "url": "/documentation/pdfkit/pdfannotationbuttonwidget/font()"
    },
    "doc://com.apple.pdfkit/documentation/PDFKit/PDFAnnotationButtonWidget/fontColor()": {
      "abstract": [
        {
          "text": "Returns the font color used in the control’s label.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "fontColor"
        },
        {
          "kind": "text",
          "text": "() -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSColor",
          "text": "NSColor"
        },
        {
          "kind": "text",
          "text": "!"
        }
      ],
      "identifier": "doc://com.apple.pdfkit/documentation/PDFKit/PDFAnnotationButtonWidget/fontColor()",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "fontColor"
        }
      ],
      "role": "symbol",
      "title": "fontColor()",
      "type": "topic",
      "url": "/documentation/pdfkit/pdfannotationbuttonwidget/fontcolor()"
    },
    "doc://com.apple.pdfkit/documentation/PDFKit/PDFAnnotationButtonWidget/onStateValue()": {
      "abstract": [
        {
          "text": "Returns the string associated with the on state of a radio button or checkbox control.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "onStateValue"
        },
        {
          "kind": "text",
          "text": "() -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": "!"
        }
      ],
      "identifier": "doc://com.apple.pdfkit/documentation/PDFKit/PDFAnnotationButtonWidget/onStateValue()",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "onStateValue"
        }
      ],
      "role": "symbol",
      "title": "onStateValue()",
      "type": "topic",
      "url": "/documentation/pdfkit/pdfannotationbuttonwidget/onstatevalue()"
    },
    "doc://com.apple.pdfkit/documentation/PDFKit/PDFAnnotationButtonWidget/setAllowsToggleToOff(_:)": {
      "abstract": [],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "setAllowsToggleToOff"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.pdfkit/documentation/PDFKit/PDFAnnotationButtonWidget/setAllowsToggleToOff(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "setAllowsToggleToOff:"
        }
      ],
      "role": "symbol",
      "title": "setAllowsToggleToOff(_:)",
      "type": "topic",
      "url": "/documentation/pdfkit/pdfannotationbuttonwidget/setallowstoggletooff(_:)"
    },
    "doc://com.apple.pdfkit/documentation/PDFKit/PDFAnnotationButtonWidget/setBackgroundColor(_:)": {
      "abstract": [
        {
          "text": "Sets the control’s background color.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "setBackgroundColor"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSColor",
          "text": "NSColor"
        },
        {
          "kind": "text",
          "text": "!)"
        }
      ],
      "identifier": "doc://com.apple.pdfkit/documentation/PDFKit/PDFAnnotationButtonWidget/setBackgroundColor(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "setBackgroundColor:"
        }
      ],
      "role": "symbol",
      "title": "setBackgroundColor(_:)",
      "type": "topic",
      "url": "/documentation/pdfkit/pdfannotationbuttonwidget/setbackgroundcolor(_:)"
    },
    "doc://com.apple.pdfkit/documentation/PDFKit/PDFAnnotationButtonWidget/setCaption(_:)": {
      "abstract": [
        {
          "text": "Sets the text of the label on a push button control.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "setCaption"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": "!)"
        }
      ],
      "identifier": "doc://com.apple.pdfkit/documentation/PDFKit/PDFAnnotationButtonWidget/setCaption(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "setCaption:"
        }
      ],
      "role": "symbol",
      "title": "setCaption(_:)",
      "type": "topic",
      "url": "/documentation/pdfkit/pdfannotationbuttonwidget/setcaption(_:)"
    },
    "doc://com.apple.pdfkit/documentation/PDFKit/PDFAnnotationButtonWidget/setControlType(_:)": {
      "abstract": [
        {
          "text": "Sets the type of the control.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "setControlType"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@PDFWidgetControlType",
          "text": "PDFWidgetControlType"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.pdfkit/documentation/PDFKit/PDFAnnotationButtonWidget/setControlType(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "setControlType:"
        }
      ],
      "role": "symbol",
      "title": "setControlType(_:)",
      "type": "topic",
      "url": "/documentation/pdfkit/pdfannotationbuttonwidget/setcontroltype(_:)"
    },
    "doc://com.apple.pdfkit/documentation/PDFKit/PDFAnnotationButtonWidget/setFieldName(_:)": {
      "abstract": [
        {
          "text": "Sets the internal name of a field (used for reset-form actions).",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "setFieldName"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": "!)"
        }
      ],
      "identifier": "doc://com.apple.pdfkit/documentation/PDFKit/PDFAnnotationButtonWidget/setFieldName(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "setFieldName:"
        }
      ],
      "role": "symbol",
      "title": "setFieldName(_:)",
      "type": "topic",
      "url": "/documentation/pdfkit/pdfannotationbuttonwidget/setfieldname(_:)"
    },
    "doc://com.apple.pdfkit/documentation/PDFKit/PDFAnnotationButtonWidget/setFont(_:)": {
      "abstract": [
        {
          "text": "Sets the font of the control’s label.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "setFont"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSFont",
          "text": "NSFont"
        },
        {
          "kind": "text",
          "text": "!)"
        }
      ],
      "identifier": "doc://com.apple.pdfkit/documentation/PDFKit/PDFAnnotationButtonWidget/setFont(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "setFont:"
        }
      ],
      "role": "symbol",
      "title": "setFont(_:)",
      "type": "topic",
      "url": "/documentation/pdfkit/pdfannotationbuttonwidget/setfont(_:)"
    },
    "doc://com.apple.pdfkit/documentation/PDFKit/PDFAnnotationButtonWidget/setFontColor(_:)": {
      "abstract": [
        {
          "text": "Sets the font color used in the control’s label.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "setFontColor"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSColor",
          "text": "NSColor"
        },
        {
          "kind": "text",
          "text": "!)"
        }
      ],
      "identifier": "doc://com.apple.pdfkit/documentation/PDFKit/PDFAnnotationButtonWidget/setFontColor(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "setFontColor:"
        }
      ],
      "role": "symbol",
      "title": "setFontColor(_:)",
      "type": "topic",
      "url": "/documentation/pdfkit/pdfannotationbuttonwidget/setfontcolor(_:)"
    },
    "doc://com.apple.pdfkit/documentation/PDFKit/PDFAnnotationButtonWidget/setOnStateValue(_:)": {
      "abstract": [
        {
          "text": "Sets the string that is associated with the on state of a radio button or checkbox control.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "setOnStateValue"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": "!)"
        }
      ],
      "identifier": "doc://com.apple.pdfkit/documentation/PDFKit/PDFAnnotationButtonWidget/setOnStateValue(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "setOnStateValue:"
        }
      ],
      "role": "symbol",
      "title": "setOnStateValue(_:)",
      "type": "topic",
      "url": "/documentation/pdfkit/pdfannotationbuttonwidget/setonstatevalue(_:)"
    },
    "doc://com.apple.pdfkit/documentation/PDFKit/PDFAnnotationButtonWidget/setState(_:)": {
      "abstract": [
        {
          "text": "Sets the state of the control.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "setState"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.pdfkit/documentation/PDFKit/PDFAnnotationButtonWidget/setState(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "setState:"
        }
      ],
      "role": "symbol",
      "title": "setState(_:)",
      "type": "topic",
      "url": "/documentation/pdfkit/pdfannotationbuttonwidget/setstate(_:)"
    },
    "doc://com.apple.pdfkit/documentation/PDFKit/PDFAnnotationButtonWidget/state()": {
      "abstract": [
        {
          "text": "Returns the state of the control.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "state"
        },
        {
          "kind": "text",
          "text": "() -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.pdfkit/documentation/PDFKit/PDFAnnotationButtonWidget/state()",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "state"
        }
      ],
      "role": "symbol",
      "title": "state()",
      "type": "topic",
      "url": "/documentation/pdfkit/pdfannotationbuttonwidget/state()"
    },
    "doc://com.apple.pdfkit/documentation/PDFKit/PDFAnnotationChoiceWidget": {
      "abstract": [
        {
          "text": "A ",
          "type": "text"
        },
        {
          "code": "PDFAnnotationChoiceWidget",
          "type": "codeVoice"
        },
        {
          "text": " object provides user interactivity on a page of a PDF document, in the form of pop-up menus and lists.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "PDFAnnotationChoiceWidget"
        }
      ],
      "identifier": "doc://com.apple.pdfkit/documentation/PDFKit/PDFAnnotationChoiceWidget",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PDFAnnotationChoiceWidget"
        }
      ],
      "role": "symbol",
      "title": "PDFAnnotationChoiceWidget",
      "type": "topic",
      "url": "/documentation/pdfkit/pdfannotationchoicewidget"
    },
    "doc://com.apple.pdfkit/documentation/PDFKit/PDFAnnotationCircle": {
      "abstract": [],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "PDFAnnotationCircle"
        }
      ],
      "identifier": "doc://com.apple.pdfkit/documentation/PDFKit/PDFAnnotationCircle",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PDFAnnotationCircle"
        }
      ],
      "role": "symbol",
      "title": "PDFAnnotationCircle",
      "type": "topic",
      "url": "/documentation/pdfkit/pdfannotationcircle"
    },
    "doc://com.apple.pdfkit/documentation/PDFKit/PDFAnnotationFreeText": {
      "abstract": [
        {
          "text": "A ",
          "type": "text"
        },
        {
          "code": "PDFAnnotationFreeText",
          "type": "codeVoice"
        },
        {
          "text": " object displays text on a page.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "PDFAnnotationFreeText"
        }
      ],
      "identifier": "doc://com.apple.pdfkit/documentation/PDFKit/PDFAnnotationFreeText",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PDFAnnotationFreeText"
        }
      ],
      "role": "symbol",
      "title": "PDFAnnotationFreeText",
      "type": "topic",
      "url": "/documentation/pdfkit/pdfannotationfreetext"
    },
    "doc://com.apple.pdfkit/documentation/PDFKit/PDFAnnotationInk": {
      "abstract": [],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "PDFAnnotationInk"
        }
      ],
      "identifier": "doc://com.apple.pdfkit/documentation/PDFKit/PDFAnnotationInk",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PDFAnnotationInk"
        }
      ],
      "role": "symbol",
      "title": "PDFAnnotationInk",
      "type": "topic",
      "url": "/documentation/pdfkit/pdfannotationink"
    },
    "doc://com.apple.pdfkit/documentation/PDFKit/PDFAnnotationLine": {
      "abstract": [
        {
          "text": "A ",
          "type": "text"
        },
        {
          "code": "PDFAnnotationLine",
          "type": "codeVoice"
        },
        {
          "text": " object displays a single line on a page.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "PDFAnnotationLine"
        }
      ],
      "identifier": "doc://com.apple.pdfkit/documentation/PDFKit/PDFAnnotationLine",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PDFAnnotationLine"
        }
      ],
      "role": "symbol",
      "title": "PDFAnnotationLine",
      "type": "topic",
      "url": "/documentation/pdfkit/pdfannotationline"
    },
    "doc://com.apple.pdfkit/documentation/PDFKit/PDFAnnotationLink": {
      "abstract": [],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "PDFAnnotationLink"
        }
      ],
      "identifier": "doc://com.apple.pdfkit/documentation/PDFKit/PDFAnnotationLink",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PDFAnnotationLink"
        }
      ],
      "role": "symbol",
      "title": "PDFAnnotationLink",
      "type": "topic",
      "url": "/documentation/pdfkit/pdfannotationlink"
    },
    "doc://com.apple.pdfkit/documentation/PDFKit/PDFAnnotationMarkup": {
      "abstract": [
        {
          "text": "A ",
          "type": "text"
        },
        {
          "code": "PDFAnnotationMarkup",
          "type": "codeVoice"
        },
        {
          "text": " object appears as highlighting, underlining, or a strikethrough style applied to the text of a document.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "PDFAnnotationMarkup"
        }
      ],
      "identifier": "doc://com.apple.pdfkit/documentation/PDFKit/PDFAnnotationMarkup",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PDFAnnotationMarkup"
        }
      ],
      "role": "symbol",
      "title": "PDFAnnotationMarkup",
      "type": "topic",
      "url": "/documentation/pdfkit/pdfannotationmarkup"
    },
    "doc://com.apple.pdfkit/documentation/PDFKit/PDFAnnotationPopup": {
      "abstract": [
        {
          "text": "A ",
          "type": "text"
        },
        {
          "code": "PDFAnnotationPopup",
          "type": "codeVoice"
        },
        {
          "text": " object provides user interactivity on a PDF page in the form of a pop-up menu.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "PDFAnnotationPopup"
        }
      ],
      "identifier": "doc://com.apple.pdfkit/documentation/PDFKit/PDFAnnotationPopup",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PDFAnnotationPopup"
        }
      ],
      "role": "symbol",
      "title": "PDFAnnotationPopup",
      "type": "topic",
      "url": "/documentation/pdfkit/pdfannotationpopup"
    },
    "doc://com.apple.pdfkit/documentation/PDFKit/PDFAnnotationSquare": {
      "abstract": [
        {
          "text": "A rectangle annotation on a page.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "PDFAnnotationSquare"
        }
      ],
      "identifier": "doc://com.apple.pdfkit/documentation/PDFKit/PDFAnnotationSquare",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PDFAnnotationSquare"
        }
      ],
      "role": "symbol",
      "title": "PDFAnnotationSquare",
      "type": "topic",
      "url": "/documentation/pdfkit/pdfannotationsquare"
    },
    "doc://com.apple.pdfkit/documentation/PDFKit/PDFAnnotationStamp": {
      "abstract": [
        {
          "text": "A ",
          "type": "text"
        },
        {
          "code": "PDFAnnotationStamp",
          "type": "codeVoice"
        },
        {
          "text": " object allows you to display a word or phrase, such as “Confidential,” in a PDF page.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "PDFAnnotationStamp"
        }
      ],
      "identifier": "doc://com.apple.pdfkit/documentation/PDFKit/PDFAnnotationStamp",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PDFAnnotationStamp"
        }
      ],
      "role": "symbol",
      "title": "PDFAnnotationStamp",
      "type": "topic",
      "url": "/documentation/pdfkit/pdfannotationstamp"
    },
    "doc://com.apple.pdfkit/documentation/PDFKit/PDFAnnotationSubtype": {
      "abstract": [
        {
          "text": "The type of annotation, such as circle, text, or ink.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "PDFAnnotationSubtype"
        }
      ],
      "identifier": "doc://com.apple.pdfkit/documentation/PDFKit/PDFAnnotationSubtype",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PDFAnnotationSubtype"
        }
      ],
      "role": "symbol",
      "title": "PDFAnnotationSubtype",
      "type": "topic",
      "url": "/documentation/pdfkit/pdfannotationsubtype"
    },
    "doc://com.apple.pdfkit/documentation/PDFKit/PDFAnnotationText": {
      "abstract": [
        {
          "text": "A ",
          "type": "text"
        },
        {
          "code": "PDFAnnotationText",
          "type": "codeVoice"
        },
        {
          "text": " object displays as an icon (such as a “sticky note”) attached to a specified point in the PDF document.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "PDFAnnotationText"
        }
      ],
      "identifier": "doc://com.apple.pdfkit/documentation/PDFKit/PDFAnnotationText",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PDFAnnotationText"
        }
      ],
      "role": "symbol",
      "title": "PDFAnnotationText",
      "type": "topic",
      "url": "/documentation/pdfkit/pdfannotationtext"
    },
    "doc://com.apple.pdfkit/documentation/PDFKit/PDFAnnotationTextWidget": {
      "abstract": [
        {
          "text": "A ",
          "type": "text"
        },
        {
          "code": "PDFAnnotationTextWidget",
          "type": "codeVoice"
        },
        {
          "text": " object allows you to manage the appearance and content of text fields.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "PDFAnnotationTextWidget"
        }
      ],
      "identifier": "doc://com.apple.pdfkit/documentation/PDFKit/PDFAnnotationTextWidget",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PDFAnnotationTextWidget"
        }
      ],
      "role": "symbol",
      "title": "PDFAnnotationTextWidget",
      "type": "topic",
      "url": "/documentation/pdfkit/pdfannotationtextwidget"
    },
    "doc://com.apple.pdfkit/documentation/PDFKit/PDFWidgetControlType": {
      "abstract": [
        {
          "text": "The types of annotation buttons.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "PDFWidgetControlType"
        }
      ],
      "identifier": "doc://com.apple.pdfkit/documentation/PDFKit/PDFWidgetControlType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PDFWidgetControlType"
        }
      ],
      "role": "symbol",
      "title": "PDFWidgetControlType",
      "type": "topic",
      "url": "/documentation/pdfkit/pdfwidgetcontroltype"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)NSCoding": {
      "abstract": [
        {
          "text": "A protocol that enables an object to be encoded and decoded for archiving and distribution.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "protocol "
        },
        {
          "kind": "identifier",
          "text": "NSCoding"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSCoding",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSCoding",
      "type": "topic",
      "url": "/documentation/foundation/nscoding"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)NSCopying": {
      "abstract": [
        {
          "text": "A protocol that objects adopt to provide functional copies of themselves.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "protocol "
        },
        {
          "kind": "identifier",
          "text": "NSCopying"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSCopying",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSCopying",
      "type": "topic",
      "url": "/documentation/foundation/nscopying"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)NSObject": {
      "abstract": [
        {
          "text": "The group of methods that are fundamental to all Objective-C objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "protocol "
        },
        {
          "kind": "identifier",
          "text": "NSObjectProtocol"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSObject",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSObjectProtocol",
      "type": "topic",
      "url": "/documentation/objectivec/nsobjectprotocol"
    },
    "doc://com.externally.resolved.symbol/s:SH": {
      "abstract": [
        {
          "text": "A type that can be hashed into a `Hasher` to produce an integer hash value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Hashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SQ",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SH",
      "kind": "symbol",
      "role": "symbol",
      "title": "Hashable",
      "type": "topic",
      "url": "/documentation/Swift/Hashable"
    },
    "doc://com.externally.resolved.symbol/s:SQ": {
      "abstract": [
        {
          "text": "A type that can be compared for value equality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SQ",
      "kind": "symbol",
      "role": "symbol",
      "title": "Equatable",
      "type": "topic",
      "url": "/documentation/Swift/Equatable"
    },
    "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP": {
      "abstract": [
        {
          "text": "A type with a customized textual representation.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CustomStringConvertible"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CustomStringConvertible",
      "type": "topic",
      "url": "/documentation/Swift/CustomStringConvertible"
    },
    "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP": {
      "abstract": [
        {
          "text": "A type with a customized textual representation suitable for debugging purposes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CustomDebugStringConvertible"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CustomDebugStringConvertible",
      "type": "topic",
      "url": "/documentation/Swift/CustomDebugStringConvertible"
    },
    "doc://com.externally.resolved.symbol/s:s7CVarArgP": {
      "abstract": [
        {
          "text": "A type whose instances can be encoded, and appropriately passed, as elements of a C `va_list`.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CVarArg"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s7CVarArgP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CVarArg",
      "type": "topic",
      "url": "/documentation/Swift/CVarArg"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.apple.pdfkit/documentation/PDFKit/PDFAnnotation"
      ],
      "kind": "relationships",
      "title": "Inherits From",
      "type": "inheritsFrom"
    },
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:s7CVarArgP",
        "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP",
        "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP",
        "doc://com.externally.resolved.symbol/s:SQ",
        "doc://com.externally.resolved.symbol/s:SH",
        "doc://com.externally.resolved.symbol/c:objc(pl)NSCoding",
        "doc://com.externally.resolved.symbol/c:objc(pl)NSCopying",
        "doc://com.externally.resolved.symbol/c:objc(pl)NSObject"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Deprecated-Annotation-Types",
      "generated": true,
      "identifiers": [
        "doc://com.apple.pdfkit/documentation/PDFKit/PDFAnnotationChoiceWidget",
        "doc://com.apple.pdfkit/documentation/PDFKit/PDFAnnotationCircle",
        "doc://com.apple.pdfkit/documentation/PDFKit/PDFAnnotationFreeText",
        "doc://com.apple.pdfkit/documentation/PDFKit/PDFAnnotationInk",
        "doc://com.apple.pdfkit/documentation/PDFKit/PDFAnnotationLine",
        "doc://com.apple.pdfkit/documentation/PDFKit/PDFAnnotationLink",
        "doc://com.apple.pdfkit/documentation/PDFKit/PDFAnnotationMarkup",
        "doc://com.apple.pdfkit/documentation/PDFKit/PDFAnnotationPopup",
        "doc://com.apple.pdfkit/documentation/PDFKit/PDFAnnotationSquare",
        "doc://com.apple.pdfkit/documentation/PDFKit/PDFAnnotationStamp",
        "doc://com.apple.pdfkit/documentation/PDFKit/PDFAnnotationText",
        "doc://com.apple.pdfkit/documentation/PDFKit/PDFAnnotationTextWidget"
      ],
      "title": "Deprecated Annotation Types"
    }
  ],
  "topicSections": [
    {
      "anchor": "Getting-and-Setting-the-Control-Type",
      "identifiers": [
        "doc://com.apple.pdfkit/documentation/PDFKit/PDFAnnotationButtonWidget/controlType()",
        "doc://com.apple.pdfkit/documentation/PDFKit/PDFAnnotationButtonWidget/setControlType(_:)"
      ],
      "title": "Getting and Setting the Control Type"
    },
    {
      "anchor": "Getting-and-Setting-the-Controls-State",
      "identifiers": [
        "doc://com.apple.pdfkit/documentation/PDFKit/PDFAnnotationButtonWidget/state()",
        "doc://com.apple.pdfkit/documentation/PDFKit/PDFAnnotationButtonWidget/setState(_:)"
      ],
      "title": "Getting and Setting the Control’s State"
    },
    {
      "anchor": "Getting-and-Setting-the-Controls-Appearance",
      "identifiers": [
        "doc://com.apple.pdfkit/documentation/PDFKit/PDFAnnotationButtonWidget/backgroundColor()",
        "doc://com.apple.pdfkit/documentation/PDFKit/PDFAnnotationButtonWidget/setBackgroundColor(_:)"
      ],
      "title": "Getting and Setting the Control’s Appearance"
    },
    {
      "anchor": "Getting-and-Setting-the-Control-Label-Font-Attributes",
      "identifiers": [
        "doc://com.apple.pdfkit/documentation/PDFKit/PDFAnnotationButtonWidget/font()",
        "doc://com.apple.pdfkit/documentation/PDFKit/PDFAnnotationButtonWidget/setFont(_:)",
        "doc://com.apple.pdfkit/documentation/PDFKit/PDFAnnotationButtonWidget/fontColor()",
        "doc://com.apple.pdfkit/documentation/PDFKit/PDFAnnotationButtonWidget/setFontColor(_:)"
      ],
      "title": "Getting and Setting the Control Label Font Attributes"
    },
    {
      "anchor": "Getting-and-Setting-the-Control-Label-Text",
      "identifiers": [
        "doc://com.apple.pdfkit/documentation/PDFKit/PDFAnnotationButtonWidget/caption()",
        "doc://com.apple.pdfkit/documentation/PDFKit/PDFAnnotationButtonWidget/setCaption(_:)"
      ],
      "title": "Getting and Setting the Control Label Text"
    },
    {
      "anchor": "Managing-Radio-Button-Behavior",
      "identifiers": [
        "doc://com.apple.pdfkit/documentation/PDFKit/PDFAnnotationButtonWidget/allowsToggleToOff()"
      ],
      "title": "Managing Radio Button Behavior"
    },
    {
      "anchor": "Managing-Control-State-Values-and-Form-Fields",
      "identifiers": [
        "doc://com.apple.pdfkit/documentation/PDFKit/PDFAnnotationButtonWidget/onStateValue()",
        "doc://com.apple.pdfkit/documentation/PDFKit/PDFAnnotationButtonWidget/setOnStateValue(_:)",
        "doc://com.apple.pdfkit/documentation/PDFKit/PDFAnnotationButtonWidget/fieldName()",
        "doc://com.apple.pdfkit/documentation/PDFKit/PDFAnnotationButtonWidget/setFieldName(_:)"
      ],
      "title": "Managing Control State Values and Form Fields"
    },
    {
      "anchor": "Constants",
      "identifiers": [
        "doc://com.apple.pdfkit/documentation/PDFKit/PDFWidgetControlType"
      ],
      "title": "Constants"
    },
    {
      "anchor": "Instance-Methods",
      "identifiers": [
        "doc://com.apple.pdfkit/documentation/PDFKit/PDFAnnotationButtonWidget/setAllowsToggleToOff(_:)"
      ],
      "title": "Instance Methods"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "deprecatedAt": "10.12",
              "introducedAt": "10.4",
              "name": "macOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Class"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "PDFAnnotationButtonWidget"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "class"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PDFAnnotationButtonWidget"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "PDFAnnotationButtonWidget"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.pdfkit/documentation/PDFKit"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Getting-and-Setting-the-Control-Type",
              "identifiers": [
                "doc://com.apple.pdfkit/documentation/PDFKit/PDFAnnotationButtonWidget/controlType()",
                "doc://com.apple.pdfkit/documentation/PDFKit/PDFAnnotationButtonWidget/setControlType(_:)"
              ],
              "title": "Getting and Setting the Control Type"
            },
            {
              "anchor": "Getting-and-Setting-the-Controls-State",
              "identifiers": [
                "doc://com.apple.pdfkit/documentation/PDFKit/PDFAnnotationButtonWidget/state()",
                "doc://com.apple.pdfkit/documentation/PDFKit/PDFAnnotationButtonWidget/setState(_:)"
              ],
              "title": "Getting and Setting the Control’s State"
            },
            {
              "anchor": "Getting-and-Setting-the-Controls-Appearance",
              "identifiers": [
                "doc://com.apple.pdfkit/documentation/PDFKit/PDFAnnotationButtonWidget/backgroundColor()",
                "doc://com.apple.pdfkit/documentation/PDFKit/PDFAnnotationButtonWidget/setBackgroundColor(_:)"
              ],
              "title": "Getting and Setting the Control’s Appearance"
            },
            {
              "anchor": "Getting-and-Setting-the-Control-Label-Font-Attributes",
              "identifiers": [
                "doc://com.apple.pdfkit/documentation/PDFKit/PDFAnnotationButtonWidget/font()",
                "doc://com.apple.pdfkit/documentation/PDFKit/PDFAnnotationButtonWidget/setFont(_:)",
                "doc://com.apple.pdfkit/documentation/PDFKit/PDFAnnotationButtonWidget/fontColor()",
                "doc://com.apple.pdfkit/documentation/PDFKit/PDFAnnotationButtonWidget/setFontColor(_:)"
              ],
              "title": "Getting and Setting the Control Label Font Attributes"
            },
            {
              "anchor": "Getting-and-Setting-the-Control-Label-Text",
              "identifiers": [
                "doc://com.apple.pdfkit/documentation/PDFKit/PDFAnnotationButtonWidget/caption()",
                "doc://com.apple.pdfkit/documentation/PDFKit/PDFAnnotationButtonWidget/setCaption(_:)"
              ],
              "title": "Getting and Setting the Control Label Text"
            },
            {
              "anchor": "Managing-Radio-Button-Behavior",
              "identifiers": [
                "doc://com.apple.pdfkit/documentation/PDFKit/PDFAnnotationButtonWidget/allowsToggleToOff()"
              ],
              "title": "Managing Radio Button Behavior"
            },
            {
              "anchor": "Managing-Control-State-Values-and-Form-Fields",
              "identifiers": [
                "doc://com.apple.pdfkit/documentation/PDFKit/PDFAnnotationButtonWidget/onStateValue()",
                "doc://com.apple.pdfkit/documentation/PDFKit/PDFAnnotationButtonWidget/setOnStateValue(_:)",
                "doc://com.apple.pdfkit/documentation/PDFKit/PDFAnnotationButtonWidget/fieldName()",
                "doc://com.apple.pdfkit/documentation/PDFKit/PDFAnnotationButtonWidget/setFieldName(_:)"
              ],
              "title": "Managing Control State Values and Form Fields"
            },
            {
              "anchor": "Constants",
              "identifiers": [
                "doc://com.apple.pdfkit/documentation/PDFKit/PDFWidgetControlType"
              ],
              "title": "Constants"
            },
            {
              "anchor": "Instance-Methods",
              "identifiers": [
                "doc://com.apple.pdfkit/documentation/PDFKit/PDFAnnotationButtonWidget/setAllowsToggleToOff(_:)"
              ],
              "title": "Instance Methods"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": [
            {
              "identifiers": [
                "doc://com.apple.pdfkit/documentation/PDFKit/PDFAnnotation"
              ],
              "kind": "relationships",
              "title": "Inherits From",
              "type": "inheritsFrom"
            },
            {
              "identifiers": [
                "doc://com.externally.resolved.symbol/c:objc(pl)NSCopying"
              ],
              "kind": "relationships",
              "title": "Conforms To",
              "type": "conformsTo"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Deprecated-Annotation-Types",
              "generated": true,
              "identifiers": [
                "doc://com.apple.pdfkit/documentation/PDFKit/PDFAnnotationChoiceWidget",
                "doc://com.apple.pdfkit/documentation/PDFKit/PDFAnnotationCircle",
                "doc://com.apple.pdfkit/documentation/PDFKit/PDFAnnotationFreeText",
                "doc://com.apple.pdfkit/documentation/PDFKit/PDFAnnotationInk",
                "doc://com.apple.pdfkit/documentation/PDFKit/PDFAnnotationLine",
                "doc://com.apple.pdfkit/documentation/PDFKit/PDFAnnotationLink",
                "doc://com.apple.pdfkit/documentation/PDFKit/PDFAnnotationMarkup",
                "doc://com.apple.pdfkit/documentation/PDFKit/PDFAnnotationPopup",
                "doc://com.apple.pdfkit/documentation/PDFKit/PDFAnnotationSquare",
                "doc://com.apple.pdfkit/documentation/PDFKit/PDFAnnotationStamp",
                "doc://com.apple.pdfkit/documentation/PDFKit/PDFAnnotationText",
                "doc://com.apple.pdfkit/documentation/PDFKit/PDFAnnotationTextWidget"
              ],
              "title": "Deprecated Annotation Types"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "macOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "@interface"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "PDFAnnotationButtonWidget"
                  },
                  {
                    "kind": "text",
                    "text": " : "
                  },
                  {
                    "identifier": "doc://com.apple.pdfkit/documentation/PDFKit/PDFAnnotation",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(cs)PDFAnnotation",
                    "text": "PDFAnnotation"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/deprecationSummary",
          "value": [
            {
              "inlineContent": [
                {
                  "text": "Use ",
                  "type": "text"
                },
                {
                  "identifier": "doc://com.apple.pdfkit/documentation/PDFKit/PDFAnnotationSubtype",
                  "isActive": true,
                  "type": "reference"
                },
                {
                  "text": " instead.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFAnnotationPopup/title",
          "value": "PDFAnnotationPopup"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFAnnotationPopup/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PDFAnnotationPopup"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFAnnotationPopup/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "PDFAnnotationPopup"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFAnnotationLink/title",
          "value": "PDFAnnotationLink"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFAnnotationLink/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PDFAnnotationLink"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFAnnotationLink/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "PDFAnnotationLink"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFAnnotationButtonWidget~1fontColor()/title",
          "value": "fontColor"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFAnnotationButtonWidget~1fontColor()/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "fontColor"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFAnnotationStamp/title",
          "value": "PDFAnnotationStamp"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFAnnotationStamp/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PDFAnnotationStamp"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFAnnotationStamp/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "PDFAnnotationStamp"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFAnnotationButtonWidget~1onStateValue()/title",
          "value": "onStateValue"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFAnnotationButtonWidget~1onStateValue()/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "onStateValue"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFAnnotationButtonWidget~1setControlType(_:)/title",
          "value": "setControlType:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFAnnotationButtonWidget~1setControlType(_:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "setControlType:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFAnnotationSubtype/title",
          "value": "PDFAnnotationSubtype"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFAnnotationSubtype/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PDFAnnotationSubtype"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFAnnotationSubtype/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "PDFAnnotationSubtype"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFAnnotationCircle/title",
          "value": "PDFAnnotationCircle"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFAnnotationCircle/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PDFAnnotationCircle"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFAnnotationCircle/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "PDFAnnotationCircle"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFAnnotationButtonWidget~1setState(_:)/title",
          "value": "setState:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFAnnotationButtonWidget~1setState(_:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "setState:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFAnnotationMarkup/title",
          "value": "PDFAnnotationMarkup"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFAnnotationMarkup/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PDFAnnotationMarkup"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFAnnotationMarkup/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "PDFAnnotationMarkup"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFAnnotation/title",
          "value": "PDFAnnotation"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFAnnotation/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PDFAnnotation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFAnnotation/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "PDFAnnotation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFAnnotationChoiceWidget/title",
          "value": "PDFAnnotationChoiceWidget"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFAnnotationChoiceWidget/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PDFAnnotationChoiceWidget"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFAnnotationChoiceWidget/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "PDFAnnotationChoiceWidget"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFAnnotationButtonWidget~1setOnStateValue(_:)/title",
          "value": "setOnStateValue:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFAnnotationButtonWidget~1setOnStateValue(_:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "setOnStateValue:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFAnnotationButtonWidget~1setBackgroundColor(_:)/title",
          "value": "setBackgroundColor:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFAnnotationButtonWidget~1setBackgroundColor(_:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "setBackgroundColor:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFWidgetControlType/title",
          "value": "PDFWidgetControlType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFWidgetControlType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PDFWidgetControlType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFWidgetControlType/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "PDFWidgetControlType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFAnnotationInk/title",
          "value": "PDFAnnotationInk"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFAnnotationInk/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PDFAnnotationInk"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFAnnotationInk/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "PDFAnnotationInk"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:objc(pl)NSObject/title",
          "value": "NSObject"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFAnnotationButtonWidget~1setCaption(_:)/title",
          "value": "setCaption:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFAnnotationButtonWidget~1setCaption(_:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "setCaption:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFAnnotationButtonWidget~1font()/title",
          "value": "font"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFAnnotationButtonWidget~1font()/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "font"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFAnnotationSquare/title",
          "value": "PDFAnnotationSquare"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFAnnotationSquare/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PDFAnnotationSquare"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFAnnotationSquare/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "PDFAnnotationSquare"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFAnnotationLine/title",
          "value": "PDFAnnotationLine"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFAnnotationLine/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PDFAnnotationLine"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFAnnotationLine/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "PDFAnnotationLine"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFAnnotationButtonWidget~1caption()/title",
          "value": "caption"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFAnnotationButtonWidget~1caption()/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "caption"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFAnnotationTextWidget/title",
          "value": "PDFAnnotationTextWidget"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFAnnotationTextWidget/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PDFAnnotationTextWidget"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFAnnotationTextWidget/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "PDFAnnotationTextWidget"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFAnnotationButtonWidget/title",
          "value": "PDFAnnotationButtonWidget"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFAnnotationButtonWidget/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PDFAnnotationButtonWidget"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFAnnotationButtonWidget/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "PDFAnnotationButtonWidget"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFAnnotationText/title",
          "value": "PDFAnnotationText"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFAnnotationText/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PDFAnnotationText"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFAnnotationText/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "PDFAnnotationText"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFAnnotationButtonWidget~1allowsToggleToOff()/title",
          "value": "allowsToggleToOff"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFAnnotationButtonWidget~1allowsToggleToOff()/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "allowsToggleToOff"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFAnnotationButtonWidget~1controlType()/title",
          "value": "controlType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFAnnotationButtonWidget~1controlType()/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "controlType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFAnnotationFreeText/title",
          "value": "PDFAnnotationFreeText"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFAnnotationFreeText/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PDFAnnotationFreeText"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFAnnotationFreeText/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "PDFAnnotationFreeText"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFAnnotationButtonWidget~1setFieldName(_:)/title",
          "value": "setFieldName:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFAnnotationButtonWidget~1setFieldName(_:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "setFieldName:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFAnnotationButtonWidget~1backgroundColor()/title",
          "value": "backgroundColor"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFAnnotationButtonWidget~1backgroundColor()/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "backgroundColor"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFAnnotationButtonWidget~1setFontColor(_:)/title",
          "value": "setFontColor:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFAnnotationButtonWidget~1setFontColor(_:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "setFontColor:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFAnnotationButtonWidget~1setAllowsToggleToOff(_:)/title",
          "value": "setAllowsToggleToOff:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFAnnotationButtonWidget~1setAllowsToggleToOff(_:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "setAllowsToggleToOff:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFAnnotationButtonWidget~1fieldName()/title",
          "value": "fieldName"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFAnnotationButtonWidget~1fieldName()/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "fieldName"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFAnnotationButtonWidget~1state()/title",
          "value": "state"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFAnnotationButtonWidget~1state()/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "state"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFAnnotationButtonWidget~1setFont(_:)/title",
          "value": "setFont:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFAnnotationButtonWidget~1setFont(_:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "setFont:"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/pdfkit/pdfannotationbuttonwidget"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/pdfkit/pdfannotationbuttonwidget"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
