{
  "diffAvailability": {
    "major": {
      "change": "modified",
      "platform": "Xcode",
      "versions": [
        "16.0",
        "16.3 beta 2"
      ]
    }
  },
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.pdfkit/documentation/PDFKit"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.pdfkit/documentation/PDFKit/PDFAccessPermissions"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@PDFAccessPermissions",
    "fragments": [
      {
        "kind": "keyword",
        "text": "enum"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "PDFAccessPermissions"
      }
    ],
    "modules": [
      {
        "name": "PDFKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "PDFAccessPermissions"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "11.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "11.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "11.0",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.4",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Enumeration",
    "symbolKind": "enum",
    "title": "PDFAccessPermissions"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "enum"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "PDFAccessPermissions"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.pdfkit/documentation/PDFKit": {
      "abstract": [
        {
          "text": "Display and manipulate PDF documents in your apps.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.pdfkit/documentation/PDFKit",
      "kind": "symbol",
      "role": "collection",
      "title": "PDFKit",
      "type": "topic",
      "url": "/documentation/pdfkit"
    },
    "doc://com.apple.pdfkit/documentation/PDFKit/PDFAccessPermissions": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "PDFAccessPermissions"
        }
      ],
      "identifier": "doc://com.apple.pdfkit/documentation/PDFKit/PDFAccessPermissions",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PDFAccessPermissions"
        }
      ],
      "role": "symbol",
      "title": "PDFAccessPermissions",
      "type": "topic",
      "url": "/documentation/pdfkit/pdfaccesspermissions"
    },
    "doc://com.apple.pdfkit/documentation/PDFKit/PDFAccessPermissions/allowsCommenting": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "allowsCommenting"
        }
      ],
      "identifier": "doc://com.apple.pdfkit/documentation/PDFKit/PDFAccessPermissions/allowsCommenting",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PDFAllowsCommenting"
        }
      ],
      "role": "symbol",
      "title": "PDFAccessPermissions.allowsCommenting",
      "type": "topic",
      "url": "/documentation/pdfkit/pdfaccesspermissions/allowscommenting"
    },
    "doc://com.apple.pdfkit/documentation/PDFKit/PDFAccessPermissions/allowsContentAccessibility": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "allowsContentAccessibility"
        }
      ],
      "identifier": "doc://com.apple.pdfkit/documentation/PDFKit/PDFAccessPermissions/allowsContentAccessibility",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PDFAllowsContentAccessibility"
        }
      ],
      "role": "symbol",
      "title": "PDFAccessPermissions.allowsContentAccessibility",
      "type": "topic",
      "url": "/documentation/pdfkit/pdfaccesspermissions/allowscontentaccessibility"
    },
    "doc://com.apple.pdfkit/documentation/PDFKit/PDFAccessPermissions/allowsContentCopying": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "allowsContentCopying"
        }
      ],
      "identifier": "doc://com.apple.pdfkit/documentation/PDFKit/PDFAccessPermissions/allowsContentCopying",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PDFAllowsContentCopying"
        }
      ],
      "role": "symbol",
      "title": "PDFAccessPermissions.allowsContentCopying",
      "type": "topic",
      "url": "/documentation/pdfkit/pdfaccesspermissions/allowscontentcopying"
    },
    "doc://com.apple.pdfkit/documentation/PDFKit/PDFAccessPermissions/allowsDocumentAssembly": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "allowsDocumentAssembly"
        }
      ],
      "identifier": "doc://com.apple.pdfkit/documentation/PDFKit/PDFAccessPermissions/allowsDocumentAssembly",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PDFAllowsDocumentAssembly"
        }
      ],
      "role": "symbol",
      "title": "PDFAccessPermissions.allowsDocumentAssembly",
      "type": "topic",
      "url": "/documentation/pdfkit/pdfaccesspermissions/allowsdocumentassembly"
    },
    "doc://com.apple.pdfkit/documentation/PDFKit/PDFAccessPermissions/allowsDocumentChanges": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "allowsDocumentChanges"
        }
      ],
      "identifier": "doc://com.apple.pdfkit/documentation/PDFKit/PDFAccessPermissions/allowsDocumentChanges",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PDFAllowsDocumentChanges"
        }
      ],
      "role": "symbol",
      "title": "PDFAccessPermissions.allowsDocumentChanges",
      "type": "topic",
      "url": "/documentation/pdfkit/pdfaccesspermissions/allowsdocumentchanges"
    },
    "doc://com.apple.pdfkit/documentation/PDFKit/PDFAccessPermissions/allowsFormFieldEntry": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "allowsFormFieldEntry"
        }
      ],
      "identifier": "doc://com.apple.pdfkit/documentation/PDFKit/PDFAccessPermissions/allowsFormFieldEntry",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PDFAllowsFormFieldEntry"
        }
      ],
      "role": "symbol",
      "title": "PDFAccessPermissions.allowsFormFieldEntry",
      "type": "topic",
      "url": "/documentation/pdfkit/pdfaccesspermissions/allowsformfieldentry"
    },
    "doc://com.apple.pdfkit/documentation/PDFKit/PDFAccessPermissions/allowsHighQualityPrinting": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "allowsHighQualityPrinting"
        }
      ],
      "identifier": "doc://com.apple.pdfkit/documentation/PDFKit/PDFAccessPermissions/allowsHighQualityPrinting",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PDFAllowsHighQualityPrinting"
        }
      ],
      "role": "symbol",
      "title": "PDFAccessPermissions.allowsHighQualityPrinting",
      "type": "topic",
      "url": "/documentation/pdfkit/pdfaccesspermissions/allowshighqualityprinting"
    },
    "doc://com.apple.pdfkit/documentation/PDFKit/PDFAccessPermissions/allowsLowQualityPrinting": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "allowsLowQualityPrinting"
        }
      ],
      "identifier": "doc://com.apple.pdfkit/documentation/PDFKit/PDFAccessPermissions/allowsLowQualityPrinting",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PDFAllowsLowQualityPrinting"
        }
      ],
      "role": "symbol",
      "title": "PDFAccessPermissions.allowsLowQualityPrinting",
      "type": "topic",
      "url": "/documentation/pdfkit/pdfaccesspermissions/allowslowqualityprinting"
    },
    "doc://com.apple.pdfkit/documentation/PDFKit/PDFAccessPermissions/init(rawValue:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "?("
        },
        {
          "kind": "externalParam",
          "text": "rawValue"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Su",
          "text": "UInt"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.pdfkit/documentation/PDFKit/PDFAccessPermissions/init(rawValue:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "init(rawValue:)",
      "type": "topic",
      "url": "/documentation/pdfkit/pdfaccesspermissions/init(rawvalue:)"
    },
    "doc://com.apple.pdfkit/documentation/PDFKit/PDFSelectionGranularity": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "PDFSelectionGranularity"
        }
      ],
      "identifier": "doc://com.apple.pdfkit/documentation/PDFKit/PDFSelectionGranularity",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PDFSelectionGranularity"
        }
      ],
      "role": "symbol",
      "title": "PDFSelectionGranularity",
      "type": "topic",
      "url": "/documentation/pdfkit/pdfselectiongranularity"
    },
    "doc://com.apple.pdfkit/documentation/PDFKit/PDFThumbnailLayoutMode": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "PDFThumbnailLayoutMode"
        }
      ],
      "identifier": "doc://com.apple.pdfkit/documentation/PDFKit/PDFThumbnailLayoutMode",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PDFThumbnailLayoutMode"
        }
      ],
      "role": "symbol",
      "title": "PDFThumbnailLayoutMode",
      "type": "topic",
      "url": "/documentation/pdfkit/pdfthumbnaillayoutmode"
    },
    "doc://com.externally.resolved.symbol/s:SH": {
      "abstract": [
        {
          "text": "A type that can be hashed into a `Hasher` to produce an integer hash value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Hashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SQ",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SH",
      "kind": "symbol",
      "role": "symbol",
      "title": "Hashable",
      "type": "topic",
      "url": "/documentation/Swift/Hashable"
    },
    "doc://com.externally.resolved.symbol/s:SQ": {
      "abstract": [
        {
          "text": "A type that can be compared for value equality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SQ",
      "kind": "symbol",
      "role": "symbol",
      "title": "Equatable",
      "type": "topic",
      "url": "/documentation/Swift/Equatable"
    },
    "doc://com.externally.resolved.symbol/s:SY": {
      "abstract": [
        {
          "text": "A type that can be converted to and from an associated raw value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "RawRepresentable"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SY8RawValueQa",
          "text": "RawValue"
        },
        {
          "kind": "text",
          "text": ">"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SY",
      "kind": "symbol",
      "role": "symbol",
      "title": "RawRepresentable",
      "type": "topic",
      "url": "/documentation/Swift/RawRepresentable"
    },
    "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BitwiseCopyable"
        },
        {
          "kind": "text",
          "text": " : ~Escapable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "BitwiseCopyable",
      "type": "topic",
      "url": "/documentation/Swift/BitwiseCopyable"
    },
    "doc://com.externally.resolved.symbol/s:s8SendableP": {
      "abstract": [
        {
          "text": "A thread-safe type whose values can be shared across arbitrary concurrent contexts without introducing a risk of data races.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Sendable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s8SendableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "Sendable",
      "type": "topic",
      "url": "/documentation/Swift/Sendable"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
        "doc://com.externally.resolved.symbol/s:SQ",
        "doc://com.externally.resolved.symbol/s:SH",
        "doc://com.externally.resolved.symbol/s:SY",
        "doc://com.externally.resolved.symbol/s:s8SendableP"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Enumerations",
      "generated": true,
      "identifiers": [
        "doc://com.apple.pdfkit/documentation/PDFKit/PDFSelectionGranularity",
        "doc://com.apple.pdfkit/documentation/PDFKit/PDFThumbnailLayoutMode"
      ],
      "title": "Enumerations"
    }
  ],
  "topicSections": [
    {
      "anchor": "Enumeration-Cases",
      "identifiers": [
        "doc://com.apple.pdfkit/documentation/PDFKit/PDFAccessPermissions/allowsCommenting",
        "doc://com.apple.pdfkit/documentation/PDFKit/PDFAccessPermissions/allowsContentAccessibility",
        "doc://com.apple.pdfkit/documentation/PDFKit/PDFAccessPermissions/allowsContentCopying",
        "doc://com.apple.pdfkit/documentation/PDFKit/PDFAccessPermissions/allowsDocumentAssembly",
        "doc://com.apple.pdfkit/documentation/PDFKit/PDFAccessPermissions/allowsDocumentChanges",
        "doc://com.apple.pdfkit/documentation/PDFKit/PDFAccessPermissions/allowsFormFieldEntry",
        "doc://com.apple.pdfkit/documentation/PDFKit/PDFAccessPermissions/allowsHighQualityPrinting",
        "doc://com.apple.pdfkit/documentation/PDFKit/PDFAccessPermissions/allowsLowQualityPrinting"
      ],
      "title": "Enumeration Cases"
    },
    {
      "anchor": "Initializers",
      "generated": true,
      "identifiers": [
        "doc://com.apple.pdfkit/documentation/PDFKit/PDFAccessPermissions/init(rawValue:)"
      ],
      "title": "Initializers"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "11.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "11.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "11.0",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.4",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "PDFAccessPermissions"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "enum"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PDFAccessPermissions"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "PDFAccessPermissions"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.pdfkit/documentation/PDFKit"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Enumeration-Cases",
              "identifiers": [
                "doc://com.apple.pdfkit/documentation/PDFKit/PDFAccessPermissions/allowsCommenting",
                "doc://com.apple.pdfkit/documentation/PDFKit/PDFAccessPermissions/allowsContentAccessibility",
                "doc://com.apple.pdfkit/documentation/PDFKit/PDFAccessPermissions/allowsContentCopying",
                "doc://com.apple.pdfkit/documentation/PDFKit/PDFAccessPermissions/allowsDocumentAssembly",
                "doc://com.apple.pdfkit/documentation/PDFKit/PDFAccessPermissions/allowsDocumentChanges",
                "doc://com.apple.pdfkit/documentation/PDFKit/PDFAccessPermissions/allowsFormFieldEntry",
                "doc://com.apple.pdfkit/documentation/PDFKit/PDFAccessPermissions/allowsHighQualityPrinting",
                "doc://com.apple.pdfkit/documentation/PDFKit/PDFAccessPermissions/allowsLowQualityPrinting"
              ],
              "title": "Enumeration Cases"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Enumerations",
              "generated": true,
              "identifiers": [
                "doc://com.apple.pdfkit/documentation/PDFKit/PDFSelectionGranularity",
                "doc://com.apple.pdfkit/documentation/PDFKit/PDFThumbnailLayoutMode"
              ],
              "title": "Enumerations"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "enum"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "PDFAccessPermissions"
                  },
                  {
                    "kind": "text",
                    "text": " : "
                  },
                  {
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@NSUInteger",
                    "text": "NSUInteger"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFAccessPermissions~1allowsHighQualityPrinting/title",
          "value": "PDFAllowsHighQualityPrinting"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFAccessPermissions~1allowsHighQualityPrinting/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PDFAllowsHighQualityPrinting"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFThumbnailLayoutMode/title",
          "value": "PDFThumbnailLayoutMode"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFThumbnailLayoutMode/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PDFThumbnailLayoutMode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFThumbnailLayoutMode/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "PDFThumbnailLayoutMode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFSelectionGranularity/title",
          "value": "PDFSelectionGranularity"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFSelectionGranularity/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PDFSelectionGranularity"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFSelectionGranularity/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "PDFSelectionGranularity"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFAccessPermissions~1allowsDocumentAssembly/title",
          "value": "PDFAllowsDocumentAssembly"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFAccessPermissions~1allowsDocumentAssembly/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PDFAllowsDocumentAssembly"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFAccessPermissions~1allowsFormFieldEntry/title",
          "value": "PDFAllowsFormFieldEntry"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFAccessPermissions~1allowsFormFieldEntry/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PDFAllowsFormFieldEntry"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFAccessPermissions/title",
          "value": "PDFAccessPermissions"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFAccessPermissions/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PDFAccessPermissions"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFAccessPermissions/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "PDFAccessPermissions"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFAccessPermissions~1allowsLowQualityPrinting/title",
          "value": "PDFAllowsLowQualityPrinting"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFAccessPermissions~1allowsLowQualityPrinting/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PDFAllowsLowQualityPrinting"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFAccessPermissions~1allowsContentAccessibility/title",
          "value": "PDFAllowsContentAccessibility"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFAccessPermissions~1allowsContentAccessibility/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PDFAllowsContentAccessibility"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFAccessPermissions~1allowsDocumentChanges/title",
          "value": "PDFAllowsDocumentChanges"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFAccessPermissions~1allowsDocumentChanges/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PDFAllowsDocumentChanges"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFAccessPermissions~1allowsCommenting/title",
          "value": "PDFAllowsCommenting"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFAccessPermissions~1allowsCommenting/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PDFAllowsCommenting"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFAccessPermissions~1allowsContentCopying/title",
          "value": "PDFAllowsContentCopying"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFAccessPermissions~1allowsContentCopying/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PDFAllowsContentCopying"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/pdfkit/pdfaccesspermissions"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/pdfkit/pdfaccesspermissions"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
