{
  "abstract": [
    {
      "text": "A notification that a write operation begins working on a page in a document.",
      "type": "text"
    }
  ],
  "diffAvailability": {
    "major": {
      "change": "modified",
      "platform": "Xcode",
      "versions": [
        "16.0",
        "16.3 beta 2"
      ]
    }
  },
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.pdfkit/documentation/PDFKit"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "occ",
    "url": "doc://com.apple.pdfkit/documentation/PDFKit/PDFDocumentDidBeginPageWriteNotification"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@PDFDocumentDidBeginPageWriteNotification",
    "fragments": [
      {
        "kind": "identifier",
        "text": "PDFDocumentDidBeginPageWriteNotification"
      }
    ],
    "modules": [
      {
        "name": "PDFKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "PDFDocumentDidBeginPageWriteNotification"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "11.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "11.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.1",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.4",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "11.0",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Global Variable",
    "symbolKind": "var",
    "title": "PDFDocumentDidBeginPageWriteNotification"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "occ"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "extern"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/c:@T@NSNotificationName",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@NSNotificationName",
              "text": "NSNotificationName"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "keyword",
              "text": "const"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "PDFDocumentDidBeginPageWriteNotification"
            },
            {
              "kind": "text",
              "text": ";"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "The notification object is the ",
              "type": "text"
            },
            {
              "code": "PDFDocument",
              "type": "codeVoice"
            },
            {
              "text": " object itself. To determine the page, use the ",
              "type": "text"
            },
            {
              "code": "@”PDFDocumentPageIndex”",
              "type": "codeVoice"
            },
            {
              "text": " key to obtain userinfo of type ",
              "type": "text"
            },
            {
              "code": "NSNumber",
              "type": "codeVoice"
            },
            {
              "text": ".",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.pdfkit/documentation/PDFKit": {
      "abstract": [
        {
          "text": "Display and manipulate PDF documents in your apps.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.pdfkit/documentation/PDFKit",
      "kind": "symbol",
      "role": "collection",
      "title": "PDFKit",
      "type": "topic",
      "url": "/documentation/pdfkit"
    },
    "doc://com.apple.pdfkit/documentation/PDFKit/PDFDocument/beginFindString(_:withOptions:)": {
      "abstract": [
        {
          "text": "Asynchronously finds all instances of the specified string in the document.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "beginFindString"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "withOptions"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSString",
          "text": "NSString"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@NSStringCompareOptions",
          "text": "CompareOptions"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.pdfkit/documentation/PDFKit/PDFDocument/beginFindString(_:withOptions:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "beginFindString:withOptions:"
        }
      ],
      "role": "symbol",
      "title": "beginFindString(_:withOptions:)",
      "type": "topic",
      "url": "/documentation/pdfkit/pdfdocument/beginfindstring(_:withoptions:)"
    },
    "doc://com.apple.pdfkit/documentation/PDFKit/PDFDocument/findString(_:withOptions:)": {
      "abstract": [
        {
          "text": "Synchronously finds all instances of the specified string in the document.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "findString"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "withOptions"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSString",
          "text": "NSString"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@NSStringCompareOptions",
          "text": "CompareOptions"
        },
        {
          "kind": "text",
          "text": ") -> ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)PDFSelection",
          "text": "PDFSelection"
        },
        {
          "kind": "text",
          "text": "]"
        }
      ],
      "identifier": "doc://com.apple.pdfkit/documentation/PDFKit/PDFDocument/findString(_:withOptions:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "findString:withOptions:"
        }
      ],
      "role": "symbol",
      "title": "findString(_:withOptions:)",
      "type": "topic",
      "url": "/documentation/pdfkit/pdfdocument/findstring(_:withoptions:)"
    },
    "doc://com.apple.pdfkit/documentation/PDFKit/PDFDocument/unlock(withPassword:)": {
      "abstract": [
        {
          "text": "Attempts to unlock an encrypted document.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "unlock"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "withPassword"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.pdfkit/documentation/PDFKit/PDFDocument/unlock(withPassword:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "unlockWithPassword:"
        }
      ],
      "role": "symbol",
      "title": "unlock(withPassword:)",
      "type": "topic",
      "url": "/documentation/pdfkit/pdfdocument/unlock(withpassword:)"
    },
    "doc://com.apple.pdfkit/documentation/PDFKit/PDFDocumentDidBeginFindNotification": {
      "abstract": [
        {
          "text": "A notification that the ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.pdfkit/documentation/PDFKit/PDFDocument/beginFindString(_:withOptions:)",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " or ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.pdfkit/documentation/PDFKit/PDFDocument/findString(_:withOptions:)",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " method begins finding.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "PDFDocumentDidBeginFindNotification"
        }
      ],
      "identifier": "doc://com.apple.pdfkit/documentation/PDFKit/PDFDocumentDidBeginFindNotification",
      "kind": "symbol",
      "role": "symbol",
      "title": "PDFDocumentDidBeginFindNotification",
      "type": "topic",
      "url": "/documentation/pdfkit/pdfdocumentdidbeginfindnotification"
    },
    "doc://com.apple.pdfkit/documentation/PDFKit/PDFDocumentDidBeginPageFindNotification": {
      "abstract": [
        {
          "text": "A notification that a find operation begins working on a new page of a document.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "PDFDocumentDidBeginPageFindNotification"
        }
      ],
      "identifier": "doc://com.apple.pdfkit/documentation/PDFKit/PDFDocumentDidBeginPageFindNotification",
      "kind": "symbol",
      "role": "symbol",
      "title": "PDFDocumentDidBeginPageFindNotification",
      "type": "topic",
      "url": "/documentation/pdfkit/pdfdocumentdidbeginpagefindnotification"
    },
    "doc://com.apple.pdfkit/documentation/PDFKit/PDFDocumentDidBeginPageWriteNotification": {
      "abstract": [
        {
          "text": "A notification that a write operation begins working on a page in a document.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "PDFDocumentDidBeginPageWriteNotification"
        }
      ],
      "identifier": "doc://com.apple.pdfkit/documentation/PDFKit/PDFDocumentDidBeginPageWriteNotification",
      "kind": "symbol",
      "role": "symbol",
      "title": "PDFDocumentDidBeginPageWriteNotification",
      "type": "topic",
      "url": "/documentation/pdfkit/pdfdocumentdidbeginpagewritenotification"
    },
    "doc://com.apple.pdfkit/documentation/PDFKit/PDFDocumentDidBeginWriteNotification": {
      "abstract": [
        {
          "text": "A notification that a write operation begins working on a document.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "PDFDocumentDidBeginWriteNotification"
        }
      ],
      "identifier": "doc://com.apple.pdfkit/documentation/PDFKit/PDFDocumentDidBeginWriteNotification",
      "kind": "symbol",
      "role": "symbol",
      "title": "PDFDocumentDidBeginWriteNotification",
      "type": "topic",
      "url": "/documentation/pdfkit/pdfdocumentdidbeginwritenotification"
    },
    "doc://com.apple.pdfkit/documentation/PDFKit/PDFDocumentDidEndFindNotification": {
      "abstract": [
        {
          "text": "A notification that the ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.pdfkit/documentation/PDFKit/PDFDocument/beginFindString(_:withOptions:)",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " or ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.pdfkit/documentation/PDFKit/PDFDocument/findString(_:withOptions:)",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " method returns.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "PDFDocumentDidEndFindNotification"
        }
      ],
      "identifier": "doc://com.apple.pdfkit/documentation/PDFKit/PDFDocumentDidEndFindNotification",
      "kind": "symbol",
      "role": "symbol",
      "title": "PDFDocumentDidEndFindNotification",
      "type": "topic",
      "url": "/documentation/pdfkit/pdfdocumentdidendfindnotification"
    },
    "doc://com.apple.pdfkit/documentation/PDFKit/PDFDocumentDidEndPageFindNotification": {
      "abstract": [
        {
          "text": "A notification that a find operation finishes working on a page in a document.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "PDFDocumentDidEndPageFindNotification"
        }
      ],
      "identifier": "doc://com.apple.pdfkit/documentation/PDFKit/PDFDocumentDidEndPageFindNotification",
      "kind": "symbol",
      "role": "symbol",
      "title": "PDFDocumentDidEndPageFindNotification",
      "type": "topic",
      "url": "/documentation/pdfkit/pdfdocumentdidendpagefindnotification"
    },
    "doc://com.apple.pdfkit/documentation/PDFKit/PDFDocumentDidEndPageWriteNotification": {
      "abstract": [
        {
          "text": "A notification that a write operation finishes working on a page in a document.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "PDFDocumentDidEndPageWriteNotification"
        }
      ],
      "identifier": "doc://com.apple.pdfkit/documentation/PDFKit/PDFDocumentDidEndPageWriteNotification",
      "kind": "symbol",
      "role": "symbol",
      "title": "PDFDocumentDidEndPageWriteNotification",
      "type": "topic",
      "url": "/documentation/pdfkit/pdfdocumentdidendpagewritenotification"
    },
    "doc://com.apple.pdfkit/documentation/PDFKit/PDFDocumentDidEndWriteNotification": {
      "abstract": [
        {
          "text": "A notification that a write operation finishes working on a document.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "PDFDocumentDidEndWriteNotification"
        }
      ],
      "identifier": "doc://com.apple.pdfkit/documentation/PDFKit/PDFDocumentDidEndWriteNotification",
      "kind": "symbol",
      "role": "symbol",
      "title": "PDFDocumentDidEndWriteNotification",
      "type": "topic",
      "url": "/documentation/pdfkit/pdfdocumentdidendwritenotification"
    },
    "doc://com.apple.pdfkit/documentation/PDFKit/PDFDocumentDidFindMatchNotification": {
      "abstract": [
        {
          "text": "A notification that a string match is found in a document.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "PDFDocumentDidFindMatchNotification"
        }
      ],
      "identifier": "doc://com.apple.pdfkit/documentation/PDFKit/PDFDocumentDidFindMatchNotification",
      "kind": "symbol",
      "role": "symbol",
      "title": "PDFDocumentDidFindMatchNotification",
      "type": "topic",
      "url": "/documentation/pdfkit/pdfdocumentdidfindmatchnotification"
    },
    "doc://com.apple.pdfkit/documentation/PDFKit/PDFDocumentDidUnlockNotification": {
      "abstract": [
        {
          "text": "A notification that a document unlocks after a ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.pdfkit/documentation/PDFKit/PDFDocument/unlock(withPassword:)",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " message.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "PDFDocumentDidUnlockNotification"
        }
      ],
      "identifier": "doc://com.apple.pdfkit/documentation/PDFKit/PDFDocumentDidUnlockNotification",
      "kind": "symbol",
      "role": "symbol",
      "title": "PDFDocumentDidUnlockNotification",
      "type": "topic",
      "url": "/documentation/pdfkit/pdfdocumentdidunlocknotification"
    },
    "doc://com.externally.resolved.symbol/c:@T@NSNotificationName": {
      "abstract": [
        {
          "text": "A structure that defines the name of a notification.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "struct "
        },
        {
          "kind": "identifier",
          "text": "NSNotification.Name"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:@T@NSNotificationName",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSNotification.Name",
      "type": "topic",
      "url": "/documentation/foundation/nsnotification/name"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Notifications",
      "generated": true,
      "identifiers": [
        "doc://com.apple.pdfkit/documentation/PDFKit/PDFDocumentDidUnlockNotification",
        "doc://com.apple.pdfkit/documentation/PDFKit/PDFDocumentDidBeginFindNotification",
        "doc://com.apple.pdfkit/documentation/PDFKit/PDFDocumentDidEndFindNotification",
        "doc://com.apple.pdfkit/documentation/PDFKit/PDFDocumentDidBeginPageFindNotification",
        "doc://com.apple.pdfkit/documentation/PDFKit/PDFDocumentDidEndPageFindNotification",
        "doc://com.apple.pdfkit/documentation/PDFKit/PDFDocumentDidFindMatchNotification",
        "doc://com.apple.pdfkit/documentation/PDFKit/PDFDocumentDidBeginWriteNotification",
        "doc://com.apple.pdfkit/documentation/PDFKit/PDFDocumentDidEndWriteNotification",
        "doc://com.apple.pdfkit/documentation/PDFKit/PDFDocumentDidEndPageWriteNotification"
      ],
      "title": "Notifications"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFDocument~1findString(_:withOptions:)/title",
          "value": "findString:withOptions:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFDocument~1findString(_:withOptions:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "findString:withOptions:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFDocument~1beginFindString(_:withOptions:)/title",
          "value": "beginFindString:withOptions:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFDocument~1beginFindString(_:withOptions:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "beginFindString:withOptions:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFDocument~1unlock(withPassword:)/title",
          "value": "unlockWithPassword:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFDocument~1unlock(withPassword:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "unlockWithPassword:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:@T@NSNotificationName/title",
          "value": "NSNotificationName"
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/pdfkit/pdfdocumentdidbeginpagewritenotification"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
