{
  "abstract": [
    {
      "text": "The delegate for the ",
      "type": "text"
    },
    {
      "code": "PDFDocument",
      "type": "codeVoice"
    },
    {
      "text": " object.",
      "type": "text"
    }
  ],
  "diffAvailability": {
    "major": {
      "change": "modified",
      "platform": "Xcode",
      "versions": [
        "16.0",
        "16.3 beta 2"
      ]
    }
  },
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.pdfkit/documentation/PDFKit"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.pdfkit/documentation/PDFKit/PDFDocumentDelegate"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(pl)PDFDocumentDelegate",
    "fragments": [
      {
        "kind": "keyword",
        "text": "protocol"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "PDFDocumentDelegate"
      }
    ],
    "modules": [
      {
        "name": "PDFKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "PDFDocumentDelegate"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "11.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "11.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "11.0",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.4",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Protocol",
    "symbolKind": "protocol",
    "title": "PDFDocumentDelegate"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "protocol"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "PDFDocumentDelegate"
            },
            {
              "kind": "text",
              "text": " : "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSObject",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(pl)NSObject",
              "text": "NSObjectProtocol"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "kind": "mentions",
      "mentions": [
        "doc://com.apple.pdfkit/documentation/PDFKit/adding-custom-graphics-to-a-pdf"
      ]
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.pdfkit/documentation/PDFKit": {
      "abstract": [
        {
          "text": "Display and manipulate PDF documents in your apps.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.pdfkit/documentation/PDFKit",
      "kind": "symbol",
      "role": "collection",
      "title": "PDFKit",
      "type": "topic",
      "url": "/documentation/pdfkit"
    },
    "doc://com.apple.pdfkit/documentation/PDFKit/PDFDocument/delegate": {
      "abstract": [
        {
          "text": "The object acting as the delegate for the ",
          "type": "text"
        },
        {
          "code": "PDFDocument",
          "type": "codeVoice"
        },
        {
          "text": " object.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "delegate"
        },
        {
          "kind": "text",
          "text": ": (any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(pl)PDFDocumentDelegate",
          "text": "PDFDocumentDelegate"
        },
        {
          "kind": "text",
          "text": ")?"
        }
      ],
      "identifier": "doc://com.apple.pdfkit/documentation/PDFKit/PDFDocument/delegate",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "delegate"
        }
      ],
      "role": "symbol",
      "title": "delegate",
      "type": "topic",
      "url": "/documentation/pdfkit/pdfdocument/delegate"
    },
    "doc://com.apple.pdfkit/documentation/PDFKit/PDFDocumentDelegate": {
      "abstract": [
        {
          "text": "The delegate for the ",
          "type": "text"
        },
        {
          "code": "PDFDocument",
          "type": "codeVoice"
        },
        {
          "text": " object.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "PDFDocumentDelegate"
        }
      ],
      "identifier": "doc://com.apple.pdfkit/documentation/PDFKit/PDFDocumentDelegate",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PDFDocumentDelegate"
        }
      ],
      "role": "symbol",
      "title": "PDFDocumentDelegate",
      "type": "topic",
      "url": "/documentation/pdfkit/pdfdocumentdelegate"
    },
    "doc://com.apple.pdfkit/documentation/PDFKit/PDFDocumentDelegate/class(forAnnotationClass:)": {
      "abstract": [
        {
          "text": "Returns a ",
          "type": "text"
        },
        {
          "code": "PDFAnnotation",
          "type": "codeVoice"
        },
        {
          "text": " subclass for a class.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "`class`"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "forAnnotationClass"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s8AnyClassa",
          "text": "AnyClass"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s8AnyClassa",
          "text": "AnyClass"
        }
      ],
      "identifier": "doc://com.apple.pdfkit/documentation/PDFKit/PDFDocumentDelegate/class(forAnnotationClass:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "classForAnnotationClass:"
        }
      ],
      "role": "symbol",
      "title": "class(forAnnotationClass:)",
      "type": "topic",
      "url": "/documentation/pdfkit/pdfdocumentdelegate/class(forannotationclass:)"
    },
    "doc://com.apple.pdfkit/documentation/PDFKit/PDFDocumentDelegate/class(forAnnotationType:)": {
      "abstract": [
        {
          "text": "Returns a ",
          "type": "text"
        },
        {
          "code": "PDFAnnotation",
          "type": "codeVoice"
        },
        {
          "text": " subclass for an annotation type.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "`class`"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "forAnnotationType"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s8AnyClassa",
          "text": "AnyClass"
        }
      ],
      "identifier": "doc://com.apple.pdfkit/documentation/PDFKit/PDFDocumentDelegate/class(forAnnotationType:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "classForAnnotationType:"
        }
      ],
      "role": "symbol",
      "title": "class(forAnnotationType:)",
      "type": "topic",
      "url": "/documentation/pdfkit/pdfdocumentdelegate/class(forannotationtype:)"
    },
    "doc://com.apple.pdfkit/documentation/PDFKit/PDFDocumentDelegate/classForPage()": {
      "abstract": [
        {
          "text": "Returns a ",
          "type": "text"
        },
        {
          "code": "PDFPage",
          "type": "codeVoice"
        },
        {
          "text": " subclass for a page object.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "classForPage"
        },
        {
          "kind": "text",
          "text": "() -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s8AnyClassa",
          "text": "AnyClass"
        }
      ],
      "identifier": "doc://com.apple.pdfkit/documentation/PDFKit/PDFDocumentDelegate/classForPage()",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "classForPage"
        }
      ],
      "role": "symbol",
      "title": "classForPage()",
      "type": "topic",
      "url": "/documentation/pdfkit/pdfdocumentdelegate/classforpage()"
    },
    "doc://com.apple.pdfkit/documentation/PDFKit/PDFDocumentDelegate/didMatchString(_:)": {
      "abstract": [
        {
          "text": "Called for every match found during a find operation.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "didMatchString"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)PDFSelection",
          "text": "PDFSelection"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.pdfkit/documentation/PDFKit/PDFDocumentDelegate/didMatchString(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "didMatchString:"
        }
      ],
      "role": "symbol",
      "title": "didMatchString(_:)",
      "type": "topic",
      "url": "/documentation/pdfkit/pdfdocumentdelegate/didmatchstring(_:)"
    },
    "doc://com.apple.pdfkit/documentation/PDFKit/PDFDocumentDelegate/documentDidBeginDocumentFind(_:)": {
      "abstract": [
        {
          "text": "Called when the ",
          "type": "text"
        },
        {
          "code": "PDFDocumentDidBeginFindNotification",
          "type": "codeVoice"
        },
        {
          "text": " notification is posted.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "documentDidBeginDocumentFind"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10Foundation12NotificationV",
          "text": "Notification"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.pdfkit/documentation/PDFKit/PDFDocumentDelegate/documentDidBeginDocumentFind(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "documentDidBeginDocumentFind:"
        }
      ],
      "role": "symbol",
      "title": "documentDidBeginDocumentFind(_:)",
      "type": "topic",
      "url": "/documentation/pdfkit/pdfdocumentdelegate/documentdidbegindocumentfind(_:)"
    },
    "doc://com.apple.pdfkit/documentation/PDFKit/PDFDocumentDelegate/documentDidBeginPageFind(_:)": {
      "abstract": [
        {
          "text": "Called when the ",
          "type": "text"
        },
        {
          "code": "PDFDocumentDidBeginPageFindNotification",
          "type": "codeVoice"
        },
        {
          "text": " notification is posted.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "documentDidBeginPageFind"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10Foundation12NotificationV",
          "text": "Notification"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.pdfkit/documentation/PDFKit/PDFDocumentDelegate/documentDidBeginPageFind(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "documentDidBeginPageFind:"
        }
      ],
      "role": "symbol",
      "title": "documentDidBeginPageFind(_:)",
      "type": "topic",
      "url": "/documentation/pdfkit/pdfdocumentdelegate/documentdidbeginpagefind(_:)"
    },
    "doc://com.apple.pdfkit/documentation/PDFKit/PDFDocumentDelegate/documentDidEndDocumentFind(_:)": {
      "abstract": [
        {
          "text": "Called when the ",
          "type": "text"
        },
        {
          "code": "PDFDocumentDidEndFindNotification",
          "type": "codeVoice"
        },
        {
          "text": " notification is posted.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "documentDidEndDocumentFind"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10Foundation12NotificationV",
          "text": "Notification"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.pdfkit/documentation/PDFKit/PDFDocumentDelegate/documentDidEndDocumentFind(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "documentDidEndDocumentFind:"
        }
      ],
      "role": "symbol",
      "title": "documentDidEndDocumentFind(_:)",
      "type": "topic",
      "url": "/documentation/pdfkit/pdfdocumentdelegate/documentdidenddocumentfind(_:)"
    },
    "doc://com.apple.pdfkit/documentation/PDFKit/PDFDocumentDelegate/documentDidEndPageFind(_:)": {
      "abstract": [
        {
          "text": "Called when the ",
          "type": "text"
        },
        {
          "code": "PDFDocumentDidEndPageFindNotification",
          "type": "codeVoice"
        },
        {
          "text": " notification is posted.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "documentDidEndPageFind"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10Foundation12NotificationV",
          "text": "Notification"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.pdfkit/documentation/PDFKit/PDFDocumentDelegate/documentDidEndPageFind(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "documentDidEndPageFind:"
        }
      ],
      "role": "symbol",
      "title": "documentDidEndPageFind(_:)",
      "type": "topic",
      "url": "/documentation/pdfkit/pdfdocumentdelegate/documentdidendpagefind(_:)"
    },
    "doc://com.apple.pdfkit/documentation/PDFKit/PDFDocumentDelegate/documentDidFindMatch(_:)": {
      "abstract": [
        {
          "text": "Called when the ",
          "type": "text"
        },
        {
          "code": "PDFDocumentDidFindMatchNotification",
          "type": "codeVoice"
        },
        {
          "text": " notification is posted.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "documentDidFindMatch"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10Foundation12NotificationV",
          "text": "Notification"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.pdfkit/documentation/PDFKit/PDFDocumentDelegate/documentDidFindMatch(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "documentDidFindMatch:"
        }
      ],
      "role": "symbol",
      "title": "documentDidFindMatch(_:)",
      "type": "topic",
      "url": "/documentation/pdfkit/pdfdocumentdelegate/documentdidfindmatch(_:)"
    },
    "doc://com.apple.pdfkit/documentation/PDFKit/PDFDocumentDelegate/documentDidUnlock(_:)": {
      "abstract": [
        {
          "text": "Called when the ",
          "type": "text"
        },
        {
          "code": "PDFDocumentDidUnlockNotification",
          "type": "codeVoice"
        },
        {
          "text": " notification is posted.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "documentDidUnlock"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10Foundation12NotificationV",
          "text": "Notification"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.pdfkit/documentation/PDFKit/PDFDocumentDelegate/documentDidUnlock(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "documentDidUnlock:"
        }
      ],
      "role": "symbol",
      "title": "documentDidUnlock(_:)",
      "type": "topic",
      "url": "/documentation/pdfkit/pdfdocumentdelegate/documentdidunlock(_:)"
    },
    "doc://com.apple.pdfkit/documentation/PDFKit/adding-custom-graphics-to-a-pdf": {
      "abstract": [
        {
          "text": "Create and add custom annotation and page graphics to your PDF document.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.pdfkit/documentation/PDFKit/adding-custom-graphics-to-a-pdf",
      "kind": "article",
      "role": "article",
      "title": "Adding Custom Graphics to a PDF",
      "type": "topic",
      "url": "/documentation/pdfkit/adding-custom-graphics-to-a-pdf"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)NSObject": {
      "abstract": [
        {
          "text": "The group of methods that are fundamental to all Objective-C objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "protocol "
        },
        {
          "kind": "identifier",
          "text": "NSObjectProtocol"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSObject",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSObjectProtocol",
      "type": "topic",
      "url": "/documentation/objectivec/nsobjectprotocol"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/c:objc(pl)NSObject"
      ],
      "kind": "relationships",
      "title": "Inherits From",
      "type": "inheritsFrom"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Setting-the-Delegate",
      "generated": true,
      "identifiers": [
        "doc://com.apple.pdfkit/documentation/PDFKit/PDFDocument/delegate"
      ],
      "title": "Setting the Delegate"
    }
  ],
  "topicSections": [
    {
      "anchor": "Managing-Document-Security",
      "identifiers": [
        "doc://com.apple.pdfkit/documentation/PDFKit/PDFDocumentDelegate/documentDidUnlock(_:)"
      ],
      "title": "Managing Document Security"
    },
    {
      "anchor": "Getting-Document-Search-Notifications",
      "identifiers": [
        "doc://com.apple.pdfkit/documentation/PDFKit/PDFDocumentDelegate/didMatchString(_:)",
        "doc://com.apple.pdfkit/documentation/PDFKit/PDFDocumentDelegate/documentDidBeginDocumentFind(_:)",
        "doc://com.apple.pdfkit/documentation/PDFKit/PDFDocumentDelegate/documentDidBeginPageFind(_:)",
        "doc://com.apple.pdfkit/documentation/PDFKit/PDFDocumentDelegate/documentDidEndDocumentFind(_:)",
        "doc://com.apple.pdfkit/documentation/PDFKit/PDFDocumentDelegate/documentDidEndPageFind(_:)",
        "doc://com.apple.pdfkit/documentation/PDFKit/PDFDocumentDelegate/documentDidFindMatch(_:)"
      ],
      "title": "Getting Document Search Notifications"
    },
    {
      "anchor": "Wrapping-Document-Elements",
      "identifiers": [
        "doc://com.apple.pdfkit/documentation/PDFKit/PDFDocumentDelegate/classForPage()",
        "doc://com.apple.pdfkit/documentation/PDFKit/PDFDocumentDelegate/class(forAnnotationClass:)",
        "doc://com.apple.pdfkit/documentation/PDFKit/PDFDocumentDelegate/class(forAnnotationType:)"
      ],
      "title": "Wrapping Document Elements"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "11.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "11.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "11.0",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.4",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Protocol"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "PDFDocumentDelegate"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "protocol"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PDFDocumentDelegate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "PDFDocumentDelegate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.pdfkit/documentation/PDFKit"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Managing-Document-Security",
              "identifiers": [
                "doc://com.apple.pdfkit/documentation/PDFKit/PDFDocumentDelegate/documentDidUnlock(_:)"
              ],
              "title": "Managing Document Security"
            },
            {
              "anchor": "Getting-Document-Search-Notifications",
              "identifiers": [
                "doc://com.apple.pdfkit/documentation/PDFKit/PDFDocumentDelegate/didMatchString(_:)",
                "doc://com.apple.pdfkit/documentation/PDFKit/PDFDocumentDelegate/documentDidBeginDocumentFind(_:)",
                "doc://com.apple.pdfkit/documentation/PDFKit/PDFDocumentDelegate/documentDidBeginPageFind(_:)",
                "doc://com.apple.pdfkit/documentation/PDFKit/PDFDocumentDelegate/documentDidEndDocumentFind(_:)",
                "doc://com.apple.pdfkit/documentation/PDFKit/PDFDocumentDelegate/documentDidEndPageFind(_:)",
                "doc://com.apple.pdfkit/documentation/PDFKit/PDFDocumentDelegate/documentDidFindMatch(_:)"
              ],
              "title": "Getting Document Search Notifications"
            },
            {
              "anchor": "Wrapping-Document-Elements",
              "identifiers": [
                "doc://com.apple.pdfkit/documentation/PDFKit/PDFDocumentDelegate/classForPage()",
                "doc://com.apple.pdfkit/documentation/PDFKit/PDFDocumentDelegate/class(forAnnotationClass:)",
                "doc://com.apple.pdfkit/documentation/PDFKit/PDFDocumentDelegate/class(forAnnotationType:)"
              ],
              "title": "Wrapping Document Elements"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": [
            {
              "identifiers": [
                "doc://com.externally.resolved.symbol/c:objc(pl)NSObject"
              ],
              "kind": "relationships",
              "title": "Inherits From",
              "type": "inheritsFrom"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Setting-the-Delegate",
              "generated": true,
              "identifiers": [
                "doc://com.apple.pdfkit/documentation/PDFKit/PDFDocument/delegate"
              ],
              "title": "Setting the Delegate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "@protocol"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "PDFDocumentDelegate"
                  },
                  {
                    "kind": "text",
                    "text": " <"
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSObject",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(pl)NSObject",
                    "text": "NSObject"
                  },
                  {
                    "kind": "text",
                    "text": ">"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFDocumentDelegate~1documentDidUnlock(_:)/title",
          "value": "documentDidUnlock:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFDocumentDelegate~1documentDidUnlock(_:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "documentDidUnlock:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFDocumentDelegate~1documentDidFindMatch(_:)/title",
          "value": "documentDidFindMatch:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFDocumentDelegate~1documentDidFindMatch(_:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "documentDidFindMatch:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFDocument~1delegate/title",
          "value": "delegate"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFDocument~1delegate/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "delegate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFDocumentDelegate~1documentDidEndDocumentFind(_:)/title",
          "value": "documentDidEndDocumentFind:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFDocumentDelegate~1documentDidEndDocumentFind(_:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "documentDidEndDocumentFind:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFDocumentDelegate~1didMatchString(_:)/title",
          "value": "didMatchString:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFDocumentDelegate~1didMatchString(_:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "didMatchString:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFDocumentDelegate~1documentDidEndPageFind(_:)/title",
          "value": "documentDidEndPageFind:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFDocumentDelegate~1documentDidEndPageFind(_:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "documentDidEndPageFind:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFDocumentDelegate~1class(forAnnotationType:)/title",
          "value": "classForAnnotationType:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFDocumentDelegate~1class(forAnnotationType:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "classForAnnotationType:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFDocumentDelegate~1class(forAnnotationClass:)/title",
          "value": "classForAnnotationClass:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFDocumentDelegate~1class(forAnnotationClass:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "classForAnnotationClass:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFDocumentDelegate~1classForPage()/title",
          "value": "classForPage"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFDocumentDelegate~1classForPage()/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "classForPage"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFDocumentDelegate~1documentDidBeginPageFind(_:)/title",
          "value": "documentDidBeginPageFind:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFDocumentDelegate~1documentDidBeginPageFind(_:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "documentDidBeginPageFind:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFDocumentDelegate~1documentDidBeginDocumentFind(_:)/title",
          "value": "documentDidBeginDocumentFind:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFDocumentDelegate~1documentDidBeginDocumentFind(_:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "documentDidBeginDocumentFind:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFDocumentDelegate/title",
          "value": "PDFDocumentDelegate"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFDocumentDelegate/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PDFDocumentDelegate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFDocumentDelegate/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "PDFDocumentDelegate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:objc(pl)NSObject/title",
          "value": "NSObject"
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/pdfkit/pdfdocumentdelegate"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/pdfkit/pdfdocumentdelegate"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
