{
  "abstract": [
    {
      "text": "A structure that specifies document attributes.",
      "type": "text"
    }
  ],
  "diffAvailability": {
    "major": {
      "change": "modified",
      "platform": "Xcode",
      "versions": [
        "16.0",
        "16.3 beta 2"
      ]
    }
  },
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.pdfkit/documentation/PDFKit"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.pdfkit/documentation/PDFKit/PDFDocumentAttribute"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@T@PDFDocumentAttribute",
    "fragments": [
      {
        "kind": "keyword",
        "text": "struct"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "PDFDocumentAttribute"
      }
    ],
    "modules": [
      {
        "name": "PDFKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "PDFDocumentAttribute"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "11.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "11.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "11.0",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.4",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Structure",
    "symbolKind": "struct",
    "title": "PDFDocumentAttribute"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "struct"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "PDFDocumentAttribute"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.pdfkit/documentation/PDFKit": {
      "abstract": [
        {
          "text": "Display and manipulate PDF documents in your apps.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.pdfkit/documentation/PDFKit",
      "kind": "symbol",
      "role": "collection",
      "title": "PDFKit",
      "type": "topic",
      "url": "/documentation/pdfkit"
    },
    "doc://com.apple.pdfkit/documentation/PDFKit/PDFDocumentAttribute": {
      "abstract": [
        {
          "text": "A structure that specifies document attributes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "PDFDocumentAttribute"
        }
      ],
      "identifier": "doc://com.apple.pdfkit/documentation/PDFKit/PDFDocumentAttribute",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PDFDocumentAttribute"
        }
      ],
      "role": "symbol",
      "title": "PDFDocumentAttribute",
      "type": "topic",
      "url": "/documentation/pdfkit/pdfdocumentattribute"
    },
    "doc://com.apple.pdfkit/documentation/PDFKit/PDFDocumentAttribute/authorAttribute": {
      "abstract": [
        {
          "text": "An optional text string containing the name of the author of the document.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "authorAttribute"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@PDFDocumentAttribute",
          "text": "PDFDocumentAttribute"
        }
      ],
      "identifier": "doc://com.apple.pdfkit/documentation/PDFKit/PDFDocumentAttribute/authorAttribute",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PDFDocumentAuthorAttribute"
        }
      ],
      "role": "symbol",
      "title": "authorAttribute",
      "type": "topic",
      "url": "/documentation/pdfkit/pdfdocumentattribute/authorattribute"
    },
    "doc://com.apple.pdfkit/documentation/PDFKit/PDFDocumentAttribute/creationDateAttribute": {
      "abstract": [
        {
          "text": "An optional text string containing the document’s creation date.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "creationDateAttribute"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@PDFDocumentAttribute",
          "text": "PDFDocumentAttribute"
        }
      ],
      "identifier": "doc://com.apple.pdfkit/documentation/PDFKit/PDFDocumentAttribute/creationDateAttribute",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PDFDocumentCreationDateAttribute"
        }
      ],
      "role": "symbol",
      "title": "creationDateAttribute",
      "type": "topic",
      "url": "/documentation/pdfkit/pdfdocumentattribute/creationdateattribute"
    },
    "doc://com.apple.pdfkit/documentation/PDFKit/PDFDocumentAttribute/creatorAttribute": {
      "abstract": [
        {
          "text": "An optional text string containing the name of the application that created the document content.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "creatorAttribute"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@PDFDocumentAttribute",
          "text": "PDFDocumentAttribute"
        }
      ],
      "identifier": "doc://com.apple.pdfkit/documentation/PDFKit/PDFDocumentAttribute/creatorAttribute",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PDFDocumentCreatorAttribute"
        }
      ],
      "role": "symbol",
      "title": "creatorAttribute",
      "type": "topic",
      "url": "/documentation/pdfkit/pdfdocumentattribute/creatorattribute"
    },
    "doc://com.apple.pdfkit/documentation/PDFKit/PDFDocumentAttribute/init(rawValue:)": {
      "abstract": [
        {
          "text": "Initialize a ",
          "type": "text"
        },
        {
          "code": "PDFDocumentAttribute",
          "type": "codeVoice"
        },
        {
          "text": " structure.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "rawValue"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.pdfkit/documentation/PDFKit/PDFDocumentAttribute/init(rawValue:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "init(rawValue:)",
      "type": "topic",
      "url": "/documentation/pdfkit/pdfdocumentattribute/init(rawvalue:)"
    },
    "doc://com.apple.pdfkit/documentation/PDFKit/PDFDocumentAttribute/keywordsAttribute": {
      "abstract": [
        {
          "text": "An optional array of text strings containing keywords for the document.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "keywordsAttribute"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@PDFDocumentAttribute",
          "text": "PDFDocumentAttribute"
        }
      ],
      "identifier": "doc://com.apple.pdfkit/documentation/PDFKit/PDFDocumentAttribute/keywordsAttribute",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PDFDocumentKeywordsAttribute"
        }
      ],
      "role": "symbol",
      "title": "keywordsAttribute",
      "type": "topic",
      "url": "/documentation/pdfkit/pdfdocumentattribute/keywordsattribute"
    },
    "doc://com.apple.pdfkit/documentation/PDFKit/PDFDocumentAttribute/modificationDateAttribute": {
      "abstract": [
        {
          "text": "An optional text string containing the document’s last-modified date.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "modificationDateAttribute"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@PDFDocumentAttribute",
          "text": "PDFDocumentAttribute"
        }
      ],
      "identifier": "doc://com.apple.pdfkit/documentation/PDFKit/PDFDocumentAttribute/modificationDateAttribute",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PDFDocumentModificationDateAttribute"
        }
      ],
      "role": "symbol",
      "title": "modificationDateAttribute",
      "type": "topic",
      "url": "/documentation/pdfkit/pdfdocumentattribute/modificationdateattribute"
    },
    "doc://com.apple.pdfkit/documentation/PDFKit/PDFDocumentAttribute/producerAttribute": {
      "abstract": [
        {
          "text": "An optional text string containing the name of the application that produced the PDF data for the document.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "producerAttribute"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@PDFDocumentAttribute",
          "text": "PDFDocumentAttribute"
        }
      ],
      "identifier": "doc://com.apple.pdfkit/documentation/PDFKit/PDFDocumentAttribute/producerAttribute",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PDFDocumentProducerAttribute"
        }
      ],
      "role": "symbol",
      "title": "producerAttribute",
      "type": "topic",
      "url": "/documentation/pdfkit/pdfdocumentattribute/producerattribute"
    },
    "doc://com.apple.pdfkit/documentation/PDFKit/PDFDocumentAttribute/subjectAttribute": {
      "abstract": [
        {
          "text": "An optional text string containing a description of the subject of the document.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "subjectAttribute"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@PDFDocumentAttribute",
          "text": "PDFDocumentAttribute"
        }
      ],
      "identifier": "doc://com.apple.pdfkit/documentation/PDFKit/PDFDocumentAttribute/subjectAttribute",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PDFDocumentSubjectAttribute"
        }
      ],
      "role": "symbol",
      "title": "subjectAttribute",
      "type": "topic",
      "url": "/documentation/pdfkit/pdfdocumentattribute/subjectattribute"
    },
    "doc://com.apple.pdfkit/documentation/PDFKit/PDFDocumentAttribute/titleAttribute": {
      "abstract": [
        {
          "text": "An optional text string containing the title of the document.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "titleAttribute"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@PDFDocumentAttribute",
          "text": "PDFDocumentAttribute"
        }
      ],
      "identifier": "doc://com.apple.pdfkit/documentation/PDFKit/PDFDocumentAttribute/titleAttribute",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PDFDocumentTitleAttribute"
        }
      ],
      "role": "symbol",
      "title": "titleAttribute",
      "type": "topic",
      "url": "/documentation/pdfkit/pdfdocumentattribute/titleattribute"
    },
    "doc://com.apple.pdfkit/documentation/PDFKit/PDFDocumentPermissions": {
      "abstract": [
        {
          "text": "An enumeration that specifies document permissions status.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "PDFDocumentPermissions"
        }
      ],
      "identifier": "doc://com.apple.pdfkit/documentation/PDFKit/PDFDocumentPermissions",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PDFDocumentPermissions"
        }
      ],
      "role": "symbol",
      "title": "PDFDocumentPermissions",
      "type": "topic",
      "url": "/documentation/pdfkit/pdfdocumentpermissions"
    },
    "doc://com.apple.pdfkit/documentation/PDFKit/PDFDocumentWriteOption": {
      "abstract": [
        {
          "text": "A structure that specifies file writing options for a document.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "PDFDocumentWriteOption"
        }
      ],
      "identifier": "doc://com.apple.pdfkit/documentation/PDFKit/PDFDocumentWriteOption",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PDFDocumentWriteOption"
        }
      ],
      "role": "symbol",
      "title": "PDFDocumentWriteOption",
      "type": "topic",
      "url": "/documentation/pdfkit/pdfdocumentwriteoption"
    },
    "doc://com.externally.resolved.symbol/c:objc(cs)NSString": {
      "abstract": [
        {
          "text": "A static, plain-text Unicode string object which you use when you need reference semantics or other Foundation-specific behavior. ",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "class "
        },
        {
          "kind": "identifier",
          "text": "NSString"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSString",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSString",
      "type": "topic",
      "url": "/documentation/foundation/nsstring"
    },
    "doc://com.externally.resolved.symbol/s:SH": {
      "abstract": [
        {
          "text": "A type that can be hashed into a `Hasher` to produce an integer hash value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Hashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SQ",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SH",
      "kind": "symbol",
      "role": "symbol",
      "title": "Hashable",
      "type": "topic",
      "url": "/documentation/Swift/Hashable"
    },
    "doc://com.externally.resolved.symbol/s:SQ": {
      "abstract": [
        {
          "text": "A type that can be compared for value equality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SQ",
      "kind": "symbol",
      "role": "symbol",
      "title": "Equatable",
      "type": "topic",
      "url": "/documentation/Swift/Equatable"
    },
    "doc://com.externally.resolved.symbol/s:SY": {
      "abstract": [
        {
          "text": "A type that can be converted to and from an associated raw value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "RawRepresentable"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SY8RawValueQa",
          "text": "RawValue"
        },
        {
          "kind": "text",
          "text": ">"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SY",
      "kind": "symbol",
      "role": "symbol",
      "title": "RawRepresentable",
      "type": "topic",
      "url": "/documentation/Swift/RawRepresentable"
    },
    "doc://com.externally.resolved.symbol/s:s8SendableP": {
      "abstract": [
        {
          "text": "A thread-safe type whose values can be shared across arbitrary concurrent contexts without introducing a risk of data races.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Sendable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s8SendableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "Sendable",
      "type": "topic",
      "url": "/documentation/Swift/Sendable"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:SQ",
        "doc://com.externally.resolved.symbol/s:SH",
        "doc://com.externally.resolved.symbol/s:SY",
        "doc://com.externally.resolved.symbol/s:s8SendableP"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Constants",
      "generated": true,
      "identifiers": [
        "doc://com.apple.pdfkit/documentation/PDFKit/PDFDocumentPermissions",
        "doc://com.apple.pdfkit/documentation/PDFKit/PDFDocumentWriteOption"
      ],
      "title": "Constants"
    }
  ],
  "topicSections": [
    {
      "anchor": "Creating-Document-Attributes",
      "identifiers": [
        "doc://com.apple.pdfkit/documentation/PDFKit/PDFDocumentAttribute/init(rawValue:)"
      ],
      "title": "Creating Document Attributes"
    },
    {
      "anchor": "Getting-Document-Attributes",
      "identifiers": [
        "doc://com.apple.pdfkit/documentation/PDFKit/PDFDocumentAttribute/authorAttribute",
        "doc://com.apple.pdfkit/documentation/PDFKit/PDFDocumentAttribute/creationDateAttribute",
        "doc://com.apple.pdfkit/documentation/PDFKit/PDFDocumentAttribute/creatorAttribute",
        "doc://com.apple.pdfkit/documentation/PDFKit/PDFDocumentAttribute/keywordsAttribute",
        "doc://com.apple.pdfkit/documentation/PDFKit/PDFDocumentAttribute/modificationDateAttribute",
        "doc://com.apple.pdfkit/documentation/PDFKit/PDFDocumentAttribute/producerAttribute",
        "doc://com.apple.pdfkit/documentation/PDFKit/PDFDocumentAttribute/subjectAttribute",
        "doc://com.apple.pdfkit/documentation/PDFKit/PDFDocumentAttribute/titleAttribute"
      ],
      "title": "Getting Document Attributes"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "11.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "11.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "11.0",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.4",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Type Alias"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "PDFDocumentAttribute"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "typealias"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PDFDocumentAttribute"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "PDFDocumentAttribute"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.pdfkit/documentation/PDFKit"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Getting-Document-Attributes",
              "identifiers": [
                "doc://com.apple.pdfkit/documentation/PDFKit/PDFDocumentAttribute/authorAttribute",
                "doc://com.apple.pdfkit/documentation/PDFKit/PDFDocumentAttribute/creationDateAttribute",
                "doc://com.apple.pdfkit/documentation/PDFKit/PDFDocumentAttribute/creatorAttribute",
                "doc://com.apple.pdfkit/documentation/PDFKit/PDFDocumentAttribute/keywordsAttribute",
                "doc://com.apple.pdfkit/documentation/PDFKit/PDFDocumentAttribute/modificationDateAttribute",
                "doc://com.apple.pdfkit/documentation/PDFKit/PDFDocumentAttribute/producerAttribute",
                "doc://com.apple.pdfkit/documentation/PDFKit/PDFDocumentAttribute/subjectAttribute",
                "doc://com.apple.pdfkit/documentation/PDFKit/PDFDocumentAttribute/titleAttribute"
              ],
              "title": "Getting Document Attributes"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Constants",
              "generated": true,
              "identifiers": [
                "doc://com.apple.pdfkit/documentation/PDFKit/PDFDocumentPermissions",
                "doc://com.apple.pdfkit/documentation/PDFKit/PDFDocumentWriteOption"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "typedef"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSString",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(cs)NSString",
                    "text": "NSString"
                  },
                  {
                    "kind": "text",
                    "text": " * "
                  },
                  {
                    "kind": "identifier",
                    "text": "PDFDocumentAttribute"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFDocumentAttribute~1titleAttribute/title",
          "value": "PDFDocumentTitleAttribute"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFDocumentAttribute~1titleAttribute/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PDFDocumentTitleAttribute"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFDocumentAttribute~1creationDateAttribute/title",
          "value": "PDFDocumentCreationDateAttribute"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFDocumentAttribute~1creationDateAttribute/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PDFDocumentCreationDateAttribute"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFDocumentAttribute~1creatorAttribute/title",
          "value": "PDFDocumentCreatorAttribute"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFDocumentAttribute~1creatorAttribute/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PDFDocumentCreatorAttribute"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFDocumentAttribute~1keywordsAttribute/title",
          "value": "PDFDocumentKeywordsAttribute"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFDocumentAttribute~1keywordsAttribute/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PDFDocumentKeywordsAttribute"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFDocumentAttribute/title",
          "value": "PDFDocumentAttribute"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFDocumentAttribute/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PDFDocumentAttribute"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFDocumentAttribute/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "PDFDocumentAttribute"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFDocumentPermissions/title",
          "value": "PDFDocumentPermissions"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFDocumentPermissions/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PDFDocumentPermissions"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFDocumentPermissions/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "PDFDocumentPermissions"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:objc(cs)NSString/abstract",
          "value": [
            {
              "text": "A static, plain-text Unicode string object.",
              "type": "text"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFDocumentAttribute~1modificationDateAttribute/title",
          "value": "PDFDocumentModificationDateAttribute"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFDocumentAttribute~1modificationDateAttribute/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PDFDocumentModificationDateAttribute"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFDocumentWriteOption/title",
          "value": "PDFDocumentWriteOption"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFDocumentWriteOption/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PDFDocumentWriteOption"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFDocumentWriteOption/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "PDFDocumentWriteOption"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFDocumentAttribute~1producerAttribute/title",
          "value": "PDFDocumentProducerAttribute"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFDocumentAttribute~1producerAttribute/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PDFDocumentProducerAttribute"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFDocumentAttribute~1authorAttribute/title",
          "value": "PDFDocumentAuthorAttribute"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFDocumentAttribute~1authorAttribute/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PDFDocumentAuthorAttribute"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFDocumentAttribute~1subjectAttribute/title",
          "value": "PDFDocumentSubjectAttribute"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFDocumentAttribute~1subjectAttribute/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PDFDocumentSubjectAttribute"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/pdfkit/pdfdocumentattribute"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/pdfkit/pdfdocumentattribute"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
