{
  "abstract": [
    {
      "text": "The following constants specify the available line ending styles.",
      "type": "text"
    }
  ],
  "diffAvailability": {
    "major": {
      "change": "modified",
      "platform": "Xcode",
      "versions": [
        "16.0",
        "16.3 beta 2"
      ]
    }
  },
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.pdfkit/documentation/PDFKit"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.pdfkit/documentation/PDFKit/PDFLineStyle"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@PDFLineStyle",
    "fragments": [
      {
        "kind": "keyword",
        "text": "enum"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "PDFLineStyle"
      }
    ],
    "modules": [
      {
        "name": "PDFKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "PDFLineStyle"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "11.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "11.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "11.0",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.4",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Enumeration",
    "symbolKind": "enum",
    "title": "PDFLineStyle"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "enum"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "PDFLineStyle"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.pdfkit/documentation/PDFKit": {
      "abstract": [
        {
          "text": "Display and manipulate PDF documents in your apps.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.pdfkit/documentation/PDFKit",
      "kind": "symbol",
      "role": "collection",
      "title": "PDFKit",
      "type": "topic",
      "url": "/documentation/pdfkit"
    },
    "doc://com.apple.pdfkit/documentation/PDFKit/PDFAnnotationKey/lineEndingStyles": {
      "abstract": [
        {
          "text": "An array of string values that specifies the styles to use for the ends of lines.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "lineEndingStyles"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@PDFAnnotationKey",
          "text": "PDFAnnotationKey"
        }
      ],
      "identifier": "doc://com.apple.pdfkit/documentation/PDFKit/PDFAnnotationKey/lineEndingStyles",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PDFAnnotationKeyLineEndingStyles"
        }
      ],
      "role": "symbol",
      "title": "lineEndingStyles",
      "type": "topic",
      "url": "/documentation/pdfkit/pdfannotationkey/lineendingstyles"
    },
    "doc://com.apple.pdfkit/documentation/PDFKit/PDFAnnotationKey/linePoints": {
      "abstract": [
        {
          "text": "An array of floating point values that specifies the starting and ending points, in page-space coordinates, of a line.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "linePoints"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@PDFAnnotationKey",
          "text": "PDFAnnotationKey"
        }
      ],
      "identifier": "doc://com.apple.pdfkit/documentation/PDFKit/PDFAnnotationKey/linePoints",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PDFAnnotationKeyLinePoints"
        }
      ],
      "role": "symbol",
      "title": "linePoints",
      "type": "topic",
      "url": "/documentation/pdfkit/pdfannotationkey/linepoints"
    },
    "doc://com.apple.pdfkit/documentation/PDFKit/PDFAnnotationLineEndingStyle": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "PDFAnnotationLineEndingStyle"
        }
      ],
      "identifier": "doc://com.apple.pdfkit/documentation/PDFKit/PDFAnnotationLineEndingStyle",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PDFAnnotationLineEndingStyle"
        }
      ],
      "role": "symbol",
      "title": "PDFAnnotationLineEndingStyle",
      "type": "topic",
      "url": "/documentation/pdfkit/pdfannotationlineendingstyle"
    },
    "doc://com.apple.pdfkit/documentation/PDFKit/PDFLineStyle": {
      "abstract": [
        {
          "text": "The following constants specify the available line ending styles.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "PDFLineStyle"
        }
      ],
      "identifier": "doc://com.apple.pdfkit/documentation/PDFKit/PDFLineStyle",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PDFLineStyle"
        }
      ],
      "role": "symbol",
      "title": "PDFLineStyle",
      "type": "topic",
      "url": "/documentation/pdfkit/pdflinestyle"
    },
    "doc://com.apple.pdfkit/documentation/PDFKit/PDFLineStyle/circle": {
      "abstract": [
        {
          "text": "A circular line ending filled with the annotation’s interior color, if any.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "circle"
        }
      ],
      "identifier": "doc://com.apple.pdfkit/documentation/PDFKit/PDFLineStyle/circle",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kPDFLineStyleCircle"
        }
      ],
      "role": "symbol",
      "title": "PDFLineStyle.circle",
      "type": "topic",
      "url": "/documentation/pdfkit/pdflinestyle/circle"
    },
    "doc://com.apple.pdfkit/documentation/PDFKit/PDFLineStyle/closedArrow": {
      "abstract": [
        {
          "text": "A closed arrowhead line ending, consisting of a triangle with the acute vertex at the line end and filled with the annotation’s interior color, if any.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "closedArrow"
        }
      ],
      "identifier": "doc://com.apple.pdfkit/documentation/PDFKit/PDFLineStyle/closedArrow",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kPDFLineStyleClosedArrow"
        }
      ],
      "role": "symbol",
      "title": "PDFLineStyle.closedArrow",
      "type": "topic",
      "url": "/documentation/pdfkit/pdflinestyle/closedarrow"
    },
    "doc://com.apple.pdfkit/documentation/PDFKit/PDFLineStyle/diamond": {
      "abstract": [
        {
          "text": "A diamond-shaped line ending filled with the annotation’s interior color, if any.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "diamond"
        }
      ],
      "identifier": "doc://com.apple.pdfkit/documentation/PDFKit/PDFLineStyle/diamond",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kPDFLineStyleDiamond"
        }
      ],
      "role": "symbol",
      "title": "PDFLineStyle.diamond",
      "type": "topic",
      "url": "/documentation/pdfkit/pdflinestyle/diamond"
    },
    "doc://com.apple.pdfkit/documentation/PDFKit/PDFLineStyle/init(rawValue:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "?("
        },
        {
          "kind": "externalParam",
          "text": "rawValue"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.pdfkit/documentation/PDFKit/PDFLineStyle/init(rawValue:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "init(rawValue:)",
      "type": "topic",
      "url": "/documentation/pdfkit/pdflinestyle/init(rawvalue:)"
    },
    "doc://com.apple.pdfkit/documentation/PDFKit/PDFLineStyle/none": {
      "abstract": [
        {
          "text": "No line ending.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "none"
        }
      ],
      "identifier": "doc://com.apple.pdfkit/documentation/PDFKit/PDFLineStyle/none",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kPDFLineStyleNone"
        }
      ],
      "role": "symbol",
      "title": "PDFLineStyle.none",
      "type": "topic",
      "url": "/documentation/pdfkit/pdflinestyle/none"
    },
    "doc://com.apple.pdfkit/documentation/PDFKit/PDFLineStyle/openArrow": {
      "abstract": [
        {
          "text": "An open arrowhead line ending, composed from two short lines meeting in an acute angle at the line end.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "openArrow"
        }
      ],
      "identifier": "doc://com.apple.pdfkit/documentation/PDFKit/PDFLineStyle/openArrow",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kPDFLineStyleOpenArrow"
        }
      ],
      "role": "symbol",
      "title": "PDFLineStyle.openArrow",
      "type": "topic",
      "url": "/documentation/pdfkit/pdflinestyle/openarrow"
    },
    "doc://com.apple.pdfkit/documentation/PDFKit/PDFLineStyle/square": {
      "abstract": [
        {
          "text": "A square line ending filled with the annotation’s interior color, if any.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "square"
        }
      ],
      "identifier": "doc://com.apple.pdfkit/documentation/PDFKit/PDFLineStyle/square",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kPDFLineStyleSquare"
        }
      ],
      "role": "symbol",
      "title": "PDFLineStyle.square",
      "type": "topic",
      "url": "/documentation/pdfkit/pdflinestyle/square"
    },
    "doc://com.externally.resolved.symbol/s:SH": {
      "abstract": [
        {
          "text": "A type that can be hashed into a `Hasher` to produce an integer hash value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Hashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SQ",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SH",
      "kind": "symbol",
      "role": "symbol",
      "title": "Hashable",
      "type": "topic",
      "url": "/documentation/Swift/Hashable"
    },
    "doc://com.externally.resolved.symbol/s:SQ": {
      "abstract": [
        {
          "text": "A type that can be compared for value equality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SQ",
      "kind": "symbol",
      "role": "symbol",
      "title": "Equatable",
      "type": "topic",
      "url": "/documentation/Swift/Equatable"
    },
    "doc://com.externally.resolved.symbol/s:SY": {
      "abstract": [
        {
          "text": "A type that can be converted to and from an associated raw value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "RawRepresentable"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SY8RawValueQa",
          "text": "RawValue"
        },
        {
          "kind": "text",
          "text": ">"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SY",
      "kind": "symbol",
      "role": "symbol",
      "title": "RawRepresentable",
      "type": "topic",
      "url": "/documentation/Swift/RawRepresentable"
    },
    "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BitwiseCopyable"
        },
        {
          "kind": "text",
          "text": " : ~Escapable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "BitwiseCopyable",
      "type": "topic",
      "url": "/documentation/Swift/BitwiseCopyable"
    },
    "doc://com.externally.resolved.symbol/s:s8SendableP": {
      "abstract": [
        {
          "text": "A thread-safe type whose values can be shared across arbitrary concurrent contexts without introducing a risk of data races.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Sendable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s8SendableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "Sendable",
      "type": "topic",
      "url": "/documentation/Swift/Sendable"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
        "doc://com.externally.resolved.symbol/s:SQ",
        "doc://com.externally.resolved.symbol/s:SH",
        "doc://com.externally.resolved.symbol/s:SY",
        "doc://com.externally.resolved.symbol/s:s8SendableP"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Configuring-Line-Properties",
      "generated": true,
      "identifiers": [
        "doc://com.apple.pdfkit/documentation/PDFKit/PDFAnnotationKey/lineEndingStyles",
        "doc://com.apple.pdfkit/documentation/PDFKit/PDFAnnotationKey/linePoints",
        "doc://com.apple.pdfkit/documentation/PDFKit/PDFAnnotationLineEndingStyle"
      ],
      "title": "Configuring Line Properties"
    }
  ],
  "topicSections": [
    {
      "anchor": "Constants",
      "identifiers": [
        "doc://com.apple.pdfkit/documentation/PDFKit/PDFLineStyle/none",
        "doc://com.apple.pdfkit/documentation/PDFKit/PDFLineStyle/square",
        "doc://com.apple.pdfkit/documentation/PDFKit/PDFLineStyle/circle",
        "doc://com.apple.pdfkit/documentation/PDFKit/PDFLineStyle/diamond",
        "doc://com.apple.pdfkit/documentation/PDFKit/PDFLineStyle/openArrow",
        "doc://com.apple.pdfkit/documentation/PDFKit/PDFLineStyle/closedArrow"
      ],
      "title": "Constants"
    },
    {
      "anchor": "Initializers",
      "generated": true,
      "identifiers": [
        "doc://com.apple.pdfkit/documentation/PDFKit/PDFLineStyle/init(rawValue:)"
      ],
      "title": "Initializers"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "11.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "11.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "11.0",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.4",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "PDFLineStyle"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "enum"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PDFLineStyle"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "PDFLineStyle"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.pdfkit/documentation/PDFKit"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Constants",
              "identifiers": [
                "doc://com.apple.pdfkit/documentation/PDFKit/PDFLineStyle/none",
                "doc://com.apple.pdfkit/documentation/PDFKit/PDFLineStyle/square",
                "doc://com.apple.pdfkit/documentation/PDFKit/PDFLineStyle/circle",
                "doc://com.apple.pdfkit/documentation/PDFKit/PDFLineStyle/diamond",
                "doc://com.apple.pdfkit/documentation/PDFKit/PDFLineStyle/openArrow",
                "doc://com.apple.pdfkit/documentation/PDFKit/PDFLineStyle/closedArrow"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Configuring-Line-Properties",
              "generated": true,
              "identifiers": [
                "doc://com.apple.pdfkit/documentation/PDFKit/PDFAnnotationKey/lineEndingStyles",
                "doc://com.apple.pdfkit/documentation/PDFKit/PDFAnnotationKey/linePoints",
                "doc://com.apple.pdfkit/documentation/PDFKit/PDFAnnotationLineEndingStyle"
              ],
              "title": "Configuring Line Properties"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "enum"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "PDFLineStyle"
                  },
                  {
                    "kind": "text",
                    "text": " : "
                  },
                  {
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@NSInteger",
                    "text": "NSInteger"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFAnnotationKey~1lineEndingStyles/title",
          "value": "PDFAnnotationKeyLineEndingStyles"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFAnnotationKey~1lineEndingStyles/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PDFAnnotationKeyLineEndingStyles"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFLineStyle/title",
          "value": "PDFLineStyle"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFLineStyle/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PDFLineStyle"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFLineStyle/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "PDFLineStyle"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFLineStyle~1diamond/title",
          "value": "kPDFLineStyleDiamond"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFLineStyle~1diamond/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kPDFLineStyleDiamond"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFLineStyle~1openArrow/title",
          "value": "kPDFLineStyleOpenArrow"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFLineStyle~1openArrow/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kPDFLineStyleOpenArrow"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFLineStyle~1circle/title",
          "value": "kPDFLineStyleCircle"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFLineStyle~1circle/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kPDFLineStyleCircle"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFLineStyle~1closedArrow/title",
          "value": "kPDFLineStyleClosedArrow"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFLineStyle~1closedArrow/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kPDFLineStyleClosedArrow"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFLineStyle~1square/title",
          "value": "kPDFLineStyleSquare"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFLineStyle~1square/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kPDFLineStyleSquare"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFLineStyle~1none/title",
          "value": "kPDFLineStyleNone"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFLineStyle~1none/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kPDFLineStyleNone"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFAnnotationKey~1linePoints/title",
          "value": "PDFAnnotationKeyLinePoints"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFAnnotationKey~1linePoints/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PDFAnnotationKeyLinePoints"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFAnnotationLineEndingStyle/title",
          "value": "PDFAnnotationLineEndingStyle"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFAnnotationLineEndingStyle/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PDFAnnotationLineEndingStyle"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFAnnotationLineEndingStyle/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "PDFAnnotationLineEndingStyle"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/pdfkit/pdflinestyle"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/pdfkit/pdflinestyle"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
