{
  "abstract": [
    {
      "text": "The types of icons that a text annotation can use.",
      "type": "text"
    }
  ],
  "diffAvailability": {
    "major": {
      "change": "modified",
      "platform": "Xcode",
      "versions": [
        "16.0",
        "16.3 beta 2"
      ]
    }
  },
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.pdfkit/documentation/PDFKit"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.pdfkit/documentation/PDFKit/PDFTextAnnotationIconType"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@PDFTextAnnotationIconType",
    "fragments": [
      {
        "kind": "keyword",
        "text": "enum"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "PDFTextAnnotationIconType"
      }
    ],
    "modules": [
      {
        "name": "PDFKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "PDFTextAnnotationIconType"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "11.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "11.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "11.0",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.4",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Enumeration",
    "symbolKind": "enum",
    "title": "PDFTextAnnotationIconType"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "enum"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "PDFTextAnnotationIconType"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.pdfkit/documentation/PDFKit": {
      "abstract": [
        {
          "text": "Display and manipulate PDF documents in your apps.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.pdfkit/documentation/PDFKit",
      "kind": "symbol",
      "role": "collection",
      "title": "PDFKit",
      "type": "topic",
      "url": "/documentation/pdfkit"
    },
    "doc://com.apple.pdfkit/documentation/PDFKit/PDFAnnotation/iconType": {
      "abstract": [
        {
          "text": "The type of icon to display for a pop-up text annotation.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "iconType"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@PDFTextAnnotationIconType",
          "text": "PDFTextAnnotationIconType"
        }
      ],
      "identifier": "doc://com.apple.pdfkit/documentation/PDFKit/PDFAnnotation/iconType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "iconType"
        }
      ],
      "role": "symbol",
      "title": "iconType",
      "type": "topic",
      "url": "/documentation/pdfkit/pdfannotation/icontype"
    },
    "doc://com.apple.pdfkit/documentation/PDFKit/PDFAnnotationTextIconType": {
      "abstract": [
        {
          "text": "Constants for icon type values in text annotation property dictionaries.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "PDFAnnotationTextIconType"
        }
      ],
      "identifier": "doc://com.apple.pdfkit/documentation/PDFKit/PDFAnnotationTextIconType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PDFAnnotationTextIconType"
        }
      ],
      "role": "symbol",
      "title": "PDFAnnotationTextIconType",
      "type": "topic",
      "url": "/documentation/pdfkit/pdfannotationtexticontype"
    },
    "doc://com.apple.pdfkit/documentation/PDFKit/PDFTextAnnotationIconType": {
      "abstract": [
        {
          "text": "The types of icons that a text annotation can use.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "PDFTextAnnotationIconType"
        }
      ],
      "identifier": "doc://com.apple.pdfkit/documentation/PDFKit/PDFTextAnnotationIconType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PDFTextAnnotationIconType"
        }
      ],
      "role": "symbol",
      "title": "PDFTextAnnotationIconType",
      "type": "topic",
      "url": "/documentation/pdfkit/pdftextannotationicontype"
    },
    "doc://com.apple.pdfkit/documentation/PDFKit/PDFTextAnnotationIconType/comment": {
      "abstract": [
        {
          "text": "Comment annotation icon.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "comment"
        }
      ],
      "identifier": "doc://com.apple.pdfkit/documentation/PDFKit/PDFTextAnnotationIconType/comment",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kPDFTextAnnotationIconComment"
        }
      ],
      "role": "symbol",
      "title": "PDFTextAnnotationIconType.comment",
      "type": "topic",
      "url": "/documentation/pdfkit/pdftextannotationicontype/comment"
    },
    "doc://com.apple.pdfkit/documentation/PDFKit/PDFTextAnnotationIconType/help": {
      "abstract": [
        {
          "text": "Help annotation icon.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "help"
        }
      ],
      "identifier": "doc://com.apple.pdfkit/documentation/PDFKit/PDFTextAnnotationIconType/help",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kPDFTextAnnotationIconHelp"
        }
      ],
      "role": "symbol",
      "title": "PDFTextAnnotationIconType.help",
      "type": "topic",
      "url": "/documentation/pdfkit/pdftextannotationicontype/help"
    },
    "doc://com.apple.pdfkit/documentation/PDFKit/PDFTextAnnotationIconType/init(rawValue:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "?("
        },
        {
          "kind": "externalParam",
          "text": "rawValue"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.pdfkit/documentation/PDFKit/PDFTextAnnotationIconType/init(rawValue:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "init(rawValue:)",
      "type": "topic",
      "url": "/documentation/pdfkit/pdftextannotationicontype/init(rawvalue:)"
    },
    "doc://com.apple.pdfkit/documentation/PDFKit/PDFTextAnnotationIconType/insert": {
      "abstract": [
        {
          "text": "Insert annotation icon.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "insert"
        }
      ],
      "identifier": "doc://com.apple.pdfkit/documentation/PDFKit/PDFTextAnnotationIconType/insert",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kPDFTextAnnotationIconInsert"
        }
      ],
      "role": "symbol",
      "title": "PDFTextAnnotationIconType.insert",
      "type": "topic",
      "url": "/documentation/pdfkit/pdftextannotationicontype/insert"
    },
    "doc://com.apple.pdfkit/documentation/PDFKit/PDFTextAnnotationIconType/key": {
      "abstract": [
        {
          "text": "Key annotation icon.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "key"
        }
      ],
      "identifier": "doc://com.apple.pdfkit/documentation/PDFKit/PDFTextAnnotationIconType/key",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kPDFTextAnnotationIconKey"
        }
      ],
      "role": "symbol",
      "title": "PDFTextAnnotationIconType.key",
      "type": "topic",
      "url": "/documentation/pdfkit/pdftextannotationicontype/key"
    },
    "doc://com.apple.pdfkit/documentation/PDFKit/PDFTextAnnotationIconType/newParagraph": {
      "abstract": [
        {
          "text": "New Paragraph annotation icon.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "newParagraph"
        }
      ],
      "identifier": "doc://com.apple.pdfkit/documentation/PDFKit/PDFTextAnnotationIconType/newParagraph",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kPDFTextAnnotationIconNewParagraph"
        }
      ],
      "role": "symbol",
      "title": "PDFTextAnnotationIconType.newParagraph",
      "type": "topic",
      "url": "/documentation/pdfkit/pdftextannotationicontype/newparagraph"
    },
    "doc://com.apple.pdfkit/documentation/PDFKit/PDFTextAnnotationIconType/note": {
      "abstract": [
        {
          "text": "Note annotation icon.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "note"
        }
      ],
      "identifier": "doc://com.apple.pdfkit/documentation/PDFKit/PDFTextAnnotationIconType/note",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kPDFTextAnnotationIconNote"
        }
      ],
      "role": "symbol",
      "title": "PDFTextAnnotationIconType.note",
      "type": "topic",
      "url": "/documentation/pdfkit/pdftextannotationicontype/note"
    },
    "doc://com.apple.pdfkit/documentation/PDFKit/PDFTextAnnotationIconType/paragraph": {
      "abstract": [
        {
          "text": "Paragraph annotation icon.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "paragraph"
        }
      ],
      "identifier": "doc://com.apple.pdfkit/documentation/PDFKit/PDFTextAnnotationIconType/paragraph",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kPDFTextAnnotationIconParagraph"
        }
      ],
      "role": "symbol",
      "title": "PDFTextAnnotationIconType.paragraph",
      "type": "topic",
      "url": "/documentation/pdfkit/pdftextannotationicontype/paragraph"
    },
    "doc://com.externally.resolved.symbol/s:SH": {
      "abstract": [
        {
          "text": "A type that can be hashed into a `Hasher` to produce an integer hash value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Hashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SQ",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SH",
      "kind": "symbol",
      "role": "symbol",
      "title": "Hashable",
      "type": "topic",
      "url": "/documentation/Swift/Hashable"
    },
    "doc://com.externally.resolved.symbol/s:SQ": {
      "abstract": [
        {
          "text": "A type that can be compared for value equality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SQ",
      "kind": "symbol",
      "role": "symbol",
      "title": "Equatable",
      "type": "topic",
      "url": "/documentation/Swift/Equatable"
    },
    "doc://com.externally.resolved.symbol/s:SY": {
      "abstract": [
        {
          "text": "A type that can be converted to and from an associated raw value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "RawRepresentable"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SY8RawValueQa",
          "text": "RawValue"
        },
        {
          "kind": "text",
          "text": ">"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SY",
      "kind": "symbol",
      "role": "symbol",
      "title": "RawRepresentable",
      "type": "topic",
      "url": "/documentation/Swift/RawRepresentable"
    },
    "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BitwiseCopyable"
        },
        {
          "kind": "text",
          "text": " : ~Escapable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "BitwiseCopyable",
      "type": "topic",
      "url": "/documentation/Swift/BitwiseCopyable"
    },
    "doc://com.externally.resolved.symbol/s:s8SendableP": {
      "abstract": [
        {
          "text": "A thread-safe type whose values can be shared across arbitrary concurrent contexts without introducing a risk of data races.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Sendable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s8SendableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "Sendable",
      "type": "topic",
      "url": "/documentation/Swift/Sendable"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
        "doc://com.externally.resolved.symbol/s:SQ",
        "doc://com.externally.resolved.symbol/s:SH",
        "doc://com.externally.resolved.symbol/s:SY",
        "doc://com.externally.resolved.symbol/s:s8SendableP"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Configuring-Text-Annotations",
      "generated": true,
      "identifiers": [
        "doc://com.apple.pdfkit/documentation/PDFKit/PDFAnnotation/iconType",
        "doc://com.apple.pdfkit/documentation/PDFKit/PDFAnnotationTextIconType"
      ],
      "title": "Configuring Text Annotations"
    }
  ],
  "topicSections": [
    {
      "anchor": "Constants",
      "identifiers": [
        "doc://com.apple.pdfkit/documentation/PDFKit/PDFTextAnnotationIconType/comment",
        "doc://com.apple.pdfkit/documentation/PDFKit/PDFTextAnnotationIconType/key",
        "doc://com.apple.pdfkit/documentation/PDFKit/PDFTextAnnotationIconType/note",
        "doc://com.apple.pdfkit/documentation/PDFKit/PDFTextAnnotationIconType/help",
        "doc://com.apple.pdfkit/documentation/PDFKit/PDFTextAnnotationIconType/newParagraph",
        "doc://com.apple.pdfkit/documentation/PDFKit/PDFTextAnnotationIconType/paragraph",
        "doc://com.apple.pdfkit/documentation/PDFKit/PDFTextAnnotationIconType/insert"
      ],
      "title": "Constants"
    },
    {
      "anchor": "Initializers",
      "generated": true,
      "identifiers": [
        "doc://com.apple.pdfkit/documentation/PDFKit/PDFTextAnnotationIconType/init(rawValue:)"
      ],
      "title": "Initializers"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "11.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "11.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "11.0",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.4",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "PDFTextAnnotationIconType"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "enum"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PDFTextAnnotationIconType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "PDFTextAnnotationIconType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.pdfkit/documentation/PDFKit"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Constants",
              "identifiers": [
                "doc://com.apple.pdfkit/documentation/PDFKit/PDFTextAnnotationIconType/comment",
                "doc://com.apple.pdfkit/documentation/PDFKit/PDFTextAnnotationIconType/key",
                "doc://com.apple.pdfkit/documentation/PDFKit/PDFTextAnnotationIconType/note",
                "doc://com.apple.pdfkit/documentation/PDFKit/PDFTextAnnotationIconType/help",
                "doc://com.apple.pdfkit/documentation/PDFKit/PDFTextAnnotationIconType/newParagraph",
                "doc://com.apple.pdfkit/documentation/PDFKit/PDFTextAnnotationIconType/paragraph",
                "doc://com.apple.pdfkit/documentation/PDFKit/PDFTextAnnotationIconType/insert"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Configuring-Text-Annotations",
              "generated": true,
              "identifiers": [
                "doc://com.apple.pdfkit/documentation/PDFKit/PDFAnnotation/iconType",
                "doc://com.apple.pdfkit/documentation/PDFKit/PDFAnnotationTextIconType"
              ],
              "title": "Configuring Text Annotations"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "enum"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "PDFTextAnnotationIconType"
                  },
                  {
                    "kind": "text",
                    "text": " : "
                  },
                  {
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@NSInteger",
                    "text": "NSInteger"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFTextAnnotationIconType~1newParagraph/title",
          "value": "kPDFTextAnnotationIconNewParagraph"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFTextAnnotationIconType~1newParagraph/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kPDFTextAnnotationIconNewParagraph"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFTextAnnotationIconType~1comment/title",
          "value": "kPDFTextAnnotationIconComment"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFTextAnnotationIconType~1comment/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kPDFTextAnnotationIconComment"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFTextAnnotationIconType~1help/title",
          "value": "kPDFTextAnnotationIconHelp"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFTextAnnotationIconType~1help/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kPDFTextAnnotationIconHelp"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFTextAnnotationIconType/title",
          "value": "PDFTextAnnotationIconType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFTextAnnotationIconType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PDFTextAnnotationIconType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFTextAnnotationIconType/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "PDFTextAnnotationIconType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFTextAnnotationIconType~1insert/title",
          "value": "kPDFTextAnnotationIconInsert"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFTextAnnotationIconType~1insert/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kPDFTextAnnotationIconInsert"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFTextAnnotationIconType~1key/title",
          "value": "kPDFTextAnnotationIconKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFTextAnnotationIconType~1key/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kPDFTextAnnotationIconKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFTextAnnotationIconType~1paragraph/title",
          "value": "kPDFTextAnnotationIconParagraph"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFTextAnnotationIconType~1paragraph/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kPDFTextAnnotationIconParagraph"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFAnnotation~1iconType/title",
          "value": "iconType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFAnnotation~1iconType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "iconType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFTextAnnotationIconType~1note/title",
          "value": "kPDFTextAnnotationIconNote"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFTextAnnotationIconType~1note/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kPDFTextAnnotationIconNote"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFAnnotationTextIconType/title",
          "value": "PDFAnnotationTextIconType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFAnnotationTextIconType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PDFAnnotationTextIconType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFAnnotationTextIconType/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "PDFAnnotationTextIconType"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/pdfkit/pdftextannotationicontype"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/pdfkit/pdftextannotationicontype"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
