{
  "abstract": [
    {
      "text": "Properties that specify what functions are allowed for a PDF document.",
      "type": "text"
    }
  ],
  "diffAvailability": {
    "major": {
      "change": "modified",
      "platform": "Xcode",
      "versions": [
        "16.0",
        "16.3 beta 2"
      ]
    }
  },
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.pdfkit/documentation/PDFKit",
        "doc://com.apple.pdfkit/documentation/PDFKit/PDFDocument",
        "doc://com.apple.pdfkit/documentation/PDFKit/read-operations"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.pdfkit/documentation/PDFKit/permission-properties"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "PDFKit"
      }
    ],
    "role": "collectionGroup",
    "roleHeading": "API Collection",
    "title": "Permission Properties"
  },
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.pdfkit/documentation/PDFKit": {
      "abstract": [
        {
          "text": "Display and manipulate PDF documents in your apps.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.pdfkit/documentation/PDFKit",
      "kind": "symbol",
      "role": "collection",
      "title": "PDFKit",
      "type": "topic",
      "url": "/documentation/pdfkit"
    },
    "doc://com.apple.pdfkit/documentation/PDFKit/PDFDocument": {
      "abstract": [
        {
          "text": "An object that represents PDF data or a PDF file and defines methods for writing, searching, and selecting PDF data.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "PDFDocument"
        }
      ],
      "identifier": "doc://com.apple.pdfkit/documentation/PDFKit/PDFDocument",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PDFDocument"
        }
      ],
      "role": "symbol",
      "title": "PDFDocument",
      "type": "topic",
      "url": "/documentation/pdfkit/pdfdocument"
    },
    "doc://com.apple.pdfkit/documentation/PDFKit/PDFDocument/allowsCommenting": {
      "abstract": [
        {
          "text": "A Boolean value indicating whether you can create or modify document annotations, including form field entries.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "allowsCommenting"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.pdfkit/documentation/PDFKit/PDFDocument/allowsCommenting",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "allowsCommenting"
        }
      ],
      "role": "symbol",
      "title": "allowsCommenting",
      "type": "topic",
      "url": "/documentation/pdfkit/pdfdocument/allowscommenting"
    },
    "doc://com.apple.pdfkit/documentation/PDFKit/PDFDocument/allowsContentAccessibility": {
      "abstract": [
        {
          "text": "A Boolean value indicating whether you can extract content from the document, but only for the purpose of accessibility.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "allowsContentAccessibility"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.pdfkit/documentation/PDFKit/PDFDocument/allowsContentAccessibility",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "allowsContentAccessibility"
        }
      ],
      "role": "symbol",
      "title": "allowsContentAccessibility",
      "type": "topic",
      "url": "/documentation/pdfkit/pdfdocument/allowscontentaccessibility"
    },
    "doc://com.apple.pdfkit/documentation/PDFKit/PDFDocument/allowsCopying": {
      "abstract": [
        {
          "text": "A Boolean value indicating whether the document allows copying of content to the Pasteboard.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "allowsCopying"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.pdfkit/documentation/PDFKit/PDFDocument/allowsCopying",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "allowsCopying"
        }
      ],
      "role": "symbol",
      "title": "allowsCopying",
      "type": "topic",
      "url": "/documentation/pdfkit/pdfdocument/allowscopying"
    },
    "doc://com.apple.pdfkit/documentation/PDFKit/PDFDocument/allowsDocumentAssembly": {
      "abstract": [
        {
          "text": "A Boolean value indicating whether you can manage a document by inserting, deleting, and rotating pages.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "allowsDocumentAssembly"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.pdfkit/documentation/PDFKit/PDFDocument/allowsDocumentAssembly",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "allowsDocumentAssembly"
        }
      ],
      "role": "symbol",
      "title": "allowsDocumentAssembly",
      "type": "topic",
      "url": "/documentation/pdfkit/pdfdocument/allowsdocumentassembly"
    },
    "doc://com.apple.pdfkit/documentation/PDFKit/PDFDocument/allowsDocumentChanges": {
      "abstract": [
        {
          "text": "A Boolean value indicating whether you can modify the document contents except for document attributes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "allowsDocumentChanges"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.pdfkit/documentation/PDFKit/PDFDocument/allowsDocumentChanges",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "allowsDocumentChanges"
        }
      ],
      "role": "symbol",
      "title": "allowsDocumentChanges",
      "type": "topic",
      "url": "/documentation/pdfkit/pdfdocument/allowsdocumentchanges"
    },
    "doc://com.apple.pdfkit/documentation/PDFKit/PDFDocument/allowsFormFieldEntry": {
      "abstract": [
        {
          "text": "A Boolean value indicating whether you can modify form field entries even if you can’t edit document annotations.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "allowsFormFieldEntry"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.pdfkit/documentation/PDFKit/PDFDocument/allowsFormFieldEntry",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "allowsFormFieldEntry"
        }
      ],
      "role": "symbol",
      "title": "allowsFormFieldEntry",
      "type": "topic",
      "url": "/documentation/pdfkit/pdfdocument/allowsformfieldentry"
    },
    "doc://com.apple.pdfkit/documentation/PDFKit/PDFDocument/allowsPrinting": {
      "abstract": [
        {
          "text": "A Boolean value indicating whether the document allows printing.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "allowsPrinting"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.pdfkit/documentation/PDFKit/PDFDocument/allowsPrinting",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "allowsPrinting"
        }
      ],
      "role": "symbol",
      "title": "allowsPrinting",
      "type": "topic",
      "url": "/documentation/pdfkit/pdfdocument/allowsprinting"
    },
    "doc://com.apple.pdfkit/documentation/PDFKit/PDFDocument/isEncrypted": {
      "abstract": [
        {
          "text": "A Boolean value specifying whether the document is encrypted.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "isEncrypted"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.pdfkit/documentation/PDFKit/PDFDocument/isEncrypted",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "isEncrypted"
        }
      ],
      "role": "symbol",
      "title": "isEncrypted",
      "type": "topic",
      "url": "/documentation/pdfkit/pdfdocument/isencrypted"
    },
    "doc://com.apple.pdfkit/documentation/PDFKit/PDFDocument/isLocked": {
      "abstract": [
        {
          "text": "A Boolean value indicating whether the document is locked.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "isLocked"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.pdfkit/documentation/PDFKit/PDFDocument/isLocked",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "isLocked"
        }
      ],
      "role": "symbol",
      "title": "isLocked",
      "type": "topic",
      "url": "/documentation/pdfkit/pdfdocument/islocked"
    },
    "doc://com.apple.pdfkit/documentation/PDFKit/PDFDocument/permissionsStatus": {
      "abstract": [
        {
          "text": "The permissions status of the PDF document.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "permissionsStatus"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@PDFDocumentPermissions",
          "text": "PDFDocumentPermissions"
        }
      ],
      "identifier": "doc://com.apple.pdfkit/documentation/PDFKit/PDFDocument/permissionsStatus",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "permissionsStatus"
        }
      ],
      "role": "symbol",
      "title": "permissionsStatus",
      "type": "topic",
      "url": "/documentation/pdfkit/pdfdocument/permissionsstatus"
    },
    "doc://com.apple.pdfkit/documentation/PDFKit/PDFDocument/unlock(withPassword:)": {
      "abstract": [
        {
          "text": "Attempts to unlock an encrypted document.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "unlock"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "withPassword"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.pdfkit/documentation/PDFKit/PDFDocument/unlock(withPassword:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "unlockWithPassword:"
        }
      ],
      "role": "symbol",
      "title": "unlock(withPassword:)",
      "type": "topic",
      "url": "/documentation/pdfkit/pdfdocument/unlock(withpassword:)"
    },
    "doc://com.apple.pdfkit/documentation/PDFKit/read-operations": {
      "abstract": [
        {
          "text": "Operations that let you access documents and pages, manage document security, and work with searching and selections.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.pdfkit/documentation/PDFKit/read-operations",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Read Operations",
      "type": "topic",
      "url": "/documentation/pdfkit/read-operations"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Managing-Document-Security",
      "generated": true,
      "identifiers": [
        "doc://com.apple.pdfkit/documentation/PDFKit/PDFDocument/isEncrypted",
        "doc://com.apple.pdfkit/documentation/PDFKit/PDFDocument/isLocked",
        "doc://com.apple.pdfkit/documentation/PDFKit/PDFDocument/unlock(withPassword:)",
        "doc://com.apple.pdfkit/documentation/PDFKit/PDFDocument/permissionsStatus"
      ],
      "title": "Managing Document Security"
    }
  ],
  "topicSections": [
    {
      "anchor": "Getting-Permissions",
      "identifiers": [
        "doc://com.apple.pdfkit/documentation/PDFKit/PDFDocument/allowsCopying",
        "doc://com.apple.pdfkit/documentation/PDFKit/PDFDocument/allowsPrinting",
        "doc://com.apple.pdfkit/documentation/PDFKit/PDFDocument/allowsCommenting",
        "doc://com.apple.pdfkit/documentation/PDFKit/PDFDocument/allowsContentAccessibility",
        "doc://com.apple.pdfkit/documentation/PDFKit/PDFDocument/allowsDocumentAssembly",
        "doc://com.apple.pdfkit/documentation/PDFKit/PDFDocument/allowsDocumentChanges",
        "doc://com.apple.pdfkit/documentation/PDFKit/PDFDocument/allowsFormFieldEntry"
      ],
      "title": "Getting Permissions"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Getting-Permissions",
              "identifiers": [
                "doc://com.apple.pdfkit/documentation/PDFKit/PDFDocument/allowsCopying",
                "doc://com.apple.pdfkit/documentation/PDFKit/PDFDocument/allowsPrinting",
                "doc://com.apple.pdfkit/documentation/PDFKit/PDFDocument/allowsCommenting",
                "doc://com.apple.pdfkit/documentation/PDFKit/PDFDocument/allowsContentAccessibility",
                "doc://com.apple.pdfkit/documentation/PDFKit/PDFDocument/allowsDocumentAssembly",
                "doc://com.apple.pdfkit/documentation/PDFKit/PDFDocument/allowsDocumentChanges",
                "doc://com.apple.pdfkit/documentation/PDFKit/PDFDocument/allowsFormFieldEntry"
              ],
              "title": "Getting Permissions"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Managing-Document-Security",
              "generated": true,
              "identifiers": [
                "doc://com.apple.pdfkit/documentation/PDFKit/PDFDocument/isEncrypted",
                "doc://com.apple.pdfkit/documentation/PDFKit/PDFDocument/isLocked",
                "doc://com.apple.pdfkit/documentation/PDFKit/PDFDocument/unlock(withPassword:)",
                "doc://com.apple.pdfkit/documentation/PDFKit/PDFDocument/permissionsStatus"
              ],
              "title": "Managing Document Security"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFDocument~1allowsFormFieldEntry/title",
          "value": "allowsFormFieldEntry"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFDocument~1allowsFormFieldEntry/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "allowsFormFieldEntry"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFDocument~1isLocked/title",
          "value": "isLocked"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFDocument~1isLocked/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "isLocked"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFDocument~1allowsDocumentAssembly/title",
          "value": "allowsDocumentAssembly"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFDocument~1allowsDocumentAssembly/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "allowsDocumentAssembly"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFDocument~1allowsCommenting/title",
          "value": "allowsCommenting"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFDocument~1allowsCommenting/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "allowsCommenting"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFDocument~1allowsCopying/title",
          "value": "allowsCopying"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFDocument~1allowsCopying/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "allowsCopying"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFDocument/title",
          "value": "PDFDocument"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFDocument/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PDFDocument"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFDocument/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "PDFDocument"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFDocument~1unlock(withPassword:)/title",
          "value": "unlockWithPassword:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFDocument~1unlock(withPassword:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "unlockWithPassword:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFDocument~1allowsPrinting/title",
          "value": "allowsPrinting"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFDocument~1allowsPrinting/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "allowsPrinting"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFDocument~1allowsDocumentChanges/title",
          "value": "allowsDocumentChanges"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFDocument~1allowsDocumentChanges/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "allowsDocumentChanges"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFDocument~1isEncrypted/title",
          "value": "isEncrypted"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFDocument~1isEncrypted/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "isEncrypted"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFDocument~1allowsContentAccessibility/title",
          "value": "allowsContentAccessibility"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFDocument~1allowsContentAccessibility/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "allowsContentAccessibility"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFDocument~1permissionsStatus/title",
          "value": "permissionsStatus"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFDocument~1permissionsStatus/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "permissionsStatus"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/pdfkit/permission-properties"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/pdfkit/permission-properties"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
