{
  "abstract": [
    {
      "text": "Operations that let you access documents and pages, manage document security, and work with searching and selections.",
      "type": "text"
    }
  ],
  "diffAvailability": {
    "major": {
      "change": "modified",
      "platform": "Xcode",
      "versions": [
        "16.0",
        "16.3 beta 2"
      ]
    }
  },
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.pdfkit/documentation/PDFKit",
        "doc://com.apple.pdfkit/documentation/PDFKit/PDFDocument"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.pdfkit/documentation/PDFKit/read-operations"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "PDFKit"
      }
    ],
    "role": "collectionGroup",
    "roleHeading": "API Collection",
    "title": "Read Operations"
  },
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.pdfkit/documentation/PDFKit": {
      "abstract": [
        {
          "text": "Display and manipulate PDF documents in your apps.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.pdfkit/documentation/PDFKit",
      "kind": "symbol",
      "role": "collection",
      "title": "PDFKit",
      "type": "topic",
      "url": "/documentation/pdfkit"
    },
    "doc://com.apple.pdfkit/documentation/PDFKit/PDFDocument": {
      "abstract": [
        {
          "text": "An object that represents PDF data or a PDF file and defines methods for writing, searching, and selecting PDF data.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "PDFDocument"
        }
      ],
      "identifier": "doc://com.apple.pdfkit/documentation/PDFKit/PDFDocument",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PDFDocument"
        }
      ],
      "role": "symbol",
      "title": "PDFDocument",
      "type": "topic",
      "url": "/documentation/pdfkit/pdfdocument"
    },
    "doc://com.apple.pdfkit/documentation/PDFKit/PDFDocument/documentAttributes": {
      "abstract": [
        {
          "text": "A dictionary of document metadata.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "documentAttributes"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s11AnyHashableV",
          "text": "AnyHashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "keyword",
          "text": "Any"
        },
        {
          "kind": "text",
          "text": "]?"
        }
      ],
      "identifier": "doc://com.apple.pdfkit/documentation/PDFKit/PDFDocument/documentAttributes",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "documentAttributes"
        }
      ],
      "role": "symbol",
      "title": "documentAttributes",
      "type": "topic",
      "url": "/documentation/pdfkit/pdfdocument/documentattributes"
    },
    "doc://com.apple.pdfkit/documentation/PDFKit/PDFDocument/documentRef": {
      "abstract": [
        {
          "text": "The ",
          "type": "text"
        },
        {
          "code": "CGPDFDocument",
          "type": "codeVoice"
        },
        {
          "text": " associated with the ",
          "type": "text"
        },
        {
          "code": "PDFDocument",
          "type": "codeVoice"
        },
        {
          "text": " object.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "documentRef"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CGPDFDocumentRef",
          "text": "CGPDFDocument"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.pdfkit/documentation/PDFKit/PDFDocument/documentRef",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "documentRef"
        }
      ],
      "role": "symbol",
      "title": "documentRef",
      "type": "topic",
      "url": "/documentation/pdfkit/pdfdocument/documentref"
    },
    "doc://com.apple.pdfkit/documentation/PDFKit/PDFDocument/documentURL": {
      "abstract": [
        {
          "text": "The URL for the document.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "documentURL"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10Foundation3URLV",
          "text": "URL"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.pdfkit/documentation/PDFKit/PDFDocument/documentURL",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "documentURL"
        }
      ],
      "role": "symbol",
      "title": "documentURL",
      "type": "topic",
      "url": "/documentation/pdfkit/pdfdocument/documenturl"
    },
    "doc://com.apple.pdfkit/documentation/PDFKit/PDFDocument/exchangePage(at:withPageAt:)": {
      "abstract": [
        {
          "text": "Swaps one page with another.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "exchangePage"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "at"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "withPageAt"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.pdfkit/documentation/PDFKit/PDFDocument/exchangePage(at:withPageAt:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "exchangePageAtIndex:withPageAtIndex:"
        }
      ],
      "role": "symbol",
      "title": "exchangePage(at:withPageAt:)",
      "type": "topic",
      "url": "/documentation/pdfkit/pdfdocument/exchangepage(at:withpageat:)"
    },
    "doc://com.apple.pdfkit/documentation/PDFKit/PDFDocument/index(for:)": {
      "abstract": [
        {
          "text": "Gets the index number for the specified page.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "index"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "for"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)PDFPage",
          "text": "PDFPage"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.pdfkit/documentation/PDFKit/PDFDocument/index(for:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "indexForPage:"
        }
      ],
      "role": "symbol",
      "title": "index(for:)",
      "type": "topic",
      "url": "/documentation/pdfkit/pdfdocument/index(for:)"
    },
    "doc://com.apple.pdfkit/documentation/PDFKit/PDFDocument/insert(_:at:)": {
      "abstract": [
        {
          "text": "Inserts a page at the specified index point.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "insert"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)PDFPage",
          "text": "PDFPage"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "at"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.pdfkit/documentation/PDFKit/PDFDocument/insert(_:at:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "insertPage:atIndex:"
        }
      ],
      "role": "symbol",
      "title": "insert(_:at:)",
      "type": "topic",
      "url": "/documentation/pdfkit/pdfdocument/insert(_:at:)"
    },
    "doc://com.apple.pdfkit/documentation/PDFKit/PDFDocument/isEncrypted": {
      "abstract": [
        {
          "text": "A Boolean value specifying whether the document is encrypted.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "isEncrypted"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.pdfkit/documentation/PDFKit/PDFDocument/isEncrypted",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "isEncrypted"
        }
      ],
      "role": "symbol",
      "title": "isEncrypted",
      "type": "topic",
      "url": "/documentation/pdfkit/pdfdocument/isencrypted"
    },
    "doc://com.apple.pdfkit/documentation/PDFKit/PDFDocument/isLocked": {
      "abstract": [
        {
          "text": "A Boolean value indicating whether the document is locked.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "isLocked"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.pdfkit/documentation/PDFKit/PDFDocument/isLocked",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "isLocked"
        }
      ],
      "role": "symbol",
      "title": "isLocked",
      "type": "topic",
      "url": "/documentation/pdfkit/pdfdocument/islocked"
    },
    "doc://com.apple.pdfkit/documentation/PDFKit/PDFDocument/majorVersion": {
      "abstract": [
        {
          "text": "The major version of the document.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "majorVersion"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.pdfkit/documentation/PDFKit/PDFDocument/majorVersion",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "majorVersion"
        }
      ],
      "role": "symbol",
      "title": "majorVersion",
      "type": "topic",
      "url": "/documentation/pdfkit/pdfdocument/majorversion"
    },
    "doc://com.apple.pdfkit/documentation/PDFKit/PDFDocument/minorVersion": {
      "abstract": [
        {
          "text": "The minor version of the document.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "minorVersion"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.pdfkit/documentation/PDFKit/PDFDocument/minorVersion",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "minorVersion"
        }
      ],
      "role": "symbol",
      "title": "minorVersion",
      "type": "topic",
      "url": "/documentation/pdfkit/pdfdocument/minorversion"
    },
    "doc://com.apple.pdfkit/documentation/PDFKit/PDFDocument/outlineItem(for:)": {
      "abstract": [
        {
          "text": "Returns the most likely parent PDF outline object for the selection.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "outlineItem"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "for"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)PDFSelection",
          "text": "PDFSelection"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)PDFOutline",
          "text": "PDFOutline"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.pdfkit/documentation/PDFKit/PDFDocument/outlineItem(for:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "outlineItemForSelection:"
        }
      ],
      "role": "symbol",
      "title": "outlineItem(for:)",
      "type": "topic",
      "url": "/documentation/pdfkit/pdfdocument/outlineitem(for:)"
    },
    "doc://com.apple.pdfkit/documentation/PDFKit/PDFDocument/outlineRoot": {
      "abstract": [
        {
          "text": "The document’s root outline to a PDF outline object.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "outlineRoot"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)PDFOutline",
          "text": "PDFOutline"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.pdfkit/documentation/PDFKit/PDFDocument/outlineRoot",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "outlineRoot"
        }
      ],
      "role": "symbol",
      "title": "outlineRoot",
      "type": "topic",
      "url": "/documentation/pdfkit/pdfdocument/outlineroot"
    },
    "doc://com.apple.pdfkit/documentation/PDFKit/PDFDocument/page(at:)": {
      "abstract": [
        {
          "text": "Returns the page at the specified index number.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "page"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "at"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)PDFPage",
          "text": "PDFPage"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.pdfkit/documentation/PDFKit/PDFDocument/page(at:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "pageAtIndex:"
        }
      ],
      "role": "symbol",
      "title": "page(at:)",
      "type": "topic",
      "url": "/documentation/pdfkit/pdfdocument/page(at:)"
    },
    "doc://com.apple.pdfkit/documentation/PDFKit/PDFDocument/pageClass": {
      "abstract": [
        {
          "text": "The class that is allocated and initialized when page objects are created for the document.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "pageClass"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s8AnyClassa",
          "text": "AnyClass"
        }
      ],
      "identifier": "doc://com.apple.pdfkit/documentation/PDFKit/PDFDocument/pageClass",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "pageClass"
        }
      ],
      "role": "symbol",
      "title": "pageClass",
      "type": "topic",
      "url": "/documentation/pdfkit/pdfdocument/pageclass"
    },
    "doc://com.apple.pdfkit/documentation/PDFKit/PDFDocument/pageCount": {
      "abstract": [
        {
          "text": "The number of pages in the document.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "pageCount"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.pdfkit/documentation/PDFKit/PDFDocument/pageCount",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "pageCount"
        }
      ],
      "role": "symbol",
      "title": "pageCount",
      "type": "topic",
      "url": "/documentation/pdfkit/pdfdocument/pagecount"
    },
    "doc://com.apple.pdfkit/documentation/PDFKit/PDFDocument/permissionsStatus": {
      "abstract": [
        {
          "text": "The permissions status of the PDF document.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "permissionsStatus"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@PDFDocumentPermissions",
          "text": "PDFDocumentPermissions"
        }
      ],
      "identifier": "doc://com.apple.pdfkit/documentation/PDFKit/PDFDocument/permissionsStatus",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "permissionsStatus"
        }
      ],
      "role": "symbol",
      "title": "permissionsStatus",
      "type": "topic",
      "url": "/documentation/pdfkit/pdfdocument/permissionsstatus"
    },
    "doc://com.apple.pdfkit/documentation/PDFKit/PDFDocument/removePage(at:)": {
      "abstract": [
        {
          "text": "Removes the page at the specified index point.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "removePage"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "at"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.pdfkit/documentation/PDFKit/PDFDocument/removePage(at:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "removePageAtIndex:"
        }
      ],
      "role": "symbol",
      "title": "removePage(at:)",
      "type": "topic",
      "url": "/documentation/pdfkit/pdfdocument/removepage(at:)"
    },
    "doc://com.apple.pdfkit/documentation/PDFKit/PDFDocument/selection(from:at:to:at:)": {
      "abstract": [
        {
          "text": "Returns the specified selection based on starting and ending points.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "selection"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "from"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)PDFPage",
          "text": "PDFPage"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "at"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@CGPoint",
          "text": "CGPoint"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "to"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)PDFPage",
          "text": "PDFPage"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "at"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@CGPoint",
          "text": "CGPoint"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)PDFSelection",
          "text": "PDFSelection"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.pdfkit/documentation/PDFKit/PDFDocument/selection(from:at:to:at:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "selectionFromPage:atPoint:toPage:atPoint:"
        }
      ],
      "role": "symbol",
      "title": "selection(from:at:to:at:)",
      "type": "topic",
      "url": "/documentation/pdfkit/pdfdocument/selection(from:at:to:at:)"
    },
    "doc://com.apple.pdfkit/documentation/PDFKit/PDFDocument/selection(from:atCharacterIndex:to:atCharacterIndex:)": {
      "abstract": [
        {
          "text": "Returns the specified selection based on starting and ending character indexes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "selection"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "from"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)PDFPage",
          "text": "PDFPage"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "atCharacterIndex"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "to"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)PDFPage",
          "text": "PDFPage"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "atCharacterIndex"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)PDFSelection",
          "text": "PDFSelection"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.pdfkit/documentation/PDFKit/PDFDocument/selection(from:atCharacterIndex:to:atCharacterIndex:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "selectionFromPage:atCharacterIndex:toPage:atCharacterIndex:"
        }
      ],
      "role": "symbol",
      "title": "selection(from:atCharacterIndex:to:atCharacterIndex:)",
      "type": "topic",
      "url": "/documentation/pdfkit/pdfdocument/selection(from:atcharacterindex:to:atcharacterindex:)"
    },
    "doc://com.apple.pdfkit/documentation/PDFKit/PDFDocument/selectionForEntireDocument": {
      "abstract": [
        {
          "text": "Returns a selection representing the textual content of the entire document.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "selectionForEntireDocument"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)PDFSelection",
          "text": "PDFSelection"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.pdfkit/documentation/PDFKit/PDFDocument/selectionForEntireDocument",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "selectionForEntireDocument"
        }
      ],
      "role": "symbol",
      "title": "selectionForEntireDocument",
      "type": "topic",
      "url": "/documentation/pdfkit/pdfdocument/selectionforentiredocument"
    },
    "doc://com.apple.pdfkit/documentation/PDFKit/PDFDocument/string": {
      "abstract": [
        {
          "text": "A string representing the textual content for the entire document.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "string"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.pdfkit/documentation/PDFKit/PDFDocument/string",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "string"
        }
      ],
      "role": "symbol",
      "title": "string",
      "type": "topic",
      "url": "/documentation/pdfkit/pdfdocument/string"
    },
    "doc://com.apple.pdfkit/documentation/PDFKit/PDFDocument/unlock(withPassword:)": {
      "abstract": [
        {
          "text": "Attempts to unlock an encrypted document.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "unlock"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "withPassword"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.pdfkit/documentation/PDFKit/PDFDocument/unlock(withPassword:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "unlockWithPassword:"
        }
      ],
      "role": "symbol",
      "title": "unlock(withPassword:)",
      "type": "topic",
      "url": "/documentation/pdfkit/pdfdocument/unlock(withpassword:)"
    },
    "doc://com.apple.pdfkit/documentation/PDFKit/permission-properties": {
      "abstract": [
        {
          "text": "Properties that specify what functions are allowed for a PDF document.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.pdfkit/documentation/PDFKit/permission-properties",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Permission Properties",
      "type": "topic",
      "url": "/documentation/pdfkit/permission-properties"
    },
    "doc://com.apple.pdfkit/documentation/PDFKit/search-operations": {
      "abstract": [
        {
          "text": "Find and search in PDFs.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.pdfkit/documentation/PDFKit/search-operations",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Search Operations",
      "type": "topic",
      "url": "/documentation/pdfkit/search-operations"
    },
    "doc://com.apple.pdfkit/documentation/PDFKit/write-operations": {
      "abstract": [
        {
          "text": "Operations that let you write document data to different locations.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.pdfkit/documentation/PDFKit/write-operations",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Write Operations",
      "type": "topic",
      "url": "/documentation/pdfkit/write-operations"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Reading-and-Writing-PDFs",
      "generated": true,
      "identifiers": [
        "doc://com.apple.pdfkit/documentation/PDFKit/write-operations"
      ],
      "title": "Reading and Writing PDFs"
    }
  ],
  "topicSections": [
    {
      "anchor": "Accessing-Document-Information",
      "identifiers": [
        "doc://com.apple.pdfkit/documentation/PDFKit/PDFDocument/documentURL",
        "doc://com.apple.pdfkit/documentation/PDFKit/PDFDocument/majorVersion",
        "doc://com.apple.pdfkit/documentation/PDFKit/PDFDocument/minorVersion",
        "doc://com.apple.pdfkit/documentation/PDFKit/PDFDocument/string",
        "doc://com.apple.pdfkit/documentation/PDFKit/PDFDocument/outlineItem(for:)",
        "doc://com.apple.pdfkit/documentation/PDFKit/PDFDocument/outlineRoot",
        "doc://com.apple.pdfkit/documentation/PDFKit/PDFDocument/documentAttributes",
        "doc://com.apple.pdfkit/documentation/PDFKit/PDFDocument/documentRef"
      ],
      "title": "Accessing Document Information"
    },
    {
      "anchor": "Managing-Document-Security",
      "identifiers": [
        "doc://com.apple.pdfkit/documentation/PDFKit/PDFDocument/isEncrypted",
        "doc://com.apple.pdfkit/documentation/PDFKit/PDFDocument/isLocked",
        "doc://com.apple.pdfkit/documentation/PDFKit/PDFDocument/unlock(withPassword:)",
        "doc://com.apple.pdfkit/documentation/PDFKit/PDFDocument/permissionsStatus",
        "doc://com.apple.pdfkit/documentation/PDFKit/permission-properties"
      ],
      "title": "Managing Document Security"
    },
    {
      "anchor": "Working-with-Selections-and-Searches",
      "identifiers": [
        "doc://com.apple.pdfkit/documentation/PDFKit/PDFDocument/selection(from:atCharacterIndex:to:atCharacterIndex:)",
        "doc://com.apple.pdfkit/documentation/PDFKit/PDFDocument/selection(from:at:to:at:)",
        "doc://com.apple.pdfkit/documentation/PDFKit/PDFDocument/selectionForEntireDocument",
        "doc://com.apple.pdfkit/documentation/PDFKit/search-operations"
      ],
      "title": "Working with Selections and Searches"
    },
    {
      "anchor": "Working-with-Pages",
      "identifiers": [
        "doc://com.apple.pdfkit/documentation/PDFKit/PDFDocument/pageCount",
        "doc://com.apple.pdfkit/documentation/PDFKit/PDFDocument/page(at:)",
        "doc://com.apple.pdfkit/documentation/PDFKit/PDFDocument/index(for:)",
        "doc://com.apple.pdfkit/documentation/PDFKit/PDFDocument/insert(_:at:)",
        "doc://com.apple.pdfkit/documentation/PDFKit/PDFDocument/removePage(at:)",
        "doc://com.apple.pdfkit/documentation/PDFKit/PDFDocument/exchangePage(at:withPageAt:)",
        "doc://com.apple.pdfkit/documentation/PDFKit/PDFDocument/pageClass"
      ],
      "title": "Working with Pages"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Accessing-Document-Information",
              "identifiers": [
                "doc://com.apple.pdfkit/documentation/PDFKit/PDFDocument/documentURL",
                "doc://com.apple.pdfkit/documentation/PDFKit/PDFDocument/majorVersion",
                "doc://com.apple.pdfkit/documentation/PDFKit/PDFDocument/minorVersion",
                "doc://com.apple.pdfkit/documentation/PDFKit/PDFDocument/string",
                "doc://com.apple.pdfkit/documentation/PDFKit/PDFDocument/outlineItem(for:)",
                "doc://com.apple.pdfkit/documentation/PDFKit/PDFDocument/outlineRoot",
                "doc://com.apple.pdfkit/documentation/PDFKit/PDFDocument/documentAttributes",
                "doc://com.apple.pdfkit/documentation/PDFKit/PDFDocument/documentRef"
              ],
              "title": "Accessing Document Information"
            },
            {
              "anchor": "Managing-Document-Security",
              "identifiers": [
                "doc://com.apple.pdfkit/documentation/PDFKit/PDFDocument/isEncrypted",
                "doc://com.apple.pdfkit/documentation/PDFKit/PDFDocument/isLocked",
                "doc://com.apple.pdfkit/documentation/PDFKit/PDFDocument/unlock(withPassword:)",
                "doc://com.apple.pdfkit/documentation/PDFKit/PDFDocument/permissionsStatus",
                "doc://com.apple.pdfkit/documentation/PDFKit/permission-properties"
              ],
              "title": "Managing Document Security"
            },
            {
              "anchor": "Working-with-Selections-and-Searches",
              "identifiers": [
                "doc://com.apple.pdfkit/documentation/PDFKit/PDFDocument/selection(from:atCharacterIndex:to:atCharacterIndex:)",
                "doc://com.apple.pdfkit/documentation/PDFKit/PDFDocument/selection(from:at:to:at:)",
                "doc://com.apple.pdfkit/documentation/PDFKit/PDFDocument/selectionForEntireDocument",
                "doc://com.apple.pdfkit/documentation/PDFKit/search-operations"
              ],
              "title": "Working with Selections and Searches"
            },
            {
              "anchor": "Working-with-Pages",
              "identifiers": [
                "doc://com.apple.pdfkit/documentation/PDFKit/PDFDocument/pageCount",
                "doc://com.apple.pdfkit/documentation/PDFKit/PDFDocument/page(at:)",
                "doc://com.apple.pdfkit/documentation/PDFKit/PDFDocument/index(for:)",
                "doc://com.apple.pdfkit/documentation/PDFKit/PDFDocument/insert(_:at:)",
                "doc://com.apple.pdfkit/documentation/PDFKit/PDFDocument/removePage(at:)",
                "doc://com.apple.pdfkit/documentation/PDFKit/PDFDocument/exchangePage(at:withPageAt:)",
                "doc://com.apple.pdfkit/documentation/PDFKit/PDFDocument/pageClass"
              ],
              "title": "Working with Pages"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Reading-and-Writing-PDFs",
              "generated": true,
              "identifiers": [
                "doc://com.apple.pdfkit/documentation/PDFKit/write-operations"
              ],
              "title": "Reading and Writing PDFs"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFDocument~1string/title",
          "value": "string"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFDocument~1string/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "string"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFDocument~1majorVersion/title",
          "value": "majorVersion"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFDocument~1majorVersion/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "majorVersion"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFDocument~1removePage(at:)/title",
          "value": "removePageAtIndex:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFDocument~1removePage(at:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "removePageAtIndex:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFDocument~1selection(from:atCharacterIndex:to:atCharacterIndex:)/title",
          "value": "selectionFromPage:atCharacterIndex:toPage:atCharacterIndex:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFDocument~1selection(from:atCharacterIndex:to:atCharacterIndex:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "selectionFromPage:atCharacterIndex:toPage:atCharacterIndex:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFDocument~1page(at:)/title",
          "value": "pageAtIndex:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFDocument~1page(at:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "pageAtIndex:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFDocument~1exchangePage(at:withPageAt:)/title",
          "value": "exchangePageAtIndex:withPageAtIndex:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFDocument~1exchangePage(at:withPageAt:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "exchangePageAtIndex:withPageAtIndex:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFDocument~1documentAttributes/title",
          "value": "documentAttributes"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFDocument~1documentAttributes/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "documentAttributes"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFDocument~1insert(_:at:)/title",
          "value": "insertPage:atIndex:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFDocument~1insert(_:at:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "insertPage:atIndex:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFDocument~1isLocked/title",
          "value": "isLocked"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFDocument~1isLocked/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "isLocked"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFDocument~1permissionsStatus/title",
          "value": "permissionsStatus"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFDocument~1permissionsStatus/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "permissionsStatus"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFDocument~1index(for:)/title",
          "value": "indexForPage:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFDocument~1index(for:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "indexForPage:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFDocument~1minorVersion/title",
          "value": "minorVersion"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFDocument~1minorVersion/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "minorVersion"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFDocument~1selection(from:at:to:at:)/title",
          "value": "selectionFromPage:atPoint:toPage:atPoint:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFDocument~1selection(from:at:to:at:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "selectionFromPage:atPoint:toPage:atPoint:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFDocument~1documentRef/title",
          "value": "documentRef"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFDocument~1documentRef/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "documentRef"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFDocument~1unlock(withPassword:)/title",
          "value": "unlockWithPassword:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFDocument~1unlock(withPassword:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "unlockWithPassword:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFDocument~1isEncrypted/title",
          "value": "isEncrypted"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFDocument~1isEncrypted/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "isEncrypted"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFDocument~1pageClass/title",
          "value": "pageClass"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFDocument~1pageClass/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "pageClass"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFDocument~1selectionForEntireDocument/title",
          "value": "selectionForEntireDocument"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFDocument~1selectionForEntireDocument/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "selectionForEntireDocument"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFDocument/title",
          "value": "PDFDocument"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFDocument/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PDFDocument"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFDocument/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "PDFDocument"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFDocument~1documentURL/title",
          "value": "documentURL"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFDocument~1documentURL/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "documentURL"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFDocument~1outlineRoot/title",
          "value": "outlineRoot"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFDocument~1outlineRoot/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "outlineRoot"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFDocument~1outlineItem(for:)/title",
          "value": "outlineItemForSelection:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFDocument~1outlineItem(for:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "outlineItemForSelection:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFDocument~1pageCount/title",
          "value": "pageCount"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFDocument~1pageCount/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "pageCount"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/pdfkit/read-operations"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/pdfkit/read-operations"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
