{"identifier":{"interfaceLanguage":"swift","url":"doc://com.apple.pdfkit/documentation/PDFKit/write-operations"},"kind":"article","metadata":{"roleHeading":"API Collection","role":"collectionGroup","modules":[{"name":"PDFKit"}],"title":"Write Operations"},"sections":[],"abstract":[{"type":"text","text":"Operations that let you write document data to different locations."}],"schemaVersion":{"major":0,"minor":3,"patch":0},"hierarchy":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.pdfkit/documentation/PDFKit","doc://com.apple.pdfkit/documentation/PDFKit/PDFDocument"]]},"seeAlsoSections":[{"anchor":"Reading-and-Writing-PDFs","title":"Reading and Writing PDFs","generated":true,"identifiers":["doc://com.apple.pdfkit/documentation/PDFKit/read-operations"]}],"topicSections":[{"anchor":"Writing-Out-the-PDF-Data","title":"Writing Out the PDF Data","identifiers":["doc://com.apple.pdfkit/documentation/PDFKit/PDFDocument/write(toFile:)","doc://com.apple.pdfkit/documentation/PDFKit/PDFDocument/write(toFile:withOptions:)","doc://com.apple.pdfkit/documentation/PDFKit/PDFDocument/write(to:)","doc://com.apple.pdfkit/documentation/PDFKit/PDFDocument/write(to:withOptions:)","doc://com.apple.pdfkit/documentation/PDFKit/data-representations"]},{"anchor":"Printing-Documents-for-macOS","title":"Printing Documents for macOS","identifiers":["doc://com.apple.pdfkit/documentation/PDFKit/PDFDocument/printOperation(for:scalingMode:autoRotate:)","doc://com.apple.pdfkit/documentation/PDFKit/PDFPrintScalingMode"]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["/documentation/pdfkit/write-operations"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["/documentation/pdfkit/write-operations"]}],"references":{"doc://com.apple.pdfkit/documentation/PDFKit/PDFDocument/printOperation(for:scalingMode:autoRotate:)":{"kind":"symbol","url":"/documentation/pdfkit/pdfdocument/printoperation(for:scalingmode:autorotate:)","title":"printOperation(for:scalingMode:autoRotate:)","identifier":"doc://com.apple.pdfkit/documentation/PDFKit/PDFDocument/printOperation(for:scalingMode:autoRotate:)","role":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"printOperationForPrintInfo:scalingMode:autoRotate:"}],"abstract":[{"text":"Returns a print operation suitable for printing the PDF document.","type":"text"}],"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"printOperation"},{"kind":"text","text":"("},{"kind":"externalParam","text":"for"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NSPrintInfo","preciseIdentifier":"c:objc(cs)NSPrintInfo"},{"text":"?, ","kind":"text"},{"text":"scalingMode","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"PDFPrintScalingMode","preciseIdentifier":"c:@E@PDFPrintScalingMode","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"autoRotate","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"text":"NSPrintOperation","preciseIdentifier":"c:objc(cs)NSPrintOperation","kind":"typeIdentifier"},{"kind":"text","text":"?"}]},"doc://com.apple.pdfkit/documentation/PDFKit/PDFPrintScalingMode":{"fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"PDFPrintScalingMode"}],"url":"/documentation/pdfkit/pdfprintscalingmode","navigatorTitle":[{"kind":"identifier","text":"PDFPrintScalingMode"}],"abstract":[{"type":"text","text":"The type of scaling to be used when printing a page (see "},{"identifier":"doc://com.apple.pdfkit/documentation/PDFKit/PDFDocument","type":"reference","isActive":true},{"type":"text","text":")."}],"kind":"symbol","identifier":"doc://com.apple.pdfkit/documentation/PDFKit/PDFPrintScalingMode","role":"symbol","type":"topic","title":"PDFPrintScalingMode"},"doc://com.apple.documentation/documentation/technologies":{"kind":"technologies","url":"/documentation/technologies","role":"overview","identifier":"doc://com.apple.documentation/documentation/technologies","abstract":[{"text":"","type":"text"}],"title":"Technologies","type":"topic"},"doc://com.apple.pdfkit/documentation/PDFKit":{"role":"collection","identifier":"doc://com.apple.pdfkit/documentation/PDFKit","type":"topic","abstract":[{"type":"text","text":"Display and manipulate PDF documents in your apps."}],"kind":"symbol","title":"PDFKit","url":"/documentation/pdfkit"},"doc://com.apple.pdfkit/documentation/PDFKit/PDFDocument/write(to:withOptions:)":{"abstract":[{"text":"Writes the document to the specified URL with the specified options.","type":"text"}],"title":"write(to:withOptions:)","navigatorTitle":[{"text":"writeToURL:withOptions:","kind":"identifier"}],"identifier":"doc://com.apple.pdfkit/documentation/PDFKit/PDFDocument/write(to:withOptions:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"write","kind":"identifier"},{"text":"(","kind":"text"},{"text":"to","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"URL","kind":"typeIdentifier","preciseIdentifier":"s:10Foundation3URLV"},{"text":", ","kind":"text"},{"text":"withOptions","kind":"externalParam"},{"text":": [","kind":"text"},{"text":"PDFDocumentWriteOption","kind":"typeIdentifier","preciseIdentifier":"c:@T@PDFDocumentWriteOption"},{"text":" : ","kind":"text"},{"text":"Any","kind":"keyword"},{"text":"]?) -> ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}],"url":"/documentation/pdfkit/pdfdocument/write(to:withoptions:)","role":"symbol","kind":"symbol","type":"topic"},"doc://com.apple.pdfkit/documentation/PDFKit/PDFDocument/write(to:)":{"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"writeToURL:"}],"identifier":"doc://com.apple.pdfkit/documentation/PDFKit/PDFDocument/write(to:)","type":"topic","abstract":[{"text":"Writes the document to a location specified by the passed-in URL.","type":"text"}],"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"write"},{"kind":"text","text":"("},{"kind":"externalParam","text":"to"},{"kind":"text","text":": "},{"preciseIdentifier":"s:10Foundation3URLV","kind":"typeIdentifier","text":"URL"},{"kind":"text","text":") -> "},{"preciseIdentifier":"s:Sb","kind":"typeIdentifier","text":"Bool"}],"kind":"symbol","title":"write(to:)","url":"/documentation/pdfkit/pdfdocument/write(to:)"},"doc://com.apple.pdfkit/documentation/PDFKit/PDFDocument/write(toFile:withOptions:)":{"title":"write(toFile:withOptions:)","navigatorTitle":[{"text":"writeToFile:withOptions:","kind":"identifier"}],"url":"/documentation/pdfkit/pdfdocument/write(tofile:withoptions:)","kind":"symbol","type":"topic","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"write","kind":"identifier"},{"text":"(","kind":"text"},{"text":"toFile","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"withOptions","kind":"externalParam"},{"text":": [","kind":"text"},{"preciseIdentifier":"c:@T@PDFDocumentWriteOption","text":"PDFDocumentWriteOption","kind":"typeIdentifier"},{"text":" : ","kind":"text"},{"text":"Any","kind":"keyword"},{"text":"]?) -> ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"}],"role":"symbol","abstract":[{"type":"text","text":"Writes the document to a file at the specified path with the specified options."}],"identifier":"doc://com.apple.pdfkit/documentation/PDFKit/PDFDocument/write(toFile:withOptions:)"},"doc://com.apple.pdfkit/documentation/PDFKit/PDFDocument":{"kind":"symbol","url":"/documentation/pdfkit/pdfdocument","navigatorTitle":[{"kind":"identifier","text":"PDFDocument"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"PDFDocument"}],"role":"symbol","identifier":"doc://com.apple.pdfkit/documentation/PDFKit/PDFDocument","abstract":[{"type":"text","text":"An object that represents PDF data or a PDF file and defines methods for writing, searching, and selecting PDF data."}],"title":"PDFDocument","type":"topic"},"doc://com.apple.pdfkit/documentation/PDFKit/data-representations":{"title":"Data Representations","role":"collectionGroup","abstract":[{"text":"Operations to represent PDF documents as data objects.","type":"text"}],"type":"topic","url":"/documentation/pdfkit/data-representations","identifier":"doc://com.apple.pdfkit/documentation/PDFKit/data-representations","kind":"article"},"doc://com.apple.pdfkit/documentation/PDFKit/PDFDocument/write(toFile:)":{"abstract":[{"text":"Writes the document to a file at the specified path.","type":"text"}],"title":"write(toFile:)","navigatorTitle":[{"text":"writeToFile:","kind":"identifier"}],"identifier":"doc://com.apple.pdfkit/documentation/PDFKit/PDFDocument/write(toFile:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"write","kind":"identifier"},{"text":"(","kind":"text"},{"text":"toFile","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"}],"url":"/documentation/pdfkit/pdfdocument/write(tofile:)","role":"symbol","kind":"symbol","type":"topic"},"doc://com.apple.pdfkit/documentation/PDFKit/read-operations":{"role":"collectionGroup","type":"topic","abstract":[{"text":"Operations that let you access documents and pages, manage document security, and work with searching and selections.","type":"text"}],"url":"/documentation/pdfkit/read-operations","kind":"article","title":"Read Operations","identifier":"doc://com.apple.pdfkit/documentation/PDFKit/read-operations"}},"variantOverrides":[{"patch":[{"op":"replace","path":"/identifier/interfaceLanguage","value":"occ"},{"op":"replace","path":"/topicSections","value":[{"identifiers":["doc://com.apple.pdfkit/documentation/PDFKit/PDFDocument/write(toFile:)","doc://com.apple.pdfkit/documentation/PDFKit/PDFDocument/write(toFile:withOptions:)","doc://com.apple.pdfkit/documentation/PDFKit/PDFDocument/write(to:)","doc://com.apple.pdfkit/documentation/PDFKit/PDFDocument/write(to:withOptions:)","doc://com.apple.pdfkit/documentation/PDFKit/data-representations"],"title":"Writing Out the PDF Data","anchor":"Writing-Out-the-PDF-Data"},{"identifiers":["doc://com.apple.pdfkit/documentation/PDFKit/PDFDocument/printOperation(for:scalingMode:autoRotate:)","doc://com.apple.pdfkit/documentation/PDFKit/PDFPrintScalingMode"],"title":"Printing Documents for macOS","anchor":"Printing-Documents-for-macOS"}]},{"path":"/seeAlsoSections","op":"replace","value":[{"generated":true,"identifiers":["doc://com.apple.pdfkit/documentation/PDFKit/read-operations"],"anchor":"Reading-and-Writing-PDFs","title":"Reading and Writing PDFs"}]},{"path":"/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFDocument~1printOperation(for:scalingMode:autoRotate:)/title","op":"replace","value":"printOperationForPrintInfo:scalingMode:autoRotate:"},{"path":"/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFDocument~1printOperation(for:scalingMode:autoRotate:)/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"printOperationForPrintInfo:scalingMode:autoRotate:"}]},{"path":"/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFPrintScalingMode/title","op":"replace","value":"PDFPrintScalingMode"},{"path":"/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFPrintScalingMode/fragments","op":"replace","value":[{"text":"PDFPrintScalingMode","kind":"identifier"}]},{"path":"/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFPrintScalingMode/navigatorTitle","op":"replace","value":[{"text":"PDFPrintScalingMode","kind":"identifier"}]},{"path":"/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFDocument~1write(to:withOptions:)/title","op":"replace","value":"writeToURL:withOptions:"},{"path":"/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFDocument~1write(to:withOptions:)/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"writeToURL:withOptions:"}]},{"path":"/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFDocument~1write(to:)/title","op":"replace","value":"writeToURL:"},{"path":"/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFDocument~1write(to:)/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"text":"writeToURL:","kind":"identifier"}]},{"path":"/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFDocument~1write(toFile:withOptions:)/title","op":"replace","value":"writeToFile:withOptions:"},{"path":"/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFDocument~1write(toFile:withOptions:)/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"text":"writeToFile:withOptions:","kind":"identifier"}]},{"path":"/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFDocument/title","op":"replace","value":"PDFDocument"},{"path":"/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFDocument/fragments","op":"replace","value":[{"text":"PDFDocument","kind":"identifier"}]},{"path":"/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFDocument/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"PDFDocument"}]},{"path":"/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFDocument~1write(toFile:)/title","op":"replace","value":"writeToFile:"},{"path":"/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFDocument~1write(toFile:)/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"writeToFile:"}]}],"traits":[{"interfaceLanguage":"occ"}]}],"diffAvailability":{"major":{"change":"modified","platform":"Xcode","versions":["16.0","16.3 beta 2"]}},"legalNotices":{"copyright":"Copyright &copy; 2025 Apple Inc. All rights reserved.","termsOfUse":"https://www.apple.com/legal/internet-services/terms/site.html","privacyPolicy":"https://www.apple.com/privacy/privacy-policy"}}