{
  "abstract": [
    {
      "text": "Zoom operations for a PDF View.",
      "type": "text"
    }
  ],
  "diffAvailability": {
    "major": {
      "change": "modified",
      "platform": "Xcode",
      "versions": [
        "16.0",
        "16.3 beta 2"
      ]
    }
  },
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.pdfkit/documentation/PDFKit",
        "doc://com.apple.pdfkit/documentation/PDFKit/PDFView",
        "doc://com.apple.pdfkit/documentation/PDFKit/configurations"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.pdfkit/documentation/PDFKit/zoom-operations"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "PDFKit"
      }
    ],
    "role": "collectionGroup",
    "roleHeading": "API Collection",
    "title": "Zoom Operations"
  },
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.pdfkit/documentation/PDFKit": {
      "abstract": [
        {
          "text": "Display and manipulate PDF documents in your apps.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.pdfkit/documentation/PDFKit",
      "kind": "symbol",
      "role": "collection",
      "title": "PDFKit",
      "type": "topic",
      "url": "/documentation/pdfkit"
    },
    "doc://com.apple.pdfkit/documentation/PDFKit/PDFView": {
      "abstract": [
        {
          "text": "An object that encapsulates the functionality of PDF Kit into a single widget that you can add to your application using Interface Builder.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "PDFView"
        }
      ],
      "identifier": "doc://com.apple.pdfkit/documentation/PDFKit/PDFView",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PDFView"
        }
      ],
      "role": "symbol",
      "title": "PDFView",
      "type": "topic",
      "url": "/documentation/pdfkit/pdfview"
    },
    "doc://com.apple.pdfkit/documentation/PDFKit/PDFView/autoScales": {
      "abstract": [
        {
          "text": "A Boolean value indicating whether autoscaling is set.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "autoScales"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.pdfkit/documentation/PDFKit/PDFView/autoScales",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "autoScales"
        }
      ],
      "role": "symbol",
      "title": "autoScales",
      "type": "topic",
      "url": "/documentation/pdfkit/pdfview/autoscales"
    },
    "doc://com.apple.pdfkit/documentation/PDFKit/PDFView/canZoomIn": {
      "abstract": [
        {
          "text": "Returns a Boolean value indicating whether the user can magnify the view and zoom in.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "canZoomIn"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.pdfkit/documentation/PDFKit/PDFView/canZoomIn",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "canZoomIn"
        }
      ],
      "role": "symbol",
      "title": "canZoomIn",
      "type": "topic",
      "url": "/documentation/pdfkit/pdfview/canzoomin"
    },
    "doc://com.apple.pdfkit/documentation/PDFKit/PDFView/canZoomOut": {
      "abstract": [
        {
          "text": "Returns a Boolean value indicating whether the user can view an expanded area and zoom out.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "canZoomOut"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.pdfkit/documentation/PDFKit/PDFView/canZoomOut",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "canZoomOut"
        }
      ],
      "role": "symbol",
      "title": "canZoomOut",
      "type": "topic",
      "url": "/documentation/pdfkit/pdfview/canzoomout"
    },
    "doc://com.apple.pdfkit/documentation/PDFKit/PDFView/maxScaleFactor": {
      "abstract": [
        {
          "text": "The maximum scaling factor for the PDF document.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "maxScaleFactor"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:14CoreFoundation7CGFloatV",
          "text": "CGFloat"
        }
      ],
      "identifier": "doc://com.apple.pdfkit/documentation/PDFKit/PDFView/maxScaleFactor",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "maxScaleFactor"
        }
      ],
      "role": "symbol",
      "title": "maxScaleFactor",
      "type": "topic",
      "url": "/documentation/pdfkit/pdfview/maxscalefactor"
    },
    "doc://com.apple.pdfkit/documentation/PDFKit/PDFView/minScaleFactor": {
      "abstract": [
        {
          "text": "The minimum scaling factor for the PDF document.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "minScaleFactor"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:14CoreFoundation7CGFloatV",
          "text": "CGFloat"
        }
      ],
      "identifier": "doc://com.apple.pdfkit/documentation/PDFKit/PDFView/minScaleFactor",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "minScaleFactor"
        }
      ],
      "role": "symbol",
      "title": "minScaleFactor",
      "type": "topic",
      "url": "/documentation/pdfkit/pdfview/minscalefactor"
    },
    "doc://com.apple.pdfkit/documentation/PDFKit/PDFView/rowSize(for:)": {
      "abstract": [
        {
          "text": "Returns the size needed to display a row of the current document page.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "rowSize"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "for"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)PDFPage",
          "text": "PDFPage"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@CGSize",
          "text": "CGSize"
        }
      ],
      "identifier": "doc://com.apple.pdfkit/documentation/PDFKit/PDFView/rowSize(for:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "rowSizeForPage:"
        }
      ],
      "role": "symbol",
      "title": "rowSize(for:)",
      "type": "topic",
      "url": "/documentation/pdfkit/pdfview/rowsize(for:)"
    },
    "doc://com.apple.pdfkit/documentation/PDFKit/PDFView/scaleFactor": {
      "abstract": [
        {
          "text": "The current scale factor for the view.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "scaleFactor"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:14CoreFoundation7CGFloatV",
          "text": "CGFloat"
        }
      ],
      "identifier": "doc://com.apple.pdfkit/documentation/PDFKit/PDFView/scaleFactor",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "scaleFactor"
        }
      ],
      "role": "symbol",
      "title": "scaleFactor",
      "type": "topic",
      "url": "/documentation/pdfkit/pdfview/scalefactor"
    },
    "doc://com.apple.pdfkit/documentation/PDFKit/PDFView/scaleFactorForSizeToFit": {
      "abstract": [
        {
          "text": "The “size to fit” scale factor that ",
          "type": "text"
        },
        {
          "code": "autoScales",
          "type": "codeVoice"
        },
        {
          "text": " would use for scaling the current document and layout.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "scaleFactorForSizeToFit"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:14CoreFoundation7CGFloatV",
          "text": "CGFloat"
        }
      ],
      "identifier": "doc://com.apple.pdfkit/documentation/PDFKit/PDFView/scaleFactorForSizeToFit",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "scaleFactorForSizeToFit"
        }
      ],
      "role": "symbol",
      "title": "scaleFactorForSizeToFit",
      "type": "topic",
      "url": "/documentation/pdfkit/pdfview/scalefactorforsizetofit"
    },
    "doc://com.apple.pdfkit/documentation/PDFKit/PDFView/zoomIn(_:)": {
      "abstract": [
        {
          "text": "Zooms in by increasing the scaling factor.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "zoomIn"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "keyword",
          "text": "Any"
        },
        {
          "kind": "text",
          "text": "?)"
        }
      ],
      "identifier": "doc://com.apple.pdfkit/documentation/PDFKit/PDFView/zoomIn(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "zoomIn:"
        }
      ],
      "role": "symbol",
      "title": "zoomIn(_:)",
      "type": "topic",
      "url": "/documentation/pdfkit/pdfview/zoomin(_:)"
    },
    "doc://com.apple.pdfkit/documentation/PDFKit/PDFView/zoomOut(_:)": {
      "abstract": [
        {
          "text": "Zooms out by decreasing the scaling factor.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "zoomOut"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "keyword",
          "text": "Any"
        },
        {
          "kind": "text",
          "text": "?)"
        }
      ],
      "identifier": "doc://com.apple.pdfkit/documentation/PDFKit/PDFView/zoomOut(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "zoomOut:"
        }
      ],
      "role": "symbol",
      "title": "zoomOut(_:)",
      "type": "topic",
      "url": "/documentation/pdfkit/pdfview/zoomout(_:)"
    },
    "doc://com.apple.pdfkit/documentation/PDFKit/configurations": {
      "abstract": [
        {
          "text": "Define display modes, scaling, rendering, printing and graphics properties.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.pdfkit/documentation/PDFKit/configurations",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Configurations",
      "type": "topic",
      "url": "/documentation/pdfkit/configurations"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Scaling-the-View",
      "generated": true,
      "identifiers": [
        "doc://com.apple.pdfkit/documentation/PDFKit/PDFView/scaleFactor",
        "doc://com.apple.pdfkit/documentation/PDFKit/PDFView/scaleFactorForSizeToFit",
        "doc://com.apple.pdfkit/documentation/PDFKit/PDFView/maxScaleFactor",
        "doc://com.apple.pdfkit/documentation/PDFKit/PDFView/minScaleFactor",
        "doc://com.apple.pdfkit/documentation/PDFKit/PDFView/autoScales",
        "doc://com.apple.pdfkit/documentation/PDFKit/PDFView/rowSize(for:)"
      ],
      "title": "Scaling the View"
    }
  ],
  "topicSections": [
    {
      "anchor": "Zooming-in-a-PDF-View",
      "identifiers": [
        "doc://com.apple.pdfkit/documentation/PDFKit/PDFView/zoomIn(_:)",
        "doc://com.apple.pdfkit/documentation/PDFKit/PDFView/canZoomIn",
        "doc://com.apple.pdfkit/documentation/PDFKit/PDFView/zoomOut(_:)",
        "doc://com.apple.pdfkit/documentation/PDFKit/PDFView/canZoomOut"
      ],
      "title": "Zooming in a PDF View"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Zooming-in-a-PDF-View",
              "identifiers": [
                "doc://com.apple.pdfkit/documentation/PDFKit/PDFView/zoomIn(_:)",
                "doc://com.apple.pdfkit/documentation/PDFKit/PDFView/canZoomIn",
                "doc://com.apple.pdfkit/documentation/PDFKit/PDFView/zoomOut(_:)",
                "doc://com.apple.pdfkit/documentation/PDFKit/PDFView/canZoomOut"
              ],
              "title": "Zooming in a PDF View"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Scaling-the-View",
              "generated": true,
              "identifiers": [
                "doc://com.apple.pdfkit/documentation/PDFKit/PDFView/scaleFactor",
                "doc://com.apple.pdfkit/documentation/PDFKit/PDFView/scaleFactorForSizeToFit",
                "doc://com.apple.pdfkit/documentation/PDFKit/PDFView/maxScaleFactor",
                "doc://com.apple.pdfkit/documentation/PDFKit/PDFView/minScaleFactor",
                "doc://com.apple.pdfkit/documentation/PDFKit/PDFView/autoScales",
                "doc://com.apple.pdfkit/documentation/PDFKit/PDFView/rowSize(for:)"
              ],
              "title": "Scaling the View"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFView~1canZoomOut/title",
          "value": "canZoomOut"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFView~1canZoomOut/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "canZoomOut"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFView~1scaleFactor/title",
          "value": "scaleFactor"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFView~1scaleFactor/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "scaleFactor"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFView~1canZoomIn/title",
          "value": "canZoomIn"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFView~1canZoomIn/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "canZoomIn"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFView~1rowSize(for:)/title",
          "value": "rowSizeForPage:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFView~1rowSize(for:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "rowSizeForPage:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFView~1zoomOut(_:)/title",
          "value": "zoomOut:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFView~1zoomOut(_:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "zoomOut:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFView/title",
          "value": "PDFView"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFView/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PDFView"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFView/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "PDFView"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFView~1scaleFactorForSizeToFit/title",
          "value": "scaleFactorForSizeToFit"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFView~1scaleFactorForSizeToFit/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "scaleFactorForSizeToFit"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFView~1minScaleFactor/title",
          "value": "minScaleFactor"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFView~1minScaleFactor/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "minScaleFactor"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFView~1maxScaleFactor/title",
          "value": "maxScaleFactor"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFView~1maxScaleFactor/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "maxScaleFactor"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFView~1autoScales/title",
          "value": "autoScales"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFView~1autoScales/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "autoScales"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFView~1zoomIn(_:)/title",
          "value": "zoomIn:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFView~1zoomIn(_:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "zoomIn:"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/pdfkit/zoom-operations"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/pdfkit/zoom-operations"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
