{
  "abstract": [
    {
      "text": "The log level at which the entry was generated.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.oslog/documentation/OSLog",
        "doc://com.apple.oslog/documentation/OSLog/OSLogEntryLog"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.oslog/documentation/OSLog/OSLogEntryLog/Level-swift.enum"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "extendedModule": "OSLog",
    "externalID": "c:@E@OSLogEntryLogLevel",
    "fragments": [
      {
        "kind": "keyword",
        "text": "enum"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "Level"
      }
    ],
    "modules": [
      {
        "name": "OSLog"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "Level"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "15.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "15.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "15.0",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.15",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "15.0",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "8.0",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Enumeration",
    "symbolKind": "enum",
    "title": "OSLogEntryLog.Level"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "enum"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "Level"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.oslog/documentation/OSLog": {
      "abstract": [
        {
          "text": "A unified logging system for the reading of historical data.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.oslog/documentation/OSLog",
      "kind": "symbol",
      "role": "collection",
      "title": "OSLog",
      "type": "topic",
      "url": "/documentation/oslog"
    },
    "doc://com.apple.oslog/documentation/OSLog/OSLogEntryLog": {
      "abstract": [
        {
          "text": "A log entry.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "OSLogEntryLog"
        }
      ],
      "identifier": "doc://com.apple.oslog/documentation/OSLog/OSLogEntryLog",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "OSLogEntryLog"
        }
      ],
      "role": "symbol",
      "title": "OSLogEntryLog",
      "type": "topic",
      "url": "/documentation/oslog/oslogentrylog"
    },
    "doc://com.apple.oslog/documentation/OSLog/OSLogEntryLog/Level-swift.enum": {
      "abstract": [
        {
          "text": "The log level at which the entry was generated.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Level"
        }
      ],
      "identifier": "doc://com.apple.oslog/documentation/OSLog/OSLogEntryLog/Level-swift.enum",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "Level"
        }
      ],
      "role": "symbol",
      "title": "OSLogEntryLog.Level",
      "type": "topic",
      "url": "/documentation/oslog/oslogentrylog/level-swift.enum"
    },
    "doc://com.apple.oslog/documentation/OSLog/OSLogEntryLog/Level-swift.enum/debug": {
      "abstract": [
        {
          "text": "A log level that captures diagnostic information.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "debug"
        }
      ],
      "identifier": "doc://com.apple.oslog/documentation/OSLog/OSLogEntryLog/Level-swift.enum/debug",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "OSLogEntryLogLevelDebug"
        }
      ],
      "role": "symbol",
      "title": "OSLogEntryLog.Level.debug",
      "type": "topic",
      "url": "/documentation/oslog/oslogentrylog/level-swift.enum/debug"
    },
    "doc://com.apple.oslog/documentation/OSLog/OSLogEntryLog/Level-swift.enum/error": {
      "abstract": [
        {
          "text": "The log level that captures errors.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "error"
        }
      ],
      "identifier": "doc://com.apple.oslog/documentation/OSLog/OSLogEntryLog/Level-swift.enum/error",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "OSLogEntryLogLevelError"
        }
      ],
      "role": "symbol",
      "title": "OSLogEntryLog.Level.error",
      "type": "topic",
      "url": "/documentation/oslog/oslogentrylog/level-swift.enum/error"
    },
    "doc://com.apple.oslog/documentation/OSLog/OSLogEntryLog/Level-swift.enum/fault": {
      "abstract": [
        {
          "text": "The log level that captures fault information.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "fault"
        }
      ],
      "identifier": "doc://com.apple.oslog/documentation/OSLog/OSLogEntryLog/Level-swift.enum/fault",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "OSLogEntryLogLevelFault"
        }
      ],
      "role": "symbol",
      "title": "OSLogEntryLog.Level.fault",
      "type": "topic",
      "url": "/documentation/oslog/oslogentrylog/level-swift.enum/fault"
    },
    "doc://com.apple.oslog/documentation/OSLog/OSLogEntryLog/Level-swift.enum/info": {
      "abstract": [
        {
          "text": "The log level that captures additional information.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "info"
        }
      ],
      "identifier": "doc://com.apple.oslog/documentation/OSLog/OSLogEntryLog/Level-swift.enum/info",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "OSLogEntryLogLevelInfo"
        }
      ],
      "role": "symbol",
      "title": "OSLogEntryLog.Level.info",
      "type": "topic",
      "url": "/documentation/oslog/oslogentrylog/level-swift.enum/info"
    },
    "doc://com.apple.oslog/documentation/OSLog/OSLogEntryLog/Level-swift.enum/init(rawValue:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "?("
        },
        {
          "kind": "externalParam",
          "text": "rawValue"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.oslog/documentation/OSLog/OSLogEntryLog/Level-swift.enum/init(rawValue:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "init(rawValue:)",
      "type": "topic",
      "url": "/documentation/oslog/oslogentrylog/level-swift.enum/init(rawvalue:)"
    },
    "doc://com.apple.oslog/documentation/OSLog/OSLogEntryLog/Level-swift.enum/notice": {
      "abstract": [
        {
          "text": "The log level that captures notifications.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "notice"
        }
      ],
      "identifier": "doc://com.apple.oslog/documentation/OSLog/OSLogEntryLog/Level-swift.enum/notice",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "OSLogEntryLogLevelNotice"
        }
      ],
      "role": "symbol",
      "title": "OSLogEntryLog.Level.notice",
      "type": "topic",
      "url": "/documentation/oslog/oslogentrylog/level-swift.enum/notice"
    },
    "doc://com.apple.oslog/documentation/OSLog/OSLogEntryLog/Level-swift.enum/undefined": {
      "abstract": [
        {
          "text": "The log level was never specified.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "undefined"
        }
      ],
      "identifier": "doc://com.apple.oslog/documentation/OSLog/OSLogEntryLog/Level-swift.enum/undefined",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "OSLogEntryLogLevelUndefined"
        }
      ],
      "role": "symbol",
      "title": "OSLogEntryLog.Level.undefined",
      "type": "topic",
      "url": "/documentation/oslog/oslogentrylog/level-swift.enum/undefined"
    },
    "doc://com.apple.oslog/documentation/OSLog/OSLogEntryLog/level-swift.property": {
      "abstract": [
        {
          "text": "The log level of the entry.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "level"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)OSLogEntryLog",
          "text": "OSLogEntryLog"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@OSLogEntryLogLevel",
          "text": "Level"
        }
      ],
      "identifier": "doc://com.apple.oslog/documentation/OSLog/OSLogEntryLog/level-swift.property",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "level"
        }
      ],
      "role": "symbol",
      "title": "level",
      "type": "topic",
      "url": "/documentation/oslog/oslogentrylog/level-swift.property"
    },
    "doc://com.externally.resolved.symbol/s:SH": {
      "abstract": [
        {
          "text": "A type that can be hashed into a `Hasher` to produce an integer hash value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Hashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SQ",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SH",
      "kind": "symbol",
      "role": "symbol",
      "title": "Hashable",
      "type": "topic",
      "url": "/documentation/Swift/Hashable"
    },
    "doc://com.externally.resolved.symbol/s:SQ": {
      "abstract": [
        {
          "text": "A type that can be compared for value equality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SQ",
      "kind": "symbol",
      "role": "symbol",
      "title": "Equatable",
      "type": "topic",
      "url": "/documentation/Swift/Equatable"
    },
    "doc://com.externally.resolved.symbol/s:SY": {
      "abstract": [
        {
          "text": "A type that can be converted to and from an associated raw value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "RawRepresentable"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SY8RawValueQa",
          "text": "RawValue"
        },
        {
          "kind": "text",
          "text": ">"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SY",
      "kind": "symbol",
      "role": "symbol",
      "title": "RawRepresentable",
      "type": "topic",
      "url": "/documentation/Swift/RawRepresentable"
    },
    "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BitwiseCopyable"
        },
        {
          "kind": "text",
          "text": " : ~Escapable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "BitwiseCopyable",
      "type": "topic",
      "url": "/documentation/Swift/BitwiseCopyable"
    },
    "doc://com.externally.resolved.symbol/s:s8SendableP": {
      "abstract": [
        {
          "text": "A thread-safe type whose values can be shared across arbitrary concurrent contexts without introducing a risk of data races.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Sendable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s8SendableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "Sendable",
      "type": "topic",
      "url": "/documentation/Swift/Sendable"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
        "doc://com.externally.resolved.symbol/s:SQ",
        "doc://com.externally.resolved.symbol/s:SH",
        "doc://com.externally.resolved.symbol/s:SY",
        "doc://com.externally.resolved.symbol/s:s8SendableP"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Accessing-Log-Levels",
      "generated": true,
      "identifiers": [
        "doc://com.apple.oslog/documentation/OSLog/OSLogEntryLog/level-swift.property"
      ],
      "title": "Accessing Log Levels"
    }
  ],
  "topicSections": [
    {
      "anchor": "Log-Levels",
      "identifiers": [
        "doc://com.apple.oslog/documentation/OSLog/OSLogEntryLog/Level-swift.enum/undefined",
        "doc://com.apple.oslog/documentation/OSLog/OSLogEntryLog/Level-swift.enum/debug",
        "doc://com.apple.oslog/documentation/OSLog/OSLogEntryLog/Level-swift.enum/info",
        "doc://com.apple.oslog/documentation/OSLog/OSLogEntryLog/Level-swift.enum/notice",
        "doc://com.apple.oslog/documentation/OSLog/OSLogEntryLog/Level-swift.enum/error",
        "doc://com.apple.oslog/documentation/OSLog/OSLogEntryLog/Level-swift.enum/fault"
      ],
      "title": "Log Levels"
    },
    {
      "anchor": "Initializers",
      "generated": true,
      "identifiers": [
        "doc://com.apple.oslog/documentation/OSLog/OSLogEntryLog/Level-swift.enum/init(rawValue:)"
      ],
      "title": "Initializers"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "15.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "15.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "15.0",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.15",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "15.0",
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "8.0",
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "OSLogEntryLogLevel"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "enum"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "OSLogEntryLogLevel"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "OSLogEntryLogLevel"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.oslog/documentation/OSLog"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Log-Levels",
              "identifiers": [
                "doc://com.apple.oslog/documentation/OSLog/OSLogEntryLog/Level-swift.enum/undefined",
                "doc://com.apple.oslog/documentation/OSLog/OSLogEntryLog/Level-swift.enum/debug",
                "doc://com.apple.oslog/documentation/OSLog/OSLogEntryLog/Level-swift.enum/info",
                "doc://com.apple.oslog/documentation/OSLog/OSLogEntryLog/Level-swift.enum/notice",
                "doc://com.apple.oslog/documentation/OSLog/OSLogEntryLog/Level-swift.enum/error",
                "doc://com.apple.oslog/documentation/OSLog/OSLogEntryLog/Level-swift.enum/fault"
              ],
              "title": "Log Levels"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Accessing-Log-Levels",
              "generated": true,
              "identifiers": [
                "doc://com.apple.oslog/documentation/OSLog/OSLogEntryLog/level-swift.property"
              ],
              "title": "Accessing Log Levels"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "enum"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "OSLogEntryLogLevel"
                  },
                  {
                    "kind": "text",
                    "text": " : "
                  },
                  {
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@NSInteger",
                    "text": "NSInteger"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.oslog~1documentation~1OSLog~1OSLogEntryLog~1Level-swift.enum~1debug/title",
          "value": "OSLogEntryLogLevelDebug"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.oslog~1documentation~1OSLog~1OSLogEntryLog~1Level-swift.enum~1debug/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "OSLogEntryLogLevelDebug"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.oslog~1documentation~1OSLog~1OSLogEntryLog~1Level-swift.enum~1fault/title",
          "value": "OSLogEntryLogLevelFault"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.oslog~1documentation~1OSLog~1OSLogEntryLog~1Level-swift.enum~1fault/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "OSLogEntryLogLevelFault"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.oslog~1documentation~1OSLog~1OSLogEntryLog~1level-swift.property/title",
          "value": "level"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.oslog~1documentation~1OSLog~1OSLogEntryLog~1level-swift.property/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "level"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.oslog~1documentation~1OSLog~1OSLogEntryLog~1Level-swift.enum~1undefined/title",
          "value": "OSLogEntryLogLevelUndefined"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.oslog~1documentation~1OSLog~1OSLogEntryLog~1Level-swift.enum~1undefined/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "OSLogEntryLogLevelUndefined"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.oslog~1documentation~1OSLog~1OSLogEntryLog~1Level-swift.enum~1info/title",
          "value": "OSLogEntryLogLevelInfo"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.oslog~1documentation~1OSLog~1OSLogEntryLog~1Level-swift.enum~1info/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "OSLogEntryLogLevelInfo"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.oslog~1documentation~1OSLog~1OSLogEntryLog/title",
          "value": "OSLogEntryLog"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.oslog~1documentation~1OSLog~1OSLogEntryLog/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "OSLogEntryLog"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.oslog~1documentation~1OSLog~1OSLogEntryLog/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "OSLogEntryLog"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.oslog~1documentation~1OSLog~1OSLogEntryLog~1Level-swift.enum~1error/title",
          "value": "OSLogEntryLogLevelError"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.oslog~1documentation~1OSLog~1OSLogEntryLog~1Level-swift.enum~1error/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "OSLogEntryLogLevelError"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.oslog~1documentation~1OSLog~1OSLogEntryLog~1Level-swift.enum~1notice/title",
          "value": "OSLogEntryLogLevelNotice"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.oslog~1documentation~1OSLog~1OSLogEntryLog~1Level-swift.enum~1notice/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "OSLogEntryLogLevelNotice"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.oslog~1documentation~1OSLog~1OSLogEntryLog~1Level-swift.enum/title",
          "value": "OSLogEntryLogLevel"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.oslog~1documentation~1OSLog~1OSLogEntryLog~1Level-swift.enum/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "OSLogEntryLogLevel"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.oslog~1documentation~1OSLog~1OSLogEntryLog~1Level-swift.enum/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "OSLogEntryLogLevel"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/oslog/oslogentrylog/level-swift.enum"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/oslog/oslogentrylog/level-swift.enum"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
