{
  "abstract": [
    {
      "text": "The total time spent tracking the current location at the best accuracy.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.metrickit/documentation/MetricKit",
        "doc://com.apple.metrickit/documentation/MetricKit/MXLocationActivityMetric"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.metrickit/documentation/MetricKit/MXLocationActivityMetric/cumulativeBestAccuracyTime"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(cs)MXLocationActivityMetric(py)cumulativeBestAccuracyTime",
    "fragments": [
      {
        "kind": "keyword",
        "text": "var"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "cumulativeBestAccuracyTime"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "s:10Foundation11MeasurementV",
        "text": "Measurement"
      },
      {
        "kind": "text",
        "text": "<"
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:objc(cs)NSUnitDuration",
        "text": "UnitDuration"
      },
      {
        "kind": "text",
        "text": ">"
      }
    ],
    "modules": [
      {
        "name": "MetricKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "cumulativeBestAccuracyTime"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.1",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Instance Property",
    "symbolKind": "property",
    "title": "cumulativeBestAccuracyTime"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "var"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "cumulativeBestAccuracyTime"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:10Foundation11MeasurementV",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:10Foundation11MeasurementV",
              "text": "Measurement"
            },
            {
              "kind": "text",
              "text": "<"
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSUnitDuration",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)NSUnitDuration",
              "text": "UnitDuration"
            },
            {
              "kind": "text",
              "text": "> { "
            },
            {
              "kind": "keyword",
              "text": "get"
            },
            {
              "kind": "text",
              "text": " }"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.metrickit/documentation/MetricKit": {
      "abstract": [
        {
          "text": "Aggregate and analyze per-device reports on exception and crash diagnostics and on power and performance metrics.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.metrickit/documentation/MetricKit",
      "kind": "symbol",
      "role": "collection",
      "title": "MetricKit",
      "type": "topic",
      "url": "/documentation/metrickit"
    },
    "doc://com.apple.metrickit/documentation/MetricKit/MXLocationActivityMetric": {
      "abstract": [
        {
          "text": "An object representing metrics about the use of location-tracking features of a device.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MXLocationActivityMetric"
        }
      ],
      "identifier": "doc://com.apple.metrickit/documentation/MetricKit/MXLocationActivityMetric",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MXLocationActivityMetric"
        }
      ],
      "role": "symbol",
      "title": "MXLocationActivityMetric",
      "type": "topic",
      "url": "/documentation/metrickit/mxlocationactivitymetric"
    },
    "doc://com.apple.metrickit/documentation/MetricKit/MXLocationActivityMetric/cumulativeBestAccuracyForNavigationTime": {
      "abstract": [
        {
          "text": "The total time spent tracking the current location at the best accuracy for navigation.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "cumulativeBestAccuracyForNavigationTime"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10Foundation11MeasurementV",
          "text": "Measurement"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSUnitDuration",
          "text": "UnitDuration"
        },
        {
          "kind": "text",
          "text": ">"
        }
      ],
      "identifier": "doc://com.apple.metrickit/documentation/MetricKit/MXLocationActivityMetric/cumulativeBestAccuracyForNavigationTime",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "cumulativeBestAccuracyForNavigationTime"
        }
      ],
      "role": "symbol",
      "title": "cumulativeBestAccuracyForNavigationTime",
      "type": "topic",
      "url": "/documentation/metrickit/mxlocationactivitymetric/cumulativebestaccuracyfornavigationtime"
    },
    "doc://com.apple.metrickit/documentation/MetricKit/MXLocationActivityMetric/cumulativeBestAccuracyTime": {
      "abstract": [
        {
          "text": "The total time spent tracking the current location at the best accuracy.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "cumulativeBestAccuracyTime"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10Foundation11MeasurementV",
          "text": "Measurement"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSUnitDuration",
          "text": "UnitDuration"
        },
        {
          "kind": "text",
          "text": ">"
        }
      ],
      "identifier": "doc://com.apple.metrickit/documentation/MetricKit/MXLocationActivityMetric/cumulativeBestAccuracyTime",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "cumulativeBestAccuracyTime"
        }
      ],
      "role": "symbol",
      "title": "cumulativeBestAccuracyTime",
      "type": "topic",
      "url": "/documentation/metrickit/mxlocationactivitymetric/cumulativebestaccuracytime"
    },
    "doc://com.apple.metrickit/documentation/MetricKit/MXLocationActivityMetric/cumulativeHundredMetersAccuracyTime": {
      "abstract": [
        {
          "text": "The total time spent tracking the current location to an accuracy of 100 meters.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "cumulativeHundredMetersAccuracyTime"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10Foundation11MeasurementV",
          "text": "Measurement"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSUnitDuration",
          "text": "UnitDuration"
        },
        {
          "kind": "text",
          "text": ">"
        }
      ],
      "identifier": "doc://com.apple.metrickit/documentation/MetricKit/MXLocationActivityMetric/cumulativeHundredMetersAccuracyTime",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "cumulativeHundredMetersAccuracyTime"
        }
      ],
      "role": "symbol",
      "title": "cumulativeHundredMetersAccuracyTime",
      "type": "topic",
      "url": "/documentation/metrickit/mxlocationactivitymetric/cumulativehundredmetersaccuracytime"
    },
    "doc://com.apple.metrickit/documentation/MetricKit/MXLocationActivityMetric/cumulativeKilometerAccuracyTime": {
      "abstract": [
        {
          "text": "The total time spent tracking the current location to an accuracy of 1 kilometer.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "cumulativeKilometerAccuracyTime"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10Foundation11MeasurementV",
          "text": "Measurement"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSUnitDuration",
          "text": "UnitDuration"
        },
        {
          "kind": "text",
          "text": ">"
        }
      ],
      "identifier": "doc://com.apple.metrickit/documentation/MetricKit/MXLocationActivityMetric/cumulativeKilometerAccuracyTime",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "cumulativeKilometerAccuracyTime"
        }
      ],
      "role": "symbol",
      "title": "cumulativeKilometerAccuracyTime",
      "type": "topic",
      "url": "/documentation/metrickit/mxlocationactivitymetric/cumulativekilometeraccuracytime"
    },
    "doc://com.apple.metrickit/documentation/MetricKit/MXLocationActivityMetric/cumulativeNearestTenMetersAccuracyTime": {
      "abstract": [
        {
          "text": "The total time spent tracking the current location to an accuracy of 10 meters.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "cumulativeNearestTenMetersAccuracyTime"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10Foundation11MeasurementV",
          "text": "Measurement"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSUnitDuration",
          "text": "UnitDuration"
        },
        {
          "kind": "text",
          "text": ">"
        }
      ],
      "identifier": "doc://com.apple.metrickit/documentation/MetricKit/MXLocationActivityMetric/cumulativeNearestTenMetersAccuracyTime",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "cumulativeNearestTenMetersAccuracyTime"
        }
      ],
      "role": "symbol",
      "title": "cumulativeNearestTenMetersAccuracyTime",
      "type": "topic",
      "url": "/documentation/metrickit/mxlocationactivitymetric/cumulativenearesttenmetersaccuracytime"
    },
    "doc://com.apple.metrickit/documentation/MetricKit/MXLocationActivityMetric/cumulativeThreeKilometersAccuracyTime": {
      "abstract": [
        {
          "text": "The total time spent tracking the current location to an accuracy of 3 kilometers.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "cumulativeThreeKilometersAccuracyTime"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10Foundation11MeasurementV",
          "text": "Measurement"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSUnitDuration",
          "text": "UnitDuration"
        },
        {
          "kind": "text",
          "text": ">"
        }
      ],
      "identifier": "doc://com.apple.metrickit/documentation/MetricKit/MXLocationActivityMetric/cumulativeThreeKilometersAccuracyTime",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "cumulativeThreeKilometersAccuracyTime"
        }
      ],
      "role": "symbol",
      "title": "cumulativeThreeKilometersAccuracyTime",
      "type": "topic",
      "url": "/documentation/metrickit/mxlocationactivitymetric/cumulativethreekilometersaccuracytime"
    },
    "doc://com.externally.resolved.symbol/c:objc(cs)NSUnitDuration": {
      "abstract": [
        {
          "text": "A unit of measure for a duration of time.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "class "
        },
        {
          "kind": "identifier",
          "text": "UnitDuration"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSUnitDuration",
      "kind": "symbol",
      "role": "symbol",
      "title": "UnitDuration",
      "type": "topic",
      "url": "/documentation/foundation/unitduration"
    },
    "doc://com.externally.resolved.symbol/s:10Foundation11MeasurementV": {
      "abstract": [
        {
          "text": "A numeric quantity labeled with a unit of measure, with support for unit conversion and unit-aware calculations. ",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "struct "
        },
        {
          "kind": "identifier",
          "text": "Measurement"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:10Foundation11MeasurementV",
      "kind": "symbol",
      "role": "symbol",
      "title": "Measurement",
      "type": "topic",
      "url": "/documentation/foundation/measurement"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Reading-location-services-use",
      "generated": true,
      "identifiers": [
        "doc://com.apple.metrickit/documentation/MetricKit/MXLocationActivityMetric/cumulativeBestAccuracyForNavigationTime",
        "doc://com.apple.metrickit/documentation/MetricKit/MXLocationActivityMetric/cumulativeNearestTenMetersAccuracyTime",
        "doc://com.apple.metrickit/documentation/MetricKit/MXLocationActivityMetric/cumulativeHundredMetersAccuracyTime",
        "doc://com.apple.metrickit/documentation/MetricKit/MXLocationActivityMetric/cumulativeKilometerAccuracyTime",
        "doc://com.apple.metrickit/documentation/MetricKit/MXLocationActivityMetric/cumulativeThreeKilometersAccuracyTime"
      ],
      "title": "Reading location services use"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.1",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Instance Property"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "cumulativeBestAccuracyTime"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "property"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "cumulativeBestAccuracyTime"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.metrickit/documentation/MetricKit",
                "doc://com.apple.metrickit/documentation/MetricKit/MXLocationActivityMetric"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Reading-location-services-use",
              "generated": true,
              "identifiers": [
                "doc://com.apple.metrickit/documentation/MetricKit/MXLocationActivityMetric/cumulativeBestAccuracyForNavigationTime",
                "doc://com.apple.metrickit/documentation/MetricKit/MXLocationActivityMetric/cumulativeNearestTenMetersAccuracyTime",
                "doc://com.apple.metrickit/documentation/MetricKit/MXLocationActivityMetric/cumulativeHundredMetersAccuracyTime",
                "doc://com.apple.metrickit/documentation/MetricKit/MXLocationActivityMetric/cumulativeKilometerAccuracyTime",
                "doc://com.apple.metrickit/documentation/MetricKit/MXLocationActivityMetric/cumulativeThreeKilometersAccuracyTime"
              ],
              "title": "Reading location services use"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "@property"
                  },
                  {
                    "kind": "text",
                    "text": " ("
                  },
                  {
                    "kind": "keyword",
                    "text": "strong"
                  },
                  {
                    "kind": "text",
                    "text": ", "
                  },
                  {
                    "kind": "keyword",
                    "text": "readonly"
                  },
                  {
                    "kind": "text",
                    "text": ") "
                  },
                  {
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:Q$objc(cs)NSMeasurement",
                    "text": "NSMeasurement<NSUnitDuration *>"
                  },
                  {
                    "kind": "text",
                    "text": " * "
                  },
                  {
                    "kind": "identifier",
                    "text": "cumulativeBestAccuracyTime"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metrickit~1documentation~1MetricKit~1MXLocationActivityMetric/title",
          "value": "MXLocationActivityMetric"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metrickit~1documentation~1MetricKit~1MXLocationActivityMetric/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MXLocationActivityMetric"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metrickit~1documentation~1MetricKit~1MXLocationActivityMetric/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MXLocationActivityMetric"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metrickit~1documentation~1MetricKit~1MXLocationActivityMetric~1cumulativeKilometerAccuracyTime/title",
          "value": "cumulativeKilometerAccuracyTime"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metrickit~1documentation~1MetricKit~1MXLocationActivityMetric~1cumulativeKilometerAccuracyTime/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "cumulativeKilometerAccuracyTime"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metrickit~1documentation~1MetricKit~1MXLocationActivityMetric~1cumulativeThreeKilometersAccuracyTime/title",
          "value": "cumulativeThreeKilometersAccuracyTime"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metrickit~1documentation~1MetricKit~1MXLocationActivityMetric~1cumulativeThreeKilometersAccuracyTime/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "cumulativeThreeKilometersAccuracyTime"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metrickit~1documentation~1MetricKit~1MXLocationActivityMetric~1cumulativeHundredMetersAccuracyTime/title",
          "value": "cumulativeHundredMetersAccuracyTime"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metrickit~1documentation~1MetricKit~1MXLocationActivityMetric~1cumulativeHundredMetersAccuracyTime/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "cumulativeHundredMetersAccuracyTime"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metrickit~1documentation~1MetricKit~1MXLocationActivityMetric~1cumulativeBestAccuracyTime/title",
          "value": "cumulativeBestAccuracyTime"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metrickit~1documentation~1MetricKit~1MXLocationActivityMetric~1cumulativeBestAccuracyTime/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "cumulativeBestAccuracyTime"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:objc(cs)NSUnitDuration/title",
          "value": "NSUnitDuration"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metrickit~1documentation~1MetricKit~1MXLocationActivityMetric~1cumulativeBestAccuracyForNavigationTime/title",
          "value": "cumulativeBestAccuracyForNavigationTime"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metrickit~1documentation~1MetricKit~1MXLocationActivityMetric~1cumulativeBestAccuracyForNavigationTime/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "cumulativeBestAccuracyForNavigationTime"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metrickit~1documentation~1MetricKit~1MXLocationActivityMetric~1cumulativeNearestTenMetersAccuracyTime/title",
          "value": "cumulativeNearestTenMetersAccuracyTime"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metrickit~1documentation~1MetricKit~1MXLocationActivityMetric~1cumulativeNearestTenMetersAccuracyTime/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "cumulativeNearestTenMetersAccuracyTime"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/metrickit/mxlocationactivitymetric/cumulativebestaccuracytime"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/metrickit/mxlocationactivitymetric/cumulativebestaccuracytime"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
