{"hierarchy":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.accelerate/documentation/Accelerate","doc://com.apple.accelerate/documentation/Accelerate/vImage","doc://com.apple.accelerate/documentation/Accelerate/vImage/PixelBuffer"]]},"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS","iPadOS","Mac Catalyst","macOS","tvOS","visionOS","watchOS"],"tokens":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"applyLookup","kind":"identifier"},{"text":"(","kind":"text"},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"lookupTable","kind":"internalParam"},{"text":": [","kind":"text"},{"text":"Pixel_16U","kind":"typeIdentifier","identifier":"doc://com.apple.accelerate/documentation/Accelerate/Pixel_16U","preciseIdentifier":"c:@T@Pixel_16U"},{"text":"], ","kind":"text"},{"text":"destination","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"vImage","kind":"typeIdentifier","identifier":"doc://com.apple.accelerate/documentation/Accelerate/vImage","preciseIdentifier":"s:10Accelerate6vImageO"},{"text":".","kind":"text"},{"text":"PixelBuffer","kind":"typeIdentifier","identifier":"doc://com.apple.accelerate/documentation/Accelerate/vImage/PixelBuffer","preciseIdentifier":"s:10Accelerate6vImageO11PixelBufferV"},{"text":"<","kind":"text"},{"text":"vImage","kind":"typeIdentifier","identifier":"doc://com.apple.accelerate/documentation/Accelerate/vImage","preciseIdentifier":"s:10Accelerate6vImageO"},{"text":".","kind":"text"},{"text":"Planar16U","kind":"typeIdentifier","identifier":"doc://com.apple.accelerate/documentation/Accelerate/vImage/Planar16U","preciseIdentifier":"s:10Accelerate6vImageO9Planar16UV"},{"text":">)","kind":"text"}],"languages":["swift"]}]},{"kind":"parameters","parameters":[{"name":"lookupTable","content":[{"type":"paragraph","inlineContent":[{"text":"A lookup table that contains 256 ","type":"text"},{"identifier":"doc://com.apple.accelerate/documentation/Accelerate/Pixel_16U","type":"reference","isActive":true},{"text":" values.","type":"text"}]}]},{"name":"destination","content":[{"inlineContent":[{"type":"text","text":"The destination pixel buffer."}],"type":"paragraph"}]}]},{"content":[{"level":2,"anchor":"Discussion","text":"Discussion","type":"heading"},{"type":"paragraph","inlineContent":[{"text":"You can use this function to create custom response curves (that is, the value of an output pixel based on the value of the corresponding input pixel). Changing the shape of the response curve changes the brightness and contrast of an image.","type":"text"}]},{"type":"paragraph","inlineContent":[{"text":"The following code creates a simple lookup table that’s based on a sigmoid function. This example uses ","type":"text"},{"identifier":"doc://com.apple.accelerate/documentation/Accelerate/BNNS","type":"reference","isActive":true},{"text":" to create 256 ","type":"text"},{"code":"Float","type":"codeVoice"},{"text":" values in the range ","type":"text"},{"code":"0...1","type":"codeVoice"},{"text":" that describe a sigmoid curve. The code scales the sigmoid curve values to ","type":"text"},{"code":"0...65535","type":"codeVoice"},{"text":" and returns ","type":"text"},{"identifier":"doc://com.apple.accelerate/documentation/Accelerate/Pixel_16U","type":"reference","isActive":true},{"text":" values that are suitable for use as a lookup table.","type":"text"}]},{"syntax":"swift","code":["let count = 256","","// The following code populates the array descriptor with sigmoid","// curve values in the range 0...1:","let sigmoidSourceValues: [Float] = vDSP.ramp(in: -10 ... 10,","                                             count: count)","let descriptor = BNNSNDArrayDescriptor.allocate(initializingFrom: sigmoidSourceValues,","                                                shape: .vector(count))","defer {","    descriptor.deallocate()","}","let activationLayer = BNNS.ActivationLayer(function: .sigmoid,","                                           input: descriptor,","                                           output: descriptor,","                                           filterParameters: nil)","try? activationLayer!.apply(batchSize: 1,","                            input: descriptor,","                            output: descriptor)","","let lookup = descriptor.data!.withMemoryRebound(to: Float.self,","                                                   capacity: count) {","    // Create an `UnsafeMutableBufferPointer` from the descriptor data.","    var sigmoid = UnsafeMutableBufferPointer(start: $0,","                                             count: count)","    ","    // Scale the sigmoid values from 0...1 to 0...65535.","    vDSP.multiply(Float(Pixel_16U.max),","                  sigmoid,","                  result: &sigmoid)","","    // Create Pixel_16U values from the Float sigmoid values.","    return vDSP.floatingPointToInteger(sigmoid,","                                       integerType: Pixel_16U.self,","                                       rounding: .towardNearestInteger)","}"],"type":"codeListing"},{"type":"paragraph","inlineContent":[{"type":"text","text":"The graph below visualizes the values in the lookup table:"}]},{"type":"paragraph","inlineContent":[{"identifier":"media-4165167","type":"image"}]},{"type":"paragraph","inlineContent":[{"text":"Use the following code to apply the lookup table to a ","type":"text"},{"identifier":"doc://com.apple.accelerate/documentation/Accelerate/vImage/Planar8","isActive":true,"type":"reference"},{"text":" source buffer and write the result to a ","type":"text"},{"identifier":"doc://com.apple.accelerate/documentation/Accelerate/vImage/Planar16U","isActive":true,"type":"reference"},{"text":" destination buffer:","type":"text"}]},{"syntax":"swift","code":["let destinationBuffer = vImage.PixelBuffer(","    size: sourceBuffer.size,","    pixelFormat: vImage.Planar16U.self)","","sourceBuffer.applyLookup(lookup, destination: destinationBuffer)"],"type":"codeListing"},{"type":"paragraph","inlineContent":[{"type":"text","text":"The images below show an example grayscale source image on the left and the transformed result on the right. The operation flattens the response for very dark and very bright areas and increases the contrast in the destination image."}]},{"type":"paragraph","inlineContent":[{"identifier":"media-4165165","type":"image"}]}],"kind":"content"}],"abstract":[{"type":"text","text":"Applies a lookup table to transform an 8-bit planar image to a 16-bit planar image."}],"metadata":{"externalID":"s:10Accelerate6vImageO11PixelBufferVAaC9Planar16UVRszrlE11applyLookup_11destinationySays6UInt16VG_AEy_AGGtF","symbolKind":"method","extendedModule":"Accelerate","role":"symbol","platforms":[{"deprecated":false,"unavailable":false,"beta":false,"name":"iOS","introducedAt":"17.0"},{"deprecated":false,"unavailable":false,"beta":false,"name":"iPadOS","introducedAt":"17.0"},{"deprecated":false,"unavailable":false,"beta":false,"name":"Mac Catalyst"},{"deprecated":false,"beta":false,"name":"macOS","unavailable":false,"introducedAt":"14.0"},{"deprecated":false,"beta":false,"name":"tvOS","unavailable":false,"introducedAt":"17.0"},{"deprecated":false,"beta":false,"name":"visionOS","unavailable":false},{"deprecated":false,"beta":false,"name":"watchOS","unavailable":false,"introducedAt":"10.0"}],"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"applyLookup"},{"kind":"text","text":"(["},{"preciseIdentifier":"c:@T@Pixel_16U","kind":"typeIdentifier","text":"Pixel_16U"},{"kind":"text","text":"], "},{"kind":"externalParam","text":"destination"},{"kind":"text","text":": "},{"preciseIdentifier":"s:10Accelerate6vImageO","kind":"typeIdentifier","text":"vImage"},{"kind":"text","text":"."},{"preciseIdentifier":"s:10Accelerate6vImageO11PixelBufferV","kind":"typeIdentifier","text":"PixelBuffer"},{"kind":"text","text":"<"},{"preciseIdentifier":"s:10Accelerate6vImageO","kind":"typeIdentifier","text":"vImage"},{"kind":"text","text":"."},{"preciseIdentifier":"s:10Accelerate6vImageO9Planar16UV","kind":"typeIdentifier","text":"Planar16U"},{"kind":"text","text":">)"}],"roleHeading":"Instance Method","title":"applyLookup(_:destination:)","conformance":{"conformancePrefix":[{"type":"text","text":"Conforms when"}],"availabilityPrefix":[{"type":"text","text":"Available when"}],"constraints":[{"type":"codeVoice","code":"Format"},{"type":"text","text":" is "},{"type":"codeVoice","code":"vImage.Planar16U"},{"type":"text","text":"."}]},"modules":[{"name":"Accelerate"}]},"identifier":{"interfaceLanguage":"swift","url":"doc://com.apple.accelerate/documentation/Accelerate/vImage/PixelBuffer/applyLookup(_:destination:)-5oi4o"},"seeAlsoSections":[{"title":"Transforming with a lookup table","generated":true,"identifiers":["doc://com.apple.accelerate/documentation/Accelerate/vImage/PixelBuffer/applyLookup(_:destination:)-5r7bq","doc://com.apple.accelerate/documentation/Accelerate/vImage/PixelBuffer/applyLookup(_:destination:)-14pjo","doc://com.apple.accelerate/documentation/Accelerate/vImage/PixelBuffer/applyLookup(_:destination:)-3ruls","doc://com.apple.accelerate/documentation/Accelerate/vImage/PixelBuffer/applyLookup(_:destination:)-1tsb5","doc://com.apple.accelerate/documentation/Accelerate/vImage/PixelBuffer/applyLookup(alphaTable:redTable:greenTable:blueTable:destination:)"],"anchor":"Transforming-with-a-lookup-table"}],"variants":[{"paths":["/documentation/accelerate/vimage/pixelbuffer/applylookup(_:destination:)-5oi4o"],"traits":[{"interfaceLanguage":"swift"}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"references":{"doc://com.apple.accelerate/documentation/Accelerate/vImage/PixelBuffer/applyLookup(_:destination:)-5oi4o":{"identifier":"doc://com.apple.accelerate/documentation/Accelerate/vImage/PixelBuffer/applyLookup(_:destination:)-5oi4o","conformance":{"conformancePrefix":[{"type":"text","text":"Conforms when"}],"availabilityPrefix":[{"type":"text","text":"Available when"}],"constraints":[{"type":"codeVoice","code":"Format"},{"type":"text","text":" is "},{"type":"codeVoice","code":"vImage.Planar16U"},{"type":"text","text":"."}]},"url":"/documentation/accelerate/vimage/pixelbuffer/applylookup(_:destination:)-5oi4o","type":"topic","abstract":[{"type":"text","text":"Applies a lookup table to transform an 8-bit planar image to a 16-bit planar image."}],"title":"applyLookup(_:destination:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"applyLookup","kind":"identifier"},{"text":"([","kind":"text"},{"preciseIdentifier":"c:@T@Pixel_16U","text":"Pixel_16U","kind":"typeIdentifier"},{"kind":"text","text":"], "},{"kind":"externalParam","text":"destination"},{"kind":"text","text":": "},{"preciseIdentifier":"s:10Accelerate6vImageO","kind":"typeIdentifier","text":"vImage"},{"kind":"text","text":"."},{"preciseIdentifier":"s:10Accelerate6vImageO11PixelBufferV","kind":"typeIdentifier","text":"PixelBuffer"},{"kind":"text","text":"<"},{"preciseIdentifier":"s:10Accelerate6vImageO","kind":"typeIdentifier","text":"vImage"},{"kind":"text","text":"."},{"preciseIdentifier":"s:10Accelerate6vImageO9Planar16UV","kind":"typeIdentifier","text":"Planar16U"},{"kind":"text","text":">)"}],"kind":"symbol","role":"symbol"},"doc://com.apple.accelerate/documentation/Accelerate/vImage/PixelBuffer/applyLookup(_:destination:)-14pjo":{"identifier":"doc://com.apple.accelerate/documentation/Accelerate/vImage/PixelBuffer/applyLookup(_:destination:)-14pjo","conformance":{"conformancePrefix":[{"text":"Conforms when","type":"text"}],"availabilityPrefix":[{"text":"Available when","type":"text"}],"constraints":[{"code":"Format","type":"codeVoice"},{"text":" is ","type":"text"},{"code":"vImage.PlanarF","type":"codeVoice"},{"text":".","type":"text"}]},"url":"/documentation/accelerate/vimage/pixelbuffer/applylookup(_:destination:)-14pjo","type":"topic","abstract":[{"type":"text","text":"Applies a lookup table to transform an 8-bit planar image to a 32-bit planar image."}],"title":"applyLookup(_:destination:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"applyLookup","kind":"identifier"},{"text":"([","kind":"text"},{"preciseIdentifier":"c:@T@Pixel_F","text":"Pixel_F","kind":"typeIdentifier"},{"text":"], ","kind":"text"},{"text":"destination","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:10Accelerate6vImageO","text":"vImage","kind":"typeIdentifier"},{"kind":"text","text":"."},{"preciseIdentifier":"s:10Accelerate6vImageO11PixelBufferV","kind":"typeIdentifier","text":"PixelBuffer"},{"kind":"text","text":"<"},{"preciseIdentifier":"s:10Accelerate6vImageO","kind":"typeIdentifier","text":"vImage"},{"kind":"text","text":"."},{"preciseIdentifier":"s:10Accelerate6vImageO7PlanarFV","kind":"typeIdentifier","text":"PlanarF"},{"kind":"text","text":">)"}],"kind":"symbol","role":"symbol"},"media-4165165":{"identifier":"media-4165165","alt":"Two versions of a close-up image of a fruit tree. On the left is the original grayscale image, and on the right is the transformed high-contrast image.","type":"image","variants":[{"traits":["2x","light"],"url":"https://docs-assets.developer.apple.com/published/ecd3ca07235a9c8c2b75acd702d2ae39/media-4165165@2x.png"},{"traits":["2x","dark"],"url":"https://docs-assets.developer.apple.com/published/73660ec1385b15968205cb684b19962a/media-4165165~dark@2x.png"}]},"doc://com.apple.accelerate/documentation/Accelerate/vImage/PixelBuffer/applyLookup(_:destination:)-3ruls":{"type":"topic","title":"applyLookup(_:destination:)","role":"symbol","identifier":"doc://com.apple.accelerate/documentation/Accelerate/vImage/PixelBuffer/applyLookup(_:destination:)-3ruls","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"applyLookup","kind":"identifier"},{"text":"([","kind":"text"},{"text":"Pixel_8888","kind":"typeIdentifier","preciseIdentifier":"c:@T@Pixel_8888"},{"text":"], ","kind":"text"},{"text":"destination","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"vImage","kind":"typeIdentifier","preciseIdentifier":"s:10Accelerate6vImageO"},{"text":".","kind":"text"},{"preciseIdentifier":"s:10Accelerate6vImageO11PixelBufferV","kind":"typeIdentifier","text":"PixelBuffer"},{"kind":"text","text":"<"},{"preciseIdentifier":"s:10Accelerate6vImageO","kind":"typeIdentifier","text":"vImage"},{"kind":"text","text":"."},{"preciseIdentifier":"s:10Accelerate6vImageO14Interleaved8x3V","kind":"typeIdentifier","text":"Interleaved8x3"},{"kind":"text","text":">)"}],"abstract":[{"type":"text","text":"Applies a lookup table to transform an 8-bit planar image to an 8-bit-per-channel, three-channel interleaved image."}],"kind":"symbol","conformance":{"conformancePrefix":[{"text":"Conforms when","type":"text"}],"availabilityPrefix":[{"text":"Available when","type":"text"}],"constraints":[{"code":"Format","type":"codeVoice"},{"text":" is ","type":"text"},{"code":"vImage.Planar8","type":"codeVoice"},{"text":".","type":"text"}]},"url":"/documentation/accelerate/vimage/pixelbuffer/applylookup(_:destination:)-3ruls"},"doc://com.apple.accelerate/documentation/Accelerate/Pixel_16U":{"role":"symbol","kind":"symbol","fragments":[{"kind":"keyword","text":"typealias"},{"text":" ","kind":"text"},{"text":"Pixel_16U","kind":"identifier"}],"url":"/documentation/accelerate/pixel_16u","identifier":"doc://com.apple.accelerate/documentation/Accelerate/Pixel_16U","abstract":[{"text":"A type for a planar, 16-bits-per-channel, unsigned pixel.","type":"text"}],"navigatorTitle":[{"text":"Pixel_16U","kind":"identifier"}],"title":"Pixel_16U","type":"topic"},"doc://com.apple.accelerate/documentation/Accelerate/vImage/Planar16U":{"kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"Planar16U"}],"fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"Planar16U"}],"role":"symbol","url":"/documentation/accelerate/vimage/planar16u","title":"vImage.Planar16U","abstract":[{"type":"text","text":"A single-channel, 16-bit-per-channel, unsigned-integer buffer."}],"identifier":"doc://com.apple.accelerate/documentation/Accelerate/vImage/Planar16U"},"doc://com.apple.accelerate/documentation/Accelerate/vImage/PixelBuffer":{"type":"topic","abstract":[{"type":"text","text":"An image buffer that stores an image’s pixel data, dimensions, bit depth, and number of channels."}],"role":"symbol","url":"/documentation/accelerate/vimage/pixelbuffer","title":"vImage.PixelBuffer","navigatorTitle":[{"kind":"identifier","text":"PixelBuffer"}],"kind":"symbol","identifier":"doc://com.apple.accelerate/documentation/Accelerate/vImage/PixelBuffer","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"PixelBuffer"}]},"doc://com.apple.documentation/documentation/technologies":{"title":"Technologies","identifier":"doc://com.apple.documentation/documentation/technologies","role":"overview","kind":"technologies","url":"/documentation/technologies","abstract":[{"text":"","type":"text"}],"type":"topic"},"doc://com.apple.accelerate/documentation/Accelerate/vImage":{"abstract":[{"type":"text","text":"An enumeration that acts as a namespace for Swift overlays to vImage."}],"navigatorTitle":[{"text":"vImage","kind":"identifier"}],"title":"vImage","type":"topic","kind":"symbol","url":"/documentation/accelerate/vimage","identifier":"doc://com.apple.accelerate/documentation/Accelerate/vImage","role":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"vImage","kind":"identifier"}]},"doc://com.apple.accelerate/documentation/Accelerate/vImage/PixelBuffer/applyLookup(_:destination:)-1tsb5":{"type":"topic","title":"applyLookup(_:destination:)","role":"symbol","identifier":"doc://com.apple.accelerate/documentation/Accelerate/vImage/PixelBuffer/applyLookup(_:destination:)-1tsb5","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"applyLookup","kind":"identifier"},{"text":"([","kind":"text"},{"text":"Pixel_FFFF","kind":"typeIdentifier","preciseIdentifier":"c:@T@Pixel_FFFF"},{"text":"], ","kind":"text"},{"text":"destination","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"vImage","kind":"typeIdentifier","preciseIdentifier":"s:10Accelerate6vImageO"},{"text":".","kind":"text"},{"preciseIdentifier":"s:10Accelerate6vImageO11PixelBufferV","kind":"typeIdentifier","text":"PixelBuffer"},{"kind":"text","text":"<"},{"preciseIdentifier":"s:10Accelerate6vImageO","kind":"typeIdentifier","text":"vImage"},{"kind":"text","text":"."},{"preciseIdentifier":"s:10Accelerate6vImageO14InterleavedFx3V","kind":"typeIdentifier","text":"InterleavedFx3"},{"kind":"text","text":">)"}],"abstract":[{"type":"text","text":"Applies a lookup table to transform an 8-bit planar image to a 32-bit-per-channel, three-channel interleaved image."}],"kind":"symbol","conformance":{"conformancePrefix":[{"text":"Conforms when","type":"text"}],"availabilityPrefix":[{"text":"Available when","type":"text"}],"constraints":[{"code":"Format","type":"codeVoice"},{"text":" is ","type":"text"},{"code":"vImage.Planar8","type":"codeVoice"},{"text":".","type":"text"}]},"url":"/documentation/accelerate/vimage/pixelbuffer/applylookup(_:destination:)-1tsb5"},"doc://com.apple.accelerate/documentation/Accelerate/BNNS":{"identifier":"doc://com.apple.accelerate/documentation/Accelerate/BNNS","kind":"symbol","title":"BNNS","fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"kind":"identifier","text":"BNNS"}],"navigatorTitle":[{"kind":"identifier","text":"BNNS"}],"role":"symbol","type":"topic","url":"/documentation/accelerate/bnns","abstract":[{"type":"text","text":"An enumeration that acts as a namespace for Swift overlays to BNNS."}]},"doc://com.apple.accelerate/documentation/Accelerate/vImage/Planar8":{"abstract":[{"type":"text","text":"A single-channel, 8-bit-per-channel, unsigned-integer buffer."}],"type":"topic","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"Planar8"}],"navigatorTitle":[{"kind":"identifier","text":"Planar8"}],"title":"vImage.Planar8","identifier":"doc://com.apple.accelerate/documentation/Accelerate/vImage/Planar8","kind":"symbol","url":"/documentation/accelerate/vimage/planar8","role":"symbol"},"doc://com.apple.accelerate/documentation/Accelerate/vImage/PixelBuffer/applyLookup(alphaTable:redTable:greenTable:blueTable:destination:)":{"type":"topic","title":"applyLookup(alphaTable:redTable:greenTable:blueTable:destination:)","role":"symbol","identifier":"doc://com.apple.accelerate/documentation/Accelerate/vImage/PixelBuffer/applyLookup(alphaTable:redTable:greenTable:blueTable:destination:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"applyLookup","kind":"identifier"},{"text":"(","kind":"text"},{"text":"alphaTable","kind":"externalParam"},{"text":": [","kind":"text"},{"text":"Pixel_8","kind":"typeIdentifier","preciseIdentifier":"c:@T@Pixel_8"},{"text":"]?, ","kind":"text"},{"text":"redTable","kind":"externalParam"},{"text":": [","kind":"text"},{"preciseIdentifier":"c:@T@Pixel_8","kind":"typeIdentifier","text":"Pixel_8"},{"kind":"text","text":"]?, "},{"kind":"externalParam","text":"greenTable"},{"kind":"text","text":": ["},{"preciseIdentifier":"c:@T@Pixel_8","kind":"typeIdentifier","text":"Pixel_8"},{"kind":"text","text":"]?, "},{"kind":"externalParam","text":"blueTable"},{"kind":"text","text":": ["},{"preciseIdentifier":"c:@T@Pixel_8","kind":"typeIdentifier","text":"Pixel_8"},{"kind":"text","text":"]?, "},{"kind":"externalParam","text":"destination"},{"kind":"text","text":": "},{"preciseIdentifier":"s:10Accelerate6vImageO","kind":"typeIdentifier","text":"vImage"},{"kind":"text","text":"."},{"preciseIdentifier":"s:10Accelerate6vImageO11PixelBufferV","kind":"typeIdentifier","text":"PixelBuffer"},{"kind":"text","text":"<"},{"preciseIdentifier":"s:10Accelerate6vImageO","kind":"typeIdentifier","text":"vImage"},{"kind":"text","text":"."},{"preciseIdentifier":"s:10Accelerate6vImageO14Interleaved8x4V","kind":"typeIdentifier","text":"Interleaved8x4"},{"kind":"text","text":">)"}],"abstract":[{"type":"text","text":"Applies a set of four lookup tables to transform an interleaved, four-channel 8-bit image."}],"kind":"symbol","conformance":{"conformancePrefix":[{"text":"Conforms when","type":"text"}],"availabilityPrefix":[{"text":"Available when","type":"text"}],"constraints":[{"type":"codeVoice","code":"Format"},{"text":" is ","type":"text"},{"type":"codeVoice","code":"vImage.Interleaved8x4"},{"text":".","type":"text"}]},"url":"/documentation/accelerate/vimage/pixelbuffer/applylookup(alphatable:redtable:greentable:bluetable:destination:)"},"doc://com.apple.accelerate/documentation/Accelerate/vImage/PixelBuffer/applyLookup(_:destination:)-5r7bq":{"type":"topic","title":"applyLookup(_:destination:)","role":"symbol","identifier":"doc://com.apple.accelerate/documentation/Accelerate/vImage/PixelBuffer/applyLookup(_:destination:)-5r7bq","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"applyLookup","kind":"identifier"},{"text":"([","kind":"text"},{"text":"Pixel_8","kind":"typeIdentifier","preciseIdentifier":"c:@T@Pixel_8"},{"text":"], ","kind":"text"},{"text":"destination","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"vImage","preciseIdentifier":"s:10Accelerate6vImageO","kind":"typeIdentifier"},{"text":".","kind":"text"},{"text":"PixelBuffer","preciseIdentifier":"s:10Accelerate6vImageO11PixelBufferV","kind":"typeIdentifier"},{"text":"<","kind":"text"},{"preciseIdentifier":"s:10Accelerate6vImageO","kind":"typeIdentifier","text":"vImage"},{"kind":"text","text":"."},{"preciseIdentifier":"s:10Accelerate6vImageO7Planar8V","kind":"typeIdentifier","text":"Planar8"},{"kind":"text","text":">)"}],"abstract":[{"type":"text","text":"Applies a lookup table to transform an 8-bit planar image."}],"kind":"symbol","conformance":{"conformancePrefix":[{"type":"text","text":"Conforms when"}],"availabilityPrefix":[{"type":"text","text":"Available when"}],"constraints":[{"type":"codeVoice","code":"Format"},{"type":"text","text":" is "},{"type":"codeVoice","code":"vImage.Planar8"},{"type":"text","text":"."}]},"url":"/documentation/accelerate/vimage/pixelbuffer/applylookup(_:destination:)-5r7bq"},"media-4165167":{"alt":"A line chart showing an s-shaped sigmoid curve.","identifier":"media-4165167","variants":[{"traits":["2x","light"],"url":"https://docs-assets.developer.apple.com/published/c0fb337c8dc8d88c6ad0f1e2067d93a6/media-4165167@2x.png"},{"traits":["2x","dark"],"url":"https://docs-assets.developer.apple.com/published/999b683b9b1d2ce5de2f512086a6ad98/media-4165167~dark@2x.png"}],"type":"image"},"doc://com.apple.accelerate/documentation/Accelerate":{"abstract":[{"text":"Make large-scale mathematical computations and image calculations, optimized for high performance and low energy consumption.","type":"text"}],"type":"topic","title":"Accelerate","identifier":"doc://com.apple.accelerate/documentation/Accelerate","kind":"symbol","url":"/documentation/accelerate","role":"collection"}},"variantOverrides":[{"patch":[{"op":"replace","path":"/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1Pixel_16U/title","value":"Pixel_16U"},{"op":"replace","path":"/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1Pixel_16U/fragments","value":[{"text":"Pixel_16U","kind":"identifier"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1Pixel_16U/navigatorTitle","value":[{"text":"Pixel_16U","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}],"legalNotices":{"copyright":"Copyright &copy; 2025 Apple Inc. All rights reserved.","termsOfUse":"https://www.apple.com/legal/internet-services/terms/site.html","privacyPolicy":"https://www.apple.com/privacy/privacy-policy"}}