{
  "abstract": [
    {
      "text": "Populates the pixel buffer with ARGB data from the given luminance and chrominance pixel buffers.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.accelerate/documentation/Accelerate",
        "doc://com.apple.accelerate/documentation/Accelerate/vImage",
        "doc://com.apple.accelerate/documentation/Accelerate/vImage/PixelBuffer"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.accelerate/documentation/Accelerate/vImage/PixelBuffer/convert(lumaSource:chromaSource:conversionInfo:)"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "conformance": {
      "availabilityPrefix": [
        {
          "text": "Available when",
          "type": "text"
        }
      ],
      "conformancePrefix": [
        {
          "text": "Conforms when",
          "type": "text"
        }
      ],
      "constraints": [
        {
          "code": "Format",
          "type": "codeVoice"
        },
        {
          "text": " is ",
          "type": "text"
        },
        {
          "code": "vImage.Interleaved8x4",
          "type": "codeVoice"
        },
        {
          "text": ".",
          "type": "text"
        }
      ]
    },
    "extendedModule": "Accelerate",
    "externalID": "s:10Accelerate6vImageO11PixelBufferVAaC14Interleaved8x4VRszrlE7convert10lumaSource06chromaH014conversionInfoyAEy_AC7Planar8VG_AEy_AC14Interleaved8x2VGSo01vB13_YpCbCrToARGBVtF",
    "fragments": [
      {
        "kind": "keyword",
        "text": "func"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "convert"
      },
      {
        "kind": "text",
        "text": "("
      },
      {
        "kind": "externalParam",
        "text": "lumaSource"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "s:10Accelerate6vImageO",
        "text": "vImage"
      },
      {
        "kind": "text",
        "text": "."
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "s:10Accelerate6vImageO11PixelBufferV",
        "text": "PixelBuffer"
      },
      {
        "kind": "text",
        "text": "<"
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "s:10Accelerate6vImageO",
        "text": "vImage"
      },
      {
        "kind": "text",
        "text": "."
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "s:10Accelerate6vImageO7Planar8V",
        "text": "Planar8"
      },
      {
        "kind": "text",
        "text": ">, "
      },
      {
        "kind": "externalParam",
        "text": "chromaSource"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "s:10Accelerate6vImageO",
        "text": "vImage"
      },
      {
        "kind": "text",
        "text": "."
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "s:10Accelerate6vImageO11PixelBufferV",
        "text": "PixelBuffer"
      },
      {
        "kind": "text",
        "text": "<"
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "s:10Accelerate6vImageO",
        "text": "vImage"
      },
      {
        "kind": "text",
        "text": "."
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "s:10Accelerate6vImageO14Interleaved8x2V",
        "text": "Interleaved8x2"
      },
      {
        "kind": "text",
        "text": ">, "
      },
      {
        "kind": "externalParam",
        "text": "conversionInfo"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@S@vImage_YpCbCrToARGB",
        "text": "vImage_YpCbCrToARGB"
      },
      {
        "kind": "text",
        "text": ")"
      }
    ],
    "modules": [
      {
        "name": "Accelerate"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "16.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "16.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.0",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "16.0",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "9.0",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Instance Method",
    "symbolKind": "method",
    "title": "convert(lumaSource:chromaSource:conversionInfo:)"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "func"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "convert"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "kind": "externalParam",
              "text": "lumaSource"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.accelerate/documentation/Accelerate/vImage",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:10Accelerate6vImageO",
              "text": "vImage"
            },
            {
              "kind": "text",
              "text": "."
            },
            {
              "identifier": "doc://com.apple.accelerate/documentation/Accelerate/vImage/PixelBuffer",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:10Accelerate6vImageO11PixelBufferV",
              "text": "PixelBuffer"
            },
            {
              "kind": "text",
              "text": "<"
            },
            {
              "identifier": "doc://com.apple.accelerate/documentation/Accelerate/vImage",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:10Accelerate6vImageO",
              "text": "vImage"
            },
            {
              "kind": "text",
              "text": "."
            },
            {
              "identifier": "doc://com.apple.accelerate/documentation/Accelerate/vImage/Planar8",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:10Accelerate6vImageO7Planar8V",
              "text": "Planar8"
            },
            {
              "kind": "text",
              "text": ">, "
            },
            {
              "kind": "externalParam",
              "text": "chromaSource"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.accelerate/documentation/Accelerate/vImage",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:10Accelerate6vImageO",
              "text": "vImage"
            },
            {
              "kind": "text",
              "text": "."
            },
            {
              "identifier": "doc://com.apple.accelerate/documentation/Accelerate/vImage/PixelBuffer",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:10Accelerate6vImageO11PixelBufferV",
              "text": "PixelBuffer"
            },
            {
              "kind": "text",
              "text": "<"
            },
            {
              "identifier": "doc://com.apple.accelerate/documentation/Accelerate/vImage",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:10Accelerate6vImageO",
              "text": "vImage"
            },
            {
              "kind": "text",
              "text": "."
            },
            {
              "identifier": "doc://com.apple.accelerate/documentation/Accelerate/vImage/Interleaved8x2",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:10Accelerate6vImageO14Interleaved8x2V",
              "text": "Interleaved8x2"
            },
            {
              "kind": "text",
              "text": ">, "
            },
            {
              "kind": "externalParam",
              "text": "conversionInfo"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.accelerate/documentation/Accelerate/vImage_YpCbCrToARGB",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@S@vImage_YpCbCrToARGB",
              "text": "vImage_YpCbCrToARGB"
            },
            {
              "kind": "text",
              "text": ")"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "kind": "parameters",
      "parameters": [
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "The source luminance buffer.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "lumaSource"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "The source CbCr chrominance buffer.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "chromaSource"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "An opaque representation of a 3 x 3 converson matrix for converting Y’CbCr signals to RGB.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "conversionInfo"
        }
      ]
    }
  ],
  "references": {
    "doc://com.apple.accelerate/documentation/Accelerate": {
      "abstract": [
        {
          "text": "Make large-scale mathematical computations and image calculations, optimized for high performance and low energy consumption.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate",
      "kind": "symbol",
      "role": "collection",
      "title": "Accelerate",
      "type": "topic",
      "url": "/documentation/accelerate"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/vImage": {
      "abstract": [
        {
          "text": "An enumeration that acts as a namespace for Swift overlays to vImage.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "vImage"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/vImage",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "vImage"
        }
      ],
      "role": "symbol",
      "title": "vImage",
      "type": "topic",
      "url": "/documentation/accelerate/vimage"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/vImage/Interleaved8x2": {
      "abstract": [
        {
          "text": "A two-channel, 8-bit-per-channel interleaved buffer.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Interleaved8x2"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/vImage/Interleaved8x2",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "Interleaved8x2"
        }
      ],
      "role": "symbol",
      "title": "vImage.Interleaved8x2",
      "type": "topic",
      "url": "/documentation/accelerate/vimage/interleaved8x2"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/vImage/PixelBuffer": {
      "abstract": [
        {
          "text": "An image buffer that stores an image’s pixel data, dimensions, bit depth, and number of channels.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "PixelBuffer"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/vImage/PixelBuffer",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PixelBuffer"
        }
      ],
      "role": "symbol",
      "title": "vImage.PixelBuffer",
      "type": "topic",
      "url": "/documentation/accelerate/vimage/pixelbuffer"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/vImage/PixelBuffer/convert(lumaSource:chromaSource:conversionInfo:)": {
      "abstract": [
        {
          "text": "Populates the pixel buffer with ARGB data from the given luminance and chrominance pixel buffers.",
          "type": "text"
        }
      ],
      "conformance": {
        "availabilityPrefix": [
          {
            "text": "Available when",
            "type": "text"
          }
        ],
        "conformancePrefix": [
          {
            "text": "Conforms when",
            "type": "text"
          }
        ],
        "constraints": [
          {
            "code": "Format",
            "type": "codeVoice"
          },
          {
            "text": " is ",
            "type": "text"
          },
          {
            "code": "vImage.Interleaved8x4",
            "type": "codeVoice"
          },
          {
            "text": ".",
            "type": "text"
          }
        ]
      },
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "convert"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "lumaSource"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10Accelerate6vImageO",
          "text": "vImage"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10Accelerate6vImageO11PixelBufferV",
          "text": "PixelBuffer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10Accelerate6vImageO",
          "text": "vImage"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10Accelerate6vImageO7Planar8V",
          "text": "Planar8"
        },
        {
          "kind": "text",
          "text": ">, "
        },
        {
          "kind": "externalParam",
          "text": "chromaSource"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10Accelerate6vImageO",
          "text": "vImage"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10Accelerate6vImageO11PixelBufferV",
          "text": "PixelBuffer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10Accelerate6vImageO",
          "text": "vImage"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10Accelerate6vImageO14Interleaved8x2V",
          "text": "Interleaved8x2"
        },
        {
          "kind": "text",
          "text": ">, "
        },
        {
          "kind": "externalParam",
          "text": "conversionInfo"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@vImage_YpCbCrToARGB",
          "text": "vImage_YpCbCrToARGB"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/vImage/PixelBuffer/convert(lumaSource:chromaSource:conversionInfo:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "convert(lumaSource:chromaSource:conversionInfo:)",
      "type": "topic",
      "url": "/documentation/accelerate/vimage/pixelbuffer/convert(lumasource:chromasource:conversioninfo:)"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/vImage/Planar8": {
      "abstract": [
        {
          "text": "A single-channel, 8-bit-per-channel, unsigned-integer buffer.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Planar8"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/vImage/Planar8",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "Planar8"
        }
      ],
      "role": "symbol",
      "title": "vImage.Planar8",
      "type": "topic",
      "url": "/documentation/accelerate/vimage/planar8"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/vImage_YpCbCrToARGB": {
      "abstract": [
        {
          "text": "The information that describes the conversion from YpCbCr to ARGB.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "vImage_YpCbCrToARGB"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/vImage_YpCbCrToARGB",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "vImage_YpCbCrToARGB"
        }
      ],
      "role": "symbol",
      "title": "vImage_YpCbCrToARGB",
      "type": "topic",
      "url": "/documentation/accelerate/vimage_ypcbcrtoargb"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1vImage_YpCbCrToARGB/title",
          "value": "vImage_YpCbCrToARGB"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1vImage_YpCbCrToARGB/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "vImage_YpCbCrToARGB"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1vImage_YpCbCrToARGB/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "vImage_YpCbCrToARGB"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/accelerate/vimage/pixelbuffer/convert(lumasource:chromasource:conversioninfo:)"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    }
  ]
}
