{
  "abstract": [
    {
      "text": "The width, in pixels, of the underlying memory, including any additional row byte padding.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.accelerate/documentation/Accelerate",
        "doc://com.apple.accelerate/documentation/Accelerate/vImage",
        "doc://com.apple.accelerate/documentation/Accelerate/vImage/PixelBuffer"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.accelerate/documentation/Accelerate/vImage/PixelBuffer/rowStride"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "conformance": {
      "availabilityPrefix": [
        {
          "text": "Available when",
          "type": "text"
        }
      ],
      "conformancePrefix": [
        {
          "text": "Conforms when",
          "type": "text"
        }
      ],
      "constraints": [
        {
          "code": "Format",
          "type": "codeVoice"
        },
        {
          "text": " conforms to ",
          "type": "text"
        },
        {
          "code": "StaticPixelFormat",
          "type": "codeVoice"
        },
        {
          "text": ".",
          "type": "text"
        }
      ]
    },
    "extendedModule": "Accelerate",
    "externalID": "s:10Accelerate6vImageO11PixelBufferVA2A06StaticC6FormatRzrlE9rowStrideSivp",
    "fragments": [
      {
        "kind": "keyword",
        "text": "var"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "rowStride"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "s:Si",
        "text": "Int"
      }
    ],
    "modules": [
      {
        "name": "Accelerate"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "16.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "16.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.0",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "16.0",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "9.0",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Instance Property",
    "symbolKind": "property",
    "title": "rowStride"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "var"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "rowStride"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:Si",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:Si",
              "text": "Int"
            },
            {
              "kind": "text",
              "text": " { "
            },
            {
              "kind": "keyword",
              "text": "get"
            },
            {
              "kind": "text",
              "text": " }"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Use this property when working with the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.accelerate/documentation/Accelerate/AccelerateBuffer",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " and ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.accelerate/documentation/Accelerate/AccelerateMutableBuffer",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " functions. The property allows you to limit work you do on the underlying memory of a pixel buffer to just the visible pixels.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "In some cases, vImage adds extra bytes at the end of each row. Use ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.accelerate/documentation/Accelerate/vImage/PixelBuffer/rowStride",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " to find the width, in pixels, of the memory pointed to by the vImage buffer’s ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.accelerate/documentation/Accelerate/vImage_Buffer/data",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " property.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "For example, the following code creates a 5 x 1 ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.accelerate/documentation/Accelerate/vImage/InterleavedFx2",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " buffer that contains the pixel values ",
              "type": "text"
            },
            {
              "code": "(1, 2)",
              "type": "codeVoice"
            },
            {
              "text": ", ",
              "type": "text"
            },
            {
              "code": "(3, 4)",
              "type": "codeVoice"
            },
            {
              "text": ", ",
              "type": "text"
            },
            {
              "code": "(5, 6)",
              "type": "codeVoice"
            },
            {
              "text": ", ",
              "type": "text"
            },
            {
              "code": "(7, 8)",
              "type": "codeVoice"
            },
            {
              "text": ", and ",
              "type": "text"
            },
            {
              "code": "(9, 10)",
              "type": "codeVoice"
            },
            {
              "text": ":",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "code": [
            " let values: [Float] = [1, 2,  3, 4,  5, 6,  7, 8,  9, 10]",
            " let buffer = vImage.PixelBuffer(pixelValues: values,",
            "                                 size: vImage.Size(width: 5, height: 1),",
            "                                 pixelFormat: vImage.InterleavedFx2.self)"
          ],
          "syntax": "swift",
          "type": "codeListing"
        },
        {
          "inlineContent": [
            {
              "text": "In this case, the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.accelerate/documentation/Accelerate/vImage/PixelBuffer/rowStride",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " is ",
              "type": "text"
            },
            {
              "code": "8",
              "type": "codeVoice"
            },
            {
              "text": ". This equates to the buffer’s ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.accelerate/documentation/Accelerate/vImage_Buffer/rowBytes",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " property of ",
              "type": "text"
            },
            {
              "code": "64",
              "type": "codeVoice"
            },
            {
              "text": ".",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "Each pixel contains two 32-bit values, which is equivalent to 8 bytes per pixel, and 8 bytes per pixel multiplied by the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.accelerate/documentation/Accelerate/vImage/PixelBuffer/rowStride",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " of 8 pixels equals 64.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "anchor": "Working-with-the-underlying-row-bytes-property",
          "level": 3,
          "text": "Working with the underlying row-bytes property.",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "If you’re accessing the underlying bytes of a pixel buffer, note that the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.accelerate/documentation/Accelerate/vImage/PixelBuffer/rowStride",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "code": "*",
              "type": "codeVoice"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.accelerate/documentation/Accelerate/vImage/PixelBuffer/channelCount",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "code": "*",
              "type": "codeVoice"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.accelerate/documentation/Accelerate/StaticPixelFormat/bitCountPerPixel",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " may not correspond to the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.accelerate/documentation/Accelerate/vImage_Buffer/rowBytes",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " properly of the underlying ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.accelerate/documentation/Accelerate/vImage_Buffer",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ". This may happen when the integer row stride multiplied by the number of bytes per pixel isn’t a factor of the row bytes.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "In this case, use the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.accelerate/documentation/Accelerate/vImage/PixelBuffer/withUnsafeVImageBuffer(_:)",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " function to access the underlying vImage buffer.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "For example, the following code creates a 3-channel, 8-bit-per-channel 5 x 5 pixel buffer. The code uses the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.accelerate/documentation/Accelerate/vImage/PixelBuffer/rowStride",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " property to fill the buffer with the constant value ",
              "type": "text"
            },
            {
              "code": "99",
              "type": "codeVoice"
            },
            {
              "text": ". The pixel buffer’s underlying bytes per row is ",
              "type": "text"
            },
            {
              "code": "16",
              "type": "codeVoice"
            },
            {
              "text": ", but because the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.accelerate/documentation/Accelerate/vImage/PixelBuffer/rowStride",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " property returns ",
              "type": "text"
            },
            {
              "code": "5",
              "type": "codeVoice"
            },
            {
              "text": ", the code calculates ",
              "type": "text"
            },
            {
              "code": "5 * 3",
              "type": "codeVoice"
            },
            {
              "text": " or ",
              "type": "text"
            },
            {
              "code": "15",
              "type": "codeVoice"
            },
            {
              "text": " bytes per row. Although the code correctly calculates the ",
              "type": "text"
            },
            {
              "code": "5 * 5 * 3",
              "type": "codeVoice"
            },
            {
              "text": " elements, it doesn’t consider the row padding.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "code": [
            "let width = 5",
            "let height = 5",
            "",
            "let pixelBuffer = vImage.PixelBuffer(size: .init(width: width,",
            "                                                 height: height),",
            "                                     pixelFormat: vImage.Interleaved8x3.self)",
            "",
            "pixelBuffer.withUnsafeMutableBufferPointer { buf in",
            "    // The following calculation for `n` doesn't properly consider the row",
            "    // padding and fails to fill all the elements in `buf`.",
            "    let n = pixelBuffer.rowStride * pixelBuffer.channelCount * pixelBuffer.height",
            "    ",
            "    for i in 0 ..< n {",
            "        buf[i] = 99",
            "    }",
            "}"
          ],
          "syntax": "swift",
          "type": "codeListing"
        },
        {
          "inlineContent": [
            {
              "text": "After the loop completes, the last four elements of the pixel buffer’s ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.accelerate/documentation/Accelerate/vImage/PixelBuffer/array",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " are ",
              "type": "text"
            },
            {
              "code": "0",
              "type": "codeVoice"
            },
            {
              "text": ". For more information on how the vImage library adds additional padding to a buffer’s memory, see ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.accelerate/documentation/Accelerate/vImage_Buffer",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ".",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "The code below performs a similar loop to that above, but uses the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.accelerate/documentation/Accelerate/vImage_Buffer/rowBytes",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " property to determine the length of the loop. In this case, the code successfully fills the entire buffer with the value ",
              "type": "text"
            },
            {
              "code": "99",
              "type": "codeVoice"
            },
            {
              "text": ".",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "code": [
            "pixelBuffer.withUnsafeVImageBuffer {",
            "    // The following calculation for `n` properly considers the row",
            "    // padding and fills all the elements in `buf`.",
            "    let n = $0.rowBytes * Int($0.height)",
            "    ",
            "    let buf = UnsafeMutableBufferPointer(",
            "        start: $0.data.assumingMemoryBound(to: Pixel_8.self),",
            "        count: n )",
            "    ",
            "    for i in 0 ..< buf.count {",
            "        buf[i] = 99",
            "    }",
            "}"
          ],
          "syntax": "swift",
          "type": "codeListing"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.accelerate/documentation/Accelerate": {
      "abstract": [
        {
          "text": "Make large-scale mathematical computations and image calculations, optimized for high performance and low energy consumption.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate",
      "kind": "symbol",
      "role": "collection",
      "title": "Accelerate",
      "type": "topic",
      "url": "/documentation/accelerate"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/AccelerateBuffer": {
      "abstract": [
        {
          "text": "A type that represents an immutable buffer.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AccelerateBuffer"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/AccelerateBuffer",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AccelerateBuffer"
        }
      ],
      "role": "symbol",
      "title": "AccelerateBuffer",
      "type": "topic",
      "url": "/documentation/accelerate/acceleratebuffer"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/AccelerateMutableBuffer": {
      "abstract": [
        {
          "text": "A type that represents a mutable buffer.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AccelerateMutableBuffer"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/AccelerateMutableBuffer",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AccelerateMutableBuffer"
        }
      ],
      "role": "symbol",
      "title": "AccelerateMutableBuffer",
      "type": "topic",
      "url": "/documentation/accelerate/acceleratemutablebuffer"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/StaticPixelFormat/bitCountPerPixel": {
      "abstract": [
        {
          "text": "The number of bits allocated for a single pixel.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "bitCountPerPixel"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/StaticPixelFormat/bitCountPerPixel",
      "kind": "symbol",
      "required": true,
      "role": "symbol",
      "title": "bitCountPerPixel",
      "type": "topic",
      "url": "/documentation/accelerate/staticpixelformat/bitcountperpixel"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/vImage": {
      "abstract": [
        {
          "text": "An enumeration that acts as a namespace for Swift overlays to vImage.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "vImage"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/vImage",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "vImage"
        }
      ],
      "role": "symbol",
      "title": "vImage",
      "type": "topic",
      "url": "/documentation/accelerate/vimage"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/vImage/InterleavedFx2": {
      "abstract": [
        {
          "text": "A two-channel, 32-bit-per-channel, floating-point interleaved buffer.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "InterleavedFx2"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/vImage/InterleavedFx2",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "InterleavedFx2"
        }
      ],
      "role": "symbol",
      "title": "vImage.InterleavedFx2",
      "type": "topic",
      "url": "/documentation/accelerate/vimage/interleavedfx2"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/vImage/PixelBuffer": {
      "abstract": [
        {
          "text": "An image buffer that stores an image’s pixel data, dimensions, bit depth, and number of channels.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "PixelBuffer"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/vImage/PixelBuffer",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PixelBuffer"
        }
      ],
      "role": "symbol",
      "title": "vImage.PixelBuffer",
      "type": "topic",
      "url": "/documentation/accelerate/vimage/pixelbuffer"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/vImage/PixelBuffer/array": {
      "abstract": [
        {
          "text": "An array of ",
          "type": "text"
        },
        {
          "code": "width * height * channelCount",
          "type": "codeVoice"
        },
        {
          "text": " values that’s a copy of the buffer’s visible contents.",
          "type": "text"
        }
      ],
      "conformance": {
        "availabilityPrefix": [
          {
            "text": "Available when",
            "type": "text"
          }
        ],
        "conformancePrefix": [
          {
            "text": "Conforms when",
            "type": "text"
          }
        ],
        "constraints": [
          {
            "code": "Format",
            "type": "codeVoice"
          },
          {
            "text": " conforms to ",
            "type": "text"
          },
          {
            "code": "StaticPixelFormat",
            "type": "codeVoice"
          },
          {
            "text": ".",
            "type": "text"
          }
        ]
      },
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "array"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "typeIdentifier",
          "text": "Format"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10Accelerate11PixelFormatP13ComponentTypeQa",
          "text": "ComponentType"
        },
        {
          "kind": "text",
          "text": "]"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/vImage/PixelBuffer/array",
      "kind": "symbol",
      "role": "symbol",
      "title": "array",
      "type": "topic",
      "url": "/documentation/accelerate/vimage/pixelbuffer/array"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/vImage/PixelBuffer/byteCountPerPixel": {
      "abstract": [
        {
          "text": "Returns the number of bytes per pixel.",
          "type": "text"
        }
      ],
      "conformance": {
        "availabilityPrefix": [
          {
            "text": "Available when",
            "type": "text"
          }
        ],
        "conformancePrefix": [
          {
            "text": "Conforms when",
            "type": "text"
          }
        ],
        "constraints": [
          {
            "code": "Format",
            "type": "codeVoice"
          },
          {
            "text": " conforms to ",
            "type": "text"
          },
          {
            "code": "StaticPixelFormat",
            "type": "codeVoice"
          },
          {
            "text": ".",
            "type": "text"
          }
        ]
      },
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "byteCountPerPixel"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/vImage/PixelBuffer/byteCountPerPixel",
      "kind": "symbol",
      "role": "symbol",
      "title": "byteCountPerPixel",
      "type": "topic",
      "url": "/documentation/accelerate/vimage/pixelbuffer/bytecountperpixel"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/vImage/PixelBuffer/channelCount": {
      "abstract": [
        {
          "text": "Returns the number of channels.",
          "type": "text"
        }
      ],
      "conformance": {
        "availabilityPrefix": [
          {
            "text": "Available when",
            "type": "text"
          }
        ],
        "conformancePrefix": [
          {
            "text": "Conforms when",
            "type": "text"
          }
        ],
        "constraints": [
          {
            "code": "Format",
            "type": "codeVoice"
          },
          {
            "text": " conforms to ",
            "type": "text"
          },
          {
            "code": "StaticPixelFormat",
            "type": "codeVoice"
          },
          {
            "text": ".",
            "type": "text"
          }
        ]
      },
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "channelCount"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/vImage/PixelBuffer/channelCount",
      "kind": "symbol",
      "role": "symbol",
      "title": "channelCount",
      "type": "topic",
      "url": "/documentation/accelerate/vimage/pixelbuffer/channelcount"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/vImage/PixelBuffer/count": {
      "abstract": [
        {
          "text": "The total number of pixels multiplied by the number of channels in the buffer, including any row padding.",
          "type": "text"
        }
      ],
      "conformance": {
        "availabilityPrefix": [
          {
            "text": "Available when",
            "type": "text"
          }
        ],
        "conformancePrefix": [
          {
            "text": "Conforms when",
            "type": "text"
          }
        ],
        "constraints": [
          {
            "code": "Format",
            "type": "codeVoice"
          },
          {
            "text": " conforms to ",
            "type": "text"
          },
          {
            "code": "StaticPixelFormat",
            "type": "codeVoice"
          },
          {
            "text": ".",
            "type": "text"
          }
        ]
      },
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "count"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/vImage/PixelBuffer/count",
      "kind": "symbol",
      "role": "symbol",
      "title": "count",
      "type": "topic",
      "url": "/documentation/accelerate/vimage/pixelbuffer/count"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/vImage/PixelBuffer/height": {
      "abstract": [
        {
          "text": "The height of the pixel buffer.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "height"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/vImage/PixelBuffer/height",
      "kind": "symbol",
      "role": "symbol",
      "title": "height",
      "type": "topic",
      "url": "/documentation/accelerate/vimage/pixelbuffer/height"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/vImage/PixelBuffer/rowStride": {
      "abstract": [
        {
          "text": "The width, in pixels, of the underlying memory, including any additional row byte padding.",
          "type": "text"
        }
      ],
      "conformance": {
        "availabilityPrefix": [
          {
            "text": "Available when",
            "type": "text"
          }
        ],
        "conformancePrefix": [
          {
            "text": "Conforms when",
            "type": "text"
          }
        ],
        "constraints": [
          {
            "code": "Format",
            "type": "codeVoice"
          },
          {
            "text": " conforms to ",
            "type": "text"
          },
          {
            "code": "StaticPixelFormat",
            "type": "codeVoice"
          },
          {
            "text": ".",
            "type": "text"
          }
        ]
      },
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "rowStride"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/vImage/PixelBuffer/rowStride",
      "kind": "symbol",
      "role": "symbol",
      "title": "rowStride",
      "type": "topic",
      "url": "/documentation/accelerate/vimage/pixelbuffer/rowstride"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/vImage/PixelBuffer/size": {
      "abstract": [
        {
          "text": "The size of the pixel buffer.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "size"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10Accelerate6vImageO",
          "text": "vImage"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10Accelerate6vImageO4SizeV",
          "text": "Size"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/vImage/PixelBuffer/size",
      "kind": "symbol",
      "role": "symbol",
      "title": "size",
      "type": "topic",
      "url": "/documentation/accelerate/vimage/pixelbuffer/size"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/vImage/PixelBuffer/width": {
      "abstract": [
        {
          "text": "The width of the pixel buffer.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "width"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/vImage/PixelBuffer/width",
      "kind": "symbol",
      "role": "symbol",
      "title": "width",
      "type": "topic",
      "url": "/documentation/accelerate/vimage/pixelbuffer/width"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/vImage/PixelBuffer/withUnsafeVImageBuffer(_:)": {
      "abstract": [
        {
          "text": "Calls the given closure with the underlying vImage buffer.",
          "type": "text"
        }
      ],
      "conformance": {
        "availabilityPrefix": [
          {
            "text": "Available when",
            "type": "text"
          }
        ],
        "conformancePrefix": [
          {
            "text": "Conforms when",
            "type": "text"
          }
        ],
        "constraints": [
          {
            "code": "Format",
            "type": "codeVoice"
          },
          {
            "text": " conforms to ",
            "type": "text"
          },
          {
            "code": "SinglePlanePixelFormat",
            "type": "codeVoice"
          },
          {
            "text": ".",
            "type": "text"
          }
        ]
      },
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "withUnsafeVImageBuffer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "genericParameter",
          "text": "R"
        },
        {
          "kind": "text",
          "text": ">(("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@vImage_Buffer",
          "text": "vImage_Buffer"
        },
        {
          "kind": "text",
          "text": ") "
        },
        {
          "kind": "keyword",
          "text": "throws"
        },
        {
          "kind": "text",
          "text": " -> "
        },
        {
          "kind": "typeIdentifier",
          "text": "R"
        },
        {
          "kind": "text",
          "text": ") "
        },
        {
          "kind": "keyword",
          "text": "rethrows"
        },
        {
          "kind": "text",
          "text": " -> "
        },
        {
          "kind": "typeIdentifier",
          "text": "R"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/vImage/PixelBuffer/withUnsafeVImageBuffer(_:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "withUnsafeVImageBuffer(_:)",
      "type": "topic",
      "url": "/documentation/accelerate/vimage/pixelbuffer/withunsafevimagebuffer(_:)"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/vImage_Buffer": {
      "abstract": [
        {
          "text": "An image buffer that stores an image’s pixel data, dimensions, and row stride.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "vImage_Buffer"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/vImage_Buffer",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "vImage_Buffer"
        }
      ],
      "role": "symbol",
      "title": "vImage_Buffer",
      "type": "topic",
      "url": "/documentation/accelerate/vimage_buffer"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/vImage_Buffer/data": {
      "abstract": [
        {
          "text": "A pointer to the top-left pixel of the image.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "data"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sv",
          "text": "UnsafeMutableRawPointer"
        },
        {
          "kind": "text",
          "text": "!"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/vImage_Buffer/data",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "data"
        }
      ],
      "role": "symbol",
      "title": "data",
      "type": "topic",
      "url": "/documentation/accelerate/vimage_buffer/data"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/vImage_Buffer/rowBytes": {
      "abstract": [
        {
          "text": "The distance, in bytes, between the start of one pixel row and the next in an image, including any unused space between them.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "rowBytes"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/vImage_Buffer/rowBytes",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "rowBytes"
        }
      ],
      "role": "symbol",
      "title": "rowBytes",
      "type": "topic",
      "url": "/documentation/accelerate/vimage_buffer/rowbytes"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.externally.resolved.symbol/s:Si": {
      "abstract": [
        {
          "text": "A signed integer value type.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@frozen"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:Si",
      "kind": "symbol",
      "role": "symbol",
      "title": "Int",
      "type": "topic",
      "url": "/documentation/Swift/Int"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Inspecting-a-pixel-buffer",
      "generated": true,
      "identifiers": [
        "doc://com.apple.accelerate/documentation/Accelerate/vImage/PixelBuffer/width",
        "doc://com.apple.accelerate/documentation/Accelerate/vImage/PixelBuffer/height",
        "doc://com.apple.accelerate/documentation/Accelerate/vImage/PixelBuffer/size",
        "doc://com.apple.accelerate/documentation/Accelerate/vImage/PixelBuffer/channelCount",
        "doc://com.apple.accelerate/documentation/Accelerate/vImage/PixelBuffer/byteCountPerPixel",
        "doc://com.apple.accelerate/documentation/Accelerate/vImage/PixelBuffer/count",
        "doc://com.apple.accelerate/documentation/Accelerate/vImage/PixelBuffer/array"
      ],
      "title": "Inspecting a pixel buffer"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1vImage_Buffer~1data/title",
          "value": "data"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1vImage_Buffer~1data/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "data"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1vImage_Buffer/title",
          "value": "vImage_Buffer"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1vImage_Buffer/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "vImage_Buffer"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1vImage_Buffer/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "vImage_Buffer"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1vImage_Buffer~1rowBytes/title",
          "value": "rowBytes"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1vImage_Buffer~1rowBytes/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "rowBytes"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/accelerate/vimage/pixelbuffer/rowstride"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    }
  ]
}
