{
  "abstract": [
    {
      "text": "An attribute that stores a 16-bit signed integer value.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.coredata/documentation/CoreData",
        "doc://com.apple.coredata/documentation/CoreData/NSAttributeDescription",
        "doc://com.apple.coredata/documentation/CoreData/NSAttributeDescription/AttributeType-swift.struct"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.coredata/documentation/CoreData/NSAttributeDescription/AttributeType-swift.struct/integer16"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "extendedModule": "CoreData",
    "externalID": "s:So22NSAttributeDescriptionC8CoreDataE13AttributeTypeV9integer16AEvpZ",
    "fragments": [
      {
        "kind": "keyword",
        "text": "static"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "keyword",
        "text": "let"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "integer16"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:objc(cs)NSAttributeDescription",
        "text": "NSAttributeDescription"
      },
      {
        "kind": "text",
        "text": "."
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "s:So22NSAttributeDescriptionC8CoreDataE13AttributeTypeV",
        "text": "AttributeType"
      }
    ],
    "modules": [
      {
        "name": "Core Data"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "15.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "15.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "12.0",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "15.0",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "8.0",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Type Property",
    "symbolKind": "property",
    "title": "integer16"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "static"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "keyword",
              "text": "let"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "integer16"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.coredata/documentation/CoreData/NSAttributeDescription",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)NSAttributeDescription",
              "text": "NSAttributeDescription"
            },
            {
              "kind": "text",
              "text": "."
            },
            {
              "identifier": "doc://com.apple.coredata/documentation/CoreData/NSAttributeDescription/AttributeType-swift.struct",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:So22NSAttributeDescriptionC8CoreDataE13AttributeTypeV",
              "text": "AttributeType"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.coredata/documentation/CoreData": {
      "abstract": [
        {
          "text": "Persist or cache data on a single device, or sync data to multiple devices with CloudKit.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.coredata/documentation/CoreData",
      "kind": "symbol",
      "role": "collection",
      "title": "Core Data",
      "type": "topic",
      "url": "/documentation/coredata"
    },
    "doc://com.apple.coredata/documentation/CoreData/NSAttributeDescription": {
      "abstract": [
        {
          "text": "A description of a single attribute belonging to an entity.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSAttributeDescription"
        }
      ],
      "identifier": "doc://com.apple.coredata/documentation/CoreData/NSAttributeDescription",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSAttributeDescription"
        }
      ],
      "role": "symbol",
      "title": "NSAttributeDescription",
      "type": "topic",
      "url": "/documentation/coredata/nsattributedescription"
    },
    "doc://com.apple.coredata/documentation/CoreData/NSAttributeDescription/AttributeType-swift.struct": {
      "abstract": [
        {
          "text": "The types of attributes that Core Data supports.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AttributeType"
        }
      ],
      "identifier": "doc://com.apple.coredata/documentation/CoreData/NSAttributeDescription/AttributeType-swift.struct",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AttributeType"
        }
      ],
      "role": "symbol",
      "title": "NSAttributeDescription.AttributeType",
      "type": "topic",
      "url": "/documentation/coredata/nsattributedescription/attributetype-swift.struct"
    },
    "doc://com.apple.coredata/documentation/CoreData/NSAttributeDescription/AttributeType-swift.struct/binaryData": {
      "abstract": [
        {
          "text": "An attribute that stores binary data.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "binaryData"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSAttributeDescription",
          "text": "NSAttributeDescription"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:So22NSAttributeDescriptionC8CoreDataE13AttributeTypeV",
          "text": "AttributeType"
        }
      ],
      "identifier": "doc://com.apple.coredata/documentation/CoreData/NSAttributeDescription/AttributeType-swift.struct/binaryData",
      "kind": "symbol",
      "role": "symbol",
      "title": "binaryData",
      "type": "topic",
      "url": "/documentation/coredata/nsattributedescription/attributetype-swift.struct/binarydata"
    },
    "doc://com.apple.coredata/documentation/CoreData/NSAttributeDescription/AttributeType-swift.struct/boolean": {
      "abstract": [
        {
          "text": "An attribute that stores a Boolean value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "boolean"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSAttributeDescription",
          "text": "NSAttributeDescription"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:So22NSAttributeDescriptionC8CoreDataE13AttributeTypeV",
          "text": "AttributeType"
        }
      ],
      "identifier": "doc://com.apple.coredata/documentation/CoreData/NSAttributeDescription/AttributeType-swift.struct/boolean",
      "kind": "symbol",
      "role": "symbol",
      "title": "boolean",
      "type": "topic",
      "url": "/documentation/coredata/nsattributedescription/attributetype-swift.struct/boolean"
    },
    "doc://com.apple.coredata/documentation/CoreData/NSAttributeDescription/AttributeType-swift.struct/composite": {
      "abstract": [
        {
          "text": "An attribute that derives its value by composing other attributes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "composite"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSAttributeDescription",
          "text": "NSAttributeDescription"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:So22NSAttributeDescriptionC8CoreDataE13AttributeTypeV",
          "text": "AttributeType"
        }
      ],
      "identifier": "doc://com.apple.coredata/documentation/CoreData/NSAttributeDescription/AttributeType-swift.struct/composite",
      "kind": "symbol",
      "role": "symbol",
      "title": "composite",
      "type": "topic",
      "url": "/documentation/coredata/nsattributedescription/attributetype-swift.struct/composite"
    },
    "doc://com.apple.coredata/documentation/CoreData/NSAttributeDescription/AttributeType-swift.struct/date": {
      "abstract": [
        {
          "text": "An attribute that stores a date.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "date"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSAttributeDescription",
          "text": "NSAttributeDescription"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:So22NSAttributeDescriptionC8CoreDataE13AttributeTypeV",
          "text": "AttributeType"
        }
      ],
      "identifier": "doc://com.apple.coredata/documentation/CoreData/NSAttributeDescription/AttributeType-swift.struct/date",
      "kind": "symbol",
      "role": "symbol",
      "title": "date",
      "type": "topic",
      "url": "/documentation/coredata/nsattributedescription/attributetype-swift.struct/date"
    },
    "doc://com.apple.coredata/documentation/CoreData/NSAttributeDescription/AttributeType-swift.struct/decimal": {
      "abstract": [
        {
          "text": "An attribute that stores a decimal value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "decimal"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSAttributeDescription",
          "text": "NSAttributeDescription"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:So22NSAttributeDescriptionC8CoreDataE13AttributeTypeV",
          "text": "AttributeType"
        }
      ],
      "identifier": "doc://com.apple.coredata/documentation/CoreData/NSAttributeDescription/AttributeType-swift.struct/decimal",
      "kind": "symbol",
      "role": "symbol",
      "title": "decimal",
      "type": "topic",
      "url": "/documentation/coredata/nsattributedescription/attributetype-swift.struct/decimal"
    },
    "doc://com.apple.coredata/documentation/CoreData/NSAttributeDescription/AttributeType-swift.struct/double": {
      "abstract": [
        {
          "text": "An attribute that stores a double value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "double"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSAttributeDescription",
          "text": "NSAttributeDescription"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:So22NSAttributeDescriptionC8CoreDataE13AttributeTypeV",
          "text": "AttributeType"
        }
      ],
      "identifier": "doc://com.apple.coredata/documentation/CoreData/NSAttributeDescription/AttributeType-swift.struct/double",
      "kind": "symbol",
      "role": "symbol",
      "title": "double",
      "type": "topic",
      "url": "/documentation/coredata/nsattributedescription/attributetype-swift.struct/double"
    },
    "doc://com.apple.coredata/documentation/CoreData/NSAttributeDescription/AttributeType-swift.struct/float": {
      "abstract": [
        {
          "text": "An attribute that stores a float value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "float"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSAttributeDescription",
          "text": "NSAttributeDescription"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:So22NSAttributeDescriptionC8CoreDataE13AttributeTypeV",
          "text": "AttributeType"
        }
      ],
      "identifier": "doc://com.apple.coredata/documentation/CoreData/NSAttributeDescription/AttributeType-swift.struct/float",
      "kind": "symbol",
      "role": "symbol",
      "title": "float",
      "type": "topic",
      "url": "/documentation/coredata/nsattributedescription/attributetype-swift.struct/float"
    },
    "doc://com.apple.coredata/documentation/CoreData/NSAttributeDescription/AttributeType-swift.struct/integer16": {
      "abstract": [
        {
          "text": "An attribute that stores a 16-bit signed integer value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "integer16"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSAttributeDescription",
          "text": "NSAttributeDescription"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:So22NSAttributeDescriptionC8CoreDataE13AttributeTypeV",
          "text": "AttributeType"
        }
      ],
      "identifier": "doc://com.apple.coredata/documentation/CoreData/NSAttributeDescription/AttributeType-swift.struct/integer16",
      "kind": "symbol",
      "role": "symbol",
      "title": "integer16",
      "type": "topic",
      "url": "/documentation/coredata/nsattributedescription/attributetype-swift.struct/integer16"
    },
    "doc://com.apple.coredata/documentation/CoreData/NSAttributeDescription/AttributeType-swift.struct/integer32": {
      "abstract": [
        {
          "text": "An attribute that stores a 32-bit signed integer value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "integer32"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSAttributeDescription",
          "text": "NSAttributeDescription"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:So22NSAttributeDescriptionC8CoreDataE13AttributeTypeV",
          "text": "AttributeType"
        }
      ],
      "identifier": "doc://com.apple.coredata/documentation/CoreData/NSAttributeDescription/AttributeType-swift.struct/integer32",
      "kind": "symbol",
      "role": "symbol",
      "title": "integer32",
      "type": "topic",
      "url": "/documentation/coredata/nsattributedescription/attributetype-swift.struct/integer32"
    },
    "doc://com.apple.coredata/documentation/CoreData/NSAttributeDescription/AttributeType-swift.struct/integer64": {
      "abstract": [
        {
          "text": "An attribute that stores a 64-bit signed integer value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "integer64"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSAttributeDescription",
          "text": "NSAttributeDescription"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:So22NSAttributeDescriptionC8CoreDataE13AttributeTypeV",
          "text": "AttributeType"
        }
      ],
      "identifier": "doc://com.apple.coredata/documentation/CoreData/NSAttributeDescription/AttributeType-swift.struct/integer64",
      "kind": "symbol",
      "role": "symbol",
      "title": "integer64",
      "type": "topic",
      "url": "/documentation/coredata/nsattributedescription/attributetype-swift.struct/integer64"
    },
    "doc://com.apple.coredata/documentation/CoreData/NSAttributeDescription/AttributeType-swift.struct/objectID": {
      "abstract": [
        {
          "text": "An attribute that stores a managed object’s ID.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "objectID"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSAttributeDescription",
          "text": "NSAttributeDescription"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:So22NSAttributeDescriptionC8CoreDataE13AttributeTypeV",
          "text": "AttributeType"
        }
      ],
      "identifier": "doc://com.apple.coredata/documentation/CoreData/NSAttributeDescription/AttributeType-swift.struct/objectID",
      "kind": "symbol",
      "role": "symbol",
      "title": "objectID",
      "type": "topic",
      "url": "/documentation/coredata/nsattributedescription/attributetype-swift.struct/objectid"
    },
    "doc://com.apple.coredata/documentation/CoreData/NSAttributeDescription/AttributeType-swift.struct/string": {
      "abstract": [
        {
          "text": "An attribute that stores a string.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "string"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSAttributeDescription",
          "text": "NSAttributeDescription"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:So22NSAttributeDescriptionC8CoreDataE13AttributeTypeV",
          "text": "AttributeType"
        }
      ],
      "identifier": "doc://com.apple.coredata/documentation/CoreData/NSAttributeDescription/AttributeType-swift.struct/string",
      "kind": "symbol",
      "role": "symbol",
      "title": "string",
      "type": "topic",
      "url": "/documentation/coredata/nsattributedescription/attributetype-swift.struct/string"
    },
    "doc://com.apple.coredata/documentation/CoreData/NSAttributeDescription/AttributeType-swift.struct/transformable": {
      "abstract": [
        {
          "text": "An attribute that uses a value transformer to derive its value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "transformable"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSAttributeDescription",
          "text": "NSAttributeDescription"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:So22NSAttributeDescriptionC8CoreDataE13AttributeTypeV",
          "text": "AttributeType"
        }
      ],
      "identifier": "doc://com.apple.coredata/documentation/CoreData/NSAttributeDescription/AttributeType-swift.struct/transformable",
      "kind": "symbol",
      "role": "symbol",
      "title": "transformable",
      "type": "topic",
      "url": "/documentation/coredata/nsattributedescription/attributetype-swift.struct/transformable"
    },
    "doc://com.apple.coredata/documentation/CoreData/NSAttributeDescription/AttributeType-swift.struct/undefined": {
      "abstract": [
        {
          "text": "An attribute that doesn’t have an explicit type.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "undefined"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSAttributeDescription",
          "text": "NSAttributeDescription"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:So22NSAttributeDescriptionC8CoreDataE13AttributeTypeV",
          "text": "AttributeType"
        }
      ],
      "identifier": "doc://com.apple.coredata/documentation/CoreData/NSAttributeDescription/AttributeType-swift.struct/undefined",
      "kind": "symbol",
      "role": "symbol",
      "title": "undefined",
      "type": "topic",
      "url": "/documentation/coredata/nsattributedescription/attributetype-swift.struct/undefined"
    },
    "doc://com.apple.coredata/documentation/CoreData/NSAttributeDescription/AttributeType-swift.struct/uri": {
      "abstract": [
        {
          "text": "An attribute that stores a uniform resource identifier.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "uri"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSAttributeDescription",
          "text": "NSAttributeDescription"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:So22NSAttributeDescriptionC8CoreDataE13AttributeTypeV",
          "text": "AttributeType"
        }
      ],
      "identifier": "doc://com.apple.coredata/documentation/CoreData/NSAttributeDescription/AttributeType-swift.struct/uri",
      "kind": "symbol",
      "role": "symbol",
      "title": "uri",
      "type": "topic",
      "url": "/documentation/coredata/nsattributedescription/attributetype-swift.struct/uri"
    },
    "doc://com.apple.coredata/documentation/CoreData/NSAttributeDescription/AttributeType-swift.struct/uuid": {
      "abstract": [
        {
          "text": "An attribute that stores a universally unique identifier.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "uuid"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSAttributeDescription",
          "text": "NSAttributeDescription"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:So22NSAttributeDescriptionC8CoreDataE13AttributeTypeV",
          "text": "AttributeType"
        }
      ],
      "identifier": "doc://com.apple.coredata/documentation/CoreData/NSAttributeDescription/AttributeType-swift.struct/uuid",
      "kind": "symbol",
      "role": "symbol",
      "title": "uuid",
      "type": "topic",
      "url": "/documentation/coredata/nsattributedescription/attributetype-swift.struct/uuid"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Attribute-Types",
      "generated": true,
      "identifiers": [
        "doc://com.apple.coredata/documentation/CoreData/NSAttributeDescription/AttributeType-swift.struct/binaryData",
        "doc://com.apple.coredata/documentation/CoreData/NSAttributeDescription/AttributeType-swift.struct/boolean",
        "doc://com.apple.coredata/documentation/CoreData/NSAttributeDescription/AttributeType-swift.struct/composite",
        "doc://com.apple.coredata/documentation/CoreData/NSAttributeDescription/AttributeType-swift.struct/date",
        "doc://com.apple.coredata/documentation/CoreData/NSAttributeDescription/AttributeType-swift.struct/decimal",
        "doc://com.apple.coredata/documentation/CoreData/NSAttributeDescription/AttributeType-swift.struct/double",
        "doc://com.apple.coredata/documentation/CoreData/NSAttributeDescription/AttributeType-swift.struct/float",
        "doc://com.apple.coredata/documentation/CoreData/NSAttributeDescription/AttributeType-swift.struct/integer32",
        "doc://com.apple.coredata/documentation/CoreData/NSAttributeDescription/AttributeType-swift.struct/integer64",
        "doc://com.apple.coredata/documentation/CoreData/NSAttributeDescription/AttributeType-swift.struct/objectID",
        "doc://com.apple.coredata/documentation/CoreData/NSAttributeDescription/AttributeType-swift.struct/string",
        "doc://com.apple.coredata/documentation/CoreData/NSAttributeDescription/AttributeType-swift.struct/transformable",
        "doc://com.apple.coredata/documentation/CoreData/NSAttributeDescription/AttributeType-swift.struct/undefined",
        "doc://com.apple.coredata/documentation/CoreData/NSAttributeDescription/AttributeType-swift.struct/uri",
        "doc://com.apple.coredata/documentation/CoreData/NSAttributeDescription/AttributeType-swift.struct/uuid"
      ],
      "title": "Attribute Types"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coredata~1documentation~1CoreData~1NSAttributeDescription/title",
          "value": "NSAttributeDescription"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coredata~1documentation~1CoreData~1NSAttributeDescription/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSAttributeDescription"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coredata~1documentation~1CoreData~1NSAttributeDescription/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSAttributeDescription"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/coredata/nsattributedescription/attributetype-swift.struct/integer16"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    }
  ]
}
