{"variants":[{"paths":["/documentation/appkit/nspasteboard/pasteboardtype/string"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["/documentation/appkit/nspasteboard/pasteboardtype/string"],"traits":[{"interfaceLanguage":"occ"}]}],"sections":[],"abstract":[{"text":"String data.","type":"text"}],"hierarchy":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.appkit/documentation/AppKit","doc://com.apple.appkit/documentation/AppKit/NSPasteboard","doc://com.apple.appkit/documentation/AppKit/NSPasteboard/PasteboardType"]]},"metadata":{"externalID":"c:@NSPasteboardTypeString","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"string"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSPasteboard","text":"NSPasteboard"},{"kind":"text","text":"."},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@NSPasteboardType","text":"PasteboardType"}],"extendedModule":"AppKit","platforms":[{"name":"macOS","introducedAt":"10.6","unavailable":false,"deprecated":false,"beta":false}],"navigatorTitle":[{"kind":"identifier","text":"NSPasteboardTypeString"}],"roleHeading":"Type Property","modules":[{"name":"AppKit"}],"symbolKind":"property","title":"string","role":"symbol"},"seeAlsoSections":[{"anchor":"Pasteboard-Types","generated":true,"title":"Pasteboard Types","identifiers":["doc://com.apple.appkit/documentation/AppKit/NSPasteboard/PasteboardType/URL","doc://com.apple.appkit/documentation/AppKit/NSPasteboard/PasteboardType/collaborationMetadata","doc://com.apple.appkit/documentation/AppKit/NSPasteboard/PasteboardType/color","doc://com.apple.appkit/documentation/AppKit/NSPasteboard/PasteboardType/fileContents","doc://com.apple.appkit/documentation/AppKit/NSPasteboard/PasteboardType/fileURL","doc://com.apple.appkit/documentation/AppKit/NSPasteboard/PasteboardType/findPanelSearchOptions","doc://com.apple.appkit/documentation/AppKit/NSPasteboard/PasteboardType/font","doc://com.apple.appkit/documentation/AppKit/NSPasteboard/PasteboardType/html","doc://com.apple.appkit/documentation/AppKit/NSPasteboard/PasteboardType/multipleTextSelection","doc://com.apple.appkit/documentation/AppKit/NSPasteboard/PasteboardType/pdf","doc://com.apple.appkit/documentation/AppKit/NSPasteboard/PasteboardType/png","doc://com.apple.appkit/documentation/AppKit/NSPasteboard/PasteboardType/rtf","doc://com.apple.appkit/documentation/AppKit/NSPasteboard/PasteboardType/rtfd","doc://com.apple.appkit/documentation/AppKit/NSPasteboard/PasteboardType/ruler","doc://com.apple.appkit/documentation/AppKit/NSPasteboard/PasteboardType/sound"]}],"identifier":{"interfaceLanguage":"swift","url":"doc://com.apple.appkit/documentation/AppKit/NSPasteboard/PasteboardType/string"},"schemaVersion":{"major":0,"minor":3,"patch":0},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"string"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)NSPasteboard","kind":"typeIdentifier","identifier":"doc://com.apple.appkit/documentation/AppKit/NSPasteboard","text":"NSPasteboard"},{"kind":"text","text":"."},{"preciseIdentifier":"c:@T@NSPasteboardType","kind":"typeIdentifier","identifier":"doc://com.apple.appkit/documentation/AppKit/NSPasteboard/PasteboardType","text":"PasteboardType"}],"platforms":["macOS"]}]},{"mentions":["doc://com.apple.appkit/documentation/AppKit/supporting-writing-tools-via-the-pasteboard"],"kind":"mentions"},{"kind":"content","content":[{"text":"Discussion","anchor":"Discussion","level":2,"type":"heading"},{"inlineContent":[{"type":"text","text":"Apps that adopt App Sandbox cannot access files identified using the "},{"identifier":"doc://com.apple.appkit/documentation/AppKit/NSPasteboard/PasteboardType/string","isActive":true,"type":"reference"},{"type":"text","text":" pasteboard type. Instead, use an "},{"identifier":"doc://com.apple.documentation/documentation/foundation/nsurl","isActive":true,"type":"reference"},{"type":"text","text":" object, a bookmark, or a filename pasteboard type."}],"type":"paragraph"}]}],"kind":"symbol","references":{"doc://com.apple.appkit/documentation/AppKit/NSPasteboard/PasteboardType/rtfd":{"role":"symbol","type":"topic","title":"rtfd","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"rtfd"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)NSPasteboard","kind":"typeIdentifier","text":"NSPasteboard"},{"text":".","kind":"text"},{"preciseIdentifier":"c:@T@NSPasteboardType","text":"PasteboardType","kind":"typeIdentifier"}],"kind":"symbol","url":"/documentation/appkit/nspasteboard/pasteboardtype/rtfd","identifier":"doc://com.apple.appkit/documentation/AppKit/NSPasteboard/PasteboardType/rtfd","navigatorTitle":[{"text":"NSPasteboardTypeRTFD","kind":"identifier"}],"abstract":[{"type":"text","text":"RTFD formatted file contents."}]},"doc://com.apple.appkit/documentation/AppKit/NSPasteboard/PasteboardType/string":{"fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"string"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSPasteboard","text":"NSPasteboard"},{"kind":"text","text":"."},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@NSPasteboardType","text":"PasteboardType"}],"url":"/documentation/appkit/nspasteboard/pasteboardtype/string","type":"topic","title":"string","navigatorTitle":[{"kind":"identifier","text":"NSPasteboardTypeString"}],"kind":"symbol","abstract":[{"type":"text","text":"String data."}],"role":"symbol","identifier":"doc://com.apple.appkit/documentation/AppKit/NSPasteboard/PasteboardType/string"},"doc://com.apple.appkit/documentation/AppKit/NSPasteboard/PasteboardType/findPanelSearchOptions":{"type":"topic","title":"findPanelSearchOptions","role":"symbol","abstract":[{"type":"text","text":"Type for the find panel metadata property list."}],"kind":"symbol","identifier":"doc://com.apple.appkit/documentation/AppKit/NSPasteboard/PasteboardType/findPanelSearchOptions","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"text":"findPanelSearchOptions","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSPasteboard","text":"NSPasteboard","kind":"typeIdentifier"},{"kind":"text","text":"."},{"preciseIdentifier":"c:@T@NSPasteboardType","kind":"typeIdentifier","text":"PasteboardType"}],"url":"/documentation/appkit/nspasteboard/pasteboardtype/findpanelsearchoptions","navigatorTitle":[{"kind":"identifier","text":"NSFindPanelSearchOptionsPboardType"}]},"doc://com.apple.appkit/documentation/AppKit/NSPasteboard/PasteboardType/sound":{"role":"symbol","navigatorTitle":[{"text":"NSPasteboardTypeSound","kind":"identifier"}],"title":"sound","identifier":"doc://com.apple.appkit/documentation/AppKit/NSPasteboard/PasteboardType/sound","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"sound"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)NSPasteboard","text":"NSPasteboard","kind":"typeIdentifier"},{"text":".","kind":"text"},{"preciseIdentifier":"c:@T@NSPasteboardType","text":"PasteboardType","kind":"typeIdentifier"}],"type":"topic","url":"/documentation/appkit/nspasteboard/pasteboardtype/sound","abstract":[{"text":"Sound data.","type":"text"}],"kind":"symbol"},"doc://com.apple.documentation/documentation/technologies":{"identifier":"doc://com.apple.documentation/documentation/technologies","role":"overview","type":"topic","url":"/documentation/technologies","abstract":[{"type":"text","text":""}],"title":"Technologies","kind":"technologies"},"doc://com.apple.appkit/documentation/AppKit/NSPasteboard":{"url":"/documentation/appkit/nspasteboard","title":"NSPasteboard","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"NSPasteboard"}],"kind":"symbol","type":"topic","navigatorTitle":[{"text":"NSPasteboard","kind":"identifier"}],"identifier":"doc://com.apple.appkit/documentation/AppKit/NSPasteboard","abstract":[{"text":"An object that transfers data to and from the pasteboard server.","type":"text"}],"role":"symbol"},"doc://com.apple.appkit/documentation/AppKit/NSPasteboard/PasteboardType/multipleTextSelection":{"type":"topic","title":"multipleTextSelection","role":"symbol","abstract":[{"type":"text","text":"Multiple text selection."}],"kind":"symbol","identifier":"doc://com.apple.appkit/documentation/AppKit/NSPasteboard/PasteboardType/multipleTextSelection","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"text":"multipleTextSelection","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSPasteboard","text":"NSPasteboard","kind":"typeIdentifier"},{"text":".","kind":"text"},{"text":"PasteboardType","kind":"typeIdentifier","preciseIdentifier":"c:@T@NSPasteboardType"}],"url":"/documentation/appkit/nspasteboard/pasteboardtype/multipletextselection","navigatorTitle":[{"text":"NSPasteboardTypeMultipleTextSelection","kind":"identifier"}]},"doc://com.apple.appkit/documentation/AppKit":{"kind":"symbol","url":"/documentation/appkit","title":"AppKit","type":"topic","abstract":[{"text":"Construct and manage a graphical, event-driven user interface for your macOS app.","type":"text"}],"identifier":"doc://com.apple.appkit/documentation/AppKit","role":"collection"},"doc://com.apple.appkit/documentation/AppKit/supporting-writing-tools-via-the-pasteboard":{"type":"topic","url":"/documentation/appkit/supporting-writing-tools-via-the-pasteboard","title":"Supporting Writing Tools via the pasteboard","abstract":[{"type":"text","text":"Adopt a simplified version of the Writing Tools experience in a custom"},{"type":"text","text":" "},{"type":"text","text":"view using the pasteboard and macOS services."}],"identifier":"doc://com.apple.appkit/documentation/AppKit/supporting-writing-tools-via-the-pasteboard","kind":"article","role":"article"},"doc://com.apple.appkit/documentation/AppKit/NSPasteboard/PasteboardType/URL":{"role":"symbol","navigatorTitle":[{"text":"NSPasteboardTypeURL","kind":"identifier"}],"title":"URL","identifier":"doc://com.apple.appkit/documentation/AppKit/NSPasteboard/PasteboardType/URL","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"URL"},{"text":": ","kind":"text"},{"text":"NSPasteboard","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSPasteboard"},{"text":".","kind":"text"},{"preciseIdentifier":"c:@T@NSPasteboardType","text":"PasteboardType","kind":"typeIdentifier"}],"type":"topic","url":"/documentation/appkit/nspasteboard/pasteboardtype/url","abstract":[{"text":"URL data for one file or resource.","type":"text"}],"kind":"symbol"},"doc://com.apple.documentation/documentation/foundation/nsurl":{"abstract":[{"type":"text","text":"An object representing the location of a resource that bridges to ; use  when you need reference semantics or other Foundation-specific behavior. "}],"url":"/documentation/foundation/nsurl","fragments":[{"text":"class ","kind":"text"},{"text":"NSURL","kind":"identifier"}],"kind":"symbol","identifier":"doc://com.apple.documentation/documentation/foundation/nsurl","role":"symbol","type":"topic","title":"NSURL"},"doc://com.apple.appkit/documentation/AppKit/NSPasteboard/PasteboardType/png":{"abstract":[{"text":"PNG image data.","type":"text"}],"role":"symbol","type":"topic","navigatorTitle":[{"text":"NSPasteboardTypePNG","kind":"identifier"}],"title":"png","url":"/documentation/appkit/nspasteboard/pasteboardtype/png","kind":"symbol","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"text":"png","kind":"identifier"},{"text":": ","kind":"text"},{"text":"NSPasteboard","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSPasteboard"},{"text":".","kind":"text"},{"text":"PasteboardType","kind":"typeIdentifier","preciseIdentifier":"c:@T@NSPasteboardType"}],"identifier":"doc://com.apple.appkit/documentation/AppKit/NSPasteboard/PasteboardType/png"},"doc://com.apple.appkit/documentation/AppKit/NSPasteboard/PasteboardType/tabularText":{"type":"topic","title":"tabularText","role":"symbol","abstract":[{"type":"text","text":"Tab-separated fields of text."}],"kind":"symbol","identifier":"doc://com.apple.appkit/documentation/AppKit/NSPasteboard/PasteboardType/tabularText","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"text":"tabularText","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSPasteboard","text":"NSPasteboard","kind":"typeIdentifier"},{"text":".","kind":"text"},{"text":"PasteboardType","kind":"typeIdentifier","preciseIdentifier":"c:@T@NSPasteboardType"}],"url":"/documentation/appkit/nspasteboard/pasteboardtype/tabulartext","navigatorTitle":[{"text":"NSPasteboardTypeTabularText","kind":"identifier"}]},"doc://com.apple.appkit/documentation/AppKit/NSPasteboard/PasteboardType/pdf":{"role":"symbol","navigatorTitle":[{"text":"NSPasteboardTypePDF","kind":"identifier"}],"title":"pdf","identifier":"doc://com.apple.appkit/documentation/AppKit/NSPasteboard/PasteboardType/pdf","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"text":"pdf","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSPasteboard","text":"NSPasteboard","kind":"typeIdentifier"},{"text":".","kind":"text"},{"preciseIdentifier":"c:@T@NSPasteboardType","text":"PasteboardType","kind":"typeIdentifier"}],"type":"topic","url":"/documentation/appkit/nspasteboard/pasteboardtype/pdf","abstract":[{"text":"PDF data.","type":"text"}],"kind":"symbol"},"doc://com.apple.appkit/documentation/AppKit/NSPasteboard/PasteboardType":{"abstract":[{"text":"The supported pasteboard types.","type":"text"}],"navigatorTitle":[{"text":"PasteboardType","kind":"identifier"}],"type":"topic","identifier":"doc://com.apple.appkit/documentation/AppKit/NSPasteboard/PasteboardType","url":"/documentation/appkit/nspasteboard/pasteboardtype","kind":"symbol","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"PasteboardType","kind":"identifier"}],"role":"symbol","title":"NSPasteboard.PasteboardType"},"doc://com.apple.appkit/documentation/AppKit/NSPasteboard/PasteboardType/rtf":{"identifier":"doc://com.apple.appkit/documentation/AppKit/NSPasteboard/PasteboardType/rtf","role":"symbol","kind":"symbol","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"rtf","kind":"identifier"},{"text":": ","kind":"text"},{"text":"NSPasteboard","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSPasteboard"},{"text":".","kind":"text"},{"preciseIdentifier":"c:@T@NSPasteboardType","text":"PasteboardType","kind":"typeIdentifier"}],"url":"/documentation/appkit/nspasteboard/pasteboardtype/rtf","title":"rtf","abstract":[{"type":"text","text":"Rich Text Format (RTF) data."}],"navigatorTitle":[{"text":"NSPasteboardTypeRTF","kind":"identifier"}],"type":"topic"},"doc://com.apple.appkit/documentation/AppKit/NSPasteboard/PasteboardType/fileContents":{"abstract":[{"text":"A representation of a file’s contents.","type":"text"}],"role":"symbol","type":"topic","navigatorTitle":[{"text":"NSFileContentsPboardType","kind":"identifier"}],"title":"fileContents","url":"/documentation/appkit/nspasteboard/pasteboardtype/filecontents","kind":"symbol","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"fileContents"},{"kind":"text","text":": "},{"text":"NSPasteboard","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSPasteboard"},{"text":".","kind":"text"},{"text":"PasteboardType","kind":"typeIdentifier","preciseIdentifier":"c:@T@NSPasteboardType"}],"identifier":"doc://com.apple.appkit/documentation/AppKit/NSPasteboard/PasteboardType/fileContents"},"doc://com.apple.appkit/documentation/AppKit/NSPasteboard/PasteboardType/color":{"url":"/documentation/appkit/nspasteboard/pasteboardtype/color","navigatorTitle":[{"kind":"identifier","text":"NSPasteboardTypeColor"}],"role":"symbol","kind":"symbol","title":"color","abstract":[{"type":"text","text":"Color data."}],"fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"color","kind":"identifier"},{"text":": ","kind":"text"},{"text":"NSPasteboard","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSPasteboard"},{"kind":"text","text":"."},{"preciseIdentifier":"c:@T@NSPasteboardType","kind":"typeIdentifier","text":"PasteboardType"}],"type":"topic","identifier":"doc://com.apple.appkit/documentation/AppKit/NSPasteboard/PasteboardType/color"},"doc://com.apple.appkit/documentation/AppKit/NSPasteboard/PasteboardType/collaborationMetadata":{"identifier":"doc://com.apple.appkit/documentation/AppKit/NSPasteboard/PasteboardType/collaborationMetadata","kind":"symbol","type":"topic","role":"symbol","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"text":"collaborationMetadata","kind":"identifier"},{"text":": ","kind":"text"},{"text":"NSPasteboard","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSPasteboard"},{"text":".","kind":"text"},{"preciseIdentifier":"c:@T@NSPasteboardType","text":"PasteboardType","kind":"typeIdentifier"}],"url":"/documentation/appkit/nspasteboard/pasteboardtype/collaborationmetadata","title":"collaborationMetadata","abstract":[{"type":"text","text":"An object you use for conveying data during a collaboration."}]},"doc://com.apple.appkit/documentation/AppKit/NSPasteboard/PasteboardType/html":{"identifier":"doc://com.apple.appkit/documentation/AppKit/NSPasteboard/PasteboardType/html","role":"symbol","kind":"symbol","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"html","kind":"identifier"},{"text":": ","kind":"text"},{"text":"NSPasteboard","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSPasteboard"},{"kind":"text","text":"."},{"preciseIdentifier":"c:@T@NSPasteboardType","kind":"typeIdentifier","text":"PasteboardType"}],"url":"/documentation/appkit/nspasteboard/pasteboardtype/html","title":"html","abstract":[{"type":"text","text":"Type for HTML content."}],"navigatorTitle":[{"kind":"identifier","text":"NSPasteboardTypeHTML"}],"type":"topic"},"doc://com.apple.appkit/documentation/AppKit/NSPasteboard/PasteboardType/fileURL":{"abstract":[{"type":"text","text":"A file URL."}],"identifier":"doc://com.apple.appkit/documentation/AppKit/NSPasteboard/PasteboardType/fileURL","kind":"symbol","url":"/documentation/appkit/nspasteboard/pasteboardtype/fileurl","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"text":"fileURL","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSPasteboard","kind":"typeIdentifier","text":"NSPasteboard"},{"kind":"text","text":"."},{"preciseIdentifier":"c:@T@NSPasteboardType","kind":"typeIdentifier","text":"PasteboardType"}],"navigatorTitle":[{"text":"NSPasteboardTypeFileURL","kind":"identifier"}],"type":"topic","role":"symbol","title":"fileURL"},"doc://com.apple.appkit/documentation/AppKit/NSPasteboard/PasteboardType/font":{"abstract":[{"type":"text","text":"Font and character information."}],"identifier":"doc://com.apple.appkit/documentation/AppKit/NSPasteboard/PasteboardType/font","kind":"symbol","url":"/documentation/appkit/nspasteboard/pasteboardtype/font","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"text":"font","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSPasteboard","kind":"typeIdentifier","text":"NSPasteboard"},{"kind":"text","text":"."},{"preciseIdentifier":"c:@T@NSPasteboardType","kind":"typeIdentifier","text":"PasteboardType"}],"navigatorTitle":[{"kind":"identifier","text":"NSPasteboardTypeFont"}],"type":"topic","role":"symbol","title":"font"},"doc://com.apple.appkit/documentation/AppKit/NSPasteboard/PasteboardType/ruler":{"abstract":[{"text":"Paragraph formatting information.","type":"text"}],"role":"symbol","type":"topic","navigatorTitle":[{"text":"NSPasteboardTypeRuler","kind":"identifier"}],"title":"ruler","url":"/documentation/appkit/nspasteboard/pasteboardtype/ruler","kind":"symbol","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"ruler"},{"kind":"text","text":": "},{"text":"NSPasteboard","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSPasteboard"},{"text":".","kind":"text"},{"text":"PasteboardType","kind":"typeIdentifier","preciseIdentifier":"c:@T@NSPasteboardType"}],"identifier":"doc://com.apple.appkit/documentation/AppKit/NSPasteboard/PasteboardType/ruler"}},"variantOverrides":[{"patch":[{"op":"replace","path":"/identifier/interfaceLanguage","value":"occ"},{"op":"replace","path":"/metadata/platforms","value":[{"beta":false,"deprecated":false,"name":"macOS","unavailable":false,"introducedAt":"10.6"}]},{"op":"replace","path":"/metadata/roleHeading","value":"Global Variable"},{"op":"replace","path":"/metadata/title","value":"NSPasteboardTypeString"},{"op":"replace","path":"/metadata/symbolKind","value":"var"},{"op":"replace","path":"/metadata/fragments","value":[{"text":"NSPasteboardTypeString","kind":"identifier"}]},{"op":"replace","path":"/hierarchy","value":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.appkit/documentation/AppKit"]]}},{"op":"add","path":"/topicSections","value":null},{"op":"add","path":"/relationshipsSections","value":null},{"op":"replace","path":"/seeAlsoSections","value":[{"anchor":"Pasteboard-Types","generated":true,"title":"Pasteboard Types","identifiers":["doc://com.apple.appkit/documentation/AppKit/NSPasteboard/PasteboardType/URL","doc://com.apple.appkit/documentation/AppKit/NSPasteboard/PasteboardType/color","doc://com.apple.appkit/documentation/AppKit/NSPasteboard/PasteboardType/fileContents","doc://com.apple.appkit/documentation/AppKit/NSPasteboard/PasteboardType/fileURL","doc://com.apple.appkit/documentation/AppKit/NSPasteboard/PasteboardType/findPanelSearchOptions","doc://com.apple.appkit/documentation/AppKit/NSPasteboard/PasteboardType/font","doc://com.apple.appkit/documentation/AppKit/NSPasteboard/PasteboardType/html","doc://com.apple.appkit/documentation/AppKit/NSPasteboard/PasteboardType/multipleTextSelection","doc://com.apple.appkit/documentation/AppKit/NSPasteboard/PasteboardType/pdf","doc://com.apple.appkit/documentation/AppKit/NSPasteboard/PasteboardType/png","doc://com.apple.appkit/documentation/AppKit/NSPasteboard/PasteboardType/rtf","doc://com.apple.appkit/documentation/AppKit/NSPasteboard/PasteboardType/rtfd","doc://com.apple.appkit/documentation/AppKit/NSPasteboard/PasteboardType/ruler","doc://com.apple.appkit/documentation/AppKit/NSPasteboard/PasteboardType/sound","doc://com.apple.appkit/documentation/AppKit/NSPasteboard/PasteboardType/tabularText"]}]},{"op":"replace","path":"/primaryContentSections/0","value":{"declarations":[{"tokens":[{"kind":"keyword","text":"extern"},{"kind":"text","text":" "},{"kind":"typeIdentifier","text":"NSPasteboardType","preciseIdentifier":"c:@T@NSPasteboardType","identifier":"doc://com.apple.appkit/documentation/AppKit/NSPasteboard/PasteboardType"},{"kind":"text","text":" "},{"kind":"keyword","text":"const"},{"kind":"text","text":" "},{"kind":"identifier","text":"NSPasteboardTypeString"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["Mac Catalyst","macOS"]}],"kind":"declarations"}},{"op":"replace","value":"NSPasteboardTypeRTFD","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSPasteboard~1PasteboardType~1rtfd/title"},{"op":"replace","value":[{"text":"NSPasteboardTypeRTFD","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSPasteboard~1PasteboardType~1rtfd/fragments"},{"op":"replace","value":"NSPasteboardTypeString","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSPasteboard~1PasteboardType~1string/title"},{"value":[{"kind":"identifier","text":"NSPasteboardTypeString"}],"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSPasteboard~1PasteboardType~1string/fragments"},{"value":"NSFindPanelSearchOptionsPboardType","op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSPasteboard~1PasteboardType~1findPanelSearchOptions/title"},{"value":[{"kind":"identifier","text":"NSFindPanelSearchOptionsPboardType"}],"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSPasteboard~1PasteboardType~1findPanelSearchOptions/fragments"},{"value":"NSPasteboardTypeSound","op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSPasteboard~1PasteboardType~1sound/title"},{"value":[{"text":"NSPasteboardTypeSound","kind":"identifier"}],"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSPasteboard~1PasteboardType~1sound/fragments"},{"value":"NSPasteboard","op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSPasteboard/title"},{"value":[{"text":"NSPasteboard","kind":"identifier"}],"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSPasteboard/fragments"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSPasteboard/navigatorTitle","op":"replace","value":[{"text":"NSPasteboard","kind":"identifier"}]},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSPasteboard~1PasteboardType~1multipleTextSelection/title","op":"replace","value":"NSPasteboardTypeMultipleTextSelection"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSPasteboard~1PasteboardType~1multipleTextSelection/fragments","op":"replace","value":[{"kind":"identifier","text":"NSPasteboardTypeMultipleTextSelection"}]},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSPasteboard~1PasteboardType~1URL/title","op":"replace","value":"NSPasteboardTypeURL"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSPasteboard~1PasteboardType~1URL/fragments","op":"replace","value":[{"kind":"identifier","text":"NSPasteboardTypeURL"}]},{"path":"/references/doc:~1~1com.apple.documentation~1documentation~1foundation~1nsurl/abstract","op":"replace","value":[{"type":"text","text":"An object that represents the location of a resource, such as an item on a remote server or the path to a local file. "}]},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSPasteboard~1PasteboardType~1png/title","op":"replace","value":"NSPasteboardTypePNG"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSPasteboard~1PasteboardType~1png/fragments","op":"replace","value":[{"text":"NSPasteboardTypePNG","kind":"identifier"}]},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSPasteboard~1PasteboardType~1tabularText/title","op":"replace","value":"NSPasteboardTypeTabularText"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSPasteboard~1PasteboardType~1tabularText/fragments","op":"replace","value":[{"text":"NSPasteboardTypeTabularText","kind":"identifier"}]},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSPasteboard~1PasteboardType~1pdf/title","op":"replace","value":"NSPasteboardTypePDF"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSPasteboard~1PasteboardType~1pdf/fragments","op":"replace","value":[{"text":"NSPasteboardTypePDF","kind":"identifier"}]},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSPasteboard~1PasteboardType/title","op":"replace","value":"NSPasteboardType"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSPasteboard~1PasteboardType/fragments","op":"replace","value":[{"kind":"identifier","text":"NSPasteboardType"}]},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSPasteboard~1PasteboardType/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"NSPasteboardType"}]},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSPasteboard~1PasteboardType~1rtf/title","op":"replace","value":"NSPasteboardTypeRTF"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSPasteboard~1PasteboardType~1rtf/fragments","op":"replace","value":[{"kind":"identifier","text":"NSPasteboardTypeRTF"}]},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSPasteboard~1PasteboardType~1fileContents/title","op":"replace","value":"NSFileContentsPboardType"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSPasteboard~1PasteboardType~1fileContents/fragments","op":"replace","value":[{"kind":"identifier","text":"NSFileContentsPboardType"}]},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSPasteboard~1PasteboardType~1color/title","op":"replace","value":"NSPasteboardTypeColor"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSPasteboard~1PasteboardType~1color/fragments","op":"replace","value":[{"text":"NSPasteboardTypeColor","kind":"identifier"}]},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSPasteboard~1PasteboardType~1html/title","op":"replace","value":"NSPasteboardTypeHTML"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSPasteboard~1PasteboardType~1html/fragments","op":"replace","value":[{"kind":"identifier","text":"NSPasteboardTypeHTML"}]},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSPasteboard~1PasteboardType~1fileURL/title","op":"replace","value":"NSPasteboardTypeFileURL"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSPasteboard~1PasteboardType~1fileURL/fragments","op":"replace","value":[{"text":"NSPasteboardTypeFileURL","kind":"identifier"}]},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSPasteboard~1PasteboardType~1font/title","op":"replace","value":"NSPasteboardTypeFont"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSPasteboard~1PasteboardType~1font/fragments","op":"replace","value":[{"text":"NSPasteboardTypeFont","kind":"identifier"}]},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSPasteboard~1PasteboardType~1ruler/title","op":"replace","value":"NSPasteboardTypeRuler"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSPasteboard~1PasteboardType~1ruler/fragments","op":"replace","value":[{"text":"NSPasteboardTypeRuler","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}],"legalNotices":{"copyright":"Copyright &copy; 2025 Apple Inc. All rights reserved.","termsOfUse":"https://www.apple.com/legal/internet-services/terms/site.html","privacyPolicy":"https://www.apple.com/privacy/privacy-policy"}}