{
  "abstract": [
    {
      "text": "The point of interest category for animal services.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.mapkit/documentation/MapKit",
        "doc://com.apple.mapkit/documentation/MapKit/MKPointOfInterestCategory"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.mapkit/documentation/MapKit/MKPointOfInterestCategory/animalService"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "extendedModule": "MapKit",
    "externalID": "c:@MKPointOfInterestCategoryAnimalService",
    "fragments": [
      {
        "kind": "keyword",
        "text": "static"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "keyword",
        "text": "let"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "animalService"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@T@MKPointOfInterestCategory",
        "text": "MKPointOfInterestCategory"
      }
    ],
    "modules": [
      {
        "name": "MapKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "MKPointOfInterestCategoryAnimalService"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "18.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "18.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "18.0",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "15.0",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "18.0",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "2.0",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Type Property",
    "symbolKind": "property",
    "title": "animalService"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "static"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "keyword",
              "text": "let"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "animalService"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.mapkit/documentation/MapKit/MKPointOfInterestCategory",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@MKPointOfInterestCategory",
              "text": "MKPointOfInterestCategory"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.mapkit/documentation/MapKit": {
      "abstract": [
        {
          "text": "Display map or satellite imagery within your app, call out points of interest, and determine placemark information for map coordinates.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.mapkit/documentation/MapKit",
      "kind": "symbol",
      "role": "collection",
      "title": "MapKit",
      "type": "topic",
      "url": "/documentation/mapkit"
    },
    "doc://com.apple.mapkit/documentation/MapKit/MKPointOfInterestCategory": {
      "abstract": [
        {
          "text": "A point of interest category.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MKPointOfInterestCategory"
        }
      ],
      "identifier": "doc://com.apple.mapkit/documentation/MapKit/MKPointOfInterestCategory",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MKPointOfInterestCategory"
        }
      ],
      "role": "symbol",
      "title": "MKPointOfInterestCategory",
      "type": "topic",
      "url": "/documentation/mapkit/mkpointofinterestcategory"
    },
    "doc://com.apple.mapkit/documentation/MapKit/MKPointOfInterestCategory/animalService": {
      "abstract": [
        {
          "text": "The point of interest category for animal services.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "animalService"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@MKPointOfInterestCategory",
          "text": "MKPointOfInterestCategory"
        }
      ],
      "identifier": "doc://com.apple.mapkit/documentation/MapKit/MKPointOfInterestCategory/animalService",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MKPointOfInterestCategoryAnimalService"
        }
      ],
      "role": "symbol",
      "title": "animalService",
      "type": "topic",
      "url": "/documentation/mapkit/mkpointofinterestcategory/animalservice"
    },
    "doc://com.apple.mapkit/documentation/MapKit/MKPointOfInterestCategory/atm": {
      "abstract": [
        {
          "text": "The point of interest category for ATM machines.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "atm"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@MKPointOfInterestCategory",
          "text": "MKPointOfInterestCategory"
        }
      ],
      "identifier": "doc://com.apple.mapkit/documentation/MapKit/MKPointOfInterestCategory/atm",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MKPointOfInterestCategoryATM"
        }
      ],
      "role": "symbol",
      "title": "atm",
      "type": "topic",
      "url": "/documentation/mapkit/mkpointofinterestcategory/atm"
    },
    "doc://com.apple.mapkit/documentation/MapKit/MKPointOfInterestCategory/automotiveRepair": {
      "abstract": [
        {
          "text": "The point of interest category for automotive repair services.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "automotiveRepair"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@MKPointOfInterestCategory",
          "text": "MKPointOfInterestCategory"
        }
      ],
      "identifier": "doc://com.apple.mapkit/documentation/MapKit/MKPointOfInterestCategory/automotiveRepair",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MKPointOfInterestCategoryAutomotiveRepair"
        }
      ],
      "role": "symbol",
      "title": "automotiveRepair",
      "type": "topic",
      "url": "/documentation/mapkit/mkpointofinterestcategory/automotiverepair"
    },
    "doc://com.apple.mapkit/documentation/MapKit/MKPointOfInterestCategory/bank": {
      "abstract": [
        {
          "text": "The point of interest category for banks.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "bank"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@MKPointOfInterestCategory",
          "text": "MKPointOfInterestCategory"
        }
      ],
      "identifier": "doc://com.apple.mapkit/documentation/MapKit/MKPointOfInterestCategory/bank",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MKPointOfInterestCategoryBank"
        }
      ],
      "role": "symbol",
      "title": "bank",
      "type": "topic",
      "url": "/documentation/mapkit/mkpointofinterestcategory/bank"
    },
    "doc://com.apple.mapkit/documentation/MapKit/MKPointOfInterestCategory/beauty": {
      "abstract": [
        {
          "text": "The point of interest category for beauty services.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "beauty"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@MKPointOfInterestCategory",
          "text": "MKPointOfInterestCategory"
        }
      ],
      "identifier": "doc://com.apple.mapkit/documentation/MapKit/MKPointOfInterestCategory/beauty",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MKPointOfInterestCategoryBeauty"
        }
      ],
      "role": "symbol",
      "title": "beauty",
      "type": "topic",
      "url": "/documentation/mapkit/mkpointofinterestcategory/beauty"
    },
    "doc://com.apple.mapkit/documentation/MapKit/MKPointOfInterestCategory/evCharger": {
      "abstract": [
        {
          "text": "The point of interest category for EV chargers.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "evCharger"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@MKPointOfInterestCategory",
          "text": "MKPointOfInterestCategory"
        }
      ],
      "identifier": "doc://com.apple.mapkit/documentation/MapKit/MKPointOfInterestCategory/evCharger",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MKPointOfInterestCategoryEVCharger"
        }
      ],
      "role": "symbol",
      "title": "evCharger",
      "type": "topic",
      "url": "/documentation/mapkit/mkpointofinterestcategory/evcharger"
    },
    "doc://com.apple.mapkit/documentation/MapKit/MKPointOfInterestCategory/fitnessCenter": {
      "abstract": [
        {
          "text": "The point of interest category for fitness centers.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "fitnessCenter"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@MKPointOfInterestCategory",
          "text": "MKPointOfInterestCategory"
        }
      ],
      "identifier": "doc://com.apple.mapkit/documentation/MapKit/MKPointOfInterestCategory/fitnessCenter",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MKPointOfInterestCategoryFitnessCenter"
        }
      ],
      "role": "symbol",
      "title": "fitnessCenter",
      "type": "topic",
      "url": "/documentation/mapkit/mkpointofinterestcategory/fitnesscenter"
    },
    "doc://com.apple.mapkit/documentation/MapKit/MKPointOfInterestCategory/laundry": {
      "abstract": [
        {
          "text": "The point of interest category for laundries.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "laundry"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@MKPointOfInterestCategory",
          "text": "MKPointOfInterestCategory"
        }
      ],
      "identifier": "doc://com.apple.mapkit/documentation/MapKit/MKPointOfInterestCategory/laundry",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MKPointOfInterestCategoryLaundry"
        }
      ],
      "role": "symbol",
      "title": "laundry",
      "type": "topic",
      "url": "/documentation/mapkit/mkpointofinterestcategory/laundry"
    },
    "doc://com.apple.mapkit/documentation/MapKit/MKPointOfInterestCategory/mailbox": {
      "abstract": [
        {
          "text": "The point of interest category for mailboxes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "mailbox"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@MKPointOfInterestCategory",
          "text": "MKPointOfInterestCategory"
        }
      ],
      "identifier": "doc://com.apple.mapkit/documentation/MapKit/MKPointOfInterestCategory/mailbox",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MKPointOfInterestCategoryMailbox"
        }
      ],
      "role": "symbol",
      "title": "mailbox",
      "type": "topic",
      "url": "/documentation/mapkit/mkpointofinterestcategory/mailbox"
    },
    "doc://com.apple.mapkit/documentation/MapKit/MKPointOfInterestCategory/postOffice": {
      "abstract": [
        {
          "text": "The point of interest category for post offices.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "postOffice"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@MKPointOfInterestCategory",
          "text": "MKPointOfInterestCategory"
        }
      ],
      "identifier": "doc://com.apple.mapkit/documentation/MapKit/MKPointOfInterestCategory/postOffice",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MKPointOfInterestCategoryPostOffice"
        }
      ],
      "role": "symbol",
      "title": "postOffice",
      "type": "topic",
      "url": "/documentation/mapkit/mkpointofinterestcategory/postoffice"
    },
    "doc://com.apple.mapkit/documentation/MapKit/MKPointOfInterestCategory/restroom": {
      "abstract": [
        {
          "text": "The point of interest category for restrooms.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "restroom"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@MKPointOfInterestCategory",
          "text": "MKPointOfInterestCategory"
        }
      ],
      "identifier": "doc://com.apple.mapkit/documentation/MapKit/MKPointOfInterestCategory/restroom",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MKPointOfInterestCategoryRestroom"
        }
      ],
      "role": "symbol",
      "title": "restroom",
      "type": "topic",
      "url": "/documentation/mapkit/mkpointofinterestcategory/restroom"
    },
    "doc://com.apple.mapkit/documentation/MapKit/MKPointOfInterestCategory/spa": {
      "abstract": [
        {
          "text": "The point of interest category for spa services.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "spa"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@MKPointOfInterestCategory",
          "text": "MKPointOfInterestCategory"
        }
      ],
      "identifier": "doc://com.apple.mapkit/documentation/MapKit/MKPointOfInterestCategory/spa",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MKPointOfInterestCategorySpa"
        }
      ],
      "role": "symbol",
      "title": "spa",
      "type": "topic",
      "url": "/documentation/mapkit/mkpointofinterestcategory/spa"
    },
    "doc://com.apple.mapkit/documentation/MapKit/MKPointOfInterestCategory/store": {
      "abstract": [
        {
          "text": "The point of interest category for stores.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "store"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@MKPointOfInterestCategory",
          "text": "MKPointOfInterestCategory"
        }
      ],
      "identifier": "doc://com.apple.mapkit/documentation/MapKit/MKPointOfInterestCategory/store",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MKPointOfInterestCategoryStore"
        }
      ],
      "role": "symbol",
      "title": "store",
      "type": "topic",
      "url": "/documentation/mapkit/mkpointofinterestcategory/store"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Personal-services",
      "generated": true,
      "identifiers": [
        "doc://com.apple.mapkit/documentation/MapKit/MKPointOfInterestCategory/atm",
        "doc://com.apple.mapkit/documentation/MapKit/MKPointOfInterestCategory/automotiveRepair",
        "doc://com.apple.mapkit/documentation/MapKit/MKPointOfInterestCategory/bank",
        "doc://com.apple.mapkit/documentation/MapKit/MKPointOfInterestCategory/beauty",
        "doc://com.apple.mapkit/documentation/MapKit/MKPointOfInterestCategory/evCharger",
        "doc://com.apple.mapkit/documentation/MapKit/MKPointOfInterestCategory/fitnessCenter",
        "doc://com.apple.mapkit/documentation/MapKit/MKPointOfInterestCategory/laundry",
        "doc://com.apple.mapkit/documentation/MapKit/MKPointOfInterestCategory/mailbox",
        "doc://com.apple.mapkit/documentation/MapKit/MKPointOfInterestCategory/postOffice",
        "doc://com.apple.mapkit/documentation/MapKit/MKPointOfInterestCategory/restroom",
        "doc://com.apple.mapkit/documentation/MapKit/MKPointOfInterestCategory/spa",
        "doc://com.apple.mapkit/documentation/MapKit/MKPointOfInterestCategory/store"
      ],
      "title": "Personal services"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "18.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "18.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "18.0",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "15.0",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "18.0",
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "2.0",
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Global Variable"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "MKPointOfInterestCategoryAnimalService"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "var"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MKPointOfInterestCategoryAnimalService"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.mapkit/documentation/MapKit"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Personal-services",
              "generated": true,
              "identifiers": [
                "doc://com.apple.mapkit/documentation/MapKit/MKPointOfInterestCategory/atm",
                "doc://com.apple.mapkit/documentation/MapKit/MKPointOfInterestCategory/automotiveRepair",
                "doc://com.apple.mapkit/documentation/MapKit/MKPointOfInterestCategory/bank",
                "doc://com.apple.mapkit/documentation/MapKit/MKPointOfInterestCategory/beauty",
                "doc://com.apple.mapkit/documentation/MapKit/MKPointOfInterestCategory/evCharger",
                "doc://com.apple.mapkit/documentation/MapKit/MKPointOfInterestCategory/fitnessCenter",
                "doc://com.apple.mapkit/documentation/MapKit/MKPointOfInterestCategory/laundry",
                "doc://com.apple.mapkit/documentation/MapKit/MKPointOfInterestCategory/mailbox",
                "doc://com.apple.mapkit/documentation/MapKit/MKPointOfInterestCategory/postOffice",
                "doc://com.apple.mapkit/documentation/MapKit/MKPointOfInterestCategory/restroom",
                "doc://com.apple.mapkit/documentation/MapKit/MKPointOfInterestCategory/spa",
                "doc://com.apple.mapkit/documentation/MapKit/MKPointOfInterestCategory/store"
              ],
              "title": "Personal services"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "extern"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "identifier": "doc://com.apple.mapkit/documentation/MapKit/MKPointOfInterestCategory",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@MKPointOfInterestCategory",
                    "text": "MKPointOfInterestCategory"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "keyword",
                    "text": "const"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "MKPointOfInterestCategoryAnimalService"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKPointOfInterestCategory~1spa/title",
          "value": "MKPointOfInterestCategorySpa"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKPointOfInterestCategory~1spa/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MKPointOfInterestCategorySpa"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKPointOfInterestCategory~1postOffice/title",
          "value": "MKPointOfInterestCategoryPostOffice"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKPointOfInterestCategory~1postOffice/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MKPointOfInterestCategoryPostOffice"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKPointOfInterestCategory~1evCharger/title",
          "value": "MKPointOfInterestCategoryEVCharger"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKPointOfInterestCategory~1evCharger/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MKPointOfInterestCategoryEVCharger"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKPointOfInterestCategory~1restroom/title",
          "value": "MKPointOfInterestCategoryRestroom"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKPointOfInterestCategory~1restroom/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MKPointOfInterestCategoryRestroom"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKPointOfInterestCategory~1automotiveRepair/title",
          "value": "MKPointOfInterestCategoryAutomotiveRepair"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKPointOfInterestCategory~1automotiveRepair/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MKPointOfInterestCategoryAutomotiveRepair"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKPointOfInterestCategory~1beauty/title",
          "value": "MKPointOfInterestCategoryBeauty"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKPointOfInterestCategory~1beauty/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MKPointOfInterestCategoryBeauty"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKPointOfInterestCategory~1animalService/title",
          "value": "MKPointOfInterestCategoryAnimalService"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKPointOfInterestCategory~1animalService/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MKPointOfInterestCategoryAnimalService"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKPointOfInterestCategory~1bank/title",
          "value": "MKPointOfInterestCategoryBank"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKPointOfInterestCategory~1bank/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MKPointOfInterestCategoryBank"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKPointOfInterestCategory~1atm/title",
          "value": "MKPointOfInterestCategoryATM"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKPointOfInterestCategory~1atm/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MKPointOfInterestCategoryATM"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKPointOfInterestCategory/title",
          "value": "MKPointOfInterestCategory"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKPointOfInterestCategory/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MKPointOfInterestCategory"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKPointOfInterestCategory/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MKPointOfInterestCategory"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKPointOfInterestCategory~1store/title",
          "value": "MKPointOfInterestCategoryStore"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKPointOfInterestCategory~1store/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MKPointOfInterestCategoryStore"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKPointOfInterestCategory~1mailbox/title",
          "value": "MKPointOfInterestCategoryMailbox"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKPointOfInterestCategory~1mailbox/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MKPointOfInterestCategoryMailbox"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKPointOfInterestCategory~1fitnessCenter/title",
          "value": "MKPointOfInterestCategoryFitnessCenter"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKPointOfInterestCategory~1fitnessCenter/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MKPointOfInterestCategoryFitnessCenter"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKPointOfInterestCategory~1laundry/title",
          "value": "MKPointOfInterestCategoryLaundry"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKPointOfInterestCategory~1laundry/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MKPointOfInterestCategoryLaundry"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/mapkit/mkpointofinterestcategory/animalservice"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/mapkit/mkpointofinterestcategory/animalservice"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
