{
  "abstract": [
    {
      "text": "Constants for specifying data types for a ",
      "type": "text"
    },
    {
      "identifier": "doc://com.apple.webkit/documentation/WebKit/WKWebExtension/DataRecord",
      "isActive": true,
      "type": "reference"
    },
    {
      "text": ".",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.webkit/documentation/WebKit",
        "doc://com.apple.webkit/documentation/WebKit/WKWebExtension"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.webkit/documentation/WebKit/WKWebExtension/DataType"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "extendedModule": "WebKit",
    "externalID": "c:@T@WKWebExtensionDataType",
    "fragments": [
      {
        "kind": "keyword",
        "text": "struct"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "DataType"
      }
    ],
    "modules": [
      {
        "name": "WebKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "DataType"
      }
    ],
    "platforms": [
      {
        "beta": true,
        "deprecated": false,
        "introducedAt": "18.4",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": true,
        "deprecated": false,
        "introducedAt": "18.4",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": true,
        "deprecated": false,
        "introducedAt": "18.4",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": true,
        "deprecated": false,
        "introducedAt": "15.4",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": true,
        "deprecated": false,
        "introducedAt": "2.4",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Structure",
    "symbolKind": "struct",
    "title": "WKWebExtension.DataType"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "struct"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "DataType"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.webkit/documentation/WebKit": {
      "abstract": [
        {
          "text": "Integrate web content seamlessly into your app, and customize content interactions to meet your app’s needs.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.webkit/documentation/WebKit",
      "kind": "symbol",
      "role": "collection",
      "title": "WebKit",
      "type": "topic",
      "url": "/documentation/webkit"
    },
    "doc://com.apple.webkit/documentation/WebKit/WKWebExtension": {
      "abstract": [
        {
          "text": "An object that encapsulates a web extension’s resources that the manifest file defines.",
          "type": "text"
        }
      ],
      "beta": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "WKWebExtension"
        }
      ],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/WKWebExtension",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "WKWebExtension"
        }
      ],
      "role": "symbol",
      "title": "WKWebExtension",
      "type": "topic",
      "url": "/documentation/webkit/wkwebextension"
    },
    "doc://com.apple.webkit/documentation/WebKit/WKWebExtension/DataRecord": {
      "abstract": [
        {
          "text": "An object that represents a record of stored data for a specific web extension context.",
          "type": "text"
        }
      ],
      "beta": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "DataRecord"
        }
      ],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/WKWebExtension/DataRecord",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "DataRecord"
        }
      ],
      "role": "symbol",
      "title": "WKWebExtension.DataRecord",
      "type": "topic",
      "url": "/documentation/webkit/wkwebextension/datarecord"
    },
    "doc://com.apple.webkit/documentation/WebKit/WKWebExtension/DataType": {
      "abstract": [
        {
          "text": "Constants for specifying data types for a ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.webkit/documentation/WebKit/WKWebExtension/DataRecord",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": ".",
          "type": "text"
        }
      ],
      "beta": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "DataType"
        }
      ],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/WKWebExtension/DataType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "DataType"
        }
      ],
      "role": "symbol",
      "title": "WKWebExtension.DataType",
      "type": "topic",
      "url": "/documentation/webkit/wkwebextension/datatype"
    },
    "doc://com.apple.webkit/documentation/WebKit/WKWebExtension/DataType/init(rawValue:)": {
      "abstract": [
        {
          "text": "Creates a data type from a raw value you provide.",
          "type": "text"
        }
      ],
      "beta": true,
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "rawValue"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/WKWebExtension/DataType/init(rawValue:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "init(rawValue:)",
      "type": "topic",
      "url": "/documentation/webkit/wkwebextension/datatype/init(rawvalue:)"
    },
    "doc://com.apple.webkit/documentation/WebKit/WKWebExtension/DataType/local": {
      "abstract": [
        {
          "text": "Specifies local storage, including ",
          "type": "text"
        },
        {
          "code": "browser.storage.local",
          "type": "codeVoice"
        },
        {
          "text": ".",
          "type": "text"
        }
      ],
      "beta": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "local"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)WKWebExtension",
          "text": "WKWebExtension"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@WKWebExtensionDataType",
          "text": "DataType"
        }
      ],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/WKWebExtension/DataType/local",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "WKWebExtensionDataTypeLocal"
        }
      ],
      "role": "symbol",
      "title": "local",
      "type": "topic",
      "url": "/documentation/webkit/wkwebextension/datatype/local"
    },
    "doc://com.apple.webkit/documentation/WebKit/WKWebExtension/DataType/session": {
      "abstract": [
        {
          "text": "Specifies session storage, including ",
          "type": "text"
        },
        {
          "code": "browser.storage.session",
          "type": "codeVoice"
        },
        {
          "text": ".",
          "type": "text"
        }
      ],
      "beta": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "session"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)WKWebExtension",
          "text": "WKWebExtension"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@WKWebExtensionDataType",
          "text": "DataType"
        }
      ],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/WKWebExtension/DataType/session",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "WKWebExtensionDataTypeSession"
        }
      ],
      "role": "symbol",
      "title": "session",
      "type": "topic",
      "url": "/documentation/webkit/wkwebextension/datatype/session"
    },
    "doc://com.apple.webkit/documentation/WebKit/WKWebExtension/DataType/synchronized": {
      "abstract": [
        {
          "text": "Specifies synchronized storage, including ",
          "type": "text"
        },
        {
          "code": "browser.storage.sync",
          "type": "codeVoice"
        },
        {
          "text": ".",
          "type": "text"
        }
      ],
      "beta": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "synchronized"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)WKWebExtension",
          "text": "WKWebExtension"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@WKWebExtensionDataType",
          "text": "DataType"
        }
      ],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/WKWebExtension/DataType/synchronized",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "WKWebExtensionDataTypeSynchronized"
        }
      ],
      "role": "symbol",
      "title": "synchronized",
      "type": "topic",
      "url": "/documentation/webkit/wkwebextension/datatype/synchronized"
    },
    "doc://com.apple.webkit/documentation/WebKit/WKWebExtension/Error": {
      "abstract": [
        {
          "text": "Constants that indicate errors in the ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.webkit/documentation/WebKit/WKWebExtension",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " domain.",
          "type": "text"
        }
      ],
      "beta": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Error"
        }
      ],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/WKWebExtension/Error",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "Error"
        }
      ],
      "role": "symbol",
      "title": "WKWebExtension.Error",
      "type": "topic",
      "url": "/documentation/webkit/wkwebextension/error"
    },
    "doc://com.apple.webkit/documentation/WebKit/WKWebExtension/Permission": {
      "abstract": [
        {
          "text": "Constants for specifying permission in a ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.webkit/documentation/WebKit/WKWebExtensionContext",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": ".",
          "type": "text"
        }
      ],
      "beta": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Permission"
        }
      ],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/WKWebExtension/Permission",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "Permission"
        }
      ],
      "role": "symbol",
      "title": "WKWebExtension.Permission",
      "type": "topic",
      "url": "/documentation/webkit/wkwebextension/permission"
    },
    "doc://com.apple.webkit/documentation/WebKit/WKWebExtension/TabChangedProperties": {
      "abstract": [
        {
          "text": "Constants the web extension controller and web extension context use to indicate tab changes.",
          "type": "text"
        }
      ],
      "beta": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "TabChangedProperties"
        }
      ],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/WKWebExtension/TabChangedProperties",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "TabChangedProperties"
        }
      ],
      "role": "symbol",
      "title": "WKWebExtension.TabChangedProperties",
      "type": "topic",
      "url": "/documentation/webkit/wkwebextension/tabchangedproperties"
    },
    "doc://com.apple.webkit/documentation/WebKit/WKWebExtensionContext": {
      "abstract": [
        {
          "text": "An object that represents the runtime environment for a web extension.",
          "type": "text"
        }
      ],
      "beta": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "WKWebExtensionContext"
        }
      ],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/WKWebExtensionContext",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "WKWebExtensionContext"
        }
      ],
      "role": "symbol",
      "title": "WKWebExtensionContext",
      "type": "topic",
      "url": "/documentation/webkit/wkwebextensioncontext"
    },
    "doc://com.externally.resolved.symbol/c:objc(cs)NSString": {
      "abstract": [
        {
          "text": "A static, plain-text Unicode string object which you use when you need reference semantics or other Foundation-specific behavior. ",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "class "
        },
        {
          "kind": "identifier",
          "text": "NSString"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSString",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSString",
      "type": "topic",
      "url": "/documentation/foundation/nsstring"
    },
    "doc://com.externally.resolved.symbol/s:SH": {
      "abstract": [
        {
          "text": "A type that can be hashed into a `Hasher` to produce an integer hash value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Hashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SQ",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SH",
      "kind": "symbol",
      "role": "symbol",
      "title": "Hashable",
      "type": "topic",
      "url": "/documentation/Swift/Hashable"
    },
    "doc://com.externally.resolved.symbol/s:SQ": {
      "abstract": [
        {
          "text": "A type that can be compared for value equality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SQ",
      "kind": "symbol",
      "role": "symbol",
      "title": "Equatable",
      "type": "topic",
      "url": "/documentation/Swift/Equatable"
    },
    "doc://com.externally.resolved.symbol/s:SY": {
      "abstract": [
        {
          "text": "A type that can be converted to and from an associated raw value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "RawRepresentable"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SY8RawValueQa",
          "text": "RawValue"
        },
        {
          "kind": "text",
          "text": ">"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SY",
      "kind": "symbol",
      "role": "symbol",
      "title": "RawRepresentable",
      "type": "topic",
      "url": "/documentation/Swift/RawRepresentable"
    },
    "doc://com.externally.resolved.symbol/s:s8SendableP": {
      "abstract": [
        {
          "text": "A thread-safe type whose values can be shared across arbitrary concurrent contexts without introducing a risk of data races.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Sendable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s8SendableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "Sendable",
      "type": "topic",
      "url": "/documentation/Swift/Sendable"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:SQ",
        "doc://com.externally.resolved.symbol/s:SH",
        "doc://com.externally.resolved.symbol/s:SY",
        "doc://com.externally.resolved.symbol/s:s8SendableP"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Structures",
      "generated": true,
      "identifiers": [
        "doc://com.apple.webkit/documentation/WebKit/WKWebExtension/Error",
        "doc://com.apple.webkit/documentation/WebKit/WKWebExtension/Permission",
        "doc://com.apple.webkit/documentation/WebKit/WKWebExtension/TabChangedProperties"
      ],
      "title": "Structures"
    }
  ],
  "topicSections": [
    {
      "anchor": "Constants",
      "identifiers": [
        "doc://com.apple.webkit/documentation/WebKit/WKWebExtension/DataType/local",
        "doc://com.apple.webkit/documentation/WebKit/WKWebExtension/DataType/session",
        "doc://com.apple.webkit/documentation/WebKit/WKWebExtension/DataType/synchronized"
      ],
      "title": "Constants"
    },
    {
      "anchor": "Initializers",
      "generated": true,
      "identifiers": [
        "doc://com.apple.webkit/documentation/WebKit/WKWebExtension/DataType/init(rawValue:)"
      ],
      "title": "Initializers"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": true,
              "deprecated": false,
              "introducedAt": "18.4",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": true,
              "deprecated": false,
              "introducedAt": "18.4",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": true,
              "deprecated": false,
              "introducedAt": "18.4",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": true,
              "deprecated": false,
              "introducedAt": "15.4",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": true,
              "deprecated": false,
              "introducedAt": "2.4",
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Type Alias"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "WKWebExtensionDataType"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "typealias"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "WKWebExtensionDataType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "WKWebExtensionDataType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.webkit/documentation/WebKit"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Constants",
              "identifiers": [
                "doc://com.apple.webkit/documentation/WebKit/WKWebExtension/DataType/local",
                "doc://com.apple.webkit/documentation/WebKit/WKWebExtension/DataType/session",
                "doc://com.apple.webkit/documentation/WebKit/WKWebExtension/DataType/synchronized"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Type-Aliases",
              "generated": true,
              "identifiers": [
                "doc://com.apple.webkit/documentation/WebKit/WKWebExtension/Permission"
              ],
              "title": "Type Aliases"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "visionOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "typedef"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSString",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(cs)NSString",
                    "text": "NSString"
                  },
                  {
                    "kind": "text",
                    "text": " * "
                  },
                  {
                    "kind": "identifier",
                    "text": "WKWebExtensionDataType"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WKWebExtensionContext/title",
          "value": "WKWebExtensionContext"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WKWebExtensionContext/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "WKWebExtensionContext"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WKWebExtensionContext/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "WKWebExtensionContext"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WKWebExtension/title",
          "value": "WKWebExtension"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WKWebExtension/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "WKWebExtension"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WKWebExtension/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "WKWebExtension"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WKWebExtension~1DataType~1local/title",
          "value": "WKWebExtensionDataTypeLocal"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WKWebExtension~1DataType~1local/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "WKWebExtensionDataTypeLocal"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WKWebExtension~1Permission/title",
          "value": "WKWebExtensionPermission"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WKWebExtension~1Permission/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "WKWebExtensionPermission"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WKWebExtension~1Permission/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "WKWebExtensionPermission"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:objc(cs)NSString/abstract",
          "value": [
            {
              "text": "A static, plain-text Unicode string object.",
              "type": "text"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WKWebExtension~1TabChangedProperties/title",
          "value": "WKWebExtensionTabChangedProperties"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WKWebExtension~1TabChangedProperties/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "WKWebExtensionTabChangedProperties"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WKWebExtension~1TabChangedProperties/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "WKWebExtensionTabChangedProperties"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WKWebExtension~1DataType~1session/title",
          "value": "WKWebExtensionDataTypeSession"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WKWebExtension~1DataType~1session/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "WKWebExtensionDataTypeSession"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WKWebExtension~1DataType~1synchronized/title",
          "value": "WKWebExtensionDataTypeSynchronized"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WKWebExtension~1DataType~1synchronized/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "WKWebExtensionDataTypeSynchronized"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WKWebExtension~1DataRecord/title",
          "value": "WKWebExtensionDataRecord"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WKWebExtension~1DataRecord/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "WKWebExtensionDataRecord"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WKWebExtension~1DataRecord/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "WKWebExtensionDataRecord"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WKWebExtension~1DataType/title",
          "value": "WKWebExtensionDataType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WKWebExtension~1DataType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "WKWebExtensionDataType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WKWebExtension~1DataType/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "WKWebExtensionDataType"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/webkit/wkwebextension/datatype"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/webkit/wkwebextension/datatype"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
