{
  "abstract": [
    {
      "text": "An object that represents a way to specify groups of URLs.",
      "type": "text"
    }
  ],
  "diffAvailability": {
    "major": {
      "change": "added",
      "platform": "Xcode",
      "versions": [
        "16.0",
        "16.3 beta 2"
      ]
    },
    "minor": {
      "change": "added",
      "platform": "Xcode",
      "versions": [
        "16.2",
        "16.3 beta 2"
      ]
    }
  },
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.webkit/documentation/WebKit",
        "doc://com.apple.webkit/documentation/WebKit/WKWebExtension"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.webkit/documentation/WebKit/WKWebExtension/MatchPattern"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "extendedModule": "WebKit",
    "externalID": "c:objc(cs)WKWebExtensionMatchPattern",
    "fragments": [
      {
        "kind": "keyword",
        "text": "class"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "MatchPattern"
      }
    ],
    "modules": [
      {
        "name": "WebKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "MatchPattern"
      }
    ],
    "platforms": [
      {
        "beta": true,
        "deprecated": false,
        "introducedAt": "18.4",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": true,
        "deprecated": false,
        "introducedAt": "18.4",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": true,
        "deprecated": false,
        "introducedAt": "18.4",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": true,
        "deprecated": false,
        "introducedAt": "15.4",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": true,
        "deprecated": false,
        "introducedAt": "2.4",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Class",
    "symbolKind": "class",
    "title": "WKWebExtension.MatchPattern"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "attribute",
              "text": "@"
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:ScM",
              "kind": "attribute",
              "preciseIdentifier": "s:ScM",
              "text": "MainActor"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "keyword",
              "text": "class"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "MatchPattern"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "All match patterns are specified as strings. Apart from the special ",
              "type": "text"
            },
            {
              "code": "<all_urls>",
              "type": "codeVoice"
            },
            {
              "text": " pattern, match patterns",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "consist of three parts: scheme, host, and path.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.webkit/documentation/WebKit": {
      "abstract": [
        {
          "text": "Integrate web content seamlessly into your app, and customize content interactions to meet your app’s needs.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.webkit/documentation/WebKit",
      "kind": "symbol",
      "role": "collection",
      "title": "WebKit",
      "type": "topic",
      "url": "/documentation/webkit"
    },
    "doc://com.apple.webkit/documentation/WebKit/WKWebExtension": {
      "abstract": [
        {
          "text": "An object that encapsulates a web extension’s resources that the manifest file defines.",
          "type": "text"
        }
      ],
      "beta": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "WKWebExtension"
        }
      ],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/WKWebExtension",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "WKWebExtension"
        }
      ],
      "role": "symbol",
      "title": "WKWebExtension",
      "type": "topic",
      "url": "/documentation/webkit/wkwebextension"
    },
    "doc://com.apple.webkit/documentation/WebKit/WKWebExtension/Action": {
      "abstract": [
        {
          "text": "An object that encapsulates the properties for an individual web extension action.",
          "type": "text"
        }
      ],
      "beta": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Action"
        }
      ],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/WKWebExtension/Action",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "Action"
        }
      ],
      "role": "symbol",
      "title": "WKWebExtension.Action",
      "type": "topic",
      "url": "/documentation/webkit/wkwebextension/action"
    },
    "doc://com.apple.webkit/documentation/WebKit/WKWebExtension/Command": {
      "abstract": [
        {
          "text": "An object that encapsulates the properties for an individual web extension command.",
          "type": "text"
        }
      ],
      "beta": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Command"
        }
      ],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/WKWebExtension/Command",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "Command"
        }
      ],
      "role": "symbol",
      "title": "WKWebExtension.Command",
      "type": "topic",
      "url": "/documentation/webkit/wkwebextension/command"
    },
    "doc://com.apple.webkit/documentation/WebKit/WKWebExtension/DataRecord": {
      "abstract": [
        {
          "text": "An object that represents a record of stored data for a specific web extension context.",
          "type": "text"
        }
      ],
      "beta": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "DataRecord"
        }
      ],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/WKWebExtension/DataRecord",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "DataRecord"
        }
      ],
      "role": "symbol",
      "title": "WKWebExtension.DataRecord",
      "type": "topic",
      "url": "/documentation/webkit/wkwebextension/datarecord"
    },
    "doc://com.apple.webkit/documentation/WebKit/WKWebExtension/MatchPattern": {
      "abstract": [
        {
          "text": "An object that represents a way to specify groups of URLs.",
          "type": "text"
        }
      ],
      "beta": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MatchPattern"
        }
      ],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/WKWebExtension/MatchPattern",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MatchPattern"
        }
      ],
      "role": "symbol",
      "title": "WKWebExtension.MatchPattern",
      "type": "topic",
      "url": "/documentation/webkit/wkwebextension/matchpattern"
    },
    "doc://com.apple.webkit/documentation/WebKit/WKWebExtension/MatchPattern/Error": {
      "abstract": [
        {
          "text": "Constants that indicate errors in the ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.webkit/documentation/WebKit/WKWebExtension/MatchPattern",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " domain.",
          "type": "text"
        }
      ],
      "beta": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Error"
        }
      ],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/WKWebExtension/MatchPattern/Error",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "Error"
        }
      ],
      "role": "symbol",
      "title": "WKWebExtension.MatchPattern.Error",
      "type": "topic",
      "url": "/documentation/webkit/wkwebextension/matchpattern/error"
    },
    "doc://com.apple.webkit/documentation/WebKit/WKWebExtension/MatchPattern/Error/Code": {
      "abstract": [
        {
          "text": "Constants that indicate errors in the ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.webkit/documentation/WebKit/WKWebExtension/MatchPattern",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " domain.",
          "type": "text"
        }
      ],
      "beta": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/WKWebExtension/MatchPattern/Error/Code",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "Code"
        }
      ],
      "role": "symbol",
      "title": "WKWebExtension.MatchPattern.Error.Code",
      "type": "topic",
      "url": "/documentation/webkit/wkwebextension/matchpattern/error/code"
    },
    "doc://com.apple.webkit/documentation/WebKit/WKWebExtension/MatchPattern/Options": {
      "abstract": [
        {
          "text": "Constants used by ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.webkit/documentation/WebKit/WKWebExtension/MatchPattern",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " to indicate matching options.",
          "type": "text"
        }
      ],
      "beta": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Options"
        }
      ],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/WKWebExtension/MatchPattern/Options",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "Options"
        }
      ],
      "role": "symbol",
      "title": "WKWebExtension.MatchPattern.Options",
      "type": "topic",
      "url": "/documentation/webkit/wkwebextension/matchpattern/options"
    },
    "doc://com.apple.webkit/documentation/WebKit/WKWebExtension/MatchPattern/allHostsAndSchemes()": {
      "abstract": [
        {
          "text": "Returns a pattern object that has ",
          "type": "text"
        },
        {
          "code": "*",
          "type": "codeVoice"
        },
        {
          "text": " for scheme, host, and path.",
          "type": "text"
        }
      ],
      "beta": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "allHostsAndSchemes"
        },
        {
          "kind": "text",
          "text": "() -> "
        },
        {
          "kind": "typeIdentifier",
          "text": "Self"
        }
      ],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/WKWebExtension/MatchPattern/allHostsAndSchemes()",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "allHostsAndSchemesMatchPattern"
        }
      ],
      "role": "symbol",
      "title": "allHostsAndSchemes()",
      "type": "topic",
      "url": "/documentation/webkit/wkwebextension/matchpattern/allhostsandschemes()"
    },
    "doc://com.apple.webkit/documentation/WebKit/WKWebExtension/MatchPattern/allURLs()": {
      "abstract": [
        {
          "text": "Returns a pattern object for ",
          "type": "text"
        },
        {
          "code": "<all_urls>",
          "type": "codeVoice"
        },
        {
          "text": ".",
          "type": "text"
        }
      ],
      "beta": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "allURLs"
        },
        {
          "kind": "text",
          "text": "() -> "
        },
        {
          "kind": "typeIdentifier",
          "text": "Self"
        }
      ],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/WKWebExtension/MatchPattern/allURLs()",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "allURLsMatchPattern"
        }
      ],
      "role": "symbol",
      "title": "allURLs()",
      "type": "topic",
      "url": "/documentation/webkit/wkwebextension/matchpattern/allurls()"
    },
    "doc://com.apple.webkit/documentation/WebKit/WKWebExtension/MatchPattern/errorDomain": {
      "abstract": [
        {
          "text": "A string that identifies the error domain.",
          "type": "text"
        }
      ],
      "beta": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "errorDomain"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/WKWebExtension/MatchPattern/errorDomain",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "WKWebExtensionMatchPatternErrorDomain"
        }
      ],
      "role": "symbol",
      "title": "errorDomain",
      "type": "topic",
      "url": "/documentation/webkit/wkwebextension/matchpattern/errordomain"
    },
    "doc://com.apple.webkit/documentation/WebKit/WKWebExtension/MatchPattern/host": {
      "abstract": [
        {
          "text": "The host part of the pattern string, unless ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.webkit/documentation/WebKit/WKWebExtension/MatchPattern/matchesAllURLs",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " is ",
          "type": "text"
        },
        {
          "code": "YES",
          "type": "codeVoice"
        },
        {
          "text": ".",
          "type": "text"
        }
      ],
      "beta": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "host"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/WKWebExtension/MatchPattern/host",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "host"
        }
      ],
      "role": "symbol",
      "title": "host",
      "type": "topic",
      "url": "/documentation/webkit/wkwebextension/matchpattern/host"
    },
    "doc://com.apple.webkit/documentation/WebKit/WKWebExtension/MatchPattern/init(scheme:host:path:)": {
      "abstract": [
        {
          "text": "Returns a pattern object for the specified scheme, host, and path strings.",
          "type": "text"
        }
      ],
      "beta": true,
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "scheme"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "host"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "path"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": ") "
        },
        {
          "kind": "keyword",
          "text": "throws"
        }
      ],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/WKWebExtension/MatchPattern/init(scheme:host:path:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "initWithScheme:host:path:error:"
        }
      ],
      "role": "symbol",
      "title": "init(scheme:host:path:)",
      "type": "topic",
      "url": "/documentation/webkit/wkwebextension/matchpattern/init(scheme:host:path:)"
    },
    "doc://com.apple.webkit/documentation/WebKit/WKWebExtension/MatchPattern/init(string:)": {
      "abstract": [
        {
          "text": "Returns a pattern object for the specified pattern string.",
          "type": "text"
        }
      ],
      "beta": true,
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "string"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": ") "
        },
        {
          "kind": "keyword",
          "text": "throws"
        }
      ],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/WKWebExtension/MatchPattern/init(string:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "initWithString:error:"
        }
      ],
      "role": "symbol",
      "title": "init(string:)",
      "type": "topic",
      "url": "/documentation/webkit/wkwebextension/matchpattern/init(string:)"
    },
    "doc://com.apple.webkit/documentation/WebKit/WKWebExtension/MatchPattern/matches(_:)-471rf": {
      "abstract": [
        {
          "text": "Matches the receiver pattern against the specified URL.",
          "type": "text"
        }
      ],
      "beta": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "matches"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10Foundation3URLV",
          "text": "URL"
        },
        {
          "kind": "text",
          "text": "?) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/WKWebExtension/MatchPattern/matches(_:)-471rf",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "matchesURL:"
        }
      ],
      "role": "symbol",
      "title": "matches(_:)",
      "type": "topic",
      "url": "/documentation/webkit/wkwebextension/matchpattern/matches(_:)-471rf"
    },
    "doc://com.apple.webkit/documentation/WebKit/WKWebExtension/MatchPattern/matches(_:)-4d84f": {
      "abstract": [
        {
          "text": "Matches the receiver pattern against the specified pattern.",
          "type": "text"
        }
      ],
      "beta": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "matches"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)WKWebExtension",
          "text": "WKWebExtension"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)WKWebExtensionMatchPattern",
          "text": "MatchPattern"
        },
        {
          "kind": "text",
          "text": "?) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/WKWebExtension/MatchPattern/matches(_:)-4d84f",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "matchesPattern:"
        }
      ],
      "role": "symbol",
      "title": "matches(_:)",
      "type": "topic",
      "url": "/documentation/webkit/wkwebextension/matchpattern/matches(_:)-4d84f"
    },
    "doc://com.apple.webkit/documentation/WebKit/WKWebExtension/MatchPattern/matches(_:options:)-5wo3g": {
      "abstract": [
        {
          "text": "Matches the receiver pattern against the specified URL with options.",
          "type": "text"
        }
      ],
      "beta": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "matches"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10Foundation3URLV",
          "text": "URL"
        },
        {
          "kind": "text",
          "text": "?, "
        },
        {
          "kind": "externalParam",
          "text": "options"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)WKWebExtension",
          "text": "WKWebExtension"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)WKWebExtensionMatchPattern",
          "text": "MatchPattern"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@WKWebExtensionMatchPatternOptions",
          "text": "Options"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/WKWebExtension/MatchPattern/matches(_:options:)-5wo3g",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "matchesURL:options:"
        }
      ],
      "role": "symbol",
      "title": "matches(_:options:)",
      "type": "topic",
      "url": "/documentation/webkit/wkwebextension/matchpattern/matches(_:options:)-5wo3g"
    },
    "doc://com.apple.webkit/documentation/WebKit/WKWebExtension/MatchPattern/matches(_:options:)-fnde": {
      "abstract": [
        {
          "text": "Matches the receiver pattern against the specified pattern with options.",
          "type": "text"
        }
      ],
      "beta": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "matches"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)WKWebExtension",
          "text": "WKWebExtension"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)WKWebExtensionMatchPattern",
          "text": "MatchPattern"
        },
        {
          "kind": "text",
          "text": "?, "
        },
        {
          "kind": "externalParam",
          "text": "options"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)WKWebExtension",
          "text": "WKWebExtension"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)WKWebExtensionMatchPattern",
          "text": "MatchPattern"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@WKWebExtensionMatchPatternOptions",
          "text": "Options"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/WKWebExtension/MatchPattern/matches(_:options:)-fnde",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "matchesPattern:options:"
        }
      ],
      "role": "symbol",
      "title": "matches(_:options:)",
      "type": "topic",
      "url": "/documentation/webkit/wkwebextension/matchpattern/matches(_:options:)-fnde"
    },
    "doc://com.apple.webkit/documentation/WebKit/WKWebExtension/MatchPattern/matchesAllHosts": {
      "abstract": [
        {
          "text": "A Boolean value that indicates if the pattern is ",
          "type": "text"
        },
        {
          "code": "<all_urls>",
          "type": "codeVoice"
        },
        {
          "text": " or has ",
          "type": "text"
        },
        {
          "code": "*",
          "type": "codeVoice"
        },
        {
          "text": " as the host.",
          "type": "text"
        }
      ],
      "beta": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "matchesAllHosts"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/WKWebExtension/MatchPattern/matchesAllHosts",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "matchesAllHosts"
        }
      ],
      "role": "symbol",
      "title": "matchesAllHosts",
      "type": "topic",
      "url": "/documentation/webkit/wkwebextension/matchpattern/matchesallhosts"
    },
    "doc://com.apple.webkit/documentation/WebKit/WKWebExtension/MatchPattern/matchesAllURLs": {
      "abstract": [
        {
          "text": "A Boolean value that indicates if the pattern is ",
          "type": "text"
        },
        {
          "code": "<all_urls>",
          "type": "codeVoice"
        },
        {
          "text": ".",
          "type": "text"
        }
      ],
      "beta": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "matchesAllURLs"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/WKWebExtension/MatchPattern/matchesAllURLs",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "matchesAllURLs"
        }
      ],
      "role": "symbol",
      "title": "matchesAllURLs",
      "type": "topic",
      "url": "/documentation/webkit/wkwebextension/matchpattern/matchesallurls"
    },
    "doc://com.apple.webkit/documentation/WebKit/WKWebExtension/MatchPattern/path": {
      "abstract": [
        {
          "text": "The path part of the pattern string, unless ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.webkit/documentation/WebKit/WKWebExtension/MatchPattern/matchesAllURLs",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " is ",
          "type": "text"
        },
        {
          "code": "YES",
          "type": "codeVoice"
        },
        {
          "text": ".",
          "type": "text"
        }
      ],
      "beta": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "path"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/WKWebExtension/MatchPattern/path",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "path"
        }
      ],
      "role": "symbol",
      "title": "path",
      "type": "topic",
      "url": "/documentation/webkit/wkwebextension/matchpattern/path"
    },
    "doc://com.apple.webkit/documentation/WebKit/WKWebExtension/MatchPattern/registerCustomURLScheme(_:)": {
      "abstract": [
        {
          "text": "Registers a custom URL scheme that can be used in match patterns.",
          "type": "text"
        }
      ],
      "beta": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "registerCustomURLScheme"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/WKWebExtension/MatchPattern/registerCustomURLScheme(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "registerCustomURLScheme:"
        }
      ],
      "role": "symbol",
      "title": "registerCustomURLScheme(_:)",
      "type": "topic",
      "url": "/documentation/webkit/wkwebextension/matchpattern/registercustomurlscheme(_:)"
    },
    "doc://com.apple.webkit/documentation/WebKit/WKWebExtension/MatchPattern/scheme": {
      "abstract": [
        {
          "text": "The scheme part of the pattern string, unless ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.webkit/documentation/WebKit/WKWebExtension/MatchPattern/matchesAllURLs",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " is ",
          "type": "text"
        },
        {
          "code": "YES",
          "type": "codeVoice"
        },
        {
          "text": ".",
          "type": "text"
        }
      ],
      "beta": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "scheme"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/WKWebExtension/MatchPattern/scheme",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "scheme"
        }
      ],
      "role": "symbol",
      "title": "scheme",
      "type": "topic",
      "url": "/documentation/webkit/wkwebextension/matchpattern/scheme"
    },
    "doc://com.apple.webkit/documentation/WebKit/WKWebExtension/MatchPattern/string": {
      "abstract": [
        {
          "text": "The original pattern string.",
          "type": "text"
        }
      ],
      "beta": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "string"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/WKWebExtension/MatchPattern/string",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "string"
        }
      ],
      "role": "symbol",
      "title": "string",
      "type": "topic",
      "url": "/documentation/webkit/wkwebextension/matchpattern/string"
    },
    "doc://com.apple.webkit/documentation/WebKit/WKWebExtension/MessagePort": {
      "abstract": [
        {
          "text": "An object that manages message-based communication with a web extension.",
          "type": "text"
        }
      ],
      "beta": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MessagePort"
        }
      ],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/WKWebExtension/MessagePort",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MessagePort"
        }
      ],
      "role": "symbol",
      "title": "WKWebExtension.MessagePort",
      "type": "topic",
      "url": "/documentation/webkit/wkwebextension/messageport"
    },
    "doc://com.apple.webkit/documentation/WebKit/WKWebExtension/TabConfiguration": {
      "abstract": [
        {
          "text": "An object that encapsulates configuration options for a tab in an extension.",
          "type": "text"
        }
      ],
      "beta": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "TabConfiguration"
        }
      ],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/WKWebExtension/TabConfiguration",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "TabConfiguration"
        }
      ],
      "role": "symbol",
      "title": "WKWebExtension.TabConfiguration",
      "type": "topic",
      "url": "/documentation/webkit/wkwebextension/tabconfiguration"
    },
    "doc://com.apple.webkit/documentation/WebKit/WKWebExtension/WindowConfiguration": {
      "abstract": [
        {
          "text": "An object that encapsulates configuration options for a window in an extension.",
          "type": "text"
        }
      ],
      "beta": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "WindowConfiguration"
        }
      ],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/WKWebExtension/WindowConfiguration",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "WindowConfiguration"
        }
      ],
      "role": "symbol",
      "title": "WKWebExtension.WindowConfiguration",
      "type": "topic",
      "url": "/documentation/webkit/wkwebextension/windowconfiguration"
    },
    "doc://com.apple.webkit/documentation/WebKit/WKWebExtensionController/Configuration-swift.class": {
      "abstract": [
        {
          "text": "A ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.webkit/documentation/WebKit/WKWebExtensionController/Configuration-swift.class",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " object with which to initialize a web extension controller.",
          "type": "text"
        }
      ],
      "beta": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Configuration"
        }
      ],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/WKWebExtensionController/Configuration-swift.class",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "Configuration"
        }
      ],
      "role": "symbol",
      "title": "WKWebExtensionController.Configuration",
      "type": "topic",
      "url": "/documentation/webkit/wkwebextensioncontroller/configuration-swift.class"
    },
    "doc://com.apple.webkit/documentation/WebKit/WKWebExtensionMatchPattern/matchPatternWithScheme:host:path:": {
      "abstract": [
        {
          "text": "Returns a pattern object for the specified scheme, host, and path strings.",
          "type": "text"
        }
      ],
      "beta": true,
      "fragments": [
        {
          "kind": "text",
          "text": "+ "
        },
        {
          "kind": "identifier",
          "text": "matchPatternWithScheme:host:path:"
        }
      ],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/WKWebExtensionMatchPattern/matchPatternWithScheme:host:path:",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "matchPatternWithScheme:host:path:"
        }
      ],
      "role": "symbol",
      "title": "matchPatternWithScheme:host:path:",
      "type": "topic",
      "url": "/documentation/webkit/wkwebextensionmatchpattern/matchpatternwithscheme:host:path:"
    },
    "doc://com.apple.webkit/documentation/WebKit/WKWebExtensionMatchPattern/matchPatternWithString:": {
      "abstract": [
        {
          "text": "Returns a pattern object for the specified pattern string.",
          "type": "text"
        }
      ],
      "beta": true,
      "fragments": [
        {
          "kind": "text",
          "text": "+ "
        },
        {
          "kind": "identifier",
          "text": "matchPatternWithString:"
        }
      ],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/WKWebExtensionMatchPattern/matchPatternWithString:",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "matchPatternWithString:"
        }
      ],
      "role": "symbol",
      "title": "matchPatternWithString:",
      "type": "topic",
      "url": "/documentation/webkit/wkwebextensionmatchpattern/matchpatternwithstring:"
    },
    "doc://com.externally.resolved.symbol/c:objc(cs)NSObject": {
      "abstract": [
        {
          "text": "The root class of most Objective-C class hierarchies, from which subclasses inherit a basic interface to the runtime system and the ability to behave as Objective-C objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "class "
        },
        {
          "kind": "identifier",
          "text": "NSObject"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSObject",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSObject",
      "type": "topic",
      "url": "/documentation/objectivec/nsobject"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)NSCoding": {
      "abstract": [
        {
          "text": "A protocol that enables an object to be encoded and decoded for archiving and distribution.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "protocol "
        },
        {
          "kind": "identifier",
          "text": "NSCoding"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSCoding",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSCoding",
      "type": "topic",
      "url": "/documentation/foundation/nscoding"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)NSCopying": {
      "abstract": [
        {
          "text": "A protocol that objects adopt to provide functional copies of themselves.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "protocol "
        },
        {
          "kind": "identifier",
          "text": "NSCopying"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSCopying",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSCopying",
      "type": "topic",
      "url": "/documentation/foundation/nscopying"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)NSObject": {
      "abstract": [
        {
          "text": "The group of methods that are fundamental to all Objective-C objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "protocol "
        },
        {
          "kind": "identifier",
          "text": "NSObjectProtocol"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSObject",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSObjectProtocol",
      "type": "topic",
      "url": "/documentation/objectivec/nsobjectprotocol"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)NSSecureCoding": {
      "abstract": [
        {
          "text": "A protocol that enables encoding and decoding in a manner that is robust against object substitution attacks.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "protocol "
        },
        {
          "kind": "identifier",
          "text": "NSSecureCoding"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSSecureCoding",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSSecureCoding",
      "type": "topic",
      "url": "/documentation/foundation/nssecurecoding"
    },
    "doc://com.externally.resolved.symbol/s:SH": {
      "abstract": [
        {
          "text": "A type that can be hashed into a `Hasher` to produce an integer hash value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Hashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SQ",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SH",
      "kind": "symbol",
      "role": "symbol",
      "title": "Hashable",
      "type": "topic",
      "url": "/documentation/Swift/Hashable"
    },
    "doc://com.externally.resolved.symbol/s:SQ": {
      "abstract": [
        {
          "text": "A type that can be compared for value equality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SQ",
      "kind": "symbol",
      "role": "symbol",
      "title": "Equatable",
      "type": "topic",
      "url": "/documentation/Swift/Equatable"
    },
    "doc://com.externally.resolved.symbol/s:ScM": {
      "abstract": [
        {
          "text": "A singleton actor whose executor is equivalent to the main dispatch queue.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@globalActor"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "final"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "actor"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MainActor"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:ScM",
      "kind": "symbol",
      "role": "symbol",
      "title": "MainActor",
      "type": "topic",
      "url": "/documentation/Swift/MainActor"
    },
    "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP": {
      "abstract": [
        {
          "text": "A type with a customized textual representation.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CustomStringConvertible"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CustomStringConvertible",
      "type": "topic",
      "url": "/documentation/Swift/CustomStringConvertible"
    },
    "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP": {
      "abstract": [
        {
          "text": "A type with a customized textual representation suitable for debugging purposes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CustomDebugStringConvertible"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CustomDebugStringConvertible",
      "type": "topic",
      "url": "/documentation/Swift/CustomDebugStringConvertible"
    },
    "doc://com.externally.resolved.symbol/s:s7CVarArgP": {
      "abstract": [
        {
          "text": "A type whose instances can be encoded, and appropriately passed, as elements of a C `va_list`.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CVarArg"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s7CVarArgP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CVarArg",
      "type": "topic",
      "url": "/documentation/Swift/CVarArg"
    },
    "doc://com.externally.resolved.symbol/s:s8SendableP": {
      "abstract": [
        {
          "text": "A thread-safe type whose values can be shared across arbitrary concurrent contexts without introducing a risk of data races.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Sendable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s8SendableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "Sendable",
      "type": "topic",
      "url": "/documentation/Swift/Sendable"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/c:objc(cs)NSObject"
      ],
      "kind": "relationships",
      "title": "Inherits From",
      "type": "inheritsFrom"
    },
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:s7CVarArgP",
        "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP",
        "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP",
        "doc://com.externally.resolved.symbol/s:SQ",
        "doc://com.externally.resolved.symbol/s:SH",
        "doc://com.externally.resolved.symbol/c:objc(pl)NSCoding",
        "doc://com.externally.resolved.symbol/c:objc(pl)NSCopying",
        "doc://com.externally.resolved.symbol/c:objc(pl)NSObject",
        "doc://com.externally.resolved.symbol/c:objc(pl)NSSecureCoding",
        "doc://com.externally.resolved.symbol/s:s8SendableP"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Classes",
      "generated": true,
      "identifiers": [
        "doc://com.apple.webkit/documentation/WebKit/WKWebExtension/Action",
        "doc://com.apple.webkit/documentation/WebKit/WKWebExtension/Command",
        "doc://com.apple.webkit/documentation/WebKit/WKWebExtension/DataRecord",
        "doc://com.apple.webkit/documentation/WebKit/WKWebExtension/MessagePort",
        "doc://com.apple.webkit/documentation/WebKit/WKWebExtension/TabConfiguration",
        "doc://com.apple.webkit/documentation/WebKit/WKWebExtension/WindowConfiguration",
        "doc://com.apple.webkit/documentation/WebKit/WKWebExtensionController/Configuration-swift.class"
      ],
      "title": "Classes"
    }
  ],
  "topicSections": [
    {
      "anchor": "Errors",
      "identifiers": [
        "doc://com.apple.webkit/documentation/WebKit/WKWebExtension/MatchPattern/Error",
        "doc://com.apple.webkit/documentation/WebKit/WKWebExtension/MatchPattern/Error/Code",
        "doc://com.apple.webkit/documentation/WebKit/WKWebExtension/MatchPattern/errorDomain"
      ],
      "title": "Errors"
    },
    {
      "anchor": "Structures",
      "identifiers": [
        "doc://com.apple.webkit/documentation/WebKit/WKWebExtension/MatchPattern/Options"
      ],
      "title": "Structures"
    },
    {
      "anchor": "Initializers",
      "generated": true,
      "identifiers": [
        "doc://com.apple.webkit/documentation/WebKit/WKWebExtension/MatchPattern/init(scheme:host:path:)",
        "doc://com.apple.webkit/documentation/WebKit/WKWebExtension/MatchPattern/init(string:)"
      ],
      "title": "Initializers"
    },
    {
      "anchor": "Instance-Properties",
      "generated": true,
      "identifiers": [
        "doc://com.apple.webkit/documentation/WebKit/WKWebExtension/MatchPattern/host",
        "doc://com.apple.webkit/documentation/WebKit/WKWebExtension/MatchPattern/matchesAllHosts",
        "doc://com.apple.webkit/documentation/WebKit/WKWebExtension/MatchPattern/matchesAllURLs",
        "doc://com.apple.webkit/documentation/WebKit/WKWebExtension/MatchPattern/path",
        "doc://com.apple.webkit/documentation/WebKit/WKWebExtension/MatchPattern/scheme",
        "doc://com.apple.webkit/documentation/WebKit/WKWebExtension/MatchPattern/string"
      ],
      "title": "Instance Properties"
    },
    {
      "anchor": "Instance-Methods",
      "generated": true,
      "identifiers": [
        "doc://com.apple.webkit/documentation/WebKit/WKWebExtension/MatchPattern/matches(_:)-471rf",
        "doc://com.apple.webkit/documentation/WebKit/WKWebExtension/MatchPattern/matches(_:)-4d84f",
        "doc://com.apple.webkit/documentation/WebKit/WKWebExtension/MatchPattern/matches(_:options:)-5wo3g",
        "doc://com.apple.webkit/documentation/WebKit/WKWebExtension/MatchPattern/matches(_:options:)-fnde"
      ],
      "title": "Instance Methods"
    },
    {
      "anchor": "Type-Methods",
      "generated": true,
      "identifiers": [
        "doc://com.apple.webkit/documentation/WebKit/WKWebExtension/MatchPattern/allHostsAndSchemes()",
        "doc://com.apple.webkit/documentation/WebKit/WKWebExtension/MatchPattern/allURLs()",
        "doc://com.apple.webkit/documentation/WebKit/WKWebExtension/MatchPattern/registerCustomURLScheme(_:)"
      ],
      "title": "Type Methods"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": true,
              "deprecated": false,
              "introducedAt": "18.4",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": true,
              "deprecated": false,
              "introducedAt": "18.4",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": true,
              "deprecated": false,
              "introducedAt": "18.4",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": true,
              "deprecated": false,
              "introducedAt": "15.4",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": true,
              "deprecated": false,
              "introducedAt": "2.4",
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Class"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "WKWebExtensionMatchPattern"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "class"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "WKWebExtensionMatchPattern"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "WKWebExtensionMatchPattern"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.webkit/documentation/WebKit"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Errors",
              "identifiers": [
                "doc://com.apple.webkit/documentation/WebKit/WKWebExtension/MatchPattern/Error/Code",
                "doc://com.apple.webkit/documentation/WebKit/WKWebExtension/MatchPattern/errorDomain"
              ],
              "title": "Errors"
            },
            {
              "anchor": "Enumerations",
              "identifiers": [
                "doc://com.apple.webkit/documentation/WebKit/WKWebExtension/MatchPattern/Options"
              ],
              "title": "Enumerations"
            },
            {
              "anchor": "Instance-Properties",
              "generated": true,
              "identifiers": [
                "doc://com.apple.webkit/documentation/WebKit/WKWebExtension/MatchPattern/host",
                "doc://com.apple.webkit/documentation/WebKit/WKWebExtension/MatchPattern/matchesAllHosts",
                "doc://com.apple.webkit/documentation/WebKit/WKWebExtension/MatchPattern/matchesAllURLs",
                "doc://com.apple.webkit/documentation/WebKit/WKWebExtension/MatchPattern/path",
                "doc://com.apple.webkit/documentation/WebKit/WKWebExtension/MatchPattern/scheme",
                "doc://com.apple.webkit/documentation/WebKit/WKWebExtension/MatchPattern/string"
              ],
              "title": "Instance Properties"
            },
            {
              "anchor": "Instance-Methods",
              "generated": true,
              "identifiers": [
                "doc://com.apple.webkit/documentation/WebKit/WKWebExtension/MatchPattern/init(scheme:host:path:)",
                "doc://com.apple.webkit/documentation/WebKit/WKWebExtension/MatchPattern/init(string:)",
                "doc://com.apple.webkit/documentation/WebKit/WKWebExtension/MatchPattern/matches(_:)-471rf",
                "doc://com.apple.webkit/documentation/WebKit/WKWebExtension/MatchPattern/matches(_:)-4d84f",
                "doc://com.apple.webkit/documentation/WebKit/WKWebExtension/MatchPattern/matches(_:options:)-5wo3g",
                "doc://com.apple.webkit/documentation/WebKit/WKWebExtension/MatchPattern/matches(_:options:)-fnde"
              ],
              "title": "Instance Methods"
            },
            {
              "anchor": "Type-Methods",
              "generated": true,
              "identifiers": [
                "doc://com.apple.webkit/documentation/WebKit/WKWebExtension/MatchPattern/allHostsAndSchemes()",
                "doc://com.apple.webkit/documentation/WebKit/WKWebExtension/MatchPattern/allURLs()",
                "doc://com.apple.webkit/documentation/WebKit/WKWebExtension/MatchPattern/registerCustomURLScheme(_:)",
                "doc://com.apple.webkit/documentation/WebKit/WKWebExtensionMatchPattern/matchPatternWithScheme:host:path:",
                "doc://com.apple.webkit/documentation/WebKit/WKWebExtensionMatchPattern/matchPatternWithString:"
              ],
              "title": "Type Methods"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": [
            {
              "identifiers": [
                "doc://com.externally.resolved.symbol/c:objc(cs)NSObject"
              ],
              "kind": "relationships",
              "title": "Inherits From",
              "type": "inheritsFrom"
            },
            {
              "identifiers": [
                "doc://com.externally.resolved.symbol/c:objc(pl)NSCopying",
                "doc://com.externally.resolved.symbol/c:objc(pl)NSSecureCoding"
              ],
              "kind": "relationships",
              "title": "Conforms To",
              "type": "conformsTo"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Classes",
              "generated": true,
              "identifiers": [
                "doc://com.apple.webkit/documentation/WebKit/WKWebExtension/Action",
                "doc://com.apple.webkit/documentation/WebKit/WKWebExtension/Command",
                "doc://com.apple.webkit/documentation/WebKit/WKWebExtension/DataRecord",
                "doc://com.apple.webkit/documentation/WebKit/WKWebExtension/MessagePort",
                "doc://com.apple.webkit/documentation/WebKit/WKWebExtension/TabConfiguration",
                "doc://com.apple.webkit/documentation/WebKit/WKWebExtension/WindowConfiguration",
                "doc://com.apple.webkit/documentation/WebKit/WKWebExtensionController/Configuration-swift.class"
              ],
              "title": "Classes"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "visionOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "@interface"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "WKWebExtensionMatchPattern"
                  },
                  {
                    "kind": "text",
                    "text": " : "
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSObject",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(cs)NSObject",
                    "text": "NSObject"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WKWebExtension~1MatchPattern~1allHostsAndSchemes()/title",
          "value": "allHostsAndSchemesMatchPattern"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WKWebExtension~1MatchPattern~1allHostsAndSchemes()/fragments",
          "value": [
            {
              "kind": "text",
              "text": "+ "
            },
            {
              "kind": "identifier",
              "text": "allHostsAndSchemesMatchPattern"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WKWebExtension/title",
          "value": "WKWebExtension"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WKWebExtension/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "WKWebExtension"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WKWebExtension/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "WKWebExtension"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WKWebExtension~1MatchPattern~1Error~1Code/title",
          "value": "WKWebExtensionMatchPatternError"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WKWebExtension~1MatchPattern~1Error~1Code/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "WKWebExtensionMatchPatternError"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WKWebExtension~1MatchPattern~1Error~1Code/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "WKWebExtensionMatchPatternError"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WKWebExtension~1Action/title",
          "value": "WKWebExtensionAction"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WKWebExtension~1Action/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "WKWebExtensionAction"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WKWebExtension~1Action/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "WKWebExtensionAction"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WKWebExtensionController~1Configuration-swift.class/title",
          "value": "WKWebExtensionControllerConfiguration"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WKWebExtensionController~1Configuration-swift.class/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "WKWebExtensionControllerConfiguration"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WKWebExtensionController~1Configuration-swift.class/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "WKWebExtensionControllerConfiguration"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WKWebExtension~1MatchPattern~1matches(_:)-471rf/title",
          "value": "matchesURL:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WKWebExtension~1MatchPattern~1matches(_:)-471rf/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "matchesURL:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WKWebExtension~1MatchPattern~1host/title",
          "value": "host"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WKWebExtension~1MatchPattern~1host/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "host"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WKWebExtension~1MatchPattern~1errorDomain/title",
          "value": "WKWebExtensionMatchPatternErrorDomain"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WKWebExtension~1MatchPattern~1errorDomain/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "WKWebExtensionMatchPatternErrorDomain"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WKWebExtension~1Command/title",
          "value": "WKWebExtensionCommand"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WKWebExtension~1Command/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "WKWebExtensionCommand"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WKWebExtension~1Command/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "WKWebExtensionCommand"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WKWebExtension~1MatchPattern~1string/title",
          "value": "string"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WKWebExtension~1MatchPattern~1string/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "string"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WKWebExtension~1MatchPattern~1registerCustomURLScheme(_:)/title",
          "value": "registerCustomURLScheme:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WKWebExtension~1MatchPattern~1registerCustomURLScheme(_:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "+ "
            },
            {
              "kind": "identifier",
              "text": "registerCustomURLScheme:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WKWebExtension~1MatchPattern~1matches(_:)-4d84f/title",
          "value": "matchesPattern:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WKWebExtension~1MatchPattern~1matches(_:)-4d84f/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "matchesPattern:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WKWebExtension~1MatchPattern~1matchesAllHosts/title",
          "value": "matchesAllHosts"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WKWebExtension~1MatchPattern~1matchesAllHosts/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "matchesAllHosts"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WKWebExtension~1TabConfiguration/title",
          "value": "WKWebExtensionTabConfiguration"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WKWebExtension~1TabConfiguration/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "WKWebExtensionTabConfiguration"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WKWebExtension~1TabConfiguration/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "WKWebExtensionTabConfiguration"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WKWebExtension~1MatchPattern~1scheme/title",
          "value": "scheme"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WKWebExtension~1MatchPattern~1scheme/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "scheme"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WKWebExtension~1DataRecord/title",
          "value": "WKWebExtensionDataRecord"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WKWebExtension~1DataRecord/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "WKWebExtensionDataRecord"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WKWebExtension~1DataRecord/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "WKWebExtensionDataRecord"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WKWebExtension~1MatchPattern~1init(string:)/title",
          "value": "initWithString:error:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WKWebExtension~1MatchPattern~1init(string:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "initWithString:error:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WKWebExtension~1MatchPattern~1allURLs()/title",
          "value": "allURLsMatchPattern"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WKWebExtension~1MatchPattern~1allURLs()/fragments",
          "value": [
            {
              "kind": "text",
              "text": "+ "
            },
            {
              "kind": "identifier",
              "text": "allURLsMatchPattern"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WKWebExtension~1MatchPattern~1matches(_:options:)-fnde/title",
          "value": "matchesPattern:options:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WKWebExtension~1MatchPattern~1matches(_:options:)-fnde/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "matchesPattern:options:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WKWebExtension~1MatchPattern~1path/title",
          "value": "path"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WKWebExtension~1MatchPattern~1path/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "path"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:objc(pl)NSObject/title",
          "value": "NSObject"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WKWebExtension~1MatchPattern~1init(scheme:host:path:)/title",
          "value": "initWithScheme:host:path:error:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WKWebExtension~1MatchPattern~1init(scheme:host:path:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "initWithScheme:host:path:error:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WKWebExtension~1MatchPattern~1Options/title",
          "value": "WKWebExtensionMatchPatternOptions"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WKWebExtension~1MatchPattern~1Options/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "WKWebExtensionMatchPatternOptions"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WKWebExtension~1MatchPattern~1Options/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "WKWebExtensionMatchPatternOptions"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WKWebExtension~1MatchPattern~1matchesAllURLs/title",
          "value": "matchesAllURLs"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WKWebExtension~1MatchPattern~1matchesAllURLs/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "matchesAllURLs"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WKWebExtension~1WindowConfiguration/title",
          "value": "WKWebExtensionWindowConfiguration"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WKWebExtension~1WindowConfiguration/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "WKWebExtensionWindowConfiguration"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WKWebExtension~1WindowConfiguration/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "WKWebExtensionWindowConfiguration"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WKWebExtension~1MatchPattern/title",
          "value": "WKWebExtensionMatchPattern"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WKWebExtension~1MatchPattern/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "WKWebExtensionMatchPattern"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WKWebExtension~1MatchPattern/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "WKWebExtensionMatchPattern"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WKWebExtension~1MatchPattern~1matches(_:options:)-5wo3g/title",
          "value": "matchesURL:options:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WKWebExtension~1MatchPattern~1matches(_:options:)-5wo3g/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "matchesURL:options:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WKWebExtension~1MessagePort/title",
          "value": "WKWebExtensionMessagePort"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WKWebExtension~1MessagePort/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "WKWebExtensionMessagePort"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WKWebExtension~1MessagePort/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "WKWebExtensionMessagePort"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/webkit/wkwebextension/matchpattern"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/webkit/wkwebextension/matchpattern"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
