{
  "abstract": [
    {
      "text": "Installs a message handler that returns a reply to your JavaScript code.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.webkit/documentation/WebKit",
        "doc://com.apple.webkit/documentation/WebKit/WKUserContentController"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.webkit/documentation/WebKit/WKUserContentController/addScriptMessageHandler(_:contentWorld:name:)"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(cs)WKUserContentController(im)addScriptMessageHandlerWithReply:contentWorld:name:",
    "fragments": [
      {
        "kind": "keyword",
        "text": "func"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "addScriptMessageHandler"
      },
      {
        "kind": "text",
        "text": "(any "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:objc(pl)WKScriptMessageHandlerWithReply",
        "text": "WKScriptMessageHandlerWithReply"
      },
      {
        "kind": "text",
        "text": ", "
      },
      {
        "kind": "externalParam",
        "text": "contentWorld"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:objc(cs)WKContentWorld",
        "text": "WKContentWorld"
      },
      {
        "kind": "text",
        "text": ", "
      },
      {
        "kind": "externalParam",
        "text": "name"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "s:SS",
        "text": "String"
      },
      {
        "kind": "text",
        "text": ")"
      }
    ],
    "modules": [
      {
        "name": "WebKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "addScriptMessageHandlerWithReply:contentWorld:name:"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "14.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "14.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "14.0",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "11.0",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Instance Method",
    "symbolKind": "method",
    "title": "addScriptMessageHandler(_:contentWorld:name:)"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "attribute",
              "text": "@"
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:ScM",
              "kind": "attribute",
              "preciseIdentifier": "s:ScM",
              "text": "MainActor"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "keyword",
              "text": "func"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "addScriptMessageHandler"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "kind": "externalParam",
              "text": "_"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "scriptMessageHandlerWithReply"
            },
            {
              "kind": "text",
              "text": ": any "
            },
            {
              "identifier": "doc://com.apple.webkit/documentation/WebKit/WKScriptMessageHandlerWithReply",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(pl)WKScriptMessageHandlerWithReply",
              "text": "WKScriptMessageHandlerWithReply"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "kind": "externalParam",
              "text": "contentWorld"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.webkit/documentation/WebKit/WKContentWorld",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)WKContentWorld",
              "text": "WKContentWorld"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "kind": "externalParam",
              "text": "name"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:SS",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:SS",
              "text": "String"
            },
            {
              "kind": "text",
              "text": ")"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "kind": "parameters",
      "parameters": [
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "The message handler object that implements your custom code. This object must adopt the ",
                  "type": "text"
                },
                {
                  "identifier": "doc://com.apple.webkit/documentation/WebKit/WKScriptMessageHandlerWithReply",
                  "isActive": true,
                  "type": "reference"
                },
                {
                  "text": " protocol.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "scriptMessageHandlerWithReply"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "The content world in which to install the message handler. Use the content world to scope your message handler to specific parts of your JavaScript code.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "contentWorld"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "The name of the message handler. This parameter must be unique within the user content controller and must not be an empty string.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            },
            {
              "inlineContent": [
                {
                  "text": "The user content controller uses this parameter to define a JavaScript function for your message handler in all frames in the specified content world. The name of this function is ",
                  "type": "text"
                },
                {
                  "code": "window.webkit.messageHandlers.",
                  "type": "codeVoice"
                },
                {
                  "inlineContent": [],
                  "type": "emphasis"
                },
                {
                  "code": ".postMessage(<messageBody>)",
                  "type": "codeVoice"
                },
                {
                  "text": ", where ",
                  "type": "text"
                },
                {
                  "inlineContent": [],
                  "type": "emphasis"
                },
                {
                  "text": " corresponds to the value of this parameter.  For example, if you specify the string ",
                  "type": "text"
                },
                {
                  "code": "MyFunction",
                  "type": "codeVoice"
                },
                {
                  "text": ", the user content controller defines the ",
                  "type": "text"
                },
                {
                  "code": "window.webkit.messageHandlers.MyFunction.postMessage()",
                  "type": "codeVoice"
                },
                {
                  "text": " function in JavaScript.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "name"
        }
      ]
    },
    {
      "content": [
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "To execute your handler’s code, call the JavaScript function that this method defines. You may pass a parameter value to the method. The user content controller packages that value into an appropriate type and delivers it to your content handler’s delegate method.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.webkit/documentation/WebKit": {
      "abstract": [
        {
          "text": "Integrate web content seamlessly into your app, and customize content interactions to meet your app’s needs.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.webkit/documentation/WebKit",
      "kind": "symbol",
      "role": "collection",
      "title": "WebKit",
      "type": "topic",
      "url": "/documentation/webkit"
    },
    "doc://com.apple.webkit/documentation/WebKit/WKContentWorld": {
      "abstract": [
        {
          "text": "An object that defines a scope of execution for JavaScript code, and which you use to prevent conflicts between different scripts.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "WKContentWorld"
        }
      ],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/WKContentWorld",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "WKContentWorld"
        }
      ],
      "role": "symbol",
      "title": "WKContentWorld",
      "type": "topic",
      "url": "/documentation/webkit/wkcontentworld"
    },
    "doc://com.apple.webkit/documentation/WebKit/WKScriptMessageHandler": {
      "abstract": [
        {
          "text": "An interface for receiving messages from JavaScript code running in a webpage.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "WKScriptMessageHandler"
        }
      ],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/WKScriptMessageHandler",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "WKScriptMessageHandler"
        }
      ],
      "role": "symbol",
      "title": "WKScriptMessageHandler",
      "type": "topic",
      "url": "/documentation/webkit/wkscriptmessagehandler"
    },
    "doc://com.apple.webkit/documentation/WebKit/WKScriptMessageHandlerWithReply": {
      "abstract": [
        {
          "text": "An interface for responding to messages from JavaScript code running in a webpage.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "WKScriptMessageHandlerWithReply"
        }
      ],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/WKScriptMessageHandlerWithReply",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "WKScriptMessageHandlerWithReply"
        }
      ],
      "role": "symbol",
      "title": "WKScriptMessageHandlerWithReply",
      "type": "topic",
      "url": "/documentation/webkit/wkscriptmessagehandlerwithreply"
    },
    "doc://com.apple.webkit/documentation/WebKit/WKUserContentController": {
      "abstract": [
        {
          "text": "An object for managing interactions between JavaScript code and your web view, and for filtering content in your web view.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "WKUserContentController"
        }
      ],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/WKUserContentController",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "WKUserContentController"
        }
      ],
      "role": "symbol",
      "title": "WKUserContentController",
      "type": "topic",
      "url": "/documentation/webkit/wkusercontentcontroller"
    },
    "doc://com.apple.webkit/documentation/WebKit/WKUserContentController/add(_:contentWorld:name:)": {
      "abstract": [
        {
          "text": "Installs a message handler that you can call from the specified content world in your JavaScript code.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "add"
        },
        {
          "kind": "text",
          "text": "(any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(pl)WKScriptMessageHandler",
          "text": "WKScriptMessageHandler"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "contentWorld"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)WKContentWorld",
          "text": "WKContentWorld"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "name"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/WKUserContentController/add(_:contentWorld:name:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "addScriptMessageHandler:contentWorld:name:"
        }
      ],
      "role": "symbol",
      "title": "add(_:contentWorld:name:)",
      "type": "topic",
      "url": "/documentation/webkit/wkusercontentcontroller/add(_:contentworld:name:)"
    },
    "doc://com.apple.webkit/documentation/WebKit/WKUserContentController/add(_:name:)": {
      "abstract": [
        {
          "text": "Installs a message handler that you can call from your JavaScript code.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "add"
        },
        {
          "kind": "text",
          "text": "(any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(pl)WKScriptMessageHandler",
          "text": "WKScriptMessageHandler"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "name"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/WKUserContentController/add(_:name:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "addScriptMessageHandler:name:"
        }
      ],
      "role": "symbol",
      "title": "add(_:name:)",
      "type": "topic",
      "url": "/documentation/webkit/wkusercontentcontroller/add(_:name:)"
    },
    "doc://com.apple.webkit/documentation/WebKit/WKUserContentController/addScriptMessageHandler(_:contentWorld:name:)": {
      "abstract": [
        {
          "text": "Installs a message handler that returns a reply to your JavaScript code.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "addScriptMessageHandler"
        },
        {
          "kind": "text",
          "text": "(any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(pl)WKScriptMessageHandlerWithReply",
          "text": "WKScriptMessageHandlerWithReply"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "contentWorld"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)WKContentWorld",
          "text": "WKContentWorld"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "name"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/WKUserContentController/addScriptMessageHandler(_:contentWorld:name:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "addScriptMessageHandlerWithReply:contentWorld:name:"
        }
      ],
      "role": "symbol",
      "title": "addScriptMessageHandler(_:contentWorld:name:)",
      "type": "topic",
      "url": "/documentation/webkit/wkusercontentcontroller/addscriptmessagehandler(_:contentworld:name:)"
    },
    "doc://com.apple.webkit/documentation/WebKit/WKUserContentController/removeAllScriptMessageHandlers()": {
      "abstract": [
        {
          "text": "Uninstalls all custom message handlers associated with the user content controller.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "removeAllScriptMessageHandlers"
        },
        {
          "kind": "text",
          "text": "()"
        }
      ],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/WKUserContentController/removeAllScriptMessageHandlers()",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "removeAllScriptMessageHandlers"
        }
      ],
      "role": "symbol",
      "title": "removeAllScriptMessageHandlers()",
      "type": "topic",
      "url": "/documentation/webkit/wkusercontentcontroller/removeallscriptmessagehandlers()"
    },
    "doc://com.apple.webkit/documentation/WebKit/WKUserContentController/removeAllScriptMessageHandlers(from:)": {
      "abstract": [
        {
          "text": "Uninstalls all custom message handlers from the specified content world in your JavaScript code.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "removeAllScriptMessageHandlers"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "from"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)WKContentWorld",
          "text": "WKContentWorld"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/WKUserContentController/removeAllScriptMessageHandlers(from:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "removeAllScriptMessageHandlersFromContentWorld:"
        }
      ],
      "role": "symbol",
      "title": "removeAllScriptMessageHandlers(from:)",
      "type": "topic",
      "url": "/documentation/webkit/wkusercontentcontroller/removeallscriptmessagehandlers(from:)"
    },
    "doc://com.apple.webkit/documentation/WebKit/WKUserContentController/removeScriptMessageHandler(forName:)": {
      "abstract": [
        {
          "text": "Uninstalls the custom message handler with the specified name from your JavaScript code.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "removeScriptMessageHandler"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "forName"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/WKUserContentController/removeScriptMessageHandler(forName:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "removeScriptMessageHandlerForName:"
        }
      ],
      "role": "symbol",
      "title": "removeScriptMessageHandler(forName:)",
      "type": "topic",
      "url": "/documentation/webkit/wkusercontentcontroller/removescriptmessagehandler(forname:)"
    },
    "doc://com.apple.webkit/documentation/WebKit/WKUserContentController/removeScriptMessageHandler(forName:contentWorld:)": {
      "abstract": [
        {
          "text": "Uninstalls a custom message handler from the specified content world in your JavaScript code.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "removeScriptMessageHandler"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "forName"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "contentWorld"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)WKContentWorld",
          "text": "WKContentWorld"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/WKUserContentController/removeScriptMessageHandler(forName:contentWorld:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "removeScriptMessageHandlerForName:contentWorld:"
        }
      ],
      "role": "symbol",
      "title": "removeScriptMessageHandler(forName:contentWorld:)",
      "type": "topic",
      "url": "/documentation/webkit/wkusercontentcontroller/removescriptmessagehandler(forname:contentworld:)"
    },
    "doc://com.externally.resolved.symbol/c:objc(cs)NSString": {
      "abstract": [
        {
          "text": "A static, plain-text Unicode string object which you use when you need reference semantics or other Foundation-specific behavior. ",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "class "
        },
        {
          "kind": "identifier",
          "text": "NSString"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSString",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSString",
      "type": "topic",
      "url": "/documentation/foundation/nsstring"
    },
    "doc://com.externally.resolved.symbol/s:SS": {
      "abstract": [
        {
          "text": "A Unicode string value that is a collection of characters.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@frozen"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "String"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SS",
      "kind": "symbol",
      "role": "symbol",
      "title": "String",
      "type": "topic",
      "url": "/documentation/Swift/String"
    },
    "doc://com.externally.resolved.symbol/s:ScM": {
      "abstract": [
        {
          "text": "A singleton actor whose executor is equivalent to the main dispatch queue.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@globalActor"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "final"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "actor"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MainActor"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:ScM",
      "kind": "symbol",
      "role": "symbol",
      "title": "MainActor",
      "type": "topic",
      "url": "/documentation/Swift/MainActor"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Adding-and-Removing-Message-Handlers",
      "generated": true,
      "identifiers": [
        "doc://com.apple.webkit/documentation/WebKit/WKUserContentController/add(_:name:)",
        "doc://com.apple.webkit/documentation/WebKit/WKUserContentController/add(_:contentWorld:name:)",
        "doc://com.apple.webkit/documentation/WebKit/WKUserContentController/removeScriptMessageHandler(forName:)",
        "doc://com.apple.webkit/documentation/WebKit/WKUserContentController/removeScriptMessageHandler(forName:contentWorld:)",
        "doc://com.apple.webkit/documentation/WebKit/WKUserContentController/removeAllScriptMessageHandlers(from:)",
        "doc://com.apple.webkit/documentation/WebKit/WKUserContentController/removeAllScriptMessageHandlers()",
        "doc://com.apple.webkit/documentation/WebKit/WKScriptMessageHandler",
        "doc://com.apple.webkit/documentation/WebKit/WKScriptMessageHandlerWithReply"
      ],
      "title": "Adding and Removing Message Handlers"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "14.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "14.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "14.0",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "11.0",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Instance Method"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "addScriptMessageHandlerWithReply:contentWorld:name:"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "method"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "addScriptMessageHandlerWithReply:contentWorld:name:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.webkit/documentation/WebKit",
                "doc://com.apple.webkit/documentation/WebKit/WKUserContentController"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Adding-and-Removing-Message-Handlers",
              "generated": true,
              "identifiers": [
                "doc://com.apple.webkit/documentation/WebKit/WKUserContentController/add(_:name:)",
                "doc://com.apple.webkit/documentation/WebKit/WKUserContentController/add(_:contentWorld:name:)",
                "doc://com.apple.webkit/documentation/WebKit/WKUserContentController/removeScriptMessageHandler(forName:)",
                "doc://com.apple.webkit/documentation/WebKit/WKUserContentController/removeScriptMessageHandler(forName:contentWorld:)",
                "doc://com.apple.webkit/documentation/WebKit/WKUserContentController/removeAllScriptMessageHandlers(from:)",
                "doc://com.apple.webkit/documentation/WebKit/WKUserContentController/removeAllScriptMessageHandlers()",
                "doc://com.apple.webkit/documentation/WebKit/WKScriptMessageHandler",
                "doc://com.apple.webkit/documentation/WebKit/WKScriptMessageHandlerWithReply"
              ],
              "title": "Adding and Removing Message Handlers"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "visionOS"
                ],
                "tokens": [
                  {
                    "kind": "text",
                    "text": "- ("
                  },
                  {
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:v",
                    "text": "void"
                  },
                  {
                    "kind": "text",
                    "text": ") "
                  },
                  {
                    "kind": "identifier",
                    "text": "addScriptMessageHandlerWithReply:"
                  },
                  {
                    "kind": "text",
                    "text": "("
                  },
                  {
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:Qoobjc(pl)WKScriptMessageHandlerWithReply",
                    "text": "id<WKScriptMessageHandlerWithReply>"
                  },
                  {
                    "kind": "text",
                    "text": ") "
                  },
                  {
                    "kind": "internalParam",
                    "text": "scriptMessageHandlerWithReply"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "contentWorld:"
                  },
                  {
                    "kind": "text",
                    "text": "("
                  },
                  {
                    "identifier": "doc://com.apple.webkit/documentation/WebKit/WKContentWorld",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(cs)WKContentWorld",
                    "text": "WKContentWorld"
                  },
                  {
                    "kind": "text",
                    "text": " *) "
                  },
                  {
                    "kind": "internalParam",
                    "text": "contentWorld"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "name:"
                  },
                  {
                    "kind": "text",
                    "text": "("
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSString",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(cs)NSString",
                    "text": "NSString"
                  },
                  {
                    "kind": "text",
                    "text": " *) "
                  },
                  {
                    "kind": "internalParam",
                    "text": "name"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/1",
          "value": {
            "kind": "parameters",
            "parameters": [
              {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "The message handler object that implements your custom code. This object must adopt the ",
                        "type": "text"
                      },
                      {
                        "identifier": "doc://com.apple.webkit/documentation/WebKit/WKScriptMessageHandlerWithReply",
                        "isActive": true,
                        "type": "reference"
                      },
                      {
                        "text": " protocol.",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ],
                "name": "scriptMessageHandlerWithReply"
              },
              {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "The content world in which to install the message handler. Use the content world to scope your message handler to specific parts of your JavaScript code.",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ],
                "name": "contentWorld"
              },
              {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "The name of the message handler. This parameter must be unique within the user content controller and must not be an empty string.",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  },
                  {
                    "inlineContent": [
                      {
                        "text": "The user content controller uses this parameter to define a JavaScript function for your message handler in all frames in the specified content world. The name of this function is ",
                        "type": "text"
                      },
                      {
                        "code": "window.webkit.messageHandlers.",
                        "type": "codeVoice"
                      },
                      {
                        "inlineContent": [],
                        "type": "emphasis"
                      },
                      {
                        "code": ".postMessage(<messageBody>)",
                        "type": "codeVoice"
                      },
                      {
                        "text": ", where ",
                        "type": "text"
                      },
                      {
                        "inlineContent": [],
                        "type": "emphasis"
                      },
                      {
                        "text": " corresponds to the value of this parameter.  For example, if you specify the string ",
                        "type": "text"
                      },
                      {
                        "code": "MyFunction",
                        "type": "codeVoice"
                      },
                      {
                        "text": ", the user content controller defines the ",
                        "type": "text"
                      },
                      {
                        "code": "window.webkit.messageHandlers.MyFunction.postMessage()",
                        "type": "codeVoice"
                      },
                      {
                        "text": " function in JavaScript.",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ],
                "name": "name"
              }
            ]
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WKUserContentController~1removeAllScriptMessageHandlers()/title",
          "value": "removeAllScriptMessageHandlers"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WKUserContentController~1removeAllScriptMessageHandlers()/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "removeAllScriptMessageHandlers"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WKScriptMessageHandlerWithReply/title",
          "value": "WKScriptMessageHandlerWithReply"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WKScriptMessageHandlerWithReply/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "WKScriptMessageHandlerWithReply"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WKScriptMessageHandlerWithReply/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "WKScriptMessageHandlerWithReply"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WKContentWorld/title",
          "value": "WKContentWorld"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WKContentWorld/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "WKContentWorld"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WKContentWorld/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "WKContentWorld"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WKUserContentController~1removeScriptMessageHandler(forName:)/title",
          "value": "removeScriptMessageHandlerForName:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WKUserContentController~1removeScriptMessageHandler(forName:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "removeScriptMessageHandlerForName:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WKUserContentController~1add(_:contentWorld:name:)/title",
          "value": "addScriptMessageHandler:contentWorld:name:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WKUserContentController~1add(_:contentWorld:name:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "addScriptMessageHandler:contentWorld:name:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WKUserContentController~1addScriptMessageHandler(_:contentWorld:name:)/title",
          "value": "addScriptMessageHandlerWithReply:contentWorld:name:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WKUserContentController~1addScriptMessageHandler(_:contentWorld:name:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "addScriptMessageHandlerWithReply:contentWorld:name:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WKScriptMessageHandler/title",
          "value": "WKScriptMessageHandler"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WKScriptMessageHandler/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "WKScriptMessageHandler"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WKScriptMessageHandler/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "WKScriptMessageHandler"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WKUserContentController~1add(_:name:)/title",
          "value": "addScriptMessageHandler:name:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WKUserContentController~1add(_:name:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "addScriptMessageHandler:name:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WKUserContentController~1removeScriptMessageHandler(forName:contentWorld:)/title",
          "value": "removeScriptMessageHandlerForName:contentWorld:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WKUserContentController~1removeScriptMessageHandler(forName:contentWorld:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "removeScriptMessageHandlerForName:contentWorld:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WKUserContentController~1removeAllScriptMessageHandlers(from:)/title",
          "value": "removeAllScriptMessageHandlersFromContentWorld:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WKUserContentController~1removeAllScriptMessageHandlers(from:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "removeAllScriptMessageHandlersFromContentWorld:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WKUserContentController/title",
          "value": "WKUserContentController"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WKUserContentController/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "WKUserContentController"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WKUserContentController/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "WKUserContentController"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:objc(cs)NSString/abstract",
          "value": [
            {
              "text": "A static, plain-text Unicode string object.",
              "type": "text"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/webkit/wkusercontentcontroller/addscriptmessagehandler(_:contentworld:name:)"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/webkit/wkusercontentcontroller/addscriptmessagehandler(_:contentworld:name:)"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
