{
  "abstract": [
    {
      "text": "A type that defines the filter to apply to the photo library.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.photokit/documentation/PhotosUI"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.photokit/documentation/PhotosUI/PHPickerFilter-swift.struct"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "s:8PhotosUI14PHPickerFilterV",
    "fragments": [
      {
        "kind": "keyword",
        "text": "struct"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "PHPickerFilter"
      }
    ],
    "modules": [
      {
        "name": "PhotosUI"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "PHPickerFilter"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "14.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "14.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.0",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "9.0",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Structure",
    "symbolKind": "struct",
    "title": "PHPickerFilter"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "struct"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "PHPickerFilter"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.photokit/documentation/PhotoKit/selecting-photos-and-videos-in-ios": {
      "abstract": [
        {
          "text": "Improve the user experience of finding and selecting assets by using the Photos picker.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.photokit/documentation/PhotoKit/selecting-photos-and-videos-in-ios",
      "kind": "article",
      "role": "sampleCode",
      "title": "Selecting Photos and Videos in iOS",
      "type": "topic",
      "url": "/documentation/photokit/selecting-photos-and-videos-in-ios"
    },
    "doc://com.apple.photokit/documentation/PhotosUI": {
      "abstract": [
        {
          "text": "Present a person’s photo library using a picker interface, display Live Photos, or extend the Photos app with custom functionality.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.photokit/documentation/PhotosUI",
      "kind": "symbol",
      "role": "collection",
      "title": "PhotosUI",
      "type": "topic",
      "url": "/documentation/photosui"
    },
    "doc://com.apple.photokit/documentation/PhotosUI/PHPickerConfiguration-swift.struct": {
      "abstract": [
        {
          "text": "An object that contains information about how to configure a picker view controller.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "PHPickerConfiguration"
        }
      ],
      "identifier": "doc://com.apple.photokit/documentation/PhotosUI/PHPickerConfiguration-swift.struct",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PHPickerConfiguration"
        }
      ],
      "role": "symbol",
      "title": "PHPickerConfiguration",
      "type": "topic",
      "url": "/documentation/photosui/phpickerconfiguration-swift.struct"
    },
    "doc://com.apple.photokit/documentation/PhotosUI/PHPickerFilter-swift.struct": {
      "abstract": [
        {
          "text": "A type that defines the filter to apply to the photo library.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "PHPickerFilter"
        }
      ],
      "identifier": "doc://com.apple.photokit/documentation/PhotosUI/PHPickerFilter-swift.struct",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PHPickerFilter"
        }
      ],
      "role": "symbol",
      "title": "PHPickerFilter",
      "type": "topic",
      "url": "/documentation/photosui/phpickerfilter-swift.struct"
    },
    "doc://com.apple.photokit/documentation/PhotosUI/PHPickerFilter-swift.struct/all(of:)": {
      "abstract": [
        {
          "text": "Creates a new filter that includes only the filters you specify.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "all"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "of"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:8PhotosUI14PHPickerFilterV",
          "text": "PHPickerFilter"
        },
        {
          "kind": "text",
          "text": "]) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:8PhotosUI14PHPickerFilterV",
          "text": "PHPickerFilter"
        }
      ],
      "identifier": "doc://com.apple.photokit/documentation/PhotosUI/PHPickerFilter-swift.struct/all(of:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "all(of:)",
      "type": "topic",
      "url": "/documentation/photosui/phpickerfilter-swift.struct/all(of:)"
    },
    "doc://com.apple.photokit/documentation/PhotosUI/PHPickerFilter-swift.struct/any(of:)": {
      "abstract": [
        {
          "text": "Returns a new filter formed by OR-ing the filters in a given array.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "any"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "of"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:8PhotosUI14PHPickerFilterV",
          "text": "PHPickerFilter"
        },
        {
          "kind": "text",
          "text": "]) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:8PhotosUI14PHPickerFilterV",
          "text": "PHPickerFilter"
        }
      ],
      "identifier": "doc://com.apple.photokit/documentation/PhotosUI/PHPickerFilter-swift.struct/any(of:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "any(of:)",
      "type": "topic",
      "url": "/documentation/photosui/phpickerfilter-swift.struct/any(of:)"
    },
    "doc://com.apple.photokit/documentation/PhotosUI/PHPickerFilter-swift.struct/bursts": {
      "abstract": [
        {
          "text": "A filter that represents assets with multiple high-speed photos.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "bursts"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:8PhotosUI14PHPickerFilterV",
          "text": "PHPickerFilter"
        }
      ],
      "identifier": "doc://com.apple.photokit/documentation/PhotosUI/PHPickerFilter-swift.struct/bursts",
      "kind": "symbol",
      "role": "symbol",
      "title": "bursts",
      "type": "topic",
      "url": "/documentation/photosui/phpickerfilter-swift.struct/bursts"
    },
    "doc://com.apple.photokit/documentation/PhotosUI/PHPickerFilter-swift.struct/cinematicVideos": {
      "abstract": [
        {
          "text": "A filter that represents videos with a shallow depth of field and focus transitions.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "cinematicVideos"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:8PhotosUI14PHPickerFilterV",
          "text": "PHPickerFilter"
        }
      ],
      "identifier": "doc://com.apple.photokit/documentation/PhotosUI/PHPickerFilter-swift.struct/cinematicVideos",
      "kind": "symbol",
      "role": "symbol",
      "title": "cinematicVideos",
      "type": "topic",
      "url": "/documentation/photosui/phpickerfilter-swift.struct/cinematicvideos"
    },
    "doc://com.apple.photokit/documentation/PhotosUI/PHPickerFilter-swift.struct/depthEffectPhotos": {
      "abstract": [
        {
          "text": "A filter that represents photos with depth information.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "depthEffectPhotos"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:8PhotosUI14PHPickerFilterV",
          "text": "PHPickerFilter"
        }
      ],
      "identifier": "doc://com.apple.photokit/documentation/PhotosUI/PHPickerFilter-swift.struct/depthEffectPhotos",
      "kind": "symbol",
      "role": "symbol",
      "title": "depthEffectPhotos",
      "type": "topic",
      "url": "/documentation/photosui/phpickerfilter-swift.struct/deptheffectphotos"
    },
    "doc://com.apple.photokit/documentation/PhotosUI/PHPickerFilter-swift.struct/images": {
      "abstract": [
        {
          "text": "The filter for images.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "images"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:8PhotosUI14PHPickerFilterV",
          "text": "PHPickerFilter"
        }
      ],
      "identifier": "doc://com.apple.photokit/documentation/PhotosUI/PHPickerFilter-swift.struct/images",
      "kind": "symbol",
      "role": "symbol",
      "title": "images",
      "type": "topic",
      "url": "/documentation/photosui/phpickerfilter-swift.struct/images"
    },
    "doc://com.apple.photokit/documentation/PhotosUI/PHPickerFilter-swift.struct/livePhotos": {
      "abstract": [
        {
          "text": "The filter for live photos.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "livePhotos"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:8PhotosUI14PHPickerFilterV",
          "text": "PHPickerFilter"
        }
      ],
      "identifier": "doc://com.apple.photokit/documentation/PhotosUI/PHPickerFilter-swift.struct/livePhotos",
      "kind": "symbol",
      "role": "symbol",
      "title": "livePhotos",
      "type": "topic",
      "url": "/documentation/photosui/phpickerfilter-swift.struct/livephotos"
    },
    "doc://com.apple.photokit/documentation/PhotosUI/PHPickerFilter-swift.struct/not(_:)": {
      "abstract": [
        {
          "text": "Creates a new filter that excludes the filter you specify.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "not"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:8PhotosUI14PHPickerFilterV",
          "text": "PHPickerFilter"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:8PhotosUI14PHPickerFilterV",
          "text": "PHPickerFilter"
        }
      ],
      "identifier": "doc://com.apple.photokit/documentation/PhotosUI/PHPickerFilter-swift.struct/not(_:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "not(_:)",
      "type": "topic",
      "url": "/documentation/photosui/phpickerfilter-swift.struct/not(_:)"
    },
    "doc://com.apple.photokit/documentation/PhotosUI/PHPickerFilter-swift.struct/panoramas": {
      "abstract": [
        {
          "text": "A filter that represents panorama photos.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "panoramas"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:8PhotosUI14PHPickerFilterV",
          "text": "PHPickerFilter"
        }
      ],
      "identifier": "doc://com.apple.photokit/documentation/PhotosUI/PHPickerFilter-swift.struct/panoramas",
      "kind": "symbol",
      "role": "symbol",
      "title": "panoramas",
      "type": "topic",
      "url": "/documentation/photosui/phpickerfilter-swift.struct/panoramas"
    },
    "doc://com.apple.photokit/documentation/PhotosUI/PHPickerFilter-swift.struct/playbackStyle(_:)": {
      "abstract": [
        {
          "text": "Creates a new filter by using the playback style you specify.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "playbackStyle"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)PHAsset",
          "text": "PHAsset"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@PHAssetPlaybackStyle",
          "text": "PlaybackStyle"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:8PhotosUI14PHPickerFilterV",
          "text": "PHPickerFilter"
        }
      ],
      "identifier": "doc://com.apple.photokit/documentation/PhotosUI/PHPickerFilter-swift.struct/playbackStyle(_:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "playbackStyle(_:)",
      "type": "topic",
      "url": "/documentation/photosui/phpickerfilter-swift.struct/playbackstyle(_:)"
    },
    "doc://com.apple.photokit/documentation/PhotosUI/PHPickerFilter-swift.struct/screenRecordings": {
      "abstract": [
        {
          "text": "A filter that represents screen recordings.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "screenRecordings"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:8PhotosUI14PHPickerFilterV",
          "text": "PHPickerFilter"
        }
      ],
      "identifier": "doc://com.apple.photokit/documentation/PhotosUI/PHPickerFilter-swift.struct/screenRecordings",
      "kind": "symbol",
      "role": "symbol",
      "title": "screenRecordings",
      "type": "topic",
      "url": "/documentation/photosui/phpickerfilter-swift.struct/screenrecordings"
    },
    "doc://com.apple.photokit/documentation/PhotosUI/PHPickerFilter-swift.struct/screenshots": {
      "abstract": [
        {
          "text": "A filter that represents screenshots.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "screenshots"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:8PhotosUI14PHPickerFilterV",
          "text": "PHPickerFilter"
        }
      ],
      "identifier": "doc://com.apple.photokit/documentation/PhotosUI/PHPickerFilter-swift.struct/screenshots",
      "kind": "symbol",
      "role": "symbol",
      "title": "screenshots",
      "type": "topic",
      "url": "/documentation/photosui/phpickerfilter-swift.struct/screenshots"
    },
    "doc://com.apple.photokit/documentation/PhotosUI/PHPickerFilter-swift.struct/slomoVideos": {
      "abstract": [
        {
          "text": "A filter that represents slow-motion videos.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "slomoVideos"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:8PhotosUI14PHPickerFilterV",
          "text": "PHPickerFilter"
        }
      ],
      "identifier": "doc://com.apple.photokit/documentation/PhotosUI/PHPickerFilter-swift.struct/slomoVideos",
      "kind": "symbol",
      "role": "symbol",
      "title": "slomoVideos",
      "type": "topic",
      "url": "/documentation/photosui/phpickerfilter-swift.struct/slomovideos"
    },
    "doc://com.apple.photokit/documentation/PhotosUI/PHPickerFilter-swift.struct/spatialMedia": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "spatialMedia"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:8PhotosUI14PHPickerFilterV",
          "text": "PHPickerFilter"
        }
      ],
      "identifier": "doc://com.apple.photokit/documentation/PhotosUI/PHPickerFilter-swift.struct/spatialMedia",
      "kind": "symbol",
      "role": "symbol",
      "title": "spatialMedia",
      "type": "topic",
      "url": "/documentation/photosui/phpickerfilter-swift.struct/spatialmedia"
    },
    "doc://com.apple.photokit/documentation/PhotosUI/PHPickerFilter-swift.struct/timelapseVideos": {
      "abstract": [
        {
          "text": "A filter that represents time-lapse videos.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "timelapseVideos"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:8PhotosUI14PHPickerFilterV",
          "text": "PHPickerFilter"
        }
      ],
      "identifier": "doc://com.apple.photokit/documentation/PhotosUI/PHPickerFilter-swift.struct/timelapseVideos",
      "kind": "symbol",
      "role": "symbol",
      "title": "timelapseVideos",
      "type": "topic",
      "url": "/documentation/photosui/phpickerfilter-swift.struct/timelapsevideos"
    },
    "doc://com.apple.photokit/documentation/PhotosUI/PHPickerFilter-swift.struct/videos": {
      "abstract": [
        {
          "text": "The filter for videos.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "videos"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:8PhotosUI14PHPickerFilterV",
          "text": "PHPickerFilter"
        }
      ],
      "identifier": "doc://com.apple.photokit/documentation/PhotosUI/PHPickerFilter-swift.struct/videos",
      "kind": "symbol",
      "role": "symbol",
      "title": "videos",
      "type": "topic",
      "url": "/documentation/photosui/phpickerfilter-swift.struct/videos"
    },
    "doc://com.apple.photokit/documentation/PhotosUI/PHPickerResult-swift.struct": {
      "abstract": [
        {
          "text": "Types that represent a selected asset from the user’s photo library.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "PHPickerResult"
        }
      ],
      "identifier": "doc://com.apple.photokit/documentation/PhotosUI/PHPickerResult-swift.struct",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PHPickerResult"
        }
      ],
      "role": "symbol",
      "title": "PHPickerResult",
      "type": "topic",
      "url": "/documentation/photosui/phpickerresult-swift.struct"
    },
    "doc://com.apple.photokit/documentation/PhotosUI/PHPickerViewController": {
      "abstract": [
        {
          "text": "A view controller that provides the user interface for choosing assets from the photo library.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "PHPickerViewController"
        }
      ],
      "identifier": "doc://com.apple.photokit/documentation/PhotosUI/PHPickerViewController",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PHPickerViewController"
        }
      ],
      "role": "symbol",
      "title": "PHPickerViewController",
      "type": "topic",
      "url": "/documentation/photosui/phpickerviewcontroller"
    },
    "doc://com.apple.photokit/documentation/PhotosUI/PHPickerViewControllerDelegate-5yntc": {
      "abstract": [
        {
          "text": "A set of methods that the delegate must implement to respond to ",
          "type": "text"
        },
        {
          "code": "PHPickerViewController",
          "type": "codeVoice"
        },
        {
          "text": " user events.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "PHPickerViewControllerDelegate"
        }
      ],
      "identifier": "doc://com.apple.photokit/documentation/PhotosUI/PHPickerViewControllerDelegate-5yntc",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PHPickerViewControllerDelegate"
        }
      ],
      "role": "symbol",
      "title": "PHPickerViewControllerDelegate",
      "type": "topic",
      "url": "/documentation/photosui/phpickerviewcontrollerdelegate-5yntc"
    },
    "doc://com.externally.resolved.symbol/s:SH": {
      "abstract": [
        {
          "text": "A type that can be hashed into a `Hasher` to produce an integer hash value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Hashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SQ",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SH",
      "kind": "symbol",
      "role": "symbol",
      "title": "Hashable",
      "type": "topic",
      "url": "/documentation/Swift/Hashable"
    },
    "doc://com.externally.resolved.symbol/s:SQ": {
      "abstract": [
        {
          "text": "A type that can be compared for value equality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SQ",
      "kind": "symbol",
      "role": "symbol",
      "title": "Equatable",
      "type": "topic",
      "url": "/documentation/Swift/Equatable"
    },
    "doc://com.externally.resolved.symbol/s:s8SendableP": {
      "abstract": [
        {
          "text": "A thread-safe type whose values can be shared across arbitrary concurrent contexts without introducing a risk of data races.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Sendable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s8SendableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "Sendable",
      "type": "topic",
      "url": "/documentation/Swift/Sendable"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:SQ",
        "doc://com.externally.resolved.symbol/s:SH",
        "doc://com.externally.resolved.symbol/s:s8SendableP"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Photos-picker-for-UIKit-AppKit",
      "generated": true,
      "identifiers": [
        "doc://com.apple.photokit/documentation/PhotoKit/selecting-photos-and-videos-in-ios",
        "doc://com.apple.photokit/documentation/PhotosUI/PHPickerViewController",
        "doc://com.apple.photokit/documentation/PhotosUI/PHPickerViewControllerDelegate-5yntc",
        "doc://com.apple.photokit/documentation/PhotosUI/PHPickerConfiguration-swift.struct",
        "doc://com.apple.photokit/documentation/PhotosUI/PHPickerResult-swift.struct"
      ],
      "title": "Photos picker for UIKit, AppKit"
    }
  ],
  "topicSections": [
    {
      "anchor": "Creating-Filters",
      "identifiers": [
        "doc://com.apple.photokit/documentation/PhotosUI/PHPickerFilter-swift.struct/playbackStyle(_:)",
        "doc://com.apple.photokit/documentation/PhotosUI/PHPickerFilter-swift.struct/all(of:)",
        "doc://com.apple.photokit/documentation/PhotosUI/PHPickerFilter-swift.struct/not(_:)"
      ],
      "title": "Creating Filters"
    },
    {
      "anchor": "Getting-Filter-Types",
      "identifiers": [
        "doc://com.apple.photokit/documentation/PhotosUI/PHPickerFilter-swift.struct/bursts",
        "doc://com.apple.photokit/documentation/PhotosUI/PHPickerFilter-swift.struct/cinematicVideos",
        "doc://com.apple.photokit/documentation/PhotosUI/PHPickerFilter-swift.struct/depthEffectPhotos",
        "doc://com.apple.photokit/documentation/PhotosUI/PHPickerFilter-swift.struct/images",
        "doc://com.apple.photokit/documentation/PhotosUI/PHPickerFilter-swift.struct/livePhotos",
        "doc://com.apple.photokit/documentation/PhotosUI/PHPickerFilter-swift.struct/panoramas",
        "doc://com.apple.photokit/documentation/PhotosUI/PHPickerFilter-swift.struct/screenRecordings",
        "doc://com.apple.photokit/documentation/PhotosUI/PHPickerFilter-swift.struct/screenshots",
        "doc://com.apple.photokit/documentation/PhotosUI/PHPickerFilter-swift.struct/slomoVideos",
        "doc://com.apple.photokit/documentation/PhotosUI/PHPickerFilter-swift.struct/timelapseVideos",
        "doc://com.apple.photokit/documentation/PhotosUI/PHPickerFilter-swift.struct/videos",
        "doc://com.apple.photokit/documentation/PhotosUI/PHPickerFilter-swift.struct/any(of:)"
      ],
      "title": "Getting Filter Types"
    },
    {
      "anchor": "Type-Properties",
      "generated": true,
      "identifiers": [
        "doc://com.apple.photokit/documentation/PhotosUI/PHPickerFilter-swift.struct/spatialMedia"
      ],
      "title": "Type Properties"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1PhotosUI~1PHPickerViewController/title",
          "value": "PHPickerViewController"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1PhotosUI~1PHPickerViewController/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PHPickerViewController"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1PhotosUI~1PHPickerViewController/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "PHPickerViewController"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/photosui/phpickerfilter-swift.struct"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    }
  ]
}
