{
  "abstract": [
    {
      "text": "An object that contains information about how to configure a picker view controller.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.photokit/documentation/PhotosUI"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.photokit/documentation/PhotosUI/PHPickerConfiguration-swift.struct"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "s:8PhotosUI21PHPickerConfigurationV",
    "fragments": [
      {
        "kind": "keyword",
        "text": "struct"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "PHPickerConfiguration"
      }
    ],
    "modules": [
      {
        "name": "PhotosUI"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "PHPickerConfiguration"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "14.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "14.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.0",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Structure",
    "symbolKind": "struct",
    "title": "PHPickerConfiguration"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "struct"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "PHPickerConfiguration"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.photokit/documentation/PhotoKit/selecting-photos-and-videos-in-ios": {
      "abstract": [
        {
          "text": "Improve the user experience of finding and selecting assets by using the Photos picker.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.photokit/documentation/PhotoKit/selecting-photos-and-videos-in-ios",
      "kind": "article",
      "role": "sampleCode",
      "title": "Selecting Photos and Videos in iOS",
      "type": "topic",
      "url": "/documentation/photokit/selecting-photos-and-videos-in-ios"
    },
    "doc://com.apple.photokit/documentation/PhotosUI": {
      "abstract": [
        {
          "text": "Present a person’s photo library using a picker interface, display Live Photos, or extend the Photos app with custom functionality.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.photokit/documentation/PhotosUI",
      "kind": "symbol",
      "role": "collection",
      "title": "PhotosUI",
      "type": "topic",
      "url": "/documentation/photosui"
    },
    "doc://com.apple.photokit/documentation/PhotosUI/PHPickerCapabilities": {
      "abstract": [
        {
          "text": "Options that customize the look and behavior of the photos picker.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "PHPickerCapabilities"
        }
      ],
      "identifier": "doc://com.apple.photokit/documentation/PhotosUI/PHPickerCapabilities",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PHPickerCapabilities"
        }
      ],
      "role": "symbol",
      "title": "PHPickerCapabilities",
      "type": "topic",
      "url": "/documentation/photosui/phpickercapabilities"
    },
    "doc://com.apple.photokit/documentation/PhotosUI/PHPickerConfiguration-swift.struct": {
      "abstract": [
        {
          "text": "An object that contains information about how to configure a picker view controller.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "PHPickerConfiguration"
        }
      ],
      "identifier": "doc://com.apple.photokit/documentation/PhotosUI/PHPickerConfiguration-swift.struct",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PHPickerConfiguration"
        }
      ],
      "role": "symbol",
      "title": "PHPickerConfiguration",
      "type": "topic",
      "url": "/documentation/photosui/phpickerconfiguration-swift.struct"
    },
    "doc://com.apple.photokit/documentation/PhotosUI/PHPickerConfiguration-swift.struct/AssetRepresentationMode": {
      "abstract": [
        {
          "text": "Constants identifying the mode the system uses when many representations exist for an asset.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AssetRepresentationMode"
        }
      ],
      "identifier": "doc://com.apple.photokit/documentation/PhotosUI/PHPickerConfiguration-swift.struct/AssetRepresentationMode",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AssetRepresentationMode"
        }
      ],
      "role": "symbol",
      "title": "PHPickerConfiguration.AssetRepresentationMode",
      "type": "topic",
      "url": "/documentation/photosui/phpickerconfiguration-swift.struct/assetrepresentationmode"
    },
    "doc://com.apple.photokit/documentation/PhotosUI/PHPickerConfiguration-swift.struct/Selection-swift.enum": {
      "abstract": [
        {
          "text": "Options that represent differing selection behavior.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Selection"
        }
      ],
      "identifier": "doc://com.apple.photokit/documentation/PhotosUI/PHPickerConfiguration-swift.struct/Selection-swift.enum",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "Selection"
        }
      ],
      "role": "symbol",
      "title": "PHPickerConfiguration.Selection",
      "type": "topic",
      "url": "/documentation/photosui/phpickerconfiguration-swift.struct/selection-swift.enum"
    },
    "doc://com.apple.photokit/documentation/PhotosUI/PHPickerConfiguration-swift.struct/Update": {
      "abstract": [
        {
          "text": "An object that defines the aspects of a photo picker’s appearance that can change while it’s presented.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Update"
        }
      ],
      "identifier": "doc://com.apple.photokit/documentation/PhotosUI/PHPickerConfiguration-swift.struct/Update",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "Update"
        }
      ],
      "role": "symbol",
      "title": "PHPickerConfiguration.Update",
      "type": "topic",
      "url": "/documentation/photosui/phpickerconfiguration-swift.struct/update"
    },
    "doc://com.apple.photokit/documentation/PhotosUI/PHPickerConfiguration-swift.struct/disabledCapabilities": {
      "abstract": [
        {
          "text": "The aspects of a photo picker’s default appearance that your app can disable.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "disabledCapabilities"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@PHPickerCapabilities",
          "text": "PHPickerCapabilities"
        }
      ],
      "identifier": "doc://com.apple.photokit/documentation/PhotosUI/PHPickerConfiguration-swift.struct/disabledCapabilities",
      "kind": "symbol",
      "role": "symbol",
      "title": "disabledCapabilities",
      "type": "topic",
      "url": "/documentation/photosui/phpickerconfiguration-swift.struct/disabledcapabilities"
    },
    "doc://com.apple.photokit/documentation/PhotosUI/PHPickerConfiguration-swift.struct/edgesWithoutContentMargins": {
      "abstract": [
        {
          "text": "The portions of a photo picker’s perimeter that are borderless.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "edgesWithoutContentMargins"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@NSDirectionalRectEdge",
          "text": "NSDirectionalRectEdge"
        }
      ],
      "identifier": "doc://com.apple.photokit/documentation/PhotosUI/PHPickerConfiguration-swift.struct/edgesWithoutContentMargins",
      "kind": "symbol",
      "role": "symbol",
      "title": "edgesWithoutContentMargins",
      "type": "topic",
      "url": "/documentation/photosui/phpickerconfiguration-swift.struct/edgeswithoutcontentmargins"
    },
    "doc://com.apple.photokit/documentation/PhotosUI/PHPickerConfiguration-swift.struct/filter": {
      "abstract": [
        {
          "text": "The filter you apply to restrict the asset types the picker displays.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "filter"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:8PhotosUI14PHPickerFilterV",
          "text": "PHPickerFilter"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.photokit/documentation/PhotosUI/PHPickerConfiguration-swift.struct/filter",
      "kind": "symbol",
      "role": "symbol",
      "title": "filter",
      "type": "topic",
      "url": "/documentation/photosui/phpickerconfiguration-swift.struct/filter"
    },
    "doc://com.apple.photokit/documentation/PhotosUI/PHPickerConfiguration-swift.struct/init()": {
      "abstract": [
        {
          "text": "Creates a new configuration object.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "()"
        }
      ],
      "identifier": "doc://com.apple.photokit/documentation/PhotosUI/PHPickerConfiguration-swift.struct/init()",
      "kind": "symbol",
      "role": "symbol",
      "title": "init()",
      "type": "topic",
      "url": "/documentation/photosui/phpickerconfiguration-swift.struct/init()"
    },
    "doc://com.apple.photokit/documentation/PhotosUI/PHPickerConfiguration-swift.struct/init(photoLibrary:)": {
      "abstract": [
        {
          "text": "Creates a new configuration object for a photo library.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "photoLibrary"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)PHPhotoLibrary",
          "text": "PHPhotoLibrary"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.photokit/documentation/PhotosUI/PHPickerConfiguration-swift.struct/init(photoLibrary:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "init(photoLibrary:)",
      "type": "topic",
      "url": "/documentation/photosui/phpickerconfiguration-swift.struct/init(photolibrary:)"
    },
    "doc://com.apple.photokit/documentation/PhotosUI/PHPickerConfiguration-swift.struct/mode": {
      "abstract": [
        {
          "text": "A layout type for the photos in the picker’s view.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "mode"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:8PhotosUI12PHPickerModeV",
          "text": "PHPickerMode"
        }
      ],
      "identifier": "doc://com.apple.photokit/documentation/PhotosUI/PHPickerConfiguration-swift.struct/mode",
      "kind": "symbol",
      "role": "symbol",
      "title": "mode",
      "type": "topic",
      "url": "/documentation/photosui/phpickerconfiguration-swift.struct/mode"
    },
    "doc://com.apple.photokit/documentation/PhotosUI/PHPickerConfiguration-swift.struct/preferredAssetRepresentationMode": {
      "abstract": [
        {
          "text": "A mode that determines which representation to use if an asset contains more than one.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "preferredAssetRepresentationMode"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:8PhotosUI21PHPickerConfigurationV",
          "text": "PHPickerConfiguration"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:8PhotosUI21PHPickerConfigurationV23AssetRepresentationModeO",
          "text": "AssetRepresentationMode"
        }
      ],
      "identifier": "doc://com.apple.photokit/documentation/PhotosUI/PHPickerConfiguration-swift.struct/preferredAssetRepresentationMode",
      "kind": "symbol",
      "role": "symbol",
      "title": "preferredAssetRepresentationMode",
      "type": "topic",
      "url": "/documentation/photosui/phpickerconfiguration-swift.struct/preferredassetrepresentationmode"
    },
    "doc://com.apple.photokit/documentation/PhotosUI/PHPickerConfiguration-swift.struct/preselectedAssetIdentifiers": {
      "abstract": [
        {
          "text": "An array of asset identifiers to preselect in the picker.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "preselectedAssetIdentifiers"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": "]"
        }
      ],
      "identifier": "doc://com.apple.photokit/documentation/PhotosUI/PHPickerConfiguration-swift.struct/preselectedAssetIdentifiers",
      "kind": "symbol",
      "role": "symbol",
      "title": "preselectedAssetIdentifiers",
      "type": "topic",
      "url": "/documentation/photosui/phpickerconfiguration-swift.struct/preselectedassetidentifiers"
    },
    "doc://com.apple.photokit/documentation/PhotosUI/PHPickerConfiguration-swift.struct/selection-swift.property": {
      "abstract": [
        {
          "text": "The selection behavior for the picker.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "selection"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:8PhotosUI21PHPickerConfigurationV",
          "text": "PHPickerConfiguration"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:8PhotosUI21PHPickerConfigurationV9SelectionO",
          "text": "Selection"
        }
      ],
      "identifier": "doc://com.apple.photokit/documentation/PhotosUI/PHPickerConfiguration-swift.struct/selection-swift.property",
      "kind": "symbol",
      "role": "symbol",
      "title": "selection",
      "type": "topic",
      "url": "/documentation/photosui/phpickerconfiguration-swift.struct/selection-swift.property"
    },
    "doc://com.apple.photokit/documentation/PhotosUI/PHPickerConfiguration-swift.struct/selectionLimit": {
      "abstract": [
        {
          "text": "The maximum number of selections the user can make.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "selectionLimit"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.photokit/documentation/PhotosUI/PHPickerConfiguration-swift.struct/selectionLimit",
      "kind": "symbol",
      "role": "symbol",
      "title": "selectionLimit",
      "type": "topic",
      "url": "/documentation/photosui/phpickerconfiguration-swift.struct/selectionlimit"
    },
    "doc://com.apple.photokit/documentation/PhotosUI/PHPickerConfigurationSelection": {
      "abstract": [
        {
          "text": "Options that represent differing selection behavior.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "PHPickerConfigurationSelection"
        }
      ],
      "identifier": "doc://com.apple.photokit/documentation/PhotosUI/PHPickerConfigurationSelection",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PHPickerConfigurationSelection"
        }
      ],
      "role": "symbol",
      "title": "PHPickerConfigurationSelection",
      "type": "topic",
      "url": "/documentation/photosui/phpickerconfigurationselection"
    },
    "doc://com.apple.photokit/documentation/PhotosUI/PHPickerFilter-swift.struct": {
      "abstract": [
        {
          "text": "A type that defines the filter to apply to the photo library.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "PHPickerFilter"
        }
      ],
      "identifier": "doc://com.apple.photokit/documentation/PhotosUI/PHPickerFilter-swift.struct",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PHPickerFilter"
        }
      ],
      "role": "symbol",
      "title": "PHPickerFilter",
      "type": "topic",
      "url": "/documentation/photosui/phpickerfilter-swift.struct"
    },
    "doc://com.apple.photokit/documentation/PhotosUI/PHPickerMode-swift.struct": {
      "abstract": [
        {
          "text": "Layout options that determine how the picker orders photos visually.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "PHPickerMode"
        }
      ],
      "identifier": "doc://com.apple.photokit/documentation/PhotosUI/PHPickerMode-swift.struct",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PHPickerMode"
        }
      ],
      "role": "symbol",
      "title": "PHPickerMode",
      "type": "topic",
      "url": "/documentation/photosui/phpickermode-swift.struct"
    },
    "doc://com.apple.photokit/documentation/PhotosUI/PHPickerResult-swift.struct": {
      "abstract": [
        {
          "text": "Types that represent a selected asset from the user’s photo library.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "PHPickerResult"
        }
      ],
      "identifier": "doc://com.apple.photokit/documentation/PhotosUI/PHPickerResult-swift.struct",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PHPickerResult"
        }
      ],
      "role": "symbol",
      "title": "PHPickerResult",
      "type": "topic",
      "url": "/documentation/photosui/phpickerresult-swift.struct"
    },
    "doc://com.apple.photokit/documentation/PhotosUI/PHPickerViewController": {
      "abstract": [
        {
          "text": "A view controller that provides the user interface for choosing assets from the photo library.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "PHPickerViewController"
        }
      ],
      "identifier": "doc://com.apple.photokit/documentation/PhotosUI/PHPickerViewController",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PHPickerViewController"
        }
      ],
      "role": "symbol",
      "title": "PHPickerViewController",
      "type": "topic",
      "url": "/documentation/photosui/phpickerviewcontroller"
    },
    "doc://com.apple.photokit/documentation/PhotosUI/PHPickerViewControllerDelegate-5yntc": {
      "abstract": [
        {
          "text": "A set of methods that the delegate must implement to respond to ",
          "type": "text"
        },
        {
          "code": "PHPickerViewController",
          "type": "codeVoice"
        },
        {
          "text": " user events.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "PHPickerViewControllerDelegate"
        }
      ],
      "identifier": "doc://com.apple.photokit/documentation/PhotosUI/PHPickerViewControllerDelegate-5yntc",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PHPickerViewControllerDelegate"
        }
      ],
      "role": "symbol",
      "title": "PHPickerViewControllerDelegate",
      "type": "topic",
      "url": "/documentation/photosui/phpickerviewcontrollerdelegate-5yntc"
    },
    "doc://com.externally.resolved.symbol/s:SH": {
      "abstract": [
        {
          "text": "A type that can be hashed into a `Hasher` to produce an integer hash value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Hashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SQ",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SH",
      "kind": "symbol",
      "role": "symbol",
      "title": "Hashable",
      "type": "topic",
      "url": "/documentation/Swift/Hashable"
    },
    "doc://com.externally.resolved.symbol/s:SQ": {
      "abstract": [
        {
          "text": "A type that can be compared for value equality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SQ",
      "kind": "symbol",
      "role": "symbol",
      "title": "Equatable",
      "type": "topic",
      "url": "/documentation/Swift/Equatable"
    },
    "doc://com.externally.resolved.symbol/s:s8SendableP": {
      "abstract": [
        {
          "text": "A thread-safe type whose values can be shared across arbitrary concurrent contexts without introducing a risk of data races.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Sendable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s8SendableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "Sendable",
      "type": "topic",
      "url": "/documentation/Swift/Sendable"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:SQ",
        "doc://com.externally.resolved.symbol/s:SH",
        "doc://com.externally.resolved.symbol/s:s8SendableP"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Photos-picker-for-UIKit-AppKit",
      "generated": true,
      "identifiers": [
        "doc://com.apple.photokit/documentation/PhotoKit/selecting-photos-and-videos-in-ios",
        "doc://com.apple.photokit/documentation/PhotosUI/PHPickerViewController",
        "doc://com.apple.photokit/documentation/PhotosUI/PHPickerViewControllerDelegate-5yntc",
        "doc://com.apple.photokit/documentation/PhotosUI/PHPickerFilter-swift.struct",
        "doc://com.apple.photokit/documentation/PhotosUI/PHPickerResult-swift.struct"
      ],
      "title": "Photos picker for UIKit, AppKit"
    }
  ],
  "topicSections": [
    {
      "anchor": "Creating-a-configuration",
      "identifiers": [
        "doc://com.apple.photokit/documentation/PhotosUI/PHPickerConfiguration-swift.struct/init()",
        "doc://com.apple.photokit/documentation/PhotosUI/PHPickerConfiguration-swift.struct/init(photoLibrary:)"
      ],
      "title": "Creating a configuration"
    },
    {
      "anchor": "Filtering-asset-types",
      "identifiers": [
        "doc://com.apple.photokit/documentation/PhotosUI/PHPickerConfiguration-swift.struct/filter",
        "doc://com.apple.photokit/documentation/PhotosUI/PHPickerFilter-swift.struct"
      ],
      "title": "Filtering asset types"
    },
    {
      "anchor": "Selecting-the-preferred-asset-representation",
      "identifiers": [
        "doc://com.apple.photokit/documentation/PhotosUI/PHPickerConfiguration-swift.struct/preferredAssetRepresentationMode",
        "doc://com.apple.photokit/documentation/PhotosUI/PHPickerConfiguration-swift.struct/AssetRepresentationMode"
      ],
      "title": "Selecting the preferred asset representation"
    },
    {
      "anchor": "Preselecting-assets",
      "identifiers": [
        "doc://com.apple.photokit/documentation/PhotosUI/PHPickerConfiguration-swift.struct/preselectedAssetIdentifiers"
      ],
      "title": "Preselecting assets"
    },
    {
      "anchor": "Setting-the-selection-limit",
      "identifiers": [
        "doc://com.apple.photokit/documentation/PhotosUI/PHPickerConfiguration-swift.struct/selectionLimit",
        "doc://com.apple.photokit/documentation/PhotosUI/PHPickerConfiguration-swift.struct/selection-swift.property",
        "doc://com.apple.photokit/documentation/PhotosUI/PHPickerConfigurationSelection",
        "doc://com.apple.photokit/documentation/PhotosUI/PHPickerConfiguration-swift.struct/Selection-swift.enum"
      ],
      "title": "Setting the selection limit"
    },
    {
      "anchor": "Customizing-picker-appearance-and-behavior",
      "identifiers": [
        "doc://com.apple.photokit/documentation/PhotosUI/PHPickerConfiguration-swift.struct/mode",
        "doc://com.apple.photokit/documentation/PhotosUI/PHPickerMode-swift.struct",
        "doc://com.apple.photokit/documentation/PhotosUI/PHPickerConfiguration-swift.struct/disabledCapabilities",
        "doc://com.apple.photokit/documentation/PhotosUI/PHPickerCapabilities",
        "doc://com.apple.photokit/documentation/PhotosUI/PHPickerConfiguration-swift.struct/edgesWithoutContentMargins",
        "doc://com.apple.photokit/documentation/PhotosUI/PHPickerConfiguration-swift.struct/Update"
      ],
      "title": "Customizing picker appearance and behavior"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1PhotosUI~1PHPickerConfigurationSelection/title",
          "value": "PHPickerConfigurationSelection"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1PhotosUI~1PHPickerConfigurationSelection/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PHPickerConfigurationSelection"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1PhotosUI~1PHPickerConfigurationSelection/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "PHPickerConfigurationSelection"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1PhotosUI~1PHPickerViewController/title",
          "value": "PHPickerViewController"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1PhotosUI~1PHPickerViewController/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PHPickerViewController"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1PhotosUI~1PHPickerViewController/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "PHPickerViewController"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1PhotosUI~1PHPickerCapabilities/title",
          "value": "PHPickerCapabilities"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1PhotosUI~1PHPickerCapabilities/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PHPickerCapabilities"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1PhotosUI~1PHPickerCapabilities/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "PHPickerCapabilities"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/photosui/phpickerconfiguration-swift.struct"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    }
  ]
}
