{
  "abstract": [
    {
      "text": "An object that contains information about how to configure a picker view controller.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.photokit/documentation/PhotosUI"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "occ",
    "url": "doc://com.apple.photokit/documentation/PhotosUI/PHPickerConfiguration-c.class"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(cs)PHPickerConfiguration",
    "fragments": [
      {
        "kind": "identifier",
        "text": "PHPickerConfiguration"
      }
    ],
    "modules": [
      {
        "name": "PhotosUI"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "PHPickerConfiguration"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "14.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "14.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "14.0",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.0",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Class",
    "symbolKind": "class",
    "title": "PHPickerConfiguration"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "occ"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "@interface"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "PHPickerConfiguration"
            },
            {
              "kind": "text",
              "text": " : "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSObject",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)NSObject",
              "text": "NSObject"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.photokit/documentation/PhotosUI": {
      "abstract": [
        {
          "text": "Present a person’s photo library using a picker interface, display Live Photos, or extend the Photos app with custom functionality.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.photokit/documentation/PhotosUI",
      "kind": "symbol",
      "role": "collection",
      "title": "PhotosUI",
      "type": "topic",
      "url": "/documentation/photosui"
    },
    "doc://com.apple.photokit/documentation/PhotosUI/PHPickerCapabilities": {
      "abstract": [
        {
          "text": "Options that customize the look and behavior of the photos picker.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "PHPickerCapabilities"
        }
      ],
      "identifier": "doc://com.apple.photokit/documentation/PhotosUI/PHPickerCapabilities",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PHPickerCapabilities"
        }
      ],
      "role": "symbol",
      "title": "PHPickerCapabilities",
      "type": "topic",
      "url": "/documentation/photosui/phpickercapabilities"
    },
    "doc://com.apple.photokit/documentation/PhotosUI/PHPickerConfiguration-c.class": {
      "abstract": [
        {
          "text": "An object that contains information about how to configure a picker view controller.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "PHPickerConfiguration"
        }
      ],
      "identifier": "doc://com.apple.photokit/documentation/PhotosUI/PHPickerConfiguration-c.class",
      "kind": "symbol",
      "role": "symbol",
      "title": "PHPickerConfiguration",
      "type": "topic",
      "url": "/documentation/photosui/phpickerconfiguration-c.class"
    },
    "doc://com.apple.photokit/documentation/PhotosUI/PHPickerConfiguration-c.class/disabledCapabilities": {
      "abstract": [
        {
          "text": "The aspects of a photo picker’s default appearance that your app can disable.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "disabledCapabilities"
        }
      ],
      "identifier": "doc://com.apple.photokit/documentation/PhotosUI/PHPickerConfiguration-c.class/disabledCapabilities",
      "kind": "symbol",
      "role": "symbol",
      "title": "disabledCapabilities",
      "type": "topic",
      "url": "/documentation/photosui/phpickerconfiguration-c.class/disabledcapabilities"
    },
    "doc://com.apple.photokit/documentation/PhotosUI/PHPickerConfiguration-c.class/edgesWithoutContentMargins": {
      "abstract": [
        {
          "text": "The portions of a photo picker’s perimeter that are borderless.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "edgesWithoutContentMargins"
        }
      ],
      "identifier": "doc://com.apple.photokit/documentation/PhotosUI/PHPickerConfiguration-c.class/edgesWithoutContentMargins",
      "kind": "symbol",
      "role": "symbol",
      "title": "edgesWithoutContentMargins",
      "type": "topic",
      "url": "/documentation/photosui/phpickerconfiguration-c.class/edgeswithoutcontentmargins"
    },
    "doc://com.apple.photokit/documentation/PhotosUI/PHPickerConfiguration-c.class/filter": {
      "abstract": [
        {
          "text": "The filter you apply to restrict the asset types the picker displays.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "filter"
        }
      ],
      "identifier": "doc://com.apple.photokit/documentation/PhotosUI/PHPickerConfiguration-c.class/filter",
      "kind": "symbol",
      "role": "symbol",
      "title": "filter",
      "type": "topic",
      "url": "/documentation/photosui/phpickerconfiguration-c.class/filter"
    },
    "doc://com.apple.photokit/documentation/PhotosUI/PHPickerConfiguration-c.class/init": {
      "abstract": [
        {
          "text": "Creates a new configuration object.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "- "
        },
        {
          "kind": "identifier",
          "text": "init"
        }
      ],
      "identifier": "doc://com.apple.photokit/documentation/PhotosUI/PHPickerConfiguration-c.class/init",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "init"
        }
      ],
      "role": "symbol",
      "title": "init",
      "type": "topic",
      "url": "/documentation/photosui/phpickerconfiguration-c.class/init"
    },
    "doc://com.apple.photokit/documentation/PhotosUI/PHPickerConfiguration-c.class/initWithPhotoLibrary:": {
      "abstract": [
        {
          "text": "Creates a new configuration object for a photo library.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "- "
        },
        {
          "kind": "identifier",
          "text": "initWithPhotoLibrary:"
        }
      ],
      "identifier": "doc://com.apple.photokit/documentation/PhotosUI/PHPickerConfiguration-c.class/initWithPhotoLibrary:",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "initWithPhotoLibrary:"
        }
      ],
      "role": "symbol",
      "title": "initWithPhotoLibrary:",
      "type": "topic",
      "url": "/documentation/photosui/phpickerconfiguration-c.class/initwithphotolibrary:"
    },
    "doc://com.apple.photokit/documentation/PhotosUI/PHPickerConfiguration-c.class/mode": {
      "abstract": [
        {
          "text": "A layout type for the photos in the picker’s view.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "mode"
        }
      ],
      "identifier": "doc://com.apple.photokit/documentation/PhotosUI/PHPickerConfiguration-c.class/mode",
      "kind": "symbol",
      "role": "symbol",
      "title": "mode",
      "type": "topic",
      "url": "/documentation/photosui/phpickerconfiguration-c.class/mode"
    },
    "doc://com.apple.photokit/documentation/PhotosUI/PHPickerConfiguration-c.class/preferredAssetRepresentationMode": {
      "abstract": [
        {
          "text": "A mode that determines which representation to use if an asset contains more than one.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "preferredAssetRepresentationMode"
        }
      ],
      "identifier": "doc://com.apple.photokit/documentation/PhotosUI/PHPickerConfiguration-c.class/preferredAssetRepresentationMode",
      "kind": "symbol",
      "role": "symbol",
      "title": "preferredAssetRepresentationMode",
      "type": "topic",
      "url": "/documentation/photosui/phpickerconfiguration-c.class/preferredassetrepresentationmode"
    },
    "doc://com.apple.photokit/documentation/PhotosUI/PHPickerConfiguration-c.class/preselectedAssetIdentifiers": {
      "abstract": [
        {
          "text": "An array of asset identifiers to preselect in the picker.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "preselectedAssetIdentifiers"
        }
      ],
      "identifier": "doc://com.apple.photokit/documentation/PhotosUI/PHPickerConfiguration-c.class/preselectedAssetIdentifiers",
      "kind": "symbol",
      "role": "symbol",
      "title": "preselectedAssetIdentifiers",
      "type": "topic",
      "url": "/documentation/photosui/phpickerconfiguration-c.class/preselectedassetidentifiers"
    },
    "doc://com.apple.photokit/documentation/PhotosUI/PHPickerConfiguration-c.class/selection": {
      "abstract": [
        {
          "text": "The selection behavior for the picker.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "selection"
        }
      ],
      "identifier": "doc://com.apple.photokit/documentation/PhotosUI/PHPickerConfiguration-c.class/selection",
      "kind": "symbol",
      "role": "symbol",
      "title": "selection",
      "type": "topic",
      "url": "/documentation/photosui/phpickerconfiguration-c.class/selection"
    },
    "doc://com.apple.photokit/documentation/PhotosUI/PHPickerConfiguration-c.class/selectionLimit": {
      "abstract": [
        {
          "text": "The maximum number of selections the user can make.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "selectionLimit"
        }
      ],
      "identifier": "doc://com.apple.photokit/documentation/PhotosUI/PHPickerConfiguration-c.class/selectionLimit",
      "kind": "symbol",
      "role": "symbol",
      "title": "selectionLimit",
      "type": "topic",
      "url": "/documentation/photosui/phpickerconfiguration-c.class/selectionlimit"
    },
    "doc://com.apple.photokit/documentation/PhotosUI/PHPickerConfigurationAssetRepresentationMode": {
      "abstract": [
        {
          "text": "Constants identifying the mode the system uses when many representations exist for an asset.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "PHPickerConfigurationAssetRepresentationMode"
        }
      ],
      "identifier": "doc://com.apple.photokit/documentation/PhotosUI/PHPickerConfigurationAssetRepresentationMode",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PHPickerConfigurationAssetRepresentationMode"
        }
      ],
      "role": "symbol",
      "title": "PHPickerConfigurationAssetRepresentationMode",
      "type": "topic",
      "url": "/documentation/photosui/phpickerconfigurationassetrepresentationmode"
    },
    "doc://com.apple.photokit/documentation/PhotosUI/PHPickerConfigurationSelection": {
      "abstract": [
        {
          "text": "Options that represent differing selection behavior.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "PHPickerConfigurationSelection"
        }
      ],
      "identifier": "doc://com.apple.photokit/documentation/PhotosUI/PHPickerConfigurationSelection",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PHPickerConfigurationSelection"
        }
      ],
      "role": "symbol",
      "title": "PHPickerConfigurationSelection",
      "type": "topic",
      "url": "/documentation/photosui/phpickerconfigurationselection"
    },
    "doc://com.apple.photokit/documentation/PhotosUI/PHPickerFilter-c.class": {
      "abstract": [
        {
          "text": "A type that defines the filter to apply to the photo library.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "PHPickerFilter"
        }
      ],
      "identifier": "doc://com.apple.photokit/documentation/PhotosUI/PHPickerFilter-c.class",
      "kind": "symbol",
      "role": "symbol",
      "title": "PHPickerFilter",
      "type": "topic",
      "url": "/documentation/photosui/phpickerfilter-c.class"
    },
    "doc://com.apple.photokit/documentation/PhotosUI/PHPickerMode-c.enum": {
      "abstract": [
        {
          "text": "Layout options that determine how the picker orders photos visually.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "PHPickerMode"
        }
      ],
      "identifier": "doc://com.apple.photokit/documentation/PhotosUI/PHPickerMode-c.enum",
      "kind": "symbol",
      "role": "symbol",
      "title": "PHPickerMode",
      "type": "topic",
      "url": "/documentation/photosui/phpickermode-c.enum"
    },
    "doc://com.apple.photokit/documentation/PhotosUI/PHPickerResult-c.class": {
      "abstract": [
        {
          "text": "Types that represent a selected asset from the user’s photo library.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "PHPickerResult"
        }
      ],
      "identifier": "doc://com.apple.photokit/documentation/PhotosUI/PHPickerResult-c.class",
      "kind": "symbol",
      "role": "symbol",
      "title": "PHPickerResult",
      "type": "topic",
      "url": "/documentation/photosui/phpickerresult-c.class"
    },
    "doc://com.apple.photokit/documentation/PhotosUI/PHPickerUpdateConfiguration": {
      "abstract": [
        {
          "text": "An object that defines the aspects of a photo picker’s appearance that can change while it’s presented.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "PHPickerUpdateConfiguration"
        }
      ],
      "identifier": "doc://com.apple.photokit/documentation/PhotosUI/PHPickerUpdateConfiguration",
      "kind": "symbol",
      "role": "symbol",
      "title": "PHPickerUpdateConfiguration",
      "type": "topic",
      "url": "/documentation/photosui/phpickerupdateconfiguration"
    },
    "doc://com.apple.photokit/documentation/PhotosUI/PHPickerViewController": {
      "abstract": [
        {
          "text": "A view controller that provides the user interface for choosing assets from the photo library.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "PHPickerViewController"
        }
      ],
      "identifier": "doc://com.apple.photokit/documentation/PhotosUI/PHPickerViewController",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PHPickerViewController"
        }
      ],
      "role": "symbol",
      "title": "PHPickerViewController",
      "type": "topic",
      "url": "/documentation/photosui/phpickerviewcontroller"
    },
    "doc://com.externally.resolved.symbol/c:objc(cs)NSObject": {
      "abstract": [
        {
          "text": "The root class of most Objective-C class hierarchies, from which subclasses inherit a basic interface to the runtime system and the ability to behave as Objective-C objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "class "
        },
        {
          "kind": "identifier",
          "text": "NSObject"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSObject",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSObject",
      "type": "topic",
      "url": "/documentation/objectivec/nsobject"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)NSCopying": {
      "abstract": [
        {
          "text": "A protocol that objects adopt to provide functional copies of themselves.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "protocol "
        },
        {
          "kind": "identifier",
          "text": "NSCopying"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSCopying",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSCopying",
      "type": "topic",
      "url": "/documentation/foundation/nscopying"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/c:objc(cs)NSObject"
      ],
      "kind": "relationships",
      "title": "Inherits From",
      "type": "inheritsFrom"
    },
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/c:objc(pl)NSCopying"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Photos-picker-for-UIKit-AppKit",
      "generated": true,
      "identifiers": [
        "doc://com.apple.photokit/documentation/PhotosUI/PHPickerViewController",
        "doc://com.apple.photokit/documentation/PhotosUI/PHPickerFilter-c.class",
        "doc://com.apple.photokit/documentation/PhotosUI/PHPickerResult-c.class"
      ],
      "title": "Photos picker for UIKit, AppKit"
    }
  ],
  "topicSections": [
    {
      "anchor": "Creating-a-configuration",
      "identifiers": [
        "doc://com.apple.photokit/documentation/PhotosUI/PHPickerConfiguration-c.class/init",
        "doc://com.apple.photokit/documentation/PhotosUI/PHPickerConfiguration-c.class/initWithPhotoLibrary:"
      ],
      "title": "Creating a configuration"
    },
    {
      "anchor": "Filtering-asset-types",
      "identifiers": [
        "doc://com.apple.photokit/documentation/PhotosUI/PHPickerConfiguration-c.class/filter",
        "doc://com.apple.photokit/documentation/PhotosUI/PHPickerFilter-c.class"
      ],
      "title": "Filtering asset types"
    },
    {
      "anchor": "Selecting-the-preferred-asset-representation",
      "identifiers": [
        "doc://com.apple.photokit/documentation/PhotosUI/PHPickerConfiguration-c.class/preferredAssetRepresentationMode",
        "doc://com.apple.photokit/documentation/PhotosUI/PHPickerConfigurationAssetRepresentationMode"
      ],
      "title": "Selecting the preferred asset representation"
    },
    {
      "anchor": "Preselecting-assets",
      "identifiers": [
        "doc://com.apple.photokit/documentation/PhotosUI/PHPickerConfiguration-c.class/preselectedAssetIdentifiers"
      ],
      "title": "Preselecting assets"
    },
    {
      "anchor": "Setting-the-selection-limit",
      "identifiers": [
        "doc://com.apple.photokit/documentation/PhotosUI/PHPickerConfiguration-c.class/selectionLimit",
        "doc://com.apple.photokit/documentation/PhotosUI/PHPickerConfiguration-c.class/selection",
        "doc://com.apple.photokit/documentation/PhotosUI/PHPickerConfigurationSelection"
      ],
      "title": "Setting the selection limit"
    },
    {
      "anchor": "Customizing-picker-appearance-and-behavior",
      "identifiers": [
        "doc://com.apple.photokit/documentation/PhotosUI/PHPickerConfiguration-c.class/mode",
        "doc://com.apple.photokit/documentation/PhotosUI/PHPickerMode-c.enum",
        "doc://com.apple.photokit/documentation/PhotosUI/PHPickerConfiguration-c.class/disabledCapabilities",
        "doc://com.apple.photokit/documentation/PhotosUI/PHPickerCapabilities",
        "doc://com.apple.photokit/documentation/PhotosUI/PHPickerConfiguration-c.class/edgesWithoutContentMargins",
        "doc://com.apple.photokit/documentation/PhotosUI/PHPickerUpdateConfiguration"
      ],
      "title": "Customizing picker appearance and behavior"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1PhotosUI~1PHPickerCapabilities/title",
          "value": "PHPickerCapabilities"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1PhotosUI~1PHPickerCapabilities/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PHPickerCapabilities"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1PhotosUI~1PHPickerCapabilities/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "PHPickerCapabilities"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1PhotosUI~1PHPickerConfigurationSelection/title",
          "value": "PHPickerConfigurationSelection"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1PhotosUI~1PHPickerConfigurationSelection/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PHPickerConfigurationSelection"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1PhotosUI~1PHPickerConfigurationSelection/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "PHPickerConfigurationSelection"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1PhotosUI~1PHPickerConfigurationAssetRepresentationMode/title",
          "value": "PHPickerConfigurationAssetRepresentationMode"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1PhotosUI~1PHPickerConfigurationAssetRepresentationMode/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PHPickerConfigurationAssetRepresentationMode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1PhotosUI~1PHPickerConfigurationAssetRepresentationMode/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "PHPickerConfigurationAssetRepresentationMode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1PhotosUI~1PHPickerViewController/title",
          "value": "PHPickerViewController"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1PhotosUI~1PHPickerViewController/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PHPickerViewController"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1PhotosUI~1PHPickerViewController/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "PHPickerViewController"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/photosui/phpickerconfiguration-c.class"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
