{
  "abstract": [
    {
      "text": "An object that defines the aspects of a photo picker’s appearance that can change while it’s presented.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.photokit/documentation/PhotosUI"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "occ",
    "url": "doc://com.apple.photokit/documentation/PhotosUI/PHPickerUpdateConfiguration"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(cs)PHPickerUpdateConfiguration",
    "fragments": [
      {
        "kind": "identifier",
        "text": "PHPickerUpdateConfiguration"
      }
    ],
    "modules": [
      {
        "name": "PhotosUI"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "PHPickerUpdateConfiguration"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "17.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "17.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "17.0",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "14.0",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Class",
    "symbolKind": "class",
    "title": "PHPickerUpdateConfiguration"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "occ"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "@interface"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "PHPickerUpdateConfiguration"
            },
            {
              "kind": "text",
              "text": " : "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSObject",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)NSObject",
              "text": "NSObject"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "While a photos picker is visible, you can use an instance of this object to change its ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.photokit/documentation/PhotosUI/PHPickerConfiguration-c.class/edgesWithoutContentMargins",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " or ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.photokit/documentation/PhotosUI/PHPickerConfiguration-swift.struct/selectionLimit",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " properties. To do that, create and configure an instance of this object and pass it to the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.photokit/documentation/PhotosUI/PHPickerViewController",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " method ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.photokit/documentation/PhotosUI/PHPickerViewController/updatePickerUsingConfiguration:",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ".",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.photokit/documentation/PhotosUI": {
      "abstract": [
        {
          "text": "Present a person’s photo library using a picker interface, display Live Photos, or extend the Photos app with custom functionality.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.photokit/documentation/PhotosUI",
      "kind": "symbol",
      "role": "collection",
      "title": "PhotosUI",
      "type": "topic",
      "url": "/documentation/photosui"
    },
    "doc://com.apple.photokit/documentation/PhotosUI/PHPickerCapabilities": {
      "abstract": [
        {
          "text": "Options that customize the look and behavior of the photos picker.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "PHPickerCapabilities"
        }
      ],
      "identifier": "doc://com.apple.photokit/documentation/PhotosUI/PHPickerCapabilities",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PHPickerCapabilities"
        }
      ],
      "role": "symbol",
      "title": "PHPickerCapabilities",
      "type": "topic",
      "url": "/documentation/photosui/phpickercapabilities"
    },
    "doc://com.apple.photokit/documentation/PhotosUI/PHPickerConfiguration-c.class/disabledCapabilities": {
      "abstract": [
        {
          "text": "The aspects of a photo picker’s default appearance that your app can disable.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "disabledCapabilities"
        }
      ],
      "identifier": "doc://com.apple.photokit/documentation/PhotosUI/PHPickerConfiguration-c.class/disabledCapabilities",
      "kind": "symbol",
      "role": "symbol",
      "title": "disabledCapabilities",
      "type": "topic",
      "url": "/documentation/photosui/phpickerconfiguration-c.class/disabledcapabilities"
    },
    "doc://com.apple.photokit/documentation/PhotosUI/PHPickerConfiguration-c.class/edgesWithoutContentMargins": {
      "abstract": [
        {
          "text": "The portions of a photo picker’s perimeter that are borderless.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "edgesWithoutContentMargins"
        }
      ],
      "identifier": "doc://com.apple.photokit/documentation/PhotosUI/PHPickerConfiguration-c.class/edgesWithoutContentMargins",
      "kind": "symbol",
      "role": "symbol",
      "title": "edgesWithoutContentMargins",
      "type": "topic",
      "url": "/documentation/photosui/phpickerconfiguration-c.class/edgeswithoutcontentmargins"
    },
    "doc://com.apple.photokit/documentation/PhotosUI/PHPickerConfiguration-c.class/mode": {
      "abstract": [
        {
          "text": "A layout type for the photos in the picker’s view.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "mode"
        }
      ],
      "identifier": "doc://com.apple.photokit/documentation/PhotosUI/PHPickerConfiguration-c.class/mode",
      "kind": "symbol",
      "role": "symbol",
      "title": "mode",
      "type": "topic",
      "url": "/documentation/photosui/phpickerconfiguration-c.class/mode"
    },
    "doc://com.apple.photokit/documentation/PhotosUI/PHPickerConfiguration-swift.struct/selectionLimit": {
      "abstract": [
        {
          "text": "The maximum number of selections the user can make.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "selectionLimit"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.photokit/documentation/PhotosUI/PHPickerConfiguration-swift.struct/selectionLimit",
      "kind": "symbol",
      "role": "symbol",
      "title": "selectionLimit",
      "type": "topic",
      "url": "/documentation/photosui/phpickerconfiguration-swift.struct/selectionlimit"
    },
    "doc://com.apple.photokit/documentation/PhotosUI/PHPickerMode-c.enum": {
      "abstract": [
        {
          "text": "Layout options that determine how the picker orders photos visually.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "PHPickerMode"
        }
      ],
      "identifier": "doc://com.apple.photokit/documentation/PhotosUI/PHPickerMode-c.enum",
      "kind": "symbol",
      "role": "symbol",
      "title": "PHPickerMode",
      "type": "topic",
      "url": "/documentation/photosui/phpickermode-c.enum"
    },
    "doc://com.apple.photokit/documentation/PhotosUI/PHPickerUpdateConfiguration": {
      "abstract": [
        {
          "text": "An object that defines the aspects of a photo picker’s appearance that can change while it’s presented.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "PHPickerUpdateConfiguration"
        }
      ],
      "identifier": "doc://com.apple.photokit/documentation/PhotosUI/PHPickerUpdateConfiguration",
      "kind": "symbol",
      "role": "symbol",
      "title": "PHPickerUpdateConfiguration",
      "type": "topic",
      "url": "/documentation/photosui/phpickerupdateconfiguration"
    },
    "doc://com.apple.photokit/documentation/PhotosUI/PHPickerUpdateConfiguration/edgesWithoutContentMargins": {
      "abstract": [
        {
          "text": "The portions of a photo picker’s permiter that are borderless.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "edgesWithoutContentMargins"
        }
      ],
      "identifier": "doc://com.apple.photokit/documentation/PhotosUI/PHPickerUpdateConfiguration/edgesWithoutContentMargins",
      "kind": "symbol",
      "role": "symbol",
      "title": "edgesWithoutContentMargins",
      "type": "topic",
      "url": "/documentation/photosui/phpickerupdateconfiguration/edgeswithoutcontentmargins"
    },
    "doc://com.apple.photokit/documentation/PhotosUI/PHPickerUpdateConfiguration/selectionLimit": {
      "abstract": [
        {
          "text": "The maximum number of selections the user can make.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "selectionLimit"
        }
      ],
      "identifier": "doc://com.apple.photokit/documentation/PhotosUI/PHPickerUpdateConfiguration/selectionLimit",
      "kind": "symbol",
      "role": "symbol",
      "title": "selectionLimit",
      "type": "topic",
      "url": "/documentation/photosui/phpickerupdateconfiguration/selectionlimit"
    },
    "doc://com.apple.photokit/documentation/PhotosUI/PHPickerViewController": {
      "abstract": [
        {
          "text": "A view controller that provides the user interface for choosing assets from the photo library.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "PHPickerViewController"
        }
      ],
      "identifier": "doc://com.apple.photokit/documentation/PhotosUI/PHPickerViewController",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PHPickerViewController"
        }
      ],
      "role": "symbol",
      "title": "PHPickerViewController",
      "type": "topic",
      "url": "/documentation/photosui/phpickerviewcontroller"
    },
    "doc://com.apple.photokit/documentation/PhotosUI/PHPickerViewController/updatePickerUsingConfiguration:": {
      "abstract": [
        {
          "text": "Customizes your app’s photo picker according to the given configuration.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "- "
        },
        {
          "kind": "identifier",
          "text": "updatePickerUsingConfiguration:"
        }
      ],
      "identifier": "doc://com.apple.photokit/documentation/PhotosUI/PHPickerViewController/updatePickerUsingConfiguration:",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "updatePickerUsingConfiguration:"
        }
      ],
      "role": "symbol",
      "title": "updatePickerUsingConfiguration:",
      "type": "topic",
      "url": "/documentation/photosui/phpickerviewcontroller/updatepickerusingconfiguration:"
    },
    "doc://com.externally.resolved.symbol/c:objc(cs)NSObject": {
      "abstract": [
        {
          "text": "The root class of most Objective-C class hierarchies, from which subclasses inherit a basic interface to the runtime system and the ability to behave as Objective-C objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "class "
        },
        {
          "kind": "identifier",
          "text": "NSObject"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSObject",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSObject",
      "type": "topic",
      "url": "/documentation/objectivec/nsobject"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)NSCopying": {
      "abstract": [
        {
          "text": "A protocol that objects adopt to provide functional copies of themselves.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "protocol "
        },
        {
          "kind": "identifier",
          "text": "NSCopying"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSCopying",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSCopying",
      "type": "topic",
      "url": "/documentation/foundation/nscopying"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/c:objc(cs)NSObject"
      ],
      "kind": "relationships",
      "title": "Inherits From",
      "type": "inheritsFrom"
    },
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/c:objc(pl)NSCopying"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Customizing-picker-appearance-and-behavior",
      "generated": true,
      "identifiers": [
        "doc://com.apple.photokit/documentation/PhotosUI/PHPickerConfiguration-c.class/mode",
        "doc://com.apple.photokit/documentation/PhotosUI/PHPickerMode-c.enum",
        "doc://com.apple.photokit/documentation/PhotosUI/PHPickerConfiguration-c.class/disabledCapabilities",
        "doc://com.apple.photokit/documentation/PhotosUI/PHPickerCapabilities",
        "doc://com.apple.photokit/documentation/PhotosUI/PHPickerConfiguration-c.class/edgesWithoutContentMargins"
      ],
      "title": "Customizing picker appearance and behavior"
    }
  ],
  "topicSections": [
    {
      "anchor": "Adjusting-selection-limits",
      "identifiers": [
        "doc://com.apple.photokit/documentation/PhotosUI/PHPickerUpdateConfiguration/selectionLimit"
      ],
      "title": "Adjusting selection limits"
    },
    {
      "anchor": "Adjusting-content-margins",
      "identifiers": [
        "doc://com.apple.photokit/documentation/PhotosUI/PHPickerUpdateConfiguration/edgesWithoutContentMargins"
      ],
      "title": "Adjusting content margins"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1PhotosUI~1PHPickerCapabilities/title",
          "value": "PHPickerCapabilities"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1PhotosUI~1PHPickerCapabilities/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PHPickerCapabilities"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1PhotosUI~1PHPickerCapabilities/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "PHPickerCapabilities"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1PhotosUI~1PHPickerViewController/title",
          "value": "PHPickerViewController"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1PhotosUI~1PHPickerViewController/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PHPickerViewController"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1PhotosUI~1PHPickerViewController/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "PHPickerViewController"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/photosui/phpickerupdateconfiguration"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
