{
  "abstract": [
    {
      "text": "A type that defines the filter to apply to the photo library.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.photokit/documentation/PhotosUI"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "occ",
    "url": "doc://com.apple.photokit/documentation/PhotosUI/PHPickerFilter-c.class"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(cs)PHPickerFilter",
    "fragments": [
      {
        "kind": "identifier",
        "text": "PHPickerFilter"
      }
    ],
    "modules": [
      {
        "name": "PhotosUI"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "PHPickerFilter"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "14.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "14.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "14.0",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.0",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Class",
    "symbolKind": "class",
    "title": "PHPickerFilter"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "occ"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "@interface"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "PHPickerFilter"
            },
            {
              "kind": "text",
              "text": " : "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSObject",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)NSObject",
              "text": "NSObject"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.photokit/documentation/PhotosUI": {
      "abstract": [
        {
          "text": "Present a person’s photo library using a picker interface, display Live Photos, or extend the Photos app with custom functionality.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.photokit/documentation/PhotosUI",
      "kind": "symbol",
      "role": "collection",
      "title": "PhotosUI",
      "type": "topic",
      "url": "/documentation/photosui"
    },
    "doc://com.apple.photokit/documentation/PhotosUI/PHPickerConfiguration-c.class": {
      "abstract": [
        {
          "text": "An object that contains information about how to configure a picker view controller.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "PHPickerConfiguration"
        }
      ],
      "identifier": "doc://com.apple.photokit/documentation/PhotosUI/PHPickerConfiguration-c.class",
      "kind": "symbol",
      "role": "symbol",
      "title": "PHPickerConfiguration",
      "type": "topic",
      "url": "/documentation/photosui/phpickerconfiguration-c.class"
    },
    "doc://com.apple.photokit/documentation/PhotosUI/PHPickerFilter-c.class": {
      "abstract": [
        {
          "text": "A type that defines the filter to apply to the photo library.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "PHPickerFilter"
        }
      ],
      "identifier": "doc://com.apple.photokit/documentation/PhotosUI/PHPickerFilter-c.class",
      "kind": "symbol",
      "role": "symbol",
      "title": "PHPickerFilter",
      "type": "topic",
      "url": "/documentation/photosui/phpickerfilter-c.class"
    },
    "doc://com.apple.photokit/documentation/PhotosUI/PHPickerFilter-c.class/allFilterMatchingSubfilters:": {
      "abstract": [
        {
          "text": "Creates a new filter that includes only the filters you specify.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "+ "
        },
        {
          "kind": "identifier",
          "text": "allFilterMatchingSubfilters:"
        }
      ],
      "identifier": "doc://com.apple.photokit/documentation/PhotosUI/PHPickerFilter-c.class/allFilterMatchingSubfilters:",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "allFilterMatchingSubfilters:"
        }
      ],
      "role": "symbol",
      "title": "allFilterMatchingSubfilters:",
      "type": "topic",
      "url": "/documentation/photosui/phpickerfilter-c.class/allfiltermatchingsubfilters:"
    },
    "doc://com.apple.photokit/documentation/PhotosUI/PHPickerFilter-c.class/anyFilterMatchingSubfilters:": {
      "abstract": [
        {
          "text": "Creates a new filter by combining the filters in the array.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "+ "
        },
        {
          "kind": "identifier",
          "text": "anyFilterMatchingSubfilters:"
        }
      ],
      "identifier": "doc://com.apple.photokit/documentation/PhotosUI/PHPickerFilter-c.class/anyFilterMatchingSubfilters:",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "anyFilterMatchingSubfilters:"
        }
      ],
      "role": "symbol",
      "title": "anyFilterMatchingSubfilters:",
      "type": "topic",
      "url": "/documentation/photosui/phpickerfilter-c.class/anyfiltermatchingsubfilters:"
    },
    "doc://com.apple.photokit/documentation/PhotosUI/PHPickerFilter-c.class/burstsFilter": {
      "abstract": [
        {
          "text": "A filter that represents assets with multiple high-speed photos.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "burstsFilter"
        }
      ],
      "identifier": "doc://com.apple.photokit/documentation/PhotosUI/PHPickerFilter-c.class/burstsFilter",
      "kind": "symbol",
      "role": "symbol",
      "title": "burstsFilter",
      "type": "topic",
      "url": "/documentation/photosui/phpickerfilter-c.class/burstsfilter"
    },
    "doc://com.apple.photokit/documentation/PhotosUI/PHPickerFilter-c.class/cinematicVideosFilter": {
      "abstract": [
        {
          "text": "A filter that represents videos with a shallow depth of field and focus transitions.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "cinematicVideosFilter"
        }
      ],
      "identifier": "doc://com.apple.photokit/documentation/PhotosUI/PHPickerFilter-c.class/cinematicVideosFilter",
      "kind": "symbol",
      "role": "symbol",
      "title": "cinematicVideosFilter",
      "type": "topic",
      "url": "/documentation/photosui/phpickerfilter-c.class/cinematicvideosfilter"
    },
    "doc://com.apple.photokit/documentation/PhotosUI/PHPickerFilter-c.class/depthEffectPhotosFilter": {
      "abstract": [
        {
          "text": "A filter that represents photos with depth information.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "depthEffectPhotosFilter"
        }
      ],
      "identifier": "doc://com.apple.photokit/documentation/PhotosUI/PHPickerFilter-c.class/depthEffectPhotosFilter",
      "kind": "symbol",
      "role": "symbol",
      "title": "depthEffectPhotosFilter",
      "type": "topic",
      "url": "/documentation/photosui/phpickerfilter-c.class/deptheffectphotosfilter"
    },
    "doc://com.apple.photokit/documentation/PhotosUI/PHPickerFilter-c.class/imagesFilter": {
      "abstract": [
        {
          "text": "A filter that represents images, and includes Live Photos.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "imagesFilter"
        }
      ],
      "identifier": "doc://com.apple.photokit/documentation/PhotosUI/PHPickerFilter-c.class/imagesFilter",
      "kind": "symbol",
      "role": "symbol",
      "title": "imagesFilter",
      "type": "topic",
      "url": "/documentation/photosui/phpickerfilter-c.class/imagesfilter"
    },
    "doc://com.apple.photokit/documentation/PhotosUI/PHPickerFilter-c.class/livePhotosFilter": {
      "abstract": [
        {
          "text": "A filter that represents Live Photos.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "livePhotosFilter"
        }
      ],
      "identifier": "doc://com.apple.photokit/documentation/PhotosUI/PHPickerFilter-c.class/livePhotosFilter",
      "kind": "symbol",
      "role": "symbol",
      "title": "livePhotosFilter",
      "type": "topic",
      "url": "/documentation/photosui/phpickerfilter-c.class/livephotosfilter"
    },
    "doc://com.apple.photokit/documentation/PhotosUI/PHPickerFilter-c.class/notFilterOfSubfilter:": {
      "abstract": [
        {
          "text": "Creates a new filter that excludes the filter you specify.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "+ "
        },
        {
          "kind": "identifier",
          "text": "notFilterOfSubfilter:"
        }
      ],
      "identifier": "doc://com.apple.photokit/documentation/PhotosUI/PHPickerFilter-c.class/notFilterOfSubfilter:",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "notFilterOfSubfilter:"
        }
      ],
      "role": "symbol",
      "title": "notFilterOfSubfilter:",
      "type": "topic",
      "url": "/documentation/photosui/phpickerfilter-c.class/notfilterofsubfilter:"
    },
    "doc://com.apple.photokit/documentation/PhotosUI/PHPickerFilter-c.class/panoramasFilter": {
      "abstract": [
        {
          "text": "A filter that represents panorama photos.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "panoramasFilter"
        }
      ],
      "identifier": "doc://com.apple.photokit/documentation/PhotosUI/PHPickerFilter-c.class/panoramasFilter",
      "kind": "symbol",
      "role": "symbol",
      "title": "panoramasFilter",
      "type": "topic",
      "url": "/documentation/photosui/phpickerfilter-c.class/panoramasfilter"
    },
    "doc://com.apple.photokit/documentation/PhotosUI/PHPickerFilter-c.class/playbackStyleFilter:": {
      "abstract": [
        {
          "text": "Creates a new filter by using the playback style you specify.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "+ "
        },
        {
          "kind": "identifier",
          "text": "playbackStyleFilter:"
        }
      ],
      "identifier": "doc://com.apple.photokit/documentation/PhotosUI/PHPickerFilter-c.class/playbackStyleFilter:",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "playbackStyleFilter:"
        }
      ],
      "role": "symbol",
      "title": "playbackStyleFilter:",
      "type": "topic",
      "url": "/documentation/photosui/phpickerfilter-c.class/playbackstylefilter:"
    },
    "doc://com.apple.photokit/documentation/PhotosUI/PHPickerFilter-c.class/screenRecordingsFilter": {
      "abstract": [
        {
          "text": "A filter that represents screen recordings.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "screenRecordingsFilter"
        }
      ],
      "identifier": "doc://com.apple.photokit/documentation/PhotosUI/PHPickerFilter-c.class/screenRecordingsFilter",
      "kind": "symbol",
      "role": "symbol",
      "title": "screenRecordingsFilter",
      "type": "topic",
      "url": "/documentation/photosui/phpickerfilter-c.class/screenrecordingsfilter"
    },
    "doc://com.apple.photokit/documentation/PhotosUI/PHPickerFilter-c.class/screenshotsFilter": {
      "abstract": [
        {
          "text": "A filter that represents screenshots.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "screenshotsFilter"
        }
      ],
      "identifier": "doc://com.apple.photokit/documentation/PhotosUI/PHPickerFilter-c.class/screenshotsFilter",
      "kind": "symbol",
      "role": "symbol",
      "title": "screenshotsFilter",
      "type": "topic",
      "url": "/documentation/photosui/phpickerfilter-c.class/screenshotsfilter"
    },
    "doc://com.apple.photokit/documentation/PhotosUI/PHPickerFilter-c.class/slomoVideosFilter": {
      "abstract": [
        {
          "text": "A filter that represents slow-motion videos.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "slomoVideosFilter"
        }
      ],
      "identifier": "doc://com.apple.photokit/documentation/PhotosUI/PHPickerFilter-c.class/slomoVideosFilter",
      "kind": "symbol",
      "role": "symbol",
      "title": "slomoVideosFilter",
      "type": "topic",
      "url": "/documentation/photosui/phpickerfilter-c.class/slomovideosfilter"
    },
    "doc://com.apple.photokit/documentation/PhotosUI/PHPickerFilter-c.class/spatialMediaFilter": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "spatialMediaFilter"
        }
      ],
      "identifier": "doc://com.apple.photokit/documentation/PhotosUI/PHPickerFilter-c.class/spatialMediaFilter",
      "kind": "symbol",
      "role": "symbol",
      "title": "spatialMediaFilter",
      "type": "topic",
      "url": "/documentation/photosui/phpickerfilter-c.class/spatialmediafilter"
    },
    "doc://com.apple.photokit/documentation/PhotosUI/PHPickerFilter-c.class/timelapseVideosFilter": {
      "abstract": [
        {
          "text": "A filter that represents time-lapse videos.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "timelapseVideosFilter"
        }
      ],
      "identifier": "doc://com.apple.photokit/documentation/PhotosUI/PHPickerFilter-c.class/timelapseVideosFilter",
      "kind": "symbol",
      "role": "symbol",
      "title": "timelapseVideosFilter",
      "type": "topic",
      "url": "/documentation/photosui/phpickerfilter-c.class/timelapsevideosfilter"
    },
    "doc://com.apple.photokit/documentation/PhotosUI/PHPickerFilter-c.class/videosFilter": {
      "abstract": [
        {
          "text": "A filter that represents video assets.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "videosFilter"
        }
      ],
      "identifier": "doc://com.apple.photokit/documentation/PhotosUI/PHPickerFilter-c.class/videosFilter",
      "kind": "symbol",
      "role": "symbol",
      "title": "videosFilter",
      "type": "topic",
      "url": "/documentation/photosui/phpickerfilter-c.class/videosfilter"
    },
    "doc://com.apple.photokit/documentation/PhotosUI/PHPickerResult-c.class": {
      "abstract": [
        {
          "text": "Types that represent a selected asset from the user’s photo library.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "PHPickerResult"
        }
      ],
      "identifier": "doc://com.apple.photokit/documentation/PhotosUI/PHPickerResult-c.class",
      "kind": "symbol",
      "role": "symbol",
      "title": "PHPickerResult",
      "type": "topic",
      "url": "/documentation/photosui/phpickerresult-c.class"
    },
    "doc://com.apple.photokit/documentation/PhotosUI/PHPickerViewController": {
      "abstract": [
        {
          "text": "A view controller that provides the user interface for choosing assets from the photo library.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "PHPickerViewController"
        }
      ],
      "identifier": "doc://com.apple.photokit/documentation/PhotosUI/PHPickerViewController",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PHPickerViewController"
        }
      ],
      "role": "symbol",
      "title": "PHPickerViewController",
      "type": "topic",
      "url": "/documentation/photosui/phpickerviewcontroller"
    },
    "doc://com.externally.resolved.symbol/c:objc(cs)NSObject": {
      "abstract": [
        {
          "text": "The root class of most Objective-C class hierarchies, from which subclasses inherit a basic interface to the runtime system and the ability to behave as Objective-C objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "class "
        },
        {
          "kind": "identifier",
          "text": "NSObject"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSObject",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSObject",
      "type": "topic",
      "url": "/documentation/objectivec/nsobject"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)NSCopying": {
      "abstract": [
        {
          "text": "A protocol that objects adopt to provide functional copies of themselves.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "protocol "
        },
        {
          "kind": "identifier",
          "text": "NSCopying"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSCopying",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSCopying",
      "type": "topic",
      "url": "/documentation/foundation/nscopying"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/c:objc(cs)NSObject"
      ],
      "kind": "relationships",
      "title": "Inherits From",
      "type": "inheritsFrom"
    },
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/c:objc(pl)NSCopying"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Photos-picker-for-UIKit-AppKit",
      "generated": true,
      "identifiers": [
        "doc://com.apple.photokit/documentation/PhotosUI/PHPickerViewController",
        "doc://com.apple.photokit/documentation/PhotosUI/PHPickerConfiguration-c.class",
        "doc://com.apple.photokit/documentation/PhotosUI/PHPickerResult-c.class"
      ],
      "title": "Photos picker for UIKit, AppKit"
    }
  ],
  "topicSections": [
    {
      "anchor": "Creating-Filters",
      "identifiers": [
        "doc://com.apple.photokit/documentation/PhotosUI/PHPickerFilter-c.class/playbackStyleFilter:",
        "doc://com.apple.photokit/documentation/PhotosUI/PHPickerFilter-c.class/allFilterMatchingSubfilters:",
        "doc://com.apple.photokit/documentation/PhotosUI/PHPickerFilter-c.class/notFilterOfSubfilter:"
      ],
      "title": "Creating Filters"
    },
    {
      "anchor": "Getting-Filter-Constants",
      "identifiers": [
        "doc://com.apple.photokit/documentation/PhotosUI/PHPickerFilter-c.class/burstsFilter",
        "doc://com.apple.photokit/documentation/PhotosUI/PHPickerFilter-c.class/cinematicVideosFilter",
        "doc://com.apple.photokit/documentation/PhotosUI/PHPickerFilter-c.class/depthEffectPhotosFilter",
        "doc://com.apple.photokit/documentation/PhotosUI/PHPickerFilter-c.class/panoramasFilter",
        "doc://com.apple.photokit/documentation/PhotosUI/PHPickerFilter-c.class/screenRecordingsFilter",
        "doc://com.apple.photokit/documentation/PhotosUI/PHPickerFilter-c.class/screenshotsFilter",
        "doc://com.apple.photokit/documentation/PhotosUI/PHPickerFilter-c.class/slomoVideosFilter",
        "doc://com.apple.photokit/documentation/PhotosUI/PHPickerFilter-c.class/timelapseVideosFilter"
      ],
      "title": "Getting Filter Constants"
    },
    {
      "anchor": "Comparing-Filters",
      "identifiers": [
        "doc://com.apple.photokit/documentation/PhotosUI/PHPickerFilter-c.class/imagesFilter",
        "doc://com.apple.photokit/documentation/PhotosUI/PHPickerFilter-c.class/livePhotosFilter",
        "doc://com.apple.photokit/documentation/PhotosUI/PHPickerFilter-c.class/videosFilter",
        "doc://com.apple.photokit/documentation/PhotosUI/PHPickerFilter-c.class/anyFilterMatchingSubfilters:"
      ],
      "title": "Comparing Filters"
    },
    {
      "anchor": "Type-Properties",
      "generated": true,
      "identifiers": [
        "doc://com.apple.photokit/documentation/PhotosUI/PHPickerFilter-c.class/spatialMediaFilter"
      ],
      "title": "Type Properties"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1PhotosUI~1PHPickerViewController/title",
          "value": "PHPickerViewController"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1PhotosUI~1PHPickerViewController/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PHPickerViewController"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1PhotosUI~1PHPickerViewController/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "PHPickerViewController"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/photosui/phpickerfilter-c.class"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
