{
  "abstract": [
    {
      "text": "The type descriptor of a project extension.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.photokit/documentation/PhotosUI"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.photokit/documentation/PhotosUI/PHProjectType"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@T@PHProjectType",
    "fragments": [
      {
        "kind": "keyword",
        "text": "struct"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "PHProjectType"
      }
    ],
    "modules": [
      {
        "name": "PhotosUI"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "PHProjectType"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Structure",
    "symbolKind": "struct",
    "title": "PHProjectType"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "macOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "struct"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "PHProjectType"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.photokit/documentation/PhotosUI": {
      "abstract": [
        {
          "text": "Present a person’s photo library using a picker interface, display Live Photos, or extend the Photos app with custom functionality.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.photokit/documentation/PhotosUI",
      "kind": "symbol",
      "role": "collection",
      "title": "PhotosUI",
      "type": "topic",
      "url": "/documentation/photosui"
    },
    "doc://com.apple.photokit/documentation/PhotosUI/PHProjectInfo/CreationSource-swift.enum": {
      "abstract": [
        {
          "text": "Defines the source of a project extension.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CreationSource"
        }
      ],
      "identifier": "doc://com.apple.photokit/documentation/PhotosUI/PHProjectInfo/CreationSource-swift.enum",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CreationSource"
        }
      ],
      "role": "symbol",
      "title": "PHProjectInfo.CreationSource",
      "type": "topic",
      "url": "/documentation/photosui/phprojectinfo/creationsource-swift.enum"
    },
    "doc://com.apple.photokit/documentation/PhotosUI/PHProjectInfo/creationSource-swift.property": {
      "abstract": [
        {
          "text": "The source from which the project was created.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "creationSource"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)PHProjectInfo",
          "text": "PHProjectInfo"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@PHProjectCreationSource",
          "text": "CreationSource"
        }
      ],
      "identifier": "doc://com.apple.photokit/documentation/PhotosUI/PHProjectInfo/creationSource-swift.property",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "creationSource"
        }
      ],
      "role": "symbol",
      "title": "creationSource",
      "type": "topic",
      "url": "/documentation/photosui/phprojectinfo/creationsource-swift.property"
    },
    "doc://com.apple.photokit/documentation/PhotosUI/PHProjectInfo/projectType": {
      "abstract": [
        {
          "text": "The project type that the user selected from the project extension options.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "projectType"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@PHProjectType",
          "text": "PHProjectType"
        }
      ],
      "identifier": "doc://com.apple.photokit/documentation/PhotosUI/PHProjectInfo/projectType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "projectType"
        }
      ],
      "role": "symbol",
      "title": "projectType",
      "type": "topic",
      "url": "/documentation/photosui/phprojectinfo/projecttype"
    },
    "doc://com.apple.photokit/documentation/PhotosUI/PHProjectInfo/sections": {
      "abstract": [
        {
          "text": "An array of project sections, each containing one or more section content objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "sections"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)PHProjectSection",
          "text": "PHProjectSection"
        },
        {
          "kind": "text",
          "text": "]"
        }
      ],
      "identifier": "doc://com.apple.photokit/documentation/PhotosUI/PHProjectInfo/sections",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "sections"
        }
      ],
      "role": "symbol",
      "title": "sections",
      "type": "topic",
      "url": "/documentation/photosui/phprojectinfo/sections"
    },
    "doc://com.apple.photokit/documentation/PhotosUI/PHProjectType": {
      "abstract": [
        {
          "text": "The type descriptor of a project extension.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "PHProjectType"
        }
      ],
      "identifier": "doc://com.apple.photokit/documentation/PhotosUI/PHProjectType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PHProjectType"
        }
      ],
      "role": "symbol",
      "title": "PHProjectType",
      "type": "topic",
      "url": "/documentation/photosui/phprojecttype"
    },
    "doc://com.apple.photokit/documentation/PhotosUI/PHProjectType/init(_:)": {
      "abstract": [
        {
          "text": "Initializes a project type from a string.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.photokit/documentation/PhotosUI/PHProjectType/init(_:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "init(_:)",
      "type": "topic",
      "url": "/documentation/photosui/phprojecttype/init(_:)"
    },
    "doc://com.apple.photokit/documentation/PhotosUI/PHProjectType/init(rawValue:)": {
      "abstract": [
        {
          "text": "Initializes a project type from its raw string value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "rawValue"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.photokit/documentation/PhotosUI/PHProjectType/init(rawValue:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "init(rawValue:)",
      "type": "topic",
      "url": "/documentation/photosui/phprojecttype/init(rawvalue:)"
    },
    "doc://com.apple.photokit/documentation/PhotosUI/PHProjectType/undefined": {
      "abstract": [
        {
          "text": "An undefined project type.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "undefined"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@PHProjectType",
          "text": "PHProjectType"
        }
      ],
      "identifier": "doc://com.apple.photokit/documentation/PhotosUI/PHProjectType/undefined",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PHProjectTypeUndefined"
        }
      ],
      "role": "symbol",
      "title": "undefined",
      "type": "topic",
      "url": "/documentation/photosui/phprojecttype/undefined"
    },
    "doc://com.apple.photokit/documentation/PhotosUI/PHProjectTypeDescription": {
      "abstract": [
        {
          "text": "An extensible enumerator for ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.photokit/documentation/PhotosUI/PHProjectType",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " that’s presented to users in the project picker.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "PHProjectTypeDescription"
        }
      ],
      "identifier": "doc://com.apple.photokit/documentation/PhotosUI/PHProjectTypeDescription",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PHProjectTypeDescription"
        }
      ],
      "role": "symbol",
      "title": "PHProjectTypeDescription",
      "type": "topic",
      "url": "/documentation/photosui/phprojecttypedescription"
    },
    "doc://com.apple.photokit/documentation/PhotosUI/PHProjectTypeDescriptionDataSource": {
      "abstract": [
        {
          "text": "A protocol that you use to provide the project with type description data.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "PHProjectTypeDescriptionDataSource"
        }
      ],
      "identifier": "doc://com.apple.photokit/documentation/PhotosUI/PHProjectTypeDescriptionDataSource",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PHProjectTypeDescriptionDataSource"
        }
      ],
      "role": "symbol",
      "title": "PHProjectTypeDescriptionDataSource",
      "type": "topic",
      "url": "/documentation/photosui/phprojecttypedescriptiondatasource"
    },
    "doc://com.apple.photokit/documentation/PhotosUI/PHProjectTypeDescriptionInvalidator": {
      "abstract": [
        {
          "text": "A protocol that you use to tell the project when and how to invalidate type and footer text.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "PHProjectTypeDescriptionInvalidator"
        }
      ],
      "identifier": "doc://com.apple.photokit/documentation/PhotosUI/PHProjectTypeDescriptionInvalidator",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PHProjectTypeDescriptionInvalidator"
        }
      ],
      "role": "symbol",
      "title": "PHProjectTypeDescriptionInvalidator",
      "type": "topic",
      "url": "/documentation/photosui/phprojecttypedescriptioninvalidator"
    },
    "doc://com.externally.resolved.symbol/c:objc(cs)NSString": {
      "abstract": [
        {
          "text": "A static, plain-text Unicode string object which you use when you need reference semantics or other Foundation-specific behavior. ",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "class "
        },
        {
          "kind": "identifier",
          "text": "NSString"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSString",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSString",
      "type": "topic",
      "url": "/documentation/foundation/nsstring"
    },
    "doc://com.externally.resolved.symbol/s:SH": {
      "abstract": [
        {
          "text": "A type that can be hashed into a `Hasher` to produce an integer hash value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Hashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SQ",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SH",
      "kind": "symbol",
      "role": "symbol",
      "title": "Hashable",
      "type": "topic",
      "url": "/documentation/Swift/Hashable"
    },
    "doc://com.externally.resolved.symbol/s:SQ": {
      "abstract": [
        {
          "text": "A type that can be compared for value equality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SQ",
      "kind": "symbol",
      "role": "symbol",
      "title": "Equatable",
      "type": "topic",
      "url": "/documentation/Swift/Equatable"
    },
    "doc://com.externally.resolved.symbol/s:SY": {
      "abstract": [
        {
          "text": "A type that can be converted to and from an associated raw value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "RawRepresentable"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SY8RawValueQa",
          "text": "RawValue"
        },
        {
          "kind": "text",
          "text": ">"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SY",
      "kind": "symbol",
      "role": "symbol",
      "title": "RawRepresentable",
      "type": "topic",
      "url": "/documentation/Swift/RawRepresentable"
    },
    "doc://com.externally.resolved.symbol/s:s8SendableP": {
      "abstract": [
        {
          "text": "A thread-safe type whose values can be shared across arbitrary concurrent contexts without introducing a risk of data races.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Sendable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s8SendableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "Sendable",
      "type": "topic",
      "url": "/documentation/Swift/Sendable"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:SQ",
        "doc://com.externally.resolved.symbol/s:SH",
        "doc://com.externally.resolved.symbol/s:SY",
        "doc://com.externally.resolved.symbol/s:s8SendableP"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Determining-Project-Type",
      "generated": true,
      "identifiers": [
        "doc://com.apple.photokit/documentation/PhotosUI/PHProjectInfo/projectType",
        "doc://com.apple.photokit/documentation/PhotosUI/PHProjectInfo/creationSource-swift.property",
        "doc://com.apple.photokit/documentation/PhotosUI/PHProjectInfo/sections",
        "doc://com.apple.photokit/documentation/PhotosUI/PHProjectTypeDescription",
        "doc://com.apple.photokit/documentation/PhotosUI/PHProjectTypeDescriptionDataSource",
        "doc://com.apple.photokit/documentation/PhotosUI/PHProjectTypeDescriptionInvalidator",
        "doc://com.apple.photokit/documentation/PhotosUI/PHProjectInfo/CreationSource-swift.enum"
      ],
      "title": "Determining Project Type"
    }
  ],
  "topicSections": [
    {
      "anchor": "Initializing-a-Project-Type",
      "identifiers": [
        "doc://com.apple.photokit/documentation/PhotosUI/PHProjectType/init(_:)",
        "doc://com.apple.photokit/documentation/PhotosUI/PHProjectType/init(rawValue:)"
      ],
      "title": "Initializing a Project Type"
    },
    {
      "anchor": "Defining-a-Project-Type",
      "identifiers": [
        "doc://com.apple.photokit/documentation/PhotosUI/PHProjectType/undefined"
      ],
      "title": "Defining a Project Type"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "name": "macOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Type Alias"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "PHProjectType"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "typealias"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PHProjectType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "PHProjectType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.photokit/documentation/PhotosUI"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Defining-a-Project-Type",
              "identifiers": [
                "doc://com.apple.photokit/documentation/PhotosUI/PHProjectType/undefined"
              ],
              "title": "Defining a Project Type"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Determining-Project-Type",
              "generated": true,
              "identifiers": [
                "doc://com.apple.photokit/documentation/PhotosUI/PHProjectInfo/projectType",
                "doc://com.apple.photokit/documentation/PhotosUI/PHProjectInfo/creationSource-swift.property",
                "doc://com.apple.photokit/documentation/PhotosUI/PHProjectInfo/sections",
                "doc://com.apple.photokit/documentation/PhotosUI/PHProjectTypeDescription",
                "doc://com.apple.photokit/documentation/PhotosUI/PHProjectTypeDescriptionDataSource",
                "doc://com.apple.photokit/documentation/PhotosUI/PHProjectTypeDescriptionInvalidator",
                "doc://com.apple.photokit/documentation/PhotosUI/PHProjectInfo/CreationSource-swift.enum"
              ],
              "title": "Determining Project Type"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "macOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "typedef"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSString",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(cs)NSString",
                    "text": "NSString"
                  },
                  {
                    "kind": "text",
                    "text": " * "
                  },
                  {
                    "kind": "identifier",
                    "text": "PHProjectType"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1PhotosUI~1PHProjectTypeDescription/title",
          "value": "PHProjectTypeDescription"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1PhotosUI~1PHProjectTypeDescription/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PHProjectTypeDescription"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1PhotosUI~1PHProjectTypeDescription/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "PHProjectTypeDescription"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1PhotosUI~1PHProjectTypeDescriptionDataSource/title",
          "value": "PHProjectTypeDescriptionDataSource"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1PhotosUI~1PHProjectTypeDescriptionDataSource/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PHProjectTypeDescriptionDataSource"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1PhotosUI~1PHProjectTypeDescriptionDataSource/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "PHProjectTypeDescriptionDataSource"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1PhotosUI~1PHProjectInfo~1CreationSource-swift.enum/title",
          "value": "PHProjectCreationSource"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1PhotosUI~1PHProjectInfo~1CreationSource-swift.enum/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PHProjectCreationSource"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1PhotosUI~1PHProjectInfo~1CreationSource-swift.enum/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "PHProjectCreationSource"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1PhotosUI~1PHProjectInfo~1projectType/title",
          "value": "projectType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1PhotosUI~1PHProjectInfo~1projectType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "projectType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1PhotosUI~1PHProjectInfo~1creationSource-swift.property/title",
          "value": "creationSource"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1PhotosUI~1PHProjectInfo~1creationSource-swift.property/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "creationSource"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:objc(cs)NSString/abstract",
          "value": [
            {
              "text": "A static, plain-text Unicode string object.",
              "type": "text"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1PhotosUI~1PHProjectType~1undefined/title",
          "value": "PHProjectTypeUndefined"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1PhotosUI~1PHProjectType~1undefined/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PHProjectTypeUndefined"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1PhotosUI~1PHProjectTypeDescriptionInvalidator/title",
          "value": "PHProjectTypeDescriptionInvalidator"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1PhotosUI~1PHProjectTypeDescriptionInvalidator/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PHProjectTypeDescriptionInvalidator"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1PhotosUI~1PHProjectTypeDescriptionInvalidator/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "PHProjectTypeDescriptionInvalidator"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1PhotosUI~1PHProjectInfo~1sections/title",
          "value": "sections"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1PhotosUI~1PHProjectInfo~1sections/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "sections"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1PhotosUI~1PHProjectType/title",
          "value": "PHProjectType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1PhotosUI~1PHProjectType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PHProjectType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1PhotosUI~1PHProjectType/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "PHProjectType"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/photosui/phprojecttype"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/photosui/phprojecttype"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
