{
  "abstract": [
    {
      "text": "An object that provides Photos project extensions with access to the underlying project, as well as to the user’s photo library for editing.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.photokit/documentation/PhotosUI"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.photokit/documentation/PhotosUI/PHProjectExtensionContext"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(cs)PHProjectExtensionContext",
    "fragments": [
      {
        "kind": "keyword",
        "text": "class"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "PHProjectExtensionContext"
      }
    ],
    "modules": [
      {
        "name": "PhotosUI"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "PHProjectExtensionContext"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.13",
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Class",
    "symbolKind": "class",
    "title": "PHProjectExtensionContext"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "macOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "class"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "PHProjectExtensionContext"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "When a Photos project extension is initialized, it is handed an extension context object. This object provides the extension with access to the underlying project, as well as the photo library from which assets are fetched and edited.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.photokit/documentation/PhotoKit/creating-a-slideshow-project-extension-for-photos": {
      "abstract": [
        {
          "text": "Augment the macOS Photos app with extensions that support project creation.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.photokit/documentation/PhotoKit/creating-a-slideshow-project-extension-for-photos",
      "kind": "article",
      "role": "sampleCode",
      "title": "Creating a Slideshow Project Extension for Photos",
      "type": "topic",
      "url": "/documentation/photokit/creating-a-slideshow-project-extension-for-photos"
    },
    "doc://com.apple.photokit/documentation/Photos/PHProject": {
      "abstract": [
        {
          "text": "A representation of a Photos app project extension.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "PHProject"
        }
      ],
      "identifier": "doc://com.apple.photokit/documentation/Photos/PHProject",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PHProject"
        }
      ],
      "role": "symbol",
      "title": "PHProject",
      "type": "topic",
      "url": "/documentation/photos/phproject"
    },
    "doc://com.apple.photokit/documentation/Photos/PHProjectChangeRequest": {
      "abstract": [
        {
          "text": "A request to change asset data in a Photos project extension.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "PHProjectChangeRequest"
        }
      ],
      "identifier": "doc://com.apple.photokit/documentation/Photos/PHProjectChangeRequest",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PHProjectChangeRequest"
        }
      ],
      "role": "symbol",
      "title": "PHProjectChangeRequest",
      "type": "topic",
      "url": "/documentation/photos/phprojectchangerequest"
    },
    "doc://com.apple.photokit/documentation/PhotosUI": {
      "abstract": [
        {
          "text": "Present a person’s photo library using a picker interface, display Live Photos, or extend the Photos app with custom functionality.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.photokit/documentation/PhotosUI",
      "kind": "symbol",
      "role": "collection",
      "title": "PhotosUI",
      "type": "topic",
      "url": "/documentation/photosui"
    },
    "doc://com.apple.photokit/documentation/PhotosUI/PHProjectCategory": {
      "abstract": [
        {
          "text": "A representation of Photos project extension categories.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "PHProjectCategory"
        }
      ],
      "identifier": "doc://com.apple.photokit/documentation/PhotosUI/PHProjectCategory",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PHProjectCategory"
        }
      ],
      "role": "symbol",
      "title": "PHProjectCategory",
      "type": "topic",
      "url": "/documentation/photosui/phprojectcategory"
    },
    "doc://com.apple.photokit/documentation/PhotosUI/PHProjectElement": {
      "abstract": [
        {
          "text": "The superclass for all element objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "PHProjectElement"
        }
      ],
      "identifier": "doc://com.apple.photokit/documentation/PhotosUI/PHProjectElement",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PHProjectElement"
        }
      ],
      "role": "symbol",
      "title": "PHProjectElement",
      "type": "topic",
      "url": "/documentation/photosui/phprojectelement"
    },
    "doc://com.apple.photokit/documentation/PhotosUI/PHProjectExtensionContext": {
      "abstract": [
        {
          "text": "An object that provides Photos project extensions with access to the underlying project, as well as to the user’s photo library for editing.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "PHProjectExtensionContext"
        }
      ],
      "identifier": "doc://com.apple.photokit/documentation/PhotosUI/PHProjectExtensionContext",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PHProjectExtensionContext"
        }
      ],
      "role": "symbol",
      "title": "PHProjectExtensionContext",
      "type": "topic",
      "url": "/documentation/photosui/phprojectextensioncontext"
    },
    "doc://com.apple.photokit/documentation/PhotosUI/PHProjectExtensionContext/photoLibrary": {
      "abstract": [
        {
          "text": "A read-only version of the photo library being modified.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "photoLibrary"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)PHPhotoLibrary",
          "text": "PHPhotoLibrary"
        }
      ],
      "identifier": "doc://com.apple.photokit/documentation/PhotosUI/PHProjectExtensionContext/photoLibrary",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "photoLibrary"
        }
      ],
      "role": "symbol",
      "title": "photoLibrary",
      "type": "topic",
      "url": "/documentation/photosui/phprojectextensioncontext/photolibrary"
    },
    "doc://com.apple.photokit/documentation/PhotosUI/PHProjectExtensionContext/project": {
      "abstract": [
        {
          "text": "A read-only version of the project being edited.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "project"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)PHProject",
          "text": "PHProject"
        }
      ],
      "identifier": "doc://com.apple.photokit/documentation/PhotosUI/PHProjectExtensionContext/project",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "project"
        }
      ],
      "role": "symbol",
      "title": "project",
      "type": "topic",
      "url": "/documentation/photosui/phprojectextensioncontext/project"
    },
    "doc://com.apple.photokit/documentation/PhotosUI/PHProjectExtensionContext/showEditor(for:)": {
      "abstract": [
        {
          "text": "Invokes the built-in photo editor for the given asset.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "showEditor"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "for"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)PHAsset",
          "text": "PHAsset"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.photokit/documentation/PhotosUI/PHProjectExtensionContext/showEditor(for:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "showEditorForAsset:"
        }
      ],
      "role": "symbol",
      "title": "showEditor(for:)",
      "type": "topic",
      "url": "/documentation/photosui/phprojectextensioncontext/showeditor(for:)"
    },
    "doc://com.apple.photokit/documentation/PhotosUI/PHProjectExtensionContext/updatedProjectInfo(from:completion:)": {
      "abstract": [
        {
          "text": "Creates an updated ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.photokit/documentation/PhotosUI/PHProjectInfo",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " instance from existing project information and current assets.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "updatedProjectInfo"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "from"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)PHProjectInfo",
          "text": "PHProjectInfo"
        },
        {
          "kind": "text",
          "text": "?, "
        },
        {
          "kind": "externalParam",
          "text": "completion"
        },
        {
          "kind": "text",
          "text": ": ("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)PHProjectInfo",
          "text": "PHProjectInfo"
        },
        {
          "kind": "text",
          "text": "?) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s4Voida",
          "text": "Void"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSProgress",
          "text": "Progress"
        }
      ],
      "identifier": "doc://com.apple.photokit/documentation/PhotosUI/PHProjectExtensionContext/updatedProjectInfo(from:completion:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "updatedProjectInfoFromProjectInfo:completion:"
        }
      ],
      "role": "symbol",
      "title": "updatedProjectInfo(from:completion:)",
      "type": "topic",
      "url": "/documentation/photosui/phprojectextensioncontext/updatedprojectinfo(from:completion:)"
    },
    "doc://com.apple.photokit/documentation/PhotosUI/PHProjectExtensionController": {
      "abstract": [
        {
          "text": "A protocol defining the life cycle and supported types of project extensions.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "PHProjectExtensionController"
        }
      ],
      "identifier": "doc://com.apple.photokit/documentation/PhotosUI/PHProjectExtensionController",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PHProjectExtensionController"
        }
      ],
      "role": "symbol",
      "title": "PHProjectExtensionController",
      "type": "topic",
      "url": "/documentation/photosui/phprojectextensioncontroller"
    },
    "doc://com.apple.photokit/documentation/PhotosUI/PHProjectInfo": {
      "abstract": [
        {
          "text": "Information about the project extension.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "PHProjectInfo"
        }
      ],
      "identifier": "doc://com.apple.photokit/documentation/PhotosUI/PHProjectInfo",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PHProjectInfo"
        }
      ],
      "role": "symbol",
      "title": "PHProjectInfo",
      "type": "topic",
      "url": "/documentation/photosui/phprojectinfo"
    },
    "doc://com.apple.photokit/documentation/PhotosUI/PHProjectRegionOfInterest": {
      "abstract": [
        {
          "text": "A representation of a region of interest in a photo asset.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "PHProjectRegionOfInterest"
        }
      ],
      "identifier": "doc://com.apple.photokit/documentation/PhotosUI/PHProjectRegionOfInterest",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PHProjectRegionOfInterest"
        }
      ],
      "role": "symbol",
      "title": "PHProjectRegionOfInterest",
      "type": "topic",
      "url": "/documentation/photosui/phprojectregionofinterest"
    },
    "doc://com.apple.photokit/documentation/PhotosUI/PHProjectSection": {
      "abstract": [
        {
          "text": "A collection of content representing curated asset and text elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "PHProjectSection"
        }
      ],
      "identifier": "doc://com.apple.photokit/documentation/PhotosUI/PHProjectSection",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PHProjectSection"
        }
      ],
      "role": "symbol",
      "title": "PHProjectSection",
      "type": "topic",
      "url": "/documentation/photosui/phprojectsection"
    },
    "doc://com.externally.resolved.symbol/c:objc(cs)NSExtensionContext": {
      "abstract": [
        {
          "text": "The host app context from which an app extension is invoked.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "class "
        },
        {
          "kind": "identifier",
          "text": "NSExtensionContext"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSExtensionContext",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSExtensionContext",
      "type": "topic",
      "url": "/documentation/foundation/nsextensioncontext"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)NSObject": {
      "abstract": [
        {
          "text": "The group of methods that are fundamental to all Objective-C objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "protocol "
        },
        {
          "kind": "identifier",
          "text": "NSObjectProtocol"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSObject",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSObjectProtocol",
      "type": "topic",
      "url": "/documentation/objectivec/nsobjectprotocol"
    },
    "doc://com.externally.resolved.symbol/s:SH": {
      "abstract": [
        {
          "text": "A type that can be hashed into a `Hasher` to produce an integer hash value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Hashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SQ",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SH",
      "kind": "symbol",
      "role": "symbol",
      "title": "Hashable",
      "type": "topic",
      "url": "/documentation/Swift/Hashable"
    },
    "doc://com.externally.resolved.symbol/s:SQ": {
      "abstract": [
        {
          "text": "A type that can be compared for value equality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SQ",
      "kind": "symbol",
      "role": "symbol",
      "title": "Equatable",
      "type": "topic",
      "url": "/documentation/Swift/Equatable"
    },
    "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP": {
      "abstract": [
        {
          "text": "A type with a customized textual representation.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CustomStringConvertible"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CustomStringConvertible",
      "type": "topic",
      "url": "/documentation/Swift/CustomStringConvertible"
    },
    "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP": {
      "abstract": [
        {
          "text": "A type with a customized textual representation suitable for debugging purposes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CustomDebugStringConvertible"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CustomDebugStringConvertible",
      "type": "topic",
      "url": "/documentation/Swift/CustomDebugStringConvertible"
    },
    "doc://com.externally.resolved.symbol/s:s7CVarArgP": {
      "abstract": [
        {
          "text": "A type whose instances can be encoded, and appropriately passed, as elements of a C `va_list`.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CVarArg"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s7CVarArgP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CVarArg",
      "type": "topic",
      "url": "/documentation/Swift/CVarArg"
    },
    "doc://com.externally.resolved.symbol/s:s8SendableP": {
      "abstract": [
        {
          "text": "A thread-safe type whose values can be shared across arbitrary concurrent contexts without introducing a risk of data races.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Sendable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s8SendableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "Sendable",
      "type": "topic",
      "url": "/documentation/Swift/Sendable"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/c:objc(cs)NSExtensionContext"
      ],
      "kind": "relationships",
      "title": "Inherits From",
      "type": "inheritsFrom"
    },
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:s7CVarArgP",
        "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP",
        "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP",
        "doc://com.externally.resolved.symbol/s:SQ",
        "doc://com.externally.resolved.symbol/s:SH",
        "doc://com.externally.resolved.symbol/c:objc(pl)NSObject",
        "doc://com.externally.resolved.symbol/s:s8SendableP"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "macOS-Photos-Project-Extensions",
      "generated": true,
      "identifiers": [
        "doc://com.apple.photokit/documentation/PhotoKit/creating-a-slideshow-project-extension-for-photos",
        "doc://com.apple.photokit/documentation/Photos/PHProject",
        "doc://com.apple.photokit/documentation/PhotosUI/PHProjectInfo",
        "doc://com.apple.photokit/documentation/PhotosUI/PHProjectElement",
        "doc://com.apple.photokit/documentation/PhotosUI/PHProjectSection",
        "doc://com.apple.photokit/documentation/PhotosUI/PHProjectRegionOfInterest",
        "doc://com.apple.photokit/documentation/Photos/PHProjectChangeRequest",
        "doc://com.apple.photokit/documentation/PhotosUI/PHProjectExtensionController",
        "doc://com.apple.photokit/documentation/PhotosUI/PHProjectCategory"
      ],
      "title": "macOS Photos Project Extensions"
    }
  ],
  "topicSections": [
    {
      "anchor": "Accessing-the-Project-and-the-Photo-Library",
      "identifiers": [
        "doc://com.apple.photokit/documentation/PhotosUI/PHProjectExtensionContext/project",
        "doc://com.apple.photokit/documentation/PhotosUI/PHProjectExtensionContext/photoLibrary"
      ],
      "title": "Accessing the Project and the Photo Library"
    },
    {
      "anchor": "Updating-Assets",
      "identifiers": [
        "doc://com.apple.photokit/documentation/PhotosUI/PHProjectExtensionContext/showEditor(for:)",
        "doc://com.apple.photokit/documentation/PhotosUI/PHProjectExtensionContext/updatedProjectInfo(from:completion:)"
      ],
      "title": "Updating Assets"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.13",
              "name": "macOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Class"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "PHProjectExtensionContext"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "class"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PHProjectExtensionContext"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "PHProjectExtensionContext"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.photokit/documentation/PhotosUI"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Accessing-the-Project-and-the-Photo-Library",
              "identifiers": [
                "doc://com.apple.photokit/documentation/PhotosUI/PHProjectExtensionContext/project",
                "doc://com.apple.photokit/documentation/PhotosUI/PHProjectExtensionContext/photoLibrary"
              ],
              "title": "Accessing the Project and the Photo Library"
            },
            {
              "anchor": "Updating-Assets",
              "identifiers": [
                "doc://com.apple.photokit/documentation/PhotosUI/PHProjectExtensionContext/showEditor(for:)",
                "doc://com.apple.photokit/documentation/PhotosUI/PHProjectExtensionContext/updatedProjectInfo(from:completion:)"
              ],
              "title": "Updating Assets"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": [
            {
              "identifiers": [
                "doc://com.externally.resolved.symbol/c:objc(cs)NSExtensionContext"
              ],
              "kind": "relationships",
              "title": "Inherits From",
              "type": "inheritsFrom"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "macOS-Photos-Project-Extensions",
              "generated": true,
              "identifiers": [
                "doc://com.apple.photokit/documentation/Photos/PHProject",
                "doc://com.apple.photokit/documentation/PhotosUI/PHProjectInfo",
                "doc://com.apple.photokit/documentation/PhotosUI/PHProjectElement",
                "doc://com.apple.photokit/documentation/PhotosUI/PHProjectSection",
                "doc://com.apple.photokit/documentation/PhotosUI/PHProjectRegionOfInterest",
                "doc://com.apple.photokit/documentation/Photos/PHProjectChangeRequest",
                "doc://com.apple.photokit/documentation/PhotosUI/PHProjectExtensionController",
                "doc://com.apple.photokit/documentation/PhotosUI/PHProjectCategory"
              ],
              "title": "macOS Photos Project Extensions"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "macOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "@interface"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "PHProjectExtensionContext"
                  },
                  {
                    "kind": "text",
                    "text": " : "
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSExtensionContext",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(cs)NSExtensionContext",
                    "text": "NSExtensionContext"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1PhotosUI~1PHProjectRegionOfInterest/title",
          "value": "PHProjectRegionOfInterest"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1PhotosUI~1PHProjectRegionOfInterest/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PHProjectRegionOfInterest"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1PhotosUI~1PHProjectRegionOfInterest/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "PHProjectRegionOfInterest"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1PhotosUI~1PHProjectInfo/title",
          "value": "PHProjectInfo"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1PhotosUI~1PHProjectInfo/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PHProjectInfo"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1PhotosUI~1PHProjectInfo/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "PHProjectInfo"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1PhotosUI~1PHProjectExtensionController/title",
          "value": "PHProjectExtensionController"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1PhotosUI~1PHProjectExtensionController/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PHProjectExtensionController"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1PhotosUI~1PHProjectExtensionController/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "PHProjectExtensionController"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHProjectChangeRequest/title",
          "value": "PHProjectChangeRequest"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHProjectChangeRequest/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PHProjectChangeRequest"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHProjectChangeRequest/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "PHProjectChangeRequest"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1PhotosUI~1PHProjectCategory/title",
          "value": "PHProjectCategory"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1PhotosUI~1PHProjectCategory/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PHProjectCategory"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1PhotosUI~1PHProjectCategory/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "PHProjectCategory"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1PhotosUI~1PHProjectExtensionContext~1updatedProjectInfo(from:completion:)/title",
          "value": "updatedProjectInfoFromProjectInfo:completion:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1PhotosUI~1PHProjectExtensionContext~1updatedProjectInfo(from:completion:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "updatedProjectInfoFromProjectInfo:completion:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:objc(pl)NSObject/title",
          "value": "NSObject"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1PhotosUI~1PHProjectExtensionContext~1showEditor(for:)/title",
          "value": "showEditorForAsset:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1PhotosUI~1PHProjectExtensionContext~1showEditor(for:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "showEditorForAsset:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1PhotosUI~1PHProjectExtensionContext~1project/title",
          "value": "project"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1PhotosUI~1PHProjectExtensionContext~1project/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "project"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHProject/title",
          "value": "PHProject"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHProject/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PHProject"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHProject/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "PHProject"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1PhotosUI~1PHProjectSection/title",
          "value": "PHProjectSection"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1PhotosUI~1PHProjectSection/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PHProjectSection"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1PhotosUI~1PHProjectSection/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "PHProjectSection"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1PhotosUI~1PHProjectElement/title",
          "value": "PHProjectElement"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1PhotosUI~1PHProjectElement/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PHProjectElement"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1PhotosUI~1PHProjectElement/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "PHProjectElement"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1PhotosUI~1PHProjectExtensionContext~1photoLibrary/title",
          "value": "photoLibrary"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1PhotosUI~1PHProjectExtensionContext~1photoLibrary/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "photoLibrary"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1PhotosUI~1PHProjectExtensionContext/title",
          "value": "PHProjectExtensionContext"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1PhotosUI~1PHProjectExtensionContext/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PHProjectExtensionContext"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1PhotosUI~1PHProjectExtensionContext/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "PHProjectExtensionContext"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/photosui/phprojectextensioncontext"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/photosui/phprojectextensioncontext"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
