{
  "abstract": [
    {
      "text": "An element that represents a media asset within project section content.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.photokit/documentation/PhotosUI"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.photokit/documentation/PhotosUI/PHProjectAssetElement"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(cs)PHProjectAssetElement",
    "fragments": [
      {
        "kind": "keyword",
        "text": "class"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "PHProjectAssetElement"
      }
    ],
    "modules": [
      {
        "name": "PhotosUI"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "PHProjectAssetElement"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.13",
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Class",
    "symbolKind": "class",
    "title": "PHProjectAssetElement"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "macOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "class"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "PHProjectAssetElement"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Access the underlying ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.photokit/documentation/Photos/PHAsset",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " by converting the provided ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.photokit/documentation/PhotosUI/PHProjectSectionContent/cloudAssetIdentifiers",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " to a ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.photokit/documentation/Photos/PHAssetResource/assetLocalIdentifier",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ", then calling ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.photokit/documentation/Photos/PHAsset/fetchAssets(withLocalIdentifiers:options:)",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ".",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.photokit/documentation/Photos/PHAsset": {
      "abstract": [
        {
          "text": "A representation of an image, video, or Live Photo in the Photos library.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "PHAsset"
        }
      ],
      "identifier": "doc://com.apple.photokit/documentation/Photos/PHAsset",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PHAsset"
        }
      ],
      "role": "symbol",
      "title": "PHAsset",
      "type": "topic",
      "url": "/documentation/photos/phasset"
    },
    "doc://com.apple.photokit/documentation/Photos/PHAsset/fetchAssets(withLocalIdentifiers:options:)": {
      "abstract": [
        {
          "text": "Retrieves assets with the specified local-device-specific unique identifiers.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "fetchAssets"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "withLocalIdentifiers"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": "], "
        },
        {
          "kind": "externalParam",
          "text": "options"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)PHFetchOptions",
          "text": "PHFetchOptions"
        },
        {
          "kind": "text",
          "text": "?) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)PHFetchResult",
          "text": "PHFetchResult"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)PHAsset",
          "text": "PHAsset"
        },
        {
          "kind": "text",
          "text": ">"
        }
      ],
      "identifier": "doc://com.apple.photokit/documentation/Photos/PHAsset/fetchAssets(withLocalIdentifiers:options:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "fetchAssetsWithLocalIdentifiers:options:"
        }
      ],
      "role": "symbol",
      "title": "fetchAssets(withLocalIdentifiers:options:)",
      "type": "topic",
      "url": "/documentation/photos/phasset/fetchassets(withlocalidentifiers:options:)"
    },
    "doc://com.apple.photokit/documentation/Photos/PHAssetResource/assetLocalIdentifier": {
      "abstract": [
        {
          "text": "The unique identifier the system associates for a local asset object.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "assetLocalIdentifier"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.photokit/documentation/Photos/PHAssetResource/assetLocalIdentifier",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "assetLocalIdentifier"
        }
      ],
      "role": "symbol",
      "title": "assetLocalIdentifier",
      "type": "topic",
      "url": "/documentation/photos/phassetresource/assetlocalidentifier"
    },
    "doc://com.apple.photokit/documentation/PhotosUI": {
      "abstract": [
        {
          "text": "Present a person’s photo library using a picker interface, display Live Photos, or extend the Photos app with custom functionality.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.photokit/documentation/PhotosUI",
      "kind": "symbol",
      "role": "collection",
      "title": "PhotosUI",
      "type": "topic",
      "url": "/documentation/photosui"
    },
    "doc://com.apple.photokit/documentation/PhotosUI/PHProjectAssetElement": {
      "abstract": [
        {
          "text": "An element that represents a media asset within project section content.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "PHProjectAssetElement"
        }
      ],
      "identifier": "doc://com.apple.photokit/documentation/PhotosUI/PHProjectAssetElement",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PHProjectAssetElement"
        }
      ],
      "role": "symbol",
      "title": "PHProjectAssetElement",
      "type": "topic",
      "url": "/documentation/photosui/phprojectassetelement"
    },
    "doc://com.apple.photokit/documentation/PhotosUI/PHProjectAssetElement/annotation": {
      "abstract": [
        {
          "text": "A string annotation attached to the asset.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "annotation"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.photokit/documentation/PhotosUI/PHProjectAssetElement/annotation",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "annotation"
        }
      ],
      "role": "symbol",
      "title": "annotation",
      "type": "topic",
      "url": "/documentation/photosui/phprojectassetelement/annotation"
    },
    "doc://com.apple.photokit/documentation/PhotosUI/PHProjectAssetElement/cloudAssetIdentifier": {
      "abstract": [
        {
          "text": "The asset’s identifier in the cloud.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "cloudAssetIdentifier"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)PHCloudIdentifier",
          "text": "PHCloudIdentifier"
        }
      ],
      "identifier": "doc://com.apple.photokit/documentation/PhotosUI/PHProjectAssetElement/cloudAssetIdentifier",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "cloudAssetIdentifier"
        }
      ],
      "role": "symbol",
      "title": "cloudAssetIdentifier",
      "type": "topic",
      "url": "/documentation/photosui/phprojectassetelement/cloudassetidentifier"
    },
    "doc://com.apple.photokit/documentation/PhotosUI/PHProjectAssetElement/cropRect": {
      "abstract": [
        {
          "text": "A rectangle defining the cropped portion of the asset.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "cropRect"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@CGRect",
          "text": "CGRect"
        }
      ],
      "identifier": "doc://com.apple.photokit/documentation/PhotosUI/PHProjectAssetElement/cropRect",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "cropRect"
        }
      ],
      "role": "symbol",
      "title": "cropRect",
      "type": "topic",
      "url": "/documentation/photosui/phprojectassetelement/croprect"
    },
    "doc://com.apple.photokit/documentation/PhotosUI/PHProjectAssetElement/horizontallyFlipped": {
      "abstract": [
        {
          "text": "A Boolean indicating whether the asset is vertically flipped.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "horizontallyFlipped"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.photokit/documentation/PhotosUI/PHProjectAssetElement/horizontallyFlipped",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "horizontallyFlipped"
        }
      ],
      "role": "symbol",
      "title": "horizontallyFlipped",
      "type": "topic",
      "url": "/documentation/photosui/phprojectassetelement/horizontallyflipped"
    },
    "doc://com.apple.photokit/documentation/PhotosUI/PHProjectAssetElement/regionsOfInterest": {
      "abstract": [
        {
          "text": "An array of regions of interest in the photo asset.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "regionsOfInterest"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)PHProjectRegionOfInterest",
          "text": "PHProjectRegionOfInterest"
        },
        {
          "kind": "text",
          "text": "]"
        }
      ],
      "identifier": "doc://com.apple.photokit/documentation/PhotosUI/PHProjectAssetElement/regionsOfInterest",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "regionsOfInterest"
        }
      ],
      "role": "symbol",
      "title": "regionsOfInterest",
      "type": "topic",
      "url": "/documentation/photosui/phprojectassetelement/regionsofinterest"
    },
    "doc://com.apple.photokit/documentation/PhotosUI/PHProjectAssetElement/verticallyFlipped": {
      "abstract": [
        {
          "text": "A Boolean indicating whether the asset is vertically flipped.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "verticallyFlipped"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.photokit/documentation/PhotosUI/PHProjectAssetElement/verticallyFlipped",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "verticallyFlipped"
        }
      ],
      "role": "symbol",
      "title": "verticallyFlipped",
      "type": "topic",
      "url": "/documentation/photosui/phprojectassetelement/verticallyflipped"
    },
    "doc://com.apple.photokit/documentation/PhotosUI/PHProjectElement": {
      "abstract": [
        {
          "text": "The superclass for all element objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "PHProjectElement"
        }
      ],
      "identifier": "doc://com.apple.photokit/documentation/PhotosUI/PHProjectElement",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PHProjectElement"
        }
      ],
      "role": "symbol",
      "title": "PHProjectElement",
      "type": "topic",
      "url": "/documentation/photosui/phprojectelement"
    },
    "doc://com.apple.photokit/documentation/PhotosUI/PHProjectJournalEntryElement": {
      "abstract": [
        {
          "text": "An element that represents a journal entry within project section content.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "PHProjectJournalEntryElement"
        }
      ],
      "identifier": "doc://com.apple.photokit/documentation/PhotosUI/PHProjectJournalEntryElement",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PHProjectJournalEntryElement"
        }
      ],
      "role": "symbol",
      "title": "PHProjectJournalEntryElement",
      "type": "topic",
      "url": "/documentation/photosui/phprojectjournalentryelement"
    },
    "doc://com.apple.photokit/documentation/PhotosUI/PHProjectMapElement": {
      "abstract": [
        {
          "text": "An element that represents a map within project section content.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "PHProjectMapElement"
        }
      ],
      "identifier": "doc://com.apple.photokit/documentation/PhotosUI/PHProjectMapElement",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PHProjectMapElement"
        }
      ],
      "role": "symbol",
      "title": "PHProjectMapElement",
      "type": "topic",
      "url": "/documentation/photosui/phprojectmapelement"
    },
    "doc://com.apple.photokit/documentation/PhotosUI/PHProjectSectionContent/cloudAssetIdentifiers": {
      "abstract": [
        {
          "text": "An array containing all cloud asset identifiers referenced in the content.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "cloudAssetIdentifiers"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)PHCloudIdentifier",
          "text": "PHCloudIdentifier"
        },
        {
          "kind": "text",
          "text": "]"
        }
      ],
      "identifier": "doc://com.apple.photokit/documentation/PhotosUI/PHProjectSectionContent/cloudAssetIdentifiers",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "cloudAssetIdentifiers"
        }
      ],
      "role": "symbol",
      "title": "cloudAssetIdentifiers",
      "type": "topic",
      "url": "/documentation/photosui/phprojectsectioncontent/cloudassetidentifiers"
    },
    "doc://com.apple.photokit/documentation/PhotosUI/PHProjectTextElement": {
      "abstract": [
        {
          "text": "An element that represents text within project section content.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "PHProjectTextElement"
        }
      ],
      "identifier": "doc://com.apple.photokit/documentation/PhotosUI/PHProjectTextElement",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PHProjectTextElement"
        }
      ],
      "role": "symbol",
      "title": "PHProjectTextElement",
      "type": "topic",
      "url": "/documentation/photosui/phprojecttextelement"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)NSCoding": {
      "abstract": [
        {
          "text": "A protocol that enables an object to be encoded and decoded for archiving and distribution.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "protocol "
        },
        {
          "kind": "identifier",
          "text": "NSCoding"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSCoding",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSCoding",
      "type": "topic",
      "url": "/documentation/foundation/nscoding"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)NSObject": {
      "abstract": [
        {
          "text": "The group of methods that are fundamental to all Objective-C objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "protocol "
        },
        {
          "kind": "identifier",
          "text": "NSObjectProtocol"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSObject",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSObjectProtocol",
      "type": "topic",
      "url": "/documentation/objectivec/nsobjectprotocol"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)NSSecureCoding": {
      "abstract": [
        {
          "text": "A protocol that enables encoding and decoding in a manner that is robust against object substitution attacks.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "protocol "
        },
        {
          "kind": "identifier",
          "text": "NSSecureCoding"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSSecureCoding",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSSecureCoding",
      "type": "topic",
      "url": "/documentation/foundation/nssecurecoding"
    },
    "doc://com.externally.resolved.symbol/s:SH": {
      "abstract": [
        {
          "text": "A type that can be hashed into a `Hasher` to produce an integer hash value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Hashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SQ",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SH",
      "kind": "symbol",
      "role": "symbol",
      "title": "Hashable",
      "type": "topic",
      "url": "/documentation/Swift/Hashable"
    },
    "doc://com.externally.resolved.symbol/s:SQ": {
      "abstract": [
        {
          "text": "A type that can be compared for value equality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SQ",
      "kind": "symbol",
      "role": "symbol",
      "title": "Equatable",
      "type": "topic",
      "url": "/documentation/Swift/Equatable"
    },
    "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP": {
      "abstract": [
        {
          "text": "A type with a customized textual representation.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CustomStringConvertible"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CustomStringConvertible",
      "type": "topic",
      "url": "/documentation/Swift/CustomStringConvertible"
    },
    "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP": {
      "abstract": [
        {
          "text": "A type with a customized textual representation suitable for debugging purposes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CustomDebugStringConvertible"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CustomDebugStringConvertible",
      "type": "topic",
      "url": "/documentation/Swift/CustomDebugStringConvertible"
    },
    "doc://com.externally.resolved.symbol/s:s7CVarArgP": {
      "abstract": [
        {
          "text": "A type whose instances can be encoded, and appropriately passed, as elements of a C `va_list`.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CVarArg"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s7CVarArgP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CVarArg",
      "type": "topic",
      "url": "/documentation/Swift/CVarArg"
    },
    "doc://com.externally.resolved.symbol/s:s8SendableP": {
      "abstract": [
        {
          "text": "A thread-safe type whose values can be shared across arbitrary concurrent contexts without introducing a risk of data races.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Sendable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s8SendableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "Sendable",
      "type": "topic",
      "url": "/documentation/Swift/Sendable"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.apple.photokit/documentation/PhotosUI/PHProjectElement"
      ],
      "kind": "relationships",
      "title": "Inherits From",
      "type": "inheritsFrom"
    },
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:s7CVarArgP",
        "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP",
        "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP",
        "doc://com.externally.resolved.symbol/s:SQ",
        "doc://com.externally.resolved.symbol/s:SH",
        "doc://com.externally.resolved.symbol/c:objc(pl)NSCoding",
        "doc://com.externally.resolved.symbol/c:objc(pl)NSObject",
        "doc://com.externally.resolved.symbol/c:objc(pl)NSSecureCoding",
        "doc://com.externally.resolved.symbol/s:s8SendableP"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Subclassing-Project-Elements",
      "generated": true,
      "identifiers": [
        "doc://com.apple.photokit/documentation/PhotosUI/PHProjectTextElement",
        "doc://com.apple.photokit/documentation/PhotosUI/PHProjectJournalEntryElement",
        "doc://com.apple.photokit/documentation/PhotosUI/PHProjectMapElement"
      ],
      "title": "Subclassing Project Elements"
    }
  ],
  "topicSections": [
    {
      "anchor": "Characterizing-an-Asset-Element",
      "identifiers": [
        "doc://com.apple.photokit/documentation/PhotosUI/PHProjectAssetElement/annotation",
        "doc://com.apple.photokit/documentation/PhotosUI/PHProjectAssetElement/cloudAssetIdentifier",
        "doc://com.apple.photokit/documentation/PhotosUI/PHProjectAssetElement/cropRect",
        "doc://com.apple.photokit/documentation/PhotosUI/PHProjectAssetElement/regionsOfInterest",
        "doc://com.apple.photokit/documentation/PhotosUI/PHProjectAssetElement/horizontallyFlipped",
        "doc://com.apple.photokit/documentation/PhotosUI/PHProjectAssetElement/verticallyFlipped"
      ],
      "title": "Characterizing an Asset Element"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.13",
              "name": "macOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Class"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "PHProjectAssetElement"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "class"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PHProjectAssetElement"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "PHProjectAssetElement"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.photokit/documentation/PhotosUI"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Characterizing-an-Asset-Element",
              "identifiers": [
                "doc://com.apple.photokit/documentation/PhotosUI/PHProjectAssetElement/annotation",
                "doc://com.apple.photokit/documentation/PhotosUI/PHProjectAssetElement/cloudAssetIdentifier",
                "doc://com.apple.photokit/documentation/PhotosUI/PHProjectAssetElement/cropRect",
                "doc://com.apple.photokit/documentation/PhotosUI/PHProjectAssetElement/regionsOfInterest",
                "doc://com.apple.photokit/documentation/PhotosUI/PHProjectAssetElement/horizontallyFlipped",
                "doc://com.apple.photokit/documentation/PhotosUI/PHProjectAssetElement/verticallyFlipped"
              ],
              "title": "Characterizing an Asset Element"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": [
            {
              "identifiers": [
                "doc://com.apple.photokit/documentation/PhotosUI/PHProjectElement"
              ],
              "kind": "relationships",
              "title": "Inherits From",
              "type": "inheritsFrom"
            },
            {
              "identifiers": [
                "doc://com.externally.resolved.symbol/c:objc(pl)NSSecureCoding"
              ],
              "kind": "relationships",
              "title": "Conforms To",
              "type": "conformsTo"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Subclassing-Project-Elements",
              "generated": true,
              "identifiers": [
                "doc://com.apple.photokit/documentation/PhotosUI/PHProjectTextElement",
                "doc://com.apple.photokit/documentation/PhotosUI/PHProjectJournalEntryElement",
                "doc://com.apple.photokit/documentation/PhotosUI/PHProjectMapElement"
              ],
              "title": "Subclassing Project Elements"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "macOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "@interface"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "PHProjectAssetElement"
                  },
                  {
                    "kind": "text",
                    "text": " : "
                  },
                  {
                    "identifier": "doc://com.apple.photokit/documentation/PhotosUI/PHProjectElement",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(cs)PHProjectElement",
                    "text": "PHProjectElement"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1PhotosUI~1PHProjectElement/title",
          "value": "PHProjectElement"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1PhotosUI~1PHProjectElement/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PHProjectElement"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1PhotosUI~1PHProjectElement/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "PHProjectElement"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1PhotosUI~1PHProjectAssetElement~1cropRect/title",
          "value": "cropRect"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1PhotosUI~1PHProjectAssetElement~1cropRect/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "cropRect"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1PhotosUI~1PHProjectAssetElement~1horizontallyFlipped/title",
          "value": "horizontallyFlipped"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1PhotosUI~1PHProjectAssetElement~1horizontallyFlipped/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "horizontallyFlipped"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1PhotosUI~1PHProjectJournalEntryElement/title",
          "value": "PHProjectJournalEntryElement"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1PhotosUI~1PHProjectJournalEntryElement/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PHProjectJournalEntryElement"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1PhotosUI~1PHProjectJournalEntryElement/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "PHProjectJournalEntryElement"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1PhotosUI~1PHProjectAssetElement~1cloudAssetIdentifier/title",
          "value": "cloudAssetIdentifier"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1PhotosUI~1PHProjectAssetElement~1cloudAssetIdentifier/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "cloudAssetIdentifier"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHAsset/title",
          "value": "PHAsset"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHAsset/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PHAsset"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHAsset/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "PHAsset"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1PhotosUI~1PHProjectAssetElement~1regionsOfInterest/title",
          "value": "regionsOfInterest"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1PhotosUI~1PHProjectAssetElement~1regionsOfInterest/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "regionsOfInterest"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1PhotosUI~1PHProjectAssetElement~1annotation/title",
          "value": "annotation"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1PhotosUI~1PHProjectAssetElement~1annotation/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "annotation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:objc(pl)NSObject/title",
          "value": "NSObject"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1PhotosUI~1PHProjectAssetElement~1verticallyFlipped/title",
          "value": "verticallyFlipped"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1PhotosUI~1PHProjectAssetElement~1verticallyFlipped/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "verticallyFlipped"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHAsset~1fetchAssets(withLocalIdentifiers:options:)/title",
          "value": "fetchAssetsWithLocalIdentifiers:options:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHAsset~1fetchAssets(withLocalIdentifiers:options:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "+ "
            },
            {
              "kind": "identifier",
              "text": "fetchAssetsWithLocalIdentifiers:options:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHAssetResource~1assetLocalIdentifier/title",
          "value": "assetLocalIdentifier"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHAssetResource~1assetLocalIdentifier/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "assetLocalIdentifier"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1PhotosUI~1PHProjectTextElement/title",
          "value": "PHProjectTextElement"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1PhotosUI~1PHProjectTextElement/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PHProjectTextElement"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1PhotosUI~1PHProjectTextElement/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "PHProjectTextElement"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1PhotosUI~1PHProjectMapElement/title",
          "value": "PHProjectMapElement"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1PhotosUI~1PHProjectMapElement/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PHProjectMapElement"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1PhotosUI~1PHProjectMapElement/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "PHProjectMapElement"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1PhotosUI~1PHProjectAssetElement/title",
          "value": "PHProjectAssetElement"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1PhotosUI~1PHProjectAssetElement/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PHProjectAssetElement"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1PhotosUI~1PHProjectAssetElement/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "PHProjectAssetElement"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1PhotosUI~1PHProjectSectionContent~1cloudAssetIdentifiers/title",
          "value": "cloudAssetIdentifiers"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1PhotosUI~1PHProjectSectionContent~1cloudAssetIdentifiers/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "cloudAssetIdentifiers"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/photosui/phprojectassetelement"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/photosui/phprojectassetelement"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
