{
  "abstract": [
    {
      "text": "The method that the person or system uses to take the reading.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.sensorkit/documentation/SensorKit",
        "doc://com.apple.sensorkit/documentation/SensorKit/SRPhotoplethysmogramSample"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.sensorkit/documentation/SensorKit/SRPhotoplethysmogramSample/usage-swift.property"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(cs)SRPhotoplethysmogramSample(py)usage",
    "fragments": [
      {
        "kind": "keyword",
        "text": "var"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "usage"
      },
      {
        "kind": "text",
        "text": ": ["
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:objc(cs)SRPhotoplethysmogramSample",
        "text": "SRPhotoplethysmogramSample"
      },
      {
        "kind": "text",
        "text": "."
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@T@SRPhotoplethysmogramSampleUsage",
        "text": "Usage"
      },
      {
        "kind": "text",
        "text": "]"
      }
    ],
    "modules": [
      {
        "name": "SensorKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "usage"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "17.4",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "17.4",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "17.4",
        "name": "Mac Catalyst",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Instance Property",
    "symbolKind": "property",
    "title": "usage"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "var"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "usage"
            },
            {
              "kind": "text",
              "text": ": ["
            },
            {
              "identifier": "doc://com.apple.sensorkit/documentation/SensorKit/SRPhotoplethysmogramSample",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)SRPhotoplethysmogramSample",
              "text": "SRPhotoplethysmogramSample"
            },
            {
              "kind": "text",
              "text": "."
            },
            {
              "identifier": "doc://com.apple.sensorkit/documentation/SensorKit/SRPhotoplethysmogramSample/Usage-swift.struct",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@SRPhotoplethysmogramSampleUsage",
              "text": "Usage"
            },
            {
              "kind": "text",
              "text": "] { "
            },
            {
              "kind": "keyword",
              "text": "get"
            },
            {
              "kind": "text",
              "text": " }"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.sensorkit/documentation/SensorKit": {
      "abstract": [
        {
          "text": "Retrieve data and derived metrics from sensors on an iPhone, or paired Apple Watch.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.sensorkit/documentation/SensorKit",
      "kind": "symbol",
      "role": "collection",
      "title": "SensorKit",
      "type": "topic",
      "url": "/documentation/sensorkit"
    },
    "doc://com.apple.sensorkit/documentation/SensorKit/SRPhotoplethysmogramAccelerometerSample": {
      "abstract": [
        {
          "text": "A data sample from the photoplethysmogram (PPG) accelerometer.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SRPhotoplethysmogramAccelerometerSample"
        }
      ],
      "identifier": "doc://com.apple.sensorkit/documentation/SensorKit/SRPhotoplethysmogramAccelerometerSample",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SRPhotoplethysmogramAccelerometerSample"
        }
      ],
      "role": "symbol",
      "title": "SRPhotoplethysmogramAccelerometerSample",
      "type": "topic",
      "url": "/documentation/sensorkit/srphotoplethysmogramaccelerometersample"
    },
    "doc://com.apple.sensorkit/documentation/SensorKit/SRPhotoplethysmogramOpticalSample": {
      "abstract": [
        {
          "text": "A data sample from the photoplethysmogram (PPG) optical sensor.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SRPhotoplethysmogramOpticalSample"
        }
      ],
      "identifier": "doc://com.apple.sensorkit/documentation/SensorKit/SRPhotoplethysmogramOpticalSample",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SRPhotoplethysmogramOpticalSample"
        }
      ],
      "role": "symbol",
      "title": "SRPhotoplethysmogramOpticalSample",
      "type": "topic",
      "url": "/documentation/sensorkit/srphotoplethysmogramopticalsample"
    },
    "doc://com.apple.sensorkit/documentation/SensorKit/SRPhotoplethysmogramSample": {
      "abstract": [
        {
          "text": "The sample photoplethysmogram (PPG) sensor data.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SRPhotoplethysmogramSample"
        }
      ],
      "identifier": "doc://com.apple.sensorkit/documentation/SensorKit/SRPhotoplethysmogramSample",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SRPhotoplethysmogramSample"
        }
      ],
      "role": "symbol",
      "title": "SRPhotoplethysmogramSample",
      "type": "topic",
      "url": "/documentation/sensorkit/srphotoplethysmogramsample"
    },
    "doc://com.apple.sensorkit/documentation/SensorKit/SRPhotoplethysmogramSample/Usage-swift.struct": {
      "abstract": [
        {
          "text": "The possible ways that a person or the system may take a photoplethysmogram (PPG) reading.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Usage"
        }
      ],
      "identifier": "doc://com.apple.sensorkit/documentation/SensorKit/SRPhotoplethysmogramSample/Usage-swift.struct",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "Usage"
        }
      ],
      "role": "symbol",
      "title": "SRPhotoplethysmogramSample.Usage",
      "type": "topic",
      "url": "/documentation/sensorkit/srphotoplethysmogramsample/usage-swift.struct"
    },
    "doc://com.apple.sensorkit/documentation/SensorKit/SRPhotoplethysmogramSample/accelerometerSamples": {
      "abstract": [
        {
          "text": "The samples recorded by the photoplethysmogram (PPG) accelerometer.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "accelerometerSamples"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)SRPhotoplethysmogramAccelerometerSample",
          "text": "SRPhotoplethysmogramAccelerometerSample"
        },
        {
          "kind": "text",
          "text": "]"
        }
      ],
      "identifier": "doc://com.apple.sensorkit/documentation/SensorKit/SRPhotoplethysmogramSample/accelerometerSamples",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "accelerometerSamples"
        }
      ],
      "role": "symbol",
      "title": "accelerometerSamples",
      "type": "topic",
      "url": "/documentation/sensorkit/srphotoplethysmogramsample/accelerometersamples"
    },
    "doc://com.apple.sensorkit/documentation/SensorKit/SRPhotoplethysmogramSample/nanosecondsSinceStart": {
      "abstract": [
        {
          "text": "The time in nanoseconds since the start of the data recording.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "nanosecondsSinceStart"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int64V",
          "text": "Int64"
        }
      ],
      "identifier": "doc://com.apple.sensorkit/documentation/SensorKit/SRPhotoplethysmogramSample/nanosecondsSinceStart",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "nanosecondsSinceStart"
        }
      ],
      "role": "symbol",
      "title": "nanosecondsSinceStart",
      "type": "topic",
      "url": "/documentation/sensorkit/srphotoplethysmogramsample/nanosecondssincestart"
    },
    "doc://com.apple.sensorkit/documentation/SensorKit/SRPhotoplethysmogramSample/opticalSamples": {
      "abstract": [
        {
          "text": "The samples recorded by the photoplethysmogram (PPG) optical sensor.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "opticalSamples"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)SRPhotoplethysmogramOpticalSample",
          "text": "SRPhotoplethysmogramOpticalSample"
        },
        {
          "kind": "text",
          "text": "]"
        }
      ],
      "identifier": "doc://com.apple.sensorkit/documentation/SensorKit/SRPhotoplethysmogramSample/opticalSamples",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "opticalSamples"
        }
      ],
      "role": "symbol",
      "title": "opticalSamples",
      "type": "topic",
      "url": "/documentation/sensorkit/srphotoplethysmogramsample/opticalsamples"
    },
    "doc://com.apple.sensorkit/documentation/SensorKit/SRPhotoplethysmogramSample/startDate": {
      "abstract": [
        {
          "text": "The start date of the photoplethysmogram (PPG) sensor data recording.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "startDate"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10Foundation4DateV",
          "text": "Date"
        }
      ],
      "identifier": "doc://com.apple.sensorkit/documentation/SensorKit/SRPhotoplethysmogramSample/startDate",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "startDate"
        }
      ],
      "role": "symbol",
      "title": "startDate",
      "type": "topic",
      "url": "/documentation/sensorkit/srphotoplethysmogramsample/startdate"
    },
    "doc://com.apple.sensorkit/documentation/SensorKit/SRPhotoplethysmogramSample/temperature": {
      "abstract": [
        {
          "text": "The samples recorded by the photoplethysmogram (PPG) thermometer.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "temperature"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10Foundation11MeasurementV",
          "text": "Measurement"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSUnitTemperature",
          "text": "UnitTemperature"
        },
        {
          "kind": "text",
          "text": ">?"
        }
      ],
      "identifier": "doc://com.apple.sensorkit/documentation/SensorKit/SRPhotoplethysmogramSample/temperature",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "temperature"
        }
      ],
      "role": "symbol",
      "title": "temperature",
      "type": "topic",
      "url": "/documentation/sensorkit/srphotoplethysmogramsample/temperature"
    },
    "doc://com.apple.sensorkit/documentation/SensorKit/SRPhotoplethysmogramSample/usage-swift.property": {
      "abstract": [
        {
          "text": "The method that the person or system uses to take the reading.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "usage"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)SRPhotoplethysmogramSample",
          "text": "SRPhotoplethysmogramSample"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@SRPhotoplethysmogramSampleUsage",
          "text": "Usage"
        },
        {
          "kind": "text",
          "text": "]"
        }
      ],
      "identifier": "doc://com.apple.sensorkit/documentation/SensorKit/SRPhotoplethysmogramSample/usage-swift.property",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "usage"
        }
      ],
      "role": "symbol",
      "title": "usage",
      "type": "topic",
      "url": "/documentation/sensorkit/srphotoplethysmogramsample/usage-swift.property"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Accessing-PPG-data",
      "generated": true,
      "identifiers": [
        "doc://com.apple.sensorkit/documentation/SensorKit/SRPhotoplethysmogramSample/startDate",
        "doc://com.apple.sensorkit/documentation/SensorKit/SRPhotoplethysmogramSample/nanosecondsSinceStart",
        "doc://com.apple.sensorkit/documentation/SensorKit/SRPhotoplethysmogramSample/Usage-swift.struct",
        "doc://com.apple.sensorkit/documentation/SensorKit/SRPhotoplethysmogramSample/opticalSamples",
        "doc://com.apple.sensorkit/documentation/SensorKit/SRPhotoplethysmogramOpticalSample",
        "doc://com.apple.sensorkit/documentation/SensorKit/SRPhotoplethysmogramSample/accelerometerSamples",
        "doc://com.apple.sensorkit/documentation/SensorKit/SRPhotoplethysmogramAccelerometerSample",
        "doc://com.apple.sensorkit/documentation/SensorKit/SRPhotoplethysmogramSample/temperature"
      ],
      "title": "Accessing PPG data"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "17.4",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "17.4",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "17.4",
              "name": "Mac Catalyst",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Instance Property"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "usage"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "property"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "usage"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.sensorkit/documentation/SensorKit",
                "doc://com.apple.sensorkit/documentation/SensorKit/SRPhotoplethysmogramSample"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Accessing-PPG-data",
              "generated": true,
              "identifiers": [
                "doc://com.apple.sensorkit/documentation/SensorKit/SRPhotoplethysmogramSample/startDate",
                "doc://com.apple.sensorkit/documentation/SensorKit/SRPhotoplethysmogramSample/nanosecondsSinceStart",
                "doc://com.apple.sensorkit/documentation/SensorKit/SRPhotoplethysmogramSample/Usage-swift.struct",
                "doc://com.apple.sensorkit/documentation/SensorKit/SRPhotoplethysmogramSample/opticalSamples",
                "doc://com.apple.sensorkit/documentation/SensorKit/SRPhotoplethysmogramOpticalSample",
                "doc://com.apple.sensorkit/documentation/SensorKit/SRPhotoplethysmogramSample/accelerometerSamples",
                "doc://com.apple.sensorkit/documentation/SensorKit/SRPhotoplethysmogramAccelerometerSample",
                "doc://com.apple.sensorkit/documentation/SensorKit/SRPhotoplethysmogramSample/temperature"
              ],
              "title": "Accessing PPG data"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "@property"
                  },
                  {
                    "kind": "text",
                    "text": " ("
                  },
                  {
                    "kind": "keyword",
                    "text": "nonatomic"
                  },
                  {
                    "kind": "text",
                    "text": ", "
                  },
                  {
                    "kind": "keyword",
                    "text": "copy"
                  },
                  {
                    "kind": "text",
                    "text": ", "
                  },
                  {
                    "kind": "keyword",
                    "text": "readonly"
                  },
                  {
                    "kind": "text",
                    "text": ") "
                  },
                  {
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:Q$objc(cs)NSArray",
                    "text": "NSArray<NSString *>"
                  },
                  {
                    "kind": "text",
                    "text": " * "
                  },
                  {
                    "kind": "identifier",
                    "text": "usage"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sensorkit~1documentation~1SensorKit~1SRPhotoplethysmogramSample~1accelerometerSamples/title",
          "value": "accelerometerSamples"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sensorkit~1documentation~1SensorKit~1SRPhotoplethysmogramSample~1accelerometerSamples/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "accelerometerSamples"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sensorkit~1documentation~1SensorKit~1SRPhotoplethysmogramAccelerometerSample/title",
          "value": "SRPhotoplethysmogramAccelerometerSample"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sensorkit~1documentation~1SensorKit~1SRPhotoplethysmogramAccelerometerSample/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SRPhotoplethysmogramAccelerometerSample"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sensorkit~1documentation~1SensorKit~1SRPhotoplethysmogramAccelerometerSample/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SRPhotoplethysmogramAccelerometerSample"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sensorkit~1documentation~1SensorKit~1SRPhotoplethysmogramSample~1usage-swift.property/title",
          "value": "usage"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sensorkit~1documentation~1SensorKit~1SRPhotoplethysmogramSample~1usage-swift.property/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "usage"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sensorkit~1documentation~1SensorKit~1SRPhotoplethysmogramSample/title",
          "value": "SRPhotoplethysmogramSample"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sensorkit~1documentation~1SensorKit~1SRPhotoplethysmogramSample/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SRPhotoplethysmogramSample"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sensorkit~1documentation~1SensorKit~1SRPhotoplethysmogramSample/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SRPhotoplethysmogramSample"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sensorkit~1documentation~1SensorKit~1SRPhotoplethysmogramSample~1nanosecondsSinceStart/title",
          "value": "nanosecondsSinceStart"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sensorkit~1documentation~1SensorKit~1SRPhotoplethysmogramSample~1nanosecondsSinceStart/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "nanosecondsSinceStart"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sensorkit~1documentation~1SensorKit~1SRPhotoplethysmogramSample~1startDate/title",
          "value": "startDate"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sensorkit~1documentation~1SensorKit~1SRPhotoplethysmogramSample~1startDate/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "startDate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sensorkit~1documentation~1SensorKit~1SRPhotoplethysmogramSample~1Usage-swift.struct/title",
          "value": "SRPhotoplethysmogramSampleUsage"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sensorkit~1documentation~1SensorKit~1SRPhotoplethysmogramSample~1Usage-swift.struct/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SRPhotoplethysmogramSampleUsage"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sensorkit~1documentation~1SensorKit~1SRPhotoplethysmogramSample~1Usage-swift.struct/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SRPhotoplethysmogramSampleUsage"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sensorkit~1documentation~1SensorKit~1SRPhotoplethysmogramOpticalSample/title",
          "value": "SRPhotoplethysmogramOpticalSample"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sensorkit~1documentation~1SensorKit~1SRPhotoplethysmogramOpticalSample/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SRPhotoplethysmogramOpticalSample"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sensorkit~1documentation~1SensorKit~1SRPhotoplethysmogramOpticalSample/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SRPhotoplethysmogramOpticalSample"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sensorkit~1documentation~1SensorKit~1SRPhotoplethysmogramSample~1opticalSamples/title",
          "value": "opticalSamples"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sensorkit~1documentation~1SensorKit~1SRPhotoplethysmogramSample~1opticalSamples/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "opticalSamples"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sensorkit~1documentation~1SensorKit~1SRPhotoplethysmogramSample~1temperature/title",
          "value": "temperature"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sensorkit~1documentation~1SensorKit~1SRPhotoplethysmogramSample~1temperature/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "temperature"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/sensorkit/srphotoplethysmogramsample/usage-swift.property"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/sensorkit/srphotoplethysmogramsample/usage-swift.property"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
