{
  "abstract": [
    {
      "text": "Error codes for identity operations.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.passkit/documentation/PassKit",
        "doc://com.apple.passkit/documentation/PassKit/PKIdentityError-swift.struct"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.passkit/documentation/PassKit/PKIdentityError-swift.struct/Code"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@PKIdentityError",
    "fragments": [
      {
        "kind": "keyword",
        "text": "enum"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "Code"
      }
    ],
    "modules": [
      {
        "name": "PassKit (Apple Pay and Wallet)"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "Code"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "16.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "16.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "16.0",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "9.0",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Enumeration",
    "symbolKind": "enum",
    "title": "PKIdentityError.Code"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "enum"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "Code"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.passkit/documentation/PassKit": {
      "abstract": [
        {
          "text": "Process Apple Pay payments in your app, and create and distribute passes for the Wallet app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.passkit/documentation/PassKit",
      "kind": "symbol",
      "role": "collection",
      "title": "PassKit (Apple Pay and Wallet)",
      "type": "topic",
      "url": "/documentation/passkit"
    },
    "doc://com.apple.passkit/documentation/PassKit/PKAddPaymentPassError": {
      "abstract": [
        {
          "text": "Error codes for adding payment passes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "PKAddPaymentPassError"
        }
      ],
      "identifier": "doc://com.apple.passkit/documentation/PassKit/PKAddPaymentPassError",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PKAddPaymentPassError"
        }
      ],
      "role": "symbol",
      "title": "PKAddPaymentPassError",
      "type": "topic",
      "url": "/documentation/passkit/pkaddpaymentpasserror"
    },
    "doc://com.apple.passkit/documentation/PassKit/PKAddSecureElementPassError": {
      "abstract": [
        {
          "text": "An error object that PassKit uses when it adds Secure Element passes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "PKAddSecureElementPassError"
        }
      ],
      "identifier": "doc://com.apple.passkit/documentation/PassKit/PKAddSecureElementPassError",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PKAddSecureElementPassError"
        }
      ],
      "role": "symbol",
      "title": "PKAddSecureElementPassError",
      "type": "topic",
      "url": "/documentation/passkit/pkaddsecureelementpasserror"
    },
    "doc://com.apple.passkit/documentation/PassKit/PKAddSecureElementPassError/Code": {
      "abstract": [
        {
          "text": "Error codes for problems that occur when you add a secure element passes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.passkit/documentation/PassKit/PKAddSecureElementPassError/Code",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "Code"
        }
      ],
      "role": "symbol",
      "title": "PKAddSecureElementPassError.Code",
      "type": "topic",
      "url": "/documentation/passkit/pkaddsecureelementpasserror/code"
    },
    "doc://com.apple.passkit/documentation/PassKit/PKAddSecureElementPassErrorDomain": {
      "abstract": [
        {
          "text": "The error domain for errors that occur when adding a secure pass.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "PKAddSecureElementPassErrorDomain"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.passkit/documentation/PassKit/PKAddSecureElementPassErrorDomain",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PKAddSecureElementPassErrorDomain"
        }
      ],
      "role": "symbol",
      "title": "PKAddSecureElementPassErrorDomain",
      "type": "topic",
      "url": "/documentation/passkit/pkaddsecureelementpasserrordomain"
    },
    "doc://com.apple.passkit/documentation/PassKit/PKIdentityError-swift.struct": {
      "abstract": [
        {
          "text": "A structure that represents an identity error.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "PKIdentityError"
        }
      ],
      "identifier": "doc://com.apple.passkit/documentation/PassKit/PKIdentityError-swift.struct",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PKIdentityError"
        }
      ],
      "role": "symbol",
      "title": "PKIdentityError",
      "type": "topic",
      "url": "/documentation/passkit/pkidentityerror-swift.struct"
    },
    "doc://com.apple.passkit/documentation/PassKit/PKIdentityError-swift.struct/Code": {
      "abstract": [
        {
          "text": "Error codes for identity operations.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.passkit/documentation/PassKit/PKIdentityError-swift.struct/Code",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "Code"
        }
      ],
      "role": "symbol",
      "title": "PKIdentityError.Code",
      "type": "topic",
      "url": "/documentation/passkit/pkidentityerror-swift.struct/code"
    },
    "doc://com.apple.passkit/documentation/PassKit/PKIdentityError-swift.struct/Code/cancelled": {
      "abstract": [
        {
          "text": "An error that indicates the user cancels the presented sheet.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "cancelled"
        }
      ],
      "identifier": "doc://com.apple.passkit/documentation/PassKit/PKIdentityError-swift.struct/Code/cancelled",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PKIdentityErrorCancelled"
        }
      ],
      "role": "symbol",
      "title": "PKIdentityError.Code.cancelled",
      "type": "topic",
      "url": "/documentation/passkit/pkidentityerror-swift.struct/code/cancelled"
    },
    "doc://com.apple.passkit/documentation/PassKit/PKIdentityError-swift.struct/Code/init(rawValue:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "?("
        },
        {
          "kind": "externalParam",
          "text": "rawValue"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.passkit/documentation/PassKit/PKIdentityError-swift.struct/Code/init(rawValue:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "init(rawValue:)",
      "type": "topic",
      "url": "/documentation/passkit/pkidentityerror-swift.struct/code/init(rawvalue:)"
    },
    "doc://com.apple.passkit/documentation/PassKit/PKIdentityError-swift.struct/Code/invalidElement": {
      "abstract": [
        {
          "text": "An error that indicates an element the app requests isn’t valid.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "invalidElement"
        }
      ],
      "identifier": "doc://com.apple.passkit/documentation/PassKit/PKIdentityError-swift.struct/Code/invalidElement",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PKIdentityErrorInvalidElement"
        }
      ],
      "role": "symbol",
      "title": "PKIdentityError.Code.invalidElement",
      "type": "topic",
      "url": "/documentation/passkit/pkidentityerror-swift.struct/code/invalidelement"
    },
    "doc://com.apple.passkit/documentation/PassKit/PKIdentityError-swift.struct/Code/invalidNonce": {
      "abstract": [
        {
          "text": "An error that indicates the number is too large or unsuitable.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "invalidNonce"
        }
      ],
      "identifier": "doc://com.apple.passkit/documentation/PassKit/PKIdentityError-swift.struct/Code/invalidNonce",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PKIdentityErrorInvalidNonce"
        }
      ],
      "role": "symbol",
      "title": "PKIdentityError.Code.invalidNonce",
      "type": "topic",
      "url": "/documentation/passkit/pkidentityerror-swift.struct/code/invalidnonce"
    },
    "doc://com.apple.passkit/documentation/PassKit/PKIdentityError-swift.struct/Code/networkUnavailable": {
      "abstract": [
        {
          "text": "An error that indicates a network isn’t available.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "networkUnavailable"
        }
      ],
      "identifier": "doc://com.apple.passkit/documentation/PassKit/PKIdentityError-swift.struct/Code/networkUnavailable",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PKIdentityErrorNetworkUnavailable"
        }
      ],
      "role": "symbol",
      "title": "PKIdentityError.Code.networkUnavailable",
      "type": "topic",
      "url": "/documentation/passkit/pkidentityerror-swift.struct/code/networkunavailable"
    },
    "doc://com.apple.passkit/documentation/PassKit/PKIdentityError-swift.struct/Code/noElementsRequested": {
      "abstract": [
        {
          "text": "An error that indicates the elements aren’t supported.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "noElementsRequested"
        }
      ],
      "identifier": "doc://com.apple.passkit/documentation/PassKit/PKIdentityError-swift.struct/Code/noElementsRequested",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PKIdentityErrorNoElementsRequested"
        }
      ],
      "role": "symbol",
      "title": "PKIdentityError.Code.noElementsRequested",
      "type": "topic",
      "url": "/documentation/passkit/pkidentityerror-swift.struct/code/noelementsrequested"
    },
    "doc://com.apple.passkit/documentation/PassKit/PKIdentityError-swift.struct/Code/notSupported": {
      "abstract": [
        {
          "text": "An error that indicates the request originates from a device the framework doesn’t support.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "notSupported"
        }
      ],
      "identifier": "doc://com.apple.passkit/documentation/PassKit/PKIdentityError-swift.struct/Code/notSupported",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PKIdentityErrorNotSupported"
        }
      ],
      "role": "symbol",
      "title": "PKIdentityError.Code.notSupported",
      "type": "topic",
      "url": "/documentation/passkit/pkidentityerror-swift.struct/code/notsupported"
    },
    "doc://com.apple.passkit/documentation/PassKit/PKIdentityError-swift.struct/Code/regionNotSupported": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "regionNotSupported"
        }
      ],
      "identifier": "doc://com.apple.passkit/documentation/PassKit/PKIdentityError-swift.struct/Code/regionNotSupported",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PKIdentityErrorRegionNotSupported"
        }
      ],
      "role": "symbol",
      "title": "PKIdentityError.Code.regionNotSupported",
      "type": "topic",
      "url": "/documentation/passkit/pkidentityerror-swift.struct/code/regionnotsupported"
    },
    "doc://com.apple.passkit/documentation/PassKit/PKIdentityError-swift.struct/Code/requestAlreadyInProgress": {
      "abstract": [
        {
          "text": "An error that indicates a request is already in progress.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "requestAlreadyInProgress"
        }
      ],
      "identifier": "doc://com.apple.passkit/documentation/PassKit/PKIdentityError-swift.struct/Code/requestAlreadyInProgress",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PKIdentityErrorRequestAlreadyInProgress"
        }
      ],
      "role": "symbol",
      "title": "PKIdentityError.Code.requestAlreadyInProgress",
      "type": "topic",
      "url": "/documentation/passkit/pkidentityerror-swift.struct/code/requestalreadyinprogress"
    },
    "doc://com.apple.passkit/documentation/PassKit/PKIdentityError-swift.struct/Code/unknown": {
      "abstract": [
        {
          "text": "An error that indicates an unknown error.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "unknown"
        }
      ],
      "identifier": "doc://com.apple.passkit/documentation/PassKit/PKIdentityError-swift.struct/Code/unknown",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PKIdentityErrorUnknown"
        }
      ],
      "role": "symbol",
      "title": "PKIdentityError.Code.unknown",
      "type": "topic",
      "url": "/documentation/passkit/pkidentityerror-swift.struct/code/unknown"
    },
    "doc://com.apple.passkit/documentation/PassKit/PKIdentityErrorDomain": {
      "abstract": [
        {
          "text": "The error domain for identity errors.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "PKIdentityErrorDomain"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.passkit/documentation/PassKit/PKIdentityErrorDomain",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PKIdentityErrorDomain"
        }
      ],
      "role": "symbol",
      "title": "PKIdentityErrorDomain",
      "type": "topic",
      "url": "/documentation/passkit/pkidentityerrordomain"
    },
    "doc://com.apple.passkit/documentation/PassKit/PKPassKitError": {
      "abstract": [
        {
          "text": "Errors that the PassKit framework uses.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "PKPassKitError"
        }
      ],
      "identifier": "doc://com.apple.passkit/documentation/PassKit/PKPassKitError",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PKPassKitError"
        }
      ],
      "role": "symbol",
      "title": "PKPassKitError",
      "type": "topic",
      "url": "/documentation/passkit/pkpasskiterror"
    },
    "doc://com.apple.passkit/documentation/PassKit/PKPassKitError/Code": {
      "abstract": [
        {
          "text": "Errors that the PassKit framework uses.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.passkit/documentation/PassKit/PKPassKitError/Code",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "Code"
        }
      ],
      "role": "symbol",
      "title": "PKPassKitError.Code",
      "type": "topic",
      "url": "/documentation/passkit/pkpasskiterror/code"
    },
    "doc://com.apple.passkit/documentation/PassKit/PKPassKitErrorDomain": {
      "abstract": [
        {
          "text": "The error domain for PassKit errors.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "PKPassKitErrorDomain"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.passkit/documentation/PassKit/PKPassKitErrorDomain",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PKPassKitErrorDomain"
        }
      ],
      "role": "symbol",
      "title": "PKPassKitErrorDomain",
      "type": "topic",
      "url": "/documentation/passkit/pkpasskiterrordomain"
    },
    "doc://com.apple.passkit/documentation/PassKit/PKShareSecureElementPassError": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "PKShareSecureElementPassError"
        }
      ],
      "identifier": "doc://com.apple.passkit/documentation/PassKit/PKShareSecureElementPassError",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PKShareSecureElementPassError"
        }
      ],
      "role": "symbol",
      "title": "PKShareSecureElementPassError",
      "type": "topic",
      "url": "/documentation/passkit/pksharesecureelementpasserror"
    },
    "doc://com.apple.passkit/documentation/PassKit/PKShareSecureElementPassError/Code": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.passkit/documentation/PassKit/PKShareSecureElementPassError/Code",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "Code"
        }
      ],
      "role": "symbol",
      "title": "PKShareSecureElementPassError.Code",
      "type": "topic",
      "url": "/documentation/passkit/pksharesecureelementpasserror/code"
    },
    "doc://com.apple.passkit/documentation/PassKit/PKShareSecureElementPassErrorDomain": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "PKShareSecureElementPassErrorDomain"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.passkit/documentation/PassKit/PKShareSecureElementPassErrorDomain",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PKShareSecureElementPassErrorDomain"
        }
      ],
      "role": "symbol",
      "title": "PKShareSecureElementPassErrorDomain",
      "type": "topic",
      "url": "/documentation/passkit/pksharesecureelementpasserrordomain"
    },
    "doc://com.apple.passkit/documentation/PassKit/PKVehicleConnectionErrorCode": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "PKVehicleConnectionErrorCode"
        }
      ],
      "identifier": "doc://com.apple.passkit/documentation/PassKit/PKVehicleConnectionErrorCode",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PKVehicleConnectionErrorCode"
        }
      ],
      "role": "symbol",
      "title": "PKVehicleConnectionErrorCode",
      "type": "topic",
      "url": "/documentation/passkit/pkvehicleconnectionerrorcode"
    },
    "doc://com.apple.passkit/documentation/PassKit/PayWithApplePayButtonPaymentAuthorizationPhase": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "PayWithApplePayButtonPaymentAuthorizationPhase"
        }
      ],
      "identifier": "doc://com.apple.passkit/documentation/PassKit/PayWithApplePayButtonPaymentAuthorizationPhase",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PayWithApplePayButtonPaymentAuthorizationPhase"
        }
      ],
      "role": "symbol",
      "title": "PayWithApplePayButtonPaymentAuthorizationPhase",
      "type": "topic",
      "url": "/documentation/passkit/paywithapplepaybuttonpaymentauthorizationphase"
    },
    "doc://com.externally.resolved.symbol/s:SH": {
      "abstract": [
        {
          "text": "A type that can be hashed into a `Hasher` to produce an integer hash value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Hashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SQ",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SH",
      "kind": "symbol",
      "role": "symbol",
      "title": "Hashable",
      "type": "topic",
      "url": "/documentation/Swift/Hashable"
    },
    "doc://com.externally.resolved.symbol/s:SQ": {
      "abstract": [
        {
          "text": "A type that can be compared for value equality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SQ",
      "kind": "symbol",
      "role": "symbol",
      "title": "Equatable",
      "type": "topic",
      "url": "/documentation/Swift/Equatable"
    },
    "doc://com.externally.resolved.symbol/s:SY": {
      "abstract": [
        {
          "text": "A type that can be converted to and from an associated raw value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "RawRepresentable"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SY8RawValueQa",
          "text": "RawValue"
        },
        {
          "kind": "text",
          "text": ">"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SY",
      "kind": "symbol",
      "role": "symbol",
      "title": "RawRepresentable",
      "type": "topic",
      "url": "/documentation/Swift/RawRepresentable"
    },
    "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BitwiseCopyable"
        },
        {
          "kind": "text",
          "text": " : ~Escapable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "BitwiseCopyable",
      "type": "topic",
      "url": "/documentation/Swift/BitwiseCopyable"
    },
    "doc://com.externally.resolved.symbol/s:s8SendableP": {
      "abstract": [
        {
          "text": "A thread-safe type whose values can be shared across arbitrary concurrent contexts without introducing a risk of data races.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Sendable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s8SendableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "Sendable",
      "type": "topic",
      "url": "/documentation/Swift/Sendable"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
        "doc://com.externally.resolved.symbol/s:SQ",
        "doc://com.externally.resolved.symbol/s:SH",
        "doc://com.externally.resolved.symbol/s:SY",
        "doc://com.externally.resolved.symbol/s:s8SendableP"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Errors",
      "generated": true,
      "identifiers": [
        "doc://com.apple.passkit/documentation/PassKit/PKPassKitError",
        "doc://com.apple.passkit/documentation/PassKit/PKAddSecureElementPassError",
        "doc://com.apple.passkit/documentation/PassKit/PKPassKitError/Code",
        "doc://com.apple.passkit/documentation/PassKit/PKAddSecureElementPassError/Code",
        "doc://com.apple.passkit/documentation/PassKit/PKAddPaymentPassError",
        "doc://com.apple.passkit/documentation/PassKit/PKIdentityError-swift.struct",
        "doc://com.apple.passkit/documentation/PassKit/PKShareSecureElementPassError",
        "doc://com.apple.passkit/documentation/PassKit/PKShareSecureElementPassError/Code",
        "doc://com.apple.passkit/documentation/PassKit/PKVehicleConnectionErrorCode",
        "doc://com.apple.passkit/documentation/PassKit/PayWithApplePayButtonPaymentAuthorizationPhase",
        "doc://com.apple.passkit/documentation/PassKit/PKPassKitErrorDomain",
        "doc://com.apple.passkit/documentation/PassKit/PKIdentityErrorDomain",
        "doc://com.apple.passkit/documentation/PassKit/PKAddSecureElementPassErrorDomain",
        "doc://com.apple.passkit/documentation/PassKit/PKShareSecureElementPassErrorDomain"
      ],
      "title": "Errors"
    }
  ],
  "topicSections": [
    {
      "anchor": "Error-codes",
      "identifiers": [
        "doc://com.apple.passkit/documentation/PassKit/PKIdentityError-swift.struct/Code/cancelled",
        "doc://com.apple.passkit/documentation/PassKit/PKIdentityError-swift.struct/Code/invalidElement",
        "doc://com.apple.passkit/documentation/PassKit/PKIdentityError-swift.struct/Code/invalidNonce",
        "doc://com.apple.passkit/documentation/PassKit/PKIdentityError-swift.struct/Code/notSupported",
        "doc://com.apple.passkit/documentation/PassKit/PKIdentityError-swift.struct/Code/networkUnavailable",
        "doc://com.apple.passkit/documentation/PassKit/PKIdentityError-swift.struct/Code/noElementsRequested",
        "doc://com.apple.passkit/documentation/PassKit/PKIdentityError-swift.struct/Code/requestAlreadyInProgress",
        "doc://com.apple.passkit/documentation/PassKit/PKIdentityError-swift.struct/Code/unknown"
      ],
      "title": "Error codes"
    },
    {
      "anchor": "Enumeration-Cases",
      "generated": true,
      "identifiers": [
        "doc://com.apple.passkit/documentation/PassKit/PKIdentityError-swift.struct/Code/regionNotSupported"
      ],
      "title": "Enumeration Cases"
    },
    {
      "anchor": "Initializers",
      "generated": true,
      "identifiers": [
        "doc://com.apple.passkit/documentation/PassKit/PKIdentityError-swift.struct/Code/init(rawValue:)"
      ],
      "title": "Initializers"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "16.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "16.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "16.0",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "9.0",
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "PKIdentityError"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "enum"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PKIdentityError"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "PKIdentityError"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.passkit/documentation/PassKit"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Error-codes",
              "identifiers": [
                "doc://com.apple.passkit/documentation/PassKit/PKIdentityError-swift.struct/Code/cancelled",
                "doc://com.apple.passkit/documentation/PassKit/PKIdentityError-swift.struct/Code/invalidElement",
                "doc://com.apple.passkit/documentation/PassKit/PKIdentityError-swift.struct/Code/invalidNonce",
                "doc://com.apple.passkit/documentation/PassKit/PKIdentityError-swift.struct/Code/notSupported",
                "doc://com.apple.passkit/documentation/PassKit/PKIdentityError-swift.struct/Code/networkUnavailable",
                "doc://com.apple.passkit/documentation/PassKit/PKIdentityError-swift.struct/Code/noElementsRequested",
                "doc://com.apple.passkit/documentation/PassKit/PKIdentityError-swift.struct/Code/requestAlreadyInProgress",
                "doc://com.apple.passkit/documentation/PassKit/PKIdentityError-swift.struct/Code/unknown"
              ],
              "title": "Error codes"
            },
            {
              "anchor": "Enumeration-Cases",
              "generated": true,
              "identifiers": [
                "doc://com.apple.passkit/documentation/PassKit/PKIdentityError-swift.struct/Code/regionNotSupported"
              ],
              "title": "Enumeration Cases"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Errors",
              "generated": true,
              "identifiers": [
                "doc://com.apple.passkit/documentation/PassKit/PKPassKitError/Code",
                "doc://com.apple.passkit/documentation/PassKit/PKAddSecureElementPassError/Code",
                "doc://com.apple.passkit/documentation/PassKit/PKAddPaymentPassError",
                "doc://com.apple.passkit/documentation/PassKit/PKShareSecureElementPassError/Code",
                "doc://com.apple.passkit/documentation/PassKit/PKVehicleConnectionErrorCode",
                "doc://com.apple.passkit/documentation/PassKit/PKPassKitErrorDomain",
                "doc://com.apple.passkit/documentation/PassKit/PKIdentityErrorDomain",
                "doc://com.apple.passkit/documentation/PassKit/PKAddSecureElementPassErrorDomain",
                "doc://com.apple.passkit/documentation/PassKit/PKShareSecureElementPassErrorDomain"
              ],
              "title": "Errors"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "enum"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "PKIdentityError"
                  },
                  {
                    "kind": "text",
                    "text": " : "
                  },
                  {
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@NSInteger",
                    "text": "NSInteger"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKAddSecureElementPassError~1Code/title",
          "value": "PKAddSecureElementPassErrorCode"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKAddSecureElementPassError~1Code/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PKAddSecureElementPassErrorCode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKAddSecureElementPassError~1Code/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "PKAddSecureElementPassErrorCode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKVehicleConnectionErrorCode/title",
          "value": "PKVehicleConnectionErrorCode"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKVehicleConnectionErrorCode/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PKVehicleConnectionErrorCode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKVehicleConnectionErrorCode/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "PKVehicleConnectionErrorCode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKIdentityError-swift.struct~1Code~1noElementsRequested/title",
          "value": "PKIdentityErrorNoElementsRequested"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKIdentityError-swift.struct~1Code~1noElementsRequested/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PKIdentityErrorNoElementsRequested"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKIdentityError-swift.struct~1Code~1requestAlreadyInProgress/title",
          "value": "PKIdentityErrorRequestAlreadyInProgress"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKIdentityError-swift.struct~1Code~1requestAlreadyInProgress/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PKIdentityErrorRequestAlreadyInProgress"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKShareSecureElementPassErrorDomain/title",
          "value": "PKShareSecureElementPassErrorDomain"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKShareSecureElementPassErrorDomain/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PKShareSecureElementPassErrorDomain"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKIdentityErrorDomain/title",
          "value": "PKIdentityErrorDomain"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKIdentityErrorDomain/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PKIdentityErrorDomain"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKIdentityError-swift.struct~1Code~1unknown/title",
          "value": "PKIdentityErrorUnknown"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKIdentityError-swift.struct~1Code~1unknown/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PKIdentityErrorUnknown"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKPassKitErrorDomain/title",
          "value": "PKPassKitErrorDomain"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKPassKitErrorDomain/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PKPassKitErrorDomain"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKIdentityError-swift.struct~1Code~1invalidNonce/title",
          "value": "PKIdentityErrorInvalidNonce"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKIdentityError-swift.struct~1Code~1invalidNonce/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PKIdentityErrorInvalidNonce"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKIdentityError-swift.struct~1Code~1networkUnavailable/title",
          "value": "PKIdentityErrorNetworkUnavailable"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKIdentityError-swift.struct~1Code~1networkUnavailable/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PKIdentityErrorNetworkUnavailable"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKAddSecureElementPassErrorDomain/title",
          "value": "PKAddSecureElementPassErrorDomain"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKAddSecureElementPassErrorDomain/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PKAddSecureElementPassErrorDomain"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKAddPaymentPassError/title",
          "value": "PKAddPaymentPassError"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKAddPaymentPassError/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PKAddPaymentPassError"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKAddPaymentPassError/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "PKAddPaymentPassError"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKIdentityError-swift.struct~1Code/title",
          "value": "PKIdentityError"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKIdentityError-swift.struct~1Code/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PKIdentityError"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKIdentityError-swift.struct~1Code/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "PKIdentityError"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKShareSecureElementPassError~1Code/title",
          "value": "PKShareSecureElementPassErrorCode"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKShareSecureElementPassError~1Code/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PKShareSecureElementPassErrorCode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKShareSecureElementPassError~1Code/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "PKShareSecureElementPassErrorCode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKIdentityError-swift.struct~1Code~1invalidElement/title",
          "value": "PKIdentityErrorInvalidElement"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKIdentityError-swift.struct~1Code~1invalidElement/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PKIdentityErrorInvalidElement"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKIdentityError-swift.struct~1Code~1notSupported/title",
          "value": "PKIdentityErrorNotSupported"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKIdentityError-swift.struct~1Code~1notSupported/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PKIdentityErrorNotSupported"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKIdentityError-swift.struct~1Code~1cancelled/title",
          "value": "PKIdentityErrorCancelled"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKIdentityError-swift.struct~1Code~1cancelled/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PKIdentityErrorCancelled"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKPassKitError~1Code/title",
          "value": "PKPassKitErrorCode"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKPassKitError~1Code/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PKPassKitErrorCode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKPassKitError~1Code/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "PKPassKitErrorCode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKIdentityError-swift.struct~1Code~1regionNotSupported/title",
          "value": "PKIdentityErrorRegionNotSupported"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKIdentityError-swift.struct~1Code~1regionNotSupported/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PKIdentityErrorRegionNotSupported"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/passkit/pkidentityerror-swift.struct/code"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/passkit/pkidentityerror-swift.struct/code"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
