{
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.Exception-Handling/documentation/ExceptionHandling"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.Exception-Handling/documentation/ExceptionHandling/exceptionhandling-constants"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "Exception Handling"
      }
    ],
    "role": "collectionGroup",
    "roleHeading": "API Collection",
    "title": "ExceptionHandling Constants"
  },
  "references": {
    "doc://com.apple.Exception-Handling/documentation/ExceptionHandling": {
      "abstract": [
        {
          "text": "Monitor and debug exceptional conditions in code.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.Exception-Handling/documentation/ExceptionHandling",
      "kind": "symbol",
      "role": "collection",
      "title": "Exception Handling",
      "type": "topic",
      "url": "/documentation/exceptionhandling"
    },
    "doc://com.apple.Exception-Handling/documentation/ExceptionHandling/EXCEPTIONHANDLING_EXPORT": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "EXCEPTIONHANDLING_EXPORT"
        }
      ],
      "identifier": "doc://com.apple.Exception-Handling/documentation/ExceptionHandling/EXCEPTIONHANDLING_EXPORT",
      "kind": "symbol",
      "role": "symbol",
      "title": "EXCEPTIONHANDLING_EXPORT",
      "type": "topic",
      "url": "/documentation/exceptionhandling/exceptionhandling_export"
    },
    "doc://com.apple.Exception-Handling/documentation/ExceptionHandling/EXCEPTIONHANDLING_IMPORT": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "EXCEPTIONHANDLING_IMPORT"
        }
      ],
      "identifier": "doc://com.apple.Exception-Handling/documentation/ExceptionHandling/EXCEPTIONHANDLING_IMPORT",
      "kind": "symbol",
      "role": "symbol",
      "title": "EXCEPTIONHANDLING_IMPORT",
      "type": "topic",
      "url": "/documentation/exceptionhandling/exceptionhandling_import"
    },
    "doc://com.apple.Exception-Handling/documentation/ExceptionHandling/NSStackTraceKey": {
      "abstract": [
        {
          "text": "The key for fetching the stack trace (an ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.documentation/documentation/foundation/nsstring",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " ",
          "type": "text"
        },
        {
          "text": "object) in the ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.documentation/documentation/foundation/nsexception/1418149-userinfo",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " ",
          "type": "text"
        },
        {
          "text": "dictionary of the ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.documentation/documentation/foundation/nsexception",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " ",
          "type": "text"
        },
        {
          "text": "object passed into one of the delegate methods described in ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.documentation/documentation/ExceptionHandling/nsexceptionhandlerdelegate#Logging-and-handling-exceptions",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": ".",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSStackTraceKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.Exception-Handling/documentation/ExceptionHandling/NSStackTraceKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSStackTraceKey"
        }
      ],
      "role": "symbol",
      "title": "NSStackTraceKey",
      "type": "topic",
      "url": "/documentation/exceptionhandling/nsstacktracekey"
    },
    "doc://com.apple.Exception-Handling/documentation/ExceptionHandling/NSUncaughtRuntimeErrorException": {
      "abstract": [
        {
          "text": "Identifies an Objective-C runtime error.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSUncaughtRuntimeErrorException"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.Exception-Handling/documentation/ExceptionHandling/NSUncaughtRuntimeErrorException",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSUncaughtRuntimeErrorException"
        }
      ],
      "role": "symbol",
      "title": "NSUncaughtRuntimeErrorException",
      "type": "topic",
      "url": "/documentation/exceptionhandling/nsuncaughtruntimeerrorexception"
    },
    "doc://com.apple.Exception-Handling/documentation/ExceptionHandling/NSUncaughtSystemExceptionException": {
      "abstract": [
        {
          "text": "Identifies an uncaught system exception.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSUncaughtSystemExceptionException"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.Exception-Handling/documentation/ExceptionHandling/NSUncaughtSystemExceptionException",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSUncaughtSystemExceptionException"
        }
      ],
      "role": "symbol",
      "title": "NSUncaughtSystemExceptionException",
      "type": "topic",
      "url": "/documentation/exceptionhandling/nsuncaughtsystemexceptionexception"
    },
    "doc://com.apple.Exception-Handling/documentation/ExceptionHandling/exceptionhandling-enumerations": {
      "abstract": [],
      "identifier": "doc://com.apple.Exception-Handling/documentation/ExceptionHandling/exceptionhandling-enumerations",
      "kind": "article",
      "role": "collectionGroup",
      "title": "ExceptionHandling Enumerations",
      "type": "topic",
      "url": "/documentation/exceptionhandling/exceptionhandling-enumerations"
    },
    "doc://com.apple.Exception-Handling/documentation/ExceptionHandling/exceptionhandling-functions": {
      "abstract": [],
      "identifier": "doc://com.apple.Exception-Handling/documentation/ExceptionHandling/exceptionhandling-functions",
      "kind": "article",
      "role": "collectionGroup",
      "title": "ExceptionHandling Functions",
      "type": "topic",
      "url": "/documentation/exceptionhandling/exceptionhandling-functions"
    },
    "doc://com.apple.documentation/documentation/ExceptionHandling/nsexceptionhandlerdelegate#Logging-and-handling-exceptions": {
      "abstract": [
        {
          "text": "The `NSExceptionHandlerDelegate` informal protocol describes methods that [`NSExceptionHandler`](doc://com.apple.Exception-Handling/documentation/ExceptionHandling/NSExceptionHandler) objects call on their delegates when exceptions occur. An [`NSExceptionHandler`](doc://com.apple.Exception-Handling/documentation/ExceptionHandling/NSExceptionHandler) object does not need to have a delegate. When one does, these delegate methods are asked to approve exception handling and logging for each monitored [`NSExceptionHandler`](doc://com.apple.Exception-Handling/documentation/ExceptionHandling/NSExceptionHandler) object.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/ExceptionHandling/nsexceptionhandlerdelegate#Logging-and-handling-exceptions",
      "kind": "article",
      "role": "article",
      "title": "NSExceptionHandlerDelegate",
      "type": "topic",
      "url": "/documentation/ExceptionHandling/nsexceptionhandlerdelegate"
    },
    "doc://com.apple.documentation/documentation/foundation/nsexception": {
      "abstract": [
        {
          "text": "An object that represents a special condition that interrupts the normal flow of program execution.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "class "
        },
        {
          "kind": "identifier",
          "text": "NSException"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/foundation/nsexception",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSException",
      "type": "topic",
      "url": "/documentation/foundation/nsexception"
    },
    "doc://com.apple.documentation/documentation/foundation/nsexception/1418149-userinfo": {
      "abstract": [
        {
          "text": "A dictionary containing application-specific data pertaining to the receiver.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "var "
        },
        {
          "kind": "identifier",
          "text": "userInfo"
        },
        {
          "kind": "text",
          "text": ": [AnyHashable : Any]?"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/foundation/nsexception/1418149-userinfo",
      "kind": "symbol",
      "role": "symbol",
      "title": "userInfo",
      "type": "topic",
      "url": "/documentation/foundation/nsexception/1418149-userinfo"
    },
    "doc://com.apple.documentation/documentation/foundation/nsstring": {
      "abstract": [
        {
          "text": "A static, plain-text Unicode string object which you use when you need reference semantics or other Foundation-specific behavior. ",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "class "
        },
        {
          "kind": "identifier",
          "text": "NSString"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/foundation/nsstring",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSString",
      "type": "topic",
      "url": "/documentation/foundation/nsstring"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Reference",
      "generated": true,
      "identifiers": [
        "doc://com.apple.Exception-Handling/documentation/ExceptionHandling/exceptionhandling-enumerations",
        "doc://com.apple.Exception-Handling/documentation/ExceptionHandling/exceptionhandling-functions"
      ],
      "title": "Reference"
    }
  ],
  "topicSections": [
    {
      "anchor": "Constants",
      "identifiers": [
        "doc://com.apple.Exception-Handling/documentation/ExceptionHandling/NSStackTraceKey",
        "doc://com.apple.Exception-Handling/documentation/ExceptionHandling/NSUncaughtRuntimeErrorException",
        "doc://com.apple.Exception-Handling/documentation/ExceptionHandling/NSUncaughtSystemExceptionException"
      ],
      "title": "Constants"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Constants",
              "identifiers": [
                "doc://com.apple.Exception-Handling/documentation/ExceptionHandling/NSStackTraceKey",
                "doc://com.apple.Exception-Handling/documentation/ExceptionHandling/NSUncaughtRuntimeErrorException",
                "doc://com.apple.Exception-Handling/documentation/ExceptionHandling/NSUncaughtSystemExceptionException"
              ],
              "title": "Constants"
            },
            {
              "anchor": "Macros",
              "identifiers": [
                "doc://com.apple.Exception-Handling/documentation/ExceptionHandling/EXCEPTIONHANDLING_EXPORT",
                "doc://com.apple.Exception-Handling/documentation/ExceptionHandling/EXCEPTIONHANDLING_IMPORT"
              ],
              "title": "Macros"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Reference",
              "generated": true,
              "identifiers": [
                "doc://com.apple.Exception-Handling/documentation/ExceptionHandling/exceptionhandling-enumerations",
                "doc://com.apple.Exception-Handling/documentation/ExceptionHandling/exceptionhandling-functions"
              ],
              "title": "Reference"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.Exception-Handling~1documentation~1ExceptionHandling~1NSUncaughtSystemExceptionException/title",
          "value": "NSUncaughtSystemExceptionException"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.Exception-Handling~1documentation~1ExceptionHandling~1NSUncaughtSystemExceptionException/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSUncaughtSystemExceptionException"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.Exception-Handling~1documentation~1ExceptionHandling~1NSStackTraceKey/title",
          "value": "NSStackTraceKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.Exception-Handling~1documentation~1ExceptionHandling~1NSStackTraceKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSStackTraceKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1foundation~1nsstring/abstract",
          "value": [
            {
              "text": "A static, plain-text Unicode string object.",
              "type": "text"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.Exception-Handling~1documentation~1ExceptionHandling~1NSUncaughtRuntimeErrorException/title",
          "value": "NSUncaughtRuntimeErrorException"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.Exception-Handling~1documentation~1ExceptionHandling~1NSUncaughtRuntimeErrorException/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSUncaughtRuntimeErrorException"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/exceptionhandling/exceptionhandling-constants"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/exceptionhandling/exceptionhandling-constants"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
