{
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.Exception-Handling/documentation/ExceptionHandling"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.Exception-Handling/documentation/ExceptionHandling/exceptionhandling-functions"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "Exception Handling"
      }
    ],
    "role": "collectionGroup",
    "roleHeading": "API Collection",
    "title": "ExceptionHandling Functions"
  },
  "references": {
    "doc://com.apple.Exception-Handling/documentation/ExceptionHandling": {
      "abstract": [
        {
          "text": "Monitor and debug exceptional conditions in code.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.Exception-Handling/documentation/ExceptionHandling",
      "kind": "symbol",
      "role": "collection",
      "title": "Exception Handling",
      "type": "topic",
      "url": "/documentation/exceptionhandling"
    },
    "doc://com.apple.Exception-Handling/documentation/ExceptionHandling/NSExceptionHandlerResume()": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSExceptionHandlerResume"
        },
        {
          "kind": "text",
          "text": "()"
        }
      ],
      "identifier": "doc://com.apple.Exception-Handling/documentation/ExceptionHandling/NSExceptionHandlerResume()",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSExceptionHandlerResume"
        }
      ],
      "role": "symbol",
      "title": "NSExceptionHandlerResume()",
      "type": "topic",
      "url": "/documentation/exceptionhandling/nsexceptionhandlerresume()"
    },
    "doc://com.apple.Exception-Handling/documentation/ExceptionHandling/exceptionhandling-constants": {
      "abstract": [],
      "identifier": "doc://com.apple.Exception-Handling/documentation/ExceptionHandling/exceptionhandling-constants",
      "kind": "article",
      "role": "collectionGroup",
      "title": "ExceptionHandling Constants",
      "type": "topic",
      "url": "/documentation/exceptionhandling/exceptionhandling-constants"
    },
    "doc://com.apple.Exception-Handling/documentation/ExceptionHandling/exceptionhandling-enumerations": {
      "abstract": [],
      "identifier": "doc://com.apple.Exception-Handling/documentation/ExceptionHandling/exceptionhandling-enumerations",
      "kind": "article",
      "role": "collectionGroup",
      "title": "ExceptionHandling Enumerations",
      "type": "topic",
      "url": "/documentation/exceptionhandling/exceptionhandling-enumerations"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Reference",
      "generated": true,
      "identifiers": [
        "doc://com.apple.Exception-Handling/documentation/ExceptionHandling/exceptionhandling-enumerations",
        "doc://com.apple.Exception-Handling/documentation/ExceptionHandling/exceptionhandling-constants"
      ],
      "title": "Reference"
    }
  ],
  "topicSections": [
    {
      "anchor": "Functions",
      "identifiers": [
        "doc://com.apple.Exception-Handling/documentation/ExceptionHandling/NSExceptionHandlerResume()"
      ],
      "title": "Functions"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Functions",
              "identifiers": [
                "doc://com.apple.Exception-Handling/documentation/ExceptionHandling/NSExceptionHandlerResume()"
              ],
              "title": "Functions"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Reference",
              "generated": true,
              "identifiers": [
                "doc://com.apple.Exception-Handling/documentation/ExceptionHandling/exceptionhandling-enumerations",
                "doc://com.apple.Exception-Handling/documentation/ExceptionHandling/exceptionhandling-constants"
              ],
              "title": "Reference"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.Exception-Handling~1documentation~1ExceptionHandling~1NSExceptionHandlerResume()/title",
          "value": "NSExceptionHandlerResume"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.Exception-Handling~1documentation~1ExceptionHandling~1NSExceptionHandlerResume()/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSExceptionHandlerResume"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/exceptionhandling/exceptionhandling-functions"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/exceptionhandling/exceptionhandling-functions"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
