{
  "abstract": [
    {
      "text": "Two of the following global string constants identify exceptions generated by the",
      "type": "text"
    },
    {
      "text": " ",
      "type": "text"
    },
    {
      "text": "framework for Objective-C runtime errors and system exceptions such as invalid memory",
      "type": "text"
    },
    {
      "text": " ",
      "type": "text"
    },
    {
      "text": "accesses. The other constant is used as a key to access the stack trace in the ",
      "type": "text"
    },
    {
      "identifier": "doc://com.apple.documentation/documentation/foundation/nsexception/1418149-userinfo",
      "isActive": true,
      "type": "reference"
    },
    {
      "text": " ",
      "type": "text"
    },
    {
      "text": "dictionary of an ",
      "type": "text"
    },
    {
      "identifier": "doc://com.apple.documentation/documentation/foundation/nsexception",
      "isActive": true,
      "type": "reference"
    },
    {
      "text": " ",
      "type": "text"
    },
    {
      "text": "object, when requested.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.Exception-Handling/documentation/ExceptionHandling",
        "doc://com.apple.Exception-Handling/documentation/ExceptionHandling/NSExceptionHandler"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.Exception-Handling/documentation/ExceptionHandling/exception-global-string-constants"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "Exception Handling"
      }
    ],
    "role": "collectionGroup",
    "roleHeading": "API Collection",
    "title": "Exception Global String Constants"
  },
  "references": {
    "doc://com.apple.Exception-Handling/documentation/ExceptionHandling": {
      "abstract": [
        {
          "text": "Monitor and debug exceptional conditions in code.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.Exception-Handling/documentation/ExceptionHandling",
      "kind": "symbol",
      "role": "collection",
      "title": "Exception Handling",
      "type": "topic",
      "url": "/documentation/exceptionhandling"
    },
    "doc://com.apple.Exception-Handling/documentation/ExceptionHandling/NSExceptionHandler": {
      "abstract": [
        {
          "text": "The ",
          "type": "text"
        },
        {
          "code": "NSExceptionHandler",
          "type": "codeVoice"
        },
        {
          "text": " class provides facilities for monitoring and debugging exceptional",
          "type": "text"
        },
        {
          "text": " ",
          "type": "text"
        },
        {
          "text": "conditions in Objective-C programs. It works by installing a special uncaught exception",
          "type": "text"
        },
        {
          "text": " ",
          "type": "text"
        },
        {
          "text": "handler via the  ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.documentation/documentation/foundation/1409609-nssetuncaughtexceptionhandler",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " ",
          "type": "text"
        },
        {
          "text": "function. Consequently, to use the services of ",
          "type": "text"
        },
        {
          "code": "NSExceptionHandler",
          "type": "codeVoice"
        },
        {
          "text": ", you must not",
          "type": "text"
        },
        {
          "text": " ",
          "type": "text"
        },
        {
          "text": "install your own custom uncaught exception handler.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSExceptionHandler"
        }
      ],
      "identifier": "doc://com.apple.Exception-Handling/documentation/ExceptionHandling/NSExceptionHandler",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSExceptionHandler"
        }
      ],
      "role": "symbol",
      "title": "NSExceptionHandler",
      "type": "topic",
      "url": "/documentation/exceptionhandling/nsexceptionhandler"
    },
    "doc://com.apple.Exception-Handling/documentation/ExceptionHandling/NSExceptionHandler/setExceptionHandlingMask(_:)": {
      "abstract": [
        {
          "text": "Sets the bit mask of constants specifying the types of exceptions monitored by the",
          "type": "text"
        },
        {
          "text": " ",
          "type": "text"
        },
        {
          "text": "receiver and its handling and logging behavior.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "setExceptionHandlingMask"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.Exception-Handling/documentation/ExceptionHandling/NSExceptionHandler/setExceptionHandlingMask(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "setExceptionHandlingMask:"
        }
      ],
      "role": "symbol",
      "title": "setExceptionHandlingMask(_:)",
      "type": "topic",
      "url": "/documentation/exceptionhandling/nsexceptionhandler/setexceptionhandlingmask(_:)"
    },
    "doc://com.apple.Exception-Handling/documentation/ExceptionHandling/NSExceptionHandler/setExceptionHangingMask(_:)": {
      "abstract": [
        {
          "text": "Sets the bit mask of constants specifying the types of exceptions that will halt",
          "type": "text"
        },
        {
          "text": " ",
          "type": "text"
        },
        {
          "text": "execution for debugging.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "setExceptionHangingMask"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.Exception-Handling/documentation/ExceptionHandling/NSExceptionHandler/setExceptionHangingMask(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "setExceptionHangingMask:"
        }
      ],
      "role": "symbol",
      "title": "setExceptionHangingMask(_:)",
      "type": "topic",
      "url": "/documentation/exceptionhandling/nsexceptionhandler/setexceptionhangingmask(_:)"
    },
    "doc://com.apple.Exception-Handling/documentation/ExceptionHandling/NSStackTraceKey": {
      "abstract": [
        {
          "text": "The key for fetching the stack trace (an ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.documentation/documentation/foundation/nsstring",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " ",
          "type": "text"
        },
        {
          "text": "object) in the ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.documentation/documentation/foundation/nsexception/1418149-userinfo",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " ",
          "type": "text"
        },
        {
          "text": "dictionary of the ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.documentation/documentation/foundation/nsexception",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " ",
          "type": "text"
        },
        {
          "text": "object passed into one of the delegate methods described in ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.documentation/documentation/ExceptionHandling/nsexceptionhandlerdelegate#Logging-and-handling-exceptions",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": ".",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSStackTraceKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.Exception-Handling/documentation/ExceptionHandling/NSStackTraceKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSStackTraceKey"
        }
      ],
      "role": "symbol",
      "title": "NSStackTraceKey",
      "type": "topic",
      "url": "/documentation/exceptionhandling/nsstacktracekey"
    },
    "doc://com.apple.Exception-Handling/documentation/ExceptionHandling/NSUncaughtRuntimeErrorException": {
      "abstract": [
        {
          "text": "Identifies an Objective-C runtime error.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSUncaughtRuntimeErrorException"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.Exception-Handling/documentation/ExceptionHandling/NSUncaughtRuntimeErrorException",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSUncaughtRuntimeErrorException"
        }
      ],
      "role": "symbol",
      "title": "NSUncaughtRuntimeErrorException",
      "type": "topic",
      "url": "/documentation/exceptionhandling/nsuncaughtruntimeerrorexception"
    },
    "doc://com.apple.Exception-Handling/documentation/ExceptionHandling/NSUncaughtSystemExceptionException": {
      "abstract": [
        {
          "text": "Identifies an uncaught system exception.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSUncaughtSystemExceptionException"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.Exception-Handling/documentation/ExceptionHandling/NSUncaughtSystemExceptionException",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSUncaughtSystemExceptionException"
        }
      ],
      "role": "symbol",
      "title": "NSUncaughtSystemExceptionException",
      "type": "topic",
      "url": "/documentation/exceptionhandling/nsuncaughtsystemexceptionexception"
    },
    "doc://com.apple.Exception-Handling/documentation/ExceptionHandling/logging-and-handling-constants": {
      "abstract": [
        {
          "text": "Use one or more of the following constants in the parameter of ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.Exception-Handling/documentation/ExceptionHandling/NSExceptionHandler/setExceptionHandlingMask(_:)",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " ",
          "type": "text"
        },
        {
          "text": "to specify the types of exceptions that the exception handler should monitor and",
          "type": "text"
        },
        {
          "text": " ",
          "type": "text"
        },
        {
          "text": "whether it should handle or log them.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.Exception-Handling/documentation/ExceptionHandling/logging-and-handling-constants",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Logging and Handling Constants",
      "type": "topic",
      "url": "/documentation/exceptionhandling/logging-and-handling-constants"
    },
    "doc://com.apple.Exception-Handling/documentation/ExceptionHandling/mask-definitions": {
      "abstract": [
        {
          "text": "The following ",
          "type": "text"
        },
        {
          "code": "#define",
          "type": "codeVoice"
        },
        {
          "text": " constants are conveniences for specifying complete sets of",
          "type": "text"
        },
        {
          "text": " ",
          "type": "text"
        },
        {
          "text": "exception-handling ",
          "type": "text"
        },
        {
          "code": "enum",
          "type": "codeVoice"
        },
        {
          "text": " constants.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.Exception-Handling/documentation/ExceptionHandling/mask-definitions",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Mask Definitions",
      "type": "topic",
      "url": "/documentation/exceptionhandling/mask-definitions"
    },
    "doc://com.apple.Exception-Handling/documentation/ExceptionHandling/system-hang-constants": {
      "abstract": [
        {
          "text": "Use one or more of the following constants in the parameter of ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.Exception-Handling/documentation/ExceptionHandling/NSExceptionHandler/setExceptionHangingMask(_:)",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " ",
          "type": "text"
        },
        {
          "text": "to specify the types of exceptions that cause the exception to halt execution so",
          "type": "text"
        },
        {
          "text": " ",
          "type": "text"
        },
        {
          "text": "a debugger can be attached.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.Exception-Handling/documentation/ExceptionHandling/system-hang-constants",
      "kind": "article",
      "role": "collectionGroup",
      "title": "System Hang Constants",
      "type": "topic",
      "url": "/documentation/exceptionhandling/system-hang-constants"
    },
    "doc://com.apple.documentation/documentation/ExceptionHandling/nsexceptionhandlerdelegate#Logging-and-handling-exceptions": {
      "abstract": [
        {
          "text": "The `NSExceptionHandlerDelegate` informal protocol describes methods that [`NSExceptionHandler`](doc://com.apple.Exception-Handling/documentation/ExceptionHandling/NSExceptionHandler) objects call on their delegates when exceptions occur. An [`NSExceptionHandler`](doc://com.apple.Exception-Handling/documentation/ExceptionHandling/NSExceptionHandler) object does not need to have a delegate. When one does, these delegate methods are asked to approve exception handling and logging for each monitored [`NSExceptionHandler`](doc://com.apple.Exception-Handling/documentation/ExceptionHandling/NSExceptionHandler) object.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/ExceptionHandling/nsexceptionhandlerdelegate#Logging-and-handling-exceptions",
      "kind": "article",
      "role": "article",
      "title": "NSExceptionHandlerDelegate",
      "type": "topic",
      "url": "/documentation/ExceptionHandling/nsexceptionhandlerdelegate"
    },
    "doc://com.apple.documentation/documentation/foundation/1409609-nssetuncaughtexceptionhandler": {
      "abstract": [
        {
          "text": "Changes the top-level error handler.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "func "
        },
        {
          "kind": "identifier",
          "text": "NSSetUncaughtExceptionHandler"
        },
        {
          "kind": "text",
          "text": "(((NSException) -> Void)?)"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/foundation/1409609-nssetuncaughtexceptionhandler",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSSetUncaughtExceptionHandler(_:)",
      "type": "topic",
      "url": "/documentation/foundation/1409609-nssetuncaughtexceptionhandler"
    },
    "doc://com.apple.documentation/documentation/foundation/nsexception": {
      "abstract": [
        {
          "text": "An object that represents a special condition that interrupts the normal flow of program execution.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "class "
        },
        {
          "kind": "identifier",
          "text": "NSException"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/foundation/nsexception",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSException",
      "type": "topic",
      "url": "/documentation/foundation/nsexception"
    },
    "doc://com.apple.documentation/documentation/foundation/nsexception/1418149-userinfo": {
      "abstract": [
        {
          "text": "A dictionary containing application-specific data pertaining to the receiver.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "var "
        },
        {
          "kind": "identifier",
          "text": "userInfo"
        },
        {
          "kind": "text",
          "text": ": [AnyHashable : Any]?"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/foundation/nsexception/1418149-userinfo",
      "kind": "symbol",
      "role": "symbol",
      "title": "userInfo",
      "type": "topic",
      "url": "/documentation/foundation/nsexception/1418149-userinfo"
    },
    "doc://com.apple.documentation/documentation/foundation/nsstring": {
      "abstract": [
        {
          "text": "A static, plain-text Unicode string object which you use when you need reference semantics or other Foundation-specific behavior. ",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "class "
        },
        {
          "kind": "identifier",
          "text": "NSString"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/foundation/nsstring",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSString",
      "type": "topic",
      "url": "/documentation/foundation/nsstring"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Constants",
      "generated": true,
      "identifiers": [
        "doc://com.apple.Exception-Handling/documentation/ExceptionHandling/logging-and-handling-constants",
        "doc://com.apple.Exception-Handling/documentation/ExceptionHandling/system-hang-constants"
      ],
      "title": "Constants"
    }
  ],
  "topicSections": [
    {
      "anchor": "Constants",
      "identifiers": [
        "doc://com.apple.Exception-Handling/documentation/ExceptionHandling/NSUncaughtSystemExceptionException",
        "doc://com.apple.Exception-Handling/documentation/ExceptionHandling/NSUncaughtRuntimeErrorException",
        "doc://com.apple.Exception-Handling/documentation/ExceptionHandling/NSStackTraceKey"
      ],
      "title": "Constants"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Constants",
              "identifiers": [
                "doc://com.apple.Exception-Handling/documentation/ExceptionHandling/NSUncaughtSystemExceptionException",
                "doc://com.apple.Exception-Handling/documentation/ExceptionHandling/NSUncaughtRuntimeErrorException",
                "doc://com.apple.Exception-Handling/documentation/ExceptionHandling/NSStackTraceKey"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Constants",
              "generated": true,
              "identifiers": [
                "doc://com.apple.Exception-Handling/documentation/ExceptionHandling/logging-and-handling-constants",
                "doc://com.apple.Exception-Handling/documentation/ExceptionHandling/system-hang-constants",
                "doc://com.apple.Exception-Handling/documentation/ExceptionHandling/mask-definitions"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1foundation~11409609-nssetuncaughtexceptionhandler/title",
          "value": "NSSetUncaughtExceptionHandler"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.Exception-Handling~1documentation~1ExceptionHandling~1NSUncaughtSystemExceptionException/title",
          "value": "NSUncaughtSystemExceptionException"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.Exception-Handling~1documentation~1ExceptionHandling~1NSUncaughtSystemExceptionException/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSUncaughtSystemExceptionException"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.Exception-Handling~1documentation~1ExceptionHandling~1NSExceptionHandler~1setExceptionHandlingMask(_:)/title",
          "value": "setExceptionHandlingMask:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.Exception-Handling~1documentation~1ExceptionHandling~1NSExceptionHandler~1setExceptionHandlingMask(_:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "setExceptionHandlingMask:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.Exception-Handling~1documentation~1ExceptionHandling~1NSStackTraceKey/title",
          "value": "NSStackTraceKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.Exception-Handling~1documentation~1ExceptionHandling~1NSStackTraceKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSStackTraceKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.Exception-Handling~1documentation~1ExceptionHandling~1NSExceptionHandler/title",
          "value": "NSExceptionHandler"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.Exception-Handling~1documentation~1ExceptionHandling~1NSExceptionHandler/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSExceptionHandler"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.Exception-Handling~1documentation~1ExceptionHandling~1NSExceptionHandler/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSExceptionHandler"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.Exception-Handling~1documentation~1ExceptionHandling~1NSExceptionHandler~1setExceptionHangingMask(_:)/title",
          "value": "setExceptionHangingMask:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.Exception-Handling~1documentation~1ExceptionHandling~1NSExceptionHandler~1setExceptionHangingMask(_:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "setExceptionHangingMask:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.Exception-Handling~1documentation~1ExceptionHandling~1NSUncaughtRuntimeErrorException/title",
          "value": "NSUncaughtRuntimeErrorException"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.Exception-Handling~1documentation~1ExceptionHandling~1NSUncaughtRuntimeErrorException/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSUncaughtRuntimeErrorException"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1foundation~1nsstring/abstract",
          "value": [
            {
              "text": "A static, plain-text Unicode string object.",
              "type": "text"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/exceptionhandling/exception-global-string-constants"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/exceptionhandling/exception-global-string-constants"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
