{
  "abstract": [
    {
      "text": "Use one or more of the following constants in the parameter of ",
      "type": "text"
    },
    {
      "identifier": "doc://com.apple.Exception-Handling/documentation/ExceptionHandling/NSExceptionHandler/setExceptionHandlingMask(_:)",
      "isActive": true,
      "type": "reference"
    },
    {
      "text": " ",
      "type": "text"
    },
    {
      "text": "to specify the types of exceptions that the exception handler should monitor and",
      "type": "text"
    },
    {
      "text": " ",
      "type": "text"
    },
    {
      "text": "whether it should handle or log them.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.Exception-Handling/documentation/ExceptionHandling",
        "doc://com.apple.Exception-Handling/documentation/ExceptionHandling/NSExceptionHandler"
      ],
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.Exception-Handling/documentation/ExceptionHandling",
        "doc://com.apple.Exception-Handling/documentation/ExceptionHandling/exceptionhandling-enumerations"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.Exception-Handling/documentation/ExceptionHandling/logging-and-handling-constants"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "Exception Handling"
      }
    ],
    "role": "collectionGroup",
    "roleHeading": "API Collection",
    "title": "Logging and Handling Constants"
  },
  "primaryContentSections": [
    {
      "content": [
        {
          "anchor": "Overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "When exception-handling domains are nested, ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.Exception-Handling/documentation/ExceptionHandling/NSLogTopLevelExceptionMask",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "and ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.Exception-Handling/documentation/ExceptionHandling/NSHandleTopLevelExceptionMask",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " deal with exceptions that",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "would make it to the top two levels of exception handlers. In the main thread of",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "a Cocoa application, the top-level handler is the global ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/AppKit/NSApplication",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "instance.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.Exception-Handling/documentation/ExceptionHandling": {
      "abstract": [
        {
          "text": "Monitor and debug exceptional conditions in code.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.Exception-Handling/documentation/ExceptionHandling",
      "kind": "symbol",
      "role": "collection",
      "title": "Exception Handling",
      "type": "topic",
      "url": "/documentation/exceptionhandling"
    },
    "doc://com.apple.Exception-Handling/documentation/ExceptionHandling/NSExceptionHandler": {
      "abstract": [
        {
          "text": "The ",
          "type": "text"
        },
        {
          "code": "NSExceptionHandler",
          "type": "codeVoice"
        },
        {
          "text": " class provides facilities for monitoring and debugging exceptional",
          "type": "text"
        },
        {
          "text": " ",
          "type": "text"
        },
        {
          "text": "conditions in Objective-C programs. It works by installing a special uncaught exception",
          "type": "text"
        },
        {
          "text": " ",
          "type": "text"
        },
        {
          "text": "handler via the  ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.documentation/documentation/foundation/1409609-nssetuncaughtexceptionhandler",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " ",
          "type": "text"
        },
        {
          "text": "function. Consequently, to use the services of ",
          "type": "text"
        },
        {
          "code": "NSExceptionHandler",
          "type": "codeVoice"
        },
        {
          "text": ", you must not",
          "type": "text"
        },
        {
          "text": " ",
          "type": "text"
        },
        {
          "text": "install your own custom uncaught exception handler.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSExceptionHandler"
        }
      ],
      "identifier": "doc://com.apple.Exception-Handling/documentation/ExceptionHandling/NSExceptionHandler",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSExceptionHandler"
        }
      ],
      "role": "symbol",
      "title": "NSExceptionHandler",
      "type": "topic",
      "url": "/documentation/exceptionhandling/nsexceptionhandler"
    },
    "doc://com.apple.Exception-Handling/documentation/ExceptionHandling/NSExceptionHandler/setExceptionHandlingMask(_:)": {
      "abstract": [
        {
          "text": "Sets the bit mask of constants specifying the types of exceptions monitored by the",
          "type": "text"
        },
        {
          "text": " ",
          "type": "text"
        },
        {
          "text": "receiver and its handling and logging behavior.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "setExceptionHandlingMask"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.Exception-Handling/documentation/ExceptionHandling/NSExceptionHandler/setExceptionHandlingMask(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "setExceptionHandlingMask:"
        }
      ],
      "role": "symbol",
      "title": "setExceptionHandlingMask(_:)",
      "type": "topic",
      "url": "/documentation/exceptionhandling/nsexceptionhandler/setexceptionhandlingmask(_:)"
    },
    "doc://com.apple.Exception-Handling/documentation/ExceptionHandling/NSExceptionHandler/setExceptionHangingMask(_:)": {
      "abstract": [
        {
          "text": "Sets the bit mask of constants specifying the types of exceptions that will halt",
          "type": "text"
        },
        {
          "text": " ",
          "type": "text"
        },
        {
          "text": "execution for debugging.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "setExceptionHangingMask"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.Exception-Handling/documentation/ExceptionHandling/NSExceptionHandler/setExceptionHangingMask(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "setExceptionHangingMask:"
        }
      ],
      "role": "symbol",
      "title": "setExceptionHangingMask(_:)",
      "type": "topic",
      "url": "/documentation/exceptionhandling/nsexceptionhandler/setexceptionhangingmask(_:)"
    },
    "doc://com.apple.Exception-Handling/documentation/ExceptionHandling/NSHandleOtherExceptionMask": {
      "abstract": [
        {
          "text": "The exception handler handles exceptions caught by handlers lower than the top-level",
          "type": "text"
        },
        {
          "text": " ",
          "type": "text"
        },
        {
          "text": "handler by converting them to ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.documentation/documentation/foundation/nsexception",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " ",
          "type": "text"
        },
        {
          "text": "objects containing a stack trace.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSHandleOtherExceptionMask"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.Exception-Handling/documentation/ExceptionHandling/NSHandleOtherExceptionMask",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSHandleOtherExceptionMask"
        }
      ],
      "role": "symbol",
      "title": "NSHandleOtherExceptionMask",
      "type": "topic",
      "url": "/documentation/exceptionhandling/nshandleotherexceptionmask"
    },
    "doc://com.apple.Exception-Handling/documentation/ExceptionHandling/NSHandleTopLevelExceptionMask": {
      "abstract": [
        {
          "text": "The exception handler handles exceptions caught by the top-level handler by converting",
          "type": "text"
        },
        {
          "text": " ",
          "type": "text"
        },
        {
          "text": "them to ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.documentation/documentation/foundation/nsexception",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " objects",
          "type": "text"
        },
        {
          "text": " ",
          "type": "text"
        },
        {
          "text": "containing a stack trace.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSHandleTopLevelExceptionMask"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.Exception-Handling/documentation/ExceptionHandling/NSHandleTopLevelExceptionMask",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSHandleTopLevelExceptionMask"
        }
      ],
      "role": "symbol",
      "title": "NSHandleTopLevelExceptionMask",
      "type": "topic",
      "url": "/documentation/exceptionhandling/nshandletoplevelexceptionmask"
    },
    "doc://com.apple.Exception-Handling/documentation/ExceptionHandling/NSHandleUncaughtExceptionMask": {
      "abstract": [
        {
          "text": "The exception handler handles uncaught exceptions by terminating the thread in which",
          "type": "text"
        },
        {
          "text": " ",
          "type": "text"
        },
        {
          "text": "they occur.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSHandleUncaughtExceptionMask"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.Exception-Handling/documentation/ExceptionHandling/NSHandleUncaughtExceptionMask",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSHandleUncaughtExceptionMask"
        }
      ],
      "role": "symbol",
      "title": "NSHandleUncaughtExceptionMask",
      "type": "topic",
      "url": "/documentation/exceptionhandling/nshandleuncaughtexceptionmask"
    },
    "doc://com.apple.Exception-Handling/documentation/ExceptionHandling/NSHandleUncaughtRuntimeErrorMask": {
      "abstract": [
        {
          "text": "The exception handler handles uncaught runtime errors by converting them to ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.documentation/documentation/foundation/nsexception",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " ",
          "type": "text"
        },
        {
          "text": "objects containing a stack trace.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSHandleUncaughtRuntimeErrorMask"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.Exception-Handling/documentation/ExceptionHandling/NSHandleUncaughtRuntimeErrorMask",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSHandleUncaughtRuntimeErrorMask"
        }
      ],
      "role": "symbol",
      "title": "NSHandleUncaughtRuntimeErrorMask",
      "type": "topic",
      "url": "/documentation/exceptionhandling/nshandleuncaughtruntimeerrormask"
    },
    "doc://com.apple.Exception-Handling/documentation/ExceptionHandling/NSHandleUncaughtSystemExceptionMask": {
      "abstract": [
        {
          "text": "The exception handler handles uncaught system exceptions by converting them to ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.documentation/documentation/foundation/nsexception",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " ",
          "type": "text"
        },
        {
          "text": "objects containing a stack trace.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSHandleUncaughtSystemExceptionMask"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.Exception-Handling/documentation/ExceptionHandling/NSHandleUncaughtSystemExceptionMask",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSHandleUncaughtSystemExceptionMask"
        }
      ],
      "role": "symbol",
      "title": "NSHandleUncaughtSystemExceptionMask",
      "type": "topic",
      "url": "/documentation/exceptionhandling/nshandleuncaughtsystemexceptionmask"
    },
    "doc://com.apple.Exception-Handling/documentation/ExceptionHandling/NSLogOtherExceptionMask": {
      "abstract": [
        {
          "text": "The exception handler logs exceptions caught by handlers lower than the top-level",
          "type": "text"
        },
        {
          "text": " ",
          "type": "text"
        },
        {
          "text": "handler.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSLogOtherExceptionMask"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.Exception-Handling/documentation/ExceptionHandling/NSLogOtherExceptionMask",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSLogOtherExceptionMask"
        }
      ],
      "role": "symbol",
      "title": "NSLogOtherExceptionMask",
      "type": "topic",
      "url": "/documentation/exceptionhandling/nslogotherexceptionmask"
    },
    "doc://com.apple.Exception-Handling/documentation/ExceptionHandling/NSLogTopLevelExceptionMask": {
      "abstract": [
        {
          "text": "The exception handler logs exceptions that would be caught by the top-level handler.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSLogTopLevelExceptionMask"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.Exception-Handling/documentation/ExceptionHandling/NSLogTopLevelExceptionMask",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSLogTopLevelExceptionMask"
        }
      ],
      "role": "symbol",
      "title": "NSLogTopLevelExceptionMask",
      "type": "topic",
      "url": "/documentation/exceptionhandling/nslogtoplevelexceptionmask"
    },
    "doc://com.apple.Exception-Handling/documentation/ExceptionHandling/NSLogUncaughtExceptionMask": {
      "abstract": [
        {
          "text": "The exception handler logs uncaught exceptions.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSLogUncaughtExceptionMask"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.Exception-Handling/documentation/ExceptionHandling/NSLogUncaughtExceptionMask",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSLogUncaughtExceptionMask"
        }
      ],
      "role": "symbol",
      "title": "NSLogUncaughtExceptionMask",
      "type": "topic",
      "url": "/documentation/exceptionhandling/nsloguncaughtexceptionmask"
    },
    "doc://com.apple.Exception-Handling/documentation/ExceptionHandling/NSLogUncaughtRuntimeErrorMask": {
      "abstract": [
        {
          "text": "The exception handler logs uncaught runtime errors.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSLogUncaughtRuntimeErrorMask"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.Exception-Handling/documentation/ExceptionHandling/NSLogUncaughtRuntimeErrorMask",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSLogUncaughtRuntimeErrorMask"
        }
      ],
      "role": "symbol",
      "title": "NSLogUncaughtRuntimeErrorMask",
      "type": "topic",
      "url": "/documentation/exceptionhandling/nsloguncaughtruntimeerrormask"
    },
    "doc://com.apple.Exception-Handling/documentation/ExceptionHandling/NSLogUncaughtSystemExceptionMask": {
      "abstract": [
        {
          "text": "The exception handler logs uncaught system exceptions.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSLogUncaughtSystemExceptionMask"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.Exception-Handling/documentation/ExceptionHandling/NSLogUncaughtSystemExceptionMask",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSLogUncaughtSystemExceptionMask"
        }
      ],
      "role": "symbol",
      "title": "NSLogUncaughtSystemExceptionMask",
      "type": "topic",
      "url": "/documentation/exceptionhandling/nsloguncaughtsystemexceptionmask"
    },
    "doc://com.apple.Exception-Handling/documentation/ExceptionHandling/exception-global-string-constants": {
      "abstract": [
        {
          "text": "Two of the following global string constants identify exceptions generated by the",
          "type": "text"
        },
        {
          "text": " ",
          "type": "text"
        },
        {
          "text": "framework for Objective-C runtime errors and system exceptions such as invalid memory",
          "type": "text"
        },
        {
          "text": " ",
          "type": "text"
        },
        {
          "text": "accesses. The other constant is used as a key to access the stack trace in the ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.documentation/documentation/foundation/nsexception/1418149-userinfo",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " ",
          "type": "text"
        },
        {
          "text": "dictionary of an ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.documentation/documentation/foundation/nsexception",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " ",
          "type": "text"
        },
        {
          "text": "object, when requested.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.Exception-Handling/documentation/ExceptionHandling/exception-global-string-constants",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Exception Global String Constants",
      "type": "topic",
      "url": "/documentation/exceptionhandling/exception-global-string-constants"
    },
    "doc://com.apple.Exception-Handling/documentation/ExceptionHandling/exceptionhandling-enumerations": {
      "abstract": [],
      "identifier": "doc://com.apple.Exception-Handling/documentation/ExceptionHandling/exceptionhandling-enumerations",
      "kind": "article",
      "role": "collectionGroup",
      "title": "ExceptionHandling Enumerations",
      "type": "topic",
      "url": "/documentation/exceptionhandling/exceptionhandling-enumerations"
    },
    "doc://com.apple.Exception-Handling/documentation/ExceptionHandling/mask-definitions": {
      "abstract": [
        {
          "text": "The following ",
          "type": "text"
        },
        {
          "code": "#define",
          "type": "codeVoice"
        },
        {
          "text": " constants are conveniences for specifying complete sets of",
          "type": "text"
        },
        {
          "text": " ",
          "type": "text"
        },
        {
          "text": "exception-handling ",
          "type": "text"
        },
        {
          "code": "enum",
          "type": "codeVoice"
        },
        {
          "text": " constants.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.Exception-Handling/documentation/ExceptionHandling/mask-definitions",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Mask Definitions",
      "type": "topic",
      "url": "/documentation/exceptionhandling/mask-definitions"
    },
    "doc://com.apple.Exception-Handling/documentation/ExceptionHandling/system-hang-constants": {
      "abstract": [
        {
          "text": "Use one or more of the following constants in the parameter of ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.Exception-Handling/documentation/ExceptionHandling/NSExceptionHandler/setExceptionHangingMask(_:)",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " ",
          "type": "text"
        },
        {
          "text": "to specify the types of exceptions that cause the exception to halt execution so",
          "type": "text"
        },
        {
          "text": " ",
          "type": "text"
        },
        {
          "text": "a debugger can be attached.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.Exception-Handling/documentation/ExceptionHandling/system-hang-constants",
      "kind": "article",
      "role": "collectionGroup",
      "title": "System Hang Constants",
      "type": "topic",
      "url": "/documentation/exceptionhandling/system-hang-constants"
    },
    "doc://com.apple.documentation/documentation/AppKit/NSApplication": {
      "abstract": [
        {
          "text": "An object that manages an app’s main event loop and resources used by all of that app’s objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@"
        },
        {
          "kind": "attribute",
          "preciseIdentifier": "s:ScM",
          "text": "MainActor"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSApplication"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/AppKit/NSApplication",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSApplication",
      "type": "topic",
      "url": "/documentation/AppKit/NSApplication"
    },
    "doc://com.apple.documentation/documentation/foundation/1409609-nssetuncaughtexceptionhandler": {
      "abstract": [
        {
          "text": "Changes the top-level error handler.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "func "
        },
        {
          "kind": "identifier",
          "text": "NSSetUncaughtExceptionHandler"
        },
        {
          "kind": "text",
          "text": "(((NSException) -> Void)?)"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/foundation/1409609-nssetuncaughtexceptionhandler",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSSetUncaughtExceptionHandler(_:)",
      "type": "topic",
      "url": "/documentation/foundation/1409609-nssetuncaughtexceptionhandler"
    },
    "doc://com.apple.documentation/documentation/foundation/nsexception": {
      "abstract": [
        {
          "text": "An object that represents a special condition that interrupts the normal flow of program execution.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "class "
        },
        {
          "kind": "identifier",
          "text": "NSException"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/foundation/nsexception",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSException",
      "type": "topic",
      "url": "/documentation/foundation/nsexception"
    },
    "doc://com.apple.documentation/documentation/foundation/nsexception/1418149-userinfo": {
      "abstract": [
        {
          "text": "A dictionary containing application-specific data pertaining to the receiver.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "var "
        },
        {
          "kind": "identifier",
          "text": "userInfo"
        },
        {
          "kind": "text",
          "text": ": [AnyHashable : Any]?"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/foundation/nsexception/1418149-userinfo",
      "kind": "symbol",
      "role": "symbol",
      "title": "userInfo",
      "type": "topic",
      "url": "/documentation/foundation/nsexception/1418149-userinfo"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Constants",
      "generated": true,
      "identifiers": [
        "doc://com.apple.Exception-Handling/documentation/ExceptionHandling/system-hang-constants",
        "doc://com.apple.Exception-Handling/documentation/ExceptionHandling/exception-global-string-constants"
      ],
      "title": "Constants"
    }
  ],
  "topicSections": [
    {
      "anchor": "Constants",
      "identifiers": [
        "doc://com.apple.Exception-Handling/documentation/ExceptionHandling/NSLogUncaughtExceptionMask",
        "doc://com.apple.Exception-Handling/documentation/ExceptionHandling/NSHandleUncaughtExceptionMask",
        "doc://com.apple.Exception-Handling/documentation/ExceptionHandling/NSLogUncaughtSystemExceptionMask",
        "doc://com.apple.Exception-Handling/documentation/ExceptionHandling/NSHandleUncaughtSystemExceptionMask",
        "doc://com.apple.Exception-Handling/documentation/ExceptionHandling/NSLogUncaughtRuntimeErrorMask",
        "doc://com.apple.Exception-Handling/documentation/ExceptionHandling/NSHandleUncaughtRuntimeErrorMask",
        "doc://com.apple.Exception-Handling/documentation/ExceptionHandling/NSLogTopLevelExceptionMask",
        "doc://com.apple.Exception-Handling/documentation/ExceptionHandling/NSHandleTopLevelExceptionMask",
        "doc://com.apple.Exception-Handling/documentation/ExceptionHandling/NSLogOtherExceptionMask",
        "doc://com.apple.Exception-Handling/documentation/ExceptionHandling/NSHandleOtherExceptionMask"
      ],
      "title": "Constants"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Constants",
              "identifiers": [
                "doc://com.apple.Exception-Handling/documentation/ExceptionHandling/NSLogUncaughtExceptionMask",
                "doc://com.apple.Exception-Handling/documentation/ExceptionHandling/NSHandleUncaughtExceptionMask",
                "doc://com.apple.Exception-Handling/documentation/ExceptionHandling/NSLogUncaughtSystemExceptionMask",
                "doc://com.apple.Exception-Handling/documentation/ExceptionHandling/NSHandleUncaughtSystemExceptionMask",
                "doc://com.apple.Exception-Handling/documentation/ExceptionHandling/NSLogUncaughtRuntimeErrorMask",
                "doc://com.apple.Exception-Handling/documentation/ExceptionHandling/NSHandleUncaughtRuntimeErrorMask",
                "doc://com.apple.Exception-Handling/documentation/ExceptionHandling/NSLogTopLevelExceptionMask",
                "doc://com.apple.Exception-Handling/documentation/ExceptionHandling/NSHandleTopLevelExceptionMask",
                "doc://com.apple.Exception-Handling/documentation/ExceptionHandling/NSLogOtherExceptionMask",
                "doc://com.apple.Exception-Handling/documentation/ExceptionHandling/NSHandleOtherExceptionMask"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Constants",
              "generated": true,
              "identifiers": [
                "doc://com.apple.Exception-Handling/documentation/ExceptionHandling/system-hang-constants",
                "doc://com.apple.Exception-Handling/documentation/ExceptionHandling/mask-definitions",
                "doc://com.apple.Exception-Handling/documentation/ExceptionHandling/exception-global-string-constants"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.Exception-Handling~1documentation~1ExceptionHandling~1NSExceptionHandler/title",
          "value": "NSExceptionHandler"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.Exception-Handling~1documentation~1ExceptionHandling~1NSExceptionHandler/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSExceptionHandler"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.Exception-Handling~1documentation~1ExceptionHandling~1NSExceptionHandler/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSExceptionHandler"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.Exception-Handling~1documentation~1ExceptionHandling~1NSHandleTopLevelExceptionMask/title",
          "value": "NSHandleTopLevelExceptionMask"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.Exception-Handling~1documentation~1ExceptionHandling~1NSHandleTopLevelExceptionMask/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSHandleTopLevelExceptionMask"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.Exception-Handling~1documentation~1ExceptionHandling~1NSLogUncaughtExceptionMask/title",
          "value": "NSLogUncaughtExceptionMask"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.Exception-Handling~1documentation~1ExceptionHandling~1NSLogUncaughtExceptionMask/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSLogUncaughtExceptionMask"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.Exception-Handling~1documentation~1ExceptionHandling~1NSLogUncaughtSystemExceptionMask/title",
          "value": "NSLogUncaughtSystemExceptionMask"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.Exception-Handling~1documentation~1ExceptionHandling~1NSLogUncaughtSystemExceptionMask/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSLogUncaughtSystemExceptionMask"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.Exception-Handling~1documentation~1ExceptionHandling~1NSExceptionHandler~1setExceptionHandlingMask(_:)/title",
          "value": "setExceptionHandlingMask:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.Exception-Handling~1documentation~1ExceptionHandling~1NSExceptionHandler~1setExceptionHandlingMask(_:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "setExceptionHandlingMask:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1AppKit~1NSApplication/fragments",
          "value": [
            {
              "kind": "keyword",
              "text": "@interface"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "NSApplication"
            },
            {
              "kind": "text",
              "text": " : "
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)NSResponder",
              "text": "NSResponder"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.Exception-Handling~1documentation~1ExceptionHandling~1NSLogOtherExceptionMask/title",
          "value": "NSLogOtherExceptionMask"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.Exception-Handling~1documentation~1ExceptionHandling~1NSLogOtherExceptionMask/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSLogOtherExceptionMask"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.Exception-Handling~1documentation~1ExceptionHandling~1NSHandleUncaughtExceptionMask/title",
          "value": "NSHandleUncaughtExceptionMask"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.Exception-Handling~1documentation~1ExceptionHandling~1NSHandleUncaughtExceptionMask/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSHandleUncaughtExceptionMask"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.Exception-Handling~1documentation~1ExceptionHandling~1NSLogUncaughtRuntimeErrorMask/title",
          "value": "NSLogUncaughtRuntimeErrorMask"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.Exception-Handling~1documentation~1ExceptionHandling~1NSLogUncaughtRuntimeErrorMask/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSLogUncaughtRuntimeErrorMask"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.Exception-Handling~1documentation~1ExceptionHandling~1NSHandleOtherExceptionMask/title",
          "value": "NSHandleOtherExceptionMask"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.Exception-Handling~1documentation~1ExceptionHandling~1NSHandleOtherExceptionMask/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSHandleOtherExceptionMask"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1foundation~11409609-nssetuncaughtexceptionhandler/title",
          "value": "NSSetUncaughtExceptionHandler"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.Exception-Handling~1documentation~1ExceptionHandling~1NSLogTopLevelExceptionMask/title",
          "value": "NSLogTopLevelExceptionMask"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.Exception-Handling~1documentation~1ExceptionHandling~1NSLogTopLevelExceptionMask/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSLogTopLevelExceptionMask"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.Exception-Handling~1documentation~1ExceptionHandling~1NSHandleUncaughtRuntimeErrorMask/title",
          "value": "NSHandleUncaughtRuntimeErrorMask"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.Exception-Handling~1documentation~1ExceptionHandling~1NSHandleUncaughtRuntimeErrorMask/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSHandleUncaughtRuntimeErrorMask"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.Exception-Handling~1documentation~1ExceptionHandling~1NSHandleUncaughtSystemExceptionMask/title",
          "value": "NSHandleUncaughtSystemExceptionMask"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.Exception-Handling~1documentation~1ExceptionHandling~1NSHandleUncaughtSystemExceptionMask/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSHandleUncaughtSystemExceptionMask"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.Exception-Handling~1documentation~1ExceptionHandling~1NSExceptionHandler~1setExceptionHangingMask(_:)/title",
          "value": "setExceptionHangingMask:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.Exception-Handling~1documentation~1ExceptionHandling~1NSExceptionHandler~1setExceptionHangingMask(_:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "setExceptionHangingMask:"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/exceptionhandling/logging-and-handling-constants"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/exceptionhandling/logging-and-handling-constants"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
