{"topicSections":[{"anchor":"Constants","identifiers":["doc://com.apple.Exception-Handling/documentation/ExceptionHandling/NSHangOnEveryExceptionMask","doc://com.apple.Exception-Handling/documentation/ExceptionHandling/NSLogAndHandleEveryExceptionMask"],"title":"Constants"}],"kind":"article","seeAlsoSections":[{"generated":true,"anchor":"Constants","identifiers":["doc://com.apple.Exception-Handling/documentation/ExceptionHandling/logging-and-handling-constants","doc://com.apple.Exception-Handling/documentation/ExceptionHandling/system-hang-constants","doc://com.apple.Exception-Handling/documentation/ExceptionHandling/exception-global-string-constants"],"title":"Constants"}],"identifier":{"interfaceLanguage":"occ","url":"doc://com.apple.Exception-Handling/documentation/ExceptionHandling/mask-definitions"},"sections":[],"hierarchy":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.Exception-Handling/documentation/ExceptionHandling","doc://com.apple.Exception-Handling/documentation/ExceptionHandling/NSExceptionHandler"]]},"abstract":[{"type":"text","text":"The following "},{"type":"codeVoice","code":"#define"},{"type":"text","text":" constants are conveniences for specifying complete sets of"},{"type":"text","text":" "},{"type":"text","text":"exception-handling "},{"type":"codeVoice","code":"enum"},{"text":" constants.","type":"text"}],"variants":[{"traits":[{"interfaceLanguage":"occ"}],"paths":["/documentation/exceptionhandling/mask-definitions"]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"metadata":{"title":"Mask Definitions","modules":[{"name":"Exception Handling"}],"role":"collectionGroup","roleHeading":"API Collection"},"references":{"doc://com.apple.documentation/documentation/foundation/nsexception/1418149-userinfo":{"fragments":[{"text":"var ","kind":"text"},{"text":"userInfo","kind":"identifier"},{"text":": [AnyHashable : Any]?","kind":"text"}],"url":"/documentation/foundation/nsexception/1418149-userinfo","type":"topic","title":"userInfo","abstract":[{"text":"A dictionary containing application-specific data pertaining to the receiver.","type":"text"}],"role":"symbol","identifier":"doc://com.apple.documentation/documentation/foundation/nsexception/1418149-userinfo","kind":"symbol"},"doc://com.apple.Exception-Handling/documentation/ExceptionHandling/NSLogAndHandleEveryExceptionMask":{"type":"topic","identifier":"doc://com.apple.Exception-Handling/documentation/ExceptionHandling/NSLogAndHandleEveryExceptionMask","abstract":[{"type":"text","text":"Combines via bitwise-OR all the constants listed in "},{"isActive":true,"type":"reference","identifier":"doc://com.apple.Exception-Handling/documentation/ExceptionHandling/logging-and-handling-constants"},{"type":"text","text":"."}],"role":"symbol","title":"NSLogAndHandleEveryExceptionMask","kind":"symbol","url":"/documentation/exceptionhandling/nslogandhandleeveryexceptionmask","fragments":[{"kind":"identifier","text":"NSLogAndHandleEveryExceptionMask"}]},"doc://com.apple.Exception-Handling/documentation/ExceptionHandling":{"url":"/documentation/exceptionhandling","abstract":[{"text":"Monitor and debug exceptional conditions in code.","type":"text"}],"identifier":"doc://com.apple.Exception-Handling/documentation/ExceptionHandling","title":"Exception Handling","kind":"symbol","role":"collection","type":"topic"},"doc://com.apple.Exception-Handling/documentation/ExceptionHandling/NSExceptionHandler/setExceptionHandlingMask(_:)":{"url":"/documentation/exceptionhandling/nsexceptionhandler/setexceptionhandlingmask(_:)","kind":"symbol","type":"topic","role":"symbol","navigatorTitle":[{"text":"setExceptionHandlingMask:","kind":"identifier"}],"abstract":[{"text":"Sets the bit mask of constants specifying the types of exceptions monitored by the","type":"text"},{"type":"text","text":" "},{"type":"text","text":"receiver and its handling and logging behavior."}],"identifier":"doc://com.apple.Exception-Handling/documentation/ExceptionHandling/NSExceptionHandler/setExceptionHandlingMask(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"setExceptionHandlingMask"},{"kind":"text","text":"("},{"preciseIdentifier":"s:Si","text":"Int","kind":"typeIdentifier"},{"text":")","kind":"text"}],"title":"setExceptionHandlingMask(_:)"},"doc://com.apple.documentation/documentation/foundation/1409609-nssetuncaughtexceptionhandler":{"identifier":"doc://com.apple.documentation/documentation/foundation/1409609-nssetuncaughtexceptionhandler","title":"NSSetUncaughtExceptionHandler(_:)","url":"/documentation/foundation/1409609-nssetuncaughtexceptionhandler","role":"symbol","kind":"symbol","abstract":[{"type":"text","text":"Changes the top-level error handler."}],"type":"topic","fragments":[{"kind":"text","text":"func "},{"text":"NSSetUncaughtExceptionHandler","kind":"identifier"},{"text":"(((NSException) -> Void)?)","kind":"text"}]},"doc://com.apple.Exception-Handling/documentation/ExceptionHandling/NSExceptionHandler/setExceptionHangingMask(_:)":{"url":"/documentation/exceptionhandling/nsexceptionhandler/setexceptionhangingmask(_:)","kind":"symbol","type":"topic","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"setExceptionHangingMask:"}],"abstract":[{"text":"Sets the bit mask of constants specifying the types of exceptions that will halt","type":"text"},{"type":"text","text":" "},{"type":"text","text":"execution for debugging."}],"identifier":"doc://com.apple.Exception-Handling/documentation/ExceptionHandling/NSExceptionHandler/setExceptionHangingMask(_:)","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"setExceptionHangingMask","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Si","text":"Int"},{"kind":"text","text":")"}],"title":"setExceptionHangingMask(_:)"},"doc://com.apple.Exception-Handling/documentation/ExceptionHandling/system-hang-constants":{"url":"/documentation/exceptionhandling/system-hang-constants","kind":"article","type":"topic","role":"collectionGroup","abstract":[{"text":"Use one or more of the following constants in the parameter of ","type":"text"},{"isActive":true,"identifier":"doc://com.apple.Exception-Handling/documentation/ExceptionHandling/NSExceptionHandler/setExceptionHangingMask(_:)","type":"reference"},{"type":"text","text":" "},{"type":"text","text":"to specify the types of exceptions that cause the exception to halt execution so"},{"type":"text","text":" "},{"type":"text","text":"a debugger can be attached."}],"identifier":"doc://com.apple.Exception-Handling/documentation/ExceptionHandling/system-hang-constants","title":"System Hang Constants"},"doc://com.apple.Exception-Handling/documentation/ExceptionHandling/logging-and-handling-constants":{"url":"/documentation/exceptionhandling/logging-and-handling-constants","kind":"article","type":"topic","role":"collectionGroup","abstract":[{"type":"text","text":"Use one or more of the following constants in the parameter of "},{"type":"reference","identifier":"doc://com.apple.Exception-Handling/documentation/ExceptionHandling/NSExceptionHandler/setExceptionHandlingMask(_:)","isActive":true},{"type":"text","text":" "},{"type":"text","text":"to specify the types of exceptions that the exception handler should monitor and"},{"type":"text","text":" "},{"type":"text","text":"whether it should handle or log them."}],"identifier":"doc://com.apple.Exception-Handling/documentation/ExceptionHandling/logging-and-handling-constants","title":"Logging and Handling Constants"},"doc://com.apple.Exception-Handling/documentation/ExceptionHandling/NSHangOnEveryExceptionMask":{"type":"topic","identifier":"doc://com.apple.Exception-Handling/documentation/ExceptionHandling/NSHangOnEveryExceptionMask","abstract":[{"type":"text","text":"Combines via bitwise-OR all the constants listed in "},{"isActive":true,"type":"reference","identifier":"doc://com.apple.Exception-Handling/documentation/ExceptionHandling/system-hang-constants"},{"type":"text","text":"."}],"role":"symbol","title":"NSHangOnEveryExceptionMask","kind":"symbol","url":"/documentation/exceptionhandling/nshangoneveryexceptionmask","fragments":[{"text":"NSHangOnEveryExceptionMask","kind":"identifier"}]},"doc://com.apple.Exception-Handling/documentation/ExceptionHandling/exception-global-string-constants":{"kind":"article","title":"Exception Global String Constants","abstract":[{"text":"Two of the following global string constants identify exceptions generated by the","type":"text"},{"text":" ","type":"text"},{"text":"framework for Objective-C runtime errors and system exceptions such as invalid memory","type":"text"},{"text":" ","type":"text"},{"text":"accesses. The other constant is used as a key to access the stack trace in the ","type":"text"},{"identifier":"doc://com.apple.documentation/documentation/foundation/nsexception/1418149-userinfo","type":"reference","isActive":true},{"text":" ","type":"text"},{"text":"dictionary of an ","type":"text"},{"identifier":"doc://com.apple.documentation/documentation/foundation/nsexception","type":"reference","isActive":true},{"text":" ","type":"text"},{"text":"object, when requested.","type":"text"}],"role":"collectionGroup","type":"topic","identifier":"doc://com.apple.Exception-Handling/documentation/ExceptionHandling/exception-global-string-constants","url":"/documentation/exceptionhandling/exception-global-string-constants"},"doc://com.apple.Exception-Handling/documentation/ExceptionHandling/NSExceptionHandler":{"kind":"symbol","url":"/documentation/exceptionhandling/nsexceptionhandler","role":"symbol","type":"topic","title":"NSExceptionHandler","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"NSExceptionHandler","kind":"identifier"}],"identifier":"doc://com.apple.Exception-Handling/documentation/ExceptionHandling/NSExceptionHandler","abstract":[{"text":"The ","type":"text"},{"code":"NSExceptionHandler","type":"codeVoice"},{"text":" class provides facilities for monitoring and debugging exceptional","type":"text"},{"type":"text","text":" "},{"type":"text","text":"conditions in Objective-C programs. It works by installing a special uncaught exception"},{"type":"text","text":" "},{"type":"text","text":"handler via the  "},{"type":"reference","isActive":true,"identifier":"doc://com.apple.documentation/documentation/foundation/1409609-nssetuncaughtexceptionhandler"},{"type":"text","text":" "},{"text":"function. Consequently, to use the services of ","type":"text"},{"code":"NSExceptionHandler","type":"codeVoice"},{"text":", you must not","type":"text"},{"text":" ","type":"text"},{"text":"install your own custom uncaught exception handler.","type":"text"}],"navigatorTitle":[{"text":"NSExceptionHandler","kind":"identifier"}]},"doc://com.apple.documentation/documentation/foundation/nsexception":{"title":"NSException","abstract":[{"text":"An object that represents a special condition that interrupts the normal flow of program execution.","type":"text"}],"url":"/documentation/foundation/nsexception","fragments":[{"text":"class ","kind":"text"},{"text":"NSException","kind":"identifier"}],"role":"symbol","identifier":"doc://com.apple.documentation/documentation/foundation/nsexception","type":"topic","kind":"symbol"},"doc://com.apple.documentation/documentation/technologies":{"url":"/documentation/technologies","abstract":[{"text":"","type":"text"}],"identifier":"doc://com.apple.documentation/documentation/technologies","title":"Technologies","kind":"technologies","role":"overview","type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"/references/doc:~1~1com.apple.Exception-Handling~1documentation~1ExceptionHandling~1NSExceptionHandler~1setExceptionHandlingMask(_:)/title","value":"setExceptionHandlingMask:","op":"replace"},{"path":"/references/doc:~1~1com.apple.Exception-Handling~1documentation~1ExceptionHandling~1NSExceptionHandler~1setExceptionHandlingMask(_:)/fragments","value":[{"text":"- ","kind":"text"},{"text":"setExceptionHandlingMask:","kind":"identifier"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.documentation~1documentation~1foundation~11409609-nssetuncaughtexceptionhandler/title","value":"NSSetUncaughtExceptionHandler","op":"replace"},{"path":"/references/doc:~1~1com.apple.Exception-Handling~1documentation~1ExceptionHandling~1NSExceptionHandler~1setExceptionHangingMask(_:)/title","value":"setExceptionHangingMask:","op":"replace"},{"path":"/references/doc:~1~1com.apple.Exception-Handling~1documentation~1ExceptionHandling~1NSExceptionHandler~1setExceptionHangingMask(_:)/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"text":"setExceptionHangingMask:","kind":"identifier"}]},{"path":"/references/doc:~1~1com.apple.Exception-Handling~1documentation~1ExceptionHandling~1NSExceptionHandler/title","op":"replace","value":"NSExceptionHandler"},{"op":"replace","path":"/references/doc:~1~1com.apple.Exception-Handling~1documentation~1ExceptionHandling~1NSExceptionHandler/fragments","value":[{"text":"NSExceptionHandler","kind":"identifier"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.Exception-Handling~1documentation~1ExceptionHandling~1NSExceptionHandler/navigatorTitle","value":[{"kind":"identifier","text":"NSExceptionHandler"}]}]}],"legalNotices":{"copyright":"Copyright &copy; 2025 Apple Inc. All rights reserved.","termsOfUse":"https://www.apple.com/legal/internet-services/terms/site.html","privacyPolicy":"https://www.apple.com/privacy/privacy-policy"}}