{
  "abstract": [
    {
      "text": "The exception handler suspends execution when it detects an exception that would",
      "type": "text"
    },
    {
      "text": " ",
      "type": "text"
    },
    {
      "text": "be handled by an object other than the top-level handler.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.Exception-Handling/documentation/ExceptionHandling"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.Exception-Handling/documentation/ExceptionHandling/NSHangOnOtherExceptionMask"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@Ea@NSHangOnUncaughtExceptionMask@NSHangOnOtherExceptionMask",
    "fragments": [
      {
        "kind": "keyword",
        "text": "var"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "NSHangOnOtherExceptionMask"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "s:Si",
        "text": "Int"
      }
    ],
    "modules": [
      {
        "name": "Exception Handling"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "NSHangOnOtherExceptionMask"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.0",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.0",
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Global Variable",
    "symbolKind": "var",
    "title": "NSHangOnOtherExceptionMask"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "macOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "var"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "NSHangOnOtherExceptionMask"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:Si",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:Si",
              "text": "Int"
            },
            {
              "kind": "text",
              "text": " { "
            },
            {
              "kind": "keyword",
              "text": "get"
            },
            {
              "kind": "text",
              "text": " }"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.Exception-Handling/documentation/ExceptionHandling": {
      "abstract": [
        {
          "text": "Monitor and debug exceptional conditions in code.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.Exception-Handling/documentation/ExceptionHandling",
      "kind": "symbol",
      "role": "collection",
      "title": "Exception Handling",
      "type": "topic",
      "url": "/documentation/exceptionhandling"
    },
    "doc://com.apple.Exception-Handling/documentation/ExceptionHandling/NSHangOnOtherExceptionMask": {
      "abstract": [
        {
          "text": "The exception handler suspends execution when it detects an exception that would",
          "type": "text"
        },
        {
          "text": " ",
          "type": "text"
        },
        {
          "text": "be handled by an object other than the top-level handler.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSHangOnOtherExceptionMask"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.Exception-Handling/documentation/ExceptionHandling/NSHangOnOtherExceptionMask",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSHangOnOtherExceptionMask"
        }
      ],
      "role": "symbol",
      "title": "NSHangOnOtherExceptionMask",
      "type": "topic",
      "url": "/documentation/exceptionhandling/nshangonotherexceptionmask"
    },
    "doc://com.apple.Exception-Handling/documentation/ExceptionHandling/NSHangOnTopLevelExceptionMask": {
      "abstract": [
        {
          "text": "The exception handler suspends execution when it detects an exception that would",
          "type": "text"
        },
        {
          "text": " ",
          "type": "text"
        },
        {
          "text": "be handled by the top-level handler.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSHangOnTopLevelExceptionMask"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.Exception-Handling/documentation/ExceptionHandling/NSHangOnTopLevelExceptionMask",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSHangOnTopLevelExceptionMask"
        }
      ],
      "role": "symbol",
      "title": "NSHangOnTopLevelExceptionMask",
      "type": "topic",
      "url": "/documentation/exceptionhandling/nshangontoplevelexceptionmask"
    },
    "doc://com.apple.Exception-Handling/documentation/ExceptionHandling/NSHangOnUncaughtExceptionMask": {
      "abstract": [
        {
          "text": "The exception handler suspends execution when it detects an uncaught exception (other",
          "type": "text"
        },
        {
          "text": " ",
          "type": "text"
        },
        {
          "text": "than a system exception or runtime error).",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSHangOnUncaughtExceptionMask"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.Exception-Handling/documentation/ExceptionHandling/NSHangOnUncaughtExceptionMask",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSHangOnUncaughtExceptionMask"
        }
      ],
      "role": "symbol",
      "title": "NSHangOnUncaughtExceptionMask",
      "type": "topic",
      "url": "/documentation/exceptionhandling/nshangonuncaughtexceptionmask"
    },
    "doc://com.apple.Exception-Handling/documentation/ExceptionHandling/NSHangOnUncaughtRuntimeErrorMask": {
      "abstract": [
        {
          "text": "The exception handler suspends execution when it detects an uncaught runtime error.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSHangOnUncaughtRuntimeErrorMask"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.Exception-Handling/documentation/ExceptionHandling/NSHangOnUncaughtRuntimeErrorMask",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSHangOnUncaughtRuntimeErrorMask"
        }
      ],
      "role": "symbol",
      "title": "NSHangOnUncaughtRuntimeErrorMask",
      "type": "topic",
      "url": "/documentation/exceptionhandling/nshangonuncaughtruntimeerrormask"
    },
    "doc://com.apple.Exception-Handling/documentation/ExceptionHandling/NSHangOnUncaughtSystemExceptionMask": {
      "abstract": [
        {
          "text": "The exception handler suspends execution when it detects an uncaught system exception.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSHangOnUncaughtSystemExceptionMask"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.Exception-Handling/documentation/ExceptionHandling/NSHangOnUncaughtSystemExceptionMask",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSHangOnUncaughtSystemExceptionMask"
        }
      ],
      "role": "symbol",
      "title": "NSHangOnUncaughtSystemExceptionMask",
      "type": "topic",
      "url": "/documentation/exceptionhandling/nshangonuncaughtsystemexceptionmask"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.externally.resolved.symbol/s:Si": {
      "abstract": [
        {
          "text": "A signed integer value type.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@frozen"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:Si",
      "kind": "symbol",
      "role": "symbol",
      "title": "Int",
      "type": "topic",
      "url": "/documentation/Swift/Int"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Constants",
      "generated": true,
      "identifiers": [
        "doc://com.apple.Exception-Handling/documentation/ExceptionHandling/NSHangOnUncaughtExceptionMask",
        "doc://com.apple.Exception-Handling/documentation/ExceptionHandling/NSHangOnUncaughtSystemExceptionMask",
        "doc://com.apple.Exception-Handling/documentation/ExceptionHandling/NSHangOnUncaughtRuntimeErrorMask",
        "doc://com.apple.Exception-Handling/documentation/ExceptionHandling/NSHangOnTopLevelExceptionMask"
      ],
      "title": "Constants"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.0",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.0",
              "name": "macOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration Case"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "NSHangOnOtherExceptionMask"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "case"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSHangOnOtherExceptionMask"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.Exception-Handling/documentation/ExceptionHandling"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Constants",
              "generated": true,
              "identifiers": [
                "doc://com.apple.Exception-Handling/documentation/ExceptionHandling/NSHangOnUncaughtExceptionMask",
                "doc://com.apple.Exception-Handling/documentation/ExceptionHandling/NSHangOnUncaughtSystemExceptionMask",
                "doc://com.apple.Exception-Handling/documentation/ExceptionHandling/NSHangOnUncaughtRuntimeErrorMask",
                "doc://com.apple.Exception-Handling/documentation/ExceptionHandling/NSHangOnTopLevelExceptionMask"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "macOS"
                ],
                "tokens": [
                  {
                    "kind": "identifier",
                    "text": "NSHangOnOtherExceptionMask"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.Exception-Handling~1documentation~1ExceptionHandling~1NSHangOnOtherExceptionMask/title",
          "value": "NSHangOnOtherExceptionMask"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.Exception-Handling~1documentation~1ExceptionHandling~1NSHangOnOtherExceptionMask/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSHangOnOtherExceptionMask"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.Exception-Handling~1documentation~1ExceptionHandling~1NSHangOnTopLevelExceptionMask/title",
          "value": "NSHangOnTopLevelExceptionMask"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.Exception-Handling~1documentation~1ExceptionHandling~1NSHangOnTopLevelExceptionMask/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSHangOnTopLevelExceptionMask"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.Exception-Handling~1documentation~1ExceptionHandling~1NSHangOnUncaughtExceptionMask/title",
          "value": "NSHangOnUncaughtExceptionMask"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.Exception-Handling~1documentation~1ExceptionHandling~1NSHangOnUncaughtExceptionMask/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSHangOnUncaughtExceptionMask"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.Exception-Handling~1documentation~1ExceptionHandling~1NSHangOnUncaughtRuntimeErrorMask/title",
          "value": "NSHangOnUncaughtRuntimeErrorMask"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.Exception-Handling~1documentation~1ExceptionHandling~1NSHangOnUncaughtRuntimeErrorMask/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSHangOnUncaughtRuntimeErrorMask"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.Exception-Handling~1documentation~1ExceptionHandling~1NSHangOnUncaughtSystemExceptionMask/title",
          "value": "NSHangOnUncaughtSystemExceptionMask"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.Exception-Handling~1documentation~1ExceptionHandling~1NSHangOnUncaughtSystemExceptionMask/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSHangOnUncaughtSystemExceptionMask"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/exceptionhandling/nshangonotherexceptionmask"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/exceptionhandling/nshangonotherexceptionmask"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
