{
  "abstract": [
    {
      "text": "The exception handler handles exceptions caught by the top-level handler by converting",
      "type": "text"
    },
    {
      "text": " ",
      "type": "text"
    },
    {
      "text": "them to ",
      "type": "text"
    },
    {
      "identifier": "doc://com.apple.documentation/documentation/foundation/nsexception",
      "isActive": true,
      "type": "reference"
    },
    {
      "text": " objects",
      "type": "text"
    },
    {
      "text": " ",
      "type": "text"
    },
    {
      "text": "containing a stack trace.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.Exception-Handling/documentation/ExceptionHandling"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.Exception-Handling/documentation/ExceptionHandling/NSHandleTopLevelExceptionMask"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@Ea@NSLogUncaughtExceptionMask@NSHandleTopLevelExceptionMask",
    "fragments": [
      {
        "kind": "keyword",
        "text": "var"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "NSHandleTopLevelExceptionMask"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "s:Si",
        "text": "Int"
      }
    ],
    "modules": [
      {
        "name": "Exception Handling"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "NSHandleTopLevelExceptionMask"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.0",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.0",
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Global Variable",
    "symbolKind": "var",
    "title": "NSHandleTopLevelExceptionMask"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "macOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "var"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "NSHandleTopLevelExceptionMask"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:Si",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:Si",
              "text": "Int"
            },
            {
              "kind": "text",
              "text": " { "
            },
            {
              "kind": "keyword",
              "text": "get"
            },
            {
              "kind": "text",
              "text": " }"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.Exception-Handling/documentation/ExceptionHandling": {
      "abstract": [
        {
          "text": "Monitor and debug exceptional conditions in code.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.Exception-Handling/documentation/ExceptionHandling",
      "kind": "symbol",
      "role": "collection",
      "title": "Exception Handling",
      "type": "topic",
      "url": "/documentation/exceptionhandling"
    },
    "doc://com.apple.Exception-Handling/documentation/ExceptionHandling/NSHandleOtherExceptionMask": {
      "abstract": [
        {
          "text": "The exception handler handles exceptions caught by handlers lower than the top-level",
          "type": "text"
        },
        {
          "text": " ",
          "type": "text"
        },
        {
          "text": "handler by converting them to ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.documentation/documentation/foundation/nsexception",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " ",
          "type": "text"
        },
        {
          "text": "objects containing a stack trace.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSHandleOtherExceptionMask"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.Exception-Handling/documentation/ExceptionHandling/NSHandleOtherExceptionMask",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSHandleOtherExceptionMask"
        }
      ],
      "role": "symbol",
      "title": "NSHandleOtherExceptionMask",
      "type": "topic",
      "url": "/documentation/exceptionhandling/nshandleotherexceptionmask"
    },
    "doc://com.apple.Exception-Handling/documentation/ExceptionHandling/NSHandleTopLevelExceptionMask": {
      "abstract": [
        {
          "text": "The exception handler handles exceptions caught by the top-level handler by converting",
          "type": "text"
        },
        {
          "text": " ",
          "type": "text"
        },
        {
          "text": "them to ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.documentation/documentation/foundation/nsexception",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " objects",
          "type": "text"
        },
        {
          "text": " ",
          "type": "text"
        },
        {
          "text": "containing a stack trace.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSHandleTopLevelExceptionMask"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.Exception-Handling/documentation/ExceptionHandling/NSHandleTopLevelExceptionMask",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSHandleTopLevelExceptionMask"
        }
      ],
      "role": "symbol",
      "title": "NSHandleTopLevelExceptionMask",
      "type": "topic",
      "url": "/documentation/exceptionhandling/nshandletoplevelexceptionmask"
    },
    "doc://com.apple.Exception-Handling/documentation/ExceptionHandling/NSHandleUncaughtExceptionMask": {
      "abstract": [
        {
          "text": "The exception handler handles uncaught exceptions by terminating the thread in which",
          "type": "text"
        },
        {
          "text": " ",
          "type": "text"
        },
        {
          "text": "they occur.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSHandleUncaughtExceptionMask"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.Exception-Handling/documentation/ExceptionHandling/NSHandleUncaughtExceptionMask",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSHandleUncaughtExceptionMask"
        }
      ],
      "role": "symbol",
      "title": "NSHandleUncaughtExceptionMask",
      "type": "topic",
      "url": "/documentation/exceptionhandling/nshandleuncaughtexceptionmask"
    },
    "doc://com.apple.Exception-Handling/documentation/ExceptionHandling/NSHandleUncaughtRuntimeErrorMask": {
      "abstract": [
        {
          "text": "The exception handler handles uncaught runtime errors by converting them to ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.documentation/documentation/foundation/nsexception",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " ",
          "type": "text"
        },
        {
          "text": "objects containing a stack trace.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSHandleUncaughtRuntimeErrorMask"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.Exception-Handling/documentation/ExceptionHandling/NSHandleUncaughtRuntimeErrorMask",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSHandleUncaughtRuntimeErrorMask"
        }
      ],
      "role": "symbol",
      "title": "NSHandleUncaughtRuntimeErrorMask",
      "type": "topic",
      "url": "/documentation/exceptionhandling/nshandleuncaughtruntimeerrormask"
    },
    "doc://com.apple.Exception-Handling/documentation/ExceptionHandling/NSHandleUncaughtSystemExceptionMask": {
      "abstract": [
        {
          "text": "The exception handler handles uncaught system exceptions by converting them to ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.documentation/documentation/foundation/nsexception",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " ",
          "type": "text"
        },
        {
          "text": "objects containing a stack trace.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSHandleUncaughtSystemExceptionMask"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.Exception-Handling/documentation/ExceptionHandling/NSHandleUncaughtSystemExceptionMask",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSHandleUncaughtSystemExceptionMask"
        }
      ],
      "role": "symbol",
      "title": "NSHandleUncaughtSystemExceptionMask",
      "type": "topic",
      "url": "/documentation/exceptionhandling/nshandleuncaughtsystemexceptionmask"
    },
    "doc://com.apple.Exception-Handling/documentation/ExceptionHandling/NSLogOtherExceptionMask": {
      "abstract": [
        {
          "text": "The exception handler logs exceptions caught by handlers lower than the top-level",
          "type": "text"
        },
        {
          "text": " ",
          "type": "text"
        },
        {
          "text": "handler.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSLogOtherExceptionMask"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.Exception-Handling/documentation/ExceptionHandling/NSLogOtherExceptionMask",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSLogOtherExceptionMask"
        }
      ],
      "role": "symbol",
      "title": "NSLogOtherExceptionMask",
      "type": "topic",
      "url": "/documentation/exceptionhandling/nslogotherexceptionmask"
    },
    "doc://com.apple.Exception-Handling/documentation/ExceptionHandling/NSLogTopLevelExceptionMask": {
      "abstract": [
        {
          "text": "The exception handler logs exceptions that would be caught by the top-level handler.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSLogTopLevelExceptionMask"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.Exception-Handling/documentation/ExceptionHandling/NSLogTopLevelExceptionMask",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSLogTopLevelExceptionMask"
        }
      ],
      "role": "symbol",
      "title": "NSLogTopLevelExceptionMask",
      "type": "topic",
      "url": "/documentation/exceptionhandling/nslogtoplevelexceptionmask"
    },
    "doc://com.apple.Exception-Handling/documentation/ExceptionHandling/NSLogUncaughtExceptionMask": {
      "abstract": [
        {
          "text": "The exception handler logs uncaught exceptions.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSLogUncaughtExceptionMask"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.Exception-Handling/documentation/ExceptionHandling/NSLogUncaughtExceptionMask",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSLogUncaughtExceptionMask"
        }
      ],
      "role": "symbol",
      "title": "NSLogUncaughtExceptionMask",
      "type": "topic",
      "url": "/documentation/exceptionhandling/nsloguncaughtexceptionmask"
    },
    "doc://com.apple.Exception-Handling/documentation/ExceptionHandling/NSLogUncaughtRuntimeErrorMask": {
      "abstract": [
        {
          "text": "The exception handler logs uncaught runtime errors.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSLogUncaughtRuntimeErrorMask"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.Exception-Handling/documentation/ExceptionHandling/NSLogUncaughtRuntimeErrorMask",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSLogUncaughtRuntimeErrorMask"
        }
      ],
      "role": "symbol",
      "title": "NSLogUncaughtRuntimeErrorMask",
      "type": "topic",
      "url": "/documentation/exceptionhandling/nsloguncaughtruntimeerrormask"
    },
    "doc://com.apple.Exception-Handling/documentation/ExceptionHandling/NSLogUncaughtSystemExceptionMask": {
      "abstract": [
        {
          "text": "The exception handler logs uncaught system exceptions.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSLogUncaughtSystemExceptionMask"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.Exception-Handling/documentation/ExceptionHandling/NSLogUncaughtSystemExceptionMask",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSLogUncaughtSystemExceptionMask"
        }
      ],
      "role": "symbol",
      "title": "NSLogUncaughtSystemExceptionMask",
      "type": "topic",
      "url": "/documentation/exceptionhandling/nsloguncaughtsystemexceptionmask"
    },
    "doc://com.apple.documentation/documentation/foundation/nsexception": {
      "abstract": [
        {
          "text": "An object that represents a special condition that interrupts the normal flow of program execution.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "class "
        },
        {
          "kind": "identifier",
          "text": "NSException"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/foundation/nsexception",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSException",
      "type": "topic",
      "url": "/documentation/foundation/nsexception"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.externally.resolved.symbol/s:Si": {
      "abstract": [
        {
          "text": "A signed integer value type.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@frozen"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:Si",
      "kind": "symbol",
      "role": "symbol",
      "title": "Int",
      "type": "topic",
      "url": "/documentation/Swift/Int"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Constants",
      "generated": true,
      "identifiers": [
        "doc://com.apple.Exception-Handling/documentation/ExceptionHandling/NSLogUncaughtExceptionMask",
        "doc://com.apple.Exception-Handling/documentation/ExceptionHandling/NSHandleUncaughtExceptionMask",
        "doc://com.apple.Exception-Handling/documentation/ExceptionHandling/NSLogUncaughtSystemExceptionMask",
        "doc://com.apple.Exception-Handling/documentation/ExceptionHandling/NSHandleUncaughtSystemExceptionMask",
        "doc://com.apple.Exception-Handling/documentation/ExceptionHandling/NSLogUncaughtRuntimeErrorMask",
        "doc://com.apple.Exception-Handling/documentation/ExceptionHandling/NSHandleUncaughtRuntimeErrorMask",
        "doc://com.apple.Exception-Handling/documentation/ExceptionHandling/NSLogTopLevelExceptionMask",
        "doc://com.apple.Exception-Handling/documentation/ExceptionHandling/NSLogOtherExceptionMask",
        "doc://com.apple.Exception-Handling/documentation/ExceptionHandling/NSHandleOtherExceptionMask"
      ],
      "title": "Constants"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.0",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.0",
              "name": "macOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration Case"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "NSHandleTopLevelExceptionMask"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "case"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSHandleTopLevelExceptionMask"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.Exception-Handling/documentation/ExceptionHandling"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Constants",
              "generated": true,
              "identifiers": [
                "doc://com.apple.Exception-Handling/documentation/ExceptionHandling/NSLogUncaughtExceptionMask",
                "doc://com.apple.Exception-Handling/documentation/ExceptionHandling/NSHandleUncaughtExceptionMask",
                "doc://com.apple.Exception-Handling/documentation/ExceptionHandling/NSLogUncaughtSystemExceptionMask",
                "doc://com.apple.Exception-Handling/documentation/ExceptionHandling/NSHandleUncaughtSystemExceptionMask",
                "doc://com.apple.Exception-Handling/documentation/ExceptionHandling/NSLogUncaughtRuntimeErrorMask",
                "doc://com.apple.Exception-Handling/documentation/ExceptionHandling/NSHandleUncaughtRuntimeErrorMask",
                "doc://com.apple.Exception-Handling/documentation/ExceptionHandling/NSLogTopLevelExceptionMask",
                "doc://com.apple.Exception-Handling/documentation/ExceptionHandling/NSLogOtherExceptionMask",
                "doc://com.apple.Exception-Handling/documentation/ExceptionHandling/NSHandleOtherExceptionMask"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "macOS"
                ],
                "tokens": [
                  {
                    "kind": "identifier",
                    "text": "NSHandleTopLevelExceptionMask"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.Exception-Handling~1documentation~1ExceptionHandling~1NSHandleOtherExceptionMask/title",
          "value": "NSHandleOtherExceptionMask"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.Exception-Handling~1documentation~1ExceptionHandling~1NSHandleOtherExceptionMask/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSHandleOtherExceptionMask"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.Exception-Handling~1documentation~1ExceptionHandling~1NSHandleUncaughtExceptionMask/title",
          "value": "NSHandleUncaughtExceptionMask"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.Exception-Handling~1documentation~1ExceptionHandling~1NSHandleUncaughtExceptionMask/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSHandleUncaughtExceptionMask"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.Exception-Handling~1documentation~1ExceptionHandling~1NSLogUncaughtExceptionMask/title",
          "value": "NSLogUncaughtExceptionMask"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.Exception-Handling~1documentation~1ExceptionHandling~1NSLogUncaughtExceptionMask/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSLogUncaughtExceptionMask"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.Exception-Handling~1documentation~1ExceptionHandling~1NSLogUncaughtSystemExceptionMask/title",
          "value": "NSLogUncaughtSystemExceptionMask"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.Exception-Handling~1documentation~1ExceptionHandling~1NSLogUncaughtSystemExceptionMask/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSLogUncaughtSystemExceptionMask"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.Exception-Handling~1documentation~1ExceptionHandling~1NSHandleTopLevelExceptionMask/title",
          "value": "NSHandleTopLevelExceptionMask"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.Exception-Handling~1documentation~1ExceptionHandling~1NSHandleTopLevelExceptionMask/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSHandleTopLevelExceptionMask"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.Exception-Handling~1documentation~1ExceptionHandling~1NSHandleUncaughtRuntimeErrorMask/title",
          "value": "NSHandleUncaughtRuntimeErrorMask"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.Exception-Handling~1documentation~1ExceptionHandling~1NSHandleUncaughtRuntimeErrorMask/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSHandleUncaughtRuntimeErrorMask"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.Exception-Handling~1documentation~1ExceptionHandling~1NSLogUncaughtRuntimeErrorMask/title",
          "value": "NSLogUncaughtRuntimeErrorMask"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.Exception-Handling~1documentation~1ExceptionHandling~1NSLogUncaughtRuntimeErrorMask/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSLogUncaughtRuntimeErrorMask"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.Exception-Handling~1documentation~1ExceptionHandling~1NSLogTopLevelExceptionMask/title",
          "value": "NSLogTopLevelExceptionMask"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.Exception-Handling~1documentation~1ExceptionHandling~1NSLogTopLevelExceptionMask/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSLogTopLevelExceptionMask"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.Exception-Handling~1documentation~1ExceptionHandling~1NSHandleUncaughtSystemExceptionMask/title",
          "value": "NSHandleUncaughtSystemExceptionMask"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.Exception-Handling~1documentation~1ExceptionHandling~1NSHandleUncaughtSystemExceptionMask/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSHandleUncaughtSystemExceptionMask"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.Exception-Handling~1documentation~1ExceptionHandling~1NSLogOtherExceptionMask/title",
          "value": "NSLogOtherExceptionMask"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.Exception-Handling~1documentation~1ExceptionHandling~1NSLogOtherExceptionMask/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSLogOtherExceptionMask"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/exceptionhandling/nshandletoplevelexceptionmask"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/exceptionhandling/nshandletoplevelexceptionmask"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
