{
  "abstract": [
    {
      "text": "The biases tensor parameters you use for optimizer updates.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.mlcompute/documentation/MLCompute",
        "doc://com.apple.mlcompute/documentation/MLCompute/MLCLSTMLayer"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.mlcompute/documentation/MLCompute/MLCLSTMLayer/biasesParameters"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(cs)MLCLSTMLayer(py)biasesParameters",
    "fragments": [
      {
        "kind": "keyword",
        "text": "var"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "biasesParameters"
      },
      {
        "kind": "text",
        "text": ": ["
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:objc(cs)MLCTensorParameter",
        "text": "MLCTensorParameter"
      },
      {
        "kind": "text",
        "text": "]?"
      }
    ],
    "modules": [
      {
        "name": "ML Compute"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "biasesParameters"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "17.4",
        "introducedAt": "14.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "17.4",
        "introducedAt": "14.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "17.4",
        "introducedAt": "14.0",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "14.3",
        "introducedAt": "11.0",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "17.4",
        "introducedAt": "14.0",
        "name": "tvOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Instance Property",
    "symbolKind": "property",
    "title": "biasesParameters"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "var"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "biasesParameters"
            },
            {
              "kind": "text",
              "text": ": ["
            },
            {
              "identifier": "doc://com.apple.mlcompute/documentation/MLCompute/MLCTensorParameter",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)MLCTensorParameter",
              "text": "MLCTensorParameter"
            },
            {
              "kind": "text",
              "text": "]? { "
            },
            {
              "kind": "keyword",
              "text": "get"
            },
            {
              "kind": "text",
              "text": " }"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.mlcompute/documentation/MLCompute": {
      "abstract": [
        {
          "text": "Accelerate training and validation of neural networks across the CPU and one or more GPUs.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "identifier": "doc://com.apple.mlcompute/documentation/MLCompute",
      "kind": "symbol",
      "role": "collection",
      "title": "ML Compute",
      "type": "topic",
      "url": "/documentation/mlcompute"
    },
    "doc://com.apple.mlcompute/documentation/MLCompute/MLCLSTMLayer": {
      "abstract": [
        {
          "text": "A layer that represents long short-term memory (LSTM) networks.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MLCLSTMLayer"
        }
      ],
      "identifier": "doc://com.apple.mlcompute/documentation/MLCompute/MLCLSTMLayer",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MLCLSTMLayer"
        }
      ],
      "role": "symbol",
      "title": "MLCLSTMLayer",
      "type": "topic",
      "url": "/documentation/mlcompute/mlclstmlayer"
    },
    "doc://com.apple.mlcompute/documentation/MLCompute/MLCLSTMLayer/biases": {
      "abstract": [
        {
          "text": "The array of tensors that describe the bias terms you use for the input, hidden, cell, and output gates.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "biases"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)MLCTensor",
          "text": "MLCTensor"
        },
        {
          "kind": "text",
          "text": "]?"
        }
      ],
      "identifier": "doc://com.apple.mlcompute/documentation/MLCompute/MLCLSTMLayer/biases",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "biases"
        }
      ],
      "role": "symbol",
      "title": "biases",
      "type": "topic",
      "url": "/documentation/mlcompute/mlclstmlayer/biases"
    },
    "doc://com.apple.mlcompute/documentation/MLCompute/MLCLSTMLayer/biasesParameters": {
      "abstract": [
        {
          "text": "The biases tensor parameters you use for optimizer updates.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "biasesParameters"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)MLCTensorParameter",
          "text": "MLCTensorParameter"
        },
        {
          "kind": "text",
          "text": "]?"
        }
      ],
      "identifier": "doc://com.apple.mlcompute/documentation/MLCompute/MLCLSTMLayer/biasesParameters",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "biasesParameters"
        }
      ],
      "role": "symbol",
      "title": "biasesParameters",
      "type": "topic",
      "url": "/documentation/mlcompute/mlclstmlayer/biasesparameters"
    },
    "doc://com.apple.mlcompute/documentation/MLCompute/MLCLSTMLayer/descriptor": {
      "abstract": [
        {
          "text": "The configuration object you use to create the LSTM layer.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "descriptor"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)MLCLSTMDescriptor",
          "text": "MLCLSTMDescriptor"
        }
      ],
      "identifier": "doc://com.apple.mlcompute/documentation/MLCompute/MLCLSTMLayer/descriptor",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "descriptor"
        }
      ],
      "role": "symbol",
      "title": "descriptor",
      "type": "topic",
      "url": "/documentation/mlcompute/mlclstmlayer/descriptor"
    },
    "doc://com.apple.mlcompute/documentation/MLCompute/MLCLSTMLayer/gateActivations": {
      "abstract": [
        {
          "text": "The array of gate activations you use for input, hidden, cell, and output gates.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "gateActivations"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)MLCActivationDescriptor",
          "text": "MLCActivationDescriptor"
        },
        {
          "kind": "text",
          "text": "]"
        }
      ],
      "identifier": "doc://com.apple.mlcompute/documentation/MLCompute/MLCLSTMLayer/gateActivations",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "gateActivations"
        }
      ],
      "role": "symbol",
      "title": "gateActivations",
      "type": "topic",
      "url": "/documentation/mlcompute/mlclstmlayer/gateactivations"
    },
    "doc://com.apple.mlcompute/documentation/MLCompute/MLCLSTMLayer/hiddenWeights": {
      "abstract": [
        {
          "text": "The array of tensors that describe the hidden weights you use for the input, hidden, cell, and output gates.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "hiddenWeights"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)MLCTensor",
          "text": "MLCTensor"
        },
        {
          "kind": "text",
          "text": "]"
        }
      ],
      "identifier": "doc://com.apple.mlcompute/documentation/MLCompute/MLCLSTMLayer/hiddenWeights",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "hiddenWeights"
        }
      ],
      "role": "symbol",
      "title": "hiddenWeights",
      "type": "topic",
      "url": "/documentation/mlcompute/mlclstmlayer/hiddenweights"
    },
    "doc://com.apple.mlcompute/documentation/MLCompute/MLCLSTMLayer/hiddenWeightsParameters": {
      "abstract": [
        {
          "text": "The hidden weights tensor parameters you use for optimizer updates.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "hiddenWeightsParameters"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)MLCTensorParameter",
          "text": "MLCTensorParameter"
        },
        {
          "kind": "text",
          "text": "]"
        }
      ],
      "identifier": "doc://com.apple.mlcompute/documentation/MLCompute/MLCLSTMLayer/hiddenWeightsParameters",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "hiddenWeightsParameters"
        }
      ],
      "role": "symbol",
      "title": "hiddenWeightsParameters",
      "type": "topic",
      "url": "/documentation/mlcompute/mlclstmlayer/hiddenweightsparameters"
    },
    "doc://com.apple.mlcompute/documentation/MLCompute/MLCLSTMLayer/inputWeights": {
      "abstract": [
        {
          "text": "The array of tensors that describe the input weights you use for the input, hidden, cell, and output gates.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "inputWeights"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)MLCTensor",
          "text": "MLCTensor"
        },
        {
          "kind": "text",
          "text": "]"
        }
      ],
      "identifier": "doc://com.apple.mlcompute/documentation/MLCompute/MLCLSTMLayer/inputWeights",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "inputWeights"
        }
      ],
      "role": "symbol",
      "title": "inputWeights",
      "type": "topic",
      "url": "/documentation/mlcompute/mlclstmlayer/inputweights"
    },
    "doc://com.apple.mlcompute/documentation/MLCompute/MLCLSTMLayer/inputWeightsParameters": {
      "abstract": [
        {
          "text": "The input weights tensor parameters you use for optimizer updates.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "inputWeightsParameters"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)MLCTensorParameter",
          "text": "MLCTensorParameter"
        },
        {
          "kind": "text",
          "text": "]"
        }
      ],
      "identifier": "doc://com.apple.mlcompute/documentation/MLCompute/MLCLSTMLayer/inputWeightsParameters",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "inputWeightsParameters"
        }
      ],
      "role": "symbol",
      "title": "inputWeightsParameters",
      "type": "topic",
      "url": "/documentation/mlcompute/mlclstmlayer/inputweightsparameters"
    },
    "doc://com.apple.mlcompute/documentation/MLCompute/MLCLSTMLayer/outputResultActivation": {
      "abstract": [
        {
          "text": "The output activation descriptor.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "outputResultActivation"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)MLCActivationDescriptor",
          "text": "MLCActivationDescriptor"
        }
      ],
      "identifier": "doc://com.apple.mlcompute/documentation/MLCompute/MLCLSTMLayer/outputResultActivation",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "outputResultActivation"
        }
      ],
      "role": "symbol",
      "title": "outputResultActivation",
      "type": "topic",
      "url": "/documentation/mlcompute/mlclstmlayer/outputresultactivation"
    },
    "doc://com.apple.mlcompute/documentation/MLCompute/MLCLSTMLayer/peepholeWeights": {
      "abstract": [
        {
          "text": "The array of tensors that describe the peephole weights you use for the input, hidden, cell, and output gates.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "peepholeWeights"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)MLCTensor",
          "text": "MLCTensor"
        },
        {
          "kind": "text",
          "text": "]?"
        }
      ],
      "identifier": "doc://com.apple.mlcompute/documentation/MLCompute/MLCLSTMLayer/peepholeWeights",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "peepholeWeights"
        }
      ],
      "role": "symbol",
      "title": "peepholeWeights",
      "type": "topic",
      "url": "/documentation/mlcompute/mlclstmlayer/peepholeweights"
    },
    "doc://com.apple.mlcompute/documentation/MLCompute/MLCLSTMLayer/peepholeWeightsParameters": {
      "abstract": [
        {
          "text": "The peephole weights tensor parameters you use for optimizer updates.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "peepholeWeightsParameters"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)MLCTensorParameter",
          "text": "MLCTensorParameter"
        },
        {
          "kind": "text",
          "text": "]?"
        }
      ],
      "identifier": "doc://com.apple.mlcompute/documentation/MLCompute/MLCLSTMLayer/peepholeWeightsParameters",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "peepholeWeightsParameters"
        }
      ],
      "role": "symbol",
      "title": "peepholeWeightsParameters",
      "type": "topic",
      "url": "/documentation/mlcompute/mlclstmlayer/peepholeweightsparameters"
    },
    "doc://com.apple.mlcompute/documentation/MLCompute/MLCTensorParameter": {
      "abstract": [
        {
          "text": "A tensor parameter object.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MLCTensorParameter"
        }
      ],
      "identifier": "doc://com.apple.mlcompute/documentation/MLCompute/MLCTensorParameter",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MLCTensorParameter"
        }
      ],
      "role": "symbol",
      "title": "MLCTensorParameter",
      "type": "topic",
      "url": "/documentation/mlcompute/mlctensorparameter"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Inspecting-LSTM-Layers",
      "generated": true,
      "identifiers": [
        "doc://com.apple.mlcompute/documentation/MLCompute/MLCLSTMLayer/descriptor",
        "doc://com.apple.mlcompute/documentation/MLCompute/MLCLSTMLayer/gateActivations",
        "doc://com.apple.mlcompute/documentation/MLCompute/MLCLSTMLayer/outputResultActivation",
        "doc://com.apple.mlcompute/documentation/MLCompute/MLCLSTMLayer/inputWeights",
        "doc://com.apple.mlcompute/documentation/MLCompute/MLCLSTMLayer/hiddenWeights",
        "doc://com.apple.mlcompute/documentation/MLCompute/MLCLSTMLayer/peepholeWeights",
        "doc://com.apple.mlcompute/documentation/MLCompute/MLCLSTMLayer/biases",
        "doc://com.apple.mlcompute/documentation/MLCompute/MLCLSTMLayer/inputWeightsParameters",
        "doc://com.apple.mlcompute/documentation/MLCompute/MLCLSTMLayer/hiddenWeightsParameters",
        "doc://com.apple.mlcompute/documentation/MLCompute/MLCLSTMLayer/peepholeWeightsParameters"
      ],
      "title": "Inspecting LSTM Layers"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "deprecatedAt": "17.4",
              "introducedAt": "14.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "deprecatedAt": "17.4",
              "introducedAt": "14.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "deprecatedAt": "17.4",
              "introducedAt": "14.0",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "deprecatedAt": "14.3",
              "introducedAt": "11.0",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "deprecatedAt": "17.4",
              "introducedAt": "14.0",
              "name": "tvOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Instance Property"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "biasesParameters"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "property"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "biasesParameters"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.mlcompute/documentation/MLCompute",
                "doc://com.apple.mlcompute/documentation/MLCompute/MLCLSTMLayer"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Inspecting-LSTM-Layers",
              "generated": true,
              "identifiers": [
                "doc://com.apple.mlcompute/documentation/MLCompute/MLCLSTMLayer/descriptor",
                "doc://com.apple.mlcompute/documentation/MLCompute/MLCLSTMLayer/gateActivations",
                "doc://com.apple.mlcompute/documentation/MLCompute/MLCLSTMLayer/outputResultActivation",
                "doc://com.apple.mlcompute/documentation/MLCompute/MLCLSTMLayer/inputWeights",
                "doc://com.apple.mlcompute/documentation/MLCompute/MLCLSTMLayer/hiddenWeights",
                "doc://com.apple.mlcompute/documentation/MLCompute/MLCLSTMLayer/peepholeWeights",
                "doc://com.apple.mlcompute/documentation/MLCompute/MLCLSTMLayer/biases",
                "doc://com.apple.mlcompute/documentation/MLCompute/MLCLSTMLayer/inputWeightsParameters",
                "doc://com.apple.mlcompute/documentation/MLCompute/MLCLSTMLayer/hiddenWeightsParameters",
                "doc://com.apple.mlcompute/documentation/MLCompute/MLCLSTMLayer/peepholeWeightsParameters"
              ],
              "title": "Inspecting LSTM Layers"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "@property"
                  },
                  {
                    "kind": "text",
                    "text": " ("
                  },
                  {
                    "kind": "keyword",
                    "text": "nonatomic"
                  },
                  {
                    "kind": "text",
                    "text": ", "
                  },
                  {
                    "kind": "keyword",
                    "text": "retain"
                  },
                  {
                    "kind": "text",
                    "text": ", "
                  },
                  {
                    "kind": "keyword",
                    "text": "readonly"
                  },
                  {
                    "kind": "text",
                    "text": ") "
                  },
                  {
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:Q$objc(cs)NSArray",
                    "text": "NSArray<MLCTensorParameter *>"
                  },
                  {
                    "kind": "text",
                    "text": " * "
                  },
                  {
                    "kind": "identifier",
                    "text": "biasesParameters"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCLSTMLayer~1descriptor/title",
          "value": "descriptor"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCLSTMLayer~1descriptor/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "descriptor"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCLSTMLayer~1hiddenWeights/title",
          "value": "hiddenWeights"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCLSTMLayer~1hiddenWeights/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "hiddenWeights"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCLSTMLayer~1biases/title",
          "value": "biases"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCLSTMLayer~1biases/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "biases"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCLSTMLayer~1peepholeWeightsParameters/title",
          "value": "peepholeWeightsParameters"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCLSTMLayer~1peepholeWeightsParameters/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "peepholeWeightsParameters"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCTensorParameter/title",
          "value": "MLCTensorParameter"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCTensorParameter/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MLCTensorParameter"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCTensorParameter/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MLCTensorParameter"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCLSTMLayer~1hiddenWeightsParameters/title",
          "value": "hiddenWeightsParameters"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCLSTMLayer~1hiddenWeightsParameters/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "hiddenWeightsParameters"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCLSTMLayer~1gateActivations/title",
          "value": "gateActivations"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCLSTMLayer~1gateActivations/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "gateActivations"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCLSTMLayer~1outputResultActivation/title",
          "value": "outputResultActivation"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCLSTMLayer~1outputResultActivation/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "outputResultActivation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCLSTMLayer~1biasesParameters/title",
          "value": "biasesParameters"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCLSTMLayer~1biasesParameters/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "biasesParameters"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCLSTMLayer~1inputWeights/title",
          "value": "inputWeights"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCLSTMLayer~1inputWeights/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "inputWeights"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCLSTMLayer/title",
          "value": "MLCLSTMLayer"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCLSTMLayer/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MLCLSTMLayer"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCLSTMLayer/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MLCLSTMLayer"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCLSTMLayer~1inputWeightsParameters/title",
          "value": "inputWeightsParameters"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCLSTMLayer~1inputWeightsParameters/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "inputWeightsParameters"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCLSTMLayer~1peepholeWeights/title",
          "value": "peepholeWeights"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCLSTMLayer~1peepholeWeights/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "peepholeWeights"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/mlcompute/mlclstmlayer/biasesparameters"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/mlcompute/mlclstmlayer/biasesparameters"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
