{
  "abstract": [
    {
      "text": "Instructs the system to provide immediate haptic feedback to the user, rather than waiting for synchronization to occur with something visual occurring on screen.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.appkit/documentation/AppKit",
        "doc://com.apple.appkit/documentation/AppKit/NSHapticFeedbackManager",
        "doc://com.apple.appkit/documentation/AppKit/NSHapticFeedbackManager/PerformanceTime"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.appkit/documentation/AppKit/NSHapticFeedbackManager/PerformanceTime/now"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@NSHapticFeedbackPerformanceTime@NSHapticFeedbackPerformanceTimeNow",
    "fragments": [
      {
        "kind": "keyword",
        "text": "case"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "now"
      }
    ],
    "modules": [
      {
        "name": "AppKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "NSHapticFeedbackPerformanceTimeNow"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.11",
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Case",
    "symbolKind": "case",
    "title": "NSHapticFeedbackManager.PerformanceTime.now"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "macOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "case"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "now"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.appkit/documentation/AppKit": {
      "abstract": [
        {
          "text": "Construct and manage a graphical, event-driven user interface for your macOS app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit",
      "kind": "symbol",
      "role": "collection",
      "title": "AppKit",
      "type": "topic",
      "url": "/documentation/appkit"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSHapticFeedbackManager": {
      "abstract": [
        {
          "text": "An object that provides access to the haptic feedback management attributes on a system with a Force Touch trackpad.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSHapticFeedbackManager"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSHapticFeedbackManager",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSHapticFeedbackManager"
        }
      ],
      "role": "symbol",
      "title": "NSHapticFeedbackManager",
      "type": "topic",
      "url": "/documentation/appkit/nshapticfeedbackmanager"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSHapticFeedbackManager/PerformanceTime": {
      "abstract": [
        {
          "text": "A time at which to provide haptic feedback to the user.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "PerformanceTime"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSHapticFeedbackManager/PerformanceTime",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PerformanceTime"
        }
      ],
      "role": "symbol",
      "title": "NSHapticFeedbackManager.PerformanceTime",
      "type": "topic",
      "url": "/documentation/appkit/nshapticfeedbackmanager/performancetime"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSHapticFeedbackManager/PerformanceTime/default": {
      "abstract": [
        {
          "text": "Allows the system to choose the most appropriate time for feedback to be provided. Currently, this is the next time the screen is updated.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "`default`"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSHapticFeedbackManager/PerformanceTime/default",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSHapticFeedbackPerformanceTimeDefault"
        }
      ],
      "role": "symbol",
      "title": "NSHapticFeedbackManager.PerformanceTime.default",
      "type": "topic",
      "url": "/documentation/appkit/nshapticfeedbackmanager/performancetime/default"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSHapticFeedbackManager/PerformanceTime/drawCompleted": {
      "abstract": [
        {
          "text": "Instructs the system to provide haptic feedback to the user the next time the screen is updated.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "drawCompleted"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSHapticFeedbackManager/PerformanceTime/drawCompleted",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSHapticFeedbackPerformanceTimeDrawCompleted"
        }
      ],
      "role": "symbol",
      "title": "NSHapticFeedbackManager.PerformanceTime.drawCompleted",
      "type": "topic",
      "url": "/documentation/appkit/nshapticfeedbackmanager/performancetime/drawcompleted"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSHapticFeedbackManager/PerformanceTime/now": {
      "abstract": [
        {
          "text": "Instructs the system to provide immediate haptic feedback to the user, rather than waiting for synchronization to occur with something visual occurring on screen.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "now"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSHapticFeedbackManager/PerformanceTime/now",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSHapticFeedbackPerformanceTimeNow"
        }
      ],
      "role": "symbol",
      "title": "NSHapticFeedbackManager.PerformanceTime.now",
      "type": "topic",
      "url": "/documentation/appkit/nshapticfeedbackmanager/performancetime/now"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Constants",
      "generated": true,
      "identifiers": [
        "doc://com.apple.appkit/documentation/AppKit/NSHapticFeedbackManager/PerformanceTime/default",
        "doc://com.apple.appkit/documentation/AppKit/NSHapticFeedbackManager/PerformanceTime/drawCompleted"
      ],
      "title": "Constants"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.11",
              "name": "macOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration Case"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "NSHapticFeedbackPerformanceTimeNow"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "case"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSHapticFeedbackPerformanceTimeNow"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.appkit/documentation/AppKit",
                "doc://com.apple.appkit/documentation/AppKit/NSHapticFeedbackManager/PerformanceTime"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Constants",
              "generated": true,
              "identifiers": [
                "doc://com.apple.appkit/documentation/AppKit/NSHapticFeedbackManager/PerformanceTime/default",
                "doc://com.apple.appkit/documentation/AppKit/NSHapticFeedbackManager/PerformanceTime/drawCompleted"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "Mac Catalyst",
                  "macOS"
                ],
                "tokens": [
                  {
                    "kind": "identifier",
                    "text": "NSHapticFeedbackPerformanceTimeNow"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSHapticFeedbackManager/title",
          "value": "NSHapticFeedbackManager"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSHapticFeedbackManager/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSHapticFeedbackManager"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSHapticFeedbackManager/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSHapticFeedbackManager"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSHapticFeedbackManager~1PerformanceTime~1now/title",
          "value": "NSHapticFeedbackPerformanceTimeNow"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSHapticFeedbackManager~1PerformanceTime~1now/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSHapticFeedbackPerformanceTimeNow"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSHapticFeedbackManager~1PerformanceTime~1default/title",
          "value": "NSHapticFeedbackPerformanceTimeDefault"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSHapticFeedbackManager~1PerformanceTime~1default/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSHapticFeedbackPerformanceTimeDefault"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSHapticFeedbackManager~1PerformanceTime/title",
          "value": "NSHapticFeedbackPerformanceTime"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSHapticFeedbackManager~1PerformanceTime/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSHapticFeedbackPerformanceTime"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSHapticFeedbackManager~1PerformanceTime/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSHapticFeedbackPerformanceTime"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSHapticFeedbackManager~1PerformanceTime~1drawCompleted/title",
          "value": "NSHapticFeedbackPerformanceTimeDrawCompleted"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSHapticFeedbackManager~1PerformanceTime~1drawCompleted/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSHapticFeedbackPerformanceTimeDrawCompleted"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/appkit/nshapticfeedbackmanager/performancetime/now"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/appkit/nshapticfeedbackmanager/performancetime/now"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
