{
  "abstract": [
    {
      "text": "Returns whether any changes made to bound user default properties are saved immediately.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.appkit/documentation/AppKit",
        "doc://com.apple.appkit/documentation/AppKit/NSUserDefaultsController"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.appkit/documentation/AppKit/NSUserDefaultsController/appliesImmediately"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(cs)NSUserDefaultsController(py)appliesImmediately",
    "fragments": [
      {
        "kind": "keyword",
        "text": "var"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "appliesImmediately"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "s:Sb",
        "text": "Bool"
      }
    ],
    "modules": [
      {
        "name": "AppKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "appliesImmediately"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Instance Property",
    "symbolKind": "property",
    "title": "appliesImmediately"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "macOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "var"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "appliesImmediately"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:Sb",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:Sb",
              "text": "Bool"
            },
            {
              "kind": "text",
              "text": " { "
            },
            {
              "kind": "keyword",
              "text": "get"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "keyword",
              "text": "set"
            },
            {
              "kind": "text",
              "text": " }"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Default is ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/swift/true",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ".",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "This property is observable using key-value observing.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.appkit/documentation/AppKit": {
      "abstract": [
        {
          "text": "Construct and manage a graphical, event-driven user interface for your macOS app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit",
      "kind": "symbol",
      "role": "collection",
      "title": "AppKit",
      "type": "topic",
      "url": "/documentation/appkit"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSUserDefaultsController": {
      "abstract": [
        {
          "text": "A controller that accesses user preference information for your app from the user’s defaults database.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSUserDefaultsController"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSUserDefaultsController",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSUserDefaultsController"
        }
      ],
      "role": "symbol",
      "title": "NSUserDefaultsController",
      "type": "topic",
      "url": "/documentation/appkit/nsuserdefaultscontroller"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSUserDefaultsController/appliesImmediately": {
      "abstract": [
        {
          "text": "Returns whether any changes made to bound user default properties are saved immediately.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "appliesImmediately"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSUserDefaultsController/appliesImmediately",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "appliesImmediately"
        }
      ],
      "role": "symbol",
      "title": "appliesImmediately",
      "type": "topic",
      "url": "/documentation/appkit/nsuserdefaultscontroller/appliesimmediately"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSUserDefaultsController/defaults": {
      "abstract": [
        {
          "text": "Returns the instance of NSUserDefaults in use by the receiver.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "defaults"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSUserDefaults",
          "text": "UserDefaults"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSUserDefaultsController/defaults",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "defaults"
        }
      ],
      "role": "symbol",
      "title": "defaults",
      "type": "topic",
      "url": "/documentation/appkit/nsuserdefaultscontroller/defaults"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSUserDefaultsController/hasUnappliedChanges": {
      "abstract": [
        {
          "text": "Returns whether the receiver has user default values that have not been saved to NSUserDefaults.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "hasUnappliedChanges"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSUserDefaultsController/hasUnappliedChanges",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "hasUnappliedChanges"
        }
      ],
      "role": "symbol",
      "title": "hasUnappliedChanges",
      "type": "topic",
      "url": "/documentation/appkit/nsuserdefaultscontroller/hasunappliedchanges"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSUserDefaultsController/initialValues": {
      "abstract": [
        {
          "text": "Returns a dictionary containing the receiver’s initial default values.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "initialValues"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "keyword",
          "text": "Any"
        },
        {
          "kind": "text",
          "text": "]?"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSUserDefaultsController/initialValues",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "initialValues"
        }
      ],
      "role": "symbol",
      "title": "initialValues",
      "type": "topic",
      "url": "/documentation/appkit/nsuserdefaultscontroller/initialvalues"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSUserDefaultsController/revert(_:)": {
      "abstract": [
        {
          "text": "Causes the receiver to discard any unsaved changes to bound user default properties, restoring their previous values.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "revert"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "keyword",
          "text": "Any"
        },
        {
          "kind": "text",
          "text": "?)"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSUserDefaultsController/revert(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "revert:"
        }
      ],
      "role": "symbol",
      "title": "revert(_:)",
      "type": "topic",
      "url": "/documentation/appkit/nsuserdefaultscontroller/revert(_:)"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSUserDefaultsController/revertToInitialValues(_:)": {
      "abstract": [
        {
          "text": "Causes the receiver to discard all edits and replace the values of all the user default properties with any corresponding values in the ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.appkit/documentation/AppKit/NSUserDefaultsController/initialValues",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " dictionary.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "revertToInitialValues"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "keyword",
          "text": "Any"
        },
        {
          "kind": "text",
          "text": "?)"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSUserDefaultsController/revertToInitialValues(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "revertToInitialValues:"
        }
      ],
      "role": "symbol",
      "title": "revertToInitialValues(_:)",
      "type": "topic",
      "url": "/documentation/appkit/nsuserdefaultscontroller/reverttoinitialvalues(_:)"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSUserDefaultsController/save(_:)": {
      "abstract": [
        {
          "text": "Saves the values of the receiver’s user default properties.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "save"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "keyword",
          "text": "Any"
        },
        {
          "kind": "text",
          "text": "?)"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSUserDefaultsController/save(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "save:"
        }
      ],
      "role": "symbol",
      "title": "save(_:)",
      "type": "topic",
      "url": "/documentation/appkit/nsuserdefaultscontroller/save(_:)"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSUserDefaultsController/values": {
      "abstract": [
        {
          "text": "Returns a key value coding compliant object that is used to access the user default properties.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "values"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "keyword",
          "text": "Any"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSUserDefaultsController/values",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "values"
        }
      ],
      "role": "symbol",
      "title": "values",
      "type": "topic",
      "url": "/documentation/appkit/nsuserdefaultscontroller/values"
    },
    "doc://com.apple.documentation/documentation/swift/true": {
      "abstract": [
        {
          "text": "A true value.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/swift/true",
      "kind": "symbol",
      "role": "symbol",
      "title": "true",
      "type": "topic",
      "url": "/documentation/swift/true"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.externally.resolved.symbol/c:@T@BOOL": {
      "abstract": [
        {
          "text": "Type to represent a Boolean value.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:@T@BOOL",
      "kind": "symbol",
      "role": "symbol",
      "title": "BOOL",
      "type": "topic",
      "url": "/documentation/objectivec/bool"
    },
    "doc://com.externally.resolved.symbol/s:Sb": {
      "abstract": [
        {
          "text": "A value type whose instances are either `true` or `false`.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@frozen"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:Sb",
      "kind": "symbol",
      "role": "symbol",
      "title": "Bool",
      "type": "topic",
      "url": "/documentation/Swift/Bool"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Managing-user-defaults-values",
      "generated": true,
      "identifiers": [
        "doc://com.apple.appkit/documentation/AppKit/NSUserDefaultsController/defaults",
        "doc://com.apple.appkit/documentation/AppKit/NSUserDefaultsController/initialValues",
        "doc://com.apple.appkit/documentation/AppKit/NSUserDefaultsController/hasUnappliedChanges",
        "doc://com.apple.appkit/documentation/AppKit/NSUserDefaultsController/values",
        "doc://com.apple.appkit/documentation/AppKit/NSUserDefaultsController/revert(_:)",
        "doc://com.apple.appkit/documentation/AppKit/NSUserDefaultsController/revertToInitialValues(_:)",
        "doc://com.apple.appkit/documentation/AppKit/NSUserDefaultsController/save(_:)"
      ],
      "title": "Managing user defaults values"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "name": "macOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Instance Property"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "appliesImmediately"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "property"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "appliesImmediately"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.appkit/documentation/AppKit",
                "doc://com.apple.appkit/documentation/AppKit/NSUserDefaultsController"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Managing-user-defaults-values",
              "generated": true,
              "identifiers": [
                "doc://com.apple.appkit/documentation/AppKit/NSUserDefaultsController/defaults",
                "doc://com.apple.appkit/documentation/AppKit/NSUserDefaultsController/initialValues",
                "doc://com.apple.appkit/documentation/AppKit/NSUserDefaultsController/hasUnappliedChanges",
                "doc://com.apple.appkit/documentation/AppKit/NSUserDefaultsController/values",
                "doc://com.apple.appkit/documentation/AppKit/NSUserDefaultsController/revert(_:)",
                "doc://com.apple.appkit/documentation/AppKit/NSUserDefaultsController/revertToInitialValues(_:)",
                "doc://com.apple.appkit/documentation/AppKit/NSUserDefaultsController/save(_:)"
              ],
              "title": "Managing user defaults values"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "Mac Catalyst",
                  "macOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "@property"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:@T@BOOL",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@BOOL",
                    "text": "BOOL"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "appliesImmediately"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSUserDefaultsController/title",
          "value": "NSUserDefaultsController"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSUserDefaultsController/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSUserDefaultsController"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSUserDefaultsController/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSUserDefaultsController"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSUserDefaultsController~1hasUnappliedChanges/title",
          "value": "hasUnappliedChanges"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSUserDefaultsController~1hasUnappliedChanges/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "hasUnappliedChanges"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSUserDefaultsController~1revert(_:)/title",
          "value": "revert:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSUserDefaultsController~1revert(_:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "revert:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSUserDefaultsController~1revertToInitialValues(_:)/title",
          "value": "revertToInitialValues:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSUserDefaultsController~1revertToInitialValues(_:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "revertToInitialValues:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSUserDefaultsController~1save(_:)/title",
          "value": "save:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSUserDefaultsController~1save(_:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "save:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSUserDefaultsController~1appliesImmediately/title",
          "value": "appliesImmediately"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSUserDefaultsController~1appliesImmediately/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "appliesImmediately"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSUserDefaultsController~1values/title",
          "value": "values"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSUserDefaultsController~1values/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "values"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSUserDefaultsController~1initialValues/title",
          "value": "initialValues"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSUserDefaultsController~1initialValues/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "initialValues"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSUserDefaultsController~1defaults/title",
          "value": "defaults"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSUserDefaultsController~1defaults/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "defaults"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/appkit/nsuserdefaultscontroller/appliesimmediately"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/appkit/nsuserdefaultscontroller/appliesimmediately"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
