{
  "abstract": [
    {
      "text": "An option specifying that the default tracking mode should be used.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.metal/documentation/Metal",
        "doc://com.apple.metal/documentation/Metal/MTLResourceOptions"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "occ",
    "url": "doc://com.apple.metal/documentation/Metal/MTLResourceOptions/MTLResourceHazardTrackingModeDefault"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@MTLResourceOptions@MTLResourceHazardTrackingModeDefault",
    "fragments": [
      {
        "kind": "identifier",
        "text": "MTLResourceHazardTrackingModeDefault"
      }
    ],
    "modules": [
      {
        "name": "Metal"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "MTLResourceHazardTrackingModeDefault"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.1",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.13",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.0",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Enumeration Case",
    "symbolKind": "case",
    "title": "MTLResourceHazardTrackingModeDefault"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "occ"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "identifier",
              "text": "MTLResourceHazardTrackingModeDefault"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "For more information, see ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.metal/documentation/Metal/MTLHazardTrackingMode/default",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ".",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.metal/documentation/Metal": {
      "abstract": [
        {
          "text": "Render advanced 3D graphics and compute data in parallel with graphics processors.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal",
      "kind": "symbol",
      "role": "collection",
      "title": "Metal",
      "type": "topic",
      "url": "/documentation/metal"
    },
    "doc://com.apple.metal/documentation/Metal/MTLHazardTrackingMode/default": {
      "abstract": [
        {
          "text": "An option specifying that the default tracking mode should be used.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "`default`"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLHazardTrackingMode/default",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTLHazardTrackingModeDefault"
        }
      ],
      "role": "symbol",
      "title": "MTLHazardTrackingMode.default",
      "type": "topic",
      "url": "/documentation/metal/mtlhazardtrackingmode/default"
    },
    "doc://com.apple.metal/documentation/Metal/MTLResourceOptions": {
      "abstract": [
        {
          "text": "Optional arguments used to set the behavior of a resource.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MTLResourceOptions"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLResourceOptions",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTLResourceOptions"
        }
      ],
      "role": "symbol",
      "title": "MTLResourceOptions",
      "type": "topic",
      "url": "/documentation/metal/mtlresourceoptions"
    },
    "doc://com.apple.metal/documentation/Metal/MTLResourceOptions/MTLResourceHazardTrackingModeDefault": {
      "abstract": [
        {
          "text": "An option specifying that the default tracking mode should be used.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "MTLResourceHazardTrackingModeDefault"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLResourceOptions/MTLResourceHazardTrackingModeDefault",
      "kind": "symbol",
      "role": "symbol",
      "title": "MTLResourceHazardTrackingModeDefault",
      "type": "topic",
      "url": "/documentation/metal/mtlresourceoptions/mtlresourcehazardtrackingmodedefault"
    },
    "doc://com.apple.metal/documentation/Metal/MTLResourceOptions/hazardTrackingModeTracked": {
      "abstract": [
        {
          "text": "An option specifying that Metal prevents hazards when modifying this object’s contents.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "hazardTrackingModeTracked"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@MTLResourceOptions",
          "text": "MTLResourceOptions"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLResourceOptions/hazardTrackingModeTracked",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTLResourceHazardTrackingModeTracked"
        }
      ],
      "role": "symbol",
      "title": "hazardTrackingModeTracked",
      "type": "topic",
      "url": "/documentation/metal/mtlresourceoptions/hazardtrackingmodetracked"
    },
    "doc://com.apple.metal/documentation/Metal/MTLResourceOptions/hazardTrackingModeUntracked": {
      "abstract": [
        {
          "text": "An option specifying that the app must prevent hazards when modifying this object’s contents.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "hazardTrackingModeUntracked"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@MTLResourceOptions",
          "text": "MTLResourceOptions"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLResourceOptions/hazardTrackingModeUntracked",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTLResourceHazardTrackingModeUntracked"
        }
      ],
      "role": "symbol",
      "title": "hazardTrackingModeUntracked",
      "type": "topic",
      "url": "/documentation/metal/mtlresourceoptions/hazardtrackingmodeuntracked"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Specifying-Hazard-Tracking",
      "generated": true,
      "identifiers": [
        "doc://com.apple.metal/documentation/Metal/MTLResourceOptions/hazardTrackingModeTracked",
        "doc://com.apple.metal/documentation/Metal/MTLResourceOptions/hazardTrackingModeUntracked"
      ],
      "title": "Specifying Hazard Tracking"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLResourceOptions~1hazardTrackingModeUntracked/title",
          "value": "MTLResourceHazardTrackingModeUntracked"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLResourceOptions~1hazardTrackingModeUntracked/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLResourceHazardTrackingModeUntracked"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLHazardTrackingMode~1default/title",
          "value": "MTLHazardTrackingModeDefault"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLHazardTrackingMode~1default/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLHazardTrackingModeDefault"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLResourceOptions/title",
          "value": "MTLResourceOptions"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLResourceOptions/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLResourceOptions"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLResourceOptions/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLResourceOptions"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLResourceOptions~1hazardTrackingModeTracked/title",
          "value": "MTLResourceHazardTrackingModeTracked"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLResourceOptions~1hazardTrackingModeTracked/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLResourceHazardTrackingModeTracked"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/metal/mtlresourceoptions/mtlresourcehazardtrackingmodedefault"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
