{
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.mlcompute/documentation/MLCompute",
        "doc://com.apple.mlcompute/documentation/MLCompute/MLCPaddingType"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.mlcompute/documentation/MLCompute/MLCPaddingType/constant"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@MLCPaddingType@MLCPaddingTypeConstant",
    "fragments": [
      {
        "kind": "keyword",
        "text": "case"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "constant"
      }
    ],
    "modules": [
      {
        "name": "ML Compute"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "MLCPaddingTypeConstant"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "17.4",
        "introducedAt": "14.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "17.4",
        "introducedAt": "14.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "17.4",
        "introducedAt": "14.0",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "14.3",
        "introducedAt": "11.0",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "17.4",
        "introducedAt": "14.0",
        "name": "tvOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Case",
    "symbolKind": "case",
    "title": "MLCPaddingType.constant"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "case"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "constant"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.mlcompute/documentation/MLCompute": {
      "abstract": [
        {
          "text": "Accelerate training and validation of neural networks across the CPU and one or more GPUs.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "identifier": "doc://com.apple.mlcompute/documentation/MLCompute",
      "kind": "symbol",
      "role": "collection",
      "title": "ML Compute",
      "type": "topic",
      "url": "/documentation/mlcompute"
    },
    "doc://com.apple.mlcompute/documentation/MLCompute/MLCPaddingType": {
      "abstract": [
        {
          "text": "A padding type that you specify for a padding layer.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MLCPaddingType"
        }
      ],
      "identifier": "doc://com.apple.mlcompute/documentation/MLCompute/MLCPaddingType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MLCPaddingType"
        }
      ],
      "role": "symbol",
      "title": "MLCPaddingType",
      "type": "topic",
      "url": "/documentation/mlcompute/mlcpaddingtype"
    },
    "doc://com.apple.mlcompute/documentation/MLCompute/MLCPaddingType/constant": {
      "abstract": [],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "constant"
        }
      ],
      "identifier": "doc://com.apple.mlcompute/documentation/MLCompute/MLCPaddingType/constant",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MLCPaddingTypeConstant"
        }
      ],
      "role": "symbol",
      "title": "MLCPaddingType.constant",
      "type": "topic",
      "url": "/documentation/mlcompute/mlcpaddingtype/constant"
    },
    "doc://com.apple.mlcompute/documentation/MLCompute/MLCPaddingType/debugDescription": {
      "abstract": [
        {
          "text": "A textual description of the padding type, suitable for debugging.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "debugDescription"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.mlcompute/documentation/MLCompute/MLCPaddingType/debugDescription",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MLCPaddingTypeDebugDescription"
        }
      ],
      "role": "symbol",
      "title": "debugDescription",
      "type": "topic",
      "url": "/documentation/mlcompute/mlcpaddingtype/debugdescription"
    },
    "doc://com.apple.mlcompute/documentation/MLCompute/MLCPaddingType/reflect": {
      "abstract": [],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "reflect"
        }
      ],
      "identifier": "doc://com.apple.mlcompute/documentation/MLCompute/MLCPaddingType/reflect",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MLCPaddingTypeReflect"
        }
      ],
      "role": "symbol",
      "title": "MLCPaddingType.reflect",
      "type": "topic",
      "url": "/documentation/mlcompute/mlcpaddingtype/reflect"
    },
    "doc://com.apple.mlcompute/documentation/MLCompute/MLCPaddingType/symmetric": {
      "abstract": [],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "symmetric"
        }
      ],
      "identifier": "doc://com.apple.mlcompute/documentation/MLCompute/MLCPaddingType/symmetric",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MLCPaddingTypeSymmetric"
        }
      ],
      "role": "symbol",
      "title": "MLCPaddingType.symmetric",
      "type": "topic",
      "url": "/documentation/mlcompute/mlcpaddingtype/symmetric"
    },
    "doc://com.apple.mlcompute/documentation/MLCompute/MLCPaddingType/zero": {
      "abstract": [],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "zero"
        }
      ],
      "identifier": "doc://com.apple.mlcompute/documentation/MLCompute/MLCPaddingType/zero",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MLCPaddingTypeZero"
        }
      ],
      "role": "symbol",
      "title": "MLCPaddingType.zero",
      "type": "topic",
      "url": "/documentation/mlcompute/mlcpaddingtype/zero"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Enumeration-Cases",
      "generated": true,
      "identifiers": [
        "doc://com.apple.mlcompute/documentation/MLCompute/MLCPaddingType/zero",
        "doc://com.apple.mlcompute/documentation/MLCompute/MLCPaddingType/reflect",
        "doc://com.apple.mlcompute/documentation/MLCompute/MLCPaddingType/symmetric",
        "doc://com.apple.mlcompute/documentation/MLCompute/MLCPaddingType/debugDescription"
      ],
      "title": "Enumeration Cases"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "14.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "14.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "14.0",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "11.0",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "14.0",
              "name": "tvOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration Case"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "MLCPaddingTypeConstant"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "case"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MLCPaddingTypeConstant"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.mlcompute/documentation/MLCompute",
                "doc://com.apple.mlcompute/documentation/MLCompute/MLCPaddingType"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Enumeration-Cases",
              "generated": true,
              "identifiers": [
                "doc://com.apple.mlcompute/documentation/MLCompute/MLCPaddingType/zero",
                "doc://com.apple.mlcompute/documentation/MLCompute/MLCPaddingType/reflect",
                "doc://com.apple.mlcompute/documentation/MLCompute/MLCPaddingType/symmetric",
                "doc://com.apple.mlcompute/documentation/MLCompute/MLCPaddingType/debugDescription"
              ],
              "title": "Enumeration Cases"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS"
                ],
                "tokens": [
                  {
                    "kind": "identifier",
                    "text": "MLCPaddingTypeConstant"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "add",
          "path": "/deprecationSummary",
          "value": []
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCPaddingType~1zero/title",
          "value": "MLCPaddingTypeZero"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCPaddingType~1zero/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MLCPaddingTypeZero"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCPaddingType/title",
          "value": "MLCPaddingType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCPaddingType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MLCPaddingType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCPaddingType/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MLCPaddingType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCPaddingType~1debugDescription/title",
          "value": "MLCPaddingTypeDebugDescription"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCPaddingType~1debugDescription/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MLCPaddingTypeDebugDescription"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCPaddingType~1reflect/title",
          "value": "MLCPaddingTypeReflect"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCPaddingType~1reflect/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MLCPaddingTypeReflect"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCPaddingType~1constant/title",
          "value": "MLCPaddingTypeConstant"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCPaddingType~1constant/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MLCPaddingTypeConstant"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCPaddingType~1symmetric/title",
          "value": "MLCPaddingTypeSymmetric"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCPaddingType~1symmetric/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MLCPaddingTypeSymmetric"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/mlcompute/mlcpaddingtype/constant"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/mlcompute/mlcpaddingtype/constant"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
