{"abstract":[{"type":"text","text":"Called after a contact has been selected by the user."}],"identifier":{"url":"doc://com.apple.Contacts-UI/documentation/ContactsUI/CNContactPickerDelegate/contactPicker(_:didSelect:)-7vcyc","interfaceLanguage":"swift"},"sections":[],"seeAlsoSections":[{"generated":true,"identifiers":["doc://com.apple.Contacts-UI/documentation/ContactsUI/CNContactPickerDelegate/contactPicker(_:didSelect:)-1xfpt","doc://com.apple.Contacts-UI/documentation/ContactsUI/CNContactPickerDelegate/contactPicker(_:didSelect:)-5neeo","doc://com.apple.Contacts-UI/documentation/ContactsUI/CNContactPickerDelegate/contactPicker(_:didSelectContactProperties:)"],"anchor":"Responding-to-User-Selections","title":"Responding to User Selections"}],"metadata":{"symbolKind":"method","navigatorTitle":[{"text":"contactPicker:didSelectContact:","kind":"identifier"}],"roleHeading":"Instance Method","externalID":"c:objc(pl)CNContactPickerDelegate(im)contactPicker:didSelectContact:","modules":[{"name":"Contacts UI"}],"title":"contactPicker(_:didSelect:)","platforms":[{"beta":false,"deprecated":false,"introducedAt":"9.0","name":"iOS","unavailable":false},{"beta":false,"deprecated":false,"introducedAt":"9.0","name":"iPadOS","unavailable":false},{"beta":false,"deprecated":false,"introducedAt":"13.1","name":"Mac Catalyst","unavailable":false},{"beta":false,"deprecated":false,"introducedAt":"10.11","name":"macOS","unavailable":false},{"beta":false,"deprecated":false,"introducedAt":"1.0","name":"visionOS","unavailable":false}],"role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"contactPicker","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)CNContactPickerViewController","text":"CNContactPickerViewController","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"didSelect","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)CNContact","text":"CNContact","kind":"typeIdentifier"},{"text":")","kind":"text"}]},"hierarchy":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.Contacts-UI/documentation/ContactsUI","doc://com.apple.Contacts-UI/documentation/ContactsUI/CNContactPickerDelegate"]]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["/documentation/contactsui/cncontactpickerdelegate/contactpicker(_:didselect:)-7vcyc"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["/documentation/contactsui/cncontactpickerdelegate/contactpicker(_:didselect:)-7vcyc"]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"kind":"keyword","text":"optional"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"contactPicker"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"picker"},{"kind":"text","text":": "},{"identifier":"doc://com.apple.Contacts-UI/documentation/ContactsUI/CNContactPicker","kind":"typeIdentifier","text":"CNContactPicker","preciseIdentifier":"c:objc(cs)CNContactPicker"},{"kind":"text","text":", "},{"kind":"externalParam","text":"didSelect"},{"kind":"text","text":" "},{"kind":"internalParam","text":"contact"},{"kind":"text","text":": "},{"identifier":"doc://com.externally.resolved.symbol/c:objc(cs)CNContact","kind":"typeIdentifier","text":"CNContact","preciseIdentifier":"c:objc(cs)CNContact"},{"kind":"text","text":")"}],"platforms":["macOS"]},{"languages":["swift"],"tokens":[{"text":"optional","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"contactPicker","kind":"identifier"},{"text":"(","kind":"text"},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"picker","kind":"internalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)CNContactPickerViewController","identifier":"doc://com.apple.Contacts-UI/documentation/ContactsUI/CNContactPickerViewController","text":"CNContactPickerViewController","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"didSelect","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"contact","kind":"internalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)CNContact","identifier":"doc://com.externally.resolved.symbol/c:objc(cs)CNContact","text":"CNContact","kind":"typeIdentifier"},{"text":")","kind":"text"}],"platforms":["iOS","iPadOS","Mac Catalyst","visionOS"]}]},{"kind":"parameters","parameters":[{"content":[{"inlineContent":[{"text":"The contact picker where the selection was made.","type":"text"}],"type":"paragraph"}],"name":"picker"},{"content":[{"inlineContent":[{"type":"text","text":"The selected contact."}],"type":"paragraph"}],"name":"contact"}]},{"kind":"content","content":[{"type":"heading","text":"Discussion","level":2,"anchor":"discussion"},{"type":"paragraph","inlineContent":[{"type":"text","text":"This delegate method is called when the user selects a single contact."}]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"kind":"symbol","references":{"doc://com.apple.Contacts-UI/documentation/ContactsUI/CNContactPicker":{"navigatorTitle":[{"text":"CNContactPicker","kind":"identifier"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"CNContactPicker","kind":"identifier"}],"title":"CNContactPicker","kind":"symbol","abstract":[{"text":"A popover-based interface for selecting a contact.","type":"text"}],"role":"symbol","type":"topic","identifier":"doc://com.apple.Contacts-UI/documentation/ContactsUI/CNContactPicker","url":"/documentation/contactsui/cncontactpicker"},"doc://com.apple.Contacts-UI/documentation/ContactsUI":{"title":"Contacts UI","kind":"symbol","abstract":[{"text":"Provide an interface that allows people to display information about their","type":"text"},{"text":" ","type":"text"},{"text":"contacts.","type":"text"}],"role":"collection","type":"topic","identifier":"doc://com.apple.Contacts-UI/documentation/ContactsUI","url":"/documentation/contactsui"},"doc://com.apple.Contacts-UI/documentation/ContactsUI/CNContactPickerDelegate/contactPicker(_:didSelectContactProperties:)":{"navigatorTitle":[{"text":"contactPicker:didSelectContactProperties:","kind":"identifier"}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"contactPicker","kind":"identifier"},{"text":"(","kind":"text"},{"text":"CNContactPickerViewController","preciseIdentifier":"c:objc(cs)CNContactPickerViewController","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"didSelectContactProperties","kind":"externalParam"},{"text":": [","kind":"text"},{"text":"CNContactProperty","preciseIdentifier":"c:objc(cs)CNContactProperty","kind":"typeIdentifier"},{"text":"])","kind":"text"}],"title":"contactPicker(_:didSelectContactProperties:)","kind":"symbol","abstract":[{"text":"Called after contact properties have been selected by the user.","type":"text"}],"role":"symbol","type":"topic","identifier":"doc://com.apple.Contacts-UI/documentation/ContactsUI/CNContactPickerDelegate/contactPicker(_:didSelectContactProperties:)","url":"/documentation/contactsui/cncontactpickerdelegate/contactpicker(_:didselectcontactproperties:)"},"doc://com.apple.Contacts-UI/documentation/ContactsUI/CNContactPickerViewController":{"navigatorTitle":[{"kind":"identifier","text":"CNContactPickerViewController"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"CNContactPickerViewController"}],"title":"CNContactPickerViewController","kind":"symbol","abstract":[{"text":"A view controller that displays an interface for picking contacts.","type":"text"}],"role":"symbol","type":"topic","identifier":"doc://com.apple.Contacts-UI/documentation/ContactsUI/CNContactPickerViewController","url":"/documentation/contactsui/cncontactpickerviewcontroller"},"doc://com.apple.Contacts-UI/documentation/ContactsUI/CNContactPickerDelegate/contactPicker(_:didSelect:)-1xfpt":{"navigatorTitle":[{"text":"contactPicker:didSelectContactProperty:","kind":"identifier"}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"contactPicker"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"CNContactPickerViewController","preciseIdentifier":"c:objc(cs)CNContactPickerViewController"},{"kind":"text","text":", "},{"kind":"externalParam","text":"didSelect"},{"text":": ","kind":"text"},{"text":"CNContactProperty","preciseIdentifier":"c:objc(cs)CNContactProperty","kind":"typeIdentifier"},{"text":")","kind":"text"}],"title":"contactPicker(_:didSelect:)","kind":"symbol","abstract":[{"text":"Called when a property of the contact has been selected by the user.","type":"text"}],"role":"symbol","type":"topic","identifier":"doc://com.apple.Contacts-UI/documentation/ContactsUI/CNContactPickerDelegate/contactPicker(_:didSelect:)-1xfpt","url":"/documentation/contactsui/cncontactpickerdelegate/contactpicker(_:didselect:)-1xfpt"},"doc://com.apple.documentation/documentation/technologies":{"title":"Technologies","kind":"technologies","abstract":[{"text":"","type":"text"}],"role":"overview","type":"topic","identifier":"doc://com.apple.documentation/documentation/technologies","url":"/documentation/technologies"},"doc://com.externally.resolved.symbol/c:objc(cs)CNContact":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"CNContact"}],"title":"CNContact","kind":"symbol","abstract":[{"text":"An immutable object that stores information about a single contact, such as the contact’s first name, phone numbers, and addresses.","type":"text"}],"role":"symbol","type":"topic","identifier":"doc://com.externally.resolved.symbol/c:objc(cs)CNContact","url":"/documentation/Contacts/CNContact"},"doc://com.apple.Contacts-UI/documentation/ContactsUI/CNContactPickerDelegate":{"navigatorTitle":[{"kind":"identifier","text":"CNContactPickerDelegate"}],"fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"CNContactPickerDelegate"}],"title":"CNContactPickerDelegate","kind":"symbol","abstract":[{"text":"The methods that you implement to respond to contact-picker user events.","type":"text"}],"role":"symbol","type":"topic","identifier":"doc://com.apple.Contacts-UI/documentation/ContactsUI/CNContactPickerDelegate","url":"/documentation/contactsui/cncontactpickerdelegate"},"doc://com.apple.Contacts-UI/documentation/ContactsUI/CNContactPickerDelegate/contactPicker(_:didSelect:)-7vcyc":{"navigatorTitle":[{"text":"contactPicker:didSelectContact:","kind":"identifier"}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"contactPicker"},{"kind":"text","text":"("},{"preciseIdentifier":"c:objc(cs)CNContactPickerViewController","text":"CNContactPickerViewController","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"didSelect","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"CNContact","preciseIdentifier":"c:objc(cs)CNContact","kind":"typeIdentifier"},{"text":")","kind":"text"}],"title":"contactPicker(_:didSelect:)","kind":"symbol","abstract":[{"text":"Called after a contact has been selected by the user.","type":"text"}],"role":"symbol","type":"topic","identifier":"doc://com.apple.Contacts-UI/documentation/ContactsUI/CNContactPickerDelegate/contactPicker(_:didSelect:)-7vcyc","url":"/documentation/contactsui/cncontactpickerdelegate/contactpicker(_:didselect:)-7vcyc"},"doc://com.apple.Contacts-UI/documentation/ContactsUI/CNContactPickerDelegate/contactPicker(_:didSelect:)-5neeo":{"navigatorTitle":[{"text":"contactPicker:didSelectContacts:","kind":"identifier"}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"contactPicker","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","text":"CNContactPickerViewController","preciseIdentifier":"c:objc(cs)CNContactPickerViewController"},{"kind":"text","text":", "},{"kind":"externalParam","text":"didSelect"},{"text":": [","kind":"text"},{"text":"CNContact","preciseIdentifier":"c:objc(cs)CNContact","kind":"typeIdentifier"},{"text":"])","kind":"text"}],"title":"contactPicker(_:didSelect:)","kind":"symbol","abstract":[{"text":"Called after contacts have been selected by the user.","type":"text"}],"role":"symbol","type":"topic","identifier":"doc://com.apple.Contacts-UI/documentation/ContactsUI/CNContactPickerDelegate/contactPicker(_:didSelect:)-5neeo","url":"/documentation/contactsui/cncontactpickerdelegate/contactpicker(_:didselect:)-5neeo"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"/identifier/interfaceLanguage"},{"op":"replace","path":"/metadata/platforms","value":[{"introducedAt":"9.0","name":"iOS","unavailable":false,"beta":false,"deprecated":false},{"introducedAt":"9.0","unavailable":false,"name":"iPadOS","beta":false,"deprecated":false},{"introducedAt":"13.1","unavailable":false,"name":"Mac Catalyst","beta":false,"deprecated":false},{"introducedAt":"10.11","unavailable":false,"name":"macOS","beta":false,"deprecated":false},{"unavailable":false,"deprecated":false,"beta":false,"name":"visionOS","introducedAt":"1.0"}]},{"op":"replace","path":"/metadata/roleHeading","value":"Instance Method"},{"op":"replace","path":"/metadata/title","value":"contactPicker:didSelectContact:"},{"op":"replace","path":"/metadata/symbolKind","value":"method"},{"op":"replace","path":"/metadata/fragments","value":[{"text":"- ","kind":"text"},{"text":"contactPicker:didSelectContact:","kind":"identifier"}]},{"op":"replace","path":"/hierarchy","value":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.Contacts-UI/documentation/ContactsUI","doc://com.apple.Contacts-UI/documentation/ContactsUI/CNContactPickerDelegate"]]}},{"op":"add","path":"/topicSections","value":null},{"op":"add","path":"/relationshipsSections","value":null},{"op":"replace","path":"/seeAlsoSections","value":[{"identifiers":["doc://com.apple.Contacts-UI/documentation/ContactsUI/CNContactPickerDelegate/contactPicker(_:didSelect:)-1xfpt","doc://com.apple.Contacts-UI/documentation/ContactsUI/CNContactPickerDelegate/contactPicker(_:didSelect:)-5neeo","doc://com.apple.Contacts-UI/documentation/ContactsUI/CNContactPickerDelegate/contactPicker(_:didSelectContactProperties:)"],"title":"Responding to User Selections","anchor":"Responding-to-User-Selections","generated":true}]},{"op":"replace","path":"/primaryContentSections/0","value":{"declarations":[{"tokens":[{"kind":"text","text":"- ("},{"preciseIdentifier":"c:v","kind":"typeIdentifier","text":"void"},{"kind":"text","text":") "},{"kind":"identifier","text":"contactPicker:"},{"kind":"text","text":"("},{"preciseIdentifier":"c:objc(cs)CNContactPicker","kind":"typeIdentifier","text":"CNContactPicker","identifier":"doc://com.apple.Contacts-UI/documentation/ContactsUI/CNContactPicker"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"picker"},{"kind":"text","text":" "},{"kind":"identifier","text":"didSelectContact:"},{"kind":"text","text":"("},{"preciseIdentifier":"c:objc(cs)CNContact","kind":"typeIdentifier","text":"CNContact","identifier":"doc://com.externally.resolved.symbol/c:objc(cs)CNContact"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"contact"},{"kind":"text","text":";"}],"platforms":["macOS"],"languages":["occ"]},{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","preciseIdentifier":"c:v","text":"void"},{"kind":"text","text":") "},{"kind":"identifier","text":"contactPicker:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","identifier":"doc://com.apple.Contacts-UI/documentation/ContactsUI/CNContactPickerViewController","preciseIdentifier":"c:objc(cs)CNContactPickerViewController","text":"CNContactPickerViewController"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"picker"},{"kind":"text","text":" "},{"kind":"identifier","text":"didSelectContact:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","identifier":"doc://com.externally.resolved.symbol/c:objc(cs)CNContact","preciseIdentifier":"c:objc(cs)CNContact","text":"CNContact"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"contact"},{"kind":"text","text":";"}],"platforms":["iOS","iPadOS","Mac Catalyst","visionOS"],"languages":["occ"]}],"kind":"declarations"}},{"path":"/primaryContentSections/1","value":{"kind":"parameters","parameters":[{"name":"picker","content":[{"inlineContent":[{"text":"The contact picker where the selection was made.","type":"text"}],"type":"paragraph"}]},{"name":"contact","content":[{"type":"paragraph","inlineContent":[{"text":"The selected contact.","type":"text"}]}]}]},"op":"replace"},{"op":"replace","path":"/references/doc:~1~1com.apple.Contacts-UI~1documentation~1ContactsUI~1CNContactPicker/title","value":"CNContactPicker"},{"op":"replace","path":"/references/doc:~1~1com.apple.Contacts-UI~1documentation~1ContactsUI~1CNContactPicker/fragments","value":[{"kind":"identifier","text":"CNContactPicker"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.Contacts-UI~1documentation~1ContactsUI~1CNContactPicker/navigatorTitle","value":[{"text":"CNContactPicker","kind":"identifier"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.Contacts-UI~1documentation~1ContactsUI~1CNContactPickerDelegate~1contactPicker(_:didSelectContactProperties:)/title","value":"contactPicker:didSelectContactProperties:"},{"op":"replace","path":"/references/doc:~1~1com.apple.Contacts-UI~1documentation~1ContactsUI~1CNContactPickerDelegate~1contactPicker(_:didSelectContactProperties:)/fragments","value":[{"text":"- ","kind":"text"},{"text":"contactPicker:didSelectContactProperties:","kind":"identifier"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.Contacts-UI~1documentation~1ContactsUI~1CNContactPickerViewController/title","value":"CNContactPickerViewController"},{"op":"replace","path":"/references/doc:~1~1com.apple.Contacts-UI~1documentation~1ContactsUI~1CNContactPickerViewController/fragments","value":[{"kind":"identifier","text":"CNContactPickerViewController"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.Contacts-UI~1documentation~1ContactsUI~1CNContactPickerViewController/navigatorTitle","value":[{"kind":"identifier","text":"CNContactPickerViewController"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.Contacts-UI~1documentation~1ContactsUI~1CNContactPickerDelegate~1contactPicker(_:didSelect:)-1xfpt/title","value":"contactPicker:didSelectContactProperty:"},{"op":"replace","path":"/references/doc:~1~1com.apple.Contacts-UI~1documentation~1ContactsUI~1CNContactPickerDelegate~1contactPicker(_:didSelect:)-1xfpt/fragments","value":[{"text":"- ","kind":"text"},{"text":"contactPicker:didSelectContactProperty:","kind":"identifier"}]},{"op":"replace","path":"/references/doc:~1~1com.externally.resolved.symbol~1c:objc(cs)CNContact/fragments","value":[{"text":"@interface","kind":"keyword"},{"text":" ","kind":"text"},{"text":"CNContact","kind":"identifier"},{"text":" : ","kind":"text"},{"text":"NSObject","preciseIdentifier":"c:objc(cs)NSObject","kind":"typeIdentifier"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.Contacts-UI~1documentation~1ContactsUI~1CNContactPickerDelegate/title","value":"CNContactPickerDelegate"},{"op":"replace","path":"/references/doc:~1~1com.apple.Contacts-UI~1documentation~1ContactsUI~1CNContactPickerDelegate/fragments","value":[{"text":"CNContactPickerDelegate","kind":"identifier"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.Contacts-UI~1documentation~1ContactsUI~1CNContactPickerDelegate/navigatorTitle","value":[{"text":"CNContactPickerDelegate","kind":"identifier"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.Contacts-UI~1documentation~1ContactsUI~1CNContactPickerDelegate~1contactPicker(_:didSelect:)-7vcyc/title","value":"contactPicker:didSelectContact:"},{"op":"replace","path":"/references/doc:~1~1com.apple.Contacts-UI~1documentation~1ContactsUI~1CNContactPickerDelegate~1contactPicker(_:didSelect:)-7vcyc/fragments","value":[{"text":"- ","kind":"text"},{"text":"contactPicker:didSelectContact:","kind":"identifier"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.Contacts-UI~1documentation~1ContactsUI~1CNContactPickerDelegate~1contactPicker(_:didSelect:)-5neeo/title","value":"contactPicker:didSelectContacts:"},{"op":"replace","path":"/references/doc:~1~1com.apple.Contacts-UI~1documentation~1ContactsUI~1CNContactPickerDelegate~1contactPicker(_:didSelect:)-5neeo/fragments","value":[{"text":"- ","kind":"text"},{"text":"contactPicker:didSelectContacts:","kind":"identifier"}]}]}],"legalNotices":{"copyright":"Copyright &copy; 2025 Apple Inc. All rights reserved.","termsOfUse":"https://www.apple.com/legal/internet-services/terms/site.html","privacyPolicy":"https://www.apple.com/privacy/privacy-policy"}}