{"metadata":{"roleHeading":"Instance Method","navigatorTitle":[{"text":"contactPicker:didSelectContacts:","kind":"identifier"}],"platforms":[{"unavailable":false,"introducedAt":"9.0","deprecated":false,"beta":false,"name":"iOS"},{"unavailable":false,"introducedAt":"9.0","deprecated":false,"beta":false,"name":"iPadOS"},{"unavailable":false,"introducedAt":"13.1","deprecated":false,"beta":false,"name":"Mac Catalyst"},{"unavailable":false,"introducedAt":"1.0","deprecated":false,"beta":false,"name":"visionOS"}],"symbolKind":"method","modules":[{"name":"Contacts UI"}],"role":"symbol","title":"contactPicker(_:didSelect:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"contactPicker","kind":"identifier"},{"text":"(","kind":"text"},{"text":"CNContactPickerViewController","preciseIdentifier":"c:objc(cs)CNContactPickerViewController","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"didSelect","kind":"externalParam"},{"text":": [","kind":"text"},{"preciseIdentifier":"c:objc(cs)CNContact","text":"CNContact","kind":"typeIdentifier"},{"text":"])","kind":"text"}],"externalID":"c:objc(pl)CNContactPickerDelegate(im)contactPicker:didSelectContacts:"},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS","iPadOS","Mac Catalyst","visionOS"],"languages":["swift"],"tokens":[{"kind":"keyword","text":"optional"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"contactPicker"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"picker"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)CNContactPickerViewController","text":"CNContactPickerViewController","identifier":"doc://com.apple.Contacts-UI/documentation/ContactsUI/CNContactPickerViewController"},{"kind":"text","text":", "},{"kind":"externalParam","text":"didSelect"},{"kind":"text","text":" "},{"kind":"internalParam","text":"contacts"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)CNContact","text":"CNContact","identifier":"doc://com.externally.resolved.symbol/c:objc(cs)CNContact"},{"kind":"text","text":"])"}]}]},{"parameters":[{"name":"picker","content":[{"inlineContent":[{"text":"The contact picker where the selection was made.","type":"text"}],"type":"paragraph"}]},{"name":"contacts","content":[{"inlineContent":[{"text":"The selected contacts.","type":"text"}],"type":"paragraph"}]}],"kind":"parameters"},{"kind":"content","content":[{"text":"Discussion","type":"heading","anchor":"discussion","level":2},{"inlineContent":[{"text":"This delegate method is called when the user selects more than one contact. Implementing","type":"text"},{"text":" ","type":"text"},{"text":"this method configures the picker for multi-selection.","type":"text"}],"type":"paragraph"}]}],"seeAlsoSections":[{"identifiers":["doc://com.apple.Contacts-UI/documentation/ContactsUI/CNContactPickerDelegate/contactPicker(_:didSelect:)-7vcyc","doc://com.apple.Contacts-UI/documentation/ContactsUI/CNContactPickerDelegate/contactPicker(_:didSelect:)-1xfpt","doc://com.apple.Contacts-UI/documentation/ContactsUI/CNContactPickerDelegate/contactPicker(_:didSelectContactProperties:)"],"generated":true,"title":"Responding to User Selections","anchor":"Responding-to-User-Selections"}],"sections":[],"schemaVersion":{"major":0,"minor":3,"patch":0},"variants":[{"paths":["/documentation/contactsui/cncontactpickerdelegate/contactpicker(_:didselect:)-5neeo"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["/documentation/contactsui/cncontactpickerdelegate/contactpicker(_:didselect:)-5neeo"],"traits":[{"interfaceLanguage":"occ"}]}],"kind":"symbol","hierarchy":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.Contacts-UI/documentation/ContactsUI","doc://com.apple.Contacts-UI/documentation/ContactsUI/CNContactPickerDelegate"]]},"abstract":[{"type":"text","text":"Called after contacts have been selected by the user."}],"identifier":{"url":"doc://com.apple.Contacts-UI/documentation/ContactsUI/CNContactPickerDelegate/contactPicker(_:didSelect:)-5neeo","interfaceLanguage":"swift"},"references":{"doc://com.externally.resolved.symbol/c:objc(cs)CNContact":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"CNContact"}],"title":"CNContact","kind":"symbol","abstract":[{"text":"An immutable object that stores information about a single contact, such as the contact’s first name, phone numbers, and addresses.","type":"text"}],"role":"symbol","type":"topic","identifier":"doc://com.externally.resolved.symbol/c:objc(cs)CNContact","url":"/documentation/Contacts/CNContact"},"doc://com.apple.Contacts-UI/documentation/ContactsUI":{"title":"Contacts UI","kind":"symbol","abstract":[{"text":"Provide an interface that allows people to display information about their","type":"text"},{"text":" ","type":"text"},{"text":"contacts.","type":"text"}],"role":"collection","type":"topic","identifier":"doc://com.apple.Contacts-UI/documentation/ContactsUI","url":"/documentation/contactsui"},"doc://com.apple.Contacts-UI/documentation/ContactsUI/CNContactPickerDelegate/contactPicker(_:didSelect:)-7vcyc":{"navigatorTitle":[{"text":"contactPicker:didSelectContact:","kind":"identifier"}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"contactPicker"},{"kind":"text","text":"("},{"preciseIdentifier":"c:objc(cs)CNContactPickerViewController","text":"CNContactPickerViewController","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"didSelect","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"CNContact","preciseIdentifier":"c:objc(cs)CNContact","kind":"typeIdentifier"},{"text":")","kind":"text"}],"title":"contactPicker(_:didSelect:)","kind":"symbol","abstract":[{"text":"Called after a contact has been selected by the user.","type":"text"}],"role":"symbol","type":"topic","identifier":"doc://com.apple.Contacts-UI/documentation/ContactsUI/CNContactPickerDelegate/contactPicker(_:didSelect:)-7vcyc","url":"/documentation/contactsui/cncontactpickerdelegate/contactpicker(_:didselect:)-7vcyc"},"doc://com.apple.Contacts-UI/documentation/ContactsUI/CNContactPickerDelegate/contactPicker(_:didSelect:)-5neeo":{"navigatorTitle":[{"text":"contactPicker:didSelectContacts:","kind":"identifier"}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"contactPicker","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","text":"CNContactPickerViewController","preciseIdentifier":"c:objc(cs)CNContactPickerViewController"},{"kind":"text","text":", "},{"kind":"externalParam","text":"didSelect"},{"text":": [","kind":"text"},{"text":"CNContact","preciseIdentifier":"c:objc(cs)CNContact","kind":"typeIdentifier"},{"text":"])","kind":"text"}],"title":"contactPicker(_:didSelect:)","kind":"symbol","abstract":[{"text":"Called after contacts have been selected by the user.","type":"text"}],"role":"symbol","type":"topic","identifier":"doc://com.apple.Contacts-UI/documentation/ContactsUI/CNContactPickerDelegate/contactPicker(_:didSelect:)-5neeo","url":"/documentation/contactsui/cncontactpickerdelegate/contactpicker(_:didselect:)-5neeo"},"doc://com.apple.Contacts-UI/documentation/ContactsUI/CNContactPickerDelegate":{"navigatorTitle":[{"kind":"identifier","text":"CNContactPickerDelegate"}],"fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"CNContactPickerDelegate"}],"title":"CNContactPickerDelegate","kind":"symbol","abstract":[{"text":"The methods that you implement to respond to contact-picker user events.","type":"text"}],"role":"symbol","type":"topic","identifier":"doc://com.apple.Contacts-UI/documentation/ContactsUI/CNContactPickerDelegate","url":"/documentation/contactsui/cncontactpickerdelegate"},"doc://com.apple.Contacts-UI/documentation/ContactsUI/CNContactPickerViewController":{"navigatorTitle":[{"kind":"identifier","text":"CNContactPickerViewController"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"CNContactPickerViewController"}],"title":"CNContactPickerViewController","kind":"symbol","abstract":[{"text":"A view controller that displays an interface for picking contacts.","type":"text"}],"role":"symbol","type":"topic","identifier":"doc://com.apple.Contacts-UI/documentation/ContactsUI/CNContactPickerViewController","url":"/documentation/contactsui/cncontactpickerviewcontroller"},"doc://com.apple.documentation/documentation/technologies":{"title":"Technologies","kind":"technologies","abstract":[{"text":"","type":"text"}],"role":"overview","type":"topic","identifier":"doc://com.apple.documentation/documentation/technologies","url":"/documentation/technologies"},"doc://com.apple.Contacts-UI/documentation/ContactsUI/CNContactPickerDelegate/contactPicker(_:didSelectContactProperties:)":{"navigatorTitle":[{"text":"contactPicker:didSelectContactProperties:","kind":"identifier"}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"contactPicker","kind":"identifier"},{"text":"(","kind":"text"},{"text":"CNContactPickerViewController","preciseIdentifier":"c:objc(cs)CNContactPickerViewController","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"didSelectContactProperties","kind":"externalParam"},{"text":": [","kind":"text"},{"text":"CNContactProperty","preciseIdentifier":"c:objc(cs)CNContactProperty","kind":"typeIdentifier"},{"text":"])","kind":"text"}],"title":"contactPicker(_:didSelectContactProperties:)","kind":"symbol","abstract":[{"text":"Called after contact properties have been selected by the user.","type":"text"}],"role":"symbol","type":"topic","identifier":"doc://com.apple.Contacts-UI/documentation/ContactsUI/CNContactPickerDelegate/contactPicker(_:didSelectContactProperties:)","url":"/documentation/contactsui/cncontactpickerdelegate/contactpicker(_:didselectcontactproperties:)"},"doc://com.apple.Contacts-UI/documentation/ContactsUI/CNContactPickerDelegate/contactPicker(_:didSelect:)-1xfpt":{"navigatorTitle":[{"text":"contactPicker:didSelectContactProperty:","kind":"identifier"}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"contactPicker"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"CNContactPickerViewController","preciseIdentifier":"c:objc(cs)CNContactPickerViewController"},{"kind":"text","text":", "},{"kind":"externalParam","text":"didSelect"},{"text":": ","kind":"text"},{"text":"CNContactProperty","preciseIdentifier":"c:objc(cs)CNContactProperty","kind":"typeIdentifier"},{"text":")","kind":"text"}],"title":"contactPicker(_:didSelect:)","kind":"symbol","abstract":[{"text":"Called when a property of the contact has been selected by the user.","type":"text"}],"role":"symbol","type":"topic","identifier":"doc://com.apple.Contacts-UI/documentation/ContactsUI/CNContactPickerDelegate/contactPicker(_:didSelect:)-1xfpt","url":"/documentation/contactsui/cncontactpickerdelegate/contactpicker(_:didselect:)-1xfpt"}},"variantOverrides":[{"patch":[{"value":"occ","path":"/identifier/interfaceLanguage","op":"replace"},{"value":[{"unavailable":false,"deprecated":false,"introducedAt":"9.0","beta":false,"name":"iOS"},{"unavailable":false,"deprecated":false,"introducedAt":"9.0","beta":false,"name":"iPadOS"},{"unavailable":false,"deprecated":false,"introducedAt":"13.1","beta":false,"name":"Mac Catalyst"},{"unavailable":false,"deprecated":false,"introducedAt":"1.0","beta":false,"name":"visionOS"}],"path":"/metadata/platforms","op":"replace"},{"value":"Instance Method","path":"/metadata/roleHeading","op":"replace"},{"value":"contactPicker:didSelectContacts:","path":"/metadata/title","op":"replace"},{"value":"method","path":"/metadata/symbolKind","op":"replace"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"contactPicker:didSelectContacts:"}],"path":"/metadata/fragments","op":"replace"},{"value":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.Contacts-UI/documentation/ContactsUI","doc://com.apple.Contacts-UI/documentation/ContactsUI/CNContactPickerDelegate"]]},"path":"/hierarchy","op":"replace"},{"value":null,"path":"/topicSections","op":"add"},{"value":null,"path":"/relationshipsSections","op":"add"},{"path":"/seeAlsoSections","value":[{"anchor":"Responding-to-User-Selections","generated":true,"title":"Responding to User Selections","identifiers":["doc://com.apple.Contacts-UI/documentation/ContactsUI/CNContactPickerDelegate/contactPicker(_:didSelect:)-7vcyc","doc://com.apple.Contacts-UI/documentation/ContactsUI/CNContactPickerDelegate/contactPicker(_:didSelect:)-1xfpt","doc://com.apple.Contacts-UI/documentation/ContactsUI/CNContactPickerDelegate/contactPicker(_:didSelectContactProperties:)"]}],"op":"replace"},{"path":"/primaryContentSections/0","value":{"declarations":[{"tokens":[{"text":"- (","kind":"text"},{"text":"void","kind":"typeIdentifier","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"kind":"identifier","text":"contactPicker:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","identifier":"doc://com.apple.Contacts-UI/documentation/ContactsUI/CNContactPickerViewController","text":"CNContactPickerViewController","preciseIdentifier":"c:objc(cs)CNContactPickerViewController"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"picker"},{"kind":"text","text":" "},{"kind":"identifier","text":"didSelectContacts:"},{"kind":"text","text":"("},{"text":"NSArray<CNContact *>","preciseIdentifier":"c:Q$objc(cs)NSArray","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"contacts","kind":"internalParam"},{"text":";","kind":"text"}],"languages":["occ"],"platforms":["iOS","iPadOS","Mac Catalyst","visionOS"]}],"kind":"declarations"},"op":"replace"},{"path":"/primaryContentSections/1","value":{"parameters":[{"content":[{"inlineContent":[{"type":"text","text":"The contact picker where the selection was made."}],"type":"paragraph"}],"name":"picker"},{"content":[{"inlineContent":[{"text":"The selected contacts.","type":"text"}],"type":"paragraph"}],"name":"contacts"}],"kind":"parameters"},"op":"replace"},{"path":"/references/doc:~1~1com.externally.resolved.symbol~1c:objc(cs)CNContact/fragments","value":[{"text":"@interface","kind":"keyword"},{"text":" ","kind":"text"},{"text":"CNContact","kind":"identifier"},{"text":" : ","kind":"text"},{"text":"NSObject","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSObject"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.Contacts-UI~1documentation~1ContactsUI~1CNContactPickerDelegate~1contactPicker(_:didSelect:)-7vcyc/title","value":"contactPicker:didSelectContact:","op":"replace"},{"path":"/references/doc:~1~1com.apple.Contacts-UI~1documentation~1ContactsUI~1CNContactPickerDelegate~1contactPicker(_:didSelect:)-7vcyc/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"contactPicker:didSelectContact:"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.Contacts-UI~1documentation~1ContactsUI~1CNContactPickerDelegate~1contactPicker(_:didSelect:)-5neeo/title","value":"contactPicker:didSelectContacts:","op":"replace"},{"path":"/references/doc:~1~1com.apple.Contacts-UI~1documentation~1ContactsUI~1CNContactPickerDelegate~1contactPicker(_:didSelect:)-5neeo/fragments","value":[{"text":"- ","kind":"text"},{"text":"contactPicker:didSelectContacts:","kind":"identifier"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.Contacts-UI~1documentation~1ContactsUI~1CNContactPickerDelegate/title","value":"CNContactPickerDelegate","op":"replace"},{"path":"/references/doc:~1~1com.apple.Contacts-UI~1documentation~1ContactsUI~1CNContactPickerDelegate/fragments","value":[{"text":"CNContactPickerDelegate","kind":"identifier"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.Contacts-UI~1documentation~1ContactsUI~1CNContactPickerDelegate/navigatorTitle","value":[{"kind":"identifier","text":"CNContactPickerDelegate"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.Contacts-UI~1documentation~1ContactsUI~1CNContactPickerViewController/title","value":"CNContactPickerViewController","op":"replace"},{"value":[{"kind":"identifier","text":"CNContactPickerViewController"}],"op":"replace","path":"/references/doc:~1~1com.apple.Contacts-UI~1documentation~1ContactsUI~1CNContactPickerViewController/fragments"},{"value":[{"kind":"identifier","text":"CNContactPickerViewController"}],"op":"replace","path":"/references/doc:~1~1com.apple.Contacts-UI~1documentation~1ContactsUI~1CNContactPickerViewController/navigatorTitle"},{"value":"contactPicker:didSelectContactProperties:","op":"replace","path":"/references/doc:~1~1com.apple.Contacts-UI~1documentation~1ContactsUI~1CNContactPickerDelegate~1contactPicker(_:didSelectContactProperties:)/title"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"contactPicker:didSelectContactProperties:"}],"op":"replace","path":"/references/doc:~1~1com.apple.Contacts-UI~1documentation~1ContactsUI~1CNContactPickerDelegate~1contactPicker(_:didSelectContactProperties:)/fragments"},{"value":"contactPicker:didSelectContactProperty:","op":"replace","path":"/references/doc:~1~1com.apple.Contacts-UI~1documentation~1ContactsUI~1CNContactPickerDelegate~1contactPicker(_:didSelect:)-1xfpt/title"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"contactPicker:didSelectContactProperty:"}],"op":"replace","path":"/references/doc:~1~1com.apple.Contacts-UI~1documentation~1ContactsUI~1CNContactPickerDelegate~1contactPicker(_:didSelect:)-1xfpt/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}],"legalNotices":{"copyright":"Copyright &copy; 2025 Apple Inc. All rights reserved.","termsOfUse":"https://www.apple.com/legal/internet-services/terms/site.html","privacyPolicy":"https://www.apple.com/privacy/privacy-policy"}}