{"schemaVersion":{"major":0,"minor":3,"patch":0},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["/documentation/healthkit/hkstatisticsoptions/init(rawvalue:)"]}],"metadata":{"fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"rawValue"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Su","kind":"typeIdentifier","text":"UInt"},{"kind":"text","text":")"}],"role":"symbol","title":"init(rawValue:)","platforms":[{"unavailable":false,"name":"iOS","deprecated":false,"beta":false,"introducedAt":"8.0"},{"unavailable":false,"name":"iPadOS","deprecated":false,"beta":false,"introducedAt":"8.0"},{"unavailable":false,"name":"Mac Catalyst","deprecated":false,"beta":false,"introducedAt":"13.0"},{"unavailable":false,"name":"macOS","deprecated":false,"beta":false,"introducedAt":"13.0"},{"unavailable":false,"name":"visionOS","deprecated":false,"beta":false,"introducedAt":"1.0"},{"unavailable":false,"name":"watchOS","deprecated":false,"beta":false,"introducedAt":"2.0"}],"symbolKind":"init","modules":[{"name":"HealthKit"}],"externalID":"s:So19HKStatisticsOptionsV8rawValueABSu_tcfc","roleHeading":"Initializer"},"sections":[],"hierarchy":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.healthkit/documentation/HealthKit","doc://com.apple.healthkit/documentation/HealthKit/HKStatisticsOptions"]]},"abstract":[{"text":"Returns a newly initialized statistics option using the provided integer.","type":"text"}],"primaryContentSections":[{"declarations":[{"platforms":["iOS","iPadOS","Mac Catalyst","macOS","visionOS","watchOS"],"tokens":[{"text":"init","kind":"keyword"},{"text":"(","kind":"text"},{"text":"rawValue","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"UInt","identifier":"doc://com.externally.resolved.symbol/s:Su","preciseIdentifier":"s:Su","kind":"typeIdentifier"},{"text":")","kind":"text"}],"languages":["swift"]}],"kind":"declarations"}],"kind":"symbol","identifier":{"interfaceLanguage":"swift","url":"doc://com.apple.healthkit/documentation/HealthKit/HKStatisticsOptions/init(rawValue:)"},"references":{"doc://com.apple.healthkit/documentation/HealthKit":{"type":"topic","title":"HealthKit","kind":"symbol","abstract":[{"text":"Access and share health and fitness data while maintaining the user’s privacy and control.","type":"text"}],"identifier":"doc://com.apple.healthkit/documentation/HealthKit","role":"collection","url":"/documentation/healthkit"},"doc://com.apple.documentation/documentation/technologies":{"title":"Technologies","url":"/documentation/technologies","abstract":[{"type":"text","text":""}],"kind":"technologies","identifier":"doc://com.apple.documentation/documentation/technologies","type":"topic","role":"overview"},"doc://com.apple.healthkit/documentation/HealthKit/HKStatisticsOptions":{"fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"HKStatisticsOptions"}],"type":"topic","title":"HKStatisticsOptions","navigatorTitle":[{"kind":"identifier","text":"HKStatisticsOptions"}],"kind":"symbol","abstract":[{"type":"text","text":"Options for specifying the statistic to calculate."}],"role":"symbol","identifier":"doc://com.apple.healthkit/documentation/HealthKit/HKStatisticsOptions","url":"/documentation/healthkit/hkstatisticsoptions"},"doc://com.apple.healthkit/documentation/HealthKit/HKStatisticsOptions/init(rawValue:)":{"identifier":"doc://com.apple.healthkit/documentation/HealthKit/HKStatisticsOptions/init(rawValue:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"rawValue"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UInt","preciseIdentifier":"s:Su"},{"kind":"text","text":")"}],"kind":"symbol","type":"topic","abstract":[{"text":"Returns a newly initialized statistics option using the provided integer.","type":"text"}],"title":"init(rawValue:)","role":"symbol","url":"/documentation/healthkit/hkstatisticsoptions/init(rawvalue:)"},"doc://com.externally.resolved.symbol/s:Su":{"kind":"symbol","fragments":[{"text":"@frozen","kind":"attribute"},{"text":" ","kind":"text"},{"text":"struct","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"UInt"}],"role":"symbol","title":"UInt","abstract":[{"type":"text","text":"An unsigned integer value type."}],"identifier":"doc://com.externally.resolved.symbol/s:Su","type":"topic","url":"/documentation/Swift/UInt"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"HKStatisticsOptions","op":"replace","path":"/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKStatisticsOptions/title"},{"value":[{"kind":"identifier","text":"HKStatisticsOptions"}],"op":"replace","path":"/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKStatisticsOptions/fragments"},{"value":[{"text":"HKStatisticsOptions","kind":"identifier"}],"op":"replace","path":"/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKStatisticsOptions/navigatorTitle"}]}],"legalNotices":{"copyright":"Copyright &copy; 2025 Apple Inc. All rights reserved.","termsOfUse":"https://www.apple.com/legal/internet-services/terms/site.html","privacyPolicy":"https://www.apple.com/privacy/privacy-policy"}}