{"identifier":{"url":"doc://com.apple.healthkit/documentation/HealthKit/HKStatisticsOptions/separateBySource","interfaceLanguage":"swift"},"sections":[],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["/documentation/healthkit/hkstatisticsoptions/separatebysource"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["/documentation/healthkit/hkstatisticsoptions/separatebysource"]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"primaryContentSections":[{"declarations":[{"tokens":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"separateBySource","kind":"identifier"},{"text":": ","kind":"text"},{"text":"HKStatisticsOptions","kind":"typeIdentifier","identifier":"doc://com.apple.healthkit/documentation/HealthKit/HKStatisticsOptions","preciseIdentifier":"c:@E@HKStatisticsOptions"},{"text":" { ","kind":"text"},{"text":"get","kind":"keyword"},{"text":" }","kind":"text"}],"platforms":["iOS","iPadOS","Mac Catalyst","macOS","visionOS","watchOS"],"languages":["swift"]}],"kind":"declarations"}],"metadata":{"symbolKind":"property","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"separateBySource","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@E@HKStatisticsOptions","text":"HKStatisticsOptions","kind":"typeIdentifier"}],"role":"symbol","modules":[{"name":"HealthKit"}],"navigatorTitle":[{"text":"HKStatisticsOptionSeparateBySource","kind":"identifier"}],"externalID":"c:@E@HKStatisticsOptions@HKStatisticsOptionSeparateBySource","title":"separateBySource","roleHeading":"Type Property","platforms":[{"unavailable":false,"name":"iOS","introducedAt":"8.0","deprecated":false,"beta":false},{"unavailable":false,"name":"iPadOS","introducedAt":"8.0","deprecated":false,"beta":false},{"unavailable":false,"name":"Mac Catalyst","introducedAt":"13.0","deprecated":false,"beta":false},{"unavailable":false,"name":"macOS","introducedAt":"13.0","deprecated":false,"beta":false},{"unavailable":false,"name":"visionOS","introducedAt":"1.0","deprecated":false,"beta":false},{"unavailable":false,"name":"watchOS","introducedAt":"2.0","deprecated":false,"beta":false}]},"abstract":[{"type":"text","text":"An option indicating that the system calculates the specified statistics separately for each source."}],"hierarchy":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.healthkit/documentation/HealthKit","doc://com.apple.healthkit/documentation/HealthKit/HKStatisticsOptions"]]},"kind":"symbol","seeAlsoSections":[{"anchor":"Constants","title":"Constants","identifiers":["doc://com.apple.healthkit/documentation/HealthKit/HKStatisticsOptions/discreteAverage","doc://com.apple.healthkit/documentation/HealthKit/HKStatisticsOptions/discreteMin","doc://com.apple.healthkit/documentation/HealthKit/HKStatisticsOptions/discreteMax","doc://com.apple.healthkit/documentation/HealthKit/HKStatisticsOptions/cumulativeSum","doc://com.apple.healthkit/documentation/HealthKit/HKStatisticsOptions/mostRecent","doc://com.apple.healthkit/documentation/HealthKit/HKStatisticsOptions/duration"],"generated":true}],"references":{"doc://com.apple.healthkit/documentation/HealthKit/HKStatisticsOptions/discreteAverage":{"role":"symbol","type":"topic","navigatorTitle":[{"text":"HKStatisticsOptionDiscreteAverage","kind":"identifier"}],"abstract":[{"text":"An option indicating that the system calculates the average quantity for the samples.","type":"text"}],"url":"/documentation/healthkit/hkstatisticsoptions/discreteaverage","kind":"symbol","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"discreteAverage","kind":"identifier"},{"text":": ","kind":"text"},{"text":"HKStatisticsOptions","kind":"typeIdentifier","preciseIdentifier":"c:@E@HKStatisticsOptions"}],"identifier":"doc://com.apple.healthkit/documentation/HealthKit/HKStatisticsOptions/discreteAverage","title":"discreteAverage"},"doc://com.apple.healthkit/documentation/HealthKit/HKStatisticsOptions/mostRecent":{"abstract":[{"text":"An option indicating that the system returns the most recent quantity from the matching samples.","type":"text"}],"identifier":"doc://com.apple.healthkit/documentation/HealthKit/HKStatisticsOptions/mostRecent","role":"symbol","url":"/documentation/healthkit/hkstatisticsoptions/mostrecent","navigatorTitle":[{"kind":"identifier","text":"HKStatisticsOptionMostRecent"}],"type":"topic","kind":"symbol","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"mostRecent"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@E@HKStatisticsOptions","text":"HKStatisticsOptions"}],"title":"mostRecent"},"doc://com.apple.healthkit/documentation/HealthKit/HKStatisticsOptions/separateBySource":{"fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"separateBySource","kind":"identifier"},{"text":": ","kind":"text"},{"text":"HKStatisticsOptions","preciseIdentifier":"c:@E@HKStatisticsOptions","kind":"typeIdentifier"}],"type":"topic","identifier":"doc://com.apple.healthkit/documentation/HealthKit/HKStatisticsOptions/separateBySource","url":"/documentation/healthkit/hkstatisticsoptions/separatebysource","title":"separateBySource","kind":"symbol","abstract":[{"text":"An option indicating that the system calculates the specified statistics separately for each source.","type":"text"}],"role":"symbol","navigatorTitle":[{"text":"HKStatisticsOptionSeparateBySource","kind":"identifier"}]},"doc://com.apple.healthkit/documentation/HealthKit":{"type":"topic","title":"HealthKit","kind":"symbol","abstract":[{"text":"Access and share health and fitness data while maintaining the user’s privacy and control.","type":"text"}],"identifier":"doc://com.apple.healthkit/documentation/HealthKit","role":"collection","url":"/documentation/healthkit"},"doc://com.apple.healthkit/documentation/HealthKit/HKStatisticsOptions/duration":{"role":"symbol","type":"topic","navigatorTitle":[{"text":"HKStatisticsOptionDuration","kind":"identifier"}],"abstract":[{"text":"An option indicating that the system calculates the total duration covering all the samples.","type":"text"}],"url":"/documentation/healthkit/hkstatisticsoptions/duration","kind":"symbol","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"duration","kind":"identifier"},{"text":": ","kind":"text"},{"text":"HKStatisticsOptions","kind":"typeIdentifier","preciseIdentifier":"c:@E@HKStatisticsOptions"}],"identifier":"doc://com.apple.healthkit/documentation/HealthKit/HKStatisticsOptions/duration","title":"duration"},"doc://com.apple.healthkit/documentation/HealthKit/HKStatisticsOptions/HKStatisticsOptionNone":{"fragments":[{"text":"HKStatisticsOptionNone","kind":"identifier"}],"type":"topic","title":"HKStatisticsOptionNone","role":"symbol","identifier":"doc://com.apple.healthkit/documentation/HealthKit/HKStatisticsOptions/HKStatisticsOptionNone","url":"/documentation/healthkit/hkstatisticsoptions/hkstatisticsoptionnone","kind":"symbol","abstract":[{"type":"text","text":"An option indicating that the system will not calculate any statistics values."}]},"doc://com.apple.healthkit/documentation/HealthKit/HKStatisticsOptions":{"fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"HKStatisticsOptions"}],"type":"topic","title":"HKStatisticsOptions","navigatorTitle":[{"kind":"identifier","text":"HKStatisticsOptions"}],"kind":"symbol","abstract":[{"type":"text","text":"Options for specifying the statistic to calculate."}],"role":"symbol","identifier":"doc://com.apple.healthkit/documentation/HealthKit/HKStatisticsOptions","url":"/documentation/healthkit/hkstatisticsoptions"},"doc://com.apple.healthkit/documentation/HealthKit/HKStatisticsOptions/discreteMax":{"identifier":"doc://com.apple.healthkit/documentation/HealthKit/HKStatisticsOptions/discreteMax","url":"/documentation/healthkit/hkstatisticsoptions/discretemax","kind":"symbol","type":"topic","title":"discreteMax","abstract":[{"text":"An option indicating that the system calculates the maximum quantity for the samples.","type":"text"}],"role":"symbol","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"discreteMax"},{"text":": ","kind":"text"},{"text":"HKStatisticsOptions","preciseIdentifier":"c:@E@HKStatisticsOptions","kind":"typeIdentifier"}],"navigatorTitle":[{"text":"HKStatisticsOptionDiscreteMax","kind":"identifier"}]},"doc://com.apple.documentation/documentation/technologies":{"title":"Technologies","url":"/documentation/technologies","abstract":[{"type":"text","text":""}],"kind":"technologies","identifier":"doc://com.apple.documentation/documentation/technologies","type":"topic","role":"overview"},"doc://com.apple.healthkit/documentation/HealthKit/HKStatisticsOptions/discreteMin":{"type":"topic","role":"symbol","title":"discreteMin","abstract":[{"text":"An option indicating that the system calculates the minimum quantity for the samples.","type":"text"}],"kind":"symbol","identifier":"doc://com.apple.healthkit/documentation/HealthKit/HKStatisticsOptions/discreteMin","url":"/documentation/healthkit/hkstatisticsoptions/discretemin","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"discreteMin","kind":"identifier"},{"text":": ","kind":"text"},{"text":"HKStatisticsOptions","kind":"typeIdentifier","preciseIdentifier":"c:@E@HKStatisticsOptions"}],"navigatorTitle":[{"text":"HKStatisticsOptionDiscreteMin","kind":"identifier"}]},"doc://com.apple.healthkit/documentation/HealthKit/HKStatisticsOptions/cumulativeSum":{"abstract":[{"text":"An option indicating that the system calculates the sum of all the quantities for the samples.","type":"text"}],"title":"cumulativeSum","identifier":"doc://com.apple.healthkit/documentation/HealthKit/HKStatisticsOptions/cumulativeSum","kind":"symbol","url":"/documentation/healthkit/hkstatisticsoptions/cumulativesum","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"cumulativeSum","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@E@HKStatisticsOptions","text":"HKStatisticsOptions","kind":"typeIdentifier"}],"role":"symbol","type":"topic","navigatorTitle":[{"text":"HKStatisticsOptionCumulativeSum","kind":"identifier"}]}},"variantOverrides":[{"patch":[{"value":"occ","path":"/identifier/interfaceLanguage","op":"replace"},{"value":[{"unavailable":false,"name":"iOS","deprecated":false,"introducedAt":"8.0","beta":false},{"unavailable":false,"name":"iPadOS","deprecated":false,"introducedAt":"8.0","beta":false},{"unavailable":false,"name":"Mac Catalyst","deprecated":false,"introducedAt":"13.0","beta":false},{"unavailable":false,"name":"macOS","deprecated":false,"introducedAt":"13.0","beta":false},{"unavailable":false,"name":"visionOS","deprecated":false,"introducedAt":"1.0","beta":false},{"unavailable":false,"name":"watchOS","deprecated":false,"introducedAt":"2.0","beta":false}],"path":"/metadata/platforms","op":"replace"},{"value":"Enumeration Case","path":"/metadata/roleHeading","op":"replace"},{"value":"HKStatisticsOptionSeparateBySource","path":"/metadata/title","op":"replace"},{"value":"case","path":"/metadata/symbolKind","op":"replace"},{"value":[{"kind":"identifier","text":"HKStatisticsOptionSeparateBySource"}],"path":"/metadata/fragments","op":"replace"},{"value":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.healthkit/documentation/HealthKit","doc://com.apple.healthkit/documentation/HealthKit/HKStatisticsOptions"]]},"path":"/hierarchy","op":"replace"},{"value":null,"path":"/topicSections","op":"add"},{"value":null,"op":"add","path":"/relationshipsSections"},{"value":[{"generated":true,"identifiers":["doc://com.apple.healthkit/documentation/HealthKit/HKStatisticsOptions/HKStatisticsOptionNone","doc://com.apple.healthkit/documentation/HealthKit/HKStatisticsOptions/discreteAverage","doc://com.apple.healthkit/documentation/HealthKit/HKStatisticsOptions/discreteMin","doc://com.apple.healthkit/documentation/HealthKit/HKStatisticsOptions/discreteMax","doc://com.apple.healthkit/documentation/HealthKit/HKStatisticsOptions/cumulativeSum","doc://com.apple.healthkit/documentation/HealthKit/HKStatisticsOptions/mostRecent","doc://com.apple.healthkit/documentation/HealthKit/HKStatisticsOptions/duration"],"title":"Constants","anchor":"Constants"}],"op":"replace","path":"/seeAlsoSections"},{"value":{"declarations":[{"tokens":[{"text":"HKStatisticsOptionSeparateBySource","kind":"identifier"}],"languages":["occ"],"platforms":["iOS","iPadOS","Mac Catalyst","macOS","visionOS","watchOS"]}],"kind":"declarations"},"op":"replace","path":"/primaryContentSections/0"},{"path":"/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKStatisticsOptions~1discreteAverage/title","op":"replace","value":"HKStatisticsOptionDiscreteAverage"},{"path":"/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKStatisticsOptions~1discreteAverage/fragments","op":"replace","value":[{"text":"HKStatisticsOptionDiscreteAverage","kind":"identifier"}]},{"path":"/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKStatisticsOptions~1mostRecent/title","op":"replace","value":"HKStatisticsOptionMostRecent"},{"path":"/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKStatisticsOptions~1mostRecent/fragments","op":"replace","value":[{"text":"HKStatisticsOptionMostRecent","kind":"identifier"}]},{"path":"/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKStatisticsOptions~1separateBySource/title","op":"replace","value":"HKStatisticsOptionSeparateBySource"},{"path":"/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKStatisticsOptions~1separateBySource/fragments","op":"replace","value":[{"text":"HKStatisticsOptionSeparateBySource","kind":"identifier"}]},{"path":"/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKStatisticsOptions~1duration/title","op":"replace","value":"HKStatisticsOptionDuration"},{"path":"/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKStatisticsOptions~1duration/fragments","op":"replace","value":[{"text":"HKStatisticsOptionDuration","kind":"identifier"}]},{"path":"/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKStatisticsOptions/title","op":"replace","value":"HKStatisticsOptions"},{"path":"/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKStatisticsOptions/fragments","op":"replace","value":[{"text":"HKStatisticsOptions","kind":"identifier"}]},{"value":[{"text":"HKStatisticsOptions","kind":"identifier"}],"op":"replace","path":"/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKStatisticsOptions/navigatorTitle"},{"value":"HKStatisticsOptionDiscreteMax","op":"replace","path":"/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKStatisticsOptions~1discreteMax/title"},{"value":[{"text":"HKStatisticsOptionDiscreteMax","kind":"identifier"}],"op":"replace","path":"/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKStatisticsOptions~1discreteMax/fragments"},{"value":"HKStatisticsOptionDiscreteMin","op":"replace","path":"/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKStatisticsOptions~1discreteMin/title"},{"value":[{"text":"HKStatisticsOptionDiscreteMin","kind":"identifier"}],"op":"replace","path":"/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKStatisticsOptions~1discreteMin/fragments"},{"value":"HKStatisticsOptionCumulativeSum","op":"replace","path":"/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKStatisticsOptions~1cumulativeSum/title"},{"value":[{"kind":"identifier","text":"HKStatisticsOptionCumulativeSum"}],"op":"replace","path":"/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKStatisticsOptions~1cumulativeSum/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}],"legalNotices":{"copyright":"Copyright &copy; 2025 Apple Inc. All rights reserved.","termsOfUse":"https://www.apple.com/legal/internet-services/terms/site.html","privacyPolicy":"https://www.apple.com/privacy/privacy-policy"}}