{
  "abstract": [
    {
      "text": "An error code that indicates a dynamic library couldn’t link to other dynamic libraries.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.metal/documentation/Metal",
        "doc://com.apple.metal/documentation/Metal/MTLDynamicLibraryError-swift.struct",
        "doc://com.apple.metal/documentation/Metal/MTLDynamicLibraryError-swift.struct/Code"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.metal/documentation/Metal/MTLDynamicLibraryError-swift.struct/Code/dependencyLoadFailure"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@MTLDynamicLibraryError@MTLDynamicLibraryErrorDependencyLoadFailure",
    "fragments": [
      {
        "kind": "keyword",
        "text": "case"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "dependencyLoadFailure"
      }
    ],
    "modules": [
      {
        "name": "Metal"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "MTLDynamicLibraryErrorDependencyLoadFailure"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "14.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "14.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "14.0",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "11.0",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "14.0",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Case",
    "symbolKind": "case",
    "title": "MTLDynamicLibraryError.Code.dependencyLoadFailure"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "case"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "dependencyLoadFailure"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.metal/documentation/Metal": {
      "abstract": [
        {
          "text": "Render advanced 3D graphics and compute data in parallel with graphics processors.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal",
      "kind": "symbol",
      "role": "collection",
      "title": "Metal",
      "type": "topic",
      "url": "/documentation/metal"
    },
    "doc://com.apple.metal/documentation/Metal/MTLDynamicLibraryError-swift.struct": {
      "abstract": [
        {
          "text": "Errors when compiling dynamic libraries.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MTLDynamicLibraryError"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLDynamicLibraryError-swift.struct",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTLDynamicLibraryError"
        }
      ],
      "role": "symbol",
      "title": "MTLDynamicLibraryError",
      "type": "topic",
      "url": "/documentation/metal/mtldynamiclibraryerror-swift.struct"
    },
    "doc://com.apple.metal/documentation/Metal/MTLDynamicLibraryError-swift.struct/Code": {
      "abstract": [
        {
          "text": "Error codes that Metal can generate when creating dynamic libraries.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLDynamicLibraryError-swift.struct/Code",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "Code"
        }
      ],
      "role": "symbol",
      "title": "MTLDynamicLibraryError.Code",
      "type": "topic",
      "url": "/documentation/metal/mtldynamiclibraryerror-swift.struct/code"
    },
    "doc://com.apple.metal/documentation/Metal/MTLDynamicLibraryError-swift.struct/Code/compilationFailure": {
      "abstract": [
        {
          "text": "An error code that indicates Metal couldn’t compile a dynamic library.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "compilationFailure"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLDynamicLibraryError-swift.struct/Code/compilationFailure",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTLDynamicLibraryErrorCompilationFailure"
        }
      ],
      "role": "symbol",
      "title": "MTLDynamicLibraryError.Code.compilationFailure",
      "type": "topic",
      "url": "/documentation/metal/mtldynamiclibraryerror-swift.struct/code/compilationfailure"
    },
    "doc://com.apple.metal/documentation/Metal/MTLDynamicLibraryError-swift.struct/Code/dependencyLoadFailure": {
      "abstract": [
        {
          "text": "An error code that indicates a dynamic library couldn’t link to other dynamic libraries.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "dependencyLoadFailure"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLDynamicLibraryError-swift.struct/Code/dependencyLoadFailure",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTLDynamicLibraryErrorDependencyLoadFailure"
        }
      ],
      "role": "symbol",
      "title": "MTLDynamicLibraryError.Code.dependencyLoadFailure",
      "type": "topic",
      "url": "/documentation/metal/mtldynamiclibraryerror-swift.struct/code/dependencyloadfailure"
    },
    "doc://com.apple.metal/documentation/Metal/MTLDynamicLibraryError-swift.struct/Code/invalidFile": {
      "abstract": [
        {
          "text": "An error code that indicates an app is using an invalid reference to a library file, typically related to a URL.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "invalidFile"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLDynamicLibraryError-swift.struct/Code/invalidFile",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTLDynamicLibraryErrorInvalidFile"
        }
      ],
      "role": "symbol",
      "title": "MTLDynamicLibraryError.Code.invalidFile",
      "type": "topic",
      "url": "/documentation/metal/mtldynamiclibraryerror-swift.struct/code/invalidfile"
    },
    "doc://com.apple.metal/documentation/Metal/MTLDynamicLibraryError-swift.struct/Code/none": {
      "abstract": [
        {
          "text": "An error code that represents the absence of any problems.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "none"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLDynamicLibraryError-swift.struct/Code/none",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTLDynamicLibraryErrorNone"
        }
      ],
      "role": "symbol",
      "title": "MTLDynamicLibraryError.Code.none",
      "type": "topic",
      "url": "/documentation/metal/mtldynamiclibraryerror-swift.struct/code/none"
    },
    "doc://com.apple.metal/documentation/Metal/MTLDynamicLibraryError-swift.struct/Code/unresolvedInstallName": {
      "abstract": [
        {
          "text": "An error code that indicates Metal couldn’t resolve the installation name for a new dynamic library.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "unresolvedInstallName"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLDynamicLibraryError-swift.struct/Code/unresolvedInstallName",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTLDynamicLibraryErrorUnresolvedInstallName"
        }
      ],
      "role": "symbol",
      "title": "MTLDynamicLibraryError.Code.unresolvedInstallName",
      "type": "topic",
      "url": "/documentation/metal/mtldynamiclibraryerror-swift.struct/code/unresolvedinstallname"
    },
    "doc://com.apple.metal/documentation/Metal/MTLDynamicLibraryError-swift.struct/Code/unsupported": {
      "abstract": [
        {
          "text": "An error code that indicates the GPU device doesn’t support dynamic libraries.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "unsupported"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLDynamicLibraryError-swift.struct/Code/unsupported",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTLDynamicLibraryErrorUnsupported"
        }
      ],
      "role": "symbol",
      "title": "MTLDynamicLibraryError.Code.unsupported",
      "type": "topic",
      "url": "/documentation/metal/mtldynamiclibraryerror-swift.struct/code/unsupported"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Error-Codes",
      "generated": true,
      "identifiers": [
        "doc://com.apple.metal/documentation/Metal/MTLDynamicLibraryError-swift.struct/Code/none",
        "doc://com.apple.metal/documentation/Metal/MTLDynamicLibraryError-swift.struct/Code/invalidFile",
        "doc://com.apple.metal/documentation/Metal/MTLDynamicLibraryError-swift.struct/Code/compilationFailure",
        "doc://com.apple.metal/documentation/Metal/MTLDynamicLibraryError-swift.struct/Code/unresolvedInstallName",
        "doc://com.apple.metal/documentation/Metal/MTLDynamicLibraryError-swift.struct/Code/unsupported",
        "doc://com.apple.metal/documentation/Metal/MTLDynamicLibraryError-swift.struct/Code/none",
        "doc://com.apple.metal/documentation/Metal/MTLDynamicLibraryError-swift.struct/Code/invalidFile",
        "doc://com.apple.metal/documentation/Metal/MTLDynamicLibraryError-swift.struct/Code/compilationFailure",
        "doc://com.apple.metal/documentation/Metal/MTLDynamicLibraryError-swift.struct/Code/unresolvedInstallName",
        "doc://com.apple.metal/documentation/Metal/MTLDynamicLibraryError-swift.struct/Code/unsupported"
      ],
      "title": "Error Codes"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "14.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "14.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "14.0",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "11.0",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "14.0",
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration Case"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "MTLDynamicLibraryErrorDependencyLoadFailure"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "case"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLDynamicLibraryErrorDependencyLoadFailure"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.metal/documentation/Metal",
                "doc://com.apple.metal/documentation/Metal/MTLDynamicLibraryError-swift.struct/Code"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Error-Codes",
              "generated": true,
              "identifiers": [
                "doc://com.apple.metal/documentation/Metal/MTLDynamicLibraryError-swift.struct/Code/none",
                "doc://com.apple.metal/documentation/Metal/MTLDynamicLibraryError-swift.struct/Code/invalidFile",
                "doc://com.apple.metal/documentation/Metal/MTLDynamicLibraryError-swift.struct/Code/compilationFailure",
                "doc://com.apple.metal/documentation/Metal/MTLDynamicLibraryError-swift.struct/Code/unresolvedInstallName",
                "doc://com.apple.metal/documentation/Metal/MTLDynamicLibraryError-swift.struct/Code/unsupported",
                "doc://com.apple.metal/documentation/Metal/MTLDynamicLibraryError-swift.struct/Code/none",
                "doc://com.apple.metal/documentation/Metal/MTLDynamicLibraryError-swift.struct/Code/invalidFile",
                "doc://com.apple.metal/documentation/Metal/MTLDynamicLibraryError-swift.struct/Code/compilationFailure",
                "doc://com.apple.metal/documentation/Metal/MTLDynamicLibraryError-swift.struct/Code/unresolvedInstallName",
                "doc://com.apple.metal/documentation/Metal/MTLDynamicLibraryError-swift.struct/Code/unsupported"
              ],
              "title": "Error Codes"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS"
                ],
                "tokens": [
                  {
                    "kind": "identifier",
                    "text": "MTLDynamicLibraryErrorDependencyLoadFailure"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLDynamicLibraryError-swift.struct~1Code~1none/title",
          "value": "MTLDynamicLibraryErrorNone"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLDynamicLibraryError-swift.struct~1Code~1none/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLDynamicLibraryErrorNone"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLDynamicLibraryError-swift.struct~1Code~1invalidFile/title",
          "value": "MTLDynamicLibraryErrorInvalidFile"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLDynamicLibraryError-swift.struct~1Code~1invalidFile/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLDynamicLibraryErrorInvalidFile"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLDynamicLibraryError-swift.struct~1Code~1unsupported/title",
          "value": "MTLDynamicLibraryErrorUnsupported"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLDynamicLibraryError-swift.struct~1Code~1unsupported/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLDynamicLibraryErrorUnsupported"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLDynamicLibraryError-swift.struct~1Code/title",
          "value": "MTLDynamicLibraryError"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLDynamicLibraryError-swift.struct~1Code/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLDynamicLibraryError"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLDynamicLibraryError-swift.struct~1Code/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLDynamicLibraryError"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLDynamicLibraryError-swift.struct~1Code~1compilationFailure/title",
          "value": "MTLDynamicLibraryErrorCompilationFailure"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLDynamicLibraryError-swift.struct~1Code~1compilationFailure/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLDynamicLibraryErrorCompilationFailure"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLDynamicLibraryError-swift.struct~1Code~1dependencyLoadFailure/title",
          "value": "MTLDynamicLibraryErrorDependencyLoadFailure"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLDynamicLibraryError-swift.struct~1Code~1dependencyLoadFailure/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLDynamicLibraryErrorDependencyLoadFailure"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLDynamicLibraryError-swift.struct~1Code~1unresolvedInstallName/title",
          "value": "MTLDynamicLibraryErrorUnresolvedInstallName"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLDynamicLibraryError-swift.struct~1Code~1unresolvedInstallName/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLDynamicLibraryErrorUnresolvedInstallName"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/metal/mtldynamiclibraryerror-swift.struct/code/dependencyloadfailure"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/metal/mtldynamiclibraryerror-swift.struct/code/dependencyloadfailure"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
