{
  "abstract": [
    {
      "text": "The type of biometric authentication supported by the device.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.localauthentication/documentation/LocalAuthentication",
        "doc://com.apple.localauthentication/documentation/LocalAuthentication/LAContext"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.localauthentication/documentation/LocalAuthentication/LAContext/biometryType"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(cs)LAContext(py)biometryType",
    "fragments": [
      {
        "kind": "keyword",
        "text": "var"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "biometryType"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@E@LABiometryType",
        "text": "LABiometryType"
      }
    ],
    "modules": [
      {
        "name": "Local Authentication"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "biometryType"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "11.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "11.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.1",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.13.2",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "11.0",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Instance Property",
    "symbolKind": "property",
    "title": "biometryType"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "var"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "biometryType"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.localauthentication/documentation/LocalAuthentication/LABiometryType",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@E@LABiometryType",
              "text": "LABiometryType"
            },
            {
              "kind": "text",
              "text": " { "
            },
            {
              "kind": "keyword",
              "text": "get"
            },
            {
              "kind": "text",
              "text": " }"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Use the value of this property to ensure that any authentication-related user prompts you create match the biometric capabilities of the device. For example, if the value of this property is ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.localauthentication/documentation/LocalAuthentication/LABiometryType/faceID",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ", don’t refer to Touch ID in an authentication prompt.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "This property is set only after you call the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.localauthentication/documentation/LocalAuthentication/LAContext/canEvaluatePolicy(_:error:)",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " method, and is set no matter what the call returns. The default value is ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.localauthentication/documentation/LocalAuthentication/LABiometryType/none",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ".",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.localauthentication/documentation/LocalAuthentication": {
      "abstract": [
        {
          "text": "Authenticate users biometrically or with a passphrase they already know.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.localauthentication/documentation/LocalAuthentication",
      "kind": "symbol",
      "role": "collection",
      "title": "Local Authentication",
      "type": "topic",
      "url": "/documentation/localauthentication"
    },
    "doc://com.apple.localauthentication/documentation/LocalAuthentication/LABiometryType": {
      "abstract": [
        {
          "text": "The set of available biometric authentication types.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "LABiometryType"
        }
      ],
      "identifier": "doc://com.apple.localauthentication/documentation/LocalAuthentication/LABiometryType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "LABiometryType"
        }
      ],
      "role": "symbol",
      "title": "LABiometryType",
      "type": "topic",
      "url": "/documentation/localauthentication/labiometrytype"
    },
    "doc://com.apple.localauthentication/documentation/LocalAuthentication/LABiometryType/faceID": {
      "abstract": [
        {
          "text": "The device supports Face ID.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "faceID"
        }
      ],
      "identifier": "doc://com.apple.localauthentication/documentation/LocalAuthentication/LABiometryType/faceID",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "LABiometryTypeFaceID"
        }
      ],
      "role": "symbol",
      "title": "LABiometryType.faceID",
      "type": "topic",
      "url": "/documentation/localauthentication/labiometrytype/faceid"
    },
    "doc://com.apple.localauthentication/documentation/LocalAuthentication/LABiometryType/none": {
      "abstract": [
        {
          "text": "No biometry type is supported.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "none"
        }
      ],
      "identifier": "doc://com.apple.localauthentication/documentation/LocalAuthentication/LABiometryType/none",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "LABiometryTypeNone"
        }
      ],
      "role": "symbol",
      "title": "LABiometryType.none",
      "type": "topic",
      "url": "/documentation/localauthentication/labiometrytype/none"
    },
    "doc://com.apple.localauthentication/documentation/LocalAuthentication/LAContext": {
      "abstract": [
        {
          "text": "A mechanism for evaluating authentication policies and access controls.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "LAContext"
        }
      ],
      "identifier": "doc://com.apple.localauthentication/documentation/LocalAuthentication/LAContext",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "LAContext"
        }
      ],
      "role": "symbol",
      "title": "LAContext",
      "type": "topic",
      "url": "/documentation/localauthentication/lacontext"
    },
    "doc://com.apple.localauthentication/documentation/LocalAuthentication/LAContext/biometryType": {
      "abstract": [
        {
          "text": "The type of biometric authentication supported by the device.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "biometryType"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@LABiometryType",
          "text": "LABiometryType"
        }
      ],
      "identifier": "doc://com.apple.localauthentication/documentation/LocalAuthentication/LAContext/biometryType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "biometryType"
        }
      ],
      "role": "symbol",
      "title": "biometryType",
      "type": "topic",
      "url": "/documentation/localauthentication/lacontext/biometrytype"
    },
    "doc://com.apple.localauthentication/documentation/LocalAuthentication/LAContext/canEvaluatePolicy(_:error:)": {
      "abstract": [
        {
          "text": "Assesses whether authentication can proceed for a given policy.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "canEvaluatePolicy"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@LAPolicy",
          "text": "LAPolicy"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "error"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10Foundation14NSErrorPointera",
          "text": "NSErrorPointer"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.localauthentication/documentation/LocalAuthentication/LAContext/canEvaluatePolicy(_:error:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "canEvaluatePolicy:error:"
        }
      ],
      "role": "symbol",
      "title": "canEvaluatePolicy(_:error:)",
      "type": "topic",
      "url": "/documentation/localauthentication/lacontext/canevaluatepolicy(_:error:)"
    },
    "doc://com.apple.localauthentication/documentation/LocalAuthentication/LAPolicy": {
      "abstract": [
        {
          "text": "The set of available local authentication policies.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "LAPolicy"
        }
      ],
      "identifier": "doc://com.apple.localauthentication/documentation/LocalAuthentication/LAPolicy",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "LAPolicy"
        }
      ],
      "role": "symbol",
      "title": "LAPolicy",
      "type": "topic",
      "url": "/documentation/localauthentication/lapolicy"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Checking-availability",
      "generated": true,
      "identifiers": [
        "doc://com.apple.localauthentication/documentation/LocalAuthentication/LAContext/canEvaluatePolicy(_:error:)",
        "doc://com.apple.localauthentication/documentation/LocalAuthentication/LAPolicy",
        "doc://com.apple.localauthentication/documentation/LocalAuthentication/LABiometryType"
      ],
      "title": "Checking availability"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "11.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "11.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.1",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.13.2",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "11.0",
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Instance Property"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "biometryType"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "property"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "biometryType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.localauthentication/documentation/LocalAuthentication",
                "doc://com.apple.localauthentication/documentation/LocalAuthentication/LAContext"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Checking-availability",
              "generated": true,
              "identifiers": [
                "doc://com.apple.localauthentication/documentation/LocalAuthentication/LAContext/canEvaluatePolicy(_:error:)",
                "doc://com.apple.localauthentication/documentation/LocalAuthentication/LAPolicy",
                "doc://com.apple.localauthentication/documentation/LocalAuthentication/LABiometryType"
              ],
              "title": "Checking availability"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "@property"
                  },
                  {
                    "kind": "text",
                    "text": " ("
                  },
                  {
                    "kind": "keyword",
                    "text": "nonatomic"
                  },
                  {
                    "kind": "text",
                    "text": ", "
                  },
                  {
                    "kind": "keyword",
                    "text": "readonly"
                  },
                  {
                    "kind": "text",
                    "text": ") "
                  },
                  {
                    "identifier": "doc://com.apple.localauthentication/documentation/LocalAuthentication/LABiometryType",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@E@LABiometryType",
                    "text": "LABiometryType"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "biometryType"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.localauthentication~1documentation~1LocalAuthentication~1LABiometryType/title",
          "value": "LABiometryType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.localauthentication~1documentation~1LocalAuthentication~1LABiometryType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "LABiometryType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.localauthentication~1documentation~1LocalAuthentication~1LABiometryType/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "LABiometryType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.localauthentication~1documentation~1LocalAuthentication~1LABiometryType~1faceID/title",
          "value": "LABiometryTypeFaceID"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.localauthentication~1documentation~1LocalAuthentication~1LABiometryType~1faceID/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "LABiometryTypeFaceID"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.localauthentication~1documentation~1LocalAuthentication~1LAPolicy/title",
          "value": "LAPolicy"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.localauthentication~1documentation~1LocalAuthentication~1LAPolicy/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "LAPolicy"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.localauthentication~1documentation~1LocalAuthentication~1LAPolicy/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "LAPolicy"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.localauthentication~1documentation~1LocalAuthentication~1LABiometryType~1none/title",
          "value": "LABiometryTypeNone"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.localauthentication~1documentation~1LocalAuthentication~1LABiometryType~1none/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "LABiometryTypeNone"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.localauthentication~1documentation~1LocalAuthentication~1LAContext/title",
          "value": "LAContext"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.localauthentication~1documentation~1LocalAuthentication~1LAContext/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "LAContext"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.localauthentication~1documentation~1LocalAuthentication~1LAContext/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "LAContext"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.localauthentication~1documentation~1LocalAuthentication~1LAContext~1biometryType/title",
          "value": "biometryType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.localauthentication~1documentation~1LocalAuthentication~1LAContext~1biometryType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "biometryType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.localauthentication~1documentation~1LocalAuthentication~1LAContext~1canEvaluatePolicy(_:error:)/title",
          "value": "canEvaluatePolicy:error:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.localauthentication~1documentation~1LocalAuthentication~1LAContext~1canEvaluatePolicy(_:error:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "canEvaluatePolicy:error:"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/localauthentication/lacontext/biometrytype"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/localauthentication/lacontext/biometrytype"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
