{
  "abstract": [
    {
      "text": "The localized explanation for authentication shown in the dialog presented to the user.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.localauthentication/documentation/LocalAuthentication",
        "doc://com.apple.localauthentication/documentation/LocalAuthentication/LAContext"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.localauthentication/documentation/LocalAuthentication/LAContext/localizedReason"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(cs)LAContext(py)localizedReason",
    "fragments": [
      {
        "kind": "keyword",
        "text": "var"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "localizedReason"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "s:SS",
        "text": "String"
      }
    ],
    "modules": [
      {
        "name": "Local Authentication"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "localizedReason"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "11.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "11.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.1",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.13",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Instance Property",
    "symbolKind": "property",
    "title": "localizedReason"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "var"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "localizedReason"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:SS",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:SS",
              "text": "String"
            },
            {
              "kind": "text",
              "text": " { "
            },
            {
              "kind": "keyword",
              "text": "get"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "keyword",
              "text": "set"
            },
            {
              "kind": "text",
              "text": " }"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "This property is overwritten if an authentication reason is provided in ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.localauthentication/documentation/LocalAuthentication/LAContext/evaluatePolicy(_:localizedReason:reply:)",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ".",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "The localized string you present to the user should provide a clear reason for why you are requesting they authenticate themselves, and what action you will be taking based on that authentication. This string should be provided in the user’s current language and should be short and clear. It should not contain the app name, because that appears elsewhere in the authentication dialog. In macOS this appears in the dialog title, and in iOS this appears in the dialog subtitle.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.localauthentication/documentation/LocalAuthentication": {
      "abstract": [
        {
          "text": "Authenticate users biometrically or with a passphrase they already know.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.localauthentication/documentation/LocalAuthentication",
      "kind": "symbol",
      "role": "collection",
      "title": "Local Authentication",
      "type": "topic",
      "url": "/documentation/localauthentication"
    },
    "doc://com.apple.localauthentication/documentation/LocalAuthentication/LAContext": {
      "abstract": [
        {
          "text": "A mechanism for evaluating authentication policies and access controls.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "LAContext"
        }
      ],
      "identifier": "doc://com.apple.localauthentication/documentation/LocalAuthentication/LAContext",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "LAContext"
        }
      ],
      "role": "symbol",
      "title": "LAContext",
      "type": "topic",
      "url": "/documentation/localauthentication/lacontext"
    },
    "doc://com.apple.localauthentication/documentation/LocalAuthentication/LAContext/evaluatePolicy(_:localizedReason:reply:)": {
      "abstract": [
        {
          "text": "Evaluates the specified policy.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "evaluatePolicy"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@LAPolicy",
          "text": "LAPolicy"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "localizedReason"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "reply"
        },
        {
          "kind": "text",
          "text": ": ("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        },
        {
          "kind": "text",
          "text": ", (any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5ErrorP",
          "text": "Error"
        },
        {
          "kind": "text",
          "text": ")?) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s4Voida",
          "text": "Void"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.localauthentication/documentation/LocalAuthentication/LAContext/evaluatePolicy(_:localizedReason:reply:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "evaluatePolicy:localizedReason:reply:"
        }
      ],
      "role": "symbol",
      "title": "evaluatePolicy(_:localizedReason:reply:)",
      "type": "topic",
      "url": "/documentation/localauthentication/lacontext/evaluatepolicy(_:localizedreason:reply:)"
    },
    "doc://com.apple.localauthentication/documentation/LocalAuthentication/LAContext/localizedCancelTitle": {
      "abstract": [
        {
          "text": "The localized title for the cancel button in the dialog presented to the user during authentication.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "localizedCancelTitle"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.localauthentication/documentation/LocalAuthentication/LAContext/localizedCancelTitle",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "localizedCancelTitle"
        }
      ],
      "role": "symbol",
      "title": "localizedCancelTitle",
      "type": "topic",
      "url": "/documentation/localauthentication/lacontext/localizedcanceltitle"
    },
    "doc://com.apple.localauthentication/documentation/LocalAuthentication/LAContext/localizedFallbackTitle": {
      "abstract": [
        {
          "text": "The localized title for the fallback button in the dialog presented to the user during authentication.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "localizedFallbackTitle"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.localauthentication/documentation/LocalAuthentication/LAContext/localizedFallbackTitle",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "localizedFallbackTitle"
        }
      ],
      "role": "symbol",
      "title": "localizedFallbackTitle",
      "type": "topic",
      "url": "/documentation/localauthentication/lacontext/localizedfallbacktitle"
    },
    "doc://com.apple.localauthentication/documentation/LocalAuthentication/LAContext/localizedReason": {
      "abstract": [
        {
          "text": "The localized explanation for authentication shown in the dialog presented to the user.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "localizedReason"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.localauthentication/documentation/LocalAuthentication/LAContext/localizedReason",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "localizedReason"
        }
      ],
      "role": "symbol",
      "title": "localizedReason",
      "type": "topic",
      "url": "/documentation/localauthentication/lacontext/localizedreason"
    },
    "doc://com.externally.resolved.symbol/s:SS": {
      "abstract": [
        {
          "text": "A Unicode string value that is a collection of characters.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@frozen"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "String"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SS",
      "kind": "symbol",
      "role": "symbol",
      "title": "String",
      "type": "topic",
      "url": "/documentation/Swift/String"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Customizing-authentication-prompts",
      "generated": true,
      "identifiers": [
        "doc://com.apple.localauthentication/documentation/LocalAuthentication/LAContext/localizedFallbackTitle",
        "doc://com.apple.localauthentication/documentation/LocalAuthentication/LAContext/localizedCancelTitle"
      ],
      "title": "Customizing authentication prompts"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "11.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "11.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.1",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.13",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Instance Property"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "localizedReason"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "property"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "localizedReason"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.localauthentication/documentation/LocalAuthentication",
                "doc://com.apple.localauthentication/documentation/LocalAuthentication/LAContext"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Customizing-authentication-prompts",
              "generated": true,
              "identifiers": [
                "doc://com.apple.localauthentication/documentation/LocalAuthentication/LAContext/localizedFallbackTitle",
                "doc://com.apple.localauthentication/documentation/LocalAuthentication/LAContext/localizedCancelTitle"
              ],
              "title": "Customizing authentication prompts"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "@property"
                  },
                  {
                    "kind": "text",
                    "text": " ("
                  },
                  {
                    "kind": "keyword",
                    "text": "nonatomic"
                  },
                  {
                    "kind": "text",
                    "text": ", "
                  },
                  {
                    "kind": "keyword",
                    "text": "copy"
                  },
                  {
                    "kind": "text",
                    "text": ") "
                  },
                  {
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(cs)NSString",
                    "text": "NSString"
                  },
                  {
                    "kind": "text",
                    "text": " * "
                  },
                  {
                    "kind": "identifier",
                    "text": "localizedReason"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.localauthentication~1documentation~1LocalAuthentication~1LAContext~1evaluatePolicy(_:localizedReason:reply:)/title",
          "value": "evaluatePolicy:localizedReason:reply:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.localauthentication~1documentation~1LocalAuthentication~1LAContext~1evaluatePolicy(_:localizedReason:reply:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "evaluatePolicy:localizedReason:reply:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.localauthentication~1documentation~1LocalAuthentication~1LAContext~1localizedCancelTitle/title",
          "value": "localizedCancelTitle"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.localauthentication~1documentation~1LocalAuthentication~1LAContext~1localizedCancelTitle/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "localizedCancelTitle"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.localauthentication~1documentation~1LocalAuthentication~1LAContext~1localizedFallbackTitle/title",
          "value": "localizedFallbackTitle"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.localauthentication~1documentation~1LocalAuthentication~1LAContext~1localizedFallbackTitle/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "localizedFallbackTitle"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.localauthentication~1documentation~1LocalAuthentication~1LAContext~1localizedReason/title",
          "value": "localizedReason"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.localauthentication~1documentation~1LocalAuthentication~1LAContext~1localizedReason/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "localizedReason"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.localauthentication~1documentation~1LocalAuthentication~1LAContext/title",
          "value": "LAContext"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.localauthentication~1documentation~1LocalAuthentication~1LAContext/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "LAContext"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.localauthentication~1documentation~1LocalAuthentication~1LAContext/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "LAContext"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/localauthentication/lacontext/localizedreason"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/localauthentication/lacontext/localizedreason"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
