{
  "abstract": [
    {
      "text": "ARKit has not yet produced a classification for the plane anchor.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.arkit/documentation/ARKit",
        "doc://com.apple.arkit/documentation/ARKit/ARPlaneClassificationStatus"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "occ",
    "url": "doc://com.apple.arkit/documentation/ARKit/ARPlaneClassificationStatus/ARPlaneClassificationStatusUndetermined"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@ARPlaneClassificationStatus@ARPlaneClassificationStatusUndetermined",
    "fragments": [
      {
        "kind": "identifier",
        "text": "ARPlaneClassificationStatusUndetermined"
      }
    ],
    "modules": [
      {
        "name": "ARKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "ARPlaneClassificationStatusUndetermined"
      }
    ],
    "role": "symbol",
    "roleHeading": "Enumeration Case",
    "symbolKind": "case",
    "title": "ARPlaneClassificationStatusUndetermined"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "occ"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst"
          ],
          "tokens": [
            {
              "kind": "identifier",
              "text": "ARPlaneClassificationStatusUndetermined"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "This status occurs when ARKit is still in the process of plane classification. To be notified when ARKit produces a classification, observe the same plane anchor in a later frame (for example, in the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.arkit/documentation/ARKit/ARSessionDelegate/session(_:didUpdate:)-3qtt8",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " or ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.arkit/documentation/ARKit/ARSCNViewDelegate/renderer(_:didUpdate:for:)",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " delegate method).",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.arkit/documentation/ARKit": {
      "abstract": [
        {
          "text": "Integrate hardware sensing features to produce augmented reality apps and games.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.arkit/documentation/ARKit",
      "kind": "symbol",
      "role": "collection",
      "title": "ARKit",
      "type": "topic",
      "url": "/documentation/arkit"
    },
    "doc://com.apple.arkit/documentation/ARKit/ARPlaneClassificationStatus": {
      "abstract": [
        {
          "text": "Possible states of ARKit’s process for classifying plane anchors.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "ARPlaneClassificationStatus"
        }
      ],
      "identifier": "doc://com.apple.arkit/documentation/ARKit/ARPlaneClassificationStatus",
      "kind": "symbol",
      "role": "symbol",
      "title": "ARPlaneClassificationStatus",
      "type": "topic",
      "url": "/documentation/arkit/arplaneclassificationstatus"
    },
    "doc://com.apple.arkit/documentation/ARKit/ARPlaneClassificationStatus/ARPlaneClassificationStatusKnown": {
      "abstract": [
        {
          "text": "ARKit has completed its classfication process for the plane anchor.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "ARPlaneClassificationStatusKnown"
        }
      ],
      "identifier": "doc://com.apple.arkit/documentation/ARKit/ARPlaneClassificationStatus/ARPlaneClassificationStatusKnown",
      "kind": "symbol",
      "role": "symbol",
      "title": "ARPlaneClassificationStatusKnown",
      "type": "topic",
      "url": "/documentation/arkit/arplaneclassificationstatus/arplaneclassificationstatusknown"
    },
    "doc://com.apple.arkit/documentation/ARKit/ARPlaneClassificationStatus/ARPlaneClassificationStatusNotAvailable": {
      "abstract": [
        {
          "text": "ARKit cannot currently provide plane classification information.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "ARPlaneClassificationStatusNotAvailable"
        }
      ],
      "identifier": "doc://com.apple.arkit/documentation/ARKit/ARPlaneClassificationStatus/ARPlaneClassificationStatusNotAvailable",
      "kind": "symbol",
      "role": "symbol",
      "title": "ARPlaneClassificationStatusNotAvailable",
      "type": "topic",
      "url": "/documentation/arkit/arplaneclassificationstatus/arplaneclassificationstatusnotavailable"
    },
    "doc://com.apple.arkit/documentation/ARKit/ARPlaneClassificationStatus/ARPlaneClassificationStatusUndetermined": {
      "abstract": [
        {
          "text": "ARKit has not yet produced a classification for the plane anchor.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "ARPlaneClassificationStatusUndetermined"
        }
      ],
      "identifier": "doc://com.apple.arkit/documentation/ARKit/ARPlaneClassificationStatus/ARPlaneClassificationStatusUndetermined",
      "kind": "symbol",
      "role": "symbol",
      "title": "ARPlaneClassificationStatusUndetermined",
      "type": "topic",
      "url": "/documentation/arkit/arplaneclassificationstatus/arplaneclassificationstatusundetermined"
    },
    "doc://com.apple.arkit/documentation/ARKit/ARPlaneClassificationStatus/ARPlaneClassificationStatusUnknown": {
      "abstract": [
        {
          "text": "ARKit has completed its classification process for the plane anchor, but the result is inconclusive.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "ARPlaneClassificationStatusUnknown"
        }
      ],
      "identifier": "doc://com.apple.arkit/documentation/ARKit/ARPlaneClassificationStatus/ARPlaneClassificationStatusUnknown",
      "kind": "symbol",
      "role": "symbol",
      "title": "ARPlaneClassificationStatusUnknown",
      "type": "topic",
      "url": "/documentation/arkit/arplaneclassificationstatus/arplaneclassificationstatusunknown"
    },
    "doc://com.apple.arkit/documentation/ARKit/ARSCNViewDelegate/renderer(_:didUpdate:for:)": {
      "abstract": [
        {
          "text": "Tells the delegate that a SceneKit node’s properties have been updated to match the current state of its corresponding anchor.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "renderer"
        },
        {
          "kind": "text",
          "text": "(any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(pl)SCNSceneRenderer",
          "text": "SCNSceneRenderer"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "didUpdate"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)SCNNode",
          "text": "SCNNode"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "for"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)ARAnchor",
          "text": "ARAnchor"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.arkit/documentation/ARKit/ARSCNViewDelegate/renderer(_:didUpdate:for:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "renderer:didUpdateNode:forAnchor:"
        }
      ],
      "role": "symbol",
      "title": "renderer(_:didUpdate:for:)",
      "type": "topic",
      "url": "/documentation/arkit/arscnviewdelegate/renderer(_:didupdate:for:)"
    },
    "doc://com.apple.arkit/documentation/ARKit/ARSessionDelegate/session(_:didUpdate:)-3qtt8": {
      "abstract": [
        {
          "text": "Tells the delegate that the session has adjusted the properties of one or more anchors.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "session"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)ARSession",
          "text": "ARSession"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "didUpdate"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)ARAnchor",
          "text": "ARAnchor"
        },
        {
          "kind": "text",
          "text": "])"
        }
      ],
      "identifier": "doc://com.apple.arkit/documentation/ARKit/ARSessionDelegate/session(_:didUpdate:)-3qtt8",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "session:didUpdateAnchors:"
        }
      ],
      "role": "symbol",
      "title": "session(_:didUpdate:)",
      "type": "topic",
      "url": "/documentation/arkit/arsessiondelegate/session(_:didupdate:)-3qtt8"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Classification-Status",
      "generated": true,
      "identifiers": [
        "doc://com.apple.arkit/documentation/ARKit/ARPlaneClassificationStatus/ARPlaneClassificationStatusNotAvailable",
        "doc://com.apple.arkit/documentation/ARKit/ARPlaneClassificationStatus/ARPlaneClassificationStatusUnknown",
        "doc://com.apple.arkit/documentation/ARKit/ARPlaneClassificationStatus/ARPlaneClassificationStatusKnown"
      ],
      "title": "Classification Status"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.arkit~1documentation~1ARKit~1ARSCNViewDelegate~1renderer(_:didUpdate:for:)/title",
          "value": "renderer:didUpdateNode:forAnchor:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.arkit~1documentation~1ARKit~1ARSCNViewDelegate~1renderer(_:didUpdate:for:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "renderer:didUpdateNode:forAnchor:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.arkit~1documentation~1ARKit~1ARSessionDelegate~1session(_:didUpdate:)-3qtt8/title",
          "value": "session:didUpdateAnchors:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.arkit~1documentation~1ARKit~1ARSessionDelegate~1session(_:didUpdate:)-3qtt8/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "session:didUpdateAnchors:"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/arkit/arplaneclassificationstatus/arplaneclassificationstatusundetermined"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
