{
  "abstract": [
    {
      "text": "Posted when the value returned by the ",
      "type": "text"
    },
    {
      "identifier": "doc://com.apple.messageui/documentation/MessageUI/MFMessageComposeViewController/canSendText()",
      "isActive": true,
      "type": "reference"
    },
    {
      "text": " class method has changed.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.messageui/documentation/MessageUI"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "occ",
    "url": "doc://com.apple.messageui/documentation/MessageUI/NSNotification/Name/MFMessageComposeViewControllerTextMessageAvailabilityDidChange"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@MFMessageComposeViewControllerTextMessageAvailabilityDidChangeNotification",
    "fragments": [
      {
        "kind": "identifier",
        "text": "MFMessageComposeViewControllerTextMessageAvailabilityDidChangeNotification"
      }
    ],
    "modules": [
      {
        "name": "Message UI"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "MFMessageComposeViewControllerTextMessageAvailabilityDidChangeNotification"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "5.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "5.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.1",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Global Variable",
    "symbolKind": "var",
    "title": "MFMessageComposeViewControllerTextMessageAvailabilityDidChangeNotification"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "occ"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "extern"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSString",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)NSString",
              "text": "NSString"
            },
            {
              "kind": "text",
              "text": " * "
            },
            {
              "kind": "keyword",
              "text": "const"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "MFMessageComposeViewControllerTextMessageAvailabilityDidChangeNotification"
            },
            {
              "kind": "text",
              "text": ";"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Upon receiving this notification, query its ",
              "type": "text"
            },
            {
              "code": "userInfo",
              "type": "codeVoice"
            },
            {
              "text": " dictionary with the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.messageui/documentation/MessageUI/MFMessageComposeViewControllerTextMessageAvailabilityKey",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " key. If the availability of text message sending has changed, your app should invalidate caches and update its user interface as appropriate.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/foundation/nsnotification/name/1614064-mfmessagecomposeviewcontrollerte": {
      "abstract": [
        {
          "text": "Posted when the value returned by the  class method has changed.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "static let "
        },
        {
          "kind": "identifier",
          "text": "MFMessageComposeViewControllerTextMessageAvailabilityDidChange"
        },
        {
          "kind": "text",
          "text": ": NSNotification.Name"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/foundation/nsnotification/name/1614064-mfmessagecomposeviewcontrollerte",
      "kind": "symbol",
      "role": "symbol",
      "title": "MFMessageComposeViewControllerTextMessageAvailabilityDidChange",
      "type": "topic",
      "url": "/documentation/foundation/nsnotification/name/1614064-mfmessagecomposeviewcontrollerte"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.messageui/documentation/MessageUI": {
      "abstract": [
        {
          "text": "Create a user interface for composing email and text messages, so users can edit and send messages without leaving your app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.messageui/documentation/MessageUI",
      "kind": "symbol",
      "role": "collection",
      "title": "Message UI",
      "type": "topic",
      "url": "/documentation/messageui"
    },
    "doc://com.apple.messageui/documentation/MessageUI/MFMessageComposeViewController/canSendText()": {
      "abstract": [
        {
          "text": "Returns a Boolean value that indicates whether the current device is capable of sending text messages.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "canSendText"
        },
        {
          "kind": "text",
          "text": "() -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.messageui/documentation/MessageUI/MFMessageComposeViewController/canSendText()",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "canSendText"
        }
      ],
      "role": "symbol",
      "title": "canSendText()",
      "type": "topic",
      "url": "/documentation/messageui/mfmessagecomposeviewcontroller/cansendtext()"
    },
    "doc://com.apple.messageui/documentation/MessageUI/MFMessageComposeViewControllerTextMessageAvailabilityKey": {
      "abstract": [
        {
          "text": "The value of this key is a number object that contains a Boolean value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MFMessageComposeViewControllerTextMessageAvailabilityKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.messageui/documentation/MessageUI/MFMessageComposeViewControllerTextMessageAvailabilityKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MFMessageComposeViewControllerTextMessageAvailabilityKey"
        }
      ],
      "role": "symbol",
      "title": "MFMessageComposeViewControllerTextMessageAvailabilityKey",
      "type": "topic",
      "url": "/documentation/messageui/mfmessagecomposeviewcontrollertextmessageavailabilitykey"
    },
    "doc://com.apple.messageui/documentation/MessageUI/NSNotification/Name/MFMessageComposeViewControllerTextMessageAvailabilityDidChange": {
      "abstract": [
        {
          "text": "Posted when the value returned by the ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.messageui/documentation/MessageUI/MFMessageComposeViewController/canSendText()",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " class method has changed.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "MFMessageComposeViewControllerTextMessageAvailabilityDidChangeNotification"
        }
      ],
      "identifier": "doc://com.apple.messageui/documentation/MessageUI/NSNotification/Name/MFMessageComposeViewControllerTextMessageAvailabilityDidChange",
      "kind": "symbol",
      "role": "symbol",
      "title": "MFMessageComposeViewControllerTextMessageAvailabilityDidChangeNotification",
      "type": "topic",
      "url": "/documentation/messageui/nsnotification/name/mfmessagecomposeviewcontrollertextmessageavailabilitydidchange"
    },
    "doc://com.externally.resolved.symbol/c:objc(cs)NSString": {
      "abstract": [
        {
          "text": "A static, plain-text Unicode string object which you use when you need reference semantics or other Foundation-specific behavior. ",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "class "
        },
        {
          "kind": "identifier",
          "text": "NSString"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSString",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSString",
      "type": "topic",
      "url": "/documentation/foundation/nsstring"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Handling-notifications",
      "generated": true,
      "identifiers": [
        "doc://com.apple.documentation/documentation/foundation/nsnotification/name/1614064-mfmessagecomposeviewcontrollerte",
        "doc://com.apple.messageui/documentation/MessageUI/MFMessageComposeViewControllerTextMessageAvailabilityKey"
      ],
      "title": "Handling notifications"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.messageui~1documentation~1MessageUI~1MFMessageComposeViewController~1canSendText()/title",
          "value": "canSendText"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.messageui~1documentation~1MessageUI~1MFMessageComposeViewController~1canSendText()/fragments",
          "value": [
            {
              "kind": "text",
              "text": "+ "
            },
            {
              "kind": "identifier",
              "text": "canSendText"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.messageui~1documentation~1MessageUI~1MFMessageComposeViewControllerTextMessageAvailabilityKey/title",
          "value": "MFMessageComposeViewControllerTextMessageAvailabilityKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.messageui~1documentation~1MessageUI~1MFMessageComposeViewControllerTextMessageAvailabilityKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MFMessageComposeViewControllerTextMessageAvailabilityKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:objc(cs)NSString/abstract",
          "value": [
            {
              "text": "A static, plain-text Unicode string object.",
              "type": "text"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/messageui/nsnotification/name/mfmessagecomposeviewcontrollertextmessageavailabilitydidchange"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
