{
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.coremediaio/documentation/CoreMediaIO",
        "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOStreamScheduledOutputNotificationProcAndRefCon"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOStreamScheduledOutputNotificationProcAndRefCon/init(scheduledOutputNotificationProc:scheduledOutputNotificationRefCon:)"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "s:So50CMIOStreamScheduledOutputNotificationProcAndRefConV09scheduledcdE00icdgH0ABys6UInt64V_AFSvSgtXCSg_AGtcfc",
    "fragments": [
      {
        "kind": "identifier",
        "text": "init"
      },
      {
        "kind": "text",
        "text": "("
      },
      {
        "kind": "externalParam",
        "text": "scheduledOutputNotificationProc"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@T@CMIOStreamScheduledOutputNotificationProc",
        "text": "CMIOStreamScheduledOutputNotificationProc"
      },
      {
        "kind": "text",
        "text": "!, "
      },
      {
        "kind": "externalParam",
        "text": "scheduledOutputNotificationRefCon"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "s:Sv",
        "text": "UnsafeMutableRawPointer"
      },
      {
        "kind": "text",
        "text": "!)"
      }
    ],
    "modules": [
      {
        "name": "Core Media I/O"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.1",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.8",
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Initializer",
    "symbolKind": "init",
    "title": "init(scheduledOutputNotificationProc:scheduledOutputNotificationRefCon:)"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "Mac Catalyst",
            "macOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "init"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "kind": "externalParam",
              "text": "scheduledOutputNotificationProc"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOStreamScheduledOutputNotificationProc",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@CMIOStreamScheduledOutputNotificationProc",
              "text": "CMIOStreamScheduledOutputNotificationProc"
            },
            {
              "kind": "text",
              "text": "!, "
            },
            {
              "kind": "externalParam",
              "text": "scheduledOutputNotificationRefCon"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:Sv",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:Sv",
              "text": "UnsafeMutableRawPointer"
            },
            {
              "kind": "text",
              "text": "!)"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.coremediaio/documentation/CoreMediaIO": {
      "abstract": [
        {
          "text": "Securely support custom camera devices in macOS.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.coremediaio/documentation/CoreMediaIO",
      "kind": "symbol",
      "role": "collection",
      "title": "Core Media I/O",
      "type": "topic",
      "url": "/documentation/coremediaio"
    },
    "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOStreamScheduledOutputNotificationProc": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CMIOStreamScheduledOutputNotificationProc"
        }
      ],
      "identifier": "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOStreamScheduledOutputNotificationProc",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CMIOStreamScheduledOutputNotificationProc"
        }
      ],
      "role": "symbol",
      "title": "CMIOStreamScheduledOutputNotificationProc",
      "type": "topic",
      "url": "/documentation/coremediaio/cmiostreamscheduledoutputnotificationproc"
    },
    "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOStreamScheduledOutputNotificationProcAndRefCon": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CMIOStreamScheduledOutputNotificationProcAndRefCon"
        }
      ],
      "identifier": "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOStreamScheduledOutputNotificationProcAndRefCon",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CMIOStreamScheduledOutputNotificationProcAndRefCon"
        }
      ],
      "role": "symbol",
      "title": "CMIOStreamScheduledOutputNotificationProcAndRefCon",
      "type": "topic",
      "url": "/documentation/coremediaio/cmiostreamscheduledoutputnotificationprocandrefcon"
    },
    "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOStreamScheduledOutputNotificationProcAndRefCon/init(scheduledOutputNotificationProc:scheduledOutputNotificationRefCon:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "scheduledOutputNotificationProc"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CMIOStreamScheduledOutputNotificationProc",
          "text": "CMIOStreamScheduledOutputNotificationProc"
        },
        {
          "kind": "text",
          "text": "!, "
        },
        {
          "kind": "externalParam",
          "text": "scheduledOutputNotificationRefCon"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sv",
          "text": "UnsafeMutableRawPointer"
        },
        {
          "kind": "text",
          "text": "!)"
        }
      ],
      "identifier": "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOStreamScheduledOutputNotificationProcAndRefCon/init(scheduledOutputNotificationProc:scheduledOutputNotificationRefCon:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "init(scheduledOutputNotificationProc:scheduledOutputNotificationRefCon:)",
      "type": "topic",
      "url": "/documentation/coremediaio/cmiostreamscheduledoutputnotificationprocandrefcon/init(scheduledoutputnotificationproc:scheduledoutputnotificationrefcon:)"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.externally.resolved.symbol/s:Sv": {
      "abstract": [
        {
          "text": "A raw pointer for accessing and manipulating untyped data.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@frozen"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UnsafeMutableRawPointer"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:Sv",
      "kind": "symbol",
      "role": "symbol",
      "title": "UnsafeMutableRawPointer",
      "type": "topic",
      "url": "/documentation/Swift/UnsafeMutableRawPointer"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1CMIOStreamScheduledOutputNotificationProcAndRefCon/title",
          "value": "CMIOStreamScheduledOutputNotificationProcAndRefCon"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1CMIOStreamScheduledOutputNotificationProcAndRefCon/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CMIOStreamScheduledOutputNotificationProcAndRefCon"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1CMIOStreamScheduledOutputNotificationProcAndRefCon/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CMIOStreamScheduledOutputNotificationProcAndRefCon"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1CMIOStreamScheduledOutputNotificationProc/title",
          "value": "CMIOStreamScheduledOutputNotificationProc"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1CMIOStreamScheduledOutputNotificationProc/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CMIOStreamScheduledOutputNotificationProc"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1CMIOStreamScheduledOutputNotificationProc/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CMIOStreamScheduledOutputNotificationProc"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/coremediaio/cmiostreamscheduledoutputnotificationprocandrefcon/init(scheduledoutputnotificationproc:scheduledoutputnotificationrefcon:)"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    }
  ]
}
