{
  "abstract": [
    {
      "text": "Checks whether the code associated with a running process satisfies a lightweight code requirement.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.LightweightCodeRequirements/documentation/LightweightCodeRequirements"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.LightweightCodeRequirements/documentation/LightweightCodeRequirements/SecCodeCheckValidityWithProcessRequirement(code:flags:requirement:)"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "s:27LightweightCodeRequirements03SecB35CheckValidityWithProcessRequirement4code5flags11requirementAA16ValidationResultVSo0dB3Refa_So0D7CSFlagsVAA0hbI0VtF",
    "fragments": [
      {
        "kind": "keyword",
        "text": "func"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "SecCodeCheckValidityWithProcessRequirement"
      },
      {
        "kind": "text",
        "text": "("
      },
      {
        "kind": "externalParam",
        "text": "code"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@T@SecCodeRef",
        "text": "SecCode"
      },
      {
        "kind": "text",
        "text": ", "
      },
      {
        "kind": "externalParam",
        "text": "flags"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@E@SecCSFlags",
        "text": "SecCSFlags"
      },
      {
        "kind": "text",
        "text": ", "
      },
      {
        "kind": "externalParam",
        "text": "requirement"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "s:27LightweightCodeRequirements07ProcessB11RequirementV",
        "text": "ProcessCodeRequirement"
      },
      {
        "kind": "text",
        "text": ") -> "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "s:27LightweightCodeRequirements16ValidationResultV",
        "text": "ValidationResult"
      }
    ],
    "modules": [
      {
        "name": "LightweightCodeRequirements"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "18.0",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "15.0",
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Function",
    "symbolKind": "func",
    "title": "SecCodeCheckValidityWithProcessRequirement(code:flags:requirement:)"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "Mac Catalyst",
            "macOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "func"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "SecCodeCheckValidityWithProcessRequirement"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "kind": "externalParam",
              "text": "code"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/c:@T@SecCodeRef",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@SecCodeRef",
              "text": "SecCode"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "kind": "externalParam",
              "text": "flags"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/c:@E@SecCSFlags",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@E@SecCSFlags",
              "text": "SecCSFlags"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "kind": "externalParam",
              "text": "requirement"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.LightweightCodeRequirements/documentation/LightweightCodeRequirements/ProcessCodeRequirement",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:27LightweightCodeRequirements07ProcessB11RequirementV",
              "text": "ProcessCodeRequirement"
            },
            {
              "kind": "text",
              "text": ") -> "
            },
            {
              "identifier": "doc://com.apple.LightweightCodeRequirements/documentation/LightweightCodeRequirements/ValidationResult",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:27LightweightCodeRequirements16ValidationResultV",
              "text": "ValidationResult"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Returns a validation result which indicates whether the code signature is valid, whether it matches the requirement, and if not one of those two, then why not.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.LightweightCodeRequirements/documentation/LightweightCodeRequirements": {
      "abstract": [
        {
          "text": "Test the identity of executable code on disk and in running processes.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.LightweightCodeRequirements/documentation/LightweightCodeRequirements",
      "kind": "symbol",
      "role": "collection",
      "title": "LightweightCodeRequirements",
      "type": "topic",
      "url": "/documentation/lightweightcoderequirements"
    },
    "doc://com.apple.LightweightCodeRequirements/documentation/LightweightCodeRequirements/LaunchCodeRequirement": {
      "abstract": [
        {
          "text": "A lightweight code requirement that you use to evaluate the executable for a launching process.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "LaunchCodeRequirement"
        }
      ],
      "identifier": "doc://com.apple.LightweightCodeRequirements/documentation/LightweightCodeRequirements/LaunchCodeRequirement",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "LaunchCodeRequirement"
        }
      ],
      "role": "symbol",
      "title": "LaunchCodeRequirement",
      "type": "topic",
      "url": "/documentation/lightweightcoderequirements/launchcoderequirement"
    },
    "doc://com.apple.LightweightCodeRequirements/documentation/LightweightCodeRequirements/LaunchConstraint": {
      "abstract": [
        {
          "text": "A protocol to which a lightweight code requirement constraint conforms if you can use it in launch code requirements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "LaunchConstraint"
        }
      ],
      "identifier": "doc://com.apple.LightweightCodeRequirements/documentation/LightweightCodeRequirements/LaunchConstraint",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "LaunchConstraint"
        }
      ],
      "role": "symbol",
      "title": "LaunchConstraint",
      "type": "topic",
      "url": "/documentation/lightweightcoderequirements/launchconstraint"
    },
    "doc://com.apple.LightweightCodeRequirements/documentation/LightweightCodeRequirements/LaunchConstraintBuilder": {
      "abstract": [
        {
          "text": "A custom parameter attribute that constructs launch constraints from closures.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "LaunchConstraintBuilder"
        }
      ],
      "identifier": "doc://com.apple.LightweightCodeRequirements/documentation/LightweightCodeRequirements/LaunchConstraintBuilder",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "LaunchConstraintBuilder"
        }
      ],
      "role": "symbol",
      "title": "LaunchConstraintBuilder",
      "type": "topic",
      "url": "/documentation/lightweightcoderequirements/launchconstraintbuilder"
    },
    "doc://com.apple.LightweightCodeRequirements/documentation/LightweightCodeRequirements/ProcessCodeRequirement": {
      "abstract": [
        {
          "text": "A lightweight code requirement that you use to evaluate a running process.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ProcessCodeRequirement"
        }
      ],
      "identifier": "doc://com.apple.LightweightCodeRequirements/documentation/LightweightCodeRequirements/ProcessCodeRequirement",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ProcessCodeRequirement"
        }
      ],
      "role": "symbol",
      "title": "ProcessCodeRequirement",
      "type": "topic",
      "url": "/documentation/lightweightcoderequirements/processcoderequirement"
    },
    "doc://com.apple.LightweightCodeRequirements/documentation/LightweightCodeRequirements/SecCodeCheckValidityWithProcessRequirement(code:flags:requirement:)": {
      "abstract": [
        {
          "text": "Checks whether the code associated with a running process satisfies a lightweight code requirement.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SecCodeCheckValidityWithProcessRequirement"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "code"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@SecCodeRef",
          "text": "SecCode"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "flags"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@SecCSFlags",
          "text": "SecCSFlags"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "requirement"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:27LightweightCodeRequirements07ProcessB11RequirementV",
          "text": "ProcessCodeRequirement"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:27LightweightCodeRequirements16ValidationResultV",
          "text": "ValidationResult"
        }
      ],
      "identifier": "doc://com.apple.LightweightCodeRequirements/documentation/LightweightCodeRequirements/SecCodeCheckValidityWithProcessRequirement(code:flags:requirement:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "SecCodeCheckValidityWithProcessRequirement(code:flags:requirement:)",
      "type": "topic",
      "url": "/documentation/lightweightcoderequirements/seccodecheckvaliditywithprocessrequirement(code:flags:requirement:)"
    },
    "doc://com.apple.LightweightCodeRequirements/documentation/LightweightCodeRequirements/ValidationResult": {
      "abstract": [
        {
          "text": "A structure that represents the result of testing a lightweight code requirement.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ValidationResult"
        }
      ],
      "identifier": "doc://com.apple.LightweightCodeRequirements/documentation/LightweightCodeRequirements/ValidationResult",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ValidationResult"
        }
      ],
      "role": "symbol",
      "title": "ValidationResult",
      "type": "topic",
      "url": "/documentation/lightweightcoderequirements/validationresult"
    },
    "doc://com.apple.LightweightCodeRequirements/documentation/LightweightCodeRequirements/allOf(requirement:)-4gf5f": {
      "abstract": [
        {
          "text": "Creates a constraint that requires a launching process’s executable to satisfy all of the provided constraints.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "allOf"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "requirement"
        },
        {
          "kind": "text",
          "text": ": () -> [any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:27LightweightCodeRequirements16LaunchConstraintP",
          "text": "LaunchConstraint"
        },
        {
          "kind": "text",
          "text": "]) -> any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:27LightweightCodeRequirements16LaunchConstraintP",
          "text": "LaunchConstraint"
        }
      ],
      "identifier": "doc://com.apple.LightweightCodeRequirements/documentation/LightweightCodeRequirements/allOf(requirement:)-4gf5f",
      "kind": "symbol",
      "role": "symbol",
      "title": "allOf(requirement:)",
      "type": "topic",
      "url": "/documentation/lightweightcoderequirements/allof(requirement:)-4gf5f"
    },
    "doc://com.apple.LightweightCodeRequirements/documentation/LightweightCodeRequirements/anyOf(requirement:)-6nicx": {
      "abstract": [
        {
          "text": "Creates a constraint that requires a launching process’s executable to satisfy any of the provided constraints.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "anyOf"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "requirement"
        },
        {
          "kind": "text",
          "text": ": () -> [any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:27LightweightCodeRequirements16LaunchConstraintP",
          "text": "LaunchConstraint"
        },
        {
          "kind": "text",
          "text": "]) -> any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:27LightweightCodeRequirements16LaunchConstraintP",
          "text": "LaunchConstraint"
        }
      ],
      "identifier": "doc://com.apple.LightweightCodeRequirements/documentation/LightweightCodeRequirements/anyOf(requirement:)-6nicx",
      "kind": "symbol",
      "role": "symbol",
      "title": "anyOf(requirement:)",
      "type": "topic",
      "url": "/documentation/lightweightcoderequirements/anyof(requirement:)-6nicx"
    },
    "doc://com.apple.documentation/documentation/foundation/process/4322522-launchrequirement": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "var "
        },
        {
          "kind": "identifier",
          "text": "launchRequirement"
        },
        {
          "kind": "text",
          "text": ": LaunchCodeRequirement?"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/foundation/process/4322522-launchrequirement",
      "kind": "symbol",
      "role": "symbol",
      "title": "launchRequirement",
      "type": "topic",
      "url": "/documentation/foundation/process/4322522-launchrequirement"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.externally.resolved.symbol/c:@E@SecCSFlags": {
      "abstract": [
        {
          "text": "Values that can be used in the `flags` parameter to most code signing functions.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SecCSFlags"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:@E@SecCSFlags",
      "kind": "symbol",
      "role": "symbol",
      "title": "SecCSFlags",
      "type": "topic",
      "url": "/documentation/Security/SecCSFlags"
    },
    "doc://com.externally.resolved.symbol/c:@T@SecCodeRef": {
      "abstract": [
        {
          "text": "A code object representing signed code running on the system.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SecCode"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:@T@SecCodeRef",
      "kind": "symbol",
      "role": "symbol",
      "title": "SecCode",
      "type": "topic",
      "url": "/documentation/Security/SecCode"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Checking-code-requirements-for-launching-processes",
      "generated": true,
      "identifiers": [
        "doc://com.apple.documentation/documentation/foundation/process/4322522-launchrequirement",
        "doc://com.apple.LightweightCodeRequirements/documentation/LightweightCodeRequirements/LaunchCodeRequirement",
        "doc://com.apple.LightweightCodeRequirements/documentation/LightweightCodeRequirements/allOf(requirement:)-4gf5f",
        "doc://com.apple.LightweightCodeRequirements/documentation/LightweightCodeRequirements/anyOf(requirement:)-6nicx",
        "doc://com.apple.LightweightCodeRequirements/documentation/LightweightCodeRequirements/LaunchConstraint",
        "doc://com.apple.LightweightCodeRequirements/documentation/LightweightCodeRequirements/LaunchConstraintBuilder"
      ],
      "title": "Checking code requirements for launching processes"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:@T@SecCodeRef/title",
          "value": "SecCodeRef"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:@T@SecCodeRef/fragments",
          "value": [
            {
              "kind": "keyword",
              "text": "typedef"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "keyword",
              "text": "struct"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@S@__SecCode",
              "text": "__SecCode"
            },
            {
              "kind": "text",
              "text": " * "
            },
            {
              "kind": "identifier",
              "text": "SecCodeRef"
            },
            {
              "kind": "text",
              "text": ";"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:@E@SecCSFlags/fragments",
          "value": [
            {
              "kind": "keyword",
              "text": "enum"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "SecCSFlags"
            },
            {
              "kind": "text",
              "text": " : "
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@uint32_t",
              "text": "uint32_t"
            },
            {
              "kind": "text",
              "text": ";"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/lightweightcoderequirements/seccodecheckvaliditywithprocessrequirement(code:flags:requirement:)"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    }
  ]
}
