{
  "abstract": [
    {
      "text": "Checks whether static code on disk satisfies a lightweight code requirement.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.LightweightCodeRequirements/documentation/LightweightCodeRequirements"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.LightweightCodeRequirements/documentation/LightweightCodeRequirements/SecStaticCodeCheckValidityWithOnDiskRequirement(code:flags:requirement:)"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "s:27LightweightCodeRequirements09SecStaticB34CheckValidityWithOnDiskRequirement4code5flags11requirementAA16ValidationResultVSo0deB3Refa_So0D7CSFlagsVAA0ijbK0VtF",
    "fragments": [
      {
        "kind": "keyword",
        "text": "func"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "SecStaticCodeCheckValidityWithOnDiskRequirement"
      },
      {
        "kind": "text",
        "text": "("
      },
      {
        "kind": "externalParam",
        "text": "code"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@T@SecStaticCodeRef",
        "text": "SecStaticCode"
      },
      {
        "kind": "text",
        "text": ", "
      },
      {
        "kind": "externalParam",
        "text": "flags"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@E@SecCSFlags",
        "text": "SecCSFlags"
      },
      {
        "kind": "text",
        "text": ", "
      },
      {
        "kind": "externalParam",
        "text": "requirement"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "s:27LightweightCodeRequirements06OnDiskB11RequirementV",
        "text": "OnDiskCodeRequirement"
      },
      {
        "kind": "text",
        "text": ") -> "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "s:27LightweightCodeRequirements16ValidationResultV",
        "text": "ValidationResult"
      }
    ],
    "modules": [
      {
        "name": "LightweightCodeRequirements"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "17.4",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "14.4",
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Function",
    "symbolKind": "func",
    "title": "SecStaticCodeCheckValidityWithOnDiskRequirement(code:flags:requirement:)"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "Mac Catalyst",
            "macOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "func"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "SecStaticCodeCheckValidityWithOnDiskRequirement"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "kind": "externalParam",
              "text": "code"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/c:@T@SecStaticCodeRef",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@SecStaticCodeRef",
              "text": "SecStaticCode"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "kind": "externalParam",
              "text": "flags"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/c:@E@SecCSFlags",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@E@SecCSFlags",
              "text": "SecCSFlags"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "kind": "externalParam",
              "text": "requirement"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.LightweightCodeRequirements/documentation/LightweightCodeRequirements/OnDiskCodeRequirement",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:27LightweightCodeRequirements06OnDiskB11RequirementV",
              "text": "OnDiskCodeRequirement"
            },
            {
              "kind": "text",
              "text": ") -> "
            },
            {
              "identifier": "doc://com.apple.LightweightCodeRequirements/documentation/LightweightCodeRequirements/ValidationResult",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:27LightweightCodeRequirements16ValidationResultV",
              "text": "ValidationResult"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Returns a validation result which indicates whether the code signature is valid, whether it matches the requirement, and if not one of those two, then why not.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.LightweightCodeRequirements/documentation/LightweightCodeRequirements": {
      "abstract": [
        {
          "text": "Test the identity of executable code on disk and in running processes.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.LightweightCodeRequirements/documentation/LightweightCodeRequirements",
      "kind": "symbol",
      "role": "collection",
      "title": "LightweightCodeRequirements",
      "type": "topic",
      "url": "/documentation/lightweightcoderequirements"
    },
    "doc://com.apple.LightweightCodeRequirements/documentation/LightweightCodeRequirements/OnDiskCodeRequirement": {
      "abstract": [
        {
          "text": "A lightweight code requirement that you use to evaluate a code file on disk.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "OnDiskCodeRequirement"
        }
      ],
      "identifier": "doc://com.apple.LightweightCodeRequirements/documentation/LightweightCodeRequirements/OnDiskCodeRequirement",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "OnDiskCodeRequirement"
        }
      ],
      "role": "symbol",
      "title": "OnDiskCodeRequirement",
      "type": "topic",
      "url": "/documentation/lightweightcoderequirements/ondiskcoderequirement"
    },
    "doc://com.apple.LightweightCodeRequirements/documentation/LightweightCodeRequirements/OnDiskCodeSigningFlags": {
      "abstract": [
        {
          "text": "A constraint that tests the code-signing flags of a code file on disk.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "OnDiskCodeSigningFlags"
        }
      ],
      "identifier": "doc://com.apple.LightweightCodeRequirements/documentation/LightweightCodeRequirements/OnDiskCodeSigningFlags",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "OnDiskCodeSigningFlags"
        }
      ],
      "role": "symbol",
      "title": "OnDiskCodeSigningFlags",
      "type": "topic",
      "url": "/documentation/lightweightcoderequirements/ondiskcodesigningflags"
    },
    "doc://com.apple.LightweightCodeRequirements/documentation/LightweightCodeRequirements/OnDiskConstraint": {
      "abstract": [
        {
          "text": "A protocol to which a lightweight code requirement constraint conforms if you can use it in on-disk code requirements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "OnDiskConstraint"
        }
      ],
      "identifier": "doc://com.apple.LightweightCodeRequirements/documentation/LightweightCodeRequirements/OnDiskConstraint",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "OnDiskConstraint"
        }
      ],
      "role": "symbol",
      "title": "OnDiskConstraint",
      "type": "topic",
      "url": "/documentation/lightweightcoderequirements/ondiskconstraint"
    },
    "doc://com.apple.LightweightCodeRequirements/documentation/LightweightCodeRequirements/OnDiskConstraintBuilder": {
      "abstract": [
        {
          "text": "A custom parameter attribute that constructs on-disk constraints from closures.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "OnDiskConstraintBuilder"
        }
      ],
      "identifier": "doc://com.apple.LightweightCodeRequirements/documentation/LightweightCodeRequirements/OnDiskConstraintBuilder",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "OnDiskConstraintBuilder"
        }
      ],
      "role": "symbol",
      "title": "OnDiskConstraintBuilder",
      "type": "topic",
      "url": "/documentation/lightweightcoderequirements/ondiskconstraintbuilder"
    },
    "doc://com.apple.LightweightCodeRequirements/documentation/LightweightCodeRequirements/SecCodeCheckValidityWithOnDiskRequirement(code:flags:requirement:)": {
      "abstract": [
        {
          "text": "Checks whether code on disk satisfies a lightweight code requirement.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SecCodeCheckValidityWithOnDiskRequirement"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "code"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@SecCodeRef",
          "text": "SecCode"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "flags"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@SecCSFlags",
          "text": "SecCSFlags"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "requirement"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:27LightweightCodeRequirements06OnDiskB11RequirementV",
          "text": "OnDiskCodeRequirement"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:27LightweightCodeRequirements16ValidationResultV",
          "text": "ValidationResult"
        }
      ],
      "identifier": "doc://com.apple.LightweightCodeRequirements/documentation/LightweightCodeRequirements/SecCodeCheckValidityWithOnDiskRequirement(code:flags:requirement:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "SecCodeCheckValidityWithOnDiskRequirement(code:flags:requirement:)",
      "type": "topic",
      "url": "/documentation/lightweightcoderequirements/seccodecheckvaliditywithondiskrequirement(code:flags:requirement:)"
    },
    "doc://com.apple.LightweightCodeRequirements/documentation/LightweightCodeRequirements/SecStaticCodeCheckValidityWithOnDiskRequirement(code:flags:requirement:)": {
      "abstract": [
        {
          "text": "Checks whether static code on disk satisfies a lightweight code requirement.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SecStaticCodeCheckValidityWithOnDiskRequirement"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "code"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@SecStaticCodeRef",
          "text": "SecStaticCode"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "flags"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@SecCSFlags",
          "text": "SecCSFlags"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "requirement"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:27LightweightCodeRequirements06OnDiskB11RequirementV",
          "text": "OnDiskCodeRequirement"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:27LightweightCodeRequirements16ValidationResultV",
          "text": "ValidationResult"
        }
      ],
      "identifier": "doc://com.apple.LightweightCodeRequirements/documentation/LightweightCodeRequirements/SecStaticCodeCheckValidityWithOnDiskRequirement(code:flags:requirement:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "SecStaticCodeCheckValidityWithOnDiskRequirement(code:flags:requirement:)",
      "type": "topic",
      "url": "/documentation/lightweightcoderequirements/secstaticcodecheckvaliditywithondiskrequirement(code:flags:requirement:)"
    },
    "doc://com.apple.LightweightCodeRequirements/documentation/LightweightCodeRequirements/ValidationResult": {
      "abstract": [
        {
          "text": "A structure that represents the result of testing a lightweight code requirement.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ValidationResult"
        }
      ],
      "identifier": "doc://com.apple.LightweightCodeRequirements/documentation/LightweightCodeRequirements/ValidationResult",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ValidationResult"
        }
      ],
      "role": "symbol",
      "title": "ValidationResult",
      "type": "topic",
      "url": "/documentation/lightweightcoderequirements/validationresult"
    },
    "doc://com.apple.LightweightCodeRequirements/documentation/LightweightCodeRequirements/allOf(requirement:)-2ocwl": {
      "abstract": [
        {
          "text": "Creates a constraint that requires code on disk to satisfy all of the provided constraints.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "allOf"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "requirement"
        },
        {
          "kind": "text",
          "text": ": () -> [any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:27LightweightCodeRequirements16OnDiskConstraintP",
          "text": "OnDiskConstraint"
        },
        {
          "kind": "text",
          "text": "]) -> any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:27LightweightCodeRequirements16OnDiskConstraintP",
          "text": "OnDiskConstraint"
        }
      ],
      "identifier": "doc://com.apple.LightweightCodeRequirements/documentation/LightweightCodeRequirements/allOf(requirement:)-2ocwl",
      "kind": "symbol",
      "role": "symbol",
      "title": "allOf(requirement:)",
      "type": "topic",
      "url": "/documentation/lightweightcoderequirements/allof(requirement:)-2ocwl"
    },
    "doc://com.apple.LightweightCodeRequirements/documentation/LightweightCodeRequirements/anyOf(requirement:)-71pff": {
      "abstract": [
        {
          "text": "Creates a constraint that requires code on disk to satisfy any of the provided constraints.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "anyOf"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "requirement"
        },
        {
          "kind": "text",
          "text": ": () -> [any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:27LightweightCodeRequirements16OnDiskConstraintP",
          "text": "OnDiskConstraint"
        },
        {
          "kind": "text",
          "text": "]) -> any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:27LightweightCodeRequirements16OnDiskConstraintP",
          "text": "OnDiskConstraint"
        }
      ],
      "identifier": "doc://com.apple.LightweightCodeRequirements/documentation/LightweightCodeRequirements/anyOf(requirement:)-71pff",
      "kind": "symbol",
      "role": "symbol",
      "title": "anyOf(requirement:)",
      "type": "topic",
      "url": "/documentation/lightweightcoderequirements/anyof(requirement:)-71pff"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.externally.resolved.symbol/c:@E@SecCSFlags": {
      "abstract": [
        {
          "text": "Values that can be used in the `flags` parameter to most code signing functions.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SecCSFlags"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:@E@SecCSFlags",
      "kind": "symbol",
      "role": "symbol",
      "title": "SecCSFlags",
      "type": "topic",
      "url": "/documentation/Security/SecCSFlags"
    },
    "doc://com.externally.resolved.symbol/c:@T@SecStaticCodeRef": {
      "abstract": [
        {
          "text": "A static code object representing signed code on disk.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SecStaticCode"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:@T@SecStaticCodeRef",
      "kind": "symbol",
      "role": "symbol",
      "title": "SecStaticCode",
      "type": "topic",
      "url": "/documentation/Security/SecStaticCode"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Checking-code-requirements-for-code-files-on-disk",
      "generated": true,
      "identifiers": [
        "doc://com.apple.LightweightCodeRequirements/documentation/LightweightCodeRequirements/SecCodeCheckValidityWithOnDiskRequirement(code:flags:requirement:)",
        "doc://com.apple.LightweightCodeRequirements/documentation/LightweightCodeRequirements/ValidationResult",
        "doc://com.apple.LightweightCodeRequirements/documentation/LightweightCodeRequirements/OnDiskCodeRequirement",
        "doc://com.apple.LightweightCodeRequirements/documentation/LightweightCodeRequirements/allOf(requirement:)-2ocwl",
        "doc://com.apple.LightweightCodeRequirements/documentation/LightweightCodeRequirements/anyOf(requirement:)-71pff",
        "doc://com.apple.LightweightCodeRequirements/documentation/LightweightCodeRequirements/OnDiskConstraint",
        "doc://com.apple.LightweightCodeRequirements/documentation/LightweightCodeRequirements/OnDiskCodeSigningFlags",
        "doc://com.apple.LightweightCodeRequirements/documentation/LightweightCodeRequirements/OnDiskConstraintBuilder"
      ],
      "title": "Checking code requirements for code files on disk"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:@E@SecCSFlags/fragments",
          "value": [
            {
              "kind": "keyword",
              "text": "enum"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "SecCSFlags"
            },
            {
              "kind": "text",
              "text": " : "
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@uint32_t",
              "text": "uint32_t"
            },
            {
              "kind": "text",
              "text": ";"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:@T@SecStaticCodeRef/title",
          "value": "SecStaticCodeRef"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:@T@SecStaticCodeRef/fragments",
          "value": [
            {
              "kind": "keyword",
              "text": "typedef"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "keyword",
              "text": "const"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "keyword",
              "text": "struct"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@S@__SecCode",
              "text": "__SecCode"
            },
            {
              "kind": "text",
              "text": " * "
            },
            {
              "kind": "identifier",
              "text": "SecStaticCodeRef"
            },
            {
              "kind": "text",
              "text": ";"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/lightweightcoderequirements/secstaticcodecheckvaliditywithondiskrequirement(code:flags:requirement:)"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    }
  ]
}
