{
  "abstract": [
    {
      "text": "Returns a predicate to find the contacts matching the specified name.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.contacts/documentation/Contacts",
        "doc://com.apple.contacts/documentation/Contacts/CNContact"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.contacts/documentation/Contacts/CNContact/predicateForContacts(matchingName:)"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "extendedModule": "Contacts",
    "externalID": "c:objc(cs)CNContact(cm)predicateForContactsMatchingName:",
    "fragments": [
      {
        "kind": "keyword",
        "text": "class"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "keyword",
        "text": "func"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "predicateForContacts"
      },
      {
        "kind": "text",
        "text": "("
      },
      {
        "kind": "externalParam",
        "text": "matchingName"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "s:SS",
        "text": "String"
      },
      {
        "kind": "text",
        "text": ") -> "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:objc(cs)NSPredicate",
        "text": "NSPredicate"
      }
    ],
    "modules": [
      {
        "name": "Contacts"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "predicateForContactsMatchingName:"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "9.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "9.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.0",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.11",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "2.0",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Type Method",
    "symbolKind": "method",
    "title": "predicateForContacts(matchingName:)"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "class"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "keyword",
              "text": "func"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "predicateForContacts"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "kind": "externalParam",
              "text": "matchingName"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "name"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:SS",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:SS",
              "text": "String"
            },
            {
              "kind": "text",
              "text": ") -> "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSPredicate",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)NSPredicate",
              "text": "NSPredicate"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "kind": "parameters",
      "parameters": [
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "The contact name to be matched.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "name"
        }
      ]
    },
    {
      "content": [
        {
          "anchor": "Return-Value",
          "level": 2,
          "text": "Return Value",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "A predicate that you can use to fetch contacts from ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.contacts/documentation/Contacts/CNContactStore",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ".",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "The name can contain any number of words.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.contacts/documentation/Contacts": {
      "abstract": [
        {
          "text": "Access the user’s contacts, and format and localize contact information.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.contacts/documentation/Contacts",
      "kind": "symbol",
      "role": "collection",
      "title": "Contacts",
      "type": "topic",
      "url": "/documentation/contacts"
    },
    "doc://com.apple.contacts/documentation/Contacts/CNContact": {
      "abstract": [
        {
          "text": "An immutable object that stores information about a single contact, such as the contact’s first name, phone numbers, and addresses.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CNContact"
        }
      ],
      "identifier": "doc://com.apple.contacts/documentation/Contacts/CNContact",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CNContact"
        }
      ],
      "role": "symbol",
      "title": "CNContact",
      "type": "topic",
      "url": "/documentation/contacts/cncontact"
    },
    "doc://com.apple.contacts/documentation/Contacts/CNContact/predicateForContacts(matching:)": {
      "abstract": [
        {
          "text": "Returns a predicate to find the contacts whose phone number matches the specified value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "predicateForContacts"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "matching"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)CNPhoneNumber",
          "text": "CNPhoneNumber"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSPredicate",
          "text": "NSPredicate"
        }
      ],
      "identifier": "doc://com.apple.contacts/documentation/Contacts/CNContact/predicateForContacts(matching:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "predicateForContactsMatchingPhoneNumber:"
        }
      ],
      "role": "symbol",
      "title": "predicateForContacts(matching:)",
      "type": "topic",
      "url": "/documentation/contacts/cncontact/predicateforcontacts(matching:)"
    },
    "doc://com.apple.contacts/documentation/Contacts/CNContact/predicateForContacts(matchingEmailAddress:)": {
      "abstract": [
        {
          "text": "Returns a predicate to find the contacts whose email address matches the specified value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "predicateForContacts"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "matchingEmailAddress"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSPredicate",
          "text": "NSPredicate"
        }
      ],
      "identifier": "doc://com.apple.contacts/documentation/Contacts/CNContact/predicateForContacts(matchingEmailAddress:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "predicateForContactsMatchingEmailAddress:"
        }
      ],
      "role": "symbol",
      "title": "predicateForContacts(matchingEmailAddress:)",
      "type": "topic",
      "url": "/documentation/contacts/cncontact/predicateforcontacts(matchingemailaddress:)"
    },
    "doc://com.apple.contacts/documentation/Contacts/CNContact/predicateForContacts(matchingName:)": {
      "abstract": [
        {
          "text": "Returns a predicate to find the contacts matching the specified name.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "predicateForContacts"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "matchingName"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSPredicate",
          "text": "NSPredicate"
        }
      ],
      "identifier": "doc://com.apple.contacts/documentation/Contacts/CNContact/predicateForContacts(matchingName:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "predicateForContactsMatchingName:"
        }
      ],
      "role": "symbol",
      "title": "predicateForContacts(matchingName:)",
      "type": "topic",
      "url": "/documentation/contacts/cncontact/predicateforcontacts(matchingname:)"
    },
    "doc://com.apple.contacts/documentation/Contacts/CNContact/predicateForContacts(withIdentifiers:)": {
      "abstract": [
        {
          "text": "Returns a predicate to find the contacts matching the specified identifiers.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "predicateForContacts"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "withIdentifiers"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": "]) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSPredicate",
          "text": "NSPredicate"
        }
      ],
      "identifier": "doc://com.apple.contacts/documentation/Contacts/CNContact/predicateForContacts(withIdentifiers:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "predicateForContactsWithIdentifiers:"
        }
      ],
      "role": "symbol",
      "title": "predicateForContacts(withIdentifiers:)",
      "type": "topic",
      "url": "/documentation/contacts/cncontact/predicateforcontacts(withidentifiers:)"
    },
    "doc://com.apple.contacts/documentation/Contacts/CNContact/predicateForContactsInContainer(withIdentifier:)": {
      "abstract": [
        {
          "text": "Returns a predicate to find the contacts in the specified container.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "predicateForContactsInContainer"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "withIdentifier"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSPredicate",
          "text": "NSPredicate"
        }
      ],
      "identifier": "doc://com.apple.contacts/documentation/Contacts/CNContact/predicateForContactsInContainer(withIdentifier:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "predicateForContactsInContainerWithIdentifier:"
        }
      ],
      "role": "symbol",
      "title": "predicateForContactsInContainer(withIdentifier:)",
      "type": "topic",
      "url": "/documentation/contacts/cncontact/predicateforcontactsincontainer(withidentifier:)"
    },
    "doc://com.apple.contacts/documentation/Contacts/CNContact/predicateForContactsInGroup(withIdentifier:)": {
      "abstract": [
        {
          "text": "Returns a predicate to find the contacts that are members in the specified group.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "predicateForContactsInGroup"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "withIdentifier"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSPredicate",
          "text": "NSPredicate"
        }
      ],
      "identifier": "doc://com.apple.contacts/documentation/Contacts/CNContact/predicateForContactsInGroup(withIdentifier:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "predicateForContactsInGroupWithIdentifier:"
        }
      ],
      "role": "symbol",
      "title": "predicateForContactsInGroup(withIdentifier:)",
      "type": "topic",
      "url": "/documentation/contacts/cncontact/predicateforcontactsingroup(withidentifier:)"
    },
    "doc://com.apple.contacts/documentation/Contacts/CNContactStore": {
      "abstract": [
        {
          "text": "The object that fetches and saves contacts, groups, and containers from the user’s Contacts database.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CNContactStore"
        }
      ],
      "identifier": "doc://com.apple.contacts/documentation/Contacts/CNContactStore",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CNContactStore"
        }
      ],
      "role": "symbol",
      "title": "CNContactStore",
      "type": "topic",
      "url": "/documentation/contacts/cncontactstore"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.externally.resolved.symbol/c:objc(cs)NSPredicate": {
      "abstract": [
        {
          "text": "A definition of logical conditions for constraining a search for a fetch or for in-memory filtering.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "class "
        },
        {
          "kind": "identifier",
          "text": "NSPredicate"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSPredicate",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSPredicate",
      "type": "topic",
      "url": "/documentation/foundation/nspredicate"
    },
    "doc://com.externally.resolved.symbol/c:objc(cs)NSString": {
      "abstract": [
        {
          "text": "A static, plain-text Unicode string object which you use when you need reference semantics or other Foundation-specific behavior. ",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "class "
        },
        {
          "kind": "identifier",
          "text": "NSString"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSString",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSString",
      "type": "topic",
      "url": "/documentation/foundation/nsstring"
    },
    "doc://com.externally.resolved.symbol/s:SS": {
      "abstract": [
        {
          "text": "A Unicode string value that is a collection of characters.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@frozen"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "String"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SS",
      "kind": "symbol",
      "role": "symbol",
      "title": "String",
      "type": "topic",
      "url": "/documentation/Swift/String"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Getting-Search-Predicates",
      "generated": true,
      "identifiers": [
        "doc://com.apple.contacts/documentation/Contacts/CNContact/predicateForContacts(withIdentifiers:)",
        "doc://com.apple.contacts/documentation/Contacts/CNContact/predicateForContactsInGroup(withIdentifier:)",
        "doc://com.apple.contacts/documentation/Contacts/CNContact/predicateForContactsInContainer(withIdentifier:)",
        "doc://com.apple.contacts/documentation/Contacts/CNContact/predicateForContacts(matching:)",
        "doc://com.apple.contacts/documentation/Contacts/CNContact/predicateForContacts(matchingEmailAddress:)"
      ],
      "title": "Getting Search Predicates"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "9.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "9.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.0",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.11",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "2.0",
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Type Method"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "predicateForContactsMatchingName:"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "method"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "text",
              "text": "+ "
            },
            {
              "kind": "identifier",
              "text": "predicateForContactsMatchingName:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.contacts/documentation/Contacts",
                "doc://com.apple.contacts/documentation/Contacts/CNContact"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Getting-Search-Predicates",
              "generated": true,
              "identifiers": [
                "doc://com.apple.contacts/documentation/Contacts/CNContact/predicateForContacts(withIdentifiers:)",
                "doc://com.apple.contacts/documentation/Contacts/CNContact/predicateForContactsInGroup(withIdentifier:)",
                "doc://com.apple.contacts/documentation/Contacts/CNContact/predicateForContactsInContainer(withIdentifier:)",
                "doc://com.apple.contacts/documentation/Contacts/CNContact/predicateForContacts(matching:)",
                "doc://com.apple.contacts/documentation/Contacts/CNContact/predicateForContacts(matchingEmailAddress:)"
              ],
              "title": "Getting Search Predicates"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "text",
                    "text": "+ ("
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSPredicate",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(cs)NSPredicate",
                    "text": "NSPredicate"
                  },
                  {
                    "kind": "text",
                    "text": " *) "
                  },
                  {
                    "kind": "identifier",
                    "text": "predicateForContactsMatchingName:"
                  },
                  {
                    "kind": "text",
                    "text": "("
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSString",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(cs)NSString",
                    "text": "NSString"
                  },
                  {
                    "kind": "text",
                    "text": " *) "
                  },
                  {
                    "kind": "internalParam",
                    "text": "name"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/1",
          "value": {
            "kind": "parameters",
            "parameters": [
              {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "The contact name to be matched.",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ],
                "name": "name"
              }
            ]
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.contacts~1documentation~1Contacts~1CNContact~1predicateForContacts(matchingName:)/title",
          "value": "predicateForContactsMatchingName:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.contacts~1documentation~1Contacts~1CNContact~1predicateForContacts(matchingName:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "+ "
            },
            {
              "kind": "identifier",
              "text": "predicateForContactsMatchingName:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.contacts~1documentation~1Contacts~1CNContact~1predicateForContacts(matchingEmailAddress:)/title",
          "value": "predicateForContactsMatchingEmailAddress:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.contacts~1documentation~1Contacts~1CNContact~1predicateForContacts(matchingEmailAddress:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "+ "
            },
            {
              "kind": "identifier",
              "text": "predicateForContactsMatchingEmailAddress:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.contacts~1documentation~1Contacts~1CNContact~1predicateForContactsInContainer(withIdentifier:)/title",
          "value": "predicateForContactsInContainerWithIdentifier:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.contacts~1documentation~1Contacts~1CNContact~1predicateForContactsInContainer(withIdentifier:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "+ "
            },
            {
              "kind": "identifier",
              "text": "predicateForContactsInContainerWithIdentifier:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.contacts~1documentation~1Contacts~1CNContact~1predicateForContacts(withIdentifiers:)/title",
          "value": "predicateForContactsWithIdentifiers:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.contacts~1documentation~1Contacts~1CNContact~1predicateForContacts(withIdentifiers:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "+ "
            },
            {
              "kind": "identifier",
              "text": "predicateForContactsWithIdentifiers:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:objc(cs)NSString/abstract",
          "value": [
            {
              "text": "A static, plain-text Unicode string object.",
              "type": "text"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.contacts~1documentation~1Contacts~1CNContact~1predicateForContacts(matching:)/title",
          "value": "predicateForContactsMatchingPhoneNumber:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.contacts~1documentation~1Contacts~1CNContact~1predicateForContacts(matching:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "+ "
            },
            {
              "kind": "identifier",
              "text": "predicateForContactsMatchingPhoneNumber:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.contacts~1documentation~1Contacts~1CNContactStore/title",
          "value": "CNContactStore"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.contacts~1documentation~1Contacts~1CNContactStore/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CNContactStore"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.contacts~1documentation~1Contacts~1CNContactStore/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CNContactStore"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.contacts~1documentation~1Contacts~1CNContact/title",
          "value": "CNContact"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.contacts~1documentation~1Contacts~1CNContact/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CNContact"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.contacts~1documentation~1Contacts~1CNContact/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CNContact"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.contacts~1documentation~1Contacts~1CNContact~1predicateForContactsInGroup(withIdentifier:)/title",
          "value": "predicateForContactsInGroupWithIdentifier:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.contacts~1documentation~1Contacts~1CNContact~1predicateForContactsInGroup(withIdentifier:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "+ "
            },
            {
              "kind": "identifier",
              "text": "predicateForContactsInGroupWithIdentifier:"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/contacts/cncontact/predicateforcontacts(matchingname:)"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/contacts/cncontact/predicateforcontacts(matchingname:)"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
