{
  "abstract": [
    {
      "text": "Consumes a sample buffer from a client.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.coremediaio/documentation/CoreMediaIO",
        "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOExtensionStream"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOExtensionStream/consumeSampleBuffer(from:completionHandler:)"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(cs)CMIOExtensionStream(im)consumeSampleBufferFromClient:completionHandler:",
    "fragments": [
      {
        "kind": "keyword",
        "text": "func"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "consumeSampleBuffer"
      },
      {
        "kind": "text",
        "text": "("
      },
      {
        "kind": "externalParam",
        "text": "from"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:objc(cs)CMIOExtensionClient",
        "text": "CMIOExtensionClient"
      },
      {
        "kind": "text",
        "text": ", "
      },
      {
        "kind": "externalParam",
        "text": "completionHandler"
      },
      {
        "kind": "text",
        "text": ": ("
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@T@CMSampleBufferRef",
        "text": "CMSampleBuffer"
      },
      {
        "kind": "text",
        "text": "?, "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "s:s6UInt64V",
        "text": "UInt64"
      },
      {
        "kind": "text",
        "text": ", "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:objc(cs)CMIOExtensionStream",
        "text": "CMIOExtensionStream"
      },
      {
        "kind": "text",
        "text": "."
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@E@CMIOExtensionStreamDiscontinuityFlags",
        "text": "DiscontinuityFlags"
      },
      {
        "kind": "text",
        "text": ", "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "s:Sb",
        "text": "Bool"
      },
      {
        "kind": "text",
        "text": ", (any "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "s:s5ErrorP",
        "text": "Error"
      },
      {
        "kind": "text",
        "text": ")?) -> "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "s:s4Voida",
        "text": "Void"
      },
      {
        "kind": "text",
        "text": ")"
      }
    ],
    "modules": [
      {
        "name": "Core Media I/O"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "consumeSampleBufferFromClient:completionHandler:"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "15.4",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "12.3",
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Instance Method",
    "symbolKind": "method",
    "title": "consumeSampleBuffer(from:completionHandler:)"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "Mac Catalyst",
            "macOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "func"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "consumeSampleBuffer"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "kind": "externalParam",
              "text": "from"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "client"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOExtensionClient",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)CMIOExtensionClient",
              "text": "CMIOExtensionClient"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "kind": "externalParam",
              "text": "completionHandler"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "kind": "keyword",
              "text": "@escaping"
            },
            {
              "kind": "text",
              "text": " ("
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/c:@T@CMSampleBufferRef",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@CMSampleBufferRef",
              "text": "CMSampleBuffer"
            },
            {
              "kind": "text",
              "text": "?, "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:s6UInt64V",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:s6UInt64V",
              "text": "UInt64"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "identifier": "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOExtensionStream",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)CMIOExtensionStream",
              "text": "CMIOExtensionStream"
            },
            {
              "kind": "text",
              "text": "."
            },
            {
              "identifier": "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOExtensionStream/DiscontinuityFlags",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@E@CMIOExtensionStreamDiscontinuityFlags",
              "text": "DiscontinuityFlags"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:Sb",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:Sb",
              "text": "Bool"
            },
            {
              "kind": "text",
              "text": ", (any "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:s5ErrorP",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:s5ErrorP",
              "text": "Error"
            },
            {
              "kind": "text",
              "text": ")?) -> "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:s4Voida",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:s4Voida",
              "text": "Void"
            },
            {
              "kind": "text",
              "text": ")"
            }
          ]
        },
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "Mac Catalyst",
            "macOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "func"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "consumeSampleBuffer"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "kind": "externalParam",
              "text": "from"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "client"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOExtensionClient",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)CMIOExtensionClient",
              "text": "CMIOExtensionClient"
            },
            {
              "kind": "text",
              "text": ") "
            },
            {
              "kind": "keyword",
              "text": "async"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "keyword",
              "text": "throws"
            },
            {
              "kind": "text",
              "text": " -> ("
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/c:@T@CMSampleBufferRef",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@CMSampleBufferRef",
              "text": "CMSampleBuffer"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:s6UInt64V",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:s6UInt64V",
              "text": "UInt64"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "identifier": "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOExtensionStream",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)CMIOExtensionStream",
              "text": "CMIOExtensionStream"
            },
            {
              "kind": "text",
              "text": "."
            },
            {
              "identifier": "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOExtensionStream/DiscontinuityFlags",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@E@CMIOExtensionStreamDiscontinuityFlags",
              "text": "DiscontinuityFlags"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:Sb",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:Sb",
              "text": "Bool"
            },
            {
              "kind": "text",
              "text": ")"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "kind": "parameters",
      "parameters": [
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "The client with a sample to process.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "client"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "A callback the system invokes with the following data:",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            },
            {
              "items": [
                {
                  "definition": {
                    "content": [
                      {
                        "inlineContent": [
                          {
                            "text": "A sample buffer that contains the media sample to consume, or ",
                            "type": "text"
                          },
                          {
                            "code": "nil",
                            "type": "codeVoice"
                          },
                          {
                            "text": " if an error occurs.",
                            "type": "text"
                          }
                        ],
                        "type": "paragraph"
                      }
                    ]
                  },
                  "term": {
                    "inlineContent": [
                      {
                        "code": "sampleBuffer",
                        "type": "codeVoice"
                      }
                    ]
                  }
                },
                {
                  "definition": {
                    "content": [
                      {
                        "inlineContent": [
                          {
                            "text": "The sequence number of the current sample.",
                            "type": "text"
                          }
                        ],
                        "type": "paragraph"
                      }
                    ]
                  },
                  "term": {
                    "inlineContent": [
                      {
                        "code": "sampleBufferSequenceNumber",
                        "type": "codeVoice"
                      }
                    ]
                  }
                },
                {
                  "definition": {
                    "content": [
                      {
                        "inlineContent": [
                          {
                            "text": "A flag that indicates if there’s a discontinuity in the stream.",
                            "type": "text"
                          }
                        ],
                        "type": "paragraph"
                      }
                    ]
                  },
                  "term": {
                    "inlineContent": [
                      {
                        "code": "discontinuity",
                        "type": "codeVoice"
                      }
                    ]
                  }
                },
                {
                  "definition": {
                    "content": [
                      {
                        "inlineContent": [
                          {
                            "text": "A Boolean value that indicates whether there are more buffers available.",
                            "type": "text"
                          }
                        ],
                        "type": "paragraph"
                      }
                    ]
                  },
                  "term": {
                    "inlineContent": [
                      {
                        "code": "hasMoreSampleBuffers",
                        "type": "codeVoice"
                      }
                    ]
                  }
                },
                {
                  "definition": {
                    "content": [
                      {
                        "inlineContent": [
                          {
                            "text": "An optional error. If an error occurs, it contains the details of the failure.",
                            "type": "text"
                          }
                        ],
                        "type": "paragraph"
                      }
                    ]
                  },
                  "term": {
                    "inlineContent": [
                      {
                        "code": "error",
                        "type": "codeVoice"
                      }
                    ]
                  }
                }
              ],
              "type": "termList"
            }
          ],
          "name": "completionHandler"
        }
      ]
    }
  ],
  "references": {
    "doc://com.apple.coremediaio/documentation/CoreMediaIO": {
      "abstract": [
        {
          "text": "Securely support custom camera devices in macOS.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.coremediaio/documentation/CoreMediaIO",
      "kind": "symbol",
      "role": "collection",
      "title": "Core Media I/O",
      "type": "topic",
      "url": "/documentation/coremediaio"
    },
    "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOExtensionClient": {
      "abstract": [
        {
          "text": "An object that represents a client of the extension.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CMIOExtensionClient"
        }
      ],
      "identifier": "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOExtensionClient",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CMIOExtensionClient"
        }
      ],
      "role": "symbol",
      "title": "CMIOExtensionClient",
      "type": "topic",
      "url": "/documentation/coremediaio/cmioextensionclient"
    },
    "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOExtensionStream": {
      "abstract": [
        {
          "text": "An object that represents a stream of media data.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CMIOExtensionStream"
        }
      ],
      "identifier": "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOExtensionStream",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CMIOExtensionStream"
        }
      ],
      "role": "symbol",
      "title": "CMIOExtensionStream",
      "type": "topic",
      "url": "/documentation/coremediaio/cmioextensionstream"
    },
    "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOExtensionStream/DiscontinuityFlags": {
      "abstract": [
        {
          "text": "Constants that specify the types of discontinuities that can occur in a media stream.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "DiscontinuityFlags"
        }
      ],
      "identifier": "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOExtensionStream/DiscontinuityFlags",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "DiscontinuityFlags"
        }
      ],
      "role": "symbol",
      "title": "CMIOExtensionStream.DiscontinuityFlags",
      "type": "topic",
      "url": "/documentation/coremediaio/cmioextensionstream/discontinuityflags"
    },
    "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOExtensionStream/consumeSampleBuffer(from:completionHandler:)": {
      "abstract": [
        {
          "text": "Consumes a sample buffer from a client.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "consumeSampleBuffer"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "from"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)CMIOExtensionClient",
          "text": "CMIOExtensionClient"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "completionHandler"
        },
        {
          "kind": "text",
          "text": ": ("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CMSampleBufferRef",
          "text": "CMSampleBuffer"
        },
        {
          "kind": "text",
          "text": "?, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt64V",
          "text": "UInt64"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)CMIOExtensionStream",
          "text": "CMIOExtensionStream"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@CMIOExtensionStreamDiscontinuityFlags",
          "text": "DiscontinuityFlags"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        },
        {
          "kind": "text",
          "text": ", (any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5ErrorP",
          "text": "Error"
        },
        {
          "kind": "text",
          "text": ")?) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s4Voida",
          "text": "Void"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOExtensionStream/consumeSampleBuffer(from:completionHandler:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "consumeSampleBufferFromClient:completionHandler:"
        }
      ],
      "role": "symbol",
      "title": "consumeSampleBuffer(from:completionHandler:)",
      "type": "topic",
      "url": "/documentation/coremediaio/cmioextensionstream/consumesamplebuffer(from:completionhandler:)"
    },
    "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOExtensionStream/send(_:discontinuity:hostTimeInNanoseconds:)": {
      "abstract": [
        {
          "text": "Sends a media sample to stream client.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "send"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CMSampleBufferRef",
          "text": "CMSampleBuffer"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "discontinuity"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)CMIOExtensionStream",
          "text": "CMIOExtensionStream"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@CMIOExtensionStreamDiscontinuityFlags",
          "text": "DiscontinuityFlags"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "hostTimeInNanoseconds"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt64V",
          "text": "UInt64"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOExtensionStream/send(_:discontinuity:hostTimeInNanoseconds:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "sendSampleBuffer:discontinuity:hostTimeInNanoseconds:"
        }
      ],
      "role": "symbol",
      "title": "send(_:discontinuity:hostTimeInNanoseconds:)",
      "type": "topic",
      "url": "/documentation/coremediaio/cmioextensionstream/send(_:discontinuity:hosttimeinnanoseconds:)"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.externally.resolved.symbol/c:@T@BOOL": {
      "abstract": [
        {
          "text": "Type to represent a Boolean value.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:@T@BOOL",
      "kind": "symbol",
      "role": "symbol",
      "title": "BOOL",
      "type": "topic",
      "url": "/documentation/objectivec/bool"
    },
    "doc://com.externally.resolved.symbol/c:@T@CMSampleBufferRef": {
      "abstract": [
        {
          "text": "A reference to a buffer of media data.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CMSampleBuffer"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:@T@CMSampleBufferRef",
      "kind": "symbol",
      "role": "symbol",
      "title": "CMSampleBuffer",
      "type": "topic",
      "url": "/documentation/CoreMedia/CMSampleBuffer"
    },
    "doc://com.externally.resolved.symbol/c:@T@uint64_t": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:@T@uint64_t",
      "kind": "symbol",
      "role": "symbol",
      "title": "uint64_t",
      "type": "topic",
      "url": "/documentation/kernel/uint64_t"
    },
    "doc://com.externally.resolved.symbol/s:Sb": {
      "abstract": [
        {
          "text": "A value type whose instances are either `true` or `false`.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@frozen"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:Sb",
      "kind": "symbol",
      "role": "symbol",
      "title": "Bool",
      "type": "topic",
      "url": "/documentation/Swift/Bool"
    },
    "doc://com.externally.resolved.symbol/s:s4Voida": {
      "abstract": [
        {
          "text": "The return type of functions that don’t explicitly specify a return type, that is, an empty tuple `()`.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Void"
        },
        {
          "kind": "text",
          "text": " = ()"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s4Voida",
      "kind": "symbol",
      "role": "symbol",
      "title": "Void",
      "type": "topic",
      "url": "/documentation/Swift/Void"
    },
    "doc://com.externally.resolved.symbol/s:s5ErrorP": {
      "abstract": [
        {
          "text": "A type representing an error value that can be thrown.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Error"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s8SendableP",
          "text": "Sendable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s5ErrorP",
      "kind": "symbol",
      "role": "symbol",
      "title": "Error",
      "type": "topic",
      "url": "/documentation/Swift/Error"
    },
    "doc://com.externally.resolved.symbol/s:s6UInt64V": {
      "abstract": [
        {
          "text": "A 64-bit unsigned integer value type.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@frozen"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UInt64"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s6UInt64V",
      "kind": "symbol",
      "role": "symbol",
      "title": "UInt64",
      "type": "topic",
      "url": "/documentation/Swift/UInt64"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Processing-Data",
      "generated": true,
      "identifiers": [
        "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOExtensionStream/send(_:discontinuity:hostTimeInNanoseconds:)",
        "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOExtensionStream/DiscontinuityFlags"
      ],
      "title": "Processing Data"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "15.4",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "12.3",
              "name": "macOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Instance Method"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "consumeSampleBufferFromClient:completionHandler:"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "method"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "consumeSampleBufferFromClient:completionHandler:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.coremediaio/documentation/CoreMediaIO",
                "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOExtensionStream"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Processing-Data",
              "generated": true,
              "identifiers": [
                "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOExtensionStream/send(_:discontinuity:hostTimeInNanoseconds:)",
                "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOExtensionStream/DiscontinuityFlags"
              ],
              "title": "Processing Data"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "Mac Catalyst",
                  "macOS"
                ],
                "tokens": [
                  {
                    "kind": "text",
                    "text": "- ("
                  },
                  {
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:v",
                    "text": "void"
                  },
                  {
                    "kind": "text",
                    "text": ") "
                  },
                  {
                    "kind": "identifier",
                    "text": "consumeSampleBufferFromClient:"
                  },
                  {
                    "kind": "text",
                    "text": "("
                  },
                  {
                    "identifier": "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOExtensionClient",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(cs)CMIOExtensionClient",
                    "text": "CMIOExtensionClient"
                  },
                  {
                    "kind": "text",
                    "text": " *) "
                  },
                  {
                    "kind": "internalParam",
                    "text": "client"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "completionHandler:"
                  },
                  {
                    "kind": "text",
                    "text": "("
                  },
                  {
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:v",
                    "text": "void"
                  },
                  {
                    "kind": "text",
                    "text": " (^)("
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:@T@CMSampleBufferRef",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@CMSampleBufferRef",
                    "text": "CMSampleBufferRef"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "internalParam",
                    "text": "sampleBuffer"
                  },
                  {
                    "kind": "text",
                    "text": ", "
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:@T@uint64_t",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@uint64_t",
                    "text": "uint64_t"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "internalParam",
                    "text": "sampleBufferSequenceNumber"
                  },
                  {
                    "kind": "text",
                    "text": ", "
                  },
                  {
                    "identifier": "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOExtensionStream/DiscontinuityFlags",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@E@CMIOExtensionStreamDiscontinuityFlags",
                    "text": "CMIOExtensionStreamDiscontinuityFlags"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "internalParam",
                    "text": "discontinuity"
                  },
                  {
                    "kind": "text",
                    "text": ", "
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:@T@BOOL",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@BOOL",
                    "text": "BOOL"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "internalParam",
                    "text": "hasMoreSampleBuffers"
                  },
                  {
                    "kind": "text",
                    "text": ", "
                  },
                  {
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(cs)NSError",
                    "text": "NSError"
                  },
                  {
                    "kind": "text",
                    "text": " * "
                  },
                  {
                    "kind": "internalParam",
                    "text": "error"
                  },
                  {
                    "kind": "text",
                    "text": ")) "
                  },
                  {
                    "kind": "internalParam",
                    "text": "completionHandler"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/1",
          "value": {
            "kind": "parameters",
            "parameters": [
              {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "The client with a sample to process.",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ],
                "name": "client"
              },
              {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "A callback the system invokes with the following data:",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  },
                  {
                    "items": [
                      {
                        "definition": {
                          "content": [
                            {
                              "inlineContent": [
                                {
                                  "text": "A sample buffer that contains the media sample to consume, or ",
                                  "type": "text"
                                },
                                {
                                  "code": "nil",
                                  "type": "codeVoice"
                                },
                                {
                                  "text": " if an error occurs.",
                                  "type": "text"
                                }
                              ],
                              "type": "paragraph"
                            }
                          ]
                        },
                        "term": {
                          "inlineContent": [
                            {
                              "code": "sampleBuffer",
                              "type": "codeVoice"
                            }
                          ]
                        }
                      },
                      {
                        "definition": {
                          "content": [
                            {
                              "inlineContent": [
                                {
                                  "text": "The sequence number of the current sample.",
                                  "type": "text"
                                }
                              ],
                              "type": "paragraph"
                            }
                          ]
                        },
                        "term": {
                          "inlineContent": [
                            {
                              "code": "sampleBufferSequenceNumber",
                              "type": "codeVoice"
                            }
                          ]
                        }
                      },
                      {
                        "definition": {
                          "content": [
                            {
                              "inlineContent": [
                                {
                                  "text": "A flag that indicates if there’s a discontinuity in the stream.",
                                  "type": "text"
                                }
                              ],
                              "type": "paragraph"
                            }
                          ]
                        },
                        "term": {
                          "inlineContent": [
                            {
                              "code": "discontinuity",
                              "type": "codeVoice"
                            }
                          ]
                        }
                      },
                      {
                        "definition": {
                          "content": [
                            {
                              "inlineContent": [
                                {
                                  "text": "A Boolean value that indicates whether there are more buffers available.",
                                  "type": "text"
                                }
                              ],
                              "type": "paragraph"
                            }
                          ]
                        },
                        "term": {
                          "inlineContent": [
                            {
                              "code": "hasMoreSampleBuffers",
                              "type": "codeVoice"
                            }
                          ]
                        }
                      },
                      {
                        "definition": {
                          "content": [
                            {
                              "inlineContent": [
                                {
                                  "text": "An optional error. If an error occurs, it contains the details of the failure.",
                                  "type": "text"
                                }
                              ],
                              "type": "paragraph"
                            }
                          ]
                        },
                        "term": {
                          "inlineContent": [
                            {
                              "code": "error",
                              "type": "codeVoice"
                            }
                          ]
                        }
                      }
                    ],
                    "type": "termList"
                  }
                ],
                "name": "completionHandler"
              }
            ]
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1CMIOExtensionStream~1DiscontinuityFlags/title",
          "value": "CMIOExtensionStreamDiscontinuityFlags"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1CMIOExtensionStream~1DiscontinuityFlags/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CMIOExtensionStreamDiscontinuityFlags"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1CMIOExtensionStream~1DiscontinuityFlags/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CMIOExtensionStreamDiscontinuityFlags"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:@T@CMSampleBufferRef/title",
          "value": "CMSampleBufferRef"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:@T@CMSampleBufferRef/fragments",
          "value": [
            {
              "kind": "keyword",
              "text": "typedef"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "keyword",
              "text": "struct"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@S@opaqueCMSampleBuffer",
              "text": "opaqueCMSampleBuffer"
            },
            {
              "kind": "text",
              "text": " * "
            },
            {
              "kind": "identifier",
              "text": "CMSampleBufferRef"
            },
            {
              "kind": "text",
              "text": ";"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1CMIOExtensionClient/title",
          "value": "CMIOExtensionClient"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1CMIOExtensionClient/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CMIOExtensionClient"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1CMIOExtensionClient/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CMIOExtensionClient"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1CMIOExtensionStream~1consumeSampleBuffer(from:completionHandler:)/title",
          "value": "consumeSampleBufferFromClient:completionHandler:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1CMIOExtensionStream~1consumeSampleBuffer(from:completionHandler:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "consumeSampleBufferFromClient:completionHandler:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1CMIOExtensionStream~1send(_:discontinuity:hostTimeInNanoseconds:)/title",
          "value": "sendSampleBuffer:discontinuity:hostTimeInNanoseconds:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1CMIOExtensionStream~1send(_:discontinuity:hostTimeInNanoseconds:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "sendSampleBuffer:discontinuity:hostTimeInNanoseconds:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1CMIOExtensionStream/title",
          "value": "CMIOExtensionStream"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1CMIOExtensionStream/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CMIOExtensionStream"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1CMIOExtensionStream/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CMIOExtensionStream"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/coremediaio/cmioextensionstream/consumesamplebuffer(from:completionhandler:)"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/coremediaio/cmioextensionstream/consumesamplebuffer(from:completionhandler:)"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
