{"schemaVersion":{"major":0,"minor":3,"patch":0},"kind":"symbol","abstract":[{"type":"text","text":"A universally unique identifier for the stream."}],"sections":[],"identifier":{"interfaceLanguage":"swift","url":"doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOExtensionStream/streamID"},"hierarchy":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.coremediaio/documentation/CoreMediaIO","doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOExtensionStream"]]},"metadata":{"navigatorTitle":[{"text":"streamID","kind":"identifier"}],"symbolKind":"property","platforms":[{"name":"Mac Catalyst","introducedAt":"15.4","deprecated":false,"unavailable":false,"beta":false},{"name":"macOS","introducedAt":"12.3","beta":false,"unavailable":false,"deprecated":false}],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"streamID"},{"text":": ","kind":"text"},{"text":"UUID","preciseIdentifier":"s:10Foundation4UUIDV","kind":"typeIdentifier"}],"modules":[{"name":"Core Media I/O"}],"roleHeading":"Instance Property","role":"symbol","title":"streamID","externalID":"c:objc(cs)CMIOExtensionStream(py)streamID"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["/documentation/coremediaio/cmioextensionstream/streamid"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["/documentation/coremediaio/cmioextensionstream/streamid"]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"streamID"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc://com.externally.resolved.symbol/s:10Foundation4UUIDV","text":"UUID","preciseIdentifier":"s:10Foundation4UUIDV"},{"kind":"text","text":" { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" }"}],"platforms":["Mac Catalyst","macOS"]}]}],"seeAlsoSections":[{"anchor":"Identifying-a-Stream","generated":true,"identifiers":["doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOExtensionStream/localizedName"],"title":"Identifying a Stream"}],"references":{"doc://com.externally.resolved.symbol/c:objc(cs)NSUUID":{"abstract":[{"type":"text","text":"An object representing a universally unique value that bridges to ; use  when you need reference semantics or other Foundation-specific behavior. "}],"url":"/documentation/foundation/nsuuid","title":"NSUUID","type":"topic","identifier":"doc://com.externally.resolved.symbol/c:objc(cs)NSUUID","role":"symbol","kind":"symbol","fragments":[{"kind":"text","text":"class "},{"kind":"identifier","text":"NSUUID"}]},"doc://com.apple.documentation/documentation/technologies":{"role":"overview","title":"Technologies","type":"topic","abstract":[{"type":"text","text":""}],"identifier":"doc://com.apple.documentation/documentation/technologies","url":"/documentation/technologies","kind":"technologies"},"doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOExtensionStream/localizedName":{"title":"localizedName","role":"symbol","kind":"symbol","type":"topic","abstract":[{"type":"text","text":"A localized name for the stream."}],"url":"/documentation/coremediaio/cmioextensionstream/localizedname","navigatorTitle":[{"kind":"identifier","text":"localizedName"}],"identifier":"doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOExtensionStream/localizedName","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"localizedName","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"}]},"doc://com.apple.coremediaio/documentation/CoreMediaIO":{"role":"collection","title":"Core Media I/O","type":"topic","abstract":[{"type":"text","text":"Securely support custom camera devices in macOS."}],"identifier":"doc://com.apple.coremediaio/documentation/CoreMediaIO","url":"/documentation/coremediaio","kind":"symbol"},"doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOExtensionStream":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"CMIOExtensionStream"}],"type":"topic","url":"/documentation/coremediaio/cmioextensionstream","abstract":[{"type":"text","text":"An object that represents a stream of media data."}],"kind":"symbol","title":"CMIOExtensionStream","navigatorTitle":[{"kind":"identifier","text":"CMIOExtensionStream"}],"role":"symbol","identifier":"doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOExtensionStream"},"doc://com.externally.resolved.symbol/s:10Foundation4UUIDV":{"abstract":[{"type":"text","text":"A universally unique value to identify types, interfaces, and other items."}],"url":"/documentation/foundation/uuid","title":"UUID","type":"topic","identifier":"doc://com.externally.resolved.symbol/s:10Foundation4UUIDV","role":"symbol","kind":"symbol","fragments":[{"text":"struct ","kind":"text"},{"text":"UUID","kind":"identifier"}]},"doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOExtensionStream/streamID":{"title":"streamID","role":"symbol","kind":"symbol","type":"topic","abstract":[{"type":"text","text":"A universally unique identifier for the stream."}],"url":"/documentation/coremediaio/cmioextensionstream/streamid","navigatorTitle":[{"kind":"identifier","text":"streamID"}],"identifier":"doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOExtensionStream/streamID","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"streamID"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:10Foundation4UUIDV","text":"UUID"}]}},"variantOverrides":[{"patch":[{"op":"replace","value":"occ","path":"/identifier/interfaceLanguage"},{"value":[{"deprecated":false,"unavailable":false,"beta":false,"name":"Mac Catalyst","introducedAt":"15.4"},{"deprecated":false,"unavailable":false,"beta":false,"name":"macOS","introducedAt":"12.3"}],"op":"replace","path":"/metadata/platforms"},{"value":"Instance Property","op":"replace","path":"/metadata/roleHeading"},{"value":"streamID","op":"replace","path":"/metadata/title"},{"value":"property","op":"replace","path":"/metadata/symbolKind"},{"value":[{"kind":"identifier","text":"streamID"}],"op":"replace","path":"/metadata/fragments"},{"path":"/hierarchy","value":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.coremediaio/documentation/CoreMediaIO","doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOExtensionStream"]]},"op":"replace"},{"path":"/topicSections","value":null,"op":"add"},{"path":"/relationshipsSections","value":null,"op":"add"},{"path":"/seeAlsoSections","value":[{"title":"Identifying a Stream","identifiers":["doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIOExtensionStream/localizedName"],"generated":true,"anchor":"Identifying-a-Stream"}],"op":"replace"},{"path":"/primaryContentSections/0","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"atomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"copy","kind":"keyword"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"identifier":"doc://com.externally.resolved.symbol/c:objc(cs)NSUUID","text":"NSUUID","preciseIdentifier":"c:objc(cs)NSUUID","kind":"typeIdentifier"},{"text":" * ","kind":"text"},{"text":"streamID","kind":"identifier"},{"text":";","kind":"text"}],"languages":["occ"],"platforms":["Mac Catalyst","macOS"]}]},"op":"replace"},{"op":"replace","path":"/references/doc:~1~1com.externally.resolved.symbol~1c:objc(cs)NSUUID/abstract","value":[{"type":"text","text":"A universally unique value that can be used to identify types, interfaces, and other items.  "}]},{"op":"replace","path":"/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1CMIOExtensionStream~1localizedName/title","value":"localizedName"},{"op":"replace","path":"/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1CMIOExtensionStream~1localizedName/fragments","value":[{"text":"localizedName","kind":"identifier"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1CMIOExtensionStream/title","value":"CMIOExtensionStream"},{"op":"replace","path":"/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1CMIOExtensionStream/fragments","value":[{"text":"CMIOExtensionStream","kind":"identifier"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1CMIOExtensionStream/navigatorTitle","value":[{"text":"CMIOExtensionStream","kind":"identifier"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1CMIOExtensionStream~1streamID/title","value":"streamID"},{"op":"replace","path":"/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1CMIOExtensionStream~1streamID/fragments","value":[{"text":"streamID","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}],"legalNotices":{"copyright":"Copyright &copy; 2025 Apple Inc. All rights reserved.","termsOfUse":"https://www.apple.com/legal/internet-services/terms/site.html","privacyPolicy":"https://www.apple.com/privacy/privacy-policy"}}