{
  "abstract": [
    {
      "text": "A header mode that styles the first item in a section as a header.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.uikit/documentation/UIKit",
        "doc://com.apple.uikit/documentation/UIKit/UICollectionLayoutListHeaderMode"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "occ",
    "url": "doc://com.apple.uikit/documentation/UIKit/UICollectionLayoutListHeaderMode/UICollectionLayoutListHeaderModeFirstItemInSection"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@UICollectionLayoutListHeaderMode@UICollectionLayoutListHeaderModeFirstItemInSection",
    "fragments": [
      {
        "kind": "identifier",
        "text": "UICollectionLayoutListHeaderModeFirstItemInSection"
      }
    ],
    "modules": [
      {
        "name": "UIKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "UICollectionLayoutListHeaderModeFirstItemInSection"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "14.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "14.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "14.0",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "14.0",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Enumeration Case",
    "symbolKind": "case",
    "title": "UICollectionLayoutListHeaderModeFirstItemInSection"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "occ"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "tvOS",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "identifier",
              "text": "UICollectionLayoutListHeaderModeFirstItemInSection"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Choose this header mode when you’re using hierarchical data sources if you want to be able to expand and collapse the header.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "When you use this header mode, a ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.uikit/documentation/UIKit/UICollectionViewListCell",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " object that appears as the first item in the section automatically uses a header appearance. When you configure your data source, make sure to account for the fact that the first item in the section (at index ",
              "type": "text"
            },
            {
              "code": "0",
              "type": "codeVoice"
            },
            {
              "text": ") represents the header, and the actual items in the section start at index ",
              "type": "text"
            },
            {
              "code": "1",
              "type": "codeVoice"
            },
            {
              "text": ".",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "By default, lists that use the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.uikit/documentation/UIKit/UICollectionLayoutListAppearance/UICollectionLayoutListAppearancePlain",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " and ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.uikit/documentation/UIKit/UICollectionLayoutListAppearance/UICollectionLayoutListAppearanceSidebarPlain",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " list appearances use pinned headers. If you want to opt into this default pinning behavior, use the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.uikit/documentation/UIKit/UICollectionLayoutListHeaderMode/UICollectionLayoutListHeaderModeSupplementary",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " header mode instead.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.uikit/documentation/UIKit": {
      "abstract": [
        {
          "text": "Construct and manage a graphical, event-driven user interface for your iOS, iPadOS, or tvOS app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit",
      "kind": "symbol",
      "role": "collection",
      "title": "UIKit",
      "type": "topic",
      "url": "/documentation/uikit"
    },
    "doc://com.apple.uikit/documentation/UIKit/UICollectionLayoutListAppearance/UICollectionLayoutListAppearancePlain": {
      "abstract": [
        {
          "text": "The plain list appearance.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "UICollectionLayoutListAppearancePlain"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UICollectionLayoutListAppearance/UICollectionLayoutListAppearancePlain",
      "kind": "symbol",
      "role": "symbol",
      "title": "UICollectionLayoutListAppearancePlain",
      "type": "topic",
      "url": "/documentation/uikit/uicollectionlayoutlistappearance/uicollectionlayoutlistappearanceplain"
    },
    "doc://com.apple.uikit/documentation/UIKit/UICollectionLayoutListAppearance/UICollectionLayoutListAppearanceSidebarPlain": {
      "abstract": [
        {
          "text": "The plain sidebar list appearance.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "UICollectionLayoutListAppearanceSidebarPlain"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UICollectionLayoutListAppearance/UICollectionLayoutListAppearanceSidebarPlain",
      "kind": "symbol",
      "role": "symbol",
      "title": "UICollectionLayoutListAppearanceSidebarPlain",
      "type": "topic",
      "url": "/documentation/uikit/uicollectionlayoutlistappearance/uicollectionlayoutlistappearancesidebarplain"
    },
    "doc://com.apple.uikit/documentation/UIKit/UICollectionLayoutListHeaderMode": {
      "abstract": [
        {
          "text": "Constants that describe the list’s header mode.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "UICollectionLayoutListHeaderMode"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UICollectionLayoutListHeaderMode",
      "kind": "symbol",
      "role": "symbol",
      "title": "UICollectionLayoutListHeaderMode",
      "type": "topic",
      "url": "/documentation/uikit/uicollectionlayoutlistheadermode"
    },
    "doc://com.apple.uikit/documentation/UIKit/UICollectionLayoutListHeaderMode/UICollectionLayoutListHeaderModeFirstItemInSection": {
      "abstract": [
        {
          "text": "A header mode that styles the first item in a section as a header.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "UICollectionLayoutListHeaderModeFirstItemInSection"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UICollectionLayoutListHeaderMode/UICollectionLayoutListHeaderModeFirstItemInSection",
      "kind": "symbol",
      "role": "symbol",
      "title": "UICollectionLayoutListHeaderModeFirstItemInSection",
      "type": "topic",
      "url": "/documentation/uikit/uicollectionlayoutlistheadermode/uicollectionlayoutlistheadermodefirstiteminsection"
    },
    "doc://com.apple.uikit/documentation/UIKit/UICollectionLayoutListHeaderMode/UICollectionLayoutListHeaderModeNone": {
      "abstract": [
        {
          "text": "No headers are shown.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "UICollectionLayoutListHeaderModeNone"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UICollectionLayoutListHeaderMode/UICollectionLayoutListHeaderModeNone",
      "kind": "symbol",
      "role": "symbol",
      "title": "UICollectionLayoutListHeaderModeNone",
      "type": "topic",
      "url": "/documentation/uikit/uicollectionlayoutlistheadermode/uicollectionlayoutlistheadermodenone"
    },
    "doc://com.apple.uikit/documentation/UIKit/UICollectionLayoutListHeaderMode/UICollectionLayoutListHeaderModeSupplementary": {
      "abstract": [
        {
          "text": "A header mode that uses supplementary views to show headers.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "UICollectionLayoutListHeaderModeSupplementary"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UICollectionLayoutListHeaderMode/UICollectionLayoutListHeaderModeSupplementary",
      "kind": "symbol",
      "role": "symbol",
      "title": "UICollectionLayoutListHeaderModeSupplementary",
      "type": "topic",
      "url": "/documentation/uikit/uicollectionlayoutlistheadermode/uicollectionlayoutlistheadermodesupplementary"
    },
    "doc://com.apple.uikit/documentation/UIKit/UICollectionViewListCell": {
      "abstract": [
        {
          "text": "A collection view cell that provides list features and default styling.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UICollectionViewListCell"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UICollectionViewListCell",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UICollectionViewListCell"
        }
      ],
      "role": "symbol",
      "title": "UICollectionViewListCell",
      "type": "topic",
      "url": "/documentation/uikit/uicollectionviewlistcell"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Header-modes",
      "generated": true,
      "identifiers": [
        "doc://com.apple.uikit/documentation/UIKit/UICollectionLayoutListHeaderMode/UICollectionLayoutListHeaderModeNone",
        "doc://com.apple.uikit/documentation/UIKit/UICollectionLayoutListHeaderMode/UICollectionLayoutListHeaderModeSupplementary"
      ],
      "title": "Header modes"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UICollectionViewListCell/title",
          "value": "UICollectionViewListCell"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UICollectionViewListCell/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UICollectionViewListCell"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UICollectionViewListCell/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UICollectionViewListCell"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/uikit/uicollectionlayoutlistheadermode/uicollectionlayoutlistheadermodefirstiteminsection"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
