{
  "abstract": [
    {
      "text": "The content is positioned in the bottom-left corner of the bounds rectangle.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.quartzcore/documentation/QuartzCore",
        "doc://com.apple.quartzcore/documentation/QuartzCore/CALayerContentsGravity"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.quartzcore/documentation/QuartzCore/CALayerContentsGravity/bottomLeft"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "extendedModule": "QuartzCore",
    "externalID": "c:@kCAGravityBottomLeft",
    "fragments": [
      {
        "kind": "keyword",
        "text": "static"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "keyword",
        "text": "let"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "bottomLeft"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@T@CALayerContentsGravity",
        "text": "CALayerContentsGravity"
      }
    ],
    "modules": [
      {
        "name": "Core Animation"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "kCAGravityBottomLeft"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "2.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "2.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.1",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.5",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "9.0",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Type Property",
    "symbolKind": "property",
    "title": "bottomLeft"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "static"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "keyword",
              "text": "let"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "bottomLeft"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.quartzcore/documentation/QuartzCore/CALayerContentsGravity",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@CALayerContentsGravity",
              "text": "CALayerContentsGravity"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.quartzcore/documentation/QuartzCore": {
      "abstract": [
        {
          "text": "Render, compose, and animate visual elements.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.quartzcore/documentation/QuartzCore",
      "kind": "symbol",
      "role": "collection",
      "title": "Core Animation",
      "type": "topic",
      "url": "/documentation/quartzcore"
    },
    "doc://com.apple.quartzcore/documentation/QuartzCore/CALayerContentsGravity": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CALayerContentsGravity"
        }
      ],
      "identifier": "doc://com.apple.quartzcore/documentation/QuartzCore/CALayerContentsGravity",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CALayerContentsGravity"
        }
      ],
      "role": "symbol",
      "title": "CALayerContentsGravity",
      "type": "topic",
      "url": "/documentation/quartzcore/calayercontentsgravity"
    },
    "doc://com.apple.quartzcore/documentation/QuartzCore/CALayerContentsGravity/bottom": {
      "abstract": [
        {
          "text": "The content is horizontally centered at the bottom-edge of the bounds rectangle.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "bottom"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CALayerContentsGravity",
          "text": "CALayerContentsGravity"
        }
      ],
      "identifier": "doc://com.apple.quartzcore/documentation/QuartzCore/CALayerContentsGravity/bottom",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCAGravityBottom"
        }
      ],
      "role": "symbol",
      "title": "bottom",
      "type": "topic",
      "url": "/documentation/quartzcore/calayercontentsgravity/bottom"
    },
    "doc://com.apple.quartzcore/documentation/QuartzCore/CALayerContentsGravity/bottomLeft": {
      "abstract": [
        {
          "text": "The content is positioned in the bottom-left corner of the bounds rectangle.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "bottomLeft"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CALayerContentsGravity",
          "text": "CALayerContentsGravity"
        }
      ],
      "identifier": "doc://com.apple.quartzcore/documentation/QuartzCore/CALayerContentsGravity/bottomLeft",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCAGravityBottomLeft"
        }
      ],
      "role": "symbol",
      "title": "bottomLeft",
      "type": "topic",
      "url": "/documentation/quartzcore/calayercontentsgravity/bottomleft"
    },
    "doc://com.apple.quartzcore/documentation/QuartzCore/CALayerContentsGravity/bottomRight": {
      "abstract": [
        {
          "text": "The content is positioned in the bottom-right corner of the bounds rectangle.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "bottomRight"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CALayerContentsGravity",
          "text": "CALayerContentsGravity"
        }
      ],
      "identifier": "doc://com.apple.quartzcore/documentation/QuartzCore/CALayerContentsGravity/bottomRight",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCAGravityBottomRight"
        }
      ],
      "role": "symbol",
      "title": "bottomRight",
      "type": "topic",
      "url": "/documentation/quartzcore/calayercontentsgravity/bottomright"
    },
    "doc://com.apple.quartzcore/documentation/QuartzCore/CALayerContentsGravity/center": {
      "abstract": [
        {
          "text": "The content is horizontally and vertically centered in the bounds rectangle.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "center"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CALayerContentsGravity",
          "text": "CALayerContentsGravity"
        }
      ],
      "identifier": "doc://com.apple.quartzcore/documentation/QuartzCore/CALayerContentsGravity/center",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCAGravityCenter"
        }
      ],
      "role": "symbol",
      "title": "center",
      "type": "topic",
      "url": "/documentation/quartzcore/calayercontentsgravity/center"
    },
    "doc://com.apple.quartzcore/documentation/QuartzCore/CALayerContentsGravity/left": {
      "abstract": [
        {
          "text": "The content is vertically centered at the left-edge of the bounds rectangle.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "left"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CALayerContentsGravity",
          "text": "CALayerContentsGravity"
        }
      ],
      "identifier": "doc://com.apple.quartzcore/documentation/QuartzCore/CALayerContentsGravity/left",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCAGravityLeft"
        }
      ],
      "role": "symbol",
      "title": "left",
      "type": "topic",
      "url": "/documentation/quartzcore/calayercontentsgravity/left"
    },
    "doc://com.apple.quartzcore/documentation/QuartzCore/CALayerContentsGravity/resize": {
      "abstract": [
        {
          "text": "The content is resized to fit the entire bounds rectangle.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "resize"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CALayerContentsGravity",
          "text": "CALayerContentsGravity"
        }
      ],
      "identifier": "doc://com.apple.quartzcore/documentation/QuartzCore/CALayerContentsGravity/resize",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCAGravityResize"
        }
      ],
      "role": "symbol",
      "title": "resize",
      "type": "topic",
      "url": "/documentation/quartzcore/calayercontentsgravity/resize"
    },
    "doc://com.apple.quartzcore/documentation/QuartzCore/CALayerContentsGravity/resizeAspect": {
      "abstract": [
        {
          "text": "The content is resized to fit the bounds rectangle, preserving the aspect of the content. If the content does not completely fill the bounds rectangle, the content is centered in the partial axis.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "resizeAspect"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CALayerContentsGravity",
          "text": "CALayerContentsGravity"
        }
      ],
      "identifier": "doc://com.apple.quartzcore/documentation/QuartzCore/CALayerContentsGravity/resizeAspect",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCAGravityResizeAspect"
        }
      ],
      "role": "symbol",
      "title": "resizeAspect",
      "type": "topic",
      "url": "/documentation/quartzcore/calayercontentsgravity/resizeaspect"
    },
    "doc://com.apple.quartzcore/documentation/QuartzCore/CALayerContentsGravity/resizeAspectFill": {
      "abstract": [
        {
          "text": "The content is resized to completely fill the bounds rectangle, while still preserving the aspect of the content. The content is centered in the axis it exceeds.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "resizeAspectFill"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CALayerContentsGravity",
          "text": "CALayerContentsGravity"
        }
      ],
      "identifier": "doc://com.apple.quartzcore/documentation/QuartzCore/CALayerContentsGravity/resizeAspectFill",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCAGravityResizeAspectFill"
        }
      ],
      "role": "symbol",
      "title": "resizeAspectFill",
      "type": "topic",
      "url": "/documentation/quartzcore/calayercontentsgravity/resizeaspectfill"
    },
    "doc://com.apple.quartzcore/documentation/QuartzCore/CALayerContentsGravity/right": {
      "abstract": [
        {
          "text": "The content is vertically centered at the right-edge of the bounds rectangle.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "right"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CALayerContentsGravity",
          "text": "CALayerContentsGravity"
        }
      ],
      "identifier": "doc://com.apple.quartzcore/documentation/QuartzCore/CALayerContentsGravity/right",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCAGravityRight"
        }
      ],
      "role": "symbol",
      "title": "right",
      "type": "topic",
      "url": "/documentation/quartzcore/calayercontentsgravity/right"
    },
    "doc://com.apple.quartzcore/documentation/QuartzCore/CALayerContentsGravity/top": {
      "abstract": [
        {
          "text": "The content is horizontally centered at the top-edge of the bounds rectangle.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "top"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CALayerContentsGravity",
          "text": "CALayerContentsGravity"
        }
      ],
      "identifier": "doc://com.apple.quartzcore/documentation/QuartzCore/CALayerContentsGravity/top",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCAGravityTop"
        }
      ],
      "role": "symbol",
      "title": "top",
      "type": "topic",
      "url": "/documentation/quartzcore/calayercontentsgravity/top"
    },
    "doc://com.apple.quartzcore/documentation/QuartzCore/CALayerContentsGravity/topLeft": {
      "abstract": [
        {
          "text": "The content is positioned in the top-left corner of the bounds rectangle.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "topLeft"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CALayerContentsGravity",
          "text": "CALayerContentsGravity"
        }
      ],
      "identifier": "doc://com.apple.quartzcore/documentation/QuartzCore/CALayerContentsGravity/topLeft",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCAGravityTopLeft"
        }
      ],
      "role": "symbol",
      "title": "topLeft",
      "type": "topic",
      "url": "/documentation/quartzcore/calayercontentsgravity/topleft"
    },
    "doc://com.apple.quartzcore/documentation/QuartzCore/CALayerContentsGravity/topRight": {
      "abstract": [
        {
          "text": "The content is positioned in the top-right corner of the bounds rectangle.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "topRight"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CALayerContentsGravity",
          "text": "CALayerContentsGravity"
        }
      ],
      "identifier": "doc://com.apple.quartzcore/documentation/QuartzCore/CALayerContentsGravity/topRight",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCAGravityTopRight"
        }
      ],
      "role": "symbol",
      "title": "topRight",
      "type": "topic",
      "url": "/documentation/quartzcore/calayercontentsgravity/topright"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Constants",
      "generated": true,
      "identifiers": [
        "doc://com.apple.quartzcore/documentation/QuartzCore/CALayerContentsGravity/center",
        "doc://com.apple.quartzcore/documentation/QuartzCore/CALayerContentsGravity/top",
        "doc://com.apple.quartzcore/documentation/QuartzCore/CALayerContentsGravity/bottom",
        "doc://com.apple.quartzcore/documentation/QuartzCore/CALayerContentsGravity/left",
        "doc://com.apple.quartzcore/documentation/QuartzCore/CALayerContentsGravity/right",
        "doc://com.apple.quartzcore/documentation/QuartzCore/CALayerContentsGravity/topLeft",
        "doc://com.apple.quartzcore/documentation/QuartzCore/CALayerContentsGravity/topRight",
        "doc://com.apple.quartzcore/documentation/QuartzCore/CALayerContentsGravity/bottomRight",
        "doc://com.apple.quartzcore/documentation/QuartzCore/CALayerContentsGravity/resize",
        "doc://com.apple.quartzcore/documentation/QuartzCore/CALayerContentsGravity/resizeAspect",
        "doc://com.apple.quartzcore/documentation/QuartzCore/CALayerContentsGravity/resizeAspectFill"
      ],
      "title": "Constants"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "2.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "2.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.1",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.5",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "9.0",
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Global Variable"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "kCAGravityBottomLeft"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "var"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCAGravityBottomLeft"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.quartzcore/documentation/QuartzCore"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Constants",
              "generated": true,
              "identifiers": [
                "doc://com.apple.quartzcore/documentation/QuartzCore/CALayerContentsGravity/center",
                "doc://com.apple.quartzcore/documentation/QuartzCore/CALayerContentsGravity/top",
                "doc://com.apple.quartzcore/documentation/QuartzCore/CALayerContentsGravity/bottom",
                "doc://com.apple.quartzcore/documentation/QuartzCore/CALayerContentsGravity/left",
                "doc://com.apple.quartzcore/documentation/QuartzCore/CALayerContentsGravity/right",
                "doc://com.apple.quartzcore/documentation/QuartzCore/CALayerContentsGravity/topLeft",
                "doc://com.apple.quartzcore/documentation/QuartzCore/CALayerContentsGravity/topRight",
                "doc://com.apple.quartzcore/documentation/QuartzCore/CALayerContentsGravity/bottomRight",
                "doc://com.apple.quartzcore/documentation/QuartzCore/CALayerContentsGravity/resize",
                "doc://com.apple.quartzcore/documentation/QuartzCore/CALayerContentsGravity/resizeAspect",
                "doc://com.apple.quartzcore/documentation/QuartzCore/CALayerContentsGravity/resizeAspectFill"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "extern"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "identifier": "doc://com.apple.quartzcore/documentation/QuartzCore/CALayerContentsGravity",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@CALayerContentsGravity",
                    "text": "CALayerContentsGravity"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "keyword",
                    "text": "const"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "kCAGravityBottomLeft"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartzcore~1documentation~1QuartzCore~1CALayerContentsGravity~1bottom/title",
          "value": "kCAGravityBottom"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartzcore~1documentation~1QuartzCore~1CALayerContentsGravity~1bottom/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCAGravityBottom"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartzcore~1documentation~1QuartzCore~1CALayerContentsGravity~1top/title",
          "value": "kCAGravityTop"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartzcore~1documentation~1QuartzCore~1CALayerContentsGravity~1top/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCAGravityTop"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartzcore~1documentation~1QuartzCore~1CALayerContentsGravity~1topLeft/title",
          "value": "kCAGravityTopLeft"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartzcore~1documentation~1QuartzCore~1CALayerContentsGravity~1topLeft/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCAGravityTopLeft"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartzcore~1documentation~1QuartzCore~1CALayerContentsGravity~1resizeAspectFill/title",
          "value": "kCAGravityResizeAspectFill"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartzcore~1documentation~1QuartzCore~1CALayerContentsGravity~1resizeAspectFill/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCAGravityResizeAspectFill"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartzcore~1documentation~1QuartzCore~1CALayerContentsGravity~1right/title",
          "value": "kCAGravityRight"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartzcore~1documentation~1QuartzCore~1CALayerContentsGravity~1right/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCAGravityRight"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartzcore~1documentation~1QuartzCore~1CALayerContentsGravity~1bottomLeft/title",
          "value": "kCAGravityBottomLeft"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartzcore~1documentation~1QuartzCore~1CALayerContentsGravity~1bottomLeft/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCAGravityBottomLeft"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartzcore~1documentation~1QuartzCore~1CALayerContentsGravity~1resize/title",
          "value": "kCAGravityResize"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartzcore~1documentation~1QuartzCore~1CALayerContentsGravity~1resize/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCAGravityResize"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartzcore~1documentation~1QuartzCore~1CALayerContentsGravity~1topRight/title",
          "value": "kCAGravityTopRight"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartzcore~1documentation~1QuartzCore~1CALayerContentsGravity~1topRight/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCAGravityTopRight"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartzcore~1documentation~1QuartzCore~1CALayerContentsGravity~1bottomRight/title",
          "value": "kCAGravityBottomRight"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartzcore~1documentation~1QuartzCore~1CALayerContentsGravity~1bottomRight/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCAGravityBottomRight"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartzcore~1documentation~1QuartzCore~1CALayerContentsGravity~1left/title",
          "value": "kCAGravityLeft"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartzcore~1documentation~1QuartzCore~1CALayerContentsGravity~1left/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCAGravityLeft"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartzcore~1documentation~1QuartzCore~1CALayerContentsGravity~1center/title",
          "value": "kCAGravityCenter"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartzcore~1documentation~1QuartzCore~1CALayerContentsGravity~1center/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCAGravityCenter"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartzcore~1documentation~1QuartzCore~1CALayerContentsGravity/title",
          "value": "CALayerContentsGravity"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartzcore~1documentation~1QuartzCore~1CALayerContentsGravity/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CALayerContentsGravity"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartzcore~1documentation~1QuartzCore~1CALayerContentsGravity/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CALayerContentsGravity"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartzcore~1documentation~1QuartzCore~1CALayerContentsGravity~1resizeAspect/title",
          "value": "kCAGravityResizeAspect"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartzcore~1documentation~1QuartzCore~1CALayerContentsGravity~1resizeAspect/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCAGravityResizeAspect"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/quartzcore/calayercontentsgravity/bottomleft"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/quartzcore/calayercontentsgravity/bottomleft"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
