{
  "abstract": [
    {
      "text": "Specifies that the overlay is at a raised position at the bottom of the screen.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.storekit/documentation/StoreKit",
        "doc://com.apple.storekit/documentation/StoreKit/SKOverlay",
        "doc://com.apple.storekit/documentation/StoreKit/SKOverlay/Position"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.storekit/documentation/StoreKit/SKOverlay/Position/bottomRaised"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@SKOverlayPosition@SKOverlayPositionBottomRaised",
    "fragments": [
      {
        "kind": "keyword",
        "text": "case"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "bottomRaised"
      }
    ],
    "modules": [
      {
        "name": "StoreKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "SKOverlayPositionBottomRaised"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "14.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "14.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "14.0",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Case",
    "symbolKind": "case",
    "title": "SKOverlay.Position.bottomRaised"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "case"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "bottomRaised"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Use this position in case your app uses a ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/UIKit/UITabBar",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ".",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/UIKit/UITabBar": {
      "abstract": [
        {
          "text": "A control that displays one or more buttons in a tab bar for selecting between different subtasks, views, or modes in an app.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@"
        },
        {
          "kind": "attribute",
          "preciseIdentifier": "s:ScM",
          "text": "MainActor"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UITabBar"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/UIKit/UITabBar",
      "kind": "symbol",
      "role": "symbol",
      "title": "UITabBar",
      "type": "topic",
      "url": "/documentation/UIKit/UITabBar"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.storekit/documentation/StoreKit": {
      "abstract": [
        {
          "text": "Support In-App Purchases and interactions with the App Store.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.storekit/documentation/StoreKit",
      "kind": "symbol",
      "role": "collection",
      "title": "StoreKit",
      "type": "topic",
      "url": "/documentation/storekit"
    },
    "doc://com.apple.storekit/documentation/StoreKit/SKOverlay": {
      "abstract": [
        {
          "text": "A class that displays an overlay you can use to recommend another app or an App Clip’s corresponding full app.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SKOverlay"
        }
      ],
      "identifier": "doc://com.apple.storekit/documentation/StoreKit/SKOverlay",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SKOverlay"
        }
      ],
      "role": "symbol",
      "title": "SKOverlay",
      "type": "topic",
      "url": "/documentation/storekit/skoverlay"
    },
    "doc://com.apple.storekit/documentation/StoreKit/SKOverlay/Position": {
      "abstract": [
        {
          "text": "Constants that identify the position of an overlay on the screen.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Position"
        }
      ],
      "identifier": "doc://com.apple.storekit/documentation/StoreKit/SKOverlay/Position",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "Position"
        }
      ],
      "role": "symbol",
      "title": "SKOverlay.Position",
      "type": "topic",
      "url": "/documentation/storekit/skoverlay/position"
    },
    "doc://com.apple.storekit/documentation/StoreKit/SKOverlay/Position/bottom": {
      "abstract": [
        {
          "text": "Specifies that the overlay is at the bottom of the screen.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "bottom"
        }
      ],
      "identifier": "doc://com.apple.storekit/documentation/StoreKit/SKOverlay/Position/bottom",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SKOverlayPositionBottom"
        }
      ],
      "role": "symbol",
      "title": "SKOverlay.Position.bottom",
      "type": "topic",
      "url": "/documentation/storekit/skoverlay/position/bottom"
    },
    "doc://com.apple.storekit/documentation/StoreKit/SKOverlay/Position/bottomRaised": {
      "abstract": [
        {
          "text": "Specifies that the overlay is at a raised position at the bottom of the screen.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "bottomRaised"
        }
      ],
      "identifier": "doc://com.apple.storekit/documentation/StoreKit/SKOverlay/Position/bottomRaised",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SKOverlayPositionBottomRaised"
        }
      ],
      "role": "symbol",
      "title": "SKOverlay.Position.bottomRaised",
      "type": "topic",
      "url": "/documentation/storekit/skoverlay/position/bottomraised"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Describing-the-Overlays-Position",
      "generated": true,
      "identifiers": [
        "doc://com.apple.storekit/documentation/StoreKit/SKOverlay/Position/bottom"
      ],
      "title": "Describing the Overlay’s Position"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "14.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "14.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "14.0",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration Case"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "SKOverlayPositionBottomRaised"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "case"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SKOverlayPositionBottomRaised"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.storekit/documentation/StoreKit",
                "doc://com.apple.storekit/documentation/StoreKit/SKOverlay/Position"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Describing-the-Overlays-Position",
              "generated": true,
              "identifiers": [
                "doc://com.apple.storekit/documentation/StoreKit/SKOverlay/Position/bottom"
              ],
              "title": "Describing the Overlay’s Position"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS"
                ],
                "tokens": [
                  {
                    "kind": "identifier",
                    "text": "SKOverlayPositionBottomRaised"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.storekit~1documentation~1StoreKit~1SKOverlay~1Position/title",
          "value": "SKOverlayPosition"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.storekit~1documentation~1StoreKit~1SKOverlay~1Position/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SKOverlayPosition"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.storekit~1documentation~1StoreKit~1SKOverlay~1Position/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SKOverlayPosition"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.storekit~1documentation~1StoreKit~1SKOverlay~1Position~1bottom/title",
          "value": "SKOverlayPositionBottom"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.storekit~1documentation~1StoreKit~1SKOverlay~1Position~1bottom/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SKOverlayPositionBottom"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.storekit~1documentation~1StoreKit~1SKOverlay~1Position~1bottomRaised/title",
          "value": "SKOverlayPositionBottomRaised"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.storekit~1documentation~1StoreKit~1SKOverlay~1Position~1bottomRaised/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SKOverlayPositionBottomRaised"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.storekit~1documentation~1StoreKit~1SKOverlay/title",
          "value": "SKOverlay"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.storekit~1documentation~1StoreKit~1SKOverlay/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SKOverlay"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.storekit~1documentation~1StoreKit~1SKOverlay/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SKOverlay"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1UIKit~1UITabBar/fragments",
          "value": [
            {
              "kind": "keyword",
              "text": "@interface"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "UITabBar"
            },
            {
              "kind": "text",
              "text": " : "
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)UIView",
              "text": "UIView"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/storekit/skoverlay/position/bottomraised"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/storekit/skoverlay/position/bottomraised"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
