{"abstract":[{"type":"text","text":"Defines the pooling window size for the width dimension."}],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"kernelWidth","kind":"identifier"},{"text":": ","kind":"text"},{"identifier":"doc://com.externally.resolved.symbol/s:Si","kind":"typeIdentifier","preciseIdentifier":"s:Si","text":"Int"},{"kind":"text","text":" { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" "},{"kind":"keyword","text":"set"},{"kind":"text","text":" }"}],"platforms":["iOS","iPadOS","Mac Catalyst","macOS","tvOS","visionOS"]}]}],"kind":"symbol","hierarchy":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.metalperformanceshadersgraph/documentation/MetalPerformanceShadersGraph","doc://com.apple.metalperformanceshadersgraph/documentation/MetalPerformanceShadersGraph/MPSGraphPooling2DOpDescriptor"]]},"metadata":{"navigatorTitle":[{"kind":"identifier","text":"kernelWidth"}],"title":"kernelWidth","symbolKind":"property","roleHeading":"Instance Property","role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"kernelWidth"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Si","text":"Int"}],"externalID":"c:objc(cs)MPSGraphPooling2DOpDescriptor(py)kernelWidth","modules":[{"name":"Metal Performance Shaders Graph"}],"platforms":[{"unavailable":false,"deprecated":false,"beta":false,"name":"iOS","introducedAt":"14.0"},{"unavailable":false,"deprecated":false,"beta":false,"name":"iPadOS","introducedAt":"14.0"},{"unavailable":false,"deprecated":false,"beta":false,"name":"Mac Catalyst","introducedAt":"14.0"},{"unavailable":false,"deprecated":false,"beta":false,"name":"macOS","introducedAt":"11.0"},{"unavailable":false,"deprecated":false,"beta":false,"name":"tvOS","introducedAt":"14.0"},{"unavailable":false,"deprecated":false,"beta":false,"name":"visionOS","introducedAt":"1.0"}]},"variants":[{"paths":["/documentation/metalperformanceshadersgraph/mpsgraphpooling2dopdescriptor/kernelwidth"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["/documentation/metalperformanceshadersgraph/mpsgraphpooling2dopdescriptor/kernelwidth"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"identifier":{"url":"doc://com.apple.metalperformanceshadersgraph/documentation/MetalPerformanceShadersGraph/MPSGraphPooling2DOpDescriptor/kernelWidth","interfaceLanguage":"swift"},"sections":[],"references":{"doc://com.apple.documentation/documentation/technologies":{"kind":"technologies","title":"Technologies","abstract":[{"type":"text","text":""}],"url":"/documentation/technologies","type":"topic","identifier":"doc://com.apple.documentation/documentation/technologies","role":"overview"},"doc://com.externally.resolved.symbol/s:Si":{"identifier":"doc://com.externally.resolved.symbol/s:Si","url":"/documentation/Swift/Int","abstract":[{"text":"A signed integer value type.","type":"text"}],"type":"topic","title":"Int","fragments":[{"text":"@frozen","kind":"attribute"},{"text":" ","kind":"text"},{"text":"struct","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"Int"}],"role":"symbol","kind":"symbol"},"doc://com.apple.metalperformanceshadersgraph/documentation/MetalPerformanceShadersGraph/MPSGraphPooling2DOpDescriptor/kernelWidth":{"abstract":[{"text":"Defines the pooling window size for the width dimension.","type":"text"}],"title":"kernelWidth","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"kernelWidth"}],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"kernelWidth"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"}],"type":"topic","identifier":"doc://com.apple.metalperformanceshadersgraph/documentation/MetalPerformanceShadersGraph/MPSGraphPooling2DOpDescriptor/kernelWidth","url":"/documentation/metalperformanceshadersgraph/mpsgraphpooling2dopdescriptor/kernelwidth","kind":"symbol"},"doc://com.apple.metalperformanceshadersgraph/documentation/MetalPerformanceShadersGraph":{"role":"collection","kind":"symbol","url":"/documentation/metalperformanceshadersgraph","abstract":[{"type":"text","text":"Build, compile, and execute compute graphs utilizing all the different compute devices on the platform, including GPU, CPU, and Neural Engine."}],"identifier":"doc://com.apple.metalperformanceshadersgraph/documentation/MetalPerformanceShadersGraph","title":"Metal Performance Shaders Graph","type":"topic"},"doc://com.apple.metalperformanceshadersgraph/documentation/MetalPerformanceShadersGraph/MPSGraphPooling2DOpDescriptor":{"role":"symbol","kind":"symbol","url":"/documentation/metalperformanceshadersgraph/mpsgraphpooling2dopdescriptor","abstract":[{"text":"The class that defines the parameters for a 2D pooling operation.","type":"text"}],"identifier":"doc://com.apple.metalperformanceshadersgraph/documentation/MetalPerformanceShadersGraph/MPSGraphPooling2DOpDescriptor","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"MPSGraphPooling2DOpDescriptor"}],"title":"MPSGraphPooling2DOpDescriptor","navigatorTitle":[{"kind":"identifier","text":"MPSGraphPooling2DOpDescriptor"}],"type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"/identifier/interfaceLanguage","value":"occ"},{"op":"replace","path":"/metadata/platforms","value":[{"introducedAt":"14.0","deprecated":false,"unavailable":false,"beta":false,"name":"iOS"},{"unavailable":false,"deprecated":false,"beta":false,"name":"iPadOS","introducedAt":"14.0"},{"unavailable":false,"deprecated":false,"beta":false,"name":"Mac Catalyst","introducedAt":"14.0"},{"unavailable":false,"deprecated":false,"beta":false,"name":"macOS","introducedAt":"11.0"},{"unavailable":false,"deprecated":false,"beta":false,"name":"tvOS","introducedAt":"14.0"},{"name":"visionOS","beta":false,"deprecated":false,"introducedAt":"1.0","unavailable":false}]},{"op":"replace","path":"/metadata/roleHeading","value":"Instance Property"},{"op":"replace","path":"/metadata/title","value":"kernelWidth"},{"op":"replace","path":"/metadata/symbolKind","value":"property"},{"op":"replace","path":"/metadata/fragments","value":[{"text":"kernelWidth","kind":"identifier"}]},{"op":"replace","path":"/hierarchy","value":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.metalperformanceshadersgraph/documentation/MetalPerformanceShadersGraph","doc://com.apple.metalperformanceshadersgraph/documentation/MetalPerformanceShadersGraph/MPSGraphPooling2DOpDescriptor"]]}},{"op":"add","path":"/topicSections","value":null},{"op":"add","path":"/relationshipsSections","value":null},{"value":null,"path":"/seeAlsoSections","op":"add"},{"value":{"declarations":[{"platforms":["iOS","iPadOS","Mac Catalyst","macOS","tvOS","visionOS"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"readwrite","kind":"keyword"},{"text":") ","kind":"text"},{"preciseIdentifier":"c:@T@NSUInteger","text":"NSUInteger","kind":"typeIdentifier"},{"kind":"text","text":" "},{"kind":"identifier","text":"kernelWidth"},{"kind":"text","text":";"}],"languages":["occ"]}],"kind":"declarations"},"path":"/primaryContentSections/0","op":"replace"},{"value":"kernelWidth","path":"/references/doc:~1~1com.apple.metalperformanceshadersgraph~1documentation~1MetalPerformanceShadersGraph~1MPSGraphPooling2DOpDescriptor~1kernelWidth/title","op":"replace"},{"value":[{"kind":"identifier","text":"kernelWidth"}],"path":"/references/doc:~1~1com.apple.metalperformanceshadersgraph~1documentation~1MetalPerformanceShadersGraph~1MPSGraphPooling2DOpDescriptor~1kernelWidth/fragments","op":"replace"},{"op":"replace","value":"MPSGraphPooling2DOpDescriptor","path":"/references/doc:~1~1com.apple.metalperformanceshadersgraph~1documentation~1MetalPerformanceShadersGraph~1MPSGraphPooling2DOpDescriptor/title"},{"op":"replace","value":[{"kind":"identifier","text":"MPSGraphPooling2DOpDescriptor"}],"path":"/references/doc:~1~1com.apple.metalperformanceshadersgraph~1documentation~1MetalPerformanceShadersGraph~1MPSGraphPooling2DOpDescriptor/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"MPSGraphPooling2DOpDescriptor"}],"path":"/references/doc:~1~1com.apple.metalperformanceshadersgraph~1documentation~1MetalPerformanceShadersGraph~1MPSGraphPooling2DOpDescriptor/navigatorTitle"}]}],"legalNotices":{"copyright":"Copyright &copy; 2025 Apple Inc. All rights reserved.","termsOfUse":"https://www.apple.com/legal/internet-services/terms/site.html","privacyPolicy":"https://www.apple.com/privacy/privacy-policy"}}