{
  "abstract": [
    {
      "text": "Initializes a balance amount object with a customizable type of information.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.sirikit/documentation/Intents",
        "doc://com.apple.sirikit/documentation/Intents/INBalanceAmount"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.sirikit/documentation/Intents/INBalanceAmount/init(amount:balanceType:)"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(cs)INBalanceAmount(im)initWithAmount:balanceType:",
    "fragments": [
      {
        "kind": "identifier",
        "text": "init"
      },
      {
        "kind": "text",
        "text": "?("
      },
      {
        "kind": "externalParam",
        "text": "amount"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:objc(cs)NSDecimalNumber",
        "text": "NSDecimalNumber"
      },
      {
        "kind": "text",
        "text": ", "
      },
      {
        "kind": "externalParam",
        "text": "balanceType"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@E@INBalanceType",
        "text": "INBalanceType"
      },
      {
        "kind": "text",
        "text": ")"
      }
    ],
    "modules": [
      {
        "name": "Intents"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "initWithAmount:balanceType:"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "11.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "11.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.1",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "4.0",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Initializer",
    "symbolKind": "init",
    "title": "init(amount:balanceType:)"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "init"
            },
            {
              "kind": "text",
              "text": "?("
            },
            {
              "kind": "externalParam",
              "text": "amount"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSDecimalNumber",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)NSDecimalNumber",
              "text": "NSDecimalNumber"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "kind": "externalParam",
              "text": "balanceType"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.sirikit/documentation/Intents/INBalanceType",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@E@INBalanceType",
              "text": "INBalanceType"
            },
            {
              "kind": "text",
              "text": ")"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "kind": "parameters",
      "parameters": [
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "The numerical amount associated with the balance.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "amount"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "The type that indicates what the balance represents. For a list of possible values, see ",
                  "type": "text"
                },
                {
                  "identifier": "doc://com.apple.sirikit/documentation/Intents/INBalanceType",
                  "isActive": true,
                  "type": "reference"
                },
                {
                  "text": ".",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "balanceType"
        }
      ]
    },
    {
      "content": [
        {
          "anchor": "return-value",
          "level": 2,
          "text": "Return Value",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "An initialized ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.sirikit/documentation/Intents/INBalanceAmount",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " object.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    },
    {
      "content": [
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Use this method when initializing balance amounts that do not involve money.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "",
                  "type": "text"
                },
                {
                  "text": " ",
                  "type": "text"
                },
                {
                  "text": "When initializing a balance involving money, use the ",
                  "type": "text"
                },
                {
                  "identifier": "doc://com.apple.sirikit/documentation/Intents/INBalanceAmount/init(amount:currencyCode:)",
                  "isActive": true,
                  "type": "reference"
                },
                {
                  "text": " method instead. Using that initializer method lets you specify the currency associated with the monetary amount.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "Important",
          "style": "important",
          "type": "aside"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.sirikit/documentation/Intents": {
      "abstract": [
        {
          "text": "Empower people to customize interactions for your app on their device.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents",
      "kind": "symbol",
      "role": "collection",
      "title": "Intents",
      "type": "topic",
      "url": "/documentation/intents"
    },
    "doc://com.apple.sirikit/documentation/Intents/INBalanceAmount": {
      "abstract": [
        {
          "text": "A balance associated with an account.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "INBalanceAmount"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INBalanceAmount",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INBalanceAmount"
        }
      ],
      "role": "symbol",
      "title": "INBalanceAmount",
      "type": "topic",
      "url": "/documentation/intents/inbalanceamount"
    },
    "doc://com.apple.sirikit/documentation/Intents/INBalanceAmount/init(amount:balanceType:)": {
      "abstract": [
        {
          "text": "Initializes a balance amount object with a customizable type of information.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "?("
        },
        {
          "kind": "externalParam",
          "text": "amount"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSDecimalNumber",
          "text": "NSDecimalNumber"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "balanceType"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@INBalanceType",
          "text": "INBalanceType"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INBalanceAmount/init(amount:balanceType:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "initWithAmount:balanceType:"
        }
      ],
      "role": "symbol",
      "title": "init(amount:balanceType:)",
      "type": "topic",
      "url": "/documentation/intents/inbalanceamount/init(amount:balancetype:)"
    },
    "doc://com.apple.sirikit/documentation/Intents/INBalanceAmount/init(amount:currencyCode:)": {
      "abstract": [
        {
          "text": "Initializes a balance amount with a monetary amount.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "amount"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSDecimalNumber",
          "text": "NSDecimalNumber"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "currencyCode"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INBalanceAmount/init(amount:currencyCode:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "initWithAmount:currencyCode:"
        }
      ],
      "role": "symbol",
      "title": "init(amount:currencyCode:)",
      "type": "topic",
      "url": "/documentation/intents/inbalanceamount/init(amount:currencycode:)"
    },
    "doc://com.apple.sirikit/documentation/Intents/INBalanceType": {
      "abstract": [
        {
          "text": "Constants indicating the meaning of a balance.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "INBalanceType"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INBalanceType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INBalanceType"
        }
      ],
      "role": "symbol",
      "title": "INBalanceType",
      "type": "topic",
      "url": "/documentation/intents/inbalancetype"
    },
    "doc://com.externally.resolved.symbol/c:objc(cs)NSDecimalNumber": {
      "abstract": [
        {
          "text": "An object for representing and performing arithmetic on base-10 numbers that bridges to ; use  when you need reference semantics or other Foundation-specific behavior.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "class "
        },
        {
          "kind": "identifier",
          "text": "NSDecimalNumber"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSDecimalNumber",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSDecimalNumber",
      "type": "topic",
      "url": "/documentation/foundation/nsdecimalnumber"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Initializing-a-Balance-Amount-Object",
      "generated": true,
      "identifiers": [
        "doc://com.apple.sirikit/documentation/Intents/INBalanceAmount/init(amount:currencyCode:)"
      ],
      "title": "Initializing a Balance Amount Object"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "11.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "11.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.1",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "4.0",
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Instance Method"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "initWithAmount:balanceType:"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "method"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "initWithAmount:balanceType:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.sirikit/documentation/Intents",
                "doc://com.apple.sirikit/documentation/Intents/INBalanceAmount"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Initializing-a-Balance-Amount-Object",
              "generated": true,
              "identifiers": [
                "doc://com.apple.sirikit/documentation/Intents/INBalanceAmount/init(amount:currencyCode:)"
              ],
              "title": "Initializing a Balance Amount Object"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "text",
                    "text": "- ("
                  },
                  {
                    "kind": "keyword",
                    "text": "instancetype"
                  },
                  {
                    "kind": "text",
                    "text": ") "
                  },
                  {
                    "kind": "identifier",
                    "text": "initWithAmount:"
                  },
                  {
                    "kind": "text",
                    "text": "("
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSDecimalNumber",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(cs)NSDecimalNumber",
                    "text": "NSDecimalNumber"
                  },
                  {
                    "kind": "text",
                    "text": " *) "
                  },
                  {
                    "kind": "internalParam",
                    "text": "amount"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "balanceType:"
                  },
                  {
                    "kind": "text",
                    "text": "("
                  },
                  {
                    "identifier": "doc://com.apple.sirikit/documentation/Intents/INBalanceType",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@E@INBalanceType",
                    "text": "INBalanceType"
                  },
                  {
                    "kind": "text",
                    "text": ") "
                  },
                  {
                    "kind": "internalParam",
                    "text": "balanceType"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/1",
          "value": {
            "kind": "parameters",
            "parameters": [
              {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "The numerical amount associated with the balance.",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ],
                "name": "amount"
              },
              {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "The type that indicates what the balance represents. For a list of possible values, see ",
                        "type": "text"
                      },
                      {
                        "identifier": "doc://com.apple.sirikit/documentation/Intents/INBalanceType",
                        "isActive": true,
                        "type": "reference"
                      },
                      {
                        "text": ".",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ],
                "name": "balanceType"
              }
            ]
          }
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/2",
          "value": {
            "content": [
              {
                "anchor": "return-value",
                "level": 2,
                "text": "Return Value",
                "type": "heading"
              },
              {
                "inlineContent": [
                  {
                    "text": "An initialized ",
                    "type": "text"
                  },
                  {
                    "identifier": "doc://com.apple.sirikit/documentation/Intents/INBalanceAmount",
                    "isActive": true,
                    "type": "reference"
                  },
                  {
                    "text": " object.",
                    "type": "text"
                  }
                ],
                "type": "paragraph"
              }
            ],
            "kind": "content"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:objc(cs)NSDecimalNumber/abstract",
          "value": [
            {
              "text": "An object for representing and performing arithmetic on base-10 numbers.",
              "type": "text"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INBalanceAmount~1init(amount:currencyCode:)/title",
          "value": "initWithAmount:currencyCode:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INBalanceAmount~1init(amount:currencyCode:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "initWithAmount:currencyCode:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INBalanceAmount/title",
          "value": "INBalanceAmount"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INBalanceAmount/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INBalanceAmount"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INBalanceAmount/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "INBalanceAmount"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INBalanceType/title",
          "value": "INBalanceType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INBalanceType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INBalanceType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INBalanceType/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "INBalanceType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INBalanceAmount~1init(amount:balanceType:)/title",
          "value": "initWithAmount:balanceType:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INBalanceAmount~1init(amount:balanceType:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "initWithAmount:balanceType:"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/intents/inbalanceamount/init(amount:balancetype:)"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/intents/inbalanceamount/init(amount:balancetype:)"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
