{
  "abstract": [
    {
      "text": "Constants for system-provided icons.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.uikit/documentation/UIKit",
        "doc://com.apple.uikit/documentation/UIKit/UIApplicationShortcutIcon"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.uikit/documentation/UIKit/UIApplicationShortcutIcon/IconType"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "extendedModule": "UIKit",
    "externalID": "c:@E@UIApplicationShortcutIconType",
    "fragments": [
      {
        "kind": "keyword",
        "text": "enum"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "IconType"
      }
    ],
    "modules": [
      {
        "name": "UIKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "IconType"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "9.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "9.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.1",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Enumeration",
    "symbolKind": "enum",
    "title": "UIApplicationShortcutIcon.IconType"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "enum"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "IconType"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.uikit/documentation/UIKit": {
      "abstract": [
        {
          "text": "Construct and manage a graphical, event-driven user interface for your iOS, iPadOS, or tvOS app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit",
      "kind": "symbol",
      "role": "collection",
      "title": "UIKit",
      "type": "topic",
      "url": "/documentation/uikit"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIApplicationShortcutIcon": {
      "abstract": [
        {
          "text": "An image you can optionally associate with a Home Screen quick action to improve its appearance and usability.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UIApplicationShortcutIcon"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIApplicationShortcutIcon",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIApplicationShortcutIcon"
        }
      ],
      "role": "symbol",
      "title": "UIApplicationShortcutIcon",
      "type": "topic",
      "url": "/documentation/uikit/uiapplicationshortcuticon"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIApplicationShortcutIcon/IconType": {
      "abstract": [
        {
          "text": "Constants for system-provided icons.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "IconType"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIApplicationShortcutIcon/IconType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "IconType"
        }
      ],
      "role": "symbol",
      "title": "UIApplicationShortcutIcon.IconType",
      "type": "topic",
      "url": "/documentation/uikit/uiapplicationshortcuticon/icontype"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIApplicationShortcutIcon/IconType/add": {
      "abstract": [
        {
          "text": "An icon for a quick action that adds an item.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "add"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIApplicationShortcutIcon/IconType/add",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIApplicationShortcutIconTypeAdd"
        }
      ],
      "role": "symbol",
      "title": "UIApplicationShortcutIcon.IconType.add",
      "type": "topic",
      "url": "/documentation/uikit/uiapplicationshortcuticon/icontype/add"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIApplicationShortcutIcon/IconType/alarm": {
      "abstract": [
        {
          "text": "An icon for a quick action that offers creation of an alarm.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "alarm"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIApplicationShortcutIcon/IconType/alarm",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIApplicationShortcutIconTypeAlarm"
        }
      ],
      "role": "symbol",
      "title": "UIApplicationShortcutIcon.IconType.alarm",
      "type": "topic",
      "url": "/documentation/uikit/uiapplicationshortcuticon/icontype/alarm"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIApplicationShortcutIcon/IconType/audio": {
      "abstract": [
        {
          "text": "An icon for a quick action that offers use of audio.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "audio"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIApplicationShortcutIcon/IconType/audio",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIApplicationShortcutIconTypeAudio"
        }
      ],
      "role": "symbol",
      "title": "UIApplicationShortcutIcon.IconType.audio",
      "type": "topic",
      "url": "/documentation/uikit/uiapplicationshortcuticon/icontype/audio"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIApplicationShortcutIcon/IconType/bookmark": {
      "abstract": [
        {
          "text": "An icon for a quick action that offers creation of a bookmark.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "bookmark"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIApplicationShortcutIcon/IconType/bookmark",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIApplicationShortcutIconTypeBookmark"
        }
      ],
      "role": "symbol",
      "title": "UIApplicationShortcutIcon.IconType.bookmark",
      "type": "topic",
      "url": "/documentation/uikit/uiapplicationshortcuticon/icontype/bookmark"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIApplicationShortcutIcon/IconType/capturePhoto": {
      "abstract": [
        {
          "text": "An icon for a quick action that offers photo capture.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "capturePhoto"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIApplicationShortcutIcon/IconType/capturePhoto",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIApplicationShortcutIconTypeCapturePhoto"
        }
      ],
      "role": "symbol",
      "title": "UIApplicationShortcutIcon.IconType.capturePhoto",
      "type": "topic",
      "url": "/documentation/uikit/uiapplicationshortcuticon/icontype/capturephoto"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIApplicationShortcutIcon/IconType/captureVideo": {
      "abstract": [
        {
          "text": "An icon for a quick action that offers video capture.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "captureVideo"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIApplicationShortcutIcon/IconType/captureVideo",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIApplicationShortcutIconTypeCaptureVideo"
        }
      ],
      "role": "symbol",
      "title": "UIApplicationShortcutIcon.IconType.captureVideo",
      "type": "topic",
      "url": "/documentation/uikit/uiapplicationshortcuticon/icontype/capturevideo"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIApplicationShortcutIcon/IconType/cloud": {
      "abstract": [
        {
          "text": "An icon for a quick action that offers cloud access.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "cloud"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIApplicationShortcutIcon/IconType/cloud",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIApplicationShortcutIconTypeCloud"
        }
      ],
      "role": "symbol",
      "title": "UIApplicationShortcutIcon.IconType.cloud",
      "type": "topic",
      "url": "/documentation/uikit/uiapplicationshortcuticon/icontype/cloud"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIApplicationShortcutIcon/IconType/compose": {
      "abstract": [
        {
          "text": "An icon for a quick action that lets a user compose new content.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "compose"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIApplicationShortcutIcon/IconType/compose",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIApplicationShortcutIconTypeCompose"
        }
      ],
      "role": "symbol",
      "title": "UIApplicationShortcutIcon.IconType.compose",
      "type": "topic",
      "url": "/documentation/uikit/uiapplicationshortcuticon/icontype/compose"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIApplicationShortcutIcon/IconType/confirmation": {
      "abstract": [
        {
          "text": "An icon for a quick action that indicates confirmation.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "confirmation"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIApplicationShortcutIcon/IconType/confirmation",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIApplicationShortcutIconTypeConfirmation"
        }
      ],
      "role": "symbol",
      "title": "UIApplicationShortcutIcon.IconType.confirmation",
      "type": "topic",
      "url": "/documentation/uikit/uiapplicationshortcuticon/icontype/confirmation"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIApplicationShortcutIcon/IconType/contact": {
      "abstract": [
        {
          "text": "An icon for a quick action that chooses a generic contact.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "contact"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIApplicationShortcutIcon/IconType/contact",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIApplicationShortcutIconTypeContact"
        }
      ],
      "role": "symbol",
      "title": "UIApplicationShortcutIcon.IconType.contact",
      "type": "topic",
      "url": "/documentation/uikit/uiapplicationshortcuticon/icontype/contact"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIApplicationShortcutIcon/IconType/date": {
      "abstract": [
        {
          "text": "An icon for a quick action that offers use of a calendar.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "date"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIApplicationShortcutIcon/IconType/date",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIApplicationShortcutIconTypeDate"
        }
      ],
      "role": "symbol",
      "title": "UIApplicationShortcutIcon.IconType.date",
      "type": "topic",
      "url": "/documentation/uikit/uiapplicationshortcuticon/icontype/date"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIApplicationShortcutIcon/IconType/favorite": {
      "abstract": [
        {
          "text": "An icon for a quick action that lets a user designate a favorite item.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "favorite"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIApplicationShortcutIcon/IconType/favorite",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIApplicationShortcutIconTypeFavorite"
        }
      ],
      "role": "symbol",
      "title": "UIApplicationShortcutIcon.IconType.favorite",
      "type": "topic",
      "url": "/documentation/uikit/uiapplicationshortcuticon/icontype/favorite"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIApplicationShortcutIcon/IconType/home": {
      "abstract": [
        {
          "text": "An icon for a quick action that indicates home.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "home"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIApplicationShortcutIcon/IconType/home",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIApplicationShortcutIconTypeHome"
        }
      ],
      "role": "symbol",
      "title": "UIApplicationShortcutIcon.IconType.home",
      "type": "topic",
      "url": "/documentation/uikit/uiapplicationshortcuticon/icontype/home"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIApplicationShortcutIcon/IconType/init(rawValue:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "?("
        },
        {
          "kind": "externalParam",
          "text": "rawValue"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIApplicationShortcutIcon/IconType/init(rawValue:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "init(rawValue:)",
      "type": "topic",
      "url": "/documentation/uikit/uiapplicationshortcuticon/icontype/init(rawvalue:)"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIApplicationShortcutIcon/IconType/invitation": {
      "abstract": [
        {
          "text": "An icon for a quick action that indicates an invitation.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "invitation"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIApplicationShortcutIcon/IconType/invitation",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIApplicationShortcutIconTypeInvitation"
        }
      ],
      "role": "symbol",
      "title": "UIApplicationShortcutIcon.IconType.invitation",
      "type": "topic",
      "url": "/documentation/uikit/uiapplicationshortcuticon/icontype/invitation"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIApplicationShortcutIcon/IconType/location": {
      "abstract": [
        {
          "text": "An icon for a quick action that accesses the user’s current location.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "location"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIApplicationShortcutIcon/IconType/location",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIApplicationShortcutIconTypeLocation"
        }
      ],
      "role": "symbol",
      "title": "UIApplicationShortcutIcon.IconType.location",
      "type": "topic",
      "url": "/documentation/uikit/uiapplicationshortcuticon/icontype/location"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIApplicationShortcutIcon/IconType/love": {
      "abstract": [
        {
          "text": "An icon for a quick action that lets a user designate a loved item.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "love"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIApplicationShortcutIcon/IconType/love",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIApplicationShortcutIconTypeLove"
        }
      ],
      "role": "symbol",
      "title": "UIApplicationShortcutIcon.IconType.love",
      "type": "topic",
      "url": "/documentation/uikit/uiapplicationshortcuticon/icontype/love"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIApplicationShortcutIcon/IconType/mail": {
      "abstract": [
        {
          "text": "An icon for a quick action that offers use of mail.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "mail"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIApplicationShortcutIcon/IconType/mail",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIApplicationShortcutIconTypeMail"
        }
      ],
      "role": "symbol",
      "title": "UIApplicationShortcutIcon.IconType.mail",
      "type": "topic",
      "url": "/documentation/uikit/uiapplicationshortcuticon/icontype/mail"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIApplicationShortcutIcon/IconType/markLocation": {
      "abstract": [
        {
          "text": "An icon for a quick action that lets a user mark a location.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "markLocation"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIApplicationShortcutIcon/IconType/markLocation",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIApplicationShortcutIconTypeMarkLocation"
        }
      ],
      "role": "symbol",
      "title": "UIApplicationShortcutIcon.IconType.markLocation",
      "type": "topic",
      "url": "/documentation/uikit/uiapplicationshortcuticon/icontype/marklocation"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIApplicationShortcutIcon/IconType/message": {
      "abstract": [
        {
          "text": "An icon for a quick action that offers use of messaging.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "message"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIApplicationShortcutIcon/IconType/message",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIApplicationShortcutIconTypeMessage"
        }
      ],
      "role": "symbol",
      "title": "UIApplicationShortcutIcon.IconType.message",
      "type": "topic",
      "url": "/documentation/uikit/uiapplicationshortcuticon/icontype/message"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIApplicationShortcutIcon/IconType/pause": {
      "abstract": [
        {
          "text": "An icon for  a quick action that pauses media playback.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "pause"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIApplicationShortcutIcon/IconType/pause",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIApplicationShortcutIconTypePause"
        }
      ],
      "role": "symbol",
      "title": "UIApplicationShortcutIcon.IconType.pause",
      "type": "topic",
      "url": "/documentation/uikit/uiapplicationshortcuticon/icontype/pause"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIApplicationShortcutIcon/IconType/play": {
      "abstract": [
        {
          "text": "An icon for a quick action that plays media.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "play"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIApplicationShortcutIcon/IconType/play",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIApplicationShortcutIconTypePlay"
        }
      ],
      "role": "symbol",
      "title": "UIApplicationShortcutIcon.IconType.play",
      "type": "topic",
      "url": "/documentation/uikit/uiapplicationshortcuticon/icontype/play"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIApplicationShortcutIcon/IconType/prohibit": {
      "abstract": [
        {
          "text": "An icon for a quick action that disallows something.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "prohibit"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIApplicationShortcutIcon/IconType/prohibit",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIApplicationShortcutIconTypeProhibit"
        }
      ],
      "role": "symbol",
      "title": "UIApplicationShortcutIcon.IconType.prohibit",
      "type": "topic",
      "url": "/documentation/uikit/uiapplicationshortcuticon/icontype/prohibit"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIApplicationShortcutIcon/IconType/search": {
      "abstract": [
        {
          "text": "An icon a quick action that offers search.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "search"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIApplicationShortcutIcon/IconType/search",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIApplicationShortcutIconTypeSearch"
        }
      ],
      "role": "symbol",
      "title": "UIApplicationShortcutIcon.IconType.search",
      "type": "topic",
      "url": "/documentation/uikit/uiapplicationshortcuticon/icontype/search"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIApplicationShortcutIcon/IconType/share": {
      "abstract": [
        {
          "text": "An icon for a quick action that offers content sharing.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "share"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIApplicationShortcutIcon/IconType/share",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIApplicationShortcutIconTypeShare"
        }
      ],
      "role": "symbol",
      "title": "UIApplicationShortcutIcon.IconType.share",
      "type": "topic",
      "url": "/documentation/uikit/uiapplicationshortcuticon/icontype/share"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIApplicationShortcutIcon/IconType/shuffle": {
      "abstract": [
        {
          "text": "An icon for a quick action that offers shuffle mode.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "shuffle"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIApplicationShortcutIcon/IconType/shuffle",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIApplicationShortcutIconTypeShuffle"
        }
      ],
      "role": "symbol",
      "title": "UIApplicationShortcutIcon.IconType.shuffle",
      "type": "topic",
      "url": "/documentation/uikit/uiapplicationshortcuticon/icontype/shuffle"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIApplicationShortcutIcon/IconType/task": {
      "abstract": [
        {
          "text": "An icon for a quick action that offers task creation.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "task"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIApplicationShortcutIcon/IconType/task",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIApplicationShortcutIconTypeTask"
        }
      ],
      "role": "symbol",
      "title": "UIApplicationShortcutIcon.IconType.task",
      "type": "topic",
      "url": "/documentation/uikit/uiapplicationshortcuticon/icontype/task"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIApplicationShortcutIcon/IconType/taskCompleted": {
      "abstract": [
        {
          "text": "An icon for a quick action that offers task completion.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "taskCompleted"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIApplicationShortcutIcon/IconType/taskCompleted",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIApplicationShortcutIconTypeTaskCompleted"
        }
      ],
      "role": "symbol",
      "title": "UIApplicationShortcutIcon.IconType.taskCompleted",
      "type": "topic",
      "url": "/documentation/uikit/uiapplicationshortcuticon/icontype/taskcompleted"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIApplicationShortcutIcon/IconType/time": {
      "abstract": [
        {
          "text": "An icon for a quick action that offers use of a clock or timer.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "time"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIApplicationShortcutIcon/IconType/time",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIApplicationShortcutIconTypeTime"
        }
      ],
      "role": "symbol",
      "title": "UIApplicationShortcutIcon.IconType.time",
      "type": "topic",
      "url": "/documentation/uikit/uiapplicationshortcuticon/icontype/time"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIApplicationShortcutIcon/IconType/update": {
      "abstract": [
        {
          "text": "An icon for a quick action that offers updating.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "update"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIApplicationShortcutIcon/IconType/update",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIApplicationShortcutIconTypeUpdate"
        }
      ],
      "role": "symbol",
      "title": "UIApplicationShortcutIcon.IconType.update",
      "type": "topic",
      "url": "/documentation/uikit/uiapplicationshortcuticon/icontype/update"
    },
    "doc://com.externally.resolved.symbol/c:@T@NSInteger": {
      "abstract": [
        {
          "text": "Describes an integer.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "typealias "
        },
        {
          "kind": "identifier",
          "text": "NSInteger"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:@T@NSInteger",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSInteger",
      "type": "topic",
      "url": "/documentation/objectivec/nsinteger"
    },
    "doc://com.externally.resolved.symbol/s:SH": {
      "abstract": [
        {
          "text": "A type that can be hashed into a `Hasher` to produce an integer hash value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Hashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SQ",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SH",
      "kind": "symbol",
      "role": "symbol",
      "title": "Hashable",
      "type": "topic",
      "url": "/documentation/Swift/Hashable"
    },
    "doc://com.externally.resolved.symbol/s:SQ": {
      "abstract": [
        {
          "text": "A type that can be compared for value equality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SQ",
      "kind": "symbol",
      "role": "symbol",
      "title": "Equatable",
      "type": "topic",
      "url": "/documentation/Swift/Equatable"
    },
    "doc://com.externally.resolved.symbol/s:SY": {
      "abstract": [
        {
          "text": "A type that can be converted to and from an associated raw value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "RawRepresentable"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SY8RawValueQa",
          "text": "RawValue"
        },
        {
          "kind": "text",
          "text": ">"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SY",
      "kind": "symbol",
      "role": "symbol",
      "title": "RawRepresentable",
      "type": "topic",
      "url": "/documentation/Swift/RawRepresentable"
    },
    "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BitwiseCopyable"
        },
        {
          "kind": "text",
          "text": " : ~Escapable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "BitwiseCopyable",
      "type": "topic",
      "url": "/documentation/Swift/BitwiseCopyable"
    },
    "doc://com.externally.resolved.symbol/s:s8SendableP": {
      "abstract": [
        {
          "text": "A thread-safe type whose values can be shared across arbitrary concurrent contexts without introducing a risk of data races.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Sendable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s8SendableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "Sendable",
      "type": "topic",
      "url": "/documentation/Swift/Sendable"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
        "doc://com.externally.resolved.symbol/s:SQ",
        "doc://com.externally.resolved.symbol/s:SH",
        "doc://com.externally.resolved.symbol/s:SY",
        "doc://com.externally.resolved.symbol/s:s8SendableP"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "topicSections": [
    {
      "anchor": "Constants",
      "identifiers": [
        "doc://com.apple.uikit/documentation/UIKit/UIApplicationShortcutIcon/IconType/compose",
        "doc://com.apple.uikit/documentation/UIKit/UIApplicationShortcutIcon/IconType/play",
        "doc://com.apple.uikit/documentation/UIKit/UIApplicationShortcutIcon/IconType/pause",
        "doc://com.apple.uikit/documentation/UIKit/UIApplicationShortcutIcon/IconType/add",
        "doc://com.apple.uikit/documentation/UIKit/UIApplicationShortcutIcon/IconType/location",
        "doc://com.apple.uikit/documentation/UIKit/UIApplicationShortcutIcon/IconType/search",
        "doc://com.apple.uikit/documentation/UIKit/UIApplicationShortcutIcon/IconType/share",
        "doc://com.apple.uikit/documentation/UIKit/UIApplicationShortcutIcon/IconType/prohibit",
        "doc://com.apple.uikit/documentation/UIKit/UIApplicationShortcutIcon/IconType/contact",
        "doc://com.apple.uikit/documentation/UIKit/UIApplicationShortcutIcon/IconType/home",
        "doc://com.apple.uikit/documentation/UIKit/UIApplicationShortcutIcon/IconType/markLocation",
        "doc://com.apple.uikit/documentation/UIKit/UIApplicationShortcutIcon/IconType/favorite",
        "doc://com.apple.uikit/documentation/UIKit/UIApplicationShortcutIcon/IconType/love",
        "doc://com.apple.uikit/documentation/UIKit/UIApplicationShortcutIcon/IconType/cloud",
        "doc://com.apple.uikit/documentation/UIKit/UIApplicationShortcutIcon/IconType/invitation",
        "doc://com.apple.uikit/documentation/UIKit/UIApplicationShortcutIcon/IconType/confirmation",
        "doc://com.apple.uikit/documentation/UIKit/UIApplicationShortcutIcon/IconType/mail",
        "doc://com.apple.uikit/documentation/UIKit/UIApplicationShortcutIcon/IconType/message",
        "doc://com.apple.uikit/documentation/UIKit/UIApplicationShortcutIcon/IconType/date",
        "doc://com.apple.uikit/documentation/UIKit/UIApplicationShortcutIcon/IconType/time",
        "doc://com.apple.uikit/documentation/UIKit/UIApplicationShortcutIcon/IconType/capturePhoto",
        "doc://com.apple.uikit/documentation/UIKit/UIApplicationShortcutIcon/IconType/captureVideo",
        "doc://com.apple.uikit/documentation/UIKit/UIApplicationShortcutIcon/IconType/task",
        "doc://com.apple.uikit/documentation/UIKit/UIApplicationShortcutIcon/IconType/taskCompleted",
        "doc://com.apple.uikit/documentation/UIKit/UIApplicationShortcutIcon/IconType/alarm",
        "doc://com.apple.uikit/documentation/UIKit/UIApplicationShortcutIcon/IconType/bookmark",
        "doc://com.apple.uikit/documentation/UIKit/UIApplicationShortcutIcon/IconType/shuffle",
        "doc://com.apple.uikit/documentation/UIKit/UIApplicationShortcutIcon/IconType/audio",
        "doc://com.apple.uikit/documentation/UIKit/UIApplicationShortcutIcon/IconType/update"
      ],
      "title": "Constants"
    },
    {
      "anchor": "Initializers",
      "generated": true,
      "identifiers": [
        "doc://com.apple.uikit/documentation/UIKit/UIApplicationShortcutIcon/IconType/init(rawValue:)"
      ],
      "title": "Initializers"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "9.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "9.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.1",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "UIApplicationShortcutIconType"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "enum"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIApplicationShortcutIconType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UIApplicationShortcutIconType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.uikit/documentation/UIKit"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Constants",
              "identifiers": [
                "doc://com.apple.uikit/documentation/UIKit/UIApplicationShortcutIcon/IconType/compose",
                "doc://com.apple.uikit/documentation/UIKit/UIApplicationShortcutIcon/IconType/play",
                "doc://com.apple.uikit/documentation/UIKit/UIApplicationShortcutIcon/IconType/pause",
                "doc://com.apple.uikit/documentation/UIKit/UIApplicationShortcutIcon/IconType/add",
                "doc://com.apple.uikit/documentation/UIKit/UIApplicationShortcutIcon/IconType/location",
                "doc://com.apple.uikit/documentation/UIKit/UIApplicationShortcutIcon/IconType/search",
                "doc://com.apple.uikit/documentation/UIKit/UIApplicationShortcutIcon/IconType/share",
                "doc://com.apple.uikit/documentation/UIKit/UIApplicationShortcutIcon/IconType/prohibit",
                "doc://com.apple.uikit/documentation/UIKit/UIApplicationShortcutIcon/IconType/contact",
                "doc://com.apple.uikit/documentation/UIKit/UIApplicationShortcutIcon/IconType/home",
                "doc://com.apple.uikit/documentation/UIKit/UIApplicationShortcutIcon/IconType/markLocation",
                "doc://com.apple.uikit/documentation/UIKit/UIApplicationShortcutIcon/IconType/favorite",
                "doc://com.apple.uikit/documentation/UIKit/UIApplicationShortcutIcon/IconType/love",
                "doc://com.apple.uikit/documentation/UIKit/UIApplicationShortcutIcon/IconType/cloud",
                "doc://com.apple.uikit/documentation/UIKit/UIApplicationShortcutIcon/IconType/invitation",
                "doc://com.apple.uikit/documentation/UIKit/UIApplicationShortcutIcon/IconType/confirmation",
                "doc://com.apple.uikit/documentation/UIKit/UIApplicationShortcutIcon/IconType/mail",
                "doc://com.apple.uikit/documentation/UIKit/UIApplicationShortcutIcon/IconType/message",
                "doc://com.apple.uikit/documentation/UIKit/UIApplicationShortcutIcon/IconType/date",
                "doc://com.apple.uikit/documentation/UIKit/UIApplicationShortcutIcon/IconType/time",
                "doc://com.apple.uikit/documentation/UIKit/UIApplicationShortcutIcon/IconType/capturePhoto",
                "doc://com.apple.uikit/documentation/UIKit/UIApplicationShortcutIcon/IconType/captureVideo",
                "doc://com.apple.uikit/documentation/UIKit/UIApplicationShortcutIcon/IconType/task",
                "doc://com.apple.uikit/documentation/UIKit/UIApplicationShortcutIcon/IconType/taskCompleted",
                "doc://com.apple.uikit/documentation/UIKit/UIApplicationShortcutIcon/IconType/alarm",
                "doc://com.apple.uikit/documentation/UIKit/UIApplicationShortcutIcon/IconType/bookmark",
                "doc://com.apple.uikit/documentation/UIKit/UIApplicationShortcutIcon/IconType/shuffle",
                "doc://com.apple.uikit/documentation/UIKit/UIApplicationShortcutIcon/IconType/audio",
                "doc://com.apple.uikit/documentation/UIKit/UIApplicationShortcutIcon/IconType/update"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/seeAlsoSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "tvOS",
                  "visionOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "enum"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "UIApplicationShortcutIconType"
                  },
                  {
                    "kind": "text",
                    "text": " : "
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:@T@NSInteger",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@NSInteger",
                    "text": "NSInteger"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIApplicationShortcutIcon~1IconType~1search/title",
          "value": "UIApplicationShortcutIconTypeSearch"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIApplicationShortcutIcon~1IconType~1search/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIApplicationShortcutIconTypeSearch"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIApplicationShortcutIcon~1IconType~1cloud/title",
          "value": "UIApplicationShortcutIconTypeCloud"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIApplicationShortcutIcon~1IconType~1cloud/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIApplicationShortcutIconTypeCloud"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIApplicationShortcutIcon~1IconType~1date/title",
          "value": "UIApplicationShortcutIconTypeDate"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIApplicationShortcutIcon~1IconType~1date/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIApplicationShortcutIconTypeDate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIApplicationShortcutIcon~1IconType~1bookmark/title",
          "value": "UIApplicationShortcutIconTypeBookmark"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIApplicationShortcutIcon~1IconType~1bookmark/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIApplicationShortcutIconTypeBookmark"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIApplicationShortcutIcon~1IconType~1confirmation/title",
          "value": "UIApplicationShortcutIconTypeConfirmation"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIApplicationShortcutIcon~1IconType~1confirmation/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIApplicationShortcutIconTypeConfirmation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIApplicationShortcutIcon~1IconType~1compose/title",
          "value": "UIApplicationShortcutIconTypeCompose"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIApplicationShortcutIcon~1IconType~1compose/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIApplicationShortcutIconTypeCompose"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIApplicationShortcutIcon~1IconType~1home/title",
          "value": "UIApplicationShortcutIconTypeHome"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIApplicationShortcutIcon~1IconType~1home/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIApplicationShortcutIconTypeHome"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIApplicationShortcutIcon~1IconType~1task/title",
          "value": "UIApplicationShortcutIconTypeTask"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIApplicationShortcutIcon~1IconType~1task/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIApplicationShortcutIconTypeTask"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIApplicationShortcutIcon~1IconType~1update/title",
          "value": "UIApplicationShortcutIconTypeUpdate"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIApplicationShortcutIcon~1IconType~1update/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIApplicationShortcutIconTypeUpdate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIApplicationShortcutIcon~1IconType~1favorite/title",
          "value": "UIApplicationShortcutIconTypeFavorite"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIApplicationShortcutIcon~1IconType~1favorite/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIApplicationShortcutIconTypeFavorite"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIApplicationShortcutIcon~1IconType~1play/title",
          "value": "UIApplicationShortcutIconTypePlay"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIApplicationShortcutIcon~1IconType~1play/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIApplicationShortcutIconTypePlay"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIApplicationShortcutIcon~1IconType/title",
          "value": "UIApplicationShortcutIconType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIApplicationShortcutIcon~1IconType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIApplicationShortcutIconType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIApplicationShortcutIcon~1IconType/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UIApplicationShortcutIconType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIApplicationShortcutIcon~1IconType~1invitation/title",
          "value": "UIApplicationShortcutIconTypeInvitation"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIApplicationShortcutIcon~1IconType~1invitation/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIApplicationShortcutIconTypeInvitation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIApplicationShortcutIcon~1IconType~1alarm/title",
          "value": "UIApplicationShortcutIconTypeAlarm"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIApplicationShortcutIcon~1IconType~1alarm/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIApplicationShortcutIconTypeAlarm"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIApplicationShortcutIcon~1IconType~1taskCompleted/title",
          "value": "UIApplicationShortcutIconTypeTaskCompleted"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIApplicationShortcutIcon~1IconType~1taskCompleted/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIApplicationShortcutIconTypeTaskCompleted"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIApplicationShortcutIcon~1IconType~1location/title",
          "value": "UIApplicationShortcutIconTypeLocation"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIApplicationShortcutIcon~1IconType~1location/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIApplicationShortcutIconTypeLocation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIApplicationShortcutIcon~1IconType~1audio/title",
          "value": "UIApplicationShortcutIconTypeAudio"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIApplicationShortcutIcon~1IconType~1audio/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIApplicationShortcutIconTypeAudio"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIApplicationShortcutIcon~1IconType~1mail/title",
          "value": "UIApplicationShortcutIconTypeMail"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIApplicationShortcutIcon~1IconType~1mail/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIApplicationShortcutIconTypeMail"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIApplicationShortcutIcon~1IconType~1contact/title",
          "value": "UIApplicationShortcutIconTypeContact"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIApplicationShortcutIcon~1IconType~1contact/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIApplicationShortcutIconTypeContact"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIApplicationShortcutIcon~1IconType~1capturePhoto/title",
          "value": "UIApplicationShortcutIconTypeCapturePhoto"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIApplicationShortcutIcon~1IconType~1capturePhoto/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIApplicationShortcutIconTypeCapturePhoto"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIApplicationShortcutIcon~1IconType~1message/title",
          "value": "UIApplicationShortcutIconTypeMessage"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIApplicationShortcutIcon~1IconType~1message/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIApplicationShortcutIconTypeMessage"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIApplicationShortcutIcon~1IconType~1markLocation/title",
          "value": "UIApplicationShortcutIconTypeMarkLocation"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIApplicationShortcutIcon~1IconType~1markLocation/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIApplicationShortcutIconTypeMarkLocation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIApplicationShortcutIcon~1IconType~1share/title",
          "value": "UIApplicationShortcutIconTypeShare"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIApplicationShortcutIcon~1IconType~1share/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIApplicationShortcutIconTypeShare"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIApplicationShortcutIcon~1IconType~1prohibit/title",
          "value": "UIApplicationShortcutIconTypeProhibit"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIApplicationShortcutIcon~1IconType~1prohibit/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIApplicationShortcutIconTypeProhibit"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIApplicationShortcutIcon~1IconType~1captureVideo/title",
          "value": "UIApplicationShortcutIconTypeCaptureVideo"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIApplicationShortcutIcon~1IconType~1captureVideo/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIApplicationShortcutIconTypeCaptureVideo"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIApplicationShortcutIcon/title",
          "value": "UIApplicationShortcutIcon"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIApplicationShortcutIcon/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIApplicationShortcutIcon"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIApplicationShortcutIcon/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UIApplicationShortcutIcon"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIApplicationShortcutIcon~1IconType~1add/title",
          "value": "UIApplicationShortcutIconTypeAdd"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIApplicationShortcutIcon~1IconType~1add/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIApplicationShortcutIconTypeAdd"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIApplicationShortcutIcon~1IconType~1love/title",
          "value": "UIApplicationShortcutIconTypeLove"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIApplicationShortcutIcon~1IconType~1love/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIApplicationShortcutIconTypeLove"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIApplicationShortcutIcon~1IconType~1shuffle/title",
          "value": "UIApplicationShortcutIconTypeShuffle"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIApplicationShortcutIcon~1IconType~1shuffle/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIApplicationShortcutIconTypeShuffle"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIApplicationShortcutIcon~1IconType~1pause/title",
          "value": "UIApplicationShortcutIconTypePause"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIApplicationShortcutIcon~1IconType~1pause/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIApplicationShortcutIconTypePause"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIApplicationShortcutIcon~1IconType~1time/title",
          "value": "UIApplicationShortcutIconTypeTime"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIApplicationShortcutIcon~1IconType~1time/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIApplicationShortcutIconTypeTime"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/uikit/uiapplicationshortcuticon/icontype"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/uikit/uiapplicationshortcuticon/icontype"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
