{
  "abstract": [
    {
      "text": "An array of strings that identifies the ad networks a publisher app shows advertisements for.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.bundleresources/documentation/BundleResources",
        "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/AdNetworkIdentifiers"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "plist:Information_Property_List.AdNetworkIdentifiers",
    "modules": [
      {
        "name": "Bundle Resources"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "AdNetworkIdentifiers"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "17.4",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "17.4",
        "name": "iPadOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Property List Key",
    "symbolKind": "typealias",
    "title": "AdNetworkIdentifiers"
  },
  "primaryContentSections": [
    {
      "details": {
        "name": "AdNetworkIdentifiers",
        "platforms": [],
        "titleStyle": "symbol",
        "value": [
          {
            "arrayMode": true,
            "baseType": "string "
          }
        ]
      },
      "kind": "details",
      "title": "Details"
    },
    {
      "content": [
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Use this key to identify which ad networks the publisher app shows advertisements for. For more information, see ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/AdAttributionKit/configuring-a-publisher-app",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ".",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.bundleresources/documentation/BundleResources": {
      "abstract": [
        {
          "text": "Resources located in an app, framework, or plugin bundle.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources",
      "kind": "symbol",
      "role": "collection",
      "title": "Bundle Resources",
      "type": "topic",
      "url": "/documentation/bundleresources"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List": {
      "abstract": [
        {
          "text": "A resource containing key-value pairs that identify and configure a bundle.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List",
      "kind": "symbol",
      "name": "Information Property List",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "Information Property List"
        }
      ],
      "role": "symbol",
      "title": "Information Property List",
      "titleStyle": "symbol",
      "type": "topic",
      "url": "/documentation/bundleresources/information-property-list"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/AdNetworkIdentifiers": {
      "abstract": [
        {
          "text": "An array of strings that identifies the ad networks a publisher app shows advertisements for.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/AdNetworkIdentifiers",
      "kind": "symbol",
      "name": "AdNetworkIdentifiers",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AdNetworkIdentifiers"
        }
      ],
      "role": "symbol",
      "title": "AdNetworkIdentifiers",
      "titleStyle": "symbol",
      "type": "topic",
      "url": "/documentation/bundleresources/information-property-list/adnetworkidentifiers"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/AttributionCopyEndpoint": {
      "abstract": [
        {
          "text": "A key that defines a URL that AdAttributionKit uses to deliver copies of ad attribution postbacks.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/AttributionCopyEndpoint",
      "kind": "symbol",
      "name": "AttributionCopyEndpoint",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AttributionCopyEndpoint"
        }
      ],
      "role": "symbol",
      "title": "AttributionCopyEndpoint",
      "titleStyle": "symbol",
      "type": "topic",
      "url": "/documentation/bundleresources/information-property-list/attributioncopyendpoint"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/EligibleForAdAttributionKitReengagementPostbackCopies": {
      "abstract": [
        {
          "text": "A Boolean value that indicates whether the developer receives copies of AdAttributionKit reengagement postbacks.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/EligibleForAdAttributionKitReengagementPostbackCopies",
      "kind": "symbol",
      "name": "EligibleForAdAttributionKitReengagementPostbackCopies",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "EligibleForAdAttributionKitReengagementPostbackCopies"
        }
      ],
      "role": "symbol",
      "title": "EligibleForAdAttributionKitReengagementPostbackCopies",
      "titleStyle": "symbol",
      "type": "topic",
      "url": "/documentation/bundleresources/information-property-list/eligibleforadattributionkitreengagementpostbackcopies"
    },
    "doc://com.apple.documentation/documentation/AdAttributionKit/configuring-a-publisher-app": {
      "abstract": [
        {
          "text": "Set up a publisher app to participate in ad campaigns.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/AdAttributionKit/configuring-a-publisher-app",
      "kind": "article",
      "role": "article",
      "title": "Configuring a publisher app",
      "type": "topic",
      "url": "/documentation/AdAttributionKit/configuring-a-publisher-app"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Ad-attributions",
      "generated": true,
      "identifiers": [
        "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/AttributionCopyEndpoint",
        "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/EligibleForAdAttributionKitReengagementPostbackCopies"
      ],
      "title": "Ad attributions"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "17.4",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "17.4",
              "name": "iPadOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Property List Key"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "AdNetworkIdentifiers"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "typealias"
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AdNetworkIdentifiers"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.bundleresources/documentation/BundleResources",
                "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Ad-attributions",
              "generated": true,
              "identifiers": [
                "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/AttributionCopyEndpoint",
                "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/EligibleForAdAttributionKitReengagementPostbackCopies"
              ],
              "title": "Ad attributions"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1AttributionCopyEndpoint/title",
          "value": "AttributionCopyEndpoint"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1AttributionCopyEndpoint/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AttributionCopyEndpoint"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1AdNetworkIdentifiers/title",
          "value": "AdNetworkIdentifiers"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1AdNetworkIdentifiers/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AdNetworkIdentifiers"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1EligibleForAdAttributionKitReengagementPostbackCopies/title",
          "value": "EligibleForAdAttributionKitReengagementPostbackCopies"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1EligibleForAdAttributionKitReengagementPostbackCopies/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "EligibleForAdAttributionKitReengagementPostbackCopies"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List/title",
          "value": "Information Property List"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "Information Property List"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/bundleresources/information-property-list/adnetworkidentifiers"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/bundleresources/information-property-list/adnetworkidentifiers"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
