{
  "abstract": [
    {
      "text": "An array of strings containing developer-specified task identifiers in reverse URL notation.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.bundleresources/documentation/BundleResources",
        "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/BGTaskSchedulerPermittedIdentifiers"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "plist:Information_Property_List.BGTaskSchedulerPermittedIdentifiers",
    "modules": [
      {
        "name": "Bundle Resources"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "BGTaskSchedulerPermittedIdentifiers"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.0",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Property List Key",
    "symbolKind": "typealias",
    "title": "BGTaskSchedulerPermittedIdentifiers"
  },
  "primaryContentSections": [
    {
      "details": {
        "ideTitle": "Permitted background task scheduler identifiers",
        "name": "BGTaskSchedulerPermittedIdentifiers",
        "platforms": [],
        "titleStyle": "symbol",
        "value": [
          {
            "arrayMode": true,
            "baseType": "string "
          }
        ]
      },
      "kind": "details",
      "title": "Details"
    }
  ],
  "references": {
    "doc://com.apple.bundleresources/documentation/BundleResources": {
      "abstract": [
        {
          "text": "Resources located in an app, framework, or plugin bundle.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources",
      "kind": "symbol",
      "role": "collection",
      "title": "Bundle Resources",
      "type": "topic",
      "url": "/documentation/bundleresources"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List": {
      "abstract": [
        {
          "text": "A resource containing key-value pairs that identify and configure a bundle.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List",
      "kind": "symbol",
      "name": "Information Property List",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "Information Property List"
        }
      ],
      "role": "symbol",
      "title": "Information Property List",
      "titleStyle": "symbol",
      "type": "topic",
      "url": "/documentation/bundleresources/information-property-list"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/BGTaskSchedulerPermittedIdentifiers": {
      "abstract": [
        {
          "text": "An array of strings containing developer-specified task identifiers in reverse URL notation.",
          "type": "text"
        }
      ],
      "ideTitle": "Permitted background task scheduler identifiers",
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/BGTaskSchedulerPermittedIdentifiers",
      "kind": "symbol",
      "name": "BGTaskSchedulerPermittedIdentifiers",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "BGTaskSchedulerPermittedIdentifiers"
        }
      ],
      "role": "symbol",
      "title": "BGTaskSchedulerPermittedIdentifiers",
      "titleStyle": "symbol",
      "type": "topic",
      "url": "/documentation/bundleresources/information-property-list/bgtaskschedulerpermittedidentifiers"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/LSBackgroundOnly": {
      "abstract": [
        {
          "text": "A Boolean value indicating whether the app runs only in the background.",
          "type": "text"
        }
      ],
      "ideTitle": "Application is background only",
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/LSBackgroundOnly",
      "kind": "symbol",
      "name": "LSBackgroundOnly",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "LSBackgroundOnly"
        }
      ],
      "role": "symbol",
      "title": "LSBackgroundOnly",
      "titleStyle": "symbol",
      "type": "topic",
      "url": "/documentation/bundleresources/information-property-list/lsbackgroundonly"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/UIBackgroundModes": {
      "abstract": [
        {
          "text": "Services provided by an app that require it to run in the background.",
          "type": "text"
        }
      ],
      "ideTitle": "Required background modes",
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/UIBackgroundModes",
      "kind": "symbol",
      "name": "UIBackgroundModes",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIBackgroundModes"
        }
      ],
      "role": "symbol",
      "title": "UIBackgroundModes",
      "titleStyle": "symbol",
      "type": "topic",
      "url": "/documentation/bundleresources/information-property-list/uibackgroundmodes"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/WKBackgroundModes": {
      "abstract": [
        {
          "text": "The services a watchOS app provides that require it to continue running in the background.",
          "type": "text"
        }
      ],
      "ideTitle": "Required background modes (Watch)",
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/WKBackgroundModes",
      "kind": "symbol",
      "name": "WKBackgroundModes",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "WKBackgroundModes"
        }
      ],
      "role": "symbol",
      "title": "WKBackgroundModes",
      "titleStyle": "symbol",
      "type": "topic",
      "url": "/documentation/bundleresources/information-property-list/wkbackgroundmodes"
    },
    "doc://com.apple.documentation/documentation/BackgroundTasks/BGTaskScheduler": {
      "abstract": [
        {
          "text": "A class for scheduling task requests that launch your app in the background.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BGTaskScheduler"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/BackgroundTasks/BGTaskScheduler",
      "kind": "symbol",
      "role": "symbol",
      "title": "BGTaskScheduler",
      "type": "topic",
      "url": "/documentation/BackgroundTasks/BGTaskScheduler"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Related-Documentation",
      "identifiers": [
        "doc://com.apple.documentation/documentation/BackgroundTasks/BGTaskScheduler"
      ],
      "title": "Related Documentation"
    },
    {
      "anchor": "Background-execution",
      "generated": true,
      "identifiers": [
        "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/UIBackgroundModes",
        "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/WKBackgroundModes",
        "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/LSBackgroundOnly"
      ],
      "title": "Background execution"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.0",
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Property List Key"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "BGTaskSchedulerPermittedIdentifiers"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "typealias"
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "BGTaskSchedulerPermittedIdentifiers"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.bundleresources/documentation/BundleResources",
                "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Related-Documentation",
              "identifiers": [
                "doc://com.apple.documentation/documentation/BackgroundTasks/BGTaskScheduler"
              ],
              "title": "Related Documentation"
            },
            {
              "anchor": "Background-execution",
              "generated": true,
              "identifiers": [
                "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/UIBackgroundModes",
                "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/WKBackgroundModes",
                "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/LSBackgroundOnly"
              ],
              "title": "Background execution"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1UIBackgroundModes/title",
          "value": "UIBackgroundModes"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1UIBackgroundModes/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UIBackgroundModes"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1BGTaskSchedulerPermittedIdentifiers/title",
          "value": "BGTaskSchedulerPermittedIdentifiers"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1BGTaskSchedulerPermittedIdentifiers/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "BGTaskSchedulerPermittedIdentifiers"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1BackgroundTasks~1BGTaskScheduler/fragments",
          "value": [
            {
              "kind": "keyword",
              "text": "@interface"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "BGTaskScheduler"
            },
            {
              "kind": "text",
              "text": " : "
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)NSObject",
              "text": "NSObject"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1WKBackgroundModes/title",
          "value": "WKBackgroundModes"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1WKBackgroundModes/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "WKBackgroundModes"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List/title",
          "value": "Information Property List"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "Information Property List"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1LSBackgroundOnly/title",
          "value": "LSBackgroundOnly"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1LSBackgroundOnly/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "LSBackgroundOnly"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/bundleresources/information-property-list/bgtaskschedulerpermittedidentifiers"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/bundleresources/information-property-list/bgtaskschedulerpermittedidentifiers"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
