{"hierarchy":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.bundleresources/documentation/BundleResources","doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List"]]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["/documentation/bundleresources/information-property-list/cfapplehelpanchor"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["/documentation/bundleresources/information-property-list/cfapplehelpanchor"]}],"metadata":{"roleHeading":"Property List Key","platforms":[{"beta":false,"introducedAt":"10.0","deprecated":false,"unavailable":false,"name":"macOS"}],"title":"CFAppleHelpAnchor","symbolKind":"typealias","externalID":"plist:Information_Property_List.CFAppleHelpAnchor","modules":[{"name":"Bundle Resources"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"CFAppleHelpAnchor"}]},"seeAlsoSections":[{"generated":true,"anchor":"Help","title":"Help","identifiers":["doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/CFBundleHelpBookName","doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/CFBundleHelpBookFolder"]}],"primaryContentSections":[{"details":{"ideTitle":"Help file","value":[{"baseType":"string","arrayMode":false}],"titleStyle":"symbol","name":"CFAppleHelpAnchor","platforms":[]},"title":"Details","kind":"details"}],"sections":[],"abstract":[{"text":"The name of the bundle’s HTML help file.","type":"text"}],"schemaVersion":{"major":0,"minor":3,"patch":0},"identifier":{"url":"doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/CFAppleHelpAnchor","interfaceLanguage":"swift"},"kind":"symbol","references":{"doc://com.apple.bundleresources/documentation/BundleResources":{"identifier":"doc://com.apple.bundleresources/documentation/BundleResources","title":"Bundle Resources","abstract":[{"type":"text","text":"Resources located in an app, framework, or plugin bundle."}],"kind":"symbol","role":"collection","url":"/documentation/bundleresources","type":"topic"},"doc://com.apple.documentation/documentation/technologies":{"title":"Technologies","kind":"technologies","role":"overview","url":"/documentation/technologies","abstract":[{"type":"text","text":""}],"type":"topic","identifier":"doc://com.apple.documentation/documentation/technologies"},"doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/CFBundleHelpBookFolder":{"identifier":"doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/CFBundleHelpBookFolder","titleStyle":"symbol","abstract":[{"text":"The name of the folder containing the bundle’s help files.","type":"text"}],"navigatorTitle":[{"text":"CFBundleHelpBookFolder","kind":"identifier"}],"name":"CFBundleHelpBookFolder","role":"symbol","ideTitle":"Help Book directory name","title":"CFBundleHelpBookFolder","kind":"symbol","type":"topic","url":"/documentation/bundleresources/information-property-list/cfbundlehelpbookfolder"},"doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/CFAppleHelpAnchor":{"url":"/documentation/bundleresources/information-property-list/cfapplehelpanchor","titleStyle":"symbol","navigatorTitle":[{"text":"CFAppleHelpAnchor","kind":"identifier"}],"type":"topic","role":"symbol","abstract":[{"type":"text","text":"The name of the bundle’s HTML help file."}],"ideTitle":"Help file","name":"CFAppleHelpAnchor","identifier":"doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/CFAppleHelpAnchor","title":"CFAppleHelpAnchor","kind":"symbol"},"doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/CFBundleHelpBookName":{"url":"/documentation/bundleresources/information-property-list/cfbundlehelpbookname","type":"topic","name":"CFBundleHelpBookName","title":"CFBundleHelpBookName","ideTitle":"Help Book identifier","identifier":"doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/CFBundleHelpBookName","abstract":[{"type":"text","text":"The name of the help file that will be opened in Help Viewer."}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"CFBundleHelpBookName"}],"titleStyle":"symbol","kind":"symbol"},"doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List":{"identifier":"doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List","title":"Information Property List","abstract":[{"type":"text","text":"A resource containing key-value pairs that identify and configure a bundle."}],"kind":"symbol","role":"symbol","url":"/documentation/bundleresources/information-property-list","name":"Information Property List","navigatorTitle":[{"text":"Information Property List","kind":"identifier"}],"type":"topic","titleStyle":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"/identifier/interfaceLanguage","value":"occ"},{"op":"replace","path":"/metadata/platforms","value":[{"introducedAt":"10.0","deprecated":false,"beta":false,"unavailable":false,"name":"macOS"}]},{"op":"replace","path":"/metadata/roleHeading","value":"Property List Key"},{"op":"replace","path":"/metadata/title","value":"CFAppleHelpAnchor"},{"op":"replace","path":"/metadata/symbolKind","value":"typealias"},{"op":"replace","path":"/metadata/navigatorTitle","value":[{"kind":"identifier","text":"CFAppleHelpAnchor"}]},{"op":"replace","path":"/hierarchy","value":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.bundleresources/documentation/BundleResources","doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List"]]}},{"op":"add","path":"/topicSections","value":null},{"op":"add","path":"/relationshipsSections","value":null},{"op":"replace","path":"/seeAlsoSections","value":[{"identifiers":["doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/CFBundleHelpBookName","doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/CFBundleHelpBookFolder"],"anchor":"Help","generated":true,"title":"Help"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1CFBundleHelpBookFolder/title","value":"CFBundleHelpBookFolder"},{"op":"replace","path":"/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1CFBundleHelpBookFolder/navigatorTitle","value":[{"text":"CFBundleHelpBookFolder","kind":"identifier"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1CFAppleHelpAnchor/title","value":"CFAppleHelpAnchor"},{"op":"replace","path":"/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1CFAppleHelpAnchor/navigatorTitle","value":[{"kind":"identifier","text":"CFAppleHelpAnchor"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1CFBundleHelpBookName/title","value":"CFBundleHelpBookName"},{"op":"replace","path":"/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1CFBundleHelpBookName/navigatorTitle","value":[{"text":"CFBundleHelpBookName","kind":"identifier"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List/title","value":"Information Property List"},{"op":"replace","path":"/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List/navigatorTitle","value":[{"kind":"identifier","text":"Information Property List"}]}]}],"legalNotices":{"copyright":"Copyright &copy; 2025 Apple Inc. All rights reserved.","termsOfUse":"https://www.apple.com/legal/internet-services/terms/site.html","privacyPolicy":"https://www.apple.com/privacy/privacy-policy"}}