{
  "abstract": [
    {
      "text": "The name of the asset that represents the app icon.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.bundleresources/documentation/BundleResources",
        "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/CFBundleIconName"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "plist:Information_Property_List.CFBundleIconName",
    "modules": [
      {
        "name": "Bundle Resources"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "CFBundleIconName"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.13",
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Property List Key",
    "symbolKind": "typealias",
    "title": "CFBundleIconName"
  },
  "primaryContentSections": [
    {
      "details": {
        "ideTitle": "Icon Name",
        "name": "CFBundleIconName",
        "platforms": [],
        "titleStyle": "symbol",
        "value": [
          {
            "arrayMode": false,
            "baseType": "string"
          }
        ]
      },
      "kind": "details",
      "title": "Details"
    }
  ],
  "references": {
    "doc://com.apple.bundleresources/documentation/BundleResources": {
      "abstract": [
        {
          "text": "Resources located in an app, framework, or plugin bundle.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources",
      "kind": "symbol",
      "role": "collection",
      "title": "Bundle Resources",
      "type": "topic",
      "url": "/documentation/bundleresources"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List": {
      "abstract": [
        {
          "text": "A resource containing key-value pairs that identify and configure a bundle.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List",
      "kind": "symbol",
      "name": "Information Property List",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "Information Property List"
        }
      ],
      "role": "symbol",
      "title": "Information Property List",
      "titleStyle": "symbol",
      "type": "topic",
      "url": "/documentation/bundleresources/information-property-list"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/CFBundleIconFile": {
      "abstract": [
        {
          "text": "The file containing the bundle’s icon.",
          "type": "text"
        }
      ],
      "ideTitle": "Icon file",
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/CFBundleIconFile",
      "kind": "symbol",
      "name": "CFBundleIconFile",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CFBundleIconFile"
        }
      ],
      "role": "symbol",
      "title": "CFBundleIconFile",
      "titleStyle": "symbol",
      "type": "topic",
      "url": "/documentation/bundleresources/information-property-list/cfbundleiconfile"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/CFBundleIconFiles": {
      "abstract": [
        {
          "text": "The names of the bundle’s icon image files.",
          "type": "text"
        }
      ],
      "ideTitle": "Icon files",
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/CFBundleIconFiles",
      "kind": "symbol",
      "name": "CFBundleIconFiles",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CFBundleIconFiles"
        }
      ],
      "role": "symbol",
      "title": "CFBundleIconFiles",
      "titleStyle": "symbol",
      "type": "topic",
      "url": "/documentation/bundleresources/information-property-list/cfbundleiconfiles"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/CFBundleIconName": {
      "abstract": [
        {
          "text": "The name of the asset that represents the app icon.",
          "type": "text"
        }
      ],
      "ideTitle": "Icon Name",
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/CFBundleIconName",
      "kind": "symbol",
      "name": "CFBundleIconName",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CFBundleIconName"
        }
      ],
      "role": "symbol",
      "title": "CFBundleIconName",
      "titleStyle": "symbol",
      "type": "topic",
      "url": "/documentation/bundleresources/information-property-list/cfbundleiconname"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/CFBundleIcons": {
      "abstract": [
        {
          "text": "Information about all of the icons used by the app.",
          "type": "text"
        }
      ],
      "ideTitle": "Icon files (iOS 5)",
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/CFBundleIcons",
      "kind": "symbol",
      "name": "CFBundleIcons",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CFBundleIcons"
        }
      ],
      "role": "symbol",
      "title": "CFBundleIcons",
      "titleStyle": "symbol",
      "type": "topic",
      "url": "/documentation/bundleresources/information-property-list/cfbundleicons"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/UIPrerenderedIcon": {
      "abstract": [
        {
          "text": "A Boolean value that indicates whether the app’s icon contains a shine effect.",
          "type": "text"
        }
      ],
      "ideTitle": "Icon already includes gloss effects",
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/UIPrerenderedIcon",
      "kind": "symbol",
      "name": "UIPrerenderedIcon",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIPrerenderedIcon"
        }
      ],
      "role": "symbol",
      "title": "UIPrerenderedIcon",
      "titleStyle": "symbol",
      "type": "topic",
      "url": "/documentation/bundleresources/information-property-list/uiprerenderedicon"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Icons",
      "generated": true,
      "identifiers": [
        "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/CFBundleIcons",
        "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/CFBundleIconFiles",
        "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/CFBundleIconFile",
        "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/UIPrerenderedIcon"
      ],
      "title": "Icons"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.13",
              "name": "macOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Property List Key"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "CFBundleIconName"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "typealias"
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CFBundleIconName"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.bundleresources/documentation/BundleResources",
                "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Icons",
              "generated": true,
              "identifiers": [
                "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/CFBundleIcons",
                "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/CFBundleIconFiles",
                "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/CFBundleIconFile",
                "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/UIPrerenderedIcon"
              ],
              "title": "Icons"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1CFBundleIcons/title",
          "value": "CFBundleIcons"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1CFBundleIcons/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CFBundleIcons"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1CFBundleIconFile/title",
          "value": "CFBundleIconFile"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1CFBundleIconFile/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CFBundleIconFile"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List/title",
          "value": "Information Property List"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "Information Property List"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1CFBundleIconName/title",
          "value": "CFBundleIconName"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1CFBundleIconName/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CFBundleIconName"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1CFBundleIconFiles/title",
          "value": "CFBundleIconFiles"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1CFBundleIconFiles/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CFBundleIconFiles"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1UIPrerenderedIcon/title",
          "value": "UIPrerenderedIcon"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1UIPrerenderedIcon/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UIPrerenderedIcon"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/bundleresources/information-property-list/cfbundleiconname"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/bundleresources/information-property-list/cfbundleiconname"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
