{"sections":[],"schemaVersion":{"major":0,"minor":3,"patch":0},"seeAlsoSections":[{"title":"Help","generated":true,"identifiers":["doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/CFAppleHelpAnchor","doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/CFBundleHelpBookName"],"anchor":"Help"}],"abstract":[{"type":"text","text":"The name of the folder containing the bundle’s help files."}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["/documentation/bundleresources/information-property-list/cfbundlehelpbookfolder"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["/documentation/bundleresources/information-property-list/cfbundlehelpbookfolder"]}],"metadata":{"role":"symbol","navigatorTitle":[{"text":"CFBundleHelpBookFolder","kind":"identifier"}],"roleHeading":"Property List Key","title":"CFBundleHelpBookFolder","symbolKind":"typealias","externalID":"plist:Information_Property_List.CFBundleHelpBookFolder","modules":[{"name":"Bundle Resources"}],"platforms":[{"deprecated":false,"introducedAt":"10.0","beta":false,"name":"macOS","unavailable":false}]},"hierarchy":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.bundleresources/documentation/BundleResources","doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List"]]},"identifier":{"url":"doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/CFBundleHelpBookFolder","interfaceLanguage":"swift"},"kind":"symbol","primaryContentSections":[{"details":{"value":[{"arrayMode":false,"baseType":"string"}],"titleStyle":"symbol","ideTitle":"Help Book directory name","name":"CFBundleHelpBookFolder","platforms":[]},"title":"Details","kind":"details"}],"references":{"doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List":{"identifier":"doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List","title":"Information Property List","abstract":[{"type":"text","text":"A resource containing key-value pairs that identify and configure a bundle."}],"kind":"symbol","role":"symbol","url":"/documentation/bundleresources/information-property-list","name":"Information Property List","navigatorTitle":[{"text":"Information Property List","kind":"identifier"}],"type":"topic","titleStyle":"symbol"},"doc://com.apple.bundleresources/documentation/BundleResources":{"identifier":"doc://com.apple.bundleresources/documentation/BundleResources","title":"Bundle Resources","abstract":[{"type":"text","text":"Resources located in an app, framework, or plugin bundle."}],"kind":"symbol","role":"collection","url":"/documentation/bundleresources","type":"topic"},"doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/CFBundleHelpBookFolder":{"identifier":"doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/CFBundleHelpBookFolder","titleStyle":"symbol","abstract":[{"text":"The name of the folder containing the bundle’s help files.","type":"text"}],"navigatorTitle":[{"text":"CFBundleHelpBookFolder","kind":"identifier"}],"name":"CFBundleHelpBookFolder","role":"symbol","ideTitle":"Help Book directory name","title":"CFBundleHelpBookFolder","kind":"symbol","type":"topic","url":"/documentation/bundleresources/information-property-list/cfbundlehelpbookfolder"},"doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/CFBundleHelpBookName":{"url":"/documentation/bundleresources/information-property-list/cfbundlehelpbookname","type":"topic","name":"CFBundleHelpBookName","title":"CFBundleHelpBookName","ideTitle":"Help Book identifier","identifier":"doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/CFBundleHelpBookName","abstract":[{"type":"text","text":"The name of the help file that will be opened in Help Viewer."}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"CFBundleHelpBookName"}],"titleStyle":"symbol","kind":"symbol"},"doc://com.apple.documentation/documentation/technologies":{"title":"Technologies","kind":"technologies","role":"overview","url":"/documentation/technologies","abstract":[{"type":"text","text":""}],"type":"topic","identifier":"doc://com.apple.documentation/documentation/technologies"},"doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/CFAppleHelpAnchor":{"url":"/documentation/bundleresources/information-property-list/cfapplehelpanchor","titleStyle":"symbol","navigatorTitle":[{"text":"CFAppleHelpAnchor","kind":"identifier"}],"type":"topic","role":"symbol","abstract":[{"type":"text","text":"The name of the bundle’s HTML help file."}],"ideTitle":"Help file","name":"CFAppleHelpAnchor","identifier":"doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/CFAppleHelpAnchor","title":"CFAppleHelpAnchor","kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"/identifier/interfaceLanguage"},{"path":"/metadata/platforms","value":[{"beta":false,"introducedAt":"10.0","name":"macOS","deprecated":false,"unavailable":false}],"op":"replace"},{"path":"/metadata/roleHeading","value":"Property List Key","op":"replace"},{"path":"/metadata/title","value":"CFBundleHelpBookFolder","op":"replace"},{"path":"/metadata/symbolKind","value":"typealias","op":"replace"},{"path":"/metadata/navigatorTitle","value":[{"kind":"identifier","text":"CFBundleHelpBookFolder"}],"op":"replace"},{"path":"/hierarchy","value":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.bundleresources/documentation/BundleResources","doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List"]]},"op":"replace"},{"path":"/topicSections","value":null,"op":"add"},{"op":"add","path":"/relationshipsSections","value":null},{"op":"replace","path":"/seeAlsoSections","value":[{"identifiers":["doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/CFAppleHelpAnchor","doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/CFBundleHelpBookName"],"title":"Help","generated":true,"anchor":"Help"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List/title","value":"Information Property List"},{"op":"replace","path":"/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List/navigatorTitle","value":[{"kind":"identifier","text":"Information Property List"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1CFBundleHelpBookFolder/title","value":"CFBundleHelpBookFolder"},{"op":"replace","path":"/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1CFBundleHelpBookFolder/navigatorTitle","value":[{"text":"CFBundleHelpBookFolder","kind":"identifier"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1CFBundleHelpBookName/title","value":"CFBundleHelpBookName"},{"op":"replace","path":"/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1CFBundleHelpBookName/navigatorTitle","value":[{"kind":"identifier","text":"CFBundleHelpBookName"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1CFAppleHelpAnchor/title","value":"CFAppleHelpAnchor"},{"op":"replace","path":"/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1CFAppleHelpAnchor/navigatorTitle","value":[{"text":"CFAppleHelpAnchor","kind":"identifier"}]}]}],"legalNotices":{"copyright":"Copyright &copy; 2025 Apple Inc. All rights reserved.","termsOfUse":"https://www.apple.com/legal/internet-services/terms/site.html","privacyPolicy":"https://www.apple.com/privacy/privacy-policy"}}