{
  "abstract": [
    {
      "text": "One or more groups of interfaces supported by the plug-in for static registration.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.bundleresources/documentation/BundleResources",
        "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/CFPlugInTypes"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "plist:Information_Property_List.CFPlugInTypes",
    "modules": [
      {
        "name": "Bundle Resources"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "CFPlugInTypes"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.0",
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Property List Key",
    "symbolKind": "dictionary",
    "title": "CFPlugInTypes"
  },
  "primaryContentSections": [
    {
      "details": {
        "ideTitle": "Plug-in types",
        "name": "CFPlugInTypes",
        "platforms": [],
        "titleStyle": "symbol",
        "value": [
          {
            "arrayMode": false,
            "baseType": "object"
          }
        ]
      },
      "kind": "details",
      "title": "Details"
    }
  ],
  "references": {
    "doc://com.apple.bundleresources/documentation/BundleResources": {
      "abstract": [
        {
          "text": "Resources located in an app, framework, or plugin bundle.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources",
      "kind": "symbol",
      "role": "collection",
      "title": "Bundle Resources",
      "type": "topic",
      "url": "/documentation/bundleresources"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List": {
      "abstract": [
        {
          "text": "A resource containing key-value pairs that identify and configure a bundle.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List",
      "kind": "symbol",
      "name": "Information Property List",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "Information Property List"
        }
      ],
      "role": "symbol",
      "title": "Information Property List",
      "titleStyle": "symbol",
      "type": "topic",
      "url": "/documentation/bundleresources/information-property-list"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/CFPlugInDynamicRegisterFunction": {
      "abstract": [
        {
          "text": "The function to use when dynamically registering a plug-in.",
          "type": "text"
        }
      ],
      "ideTitle": "Plug-in dynamic registration function name",
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/CFPlugInDynamicRegisterFunction",
      "kind": "symbol",
      "name": "CFPlugInDynamicRegisterFunction",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CFPlugInDynamicRegisterFunction"
        }
      ],
      "role": "symbol",
      "title": "CFPlugInDynamicRegisterFunction",
      "titleStyle": "symbol",
      "type": "topic",
      "url": "/documentation/bundleresources/information-property-list/cfplugindynamicregisterfunction"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/CFPlugInDynamicRegistration": {
      "abstract": [
        {
          "text": "A Boolean value indicating whether the host loads this plug-in.",
          "type": "text"
        }
      ],
      "ideTitle": "Plug-in should be registered dynamically",
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/CFPlugInDynamicRegistration",
      "kind": "symbol",
      "name": "CFPlugInDynamicRegistration",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CFPlugInDynamicRegistration"
        }
      ],
      "role": "symbol",
      "title": "CFPlugInDynamicRegistration",
      "titleStyle": "symbol",
      "type": "topic",
      "url": "/documentation/bundleresources/information-property-list/cfplugindynamicregistration"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/CFPlugInFactories": {
      "abstract": [
        {
          "text": "The interfaces supported by the plug-in for static registration.",
          "type": "text"
        }
      ],
      "ideTitle": "Plug-in factory interfaces",
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/CFPlugInFactories",
      "kind": "symbol",
      "name": "CFPlugInFactories",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CFPlugInFactories"
        }
      ],
      "role": "symbol",
      "title": "CFPlugInFactories",
      "titleStyle": "symbol",
      "type": "topic",
      "url": "/documentation/bundleresources/information-property-list/cfpluginfactories"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/CFPlugInTypes": {
      "abstract": [
        {
          "text": "One or more groups of interfaces supported by the plug-in for static registration.",
          "type": "text"
        }
      ],
      "ideTitle": "Plug-in types",
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/CFPlugInTypes",
      "kind": "symbol",
      "name": "CFPlugInTypes",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CFPlugInTypes"
        }
      ],
      "role": "symbol",
      "title": "CFPlugInTypes",
      "titleStyle": "symbol",
      "type": "topic",
      "url": "/documentation/bundleresources/information-property-list/cfplugintypes"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/CFPlugInUnloadFunction": {
      "abstract": [
        {
          "text": "The name of the function to call to unload the plug-in code from memory.",
          "type": "text"
        }
      ],
      "ideTitle": "Plug-in unload function name",
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/CFPlugInUnloadFunction",
      "kind": "symbol",
      "name": "CFPlugInUnloadFunction",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CFPlugInUnloadFunction"
        }
      ],
      "role": "symbol",
      "title": "CFPlugInUnloadFunction",
      "titleStyle": "symbol",
      "type": "topic",
      "url": "/documentation/bundleresources/information-property-list/cfpluginunloadfunction"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Plug-in-configuration",
      "generated": true,
      "identifiers": [
        "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/CFPlugInDynamicRegisterFunction",
        "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/CFPlugInDynamicRegistration",
        "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/CFPlugInFactories",
        "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/CFPlugInUnloadFunction"
      ],
      "title": "Plug-in configuration"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.0",
              "name": "macOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Property List Key"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "CFPlugInTypes"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "dictionary"
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CFPlugInTypes"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.bundleresources/documentation/BundleResources",
                "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Plug-in-configuration",
              "generated": true,
              "identifiers": [
                "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/CFPlugInDynamicRegisterFunction",
                "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/CFPlugInDynamicRegistration",
                "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/CFPlugInFactories",
                "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/CFPlugInUnloadFunction"
              ],
              "title": "Plug-in configuration"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1CFPlugInDynamicRegisterFunction/title",
          "value": "CFPlugInDynamicRegisterFunction"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1CFPlugInDynamicRegisterFunction/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CFPlugInDynamicRegisterFunction"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1CFPlugInUnloadFunction/title",
          "value": "CFPlugInUnloadFunction"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1CFPlugInUnloadFunction/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CFPlugInUnloadFunction"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1CFPlugInFactories/title",
          "value": "CFPlugInFactories"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1CFPlugInFactories/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CFPlugInFactories"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1CFPlugInDynamicRegistration/title",
          "value": "CFPlugInDynamicRegistration"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1CFPlugInDynamicRegistration/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CFPlugInDynamicRegistration"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1CFPlugInTypes/title",
          "value": "CFPlugInTypes"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1CFPlugInTypes/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CFPlugInTypes"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List/title",
          "value": "Information Property List"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "Information Property List"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/bundleresources/information-property-list/cfplugintypes"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/bundleresources/information-property-list/cfplugintypes"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
