{
  "abstract": [
    {
      "text": "A dictionary that contains details about actions available to users for Spotlight search results.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.bundleresources/documentation/BundleResources",
        "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/CoreSpotlightActions"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "plist:Information_Property_List.CoreSpotlightActions",
    "modules": [
      {
        "name": "Bundle Resources"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "CoreSpotlightActions"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "15.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "15.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Property List Key",
    "symbolKind": "dictionary",
    "title": "CoreSpotlightActions"
  },
  "primaryContentSections": [
    {
      "details": {
        "name": "CoreSpotlightActions",
        "platforms": [],
        "titleStyle": "symbol",
        "value": [
          {
            "arrayMode": true,
            "baseType": "dictionary "
          }
        ]
      },
      "kind": "details",
      "title": "Details"
    }
  ],
  "references": {
    "doc://com.apple.bundleresources/documentation/BundleResources": {
      "abstract": [
        {
          "text": "Resources located in an app, framework, or plugin bundle.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources",
      "kind": "symbol",
      "role": "collection",
      "title": "Bundle Resources",
      "type": "topic",
      "url": "/documentation/bundleresources"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List": {
      "abstract": [
        {
          "text": "A resource containing key-value pairs that identify and configure a bundle.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List",
      "kind": "symbol",
      "name": "Information Property List",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "Information Property List"
        }
      ],
      "role": "symbol",
      "title": "Information Property List",
      "titleStyle": "symbol",
      "type": "topic",
      "url": "/documentation/bundleresources/information-property-list"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/CoreSpotlightActions": {
      "abstract": [
        {
          "text": "A dictionary that contains details about actions available to users for Spotlight search results.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/CoreSpotlightActions",
      "kind": "symbol",
      "name": "CoreSpotlightActions",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CoreSpotlightActions"
        }
      ],
      "role": "symbol",
      "title": "CoreSpotlightActions",
      "titleStyle": "symbol",
      "type": "topic",
      "url": "/documentation/bundleresources/information-property-list/corespotlightactions"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/CoreSpotlightActions/CoreSpotlightActionIdentifier": {
      "abstract": [
        {
          "text": "A string an app defines to identify the action.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/CoreSpotlightActions/CoreSpotlightActionIdentifier",
      "kind": "symbol",
      "name": "CoreSpotlightActionIdentifier",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CoreSpotlightActionIdentifier"
        }
      ],
      "role": "symbol",
      "title": "CoreSpotlightActionIdentifier",
      "titleStyle": "symbol",
      "type": "topic",
      "url": "/documentation/bundleresources/information-property-list/corespotlightactions/corespotlightactionidentifier"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/CoreSpotlightActions/CoreSpotlightActionSymbolImage": {
      "abstract": [
        {
          "text": "The name of a SF Symbol to display next to the action’s title.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/CoreSpotlightActions/CoreSpotlightActionSymbolImage",
      "kind": "symbol",
      "name": "CoreSpotlightActionSymbolImage",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CoreSpotlightActionSymbolImage"
        }
      ],
      "role": "symbol",
      "title": "CoreSpotlightActionSymbolImage",
      "titleStyle": "symbol",
      "type": "topic",
      "url": "/documentation/bundleresources/information-property-list/corespotlightactions/corespotlightactionsymbolimage"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/CoreSpotlightActions/CoreSpotlightActionTitle": {
      "abstract": [
        {
          "text": "The user-visible string that Spotlight displays as the title of the action.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/CoreSpotlightActions/CoreSpotlightActionTitle",
      "kind": "symbol",
      "name": "CoreSpotlightActionTitle",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CoreSpotlightActionTitle"
        }
      ],
      "role": "symbol",
      "title": "CoreSpotlightActionTitle",
      "titleStyle": "symbol",
      "type": "topic",
      "url": "/documentation/bundleresources/information-property-list/corespotlightactions/corespotlightactiontitle"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "topicSections": [
    {
      "anchor": "Action-Properties",
      "identifiers": [
        "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/CoreSpotlightActions/CoreSpotlightActionTitle",
        "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/CoreSpotlightActions/CoreSpotlightActionSymbolImage",
        "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/CoreSpotlightActions/CoreSpotlightActionIdentifier"
      ],
      "title": "Action Properties"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "15.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "15.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Property List Key"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "CoreSpotlightActions"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "dictionary"
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CoreSpotlightActions"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.bundleresources/documentation/BundleResources",
                "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Action-Properties",
              "identifiers": [
                "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/CoreSpotlightActions/CoreSpotlightActionTitle",
                "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/CoreSpotlightActions/CoreSpotlightActionSymbolImage",
                "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/CoreSpotlightActions/CoreSpotlightActionIdentifier"
              ],
              "title": "Action Properties"
            }
          ]
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/seeAlsoSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1CoreSpotlightActions~1CoreSpotlightActionTitle/title",
          "value": "CoreSpotlightActionTitle"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1CoreSpotlightActions~1CoreSpotlightActionTitle/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CoreSpotlightActionTitle"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1CoreSpotlightActions/title",
          "value": "CoreSpotlightActions"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1CoreSpotlightActions/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CoreSpotlightActions"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List/title",
          "value": "Information Property List"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "Information Property List"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1CoreSpotlightActions~1CoreSpotlightActionIdentifier/title",
          "value": "CoreSpotlightActionIdentifier"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1CoreSpotlightActions~1CoreSpotlightActionIdentifier/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CoreSpotlightActionIdentifier"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1CoreSpotlightActions~1CoreSpotlightActionSymbolImage/title",
          "value": "CoreSpotlightActionSymbolImage"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1CoreSpotlightActions~1CoreSpotlightActionSymbolImage/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CoreSpotlightActionSymbolImage"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/bundleresources/information-property-list/corespotlightactions"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/bundleresources/information-property-list/corespotlightactions"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
