{
  "abstract": [
    {
      "text": "The types of game controller profiles that the app supports or requires.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.bundleresources/documentation/BundleResources",
        "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/GCSupportedGameControllers"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "plist:Information_Property_List.GCSupportedGameControllers",
    "modules": [
      {
        "name": "Bundle Resources"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "GCSupportedGameControllers"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "7.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "7.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.9",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "9.0",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Property List Key",
    "symbolKind": "dictionary",
    "title": "GCSupportedGameControllers"
  },
  "primaryContentSections": [
    {
      "details": {
        "ideTitle": "Supported game controller types",
        "name": "GCSupportedGameControllers",
        "platforms": [],
        "titleStyle": "symbol",
        "value": [
          {
            "arrayMode": true,
            "baseType": "dictionary "
          }
        ]
      },
      "kind": "details",
      "title": "Details"
    },
    {
      "items": [
        {
          "attributes": [
            {
              "kind": "allowedValues",
              "values": [
                "DirectionalGamepad",
                "ExtendedGamepad",
                "MicroGamepad"
              ]
            }
          ],
          "content": [],
          "introducedVersion": "7.0.0",
          "name": "ProfileName",
          "required": false,
          "type": [
            {
              "kind": "text",
              "text": "string"
            }
          ]
        }
      ],
      "kind": "properties",
      "title": "Properties"
    },
    {
      "content": [
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "The dictionary keys are ",
              "type": "text"
            },
            {
              "code": "ProfileName",
              "type": "codeVoice"
            },
            {
              "text": " and the possible game controller values are:",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "items": [
            {
              "definition": {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "The extended set of gamepad controls. See ",
                        "type": "text"
                      },
                      {
                        "identifier": "doc://com.apple.documentation/documentation/GameController/GCExtendedGamepad",
                        "isActive": true,
                        "type": "reference"
                      },
                      {
                        "text": ".",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ]
              },
              "term": {
                "inlineContent": [
                  {
                    "code": "ExtendedGamepad",
                    "type": "codeVoice"
                  }
                ]
              }
            },
            {
              "definition": {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "The 1st Generation Siri Remote. See ",
                        "type": "text"
                      },
                      {
                        "identifier": "doc://com.apple.documentation/documentation/GameController/GCMicroGamepad",
                        "isActive": true,
                        "type": "reference"
                      },
                      {
                        "text": ".",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ]
              },
              "term": {
                "inlineContent": [
                  {
                    "code": "MicroGamepad",
                    "type": "codeVoice"
                  }
                ]
              }
            },
            {
              "definition": {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "The 2nd Generation Siri Remote. A directional pad without motion or rotation. See ",
                        "type": "text"
                      },
                      {
                        "identifier": "doc://com.apple.documentation/documentation/GameController/GCDirectionalGamepad",
                        "isActive": true,
                        "type": "reference"
                      },
                      {
                        "text": ". Available in iOS 14.3+, macOS 11.1+, Mac Catalyst 14.3+, and tvOS 14.3+.",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ]
              },
              "term": {
                "inlineContent": [
                  {
                    "code": "DirectionalGamepad",
                    "type": "codeVoice"
                  }
                ]
              }
            }
          ],
          "type": "termList"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.bundleresources/documentation/BundleResources": {
      "abstract": [
        {
          "text": "Resources located in an app, framework, or plugin bundle.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources",
      "kind": "symbol",
      "role": "collection",
      "title": "Bundle Resources",
      "type": "topic",
      "url": "/documentation/bundleresources"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List": {
      "abstract": [
        {
          "text": "A resource containing key-value pairs that identify and configure a bundle.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List",
      "kind": "symbol",
      "name": "Information Property List",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "Information Property List"
        }
      ],
      "role": "symbol",
      "title": "Information Property List",
      "titleStyle": "symbol",
      "type": "topic",
      "url": "/documentation/bundleresources/information-property-list"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/AVGameBypassSystemSpatialAudio": {
      "abstract": [
        {
          "text": "A key that ignores the system spatial-audio toggle in Control Center.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/AVGameBypassSystemSpatialAudio",
      "kind": "symbol",
      "name": "AVGameBypassSystemSpatialAudio",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVGameBypassSystemSpatialAudio"
        }
      ],
      "role": "symbol",
      "title": "AVGameBypassSystemSpatialAudio",
      "titleStyle": "symbol",
      "type": "topic",
      "url": "/documentation/bundleresources/information-property-list/avgamebypasssystemspatialaudio"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/GCRequiresControllerUserInteraction": {
      "abstract": [
        {
          "text": "The platforms for which your app requires or you recommend a game controller.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/GCRequiresControllerUserInteraction",
      "kind": "symbol",
      "name": "GCRequiresControllerUserInteraction",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GCRequiresControllerUserInteraction"
        }
      ],
      "role": "symbol",
      "title": "GCRequiresControllerUserInteraction",
      "titleStyle": "symbol",
      "type": "topic",
      "url": "/documentation/bundleresources/information-property-list/gcrequirescontrolleruserinteraction"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/GCSupportedGameControllers": {
      "abstract": [
        {
          "text": "The types of game controller profiles that the app supports or requires.",
          "type": "text"
        }
      ],
      "ideTitle": "Supported game controller types",
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/GCSupportedGameControllers",
      "kind": "symbol",
      "name": "GCSupportedGameControllers",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GCSupportedGameControllers"
        }
      ],
      "role": "symbol",
      "title": "GCSupportedGameControllers",
      "titleStyle": "symbol",
      "type": "topic",
      "url": "/documentation/bundleresources/information-property-list/gcsupportedgamecontrollers"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/GCSupportsControllerUserInteraction": {
      "abstract": [
        {
          "text": "A Boolean value indicating whether the app supports a game controller.",
          "type": "text"
        }
      ],
      "ideTitle": "Supports Controller User Interaction",
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/GCSupportsControllerUserInteraction",
      "kind": "symbol",
      "name": "GCSupportsControllerUserInteraction",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GCSupportsControllerUserInteraction"
        }
      ],
      "role": "symbol",
      "title": "GCSupportsControllerUserInteraction",
      "titleStyle": "symbol",
      "type": "topic",
      "url": "/documentation/bundleresources/information-property-list/gcsupportscontrolleruserinteraction"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/GCSupportsMultipleMicroGamepads": {
      "abstract": [
        {
          "text": "A Boolean value indicating whether the physical Apple TV Remote and the Apple TV Remote app operate as separate game controllers.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/GCSupportsMultipleMicroGamepads",
      "kind": "symbol",
      "name": "GCSupportsMultipleMicroGamepads",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GCSupportsMultipleMicroGamepads"
        }
      ],
      "role": "symbol",
      "title": "GCSupportsMultipleMicroGamepads",
      "titleStyle": "symbol",
      "type": "topic",
      "url": "/documentation/bundleresources/information-property-list/gcsupportsmultiplemicrogamepads"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/GKGameCenterBadgingDisabled": {
      "abstract": [
        {
          "text": "A Boolean value indicating whether GameKit can add badges to a turn-based game icon.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/GKGameCenterBadgingDisabled",
      "kind": "symbol",
      "name": "GKGameCenterBadgingDisabled",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GKGameCenterBadgingDisabled"
        }
      ],
      "role": "symbol",
      "title": "GKGameCenterBadgingDisabled",
      "titleStyle": "symbol",
      "type": "topic",
      "url": "/documentation/bundleresources/information-property-list/gkgamecenterbadgingdisabled"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/GKShowChallengeBanners": {
      "abstract": [
        {
          "text": "A Boolean value that indicates whether GameKit can display challenge banners in a game.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/GKShowChallengeBanners",
      "kind": "symbol",
      "name": "GKShowChallengeBanners",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GKShowChallengeBanners"
        }
      ],
      "role": "symbol",
      "title": "GKShowChallengeBanners",
      "titleStyle": "symbol",
      "type": "topic",
      "url": "/documentation/bundleresources/information-property-list/gkshowchallengebanners"
    },
    "doc://com.apple.documentation/documentation/GameController/GCDirectionalGamepad": {
      "abstract": [
        {
          "text": "A profile that supports only the directional pad, without motion or rotation.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "GCDirectionalGamepad"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/GameController/GCDirectionalGamepad",
      "kind": "symbol",
      "role": "symbol",
      "title": "GCDirectionalGamepad",
      "type": "topic",
      "url": "/documentation/GameController/GCDirectionalGamepad"
    },
    "doc://com.apple.documentation/documentation/GameController/GCExtendedGamepad": {
      "abstract": [
        {
          "text": "A controller profile that supports the extended set of gamepad controls.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "GCExtendedGamepad"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/GameController/GCExtendedGamepad",
      "kind": "symbol",
      "role": "symbol",
      "title": "GCExtendedGamepad",
      "type": "topic",
      "url": "/documentation/GameController/GCExtendedGamepad"
    },
    "doc://com.apple.documentation/documentation/GameController/GCMicroGamepad": {
      "abstract": [
        {
          "text": "A controller profile that supports the Siri Remote.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "GCMicroGamepad"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/GameController/GCMicroGamepad",
      "kind": "symbol",
      "role": "symbol",
      "title": "GCMicroGamepad",
      "type": "topic",
      "url": "/documentation/GameController/GCMicroGamepad"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Games",
      "generated": true,
      "identifiers": [
        "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/AVGameBypassSystemSpatialAudio",
        "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/GKGameCenterBadgingDisabled",
        "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/GKShowChallengeBanners",
        "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/GCSupportsControllerUserInteraction",
        "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/GCRequiresControllerUserInteraction",
        "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/GCSupportsMultipleMicroGamepads"
      ],
      "title": "Games"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "7.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "7.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.9",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "9.0",
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Property List Key"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "GCSupportedGameControllers"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "dictionary"
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "GCSupportedGameControllers"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.bundleresources/documentation/BundleResources",
                "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Games",
              "generated": true,
              "identifiers": [
                "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/AVGameBypassSystemSpatialAudio",
                "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/GKGameCenterBadgingDisabled",
                "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/GKShowChallengeBanners",
                "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/GCSupportsControllerUserInteraction",
                "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/GCRequiresControllerUserInteraction",
                "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/GCSupportsMultipleMicroGamepads"
              ],
              "title": "Games"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/3",
          "value": {
            "items": [
              {
                "attributes": [
                  {
                    "kind": "allowedValues",
                    "values": [
                      "DirectionalGamepad",
                      "ExtendedGamepad",
                      "MicroGamepad"
                    ]
                  }
                ],
                "content": [],
                "introducedVersion": "7.0.0",
                "name": "ProfileName",
                "required": false,
                "type": [
                  {
                    "kind": "text",
                    "text": "string"
                  }
                ]
              }
            ],
            "kind": "properties",
            "title": "Properties"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1GCRequiresControllerUserInteraction/title",
          "value": "GCRequiresControllerUserInteraction"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1GCRequiresControllerUserInteraction/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "GCRequiresControllerUserInteraction"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1GKGameCenterBadgingDisabled/title",
          "value": "GKGameCenterBadgingDisabled"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1GKGameCenterBadgingDisabled/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "GKGameCenterBadgingDisabled"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1GCSupportedGameControllers/title",
          "value": "GCSupportedGameControllers"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1GCSupportedGameControllers/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "GCSupportedGameControllers"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1GCSupportsControllerUserInteraction/title",
          "value": "GCSupportsControllerUserInteraction"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1GCSupportsControllerUserInteraction/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "GCSupportsControllerUserInteraction"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List/title",
          "value": "Information Property List"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "Information Property List"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1GameController~1GCMicroGamepad/fragments",
          "value": [
            {
              "kind": "keyword",
              "text": "@interface"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "GCMicroGamepad"
            },
            {
              "kind": "text",
              "text": " : "
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)GCPhysicalInputProfile",
              "text": "GCPhysicalInputProfile"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1GCSupportsMultipleMicroGamepads/title",
          "value": "GCSupportsMultipleMicroGamepads"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1GCSupportsMultipleMicroGamepads/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "GCSupportsMultipleMicroGamepads"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1AVGameBypassSystemSpatialAudio/title",
          "value": "AVGameBypassSystemSpatialAudio"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1AVGameBypassSystemSpatialAudio/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AVGameBypassSystemSpatialAudio"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1GameController~1GCExtendedGamepad/fragments",
          "value": [
            {
              "kind": "keyword",
              "text": "@interface"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "GCExtendedGamepad"
            },
            {
              "kind": "text",
              "text": " : "
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)GCPhysicalInputProfile",
              "text": "GCPhysicalInputProfile"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1GameController~1GCDirectionalGamepad/fragments",
          "value": [
            {
              "kind": "keyword",
              "text": "@interface"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "GCDirectionalGamepad"
            },
            {
              "kind": "text",
              "text": " : "
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)GCMicroGamepad",
              "text": "GCMicroGamepad"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1GKShowChallengeBanners/title",
          "value": "GKShowChallengeBanners"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1GKShowChallengeBanners/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "GKShowChallengeBanners"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/bundleresources/information-property-list/gcsupportedgamecontrollers"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/bundleresources/information-property-list/gcsupportedgamecontrollers"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
