{
  "abstract": [
    {
      "text": "A Boolean value indicating whether the app supports a game controller.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.bundleresources/documentation/BundleResources",
        "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/GCSupportsControllerUserInteraction"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "plist:Information_Property_List.GCSupportsControllerUserInteraction",
    "modules": [
      {
        "name": "Bundle Resources"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "GCSupportsControllerUserInteraction"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "2.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "2.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.0",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "9.0",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Property List Key",
    "symbolKind": "typealias",
    "title": "GCSupportsControllerUserInteraction"
  },
  "primaryContentSections": [
    {
      "details": {
        "ideTitle": "Supports Controller User Interaction",
        "name": "GCSupportsControllerUserInteraction",
        "platforms": [],
        "titleStyle": "symbol",
        "value": [
          {
            "arrayMode": false,
            "baseType": "boolean"
          }
        ]
      },
      "kind": "details",
      "title": "Details"
    },
    {
      "content": [
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "To add this key to the information property list, enable the Game Controllers capability in Xcode. If you set this key to ",
              "type": "text"
            },
            {
              "code": "YES",
              "type": "codeVoice"
            },
            {
              "text": " and check ExtendedGamepad under the Game Controllers capability in your project, App Store adds a game controller support badge to your app. Then users can customize their game controller mappings in Settings and Preferences.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "",
                  "type": "text"
                },
                {
                  "text": " ",
                  "type": "text"
                },
                {
                  "text": "To recommend the use of a game controller on iOS or if your app requires a game controller on visionOS, add an entry into the ",
                  "type": "text"
                },
                {
                  "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/GCRequiresControllerUserInteraction",
                  "isActive": true,
                  "type": "reference"
                },
                {
                  "text": " dictionary for that platform and set the value to ",
                  "type": "text"
                },
                {
                  "code": "YES",
                  "type": "codeVoice"
                },
                {
                  "text": ".",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "Important",
          "style": "important",
          "type": "aside"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.bundleresources/documentation/BundleResources": {
      "abstract": [
        {
          "text": "Resources located in an app, framework, or plugin bundle.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources",
      "kind": "symbol",
      "role": "collection",
      "title": "Bundle Resources",
      "type": "topic",
      "url": "/documentation/bundleresources"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List": {
      "abstract": [
        {
          "text": "A resource containing key-value pairs that identify and configure a bundle.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List",
      "kind": "symbol",
      "name": "Information Property List",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "Information Property List"
        }
      ],
      "role": "symbol",
      "title": "Information Property List",
      "titleStyle": "symbol",
      "type": "topic",
      "url": "/documentation/bundleresources/information-property-list"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/AVGameBypassSystemSpatialAudio": {
      "abstract": [
        {
          "text": "A key that ignores the system spatial-audio toggle in Control Center.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/AVGameBypassSystemSpatialAudio",
      "kind": "symbol",
      "name": "AVGameBypassSystemSpatialAudio",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVGameBypassSystemSpatialAudio"
        }
      ],
      "role": "symbol",
      "title": "AVGameBypassSystemSpatialAudio",
      "titleStyle": "symbol",
      "type": "topic",
      "url": "/documentation/bundleresources/information-property-list/avgamebypasssystemspatialaudio"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/GCRequiresControllerUserInteraction": {
      "abstract": [
        {
          "text": "The platforms for which your app requires or you recommend a game controller.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/GCRequiresControllerUserInteraction",
      "kind": "symbol",
      "name": "GCRequiresControllerUserInteraction",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GCRequiresControllerUserInteraction"
        }
      ],
      "role": "symbol",
      "title": "GCRequiresControllerUserInteraction",
      "titleStyle": "symbol",
      "type": "topic",
      "url": "/documentation/bundleresources/information-property-list/gcrequirescontrolleruserinteraction"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/GCSupportedGameControllers": {
      "abstract": [
        {
          "text": "The types of game controller profiles that the app supports or requires.",
          "type": "text"
        }
      ],
      "ideTitle": "Supported game controller types",
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/GCSupportedGameControllers",
      "kind": "symbol",
      "name": "GCSupportedGameControllers",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GCSupportedGameControllers"
        }
      ],
      "role": "symbol",
      "title": "GCSupportedGameControllers",
      "titleStyle": "symbol",
      "type": "topic",
      "url": "/documentation/bundleresources/information-property-list/gcsupportedgamecontrollers"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/GCSupportsControllerUserInteraction": {
      "abstract": [
        {
          "text": "A Boolean value indicating whether the app supports a game controller.",
          "type": "text"
        }
      ],
      "ideTitle": "Supports Controller User Interaction",
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/GCSupportsControllerUserInteraction",
      "kind": "symbol",
      "name": "GCSupportsControllerUserInteraction",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GCSupportsControllerUserInteraction"
        }
      ],
      "role": "symbol",
      "title": "GCSupportsControllerUserInteraction",
      "titleStyle": "symbol",
      "type": "topic",
      "url": "/documentation/bundleresources/information-property-list/gcsupportscontrolleruserinteraction"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/GCSupportsMultipleMicroGamepads": {
      "abstract": [
        {
          "text": "A Boolean value indicating whether the physical Apple TV Remote and the Apple TV Remote app operate as separate game controllers.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/GCSupportsMultipleMicroGamepads",
      "kind": "symbol",
      "name": "GCSupportsMultipleMicroGamepads",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GCSupportsMultipleMicroGamepads"
        }
      ],
      "role": "symbol",
      "title": "GCSupportsMultipleMicroGamepads",
      "titleStyle": "symbol",
      "type": "topic",
      "url": "/documentation/bundleresources/information-property-list/gcsupportsmultiplemicrogamepads"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/GKGameCenterBadgingDisabled": {
      "abstract": [
        {
          "text": "A Boolean value indicating whether GameKit can add badges to a turn-based game icon.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/GKGameCenterBadgingDisabled",
      "kind": "symbol",
      "name": "GKGameCenterBadgingDisabled",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GKGameCenterBadgingDisabled"
        }
      ],
      "role": "symbol",
      "title": "GKGameCenterBadgingDisabled",
      "titleStyle": "symbol",
      "type": "topic",
      "url": "/documentation/bundleresources/information-property-list/gkgamecenterbadgingdisabled"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/GKShowChallengeBanners": {
      "abstract": [
        {
          "text": "A Boolean value that indicates whether GameKit can display challenge banners in a game.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/GKShowChallengeBanners",
      "kind": "symbol",
      "name": "GKShowChallengeBanners",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GKShowChallengeBanners"
        }
      ],
      "role": "symbol",
      "title": "GKShowChallengeBanners",
      "titleStyle": "symbol",
      "type": "topic",
      "url": "/documentation/bundleresources/information-property-list/gkshowchallengebanners"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Games",
      "generated": true,
      "identifiers": [
        "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/AVGameBypassSystemSpatialAudio",
        "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/GKGameCenterBadgingDisabled",
        "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/GKShowChallengeBanners",
        "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/GCSupportedGameControllers",
        "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/GCRequiresControllerUserInteraction",
        "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/GCSupportsMultipleMicroGamepads"
      ],
      "title": "Games"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "2.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "2.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.0",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "9.0",
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Property List Key"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "GCSupportsControllerUserInteraction"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "typealias"
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "GCSupportsControllerUserInteraction"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.bundleresources/documentation/BundleResources",
                "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Games",
              "generated": true,
              "identifiers": [
                "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/AVGameBypassSystemSpatialAudio",
                "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/GKGameCenterBadgingDisabled",
                "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/GKShowChallengeBanners",
                "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/GCSupportedGameControllers",
                "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/GCRequiresControllerUserInteraction",
                "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/GCSupportsMultipleMicroGamepads"
              ],
              "title": "Games"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1GCSupportsMultipleMicroGamepads/title",
          "value": "GCSupportsMultipleMicroGamepads"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1GCSupportsMultipleMicroGamepads/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "GCSupportsMultipleMicroGamepads"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List/title",
          "value": "Information Property List"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "Information Property List"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1GKGameCenterBadgingDisabled/title",
          "value": "GKGameCenterBadgingDisabled"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1GKGameCenterBadgingDisabled/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "GKGameCenterBadgingDisabled"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1GCSupportsControllerUserInteraction/title",
          "value": "GCSupportsControllerUserInteraction"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1GCSupportsControllerUserInteraction/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "GCSupportsControllerUserInteraction"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1AVGameBypassSystemSpatialAudio/title",
          "value": "AVGameBypassSystemSpatialAudio"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1AVGameBypassSystemSpatialAudio/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AVGameBypassSystemSpatialAudio"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1GCSupportedGameControllers/title",
          "value": "GCSupportedGameControllers"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1GCSupportedGameControllers/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "GCSupportedGameControllers"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1GKShowChallengeBanners/title",
          "value": "GKShowChallengeBanners"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1GKShowChallengeBanners/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "GKShowChallengeBanners"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1GCRequiresControllerUserInteraction/title",
          "value": "GCRequiresControllerUserInteraction"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1GCRequiresControllerUserInteraction/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "GCRequiresControllerUserInteraction"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/bundleresources/information-property-list/gcsupportscontrolleruserinteraction"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/bundleresources/information-property-list/gcsupportscontrolleruserinteraction"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
