{
  "abstract": [
    {
      "text": "One or more groups of attributes that tell the system about the devices your driver supports.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.bundleresources/documentation/BundleResources",
        "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/IOKitPersonalities"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "plist:Information_Property_List.IOKitPersonalities",
    "modules": [
      {
        "name": "Bundle Resources"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "IOKitPersonalities"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.0",
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Property List Key",
    "symbolKind": "dictionary",
    "title": "IOKitPersonalities"
  },
  "primaryContentSections": [
    {
      "details": {
        "name": "IOKitPersonalities",
        "platforms": [],
        "titleStyle": "symbol",
        "value": [
          {
            "arrayMode": false,
            "baseType": "object"
          }
        ]
      },
      "kind": "details",
      "title": "Details"
    },
    {
      "content": [
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "This key contains a dictionary of driver ",
              "type": "text"
            },
            {
              "inlineContent": [
                {
                  "text": "personalities",
                  "type": "text"
                }
              ],
              "type": "emphasis"
            },
            {
              "text": ", each of which specifies how to pair the driver to a device. Each key in the dictionary is a string you designate as the name of a specific personality, and the system doesn’t use your key names internally. The value of each key is a dictionary of attributes that describe the specific device to match with the driver. Thus, each key and dictionary combination represents a single personality of the driver. The system uses these personalities to match the driver to an attached device.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "During the matching process, the system compares the attributes in each personality dictionary to data it obtained from the attached device. For example, if the personality dictionary includes the ",
              "type": "text"
            },
            {
              "code": "VendorID",
              "type": "codeVoice"
            },
            {
              "text": " key, the system compares that key to the vendor information from the device. The system picks the driver that is compatible with the device and provides the best overall match. It then uses additional information from the personality dictionary to load and run the driver.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "All personality dictionaries must include the following keys:",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "items": [
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/CFBundleIdentifier",
                      "isActive": true,
                      "type": "reference"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/IOProviderClass",
                      "isActive": true,
                      "type": "reference"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/IOClass",
                      "isActive": true,
                      "type": "reference"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            }
          ],
          "type": "unorderedList"
        },
        {
          "inlineContent": [
            {
              "text": "Include any of the following keys in your personality dictionary to customize the match criteria:",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "items": [
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/IOPropertyMatch",
                      "isActive": true,
                      "type": "reference"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/IONameMatch",
                      "isActive": true,
                      "type": "reference"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/IOResourceMatch",
                      "isActive": true,
                      "type": "reference"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "code": "IOParentMatch",
                      "type": "codeVoice"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "code": "IOPathMatch",
                      "type": "codeVoice"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "code": "IOMatchCategory",
                      "type": "codeVoice"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Device-specific keys, such as ",
                      "type": "text"
                    },
                    {
                      "code": "DeviceUsagePairs",
                      "type": "codeVoice"
                    },
                    {
                      "text": ", ",
                      "type": "text"
                    },
                    {
                      "code": "VendorID",
                      "type": "codeVoice"
                    },
                    {
                      "text": ", or ",
                      "type": "text"
                    },
                    {
                      "code": "ProductID",
                      "type": "codeVoice"
                    },
                    {
                      "text": ". See a specific ",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.documentation/documentation/driverkit/ioservice",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": " subclass for information about the keys it supports.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            }
          ],
          "type": "unorderedList"
        },
        {
          "inlineContent": [
            {
              "text": "Include one of more of the following keys to specify how to load your driver’s code:",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "items": [
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/IOUserClass",
                      "isActive": true,
                      "type": "reference"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/IOUserServerName",
                      "isActive": true,
                      "type": "reference"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/IOUserClientClass",
                      "isActive": true,
                      "type": "reference"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            }
          ],
          "type": "unorderedList"
        },
        {
          "inlineContent": [
            {
              "text": "Use the following keys to further customize your driver’s behavior:",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "items": [
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "code": "IOMatchDefer",
                      "type": "codeVoice"
                    },
                    {
                      "text": ". Set the value of this key to ",
                      "type": "text"
                    },
                    {
                      "code": "true",
                      "type": "codeVoice"
                    },
                    {
                      "text": " to defer the matching process until after ",
                      "type": "text"
                    },
                    {
                      "code": "kextd",
                      "type": "codeVoice"
                    },
                    {
                      "text": " starts.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "code": "IOUserServerOneProcess",
                      "type": "codeVoice"
                    },
                    {
                      "text": ". Set the value of this key to ",
                      "type": "text"
                    },
                    {
                      "code": "true",
                      "type": "codeVoice"
                    },
                    {
                      "text": " to run your DriverKit services in one process. If the key is missing or its value is ",
                      "type": "text"
                    },
                    {
                      "code": "false",
                      "type": "codeVoice"
                    },
                    {
                      "text": ", the system creates a separate process for each service.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            }
          ],
          "type": "unorderedList"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.bundleresources/documentation/BundleResources": {
      "abstract": [
        {
          "text": "Resources located in an app, framework, or plugin bundle.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources",
      "kind": "symbol",
      "role": "collection",
      "title": "Bundle Resources",
      "type": "topic",
      "url": "/documentation/bundleresources"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List": {
      "abstract": [
        {
          "text": "A resource containing key-value pairs that identify and configure a bundle.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List",
      "kind": "symbol",
      "name": "Information Property List",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "Information Property List"
        }
      ],
      "role": "symbol",
      "title": "Information Property List",
      "titleStyle": "symbol",
      "type": "topic",
      "url": "/documentation/bundleresources/information-property-list"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/CFBundleIdentifier": {
      "abstract": [
        {
          "text": "A unique identifier for a bundle.",
          "type": "text"
        }
      ],
      "ideTitle": "Bundle identifier",
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/CFBundleIdentifier",
      "kind": "symbol",
      "name": "CFBundleIdentifier",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CFBundleIdentifier"
        }
      ],
      "role": "symbol",
      "title": "CFBundleIdentifier",
      "titleStyle": "symbol",
      "type": "topic",
      "url": "/documentation/bundleresources/information-property-list/cfbundleidentifier"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/IOClass": {
      "abstract": [
        {
          "text": "The name of the class to instantiate from your driver.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/IOClass",
      "kind": "symbol",
      "name": "IOClass",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "IOClass"
        }
      ],
      "role": "symbol",
      "title": "IOClass",
      "titleStyle": "symbol",
      "type": "topic",
      "url": "/documentation/bundleresources/information-property-list/ioclass"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/IOKitPersonalities": {
      "abstract": [
        {
          "text": "One or more groups of attributes that tell the system about the devices your driver supports.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/IOKitPersonalities",
      "kind": "symbol",
      "name": "IOKitPersonalities",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "IOKitPersonalities"
        }
      ],
      "role": "symbol",
      "title": "IOKitPersonalities",
      "titleStyle": "symbol",
      "type": "topic",
      "url": "/documentation/bundleresources/information-property-list/iokitpersonalities"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/IOMatchCategory": {
      "abstract": [],
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/IOMatchCategory",
      "kind": "symbol",
      "name": "IOMatchCategory",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "IOMatchCategory"
        }
      ],
      "role": "symbol",
      "title": "IOMatchCategory",
      "titleStyle": "symbol",
      "type": "topic",
      "url": "/documentation/bundleresources/information-property-list/iomatchcategory"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/IONameMatch": {
      "abstract": [
        {
          "text": "One or more strings that contain the names of possible provider objects in the system registry.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/IONameMatch",
      "kind": "symbol",
      "name": "IONameMatch",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "IONameMatch"
        }
      ],
      "role": "symbol",
      "title": "IONameMatch",
      "titleStyle": "symbol",
      "type": "topic",
      "url": "/documentation/bundleresources/information-property-list/ionamematch"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/IOParentMatch": {
      "abstract": [],
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/IOParentMatch",
      "kind": "symbol",
      "name": "IOParentMatch",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "IOParentMatch"
        }
      ],
      "role": "symbol",
      "title": "IOParentMatch",
      "titleStyle": "symbol",
      "type": "topic",
      "url": "/documentation/bundleresources/information-property-list/ioparentmatch"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/IOPathMatch": {
      "abstract": [],
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/IOPathMatch",
      "kind": "symbol",
      "name": "IOPathMatch",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "IOPathMatch"
        }
      ],
      "role": "symbol",
      "title": "IOPathMatch",
      "titleStyle": "symbol",
      "type": "topic",
      "url": "/documentation/bundleresources/information-property-list/iopathmatch"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/IOPropertyMatch": {
      "abstract": [
        {
          "text": "The device-specific keys the system must match in order to use your driver.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/IOPropertyMatch",
      "kind": "symbol",
      "name": "IOPropertyMatch",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "IOPropertyMatch"
        }
      ],
      "role": "symbol",
      "title": "IOPropertyMatch",
      "titleStyle": "symbol",
      "type": "topic",
      "url": "/documentation/bundleresources/information-property-list/iopropertymatch"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/IOProviderClass": {
      "abstract": [
        {
          "text": "The name of the class that your driver expects to provide the implementation for its provider object.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/IOProviderClass",
      "kind": "symbol",
      "name": "IOProviderClass",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "IOProviderClass"
        }
      ],
      "role": "symbol",
      "title": "IOProviderClass",
      "titleStyle": "symbol",
      "type": "topic",
      "url": "/documentation/bundleresources/information-property-list/ioproviderclass"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/IOResourceMatch": {
      "abstract": [
        {
          "text": "One or more system-specific or device-specific resources that your driver requires.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/IOResourceMatch",
      "kind": "symbol",
      "name": "IOResourceMatch",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "IOResourceMatch"
        }
      ],
      "role": "symbol",
      "title": "IOResourceMatch",
      "titleStyle": "symbol",
      "type": "topic",
      "url": "/documentation/bundleresources/information-property-list/ioresourcematch"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/IOUserClass": {
      "abstract": [
        {
          "text": "The name of your driver’s main class, which is the entry point for interacting with your driver’s code.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/IOUserClass",
      "kind": "symbol",
      "name": "IOUserClass",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "IOUserClass"
        }
      ],
      "role": "symbol",
      "title": "IOUserClass",
      "titleStyle": "symbol",
      "type": "topic",
      "url": "/documentation/bundleresources/information-property-list/iouserclass"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/IOUserClientClass": {
      "abstract": [
        {
          "text": "The name of the class to instantiate when the system requires a client connection to the driver.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/IOUserClientClass",
      "kind": "symbol",
      "name": "IOUserClientClass",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "IOUserClientClass"
        }
      ],
      "role": "symbol",
      "title": "IOUserClientClass",
      "titleStyle": "symbol",
      "type": "topic",
      "url": "/documentation/bundleresources/information-property-list/iouserclientclass"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/IOUserServerName": {
      "abstract": [
        {
          "text": "The name that the system uses to facilitate communication between your driver and other clients.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/IOUserServerName",
      "kind": "symbol",
      "name": "IOUserServerName",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "IOUserServerName"
        }
      ],
      "role": "symbol",
      "title": "IOUserServerName",
      "titleStyle": "symbol",
      "type": "topic",
      "url": "/documentation/bundleresources/information-property-list/iouserservername"
    },
    "doc://com.apple.documentation/documentation/driverkit/ioservice": {
      "abstract": [
        {
          "text": "The base class for managing the setup and registration of your driver.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/driverkit/ioservice",
      "kind": "symbol",
      "role": "symbol",
      "title": "IOService",
      "type": "topic",
      "url": "/documentation/driverkit/ioservice"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "topicSections": [
    {
      "anchor": "Driver-Classes",
      "identifiers": [
        "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/IOUserClass",
        "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/IOProviderClass",
        "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/IOClass",
        "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/IOUserClientClass",
        "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/IOUserServerName"
      ],
      "title": "Driver Classes"
    },
    {
      "anchor": "Advanced-Match-Criteria",
      "identifiers": [
        "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/IOPropertyMatch",
        "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/IONameMatch",
        "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/IOResourceMatch",
        "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/IOParentMatch",
        "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/IOPathMatch",
        "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/IOMatchCategory"
      ],
      "title": "Advanced Match Criteria"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.0",
              "name": "macOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Property List Key"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "IOKitPersonalities"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "dictionary"
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "IOKitPersonalities"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.bundleresources/documentation/BundleResources",
                "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Driver-Classes",
              "identifiers": [
                "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/IOUserClass",
                "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/IOProviderClass",
                "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/IOClass",
                "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/IOUserClientClass",
                "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/IOUserServerName"
              ],
              "title": "Driver Classes"
            },
            {
              "anchor": "Advanced-Match-Criteria",
              "identifiers": [
                "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/IOPropertyMatch",
                "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/IONameMatch",
                "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/IOResourceMatch",
                "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/IOParentMatch",
                "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/IOPathMatch",
                "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/IOMatchCategory"
              ],
              "title": "Advanced Match Criteria"
            }
          ]
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/seeAlsoSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1IOProviderClass/title",
          "value": "IOProviderClass"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1IOProviderClass/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "IOProviderClass"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1IOParentMatch/title",
          "value": "IOParentMatch"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1IOParentMatch/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "IOParentMatch"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1IOPathMatch/title",
          "value": "IOPathMatch"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1IOPathMatch/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "IOPathMatch"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1IONameMatch/title",
          "value": "IONameMatch"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1IONameMatch/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "IONameMatch"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List/title",
          "value": "Information Property List"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "Information Property List"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1IOKitPersonalities/title",
          "value": "IOKitPersonalities"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1IOKitPersonalities/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "IOKitPersonalities"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1IOMatchCategory/title",
          "value": "IOMatchCategory"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1IOMatchCategory/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "IOMatchCategory"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1CFBundleIdentifier/title",
          "value": "CFBundleIdentifier"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1CFBundleIdentifier/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CFBundleIdentifier"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1IOUserServerName/title",
          "value": "IOUserServerName"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1IOUserServerName/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "IOUserServerName"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1IOPropertyMatch/title",
          "value": "IOPropertyMatch"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1IOPropertyMatch/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "IOPropertyMatch"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1IOClass/title",
          "value": "IOClass"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1IOClass/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "IOClass"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1IOResourceMatch/title",
          "value": "IOResourceMatch"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1IOResourceMatch/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "IOResourceMatch"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1IOUserClass/title",
          "value": "IOUserClass"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1IOUserClass/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "IOUserClass"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1IOUserClientClass/title",
          "value": "IOUserClientClass"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1IOUserClientClass/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "IOUserClientClass"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/bundleresources/information-property-list/iokitpersonalities"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/bundleresources/information-property-list/iokitpersonalities"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
