{
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.bundleresources/documentation/BundleResources",
        "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/IOPathMatch"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "plist:Information_Property_List.IOPathMatch",
    "modules": [
      {
        "name": "Bundle Resources"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "IOPathMatch"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.0",
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Property List Key",
    "symbolKind": "typealias",
    "title": "IOPathMatch"
  },
  "primaryContentSections": [
    {
      "details": {
        "name": "IOPathMatch",
        "platforms": [],
        "titleStyle": "symbol",
        "value": [
          {
            "arrayMode": false,
            "baseType": "string"
          }
        ]
      },
      "kind": "details",
      "title": "Details"
    }
  ],
  "references": {
    "doc://com.apple.bundleresources/documentation/BundleResources": {
      "abstract": [
        {
          "text": "Resources located in an app, framework, or plugin bundle.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources",
      "kind": "symbol",
      "role": "collection",
      "title": "Bundle Resources",
      "type": "topic",
      "url": "/documentation/bundleresources"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List": {
      "abstract": [
        {
          "text": "A resource containing key-value pairs that identify and configure a bundle.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List",
      "kind": "symbol",
      "name": "Information Property List",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "Information Property List"
        }
      ],
      "role": "symbol",
      "title": "Information Property List",
      "titleStyle": "symbol",
      "type": "topic",
      "url": "/documentation/bundleresources/information-property-list"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/IOMatchCategory": {
      "abstract": [],
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/IOMatchCategory",
      "kind": "symbol",
      "name": "IOMatchCategory",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "IOMatchCategory"
        }
      ],
      "role": "symbol",
      "title": "IOMatchCategory",
      "titleStyle": "symbol",
      "type": "topic",
      "url": "/documentation/bundleresources/information-property-list/iomatchcategory"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/IONameMatch": {
      "abstract": [
        {
          "text": "One or more strings that contain the names of possible provider objects in the system registry.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/IONameMatch",
      "kind": "symbol",
      "name": "IONameMatch",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "IONameMatch"
        }
      ],
      "role": "symbol",
      "title": "IONameMatch",
      "titleStyle": "symbol",
      "type": "topic",
      "url": "/documentation/bundleresources/information-property-list/ionamematch"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/IOParentMatch": {
      "abstract": [],
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/IOParentMatch",
      "kind": "symbol",
      "name": "IOParentMatch",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "IOParentMatch"
        }
      ],
      "role": "symbol",
      "title": "IOParentMatch",
      "titleStyle": "symbol",
      "type": "topic",
      "url": "/documentation/bundleresources/information-property-list/ioparentmatch"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/IOPathMatch": {
      "abstract": [],
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/IOPathMatch",
      "kind": "symbol",
      "name": "IOPathMatch",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "IOPathMatch"
        }
      ],
      "role": "symbol",
      "title": "IOPathMatch",
      "titleStyle": "symbol",
      "type": "topic",
      "url": "/documentation/bundleresources/information-property-list/iopathmatch"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/IOPropertyMatch": {
      "abstract": [
        {
          "text": "The device-specific keys the system must match in order to use your driver.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/IOPropertyMatch",
      "kind": "symbol",
      "name": "IOPropertyMatch",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "IOPropertyMatch"
        }
      ],
      "role": "symbol",
      "title": "IOPropertyMatch",
      "titleStyle": "symbol",
      "type": "topic",
      "url": "/documentation/bundleresources/information-property-list/iopropertymatch"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/IOResourceMatch": {
      "abstract": [
        {
          "text": "One or more system-specific or device-specific resources that your driver requires.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/IOResourceMatch",
      "kind": "symbol",
      "name": "IOResourceMatch",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "IOResourceMatch"
        }
      ],
      "role": "symbol",
      "title": "IOResourceMatch",
      "titleStyle": "symbol",
      "type": "topic",
      "url": "/documentation/bundleresources/information-property-list/ioresourcematch"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Advanced-Match-Criteria",
      "generated": true,
      "identifiers": [
        "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/IOPropertyMatch",
        "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/IONameMatch",
        "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/IOResourceMatch",
        "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/IOParentMatch",
        "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/IOMatchCategory"
      ],
      "title": "Advanced Match Criteria"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.0",
              "name": "macOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Property List Key"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "IOPathMatch"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "typealias"
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "IOPathMatch"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.bundleresources/documentation/BundleResources",
                "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Advanced-Match-Criteria",
              "generated": true,
              "identifiers": [
                "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/IOPropertyMatch",
                "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/IONameMatch",
                "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/IOResourceMatch",
                "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/IOParentMatch",
                "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/IOMatchCategory"
              ],
              "title": "Advanced Match Criteria"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1IONameMatch/title",
          "value": "IONameMatch"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1IONameMatch/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "IONameMatch"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1IOPathMatch/title",
          "value": "IOPathMatch"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1IOPathMatch/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "IOPathMatch"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1IOPropertyMatch/title",
          "value": "IOPropertyMatch"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1IOPropertyMatch/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "IOPropertyMatch"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1IOResourceMatch/title",
          "value": "IOResourceMatch"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1IOResourceMatch/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "IOResourceMatch"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List/title",
          "value": "Information Property List"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "Information Property List"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1IOMatchCategory/title",
          "value": "IOMatchCategory"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1IOMatchCategory/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "IOMatchCategory"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1IOParentMatch/title",
          "value": "IOParentMatch"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1IOParentMatch/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "IOParentMatch"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/bundleresources/information-property-list/iopathmatch"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/bundleresources/information-property-list/iopathmatch"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
