{
  "abstract": [
    {
      "text": "The name of your driver’s main class, which is the entry point for interacting with your driver’s code.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.bundleresources/documentation/BundleResources",
        "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/IOUserClass"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "plist:Information_Property_List.IOUserClass",
    "modules": [
      {
        "name": "Bundle Resources"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "IOUserClass"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.14",
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Property List Key",
    "symbolKind": "typealias",
    "title": "IOUserClass"
  },
  "primaryContentSections": [
    {
      "details": {
        "name": "IOUserClass",
        "platforms": [],
        "titleStyle": "symbol",
        "value": [
          {
            "arrayMode": false,
            "baseType": "string"
          }
        ]
      },
      "kind": "details",
      "title": "Details"
    },
    {
      "content": [
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Include this key only in the personality dictionary of a DriverKit extension, and use it to specify the name of the custom ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/driverkit/ioservice",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " subclass that provides your driver’s behavior. When it’s time to load your driver, the system instantiates the specified class and begins the initialization and startup processes.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.bundleresources/documentation/BundleResources": {
      "abstract": [
        {
          "text": "Resources located in an app, framework, or plugin bundle.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources",
      "kind": "symbol",
      "role": "collection",
      "title": "Bundle Resources",
      "type": "topic",
      "url": "/documentation/bundleresources"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List": {
      "abstract": [
        {
          "text": "A resource containing key-value pairs that identify and configure a bundle.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List",
      "kind": "symbol",
      "name": "Information Property List",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "Information Property List"
        }
      ],
      "role": "symbol",
      "title": "Information Property List",
      "titleStyle": "symbol",
      "type": "topic",
      "url": "/documentation/bundleresources/information-property-list"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/IOClass": {
      "abstract": [
        {
          "text": "The name of the class to instantiate from your driver.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/IOClass",
      "kind": "symbol",
      "name": "IOClass",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "IOClass"
        }
      ],
      "role": "symbol",
      "title": "IOClass",
      "titleStyle": "symbol",
      "type": "topic",
      "url": "/documentation/bundleresources/information-property-list/ioclass"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/IOProviderClass": {
      "abstract": [
        {
          "text": "The name of the class that your driver expects to provide the implementation for its provider object.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/IOProviderClass",
      "kind": "symbol",
      "name": "IOProviderClass",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "IOProviderClass"
        }
      ],
      "role": "symbol",
      "title": "IOProviderClass",
      "titleStyle": "symbol",
      "type": "topic",
      "url": "/documentation/bundleresources/information-property-list/ioproviderclass"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/IOUserClass": {
      "abstract": [
        {
          "text": "The name of your driver’s main class, which is the entry point for interacting with your driver’s code.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/IOUserClass",
      "kind": "symbol",
      "name": "IOUserClass",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "IOUserClass"
        }
      ],
      "role": "symbol",
      "title": "IOUserClass",
      "titleStyle": "symbol",
      "type": "topic",
      "url": "/documentation/bundleresources/information-property-list/iouserclass"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/IOUserClientClass": {
      "abstract": [
        {
          "text": "The name of the class to instantiate when the system requires a client connection to the driver.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/IOUserClientClass",
      "kind": "symbol",
      "name": "IOUserClientClass",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "IOUserClientClass"
        }
      ],
      "role": "symbol",
      "title": "IOUserClientClass",
      "titleStyle": "symbol",
      "type": "topic",
      "url": "/documentation/bundleresources/information-property-list/iouserclientclass"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/IOUserServerName": {
      "abstract": [
        {
          "text": "The name that the system uses to facilitate communication between your driver and other clients.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/IOUserServerName",
      "kind": "symbol",
      "name": "IOUserServerName",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "IOUserServerName"
        }
      ],
      "role": "symbol",
      "title": "IOUserServerName",
      "titleStyle": "symbol",
      "type": "topic",
      "url": "/documentation/bundleresources/information-property-list/iouserservername"
    },
    "doc://com.apple.documentation/documentation/driverkit/ioservice": {
      "abstract": [
        {
          "text": "The base class for managing the setup and registration of your driver.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/driverkit/ioservice",
      "kind": "symbol",
      "role": "symbol",
      "title": "IOService",
      "type": "topic",
      "url": "/documentation/driverkit/ioservice"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Driver-Classes",
      "generated": true,
      "identifiers": [
        "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/IOProviderClass",
        "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/IOClass",
        "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/IOUserClientClass",
        "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/IOUserServerName"
      ],
      "title": "Driver Classes"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.14",
              "name": "macOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Property List Key"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "IOUserClass"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "typealias"
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "IOUserClass"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.bundleresources/documentation/BundleResources",
                "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Driver-Classes",
              "generated": true,
              "identifiers": [
                "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/IOProviderClass",
                "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/IOClass",
                "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/IOUserClientClass",
                "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/IOUserServerName"
              ],
              "title": "Driver Classes"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1IOProviderClass/title",
          "value": "IOProviderClass"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1IOProviderClass/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "IOProviderClass"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1IOUserServerName/title",
          "value": "IOUserServerName"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1IOUserServerName/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "IOUserServerName"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1IOUserClass/title",
          "value": "IOUserClass"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1IOUserClass/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "IOUserClass"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1IOUserClientClass/title",
          "value": "IOUserClientClass"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1IOUserClientClass/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "IOUserClientClass"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List/title",
          "value": "Information Property List"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "Information Property List"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1IOClass/title",
          "value": "IOClass"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1IOClass/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "IOClass"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/bundleresources/information-property-list/iouserclass"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/bundleresources/information-property-list/iouserclass"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
