{
  "abstract": [
    {
      "text": "A Boolean value indicating whether the app uses encryption.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.bundleresources/documentation/BundleResources",
        "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/ITSAppUsesNonExemptEncryption"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "plist:Information_Property_List.ITSAppUsesNonExemptEncryption",
    "modules": [
      {
        "name": "Bundle Resources"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "ITSAppUsesNonExemptEncryption"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.0",
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Property List Key",
    "symbolKind": "typealias",
    "title": "ITSAppUsesNonExemptEncryption"
  },
  "primaryContentSections": [
    {
      "details": {
        "ideTitle": "App Uses Non-Exempt Encryption",
        "name": "ITSAppUsesNonExemptEncryption",
        "platforms": [],
        "titleStyle": "symbol",
        "value": [
          {
            "arrayMode": false,
            "baseType": "boolean"
          }
        ]
      },
      "kind": "details",
      "title": "Details"
    },
    {
      "content": [
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Set the value for this key to ",
              "type": "text"
            },
            {
              "code": "NO",
              "type": "codeVoice"
            },
            {
              "text": " in your app’s ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " file to indicate that your app—including any third-party libraries you link against—either uses no encryption, or only uses encryption that’s exempt from export compliance requirements, as described in ",
              "type": "text"
            },
            {
              "identifier": "https://help.apple.com/app-store-connect/#/dev63c95e436",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ". Set the value to ",
              "type": "text"
            },
            {
              "code": "YES",
              "type": "codeVoice"
            },
            {
              "text": " to indicate that your app uses non-exempt encryption.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "If you set the value to ",
              "type": "text"
            },
            {
              "code": "YES",
              "type": "codeVoice"
            },
            {
              "text": ", you typically also provide a value for the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/ITSEncryptionExportComplianceCode",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " key. You set that key’s value using a code Apple provides after successfully reviewing your export compliance documentation.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "If you don’t have the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/ITSAppUsesNonExemptEncryption",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " key in your app’s ",
              "type": "text"
            },
            {
              "code": "Info.plist",
              "type": "codeVoice"
            },
            {
              "text": " file, App Store Connect walks you through an export compliance questionnaire every time you upload a new version of your app. Including the key streamlines the app submission process.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "For additional information, see ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/Security/complying-with-encryption-export-regulations",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ".",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.bundleresources/documentation/BundleResources": {
      "abstract": [
        {
          "text": "Resources located in an app, framework, or plugin bundle.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources",
      "kind": "symbol",
      "role": "collection",
      "title": "Bundle Resources",
      "type": "topic",
      "url": "/documentation/bundleresources"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List": {
      "abstract": [
        {
          "text": "A resource containing key-value pairs that identify and configure a bundle.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List",
      "kind": "symbol",
      "name": "Information Property List",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "Information Property List"
        }
      ],
      "role": "symbol",
      "title": "Information Property List",
      "titleStyle": "symbol",
      "type": "topic",
      "url": "/documentation/bundleresources/information-property-list"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/ITSAppUsesNonExemptEncryption": {
      "abstract": [
        {
          "text": "A Boolean value indicating whether the app uses encryption.",
          "type": "text"
        }
      ],
      "ideTitle": "App Uses Non-Exempt Encryption",
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/ITSAppUsesNonExemptEncryption",
      "kind": "symbol",
      "name": "ITSAppUsesNonExemptEncryption",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ITSAppUsesNonExemptEncryption"
        }
      ],
      "role": "symbol",
      "title": "ITSAppUsesNonExemptEncryption",
      "titleStyle": "symbol",
      "type": "topic",
      "url": "/documentation/bundleresources/information-property-list/itsappusesnonexemptencryption"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/ITSEncryptionExportComplianceCode": {
      "abstract": [
        {
          "text": "The export compliance code provided by App Store Connect for apps that require it.",
          "type": "text"
        }
      ],
      "ideTitle": "App Encryption Export Compliance Code",
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/ITSEncryptionExportComplianceCode",
      "kind": "symbol",
      "name": "ITSEncryptionExportComplianceCode",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ITSEncryptionExportComplianceCode"
        }
      ],
      "role": "symbol",
      "title": "ITSEncryptionExportComplianceCode",
      "titleStyle": "symbol",
      "type": "topic",
      "url": "/documentation/bundleresources/information-property-list/itsencryptionexportcompliancecode"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSAppDataUsageDescription": {
      "abstract": [
        {
          "text": "A message that tells the user why the app needs to access files in other apps’ sandbox containers.",
          "type": "text"
        }
      ],
      "ideTitle": "Privacy - Other Application Data Usage Description",
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSAppDataUsageDescription",
      "kind": "symbol",
      "name": "NSAppDataUsageDescription",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSAppDataUsageDescription"
        }
      ],
      "role": "symbol",
      "title": "NSAppDataUsageDescription",
      "titleStyle": "symbol",
      "type": "topic",
      "url": "/documentation/bundleresources/information-property-list/nsappdatausagedescription"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSAppleEventsUsageDescription": {
      "abstract": [
        {
          "text": "A message that tells the user why the app is requesting the ability to send Apple events.",
          "type": "text"
        }
      ],
      "ideTitle": "Privacy - AppleEvents Sending Usage Description",
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSAppleEventsUsageDescription",
      "kind": "symbol",
      "name": "NSAppleEventsUsageDescription",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSAppleEventsUsageDescription"
        }
      ],
      "role": "symbol",
      "title": "NSAppleEventsUsageDescription",
      "titleStyle": "symbol",
      "type": "topic",
      "url": "/documentation/bundleresources/information-property-list/nsappleeventsusagedescription"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSSystemAdministrationUsageDescription": {
      "abstract": [
        {
          "text": "A message in macOS that tells the user why the app is requesting to manipulate the system configuration.",
          "type": "text"
        }
      ],
      "ideTitle": "Privacy - System Administration Usage Description",
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSSystemAdministrationUsageDescription",
      "kind": "symbol",
      "name": "NSSystemAdministrationUsageDescription",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSSystemAdministrationUsageDescription"
        }
      ],
      "role": "symbol",
      "title": "NSSystemAdministrationUsageDescription",
      "titleStyle": "symbol",
      "type": "topic",
      "url": "/documentation/bundleresources/information-property-list/nssystemadministrationusagedescription"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSUpdateSecurityPolicy": {
      "abstract": [
        {
          "text": "A dictionary that identifies which apps or installer packages the operating system allows to write to the app’s bundle.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSUpdateSecurityPolicy",
      "kind": "symbol",
      "name": "NSUpdateSecurityPolicy",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSUpdateSecurityPolicy"
        }
      ],
      "role": "symbol",
      "title": "NSUpdateSecurityPolicy",
      "titleStyle": "symbol",
      "type": "topic",
      "url": "/documentation/bundleresources/information-property-list/nsupdatesecuritypolicy"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSUserTrackingUsageDescription": {
      "abstract": [
        {
          "text": "A message that informs the user why an app is requesting permission to use data for tracking the user or the device.",
          "type": "text"
        }
      ],
      "ideTitle": "Privacy - Tracking Usage Description",
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSUserTrackingUsageDescription",
      "kind": "symbol",
      "name": "NSUserTrackingUsageDescription",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSUserTrackingUsageDescription"
        }
      ],
      "role": "symbol",
      "title": "NSUserTrackingUsageDescription",
      "titleStyle": "symbol",
      "type": "topic",
      "url": "/documentation/bundleresources/information-property-list/nsusertrackingusagedescription"
    },
    "doc://com.apple.documentation/documentation/Security/complying-with-encryption-export-regulations": {
      "abstract": [
        {
          "text": "Declare the use of encryption in your app to streamline the app submission process.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/Security/complying-with-encryption-export-regulations",
      "kind": "article",
      "role": "article",
      "title": "Complying with Encryption Export Regulations",
      "type": "topic",
      "url": "/documentation/Security/complying-with-encryption-export-regulations"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "https://help.apple.com/app-store-connect/#/dev63c95e436": {
      "identifier": "https://help.apple.com/app-store-connect/#/dev63c95e436",
      "title": "Determine your export compliance requirements",
      "titleInlineContent": [
        {
          "text": "Determine your export compliance requirements",
          "type": "text"
        }
      ],
      "type": "link",
      "url": "https://help.apple.com/app-store-connect/#/dev63c95e436"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Security",
      "generated": true,
      "identifiers": [
        "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSUpdateSecurityPolicy",
        "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSAppDataUsageDescription",
        "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSUserTrackingUsageDescription",
        "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSAppleEventsUsageDescription",
        "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSSystemAdministrationUsageDescription",
        "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/ITSEncryptionExportComplianceCode"
      ],
      "title": "Security"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.0",
              "name": "macOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Property List Key"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "ITSAppUsesNonExemptEncryption"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "typealias"
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "ITSAppUsesNonExemptEncryption"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.bundleresources/documentation/BundleResources",
                "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Security",
              "generated": true,
              "identifiers": [
                "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSUpdateSecurityPolicy",
                "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSAppDataUsageDescription",
                "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSUserTrackingUsageDescription",
                "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSAppleEventsUsageDescription",
                "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSSystemAdministrationUsageDescription",
                "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/ITSEncryptionExportComplianceCode"
              ],
              "title": "Security"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1NSAppleEventsUsageDescription/title",
          "value": "NSAppleEventsUsageDescription"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1NSAppleEventsUsageDescription/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSAppleEventsUsageDescription"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List/title",
          "value": "Information Property List"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "Information Property List"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1ITSAppUsesNonExemptEncryption/title",
          "value": "ITSAppUsesNonExemptEncryption"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1ITSAppUsesNonExemptEncryption/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "ITSAppUsesNonExemptEncryption"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1ITSEncryptionExportComplianceCode/title",
          "value": "ITSEncryptionExportComplianceCode"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1ITSEncryptionExportComplianceCode/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "ITSEncryptionExportComplianceCode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1NSUserTrackingUsageDescription/title",
          "value": "NSUserTrackingUsageDescription"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1NSUserTrackingUsageDescription/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSUserTrackingUsageDescription"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1NSAppDataUsageDescription/title",
          "value": "NSAppDataUsageDescription"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1NSAppDataUsageDescription/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSAppDataUsageDescription"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1NSSystemAdministrationUsageDescription/title",
          "value": "NSSystemAdministrationUsageDescription"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1NSSystemAdministrationUsageDescription/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSSystemAdministrationUsageDescription"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1NSUpdateSecurityPolicy/title",
          "value": "NSUpdateSecurityPolicy"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1NSUpdateSecurityPolicy/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSUpdateSecurityPolicy"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/bundleresources/information-property-list/itsappusesnonexemptencryption"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/bundleresources/information-property-list/itsappusesnonexemptencryption"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
