{
  "abstract": [
    {
      "text": "The category that best describes your app for the App Store.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.bundleresources/documentation/BundleResources",
        "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/LSApplicationCategoryType"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "plist:Information_Property_List.LSApplicationCategoryType",
    "modules": [
      {
        "name": "Bundle Resources"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "LSApplicationCategoryType"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.0",
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Property List Key",
    "symbolKind": "typealias",
    "title": "LSApplicationCategoryType"
  },
  "primaryContentSections": [
    {
      "details": {
        "ideTitle": "Application Category",
        "name": "LSApplicationCategoryType",
        "platforms": [],
        "titleStyle": "symbol",
        "value": [
          {
            "arrayMode": false,
            "baseType": "string"
          }
        ]
      },
      "kind": "details",
      "title": "Details"
    },
    {
      "kind": "possibleValues",
      "title": "Possible Values",
      "values": [
        {
          "content": [],
          "name": "public.app-category.business"
        },
        {
          "content": [],
          "name": "public.app-category.developer-tools"
        },
        {
          "content": [],
          "name": "public.app-category.education"
        },
        {
          "content": [],
          "name": "public.app-category.entertainment"
        },
        {
          "content": [],
          "name": "public.app-category.finance"
        },
        {
          "content": [],
          "name": "public.app-category.games"
        },
        {
          "content": [],
          "name": "public.app-category.action-games"
        },
        {
          "content": [],
          "name": "public.app-category.adventure-games"
        },
        {
          "content": [],
          "name": "public.app-category.arcade-games"
        },
        {
          "content": [],
          "name": "public.app-category.board-games"
        },
        {
          "content": [],
          "name": "public.app-category.card-games"
        },
        {
          "content": [],
          "name": "public.app-category.casino-games"
        },
        {
          "content": [],
          "name": "public.app-category.dice-games"
        },
        {
          "content": [],
          "name": "public.app-category.educational-games"
        },
        {
          "content": [],
          "name": "public.app-category.family-games"
        },
        {
          "content": [],
          "name": "public.app-category.kids-games"
        },
        {
          "content": [],
          "name": "public.app-category.music-games"
        },
        {
          "content": [],
          "name": "public.app-category.puzzle-games"
        },
        {
          "content": [],
          "name": "public.app-category.racing-games"
        },
        {
          "content": [],
          "name": "public.app-category.role-playing-games"
        },
        {
          "content": [],
          "name": "public.app-category.simulation-games"
        },
        {
          "content": [],
          "name": "public.app-category.sports-games"
        },
        {
          "content": [],
          "name": "public.app-category.strategy-games"
        },
        {
          "content": [],
          "name": "public.app-category.trivia-games"
        },
        {
          "content": [],
          "name": "public.app-category.word-games"
        },
        {
          "content": [],
          "name": "public.app-category.graphics-design"
        },
        {
          "content": [],
          "name": "public.app-category.healthcare-fitness"
        },
        {
          "content": [],
          "name": "public.app-category.lifestyle"
        },
        {
          "content": [],
          "name": "public.app-category.medical"
        },
        {
          "content": [],
          "name": "public.app-category.music"
        },
        {
          "content": [],
          "name": "public.app-category.news"
        },
        {
          "content": [],
          "name": "public.app-category.photography"
        },
        {
          "content": [],
          "name": "public.app-category.productivity"
        },
        {
          "content": [],
          "name": "public.app-category.reference"
        },
        {
          "content": [],
          "name": "public.app-category.social-networking"
        },
        {
          "content": [],
          "name": "public.app-category.sports"
        },
        {
          "content": [],
          "name": "public.app-category.travel"
        },
        {
          "content": [],
          "name": "public.app-category.utilities"
        },
        {
          "content": [],
          "name": "public.app-category.video"
        },
        {
          "content": [],
          "name": "public.app-category.weather"
        }
      ]
    }
  ],
  "references": {
    "doc://com.apple.bundleresources/documentation/BundleResources": {
      "abstract": [
        {
          "text": "Resources located in an app, framework, or plugin bundle.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources",
      "kind": "symbol",
      "role": "collection",
      "title": "Bundle Resources",
      "type": "topic",
      "url": "/documentation/bundleresources"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List": {
      "abstract": [
        {
          "text": "A resource containing key-value pairs that identify and configure a bundle.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List",
      "kind": "symbol",
      "name": "Information Property List",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "Information Property List"
        }
      ],
      "role": "symbol",
      "title": "Information Property List",
      "titleStyle": "symbol",
      "type": "topic",
      "url": "/documentation/bundleresources/information-property-list"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/CFBundlePackageType": {
      "abstract": [
        {
          "text": "The type of bundle.",
          "type": "text"
        }
      ],
      "ideTitle": "Bundle OS Type code",
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/CFBundlePackageType",
      "kind": "symbol",
      "name": "CFBundlePackageType",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CFBundlePackageType"
        }
      ],
      "role": "symbol",
      "title": "CFBundlePackageType",
      "titleStyle": "symbol",
      "type": "topic",
      "url": "/documentation/bundleresources/information-property-list/cfbundlepackagetype"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/LSApplicationCategoryType": {
      "abstract": [
        {
          "text": "The category that best describes your app for the App Store.",
          "type": "text"
        }
      ],
      "ideTitle": "Application Category",
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/LSApplicationCategoryType",
      "kind": "symbol",
      "name": "LSApplicationCategoryType",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "LSApplicationCategoryType"
        }
      ],
      "role": "symbol",
      "title": "LSApplicationCategoryType",
      "titleStyle": "symbol",
      "type": "topic",
      "url": "/documentation/bundleresources/information-property-list/lsapplicationcategorytype"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Categorization",
      "generated": true,
      "identifiers": [
        "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/CFBundlePackageType"
      ],
      "title": "Categorization"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.0",
              "name": "macOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Property List Key"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "LSApplicationCategoryType"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "typealias"
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "LSApplicationCategoryType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.bundleresources/documentation/BundleResources",
                "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Categorization",
              "generated": true,
              "identifiers": [
                "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/CFBundlePackageType"
              ],
              "title": "Categorization"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1CFBundlePackageType/title",
          "value": "CFBundlePackageType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1CFBundlePackageType/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CFBundlePackageType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List/title",
          "value": "Information Property List"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "Information Property List"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1LSApplicationCategoryType/title",
          "value": "LSApplicationCategoryType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1LSApplicationCategoryType/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "LSApplicationCategoryType"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/bundleresources/information-property-list/lsapplicationcategorytype"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/bundleresources/information-property-list/lsapplicationcategorytype"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
