{
  "abstract": [
    {
      "text": "Environment variables to set before launching the app.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.bundleresources/documentation/BundleResources",
        "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/LSEnvironment"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "plist:Information_Property_List.LSEnvironment",
    "modules": [
      {
        "name": "Bundle Resources"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "LSEnvironment"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.0",
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Property List Key",
    "symbolKind": "dictionary",
    "title": "LSEnvironment"
  },
  "primaryContentSections": [
    {
      "details": {
        "ideTitle": "Environment variables",
        "name": "LSEnvironment",
        "platforms": [],
        "titleStyle": "symbol",
        "value": [
          {
            "arrayMode": false,
            "baseType": "object"
          }
        ]
      },
      "kind": "details",
      "title": "Details"
    }
  ],
  "references": {
    "doc://com.apple.bundleresources/documentation/BundleResources": {
      "abstract": [
        {
          "text": "Resources located in an app, framework, or plugin bundle.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources",
      "kind": "symbol",
      "role": "collection",
      "title": "Bundle Resources",
      "type": "topic",
      "url": "/documentation/bundleresources"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List": {
      "abstract": [
        {
          "text": "A resource containing key-value pairs that identify and configure a bundle.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List",
      "kind": "symbol",
      "name": "Information Property List",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "Information Property List"
        }
      ],
      "role": "symbol",
      "title": "Information Property List",
      "titleStyle": "symbol",
      "type": "topic",
      "url": "/documentation/bundleresources/information-property-list"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/CFBundleExecutable": {
      "abstract": [
        {
          "text": "The name of the bundle’s executable file.",
          "type": "text"
        }
      ],
      "ideTitle": "Executable file",
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/CFBundleExecutable",
      "kind": "symbol",
      "name": "CFBundleExecutable",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CFBundleExecutable"
        }
      ],
      "role": "symbol",
      "title": "CFBundleExecutable",
      "titleStyle": "symbol",
      "type": "topic",
      "url": "/documentation/bundleresources/information-property-list/cfbundleexecutable"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/CLKComplicationPrincipalClass": {
      "abstract": [
        {
          "text": "The name of the class that implements the complication data source protocol.",
          "type": "text"
        }
      ],
      "ideTitle": "ClockKit Complication - Principal Class",
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/CLKComplicationPrincipalClass",
      "kind": "symbol",
      "name": "CLKComplicationPrincipalClass",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CLKComplicationPrincipalClass"
        }
      ],
      "role": "symbol",
      "title": "CLKComplicationPrincipalClass",
      "titleStyle": "symbol",
      "type": "topic",
      "url": "/documentation/bundleresources/information-property-list/clkcomplicationprincipalclass"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/LSEnvironment": {
      "abstract": [
        {
          "text": "Environment variables to set before launching the app.",
          "type": "text"
        }
      ],
      "ideTitle": "Environment variables",
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/LSEnvironment",
      "kind": "symbol",
      "name": "LSEnvironment",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "LSEnvironment"
        }
      ],
      "role": "symbol",
      "title": "LSEnvironment",
      "titleStyle": "symbol",
      "type": "topic",
      "url": "/documentation/bundleresources/information-property-list/lsenvironment"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSPrincipalClass": {
      "abstract": [
        {
          "text": "The name of the bundle’s main executable class.",
          "type": "text"
        }
      ],
      "ideTitle": "Principal class",
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSPrincipalClass",
      "kind": "symbol",
      "name": "NSPrincipalClass",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSPrincipalClass"
        }
      ],
      "role": "symbol",
      "title": "NSPrincipalClass",
      "titleStyle": "symbol",
      "type": "topic",
      "url": "/documentation/bundleresources/information-property-list/nsprincipalclass"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/UIApplicationShortcutItems": {
      "abstract": [],
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/UIApplicationShortcutItems",
      "kind": "symbol",
      "name": "UIApplicationShortcutItems",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIApplicationShortcutItems"
        }
      ],
      "role": "symbol",
      "title": "UIApplicationShortcutItems",
      "titleStyle": "symbol",
      "type": "topic",
      "url": "/documentation/bundleresources/information-property-list/uiapplicationshortcutitems"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Launch",
      "generated": true,
      "identifiers": [
        "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSPrincipalClass",
        "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/CLKComplicationPrincipalClass",
        "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/CFBundleExecutable",
        "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/UIApplicationShortcutItems"
      ],
      "title": "Launch"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.0",
              "name": "macOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Property List Key"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "LSEnvironment"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "dictionary"
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "LSEnvironment"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.bundleresources/documentation/BundleResources",
                "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Launch",
              "generated": true,
              "identifiers": [
                "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSPrincipalClass",
                "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/CLKComplicationPrincipalClass",
                "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/CFBundleExecutable",
                "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/UIApplicationShortcutItems"
              ],
              "title": "Launch"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1LSEnvironment/title",
          "value": "LSEnvironment"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1LSEnvironment/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "LSEnvironment"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1CLKComplicationPrincipalClass/title",
          "value": "CLKComplicationPrincipalClass"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1CLKComplicationPrincipalClass/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CLKComplicationPrincipalClass"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List/title",
          "value": "Information Property List"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "Information Property List"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1UIApplicationShortcutItems/title",
          "value": "UIApplicationShortcutItems"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1UIApplicationShortcutItems/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UIApplicationShortcutItems"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1CFBundleExecutable/title",
          "value": "CFBundleExecutable"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1CFBundleExecutable/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CFBundleExecutable"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1NSPrincipalClass/title",
          "value": "NSPrincipalClass"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1NSPrincipalClass/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSPrincipalClass"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/bundleresources/information-property-list/lsenvironment"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/bundleresources/information-property-list/lsenvironment"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
