{
  "abstract": [
    {
      "text": "A Boolean value indicating whether the files this app creates are quarantined by default.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.bundleresources/documentation/BundleResources",
        "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/LSFileQuarantineEnabled"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "plist:Information_Property_List.LSFileQuarantineEnabled",
    "modules": [
      {
        "name": "Bundle Resources"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "LSFileQuarantineEnabled"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.0",
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Property List Key",
    "symbolKind": "typealias",
    "title": "LSFileQuarantineEnabled"
  },
  "primaryContentSections": [
    {
      "details": {
        "ideTitle": "File quarantine enabled",
        "name": "LSFileQuarantineEnabled",
        "platforms": [],
        "titleStyle": "symbol",
        "value": [
          {
            "arrayMode": false,
            "baseType": "boolean"
          }
        ]
      },
      "kind": "details",
      "title": "Details"
    }
  ],
  "references": {
    "doc://com.apple.bundleresources/documentation/BundleResources": {
      "abstract": [
        {
          "text": "Resources located in an app, framework, or plugin bundle.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources",
      "kind": "symbol",
      "role": "collection",
      "title": "Bundle Resources",
      "type": "topic",
      "url": "/documentation/bundleresources"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List": {
      "abstract": [
        {
          "text": "A resource containing key-value pairs that identify and configure a bundle.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List",
      "kind": "symbol",
      "name": "Information Property List",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "Information Property List"
        }
      ],
      "role": "symbol",
      "title": "Information Property List",
      "titleStyle": "symbol",
      "type": "topic",
      "url": "/documentation/bundleresources/information-property-list"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/APFiles": {
      "abstract": [
        {
          "text": "Describes the files or directories the app installs on the system.",
          "type": "text"
        }
      ],
      "ideTitle": "Installation files",
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/APFiles",
      "kind": "symbol",
      "name": "APFiles",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "APFiles"
        }
      ],
      "role": "symbol",
      "title": "APFiles",
      "titleStyle": "symbol",
      "type": "topic",
      "url": "/documentation/bundleresources/information-property-list/apfiles"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/APInstallerURL": {
      "abstract": [
        {
          "text": "The base path to the files or folders that the app installs.",
          "type": "text"
        }
      ],
      "ideTitle": "Installation directory base file URL",
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/APInstallerURL",
      "kind": "symbol",
      "name": "APInstallerURL",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "APInstallerURL"
        }
      ],
      "role": "symbol",
      "title": "APInstallerURL",
      "titleStyle": "symbol",
      "type": "topic",
      "url": "/documentation/bundleresources/information-property-list/apinstallerurl"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/CSResourcesFileMapped": {
      "abstract": [
        {
          "text": "A Boolean value indicating whether the app’s resources files should be mapped into memory.",
          "type": "text"
        }
      ],
      "ideTitle": "Resources should be file-mapped",
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/CSResourcesFileMapped",
      "kind": "symbol",
      "name": "CSResourcesFileMapped",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CSResourcesFileMapped"
        }
      ],
      "role": "symbol",
      "title": "CSResourcesFileMapped",
      "titleStyle": "symbol",
      "type": "topic",
      "url": "/documentation/bundleresources/information-property-list/csresourcesfilemapped"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/LSFileQuarantineEnabled": {
      "abstract": [
        {
          "text": "A Boolean value indicating whether the files this app creates are quarantined by default.",
          "type": "text"
        }
      ],
      "ideTitle": "File quarantine enabled",
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/LSFileQuarantineEnabled",
      "kind": "symbol",
      "name": "LSFileQuarantineEnabled",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "LSFileQuarantineEnabled"
        }
      ],
      "role": "symbol",
      "title": "LSFileQuarantineEnabled",
      "titleStyle": "symbol",
      "type": "topic",
      "url": "/documentation/bundleresources/information-property-list/lsfilequarantineenabled"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSDownloadsUbiquitousContents": {
      "abstract": [
        {
          "text": "A Boolean value that indicates whether the system should download documents before handing them over to the app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSDownloadsUbiquitousContents",
      "kind": "symbol",
      "name": "NSDownloadsUbiquitousContents",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSDownloadsUbiquitousContents"
        }
      ],
      "role": "symbol",
      "title": "NSDownloadsUbiquitousContents",
      "titleStyle": "symbol",
      "type": "topic",
      "url": "/documentation/bundleresources/information-property-list/nsdownloadsubiquitouscontents"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSSupportsPurgeableLocalStorage": {
      "abstract": [
        {
          "text": "A Boolean value indicating whether the app continues working if the system purges the local storage.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSSupportsPurgeableLocalStorage",
      "kind": "symbol",
      "name": "NSSupportsPurgeableLocalStorage",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSSupportsPurgeableLocalStorage"
        }
      ],
      "role": "symbol",
      "title": "NSSupportsPurgeableLocalStorage",
      "titleStyle": "symbol",
      "type": "topic",
      "url": "/documentation/bundleresources/information-property-list/nssupportspurgeablelocalstorage"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/UIFileSharingEnabled": {
      "abstract": [
        {
          "text": "A Boolean value indicating whether the app shares files.",
          "type": "text"
        }
      ],
      "ideTitle": "Application supports iTunes file sharing",
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/UIFileSharingEnabled",
      "kind": "symbol",
      "name": "UIFileSharingEnabled",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIFileSharingEnabled"
        }
      ],
      "role": "symbol",
      "title": "UIFileSharingEnabled",
      "titleStyle": "symbol",
      "type": "topic",
      "url": "/documentation/bundleresources/information-property-list/uifilesharingenabled"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Storage",
      "generated": true,
      "identifiers": [
        "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/APFiles",
        "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/APInstallerURL",
        "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSSupportsPurgeableLocalStorage",
        "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/UIFileSharingEnabled",
        "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/CSResourcesFileMapped",
        "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSDownloadsUbiquitousContents"
      ],
      "title": "Storage"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.0",
              "name": "macOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Property List Key"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "LSFileQuarantineEnabled"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "typealias"
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "LSFileQuarantineEnabled"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.bundleresources/documentation/BundleResources",
                "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Storage",
              "generated": true,
              "identifiers": [
                "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/APFiles",
                "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/APInstallerURL",
                "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSSupportsPurgeableLocalStorage",
                "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/UIFileSharingEnabled",
                "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/CSResourcesFileMapped",
                "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSDownloadsUbiquitousContents"
              ],
              "title": "Storage"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1NSSupportsPurgeableLocalStorage/title",
          "value": "NSSupportsPurgeableLocalStorage"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1NSSupportsPurgeableLocalStorage/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSSupportsPurgeableLocalStorage"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1LSFileQuarantineEnabled/title",
          "value": "LSFileQuarantineEnabled"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1LSFileQuarantineEnabled/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "LSFileQuarantineEnabled"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List/title",
          "value": "Information Property List"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "Information Property List"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1APFiles/title",
          "value": "APFiles"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1APFiles/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "APFiles"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1APInstallerURL/title",
          "value": "APInstallerURL"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1APInstallerURL/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "APInstallerURL"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1UIFileSharingEnabled/title",
          "value": "UIFileSharingEnabled"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1UIFileSharingEnabled/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UIFileSharingEnabled"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1CSResourcesFileMapped/title",
          "value": "CSResourcesFileMapped"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1CSResourcesFileMapped/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CSResourcesFileMapped"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1NSDownloadsUbiquitousContents/title",
          "value": "NSDownloadsUbiquitousContents"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1NSDownloadsUbiquitousContents/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSDownloadsUbiquitousContents"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/bundleresources/information-property-list/lsfilequarantineenabled"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/bundleresources/information-property-list/lsfilequarantineenabled"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
