{
  "abstract": [
    {
      "text": "A Boolean value indicating whether the app is notified when a child process dies.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.bundleresources/documentation/BundleResources",
        "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/LSGetAppDiedEvents"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "plist:Information_Property_List.LSGetAppDiedEvents",
    "modules": [
      {
        "name": "Bundle Resources"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "LSGetAppDiedEvents"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.0",
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Property List Key",
    "symbolKind": "typealias",
    "title": "LSGetAppDiedEvents"
  },
  "primaryContentSections": [
    {
      "details": {
        "ideTitle": "Application should get App Died events",
        "name": "LSGetAppDiedEvents",
        "platforms": [],
        "titleStyle": "symbol",
        "value": [
          {
            "arrayMode": false,
            "baseType": "boolean"
          }
        ]
      },
      "kind": "details",
      "title": "Details"
    }
  ],
  "references": {
    "doc://com.apple.bundleresources/documentation/BundleResources": {
      "abstract": [
        {
          "text": "Resources located in an app, framework, or plugin bundle.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources",
      "kind": "symbol",
      "role": "collection",
      "title": "Bundle Resources",
      "type": "topic",
      "url": "/documentation/bundleresources"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List": {
      "abstract": [
        {
          "text": "A resource containing key-value pairs that identify and configure a bundle.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List",
      "kind": "symbol",
      "name": "Information Property List",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "Information Property List"
        }
      ],
      "role": "symbol",
      "title": "Information Property List",
      "titleStyle": "symbol",
      "type": "topic",
      "url": "/documentation/bundleresources/information-property-list"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/LSGetAppDiedEvents": {
      "abstract": [
        {
          "text": "A Boolean value indicating whether the app is notified when a child process dies.",
          "type": "text"
        }
      ],
      "ideTitle": "Application should get App Died events",
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/LSGetAppDiedEvents",
      "kind": "symbol",
      "name": "LSGetAppDiedEvents",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "LSGetAppDiedEvents"
        }
      ],
      "role": "symbol",
      "title": "LSGetAppDiedEvents",
      "titleStyle": "symbol",
      "type": "topic",
      "url": "/documentation/bundleresources/information-property-list/lsgetappdiedevents"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSSupportsSuddenTermination": {
      "abstract": [
        {
          "text": "A Boolean value indicating whether the system may terminate the app to log out or shut down more quickly.",
          "type": "text"
        }
      ],
      "ideTitle": "Application can be killed immediately after launch",
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSSupportsSuddenTermination",
      "kind": "symbol",
      "name": "NSSupportsSuddenTermination",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSSupportsSuddenTermination"
        }
      ],
      "role": "symbol",
      "title": "NSSupportsSuddenTermination",
      "titleStyle": "symbol",
      "type": "topic",
      "url": "/documentation/bundleresources/information-property-list/nssupportssuddentermination"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/UIApplicationExitsOnSuspend": {
      "abstract": [
        {
          "text": "A Boolean value indicating whether the app terminates, rather than moves to the background, when the app quits.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "ideTitle": "Application does not run in background",
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/UIApplicationExitsOnSuspend",
      "kind": "symbol",
      "name": "UIApplicationExitsOnSuspend",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIApplicationExitsOnSuspend"
        }
      ],
      "role": "symbol",
      "title": "UIApplicationExitsOnSuspend",
      "titleStyle": "symbol",
      "type": "topic",
      "url": "/documentation/bundleresources/information-property-list/uiapplicationexitsonsuspend"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Termination",
      "generated": true,
      "identifiers": [
        "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSSupportsSuddenTermination",
        "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/UIApplicationExitsOnSuspend"
      ],
      "title": "Termination"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.0",
              "name": "macOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Property List Key"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "LSGetAppDiedEvents"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "typealias"
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "LSGetAppDiedEvents"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.bundleresources/documentation/BundleResources",
                "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Termination",
              "generated": true,
              "identifiers": [
                "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSSupportsSuddenTermination",
                "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/UIApplicationExitsOnSuspend"
              ],
              "title": "Termination"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List/title",
          "value": "Information Property List"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "Information Property List"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1NSSupportsSuddenTermination/title",
          "value": "NSSupportsSuddenTermination"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1NSSupportsSuddenTermination/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSSupportsSuddenTermination"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1UIApplicationExitsOnSuspend/title",
          "value": "UIApplicationExitsOnSuspend"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1UIApplicationExitsOnSuspend/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UIApplicationExitsOnSuspend"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1LSGetAppDiedEvents/title",
          "value": "LSGetAppDiedEvents"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1LSGetAppDiedEvents/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "LSGetAppDiedEvents"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/bundleresources/information-property-list/lsgetappdiedevents"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/bundleresources/information-property-list/lsgetappdiedevents"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
