{
  "abstract": [
    {
      "text": "The minimum version of macOS required for the app to run on a set of architectures.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.bundleresources/documentation/BundleResources",
        "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/LSMinimumSystemVersionByArchitecture"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "plist:Information_Property_List.LSMinimumSystemVersionByArchitecture",
    "modules": [
      {
        "name": "Bundle Resources"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "LSMinimumSystemVersionByArchitecture"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.0",
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Property List Key",
    "symbolKind": "dictionary",
    "title": "LSMinimumSystemVersionByArchitecture"
  },
  "primaryContentSections": [
    {
      "details": {
        "ideTitle": "Minimum system versions, per-architecture",
        "name": "LSMinimumSystemVersionByArchitecture",
        "platforms": [],
        "titleStyle": "symbol",
        "value": [
          {
            "arrayMode": false,
            "baseType": "object"
          }
        ]
      },
      "kind": "details",
      "title": "Details"
    },
    {
      "items": [
        {
          "attributes": [
            {
              "kind": "default",
              "value": "10.0.0"
            }
          ],
          "content": [],
          "introducedVersion": "10.0.0",
          "name": "i386",
          "required": false,
          "type": [
            {
              "kind": "text",
              "text": "string"
            }
          ]
        },
        {
          "attributes": [
            {
              "kind": "default",
              "value": "10.0.0"
            }
          ],
          "content": [],
          "introducedVersion": "10.0.0",
          "name": "ppc",
          "required": false,
          "type": [
            {
              "kind": "text",
              "text": "string"
            }
          ]
        },
        {
          "attributes": [
            {
              "kind": "default",
              "value": "10.0.0"
            }
          ],
          "content": [],
          "introducedVersion": "10.0.0",
          "name": "ppc64",
          "required": false,
          "type": [
            {
              "kind": "text",
              "text": "string"
            }
          ]
        },
        {
          "attributes": [
            {
              "kind": "default",
              "value": "10.0.0"
            }
          ],
          "content": [],
          "introducedVersion": "10.0.0",
          "name": "x86_64",
          "required": false,
          "type": [
            {
              "kind": "text",
              "text": "string"
            }
          ]
        }
      ],
      "kind": "properties",
      "title": "Properties"
    },
    {
      "content": [
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "The possible dictionary keys are: ",
              "type": "text"
            },
            {
              "code": "i386",
              "type": "codeVoice"
            },
            {
              "text": ", ",
              "type": "text"
            },
            {
              "code": "ppc",
              "type": "codeVoice"
            },
            {
              "text": ", ",
              "type": "text"
            },
            {
              "code": "ppc64",
              "type": "codeVoice"
            },
            {
              "text": ", and ",
              "type": "text"
            },
            {
              "code": "x86_64",
              "type": "codeVoice"
            },
            {
              "text": ". The values are the minimum version for the architecture. The default values are ",
              "type": "text"
            },
            {
              "code": "10.0.0",
              "type": "codeVoice"
            },
            {
              "text": ".",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.bundleresources/documentation/BundleResources": {
      "abstract": [
        {
          "text": "Resources located in an app, framework, or plugin bundle.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources",
      "kind": "symbol",
      "role": "collection",
      "title": "Bundle Resources",
      "type": "topic",
      "url": "/documentation/bundleresources"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List": {
      "abstract": [
        {
          "text": "A resource containing key-value pairs that identify and configure a bundle.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List",
      "kind": "symbol",
      "name": "Information Property List",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "Information Property List"
        }
      ],
      "role": "symbol",
      "title": "Information Property List",
      "titleStyle": "symbol",
      "type": "topic",
      "url": "/documentation/bundleresources/information-property-list"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/LSMinimumSystemVersion": {
      "abstract": [
        {
          "text": "The minimum version of the operating system required for the app to run in macOS.",
          "type": "text"
        }
      ],
      "ideTitle": "Minimum system version",
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/LSMinimumSystemVersion",
      "kind": "symbol",
      "name": "LSMinimumSystemVersion",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "LSMinimumSystemVersion"
        }
      ],
      "role": "symbol",
      "title": "LSMinimumSystemVersion",
      "titleStyle": "symbol",
      "type": "topic",
      "url": "/documentation/bundleresources/information-property-list/lsminimumsystemversion"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/LSMinimumSystemVersionByArchitecture": {
      "abstract": [
        {
          "text": "The minimum version of macOS required for the app to run on a set of architectures.",
          "type": "text"
        }
      ],
      "ideTitle": "Minimum system versions, per-architecture",
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/LSMinimumSystemVersionByArchitecture",
      "kind": "symbol",
      "name": "LSMinimumSystemVersionByArchitecture",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "LSMinimumSystemVersionByArchitecture"
        }
      ],
      "role": "symbol",
      "title": "LSMinimumSystemVersionByArchitecture",
      "titleStyle": "symbol",
      "type": "topic",
      "url": "/documentation/bundleresources/information-property-list/lsminimumsystemversionbyarchitecture"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/LSRequiresIPhoneOS": {
      "abstract": [
        {
          "text": "A Boolean value indicating whether the app must run in iOS.",
          "type": "text"
        }
      ],
      "ideTitle": "Application requires iPhone environment",
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/LSRequiresIPhoneOS",
      "kind": "symbol",
      "name": "LSRequiresIPhoneOS",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "LSRequiresIPhoneOS"
        }
      ],
      "role": "symbol",
      "title": "LSRequiresIPhoneOS",
      "titleStyle": "symbol",
      "type": "topic",
      "url": "/documentation/bundleresources/information-property-list/lsrequiresiphoneos"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/MinimumOSVersion": {
      "abstract": [
        {
          "text": "The minimum version of the operating system required for the app to run in iOS, iPadOS, tvOS, and watchOS.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/MinimumOSVersion",
      "kind": "symbol",
      "name": "MinimumOSVersion",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MinimumOSVersion"
        }
      ],
      "role": "symbol",
      "title": "MinimumOSVersion",
      "titleStyle": "symbol",
      "type": "topic",
      "url": "/documentation/bundleresources/information-property-list/minimumosversion"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/WKApplication": {
      "abstract": [],
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/WKApplication",
      "kind": "symbol",
      "name": "WKApplication",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "WKApplication"
        }
      ],
      "role": "symbol",
      "title": "WKApplication",
      "titleStyle": "symbol",
      "type": "topic",
      "url": "/documentation/bundleresources/information-property-list/wkapplication"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/WKWatchKitApp": {
      "abstract": [
        {
          "text": "A Boolean value that indicates whether the bundle is a watchOS app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/WKWatchKitApp",
      "kind": "symbol",
      "name": "WKWatchKitApp",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "WKWatchKitApp"
        }
      ],
      "role": "symbol",
      "title": "WKWatchKitApp",
      "titleStyle": "symbol",
      "type": "topic",
      "url": "/documentation/bundleresources/information-property-list/wkwatchkitapp"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Operating-system-version",
      "generated": true,
      "identifiers": [
        "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/LSMinimumSystemVersion",
        "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/MinimumOSVersion",
        "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/LSRequiresIPhoneOS",
        "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/WKApplication",
        "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/WKWatchKitApp"
      ],
      "title": "Operating system version"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.0",
              "name": "macOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Property List Key"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "LSMinimumSystemVersionByArchitecture"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "dictionary"
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "LSMinimumSystemVersionByArchitecture"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.bundleresources/documentation/BundleResources",
                "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Operating-system-version",
              "generated": true,
              "identifiers": [
                "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/LSMinimumSystemVersion",
                "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/MinimumOSVersion",
                "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/LSRequiresIPhoneOS",
                "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/WKApplication",
                "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/WKWatchKitApp"
              ],
              "title": "Operating system version"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/3",
          "value": {
            "items": [
              {
                "attributes": [
                  {
                    "kind": "default",
                    "value": "10.0.0"
                  }
                ],
                "content": [],
                "introducedVersion": "10.0.0",
                "name": "i386",
                "required": false,
                "type": [
                  {
                    "kind": "text",
                    "text": "string"
                  }
                ]
              },
              {
                "attributes": [
                  {
                    "kind": "default",
                    "value": "10.0.0"
                  }
                ],
                "content": [],
                "introducedVersion": "10.0.0",
                "name": "ppc",
                "required": false,
                "type": [
                  {
                    "kind": "text",
                    "text": "string"
                  }
                ]
              },
              {
                "attributes": [
                  {
                    "kind": "default",
                    "value": "10.0.0"
                  }
                ],
                "content": [],
                "introducedVersion": "10.0.0",
                "name": "ppc64",
                "required": false,
                "type": [
                  {
                    "kind": "text",
                    "text": "string"
                  }
                ]
              },
              {
                "attributes": [
                  {
                    "kind": "default",
                    "value": "10.0.0"
                  }
                ],
                "content": [],
                "introducedVersion": "10.0.0",
                "name": "x86_64",
                "required": false,
                "type": [
                  {
                    "kind": "text",
                    "text": "string"
                  }
                ]
              }
            ],
            "kind": "properties",
            "title": "Properties"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1LSMinimumSystemVersion/title",
          "value": "LSMinimumSystemVersion"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1LSMinimumSystemVersion/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "LSMinimumSystemVersion"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List/title",
          "value": "Information Property List"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "Information Property List"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1LSRequiresIPhoneOS/title",
          "value": "LSRequiresIPhoneOS"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1LSRequiresIPhoneOS/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "LSRequiresIPhoneOS"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1LSMinimumSystemVersionByArchitecture/title",
          "value": "LSMinimumSystemVersionByArchitecture"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1LSMinimumSystemVersionByArchitecture/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "LSMinimumSystemVersionByArchitecture"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1MinimumOSVersion/title",
          "value": "MinimumOSVersion"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1MinimumOSVersion/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MinimumOSVersion"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1WKWatchKitApp/title",
          "value": "WKWatchKitApp"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1WKWatchKitApp/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "WKWatchKitApp"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1WKApplication/title",
          "value": "WKApplication"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1WKApplication/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "WKApplication"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/bundleresources/information-property-list/lsminimumsystemversionbyarchitecture"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/bundleresources/information-property-list/lsminimumsystemversionbyarchitecture"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
