{
  "abstract": [
    {
      "text": "The minimum version of the operating system required for the app to run in macOS.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.bundleresources/documentation/BundleResources",
        "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/LSMinimumSystemVersion"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "plist:Information_Property_List.LSMinimumSystemVersion",
    "modules": [
      {
        "name": "Bundle Resources"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "LSMinimumSystemVersion"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.0",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.0",
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Property List Key",
    "symbolKind": "typealias",
    "title": "LSMinimumSystemVersion"
  },
  "primaryContentSections": [
    {
      "details": {
        "ideTitle": "Minimum system version",
        "name": "LSMinimumSystemVersion",
        "platforms": [],
        "titleStyle": "symbol",
        "value": [
          {
            "arrayMode": false,
            "baseType": "string"
          }
        ]
      },
      "kind": "details",
      "title": "Details"
    },
    {
      "attributes": [
        {
          "kind": "default",
          "value": "10.0.0"
        }
      ],
      "kind": "attributes",
      "title": "Attributes"
    },
    {
      "content": [
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Use this key to indicate the minimum macOS release that your app supports. The App Store uses this key to indicate the macOS releases on which your app can run, and to show compatibility with a person’s Mac.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "Starting with macOS 11.4, the lowest version number you can specify as the value for the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/LSMinimumSystemVersion",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " key is:",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "items": [
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "code": "10",
                      "type": "codeVoice"
                    },
                    {
                      "text": " if your app links against the macOS SDK.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "code": "10.15",
                      "type": "codeVoice"
                    },
                    {
                      "text": " if your app links against the iOS 14.3 SDK (or later) and builds using Mac Catalyst.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "code": "11",
                      "type": "codeVoice"
                    },
                    {
                      "text": " if your iPad or iPhone app links against the iOS 14.3 SDK (or later) and can run on a Mac with Apple silicon.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            }
          ],
          "type": "unorderedList"
        },
        {
          "inlineContent": [
            {
              "text": "To specify the minimum version of iOS, iPadOS, tvOS, or watchOS that your app supports, use ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/MinimumOSVersion",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ".",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.bundleresources/documentation/BundleResources": {
      "abstract": [
        {
          "text": "Resources located in an app, framework, or plugin bundle.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources",
      "kind": "symbol",
      "role": "collection",
      "title": "Bundle Resources",
      "type": "topic",
      "url": "/documentation/bundleresources"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List": {
      "abstract": [
        {
          "text": "A resource containing key-value pairs that identify and configure a bundle.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List",
      "kind": "symbol",
      "name": "Information Property List",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "Information Property List"
        }
      ],
      "role": "symbol",
      "title": "Information Property List",
      "titleStyle": "symbol",
      "type": "topic",
      "url": "/documentation/bundleresources/information-property-list"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/LSMinimumSystemVersion": {
      "abstract": [
        {
          "text": "The minimum version of the operating system required for the app to run in macOS.",
          "type": "text"
        }
      ],
      "ideTitle": "Minimum system version",
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/LSMinimumSystemVersion",
      "kind": "symbol",
      "name": "LSMinimumSystemVersion",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "LSMinimumSystemVersion"
        }
      ],
      "role": "symbol",
      "title": "LSMinimumSystemVersion",
      "titleStyle": "symbol",
      "type": "topic",
      "url": "/documentation/bundleresources/information-property-list/lsminimumsystemversion"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/LSMinimumSystemVersionByArchitecture": {
      "abstract": [
        {
          "text": "The minimum version of macOS required for the app to run on a set of architectures.",
          "type": "text"
        }
      ],
      "ideTitle": "Minimum system versions, per-architecture",
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/LSMinimumSystemVersionByArchitecture",
      "kind": "symbol",
      "name": "LSMinimumSystemVersionByArchitecture",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "LSMinimumSystemVersionByArchitecture"
        }
      ],
      "role": "symbol",
      "title": "LSMinimumSystemVersionByArchitecture",
      "titleStyle": "symbol",
      "type": "topic",
      "url": "/documentation/bundleresources/information-property-list/lsminimumsystemversionbyarchitecture"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/LSRequiresIPhoneOS": {
      "abstract": [
        {
          "text": "A Boolean value indicating whether the app must run in iOS.",
          "type": "text"
        }
      ],
      "ideTitle": "Application requires iPhone environment",
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/LSRequiresIPhoneOS",
      "kind": "symbol",
      "name": "LSRequiresIPhoneOS",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "LSRequiresIPhoneOS"
        }
      ],
      "role": "symbol",
      "title": "LSRequiresIPhoneOS",
      "titleStyle": "symbol",
      "type": "topic",
      "url": "/documentation/bundleresources/information-property-list/lsrequiresiphoneos"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/MinimumOSVersion": {
      "abstract": [
        {
          "text": "The minimum version of the operating system required for the app to run in iOS, iPadOS, tvOS, and watchOS.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/MinimumOSVersion",
      "kind": "symbol",
      "name": "MinimumOSVersion",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MinimumOSVersion"
        }
      ],
      "role": "symbol",
      "title": "MinimumOSVersion",
      "titleStyle": "symbol",
      "type": "topic",
      "url": "/documentation/bundleresources/information-property-list/minimumosversion"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/WKApplication": {
      "abstract": [],
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/WKApplication",
      "kind": "symbol",
      "name": "WKApplication",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "WKApplication"
        }
      ],
      "role": "symbol",
      "title": "WKApplication",
      "titleStyle": "symbol",
      "type": "topic",
      "url": "/documentation/bundleresources/information-property-list/wkapplication"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/WKWatchKitApp": {
      "abstract": [
        {
          "text": "A Boolean value that indicates whether the bundle is a watchOS app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/WKWatchKitApp",
      "kind": "symbol",
      "name": "WKWatchKitApp",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "WKWatchKitApp"
        }
      ],
      "role": "symbol",
      "title": "WKWatchKitApp",
      "titleStyle": "symbol",
      "type": "topic",
      "url": "/documentation/bundleresources/information-property-list/wkwatchkitapp"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Operating-system-version",
      "generated": true,
      "identifiers": [
        "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/LSMinimumSystemVersionByArchitecture",
        "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/MinimumOSVersion",
        "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/LSRequiresIPhoneOS",
        "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/WKApplication",
        "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/WKWatchKitApp"
      ],
      "title": "Operating system version"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.0",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.0",
              "name": "macOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Property List Key"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "LSMinimumSystemVersion"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "typealias"
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "LSMinimumSystemVersion"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.bundleresources/documentation/BundleResources",
                "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Operating-system-version",
              "generated": true,
              "identifiers": [
                "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/LSMinimumSystemVersionByArchitecture",
                "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/MinimumOSVersion",
                "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/LSRequiresIPhoneOS",
                "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/WKApplication",
                "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/WKWatchKitApp"
              ],
              "title": "Operating system version"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List/title",
          "value": "Information Property List"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "Information Property List"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1MinimumOSVersion/title",
          "value": "MinimumOSVersion"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1MinimumOSVersion/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MinimumOSVersion"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1WKApplication/title",
          "value": "WKApplication"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1WKApplication/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "WKApplication"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1LSMinimumSystemVersion/title",
          "value": "LSMinimumSystemVersion"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1LSMinimumSystemVersion/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "LSMinimumSystemVersion"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1LSMinimumSystemVersionByArchitecture/title",
          "value": "LSMinimumSystemVersionByArchitecture"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1LSMinimumSystemVersionByArchitecture/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "LSMinimumSystemVersionByArchitecture"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1WKWatchKitApp/title",
          "value": "WKWatchKitApp"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1WKWatchKitApp/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "WKWatchKitApp"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1LSRequiresIPhoneOS/title",
          "value": "LSRequiresIPhoneOS"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1LSRequiresIPhoneOS/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "LSRequiresIPhoneOS"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/bundleresources/information-property-list/lsminimumsystemversion"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/bundleresources/information-property-list/lsminimumsystemversion"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
