{
  "abstract": [
    {
      "text": "A Boolean value indicating whether the app may open the original document from a file provider, rather than a copy of the document.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.bundleresources/documentation/BundleResources",
        "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/LSSupportsOpeningDocumentsInPlace"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "plist:Information_Property_List.LSSupportsOpeningDocumentsInPlace",
    "modules": [
      {
        "name": "Bundle Resources"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "LSSupportsOpeningDocumentsInPlace"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "2.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "2.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Property List Key",
    "symbolKind": "typealias",
    "title": "LSSupportsOpeningDocumentsInPlace"
  },
  "primaryContentSections": [
    {
      "details": {
        "ideTitle": "Supports opening documents in place",
        "name": "LSSupportsOpeningDocumentsInPlace",
        "platforms": [],
        "titleStyle": "symbol",
        "value": [
          {
            "arrayMode": false,
            "baseType": "boolean"
          }
        ]
      },
      "kind": "details",
      "title": "Details"
    }
  ],
  "references": {
    "doc://com.apple.bundleresources/documentation/BundleResources": {
      "abstract": [
        {
          "text": "Resources located in an app, framework, or plugin bundle.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources",
      "kind": "symbol",
      "role": "collection",
      "title": "Bundle Resources",
      "type": "topic",
      "url": "/documentation/bundleresources"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List": {
      "abstract": [
        {
          "text": "A resource containing key-value pairs that identify and configure a bundle.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List",
      "kind": "symbol",
      "name": "Information Property List",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "Information Property List"
        }
      ],
      "role": "symbol",
      "title": "Information Property List",
      "titleStyle": "symbol",
      "type": "topic",
      "url": "/documentation/bundleresources/information-property-list"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/CFBundleDocumentTypes": {
      "abstract": [
        {
          "text": "The document types supported by the bundle.",
          "type": "text"
        }
      ],
      "ideTitle": "Document types",
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/CFBundleDocumentTypes",
      "kind": "symbol",
      "name": "CFBundleDocumentTypes",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CFBundleDocumentTypes"
        }
      ],
      "role": "symbol",
      "title": "CFBundleDocumentTypes",
      "titleStyle": "symbol",
      "type": "topic",
      "url": "/documentation/bundleresources/information-property-list/cfbundledocumenttypes"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/LSSupportsOpeningDocumentsInPlace": {
      "abstract": [
        {
          "text": "A Boolean value indicating whether the app may open the original document from a file provider, rather than a copy of the document.",
          "type": "text"
        }
      ],
      "ideTitle": "Supports opening documents in place",
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/LSSupportsOpeningDocumentsInPlace",
      "kind": "symbol",
      "name": "LSSupportsOpeningDocumentsInPlace",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "LSSupportsOpeningDocumentsInPlace"
        }
      ],
      "role": "symbol",
      "title": "LSSupportsOpeningDocumentsInPlace",
      "titleStyle": "symbol",
      "type": "topic",
      "url": "/documentation/bundleresources/information-property-list/lssupportsopeningdocumentsinplace"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSDownloadsUbiquitousContents": {
      "abstract": [
        {
          "text": "A Boolean value that indicates whether the system should download documents before handing them over to the app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSDownloadsUbiquitousContents",
      "kind": "symbol",
      "name": "NSDownloadsUbiquitousContents",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSDownloadsUbiquitousContents"
        }
      ],
      "role": "symbol",
      "title": "NSDownloadsUbiquitousContents",
      "titleStyle": "symbol",
      "type": "topic",
      "url": "/documentation/bundleresources/information-property-list/nsdownloadsubiquitouscontents"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/UISupportsDocumentBrowser": {
      "abstract": [
        {
          "text": "A Boolean value indicating whether the app is a document-based app.",
          "type": "text"
        }
      ],
      "ideTitle": "Supports Document Browser",
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/UISupportsDocumentBrowser",
      "kind": "symbol",
      "name": "UISupportsDocumentBrowser",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UISupportsDocumentBrowser"
        }
      ],
      "role": "symbol",
      "title": "UISupportsDocumentBrowser",
      "titleStyle": "symbol",
      "type": "topic",
      "url": "/documentation/bundleresources/information-property-list/uisupportsdocumentbrowser"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Documents",
      "generated": true,
      "identifiers": [
        "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/CFBundleDocumentTypes",
        "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/UISupportsDocumentBrowser",
        "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSDownloadsUbiquitousContents"
      ],
      "title": "Documents"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "2.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "2.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Property List Key"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "LSSupportsOpeningDocumentsInPlace"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "typealias"
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "LSSupportsOpeningDocumentsInPlace"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.bundleresources/documentation/BundleResources",
                "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Documents",
              "generated": true,
              "identifiers": [
                "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/CFBundleDocumentTypes",
                "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/UISupportsDocumentBrowser",
                "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSDownloadsUbiquitousContents"
              ],
              "title": "Documents"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1UISupportsDocumentBrowser/title",
          "value": "UISupportsDocumentBrowser"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1UISupportsDocumentBrowser/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UISupportsDocumentBrowser"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1NSDownloadsUbiquitousContents/title",
          "value": "NSDownloadsUbiquitousContents"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1NSDownloadsUbiquitousContents/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSDownloadsUbiquitousContents"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1LSSupportsOpeningDocumentsInPlace/title",
          "value": "LSSupportsOpeningDocumentsInPlace"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1LSSupportsOpeningDocumentsInPlace/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "LSSupportsOpeningDocumentsInPlace"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1CFBundleDocumentTypes/title",
          "value": "CFBundleDocumentTypes"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1CFBundleDocumentTypes/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CFBundleDocumentTypes"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List/title",
          "value": "Information Property List"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "Information Property List"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/bundleresources/information-property-list/lssupportsopeningdocumentsinplace"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/bundleresources/information-property-list/lssupportsopeningdocumentsinplace"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
