{
  "abstract": [
    {
      "text": "The initial user-interface mode for the app.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.bundleresources/documentation/BundleResources",
        "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/LSUIPresentationMode"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "plist:Information_Property_List.LSUIPresentationMode",
    "modules": [
      {
        "name": "Bundle Resources"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "LSUIPresentationMode"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.0",
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Property List Key",
    "symbolKind": "typealias",
    "title": "LSUIPresentationMode"
  },
  "primaryContentSections": [
    {
      "details": {
        "ideTitle": "Application UI Presentation Mode",
        "name": "LSUIPresentationMode",
        "platforms": [],
        "titleStyle": "symbol",
        "value": [
          {
            "arrayMode": false,
            "baseType": "number"
          }
        ]
      },
      "kind": "details",
      "title": "Details"
    },
    {
      "kind": "possibleValues",
      "title": "Possible Values",
      "values": [
        {
          "content": [],
          "name": "0"
        },
        {
          "content": [],
          "name": "1"
        },
        {
          "content": [],
          "name": "2"
        },
        {
          "content": [],
          "name": "3"
        },
        {
          "content": [],
          "name": "4"
        }
      ]
    },
    {
      "attributes": [
        {
          "kind": "default",
          "value": "0"
        }
      ],
      "kind": "attributes",
      "title": "Attributes"
    }
  ],
  "references": {
    "doc://com.apple.bundleresources/documentation/BundleResources": {
      "abstract": [
        {
          "text": "Resources located in an app, framework, or plugin bundle.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources",
      "kind": "symbol",
      "role": "collection",
      "title": "Bundle Resources",
      "type": "topic",
      "url": "/documentation/bundleresources"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List": {
      "abstract": [
        {
          "text": "A resource containing key-value pairs that identify and configure a bundle.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List",
      "kind": "symbol",
      "name": "Information Property List",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "Information Property List"
        }
      ],
      "role": "symbol",
      "title": "Information Property List",
      "titleStyle": "symbol",
      "type": "topic",
      "url": "/documentation/bundleresources/information-property-list"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/LSUIPresentationMode": {
      "abstract": [
        {
          "text": "The initial user-interface mode for the app.",
          "type": "text"
        }
      ],
      "ideTitle": "Application UI Presentation Mode",
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/LSUIPresentationMode",
      "kind": "symbol",
      "name": "LSUIPresentationMode",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "LSUIPresentationMode"
        }
      ],
      "role": "symbol",
      "title": "LSUIPresentationMode",
      "titleStyle": "symbol",
      "type": "topic",
      "url": "/documentation/bundleresources/information-property-list/lsuipresentationmode"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/UILaunchScreen": {
      "abstract": [
        {
          "text": "The user interface to show while an app launches.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/UILaunchScreen",
      "kind": "symbol",
      "name": "UILaunchScreen",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UILaunchScreen"
        }
      ],
      "role": "symbol",
      "title": "UILaunchScreen",
      "titleStyle": "symbol",
      "type": "topic",
      "url": "/documentation/bundleresources/information-property-list/uilaunchscreen"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/UILaunchScreens": {
      "abstract": [
        {
          "text": "The user interfaces to show while an app launches in response to different URL schemes.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/UILaunchScreens",
      "kind": "symbol",
      "name": "UILaunchScreens",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UILaunchScreens"
        }
      ],
      "role": "symbol",
      "title": "UILaunchScreens",
      "titleStyle": "symbol",
      "type": "topic",
      "url": "/documentation/bundleresources/information-property-list/uilaunchscreens"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/UILaunchStoryboardName": {
      "abstract": [
        {
          "text": "The filename of the storyboard from which to generate the app’s launch image.",
          "type": "text"
        }
      ],
      "ideTitle": "Launch screen interface file base name",
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/UILaunchStoryboardName",
      "kind": "symbol",
      "name": "UILaunchStoryboardName",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UILaunchStoryboardName"
        }
      ],
      "role": "symbol",
      "title": "UILaunchStoryboardName",
      "titleStyle": "symbol",
      "type": "topic",
      "url": "/documentation/bundleresources/information-property-list/uilaunchstoryboardname"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/UILaunchStoryboards": {
      "abstract": [
        {
          "text": "The launch storyboard to use to generate a launch image when your app opens from a supported scheme.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/UILaunchStoryboards",
      "kind": "symbol",
      "name": "UILaunchStoryboards",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UILaunchStoryboards"
        }
      ],
      "role": "symbol",
      "title": "UILaunchStoryboards",
      "titleStyle": "symbol",
      "type": "topic",
      "url": "/documentation/bundleresources/information-property-list/uilaunchstoryboards"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/UILaunchToFullScreenByDefaultOnMac": {
      "abstract": [
        {
          "text": "A Boolean value that indicates whether to launch your iPad app in full-screen mode when running on a Mac.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/UILaunchToFullScreenByDefaultOnMac",
      "kind": "symbol",
      "name": "UILaunchToFullScreenByDefaultOnMac",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UILaunchToFullScreenByDefaultOnMac"
        }
      ],
      "role": "symbol",
      "title": "UILaunchToFullScreenByDefaultOnMac",
      "titleStyle": "symbol",
      "type": "topic",
      "url": "/documentation/bundleresources/information-property-list/uilaunchtofullscreenbydefaultonmac"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Launch-interface",
      "generated": true,
      "identifiers": [
        "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/UILaunchScreen",
        "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/UILaunchScreens",
        "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/UILaunchStoryboardName",
        "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/UILaunchStoryboards",
        "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/UILaunchToFullScreenByDefaultOnMac"
      ],
      "title": "Launch interface"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.0",
              "name": "macOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Property List Key"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "LSUIPresentationMode"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "typealias"
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "LSUIPresentationMode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.bundleresources/documentation/BundleResources",
                "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Launch-interface",
              "generated": true,
              "identifiers": [
                "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/UILaunchScreen",
                "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/UILaunchScreens",
                "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/UILaunchStoryboardName",
                "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/UILaunchStoryboards",
                "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/UILaunchToFullScreenByDefaultOnMac"
              ],
              "title": "Launch interface"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1UILaunchScreens/title",
          "value": "UILaunchScreens"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1UILaunchScreens/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UILaunchScreens"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1LSUIPresentationMode/title",
          "value": "LSUIPresentationMode"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1LSUIPresentationMode/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "LSUIPresentationMode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1UILaunchToFullScreenByDefaultOnMac/title",
          "value": "UILaunchToFullScreenByDefaultOnMac"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1UILaunchToFullScreenByDefaultOnMac/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UILaunchToFullScreenByDefaultOnMac"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1UILaunchStoryboards/title",
          "value": "UILaunchStoryboards"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1UILaunchStoryboards/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UILaunchStoryboards"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1UILaunchScreen/title",
          "value": "UILaunchScreen"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1UILaunchScreen/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UILaunchScreen"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1UILaunchStoryboardName/title",
          "value": "UILaunchStoryboardName"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1UILaunchStoryboardName/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UILaunchStoryboardName"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List/title",
          "value": "Information Property List"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "Information Property List"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/bundleresources/information-property-list/lsuipresentationmode"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/bundleresources/information-property-list/lsuipresentationmode"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
