{
  "abstract": [
    {
      "text": "An array of strings that represent the hexadecimal values of Bluetooth SIG-defined services or custom services for accessories your app configures.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.bundleresources/documentation/BundleResources",
        "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSAccessorySetupBluetoothServices"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "plist:Information_Property_List.NSAccessorySetupBluetoothServices",
    "modules": [
      {
        "name": "Bundle Resources"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "NSAccessorySetupBluetoothServices"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "18.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "18.0",
        "name": "iPadOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Property List Key",
    "symbolKind": "typealias",
    "title": "NSAccessorySetupBluetoothServices"
  },
  "primaryContentSections": [
    {
      "details": {
        "ideTitle": "AccessorySetupKit - Bluetooth Services",
        "name": "NSAccessorySetupBluetoothServices",
        "platforms": [],
        "titleStyle": "symbol",
        "value": [
          {
            "arrayMode": true,
            "baseType": "string "
          }
        ]
      },
      "kind": "details",
      "title": "Details"
    },
    {
      "content": [
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Each value is a 16- or 128-bit UUID that represents either a Bluetooth Special Interest Group (SIG)-registered service or a custom service.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.bundleresources/documentation/BundleResources": {
      "abstract": [
        {
          "text": "Resources located in an app, framework, or plugin bundle.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources",
      "kind": "symbol",
      "role": "collection",
      "title": "Bundle Resources",
      "type": "topic",
      "url": "/documentation/bundleresources"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List": {
      "abstract": [
        {
          "text": "A resource containing key-value pairs that identify and configure a bundle.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List",
      "kind": "symbol",
      "name": "Information Property List",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "Information Property List"
        }
      ],
      "role": "symbol",
      "title": "Information Property List",
      "titleStyle": "symbol",
      "type": "topic",
      "url": "/documentation/bundleresources/information-property-list"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSAccessorySetupBluetoothCompanyIdentifiers": {
      "abstract": [
        {
          "text": "An array of strings that represent the Bluetooth company identifiers for accessories that your app configures.",
          "type": "text"
        }
      ],
      "ideTitle": "AccessorySetupKit - Bluetooth Company Identifiers",
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSAccessorySetupBluetoothCompanyIdentifiers",
      "kind": "symbol",
      "name": "NSAccessorySetupBluetoothCompanyIdentifiers",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSAccessorySetupBluetoothCompanyIdentifiers"
        }
      ],
      "role": "symbol",
      "title": "NSAccessorySetupBluetoothCompanyIdentifiers",
      "titleStyle": "symbol",
      "type": "topic",
      "url": "/documentation/bundleresources/information-property-list/nsaccessorysetupbluetoothcompanyidentifiers"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSAccessorySetupBluetoothNames": {
      "abstract": [
        {
          "text": "An array of strings that represent the Bluetooth device names or substrings for accessories that your app configures.",
          "type": "text"
        }
      ],
      "ideTitle": "AccessorySetupKit - Bluetooth Names",
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSAccessorySetupBluetoothNames",
      "kind": "symbol",
      "name": "NSAccessorySetupBluetoothNames",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSAccessorySetupBluetoothNames"
        }
      ],
      "role": "symbol",
      "title": "NSAccessorySetupBluetoothNames",
      "titleStyle": "symbol",
      "type": "topic",
      "url": "/documentation/bundleresources/information-property-list/nsaccessorysetupbluetoothnames"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSAccessorySetupBluetoothServices": {
      "abstract": [
        {
          "text": "An array of strings that represent the hexadecimal values of Bluetooth SIG-defined services or custom services for accessories your app configures.",
          "type": "text"
        }
      ],
      "ideTitle": "AccessorySetupKit - Bluetooth Services",
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSAccessorySetupBluetoothServices",
      "kind": "symbol",
      "name": "NSAccessorySetupBluetoothServices",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSAccessorySetupBluetoothServices"
        }
      ],
      "role": "symbol",
      "title": "NSAccessorySetupBluetoothServices",
      "titleStyle": "symbol",
      "type": "topic",
      "url": "/documentation/bundleresources/information-property-list/nsaccessorysetupbluetoothservices"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSAccessorySetupSupports": {
      "abstract": [
        {
          "text": "An array of strings that indicates the wireless technologies AccessorySetupKit uses when discovering and configuring accessories.",
          "type": "text"
        }
      ],
      "ideTitle": "AccessorySetupKit - Supports",
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSAccessorySetupSupports",
      "kind": "symbol",
      "name": "NSAccessorySetupSupports",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSAccessorySetupSupports"
        }
      ],
      "role": "symbol",
      "title": "NSAccessorySetupSupports",
      "titleStyle": "symbol",
      "type": "topic",
      "url": "/documentation/bundleresources/information-property-list/nsaccessorysetupsupports"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Accessories",
      "generated": true,
      "identifiers": [
        "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSAccessorySetupSupports",
        "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSAccessorySetupBluetoothCompanyIdentifiers",
        "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSAccessorySetupBluetoothNames"
      ],
      "title": "Accessories"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "18.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "18.0",
              "name": "iPadOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Property List Key"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "NSAccessorySetupBluetoothServices"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "typealias"
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSAccessorySetupBluetoothServices"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.bundleresources/documentation/BundleResources",
                "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Accessories",
              "generated": true,
              "identifiers": [
                "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSAccessorySetupSupports",
                "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSAccessorySetupBluetoothCompanyIdentifiers",
                "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSAccessorySetupBluetoothNames"
              ],
              "title": "Accessories"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List/title",
          "value": "Information Property List"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "Information Property List"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1NSAccessorySetupSupports/title",
          "value": "NSAccessorySetupSupports"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1NSAccessorySetupSupports/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSAccessorySetupSupports"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1NSAccessorySetupBluetoothNames/title",
          "value": "NSAccessorySetupBluetoothNames"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1NSAccessorySetupBluetoothNames/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSAccessorySetupBluetoothNames"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1NSAccessorySetupBluetoothServices/title",
          "value": "NSAccessorySetupBluetoothServices"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1NSAccessorySetupBluetoothServices/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSAccessorySetupBluetoothServices"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1NSAccessorySetupBluetoothCompanyIdentifiers/title",
          "value": "NSAccessorySetupBluetoothCompanyIdentifiers"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1NSAccessorySetupBluetoothCompanyIdentifiers/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSAccessorySetupBluetoothCompanyIdentifiers"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/bundleresources/information-property-list/nsaccessorysetupbluetoothservices"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/bundleresources/information-property-list/nsaccessorysetupbluetoothservices"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
