{
  "abstract": [
    {
      "text": "The URL where Private Click Measurement and SKAdNetwork send attribution information.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.bundleresources/documentation/BundleResources",
        "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSAdvertisingAttributionReportEndpoint"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "plist:Information_Property_List.NSAdvertisingAttributionReportEndpoint",
    "modules": [
      {
        "name": "Bundle Resources"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "NSAdvertisingAttributionReportEndpoint"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "14.5",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "14.5",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Property List Key",
    "symbolKind": "typealias",
    "title": "NSAdvertisingAttributionReportEndpoint"
  },
  "primaryContentSections": [
    {
      "details": {
        "name": "NSAdvertisingAttributionReportEndpoint",
        "platforms": [],
        "titleStyle": "symbol",
        "value": [
          {
            "arrayMode": false,
            "baseType": "string"
          }
        ]
      },
      "kind": "details",
      "title": "Details"
    },
    {
      "content": [
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "This key is a string that contains a valid URL containing your domain name. Provide a string in the format ",
              "type": "text"
            },
            {
              "code": "“https://example.com”",
              "type": "codeVoice"
            },
            {
              "text": ", where you replace ",
              "type": "text"
            },
            {
              "code": "example",
              "type": "codeVoice"
            },
            {
              "text": " with your domain name. Include this key in your app for the following two uses:",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "items": [
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "To specify where the system sends event attribution data it receives from launched websites that support Private Click Measurement (PCM). PCM won’t work if your app doesn’t include this key.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "To specify where the system sends a copy of the winning install-validation postback to the advertised app’s developer, for apps that are advertised using the ",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.documentation/documentation/StoreKit/SKAdNetwork",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": " API. Including this key is optional.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            }
          ],
          "type": "unorderedList"
        },
        {
          "inlineContent": [
            {
              "text": "The system sends postbacks to a well-known URL it generates using the domain name you provide in the key. To receive the postbacks, configure your server to receive HTTPS POST messages at the following endpoints:",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "items": [
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "To receive PCM event attribution data: ",
                      "type": "text"
                    },
                    {
                      "code": "https://example.com/.well-known/private-click-measurement/report-attribution/",
                      "type": "codeVoice"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "To receive SKAdNetwork install-validation postbacks: ",
                      "type": "text"
                    },
                    {
                      "code": "https://example.com/.well-known/skadnetwork/report-attribution/",
                      "type": "codeVoice"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            }
          ],
          "type": "unorderedList"
        },
        {
          "inlineContent": [
            {
              "text": "Replace ",
              "type": "text"
            },
            {
              "code": "example.com",
              "type": "codeVoice"
            },
            {
              "text": " with your domain name. The system uses only the registrable part of the domain name, and ignores any subdomains.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "For more information about PCM and setting up a server to receive event attribution data, see ",
              "type": "text"
            },
            {
              "identifier": "https://webkit.org/blog/11529/introducing-private-click-measurement-pcm/",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ". For more information about configuring an advertised app to enable its developer to receive postbacks, see ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/StoreKit/configuring-an-advertised-app",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " and ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/StoreKit/SKAdNetwork",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ".",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "",
                  "type": "text"
                },
                {
                  "text": " ",
                  "type": "text"
                },
                {
                  "text": "Mac apps built with Mac Catalyst don’t support PCM.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "Note",
          "style": "note",
          "type": "aside"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.bundleresources/documentation/BundleResources": {
      "abstract": [
        {
          "text": "Resources located in an app, framework, or plugin bundle.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources",
      "kind": "symbol",
      "role": "collection",
      "title": "Bundle Resources",
      "type": "topic",
      "url": "/documentation/bundleresources"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List": {
      "abstract": [
        {
          "text": "A resource containing key-value pairs that identify and configure a bundle.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List",
      "kind": "symbol",
      "name": "Information Property List",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "Information Property List"
        }
      ],
      "role": "symbol",
      "title": "Information Property List",
      "titleStyle": "symbol",
      "type": "topic",
      "url": "/documentation/bundleresources/information-property-list"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/CKSharingSupported": {
      "abstract": [
        {
          "text": "A Boolean value that indicates your app supports CloudKit Sharing.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/CKSharingSupported",
      "kind": "symbol",
      "name": "CKSharingSupported",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CKSharingSupported"
        }
      ],
      "role": "symbol",
      "title": "CKSharingSupported",
      "titleStyle": "symbol",
      "type": "topic",
      "url": "/documentation/bundleresources/information-property-list/cksharingsupported"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSAdvertisingAttributionReportEndpoint": {
      "abstract": [
        {
          "text": "The URL where Private Click Measurement and SKAdNetwork send attribution information.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSAdvertisingAttributionReportEndpoint",
      "kind": "symbol",
      "name": "NSAdvertisingAttributionReportEndpoint",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSAdvertisingAttributionReportEndpoint"
        }
      ],
      "role": "symbol",
      "title": "NSAdvertisingAttributionReportEndpoint",
      "titleStyle": "symbol",
      "type": "topic",
      "url": "/documentation/bundleresources/information-property-list/nsadvertisingattributionreportendpoint"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSAppTransportSecurity": {
      "abstract": [
        {
          "text": "A description of changes made to the default security for HTTP connections.",
          "type": "text"
        }
      ],
      "ideTitle": "App Transport Security Settings",
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSAppTransportSecurity",
      "kind": "symbol",
      "name": "NSAppTransportSecurity",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSAppTransportSecurity"
        }
      ],
      "role": "symbol",
      "title": "NSAppTransportSecurity",
      "titleStyle": "symbol",
      "type": "topic",
      "url": "/documentation/bundleresources/information-property-list/nsapptransportsecurity"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSBonjourServices": {
      "abstract": [
        {
          "text": "Bonjour service types browsed by the app.",
          "type": "text"
        }
      ],
      "ideTitle": "Bonjour services",
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSBonjourServices",
      "kind": "symbol",
      "name": "NSBonjourServices",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSBonjourServices"
        }
      ],
      "role": "symbol",
      "title": "NSBonjourServices",
      "titleStyle": "symbol",
      "type": "topic",
      "url": "/documentation/bundleresources/information-property-list/nsbonjourservices"
    },
    "doc://com.apple.documentation/documentation/StoreKit/SKAdNetwork": {
      "abstract": [
        {
          "text": "A class that validates advertisement-driven app installations.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SKAdNetwork"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/StoreKit/SKAdNetwork",
      "kind": "symbol",
      "role": "symbol",
      "title": "SKAdNetwork",
      "type": "topic",
      "url": "/documentation/StoreKit/SKAdNetwork"
    },
    "doc://com.apple.documentation/documentation/StoreKit/configuring-an-advertised-app": {
      "abstract": [
        {
          "text": "Prepare an advertised app to participate in ad campaigns.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/StoreKit/configuring-an-advertised-app",
      "kind": "article",
      "role": "article",
      "title": "Configuring an advertised app",
      "type": "topic",
      "url": "/documentation/StoreKit/configuring-an-advertised-app"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "https://webkit.org/blog/11529/introducing-private-click-measurement-pcm/": {
      "identifier": "https://webkit.org/blog/11529/introducing-private-click-measurement-pcm/",
      "title": "Introducing Private Click Measurement",
      "titleInlineContent": [
        {
          "text": "Introducing Private Click Measurement",
          "type": "text"
        }
      ],
      "type": "link",
      "url": "https://webkit.org/blog/11529/introducing-private-click-measurement-pcm/"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Network",
      "generated": true,
      "identifiers": [
        "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSAppTransportSecurity",
        "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSBonjourServices",
        "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/CKSharingSupported"
      ],
      "title": "Network"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "14.5",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "14.5",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Property List Key"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "NSAdvertisingAttributionReportEndpoint"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "typealias"
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSAdvertisingAttributionReportEndpoint"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.bundleresources/documentation/BundleResources",
                "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Network",
              "generated": true,
              "identifiers": [
                "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSAppTransportSecurity",
                "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSBonjourServices",
                "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/CKSharingSupported"
              ],
              "title": "Network"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1CKSharingSupported/title",
          "value": "CKSharingSupported"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1CKSharingSupported/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CKSharingSupported"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1StoreKit~1SKAdNetwork/fragments",
          "value": [
            {
              "kind": "keyword",
              "text": "@interface"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "SKAdNetwork"
            },
            {
              "kind": "text",
              "text": " : "
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)NSObject",
              "text": "NSObject"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1NSBonjourServices/title",
          "value": "NSBonjourServices"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1NSBonjourServices/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSBonjourServices"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List/title",
          "value": "Information Property List"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "Information Property List"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1NSAppTransportSecurity/title",
          "value": "NSAppTransportSecurity"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1NSAppTransportSecurity/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSAppTransportSecurity"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1NSAdvertisingAttributionReportEndpoint/title",
          "value": "NSAdvertisingAttributionReportEndpoint"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1NSAdvertisingAttributionReportEndpoint/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSAdvertisingAttributionReportEndpoint"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/bundleresources/information-property-list/nsadvertisingattributionreportendpoint"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/bundleresources/information-property-list/nsadvertisingattributionreportendpoint"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
