{
  "abstract": [
    {
      "text": "A collection of keys that an App Clip uses to get additional capabilities.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.bundleresources/documentation/BundleResources",
        "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSAppClip"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "plist:Information_Property_List.NSAppClip",
    "modules": [
      {
        "name": "Bundle Resources"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "NSAppClip"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "14.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "14.0",
        "name": "iPadOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Property List Key",
    "symbolKind": "dictionary",
    "title": "NSAppClip"
  },
  "primaryContentSections": [
    {
      "details": {
        "ideTitle": "App Clip",
        "name": "NSAppClip",
        "platforms": [],
        "titleStyle": "symbol",
        "value": [
          {
            "arrayMode": false,
            "baseType": "object"
          }
        ]
      },
      "kind": "details",
      "title": "Details"
    }
  ],
  "references": {
    "doc://com.apple.bundleresources/documentation/BundleResources": {
      "abstract": [
        {
          "text": "Resources located in an app, framework, or plugin bundle.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources",
      "kind": "symbol",
      "role": "collection",
      "title": "Bundle Resources",
      "type": "topic",
      "url": "/documentation/bundleresources"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List": {
      "abstract": [
        {
          "text": "A resource containing key-value pairs that identify and configure a bundle.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List",
      "kind": "symbol",
      "name": "Information Property List",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "Information Property List"
        }
      ],
      "role": "symbol",
      "title": "Information Property List",
      "titleStyle": "symbol",
      "type": "topic",
      "url": "/documentation/bundleresources/information-property-list"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSAppClip": {
      "abstract": [
        {
          "text": "A collection of keys that an App Clip uses to get additional capabilities.",
          "type": "text"
        }
      ],
      "ideTitle": "App Clip",
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSAppClip",
      "kind": "symbol",
      "name": "NSAppClip",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSAppClip"
        }
      ],
      "role": "symbol",
      "title": "NSAppClip",
      "titleStyle": "symbol",
      "type": "topic",
      "url": "/documentation/bundleresources/information-property-list/nsappclip"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSAppClip/NSAppClipRequestEphemeralUserNotification": {
      "abstract": [
        {
          "text": "A Boolean value that indicates whether an App Clip can schedule or receive notifications for a limited amount of time.",
          "type": "text"
        }
      ],
      "ideTitle": "Requests ephemeral user notifications",
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSAppClip/NSAppClipRequestEphemeralUserNotification",
      "kind": "symbol",
      "name": "NSAppClipRequestEphemeralUserNotification",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSAppClipRequestEphemeralUserNotification"
        }
      ],
      "role": "symbol",
      "title": "NSAppClipRequestEphemeralUserNotification",
      "titleStyle": "symbol",
      "type": "topic",
      "url": "/documentation/bundleresources/information-property-list/nsappclip/nsappcliprequestephemeralusernotification"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSAppClip/NSAppClipRequestLocationConfirmation": {
      "abstract": [
        {
          "text": "A Boolean value that indicates whether an App Clip can confirm the user’s location.",
          "type": "text"
        }
      ],
      "ideTitle": "Requests location confirmation",
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSAppClip/NSAppClipRequestLocationConfirmation",
      "kind": "symbol",
      "name": "NSAppClipRequestLocationConfirmation",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSAppClipRequestLocationConfirmation"
        }
      ],
      "role": "symbol",
      "title": "NSAppClipRequestLocationConfirmation",
      "titleStyle": "symbol",
      "type": "topic",
      "url": "/documentation/bundleresources/information-property-list/nsappclip/nsappcliprequestlocationconfirmation"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "topicSections": [
    {
      "anchor": "Scheduling-and-Receiving-Temporary-Notifications",
      "identifiers": [
        "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSAppClip/NSAppClipRequestEphemeralUserNotification"
      ],
      "title": "Scheduling and Receiving Temporary Notifications"
    },
    {
      "anchor": "Verifying-Location",
      "identifiers": [
        "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSAppClip/NSAppClipRequestLocationConfirmation"
      ],
      "title": "Verifying Location"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "14.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "14.0",
              "name": "iPadOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Property List Key"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "NSAppClip"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "dictionary"
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSAppClip"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.bundleresources/documentation/BundleResources",
                "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Scheduling-and-Receiving-Temporary-Notifications",
              "identifiers": [
                "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSAppClip/NSAppClipRequestEphemeralUserNotification"
              ],
              "title": "Scheduling and Receiving Temporary Notifications"
            },
            {
              "anchor": "Verifying-Location",
              "identifiers": [
                "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSAppClip/NSAppClipRequestLocationConfirmation"
              ],
              "title": "Verifying Location"
            }
          ]
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/seeAlsoSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List/title",
          "value": "Information Property List"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "Information Property List"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1NSAppClip/title",
          "value": "NSAppClip"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1NSAppClip/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSAppClip"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1NSAppClip~1NSAppClipRequestLocationConfirmation/title",
          "value": "NSAppClipRequestLocationConfirmation"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1NSAppClip~1NSAppClipRequestLocationConfirmation/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSAppClipRequestLocationConfirmation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1NSAppClip~1NSAppClipRequestEphemeralUserNotification/title",
          "value": "NSAppClipRequestEphemeralUserNotification"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1NSAppClip~1NSAppClipRequestEphemeralUserNotification/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSAppClipRequestEphemeralUserNotification"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/bundleresources/information-property-list/nsappclip"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/bundleresources/information-property-list/nsappclip"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
