{
  "abstract": [
    {
      "text": "The properties of an app extension.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.bundleresources/documentation/BundleResources",
        "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSExtension"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "plist:Information_Property_List.NSExtension",
    "modules": [
      {
        "name": "Bundle Resources"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "NSExtension"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "8.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "8.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.10",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Property List Key",
    "symbolKind": "dictionary",
    "title": "NSExtension"
  },
  "primaryContentSections": [
    {
      "details": {
        "name": "NSExtension",
        "platforms": [],
        "titleStyle": "symbol",
        "value": [
          {
            "arrayMode": false,
            "baseType": "object"
          }
        ]
      },
      "kind": "details",
      "title": "Details"
    }
  ],
  "references": {
    "doc://com.apple.bundleresources/documentation/BundleResources": {
      "abstract": [
        {
          "text": "Resources located in an app, framework, or plugin bundle.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources",
      "kind": "symbol",
      "role": "collection",
      "title": "Bundle Resources",
      "type": "topic",
      "url": "/documentation/bundleresources"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List": {
      "abstract": [
        {
          "text": "A resource containing key-value pairs that identify and configure a bundle.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List",
      "kind": "symbol",
      "name": "Information Property List",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "Information Property List"
        }
      ],
      "role": "symbol",
      "title": "Information Property List",
      "titleStyle": "symbol",
      "type": "topic",
      "url": "/documentation/bundleresources/information-property-list"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSExtension": {
      "abstract": [
        {
          "text": "The properties of an app extension.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSExtension",
      "kind": "symbol",
      "name": "NSExtension",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSExtension"
        }
      ],
      "role": "symbol",
      "title": "NSExtension",
      "titleStyle": "symbol",
      "type": "topic",
      "url": "/documentation/bundleresources/information-property-list/nsextension"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSExtension/ASAccountAuthenticationModificationPasswordGenerationRequirements": {
      "abstract": [
        {
          "text": "The rules the system satisfies when generating a strong password for your extension during an automatic upgrade.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSExtension/ASAccountAuthenticationModificationPasswordGenerationRequirements",
      "kind": "symbol",
      "name": "ASAccountAuthenticationModificationPasswordGenerationRequirements",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ASAccountAuthenticationModificationPasswordGenerationRequirements"
        }
      ],
      "role": "symbol",
      "title": "ASAccountAuthenticationModificationPasswordGenerationRequirements",
      "titleStyle": "symbol",
      "type": "topic",
      "url": "/documentation/bundleresources/information-property-list/nsextension/asaccountauthenticationmodificationpasswordgenerationrequirements"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSExtension/ASAccountAuthenticationModificationSupportsStrongPasswordChange": {
      "abstract": [
        {
          "text": "A Boolean value that indicates whether the extension supports upgrading a user’s password to a strong password.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSExtension/ASAccountAuthenticationModificationSupportsStrongPasswordChange",
      "kind": "symbol",
      "name": "ASAccountAuthenticationModificationSupportsStrongPasswordChange",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ASAccountAuthenticationModificationSupportsStrongPasswordChange"
        }
      ],
      "role": "symbol",
      "title": "ASAccountAuthenticationModificationSupportsStrongPasswordChange",
      "titleStyle": "symbol",
      "type": "topic",
      "url": "/documentation/bundleresources/information-property-list/nsextension/asaccountauthenticationmodificationsupportsstrongpasswordchange"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSExtension/ASAccountAuthenticationModificationSupportsUpgradeToSignInWithApple": {
      "abstract": [
        {
          "text": "A Boolean value that indicates whether the extension supports upgrading from using password authentication to using Sign in with Apple.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSExtension/ASAccountAuthenticationModificationSupportsUpgradeToSignInWithApple",
      "kind": "symbol",
      "name": "ASAccountAuthenticationModificationSupportsUpgradeToSignInWithApple",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ASAccountAuthenticationModificationSupportsUpgradeToSignInWithApple"
        }
      ],
      "role": "symbol",
      "title": "ASAccountAuthenticationModificationSupportsUpgradeToSignInWithApple",
      "titleStyle": "symbol",
      "type": "topic",
      "url": "/documentation/bundleresources/information-property-list/nsextension/asaccountauthenticationmodificationsupportsupgradetosigninwithapple"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSExtension/IntentsSupported": {
      "abstract": [
        {
          "text": "The names of the intents that an extension supports.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSExtension/IntentsSupported",
      "kind": "symbol",
      "name": "IntentsSupported",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "IntentsSupported"
        }
      ],
      "role": "symbol",
      "title": "IntentsSupported",
      "titleStyle": "symbol",
      "type": "topic",
      "url": "/documentation/bundleresources/information-property-list/nsextension/intentssupported"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSExtension/NSExtensionActionWantsFullScreenPresentation": {
      "abstract": [
        {
          "text": "A Boolean value indicating whether the Action extension is presented in full screen.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSExtension/NSExtensionActionWantsFullScreenPresentation",
      "kind": "symbol",
      "name": "NSExtensionActionWantsFullScreenPresentation",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSExtensionActionWantsFullScreenPresentation"
        }
      ],
      "role": "symbol",
      "title": "NSExtensionActionWantsFullScreenPresentation",
      "titleStyle": "symbol",
      "type": "topic",
      "url": "/documentation/bundleresources/information-property-list/nsextension/nsextensionactionwantsfullscreenpresentation"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSExtension/NSExtensionAttributes": {
      "abstract": [
        {
          "text": "Properties of an app extension.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSExtension/NSExtensionAttributes",
      "kind": "symbol",
      "name": "NSExtensionAttributes",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSExtensionAttributes"
        }
      ],
      "role": "symbol",
      "title": "NSExtensionAttributes",
      "titleStyle": "symbol",
      "type": "topic",
      "url": "/documentation/bundleresources/information-property-list/nsextension/nsextensionattributes"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSExtension/NSExtensionFileProviderActions": {
      "abstract": [
        {
          "text": "The custom actions for a File Provider extension.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSExtension/NSExtensionFileProviderActions",
      "kind": "symbol",
      "name": "NSExtensionFileProviderActions",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSExtensionFileProviderActions"
        }
      ],
      "role": "symbol",
      "title": "NSExtensionFileProviderActions",
      "titleStyle": "symbol",
      "type": "topic",
      "url": "/documentation/bundleresources/information-property-list/nsextension/nsextensionfileprovideractions"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSExtension/NSExtensionFileProviderDocumentGroup": {
      "abstract": [
        {
          "text": "The identifier of a shared container that can be accessed by a Document Picker extension and its associated File Provider extension.",
          "type": "text"
        }
      ],
      "ideTitle": "App group used for document storage",
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSExtension/NSExtensionFileProviderDocumentGroup",
      "kind": "symbol",
      "name": "NSExtensionFileProviderDocumentGroup",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSExtensionFileProviderDocumentGroup"
        }
      ],
      "role": "symbol",
      "title": "NSExtensionFileProviderDocumentGroup",
      "titleStyle": "symbol",
      "type": "topic",
      "url": "/documentation/bundleresources/information-property-list/nsextension/nsextensionfileproviderdocumentgroup"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSExtension/NSExtensionFileProviderDownloadPipelineDepth": {
      "abstract": [
        {
          "text": "The per-domain limit of concurrent calls that a file provider extension can make to fetch data from remote storage.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSExtension/NSExtensionFileProviderDownloadPipelineDepth",
      "kind": "symbol",
      "name": "NSExtensionFileProviderDownloadPipelineDepth",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSExtensionFileProviderDownloadPipelineDepth"
        }
      ],
      "role": "symbol",
      "title": "NSExtensionFileProviderDownloadPipelineDepth",
      "titleStyle": "symbol",
      "type": "topic",
      "url": "/documentation/bundleresources/information-property-list/nsextension/nsextensionfileproviderdownloadpipelinedepth"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSExtension/NSExtensionFileProviderSupportsEnumeration": {
      "abstract": [
        {
          "text": "A Boolean value that indicates whether a File Provider extension enumerates its content.",
          "type": "text"
        }
      ],
      "ideTitle": "File Provider supports Enumeration",
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSExtension/NSExtensionFileProviderSupportsEnumeration",
      "kind": "symbol",
      "name": "NSExtensionFileProviderSupportsEnumeration",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSExtensionFileProviderSupportsEnumeration"
        }
      ],
      "role": "symbol",
      "title": "NSExtensionFileProviderSupportsEnumeration",
      "titleStyle": "symbol",
      "type": "topic",
      "url": "/documentation/bundleresources/information-property-list/nsextension/nsextensionfileprovidersupportsenumeration"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSExtension/NSExtensionFileProviderUploadPipelineDepth": {
      "abstract": [
        {
          "text": "The per-domain limit of concurrent calls that a file provider extension can make to upload data.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSExtension/NSExtensionFileProviderUploadPipelineDepth",
      "kind": "symbol",
      "name": "NSExtensionFileProviderUploadPipelineDepth",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSExtensionFileProviderUploadPipelineDepth"
        }
      ],
      "role": "symbol",
      "title": "NSExtensionFileProviderUploadPipelineDepth",
      "titleStyle": "symbol",
      "type": "topic",
      "url": "/documentation/bundleresources/information-property-list/nsextension/nsextensionfileprovideruploadpipelinedepth"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSExtension/NSExtensionMainStoryboard": {
      "abstract": [
        {
          "text": "The name of the app extension’s main storyboard file.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSExtension/NSExtensionMainStoryboard",
      "kind": "symbol",
      "name": "NSExtensionMainStoryboard",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSExtensionMainStoryboard"
        }
      ],
      "role": "symbol",
      "title": "NSExtensionMainStoryboard",
      "titleStyle": "symbol",
      "type": "topic",
      "url": "/documentation/bundleresources/information-property-list/nsextension/nsextensionmainstoryboard"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSExtension/NSExtensionOverridesHostUIAppearance": {
      "abstract": [
        {
          "text": "A Boolean value indicating whether the app extension ignores appearance changes made by the host app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSExtension/NSExtensionOverridesHostUIAppearance",
      "kind": "symbol",
      "name": "NSExtensionOverridesHostUIAppearance",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSExtensionOverridesHostUIAppearance"
        }
      ],
      "role": "symbol",
      "title": "NSExtensionOverridesHostUIAppearance",
      "titleStyle": "symbol",
      "type": "topic",
      "url": "/documentation/bundleresources/information-property-list/nsextension/nsextensionoverrideshostuiappearance"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSExtension/NSExtensionPointIdentifier": {
      "abstract": [
        {
          "text": "The extension point that supports an app extension.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSExtension/NSExtensionPointIdentifier",
      "kind": "symbol",
      "name": "NSExtensionPointIdentifier",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSExtensionPointIdentifier"
        }
      ],
      "role": "symbol",
      "title": "NSExtensionPointIdentifier",
      "titleStyle": "symbol",
      "type": "topic",
      "url": "/documentation/bundleresources/information-property-list/nsextension/nsextensionpointidentifier"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSExtension/NSExtensionPrincipalClass": {
      "abstract": [
        {
          "text": "The custom class that implements an app extension’s primary view or functionality.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSExtension/NSExtensionPrincipalClass",
      "kind": "symbol",
      "name": "NSExtensionPrincipalClass",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSExtensionPrincipalClass"
        }
      ],
      "role": "symbol",
      "title": "NSExtensionPrincipalClass",
      "titleStyle": "symbol",
      "type": "topic",
      "url": "/documentation/bundleresources/information-property-list/nsextension/nsextensionprincipalclass"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSExtension/ProExtensionAttributes": {
      "abstract": [
        {
          "text": "A dictionary that specifies the minimum size of the floating window in which Final Cut Pro hosts the extension view.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSExtension/ProExtensionAttributes",
      "kind": "symbol",
      "name": "ProExtensionAttributes",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ProExtensionAttributes"
        }
      ],
      "role": "symbol",
      "title": "ProExtensionAttributes",
      "titleStyle": "symbol",
      "type": "topic",
      "url": "/documentation/bundleresources/information-property-list/nsextension/proextensionattributes"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSExtension/ProExtensionPrincipalClass": {
      "abstract": [
        {
          "text": "The name of the class with the principal implementation of your extension.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSExtension/ProExtensionPrincipalClass",
      "kind": "symbol",
      "name": "ProExtensionPrincipalClass",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ProExtensionPrincipalClass"
        }
      ],
      "role": "symbol",
      "title": "ProExtensionPrincipalClass",
      "titleStyle": "symbol",
      "type": "topic",
      "url": "/documentation/bundleresources/information-property-list/nsextension/proextensionprincipalclass"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSExtension/ProExtensionPrincipalViewControllerClass": {
      "abstract": [
        {
          "text": "The name of the principal view controller class of your extension.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSExtension/ProExtensionPrincipalViewControllerClass",
      "kind": "symbol",
      "name": "ProExtensionPrincipalViewControllerClass",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ProExtensionPrincipalViewControllerClass"
        }
      ],
      "role": "symbol",
      "title": "ProExtensionPrincipalViewControllerClass",
      "titleStyle": "symbol",
      "type": "topic",
      "url": "/documentation/bundleresources/information-property-list/nsextension/proextensionprincipalviewcontrollerclass"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSExtension/ProExtensionUUID": {
      "abstract": [
        {
          "text": "A UUID string that uniquely identifies your extension to the Compressor app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSExtension/ProExtensionUUID",
      "kind": "symbol",
      "name": "ProExtensionUUID",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ProExtensionUUID"
        }
      ],
      "role": "symbol",
      "title": "ProExtensionUUID",
      "titleStyle": "symbol",
      "type": "topic",
      "url": "/documentation/bundleresources/information-property-list/nsextension/proextensionuuid"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSExtension/SFSafariContentScript": {
      "abstract": [
        {
          "text": "The content scripts for a Safari extension.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSExtension/SFSafariContentScript",
      "kind": "symbol",
      "name": "SFSafariContentScript",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SFSafariContentScript"
        }
      ],
      "role": "symbol",
      "title": "SFSafariContentScript",
      "titleStyle": "symbol",
      "type": "topic",
      "url": "/documentation/bundleresources/information-property-list/nsextension/sfsafaricontentscript"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSExtension/SFSafariContextMenu": {
      "abstract": [
        {
          "text": "The context menu items for a Safari extension.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSExtension/SFSafariContextMenu",
      "kind": "symbol",
      "name": "SFSafariContextMenu",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SFSafariContextMenu"
        }
      ],
      "role": "symbol",
      "title": "SFSafariContextMenu",
      "titleStyle": "symbol",
      "type": "topic",
      "url": "/documentation/bundleresources/information-property-list/nsextension/sfsafaricontextmenu"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSExtension/SFSafariStyleSheet": {
      "abstract": [
        {
          "text": "The style sheet for a Safari extension.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSExtension/SFSafariStyleSheet",
      "kind": "symbol",
      "name": "SFSafariStyleSheet",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SFSafariStyleSheet"
        }
      ],
      "role": "symbol",
      "title": "SFSafariStyleSheet",
      "titleStyle": "symbol",
      "type": "topic",
      "url": "/documentation/bundleresources/information-property-list/nsextension/sfsafaristylesheet"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSExtension/SFSafariToolbarItem": {
      "abstract": [
        {
          "text": "The items to add to the toolbar for a Safari extension.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSExtension/SFSafariToolbarItem",
      "kind": "symbol",
      "name": "SFSafariToolbarItem",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SFSafariToolbarItem"
        }
      ],
      "role": "symbol",
      "title": "SFSafariToolbarItem",
      "titleStyle": "symbol",
      "type": "topic",
      "url": "/documentation/bundleresources/information-property-list/nsextension/sfsafaritoolbaritem"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSExtension/SFSafariWebsiteAccess": {
      "abstract": [
        {
          "text": "The webpages a Safari extension can access.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSExtension/SFSafariWebsiteAccess",
      "kind": "symbol",
      "name": "SFSafariWebsiteAccess",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SFSafariWebsiteAccess"
        }
      ],
      "role": "symbol",
      "title": "SFSafariWebsiteAccess",
      "titleStyle": "symbol",
      "type": "topic",
      "url": "/documentation/bundleresources/information-property-list/nsextension/sfsafariwebsiteaccess"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSServices": {
      "abstract": [
        {
          "text": "The services provided by an app.",
          "type": "text"
        }
      ],
      "ideTitle": "Services",
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSServices",
      "kind": "symbol",
      "name": "NSServices",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSServices"
        }
      ],
      "role": "symbol",
      "title": "NSServices",
      "titleStyle": "symbol",
      "type": "topic",
      "url": "/documentation/bundleresources/information-property-list/nsservices"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/UIApplicationShortcutWidget": {
      "abstract": [
        {
          "text": "The bundle ID of the widget that’s available as a Home screen quick action in apps that have more than one widget.",
          "type": "text"
        }
      ],
      "ideTitle": "Home Screen Widget",
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/UIApplicationShortcutWidget",
      "kind": "symbol",
      "name": "UIApplicationShortcutWidget",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIApplicationShortcutWidget"
        }
      ],
      "role": "symbol",
      "title": "UIApplicationShortcutWidget",
      "titleStyle": "symbol",
      "type": "topic",
      "url": "/documentation/bundleresources/information-property-list/uiapplicationshortcutwidget"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/WKExtensionDelegateClassName": {
      "abstract": [
        {
          "text": "The name of your watchOS app’s extension delegate.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/WKExtensionDelegateClassName",
      "kind": "symbol",
      "name": "WKExtensionDelegateClassName",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "WKExtensionDelegateClassName"
        }
      ],
      "role": "symbol",
      "title": "WKExtensionDelegateClassName",
      "titleStyle": "symbol",
      "type": "topic",
      "url": "/documentation/bundleresources/information-property-list/wkextensiondelegateclassname"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Extensions-and-services",
      "generated": true,
      "identifiers": [
        "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSServices",
        "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/WKExtensionDelegateClassName",
        "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/UIApplicationShortcutWidget"
      ],
      "title": "Extensions and services"
    }
  ],
  "topicSections": [
    {
      "anchor": "Appearance-and-Presentation",
      "identifiers": [
        "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSExtension/NSExtensionActionWantsFullScreenPresentation",
        "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSExtension/NSExtensionMainStoryboard",
        "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSExtension/NSExtensionOverridesHostUIAppearance",
        "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSExtension/NSExtensionPointIdentifier",
        "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSExtension/NSExtensionPrincipalClass"
      ],
      "title": "Appearance and Presentation"
    },
    {
      "anchor": "Attributes",
      "identifiers": [
        "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSExtension/NSExtensionAttributes"
      ],
      "title": "Attributes"
    },
    {
      "anchor": "Authentication",
      "identifiers": [
        "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSExtension/ASAccountAuthenticationModificationPasswordGenerationRequirements",
        "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSExtension/ASAccountAuthenticationModificationSupportsStrongPasswordChange",
        "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSExtension/ASAccountAuthenticationModificationSupportsUpgradeToSignInWithApple"
      ],
      "title": "Authentication"
    },
    {
      "anchor": "File-Provider",
      "identifiers": [
        "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSExtension/NSExtensionFileProviderActions",
        "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSExtension/NSExtensionFileProviderDocumentGroup",
        "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSExtension/NSExtensionFileProviderSupportsEnumeration",
        "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSExtension/NSExtensionFileProviderDownloadPipelineDepth",
        "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSExtension/NSExtensionFileProviderUploadPipelineDepth"
      ],
      "title": "File Provider"
    },
    {
      "anchor": "Intents",
      "identifiers": [
        "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSExtension/IntentsSupported"
      ],
      "title": "Intents"
    },
    {
      "anchor": "Professional-Video-Applications",
      "identifiers": [
        "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSExtension/ProExtensionAttributes",
        "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSExtension/ProExtensionPrincipalClass",
        "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSExtension/ProExtensionPrincipalViewControllerClass",
        "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSExtension/ProExtensionUUID"
      ],
      "title": "Professional Video Applications"
    },
    {
      "anchor": "SafariServices",
      "identifiers": [
        "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSExtension/SFSafariContentScript",
        "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSExtension/SFSafariContextMenu",
        "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSExtension/SFSafariStyleSheet",
        "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSExtension/SFSafariToolbarItem",
        "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSExtension/SFSafariWebsiteAccess"
      ],
      "title": "SafariServices"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "8.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "8.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.10",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Property List Key"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "NSExtension"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "dictionary"
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSExtension"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.bundleresources/documentation/BundleResources",
                "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Appearance-and-Presentation",
              "identifiers": [
                "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSExtension/NSExtensionActionWantsFullScreenPresentation",
                "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSExtension/NSExtensionMainStoryboard",
                "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSExtension/NSExtensionOverridesHostUIAppearance",
                "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSExtension/NSExtensionPointIdentifier",
                "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSExtension/NSExtensionPrincipalClass"
              ],
              "title": "Appearance and Presentation"
            },
            {
              "anchor": "Attributes",
              "identifiers": [
                "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSExtension/NSExtensionAttributes"
              ],
              "title": "Attributes"
            },
            {
              "anchor": "Authentication",
              "identifiers": [
                "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSExtension/ASAccountAuthenticationModificationPasswordGenerationRequirements",
                "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSExtension/ASAccountAuthenticationModificationSupportsStrongPasswordChange",
                "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSExtension/ASAccountAuthenticationModificationSupportsUpgradeToSignInWithApple"
              ],
              "title": "Authentication"
            },
            {
              "anchor": "File-Provider",
              "identifiers": [
                "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSExtension/NSExtensionFileProviderActions",
                "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSExtension/NSExtensionFileProviderDocumentGroup",
                "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSExtension/NSExtensionFileProviderSupportsEnumeration",
                "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSExtension/NSExtensionFileProviderDownloadPipelineDepth",
                "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSExtension/NSExtensionFileProviderUploadPipelineDepth"
              ],
              "title": "File Provider"
            },
            {
              "anchor": "Intents",
              "identifiers": [
                "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSExtension/IntentsSupported"
              ],
              "title": "Intents"
            },
            {
              "anchor": "Professional-Video-Applications",
              "identifiers": [
                "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSExtension/ProExtensionAttributes",
                "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSExtension/ProExtensionPrincipalClass",
                "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSExtension/ProExtensionPrincipalViewControllerClass",
                "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSExtension/ProExtensionUUID"
              ],
              "title": "Professional Video Applications"
            },
            {
              "anchor": "SafariServices",
              "identifiers": [
                "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSExtension/SFSafariContentScript",
                "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSExtension/SFSafariContextMenu",
                "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSExtension/SFSafariStyleSheet",
                "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSExtension/SFSafariToolbarItem",
                "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSExtension/SFSafariWebsiteAccess"
              ],
              "title": "SafariServices"
            }
          ]
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Extensions-and-services",
              "generated": true,
              "identifiers": [
                "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSServices",
                "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/WKExtensionDelegateClassName",
                "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/UIApplicationShortcutWidget"
              ],
              "title": "Extensions and services"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1UIApplicationShortcutWidget/title",
          "value": "UIApplicationShortcutWidget"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1UIApplicationShortcutWidget/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UIApplicationShortcutWidget"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1NSExtension~1NSExtensionMainStoryboard/title",
          "value": "NSExtensionMainStoryboard"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1NSExtension~1NSExtensionMainStoryboard/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSExtensionMainStoryboard"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1NSExtension~1NSExtensionPrincipalClass/title",
          "value": "NSExtensionPrincipalClass"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1NSExtension~1NSExtensionPrincipalClass/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSExtensionPrincipalClass"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1NSExtension/title",
          "value": "NSExtension"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1NSExtension/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSExtension"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1NSServices/title",
          "value": "NSServices"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1NSServices/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSServices"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1NSExtension~1NSExtensionFileProviderDownloadPipelineDepth/title",
          "value": "NSExtensionFileProviderDownloadPipelineDepth"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1NSExtension~1NSExtensionFileProviderDownloadPipelineDepth/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSExtensionFileProviderDownloadPipelineDepth"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1NSExtension~1SFSafariContextMenu/title",
          "value": "SFSafariContextMenu"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1NSExtension~1SFSafariContextMenu/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SFSafariContextMenu"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1NSExtension~1NSExtensionFileProviderSupportsEnumeration/title",
          "value": "NSExtensionFileProviderSupportsEnumeration"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1NSExtension~1NSExtensionFileProviderSupportsEnumeration/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSExtensionFileProviderSupportsEnumeration"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1NSExtension~1ProExtensionPrincipalViewControllerClass/title",
          "value": "ProExtensionPrincipalViewControllerClass"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1NSExtension~1ProExtensionPrincipalViewControllerClass/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "ProExtensionPrincipalViewControllerClass"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1NSExtension~1NSExtensionFileProviderDocumentGroup/title",
          "value": "NSExtensionFileProviderDocumentGroup"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1NSExtension~1NSExtensionFileProviderDocumentGroup/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSExtensionFileProviderDocumentGroup"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1NSExtension~1NSExtensionFileProviderActions/title",
          "value": "NSExtensionFileProviderActions"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1NSExtension~1NSExtensionFileProviderActions/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSExtensionFileProviderActions"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1NSExtension~1ProExtensionAttributes/title",
          "value": "ProExtensionAttributes"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1NSExtension~1ProExtensionAttributes/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "ProExtensionAttributes"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1NSExtension~1SFSafariWebsiteAccess/title",
          "value": "SFSafariWebsiteAccess"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1NSExtension~1SFSafariWebsiteAccess/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SFSafariWebsiteAccess"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1NSExtension~1ASAccountAuthenticationModificationSupportsStrongPasswordChange/title",
          "value": "ASAccountAuthenticationModificationSupportsStrongPasswordChange"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1NSExtension~1ASAccountAuthenticationModificationSupportsStrongPasswordChange/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "ASAccountAuthenticationModificationSupportsStrongPasswordChange"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1NSExtension~1ASAccountAuthenticationModificationSupportsUpgradeToSignInWithApple/title",
          "value": "ASAccountAuthenticationModificationSupportsUpgradeToSignInWithApple"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1NSExtension~1ASAccountAuthenticationModificationSupportsUpgradeToSignInWithApple/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "ASAccountAuthenticationModificationSupportsUpgradeToSignInWithApple"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1NSExtension~1ASAccountAuthenticationModificationPasswordGenerationRequirements/title",
          "value": "ASAccountAuthenticationModificationPasswordGenerationRequirements"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1NSExtension~1ASAccountAuthenticationModificationPasswordGenerationRequirements/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "ASAccountAuthenticationModificationPasswordGenerationRequirements"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1NSExtension~1ProExtensionPrincipalClass/title",
          "value": "ProExtensionPrincipalClass"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1NSExtension~1ProExtensionPrincipalClass/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "ProExtensionPrincipalClass"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1NSExtension~1SFSafariStyleSheet/title",
          "value": "SFSafariStyleSheet"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1NSExtension~1SFSafariStyleSheet/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SFSafariStyleSheet"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1NSExtension~1NSExtensionActionWantsFullScreenPresentation/title",
          "value": "NSExtensionActionWantsFullScreenPresentation"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1NSExtension~1NSExtensionActionWantsFullScreenPresentation/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSExtensionActionWantsFullScreenPresentation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List/title",
          "value": "Information Property List"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "Information Property List"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1NSExtension~1IntentsSupported/title",
          "value": "IntentsSupported"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1NSExtension~1IntentsSupported/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "IntentsSupported"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1NSExtension~1NSExtensionAttributes/title",
          "value": "NSExtensionAttributes"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1NSExtension~1NSExtensionAttributes/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSExtensionAttributes"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1NSExtension~1SFSafariToolbarItem/title",
          "value": "SFSafariToolbarItem"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1NSExtension~1SFSafariToolbarItem/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SFSafariToolbarItem"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1NSExtension~1SFSafariContentScript/title",
          "value": "SFSafariContentScript"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1NSExtension~1SFSafariContentScript/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SFSafariContentScript"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1NSExtension~1ProExtensionUUID/title",
          "value": "ProExtensionUUID"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1NSExtension~1ProExtensionUUID/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "ProExtensionUUID"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1NSExtension~1NSExtensionFileProviderUploadPipelineDepth/title",
          "value": "NSExtensionFileProviderUploadPipelineDepth"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1NSExtension~1NSExtensionFileProviderUploadPipelineDepth/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSExtensionFileProviderUploadPipelineDepth"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1NSExtension~1NSExtensionOverridesHostUIAppearance/title",
          "value": "NSExtensionOverridesHostUIAppearance"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1NSExtension~1NSExtensionOverridesHostUIAppearance/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSExtensionOverridesHostUIAppearance"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1NSExtension~1NSExtensionPointIdentifier/title",
          "value": "NSExtensionPointIdentifier"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1NSExtension~1NSExtensionPointIdentifier/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSExtensionPointIdentifier"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1WKExtensionDelegateClassName/title",
          "value": "WKExtensionDelegateClassName"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1WKExtensionDelegateClassName/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "WKExtensionDelegateClassName"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/bundleresources/information-property-list/nsextension"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/bundleresources/information-property-list/nsextension"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
