{
  "abstract": [
    {
      "text": "A message that tells the user why the app is requesting the ability to authenticate with Face ID.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.bundleresources/documentation/BundleResources",
        "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSFaceIDUsageDescription"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "plist:Information_Property_List.NSFaceIDUsageDescription",
    "modules": [
      {
        "name": "Bundle Resources"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "NSFaceIDUsageDescription"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "11.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "11.0",
        "name": "iPadOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Property List Key",
    "symbolKind": "typealias",
    "title": "NSFaceIDUsageDescription"
  },
  "primaryContentSections": [
    {
      "details": {
        "ideTitle": "Privacy - Face ID Usage Description",
        "name": "NSFaceIDUsageDescription",
        "platforms": [],
        "titleStyle": "symbol",
        "value": [
          {
            "arrayMode": false,
            "baseType": "string"
          }
        ]
      },
      "kind": "details",
      "title": "Details"
    },
    {
      "content": [
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "",
                  "type": "text"
                },
                {
                  "text": " ",
                  "type": "text"
                },
                {
                  "text": "This key is required if your app uses APIs that access Face ID. Also note that App Clips can’t use Face ID. For more information about functionality that’s unavailable to App Clips, see ",
                  "type": "text"
                },
                {
                  "identifier": "doc://com.apple.documentation/documentation/AppClip/choosing-the-right-functionality-for-your-app-clip",
                  "isActive": true,
                  "type": "reference"
                },
                {
                  "text": ".",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "Important",
          "style": "important",
          "type": "aside"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.bundleresources/documentation/BundleResources": {
      "abstract": [
        {
          "text": "Resources located in an app, framework, or plugin bundle.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources",
      "kind": "symbol",
      "role": "collection",
      "title": "Bundle Resources",
      "type": "topic",
      "url": "/documentation/bundleresources"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List": {
      "abstract": [
        {
          "text": "A resource containing key-value pairs that identify and configure a bundle.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List",
      "kind": "symbol",
      "name": "Information Property List",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "Information Property List"
        }
      ],
      "role": "symbol",
      "title": "Information Property List",
      "titleStyle": "symbol",
      "type": "topic",
      "url": "/documentation/bundleresources/information-property-list"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSFaceIDUsageDescription": {
      "abstract": [
        {
          "text": "A message that tells the user why the app is requesting the ability to authenticate with Face ID.",
          "type": "text"
        }
      ],
      "ideTitle": "Privacy - Face ID Usage Description",
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSFaceIDUsageDescription",
      "kind": "symbol",
      "name": "NSFaceIDUsageDescription",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSFaceIDUsageDescription"
        }
      ],
      "role": "symbol",
      "title": "NSFaceIDUsageDescription",
      "titleStyle": "symbol",
      "type": "topic",
      "url": "/documentation/bundleresources/information-property-list/nsfaceidusagedescription"
    },
    "doc://com.apple.documentation/documentation/AppClip/choosing-the-right-functionality-for-your-app-clip": {
      "abstract": [
        {
          "text": "Review frameworks available to App Clips and identify functionality that makes a great App Clip.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/AppClip/choosing-the-right-functionality-for-your-app-clip",
      "kind": "article",
      "role": "article",
      "title": "Choosing the right functionality for your App Clip",
      "type": "topic",
      "url": "/documentation/AppClip/choosing-the-right-functionality-for-your-app-clip"
    },
    "doc://com.apple.documentation/documentation/LocalAuthentication/logging-a-user-into-your-app-with-face-id-or-touch-id": {
      "abstract": [
        {
          "text": "Supplement your own authentication scheme with biometric authentication, making it easy for users to access sensitive parts of your app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/LocalAuthentication/logging-a-user-into-your-app-with-face-id-or-touch-id",
      "kind": "article",
      "role": "sampleCode",
      "title": "Logging a User into Your App with Face ID or Touch ID",
      "type": "topic",
      "url": "/documentation/LocalAuthentication/logging-a-user-into-your-app-with-face-id-or-touch-id"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Face-ID",
      "generated": true,
      "identifiers": [
        "doc://com.apple.documentation/documentation/LocalAuthentication/logging-a-user-into-your-app-with-face-id-or-touch-id"
      ],
      "title": "Face ID"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "11.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "11.0",
              "name": "iPadOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Property List Key"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "NSFaceIDUsageDescription"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "typealias"
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSFaceIDUsageDescription"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.bundleresources/documentation/BundleResources",
                "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Face-ID",
              "generated": true,
              "identifiers": [
                "doc://com.apple.documentation/documentation/LocalAuthentication/logging-a-user-into-your-app-with-face-id-or-touch-id"
              ],
              "title": "Face ID"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1NSFaceIDUsageDescription/title",
          "value": "NSFaceIDUsageDescription"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1NSFaceIDUsageDescription/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSFaceIDUsageDescription"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List/title",
          "value": "Information Property List"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "Information Property List"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/bundleresources/information-property-list/nsfaceidusagedescription"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/bundleresources/information-property-list/nsfaceidusagedescription"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
