{
  "abstract": [
    {
      "text": "The clinical record data types that your app must get permission to read.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.bundleresources/documentation/BundleResources",
        "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSHealthRequiredReadAuthorizationTypeIdentifiers"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "plist:Information_Property_List.NSHealthRequiredReadAuthorizationTypeIdentifiers",
    "modules": [
      {
        "name": "Bundle Resources"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "NSHealthRequiredReadAuthorizationTypeIdentifiers"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "12.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "12.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Property List Key",
    "symbolKind": "typealias",
    "title": "NSHealthRequiredReadAuthorizationTypeIdentifiers"
  },
  "primaryContentSections": [
    {
      "details": {
        "name": "NSHealthRequiredReadAuthorizationTypeIdentifiers",
        "platforms": [],
        "titleStyle": "symbol",
        "value": [
          {
            "arrayMode": true,
            "baseType": "string "
          }
        ]
      },
      "kind": "details",
      "title": "Details"
    },
    {
      "content": [
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Use this key to indicate that your app requires access to specific clinical record data types to function properly. Set the value to an array of strings containing the type identifiers for your required types. For a list of type identifiers, see ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/HealthKit/HKClinicalTypeIdentifier",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ".",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "To protect the user’s privacy, you must specify three or more required clinical record types. If the user denies authorization to any of the types, authorization fails with an ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/HealthKit/HKError/Code/errorRequiredAuthorizationDenied",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " error. Your app is not told the record types to which the user denied access.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.bundleresources/documentation/BundleResources": {
      "abstract": [
        {
          "text": "Resources located in an app, framework, or plugin bundle.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources",
      "kind": "symbol",
      "role": "collection",
      "title": "Bundle Resources",
      "type": "topic",
      "url": "/documentation/bundleresources"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List": {
      "abstract": [
        {
          "text": "A resource containing key-value pairs that identify and configure a bundle.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List",
      "kind": "symbol",
      "name": "Information Property List",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "Information Property List"
        }
      ],
      "role": "symbol",
      "title": "Information Property List",
      "titleStyle": "symbol",
      "type": "topic",
      "url": "/documentation/bundleresources/information-property-list"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSHealthClinicalHealthRecordsShareUsageDescription": {
      "abstract": [
        {
          "text": "A message to the user that explains why the app requested permission to read clinical records.",
          "type": "text"
        }
      ],
      "ideTitle": "Privacy - Health Records Usage Description",
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSHealthClinicalHealthRecordsShareUsageDescription",
      "kind": "symbol",
      "name": "NSHealthClinicalHealthRecordsShareUsageDescription",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSHealthClinicalHealthRecordsShareUsageDescription"
        }
      ],
      "role": "symbol",
      "title": "NSHealthClinicalHealthRecordsShareUsageDescription",
      "titleStyle": "symbol",
      "type": "topic",
      "url": "/documentation/bundleresources/information-property-list/nshealthclinicalhealthrecordsshareusagedescription"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSHealthRequiredReadAuthorizationTypeIdentifiers": {
      "abstract": [
        {
          "text": "The clinical record data types that your app must get permission to read.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSHealthRequiredReadAuthorizationTypeIdentifiers",
      "kind": "symbol",
      "name": "NSHealthRequiredReadAuthorizationTypeIdentifiers",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSHealthRequiredReadAuthorizationTypeIdentifiers"
        }
      ],
      "role": "symbol",
      "title": "NSHealthRequiredReadAuthorizationTypeIdentifiers",
      "titleStyle": "symbol",
      "type": "topic",
      "url": "/documentation/bundleresources/information-property-list/nshealthrequiredreadauthorizationtypeidentifiers"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSHealthShareUsageDescription": {
      "abstract": [
        {
          "text": "A message to the user that explains why the app requested permission to read samples from the HealthKit store.",
          "type": "text"
        }
      ],
      "ideTitle": "Privacy - Health Share Usage Description",
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSHealthShareUsageDescription",
      "kind": "symbol",
      "name": "NSHealthShareUsageDescription",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSHealthShareUsageDescription"
        }
      ],
      "role": "symbol",
      "title": "NSHealthShareUsageDescription",
      "titleStyle": "symbol",
      "type": "topic",
      "url": "/documentation/bundleresources/information-property-list/nshealthshareusagedescription"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSHealthUpdateUsageDescription": {
      "abstract": [
        {
          "text": "A message to the user that explains why the app requested permission to save samples to the HealthKit store.",
          "type": "text"
        }
      ],
      "ideTitle": "Privacy - Health Update Usage Description",
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSHealthUpdateUsageDescription",
      "kind": "symbol",
      "name": "NSHealthUpdateUsageDescription",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSHealthUpdateUsageDescription"
        }
      ],
      "role": "symbol",
      "title": "NSHealthUpdateUsageDescription",
      "titleStyle": "symbol",
      "type": "topic",
      "url": "/documentation/bundleresources/information-property-list/nshealthupdateusagedescription"
    },
    "doc://com.apple.documentation/documentation/HealthKit/HKClinicalTypeIdentifier": {
      "abstract": [
        {
          "text": "A type identifier for the different categories of clinical records.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "HKClinicalTypeIdentifier"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/HealthKit/HKClinicalTypeIdentifier",
      "kind": "symbol",
      "role": "symbol",
      "title": "HKClinicalTypeIdentifier",
      "type": "topic",
      "url": "/documentation/HealthKit/HKClinicalTypeIdentifier"
    },
    "doc://com.apple.documentation/documentation/HealthKit/HKError/Code/errorRequiredAuthorizationDenied": {
      "abstract": [
        {
          "text": "The user hasn’t granted the application authorization to access all the required clinical record types.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "errorRequiredAuthorizationDenied"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/HealthKit/HKError/Code/errorRequiredAuthorizationDenied",
      "kind": "symbol",
      "role": "symbol",
      "title": "HKError.Code.errorRequiredAuthorizationDenied",
      "type": "topic",
      "url": "/documentation/HealthKit/HKError/Code/errorRequiredAuthorizationDenied"
    },
    "doc://com.apple.documentation/documentation/HealthKit/setting-up-healthkit": {
      "abstract": [
        {
          "text": "Set up and configure your HealthKit store.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/HealthKit/setting-up-healthkit",
      "kind": "article",
      "role": "article",
      "title": "Setting up HealthKit",
      "type": "topic",
      "url": "/documentation/HealthKit/setting-up-healthkit"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Health",
      "generated": true,
      "identifiers": [
        "doc://com.apple.documentation/documentation/HealthKit/setting-up-healthkit",
        "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSHealthClinicalHealthRecordsShareUsageDescription",
        "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSHealthShareUsageDescription",
        "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSHealthUpdateUsageDescription"
      ],
      "title": "Health"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "12.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "12.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Property List Key"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "NSHealthRequiredReadAuthorizationTypeIdentifiers"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "typealias"
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSHealthRequiredReadAuthorizationTypeIdentifiers"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.bundleresources/documentation/BundleResources",
                "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Health",
              "generated": true,
              "identifiers": [
                "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSHealthClinicalHealthRecordsShareUsageDescription",
                "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSHealthShareUsageDescription",
                "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSHealthUpdateUsageDescription"
              ],
              "title": "Health"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1NSHealthClinicalHealthRecordsShareUsageDescription/title",
          "value": "NSHealthClinicalHealthRecordsShareUsageDescription"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1NSHealthClinicalHealthRecordsShareUsageDescription/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSHealthClinicalHealthRecordsShareUsageDescription"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1NSHealthRequiredReadAuthorizationTypeIdentifiers/title",
          "value": "NSHealthRequiredReadAuthorizationTypeIdentifiers"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1NSHealthRequiredReadAuthorizationTypeIdentifiers/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSHealthRequiredReadAuthorizationTypeIdentifiers"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1HealthKit~1HKClinicalTypeIdentifier/fragments",
          "value": [
            {
              "kind": "keyword",
              "text": "typedef"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)NSString",
              "text": "NSString"
            },
            {
              "kind": "text",
              "text": " * "
            },
            {
              "kind": "identifier",
              "text": "HKClinicalTypeIdentifier"
            },
            {
              "kind": "text",
              "text": ";"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1NSHealthUpdateUsageDescription/title",
          "value": "NSHealthUpdateUsageDescription"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1NSHealthUpdateUsageDescription/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSHealthUpdateUsageDescription"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1HealthKit~1HKError~1Code~1errorRequiredAuthorizationDenied/title",
          "value": "HKErrorRequiredAuthorizationDenied"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1HealthKit~1HKError~1Code~1errorRequiredAuthorizationDenied/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HKErrorRequiredAuthorizationDenied"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1NSHealthShareUsageDescription/title",
          "value": "NSHealthShareUsageDescription"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1NSHealthShareUsageDescription/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSHealthShareUsageDescription"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List/title",
          "value": "Information Property List"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "Information Property List"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/bundleresources/information-property-list/nshealthrequiredreadauthorizationtypeidentifiers"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/bundleresources/information-property-list/nshealthrequiredreadauthorizationtypeidentifiers"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
