{
  "abstract": [
    {
      "text": "A Boolean value indicating whether the Cocoa app supports high-resolution displays.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.bundleresources/documentation/BundleResources",
        "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSHighResolutionCapable"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "plist:Information_Property_List.NSHighResolutionCapable",
    "modules": [
      {
        "name": "Bundle Resources"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "NSHighResolutionCapable"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "2.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "2.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.0",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "9.0",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "2.0",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Property List Key",
    "symbolKind": "typealias",
    "title": "NSHighResolutionCapable"
  },
  "primaryContentSections": [
    {
      "details": {
        "ideTitle": "High Resolution Capable",
        "name": "NSHighResolutionCapable",
        "platforms": [],
        "titleStyle": "symbol",
        "value": [
          {
            "arrayMode": false,
            "baseType": "boolean"
          }
        ]
      },
      "kind": "details",
      "title": "Details"
    }
  ],
  "references": {
    "doc://com.apple.bundleresources/documentation/BundleResources": {
      "abstract": [
        {
          "text": "Resources located in an app, framework, or plugin bundle.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources",
      "kind": "symbol",
      "role": "collection",
      "title": "Bundle Resources",
      "type": "topic",
      "url": "/documentation/bundleresources"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List": {
      "abstract": [
        {
          "text": "A resource containing key-value pairs that identify and configure a bundle.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List",
      "kind": "symbol",
      "name": "Information Property List",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "Information Property List"
        }
      ],
      "role": "symbol",
      "title": "Information Property List",
      "titleStyle": "symbol",
      "type": "topic",
      "url": "/documentation/bundleresources/information-property-list"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/GPUEjectPolicy": {
      "abstract": [
        {
          "text": "The preferred system action when an external GPU is connected from the system.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/GPUEjectPolicy",
      "kind": "symbol",
      "name": "GPUEjectPolicy",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GPUEjectPolicy"
        }
      ],
      "role": "symbol",
      "title": "GPUEjectPolicy",
      "titleStyle": "symbol",
      "type": "topic",
      "url": "/documentation/bundleresources/information-property-list/gpuejectpolicy"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/GPUSelectionPolicy": {
      "abstract": [
        {
          "text": "The app’s preference for whether it wants to use external graphics processors.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/GPUSelectionPolicy",
      "kind": "symbol",
      "name": "GPUSelectionPolicy",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GPUSelectionPolicy"
        }
      ],
      "role": "symbol",
      "title": "GPUSelectionPolicy",
      "titleStyle": "symbol",
      "type": "topic",
      "url": "/documentation/bundleresources/information-property-list/gpuselectionpolicy"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSHighResolutionCapable": {
      "abstract": [
        {
          "text": "A Boolean value indicating whether the Cocoa app supports high-resolution displays.",
          "type": "text"
        }
      ],
      "ideTitle": "High Resolution Capable",
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSHighResolutionCapable",
      "kind": "symbol",
      "name": "NSHighResolutionCapable",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSHighResolutionCapable"
        }
      ],
      "role": "symbol",
      "title": "NSHighResolutionCapable",
      "titleStyle": "symbol",
      "type": "topic",
      "url": "/documentation/bundleresources/information-property-list/nshighresolutioncapable"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSSupportsAutomaticGraphicsSwitching": {
      "abstract": [
        {
          "text": "A Boolean value indicating whether an OpenGL app may utilize the integrated GPU.",
          "type": "text"
        }
      ],
      "ideTitle": "Supports Automatic Graphics Switching",
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSSupportsAutomaticGraphicsSwitching",
      "kind": "symbol",
      "name": "NSSupportsAutomaticGraphicsSwitching",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSSupportsAutomaticGraphicsSwitching"
        }
      ],
      "role": "symbol",
      "title": "NSSupportsAutomaticGraphicsSwitching",
      "titleStyle": "symbol",
      "type": "topic",
      "url": "/documentation/bundleresources/information-property-list/nssupportsautomaticgraphicsswitching"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/UIAppSupportsHDR": {
      "abstract": [
        {
          "text": "A Boolean value that indicates whether the app supports HDR mode on Apple TV 4K.",
          "type": "text"
        }
      ],
      "ideTitle": "Supports HDR color mode",
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/UIAppSupportsHDR",
      "kind": "symbol",
      "name": "UIAppSupportsHDR",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIAppSupportsHDR"
        }
      ],
      "role": "symbol",
      "title": "UIAppSupportsHDR",
      "titleStyle": "symbol",
      "type": "topic",
      "url": "/documentation/bundleresources/information-property-list/uiappsupportshdr"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Graphics",
      "generated": true,
      "identifiers": [
        "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/UIAppSupportsHDR",
        "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSSupportsAutomaticGraphicsSwitching",
        "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/GPUEjectPolicy",
        "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/GPUSelectionPolicy"
      ],
      "title": "Graphics"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "2.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "2.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.0",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "9.0",
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "2.0",
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Property List Key"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "NSHighResolutionCapable"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "typealias"
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSHighResolutionCapable"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.bundleresources/documentation/BundleResources",
                "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Graphics",
              "generated": true,
              "identifiers": [
                "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/UIAppSupportsHDR",
                "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSSupportsAutomaticGraphicsSwitching",
                "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/GPUEjectPolicy",
                "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/GPUSelectionPolicy"
              ],
              "title": "Graphics"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1NSSupportsAutomaticGraphicsSwitching/title",
          "value": "NSSupportsAutomaticGraphicsSwitching"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1NSSupportsAutomaticGraphicsSwitching/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSSupportsAutomaticGraphicsSwitching"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List/title",
          "value": "Information Property List"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "Information Property List"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1GPUEjectPolicy/title",
          "value": "GPUEjectPolicy"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1GPUEjectPolicy/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "GPUEjectPolicy"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1NSHighResolutionCapable/title",
          "value": "NSHighResolutionCapable"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1NSHighResolutionCapable/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSHighResolutionCapable"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1UIAppSupportsHDR/title",
          "value": "UIAppSupportsHDR"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1UIAppSupportsHDR/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UIAppSupportsHDR"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1GPUSelectionPolicy/title",
          "value": "GPUSelectionPolicy"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1GPUSelectionPolicy/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "GPUSelectionPolicy"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/bundleresources/information-property-list/nshighresolutioncapable"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/bundleresources/information-property-list/nshighresolutioncapable"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
