{
  "abstract": [
    {
      "text": "A collection of messages that explain why the app is requesting temporary access to the user’s location.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.bundleresources/documentation/BundleResources",
        "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSLocationTemporaryUsageDescriptionDictionary"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "plist:Information_Property_List.NSLocationTemporaryUsageDescriptionDictionary",
    "modules": [
      {
        "name": "Bundle Resources"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "NSLocationTemporaryUsageDescriptionDictionary"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "14.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "14.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "11.0",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Property List Key",
    "symbolKind": "dictionary",
    "title": "NSLocationTemporaryUsageDescriptionDictionary"
  },
  "primaryContentSections": [
    {
      "details": {
        "ideTitle": "Privacy - Location Temporary Usage Description Dictionary",
        "name": "NSLocationTemporaryUsageDescriptionDictionary",
        "platforms": [],
        "titleStyle": "symbol",
        "value": [
          {
            "arrayMode": false,
            "baseType": "object"
          }
        ]
      },
      "kind": "details",
      "title": "Details"
    },
    {
      "content": [
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Use this key if your app needs temporary access to full accuracy location information. Provide a dictionary of messages that address different use cases, keyed by strings that you define. For example, if your app suggests nearby coffee shops in one part of the app, and finds nearby friends in another, you could include two entries:",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "identifier": "media-3729482",
              "type": "image"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "When you request access, select among the messages at run time by providing the associated key to the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/CoreLocation/CLLocationManager/requestTemporaryFullAccuracyAuthorization(withPurposeKey:)",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " method:",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "code": [
            "// Request location access to find coffee shops.",
            "manager.requestTemporaryFullAccuracyAuthorization(withPurposeKey: \"coffee\")"
          ],
          "syntax": "swift",
          "type": "codeListing"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.bundleresources/documentation/BundleResources": {
      "abstract": [
        {
          "text": "Resources located in an app, framework, or plugin bundle.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources",
      "kind": "symbol",
      "role": "collection",
      "title": "Bundle Resources",
      "type": "topic",
      "url": "/documentation/bundleresources"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List": {
      "abstract": [
        {
          "text": "A resource containing key-value pairs that identify and configure a bundle.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List",
      "kind": "symbol",
      "name": "Information Property List",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "Information Property List"
        }
      ],
      "role": "symbol",
      "title": "Information Property List",
      "titleStyle": "symbol",
      "type": "topic",
      "url": "/documentation/bundleresources/information-property-list"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSLocationAlwaysAndWhenInUseUsageDescription": {
      "abstract": [
        {
          "text": "A message that tells the user why the app is requesting access to the user’s location information at all times.",
          "type": "text"
        }
      ],
      "ideTitle": "Privacy - Location Always and When In Use Usage Description",
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSLocationAlwaysAndWhenInUseUsageDescription",
      "kind": "symbol",
      "name": "NSLocationAlwaysAndWhenInUseUsageDescription",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSLocationAlwaysAndWhenInUseUsageDescription"
        }
      ],
      "role": "symbol",
      "title": "NSLocationAlwaysAndWhenInUseUsageDescription",
      "titleStyle": "symbol",
      "type": "topic",
      "url": "/documentation/bundleresources/information-property-list/nslocationalwaysandwheninuseusagedescription"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSLocationAlwaysUsageDescription": {
      "abstract": [
        {
          "text": "A message that tells the user why the app is requesting access to the user’s location at all times.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "ideTitle": "Privacy - Location Always Usage Description",
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSLocationAlwaysUsageDescription",
      "kind": "symbol",
      "name": "NSLocationAlwaysUsageDescription",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSLocationAlwaysUsageDescription"
        }
      ],
      "role": "symbol",
      "title": "NSLocationAlwaysUsageDescription",
      "titleStyle": "symbol",
      "type": "topic",
      "url": "/documentation/bundleresources/information-property-list/nslocationalwaysusagedescription"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSLocationDefaultAccuracyReduced": {
      "abstract": [
        {
          "text": "A Boolean value that indicates whether the app requests reduced location accuracy by default.",
          "type": "text"
        }
      ],
      "ideTitle": "Privacy - Location Default Accuracy Reduced",
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSLocationDefaultAccuracyReduced",
      "kind": "symbol",
      "name": "NSLocationDefaultAccuracyReduced",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSLocationDefaultAccuracyReduced"
        }
      ],
      "role": "symbol",
      "title": "NSLocationDefaultAccuracyReduced",
      "titleStyle": "symbol",
      "type": "topic",
      "url": "/documentation/bundleresources/information-property-list/nslocationdefaultaccuracyreduced"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSLocationTemporaryUsageDescriptionDictionary": {
      "abstract": [
        {
          "text": "A collection of messages that explain why the app is requesting temporary access to the user’s location.",
          "type": "text"
        }
      ],
      "ideTitle": "Privacy - Location Temporary Usage Description Dictionary",
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSLocationTemporaryUsageDescriptionDictionary",
      "kind": "symbol",
      "name": "NSLocationTemporaryUsageDescriptionDictionary",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSLocationTemporaryUsageDescriptionDictionary"
        }
      ],
      "role": "symbol",
      "title": "NSLocationTemporaryUsageDescriptionDictionary",
      "titleStyle": "symbol",
      "type": "topic",
      "url": "/documentation/bundleresources/information-property-list/nslocationtemporaryusagedescriptiondictionary"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSLocationUsageDescription": {
      "abstract": [
        {
          "text": "A message that tells the user why the app is requesting access to the user’s location information.",
          "type": "text"
        }
      ],
      "ideTitle": "Privacy - Location Usage Description",
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSLocationUsageDescription",
      "kind": "symbol",
      "name": "NSLocationUsageDescription",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSLocationUsageDescription"
        }
      ],
      "role": "symbol",
      "title": "NSLocationUsageDescription",
      "titleStyle": "symbol",
      "type": "topic",
      "url": "/documentation/bundleresources/information-property-list/nslocationusagedescription"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSLocationWhenInUseUsageDescription": {
      "abstract": [
        {
          "text": "A message that tells the user why the app is requesting access to the user’s location information while the app is running in the foreground.",
          "type": "text"
        }
      ],
      "ideTitle": "Privacy - Location When In Use Usage Description",
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSLocationWhenInUseUsageDescription",
      "kind": "symbol",
      "name": "NSLocationWhenInUseUsageDescription",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSLocationWhenInUseUsageDescription"
        }
      ],
      "role": "symbol",
      "title": "NSLocationWhenInUseUsageDescription",
      "titleStyle": "symbol",
      "type": "topic",
      "url": "/documentation/bundleresources/information-property-list/nslocationwheninuseusagedescription"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSWidgetWantsLocation": {
      "abstract": [
        {
          "text": "A Boolean value that indicates a widget uses the user’s location information.",
          "type": "text"
        }
      ],
      "ideTitle": "Widget wants location",
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSWidgetWantsLocation",
      "kind": "symbol",
      "name": "NSWidgetWantsLocation",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSWidgetWantsLocation"
        }
      ],
      "role": "symbol",
      "title": "NSWidgetWantsLocation",
      "titleStyle": "symbol",
      "type": "topic",
      "url": "/documentation/bundleresources/information-property-list/nswidgetwantslocation"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/choosing-the-location-services-authorization-to-request": {
      "abstract": [
        {
          "text": "Determine the authorization your app needs to access location data.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/choosing-the-location-services-authorization-to-request",
      "kind": "article",
      "role": "article",
      "title": "Choosing the  Location Services Authorization to Request",
      "type": "topic",
      "url": "/documentation/bundleresources/choosing-the-location-services-authorization-to-request"
    },
    "doc://com.apple.documentation/documentation/CoreLocation/CLLocationManager/requestTemporaryFullAccuracyAuthorization(withPurposeKey:)": {
      "abstract": [
        {
          "text": "Requests permission to temporarily use location services with full accuracy.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "requestTemporaryFullAccuracyAuthorization"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "withPurposeKey"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "internalParam",
          "text": "purposeKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/CoreLocation/CLLocationManager/requestTemporaryFullAccuracyAuthorization(withPurposeKey:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "requestTemporaryFullAccuracyAuthorization(withPurposeKey:)",
      "type": "topic",
      "url": "/documentation/CoreLocation/CLLocationManager/requestTemporaryFullAccuracyAuthorization(withPurposeKey:)"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "media-3729482": {
      "alt": "A screenshot of the NSLocationTemporaryUsageDescriptionDictionary item in the Xcode property list editor showing two entries. The first entry has the key friends and a value that says your location is used to connect with nearby friends. The second entry has the key coffee and a value that says your location is used to find the closest coffee shop.",
      "identifier": "media-3729482",
      "type": "image",
      "variants": [
        {
          "traits": [
            "2x",
            "light"
          ],
          "url": "https://docs-assets.developer.apple.com/published/9f8690a62d7d5ae92fb5f59a3410620a/media-3729482@2x.png"
        }
      ]
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Location",
      "generated": true,
      "identifiers": [
        "doc://com.apple.bundleresources/documentation/BundleResources/choosing-the-location-services-authorization-to-request",
        "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSLocationAlwaysAndWhenInUseUsageDescription",
        "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSLocationUsageDescription",
        "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSLocationWhenInUseUsageDescription",
        "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSLocationAlwaysUsageDescription",
        "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSWidgetWantsLocation",
        "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSLocationDefaultAccuracyReduced"
      ],
      "title": "Location"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "14.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "14.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "11.0",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Property List Key"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "NSLocationTemporaryUsageDescriptionDictionary"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "dictionary"
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSLocationTemporaryUsageDescriptionDictionary"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.bundleresources/documentation/BundleResources",
                "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Location",
              "generated": true,
              "identifiers": [
                "doc://com.apple.bundleresources/documentation/BundleResources/choosing-the-location-services-authorization-to-request",
                "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSLocationAlwaysAndWhenInUseUsageDescription",
                "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSLocationUsageDescription",
                "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSLocationWhenInUseUsageDescription",
                "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSLocationAlwaysUsageDescription",
                "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSWidgetWantsLocation",
                "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSLocationDefaultAccuracyReduced"
              ],
              "title": "Location"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List/title",
          "value": "Information Property List"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "Information Property List"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1NSLocationAlwaysUsageDescription/title",
          "value": "NSLocationAlwaysUsageDescription"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1NSLocationAlwaysUsageDescription/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSLocationAlwaysUsageDescription"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1NSLocationWhenInUseUsageDescription/title",
          "value": "NSLocationWhenInUseUsageDescription"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1NSLocationWhenInUseUsageDescription/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSLocationWhenInUseUsageDescription"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1NSLocationDefaultAccuracyReduced/title",
          "value": "NSLocationDefaultAccuracyReduced"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1NSLocationDefaultAccuracyReduced/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSLocationDefaultAccuracyReduced"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1NSWidgetWantsLocation/title",
          "value": "NSWidgetWantsLocation"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1NSWidgetWantsLocation/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSWidgetWantsLocation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1CoreLocation~1CLLocationManager~1requestTemporaryFullAccuracyAuthorization(withPurposeKey:)/title",
          "value": "requestTemporaryFullAccuracyAuthorizationWithPurposeKey:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1CoreLocation~1CLLocationManager~1requestTemporaryFullAccuracyAuthorization(withPurposeKey:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- ("
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:v",
              "text": "void"
            },
            {
              "kind": "text",
              "text": ") "
            },
            {
              "kind": "identifier",
              "text": "requestTemporaryFullAccuracyAuthorizationWithPurposeKey:"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)NSString",
              "text": "NSString"
            },
            {
              "kind": "text",
              "text": " *) "
            },
            {
              "kind": "internalParam",
              "text": "purposeKey"
            },
            {
              "kind": "text",
              "text": ";"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1NSLocationTemporaryUsageDescriptionDictionary/title",
          "value": "NSLocationTemporaryUsageDescriptionDictionary"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1NSLocationTemporaryUsageDescriptionDictionary/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSLocationTemporaryUsageDescriptionDictionary"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1NSLocationAlwaysAndWhenInUseUsageDescription/title",
          "value": "NSLocationAlwaysAndWhenInUseUsageDescription"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1NSLocationAlwaysAndWhenInUseUsageDescription/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSLocationAlwaysAndWhenInUseUsageDescription"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1NSLocationUsageDescription/title",
          "value": "NSLocationUsageDescription"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1NSLocationUsageDescription/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSLocationUsageDescription"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/bundleresources/information-property-list/nslocationtemporaryusagedescriptiondictionary"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/bundleresources/information-property-list/nslocationtemporaryusagedescriptiondictionary"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
