{
  "abstract": [
    {
      "text": "A Boolean value that indicates whether the app requests reduced location accuracy by default.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.bundleresources/documentation/BundleResources",
        "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSLocationDefaultAccuracyReduced"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "plist:Information_Property_List.NSLocationDefaultAccuracyReduced",
    "modules": [
      {
        "name": "Bundle Resources"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "NSLocationDefaultAccuracyReduced"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "14.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "14.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "7.0",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Property List Key",
    "symbolKind": "typealias",
    "title": "NSLocationDefaultAccuracyReduced"
  },
  "primaryContentSections": [
    {
      "details": {
        "ideTitle": "Privacy - Location Default Accuracy Reduced",
        "name": "NSLocationDefaultAccuracyReduced",
        "platforms": [],
        "titleStyle": "symbol",
        "value": [
          {
            "arrayMode": false,
            "baseType": "boolean"
          }
        ]
      },
      "kind": "details",
      "title": "Details"
    },
    {
      "attributes": [
        {
          "kind": "default",
          "value": "NO"
        }
      ],
      "kind": "attributes",
      "title": "Attributes"
    },
    {
      "content": [
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Include this key in your information property list to set your app’s default behavior for location accuracy when it calls the Core Location framework. Set the key value to ",
              "type": "text"
            },
            {
              "code": "true",
              "type": "codeVoice"
            },
            {
              "text": " to prompt the user for reduced accuracy by default; set it to ",
              "type": "text"
            },
            {
              "code": "false",
              "type": "codeVoice"
            },
            {
              "text": " to prompt for full location accuracy. If you don’t include that key in your ",
              "type": "text"
            },
            {
              "code": "Info.plist",
              "type": "codeVoice"
            },
            {
              "text": ", that’s equivalent to setting it to ",
              "type": "text"
            },
            {
              "code": "false",
              "type": "codeVoice"
            },
            {
              "text": ".",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "Include the key pair in your ",
              "type": "text"
            },
            {
              "code": "Info.plist",
              "type": "codeVoice"
            },
            {
              "text": " file as shown:",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "code": [
            "<!-- Info.plist -->",
            "<key>NSLocationDefaultAccuracyReduced</key>",
            "<true/>"
          ],
          "syntax": "xml",
          "type": "codeListing"
        },
        {
          "inlineContent": [
            {
              "text": "When this key is set to ",
              "type": "text"
            },
            {
              "code": "true",
              "type": "codeVoice"
            },
            {
              "text": ", all Core Location services (location updates, visit monitoring, significant location change, fence monitoring) receive service at the reduced-accuracy service level.  Users will see that your app is asking for reduced accuracy because the location authorization prompt will show a map with an approximate location, and your app will have the Precise Location toggled off in Settings > Privacy > Location Services . These indicators of an app’s improved privacy are ones that users may value.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "If you want to leverage the reduced-accuracy feature to improve privacy in a particular operation without setting this key, use the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/CoreLocation/CLLocationManager/desiredAccuracy",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " constant ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/CoreLocation/kCLLocationAccuracyReduced",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ". This constant causes ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/CoreLocation/CLLocationManager/startUpdatingLocation()",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " to deliver results as if the app were authorized for approximate location until you change the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/CoreLocation/CLLocationManager/desiredAccuracy",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " constant again.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "Setting ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSLocationDefaultAccuracyReduced",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " determines the default type of authorization your app gets, but users can override it any time in Settings. Users always control the level of location accuracy they want to share, and can change precision settings in Settings > Privacy > Location Services by selecting Precise Location for your app.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.bundleresources/documentation/BundleResources": {
      "abstract": [
        {
          "text": "Resources located in an app, framework, or plugin bundle.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources",
      "kind": "symbol",
      "role": "collection",
      "title": "Bundle Resources",
      "type": "topic",
      "url": "/documentation/bundleresources"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List": {
      "abstract": [
        {
          "text": "A resource containing key-value pairs that identify and configure a bundle.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List",
      "kind": "symbol",
      "name": "Information Property List",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "Information Property List"
        }
      ],
      "role": "symbol",
      "title": "Information Property List",
      "titleStyle": "symbol",
      "type": "topic",
      "url": "/documentation/bundleresources/information-property-list"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSLocationAlwaysAndWhenInUseUsageDescription": {
      "abstract": [
        {
          "text": "A message that tells the user why the app is requesting access to the user’s location information at all times.",
          "type": "text"
        }
      ],
      "ideTitle": "Privacy - Location Always and When In Use Usage Description",
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSLocationAlwaysAndWhenInUseUsageDescription",
      "kind": "symbol",
      "name": "NSLocationAlwaysAndWhenInUseUsageDescription",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSLocationAlwaysAndWhenInUseUsageDescription"
        }
      ],
      "role": "symbol",
      "title": "NSLocationAlwaysAndWhenInUseUsageDescription",
      "titleStyle": "symbol",
      "type": "topic",
      "url": "/documentation/bundleresources/information-property-list/nslocationalwaysandwheninuseusagedescription"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSLocationAlwaysUsageDescription": {
      "abstract": [
        {
          "text": "A message that tells the user why the app is requesting access to the user’s location at all times.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "ideTitle": "Privacy - Location Always Usage Description",
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSLocationAlwaysUsageDescription",
      "kind": "symbol",
      "name": "NSLocationAlwaysUsageDescription",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSLocationAlwaysUsageDescription"
        }
      ],
      "role": "symbol",
      "title": "NSLocationAlwaysUsageDescription",
      "titleStyle": "symbol",
      "type": "topic",
      "url": "/documentation/bundleresources/information-property-list/nslocationalwaysusagedescription"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSLocationDefaultAccuracyReduced": {
      "abstract": [
        {
          "text": "A Boolean value that indicates whether the app requests reduced location accuracy by default.",
          "type": "text"
        }
      ],
      "ideTitle": "Privacy - Location Default Accuracy Reduced",
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSLocationDefaultAccuracyReduced",
      "kind": "symbol",
      "name": "NSLocationDefaultAccuracyReduced",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSLocationDefaultAccuracyReduced"
        }
      ],
      "role": "symbol",
      "title": "NSLocationDefaultAccuracyReduced",
      "titleStyle": "symbol",
      "type": "topic",
      "url": "/documentation/bundleresources/information-property-list/nslocationdefaultaccuracyreduced"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSLocationTemporaryUsageDescriptionDictionary": {
      "abstract": [
        {
          "text": "A collection of messages that explain why the app is requesting temporary access to the user’s location.",
          "type": "text"
        }
      ],
      "ideTitle": "Privacy - Location Temporary Usage Description Dictionary",
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSLocationTemporaryUsageDescriptionDictionary",
      "kind": "symbol",
      "name": "NSLocationTemporaryUsageDescriptionDictionary",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSLocationTemporaryUsageDescriptionDictionary"
        }
      ],
      "role": "symbol",
      "title": "NSLocationTemporaryUsageDescriptionDictionary",
      "titleStyle": "symbol",
      "type": "topic",
      "url": "/documentation/bundleresources/information-property-list/nslocationtemporaryusagedescriptiondictionary"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSLocationUsageDescription": {
      "abstract": [
        {
          "text": "A message that tells the user why the app is requesting access to the user’s location information.",
          "type": "text"
        }
      ],
      "ideTitle": "Privacy - Location Usage Description",
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSLocationUsageDescription",
      "kind": "symbol",
      "name": "NSLocationUsageDescription",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSLocationUsageDescription"
        }
      ],
      "role": "symbol",
      "title": "NSLocationUsageDescription",
      "titleStyle": "symbol",
      "type": "topic",
      "url": "/documentation/bundleresources/information-property-list/nslocationusagedescription"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSLocationWhenInUseUsageDescription": {
      "abstract": [
        {
          "text": "A message that tells the user why the app is requesting access to the user’s location information while the app is running in the foreground.",
          "type": "text"
        }
      ],
      "ideTitle": "Privacy - Location When In Use Usage Description",
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSLocationWhenInUseUsageDescription",
      "kind": "symbol",
      "name": "NSLocationWhenInUseUsageDescription",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSLocationWhenInUseUsageDescription"
        }
      ],
      "role": "symbol",
      "title": "NSLocationWhenInUseUsageDescription",
      "titleStyle": "symbol",
      "type": "topic",
      "url": "/documentation/bundleresources/information-property-list/nslocationwheninuseusagedescription"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSWidgetWantsLocation": {
      "abstract": [
        {
          "text": "A Boolean value that indicates a widget uses the user’s location information.",
          "type": "text"
        }
      ],
      "ideTitle": "Widget wants location",
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSWidgetWantsLocation",
      "kind": "symbol",
      "name": "NSWidgetWantsLocation",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSWidgetWantsLocation"
        }
      ],
      "role": "symbol",
      "title": "NSWidgetWantsLocation",
      "titleStyle": "symbol",
      "type": "topic",
      "url": "/documentation/bundleresources/information-property-list/nswidgetwantslocation"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/choosing-the-location-services-authorization-to-request": {
      "abstract": [
        {
          "text": "Determine the authorization your app needs to access location data.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/choosing-the-location-services-authorization-to-request",
      "kind": "article",
      "role": "article",
      "title": "Choosing the  Location Services Authorization to Request",
      "type": "topic",
      "url": "/documentation/bundleresources/choosing-the-location-services-authorization-to-request"
    },
    "doc://com.apple.documentation/documentation/CoreLocation/CLLocationManager/desiredAccuracy": {
      "abstract": [
        {
          "text": "The accuracy of the location data that your app wants to receive.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "desiredAccuracy"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CLLocationAccuracy",
          "text": "CLLocationAccuracy"
        },
        {
          "kind": "text",
          "text": " { "
        },
        {
          "kind": "keyword",
          "text": "get"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "set"
        },
        {
          "kind": "text",
          "text": " }"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/CoreLocation/CLLocationManager/desiredAccuracy",
      "kind": "symbol",
      "role": "symbol",
      "title": "desiredAccuracy",
      "type": "topic",
      "url": "/documentation/CoreLocation/CLLocationManager/desiredAccuracy"
    },
    "doc://com.apple.documentation/documentation/CoreLocation/CLLocationManager/startUpdatingLocation()": {
      "abstract": [
        {
          "text": "Starts the generation of updates that report the user’s current location.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "startUpdatingLocation"
        },
        {
          "kind": "text",
          "text": "()"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/CoreLocation/CLLocationManager/startUpdatingLocation()",
      "kind": "symbol",
      "role": "symbol",
      "title": "startUpdatingLocation()",
      "type": "topic",
      "url": "/documentation/CoreLocation/CLLocationManager/startUpdatingLocation()"
    },
    "doc://com.apple.documentation/documentation/CoreLocation/kCLLocationAccuracyReduced": {
      "abstract": [
        {
          "text": "The level of accuracy used when an app isn’t authorized for full accuracy location data.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCLLocationAccuracyReduced"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CLLocationAccuracy",
          "text": "CLLocationAccuracy"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/CoreLocation/kCLLocationAccuracyReduced",
      "kind": "symbol",
      "role": "symbol",
      "title": "kCLLocationAccuracyReduced",
      "type": "topic",
      "url": "/documentation/CoreLocation/kCLLocationAccuracyReduced"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Location",
      "generated": true,
      "identifiers": [
        "doc://com.apple.bundleresources/documentation/BundleResources/choosing-the-location-services-authorization-to-request",
        "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSLocationAlwaysAndWhenInUseUsageDescription",
        "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSLocationUsageDescription",
        "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSLocationWhenInUseUsageDescription",
        "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSLocationTemporaryUsageDescriptionDictionary",
        "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSLocationAlwaysUsageDescription",
        "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSWidgetWantsLocation"
      ],
      "title": "Location"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "14.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "14.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "7.0",
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Property List Key"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "NSLocationDefaultAccuracyReduced"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "typealias"
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSLocationDefaultAccuracyReduced"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.bundleresources/documentation/BundleResources",
                "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Location",
              "generated": true,
              "identifiers": [
                "doc://com.apple.bundleresources/documentation/BundleResources/choosing-the-location-services-authorization-to-request",
                "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSLocationAlwaysAndWhenInUseUsageDescription",
                "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSLocationUsageDescription",
                "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSLocationWhenInUseUsageDescription",
                "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSLocationTemporaryUsageDescriptionDictionary",
                "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSLocationAlwaysUsageDescription",
                "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSWidgetWantsLocation"
              ],
              "title": "Location"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1CoreLocation~1CLLocationManager~1startUpdatingLocation()/title",
          "value": "startUpdatingLocation"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1CoreLocation~1CLLocationManager~1startUpdatingLocation()/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- ("
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:v",
              "text": "void"
            },
            {
              "kind": "text",
              "text": ") "
            },
            {
              "kind": "identifier",
              "text": "startUpdatingLocation"
            },
            {
              "kind": "text",
              "text": ";"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1NSLocationDefaultAccuracyReduced/title",
          "value": "NSLocationDefaultAccuracyReduced"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1NSLocationDefaultAccuracyReduced/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSLocationDefaultAccuracyReduced"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1CoreLocation~1kCLLocationAccuracyReduced/fragments",
          "value": [
            {
              "kind": "keyword",
              "text": "extern"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "keyword",
              "text": "const"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@CLLocationAccuracy",
              "text": "CLLocationAccuracy"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "kCLLocationAccuracyReduced"
            },
            {
              "kind": "text",
              "text": ";"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1NSLocationAlwaysAndWhenInUseUsageDescription/title",
          "value": "NSLocationAlwaysAndWhenInUseUsageDescription"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1NSLocationAlwaysAndWhenInUseUsageDescription/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSLocationAlwaysAndWhenInUseUsageDescription"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1NSLocationUsageDescription/title",
          "value": "NSLocationUsageDescription"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1NSLocationUsageDescription/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSLocationUsageDescription"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1NSLocationWhenInUseUsageDescription/title",
          "value": "NSLocationWhenInUseUsageDescription"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1NSLocationWhenInUseUsageDescription/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSLocationWhenInUseUsageDescription"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List/title",
          "value": "Information Property List"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "Information Property List"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1CoreLocation~1CLLocationManager~1desiredAccuracy/fragments",
          "value": [
            {
              "kind": "keyword",
              "text": "@property"
            },
            {
              "kind": "text",
              "text": " ("
            },
            {
              "kind": "keyword",
              "text": "nonatomic"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "kind": "keyword",
              "text": "assign"
            },
            {
              "kind": "text",
              "text": ") "
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@CLLocationAccuracy",
              "text": "CLLocationAccuracy"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "desiredAccuracy"
            },
            {
              "kind": "text",
              "text": ";"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1NSLocationTemporaryUsageDescriptionDictionary/title",
          "value": "NSLocationTemporaryUsageDescriptionDictionary"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1NSLocationTemporaryUsageDescriptionDictionary/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSLocationTemporaryUsageDescriptionDictionary"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1NSLocationAlwaysUsageDescription/title",
          "value": "NSLocationAlwaysUsageDescription"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1NSLocationAlwaysUsageDescription/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSLocationAlwaysUsageDescription"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1NSWidgetWantsLocation/title",
          "value": "NSWidgetWantsLocation"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1NSWidgetWantsLocation/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSWidgetWantsLocation"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/bundleresources/information-property-list/nslocationdefaultaccuracyreduced"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/bundleresources/information-property-list/nslocationdefaultaccuracyreduced"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
