{
  "abstract": [
    {
      "text": "An obsolete Boolean value indicating whether to require Certificate Transparency.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.bundleresources/documentation/BundleResources",
        "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSRequiresCertificateTransparency"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "plist:Information_Property_List.NSRequiresCertificateTransparency",
    "modules": [
      {
        "name": "Bundle Resources"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "NSRequiresCertificateTransparency"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "9.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "9.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.11",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Property List Key",
    "symbolKind": "typealias",
    "title": "NSRequiresCertificateTransparency"
  },
  "primaryContentSections": [
    {
      "details": {
        "name": "NSRequiresCertificateTransparency",
        "platforms": [],
        "titleStyle": "symbol",
        "value": [
          {
            "arrayMode": false,
            "baseType": "boolean"
          }
        ]
      },
      "kind": "details",
      "title": "Details"
    },
    {
      "attributes": [
        {
          "kind": "default",
          "value": "NO"
        }
      ],
      "kind": "attributes",
      "title": "Attributes"
    },
    {
      "content": [
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Certificate Transparency (CT) is a protocol that ATS can use to identify mistakenly or maliciously issued X.509 certificates. Earlier versions of the system used this key to enable or disable CT for a given domain. Specifically, CT requires a domain’s server certificates to have support from signed CT timestamps from at least two CT logs trusted by Apple. For more information about Certificate Transparency, see ",
              "type": "text"
            },
            {
              "identifier": "https://tools.ietf.org/html/rfc6962",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ".",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "The system now requires this behavior in all cases, making the key irrelevant.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "",
                  "type": "text"
                },
                {
                  "text": " ",
                  "type": "text"
                },
                {
                  "text": "Don’t use this key. The current system enforces this behavior, and new certificates can’t meet the requirement on older systems.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "Warning",
          "style": "warning",
          "type": "aside"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.bundleresources/documentation/BundleResources": {
      "abstract": [
        {
          "text": "Resources located in an app, framework, or plugin bundle.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources",
      "kind": "symbol",
      "role": "collection",
      "title": "Bundle Resources",
      "type": "topic",
      "url": "/documentation/bundleresources"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List": {
      "abstract": [
        {
          "text": "A resource containing key-value pairs that identify and configure a bundle.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List",
      "kind": "symbol",
      "name": "Information Property List",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "Information Property List"
        }
      ],
      "role": "symbol",
      "title": "Information Property List",
      "titleStyle": "symbol",
      "type": "topic",
      "url": "/documentation/bundleresources/information-property-list"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSExceptionAllowsInsecureHTTPLoads": {
      "abstract": [
        {
          "text": "A Boolean value indicating whether to allow insecure HTTP loads.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSExceptionAllowsInsecureHTTPLoads",
      "kind": "symbol",
      "name": "NSExceptionAllowsInsecureHTTPLoads",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSExceptionAllowsInsecureHTTPLoads"
        }
      ],
      "role": "symbol",
      "title": "NSExceptionAllowsInsecureHTTPLoads",
      "titleStyle": "symbol",
      "type": "topic",
      "url": "/documentation/bundleresources/information-property-list/nsexceptionallowsinsecurehttploads"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSExceptionMinimumTLSVersion": {
      "abstract": [
        {
          "text": "The minimum Transport Layer Security (TLS) version for network connections.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSExceptionMinimumTLSVersion",
      "kind": "symbol",
      "name": "NSExceptionMinimumTLSVersion",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSExceptionMinimumTLSVersion"
        }
      ],
      "role": "symbol",
      "title": "NSExceptionMinimumTLSVersion",
      "titleStyle": "symbol",
      "type": "topic",
      "url": "/documentation/bundleresources/information-property-list/nsexceptionminimumtlsversion"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSExceptionRequiresForwardSecrecy": {
      "abstract": [
        {
          "text": "A Boolean value indicating whether to override the perfect forward secrecy requirement.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSExceptionRequiresForwardSecrecy",
      "kind": "symbol",
      "name": "NSExceptionRequiresForwardSecrecy",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSExceptionRequiresForwardSecrecy"
        }
      ],
      "role": "symbol",
      "title": "NSExceptionRequiresForwardSecrecy",
      "titleStyle": "symbol",
      "type": "topic",
      "url": "/documentation/bundleresources/information-property-list/nsexceptionrequiresforwardsecrecy"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSRequiresCertificateTransparency": {
      "abstract": [
        {
          "text": "An obsolete Boolean value indicating whether to require Certificate Transparency.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSRequiresCertificateTransparency",
      "kind": "symbol",
      "name": "NSRequiresCertificateTransparency",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSRequiresCertificateTransparency"
        }
      ],
      "role": "symbol",
      "title": "NSRequiresCertificateTransparency",
      "titleStyle": "symbol",
      "type": "topic",
      "url": "/documentation/bundleresources/information-property-list/nsrequirescertificatetransparency"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "https://tools.ietf.org/html/rfc6962": {
      "identifier": "https://tools.ietf.org/html/rfc6962",
      "title": "RFC 6962",
      "titleInlineContent": [
        {
          "text": "RFC 6962",
          "type": "text"
        }
      ],
      "type": "link",
      "url": "https://tools.ietf.org/html/rfc6962"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Exceptions",
      "generated": true,
      "identifiers": [
        "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSExceptionAllowsInsecureHTTPLoads",
        "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSExceptionMinimumTLSVersion",
        "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSExceptionRequiresForwardSecrecy"
      ],
      "title": "Exceptions"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "9.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "9.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.11",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Property List Key"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "NSRequiresCertificateTransparency"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "typealias"
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSRequiresCertificateTransparency"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.bundleresources/documentation/BundleResources",
                "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Exceptions",
              "generated": true,
              "identifiers": [
                "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSExceptionAllowsInsecureHTTPLoads",
                "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSExceptionMinimumTLSVersion",
                "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSExceptionRequiresForwardSecrecy"
              ],
              "title": "Exceptions"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1NSRequiresCertificateTransparency/title",
          "value": "NSRequiresCertificateTransparency"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1NSRequiresCertificateTransparency/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSRequiresCertificateTransparency"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1NSExceptionMinimumTLSVersion/title",
          "value": "NSExceptionMinimumTLSVersion"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1NSExceptionMinimumTLSVersion/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSExceptionMinimumTLSVersion"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List/title",
          "value": "Information Property List"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "Information Property List"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1NSExceptionAllowsInsecureHTTPLoads/title",
          "value": "NSExceptionAllowsInsecureHTTPLoads"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1NSExceptionAllowsInsecureHTTPLoads/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSExceptionAllowsInsecureHTTPLoads"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1NSExceptionRequiresForwardSecrecy/title",
          "value": "NSExceptionRequiresForwardSecrecy"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1NSExceptionRequiresForwardSecrecy/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSExceptionRequiresForwardSecrecy"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/bundleresources/information-property-list/nsrequirescertificatetransparency"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/bundleresources/information-property-list/nsrequirescertificatetransparency"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
