{
  "abstract": [
    {
      "text": "The services provided by an app.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.bundleresources/documentation/BundleResources",
        "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSServices"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "plist:Information_Property_List.NSServices",
    "modules": [
      {
        "name": "Bundle Resources"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "NSServices"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.0",
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Property List Key",
    "symbolKind": "dictionary",
    "title": "NSServices"
  },
  "primaryContentSections": [
    {
      "details": {
        "ideTitle": "Services",
        "name": "NSServices",
        "platforms": [],
        "titleStyle": "symbol",
        "value": [
          {
            "arrayMode": true,
            "baseType": "dictionary "
          }
        ]
      },
      "kind": "details",
      "title": "Details"
    }
  ],
  "references": {
    "doc://com.apple.bundleresources/documentation/BundleResources": {
      "abstract": [
        {
          "text": "Resources located in an app, framework, or plugin bundle.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources",
      "kind": "symbol",
      "role": "collection",
      "title": "Bundle Resources",
      "type": "topic",
      "url": "/documentation/bundleresources"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List": {
      "abstract": [
        {
          "text": "A resource containing key-value pairs that identify and configure a bundle.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List",
      "kind": "symbol",
      "name": "Information Property List",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "Information Property List"
        }
      ],
      "role": "symbol",
      "title": "Information Property List",
      "titleStyle": "symbol",
      "type": "topic",
      "url": "/documentation/bundleresources/information-property-list"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSExtension": {
      "abstract": [
        {
          "text": "The properties of an app extension.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSExtension",
      "kind": "symbol",
      "name": "NSExtension",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSExtension"
        }
      ],
      "role": "symbol",
      "title": "NSExtension",
      "titleStyle": "symbol",
      "type": "topic",
      "url": "/documentation/bundleresources/information-property-list/nsextension"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSServices": {
      "abstract": [
        {
          "text": "The services provided by an app.",
          "type": "text"
        }
      ],
      "ideTitle": "Services",
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSServices",
      "kind": "symbol",
      "name": "NSServices",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSServices"
        }
      ],
      "role": "symbol",
      "title": "NSServices",
      "titleStyle": "symbol",
      "type": "topic",
      "url": "/documentation/bundleresources/information-property-list/nsservices"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSServices/NSKeyEquivalent": {
      "abstract": [
        {
          "text": "A keyboard shortcut that invokes the service menu command.",
          "type": "text"
        }
      ],
      "ideTitle": "Menu key equivalent",
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSServices/NSKeyEquivalent",
      "kind": "symbol",
      "name": "NSKeyEquivalent",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSKeyEquivalent"
        }
      ],
      "role": "symbol",
      "title": "NSKeyEquivalent",
      "titleStyle": "symbol",
      "type": "topic",
      "url": "/documentation/bundleresources/information-property-list/nsservices/nskeyequivalent"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSServices/NSMenuItem": {
      "abstract": [
        {
          "text": "Text for a Services menu item.",
          "type": "text"
        }
      ],
      "ideTitle": "Menu",
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSServices/NSMenuItem",
      "kind": "symbol",
      "name": "NSMenuItem",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSMenuItem"
        }
      ],
      "role": "symbol",
      "title": "NSMenuItem",
      "titleStyle": "symbol",
      "type": "topic",
      "url": "/documentation/bundleresources/information-property-list/nsservices/nsmenuitem"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSServices/NSMessage": {
      "abstract": [
        {
          "text": "An instance method that invokes the service.",
          "type": "text"
        }
      ],
      "ideTitle": "Instance method name",
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSServices/NSMessage",
      "kind": "symbol",
      "name": "NSMessage",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSMessage"
        }
      ],
      "role": "symbol",
      "title": "NSMessage",
      "titleStyle": "symbol",
      "type": "topic",
      "url": "/documentation/bundleresources/information-property-list/nsservices/nsmessage"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSServices/NSPortName": {
      "abstract": [
        {
          "text": "The port that the service monitors for incoming requests.",
          "type": "text"
        }
      ],
      "ideTitle": "Incoming service port name",
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSServices/NSPortName",
      "kind": "symbol",
      "name": "NSPortName",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSPortName"
        }
      ],
      "role": "symbol",
      "title": "NSPortName",
      "titleStyle": "symbol",
      "type": "topic",
      "url": "/documentation/bundleresources/information-property-list/nsservices/nsportname"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSServices/NSReturnTypes": {
      "abstract": [
        {
          "text": "The data types that the service returns.",
          "type": "text"
        }
      ],
      "ideTitle": "Return Types",
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSServices/NSReturnTypes",
      "kind": "symbol",
      "name": "NSReturnTypes",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSReturnTypes"
        }
      ],
      "role": "symbol",
      "title": "NSReturnTypes",
      "titleStyle": "symbol",
      "type": "topic",
      "url": "/documentation/bundleresources/information-property-list/nsservices/nsreturntypes"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSServices/NSSendTypes": {
      "abstract": [
        {
          "text": "The data types that the service can read.",
          "type": "text"
        }
      ],
      "ideTitle": "Send Types",
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSServices/NSSendTypes",
      "kind": "symbol",
      "name": "NSSendTypes",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSSendTypes"
        }
      ],
      "role": "symbol",
      "title": "NSSendTypes",
      "titleStyle": "symbol",
      "type": "topic",
      "url": "/documentation/bundleresources/information-property-list/nsservices/nssendtypes"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSServices/NSTimeout": {
      "abstract": [
        {
          "text": "The amount of time, in milliseconds, that the system waits for a response from the service.",
          "type": "text"
        }
      ],
      "ideTitle": "Timeout value (in milliseconds)",
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSServices/NSTimeout",
      "kind": "symbol",
      "name": "NSTimeout",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSTimeout"
        }
      ],
      "role": "symbol",
      "title": "NSTimeout",
      "titleStyle": "symbol",
      "type": "topic",
      "url": "/documentation/bundleresources/information-property-list/nsservices/nstimeout"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSServices/NSUserData": {
      "abstract": [
        {
          "text": "A service-specific string value.",
          "type": "text"
        }
      ],
      "ideTitle": "User Data",
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSServices/NSUserData",
      "kind": "symbol",
      "name": "NSUserData",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSUserData"
        }
      ],
      "role": "symbol",
      "title": "NSUserData",
      "titleStyle": "symbol",
      "type": "topic",
      "url": "/documentation/bundleresources/information-property-list/nsservices/nsuserdata"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/UIApplicationShortcutWidget": {
      "abstract": [
        {
          "text": "The bundle ID of the widget that’s available as a Home screen quick action in apps that have more than one widget.",
          "type": "text"
        }
      ],
      "ideTitle": "Home Screen Widget",
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/UIApplicationShortcutWidget",
      "kind": "symbol",
      "name": "UIApplicationShortcutWidget",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIApplicationShortcutWidget"
        }
      ],
      "role": "symbol",
      "title": "UIApplicationShortcutWidget",
      "titleStyle": "symbol",
      "type": "topic",
      "url": "/documentation/bundleresources/information-property-list/uiapplicationshortcutwidget"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/WKExtensionDelegateClassName": {
      "abstract": [
        {
          "text": "The name of your watchOS app’s extension delegate.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/WKExtensionDelegateClassName",
      "kind": "symbol",
      "name": "WKExtensionDelegateClassName",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "WKExtensionDelegateClassName"
        }
      ],
      "role": "symbol",
      "title": "WKExtensionDelegateClassName",
      "titleStyle": "symbol",
      "type": "topic",
      "url": "/documentation/bundleresources/information-property-list/wkextensiondelegateclassname"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Extensions-and-services",
      "generated": true,
      "identifiers": [
        "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSExtension",
        "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/WKExtensionDelegateClassName",
        "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/UIApplicationShortcutWidget"
      ],
      "title": "Extensions and services"
    }
  ],
  "topicSections": [
    {
      "anchor": "Invocation",
      "identifiers": [
        "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSServices/NSKeyEquivalent",
        "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSServices/NSMenuItem",
        "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSServices/NSMessage",
        "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSServices/NSPortName",
        "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSServices/NSTimeout"
      ],
      "title": "Invocation"
    },
    {
      "anchor": "Data",
      "identifiers": [
        "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSServices/NSReturnTypes",
        "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSServices/NSSendTypes",
        "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSServices/NSUserData"
      ],
      "title": "Data"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.0",
              "name": "macOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Property List Key"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "NSServices"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "dictionary"
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSServices"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.bundleresources/documentation/BundleResources",
                "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Invocation",
              "identifiers": [
                "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSServices/NSKeyEquivalent",
                "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSServices/NSMenuItem",
                "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSServices/NSMessage",
                "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSServices/NSPortName",
                "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSServices/NSTimeout"
              ],
              "title": "Invocation"
            },
            {
              "anchor": "Data",
              "identifiers": [
                "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSServices/NSReturnTypes",
                "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSServices/NSSendTypes",
                "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSServices/NSUserData"
              ],
              "title": "Data"
            }
          ]
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Extensions-and-services",
              "generated": true,
              "identifiers": [
                "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSExtension",
                "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/WKExtensionDelegateClassName",
                "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/UIApplicationShortcutWidget"
              ],
              "title": "Extensions and services"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1NSServices~1NSMenuItem/title",
          "value": "NSMenuItem"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1NSServices~1NSMenuItem/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSMenuItem"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1UIApplicationShortcutWidget/title",
          "value": "UIApplicationShortcutWidget"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1UIApplicationShortcutWidget/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UIApplicationShortcutWidget"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1NSServices~1NSKeyEquivalent/title",
          "value": "NSKeyEquivalent"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1NSServices~1NSKeyEquivalent/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSKeyEquivalent"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1NSServices~1NSUserData/title",
          "value": "NSUserData"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1NSServices~1NSUserData/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSUserData"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1NSServices~1NSReturnTypes/title",
          "value": "NSReturnTypes"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1NSServices~1NSReturnTypes/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSReturnTypes"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1NSExtension/title",
          "value": "NSExtension"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1NSExtension/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSExtension"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1NSServices~1NSPortName/title",
          "value": "NSPortName"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1NSServices~1NSPortName/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSPortName"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1NSServices~1NSTimeout/title",
          "value": "NSTimeout"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1NSServices~1NSTimeout/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSTimeout"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1NSServices~1NSMessage/title",
          "value": "NSMessage"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1NSServices~1NSMessage/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSMessage"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1WKExtensionDelegateClassName/title",
          "value": "WKExtensionDelegateClassName"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1WKExtensionDelegateClassName/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "WKExtensionDelegateClassName"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1NSServices~1NSSendTypes/title",
          "value": "NSSendTypes"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1NSServices~1NSSendTypes/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSSendTypes"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List/title",
          "value": "Information Property List"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "Information Property List"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1NSServices/title",
          "value": "NSServices"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1NSServices/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSServices"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/bundleresources/information-property-list/nsservices"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/bundleresources/information-property-list/nsservices"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
