{
  "abstract": [
    {
      "text": "A dictionary that includes keys for the specific information your app collects.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.bundleresources/documentation/BundleResources",
        "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSSensorKitUsageDetail"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "plist:Information_Property_List.NSSensorKitUsageDetail",
    "modules": [
      {
        "name": "Bundle Resources"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "NSSensorKitUsageDetail"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "14.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "14.0",
        "name": "iPadOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Property List Key",
    "symbolKind": "dictionary",
    "title": "NSSensorKitUsageDetail"
  },
  "primaryContentSections": [
    {
      "details": {
        "name": "NSSensorKitUsageDetail",
        "platforms": [],
        "titleStyle": "symbol",
        "value": [
          {
            "arrayMode": false,
            "baseType": "object"
          }
        ]
      },
      "kind": "details",
      "title": "Details"
    },
    {
      "content": [
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "When your app attempts to read sensor information for the first time on a user’s device, the system presents a sheet that describes the information your app collects. You specify which information by defining an ",
              "type": "text"
            },
            {
              "code": "Info.plist",
              "type": "codeVoice"
            },
            {
              "text": " key in this dictionary for each sensor your app uses, such as ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSSensorKitUsageDetail/SRSensorUsageAmbientLightSensor",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ". Users approve or deny your app’s ability to read private sensor information based on the description you provide for these properties.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "For more information, see ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/SensorKit/configuring-your-project-for-sensor-reading",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ".",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.bundleresources/documentation/BundleResources": {
      "abstract": [
        {
          "text": "Resources located in an app, framework, or plugin bundle.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources",
      "kind": "symbol",
      "role": "collection",
      "title": "Bundle Resources",
      "type": "topic",
      "url": "/documentation/bundleresources"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List": {
      "abstract": [
        {
          "text": "A resource containing key-value pairs that identify and configure a bundle.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List",
      "kind": "symbol",
      "name": "Information Property List",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "Information Property List"
        }
      ],
      "role": "symbol",
      "title": "Information Property List",
      "titleStyle": "symbol",
      "type": "topic",
      "url": "/documentation/bundleresources/information-property-list"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSSensorKitPrivacyPolicyURL": {
      "abstract": [
        {
          "text": "A hyperlink to a webpage that displays the privacy policy for your app’s research study.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSSensorKitPrivacyPolicyURL",
      "kind": "symbol",
      "name": "NSSensorKitPrivacyPolicyURL",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSSensorKitPrivacyPolicyURL"
        }
      ],
      "role": "symbol",
      "title": "NSSensorKitPrivacyPolicyURL",
      "titleStyle": "symbol",
      "type": "topic",
      "url": "/documentation/bundleresources/information-property-list/nssensorkitprivacypolicyurl"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSSensorKitUsageDescription": {
      "abstract": [
        {
          "text": "A short description of the purpose of your app’s research study.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSSensorKitUsageDescription",
      "kind": "symbol",
      "name": "NSSensorKitUsageDescription",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSSensorKitUsageDescription"
        }
      ],
      "role": "symbol",
      "title": "NSSensorKitUsageDescription",
      "titleStyle": "symbol",
      "type": "topic",
      "url": "/documentation/bundleresources/information-property-list/nssensorkitusagedescription"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSSensorKitUsageDetail": {
      "abstract": [
        {
          "text": "A dictionary that includes keys for the specific information your app collects.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSSensorKitUsageDetail",
      "kind": "symbol",
      "name": "NSSensorKitUsageDetail",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSSensorKitUsageDetail"
        }
      ],
      "role": "symbol",
      "title": "NSSensorKitUsageDetail",
      "titleStyle": "symbol",
      "type": "topic",
      "url": "/documentation/bundleresources/information-property-list/nssensorkitusagedetail"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSSensorKitUsageDetail/SRSensorUsageAmbientLightSensor": {
      "abstract": [
        {
          "text": "A collection of properties that explain your app’s need to observe light levels in the user’s environment.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSSensorKitUsageDetail/SRSensorUsageAmbientLightSensor",
      "kind": "symbol",
      "name": "SRSensorUsageAmbientLightSensor",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SRSensorUsageAmbientLightSensor"
        }
      ],
      "role": "symbol",
      "title": "SRSensorUsageAmbientLightSensor",
      "titleStyle": "symbol",
      "type": "topic",
      "url": "/documentation/bundleresources/information-property-list/nssensorkitusagedetail/srsensorusageambientlightsensor"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSSensorKitUsageDetail/SRSensorUsageDeviceUsage": {
      "abstract": [
        {
          "text": "A collection of properties that explain your app’s need to observe how frequently a user’s device activates.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSSensorKitUsageDetail/SRSensorUsageDeviceUsage",
      "kind": "symbol",
      "name": "SRSensorUsageDeviceUsage",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SRSensorUsageDeviceUsage"
        }
      ],
      "role": "symbol",
      "title": "SRSensorUsageDeviceUsage",
      "titleStyle": "symbol",
      "type": "topic",
      "url": "/documentation/bundleresources/information-property-list/nssensorkitusagedetail/srsensorusagedeviceusage"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSSensorKitUsageDetail/SRSensorUsageECG": {
      "abstract": [
        {
          "text": "A collection of properties that explains your app’s need to observe the person’s electrocardiogram sensor data.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSSensorKitUsageDetail/SRSensorUsageECG",
      "kind": "symbol",
      "name": "SRSensorUsageECG",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SRSensorUsageECG"
        }
      ],
      "role": "symbol",
      "title": "SRSensorUsageECG",
      "titleStyle": "symbol",
      "type": "topic",
      "url": "/documentation/bundleresources/information-property-list/nssensorkitusagedetail/srsensorusageecg"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSSensorKitUsageDetail/SRSensorUsageElevation": {
      "abstract": [
        {
          "text": "A collection of properties that explains your app’s need to observe the device’s elevation data.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSSensorKitUsageDetail/SRSensorUsageElevation",
      "kind": "symbol",
      "name": "SRSensorUsageElevation",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SRSensorUsageElevation"
        }
      ],
      "role": "symbol",
      "title": "SRSensorUsageElevation",
      "titleStyle": "symbol",
      "type": "topic",
      "url": "/documentation/bundleresources/information-property-list/nssensorkitusagedetail/srsensorusageelevation"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSSensorKitUsageDetail/SRSensorUsageFacialMetrics": {
      "abstract": [
        {
          "text": "A collection of properties that explains your app’s need to observe the user’s facial expressions.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSSensorKitUsageDetail/SRSensorUsageFacialMetrics",
      "kind": "symbol",
      "name": "SRSensorUsageFacialMetrics",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SRSensorUsageFacialMetrics"
        }
      ],
      "role": "symbol",
      "title": "SRSensorUsageFacialMetrics",
      "titleStyle": "symbol",
      "type": "topic",
      "url": "/documentation/bundleresources/information-property-list/nssensorkitusagedetail/srsensorusagefacialmetrics"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSSensorKitUsageDetail/SRSensorUsageHeartRate": {
      "abstract": [
        {
          "text": "A collection of properties that explains your app’s need to observe the user’s heart rate.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSSensorKitUsageDetail/SRSensorUsageHeartRate",
      "kind": "symbol",
      "name": "SRSensorUsageHeartRate",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SRSensorUsageHeartRate"
        }
      ],
      "role": "symbol",
      "title": "SRSensorUsageHeartRate",
      "titleStyle": "symbol",
      "type": "topic",
      "url": "/documentation/bundleresources/information-property-list/nssensorkitusagedetail/srsensorusageheartrate"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSSensorKitUsageDetail/SRSensorUsageKeyboardMetrics": {
      "abstract": [
        {
          "text": "A collection of properties that explain your app’s need to observe the user’s keyboard activity.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSSensorKitUsageDetail/SRSensorUsageKeyboardMetrics",
      "kind": "symbol",
      "name": "SRSensorUsageKeyboardMetrics",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SRSensorUsageKeyboardMetrics"
        }
      ],
      "role": "symbol",
      "title": "SRSensorUsageKeyboardMetrics",
      "titleStyle": "symbol",
      "type": "topic",
      "url": "/documentation/bundleresources/information-property-list/nssensorkitusagedetail/srsensorusagekeyboardmetrics"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSSensorKitUsageDetail/SRSensorUsageMediaEvents": {
      "abstract": [
        {
          "text": "A collection of properties that explains your app’s need to observe the user’s interactions with media, such as images and videos, in messaging apps.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSSensorKitUsageDetail/SRSensorUsageMediaEvents",
      "kind": "symbol",
      "name": "SRSensorUsageMediaEvents",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SRSensorUsageMediaEvents"
        }
      ],
      "role": "symbol",
      "title": "SRSensorUsageMediaEvents",
      "titleStyle": "symbol",
      "type": "topic",
      "url": "/documentation/bundleresources/information-property-list/nssensorkitusagedetail/srsensorusagemediaevents"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSSensorKitUsageDetail/SRSensorUsageMessageUsage": {
      "abstract": [
        {
          "text": "A collection of properties that explain your app’s need to observe the user’s activity in Messages.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSSensorKitUsageDetail/SRSensorUsageMessageUsage",
      "kind": "symbol",
      "name": "SRSensorUsageMessageUsage",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SRSensorUsageMessageUsage"
        }
      ],
      "role": "symbol",
      "title": "SRSensorUsageMessageUsage",
      "titleStyle": "symbol",
      "type": "topic",
      "url": "/documentation/bundleresources/information-property-list/nssensorkitusagedetail/srsensorusagemessageusage"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSSensorKitUsageDetail/SRSensorUsageMotion": {
      "abstract": [
        {
          "text": "A collection of properties that explain your app’s need to observe motion data.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSSensorKitUsageDetail/SRSensorUsageMotion",
      "kind": "symbol",
      "name": "SRSensorUsageMotion",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SRSensorUsageMotion"
        }
      ],
      "role": "symbol",
      "title": "SRSensorUsageMotion",
      "titleStyle": "symbol",
      "type": "topic",
      "url": "/documentation/bundleresources/information-property-list/nssensorkitusagedetail/srsensorusagemotion"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSSensorKitUsageDetail/SRSensorUsageOdometer": {
      "abstract": [
        {
          "text": "A collection of properties that explains your app’s need to observe the user’s odometer data.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSSensorKitUsageDetail/SRSensorUsageOdometer",
      "kind": "symbol",
      "name": "SRSensorUsageOdometer",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SRSensorUsageOdometer"
        }
      ],
      "role": "symbol",
      "title": "SRSensorUsageOdometer",
      "titleStyle": "symbol",
      "type": "topic",
      "url": "/documentation/bundleresources/information-property-list/nssensorkitusagedetail/srsensorusageodometer"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSSensorKitUsageDetail/SRSensorUsagePPG": {
      "abstract": [
        {
          "text": "A collection of properties that explains your app’s need to observe the person’s photoplethysmogram sensor data.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSSensorKitUsageDetail/SRSensorUsagePPG",
      "kind": "symbol",
      "name": "SRSensorUsagePPG",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SRSensorUsagePPG"
        }
      ],
      "role": "symbol",
      "title": "SRSensorUsagePPG",
      "titleStyle": "symbol",
      "type": "topic",
      "url": "/documentation/bundleresources/information-property-list/nssensorkitusagedetail/srsensorusageppg"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSSensorKitUsageDetail/SRSensorUsagePedometer": {
      "abstract": [
        {
          "text": "A collection of properties that explain your app’s need to observe steps information.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSSensorKitUsageDetail/SRSensorUsagePedometer",
      "kind": "symbol",
      "name": "SRSensorUsagePedometer",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SRSensorUsagePedometer"
        }
      ],
      "role": "symbol",
      "title": "SRSensorUsagePedometer",
      "titleStyle": "symbol",
      "type": "topic",
      "url": "/documentation/bundleresources/information-property-list/nssensorkitusagedetail/srsensorusagepedometer"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSSensorKitUsageDetail/SRSensorUsagePhoneUsage": {
      "abstract": [
        {
          "text": "A collection of properties that explain your app’s need to observe the user’s phone activity.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSSensorKitUsageDetail/SRSensorUsagePhoneUsage",
      "kind": "symbol",
      "name": "SRSensorUsagePhoneUsage",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SRSensorUsagePhoneUsage"
        }
      ],
      "role": "symbol",
      "title": "SRSensorUsagePhoneUsage",
      "titleStyle": "symbol",
      "type": "topic",
      "url": "/documentation/bundleresources/information-property-list/nssensorkitusagedetail/srsensorusagephoneusage"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSSensorKitUsageDetail/SRSensorUsageSpeechMetrics": {
      "abstract": [
        {
          "text": "A collection of properties that explain your app’s need to analyze the user’s speech.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSSensorKitUsageDetail/SRSensorUsageSpeechMetrics",
      "kind": "symbol",
      "name": "SRSensorUsageSpeechMetrics",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SRSensorUsageSpeechMetrics"
        }
      ],
      "role": "symbol",
      "title": "SRSensorUsageSpeechMetrics",
      "titleStyle": "symbol",
      "type": "topic",
      "url": "/documentation/bundleresources/information-property-list/nssensorkitusagedetail/srsensorusagespeechmetrics"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSSensorKitUsageDetail/SRSensorUsageVisits": {
      "abstract": [
        {
          "text": "A collection of properties that explain your app’s need to observe the locations that the user frequents.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSSensorKitUsageDetail/SRSensorUsageVisits",
      "kind": "symbol",
      "name": "SRSensorUsageVisits",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SRSensorUsageVisits"
        }
      ],
      "role": "symbol",
      "title": "SRSensorUsageVisits",
      "titleStyle": "symbol",
      "type": "topic",
      "url": "/documentation/bundleresources/information-property-list/nssensorkitusagedetail/srsensorusagevisits"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSSensorKitUsageDetail/SRSensorUsageWristDetection": {
      "abstract": [
        {
          "text": "A collection of properties that explain your app’s need to observe how the user wears their watch.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSSensorKitUsageDetail/SRSensorUsageWristDetection",
      "kind": "symbol",
      "name": "SRSensorUsageWristDetection",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SRSensorUsageWristDetection"
        }
      ],
      "role": "symbol",
      "title": "SRSensorUsageWristDetection",
      "titleStyle": "symbol",
      "type": "topic",
      "url": "/documentation/bundleresources/information-property-list/nssensorkitusagedetail/srsensorusagewristdetection"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSSensorKitUsageDetail/SRSensorUsageWristTemperature": {
      "abstract": [
        {
          "text": "A collection of properties that explains your app’s need to observe the user’s wrist temperature while the user sleeps.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSSensorKitUsageDetail/SRSensorUsageWristTemperature",
      "kind": "symbol",
      "name": "SRSensorUsageWristTemperature",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SRSensorUsageWristTemperature"
        }
      ],
      "role": "symbol",
      "title": "SRSensorUsageWristTemperature",
      "titleStyle": "symbol",
      "type": "topic",
      "url": "/documentation/bundleresources/information-property-list/nssensorkitusagedetail/srsensorusagewristtemperature"
    },
    "doc://com.apple.documentation/documentation/SensorKit/configuring-your-project-for-sensor-reading": {
      "abstract": [
        {
          "text": "Add metadata to your app to attain system and user permission to access sensor data.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/SensorKit/configuring-your-project-for-sensor-reading",
      "kind": "article",
      "role": "article",
      "title": "Configuring your project for sensor reading",
      "type": "topic",
      "url": "/documentation/SensorKit/configuring-your-project-for-sensor-reading"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Sensors",
      "generated": true,
      "identifiers": [
        "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSSensorKitUsageDescription",
        "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSSensorKitPrivacyPolicyURL"
      ],
      "title": "Sensors"
    }
  ],
  "topicSections": [
    {
      "anchor": "Device-Activity",
      "identifiers": [
        "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSSensorKitUsageDetail/SRSensorUsageDeviceUsage",
        "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSSensorKitUsageDetail/SRSensorUsageKeyboardMetrics",
        "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSSensorKitUsageDetail/SRSensorUsageWristDetection"
      ],
      "title": "Device Activity"
    },
    {
      "anchor": "App-Activity",
      "identifiers": [
        "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSSensorKitUsageDetail/SRSensorUsageMessageUsage",
        "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSSensorKitUsageDetail/SRSensorUsagePhoneUsage"
      ],
      "title": "App Activity"
    },
    {
      "anchor": "User-Activity",
      "identifiers": [
        "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSSensorKitUsageDetail/SRSensorUsageECG",
        "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSSensorKitUsageDetail/SRSensorUsageElevation",
        "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSSensorKitUsageDetail/SRSensorUsageFacialMetrics",
        "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSSensorKitUsageDetail/SRSensorUsageHeartRate",
        "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSSensorKitUsageDetail/SRSensorUsageMediaEvents",
        "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSSensorKitUsageDetail/SRSensorUsageMotion",
        "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSSensorKitUsageDetail/SRSensorUsageOdometer",
        "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSSensorKitUsageDetail/SRSensorUsagePedometer",
        "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSSensorKitUsageDetail/SRSensorUsagePPG",
        "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSSensorKitUsageDetail/SRSensorUsageSpeechMetrics",
        "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSSensorKitUsageDetail/SRSensorUsageVisits",
        "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSSensorKitUsageDetail/SRSensorUsageWristTemperature"
      ],
      "title": "User Activity"
    },
    {
      "anchor": "Environment",
      "identifiers": [
        "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSSensorKitUsageDetail/SRSensorUsageAmbientLightSensor"
      ],
      "title": "Environment"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "14.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "14.0",
              "name": "iPadOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Property List Key"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "NSSensorKitUsageDetail"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "dictionary"
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSSensorKitUsageDetail"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.bundleresources/documentation/BundleResources",
                "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Device-Activity",
              "identifiers": [
                "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSSensorKitUsageDetail/SRSensorUsageDeviceUsage",
                "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSSensorKitUsageDetail/SRSensorUsageKeyboardMetrics",
                "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSSensorKitUsageDetail/SRSensorUsageWristDetection"
              ],
              "title": "Device Activity"
            },
            {
              "anchor": "App-Activity",
              "identifiers": [
                "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSSensorKitUsageDetail/SRSensorUsageMessageUsage",
                "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSSensorKitUsageDetail/SRSensorUsagePhoneUsage"
              ],
              "title": "App Activity"
            },
            {
              "anchor": "User-Activity",
              "identifiers": [
                "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSSensorKitUsageDetail/SRSensorUsageECG",
                "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSSensorKitUsageDetail/SRSensorUsageElevation",
                "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSSensorKitUsageDetail/SRSensorUsageFacialMetrics",
                "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSSensorKitUsageDetail/SRSensorUsageHeartRate",
                "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSSensorKitUsageDetail/SRSensorUsageMediaEvents",
                "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSSensorKitUsageDetail/SRSensorUsageMotion",
                "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSSensorKitUsageDetail/SRSensorUsageOdometer",
                "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSSensorKitUsageDetail/SRSensorUsagePedometer",
                "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSSensorKitUsageDetail/SRSensorUsagePPG",
                "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSSensorKitUsageDetail/SRSensorUsageSpeechMetrics",
                "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSSensorKitUsageDetail/SRSensorUsageVisits",
                "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSSensorKitUsageDetail/SRSensorUsageWristTemperature"
              ],
              "title": "User Activity"
            },
            {
              "anchor": "Environment",
              "identifiers": [
                "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSSensorKitUsageDetail/SRSensorUsageAmbientLightSensor"
              ],
              "title": "Environment"
            }
          ]
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Sensors",
              "generated": true,
              "identifiers": [
                "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSSensorKitUsageDescription",
                "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSSensorKitPrivacyPolicyURL"
              ],
              "title": "Sensors"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1NSSensorKitUsageDetail~1SRSensorUsageFacialMetrics/title",
          "value": "SRSensorUsageFacialMetrics"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1NSSensorKitUsageDetail~1SRSensorUsageFacialMetrics/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SRSensorUsageFacialMetrics"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List/title",
          "value": "Information Property List"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "Information Property List"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1NSSensorKitUsageDetail~1SRSensorUsageWristDetection/title",
          "value": "SRSensorUsageWristDetection"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1NSSensorKitUsageDetail~1SRSensorUsageWristDetection/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SRSensorUsageWristDetection"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1NSSensorKitUsageDetail~1SRSensorUsagePhoneUsage/title",
          "value": "SRSensorUsagePhoneUsage"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1NSSensorKitUsageDetail~1SRSensorUsagePhoneUsage/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SRSensorUsagePhoneUsage"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1NSSensorKitUsageDetail~1SRSensorUsageMessageUsage/title",
          "value": "SRSensorUsageMessageUsage"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1NSSensorKitUsageDetail~1SRSensorUsageMessageUsage/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SRSensorUsageMessageUsage"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1NSSensorKitUsageDetail~1SRSensorUsageAmbientLightSensor/title",
          "value": "SRSensorUsageAmbientLightSensor"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1NSSensorKitUsageDetail~1SRSensorUsageAmbientLightSensor/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SRSensorUsageAmbientLightSensor"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1NSSensorKitUsageDetail~1SRSensorUsageKeyboardMetrics/title",
          "value": "SRSensorUsageKeyboardMetrics"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1NSSensorKitUsageDetail~1SRSensorUsageKeyboardMetrics/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SRSensorUsageKeyboardMetrics"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1NSSensorKitUsageDetail/title",
          "value": "NSSensorKitUsageDetail"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1NSSensorKitUsageDetail/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSSensorKitUsageDetail"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1NSSensorKitPrivacyPolicyURL/title",
          "value": "NSSensorKitPrivacyPolicyURL"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1NSSensorKitPrivacyPolicyURL/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSSensorKitPrivacyPolicyURL"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1NSSensorKitUsageDetail~1SRSensorUsageElevation/title",
          "value": "SRSensorUsageElevation"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1NSSensorKitUsageDetail~1SRSensorUsageElevation/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SRSensorUsageElevation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1NSSensorKitUsageDetail~1SRSensorUsageMediaEvents/title",
          "value": "SRSensorUsageMediaEvents"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1NSSensorKitUsageDetail~1SRSensorUsageMediaEvents/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SRSensorUsageMediaEvents"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1NSSensorKitUsageDetail~1SRSensorUsageOdometer/title",
          "value": "SRSensorUsageOdometer"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1NSSensorKitUsageDetail~1SRSensorUsageOdometer/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SRSensorUsageOdometer"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1NSSensorKitUsageDetail~1SRSensorUsageHeartRate/title",
          "value": "SRSensorUsageHeartRate"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1NSSensorKitUsageDetail~1SRSensorUsageHeartRate/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SRSensorUsageHeartRate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1NSSensorKitUsageDetail~1SRSensorUsageECG/title",
          "value": "SRSensorUsageECG"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1NSSensorKitUsageDetail~1SRSensorUsageECG/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SRSensorUsageECG"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1NSSensorKitUsageDetail~1SRSensorUsageVisits/title",
          "value": "SRSensorUsageVisits"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1NSSensorKitUsageDetail~1SRSensorUsageVisits/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SRSensorUsageVisits"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1NSSensorKitUsageDetail~1SRSensorUsageSpeechMetrics/title",
          "value": "SRSensorUsageSpeechMetrics"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1NSSensorKitUsageDetail~1SRSensorUsageSpeechMetrics/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SRSensorUsageSpeechMetrics"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1NSSensorKitUsageDetail~1SRSensorUsagePedometer/title",
          "value": "SRSensorUsagePedometer"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1NSSensorKitUsageDetail~1SRSensorUsagePedometer/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SRSensorUsagePedometer"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1NSSensorKitUsageDetail~1SRSensorUsageDeviceUsage/title",
          "value": "SRSensorUsageDeviceUsage"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1NSSensorKitUsageDetail~1SRSensorUsageDeviceUsage/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SRSensorUsageDeviceUsage"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1NSSensorKitUsageDetail~1SRSensorUsagePPG/title",
          "value": "SRSensorUsagePPG"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1NSSensorKitUsageDetail~1SRSensorUsagePPG/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SRSensorUsagePPG"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1NSSensorKitUsageDetail~1SRSensorUsageMotion/title",
          "value": "SRSensorUsageMotion"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1NSSensorKitUsageDetail~1SRSensorUsageMotion/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SRSensorUsageMotion"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1NSSensorKitUsageDescription/title",
          "value": "NSSensorKitUsageDescription"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1NSSensorKitUsageDescription/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSSensorKitUsageDescription"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1NSSensorKitUsageDetail~1SRSensorUsageWristTemperature/title",
          "value": "SRSensorUsageWristTemperature"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1NSSensorKitUsageDetail~1SRSensorUsageWristTemperature/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SRSensorUsageWristTemperature"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/bundleresources/information-property-list/nssensorkitusagedetail"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/bundleresources/information-property-list/nssensorkitusagedetail"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
