{
  "abstract": [
    {
      "text": "A hint at the height, in points, of a Quick Look app’s previews.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.bundleresources/documentation/BundleResources",
        "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/QLPreviewHeight"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "plist:Information_Property_List.QLPreviewHeight",
    "modules": [
      {
        "name": "Bundle Resources"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "QLPreviewHeight"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "2.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "2.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.0",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Property List Key",
    "symbolKind": "typealias",
    "title": "QLPreviewHeight"
  },
  "primaryContentSections": [
    {
      "details": {
        "ideTitle": "Quick Look preview height",
        "name": "QLPreviewHeight",
        "platforms": [],
        "titleStyle": "symbol",
        "value": [
          {
            "arrayMode": false,
            "baseType": "number"
          }
        ]
      },
      "kind": "details",
      "title": "Details"
    },
    {
      "attributes": [
        {
          "kind": "default",
          "value": "800.0"
        }
      ],
      "kind": "attributes",
      "title": "Attributes"
    },
    {
      "content": [
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "If the app’s generator takes too long to produce the preview, Quick Look uses this key.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.bundleresources/documentation/BundleResources": {
      "abstract": [
        {
          "text": "Resources located in an app, framework, or plugin bundle.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources",
      "kind": "symbol",
      "role": "collection",
      "title": "Bundle Resources",
      "type": "topic",
      "url": "/documentation/bundleresources"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List": {
      "abstract": [
        {
          "text": "A resource containing key-value pairs that identify and configure a bundle.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List",
      "kind": "symbol",
      "name": "Information Property List",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "Information Property List"
        }
      ],
      "role": "symbol",
      "title": "Information Property List",
      "titleStyle": "symbol",
      "type": "topic",
      "url": "/documentation/bundleresources/information-property-list"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/QLNeedsToBeRunInMainThread": {
      "abstract": [
        {
          "text": "A Boolean value indicating whether a Quick Look app’s generator can be run in threads other than the main thread.",
          "type": "text"
        }
      ],
      "ideTitle": "Quick Look needs to be run in main thread",
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/QLNeedsToBeRunInMainThread",
      "kind": "symbol",
      "name": "QLNeedsToBeRunInMainThread",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "QLNeedsToBeRunInMainThread"
        }
      ],
      "role": "symbol",
      "title": "QLNeedsToBeRunInMainThread",
      "titleStyle": "symbol",
      "type": "topic",
      "url": "/documentation/bundleresources/information-property-list/qlneedstoberuninmainthread"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/QLPreviewHeight": {
      "abstract": [
        {
          "text": "A hint at the height, in points, of a Quick Look app’s previews.",
          "type": "text"
        }
      ],
      "ideTitle": "Quick Look preview height",
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/QLPreviewHeight",
      "kind": "symbol",
      "name": "QLPreviewHeight",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "QLPreviewHeight"
        }
      ],
      "role": "symbol",
      "title": "QLPreviewHeight",
      "titleStyle": "symbol",
      "type": "topic",
      "url": "/documentation/bundleresources/information-property-list/qlpreviewheight"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/QLPreviewWidth": {
      "abstract": [
        {
          "text": "A hint at the width, in points, of a Quick Look app’s previews.",
          "type": "text"
        }
      ],
      "ideTitle": "Quick Look preview width",
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/QLPreviewWidth",
      "kind": "symbol",
      "name": "QLPreviewWidth",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "QLPreviewWidth"
        }
      ],
      "role": "symbol",
      "title": "QLPreviewWidth",
      "titleStyle": "symbol",
      "type": "topic",
      "url": "/documentation/bundleresources/information-property-list/qlpreviewwidth"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/QLSupportsConcurrentRequests": {
      "abstract": [
        {
          "text": "A Boolean value indicating whether a Quick Look app’s  generator can handle concurrent thumbnail and preview requests.",
          "type": "text"
        }
      ],
      "ideTitle": "Quick Look supports concurrent requests",
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/QLSupportsConcurrentRequests",
      "kind": "symbol",
      "name": "QLSupportsConcurrentRequests",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "QLSupportsConcurrentRequests"
        }
      ],
      "role": "symbol",
      "title": "QLSupportsConcurrentRequests",
      "titleStyle": "symbol",
      "type": "topic",
      "url": "/documentation/bundleresources/information-property-list/qlsupportsconcurrentrequests"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/QLThumbnailMinimumSize": {
      "abstract": [
        {
          "text": "The minimum size, in points, along one dimension of thumbnails for a Quick Look app’s generator.",
          "type": "text"
        }
      ],
      "ideTitle": "Quick Look thumbnail minimum size",
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/QLThumbnailMinimumSize",
      "kind": "symbol",
      "name": "QLThumbnailMinimumSize",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "QLThumbnailMinimumSize"
        }
      ],
      "role": "symbol",
      "title": "QLThumbnailMinimumSize",
      "titleStyle": "symbol",
      "type": "topic",
      "url": "/documentation/bundleresources/information-property-list/qlthumbnailminimumsize"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "QuickLook",
      "generated": true,
      "identifiers": [
        "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/QLNeedsToBeRunInMainThread",
        "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/QLPreviewWidth",
        "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/QLSupportsConcurrentRequests",
        "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/QLThumbnailMinimumSize"
      ],
      "title": "QuickLook"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "2.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "2.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.0",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Property List Key"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "QLPreviewHeight"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "typealias"
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "QLPreviewHeight"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.bundleresources/documentation/BundleResources",
                "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "QuickLook",
              "generated": true,
              "identifiers": [
                "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/QLNeedsToBeRunInMainThread",
                "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/QLPreviewWidth",
                "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/QLSupportsConcurrentRequests",
                "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/QLThumbnailMinimumSize"
              ],
              "title": "QuickLook"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1QLSupportsConcurrentRequests/title",
          "value": "QLSupportsConcurrentRequests"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1QLSupportsConcurrentRequests/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "QLSupportsConcurrentRequests"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1QLPreviewWidth/title",
          "value": "QLPreviewWidth"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1QLPreviewWidth/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "QLPreviewWidth"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List/title",
          "value": "Information Property List"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "Information Property List"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1QLThumbnailMinimumSize/title",
          "value": "QLThumbnailMinimumSize"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1QLThumbnailMinimumSize/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "QLThumbnailMinimumSize"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1QLNeedsToBeRunInMainThread/title",
          "value": "QLNeedsToBeRunInMainThread"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1QLNeedsToBeRunInMainThread/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "QLNeedsToBeRunInMainThread"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1QLPreviewHeight/title",
          "value": "QLPreviewHeight"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1QLPreviewHeight/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "QLPreviewHeight"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/bundleresources/information-property-list/qlpreviewheight"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/bundleresources/information-property-list/qlpreviewheight"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
