{
  "abstract": [
    {
      "text": "A string bundle ID that identifies the corresponding iOS app that contains a content blocker or Safari web extension.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.bundleresources/documentation/BundleResources",
        "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/SFSafariCorrespondingIOSAppBundleIdentifier"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "plist:Information_Property_List.SFSafariCorrespondingIOSAppBundleIdentifier",
    "modules": [
      {
        "name": "Bundle Resources"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "SFSafariCorrespondingIOSAppBundleIdentifier"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.0",
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Property List Key",
    "symbolKind": "typealias",
    "title": "SFSafariCorrespondingIOSAppBundleIdentifier"
  },
  "primaryContentSections": [
    {
      "details": {
        "ideTitle": "Safari - Associated iOS App Bundle Identifier",
        "name": "SFSafariCorrespondingIOSAppBundleIdentifier",
        "platforms": [],
        "titleStyle": "symbol",
        "value": [
          {
            "arrayMode": false,
            "baseType": "string"
          }
        ]
      },
      "kind": "details",
      "title": "Details"
    },
    {
      "content": [
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "To enable extension syncing for your macOS app that contains a content blocker or Safari web extension, specify the bundle ID of the corresponding iOS app that contains the same content blocker or Safari web extension.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "Only add this to your ",
              "type": "text"
            },
            {
              "code": "Info.plist",
              "type": "codeVoice"
            },
            {
              "text": " if the bundle ID for your macOS app is different from the bundle ID for your iOS app.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "For more information, see ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/SafariServices/syncing-safari-web-extensions-across-devices-and-platforms",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ".",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.bundleresources/documentation/BundleResources": {
      "abstract": [
        {
          "text": "Resources located in an app, framework, or plugin bundle.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources",
      "kind": "symbol",
      "role": "collection",
      "title": "Bundle Resources",
      "type": "topic",
      "url": "/documentation/bundleresources"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List": {
      "abstract": [
        {
          "text": "A resource containing key-value pairs that identify and configure a bundle.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List",
      "kind": "symbol",
      "name": "Information Property List",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "Information Property List"
        }
      ],
      "role": "symbol",
      "title": "Information Property List",
      "titleStyle": "symbol",
      "type": "topic",
      "url": "/documentation/bundleresources/information-property-list"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/SFSafariCorrespondingIOSAppBundleIdentifier": {
      "abstract": [
        {
          "text": "A string bundle ID that identifies the corresponding iOS app that contains a content blocker or Safari web extension.",
          "type": "text"
        }
      ],
      "ideTitle": "Safari - Associated iOS App Bundle Identifier",
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/SFSafariCorrespondingIOSAppBundleIdentifier",
      "kind": "symbol",
      "name": "SFSafariCorrespondingIOSAppBundleIdentifier",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SFSafariCorrespondingIOSAppBundleIdentifier"
        }
      ],
      "role": "symbol",
      "title": "SFSafariCorrespondingIOSAppBundleIdentifier",
      "titleStyle": "symbol",
      "type": "topic",
      "url": "/documentation/bundleresources/information-property-list/sfsafaricorrespondingiosappbundleidentifier"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/SFSafariCorrespondingIOSExtensionBundleIdentifier": {
      "abstract": [
        {
          "text": "A string bundle ID that identifies the corresponding content blocker extension or Safari web extension on iOS.",
          "type": "text"
        }
      ],
      "ideTitle": "Safari - Associated iOS Extension Bundle Identifier",
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/SFSafariCorrespondingIOSExtensionBundleIdentifier",
      "kind": "symbol",
      "name": "SFSafariCorrespondingIOSExtensionBundleIdentifier",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SFSafariCorrespondingIOSExtensionBundleIdentifier"
        }
      ],
      "role": "symbol",
      "title": "SFSafariCorrespondingIOSExtensionBundleIdentifier",
      "titleStyle": "symbol",
      "type": "topic",
      "url": "/documentation/bundleresources/information-property-list/sfsafaricorrespondingiosextensionbundleidentifier"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/SFSafariCorrespondingMacOSAppBundleIdentifier": {
      "abstract": [
        {
          "text": "A string bundle ID that identifies the corresponding macOS app that contains a content blocker or Safari web extension.",
          "type": "text"
        }
      ],
      "ideTitle": "Safari - Associated macOS App Bundle Identifier",
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/SFSafariCorrespondingMacOSAppBundleIdentifier",
      "kind": "symbol",
      "name": "SFSafariCorrespondingMacOSAppBundleIdentifier",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SFSafariCorrespondingMacOSAppBundleIdentifier"
        }
      ],
      "role": "symbol",
      "title": "SFSafariCorrespondingMacOSAppBundleIdentifier",
      "titleStyle": "symbol",
      "type": "topic",
      "url": "/documentation/bundleresources/information-property-list/sfsafaricorrespondingmacosappbundleidentifier"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/SFSafariCorrespondingMacOSExtensionBundleIdentifier": {
      "abstract": [
        {
          "text": "A string bundle ID that identifies the corresponding content blocker extension or Safari web extension on macOS.",
          "type": "text"
        }
      ],
      "ideTitle": "Safari - Associated macOS Extension Bundle Identifier",
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/SFSafariCorrespondingMacOSExtensionBundleIdentifier",
      "kind": "symbol",
      "name": "SFSafariCorrespondingMacOSExtensionBundleIdentifier",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SFSafariCorrespondingMacOSExtensionBundleIdentifier"
        }
      ],
      "role": "symbol",
      "title": "SFSafariCorrespondingMacOSExtensionBundleIdentifier",
      "titleStyle": "symbol",
      "type": "topic",
      "url": "/documentation/bundleresources/information-property-list/sfsafaricorrespondingmacosextensionbundleidentifier"
    },
    "doc://com.apple.documentation/documentation/SafariServices/syncing-safari-web-extensions-across-devices-and-platforms": {
      "abstract": [
        {
          "text": "Let users install your extension on one device and then use and manage the extension on all their other iOS and macOS devices.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/SafariServices/syncing-safari-web-extensions-across-devices-and-platforms",
      "kind": "article",
      "role": "article",
      "title": "Syncing Safari web extensions across devices and platforms",
      "type": "topic",
      "url": "/documentation/SafariServices/syncing-safari-web-extensions-across-devices-and-platforms"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Safari-services",
      "generated": true,
      "identifiers": [
        "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/SFSafariCorrespondingIOSExtensionBundleIdentifier",
        "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/SFSafariCorrespondingMacOSAppBundleIdentifier",
        "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/SFSafariCorrespondingMacOSExtensionBundleIdentifier"
      ],
      "title": "Safari services"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.0",
              "name": "macOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Property List Key"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "SFSafariCorrespondingIOSAppBundleIdentifier"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "typealias"
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SFSafariCorrespondingIOSAppBundleIdentifier"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.bundleresources/documentation/BundleResources",
                "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Safari-services",
              "generated": true,
              "identifiers": [
                "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/SFSafariCorrespondingIOSExtensionBundleIdentifier",
                "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/SFSafariCorrespondingMacOSAppBundleIdentifier",
                "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/SFSafariCorrespondingMacOSExtensionBundleIdentifier"
              ],
              "title": "Safari services"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1SFSafariCorrespondingMacOSAppBundleIdentifier/title",
          "value": "SFSafariCorrespondingMacOSAppBundleIdentifier"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1SFSafariCorrespondingMacOSAppBundleIdentifier/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SFSafariCorrespondingMacOSAppBundleIdentifier"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1SFSafariCorrespondingIOSAppBundleIdentifier/title",
          "value": "SFSafariCorrespondingIOSAppBundleIdentifier"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1SFSafariCorrespondingIOSAppBundleIdentifier/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SFSafariCorrespondingIOSAppBundleIdentifier"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1SFSafariCorrespondingMacOSExtensionBundleIdentifier/title",
          "value": "SFSafariCorrespondingMacOSExtensionBundleIdentifier"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1SFSafariCorrespondingMacOSExtensionBundleIdentifier/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SFSafariCorrespondingMacOSExtensionBundleIdentifier"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List/title",
          "value": "Information Property List"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "Information Property List"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1SFSafariCorrespondingIOSExtensionBundleIdentifier/title",
          "value": "SFSafariCorrespondingIOSExtensionBundleIdentifier"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1SFSafariCorrespondingIOSExtensionBundleIdentifier/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SFSafariCorrespondingIOSExtensionBundleIdentifier"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/bundleresources/information-property-list/sfsafaricorrespondingiosappbundleidentifier"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/bundleresources/information-property-list/sfsafaricorrespondingiosappbundleidentifier"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
