{
  "abstract": [
    {
      "text": "An array of dictionaries containing a list of ad network IDs.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.bundleresources/documentation/BundleResources",
        "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/SKAdNetworkItems"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "plist:Information_Property_List.SKAdNetworkItems",
    "modules": [
      {
        "name": "Bundle Resources"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "SKAdNetworkItems"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "11.3",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "11.3",
        "name": "iPadOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Property List Key",
    "symbolKind": "dictionary",
    "title": "SKAdNetworkItems"
  },
  "primaryContentSections": [
    {
      "details": {
        "name": "SKAdNetworkItems",
        "platforms": [],
        "titleStyle": "symbol",
        "value": [
          {
            "arrayMode": true,
            "baseType": "dictionary "
          }
        ]
      },
      "kind": "details",
      "title": "Details"
    },
    {
      "content": [
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Apps that display ads and initiate install-validation information to share with ad networks need to include the ad network IDs in this key.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "Each dictionary contains one ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/SKAdNetworkItems/SKAdNetworkIdentifier",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ". Provide one dictionary for each ad network that you work with.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "",
                  "type": "text"
                },
                {
                  "text": " ",
                  "type": "text"
                },
                {
                  "text": "Ad network IDs are case-sensitive and are in lowercase.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "Important",
          "style": "important",
          "type": "aside"
        },
        {
          "inlineContent": [
            {
              "text": "For more information, see ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/StoreKit/configuring-a-source-app",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ".",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.bundleresources/documentation/BundleResources": {
      "abstract": [
        {
          "text": "Resources located in an app, framework, or plugin bundle.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources",
      "kind": "symbol",
      "role": "collection",
      "title": "Bundle Resources",
      "type": "topic",
      "url": "/documentation/bundleresources"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List": {
      "abstract": [
        {
          "text": "A resource containing key-value pairs that identify and configure a bundle.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List",
      "kind": "symbol",
      "name": "Information Property List",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "Information Property List"
        }
      ],
      "role": "symbol",
      "title": "Information Property List",
      "titleStyle": "symbol",
      "type": "topic",
      "url": "/documentation/bundleresources/information-property-list"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/SKAdNetworkItems": {
      "abstract": [
        {
          "text": "An array of dictionaries containing a list of ad network IDs.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/SKAdNetworkItems",
      "kind": "symbol",
      "name": "SKAdNetworkItems",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SKAdNetworkItems"
        }
      ],
      "role": "symbol",
      "title": "SKAdNetworkItems",
      "titleStyle": "symbol",
      "type": "topic",
      "url": "/documentation/bundleresources/information-property-list/skadnetworkitems"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/SKAdNetworkItems/SKAdNetworkIdentifier": {
      "abstract": [
        {
          "text": "A string that contains an ad network ID.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/SKAdNetworkItems/SKAdNetworkIdentifier",
      "kind": "symbol",
      "name": "SKAdNetworkIdentifier",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SKAdNetworkIdentifier"
        }
      ],
      "role": "symbol",
      "title": "SKAdNetworkIdentifier",
      "titleStyle": "symbol",
      "type": "topic",
      "url": "/documentation/bundleresources/information-property-list/skadnetworkitems/skadnetworkidentifier"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/SKExternalLinkAccount": {
      "abstract": [
        {
          "text": "A dictionary that contains localized URLs to an external website for account creation or management.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/SKExternalLinkAccount",
      "kind": "symbol",
      "name": "SKExternalLinkAccount",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SKExternalLinkAccount"
        }
      ],
      "role": "symbol",
      "title": "SKExternalLinkAccount",
      "titleStyle": "symbol",
      "type": "topic",
      "url": "/documentation/bundleresources/information-property-list/skexternallinkaccount"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/SKExternalPurchase": {
      "abstract": [
        {
          "text": "A string array of country codes that indicates your app supports external purchases.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/SKExternalPurchase",
      "kind": "symbol",
      "name": "SKExternalPurchase",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SKExternalPurchase"
        }
      ],
      "role": "symbol",
      "title": "SKExternalPurchase",
      "titleStyle": "symbol",
      "type": "topic",
      "url": "/documentation/bundleresources/information-property-list/skexternalpurchase"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/SKExternalPurchaseCustomLinkRegions": {
      "abstract": [
        {
          "text": "An array of country code strings that indicate the regions where your app supports custom links for external purchases.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/SKExternalPurchaseCustomLinkRegions",
      "kind": "symbol",
      "name": "SKExternalPurchaseCustomLinkRegions",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SKExternalPurchaseCustomLinkRegions"
        }
      ],
      "role": "symbol",
      "title": "SKExternalPurchaseCustomLinkRegions",
      "titleStyle": "symbol",
      "type": "topic",
      "url": "/documentation/bundleresources/information-property-list/skexternalpurchasecustomlinkregions"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/SKExternalPurchaseLink": {
      "abstract": [
        {
          "text": "A dictionary that contains URLs to websites where people using your app can make external purchases for supported regions.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/SKExternalPurchaseLink",
      "kind": "symbol",
      "name": "SKExternalPurchaseLink",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SKExternalPurchaseLink"
        }
      ],
      "role": "symbol",
      "title": "SKExternalPurchaseLink",
      "titleStyle": "symbol",
      "type": "topic",
      "url": "/documentation/bundleresources/information-property-list/skexternalpurchaselink"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/SKExternalPurchaseMultiLink": {
      "abstract": [
        {
          "text": "A dictionary that contains an array of URLs to websites where people using your app can make external purchases.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/SKExternalPurchaseMultiLink",
      "kind": "symbol",
      "name": "SKExternalPurchaseMultiLink",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SKExternalPurchaseMultiLink"
        }
      ],
      "role": "symbol",
      "title": "SKExternalPurchaseMultiLink",
      "titleStyle": "symbol",
      "type": "topic",
      "url": "/documentation/bundleresources/information-property-list/skexternalpurchasemultilink"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/SKIncludeConsumableInAppPurchaseHistory": {
      "abstract": [
        {
          "text": "A Boolean value that determines whether StoreKit includes finished consumable In-App Purchases in transaction information.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/SKIncludeConsumableInAppPurchaseHistory",
      "kind": "symbol",
      "name": "SKIncludeConsumableInAppPurchaseHistory",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SKIncludeConsumableInAppPurchaseHistory"
        }
      ],
      "role": "symbol",
      "title": "SKIncludeConsumableInAppPurchaseHistory",
      "titleStyle": "symbol",
      "type": "topic",
      "url": "/documentation/bundleresources/information-property-list/skincludeconsumableinapppurchasehistory"
    },
    "doc://com.apple.documentation/documentation/StoreKit/configuring-a-source-app": {
      "abstract": [
        {
          "text": "Set up a source app to participate in ad campaigns.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/StoreKit/configuring-a-source-app",
      "kind": "article",
      "role": "article",
      "title": "Configuring a source app",
      "type": "topic",
      "url": "/documentation/StoreKit/configuring-a-source-app"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "StoreKit",
      "generated": true,
      "identifiers": [
        "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/SKExternalLinkAccount",
        "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/SKExternalPurchase",
        "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/SKExternalPurchaseCustomLinkRegions",
        "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/SKExternalPurchaseLink",
        "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/SKExternalPurchaseMultiLink",
        "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/SKIncludeConsumableInAppPurchaseHistory"
      ],
      "title": "StoreKit"
    }
  ],
  "topicSections": [
    {
      "anchor": "Ad-network-identifiers",
      "identifiers": [
        "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/SKAdNetworkItems/SKAdNetworkIdentifier"
      ],
      "title": "Ad network identifiers"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "11.3",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "11.3",
              "name": "iPadOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Property List Key"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "SKAdNetworkItems"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "dictionary"
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SKAdNetworkItems"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.bundleresources/documentation/BundleResources",
                "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Ad-network-identifiers",
              "identifiers": [
                "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/SKAdNetworkItems/SKAdNetworkIdentifier"
              ],
              "title": "Ad network identifiers"
            }
          ]
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "StoreKit",
              "generated": true,
              "identifiers": [
                "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/SKExternalLinkAccount",
                "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/SKExternalPurchase",
                "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/SKExternalPurchaseCustomLinkRegions",
                "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/SKExternalPurchaseLink",
                "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/SKExternalPurchaseMultiLink",
                "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/SKIncludeConsumableInAppPurchaseHistory"
              ],
              "title": "StoreKit"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1SKExternalLinkAccount/title",
          "value": "SKExternalLinkAccount"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1SKExternalLinkAccount/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SKExternalLinkAccount"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1SKExternalPurchaseMultiLink/title",
          "value": "SKExternalPurchaseMultiLink"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1SKExternalPurchaseMultiLink/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SKExternalPurchaseMultiLink"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1SKAdNetworkItems~1SKAdNetworkIdentifier/title",
          "value": "SKAdNetworkIdentifier"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1SKAdNetworkItems~1SKAdNetworkIdentifier/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SKAdNetworkIdentifier"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1SKExternalPurchaseLink/title",
          "value": "SKExternalPurchaseLink"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1SKExternalPurchaseLink/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SKExternalPurchaseLink"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1SKExternalPurchase/title",
          "value": "SKExternalPurchase"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1SKExternalPurchase/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SKExternalPurchase"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1SKExternalPurchaseCustomLinkRegions/title",
          "value": "SKExternalPurchaseCustomLinkRegions"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1SKExternalPurchaseCustomLinkRegions/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SKExternalPurchaseCustomLinkRegions"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1SKAdNetworkItems/title",
          "value": "SKAdNetworkItems"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1SKAdNetworkItems/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SKAdNetworkItems"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1SKIncludeConsumableInAppPurchaseHistory/title",
          "value": "SKIncludeConsumableInAppPurchaseHistory"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1SKIncludeConsumableInAppPurchaseHistory/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SKIncludeConsumableInAppPurchaseHistory"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List/title",
          "value": "Information Property List"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "Information Property List"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/bundleresources/information-property-list/skadnetworkitems"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/bundleresources/information-property-list/skadnetworkitems"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
