{
  "abstract": [
    {
      "text": "A string array of country codes that indicates your app supports external purchases.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.bundleresources/documentation/BundleResources",
        "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/SKExternalPurchase"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "plist:Information_Property_List.SKExternalPurchase",
    "modules": [
      {
        "name": "Bundle Resources"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "SKExternalPurchase"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "15.4",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "15.4",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "17.4",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "14.4",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "17.4",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.4",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Property List Key",
    "symbolKind": "typealias",
    "title": "SKExternalPurchase"
  },
  "primaryContentSections": [
    {
      "details": {
        "name": "SKExternalPurchase",
        "platforms": [],
        "titleStyle": "symbol",
        "value": [
          {
            "arrayMode": true,
            "baseType": "string "
          }
        ]
      },
      "kind": "details",
      "title": "Details"
    },
    {
      "content": [
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Use this information property list key if your app has the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Entitlements/com.apple.developer.storekit.external-purchase",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " entitlement.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "To the array, add a string containing the lowercased ISO 3166-1 alpha-2 country code for each country where your app supports external purchases. The following code example shows a property list entry with two strings, for the Netherlands (",
              "type": "text"
            },
            {
              "code": "nl",
              "type": "codeVoice"
            },
            {
              "text": ") and Italy (",
              "type": "text"
            },
            {
              "code": "it",
              "type": "codeVoice"
            },
            {
              "text": "):",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "code": [
            "<plist>",
            "<dict>",
            "    <key>SKExternalPurchase</key>",
            "    <array>",
            "        <string>nl</string>",
            "        <string>it</string>",
            "    </array>",
            "</dict>",
            "</plist>"
          ],
          "syntax": "xml",
          "type": "codeListing"
        },
        {
          "inlineContent": [
            {
              "text": "Use valid country codes for the following allowed countries or regions:",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "items": [
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "In the European Union: Austria (",
                      "type": "text"
                    },
                    {
                      "code": "at",
                      "type": "codeVoice"
                    },
                    {
                      "text": "), Belgium (",
                      "type": "text"
                    },
                    {
                      "code": "be",
                      "type": "codeVoice"
                    },
                    {
                      "text": "), Bulgaria (",
                      "type": "text"
                    },
                    {
                      "code": "bg",
                      "type": "codeVoice"
                    },
                    {
                      "text": "), Croatia (",
                      "type": "text"
                    },
                    {
                      "code": "hr",
                      "type": "codeVoice"
                    },
                    {
                      "text": "), Cyprus (",
                      "type": "text"
                    },
                    {
                      "code": "cy",
                      "type": "codeVoice"
                    },
                    {
                      "text": "), Czechia (",
                      "type": "text"
                    },
                    {
                      "code": "cz",
                      "type": "codeVoice"
                    },
                    {
                      "text": "), Denmark (",
                      "type": "text"
                    },
                    {
                      "code": "dk",
                      "type": "codeVoice"
                    },
                    {
                      "text": "), Estonia (",
                      "type": "text"
                    },
                    {
                      "code": "ee",
                      "type": "codeVoice"
                    },
                    {
                      "text": "), Finland (",
                      "type": "text"
                    },
                    {
                      "code": "fi",
                      "type": "codeVoice"
                    },
                    {
                      "text": "), France (",
                      "type": "text"
                    },
                    {
                      "code": "fr",
                      "type": "codeVoice"
                    },
                    {
                      "text": "), Germany (",
                      "type": "text"
                    },
                    {
                      "code": "de",
                      "type": "codeVoice"
                    },
                    {
                      "text": "), Greece (",
                      "type": "text"
                    },
                    {
                      "code": "gr",
                      "type": "codeVoice"
                    },
                    {
                      "text": "), Hungary (",
                      "type": "text"
                    },
                    {
                      "code": "hu",
                      "type": "codeVoice"
                    },
                    {
                      "text": "), Ireland (",
                      "type": "text"
                    },
                    {
                      "code": "ie",
                      "type": "codeVoice"
                    },
                    {
                      "text": "), Italy (",
                      "type": "text"
                    },
                    {
                      "code": "it",
                      "type": "codeVoice"
                    },
                    {
                      "text": "), Latvia (",
                      "type": "text"
                    },
                    {
                      "code": "lv",
                      "type": "codeVoice"
                    },
                    {
                      "text": "), Lithuania (",
                      "type": "text"
                    },
                    {
                      "code": "lt",
                      "type": "codeVoice"
                    },
                    {
                      "text": "), Luxembourg (",
                      "type": "text"
                    },
                    {
                      "code": "lu",
                      "type": "codeVoice"
                    },
                    {
                      "text": "), Malta (",
                      "type": "text"
                    },
                    {
                      "code": "mt",
                      "type": "codeVoice"
                    },
                    {
                      "text": "), Netherlands (",
                      "type": "text"
                    },
                    {
                      "code": "nl",
                      "type": "codeVoice"
                    },
                    {
                      "text": "), Poland (",
                      "type": "text"
                    },
                    {
                      "code": "pl",
                      "type": "codeVoice"
                    },
                    {
                      "text": "), Portugal (",
                      "type": "text"
                    },
                    {
                      "code": "pt",
                      "type": "codeVoice"
                    },
                    {
                      "text": "), Romania (",
                      "type": "text"
                    },
                    {
                      "code": "ro",
                      "type": "codeVoice"
                    },
                    {
                      "text": "), Slovakia (",
                      "type": "text"
                    },
                    {
                      "code": "sk",
                      "type": "codeVoice"
                    },
                    {
                      "text": "), Slovenia (",
                      "type": "text"
                    },
                    {
                      "code": "si",
                      "type": "codeVoice"
                    },
                    {
                      "text": "), Spain (",
                      "type": "text"
                    },
                    {
                      "code": "es",
                      "type": "codeVoice"
                    },
                    {
                      "text": "), Sweden (",
                      "type": "text"
                    },
                    {
                      "code": "se",
                      "type": "codeVoice"
                    },
                    {
                      "text": ")",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "South Korea (",
                      "type": "text"
                    },
                    {
                      "code": "kr",
                      "type": "codeVoice"
                    },
                    {
                      "text": ")",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            }
          ],
          "type": "unorderedList"
        },
        {
          "inlineContent": [
            {
              "text": "For more information, see ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/StoreKit/external-purchase",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ".",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.bundleresources/documentation/BundleResources": {
      "abstract": [
        {
          "text": "Resources located in an app, framework, or plugin bundle.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources",
      "kind": "symbol",
      "role": "collection",
      "title": "Bundle Resources",
      "type": "topic",
      "url": "/documentation/bundleresources"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/Entitlements/com.apple.developer.storekit.external-purchase": {
      "abstract": [
        {
          "text": "A Boolean value that indicates whether your app can offer external purchases.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Entitlements/com.apple.developer.storekit.external-purchase",
      "kind": "symbol",
      "name": "com.apple.developer.storekit.external-purchase",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "com.apple.developer.storekit.external-purchase"
        }
      ],
      "role": "symbol",
      "title": "com.apple.developer.storekit.external-purchase",
      "titleStyle": "title",
      "type": "topic",
      "url": "/documentation/bundleresources/entitlements/com.apple.developer.storekit.external-purchase"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List": {
      "abstract": [
        {
          "text": "A resource containing key-value pairs that identify and configure a bundle.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List",
      "kind": "symbol",
      "name": "Information Property List",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "Information Property List"
        }
      ],
      "role": "symbol",
      "title": "Information Property List",
      "titleStyle": "symbol",
      "type": "topic",
      "url": "/documentation/bundleresources/information-property-list"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/SKAdNetworkItems": {
      "abstract": [
        {
          "text": "An array of dictionaries containing a list of ad network IDs.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/SKAdNetworkItems",
      "kind": "symbol",
      "name": "SKAdNetworkItems",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SKAdNetworkItems"
        }
      ],
      "role": "symbol",
      "title": "SKAdNetworkItems",
      "titleStyle": "symbol",
      "type": "topic",
      "url": "/documentation/bundleresources/information-property-list/skadnetworkitems"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/SKExternalLinkAccount": {
      "abstract": [
        {
          "text": "A dictionary that contains localized URLs to an external website for account creation or management.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/SKExternalLinkAccount",
      "kind": "symbol",
      "name": "SKExternalLinkAccount",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SKExternalLinkAccount"
        }
      ],
      "role": "symbol",
      "title": "SKExternalLinkAccount",
      "titleStyle": "symbol",
      "type": "topic",
      "url": "/documentation/bundleresources/information-property-list/skexternallinkaccount"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/SKExternalPurchase": {
      "abstract": [
        {
          "text": "A string array of country codes that indicates your app supports external purchases.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/SKExternalPurchase",
      "kind": "symbol",
      "name": "SKExternalPurchase",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SKExternalPurchase"
        }
      ],
      "role": "symbol",
      "title": "SKExternalPurchase",
      "titleStyle": "symbol",
      "type": "topic",
      "url": "/documentation/bundleresources/information-property-list/skexternalpurchase"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/SKExternalPurchaseCustomLinkRegions": {
      "abstract": [
        {
          "text": "An array of country code strings that indicate the regions where your app supports custom links for external purchases.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/SKExternalPurchaseCustomLinkRegions",
      "kind": "symbol",
      "name": "SKExternalPurchaseCustomLinkRegions",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SKExternalPurchaseCustomLinkRegions"
        }
      ],
      "role": "symbol",
      "title": "SKExternalPurchaseCustomLinkRegions",
      "titleStyle": "symbol",
      "type": "topic",
      "url": "/documentation/bundleresources/information-property-list/skexternalpurchasecustomlinkregions"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/SKExternalPurchaseLink": {
      "abstract": [
        {
          "text": "A dictionary that contains URLs to websites where people using your app can make external purchases for supported regions.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/SKExternalPurchaseLink",
      "kind": "symbol",
      "name": "SKExternalPurchaseLink",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SKExternalPurchaseLink"
        }
      ],
      "role": "symbol",
      "title": "SKExternalPurchaseLink",
      "titleStyle": "symbol",
      "type": "topic",
      "url": "/documentation/bundleresources/information-property-list/skexternalpurchaselink"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/SKExternalPurchaseMultiLink": {
      "abstract": [
        {
          "text": "A dictionary that contains an array of URLs to websites where people using your app can make external purchases.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/SKExternalPurchaseMultiLink",
      "kind": "symbol",
      "name": "SKExternalPurchaseMultiLink",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SKExternalPurchaseMultiLink"
        }
      ],
      "role": "symbol",
      "title": "SKExternalPurchaseMultiLink",
      "titleStyle": "symbol",
      "type": "topic",
      "url": "/documentation/bundleresources/information-property-list/skexternalpurchasemultilink"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/SKIncludeConsumableInAppPurchaseHistory": {
      "abstract": [
        {
          "text": "A Boolean value that determines whether StoreKit includes finished consumable In-App Purchases in transaction information.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/SKIncludeConsumableInAppPurchaseHistory",
      "kind": "symbol",
      "name": "SKIncludeConsumableInAppPurchaseHistory",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SKIncludeConsumableInAppPurchaseHistory"
        }
      ],
      "role": "symbol",
      "title": "SKIncludeConsumableInAppPurchaseHistory",
      "titleStyle": "symbol",
      "type": "topic",
      "url": "/documentation/bundleresources/information-property-list/skincludeconsumableinapppurchasehistory"
    },
    "doc://com.apple.documentation/documentation/StoreKit/external-purchase": {
      "abstract": [
        {
          "text": "Enable qualifying apps to offer external purchases.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/StoreKit/external-purchase",
      "kind": "article",
      "role": "article",
      "title": "External Purchase",
      "type": "topic",
      "url": "/documentation/StoreKit/external-purchase"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "StoreKit",
      "generated": true,
      "identifiers": [
        "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/SKAdNetworkItems",
        "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/SKExternalLinkAccount",
        "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/SKExternalPurchaseCustomLinkRegions",
        "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/SKExternalPurchaseLink",
        "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/SKExternalPurchaseMultiLink",
        "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/SKIncludeConsumableInAppPurchaseHistory"
      ],
      "title": "StoreKit"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "15.4",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "15.4",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "17.4",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "14.4",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "17.4",
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.4",
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Property List Key"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "SKExternalPurchase"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "typealias"
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SKExternalPurchase"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.bundleresources/documentation/BundleResources",
                "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "StoreKit",
              "generated": true,
              "identifiers": [
                "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/SKAdNetworkItems",
                "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/SKExternalLinkAccount",
                "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/SKExternalPurchaseCustomLinkRegions",
                "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/SKExternalPurchaseLink",
                "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/SKExternalPurchaseMultiLink",
                "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/SKIncludeConsumableInAppPurchaseHistory"
              ],
              "title": "StoreKit"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1SKExternalPurchaseMultiLink/title",
          "value": "SKExternalPurchaseMultiLink"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1SKExternalPurchaseMultiLink/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SKExternalPurchaseMultiLink"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1SKIncludeConsumableInAppPurchaseHistory/title",
          "value": "SKIncludeConsumableInAppPurchaseHistory"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1SKIncludeConsumableInAppPurchaseHistory/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SKIncludeConsumableInAppPurchaseHistory"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1SKExternalPurchase/title",
          "value": "SKExternalPurchase"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1SKExternalPurchase/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SKExternalPurchase"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1SKExternalLinkAccount/title",
          "value": "SKExternalLinkAccount"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1SKExternalLinkAccount/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SKExternalLinkAccount"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1SKExternalPurchaseLink/title",
          "value": "SKExternalPurchaseLink"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1SKExternalPurchaseLink/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SKExternalPurchaseLink"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List/title",
          "value": "Information Property List"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "Information Property List"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1SKExternalPurchaseCustomLinkRegions/title",
          "value": "SKExternalPurchaseCustomLinkRegions"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1SKExternalPurchaseCustomLinkRegions/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SKExternalPurchaseCustomLinkRegions"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1SKAdNetworkItems/title",
          "value": "SKAdNetworkItems"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1SKAdNetworkItems/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SKAdNetworkItems"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Entitlements~1com.apple.developer.storekit.external-purchase/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "com.apple.developer.storekit.external-purchase"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/bundleresources/information-property-list/skexternalpurchase"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/bundleresources/information-property-list/skexternalpurchase"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
