{
  "abstract": [
    {
      "text": "A dictionary that contains localized URLs to an external website for account creation or management.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.bundleresources/documentation/BundleResources",
        "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/SKExternalLinkAccount"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "plist:Information_Property_List.SKExternalLinkAccount",
    "modules": [
      {
        "name": "Bundle Resources"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "SKExternalLinkAccount"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "15.4",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "15.4",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "16.4",
        "name": "tvOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Property List Key",
    "symbolKind": "dictionary",
    "title": "SKExternalLinkAccount"
  },
  "primaryContentSections": [
    {
      "details": {
        "name": "SKExternalLinkAccount",
        "platforms": [],
        "titleStyle": "symbol",
        "value": [
          {
            "arrayMode": false,
            "baseType": "object"
          }
        ]
      },
      "kind": "details",
      "title": "Details"
    },
    {
      "items": [
        {
          "attributes": [],
          "content": [],
          "introducedVersion": "15.4.0",
          "name": "Any Key",
          "required": false,
          "type": [
            {
              "kind": "text",
              "text": "string"
            }
          ]
        }
      ],
      "kind": "properties",
      "title": "Properties"
    },
    {
      "content": [
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Use this information property list key if your app has the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Entitlements/com.apple.developer.storekit.external-link.account",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " entitlement.",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "Each key is a string that is a lowercase ISO 3166-1 alpha-2 country code, the value for which is a URL to the localized version of the external website for that locale.",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "The dictionary must contain a key with the string ",
              "type": "text"
            },
            {
              "code": "*",
              "type": "codeVoice"
            },
            {
              "text": " that maps to a default URL.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "The following shows a property list with a default URL and a specific URL for the ",
              "type": "text"
            },
            {
              "code": "jp",
              "type": "codeVoice"
            },
            {
              "text": " locale:",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "code": [
            "<plist>",
            "<dict>",
            "    <key>SKExternalLinkAccount</key>",
            "    <dict>",
            "        <key>*</key>",
            "        <string>https://example.com</string>",
            "        <key>jp</key>",
            "        <string>https://example.com/jp</string>",
            "    </dict>",
            "</dict>",
            "</plist>"
          ],
          "syntax": "xml",
          "type": "codeListing"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.bundleresources/documentation/BundleResources": {
      "abstract": [
        {
          "text": "Resources located in an app, framework, or plugin bundle.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources",
      "kind": "symbol",
      "role": "collection",
      "title": "Bundle Resources",
      "type": "topic",
      "url": "/documentation/bundleresources"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/Entitlements/com.apple.developer.storekit.external-link.account": {
      "abstract": [
        {
          "text": "A Boolean value that indicates whether your app can link to an external website for account creation or management.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Entitlements/com.apple.developer.storekit.external-link.account",
      "kind": "symbol",
      "name": "com.apple.developer.storekit.external-link.account",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "com.apple.developer.storekit.external-link.account"
        }
      ],
      "role": "symbol",
      "title": "com.apple.developer.storekit.external-link.account",
      "titleStyle": "title",
      "type": "topic",
      "url": "/documentation/bundleresources/entitlements/com.apple.developer.storekit.external-link.account"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List": {
      "abstract": [
        {
          "text": "A resource containing key-value pairs that identify and configure a bundle.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List",
      "kind": "symbol",
      "name": "Information Property List",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "Information Property List"
        }
      ],
      "role": "symbol",
      "title": "Information Property List",
      "titleStyle": "symbol",
      "type": "topic",
      "url": "/documentation/bundleresources/information-property-list"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/SKAdNetworkItems": {
      "abstract": [
        {
          "text": "An array of dictionaries containing a list of ad network IDs.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/SKAdNetworkItems",
      "kind": "symbol",
      "name": "SKAdNetworkItems",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SKAdNetworkItems"
        }
      ],
      "role": "symbol",
      "title": "SKAdNetworkItems",
      "titleStyle": "symbol",
      "type": "topic",
      "url": "/documentation/bundleresources/information-property-list/skadnetworkitems"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/SKExternalLinkAccount": {
      "abstract": [
        {
          "text": "A dictionary that contains localized URLs to an external website for account creation or management.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/SKExternalLinkAccount",
      "kind": "symbol",
      "name": "SKExternalLinkAccount",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SKExternalLinkAccount"
        }
      ],
      "role": "symbol",
      "title": "SKExternalLinkAccount",
      "titleStyle": "symbol",
      "type": "topic",
      "url": "/documentation/bundleresources/information-property-list/skexternallinkaccount"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/SKExternalPurchase": {
      "abstract": [
        {
          "text": "A string array of country codes that indicates your app supports external purchases.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/SKExternalPurchase",
      "kind": "symbol",
      "name": "SKExternalPurchase",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SKExternalPurchase"
        }
      ],
      "role": "symbol",
      "title": "SKExternalPurchase",
      "titleStyle": "symbol",
      "type": "topic",
      "url": "/documentation/bundleresources/information-property-list/skexternalpurchase"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/SKExternalPurchaseCustomLinkRegions": {
      "abstract": [
        {
          "text": "An array of country code strings that indicate the regions where your app supports custom links for external purchases.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/SKExternalPurchaseCustomLinkRegions",
      "kind": "symbol",
      "name": "SKExternalPurchaseCustomLinkRegions",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SKExternalPurchaseCustomLinkRegions"
        }
      ],
      "role": "symbol",
      "title": "SKExternalPurchaseCustomLinkRegions",
      "titleStyle": "symbol",
      "type": "topic",
      "url": "/documentation/bundleresources/information-property-list/skexternalpurchasecustomlinkregions"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/SKExternalPurchaseLink": {
      "abstract": [
        {
          "text": "A dictionary that contains URLs to websites where people using your app can make external purchases for supported regions.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/SKExternalPurchaseLink",
      "kind": "symbol",
      "name": "SKExternalPurchaseLink",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SKExternalPurchaseLink"
        }
      ],
      "role": "symbol",
      "title": "SKExternalPurchaseLink",
      "titleStyle": "symbol",
      "type": "topic",
      "url": "/documentation/bundleresources/information-property-list/skexternalpurchaselink"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/SKExternalPurchaseMultiLink": {
      "abstract": [
        {
          "text": "A dictionary that contains an array of URLs to websites where people using your app can make external purchases.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/SKExternalPurchaseMultiLink",
      "kind": "symbol",
      "name": "SKExternalPurchaseMultiLink",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SKExternalPurchaseMultiLink"
        }
      ],
      "role": "symbol",
      "title": "SKExternalPurchaseMultiLink",
      "titleStyle": "symbol",
      "type": "topic",
      "url": "/documentation/bundleresources/information-property-list/skexternalpurchasemultilink"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/SKIncludeConsumableInAppPurchaseHistory": {
      "abstract": [
        {
          "text": "A Boolean value that determines whether StoreKit includes finished consumable In-App Purchases in transaction information.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/SKIncludeConsumableInAppPurchaseHistory",
      "kind": "symbol",
      "name": "SKIncludeConsumableInAppPurchaseHistory",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SKIncludeConsumableInAppPurchaseHistory"
        }
      ],
      "role": "symbol",
      "title": "SKIncludeConsumableInAppPurchaseHistory",
      "titleStyle": "symbol",
      "type": "topic",
      "url": "/documentation/bundleresources/information-property-list/skincludeconsumableinapppurchasehistory"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "StoreKit",
      "generated": true,
      "identifiers": [
        "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/SKAdNetworkItems",
        "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/SKExternalPurchase",
        "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/SKExternalPurchaseCustomLinkRegions",
        "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/SKExternalPurchaseLink",
        "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/SKExternalPurchaseMultiLink",
        "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/SKIncludeConsumableInAppPurchaseHistory"
      ],
      "title": "StoreKit"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "15.4",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "15.4",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "16.4",
              "name": "tvOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Property List Key"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "SKExternalLinkAccount"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "dictionary"
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SKExternalLinkAccount"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.bundleresources/documentation/BundleResources",
                "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "StoreKit",
              "generated": true,
              "identifiers": [
                "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/SKAdNetworkItems",
                "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/SKExternalPurchase",
                "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/SKExternalPurchaseCustomLinkRegions",
                "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/SKExternalPurchaseLink",
                "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/SKExternalPurchaseMultiLink",
                "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/SKIncludeConsumableInAppPurchaseHistory"
              ],
              "title": "StoreKit"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/3",
          "value": {
            "items": [
              {
                "attributes": [],
                "content": [],
                "introducedVersion": "15.4.0",
                "name": "Any Key",
                "required": false,
                "type": [
                  {
                    "kind": "text",
                    "text": "string"
                  }
                ]
              }
            ],
            "kind": "properties",
            "title": "Properties"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1SKExternalLinkAccount/title",
          "value": "SKExternalLinkAccount"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1SKExternalLinkAccount/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SKExternalLinkAccount"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1SKAdNetworkItems/title",
          "value": "SKAdNetworkItems"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1SKAdNetworkItems/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SKAdNetworkItems"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1SKExternalPurchaseMultiLink/title",
          "value": "SKExternalPurchaseMultiLink"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1SKExternalPurchaseMultiLink/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SKExternalPurchaseMultiLink"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Entitlements~1com.apple.developer.storekit.external-link.account/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "com.apple.developer.storekit.external-link.account"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1SKExternalPurchase/title",
          "value": "SKExternalPurchase"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1SKExternalPurchase/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SKExternalPurchase"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1SKExternalPurchaseLink/title",
          "value": "SKExternalPurchaseLink"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1SKExternalPurchaseLink/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SKExternalPurchaseLink"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List/title",
          "value": "Information Property List"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "Information Property List"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1SKExternalPurchaseCustomLinkRegions/title",
          "value": "SKExternalPurchaseCustomLinkRegions"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1SKExternalPurchaseCustomLinkRegions/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SKExternalPurchaseCustomLinkRegions"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1SKIncludeConsumableInAppPurchaseHistory/title",
          "value": "SKIncludeConsumableInAppPurchaseHistory"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1SKIncludeConsumableInAppPurchaseHistory/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SKIncludeConsumableInAppPurchaseHistory"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/bundleresources/information-property-list/skexternallinkaccount"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/bundleresources/information-property-list/skexternallinkaccount"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
