{
  "abstract": [
    {
      "text": "A dictionary that contains an array of URLs to websites where people using your app can make external purchases.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.bundleresources/documentation/BundleResources",
        "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/SKExternalPurchaseMultiLink"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "plist:Information_Property_List.SKExternalPurchaseMultiLink",
    "modules": [
      {
        "name": "Bundle Resources"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "SKExternalPurchaseMultiLink"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "17.5",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "17.5",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "17.5",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "14.5",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "17.5",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.2",
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.5",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Property List Key",
    "symbolKind": "dictionary",
    "title": "SKExternalPurchaseMultiLink"
  },
  "primaryContentSections": [
    {
      "details": {
        "name": "SKExternalPurchaseMultiLink",
        "platforms": [],
        "titleStyle": "symbol",
        "value": [
          {
            "arrayMode": false,
            "baseType": "object"
          }
        ]
      },
      "kind": "details",
      "title": "Details"
    },
    {
      "items": [
        {
          "attributes": [],
          "content": [],
          "introducedVersion": "17.5.0",
          "name": "Any Key",
          "required": false,
          "type": [
            {
              "kind": "text",
              "text": "[string]"
            }
          ]
        }
      ],
      "kind": "properties",
      "title": "Properties"
    },
    {
      "content": [
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Use this information property list key if your app has the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Entitlements/com.apple.developer.storekit.external-purchase-link",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " entitlement.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "The keys for this dictionary are lowercased ISO 3166-1 alpha-2 country codes.",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "Valid country codes include those for the European Union: Austria (",
              "type": "text"
            },
            {
              "code": "at",
              "type": "codeVoice"
            },
            {
              "text": "), Belgium (",
              "type": "text"
            },
            {
              "code": "be",
              "type": "codeVoice"
            },
            {
              "text": "), Bulgaria (",
              "type": "text"
            },
            {
              "code": "bg",
              "type": "codeVoice"
            },
            {
              "text": "), Croatia (",
              "type": "text"
            },
            {
              "code": "hr",
              "type": "codeVoice"
            },
            {
              "text": "), Cyprus (",
              "type": "text"
            },
            {
              "code": "cy",
              "type": "codeVoice"
            },
            {
              "text": "), Czechia (",
              "type": "text"
            },
            {
              "code": "cz",
              "type": "codeVoice"
            },
            {
              "text": "), Denmark (",
              "type": "text"
            },
            {
              "code": "dk",
              "type": "codeVoice"
            },
            {
              "text": "), Estonia (",
              "type": "text"
            },
            {
              "code": "ee",
              "type": "codeVoice"
            },
            {
              "text": "), Finland (",
              "type": "text"
            },
            {
              "code": "fi",
              "type": "codeVoice"
            },
            {
              "text": "), France (",
              "type": "text"
            },
            {
              "code": "fr",
              "type": "codeVoice"
            },
            {
              "text": "), Germany (",
              "type": "text"
            },
            {
              "code": "de",
              "type": "codeVoice"
            },
            {
              "text": "), Greece (",
              "type": "text"
            },
            {
              "code": "gr",
              "type": "codeVoice"
            },
            {
              "text": "), Hungary (",
              "type": "text"
            },
            {
              "code": "hu",
              "type": "codeVoice"
            },
            {
              "text": "), Ireland (",
              "type": "text"
            },
            {
              "code": "ie",
              "type": "codeVoice"
            },
            {
              "text": "), Italy (",
              "type": "text"
            },
            {
              "code": "it",
              "type": "codeVoice"
            },
            {
              "text": "), Latvia (",
              "type": "text"
            },
            {
              "code": "lv",
              "type": "codeVoice"
            },
            {
              "text": "), Lithuania (",
              "type": "text"
            },
            {
              "code": "lt",
              "type": "codeVoice"
            },
            {
              "text": "), Luxembourg (",
              "type": "text"
            },
            {
              "code": "lu",
              "type": "codeVoice"
            },
            {
              "text": "), Malta (",
              "type": "text"
            },
            {
              "code": "mt",
              "type": "codeVoice"
            },
            {
              "text": "), Netherlands (",
              "type": "text"
            },
            {
              "code": "nl",
              "type": "codeVoice"
            },
            {
              "text": "), Poland (",
              "type": "text"
            },
            {
              "code": "pl",
              "type": "codeVoice"
            },
            {
              "text": "), Portugal (",
              "type": "text"
            },
            {
              "code": "pt",
              "type": "codeVoice"
            },
            {
              "text": "), Romania (",
              "type": "text"
            },
            {
              "code": "ro",
              "type": "codeVoice"
            },
            {
              "text": "), Slovakia (",
              "type": "text"
            },
            {
              "code": "sk",
              "type": "codeVoice"
            },
            {
              "text": "), Slovenia (",
              "type": "text"
            },
            {
              "code": "si",
              "type": "codeVoice"
            },
            {
              "text": "), Spain (",
              "type": "text"
            },
            {
              "code": "es",
              "type": "codeVoice"
            },
            {
              "text": "), Sweden (",
              "type": "text"
            },
            {
              "code": "se",
              "type": "codeVoice"
            },
            {
              "text": "); and Iceland (",
              "type": "text"
            },
            {
              "code": "is",
              "type": "codeVoice"
            },
            {
              "text": "), Norway (",
              "type": "text"
            },
            {
              "code": "no",
              "type": "codeVoice"
            },
            {
              "text": "), Russia (",
              "type": "text"
            },
            {
              "code": "ru",
              "type": "codeVoice"
            },
            {
              "text": "), and United States (",
              "type": "text"
            },
            {
              "code": "us",
              "type": "codeVoice"
            },
            {
              "text": ").",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "Include a key entry for each country code where your app supports an external purchase link. Provide from one to five destination URLs (links to your website) for your app to choose from for each country code.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "",
                  "type": "text"
                },
                {
                  "text": " ",
                  "type": "text"
                },
                {
                  "text": "You can provide up to five links if your app qualifies for the StoreKit External Purchase Link entitlement as described in ",
                  "type": "text"
                },
                {
                  "identifier": "https://developer.apple.com/support/music-streaming-services-entitlement-eea/",
                  "isActive": true,
                  "type": "reference"
                },
                {
                  "text": ".  Otherwise, provide one link for each country code.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "Note",
          "style": "note",
          "type": "aside"
        },
        {
          "inlineContent": [
            {
              "text": "Your app accesses these URLs through the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/StoreKit/ExternalPurchaseLink/eligibleURLs",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " array in the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/StoreKit/ExternalPurchaseLink",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " object, and uses the link you select with the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/StoreKit/ExternalPurchaseLink/open(url:)",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " method in the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/StoreKit/ExternalPurchaseLink",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " object.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "",
                  "type": "text"
                },
                {
                  "text": " ",
                  "type": "text"
                },
                {
                  "text": "At all times, the destination URLs that you provide in the property list key must match the values in your app binary that you submit to App Review.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "Important",
          "style": "important",
          "type": "aside"
        },
        {
          "inlineContent": [
            {
              "text": "Make sure each destination URL meets all of the following conditions:",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "items": [
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Uses the HTTPS scheme",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Forms a valid, absolute URL",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Contains no query parameters",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Contains 1,000 or fewer ASCII characters",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            }
          ],
          "type": "unorderedList"
        },
        {
          "inlineContent": [
            {
              "text": "The following code example shows a property list entry with keys for several country codes, and links for each entry:",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "code": [
            "<key>SKExternalPurchaseMultiLink</key>",
            "<dict>",
            "    <key>es</key>",
            "    <array>",
            "        <string>https://www.example.com/es1</string>",
            "        <string>https://www.example.com/new-user-es</string>",
            "        <string>https://www.example.com/seasonal-sale-es</string>",
            "        <string>https://www.example.com/es2</string>",
            "        <string>https://www.example.com/es3</string>",
            "    </array>",
            "    <key>fr</key>",
            "    <array>",
            "        <string>https://www.example.com/fr</string>",
            "        <string>https://www.example.com/global-sale</string>",
            "        <string>https://www.example.com/new-user-fr</string>",
            "    </array>",
            "    <key>it</key>",
            "    <array>",
            "        <string>https://www.example.com/global-sale</string>",
            "    </array>",
            "</dict>"
          ],
          "syntax": "xml",
          "type": "codeListing"
        },
        {
          "inlineContent": [
            {
              "text": "The order of the links is not significant.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "For more information, see ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/StoreKit/external-purchase",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " and ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/StoreKit/ExternalPurchaseLink",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ".",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "anchor": "Provide-up-to-the-maximum-number-of-links",
          "level": 3,
          "text": "Provide up to the maximum number of links",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "The following country codes have a maximum of five links for apps that qualify for the StoreKit External Purchase Link entitlement as described in ",
              "type": "text"
            },
            {
              "identifier": "https://developer.apple.com/support/music-streaming-services-entitlement-eea/",
              "isActive": true,
              "overridingTitle": "Distributing music streaming apps in the EEA that provide an external purchase link",
              "overridingTitleInlineContent": [
                {
                  "text": "Distributing music streaming apps in the EEA that provide an external purchase link",
                  "type": "text"
                }
              ],
              "type": "reference"
            },
            {
              "text": ": Austria (",
              "type": "text"
            },
            {
              "code": "at",
              "type": "codeVoice"
            },
            {
              "text": "), Belgium (",
              "type": "text"
            },
            {
              "code": "be",
              "type": "codeVoice"
            },
            {
              "text": "), Bulgaria (",
              "type": "text"
            },
            {
              "code": "bg",
              "type": "codeVoice"
            },
            {
              "text": "), Croatia (",
              "type": "text"
            },
            {
              "code": "hr",
              "type": "codeVoice"
            },
            {
              "text": "), Cyprus (",
              "type": "text"
            },
            {
              "code": "cy",
              "type": "codeVoice"
            },
            {
              "text": "), Czechia (",
              "type": "text"
            },
            {
              "code": "cz",
              "type": "codeVoice"
            },
            {
              "text": "), Denmark (",
              "type": "text"
            },
            {
              "code": "dk",
              "type": "codeVoice"
            },
            {
              "text": "), Estonia (",
              "type": "text"
            },
            {
              "code": "ee",
              "type": "codeVoice"
            },
            {
              "text": "), Finland (",
              "type": "text"
            },
            {
              "code": "fi",
              "type": "codeVoice"
            },
            {
              "text": "), France (",
              "type": "text"
            },
            {
              "code": "fr",
              "type": "codeVoice"
            },
            {
              "text": "), Germany (",
              "type": "text"
            },
            {
              "code": "de",
              "type": "codeVoice"
            },
            {
              "text": "), Greece (",
              "type": "text"
            },
            {
              "code": "gr",
              "type": "codeVoice"
            },
            {
              "text": "), Hungary (",
              "type": "text"
            },
            {
              "code": "hu",
              "type": "codeVoice"
            },
            {
              "text": "), Ireland (",
              "type": "text"
            },
            {
              "code": "ie",
              "type": "codeVoice"
            },
            {
              "text": "), Italy (",
              "type": "text"
            },
            {
              "code": "it",
              "type": "codeVoice"
            },
            {
              "text": "), Latvia (",
              "type": "text"
            },
            {
              "code": "lv",
              "type": "codeVoice"
            },
            {
              "text": "), Lithuania (",
              "type": "text"
            },
            {
              "code": "lt",
              "type": "codeVoice"
            },
            {
              "text": "), Luxembourg (",
              "type": "text"
            },
            {
              "code": "lu",
              "type": "codeVoice"
            },
            {
              "text": "), Malta (",
              "type": "text"
            },
            {
              "code": "mt",
              "type": "codeVoice"
            },
            {
              "text": "), Netherlands (",
              "type": "text"
            },
            {
              "code": "nl",
              "type": "codeVoice"
            },
            {
              "text": "), Poland (",
              "type": "text"
            },
            {
              "code": "pl",
              "type": "codeVoice"
            },
            {
              "text": "), Portugal (",
              "type": "text"
            },
            {
              "code": "pt",
              "type": "codeVoice"
            },
            {
              "text": "), Romania (",
              "type": "text"
            },
            {
              "code": "ro",
              "type": "codeVoice"
            },
            {
              "text": "), Slovakia (",
              "type": "text"
            },
            {
              "code": "sk",
              "type": "codeVoice"
            },
            {
              "text": "), Slovenia (",
              "type": "text"
            },
            {
              "code": "si",
              "type": "codeVoice"
            },
            {
              "text": "), Spain (",
              "type": "text"
            },
            {
              "code": "es",
              "type": "codeVoice"
            },
            {
              "text": "), Sweden (",
              "type": "text"
            },
            {
              "code": "se",
              "type": "codeVoice"
            },
            {
              "text": "), Iceland (",
              "type": "text"
            },
            {
              "code": "is",
              "type": "codeVoice"
            },
            {
              "text": "), Norway (",
              "type": "text"
            },
            {
              "code": "no",
              "type": "codeVoice"
            },
            {
              "text": "). Otherwise, the maximum is one link, for valid country codes.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "Count the total number of unique links you provide for each country code by adding together the number of links you provide in the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/SKExternalPurchaseMultiLink",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " and ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/SKExternalPurchaseLink",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " property list keys.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "For example, if a country code has a maximum of five links and you provide five unique links in the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/SKExternalPurchaseMultiLink",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " key, then specify one of the same five links in the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/SKExternalPurchaseLink",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " key to avoid exceeding the maximum allowed links.  If a country code has a maximum of one link, the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/SKExternalPurchaseMultiLink",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " and ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/SKExternalPurchaseLink",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " keys need to specify the same link.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.bundleresources/documentation/BundleResources": {
      "abstract": [
        {
          "text": "Resources located in an app, framework, or plugin bundle.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources",
      "kind": "symbol",
      "role": "collection",
      "title": "Bundle Resources",
      "type": "topic",
      "url": "/documentation/bundleresources"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/Entitlements/com.apple.developer.storekit.external-purchase-link": {
      "abstract": [
        {
          "text": "A Boolean value that indicates whether your app can include a link that directs people to a website to make an external purchase.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Entitlements/com.apple.developer.storekit.external-purchase-link",
      "kind": "symbol",
      "name": "com.apple.developer.storekit.external-purchase-link",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "com.apple.developer.storekit.external-purchase-link"
        }
      ],
      "role": "symbol",
      "title": "com.apple.developer.storekit.external-purchase-link",
      "titleStyle": "title",
      "type": "topic",
      "url": "/documentation/bundleresources/entitlements/com.apple.developer.storekit.external-purchase-link"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List": {
      "abstract": [
        {
          "text": "A resource containing key-value pairs that identify and configure a bundle.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List",
      "kind": "symbol",
      "name": "Information Property List",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "Information Property List"
        }
      ],
      "role": "symbol",
      "title": "Information Property List",
      "titleStyle": "symbol",
      "type": "topic",
      "url": "/documentation/bundleresources/information-property-list"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/SKAdNetworkItems": {
      "abstract": [
        {
          "text": "An array of dictionaries containing a list of ad network IDs.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/SKAdNetworkItems",
      "kind": "symbol",
      "name": "SKAdNetworkItems",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SKAdNetworkItems"
        }
      ],
      "role": "symbol",
      "title": "SKAdNetworkItems",
      "titleStyle": "symbol",
      "type": "topic",
      "url": "/documentation/bundleresources/information-property-list/skadnetworkitems"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/SKExternalLinkAccount": {
      "abstract": [
        {
          "text": "A dictionary that contains localized URLs to an external website for account creation or management.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/SKExternalLinkAccount",
      "kind": "symbol",
      "name": "SKExternalLinkAccount",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SKExternalLinkAccount"
        }
      ],
      "role": "symbol",
      "title": "SKExternalLinkAccount",
      "titleStyle": "symbol",
      "type": "topic",
      "url": "/documentation/bundleresources/information-property-list/skexternallinkaccount"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/SKExternalPurchase": {
      "abstract": [
        {
          "text": "A string array of country codes that indicates your app supports external purchases.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/SKExternalPurchase",
      "kind": "symbol",
      "name": "SKExternalPurchase",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SKExternalPurchase"
        }
      ],
      "role": "symbol",
      "title": "SKExternalPurchase",
      "titleStyle": "symbol",
      "type": "topic",
      "url": "/documentation/bundleresources/information-property-list/skexternalpurchase"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/SKExternalPurchaseCustomLinkRegions": {
      "abstract": [
        {
          "text": "An array of country code strings that indicate the regions where your app supports custom links for external purchases.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/SKExternalPurchaseCustomLinkRegions",
      "kind": "symbol",
      "name": "SKExternalPurchaseCustomLinkRegions",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SKExternalPurchaseCustomLinkRegions"
        }
      ],
      "role": "symbol",
      "title": "SKExternalPurchaseCustomLinkRegions",
      "titleStyle": "symbol",
      "type": "topic",
      "url": "/documentation/bundleresources/information-property-list/skexternalpurchasecustomlinkregions"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/SKExternalPurchaseLink": {
      "abstract": [
        {
          "text": "A dictionary that contains URLs to websites where people using your app can make external purchases for supported regions.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/SKExternalPurchaseLink",
      "kind": "symbol",
      "name": "SKExternalPurchaseLink",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SKExternalPurchaseLink"
        }
      ],
      "role": "symbol",
      "title": "SKExternalPurchaseLink",
      "titleStyle": "symbol",
      "type": "topic",
      "url": "/documentation/bundleresources/information-property-list/skexternalpurchaselink"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/SKExternalPurchaseMultiLink": {
      "abstract": [
        {
          "text": "A dictionary that contains an array of URLs to websites where people using your app can make external purchases.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/SKExternalPurchaseMultiLink",
      "kind": "symbol",
      "name": "SKExternalPurchaseMultiLink",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SKExternalPurchaseMultiLink"
        }
      ],
      "role": "symbol",
      "title": "SKExternalPurchaseMultiLink",
      "titleStyle": "symbol",
      "type": "topic",
      "url": "/documentation/bundleresources/information-property-list/skexternalpurchasemultilink"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/SKIncludeConsumableInAppPurchaseHistory": {
      "abstract": [
        {
          "text": "A Boolean value that determines whether StoreKit includes finished consumable In-App Purchases in transaction information.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/SKIncludeConsumableInAppPurchaseHistory",
      "kind": "symbol",
      "name": "SKIncludeConsumableInAppPurchaseHistory",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SKIncludeConsumableInAppPurchaseHistory"
        }
      ],
      "role": "symbol",
      "title": "SKIncludeConsumableInAppPurchaseHistory",
      "titleStyle": "symbol",
      "type": "topic",
      "url": "/documentation/bundleresources/information-property-list/skincludeconsumableinapppurchasehistory"
    },
    "doc://com.apple.documentation/documentation/StoreKit/ExternalPurchaseLink": {
      "abstract": [
        {
          "text": "Enables qualifying apps to offer external purchase links.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ExternalPurchaseLink"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/StoreKit/ExternalPurchaseLink",
      "kind": "symbol",
      "role": "symbol",
      "title": "ExternalPurchaseLink",
      "type": "topic",
      "url": "/documentation/StoreKit/ExternalPurchaseLink"
    },
    "doc://com.apple.documentation/documentation/StoreKit/ExternalPurchaseLink/eligibleURLs": {
      "abstract": [
        {
          "text": "An array of external purchase links for the current storefront that the app configured and from which it chooses.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "eligibleURLs"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10Foundation3URLV",
          "text": "URL"
        },
        {
          "kind": "text",
          "text": "]? { "
        },
        {
          "kind": "keyword",
          "text": "get"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "async"
        },
        {
          "kind": "text",
          "text": " }"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/StoreKit/ExternalPurchaseLink/eligibleURLs",
      "kind": "symbol",
      "role": "symbol",
      "title": "eligibleURLs",
      "type": "topic",
      "url": "/documentation/StoreKit/ExternalPurchaseLink/eligibleURLs"
    },
    "doc://com.apple.documentation/documentation/StoreKit/ExternalPurchaseLink/open(url:)": {
      "abstract": [
        {
          "text": "Presents a continuation sheet that enables people to choose whether your app shows the indicated URL link for external purchases.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "open"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "url"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10Foundation3URLV",
          "text": "URL"
        },
        {
          "kind": "text",
          "text": ") "
        },
        {
          "kind": "keyword",
          "text": "async"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "throws"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/StoreKit/ExternalPurchaseLink/open(url:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "open(url:)",
      "type": "topic",
      "url": "/documentation/StoreKit/ExternalPurchaseLink/open(url:)"
    },
    "doc://com.apple.documentation/documentation/StoreKit/external-purchase": {
      "abstract": [
        {
          "text": "Enable qualifying apps to offer external purchases.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/StoreKit/external-purchase",
      "kind": "article",
      "role": "article",
      "title": "External Purchase",
      "type": "topic",
      "url": "/documentation/StoreKit/external-purchase"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "https://developer.apple.com/support/music-streaming-services-entitlement-eea/": {
      "identifier": "https://developer.apple.com/support/music-streaming-services-entitlement-eea/",
      "title": "Distributing music streaming apps in the EEA that provide an external purchase link",
      "titleInlineContent": [
        {
          "text": "Distributing music streaming apps in the EEA that provide an external purchase link",
          "type": "text"
        }
      ],
      "type": "link",
      "url": "https://developer.apple.com/support/music-streaming-services-entitlement-eea/"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "StoreKit",
      "generated": true,
      "identifiers": [
        "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/SKAdNetworkItems",
        "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/SKExternalLinkAccount",
        "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/SKExternalPurchase",
        "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/SKExternalPurchaseCustomLinkRegions",
        "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/SKExternalPurchaseLink",
        "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/SKIncludeConsumableInAppPurchaseHistory"
      ],
      "title": "StoreKit"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "17.5",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "17.5",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "17.5",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "14.5",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "17.5",
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.2",
              "name": "visionOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.5",
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Property List Key"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "SKExternalPurchaseMultiLink"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "dictionary"
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SKExternalPurchaseMultiLink"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.bundleresources/documentation/BundleResources",
                "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "StoreKit",
              "generated": true,
              "identifiers": [
                "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/SKAdNetworkItems",
                "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/SKExternalLinkAccount",
                "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/SKExternalPurchase",
                "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/SKExternalPurchaseCustomLinkRegions",
                "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/SKExternalPurchaseLink",
                "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/SKIncludeConsumableInAppPurchaseHistory"
              ],
              "title": "StoreKit"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/3",
          "value": {
            "items": [
              {
                "attributes": [],
                "content": [],
                "introducedVersion": "17.5.0",
                "name": "Any Key",
                "required": false,
                "type": [
                  {
                    "kind": "text",
                    "text": "[string]"
                  }
                ]
              }
            ],
            "kind": "properties",
            "title": "Properties"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1SKExternalLinkAccount/title",
          "value": "SKExternalLinkAccount"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1SKExternalLinkAccount/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SKExternalLinkAccount"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1SKIncludeConsumableInAppPurchaseHistory/title",
          "value": "SKIncludeConsumableInAppPurchaseHistory"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1SKIncludeConsumableInAppPurchaseHistory/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SKIncludeConsumableInAppPurchaseHistory"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List/title",
          "value": "Information Property List"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "Information Property List"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1SKAdNetworkItems/title",
          "value": "SKAdNetworkItems"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1SKAdNetworkItems/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SKAdNetworkItems"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1SKExternalPurchaseCustomLinkRegions/title",
          "value": "SKExternalPurchaseCustomLinkRegions"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1SKExternalPurchaseCustomLinkRegions/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SKExternalPurchaseCustomLinkRegions"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1SKExternalPurchaseMultiLink/title",
          "value": "SKExternalPurchaseMultiLink"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1SKExternalPurchaseMultiLink/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SKExternalPurchaseMultiLink"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1SKExternalPurchaseLink/title",
          "value": "SKExternalPurchaseLink"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1SKExternalPurchaseLink/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SKExternalPurchaseLink"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Entitlements~1com.apple.developer.storekit.external-purchase-link/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "com.apple.developer.storekit.external-purchase-link"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1SKExternalPurchase/title",
          "value": "SKExternalPurchase"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1SKExternalPurchase/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SKExternalPurchase"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/bundleresources/information-property-list/skexternalpurchasemultilink"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/bundleresources/information-property-list/skexternalpurchasemultilink"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
