{
  "abstract": [
    {
      "text": "A Boolean value that determines whether StoreKit includes finished consumable In-App Purchases in transaction information.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.bundleresources/documentation/BundleResources",
        "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/SKIncludeConsumableInAppPurchaseHistory"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "plist:Information_Property_List.SKIncludeConsumableInAppPurchaseHistory",
    "modules": [
      {
        "name": "Bundle Resources"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "SKIncludeConsumableInAppPurchaseHistory"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "18.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "18.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "18.0",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "15.0",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "18.0",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "2.0",
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "11.0",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Property List Key",
    "symbolKind": "typealias",
    "title": "SKIncludeConsumableInAppPurchaseHistory"
  },
  "primaryContentSections": [
    {
      "details": {
        "name": "SKIncludeConsumableInAppPurchaseHistory",
        "platforms": [],
        "titleStyle": "symbol",
        "value": [
          {
            "arrayMode": false,
            "baseType": "boolean"
          }
        ]
      },
      "kind": "details",
      "title": "Details"
    },
    {
      "content": [
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "By default, this value is ",
              "type": "text"
            },
            {
              "code": "false",
              "type": "codeVoice"
            },
            {
              "text": ". When it’s ",
              "type": "text"
            },
            {
              "code": "false",
              "type": "codeVoice"
            },
            {
              "text": ", StoreKit doesn’t return finished consumables (unless refunded or revoked) in the transaction information from the following APIs:",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "items": [
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "The ",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.documentation/documentation/StoreKit/Transaction/all",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": " sequence in ",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.documentation/documentation/StoreKit/Transaction",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": ", which returns the customer’s transaction history for your app",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "The ",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.documentation/documentation/StoreKit/Transaction/latest(for:)",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": " in ",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.documentation/documentation/StoreKit/Transaction",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": ", which returns the customer’s most recent transaction for a specific product",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "The ",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.documentation/documentation/StoreKit/Product/latestTransaction",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": " in ",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.documentation/documentation/StoreKit/Product",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": ", which provides the customer’s most recent transaction for the product",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            }
          ],
          "type": "unorderedList"
        },
        {
          "inlineContent": [
            {
              "text": "When you set this value to ",
              "type": "text"
            },
            {
              "code": "true",
              "type": "codeVoice"
            },
            {
              "text": ", StoreKit includes all In-App Purchase transactions — including all finished consumables — in the transaction information when you use the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/StoreKit/Transaction/all",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ", ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/StoreKit/Transaction/latest(for:)",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ", and ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/StoreKit/Product/latestTransaction",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " APIs.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "",
                  "type": "text"
                },
                {
                  "text": " ",
                  "type": "text"
                },
                {
                  "text": "Before you set ",
                  "type": "text"
                },
                {
                  "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/SKIncludeConsumableInAppPurchaseHistory",
                  "isActive": true,
                  "type": "reference"
                },
                {
                  "text": " to ",
                  "type": "text"
                },
                {
                  "code": "true",
                  "type": "codeVoice"
                },
                {
                  "text": ", be sure you have a way to reconcile a customer’s consumable transactions on your server, not only on the device. For example, store a transaction’s unique transaction identifier, ",
                  "type": "text"
                },
                {
                  "identifier": "doc://com.apple.documentation/documentation/StoreKit/Transaction/id",
                  "isActive": true,
                  "type": "reference"
                },
                {
                  "text": ", along with its finish state to avoid unintentionally delivering content multiple times if the customer reinstalls the app. Use ",
                  "type": "text"
                },
                {
                  "identifier": "doc://com.apple.documentation/documentation/StoreKit/Transaction/unfinished",
                  "isActive": true,
                  "type": "reference"
                },
                {
                  "text": " to get and process unfinished transactions.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "Warning",
          "style": "warning",
          "type": "aside"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.bundleresources/documentation/BundleResources": {
      "abstract": [
        {
          "text": "Resources located in an app, framework, or plugin bundle.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources",
      "kind": "symbol",
      "role": "collection",
      "title": "Bundle Resources",
      "type": "topic",
      "url": "/documentation/bundleresources"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List": {
      "abstract": [
        {
          "text": "A resource containing key-value pairs that identify and configure a bundle.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List",
      "kind": "symbol",
      "name": "Information Property List",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "Information Property List"
        }
      ],
      "role": "symbol",
      "title": "Information Property List",
      "titleStyle": "symbol",
      "type": "topic",
      "url": "/documentation/bundleresources/information-property-list"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/SKAdNetworkItems": {
      "abstract": [
        {
          "text": "An array of dictionaries containing a list of ad network IDs.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/SKAdNetworkItems",
      "kind": "symbol",
      "name": "SKAdNetworkItems",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SKAdNetworkItems"
        }
      ],
      "role": "symbol",
      "title": "SKAdNetworkItems",
      "titleStyle": "symbol",
      "type": "topic",
      "url": "/documentation/bundleresources/information-property-list/skadnetworkitems"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/SKExternalLinkAccount": {
      "abstract": [
        {
          "text": "A dictionary that contains localized URLs to an external website for account creation or management.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/SKExternalLinkAccount",
      "kind": "symbol",
      "name": "SKExternalLinkAccount",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SKExternalLinkAccount"
        }
      ],
      "role": "symbol",
      "title": "SKExternalLinkAccount",
      "titleStyle": "symbol",
      "type": "topic",
      "url": "/documentation/bundleresources/information-property-list/skexternallinkaccount"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/SKExternalPurchase": {
      "abstract": [
        {
          "text": "A string array of country codes that indicates your app supports external purchases.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/SKExternalPurchase",
      "kind": "symbol",
      "name": "SKExternalPurchase",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SKExternalPurchase"
        }
      ],
      "role": "symbol",
      "title": "SKExternalPurchase",
      "titleStyle": "symbol",
      "type": "topic",
      "url": "/documentation/bundleresources/information-property-list/skexternalpurchase"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/SKExternalPurchaseCustomLinkRegions": {
      "abstract": [
        {
          "text": "An array of country code strings that indicate the regions where your app supports custom links for external purchases.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/SKExternalPurchaseCustomLinkRegions",
      "kind": "symbol",
      "name": "SKExternalPurchaseCustomLinkRegions",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SKExternalPurchaseCustomLinkRegions"
        }
      ],
      "role": "symbol",
      "title": "SKExternalPurchaseCustomLinkRegions",
      "titleStyle": "symbol",
      "type": "topic",
      "url": "/documentation/bundleresources/information-property-list/skexternalpurchasecustomlinkregions"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/SKExternalPurchaseLink": {
      "abstract": [
        {
          "text": "A dictionary that contains URLs to websites where people using your app can make external purchases for supported regions.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/SKExternalPurchaseLink",
      "kind": "symbol",
      "name": "SKExternalPurchaseLink",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SKExternalPurchaseLink"
        }
      ],
      "role": "symbol",
      "title": "SKExternalPurchaseLink",
      "titleStyle": "symbol",
      "type": "topic",
      "url": "/documentation/bundleresources/information-property-list/skexternalpurchaselink"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/SKExternalPurchaseMultiLink": {
      "abstract": [
        {
          "text": "A dictionary that contains an array of URLs to websites where people using your app can make external purchases.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/SKExternalPurchaseMultiLink",
      "kind": "symbol",
      "name": "SKExternalPurchaseMultiLink",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SKExternalPurchaseMultiLink"
        }
      ],
      "role": "symbol",
      "title": "SKExternalPurchaseMultiLink",
      "titleStyle": "symbol",
      "type": "topic",
      "url": "/documentation/bundleresources/information-property-list/skexternalpurchasemultilink"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/SKIncludeConsumableInAppPurchaseHistory": {
      "abstract": [
        {
          "text": "A Boolean value that determines whether StoreKit includes finished consumable In-App Purchases in transaction information.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/SKIncludeConsumableInAppPurchaseHistory",
      "kind": "symbol",
      "name": "SKIncludeConsumableInAppPurchaseHistory",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SKIncludeConsumableInAppPurchaseHistory"
        }
      ],
      "role": "symbol",
      "title": "SKIncludeConsumableInAppPurchaseHistory",
      "titleStyle": "symbol",
      "type": "topic",
      "url": "/documentation/bundleresources/information-property-list/skincludeconsumableinapppurchasehistory"
    },
    "doc://com.apple.documentation/documentation/StoreKit/Product": {
      "abstract": [
        {
          "text": "Information about a product that you configure in App Store Connect.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Product"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/StoreKit/Product",
      "kind": "symbol",
      "role": "symbol",
      "title": "Product",
      "type": "topic",
      "url": "/documentation/StoreKit/Product"
    },
    "doc://com.apple.documentation/documentation/StoreKit/Product/latestTransaction": {
      "abstract": [
        {
          "text": "The most recent transaction for the product.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "latestTransaction"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:8StoreKit18VerificationResultO",
          "text": "VerificationResult"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:8StoreKit11TransactionV",
          "text": "Transaction"
        },
        {
          "kind": "text",
          "text": ">? { "
        },
        {
          "kind": "keyword",
          "text": "get"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "async"
        },
        {
          "kind": "text",
          "text": " }"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/StoreKit/Product/latestTransaction",
      "kind": "symbol",
      "role": "symbol",
      "title": "latestTransaction",
      "type": "topic",
      "url": "/documentation/StoreKit/Product/latestTransaction"
    },
    "doc://com.apple.documentation/documentation/StoreKit/Transaction": {
      "abstract": [
        {
          "text": "Information that represents the customer’s purchase of a product in your app.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Transaction"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/StoreKit/Transaction",
      "kind": "symbol",
      "role": "symbol",
      "title": "Transaction",
      "type": "topic",
      "url": "/documentation/StoreKit/Transaction"
    },
    "doc://com.apple.documentation/documentation/StoreKit/Transaction/all": {
      "abstract": [
        {
          "text": "A sequence that emits all the customer’s transactions for your app.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "all"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:8StoreKit11TransactionV",
          "text": "Transaction"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:8StoreKit11TransactionV12TransactionsV",
          "text": "Transactions"
        },
        {
          "kind": "text",
          "text": " { "
        },
        {
          "kind": "keyword",
          "text": "get"
        },
        {
          "kind": "text",
          "text": " }"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/StoreKit/Transaction/all",
      "kind": "symbol",
      "role": "symbol",
      "title": "all",
      "type": "topic",
      "url": "/documentation/StoreKit/Transaction/all"
    },
    "doc://com.apple.documentation/documentation/StoreKit/Transaction/id": {
      "abstract": [
        {
          "text": "The unique identifier for the transaction.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "id"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt64V",
          "text": "UInt64"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/StoreKit/Transaction/id",
      "kind": "symbol",
      "role": "symbol",
      "title": "id",
      "type": "topic",
      "url": "/documentation/StoreKit/Transaction/id"
    },
    "doc://com.apple.documentation/documentation/StoreKit/Transaction/latest(for:)": {
      "abstract": [
        {
          "text": "Gets the customer’s most recent transaction for an In-App Purchase.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "latest"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "for"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "internalParam",
          "text": "productID"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": ") "
        },
        {
          "kind": "keyword",
          "text": "async"
        },
        {
          "kind": "text",
          "text": " -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:8StoreKit18VerificationResultO",
          "text": "VerificationResult"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:8StoreKit11TransactionV",
          "text": "Transaction"
        },
        {
          "kind": "text",
          "text": ">?"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/StoreKit/Transaction/latest(for:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "latest(for:)",
      "type": "topic",
      "url": "/documentation/StoreKit/Transaction/latest(for:)"
    },
    "doc://com.apple.documentation/documentation/StoreKit/Transaction/unfinished": {
      "abstract": [
        {
          "text": "A sequence that emits unfinished transactions for the customer.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "unfinished"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:8StoreKit11TransactionV",
          "text": "Transaction"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:8StoreKit11TransactionV12TransactionsV",
          "text": "Transactions"
        },
        {
          "kind": "text",
          "text": " { "
        },
        {
          "kind": "keyword",
          "text": "get"
        },
        {
          "kind": "text",
          "text": " }"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/StoreKit/Transaction/unfinished",
      "kind": "symbol",
      "role": "symbol",
      "title": "unfinished",
      "type": "topic",
      "url": "/documentation/StoreKit/Transaction/unfinished"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "StoreKit",
      "generated": true,
      "identifiers": [
        "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/SKAdNetworkItems",
        "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/SKExternalLinkAccount",
        "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/SKExternalPurchase",
        "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/SKExternalPurchaseCustomLinkRegions",
        "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/SKExternalPurchaseLink",
        "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/SKExternalPurchaseMultiLink"
      ],
      "title": "StoreKit"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "18.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "18.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "18.0",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "15.0",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "18.0",
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "2.0",
              "name": "visionOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "11.0",
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Property List Key"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "SKIncludeConsumableInAppPurchaseHistory"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "typealias"
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SKIncludeConsumableInAppPurchaseHistory"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.bundleresources/documentation/BundleResources",
                "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "StoreKit",
              "generated": true,
              "identifiers": [
                "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/SKAdNetworkItems",
                "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/SKExternalLinkAccount",
                "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/SKExternalPurchase",
                "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/SKExternalPurchaseCustomLinkRegions",
                "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/SKExternalPurchaseLink",
                "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/SKExternalPurchaseMultiLink"
              ],
              "title": "StoreKit"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1SKExternalLinkAccount/title",
          "value": "SKExternalLinkAccount"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1SKExternalLinkAccount/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SKExternalLinkAccount"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1SKExternalPurchaseMultiLink/title",
          "value": "SKExternalPurchaseMultiLink"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1SKExternalPurchaseMultiLink/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SKExternalPurchaseMultiLink"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1SKAdNetworkItems/title",
          "value": "SKAdNetworkItems"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1SKAdNetworkItems/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SKAdNetworkItems"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1SKExternalPurchase/title",
          "value": "SKExternalPurchase"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1SKExternalPurchase/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SKExternalPurchase"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List/title",
          "value": "Information Property List"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "Information Property List"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1SKExternalPurchaseLink/title",
          "value": "SKExternalPurchaseLink"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1SKExternalPurchaseLink/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SKExternalPurchaseLink"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1SKIncludeConsumableInAppPurchaseHistory/title",
          "value": "SKIncludeConsumableInAppPurchaseHistory"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1SKIncludeConsumableInAppPurchaseHistory/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SKIncludeConsumableInAppPurchaseHistory"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1SKExternalPurchaseCustomLinkRegions/title",
          "value": "SKExternalPurchaseCustomLinkRegions"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1SKExternalPurchaseCustomLinkRegions/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SKExternalPurchaseCustomLinkRegions"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/bundleresources/information-property-list/skincludeconsumableinapppurchasehistory"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/bundleresources/information-property-list/skincludeconsumableinapppurchasehistory"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
