{
  "abstract": [
    {
      "text": "A Boolean value that enables the Caps Lock key to switch between Latin and non-Latin input sources.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.bundleresources/documentation/BundleResources",
        "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/TICapsLockLanguageSwitchCapable"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "plist:Information_Property_List.TICapsLockLanguageSwitchCapable",
    "modules": [
      {
        "name": "Bundle Resources"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "TICapsLockLanguageSwitchCapable"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.15",
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Property List Key",
    "symbolKind": "typealias",
    "title": "TICapsLockLanguageSwitchCapable"
  },
  "primaryContentSections": [
    {
      "details": {
        "name": "TICapsLockLanguageSwitchCapable",
        "platforms": [],
        "titleStyle": "symbol",
        "value": [
          {
            "arrayMode": false,
            "baseType": "boolean"
          }
        ]
      },
      "kind": "details",
      "title": "Details"
    },
    {
      "content": [
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Latin input sources, such as ABC, U.S., and Vietnamese, output characters in Latin script. Non-Latin input sources, such as Bulgarian (Cyrillic script), Hindi (Devanagari script), and Urdu (Arabic script), output characters in scripts other than Latin.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "After implementing the key, users can enable or disable this functionality by modifying the “Use Caps Lock to switch to and from” preference, which can be found in System Preferences > Keyboard > Input Sources.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.bundleresources/documentation/BundleResources": {
      "abstract": [
        {
          "text": "Resources located in an app, framework, or plugin bundle.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources",
      "kind": "symbol",
      "role": "collection",
      "title": "Bundle Resources",
      "type": "topic",
      "url": "/documentation/bundleresources"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List": {
      "abstract": [
        {
          "text": "A resource containing key-value pairs that identify and configure a bundle.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List",
      "kind": "symbol",
      "name": "Information Property List",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "Information Property List"
        }
      ],
      "role": "symbol",
      "title": "Information Property List",
      "titleStyle": "symbol",
      "type": "topic",
      "url": "/documentation/bundleresources/information-property-list"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/CFBundleAllowMixedLocalizations": {
      "abstract": [
        {
          "text": "A Boolean value that indicates whether the bundle supports the retrieval of localized strings from frameworks.",
          "type": "text"
        }
      ],
      "ideTitle": "Localized resources can be mixed",
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/CFBundleAllowMixedLocalizations",
      "kind": "symbol",
      "name": "CFBundleAllowMixedLocalizations",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CFBundleAllowMixedLocalizations"
        }
      ],
      "role": "symbol",
      "title": "CFBundleAllowMixedLocalizations",
      "titleStyle": "symbol",
      "type": "topic",
      "url": "/documentation/bundleresources/information-property-list/cfbundleallowmixedlocalizations"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/CFBundleDevelopmentRegion": {
      "abstract": [
        {
          "text": "The default language and region for the bundle, as a language ID.",
          "type": "text"
        }
      ],
      "ideTitle": "Localization native development region",
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/CFBundleDevelopmentRegion",
      "kind": "symbol",
      "name": "CFBundleDevelopmentRegion",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CFBundleDevelopmentRegion"
        }
      ],
      "role": "symbol",
      "title": "CFBundleDevelopmentRegion",
      "titleStyle": "symbol",
      "type": "topic",
      "url": "/documentation/bundleresources/information-property-list/cfbundledevelopmentregion"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/CFBundleLocalizations": {
      "abstract": [
        {
          "text": "The localizations handled manually by your app.",
          "type": "text"
        }
      ],
      "ideTitle": "Localizations",
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/CFBundleLocalizations",
      "kind": "symbol",
      "name": "CFBundleLocalizations",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CFBundleLocalizations"
        }
      ],
      "role": "symbol",
      "title": "CFBundleLocalizations",
      "titleStyle": "symbol",
      "type": "topic",
      "url": "/documentation/bundleresources/information-property-list/cfbundlelocalizations"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/TICapsLockLanguageSwitchCapable": {
      "abstract": [
        {
          "text": "A Boolean value that enables the Caps Lock key to switch between Latin and non-Latin input sources.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/TICapsLockLanguageSwitchCapable",
      "kind": "symbol",
      "name": "TICapsLockLanguageSwitchCapable",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "TICapsLockLanguageSwitchCapable"
        }
      ],
      "role": "symbol",
      "title": "TICapsLockLanguageSwitchCapable",
      "titleStyle": "symbol",
      "type": "topic",
      "url": "/documentation/bundleresources/information-property-list/ticapslocklanguageswitchcapable"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Localization",
      "generated": true,
      "identifiers": [
        "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/CFBundleDevelopmentRegion",
        "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/CFBundleLocalizations",
        "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/CFBundleAllowMixedLocalizations"
      ],
      "title": "Localization"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.15",
              "name": "macOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Property List Key"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "TICapsLockLanguageSwitchCapable"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "typealias"
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "TICapsLockLanguageSwitchCapable"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.bundleresources/documentation/BundleResources",
                "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Localization",
              "generated": true,
              "identifiers": [
                "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/CFBundleDevelopmentRegion",
                "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/CFBundleLocalizations",
                "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/CFBundleAllowMixedLocalizations"
              ],
              "title": "Localization"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1TICapsLockLanguageSwitchCapable/title",
          "value": "TICapsLockLanguageSwitchCapable"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1TICapsLockLanguageSwitchCapable/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "TICapsLockLanguageSwitchCapable"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1CFBundleAllowMixedLocalizations/title",
          "value": "CFBundleAllowMixedLocalizations"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1CFBundleAllowMixedLocalizations/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CFBundleAllowMixedLocalizations"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1CFBundleDevelopmentRegion/title",
          "value": "CFBundleDevelopmentRegion"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1CFBundleDevelopmentRegion/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CFBundleDevelopmentRegion"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List/title",
          "value": "Information Property List"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "Information Property List"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1CFBundleLocalizations/title",
          "value": "CFBundleLocalizations"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1CFBundleLocalizations/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CFBundleLocalizations"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/bundleresources/information-property-list/ticapslocklanguageswitchcapable"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/bundleresources/information-property-list/ticapslocklanguageswitchcapable"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
